{1}{1}25.000
{1798}{1897} MRAVATOR 
{2451}{2528}To je to! Spindle, stražnja svjetla.
{2773}{2820}Hej. Hej!
{2824}{2884}- Što? | - Kako to misliš "što"?
{2888}{2944}Hej! Hej, što radiš?
{2948}{3036}Da, ovo je odaja za spavanje. | Spavaj.
{3040}{3084}Nemoj da ti doðem gore!
{3088}{3201}Oprostite, no moram imati | posljednji sastojak za svoj napitak.
{3205}{3246}Što je važnije:
{3250}{3392}Da ja završim svoje životno djelo | za spas kolonije...
{3396}{3440}...koja ukljuèuje i vas...
{3444}{3495}...ili da vi spavate?
{3499}{3561}- Ja sam za spavanje. | - Da, ovo drugo.
{3565}{3642}Onda æu pokušati biti jako tih.
{3646}{3688}Klikiti-klok!
{3748}{3833}Dosta je, idem gore!
{3872}{3912}Vatreni kristali.
{3932}{4017}Napokon. Posljednji sastojak.
{4122}{4176}Na odmoru sam.
{4247}{4310}- Ne. Ne, prestani. | - Hrpa.
{4314}{4360}Hrpa.
{4465}{4499}To je Razaraè!
{4639}{4681}Atomski klin.
{4704}{4738}I èisto izvlaèenje.
{4742}{4796}- Èisto. Sjajan klin. | - Bravo.
{4800}{4863}Hajde, stari, | ponestaje mi rublja.
{4867}{4923}I što æeš napraviti? | Ništa.
{4927}{5043}- Jer sam ja velik, a ti mali. | - Da.
{5047}{5169}- Jer je on velik, a ti mali. | - Hej.
{5173}{5238}Prestani ponavljati | sve što kažem.
{5242}{5291}Samo sam htio naglasiti.
{5295}{5361}Zašto moraš mrziti?
{5770}{5797}Razaraè.
{6138}{6165}Zoc?
{6190}{6229}Voda!
{6233}{6283}- Zoc. | - Hova, idi u travu.
{6287}{6320}Ovdje je opasno.
{6324}{6384}Ali želim ljude vidjeti izbliza.
{6388}{6444}Èujem da mogu govoriti, | kao i mi.
{6448}{6512}Oni nisu poput nas.
{6652}{6722}Što æete napraviti, mravi? | Ništa.
{6726}{6812}Jer sam ja velik, a vi mali.
{6816}{6934}Bježi, èudovište, ili æu upotrijebiti | svoje moæi da te uništim.
{7014}{7097}Moæi koje tek trebam usavršiti. Bježi!
{7295}{7325}Zdravo.
{7329}{7410}Ne želimo te ozlijediti.
{7414}{7446}- Sjajno. | - Cipela!
{7450}{7492}Cipela!
{7644}{7723}- Molim, idi u miru. | - Pazi!
{7828}{7929}- Jesi dobro? | - Valjda me nije èuo.
{7955}{8000}Lucas.
{8004}{8059}Kikirikiæu, vrijeme je da uðeš.
{8227}{8276}Kikirikiæ.
{8292}{8352}Mislim da sam doprla do njega.
{8356}{8445}- Što misliš? | - Razaraè.
{8465}{8494}Zalij vrt! | Mama i tata
{8498}{8552}Tiffany, Lucas, idemo.
{8558}{8622}Lucas? | Svi su brojevi na hladnjaku.
{8626}{8712}- Dobra. Produžena igra. | - Lucas.
{8732}{8820}Što radiš tamo? | Zašto mi se ne javljaš?
{8832}{8882}- Jesi dobro, dušo? | - Da.
{8886}{8968}- Samo sam se igrao s prijateljima. | - Ne znam.
{8972}{9059}- Možda da ne idemo na odmor. | - Godišnjica nam je.
{9063}{9105}Idemo u Puerco Vallartu.
{9109}{9223}I moram provesti malo kvalitetnog | vremena s mamacitom.
{9240}{9299}Ne otkazujte odmor | zbog mene.
{9303}{9399}- Mogu sam riješiti svoje probleme. | - Probleme? Kakve probleme?
{9403}{9475}Ima li to veze s nestankom | tvog veša?
{9479}{9508}Ne!
{9512}{9584}Ne moraš se sramiti piškenja | u krevet.
{9588}{9633}Što? | Samo prestani, mama!
{9637}{9711}Jedini je problem | što me tretiraš kao bebu.
{9725}{9797}- Kikirikiæu. | - I prestani me tako zvati.
{9801}{9864}Samo idite i pustite me na miru.
{9976}{10040}Ja, Zoc, zovem elemente:
{10044}{10160}Vjetar koji puše, kišu koja pada, | vatru koja gori.
{10164}{10264}Pošaljite svoje sjajne moæi | i pretvorite moj napitak.
{10268}{10310}Klikiti-klok!
{10395}{10444}To je bilo sjajno, dušo.
{10448}{10532}Super su dimni efekti. | Zar ne, Spindle?
{10546}{10578}Ti...
{10582}{10627}...kamenu. | Proklinjem ti djecu.
{10631}{10694}Mislim da kamenje | nema djece, dušo.
{10721}{10802}- Sada neæe. | - Dobro. Što ne valja?
{10806}{10861}Napitak treba | promijeniti boju.
{10865}{10948}Ne mijenja boju. | Ne mijenja boju.
{10952}{11008}Pozvao sam elemente: | Vjetar, kišu itd.
{11012}{11072}Pretvori moj napitak i klikiti-klok.
{11142}{11200}Klikiti-klok, klikiti-klok...
{11228}{11303}- Možda je krivo izgovaraš. | - Kako mogu?
{11307}{11382}- Ja sam je smislio. | - Uzmi pauzu.
{11386}{11427}Hova, možda nisi uoèila...
{11431}{11527}...no danas smo bili skoro zgnjeèeni, | a kolonija se raspada.
{11531}{11629}Ovako sam blizu pronalasku rješenja | za ljudski problem...
{11633}{11695}...a ti mi kažeš da... | Što radiš?
{11699}{11747}- Ništa ne radim. | - Èekaj.
{11751}{11796}- Ne. | - Samo hodam ka tebi.
{11800}{11853}- Nema razloga za paniku. | - Èekaj.
{11857}{11916}- Samo idem prema tebi. | - Èekaj. Ne.
{11920}{11975}Škaklja te? A ovo?
{11979}{12025}Zašto se smiješ? | Vidim te.
{12029}{12079}Nemoj da te klikiti-kloknem.
{12083}{12184}Drago mi je da se vas dvoje imate | èemu smijati.
{12218}{12271}- Šefe odbora. | - Bok.
{12275}{12356}Lijepo od vas što ste... | Nismo vas oèekivali.
{12360}{12423}Oprostite. | Radio sam na eksperimentu.
{12427}{12480}Da, razumijem.
{12484}{12569}Pa, mi smo... | Kako vam mogu pomoæi?
{12573}{12651}Zoc, Razaraèevi napadi | postali su uèestaliji.
{12655}{12721}Zalihe hrane su oèajno slabe.
{12725}{12837}Odbor se nadao da možda | ti imaš rješenje.
{12860}{12924}Uzvratimo. | Moramo zaustaviti Razaraèa.
{12928}{12984}Tisuæe mrava bi | nepotrebno umrlo.
{12988}{13077}Možda da razgovaramo s ljudima.
{13081}{13167}Kakva sjajna zamisao! | Idemo èavrljati.
{13171}{13250}"Bok Razaraèu. | Uh, izgledaš malo umorno.
{13254}{13314}Odmori svoje noge | na mojoj djevojci."
{13318}{13348}Dobro.
{13352}{13411}Ponekad si prava smrdibuba, znaš?
{13415}{13539}Zoc, rat s ljudima je... | To je nemoguæe.
{13543}{13650}Èarobnjak ne poznaje tu rijeè.
{13755}{13836}- Svejedno. | - Bok, Tiff. Bok, Lucas.
{13840}{13898}Volim vas.
{13942}{13993}Èuvajte baku!
{13997}{14052}Dobro, bok. Zabavite se.
{14056}{14132}Ne brinite, sve je pod kontrolom.
{14258}{14306}Malo pomoæi, molim.
{14310}{14372}Mislim da je tvoj red.
{14376}{14424}Zubi u travi.
{14456}{14553}Mommo, gdje ti je...? | Što radiš?
{14557}{14656}Sprjeèavam otmicu vanzemaljaca, | eto što radim.
{14660}{14708}Hvala.
{14746}{14801}Vražji korov.
{14805}{14912}Vidiš? Strujanje zraka. Vanzemaljci | mrze strujanje zraka.
{14929}{15040}Izluðuje ih. I ako usred noæi probaju | iskljuèiti struju...
{15091}{15153}...ove bebice æe me probuditi.
{15157}{15257}- Moramo biti spremni. Reci prijateljima. | - Nemam prijatelja.
{15261}{15320}Pa, tko æe te paziti kad ostariš...
{15324}{15420}...i kad ti zubi budu ispadali, | a love te vanzemaljci?
{15424}{15512}- Lucas. | - Sam æu se paziti.
{15548}{15621}- Laku noæ, Mommo. | - Noæ. Lijepo spavaj.
{15625}{15674}Ne daj da te bube gnjave...
{15678}{15755}...da ti uðu u uho | i stave jajašca u mozak.
{16109}{16195}- Pleši Pukas. | - Pleši, majmunèiæu, pleši!
{16209}{16251}Misli brzo.
{16255}{16300}BADA-BOMBA
{16776}{16817}Klikiti-klok.
{16896}{16938}Ti...
{16942}{17006}Zoc, molim te, ne pred Spindleom.
{17040}{17077}Oprosti.
{17102}{17191}Bože, sigurno sam nešto propustio.
{17198}{17247}Èekaj. Pukotina.
{17251}{17325}To je to. Nesavršenost kristala.
{17329}{17399}Možda da ih umoèim u | viskoznu mješavinu.
{17403}{17450}Spindle. Smola.
{17654}{17684}Klikiti-klok.
{17810}{17924}To je to. Uspjelo je! | Napitak je gotov!
{17936}{18050}Slava Majci! Da! Da! Da!
{18054}{18088}Ne!
{18135}{18207}- Zoc! | - Hova, drži se.
{18217}{18302}Spindle, donesi napitak. Brzo.
{19022}{19072}Zdravo.
{19105}{19235}Da, bio sam tvojih godina kad | sam potopio prvu koloniju.
{19243}{19349}Èovjeèe, to su bila dobra vremena. | Dobra vremena!
{19377}{19455}- Tko ste vi? | - Zovem se Stan Beals.
{19459}{19500}Beals-Buba | protiv nametnika.
{19504}{19533}Beals-Buba | Osnovana '76.
{19537}{19602}Tamanitelj, istrebljivaè. | Negator svih problema.
{19606}{19671}Hej, ti si sigurno Nickleov deèko?
{19675}{19724}Tvoj me je tata pozvao...
{19728}{19791}...no zaboravio je | potpisati ugovor.
{19795}{19866}Zaposlen je. Puno stvari na umu. | Dogaða se.
{19870}{19944}Rekao mi je da razgovaram s tobom...
{19949}{20019}- Lucas. | - Da, Lucas.
{20023}{20113}Rekao je: "Neka moj sin Lucas | potpiše ugovor za mene...
{20117}{20214}...ako ja sluèajno zaboravim. | On je sada odrastao."
{20218}{20266}Njegove rijeèi.
{20293}{20363}Ne znam. Imate li | neke preporuke?
{20379}{20425}Preporuke?
{20429}{20472}Evo jedne.
{20516}{20572}Ne mislim da bih smio.
{20596}{20696}Ne misliš da bi smio? | Ne misliš?
{20700}{20785}Tko misli umjesto tebe? | Tvoja mamica?
{20789}{20848}"Mamice, mamice, mamice, | što æu?
{20852}{20921}Ja sam bebica, ne mogu | misliti za sebe.
{20925}{20968}Obriši mi guzu.
{20972}{21070}Obriši me. Molim te, obriši me."
{21097}{21195}- Dajte mi taj glupi ugovor. | - Da. Jako zrela odluka.
{21199}{21257}U svijetu bez buba uživajte vi
{21261}{21358}Samo potpišite ovdje | I ubijanje prepustite meni
{21362}{21408}Ja sam to napisao.
{21756}{21817}- Jesi dobro? | - Jesam.
{21821}{21894}Spindle? Spindle?
{21927}{21998}Spindle. Spasio si ga.
{22015}{22054}Doði ovamo.
{22058}{22130}Netko æe dobiti | dodatni pljesnivi korijen.
{22134}{22185}- Dobro, dobro. | - Zoc.
{22249}{22308}Spindle, svjetlo.
{22476}{22552}- Majko, pomozi nam. | - Ne.
{22556}{22645}Da nas napadnu bez provokacije, | bez razloga...
{22649}{22750}...samo zato što oni mogu, to je... | To je divljaèki.
{22769}{22826}Ali što možemo?
{22837}{22891}Izgubljeni smo.
{22904}{22976}Ne. Spašeni smo.
{22980}{23055}Ovo je naš spas.
{23059}{23110}Napitak?
{23114}{23224}Što li... toèno radi?
{25249}{25297}Žaboletaèi.
{25428}{25460}Hej, hej.
{25589}{25654}SIDOVA MORSKA SOL | ÈIPS
{25926}{26006}Èovjeèe. Poði s nama.
{26144}{26198}Iš. Iš. Mièi se. Mièi se.
{26202}{26277}Imam ventilator. Vjetrovita sam.
{26300}{26341}Ja jesam vjetrovita.
{26436}{26481}Halo?
{26485}{26530}Halo?
{26698}{26784}Skeniram. Skeniram. Skeniram.
{26802}{26850}Ne! Hajde! Prestanite!
{26854}{26939}Zašto nisi u krevetu, | maleni Lucase?
{27196}{27264}Što ste mi napravili? | Pustite me!
{27942}{28003}Odvratno. Hej, prestanite.
{28404}{28484}Spustite me! Hej. Prestanite. | Spustite me.
{28605}{28635}Spustite me!
{28778}{28818}Što je to? Smrdi.
{28822}{28903}- To je èovjek. | - Kikirikiæ. Razaraè.
{28958}{29004}Bože.
{29008}{29082}- Dobro, Kikirikiæu, ovuda. | - Malen je.
{29086}{29118}- Što je to? | - Dodirni.
{29122}{29147}- Ne diraj. | - Hej.
{29151}{29222}- Pikni ga. | - Tako je mekan.
{29226}{29332}- Kostur mu je unutra. | - Naopak je?
{29495}{29561}Kamo me vodite? Upomoæ!
{29606}{29679}Tko ste? Što ste mi napravili? | Pustite me!
{29745}{29776}Èovjeèe...
{29794}{29865}...doveden si pred odbor...
{29869}{29960}...zbog optužbe za zloèine | protiv kolonije.
{29964}{29995}Èujmo optužbe.
{30014}{30069}"Ova zvijer | èovjek-uništavaè...
{30073}{30153}...nadalje odreðen kao | Kikirikiæ Razaraè...
{30157}{30222}...voljno je i | s predumišljajem...
{30226}{30290}...uništio ostave...
{30294}{30352}...poplavio odaje za jajašca...
{30356}{30490}...i smoèio koloniju | strašnom žutom kišom."
{30494}{30543}Hej, hajde, bilo mi je sila.
{30575}{30654}Presudu èovjeku donijet æe...
{30658}{30722}...sama Kraljica.
{30938}{31029}Pozdrav, djeco moja...
{31033}{31138}...i našem neobiènom gostu...
{31142}{31268}...èovjeku koji prijeti samom | postojanju naše kolonije.
{31272}{31344}Èekajte malo! Èekajte, èekajte. | Time-out.
{31348}{31449}Kako da znam da mravi imaju | osjeæaje, obitelji ili suðenja?
{31453}{31544}- Vi ste samo hrpa glupih mrava. | - Razorimo Razaraèa!
{31548}{31609}- Baci ga u rupu. | - Pojedimo ga!
{31613}{31703}Ne, èekajte. Mi nismo | bezobzirni divljaci.
{31707}{31758}Ovog èovjeka treba prouèiti.
{31762}{31800}- A onda pojesti. | - Da.
{31804}{31877}Pojesti! Pojesti! Pojesti!
{31887}{31949}Mir. Mir.
{31959}{32011}Budite mirni.
{32015}{32102}Veèeras imamo izbor.
{32106}{32235}Možemo uništiti ovog èovjeka | i ovaj dan uèiniti sigurnim.
{32239}{32354}Ili možemo promijeniti | prirodu ovog èovjeka...
{32358}{32494}...i možda stvoriti svjetliju | buduænost za nas mrave.
{32498}{32620}Stoga osuðujem ovog èovjeka | na život i rad u koloniji...
{32624}{32747}...da nauèi naše obièaje. | On mora postati mrav.
{32764}{32846}- Što? | - Ne. Ne, moja Kraljice.
{32856}{32956}Što ako ne postane mrav?
{32960}{33015}Dobro, mislim, hajde.
{33024}{33088}To bismo mogli požaliti.
{33109}{33183}Ali... | Tko æe ga nauèiti našim obièajima?
{33210}{33270}- Ja. | - Hova?
{33274}{33309}Dogovoreno.
{33313}{33387}Nastavimo s poslom.
{33417}{33477}To je to? | Koliko æu biti ovakav?
{33481}{33512}Želim iæi kuæi.
{33516}{33558}Èekajte. | To je neljudski.
{33583}{33645}Da, jest.
{33715}{33767}Zdravo, Kikirikiæu.
{33786}{33835}Razaraèu?
{33844}{33901}Zdravo? Moramo iæi.
{33916}{33975}Vrijeme je da poèneš obuku.
{33997}{34043}Gdje si?
{34151}{34178}Jednostavno je.
{34182}{34256}Moram proæi kraj straže, | uz hrpu zemlje...
{34260}{34332}...i paziti da me ništa ne pojede. | - Bok.
{34336}{34392}Milijun stvari te | želim pitati.
{34396}{34468}Kad si se izlegao? Jesi...? | Muško ili žensko?
{34480}{34519}I u èemu je razlika?
{34523}{34591}Je li...? Tako?
{34595}{34698}Hej, prestani viriti. | Ili æu stati na tebe.
{34702}{34792}Ja ne bih, da sam ti. | Ja sam ti jedini prijatelj.
{34796}{34824}Pojest æeš me.
{34833}{34911}Sad kad si spomenuo, | izgledaš mekano...
{34915}{34974}...no obeæala sam kraljici da neæu.
{35008}{35038}Tako ti srca?
{35042}{35081}Što? Dobro.
{35085}{35133}Tako mi srca, neæu.
{35152}{35204}Rekoh, srca, ne guze.
{35208}{35251}Da.
{35255}{35308}Evo, napravih opet.
{35312}{35342}Èudan obièaj.
{35352}{35387}Ipak ne idem.
{35391}{35461}- Kikirikiæu, trebaš... | - Zovem se Lucas.
{35465}{35507}Lucas.
{35511}{35584}Pa, Lucas. Èuo si kraljicu.
{35588}{35652}Moraš postati mrav | ako želiš kuæi.
{35656}{35703}A kako da to napravim?
{35707}{35768}Moraš naæi svoje mjesto | u koloniji.
{36017}{36104}Pa, Lucas, | imaš neke posebne vještine?
{36108}{36167}Iz sestrinog nosa | potjeram mlijeko.
{36171}{36262}Dobro, probajmo skupljanje hrane.
{36266}{36314}Instruktorica mi je prijatelj.
{36318}{36369}Bit æe joj drago pomoæi.
{36373}{36426}Kikirikiæ? Razaraè?
{36430}{36481}Otišla sam iz gnijezda | zbog tebe.
{36485}{36524}Sve sam izgubila.
{36528}{36582}Cijelo jutro sam gradila.
{36586}{36698}Hova, nemoj mi reæi da si | mentorica ovom... Ovom... Ovom...
{36711}{36753}Zove se Lucas.
{36800}{36881}Zašto je pokriven smeæem? | Ja ne poduèavam luðake.
{36885}{36970}Ne, ne, ne. On smeæe zove "odjeæa".
{36974}{37023}Vole kriti spolne osobine.
{37043}{37092}On je mužjak.
{37116}{37185}Dobro, Lucas, u plavom si timu.
{37189}{37229}- Nije fer. | - Ma daj!
{37233}{37282}Hej, hej, hej, tišina.
{37286}{37349}I uvuci prsni koš.
{37353}{37457}Kao i sve u koloniji i skupljanje hrane | je timski rad.
{37461}{37606}U ovom testu svaki tim djeluje kao | jedinka da bi izbjegao prepreke...
{37610}{37700}...donio ovaj slatki kamen i | vratio se u gnijezdo.
{37704}{37777}Nijedan mrav ne smije zaostati.
{37781}{37820}Prvi koji se vrati | pobjeðuje.
{37824}{37871}Ima pitanja?
{37968}{38031}- Zdravo, mala. | - Fugax.
{38035}{38131}Zar nije istina da mravi izviðaèi, | kao ja...
{38135}{38242}...vode uzbudljiv život prepun | avantura i intriga.
{38253}{38337}- Fugax! | - Dok skupljaèi hrane, kao vi...
{38341}{38418}...samo šeæu i skupljaju štapiæe.
{38476}{38505}Pitanja, itko?
{38509}{38561}- Gospodine? | - Tip s iskrivljenom vilicom.
{38565}{38602}Kakve avanture?
{38606}{38663}Drago mi je da si pitao.
{38667}{38748}- Fugax. | - Okupite se, mladi izviðaèi.
{38752}{38885}U svojim putovanjima išao sam mnogo | dalje od velikog plosnatog kamena.
{38921}{38959}Misliš, na ulicu?
{38971}{39038}Ne. Veliki plosnati kamen...
{39042}{39163}...gdje ljudi jašu u ogromnim | metalnim èahurama.
{39172}{39203}Autima.
{39223}{39254}Pitao sam te nešto?
{39258}{39312}Tko je pozvao kvaritelja zabave?
{39316}{39361}Fugax, upoznaj Razaraèa.
{39365}{39399}Razaraè?
{39573}{39645}Ima li drugih...?
{39698}{39778}Ima li još pitanja u vezi | vašeg zadatka?
{39782}{39851}Da, što je slatki kamen?
{39855}{39892}Krenite!
{40053}{40088}- Most. | - Na hrpu.
{40092}{40127}Most, tako je.
{40131}{40160}Hajde, Kikirikiæu.
{40164}{40240}Ja to mogu sam.
{40330}{40389}Hej, deèki. Mislim da je mrtav.
{40404}{40450}Nisam mrtav.
{40460}{40517}- Ljestve. | - Ljestve, tako je.
{40527}{40583}- Hajde. | - Uhvati se.
{40587}{40634}Ne trebam vašu pomoæ.
{40638}{40688}Trebam vašu pomoæ!
{40692}{40744}Bok, gubitnici.
{40758}{40800}Hajde.
{40873}{40928}- Dobro. | - Požuri, èovjeèe.
{40932}{40961}Zbog tebe gubimo.
{40965}{41020}Hej. Imam samo dvije noge.
{41048}{41099}Idi, Dvonožni, idi.
{41103}{41134}Idi, Lucas.
{41138}{41193}- Izvor. | - Izvor, tako je.
{41197}{41244}Tako je.
{41279}{41327}Time-out.
{41331}{41377}Mislim da to ne mogu...
{41381}{41409}Dobro.
{41464}{41537}- Pustite me! | - Ne puštaj!
{41547}{41587}Pozlit æe mi.
{41591}{41630}Ne puštaj.
{41634}{41686}- Puštam. | - Ne puštaj!
{41763}{41788}Pustio je.
{41939}{42004}- Bombonèiæ? | - To, Lucas.
{42008}{42050}Dobro razmišljanje.
{42068}{42112}Praæka, tako je.
{42309}{42373}- Bravo, Lucas. | - Kikirikiæu, zakon si.
{42377}{42452}- Hajde, gubimo. Idemo. | - Dobar posao.
{42456}{42494}- Pobijedili smo? | - Skoro.
{42498}{42568}Moramo prenijeti slatki kamen | preko cilja.
{42572}{42601}Hajde, idemo.
{42634}{42690}Požuri, Kikirikiæu.
{42699}{42765}Da, baš.
{42769}{42815}Požuri Lucas, popni se.
{42819}{42849}Brzo se penji.
{42853}{42883}Stižu nas.
{42892}{42932}Bok, gubitnièe.
{42936}{42973}Popni se uz zid.
{43002}{43045}Hajde. Popni se uz zid.
{43049}{43088}Hajde.
{43105}{43159}Zaboravi. | Igra je namještena.
{43173}{43211}- Ljestve. | - Tako je.
{43215}{43310}Hajde. Idemo. Idi, idi, idi.
{43314}{43361}Uspjeli smo. Da, èovjeèe.
{43365}{43400}Crveni su zakon.
{43456}{43491}Crveni su pobijedili.
{43500}{43568}Dobro. Uspjeli smo.
{43627}{43681}Hvala na trudu.
{43963}{44012}Lucas, bio si dobar, doista.
{44016}{44074}Samo moraš pronaæi mrava u sebi.
{44078}{44135}Prvo zamisli da imaš | šest nogu.
{44139}{44189}- I... | - Kako æe me to dovesti kuæi?
{44193}{44253}Pogledaj me. | Ja nisam glupi mrav.
{44257}{44349}Biti mrav nije samo imati | šest nogu, dizati 10 puta...
{44353}{44434}...više nego težiš | ili se vertikalno penjati...
{44438}{44523}...to znaèi biti dio kolonije. | Ne misliti prvo na sebe.
{44527}{44582}- Pazi. | - Hej, ne diraj me.
{44586}{44636}Pokušavam ti pomoæi.
{44640}{44672}A meni je lako?
{44676}{44730}Biti Razaraèeva pomagaèica?
{44734}{44827}Ti se brini za sebe, | a ja æu za sebe.
{44836}{44876}O, Lucas.
{44880}{44920}Mravi nisu takvi.
{44924}{45001}Hova, ja sam takav.
{45005}{45072}Ako bih samo mogla...
{45114}{45143}Što?
{45154}{45229}Halo? Zemlja dami mrav.
{45233}{45289}Gotovo da zvuèimo | kao moja mama.
{45300}{45358}Dolaze. Bježi!
{45384}{45431}Hej. Hej! Što ne valja?
{45577}{45641}- Love èopor. | - Kakav èopor?
{45698}{45734}Hej, polako, curo.
{45738}{45780}Polako.
{45838}{45879}U zaklon.
{45941}{45990}Reci kraljici da je volim.
{46029}{46065}Odsjeèeni smo.
{46156}{46260}Hajde, braæo, za kraljicu i koloniju.
{46449}{46494}U travu.
{46507}{46539}Formacija za napad.
{46548}{46591}Napuni ih.
{46652}{46724}- Neprijateljska vatra. | - Pazi na krilo.
{46728}{46779}- To peèe. | - Lijep pogodak.
{46818}{46852}Moj red.
{46862}{46906}- Hvala. | - Gdje je Hova?
{46910}{46952}Ne znam.
{46956}{46994}Hajde.
{47004}{47066}Na položaje. Priprema.
{47112}{47150}Prskanje.
{47361}{47427}Nemojte. | Samo sam slijedio naredbe.
{47461}{47490}Tko želi èaroliju?
{47494}{47535}Klikiti-klok.
{47657}{47692}Izgledaš ukusno.
{47696}{47729}Pusti ga na miru.
{47799}{47853}Hova? | Brzo, mièi mi se s puta.
{47857}{47885}Mièi se.
{47889}{47946}- Hova! | - Požurite.
{47950}{47984}Svi, u travu.
{47996}{48045}Ne stoj samo. Pomozi joj.
{48069}{48112}Lucas, bježi.
{48116}{48145}Što radiš?
{48254}{48290}Svi, u travu.
{48884}{48929}Gdje si...
{48933}{48979}...malena bubice?
{49311}{49349}BADA-BOMBA
{49469}{49526}Molim te, požuri. | Svjetlo, svjetlo.
{49588}{49642}Svjetlo, svjetlo.
{49896}{49922}Hova, dolje.
{49948}{49987}Zoc.
{50108}{50160}Ne!
{50195}{50231}Stani, hej! Ne, ne.
{50472}{50504}Vatra u rupi!
{50720}{50773}- Što je to? | - Kupanje.
{50777}{50804}Povlaèenje.
{51092}{51119}Odlaze.
{51123}{51154}Pobijedili smo.
{51237}{51297}Živio Razaraè!
{51301}{51336}Kikirikiæ! Kikirikiæ!
{51340}{51374}Sjajno. Genijalno.
{51378}{51414}Lucas je napravio:
{51418}{51477}A onda... su svi odletjeli.
{51481}{51536}Sada znam zašto te | zovu Kikirikiæ.
{51540}{51620}Ima mozak velièine kikirikija.
{51624}{51664}Lucas Razaraè.
{51673}{51737}Povlaèim sve što sam | mislila o tebi.
{51741}{51778}Spasio si nas.
{51788}{51837}Hvala ti, Lucas.
{51841}{51907}Da, naravno.
{51936}{51981}On nas je spasio.
{51985}{52078}Tako je oèito. Tako sam glup.
{52082}{52143}Slava Razaraèu.
{52147}{52203}Probudite se! | On je sebe spasio.
{52228}{52256}Mi ostali...
{52276}{52330}...smo samo bili ovdje.
{52341}{52393}Zoc. Jesi dobro?
{52397}{52432}- Ne... | - Što je bilo?
{52436}{52473}Dobro sam. Dobro.
{52477}{52532}- Ozlijeðen si. | - Ma, to nije ništa.
{52536}{52580}Zoc, imaš sok od juke?
{52584}{52661}Lucas ima opeklinu. Jadnièak.
{52684}{52752}Ovo je naš neprijatelj.
{52761}{52846}Oni ne spašavaju mrave, oni ih ubijaju.
{52850}{52909}Mene je gotovo ubio.
{52933}{52985}Ili ti to nije važno?
{53214}{53298}Volim ja, voliš ti | Mednu rosu volimo svi
{53302}{53338}Veèera je poslužena.
{53342}{53377}A ja sam desert.
{53381}{53444}A ja sam na dijeti.
{53448}{53504}I znaš, dobro ti stoji.
{53508}{53548}Lucas, na èemu radiš?
{53552}{53577}Na naoèalama.
{53637}{53705}Ovo je neka dobra medna rosa.
{53752}{53835}Lucas, moraš je probati. | Jako je dobra.
{53877}{53905}Hajde.
{54036}{54068}Ovo je sjajno.
{54072}{54132}Okusa je kao žvaka | od zelene jabuke.
{54289}{54348}Brzo su otišli. | Još jedna runda?
{54352}{54387}Da, samo daj.
{54773}{54824}Uzmi dok je vruæe.
{54867}{54945}Hej, nisam znao da ljudi | mogu mijenjati boje.
{54949}{54994}- Ludilo. | - Možda je...
{54998}{55056}...pojeo previše medne rose.
{55178}{55217}Evo, pojedi ovo.
{55221}{55254}Bit æe ti bolje.
{55286}{55338}Iz èega je to izašlo?
{55353}{55384}To je korijen.
{55388}{55485}Zoc je otkrio njene moæi da izgna zlo | i stvori dobro.
{55512}{55563}On je sjajan èarobnjak.
{55567}{55616}Da, on me mrzi.
{55620}{55656}Hej, stvarno, zar ne?
{55660}{55701}Mislim, mrzi te do srži.
{55705}{55770}Zadivljujuæe je koliko mrzi | tvoju srž.
{55774}{55804}Dobro, žao mi je.
{55808}{55900}Da, Zoc ima problema s bijesom, | osobito prema ljudima...
{55904}{55940}...no pravi je mrav.
{55949}{56022}Tvrd izvana, no mekan iznutra.
{56032}{56092}Samo mu daj vremena, Lucas.
{56530}{56565}Slava Majci.
{56594}{56643}Slava Majci.
{56676}{56715}Hvala.
{56719}{56780}Koja je to majka | o kojoj govorite?
{56784}{56809}Kraljica?
{56813}{56868}Ne, Lucas, Majka mrav.
{56877}{56916}Kraljica nad kraljicama.
{56920}{56987}Rodila je prvu koloniju.
{56991}{57056}Sve mrave.
{57060}{57143}Hajde. Vrijeme je da vidiš.
{57507}{57612}Ovo je Odaja vjekova.
{57692}{57727}Što je to?
{57736}{57820}Oni prièaju prièu o našoj | koloniji, našu povijest.
{57824}{57880}Fora su.
{58152}{58233}Ovo je slika Majke mrav.
{58304}{58378}Piše da æe se jednoga dana vratiti...
{58382}{58475}...i da æe medna rosa | teæi s neba kao kiša.
{58479}{58560}I nikada više neæemo biti gladni.
{58564}{58628}Želite da topla kakica | padne s neba?
{58632}{58720}Da. To bi bio blagoslovljen dan.
{58730}{58799}Oprosti, tako je predivno.
{58809}{58873}Hej, što je ovo?
{58877}{58918}Zlo.
{58935}{58981}Oblakodah.
{58990}{59064}Drevna je, naslikana prije našeg doba.
{59068}{59198}Nitko nije siguran što je to, | osim da ga slijedi smrt.
{59202}{59280}Prièa za plašenje | zloèestih kukuljica.
{59310}{59376}Ne, tamanitelj.
{59380}{59411}Moram mu otkazati.
{59415}{59449}Moram sada kuæi.
{59453}{59486}Ali još nisi mrav.
{59496}{59544}- Na brzinu. | - Nema šanse.
{59548}{59596}Ljudsko gnijezdo je zabranjeno.
{59621}{59656}Pa...
{59676}{59725}Kolonija treba hranu?
{59729}{59766}Hranu?
{59770}{59837}Da, slatko kamenje. | Moja ih je kuæa puna.
{59841}{59924}- Raznih boja i okusa. | - Raznih okusa?
{59928}{59959}Èak i zelenih?
{59963}{60024}Pa, trebat æeš izviðaèa.
{60028}{60073}Ne. Nema šanse | da æete me...
{60077}{60137}- Može. | - Hajde.
{60163}{60218}Bolje da ima i crvenih.
{60303}{60356}Hej, ovo je veliko gnijezdo.
{60360}{60427}Trebalo je tisuæu ljudi | da ga sagradi.
{60431}{60484}- Što je to? | - Samo vrata.
{60488}{60548}Vrata? Fantastièno.
{60557}{60611}Svi gosti prolaze | ispod vrata?
{60615}{60707}Pa, zapravo, vi ste prvi prijatelji | koji su mi došli.
{60711}{60752}Mi smo prvi?
{60756}{60822}Mi smo prvi koji su | prošli ispod vrata.
{60826}{60877}- Izvrsno. | - I kad pomisliš...
{60881}{60964}...da je sve napravljeno od | vlastite kakice.
{60971}{60999}Lijepo.
{61030}{61112}Zašto je mama morala | staviti debeli tepih?
{61116}{61181}Trebat æe nam dani da doðemo | do kuhinje.
{61185}{61269}Isuse, šteta.
{61273}{61364}Sad moramo kuæi prije nego | upadnemo u nevolje.
{61425}{61455}Ne.
{61483}{61524}Èekajte.
{61624}{61655}Hajde.
{61659}{61703}Ovo se zove zmajarenje.
{61741}{61811}Jesi to ikad radio?
{61815}{61844}Igrao sam igricu.
{61848}{61909}Kad dam znak, svi skoèite.
{62010}{62047}Sad.
{62122}{62175}Oprosti, to je bio znak?
{62179}{62231}- Stižem. | - Hej, hej, pazi.
{62235}{62308}Za kraljicu i koloniju.
{62312}{62361}Bože.
{62492}{62592}- Pravi se važan. | - Sjajno. Da.
{62641}{62693}Havaji. | Bili smo prošlo ljeto.
{62697}{62777}Ima vulkane, hula plesaèice, | Don Hoa, surfanje.
{62781}{62820}I ja sam ulovio ribu.
{62852}{62917}To su piramide. | Ne prave, prave su veæe.
{62921}{62989}Mommo kaže | da su ih izgradili vanzemaljci.
{62993}{63025}Ona je moja baka.
{63257}{63301}Ovo su tvoji?
{63311}{63370}Da, moja obitelj.
{63374}{63401}Tko je kraljica?
{63405}{63470}Moja sestra misli da je ona.
{63495}{63526}Što ne valja?
{63530}{63606}Ništa. Samo, pa...
{63638}{63711}Trebao sam se pozdraviti | s mamom. Samo to.
{63726}{63795}Ponekad sam pravi seronja.
{63814}{63874}- Lucas, lice ti curi. | - Curi?
{63878}{63947}Ne, u redu je.
{63951}{64005}To ljudi rade kada su tužni?
{64009}{64045}Curi im iz lica?
{64058}{64144}Kad su mravi tužni, rade ovo:
{64619}{64691}Lucas, to je... To je...
{64695}{64743}Predivno je!
{64776}{64839}Slatko kamenje, doði tatici!
{65265}{65290}Crveni.
{65294}{65357}Što radite? | Zašto ne uzimate crvene?
{65361}{65437}Pa, zapravo je jednostavno, | šeæerko.
{65441}{65475}Ja mrzim crvene.
{65479}{65529}Pa, ja ih volim.
{65533}{65569}- Mrzim. | - Volim!
{65573}{65614}- Mrzim, mrzim. | - Volim.
{65618}{65686}- Priznaj, privlaèan sam ti. | - Što?
{65690}{65756}Kako me izazivaš svojim | slatkim govorom.
{65760}{65814}Želiš malo slatkog govora?
{65818}{65872}Jer æu ti ga dati malo.
{65876}{65935}Uzmi crveni prije nego | ih povuèem.
{65939}{65977}Hej, trebam ih.
{66022}{66060}Što radimo?
{66064}{66108}Ništa, ništa.
{66160}{66236}Beals-Buba | 702-555-0117
{66591}{66658}- Mommo, tu sam! | - Što je to?
{66680}{66733}- Tiffany. | - Što je Tiffany?
{66737}{66771}- Požurite! | - Da.
{66775}{66815}Ostavite crvene!
{66819}{66861}Fugax!
{66907}{66963}Hej, bezveznjakoviæu, jesi tu?
{66967}{67009}Zdravo?
{67013}{67056}Pucnjava!
{67064}{67160}Taj klinac i glupe | elektronske igraèke.
{67257}{67294}Što on radi?
{67298}{67353}Skaèe. Znaš, | hop-hop, gore-dolje?
{67357}{67405}Izviðaèka stvar. | Nije za tebe.
{67414}{67460}Dobro, hajde. Još jedan.
{67464}{67489}Samo trebam | sedmicu.
{67576}{67662}- Bok. Kako si? | - Bok.
{67666}{67712}Kraljevstvo pizza. | Pozdrav kralju.
{67716}{67808}Želite novu Zaèinjenu Princezu | s jakim Jester umakom?
{67816}{67868}Halo! Ovdje Lucas Nickle!
{67872}{67924}Moram otkazati narudžbu!
{67993}{68018}Što?
{68022}{68054}Ne želite naruèiti?
{68109}{68161}Molim otkažite ugovor!
{68165}{68280}- Bez tamanitelja! | - Da bude taman. Može.
{68324}{68376}Da. Bez tamanitelja.
{68380}{68428}Otkazujem ugovor.
{68432}{68501}Što? Želite otkazati?
{68505}{68530}Tko je to?
{68534}{68579}Bill, to si ti, stari?
{68583}{68660}Jesi me, stari. Jesi me, èovjeèe.
{68704}{68734}Kakvo olakšanje.
{68738}{68823}Dobro Lucas, ne razumijem | veæinu dogaðaja.
{68827}{68862}Što je tamanitelj?
{68866}{68960}Ne brini. Sada je sve u redu.
{69137}{69177}U zaklon!
{69256}{69324}Ovdje Tiff. Bok, mama.
{69328}{69406}Da, sve je u redu. | Lucas je štetoèina.
{69447}{69478}Igra glupe...
{69482}{69524}...video igre. | - Ne!
{69540}{69598}Hoæu. Hoæu. Dobro, mama.
{69608}{69730}Da. I ja grlim telefon. Bok.
{69868}{69914}Ti si kraljica Tiffany.
{69918}{69956}Dopusti da predstavim...
{70258}{70300}Sjeti se obuke.
{70357}{70407}Ne. Ne, ne, ne! Majko!
{70462}{70545}Žao nam je. Vaš broj | nije potpun.
{70549}{70588}Halo?
{70612}{70671}Tiffany, ne! | Zgnjeèit æeš Lucasa.
{70675}{70730}Halo. Nitko se nije smanjio. | Bok.
{70734}{70765}O èemu to prièaš?
{70769}{70834}Lucas! Pustite ga. Mene želite.
{70838}{70977}Vratite se. Istražite mene | umjesto njega. Lucas!
{71045}{71117}Vratite Lucasa, vanzemaljski ološu!
{71121}{71169}Lucas. Lucas.
{71173}{71207}- Dobro, Mommo. | - Lucas.
{71211}{71288}Idemo naæi tvoje druge zube.
{71735}{71817}Hova, gdje si?
{72085}{72183}Hova? Hova! Jesi dobro?
{72197}{72253}Jesmo dobro? Naravno. | Zašto ne?
{72257}{72326}U redu je. Dobro smo. Budalice.
{72346}{72393}Hej, hej, èekaj. | Ne, èekaj.
{72397}{72449}Zoc, pogodi što smo radili?
{72453}{72504}Išli smo na Havaje. | Vidjeli piramide.
{72508}{72541}Letjeli bez krila.
{72545}{72584}Prvo je bilo kao:
{72588}{72625}A onda:
{72629}{72709}Drugi su bili užasnuti | i ja sam preuzeo vodstvo.
{72713}{72771}Bili smo u ljudskom gnijezdu.
{72775}{72848}Ljudskom gnijezdu? To je zabranjeno!
{72852}{72878}Da, da.
{72882}{72950}No gnijezdo je bilo puno | slatkog kamenja.
{72954}{72990}Puno.
{72994}{73093}Kraljica Tiffany je gnjeèila, | napali su nas leteæi zubi...
{73097}{73163}...i eto nas. | Kakav dan. Laku noæ.
{73167}{73250}A tko ti je rekao | za to slatko kamenje?
{73254}{73332}- Lucas, naravno. | - Doista?
{73396}{73443}Bok. Kako si?
{73480}{73548}- Dobro. | - To je dobro.
{73552}{73595}Dobro je biti dobro.
{73599}{73712}Slušaj, samo sam ti htio nešto | pokazati, ako može.
{73737}{73785}Znaš što je ovo?
{73793}{73884}Napitak koji æe te opet uèiniti velikim.
{73891}{73985}Samo sam htio da ga | jako dobro pogledaš.
{73996}{74062}Jer je ovo zadnji put što ga vidiš.
{74092}{74126}Kako to misliš?
{74130}{74233}Mislim da nema šanse da æu te ikada | napraviti velikim.
{74275}{74393}Ikada. Ti si prijetnja | svakom mravu u ovoj koloniji.
{74397}{74444}Osobito za Hovu.
{74448}{74506}Ali nikada ne bih povrijedio Hovu.
{74510}{74584}Samo... Ja...
{74588}{74636}Samo želim iæi kuæi.
{74640}{74678}Da sam ja ti...
{74682}{74809}...pronašao bih pomoæ negdje drugdje, | jer ovdje za tebe nema nièega.
{74865}{74898}Nièega.
{75184}{75232}Bol, bol! | Nepodnošljiva je.
{75236}{75272}Riješite me mog jada!
{75276}{75317}Mirno, velika kukuljice.
{75321}{75377}Još te nisam ni dodirnula.
{75405}{75451}Budi nježna sa mnom.
{75673}{75732}- Gdje je Lucas? | - Nije s tobom?
{75737}{75862}- Ne. | - Lucas? Lucas? To je èudno.
{75869}{75953}Vjerojatno uništava neku | jadnu, nesretnu koloniju.
{75957}{76005}Znaš kakvi su oni. Razaraèi.
{76021}{76054}Što si napravio?
{76058}{76134}- Ja? Što sam ja napravio? | - Gdje je on?
{76138}{76173}Otišao je.
{76177}{76251}- Odveo te u zamku, Hova. | - Nije bilo zamke.
{76255}{76332}Odveo nas je do hrane. | Štitio nas je od...
{76336}{76394}- Od èega? Èega, Hova? | - Od neèega.
{76398}{76433}Neèega!
{76437}{76487}A brinuo sam da je od nièega.
{76491}{76530}Zaslijepio te je, Hova.
{76534}{76589}Ne, ti si taj koji je slijep.
{76593}{76670}Toliko si obuzet mržnjom | prema ljudima...
{76674}{76752}...da vidiš samo ono što želiš. | - Ma daj!
{76759}{76851}Vidim mladu kukuljicu, | èovjeka koji uèi naše obièaje...
{76855}{76944}...postaje dio ove kolonije, | postaje mrav.
{76951}{77006}- Nemoguæe. | - Slušaj se, Zoc.
{77010}{77097}"Èarobnjak ne poznaje tu rijeè." | Što si ti sada?
{77103}{77162}Sigurno ne mrav kojeg volim.
{77171}{77208}Hova!
{77212}{77277}Napravio sam to za tebe, za koloniju.
{77281}{77333}Napravio si to za sebe.
{77347}{77389}Hova, ja...
{77441}{77486}Neæe uspjeti sam po noæi.
{77490}{77539}Fugax, noga ti je slomljena.
{77543}{77599}Da, ali još imam pet dobrih.
{77603}{77649}Jako dobrih.
{77653}{77738}Vjerujem da nas je pokušao | zaštititi od neèega.
{77744}{77792}Vidimo se, Zoc.
{78334}{78383}Možda je Zoc u pravu.
{78389}{78459}Sada nikad neæu doæi kuæi.
{78514}{78582}Bok! Lijepa veèer, zar ne?
{78586}{78611}Mogu li?
{78632}{78659}Posluži se.
{78663}{78758}Hvala, obožavam vodu! Ja volim vodu, | no nisam vodena buba.
{78762}{78826}Zar nije smiješno? Ja sam...
{79721}{79757}Hej, Lucas.
{79781}{79865}Hej, zna li itko što znaèi...?
{79882}{79940}Mislim da sam upravo shvatio.
{79964}{79990}Kreketalac!
{80075}{80106}Ovuda!
{80274}{80314}Nemoj me više ostaviti.
{80318}{80374}- Zoc reèe... | - Moja si kukuljica.
{80461}{80497}Lucas, hajde.
{80639}{80726}Penji se! Možeš ti to. | Samo se usredotoèi.
{80753}{80796}Ja sam mrav. Ja sam mrav.
{80800}{80873}- Uspio je. Uspio je. | - Ja sam mrav!
{80877}{80946}Nije uspio.
{81132}{81180}Primi se!
{81224}{81266}Hova?
{81316}{81363}Lucas!
{81697}{81777}Prošli smo mu ravno | kroz grlo, zar ne?
{81781}{81821}Hej, na mom si krilu.
{81825}{81873}Oprosti. Jako mi je žao.
{81877}{81912}Pa, što vi radite?
{81916}{81989}Ja sam krijesnica. Ja svijetlim.
{81993}{82021}To je sjajno!
{82025}{82085}Poèinješ me iritirati. | Možeš li...?
{82198}{82257}Odvratno.
{82263}{82329}Prestani jesti, debeli.
{82333}{82381}Tu je pretrpano. | Nema mjesta!
{82385}{82498}Ne brini. Bojim se da æemo krenuti | u prikladno vrijeme.
{82502}{82541}Uvijek si pesimistièan.
{82545}{82626}Zašto ne možeš biti više... Hej, Lenny!
{82636}{82670}O tome ti ja prièam.
{82674}{82753}Lenny se uvijek smije...
{82818}{82862}Pustite me van!
{82866}{82939}- Ne želim biti gljiva! | - "Gljiva." Sjajno.
{82943}{82981}- Sviða ti se? | - Èudno je.
{82985}{83036}Ima još mnogo toga, kompa.
{83040}{83085}Bok, kako se ti zoveš?
{83089}{83139}Evo ga opet.
{83169}{83220}Stani! Vrati se!
{83224}{83257}- Hova! | - Ne!
{83261}{83322}Hova, otišao je.
{83350}{83404}Kreketalac, ovamo. Ovuda!
{83408}{83437}- Zoc! | - Zoc!
{83441}{83493}Slastan sam, pojedi me.
{83497}{83548}Zoc, jesi lud?
{83552}{83615}- On je lud. | - Hej, žabice!
{83664}{83734}Nijedna veza nije ovoga vrijedna.
{83856}{83943}Naravno. Zašto ne? Uði.
{83947}{84027}- Dobrodošao u raj. | - Zoc! Kako si tu dospio?
{84031}{84085}Nisam ušao na | stražnji ulaz.
{84089}{84152}Dobrodošao. Raskomoti se. Bok.
{84156}{84192}Tko je to? Tvoj mrav?
{84196}{84262}Zoc, lud si. U žabi si, | za Majku milu.
{84266}{84310}Što radiš? To je nemoguæe!
{84314}{84380}"Èarobnjak ne poznaje tu rijeè.
{84384}{84438}Što si ti sada?"
{84487}{84520}Èudak.
{84539}{84581}Što ona vidi u tebi?
{84585}{84654}- Što ona vidi u tebi? | - Toèno!
{84749}{84788}Nisam ja.
{84797}{84876}- Hej, je li to...? | - Korijen alke? I jest.
{84950}{84980}- Ne. | - Bože.
{85061}{85108}Možda bi to trebao pustiti.
{85112}{85181}Ne. Da ga onda ti zgrabiš? | Ne bih rekao.
{85185}{85256}- Ruke u zrak. | - Bože.
{85377}{85420}Hej, to je bilo sjajno!
{85424}{85491}Hej, dugujemo ti! | Puno hvala!
{85501}{85580}Slobodan sam! Slobodan!
{85610}{85671}Sranje.
{85738}{85817}Zoc, hvala. Ali zašto si | to napravio?
{85821}{85904}Mrav se žrtvuje za svoje prijatelje.
{85908}{85986}- Mislio sam da me mrziš. | - Nije to zbog tebe.
{86352}{86408}Dobro, trebamo ovdje prenoæiti.
{86412}{86473}Hajde, Fugax. | Skupimo neku hranu.
{86477}{86548}Molim? Ja ne skupljam hranu.
{86552}{86609}Ja izviðam hranu.
{86613}{86649}Dobro, idemo.
{86657}{86702}Zoc, ostani s Lucasom.
{86706}{86744}Puno je danas prošao.
{86748}{86817}- Ne traži me da... | - Nije ono što misliš.
{86821}{86865}U njemu postoji dobrota.
{86869}{86935}U njemu postoji mrav.
{86948}{87013}Vidiš, stvarno se trudi.
{87017}{87058}Hajde. Možeš ti to.
{87065}{87165}- Usredotoèi se. | - Jedan, dva, tri.
{87169}{87270}Misli mrav. Mrav. Mrav.
{87298}{87352}Da, dobro.
{87391}{87436}Sto mu mrvica.
{87658}{87689}Èudno.
{87693}{87773}Nebo izgleda potpuno isto.
{87777}{87834}Sve drugo je tako drugaèije...
{87838}{87916}...ali to je isto nebo, iste zvijezde.
{87975}{88019}Zašto to stalno radiš?
{88023}{88130}- Jesi bolestan? | - Što? Misliš na zijevanje.
{88134}{88214}- Umoran sam. | - Molim te, prestani. Odvratno je.
{88221}{88341}- Mravi ne zijevaju? | - Definitivno ne, hvala.
{88391}{88495}Taj tvoj grad je kao gnijezdo?
{88499}{88565}Pa, da. Kao.
{88569}{88633}A ljudi koji tamo žive | su svi braæa...
{88637}{88709}...i rade zajedno za | dobrobit kolonije?
{88717}{88768}Pa, ne baš.
{88772}{88889}Više je kao, znaš, svatko za sebe.
{88896}{88951}Ali to je tako primitivno.
{88955}{88993}Kako se išta napravi?
{88999}{89043}Neki ljudi rade zajedno.
{89047}{89093}Neki. Zašto ne svi?
{89105}{89181}Valjda je to zbog | njihovih razlièitosti.
{89185}{89247}Razlièitosti jaèaju koloniju.
{89251}{89339}Skupljaèi hrane, izviðaèi, trutovi, | njegovatelji...
{89343}{89421}...svi su razlièiti, no | važni dijelovi cjeline.
{89425}{89485}Tu mi mravi crpimo svoju snagu.
{89517}{89567}A mene tuku zbog razlièitosti.
{89571}{89635}- Zašto? | - Ne znam.
{89647}{89732}Neki ljudi vole tuæi ljude | koje ne razumiju.
{89736}{89825}Kao što ti voliš tuæi mrave.
{89845}{89921}Valjda nisam razmišljao o tome | što èinim.
{89925}{89984}Izgleda da se to èesto dogaða.
{90049}{90146}Valjda ponekad i ja radim | bez razmišljanja.
{90190}{90292}Možda smo u tome slièni.
{90363}{90418}Laku noæ, Lucas.
{90422}{90462}Laku noæ, Zoc.
{91433}{91479}- Što ne valja? | - Gledajte!
{91483}{91533}- Što je? Što ne valja? | - Vidim je!
{91537}{91580}- Koga? | - Majku mrava!
{91584}{91638}Došla je! Ovdje je!
{91699}{91760}Gledajte! Gledajte!
{91873}{91911}Ma što kažeš?
{91929}{91973}Doista postoji...
{92044}{92076}Ne.
{92313}{92355}Oblakodah.
{92359}{92421}Ali otkazao sam ugovor.
{92454}{92497}Slava Majci!
{92501}{92545}- Slava Majci! | - Napokon je došla!
{92551}{92634}Molim vas da se svi smirite.
{92739}{92821}Slušajte me! To nije Majka mrav!
{92825}{92904}- To je Oblakodah! | - To je istina.
{92918}{92976}Došao je uništiti cijelu koloniju.
{92986}{93025}Kako možemo uzvratiti?
{93034}{93070}Ima jaku èaroliju.
{93131}{93167}Prskalice.
{93203}{93243}Zamagljivaèi.
{93257}{93292}To je prava stvar.
{93296}{93337}Ubijaèi.
{93362}{93394}Sumporne bombe.
{93555}{93642}I kako znaš tog stvora?
{93651}{93697}Jer...
{93719}{93779}- Jer sam ga ja doveo ovamo. | - Lucas!
{93783}{93811}Znao sam. | Rekao sam ti.
{93815}{93905}- Straža, ukloni ovog èovjeka. | - Hajde, deèko.
{93909}{93963}- Hova! | - Lucas!
{94009}{94072}- Ne. | - Èekaj. Napitak.
{94076}{94207}To je to! Zoc, ti si me smanjio. | Možeš smanjiti i Oblakodaha.
{94222}{94289}Možemo ih utovariti i onda:
{94293}{94328}Ravno u uho!
{94355}{94414}Da. Da, valjda.
{94418}{94485}No Oblakodah se nadvija | nad nas kao drvo.
{94489}{94528}Kako da se približimo?
{94532}{94569}Imam ideju.
{94573}{94690}Zoc, vjerovao bi ovom èovjeku?
{94906}{94959}Ju-hu, zdravo.
{94963}{95011}Moramo razgovarati s vama.
{95031}{95085}Pokažite se.
{95107}{95188}Tu dolje. Zdravo, gdje ste?
{95359}{95463}Vidi, vidi, vidi. | Baš na vrijeme za ruèak.
{95467}{95509}- Zdravo. | - Èekajte.
{95513}{95575}Slušajte. Dolazimo u miru.
{95579}{95679}Tamanitelj je tu. Nosi oblake | smrti koji æe nas uništiti...
{95683}{95738}...ako ga zajedno | ne zaustavimo.
{95749}{95809}Oblaci smrti?
{95813}{95874}Dobro, idemo jesti.
{95925}{95960}Iza mene.
{96261}{96392}Gospodine, istoèno gnijezdo je | potpuno uništeno.
{96401}{96455}Oblak dolazi.
{96465}{96533}Oblak!
{96829}{96908}Što ti je na umu?
{97049}{97123}Zapamtite, možete pucati samo jednom.
{97127}{97229}Ne pucajte prije nego vidite | njegovu ušnu smolu.
{97233}{97296}- Razumijemo. | - Spremni? Lucas?
{97300}{97381}- Izgleda dobro. | - Hej. Hej. Prestani.
{97385}{97469}Zoc! Može zamjena? Moj je polomljen.
{97477}{97538}Dobro, deèki. Zagrijte ih.
{97673}{97737}Poletimo.
{98201}{98281}Hej, izgleda zabavno. Idemo pomoæi.
{98285}{98373}Dobro. Ionako živim samo dva tjedna.
{98377}{98432}Dobro za tebe.
{98637}{98713}Prvi val, napad!
{98838}{98919}Želiš klepetati? Hajde. Hajde.
{98923}{98960}Hajde!
{98964}{98999}Ja ulazim.
{99232}{99311}Ne mogu se probiti. | Ima neki štit.
{99321}{99376}Sto mu mrvica. Slušalice!
{99937}{100013}Za kraljicu i koloniju!
{100065}{100095}Da.
{100141}{100194}Zašto si stao?
{100209}{100306}Isuse. To boli. Molim te, prestani.
{100310}{100346}Bokiæ.
{100519}{100607}Moramo sletjeti na njega. | Pronaðite ulaz.
{100713}{100793}Ponovno puni! Sad imamo šansu.
{100906}{100951}Povuci!
{101031}{101073}Zoc!
{101324}{101404}- Dobrodošao na skalp. | - Zdravo.
{101408}{101464}- Uzmi komad. | - Uživaj.
{101515}{101551}Prsti!
{101555}{101605}Opet se èeše!
{101617}{101690}- U pazuh! | - Dolje, dolje!
{101853}{101924}Pusti moje prijatelje na miru!
{102073}{102122}Ne kopaj nos. | Ne kopaj nos.
{102264}{102333}- Trebaš prijevoz? | - Hvala.
{102784}{102830}Ne.
{102853}{102929}Hova, jesi dobro?
{102933}{102971}Što?
{103010}{103053}Laku noæ.
{103077}{103107}Bježite!
{103209}{103287}Hajde, ustaj! | Moramo iæi, moramo iæi!
{103293}{103332}Gotova sam, mraviæu.
{103483}{103548}Bježi! Bježi!
{103591}{103646}Lucas, hajde.
{103650}{103701}Spasi sebe.
{104023}{104094}Mravi nisu takvi.
{104171}{104207}Požuri.
{104575}{104626}Lucas? Lucas!
{104721}{104761}Lucas!
{104907}{104956}Uspio si. Uspio si!
{104981}{105033}To je pravi mrav.
{105037}{105067}Oprosti.
{105078}{105133}Hvala, mali.
{105360}{105406}Da!
{105427}{105505}- Oružje je beskorisno. | - Trebamo jasnu metu.
{105593}{105663}Hej, èekaj. Meta.
{105717}{105789}Dobro, što sada?
{105793}{105889}Pa, ne znam jer nikada ranije | nisam napadao.
{105893}{105942}- Zar nije smiješno? | - Ludo.
{105952}{106015}Gledaj. Evo prolaza.
{106086}{106180}U svijetu bez buba uživajte vi
{106197}{106289}Nazovite Beals-Bubu | I ubijanje prepustite meni
{106429}{106537}Dobro, osjeæam da | trebamo napasti nešto tu.
{106561}{106625}Hej, to izgleda ranjivo.
{106629}{106687}Savršeno.
{106792}{106859}Gledaj. Evo nam izlaza.
{106871}{106937}Dajmo mu pusu za zbogom.
{107000}{107042}Pusica, g. Beals!
{107661}{107723}Ne, ne, ne.
{107727}{107785}Prestanite. | Mièite se od mene.
{107964}{108001}Ne možete me uništiti.
{108005}{108089}Da. Ja sam Stan Beals!
{108093}{108134}Ne, ne, ne!
{108184}{108248}Slava Majci!
{108401}{108461}Lucas! Lucas! Lucas!
{108654}{108775}Danas više ne vidim | èovjeka meðu mravima...
{108779}{108874}...nego jedinstvenu koloniju.
{108878}{108949}Nema više Lucasa Razaraèa...
{108953}{109034}...nego je tu Rokai mrav.
{109114}{109172}Dobrodošao u koloniju.
{109203}{109277}Nije li to predivno?
{109298}{109353}- Rokai? | - To je mravlje ime.
{109357}{109392}Èarobnjaèko ime.
{109403}{109508}Rokai je zavrijedio svoju slobodu.
{109520}{109597}A mi smo stekli prijatelja.
{109606}{109677}Zapamti nas.
{109754}{109784}Hej, Lucas...
{109808}{109905}Mislim, Rokai. Kad se vratiš, | ako budeš imao priliku...
{109909}{109979}...možeš tu i tamo baciti | slatko kamenje?
{109983}{110059}Znaš, radije crvene.
{110063}{110141}Crvene? Mislio sam | da mrziš crvene.
{110145}{110259}Pa, da, ali poèinju mi se sviðati.
{110285}{110354}Nedostajat æeš mi, Dvonožni.
{110358}{110425}Z vati èovjeka "prijatelj".
{110429}{110494}Mislio sam da je to nemoguæe.
{110498}{110565}Ali, Zoc, èarobnjak | ne poznaje tu rijeè.
{110581}{110622}Istina.
{110633}{110665}Izvoli.
{110691}{110765}No nemoj piti prije nego izaðeš.
{110769}{110839}Još mislim da sam te trebala pojesti.
{110843}{110886}Lako se žvaèem.
{110890}{110959}No obeæala sam kraljici da neæu.
{110976}{111012}Nedostajat æeš mi.
{111016}{111078}I ti æeš nama nedostajati, Rokai.
{111082}{111118}Èasna rijeè.
{111127}{111190}Èasna rijeè!
{111424}{111498}Vratio se. Vratio se!
{111502}{111650}Slavi roðendan. | Sretan roðendan, Lucas!
{111694}{111737}Jesam te.
{111934}{111993}Bok, Tiff. Je li sve u redu?
{111997}{112026}Gdje je Lucas?
{112030}{112114}Još zakljuèan u sobi, | krije se od društva.
{112122}{112163}Mama, hej, mama!
{112167}{112254}- Lucas, što je? | - Zaboravio sam ti reæi zbogom.
{112268}{112314}Zbogom.
{112318}{112402}Zbogom, Kikirikiæu. Oprosti, | neæu te tako zvati.
{112406}{112470}U redu je. Ne smeta me.
{112481}{112549}Casa, slatka casa.
{112556}{112621}Ove su torbe muy grande.
{112625}{112661}A da otvoriš el vrata?
{112665}{112719}Ne znam na što misliš, dušo.
{112723}{112785}- Da, dušo, puerta... | - Što je puerta?
{112789}{112867}- Vrata, vrata! | - Vrata. Dobro, shvatila sam.
{112917}{113005}Hej, Pukas, gdje si bio? | Tražili smo te.
{113009}{113139}- Netko je zakasnio na hrpu. | - Da, hrpa!
{113143}{113173}Rekao je | hrpa.
{113177}{113285}Prestani ponavljati za mnom, kužiš?
{113289}{113384}Da prestanem ponavljati. Kužim.
{113388}{113452}Dosta je. | A da ja tebe bacim na hrpu?
{113456}{113531}A da ga pustiš? | Što je s tobom, sto mu mušica?
{113542}{113621}Što? A da me prisiliš?
{113625}{113733}Tako je, ne možeš.
{113737}{113836}Jer sam ja velik, a ti mali.
{113844}{113978}Da, ja sam mali. Svi smo mali. | No zajedno smo veliki.
{113982}{114063}Misliš da æe ti gubitnici | iæi protiv mene?
{114067}{114177}Mogu im raditi što god želim, | a oni ne mogu ništa.
{114185}{114276}A isto vrijedi i za tebe, Pukas.
{114289}{114337}Hrpa!
{114381}{114476}Rekoh, hrpa!
{114496}{114605}- Èuli ste ga. | - Hrpa!
{114658}{114757}Ne! Nemojte me ozlijediti! Mama!
{114781}{114832}Hej, želite se doæi igrati?
{114836}{114891}Da, fora. Hajde, Lucas.
{114895}{114961}Stiæi æu vas. | Prvo moram nešto obaviti.
{114965}{115033}Da! Dobro!
{115037}{115074}Da.
{115109}{115174}Baš brzo rastu.
{115201}{115250}- Što? | - Vidi što ja imam.
{115254}{115285}Ne. Zoc.
{115289}{115385}Zoc! Èekaj! Èekaj! | Ne, ne! Prestani!
{115389}{115426}Hajde.
{115448}{115514}Prestani! Ozbiljna sam...
{115633}{115669}Slatko kamenje!
{115700}{115800}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan 
