{1}{1}25.000
{1711}{1783}Moramo krenuti. Èeka nas naporan dan. 
{1802}{1830}Dobro.
{1920}{2020} BOŽIÆ S OBITELJI KRANKS 
{2070}{2172}Podizanje prtljage, | podzemna, prodaja karata
{2269}{2361}Nedjelja nakon Dana zahvalnosti. | Najveæa gužva u godini.
{2370}{2461}Možeš li me podsjetiti zašto | putuješ baš danas, Blair?
{2534}{2619}Godina æe proletjeti. | Doæi æu kuæi iduæi Božiæ.
{2716}{2786}Volim te, mama. | - Srce moje!
{2791}{2856}Dosta je bilo. Preživjet æe.
{2874}{2902}Tata!
{2969}{3003}Volim te.
{3171}{3203}Bog, zlato.
{3306}{3337}Volim te!
{3389}{3423}Volim vas!
{3743}{3786}Misliš da æe biti dobro?
{3832}{3924}I bolje nego dobro. | - U Peruu, u džungli.
{3931}{3994}Prestani razbijati glavu time.
{3996}{4096}Mirovne snage neæe je | poslati nekamo gdje je opasno.
{4131}{4177}Neæe to biti isto!
{4189}{4223}Što to?
{4241}{4272}Božiæ.
{4641}{4650}BLAGDAN
{4650}{4674}BLAGDAN
{4676}{4749}Radim desert za sutrašnji | ruèak umjetnièke zajednice.
{4751}{4830}Trebam neke stvari od Chipa. Eno mjesta!
{4832}{4895}Trebam bijelu èokoladu i pistacije.
{5115}{5207}Nisam ponio kišobran. | - Moram to kupiti kod Chipa.
{5211}{5263}Nisam ponio kišobran!
{5270}{5346}Svejedno to moram kupiti. | - Drugi put.
{5404}{5487}Ti ostani u autu, a ja... | - Idem ja!
{5489}{5553}Vidi, obièna rosulja!
{5574}{5650}Nemoj zaboraviti: Bijela | èokolada Dixon od 0,5 kg.
{5652}{5703}I pistacije March Brothers.
{5714}{5740}Dobro!
{6177}{6242}Vama treba kišobran!
{6244}{6288}Ma samo bijela èokolada.
{6290}{6320}CHIPOVA TRGOVINA
{6798}{6825}Što je bilo?
{6827}{6893}Èula sam se s Blair. Nazvala je iz aviona.
{6895}{6931}Zvala je iz aviona?
{6933}{7028}Znaš li ti koliko košta poziv iz aviona?
{7077}{7160}Kako je? | - Dobro. Nedostajemo joj.
{7187}{7300}Stajao sam ondje. Neæeš... | - Nisi kupio bijelu èokoladu!
{7325}{7365}Nisu je imali.
{7367}{7405}Jesi li razgovarao s Rexom?
{7407}{7465}Tko je Rex? | - Mesar!
{7527}{7645}Šokirat æeš se, ali nisam | pitao mesara gdje je èokolada!
{7735}{7781}Ali hoæu. | - Hvala.
{7785}{7883}Iz ovih stopa idem do Rexa. | Možda me pita zašto sam mokar.
{8154}{8197}Sigurno ne trebate...
{8297}{8387}Može jedan meni? | - Kako da ne. Hvala.
{8624}{8703}Ozbiljno, vama treba kišobran!
{8707}{8795}Ne! Znate zašto neæu vaš | glupi kišobran? Zato što...
{8885}{8997}Zato što mokriji ne mogu biti!
{9278}{9337}Deprimiraju vas kišni dani?
{9386}{9441}Krstarite Karibima s... | Carnival Cruise Lines
{9883}{9921}'Jutro, Luthere.
{9956}{9992}Zdravo, g. Krank.
{10010}{10052}'Jutro, g. Krank.
{11045}{11118}Ovaj æe Božiæ biti potpuno | drukèiji, zar ne, Luthere?
{11120}{11172}Hoæe, potpuno drukèiji.
{11184}{11233}Ništa neæe biti isto.
{11249}{11343}Prvi put u 23 godine Blair neæe biti ovdje.
{11381}{11429}Možda èak padnemo u depresiju.
{11494}{11561}Depresija je èesta za Božiæ.
{11590}{11626}Ma da.
{11658}{11720}Voljela bih zaboraviti sve to.
{11936}{11983}Što to gledaš?
{12045}{12107}Zašto me tako gledaš?
{12192}{12236}Pojedi tjesteninu do kraja!
{12258}{12342}S tjesteninom sam gotov, ali s tobom nisam.
{12344}{12386}Odmah se vraæam.
{12418}{12471}Èekaj tu. | - Dobro!
{12811}{12840}Luthere?
{12926}{13003}Što to radiš? A nije ni subota naveèer.
{13218}{13286}Sjetio sam se neèega! | - Je li?
{13288}{13328}Neèega genijalnog!
{13480}{13538}Obvezno navuci zastore!
{13564}{13595}Evo!
{13613}{13657}Doði. Okreni se.
{13659}{13711}Što te spopalo? Sjedni.
{13723}{13767}Zakopèaj se i sjedni.
{13774}{13808}Vidi ovo.
{13810}{13907}Ovo je mali popis izdataka za lanjski Božiæ.
{13917}{14017}Vidi ti te stavke. 63 dolara | za popravak božiæne kuglice?
{14029}{14100}Strašno! Pogledaj ukupni iznos.
{14116}{14180}Lani smo na Božiæ potrošili 6.100 dolara.
{14197}{14275}6.100 dolara na...
{14277}{14318}Ne moraš ponavljati.
{14320}{14408}A nismo imali ništa od toga. | - Što želiš reæi?
{14475}{14511}Karibi!
{14554}{14624}Desetodnevno luksuzno | krstarenje na Jubileeju.
{14639}{14703}Najluksuzniji brod u floti.
{14705}{14742}Kajmansko otoèje.
{14766}{14815}Ronjenje. Idemo na Jamajku.
{14817}{14892}Daskanje s jedrom, ma što to bilo! | Vidi ovu sliku.
{14894}{14992}Bahami. Sunèanje. | 10 dana luksuznog krstarenja, ti i ja.
{15011}{15101}Možda æu morati smršavjeti. | - Ma ja æu umjesto tebe!
{15105}{15148}U èemu je kvaka?
{15195}{15245}Ne bih rekao da je to kvaka.
{15355}{15396}Preskoèit æemo Božiæ.
{15423}{15464}Preskoèit æemo Božiæ?
{15477}{15558}Preskoèit æemo Božiæ, | uštedjeti novac pa ga potrošiti na sebe.
{15560}{15596}Ne znam baš.
{15598}{15686}Hajde, molim te! Idemo se | izležavati na karipskom suncu.
{15735}{15804}Koliko æe to koštati? | - Tri tisuæe dolara.
{15859}{15965}Uštedjet æemo? | - Itekako!
{16015}{16080}Svejedno možemo dati | dobrovoljne priloge...
{16082}{16142}djeèjoj bolnici i crkvi, naravno?
{16144}{16221}Ne, ovo je totalan bojkot, srce.
{16226}{16260}To je 600 dolara.
{16298}{16340}Bojkot je totalan.
{16342}{16408}To je sve što æu reæi na tu temu.
{16410}{16472}U tom sluèaju, ne.
{16502}{16550}Glupava ideja!
{16586}{16688}Dopuštaš da nas bijednih 600 | dijeli od krstarenja Karibima!
{16708}{16754}Ne. Ti to dopuštaš.
{16905}{16931}Dobro!
{16933}{17032}Dat æu crkvi i bolnici koliko sam i lani.
{17034}{17080}Ali ni novèiæa više.
{17082}{17152}Kada kreæemo? | - Toèno u podne na Božiæ.
{17263}{17318}A nije ni subota naveèer!
{17335}{17404}Drage kolege,
{17417}{17489}ove godine neæu slaviti Božiæ.
{17539}{17608}Kako što mnogi znaju, | Blair je postala èlanica...
{17626}{17665}Mirovnih snaga.
{17763}{17846}Stoga smo Nora i ja odluèili | zaobiæi božiæne rituale,
{17848}{17919}uštedjeti novac i otiæi na krstarenje.
{17943}{18052}Dakle, neæu sudjelovati | u božiænim obièajima.
{18054}{18163}Neæu kupovati ni primati | darove. Svejedno vam hvala.
{18165}{18232}Neæu doæi na sveèani | tvrtkin domjenak za Božiæ...
{18234}{18300}a ni na uredsku zabavu.
{18327}{18417}Nisam bijesan i neæu urlati...
{18442}{18523}mrzovoljno na sve koji | mi èestitaju blagdane.
{18586}{18674}Jednostavno preskaèem Božiæ.
{18788}{18881}BUNDEVINO SJEME
{18915}{18975}Dobar dan, gðo Krank. | - Zdravo, Aubie, kako si?
{18977}{19034}Zabrinut sam za vaše božiæne èestitke.
{19036}{19063}Zašto si zabrinut?
{19065}{19160}Uvijek izaberete najljepše. | Trebali biste ih naruèiti.
{19162}{19223}Ove godine neæemo | naruèivati božiæne èestitke.
{19225}{19268}Što neæete? | - Èuo si me.
{19270}{19300}Mogu li pitati zašto neæete?
{19302}{19404}Veæ kasnim na ruèak. | Pa-pa! Pozdravi svoju mamu.
{19431}{19488}Ali na dražbi uvijek svira bend uživo!
{19490}{19548}Ali lani je koštao 15.000.
{19550}{19609}Za Bal borbe protiv raka uzeli smo DJ-a.
{19611}{19636}Moje dame.
{19638}{19678}Bog, Aubie. | - Zdravo.
{19685}{19775}Gðo Krank, nismo spomenuli | vaše božiæne pozivnice.
{19777}{19828}Ni njih neæemo trebati.
{19830}{19899}Neæete imati zabavu? | - Za Badnjak?
{19919}{19964}Ove godine nema zabave.
{19966}{20034}Nije naruèila ni božiæne èestitke.
{20109}{20141}Što se dogaða?
{20226}{20254}Mi...
{20265}{20303}predahnut æemo.
{20330}{20401}Ove godine nemamo Božiæ.
{20403}{20494}Kako je moguæe nemati Božiæ? | - Preskoèiš ga.
{20503}{20567}Što æemo mi onda za Badnjak?
{20569}{20643}Smislit æete nešto. Mnogo je drugih zabava.
{20645}{20689}Ali nijedna nije kao tvoja.
{20697}{20724}Baš si draga!
{20726}{20785}Kad kreæete? | - Na Božiæ.
{20804}{20857}Èudno doba za putovanje!
{20864}{20943}Èini se da malo ljudi putuje 25. prosinca.
{20945}{20995}Luther je dobio sjajnu ponudu.
{21010}{21056}Zašto svejedno nemate zabavu?
{21058}{21141}Zato što ne želimo, Merry! Predahnut æemo!
{21155}{21220}Jedna godina bez Božiæa!
{21276}{21356}Što æemo? | - Ne znam.
{21836}{21896}G. Krank, ja sam Randy Scanlon.
{21898}{21954}I ove godine prodajemo božiæna drvca.
{21956}{22001}Ovo je vaše.
{22043}{22109}Lani ste uzeli kanadsku plavu smreku.
{22111}{22184}Ova je prava ljepotica. Ima u njoj tri metra.
{22191}{22244}Gða Krank voli velike.
{22246}{22272}Slatki su!
{22274}{22360}Koliko je velika? | - 90. Morali smo poskupjeti.
{22433}{22504}Ove godine ne kupujemo božiæno drvce.
{22556}{22610}Luthere! | - To smo raspravili.
{22832}{22893}Oprostite na povišenju cijene!
{22898}{22956}Po drvcu zaradimo manje nego lani.
{22958}{23035}Nije stvar u novcu! | Ove godine nemamo Božiæ.
{23037}{23092}Idemo na krstarenje.
{23115}{23158}Ne trebamo drvce.
{23328}{23404}Dobro. Iz zla...
{23429}{23468}u gore.
{23502}{23532}Luthere!
{23534}{23577}Što je? | - Doði.
{23581}{23633}Zašto? | - Doði!
{23685}{23734}Što to rade? | - Tko?
{23770}{23875}Traèaju nas Frohmeyeru. | - Samo ne Frohmeyeru!
{23936}{23994}Bojiš se Vica Frohmeyera?
{23996}{24064}On je neslužbeni šef naše ulice!
{24066}{24135}Frohmeyeru smeta što | æemo preskoèiti Božiæ?
{24137}{24173}Komu æe nas tužiti?
{24175}{24237}Trojici mudraca? Djedu Mrazu?
{24272}{24325}Ne podcjenjuj ga, dušo!
{24327}{24415}Vic Frohmeyer dušom | je i tijelom za ovaj kvart!
{24421}{24473}Trebao si kupiti drvce. | - Ma ne!
{24475}{24515}Nisi ga morao postaviti. | - Ne.
{24517}{24587}Moglo je ostati u dvorištu! | - Tišina!
{24589}{24651}Zašto šapæeš? Ovo je naša kuæa!
{24653}{24748}Iz istog razloga zbog kojeg | se ti skrivaš iza zavjese!
{24825}{24857}Bog, Walte.
{24859}{24944}Luther Krank nije od izviðaèa | htio kupiti božiæno drvce.
{25055}{25117}Možete li vi to vjerovati, g. Frohmeyer?
{25766}{25843}Ne postavljaj ih gore! | Hoæu ih sa stražnje strane kuæe!
{25850}{25941}Pomakni udesno! U drugo desno!
{25955}{26015}Beckerovi se opet svaðaju. | - 'Veèer, Vic.
{26026}{26090}Ove æe godine Blair svima nedostajati.
{26092}{26151}Cijela ulica bruji o tomu. Kako je ona?
{26153}{26221}Dobro je, hvala na pitanju.
{26230}{26261}Kako tvoja obitelj?
{26263}{26340}Izvrsno raspoložena. | Veèeras postavljamo ukrase.
{26342}{26380}Èvrsto omotaj, Spike!
{26407}{26484}Zdravo, tata! | - Dobro je, mama!
{26534}{26606}Ovo je najljepše doba | godine, zar ne, Luthere?
{26608}{26657}Mojoj sreæi nigdje kraja.
{26675}{26726}Neæe biti isto sad kad Blair nema.
{26728}{26766}Naravno da neæe.
{26897}{26939}Dušo, jesi li dobro?
{26951}{27036}Doði! Dragi! | - Pomozi mi!
{27076}{27172}Ima ovdje dogodovština zbog | kojih æe mi Božiæ nedostajati.
{27174}{27206}I tako...
{27215}{27256}stvarno ga preskaèete?
{27258}{27294}Tako je.
{27312}{27372}Nekako mi se èini da griješiš.
{27374}{27437}Ali ne odluèuješ ti o tomu.
{27439}{27501}Moram ti reæi, mnogi su se susjedi uzrujali.
{27503}{27528}Je li?
{27530}{27617}Božiæ je nama uvijek susjedska | proslava, znaš to i sam.
{27619}{27718}Svi postavljaju ukrase, | peku kolaèe, razmjenjuju darove.
{27750}{27789}Valjda to radimo zbog djece.
{27791}{27853}Ako hoæeš da se | žderem zbog toga, odustani.
{27855}{27912}I još nešto.
{27914}{27982}Volio bih da ti i svi ostali | ovdje poštujete moje želje.
{27984}{28032}Kako ti kažeš, Luthere.
{28310}{28366}Sutra æe biti vedro.
{28379}{28433}Pravo vrijeme za snjegoviæa.
{28467}{28497}Snjegoviæa?
{28545}{28613}SNJEGOVIÆEVA PROSLAVA | Susjede, postavi snjegoviæa!
{28615}{28687}Znaš, ako odem...
{28781}{28809}Vic?
{28989}{29051}Snjegoviæ je božiæni obièaj!
{29064}{29118}Snjegoviæ je božiæni ukras.
{29120}{29222}Neæe mi Vic Frohmeyer govoriti | da ukrasim kuæu za Božiæ.
{29257}{29309}Zašto neæeš postaviti snjegoviæa?
{29341}{29407}To je stvar principa, razumiješ?
{29409}{29484}Ako mi tako hoæemo, | možemo zaboraviti na Božiæ.
{29486}{29560}Nitko, pa ni Vic Frohmeyer, | ne može nas sprijeèiti.
{29568}{29630}Neæe me prisiliti na to.
{29837}{29879}Ugodan dan!
{29936}{29967}Zdravo, Nora!
{29979}{30045}'Jutro, Bev. Walte. | - Zdravo, Nora!
{30241}{30283}Bilo je sluèajno!
{30304}{30363}Walte, zašto ne staviš | povodac tom svom maèku?
{30365}{30422}Samo psi imaju povodac, stari.
{30438}{30502}Misliš da možeš pobjeæi od Božiæa?
{30534}{30616}Pokušavam. | - To je dobra metoda štednje.
{30634}{30699}Nije stvar u novcu. | - Kako da ne!
{30708}{30803}Mufflese, budi fin. | Hoæete li se vi ikad sprijateljiti?
{30833}{30889}Volio bih reæi, hoæemo, ali...
{31015}{31050}Kako si danas, Bev?
{31052}{31133}Nekad bolje, nekad gore. Danas je bolje.
{31140}{31186}Drago mi je.
{31198}{31254}Doði na doruèak, srce.
{31274}{31310}Moram na posao.
{31312}{31367}Još radiš za šefove, je li?
{31380}{31429}Zapravo i imam šefa.
{31431}{31504}Zar te veæ nisu trebali uzeti za partnera?
{31546}{31589}Moram na posao.
{31596}{31646}Ugodan dan, stari.
{31766}{31839}Jedna gruda s malenom žutom mrljom.
{31849}{31938}Tek toliko da mu okrzne | tjeme te njegove sitne glave.
{31940}{31972}Stari!
{32077}{32111}Mrgud!
{32150}{32199}Dobro jutro, g. Scrooge.
{32292}{32356}'Jutro, Dox. Ima li poruka? | - Zvali su iz Wal-Marta.
{32358}{32463}Sama æu kupiti jeftini parfem, | ove godine nema Djeda Mraza.
{32495}{32525}Duhovito!
{32567}{32601}Nora Krank!
{32616}{32661}Došli smo po snjegoviæa!
{32865}{32896}Halo? | - Luthere!
{32898}{32947}Bog, srce. | - Došli su!
{32949}{32975}Tko?
{32977}{33074}Vic Frohmeyer, Wes Trogdon, | Ned Becker i njihova djeca!
{33076}{33121}Došli smo po snjegoviæa!
{33127}{33189}Hoæe snjegoviæa! | - Ne mogu ga dobiti.
{33191}{33218}Nora!
{33227}{33278}Molim te, daj nam snjegoviæa.
{33343}{33395}Dušo, a gdje je snjegoviæ?
{33397}{33466}Iza peæi. Zašto? | - Ne žele otiæi!
{33468}{33509}Ne daj im snjegoviæa!
{33511}{33579}Ti i Luther ne morate ništa!
{33587}{33691}Samo ostavite snjegoviæa pred | kuæom i mi æemo ga postaviti.
{33703}{33773}Kažu da æe ga oni postaviti. | - Ne dolazi u obzir!
{33775}{33831}Molim te, Luthere! | - Ne!
{33853}{33897}Vratit æemo se.
{33918}{33962}Neka snjegoviæ bude vani!
{33964}{34010}Vratit æe se!
{34012}{34037}Poslušaj samu sebe.
{34039}{34094}Panièariš na telefonu u zakljuèanoj kuæi...
{34096}{34150}zato što susjedi idu od vrata do vrata...
{34152}{34263}da bi postavili smiješnog | snjegoviæa od dva metra!
{34293}{34387}Lako je tebi govoriti! | Daleko si i siguran u svom uredu!
{34389}{34416}E pa...
{34418}{34492}Ja sam u klopci! Na mene su navalili!
{34494}{34579}Dobro, slažem se. | Možda bi trebala otiæi odatle.
{34581}{34653}Ma naravno, dragi! A kako da to izvedem?
{34655}{34725}Ulica vrvi od naših susjeda!
{34727}{34805}Idi u garažu pa u auto, | upali ga i kreni u trgovaèki centar.
{34807}{34842}Vidimo se u O'Leary'su.
{34844}{34923}Hajde! Možeš ti to! Hajde prije nego...
{35299}{35342}Još malo ulijevo.
{35390}{35430}Dobro je.
{35653}{35716}Zdravo, gðo Krank. | - Nora?
{35808}{35851}Vic, ona odlazi!
{35923}{35958}Što je njoj?
{35960}{36022}Jako mi je žao!
{36101}{36131}Oprostite!
{36196}{36236}Nora, zaustavi auto.
{36238}{36338}Zaustavi auto. Molim te, èuj. | Nemoj da ti poslije bude žao!
{36340}{36424}Molim te, samo na trenutak.
{36426}{36498}Zaustavi auto! | Slušaj me. Daj nam snjegoviæa!
{36500}{36535}Zaustavi auto!
{36622}{36668}Mi samo hoæemo snjegoviæa!
{36682}{36759}Reci mi nešto. Molim te!
{37205}{37280}Božiæ trpimo mi žene, a ne muškarci!
{37282}{37366}Ja snosim posljedice tvoje morske ideje!
{37368}{37424}Ja sam na prvoj liniji!
{37485}{37528}Imam iznenaðenje za tebe. | - Koje?
{37530}{37566}Zažmiri.
{37689}{37734}Dobro, otvori oèi.
{37816}{37916}Je li ovo neka šala? | - Imam ga i ja. Što kažeš?
{37918}{37965}Ženski kupaæi kostim?
{37986}{38057}Vjerojatno ide uz to. Ne, ja imam svoj.
{38079}{38159}Vidi ti to! Krpica za skakanje s litica.
{38172}{38268}Nema šanse da to | obuèemo na ovom krstarenju.
{38292}{38343}Nisu za krstarenje.
{38421}{38463}Znaš što je pomaknuto?
{38465}{38566}Kad irska pivnica poslužuje | riblje tacose. To ne kužim.
{38568}{38675}Imam žgaravicu. Više ih neæu jesti. Eno.
{38686}{38755}Hajde. Za mnom. I ne spominji njezine oèi.
{38757}{38794}'Dan, g. Krank!
{38796}{38881}Zdravo, Daisy. Moja žena Nora. | - Dobar dan.
{38946}{38981}Nisam baš raspoložena za ovo.
{38983}{39071}Ne, hajde! Dobio sam popust. | 60 dolara za 12 termina.
{39094}{39146}Zašto da pocrnimo prije krstarenja?
{39148}{39219}Zar nije poenta u tomu | da pocrnimo dok krstarimo?
{39221}{39307}Pogledaj našu kožu. | Izgledamo kao nedokuhana piletina.
{39321}{39368}Izgledate kao truplo!
{39387}{39454}A i vama bi trebala pomoæ.
{39463}{39496}Hvala!
{39574}{39646}Zaboga, ovo treba zakonom zabraniti!
{39958}{39997}Dobro, smiri se!
{40275}{40307}Oprostite!
{40503}{40587}Oprostite! Pardon!
{40595}{40638}Trebam flaster.
{40652}{40691}Nora Krank?
{40775}{40868}Veleèasni Zabriskie. | Dobar dan. Otkud vi ovdje?
{40872}{40939}Ovo je trgovaèki centar. | Kupujem božiæne darove.
{40961}{41029}Pa normalno!
{41035}{41069}Jesi li dobro?
{41073}{41123}Jesam. Otprilike.
{41127}{41164}Krvariš.
{41166}{41261}To je samo ogrebotina. | Molim vas drugi ruènik.
{41266}{41359}Tražim flaster! Gospoðo, dajte se odluèite!
{41504}{41600}Nora, iz pouzdanog sam | izvora èuo da ste ti i Luther...
{41615}{41691}ove godine odluèili da neæete slaviti Božiæ.
{41763}{41799}Tako nekako!
{41829}{41903}Veleèasni Zabriskie, Luther i ja smo dobro.
{41906}{41991}Sve je u redu, baš kao inaèe.
{41995}{42054}Poslužiteljica je rekla | da krvariš. Jesi li dobro?
{42056}{42103}Luthere? | - Pozdrav.
{42150}{42191}Veleèasni Zabriskie.
{42221}{42248}Bog!
{42336}{42372}Dospjeli smo na naslovnicu.
{42377}{42425}Preskaèu Božiæ
{42446}{42493}Pogledaj. | - Èekaj.
{42583}{42633}Preskaèu Božiæ? | - Aha.
{42635}{42716}Dom g. I gðe Krank | ovaj je Božiæ potonuo u tamu.
{42718}{42816}Njihovi susjedi postavljaju | ukrase i èekaju Djeda Mraza...
{42818}{42877}a Krankovi su Božiæ preskoèili.
{42879}{42969}Neimenovani izvori kažu da | se pripremaju za krstarenje.
{42977}{43036}Nemaju drvce, svjetla | ni snjegoviæa na krovu.
{43038}{43112}Jedino su oni u Hemlocku | ostavili snjegoviæa u podrumu.
{43114}{43200}Kako znaju gdje je snjegoviæ? | - Posvuda imaju špijune!
{43202}{43286}Hemlock, èest pobjednik u | natjecanju u ureðivanju ulica...
{43288}{43339}ove je godine zauzeo | razoèaravajuæe 6. mjesto.
{43341}{43436}Valjda su sada sretni, | potužio se anonimni susjed.
{43438}{43526}Drugi je izjavio: Pokvareno sebiènjaštvo.
{43528}{43583}Tko je to rekao? | - Mogao je bilo tko.
{43585}{43626}Kako se usuðuju!
{43645}{43703}Kakvi šmokljani!
{43719}{43751}Reæi æu ti nešto, Luthere!
{43753}{43844}Mislim da se neæu vratiti s ovog krstarenja!
{43865}{43917}To se traži! Još dva dana i odlazimo.
{43919}{43956}Još dva, srce!
{43988}{44015}Kreteni!
{44045}{44089}Èokoladno mlijeko? | - Može.
{44108}{44137}To je moje!
{44139}{44195}VOJSKA SPASA | Doba davanja, vrijeme radosti i mira
{44197}{44262}Kao i obièno. | - Oprostite što kasnim.
{44264}{44306}Što je bilo?
{44312}{44355}Ma Bev Scheel!
{44405}{44471}Možeš me zamijeniti? | - Naravno.
{44473}{44533}Što se dogodilo? | - Juèer je bila na pregledu.
{44535}{44598}Rak se vratio treæi put!
{44600}{44663}Je li metastazirao? | - Misle da jest.
{44665}{44698}Užas!
{44705}{44760}Ovo joj je možda zadnji Božiæ.
{44762}{44794}Zlato!
{45170}{45243}Vidi, Scrooge glavom i bradom!
{45278}{45340}Što misliš, kako je ovaj | fotograf došao do slike?
{45342}{45411}Koji fotograf? | - Onaj koji je ovo slikao.
{45413}{45463}Aha, taj. | - Da, taj!
{45469}{45505}Popeo se.
{45514}{45562}Na tvoj krov? | - Aha.
{45587}{45659}Zašto si to uèinio? | - Ne znam.
{45668}{45748}Rekao je da želi uhvatiti cijelu ulicu.
{45814}{45861}Bar si dosljedan.
{45863}{45902}Trudim se, stari.
{45904}{45943}Prestani s tim! | - S èim?
{45945}{45994}Prestani me zvati stari!
{46008}{46050}10 si godina stariji od mene!
{46052}{46081}Jesam li? | - Jesi.
{46083}{46125}Dokaži! | - Walte.
{46182}{46265}Èula sam za Bev. Žao mi je.
{46331}{46371}Kako je ona?
{46373}{46476}Zaèudo, dobro. Raspoložena je. | Ukrašava kuæu, peèe kolaèe.
{46478}{46557}Ma da. Ako ikako | možemo pomoæi, samo mi javi.
{46569}{46627}Hvala. To mi puno znaèi.
{47609}{47657}Došli su po snjegoviæa.
{47727}{47753}Neæu!
{47892}{47939}Ja æu. | - Hvala.
{48070}{48147}Dobra veèer, g. Krank. | - Dobra veèer, pozornici.
{48150}{48211}Ponovno je kucnuo taj èas!
{48213}{48306}Policijska udruga skuplja | priloge u dobrotvorne svrhe.
{48308}{48336}Odlièno.
{48338}{48430}Za igraèke za djecu i košare | s darovima za siromašne.
{48432}{48481}Da invalidna djeca kližu.
{48483}{48570}Svake godine donosimo darove | stanovnicima staraèkih domova.
{48572}{48625}I ratnim veteranima, dakako.
{48627}{48690}Prodajemo svoje kalendare.
{48692}{48767}Vi ga kupite svake godine, zato smo opet tu.
{48865}{48914}Ove godine ne trebamo kalendar.
{49044}{49079}Kakav krelac!
{49095}{49147}Rekao je da ga ne treba.
{49187}{49264}Vama hvala na prilogu. Sretan Božiæ.
{49267}{49334}Sretan Božiæ. Držite se!
{49492}{49563}Sretan Božiæ. | - Sretan Božiæ.
{49565}{49675}Mi smo božiæni zbor crkve | sv. Marije. Jesu li oni doma?
{49695}{49738}Jesu.
{49747}{49802}Jesu li židovi? | - Nisu.
{49816}{49887}Budisti ili nešto? | - Ne, ništa od toga.
{49892}{49970}Samo pokušavaju izbjeæi Božiæ ove godine.
{49975}{50063}Što? | - Èuli ste me. On je èudak.
{50076}{50142}Preskoèio je Božiæ da uštedi za krstarenje.
{50144}{50171}Ne!
{50173}{50256}Meni se èini da bi im | dobro došao božiæni duh.
{50258}{50300}Stvarno? | - Samo vi dajte.
{50302}{50338}Dobro onda!
{50469}{50498}Na pod!
{50554}{50581}Baci se!
{51073}{51100}Kreni!
{51232}{51266}Baš je zabavno!
{51359}{51434}Pjevaèi božiænih | pjesama pokraj naših borovica.
{51458}{51485}Krasno!
{51487}{51555}Nije krasno! Ometaju tuði | posjed. Netko nam je smjestio.
{51557}{51630}Ne ometaju posjed! | - Ometaju!
{51632}{51689}Na našem su zemljištu. Nismo ih pozvali.
{51691}{51767}Netko im je rekao da doðu. | Scheel ili Frohmeyer.
{51785}{51892}Božiæni zbor ne ometa posjed! | - Znam ja o èemu govorim!
{51894}{51973}Zašto onda ne zoveš policiju? | - Možda i hoæu.
{51984}{52052}Nazovi svoje prijatelje iz policijske postaje.
{52054}{52145}Duhovito! | - Još stigneš kupiti kalendar!
{52181}{52236}To nije vic. To je vojni znak.
{52238}{52313}Mornarièkih marinaca. | Vidio sam na Discovery Channelu.
{54325}{54355}Doði!
{54565}{54647}Sjedni tu. Tako.
{54649}{54710}Eto. Savršeno.
{54725}{54814}Najtiša prostorija u kuæi. | Ovdje nas nitko neæe naæi.
{55076}{55141}Sloboda snjegoviæu!
{55339}{55373}OSLOBODITE SNJEGOVIÆA
{55466}{55518}Sretan Božiæ, gðo Krank.
{56499}{56535}Luthere!
{56656}{56740}Svaki Tkotavac u | Tkogradu volio je Božiæ jako.
{56746}{56846}Ali Grinch sjeverno od | Tkograda ama baš nikako.
{56862}{56952}Grinch je mrzio Božiæ | i cijelo božiæno vrijeme.
{56954}{57042}Zašto, ne pitajte, svih je | muèilo tog pitanja breme.
{57044}{57125}Možda mu glava nije dobro uglavljena bila.
{57130}{57212}A možda mu se pak | cipela na krivom mjestu svila.
{57274}{57335}No meni èini se da razlog zapravo bio je...
{57337}{57436}to što njegovo srce | dva broja preusko bijaše.
{57518}{57558}Luthere, tvoje lice!
{57565}{57646}Što je s njim? | - Kao da je nekako zamrznuto.
{57654}{57682}Ovo?
{57712}{57769}Danas sam dobio injekciju botoksa.
{57784}{57813}Tretman botoksom!
{57815}{57904}Uzmu veliku iglu i ubrizgaju ti ga u èelo.
{57906}{57982}Lice ti se tako zamrzne. | Èitao sam u èasopisu o zdravlju.
{57984}{58070}Koliko æeš biti takav? | - Ovo je privremeno.
{58078}{58149}A onda ti nestanu sve bore.
{58269}{58354}I ti bi trebala pokušati. | - Traži da ti vrate novac.
{58443}{58526}Ne mogu više tako živjeti! | - Ha?
{58537}{58574}Ne možemo izaæi.
{58576}{58654}Kamo god da izaðemo, | šuškaju nam iza leða.
{58656}{58730}Ne mogu kuæi. Previše je depresivno.
{58748}{58839}Nema drvca, svjetala ni glazbe.
{58926}{58972}S tobom ne mogu razgovarati.
{58980}{59069}Obuzet si sobom. | - To nije istina!
{59073}{59127}Pogledaj na što si spreman. | - Nevjerojatno!
{59129}{59204}Travnjak nam je klizalište. | - Ništa ne osjeæam.
{59206}{59274}Netko je mogao slomiti vrat ili nogu.
{59276}{59374}Pjevaèi su mogli nastradati. | - A to je kao loše?
{59376}{59447}Šalim se! Znam da ti nije bilo lako.
{59449}{59531}Ali još jedan dan, 24 sata, | i kreæemo na putovanje.
{59538}{59593}Sve æe biti bolje, obeæavam ti.
{59615}{59644}Ne znam baš.
{59941}{60044}Misliš da æe se Blair uopæe sjetiti Božiæa?
{60046}{60114}Vjerojatno neæe. Ipak je u džungli.
{60116}{60178}I s ljudima koji štuju drveæe.
{60180}{60254}Jedu koru, žabe i sve to.
{60273}{60332}To æeš obuæi? | - Nego.
{60334}{60362}Zgodno!
{60444}{60471}Sloboda snjegoviæu!
{60473}{60527}Znam da si to ti, Spike. Bog.
{60529}{60621}Opet? Koji je to veæ put? | - Valjda peti ili šesti.
{60638}{60705}Da bar mogu nekako | odbrusiti tom pametnjakoviæu.
{60707}{60758}Ma briga te. | - Dobro kažeš.
{60779}{60830}Otoci zovu.
{60928}{60977}Sloboda snjegoviæu! | - Bog, Spike.
{61012}{61062}Ti si genij. | - Hvala.
{61269}{61348}Dobro, snjegoviæ je mrtav. | - Molim? Tata, to si ti?
{61350}{61399}Stani malo. Blair? | - Da.
{61401}{61517}Ne, to je bila šala. | Mislio sam da je netko s posla.
{61519}{61611}Tvoja mama ide na drugi | telefon pa æemo ti reæi nešto.
{61613}{61648}Blair! | - Bog, mama.
{61704}{61771}Bog, zlato! Mama je! Kako si? Gdje si?
{61773}{61828}U Miamiju sam, dolazim kuæi za Božiæ.
{61830}{61875}Ha? | - Jeste li iznenaðeni?
{61877}{61934}Osupnuta sam! | - Zateèen.
{61941}{62015}Sletjeli smo prije jedan sat. | - Pa to je divno!
{62017}{62094}Koji to mi? | - Imam još jedno iznenaðenje.
{62096}{62157}Da? Koje? | - S Enriqueom sam.
{62198}{62253}Što je to rique? | - Enrique.
{62255}{62311}Lijeènik je. | Zajedno smo studirali na Brownu.
{62313}{62395}Sretali ste ga. | U studentskom domu i na promociji.
{62397}{62432}Naravno! | - Ja se ne sjeæam.
{62434}{62464}Peruanacje.
{62466}{62525}Krasno! Komunist! | - Dragi!
{62534}{62592}Katkad smo ga zvali Rick. | - Rick?
{62594}{62654}Onaj s kojim si otišla | živjeti u divljem braku dolje!
{62656}{62700}Imao je svoju kolibu, tata!
{62702}{62772}Ma kakva koliba! | Želim slike koje to dokazuju!
{62774}{62853}Godinama smo prijatelji. On je divan.
{62855}{62914}Zaljubili smo se dok smo radili skupa.
{62916}{62968}Zaprosio me.
{62970}{63001}Molim?
{63003}{63048}Od srca to želim.
{63098}{63129}Dušo!
{63138}{63205}Enrique je za blagdane uvijek putovao kuæi.
{63207}{63282}Nikad nije proslavio Božiæ u Americi. | Jako se veseli.
{63284}{63363}Prièala sam mu o Božiæu. Drvcu, ukrasima.
{63365}{63444}Snjegoviæu na krovu, | o svemu. Pada li snijeg, tata?
{63446}{63506}Enrique nikad nije doživio bijeli Božiæ.
{63508}{63562}Ne, ali sprema se oluja.
{63564}{63634}Kada slijeæete? Kada stižete?
{63636}{63694}Slijeæemo u 8:03. | - Veèeras?
{63696}{63785}Da, veèeras. U pravi èas | za našu badnjaèku zabavu.
{63802}{63863}Prireðujete zabavu, je li tako, mama?
{63889}{63927}Ma naravno!
{63929}{64038}Super! Mama, Enrique æe te osvojiti.
{64040}{64085}Želi punu kuæu djece.
{64087}{64122}Zlato!
{64124}{64211}Mama, jedva èekam da doðem | kuæi! Baš smo vas iznenadili.
{64219}{64272}Ostala sam bez teksta!
{64274}{64361}A tvoj je otac vjerojatno izvan sebe.
{64363}{64401}Super. Volim te, mama.
{64403}{64492}I ja tebe, dušo. Sretan put. | Vidjet æemo se kad stignete.
{64618}{64682}Trebala je prije nazvati. | - Ali nije!
{64684}{64740}Zašto si joj rekla da æemo imati zabavu?
{64742}{64777}Zato što hoæemo.
{64779}{64815}Trebam svoj prsluk!
{64874}{64953}Ne znam tko æe doæi ni što æe jesti...
{64955}{64991}ali zabavu æemo imati!
{64993}{65019}A naše putovanje?
{65021}{65106}Da se nisi usudio! | Ovo je bila tvoja glupa ideja!
{65179}{65244}Glupa ideja? Prije pet minuta bio sam genij.
{65246}{65324}E pa sad si idiot. | - Kako jedan poziv sve mijenja?
{65326}{65408}Pusti prošlost, | otoènjaèe, imat æemo zabavu!
{65410}{65482}Sir, vino i ono što Blairey | najviše voli: Šunku u medu!
{65484}{65556}A tko dolazi na tu zabavu? | - Dotle još nisam stigla.
{65558}{65614}Ti si zadužen za drvce. | - Nemamo drvce.
{65616}{65643}Nabavi ga i postavi!
{65645}{65741}Pa odvuci preplanulu guzicu | u podrum i postavi snjegoviæa.
{65743}{65770}Neæu! | - Hoæeš!
{65772}{65831}Izvest æemo malo božiæno èudo.
{65833}{65897}Ako uspijemo, Blairey nikad neæe doznati...
{65899}{65982}za tvoj glupi, apsurdni, djetinjasti plan...
{65984}{66029}da preskoèimo Božiæ!
{66114}{66179}BOŽIÆNA DRVCA | Amerièki izviðaèi 18. odred
{66473}{66517}Oprostite zbog ovog ružnog grmiæa.
{66519}{66564}Sretan Božiæ. | - I jest, zar nije?
{66566}{66594}Duke Scanlon. | - Bog, Duke.
{66596}{66625}Onaj koji vam je donio...
{66627}{66691}onu krasnu kanadsku plavu | smreku prije nekoliko tjedana.
{66693}{66792}Odlièno! Sretan vam Božiæ! | Trebam još jednu takvu smreku.
{66794}{66875}Hitno mi je potrebno drvce. | Što vam je ostalo?
{66952}{66985}Samo jedno.
{67032}{67108}Sviða mi se! Uzimam.
{67125}{67180}Zbilja? | - Da. Koliko je?
{67202}{67262}75 dolara. | - Ovdje piše 15.
{67269}{67355}Zakon ponude i potražnje. | - Ovo je prava pljaèka, zar ne?
{67357}{67465}Izviðaèima treba prilog od 75 | dolara za njihovu skupštinu.
{67475}{67535}A da vam dam 25 dolara, deèki?
{67551}{67617}75 dolara! Uzmi ili ostavi!
{67645}{67675}Vaša djeca?
{68521}{68581}Wes. | - Luthere. Sretan Božiæ.
{68583}{68663}Sretan Božiæ i tebi. U škripcu sam.
{68665}{68744}Do 17 moramo biti kod ženinih. | Trebao sam krenuti prije 2 h.
{68746}{68824}Pomoæi æu ti. Ovo neæe dugo trajati.
{68826}{68882}Èuj, promijenio sam planove.
{68884}{68962}Nazvala me Blair. Vraæa se kuæi, veèeras!
{69100}{69149}Što je s krstarenjem? | - Ne znam.
{69151}{69221}Ne mogu naæi božiæno drvce. | - Pa?
{69291}{69321}Mogu li posuditi tvoje?
{69323}{69398}Wes, moramo iæi! | - Evo me, T.
{69400}{69431}Hoæeš moje drvce? | - Da.
{69433}{69498}Vratit æu ti ga u kuæu prije nego što doðete.
{69512}{69570}Svašta! | - Nemam izbora.
{69572}{69649}Svima drugima drvce treba veèeras i sutra.
{69660}{69730}Ti to ozbiljno, je I' da? | - Smrtno ozbiljno.
{69737}{69799}Trish se to ne bi svidjelo. | - Trish ne mora znati.
{69801}{69847}Bog, Trish! | - Zdravo, Luthere.
{69859}{69945}Dušo, moramo krenuti. | - Samo mi èestita Božiæ.
{70019}{70048}Molim te!
{70162}{70218}Ako razbiješ ijednu | kuglicu, obojica smo gotovi!
{70220}{70322}Ostavit æu ga kako sam ga | i našao. Hvala ti, stvarno!
{70324}{70390}Ovo je da umreš od smijeha! | - Zašto se onda ne smijem?
{70392}{70439}Sloboda snjegoviæu!
{70441}{70485}Moram iæi. | - Hvala.
{70580}{70638}Deèki. Momci!
{70657}{70704}Deèki, ovdje sam.
{70706}{70755}Bježi! | - Crta!
{70758}{70802}Èekaj! | - Trk!
{70804}{70840}Stani, doði.
{70888}{70947}Samo hoæu razgovarati, Spike.
{71059}{71097}Pusti me! | - Zloèesti vilenjak!
{71099}{71159}Prestani se koprcati! | - Makni se!
{71161}{71198}Hajde. | - Nemoj me tuæi!
{71200}{71262}Sve je bilo šala. | Natpis za snjegoviæa, pozivi!
{71264}{71330}Znam. Neæu ti ništa, neæu te tuæi.
{71336}{71392}Ali moj si dužnik.
{71403}{71480}Imam samo 20 dolara. | - Ne želim tvoj novac.
{71528}{71570}Trebam malu pomoæ.
{71806}{71850}TRŽNICA
{72025}{72114}Golemo drvce. Podsjeæa me | na jedno koje je tata kupio...
{72116}{72207}Zanimljivo. Ovako æemo. | Krhke æemo staviti na kauè.
{72209}{72308}Je li ovo protuzakonito? | - Ne. Samo nemoj ništa razbiti.
{72700}{72727}Spike!
{72729}{72791}Ništa vrijedno. | - Što piše na njoj?
{72818}{72867}Prvi Božiæ novoroðenèeta.
{72895}{72923}Divota!
{73011}{73062}Halo? | - Bog, Walte. Ned ovdje.
{73066}{73140}Sretan Božiæ, Nede. | - Sretan Božiæ, Walte.
{73142}{73205}Promatram kuæu Trogdona.
{73222}{73293}Èini se da je Krank poludio.
{73295}{73360}Kako to? | - Krade njihovo božiæno drvce.
{73450}{73559}Oprostite, tražim šunku. Šunku u medu.
{73561}{73626}Ako ih je uopæe ostalo, onda su otraga.
{73628}{73698}Hvala lijepa, sretan Božiæ. Oprostite.
{73761}{73797}MELOVA ŠUNKA U MEDU
{74515}{74551}Sretni blagdani!
{74648}{74744}Ovo sigurno nije nezakonito? | - Jesi ti policajac? Idemo!
{74996}{75041}Mogu li kupiti vašu šunku? | - Molim?
{75043}{75090}Vašu šunku, zadnja je.
{75092}{75188}A moja kæi Blair dolazi kuæi èak iz Perua...
{75190}{75255}Šunku u medu voli više od svega.
{75257}{75348}Htjela bih je otkupiti od vas. | - Nije na prodaju.
{75354}{75458}Ali... Ona je u mirovnim snagama!
{75460}{75566}Spremna sam platiti više | nego što piše na etiketi!
{75586}{75635}Nismo zainteresirani.
{75661}{75753}Nikad nije prerano da | poènete razmišljati o štednji...
{75755}{75837}za djetetovo fakultetsko obrazovanje.
{75916}{75950}Možeš?
{76138}{76210}Doði, ti upravljaj, a ja æu držati otraga.
{76212}{76261}Upravljaj. Spreman?
{76325}{76350}Spike!
{76742}{76799}Zdravo, g. Krank. | - Bog, deèki.
{76864}{76910}Kamo æete s tim drvcem?
{76912}{76983}Spike i ja ga nosimo mojoj kuæi.
{76985}{77014}Spike?
{77023}{77073}Da, mali. Spike.
{77195}{77277}Je li otrèao onamo? Ne? Baš èudno.
{77316}{77387}To vam je zamišljeni prijatelj? | - Nije!
{77559}{77598}Sretan Božiæ!
{77703}{77731}Stani!
{78568}{78619}Trebali ste kupiti kalendar.
{78634}{78691}Trebat æe vam ondje kamo idete.
{78863}{78890}Što ti hoæeš?
{78892}{78965}To sam ja, Spike Frohmeyer. | Vicov mali, znate.
{78967}{78995}Aha.
{79007}{79094}Ako kaže da mu je Trogdon | posudio drvce, govori istinu.
{79096}{79158}Evo kljuèa. Nije provalio.
{79206}{79233}Kljuè!
{79328}{79365}Nestani, Krank.
{79503}{79576}Hvala, Spike. Baš sam se prepao.
{79594}{79674}Sve je pod kontrolom. | Opusti se malo, Luthere.
{79757}{79792}Idi po drvce.
{79997}{80061}Što je bilo? | - Istrpaj stvari iz auta!
{80067}{80114}Što se dogodilo? | - Nitko neæe doæi!
{80116}{80174}Nazvala sam sve koje znamo, svi su zauzeti.
{80176}{80253}Morat æemo pozvati susjede. | - Preko mene mrtvog!
{80255}{80303}Kakvo je drvce? | - Pa...
{80392}{80431}Užas!
{80443}{80484}Uzmi ili ostavi.
{80486}{80598}Plave sige i nogometaške | kuglice? Kokice! To nije moje!
{80620}{80701}Dimljena pastrva! | - Bolje nego smrznuta pizza!
{80733}{80798}Što je bilo sa šunkom u medu?
{80875}{80961}Da nikad više nisi izgovorio šunka u medu!
{81066}{81143}Halo? Blair! Zdravo, zlato!
{81145}{81202}Da je pitam mogu li je vratiti u Peru.
{81204}{81251}U Atlanti ste!
{81273}{81351}Ma mi kuhamo kao ludi, | spremamo se za zabavu.
{81353}{81435}Naravno da æu ispeæi kremastu | pitu s karamelom koju voliš!
{81465}{81525}Tata i ja dolazimo po vas u osam.
{81527}{81598}I ja te jedva èekam vidjeti. Volim te!
{81656}{81740}Sad je pola pet. Trebam 1 kg | karamela i sljezovu kremu.
{81742}{81827}Diskont s piæem zatvara u pet. | Èuvaju mi sanduk Pinot Noira.
{81830}{81866}Sanduk vina za nas èetvero?
{81868}{81939}Šuti! Koliko æe ti trebati | da postaviš snjegoviæa?
{81941}{81968}Tri dana. | - Super!
{81970}{82054}Kad završiš, nazovi sve | susjede i pozovi ih na zabavu.
{82056}{82090}Kakvu zabavu?
{83059}{83105}Sretan Božiæ, Nora.
{83142}{83193}Sretan Božiæ i vama.
{83221}{83276}Zašto ti jurcaš uokolo?
{83278}{83342}Kupujem završne sitnice. A vi?
{83349}{83420}Kupujem nešto. Pomalo.
{83485}{83525}Sutra imate veliku zabavu?
{83527}{83631}Ne, veèeras. Moja se | kæi vraæa iz Južne Amerike.
{83648}{83739}Priredit æemo mali prijam. | Dovodi novog deèka.
{83741}{83770}Blair.
{83826}{83852}Da!
{83972}{84018}Želite li doæi?
{84042}{84080}Ozbiljno?
{84114}{84174}Naravno. Svi su pozvani.
{84177}{84210}U koliko sati?
{84243}{84271}Pola devet.
{84282}{84351}Vi ste u Hemlockovoj? | - Da, broj 1482.
{84364}{84438}Hvala! Hvala lijepa!
{84517}{84552}Tko ste vi?
{84589}{84622}Nemam pojma!
{84843}{84896}Svake si godine sve teži!
{84898}{84926}Doði!
{84936}{84968}Hajde!
{84970}{85015}Tako!
{85356}{85392}Vidim snjegoviæa.
{85417}{85525}Djeco! Narode! | G. Krank postavlja snjegoviæa!
{85532}{85564}Idemo!
{85845}{85917}Hajde, izravnaj se! Još malo.
{85989}{86048}Dobra veèer, Luthere! | - Hej!
{86107}{86155}Trebaš li pomoæ, prijatelju?
{86178}{86205}Ne.
{86212}{86265}Luthere, drži se!
{86300}{86341}Pazi na ravnotežu!
{86427}{86479}Polako! Pazi!
{86509}{86565}Pazi, Luthere!
{86592}{86664}Idemo malo unatrag!
{87066}{87094}Èuvaj!
{87425}{87457}Jesi li dobro?
{87476}{87540}Ma divno, Vic. Hvala. A ti?
{87542}{87596}Nazvao sam Hitnu, stižu.
{87598}{87654}Hvala, Walte. | - Bev me natjerala!
{87734}{87821}Do maloprije bio je na krovu. | - Je li dobro?
{87842}{87874}Jadni snjegoviæ!
{87876}{87922}Jadni snjegoviæ, malo sutra!
{87964}{87999}Dobro je!
{88006}{88058}Ma pusti me da padnem.
{88075}{88104}Dobro je, Nora.
{88106}{88174}Što to izvodiš? Jesi li èitav?
{88177}{88229}Pokušao sam se ubiti.
{88231}{88310}No nisam dobro proèitao upute. | Ali bar mi je noga utrnula.
{88312}{88407}Popeo se sam, pokušavao | je postaviti vašeg snjegoviæa!
{88446}{88523}Evo ih. | - Stižu profesionalci. Ovamo!
{88543}{88622}Drži se. Baš i ne možeš, ha?
{88639}{88670}Požurite se!
{88673}{88751}Odmaknite se, bit æu dobro. | Pustite deèke da to obave.
{88753}{88839}Hvala. Problemèiæ s užetom. | Ako biste ga mogli odvezati.
{88841}{88921}Ljestve bi mogle biti | korisne, ali ne znam baš.
{88923}{88998}Što æete s tim škarama, deèki?
{89000}{89030}Držite ga?
{89120}{89145}Jesi li dobro?
{89203}{89260}Ovamo, ekipa!
{89262}{89322}Polako. Tako je, ovamo.
{89383}{89422}Odmaknite se, narode.
{89424}{89451}Što se dogaða?
{89453}{89553}Luther je dizao snjegoviæa | na krov pa su obojica pala.
{89556}{89582}Razmaknite se.
{89584}{89665}Zar neæete preskoèiti | Božiæ ove godine, g. Krank?
{89669}{89732}Da, što je s tim, Luthere?
{89754}{89813}Blair dolazi kuæi za Božiæ.
{89933}{89982}I dovodi svog deèka.
{90066}{90129}Oèekuje božiæno drvce? | - Aha.
{90131}{90178}I snjegoviæa? | - Naravno.
{90182}{90266}A godišnju badnjaèku zabavu Krankovih?
{90278}{90309}I to.
{90311}{90391}Kada stiže? | - Avion slijeæe oko osam.
{90497}{90561}Narode, slušajte. Okupite se!
{90563}{90638}Imat æemo zabavu kod Krankovih!
{90662}{90717}Božiænu dobrodošlicu za Blair.
{90719}{90761}Odlièna ideja, Vic!
{90763}{90843}Prekinite posao i pomozite. | Nora, imate li puricu?
{90882}{90916}Dimljenu pastrvu.
{90926}{90961}Dimljenu pastrvu?
{91087}{91117}Ima li tko puricu?
{91119}{91190}Mi imamo dvije, obje se peku. | - Izvrsno, donesite ih!
{91192}{91261}Ned, idi Brixleyju i donesi | njegovog snjegoviæa i svjetla.
{91263}{91311}Postavit æemo ih oko Lutherove šimširovine.
{91313}{91417}Stani! Zašto da mu pomognemo? | - Pa da. Krelacje!
{91419}{91522}Ma što mislili o Lutheru... | Znam da niste naèistu s tim.
{91524}{91606}Ali mi smo susjedstvo. | A susjedi pomažu jedni drugima.
{91608}{91694}Iako se jedan od njih veæi dio blagdana...
{91696}{91754}ponašao kao sebièno i razmaženo dijete.
{91760}{91844}Ne èinimo ovo zbog | njega. Èinimo to zbog Blair.
{91869}{91936}Blair koja je èuvala vašu djecu.
{91938}{92039}Blair koja ljeti dolazi kuæi | pa se svi osjeæamo kao obitelj.
{92044}{92073}Tako je!
{92075}{92157}Zašto bi kæi morala | ispaštati zbog oèevih grijeha?
{92187}{92267}Da bismo ovo i približno | uspjeli, morate prionuti.
{92269}{92376}Ponesite rezervnu odjeæu | i hranu i doðite za pola sata!
{92378}{92435}Idemo! | - Randy, Mike, doðite.
{92462}{92522}Hvala! | - Nema na èemu, Nora.
{92524}{92579}Deèki, vi idite na aerodrom.
{92585}{92647}A zašto? | - Blair treba prijevoz kuæi!
{92683}{92741}Ne znam možemo li to.
{92791}{92837}Da nazovem naèelnika?
{92906}{92945}Ma možemo!
{93103}{93145}Držite li snjegoviæa?
{93147}{93207}Polako! Evo ga!
{93209}{93246}Tako!
{93397}{93427}Napokon!
{93450}{93502}Nema do bijelog Božiæa!
{93520}{93560}Sretan Božiæ!
{93573}{93607}Pozdrav svima!
{93671}{93729}Šefe! | - Uðite, narode.
{93731}{93766}Aubie! Hvala ti.
{93925}{93953}Što je ovo?
{94006}{94031}Zlato?
{94072}{94108}Je li ovo zakonito?
{94447}{94495}Evo! Imam dio koji ti treba.
{94560}{94606}To bi trebalo diæi.
{94687}{94748}Vidi, dragi! Imela!
{94829}{94857}Halo?
{94868}{94909}Bog, Blair. | - Blair?
{94947}{95012}Uranili ste 55 minuta. | - Što?
{95014}{95110}Dobar neki vjetar u leða! Ma odlièno!
{95148}{95223}Èekamo ovdje. Nikako da te doèekamo.
{95225}{95250}Volimo te, zlato!
{95252}{95308}To je bila tvoja mama. Oboje te volimo.
{95310}{95400}Što æemo? Neæemo stiæi! | - Sjetio sam se neèeg. Stanite.
{95470}{95499}Kreni!
{95501}{95533}Hajde, Spike!
{95535}{95619}Što god da još naðete po | kutijama spustite u podrum!
{95621}{95666}Baš dobro izgleda.
{95771}{95842}Vidiš li ih? | - Nigdje ne vidim svoje.
{95996}{96074}BLAIR I N. REEKY
{96111}{96137}Dušo.
{96155}{96187}Jesmo li to mi?
{96423}{96503}Ja sam Blair. Ovo je Enrique.
{96536}{96601}Policijska pratnja? Dojmljivo.
{96611}{96703}Èini se da je moj tata ove | godine dao velikodušan prilog.
{96718}{96774}Aha. Da samo znate!
{96780}{96839}37 minuta, prijatelji!
{96937}{96997}Dobro došli u SAD. Dajte mi prtljagu.
{96999}{97097}Ovdje pozornik Frohmeyer. Èujete li me?
{97099}{97161}Koliko æu ti puta ponoviti, ne javljaj...
{97163}{97216}Hitno je. Možete razgovarati?
{97262}{97330}Reci. | - Morate ih zavlaèiti.
{97332}{97369}Zavlaèiti? | - Spremni smo.
{97371}{97402}Nismo spremni.
{97430}{97481}Dobro. Zavlaèiti!
{97497}{97557}Ja æu, hvala.
{97575}{97653}Sretan Božiæ, Luthere. Šunka. | - Izvolite?
{97655}{97750}Oprostite, malo sam uranio. Zahladnjelo je!
{97752}{97828}Samo uðite. Zabavite se. | - Baš lijepo!
{97830}{97898}Veleèasni Zabriskie, drago | mi je što vas opet vidim.
{97900}{97927}Hvala.
{97970}{98037}Ne znam tko je on. | - Donio je šunku!
{98487}{98539}Zašto voziš tako sporo?
{98558}{98592}Led na cesti.
{98602}{98697}Hoæeš slaviti Božiæ pod | imelom ili u mrtvaènici?
{98959}{99013}Mogu li vam pomoæi? | - Hvala.
{99015}{99082}Fino. | - Evo.
{99084}{99183}Razgovarao sam sa svima. | Njega nitko ne poznaje.
{99213}{99241}On poznaje njih.
{99243}{99284}Što... Kako...
{99286}{99319}Hvala, veleèasni.
{99338}{99388}Robbie, provjeri donji kabel. | - Razumijem.
{99390}{99441}Kakvo je, takvo je. Nemamo vremena.
{99443}{99483}Randy, ukljuèi.
{99893}{99926}Ideš!
{99968}{100013}Nema struje.
{100039}{100122}Provjerit æu prekidaè. | - Idem pomoæi Lutheru.
{100199}{100254}Poznaješ li ikog u Elektri?
{100306}{100402}Pozornik Frohmeyer, èujete | li me? Brzo, curi mi baterija.
{100430}{100512}Što je, Spike... Gospodine? | - Morate još otezati.
{100547}{100620}Prijam. | - Što je to? Tko da oteže?
{100669}{100703}Rekao je veže.
{100705}{100810}Možda je nasilje u obitelji. Idemo provjeriti.
{100835}{100886}Ma o èemu ti to?
{101148}{101240}Ovo æemo staviti na stol za predjelo.
{101284}{101358}Aubie, keksiæe stavi na rub stola.
{101413}{101519}U kutiji su bile kuglice... | - Onu veliku si odnijela dolje.
{101582}{101614}Napokon!
{101686}{101725}Krasno!
{101761}{101832}Prelijepo izgleda! | - Stvarno je krasno.
{101834}{101896}Samo što nije stigla!
{101898}{101993}Idemo na kat. Sredi nekako taj | ten pa se moramo presvuæi.
{102019}{102091}Hoæeš li mi objasniti koji se vrag dogaða?
{102093}{102134}Moramo zavlaèiti.
{102153}{102239}Nekoliko minuta dok zabava ne krene.
{102241}{102274}Dobro!
{102300}{102395}Sve je u redu. Samo provjeravaju.
{102410}{102485}Idemo do ovih vrata | kao da nešto istražujemo.
{102487}{102545}Stavit æu ruku na | pištolj da izgleda službeno.
{102547}{102606}Samo daj, Terminatore!
{102731}{102772}Izgledam kao moja majka!
{102781}{102837}A ona je mrtva veæ 15 g.
{102884}{102935}Dosta je bilo, idemo u auto.
{102937}{102962}Može.
{103049}{103121}Što je to? Možda je provala!
{103123}{103181}Ma nije! | - Ma je.
{103183}{103234}Ne treba mi ovo, ne sad.
{103236}{103300}Provale su èeste na Badnjak.
{103302}{103359}Znam, ali èeka nas zabava!
{103361}{103417}I što sad, da ignoriramo ovo?
{103497}{103537}To ne možemo.
{103628}{103668}Eno ga! | - Policija!
{103670}{103701}Evo vam na!
{103741}{103802}Drž' ga! Hajde!
{104037}{104127}Diži se, bježi! Brže!
{104129}{104189}Ne izležavaj se! Pobjeæi æe!
{104191}{104258}Ni makac! Ostani gdje jesi.
{104260}{104295}Policija!
{104325}{104365}Drži ga! | - Policija.
{104512}{104569}To! Naš je!
{104762}{104853}Ovo je Enriqueov prvi Božiæ u Americi.
{104855}{104907}Samo da ostavimo dobar dojam.
{104909}{104955}Nora, jesi li sigurna u ovo?
{104978}{105065}Izgledam kao mafijaški kapo. | - U crnom ti je koža svjetlija.
{105082}{105165}Blair nikad ne smije | doznati za krstarenje, jasno?
{105167}{105222}Èuo sam te i prvih 60 puta.
{105374}{105418}Frohmeyer 1 Frohmeyeru 2.
{105420}{105483}Orao je sletio. | - Prijam.
{105485}{105549}Nede! Stigli su!
{105561}{105613}Nisam gotov! | - Sakrij se!
{106064}{106119}Blair je stigla!
{106179}{106207}Vidim je!
{106244}{106312}Evo ih! | - Što ako nam se ne svidi?
{106325}{106370}Odgojili smo pametnu curu.
{106372}{106407}Dobro došla kuæi!
{106409}{106454}Izlaze iz auta!
{106456}{106539}Doma je! Narode, stigla je!
{106541}{106570}Drago mi je što te vidim.
{106572}{106615}Tko je to? | - Enrique, moj deèko.
{106617}{106694}Vic Frohmeyer, drago mi je. | - I meni, gospodine.
{106696}{106742}Baš sam uzbuðena!
{106744}{106855}Roditelji te èekaju. Zar nije | Luther krasno ukrasio kuæu?
{106914}{106957}Dušo, stigli su!
{107018}{107095}Ne mogu vjerovati da sam doma! | - Ni mi to ne možemo vjerovati.
{107097}{107125}Tata!
{107164}{107262}Luther Krank. Moja žena Nora. | - Ja sam Enrique DeCardenal.
{107266}{107319}Daj da te zagrlim!
{107321}{107389}Sretan Božiæ! | - I vama.
{107409}{107485}Krasno izgledate. | - Pazili smo na prehranu.
{107487}{107542}A i sunèali ste se. | - Ma nismo!
{107544}{107611}U crnom sam da budem svjetliji.
{107695}{107779}Zabava! Vidi! Doði, zabava je u tijeku!
{107781}{107851}Zabava, narode!
{107871}{107907}Baš nam je drago što si tu!
{107909}{107965}Ja uzimam lagani, ti ostale.
{107967}{108008}Aubie, kako si?
{108139}{108167}Mali.
{108189}{108223}Doði malo.
{108240}{108278}Smrzavam se.
{108280}{108349}Umirem od gladi. Nisam jeo sedam dana.
{108351}{108391}Sedam dana? | - Da.
{108402}{108466}Sve okrajke dajem djeci.
{108492}{108556}Kojoj djeci? | - Mojoj djeci.
{108572}{108666}Imam èetvero: | Annie, Billyja, Tommyja i Chucka.
{108697}{108783}Samo sam im želio priuštiti | pošten Božiæ ove godine.
{108785}{108825}Zaslužili su ga.
{108912}{109012}Dajem ti 20 minuta. | Stigneš se zagrijati i uzeti hrane.
{109019}{109112}A onda natrag u policijski | auto. Bez muljanja, jasno?
{109129}{109158}Èasna rijeè?
{109171}{109218}Kunem se životom svoje djece.
{109255}{109326}Moraš kušati šunku u medu.
{109328}{109408}To Blairey najviše voli. Božiæni klasik.
{109474}{109554}Hrana je ondje. | - Hvala, sinko, dužnik sam ti.
{109556}{109647}Jedemo je otkad je bila mala. | - Dobro došla kuæi, Blair.
{109649}{109707}Sretan Božiæ. | - Sretan Božiæ.
{109744}{109789}Ovo je sigurno tvoj deèko.
{109791}{109861}Jest. Dušo. | - Ja sam Enrique DeCardenal.
{109863}{109933}Zovi me Marty. | - Urbi et orbi, znamo i ime!
{109935}{110014}Je li to peruanski naglasak? | - Kako znate?
{110019}{110110}Živio sam ondje 5 g. Silno mi nedostaje.
{110367}{110436}Porazgovarat æu s Martyjem. | - Samo daj.
{110438}{110476}Šarmantan je!
{110478}{110556}Tko je to? | - Znaš Martyja, svi ga znaju.
{110715}{110756}Sretan Božiæ!
{110767}{110807}Baš ste dragi!
{110833}{110870}Bog vas blagoslovio.
{112413}{112485}Ako dopuštate, nazdravio bih.
{112502}{112600}Za moju novu obitelj i prijatelje.
{112604}{112707}Hvala vam što ste me tako srdaèno doèekali.
{113012}{113095}A ja sam htjela reæi...
{113118}{113173}Hvala vam svima.
{113175}{113250}Našim prijateljima i našim susjedima...
{113266}{113319}što su nam pomogli da ovo bude...
{113341}{113415}najljepši Badnjak do sada.
{113417}{113514}Pokazali ste nam što | znaèi pravo zajedništvo.
{113516}{113550}Hvala vam lijepa svima.
{113552}{113588}Sretan Božiæ.
{113914}{113967}Isto vrijedi i za mene, i to duplo.
{114101}{114131}Uzdravlje.
{114172}{114236}Deèki, može neka vesela?
{114552}{114577}G.
{115299}{115382}To je sve? Nisi mogao smisliti ništa bolje?
{115389}{115444}Ne znam držati zdravice.
{115503}{115551}Nakon svega što su uèinili...
{115583}{115662}ti nisi preko usta mogao | prevaliti obièno hvala?
{115681}{115732}Jesam. Kratko i slatko.
{115893}{115935}Još se ljutiš...
{115937}{116022}zato što nisi mogao | otiæi na svoje krstarenje!
{116024}{116066}Još stignemo.
{116073}{116121}Molim? | - Još stignemo otiæi.
{116140}{116174}Slušaj me.
{116205}{116286}Enrique i Blair mogu ostati, | neka se raskomote u kuæi.
{116288}{116356}Mi æemo otiæi pa æemo | svi imati romantièan odmor.
{116358}{116456}Tvoja je kæi preletjela | tisuæe kilometara da doðe kuæi...
{116460}{116525}sa svojim šarmantnim buduæim suprugom...
{116527}{116577}da bi s nama provela Božiæ.
{116579}{116611}Znaš...
{116640}{116701}šest sam tjedana planirao ovaj odmor.
{116723}{116787}Duže nego što oni hodaju!
{116841}{116934}Svi oni žrtvovali su svoj | Badnjak da bi pomogli nama!
{116997}{117061}Mislila sam da æe te možda to dirnuti.
{117067}{117181}Možda poèneš misliti na | druge, a ne uvijek na sebe.
{117205}{117270}Ali mislim da je to nemoguæe.
{117318}{117355}Šteta.
{117493}{117534}Pomaknite se unutra.
{117735}{117815}Kako ste? Sretan vam Božiæ.
{117840}{117881}Hladno je vani.
{118526}{118558}Bravo!
{119001}{119038}Luthere!
{119166}{119197}Snjegoviæ?
{119574}{119637}Sretan Božiæ, Luthere.
{119639}{119690}Sretan Božiæ i tebi, Walte.
{119692}{119771}Otišao si sa svoje zabave. | - Ma...
{119809}{119841}Kako je Bev?
{119858}{119924}Danas je jedan od boljih dana, hvala.
{119926}{120031}Krenuli smo vidjeti Blair, | ali snijeg je poèeo padati pa...
{120069}{120117}Kakav joj je deèko?
{120126}{120204}Zapravo je baš simpatièan mladiæ.
{120217}{120293}Sretan Božiæ, Luthere. | - I tebi, Bev.
{120295}{120377}Jesi li dobro? | - Baš si gadno pao.
{120379}{120469}Mogao sam i gore proæi. | Uže je moglo puknuti i onda...
{120498}{120566}Nora je rekla da vam donesem ovo.
{120583}{120695}Ja sam alergièan na svinjetinu, | a Bev baš ne voli meso.
{120697}{120779}Bez brige, | Melove su šunke obièno punjene...
{120781}{120862}samo želatinom i salom. Izvolite.
{120864}{120917}Lijepo od tebe, Luthere.
{121053}{121104}I tako... Uživajte.
{123114}{123169}Mogu li malo uæi?
{123224}{123253}Hvala.
{123341}{123415}Blair æe ostati kod nas deset dana...
{123421}{123475}pa neæemo na krstarenje.
{123477}{123557}Nora i ja voljeli bismo da vi odete.
{123640}{123686}Avion polijeæe sutra u podne.
{123688}{123754}Morate doæi dva sata prije.
{123757}{123853}Deset dana na Karibima. | Otoci, plaže i sve što uz to ide.
{123896}{123942}Odmor iz snova.
{124030}{124099}Ne možemo to prihvatiti. Nije u redu.
{124106}{124169}Nisam izvadio osiguranje.
{124171}{124250}Ako ga vi ne prihvatite, | cijeli aranžman propada.
{124253}{124327}Ne znam bi li me lijeènik pustio.
{124334}{124420}Ja ugovaram posao s Lexonom.
{124422}{124479}Benny je rekao da æe sutra možda svratiti.
{124481}{124534}Ne možemo ostaviti maèka.
{124567}{124612}Ovo mi darujemo vama.
{124614}{124693}Ovo je iskren, srdaèan...
{124697}{124764}božiæni dar bez ikakvih uvjeta.
{124779}{124875}Za dvoje nesebiènih ljudi...
{124887}{124965}koji se upravo koprcaju ne bi li našli izliku.
{125030}{125094}Benny je stvarno rekao da æe možda svratiti.
{125146}{125234}Bev, ruku na srce, Benny | nije kuæi došao godinama.
{125312}{125360}Sve je ovdje.
{125362}{125456}Avionske karte, vauèeri | za krstarenje, brošura.
{125493}{125585}Koliko to košta? Ako odluèimo iæi, | vratili bismo vam novac.
{125587}{125633}To je obièan dar, Walte.
{125648}{125739}Nema cijene, | nema povrata duga. Ne kompliciraj.
{125872}{125967}Na kartama nisu naša imena. | - Znam. Sredit æu to.
{125969}{126009}Što æemo s maèkom?
{126011}{126104}To je problem. Prekasno | je da zovemo prihvatilište.
{126106}{126153}Ne možemo ga ostaviti.
{126165}{126221}Možemo zamoliti Jude Becker.
{126230}{126268}Ona je alergièna.
{126326}{126368}Ja æu uzeti maèka.
{126381}{126433}Kako? | - Jesi li siguran?
{126460}{126486}Da.
{126506}{126552}Ma eto!
{126598}{126683}Možda ako ga ne budeš tako èesto gazio...
{126692}{126744}Snaæi æemo se.
{126852}{126932}Hvala ti lijepa. | - Sretan Božiæ.
{126963}{127048}Moram se vratiti na svoju zabavu.
{127317}{127371}Ovo nam puno znaèi.
{127418}{127450}Hvala ti.
{127488}{127526}Nema na èemu.
{127569}{127655}Znaèi li to da odsad moramo | biti meðusobno ljubazni?
{127685}{127741}Naravno da ne! | - Fino.
{127764}{127838}Svejedno mi nisi baš | previše simpatièan, stari.
{127840}{127872}Baš dobro.
{127906}{127964}Ni ti meni nisi prirastao srcu.
{128206}{128251}Bev, moramo se spakirati!
{128299}{128361}Luthere! Pomozi mi!
{128414}{128503}Nede! Za ime Božje, što radiš gore?
{128511}{128550}Blair je došla kuæi.
{128566}{128617}Frohmeyer je maknuo ljestve.
{128619}{128686}Ušao je, mene je zaboravio.
{128709}{128773}Cijelo si vrijeme gore?
{128862}{128922}Zamrznuo sam se za snjegoviæa!
{128935}{128976}Spustit æu te!
{129295}{129338}Što to radiš?
{129348}{129402}Zakleo si se životima svoje djece!
{129418}{129499}Koje djece? | - Upomoæ! Policija!
{129668}{129704}Polako.
{129731}{129791}Uði, popij nešto vrelo.
{129901}{129971}Silazi odande! Siði s krova!
{130020}{130055}Moj auto!
{130079}{130113}Jeste li dobro?
{130143}{130185}Što je u toj torbi?
{130256}{130287}Nije loše!
{130313}{130416}Svaka èast, Djede Mraze. Hajde!
{130456}{130550}Zakleo si mi se! | - Ne jurca mi se više za tobom.
{130639}{130736}Što se ovdje dogaða? | - Rekao sam da trebaš kišobran.
{130749}{130776}Molim?
{130920}{130966}Marty. | - Da.
{131009}{131111}Stani. Ti si onaj koji je | prodavao kišobrane na kiši?
{131113}{131180}Od neèeg moram živjeti. | Tako upoznajem drage ljude.
{131182}{131265}Moram iæi, ne smijem | propustiti ovakvo vrijeme.
{131267}{131338}Tad posao dobro ide. Hvala na zabavi.
{131340}{131419}Nema na èemu. Žao mi je | što moraš raditi na Badnjak.
{131421}{131504}Djed Mraz uvijek mora raditi na Badnjak!
{131556}{131604}Valjda mora.
{131844}{131883}Sretan Božiæ!
{132457}{132502}Bev Scheel je nazvala.
{132554}{132605}Možda sam se prevarila u tebi.
{132630}{132830}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan  
{132840}{132897}Ova je noæ puna iznenaðenja.
{132991}{133071}Preskoèiti Božiæ, kakva glupost!
{133089}{133131}Možda dogodine.
{134153}{134231}Sretan Božiæ!
{134235}{134272}Svršetak
