{1}{1}25.000
{1162}{1266}Sabrina, dobijemo li ovaj sluèaj, | bit æe to prava pobjeda.
{1267}{1344}G. Reynolds, ne trebate mi reæi.
{1394}{1431}Znam.
{1432}{1478}Èovjeèe.
{1479}{1549}Danas, mnogo mladih ljudi | završava u zatvoru.
{1550}{1626}Neki od njih to zaslužuju, | drugi ne.
{1627}{1731}{C:$0000FF}{y:ib} PRAVDA |{C:$FF0000}{y:b} IZA REŠETAKA 
{1732}{1809}Zanimljive su | njihove životne prièe.
{1810}{1859}Svi ih žele èuti.
{1910}{1981}Zatvor nije šala. | Znate li kako znam?
{1982}{2081}Od svoje 15. godine | ulazim i izlazim iz zatvora.
{2082}{2172}Najgore je bilo | u zatvoru Whitehead.
{2173}{2286}Znam što ti želiš. | No isprièat æu prièu na svoj naèin.
{2287}{2321}Moja je.
{2322}{2405}Taj mi je jebeni zatvor | promijenio život.
{2499}{2593}Pogledaj mi nokte. Navikla sam ih | ureðivati svaki tjedan.
{2594}{2625}Ja ne igram.
{2626}{2683}Jebi ga, trebala bi | više paziti na kosu.
{2684}{2725}Jebi se.
{2726}{2776}Svi ste vi lude...
{2777}{2836}...jer toga više neæe biti.
{2837}{2906}Nokti, kosa, stopala, | nema više tih sranja.
{2907}{2984}Brusit æete ih na zidu, | pizde jedne.
{2985}{3036}A što ste sve vi... | Nekog si ubila?
{3037}{3084}Da. Jesam.
{3085}{3133}Oh, ne. | Ja nisam nikoga.
{3134}{3198}Nisam ja ta Sabrina Downs.
{3199}{3271}Možda ih ima još 13 | na svijetu.
{3272}{3316}Nekoliko njih | i u Americi.
{3317}{3421}Znam da je pizda blijede puti, | èudne pletenice, i slièna meni.
{3422}{3470}Svi bi me bacili u | zatvor.
{3471}{3500}ZATVOR WHITEHEAD | DOWNS, SABRINA BR. 344
{3501}{3545}Preskoèit æu ovo...
{3546}{3593}...i zadaviti te! | - Što je?
{3594}{3653}Pizdo, èekaj dok stignemo!
{3654}{3709}- Samo èekaj. | - Ništa ti neæeš.
{3710}{3791}Sve ste vi pizde nevine, | ništa niste uèinile.
{3792}{3860}Mirno ste brale pamuk...
{3861}{3893}...i upale u nevolje.
{3894}{4012}Tu ste jer žele vaše guze, | niste vi posebne.
{4272}{4380}Ako malo digneš ruke.
{4381}{4426}Tako, curo.
{4510}{4567}Hvala.
{4569}{4607}Sve u redu.
{4609}{4675}Tako sam upoznala | Frances Shepherd.
{5029}{5140}Od sada ste vlasništvo | zatvora Whitehead.
{5141}{5188}Ja sam kapetan | Alan Dease.
{5210}{5247}Upamtite mi ime.
{5248}{5334}Obeæavam vam, | moje lice neæete nikad zaboraviti.
{5335}{5373}Pozornost, dame!
{5380}{5457}Više neæete moæi jesti, spavati...
{5458}{5582}...ili odlaziti u kupaonu | bez dopuštenja.
{5602}{5717}Ovo æu reæi samo jednom, | i neæu ponoviti.
{5734}{5832}Sve vrijeme nosite | vaš identifikacijski broj.
{5833}{5962}Propusti æe biti | disciplinski kažnjeni.
{5967}{6044}Zabranjeno je kockanje...
{6045}{6127}...korištenje zabranjenih tvari, | i ilegalnih seksualnih aktivnosti.
{6128}{6186}Tom Nelson ja bio upravitelj.
{6187}{6265}No, ovaj pizdek Dease, | upravljao je zatvorom.
{6266}{6356}Zabranjeno je voðenje poslova | i trgovina u bilo kojem obliku.
{6357}{6426}U njegovo vrijeme | promijenilo se 4 ili 5 upravitelja.
{6427}{6474}Dugo je bio tamo.
{6475}{6536}Crnjo je mislio | da sve pripada njemu.
{6537}{6605}Od jebenih krovova, | do štakora.
{6606}{6692}Zabranjeno je uništavanje | državnog vlasništva.
{6693}{6784}Dease? Pravi kreten.
{6785}{6887}Svaka pobuna...
{6888}{6952}...ili nepokornost...
{6953}{7030}...bit æe disciplinski kažnjeni.
{7031}{7081}- Jeste li razumjele? | - Da gospodine.
{7082}{7178}- Jeste li razumjele!? | - Da gospodine!
{7205}{7253}Dobro.
{7295}{7325}Dobro, dame.
{7326}{7436}Mi smo bile djevojke koje | žive u njegovoj jebenoj kuæi.
{7442}{7494}Stvarno je bilo jebeno.
{7944}{8005}Prekinite, dame.
{8006}{8068}Frances nije bila | poput nas ostalih.
{8069}{8106}Nova zatvorenica.
{8107}{8168}Nikad prije nije bila u | zatvoru.
{8193}{8305}Kao ni Lil' Mama, trudna u 17-toj, | naša propovjednica.
{8318}{8408}Nikki, ovo je Frances Shepherd, | upoznaj je s pravilima.
{8409}{8448}- Ne želim ju. | - Nemaš izbora.
{8449}{8530}Od mene može nauèiti | samo nepokornost.
{8531}{8582}Ma nemoj.
{8679}{8743}Bit æe ti ugodno. | Stavi stvari tamo.
{8744}{8834}Kasnije æemo urediti tvoj krevet, | napraviti više mjesta.
{9133}{9179}Znam kako ti je.
{9180}{9234}Treba vremena.
{9235}{9286}Doði da te upoznam | sa svima.
{9287}{9352}Ono je Nikki, | s njom se nije šaliti.
{9353}{9404}Drugi put je ovdje.
{9405}{9475}Nje se svi boje, | samo ja ne.
{9476}{9562}Slažemo se. Hladno je ovdje. | Nemamo grijanja.
{9563}{9620}Navuci nešto toplo | da ne oboliš.
{9621}{9681}Frances, kako si. | Ja sam Wet.
{9682}{9760}Izaði iz æelije, | ionako æeš biti dugo u njoj.
{9761}{9812}Dovoljno dugo da izludiš.
{9813}{9858}Ovo ti je kao blok.
{9859}{9926}Moraš paziti | s kim se družiš.
{9927}{9964}Vidiš one cure?
{9965}{10042}Liz-liz ekipa, | ako to voliš, dobro.
{10043}{10124}One cure tamo, | to su hotepke.
{10125}{10175}- Hotepke! | - Da!
{10176}{10266}Moja škvadra. | Mi smo zadužene za buðenje.
{10312}{10364}Daj zaveži, pizdo!
{10365}{10421}Vidiš na što mislim?
{10422}{10468}Zašto su te zatvorili?
{10469}{10522}- Zbog ubojstva. | - Ubojstva?
{10523}{10571}Ne lièiš na ubojicu.
{10572}{10652}Meni lièi na žutokljunu pizdu.
{10653}{10734}Frances, svako jutro ustajemo u 5:30.
{10735}{10783}- Tuširanje. | - Ne, jebeš to.
{10784}{10866}Treba znati kako | nas teroriziraju.
{10867}{10914}Moraš se zaštititi.
{10915}{10972}- Ništa nisam uèinila. | - Nije bitno.
{10998}{11052}Imam peticiju koju | trebaš potpisati.
{11053}{11113}Pokušavam uvjeriti sve | da je potpišu.
{11114}{11155}Gdje mi je olovka?
{11156}{11200}Zatvaranje. | Dvije minute.
{11210}{11268}- Dvije minute do zatvaranja. | - Dobro, svi.
{11269}{11357}Hajdemo, Wet, vidimo se.
{11358}{11406}U redu, Frances.
{11710}{11829}Nema tog novca za koji bi radila | u ovom jebenom mjestu.
{11923}{11956}Ovo je ludnica.
{11957}{12010}Znaš li da je Yvette | ugrizao štakor?
{12011}{12059}- Stvarno? | - Što?
{12060}{12153}Smiri se, ne daj im razloga | da nas bace u samicu.
{12154}{12187}Samicu?
{12188}{12247}Neæe gledati to sranje.
{12248}{12339}- Usporiti produktivnost. | - Tako je.
{12340}{12378}Novac mora teæi.
{12379}{12461}Frances, da ti objasnim | što radimo subotom.
{12462}{12517}Do podneva smo | u teretani.
{12518}{12613}Zatim sat vremena u dvorištu | i natrag na èišæenje...
{12614}{12694}...istovar kamiona, kuhanje, | sat za telefoniranje.
{12695}{12750}Plaæaju 1, 15 $ na sat. | Nije pošteno.
{12751}{12828}- Tako je to. | - Ne, nije pošteno, to je protuzakonito.
{12829}{12936}Jebeno robovlasništvo nije zakonito.
{12937}{13028}Dame, vrijeme da | zaradite stanarinu.
{13084}{13166}Sestro Frances, | dobro došla na plantažu.
{13671}{13769}Frances, što se tebi dogodilo? | Kako si dospjela ovamo?
{13770}{13813}Ubila sam supruga.
{13814}{13866}Bio je nesretan sluèaj.
{13867}{13921}Ma stvarno?
{13927}{14021}Ja sam ubila oèuha, | nije bio nesretan sluèaj.
{14041}{14083}Imaš li djece?
{14084}{14127}Da, jedno.
{14128}{14195}- Pogledaj. | - Oh, imaš medaljon.
{14196}{14258}Ime joj je Maxine.
{14261}{14329}Boluje od astme, | jako brinem za nju.
{14330}{14367}Baš je slatka.
{14368}{14405}- Hvala ti. | - Nema na èemu.
{14406}{14490}Svi mi ovdje imamo djecu. | Nikki takoðer.
{14491}{14547}Blizance, s njenom su majkom.
{14548}{14614}Wet ima dvoje.
{14624}{14695}Oduzeti su joj.
{14717}{14829}Curo, sredi se, ovdje je | grdo na majèin dan.
{14830}{14901}Razmatraju moj apel. | Izlazim.
{14902}{14939}Oh, stvarno?
{14940}{14977}I ja izlazim.
{14978}{15009}Oh, da? Kada?
{15010}{15086}Za pet godina.
{15087}{15144}Pet godina?
{15145}{15234}Da, pet godina.
{15429}{15476}Harvey, nemoj mi srati.
{15477}{15542}- Oprostite, kapetan Dease? | - Da?
{15543}{15585}Bok. Ja sam | Michael Meadows.
{15586}{15638}Nazvat æu te.
{15640}{15692}Treba li mi to | nešto znaèiti?
{15693}{15738}Ja sam novi službenik.
{15739}{15789}Trebam poèeti u srijedu.
{15790}{15850}Zašto si uranio?
{15851}{15967}Upravitelj je rekao da bih | trebao doæi i upoznati se.
{15968}{16027}- Da, ti si onaj novi studoš? | - Jesam.
{16028}{16084}- Drago mi je. | - I meni.
{16085}{16176}Sinko, nisi mogao naæi | nešto bolje?
{16230}{16313}Da budem iskren, | treba mi novac za pripravnièki.
{16314}{16378}To razumijem. Treba ti novac. | Svima nam treba.
{16379}{16413}- Nisam ljut na tebe. | - Dobro.
{16414}{16464}Nema frke, imamo ih.
{16465}{16507}- Daj... | - Budi tamo.
{16508}{16596}Nema frke, | imamo ih, imamo ih.
{16597}{16647}Kaže: "Imamo ih. Imamo ih."
{16648}{16714}- Razgovarajmo, privuci stolicu. | - Može.
{16715}{16773}Reci mi nešto o sebi.
{16774}{16848}Na post-diplomskom sam, pravo...
{16849}{16884}...kazneno pravo.
{16885}{16930}Namjeravam, | pomagati ljudima.
{16931}{16985}5 $ da nas nemaš.
{16986}{17066}To je Aisha, Deasova sadašnja pièkica.
{17067}{17123}Sve mu otkucava.
{17124}{17225}Aisha, ti bi okladu?
{17226}{17275}Neka Lil' Mama drži lovu. | Lil' Mama.
{17276}{17335}Èekaj, èekaj, èekaj. | Stani malo.
{17336}{17386}- Zašto da Lil' Mama drži lovu? | - Zašto ne?
{17387}{17447}Jer je vjernica, evo zašto.
{17448}{17498}Wet, neka te | Bog èuva i pazi.
{17499}{17561}Koji je ovo kurac, crkva? | Evo ti, kako želiš.
{17562}{17638}- Moj otac i... | - Tvoj otac i Nelson se dugo znaju.
{17639}{17680}- Da. | - Zajedno su studirali?
{17681}{17729}Da, jesu.
{17730}{17769}Ja sam jedinac.
{17770}{17848}Kao i moji roditelji. | Družimo se.
{17849}{17924}Prilagodit æu se.
{17925}{17979}Prestani lajati i serviraj.
{17980}{18044}- Što? | - Hajdemo.
{18080}{18134}Dobro, ja serviram!
{18135}{18264}To hoæeš, jebena kujo!
{18527}{18569}Kujo jebena!
{18599}{18632}Dease ovdje.
{18633}{18674}Tuènjava gospodine.
{18675}{18722}Zatvaraj ih, stižem.
{18723}{18762}Sinko, idemo.
{18763}{18823}Poèinje tvoje upoznavanje.
{18912}{18979}Nisi ti ništa kujo. | Hoæemo još?
{18980}{19073}Prekinite! Prekinite, proklete bile!
{19074}{19107}Koja je prva poèela?
{19108}{19143}- Ona! | - Pizdo lažljiva!
{19144}{19179}- Ona je poèela! | - Zaèepi!
{19180}{19280}- Aisha ju je udarila loptom. | - Zaveži, ne govorim tebi.
{19283}{19365}Shepherdice, koja je prva poèela?
{19385}{19446}Odgovori, prokleta bila.
{19447}{19499}Ova tamo.
{19500}{19561}Dobro, vodite te žene.
{19562}{19618}Hajdemo, pokret!
{19634}{19678}Otprati gðicu Nance | natrag u æeliju.
{19679}{19733}U redu ljudi, u redu.!
{19734}{19781}Prokletstvo, èule ste!
{19782}{19817}Ništa nisam uèinila!
{19818}{19905}Zatvori gubicu. | O tome ja odluèujem.
{19906}{19971}Èule ste, hajdemo!
{20083}{20144}Zatvorenice su | gore od životinja.
{20145}{20239}Treba ih disciplinirati. | Naroèito onu kuju Barnesicu.
{20240}{20316}Jedino ju ja | mogu disciplinirati.
{20324}{20386}Ide mi na živce.
{20432}{20480}Znaš, smiješno.
{20481}{20571}Malo se zapalila | na mene.
{20572}{20623}Vidio si kako me gledala?
{20624}{20704}- Da. Da. | - Jesi li vidio?
{20705}{20769}Postaje nemirna ako joj | ne posvetim dovoljno pažnje.
{20770}{20830}- Znaš kakve su mlade cure. | - Znam.
{20831}{20926}Bit æeš ti dobar. | Želim da upamtiš ovo:
{20941}{21025}Upravitelj te je zaposlio, | no budeš li imao problema...
{21026}{21115}...ja sam prvi i | posljednji kome æeš se obratiti.
{21116}{21176}Ja upravljam ovim jebenim zatvorom. | Ne Nelson.
{21177}{21218}Nemoj to zaboraviti.
{21219}{21261}- Razumio? | - Da.
{21262}{21322}Mi o vragu, | evo upravitelja.
{21323}{21368}- Upravitelj! | - Kako si?
{21369}{21421}Dobro je vidjeti te.
{21461}{21514}- Dobro je vidjeti te. | - Meni takoðer.
{21515}{21581}- Kako ti ide? | - Dobro, narastao si.
{21582}{21651}Da još jednom zahvalim. | Cijenim to.
{21652}{21748}Nije to ništa. Postane li gusto, | javi mi.
{21749}{21800}Uvijek možeš raditi | u uredu sa mnom.
{21801}{21877}- Jesi li preuzeo odoru? | - Nisam, namjeravam sada.
{21878}{21926}U redu, dobro, samo idi.
{21927}{22027}Dease, pazi na njega. | Njegova i moja obitelj se dugo znaju.
{22028}{22089}- Siguran sam da æe ispasti dobro. | - Da.
{22090}{22139}- U redu. | - Dobro je vidjeti te.
{22140}{22189}- Pazi se. | - G. Dease.
{22199}{22245}- Imam dobre vijesti. | - Što se dogaða?
{22246}{22335}Dolaze oni iz Wellcora, | pripremi svoje ljude.
{22336}{22424}Bili su tu nedavno. | Mislio sam da je sve u redu.
{22425}{22497}S nama da, | no ne i s onima iz Edgehuilla.
{22498}{22577}Wallcor namjerava prekinuti | suradnju s njima.
{22578}{22682}Doðe li do toga, | možemo nastaviti s radom.
{22683}{22766}Vidim, sviða mi se, baš dobro.
{22767}{22836}Wallcor namjerava uvesti | neke promijene.
{22845}{22927}Ljudi ne znaju da su | zatvori dobar posao.
{22928}{23048}Svi traže zaradu, | legalno ili ne.
{23061}{23133}Sve ostaje po starom, | samo rastu naše plaèe.
{23134}{23188}- To mi se sviða. | - Da.
{23189}{23214}- Bok. | - Bok, dušo.
{23215}{23293}- Kako ide? | - Dobro.
{23299}{23367}Zar ti nisam rekao | da me ne zoveš tako.
{23385}{23433}Želim ti zahvaliti.
{23434}{23515}Za ono s Nikki na odbojci.
{23516}{23571}Neka zna tko je | ovdje važan.
{23572}{23639}Doði, razgovarajmo.
{23707}{23749}- Jesam li ti nedostajao? | - Jesi.
{23750}{23792}I ti meni.
{23878}{23955}Jebena glupa pizdo!
{23971}{24020}Nisi ti važna.
{24021}{24090}Nemoj si ni pomisliti.
{24091}{24147}Jesi li razumjela?
{24178}{24251}- Da, kapetane. | - Nisam te èuo!
{24263}{24324}Da, kapetane.
{24402}{24452}Dobro.
{24554}{24619}Nosiš mi informacije?
{24629}{24670}Ne, ništa nisam èula.
{24671}{24720}Nisi?
{24819}{24880}Ne, ne, ne.
{24891}{24957}Prvo saznaj nešto.
{25048}{25110}Vratit æu se kad saznam nešto.
{25111}{25179}Curo, nešto si zaboravila?
{25180}{25248}Ne znam, jesam li?
{25289}{25353}Zaboravila si mi zahvaliti.
{25420}{25471}Prièekaj trenutak.
{25484}{25560}Sad me vidiš, sad ne.
{26056}{26149}- Dease ovdje. | - Bok, veliki, Što ima?
{26150}{26209}Fred, što se dogaða?
{26429}{26474}Jebeš njega.
{26639}{26713}- Ne! | - Drži jebena usta zatvorena!
{26714}{26754}Kurvo!
{26756}{26830}Ne zajebavaj se sa mnom, kujo!
{26831}{26903}Èuvaj se, pizdo...!
{26972}{27038}Kujo jebena.
{27064}{27108}Daj mi to.
{27122}{27162}Igra je gotova.
{27184}{27220}Jebo te!
{27221}{27276}- Ti gubiš, kujo. | - Pomoæ!
{27277}{27348}Pomoæ! Jebi ga.
{27353}{27431}Moja si, Nikki! Kunem se!
{27612}{27670}- Oprosti. | - Ne, oprosti ti meni.
{27671}{27718}Zajednièki ormariæi?
{27719}{27781}- Da, èuo sam. | - Ništa se tu ne može.
{27782}{27846}Zaboravio sam.
{27851}{27901}Kako ti ide?
{27903}{27968}Dosta dobro.
{27994}{28028}I meni se èini.
{28029}{28143}Cervantes je hladnokrvna kuja | koja se drži pravila.
{28144}{28211}...i meni isto.
{28220}{28341}Iskreno, nisam siguran | važi li isto i za policiju.
{28371}{28418}Nadam se da nije uvreda.
{28419}{28490}Moja obitelj ima dugu | tradiciju u policiji.
{28491}{28523}Oh, žao mi je.
{28524}{28586}Pokušale smo razgovarati | s njom o problemima.
{28587}{28663}No bila je ambiciozna, | i grebla se za èin.
{28664}{28751}Uvijek petlja s novim stražarima.
{28752}{28842}- Nisam to tako ni shvatila, ali... | - U redu, dobro, dobro.
{28843}{28992}...mogli bi na ruèak, | pa mi objasni.
{28993}{29090}Da, to bi bilo guba.
{29091}{29139}Kad bih bar mogao.
{29140}{29212}- Moram poslije ovoga uèiti... | - Dobro.
{29213}{29339}Možda nam se uskoro | ukaže prilika za razgovor.
{29340}{29453}Možda promijenim tvoje | mišljenje o policiji.
{29454}{29530}Dobro, u redu onda.
{29531}{29576}- Može. | - Dobro.
{29577}{29623}Èuvaj se.
{29624}{29694}- I ti, Cervantes. | - Dobro.
{29859}{29909}Zašto toliko | dugo telefonira?
{29910}{29963}Pusti je. | Razgovara s frizerkom.
{29964}{30021}Kuja nema drugu | prijateljicu.
{30031}{30081}Daj požuri! | Imam posla.
{30082}{30135}Da, narednih 10 godina.
{30136}{30246}- Znaš reæi "apel"? | - I za 10 godina, bit æeš tu.
{30247}{30323}I ti isto.
{30324}{30414}Frances Shepherd? | Upravitelj te želi vidjeti.
{30415}{30458}Ma daj, moram | telefonirati!
{30459}{30528}Rekao je da odmah doðemo.
{30761}{30852}Shepherd, bit æe bolje | ako progovoriš.
{30861}{30935}Tko zna, možda jednog dana | postaneš povlaštena.
{30991}{31043}- Kapetane | - Hvala vam, gospodine.
{31054}{31097}Shepherd.
{31193}{31262}- Što ti se dogodilo licu? | - Ništa.
{31281}{31345}Dobro, nekoliko pitanja.
{31346}{31393}Jesi li vidjela tko je ubo | Aishu Nance?
{31394}{31429}Ne gospodine, nisam.
{31430}{31487}Bila si u blizini | dok se to dogodilo?
{31488}{31604}Jesam, priznajem, vidjela sam Aishu, | nakon što sam izašla iz kupaone.
{31644}{31715}- Jesi li èula nešto? | - Nisam gospodine.
{31787}{31866}- Trebaš negdje biti? | - Ne želim propustiti telefoniranje.
{32005}{32063}Dobro, možeš iæi. | To bi bilo sve, hvala ti.
{32064}{32102}Hvala vama.
{32182}{32238}Ni jedna neæe progovoriti. | Gubimo vrijeme.
{32239}{32306}Ona zna što se dogodilo.
{32307}{32378}- Da zatvorim odjel? | - Prokletstvo, Dease, ne.
{32379}{32417}Ne možemo | zatvoriti odjel!
{32418}{32492}- Sve mora funkcionirati! | - Da, gospodine.
{32675}{32787}Ne želim te požurivati. | Pokušaj što kraæe. Dobro?
{32813}{32870}Kako je Michael? Kako mu je?
{32871}{32990}Nije loš, gospodine. | No ja bih radije vojnika.
{32991}{33038}Pouzdaniji su.
{33039}{33097}Studoši su za mene | malo premekani.
{33098}{33141}Ja sam bio studoš, | Dease.
{33182}{33251}Pokušavaš reæi da sam premekan?
{33267}{33316}Ne, gospodine.
{33332}{33381}Ne, gospodine.
{33415}{33463}Drž'se, mali.
{33674}{33730}Kako mamina velika cura?
{33731}{33802}Mamice, želim te vidjeti, mamice.
{33894}{33959}I ja tebe.
{33974}{34031}Slušaš li tetu Kim?
{34032}{34073}SluŠam.
{34074}{34150}ZaŠto te ne mogu vidjeti?
{34182}{34268}Mamice, želim te vidjeti.
{34269}{34340}Kontrola, vaŠe je | vrijeme proŠlo.
{34341}{34421}- Mamice. | - Dušo, bilo je...
{34805}{34866}Gðice Shepherd, | jeste li dobro?
{34917}{34962}Nisam.
{35029}{35096}Vaša je kæi dobro? | Sve u redu s njom?
{35097}{35203}Nije. Nadam se da neæete imati | problema zbog mene.
{35204}{35254}O, ne, ne.
{35255}{35293}Hvala.
{35294}{35346}Sve u redu.
{35390}{35459}Trebali bismo poæi.
{35898}{35990}Misliš li da je | Frances rekla nešto Nelsonu?
{35993}{36115}Nisu me bacili u samicu. | Nisu nas izolirali.
{36118}{36210}Ništa nije rekla. | Bolje da nije.
{36211}{36274}Frances nije takva.
{36275}{36393}Lil' Mama, ne trebaš li | èitati sveto pismo?
{36539}{36624}Meni je Rodney Dangerfield simpa.
{36625}{36687}Ima dobre viceve.
{36688}{36778}Kako znaš da ti | se žena deblja?
{36779}{36809}Ne znam.
{36810}{36891}Kad ti sjedne na lice, | i ne možeš èuti glazbu.
{36892}{36976}Nikki, dušo, ustaj.
{36977}{37036}Znam da si ti piknula Aishu.
{37037}{37088}- Budi dobra prema meni... | - Ne.
{37089}{37155}- I ja æu biti dobar prema tebi. | - Ne, pustite me!
{37156}{37240}Dobro, dobro, kujo! | Doði, kujo mala...
{37241}{37298}Nikki nije dobila batine | zbog Aishe.
{37299}{37370}Bilo je to izmeðu Deasea i Nikki.
{37371}{37478}Dease je bio lud za njom, | no ona je mrzila tog crnju.
{37479}{37565}Zato je izolirao nju i njenu grupu...
{37566}{37632}...kažnjavao ih je | za primjer drugima.
{37633}{37696}Svi su znali | što se dogaða.
{37697}{37769}U zatvoru nema tajni!
{38565}{38658}Vidiš li me s nekom debelom, | odmah zovem policiju.
{38659}{38741}- Što ima, kapetane? | - Vidimo se kasnije.
{38742}{38859}Žena mog prijatelja je tako debela, | da je dupe vukla iz dva puta.
{38894}{38980}Što imaš, Banks? | Nešto dobro?
{38981}{39051}Bože moj, domaæi | makaroni sa sirom.
{39052}{39119}Daj griz, kompa.
{39162}{39243}- Zar ti nije dojadilo grepsti se? | - Ne, nije.
{39244}{39287}Što se žališ, Banks?
{39288}{39359}Hraniš sedmoro, još jedna usta | ti ništa ne znaèe.
{39360}{39415}Ne, žena mi je opet trudna.
{39416}{39515}Daj odjebi, vi bijelci | ne vjerujete u kontracepciju?
{39572}{39638}Oèito, nikad èuli. | Vidi studoša, što ima?
{39639}{39748}- Donio sam piæe i... | - Dobro, stavi ovdje.
{39776}{39827}Da te upozorim...
{39828}{39931}...zahodi u odjelu 4, | još su zaèepljeni.
{39932}{39982}Jako smrdi.
{39983}{40019}Nije loše.
{40020}{40099}Bar ne smrde | neke tamo kuje.
{40119}{40153}Sve je polomljeno.
{40154}{40225}Uskoro æe nas | država zatvoriti.
{40229}{40271}Ja tražim novi posao.
{40272}{40321}Ne budi lud.
{40322}{40394}Da znaš što ja znam, | ostao bi.
{40395}{40483}Ako je u pitanju Wallcor, | ipak æu potražiti posao.
{40484}{40542}Reæi æu ti | u èemu je problem.
{40556}{40606}To je zbog ovih | mekušaca koji dolaze.
{40607}{40694}Imaju veze, | otimaju tuðe poslove.
{40695}{40735}Nije li tako, Michael?
{40736}{40783}Nisi èlan sindikata?
{40784}{40837}Rekao sam da je studoš.
{40838}{40947}On i Nelson se dugo znaju. | Nije li tako, Michael?
{40948}{41008}Ovdje se više | ne prolazi obuka.
{41024}{41057}Ne brini.
{41058}{41121}Znaš da ja pazim | na naše ljude.
{41124}{41181}Doði na sastanak | iduæeg petka.
{41182}{41243}Bit æu tamo, | moram hraniti obitelj.
{41244}{41278}Trebam posao.
{41279}{41336}Mislim da i ja trebam posao. | Zato sam ovdje.
{41337}{41400}Nemam obitelj, ni djece.
{41401}{41450}Moram plaæati studije.
{41451}{41498}Imam i kredite.
{41499}{41544}Ne želim | nikome oteti posao.
{41545}{41614}Pokušavam zaraditi dolar | kao i svi ostali.
{41618}{41671}Da sam znao | da æe ispasti ovako...
{41672}{41717}Što si oèekivao?
{41718}{41747}Oz?
{41748}{41803}Ne, ne oèekujem Oz.
{41804}{41859}Nikako, ali mislim...
{41860}{41911}Ponekad je teško, znaš?
{41912}{41986}Naèin na koji se | postupa sa ženama...
{41987}{42057}Postupa sa ženama? | O èemu ti prièaš?
{42058}{42109}- Ništa, ja... | - O èemu prièaš?
{42110}{42170}Te su žene lopovi, | ubojice i narkomanke!
{42171}{42224}Nemaju poštovanja | ni za što!
{42225}{42279}Jedini lijek je zatvoriti ih | i baciti kljuè.
{42280}{42369}Izaðu li iz bilo kojeg razloga, | neka Boga mole...
{42370}{42432}...da se više nikad ne vrate!
{42456}{42559}Isuse, sa kojeg si se ti | jebenog broda iskrcao?
{42604}{42666}Moram natrag na posao.
{42712}{42752}Vidimo se, Banks.
{42753}{42813}Da ti kažem još nešto.
{42815}{42911}Iduæi tjedan radiš | dvije smjene, razumiješ?
{42933}{43013}Prilika da zaslužiš | nešto love koja ti treba.
{43032}{43083}Studošu.
{43449}{43503}Nisam znao da sam u vojsci.
{43505}{43548}17 godina na ovom | mjestu.
{43549}{43659}Loše utjeèe na njega, | trebao bi promijeniti zanimanje.
{44334}{44377}Michael je bio obrazovan.
{44378}{44481}No, njegovo pravo obrazovanje | poèelo je radom u ovom zatvoru.
{44491}{44559}Mislio je da je sve | u rehabilitaciji.
{44613}{44711}Èim je zapoèeo s radom, | otkrio je mnoga sranja.
{44712}{44794}Otkrio je da smo skupa | roba na Wall Streetu.
{44795}{44849}Svi su zaraðivali | na našoj muci.
{44850}{44914}Šivale smo skijaške jakne | za dnevnicu od 1.50 $...
{44915}{45025}...za neku ženu iz Francuske | koja je plaæala tisuæu.
{45068}{45145}Današnji zatvori su poput negdašnjih | plantaža sa Juga
{45146}{45265}Korporacije namièu velike profite | koristeæi ljudski rad
{45266}{45356}Zatvorski moto: "Sagradi, i doæi æe!"
{45862}{45948}Lil' Mama? U èemu je problem?
{45954}{46054}- Oh, Frances, beba! | Oh, sranje!
{46096}{46174}Ne, nemoj ustajati, lezi.
{46220}{46253}U redu je.
{46254}{46284}Ne!
{46285}{46352}Lil' Mama's je bolesna! | Trebamo doktora!
{46353}{46391}Što se dogaða?
{46392}{46483}Stražaru, trebamo doktora!
{46484}{46566}Stražaru, hitno, trebamo pomoæ!
{46567}{46649}Bože moj! Gdje je stražar?
{46652}{46718}Ne dopustite da joj se što dogodi.
{46721}{46833}Lil' Mama, diši, opusti se. | Sve æe biti u redu.
{46932}{47015}Hvala Bogu. | Lil' Mama, odmori se malo.
{47016}{47096}Frances, krvari li?
{47166}{47244}Nema krvi, hvala Bogu.
{47375}{47429}Hej, Siddity.
{47443}{47508}Lil' Mama kaže da si | ubila svog starog.
{47509}{47567}Nisam htjela.
{47568}{47623}Samo sam ga željela | skinuti sa sebe.
{47624}{47685}Da prestanu udarci i batine.
{47686}{47757}- Dakle, nisi kriva. | - Mislim da nisam.
{47758}{47793}Ludo sranje.
{47794}{47834}Tuèe te...
{47835}{47902}...ti trpiš i ne braniš se.
{47903}{47986}- Trebala bi mi biti odvjetnica. | - Ne, ja bih ti trebala biti odvjetnica.
{47987}{48034}Bila sam dobra | odvjetnica.
{48036}{48128}- Wet, zbog èega si ovdje? | - Zbog neèeg glupog.
{48129}{48170}Upucala sam | plesaèicu u nogu.
{48171}{48245}Pred svjedocima.
{48246}{48323}No više neæe petljati s tuðim | muškarcima, nije li tako, Wet?
{48324}{48442}Ne neæe. Ali neæe više ni trèati.
{48450}{48514}Baš je žalim.
{48523}{48586}Znaš, baš glupa stvar.
{48587}{48644}Da, znam.
{49295}{49358}Zašto nisi rekla | da si bolnièarka?
{49359}{49424}Nitko me nije pitao.
{49541}{49633}Hvala što si pomogla Lil' Mami. | Zaista lijepo od tebe.
{49634}{49691}Nisi trebala, no ipak jesi.
{49692}{49757}Siddity, za mene si u redu.
{49758}{49806}- Nikki. | - Što?
{49807}{49894}Zovem se Frances. Zovi me tako.
{49895}{49974}Može, Frances.
{49994}{50081}Možeš mi biti mlaða sestra.
{50144}{50182}Imale smo samo | jedna drugu...
{50183}{50259}...i ponekad malo potpore izvana.
{50260}{50317}Na dan posjeta, | dolazila je Nikkina mama...
{50318}{50382}...dovodila je njenu djecu | koja su roðena u zatvoru.
{50383}{50444}Dease nije dopuštao | da ih Nikki vidi...
{50445}{50493}...prije nego ih je | predao njenoj majci.
{50494}{50587}Frances je bila uzbuðena, oèekivala je | dobre vijesti u vezi apela.
{50588}{50636}Tog su se dana | svi osjeæali dobro.
{50637}{50705}- Izgledaš lijepo. Kuda ideš? | - Hvala.
{50706}{50773}Dolazi njena mama, | s djecom.
{50774}{50848}- Lil' Mama, ne možeš šutjeti! | - Oprosti.
{50849}{50973}- Nisam željela da netko prije sazna. | - Uslikaj ih.
{50974}{51040}- Izgledaš lijepo. | - Sretna sam zbog tebe.
{51049}{51142}- Nisam to loše uradila! | - Ne, nisi.
{51146}{51210}Dakle, gðice Barnes.
{51227}{51308}Vidi, vidi. Gðicu Barnes, | gðice Barnes.
{51309}{51383}- Ne izgleda li lijepo? | - Idete li na maturalac?
{51410}{51450}Jako lijepo.
{51459}{51515}Gðice Shepherd, | imate posjetu.
{51595}{51669}- Vidimo se, Frances. | - Vidimo se.
{51688}{51767}Vratit æu se po tebe, gðice Barnes.
{51793}{51857}Dobro. | U meðuvremenu...
{51858}{51918}Kažu da se sranja dogaðaju.
{51919}{51994}Nikkina mama nije došla. | Francesin apel je odbijen.
{51995}{52097}Gðice Shepherd, | vaš je premještaj odbijen.
{52098}{52168}Bit æete s nama | još neko vrijeme.
{52182}{52284}Hajdemo dame, jedite! | Hajde, jedite!
{52293}{52359}Morale smo raditi sve duže i duže.
{52360}{52418}Ponekad smo morale | u krevet bez veèere.
{52419}{52537}Nakon toga i batina koje je | Nikki popušila, Weti je prekipjelo.
{52538}{52618}Rekla je da moramo poduzeti nešto, | i prekinuti s radom...
{52619}{52667}...poput poslušnih crnja sa | plantaže.
{52668}{52735}Vrijeme da preda upravitelju | našu peticiju.
{52736}{52776}Frances.
{52777}{52880}Pokušavam prikupiti | potpise za peticiju.
{52910}{52992}Sve se pogoršalo. | Upravitelj joj se nasmijao u lice.
{52993}{53047}I bacio peticiju u smeæe.
{53048}{53122}Prijavio je, | i produljio kaznu.
{53123}{53199}Zatim se ona svadljiva kuja Aisha...
{53200}{53247}...vratila iz bolnice...
{53248}{53304}...i sve je opet bilo | gadno k'o i prije.
{53305}{53361}Kako je u federalnoj bolnici?
{53362}{53430}Jesu li i tebi zašili rupu?
{53431}{53523}Jesu, no tvoja ju je mama | opet razvalila jezikom.
{53524}{53591}Dvorište, pizdo, na dvorištu!
{53592}{53659}Zatvorenice, | ostale ste bez slobodnog.
{53660}{53742}Nisam zatvorenica, kujo. | Ja sam kažnjenik.
{53743}{53811}Wet je teško prihvatila | upraviteljevu odluku.
{53812}{53920}Zato smo mi cure odluèile | malko je razveseliti.
{53921}{53997}Priredile smo mali tulum.
{54022}{54070}Jesmo.
{54071}{54182}Znaš što æu uèiniti | kad izaðem? Spavati.
{54190}{54255}Ma daj!
{54261}{54322}Dosta mi je...
{54323}{54461}...gasi svjetla, lezi spavat. | Ne želim da me programiraju.
{54496}{54550}Želim vlastite kljuèeve.
{54551}{54621}Da otvaram vrata, | dolazim i odlazim kad želim.
{54622}{54673}Znam što želiš, curo.
{54674}{54708}U to ime.
{54709}{54803}Za našu djecu i preživljavanje.
{54804}{54861}- Preživljavanje | - Èula sam.
{54949}{54992}Sranje, to je Dease.
{54993}{55049}- U ostavu! | - Hajde! Hajde!
{55073}{55122}- Hajde, hajde. | - Ne mogu brže.
{55123}{55176}Ne želim da me on uhvati. | Požuri.
{55177}{55215}Dobro.
{55216}{55259}Što to Dease èini tamo?
{55260}{55337}Nešto što ne bi smio.
{55372}{55416}Što to èini oko peænice?
{55417}{55507}Rekoh ti, nešto što ne bi smio.
{55522}{55576}Duga noæ, zar ne Meadows?
{55594}{55656}Da, toèno...
{55657}{55702}Uèio sam prošle noæi.
{55703}{55742}Težak život studenta.
{55743}{55807}- Nisam znao da ti je stalo, Banks. | - I nije.
{55900}{55941}Što je to bilo?
{55995}{56063}Kontrola, ovdje Cervantes. | Što je to bilo?
{56064}{56114}NeŠto je eksplodiralo u | kuhinji.
{56115}{56173}Razumjela, hajdemo.
{56174}{56248}Deaseovi prijatelji dobili su | ugovor da urede kuhinju.
{56249}{56303}Kao i uvijek, okrivio je nas.
{56304}{56352}Rekao je da je netko | bio nepažljiv.
{56353}{56409}Želio je otkriti tko.
{56410}{56491}Kao da nije on taj | koji uvijek sve sjebe.
{56492}{56571}Nelson je izolirao èitav zatvor.
{56572}{56722}Ukinuo posjete, telefonske pozive, | ukinuo je sve. Baš sve.
{56775}{56812}- Bok. | - Bok, èovjeèe.
{56813}{56852}- Drago mi je. | - I meni.
{56853}{56927}U subotu igram golf | s ljudima iz Wallcora.
{56928}{57005}Htio sam te ubaciti, | no veæ imamo èetvorku.
{57006}{57085}- Možda iduæi put, može? | - Hvala što si mislio na mene.
{57086}{57172}- Nema problema. | - Nije mi baš do golfa.
{57173}{57265}Nije, no ipak igraš neke igre, | zar ne Dease?
{57320}{57431}- Gospodine? | - Mislim na onu eksploziju.
{57432}{57476}Imaš li mi što reæi?
{57497}{57534}Nemam, gospodine.
{57535}{57605}- Je li netko prièao? | - Nije stvar u tome.
{57606}{57663}Problem je što je | došlo do mene.
{57664}{57716}Možda se i složim...
{57717}{57795}...da tvoji deèki preurede kuhinju.
{57796}{57883}Tvoj je posao da sve bude u redu.
{57884}{57970}Na kad mi u ured dolaze | s kojekakvim prièama...
{57971}{58058}...da me nije briga što ti radiš.
{58060}{58152}- Radim svoj posao. | - Ne, ne radiš.
{58178}{58274}Chante Wright je bila kod mene s | peticijom za koju ne znaš.
{58275}{58361}- Njena je peticija sranje. | - Što govoriš, Dease?
{58381}{58451}- Da zatvorenice imaju kontrolu? | - Ne, gospodine.
{58452}{58510}Da razjasnimo neke stvari.
{58511}{58606}Ja upravljam jebenim zatvorom, ne ti.
{58609}{58710}- Da, gospodine. | - Želim da prekineš fušariti.
{58711}{58782}Budeš li se i dalje | bavio takvim poslovima...
{58783}{58854}...vraèaš se gdje | sam te našao...
{58855}{58931}...u moèvare Floride, | na osmatraènicu.
{58962}{59041}Gdje æe ti komarci | zujati oko guzice.
{59072}{59116}Da, gospodine.
{59329}{59410}"Život je lijep kad si | voljen. Kako prolazi vrijeme...
{59411}{59494}...postaješ svjestan, | tko si i nestaje sjeme...
{59495}{59543}...sumnje."
{59969}{60035}Zaveži i mièi se.
{60061}{60118}Provjera. Provjera. Provjera.
{60119}{60183}Što tražiš? | Što to radiš?
{60184}{60244}Tražim ovo.
{60248}{60287}Ostavi moje stvari.
{60288}{60339}Što to radiš?
{60347}{60395}Platit æeš ti ovo kujo.
{60396}{60433}Pusti je.
{60434}{60485}Što si joj uèinio?
{60486}{60554}Da vidimo, možeš li pisati u rupi.
{60555}{60592}Jebi se.
{60595}{60687}Odmah je vodite u rupu.
{60799}{60869}- Wet, smiri se. | - Bog æe te èuvati, Wet.
{60870}{60916}Odstupi, idemo.
{60917}{60972}- Molim Te èuvaj je. | - U svoje æelije!
{60973}{61013}Ne dopusti da je | povrede.
{61014}{61081}Ne dopusti da je povrede.
{61083}{61126}Bože, pomozi joj.
{61219}{61271}Harvey, briga me.
{61272}{61322}Obavi to.
{61323}{61385}Isuse Kriste.
{61408}{61467}Pasji skot.
{61627}{61679}Vidi, vidi.
{61719}{61772}Ti si moja nova djevojka.
{61773}{61847}Da gospodine, mijenjam Sabrinu.
{61873}{61945}- Kako ti je ime, mlada damo? | - Rose.
{61946}{61990}Rose.
{61991}{62040}Jako lijepo ime.
{62041}{62075}Hvala.
{62076}{62151}Moja se baka zove Rose.
{62209}{62291}Rose, dobro èistiš.
{62356}{62395}Vidi...
{62396}{62443}Propustila si ono gore, | Rose.
{62444}{62528}Pauèina što tamo visi. | Vidiš li?
{62542}{62602}Volim da je sve uredno.
{62603}{62669}Uzmi stolicu.
{62676}{62753}Oèisti tu pauèinu.
{62987}{63056}Rose, stvarno dobro èistiš.
{63173}{63237}Ti i ja æemo se dobro slagati.
{63238}{63287}Jesam li slobodna?
{63288}{63337}Ja te ne zadržavam.
{63338}{63398}Lil' Mama nam je isprièala | što je Dease pokušao...
{63399}{63474}...Wet je izašla iz rupe s | ožiljkom na licu.
{63475}{63538}Postalo nam je svejedno | što æe se dogoditi.
{63539}{63632}Znale smo da moramo uzvratiti. | Trebala nam je prilika.
{63639}{63689}Mike je rekao da | dolazi Wallcor.
{63690}{63752}Poèele smo s pripremama.
{63830}{63899}Imam nešto za tebe.
{64155}{64193}Dobro.
{64372}{64436}U nekoliko dana | prikupile su sve potpise.
{64437}{64551}Organizirale smo se | toèno Deaseu pod nosom.
{64846}{64884}Što su rekli?
{64885}{64942}Wallcor je odgodio.
{64943}{65007}- Za kada? | - Iduæi èetvrtak.
{65008}{65079}Sve je teklo kako treba, | dok Lil' Mama nije došla...
{65080}{65156}...i otkrila da je | Wallcor odgodio.
{65157}{65270}Pošemerili su nam plan, | pa smo mi uzvratile istom mjerom.
{65546}{65603}Koristile smo papiriæe | za prijenos poruka.
{65604}{65644}Nije smjelo biti | zajeba.
{65645}{65740}Sve bi upropastile | veæ na poèetku.
{66261}{66334}Molila sam cijelu noæ. | Bit æe u redu.
{66335}{66378}- Razgovarala si s Deaseom? | - Jesam.
{66379}{66474}Ja s ovim nemam ništa, | ne raèunajte na mene.
{66475}{66509}Vidi...
{66510}{66586}Ti proèitaj zahtjeve, | ja æu ih uruèiti.
{66587}{66626}Zašto? Ti si glavna.
{66627}{66728}Kad ustanem, znat æe | da se sprema neko sranje.
{66775}{66856}- Onda æu ja. | - Dobro, ja æu biti uz tebe.
{66857}{66913}Dobro.
{67450}{67522}- Kapetane Dease, ja sam Miller. | - Oèekivali smo vas.
{67523}{67560}- Miller. | - Nelson.
{67561}{67612}- Stigao si. | - Èovjeèe, što se dogaða?
{67613}{67653}Sve je kako treba.
{67654}{67733}Ono iz prve, u 17-tu, | bilo je sjajno.
{67734}{67790}- Trebao si biti tamo. | - Nisam mogao.
{67791}{67861}Budimo ozbiljni, naše | zatvorenice obožavaju svoj posao.
{67862}{67909}Ovdje stjeèu vrijedna | iskustva...
{67910}{67963}...a vi imate proizvod | za plasiranje.
{67964}{68017}Radna snaga je | ovdje isplativija.
{68018}{68077}Otkrit æu ti tajnu.
{68078}{68143}Radnici ne mogu dati otkaz.
{68204}{68293}G. Dease i ja se radujemo | suradnji s vama.
{68294}{68325}Stvarno, stvarno.
{68326}{68394}Mr. Dease je pravi buldog. | Nije li?
{68395}{68455}Pa, svaki duæan treba jednog.
{68456}{68523}Bit æete oduševljeni | s našom organizacijom.
{68524}{68575}Uspjeli smo udvostruèiti...
{68576}{68664}Impresioniran sam. Posljednja | dva kvartala su izvrsni.
{68665}{68740}Da su bar svi naši | isporuèitelji toliko vrijedni.
{68741}{68813}Naredna dva kvartala, | bit æe još bolja.
{68814}{68851}Hajdemo razgledati.
{68852}{68928}Ove žene kroje | skijaške jakne.
{68929}{69025}Jako su dobro obuèene. | Koristimo timski rad.
{69026}{69113}Ona grupa šiva krojeve...
{69114}{69172}...zatim postavljaju | zatvaraèe.
{69236}{69267}Imamo i...
{69268}{69312}Koji...?
{69324}{69386}Ovo je dobronamjerna | obustava rada.
{69434}{69524}- Tražimo reformu. | - Zaveži i sjedni!
{69525}{69573}Tražimo pravedan tretman | za zatvorenice.
{69574}{69619}Koji je sad vrag?
{69620}{69657}Bolje uvjete rada.
{69658}{69694}- Bolje grijanje. | - Shepherdice.
{69695}{69810}Prestanak svakodnevnog brutalnog | premlaæivanja i silovanja.
{69811}{69879}Natrag na posao, proklete bile. | Natrag na posao.
{69885}{69923}Prihvatite | našu peticiju.
{69924}{70023}Neka svi znaju što | se dogaða iza ovih zidova.
{70049}{70081}Dease.
{70082}{70134}Je li ovo neka šala?
{70135}{70188}Sve ove žene | stoje uz ove zahtjeve.
{70189}{70254}Imamo malih problema | s ove dvije žene.
{70255}{70310}Kao što vidite, | niti jedna nije uz njih.
{70516}{70558}Ja sam uz nju.
{70559}{70609}Sabrina.
{70612}{70679}- Nadam se da znaš što èiniš. | - Ja sam uz nju.
{70680}{70716}Ja sam uz nju.
{70717}{70766}Ja sam uz nju.
{70767}{70817}Ja sam uz nju.
{70818}{70856}Ja sam uz nju.
{70857}{70903}To.
{70924}{70976}Platit æete za ovo.
{70977}{71054}- Natrag na posao, proklete bile. | - I ja sam s njima.
{71068}{71116}Molim vas.
{71129}{71182}Uzmite ovo.
{71214}{71285}Natrag na posao.
{71286}{71341}Jebi se.
{71403}{71448}Što to radiš?
{72033}{72083}Vodi kuju u rupu.
{72084}{72219}Natrag na posao. Natrag na posao. | Natrag na posao.
{72636}{72683}Koliko smo dugo ovdje?
{72739}{72789}Tri?
{72793}{72835}Èetiri dana?
{72836}{72878}Koliko.
{72926}{73055}Privikni se. Bit æemo ovdje | neko vrijeme.
{73085}{73140}1.
{73189}{73233}2.
{73264}{73324}31.
{73353}{73414}3, 4.
{73490}{73534}8.
{73561}{73595}9.
{73619}{73653}35, hajde.
{73654}{73712}Hajde Nikki, možeš ti to.
{73713}{73759}Hajde.
{73795}{73864}Veæ sam 6 dana ovdje.
{73865}{73954}Veæ danima me | nitko nije obišao.
{74016}{74096}Jebeš ovo, jebeš ovo.
{74097}{74149}Hajde Nikki, možeš ti to.
{74156}{74247}- Ostani prisebna. Hajde, idemo. | - Zašto si tako sigurna?
{74248}{74293}Jer imam malu curicu.
{74294}{74371}Èeka da se vratim kuæi.
{74481}{74567}- Kako joj je ime? | - Maxine.
{74694}{74748}Oh, Maxine.
{74826}{74908}Maxine. Dušo, gdje si?
{74909}{74974}Oh, moj Bože, Ne èekaj... | Oh moj...
{74975}{75013}Frances?
{75084}{75173}Frances? Oh, zove se Maxine.
{75192}{75262}Ime joj je Maxine.
{75297}{75348}Ime joj je Maxine.
{75359}{75393}Moja se cura...
{75394}{75452}...zove Maxine.
{75459}{75528}Zašto su te zatvorili?
{75529}{75591}Oružana pljaèka.
{75620}{75702}Iz nekog razloga, žene rade | razna sranja...
{75703}{75760}...za muškarca.
{75831}{75888}No bio je pravi muškarac.
{75930}{75981}Zvao se Smalls.
{75989}{76036}Tvrdio je da je igraè.
{76040}{76119}No bio je obièni narkiæ.
{76122}{76163}Predložio je...
{76164}{76229}...da opljaèkamo starog dilera.
{76231}{76267}Nije bio dovoljno | pametan...
{76268}{76324}...da to obavi bez mene.
{76343}{76392}Trebali smo biti | Bonnie i Clyde.
{76393}{76454}Pokupiti malo onog ledenog, | nešto od onog sranja...
{76455}{76511}...koja gledamo na | reklamama.
{76564}{76638}Samo, Smalls nije bio Clyde.
{76659}{76757}Ubili ga, a ja sam završila ovdje.
{76758}{76806}Ponovno.
{76854}{76922}Nikad nisam željela | nekoga ozlijediti.
{76923}{76984}Uvijek sam poštivala pravila.
{76985}{77041}Ja nikada.
{77042}{77114}I završile smo na istom mjestu.
{77115}{77168}Kakva li sranja.
{77169}{77223}Upoznala sam Grega.
{77230}{77294}Jako sam ga voljela.
{77295}{77370}Pitam se što sad rade.
{77393}{77475}- Da. | - Nikad se nisam drogirala.
{77495}{77530}Kakav je to osjeæaj?
{77531}{77614}Nadam se da æe Dease | dobiti što zaslužuje...
{77623}{77686}...i da æu ja gledati.
{77845}{77900}Nikki, ne bježi od mene.
{77932}{77990}Vrijeme za fiks.
{78003}{78061}Imam nešto za tebe.
{78089}{78152}Razmisli Nikki.
{78153}{78225}Dugo æeš biti ovdje.
{78259}{78322}Ovo æe ti pomoæi | da brže proðe vrijeme.
{78348}{78385}Hajde.
{78386}{78436}Kušaj malo.
{78439}{78496}- Što se ovdje dogaða? | - Peder jebeni!
{78497}{78566}Ostavit æu ovo za tebe.
{78628}{78678}Hajde, Nikki.
{78694}{78745}Uzmi malo.
{78746}{78801}- Nikki? | - Popustit æeš.
{78802}{78865}Nisi ti tako jaka.
{78901}{79000}Nikki ne, èuj me, ostani prisebna, | ponavljaj za mnom.
{79002}{79066}Pet puta dva, pet puta dva. Ponovi.
{79067}{79150}To je 10. Pet puta tri je 15.
{79167}{79234}Hajde Nikki! Ponavljaj za mnom. | Ostani prisebna.
{79288}{79348}Pet puta èetiri...
{79374}{79416}...je 20.
{79426}{79485}Pet puta pet je 25.
{79553}{79602}Pet puta šest...
{79603}{79654}...je 30.
{79694}{79754}Ne èujem te.
{79766}{79799}Pet puta sedam...
{79800}{79832}Je koliko?
{79833}{79889}- 35. | - To.
{79951}{80008}- Pet puta osam. | - Da?
{80009}{80079}- Je 40. | - Da, toèno.
{81376}{81437}Barnes, vrijeme je.
{81467}{81521}Pokreni se.
{81525}{81570}Hajde.
{81628}{81676}Shep, idemo.
{81704}{81748}Hajde.
{81827}{81877}Hajde, ustaj.
{81970}{82031}Mièite guzice.
{82041}{82112}Nikki i Frances su smatrale da | štrajk nije ništa znaèio.
{82113}{82187}Nisu bile u pravu. | Meni je nešto znaèio.
{82188}{82284}Nikad prije nisam imala stav.
{82285}{82387}Taj sam dan zauzela stav | i imam ga još danas.
{82390}{82467}Kapetan ima iznenaðenje za tebe.
{82583}{82649}Gulit æeš ovaj zid.
{82650}{82720}- Sama? | - Tako sam rekao.
{83847}{83916}Što kaže slijepac kada prolazi | pored ribarnice?
{83917}{83971}"Dobro jutro, dame."
{84144}{84190}Ovaj?
{84218}{84293}Banks ti je rekao | da guliš ovaj zid.
{84294}{84357}- Nije, rekao je da gulim... | - Nisam.
{84358}{84407}Ne znaš gdje je dopušteno?
{84408}{84455}- Nisam rekla... | - Što nisi rekla?
{84456}{84515}- Što nisi rekla? | - Da gulim ovaj zid.
{84516}{84554}Banks je rekao da | gulim.
{84555}{84598}Banks, jesi li joj rekao, | ovaj zid?
{84599}{84652}Ne, lažeš. | Rekao je, ovaj zid.
{84653}{84725}- Banks je rekao, da gulim ovaj zid. | - Banks je rekao, ovaj zid.
{84726}{84785}- Èula sam što je Banks rekao. | - Vodi je u rupu.
{84786}{84822}Vodi je natrag u rupu.
{84823}{84878}- Ne. | - Vodi pizdu u rupu.
{84879}{84957}Ne, molim vas, nemojte. | Uèinit æu sve što kažete.
{84958}{85025}Sve što kažete, kapetane. | Samo nemojte, ne, ne.
{85026}{85150}- Reci da æeš biti poslušna. | - Bit æu poslušna, obeæavam.
{85151}{85247}Reci da æeš biti poslušna.
{85248}{85305}Reci da æeš biti poslušna.
{85306}{85345}Reci.
{85346}{85416}Reci: " Bit æu poslušna, | kapetane Dease".
{85417}{85467}Reci.
{85498}{85576}Bit æu poslušna, kapetane Dease.
{85656}{85707}Pusti je.
{85804}{85858}Nismo završili.
{86279}{86345}Shepherd, imaš 15.
{86367}{86401}Bok.
{86468}{86530}Ne izgledaš dobro.
{86531}{86612}To je zatvorski ten. | No, plaža nema.
{86613}{86658}Gdje je beba?
{86665}{86772}Pokušala sam te vidjeti. | Rekli su da nema posjeta.
{86773}{86832}Bila sam u samici.
{86939}{86980}Oh, nemoj. Hej, hej.
{86984}{87033}Nemoj plakati.
{87034}{87064}Nemoj plakati.
{87065}{87143}Nije bilo lagano, | no sad sam vani.
{87144}{87189}Ovdje sam.
{87208}{87269}Je li beba u autu?
{87277}{87324}Nisu ti dopustili | da je dovedeš.
{87325}{87373}Ne.
{87398}{87477}Rekla sam Walteru.
{87478}{87537}Rekla sam Walteru | da se kloni uliènih bandi.
{87538}{87594}- Kim, gdje je beba? | - Izbila je tuènjava.
{87595}{87660}- Nešto mi muljaš. | - Walter mi nije rekao.
{87661}{87695}- Metak. | - Kakav metak?
{87696}{87735}Pogodio je Maxine.
{87748}{87798}Umrla je prije 2 tjedna.
{87808}{87875}- Pokušala sam te nazvati. | - Ne, lažeš.
{87902}{87940}Ne. Ne.
{88052}{88113}Ne. Ne. Lažeš.
{88114}{88155}Ne.
{88156}{88190}Ne.
{88191}{88242}Ne.
{88246}{88289}Ne.
{88290}{88379}Ti lažljivice. Ne Maxine.
{88380}{88447}Ne.
{88776}{88820}Što si èula?
{88821}{88893}Pod stalnom je prismotrom.
{88908}{88961}Jebi ga.
{88963}{89028}Èula si se s starim?
{89036}{89145}Jesam, odvjetnik kaže | da trebamo èvrste dokaze.
{89177}{89254}Naæi æemo ih.
{90264}{90327}Frances, bez obzira što mislila...
{90328}{90413}...iskreno žalim za tvojom kæerkicom.
{91442}{91503}Što kuja želi?
{91509}{91555}Ne znam.
{91578}{91632}Nick, u redu je.
{91654}{91711}Kako æete ga srediti?
{91883}{91946}Aisha, o èemu prièaš?
{91947}{91999}Nikki, znaš ti o èemu prièam.
{92000}{92042}Deaseu.
{92043}{92117}Znam da nešto planirate.
{92223}{92300}Mislile smo da ti je | Dease ljubavnik.
{92411}{92479}- Oh, moj Bože. | - Što se dogodilo?
{92480}{92555}Nešto što se | više neæe ponoviti.
{92565}{92648}Želim tog jebivjetra. | Jako to želim.
{92658}{92741}I da smo nešto planirale, | što nismo...
{92742}{92829}...zašto misliš da bismo | tebi vjerovale?
{92861}{92907}Pošteno pitanje.
{92918}{92999}Kunem se životom mog malog Shortyja.
{93015}{93110}Ako se ne osvetim tom | jebenom crnji, vi možete...
{93111}{93153}Vi možete srediti | mene.
{93194}{93271}I hoæemo, Aisha.
{93292}{93352}Znam da niste | završile s Deaseom.
{93379}{93448}Znam da nešto planirate.
{93449}{93526}Ja se želim osvetiti | jebenoj svinji.
{93535}{93581}Možda možemo | sklopiti posao.
{93582}{93660}Da, zvat æemo te u vezi toga.
{93827}{93888}Sjebao ju je.
{93908}{93976}Napokon su nešto isplanirale.
{93977}{94042}No trebale su pomoæ iznutra.
{94053}{94094}Pa su pitale Michaela.
{94095}{94171}Oprosti, možemo li razgovarati?
{94172}{94283}Deaseovi su dani bili odbrojani, | spremale su mu nešto gadno.
{94422}{94468}Kapetane.
{94469}{94516}Uði.
{94680}{94727}Što tražiš ovdje?
{94728}{94783}Mislio sam | da si ljuta na mene.
{94784}{94822}Nisam.
{94843}{94903}Nedostajao si mi, ljubavnièe.
{95056}{95092}Rose.
{95093}{95142}Za danas je dosta.
{95143}{95191}Možeš iæi.
{95289}{95341}Odmah se vraæam.
{95363}{95404}Ostani ovdje.
{95664}{95754}- Dobro izgledaš. | - Dakle, nisi ljuta na mene?
{95763}{95873}- Kapetane, zaboravila sam Bibliju. | - Rose, uzmi je, i idi.
{95971}{96010}Izgledaš dobro | danas.
{96107}{96169}Rose, požuri.
{96170}{96241}- Isuse. | - Hvala, gospodine.
{96314}{96359}Doði.
{96363}{96406}- Da vidim. | - Prestanite.
{96407}{96468}- O èemu prièaš? | - Prestanite.
{96469}{96542}- Nemoj se igrati sa mnom. | - Ništa nisam uradila.
{96543}{96636}- Promijenila si miŠljenje? | - NiŠta nisam uradila.
{96637}{96697}- Molim vas, niŠta nisam uradila. | - Zaveži.
{96698}{96761}Molim vas.
{96786}{96864}Molim vas, prestanite. | Zašto mi to radite?
{96883}{96930}Sranje.
{96963}{97014}Oh, Bože.
{97015}{97057}Oh, Bože.
{97058}{97089}Oh, sranje.
{97090}{97147}Mogu li dobiti ruènik...
{97148}{97190}...gospodine?
{97316}{97371}Da, da, naravno.
{97475}{97538}Oh, sranje.
{97543}{97608}Oh, sranje.
{98345}{98393}Odjebi sad odavdje.
{98394}{98493}Plan je: Lil' Mama | æe predati traku Michaelu.
{98520}{98600}Michael æe predati traku | Wetinom deèku.
{98604}{98680}Wetin deèko æe predati traku | nekom drugom...
{98681}{98727}...tko ima veze s | guvernerom.
{98728}{98790}- Zaveži. | - Ništa nisam uradila.
{98910}{99015}Lil' Mama se vratila po traku | s praznim koricama za Bibliju.
{99016}{99102}No vrata su bila zakljuèana, | a Dease je rano otišao.
{99103}{99196}Morala je pokušati ponovno | iduæi dan.
{99296}{99385}Prokleta metla. | Jebeni zatvor.
{99476}{99559}Rose, zar ti za danas | nije dosta?
{99566}{99612}Vrijedna si ti dama.
{99613}{99657}Èitavo jutro èistiš.
{99664}{99709}Mora da si umorna.
{99710}{99776}Znam da volite èistoæu.
{99777}{99837}Rose, baš slatko od tebe.
{99838}{99877}Zaista slatko.
{99878}{99944}Primijetio sam kako si lijepa.
{99945}{99994}Gdje je jebeni Dease?
{99995}{100050}Sviða mi se tvoja kosa.
{100057}{100105}Hvala vam.
{100168}{100200}Ovdje Dease.
{100201}{100250}Samo tebe èekamo.
{100251}{100330}- Ne možete bez mene? | - Možemo, ali trebaŠ za glasanje...
{100331}{100406}Dolazim odmah. Rose.
{100407}{100478}Izgleda da želi doæi posljednji.
{100479}{100542}Koji ga kurac zadržava?
{100674}{100722}Pokušavaš otiæi?
{100723}{100781}Prestanite, molim vas.
{100782}{100892}- Rose, znam da to voliš. | - Ne, ne volim, to je grijeh.
{100909}{100981}Kao i ono što si uèinila svom ocu?
{100982}{101033}Nije mi bio otac.
{101034}{101073}Oèuh.
{101074}{101111}Ljubavnik.
{101112}{101168}Otac tvog neroðenog djeteta.
{101169}{101233}U èemu je razlika?
{101234}{101277}Rose, nisi ti djevica.
{101278}{101335}- Jesi li? Jesi li, Rose? | - Prestanite.
{101336}{101390}- Nisi ti djevica. | - Prestanite.
{101391}{101466}Ti nisi jebena djevica, Rose. | Meni ne bi dala.
{101467}{101525}- Dat æeš mi, dat. | - Ne. Ne.
{101526}{101586}Zaveži.
{101590}{101649}Lezi dolje.
{101684}{101735}Molim vas, nemojte. | Nemojte.
{102066}{102130}Gospodin je moje svijetlo i moj spas, | straha nemam.
{102131}{102213}Gospodin mi daje snage, | straha nemam.
{102214}{102303}- Oh, oèe i majko moja... | - Lil' Mama, gdje si?
{102428}{102463}Što se dogodilo?
{102464}{102537}- Nije se pojavila. | - Prokletstvo, idem je potražiti.
{102538}{102615}Dease je trebao biti | na sastanku.
{102631}{102670}Nešto nije u redu.
{102769}{102890}- Bože, što se dogodilo? | - Možda je ozlijedio bebu.
{102891}{102954}Sranje, pomozi mi. | Pomozi mi.
{102955}{103007}- Bože, ona krvari. | - Oh, moj Bože.
{103008}{103067}Brzo s njom u ambulantu.
{103130}{103176}- Bit æeš dobro. | - Pomoæ.
{103177}{103233}- Mjesta. Mjesta. | - Pomoæ.
{103234}{103286}Okreni je.
{103568}{103616}Što joj je?
{103647}{103687}Ima pobaèaj.
{103688}{103722}- Ne. | - Beba?
{103723}{103798}Ne mogu pomoæi, | moram nju spasiti.
{103799}{103851}- Ne. Ne. | - Drži se, Lil' Mama. Drži se.
{103852}{103904}- Dobro je... U redu je. | - Ne.
{103905}{103951}- Što se dogodilo? | - Tu smo.
{103952}{104045}Silovao me kapetan.
{104046}{104108}- Silovana sam. | - Silovana?
{104130}{104169}Oh, moj Bože.
{104205}{104256}Držite je.
{104271}{104329}Ne idemo nikuda.
{104336}{104376}Umirite je.
{104466}{104505}- Ne. | - Izmjerite tlak.
{104506}{104541}Mogu pomoæi, | bolnièarka sam.
{104542}{104583}Zastoj srca.
{104584}{104622}Dajte defibrilator.
{104623}{104667}- Evo. | - Drži se, Lil' Mama. Drži se.
{104668}{104732}- Molim te, Lil' Mama, drži se. | - Pusti je. Pusti je.
{104733}{104792}Pusti je, Nikki. Pusti je! .
{104806}{104856}Odmakni se!
{104863}{104920}- Još jednom. | - Drži se, Lil' Mama. Molim te.
{104921}{105019}Diši, diši. Hajde diši.
{105059}{105119}- Možete ugasiti. | - Što?
{105120}{105160}- Umrla je. | - Ne.
{105167}{105212}Ne. Lil' Mama.
{105245}{105300}Djevojke, morate iæi.
{105311}{105373}- Izvedi ih. | - Jako mi je žao, ne.
{105374}{105411}- Ne, Mama, ne. | - Mrtva je.
{105412}{105459}Ovo ne pomaže.
{105460}{105500}Jebi ga.
{105501}{105540}Stražaru, izvedi ih.
{105541}{105582}Zvat æu | kapetana Deasea.
{105583}{105686}Dalje od telefona. Dalje od | telefona, proklet bio.
{105797}{105874}Nikki, ne razmišljaš, | uzmi mu telefon.
{106072}{106116}Ne.
{106138}{106183}Moram ti staviti | lisice.
{106302}{106346}Ne idemo mi nikuda!
{106347}{106410}Poèelo je. | Ne idemo mi nikuda!
{106434}{106523}Cervantes, sluŠaj. | Izoliraj ambulantu.
{106524}{106566}Razumjela. Sranje.
{106569}{106617}Frances, što radiš?
{106618}{106663}Što moramo.
{106950}{107009}Bacit æu te opet u rupu.
{107118}{107206}Da znaš što i ja, | legla bi i umrla odmah.
{107213}{107254}Poslije tebe | pizdo jebena.
{107958}{108025}Jebi se, pizdo!
{108072}{108158}Doktore, jeste li dobro?
{108208}{108290}- Tko god bio, odmah stani! | - Uzmi njegove lisice.
{108291}{108358}- Tko æe sad u rupu? | - Imamo taoce.
{108359}{108469}Približite se | i upucat æemo taoce.
{108533}{108626}Hitno izolirajte. | Ponavljam, hitno izolirajte.
{108627}{108717}- Jesu li zadržane u ambulanti? | - Jesu, gospodine.
{108731}{108781}Naoružane su.
{108792}{108882}Nisam se mogla | približiti s ljudima.
{108883}{108984}- Postoji li drugi ulaz? | - Požarne stepenice, preko dvorišta.
{108985}{109052}Vidjet æe nas.
{109068}{109106}Gospodine...
{109107}{109213}Možemo upasti brzo i žestoko, | no moramo obavijestiti guvernera.
{109214}{109301}Nitko neæe zvati guvernera. | Ovo æemo sami srediti.
{109338}{109382}Sranje.
{109391}{109462}Možemo sami. | Za škart æemo se pobrinuti kasnije.
{109463}{109531}- Mislim da nije dobra zamisao. | - Zaveži.
{109580}{109621}U redu.
{109622}{109690}U redu. Imaju samo | lokalnu telefonsku vezu.
{109691}{109778}- Da, gospodine. | - Èekamo da nazovu.
{109819}{109915}Budite pripravni. | Oružje spremno. U redu?
{110026}{110077}Dobro su sredile Deasea.
{110082}{110123}Crkni, pizdo!
{110124}{110200}Michaela su pustile, | s njim nisu u svaði.
{110201}{110318}Bio je dobar deèko | u lošem društvu.
{110350}{110422}Tko je èuo da | žene zauzmu zatvor?
{110423}{110476}Što nam je raditi?
{110477}{110525}Moramo postaviti zahtjeve.
{110526}{110631}Tako rade pravi revolucionari | da privuku pozornost.
{110632}{110684}Jebene kuje.
{110685}{110776}Bolje da se predate, | ja bih na vašem mjestu...
{110777}{110864}...i pustite me prije | nego vam raznesu jebene glave.
{110865}{110953}Tebi æu raznijeti glavu budeš | li nas još jednom nazvao kuje.
{110954}{111002}- Nikki. | - Ne, jebi ga...
{111003}{111058}- Nikki. | - Nisam kuja, pizdo jebena.
{111059}{111104}Nemoj. Moramo razmisliti.
{111105}{111198}Vi kuje ne znate razmišljati. | Nemate dovoljno mozga.
{111199}{111244}Wet.
{111246}{111278}Sranje!
{111279}{111374}Moramo ih uvjeriti da je | Dease ubio Lil' Mamu i doktora.
{111375}{111418}Neæe vjerovati.
{111420}{111487}Nemojte ništa reèi Nelsonu.
{111488}{111563}Idemo preko njega, | razgovarajmo s guvernerom.
{111583}{111631}Nikki.
{111652}{111718}Ima tu neèega.
{111724}{111825}Frances, sestro, toèno znam | što trebaš reæi.
{111885}{111917}Upravitelj Nelson.
{111918}{111991}Ovdje Frances Shepherd, | iz ženskog komiteta za reformu.
{111992}{112056}Shepherdice, ne seri.
{112057}{112148}Predajte se. Što zamišljate, | da je ovo neka politièka igra?
{112149}{112192}Sve je politika.
{112206}{112282}Imate sat vremena da nam | date guvernera na telefon.
{112315}{112350}Za to nemam ovlasti.
{112351}{112408}- Da èujem Deasea. | - Jedan sat.
{112714}{112761}Prokletstvo.
{112919}{112986}Izgledaš mi koma, crnjo.
{113003}{113064}Da, imaš vatre?
{113065}{113118}Hoæeš li pomoæi?
{113119}{113214}- Pomoæi æu! | - U redu. Imam vatre.
{113266}{113352}- Je li to guverner? | - Moram znati jesu li taoci dobro.
{113353}{113400}Daj mi nekoga. | Bilo koga.
{113401}{113465}Morat æeš mi vjerovati.
{113469}{113540}Nisi normalna. | Zašto bih ti vjerovao?
{113541}{113601}Jer imamo oružje i taoce.
{113603}{113638}Ona koja ima | oružje...
{113639}{113691}...postavlja jebena pravila.
{113692}{113739}Zajebavati se s Deaseom.
{113740}{113798}- Probudite... | - Jebeš Deasea.
{113817}{113855}Nemoj tako brzopleto.
{113856}{113935}- Jebeš Deasea. | - Dopusti da razgovaram s Deaseom.
{113938}{114022}NiŠta od pogodbe do tada. | Daj ga na telefon.
{114023}{114068}Dovuci mu guzicu.
{114069}{114124}Dovuci tu pizdu.
{114139}{114187}Nastupaš, kujo.
{114188}{114263}- Daj mi povoda. | - Dovuci pizdu.
{114321}{114391}Tko je sad kuja, pizdo?
{114475}{114543}- Reci mu. Reci mu. | - Èuo si je.
{114544}{114593}Reci mu sad.
{114621}{114718}Ubio sam Lil' Mamu i doktora.
{114762}{114821}Povuci ljude, povuci ih.
{114822}{114891}Dosta je. Imaš sat vremena.
{114892}{114943}Dease, Pusti je.
{114944}{115013}Jebi se, jebena kujo. | Jebi se.
{115019}{115068}- Jebi se ti. | - Ubi pizdu.
{115110}{115157}Ubi ga!
{115158}{115206}Ubi ga!
{115266}{115345}Ovo je za Lil' Mamu. | Ovo je za Frances.
{115352}{115451}Ovo, za moju i tvoju djecu, | pizdo jebena.
{116003}{116040}Izaðite...
{116041}{116093}...s podignutim rukama.
{116100}{116162}Izaðite s podignutim rukama.
{116163}{116262}Wet, što radiš? | Ne. Wet. Wet. Ne.
{116294}{116377}Wet. Wet. Ne.
{116378}{116419}Prekini s paljbom!
{116459}{116511}Pizda jebena.
{116605}{116656}Kod vrata ima nekoga.
{116924}{116958}Ne.
{116998}{117041}Povuci se. | Odmah se povuci.
{117086}{117175}Svi se odmah povucite. | Povucite se svi.
{117406}{117478}Oh, Bože. Oh, Bože.
{117479}{117527}Bit æeš dobro.
{117528}{117617}- Bit æeš dobro. | - Frances, hoæu li umrijeti?
{117618}{117683}Umrijet æu, zar ne?
{117688}{117751}Bože. Oh, Bože.
{117752}{117830}Ne dopustite da umrem uzalud.
{117913}{117942}Oh, Bože.
{117943}{118019}- Drži se. | - Curo, tu smo.
{118020}{118086}- Dobro si. Dobro si. | - Ne! Ne, Wet, molim te.
{118087}{118135}- Ne. | - Ne.
{118143}{118233}Ne.
{118788}{118854}Dobro smo sredile tu pizdu.
{118858}{118916}Dobro smo ga.
{118944}{119022}Saznao je kako je to | kad mu se nešto oduzme.
{119023}{119087}Njegov jebeni život.
{119326}{119379}Kako vidim.
{119383}{119443}Imamo dva izbora.
{119463}{119528}Možemo ovdje èekati...
{119529}{119594}...da doðu po nas...
{119621}{119668}...ili riskirajmo...
{119669}{119754}...izaðemo i vidimo što imaju za nas.
{119755}{119818}Krovni položaj, | vrata na niŠanu.
{119819}{119851}Ne.
{119852}{119914}Imamo još jednu opciju.
{119915}{119982}- Sve možemo okonèati same. | - Sranje.
{119983}{120020}Što se tamo dogaða?
{120021}{120093}Cervantes. Cervantes.
{120099}{120180}Neæu si uperiti pištolj | u glavu, jebeš to.
{120181}{120299}Upravitelju, Cervantes. JoŠ bih jednom | pokuŠala pregovarati.
{120336}{120381}Nikki.
{120382}{120410}Nikki.
{120411}{120477}Nije li to Cervantes?
{120490}{120554}Pušta ženu da mu | obavlja prljave poslove.
{120555}{120624}Cervantes, nije ti dojadilo | lizati dupe?
{120632}{120694}Moraš misliti na svoju djecu.
{120695}{120760}Mogu pomoæi da se | pogodite s upraviteljem.
{120769}{120857}Nikki, možda ima pravo.
{120892}{120958}Moja me djeca ne poznaju.
{120962}{121028}Toliko me dugo nema.
{121047}{121111}Zaveži, Cervantes. | Prestani nas izigravati.
{121112}{121184}Prekasno je za to.
{121393}{121450}Bit æe gadno.
{121460}{121489}Cervantes.
{121490}{121540}Cervantes, odmah privedi kraju.
{121591}{121645}Siddity.
{121649}{121707}Ti æeš razgovarati, može?
{121708}{121782}Èuju li tebe, | mislit æe da se nešto sprema.
{121783}{121855}U pravu si, znat æe | da se nešto sprema.
{121856}{121907}Obavimo to.
{122033}{122101}Cervantes. Privedi kraju.
{122160}{122220}Moram li ti objasniti?
{122248}{122296}Privedite kraju.
{122297}{122346}Privedite kraju.
{122372}{122447}Privedite kraju. Privedite kraju.
{122509}{122556}Privedite kraju.
{122965}{123017}Daj, daj.
{123032}{123078}Imam to.
{123604}{123653}TRIBUNE | 25 ŽENA DOBILE PARNICU
{123654}{123758}Iznenaðenje, Aisha je | uzela traku...
{123759}{123838}...i taj nam je dokaz omoguæio | da na sudu pobijedimo.
{124002}{124058}Nelson je dobio | što je zaslužio.
{124059}{124108}...zatvorenice obožavaju | svoj posao.
{124109}{124228}Ovdje stjeèu vrijedna iskustva, | a vi imate proizvod za plasiranje.
{124229}{124305}Dok je guverner istražio | Wallcor...
{124306}{124360}...veæ su bankrotirali.
{124361}{124428}Nelsonu su pronašli | toliko sranja...
{124429}{124490}...da su morali ukinuti zatvor.
{124491}{124536}On je pod istragom.
{124537}{124606}- Dease, trebao si biti tamo. | - Nisam mogao.
{124640}{124695}Moja cura Aisha.
{124696}{124732}Ubijena je u | tuènjavi.
{124733}{124803}Nedugo nakon pobune.
{124804}{124906}Nikako se nije mogla riješiti | zatvorskog mentaliteta.
{124931}{125043}Našu pobjedu posveæujemo | sjeæanju na moje cure.
{125044}{125087}Wet.
{125099}{125144}Lil' Mama.
{125170}{125214}Frances.
{125242}{125288}I Nikki.
{125317}{125399}Zloèin smo poèinile | i kaznu odgulile.
{125400}{125460}No nitko nije spomenuo | da zlostavljanje...
{125461}{125525}...i izrabljivanje | spada u kaznu.
{125526}{125600}Vraæam se u Chicago | da završim knjigu.
{125601}{125665}Èinit æu sve što mogu, | da budem što dalje od zatvora.
{125666}{125751}Tamo se ne dogaða ništa dobro.
{125752}{125833}Sad, kad znate što i ja, | proširite rijeè.
{125834}{125968}Molim vas, dajte nam posao. | No, ne u zatvoru.
{125973}{126057}Nemojte me zaboraviti. | Ja sam Sabrina.
{126058}{126117}Ovo je moj jebeni život.
{126118}{126240}{C:$0000FF}{y:ib} d |{C:$FF0000}{y:b} d 
