{1000}{1400}Preuzeto sa www.titlovi.com
{1500}{2000}Subtitles by:|M O Z E N | Sync by blackpk091
{2336}{2445}Planirate odmor, gospodine Sullivan?
{2466}{2556}Ne, samo èitam da mi proðe vrijeme.
{2690}{2826}Priðite, gospodine Sullivan. Oèekuju vas u|sobi 102, do kraja hodnika, pa desno.
{2831}{2883}Hvala!
{3223}{3349}- Kako se zovete?|- Morgan Sullivan.
{3383}{3493}- Gdje ste roðeni?|- Madison, Wisconsin.
{3519}{3607}- Da li ste špijun?|- Ne.
{3612}{3702}- Da li radite tajno za Sunways Systems?|- Ne.
{3707}{3798}Da li vas Sunways Systems plaæa da|kradete podatke od DigiCorp Technologies?
{3802}{3851}Ne.
{3909}{4007}Jeste li radili na nekoj poziciji|u Sunways Systems do sada?
{4012}{4083}Ovo je tehnološka firma, g. Sullivan.
{4088}{4202}Ako vas odluèimo zaposliti u DigiCorpu,|špijunirat æete druge korporacije,
{4207}{4335}izvještavat æete nas o njihovim poslovnim planovima,|istraživaèkim programima i kontra-obavještajnim operacijama.
{4340}{4437}Do sad, Vaša odluènost je bila impresivna.
{4442}{4560}Ako ima još neèeg,|što vam mogu reæi o sebi...
{4565}{4657}Bilo èega,|što veæ nije saznao DigiCorp...
{4662}{4737}Vaši osobni podaci su odlièni.|Prošli ste neurograf 5 puta.
{4742}{4836}- Ako želite, mogu ponovo na test...|- Oženjeni ste 4 godine,
{4841}{4998}živjeli ste u pristojnom kraju, imali ste|pristojan posao i odliènu kreditnu prošlost.
{5003}{5069}Ne drogirate se,
{5074}{5176}ne pijete. Ne pušite?|- Ne. - Nemate nikakvih drugih poroka.
{5181}{5280}Ima li ièeg drugog što|bismo trebali znati o vama?
{5285}{5446}Možda mi je trebalo prilièno vremena|da stignem do ovog dijela, g. Finster...
{5451}{5586}ali sad kad sam tu, napravit æu to.
{5671}{5777}To sam ja..
{5782}{5880}i to je ono što želim raditi!
{6047}{6140}- Ulozi u ovom poslu su vrlo visoki.|- Da, razumijem.
{6145}{6232}- Bit æe kao nijedan vaš posao do sada!|- I, spreman sam ja na to!
{6237}{6336}Slat æemo vas po kongresima širom|zemlje, a vi æete snimati govore.
{6341}{6444}- To mi je potpuno jasno!|- Morat æete kriti od ljudi èime se bavite.
{6449}{6516}- Da!|- Èak i od vaše žene.
{6521}{6627}- Da!|- Neæe vam smetati što lažete ženu?
{6664}{6731}Ne...
{6786}{6846}neæe mi smetati.
{6933}{7013}Ova je bila dobra. Preðite na sljedeæu.
{7175}{7292}- Dobar dan, g. Sullivan. - Dobar dan.|- Nemojte je vaditi, dok govor na kongresu ne poène.
{7295}{7442}Pritisnite je. Vidite li svjetlo? Sada je|ukljuèena. Pritisnite ponovo. Sad je iskljuèena.
{7447}{7536}- Lako je, zar ne?|- A, prijenos zvuka je prilièno jasan?
{7541}{7611}Do 50 metara. Držite je ispred,|zbog boljeg prijema.
{7617}{7749}- Gdje ide signal?|- Do satelita i natrag do baze podataka.
{7782}{7907}- Pretpostavljam da su govori prilièno važni.|- Govori vas se ne tièu, g. Sullivan.
{7911}{8013}Samo radite svoj posao, pratite naša uputstva|i ništa drugo. Razumijete?
{8018}{8081}Da, gospodine Finster!
{8086}{8152}Spremni!
{8388}{8476}- Jack Thursby?|- Tako æete se zvati od sada.
{8481}{8624}Što se tièe DigiCorpa, Morgan Sullivan ne postoji,|nikada nije i neæe ga ni biti.
{8655}{8758}- Kakav je on?|- Molim?
{8763}{8843}Kakva mu je osobnost?
{8848}{8952}Kakva god vi želite da bude.
{10792}{10881}Buffalo? Zašto im treba da ideš|èak do Buffala?
{10886}{10994}Trebam im da ih nauèim koristiti|software koji sam koristio na prošlom poslu.
{10999}{11086}- I platit æe ti honorarno za to?|- Naravno!
{11091}{11164}Slobodan ugovor.
{11169}{11304}Ako sve ispadne kako treba,|možda æe biti više puteva za mene.
{11309}{11454}Mislila sam da smo se dogovorili da se još ne vraæaš|na posao, sve dok se ona pozicija u firmi mog oca ne otvori.
{11459}{11549}- Mogu raditi ovo u meðuvremenu, zar ne?|- Trebaš mi doma trenutno, Morgan.
{11554}{11617}S obzirom da sam toliko zauzeta|sluèajem Williams.
{11642}{11750}To æe biti samo privremeno, draga.|Neæu ostati dugo.
{12361}{12480}- Halo? - Poslije kongresa, potvrdit æete|prijenos u letu u povratku. - Da.
{12485}{12562}- Da li ste zapamtili lokaciju torbe?|- Da.
{12567}{12674}- Sretno, gospodine Thursby.|Raèunamo na Vas. - Hvala.
{13570}{13649}Ostavio sam je u kabini.
{14477}{14552}Nešto za piæe, gospodine?
{14606}{14677}Jedno pivo od ðumbira.
{14817}{14913}Ustvari, dajte mi viski.
{14918}{15002}- Viski?|- Èisti.
{15045}{15112}- Sa ledom.|- Da, gospodine.
{15354}{15418}Dobrodošli u Buffalo, g. Thursby.
{16610}{16794}Nova antialergijska krema|obogaæena vitaminima.
{16799}{16957}- Fred Garfield.|- Bok, Jack Thursby.
{16962}{17020}Fairway Fragrances.|Gdje se oni toèno nalaze?
{17049}{17118}Tulsa, Oklahoma.
{17123}{17206}Nemojte izmišljati. Ja imam obitelj|u Tulsi. Nemate njihov naglasak.
{17211}{17343}- Nisam odrastao tamo.|- Gdje ste odrasli?
{17423}{17473}- Pitao sam: "Gdje ste odrasli?"|- Južni Pacifik.
{17478}{17581}- Oprostite, gdje?|- Južno Pacifièka otoèja.
{17586}{17699}Arhipelag Tuamoto, Francuska|Polinezija, Tahiti, Papeete.
{17704}{17844}- O, vrlo neobièno! - Da. Planiram se vratiti|tamo jednog dana, kad odem u mirovinu.
{17849}{17920}Voda, gospodine??
{17963}{18064}- Hvala.|- Pa, vidimo se, Jack.
{18086}{18165}Razumije se, Fred.
{18205}{18307}Konferencija poèinje za 5 minuta.
{18511}{18626}Dobro jutro svima. Zovem se|Robert Tuttle, ja æu prvi govoriti.
{18631}{18738}Prvo æu prokomentirati pjenu za brijanje|na tržištu Sjeverne Amerike.
{18743}{18887}Poèet æu sa onim što je postalo aksiomatièno|u distribuciji pjene za brijanje.
{18892}{19089}Naime, da je pjena za brijanje, ustvari skoro svi proizvodi|za higijenu mušaraca, ono što mi zovemo "Otporno na modu".
{19113}{19226}Velika veæina korisnika pjene za brijanje|æe prihvatiti marku i držati se nje...
{19231}{19331}ono što je vrlo važno primijetiti, a to su razlièite|metode koje se koriste da se probije na tržitu.
{19336}{19424}Zato što ove dvije metode|koje koriste ove kompanije..
{19429}{19521}ustvari prikazuju strateški izbor|koji se bazira na...
{19551}{19701}Mediteran je prelijep, ali ako Vas|interesira pravo jedrenje,
{19706}{19849}preporuèio bih Vam otok Sunda u|Banda Sea. Bio sam tamo prošlog proljeæa.
{19854}{19953}- Cigarete, gospodine?|- Hvala puno.
{20020}{20124}Kohibas, moja omiljena marka.
{20161}{20265}- Hvala. O, oprostite..|- Hvala.
{20459}{20524}Ja se izvinjavam.
{21440}{21562}- Dobra veèer, gospodine. Što želite?|Dajte mi viski, èisti, sa ledom.
{21717}{21793}Jesmo li se vidjeli nekad prije?
{21798}{21917}Morat æete smisliti nešto originalnije od toga.
{22201}{22287}Tu sam zbog konferencije.
{22292}{22356}To je fascinantno.
{22361}{22446}- Bavite se marketingom, zar ne?|- Ne, prodajom.
{22451}{22558}- Zar postoji razlika?|- A ti?
{22563}{22675}- Ja sam zdravstveni inspektor za hotelske restorane.|- Zvuèi interesantno.
{22680}{22787}- Ma ne.|- Imate odgovor za sve?
{22792}{22867}Da.
{23023}{23089}Rita Foster.
{23181}{23242}Jack Thursby.
{23935}{24056}I, èime se još bavite, osim što idete po dosadnim|gradovima i prièate sa ženama po barovima?
{24061}{24172}- Ja... igram golf.|- Jeste li dobri?
{24236}{24351}- Ne.|- Iskrenost. To mi se sviða.
{24356}{24493}- Što ti se još sviða?|- Nikakve obaveze.
{24532}{24601}Bez gluposti.
{24645}{24743}- I bez prstenja.|- Bez prstenja?
{24748}{24823}Možda æeš željeti skinuti svoj.
{24882}{24958}Oprosti...
{25060}{25164}Ostavit æu te na miru.
{25257}{25365}Vaš prijenos je ostvaren, g. Thursby.|Signal je bio jasan.
{25370}{25480}Možda bih mogao napraviti nešto drugo na svom|sljedeæem putovanju. Mislim da sam spreman za veæe zadatke.
{25485}{25664}- Poslat æemo vas u Omahu sljedeæe srijede. - Omahu?|- Napravit æete isto što ste napravili u Buffalu.
{26563}{26673}Omaha? Zašto ne naðu nekog iz Omahe?
{26704}{26829}- Zašto moraš ti? Nije mi logièno.
{26834}{26880}Morgan!
{26885}{26973}Morgan, slušaš li me?
{27065}{27157}Otkad te interesira golf?
{27197}{27304}Neæeš iæi na ovaj put, Morgane! Žao mi je.
{27309}{27424}- Kako to misliš?|- Moj otac želi da doðeš kod njega u kancelariju sutra.
{27429}{27531}Dolazak na poziciju u ovoj kompaniji je|puno važniji nego neki honorarni posao.
{27536}{27663}- Rekao sam da æu otiæi.|- Neæeš iæi, Morgane. Kraj prièe.
{27669}{27798}Ostaješ ovdje. Pozvat æu oca|veèeras i mi æemo...
{27818}{27900}Reci svom ocu neka se jebe.
{27979}{28106}Što si rekao? Isprièaj se, Morgan.
{28111}{28166}Morgan!
{28171}{28269}Ako se ne isprièaš, ne vraæaj se u ovu kuæu.
{28275}{28360}Morgan, slušaš li me?
{28365}{28493}O, Bože, što je tebi?|Otkad si propušio?
{28498}{28623}Morgan, što se dešava?|Mislim da zaslužujem objašnjenje.
{28796}{28881}Izvolite viski, g. Thursby.
{31159}{31238}Okreni se, polako, molim!
{31411}{31519}- Èime prisluškuješ?|- Mislio sam da si zdravstveni inspektor.
{31574}{31680}Pitat æu te ponovo.|Èime prisluškuješ?
{31724}{31785}Olovka, u džepu od jakne.
{32157}{32303}- Ne ukljuèuj je! - Molim?|- Kad si u sali, drži je iskljuèenu!
{32307}{32357}Ne šalji signal u DigiCorp!
{32363}{32457}Ako kažeš DigiCorpu|da si me vidio, ubit æe te.
{32491}{32580}Uzimaj po 2 svakih 6 sati.|Riješit æeš se košmara koje imaš.
{32585}{32713}Nestat æe i glavobolje, a i bol u vratu.
{32718}{32803}- Otkud znaš da imam košmare?|- Vidjet æemo se u Boise.
{32807}{32896}- Što æe oni napraviti, ako ne vratim olovku?|- Samo zapamti tko si!
{32944}{33075}Ti si Morgan Sullivan,|nisi Jack Thursby.
{33341}{33412}Èekaj!
{33706}{33814}Dobro jutro svima. Ja sam Alex Chen.|Ja æu prvi govoriti danas.
{33819}{33987}Dame i gospodo, ja sam tu da prokomentiram|kontraverziju koja postoji u novim tehnikama pripreme sira.
{33992}{34150}S rizikom da prepojednostavim, pitanje s kojim|se suoèava prosjeèni proizvoðaè sira je sljedeæe:
{34155}{34253}Predrasude koje postoje o|upotrebi kemijskih konzervansa,
{34258}{34380}kako da produžimo rok upotrebe,|a da ne izgubimo na kvaliteti ...
{34385}{34469}Drago mi je što èujem da nije bilo problema|na konferenciji, g. Thursby.
{34474}{34583}Pozvat æu laboratorij da provjerim|da li  je prijenos prošao kako treba.
{34657}{34766}- Odlièno obavljen posao, g. Thursby.|Hvala.
{34771}{34871}Signal je prošao odlièno.|Isto kao i prošli put.
{34876}{35009}Želim da odete na još jedan put, Boise, Idaho.
{35014}{35114}Složili smo da imate vezani let kad sletite.|Neæete imati vremena da odete kuæi. To nije problem, zar ne?
{35119}{35247}Ne, nije problem.
{36738}{36834}Soba 1943, g. Thursby.|Kongresna sala æe se otvoriti za sat vremena.
{36839}{36894}Hvala.
{36899}{36994}Gospodine Thursby, samo još nešto...
{36999}{37140}Prvo slovo svake rijeèi je|broj telefona da je pozovete.
{37854}{37957}Halo, g. Sullivan. Pozvali ste poseban broj|koji ne može biti praæen ni sniman.
{37962}{38076}Slušajte pažljivo. Uzmite teretni lift|na kraju hodnika i idite do podruma.
{38081}{38181}- Bit æe èisto u iduæih 5 minuta.|- Èekajte.
{38611}{38683}Produži.
{39106}{39202}Zavrnite rukave molim.|Nemamo mnogo vremena.
{39382}{39471}Jeste li ludi?|Neæete me sa tim ubosti!
{39476}{39607}- On je doktor, gospodine Sulivan.|- Baš me briga i da je kirurg, neæete me drogirati.
{39612}{39722}Ovo je protulijek. Šok æe blokirati|djelovanje DigiCorp narkotika.
{39727}{39852}Kemikaliju koju vam daju u krvotok prije svakog|kongresa. Da li obièno pijete nešto u kongresnoj sali?
{39907}{39993}- Mineralnu vodu. - Narkotik nema ni|miris ni ukus. Ne biste ni primijetili.
{39998}{40125}Jeste li uzimali lijekove koje sam vam dala?|Je li buka u glavi poèela nestajati?
{40130}{40227}- A noæne more?|- Bože, što je ovo?
{40232}{40325}Zašto DigiCorp nije provjerio prijenos u Omahi?
{40330}{40426}Nije ni bilo prijenosa u Omahi,|niti u Buffalu, niti bilo gdje drugdje.
{40431}{40564}- Zašto me onda šalju na te kongrese?|- Kongresi su samo paravan.
{40569}{40694}Ti, i ostali gosti na kongresu, vi svi|radite za DigiCorp. Svi ste špijuni.
{40699}{40806}Dali su vam lažne zadatke, lažne identitete...|Vi mislite da vam je olovka prisluškivaè.
{40811}{40894}Drugi gost misli da mu je to|igla za kravatu ili sat..
{40899}{41009}Sve je samo prevara da vam skrenu pažnju,|da ne shvatite šta se stvarno dešava.
{41014}{41094}A što se stvarno dešava?
{41132}{41233}Ako želiš odgovore, primi injekciju.
{41490}{41605}Kad budeš unutra, ponašaj se kao i obièno.|Naruèi mineralnu vodu, popij je.
{41610}{41711}Nemoj da posumnjaju. Injekcija koju smo|ti dali bi te trebala zaštititi.
{41716}{41847}- Trebalo bi? A što ako me ne zaštiti?|- Slušaj me pažljivo!
{41852}{42005}Što god da se desi u toj sobi, ne pokazuj|nikakve reakcije, emocije, ne iznenaðuj se!
{42010}{42130}Bez obzira što vidiš, ne pomièi se!
{42152}{42239}Što æu vidjeti?
{42352}{42439}- Tko te poslao?|- Prijatelj.
{42444}{42519}Ja nemam prijatelja.
{42524}{42639}- Kad æu te ponovo vidjeti?|- Uskoro.
{42662}{42722}Obeæajem.
{42848}{42986}... važne stvari u ovome su, kao prvo|èinjenica da je PIM-NHP
{42988}{43121}zauzeo veæinu tržišta.
{43133}{43290}Pod ovim podrazumijevam da je veæina njihovih prodaja obavljena|individualno, ali da ima znatno više mjesta za pregovore.
{43295}{43483}Stoga, u tim prodajama æemo vjerojatno naæi|zvanièni rast stope prodaje...
{43488}{43593}... povratno u investicije u hi-tech industriji
{43598}{43783}što je dovelo do promjena u trošenju kapitala|i znaèajno je poveæalo rast produktivnosti.
{43788}{43928}Kapitalizacija ovih, veæih od oèekivanih prihoda|srazmjerno su poveæale cjene,
{43933}{44060}uglavnom više od oèekivanih porasta osobnih prihoda.
{44065}{44246}Porast prodaje automobila, npr. prati porast broja|automobila na ulici, više nego što industrija može izdržati.
{44251}{44367}I, iako se potreba za hi-tech proizvodima|udvostruèavala i utrostruèavala godišnje,
{44372}{44466}u mnogim sluèajevima se ponuda|poveæavala èak i brže.
{44471}{44609}Ukupno se kapacitet hi-tech industrije|poveæao skoro 50% prošle godine...
{47571}{47650}Samo reakcija...
{49187}{49313}Ti nisi Morgan Sullivan. Ti si Jack Thursby.|Ti nisi oženjen sa Amy Sullivan.
{49318}{49408}Tvoja žena se zove Diane Thursby.
{50139}{50217}Tvoja žena se zove Diane Thursby.
{50222}{50325}Ti živiš u Redmondu, Washington.
{50862}{50943}Prema financijskim izvještajima
{50948}{51076}federalne rezerve su ubrzale|osnovu vladine politike.
{51081}{51211}I zakljuèak: "oprezan pristup|je uvijek najbolja strategija".
{51273}{51334}Hvala vam na pažnji.
{51722}{51821}Oprostite, da li imate sat?
{51870}{51990}- Vrijeme, sat?|- Da, 15:30.
{51995}{52093}Veæ? Kako vrijeme leti.
{52097}{52170}Jeste li uživali?
{52175}{52251}Da, jako.
{53128}{53181}Halo?
{53215}{53288}Za vas je.
{53382}{53466}DigiCorp æe ti priæi na aerodromu.|Predstavi se kao Jack Thursby.
{53471}{53557}Reci im da nikad nisi èuo za Morgana Sulivana.|Neka pomisle da su ti isprali mozak.
{53562}{53627}Ako se odaš, ubit æe te.
{53632}{53733}- Što se desilo tamo?|- Osjeæaš nuspojave neutralizirajuæeg agensa.
{53738}{53838}Ne brini. Bit æe ti dobro.
{54793}{54888}Gospodine Sullivan? Došlo je|do promjene plana, g. Sulivan.
{54893}{55017}Morate doæi u lokalnu|kancelariju DigiCorpa. Gospodine Sulivan?
{55050}{55133}...gospodine Sulivan?
{55208}{55287}Jeste li dobro?
{55292}{55421}Mislim da griješite.|Ja se ne zovem Sullivan.
{55456}{55528}Vi niste Morgan Sullivan?
{55533}{55651}- Ne radite za DigiCorp?|- Ne. Zovem se Thursby, Jack Thursby.
{55671}{55759}Mislim da tražite nekog drugog.
{55764}{55896}Izvinite, gospodine Thursby.|Moja greška.
{55902}{55981}U redu je.
{56471}{56543}Dobar dan, gospodine. Kako ste?
{56577}{56637}Treba mi samo vaša propusnica, molim.
{57084}{57152}- Hvala.|- Molim.
{57233}{57328}- Oprostite.|- Nema problema.
{59352}{59470}Na tebe je red. Nije ostalo|mnogo tople vode, oprosti.
{60125}{60230}- Hoæemo li veèerati pola|sata ranije veèeras? Naravno.
{60234}{60347}- Ima nekih poslova koje bi|trebao napraviti danas. - OK.
{60353}{60479}Kljuèevi su ti u kutiji pored torbe,|toèno gdje si ih i ostavio.
{61210}{61296}Intervju, SUNWAYS SYSTEMS 10:30.
{61700}{61768}Planirate li put?
{61772}{61821}Samo èitam da mi proðe vrijeme.
{61827}{61943}Oèekuju vas na recepciji, g. Thursby,|niz hodnik, pa lijevo.
{62167}{62268}- Kako se zovete?|- Jack Thursby.
{62678}{62783}Ja se zovem Frank Callaway. Ja sam šef|osiguranja u Sunways Systems.
{62855}{62959}Prema nalazima neurografa, vi lažete.
{62964}{63037}Lažete kada kažete da se|zovete Jack Thursby.
{63042}{63129}Lažete kada kažete da niste špijun.
{63134}{63249}Lažete kada kažete da ne radite za DigiCorp.
{63347}{63458}I ne mogu vam reæi koliko|nam je drago zbog toga.
{63490}{63569}Nema šanse. Ne vraæam se u tu kuæu.
{63574}{63622}Vi ste u posebnoj situaciji sada, Morgan.
{63628}{63710}DigiCorp misli da ste vi Jack Thursby.
{63716}{63812}Oni misle da ste prošli neurograf i žele|da vas zaposlimo kao jednog od naših agenata.
{63817}{63935}- Nas zanima što oni žele! - Kontraobavještajni|posao za Sunways æe biti vrlo jednostavan.
{63941}{64088}DigiCorp neæe posumnjati da vi radite za nas,|tako da vas neæe puno nadgledati dok ste u kuæi.
{64093}{64184}Sve što trebate napraviti je da postavite|po jednu bubicu u svaku sobu.
{64190}{64301}Vi mene ne razumijete. Ja idem kuæi.|Idem svojoj pravoj kuæi.
{64306}{64439}- Vaše stvarne kuæe više nema, Morgan.|- O èemu prièate? - Vaša žena je dala kuæu na prodaju.
{64444}{64539}Vaši advokati su vas pokušavali naæi|posljednjih par dana.
{64544}{64697}Podnijela je zahtjev za razvod prije 3 dana.|Žao mi je, Morgan.
{64732}{64868}- Gledaj, Morgan, znam da ti je sad teško...|-Želim vidjeti Ritu. - Koga? - Ritu Foster.
{64872}{64960}- Ona me spasila od ispiranja mozga.|- Ne, Morgan, ne možeš je vidjeti.
{64966}{65049}- Zašto? Ona radi za vas.|- Ne, ne radi za nas.
{65054}{65157}- Ali rekli ste da æemo se naæi|ispred hotela, zar ne? - Ne.
{65162}{65247}Ali znate za koga radi.
{65292}{65356}Za koga radi?
{65360}{65453}- Ona radi za Sebastiana Rooksa.|- Ko je Sebastian Rooks?
{65458}{65555}Sebastian Rooks je nezavisni agent|koga smo mi unajmili da sazna kako je
{65559}{65629}DigiCorp pripremio svoje agente|da proðu neurograf.
{65634}{65781}Zatim smo mu tražili da nam pošalje agenta|kome nije ispran mozak. On nam je doveo tebe.
{65786}{65882}On je najbolji u tom poslu, ali je|takoðer opasan i bezobziran.
{65887}{65973}Savjetovao bih ti da ga se kloniš.
{65978}{66071}Kloni se njega... i nje!
{66254}{66309}Gledaj...
{66314}{66420}mi ti nudimo izvrsnu ponudu.
{66425}{66555}Kad završiš posao za nas|dat æemo ti novi identitet.
{66560}{66697}Novi dom, daleko od DigiCorpa.
{66729}{66841}Žao mi je, g. Callaway. Morat æete naæi|nekog drugog za taj vaš posao.
{66974}{67038}Neæeš izdržati mnogo napolju.
{67043}{67156}Gdje god da kreneš DigiCorp æe te pratiti.
{67161}{67236}Ako pokušaš pobjeæi...
{67241}{67346}ako se ponašaš kao Morgan Sullivan,|a ne Jack Thursby...
{67351}{67404}eliminirat æe te.
{67409}{67545}Brzo, efikasno, beskompromisno.
{67745}{67849}Ti si sretan èovjek, Morgan, da ti nismo|prekinuli proces ispiranja mozga
{67854}{67922}bio bi kao ostali gosti kongresa.
{67927}{68015}Program "Novi identitet", poslan kompanijama širom svijeta,
{68020}{68126}prekinut je kad ste preživjeli|svoju korisnost u DigiCorpu.
{68131}{68240}Imate moguænost da uzvratite udarac. Dakle...
{68324}{68410}Da li si spreman da budeš špijun, Morgan?
{68788}{68872}Stavit æu još malo brokolija.
{70548}{70614}Prisluškujemo telefone.
{70687}{70765}Nadgledamo sve sobe.
{70856}{70941}Evo ih, u trpezariji.
{70969}{71052}Soljenku snima iz dobrog kuta, zar ne?
{71057}{71148}Odlièno, on vjeruje da je on Jack Thursby|i da je to njegova žena. Poèeo se prilagoðavati...
{71153}{71263}- S kim prièa?|- Sa DigiCorpovim agentima.
{71268}{71333}Podnosi im izvještaj o tebi.
{71338}{71482}Provodi dosta vremena unutra. Naravno, on nema|prijatelja i ima vrlo malo kontakta s vanjskim svijetom.
{71487}{71565}Prisluškujemo i internet.
{71570}{71662}Odlièan rad, Morgan. Odlièan!
{71667}{71739}Bože...
{71763}{71850}Moj život je isti kao što je uvijek bio.
{71855}{71944}To je zato što je DigiCorp pratio|cijeli vaš život i duplicirao ga.
{71949}{72010}To pomaže u tranziciji kad postajete druga osoba.
{72015}{72093}Ja to više nisam.
{72246}{72380}Ja pušim... pijem viski... igram golf...
{72385}{72485}Ja ne bih  trebao živjeti u predgraðu.
{72490}{72576}Ne bih trebao biti takav.
{72581}{72718}Žao mi je ako si razoèaran, Morgan, ali to je|tvoja vizija Jacka Thursbyja.
{72723}{72812}Nije DigiCorpova.
{72865}{72966}Da li mogu izoštriti sliku u hodniku?
{74111}{74177}Da, Jamison.
{74194}{74301}Nije Jamison. Ovdje Morgan Sullivan.
{74418}{74504}- Što želite, g. Sullivan?|- Treba mi tvoja pomoæ.
{74509}{74592}Želim unajmiti Sebastiana Rooksa.
{74622}{74699}- Još si tu?|Doviðenja, g. Sullivan.
{74704}{74760}- Platit æu.|- On ne radi za individualce.
{74765}{74869}- Pitaj ga da napravi izuzetak, napravi što god treba.|- Morat æeš sam. Žao mi je.
{74874}{74946}Ne, ne!
{74951}{75078}- Moraš mi pomoæi!|- Ne mogu...
{75083}{75209}Rekla si da ti mogu vjerovati.|Povjerovao sam kad si mi to rekla.
{75214}{75331}Naæi æemo se ispred praonice auta|na uglu 4-te i Jeffersonove za 3 sata.
{75481}{75614}Morgan!|Šaljemo te na prvi zadatak sljedeæi tjedan.
{75619}{75777}Naša oprema za pratnju se veæ otplatila. Znamo|toèno koje informacije je DigiCorp htio ukrasti od nas.
{75782}{75894}Dakle, veèeras, reæi æeš da ideš na poslovni put.
{75899}{76001}Znat æeš kako da joj to kažeš, zar ne?
{76006}{76089}- Morgan?|- Da.
{76208}{76360}Držat æeš se plana, neæeš pokušavati ništa rizièno.|Da li me razumiješ?
{76432}{76508}Sebastian Rooks je pristao da ti pomogne.
{76513}{76630}- Kad æe me moæi vidjeti?|- Još ne, on je u autu iza nas.
{76792}{76921}- Koliko novca æe mi tražiti?|- Ne interesira ga lova. On misli da æe te moæi iskoristiti.
{76926}{77038}- Kako?|- Bit æemo u kontaktu u Wichiti.
{77043}{77098}-Wichiti?|-Tamo æete Sunways poslati na posljednji zadatak.
{77103}{77200}Otkud to znaš? Nisu èak ni meni rekli.
{77205}{77292}Rooks zna. On sve zna.
{77297}{77379}- Mogu li mu vjerovati?|- Ne mogu ti ništa garantirati.
{77384}{77503}Ali ima moguænosti da ti osigura|novi život, novi identitet.
{77508}{77577}Izbor je na tebi, Sullivan.
{77612}{77669}Šta trebam raditi?
{77674}{77768}Sunways æe te slati na nekoliko zadataka.|Dobivat æeš disk na svakom putovanju.
{77856}{77942}DigiCorpovi agenti æe te pratiti gdje god krenuo.
{77947}{78043}Neka, to je ono što Sunways želi.
{78198}{78285}Na svakoj destinaciji æeš se sretati sa|Sunwaysovim ljudima za kontakt.
{78290}{78367}Oni æe skidati podatke na tvoj disk.
{78457}{78586}Agenti DigiCorpa æe misliti da|primaš vrijedne informacije.
{78642}{78736}Kasnije kad budeš posjetio sve više gradova,|skupljao sve više podataka
{78741}{78796}tvoj agentski status æe rasti.
{78801}{78906}DigiCorp æe onda pomisliti da si postao|jedan od Sunwaysovih vrsnih ljudi u kompaniji.
{79163}{79224}Jack?
{79249}{79370}Svaki disk koji doneseš kuæi æe|izgledati važnije od prethodnog.
{79432}{79576}Dok kopiraju diskove, DigiCorp æe misliti da|odnosi jednu od najveæih pobjeda protiv svog rivala.
{79598}{79672}U stvari, DigiCorp gubi.
{79677}{79806}Sunways im daje pogrešne podatke|koji æe sabotirati operaciju.
{79811}{79930}Ali pazi da ne pogriješiš, Sullivan.|Sunways je jednako beskrupulozan kao i DigiCorp.
{79959}{80072}Kad se ova operacija završi|oni æe te eliminirati.
{80119}{80194}Rooks æe te štititi.
{80245}{80299}Molim te, meni možeš vjerovati.
{80389}{80469}Šaljemo te u Kansas, Wichita.
{80508}{80571}Skoro je gotovo, Morgan.
{80576}{80679}Poslije ovog puta do trezora,|vaš posao kod nas æe se završiti.
{80684}{80754}- Trezora?|- To je naša baza podataka.
{80759}{80854}Potpuno je odvojeno od vanjskog svijeta,|ali mi šaljemo agenta-kurira
{80859}{81022}ako želimo primiti ili dodati file.|Vi æete biti naš sljedeæi kurir.
{81022}{81122}a DigiCorp æe misliti da je dobio glavnu premiju.
{82002}{82170}Moramo prièati tiho.|Zamijeni ovaj disk sa onim u tvojoj torbi.
{82175}{82284}Prije nego što odeš u trezor,|skini prsten.
{82289}{82390}- Što?|- Prsten.
{82523}{82656}Ovo je ureðaj za praæenje.|Znat æemo tvoju toènu lokaciju uvijek.
{82727}{82800}Da li ovo znaèi da æemo se vidjeti ponovo?
{82805}{82872}Srest æemo se kad izaðeš iz trezora,|da te odvedem do Rooksa.
{82877}{83004}- Mislio sam, poslije toga.|- Neæemo se više moæi viðati.
{83009}{83121}To æe ugroziti tvoj novi identitet.
{83292}{83392}Nikada neæu izaæi iz ovog, zar ne?
{85394}{85474}Ulica "Horse Creek" 500, molim.
{85479}{85548}Znam gdje da idem.
{85608}{85735}Smirite se, g. Sullivan.|Èeka nas dug put.
{86221}{86311}Ne moraš se praviti da si Thursby.
{86316}{86391}Znam da ti mozak nije opran.
{86396}{86521}Znam da te Sunways koristi kao|dvostrukog agenta protiv DigiCorpa.
{86587}{86653}Morat æete me ubiti?
{86658}{86736}Ne, ako mi budeš vjeran
{86741}{86873}umjesto Sebastianu Rooksu.|Da, znam da radiš za njega.
{86902}{87061}Ustvari mi obojica radimo za njega.|Ja sam mu unutrašnji izvor u DigiCorpu.
{87092}{87189}- Što?|- Platio mi je da te zaposlim, da budeš njegov piun.
{87350}{87486}Nisi valjda mislio da sam te zaposlio|jer sam bio impresioniran tobom?
{87524}{87587}Stvarno je dobar plan.
{87592}{87687}Rooks je znao da æeš završiti ovdje u Kansasu,|na putu za Sunwaysov trezor.
{87692}{87772}Znao je da æe te moæi uvjeriti|da zamijeniš njihov disk sa njegovim.
{87777}{87889}- To je bio njegov plan od poèetka.|- To nije moguæe.
{87894}{87992}Rooksov disk sadrži program za pretragu.
{87997}{88162}Uæi æe neprimjetno u sigurnosnu mrežu trezora|i ukrasti fileove s podacima, bez aktiviranja alarma.
{88167}{88225}Kakve fileove s podacima?
{88230}{88333}Tko zna. Ali ako se Rooks|ovoliko namuèio da doðe do njih
{88338}{88410}mora da su izuzetno važni.
{88427}{88496}Plan je bio neuništiv.
{88501}{88597}Osim jedne èinjenice koju je previdio...
{88602}{88658}Mene.
{88663}{88780}- Što ti hoæeš?|- Kada budeš izlazio dat æeš disk meni, a ne Rooksu.
{88785}{88834}Ja sam bio lojalan DigiCorpu cijelo vrijeme.
{88839}{88917}Zašto bih vjerovao tebi... ili DigiCorpu?
{88922}{89000}Zato što æemo te ostaviti na životu,|a Rooks neæe. Jednostavno.
{89005}{89101}Nitko mu ne može vidjeti lice|i preživjeti da prièa o tome.
{89106}{89216}- Nitko ga nije vidio?|- On je duboko sakriven agent.
{89221}{89336}Fantom. Kompanije ga angažiraju|bez znanja tko je on.
{89341}{89411}Kad bi znale, ubile bi ga.
{89416}{89565}Onog trena kad daš taj disk|Rooksu, on æe te eliminirati.
{89613}{89721}Postoji samo jedna osoba|kojoj Rooks vjeruje.
{89726}{89834}Rita Foster. Njegova ljubavnica.
{89883}{89984}Ona mu je potpuno lojalna...
{90011}{90117}Ja sam jedina osoba kojoj sad možeš vjerovati.
{90262}{90342}Bit æu u blizini kad izaðeš.
{90367}{90468}Za svaki sluèaj, ako se razdvojimo.
{90534}{90598}Neæu ti naplatiti za vožnju.
{92853}{92936}Dobra veèer, gospodine Thursby.
{93173}{93238}Moje ime je Virgil Dunn.
{93269}{93341}Dobrodošli u trezor.
{93808}{93881}Prvi put?
{93933}{94058}Nadam se da se niste prejeli.
{94585}{94637}Krenite naprijed, molim.
{95293}{95388}Sad kad znamo da niste ozvuèeni
{95393}{95483}možemo te zvati pravim imenom, Morgan.
{95551}{95634}Dunn, Virgil C.
{97403}{97492}Daj mi svoj disk sada, molim.
{97660}{97715}Dobro.
{98629}{98759}DigiCorp æe se usrati u gaæe kad prekopiraju|podatke koje sam im upravo pripremio.
{98810}{98928}Neæeš vjerovati koliko puta su pokušali|upasti u sistem ovdje.
{98933}{98995}- Jesu li nekad uspjeli?|- Ne.
{99026}{99147}Ovo mjesto je uže|od opatièine pièke.
{99396}{99487}- Nešto za piæe? - Naravno.
{99492}{99646}To mi jedan od hobija, da ubijem vrijeme.
{99956}{100058}U zdravlje agenta!
{100252}{100316}I ja sam bio agent kao ti nekad.
{100321}{100397}Ja sam bio najbolji u poslu.
{100402}{100504}Ostaviš li me u sobi sa moguæim dvostrukim|agentom i ja mu postavim par pitanja
{100509}{100607}mogao bih ti reæi odmah|da li je špijun ili ne.
{100612}{100734}To je bilo prije nego što me Sunways|stavio ovdje. Prije tri godine.
{100739}{100839}- Što se desilo?|-Ova jebena mašina, to se desilo.
{100844}{100962}Rekli su da je neurograf|100% precizan, a da ja nisam.
{100967}{101097}I da me jako dobar špijun ili jako|dobar lažljivac može prevariti svaki put.
{101102}{101188}"To su gluposti", rekao sam im.
{101193}{101251}Nisu me slušali.
{101256}{101446}Vidiš, postoje stvari koje samo èovjek|može znati o drugom èovjeku.
{101451}{101619}Stvari koje strojevi nikad neæe moæi shvatiti.|Naprimjer, da vam pitam par pitanja...
{101647}{101762}Koje je tvoje omiljeno piæe?|Slobodno odgovori, samo ti hoæu pokazati.
{101779}{101864}Koje je tvoje omiljeno piæe?
{101940}{102030}Viski, sa ledom.
{102054}{102131}Istina.
{102136}{102220}- Oženjen?|- Da.
{102249}{102378}Ponovo istina. Vidiš?|Lako te je proèitati.
{102423}{102531}- Voliš li svoju ženu?
{102682}{102833}- Da.|- Eto, upravo si slagao, zar ne?
{102938}{103027}Da, slagao sam.
{103198}{103263}Ima tu više od samih pitanja.
{103300}{103481}Osjeæam neku napetost u tebi.
{103551}{103676}Napet si, otkako si stavio disk u moj kompjuter.
{103681}{103793}Kako je to moguæe? Obojica|znamo da ovaj disk dolazi iz Sunwaysa.
{103801}{103914}Nema nièeg na njemu|zbog èega bi se osjeæao neugodno?
{104041}{104164}- Još samo jedno pitanje, OK?|- Da.
{104206}{104291}- Da li si ti dvostruki agent?
{105320}{105393}Gdje je g. Dunn?
{105425}{105490}Ostao je u kancelariji.
{105543}{105648}- Možete iæi, g. Sullivan.|- Hvala.
{106051}{106101}Ne dajte mu da ode!
{106988}{107052}Posade za spašavanje stižu.
{107057}{107155}Zbog vaše sigurnosti|molimo vas da ostanete u liftu.
{107311}{107394}...molimo vas da ostanete u liftu.
{107427}{107497}Posade za spašavanje stižu.
{107502}{107624}Zbog vase sigurnosti|molimo vas da ostanete u liftu.
{109221}{109287}Skoèi!
{109431}{109519}Sad!
{109994}{110060}Rekoh ti da znam gdje æe biti.
{110064}{110136}- Mogu uzeti disk sada.|- Je li to Rooks?
{110140}{110265}Jamison, jedan od naših agenata.|Rooks nas èeka u hotelu.
{110271}{110354}Jedva èeka da te vidi.
{111423}{111527}Auto èeka dolje.|Zovi me kad doðeš do laboratorija.
{111579}{111715}- Ovdje Rooks živi?|- Trenutno. Stalno se seli.
{111721}{111860}- Ali ti uvijek znaš gdje je on?|- Mi imamo poseban odnos.
{111941}{112043}Tvoj zadatak je skoro završen, Sullivan.
{112578}{112665}Odmah se vraæam.
{113434}{113488}Finster.
{113494}{113593}- Morgan Sullivan je.|- Što se desilo sa tobom?
{113598}{113680}U potkrovlju sam jedne stare kuæe,|ali ne znam gdje je to.
{113685}{113756}Pratimo poziv. Bit æemo tamo uskoro.|Gdje je Rooks?
{113761}{113846}- Sad æu ga upoznati.|- Spusti telefon, prije nego što te vidi.
{113851}{113986}Ubit æe te. Razumiješ?|Èuvaj disk. Dolazimo odmah.
{114126}{114288}- Ne približavaj se!|Spusti pištolj, Sullivan.
{114293}{114398}Polomit æu ga, ako priðeš još malo!
{114403}{114540}Dao sam ti Sunwaysov disk,|ovaj je tvoj, onaj koji Rooks želi.
{114663}{114713}Stani!
{114720}{114859}- Ne želiš to napraviti.|- Iskoristila si me. Ti i Rooks.
{114885}{114971}- Koristila si me od poèetka.|- Stani, èekaj da ti objasnim...
{114976}{115039}Ne.|Finster mi je veæ sve objasnio.
{115045}{115133}- Kad si prièao s Finsterom?|- Sad æe doæi. Sad sam ga zvao.
{115138}{115266}Ako Rooks želi ovaj disk prije nego što Finster naiðe|bolje otkljuèaj ta vrata i pusti me da idem.
{115272}{115403}Slušaj me. Sebastian Rooks nije osoba koja ti misliš da je.
{115408}{115524}- Rooks je bezobziran špijun, a i ti si.|- Ne, griješiš!
{115529}{115597}Znam sve o tebi.
{115602}{115701}Za vas dvoje i za vaš specijalan odnos.
{115706}{115815}- Samo me poslušaj...|- Ne želim više slušati laži!
{115922}{116079}Bože, ne mogu vjerovati da sam stvarno|povjerovao da ti je stalo do mene.
{116129}{116255}- Ne mogu vjerovati da sam takva budala.|- Stalo mi je do tebe.
{116462}{116519}Ne...
{116548}{116678}Samo se idi vidjeti sa Rooksom.|Bit æe sve u redu.
{116874}{116973}Požuri...!
{120176}{120309}Pokušala sam te zaustaviti.|Ali ti si inzsistirao.
{120313}{120430}On je rekao da je ovo jedini naèin|da se ukradu podaci iz trezora.
{120435}{120530}Dobro došao kuæi, g. Rooks.
{120752}{120859}Hajde.|Finster æe stiæi ovdje svaki èas.
{120863}{120983}Ne! Nema više laži.|Ne možeš me prevariti više.
{120988}{121078}Slušaj me.|Ti nisi Morgan Sullivan.
{121083}{121166}To je tvoja fantazija.
{121187}{121307}Tvoj život u predgraðu, tvoj brak,|tvoja žena Amy je samo jedan agent
{121312}{121369}koga si ti zaposlio na tom zadatku.
{121374}{121485}Što više se budeš borio s istinom,|više æe te boljeti.
{121511}{121618}Ti koristiš istu tehniku|ispiranja mozga kao i DigiCorp.
{121623}{121688}Ti si im i prodao tu tehnologiju.
{121694}{121752}- Nema nikakvog smisla!|- Ima idealnog smisla!
{121757}{121869}Pretvaranje u Morgana Sullivana je bio jedini naèin|na koji si mogao proæi DigiCorpov neurograf.
{121874}{121977}Jedino tako bi te zaposlili i poslali u Sunways.
{121982}{122059}- Zasto bi itko želio ovo napraviti?|- Za ovo.
{122063}{122157}- Što je to?|- Nadala sam se da æeš ti meni reæi.
{122162}{122276}- Ne znaš?|- Puno sam vjere uložila u ovaj zadatak.
{122513}{122569}Ne mrdajte!
{122796}{122899}Sunways osiguranje!|DigiCorp osiguranje!
{123224}{123302}- Da li me pratiš, Callaway?|- Tu sam zbog Rooksa, ne zbog tebe.
{123307}{123388}I ja sam tu zbog njega.
{123580}{123690}- Jesi li letjela nekad s ovim?|- Ne, nikada.
{123696}{123820}Ti ga znaš voziti.|Ti si ga napravio.
{124032}{124094}- Ne znam što da radim!|- Sebastian Rooks zna.
{124099}{124215}- Ne mogu se sjetiti Sebastiana Rooksa!|- Sjeæaš se da me voliš?
{124383}{124459}Samo razmisli!
{125788}{125884}Odosmo.
{126069}{126171}Jesi li ga vidio?|Jesi li vidio Rooksovo lice?
{126176}{126262}Samo Morgana Sullivana.|Pijuna.
{126543}{126637}Bože, pa to je Rooks!
{129200}{129270}Je li to ono što su željeli?
{129275}{129340}Da.
{129480}{129539}To si ti.
{129746}{129871}File u trezoru je obrisan.|Ovo je jedina kopija.
{130122}{130196}Sad više nema ni jedne.
{131115}{131871}Subtitles by:|M O Z E N
