{1}{1}25.000
{111}{162}PREMA ISTINITOJ PRIÈI
{360}{460} DAWN ANNA 
{461}{564} NOV POÈETAK 
{2856}{2981}A konobar kaže: "Nije, | nego je majmun."
{2987}{3064}Denvere, otvorimo prozor | na ovo lijepo proljetno jutro.
{3068}{3193}6.30 je, 7. travnja 1993., | godine Zmaja.
{3200}{3267}Ili Majmuna.
{3279}{3372}Ili, sudeæi prema meni, | Troprstnog ljenjivca.
{3422}{3489}Idemo. Još 30 minuta.
{3493}{3523}Je li tko unutra?
{3527}{3599}Za 29 minuta moramo | krenuti. Hajde.
{3603}{3637}Hajde, mušketiri.
{3660}{3714}Kapetane, ne mogu | pogoditi mješavinu.
{3718}{3775}Gubimo snagu, Uhura. | Još žitarica.
{3779}{3836}- Ja sam sokol! | - Lauren, nemamo vremena.
{3840}{3865}- Jesi li jela? | - Ne.
{3869}{3904}Ponestalo nam je Fruity | Chunksa, kapetane.
{3908}{3943}- To je èisti šeæer. | - Halo.
{3947}{4023}Fruity Chunks. | U njima je voæe.
{4028}{4074}Ja sam sokol!
{4078}{4173}- Sokol? Što je s vukovima? | - Dobro jutro, mama.
{4178}{4251}Stani, rez ili kako se veæ kaže. | Jeste li jeli?
{4255}{4321}- Ponestalo nam je žitarica. | - Kristin, Matt, siðite.
{4325}{4373}Zamjenska sam uèiteljica. | Ne smijem zakasniti.
{4377}{4409}Ponestalo nam je | žitarica, mama.
{4413}{4509}Daj mi kosu. Josh, ako nema | žitarica, stavi ih na popis.
{4513}{4560}Ne obnavljaju se, Josh.
{4564}{4631}Može li mi netko reæi... | Lauren, na primjer...
{4635}{4710}...što je ovaj glodavac radio u | mojoj ladici za donje rublje?
{4714}{4792}- Bila sam zabrinuta za tebe. | - Znala si da je pobjegao?
{4796}{4826}To je ona.
{4830}{4900}Mama, kladim se da je kuæa | puna hrèkova izmeta.
{4904}{4954}- Hrèkov izmet mi je najdraži. | - Smiješno.
{4958}{5024}Kristin, hoæeš li mi | objasniti tu svoju odjeæu?
{5028}{5076}- Mama, Hula klub. | - Postoji klub za to?
{5080}{5160}Priznajem, kad si mi rekla, | nisam te shvatila doslovno.
{5164}{5248}To je Hula klub, u redu?
{5252}{5354}- Ima li tosta? | - Da, ako ima kruha. Ne.
{5358}{5424}Nemoj biti jedna od onih | djevojaka koje ništa ne jedu.
{5428}{5475}- Dobro jutro. | - Dobro jutro, Matt.
{5479}{5543}Kristin je jutros našla živinu | u ladici za gaæice.
{5547}{5613}To objašnjava vriskove...
{5617}{5671}- Ali ne i odjeæu. | - Hula klub.
{5675}{5728}- Matt, Hula klub. | - Dobro.
{5732}{5789}Vrati tog hrèka u kavez.
{5793}{5886}Požurite se. | Ne smijem zakasniti.
{5890}{6018}- Ja sam sokol. | - Josh, odloži kameru. Molim te.
{6047}{6134}U redu. Danas mijenjam u Powellu.
{6152}{6255}Ona je uèiteljica | Bit æe zamjenska
{6259}{6340}- No poslije imam pravi razgovor. | - Izvrsno, mama.
{6344}{6475}Izvadite varivo iz hladnjaka | i u peænicu u 5, na 350.
{6479}{6556}A ako nekog zanima, | veèeras idem u kupnju.
{6560}{6635}Zatim ocjenjujem Joshovu igru...
{6639}{6707}...a zatim... Ne znam. Bit æe me | svuda, pa mi poželite sreæu.
{6711}{6765}Sretno, tako da možeš | kupiti Mattu i meni auto.
{6769}{6813}Znaèi, radi se o tebi.
{6817}{6863}I hranu da ne moram gladovati.
{6867}{6938}- Ne zaboravite užine. Lulu. | - Hrèak mi je pobjegao.
{6942}{6987}Ne smijem zakasniti.
{6991}{7060}Opet je pobjegla. | Hrèak mi je pobjegao.
{7064}{7096}- Što je to? | - Doruèak.
{7100}{7182}- Kapetane, gubimo vezu. | - Pobjegla je. Josh.
{7201}{7269}Broj 19 je C.
{7273}{7338}Broj 20 je A.
{7389}{7446}Broj 21 je A.
{7450}{7512}Broj 22 je...
{7557}{7599}Znate što?
{7620}{7665}Ovo je dosadno.
{7688}{7788}Idemo ispitivati rjeènik.
{7792}{7876}- Odaberi tešku. | - Ispitajte ovo, zamjenice.
{8142}{8216}Sve što je glasno | šuplje je iznutra.
{8220}{8268}Bubanj, truba.
{8272}{8323}Ti nisi šupalj, znam to.
{8327}{8438}Stoga me ponizi. | Daj mi tešku rijeè.
{8578}{8644}- Imbibe. | - Piti. Daj još jednu.
{8800}{8852}- Vjetruša. | - Vjetruša?
{8856}{8924}Mali sokol, kao moja kæi.
{8928}{8996}Dajte mi još jednu. Bilo tko.
{9000}{9101}- Svudašnji. | - Svudašnji? Sveprisutni.
{9188}{9231}Dobar dan.
{9235}{9300}Sjednite. Hvala što ste došli.
{9304}{9384}Dobro, gðo Anna, | imamo nekoliko pitanja.
{9388}{9452}Pristojne preporuke. | Nije loše.
{9456}{9545}Znaèi, gðo Anna... | Anna vam je prezime?
{9549}{9641}Da. Gðica.
{9676}{9784}Recite nam zašto mislite | da ste dobra uèiteljica?
{9788}{9849}Volim taj posao. | I djeca to znaju.
{9889}{9936}To je kada doðe onaj dan...
{9940}{10036}Udarali ste u zid s djetetom | koje jednostavno ne shvaæa...
{10040}{10162}...a vi ste vidjeli nadu, ali ono | ne shvaæa, ali trudi se...
{10166}{10279}Doista se trudi. | Vi se trudite...
{10283}{10340}...i dijete se trudi...
{10344}{10466}...ali jednostavno ne shvaæa. | A onda doðe taj dan.
{10480}{10618}Tada se upali svjetlo. | Kao da izaðe veliko sunce.
{10622}{10715}I tada možete vidjeti taj trenutak.
{10719}{10828}- Živim za taj trenutak. | - To vam daje puno posla.
{10901}{10957}Evo što æemo uèiniti.
{10961}{11012}Zadržat æemo vaš životopis...
{11016}{11085}...i kad æemo drugi put tražiti, | na popisu ste.
{11096}{11136}A ovaj posao?
{11198}{11231}Imat æemo vas u vidu.
{11272}{11383}Šalite se. | Kako je to nošena?
{11408}{11447}Ne mogu vjerovati | kakvi su suci.
{11451}{11554}Ostalo je 4 i pol sekunde. | Trebaju veliki preokret.
{11667}{11700}Pogaða!
{11704}{11732}DOM REBELSA
{11811}{11858}To je moj mali.
{11886}{11972}- Jesi li bila na mojoj tekmi? | - Uèila sam za ispit.
{11976}{12032}Zar je to bilo važnije | od toga da vidiš mene...
{12036}{12084}...kako prelazim drugog | najboljeg branièa u ligi?
{12088}{12125}Kvragu, kelj.
{12129}{12179}Morala sam malo vratiti. | Ne budi dijete.
{12183}{12223}Volim vraæati stvari.
{12227}{12344}Volim stavljati krekere na | mjesto markera. Iznenade te.
{12348}{12412}Bit æu iznenaðen kad naðem | žitarice sa sladoledom.
{12416}{12467}Evo raèuna za namirnice, mama.
{12496}{12560}- Možeš postaviti stol. | - Hvala.
{12564}{12615}A zašto ga veæ nisi postavila?
{12619}{12671}Tražim barem jednu | smeðu žitaricu.
{12720}{12754}Što je?
{12790}{12835}Dobro.
{12904}{13000}- Onda, svi ste dobro? | - Da.
{13007}{13059}- Laku noæ. | - Laku noæ, mama. Volim te.
{13063}{13108}- Mogu li u kupaonicu? | - Da.
{13112}{13208}- Zaposlit æu se. | - Neæeš, kaže mama.
{13243}{13288}Neæeš.
{13395}{13486}Kišobran, što danas neæeš | dobiti, Denvere. Sunèano...
{13490}{13536}Idemo, idemo.
{13540}{13605}Razgovor danas, gozba veèeras, | ako sve dobro proðe.
{13609}{13653}Autobus polazi za 28 minuta.
{13844}{13924}Oprostite, gospoðo, možete li | mi reæi gdje je dr. Bender?
{13928}{13968}Gospoðo?
{13987}{14024}Gðice?
{14034}{14065}Kompa?
{14069}{14119}U starom je krilu.
{14125}{14204}Dobro. Dawn, u starom je krilu.
{14230}{14328}- Došli ste zbog posla? | - Da. Gdje je staro krilo?
{14332}{14408}Doði, pokazat æu ti. Kompa.
{14422}{14487}- Ja sam Mary Kimmel. | - Naravno da jesi.
{14491}{14553}- A ja sam Dawn Anna. | - Anna ti je prezime?
{14557}{14618}Kladim se da te to svi pitaju.
{14696}{14739}Ale.
{14758}{14815}Ovo je Dawn Anna.
{14826}{14872}Hvala, Mary.
{14883}{14932}Možeš li pozvati održavanje?
{14936}{14970}Može.
{14984}{15042}- Gðo Anna. | - Kako ste?
{15059}{15094}Želim ovaj posao.
{15098}{15146}Nadam se da æete me zaposliti, | ali ako to ne uèinite...
{15150}{15207}...netko drugi æe | biti jako sretan...
{15212}{15262}...jer æu se zaposliti | prije ili kasnije.
{15266}{15326}Nadam se da æe to biti prije, | jer imam 83 dolara u banci...
{15330}{15413}...i èetvero djece koja moraju | jesti, ali to nije važno...
{15417}{15551}...jer sam sjajna uèiteljica i | vaša buduæa najbolja odluka.
{15555}{15583}Dobro.
{15609}{15662}- Dobro? | - Možete li poèeti sljedeæi tjedan?
{15827}{15941}Plaæa je manja nego što bih | želio, no ako izdržite...
{15945}{16055}...do sljedeæe proraèunske krize, | možda æe biti dostatna.
{16061}{16106}Što kažete?
{16249}{16358}- Hajde, mušketiri. Javite se. | - Ovo je snimljena poruka.
{16362}{16419}Broj koji ste nazvali | je iskljuèen.
{16454}{16511}Koji vrag?
{16568}{16609}Djeco?
{16678}{16717}Djeco?
{16739}{16788}Što je s telefonom?
{16811}{16855}Kristin.
{16920}{17018}Znam kako je to, Dawn, | kad nemaš love...
{17022}{17108}...gajba je tijesna, | dijeliš kupaonicu.
{17112}{17191}Osjeæam tvoju bol, znaš?
{17200}{17248}Ali telefon...
{17255}{17320}Tako posegneš | i dotakneš nekoga.
{17353}{17383}To je kljuèno.
{17394}{17492}Danas nisam mogao dobiti | Kristin i zabrinuo sam se...
{17496}{17554}...pa sam došao provjeriti | o èemu se radi.
{17558}{17604}Možeš mi dodati to, | što god da jest?
{17714}{17749}Shane.
{17775}{17827}Reæi æu ti nekoliko stvari...
{17831}{17911}...ako æeš više ikada poželjeti | kroèiti u ovu kuæu.
{17915}{18013}Prvo, ne zovi me Dawn. Ikada.
{18048}{18150}Drugo, makni ruku | s noge moje kæeri.
{18164}{18248}Ovo nije drive-in, | blagovaonica je.
{18270}{18344}I treæe, ako imaš ideje...
{18348}{18433}...kako moje kuæanstvo | radi ili ne radi...
{18437}{18522}...možeš ih reæi sebi | u kamionetu na autoputu...
{18526}{18643}...vozeæi 90 km/h, vezan, | na putu odavde.
{18733}{18867}I kaže se: " Molim, dodaj | to, što god da jest."
{18871}{18943}Svemoæna kraljice.
{18956}{19009}"Svemoæna kraljice" je dobro.
{19088}{19148}O, da. Dobila sam posao.
{19152}{19209}- Bože. | - Mama, fantastièno.
{19213}{19272}- To je sjajno. | - Èudesno.
{19276}{19352}Ona je uèiteljica | Predavat æe
{19359}{19397}Gða Anna
{19496}{19601}Ime mi je Dawn Anna. Anna mi je | prezime. Gða Anna za vas.
{19605}{19716}U svojoj uèionici | imam samo jedno pravilo:
{19720}{19788}"Nema plivanja."
{19795}{19840}Nikakvoga.
{19844}{19896}Naravno, govorit æemo | kad nas prozovu...
{19900}{19968}...i radit æemo sa | strašæu i humorom...
{19972}{20040}...i meðusobno æemo se poštivati...
{20044}{20119}...ali neæe biti plivanja.
{20123}{20170}Ima li pitanja?
{20182}{20282}Dobro. Ako netko ima | pitanje ili prijedlog...
{20286}{20413}...drugih pravila, razgovarat æemo. | Ja imam samo jedno.
{20417}{20505}Otvorimo knjige na prvoj lekciji...
{20509}{20536}...i možemo poèeti.
{21133}{21204}- Gdje ste igrali? | - U srednjoj školi.
{21223}{21277}Igrali ste u takvoj opravi?
{21288}{21407}Bila sam MVP 3 g. U nizu. | Oprava nije imala veze s tim.
{21454}{21521}I osvojila sam državno | prvenstvo u zadnjoj godini.
{21525}{21574}Državno prvenstvo, je li?
{21588}{21654}Škola traži novu | trenericu odbojke.
{21658}{21697}Ženska ekipa.
{21731}{21820}Upravo sam dobila | posao uèiteljice, pa...
{21824}{21879}To je pravi posao. | Plaæa se u pravom novcu.
{21921}{21963}Kako vam se sviða ta lopta?
{21967}{22057}Dobra je. Mogu li je dobiti natrag?
{22291}{22347}- Moglo bi biti dobro, mama. | - Voliš odbojku.
{22351}{22427}- Bilo bi lijepo ne misliti o novcu. | - To je velika žrtva.
{22431}{22489}Za ljudske žrtve | mogu donijeti kameru.
{22493}{22535}Josh, nije smiješno.
{22539}{22581}Slušajte, radi se | o rasporedu.
{22585}{22653}Neæu moæi kuhati | ni voziti vas sve.
{22657}{22789}- Shane ima kamionet. Ima ga. | - To stvari èini još težima.
{22793}{22839}Kreni prema lopti.
{22886}{22944}Na prste.
{23073}{23139}Hajde, na pod.
{23157}{23235}Zahrðala sam.
{23239}{23331}Potrudite se da ispadnem bolja. | Hajde!
{23349}{23405}Idemo, idemo.
{23410}{23453}PONOS | REBELSA
{23711}{23753}Zdravo, trenerice.
{23763}{23848}Tko ste vi? | Što radite i što želite?
{23852}{23947}Bruce Beck, Atletska oprema Denvera.
{23951}{24043}Prodajete li puno opreme | takvim pristupom?
{24047}{24111}Ovo mi je prvi pokušaj. | Kako mi ide?
{24125}{24157}Moram iæi.
{24161}{24265}Neæe me biti nekoliko tjedana. | Ako trebate nešto od opreme...
{24269}{24329}Kad se Beck vrati.
{24355}{24405}- U redu. | - Sa svojom opremom.
{24409}{24472}- Usput, zovite me Bink. | - Bink?
{24476}{24560}- Tako me svi zovu. | - I vi im to dopuštate?
{24587}{24689}- Ja sam Dawn Anna. Anna mi je... | - Prezime.
{24693}{24745}Znam. Znao sam.
{24749}{24838}Uvjerena sam da ste znali. | Da znate.
{24853}{24915}Hvala za ovo.
{24995}{25039}Uvijek.
{25079}{25187}I bilo gdje.
{25386}{25444}Ovo je vaše buðenje.
{25448}{25503}- Ovo je vaše buðenje. | - Probudi se, mama.
{25507}{25576}- Probudi se. | - Probudi se.
{25632}{25668}Djeco?
{25688}{25725}Djeco.
{25847}{25919}Shane æe doæi po nas. | Ne brini se.
{25923}{25989}Nemamo mlijeka. | Hrèak je u bijegu.
{25993}{26046}Volimo te. Kako ti se | svidjelo buðenje?
{26050}{26125}Lulu se toga dosjetila. | Pogledaj kalendar.
{26129}{26201}Nadam se da æeš imati sjajan | dan, mama. Volim te.
{26205}{26280}Želim ti dobar prvi dan. | Puno te volim. Volim. Volim.
{26284}{26325}Kod Jenny. Matt æe me | pokupiti pješke.
{26329}{26402}Vježba, vježba. Trener me | vozi, spremam veèeru.
{26406}{26477}Knjižnica, idem po Lauren, | protuotrov veèeri.
{26481}{26569}Kupnja sa Shaneom, ples u 19:30. | Shane æe me pokupiti.
{26573}{26715}Kasno ustaješ, tekma u 19, | podgrijana veèera, protuotrov.
{26719}{26831}- Što spremaš za veèeru, Josh? | - Improvizirat æu.
{26837}{26882}- Peèenog hrèka. | - Josh.
{26886}{26966}Ljudi... Probudit æemo mamu.
{27029}{27058}Vratio sam se.
{27062}{27126}Rekao si nekoliko tjedana. | Nije prošao ni tjedan.
{27130}{27165}Brojiš dane, je li?
{27169}{27227}Što hoæeš? Želiš mi | nešto prodati?
{27231}{27327}Da. Nisam mogao spavati od pomisli | na vaše otrcane dresove.
{27331}{27420}- Što radiš kad ne možeš spavati? | - Jedem. Volim jesti.
{27424}{27471}Volim hranu. A ti?
{27475}{27542}- Hrana je dobra. Volim hranu. | - Dobro. Hajdemo jesti.
{27550}{27617}- Nisam gladna. | - Ne, mislio sam veèeras. Veèera.
{27626}{27673}- Ne mogu. | - Sutra?
{27677}{27702}Ne mogu.
{27706}{27748}Bilo koja veèer ovog mjeseca? | Zadnja ponuda.
{27772}{27881}Polaskana sam, Bink, | ali trenutaèno ne mogu.
{27885}{27964}Ne mogu izlaziti. | Ne u ovom životu.
{27981}{28081}- Starci su ti zbilja strogi. | - Imam èetvero djece.
{28085}{28143}Možda bi tvoj muž mogao | pripaziti na njih.
{28175}{28212}Šalim se. | Samo se šalim.
{28216}{28340}Nemam muža, ali imam èetvero djece.
{28344}{28436}- A ja te zovem van. | - Proèitaj neki èasopis.
{28440}{28509}Žena izaðe s tipom, | spomene mu djecu...
{28513}{28557}...i bum! On nestane | prije deserta.
{28561}{28604}- Eto vidiš. | - Što?
{28612}{28671}Volim desert.
{28746}{28776}Fantastièno.
{28780}{28849}Veæ se dugo nisam uvukla u ovo.
{28853}{28898}- Baš lijepo izgledaš, mama. | - Misliš?
{28902}{28960}Baš si lijepa.
{29043}{29118}Dobro, makni se. | Da dovršimo ovo.
{29142}{29171}Katastrofa sam.
{29175}{29216}Mama.
{29220}{29312}- Ne, imam vrtoglavicu. | - Što je? Jesi li dobro?
{29316}{29435}- Možda ne bi trebala voziti. | - Ne, nervozna sam.
{29439}{29495}Nema šanse da ne vozim.
{29499}{29570}- Dobro sam. Samo dovrši ovo. | - Sjajno izgledaš, mama.
{29574}{29627}Dovršimo to.
{29631}{29684}Mama je faca.
{29688}{29719}Opa, mama.
{29723}{29764}Misliš?
{29774}{29804}Da.
{29808}{29844}Dobro.
{29991}{30039}Što radim?
{30114}{30158}Evo nas. Vani smo.
{30162}{30238}Znam, ali malo smo vjerojatni.
{30242}{30318}Uvijek su mi se sviðali | slabi izgledi.
{30434}{30518}Znaš, promatrala sam te.
{30522}{30636}Mislila sam da je èišæenje i | ispravljanje nervozna navika...
{30640}{30675}...ali tebi se sviða.
{30679}{30744}- Voliš èistiti i ispravljati, zar ne? | - Da.
{30748}{30814}Mislim da je to | zato što sam sam.
{30818}{30916}Kad sam bio mali, roditelji su mi | rekli da odgajaju èovjeka.
{30926}{31022}Prao sam rublje sa šest godina | i dobar sam u tome.
{31058}{31110}Nikad nisi bio u braku?
{31114}{31158}Kao što sam rekao.
{31200}{31248}Jesi li bio u ozbiljnoj vezi?
{31257}{31285}Sad sam ozbiljan.
{31342}{31393}Ne tako ozbiljan.
{31402}{31463}Ne. Ne.
{31494}{31603}Ne znam. Teturala sam i padala...
{31610}{31655}To je vjerojatno stres, | zar ne?
{31678}{31785}Èetvero djece, dva posla, | a sad i vrebaè.
{31813}{31863}Prilièno stresno.
{31930}{31991}- Odmah dolazim. | - Dan je bio dug. Možemo poæi.
{32030}{32130}Znaèi, "volim desert" | je bila samo fora, je li?
{32155}{32252}Možemo li dobiti pitu? I biskvite.
{32256}{32343}Nisam bila na pravom izlasku | od vremena prije braka.
{32347}{32469}To je bilo i prije dinosaura.
{32490}{32522}Ali jedno znam.
{32526}{32610}Moraš se zagrijati prije igre, | pa æemo biti jednostavni.
{32614}{32696}Puno ti hvala. Hvala.
{32700}{32753}Ovo je igra.
{33078}{33118}Hej.
{33186}{33219}Da èujem.
{33253}{33320}Ne sviða mi se, to je sve.
{33342}{33388}Volim te.
{33393}{33440}I umorna sam.
{33454}{33536}Nemoj predugo ostati. | Dolazi oluja.
{33830}{33929}Opet, buduæi da nema znaka | izmeðu osmice i zagrade...
{33934}{34029}...sve u zagradi množi se sa osam.
{34034}{34108}Ali 2 plus A se | ne može više skratiti...
{34112}{34176}...jer ne znamo vrijednost A.
{34181}{34205}Tako je.
{34306}{34363}- Izvolite. | - Hvala.
{34530}{34580}Izvoli tablete, mama.
{34615}{34648}Pa...
{34716}{34758}Vode?
{34856}{34896}Doði.
{34932}{34972}Žao mi je, mama.
{35205}{35257}Zdravo, kompa. Dawn?
{35262}{35328}Dawn, što ti je? Dawn?
{35332}{35427}- Što nije u redu? | - Ne, dobro sam. Imam vrtoglavicu.
{35446}{35494}Idem u svoju uèionicu.
{35499}{35561}Ne, nešto je drugo. | Oèi ti èudno izgledaju.
{35566}{35680}To izluðuje deèke. Dobro sam. | Idem u uèionicu.
{35688}{35731}Lijekovi su me odrvenili.
{35736}{35823}Nisam znala jesam li | simptomatièna ili... Ne znam.
{35828}{35896}Drugi mi je rekao | da se trebam odmarati...
{35901}{35996}...što nije bilo teško obzirom na | sve lijekove koje sam imala.
{36001}{36102}Treæi ili èetvrti mislio je | da ima veze s kiropraktikom.
{36106}{36226}Otišla sam kiropraktièaru, ali | vrtoglavica je bila još jaèa.
{36231}{36303}Stoga sam kupila lijek | za vrtoglavicu...
{36308}{36367}...ali ne mogu funkcionirati | s takvim lijekom.
{36372}{36433}Lopte za odbojku su | mi plovile glavom.
{36464}{36503}Ja æu.
{36609}{36677}Zdravo. Uðite.
{36713}{36742}- Ja sam Lauren. | - Bink.
{36747}{36784}Drago mi je.
{36829}{36905}- Ovo su Matt i Kristin. | - Zdravo. Drago mi je.
{36910}{37005}- Blizanci su. Matt je stariji. | - Jer mi je stajao na glavi.
{37010}{37080}- Zdravo. | - Zdravo i tebi.
{37085}{37160}Hvala. Lijepo od tebe. | A ovo je Josh.
{37165}{37206}Josh.
{37229}{37300}Idem dovršiti veèeru.
{37305}{37369}- Želite li što popiti? | - Pivo, ako imate.
{37374}{37464}- Pivo? Svakako. | - Mogu li vam uzeti jaknu?
{37508}{37548}Doðite sjesti.
{37648}{37702}- Izvolite. | - Hvala.
{37768}{37803}Jesu li svi ovdje?
{37808}{37857}Nema mojega tate.
{37893}{37943}I tako hrèak kaže: | "Što ti se dogodilo?"
{37948}{38043}A puž odgovori: " Ne znam. | Dogodilo se prebrzo."
{38246}{38292}Kako se osjeæaš, mama?
{38366}{38432}Smušeno, ali dobro.
{38436}{38489}Bolje bih se osjeæala | kad bih znala što je to.
{38494}{38575}- A zadnja pretraga? | - Ne znam, dušo.
{38580}{38648}Mislim da sam odustala od | toga da æe bilo što pronaæi.
{38652}{38711}Ja sam anomalija.
{38724}{38762}Što je anomalija?
{38767}{38837}Rijetkost, Lulu. | Ona je rijetka.
{38842}{38899}G. Maturant.
{38915}{38979}Ne jedeš, mama. Trebala | bi nositi užinu u školu.
{38984}{39019}Ima pravo.
{39024}{39080}Iako to s prijezirom | priznajem.
{39121}{39167}To bi bio Shane.
{39172}{39211}Bolje za njega da je on.
{39216}{39270}Što ako æe to | uvijek biti anomalija?
{39275}{39376}- Ne, dušo. Bit æu dobro. | - Da. Mama?
{39380}{39432}Dr. Emerson.
{39510}{39596}Zbog bolesti zaboravljam | ime bolesti...
{39601}{39671}...ili ta bolest | ima loše ime?
{39704}{39779}Kad imate rak, znate što imate...
{39784}{39836}...a s neèim kao što je | Epstein-Barr...
{39841}{39930}...zamišljate ime odvjetnièke tvrtke.
{39960}{40037}Recite mi još jedanput. | Što je to?
{40042}{40125}- Arterijsko vaskularna malformacija. | - Vidite?
{40130}{40183}Veæ sam zaboravila.
{40216}{40270}Katkad možete | zaboraviti simptome.
{40275}{40330}U jednom se trenutku možete | osjeæati savršeno dobro...
{40335}{40394}...a u iduæem možda neæete moæi | izgovoriti vlastito ime...
{40399}{40469}...ili možete završiti na podu, | kao što znate.
{40474}{40544}S obzirom na to gdje se | nalazi problem...
{40549}{40648}...mogli biste doživjeti i | moždani udar ili nešto gore.
{40658}{40709}Dr. Kahn. Dr. Kahn.
{40714}{40759}Što æete uèiniti?
{40773}{40810}Dvije opcije. | Jedna je operacija.
{40814}{40875}- Otvorili bismo lubanju i popravili... | - Moju lubanju?
{40880}{40948}Razgovarajmo o drugoj opciji.
{40960}{41015}Zove se embolizacija.
{41020}{41082}Penjemo se arterijom | mikroskopskim alatom.
{41087}{41142}Podvežemo vene i | kapilare koje krvare.
{41147}{41199}Kada zaustavimo krvarenje, | riješili smo problem.
{41221}{41262}To zvuèi...
{41275}{41322}...puno blaže.
{41344}{41462}Manje je napadno od operacije | mozga, ali nije sigurno.
{41540}{41650}Dr. Allen, radiologija. | Dr. Allen, radiologija.
{41900}{41968}Evo ti izlaza.
{41972}{42025}Nisi to rekla.
{42072}{42148}To je puno više od onoga | za što si se pogodio.
{42153}{42203}Nema pogaðanja.
{42208}{42254}Tu sam. Neæu otiæi.
{42259}{42300}- Tek sam te pronašao. | - Gledaj, Bink...
{42304}{42378}Oboje znamo da æeš trebati pomoæ.
{42389}{42479}Djeca æe trebati pomoæ. | Dopusti da ti pomognem.
{42513}{42599}Ne shvaæam zašto bi to želio uèiniti.
{42625}{42678}Netko je jednom rekao:
{42685}{42809}"Kad nešto ne shvaæaš, | pokušaj to uhvatiti."
{42814}{42857}Tko je to rekao?
{42869}{42955}Konfucije, mislim. | Ili Woodrow Wilson.
{43013}{43099}Ili je doista dubokoumno | ili zbilja glupo.
{43113}{43171}Dubokoumno je glupo.
{43399}{43442}Evo što æemo uèiniti.
{43446}{43527}Gurat æemo fibro-optièku | kameru kroz arteriju...
{43531}{43589}...dok ne naiðe na masu | u vašemu mozgu.
{43593}{43658}Zatim æemo ubaciti iglu | i pustiti struju kroz...
{43662}{43698}Sjajno, ja sam video igra.
{43702}{43788}Pustit æemo struju kroz | iglu da spali posude.
{43792}{43864}To je kao da im | presijeèemo dovod.
{43875}{43949}Bit æete budni, ali | ništa neæete osjetiti.
{43953}{43990}Imate li pitanja?
{44000}{44086}Možete li spaliti onu koja pamti | glazbenu temu Bonanze?
{44138}{44203}- Zdravo, Matt. | - Bink.
{44321}{44370}- Zdravo, Bink. | - Zdravo, ljudi.
{44927}{44975}Voliš li hokej?
{45075}{45144}Ne shvaæam ga. | Ništa se ne dogaða.
{45148}{45218}Da. Nije kao košarka.
{45222}{45261}Ali što jest?
{45327}{45467}Trebali bi pustiti krave na led.
{45576}{45613}Hvala.
{45754}{45819}Krave na klizaljkama. | I svinje.
{45823}{45919}- I majmune koji bi ih jahali. | - I polarne medvjede.
{45934}{45976}Ljudoždere.
{45982}{46031}Ljudoždere.
{46324}{46371}Tamo sam.
{46412}{46467}Ali nemam više kamo otiæi.
{46471}{46560}Mislio sam da mogu skrenuti | i ostaviti sve netaknuto...
{46573}{46619}...ali ne mogu.
{46720}{46777}Želim iæi doma.
{46794}{46860}Znam. Znam.
{46925}{46993}Prelazimo na plan B.
{46997}{47041}Pod nož.
{47052}{47095}Pilu.
{47105}{47163}Poènu s malom pilom.
{47170}{47246}- Ne mogu se suoèiti s tim. | - Sigurno možeš.
{47250}{47311}Ništa tu nije sigurno. | Baš ništa.
{47315}{47435}- I kako ti znaš što ja mogu? | - Slušaj. Pobijedit æemo to.
{47439}{47505}Tko smo to "mi", Kemosabe?
{47511}{47577}Rupa koju æe izbušiti | je u mojoj lubanji.
{47581}{47639}I ono što æe staviti unutra | ide u moj mozak...
{47643}{47696}...a ona uplašena djeca | u èekaonici...
{47700}{47771}...moja su djeca, za koju | sam se sama brinula...
{47775}{47875}...èitav život, stoga mi | nemoj govoriti "mi".
{47879}{47957}Previše sam umorna i bojim se.
{47970}{48078}Ovo me ogoljelo do ništavila. | Ne mogu ja to.
{48130}{48239}- I uopæe nisam spavala. Oprosti. | - Znam. Znam.
{48261}{48315}Doista te volim.
{48323}{48363}Doista.
{48367}{48455}- Sve æe biti u redu. | - Kako znaš?
{48459}{48511}Znam. Znam.
{48568}{48628}Dat æu vam anesteziju u vrat.
{48632}{48739}Osjetit æete mali ubod, | a zatim hladnoæu.
{48847}{48925}Pokušajte se opustiti.
{50036}{50063}Mama?
{50072}{50126}- Hej, mama. | - Vratila se.
{50132}{50178}- Uspjela si, mama. | - Vratila si se.
{50182}{50222}Zdravo, svemirska curo.
{50924}{50969}U redu, što je ovo, mama?
{51052}{51090}A ovo?
{51254}{51301}A ovo?
{51384}{51421}U redu je, mama.
{51425}{51491}Riješit æemo to. | Samo treba vremena.
{51507}{51552}Kad æeš drugi put iæi | na operaciju mozga...
{51556}{51608}...možeš li odabrati bolnicu | s boljim slatkišima?
{51612}{51642}Josh, prekini.
{51646}{51731}Dr. Morris, nazovite 182.
{51745}{51790}Kako ide?
{51833}{51875}Teško je.
{51915}{51973}Mama, znaš što su rekli.
{51977}{52041}Što æeš više govoriti, | brže æeš se oporaviti.
{52046}{52076}Možeš ti to.
{52119}{52198}Mama, što ovo znaèi?
{52330}{52393}U redu je.
{52450}{52499}- Zdravo, ljepotice. | - Zdravo, mama.
{52678}{52766}Kapetanica odbojkaške momèadi | je zvala. Žele te posjetiti.
{52770}{52847}Sve. Mislio sam da bi | sutra mogle doæi.
{52856}{52928}- Možda u utorak. | - Da, još malo vremena.
{52932}{53036}Mislim da bi željela biti | malo bolje kad je posjete.
{53072}{53118}Dušo.
{53141}{53176}Dušo.
{53180}{53272}- Mama, ti si. | - Dušo. Dušo.
{53278}{53337}"Dušo." To si ti.
{53345}{53387}Dušo.
{53436}{53524}Brinuo sam se, ali bila je | dobro. Vidimo se.
{53528}{53611}- Zbogom, Bink. Vidimo se sutra. | - Vozite oprezno.
{53619}{53698}Bit æe dobro. Idem s vama.
{54147}{54215}Postavi težište na lijevu | stranu. Lijevu stranu.
{54219}{54267}Tako je, lijeva strana.
{54271}{54346}- Dobro, podigni desnu nogu. | - Ne mogu.
{54350}{54399}Možeš. Nema "ne mogu".
{54403}{54469}Ne ovdje. Možeš. Možeš to.
{54539}{54637}Uvijek tako poèinje. Prije | ili kasnije se uhvatiš.
{54641}{54678}I ideš.
{54682}{54743}Postavi težište na lijevu | stranu. Lijeva strana.
{54747}{54788}Sada privuci | desnu nogu k meni.
{54792}{54873}Tako je. Podigni je.
{54877}{54909}Tako.
{54913}{54952}Dobro.
{54992}{55072}Imaju li ovi ljudi svoje sobe?
{55076}{55131}Oni?
{55135}{55211}Vjerojatno èekaju da ti se | halja opet otvori.
{55215}{55277}Stavi težište na lijevu stranu.
{55292}{55363}Privuci desnu nogu | prema meni. Tako.
{55367}{55460}Dobro. Podigni. Tako.
{55550}{55602}Vruæa voda.
{55639}{55683}Vruæa voda.
{55749}{55801}Vruæa voda.
{55918}{55967}Vruæa voda.
{56027}{56111}- Lauren, otvori vrata. | - Idem.
{56115}{56205}- Lauren, otvori vrata. | - Da, idem.
{56507}{56633}Kupio sam sok, maslac | od kikirikija i žitarice.
{56864}{56907}Pomakni desnu nogu.
{56911}{57006}Tako je. Dobro. Stavi | težište na desnu nogu.
{57037}{57133}Sada pomakni lijevu nogu. | Težište na lijevu. Da.
{57144}{57242}U redu je. Dovucite stolac.
{57266}{57302}Dobro si?
{57309}{57399}Idi, Bink. Idi. Idi.
{57403}{57482}Pala je.
{57755}{57787}"Ali ja...
{57791}{57837}Dr. Seuss | Jedna riba-dvije ribe
{57841}{57871}...se kladim...
{57875}{57995}...da su prevalile dugi...
{58011}{58061}...dugi..."
{58085}{58123}- Velika. | - Velika.
{58127}{58180}- Velika. | - Velika.
{58184}{58247}- Velika. | - Velika. Pobjeda.
{58251}{58281}Pobjeda.
{58359}{58408}Nedostaješ mi, kompa.
{58415}{58471}Sebi još više nedostajem.
{58475}{58525}Ovo je loše dijeljenje.
{58529}{58603}- Trenerice Anna. | - Hej, trenerice Anna.
{58634}{58670}Brzo nam ozdravite.
{58674}{58760}- Momèad vas treba. | - Jedva èekamo da vas opet vidimo.
{58764}{58807}Nedostajete nam.
{59043}{59093}Mogu stajati.
{59111}{59149}Dobro.
{59198}{59226}Sad hodaj.
{59470}{59520}Dobro. Još jedan.
{59755}{59802}Još jedan.
{59978}{60018}Hodaj.
{60167}{60210}Hodaš.
{60232}{60277}Hodam.
{60290}{60324}Hodaš.
{60401}{60436}Hodaš.
{60606}{60686}Èula sam vaše cipele.
{60737}{60779}Kako ste?
{60812}{60861}Imala sam dobar dan.
{60866}{60918}Da, èuo sam.
{61004}{61079}Karton vam izgleda izvrsno. | Sjajno napredujete.
{61134}{61172}Samo...
{61182}{61250}Htio sam razgovarati | s vama o poslije...
{61260}{61350}Kad odete odavde, | a to æe biti uskoro.
{61360}{61400}Dobro.
{61454}{61564}Možda... Vjerojatno æete | uvijek biti simptomatièni.
{61578}{61630}Jaka svjetlost æe vam smetati.
{61654}{61766}Imat æete vrtoglavice, glavobolje...
{61770}{61830}...naroèito kad se umorite...
{61834}{61867}...stoga pazite na to.
{61872}{61949}Pazite na simptome | o kojima smo razgovarali.
{62004}{62074}Nismo mogli popraviti zaèepljenje...
{62080}{62146}...jer je postalo dio vas.
{62214}{62270}Koji vrag?
{62288}{62436}Dolaze novi lijekovi, koje | vjerojatno neæete uzimati.
{62446}{62559}I postoje novi, obeæavajuæi | operativni zahvati.
{62564}{62607}Postoji akrilno...
{62726}{62820}Zapravo sam ovo vrlo | intenzivno uvježbavao.
{63010}{63058}Žao mi je, Dawn.
{63118}{63160}U redu je.
{63184}{63246}Josh, uspori.
{63302}{63350}Dobro je. Dobro je.
{63478}{63529}Bilo je sjajno.
{63534}{63606}Bilo je baš sjajno.
{63648}{63688}Osjeæam muèninu.
{63693}{63729}Nešto nije u redu.
{63752}{63795}Nešto nije u redu.
{63799}{63847}Nešto nije u redu.
{63884}{63945}Hladno mi je. Hladno mi je.
{63949}{64040}Janice, zovi Emersona.
{64050}{64118}Znate, kockala se | s prvim postupkom.
{64122}{64159}Znala je da nema jamstava.
{64164}{64261}Poslije operacije nije mogla | govoriti ni hodati.
{64266}{64357}- To nije bilo zbog operacije... | - A sad je dobila infekciju...
{64362}{64459}...od mjesta iz kojega se svim | silama želi izvuæi.
{64478}{64532}To nije prepreka.
{64558}{64644}Traži se dr. Stemen.
{64662}{64719}Koliko dugo? Recite mi.
{64772}{64815}Do odlaska kuæi?
{64880}{64954}Tri tjedna, manje-više.
{64994}{65042}Tri tjedna?
{65064}{65180}Dr. Emerson je rekao da | može doma za tri tjedna.
{65190}{65245}Ovaj kolaèiæ je koma.
{65376}{65519}"Mladi sportaš kao pustinjski | cvijet treba hladan tuš."
{65650}{65714}Neæu ovo raditi. | Nisam na redu.
{65718}{65766}Ti si na redu, Kristin.
{66108}{66173}- Želim je odvesti doma. | - Nismo spremni za to.
{66178}{66237}Treba svoju djecu, | a i ona trebaju nju.
{66242}{66328}Ne može ispunjavati nièije | potrebe. Treba stalnu njegu.
{66332}{66383}Rekli ste da se mora | vratiti svome životu.
{66388}{66442}To je bilo prije zadnjega | maloga problema.
{66446}{66508}Rekli ste da se izvukla.
{66552}{66586}Gledajte.
{66602}{66662}Samo se pitam | jeste li spremni.
{66668}{66705}To je sve.
{66710}{66742}- Mike. | - Zdravo, doktore.
{66746}{66803}- Kako ide? | - Dobro.
{66834}{66936}Govorimo o intravenoznoj | administraciji antibiotika...
{66940}{67034}...svaka èetiri sata, bez iznimaka, | fizikalnoj terapiji...
{67038}{67105}To je ozbiljna njega. | Vrlo ozbiljna.
{67110}{67145}Ja sam ozbiljan.
{67150}{67182}A ta djeca...
{67186}{67263}Vidio sam ih, ali drukèije | je 24 sata na dan.
{67268}{67334}To su 24-satna djeca.
{67374}{67462}Takvu djecu neæete vidjeti | u ovom ni u iduæem životu...
{67502}{67554}...ako vjerujete u te stvari.
{67590}{67633}Oprostite.
{67640}{67708}U redu. Vaša je.
{67772}{67806}U redu.
{67826}{67871}Dobrodošla kuæi | Mama
{68046}{68110}- Evo je. | - Ide?
{68118}{68182}Da. Idemo.
{68226}{68278}Zaboga.
{68396}{68453}Takav metež.
{68484}{68531}Takva strka.
{68536}{68566}Ne trebam ovo.
{68690}{68734}Joshie.
{68780}{68835}Josh, mièi se s puta.
{68854}{68903}Vidi tko je ovdje.
{68908}{68992}Dobro došli, trenerice Anna. | Vi ste najbolja banana.
{68996}{69054}Zbor i odbojkaška momèad.
{69058}{69105}Zdravo, Mary.
{69126}{69220}Dobro. Sad idem malo drijemati.
{69232}{69328}Dobrodošla kuæi, | svemoæna kraljice
{69438}{69530}- Bože. | - Oprosti. Mislio sam da si gore.
{69544}{69578}Sjajna frizura.
{69582}{69629}Pravi se javio.
{69634}{69683}Samo pokušavam...
{69726}{69828}- Kad Bink dolazi? | - Ne znam, vjerojatno uskoro.
{69852}{69897}- Dobro. | - Samo...
{69978}{70078}Samo ti želim reæi | da posve odobravam...
{70082}{70138}...njega i tebe.
{70142}{70202}Odobravam njega i tebe.
{70220}{70269}Bio je sjajan.
{70318}{70388}Ne znam kako... | Bio je sjajan prema meni.
{70392}{70494}- Doista. | - Samo nestani odavde.
{70726}{70832}Uvijek donosi vlastiti dresing | za salatu iz Aljaske.
{70836}{70892}Izbirljiva je.
{71106}{71174}To su blizanci Riley. | Govore latinski.
{71178}{71286}Znam, ljudi. | 5.30 je. Što oèekujete?
{71504}{71537}Spremna?
{71542}{71575}Da.
{71604}{71640}Idemo.
{71652}{71713}- Hoæu, Kristin. | - Neæeš, mama.
{71718}{71759}Hoæu, Kristin.
{71764}{71847}Neæeš se vratiti, mama. | Nisi spremna.
{71852}{71887}Kristin...
{71926}{71966}Jesam.
{72152}{72256}- Jesam, Kristin. | - Dobro.
{72758}{72830}Gdje smo ono stali?
{73084}{73150}- Timeout. | - Timeout, Rebelsi.
{73189}{73268}Jeste li zabrinute zbog mene?
{73272}{73359}Bacite se na pod ili idemo doma. | Ja imam štap, a ne vi.
{73363}{73420}- Na teren. | - Idemo, trenerice.
{73428}{73474}Ni tebe baš ne volim.
{73478}{73544}Gledaj vanjsku udaraèicu. | U mreži je cijelu veèer.
{73548}{73618}Jedan, dva, tri. Zajedno.
{74136}{74204}Kristin, da ti ugasim svjetlo?
{74208}{74243}Ne.
{74261}{74301}Slatkice.
{76348}{76416}PET GODINA KASNIJE
{76561}{76613}Letjela sam.
{76619}{76670}Spavaj dalje, dušo.
{76674}{76715}Hoæu.
{76735}{76805}Crteži su ti èudesni.
{76856}{76920}Prebrzo rasteš.
{76941}{77002}Sve ide prebrzo.
{77006}{77045}Znam.
{77098}{77142}Znam.
{77146}{77231}Veæ ste se vratile? | Kako je bilo na trèanju?
{77235}{77339}- Sjajno. Dan je lijep. | - Držale ste dobar tempo.
{77343}{77440}- Sve se dimilo. | - Dimilo se? I ja kažem. Nešto se dimilo.
{77444}{77484}Kakvo ste vrijeme napravile.
{77488}{77567}1.600 m za èetiri minute. | I to bez imalo znoja.
{77571}{77606}Kako to?
{77647}{77720}Dobro, presjekle smo kroz | Hendersonov pašnjak.
{77724}{77776}Ima nova grla.
{77790}{77838}Posve su nova. | Bile smo glupe.
{77842}{77930}Ovisi kako gledaš na to. | Šetale ste prirodom...
{77934}{78037}...a sada imate energije za | skokove. Smjesta, na liniju!
{78041}{78090}Townsend, Lauren, za mnom.
{78094}{78145}Ti si kapetanica... Hajde!
{78149}{78241}Suigraèice su te izabrale, a | kapetanica vodi. Ti ne vodiš.
{78245}{78350}Stoga tu sjedni i pusti ih | da skaèu umjesto tebe.
{78354}{78440}Drago mi je što ste vidjele | stoku. Hajde, hajde!
{78444}{78490}Brže!
{78675}{78772}Nisam ga vidjela dva tjedna, | ali nisam znala da æu šiziti.
{78776}{78817}Èuvaj se, Bink.
{78821}{78877}Reci mi od èega se | sastoji taj posao.
{78881}{78949}Od svega. Èišæenje | kaveza, šetanje pasa...
{78953}{79010}...hranjenje bolesnih ptica.
{79014}{79080}Èak bih pomagala | pri uškopljavanju.
{79084}{79145}Uvijek sam govorila djeci | da æe s dobrim ocjenama...
{79149}{79212}...moæi naæi posao, | ali ne znam.
{79216}{79280}Josh ove godine možda | neæe dobiti stipendiju.
{79284}{79351}Kažu da im dolazi dobar | braniè iz New Yorka...
{79355}{79439}...a i želimo pomoæi Kristin | i Shane s njihovom kuæom.
{79443}{79568}- Pusti da sama kupujem CD-e. | - Radi se o CD-ima. Ne znam.
{79572}{79641}Izgubi posao, naði posao. | Svuda samo posao, posao.
{79646}{79689}Ija-ija-o.
{79849}{79904}Bink, opet èistiš.
{79908}{80012}Posao pravoga muškarca | nikad nije gotov.
{80204}{80277}- Razmišljao sam. | - Ne u vožnji, nadam se.
{80303}{80388}- Puno sam razmišljao. | - Nemoj razmišljati i voziti.
{80400}{80471}Prijatelj me neki dan pitao...
{80475}{80554}...što volim kod žene, | neobavezno.
{80572}{80669}Pomislio sam: Treba biti lijepa...
{80677}{80719}...pametna...
{80724}{80761}...zabavna...
{80776}{80844}...velikodušna... | - Èetvero djece, vaskularno izazvana.
{80848}{80886}...dobra...
{80895}{80927}...iskrena...
{80936}{80965}...jaka.
{81032}{81077}Prekidaš sa mnom?
{81144}{81200}Nikada to ne bih ni sanjao.
{81235}{81296}Ni u tisuæu godina.
{81315}{81398}Sve što si proživjela, | što si mi pokazala.
{81402}{81464}Sve što sam nauèio.
{81472}{81560}Da dobiješ ono što trebaš | kada to trebaš.
{81600}{81628}I ti si sve to.
{81657}{81711}Ti si sve što trebam.
{81725}{81788}Ti si ono što sam sebe pitao | proteklih pet godina...
{81792}{81844}...i nisam imao | hrabrosti odgovoriti.
{81858}{81924}Pitanje je:
{81949}{81983}Hoæeš li se udati | za mene?
{82010}{82050}Da, baš.
{82088}{82118}Hoæeš li se udati | za mene?
{82405}{82472}- Hoæemo li imati prave? | - O, da.
{82536}{82632}Doði da te mogu puno ljubiti.
{82802}{82837}Naljepnica s piva?
{82841}{82886}Pokazivala ju je | kao da je dijamant.
{82890}{82973}Vjerojatno je ostavio pravoga | u autu. Upozorio sam mamu.
{82977}{83040}- Sad smo posve Binkirani. | - Šuti, Josh.
{83044}{83140}Dobila si svoju sobu, | telefon i postala Kristin.
{83144}{83180}Znaš što? | Šuti, Josh.
{83184}{83271}Josh, konferencijski poziv | nije dobar za tebe.
{83275}{83355}Èini se da æemo dobiti i novu kuæu | na Highlands Ranchu.
{83359}{83466}- Highlands Ranch? | - Kako romantièno.
{83470}{83535}- Dolaziš na vjenèanje? | - Hoæeš li promijeniti školu?
{83539}{83596}- Imaju li tamo vodovod? | - Josh.
{83600}{83676}Ne moram mijenjati školu. | Ostajem Rebel.
{83680}{83762}Moram igrati za mamu zadnju godinu. | Ionako me vozi.
{83766}{83842}I pobrinut æu se da svi imate sobe | kad doðete na vjenèanje.
{83846}{83892}Josh, ti možeš spavati | u pseæoj kuæici.
{83896}{83965}Tako æe i biti ako ne dobijem | peticu iz kemije. Vidimo se.
{83969}{84042}- Bog, ljudi. Volim vas. | - Vidimo se.
{84054}{84128}Matt? Još si tu?
{84132}{84232}Jesam, Lulu. Još hvatam | dominikanske žabe.
{84236}{84308}- Pjevaju li veèeras? | - Pjevaju.
{84312}{84352}Slušaj.
{84835}{84891}Kakav medeni mjesec.
{84931}{84987}Dome, slatki dome.
{85052}{85125}Dušo, gdje mi je èetkica za zube?
{85226}{85283}Lulu, 27 minuta.
{85327}{85357}Jesi li spremna?
{85361}{85404}Naravno.
{85408}{85463}- Posve. | - Posve.
{85531}{85617}Ako je poticajni iznos X...
{85626}{85696}...a iznos produktivnosti...
{85700}{85803}...ovisna varijabla Y...
{85807}{85933}...s time da je Y jednako, | recimo 1,5 puta X...
{85937}{86091}...taj odnos možemo prikazati | grafom kao linearnu funkciju.
{86095}{86205}Tako roditeljima objasnite | da trebate povišicu džeparca.
{86209}{86251}Dobro.
{86391}{86435}Oprosti, Leonarde.
{86498}{86547}Vaš zadatak...
{86551}{86587}...za...
{86656}{86691}...je...
{86754}{86794}...stranica...
{86891}{86939}Je li 23, gðo Anna?
{86943}{86988}123.
{87010}{87056}123.
{87127}{87231}Kad sam se vratila uèenju, | primala sam školarinu.
{87235}{87335}Moji medicinski raèuni bili su | znanstvena fantastika.
{87339}{87403}Trebala sam osiguranje.
{87407}{87463}Trebala sam mjesto | na koje mogu otiæi.
{87467}{87506}Trebala sam posao.
{87559}{87615}Doista sam trebala | znati mogu li to.
{87619}{87667}Više to ne moram znati.
{87671}{87726}Ta djeca zaslužuju više | od pola uèiteljice.
{87730}{87830}Posao nije ništa | ako se usporedi s tim.
{87866}{87898}Dawn.
{87902}{88019}Dio tebe vrijedi 10 puta više | od bilo koga drugoga.
{88044}{88119}Kad veæ govorimo | o zbrkanoj matematici.
{88159}{88255}Još mogu trenirati. | Lauren sada uglavnom vodi igru.
{88259}{88359}Ali moram odustati od ovoga. | Jednostavno moram.
{89021}{89075}- Hej. | - Hej.
{89098}{89149}- Što je to? | - Moje bolovanje.
{89153}{89228}- Što s njima? | - A ovo su neiskorišteni slobodni dani.
{89232}{89296}- Ne pratim te. | - Nisam ih iskoristila. Tvoji su.
{89315}{89389}- Mary, ne mogu... | - Nemoj ni pokušavati.
{89393}{89467}Znaš da bi ti uèinila isto. | Znaš to.
{89472}{89535}Tvoji su. Iskoristi ih.
{89701}{89739}Ja nikada nisam bolestan.
{89900}{89964}Vi èak i ne radite ovdje.
{89976}{90008}Iz cijeloga su okruga.
{90012}{90097}Došli su predati svoje dane èim su èuli.
{90435}{90477}U redu.
{90646}{90696}Dobro, Lulu, dosta.
{90700}{90749}Dvorana se vrti. | Moram sjesti.
{90753}{90814}Znaš što moraš uèiniti | da ih pripremiš?
{90818}{90892}Ljudi, idemo, idemo.
{90897}{90945}Trenerica uzima pauzu.
{90949}{90998}Ove smo godine jedanput | veæ izgubile od njih.
{91002}{91089}Bolje smo od njih. Još tri pobjede | i u diviziji smo.
{91093}{91185}To su domaæe utakmice. | Dodavanje, udarac, pobjeda.
{91189}{91228}- Možemo li mi to? | - Da.
{91232}{91284}- Pitala sam, možemo li mi to? | - Da!
{91288}{91338}Jedan, dva. Zajedno!
{91468}{91581}Razdoblje inkubacije jajeta | pileta s Rhode Islanda
{92068}{92109}To!
{93088}{93164}Ponosim se ovom momèadi | koliko i svima do sada.
{93168}{93256}Sve ste ostavile na terenu | u zadnjih nekoliko utakmica.
{93260}{93306}To je sve što mogu | tražiti od vas.
{93310}{93391}- Igrale ste zajedno. | - Da, Lulu.
{93396}{93477}- Moje jaje se veæ trebalo izleæi. | - Što, dušo?
{93482}{93549}Moje jaje. Nije se izleglo.
{93554}{93640}Inkubacija je završila. | Trebalo se izleæi pile.
{93644}{93721}Daj mu još dan, dva.
{93726}{93805}To je kao raspored. | Znaš, vlakovi kasne.
{93810}{93878}Ti si, draga moja, došla ranije.
{93894}{93946}Možda je jaje æorak.
{93950}{94000}Možda ga je Mozart ubio.
{94004}{94108}Možda bi mogla navuæi dekicu | na njega da ga ugriješ.
{94112}{94197}Ili šeširiæ i pidžamicu.
{94224}{94264}Ja æu.
{94274}{94310}Dobra zamisao.
{94314}{94365}Što mu je?
{94380}{94458}- Nisi trebao. | - I nisam, gospodine.
{94496}{94553}- Shane, opusti se. | - Zdravo, Shane.
{94558}{94623}Zdravo. Došao sam zaprositi | Kristininu ruku.
{94628}{94668}Kompa, kompa.
{94672}{94761}Molim vas, pristanite jer sam | je poslao u potragu gradom...
{94766}{94839}...na sva mjesta na kojima smo | bili i ostavio joj tragove...
{94844}{94906}...i ove bijele ruže | na svakom mjestu.
{94910}{94981}Zakon si. Zakon si.
{94986}{95063}Doæi æe svakog trena. | Doista sam nervozan.
{95068}{95128}- Moram nazvati Josha. | - Mislim da bi mogla pristati.
{95132}{95182}Ali neæu to uèiniti | bez vašeg blagoslova.
{95186}{95220}Uèinio bi ti to.
{95224}{95251}Stoga...
{95256}{95344}...hoæete li nas blagosloviti... | - Nazovi nekoga.
{95348}{95491}...ako se ja i vaša kæi vjenèamo, Dawn?
{95512}{95570}Nemoj me više nikada | nazvati Dawn.
{95574}{95616}Možeš me zvati mama.
{95620}{95685}Ajme. Evo je, evo je.
{95690}{95733}- Evo je. | - Bože moj.
{95738}{95776}Bože moj.
{95780}{95871}- Kristin...? | - Da, da, da.
{95876}{95956}Hoæu. Hoæu. Toliko te volim.
{96024}{96076}Volim te... Mama.
{96080}{96121}Dušo.
{96136}{96179}Èovjeèe.
{96228}{96271}Da vidimo.
{96276}{96360}Divan je. Tako je lijep.
{96424}{96463}Ne mogu si pomoæi.
{96468}{96557}- Ja æu ti pridržati ruku. | - Bože.
{96590}{96637}Bože.
{96744}{96784}Velika veèer, je li?
{96796}{96844}Velika, da.
{96914}{96951}Hej, Lu.
{96956}{97037}Kad æeš biti svjetski | priznata biologinja...
{97042}{97114}...a stari Henderson æe još | misliti da si veterinarka...
{97118}{97206}...i nazove te usred noæi jer je | jedno njegovo tele zaglavilo...
{97210}{97280}...a vani je metar snijega...
{97284}{97366}...možda æeš poželjeti spora jaja.
{97436}{97522}- Laku noæ, dušo. | - Laku noæ.
{97612}{97668}Hajde. Da èujem.
{97708}{97745}Dobro.
{97874}{97917}Evo.
{97926}{98023}Ugleda je i ona ugleda | njega preko sudnice...
{98028}{98111}...i kaže mu: | "O, moj hrabri ratnièe."
{98116}{98208}I razgovaraju, | a onda on kaže ovo:
{98212}{98305}"Nemam rijeèi za ovu sreæu.
{98310}{98412}Napuštaju me. | Radost je prevelika."
{98416}{98532}Zatim se poljube i on kaže: | "I ovo, i ovo...
{98536}{98655}...neka bude naše najveæe neslaganje!"
{98774}{98830}Ali nije samo to.
{98834}{98946}Ima toliko toga | i lijepo je i veliko...
{98954}{99088}...ali tako je veliko da je | užasno, ali lijepo.
{99092}{99151}Tako lijepo, znaš?
{99156}{99279}No èini se da je sve u zadnje | vrijeme preveliko ili premalo.
{99284}{99332}Ili previše pre.
{99352}{99424}Tako previše pre.
{99724}{99786}Hajde, maleni.
{99836}{99863}Dobro jutro, | Denvere.
{99868}{99975}20. travnja je, 1999. Danas | je roðendan mojoj teti Bunny.
{99980}{100024}Teta Bunny, ako slušaš...
{100234}{100302}26 minuta, Lulu.
{100386}{100449}Gdje su moji kljuèevi?
{100534}{100620}- Shane. Tko bi pomislio? | - Bijele ruže.
{100632}{100764}- Zakon je. | - Doista to nisam predvidjela.
{100774}{100859}Nadam se da æe haljine | za djeveruše biti cool.
{100864}{100912}Kristin ima dobar ukus...
{100916}{100995}...ali katkad kod vjenèanja | ljudi jednostavno polude.
{101000}{101103}Želim izgledati dobro. | Vrlo jednostavno i elegantno.
{101108}{101179}To pile æe ti se pokakati u krilo.
{101184}{101281}Nema šanse. Povezani smo. | Moraš se povezati.
{101285}{101368}Povezat æu ga za noge | ako upropasti tu suknju.
{101400}{101474}Ne pušim ga kao | projekt iz biologije.
{101478}{101579}- Kako to misliš? | - Nemoj mu dati ime.
{101584}{101663}- Moo Shu. | - Moo Shu?
{101668}{101732}- Jesi li spremna? | - Naravno.
{101884}{101959}- Mama, baš totalno. | - Totalno.
{101964}{102001}Zdravo, Lauren.
{102014}{102042}Èovjeèe.
{102154}{102235}Apsolutno. Vjeèno.
{102518}{102564}SREDNJA ŠKOLA COLUMBINE | SRETNO
{103109}{103189}Prijavljena je pucnjava | u srednjoj školi Columbine.
{103202}{103298}Policija potvrðuje pucnjavu | i nasilje u školi...
{103304}{103368}...gdje gotovo 2000 uèenika | pohaða nastavu.
{103372}{103461}Ponavljamo, pucnjava i | eksplozije u školi Columbine.
{103465}{103526}Molimo sve roditelje uèenika...
{103530}{103562}...da ostanu sabrani.
{103566}{103612}Takoðer ih se moli | da ostanu kod kuæe.
{103616}{103705}Oko škole su postavljene | blokade i nitko nema pristup.
{103709}{103772}Još nema vijesti o | ranjenima ili ubijenima...
{103776}{103825}...ali pozvane su | specijalne jedinice.
{103829}{103893}U knjižnici je. | Sjedi za stolom.
{103897}{103945}Za stolom je u knjižnici.
{103949}{104005}Dobro, idi kuæi. Zna da | treba nazvati. Nazvat æe.
{104009}{104039}...leže na tlu...
{104043}{104099}U knjižnici je. Nazvat æe.
{104133}{104189}...policija okruga | Jefferson i Arapahoe...
{104193}{104236}...podigla je barikade...
{104240}{104316}Ostani mirna. | Nazvat æe. Dušo!
{104471}{104516}U redu je.
{104599}{104683}- Zdravo, Bink. Ovdje... | - Ne, ne, ne.
{104687}{104722}Bink.
{104837}{104904}Još se ne zna koliko je | uèenika ranjeno.
{104908}{104952}Ne zna se ima li žrtava...
{104956}{105064}...ali izvješæa o stalnoj | automatskoj paljbi pristižu...
{105068}{105177}...od stanovnika koji su | svjedoci tog strašnog napada.
{105181}{105209}Bože.
{105218}{105312}FBI je dobio prijavu da je | pucnjava poèela oko 11 sati.
{105316}{105400}Imamo izvješæa o pozivima | policiji iz škole.
{105404}{105498}Svjedoci javljaju | o automatskoj paljbi...
{105583}{105619}Halo?
{105630}{105688}- Dawn? | - Ovdje sam, Shane.
{105692}{105784}Koji novinar? Koje novine? Boston?
{105788}{105897}Ne, ne možete me zvati. | Linija mora biti slobodna.
{105901}{105969}Linija mora ostati | slobodna, Shane.
{106008}{106044}Halo?
{107460}{107520}Još se ne zna koliko | je uèenika ranjeno.
{107524}{107568}Ne zna se ni | ima li mrtvih...
{107572}{107668}...ali vijesti o stalnoj paljbi | iz automatskog oružja...
{107672}{107720}...pristižu od ljudi | u okolnim kuæama.
{107724}{107820}Ne, bako. Rekla sam da æu te | nazvati èim se Lauren javi.
{107824}{107900}Roditelji uèenika | mole se da ostanu mirni.
{107904}{107979}Kad vidite Lauren, recite joj | da nazove doma. Èekamo je.
{107983}{108060}- Hvala. | - Mole se i da ostanu kod kuæe.
{108066}{108124}Ceste su blokirane.
{108128}{108197}Lauren? Prestanite nas nazivati!
{108201}{108275}Linija mora biti slobodna. | Što vam je, ljudi?!
{108279}{108313}Samo poklopi!
{108317}{108370}Prenijet æemo vam informacije | èim ih saznamo.
{108374}{108445}Rodbino uèenika škole Columbine...
{108449}{108547}...ostanite kod kuæe. | Javit æemo vam se.
{108551}{108607}Gdje je Lauren?
{108627}{108672}- Bože moj. Bože moj. | - Halo?
{108676}{108750}Linija mora ostati slobodna.
{108809}{108834}Gdje je Lauren?
{108929}{109018}Jasno mi je koliko vam je ovo teško...
{109026}{109113}...i želim naglasiti da | pitanja koja imamo za vas...
{109117}{109200}...postavljamo kao odvjetnici. | - Odvjetnici?
{109212}{109276}Da. Mi smo Udruga | za zastupanje žrtava.
{109296}{109340}Je li moja Lauren žrtva?
{109352}{109448}Pitanja koja imamo æe | pomoæi da se to utvrdi.
{109503}{109547}Je li moja kæi mrtva?
{109598}{109651}Trenutaèno to | ne možemo potvrditi.
{109681}{109747}Što je Lauren jutros nosila?
{109779}{109926}Plavu suknju i bijelu majicu | kratkih rukava.
{109930}{109963}U redu.
{109967}{110053}Ima li madeža ili tetovaža?
{110108}{110182}Nema tetovaža. Zaboga, ne.
{110278}{110311}Što je?
{110324}{110402}Ima tetovažu, mama.
{110406}{110485}Namjeravala ti je reæi, | ali oèito nije.
{110521}{110593}Mislila ti je reæi kasnije.
{110597}{110626}Malena je.
{110643}{110744}Mislila ti je reæi kad maturira.
{110769}{110812}Tetovaža?
{110816}{110850}Imala je malenu tetovažu.
{110862}{110920}Namjeravala ti je reæi.
{110926}{110961}Gdje je tetovaža bila?
{110994}{111062}Na kuku.
{111428}{111489}Donosit æemo vam informacije | èim postanu dostupne...
{111493}{111592}...i roditelji uèenika | koji se još nisu javili...
{111596}{111674}...sada je potvrðeno | da su meðu ubijenima.
{111689}{111727}Mama.
{111737}{111792}Mama, što se dogodilo?
{111847}{111900}Gdje je Lauren?
{111904}{112024}- Bože. Gdje je Lauren? | - Na TV-u kažu da je Lulu mrtva.
{112129}{112204}Rekli su na TV-u.
{112386}{112456}Mama, mama...
{115227}{115290}Spavaš. Probudi se.
{115493}{115532}Probudi se.
{115571}{115645}Sve æe biti u redu.
{115793}{115850}Draga kæeri...
{115880}{115944}...posvuda sam te tražila.
{115948}{116014}Mislim da te vidim | gdje god pogledam...
{116019}{116087}...ali to je kao da vidim | nešto krajièkom oka...
{116091}{116146}...a kad pogledam ravno | u to, nema nièega.
{116183}{116230}Zašto pišem?
{116253}{116312}Veæ sam ti sve rekla.
{116326}{116373}Ne mogu prestati | razgovarati s tobom.
{116403}{116467}Rekla sam ti sve | što se dogodilo...
{116475}{116605}...i još uvijek imam užasan | osjeæaj da je sve u redu.
{116619}{116699}Jedno vrijeme nisam htjela | da se više bilo što dogodi...
{116704}{116790}...da život stane | jer tebe više nema.
{116805}{116879}Stoga sam uèinila ono u èemu | sam dobra. Govorila sam.
{116887}{116936}Moje ime je Dawn Anna.
{116941}{116982}Nisam profesionalni govornik.
{116987}{117110}Majka sam koja zastupa sve | koji su ikada voljeli dijete.
{117151}{117235}Lauren Townsend, moja Lulu...
{117243}{117331}...napisala je u svoj dnevnik da | æe biti potrebno nešto golemo...
{117336}{117398}...da se naš svijet | prisili na promjenu.
{117403}{117456}Nadala se da æe to doživjeti.
{117461}{117485}Hrabro je govorila...
{117490}{117595}Prvi sam put osjetila tvoju | blizinu na prvom maršu.
{117613}{117666}Milijun mama.
{117693}{117740}Imala sam osjeæaj | da je to svijet.
{118090}{118141}Hoæeš kokice?
{118201}{118260}Mala McKenna.
{118264}{118334}Daj mi to dijete.
{118338}{118422}Kunem se, Lulu, kad pomislim | koliko bi voljela neæakinju...
{118427}{118546}...i koliko bi ona voljela tebe, | to je doživotna tuga.
{118579}{118624}Hoæeš vidjeti Lulu?
{118629}{118670}Pogledaj Lulu.
{118800}{118837}Znaš li to?
{118842}{118903}Pitam se možeš li to | uopæe osjetiti.
{118908}{118990}Ili je sva tvoja divna | žudnja pala s tobom?
{119339}{119384}Rušimo onu knjižnicu.
{119408}{119490}Gradimo novu s novèiæima | iz cijeloga svijeta.
{119495}{119579}Ne bi vjerovala | što je ljudima u srcima.
{119607}{119702}Koliko žele da se stvari promijene | i koliko je to teško.
{119750}{119840}Prestat æu žaliti ljude koji | te nisu stigli upoznati.
{119863}{119928}Voljela bih da mi daš znak.
{119951}{120035}Osjeæam se kao da razgovaram | sama sa sobom, kao i obièno.
{120045}{120150}A možda i ako razgovaram sa | sobom, razgovaram i s tobom.
{120189}{120323}Na dan tvoga roðenja rekli su | da neæemo preživjeti.
{120370}{120442}Bila sam uplašena i slaba, | dok sam sama ležala.
{120446}{120474}Èula sam glas.
{120619}{120751}Držao me kao ruke. Rekao je: | "Sve æe biti u redu."
{120759}{120858}Žudim za mirom i sigurnošæu | koje sam tada osjetila.
{120875}{120930}"Sve æe biti u redu."
{120934}{121039}Rekla si to djevojèicama | pod stolom s tobom.
{121043}{121115}Onima koje su se | izvukle zbog tebe.
{121231}{121301}Želim ti reæi nešto | što ti još nisam rekla.
{121305}{121383}To je stvar koju ti voliš, | a ja sam upravo nauèila.
{121387}{121498}Najveæi organizam na Zemlji | je šumarak jasika.
{121518}{121567}Jesi li to znala?
{121603}{121712}Sva stabla su spojena pod zemljom | u jedno veliko drvo.
{121772}{121838}To je nešto što bi ti meni rekla.
{122042}{122139}Lauren Dawn Townsend | 17. 1. 1981. - 20. 4. 1999.
{122163}{122239}Mislila sam da sam umrla | onoga dana kad si ubijena.
{122283}{122312}Imala si pravo.
{122343}{122396}Spavala sam.
{122445}{122502}Govorila sam u snu.
{122581}{122651}Sada sam budna | i ovo sam položila...
{122655}{122776}...da to mogu vidjeti pred sobom | i da sve mogu pustiti...
{122822}{122925}...da se rodi u ovome svijetu, | svijetu bez tebe.
{122926}{123126}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan  
{123422}{123543}Nedostaješ mi, hvala ti, | blagoslovljena bila svaki dan.
{123547}{123619}Uvijek te voli, mama.
{123731}{123776}DANAS DAWN ANNA LOBIRA | ZA KONTROLU ORUŽJA
{123781}{123840}I DILJEM ZEMLJE | DRŽI GOVORE UÈENICIMA
{123844}{123887}O SPRJEÈAVANJU | NASILJA U ŠKOLAMA.
{123949}{124014}OVAJ FILM POSVEÆEN JE | ONIMA KOJI SU IZGUBILI ŽIVOTE
{124018}{124051}U SREDNJOJ ŠKOLI | COLUMBINE...
