{750}{786}SMRT SMOOCHYJU
{844}{900}Šest mjeseci ranije...
{918}{993}Poèinje! Randolph Duga!
{996}{1084}Dobro došli na šou omiljenog|zabavljaèa djece, Randolpha Duge!
{1089}{1194}Predstavljamo vam najboljeg|prijatelja na svijetu, Randolpha Dugu!
{1231}{1355}Tu su i Angelo Pike i Djeca Krinkle!|-Prijatelja ima svih velièina!
{1358}{1388}Tako je, Dugo!
{3034}{3159}Znate li èega još ima svih velièina?|Naših proizvoda. I na Internetu smo.
{3167}{3288}Na RainbowRandolph.com|Posjetite nas. Nije besplatno.
{3335}{3418}Randolph Duga u|Garden State Paviljonu
{3924}{4004}Moj æe klinac biti u prvom|planu i sjediti na stolici?
{4030}{4139}Želite da balavac bude|u mom šouu? -Da. Jako.
{4172}{4277}Onda se ne miješajte u moj|jebeni posao. -Samo smo...
{4296}{4340}Nazvat æu ako bude mjesta.
{4391}{4523}Stoj, pederu! -Baci aktovku!|FBI! -Nisam ni taknuo novac!
{4529}{4623}Uhiæen si. -Ja sam jebeni|Randolph Duga. Djeca me obožavaju.
{4708}{4854}Korupcija u Zemlji Krinkle? Randolpha|Dugu uhitio je FBI u baru Patsy.
{4976}{5011}Duga je uhiæen
{5027}{5063}FCC sondira djeèje emisije
{5347}{5465}Gospodo, i ja sam isto|toliko šokiran koliko i vi...
{5474}{5585}Ostavi to za novine! lmamo|nervozne sponzore. Što æeš poduzeti?
{5604}{5675}Izvrsno pitanje. Imam popis|zamjena... -Provjerenih?
{5681}{5865}Isuse Kriste! Odakle ih samo vadiš?|Uvjeravam vam, te, g. Stokes,
{5872}{5996}ova mreža neæe preživjeti još|jednog Randolpha Dugu. -Apsolutno.
{6001}{6131}Osobno æu pronaæi zamjenu.|Izvoðaèa s karakterom i èasnog.
{6143}{6244}I što je najvažnije...|-Besprijekorno, jebeno èistog!
{6268}{6311}Besprijekorno èistog.
{6319}{6365}Buggy Ding Dong? -Ovisnik o heroinu.
{6377}{6430}Danny plesaè s|trga. -Tuèe ženu.
{6434}{6506}Princeza Poppy? -Nemoj me zajebavati.
{6513}{6615}Oprosti. -Crni Skippy i trolovi?|-Skippyja su deportirali, a trolovi...
{6625}{6753}Koga briga? Ovo je nemoguæe.|Zadavila bih Randolpha Dugu.
{6762}{6830}Daviti ga dok mu oèi ne ispadnu!
{6834}{6924}Prije nego što poènemo maštati,|spasimo moju guzicu. -Oprosti.
{6940}{7087}Što je sa Sheldonom Mopesom? -Nismo|valjda na to spali? Nosorog Smoochy?
{7093}{7160}Kakav blesan. -Baš takvog|i trebamo. Mièi nogu s mog stola.
{7171}{7321}Tip ima kostim. Lažnjak. -Izuzmi|lovu mreže i ostalo, i svi su isti.
{7326}{7462}Marginalci, propali glumci...|-Ti to ozbiljno? Svira u bolnicama.
{7470}{7594}Pao je na dno. -To! Njega trebamo! -Pa|možemo mi i bolje od Sheldona Mopesa.
{7600}{7732}On ne donosi ništa novo. -Osim|etike. O njemu ne govore ništa.
{7736}{7846}Bezopasan je. -Nemoj...|-On je boèica sirupa s nogama.
{7851}{7899}Frank! -Dovedi mi Smoochyja!
{8078}{8146}Halo?-´Dan, ovdje Nora Wells...
{8151}{8264}Šalim se. Ostavite poruku|ili me doðite vidjeti na djelu.
{8268}{8392}U petak pjevam u klinici za|metadon. Vidimo se... Upamtite,
{8417}{8550}svijet promijeniti ne možete,|ali možete ostaviti trag. -Sigurno.
{8929}{9077}Hvala. Kad vas vidim, vrijeme|je da privedem program ka kraju.
{9090}{9173}Završit æu s poznatom pjesmicom.|Rijeèi su malo izmijenjene.
{9178}{9273}Ako ulovite refren, pridružite se.
{9416}{9480}Skinut æemo vas s heroina, o da
{9512}{9583}Skinut æemo vas s heroina, o da
{9607}{9708}Skinut æemo vas s heroina,|skinut vam s leða tog majmuna
{9712}{9783}i vratiti na put života, o da
{9870}{9920}Važno je poèeti. Znate zašto?
{9996}{10073}Heroin vodi do kokaina, o da
{10103}{10195}Carl, ti znaš o èemu|govorim. Pjevajte sa mnom!
{10244}{10311}Odustat æemo od heroina, o da
{10377}{10424}Bok, deèki. -G. Mopes?
{10461}{10547}Gledala sam vas|maloprije. Nadahnjujuæe.
{10565}{10659}Hvala. Ponekad pjevam duže, ali...
{10683}{10780}Kad lijek poène djelovati,|Connie Island postane spavaonica.
{10801}{10927}Ne slijede pjesmu. -Bar znate da je|to od heroina, a ne od vašeg pjevanja.
{10960}{11045}Da. Nadam se. -Možemo li razgovarati?
{11058}{11170}Nemam ništa protiv, ali struèni|vam savjetnici mogu pomoæi.
{11199}{11318}Došli ste vlakom H?|Malo heroina? Soka? -Ne!
{11346}{11433}Ali lijepo od vas što ste|to pomislili. Nora Wells.
{11447}{11539}Potpredsjednica razvoja|mreže Kidnet. -Radite za Kidnet?
{11545}{11649}Da. -Vi to ozbiljno? -Da, kao infarkt.
{11700}{11804}Drago mi je da nisam znao da|ste tu. Upropastio bih bio toèku.
{11826}{11920}Roðen sam 1 1 . studenog, 1970.|Znate što se još tada dogodilo? -Ne.
{11931}{11989}Prva emisija Ulice Sezam.
{11997}{12104}Namuèio sam se dok nisu|poèeli raditi hot dog od soje.
{12112}{12181}Zdravo... Ljudi, probudite se|i pomirišite buduænost. Jer...
{12196}{12308}Organskog je porijekla, ima dvostruko|bjelanèevina i nitko nije ubijen.
{12323}{12425}Znate veæ... Dat æu ja tebi s|onim pecivima bez glutena...
{12430}{12477}Promijenit æemo|svijet. -Dobro, Sheldone.
{12500}{12583}Kao što rekoh,|prijatelji mi uvijek kažu,
{12602}{12740}Ako se s takvim talentom ne|prodaš, uvijek æeš svirati zahvalnoj,
{12743}{12867}ali veoma limitiranoj publici.|Sirup s maslacem od badema?
{12879}{12954}Sigurno ne želiš?|-Vjerovao ili ne, ali ne.
{12969}{13071}Govorimo o zabavi djece.|Govorimo o dobrom djelu.
{13114}{13241}Integritetu. Dobar šou s|pozitivnom temeljnom porukom.
{13251}{13343}Ne možeš imati temelje bez betona.
{13365}{13449}Ovo je beton,|sestro! Ovo je integritet!
{13457}{13486}Vidim to.
{13599}{13695}Žao mi je. -Slušajte,|g. Mopes, razlog moje posjete...
{13706}{13853}Kidnettraži izvoðaèa s|uvjerenjima i integritetom.
{13873}{13963}Nekoga poput vas. -Samo trenutak.
{13973}{14091}Kažete da æe Kidnetnapokon|imati šou Smoochyjevog kalibra?
{14110}{14267}Obvezati se na kvalitetu Smoochyja?|-Da, spremni smo prijeæi na tu razinu.
{14427}{14470}Znao sam! Zna...
{14523}{14608}Znao sam. Ako budem strpljiv,
{14613}{14735}netko æe doæi jednog dana,|pogledati me i shvatiti što radim.
{14767}{14857}To ste vi. Shvaæate me.|-Bojim se da je tako.
{14882}{15011}Pa, Nora Wells, potpredsjednice|razvoja, poènimo pisati povijest.
{16097}{16122}Sviða mi se.
{16239}{16289}Vrijeme je za Smoochyja
{16442}{16535}Nemoj zaboraviti 50 $ za|ovaj vikend. -Bok, Angelo.
{16562}{16713}Obožavao sam Djecu Krinkle.|Drago mi je da æeš biti Nosorogiæ.
{16722}{16799}Posao je posao.|-Dobro, vidimo se na sceni.
{17071}{17183}Kamo iæi kad je sve sivo|Gdje je sunce i u igri sve živo
{17186}{17280}Gdje svaki je sretan dan|Smoochy put pokazat æe vam
{17397}{17530}Smoochyejava èarobna|džungla, sretno je mjesto
{18064}{18198}Veæ sam mislio da neæeš doæi.|-Pristao sam se naæi s tobom, zar ne?
{18204}{18337}Imao sam dogovor za veèeru. -Da? I ja|sam nekad. Èetiri ili pet na veèer.
{18348}{18385}Ne èini to, Randy, daj.
{18492}{18633}U restoranu bi me pozdravljali. Zahod|bi ispraznili kad bih išao pišati.
{18647}{18782}Znaš zašto, Frank? Zato što sam|jebeni Randolph Duga! Eto zašto!
{18793}{18822}Jesi li završio?
{18851}{18942}Što je? lmaš posla?|Nemaš vremena za mene?
{18960}{19071}Za tipa koji ti je zaradio lovu?|Za onog koji ti je kupio Armani odijela?
{19078}{19188}Za onog koji ti je stavio coq au vin u usta?|-Pomogli smo jedan drugomu.
{19191}{19314}Sve dok netko nije zafrknuo.|Tko? Jebeni Randolph Duga!
{19338}{19461}Zašto? Za lovu.|-Sredi ovo, Frank.
{19471}{19620}Vrati mi moj program. Ne mogu|gledati tog nosoroga dok mi krade šou.
{19630}{19753}Zaraðuje na meni.|Daj, Frank, dugo se znamo.
{19758}{19878}Ne mogu ti pomoæi. Izopæenik si.|Ne smijem biti viðen s tobom.
{19882}{19977}Ne èini mi to, Frank.|Utapam se. Propadam.
{19993}{20113}Izbacili su me iz stana. Beskuænik sam.|Stavi se u moje cipele.
{20136}{20276}Tvoje su cipele postale moje.|Sve dok nosorog šljaka, u redu je.
{20279}{20390}Nema postotka, ni prijevare. Htjeli su|nekog besprijekorno èistog. Eno im ga.
{20408}{20454}Mopes je sjajan.
{20516}{20544}Molim te?
{20589}{20712}Gotov si. nemaš više ništa.|-To ti i govorim, kompa.
{20917}{21047}Što je ovo? -Pokloni.|Kamere za jednokratnu upotrebu,
{21060}{21182}kikiriki s okusom Kahlue, losion za|ruke... Nije testiran na životinjama.
{21201}{21252}Ne zovi me više, Randy.
{21316}{21356}Izlazi.
{21421}{21481}Znaš što možeš s losionom|za ruke, drkadžijo.
{21568}{21698}Dobit æeš ti svoje! Nosorog|takoðer! Kolo sreæe se okreæe!
{21824}{21900}Èak se i besprijekorno|èisti mogu zaprljati.
{22010}{22137}Smoochy lutka i Nosorogiæi prodavat|æe se odvojeno. Ovo su prototipovi.
{22142}{22232}Rekli su mi da æe greške biti|ispravljene prije Božiæa. Dobro,
{22240}{22373}rekapitulirajmo. Da za|sladoled, da za niti od sira,
{22376}{22481}polako s kolom i èekamo što|æe biti sa šamponom! -Dobro.
{22505}{22611}Predah. Samo trenutak.|Smijem li nešto reæi?
{22617}{22754}Moramo preispitati principe.|Još pokušavamo... Smoochy...
{22764}{22915}...pokušava zadobiti povjerenje djece.|To neæe postiæi nitima od sira,
{22918}{23036}šamponom i kolom, koja,|dodao bih, sadrži èak dva aditiva.
{23057}{23158}Moramo se usredotoèiti|da emisija bude što bolja.
{23165}{23303}Da poruka bude pozitivna, ali bez svih|tih dodatnih stvari. Imam li amen?
{23310}{23346}Jeste li sa mnom?
{23461}{23487}Kvragu!
{23538}{23607}Ja æu ga donijeti. -Zatvori vrata.
{23703}{23837}Zakljuèaj. Hvala. Još razmatramo|da li æe Smoochy pahuljice
{23843}{23957}biti zašeæerene ili s okusom voæa|Prijedlozi? -Istraživanja pokazuju
{23961}{24090}da stariji vole zašeæerene, a mlaði|s okusom voæa. -Oboje? Dobro.
{24106}{24281}Volim zašeæerene. -I ja. -Kao mala|sam ih jela. Dobro, može onda tako...
{24309}{24414}Želio bih ti iskreno reæi da|sam osjetio... Hej, Nora! Èekaj!
{24450}{24560}Mislim da je sastanak bio|dobar. Dotakli smo važne stvari.
{24567}{24693}No mislim da se mene nije slušalo.|-To je konzervativna procjena.
{24700}{24808}Želim da šou ima težinu. Znaš|veæ. Blesave pjesmice, apsolutno,
{24811}{24962}ali s porukom. Znaš koliko|originalnih Smoochy pjesmica imam?
{24969}{25092}Primjeæuješ li moju indiferentnost?|-Više od 300. Od voæa u prehrani,
{25095}{25222}do važnosti doniranja plazme.|Vrijedan sam izvor. Iskoristi me.
{25228}{25304}Dobro, šuti. Reæi æu|ti ovo veoma jednostavno.
{25321}{25444}Jedini razlog što si na TV-u jest|zato što je Randolph Duga ološ.
{25462}{25551}Nisam te otkrila. Isporuèila|sam te. Kao namirnicu.
{25559}{25693}Uložila sam više emocija u nabavu|laka za nokte. I zato, ne trabunjaj.
{25702}{25829}Posao ti je da se smiješ i klimaš glavom.
{26211}{26325}Shvati, ne usporeðujem Kapetana|klokana s Isusom Kristom,
{26329}{26473}ali Kapetan je, kao i Krist,|netko u koga možeš vjerovati.
{26521}{26650}Ti ljudi nisu marili za slavu.|Zanimao ih je samo posao.
{26677}{26776}Posebno Isusa. Zaboravi.
{26783}{26893}Nisam znao da se možeš napiti|od juicea. -Imam malu tajnu.
{26900}{26991}Staviš malo tekuæe|alfalfe unutra i to je super.
{27039}{27107}Daj mi Five Crown.
{27186}{27287}Nosorog Smoochy? -Da, to sam|ja. -Tvoj sam veliki obožavatelj.
{27330}{27424}Kako ti se èini? Prvi me put|netko prepoznao bez kostima.
{27431}{27533}Burke Bennet. Agent za talente.|-Sheldon Mopes. Drago mi je.
{27541}{27699}I meni. Tako mreže rade. Stokes|mu je htio skinuti bodove od prodaje.
{27702}{27829}Rekao je da je skladište puno lutkica.|Frank i ja smo veæ dugo prijatelji.
{27834}{27934}Rekao sam mu, Dobro, kuronjo,|pokaži mi skladište. I da skratim,
{27940}{28050}ja sam odšetao s èekom na sto somova,|a Stokes je stavio prst u guzicu.
{28093}{28217}Super prièa, ali|meni nije stalo do toga.
{28245}{28379}Nije mi stalo do Smoochy lutkica,|èokolade... Jedino mi je stalo do toga
{28382}{28512}da šou bude kreativan. Taj|je nosorog izašao iz moje utrobe.
{28537}{28663}Ja sam ga rodio i brinuo se o njemu.|Ja sam taj koji bi ga trebao odgojiti.
{28677}{28768}Sve je u lovi. S novcem imaš moæ.
{28775}{28897}A kad imaš moæ, Smoochy može šetati|s vibratorom na glavi, ako tako želiš.
{28959}{29068}Nisam baš na to mislio,|ali shvaæam što želiš reæi.
{29081}{29178}Kad budeš spreman razgovarati,|pomoæi æu ti. Otvorit æu ti vrata.
{29347}{29408}Kako vam se ovo èini?
{29447}{29611}Obavljeno. On je rogata banka. Zaradit|æeš 20 puta više nego s Randolphom.
{29621}{29740}Važno je za Paradu nade. -Sreðeno|je. Možda æe ga trebati malo masirati.
{29745}{29813}Nemoj da izgubim|osmijeh, Burkey, mali.
{30016}{30088}Posebna vrsta keksa|za posebnog nosoroga.
{30119}{30208}Baš sam pametan. Prekrasni su.
{30235}{30344}Uèit æeš o sramoti, dragi|Smoochy, a ja æu biti tvoj uèitelj.
{30560}{30588}Možemo razgovarati?
{30609}{30689}Zašto je pjesma Molim i hvala|izbaèena? -Zbog Pjesme o keksima.
{30693}{30802}Ona je podiže. Pjesma o keksima|nema smisla bez pjesma Molim i hvala.
{30807}{30930}To je lekcija. Moralno sidro.|-Izbaèena je i promijeni rijeèi.
{30936}{31080}Neæu nagovarati djecu da jedu šeæer.|Žao mi je, moram živjeti sa sobom.
{31085}{31201}Ovo je TV mreža, a ne farma.|Ti prodaješ šeæer i plastiku.
{31206}{31322}Èuješ li se? -Da. -Neæu to uèiniti.|Piše li ovdje Norina èarobna džungla?
{31326}{31423}Ne. Ne govori sa mnom tako.|Nisam tvoja lutka. -Otkad?
{31428}{31515}Gubi se s tom spužvastom roza|guzicom i pleši pred kamerama.
{31681}{31775}Ovo je emisija za|djecu. Ja pjevam djeci.
{31780}{31907}Ti više i ne vidiš djecu.|Vidiš samo novèanike s kikicama.
{32545}{32640}Dobra veèer, Smoochy. Dobro|došao u zemlju Fattyja Arbucklea.
{32938}{33029}Ne brinite se, maleni.|Randolph Duga æe se vratiti.
{33385}{33521}To! Da vam kažem... Od|ovog sam plesa zaista ogladnio.
{33526}{33667}A kad sam gladan, znate koliko je|sati? -Vrijeme je za Carobne kekse!
{33683}{33780}Molim? -Vrijeme je za Èarobne kekse!
{33795}{33893}Tako je! Svi u sredinu! Svi u sredinu!
{33991}{34036}Angelo, nabaci!
{35038}{35078}Daj im keks. Daj im keks.
{35126}{35217}Eksa, peksa, teksa,|evo nama keksa.
{35235}{35342}Svjež i organski, nema mjesta|panici... -Nije promijenio rijeèi.
{35366}{35460}Ravno iz zemlje|Pazili smo na ulje
{35473}{35581}Zaslaðen voænim sokom|Energiju æemo dobiti skokom
{35626}{35675}Što god ti kažeš, jebena seljaèino.
{35717}{35821}Tko želi prvi kolaè? Da|vidimo što imamo ovdje danas!
{35859}{35895}Daj im keks. Daj im ga.
{36164}{36192}Opaca...
{36473}{36498}To je...
{36545}{36570}To je...
{36582}{36607}To je...
{36623}{36648}To je...
{36712}{36864}To je raketa! Da! Raketa|za Zemlju džungle! Idemo!
{36885}{37010}Jebiga! -Za mnom. Letimo|iznad stabala u èarobnoj raketi.
{37053}{37157}Kakav poseban dan. Zaista|je poseban... -Zar si slijep?
{37164}{37250}To je kurac. Nije raketa,|glupane bolesni. Pogledaj.
{37255}{37360}Randolphe! -To je|kurac. Evo i jaja. Pimpek.
{37376}{37497}Kobasica s jajima. Tvrdi|pimpek. Da. To je penis!
{37514}{37624}Penis maksimus! Kobasa! Pimpaè!|G. Visuljak! -Vodite ga odavde!
{37638}{37776}Jednooka zmijica! Jimmy i blizanci!|lvica i kožica! To je on uèinio!
{37807}{37933}Od vibrator tijesta!|-Mahnite gospodinu! Pa-pa!
{37971}{38009}Puštajte me!
{38031}{38089}Ja sam jebeni Randolph|Duga. Znam put van....
{38537}{38664}Zahvaljujem vam na ovom sastanku.|Ima par stvari koje moramo izgladiti.
{38668}{38798}Suradnja i komunikacija ne|šljakaju. Nisam uperio prst na nikoga.
{38804}{38935}Èim u nekoga uperiš prst, nekoga|izbodu. Ne želim da vi budete...
{38943}{38980}...izbodeni.
{39060}{39205}Svejedno. Ovo je moj novi menadžer,|Burke Bennett. Ima mnogo iskustva.
{39209}{39337}Mislim da nam može|pomoæi. Evo Burkea!
{39385}{39501}Hvala, Sheldone. Frank, vidiš|ovog tipa? Dobro ga pogledaj.
{39509}{39650}On ti je spasio guzicu. Bez|njega, sad bi sjedio u birtiji
{39653}{39827}i pio na slamèicu, dok bi za tvojim|stolom sjedili novi Frank Stokes
{39831}{39949}i njegova picica. Isprièavam|se, zlato. -Ti to ne znaš.
{39957}{40073}Uvijek smo se mogli dogovoriti. Èemu|vatromet? -Zato što je barut kod mene.
{40076}{40211}Predstavljam èovjeka koji je stvorio,|posjeduje i kontrolira Smoochyja.
{40221}{40328}Èini se da si zaboravio da smo|ga mi pronašli, iskopali truplo
{40331}{40459}i dali mu šou kad se nije mogao|nigdje prodati. -To nije posve toèno.
{40464}{40591}Mnogi su me u onoj klinici gledali.|-Dopusti da prekinem ovu mrežu.
{40596}{40715}Briga me ako je dosad žonglirao|jabukama za pigmejce u Kongu.
{40725}{40801}Tip je pravi i trebate ga.
{40823}{40917}I zato æe nosorog dobiti ono|što zaslužuje. -A što je to toèno?
{40982}{41111}Zvijezdi i izvršnom producentu|Smoochy šoua. -Još sam u šoku.
{41147}{41247}Ne mogu vjerovati. Ponovi mi još|jednom. Imam potpunu kontrolu. -Da.
{41267}{41376}Veto na trgovinu.|Stan od firme. -Super.
{41397}{41535}Sigurno sanjam. -Ovo je pravi|život, Shel. Moraš se naviæi.
{41543}{41654}Uskoro æeš pišati na novèanice od|100 $ samo da vidiš Franklinovu facu.
{41677}{41773}Ne bih to nikad mogao.|Previše ga poštujem.
{41809}{41940}Da, dobar je. -Što je to? -Tiho, tiho.
{41953}{42041}Što si to uèinio, zmijo?|-Mali poklon za diplomu.
{42100}{42171}Smatraj to alatom zanata.
{42200}{42328}Ne mogu to prihvatiti. -Ne? -Nikad|nisam imao pištolj. Ne vjerujem u to.
{42335}{42472}Zaista? -U igri kauboja i indijanaca,|uvijek sam bio radnik na željeznici.
{42476}{42574}Vjeruj mi. Koristi|u ovom poslu.
{42674}{42808}Ajoj. Ne govori s ovim tipom|ili æe ostati s nama cijelu noæ.
{42827}{42926}Super. -To je Spinner|Dunn? Boksaè? -Sprženi grah.
{42933}{43047}Ne postaje se guverner s|rekordom od 89 meèeva i 51 poraz.
{43053}{43192}Vodi ovo mjesto. Sigurno je pametan.|-On? Ni slavinu ne bi mogao otvoriti.
{43196}{43363}On je maskota. Tommy Cotter|i njezini deèki vode ovo mjesto.
{43367}{43435}Irska mafija. -Kako ti se to èini?
{43447}{43492}Jagode i...
{43576}{43607}Evo ga.
{43692}{43830}Smoochy! Ja sam Spinner!|O, tako mi je drago!
{43841}{43941}I meni, Spinner! -Ja sam Spinner!
{44010}{44197}Jedan od obožavatelja|si? -Volim onaj tvoj ples.
{44251}{44342}Onaj za vrijeme Ludog|vremena? -To je najvažnija toèka.
{44405}{44503}Hoæeš me vidjeti?|-Što? Ti æeš plesati?
{44529}{44602}Jednog dana... -Ne, sad æu ja to...
{44854}{44912}Isprièavam se, senatore. -Naravno.
{44935}{45042}Puno te volim. -I ja tebe,|Spinner. -Ja sam Spinner.
{45053}{45156}Da. -Spinner, doði|i upoznaj senatora.
{45168}{45309}Samo hajde. -Smoochy|je tu. -Baš mi je drago.
{45378}{45471}Kad moji èuju da sam upoznao|Dunna. -Jednog i jedinstvenog.
{45478}{45643}Baš je dobar. -Nemoj otiæi Smoochy.|Odmah se vraæam. Idem se posrati.
{45671}{45742}Mislim da imaš novog prijatelja, mali.
{45776}{45899}Otkad nema Randolpha, imamo|zrak u cijevima. Kad æe poteæi voda?
{45906}{46017}Nosorog je još zelen,|ali s vremenom æe shvatiti.
{46035}{46183}Mora se naviknuti. -Nemam vremena|za vrijeme. Svi starimo i umiremo.
{46196}{46353}Samo se ponekad ne stigne ostariti.|-Dajem sve od sebe. Pod nadzorom sam.
{46359}{46491}Imaš problem. Neka nosorog|nauèi igrati i to što prije.
{46499}{46578}Ili æe mu biti potreban mali trening.
{46618}{46731}Obriši èelo, Frank. Imat|æeš vremena znojiti se.
{47072}{47176}Tko je? -Otvori, zlato. Randolph|je. Prošlo je mnogo vremena.
{47314}{47435}Randy? -Angie, jebeni izdajnièe.|Brzo si poèeo raditi za nosoroga.
{47439}{47587}Moram jesti. -Brzo si navukao rog.|Ti si Krinkle dijete. Ponovi za mnom.
{47594}{47704}Nosorogiæ. -Ponovi. Pred|Bogom i kostima svetaca!
{47772}{47860}Ja sam Nosorogiæ, kužiš?|Djeca Krinkle su pokopana.
{47881}{48011}Zajedno s tobom. -Toliko si mi|nedostajao. Mogu li ostati ovdje?
{48029}{48077}Nemam kamo.
{48164}{48270}Izbacili su me iz stana. Gadovi.|Tako sam zaradio ovu ljepoticu.
{48293}{48412}Imam poreze, raèune, odvjetnike,|prijetnje. Svi su protiv mene.
{48417}{48567}No, ne brini se, dugo pamtim.
{48607}{48716}Ono što su posijali|to æe i požnjeti, Angie!
{48869}{49037}Prestani. Ne odbacuj ovako život.|-Svemu je kriv taj nosorog, Angie.
{49044}{49129}Sam vrag ga je poslao da me uništi.
{49141}{49219}Smoochy je lice zla.
{49668}{49758}Obraèun kod Smoochyja|Mopes je izvršni producent
{49787}{49887}Èestitam, Sheldone.|-Èestitke, g. Mopes. -Hvala.
{49900}{50054}Dopustite meni, g. Mopes.|Zatrebate li štogod, pozovite me.
{50070}{50197}Hvala, Natasha. -Ne, moram|raditi. Doæi æu u nedjelju.
{50219}{50307}Dobro, to je... -Možemo|li razgovarati na trenutak?
{50343}{50454}Mogu te nazvati poslije, mama?|Treba me neki peder. Hvala. Bok.
{50510}{50626}Nisi morala zbog mene prekinuti.|-Inaèe bi još tu stajao. -Još sam tu.
{50633}{50739}Nadam se da æu to uskoro|ispraviti. -Slušaj, Nora...
{50769}{50933}Shvaæam da se osjeæaš èudno, èak|i pod prijetnjom, zbog promjena,
{50940}{51067}ali još uvijek si vrijedna suradnica.|Smatram te partnericom.
{51073}{51183}Da živim još tisuæu godina i doživim|drugog Krista, ne bismo bili partneri.
{51190}{51301}Znam da još nismo partneri.|Zato to i govorim. Osmislimo plan.
{51311}{51454}Dogovorimo par ruèkova. Idemo|na osamu. Ti i ja, sami, zajedno.
{51459}{51576}Kolege koji žvaèu probleme.|Posadimo sjeme stvarne suradnje.
{51583}{51627}Posadi ti ovo!
{51681}{51717}Znaš, Nora...
{51728}{51864}Jesu li ti rekli da te joga ili|dobra probava uspješno opuštaju?
{51868}{51909}Van.
{51912}{52045}Ti izaði! Više neæeš govoriti|ovom deèku što da radi, ti živèana...
{52181}{52334}Sad æu stati. Znaš tu tehniku?|Gladan, ljut, sam i umoran.
{52341}{52468}To si ti. Neæeš me uvuæi u svoju|negativnu energiju. Bit æu u uredu.
{52481}{52587}To je onaj veliki s pogledom.|-Svi imaju pogled, glupane idiotski!
{52590}{52654}Ali ne prema ovamo!|-Ne zatvaraj mi vrata!
{52883}{52941}Trèi dugo i zdravo. Burke.
{52965}{53085}Moj vlastiti busen trave.|-´Jutro. Èestitam na fotelji.
{53094}{53257}Svidio si se Spinneru. Od|onog dana nije prestao trabunjati.
{53262}{53340}Smoochy ovo, Smoochy ono. -Baš|lijepo. Drag je za nekog tko je...
{53401}{53527}...tako velik. -Možeš li|mu dati mjesto u emisiji?
{53539}{53683}Mjesto? -Da. U emisiji. Izvršni|si producent. Ti odluèuješ, zar ne?
{53719}{53861}Da, tako je, ali televizija|je veoma kompliciran medij.
{53867}{53995}Ne može svatko uspjeti. Spinner|mi se sviða, ali njegove su šanse
{53998}{54136}iste koliko i moje u|ringu. Znate što želim reæi?
{54168}{54342}To bi bilo bolno. -Što je,|Tommy? -Ništa, samo...
{54361}{54449}Samo sam tužna. -Tko te|rastužio? -Ne želim spominjati imena.
{54561}{54669}Baš sam se sjetio. Imamo|savršenu ulogu za Spinnera.
{54696}{54870}Imam rješenje. -Dobar si, Mopes. Mi to|ne zaboravljamo. Svrati kad zaželiš.
{54875}{54990}Idemo, deèki. -Dobro,|hvala vam što ste svratili.
{55088}{55208}Halo? -Pazi leða,|seronjo. Neæu spavati mirno
{55212}{55346}sve dok crvi ne budu plazili|po tebi. Idem na safari! Safari!
{55428}{55478}Isuse, kakav dan!
{55491}{55542}Kucaš li ti ikada?
{55550}{55645}Èestitam na predstavi na ledu. -Molim?|-Nije ti dugo trebalo da se prodaš.
{55650}{55771}O èemu govoriš? -O tebi i o|tomu kako si isti kao i ostali.
{55789}{55905}Ja sam Smoochy. Baš me|briga za novac i slavu i sve to.
{55918}{56061}Nastavi. Dobro izgledaš kad|si takva. Samo nastavi tako.
{56096}{56215}Gdje ti je taj integritet?|lli je i to dio šoua?
{56314}{56376}Smoochy na ledu u Broadway Colliseumu
{56417}{56554}Nikad nisam pristao na ovo.|-Znaš li koliko možemo zaraditi?
{56559}{56682}Baš me briga. To je sve ono|protiv èega sam. Glupi spektakli
{56685}{56796}gdje se prodaje precijenjena|ušeæerena voda i plastiène igraèke
{56801}{56995}koje završe u djeèjem grlu. Gdje je|dignitet? -Znam da ti je etika fetiš.
{57000}{57124}Nije vrijeme. Ne možeš promijeniti|svijet. -Ne, ali možeš ostaviti trag.
{57129}{57289}Nitko nikada nije odbio šou na ledu.|-Dosad. Smoochy se ne prodaje i gotovo!
{57293}{57395}Trebao bi se ponositi ovakvim|klijentom. -Da, skaèem od sreæe.
{58009}{58118}Nije li ovo bilo zabavno|na jedan èudan naèin? -Da!
{58138}{58178}Naravno da jest!
{58232}{58334}Jesam li bio dobar?|-Bio si izvrstan, kompa.
{58353}{58429}Idem se napiti sad. -Èuvaj se.
{58443}{58514}Zdravo, damo. -Izvrsno obavljen posao.
{58517}{58640}Uzimaš luðake. Super.|-Prestani. On nije luðak.
{58657}{58817}Ima noæni klub i ambasador je|svog sporta. S pameæu 5-godišnjaka.
{58839}{58949}I roðakinjom po imenu Tommy|Cotter. -Bar ima smisla za humor!
{58988}{59048}Znatno više od nekih drugih.
{59186}{59219}Što je?
{59396}{59473}Zdravo. -Kako ste? -Ulazi!
{59512}{59650}Nema veze. Prièekat æu|taksi. -Udovolji mi, nosorože.
{59684}{59726}Kako ti se to èini?
{59816}{59930}Merve Green, drago mi je.|-Jesi li pokušao ovo bez pištolja?
{59939}{60088}Predstavljam Paradu nade. Poznato?|-Prikupljate novac za djeèje bolnice.
{60093}{60247}Pomogli smo malo. Prijeðimo na stvar.|Èujem da odustaješ od šoua na ledu?
{60252}{60393}Istina? -Nije. Nisam|ni pristao na šou na ledu.
{60397}{60498}I nikad ne bih. Smijem|li pitati, što se to vas tièe?
{60505}{60660}Sponzoriramo sve predstave na ledu|od 1964. Zaradimo malo i svi sretni.
{60670}{60816}Nemojmo pokvariti povijest. -Po|stoti put. Ne radim predstave na ledu.
{60820}{60949}Nikad! Ako je to sve, pustite me van.|Možete me izbaciti na sljedeæem uglu?
{60964}{61134}Od sutra, Smoochy radi za Paradu nade.|Banketi, dobrotvorne priredbe, sve.
{61179}{61230}Možeš stati, Jimmy.
{61305}{61404}A što se tièe predstave|na ledu, kupi sklizaljke.
{61543}{61689}Nedopustivo. Zvat æu vlasti.|-Nemoj. Zafrkni Paradu nade
{61692}{61801}i s malo sreæe, znat æeš gdje|su ti nokti. Oni su najgori.
{61806}{61961}Nisi èuo. Prijetila mi je organizacija|koja navodno pomaže djeci.
{61966}{62115}U kakvom to svijetu živimo? -Stvarnom.|Razmotri to s ledom i ostani živ.
{62166}{62210}Kako vam se ovo èini?
{62276}{62389}Bok. -Što sam sad uèinio?|-Smijem uæi. -Naravno.
{62427}{62491}Je li sve u redu? -Pijana sam.
{62541}{62654}Ne želim te ogaditi, ali s|alkoholom unosiš i kalorije.
{62666}{62792}Došla sam se isprièati. -Zaista?|-Da. U tim rijetkim situacijama,
{62796}{62907}kad imam potrebu da se nekomu|isprièam, pomaže ako sam pijana.
{62939}{63072}Trebam li biti poèašæen? -Možda sam|bila malo stroga s tobom. Nepravedna.
{63090}{63207}Nema problema. Prošli tjedan si rekla|da sam kostimirani idiot bez talenta.
{63214}{63332}Èujem da ne radiš šou na ledu? -Ne,|pogotovu sad kad znam o èemu je rijeè.
{63337}{63431}Zašto nisi rekao? -Nisam|ti htio pokvariti zabavu.
{63445}{63577}Sva zasvijetliš kad|me gadiš pred drugima.
{63604}{63685}Možda sam malo otvrdnula|tijekom godina. -Da.
{63691}{63793}Iskrenost je laka krinka. Teško|je znati tko je na kojoj razini.
{63837}{63942}To je istina. I sam sam to|vidio u posljednje vrijeme.
{64011}{64127}Ponekad svjetlo poput mraka je|Ponekad vrana pjeva poput ševe
{64132}{64231}Ponekad zima poput proljeæa je|Nemoj misliti da znadeš sve
{64239}{64386}Vodenkonj Rickets. -Znaš ga?|-Jedino sam njemu vjerovala kao mala.
{64393}{64487}Zbog njega radim na|televiziji. -I ja. -Ne. -Da.
{64500}{64643}Na predavanju o bijesu morali smo|navesti nekoga za ljubav i strpljenje.
{64647}{64759}Ja sam naveo njega. Zbog njega sam|smislio Smoochyja. -Ne mogu vjerovati.
{64768}{64887}Ni ja. -Kad drugima prièam|o njemu, misle da sam luda.
{64893}{65036}Ma daj! Najbolji je. Sjeæaš se|klunky-wunkyja?-Molim? Èinila sam to.
{65039}{65152}Na prièesti. -Ma da. Ti? I sve ono...
{65293}{65334}Od mene, tebi.
{65566}{65691}Moram iæi. -Ne, ostani malo.|Imam Ricketsa snimljenog na vrpci.
{65695}{65787}Kasno. -Sigurno? Mogli|bismo popiti èaj i razgovarati.
{65791}{65857}Bolje se javi. Bok. -Nema veze...
{65909}{65952}Vidimo se na poslu.
{66041}{66157}Halo? -G. Mopes? Ja sam|Benjamin McKnuckelpeck.
{66160}{66278}Iz udrugeRoditelji za pristojnost|na TV-u. Culi ste za nas? -Nisam.
{66283}{66391}Ali sviða mi se to za što se|zalažete. Baš sam razgovarao...
{66400}{66576}Sutra imamo banket. Voljeli bismo kad|biste došli. Imamo i nagradu za vas.
{66580}{66727}Za doprinos djeèjoj televiziji.|Voditelj je siroèe s astmom.
{66734}{66830}Hoæete li doæi? -Sa|zadovoljstvom. -Izvrsno.
{66868}{66957}Hvala vam što ste došli po mene.|-Nema problema, g. Mopes,
{66959}{67103}za Smoochyja bih stavio|pišu u košnicu kad bih morao.
{67132}{67250}To je malo radikalno. Pokušajte|me zamoliti. -Baš ste duhoviti.
{67259}{67335}Imate votke i krumpiriæa|ondje pozadi. -Ne znam znate li,
{67343}{67429}ali takva vam hrana može|poprilièno smanjiti vaš chi.
{67435}{67516}Nisam još kušao korejsku|hranu, ali hvala na informaciji.
{67538}{67670}Zato maleni vole vaš šou. Mogu|se smijati i uèiti istovremeno.
{67688}{67828}Lijepa promjena nakon|onog prevaranta Duge Randyja...
{67832}{67953}Kako se ono zvao? -Randolph,|mislim. -Da, Randolph. Hulja.
{67960}{68112}Vjerojatno je i homiæ. -Molim?|-Grize jastuk, znate? Stari...
{68126}{68256}Ne znam za njegov poremeæaj|sna, ali sigurno ima problema.
{68269}{68388}Alkohol i bijes su samo neki.|-Kako to mislite? - Žalim ga.
{68392}{68524}Ima problema. -Slažem se,|ali ne osjeæate li posebnu radost
{68527}{68636}to što ste mu oteli program|i prekrili njegovo truplo zemljom?
{68643}{68753}Ne, nikad ne bi osjeæao radost zbog|tuðe nesreæe. Ako baš želite znati,
{68758}{68906}mislim da je zaista talentiran. -Pušaè|je i pederèina! Mrzite ga! Priznajte!
{68975}{69050}Odakle ste vi ono, g. McKnuckelpeck?
{69313}{69450}Maleni su spremni za vas. -I ja|sam spreman. Idemo! Moju sjekiru!
{69468}{69562}Idemo! Prodrmajmo ih!|-Ovo je zaista uzbudljivo.
{69592}{69714}Još nisam svirao u skladištu rezervnih|dijelova. -Nije bitno mjesto.
{69720}{69835}Bitni su maleni. -Izvrstan|stav. Da bar više ljudi tako misli.
{69841}{69958}Znate moj moto? Svijet promijeniti|ne možeš, ali možeš ostaviti trag.
{69974}{70070}Ne brinite se. Trag|æete sigurno ostaviti.
{70074}{70125}Izaðite i pokažite im rog! -Dobro.
{70131}{70229}Evo nosoroga Smoochyja!
{70232}{70274}Zdravo, New Jersey!
{70367}{70489}Izvrsno je biti ovdje,|djeco. Slijedite, ako znate rijeèi.
{70503}{70593}Prijatelji, svi ih imamo|Ti imaš mene i tebe imam ja
{70612}{70710}Prijatelji, svi ih trebamo|Oni nam pomažu u nevoljama
{70731}{70827}Da imam dolara za|svakog prijatelja svog...
{70931}{71073}Znate, teško je pjevati|prijateljima kad ih ne vidite.
{71119}{71196}Možemo li ugasiti|reflektor i upaliti svjetla?
{71422}{71471}Heil, Smoochy!
{71725}{71767}Nadam se da sanjam.
{71866}{71982}Ovo je nezakonito okupljanje!|Stavite ruke na glavu i stanite u red!
{72151}{72268}Èitao Mein Kampf? -Smoochy voli|bijelu moæ? -Hitler ti je prijatelj?
{72275}{72435}Nikoga ne mrzim! -Ni naciste?|-Kako se osjeæaš, prljava huljo?
{72563}{72679}Smoochy uhiæen na okupu nacista
{73085}{73168}Ovdje u Kidnet džungli,|nosorog je izumro.
{73176}{73294}Zamijenit æe ga reprize crtiæa.
{73704}{73783}Zdravo žvakaèu|bradavice. Nosorog je nacista.
{73843}{73900}Nosorog je sjeban|Sjeban je on
{74485}{74594}Nora. Ja sam. Moramo razgovarati.
{74604}{74746}Nemam ti što reæi. -Što? Zar ne|vidiš da me usporeðuju s Goebbelsom?
{74759}{74889}Ako ti to pristaje...|-Neæeš valjda reæi da im vjeruješ?
{74904}{74990}Ne moram. Slika u novinama|govori sama za sebe. -Smjestili su mi.
{74997}{75137}Taj tip mi je rekao da je|to za djecu! To sam mislio!
{75150}{75275}Nisam znao da je to okupljanje|nacista. -A 20 metarska Svastika?
{75296}{75453}To je bilo kasnije. Imao sam reflektor|u oèima. To je bila noæna mora.
{75464}{75571}I odjednom... Èizme, Gestapo|i Smooch Heil, Smooch Heil.
{75582}{75731}Trebam tvoju pomoæ. U nevolji sam.|-Istina je da te zapravo ne poznajem.
{75737}{75884}Molim? -Tako je. Ne oèekuj|da reagiram s emocijama.
{75909}{75938}Ali, Nora...
{76016}{76141}A klunky-wunky ples?|-Bila sam pijana. Zaboravi to.
{76532}{76598}Smoochy je nacist
{77052}{77132}Klinika na Connie Islandu|zatvorena zbog nedostatka novca
{77428}{77535}Ako tražiš malo soka,|bunar je presušio. Zatvorili su je.
{77545}{77642}Gadovi æe staviti|nove sise Kipu slobode,
{77647}{77787}ali ne žele pomoæi narkomanima.|Da mi je bar jednom imati vlast.
{77793}{77880}Sredio bih stvari u|ovom gradu. Vjeruj mi.
{77966}{78009}Baš super svijet.
{78105}{78138}Baš super svijet.
{78553}{78679}Što hoæeš? -Možeš dati 60 sekunda|nasmijanom licu iz prošlosti?
{78747}{78786}Zdravo, maèkice.
{78862}{78987}Evo vijesti. Znam da ste ti i Frank|u nevolji. Rado æu prekinuti odmor
{78990}{79116}i vratiti se u program. Mogu|poèeti u ponedjeljak. Nema mesa.
{79123}{79274}Otkad si vegetarijanka? Nazovi|garderobu i reci im da se R-man vraæa.
{79279}{79415}Spreman da zasvira maloj djeèici.|Komu moram popušiti za jedno piæe?
{79419}{79547}Imaš tri sekunde da odeš|odavde! -Daj, molim te!
{79553}{79668}Trebaš nekoga i tu sam da tražim|ono što je moje. -Ako si zaboravio,
{79672}{79814}zloèinac si i hulja. -Ne osjeæaš više|ništa prema meni? A ono što smo imali?
{79817}{79935}To je bilo davno. Bila|sam mlada i glupa. -I gipka.
{79938}{80041}Zašto smo samo prekinuli?|-Bio si pederèina i nisam to voljela.
{80044}{80093}To smo mogli srediti.
{80131}{80280}Pobogu, publika me želi. Znaš to.|Ja sam patriot u poreðenju s Mopesom.
{80285}{80386}On je nacista i peder. Da si samo|vidjela kako me gledao u automobilu.
{80445}{80565}Što to znaèi? -Koje? -Rekao si|da te gledao. U kojem automobilu?
{80572}{80702}Ne, to je samo osjeæaj. Nekakav|nacistièko pederski osjeæaj.
{80720}{80825}Vidi se na TV-u. Kakav je to|kostim? Taj uzdignuti rog...
{80828}{80949}Govoriš jako brzo. -Kako to misliš?|Nije istina. Još te volim, Nora.
{80954}{81041}I ti si bio na tom okupljanju? Ha?
{81077}{81228}Reci, ti si imao veze s|time? Ti si smjestio Sheldonu?
{81245}{81369}Ti si smjestio... Sad znam zašto|smo prekinuli. Uvijek me optužuješ.
{81372}{81406}Kuèko, kuèko, kuèko...
{81471}{81613}Nedostaje mi Smoochy.|Nije on uèinio to što kažu.
{81622}{81743}Nije on nacist. Hoæu|da se Smoochy vrati.
{81760}{81861}Želim biti na televiziji opet.|Želim udarati u zvono.
{81902}{82033}Je li Burke bio tu? -Nisam ga vidjela.|-Moram razgovarati s njim o Sheldonu.
{82052}{82140}O Sheldonu? Što je sa Sheldonom?
{82223}{82334}Pokušavam spavati, pederèino!|Doði oèitati mjerilo neki drugi put!
{82412}{82545}´Dan, g. Dugo. Baš vas je|lijepo vidjeti u živo. Dolazi!
{82575}{82682}Hoæeš razgovarati o nosorogu?|-Upali ste na privatni posjed.
{82750}{82823}Danny, poèeši g. Smješka po leðima.
{82924}{83046}Poèni s prièom. -Ništa|ja ne znam. Upali ste u moju...
{83271}{83418}Dobro, guzice jedne. Tužit æu vaše|irske guzice! Poslat æu vas doma!
{83446}{83543}Roy, imaš èekiæ tu?|-Uvijek ga nosim sa sobom.
{83596}{83731}Ja sam to uèinio. Kriv sam. Hvala|Bogu da smo to riješili bez nasilja.
{83793}{83843}Duga smjestio Smoochyju
{83962}{84075}Ne dirajte me! Ne zovem|se Wandolph, veæ Randolph!
{84093}{84183}Kako je biti najnepopularnija osoba|Amerike? -U zemlji Neandertalaca,
{84188}{84300}to je prava èast. -Nora kaže|da si opsjednut Mopesom.
{84309}{84458}Jedva znam kuèku. Sjela je|na sve. Širi se kao topljeni sir.
{84465}{84547}A glasine da ste|ludi? -Tko je to rekao?
{84625}{84792}Pusti mene. Moj klijent je upao|u tešku psihotiènu depresiju.
{84804}{84933}Tko me uhvatio za guzicu? Dalje|od mene! Ne dirajte me! -Jako lijepo!
{84947}{85041}Nastrijelili su me! To je salmonela!|Odvjetnik si, ovo je salmonela!
{85050}{85120}Netko me uhvatio za|guzicu! Trebam zraka!
{85224}{85278}Žao nam je, Smoochy
{85335}{85476} Vani je ludo. -Da?|-Cuj, htjela sam se isprièati.
{85501}{85620}Žao mi je što ti nisam vjerovala.|Pala sam anti-Smoochyizam.
{85627}{85738}Nema problema. To je kuæa|zrcala. Nikad ne znaš što gledaš.
{85760}{85846}Da. -Osim toga, da nije bilo|tebe, ne bih sada bio ovdje.
{85879}{85935}Hvala.|-Dobro.
{85972}{86098}Pet minuta. -Hvala. -Merde.|-Ne govorim španjolski, ali hvala.
{86128}{86161}To znaèi sretno.
{86307}{86452}Dame i gospodo, djevojèice i|djeèaci, tko je vaš omiljeni nosorog?
{86714}{86745}Smoochy!
{86968}{87009}Najbolji ste!
{87076}{87176}Hvala, djeco, hvala vam.|Lijepo je biti kod kuæe.
{87190}{87322}Znam da me dugo nije bilo.|I znam da znate da mi nije bilo lako.
{87327}{87448}Život izvan Èarobne džungle|može biti veoma kompliciran.
{87461}{87618}Puno je neugodnosti i nepravde.|Ponekad biti dobra osoba znaèi...
{87645}{87753}Ponekad to nije dovoljno|i kad se dogodi, frustrirajuæe je.
{87787}{87853}Osjetiš èak i malo gorèine.
{87902}{88038}Reæi æu vam, ponekad|se jednostavno naljutite.
{88059}{88237}Znate što ja èinim kad sam ljut|i kad mi nešto pritišæe srce?
{88243}{88351}I kad osjeæam da više ne mogu?|I kad kažem da bi ovaj nosorog
{88354}{88455}mogao ozlijediti nekoga?|Znate li što tada èinim?
{88494}{88612}Urlièem! Tako je. Uzmem|sve ono što ne volim o svijetu
{88617}{88669}i zaurlam!
{88833}{88877}Hajde, urlajte sa mnom!
{88993}{89132}Urlajte! Uzmite|frustraciju, skupite je u loptu
{89138}{89197}i ispustite je u urliku!
{89895}{89983}Hvala vam, djeco.|Sad mi je mnogo bolje.
{90017}{90076}Onda, tko hoæe plesati?
{90354}{90467}Smoochy se vratio. Baš|nam je nedostajao. -Zašuti!
{90485}{90558}Loše. Veoma loše.
{90656}{90706}Previše za mozak. Pritisak raste.
{90778}{90836}Šuti! Prezirem te!
{90868}{90917}Mrzim te!
{90992}{91031}Kopile jedno!
{91092}{91215}Umri, pahuljo jedna!|Nezakoniti Teletubbysu!
{91232}{91350}Umri, lutko iz pakla!|Umri, pederèino spužvasta!
{91382}{91501}Što radiš? lmao je sliku|u slici. -Bilo je sluèajno.
{91505}{91597}Želim da odeš! -Ne, Angelo...|Kamo æu? -Baš me briga!
{91605}{91722}Van! -Zar ne vidiš da|trebam pomoæ? -Briga me!
{91728}{91806}Angelo, molim te. -Pomogao|sam ti, ali ovo je previše.
{91879}{91965}Toliko si mi nedostajao.|-I ti meni. -Pogledaj...
{91979}{92080}Vježbao sam. Sad sam zaista dobar.
{92098}{92163}Hoæeš vidjeti kako marširam?|-Ne, ali svejedno æeš to uèiniti.
{92257}{92287}Moraš ga voljeti.
{92354}{92492}Prvo, dobre vijesti. Odluèio|sam napraviti šou na ledu.
{92564}{92695}To je moj bar mitzvah deèko.|Bravo. -Ne, ali nakon svega,
{92699}{92825}šteta je protratiti moæ, ako je imaš.|-To je fakultetsko obrazovanje.
{92833}{92966}Jesi spreman za još bolje vijesti?|Sam æu sve uèiniti. Bez sponzora.
{92973}{93061}Bez trgovaca i lopova.|Nitko neæe zaraditi ni novèiæa
{93067}{93214}na toj djeci. Smoochy na|ledu bit æe besprijekorno èist.
{93232}{93378}Nisam završio. Sokove æu|nabaviti ja i dijelit æu ih besplatno.
{93384}{93506}Sokovi bez natrija. Kriške jabuke,|organski kolaèiæi. Sve zdravo.
{93512}{93572}Hoæeš èuti ono|najbolje? -Jedva èekam.
{93591}{93688}Pola prihoda iæi æe za izgradnju|klinike na Connie Islandu.
{93717}{93775}Zar æeš pokloniti pola profita?
{93780}{93842}Ne, sve. -Sve?
{93852}{93998}Ostatak ide za obrazovanje|djece. I narkomani su bili djeca.
{94001}{94105}Promijenit æemo sve iz temelja.|-Ne možeš iskljuèiti prodavaèe.
{94110}{94219}A pogotovu ne Paradu nade. To je|samoubojstvo. -Nije. Nauèio si me.
{94229}{94365}Kad imaš mišiæe, stvaraš pravila.|Sad se osjeæam prilièno jakim.
{94379}{94480}Imam moæ i upotrijebit|æu je. Neka tako bude.
{94533}{94672}Shel, pomozi mi, udara|u ovo od jutra do mraka.
{94683}{94801}Mrzim mu to oduzeti, ali sve|me boli. -Znaš da volim Spinnera,
{94813}{94930}ali dugujem ti. Vidjet æu što mogu.|-Uèini bilo što, samo da je tiho.
{94948}{95003}Budi blagoslovljen.
{95116}{95175}Spasite nosoroga! Spasite nosoroga!
{95202}{95359}Spasite nosoroga!|Spasite afrièkog crnog nosoroga!
{95376}{95415}Izvoli. -Hvala.
{95448}{95518}Spasite nosoroga prije nego|što bude kasno! Donirajte novac!
{95624}{95744}Neka mene spase, a ne tog|tipa s rogom! Spasite Dugu!
{95754}{95785}Spasite Dugu!
{95822}{95929}Tvoj me klijent stavio u opasnu|situaciju, za koju Merve Green
{95933}{96090}misli da sam ja odgovoran. -Dosta.|-Nosorog me stavio u kutiju bez zraka.
{96096}{96229}Žao mi je, ali što ja tu|mogu? -Sve æu ti reæi.
{96239}{96336}Sve. Bit æemo partneri.|Èak i za šou na ledu.
{96348}{96459}Imamo šansu vratiti stvar u|svoje ruke. Maknimo nosoroga.
{96465}{96537}Stari dobri dani.|-Prije nosoroga.
{96570}{96601}Pusti da razmislim.
{96661}{96785}Nitko me neæe izuzeti. Briga me|za klinike. -Moramo srediti ovo.
{96799}{96901}Nosorog je izvan kontrole.|-Ako me želiš naljutiti, super ti ide.
{96905}{97021}Ne želim te ljutiti. Samo|nauèiti. -Stokesa æemo nauèiti.
{97029}{97140}O kolièini kiseline u East Riveru.|-Nije o njemu rijeè, veæ o Mopesu.
{97147}{97284}Nosorog je opasan. Razgovara s ljudima|s koji ne bi smio. -To nije dobro.
{97291}{97412}Misli da æe oèistiti naš posao.|Postoji samo jedan izlaz.
{97560}{97651}Deèki, imamo ozbiljan problem.
{97703}{97832}Ovo je prièa o otrovnom nosorogu|i njegovoj agresivnoj kampanji
{97836}{97982}da okleveæe, ocrni, degradira|i uprlja moje dobro ime!
{97997}{98106}Ali ono što ne može|uèiniti jest oduzeti mi život.
{98116}{98165}To jedino ja mogu.
{98188}{98323}Ovo mi je Smoochy uèinio. Ne mogu|živjeti u svijetu gdje nedužni pate,
{98329}{98395}a zloèesti uspijevaju!
{98726}{98846}žao mi je što morate proæi kroz|ovo. Ne pokušavajte me odgovoriti.
{98925}{99040}U ovom životu više|neæete vidjeti Randolpha Dugu!
{99046}{99137}Ovo je za tebe, Smoochy!|Ovo si mi ti uèinio!
{99338}{99365}Ne!
{99411}{99469}Što to radiš Randolphe Dugo?
{99666}{99701}U redu je.
{99859}{99907}Eno Smoochyja! Idemo!
{100464}{100571}Bože! Što sve ovo znaèi?
{100616}{100750}Lupa vratima, udara nogama,|U krevet me šalje bez peciva
{100770}{100898}No moj oèuh nije zao|Samo se prilagoðava
{100918}{101034}Karakter mu je loš i lijen je|Ogorèen je jer bez posla je
{101058}{101180}No moj oèuh nije zao|Samo se prilagoðava
{101208}{101316}I zato tri pozdrava za|èovjeka kojeg zovem Stan
{101322}{101492}Nije mi ni tata ni brat|lma peh, ali još je šef
{101515}{101606}Osim toga brine se o mojoj mami
{101625}{101758}Budi strpljiv sa Stanom|Nije lako biti drugi
{101793}{101923}No moj oèuh nije zao|Samo se prilagoðava
{101936}{102062}Upamtite, djeco, oèuh je kao novi|ljubimac. Trebaju strpljenje i ljubav
{102065}{102194}dok se ne naviknu na novi|okolinu. Ali ako bude zlostavljao vas
{102197}{102306}ili vašu mamu, koji|je èarobni broj? -91 1 .
{102321}{102459}Tako je! veoma sam|uzbuðen što æu vam predstaviti
{102462}{102520}iznenadnog nam|posjetioca. Djeco,
{102559}{102707}on dolazi iz rezervata za|nosoroge. Moj roðak, Moochy!
{102856}{102919}Doði ovamo, Mooch!
{102960}{103073}Ti veliki ispijaèu vode.|Bože, hvala ti što si došao.
{103086}{103157}Pozdravi sve djeèake|i djevojèice koji nas gledaju.
{103298}{103322}Moochy?
{103361}{103462}Ja sam Moochy.|-Da, to smo utvrdili.
{103489}{103559}Sheldone, od ovog|me kostima èešu jaja.
{103774}{103960}Biloje super! -Baš si bio dobar!|-Sou na ledu æe biti zabavan!
{103964}{104046}Sklizat æu se i pasti na guzicu i...
{104110}{104253}Jedva èekaš, ha? -Povratak|u Colliseum. U arenu...
{104280}{104452}I publika... Pljeskat|æe... Bit æe kao... Kao...
{104460}{104567}Raj. -Bit æe super, prvaèe.
{104607}{104726}Sheldone, volim te. Da, tako je.
{104772}{104900}Idem u garderobu... Presvuæi se...
{104905}{104950}A ti... Ti... Ti...
{105023}{105080}Dobro. U redu...
{105270}{105378}Uzbuðen je zbog šoua na|ledu. -Puno sam èitala o tomu.
{105385}{105535}Da, puno pišu o tome.|-Mislim da je super to što èiniš.
{105563}{105653}Hvala. Ti si me|nadahnula. Ti si bila ta.
{105677}{105748}Zaista sam ti zahvalan. -Dobro.
{105827}{105855}Hvala.
{105914}{106049}Ono o oèuhu je bilo dobro.|-Da? Ne znam što se dogaðalo s...
{106072}{106167}Energija je bila baš prava. -Da.
{106229}{106276}Da. -Da.
{106445}{106543}Nisi pun sranja kao i ostali,|zar ne? Pravi si? -Totalno.
{106584}{106697}Hoæu reæi, nisam znala.|Prvo sam mislila da glumiš,
{106773}{106890}a onda sam mislila|da si glup ili tako nešto.
{106895}{106933}Razumljivo je.
{106995}{107093}Onda ono sranje s|nacistima. -Opraštam ti za to.
{107135}{107167}Sheldone...
{107664}{107694}Koja je ovo runda?
{108514}{108652}Bivši boksaè, Spinner Dunn,|pronaðen je mrtav jutros.
{108656}{108713}Bio je odjeven u kostim nosoroga.
{108731}{108846}Kako ste mogli pogriješiti?|-Nismo znali za Moochyja. Isti su.
{108853}{108964}Smoochy je roza, a Moochy,|trula višnja. Èitajte novine.
{108970}{109082}Da vas šaljem u vrtiæ? -Rekao si|da ga ubijemo. Nisi specificirao boju.
{109088}{109190}Nisam ja kriv. -Nisam još|gotov s tobom, nosorože.
{109206}{109280}Doæi æe tvoje vrijeme.
{109324}{109458}Toliko je želio sklizati. -Nemoj|se muèiti više. -Žao mi je, Spinner.
{109485}{109574}Žao mi je. -Volio te, Shel. -Znam.
{109593}{109753}Garantiram ti da æe Randolph Duga|dobiti svoje. Jaja æemo mu odrezati.
{109768}{109896}Pustimo to policiji. -Oni|ne režu jaja. Protivno je pravilima.
{109904}{110030}Ne zaboravi, ti si bio meta.|Odsad, kamo ti, tuda i mi.
{110035}{110163}Bit æu u redu. -Vraga. Tako mi Boga,|nitko ti neæe dirnuti ni vlas s glave.
{110169}{110319}Spinner bi tako želio. -Jadnik.|-Deèki, pomolimo se i napijmo se.
{110349}{110442}Samo dajte. I za mene, dobro?
{110461}{110538}Nemoj nikoga ozlijediti,|Roy? Što bi Isus uèinio?
{111067}{111167}Koliko je dugo Randolph bio|ovdje? -Samo nekoliko noæi.
{111326}{111391}Smoochy! Tommy je došla!
{111627}{111763}Sigurna si? Policija ima mnogo dokaza|protiv Randolpha. -Sami smo istražili.
{111798}{111883}Roðak lan. Iz|mrtvaènice. Upoznao si ga.
{111911}{112074}Vidiš vrat. Slomljen. Životinje.|Parada nade. To je njihov znak.
{112078}{112151}Kako se zove onaj tip? -Merve Green.
{112205}{112344}Sada nisu trebali ostaviti|svoj znak. -Znala sam da je gad.
{112370}{112432}Èim me primio za guzu|na dobrotvornoj priredbi.
{112437}{112563}G. Green i njegovi prijatelji æe imati|pravu vožnju pravnim sustavom.
{112571}{112694}Sve je sreðeno. -Kako to misliš?|-U neko doba u ovom životu,
{112701}{112822}èovjek mora odgovarati za|svoje postupke. -To je bila greška.
{112835}{112955}Iskrena greška. Samo|pomažemo djeci. -Voliš djecu, ha?
{112960}{113037}Naravno. -Sigurno|onda znaš pokoju bajku?
{113046}{113146}Danny, isprièaj mu onu o|pederèini kojoj odrube glavu!
{113187}{113212}Ne!
{113222}{113247}Ne!
{113257}{113282}Ne!
{113439}{113553}Mislim da mi to nije drago.|-Uzeli smo glavu i zaigrali...
{113561}{113683}Dobro, to je zaista više|nego što želim znati. Hvala.
{113742}{113826}Mijenjam mišljenje. Mislim|da ovo nije dobro. -Smiri se.
{113842}{113947}Našli su Greenovu|glavu. -Ostaje više za nas.
{113959}{114098}To s Buggyjem je pogreška.|-Pusti ga meni. Kad obavi posao,
{114106}{114215}nosorog je mrtav, a mi|æemo zapaliti cigaru! Smiri se!
{114274}{114384}Gdje nam je poèasni gost? -Misliš|ovisnik o heroinu? -Sve æe biti dobro.
{114397}{114455}Oslanjamo se na ovisnika. Super.
{114569}{114709}Žali što kasnim. Zaspao sam na|autobusnoj postaji. -Dobro izgledaš.
{114720}{114794}Oprostite na smradu. Znate kako je.
{114827}{114879}Neka nam Bog pomogne.
{114925}{115081}Hoæeš neko piæe? -Votku.|Obavim to i mjesto je moje, toèno?
{115091}{115180}Tako je. Mora se uspavati.
{115197}{115260}Nosorog je veæ davno|trebao poæi na spavanje.
{115357}{115382}Buggy?
{115539}{115611}Dogovoreno? Spremni smo? -Da, naravno.
{115632}{115683}Pogledaj ta lijepa svjetla.
{115705}{115828}Svaki te murjak traži. Moraš ostati|skriven. -Htio sam biti sveæenik.
{115836}{115911}Znam. -Vjeruješ li u anðele?
{115954}{116051}Vidio sam jednog na|Times Squareu. S kovrèama.
{116093}{116191}Jedino je njoj bilo stalo|do mene. Spasila mi je život.
{116222}{116359}Ne želiš se ubiti. Znaš to.|-Vrijeme je za ozdravljenje.
{116395}{116537}Treba priznati da je Smoochy pobijedio|i nastaviti put. -Tako je, mali.
{116549}{116675}To je velik korak. Ponosim se.|-Donio si ruèak? Piletinu i zvijezde?
{116684}{116752}Kao što si tražio.|-Mogu dobiti? -Za osmijeh.
{116822}{116847}To!
{116888}{116944}Izvoli. Donio sam ti|križaljke i nešto za èitanje.
{117314}{117423}Jesi dobro? -Prvo|mi uzme karijeru,
{117431}{117567}zatim život, a na kraju i djevojku.|-Smiri se, više ti nije djevojka.
{117584}{117727}Kakva muda ima taj peder!|Dio po dio æu ga isjeæi!
{117742}{117831}Dio po dio! -Rekao si da je|vrijeme za ozdravljenje. Prestani!
{117857}{117949}Totalno æu ga sjebati! Rog po rog!
{117972}{118083} Jednom i zauvijek!|-Što je bilo s onim, nastaviti put?
{118093}{118142}Pederèina!
{118409}{118551}To! -Mogu vam pomoæi?|-Imam vijesti, Nora. -Buggy?
{118566}{118701}Kako si, ljepotice? Dugo se|nismo vidjeli. -Što ti radiš ovdje?
{118711}{118857}Imam posla sa Stokesom?|-Da? -Da. Vratit æe me u emisiju.
{118864}{118997}Dat æe mi priliku. Umjesto|nosoroga. -Sto to govoriš, Buggy?
{119008}{119172}Buggy æe ustati poput Phoenixa.|Ili nekog drugog grada u Arizoni.
{119224}{119328}Uvijek si mi se sviðala. Daj|da ti pokažem svoju opremu.
{119351}{119387}Mièi se, Drakulo!
{119394}{119488}Ostat æemo u vezi! U vezi!
{119532}{119633}Stokes se dogovorio s|Buggyjem za termin Smoochyja.
{119637}{119772}To je onaj isti Buggy iz Truckavih|traènica. -Da, dok nije otkrio heroin.
{119779}{119876}Nema smisla. Zašto bi Stokes|zamijenio Smoochyja s ovisnikom?
{119884}{120010}Ne znam. neka mi netko|da ruènik. Glava mi je u vodi.
{120044}{120089}Kako ste?
{120112}{120218}Dvoje za cijenu jednog!|lzvrsno, baš sam sretan.
{120224}{120320}Odjebi odvade. -Jedeš|s tim ustima? -Da.
{120331}{120458}Smirimo se malo. -Popuši|mi ga. Prvo je bila moja.
{120465}{120555}Što? -Tako je. Ukrao si mi je
{120559}{120693}i sad moraš platiti. -Zaboravi. -Hoæe|mi netko objasniti što se dogaða?
{120699}{120803}Nije ti prièala o našoj|ljubavi. Strastvenoj, ali nježnoj.
{120808}{120957}Staromodnoj, ali eksperimentalnoj.|-Lud si. -Prosvijetli momka, Nora.
{120964}{121084}Bila si vatrena kobila. Uzde|ti još pašu? -Pazi što govoriš...
{121089}{121202}Eksperimenti? Vidjela|sam i tvrðe. -Mali je, ali opak.
{121247}{121334}Samo malo. Ovo je istina?
{121365}{121447}Ti i on? -Ne. Znaš kako je... Da.
{121467}{121503}Kako ti se to èini?
{121540}{121673}Ti si samojoš jedan za njenu|kolekciju. -Suti ili æu te odalamiti.
{121677}{121777}Znam sve. Reci mu za Jingle Jacksona.
{121788}{121907}I s njim si bila? -Voljela se|igrati s njegovim zvonima.
{121931}{122060}A kit Wally? -Kako si|mogla biti s kitom Wallyjem?
{122066}{122192}Mala je mrak. -Ne mogu|vjerovati da mi nisi ništa rekla.
{122213}{122362}Sheldone, ne ponosim se time,|ali bilo je doba u mom životu,
{122372}{122495}kad sam voljela grupnjake.|-O, Bože, vrti mi se.
{122501}{122648}To nema veze s nama. To je bilo|drugo vrijeme. Bila sam drukèija.
{122654}{122754}Pokazao si mi svijet za|koji nisam znala da postoji.
{122762}{122899}Zaista? -Da. -Koji ja|to kurac gledam ovdje?
{122903}{123038}Nekakvu sapunicu? Ti ovo,|ja ono... Tišina! Ovo je moj šou!
{123049}{123160}Znaš li koliku moæ ima osuðeni|èovjek? -Smiri se, Randolphe.
{123166}{123317}Mislim da ne želiš nikomu nauditi.|-Odjebi. Što si uèinio od ovog mjesta?
{123322}{123475}Ovo je za Diane Fossey. Sa mnom je sve|bilo Bob Fossey. Tu je bila gola pica.
{123479}{123598}S biljkom u ruci. Pica se nije|vidjela. Sad je tu slika tvoje mame!
{123613}{123738}Znamo da nisi ti ubio Spinnera.|Smiri se. -Hvala, Majko Tereza.
{123743}{123888}Reci to onim mafijašima. Žele me|koknuti. Kao da sam na prodaju.
{123892}{123996}Randolphova guzica, treæi red.|-læi æemo na policiju. Ujutro.
{124000}{124111}Sve æu im objasniti|i sve æe biti u redu. Vjeruj mi.
{124189}{124275}Ne poèinji s trikovima, mladi Mojsije.
{124286}{124372}Ja sam Faraon, a ti moj rob.
{124408}{124500}I ovo je moje kraljevstvo!
{124562}{124649}Randolph Duga pravi je|O da, o da, o da...
{124670}{124760}On je glavni u zemlji duge|O da, o da, o da...
{124765}{124912}Zabava tu, zabava tamo|Randolph Duga je kralj...
{125124}{125190}Što?|-Uzmi mu pištolj.
{125293}{125371}Boli me.|-Hoæeš izgorjeti?
{125388}{125443}Prevruæe je! Poludjet æu!
{125625}{125674}Hajde, ubijte me!
{125716}{125827}Dovršite me. Ja sam|nula. Poštedite me jada.
{125865}{126021}Nisi nula. Ogorèen si, krivo|voðen i seksualno zbunjen.
{126032}{126149}Ali još si Randolph Duga. To|vrijedi. Mnogu si djecu usreæio.
{126225}{126261}Hoæeš mi biti prijatelj?
{126338}{126425}Naravno. -Oboje vas volim.
{126468}{126595}Spuštaš se na njihovu razinu.|-Ne, opametio sam se. -Ima pravo.
{126600}{126728}Nemoj pogriješiti kao ja.|Zadrži dignitet. Moja jaja!
{126741}{126886}Gore! -Hvala na|brizi, ali znam što èinim.
{126896}{127020}Pokušao sam. -Moramo na|predstavu. Ostani ovdje koliko želiš.
{127028}{127110}Ovdje si siguran.|-On je dobar èovjek, Nora.
{127130}{127251}Odmori se. -Pravi si,|Sheldone. -Hvala, Randy.
{127279}{127353}Ja sam prevarant. Zloban|sam èovjek koji je poèinio zlo.
{127375}{127491}Baš kao u pjesmi,|Svi imamo loš dan.
{127618}{127731}Buggy? -Angelo. -Što to|radiš? Mislio sam da si èist.
{127751}{127833}Da, oèistio sam|pola polja maka u Aziji.
{128432}{128532}Izvolite. -Sol. -Žalim,|naši su proizvodi bez soli.
{128832}{128976}Trebali bismo odustati. -Ne mogu.|Mnogo djece i ovisnika raèuna na mene.
{129006}{129043}Moram obaviti posao.
{129102}{129152}Hajde, zaželi mi sreæu.
{129197}{129325}Halo? -Randy?-Angie, mali. Što|æeš odjenuti? Nadam se samo tangu.
{129329}{129362}Buggy je bio tu.
{129366}{129439}Onaj s dva D.|-Da, provalio je kod mene,
{129442}{129532}uzeo mi je propusnicu i rekao da|mora obaviti nešto za Bennetta.
{129535}{129644}Dobit æe šou kad nosoroga više|ne bude. Bio je elegantno odjeven.
{129656}{129755}Imam loš predosjeæaj.|-Ma da. -Moram do ledene dvorane.
{129762}{129910}Murja æe te uhititi. -Briga me.|Burke i Ding Dong jednako nevolje.
{129913}{129949}Moram spasiti nosoroga. -Èekaj...
{129960}{129985}Randy!
{130027}{130128}Vaš najdraži nosorog, dame|i gospodo, djeco, evo Smoochyja!
{130328}{130353}Hvala.
{130370}{130413}Hvala. Hvala.
{130425}{130562}Hvala vam u svoje i u ime|uskoro obnovljene klinike za metadon.
{130636}{130667}Da, jupi.
{130691}{130849}Hvala. Znam da ste došli èuti|vama najdraže Smoochy pjesme,
{130855}{130954}ali priredili smo nešto|drugaèije. Nešto osobno.
{130963}{131072}Uvijek sam govorio da|budete iskreni u vezi osjeæaja.
{131081}{131286}Da ja ne podijelim svoje s vama,|ne bih bio iskren nosorog, zar ne?
{131304}{131457}Kreæem na put. Nadam se da idete sa|mnom. Moraš imati prijatelje uz sebe.
{131689}{131729}Ovo je za Spinnera.
{133753}{133836}Smoochy je broj 1
{133924}{133972}Nemoj da te uhvate, Smoochy!
{134350}{134493}To je Randolph Duga!|-Ne, nisam Samo mu slièim!
{134501}{134609}Pokušavam spasiti prijatelja od|ovisnika. Dobro, jedna za djecu.
{134618}{134652}Prijatelja ima svih velièina.
{138441}{138466}Isprièavam se.
{138577}{138623}Sheldone! -Zbogom, Smoochy.
{138961}{139012}Ubio si Smoochyja, gade!
{139063}{139145}Daj tu pušku! -Pusti me!|Moram ubiti nosoroga!
{139296}{139340}Skidaj se s mene! Ne!
{139396}{139432}Daj tu pušku, gade!
{139563}{139686}Sheldone, to je Buggy. -Što|sad? -Preživljavanje najsnažnijih.
{139744}{139771}To je Buggy!
{139840}{139921}Eno Randolpha!|-Puštaj, ti jebeni ovisnièe!
{140024}{140066}Nikad nisam bio u Veneciji!
{140339}{140423}Jesi dobro? -Ne znam.|Nekako sam opæenito sjeban.
{140507}{140615}Burke ti je htio smjestiti!|Pokušao te ubiti! Eno ga!
{140639}{140739}Bježi! -Burke! -Ne! Sheldone!
{140776}{140806}Burke! Vraæaj se!
{141194}{141219}Eno Smoochyja! -Burke!
{141314}{141365}Zaustavite ga! -Eno Smoochyja!
{142718}{142838}U mene si uperio pištolj? Onaj koji|sam ti poklonio? Gdje ti je etiketa?
{142844}{142967}Pištolji imaju malu tajnu.|-Da? koju? -Moraš ga napeti.
{142992}{143036}Baci ga, seronjo!
{143251}{143326}Ne mièi se! Jesi li dobro? -Jesam.
{143385}{143519}Ti! -Smiri se. -Bio si mi menadžer.|Kako si mi mogao tako smjestiti?
{143526}{143647}Zbog okolnosti. -Okolnosti? Ubio|si Spinnera! -Tragièna pogreška.
{143658}{143754}Da bar mogu vratiti vrijeme.|-Bio mi je prijatelj, gade!
{143788}{143910}Ustaj! Pogledaj me!|-Ubit æeš me? -Tako je!
{143914}{144036}To baš i ne prilièi Smoochyju!|-Sad se baš ne osjeæam kao on.
{144050}{144171}Èekaj... -Zajebavao si se|s pogrešnim nosorogom.
{144177}{144261}Ne! -Ne èini to, Sheldone!
{144301}{144422}Tommy, ovo se tebe ne tièe. -Nemoj|sve upropastiti zbog tog govna.
{144543}{144575}Daj mi taj pištolj.
{144631}{144675}Bože, što to radim?
{144715}{144850}Hajde. Tako. -Žao mi je.|Ne znam kako se to dogodilo.
{144887}{144975}Samo si èovjek, dragi.|Idemo. Idite odavde. Hajde.
{145053}{145154}Što æemo s njima? -Ništa ti|ne brini. Mi æemo to obaviti.
{145162}{145290}Sigurno? Nemojte biti ekstremni.|-I štakor zaslužuje milost ponekad.
{145302}{145393}Hvala. -Vraga cigare! -Šuti!
{145432}{145477}U govnima smo! Velikima!
{145619}{145688}Jeste li ikada prije zajedno putovali?
{145990}{146080}Prekrasan grad,|ali ima puno prljavštine.
{146112}{146212}Ti si ga malo oèistio. -Misliš?
{146246}{146331}Hvala. -Idemo kuæi,|Smooch. Predstava je gotova.
{146365}{146434}Nije. tek poèinje.
{146980}{147086}S velikim zadovoljstvom vam|predstavljam, po prvi put zajedno,
{147089}{147195}bok uz bok, rame uz rame,|dame i gospodo, djeco, pozdravite
{147223}{147305}nosoroga Smoochyja|i Randolpha Dugu!
{150459}{150549}K R A J
{150569}{151549}{C:$0000FF}Obrada: |{C:$FF0000} movies|{C:$0000FF}Damir_123