{1}{1}25.000
{1760}{1860} RAZINA STRAHA 
{6835}{6891}Gospoðice, jeste li dobro?
{7723}{7788}Ne sjeæam se kada me prvi put | probudila noæna mora.
{7838}{7893}Prestrašni su da ih zovem noæni snovi.
{7896}{7965}CHEEVER LAKE - DOBRO DOŠLI
{7971}{8017}Nikome nisam rekao za njih.
{8056}{8097}Nikada nisu imali nikakvog smisla.
{8143}{8179}I onda sam pronašao Put.
{8220}{8310}Sada su mi jasni.
{8342}{8408}KAMPUS FAKULTETA CHEEVER LAKE
{8556}{8601}Doruèak za prvake.
{8631}{8670}Kada si se zadnji put naspavao?
{8673}{8743}Sretan sam što mogu stajati. | Veæ tri dana bjesnim.
{8746}{8806}Stari æe te srediti ako ne položiš koji ispit.
{8809}{8864}Otkad mu treba isprika?
{8867}{8902}Ti bar ne živiš kod kuæe.
{8905}{8962}Odmah bih se mijenjao s tobom.
{9001}{9052}Kako si, Jake? | - Dariuse.
{9055}{9082}Kako si?
{9087}{9125}Hoæeš li zaigrati u iduæoj godini?
{9155}{9222}Ne znam. | - Postupi pametno.
{9238}{9284}To si rekao i u prošlom polugodištu.
{9296}{9370}Deèki u teretani govore mi da si pravi.
{9444}{9508}U što buljiš? | - Ne u tvoj džip, kompa.
{9692}{9727}Polako. | - Što to ima?
{9730}{9760}Ništa. | - Gluposti.
{9763}{9789}Zaboravi.
{9797}{9857}Drži ga na uzici. | - Hoæu.
{10029}{10075}Zar si ga mislio upucati?
{10078}{10126}Smiri se. Ono mi je reklo da ga uplašim.
{10130}{10180}Što je to "ono"?
{10197}{10228}Vrati mi ga.
{10231}{10304}Neæu. Jesi li poludio? Želiš li da te uhite?
{10316}{10348}Odakle ti to?
{10374}{10398}Reæi æu ti kasnije.
{10440}{10466}Sretan roðendan.
{10542}{10612}Joseph Campbell je vjerovao | da je snaga mita povezana
{10620}{10718}s odreðenim važnim i opæim | vrijednostima nekih kultura.
{10721}{10802}Npr. Potreba za štovanjem Boga, | za štiæenjem obitelji
{10815}{10865}ili suživot s prirodom.
{10886}{10965}Iz ovih su zamisli nastale prièe
{10968}{11030}koje su prenesene iz | jednog naraštaja u drugi
{11033}{11094}a svaka je imala svoga glavnog junaka.
{11102}{11138}Zanima li te što si propustila?
{11186}{11262}Da me zanima, ne bih propustila.
{11295}{11351}Campbell je nazvao plemenitim putom...
{11354}{11418}Samo ti želim pomoæi. | - Šteta.
{11440}{11501}Mislila sam da me želiš odvuæi u krevet.
{11557}{11585}Danas mi je roðendan.
{11665}{11692}Dovoljan razlog.
{11773}{11844}No zanimljivije od prièa | koje smo slušali odrastajuæi
{11847}{11889}i tradicije njihove usmene predaje
{11892}{11981}jest ono što povezuje najrazlièitija društva.
{12005}{12084}Sretan roðendan, ljepotane.
{12144}{12230}Kako je imati 21 g.? | - Još nemam planova za buduænost.
{12233}{12315}G. Gray, prekidam li slavlje?
{12333}{12370}Oprostite, prof. Hartney.
{12377}{12478}Èemu služi ovaj Dionizijski dar, Dakota?
{12556}{12584}Za koktele.
{12697}{12775}U redu. Gotovi smo za danas. Hvala.
{12884}{12971}Hoæemo li ga popiti veèeras? | - Veèeras æemo raditi štošta.
{13062}{13090}Dakota.
{13127}{13176}U moj ured, za 30 min.
{13230}{13273}Izbavi me iz ovoga grada.
{14126}{14156}Raèunala Liteon
{14521}{14602}SRETAN ROÐENDAN, DRAGI | Volim te, mama
{14730}{14763}Ti si Jake.
{14806}{14842}Jesam. Kako znate?
{14862}{14926}Dami je potrebna pomoæ.
{14976}{15046}U redu. U èemu je problem?
{15108}{15148}Prestao je raditi.
{15164}{15190}Dogodi se to.
{15251}{15278}Dobro. Da vidimo.
{15376}{15451}Tako to izgleda unutra? | - Što ste oèekivali?
{15454}{15523}Puno èovjeèuljaka | koji obavljaju stvari za mene.
{15611}{15639}U redu.
{15762}{15833}Ovdje ima crvenog voska.
{15864}{15920}Vosak? Moje tarot karte.
{15937}{16031}Molim? | - Kada ih èitam, zapalim svijeæe.
{16051}{16097}Pomažu vam da èitate buduænost, zar ne?
{16100}{16140}Da, i prošlost.
{16216}{16243}U redu.
{16290}{16315}Radi.
{16434}{16491}Koliko sam dužna? | - Ništa.
{16519}{16554}Zbilja? | - Da.
{16560}{16613}Lijepo od vas. Hvala.
{16634}{16659}Jake.
{16782}{16837}Mogao si naplatiti 75 $ .
{16840}{16884}Za komad voska. | - Je li?
{16891}{16931}Uzet æu ti od plaæe.
{16934}{16960}Zašto?
{16963}{17033}Tvoje vrijeme je moj novac.
{17058}{17111}Molim te, pazi što govoriš.
{18208}{18250}Neæeš li ih ugasiti?
{18253}{18305}Neæeš li mi zapjevati "Sretan roðendan"?
{18308}{18390}Prestao sam pjevati | kad su me izbacili iz crkvenog zbora.
{18510}{18545}Jesi li posjetio majku?
{18557}{18635}Nisam. Nije se osjeæala dobro. | Posjetit æu je sutra.
{18696}{18738}Što ima u tvornici?
{18754}{18785}Još imam posao.
{18813}{18880}Ako te se riješe, morat æe je zatvoriti.
{18883}{18908}Hvala.
{19006}{19094}Izlaziš li s Conradom i s Dakotom veèeras?
{19108}{19133}Punoljetan sam.
{19145}{19179}Oni te poštuju, Jake.
{19278}{19323}Mislim da ne vide èisto.
{19390}{19425}Što to znaèi?
{19456}{19485}Drži se svojih ciljeva.
{20331}{20399}Ludex? X? Koji je tvoj otrov, ljubavnièe?
{20402}{20477}Uživaš ili plaèeš? | - Imala sam i boljih dana.
{20480}{20536}Što se zbilo? | - Hartney mi se opet upucavao.
{20539}{20615}Što je rekao? | - Ševa ili jedinica.
{20622}{20657}Lijepo je to sroèio.
{20660}{20757}Pobjegla sam iz ureda. | Uspjela sam to odgoditi.
{20760}{20819}Zašto ga ne prijaviš? To stalno radi.
{20822}{20883}Dean Glick neæe ništa poduzeti. | - Zašto?
{20890}{20928}Pomoæi æu ti da pogodiš.
{21019}{21059}Doði!
{21100}{21127}Sranje.
{21437}{21499}Razbit æu vas obojicu!
{21507}{21566}Nisam tražio pojaèanje. | - Nema na èemu.
{21602}{21698}Valerie Gaines, iza sportske dvorane.
{21733}{21768}Maturalna veèer.
{21776}{21855}Mislili ste da pudramo nos.
{21858}{21907}A ona ga je gurala ispod moje suknje.
{21948}{21979}Èovjeèe!
{22040}{22102}Koji je naš zip code?
{22107}{22156}98133.
{22171}{22209}Jesi li znao za to?
{22212}{22266}Osobno mislim da je deprimirajuæe.
{22278}{22325}Jer nisi bio ondje.
{22333}{22389}Tako je. Koje si godište?
{22392}{22422}Kao i ti. Glupane.
{22448}{22539}Koji su tvoji najèudniji obiteljski praznici?
{22553}{22596}Zaboravi. Trebala bi cijelu noæ...
{22616}{22711}A tvoji najèudniji obiteljski praznici?
{22823}{22871}Dan zahvalnosti, prije dvije godine.
{22884}{22959}Gradio sam rampu za | mamina invalidska kolica.
{22968}{23010}Otac Moore je došao u posjet.
{23026}{23135}Gledali su utakmicu. | Dallas - Tampe. Dallas je izgubio.
{23224}{23276}To su tvoji najèudniji obiteljski praznici?
{23279}{23331}Držao sam èekiæ,
{23334}{23402}otac Moore mi se nasmijao,
{23408}{23473}a ja sam zamišljao kako ga lupam po glavi.
{23545}{23610}A zatim bih to uèinio i roditeljima.
{23638}{23699}Ali i polovici ljudi koje poznajem.
{23715}{23790}Pomislio sam što bih još htio uèiniti.
{23836}{23889}Svakakva su mi sranja | poèela padati napamet.
{23991}{24022}Što se dogodilo?
{24060}{24108}Završio sam rampu i pojeli smo puricu.
{24165}{24256}Ovo je prebolesno, èak i za mene.
{24263}{24372}U svojim sam snovima | kastrirala oca 112 puta.
{24431}{24460}Baš smo se našli, zar ne?
{24471}{24531}Zaigrajmo zbilja sjebanu igru.
{24753}{24801}"Dobro došli na Put."
{24878}{24930}Put.
{24992}{25039}Nisam to igrala.
{25049}{25100}To je tajna, Dakota.
{25125}{25189}Nije neka tajna, ako ti znaš za nj.
{25216}{25241}Ozbiljno ti govorim.
{25244}{25296}Date mu broj telefona
{25315}{25391}i ono vas nazove | i naredi vam da èinite bizarne stvari.
{25396}{25438}Kakve bizarne stvari?
{25452}{25519}Ne znaš, ako ne igraš.
{25530}{25592}Kako se poèinje? | - Poèeli smo.
{25657}{25686}Sretan roðendan.
{25784}{25846}Sranje. Ovo je moj život.
{25849}{25890}Nije li ludo?
{25912}{25967}Neæeš nikada postati Predsjednikom, stari.
{26030}{26080}Iskljuèi to. Možda netko èita.
{26083}{26167}Nikog ne zanima | tvoj bijedan bankovni raèun.
{26170}{26199}Prekini to.
{26226}{26251}Sranje!
{26281}{26322}Tako sam pijana.
{26391}{26426}Treba mi još jedno piæe.
{26429}{26466}Pijmo s tijela!
{26550}{26606}Stižem za minutu. | - Uživaj.
{26708}{26758}Dobro došli u PUT
{26896}{26930}Srednja škola Cordova | ZDRAVSTVENO OSIGURANJE
{26933}{26966}WASHINGTON - Fakultet Cheever Lake
{27412}{27451}Što to radiš?
{28672}{28730}Donijela ih je ženska | kojoj nisi naplatio popravak.
{28802}{28835}Je li ostavila broj?
{28844}{28886}Slièim ti na tajnicu?
{28966}{29013}Nego, otpušten si.
{29049}{29091}Ma nemoj. Zakasnio sam 10 min.
{29097}{29168}Moj neæak je izašao iz zatvora. | Treba mu posao.
{29174}{29225}I meni. | - Nisam siguran.
{29232}{29311}Dilaj travu poput njega. | Prije uhiæenja zaradio je brdo love.
{29424}{29455}Daj mi kljuèeve.
{29516}{29552}Šališ se.
{29658}{29700}Duguješ mi plaæu za dva tjedna.
{29747}{29775}Tuži me.
{29792}{29816}Kujin sine.
{30104}{30129}Molim?
{30132}{30206}Dobio si otkaz, | a ti si samo udario šakom o stol?
{30243}{30270}Tko je to?
{30280}{30349}Znam što ti govore glasovi u glavi.
{30352}{30417}Ne znam tko si. Nemam vremena za igre.
{30420}{30466}Ne bi dopustio Conradu da te uèlani,
{30469}{30541}da ne tražiš razonodu | kako bi pobjegao iz jadnog svijeta.
{30544}{30573}Sretan roðendan.
{30669}{30699}Je li to Put?
{30702}{30777}Danas se osveæujemo glupanu | kojeg æeš ti odabrati.
{30786}{30839}Imaš li koga na umu? | - Svoga šefa.
{30842}{30915}Što bi mu htio uèiniti? | - Ubio bih ga.
{30918}{30960}Uèinit æeš mu uslugu.
{30996}{31041}Uživaj u prvom danu slobode
{31056}{31129}i vrati se sutra da vidiš | što æe Put uèiniti za tebe.
{31723}{31756}Tko je naruèio orhideju?
{31835}{31871}Ne oèekuj napojnicu.
{32187}{32225}Jesi li mislila na mene?
{32252}{32309}Samo izmeðu satova plesa.
{32380}{32428}Jesi li dobro? | - Jesam.
{32432}{32464}Zbilja? | - Da.
{32475}{32515}Kako je na poslu?
{32543}{32568}Odlièno.
{32608}{32651}Slažeš li se s ocem?
{32684}{32710}Da. Dobro smo.
{32738}{32772}Je li toliko loše?
{32834}{32882}Možda bih se trebala vratiti kuæi.
{32911}{32959}Ovo nas mjesto stoji puno novca.
{32968}{33039}Nemoj. Nitko se ne bi mogao brinuti o tebi.
{33068}{33096}Ja i tata smo dobro.
{33196}{33267}Nikada nisi znao lagati.
{33300}{33371}Gdje ti je deka? Idem po nju. Prièekaj.
{33375}{33433}Oprostite. Mogu li dobiti deku za...
{33487}{33537}Marisol. | - Jake.
{33588}{33619}Što radiš ovdje?
{33651}{33691}Poznajete se?
{33696}{33743}Da. Došla je u duæan.
{33753}{33795}Jake mi je spasio život.
{33816}{33852}To je samo raèunalo.
{33921}{33980}Znaèi, ti donosiš Kathy cvijeæe?
{33983}{34008}Da.
{34135}{34214}Donijet æu vam deku. | - Hvala na kartama.
{34230}{34271}Nema na èemu. | - Svijet je mali.
{34298}{34355}Jest. No sviða mi se takav.
{34448}{34479}Pazi kako se ponašaš, mama.
{34532}{34580}Zašto da sada poèinjem?
{34628}{34667}CHEEVER LAKE URED ŠERIFA
{35015}{35067}To je on. On me opljaèkao.
{35090}{35128}Uhitite ga. | - Smirite se.
{35131}{35236}Otpustio sam ga juèer. | Vratio se i opljaèkao me.
{35246}{35311}Došao sam po novac. | Duguje mi plaæu za dva tjedna.
{35314}{35364}Jeste li sinoæ dolazili ovdje? | - Nisam.
{35370}{35402}U redu. Uèinimo sljedeæe.
{35405}{35491}Pogledajmo što su snimile kamere.
{35494}{35541}Nisi znao za njih, zar ne, Jake?
{35544}{35618}Pustit æu vrpcu od trenutka | kada sam zatvorio duæan.
{35748}{35779}Koga vraga?
{35884}{35910}To nisam ja.
{36068}{36099}Falsificirao si vrpcu.
{36131}{36187}Nitkove jedan! Zar ne shvaæate?
{36195}{36228}Vraški je pametan.
{36236}{36273}Sredio si me, Graye!
{36276}{36335}Kako si to uèinio?
{36412}{36483}Tko su ovi deèki?
{36486}{36554}Ne znam. Zato pokušavam upasti na site.
{36592}{36661}Tko god bili, ne bih ih razljutila.
{36664}{36689}Slažem se.
{36702}{36727}Sranje.
{36805}{36854}Otkad te zanima vudu?
{36857}{36926}To su spiritualna objašnjenja | univerzalnih ideja.
{37000}{37039}Tako je pisalo na kutiji.
{37159}{37211}Što su ti karte rekle o tim tipovima?
{37352}{37417}"Slike prikazuju mladost, ljubav i nevinost
{37420}{37474}"prije nego što ih požuda pokvari."
{37626}{37671}Sjeæaš se kada si mi oduzeo nevinost?
{37752}{37810}Ako se dobro sjeæam, ti si je oduzela meni.
{37867}{37895}To su detalji.
{38060}{38106}Da zapalimo svijeæu?
{39570}{39606}Toliko o maženju.
{39646}{39727}Jake, dobio si što želiš,
{39730}{39784}a ja se igram Puta.
{39818}{39883}Vodili smo ljubav jer ti je Put to naredio?
{39886}{39949}Ne. Poševila sam te jer mi je Put to naredio.
{39988}{40036}Kada si poèela igrati?
{40064}{40096}To tebe ne zanima.
{40156}{40218}Ionako te nikada nije bilo briga za mene.
{40256}{40295}A to važi za sve muškarce.
{40480}{40508}Vidimo se na faksu.
{41761}{41787}Halo?
{41796}{41824}Nešto ti odvlaèi pozornost?
{41841}{41882}Bolje to nego da gledam televiziju.
{41888}{41935}Spreman za još jedan test?
{41948}{41992}Nije li to bio Dakotin test?
{41999}{42051}To nam nije bio prvi put.
{42054}{42097}Ali je ona držala sve pod kontrolom.
{42119}{42168}Mislio sam da se ja trebam zabavljati.
{42171}{42243}Bit je u tome da vidimo što imaš u glavi.
{47199}{47235}Veèera je gotova.
{47844}{47875}Hoæeš li mi slomiti ruku?
{47920}{47967}Što je s tobom?
{47970}{48006}Baci loptu.
{48309}{48340}Da vidim.
{48532}{48588}Je I' Darius to uèinio? | - S malo pomoæi.
{48628}{48692}Kvragu. Ne mogu te paziti danju i noæu.
{48721}{48750}Jesam li to tražio?
{48772}{48856}Ne seri. Èuvam te otkad nam je bilo 9 g.
{48861}{48896}Zašto ne prestaneš?
{48937}{48966}U redu.
{48990}{49015}Oprosti.
{49030}{49093}Pokušavam se oduprijeti drogi.
{49158}{49200}Mislim da smo obojica zastranili.
{49203}{49276}Slušaj. Sinoæ sam bio u podrumu.
{49289}{49334}Nazvali su me iz Puta.
{49337}{49403}Okrenuo sam se i ugledao | ogromno biæe kako zuri u mene.
{49406}{49438}Biæe.
{49444}{49480}Pola muškarac, pola žena.
{49500}{49558}Sanjao sam da sam se popeo u kuæu
{49570}{49622}i upucao starog u glavu.
{49634}{49688}Je li se takvo što dogaðalo i tebi?
{49691}{49732}Svakoga dana.
{49814}{49845}Odlièno.
{49914}{49980}Bit æu blag. | - Naravno.
{50261}{50301}Da. | - Jakey.
{50325}{50389}Imam dva komada u sobi.
{50405}{50473}Ne mogu ih otjerati. | - Odlièno, stari.
{50486}{50523}Zašto me nisi pozvao?
{50526}{50563}Baš bih tebe pozvao.
{50566}{50644}Kad bi te vidjele, odmah bi me odjebale.
{50726}{50756}Sve u redu?
{50782}{50844}Ne znam. Iscijeðen sam.
{50857}{50894}U redu, stari. Budi oprezan.
{50925}{50972}Doruèkujmo zajedno sutra.
{50975}{51012}U redu. Nazvat æu te.
{51015}{51060}Jake? | - Što je?
{51093}{51119}Odjebi.
{51526}{51570}Što još hoæeš?
{51594}{51652}Nitko ne zna koliko si sjeban.
{51658}{51715}I nikoga nije briga za to.
{52732}{52761}Koga vraga!
{53761}{53789}Connie.
{53869}{53919}Idemo na doruèak, stari.
{53943}{53983}Ili radije na ruèak.
{54081}{54123}Connie, probudi se.
{56397}{56425}Strièe Ross.
{56575}{56630}Zvuèao je loše. Trebao sam doæi.
{56705}{56746}I ti bi tako završio.
{56787}{56830}Conrad nije bio psihopat.
{56833}{56920}Uvijek je bio na rubu. | Ovo s Dariusom ga je dokrajèilo.
{56923}{57005}Malo bi se svaðali, a onda bi se ušlagirali.
{57020}{57083}To æe sigurno utješiti njihove roditelje.
{57118}{57160}Jesi li mu pomogao da ukrade pištolj?
{57193}{57218}Što?
{57221}{57317}Serijski broj je isti | kao i ukradenog pištolja... 38.
{57413}{57460}To je nemoguæe. | - Zašto?
{57489}{57551}Taj sam pištolj bacio u jezero Covent. | - Što si uèinio?
{57582}{57625}Connieju sam oduzeo pištolj.
{57628}{57701}Nisam htio da ima problema | i bacio sam ga u jezero.
{57704}{57749}Otkud mu opet pištolj?
{57752}{57778}Takvo što je nemoguæe.
{57788}{57832}Nemoj mi sada poèeti lagati.
{57835}{57862}Ne lažem.
{57865}{57932}I mene zanima što se dogodilo.
{57979}{58022}Hoæeš li ti reæi mojoj sestri ili ja?
{58207}{58265}Ja æu. A sad bih htio otiæi u bolnicu.
{58403}{58444}Tvoj sam stric.
{58481}{58526}Mogao si ga dati meni.
{59985}{60013}Jesi li dobro?
{60019}{60057}Ovo je najgori dan u mom životu.
{60077}{60110}Hoæeš da razgovaramo o tome?
{60146}{60175}Ne ovdje.
{60179}{60228}Naðimo se ispred za 5 minuta.
{60252}{60276}U redu?
{60345}{60370}Dobro.
{60509}{60561}Ne želim završiti poput oca.
{60573}{60657}Raditi od 6.00 do 20.00, | i to ponavljati svaki dan.
{60660}{60692}Što želiš raditi?
{60732}{60800}Da bar znam. | - Jesi li ikada pomislio da odeš odavde?
{60821}{60905}Tko bi majci donosio orhideje? | - Voljela bi i razglednice.
{61012}{61065}Èini se da voliš putovati.
{61081}{61106}Volim.
{61154}{61207}Volim sakupljati stvari.
{61266}{61339}Kako si dospjela ovamo? | - Zbog muškarca.
{61366}{61402}Nisam htio biti znatiželjan.
{61409}{61471}U redu je. Sada uživam u tome.
{61594}{61652}A ti? Viðaš li se s kime?
{61687}{61725}Dugo ti je trebalo da pitaš.
{61784}{61832}To æu shvatiti kao ne. | - Tako je.
{61881}{61977}No tko zna, možda naletim | na nekog kad najmanje oèekujem.
{62033}{62063}To se ne dogaða.
{62129}{62216}Loše tempiranje. | Želim otiæi iz grada, a ti si tek došla.
{62222}{62276}Moramo se naæi negdje u sredini.
{62346}{62372}U redu.
{62404}{62466}Bila si u pravu. Dan se proljepšao.
{62639}{62675}Žao mi je zbog tvog prijatelja.
{62949}{63043}Glumit æu frajera | i neæu te nazvati bar sat vremena.
{63082}{63129}U redu. Bog, Jake.
{63162}{63188}Bog.
{63747}{63842}Sjeæam se kad ste se ti i Connie | upoznali na vjeronauku.
{63916}{63941}Piješ li?
{63978}{64011}Ne molim se.
{64058}{64122}Misliš olako odbaciti 5 godina života?
{64139}{64231}Misliš li da ne znam | što ste ti i Connie radili?
{64234}{64262}Misliš li da to ne znam?
{64265}{64317}To što je Connie uèinio nema veze sa mnom.
{64320}{64350}Završio je u paklu.
{64430}{64470}Ne moram to slušati.
{64489}{64558}Prièekaj, Jake, èekaj!
{64668}{64753}Neæemo te uspjeti spasiti.
{64756}{64815}Nemoj mi zapovijedati s piæem u ruci, tata.
{64818}{64880}Nezahvalna huljo.
{64894}{64992}Znadeš li da smo sve žrtvovali zbog tebe?
{65017}{65083}Žrtvovali? Ti si se žrtvovao?
{65111}{65169}Mogao sam nekamo otiæi i štošta uèiniti.
{65172}{65226}No ostao sam ovdje zbog tebe i mame.
{65229}{65271}Èega si se ti odrekao zbog mene?
{65321}{65347}Svoje predivne žene.
{65358}{65386}Što to znaèi?
{65452}{65531}Mislio sam da æu moæi, no ne mogu. | - Što govoriš?
{65534}{65616}Što mi želiš reæi? Da mene okrivljuješ
{65619}{65677}zbog mamine nesreæe? | Sad æeš me zato okrivljavati?
{65680}{65767}I to dan nakon što se | moj najbolji prijatelj ubio?
{65800}{65848}Nije to ništa strašno, Jake.
{65961}{66051}Danas kada te najviše trebam, | kada trebam svoga oca,
{66076}{66101}ti uèiniš to?
{66207}{66233}Stidi se.
{66273}{66298}Jake?
{66489}{66513}BOG TE BLAGOSLOVIO
{66516}{66562}Ne znam bih li plakala ili vrištala.
{66593}{66621}Znam kako ti je.
{66696}{66752}Nazvala sam te šest puta.
{66798}{66861}Žao mi je zbog preksinoæ.
{66876}{66905}Ne brini se.
{67109}{67186}Zašto mi nisi odgovorio? | - Družio sam se s prijateljem.
{67241}{67267}Tko je ona?
{67301}{67329}Zove se Marisol.
{67391}{67431}Zvuèi egzotièno. | - Drukèija je.
{67447}{67496}Užasno kasnim. | - Dakota?
{67586}{67639}Èula si što si je Conrad uèinio, zar ne?
{67658}{67698}Stalno mislim o tome.
{67703}{67782}Sinoæ, nakon razgovora s Putom,
{67785}{67847}sanjao sam da sam sebi uèinio istu stvar.
{67903}{67995}Misliš li da je Put upleten u to?
{67998}{68070}Možda jest. Još uvijek igraš?
{68077}{68160}Nije zatražio od mene | da zavedem nekog drugog.
{68163}{68198}U redu. Uèini mi uslugu.
{68201}{68238}Bilo što. | - Prestani igrati.
{68322}{68349}Naravno.
{68392}{68463}Doði u Tomahawk sutra. Èastim te veèerom.
{68523}{68553}Dovedi prijateljicu.
{68695}{68736}Sigurno želiš društvo veèeras?
{68766}{68841}Ne, no volim biti s tobom. | - Dobro.
{68968}{69036}Sad sam zbilja ljubomorna.
{69069}{69123}Marisol, ovo je Dakota. | - Drago mi je.
{69130}{69200}Marisol. Prelijepo ime. | - Hvala.
{69203}{69275}Što znaèi? | - Na španjolskom znaèi more i sunce.
{69292}{69358}Roditelji su me nazvali prema | mjestu na kojemu sam zaèeta.
{69550}{69619}Doista bih voljela ostati razgovarati s vama,
{69622}{69676}no šef mi je za vratom.
{69697}{69744}U redu. Naruèit æemo za van.
{69747}{69795}Dva hamburgera, dva pomfrita i dva piva.
{69798}{69859}Ne ostajemo li? | - Ne. Imam iznenaðenje za tebe.
{69931}{69983}A sada bih se trebala razboljeti.
{70195}{70238}Oprostite. Tražim muški WC.
{70368}{70452}Znate gdje je. | Jedete ovdje dvaput na tjedan.
{70458}{70531}Jesi li razmišljala | o našem juèerašnjem razgovoru?
{70666}{70758}Budete li jaèe stiskali prsten, | otpast æe vam prst.
{70784}{70814}Imam ih napretek.
{70848}{70887}Seronjo!
{71233}{71311}Tomahawk. | - I Hartney zna da si slaba.
{71321}{71364}Svi muškarci to znaju.
{71384}{71477}Zašto Jake nije nikada s tobom | duže od jedne noæi?
{71537}{71592}Zna da si poševila sve njegove prijatelje.
{71606}{71657}Tko želi takvu djevojku?
{71678}{71750}Znam. Nisi ti kriva.
{71758}{71800}Tata je bio èudovište.
{71814}{71858}No, priznajmo nešto.
{71864}{71948}Puno cura ima loše oèeve, | no ne završe poput tebe.
{71965}{72007}Privikni se na to.
{72012}{72061}Ako te Hartney ruši,
{72064}{72174}cijeli æeš život raditi u ovakvim rupama.
{72187}{72256}Zar to želiš? | - Odjebi.
{72280}{72325}Svi odjebite!
{72346}{72433}To je moja cura. Nije li ti to godilo?
{72447}{72515}Zar ne shvaæaš da ti želim pomoæi?
{72527}{72562}Da se bolje osjeæaš.
{72574}{72651}Pomoæi æu ti da sve riješiš | s Hartneyjem dok nije prekasno.
{72676}{72704}Da.
{72714}{72800}Ne boj se. Vrijeme je za igru.
{72980}{73053}S 9 mj., moji su se roditelji | preselili ovamo iz Seattlea
{73056}{73106}kako bi živjeli blizu maminoga brata.
{73123}{73187}Zbog snježne oluje | otac je izgubio kontrolu nad autom.
{73190}{73242}Pravo je èudo što smo preživjeli.
{73248}{73300}Viša sila te èuva.
{73465}{73497}Je li dobro?
{73523}{73600}Nazvat æu je. Kasnimo. | - Gdje kasnimo?
{74044}{74143}Bol se isplati. Obeæavam.
{74158}{74207}Treba mi još malo lijeka, sestro.
{74211}{74244}Spreman? | - Spreman.
{74262}{74291}1, 2, 3, sad!
{74485}{74570}Znaš li se boriti? Nisam nikad | tetovirao cvijet na muškarcu.
{74588}{74638}To je za mamu, Walte.
{74653}{74703}Slomio si mi srce.
{74776}{74805}Oprosti.
{74820}{74858}Juèer sam prestao pušiti.
{74891}{74918}Odlièno.
{75977}{76003}Jake.
{76099}{76151}U što ste se uvalili ti i tvoji prijatelji?
{76192}{76216}Ni u što.
{76220}{76311}Prvo Conrad, a sada je Dakota | ubila profesora, pa sebe.
{76316}{76361}Ovo nije sluèajnost.
{76408}{76488}Mogao bi biti sljedeæi. Neæu to dopustiti.
{76652}{76738}Odvedite ga kuæi. | Pobrinite se da se naspava.
{76764}{76855}Želim da se sutra sastanemo u mojoj kolibi.
{76858}{76892}Ondje nas nitko neæe ometati.
{76895}{76968}Neæemo otiæi dok mi ne kažeš što se zbiva.
{77996}{78020}Strièe Ross?
{78447}{78475}Devet bodova?
{78567}{78600}Nisam vas èuo.
{78617}{78666}Kako se držiš?
{78708}{78746}Dobro. | - Zbilja?
{78790}{78820}Što je ispod zemlje?
{78846}{78900}Nakon lova pokopamo ostatke životinje.
{78919}{78983}To je indijanski ritual | koji sam Jakea davno nauèio.
{78994}{79041}Tako se duša životinje vraæa u zemlju.
{79099}{79137}Uðite.
{79306}{79357}Kad smo poèeli, Put je bio samo igra.
{79360}{79433}Imala je èudnu moæ. Znala je što mislimo.
{79436}{79504}I Conrad je uporabio pištolj | koji sam bacio u jezero
{79518}{79559}i odsjekao si jezik
{79562}{79658}poput mene, nakon što mi | je to poruèila zvijer u snu.
{79720}{79837}Pomislio sam da to nije bio san. | Da to možda nije igra.
{80096}{80134}Èini mi se da æu poludjeti.
{80182}{80280}Tražiš odgovor na nešto | strašno i zato nema odgovora.
{80297}{80323}Sviða mi se ovdje.
{80368}{80393}Mirno je.
{80448}{80476}Hvala.
{80508}{80576}Za dva sata imam sastanak | s FBI-em u svom uredu.
{80579}{80643}Zamolit æu ih da provjere | tu tvoju raèunalnu igru.
{80686}{80728}Zašto ne provedete noæ ovdje?
{80747}{80780}Možda ti pomogne.
{81288}{81315}Šerif North.
{83024}{83049}Što je?
{83091}{83120}Nešto nije u redu.
{83189}{83261}Oprosti. Trebali bismo otiæi.
{83284}{83309}U redu.
{83678}{83709}Razgovaraj sa mnom, Jake.
{83728}{83756}Sranje.
{85112}{85196}Podari odmor, O, Kriste, | svome slugi sa svojim svecima.
{85217}{85274}Gdje ne postoje ni tuga ni bol.
{85290}{85366}Ni uzdaha, nego vjeèni život.
{85403}{85503}Jedino si Ti besmrtan, Ti si Stvoritelj svega.
{85525}{85591}Mi smo smrtni, zemlja nas je rodila
{85612}{85666}i zemlji se vraæamo.
{85695}{85763}Tako si zapovjedio kada si nas stvorio:
{85773}{85864}"Prah si i u prah æeš se pretvoriti."
{85879}{85933}I prahu se vraæamo
{85945}{86016}I na grobu pjevamo pjesmu tu.
{86036}{86152}Aleluja, aleluja, aleluja.
{86388}{86459}Rekla si mi da me èuva viša sila.
{86495}{86539}Treba mi sad. Gdje je sad?
{86846}{86936}Vaš protivnik, Sotona, | obilazi k'o lav tražeæi kog da proždere
{86939}{86964}PETAR 5:8
{87172}{87198}Što je, Jake?
{87376}{87416}Moram posjetiti starog prijatelja.
{87679}{87746}Zašto te odjedanput | zanima Sotona, Jacobe?
{87817}{87857}Misliš li da zbilja postoji?
{87897}{87983}Mnogi ga u Crkvi doslovno shvaæaju.
{88000}{88118}Ja mislim da je simbol kušnje, | a ne rogata zvijer.
{88376}{88453}Što u Bibliji piše | o opsjednutosti i samoranjavanju?
{88509}{88564}Misliš da su tvoji prijatelji bili opsjednuti?
{88636}{88663}Možda jesu.
{88789}{88907}Marko 9:25:
{88939}{89056}"Kad vidje Isus da narod prilazi, | zaprijeti neèistom duhu:
{89059}{89165}"Nijemi i gluhi duše, | zapovijedam ti, izaði iz njega."
{89253}{89318}ZABRANA PARKIRANJA
{89441}{89495}Žao mi je zbog tvog prijatelja.
{89543}{89569}Hvala.
{89622}{89693}Kada si prestao štovati Sotonu?
{89915}{89981}Prije 10 godina. Kršæanin sam.
{90028}{90056}To je isplativije.
{90115}{90152}Zašto si poèeo s time?
{90163}{90216}Neki ljudi žele ono što im Bog ne daje.
{90232}{90261}Novac. Moæ.
{90265}{90318}Ja sam samo htio ševiti.
{90366}{90449}Ima više komada na Crnoj misi | nego na koncertu Metallice.
{90511}{90549}Što se zbiva na Crnoj misi?
{90563}{90590}Ljudi se razodijevaju.
{90624}{90670}Zatim nešto žrtvuju.
{90687}{90727}Maèku ili psa.
{90755}{90804}Sotona te nagraðuje ako ubiješ psa?
{90807}{90877}Što više daješ, više dobiješ.
{90904}{90946}Što se dogodi ako ubiješ ljudsko biæe?
{91000}{91053}U mojoj su grupi bili bankari i domaæice
{91056}{91111}koji su tražili drukèiju zabavu.
{91135}{91188}Poznaješ li nekog tko je odaniji od toga?
{91221}{91302}Ne susreæeš ljude | koji žele odustati od svoje duše.
{91488}{91543}Molim te, Walte.
{91843}{91883}Poznajem jednog tipa.
{91908}{91950}Uèini mi uslugu.
{92017}{92058}Nemoj mu reæi da sam te ja poslao.
{92451}{92490}Evo me. Sammy.
{92591}{92624}G. Reisz. Jake Gray.
{92640}{92710}Nazvao sam vas prije sat vremena.
{92817}{92841}Da.
{92856}{92917}Savjetovanje naplaæujem 50 $ na sat.
{92926}{92952}U redu.
{92983}{93019}Trebao bih tražiti više.
{93050}{93100}Tip koji mi popravlja auto traži 80 $ .
{93119}{93224}Nema pojma gdje su svjeæice, | a kamoli kako dozvati Sotonu.
{93459}{93507}Jesam li ti ikada nudio knjige?
{93535}{93560}Niste.
{93843}{93893}Rekli ste da se zove Put?
{93901}{93927}Da. Zašto?
{93930}{94030}Tako zovemo sponu | izmeðu vraga i opsjednutih ljudi.
{94033}{94067}Kako sam ja odolio tome?
{94081}{94154}Èesto nismo svjesni snage | dok ona nije stavljena na kušnju.
{94195}{94260}Zašto vrag to èini pomoæu raèunala i igrica?
{94263}{94292}Razmisli.
{94305}{94363}To je uèinkovit naèin širenja poruke.
{94379}{94443}Zamisli da je Hitler imao Internet.
{94452}{94514}Sotona je opet pronašao | nekog tko æe širiti zapovijed.
{95015}{95073}Drugi dolazak
{95083}{95114}Vidio sam tog èovjeka.
{95117}{95150}IGRANJE S G. KATEROM
{95244}{95272}U svojoj glavi.
{95285}{95310}I ja sam ga vidio.
{95376}{95440}Kako znate da može dozvati Sotonu?
{95486}{95519}Ja sam ga nauèio tomu.
{95602}{95675}Kada je Aidan Kater došao | k meni uèiti crnu magiju,
{95709}{95766}bio je obièan èudak koji je živio u autu.
{95814}{95862}Nakon nekoliko godina | prestao sam pouèavati.
{95895}{95954}No veæ je tada bio dobro uvježban.
{95974}{96006}Zašto ste prestali?
{96012}{96046}Trebao sam postati otac.
{96099}{96125}Trebali ste?
{96140}{96220}Anne Kilton je prije braka bila moja uèenica.
{96230}{96275}Imala je tešku trudnoæu.
{96281}{96323}Imala je loš predosjeæaj.
{96334}{96423}Htjela je da obavim žrtvovanje | u ime djetetova zdravlja.
{96429}{96462}Žrtvovanje ljudskoga biæa.
{96505}{96530}Odbio sam.
{96547}{96579}Kater vas je zamijenio.
{96617}{96682}Na povratku kuæi, | u vrtu sam pronašao pentagram.
{96699}{96738}Svugdje je bilo krvi.
{96748}{96782}Prvo sam pomislio
{96799}{96870}da je Anne žrtvovala nekakvu životinju.
{96890}{96930}No Anne nije bila ondje.
{96950}{97035}Kad su nakon dva dana našli | njezinu krvavu odjeæu u jarku,
{97084}{97158}znao sam da je Kater žrtvovao | nju zajedno s neroðenim djetetom.
{97192}{97222}Žao mi je.
{97243}{97274}Što su rekli u policiji?
{97327}{97364}Bili su od velike pomoæi.
{97386}{97431}Bio sam njihov glavni sumnjivac.
{97434}{97511}Iduæih pet godina proveo sam | dokazujuæi da nisam kriv.
{97514}{97567}To je jedino po èemu ih pamtim.
{97626}{97654}Praznom grobu.
{98231}{98282}IGRE KATER
{98469}{98526}Putem Puta Sotona opsjeda ljude.
{98529}{98602}I zatim ih natjera da ubiju.
{98617}{98658}I da poèine samoubojstvo?
{98667}{98698}Ona ih zavede.
{98789}{98824}Je I' Sotona žena?
{98831}{98885}Ne znam. Može biti što god želi, po potrebi.
{98888}{98928}Možda ti želiš da je tako.
{98931}{98978}Ja ne želim da bude žena.
{98981}{99038}Misliš da su Conrad i Dakota | željeli takvu smrt?
{99041}{99078}Jedan dio njih jest.
{99081}{99107}Ti ih nisi poznavala!
{99110}{99187}Ne mislim da si kriv. Ljut si jer...
{99190}{99219}Tako je. Ljut sam.
{99235}{99282}Moji su prijatelji mrtvi! Ljut sam!
{99302}{99359}No nisam lud. Kater stoji iza svega.
{99362}{99418}Moram poduzeti nešto. | Ne mogu samo stajati.
{99421}{99502}Što æeš uèiniti? Polit æeš ga | svetom vodicom? Zapaliti ga?
{99505}{99551}Povjerovala si da sam vidio nešto.
{99554}{99629}Da. Vjerujem da si imao priviðenje.
{99632}{99670}To je bilo u mom podrumu!
{99677}{99718}U redu. Slušaj.
{99750}{99816}Ovo je postalo preteško za mene.
{99895}{99948}Obožavam te, no ovo je otišlo predaleko.
{99951}{99994}Nisam smio doæi.
{99997}{100026}Žao mi je.
{100049}{100083}Sranje.
{102137}{102201}Ubojstva odaju štovatelje okultnog | na sjeverozapadu
{102295}{102340}LOV NA VJEŠTICE NA SJEVEROZAPADU
{102431}{102477}Sukob kršæanskih udruga i okultista
{102555}{102601}Sada te neæemo uspjeti spasiti.
{102605}{102686}Pepeo si.
{102695}{102728}Završio je u paklu.
{103131}{103180}Kamo to nosiš, Jake?
{103205}{103246}Roditeljima?
{103291}{103328}Ne možeš to uèiniti.
{103352}{103390}Sve æeš upropastiti.
{103639}{103666}Jake.
{103726}{103770}Nisam imao izbora.
{103855}{103884}Nitko od nas nema izbora.
{103939}{103967}Jesmo li u paklu?
{103980}{104006}Nismo.
{104044}{104082}No u paklu i nije tako loše.
{104147}{104173}Vidjet æeš.
{104646}{104721}Podsjeæaš me na sebe | kad sam bio tvojih godina.
{104727}{104754}Pametan.
{104780}{104806}Gnjevan.
{104820}{104897}Oèajnièki sam se trudio | da se pokažem vrijednim.
{104900}{104973}No duboko u sebi | uvijek sam znao da nije tako.
{104983}{105029}Nisam poput tebe. Ne ubijam ljude.
{105032}{105068}Ne, samo sanjaš o tome.
{105150}{105199}Tako si dospio do Conrada i Dakote?
{105202}{105268}Umiješaš se u njihov um | dok ne uèine nešto što ti želiš.
{105271}{105299}To je bio ispit.
{105342}{105386}Oni ga nisu položili, ti jesi.
{105438}{105506}Gledao si Sotonu ravno u oèi
{105532}{105565}i nikada nisi maknuo pogled.
{105704}{105740}Kada si to napokon uèinio,
{105755}{105791}znali smo da smo te pronašli.
{105815}{105855}Pronašli ste me pomoæu Puta?
{105973}{105999}Zašto?
{106009}{106051}Jer su te ukrali od nas.
{106073}{106117}Trebao nam je naèin da te povratimo.
{106139}{106163}Ukrali su me?
{106200}{106226}Tko je to uèinio?
{106229}{106279}Ljudi koje zoveš roditeljima.
{106302}{106385}Pronašli su majku kako se krije, | noæ kada si se rodio.
{106399}{106450}Bila je preslaba da im se opire.
{106506}{106534}Ti si lud.
{106551}{106642}Uzeli su te od prave majke | u noæi kad si roðen.
{106679}{106709}Moja prava majka?
{106726}{106752}Anne Kilton.
{106795}{106820}Gluposti.
{106865}{106919}Anne nije nikada rodila. | Ti si se pobrinuo za to.
{106928}{106990}Svaki sin želi vjerovati ocu, | no namještanjem
{106994}{107053}Anneine smrti, Ivan nije nikad otkrio istinu.
{107078}{107110}Pripadaš nama.
{107125}{107161}Uvijek je bilo tako.
{107180}{107210}Anne je imala plan,
{107213}{107262}no kada su se Paul i Kathy umiješali,
{107265}{107324}od Kraljeviæa Tame
{107327}{107378}pretvorio si se u još jednog sjebanog klinca.
{107524}{107553}Slušaj me.
{107722}{107762}Tvoj život je laž.
{107775}{107811}Zašto mi to radiš?
{107814}{107840}Zašto?
{108851}{108882}Ne boj se.
{108922}{108966}Ona æe ti sve objasniti.
{109039}{109063}Gdje je?
{112454}{112486}Sad znam tko si.
{113861}{113886}Zašto?
{115897}{115975}Ne!
{116918}{116965}Viša sila pazi na tebe.
{117053}{117109}Morala sam znati | da mi sin još uvijek pripada.
{117131}{117157}O, Bože.
{117170}{117230}Morao si ubijati prije | nego što sam ti se pokazala.
{117290}{117323}Oduzeli su mi te,
{117363}{117417}no žao mi je što sam ti to priuštila.
{117503}{117534}Ovo nije tvoja krv.
{117634}{117665}Popij to.
{117726}{117775}Prihvati ulogu dodijeljenu roðenjem
{117796}{117842}ili se vrati životu koji mrziš.
{118094}{118122}Hoæeš li biti uz mene?
{118154}{118196}Bit æu što god poželiš.
{121268}{121299}Ti si èudovište.
{121422}{121472}O, Bože. Misle li da sam ih ja ubio?
{121501}{121582}Sotona nije htio ubiti svoje dijete | i sada ja plaæam za to.
{121585}{121617}Jer želim biti ljudsko biæe.
{121667}{121700}No možda su u pravu.
{121710}{121752}Možda ne postoji Put.
{121766}{121871}Možda je to plod mašte | da mogu živjeti s ovim strahotama.
{121929}{121965}Probudite me iz ove noæne more.
{121991}{122056}Molim vas. Pomozite mi.
{122060}{122160}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan 
