{1175}{1221}...bez komenatara su  i jedna i|druga vlada.
{1224}{1340}Predsjednik je izrazio stav od ranije,|ali ovo je od velike važnosti za Francusku.
{1343}{1448}Spasioci su došli na mesto nesreæe| Zarigovog leta 370.
{1451}{1514}Let 370 je vozio 210 |putnika.
{1517}{1604}i poletio je u 7 sati ujutro,|a trebao se spustiti u Parizu.
{1607}{1678}Prvi izvještaji govore o tome|da izgleda da nema preživjelih.
{1681}{1741}Avion se srušio 70 km od|Beograda
{1744}{1819}i još je rano govoriti o|uzrocima.
{1822}{1859}Mada je vrijeme bilo sunèano
{1863}{1917}i nije bilo nikakvih neobiènih|dešavanja u kabini.
{1920}{1943}Postoje nepotvrðeni |izvještaji da je
{1946}{2023}poznati ratni zloèinac| Slobovan Pavlov,
{2026}{2085}bio jedan od putnika na avionu.
{2088}{2127}Prema našim izvorima u Interpolu,
{2131}{2202}Pavlov, jedan od najveæih|ratnih zloèinaca,
{2206}{2272}umiješan u ubojstvo stotine bosanskih|civila za vrijeme rata
{2275}{2331}je putovao sa lažnom putovnicom|na tom letu.
{2334}{2467}Ako je istina, bit æe ovo ironièan kraj|jednog od najveæih potjera u Europi.
{2470}{2540}Pridružite nam se u sljedeæoj dopuni|vijesti u 6 sati.
{2569}{2662}E X T R E M I S T I
{4476}{4512}Kako æemo biti sigurni?
{4515}{4554}U redu, hajdemo.
{4600}{4642}Zovi u pomoæ!
{4661}{4709}Hej, jesi li slikao?
{4709}{4748}Ne.|- Nevjerojatno.
{4751}{4816}To nije nevjerojatno,|to je ludo!
{4821}{4864}Moj Bože, što sam ti ja |govorio, Will?
{4868}{4932}Jesam li ti rekao da se povuèeš |prije nego uðeš u vodopade.
{4935}{4973}OK, OK, OK!
{4976}{5003}Podiži.
{5055}{5157}Halo?|Ne, nije loš trenutak. Odlièno je.
{5161}{5236}Znaš veæ, zezamo se,|pijemo pivo...
{5248}{5313}O, to je samo peraè suða.|- Povuci se.
{5426}{5471}Znaš kako æeš snimiti?
{5573}{5657}Moj koncept ove slike je |da se dobije slika...
{5671}{5710}i pokret.
{5723}{5758}U djeliæu framea.
{5761}{5791}reæi æete...
{5797}{5853}znaš što, nabavio je digitalnu| kameru
{5856}{5932}i završio posao, jer èak i da se |ne pomièu ona æe to uèiniti za njega...
{5935}{6046}Znate li da sa ovom kamerom možete| uhvatiti prikrivenu energiju trenutka.
{6049}{6091}Prikrivenu energiju?
{6095}{6146}Da, upravo tako.
{6149}{6172}Oprosti.
{6197}{6290}Što? Pa... on zna što je najbolje.| -Možete li mi nazvati gospodina Imaharamu?
{6300}{6322}Ian.
{6325}{6377}Što se dešava?|- U redu, slušaj.
{6388}{6451}U redu, nisam ostavio kljuè|i nisam...
{6454}{6484}Ian, jesi li OK?
{6487}{6514}Evo me za trenutak.
{6517}{6541}zvat æu...
{6544}{6634}Vrati se u  kajak.|Vrati se u kajak!
{6637}{6671}Mislim da je bio tim.
{6675}{6762}Pa, ne budi lud, vrati se!|-To mu uvijek govoriš.
{6765}{6902}Na tvojoj glavi je.|-Gubimo svjetlo. -Opusti se. Sve je OK.
{6908}{6934}U redu.
{6987}{7022}Ian!
{7279}{7316}Da, samo naprijed!
{7423}{7482}Što se dešava?|-O, ništa.
{7485}{7509}Vjerojatno.
{7520}{7559}Vjerojatno ništa.
{7667}{7690}Gdje je Charlie?
{7693}{7714}Vidiš li ga?
{7717}{7753}Stvarno æu te ubiti.
{7774}{7815}Jel taj luðak živ?
{7818}{7861}Do sada. -Do sada?!
{7983}{8007}Daj mi još šampanjca.
{8010}{8137}Možda je moguæe, i bit æe interesantno slikati kajak|ispred kamere. Vjerojatno æe biti opasno i jebeno neuspjelo.
{8141}{8169}Naravno da je moguæe...
{8172}{8232}samo trebaš iæi|brzo iza njega...
{8235}{8366}Ovo je vrlo dobra slika svijeta gdje|ne postoji gravitacija. U ovom svijetu
{8371}{8393}ona postoji.
{8396}{8445}Slikat æeš na moj|prokleti naèin.
{8454}{8503}Isprièajte me.|U redu.
{8514}{8546}Na tvojoj glavi je.
{8549}{8640}Morat æeš to objasniti klijentu.|- Briga me. Samo da završimo.
{8643}{8675}Opet?
{8825}{8853}Spremni smo.
{8856}{8880}I...
{8894}{8926}Akcija!
{9351}{9367}OK, jesi li spreman?
{9370}{9431}Navali, vuci.... snimaj.
{9451}{9494}Brže, brže.
{10324}{10346}Odlièno.
{10844}{10941}G. Imahara, nije moja greška, probao sam |po dogovorenom.
{10944}{11036}Ovaj režiser odluèio je |da ide po njegovom.
{11038}{11076}Možete li se pobrinuti da g....
{11186}{11257}Sviða mu se. Misli da je lavina |prava stvar.
{11290}{11322}Fino.
{11431}{11458}Hvala.
{11491}{11641}O, i recite g. Imahari da ne radimo|lavinu sa digitalnim efektima.
{11644}{11688}Mi to radimo stvarno.
{11691}{11711}OK.
{11878}{11912}OK, OK... OK, OK, OK.
{11915}{11940}Moje gledište
{11943}{12046}Ne, ne, ne... Jeffrey, imamo 25 sekundi|da doðemo do mog gledišta!
{12050}{12078}25 sekundi?
{12081}{12153}Da, poanta je doæi do |opasne zone.
{12156}{12231}Smisao je da imaš 50:50|šansi da te ispustim.
{12234}{12271}Više kao 60:40, Jeffrey.
{12274}{12339}Hej, Jeffrey, podigni |malo glavu.
{12343}{12456}Još malo. -To su otprilike iste šanse |da skijaš na lavini i ostaneš živ.
{12459}{12509}Sada, što sam ja trebao|napraviti?
{12512}{12600}Nemao ni novac ni vrijeme da to|napravimo s elektronskim efektima.
{12603}{12691}Imam sjajnu ponudu|u malom mjestu u Austriji.
{12694}{12768}Mislio sam da to želiš napraviti|stvarno.
{12771}{12799}Zašto mi onda nisi|to rekao?
{12802}{12844}Rekao sam ti |unutra.
{12847}{12925}Kada smo osnovali kompaniju Jeffou,
{12928}{13041}Pristao sam da se ne miješam u stranu posla,|a ti da se držiš strane kreativnosti.
{13044}{13106}Ti si donio odluku kojom si se |umiješao u moju stranu posla.
{13109}{13168}Poèeo sam na svom |dijelu posla.
{13171}{13253}Misliš da si u poziciji...|- Ne, ne, ne. Žao mi je.
{13256}{13345}Obeæajem ti da neæu| prijeæi u tvoju
{13348}{13405}stranu nikada|više.
{13408}{13459}Da ga podignem?| - Da, OK.
{13466}{13505}U redu, podižem.
{13596}{13644}Vi ste opièeni.
{13777}{13843}Ne znam. Što ti misliš?|- Mislim da æe biti luda zabava.
{13876}{13921}To ja mislim.
{13924}{13973}Znaš što ja mislim.|- Slušaj...
{13978}{14078}Dat æu ti sve što treba osim jedne|stvari, da ne ideš ti.
{14099}{14139}Tko æe ti onda to|napraviti?
{14190}{14239}Ne znam. Flaky?|- Ne.
{14242}{14271}Imaš li ti nekog?
{14302}{14314}Da.
{14317}{14352}Znam neke ljude.
{15661}{15716}Kreæemo za Austriju za tri |dana, deèki, pa...
{15754}{15805}Da, hajdemo se probati|naæi u Parizu.
{15827}{15872}Da se osiguramo.
{15906}{15928}Što ti misliš?
{15937}{15959}Ian...
{16001}{16036}Samo mi reci što ti|misliš o tome.
{16064}{16075}Samo trenutak,|draga.
{16078}{16228}Ovo je Ian Fintack.|On æe biti režiser, a ovo je Chloe Western.
{16231}{16277}Dobitnica zlatne medalje|u spustu.
{16283}{16314}Amerièka ljepotica.
{16317}{16339}Bok.|- Bok.
{16353}{16385}Drago mi je što æe mo|saraðivati.
{16408}{16449}Let za Austriju 431....
{16452}{16476}Jeffrey.|Za Beè.
{16522}{16557}To je naš, hajdemo.|Sada se ukrcava pisti 24.
{16560}{16577}Jeffrey?
{16779}{16808}Halo.
{16828}{16855}Ja sam Will.
{16934}{16959}OK?
{16969}{17014}Ti si momak koji æe me|nauèiti skijati?
{17052}{17100}Reci... da.
{17146}{17187}Nešto si mekan |tu u sredini.
{17246}{17258}Priði.
{17501}{17520}Reci.
{17547}{17585}Imaš li neke lekove?
{17604}{17623}Èega?
{17626}{17659}Midol, Advil.
{17723}{17781}Èovjeèe... imam grèeve i krvarim|kao zaklana svinja.
{17877}{17928}Pa... javi mi ako naðeš nešto|korisno.
{17946}{17963}U redu.
{18055}{18107}Izgleda da se tvoj deèko|Silo nije pojavio.
{18115}{18135}Bit æe on ovdje.
{18138}{18158}Silo?
{18161}{18189}Hej, poznaješ ga?
{18198}{18223}Pomalo.
{18226}{18283}Hajdemo samo reæi da on nije tako| mekan u sredini kao ti.
{18540}{18583}O... Silo.
{18663}{18698}Što ima, kuèke?
{18783}{18828}Stavite prvo malo više u |ovu èašu.
{18831}{18902}Želite li?|- Ne hvala. -Dosta mi je jedna.
{18928}{18938}Jeffrey..
{18942}{18998}bit æu iza.
{19057}{19115}Režiser se izgleda nije razveselio|što me vidi.
{19123}{19192}O, možda je samo preplašen.
{19195}{19271}Na njegovoj polici nisam vidio |mnogo zlatnih medalja.
{19530}{19581}Zato što je Jeffrey |prokleti idiot.
{19593}{19702}Dovoðenje Chloe neæe dati lavini|digitalni efekt. Sada  tek nemamo šanse.
{19713}{19735}Odlièno.
{19763}{19791}Hey, koji je tvoj problem?
{19800}{19874}Hoæeš li gledati svoja posla, OK.|- O, u redu. - Oprosti.
{19878}{19898}Samo...
{19923}{20009}opusti se. Makni taj prokleti|paket s leða.
{20039}{20056}Ne mogu.
{20059}{20083}Zašto?
{20106}{20142}To je moj |padobran.
{20222}{20242}Tvoj što?
{20279}{20344}Moj padobran.|Nikada ne znaš kada æe ti zatrebati.
{20347}{20390}O, g. Ludi se plaši|letenja?
{20396}{20461}Gledaj. Volim stvari koje mogu ja|kontrolirati, OK.
{20464}{20549}Milijun tona metala na |60000 fita od zemlje.
{20557}{20636}Pa... ako biste mogli gledati|svoja posla.
{20703}{20753}Hej... èitaj ovo.
{20756}{20794}Da ne bi mislio na to.
{20922}{21047}Avion srušen. Srpski ratni zloèinac-|Ubijen. - Isuse...
{21050}{21082}Ja o tome ne bih brinuo.
{21086}{21157}Ovaj tip je zao. Osjeæam to.
{21177}{21230}A jesu li i ostalih 200 |što su umrli?
{21245}{21270}Jesu li oni bili|zli?
{21273}{21322}Nisu,upravu si,|gotovi smo.
{21391}{21480}Austria, Karawanken Range
{21531}{21630}Samo da rašèistimo. Chloe Western| neæe skijati u mojoj reklami.
{21643}{21816}Slušaj me, koliko ljudi zna skijati na lavini? Chloe nije|jedna od njih, olimpijada te ne priprema za tako nešto
{21899}{21965}Možemo li se koncentrisati na samo |jednu tvoju opsesiju?
{21968}{21997}Naravno. |- Kako god.
{22000}{22065}To je tvoja strana posla i povlaèim se.|Po dogovoru. -Odlièno.
{22069}{22107}Zašto si je onda |doveo?
{22164}{22238}Ona je dio ugovora.|Ona mora biti u reklami.
{22272}{22326}Saèekaj zar se nismo |dogovorili?
{22345}{22475}Zbliži se sa njom. On æe| skijati još dosta vremena. Oprosti.
{22478}{22551}Morat æeš promijeniti mišljenje.|- Pa, to me ne iznenaðuje.
{22554}{22630}Ali moram te upozoriti,|prilièno je nezgodna.
{22633}{22664}Jel tako?
{22728}{22763}Pozdravi i Stacy u moje ime.
{22766}{22788}Da?
{22791}{22819}Iz Amerike?
{22826}{22849}U redu.
{22852}{22870}Pa..
{22874}{22902}dalaziš li u Europu?
{22955}{22979}Zašto ne?
{23041}{23072}Stace?
{23180}{23250}Stace, sranje.
{23266}{23356}Ian... možda bi volio...|ovo vidjeti?
{23505}{23535}Problem.
{23688}{23732}Dva problema.
{23875}{23904}Navali.
{23986}{24046}Will, Will, hvataš li ovo?
{24089}{24132}O, naravno, bit æe OK.
{24380}{24405}Lijepo.
{24522}{24596}Ovo je ludo.|-Da, naravno da je ludo.
{24599}{24665}Kao i skijanje niz|lavinu.
{25256}{25316}Dobro je!
{25660}{25708}Ti mora da si Zoro, |jel' tako?
{25722}{25770}Zoran.|-Kako god.
{25773}{25829}Jel nam stigla oprema?|- Da, juèer.
{25832}{25865}Donijet æu ti je |sutra.
{25868}{25929}Odlièno.Hajdemo u hotel.|- Ne,  u helikopter.
{25957}{26060}Ne...|Helikopter... poslije... hotel.
{26063}{26166}Ne, prvo helikopter poslije hotel.|Lijepo je vrijeme.
{26249}{26324}Hoæe napraviti sada dio, prije nego| što se vrijeme pokvari. Hajdemo.
{26327}{26374}Pa zašto nam onda nije|rekao to?
{26377}{26447}Idemo gore sada. Vidjet æemo se|kasnije.
{26453}{26500}A što da mi radimo?|- Ne znam.
{26515}{26544}Nisam pametan.
{26569}{26593}Oprostite, deèki.
{26668}{26704}Hajdemo na piæe.
{26748}{26791}Daj ovamo. |Èekaj, èekaj...
{26801}{26841}Ne, sama æu.
{27241}{27273}Yo, Zoro...
{27310}{27362}Jel' ima još puno do|helikoptera?
{27365}{27388}Da.
{27411}{27508}Vi ovdje nemate....|èetverokotaèe?
{27518}{27614}Skimobile.... ili jakove?
{27617}{27639}Da.
{27659}{27700}A mi hodamo?
{27728}{27753}Da.
{28095}{28145}I nikada nisi èula za|mene?
{28175}{28224}Ne, jesam li |trebala.
{28227}{28327}Pa ja sam osvojila zlato u spustu|na olimpijadi.
{28330}{28359}Olimpijada?
{28380}{28409}Što je to |olimpijada?
{28412}{28437}Ja ne znam.
{28440}{28495}Osvojila sam zlato u |spustu.
{28498}{28529}Koje je boje?
{28532}{28607}Èekaj, to je kad skijaš odozgo na|dolje niz stazu kao prije sto godina
{28610}{28777}i nitko ne bude brži milijunti|dio sekunde od prethodnog.
{28807}{28860}Ja zapravo ne mislim da |je to skijanje.
{28863}{28926}Stvarno? A što misliš da je?
{28929}{28946}Dosadno.
{28949}{28967}Neprivlaèno.
{28970}{28997}Glupo.
{29014}{29066}Èekaj, ponovi mi pitanje?
{29074}{29133}Pitanje je - što ja uopæe tražim s|vama dvoma.
{29169}{29192}Izvoli.
{29205}{29221}Evo.
{29260}{29286}Evo...
{29289}{29348}Prièekaj. - Hej... kul... u redu.
{29351}{29389}Živjeli!
{29780}{29811}Tu je odlièno.
{29827}{29891}Trebat æe dve eksplozije|da bi lavina došla do dolje.
{29894}{29951}Ima dosta mjesta da proðe|lavina.
{29985}{30015}Što je to?
{30028}{30051}Odmaralište...
{30055}{30089}Odmaralište?
{30092}{30131}Nije završeno.
{30135}{30170}Što? Ima li koga?
{30173}{30199}Srbi.
{30212}{30233}Što?
{30236}{30311}Radnici. Idu do same granice|sa Jugoslavijom.
{30314}{30356}Slušaj. Možemo li tu|odsjesti?
{30359}{30381}Moguæe je.
{30390}{30408}U pravu si.
{30411}{30507}Nikako. -Zašto? Tu æe mo i raditi.|Bit æe nam puno lakše.
{30510}{30618}Ti si kreativac, ja vodim posao,|a gdje odsjedamo moja je briga.
{30879}{30939}Austria!
{30982}{31027}Jeste li spremni?
{31051}{31082}Navali!
{31413}{31488}Ne, ne, ne.... To se nismo| dogovorili.
{31498}{31544}Reci mu da se tako nismo|dogovorili.
{31699}{31754}Kaže da se cijena promijenila.|Ne može ništa uèiniti.
{31757}{31800}To je sranje.
{31821}{31962}Reci im da sam ja veliki producent|koji radi veliku reklamu.
{31967}{32046}I hoæu jebene cene koje smo |dogovorili.
{32194}{32250}Morate mu oprostiti.|Malo je nervozan zbog operacije.
{32254}{32299}Koje operacije?
{32325}{32372}Na njegovom |mališanu.
{32377}{32405}Mališanu?|- Da.
{32408}{32466}Nikada nije spavao sa ženom.
{32481}{32552}Boji se da je ne izgubi.
{32555}{32667}Jedan doktor je rekao da|mu može zamijeniti sa ovnovom.
{32671}{32704}Ali operacija je bila |previše skupa...
{32707}{32756}Nemojte više. Molim vas, |preklinjem vas.
{32759}{32782}Jeffrey.
{32809}{32826}Što je rekao?
{32840}{32900}Rekao je. Da možemo po |staroj cijeni.
{32903}{32935}Odlièno... odlièno.
{32940}{32975}Hvala.
{33104}{33126}Èemu se smiju?
{33129}{33205}Ne znam. Možda je naglasak?
{33213}{33235}U redu.
{33605}{33696}Mogu li dobiti jedan? Ili æe mo planu?|- Da, dobro. Odlièno.
{34185}{34205}Šteta.
{34210}{34231}Što?
{34235}{34272}O... divno.
{34275}{34340}Ja mislim ipak da trebamo biti|na planini.
{34406}{34481}Èovjek æe vas gore èekati.|Njemu dajte novac
{34489}{34528}i pustit æe vas.
{34551}{34610}Što? Ti ne ideš sa nama?|- Ne.
{34613}{34654}Zašto? - Vau... èekaj.
{34657}{34766}Èek, èek, èekaj.|Kako æe nas ovo popeti na brdo?
{34769}{34849}Da se popnete palica na gore.|a da siðete na dolje.
{34852}{34882}A gdje je naša |oprema?
{34885}{34933}Donijet æu je sutra.|Trebat æe mi vremena.
{34936}{35010}Hrana je gore.|Znaèi, gore je gore, a dolje dolje?
{35395}{35471}Isuse Kriste, ubit æe nas?|- Što hoæeš da radim?
{35474}{35586}Da nas ne ubiješ. - Ne vidim da se itko|ponudio da vozi.
{35589}{35619}Ja æu.
{36036}{36057}Hajdemo, deèki.
{36438}{36484}Da, pretpostavljam da smo|u paklu.
{36488}{36515}Zdravo...
{36541}{36587}Imam novac za tebe.
{36680}{36754}Jedan, dva... tri. Uzmi.
{36770}{36798}èetiri, pet..
{36814}{36843}Evo vam mape,|gospodine.
{36855}{36886}Za što?
{37007}{37055}Izgleda kao australijski|kamp.
{37064}{37148}Jesu li oni pravili?|-Stavi drugi komad na roštilj.
{37152}{37222}Austrijski, ne australijski.|-Ti to kažeš.
{37225}{37290}Ovo nije ono što smo vidjeli|iz helikoptera.
{37314}{37348}Ovamo je?
{37368}{37393}Hajdemo.
{38015}{38055}Ne èitam srpski, ali...
{38058}{38116}Vi idite ovim putem,|a mi æemo ovamo, OK?
{38856}{38927}Mjesto je slatko.|- Hej, ne poèinji sa mnom.
{38930}{38992}Ne bi bili u ovoj frci da nije bilo|tebe i...
{38995}{39055}one maèkice.|- Ohladite.
{39058}{39082}Sviða mi se ovo.
{39085}{39162}Ne možeš svaki dan ovo|raditi u hotelskom holu!
{39276}{39315}Dobar udarac... da!
{39328}{39419}Deèki, prestanite gaðati|...au.
{39972}{39999}Pogledaj ti ovo.
{40002}{40046}Vjerojatno je |lezbijka.
{40064}{40102}Kako misliš? Mislio sam da si je|kresnuo.
{40105}{40158}Ne... nije moj |tip.
{40194}{40258}Nije tvoj tip, hmm.|- Ne. - Tko je tvoj tip, Silo?
{40261}{40357}Volim oštrije ribe, znaš.|- Kao Chloe?
{40362}{40434}Više kao, moja stara |fantazija...
{40438}{40475}seks sa...
{40486}{40528}TV spikerom.
{40531}{40566}Zajebavaš me?
{40569}{40598}Ne. - Sa TV spikerom?
{40601}{40650}Da. Ne misliš da je kul?|- Vijesti, pa...
{40660}{40781}Nebitno. Sjede sa svojim svežnjem|s perfektnim naglaskom
{40784}{40868}to je... Will, moj prijatelju, avion.
{40967}{40993}Znaš što, Silo?
{41060}{41116}Ne... ovo je avion.|- Vau.
{41119}{41140}Tko je ona?
{41143}{41182}Koga je briga.
{41191}{41229}Što misliš gdje ide?
{41277}{41315}Isto gdje i mi.
{41549}{41593}Možda ima neke |prijateljice.
{41619}{41662}Èekaj.... Imam|ideju.
{41665}{41696}Što?|- Hajde.
{41985}{42014}Što vidiš?
{42088}{42127}Mislim da joj je to |otac.
{42176}{42195}Znaš...
{42199}{42260}Dio mene misli da joj je| to otac.
{42264}{42294}To je kul.
{42359}{42390}Što dugi dio |misli?
{42394}{42437}Drugi dio misli | hmm...
{42500}{42548}Psi!
{42555}{42602}Trèi!|- Mrzim pse.
{42844}{42887}Hajde!|Idi tamo!
{43089}{43119}Brže!
{43403}{43431}Ima ih svuda!
{43459}{43496}Drugim putem! Drugim putem!
{43537}{43580}Ovuda. Ovuda.
{43606}{43623}Èekaj.
{43892}{43955}Hajde! Hajde!...
{44095}{44123}Dolaze!
{44645}{44668}Hoo... uspjeli smo.
{44671}{44737}Kako si mogao postaviti takva pravila|, ti bezopasni gade?
{44765}{44802}Nitko nje znao.
{44805}{44829}Oni su znali.
{44842}{44875}Njima vjeruješ, meni ne?
{44878}{44951}Oprosti, morali su znati.|Morali su minirati avion.
{44954}{45021}Moralo je biti uvjerljivo |da sam i ja na njemu.
{45024}{45102}Zaglavljena sam u ovom odvratnom|selu cijeli dan.
{45106}{45173}Zašto mi netko nije rekao|što trebam raditi...
{45176}{45206}kad doðem ovde!
{45209}{45266}Nije bilo sigurno |za nas.
{45308}{45367}Nisam htio da imaš dva|roðendana.
{45416}{45451}Mrzim te!
{45454}{45536}Mislio sam da æe ti biti drago |što sam živ. - Bilo mi je.
{45564}{45594}Ali sada te |mrzim.
{45613}{45640}A sada?
{46042}{46068}Van...
{46168}{46192}Van!
{46565}{46600}Gdje æeš?
{46604}{46635}Ne mogu zaspati.
{47111}{47134}Hej.
{47158}{47195}Što ti radiš ovdje?
{47203}{47233}Nisam mogao zaspati.
{47288}{47322}Mogu ti se pridružiti?
{47356}{47383}Kako god |hoæeš.
{48658}{48686}Baš je kul, ha?
{48787}{48827}Tako mekano,| Willy.
{50013}{50047}Odlièno. Hvala.
{50052}{50082}Hvala ti puno.
{50138}{50177}Amerièki filmovi?
{50215}{50239}Ne.
{50248}{50310}Napravimo film.|Pravimo reklamu.
{50313}{50340}Reklamu?
{50352}{50389}Što ima!
{50403}{50451}Gledam igru. Tri na jednog.
{50454}{50483}Oprosti, što?
{50486}{50551}Ovo mjesto je smiješno.|- Mogu ti pomoæi.
{50583}{50639}Nema kablovske, nema TV-a...
{50643}{50721}Nema grijanja. Da se|smrzneš.
{50743}{50792}Doðe ti da odeš živjeti|u Kanadi.
{50810}{50839}Zabavljaš se, je li?
{50842}{50873}Da.
{50988}{51031}To sam i ja mislio.
{51035}{51085}Ne možeš prièekati da odeš|gore?
{51095}{51142}Da, idem po naše stvari.
{51940}{51980}Ne mogu prestati|misliti na nju.
{51983}{52028}Hoæeš li pretati|razmišljati svojim?
{52049}{52127}Nema više noænog skijanja.|Jesi li me èuo?
{52159}{52207}U redu.|Pogledaj je...
{52210}{52229}Zar nije vruæa.
{52232}{52268}Pusti je, èovjeèe.
{52273}{52318}Slušaj, ne poznajemo| ove planine... i kada krenemo
{52321}{52400}ne mislimo na ribe. Jel' tako?|-Da.
{52403}{52436}U redu!?|- Da!
{52601}{52621}Kako ti izgleda?
{52624}{52659}Morat æemo iæi višlje.
{52681}{52709}Je li gore udubno?
{52712}{52737}Njemaèki je...
{52740}{52776}nikada nije udoban.
{52972}{53018}U redu, deèki i cure.
{53029}{53086}Tu su stvarèice koje smo|èekali.
{53100}{53149}Vaši planinski prsluci,
{53162}{53237}sonarni transmiteri... maske|za kisik.
{53250}{53285}To je za djevojèice.
{53292}{53311}Gledaj...
{53325}{53399}Nije mi lako priznati, ali|èinjenica je..
{53405}{53518}Zadnjih 24 sata sam zavolio svakog od vas.|Bit æe prilièno visoko i opasno gore
{53521}{53574}i ako vam se nešto desi|nikada sebi ne bih oprostio..
{53577}{53625}naroèito da se tebi desi|nešto, Silo.
{53636}{53708}Tvoj šarm baca èini|na mene.
{53756}{53784}Odjebi.
{53808}{53834}Hajdemo.
{54220}{54237}U redu.
{54240}{54259}Napred!
{54371}{54403}Prati me!
{54548}{54595}Ispod smo dozvoljenih|sto metara.
{55813}{55851}Ovo je divno.
{56911}{56957}Odlièno, što æemo raditi?
{56964}{57013}Radit æemo snimak|sa strane.
{57019}{57050}Cijelog dijela
{57054}{57103}jureæi iza tebe.
{57734}{57756}Je li dobro?
{57759}{57791}Spremi se - kreni!
{58192}{58229}Kittie... naprijed!
{58862}{58952}Odlièno. Naprijed.|Vrijeme je za spust prije nego završimo.
{58990}{59025}A što da ja radim?
{59028}{59067}Kreni Chloe.
{59134}{59200}Kopile.|- Èujem te.
{59204}{59240}Da, znam.
{59301}{59328}Deèki, kako ide?
{59331}{59356}Ide odlièno.
{59358}{59415}Snimit æemo lavinu.|Hoæeš sa nama?
{59418}{59473}Ne, ne, ne...
{59624}{59682}Koji ti imaš problem|sa mnom?
{59715}{59749}Hoæeš znati moj |problem?
{59752}{59829}Samo pomisli na cijeli dan gore dolje|niz planinu.
{59872}{59915}Ja to mogu.
{59917}{59977}Ne možeš izaæi na kraj |sa promjenom debljine snijega.
{59981}{60090}Ne možeš nas pratiti.|-Mogu napraviti sve što pomislim.
{60108}{60171}Stvarno želiš znati kako|izgleda kad se skijaš niz lavinu?
{60245}{60266}Da.
{60348}{60379}Jesi li sigurna?
{60387}{60412}Da!
{60426}{60458}U redu.
{60468}{60500}Tražila si.
{60510}{60532}Hajde.
{60598}{60628}Blagoslovljen ti put.
{60753}{60780}U redu.
{60794}{60823}Spreman, Mark?
{60997}{61027}Zoran?
{61291}{61343}Will... jesi li na mjestu?
{61358}{61391}Sranje!
{61401}{61421}Što?
{61452}{61511}Ništa.|- U redu, podigni je.
{61529}{61553}Spremna.
{61580}{61639}To nije neophodno... |Hvala.
{61645}{61675}U redu, ti si |šef.
{61678}{61757}Zoran, uzleti.|Will, Mark, hajdemo!
{61865}{61899}Luðaci.
{61902}{62012}Tri - dva - jedan |- KRENI!
{62505}{62534}OK.
{62751}{62764}Ian..
{62767}{62852}Skoro je dva put bolja od oèekivanog.|- Niže, Zorane. Zorane, niže, niže!
{62930}{63010}Ian, lavina je krenula.|Odbit æe se od dolinu.
{63088}{63163}Radi ono što znamo, Ian.|- Samo još sekundu.
{63166}{63190}Podiæi æu vas više.
{63313}{63358}U redu, pogledaj, pogledaj!
{63361}{63443}Vraæa mi se. Prijeæi æe nas.|- Bože!
{63581}{63656}Will, lavina ti dolazi.|Samo obriši nos.
{63659}{63693}Bok, bok...
{63716}{63742}Što?
{64395}{64446}Hej, Will jesi li|uhvatio vrijeme?
{64480}{64563}Bit æe 3,2 sekunde.
{64598}{64655}Probaj|iskulirati.
{64666}{64710}U redu!
{64777}{64821}Nisam siguran,|ali mi se sviða...
{64947}{65037}- To je lijepo. - Uhm.|- Apsolutno prelijepo.
{65064}{65098}Hej, što æemo sa Choe?
{65151}{65256}To je Chloe.|- Sranje...
{65322}{65373}Mogu ja to, ha?
{65513}{65619}- Jeste li u redu vi tamo?|- Radi... -Dobro uèinjeno.
{65804}{65869}-Jesi li OK?|- Da.
{65987}{66088}-Jesam li ti rekla da sam svirala|u bandu? - Ne
{66125}{66235}- Jel' te zanima kako su se zvali?|-  Ne baš.
{66289}{66443}Veliki band... Obožavam to. Imali smo|samo tri pjesme
{66443}{66509}ali smo ih mogli svirati|satima. Dosta buke...
{66509}{66578}i samo vrištanje!
{66642}{66725}Nekad je stvarno bezveze
{66736}{66821}Ali nekada ispadne |dobro..
{66850}{66916}Jel' me ti to pokušavaš|oraspoložiti?
{66916}{66972}Ne, samo prièam o| muzici.
{67119}{67278}Ja sam dobar skijaš.. |Ne znam što se tamo desilo.
{67278}{67344}Ne znam, možda bi trebala malo|osluhnuti.
{67347}{67382}Pusti da ti planina kaže što da|radiš..
{67386}{67490}-Ali zar se ti nikada ne uplašiš?|-Dovraga, da, to je najbolji dio.
{67586}{67595}Što ima?
{67598}{67689}Da, prièamo o tome|kakav si davež.
{67747}{67845}U redu...|Imam vam nešto za pokazati.
{67868}{67952}- Hoæeš da pogledamo?|- Zašto ne..
{68108}{68154}- Kako si je zagrijao?|- Pazi..
{68154}{68262}- Vruæ kamen ide, u-hu...|- O, kul..
{68262}{68282}Ne.
{68440}{68662}To je hladno.|Izvolite. Još kamenja.
{68692}{68790}Samo nam reci što nije u redu. |Reci mi...
{68790}{68867}Da, zašto nam bar ne daš |drugu šansu?
{68905}{69002}Što? To ne mijenja moje|osjeæaje prema tebi, Stacy?
{69062}{69168}Ne, ne ti. Telefon je...
{69168}{69276}Draga, samo kažem ne mijenja. I...|Ma hajde. Nije to...
{69417}{69469}Hej, jesi li OK?
{69496}{69596}- Potrebno mi je piæe.|- Imam samo ono što je zubar naredio...
{69596}{69659}Doktor. Ono što je|doktor naredio.
{69774}{69932}Trebao bi mi suši i kozmetièar|i pedikir... Sranje!
{70311}{70392}- Hej, Smješko. Uzmeš sok i napraviti.|- Da? To je pravilo.
{70392}{70438}- Jel' tako?|- O, definitivno.
{70438}{70507}-Hajde, neæe biti tako loše|- Hmmm... Bože.
{70544}{70652}Hmmm, završimo s tim.
{70717}{70765}- O, da! O tome ti prièam.|-  Prelijepo!
{70765}{70824}Žvaka, ha?
{70888}{70926}- Pij!|- Moje divne damice.
{71362}{71509}OK, Hoæu da izaðeš, valjaš se po snijegu,|odeš uz i niz onaj konopac.
{71626}{71652}Ništa lakše.
{71655}{71678}Gol...
{72390}{72460}Pij!
{72482}{72608}- Treba nam još piva.|-Izvoli.
{72629}{72718}Moram piškiti.
{73452}{73525}- Hej, sinoæ mi je bilo|lijepo.
{73608}{73740}-Znaš, ti, ja, planine...
{73740}{73809}- Zajedno. Znaš ono, |kao odrasli.
{73816}{73992}- Jesi li osjetila?|- Hmmm... - Jesi?
{74022}{74200}- Osjetila mekano..|- O, upravo sada.. Bok.
{74335}{74409}- Hej, kuda æeš?|- Daleko.
{74488}{74551}Da... Èekaj.
{74551}{74650}- Što ti misliš da radiš?|- Ja sam...
{74650}{74751}- Ova kada - samo za dame..|- Da, ne mislimo biti grube.
{74772}{74832}Pa-pa..
{74866}{74930}Hej, prijatelju, prièekaj.
{74939}{74995}Evo, uzmi još jedno.
{75516}{75681}- Bok. - Bok.|- Mislim da si bio u pravu za mene.
{75774}{75893}- Da?|- Da. Nije mi mjesto ovdje.
{75912}{76014}To je bilo |ponižavajuæe.
{76024}{76125}Nisam graðena kao vi.
{76136}{76234}Mislim da sam bila previše|tvrdoglava.
{76321}{76457}Sve što radim su natjecanja|i treninzi.
{76483}{76550}Svi  ti moji, treneri|agenti.
{76550}{76694}Ovo sam radila zbog para i prestiža,|ali ustvari ja sam...
{76830}{76892}Znala sam tko si.
{76986}{77130}I mislila sam da se bar|jednom u životu mogu
{77203}{77275}skijati iz zabave.
{77321}{77442}Ali oèigledno da nisam sposobna.|I sada sve...
{77442}{77460}O, sranje!
{77460}{77585}Sada se cijela stvar pretvorila|u katastofu.
{77609}{77678}Možda si samo |malo pijana.
{77715}{77803}- Ne.|- O, OK.
{77880}{77930}OK, možda samo |malo...
{77945}{78009}Kittie me htjela malo|oraspoložiti.
{78020}{78110}Uspanièila sam se, izgleda da ni|to ne znam napraviti.
{78110}{78118}Ne budi tako oštra prema|sebi.
{78139}{78232}Gledao sam kako skijaš. Ti si|odlièna skijašica.
{78287}{78352}- Stvarno?|- Ma hajde, ti imaš zlatnu medalju..
{78387}{78427}Imaš zlatnu medalju.
{78496}{78564}- Hoæeš je vidjeti?|- Što?
{78614}{78701}O, OK.|Nisam znao da je nosiš.
{78735}{78772}Ovo je zlatna medalja.
{78789}{78855}Da li znaš koliko sam naporno|radila da je dobijem?
{78985}{79056}Uffff, znaš što? Malo| mi se vrti.
{79056}{79126}Da, trebala bi odspavati.
{79149}{79167}Da.
{79167}{79302}A ovisno kako se ujutro osjeæaš,|možda bi se trebala zagrijati, ha?
{79358}{79524}- Stvarno?|- Da. - Hvala.
{79634}{79701}Prošlo mi je |štucanje..
{79751}{79877}- Uups. Vratilo se.|- Laku noæ!
{80155}{80218}Ušuti! I ti..
{80538}{80600}Ovo je za europsku verziju.
{80676}{80726}Naravno.
{80729}{80787}Hej, to je ona djevojka| iz vlaka.
{80809}{80900}- Zašto se ljubi s ocem?|- Ovog znam odnekud.
{80900}{80939}U redu, nije zezanje.
{80974}{80997}Hajde.
{81002}{81082}Što je s torbama, Jeffrey?
{81130}{81255}- Koje torbe?|- Ah, te torbe. - A da.
{81271}{81332}Uzimam slobodno. Nisam ti rekao?
{81343}{81456}- Ne, nisi.|- O... Pa, uzimam slobodno.
{81470}{81562}Ostavit æeš nas ovdje,|je li?
{81562}{81652}Ne, ne. Bit æu tu. Dolje... |blizu u selu.
{81652}{81689}To je divno.
{81689}{81766}- Sjeæaš se hotela gdje smo odsjeli?|- Hmm hmm. - A taj.
{81766}{81802}Bit æu tamo.
{81815}{81849}Ispostavilo se da ima malo
{81849}{81888}više novca u budžetu.
{81888}{81940}Lijepo.
{81940}{82139}- O, bolestan sam.|- Ne, ti si budala. - Što god.
{82158}{82273}Znam da su CIA, tata.
{82273}{82348}- Mogu ih namirisati.|- Paranoièan si.
{82359}{82395}Zašto bi me itko tražio?
{82416}{82470}CIA misli da sam |mrtav.
{82470}{82550}Nema smisla doæi ovdje|da snimiš reklamu.
{82561}{82735}Iz istog razloga kao i mi.|Prelijepo. I nitko ne zna za njega.
{82735}{82806}Šah... |Mat...
{82806}{82927}Slušaj me, mogu te vidjeti. Razumiješ?|Ako te vide...
{82927}{83005}Svi naši planovi odoše|dovraga.
{83005}{83092}Ako ne raznesemo sud u Nizozemskoj|u roku od dva dana..
{83092}{83240}Sve æe saznati. I naši ljudi æe biti|zatvoreni do kraja života.
{83240}{83337}A ti... Opet bježati.
{83337}{83441}Zašto da riskiramo? Zašto ih jednostavno|ne ubijemo?
{83468}{83502}Volim ovog momka..
{83577}{83668}Isti tata. Bog ga blagoslovio.
{83713}{83785}Mislim da imamo...|problema
{84004}{84132}Ne, neæu djeèaka, hoæu djevojku.|Plavušu, dobro graðenu.
{84192}{84251}Deèki, idemo li?!
{84298}{84361}Kasnim. Torbe su mi ovdje..
{84361}{84480}Imam zakazanu masažu za sat i pol.|Zato hajdemo.
{84483}{84529}Krenimo na put.
{84552}{84581}OK!
{84684}{84788}- Što?|- Što što?
{84837}{84917}Hajdemo na posao prije nego vrijeme|sve upropasti, OK?
{84917}{84985}Veæ je upropastilo.
{84985}{85069}- Ako na završimo danas |probijamo rok. - Vau.
{85086}{85168}Samo provjerava... Tako da sam|siguran.
{86323}{86452}U redu, deèki i cure...|Nizak spust ide na 3 - 8 - 3
{86452}{86511}mora biti toliko.
{87570}{87637}U redu, 30 sekundi|ravno.
{87637}{87689}- To mora da je to.|- Završeno, Ian. - Uspjela sam.
{88339}{88402}Dobro jutro.
{88412}{88559}Za vas možda ne |toliko dobro.
{88742}{88799}Gdje je traka?
{88821}{88858}Koja traka?
{89572}{89639}Sranje!
{89917}{90018}Ima laptop.
{90030}{90093}Zašto si mi snimao oca?
{90093}{90163}Gledaj, nitko ne zna o |èemu prièate.
{90328}{90440}- Ti CIA?|- Što sam ja?
{90476}{90594}- CIA.|- Naravno, Hollywood.
{90868}{90954}Mala princezo, odgovori |na pitanje..
{90954}{91056}Zašto je ne ostaviš |na miru?
{91056}{91105}Ti si deèko.
{91145}{91252}Slavko, što to radiš?|Vodimo ih nazad.
{91252}{91466}Ne, princeza ljubi svoga deèka kao|u vruæoj kupci. Pusica, pusica, la la la.
{91538}{91642}Hej, ništa nisu napravili. Hej.|Smiri se.
{91665}{91726}Meni prièaš?
{91726}{91793}Dovraga, koji je tvoj |problem, ha?
{91993}{92059}Polazi, polazi.
{92090}{92170}O, oprosti, tako mi je žao.
{92196}{92242}Ustani. USTANI!
{92319}{92404}Sad, skini svu odjeæu.
{92433}{92515}Hajde... Slikaj sretan par.
{92515}{92592}Što radiš, bolesni?!
{92622}{92694}Hehe, bolesni, ali s puškom.
{92728}{92797}Slavko! Dosta je!
{92797}{92830}Vraæamo ih!
{92846}{92921}Igrat æu se s njima.
{93224}{93313}Hajde, pusti ga da se obuèe.
{93313}{93353}Ne, poljubac..
{93364}{93473}Fino, jesi li sretan,|pusti ga da se obuèe!
{93491}{93563}Više ljubavi. Više ljubavi.
{93596}{93675}Will, obuci se.
{93727}{93829}Što? Hoæete da se obuèem, ha?|Jebeno je hladno da bi imao jaknu.
{93829}{93933}Sve æu skinuti. Što misliš o |ovom, ha?
{93933}{93992}Evo ti! Ovo hoæeš?
{93992}{94087}Jebena jakna!|Zašto ne zaplešem havajski.
{94244}{94327}Poljubac! Poljubac!
{94394}{94437}Dosta je!
{94537}{94585}Što to radiš, Ivo?
{94608}{94645}Ovo je bolesno.
{94645}{94700}Ja sam vojnik.
{94700}{94770}Vežemo ih i odvedemo...
{94770}{94815}ili ih ubijemo.
{94815}{94961}Kada moj otac sazna da s uperio|pištolj u mene, Ivo.
{94961}{95055}Tvoj otac je vojnik.
{95260}{95414}Spusti svoj pištolj, Ivo.
{95414}{95480}Ne... spusti tvoju pušku.
{95480}{95590}Kažem spusti svoj pištolj!|To je zapovijed.
{95713}{95786}- Sranje!|- Bože.
{95995}{96032}Jeste li svi OK?
{96058}{96120}Samo sam, samo sam htio|da vas ostavi.
{96256}{96282}Sranje!
{96288}{96308}Ian?!?
{96319}{96345}Do vraga!
{96353}{96384}Kreni kreni....
{96956}{97028}- Ovaj èovjek je Pavlov?|- Tako je..
{97028}{97187}- Èitao sam o njima u novinama.|- Neka vojska, ali napisano je da su mrtvi.
{97187}{97344}Pavlov ne može poginuti.|Hoæe da svijet misli da je mrtav...
{97344}{97405}tako da može raditi sa|skrovitog mjesta.
{97405}{97468}On je najtraženiji èovjek| ovih dana.
{97468}{97517}- A to mu je bio sin?|- Da.
{97517}{97604}Nadajmo se da se nismo isprijeèili|obiteljskom okupljanju.
{97604}{97674}Nismo ga ubili. Ništa nismo |loše uèinili.
{97680}{97731}O, da? A tko ih je prevario da se|poubijaju, ha?
{97731}{97805}- OK, moramo otiæi odavde.|- Što æemo s opremom?
{97805}{97864}- Što æemo sa Jefreyem?|- Rekao je da ide u selo.
{97864}{97904}On je rekao mnoge |stvari.
{97904}{97989}Iæi æemo po Jeffreya,|uzeti stvari, i izgubiti se odavde.
{98078}{98141}Ivo?! Slavko?!
{98427}{98532}Izgleda da je èisto.|Uzmimo stvari.
{98661}{98716}Što se dešava?
{98743}{98794}Vidio sam te u vlaku.|Sjeæaš se?
{98794}{98896}Reci mu da je pogriješio. |Ništa loše nismo uèinili!
{98935}{99003}- A zašto si me snimao?|- Nisam.
{99003}{99162}Will je. A i nije htio tebe snimiti...|Htio je snimiti tebe!
{99162}{99199}- Mene?|- Da.
{99222}{99257}Zašto mene?
{99257}{99397}Zašto? Pogledaj se.|Prelijepa si.
{99426}{99515}Hoæeš ti biti u reklami?|Ja to mogu srediti.
{99515}{99562}Hej, ja te mogu ubaciti. |Sviðat æe ti se.
{99569}{99658}Moæi æeš se hvaliti|prijateljima.
{99894}{99918}Ivo?!
{99947}{99984}Slavko?!
{100006}{100065}On ne traži nas.
{100113}{100160}Èekaj dok proðe.
{100160}{100220}I potrèi prema vratima, OK?
{100259}{100279}Molim?
{100310}{100332}Polako!
{100424}{100463}Hej, to je Stacy.
{100463}{100512}Siði!
{100544}{100616}OK, oprosti, moj telefon.
{100649}{100691}Mislio sam da je na vibraciji.
{100691}{100729}Naravno.
{100939}{101007}Hoæeš ti prièati s njom? |Mogao bi ako hoæeš.
{101138}{101166}Da!
{101166}{101219}Jeste li OK? Hajdemo.
{101219}{101253}-Ti? -Da.|Hajdemo, požurite.
{101593}{101639}Chloe, požuri!
{101663}{101715}Proklete èizme...
{101715}{101773}Eto ti još jedan razlog što je,|snowboard bolji od skijanja.
{101783}{101815}- Hajde, kreæi, kreæi!|- Hej, èekajte mene.
{102288}{102382}Došao sam razmijeniti neke informacije|za moj život.
{102515}{102594}Ta djeca nisu ono| što mislite.
{103257}{103315}Isuse, što je to bilo?
{103507}{103565}Premostili su kontrole.
{103565}{103606}Oni nas neæe pustiti da| odemo.
{103941}{103967}- Što je ono?|- Što?
{104215}{104261}Ptice u kavezu...
{104298}{104384}Hoæu ih žive.|Prije nego što ih ubijem.
{104469}{104513}Eno ponovo onog tipa..
{104516}{104543}Izgleda da je  nešto|popizdio.
{104551}{104623}Kevin, uzmi svoje stvari, odlazimo| odavde.
{104645}{104713}Ti mora da se šališ!
{104760}{104825}- U redu, razbij te prozore...|- Èekajte, èekajte.
{104990}{105024}Ružièasto.
{105046}{105077}OK OK..
{105082}{105124}Pokret, kreni!
{105192}{105214}Lijep skok.
{105568}{105625}Hej, hej, pucaj!
{106183}{106255}Nastavi, odmah iza tebe| sam..
{106563}{106672}- Ja ovo ne mogu!|- Možeš, vjeruj sebi.
{107269}{107365}- Sranje! Jesi OK?|- Samo što sam je kupio.
{107429}{107474}- OK, dodaj  to meni.|- OK.
{109007}{109045}Ne! Ne!
{109169}{109197}Sranje!
{109396}{109405}OK?
{109405}{109460}Hej, pridrži.
{109608}{109704}Will, uzmi drugi kraj konopca. Omotaj|oko struka.
{109704}{109746}Brzo... požuri.
{109884}{109936}Veži ga èvrsto, dolazim |- OK, hajdemo.
{110232}{110264}Držim te
{110703}{110760}Drži se!
{111269}{111336}Što da sada radimo?
{111451}{111503}Drži se.
{111583}{111648}Will, što to radiš?
{111722}{111751}-Kopile!|- Nisam htio.
{111957}{111998}Mark, jesi OK?
{112039}{112078}Pusti je dolje..
{112236}{112328}Deèki, ima sigurna litica|50 metara ispod.
{112575}{112664}Nastavi, OK? Mogu je vidjeti...
{112728}{112826}Chloe, stavi nogu malo ulijevo. U redu?
{112902}{112966}Ne lijevo, mislio sam desno.
{113016}{113052}O, sranje!
{113270}{113359}Daj mi još malo |konopca.
{113623}{113689}Presijecimo prokleti konopac.
{114280}{114323}Nastavi..
{114323}{114407}Chloe, Chloe, hajde.| Skoèi, skoèi!
{114520}{114566}U redu, evo me dolje.
{114617}{114680}Jesi li OK?
{115959}{115977}Will!
{115998}{116043}Jesi OK?|Will, jesi li dobro?
{116187}{116216}Will?
{116266}{116352}Hajde, što to radiš?!
{116431}{116455}Zaglavio sam se.
{116493}{116569}Povuci! Hajde, vuci!
{116604}{116645}Will, Will?
{116708}{116792}Hej, Kittie, hoæeš li još misliti|da sam mekan
{116792}{116864}ako se žrtvujem zbog tima?
{116864}{116903}Ne mislim da si mekan!
{116903}{116940}Znaèi li to da ti se sviðam?
{116940}{116981}Da, stvarno mi se |sviðaš!
{116981}{117016}Hoæeš li izaæi|sa mnom?
{117016}{117075}Voljela bih! Hajde!
{117110}{117157}Približi se!
{117240}{117290}Uzmi tu kameru!
{117411}{117449}Pavlev, nema goriva!|Moramo nazad!
{117480}{117511}Ušuti! Približi se!
{117531}{117587}- Obeæaješ, u redu?|- Obeæajem!
{117587}{117657}- OK!|- Will, ne! -Ne.
{118106}{118174}Kopile!
{118330}{118361}Ostani tu!
{118389}{118435}Gdje je Ian?
{118435}{118467}Mark.
{118590}{118636}OK, speman. Silo.
{118968}{119010}Približi se!
{119020}{119051}Nemamo goriva!|Moramo nazad!
{119072}{119128}Rekao sam. Približi se!
{119241}{119281}- Ian.|- Hajde.
{119378}{119444}Neæe nigdje otiæi.
{119444}{119491}Nigdje. Nigdje.
{119533}{119602}Prokletstvo... Idi.
{119788}{119826}Pritisni to.
{119858}{119939}Idite odavde prije nego se Slavko vrati.
{119939}{119970}OK?
{119980}{120033}- Nemoj da se pomièe.|- Hvala.
{120087}{120117}Ja æu ostati.
{120117}{120190}Jesi li sigurna?
{120590}{120689}Trebali bismo otiæi sutra.|Kao što si planirao.
{120689}{120762}Oni ne smiju biti žvi.
{120762}{120847}Neæu otiæi dok ih ne vidim|mrtve.
{120847}{120949}Gledali su kako Slavko umire.|Hoæu da vidim kako umiru.
{120949}{121006}Èekaj, koliko...
{121026}{121086}Koliko misliš da se|možemo ovdje kriti?
{121086}{121130}Koliko dugo prije nego |nas netko otkrije.
{121157}{121203}Je li Slavko vrijedan toga?
{121256}{121340}Nemoj više nikada ništa reæi|za mog sina,
{121340}{121401}ubit æu te.
{121807}{121853}Hej! Probudi se!
{121903}{121932}Što je?
{121967}{121994}O, bok.
{121994}{122041}Možeš li me odvesti do|New Yorka?
{122834}{122920}- Misliš da je Willu dobro?|- Da, sigurno je dobro.
{123423}{123457}Uspjeli smo.
{123624}{123672}Mora da se šališ.
{124064}{124104}Imam ideju..
{124402}{124450}Uèini to. Odvuci idiotima|pažnju.
{124450}{124499}Hajdemo.
{124678}{124734}To nam je jedina |šansa.
{124887}{124943}Hajde, Kittie.
{124943}{124968}To je velièine mini busa.
{124989}{125015}Pa u pokretu je.
{125026}{125077}Naravno da je u pokretu.|Što si oèekivala?
{125235}{125286}Promašila si!
{126857}{126894}OK, sada!
{127055}{127076}Tamo!
{127297}{127336}Što se dešava?
{127430}{127503}Jurit æe ih.
{129261}{129379}Vau! Pogodi ptièicu.
{129659}{129764}Evo ti je lavina koju si tražila.|Hajde, idemo.
{130108}{130162}OK, hajde, Chloe.|Osvoji medalju.
{130162}{130216}Slušaj me! Skijaj kao da si na |trci.
{130685}{130824}OK, Chloe, odlièno je! To je ono| što nam treba!
{130903}{131023}OK, iza tebe sam! |Prijeði na desno!
{131057}{131117}Jedan. Dva. Tri.
{131775}{131884}Bila je odlièna, zar ne?|Kao što sam obeæao.
{131930}{132007}G. Imahara hoæe znati|kako je pobjegla od lavine.
{132010}{132032}Pozdravi  Chloe...
{132035}{132066}Zato je ona šampion.
{132070}{132137}Pogledaj kroz prozor!
{133114}{133160}Idemo ispoèetka.
{133350}{133666}Subtitles by:|M O Z E N

