{500}{550}uloge
{940}{1040}{C:$0000FF}{y:ib} ZAGROBNE |{C:$FF0000}{y:b} STVARI 
{3835}{3885}Dovraga!
{3993}{4080}Kako zaspati | po takvoj vruæini?
{4158}{4260}Ja ne mogu spavati | kad mi jebene muhe slijeæu na lice.
{4280}{4400}Da. | Više ih je no lani.
{4425}{4502}Dosad nije | bilo tako grozno.
{4719}{4760}Tisifona...
{4843}{4880}Megera...
{4900}{4950}i Alekto.
{4984}{5025}Erinije.
{5056}{5120}Grèka mitologija.
{5137}{5253}Što ti znaš o grèkoj mitologijii? | Vjerojatno ne izgovoraš dobro.
{5254}{5320}Posudila sam u knjižnici.
{5362}{5430}Mogu ti prièati o tome, ako želiš.
{5482}{5610}Znaš to je mitologija? | - Sigurno da znam.
{5623}{5700}Svatko zna što je mitologija.
{5764}{5850}Zapravo ljudi više u | to ne vjeruju.
{5937}{6025}Tri sata ujutro. | Tko bi vjerovao.
{6063}{6120}Hoæeš ledeni èaj?
{6280}{6329}Jebeno gadno smrdi.
{6330}{6392}Prozor je zatvoren cijele noæi.
{6393}{6520}Trebam zraka. | Što tu smrdi?
{6920}{7009}Mislim da je kriv | proces tehnologije.
{7025}{7085}Zakopala si psa juèer, je li?
{7090}{7160}Ti bi ga ostavio da se raspada.
{7169}{7235}Sigurno ga je netko otkopao.
{7720}{7820}Smrdi jako gadno ovdje.
{8377}{8397}Isuse!
{8398}{8455}O, Bože!
{8515}{8570}Mick?
{8584}{8710}Isuse Kriste, što je to? | - Bolje da ne znaš.
{8880}{8972}Popušio sam! | - Nisi u pravu.
{8973}{9040}Mogli bi upasti u gadne | nevolje ne pozovemo li murjake.
{9040}{9082}Ne zovi policiju. | - Ali Mick...
{9083}{9110}Ne!
{9110}{9181}Mogli bi pogoršati situaciju | ako ne pozovemo murjake.
{9182}{9241}Slušaj, dobro slušaj.
{9242}{9310}Još sam na jebenoj uvjetnoj, |jer sam razbio onog lika.
{9311}{9376}Upamti, nisu bili presretni | kad sam izišao.
{9377}{9421}Ovo samo èekaju.
{9422}{9510}Neæe te okriviti ako si nevin.
{9530}{9610}Tko kaže da sam nevin?
{9611}{9678}Ja sam donio lika | i ostavio, što li?
{9679}{9829}Ne. Nego te ne mogu uhititi | zato što je èovjek naðen na posjedu.
{9850}{9912}Da. | Volio bi znati 
{9913}{9970}koji kurac ga je tu stavio.
{10315}{10370}Bože!
{10516}{10625}Što to radiš? | - Tražim nešto što æe reæi tko je.
{10626}{10725}Nije higijenski. | - Drži mi lampu.
{10938}{10970}Što je to?
{11037}{11070}Ništa.
{11130}{11210}Nešto bi moglo reæi | o tome tko je.
{11538}{11640}Što je to? | - Drži svjetlo mirno.
{11681}{11770}Adresirano na T...
{11771}{11822}Soval...
{11840}{11925}Covaleski. | - Covaleski.
{12038}{12162}Možda njemu, | možda njegovom prijatelju.
{12233}{12320}Popis. | - Kakav popis?
{12341}{12410}Popis imena.
{12440}{12520}Nitko s liste za | kog sam èuo.
{12625}{12680}Reci pa-pa!
{12700}{12750}Pa-pa!
{12787}{12850}Kakav je lik, što misliš?
{12901}{13030}Bio! | Više ne postoji.
{13102}{13195}Postojat æe dotle dok | ga se netko bude sjeæao.
{13260}{13340}U knjizi iz knjižnice si to pronašla?
{14121}{14180}Što? | - Haj, Christine.
{14250}{14280}Tko je to?
{14301}{14460}Uvalila si se u velike probleme. | Kako misliš da znam da si u problemima?
{14498}{14600}Jer sam mrtav, glupa kujo.
{15100}{15190}...bojali su se, a pucnjevi su
{15200}{15264}bili od petardi. 
{15266}{15382}Hej, maleni. | Hoæemo u vožnju ili nekamo?
{15383}{15460}Trebam nešto iz duæana u gradu.
{15520}{15670}Tamo smo za trideset minuta. |Ako zakasnimo,
{15678}{15780}mogli bi u šetnju, ili nekamo.
{16111}{16230}Zašto bi htjela provesti | popodne s ubojicom?
{16348}{16489}Misliš nastaviti s time, Mick? | Trebali bi sve to zaboraviti.
{16518}{16650}Ionako to nisi uèinio. | Pijano brbljanje.
{16683}{16740}Kako znaš?
{16815}{16885}Kako znaš da nisam | ubio lika?
{17058}{17208}Zašto misliš da sam muškarac | nesposoban ubiti nekoga?
{17271}{17390}Za ubiti èovjeka ne treba | biti muškarac, Mick.
{17438}{17500}Da, ti o tome znaš?
{17633}{17680}Gdje mi je piksa?
{17681}{17770}U spavaæoj, sam zadnju vidjela.
{17813}{17880}G. James je opet vadio pimpek.
{17903}{17965}Nemoj gledati.
{17975}{18065}Ne želim gledati | stari smežurani pimpek.
{18104}{18185}Što, bilo bi drugaèije | da je mladiæ?
{18186}{18226}On je bolestan, Mick.
{18228}{18341}Trebaju ga zalokotati. | - Zašto? Nikog ne dira.
{18342}{18491}Perverzni gad. | - Bar nije pijan kao neki.
{18602}{18655}Ja sam pijan?
{18692}{18740}Ti si kurva!
{18797}{18880}Što nas èini savršenim parom, malena.
{18953}{19018}Idem van! | - Kamo ideš?
{19019}{19057}Van!
{19058}{19177}Zaglavit æu ovdje, ako odeš! | - Nije me puno briga.
{19178}{19238}Kad misliš popraviti moj auto, dovraga?
{19239}{19310}Misliš da æu popravljati auto | cijelog tjedna?
{19311}{19410}Isuse, Mick, koji ti je vrag? | - Prestani, ha?
{19450}{19540}Ne želim da si zlovoljna kad doðem. | Uživaj u pogledu.
{20450}{20490}Mick?
{22603}{22650}Christine!
{24755}{24805}Prestrašio si me | da sam se usrala!
{24860}{24955}Zašto se uvijek moraš blesaviti? | - Koji kurac radiš?
{25000}{25110}Imaš jebenu pušku. | - Koliko dugo si ovdje, Mick?
{25133}{25216}Mick? | - O èemu govoriš?
{25217}{25320}Od kada si ovdje? | Nisam vidjela da si ušao.
{25343}{25465}Pusti me spavati. | - Mick, zašto nisam vidjela kad si ušao?
{25470}{25522}Reci? | - Što?
{25579}{25620}Zašto nisam vidjela kad si ulazio?
{25715}{25825}Ne znam. | Nešto si radila u kuhinji.
{25850}{25910}Ne koristiš ova vrata.
{25955}{26080}Zašto bi išao kroz jebeno dvorište | u kojem je groblje?
{26155}{26280}Drugi imaju jebeno dvorište, | mi imamo vražje groblje.
{26285}{26380}Nije dosta što si | psa tamo pokopala.
{26407}{26480}Sad imamo mrtvaca.
{26584}{26655}Daj mi još jednu pivu, malena.
{27009}{27055}Christine?
{27995}{28040}Christine, ja sam.
{28240}{28295}U nevolji smo, mala.
{28321}{28377}Što je bilo, Mick?
{28504}{28577}Reci mi, Mick.
{28702}{28788}Danas je lik stigao u grad.
{28789}{28908}Ispitivao o nestalim osobama, | mislim da traži mrtvaca.
{28909}{29020}Što æemo, Mick? | Rekla sam da trebamo zvati murjake.
{29020}{29080}Bez jebenih murjaka, Christine, ok!
{29106}{29180}Ne šizi na mene.
{29193}{29264}Ostani smirena, | i sve æe biti u redu.
{29270}{29310}Ostani smirena.
{29417}{29576}Kako je izgledao? | Možda je prijatelj od mrtvaca.
{29582}{29620}Ne znam.
{29698}{29823}Misliš da je bio murjak? | - Kako da znam?
{29824}{29890}Nije djelovao kao murjak.
{29964}{30070}Nisam ja za takve|stvari, Mick.
{30099}{30145}Koji je vrag s tobom?
{30189}{30250}Danas se ne osjeæam dobro.
{30285}{30404}Hoæeš aspirin, ili nešto? | - Ne.
{30456}{30530}Valjda sam oèajna, što drugo.
{30531}{30595}Imali smo tešku noæ.
{30672}{30779}Od mrtvaca zakopanog | u dvorištu, lovi me jeza.
{30782}{30855}Jeza?! | Imam jebene noæne more.
{31028}{31110}Naðu li mrtvaca, | prišit æe meni,
{31111}{31180}bit æu unutra brzo | dok trepneš.
{31187}{31304}Nitko ne zna da je tamo, Mick. | Jedini mi znamo da je tamo.
{31310}{31372}Trebam nestati, | dok sranje sve ne usere.
{31373}{31480}Ne možeš me tu ostaviti! | - Od kad tu ti postavljaš pravila?
{31502}{31605}Što ako ljudi postanu sumnjièavi? | - Misliš da ne znam?
{31679}{31760}Dragi, ne ljuti se na mene.
{31796}{31900}Trebamo se držati zajedno. | - Imaš pravo.
{31921}{31944}Imaš pravo.
{31945}{32037}Što kažeš na prigodu za | jeftino putovanje?
{32038}{32106}Ali bi trebali odmah poæi? | - Kako misliš?
{32107}{32257}Nakon što policija prestane njuškati, | možemo se vratiti.
{32350}{32430}Preumoran sam za razmišljanje.
{32527}{32648}Tako ti je to u gradu.|Nitko te ništa ne pita dok ih se ne tièe.
{32664}{32777}Neæu iæi nikamo, šupèino.
{32785}{32838}Tako je. Da.
{32839}{32880}Da, može i ona.
{32979}{33129}Da.
{33384}{33445}Nema šanse, èovjeèe. | Vidio sam tvoju ženu.
{33450}{33530}Govori o ljubavi.
{33543}{33630}Ljubav je ljubav, | a žene su žene.
{33659}{33780}Da, premekani ste sa svojim ljubimcima. | Možeš završiti ubijen.
{33889}{33954}Odlièna jebena zamisao.
{33997}{34086}Trebaš ih sam dresirati, | a ne kao neki.
{34087}{34237}Moglo bi poæi krivo. | Treba im pravi muškarac.
{34270}{34420}Da. A gdje bi im stavili prekidaè? | U glavu?
{34519}{34548}Isuse!
{34549}{34605}Trebali bi i daljinski, èovjeèe.
{34606}{34700}Upaljeno i ugašeno. Dva dugmeta. | Da je jednostavan.
{34794}{34858}Isuse, trebam takvu,
{34859}{34910}to nama treba jadnima.
{34911}{35024}Možeš zamisliti? Klik, | lijepo stani, draga. 
{35025}{35105}Klik, klik, | vrijeme za spremiti veèeru, dušo.
{35106}{35220}Lijepo doði i kao dobra curica | odi napraviti veèeru.
{35232}{35325}Ili klik, odi spavaj draga. | Izlazim.
{35331}{35441}Klik, donesi pivo!! | Klik, gdje su mi papuèe?
{35442}{35560}Klik, operi leða! | Klik, puši kurac!
{35592}{35660}Ljubi mi guzicu!
{35706}{35780}Ubit æeš me!
{35843}{35989}Bože! | Trebao bi ju kliknuti jednom zauvijek.
{35990}{36140}Zamijeniti sa vruæom prekrasnom | prirodnom plavušom.
{36158}{36308}Sa dvije moždane stanice. | Da, velikim sisama.
{36641}{36770}Hej, draga. | Što æemo veèeras jesti?
{36802}{36933}Mislio sam, ako | bude sve dobro,
{36934}{37045}mogli bi nekamo dalje od prometnice, | i nabavila bi novog psa.
{37069}{37175}Pravog psa ovaj put. | Ne šugavog starog ðukca k'o prije.
{37178}{37290}Šugavom starom ðukcu bi bilo dobro ovdje, | da nije tebe.
{37333}{37465}Otkud ti to? - Misliš da æu opet | uzeti psa da ga udaraš?
{37545}{37678}Tko si ti, jebo te, | da mi tako govoriš?
{37679}{37770}Sereš veæ cijeli tjedan, draga.
{37795}{37945}Ne bi molio da me puste na odmor, | da mi uperiš jebenu pušku.
{38077}{38180}Bio sam tako pijan, mislila | si neæu se sjeæati, je li?
{38209}{38337}Misliš da sam zaboravio da si | mi pušku okrenula u lice?
{38338}{38400}Nije bilo tako, Mick.
{38796}{38820}Hajde, Mick.
{38884}{38955}Nisam znala da si ti u spavaæoj.
{39007}{39090}Kvragu, | nije mi veèeras do igre!
{39142}{39255}Kako ti se dopada? | - Molim te, Mick.
{39373}{39420}Skini gornji dio!
{39454}{39550}Molim te, Mick, ne radi mi to. | Imam stvari za obaviti.
{39607}{39756}Ok, nemoj se još skidati. | Prvo upali radio, a onda skini gornji dio.
{39789}{39905}Požuri, za ime Krista! | Misliš me zavlaèiti cijeli dan!
{40128}{40188}Dobro.
{40218}{40288}Hajde, trebam predstavu.
{40400}{40485}Na kauè, da vidim.
{40500}{40540}Kreni!
{40600}{40655}Ugasit æu sranje.
{40721}{40785}Hajde, curo, pokaži što imaš!
{41123}{41165}Lijepo.
{41300}{41360}Skini ju!
{41794}{41855}Hajde, mala.
{41968}{42015}Jebi se, Mick!
{42016}{42055}Jebi se ti!
{42110}{42155}Hoæeš li ga?
{43186}{43220}Sad izlaziš?
{43285}{43410}Naravno, zašto ne? | Nemam sad tu što raditi.
{43488}{43580}Lutkice... | - Mièi ruke sa mene!
{43580}{43673}Oprosti, | što svoju ženu hvatam.
{43674}{43750}Isuse, jebo te, Mick!
{43776}{43820}Oprosti.
{43929}{44006}Hoæeš priæi i malo popušiti, | za put, a?
{44007}{44051}Veæ sam obavila, Mick.
{44052}{44141}A ustima? | - Nisam prostitutka!
{44142}{44266}Nisam rekao da jesi. | Suviše zahtijevam?
{44328}{44399}Nije sigurno napaljenog muža | pustiti u bar.
{44400}{44450}To je prijetnja?
{44503}{44640}Isuse Kriste, tražim ženu da mi | jebeno popuši,
{44641}{44750}ona jebeno neæe | ni popušiti.
{44850}{44901}Smislila si uzeti inicijativu?
{44930}{44980}Moglo bi mi se dopasti.
{45045}{45140}Usrao sam se od straha.
{45213}{45280}Klik!
{45398}{45544}Hoæu znati zbog èega si | jebeno uvrnut?
{45545}{45650}Zašto me tako tretiraš? | - Daj mi pušku!
{45655}{45720}Evo ti!
{45899}{45940}Gaduro!
{47430}{47480}Mick?
{47580}{47680}Oh, Mick, žao mi je.
{47766}{47840}Oprosti, dušo.
{49211}{49300}Da? | - Gða Eliot?
{49357}{49430}Ovdje g. James, preko puta.
{49435}{49569}Proðem svako malo pozadi i nisam | uoèio nekoga izlaziti na zadnja vrata.
{49570}{49745}Pitao sam se je li sve u redu. | - Sve je u redu, g. James.
{49753}{49890}Primijetio sam, ponekad podnosite | grubosti od svog muža.
{49951}{50025}Ne želim biti nepristojna, g. James,
{50030}{50160}ne vidim da je to vaša briga. | Moram iæi.
{50161}{50260}Znate, vaš suprug | zadaje mi je beskrajne nevolje.
{50301}{50441}Znam, ali... | - Mogao vam je isprièati laži o meni.
{50442}{50500}I laže, znate.
{50500}{50620}Mogu sam nazvati policiju i | žaliti se na buku iz vaše kuæe.
{50664}{50814}Pa, trebali bi to sa njime | raspraviti, g. James.
{50844}{51005}Stvarno je pretjerao.| - Znam, ali rekla bih
{51006}{51081}da vas više neæe gnjaviti.
{51083}{51188}Moram iæi. | - Dobro, ako ste uvjerena...
{51194}{51276}Samo nije normalno | koju galamu radite,
{51277}{51370}glasna muzika, vikanje i to.
{51379}{51520}Blesavimo se, g. James. | Sad moram iæi.
{51534}{51670}Ne dopada mi se vaš suprug, gðo Elliot. | - Znam da ne, g. James.
{51678}{51828}Stvarno moram iæi. | - Shvaæam, sluša, je li?
{51843}{51880}Da.
{51921}{51950}Doviðenja.
{53536}{53580}Christine!
{57710}{57840}O ne, draga, ne bi | se požalila g. Jamesu, je li?
{57888}{57950}Hej, malena. | Kako si?
{57966}{58000}Što je bilo?
{58070}{58237}Trebamo biti otvoreni. | Ne bi oèekivala da æu te lako pustiti, je li?
{58307}{58355}Ne nakon onog što si uèinila.
{58670}{58720}Jebena gadura!
{58721}{58864}Zabila si mi metal | u mozak! Slomila dva kralješka!
{58865}{58930}Uznemirio sam te.
{58999}{59040}Nije li to tužno.
{59080}{59140}Nije li taj zloèin za sramiti se?
{59356}{59440}Prestravila si me se, je li?
{59524}{59674}Što je? | Nisam te uplašio, je li?
{59773}{59900}Èuj, ako ti je neugodno, | ovako,
{59920}{60015}nabaci odjeæu | i sjedni da poprièamo.
{60123}{60156}Idi!
{60219}{60313}Neæu te strašiti, | èasna masna.
{60576}{60662}Oprosti, oprosti. | Nisam mogao odoljeti.
{60668}{60763}Idi! | Nemaš zašto brinuti.
{61230}{61315}Dok god želiš malena, | na usluzi djevojko.
{61820}{61933}Žuriš se. | Planiraš nekamo otiæi?
{62056}{62110}Odgovorit æeš mi na pitanje?
{62271}{62310}Da...
{62394}{62516}Ne znam. | - Ne znam. Tipièno za tebe.
{62571}{62721}Neæeš izdržati ni dvije minute sama.|Šteta što si me se riješila.
{62874}{62955}Primorao si me to napraviti.
{62964}{63120}Zašto ti je tako teško prihvatiti | odgovornost za svoje postupke?
{63120}{63210}Ništa ne uèiniš po svome?
{63339}{63460}A što ako, ne želim | da odeš?
{63522}{63569}Ne želim da odeš!
{63570}{63655}Kažem ti, ne možeš, | još te hoæu sa sobom!
{64340}{64483}Ne bi se time gnjavio. | Upropastila bi naboje.
{64484}{64560}Ne možeš me ponovo ubiti.
{64610}{64669}Baš je nezgodno.
{64670}{64794}Možda bi si otišla | nešto napraviti,
{64795}{64864}malo namazati, | poèešljati kosu.
{64891}{64988}Zbilja te nije zgodno gledati.
{65020}{65070}Odi!
{65539}{65673}Sljedeæi poziv u nevolji je Mick. | Kako si, Mick?
{65674}{65740}Dobro, dobro.
{65751}{65951}Kad promislim malo... nisam baš dobro. | - Kakav imaš problem? Ne srami se.
{65982}{66107}Osjeæam se nekako... udaren. | - Emocionalno?
{66113}{66262}Ne, ne emocionalno. | Mislim zbilja udaren.
{66263}{66340}I meni je malo glupo | iznijeti problem,
{66342}{66470}osjeæam spravu fizièku | nepodnošljivu patnju.
{66488}{66555}Imam takoðer problem u braku.
{66572}{66670}Moja žena nema muža.
{66838}{66924}Smirite se, g. Elliot. | Ovo je ozbiljna emisija.
{66925}{67038}Dobro, dobro. | Imam još jedan.
{67039}{67196}Žena me ne razumije. | - Žena vas ne razumije?
{67197}{67290}Najbolji savjet koji mogu dati je | da uzmete sjekiru.
{67291}{67330}E, to je ideja!
{67432}{67485}I moja žena je loša.
{67504}{67610}Zato hoæu seks sa vašom. | Haj, Christine.
{67670}{67732}Isprašit æu ti guzicu!
{67746}{67866}Sve je zabavnije | što je više zgoditaka, pred kraj.
{68019}{68105}Mogu te pitati, | Chrissie.
{68118}{68166}Zašto to radiš?
{68247}{68270}Što radim?
{68301}{68380}Zašto s murjakom, | od svih ljudi?
{68390}{68544}Kako znaš za to? | - Znam sve o tebi, Christine.
{68604}{68680}Isuse! | Jebenim policajcem!
{68702}{68809}Bio je dobar. | - Dobar? Kurac dobar!
{68810}{68854}Murjaci nisu dobri, Christine.
{68855}{68955}Žive u stvarnom svijetu. | Nisu sposobni biti dobri.
{68969}{69080}Trebaju tu rijeè tražiti u rjeèniku. | - Bio je dobar prema meni.
{69089}{69194}Bio je dobar prema tebi | jer te jebao, glupa kujo.
{69220}{69260}Znaš li to?
{69377}{69470}Da. | Sada znam.
{69539}{69668}Pala si na prièu da te volim,| Chrissie govno!
{69676}{69733}Zaveži i ostavi me!
{69754}{69866}Htjela sam biti s njim | jer mi je bilo dobro.
{69880}{69960}Bio je obrazovan, | razgovarao sa mnom.
{69980}{70070}Nije urlao na mene | i udarao me.
{70084}{70230}Da, mislila si da æe te odvesti | iz smrdljivog gradiæa, je li?
{70231}{70314}Da. | - Nekamo gdje je lijepo, lijepo...
{70315}{70362}Da.
{70363}{70491}Mislila sam možda æu | napokon imati pristojan život.
{70492}{70653}Gdje zrak miriše na zrak i umorna sam | od piæa u tvojoj glavi neprestano.
{70656}{70725}Morala si biti uzbuðena.
{70770}{70840}Sramota da si se | pretvorila u govno.
{70920}{70965}Da, sramota.
{71049}{71125}Napravila si mu vražju zbrku u glavi.
{71163}{71235}Lijepo si me sredila.
{71334}{71376}Ne!
{71561}{71625}Ti si mi to uèinila, Chrissie.
{72334}{72420}Ne bi valjalo u ovoj državi...
{72448}{72500}preko granice, a?
{72543}{72610}I mene bi izradio.
{72723}{72873}Šteta što je krenulo tako ozbiljno.
{72966}{73080}Zbilja si oèekivala da æe te | odvesti, je li?
{73179}{73270}Nije ti namjeravao ništa pružiti.
{73305}{73409}Njegova žena ne bi prihvatila situaciju.
{73410}{73480}Valjda te to pogaða.
{73556}{73610}Stalo mu je do žene.
{73790}{73880}Sad vidiš kakav stvarno je.
{73934}{74000}Pokvaren do srži.
{74428}{74466}Kako je...
{74503}{74555}ubiti èovjeka?
{74620}{74750}Sigurno je bilo puno lakše|onom bijedniku pucati u glavu.
{74797}{74889}Èekati da progovori... | - Prestani!
{74890}{75021}Prestani me maltretirati! | Što sam uèinila
{75022}{75082}da me stalno muèiš?
{75083}{75163}Trèi, Chrissie! | Kamo æeš?
{75164}{75232}Ne ideš nikamo! | - Ne!
{75265}{75378}Pokaži mi sise, draga! | - Odlazi od mene!
{75379}{75455}Kako me možeš natjerati?
{75490}{75550}Kako æeš me zaustaviti, a?
{75640}{75750}Nisam èovjek s kojim se može|sporazumjeti.
{75793}{75840}Gledaj me!
{75925}{75970}Dobro si, draga?
{76198}{76295}Tako si lak plijen, | da nije ni zabavno.
{76312}{76375}Zašto to radiš?
{76476}{76540}Jer mogu.
{76617}{76725}Radije upotrijebi nož odmah!
{76848}{76970}Ili æu nastaviti svojim životom...
{77103}{77175}kao da te nema ovdje.
{77369}{77492}Jer te nema. | - Sigurno ti nisam lijep, draga.
{77493}{77699}Naravno da sam tu. | Možeš vidjeti svojim oèima. Kopèaš?
{78580}{78700}Gdje ti je novèanik? | - Otkud bi ja znao?
{78781}{78855}A kljuèevi, Mick? | Gdje su?
{78928}{79078}Pogledaj mi u guzici, koliko znam. | - Baš odlièno.
{79087}{79237}Pogledaj mi u guzici, koliko znam...
{79245}{79334}Zaveži, jebeni kuèkin sine!
{79335}{79485}O, ne krivi mene! | ...ne krivi mene... ...ne krivi mene...
{79998}{80055}Sranje!
{80088}{80162}Da? | - Chris, ovdje Ron.
{80163}{80274}Hoæeš mi dati Micka? | - Nije unutra.
{80274}{80403}O, dobro, kad je izašao? Lijena guzica | rekao je biti pred 30 minuta.
{80406}{80483}Chris? | - Da.
{80484}{80610}Kad je gad zašao? Ne mogu ga | èekati do jutra. Imam još puno voziti.
{80619}{80759}Ne doðe li za deset munuta, | morat æu njegovu kartu ostaviti i iæi sam, ok?
{80811}{80954}Nastavi samo, Ron. | Oprosti, zaspala sam.
{80955}{81065}Htjela sam zvati i reæi | da Mick neæe moæi.
{81066}{81130}Kvragu, kako misliš | neæe moæi?
{81136}{81254}Trebao je nešto obaviti prije | nego je išao na odmor.
{81255}{81370}U nekakvoj je nevolji? | - Zašto pitaš?
{81381}{81476}Zbrojio sam dva i dva. | Nekakav je okolo njuškao.
{81477}{81614}Moguæe nekakav tajni policajac. | Jako se zanimao za Micka.
{81615}{81765}Razuvjerio sam ga. | - Hvala, Ron, nema se zbog èega zabrinjavati.
{81777}{81845}Ja sam ovdje!
{81846}{81902}Sad moram iæi, dobro?
{81903}{82053}Reæi æu Micku neka nazove.
{83881}{84000}Dobro jutro. Gða Elliot? | - Da. Kako mogu pomoæi?
{84001}{84060}Trebam postaviti nekoliko pitanja.
{84087}{84128}Što želite znati?
{84129}{84227}Ne možemo sjesti i | poprièati?
{84228}{84368}O, sad sam uposlena. | Pitajte što želite znati?
{84369}{84425}Ovo je zaista važno.
{84447}{84597}Zovi ga unutra, draga. | Ne želiš da poène u tebe sumnjati?
{84705}{84782}Uðite, kad želite. | - Dobro.
{84783}{84888}Samo za uvod, | ne smetaš mi, murjak!
{84966}{85100}Pitaj ga hoæe li popiti? | - Možemo... kavu?
{85121}{85165}Bilo bi odlièno.
{85358}{85485}Lijep kaktus. | - Da, sakupljam ih.
{85625}{85715}Izvolite. | - Zamazan posao, a?
{85727}{85830}Svakako. | Radim cijelo jutro.
{85865}{85984}Ne znam kako bi moj procvjetao. | - Da?
{85985}{86099}Treba im hrane. | - Vjerojatno ste u pravu.
{86158}{86260}Ovo je èovjek kojeg tražim. | Mogli ste ga vidjeti.
{86262}{86358}O da, vidjela ga je. | Vidjela je svaki njegov djeliæ.
{86359}{86495}O, ne. Poznat mi izgleda, | ali ga sigurno nisam vidjela.
{86503}{86565}Dobro. | - Sjednite.
{86566}{86679}Hvala. | - Hoæete žlièicu šeæera?
{86680}{86760}Ne. Dobra je ovakva.
{86866}{86930}Dobra kava!
{86947}{87000}Kako ste porezali usnu?
{87066}{87140}Nije te jebeno briga!
{87153}{87240}Dobro, nije me briga.
{87426}{87518}To ste htjeli znati, | jesam li ga vidjela?
{87519}{87590}Da, zadnji put sam ga | vidio u ovom predjelu.
{87591}{87644}Znao sam! | Gleda te sa zanimanjem, Chrissie.
{87645}{87760}Djelujete malo nervozno. Ne grizem. | - Znam.
{87761}{87870}Nisam nervozna, | ima veze s neèim od sinoæ.
{87891}{88000}Jedan susjed, | misli da je vidio traženog,
{88001}{88135}dolazio je ovamo pred dva tjedna. | - Pogledajmo kako æeš se izvuæi, Chrissy.
{88283}{88440}Vjerojatno je morao reæi g. James, je li? | On je ludi starac.
{88446}{88588}Reæi æe sve da pridobije pažnju, | ne bi polagala nešto na to.
{88599}{88680}Da smetnem s uma. | - Tako uèinite.
{88700}{88750}Trebate provjeriti njegov karton.
{88881}{88950}Kad bi razgovarao s vašim | mužem, bilo bi odlièno.
{88958}{89023}Na praznicima ste, je li? | Blizu je?
{89024}{89090}Izašao je poslom.
{89102}{89140}Kad ga oèekujete natrag?
{89267}{89340}Trebala si si dati vremena | i pokopati me kako treba.
{89341}{89455}Treba ga uhvatiti, |kad se vrati sa odmora.
{89627}{89728}Što psi tu kopaju? | - Vjerojatno su se provukli kroz ogradu.
{89729}{89827}Idem ih poplašiti. | - Ne, nemojte, nemojte.
{89828}{89920}Znam pse. | Tu se motaju.
{89929}{90020}Imala sam i ja psa, | pogazio ga je kamion.
{90025}{90090}Ako vam više ne mogu pomoæi...
{90154}{90220}Ispratite se. | - Dobro.
{90313}{90400}Psi kopaju grob...
{90508}{90627}Možda æu morati još pitati. | Neæete skoro odlaziti, je li?
{90628}{90720}Sve sam odgodila za | prvi odmor u godini.
{90769}{90840}Naæi æu vas ako zatrebam.
{90955}{91110}Valjda neæe doæi do toga.
{91202}{91333}Dobro si se držala... | za gubitnika.
{91505}{91540}Kamo ideš?
{91550}{91650}Misliš da æe murjak ostaviti | istragu prije no...
{91650}{91715}Zaveži! | - Zaveži?
{91722}{91840}Ne slažem se! | Jedva èekam da se otkrije.
{91841}{91940}Ljudi æe imati | pravu gozbu.
{91961}{92117}Ime æe ti vuæi po svim vijestima | i televizijama države.
{92118}{92246}Poludila potpuno, ubila voljenog supruga. | Detalje jedva èekaju!
{92342}{92460}Naprijed, naprijed. | Ne reci da te nisam upozorio.
{92696}{92845}Jadna Chrissy. | Nema kamo otiæi.
{93433}{93525}Vidiš kako nam može biti zabavno, | draga?
{94491}{94553}Da, Ron je. | Mick se vratio?
{94554}{94649}Ne, Ron. | Mislila sam da ste na utakmici.
{94650}{94710}Prodao sam karte.
{94739}{94849}Dobro si? | - Da, dobro, dobro.
{94850}{94919}Slušaj, Chris. | Znam da se nešto dogaða.
{94920}{95038}Ne želim znati što, | ali reci Micku neka se drži podalje.
{95039}{95146}Lik se vratio. Sumnjièav je. | Ne vjerujem mu.
{95152}{95274}Može biti opasno ako je murjak. | Opet je ispitivao o vama dvoje.
{95275}{95350}Mislim da je na putu k vama.
{95359}{95430}Dobro, Rone, hvala. | - Dobro si?
{95431}{95535}Trebaš nešto? | - Ne, sasvim sam dobro.
{95536}{95592}Velika zabuna, samo to.
{95593}{95715}Obavijesti me, važi? | - Svakako, doviðenja.
{95724}{95795}Rekao sam da æe za èas.
{95865}{95980}Možda bi mogla|skinuti naušnice.
{96060}{96100}K vragu.
{96318}{96390}Isprièavam se zbog dosaðivanja, gospoðo, | trebamo razgovarati.
{96399}{96491}Na odmoru sa, sjeæate se, | ne želim se sada zamarati.
{96492}{96602}Da, ali moramo razgovarati. | Hoæete me pustiti?
{96603}{96680}Možemo razgovarati i ovdje.
{96788}{96880}Pokušavam biti što ugodniji | u ovoj situaciji.
{96971}{97060}Možda bolje da sam se najavio.
{97079}{97210}Žao mi je, | samo moram do kraja rašèistiti.
{97268}{97390}Teška vruæina unutra. | Vrijeme?
{97421}{97507}Zašto je podignuta zavjesa? | - U èemu je problem?
{97508}{97579}Rekla sam da ne znam ništa.
{97580}{97630}Mislim da znate.
{97702}{97770}Hajde, Christine. |Doæi æemo do toga ovako ili onako.
{97771}{97921}Rekla sam vam. | - Nisi rekla ništa.
{97975}{98030}Evo pogledaj ovo!
{98125}{98177}Zaboravi.
{98233}{98307}Dobar je zaborav.
{98308}{98352}Reci što se dogodilo mom detektivu?
{98353}{98450}Ne znam ništa o tvom detektivu.
{98542}{98655}Možeš ponovo promisliti? | - Rekla sam vam nekoliko puta.
{98679}{98740}Pogledaj izbliza.
{98811}{98855}Sada...
{98868}{98940}osjeæaš da bi voljela o tome razgovarati?
{98997}{99068}Mogu dobro zamisliti | što se dogodilo.
{99069}{99197}On ti je muž. | Shvaæam da ga želiš zaštititi.
{99198}{99257}Da sam bio tako sretan.
{99258}{99400}Pitam se kamo je pobjegao? | - Nije pobjegao, na odmoru je.
{99415}{99505}Slušaj, | dogovorit æemo se.
{99522}{99680}Bit æu otvoren prema tebi, | trebaš mi samo uzvratiti uslugu, ok?
{99842}{99890}Dobro.
{99918}{99986}Drago mi je što æemo se razumjeti.
{99987}{100045}Postaje zanimljivo, a?
{100050}{100200}Nekoæ je bio | zgodan mladi detektiv,
{100236}{100367}jednog dana bi poslan u | ružni gradiæ na kraju svijeta,
{100368}{100480}poslao ga zli šef, | po nekom posliæu.
{100509}{100700}Na putu kuæi, stigne do | seksi, vitke, lijepe princeze.
{100760}{100910}Opisao je da se lijepa princeza | hoæe riješiti pijanca?
{100916}{101000}Momak je poèeo piti svom silom.
{101036}{101186}Dojmila se | dosta nalik... tebi.
{101288}{101460}Nema razloga da trebamo | imati cijeli opis.
{101471}{101520}Kurva.
{101590}{101655}Što se dogodilo?
{101656}{101766}Ulovio vas u naletu strasti, | zguza?
{101797}{101835}Ubio ga?
{101863}{101990}Kako ga je ubio golim rukama? | Morao je biti nagao.
{101998}{102060}Hej, to nije pošteno.
{102103}{102144}U pravu sam?
{102178}{102230}Ustrijelio ga je.
{102238}{102290}I on je umro.
{102765}{102850}Nisam ja ta, mamojebaèu!
{102861}{102970}Radije me uhiti, | ako što još hoæeš saznati.
{103005}{103080}Gdje je tijelo, žestoka curo?
{103140}{103200}Gdje je tijelo?
{103260}{103330}Gledaj... gledaj me!
{103350}{103499}Reci gdje je tijelo, | neæu te više povrijediti.
{103544}{103730}Pitat æu još jednom. | Sasvim ljubazno. Gdje je tijelo?
{103739}{103800}Ne znam gdje ti je jebeno tijelo.
{103801}{103927}Mislim da znaš! | - Ne znam! Prestani!
{103928}{104017}He, to je moja žena!
{104018}{104080}Reci! | - Ti si jebeni luðak?
{104081}{104122}Reci!
{104123}{104230}Policajci ubijaju ljude? | - Prešao si mjeru, pajkane!
{104231}{104302}Da te i optuže, neæe naæi tijelo.
{104303}{104430}Jebeno si luda?! | - Ubij me i neæeš naæi tijelo.
{104431}{104517}Reci mi, ili æu te povrijediti.
{104518}{104668}Imam prilièno visok prag bola.
{104926}{105021}Èovjeèe, s ovime neæeš proæi.
{105022}{105129}Sada bi me uhitio, je li?
{105130}{105260}Zašto tako žestoko tražiš tijelo? | Zašto ne ubojicu?
{105331}{105480}Možda je na tijelu | nešto što želi.
{105513}{105635}Kako si rekao da mu je ime?!
{105636}{105761}Nisam nikako. | - Covalinski, zar ne?
{105762}{105857}Bingo. | - I hoæeš nekakvu listu?
{105858}{105926}Gdje je lista?
{105927}{105980}Sad ga imaš!
{106092}{106182}Gdje je? | - U njegovoj jakni.
{106183}{106250}U njegovoj jakni? | - Da, u njegovoj jakni.
{106251}{106355}E pa, | nekamo smo krenuli.
{106370}{106447}A gdje je vražje tijelo?
{106448}{106516}Voliš raditi pogodbe?
{106517}{106743}Dam ti listu, tvoje tijelo, osiguraš li | da ja i Mick sigurno izaðemo iz države.
{106743}{106841}Lista, gdje je lista? | - Nisam još gotova!
{106842}{106916}Daj mi 10.000, gotovinu.
{106917}{107039}Mogao bi te staviti u zatvor. | - Možda neæeš.
{107050}{107120}Imam što želiš.
{107335}{107440}Dobro. | Donijet æu novac.
{107524}{107667}Kada? | - Sutra... sutra naveèer.
{107668}{107790}Doæi æeš sutra s gotovinom, | i dat æu ti leš.
{107944}{108066}Napustiš li kuæu, | ili mi napraviš ikakve probleme,
{108115}{108165}pronaæi æu te.
{108232}{108280}Dobro?
{108423}{108535}Ne misli da te neæu naæi u | nekom jeftinom motelu.
{108660}{108767}Jest æeš pseæa govna...
{108768}{108850}dok ja ne dobijem listu.
{109535}{109675}U nekom dubokom si govnu, Crissie. | - Zaveži, Mick. Razmišljam.
{109676}{109729}Mora ti ovo biti teško.
{109730}{109800}Da, i još si ti pokraj mene.
{109946}{110041}Nekako me iznenaðuje
{110042}{110140}u kakvoj si se teškoj situaciji snašla, Christine.
{110141}{110290}Zaveži, Mick. | - Ne mogu vjerovati kako me iskorištavaš.
{110413}{110496}Vjerujem da ti mogu dugovati,
{110497}{110590}nakon svih godina | što si ti iskorištavao mene.
{110611}{110720}Usputno, si i mrtav, | pa ti nije važno.
{111025}{111070}Što sad radiš?
{111133}{111070}I on te želi.
{111210}{111300}Zašto nije ovdje i muèi | me poput tebe?
{111318}{111400}Jer se sad imaš više | brinuti za mene.
{111450}{111600}Trebam te paziti od murjaka, |da te ne zajebe.
{111684}{111760}Mislim da nema drugog izbora.
{111819}{111914}Pitam se zašto ti je stalo? | Što namjeravaš?
{111915}{112000}Ništa draga. | Nisam ništa naumio.
{112056}{112140}Poèelo mi je dosadno | biti stalno zao.
{112250}{112313}Ne prodavaj mi to sranje, | Mick.
{112314}{112380}Nikad ti ne bi dosadilo | biti zao.
{112427}{112469}Mogli smo biti sretni.
{112517}{112580}Zbiljski sam te voljela.
{112622}{112390}Bila sam sretna što te imam.
{112868}{112920}To je tvoj problem.
{112961}{113123}Nismo jednaki, Mick. | Nije u redu okoristiti se povuèenim ženama.
{113125}{113202}To je zla ljudska sreæe, Christine. | U ljudskoj prirodi.
{113203}{113274}Uvijek bila, i uvijek æe biti.
{113275}{113320}Ubio si me iznutra.
{113362}{113460}Ništa nije preostalo, | samo vakuum.
{113551}{113640}Ne vakuum na | kakav se misli.
{113683}{113790}Misli se na prostor | bez ièega u njemu.
{113836}{113940}Kod mene je pravo veliko ništa.
{113971}{114030}Kao vanjski svemir.
{114111}{114190}Nemoguæe, | nisam tako razmišljao.
{114285}{114370}Zašto nismo mogli | tako razgovarati dok si bio živ?
{114396}{114488}Isuse, Christine, | osjeæam se zbunjeno.
{114540}{114605}Nikad nisam tako razgovarao.
{114711}{114790}Razgovarala si tako | sa ljubavnikom?
{114812}{114887}Isuse, tako si pametna | ovih dana?
{114888}{114939}Isuse, Mick, što hoæeš?
{114950}{115037}Suviše se baviš izmišljenima, | zato na tebe vièem.
{115046}{115120}Kako æeš otiæi meðu prave ljude?
{115151}{115200}Još se nisi oslobodila | misliti na mene.
{115285}{115320}Nije istina, Mick.
{115396}{115460}Neæu više moæi tako.
{115498}{115552}Stvari su se promijenile, Mick.
{115600}{115684}Mislim da te više neæu trebati.
{116505}{116609}Izgledaš drugaèije. | - Osjeæam se drugaèije.
{116610}{116665}Imaš novac?
{117131}{117184}Kad... idemo?
{117185}{117277}Hoæu znati zašto ti tako jako | treba popis.
{117278}{117350}To nije dio dogovora.
{117428}{117490}To je amandman.
{117521}{117610}Ne troši mi sad vrijeme. | - Znatiželjna sam.
{117617}{117667}Znatiželjna si? | - Da.
{117905}{117940}Dobro.
{117979}{118065}Pa æemo po listu? | - Svakako, detektive Covalinski.
{118066}{118190}Covaleski. | I nisam detektiv.
{118198}{118299}Nastavi, šefe. | - Nije važno.
{118300}{118377}Ako bi isprièao prièu, | vjerovala bi mi?
{118378}{118425}Možda bi.
{118492}{118642}Èuj, najvažnije je da uklonim listu | od mrtvog tijela.
{118708}{118795}Gdje lista je?
{118834}{118890}Ovdje.
{119112}{119262}Si kad živio negdje gdje |postoji lijepi sumrak?
{119340}{119435}Bojiš se da bi te |dolje moglo doèekati iznenaðenje?
{119511}{119661}Što je bilo? Tako si ju jako htio | pred samo pet minuta.
{119712}{119822}Još je u jakni? | - Da. Toèno gdje ju je stavio.
{119864}{120014}Stajat æeš tu i gledati, a?
{120185}{120335}Nije on! | Lagala si?
{121420}{121499}Pridružio sam se tvojim drugovima.
{121672}{121800}Pobijedila sam. | Bilo je ti ili ja.
{121845}{121890}Sranje!
{121900}{121985}I jer sam si bila | važnija od vas,
{122022}{122100}morala sam pobijediti.
{122855}{122925}Haj! | - Gospodine James.
{122926}{123024}Zdravo gðo Elliot. Zovem | jer sam nešto zabrinut.
{123025}{123088}Zbog èega? | - Pa, mislim da znate.
{123089}{123230}Buduæi znam da muža nema, | a èuo sam onoliku buku u kuæi,
{123231}{123304}èini se da ste izgubili | kontrolu zadnjih nekoliko dana.
{123305}{123426}Znam koliko je opasno izgubi li žena kontrolu, | ako znate što mislim.
{123427}{123567}Savršeno sam pod kontrolom, g. James. | - Dobro je èuti, ali mislim...
{123568}{123660}Ne mislite da žena pod kontrolom | može biti puno opasnija
{123661}{123700}od žene van kontrole?
{123701}{123772}Jeste na to pomislili, g. James? | - Pa ja...
{123774}{123880}A ne morate više brinuti. | Napuštam grad.
{123895}{123978}Lijepo smo se razgovarali, | g. James.
{124589}{124689}{C:$0000FF}{y:ib} preveo |{C:$FF0000}{y:b} drdamjan 
{124778}{125178}
