{1}{1}25.000
{1550}{1650} ELITNA EKIPA 
{4370}{4453}Velièanstveni K. O. U drugoj rundi | okrunio je briljantnu...
{4458}{4523}...boksaèku karijeru | Waynea Barclaya.
{4528}{4613}Otkad se povukao s ringa, | nije se osvrtao na prošlost.
{4618}{4672}Upotrijebivši milijune koje je | zaradio u prizefightningu...
{4677}{4735}...Wayne je preusmjerio svoju | fantastiènu energiju...
{4740}{4818}...u ponovno oživljavanje kvarta | u kojem je roðen i odgojen.
{4823}{4888}Poèeo je s nekoliko restorana | brze hrane...
{4893}{4949}...ali je ubrzo prešao | na trgovaèke centre...
{4954}{5026}...zatim na kino dvorane, i konaèno | na poslovne zgrade.
{5031}{5090}U skoro su mu prihodi tih | riziènih ulaganja dozvolili...
{5095}{5180}...da konaèno sravni sa zemljom te | zapuštene sirotinjske èetvrti...
{5185}{5278}...i zamijeni ih èistim stambenim | prostorima pristupaènih cijena.
{5294}{5408}A što se zakona tièe, | neoèekivan razvoj dogaðaja...
{5693}{5734}Kako to da se moja | fontana smanjuje...
{5739}{5782}...svaki put kad vi | odete odavde?
{5787}{5908}Oprostite, g. Barclay, postoje | pravila koje moramo poštivati.
{5919}{5994}Ne tražim od vas Nijagarine slapove.
{6010}{6059}Ja to cijenim. | Ali pravila su pravila.
{6064}{6141}Ja samo želim tu vražju fontanu | da bi se èovjek ovdje osjetio...
{6146}{6205}...nekako posebnim. | Razumijete?
{6210}{6262}Želim nešto gdje æe ljudi | koji tu stanuju osjetiti...
{6267}{6326}...da je njihov dio grada jednako | dobar kao bilo koji drugi.
{6341}{6386}Wayne, brzo, upali vijesti!
{6391}{6470}- Tamara, na sastanku smo. | - Moraš ovo vidjeti.
{6488}{6534}Stvarno moraš ovo vidjeti, | Wayne.
{6539}{6618}Ranije puštanje na slobodu | koje je iznenadilo tužitelje...
{6623}{6696}...potvrðeno je danas na | saslušanju za uvjetne kazne.
{6709}{6773}Velikan rap muzike | Terrell Singletery...
{6778}{6862}...osuðen je na deset godina | zbog iznuðivanja...
{6867}{6960}...izbjeljivanja nov ca i | zastrašivanja svjedoka.
{6965}{7048}Ali spominjuæi njegovo dobro | ponašanje u zatvoru...
{7053}{7116}...i njegove brojne doprinose | u dobrotvorne svrhe...
{7121}{7181}...tijekom 18 mjeseci zatvora | odbor za uvjetne kazne...
{7194}{7293}...pretvorio je njegu preostalu | kaznu u uvjetnu slobodu.
{7298}{7374}Pa državni tužitelj je obeæao | da æe odslužiti mimimum 8 god.
{7379}{7418}Ovo se nije trebalo dogoditi.
{7423}{7502}Zahvaljujuæi njegovom novom | super advokatu, dogodilo se.
{7507}{7566}U redu, što želite da ja | napravim u vezi s tim?
{7571}{7612}Da iskopam rupu i skrivam | se poput krtice?
{7617}{7654}Taj èovjek je na uvjetnoj.
{7659}{7737}Ali ako i pljune na ploènik, | vraæaju ga u zatvor.
{7742}{7795}Ne brinem se zato što bi mogao | pljuvati po ploèniku.
{7800}{7892}T. Singletery je poznat jer tuèe | sve koji mu ne poštuju ime.
{7903}{7933}Stvarno?
{7938}{7999}Ja sam uèinio i gore od toga, | a još sam ovdje, zar ne?
{8004}{8088}Doði sutra, tada više neæe | nadzirati njegove pozive.
{8093}{8153}Neæe prisluškivati dok je | sa svojim odvjetnikom.
{8158}{8190}A on æe biti na ulici.
{8195}{8264}I želiš znati koji æe mu biti | prvi poslovni zadatak?
{8269}{8326}Poslati poruku onome | koji ga je odao.
{8331}{8389}Wayne, molim te, slušaj me.
{8394}{8450}Potrebna ti je ozbiljna zaštita.
{8455}{8496}Imam zaštitu, sestrice.
{8501}{8542}U redu? | Imam zaštitu.
{8547}{8630}Mislim, zašto plaæamo glavnog | zaštitara ovdje?
{8635}{8690}Moraš poslušati svoju sestru | što se ovoga tièe, Wayne.
{8695}{8766}- Potrebna ti je dodatna zaštita. | - K vragu.
{8771}{8847}Reæi æu vam nešto. Wayne Barclay | neæe popustiti ni pred kojim...
{8852}{8894}...kretenom na ovom svijetu.
{8927}{8960}- Wayne... | - Wayne!
{8965}{9065}Slušaj, ako Terrell želi dio mene, | zna gdje æe me naæi.
{9070}{9100}Ne...
{9202}{9241}G. Mullins...
{9246}{9330}Što ste toèno mislili pod | "dodatna zaštita"?
{9902}{9978}G. Singletery! | G. Singletery, ovamo!
{9990}{10056}Kakav je osjeæaj biti | slobodan èovjek, Terrell?
{10061}{10126}- Makni se. | - Kako je biti slobodan?
{10131}{10160}Oslobaðajuæe.
{10234}{10296}Samo radimo svoj posao, u redu? | Ne budite tako teški...
{10301}{10374}Strièe T, ovamo, idemo!
{10379}{10449}- U redu, idemo, idemo. | - Makni ruke s mene.
{10604}{10672}- Vrata, hajde. | - Što osjeæate prema...
{10677}{10724}...Wayneu Barclayu, èiji vas je | dokaz strpao u zatvor?
{10729}{10769}Dosta. | Bez drugih pitanja.
{10774}{10810}Ovo je super, Leonarde.
{10815}{10898}Znam da je g. Barclay radio | dobar posao za našu zajednicu.
{10903}{10986}U ovom trenutku svog života | samo kažem oprosti i zaboravi.
{10991}{11033}I Bog te blagoslovio. | Oprostite.
{11038}{11078}Kako je bilo u zatvoru, | Terrell?
{11083}{11129}Stariji vodnik Clarence Bowden.
{11147}{11212}Ovo smo mi u Kuvajtu, baš | nakon Pustinjske oluje.
{11217}{11282}Sreæom po nas, on je u mirovini | i traži nešto novo.
{11295}{11324}Vrlo dojmljiv | životopis.
{11371}{11434}Ali mi nismo u ratu ovdje, | Mullinse.
{11445}{11506}I ja se nadam da æe | tako i ostati.
{11523}{11569}Želim reæi...
{11574}{11608}...da li tvoj prijatelj | razumije...
{11613}{11680}...sve finese izvršne zaštite?
{11685}{11745}U Pentagonu se brinuo o | Osnovnoj Osobnoj Zaštiti.
{11750}{11819}U Afganistanu je bio tjelesni | èuvar generala.
{11836}{11895}Prije toga je istu stvar | napravio na Haitiju.
{11918}{12000}Nisam rekao da nam je Clarence | Bowden jedini izbor koji imamo.
{12019}{12066}Kažem da bismo imali vrašku | sreæu da ga dobijemo.
{12770}{12815}Sredi se, vojnièe.
{12854}{12893}Imam zadatak za tebe.
{13079}{13118}Našao sam nam gažu.
{13816}{13863}Bilo je vrijeme.
{13887}{13931}Da.
{14007}{14057}Hej, šefe.
{14128}{14182}Dobrodošao kuæi.
{14207}{14241}Ugodna vožnja?
{14246}{14282}Da...
{14287}{14345}Vozili smo po slikovitoj cesti.
{14415}{14487}- Vidio sam te na TV. | - Ma daj.
{14541}{14580}Yo, B.!
{14585}{14665}Kakva je to prièa o opraštanju | i zaboravu, èovjeèe?
{14670}{14718}Ma oprosti što lažem.
{14723}{14763}Zaboravi da sam to rekao.
{14768}{14838}Pretvorit æemo ovo u ratnu zonu.
{14843}{14943}Oprosti, strièe T., ali što je | s novim dnevnim redom?
{14948}{15022}Onim o kojem si govorio. Znaš | ono o "pojaèavanju mira".
{15039}{15073}O, to æe veæ doæi.
{15078}{15150}Ali prvo, ljudi u ovom gradu | moraju znati...
{15160}{15234}...da nitko ne radi budalu | od Terrella Singleteryja.
{15333}{15374}Strièe T.!
{15399}{15447}Strièe T., na uvjetnoj si!
{15452}{15512}Kad bi odvjetnik znao | da ovako govoriš...
{15517}{15576}Neæe saznati. Simcoe, jesi li | oèistio kuæu?
{15581}{15626}Neæe oni postaviti prislušne | ureðaje u kuæu. Ne mogu oni to.
{15631}{15678}Pribit æemo im guzice na zid.
{15683}{15737}Ali kad bi Wayne Barclay | prijevremeno završio život...
{15742}{15800}...pod bilo kojim okolnostima, | tebe bi optužili za to.
{15805}{15860}Bi li ti slušao ova sranja?
{15867}{15958}Takve rijeèi su te nauèili | na tom otmjenom koledžu?
{15963}{16004}Da, upravo tako.
{16009}{16076}Zahvaljujuæi tebi i tvojoj | velikodušnosti.
{16081}{16113}Da...
{16118}{16178}Slušaj tog malog pizdeka.
{16183}{16211}Taj bi se mali crnjo...
{16216}{16260}...riješio Michaela Jacksona...
{16265}{16330}...i dobio skrbništvo nad | njegovom djecom.
{16343}{16378}Hvala.
{16436}{16465}Vodnièe!
{16470}{16518}Odsad dobri stari Clarence. | Kako si, Ken?
{16523}{16552}- Dobro izgledaš. | - Ti takoðer.
{16557}{16626}- Život izvan svega te mazi? | - Ne mogu se potužiti.
{16637}{16686}Doveo sam svog kompanjona.
{16691}{16770}Ovo je Philippe Sauvage. Služili | smo skupa u Afganistanu i Iraku.
{16828}{16866}A ovo je Tamara Barclay.
{16879}{16951}Wayneova sestra i financijski | struènjak u Barclay Entreprises.
{16956}{17004}Dama èiji je potpis na èekovima.
{17015}{17068}To sam ja. Drago mi je što smo | se upoznali, g. Bowden.
{17073}{17118}- Zadovoljstvo je moje, gospoðo. | - Sjednite.
{17123}{17238}Pretpostavljam da vas je g. Mullins | obavijestio o situaciji.
{17243}{17329}Je li vam objasnio i to da moj brat | može biti vrlo tvrdoglav?
{17334}{17387}Dobro je da boksaè bude takav.
{17392}{17446}Eto zbog èega se on uvijek | snaðe u teškim situacijama.
{17451}{17505}Nažalost, sada je u malo | drugaèijem ringu.
{17510}{17557}A njegov protivnik | ne nosi rukavice.
{17562}{17601}Njegov protivnik æe sve | napraviti da pobijedi.
{17606}{17665}Tu vrstu borbe razumijemo.
{17670}{17762}Moj brat ne razumije da mu je | život u velikoj opasnosti.
{17767}{17826}Istina je da ja | potpisujem èekove...
{17831}{17904}...ali on donosi najvažnije odluke | o ovoj korporaciji.
{17915}{17982}Dakle, trebam nekoga | tko bi mogao biti...
{17987}{18050}...Waynov nevidljivi anðeo èuvar.
{18117}{18146}Dakle...
{18151}{18228}Svidio mi se Bowden. | Jako mi se svidio.
{18233}{18262}A onaj...
{18267}{18304}Onaj drugi tip?
{18325}{18355}Zaboravi na to.
{18360}{18392}Ona me mrzi.
{18397}{18448}Razgovarali smo o gaži, | ne o sudaru naslijepo.
{18453}{18507}Da. | O gaži koja nam ne treba.
{18512}{18576}Meni ne treba. Tebi da.
{18593}{18685}Nešto u njemu je nekako | zabrinjavajuæe.
{18711}{18778}Godina u Afganistanu | i još dvije u Iraku...
{18783}{18814}...mogu to prouzroèiti.
{18831}{18862}Slušaj, Philippe...
{18867}{18939}Bio sam u istoj frci kad sam se | vratio iz Vijetnama.
{18944}{18986}Zbog istih razloga.
{18991}{19060}Prešao si dug put i ponosan | sam na tebe zbog toga.
{19065}{19133}Ali nisi još sasvim dobro.
{19144}{19194}Razumiješ li me, vojnièe?
{19231}{19262}Jasno i glasno.
{19267}{19300}U redu.
{19305}{19376}Moraš se vratiti u struju. | Uèini slijedeæi korak.
{19381}{19413}Prihvati taj posao.
{19418}{19451}Znaš, sad kad o | tome razmišljam...
{19456}{19530}...ni sudar naslijepo | nije loša ideja.
{19535}{19580}To je dio programa | u 12 koraka?
{19585}{19666}Ozbiljan sam. Kad si zadnji | put bio s nekim?
{19724}{19754}Dosta.
{19759}{19786}- Što? | - Dosta.
{19791}{19850}To bi moglo promijeniti taj tvoj | konvencionalni stav.
{19855}{19929}Moglo bi ti i navuæi smiješak | na tvoje lice.
{19934}{19978}Zar je loše nadati se da se ti | tjelesni èuvari...
{19983}{20037}...neprimjetno ubace u život | moga brata?
{20042}{20116}Nismo baš bili neprimjetni | u Afganistanu.
{20121}{20174}Slušaj, Bowden kaže | da je on najbolji.
{20179}{20217}Zar nije u tome bit ovdje?
{20222}{20270}Zaštititi život tvoga brata?
{20323}{20371}Uostalom, zar nismo inzistirali...
{20376}{20426}...na jasnoj akciji ovdje?
{20431}{20485}Znaš da mrzim kad vršiš | pritisak na mene.
{20490}{20544}- Da, znam. | - Ali, u redu.
{20578}{20638}Dakle, ubrzo imamo taj | hip-hop dogaðaj.
{20652}{20682}Uvijek sam ga se | pribojavala.
{20711}{20743}Bila sam veæ u tom klubu.
{20748}{20781}Bit æe pun ljudi, buèan...
{20786}{20822}...mraèan, pun obožavateljica...
{20827}{20906}...a sigurnosne mjere nikakve.
{20947}{21033}Èini se kao savršena prilika da | svoje deèke staviš na probu.
{21065}{21164}I zapamti, moj brat ne smije | ništa opaziti...
{21169}{21238}...osim ako to postane | neophodno potrebno.
{21529}{21592}- Hej, ovuda! | - Hvala!
{21610}{21663}- Slikajmo se. | - Hajde, èovjeèe.
{21668}{21721}Idemo. Oprostite, moje dame, | izvolite.
{21875}{21925}- Hej, Wayne! | - Uðite sada.
{21930}{21972}Pokažite svoje VIP propusnice. | Na listi ste.
{22028}{22084}Javljam se na dužnost, | gospodine.
{22295}{22377}Što ti je? Samo nastavi to | što radiš, dobro je.
{22448}{22524}U redu. Što misliš o onoj | dvojici tamo?
{22573}{22630}Uvijek ista igra. | Provjeri ih.
{22646}{22719}Da, dobro æemo se zabaviti | s tim. Pogledaj ovamo.
{23111}{23166}Trebat æe mi tjedan dana | koncentriranog Marvina Gayea...
{23171}{23218}...da isperem ovu buku iz glave.
{23270}{23326}- Jesi li spreman? | - Naravno.
{23331}{23370}U redu.
{23579}{23652}Želim svima dobrodošlicu.
{23657}{23714}Danas imamo posebnog | gosta u zgradi.
{23719}{23750}Svi znate tko je on.
{23755}{23831}Stvarno poseban gost. | Pozdravite jedinog, najveæeg...
{23836}{23898}...svjetskog prvaka teške | kategorije, Waynea Barclaya!
{23903}{23948}Svi zajedno!
{24780}{24816}Oprostite.
{24822}{24866}- Hej! | - Žao mi je.
{24902}{24996}- Oprosti, brate. | - Rekao sam da odemo odavde.
{25001}{25042}Gledaj kamo ideš, klaune!
{25106}{25176}Toliko o tome da ostane | neprimijeæen.
{25221}{25274}Moraš priznati da iskaèe.
{25279}{25331}Poput bolnog palca.
{25336}{25401}Mullinse, znam da si | mislio najbolje...
{25406}{25454}...ali ovo neæe iæi.
{25469}{25514}Nemoj više ništa reæi.
{25626}{25654}Ozbiljno?
{25659}{25705}To sam èula.
{25812}{25919}Možda bih trebao èekati vani | i paziti na auto.
{25924}{25965}Reæi æu Bowdenu.
{25970}{26007}Hvala.
{26638}{26678}Pošalji auto.
{26786}{26838}Phill, moram ti nešto reæi.
{26843}{26905}Ova gaža ne funkcionira.
{26935}{26970}Nisi ti kriv.
{26975}{27014}Ma daj, Clarence.
{27019}{27077}Osjetio sam tu vibru | u njenom uredu.
{27083}{27131}Loša kemija.
{27136}{27250}Nitko nije kriv. To je život, zar ne?
{27338}{27381}Evo auta.
{27821}{27864}- Nema autograma. | - Nema veze, guba.
{27869}{27914}Ovuda!
{27919}{27970}- Što je, curo? Kako se zoveš? | - Virginia.
{27975}{28014}- Virginia? | - Da.
{28103}{28134}- Wayne? Hajde, idemo! | - Drži se!
{28139}{28176}Wayne?
{28217}{28282}Idemo sada, Wayne!
{28295}{28360}Izvoli. Kako si, ljepoto?
{28445}{28498}- Razvalimo ovog kretena. | - Pištolj!
{28708}{28782}- Ostani dolje! | - Wayne! U auto!
{28843}{28902}- Uði u auto! | - U auto, Wayne!
{28927}{28974}- Uði u auto! | - Neka Barclay uðe u auto!
{28984}{29038}Hajde, èovjeèe, idemo!
{29068}{29100}- U auto! | - Tko si ti?
{29105}{29141}- Uði u auto. | - Wayne!
{29146}{29186}Ostani gdje jesi!
{29509}{29545}K vragu!
{29770}{29813}Bowden!
{30128}{30158}Hej...
{30223}{30254}Bowden...
{30283}{30318}Bowden...
{31903}{31965}Tužne li ironije...
{31970}{32025}...što stojim ovdje danas...
{32033}{32084}...nad lijesom...
{32100}{32149}...Clarencea Bowdena.
{32199}{32286}Jer, da nije bilo njegove akcije | u Kandaharu prije par godina...
{32291}{32349}...sada bi on stajao...
{32354}{32400}...nad mojim lijesom.
{32464}{32513}I uvjeren sam...
{32518}{32591}...da ovdje ima još | nekoliko ljudi...
{32618}{32660}...koji bi mogli to isto reæi.
{32820}{32886}Odano je služio | svojoj domovini...
{32915}{32972}...i brinuo se za | svoje prijatelje.
{33022}{33068}Zbogom, prijatelju.
{33113}{33154}Zbogom.
{33159}{33204}Oružje!
{33239}{33284}Pripremni...
{33304}{33346}Pucaj!
{33351}{33386}Repetiraj!
{33391}{33461}Spremni. Pucaj!
{33483}{33526}Spremni. Pucaj!
{33591}{33658}Spremni. Pucaj!
{34417}{34470}Eto, ljudi...
{34475}{34536}- Dobro izgledaš. | - Pazi na sebe.
{34716}{34765}G. Sauvage?
{34773}{34852}G. Sauvage? G. Sauvage!
{34879}{34924}Možemo li vas povesti?
{34983}{35042}Ne, hvala, htio bih biti sam.
{35071}{35170}Wayne i ja smo vam samo | htjeli izraziti suæut.
{35201}{35272}Vaš brat je dao svoj život za mene.
{35279}{35362}Nema mnogo ljudi koji bi to bili | spremni uèiniti za mene.
{35377}{35466}Da se mene pita, obojicu bih vas | preporuèio za medalju.
{35495}{35554}Ne osjeæam se baš kao heroj | u ovom trenutku.
{35603}{35681}Ima li mnogo ljudi poput vas, | g. Sauvage?
{35731}{35810}- Poput mene? | - Profesionalaca.
{35825}{35862}Ljudi na koje možeš raèunati.
{35867}{35907}Pazi!
{35934}{35972}Ima li kakvih problema?
{35980}{36058}G. Barclay, prava mi je èast.
{36067}{36132}Ja sam det. Teague iz odjela | za teške zloèine.
{36164}{36234}Vi ste Philippe Sauvage, bivši | vojnik U.S. Vojske?
{36239}{36298}- Da, jesam. | - Uhiæeni ste.
{36303}{36350}- Što? | - Ruke iza leða, gospodine.
{36355}{36422}- A da nam objasnite o èemu se radi? | - O incidentu u klubu.
{36427}{36498}Povreda zakona o oružju.
{36503}{36556}Vaši ljudi su uzeli njegovu | izjavu i pustili ga.
{36561}{36612}Izjavio je da ima dozvolu | za taj MP7.
{36617}{36662}Onaj kojim su ubijena | tri civila.
{36671}{36722}U samoobrani.
{36727}{36780}Bowden je rekao da | je sve sreðeno.
{36785}{36850}Sada je kasno da to | provjerimo s njim, ne?
{36855}{36886}Strpajte ga u auto.
{36891}{36930}- Kako? Što? | - Ovo je glupo.
{36935}{36992}Èekajte, ovo je sranje! | Zašto ne uhitite èovjeka...
{36997}{37038}...koji je upucao mog brata?
{37050}{37096}- Tko bi to mogao biti? | - Detektive...
{37101}{37146}Vi izlijevate vodu na govna | i zovete to umakom.
{37151}{37202}Moji odvjetnici æe kontaktirati | vaš glupi odjel.
{37207}{37262}- Unutar sat vremena. | - Vjerujte u to.
{37279}{37358}Zašto ih sami ne nazovete? | Još bolje...
{37377}{37446}...nazovite mene. | - Naravno da hoæu.
{37464}{37507}Želim vam ugodan dan.
{37779}{37841}Hej, Simcoe, što ima?
{37882}{37928}Tako je cool.
{37942}{37986}Dobro izgedaš.
{38026}{38064}Yo!
{38071}{38104}Gospoðo!
{38205}{38266}Gangsteri, to!
{38271}{38310}- Hej. | - Hej.
{38315}{38346}Znaš to. Idi, curo.
{38351}{38398}- Vrati se. | - Zašto?
{38417}{38522}Gospodo, svi èekamo danas. | Jeste li gladni?
{38550}{38606}G. Singletery, ono nekidan, | mi smo malo...
{38611}{38669}Nemoj sad o tome, pizdo!
{38727}{38766}Tvoji prijatelji?
{38777}{38824}Ne, ovo je ekipa | za temeljito èišæenje.
{38829}{38876}Zaboravili su iznijeti | neko smeæe.
{38915}{38959}Ekipa za èišæenje, ha?
{38994}{39076}Strièe T., da li ovo ima veze s | incidentom u koji je upleten...
{39081}{39122}Cynthia!
{39143}{39178}Cynthia!
{39183}{39226}Doði ovamo, draga.
{39231}{39269}Super izgledaš!
{39274}{39346}Jesi li upoznala sina moje sestre, | novog J. Cochrana?
{39351}{39452}Ne. Bog. Kako se zoveš?
{39488}{39562}Leonard, prestani sliniti. Zašto | ne odeš dami pripremiti piæe?
{39572}{39613}Upoznajte se, hajde!
{39655}{39730}A ja æu se pobrinuti | za moje drage prijatelje.
{39735}{39770}Znaš...
{39775}{39828}I ja razmišljam o upisu | na pravo.
{39833}{39871}Stvarno?
{40074}{40140}Vi, govnari, imali ste misiju.
{40145}{40192}Sa svim poštovanjem, Terrell...
{40197}{40237}...nismo oèekivali | da nas napadnu...
{40242}{40294}...tipovi s Uzijem.
{40306}{40390}Ne sjeæam se da sam te | pitao za objašnjenje.
{40395}{40446}I obraæaj mi se s "gospodine | Singletery"!
{40451}{40510}Hajde, faco, reci nešto!
{40535}{40602}Baš poput kurve. Hajde!
{40640}{40698}Da, srce.
{40714}{40768}Bebice moje!
{40777}{40830}Tu ste? Da, da...
{40835}{40906}Max, pravi si.
{40911}{40949}Tako je.
{40965}{41038}Da, da, bebice moje, | falio vam je tatica?
{41043}{41122}Falio vam je tatica? Tatica je | došao kuæi. Tu je, u redu?
{41127}{41161}Tako je.
{41200}{41271}Wayne Barclay je pizda.
{41290}{41386}I taj kreten je još živ i ugrožava | moje poslovne interese!
{41391}{41440}Jesam li rekao da mrzim | tog pizduna?
{41459}{41514}Da, mrzim ga!
{41522}{41615}Platio sam puno novaca da se | taj problem riješi, istina?
{41620}{41660}Istina?
{41755}{41814}Mislim da su bebice još gladne, | šefe.
{41845}{41906}Tate dugo nije bilo.
{41917}{41978}Nisu ih dobro hranili.
{41997}{42036}O, sranje!
{42099}{42141}Sviða vam se ovo?
{42378}{42418}Ovo je dobro, da...
{42454}{42509}Ovo je za vas, bebice. | Da, sve je to za vas.
{42514}{42610}Jednaki dijelovi za sve, | neæe biti favoriziranih.
{42633}{42710}Sada imam više opcija pred sobom.
{42715}{42766}Mogao bih tražiti | iskrenu ispriku.
{42771}{42810}I obeæanje da se | ovakav zajeb...
{42815}{42868}...neæe nikad više | ponoviti, ili...
{42873}{42958}Znam tko je ona pièka | koju ševi. Zove se Lydia.
{42963}{43026}- Lydia? | - Dok je još bila mršava...
{43031}{43113}...uvalio sam joj par puta jezik. | Ta pièka mi duguje, istina?
{43118}{43157}- Hajde, ispljuni! | - Èovjeèe, govorim...
{43162}{43230}...da kad Barclay iduæi put svrati | svojoj dragoj...
{43235}{43300}...doèekat æemo ga. | Razvalit æemo mu guzicu.
{43355}{43403}Sviða vam se ovo?
{43475}{43561}Nema nièeg ukusnijeg od friškog | komada sirove jetre.
{43615}{43690}U redu, izvest æemo plan s Lydiom.
{43695}{43735}I za dobro svih...
{43740}{43829}...nadaj se da se ta kurva | seksa u pravo vrijeme.
{43834}{43897}U najbolje vrijeme.
{43961}{43990}Hvala.
{43995}{44054}Potrudi se da sortiraš ostatak | ovoga do veèeras, molim te.
{44059}{44119}Moj brat želi zaposliti tog | èovjeka od sutra.
{44153}{44199}Bit æe napravljeno, gðice | Barclay, odmah.
{44325}{44374}Vi ovdje ne gubite vrijeme.
{44379}{44432}Nemam vremena za to.
{44437}{44532}Kratko æemo se zaustaviti u | V.A. -u i pokupiti vaše stvari.
{44549}{44618}- Moje stvari? | - Da, tako možete useliti k nama.
{44623}{44673}Ne brinite. | Imamo puno soba.
{44687}{44727}Slušajte, cijenim što se | brinete za...
{44732}{44773}Ne borite se sa mnom oko toga, | g. Sauvage.
{44778}{44844}Mi tamo stanujemo. | I tamo je Wayne najizloženiji.
{44882}{44931}Oprostite, ali...
{44936}{44969}Jesam li što propustio?
{44979}{45058}One noæi smo angažirali vas i | g. Bowdena za probu.
{45063}{45109}Uspješno ste prošli test.
{45114}{45198}Moj brat vas sada želi | zaposliti na stalno.
{45203}{45264}A kako g. Bowden...
{45269}{45308}...nažalost nije | više s nama...
{45313}{45381}...pretpostavili smo da æete | vi prihvatiti posao.
{45387}{45430}Želite da ja...
{45435}{45500}...budem u ekipi | osiguranja g. Barclaya?
{45505}{45539}Ne.
{45544}{45589}Želimo da budete voða ekipe.
{45654}{45765}Nije mi lako tako brzo donijeti odluku.
{45770}{45834}Ako je problem novac...
{45851}{45894}Nije to.
{45906}{45970}Upravo sam izgubio vrlo | bliskog prijatelja.
{45975}{46022}Znamo to.
{46033}{46101}Ali nije vam prvi put da ste | izgubili prijatelja u borbi.
{46123}{46160}Nije.
{46165}{46212}G. Sauvage...
{46232}{46298}Što bi Bowden bio | volio da napravite?
{46790}{46828}G. Sauvage...
{46833}{46894}Jeste li sigurni da | ne želite doæi k nama?
{46899}{46956}- Gðice Barclay... | - Zovite me Tamara.
{46961}{47032}Tamara, jeste li sigurni?
{47040}{47074}Mislim, o meni.
{47079}{47168}Znam da nismo zapoèeli kako treba...
{47173}{47254}...i to je bila potpuno moja greška.
{47277}{47324}Oprostite mi.
{47375}{47426}Zovite me Philippe.
{47440}{47478}U redu, Philippe.
{47497}{47600}Ponekad moja prezaštitnièka | duša izvuèe najbolje iz mene.
{47605}{47648}Odsada, Tamara...
{47659}{47712}...to možete prepustiti meni.
{48112}{48170}G. Barclay, hvala na dolasku.
{48183}{48212}Cijenim pratnju.
{48217}{48302}Mislite da æe gradonaèelnik | biti ljubomoran?
{48307}{48394}Igramo na sigurno dok ne | zatvorimo vaše napadaèe.
{48399}{48478}Ovuda, molim. Gospodo, ostanite | ovdje, neæemo dugo.
{48483}{48567}- Ja idem s g. Barclayem. | - Ne, vi ostajete ovdje.
{48572}{48646}Ovo je sjedište policije, | na sigurnom je. Vjerujte mi.
{48651}{48708}Super, shvatio sam.
{48800}{48862}Pretpostavljam da ste me doveli | ovamo zbog neke...
{48867}{48932}...povjerljive senzacionalne vijesti | o slavnom g. Singleteryju?
{48940}{48979}Sjednite, molim vas.
{49015}{49074}Poput, možda, na primjer...
{49079}{49142}...vijesti o njegovom skorom | uhiæenju?
{49156}{49234}Ne bih nikome trebao reæi, ali | vi kontrolirate situaciju.
{49239}{49326}Žao mi je, ali ne. Koliko znam, | njegov nos je èist.
{49332}{49380}Toèno.
{49385}{49438}Sigurno me Al-Quaida | želi izvuæi.
{49443}{49496}Bin Laden i ostali, to je?
{49513}{49592}Zar vas hrane tabletama za | glupost ovdje ili što?
{49599}{49648}Zašto gubim svoje prokleto | vrijeme...
{49653}{49687}G. Barclay...
{49692}{49740}...bacite pogled na ovo.
{49838}{49937}Htio sam vam nešto isprièati | o vašem novom tjelesnom èuvaru.
{49942}{50002}Sjednite, molim vas, | morate ovo èuti.
{50131}{50190}Philippe Sauvage je razvio neke...
{50195}{50265}...nazovimo to psihološke | probleme koji su se...
{50270}{50358}...prvo pojavili u Afganistanu i | konaèno razvili u Iraku.
{50364}{50418}U Mosulu je došlo do | masakra civila.
{50423}{50462}Najviše je bilo djece.
{50487}{50563}Novinske agencije nisu saznale | cijelu prièu, ali ja jesam.
{50575}{50613}Philippe Sauvage je onaj...
{50618}{50698}...koji je vlastoruèno masakrirao | tu djecu.
{50706}{50790}Po mišljenju vojnog psihologa, | on je hodajuæa tempirana bomba.
{50795}{50866}A prije nego što su ga pustili | iz bolnice, bio je zatvoren...
{50871}{50956}...na psihijatriji. | Želite znati zašto?
{50961}{51057}Zato što ga je vojska smatrala | preopasnim da bude na slobodi.
{51062}{51124}Zašto mi to sve prièate?
{51129}{51174}Samo se trudim biti temeljit.
{51179}{51273}Niste shvatili da sam ja jedan | od vaših najveæih obožavatelja.
{51327}{51429}Znam da èesto to traže od vas, ali...
{51466}{51514}...biste li mogli?
{51547}{51588}Imate li flomaster?
{51724}{51774}Taj tip, Sauvage...
{51779}{51837}...bit æe odgovoran za | vašu sigurnost.
{51842}{51891}I sigurnost vaše obitelji. | Vaše sestre.
{51905}{52010}Ne bih htio to imati na savjesti | ako se nešto loše desi.
{52367}{52397}Kako vam se sviða | kuæica?
{52425}{52521}Kuæica? Vidio sam desetoroèlanu | obitelj u manjoj od ove.
{52548}{52634}Trebali ste vidjeti gdje smo | moja braæa i ja odrasli.
{52645}{52713}Vaša braæa? Koliko?
{52777}{52817}Samo jedan.
{52847}{52893}Želite pogledati ostatak kuæe?
{52927}{52960}Naravno.
{52965}{53012}Pitam se gdje se Wayne zadržao.
{53239}{53295}Dobrodošli u Wayneov svijet.
{53321}{53426}- Želite li piæe? | - Ne, hvala.
{53431}{53542}Dajte, samo jedno. Službeno | još niste na dužnosti.
{53547}{53617}Nije to. Ne bih smio piti.
{53651}{53722}Imao sam problema s time.
{53756}{53781}Razumijem.
{53786}{53838}- Oprostite što sam inzistirala. | - Sve je u redu.
{53867}{53914}Dakle, koliko æe vam ljudi | trebati u ekipi?
{53919}{53957}Pokušavam raditi na budžetu.
{53962}{54074}Otprilike šestorica. | Upravo sam obavio par razgovora.
{54123}{54230}Izvolite. Dobra stara H2O, | ne možete biti protiv.
{54257}{54370}- Za novo partnerstvo. | - Za novo partnerstvo.
{54566}{54642}- Igrate li biljar? | - Nisam veæ dugo.
{54664}{54713}Zašto ne bismo odigrali partiju?
{54751}{54801}Pogledajmo što znate.
{54848}{54934}Philippe, imate li obitelj?
{54951}{54988}Ne baš.
{55003}{55058}Bowden i neki od ljudi | sa sprovoda...
{55063}{55113}...to je moja obitelj.
{55118}{55225}O, hvala. | Jeste li bili oženjeni?
{55230}{55277}Nisam nikad uspio dovoljno | dugo sjediti mirno.
{55372}{55456}- A što je s vama? | - Isprobala sam to jednom.
{55461}{55513}Sada sam udana za posao.
{55536}{55598}Mislite da je lako | s mojim bratom?
{55603}{55658}Koliko se god sjeæam...
{55663}{55750}...on je uvijek volio trošiti, | a ja štedjeti.
{55794}{55857}On mi je platio školovanje.
{55880}{55989}Sada ga moja diploma sprjeèava | u razbacivanju novca.
{56077}{56106}Vi ste na redu.
{56217}{56298}Sjeæam se nekih od njegovih borbi.
{56311}{56450}Bio je vrlo agresivan, stalno | u napadu, bez opuštanja.
{56463}{56502}Dok ga mi èekamo...
{56742}{56779}Da, to. To! Divno.
{56784}{56892}Da, da. O tome govorim!
{56929}{57021}Hajde, Barclay. Da! Tako! | Da, hajde, Wayne!
{57034}{57069}To!
{57119}{57182}E, o tome govorim! | Barclay! Barclay!
{57278}{57321}Hej, Wayne!
{57378}{57493}Upravo sam upoznavala g. Sauvagea | s obiteljskom prošlošæu.
{57498}{57540}- Obiteljskom prošlošæu? | - Da.
{57545}{57596}Dobra zamisao.
{57649}{57706}Zašto mu ne daš | neki od ovih DVD-a?
{57711}{57749}Može ih gledati kod kuæe.
{57761}{57876}Wayne, bila sam tako slobodna | da ga smjestim u kuæu za goste.
{57881}{58005}Kakvog smisla ima da je u hotelu | kad ga ovdje stalno trebamo?
{58044}{58117}Nisam je zaposlio samo zato što | mi je sestra.
{58140}{58173}Ona uvijek razmišlja.
{58218}{58273}Uvijek je korak ispred igre.
{58278}{58315}Imate pravo.
{58334}{58412}- Vi ste sretnik. | - Oprostite.
{58460}{58502}G. Barclay...
{58526}{58595}Možemo li pojasniti par stvari | prije nego stupim na posao?
{58600}{58651}Jeste li s Tamarom | dogovorili plaæu?
{58656}{58765}Ne želim o tome, nego o ljudima | koji su bili na sprovodu.
{58775}{58818}Kada okupim svoju ekipu...
{58823}{58894}...možete ih poslati natrag u | teretanu u kojoj ste ih našli.
{58933}{59010}Ne trebaju nam amateri. | Ako ja budem vodio taj posao...
{59015}{59070}...želim najjaèe od najjaèih. | Velièanstvene.
{59110}{59168}Onda neka tako bude. | Ekipa velièanstvenih.
{59173}{59220}BARCLAY | Boksaèka dvorana
{59459}{59507}Ovdje sam nauèio boksati.
{59528}{59615}Bilo mi je 15 god. Kad sam | prvi put došao ovamo.
{59688}{59738}A sada je taj prostor moj.
{59743}{59813}Polako ga pretvaram u umjetnost.
{59819}{59905}Ljubavne muke, zapravo. | Pazi na glavu!
{59927}{59990}Financijski, ovo mjesto je | prava propast.
{60111}{60162}Hej, Cujo!
{60167}{60215}Dobro si danas, zar ne?
{60220}{60264}Što ima novog? | Hoæeš se kladiti?
{60283}{60330}Kako si?
{60335}{60411}- Idi izmlati nekog. | - Što radiš, èovjeèe?
{60635}{60690}Provest æemo jutro promatrajuæi.
{60695}{60776}To æe ti omoguæiti da izabereš.
{60815}{60898}- Da izaberem? | - Da, za ekipu.
{60907}{60971}Imamo nekoliko dobrih ljudi | ovdje, Sauvage.
{61043}{61138}- Slažeš se? | - Moramo razgovarati.
{61159}{61242}- Zar veæ ne razgovaramo? | - Nasamo.
{61254}{61310}Na sprovodu si me pitao...
{61315}{61385}...postoji li još tko poput | mene, zar ne?
{61390}{61426}Da. Toèno. | Najjaèi od najjaèih.
{61431}{61499}I ništa se nije promijenilo. Još | možeš dovesti svoje ljude.
{61504}{61546}Ali oni æe raditi s nekoliko | mojih ljudi.
{61555}{61594}Dogovor nije bio takav.
{61643}{61738}U redu, zapamti ovo. | Ja pišem èekove.
{61743}{61806}Ja odluèujem kakav æe nam | dogovor biti.
{61811}{61913}Pretpostavljam. Upravo si odluèio. | Ja ne sudjelujem u tome.
{61924}{61982}Ne, èekaj, èekaj.
{61987}{62040}- Èekaj malo, èekaj. | - Mullins, makni se.
{62045}{62087}Wayne zna ove ljude.
{62092}{62162}Neke od njih i godinama. | Vjeruje im.
{62187}{62300}Kako da radim svoj posao i èuvam | istovremeno amatere?
{62305}{62356}Ma daj!
{62361}{62420}Nemoj mi reæi da nije bilo | trenutaka u tvom životu...
{62425}{62474}...kad si i ti bio amater.
{62479}{62561}Ja znam da sam ja to bio kad sam | prvi put došao ovamo.
{62572}{62628}Ali netko je u meni vidio | potencijal.
{62633}{62702}Nema razloga da ti ne napraviš | isto s par mojih ljudi.
{62839}{62878}Hej, Cujo!
{62896}{62958}Dobro, deèki. Dosta je.
{62963}{63002}Gino, Kim!
{63265}{63298}U redu, Kim.
{63351}{63454}- Tko je ovaj? | - To je Kim, crni pojas u tae kwon do-u.
{63499}{63586}Zašto on nije bio u zaštitarskoj | ekipi u klubu?
{63591}{63662}- Nije se uklopio? | - Zbog visine.
{63682}{63724}To je ponekad dobro.
{63729}{63808}Opaki tipovi ne moraju znati | da je on tvoj tjelesni èuvar.
{63975}{64084}Molim! Što? Isprièaj me.
{64089}{64181}Reci inspektorima da si mogu | pravila strpati u guzicu.
{64366}{64445}Prièekat æu vani. Prijatelj | mi je došao u grad.
{64450}{64492}Želim biti siguran da se nije | izgubio dolazeæi ovamo.
{64497}{64540}Da te ona prièeka, ili...?
{64545}{64641}Ne, dosta je briga i bez ženske u ekipi.
{64655}{64690}Žao mi je.
{64730}{64798}Hej, èovjeèe, dovoljno si jak | da ideš u Irak...
{64803}{64862}...ali kod kuæe je prièa drugaèija?
{64975}{65062}Ovo nije igra. | Trebam tjelesne èuvare.
{65097}{65172}Jesi li spremna primiti metak | umjesto g. Barclaya?
{65226}{65288}Spremna? A vi, deèki?
{65336}{65442}Svi vi. | Bilo tko od vas?
{65523}{65558}Samo mi daj priliku.
{65595}{65674}Hajde, Sauvage, daj joj priliku.
{65759}{65802}Ona se ne šali.
{65951}{66058}- Pokaži nam što znaš, vojnièe! | - U redu, Sauvage! Idemo!
{66072}{66127}- Hajde! | - Pazi na ljevicu.
{66317}{66354}Dobro ti ide!
{66585}{66614}Pazi, pazi!
{66799}{66862}Samo naprijed, curo! | Samo naprijed!
{66985}{67038}Hej, Sauvage, dobra je, ha?
{67157}{67220}- Ti si kandidat. | - Ja sam što?
{67225}{67325}Kandidat. Zapoèinješ sutra | trening za tjelesnog èuvara.
{67395}{67502}Upoznaj se s instruktorom. | Vodnik Casey Bledsoe.
{67507}{67538}Bog daj!
{67559}{67642}Sauvage, nisi mi rekao da je | Roy Rogers u igri.
{67685}{67756}Donio sam nešto kamuflaže, | gospodine.
{67819}{67852}Ovako je bolje?
{68013}{68052}Blagi Bože!
{68431}{68492}Nemojte mi reæi da ste umorni!
{68522}{68570}Idemo unutra, | èeka nas još posla.
{68829}{68868}Hej, hej, pazi na odijelo!
{68897}{68976}Što se dogaða? | I ti ovo zoveš zaštitom?
{68981}{69040}Može biti gadno. Možda te | malo protresu.
{69058}{69124}- Ali ostat æeš živ. | - Da, baš.
{69129}{69249}- Istina, šefe? | - Toèno, Casey. Ponovi to.
{69326}{69397}- Ne, ne! Ne tako! Lijevu ruku gore! | - U redu.
{69402}{69459}Ne trudi se biti previše | neobièna.
{69464}{69518}Ne drži oružje ovako. | U redu?
{69523}{69558}- U redu. | - Mogla bi sresti...
{69563}{69643}...nekoga tko ga tako drži. | Taj æe promašiti.
{69648}{69693}- Ja neæu. | - Toèno.
{69698}{69786}Sada ubaci šaržer kao obièno.
{69791}{69877}Otkoèi, kao i obièno. | Odaberi svoju metu.
{69887}{70024}Pozicija nogu. | Sjeæaš se, stabilna, jaka. Diši.
{70034}{70077}Opusti se i pucaj.
{70186}{70294}Ovo je bilo dobro!
{70323}{70360}Na tebi je red!
{70377}{70454}G. Sauvage, | jeste li ubili mnogo ljudi?
{70663}{70710}- Što je to na krovu? | - Pogledaj!
{70831}{70873}Imam ga!
{70902}{70942}Èisto!
{71207}{71254}G. Sauvage?
{71332}{71363}- G. Sauvage? | - Da...
{71368}{71461}- Jeste li dobro? | - Na tebi je red.
{71498}{71538}- Uzmi revolver. | - U redu.
{71572}{71632}Dobro, opusti se.
{71830}{71882}Odmor, vojnièe!
{71963}{72049}Ponekad volim ovdje sjetiti noæu...
{72057}{72147}...i gledati zvijezde. | To me smiruje.
{72240}{72317}Evo. Izvolite.
{72355}{72394}Dobra stara H2O.
{72406}{72441}Baš kako je vi | volite, je li?
{72446}{72489}Tako je. | A što vi pijete?
{72494}{72553}Uveli smo nova pravila za piæe.
{72558}{72613}Ne pitaj, ne govori.
{72805}{72876}- Smijem li biti malo znatiželjna? | - Naravno!
{72891}{72950}Casey je nešto govorio o djeci.
{73054}{73090}To je bilo u Iraku.
{73122}{73212}Casey i ja smo slijedili | neke teroriste.
{73217}{73274}A tada...
{73299}{73354}Jedan od njih je ušao u školu.
{73476}{73514}I...
{73543}{73613}Veèeras je oblaèno.
{73623}{73688}Nema zvijezda, zar ne?
{73760}{73824}Brine me sutrašnji dan, | Philippe.
{73829}{73883}Otvara se sportski centar.
{73888}{73966}Doæi æe gradonaèelnik | i još masa ljudi.
{74032}{74118}- Jeste li sigurni da smo spremni? | - Ne baš.
{74151}{74248}Ali još uvijek èekam da se | pojave neki moji deèki.
{74274}{74387}Prepustite brige meni. Može?
{74410}{74509}- Pokušat æu. | - I pokušajte spavati.
{74548}{74581}Je li to zapovijed, | pukovnièe?
{74618}{74662}To je zapovijed.
{74979}{75021}Laku noæ, Tamara.
{75066}{75099}Laku noæ.
{75935}{76004}O, doðavola, što...?
{76009}{76091}- Hej, ovo nije obaranje u nogometu! | - Naravno da nije.
{76096}{76132}Koji k...?
{76163}{76234}Možeš li mi reæi zašto tako | njuškaš okolo?
{76239}{76318}Ja sad njuškam? E, kad veæ | govorimo o loncu...
{76323}{76395}- O èemu to prièaš? | - O tome æemo kasnije.
{76400}{76446}A sad se idem malo provozati.
{76451}{76542}Provozati? U ovo doba noæi?
{76547}{76644}Da, s Cujom, jednim od tvojih | uèenika. Èeka me na ulici.
{76698}{76732}Onda ja uzimam saèmaricu.
{76741}{76795}Upravo sam ti rekao. | Imam èuvara, u redu?
{76800}{76842}Pa ti si mu trener.
{76847}{76882}Nije još spreman | za samostalne akcije.
{76887}{76925}Nijedan od njih nije.
{76940}{77015}U redu, èovjeèe. | Imam privatni sastanak...
{77020}{77092}...s izvjesnom mladom damom. | Razumiješ?
{77097}{77149}Ima li razloga da ona ne može | doæi ovamo?
{77188}{77258}Slušaj, to je duga prièa. Sestra | misli da mi Lydia kvari image.
{77279}{77309}Ali ovaj malac...
{77329}{77406}...je napaljen noæas, èovjeèe! | Napaljen, kužiš?
{77411}{77457}Onda, mogu li obaviti svoj | posao? Mogu li? A?
{77462}{77523}Ili ja uzimam saèmaricu | ili ti ne odlaziš.
{77528}{77581}Osim ako želiš da ovi murjaci | idu s tobom.
{77586}{77661}Da ih hoæu, zar bih se penjao | preko moje proklete ograde?
{77759}{77825}I znaš, postaješ najveæi | dosadnjakoviæ, znaš to?
{77830}{77908}Da. Za to me i plaæaš.
{78347}{78381}Osjeæaš li ovo?
{78407}{78460}Možda, kad bih razumio | što oni govore...
{78465}{78565}...osim: "kujo, ho, govnaru"...
{78650}{78730}Zašto mi ne pomogneš | da to shvatim?
{78748}{78805}A što to petljate ti i | moja sestra?
{78817}{78862}- Što? | - Èuo si.
{78867}{78944}Kokteli na mjeseèini, sve te | gluposti. Imam oèi, èovjeèe.
{78949}{79025}Prvo i prvo, nitko ne petlja.
{79036}{79114}A ja sam onaj koji bi tebe | trebao držati na oku.
{79139}{79237}- Reci mi da te nije poljubila! | - Ti to zoveš poljupcem?
{79242}{79302}Kljucnula me je u obraz.
{79319}{79385}Da, a kasnije dolazi na red | lizuckanje drugih mjesta.
{79393}{79438}Èovjeèe, znaš kako to poèinje.
{79443}{79535}To nije smiješno, sestra mi je!
{79587}{79676}Gospodine, moj si pretpostavljeni.
{79681}{79729}Ona je, pak, izvršni službenik.
{79734}{79830}Ne obraæam se pretpostavljenima | kao braæi.
{79835}{79890}Dobro. Samo tako i nastavi.
{79957}{80026}Hoæeš li skinuti taj smiješak | s lica, vojnièe?
{80056}{80093}Da, gospodine.
{80242}{80280}Moram iæi.
{80326}{80357}On je tu.
{80388}{80471}Ne sada, budalo. Traži autogram | u svoje slobodno vrijeme.
{80476}{80506}Idiote!
{80575}{80642}Hej, ne ideš dalje!
{80651}{80690}Iza kuæe je aleja.
{80703}{80737}Trebam je provjeriti.
{80767}{80818}Ono što ti treba je jedna | uspaljena...
{80823}{80902}...divlja, gola, skandalozna guzica | samo za tebe. To ti treba.
{80917}{80977}Ne s mojom sestrom, ali to je | ono što trebaš.
{80982}{81046}Mislio sam da smo tu stvar | riješili.
{81078}{81202}Ozbiljno, èovjeèe, to bi uèinilo | èuda tvom krutom držanju.
{81259}{81298}Da, to su mi veæ rekli.
{81323}{81374}Znaš što? Govorit æu | s Lydijom.
{81393}{81442}Možda te ona može spetljati | s nekom prijateljicom.
{81467}{81505}Neæe biti potrebno.
{81510}{81589}Ona ima par sexy frendica, razmisli!
{81958}{82009}Što nije u redu, ljubavi?
{82031}{82101}Veæ me dugo nisi posjetio.
{82115}{82200}Da, bio sam zauzet.
{82451}{82514}Tamara me još uvijek ne voli.
{82520}{82558}O tome se radi?
{82563}{82650}Nemoj misliti da mi nareðuje | gdje i s kim da se sastajem.
{82715}{82760}Sada ona nije tu negdje, je li?
{82765}{82796}Ma nije.
{82801}{82854}Ali sada imam novog èuvara.
{82887}{82957}A taj malo preozbiljno | shvaæa svoj posao.
{83058}{83154}E, pa ja sam tvoj tjelesni èuvar | u spavaæoj sobi.
{83167}{83269}I postat æu stvarno ozbiljna.
{83963}{84026}O, sranje!
{85215}{85242}Cujo zove
{85264}{85343}U redu. Dakle, taj bolesnik je | ispred kuæe.
{85348}{85402}Vjerojatno je to jedan iz | Barclayeve ekipe.
{85407}{85474}Zaustavit æeš ga ako se dovuèe | do kuæe, zar ne?
{85479}{85533}Naravno. | Misliš da je doveo još nekoga?
{85538}{85610}Nisam vidio tog kurvinskog | èuvara, niti sam vidio murjake.
{85615}{85662}Onda uèinimo to.
{86104}{86151}- G. Sauvage! | - Nazovi Caseya.
{86156}{86201}Reci mu da odmah doðe ovamo.
{86209}{86286}- Ti ostani u autu. | - U redu, da, da.
{86291}{86333}Poèni rabiti svoj COMSET.
{86338}{86388}Dobro, dobro, O.K.
{86751}{86831}- Veæ odlaziš, dušo? | - Da.
{86845}{86921}Znaš da imam tu stvar sa | sportskim centrom sutra.
{86969}{87043}Ali mislila sam da možeš | provesti noæ sa mnom.
{87067}{87122}Volio bih da mogu.
{87127}{87205}Znaš, gradonaèelnik dolazi tamo, | i sve to. Moram iæi.
{87210}{87247}Iduæi put.
{87282}{87354}Hej, Lydia, što se dešava? | Je li ovdje?
{87359}{87405}- Ne, nije. | - Tko je to?
{87410}{87454}Neka budala koja želi tvoj | autogram.
{87459}{87501}Dat æu mu šaku u glavu | umjesto autograma!
{87514}{87542}- Dušo, èekaj! | - Mièi se!
{87547}{87598}- Sranje! | - Glupa kuèko!
{87603}{87657}- Smiri se, èovjeèe! | - Ne glumi junaka, Barclay!
{87662}{87722}- Ulazi ovamo, ništarijo! | - Smiri se, O.K.?
{87727}{87766}Nastavi hodati!
{87810}{87841}U redu.
{87846}{87916}Ako znate koju molitvu, najbolje | da je sad izmolite.
{88094}{88144}Predaj pištolj, kretenu!
{88475}{88524}Jebeni kretenu!
{89018}{89050}Jebeno štakorsko kopile!
{89428}{89517}Tko te je poslao? Ona ništarija | Terrell?
{89543}{89572}Govori, govno jedno!
{89577}{89622}Ja æu ga prisiliti da govori!
{89627}{89662}Hej, dušo, jebote!
{89741}{89806}Digni se! Koji ti je kurac?
{89887}{89942}U redu, u redu, imao si pravo.
{89971}{90005}Odjebi tamo!
{90010}{90050}Dolje!
{90147}{90186}Gle što sam našao vani.
{90191}{90238}Zar nisi veæ trebao biti | u krevetu, mali?
{90274}{90352}- Dobar posao, Cujo! | - Mama ti zna da si tako kasno vani?
{90438}{90486}Propustio sam zabavu, je li?
{90619}{90664}- Uzimamo ratne zarobljenike? | - A zašto?
{90698}{90789}- Ujutro moraju iæi na kontrolu. | - Rekao sam: Ubij ga.
{90805}{90857}- Veæ uèinjeno. | - O, ne, Cujo, ne!
{90862}{90910}Hajde, daj mi barem jednoga. | Samo jednoga.
{90915}{90958}Ostavi ti njih murjacima.
{90971}{91092}To bi im bio dovoljan dokaz da | je Terrel prekršio uvjetnu.
{91097}{91147}To ionako neæe ništa znaèiti.
{91171}{91238}Ti si mrtav èovjek, Barclay!
{91247}{91314}I ti, a i ti!
{91359}{91398}A pogotovo ti, kujo!
{91403}{91450}- Kujo? | - Hej, dušo!
{91455}{91510}- Što? | - Lydia! Smiri se.
{91589}{91645}Hoæeš i komadiæ od mene, | ništarijo?
{91668}{91738}- Imaš li ti sestru? | - Ovo je previše.
{91749}{91848}Imam otvorenje tog sportskog | centra za manje od šest sati.
{91853}{91927}Èekaj, èekaj. Zar ideš tamo?
{91932}{91997}Da, gradonaèelnik dolazi.
{92002}{92060}Da, a možda i još neka | naoružana ekipa!
{92065}{92136}Daj, èovjeèe, kad æeš napokon | poèeti slušati?
{92147}{92186}Naša ekipa još nije spremna.
{92219}{92310}Veèeras si bio ovako blizu | da te ukokaju.
{92315}{92382}Da, a ti si se isprsio.
{92387}{92449}I zaraðuješ svoj novac, èovjeèe.
{92454}{92506}A ja od tebe oèekujem da | nastaviš na isti naèin.
{92511}{92552}Na otvorenju.
{92583}{92619}Idemo!
{92651}{92713}Ni rijeèi o ovome mojoj sestri!
{92718}{92804}Ako dozna za ovo, poludjet æe. | U redu?
{92809}{92892}- Razumiješ me, zar ne, Sauvage? | - Razumijem.
{92929}{93002}Dobar si ti èovjek. Dobar.
{93215}{93285}U redu, idemo!
{93328}{93360}SVEÈANO OTVARANJE | SPORTSKOG CENTRA
{93365}{93437}DOBRODOŠLI U SPORTSKI | CENTAR BARCLAY
{93802}{93834}Ovo je sranje.
{93839}{93873}Bez zezancije.
{93883}{93943}Davim se od ovog ovratnika.
{93948}{94009}I od svega ostalog.
{94021}{94050}Ova školska djeca.
{94137}{94170}Phil!
{94208}{94261}U redu, opet imam opsesije.
{94266}{94350}Ali vrlo lako se može dogoditi | da zapucamo u njihovom smjeru.
{94355}{94405}Koga smo došli èuvati?
{94429}{94498}Znam, znam. Stvarno mrzim | sve ovo.
{94626}{94682}- Hej, Big Mo! | - Svi su tu.
{94687}{94742}- Èekaj! | - Gradonaèelnik stiže za pet minuta!
{94747}{94784}Izvoli.
{94800}{94842}Predstava poèinje!
{94892}{94973}G. Barclay, moram vam nešto reæi | što možda ne želite èuti.
{94978}{95013}Onda nemojte reæi.
{95018}{95102}Odliène sam volje, Sauvage, | nemoj me oneraspoložiti!
{95127}{95164}Možeš to meni reæi, Philippe.
{95188}{95243}Tamara, bolje bih se osjeæao | kada bi ti otišla tamo...
{95248}{95306}...i održala govor umjesto | tvog brata.
{95331}{95377}U redu, da, baš.
{95382}{95426}Možda sam trebao seku | poslati u ring...
{95431}{95480}...kada sam se borio | protiv Tysona.
{95485}{95538}- Wayne! | - Poèinjem vjerovati onim ljudima...
{95543}{95598}...koji su te | proglasili ludim.
{95635}{95704}A koji bi ti ljudi mogli biti?
{95731}{95790}- A što sam ti rekao? | - Gradonaèelnik za 4 minute.
{95803}{95905}Onima koji drže govor savjetujem | da odu u WC.
{95939}{95985}Razgovaraj s njim.
{96003}{96060}Rekao sam da nemam vremena!
{96115}{96159}O èemu on to govori?
{96164}{96213}Razgovarat æemo o tome | u prikladnije vrijeme.
{96218}{96254}Nakon otvorenja.
{96304}{96333}Ali zapamti ovo:
{96338}{96426}Rado bih održala govor sama | kad bi mi on to dozvolio.
{96431}{96464}Upozorila sam te | da je tvrdoglav.
{96477}{96572}Oèekivao sam cement, | ali ne i titanij.
{96577}{96654}Philippe, Wayne je dobar èovjek. | Ima dobre namjere.
{96659}{96716}Ne dopusti da mu se što dogodi.
{96736}{96793}Ne znam da li bih mogla još | jednom ovo proživjeti.
{97042}{97073}- G. Gradonaèelnièe! | - Gradonaèelnièe, ovamo!
{97078}{97118}G. Gradonaèelnièe, | smiješak molim!
{97127}{97166}Imate li vremena za intervju?
{97171}{97208}- G. Gradonaèelnièe! | - Možemo li dobiti vašu izjavu?
{97213}{97242}G. Gradonaèelnièe, molim vas!
{97479}{97558}- U redu, idemo! | - Bit æeš fantastièan, braco!
{98193}{98248}Hej! Šampion je tu!
{98409}{98460}- Hej, šampione! | - Što se dogaða?
{98465}{98543}- Hvala, hvala! | - G. Barclay, mogu li dobiti autogram?
{98548}{98622}Kakva je ovo ludnica? Mièi se! | Samo želim autogram!
{98627}{98694}Samo sam htio autogram, èovjeèe!
{98748}{98822}Hej, kako si? Hvala. Hvala vam | što ste došli.
{98837}{98894}Hvala, hvala! Kako si?
{99099}{99146}- Barclay za gradonaèelnika! | - Evo ga, tu je!
{99192}{99229}Hvala!
{99271}{99302}Što se dogaða, gradonaèelnièe?
{99457}{99518}Tamara, drago mi je što vas | vidim. Izvolite sjesti.
{99635}{99661}Barclaya za predsjednika!
{99732}{99826}Èuo neke od vas kako vièu | "Barclay za gradonaèelnika".
{99906}{99992}Ne vidim što sve ne bi mogao | ovaj èovjek, taj bivši prvak...
{99997}{100090}...teške kategorije, koji je postao | uspješan biznismen...
{100095}{100133}...sjajan graditelj...
{100142}{100182}...poštovani lider...
{100187}{100224}...i stup moæi...
{100229}{100312}...u zajednici koja oèajnièki treba | pozitivne uzore.
{100317}{100358}- Amen. | - Ali molim vas...
{100363}{100432}...nemojte ga navoditi | ni na kakve ideje.
{100437}{100518}S tim èovjekom se ne bih rado | sreo ni u kojoj areni.
{100553}{100618}Dame i gospodo, | g. Wayne Barclay!
{100813}{100859}Barclay!
{100931}{101012}Barclay! Barclay!
{101270}{101318}Barclay! Barclay! Barclay!
{101323}{101358}Barclay! Barclay!
{101363}{101406}- Barclay! | - Uoèio sam metu.
{101416}{101478}Crnac, preko 185 visine.
{101483}{101546}Skoro direktno | ispred podija.
{101654}{101688}Mohawk, s ožiljkom na licu?
{101704}{101733}To je taj.
{101791}{101898}Kim i Cujo, nastojte se | približiti tom èovjeku što brže.
{102003}{102048}U redu, veliki Wayne!
{102060}{102132}Znate, prije mnogo vremena...
{102177}{102226}...igrao sam se na ovim ulicama.
{102238}{102294}Ali u to vrijeme i nisu bile | naroèito lijepe.
{102308}{102372}Na ovim sam se ulicama | nauèio tuæi.
{102414}{102474}Danas tu ne vidim toliko | tuènjava.
{102499}{102566}Danas poèinjem | opažati napredak.
{102611}{102689}Danas su se ostvarili snovi | i meni...
{102694}{102746}...i ovoj zajednici.
{102829}{102865}Pištolj!
{102899}{102936}Mièi se!
{103190}{103238}Pusti mi ruku, èovjeèe! | Makni se od moje ruke!
{103596}{103656}- Digni guzicu! | - Što tu imaš?
{103667}{103703}Vidjeli smo da uzima pištolj!
{103726}{103813}- Što se dogodilo? | - Objasnit æu ti kasnije, na sigurnom.
{103827}{103876}- Ovo je sranje! | - Hej, ti si govno!
{103919}{103954}Misliš na ovo?
{103959}{104042}K vragu, propustio sam poziv!
{104116}{104146}A još k tome, | mama me je zvala.
{104179}{104226}Trebao sam vas sve zatvoriti, | sve vas kretene.
{104235}{104294}Sve do zadnjega.
{104318}{104408}Osjeæaj mira je prevladavao, | ali malo prije je skoro buknula...
{104413}{104480}...pobuna kad se èuvarima bivšeg | šampiona teškaša W. Barclaya...
{104485}{104561}...uèinilo da vide èovjeka | s oružjem.
{104635}{104692}Sa mnom je ovdje poruènik | Teague iz gradske policije.
{104701}{104731}O, Bože!
{104736}{104810}Opišite nam, molim vas, što je | taj gospodin imao u ruci?
{104815}{104880}Imao je mobitel.
{104887}{104926}Ovdje je gospodin kojega | je zlostavljala...
{104931}{104986}...ova amaterska | grupa tjelesnih èuvara.
{104991}{105081}On planira podnijeti tužbu | protiv g. Barclaya za napad...
{105086}{105149}...i vjerojatno za povredu | njegovih civilnih prava.
{105284}{105358}- Gledaš ovo na TV? | - Da.
{105467}{105517}Ništa nismo mogli napraviti, | Terrell.
{105522}{105566}Ovi gadovi su nam bili | za leðima cijeli dan.
{105571}{105616}Da, reci mu, stari.
{105643}{105685}Prelazimo na plan B.
{105759}{105806}U redu, gangsteri.
{105821}{105850}Prelazimo na plan B.
{105855}{105906}Što je plan B?
{105987}{106046}Dopusti da ti dam jedan savjet.
{106051}{106150}Ako želiš srati u društvu velikih | pasa, ne pišaj sa psiæima.
{106155}{106247}Jesu li Barclayevi èuvari | imali razloga za takvu nervozu?
{106255}{106328}Gospodin kojeg su napali je | Afroamerikanac, pa je moguæe...
{106333}{106409}...da je njihova prevelika revnost | bila rasistièki motivirana.
{106421}{106457}- Nevjerojatno. | - Molim te.
{106465}{106538}Taj tip je toliko pun govana da | mu oène jabuèice postaju smeðe.
{106543}{106626}Da, smeðe oèi su htjele | završiti igru.
{106631}{106710}Od gradonaèelnika sam u pet | minuta postao kapetan Kangaroo!
{106715}{106787}Tako bih mogao biti na pozornici | i pjevati "Mammy"!
{106792}{106822}Smiri se, Wayne.
{106827}{106881}Taj èovjek daje sve od sebe | da te zaštiti.
{106886}{106948}- A ja se trudim zaštititi tebe. | - Od èega?
{106981}{107035}- Zašto njega ne pitaš? | - Što to?
{107040}{107129}Pitaj ga zašto ga je Vojska | zatvorila na psihijatriju.
{107134}{107162}- Što? | - Da, to je istina.
{107167}{107208}Zašto joj to ne kažeš, je li?
{107213}{107270}- Reci joj što je bilo! | - O èemu to govoriš?
{107275}{107314}Taj èovjek je ubojica. | Neka budem proklet...
{107319}{107414}...ako dopustim da taj psihotièni | shizofreni luðak povrijedi moju sestru.
{107419}{107456}Wayne!
{107501}{107558}Tko se ovdje luðaèki ponaša?
{107759}{107832}- Jessie, ostani s njom. | - Nema problema.
{107871}{107944}Barclay, dajem otkaz.
{107949}{107998}Ovaj put neopozivo.
{108015}{108056}Vidiš li da plaèem?
{108063}{108158}Nas dvojica moramo razgovarati | o mojoj otpremnini.
{108171}{108202}Zašto ovo ne otpremiš?
{108299}{108352}Èini se da ne razumiješ.
{108357}{108405}Želim da odrediš mjesto...
{108413}{108493}...i da tamo dopremiš ledene obloge | i lijekove protiv bolova.
{108498}{108530}Bit æe bolno.
{108535}{108598}Dakle, želiš da tako bude. | I bit æe.
{108603}{108657}Moja vježbaonica, | za 30 minuta.
{108662}{108738}Da sam ti, pripremio bih se | da jedem na slamèicu.
{108751}{108786}Naravno.
{109135}{109182}Casey, èekaj ovdje.
{109187}{109218}Ovo neæe dugo trajati.
{109367}{109490}Hoæe li jedan od vas donijeti | hladne obloge i lijekove?
{109567}{109650}Moj Benjamin Franklin kaže da æe | ih tvoj deèko trebati.
{109986}{110020}Idemo.
{110025}{110073}Hajde, sitni èovjeèe, | pokaži mi što znaš.
{110117}{110155}U ringu?
{110196}{110226}Ne razumiješ, zar ne?
{110270}{110310}Ne želim poštenu borbu.
{110341}{110385}Kako god želiš.
{110475}{110514}Rezultat æe biti jednak.
{110530}{110570}Hajde, pokaži mi!
{110860}{110924}Ovo æe biti bolji trening nego | što sam oèekivao.
{111155}{111199}Tko je govorio sranja o meni?
{111265}{111370}Jedino sranje si sam rekao o sebi.
{111375}{111432}Prvo si u to uvjerio | moju sestru.
{111448}{111520}Onda i mene. A sada æe govno | pogoditi ventilator.
{111675}{111733}Osjeæaš to?
{111761}{111802}Upravo si se upustio u | borbu sa šampionom.
{111807}{111866}Shvatit æeš zašto me tako zovu.
{111899}{111938}Što æeš sad?
{112043}{112088}Moja leða su ovdje.
{112191}{112222}Osjeæaš ovo? Da...
{112431}{112473}Tako... Dobro.
{114902}{114982}Phil! Imamo problem.
{115031}{115066}Mullins je nazvao.
{115071}{115153}- Jessie je u bolnici. | - Izgleda da je gadno ranjena.
{115158}{115218}- Što? | - Upucali su Jessie.
{115223}{115266}- Tko? | - Ne znamo.
{115301}{115330}Što je s mojom sestrom?
{115415}{115462}Zar Jessie nije trebala | pratiti Tamaru?
{115571}{115614}Bila je u nesvijesti kad | ju je hitna dovela.
{115619}{115676}Ima tri ustrijelne rane.
{115681}{115763}Tko god je to uèinio, sigurno je | mislio da je mrtva.
{115768}{115798}Imate pet minuta.
{115803}{115837}Treba joj odmor.
{115906}{115958}Tko je to uèinio, Jessie?
{116032}{116071}Jedan od njih...
{116087}{116130}Vidjela sam ga | u centru...
{116173}{116231}Velik, ružan...
{116239}{116282}S ožiljcima po licu...
{116287}{116333}Èovjek s mobitelom.
{116355}{116392}Što je s Tamarom?
{116419}{116458}Odveli su je.
{116471}{116522}Sve sam pokušala, g. Barclay.
{116527}{116578}Bilo ih je previše.
{116628}{116658}Jessie, slušaj.
{116697}{116744}Jesi li veæ razgovarala | s policijom?
{116764}{116800}Ne.
{116810}{116844}Dobro.
{116875}{116916}Ako ti postave pitanja...
{116933}{116976}...ne govori previše.
{116987}{117045}Ne možeš se sjetiti ni vlastitog | imena, u redu?
{117099}{117133}Bila si dobra.
{117225}{117254}I svi mi.
{117259}{117302}O èemu ti to govoriš?
{117307}{117338}Dobro znamo | tko je ovo uèinio.
{117353}{117418}Wayne, odveo je tvoju sestru | jer zapravo tebe želi.
{117423}{117454}Ona je mamac.
{117463}{117542}Ako pozoveš murjake, | pogoršat æeš stvari.
{117573}{117626}On bi mogao odluèiti | da se riješi dokaza.
{117631}{117695}Oprostite, ovo je intenzivna | njega, ne možete uæi.
{117700}{117782}Kako ste? Ovo je istraga specijalne | policije. Kratko æemo.
{117841}{117915}Ovdje smo da postavimo gðici | Jessie Otero nekoliko pitanja.
{118005}{118063}Molim vas, budite kratki.
{118077}{118127}Upravo je izašla iz kome.
{118219}{118302}Loše vijesti vas slijede poput | muhe koja leti za govnom.
{118322}{118388}Što se dogodilo? Imali ste | prometnu nesreæu dolazeæi ovamo?
{118393}{118438}Recimo da je to bio...
{118443}{118477}...samo sudar.
{118559}{118614}Mlada damo, možete li mi reæi | što se dogodilo?
{118707}{118738}Recite nešto, molim!
{118797}{118838}U redu, gospodo, žao mi je.
{118843}{118910}Moram vas zamoliti da prièekate | u hodniku. Vrijeme je za lijek.
{118915}{118943}Odmah!
{118948}{118983}Svi!
{119085}{119125}Van!
{119149}{119189}Svi!
{119254}{119297}- Van! | - U redu.
{119302}{119392}- Je li ona vama što rekla? | - Ne, tek smo stigli ovamo.
{119397}{119470}- G. Barclay? | - Ne, ništa.
{119480}{119536}Dovraga, zar su svi ovdje | u komi?
{119585}{119634}Imate li vijesti o vašoj | sestri?
{119652}{119689}Što o mojoj sestri?
{119694}{119784}Ova Jessie je vaš èuvar, | samo sam pomislio...
{119789}{119826}Što, da je bila s Tamarom?
{119867}{119899}Zašto ste to pomislili?
{119904}{119942}Mi sigurno nismo ništa rekli.
{119947}{120012}Samo sam to pomislio. | Mogla je ženska štititi žensku.
{120017}{120081}Vi ste tako brzo izletjeli | iz centra...
{120086}{120132}Prebrzo da nam | stavite soli na rep.
{120137}{120197}Ali možda ne i za nju.
{120208}{120249}Što dovraga insinuirate?
{120254}{120313}Detektive, moja sestra se nije | vratila kuæi.
{120318}{120356}Ne možemo je dobiti ni | na mobitel.
{120361}{120412}Ako znate gdje bi ona | mogla biti...
{120417}{120467}...cijenili bismo vašu pomoæ.
{120472}{120549}Kao prvo, nisam nikada rekao | da znam da je nestala.
{120554}{120617}A ako jest, možemo je poèeti | tražiti.
{120687}{120722}Ne još.
{120727}{120810}Možda je otišla u kupovinu | i auto joj se pokvario.
{120815}{120878}Kada budete sigurni, recite mi.
{120924}{120954}Javit æu se.
{121035}{121141}On se uvijek pojavi u pravo | vrijeme na pravom mjestu.
{121146}{121230}Možda je to samo sluèajnost?
{121255}{121300}Haj, Sauvage...
{121321}{121356}On je taj.
{121411}{121458}Rekao je da si ti bio sluèaj | za pod kljuè.
{121463}{121566}Rekao je da si naprosto jednog | dana poubijao masu žena i djece.
{121654}{121748}Imao sam problema s PTSP-om.
{121771}{121823}Taj dio je istinit.
{121843}{121950}Proveo sam neko vrijeme u bolnici.
{121999}{122074}Ali nikada nisam ubio nikoga tko | nije pokušao ubiti mene.
{122127}{122170}Skoro...
{122434}{122498}Baci pištolj!
{122550}{122598}- Pucaj, Phill! | - Ona je preblizu!
{122663}{122701}Pucaj konaèno, Phill!
{122831}{122870}Ne!
{123010}{123092}Dvadesetoro djece u školi.
{123097}{123135}Prema Al-Jaziri...
{123140}{123198}...i nekim stranim novinskim | servisima...
{123203}{123275}...jedan ih je ludi Amerikanac | sve ubio.
{123313}{123390}U to sam se vrijeme skoro | slagao s njima.
{123426}{123483}Nakon toga, nekako sam izgubio | taj osjeæaj.
{123526}{123629}Poslali su me kuæi, držali | na promatranju.
{123660}{123759}Bowden me je došao posjetiti.
{123778}{123818}Ostalo znate.
{123825}{123863}Èovjeèe...
{123871}{123950}Ponekad je život težak, zar ne?
{123981}{124072}Sada je na tebi red. Zašto se | toliko mrzite Terrell i ti?
{124167}{124216}Prije petnaest godina...
{124236}{124286}...kada sam tek poèinjao...
{124317}{124398}...Terrell mi je ponudio ogromne | novce da namjerno izgubim.
{124444}{124504}To je bila moja prva | profesionalna borba.
{124516}{124566}Rekao sam: "Ni u ludilu."
{124630}{124702}Jesi li znao da smo Tamara i ja | imali još jednog brata?
{124707}{124780}Da, spomenula mi je to.
{124799}{124834}Dakle...
{124839}{124924}Pobijedio sam. | Nekoliko noæi poslije...
{124931}{124986}...jedan je auto prošao kraj kuæe...
{124991}{125062}...i netko iznutra je upucao | mog mlaðeg brata.
{125125}{125190}Bio je pogoðen desetak puta.
{125202}{125248}Umro je tamo, na ploèniku.
{125253}{125342}Nitko nikada nije saznao tko je | to napravio i zašto.
{125377}{125420}Ali netko je ipak imao | lude pretpostavke?
{125425}{125474}Da, ja...
{125487}{125528}Stotinjak puta...
{125533}{125602}I uvijek sam dolazio do | istog zakljuèka.
{125614}{125654}Bilo kako bilo...
{125675}{125710}...prije pet godina...
{125715}{125782}...pronašao sam èvrste | dokaze da Terrell...
{125787}{125847}...izbjeljuje novac od prodaje | droge u mojoj lokalnoj banci.
{125852}{125928}Kada me je sudac ispitao...
{125946}{126044}...našao sam se pred teškim izborom.
{126049}{126118}Štitim li ja to èovjeka koji je | najvjerojatnije ubio mog brata?
{126123}{126174}- To ne zvuèi kao težak izbor. | - Sauvage...
{126179}{126262}Da je izbor bio lak, moja sestra | ne bi veèeras nestala.
{126436}{126465}K vragu!
{126470}{126544}To je Lydia. Još mi i ona treba!
{126549}{126634}Odgovori, ali nemoj reæi | da sam s tobom.
{126708}{126762}Hej, što je, curo?
{126767}{126814}Bog, ljubavi.
{126843}{126882}Jesi li sam?
{126907}{126957}Jesam, zašto?
{126962}{127040}Ne mogu sve reæi preko telefona, ali...
{127063}{127118}...molim te da svratiš | èim budeš mogao.
{127135}{127170}O èemu se radi?
{127195}{127242}Molim te, dragi...
{127268}{127305}Ne mogu reæi ništa više.
{127327}{127374}Ne dovodi nikoga.
{127385}{127446}Pogotovo ne onog svog | novog èuvara.
{127451}{127507}U redu. U redu, stižem.
{127512}{127562}Za 30 minuta, sam.
{127663}{127709}Wayne, ne mogu te pustiti.
{127714}{127781}Slušaj, život moje sestre je | u opasnosti, Sauvage.
{127786}{127846}Upravo sam se sjetio što je moj | bivši èuvar rekao:
{127851}{127922}"Terrell bi se mogao riješiti | dokaza ako pojaèaš vatru."
{127927}{127965}Ako ovo obavimo | kako treba...
{127970}{128089}...on neæe znati da je vatra jaka | dok ne shvati da mu je guzica u tavi!
{128425}{128498}Sranje! Èija je guzica u tavi?
{128725}{128767}Ljubavi...
{128780}{128849}Ljubavi... | Toliko mi je žao...
{129126}{129202}Nisam li ti rekao, Wayne? Ja sam | tvoje najveæi obožavatelj!
{129322}{129346}Gdje je Tamara?
{129351}{129404}Polako, šampione, | ne zakljuèuj prebrzo.
{129414}{129471}Moram te pretresti, oprosti.
{129519}{129571}- Nisi ozvuèen, je li? | - Zašto?
{129576}{129611}Èega se bojiš?
{129616}{129660}Ili moram pitati | èega se Terrell boji?
{129665}{129712}Eto, opet brzaš sa zakljuècima.
{129717}{129746}Molim?
{129751}{129834}Kada vidim policijskog detektiva koji | radi za zloèinca kojemu je dokazana...
{129839}{129870}...krivnja, što bih | trebao misliti?
{129875}{129923}Moraš misliti da ti tvoj | najveæi obožavalac...
{129928}{129966}...pokušava opet | nešto smjestiti.
{129990}{130038}Terrell ti nudi maslinovu | granèicu.
{130043}{130090}Ti odluèi hoæeš li je | prihvatiti ili ne.
{130095}{130142}Da, a moja sestra je ulog.
{130171}{130261}- A što ako odbijem? | - Hajde, šampione, ne budi pesimist!
{130266}{130311}Moraš poslovati direktno | s Terrellom.
{130316}{130386}Ja sam ovdje samo da | to pojednostavnimo.
{130406}{130449}- Terrell dolazi ovamo? | - Ne.
{130454}{130502}U znak otvorenosti i pomirbe...
{130507}{130568}...pozvao vas je svojoj kuæi.
{130580}{130622}A suradnici g. Singleteryja...
{130627}{130686}...æe se pobrinuti za prijevoz | i osiguranje.
{130691}{130761}Razumijem. | Vrlo velikodušno od njega.
{130796}{130826}Gdje je vaš èuvar?
{131155}{131189}- Isuse! | - Pazi!
{131194}{131228}Cujo, udari ga!
{131263}{131293}Pizdo!
{131359}{131405}Vaše osiguranje je upravo | palo na prvom ispitu.
{131410}{131474}Ja æu si sam naæi moje, ako | g, Singletery nema ništa protiv.
{131479}{131536}Èiniš prokleto ozbiljnu | pogrešku, Wayne!
{131541}{131617}I opet brzaš sa zakljuècima.
{131775}{131829}GLAVNI ULAZ | 01: 15
{132961}{133017}Terrell me sigurno oèekuje.
{133059}{133145}- Nemoj! Svi æemo umrijeti! | - Spusti oružje!
{133248}{133309}Obavijestit æu g. Singleteryja | da ste ovdje.
{133319}{133350}Hej, ostani ovdje!
{133375}{133425}Upotrijebi interkom.
{133527}{133564}Hej, Terrell!
{133569}{133605}Imaš goste.
{133610}{133653}Ušli su.
{133658}{133728}Goste? | Oèekivao sam samo jednoga.
{133733}{133806}Tvoj gost je doveo prijatelje.
{133835}{133906}Razumijem. Evo me odmah dolje.
{134021}{134074}Provjeri je li mojoj drugoj | gošæi udobno.
{134122}{134182}Pogledat æu što je s njom.
{134217}{134275}Ali ako ti je stalo da se družim | s vama...
{134280}{134354}...možeš me slobodno | povezati s jednim od njih.
{134401}{134458}Prvorazredan izbor.
{134491}{134554}Svi doðite sa mnom
{134578}{134629}Provjeri što je s kuèkom.
{134797}{134866}Neutralizirali su te.
{135020}{135079}Stric Terrell želi da obojica | odete u garažu.
{135110}{135178}Govnari, zar mu baš trebam reæi | da sam morao dva puta pitati?
{135237}{135312}Hodajte malo življe. | Hajde. Pokrenite se.
{135317}{135360}- O, èovjeèe! | - Hvala!
{135365}{135435}- Imaš problem? | - Molim?
{135440}{135469}Što?
{135474}{135514}Kljuè za lisice.
{135572}{135622}Hvala ti, brate.
{136217}{136245}Ti si Leonard.
{136250}{136278}Odvjetnik?
{136283}{136349}Onaj koji je pomogao svom stricu | da bude ranije pušten.
{136354}{136402}Ne znam kako da zapoènem | s isprikama.
{136407}{136479}- Možeš poèeti s ovim. | - O, svakako!
{136484}{136557}Cijela je ta stvar bila strašna | pogreška.
{136585}{136614}Hvala ti.
{136619}{136669}Možda mogu sprijeèiti da se | ovo pretvori u tragediju.
{136674}{136704}Hvala!
{136741}{136794}O, Bože! Propali smo!
{136997}{137052}Wayne Barclay...
{137091}{137130}Sanjao sam | ovaj trenutak.
{137140}{137182}Samo nastavi sanjati!
{137199}{137237}Tamara!
{137299}{137328}Jesi li dobro?
{137352}{137392}Jesam.
{137496}{137530}Hvala!
{137535}{137566}Hvala ti!
{137579}{137636}Èekajte, vi niste iz policije?
{137648}{137708}Ne. Mi smo Ekipa velièanstvenih.
{137718}{137770}Reci svojim deèkima | da spuste oružanje.
{137775}{137830}Ili æe ovaj Prljavi Harry | vrlo brzo sresti Elvisa.
{137835}{137879}To bi bila velika šteta.
{137884}{137926}Teško je naæi dobre pomoænike.
{138156}{138201}Jao, Bože, previše sam zakasnio!
{138350}{138394}Tamara je s nama. | Što se tamo dogaða?
{138399}{138430}Dajemo posla ovim ljudima.
{138495}{138529}- Trebate li pomoæ? | - Ne.
{138534}{138579}Samo udaljite gðicu | Barclay odavde.
{138584}{138656}- U redu, idemo. | - Gdje mi je brat?
{138687}{138718}Wayne, Tamara je s njima.
{138747}{138798}- Odakle ta pucnjava? | - Kamo je onaj klinac otišao?
{138803}{138866}- Klinac je Terrelleov neæak. | - Dovraga. Hajde, idemo.
{139365}{139398}Sranje!
{139715}{139758}Simcoe, daj mi šaržer.
{139763}{139802}Ne, ovo mi je zadnji.
{139807}{139855}- Što? | - Ne mogu ti nikako pomoæi.
{139863}{139892}Žao mi je.
{139897}{139929}Pederi!
{139953}{139989}- Idem ja. | - Kamo ideš?
{139994}{140050}Mièem svoje dupe odavde.
{140055}{140101}- Mièem svoje dupe odavde. | - Kujo!
{140439}{140493}Barclay?
{140507}{140558}Barclay? Slušaj, èovjeèe, | slušaj...
{140563}{140610}Moram ti reæi nešto važno. | Hajde!
{140712}{140770}Dakle, reæi æu ti tko je | ubio tvog brata.
{140775}{140820}Znam da te to zanima.
{140825}{140854}Spuštam pištolje.
{140894}{140928}Gledaj.
{140975}{141006}Hajde, èovjeèe!
{141011}{141066}Razgovarajmo, | ja sam poslovni èovjek.
{141071}{141117}Ti, poslovni èovjek?!
{141240}{141272}Istina?
{141277}{141393}Vidiš, obièno ja ne obavljam | neugodne zadatke.
{141398}{141434}Ali reæi æu ti nešto.
{141479}{141534}Bio mi je pravi užitak | slistiti tog gada.
{141539}{141569}Pas mater!
{141825}{141888}A sad æu imati još više užitka | kad sredim ovog gada...
{141893}{141974}...kojeg sam veæ onda trebao srediti!
{141979}{142022}Strièe T.! Ne!
{142165}{142206}Strièe T., molim te!
{142211}{142240}Još možemo | ovo nekako ublažiti.
{142259}{142320}Spusti pucaljku. Ne mora | sve završiti ovako.
{142325}{142360}Ne može završiti na drugi naèin.
{142641}{142703}Bože, Mullins je ranjen!
{142715}{142760}Phil, izvuci ih odavde!
{142771}{142821}- Bit æu dobro. | - To je zapovijed, vojnièe!
{142826}{142854}Idi!
{142859}{142921}Casey, pokrivaj me! | Kreni! Sad!
{144482}{144542}To je meso. Hoæete malo | friškog mesa, ha?
{144970}{145026}Ovo voliš, gade, je li?
{146411}{146460}Hej, g. Barclay!
{146465}{146516}Mogu li sada dobiti | vaš autogram?
{146627}{146658}Možeš, kujo!
{146663}{146722}Dovedi svoju kurvinsku guzicu!
{146855}{146892}Na èemu smo stali, | seronjo?
{146915}{146968}Misliš da me možeš prijeæi, | crnjo?
{146982}{147038}A što misliš, s kim si petljao?
{147043}{147086}Jesi li spreman pozdraviti | svog malog brata?
{147099}{147146}- Jebi se. | - Da se jebem?
{147151}{147186}Jebi se, crnèugo!
{147882}{147921}Sauvage!
{147939}{147978}O, sranje.
{147983}{148028}Ne, ne, ne!
{148033}{148112}Hajde, Sauvage, daj! | Hajde, èovjeèe!
{148117}{148152}Sauvage, hej, Sauvage!
{148178}{148209}Ustani!
{148214}{148253}Phil! | Èuješ li me, Phil?
{148258}{148337}Probudi se, Phil! Ustani!
{148342}{148392}Ustani, Phil!
{148493}{148556}- Hej, Phil! | - Wayne?
{148663}{148702}Ovo strašno boli.
{148740}{148778}Bit æeš opet dobro.
{148799}{148875}- Phil, sve æe biti u redu. | - O.K.
{149167}{149218}Ne možemo ostati izvan ovoga, | je li?
{149234}{149284}Èudan naèin zaraðivanja, | to je sigurno.
{149326}{149382}Bit æe uskoro bolje.
{149387}{149422}Za mene je gotovo.
{149427}{149524}- Jesi li dobro? | - Pa, znalo mi je biti i bolje.
{149529}{149567}- Ali da, dobro sam. | - Hvala, èovjeèe.
{149572}{149618}A jesi li ti dobro?
{149907}{149946}Imao si pravo, mali.
{149951}{149996}Nije moralo završiti ovako.
{150001}{150050}G. Barclay!
{150071}{150154}Teague je neko vrijeme bio | pod internom istragom.
{150159}{150210}Ona prièa o osiguranju?
{150215}{150261}Nisu samo vas držali na oku.
{150266}{150305}Nadzirali su i njega.
{150310}{150378}Tako dakle. Drugim rijeèima, | ja sam bio mamac?
{150383}{150426}Pa nije baš tako.
{150431}{150461}Ali slièno.
{150466}{150538}Na sreæu, imali smo g. Sauvagea.
{150543}{150599}Da, a sve to dugujem tebi, | sestrice.
{150604}{150676}Usprkos tome što je on | najveæi gnjavator na svijetu.
{150681}{150740}Za to me plaæaš, gospodine.
{150745}{150833}Ili bolje reæi, plaæao si me.
{150838}{150882}Molim?
{150887}{150933}Od kada, Wayne?
{150943}{150979}To je bio samo nesporazum.
{150984}{151024}- Kako da ne! | - Mene su upucali!
{151029}{151085}- I što onda? | - Ljubavi, jesi li dobro?
{151090}{151122}Hej, dušo, što je?
{151166}{151217}Toliko sam se brinula!
{151222}{151268}Izgleda da te ovo jako boli!
{151273}{151345}Udario me je malo po oku.
{151350}{151402}Èini se da ti je potrebna | posebna njega.
{151407}{151502}To je dokazana èinjenica. Malo | nježnosti èini èuda.
{151507}{151543}Stvarno?
{151548}{151600}A tko je tvoj èudotvorac?
{151605}{151688}Nemam ga još, ali skupljam | životopise.
{151693}{151762}Onda dozvoli da ti predam svoj.
{151820}{151850}Gle, gle, gle!
{151855}{151910}I ovo æeš nazvati | poljubac u obraz?
{151939}{151990}Wayne, okreni se.
{151995}{152042}Wayne, okreni se.
{152050}{152250}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan 
