{1}{1}25.000
{692}{791}Nisam to jako | pritisnuo! - Ali boli!
{795}{900}Gdje boli? Ovdje? - Ne, | ne. Baš tu. Toèno tu.
{915}{1037}Ne gunðaj toliko. | Pa ne boli tako jako?
{1042}{1198}Nimalo ne boli. | To je manja ozljeda.
{1243}{1350}Nema alkohola. - Nisam pio. | - Neka te grom pogodi, ako jesi.
{1590}{1639}Idi. - Siu-Bo.
{1643}{1698}Žurim. Nešto važno.
{1703}{1791}Mogu li hodati? - Naravno! | Možeš i trèati ako želiš.
{1795}{1898}Idem u park. - Prošeæi po | parku. Nazvat æu te kasnije.
{2545}{2602}Siu-Bo.
{2710}{2773}Razumio sam.
{3320}{3420}{C:$0000FF}{y:ib} KUÆA |{C:$FF0000}{y:b} BIJESA 
{3863}{3920}Upomoæ!
{8003}{8077}Jedan, dva, tri, èetiri, pet...
{8081}{8161}Šest, sedam, osam, devet, deset.
{8256}{8394}G. Yue, definitivno ste rekli 12 | nindži. Nabrojala sam samo 10.
{8474}{8598}Zaista? Rekao sam 12? | Nisam li rekao da ih je 10?
{8604}{8764}Kako god. Razgovarajmo prvo o | 18 oružja. Od èega se sastoje?
{8776}{8905}Maè, koplje, sablja, strijela...
{8912}{8991}Maè, koplje, sablja, strijela...
{8995}{9091}Poèet æu s 10, a | ostalih 8 objasnit æu drugi put.
{9095}{9200}Èekajte. Sad ste rekli | da ste ušli nenaoružani.
{9204}{9284}Odakle onda Kwan-To i koplje?
{9321}{9425}Ne prekidaj moju prièu. | Ako sve sad objasnim,
{9428}{9527}što æu prièati iduæi put? | Gdje sam stao? Ah, da.
{9531}{9622}Bio sam nenaoružan. | Držao sam Kwan-To i koplje
{9626}{9702}i uletio u gomilu ljudi...
{9829}{9994}Što radim ovdje? Koliko je sati? | - Pola 5. - Pola 5? Tako kasno?
{9998}{10097}Došao sam po svoju kæer, a ja | ovdje prièam s vama. Dosta je.
{10101}{10208}Idite kuæi napisati zadaæu.
{10229}{10334}Natalie, otac ti je ovdje. | - Znam. Zato i žurim.
{10338}{10395}Javi se na telefon...
{10399}{10505}Tako je dosadan! - Nemoj biti | takva! Tata ti je smiješan.
{10507}{10602}Prièa zanimljive prièe. | - Tebi su jedinoj one smiješne.
{10604}{10702}To kažeš jer nije tvoj tata. | - Valjda. Veèeras spavam kod tebe.
{10704}{10789}Zašto? Tvoji su | opet otputovali? - Da.
{10793}{10897}Hoæe li to smetati tvom | bratu? - Zašto bi mu smetalo?
{10901}{11003}Bio bi presretan | da ostaneš zauvijek kod nas.
{11454}{11558}Veliki pljesak za naše delfine, | Ding Dinga i Wai Waia.
{11560}{11662}I za našeg trenera Nickya! | Hvala svima što ste došli
{11667}{11769}na našu predstavu | u Svijet oceana.
{11774}{11852}Idem, Nicky. - Bok.
{12710}{12831}Tako si zao.
{12884}{12941}Da.
{12948}{13055}Idemo na veèeru sutra naveèer. | - Može. - Veèerajmo kod tebe.
{13060}{13186}Nisam upoznao tvoju obitelj. | - Ne. Moji su zaista dosadni.
{13231}{13337}Nije važno. Morat æu ih | upoznati prije ili kasnije.
{13406}{13500}Idemo | negdje drugdje jesti.
{13506}{13580}Gledam!
{13659}{13752}Lakiraš si nokte i prièaš. Koliko | stvari možeš raditi istovremeno?
{13756}{13831}To te se ne tièe. Promijeni kanal.
{13871}{13944}Jason, prièekaj.
{14996}{15069}Što se dogaða?
{15073}{15178}Zašto mi nisi rekla da je Ella | tu? - Zašto bih ti trebala reæi?
{15421}{15523}Spremite se za | veèeru. - 'dan, g. Yue.
{15528}{15628}Ovdje si? Veèeraj s nama. | - Može. - Tata.
{15632}{15744}Doðite i uzmite si. | - Sjajno. - Doði, idemo jesti.
{15910}{16025}Halo? Hoæemo li veèerati? | - Dobar tek. - Dobar tek.
{16032}{16112}Ella, uzmi malo povræa.
{16118}{16217}Hvala, g. Yue. - Nema na èemu. | - Kad se vraæaju tvoji roditelji?
{16221}{16327}Ne znam. Nisam pitala, a oni nisu | rekli. - Ostani ovdje par dana.
{16331}{16430}Èak i da je neodreðeno | vrijeme, ne bi bilo problema.
{16432}{16528}Zlato, zašto te | danas nisam vidio u školi?
{16532}{16594}Došao si? Nisam znala.
{16598}{16697}Svugdje sam te tražio, | ali si me ignorirala.
{16701}{16786}Zvao sam, ali ti je | mobitel bio ugašen.
{16790}{16884}Ne smijemo ga ukljuèiti u školi. | Takve su odredbe ravnatelja.
{16887}{16969}Zato sam ga zaboravila upaliti. | - Prebaci ga na govornu poštu.
{16974}{17080}Kakvo logièno objašnjenje. | Što æeš joj reæi?
{17145}{17253}Jedi, jedi. Uzmi batak. | - Hvala, brate.
{17446}{17517}Da vam isprièam vic?
{17538}{17675}Ovaj je novi. Dok sam kupovao, | prošao sam kraj restorana.
{17687}{17784}Vidio sam kako | neki kreten bira ribu.
{17788}{17891}Birao je i birao, | sve dok nije upao u tank.
{17895}{17948}Nije znao što bi uèinio u tanku,
{17953}{18062}pa je plivao u krug | prije nego što je izašao.
{18224}{18319}Oprostite, oprostite.
{18351}{18456}Gotov sam. | - Urnebesno je, zar ne?
{18504}{18608}Hajde. Jedimo. | Jedimo. - Jedimo.
{19073}{19153}Jesi li veæ zaspala?
{19157}{19266}Ako nisi, možemo malo | prièati? Što si danas radila?
{19298}{19423}Bio sam tako glup. Išao | sam po našu kæer u školu
{19437}{19537}ali je veæ otišla. | Znam da me namjerno izbjegava
{19540}{19603}da joj ne stvaram pritisak.
{19607}{19698}Pritisak bi samo pogoršao stvari.
{19703}{19803}Za veèerom sam htio isprièati | vic da se svi nasmijemo,
{19807}{19892}ali naš se sin bez | rijeèi povukao u sobu.
{19896}{20003}Zar sam zaista tako dosadan? | Zato me svi izbjegavaju?
{20065}{20172}Otišla si brzo, nisi se morala | baviti tim roditeljskim stvarima.
{20178}{20280}Teško je biti otac. Osim dojenja, | sve sam uèinio za njih.
{20301}{20400}Dosta brbljanja, | inaèe æe mi se jezik zaplesti.
{20406}{20480}Jako mi nedostaješ.
{20938}{21050}Cigarete nisu dozvoljene u ovoj | kuæi. - To je cigara, ne cigareta.
{21140}{21300}Ne slažeš se s tatom? - Da ne | sere slagali bismo se bolje.
{21306}{21419}A ti? Što je s tvojima?
{21476}{21581}Da moj tata nema deèka, a mama | curu, bila bih puno sretnija.
{22388}{22520}Sviðam li ti se? | - Natalie ti je rekla?
{22579}{22678}Rekla je da si nepristojan, | sebièan gnjavator
{22682}{22787}i da nisi vrijedan da | se itko u tebe zaljubi.
{22793}{22967}Inaèe sam O.K. Toèno? | - Dosadno ti je? - Kako to misliš?
{22971}{23106}Što? - Hoæeš francuski poljubac? | - Što? - Želiš ili ne želiš?
{23251}{23330}Da! - Vrijeme je isteklo.
{23584}{23686}Da promijenim spol, | da li bi ti se sviðala?
{24034}{24142}Natalie, mjeseènica | Ne ide mi se u školu. Ella!
{24303}{24408}Tata? - Moram ti | nešto reæi. - Dobro, reci mi.
{24413}{24520}Jason dolazi veèeras | na veèeru. - Jason?
{24535}{24653}Jason! Tvoj deèko. - Kakav | deèko? On je samo prijatelj.
{24671}{24797}Znaš li tko je Jason? - Žao | mi je. Krivo sam zapamtio.
{24799}{24916}Nije Jackson, veæ Jason. | - Kako god. Priredit æu gozbu.
{24921}{25025}I nemoj prièati gluposti. | - Prièam puno gluposti?
{25029}{25133}Nemoj se praviti da ne znaš. | Siliš ljude da slušaju te prièe
{25137}{25242}o tajnoj zaštiti. Nemoj | uplašiti Jasona na prvoj posjeti.
{25245}{25345}Baš me briga vjeruju | li drugi u moje prièe,
{25349}{25459}èak mi ne smeta prièati ih. Bitno | je da mi ti i brat vjerujete.
{25465}{25584}Sve prièe koje prièam su | istinite. - Dosta! - Sve! - Dosta.
{25607}{25709}Zbog tebe sam klaun. Nemoj | me i pred Jasonom osramotiti.
{25713}{25792}Jasno?
{25854}{25978}Vas dvoje ste | voljeli slušati moje prièe.
{25982}{26091}Kad niste mogli spavati, | slušali biste ih dok ne zaspete.
{26098}{26202}Kad su vam se prestale sviðati? | - Kad je mama umrla.
{26499}{26652}Oprosti. - Glupa djevojko. Tata | se ne bi na tebe mogao naljutiti.
{26667}{26769}Obitelji nikad ne | moraš reæi da ti je žao.
{26812}{26906}Zaboravio sam ti reæi, | danas imam puno pacijenata.
{26910}{27012}Neæu moæi doæi po vas. | Èuvaj se. - Hoæu. Vidimo se.
{27084}{27208}Dušo... Dušo... - Što sad? | - Tvoja amajlija. - Nosim je,
{27212}{27317}nemam vremena. Imam predstavu | za 2 dana. Moram na probu.
{27320}{27409}Glumiš? - Da. - Ti si | glavna ženska uloga? - Da.
{27412}{27486}Onda tata to mora doæi pogledati. | - Nema šanse. - Nema šanse?
{27490}{27587}Ti si glavna ženska uloga. | - Ako doðeš, bit æu nervozna.
{27592}{27694}Dobro onda. | - Oprezno vozi. Bok. - Bok.
{27698}{27825}Mogu li vidjeti kako glumiš? | - Ne! Bok. - Ne smijem vidjeti?
{27846}{27920}Kakvu je to onda predstava?
{28173}{28278}Iako si kiropraktièar, | poštujem te. Tvoja kæer.
{28395}{28492}Vidiš li ovo, draga? | Kæi nam se boji da æu biti tužan.
{28496}{28602}Pa je poslala | poruku da me razveseli.
{28624}{28730}Razgovor s tobom je gubitak | vremena. Ne možeš se vratiti.
{29717}{29797}Zaista ništa ne znam.
{30343}{30448}Možda æe mi oni | reæi što moram znati.
{30531}{30611}Imaš 10 sekundi da se odluèiš.
{30661}{30835}1, 2, 3, 4, 5, 6...
{30856}{31030}7, 8, 9, 10...
{31060}{31166}Ubij ih. | Ubij ih. - Reæi æu! Reæi æu!
{31953}{32006}Hvala.
{32010}{32111}I kao što sam | obeæao, sad možeš iæi.
{33137}{33261}Prokletstvo! Može | malo nježnije? Zaista boli.
{33267}{33381}Ne boli kad padneš s skatea? | Zar vi niste navikli na to?
{33406}{33527}Nosi se s tim. Ruka ti je | išèašena. Stavit æu je na mjesto.
{33532}{33620}Bit æeš dobro nakon 8 do 10 dana. | - Tako dugo? Pokrao si me!
{33624}{33736}Pokrao? Ponovi to. | - O.K. Nema problema.
{34131}{34236}Izvolite, mogu li vam pomoæi? | - Razumijem kineski.
{34240}{34339}To olakšava stvar. | Pregledat æu vas.
{34342}{34442}Vaše su ozljede | jako problematiène.
{34446}{34545}Ne radi se o nekoliko kura | lijeèenja. Shvaæate li? - Shvaæam.
{34549}{34648}Ali nisam vam došao | kao lijeèniku. Tražim nekog.
{34651}{34731}Zove se Tai Chi-Lung.
{34829}{34942}Nelson, sjedni ovdje. | - Dobro, tata.
{35128}{35250}Prije 12 godina, skupina | terorista bombardirala je hotel
{35254}{35331}na Filipinima pun turista.
{35385}{35503}To je bila odmazda SAD-u | zbog pomaganja filipinskoj vladi
{35507}{35616}u suzbijanju terorizma. | Nakon bombaškog napada,
{35621}{35722}amerièka vlada je | odobrila niz operacija
{35726}{35802}da se likvidiraju odgovorni.
{35857}{35983}Moj posao je bio ubiti vezu | te skupine u Hong Kongu.
{36006}{36111}Bivšeg filipinca Fernandeza.
{36424}{36552}Nisam znao da je britanska | protuobavještajna u Hong Kongu
{36556}{36659}poslala jednog | svog agenta za mnom.
{37201}{37303}U paklu koji je slijedio, | ozlijedio sam kralježnicu
{37306}{37416}i paraliziran sam od vrata. | Mogao sam micati samo prstima.
{37496}{37600}Nakon nekoliko godina napokon | sam saznao tko je to uèinio.
{37609}{37733}Zove se Tai Chi-Lung! | Kad sam ga pokušao pronaæi
{37737}{37842}saznao sam da se | povukao iz obavještajaca
{37862}{37980}i da mu je dan novi identitet od | odjela za zaštitu bivših agenata.
{38003}{38134}A tko mu je dao | novi identitet? Ti, Yue Siu-Bo!
{38301}{38431}Znate koliko se ljudi zove | Yue Sin-Bo u Hong Kongu?
{38515}{38648}Shvaæam, ali sam siguran da | vi razumijete što ja govorim.
{38659}{38777}Oprostite, moje sadašnje | medicinske vještine
{38782}{38891}vam zaista ne mogu | pomoæi. Trebate specijalista.
{38899}{38948}O.K.
{38954}{39036}Srest æemo se opet!
{39110}{39219}Nelson. - Tata, | vidi ovo je tako mrak.
{39223}{39303}Znate li borilaèke vještine?
{39393}{39453}Idemo.
{40460}{40566}'Dan, g. Yue. | - Ti si Jason. Uði. Uði.
{40621}{40681}Sjedni se.
{40784}{40861}Jason je došao. - O.K.
{40915}{41008}Raskomoti se, | idem pripremiti veèeru.
{41010}{41116}Nemoj samo sjediti, | prièaj s našim gostom. - O.K.
{41184}{41287}Bok. - Bok. - Ja sam | Jason. - Ja sam Nicky.
{41337}{41481}Ostavi je. - Što? | - U tom sluèaju, sretno.
{41537}{41611}Stigao si. - Da.
{41656}{41805}Za tebe je. - Hvala.
{41815}{41903}Izgledaš odlièno. - Hvala.
{41931}{42034}Ima li još nešto. | - Što? - Otvori i pogledaj.
{42112}{42264}Tako je sladak. Ima | li ime? - Ne. Daj mu ime.
{42421}{42595}Zvat æemo ga Prašèiæ. | - Prašèiæ zvuèi odlièno.
{42613}{42734}Znaèi, Prašèiæ je. - Dao ti je | svinju. Želi te poševiti.
{42771}{42880}I vaša obitelj prodaje svinje? | - Ignoriraj ga. Prièa gluposti.
{42912}{43014}Veèera je na stolu. | Zašto je ovdje svinja?
{43018}{43147}Poklon od Jasona. Zove se | Prašèiæ. - Slatko. Jako slatko.
{43184}{43305}Veèera je na stolu. | Doðite. Idemo jesti.
{43356}{43480}Dakle, Jason, èine se | baviš? - Ja sam glazbenik.
{43506}{43580}Glazbenik. To je dobro.
{43612}{43734}Sviða li ti se hrana? - Super je. | Nisam izbirljiv kod predigre.
{43743}{43873}U èemu nisi izbirljiv? - Ne! | Mislio je na slijed jela.
{43887}{43991}Nisam li upravo to rekao? | A što sam to rekao?
{44015}{44120}Oprostite, moj izgovor | kineskog nije baš sjajan.
{44131}{44292}Nema veze. Jedi. Jedi. | - Brate, dodaj mi piletinu.
{44365}{44505}Mogu li ti dodati | piletinu? Dodati?
{44531}{44605}Zar igramo poker?
{45053}{45111}Bako, opet poèinju.
{45984}{46045}Ostavi je.
{46231}{46330}Dobro je što nisi | izbirljiv kod jela. Jedi. Jedi.
{46540}{46631}Uði. Bok, tata. - Èitaš? - Da.
{46707}{46814}Ne spavaš još? Radiš sutra? | - Radim. Uskoro æu spavati.
{46818}{46948}Prièajmo malo. - Idem spavati. | - Samo malo. - Idem spavati.
{47209}{47314}Zanemario si borilaèke vještine. | Kung-fu se usavršava vježbom.
{47360}{47508}Znaš kako se kaže, bez muke | nema znanja. Jasno? - Da. Da.
{47621}{47734}Sestra ti je mlada. Kao stariji | brat trebao bi prilagodljiviji.
{47803}{47916}Èuješ li me? - Da.
{48001}{48111}Mame veæ dugo nema. Ako se | nešto dogodi i mene više ne bude,
{48121}{48255}što æeš uèiniti? | Moraš se brinuti za svoju sestru.
{48293}{48373}Znam. - Idem sad.
{48513}{48619}Pokrij ramena. Ako ti se ramena | nahlade, dugo æeš biti bolestan.
{48651}{48709}Laku noæ.
{50199}{50322}Cijenim to što morate obaviti | posao. Ali vi jedini znate
{50326}{50442}gdje je Tai Chi-Lung. Došao | sam jer nemam drugog izbora.
{50476}{50591}Nagon mi kaže da ako mi | ne odate gdje se on nalazi,
{50595}{50697}život vam neæe | biti više tako ugodan.
{50732}{50808}Srest æemo se opet.
{53120}{53202}Popijte èaja.
{58865}{58945}Gdje je Tai Chi-Lung?
{59003}{59106}Veæ sam vam rekao, | tražite ga u imeniku.
{59359}{59441}Rocco je. - Ne želi ništa reæi.
{59518}{59597}Dovedi ga ovdje.
{59610}{59784}Nelson, kasno je. Idi u krevet. | - O.K. Laku noæ. - Laku noæ.
{60671}{60778}Trebaš mi samo reæi | što želim znati i možeš iæi.
{60868}{60972}Gubite vrijeme. | Neæu vam ništa reæi.
{61431}{61547}Ne morate to èiniti. | Tai bi trebao patiti.
{61621}{61697}Samo radim svoj posao.
{61917}{62019}Onda æete morati birati | izmeðu posla i èasti
{62023}{62086}i svoje djece!
{62542}{62617}Recite mi gdje je Tai Chi-Lung.
{63256}{63334}Siu-Bo, jako me boli glava.
{64106}{64209}Kad bi barem moja obitelj | bila fina i ugodna kao vaša.
{64371}{64477}Nicky, telefon. Neki | Chiu. Kaže da je hitno.
{64887}{65061}Chiu? - Jeste li pronašli | oca? - Nije upalio mobitel još.
{65090}{65264}Što se dogodilo? - Ne znam. | Bilo je ovako kad sam došao.
{65771}{65878}Siu-Bo je razljutio neke | ljude, pa su mu sve uništili?
{65962}{66067}Tata voli srati. | Ali zašto bi mu netko ovo uèinio?
{66238}{66362}Što je ovo? | - Ne znam. Pazi.
{66795}{66900}Buduæi da niste progovorili, | morat æemo probati nešto drugo.
{66945}{67050}Ovo je moj prijatelj Edward. | Donio je nešto posebno za vas.
{67120}{67197}Što? Vitamin C?
{67220}{67322}Krivo! | Odgovor je Kalcij penatol.
{67326}{67430}Služio je kao serum | istine na poèetku stoljeæa.
{67581}{67686}A zapravo utjeèe na vaš | centralni živèani sustav
{67712}{67792}i izaziva hipnotièko stanje,
{67812}{67914}te onemoguæava laganje.
{67970}{68073}Dakle... | Gdje je Tai Chi-Lung?
{68153}{68233}Gdje je Tai Chi-Lung?
{68245}{68327}Gdje je Tai Chi-Lung?
{68765}{68850}Tata! Tata!
{69012}{69144}Kako da ga pronaðem? | - Memorijske kartice.
{69160}{69284}Memorijske kartice? | - U amajlijama su.
{69309}{69414}Ako naðem amajlije, naæi | æu i memorijske kartice?
{69465}{69545}A gdje držite amajlije?
{69667}{69791}Ispod majèina | kreveta. One nas èuvaju.
{69906}{69966}Traženje...
{70506}{70589}Nisu li te amajlije lijepe?
{70984}{71078}Što je ovo? - Ne znam.
{71656}{71758}Reæi æu ti nešto. Tata æe | uskoro promijeniti posao.
{71760}{71870}Kad promijenim posao, neæu | više èuvati vladine službenike.
{71874}{71969}Štitit æu tajne agente. - Što | su to tajni agenti? -To su...
{71973}{72087}...posebna vrsta ljudi. | Rješavaju probleme drugih ljudi.
{72096}{72245}Kad doðem na novo mjesto, | neæu više imati toliko vremena.
{72249}{72378}Shvaæate? Zaštitit æu vas jer | æu vas nauèiti kako se štititi.
{72393}{72502}Pokreti moraju biti nježni | i brzi, glatki i kontinuirani.
{72506}{72606}Koristi disanje da stimuliraš | chi. Koristi duhovnu snagu
{72610}{72708}tako da ne bude | nejednakosti ili diskontinuiteta.
{72712}{72811}Zar se ne slažeš s ocem? | - Da ne voli toliko srati,
{72815}{72922}slagali bismo se puno bolje. | - Sestra ti je još mlada.
{72926}{73025}Kao njen stariji brat, | trebao bi biti prilagodljiviji.
{73029}{73128}Mame veæ dugo nema. Ako | se nešto dogodi i mene ne bude,
{73131}{73298}što æeš uèiniti? Moraš se | brinuti za svoju sestru, jasno?
{73404}{73464}Kuda ideš?
{73646}{73800}Princezo... Princezo... | Princezo, slušaj.
{73806}{73906}Zgodan sam i bogat. | I još važnije, volim te.
{73909}{74011}Princezo, udaj se za mene! | - Princezo, siromašan sam
{74013}{74117}i nisam zgodan. Ali znam kuhati | curry. Udaj se za mene!
{74148}{74245}Oboje ste dobri. Zaista | ne znam koga da odaberem.
{74248}{74337}Koliko još do kraja? | - Još malo, ravnatelju.
{74342}{74434}Zbog moje sreæe i | buduænosti, udaj se za mene!
{74438}{74544}Princezo, znam kuhati | žuti, zeleni i crveni curry.
{74548}{74645}Zaista morate odabrati. | - Prinèe Muhamede,
{74649}{74741}na ovom svijetu | najviše mrzim curry.
{74746}{74853}Ali još više mrzim | zgodne muškarce.
{74856}{74961}Zato sam odabrala | vas, prinèe Muhamede.
{75031}{75155}Nebesa! | Straža! Uhitite ih!
{75548}{75627}To je veæ nešto.
{76101}{76217}Ella, što je bilo? | - Tvoja sestra. Nešto se dogodilo!
{76253}{76406}Ravnatelju, ovo nije iu | programu. Krenite prema izlazu.
{76448}{76589}Èega se boje? - Nemojte | ozlijediti moju princezu!
{77420}{77475}Idemo.
{78151}{78230}Što se dogaða? - Jason, vozi!
{79670}{79777}Moja sestra je | ostavila odjeæu, obuci je.
{80192}{80347}Mogu li kako pomoæi? - Iskreno, | ni ja ne znam što da radim.
{80382}{80491}Znaš li tko progoni Natalie? | - Ako su prièe oca istinite,
{80523}{80697}onda ima veze s zaštitom | bivših agenata. - Vjeruješ li mu?
{80784}{80895}Nisam prije, | ali sad više ne znam.
{82290}{82392}Brate, znaš... | Ovo sam našla unutra.
{82395}{82473}Nije èudo što su ti ljudi | htjeli uzeti moju amajliju.
{82476}{82550}Imaš li kompjutor? - Naravno.
{82713}{82772}Uèitavanje...
{82867}{82991}Umetnite disk 2. - Trebaš | drugu memorijsku karticu.
{83581}{83636}Požuri!
{84284}{84359}Sestro, budi oprezna!
{87120}{87178}Kujo!
{89709}{89791}Brate! - Jesi li dobro? Idemo.
{90160}{90234}Imaš li ga? - Tko si ti?
{90313}{90419}Ako se ne varam, ti si Nicky. | - Jesi li ti oteo mog oca?
{90431}{90569}Dobar si borac, kao i tvoj otac. | - Što želiš? - Pustite mog tatu!
{90695}{90802}Slušaj me. Ako ti i tvoja sestra | ne predate memorijske kartice,
{90806}{90908}ubit æemo vašeg oca. - Ne | biste se usudili! Zapalit æu ih!
{90948}{91039}Mala promjena plana! | Memorijske kartica koje imate
{91043}{91128}sadrži detaljne podatke | špijuna kojeg tražim,
{91132}{91227}zove se Tai Chi-Lung. | Dovedite ga meni,
{91231}{91328}i vaš otac æe biti pošteðen. | - Dobro. Uèinit æu to.
{91332}{91403}Ali prvo moram èuti oèev glas.
{91595}{91700}Sad ste na razglasu | sa svojom djecom.
{91874}{91984}Nicky. - Tata! | - Brzo, uzmi sestru i bježi!
{92020}{92122}Isprièajte ga, trenutno | se ne osjeæa dobro.
{92160}{92256}Imate jedan dan da mi | dovedete Tai Chi-Lunga.
{92260}{92359}Pokušajte nešto glupo | i vaš otac æe umrijeti.
{92363}{92505}Zadržite telefon. Zvat æu | vas. - Tata? - Kako je tata?
{92553}{92658}Imamo samo jedan dan. | Moramo naæi tog Tai Chi-Lunga.
{93090}{93172}Potrebno prepoznavanje | korisnikovog glasa.
{93176}{93259}Ovaj dokument je zaštiæen. | - Što to znaèi?
{93262}{93367}Da otvorimo ovaj dokument, | trebamo glas g. Yuea.
{93523}{93655}Imam tatin glas u mobitelu. | - Javi se na telefon...
{93662}{93769}Možda pomogne. | Daj mi da pokušam.
{93831}{93906}Koliko æe potrajati? | Nemamo puno vremena.
{93910}{94016}Možda nekoliko sati. Potrudit | æu se što više mogu. - Hvala.
{94246}{94334}Hej! Hej!
{95103}{95177}Hej, stari!
{95184}{95272}Što kažeš na pivu?
{95643}{95723}To se ne radi tako.
{95787}{95852}Sigurno znaš kako to napraviti?
{95856}{95936}Uèila sam prvu pomoæ u školi.
{95985}{96130}Hvala. - Za što? | - Što si me sad spasio.
{96165}{96267}Da nisi, ne bih | znala da ti je stalo do mene.
{96540}{96645}Moje vještine zavijanja rana | nisu tako dobre kao tatine.
{96649}{96784}Tata je rekao da želi | danas gledati moju predstavu.
{96809}{96887}Nisam mu dopustila.
{96945}{97023}Oboje ga nismo razumjeli.
{97092}{97173}Èitavo je vrijeme govorio istinu.
{97448}{97522}Prijenos u tijeku.
{99557}{99661}Oprostite, gospodine. | Ne možete otiæi.
{102274}{102348}Yue Siu-Bo!
{102412}{102467}Dakle?
{102496}{102581}Jesi li otvorio? | - Da. Upravo sam ga otvorio.
{102585}{102659}Brate, dokument je otvoren.
{102693}{102748}I?
{102770}{102834}Pristup dopušten
{102907}{102984}Tai Chi-Lung.
{103338}{103467}Chiu? - Znate ga? - On | je tatin prijatelj. Posjeæuje ga.
{103490}{103583}Bio je specijalni agent? - Nemamo | vremena, moramo ga pronaæi.
{103587}{103694}Ja æu vas povesti. | Trebamo te memorijske kartice.
{103795}{103870}Što radiš? - Jason, otvori vrata.
{103962}{104062}Oprostite, ne mogu vas | pustiti da tražite Chiua.
{104067}{104167}Ja sam u službi za | zaštitu tajnih agenata.
{104171}{104277}Organizacija je mislila, | pošto g. Yue stari,
{104279}{104358}da neæe više moæi | obavljati poslove sam.
{104362}{104442}Pa su poslali mene da | budem njegovo tajno pojaèanje.
{104446}{104536}Tvoj otac je znao koji je | rizik èim je preuzeo posao.
{104540}{104620}Želim da shvatite da je dužnost | biti spreman žrtvovati se.
{104623}{104703}Sad kad je Chiu u opasnosti, | dužnost mi je štititi ga.
{104784}{104891}Natalie. Žao mi je. | Moraš mi vjerovati
{104904}{104983}da su moji osjeæaju | prema tebi stvarni. - Gade!
{104987}{105067}Bio si sa mnom samo zbog posla.
{105074}{105145}Otvori vrata!
{105374}{105453}Želim ti nešto pokazati.
{105496}{105597}Vidiš, u ovoj ruci nema | nièega. Pogledaj ovdje.
{105642}{105719}Ovo je za tebe.
{106781}{106837}Sestro...
{106909}{107062}Siu-Mun. Pogledaj se, tako si | nepažljiva. Zašto toliko maslaca?
{107076}{107178}Zato što je ukusno tako. | - Moramo paziti što jedemo.
{107182}{107294}A to znaèi manje kolesterola. | - Djede, baš si dosadan.
{108270}{108364}Izvolite, gospodine? | - Gdje ti je šef? - Samo trenutak.
{108368}{108473}Šefe, netko vas želi vidjeti. | Netko vas želi vidjeti. - O.K.
{108509}{108617}Mene trebate? - Tai | Chi-Lung. Ne brinite se,
{108620}{108716}ovdje sam da vas zaštitim. | Vaš identitet je otkriven.
{108720}{108800}Morate odmah otiæi. - Siu-Bo?
{108865}{108989}Koliko imam vremena? | - Nemate. Moramo odmah otiæi!
{109154}{109259}Samo tren. | - Chiu! - Dolazim. Dolazim.
{110249}{110355}Gdje je Chiu? | - Neæete ga uloviti.
{111612}{111681}Što, dovraga?
{112012}{112111}Nemoj bježati, Chiu. | Traže vas neki ljudi.
{112115}{112198}Ako pobjegnete, ne mogu | jamèiti za vašu sigurnost.
{112203}{112311}Vjerovat æu samo | Siu-Bou. - On je veæ zatoèen.
{112320}{112412}Oteli su ga ljudi koji traže | vas. Vjerujete li mi ili ne,
{112417}{112502}moja dužnost je da | vas odvedem odavde.
{112506}{112608}Star sam. Ne želim | nikuda iæi. - Onda mi oprostite.
{112765}{112852}Chiu. - Chiu. - Chiu. - Chiu.
{112856}{112972}Je li netko vidio Chiua? | - Ja nisam. - Otišao je tamo.
{114953}{115053}Moja trgovina i | moja unuka su moj život.
{115057}{115161}Ako si zaista onaj za koga | se izdaješ, ne idem s tobom.
{115588}{115686}Chiu. | Chiu, netko je oteo tatu.
{115688}{115786}Ti ga jedini možeš spasiti. | Molim te, poði s nama.
{115790}{115902}Ne idem s vama. Želite | spasiti Siu-Boa. Cijenim to.
{115912}{116008}Ali moj posao | i unuka su moj život.
{116010}{116098}Želim vidjeti kako | tvoja unuka odrasta.
{116103}{116194}Zašto mi želite to oduzeti? | Ne želim još umrijeti. Žao mi je.
{116198}{116302}Chiu, ne mogu samo sjediti | dok mi je otac u opasnosti.
{116307}{116439}Digni se. - Èovjek koji je | oteo tatu ne traži njega.
{116454}{116561}On traži tebe, Chiu. | Èak i da ovaj put pobjegneš,
{116565}{116686}i dalje æe te tražiti. Otet æe ti | unuku da te prisile na predaju.
{116692}{116792}Umjesto da ovako bježiš, | i stalno brineš za svoju obitelj,
{116796}{116927}zašto im se ne suprotstaviš | i riješiš to jednom zauvijek?
{117756}{117911}Zbog mog oca ili sebe. | - Preklinjem te, molim te!
{118356}{118465}Davno prije, gotovo | sam poginuo u jednoj misiji.
{118469}{118596}Siu-Bo mi je spasio život i | omoguæio živjeti bezbrižan život
{118600}{118726}ovih 12 godina. Otvorio sam | trgovinu. Dobio sam Siu-Mun.
{118766}{118890}Gledao sam kako raste dan za | danom. Osjeæam se jako sretnim.
{118986}{119118}Dobro, iæi æu s vama. Ustanite! | - Hvala ti, Chiu! - Hvala ti!
{119145}{119201}Nicky!
{119381}{119485}Imamo razlièita stajališta. | Nemamo o èemu razgovarati.
{119711}{119815}Ne brini se. Dat æu | i život da vratim Chiua.
{120310}{120415}Imaš li ga? | - Imam Tai Chi-Lunga.
{120419}{120521}Vodi ga do pristaništa Sai Kung. | Netko æe doæi tamo doèekati vas.
{120545}{120648}Želim prvo razgovarati | s ocem. - Budi strpljiv,
{120650}{120749}uskoro æeš ga vidjeti. | Da te podsjetim...
{120752}{120868}Samo ako osjetim nešto | neprikladno kao npr. Policiju,
{120913}{121023}bit æe najfinije jelo koje | su tvoji delfini ikad dobili.
{122174}{122255}Ti si sigurno Nicky, Natalie.
{122278}{122348}Drago mi je što sam | vas napokon upoznao.
{122352}{122435}Gdje je moj otac? | - Gdje je Tai Chi-Lung?
{122438}{122538}Neæemo ga pokazati | dok ne vidimo mog oca.
{122953}{123034}Tata!
{123341}{123449}Ne budite glup. | Trošite vrijeme uzalud.
{123600}{123705}Otac vam se bori | da unese kisik u pluæa.
{123775}{123852}Ostalo mu je još 8 minuta.
{123906}{124007}Još jednom vas pitam. | Gdje je Tai Chi-Lung?
{124011}{124068}Ovdje sam.
{124327}{124444}Tai Chi-Lung, sjeæaš li | me se? - Možda sam star,
{124450}{124621}ali me pamæenje dobro služi. | Ja sam tvoja meta. Pusti ih.
{124656}{124760}Ne možeš doæi na moj teren | i zapovijedati mi što da radim.
{124767}{124899}12 godina sam bio paraliziran | u zatvoru. Izgubio sam ženu
{124905}{125005}i dragocjeno vrijeme sa | svojim sinom zbog tebe!
{125010}{125157}Kako mi se usuðuješ nareðivati? | - Preuzimam odgovornost! Nicky.
{125241}{125354}Odvedi svog oca i sestru | odavde. - Zakleo sam se
{125358}{125468}da vas neæu ostaviti ovdje. | - Nema potrebe da se vi žrtvujete.
{125485}{125563}Iskreno, nitko ne ide nikamo!
{126283}{126387}Spasite tatu. | Ja æu se pobrinuti za Rocca.
{126442}{126521}Sve ih ubij!
{128192}{128269}Sredi tog starca!
{128552}{128629}Stani! Nemoj ga ubiti!
{128675}{128779}Želim da pati | kao što patim i ja!
{129166}{129237}Chiu. - Dobro sam.
{129275}{129348}Idi i sakrij se.
{130481}{130559}Uzalud, to neæe probiti èelik.
{134789}{134848}Tata!
{135272}{135379}Tata, diži se! | Nemoj zaspati! Diži se!
{135385}{135473}Brzo, diži se! Nemoj zaspati!
{135535}{135660}Tata! Nemoj zaspati!
{136914}{137016}Pokret mora biti nježan | i brz, mekan i kontinuiran.
{137019}{137118}Koristi disanje da stimuliraš | chi. Iskoristi duhovnu snagu
{137122}{137235}tako da nema | nejednakosti i nekontinuiranosti.
{137239}{137348}Da bi uspio, zaboravi na | neuspjeh. Ubij to u korijenu.
{137352}{137459}Shvaæaš? -Ne, ne | shvaæam. - Ne shvaæaš?
{137485}{137607}Stisni šaku, udari iz sve snage. | Udari toèku na sredini da pukne.
{138875}{138974}Usuðuješ se udariti me? - Ne. | Molim vas, pustite me!
{139802}{139912}Ubijte mene! | - Ne diraj mi tatu!
{139916}{139994}Hajde!
{140380}{140477}Tata! Diši, diši! Tata! Tata! | - Udahni prije nego progovoriš.
{140480}{140601}Kako si? - Pokvarenjak | mali. - Udahni malo kisika.
{140605}{140701}Želiš da udahnem iz | ovog aparata? - Udahni kisika.
{140705}{140796}Izgledam li kao da mi kisik | treba? - Više nego meni. - Da.
{140800}{140909}Hoæeš da nazovem? - Nemoj se | ljutiti, tata. Da pozovem hitnu?
{140914}{141019}Da, da. - Da. Toliko se brineš | za tatu? Daj tati nešto novaca.
{141024}{141124}Nisi došao kad te otac trebao, | a sad kad sam dobro, pojaviš se.
{141128}{141235}Jesi li vidio kako sam bio | cool? Ja nasuprot njih stotinu.
{141344}{141446}Ne moramo više | razgovarati o odgoju naše djece.
{141450}{141552}Oboje su ispali dobro. | Prošli tjedan na dan oèeva,
{141555}{141665}izveli su me na èaj. Naš sin mi | je èak napisao èek na 8,88 $ .
{141670}{141790}Rekao mi je da požurim i da si | naðem partnericu. Shvaæam.
{141828}{141959}Naša djeca su odrasla. | Nema više vremena za starog tatu.
{141963}{142012}Nedostaješ mi.
{142347}{142502}G. Yue. - Uði. - Moja | kæi se ne ljuti inaèe dugo.
{142506}{142634}Samo reci lijepe stvari i potrudi | se. Predomislit æe se za èas.
{142638}{142738}O.K. - Mekog je srca. Govori | lijepe stvari i ne zatvaraj usta.
{142742}{142849}Samo idi i sredi to- | - O.K. Hvala, g. Yue.
{143044}{143102}Uði.
{143164}{143240}Zašto si došao? Prekinuli smo.
{143294}{143396}Možeš li mi dati | još jednu priliku? - Ne.
{143608}{143735}Dani koje smo zajedno proveli | bili su najsretniji dani života.
{143844}{143951}Znam da mi neæeš oprostiti | koliko god se objašnjavao.
{143958}{144038}Zbog toga poštujem tvoju odluku.
{144064}{144169}Iako više nismo zajedno, | još uvijek ti želim sve najbolje.
{144197}{144327}Nadam se da æeš naæi | nekoga tko te voli više od mene.
{144341}{144455}Što? Odustaješ tako | lako? Ja sam djevojka!
{144463}{144573}Zar ne znaš ništa o nama? | - Što je to trebalo znaèiti?
{144586}{144691}To znaèi da se | možemo viðati i dalje?
{144695}{144868}Možemo? Hvala ti. | Bojao sam se da me više ne želiš.
{145041}{145127}Pomirili su se.
{145330}{145455}Dosadno ti je? - Da. | - Želiš francuski poljubac? - Da!
{145486}{145566}Zatvori prvo vrata.
{145677}{145755}Vrijeme je isteklo. - Što?
{145863}{146007}Igraš mnogo bolje šah. | - Hoæeš pokolj? Uništiti sve moje?
{146020}{146140}Neæeš mi dopustiti da | uzmem èak i jednog pijuna?
{146152}{146293}Svi koji su zajedno, èine jednu | obitelj. I pijuni su ljudi.
{146302}{146457}I oni trebaju biti zaštiæeni. | - Hoæeš li nas nastaviti štititi?
{146514}{146671}Samo sanjaj! Nikad više. | Uživat æu u obiteljskom životu.
{146675}{146765}Obitelj je vrlo važna. Šah!
{146780}{147080}{C:$0000FF}{y:ib} d |{C:$FF0000}{y:b} d 
