{1}{1}29.970
{1363}{1478}Bok, zovem se Caveh,|i upravo æu se oženiti.
{1479}{1621}To mi nije prvi put.|Veæ sam bio oženjen dva puta.
{1622}{1728}Poprilièno sam siguran da æe|mi ovo biti po posljednji puta.
{1729}{1778}Um...
{1779}{1881}Kako to znam sigurno?|Ne mogu, oèigledno.
{1882}{1992}Moja posljednja dva braka, raspala|su se jer sam bio ovisnik o seksu,
{1993}{2057}a to me sada prošlo.
{2058}{2148}Bar ne u smislu kojeg|je bilo prije.
{2149}{2194}Um...
{2195}{2319}Prije 10 godina krenuo sam na|sastanke Anonimnih ovisnika o seksu.
{2320}{2421}Bok, zovem se Caveh.|I ovisnik sam o seksu.
{2422}{2481}Bok, Caveh.
{2482}{2639}Za mene, sve je poèelo|prije nekih 7 godina u Parizu.
{2831}{2969}Ustvari, nisam mogao pronaæi|novac za put u Pariz,
{2970}{3037}pa æu snimati ovo|ovdje u San Franciscu.
{3038}{3084}Gdje trenutno živim.
{3085}{3176}Pa, ako se možete|pretvarati da je ovo Pariz...
{3375}{3462}...a da sam ja|star 23 godine...
{3559}{3652}I tako, šetao sam|jedan dan ulicom...
{3723}{3866}...kad sam ugledao prostitutku.
{3889}{4003}Prvo što me zateklo,|je njezina odjeæa.
{4005}{4114}Onda sam ugledao nju,|èistu kopiju moje žene.
{4121}{4219}Pomislio sam da je èudno da me|ta žena toliko napali,
{4220}{4338}a istovremeno da me|podsjeæa na moju ženu.
{4339}{4393}Jebeno zaèepi!
{4394}{4465}Ovo je Caroline, moja žena.
{4466}{4524}Kako sam se oženio njom?
{4525}{4650}Umjesto sa ženom u koju sam|bio zaljubljen jako dugo.
{4651}{4774}Ali trebao bih poèeti objašnjavajuæi|da se nikad ne bih oženio sa Caroline
{4775}{4863}da nije bila Francuskinja
{4897}{4978}i da je njezina viza|bila na isteku.
{4987}{5082}Ustvari, vratimo se malo unatrag.
{5162}{5216}Ovo je Anna.
{5217}{5344}Ona je bila moja prva prava djevojka|i ljubav mog života.
{5370}{5492}Upoznali smo se na koledžu i|bili smo zajedno dvije godine.
{5511}{5618}Trebao bih objasniti|da otkad sam bio klinac,
{5619}{5717}bio sam opsjednut|pronaæi svoju srodnu dušu.
{5718}{5789}Svaki put kad bih|upoznao djevojku, pomislio bih,
{5790}{5834}Da li je ona ta?
{5835}{5879}Da li je ona?
{5880}{5948}Ili ona?
{5949}{6044}Neprestano sam se zaljubljivao|bez imalo razmišljanja,
{6045}{6188}ali djevojke koje su mene|privlaèile, nisam privlaèio ja.
{6206}{6276}Stvari su tako stajale godinama.
{6277}{6401}Poèeo sam pomišljati da nikada|neæu pronaæi srodnu dušu.
{6413}{6492}I tada sam upoznao Annu.
{6514}{6603}Imala je èudesniju dušu, od bilo koje|koju sam ikada upoznao.
{6625}{6743}I dvije godine koje smo proveli zajedno|bile su najsretnije godine mog života.
{6794}{6869}Èinilo se da nikada ništa neæe|moæi stati izmeðu nas.
{6870}{6949}I da æemo zauvijek|biti zajedno.
{7019}{7110}Jedini problem je bio|da sam volio filozofirati
{7111}{7189}i da sam vjerovao u slobodnu ljubav.
{7243}{7338}Za mene, monogamija je bila|forma privatnog vlasništva,
{7339}{7423}a ja sam bio protiv|privatnog vlasništva.
{7424}{7497}Da pokušam objasniti drugaèije.
{7526}{7662}Naši uzori u tim danima bili su|Jean Paul Satre i Simone de Beauvoir,
{7663}{7752}jer su za njih govorili da su|imali poligamijsku vezu,
{7753}{7837}koja je potrajala cijelog|njihovog života.
{7891}{7995}Anna je imala svoje afere|pa sam i ja imao svoje.
{7996}{8073}Naravno, ponekad smo oboje|bili pomalo ljubomorni,
{8074}{8175}ali vjerovali smo da je ljubomora|samo nešto neodreðeno i
{8176}{8287}da je moguæe istovremeno|voljeti nekoliko osoba...
{8312}{8405}...a to je dovelo do toga da|se upletem sa Caroline.
{8489}{8573}Upoznali smo se u Parizu|nekoliko mjeseci ranije,
{8574}{8631}i proveli tri idilièna|dana zajedno.
{8632}{8774}Znam da sam rekao da si ne možemo|priuštiti snimanje u Parizu, doista ne možemo,
{8775}{8850}ali glumici koja igra|Caroline,
{8851}{8986}doista je istekla viza i ona se|morala vratiti u Francusku,
{8987}{9070}prije nego što smo|dovršili ovaj film.
{9071}{9154}Ustvari, da se vratim još malo|unatrag.
{9155}{9267}Vidite, bio je stvarno veliki problem|pronaæi Francuskinju da igra moju ženu.
{9268}{9329}I onda sam jednog dana|vidio tu ženu kako hoda ulicom,
{9330}{9397}koja je izgledala|poput prave Caroline.
{9398}{9495}Poèeo sam prièati s njom i|ispostavilo se da je ona Francuskinja.
{9496}{9549}Zakazao sam joj audiciju.
{9550}{9660}Što radiš u životu?|Što ti je posao?
{9661}{9709}Imam tvrku za šminkanje.
{9710}{9771}Doista?|Ti šminkaš glumce?
{9772}{9856}Ustvari, uèim ljude|kako da se sami šminkaju.
{9857}{9920}Doista? Dakle, ti uèiš druge, kako|da šminkaju glumce?
{9921}{9958}Da.
{9959}{10007}Trebao bih objasniti,
{10008}{10096}da je i prava Caroline|bila u istom poslu,
{10097}{10237}što sam protumaèio kao znak|da imam pravu osobu za posao.
{10238}{10356}Ali onda se nekoliko mjeseci poslije,|kad smo trebali poèeti snimati,
{10357}{10415}dogodilo nešto èudno.
{10416}{10513}Okej, upravo se nešto|èudno dogodilo.
{10514}{10684}Tražio sam francusku prostitutku,
{10685}{10759}da glumi u filmu|u sceni prostitucije.
{10760}{10813}Gdje je?
{10814}{10856}Eto je.
{10857}{11001}Pronašao sam lice koje se|zvalo Rebecca Lord.
{11002}{11076}Pogledao sam...
{11115}{11179}i bio sam poput...
{11180}{11263}"Porno zvijezda, Rebecca Lord, Francuskinja"
{11264}{11411}I rekoh, "Ona izgleda|tako slièna Caroline."
{11443}{11506}Pogledao sam dalje.
{11507}{11593}Rekoh, "Ona stvarno|slièi Caroline."
{11594}{11689}I onda sam vidio
{11690}{11771}"radila na šminkanju glumaca."
{11772}{11844}To je Caroline bila.
{11847}{11988}I pisalo je da æe posjetiti San Francisco|od 07-11-og kolovoza,
{11989}{12069}da æe sudjelovati|na nekakvom snimanju.
{12070}{12149}Pomislih, "Samo malo.
{12150}{12298}Caroline... je prostituka?"
{12404}{12480}I bila je tamo|lista filmova.
{12489}{12579}Njezina lista.
{12714}{12788}Kurve Francuske.
{12861}{13024}I tako sam angažirao porno glumicu|da igra moju ženu Francuskinju.
{13025}{13118}Ali vratimo se na prièu.
{13183}{13238}Upoznali smo se u Parizu|nekoliko mjeseci,
{13239}{13349}te proveli tri idilièna dana zajedno.
{13384}{13444}Bio sam potpuno iskren|prema Caroline
{13445}{13533}o mojoj vezi sa Annom.|Upitao sam je;
{13534}{13604}Da li si ikada|bila ljubomorna?
{13605}{13639}Na što je ona odgovorima,
{13640}{13721}Život je prekratak za|takve stvari.
{13722}{13800}Iznenadila me odgovorom,
{13801}{13929}te sam shvatio da se|poèinjem zaljubljivati u nju.
{13939}{14059}Ali još uvijek sam vjerovao da je|Anna bila prava ljubav mog života.
{14076}{14193}Ali onda, mjesec dana poslije,|Caroline je doletjela da me posjeti,
{14194}{14273}i tada su poèele nevolje.
{14274}{14363}Vidite.|Anna je postala ljubomorna na Caroline.
{14364}{14453}Inzistirala je da|izaberem izmeðu njih dvije.
{14454}{14522}Nisam želio izabirati|izmeðu njih
{14523}{14610}želio sam ih viðati obje.
{14619}{14699}Ali onda je Anna imala|ljetna predavanja u New Yorku.
{14700}{14821}A Caroline i ja smo cijelo|ljeto proveli zajedno.
{14822}{14920}Zbog èega joj je|viza i istekla.
{14921}{15035}Ponudio sam se da je oženim|kako bi mogla ostati u Americi.
{15036}{15173}Trebao bih objasniti da ja i|nisam tip za ženidbu.
{15174}{15264}Ustvari, bio sam totalno|protiv tih stvari.
{15265}{15356}Odrastao sam|za vrijeme vijetnamskog rata
{15357}{15450}i gledao sam na brak kao na|dio istog kapitalistièkog sustava
{15451}{15538}koji je vršio genocid|nad Vijetnamom.
{15753}{15849}Ali bio sam i pod utjecajem|performanse...
{15861}{15977}i ideje života kao takve,|da je on samo dio performansa.
{16015}{16144}Za mene institut braka|je bio toliko apsurdan
{16145}{16240}da sam ga pokušao preokrenuti|tretirati ga kao èin performanse.
{16241}{16275}Uzimam.
{16276}{16388}Osim što se šala, okrenula|prema meni i bila na moj raèun.
{16389}{16491}Jer kad je Anna saznala da sam|oženio Caroline,
{16492}{16577}nije to tako dobro primila.
{16603}{16694}I tada sam uèinio|nešto stvarno glupo.
{16713}{16814}Vidite, Caroline i ja|smo ostali bez novca...
{16838}{17011}a ideja da pronaðem posao bila mi je|gora od pomisli na smrt.
{17019}{17093}Jedino što me zanimalo
{17094}{17174}je da postanem|slavni filmski redatelj.
{17175}{17245}Ali nekoliko ekperimentalnih filmova|koje sam napravio,
{17246}{17398}nisu prihvaæeni sa velikim entuzijazmom|od strane filmskog svijeta.
{17679}{17734}Da bih ublažio ovu situaciju,
{17735}{17863}nedavno sam napisao scenarij o|francuskom piscu Arthuru Rimbaudu,
{17864}{17978}za koji sam siguran da|æe revolucionirati filmski svijet...
{18037}{18160}i za koji je Caroline tvrdila da æe|zaraditi puno novca u Francuskoj.
{18170}{18299}Zaraditi æe puno|novca u Francuskoj.
{18314}{18444}Ali selidba u Francusku|ispala je prava katastrofa.
{18457}{18594}Veæina filmskih producenata koje sam|pokušao vidjeti, nije me htjela primiti.
{18595}{18736}Ona nekolicina koja je,|samo mi je rekla da sam nitko i ništa.
{18754}{18880}Istvoremeno, moja veza|sa Caroline je zapadala u krizu.
{18903}{19024}Caroline je bila ljubomorna na Annu|i histerièno bi plakala
{19025}{19102}kad god bih joj pisao pismo|ili prièao s njom na telefon.
{19103}{19150}Bok, kako si?
{19151}{19251}Poèeo sam se osjeæati zatoèenim i|nije mi bilo teško za to okriviti Caroline,
{19252}{19388}da pokušava stati izmeðu|na kraj moje veze sa Annom.
{19389}{19484}I tada jednog dana,|dobio sam pismo od Anne.
{19485}{19565}Pisala je da dolazi|u Amsterdam
{19566}{19663}i upitala me|da li bih htio doæi do nje.
{19692}{19733}Bio sam zaluðen.
{19734}{19865}Osjeæao sam da konaèno imam šansu|ponovno vratiti Annu.
{19874}{19999}Ali Caroline je znala da ako odem,|nikada se više neæu vratiti.
{20000}{20085}Pa je odluèila|skoèiti kroz prozor.
{20126}{20186}Pomisao da sam bio|odovoran za njezinu smrt
{20187}{20272}bila je veæa nego|što sam mogao podnijeti.
{20273}{20387}Caroline! Caroline!|-Ne! Ne!
{20437}{20543}I odluèio sam nikada|više ne sresti Annu.
{20717}{20835}Bila je to najbolnija|odluka koju sam uèinio.
{20840}{20918}Ali donio sam je, jer godine|pohaðanja veèernjih škola,
{20919}{21041}nauèili su me da stvarni život|zahtijeva odreðena odricanja.
{21081}{21159}Mogu li dolje?|Još jednom.
{21160}{21287}Trebao bih objasniti, da kad|sam bio na koledžu
{21288}{21366}jednom sam pitao|prijatelja Alfreda...
{21435}{21545}Što ti je glavni cilj u životu?
{21546}{21587}A on je rekao...
{21588}{21645}Postati svetac.
{21646}{21731}Ostao sam zateèen|njegovim odgovorom
{21750}{21865}i odluèio sam da i ja|trebam pokušati postati svetac.
{21900}{22005}Zbog èega sam,|kad mi je Caroline rekla
{22006}{22114}da prekinem svaku vezu sa osobom|koju sam ikada stvarno ljubio,
{22115}{22194}odluèio sam je poslušati.
{22276}{22332}Kad sam mnogo kasnije saznao
{22333}{22417}da se Anna udala|za nekoga drugoga
{22418}{22486}bio sam shrvan od bola.
{22487}{22638}Potajno sam se nadao da æemo|Caroline i ja jednom prekinuti,
{22639}{22735}i da æe Anna tada|ponovno biti dio mog života.
{22736}{22867}Ali tada sam shvatio da|sam stvarno gotov.
{22965}{23045}Pokušao sam što više|zanemariti svoje osjeæaje
{23046}{23172}i odluèio sam živjeti svoj život|u tihoj patnji.
{23173}{23270}Ali ustvari, bio sam|strašno ljut
{23271}{23329}na Boga,
{23330}{23384}na Caroline,
{23385}{23461}i na samog sebe.
{23462}{23583}Ali najviše na Caroline.
{23600}{23703}I tada jednog dana,|hodao sam ulicom,
{23704}{23841}kad sam ugledao...|prostitutku.
{23923}{23960}Nešto na njoj
{23961}{24102}toliko me napalilo|kao nikada do tada.
{24120}{24220}Kao da sam bio hipnotiziran.
{24429}{24561}I tada sam izrekao nešto što|nikada do tada nisam izrekao.
{24562}{24640}Rekoh...
{24670}{24819}Želim objasniti da sam se uvijek|smatrao feministom
{24820}{24948}i da sam jednom bio u grupi ljudi|koji su protestirali protiv pornografije.
{24992}{25037}Zbog èega
{25038}{25133}kad sam se èuo|kako izgovaram te rijeèi
{25157}{25263}oèekivao da æe prostitutka|vrišteæi pobjeæi...
{25313}{25387}...ili me ošamariti.
{25414}{25575}Èinjenica da to nije uèinila|nego se nasmiješila i rekla...
{25577}{25626}Popušiti æu ti|i pojebati te.
{25628}{25685}zavrtilo mi je glavu.
{26140}{26263}Poslije, bio sam|totalno uznemiren.
{26302}{26387}Nisam je mogao|izbiti iz glave.
{26748}{26819}Bok.|-Bok.
{27096}{27243}Mislio sam da ako budem masturbirao,|izbiti æu je iz glave.
{27246}{27330}Ali nije uspjelo.
{27375}{27495}Nakon nekoliko dana|neprestane masturbacije,
{27496}{27597}pomislih da trebam|novu strategiju.
{27880}{27988}Vidite, znao sam da ona|nije obièna osoba,
{27989}{28154}ali nekako, u svojoj glavi, zamišljao|sam je kao vlastito erotsko spasenje,
{28164}{28306}i èinilo se da jedini naèin da je|spustim sa tog erotskog pijedestala
{28307}{28398}bio da poprièam sa njom.
{28498}{28612}Nažalost, nije bila tamo.
{29008}{29139}Ljutio sam se na sebe što sam na nju|potrošio tolike sate svog života.
{29140}{29233}Ali nisam želio otiæi samo tako.
{30106}{30280}Isto pitanje upitao sam|svaku prostituku koju sam sreo tog dana.
{30281}{30376}Neke sam pitao i|po dva puta.
{30386}{30512}Poslije, osjeæao sam se|tako euforièno.
{30515}{30666}I vratio sam se kuæi misleæi|da sam konaèno uspio izbiti si to iz glave.
{30710}{30761}Ali nisam bio u pravu.
{30762}{30867}Umjesto da maštam o samo|o jednoj prostitutki,
{30868}{30965}sada sam maštao o|njima svima.
{30993}{31057}Vratio sam se i sljedeæi dan...
{31058}{31142}i sljedeæi...
{31143}{31225}i sljedeæi.
{31255}{31360}Ispoèetka bilo je dovoljno|da razgovaram s njima...
{31396}{31471}i da maštam|o njima poslije.
{31561}{31704}Ali nakon nekog vremena,|to nije više bilo dovoljno.
{31940}{32019}Znam da bi mnogi muškarci|u mojoj situaciji
{32020}{32096}imali seks sa prostitutkom
{32097}{32159}i nikada to ne bi rekli|svojoj ženi.
{32160}{32235}Ali mene je oduvijek|muèila ta iskrenost.
{32236}{32307}Kad sam bio klinac,
{32308}{32408}moja majka je saznala|da je moj otac vara.
{32409}{32516}I odvezla je mene i moju sestru|u kuæu te druge žene
{32517}{32611}da bi ga ponizila|pred nama.
{32612}{32692}Bio sam premlad da|bih znao što je to seks,
{32693}{32765}ali znao sam da je|to nešto užasno.
{32766}{32866}I da je odgovorno za|razvod mojih roditelja.
{32867}{32964}Tada sam imao samo osam godina,
{32965}{33026}ali poèeo sam|mrziti svog oca.
{33027}{33139}I zakleo sam se samom sebi, da|nikada neæu biti poput njega.
{33533}{33677}Znaš, ako ti stvarno|trebaju prostitutke, pristajem.
{33678}{33797}Ne želim ih.|Želim se oduprijeti tome.
{33798}{33850}Ali trebam tvoju pomoæ.
{33851}{33918}Što želiš da uèinim?
{33919}{33989}Samo želim moguænost|da razgovaram s tobom.
{33990}{34080}Mislim da ako mogu o tome|prièati s tobom, biti æe mi manje privlaèno,
{34081}{34135}i biti æe mi se lakše|oduprijeti tome.
{34136}{34215}Možemo razgovarati o tome.
{34216}{34266}Možemo?
{34267}{34338}Naravno.
{34426}{34519}Dobro, osjeæam se|mnogo bolje.
{34604}{34682}Da li si imao seks|sa prostitutkom
{34683}{34810}ili ti je samo pušila?
{34811}{34869}Oh, ne. Samo pušenje.
{34870}{34968}Nikada ne bih želio imati seks s njom.|To me totalno užasava.
{34969}{35045}Doista?|-Oh, da.
{35046}{35129}Ti si jedina osoba s kojom|želim imati seks.
{35130}{35174}Obeæavaš?
{35175}{35281}Da, obeæavam.
{35377}{35503}Da li ti išta mogu uèiniti|da bih ti smanjila tu potrebu?
{35566}{35674}Možda da mi popušiš|èešæe?
{35675}{35725}Nemam ništa protiv.
{35726}{35843}Mogu i odmah sada,|ako želiš.
{35884}{35944}Okej.
{36044}{36123}Osjeæao sam krivnju|prihvaæajuæi njezinu ponudu,
{36124}{36220}ali mislio sam da bi to|mogla biti dobra ideja.
{36564}{36649}Još uvijek sam maštao|da je ona prostitutka,
{36650}{36733}ali to što je ona to znala|i prihvaæala me takvog,
{36734}{36804}èinilo je to drugaèije|nego prije.
{36805}{36954}Kao da smo nešto dijelili,|nešto radili zajedno.
{36955}{37077}I osjeæao sam da po prvi put|doista volim Caroline.
{37148}{37251}Nakon što sam svršio,|još mi je bio tvrd.
{37252}{37346}To mi se nikada prije|nije dogodilo.
{37347}{37436}To što više nisam morao|susprezati svoju seksualnost
{37437}{37561}kao da je otkoèilo moju|suzbijenu seksualnu energiju.
{37562}{37659}Pa se Caroline ponudila da mi|ga popuši još jednom.
{37772}{37879}Na moje èuðenje, još mi je|uvijek ostao tvrd.
{37880}{37995}Pa se Caroline ponudila da mi|ga popuši još jednom.
{38077}{38187}Nakon toga, još mi je|bio tvrd.
{38188}{38325}Nikada nisam vidio nešto slièno,|i iskreno, poèeo sam se bojati.
{38326}{38483}Bojao sam se da bi moja erekcija|mogla ostati trajna i nikada više ne otiæi.
{38484}{38559}Caroline se ponudila za još|jedno pušenje,
{38560}{38636}ali nedavno sam dobio posao|kao filmski kritièar
{38637}{38739}i nisam želio zakasniti na|svoj prvi film.
{38856}{38978}Na putu onamo, moja erekcija|se konaèno okonèala,
{39197}{39294}U jednom trenutku osjetio sam|istinsku ljubav prema Caroline,
{39295}{39394}i osjeæao sam joj se bliskijim|nego ikada prije.
{39471}{39539}Kao dio naše nove|bliskosti
{39540}{39628}poèeo sam Caroline govoriti|koje me žene privlaèe.
{39629}{39690}Sviða mi se ova.
{39691}{39765}Ta?|Odurna je!
{39766}{39829}Meni nije.
{39830}{39932}I ona mi se sviða?|-Šališ se, toèno?
{39933}{39995}Ne, ozbiljan sam.|Ona je upravo moj tip.
{39996}{40039}Ali tako je vulgarna.
{40040}{40177}Znam. To je ono što mi se|na njoj sviða. Istina je.
{40195}{40328}Vidjela si onu ženu?|S njom bih volio imati seks.
{40467}{40564}Bilo je tako odlièno|biti potpuno iskren prema Caroline,
{40565}{40656}da sam poèeo osjeæati da napokon|imam otvorenu i iskrenu vezu
{40657}{40742}o kakvoj sam|oduvijek sanjao.
{40743}{40825}Pazi te usne!
{40826}{40919}Volio bih da|mi ona popuši.
{40977}{41047}Vidjela si onu?
{41099}{41247}Ali nakon nekog vremena,|Caroline više nije mogla podnijeti.
{41746}{41823}Što je?|-Što misliš?
{41824}{41936}Dosta mi je da cijelo vrijeme|gledaš u druge žene.
{41937}{42002}Ponižavajuæe je.|-Što bih trebao?
{42003}{42088}Trebao bih ti skrivati èinjenicu|da me netko privlaèi?
{42089}{42242}Što bi rekao kad bih poèela sliniti|na svakog tipa koji me privlaèi?
{42243}{42356}Vjerovatno bih bio malo ljubomoran,|ali pokušao bih to potisnuti.
{42369}{42413}Doista!
{42414}{42480}Nisi li rekla da želiš|da sam potpuno iskren prema tebi?
{42481}{42565}Promijenila sam mišljenje!
{42677}{42761}To što više nisam mogao|biti potpuno iskren prema njom,
{42762}{42830}dovelo je do toga, da sam|se opet osjeæao utuèenim.
{42831}{42980}I poèeo sam maštati o ženama|koje sam sretao na ulici.
{42981}{43025}Sjeæam se jednom,
{43026}{43169}kad sam vidio ženu u vlaku,|koja me pomalo privlaèila.
{43206}{43349}Ne znam što sam mislio, ali odjednom|sam je poèeo slijediti.
{43476}{43619}Iz nekog razloga, želio sam posegnuti|za njoj i dodirnuti joj butinu.
{43806}{43865}Pokušavao sam smoæi|hrabrost za to uèiniti
{43866}{43980}kad se odjednom pojavio|njezin deèko.
{44076}{44249}Ali ona me toliko napalila, da|sam poželio masturbirati.
{44316}{44430}Jedino mjesto koje sam mogao|pronaæi bila je ispovjedaonica.
{44556}{44651}Bilo je nešto u ideji da|masturbiram u ispovjedaonici
{44652}{44723}što je u meni pobudilo|osjeæaj dodatne napaljenosti.
{44724}{44926}Nije prošlo dugo, a veæ sam masturbirao|u svakoj crkvi u Parizu.
{44927}{45048}U meðuvremenu, Caroline i ja|svaðali smo se sve èešæe
{45049}{45133}i poèeo sam joj prijetiti da æu se|poèeti opet seksati sa prostitutkama
{45134}{45198}kako bih je natjerao da|se prestane svaðati sa mnom.
{45199}{45266}Idem se seksati sa prostitutkom!
{45267}{45413}Lijepo! Idi, daj joj da ti popuši,|pa da vidimo da li me uopæe briga!
{45622}{45743}I onda sam se jednog|dana nekako uvjerio
{45744}{45874}da joj više bola nanosim samim time|što joj prijetim seksom s prostitutkom,
{45875}{45926}nego što bih da to|doista i uèinim.
{45927}{46022}I da to odbacim jednom|za svagda iz svog života.
{46656}{46743}Želio sam joj dotaknuti butine
{46744}{46822}ali osjeæao sam|se sramežljivo.
{46823}{46913}Nisam znao da li|je bilo dozvoljeno.
{50496}{50560}Uh...
{50910}{50991}Um...
{51834}{51881}Bio sam iskreno u napasti...
{51882}{52068}ali znao sam da se mogu suzdržati od|odnosa s njom, dok ona nije rekla...
{52070}{52125}Siluj me.
{52127}{52283}Iz nekog razloga, te rijeèi aktivirale|su kemijsku reakciju u mojem mozgu.
{52284}{52382}I odjednom, kao da|nisam imao izbora.
{52599}{52664}Nisam siguran zašto...
{52666}{52753}ali to što njezina gluma|i nije bila tako uvjerljiva...
{52754}{52842}još me samo|više napalilo.
{53712}{53765}Nešto ti moram priznati.
{53766}{53901}Znam. Imao si|seks sa prostitutkom.
{54003}{54072}Kako znaš?
{54119}{54188}Znam.
{54199}{54272}Nisi ljuta na mene?
{54282}{54380}Ne, nisam.
{54470}{54541}Mislim da je to bilo|ispravno uèiniti
{54542}{54643}jer sada sam to konaèno|izbacio iz svoje glave.
{54745}{54808}Volim te.
{54809}{54931}Znam. Samo, molim te,|otuširaj se.
{55584}{55712}Reci mi, što se dogodilo.
{55789}{55858}Rekoh joj cijelu prièu.
{55859}{55979}Ali kad sam došao do èina seksa,|poprilièno se uzrujala.
{55980}{56054}Ušao si u nju?
{56063}{56109}Da.
{56110}{56162}Ali koristio sam kondom.
{56163}{56231}Obeæao si da to nikada neæeš uèiniti.
{56232}{56316}Znam, oprosti.
{56337}{56470}Pokušao sam, ali|nisam si mogao pomoæi.
{56537}{56684}Rekla je, siluj me,|i nakon toga sam se napalio.
{56691}{56836}Želim objasniti da je to za Caroline|bilo najteže èuti,
{56837}{56948}jer je i sama jednom|bila silovana.
{56971}{57088}Nadao sam se da æe potpuna|iskrenost biti najbolje za našu vezu.
{57089}{57187}Ali preraèunao sam se.
{57345}{57433}Ne želim voditi ljubav veèeras.
{57434}{57507}Nisam niti htio predložiti.
{57508}{57589}Nije da te želim kazniti.
{57590}{57621}Znam.
{57622}{57729}Samo mi treba više vremena|da prihvatim sve ovo.
{57730}{57828}Razumijem.|Koliko god vremena hoæeš.
{57845}{57904}Hvala.
{58059}{58163}Iznenadio sam se koliko joj|je malo vremena trebalo.
{58176}{58256}Samo tri dana.
{58281}{58415}Nakon toga, sve se poprilièno|vratilo u normalu.
{58416}{58565}Osim jedne stvari... Caroline se iz|nekog razloga poèela onesvješæivati.
{58598}{58659}Caroline! Caroline!|Što ti je?
{58660}{58761}Ne znam.|Ne osjeæam se dobro.
{58762}{58889}Išli smo do nekolicine doktora.|Pokušavali smo shvatiti što joj je.
{58890}{58966}Ali nitko od njih|nije ništa pronašao.
{58967}{59041}Ona je savršena zdravlja.
{59155}{59305}Prošlo je više od dva mjeseca|od kada smo vodili ljubav.
{59354}{59439}Ako želiš da ti ga popušim,|uèiniti æu to.
{59440}{59493}Ne govorim o tome.
{59494}{59599}Možda je to zbog toga|jer se ljutiš na mene.
{59606}{59767}Ne ljutim se.|Samo se ne osjeæam dobro.
{59788}{59849}Okej.
{60000}{60089}Sigurno ne želiš da ja tebe|zadovoljim oralno?
{60090}{60189}Caveh, doista se ne|osjeæam dobro.
{60190}{60251}Okej.
{60413}{60486}Tako je bilo gotovo godinu dana,
{60487}{60625}tijekom koje se moja napaljenost|na prostitutke vratila.
{61230}{61296}Pokušavao sam pobjeæi od|braène nesreæe
{61297}{61355}bacajuæi se na posao...
{61356}{61416}Više!
{61435}{61473}Rekoh, više!
{61474}{61558}{Y:i}...ali nisam mogao namaæi novac|za bilo koji vlastiti filmski uradak.
{61559}{61619}Više!
{61666}{61793}Što ti je?|Možeš li više skoèiti?
{61927}{62072}U oèaju, prijavio sam se ponovno|na filmsku akademiju u Americi.
{62305}{62380}Ubrzo nakon što smo se|odselili u Los Angeles,
{62381}{62516}Caroline mi je priznala da se|zaljubila u mog prijatelja Garyja...
{62522}{62623}nakon njega, da je zaljubljena i u mog|prijatelja Keitha...
{62628}{62729}a nakon njega, u mog|prijatelja Teddyja...
{62730}{62827}Tjedan poslije,|ona i Teddy su poèeli živjeti zajedno.
{62828}{62925}Godinu poslije, vjenèali su se.
{62941}{63007}To je prava Caroline.
{63008}{63129}Pitao sam je da odigra ulogu sebe u|filmu, ali odbila je.
{63157}{63230}Pokušao sam ostati s njom|u kontaktu kroz ove godine.
{63231}{63374}Ali nakon što mi se prestala|javljati na telefonske pozive,
{63424}{63540}shvatio sam da iako sam|mislio da volim Caroline,
{63541}{63630}prava istina je bila,
{63631}{63723}ja nisam sposoban|voljeti nikoga.
{63724}{63836}Mislim, u to vrijeme, imao sam|samo 26 godina.
{63933}{64104}Nakon prekida, jedino o èemu sam|razmišljao je pronaæi nekoga za seks.
{64499}{64562}Bok, mogu li uæi?
{64563}{64603}Koliko?
{64604}{64691}Koliko želiš potrošiti?
{64725}{64761}30?
{64762}{64816}Okej. Mogu uæi?
{64817}{64887}Okej.
{65035}{65128}Bok, zovem se Candy.|-Ja sam Bob.
{65129}{65236}Drago mi je.|-I meni.
{65720}{65861}Kamo æemo?|-Stani tamo.
{66296}{66342}Mogu li dobiti novac?
{66343}{66435}Oh, naravno.
{66465}{66517}Um...
{66518}{66566}Imaš li mi za razmijeniti?
{66567}{66677}Ne, ali ako mi daš 40,|biti æu vrlo dobra.
{66678}{66742}Um...
{66765}{66828}Okej.
{66919}{66985}Pazi na muriju, ok?
{67495}{67567}Bok.
{67863}{67969}Poslije, osjeæao sas|se euforièno.
{68003}{68055}Ali kad sam stigao kuæi,
{68056}{68164}osjeæao sam se prazno|i depresivno.
{68165}{68300}I zakleo sam se da više nikada|neæu imati odnos sa prostitutkom.
{68355}{68399}Ali nekoliko dana poslije...
{68400}{68542}poèeo sam maštati o|istoj prostitutki.
{69023}{69062}Želiš li?
{69063}{69103}Bilo je šablonski.
{69104}{69195}Svaki put kad bih imao|odnos s prostitutkom,
{69196}{69286}osjeæao bih se prazno|i depresivno poslije toga,
{69287}{69360}i zaklinjao bih se da to|više nikada neæu uèiniti.
{69361}{69481}Uvjerio sam se da ako to|dovoljno puta uèinim,
{69482}{69608}moja želja za seksom sa prostitutkom,|s vremenom æe nestati.
{70392}{70449}Onda sam upoznao Christu.
{70450}{70530}Išao sam hodnikom|filmske akademije...
{70531}{70602}kad sam je prvi|put ugledao.
{70603}{70678}Bok.
{70702}{70835}Nije bilo uobièajeno za žene koje|me vide prvi put, da me pozdrave.
{70836}{70971}Buduæi da ona je, pretpostavljao|sam da želi seks sa mnom.
{71109}{71224}Nakon nekoliko dana,|vidio sam je opet.
{71461}{71529}Oprosti.
{71546}{71615}Znaš li kako ovo otvoriti?
{71616}{71680}Ne mogu skužiti.
{71681}{71755}Pokušati æu.
{71853}{71889}Eto ga.
{71890}{71982}Samo se odvrne, je li?
{72056}{72100}Voliš Capru?
{72101}{72179}Volim Capru.
{72188}{72273}Zovem se Caveh.|-Ja sam Christa.
{72274}{72363}Drago mi je.|-I meni.
{72391}{72540}Pozvala me na zabavu koju je|pripremala za petak naveèer...
{72569}{72668}...otišao sam,|nadajuæi se seksu s njom.
{72737}{72829}Christa je ovdje?|-Da, uði.
{73017}{73121}Nisam uspio u svojoj nakani.
{73140}{73242}Ali uspjela mi je uvaliti|kopiju svog scenarija.
{73249}{73334}Bio je to jedan od najboljih scenarija|koje sam ikada proèitao.
{73553}{73676}I pomislio sam da sam konaèno pronašao|nekoga na koga se mogu osloniti.
{73698}{73811}Odmah sam je nazvao i|pozvao je na spoj.
{74111}{74185}Tada se dogodilo,
{74193}{74321}pogledao sam je u oèi i|vidio njezinu dušu.
{74345}{74487}Do tada, bila je samo netko, od|koga sam nešto želio dobiti.
{74497}{74613}Ali od tog trena, shvatio sam da je|ona još jedno ljudsko biæe.
{74614}{74726}Sa vlastitim potrebama|i osjeæajima.
{74744}{74814}Usrao sam se od straha.
{75100}{75258}Jedne veèeri gledali smo|"Vivre Sa Vie" od Jean-Luc Godarda,
{75259}{75367}o ženi koja je postala|prostitutka...
{75386}{75466}Znaš što sam èula?
{75467}{75500}Što?
{75501}{75604}Èula sam da Godard u stvarnom|životu ima fetiš prema prostitutkama.
{75605}{75675}Možeš li vjerovati?
{75676}{75744}Da.
{75774}{75899}Ja ne mogu.|Èini se tako osjeæajnim prema ženama.
{75900}{75946}To ništa ne znaèi.
{75947}{76121}Mislim, i ja sam osjeæajan prema|ženama, a imama isti fetiš.
{76149}{76204}Šališ se?
{76205}{76281}Ne, ozbiljno.
{76309}{76356}Ne mogu vjerovati.
{76357}{76437}Pa, istina je.
{76438}{76558}Caveh, kako je to moguæe?|Kako to možeš podnijeti?
{76559}{76635}Slažem se da nije potpuno|moralno ili nešto takvo...
{76636}{76725}ali mislim i da nije|užasno.
{76726}{76846}Caveh, to je poput silovanja!|Te žene nemaju izbora.
{76847}{76933}Svatko ima izbor.|Ili ga nitko nema.
{76934}{76988}Ne mogu vjerovati|da si to rekao.
{76989}{77066}Istina je.
{77111}{77151}Što to radiš?
{77152}{77252}Moram iæi.|Mislim da æe mi pozliti.
{77253}{77334}Samo zato što sam imao|seks sa prostitutkom?
{77335}{77385}Caveh, ne razumiješ.
{77386}{77526}Doslovno osjeæam da æu|povraæati. Moram iæi.
{77563}{77631}Christa!
{77830}{77901}Nakon nekoliko dana,|sreo sam je opet.
{77902}{78012}Bok.
{78166}{78262}Još ti je zlo?|-Ne.
{78263}{78327}Sigurno ti ne smeta|da se vidimo?
{78328}{78380}Prestani.
{78381}{78490}Oprosti. Mislio sam da sam|ti oduran.
{78491}{78575}Ne mislim tako.
{78585}{78658}Nije da to još|uvijek èinim.
{78659}{78743}Znam. Žao mi je.
{78744}{78810}Ne želim išta|skrivati od tebe.
{78811}{78911}Ne želiš li da budem|iskren? -Želim.
{78934}{79014}Caveh, pomirimo se.
{79285}{79392}Nekoliko tjedana poslije,|bio mi je roðendan.
{79402}{79529}I nagovorio sam je da uzme ecstasy|sa mnom, kako bi proslavili.
{79602}{79706}Okej.|-Hvala ti.
{79767}{79886}Te noæi, bili smo bliskiji|nego ijednu prije.
{79887}{80025}Ali ecstasy nije samo ljubavni serum,|on je i serum istine.
{80026}{80084}Toliko te volim
{80085}{80133}I ja tebe.
{80134}{80218}Voliš me?|-Da.
{80288}{80396}Ne želim da postoji|ikakva tajna meðu nama.
{80422}{80492}Caveh, ne želim.
{80532}{80589}Niti ja.
{80590}{80671}Mogu li te nešto pitati?|-Da.
{80672}{80757}Reæi æeš mi istinu?|-Da.
{80763}{80921}Postoji nešto što mi|do sada nisi rekao?
{80935}{80987}Mogu to podnijeti.
{80988}{81063}Da, postoji nešto.|-Što?
{81064}{81157}Èekao sam da ti kažem,|ali sam se bojao.
{81158}{81300}Caveh, možeš mi reæi.|-Okej.
{81321}{81424}Ponekad, kad vodimo ljubav...|-Da?
{81425}{81517}...maštam o drugim ženama.
{81618}{81692}Christu je uništilo moje priznanje.
{81693}{81805}Postala je hipersenzitivna|na druge žene.
{81842}{81926}Opazila bi ih i|prije nego bih ja.
{81927}{82050}Odmah bi tražila na mojem licu|znak da se zanimam za njih.
{82051}{82160}Postalo je neprijatno tijekom vremena.|Pa sam pokušao to nadiæi.
{82161}{82208}Poprilièno je seksi.
{82209}{82290}Više je tvoj tip|od mene, je li?
{82291}{82369}O èemu govoriš?
{82513}{82622}Jednog dana bio sam na|putu da ruèam s Christom
{82623}{82719}kad sam odluèio da stanem|i natoèim gorivo u auto.
{82931}{83014}Bilo je neèega u njezinom|položaju
{83015}{83090}što me napalilo.
{83379}{83440}Oprosti što kasnim.|-Caveh, èekala sam te.
{83441}{83527}Znam, oprosti.|Imao sam malu masturbacijsku epizodu.
{83528}{83589}Što?
{83614}{83678}Stao sam natoèiti gorivo i...
{83679}{83754}Jesi li rekao,|"malu masturbacijsku epizodu"?
{83755}{83804}Da, stao sam natoèiti gorivo,
{83805}{83909}tamo je bila žena koja se nagnula|da bi natoèila gorivo u svoj auto...
{83910}{83979}bila je stvarno seksi
{83980}{84134}i jako me napalio naèin na|koji je bila nagnuta
{84135}{84288}i otišao sam do stana|kako bih mogao masturbirati.
{84289}{84374}Ali nije ništa strašno.|Samo da znaš.
{84375}{84435}Ja sam...
{84621}{84676}Ne želim razgovarati o tome.|-O istini?
{84677}{84775}Ne želim je slušati svaki dan?|-Ne želiš li istinu?
{84776}{84843}Znam da se te stvari dogaðaju,|Caveh.
{84844}{84922}Znam. I razumijem te.
{84923}{84999}I vjeruj mi, bilo bi puno|bolje za nas, da ne znam.
{85000}{85067}Nemoj mi to govoriti.
{85077}{85163}Ne želim to èuti.|-Dobro.
{85164}{85234}Nemoj mi govoriti.
{85268}{85410}Jedne veèrei|gledao sam vijesti...
{85411}{85516}Istražitelji kavu|da su pronašli sedam javnih kuæa
{85517}{85579}pod krinkom|salona za masažu.
{85580}{85684}Policija kaže da uhiæenja|samo vrh ledenog brijega
{85685}{85814}i da mnogi saloni za masažu|ustvari pružaju seksualne usluge.
{85815}{85941}Ja sam Maya Ellington, za|vijesti Kanala 3.
{86322}{86362}Želite masažu?
{86363}{86395}Um...
{86396}{86461}Da.
{86462}{86517}Koliko?
{86518}{86601}40 dolara za pola sata.
{86602}{86647}Um...
{86648}{86711}To ukljuèuje sve?
{86712}{86785}To ukljuèuje pola sata.
{86786}{86832}Um...
{86833}{86926}Tko masira?|-Razlièite djevojke.
{86927}{87005}Vi ste jedna od njih?|-Ne.
{87006}{87048}Um...
{87049}{87104}Mogu li ih vidjeti?
{87105}{87203}Ne. Prvo morate platiti.
{87259}{87324}Odlazite odavde!
{87325}{87371}Žao mi je.|-Odlazite odavde!
{87372}{87403}Žao mi je.
{87404}{87536}Odlazite!
{87582}{87694}Posjetio sam svaki salon za|masažu u Los Angelesu.
{87769}{87829}Ispoèetka, napaljivalo me,
{87830}{87962}samo da zgrabim recepcionarku|za grudi i pobjegnem.
{87966}{88106}Ali nakon nekog vremena, niti|to više nije bilo dovoljno uzbuðujuæe.
{88151}{88282}Onda sam jednog dana|dobio ideju.
{88511}{88638}Možda je razlog što nisam mogao|suzbiti svoj fetiš prema prostitutkama
{88639}{88737}je taj što niti jednom nisam s nekom|od njih išao do kraja.
{88738}{88780}Kako to misliš?
{88781}{88855}Greg mi je tada bio|najbolji prijatelj.
{88856}{89010}Upoznali smo se na UCLA-u i zajedno|snimili nekoliko studentskih filmova.
{89011}{89142}Mislim, niti s jednom nisam radio|ono o èemu maštam.
{89143}{89187}O èemu?
{89188}{89248}O nasilnim stvarima.
{89249}{89361}U maštarijama ugrabim|je za kosu
{89362}{89482}i tjeram je da govori|"želim ti pušiti kurac"
{89483}{89571}vièem joj kurvo i droljo
{89572}{89691}i poènem je jako jebati|u usta, da se zagrcne i svašta.
{89692}{89731}Zanimljivo.
{89732}{89810}Ali u stvarnom životu,|to nikad nisam uèinio.
{89811}{89867}Zašto ne?
{89868}{89957}Jer im se|želim svidjeti.
{89958}{90010}Kužim.
{90011}{90136}Mislim da ako po posljednji puta|s prostitutkom
{90137}{90246}uèinim sve iz|svojih maštarija,
{90247}{90394}možda æe mi sve to|konaèno izaæi iz glave.
{90395}{90481}Hoæe li ti dopustiti|da im to uèiniš?
{90482}{90519}Um...
{90520}{90603}Pretpostavljam.
{90622}{90707}Vrijedi pokušati.
{90750}{90796}Da, zar ne?
{90797}{90870}Da, pokušaj.
{90871}{90964}Ali nisam to mogao uèiniti,|a da Christa ne zna za to.
{90965}{91086}Mislim, moram joj reæi, zar ne?
{91095}{91138}Ozbiljan si?
{91139}{91221}Christa, ne mogu potiskivati svoju|požudu. Nije zdravo.
{91222}{91283}Što želiš da uèinim?|Kažem da je u redu?
{91284}{91331}Da.|-E pa nije!
{91332}{91419}Ako se budeš seksao sa prostitutkom,|meðu nama je gotovo!
{91420}{91517}Christa, pokušaj me razumjeti.|Moram to uèiniti.
{91518}{91601}Ne mogu vjerovati da želiš|žrtvovati našu vezu
{91602}{91680}samo da bi ispunio neku|glupu maštariju!
{91681}{91742}Ne želim žrtvovati|našu vezu.
{91743}{91828}Želim to uèiniti kako|bi je ojaèao.
{91896}{92004}Christa, ovo nije konstruktivno.
{92048}{92149}Posljednje što sam želio|je da izgubim Christu,
{92150}{92233}stoga sam odluèio|potražiti profesionalnu pomoæ.
{92234}{92397}Moja majka je imala strah|od mijenjanja pelena.
{92398}{92592}Osjeæala je odbojnost prema,|znate, pelenama.
{92593}{92677}Sjeæate li se nekog|skorašnjeg sna?
{92678}{92737}Um...
{92738}{92900}Imam san u kojem|sjedim na školjki,
{92901}{92996}postajem sve|manji i manji,
{92997}{93074}i onda upadnem u nju.
{93166}{93219}Trebam te, mamice!
{93220}{93296}Jaèe!|-Trebam te, mamice!
{93297}{93367}Glasnije!|-Trebam te, mamice!
{93368}{93429}Tako je!|-Trebam te, mamice!
{93430}{93497}Tako je!|-Trebam te, mamice!
{93498}{93594}Jaèe!|-Trebam te, mamice!
{93595}{93690}Ali nijedan mi nije|uspio pomoæi.
{93705}{93813}Napokon, nakon tjedana|odgaðanja,
{93814}{93909}odluèio sam to uèiniti.
{93910}{94010}Èak i ako izgubim Christu.
{94264}{94329}Skini odjeæu.
{94336}{94378}Puši mi.
{94379}{94440}Daš mi novac?
{94441}{94503}Oh, da.
{94505}{94583}20 sada,
{94584}{94691}20 poslije, ako uèiniš|sve što ti kažem.
{94754}{94836}Na stojeæki.
{94958}{95033}Da.
{95110}{95165}Da.
{95166}{95236}Oh, èekaj. Reci,|"želim ti pušiti kurac".
{95237}{95376}Ne, èekaj.|Prvo reci, "želim ti pušiti kurac".
{95386}{95509}Ne govorim|vrlo dobro engleski.
{95526}{95706}Reci, "želim ti pušiti|kurac".
{95736}{95814}Ne razumjeti.
{95834}{95904}Reci "Ja...
{95905}{96030}Ne, èekaj... "Ja...
{96031}{96141}Reci, "Ja...|"Ja..."
{96142}{96196}"Ja...", reci, "Ja...",
{96197}{96285}"Ja". Reci, "ja...
{96286}{96464}Èinjenica što nije uopæe razmumjela što|želim da mi kaže, umanjila je sav užitak.
{96465}{96585}Okej, samo ga popuši.
{96726}{96807}Oh, da.
{96808}{96929}Puši ga. Da, kurvo.
{96930}{97015}Da, puši ga, droljo.
{97016}{97081}Da.
{97153}{97281}Sviða ti se, zar ne?|Ti mala kurvo.
{97377}{97440}Prièekaj.
{97441}{97473}Um...
{97474}{97528}Stani tamo.
{97529}{97642}Tamo.
{98183}{98306}Poslije, nešto|èudesno se dogodilo.
{98307}{98403}Potapšala me po guzici|i rekla mi...
{98404}{98470}Doði opet.
{98604}{98734}Odmah sam izgubio onaj|osjeæaj zbog kojeg sam prije osjeæao sram,
{98735}{98871}a u tome je još više pomoglo što mi se|nasmiješila sa tolikim razumijevanjem.
{98872}{98973}Osjeæao sam da sam doživio|misteriozno iskustvo,
{98974}{99079}te da se nešto u meni|konaèno promijenilo.
{99117}{99185}Te noæi, otišao sam|do Christe
{99186}{99284}da bih joj rekao da sam|spreman na pravu vezu.
{99285}{99395}Što želiš?|-Želim da opet budemo zajedno.
{99448}{99559}Christa je razumljivo bila skeptièna|prema mojoj promjeni...
{99686}{99845}...ali napokon sam je uspio uvjeriti|da sam se konaèno izlijeèio.
{99890}{99961}U ovom trenutku filma,
{99962}{100074}trebala bi biti scena u kojoj mi|Christa puši.
{100075}{100147}Ne zapravo, samo|se pravimo.
{100148}{100306}Ali glumica koja glumi Christu|odbila je takvu scenu.
{100310}{100466}Osjeæaš li se manje važnom ili|nekakva ženska stvar?
{100467}{100644}Ne, samo se u takvoj sceni|ne bih osjeæala ugodno.
{100645}{100694}Možeš li ipak to uèiniti?
{100695}{100731}Ne.
{100732}{100839}Ako bi mogli zamisliti da|mi ga ona puši,
{100840}{100954}recimo ovako|dugo...
{100983}{101080}Seks bi postao|savim drugaèiji.
{101081}{101171}Umjesto da maštam|da je Christa neka nepoznata žena,
{101172}{101294}želio sam pokušati zamisliti|ono što je stvarnost.
{101295}{101358}I bilo je odlièno.
{101359}{101445}Gotovo sam osjetio|njezinu ljubav.
{101446}{101525}Nisam mogao vjerovati da me ijedno|ljudsko biæe može voljeti,
{101568}{101634}da želi uzeti moj penis,
{101635}{101730}koji sam uvijek smatrao|ružnim i prljavim.
{101731}{101784}staviti si ga u usta,
{101785}{101893}ili da želi progutati|moju spermu.
{102071}{102121}Hej, dušo.|Bok.
{102122}{102227}Nedostajala si mi.|Kako je?
{102228}{102275}Dobro.
{102276}{102346}Što nije u redu?
{102416}{102531}Nešto ti moram priznati.
{102532}{102592}Što?
{102638}{102745}Sjeæaš se da sam ti rekla da veèeras|idem sa Robby pogledati film?
{102746}{102811}Da.
{102868}{102932}Pa...
{102968}{103041}Poslije...
{103087}{103208}Nisam si mogla pomoæi i|poèeli smo se maziti.
{103209}{103287}Kako to misliš, nisi si|mogla pomoæi?
{103288}{103411}Ne znam. Samo se dogodilo.|Nisam to planirala.
{103441}{103526}Kako to misliš "mazili ste se"?
{103535}{103623}Ljubili smo se i takve stvari.
{103641}{103725}Kako to misliš "takve stvari"?
{103746}{103846}Malo smo se glupirali.
{103905}{103976}Što se onda dogodilo?
{103996}{104081}Trebala bih ga sresti sutra|naveèer na veèeri.
{104082}{104221}Ali otiæi æu mu reæi da sam pogriješila i|da se ne možemo viðati u tom smislu.
{104254}{104350}Caveh, žao mi je.
{104500}{104676}Osjeæao sam se strašno ljubomornim,|ali pokušavao sam suzbiti osjeæaje.
{104713}{104819}Ne mogu to uèiniti.|Osjeæam se kao da ljubim Robbyja.
{104820}{104926}Kao da osjeæam njegovu|slinu u tvojim ustima.
{104936}{105056}Kako misliš da je meni bilo|kad si se seksao sa prostitutkama?
{105149}{105199}Mogao sam je shvatiti,
{105200}{105303}te sam znao da joj nemam što predbacivati,|nakon svega što sam joj priredio.
{105304}{105405}Ali nisam si mogao pomoæi.
{105427}{105494}Te noæi, nazvao sam Robbyja|u 3 sata ujutro
{105495}{105616}i zamolio ga da mi uèini osobnu uslugu i|da se prestane muvati sa Christom.
{105617}{105684}I on se složio.
{105685}{105782}Hvala, Robby.|Cijenim to.
{105783}{105893}Ali lagao je.|Èinili su to iduæu veèer.
{105894}{106001}Obeæala si da neæeš.|-Znam. Žao mi je.
{106002}{106066}Šta si mislila, Christa?
{106067}{106174}Ne znam.|Nisam si mogla pomoæi.
{106197}{106276}Poèela je zvuèati poput mene.
{106277}{106363}Christa je nastavila|provoditi vrijeme sa Robbyjem.
{106364}{106425}A ja sam postajao sve|više ljubomoran.
{106426}{106481}Sve više sam je trebao i
{106482}{106568}bio sam sve nesigurniji.
{106581}{106672}Pa smo krenuli na|nekoliko terapija.
{106673}{106796}Dakle, Caveh,|o èemu trenutno razmišljaš?
{106965}{107079}Da mi se sviðate.
{107184}{107311}U meðuvremenu, naše svaðe|izmicale su kontroli.
{107374}{107552}I prije nego sam se snašao, moja potreba|za seksom sa prostitutkama se vratila.
{107716}{107783}Koliko?|-Što želiš?
{107784}{107880}Koliko za pušenje?|-50 dolara.
{107881}{107956}Razmisliti æu.
{108161}{108289}Nakon te noæi, vozikao|sam se tako svakodnevno.
{108290}{108369}Ponekad to jutra.
{108434}{108479}I tada sam upoznao Devin.
{108480}{108540}Austin, Texas
{108541}{108585}Jebiga.
{108586}{108668}Pozvalo me|društvo Austin Film
{108669}{108766}da bi prikazali film|koji smo Greg i ja zajedno napravili.
{108780}{108840}Devin je bila jedna od|organizatorica.
{108841}{108895}Hej.
{108909}{109009}Te noæi smo|se zajedno napušili.
{109010}{109125}Odjednom me poèela|strašno privlaèiti.
{109313}{109471}Mog posljednjeg dana u Austinu|odluèili smo zajedno pojesti mušmule.
{110104}{110246}Vrijeme sa Devin je jedno od najmistiènijeg|koje sam imao u životu.
{110300}{110373}Osjeæao sam kao da|se potpuno razumijemo.
{110374}{110463}Kako nisam mogao niti zamisliti|da dvoje ljudi može.
{110900}{111041}Nakon što smo došli k sebi,|isprièao sam joj o mojoj vezi sa Christom.
{111042}{111129}Kladim se, da se upravo|sada jebe sa Robbyjem.
{111130}{111214}Caveh, lud si.|-Zašto?
{111215}{111361}Trebao bi biti sretan zbog nje.|Nadati se da ima dobar seks.
{111362}{111445}Znaš, trebao bih.
{111446}{111518}Ja èak niti ne|vjerujem u monogamiju.
{111519}{111628}Jebeš ga, niti ja.
{111657}{111734}Èinilo mi se kao da sam konaèno|pronašao srodnu dušu
{111735}{111804}koju sam tražio cijeli svoj život.
{111805}{111869}Što to radiš?
{111870}{111953}Ovdje je ta osoba,|zove se Caveh.
{111954}{112053}On je stvaran.|On postoji.
{112056}{112144}Misliš na mene?|-Da, na tebe.
{112145}{112300}Koliko god je èasno do tebe da|žrtvuješ svoje potrebe zbog nje,
{112301}{112415}trebaš biti iskren i prema sebi,|jer i ti si stvaran.
{112416}{112523}Ali problem je što ne mogu|zamisliti da joj nanesem bol.
{112524}{112638}Nanosiš joj bol i više ako produžavaš|vezu koja ne funkcionira
{112639}{112704}nego da je prekineš odmah.
{112705}{112791}Ali i bojim se.
{112792}{112927}Bojim se da æu biti usamljen|i napaljen
{112928}{113042}i oèajan.
{113043}{113098}Mrzim to.
{113099}{113199}To mi se ne èini dobrim razlogom|da bi ostao s njom.
{113200}{113291}Imaš pravo.
{113379}{113441}Složio sam se sa svim|što je rekla...
{113442}{113539}ali sam se pitao, da li bi Devin|mogla prihvatiti moj fetiš
{113540}{113618}išta bolje od Christe.
{113629}{113735}Ali Christa se stvarno trudi.|Mislim, i ja sam stvarno sjeban.
{113736}{113892}Na primjer,|imam fetiš prema prostitutkama.
{113893}{114038}Nije jebeno važno.|Svatko ima takve stvari.
{114039}{114099}Kad je Devin izrekla|te rijeèi,
{114100}{114253}pomislio sam da nije problem|moj fetiš
{114254}{114344}veæ je Christa moj problem.
{114755}{114809}Na putu natrag u Los Angeles
{114810}{114923}odluèio sam|da æu prekinuti s Christom.
{114958}{115074}Bili smo zajedno 3 godine.
{115085}{115157}Ovo je stvarna Christa.
{115158}{115299}Prvih godina poslije prekida,|nismo bili u najboljim odnosima.
{115300}{115379}Ali sada su se stvari popravile.
{115380}{115507}Udala se i nedavno|rodila dijete.
{115718}{115842}Nakon prekida,|nisam mogao prestati misliti na Devin.
{115876}{115990}Slijedeæih mjesec dana,|pisao sam joj svaki dan.
{116017}{116123}I kad sam primio poziv|dva Europska filmska festivala,
{116124}{116213}pozvao sam Devin da|poðe sa mnom.
{116345}{116466}Naših prvih nekoliko dana|zajedno su bili idilièni.
{116523}{116618}Ali tada su se stvari zakomplicirale.
{116845}{116895}Mislim da joj se sviðaš.
{116896}{116975}Misliš?|Definitivno.
{116976}{117084}Ne znam. Nije moj tip.|Nije dovoljno droljasta.
{117085}{117152}Da, baš.
{117312}{117466}Ako želiš posjetiti koju prostitutku dok|smo u Europi, uèini to slobodno.
{117467}{117554}Možeš otiæi i|reæi, "Hej, Devin, vidimo se".
{117555}{117642}Otiði i obavi to.
{117684}{117764}Razmišljao sam o onome|što si rekla ranije,
{117765}{117945}te ti želim reæi da ja doista želim|izbaciti taj svoj fetiš iz sebe.
{117946}{117993}Znaš, doista želim.
{117994}{118067}Ali palo mi je na pamet,
{118068}{118169}ako bi me gledala dok|se seksam sa nekim drugim,
{118170}{118249}možda bi me to|definitivno izlijeèilo.
{118483}{118593}Caveh, voljela bih to.
{118594}{118657}Doista?
{118673}{118750}Da.
{118751}{118875}Mislim da je puno toga|povezano sa sramom,
{118876}{118975}pa kad bi me ti gledala,
{118976}{119061}osjeæao bih se kao da|nešto èinimo zajedno.
{119062}{119213}I onda bi mi to pomoglo da|izbrišem sav sram zbog toga,
{119214}{119369}te da više ne bih osjeæao potrebu|da to èinim.
{119370}{119435}Slijedeæeg dana, unajmili smo auto
{119436}{119562}i odvezli se do Milana da pogledamo|Leonardo da Vincijevu "Posljednju veèeru".
{119599}{119663}Hej, prostitutka!
{119692}{119759}Želiš da stanem i da|je bolje pogledaš?
{119760}{119840}Ne znam.
{119898}{119958}Ako nemaš ništa protiv.
{119959}{120050}Ne, samo navali.
{120805}{120865}Što misliš?
{120866}{120931}Želiš gledati?
{120932}{121061}Ako ti je to stvarno|tako važno, hoæu.
{121076}{121130}Hvala, Devin.
{121131}{121210}Cijenim to.
{121614}{121677}Ne želi da nas gledaš.
{121678}{121764}Što želiš uèiniti?
{121794}{121859}Ne znam.
{121954}{121999}Zaboravimo.
{122000}{122061}Okej.
{122643}{122778}Našeg posljednjeg dana u Italiji,|opet sam vidio djevojku sa šetališta.
{123012}{123168}Zvala se Paola i ispalo je da|je ona glumica u usponu.
{123174}{123300}Pogledala je moj film i|svidio joj se.
{123401}{123498}Hej.
{123499}{123594}Kako ide?|-Super. Dala mi je svoje cipele.
{123595}{123631}Ma nemoj. Kul.
{123632}{123692}Da, gledala je moj film.|Poljubili smo se.
{123693}{123762}Poljubili?|Sretnièe.
{123763}{123836}Poljubac nije bio ništa posebno.|Nije poput tvojih.
{123837}{123903}Ohh.
{123905}{123987}Primijetio si kako sam ja nastavila|dalje
{123988}{124049}kad si ti odluèio|malo bolje je pogledati?
{124050}{124095}Ne, mislim da nisam.
{124096}{124156}Samo to želim istaknuti
{124157}{124218}jer mislim da mnoge djevojke|to ne bi uèinile,
{124219}{124285}samo otišle dalje i pustile|deèka da obavi svoje.
{124286}{124350}Mislim da si u pravu.
{124351}{124493}Samo želim malo zahvalnosti,|jer veæina djevojaka ti
{124494}{124555}ne bi to olako dopustile.
{124556}{124602}Istina.|Hvala, Devin.
{124603}{124688}Da, baš.|-Ne, doista to cijenim.
{124689}{124739}Da.
{124740}{124808}Uèini mi uslugu.|-Što?
{124809}{124852}Samo jednu.|-Okej.
{124853}{124955}Nemoj je jebati u našem|krevetu, ok?
{124978}{125036}Okej.
{125043}{125111}Iznenadio sam se da|joj je stalo,
{125112}{125235}ali odluèio sam da|se ne obazirem.
{125289}{125424}Paola me pozvala na piæe|sa prijateljima.
{125430}{125505}Pitao sam Devin|ako želi poæi i ona,
{125506}{125599}potajice se nadajuæi se da æe odbiti.
{125610}{125687}Ali nije odbila.
{125700}{125773}Nisam se mogao odluèiti|kamo da sjednem
{125774}{125933}želio sam sjesti pored Paole,|ali osjeæao sam da moram pored Devin.
{125954}{126039}Odluèio sam se na kompromis,|neæu sjesti niti pored jedne,
{126040}{126113}tako održavajuæi odstojanje|od obje,
{126114}{126234}kao Isus u Da Vincijevoj|"Posljednjoj veèeri".
{126593}{126689}Idem natrag u hotel|vidimo se poslije.
{126690}{126744}Ne želiš na plivanje?
{126745}{126876}Ne. Zašto ne odeš|sa svojim prijateljima Talijanima.
{126881}{126957}Radije bih išao|sa tobom.
{126958}{127078}Ne, idi s njom.|Vidimo se.
{127571}{127623}Sigurno ne želiš|plivati gola?
{127624}{127696}Sigurna sam.
{127697}{127746}Bilo bi zabavno.
{127747}{127836}Ne.|-Doista.
{128012}{128064}Sigurno ne želiš|spavati sa mnom?
{128065}{128173}Da, sigurna sam.|Ali možda, kad bi došao u Torino.
{128174}{128224}Super, do tada æu|vjerovatno biti starac.
{128225}{128304}Pisati æu ti.
{128318}{128368}Okej.
{128369}{128498}Ako ikada zatrebaš nekoga|da glumi u tvom filmu,
{128499}{128549}samo me nazovi.
{128550}{128621}To je bila reèenica, zbog|koje sam se mrzio.
{128622}{128662}Okej.
{128663}{128775}Osjeæao sam se poput|ljigavog holivudskog redatelja.
{128912}{129048}Na putu kuæi, imao sam|viziju svoje buduænosti, noænu moru.
{129049}{129222}Vidio sam se 20 godina starijeg,|još uvijek samac.
{129282}{129452}Kad sam stigao do hotela,|osjeæao sam se prazno i depresivno.
{129461}{129622}Jedino što sam želio je leæi|u krevet uz Devin.
{129946}{130013}Devin!
{130085}{130162}Devin!
{130481}{130567}Jesi li je pojebao?|-Nisam.
{130568}{130636}Zašto nisi?|Željela te je.
{130637}{130720}Ne dovoljno.
{130726}{130807}Ja sam se skoro pojebala.
{130808}{130864}S kim?
{130865}{130930}Nekim tipom kojeg|sam srela u baru.
{130931}{130988}Ovdje.
{130989}{131054}Oprosti.
{131072}{131137}Osjeæao sam se ljubomoran|i nesiguran.
{131138}{131212}Ali želio sam vjerovati da|Devin i ja imamo nešto posebno
{131213}{131334}da smo dio nekog genijalnog eksperimenta|u suzbijanju osjeæaja.
{131387}{131495}Slijedeæeg dana|letjeli smo za Munchen.
{131534}{131637}Imam takvu jebenu glavobolju.
{131644}{131756}Oprostite, mogu|li dobiti viski?
{131757}{131835}Jedan viski?|-Da.
{131882}{132022}Nemaš li glavobolju?|-Imam. Zato i trebam piæe.
{132023}{132072}Misliš da je to pametno?
{132073}{132180}Samo æe tako prestati.
{132210}{132320}Istina.|Znam što radim.
{132354}{132415}Okej.
{132431}{132544}Ali to mi je zadnje|piæe. Obeæavam.
{132765}{132810}Obeæala si da više|neæeš piti.
{132811}{132932}Tip mi je nastavljao plaæati pivo.|Nisam ga mogla odbiti.
{132933}{133022}Zašto ne?|-Besplatno pivo, èovjeèe.
{133023}{133158}Poèeo sam shvaæati da|Devin ima problem sa alkoholom.
{133159}{133205}Trebao bih objasniti
{133206}{133353}da glumica koja glumi Devin ima|problem sa piæem i u stvarnom životu.
{133702}{133786}Razlog i rješenje za sve|životne probleme.
{133787}{133878}Ali vratimo se natrag|na prièu...
{133917}{134028}Devin, prestani.|Rekla si da ti je zadnje.
{134031}{134153}Što ne odeš pojebati prostitutku|i ostaviš me na miru?
{134162}{134316}Devin, o èemu govoriš?|Rekla si da æeš prestati piti!
{134317}{134398}Izgleda da sam se predomislila.
{134413}{134521}Devin, mislim da si|popila dovoljno.
{134523}{134628}Smiješno, Caveh,|ja mislim da nisam.
{134761}{134807}Jebiga!
{134808}{134910}Jebeni kretenu!|To sranje je skupo!
{135121}{135206}Poèela mi je nedostajati|Christa!
{135305}{135414}Te noæi, razgovarao sam sa|svakom prostitutkom u Munchenu.
{135415}{135470}Um...
{135551}{135588}Blasen?
{135589}{135702}Blasen?|-Blasen. Ja. Blasen.
{135837}{135996}Nakon razgovora sa uliènim prostitutkama,|obišao sam bordele.
{136665}{136796}Pronašao sam jednu prostitutku|koja me posebno napalila.
{137004}{137079}Umirao sam od želje|da se seksam s njom
{137080}{137176}ali uspio sam se oduprijeti.
{137191}{137250}I vratio sam se u hotel,
{137251}{137400}uzbuðen da kažem Devin kako|sam se uspješno suzdržao.
{137520}{137623}Iduæeg dana, organizatori|filmskog festivala
{137624}{137743}inzistirali su da platimo 300 dolara|za štetu u hotelskoj sobi
{137744}{137855}i da napustimo grad odmah|nakon prikazivanja mog filma.
{137926}{138129}Neæu popiti ništa vrlo dugo,|to ti mogu obeæati.
{138173}{138242}Drago mi je.
{138370}{138498}Devin je imala gadnu glavobolju|i prespavala je cijelo popodne.
{138507}{138645}Bio je naš posljednji dan u Munchenu, pa|sam odluèio otiæi na striptiz.
{139011}{139081}Živio.
{139095}{139176}Jebi se, Devin.
{139455}{139533}Kamo si otišao?
{139534}{139591}Idem da mi popuše.
{139592}{139691}Okej. Idem s tobom.
{139723}{139771}Ne želim to.
{139772}{139852}Zašto ne? Mislila sam|da želiš da gledam.
{139853}{139975}Nisi li želio da tvoja djevojka to gleda, kako|bi osjetio da je to "normalno".
{139976}{140043}Trenutno se ljutim na tebe.
{140044}{140173}Ovo ti je velika šansa.
{141254}{141346}Govoriš engleski?|-Da.
{141347}{141378}Bok.
{141379}{141457}Tražim ženu koja je ovdje|bila sinoæ.
{141458}{141512}Imala je crnu kosu.|Da li je ovdje?
{141513}{141655}Biti æe zaposlena još sat vremena.|Možda ti ja mogu pomoæi.
{141656}{141706}Um...
{141707}{141767}Nadao sam se vidjeti nju.
{141768}{141812}Ja sam jako dobra.
{141813}{141943}Siguran sam,|ali moram razmisliti.
{141944}{142008}Okej.
{142107}{142177}Ne vidim onu zbog|koje sam došao.
{142178}{142309}Zašto ne daš da ti popuši|neka od ovih?
{142314}{142396}Jer mi se ona|više sviðala.
{142397}{142460}- Pa, ako nje nema...|-Ovdje je.
{142461}{142558}Rekli su mi da je sa mušterijom.|Biti æe gotova za sat vremena.
{142559}{142702}Sat?|Èekati æemo cijeli sat?
{142752}{142825}Trebam još jedno piæe.
{142826}{142933}Devin, ne možemo si|to priuštiti.
{142934}{143009}Kako to misliš?
{143010}{143116}Doveo si curu u bordel i ne želiš|joj niti platiti piæe?
{143117}{143219}Devin, ostalo nam je samo 200 maraka.|Jedva da imam dosta da platim pušenje.
{143220}{143281}Nije dovoljno i za piæe|i za pušenje.
{143282}{143358}Jebi se, Caveh.|Želim piæe.
{143359}{143457}Devin, nisi popila ni|ovo što imaš.
{143538}{143610}Sada sam popila.
{143896}{143955}Evo ti.
{143965}{144014}Hvala.
{144015}{144136}Oprostite. Žena koju|želite, sada je slobodna.
{144137}{144202}Slijedi me.
{144427}{144553}Žao mi je, tražio sam drugu|ženu sa crnom kosom.
{144554}{144691}Bila je ovdje sinoæ.|-Veèeras je nema.
{144786}{144876}To nije ona.|-Kako to misliš?
{144877}{144935}Ona koju ja želim veèeras|nije ovdje.
{144936}{145051}Èekali smo jebeni sat, a|ona nije ovdje?
{145071}{145133}Da.
{145143}{145241}Što æemo?|Da odemo?
{145290}{145364}Nisam siguran.
{145365}{145432}Ne mogu se odluèiti.
{145433}{145530}Zašto ne pojebeš neku|od ovih?
{145531}{145599}Ne znam.|Želio sam onu.
{145600}{145703}Nijedna od ovih me|ne privlaèi toliko.
{145704}{145828}Došli smo ovamo.|Možeš bar to uèiniti.
{145971}{146065}Želiš otiæi gore sa mnom?
{146066}{146160}Možda, nisam siguran.
{146161}{146242}Mogu ti priuštiti|veliko zadovoljstvo.
{146243}{146332}Siguran sam.
{146449}{146511}Spreman si?
{146512}{146603}Ne znam.|Ne mogu se odluèiti.
{146604}{146659}Možda da ti pomognem,|da se odluèiš.
{146660}{146696}Um...
{146697}{146819}Što misliš?|-Primamljujuæe.
{146863}{146901}Kamo æeš?
{146902}{146997}Ne brini za nju.|Biti æe ona dobro.
{146998}{147127}Kamo one dvije idu?|-Neæe je ozlijediti.
{147132}{147242}Žao mi je.|Moram poæi.
{147708}{147793}Jebi se, Caveh!|Jebi se!
{147794}{147871}Devin, smiri se.|-Jebi se!
{147872}{147910}Što ti je rekla?
{147911}{148008}Bila je zabrinuta za mene,|za razliku od tebe!
{148009}{148093}Rekla je, "Doði sa mnom|i pobrinuti æu se za tebe
{148094}{148178}i pomoæi ti da se|osjeæaš bolje."
{148188}{148242}Mislila je na seks?
{148243}{148348}Samo na to misliš, zar ne?
{148349}{148399}Da li je to mislila?
{148400}{148448}Izlazim!
{148449}{148556}Devin, èekaj!|Prestani! Zatvori vrata!
{148802}{148947}Nakon povratka u hotel, Devin je|inzistirala da mi ga popuši.
{148948}{149106}Rekoh joj da ne želim,|ali me polegla na krevet.
{149117}{149248}Cijelo vrijeme sam se bojao|da æe mi odgristi penis.
{149336}{149448}Slijedeæeg jutra, odletjeli|smo za New York.
{149767}{149828}Koliko?
{150382}{150470}Da ti ga stavim.
{150510}{150559}Na koljena.
{150560}{150652}Neæu na jebena koljena, dolje|je polupano staklo.
{150653}{150728}Oh, oprosti.
{151215}{151351}Slijedeæeg dana,|krenuli smo razlièitim putevima.
{151378}{151516}Želio sam reæi, "volim te",|ali nisam mogao.
{151522}{151706}Ali kako sam se približavao vratima,|osjeæao sam da želim to reæi.
{151729}{151812}Ali bilo je prekasno.
{151894}{151957}Ovo je prava Devin.
{151958}{152035}Ostali smo prijatelji kroz|sve ove godine
{152036}{152182}i pojavila se u mom filmu|"Više ne mrzim Las Vegas".
{152183}{152288}Ali tada su joj veæ|dijagnosticirali rak
{152289}{152428}i upravo je prolazila kroz|kemoterapiju.
{152433}{152524}Umrla je tri godine poslije.
{152784}{152936}Na putu kuæi, osjeæao sam|kao da mi nešto nedostaje.
{152945}{152999}Od trena kad sam|upoznao Devin
{153000}{153076}vjerovao sam da sam|napokon upoznao osobu
{153077}{153160}koja me može prihvatiti|onakvog kakav jesam.
{153212}{153338}Ali sada sam shvatio da sam|bio u krivu.
{153375}{153506}Jednom sam negdje proèitao da,|svi koji uðu u naše živote,
{153507}{153624}samo su ogledalo onoga u nama|što ne možemo vidjeti.
{153625}{153680}Pa sam se upitao,
{153681}{153843}kako bi Devin mogla biti ogledalo neèega|u meni što ne mogu vidjeti.
{153844}{153927}Isprva to nisam mogao shvatiti.
{153928}{154076}Devin je bila alkoholièarka.|Ja nisam bio.
{154079}{154211}Ali odjednom mi je sinulo,|da nisam bio ovisnik o alkoholu,
{154212}{154355}ali sam bio ovisnik o seksu.
{154571}{154618}Caveh?|-Da, bok.
{154619}{154661}Bok.
{154662}{154760}U Los Angelesu sam|posjetio terapeuta
{154761}{154891}koji me uputio na sastanak|Društva ovisnika o seksu.
{156080}{156219}Pregledao sam lica ostalih ljudi u sobi,|tražeæi nekakav znak perverzije,
{156220}{156308}ali izgledali su poput svih ostalih.
{156396}{156463}Dobra veèer, moje ime je Ken.
{156464}{156532}Ja sam|ovisnik o seksu.
{156533}{156584}Bok, Ken.
{156585}{156729}Dobrodošli na sastanak ponedjeljkom,|na kojem su samo muškarci.
{156730}{156790}Ovo je zatvoreni sastanak.
{156791}{156902}Samo za one koji žele|apstinirati od seksa.
{156903}{156959}U našem društvu, apstinencija
{156960}{157065}ne znaèi kompletno izbacivanje|seksualnosi iz svakodnevnog života,
{157066}{157153}samo onog kompulzivnog|seksualnog ponašanja
{157154}{157268}koje dovodi to inkomprehizivnog|demoraliziranja.
{157269}{157317}Prepuštamo vama individualno da
{157318}{157411}odluèite kojeg se to dijela svog|seksualnog ponašanja želite odreæi.
{157412}{157467}Rekao sam da sam|ovisnik o seksu.
{157468}{157575}Ima li još netko takav?
{157667}{157758}Moje ima je Sasha, ja sam|ovisnik o seksu.
{157759}{157798}Bok, Sasha.
{157799}{157918}Prošlog tjedna konaèno sam sve svoje|porniæe strpao u smeæe
{157919}{158028}i osjeæam se slobodno, jer veæ|sam se smuèio samom sebi.
{158029}{158108}Razmišljam o svim onim stotinama|i tisuæama sati
{158109}{158217}koje sam proveo|kružeæi svojim autom...
{158218}{158266}...provedenih noæi|u striptiz klubovima,
{158267}{158370}u kojima nije bilo nikoga, s kim|sam ustvari želio imati seks.
{158371}{158514}Poèelo mi je utjecati na|posao, brak...
{158515}{158568}Svatko je imao drugaèiju ovisnost.
{158569}{158653}Ken se palio na|gay turske kupelje.
{158654}{158756}Ron je bio|kompulzivni masturbator.
{158757}{158844}A Tom je bio voajer.
{158845}{158925}Ali njihove prièe|imale su jednu stvar zajednièku,
{158926}{159009}što su više|udovoljavali potrebi,
{159010}{159092}ona je postajala|sve jaèom.
{159093}{159188}U hodniku sam|i krvarim
{159189}{159313}i shvaæam da sam|dotaknuo jebeno dno.
{159314}{159501}Stvarno trebam pomoæ noæas,|jer ovo je bio stvarno težak tjedan.
{159634}{159746}Sada je 21:15. Tada najèešæe odvajamo|vrijeme za nove èlanove.
{159747}{159858}Hoæe li netko od novih èlanova|reæi nešto?
{159970}{160036}Da.
{160293}{160412}Kao što možete vidjeti,|ne ide mi plakanje pred kamerama.
{160413}{160495}Ali doista sam se slomio|i plakao
{160496}{160580}na prvom sastanku|na kojem sam bio
{160581}{160678}i doista sam ta i|snimio kamerom.
{160679}{160838}I ovo je traka koju sam snimio|upravo na prvom sastanku.
{160842}{160932}To je bilo 1991.godine.
{160933}{161003}Pustiti æu vam je
{161004}{161146}da možete æuti kako je to zvuèalo.
{161175}{161271}Osjeæam se dirnutim|onim što su svi izrekli.
{161272}{161335}Kako se zoveš?|-Zovem se Robert.
{161336}{161408}Bok, Robert.
{161409}{161492}Nisam koristio svoje|pravo ime.
{161548}{161585}Pušem nos.
{161586}{161667}Bio sam oženjen i...
{161777}{161848}Teško je govoriti.
{161916}{162020}Poèeo sam posjeæivati prostitutke i...
{162039}{162134}...to mi je uništilo brak...
{162181}{162250}Tada sam...
{162280}{162373}...se spetljao s nekim drugim...
{162401}{162493}...što se nedavno prekinulo...
{162514}{162586}...iz istog razloga...
{162587}{162683}Pritisnuo sam gumb|za snimanje.
{162692}{162771}Kakogod, to je to...
{162773}{162880}To je to.|Mislim, ima još, ali...
{162887}{162932}Vratimo se filmu.
{162933}{163032}Nakon toga, na sastanke|sam dolazio redovno,
{163033}{163156}te sam se s vremenom uspio suzdržati|od seksa sa prostitutkama dovoljno dugo
{163157}{163225}da bih se ponovno oženio.
{163264}{163382}Nažalost, taj brak nije|bio baš tako savršen.
{163387}{163482}Dvije godine poslije, kad se naš|brak raspadao,
{163483}{163623}imao sam odnos s prostitutkom|i to sam rekao svojoj ženi.
{163624}{163715}Podnijela je rastavu braka|odmah nakon toga.
{163740}{163813}Bok, moje ime je Caveh.|Ja sam ovisnik o seksu.
{163814}{163861}Bok, Caveh.
{163862}{163912}Nije bilo lako.
{163913}{164022}Ali nakon dugododišnjeg dolaženja|na sastanke, bar jednom na tjedan,
{164023}{164132}konaèno sam uspio imati odnosa|sa prostitutkama i to bilo kakve.
{164133}{164250}Teško je objasniti, kako sam|na kraju uspio u tome.
{164251}{164329}To je jednostavno tako.
{164330}{164514}Ali kad razmišljam o tome, sjetim se|prièe o Orfeju i sirenama.
{164580}{164660}Sirene su bile ta mistièna|biæa
{164661}{164728}èiji je pjev bio tako|opèaravajuæ
{164729}{164855}da tko god bi ga èuo,|poludio bih od strasti.
{164895}{165006}Mornari bi se bacali u more u|pokušajima da ih dohvate
{165007}{165113}da bi na kraju samo umrli|razbijajuæi se o stijenje.
{165134}{165254}Ali kada su Jason i Argonauti|morali ploviti pored sirena,
{165255}{165359}Orfej, najveæi pjesnik|stare Grèke,
{165360}{165443}došao je sa|genijalnom idejom.
{165495}{165584}Jednostavno je poèeo pjevati
{165593}{165670}i buduæi da je njegovo pjevanje|bilo tako lijepo
{165671}{165767}mornari su slušali samo|njegovu pjesmu
{165768}{165856}i nisu uopæe niti èuli|pjesmu sirena.
{165885}{165974}Osjeæam, kao da se|nešto tako dogodilo meni.
{165990}{166082}Èuo sam ljepšu pjesmu.
{166418}{166509}I tada sam upoznao Mandy.|-Bok.
{166510}{166598}Ovo je Mandy.|-Bili smo na plivanju.
{166599}{166746}Upoznali smo se na satu plesa i|ubrzo sam se zaljubio u nju.
{166794}{166880}Veæ smo 7 godina zajedno,
{166881}{166995}što je najviše da sam|s nekim proveo.
{167027}{167097}Volim te, dušo.|-I ja tebe.
{167098}{167156}Ne kažem da se|nikada ne svaðamo.
{167157}{167248}Mandy, spreman sam razgovarati|o tome. Ti nisi.
{167249}{167310}Svaðamo se stalno.
{167311}{167397}Sad je ovdje i snima me.
{167398}{167502}Ali svaðanje me više ne tjera da|utjehu idem pronalaziti u prostitutkama
{167503}{167568}ili u pronalaženju nove djevojke.
{167569}{167737}Umjesto toga, ostajem s njom i|pokušavam popraviti stvari.
{167788}{167879}Mogao bih nastaviti prièati|kako je onda odlièna,
{167880}{167941}ali vjenèanje treba poèeti.
{167942}{168024}Greg, uèinimo to.
{168823}{168910}Spreman?|Idemo.
{172419}{172503}Jedan, dva, tri.
