{279}{398}Možeš vjerovati? Zamolio sam | da odu, a nitko ni makac.
{406}{461}Da im napravimo sendvièe?
{468}{531}Zašto ih moliš? | - Molim?
{545}{634}Ako želiš da odu, naredi im.
{705}{780}Dobro, reæi æu im.
{1094}{1204}Nisu po mjerilima. | I uvijek razoèaraju.
{1237}{1345}Nikad nisu bili dobri | muževi ili oèevi.
{1375}{1486}Ne mogu ni sebe zadovoljiti. | Ne može ni itko drugi.
{1881}{1955}Dugo si spavao.
{1963}{2025}Uzeo sam tvoju tabletu.
{2048}{2120}Dosad nikada nisi.
{2202}{2274}Evo, crno na bijelom.
{2283}{2368}Proèitaj što govori. | Nevjerojatno!
{2558}{2606}Bolje da poðem.
{2645}{2703}Kamo? Subota je.
{2720}{2837}Moram nešto srediti | u ordinaciji. Neæu dugo.
{3164}{3235}Strout izašao uz jamèevinu
{3434}{3489}Želite raèun?
{3814}{3921}Ne smetam, nadam se. | - Ni govora.
{4010}{4075}Možete razmijeniti 50 $?
{4415}{4515}Hvala. Može još jedna vreæica? | - Svakako.
{4801}{4857}Pa, samo sam...
{4875}{4951}Zanimalo me kako si.
{4969}{5034}Zvao sam te.
{5157}{5226}Živimo kod mame.
{5274}{5356}Htjela sam vas nazvati... | - U redu je.
{5460}{5549}Dr. Fowler, ja... Ne mogu.
{5589}{5646}Da, znam.
{5819}{5886}Nisam lagala.
{5929}{6026}Nisam lagala prvi put. Samo...
{6111}{6168}Tako je ispalo.
{6338}{6444}Gða Fowler? | - Ja...
{6454}{6510}Kutiju crvenog Marlbora.
{7153}{7205}Kako su deèki?
{7225}{7262}Dobro su?
{7449}{7520}Moram iæi.
{7563}{7612}Vidimo se.
{7931}{7993}Dokle je tvoje?
{8002}{8104}Uvijek to pitaš. | Vidiš uvalu iza kuæice?
{8128}{8191}Do druge obale.
{8201}{8256}Gotovo 350 rali.
{8264}{8354}Znaš koliko je stajalo? | Bolje da ne znaš.
{8572}{8642}To je mali Charles kod bazena.
{8665}{8766}Otkrio je kako doæi | do bazena dizalom, sam.
{8797}{8873}Zacijelo si bila ponosna.
{8892}{8998}Shannon u redu za... | Jao, taj tobogan! Znaš koji.
{9033}{9167}Dugo se èeka u redu? | - Katkad. Više od 60 minuta.
{9198}{9296}Ako nemaš brzu propusnicu.
{9313}{9376}Što je to?
{9414}{9506}Imaju razna kraljevstva.
{9530}{9639}Brza propusnica je | laminirana ulaznica.
{9644}{9775}Na njoj piše kad da doðeš. | Ne moraš èekati.
{9783}{9881}Uðeš ravno unutra. | Bili ste na Floridi?
{9894}{9945}Nismo.
{9996}{10076}Koliko sad imaš unuka?
{10227}{10293}Maloga Charlesa i Shannon.
{10316}{10405}Troje starijih | i malene.
{10511}{10580}Charles, Shannon, Mary, | George, Wendy, Lee. 11.
{10586}{10635}Zacijelo je divno.
{10649}{10754}Willis kaže da | ne možemo izumrijeti.
{11136}{11199}Oprosti, Ruth.
{11215}{11287}Nisam razmišljala.
{11302}{11413}Željela sam još djece. | No rodio se Frank...
{11473}{11548}A Matt je upravo | otvorio ordinaciju.
{11585}{11649}Imalo je smisla, valjda.
{11918}{11969}Mali Charles.
{11992}{12094}Nemamo mnogo drva. | Znaš koliko Daniels naplaæuje.
{12115}{12219}Mogu složiti ovo, imat æu | drva za cijelu jesen.
{12463}{12532}Divan proizvod i | krasni su prema tebi.
{12543}{12598}Prodajom broda | kupili smo Subaru.
{12606}{12693}Lijepo se voziti. | Vrlo je udoban.
{12700}{12784}Nije zapravo auto | nego SUV.
{12794}{12889}Što je zapravo SUV? | - Terenac.
{12896}{12953}Mali džip!
{12959}{13055}ATV, KFC...
{13079}{13168}Èemu sve te... | - Kratice.
{13194}{13293}Ljudima je muka | sve to izgovarati.
{13301}{13391}Pa što znaèi PMS? | - Vojnièko sam dijete.
{13398}{13462}Odrasla sam uz džipove.
{13473}{13591}Willyju smeta što znam | više o muškoj stvari.
{13597}{13654}Samo o jednoj?
{13661}{13750}Hvala, stari. | - Sviða mi se.
{14005}{14080}Lijepo si sve ovo uredila.
{14088}{14191}Nisi valjda sama šivala zastore! | To je stari lan?
{14200}{14293}Recimo. Jastuènice | iz naše prve kuæe.
{14310}{14440}Saèuvala sam sve gluposti | koje sam imala. Pa i tebe.
{14983}{15048}Nismo dobro pogodili vrijeme.
{15545}{15612}Ionako ne voli | raditi na novaèenju.
{15627}{15697}Dolaze u ured u | trgovaèki centar.
{15704}{15807}Na pola se predomisle. | Ja to ne bih mogao.
{15814}{15872}Ili odustanu.
{15877}{15957}Kao onaj. Obavio je | svu papirologiju.
{16057}{16134}Da, djeèakovi su | roditelji zvali Davida.
{16142}{16253}Rekli su da je deèko toliko | htio odustati da se ubio.
{16275}{16387}To pogodi èovjeka. | Ja to ne bih mogao.
{16809}{16854}Idem sad.
{16963}{17039}Raduješ se povratku na posao?
{17127}{17185}Lijepo izgledaš.
{17629}{17723}Frank Fowler, možda si | osvojio 10.000.000 $!
{18534}{18622}Vozaè uèenik | Molite za nas
{19454}{19531}To je bilo dobro. | Ovaj put sam ja malo griješila.
{20449}{20509}Dolazi u valovima.
{20533}{20594}I onda ništa.
{20624}{20685}Kao stanka u glazbi.
{20713}{20795}Nema zvuka, no | tako je glasna.
{20901}{20999}Ne znam što da èinim. | Osjeæam se tako gnjevno.
{21085}{21221}Louise McVey izgubila je dijete. | Možda se sjeæaš.
{21323}{21429}Imala je èetvero. | Najmlaðe, zar ne?
{21470}{21555}Prièala mi je | o svojim vizijama.
{21563}{21645}Kad je doznala da | joj je kæi umrla.
{21656}{21749}Vidjela je sebe | daleko od Zemlje.
{21758}{21889}A oko nje beskonaèan red. | Kako je prilazila bliže...
{21909}{22025}Vidjela je da su to | majke koje idu naprijed.
{22057}{22147}Ušla je u red | i hodala s njima.
{22167}{22275}Na odreðenoj se toèki | red podijelio.
{22287}{22426}Rekla je kako je znala da su | na njezinoj strani
{22445}{22578}milijuni žena, sve | majke koje su izgubile djecu.
{22784}{22884}To joj je pružilo | veliku utjehu.
{22993}{23049}Kako je malena umrla?
{23057}{23128}Utopila se. | Nesreæa na plivanju.
{23492}{23574}Igra je | Teksaški lov.
{23597}{23646}Problem?
{23652}{23704}Zašto se gnjaviš | tim glupostima?
{23709}{23767}Što? | - Nismo u Vegasu.
{23774}{23833}Zatvoreni s 5 ili | otvoreni sa 7 karata.
{23838}{23934}To sam rekao. Zatvoreni. | Otvor je par deèki.
{23941}{23997}Carl? | - Seronjo!
{24009}{24085}Dolar. | - Dižem za dolar.
{24631}{24697}Recite nešto, zaboga.
{24734}{24814}Ne okolišajte preda mnom.
{24877}{24958}Zar da cijelu veèer | buljim u karte?
{25342}{25430}Postoje stvari | Koje se prešute
{25486}{25565}Neki snovi | Nikad ne umru.
{25604}{25701}Neki snovi | Jako srce oslabe
{25739}{25815}Od njih obraz izblijedi
{25834}{25901}A oko se zamagli.
{25961}{26040}Rijeèi te | Kobne pjesme
{26063}{26147}Obuzmu me | Poput jeze.
{26207}{26262}Djeèakova volja
{26280}{26337}Vjetrova je volja
{26364}{26434}A misli mladenaèke
{26440}{26523}Misli su pune žudnje.
{26729}{26786}Plaæam dva.
{26803}{26832}Idem.
{26850}{26917}Jednu. | - Ja trebam...
{26942}{27004}Trebam sve. | Daj tri.
{27035}{27096}Neka budu dobre.
{28946}{29022}Znaš kamo idemo veèeras? | Iznenaðenje je.
{29978}{30005}Matte?
{34478}{34578}Žao mi je, to je | neprihvatljivo.
{34583}{34640}Što je rekao?
{34675}{34748}Ne, ne smijemo | to dopustiti.
{34755}{34769}Èekaj.
{34778}{34878}Vani je Ryan Collit. | Majka ga je dovela.
{34885}{34979}Nazvat æu poslije. | Dobro. U redu.
{35054}{35114}Vraæam se u 16 h.
{35222}{35294}Žalim, dr. Fowler, | upravo je otišao.
{35312}{35399}Doista ga trebam. | Otišao je na ruèak?
{35572}{35630}Preko puta.
{35647}{35671}Hvala.
{36444}{36499}Matte!
{36563}{36623}Sjedni. | - Hvala.
{36669}{36741}Moj pomoænik Jack. | - Zdravo.
{36746}{36803}Don. Ovo je Ed.
{36808}{36886}Matt Fowler. | Kako ide?
{36897}{36976}Ma, u redu je. | Znaš...
{36996}{37091}Htio sam samo | proæi neke stvari.
{37135}{37216}Znaš, nakon što ruèaš. | - Svakako.
{37257}{37338}Èinimo sve što možemo. | Doista.
{37345}{37420}Što ja mogu uèiniti? | - Ništa.
{37428}{37496}Ne može ostati | ubojstvo na mah.
{37504}{37578}Ne možete li | naæi nekakav dokaz?
{37604}{37684}Ne dogaða li se to? | - Doista èinimo sve.
{37706}{37797}Neæu ti lagati. | Imamo samo Strouticu.
{37803}{37868}Tvrdi da je bilo borbe.
{37873}{37955}Forenzièari to | ne mogu dokazati.
{37972}{38069}Najbolje je da samo èekaš.
{38077}{38158}Nismo se predali, | nemoj ni ti.
{38164}{38243}Dva istražitelja | rade na sluèaju.
{38248}{38362}Još nam je najvažniji. | Pratimo neke tragove.
{38392}{38459}Imamo još mnogo posla.
{38466}{38540}Èinimo što možemo uza | sredstva koja imamo.
{38546}{38656}Moraš biti strpljiv. | Imaj povjerenja u nas...
{39174}{39269}Iznad vage zabije | bejzbolske palice.
{39275}{39347}Jer Lajavac | dolazi s ulovom.
{39352}{39427}Starac ga upita: | Ivane, što radiš?
{39432}{39494}Stari odgovori: | Šaljem poruku.
{39503}{39601}Ja uðem i vidim | te palice na zidu.
{39607}{39690}A ispred njih | velika poruka.
{39698}{39815}Kakva? | - Evo palica ako imaš muda.
{39943}{40009}Više nije dirao naše vrše.
{40014}{40061}Dr. Fowler.
{40066}{40117}Hej, Time.
{40124}{40178}Je li ikad...
{40191}{40290}Je li ti spomenuo | što se tad dogodilo?
{40301}{40404}Nije. Više i | ne viðam Richarda.
{40426}{40507}I ništa mi ne bi | rekao. Vjerujte.
{40515}{40609}Svakako. Ni govora. | Samo sam se pitao...
{40633}{40709}Možda si èuo kakav traè.
{40718}{40790}Možda je koji njegov | kompa nešto rekao?
{40839}{40874}Nije.
{40926}{40996}Njegova braæa još rade s tobom?
{41031}{41095}Sigurno nešto govore.
{41141}{41261}Želim reæi, ako otkrijemo | nešto konkretno...
{41298}{41398}Možda je nešto izletjelo.
{41583}{41657}Naæulit æu uši. | - Hvala.
{41787}{41882}Èudno je što | smo se ovdje sreli.
{42667}{42754}Nadala sam se da | možemo razgovarati.
{42854}{42968}Htjela sam reæi | koliko mi je žao i...
{43025}{43164}Ako postoji išta što bih | mogla uèiniti...
{43297}{43355}Razgovarati...
{44249}{44326}Vraæam se na posao. | Nemoj ništa ukrasti.
{44515}{44580}Još štogod? | - Bijeli Marlboro.
{44757}{44855}To je 14,95, | s cigaretama.
{45364}{45420}Kako je danas bilo?
{45787}{45849}Nešto ne valja? | - Ne valja?
{45859}{45912}Što, na primjer?
{46425}{46515}Što želiš? | - Znati što se dogaða.
{46584}{46675}Uzrujana si. Možemo li | razgovarati?
{46704}{46783}Razgovarati? | Tko, mi?
{46790}{46844}Što ako tko naiðe?
{46851}{46929}Mislili bi da su | pogriješili kuæu.
{46963}{47067}Želiš razgovarati? | - O našem mrtvom sinu? Ne.
{47105}{47197}Nismo prije, | zašto bismo sad?
{47253}{47339}Što mogu uèiniti? | - Zaboravi, Matte.
{47364}{47417}Samo otiði.
{47436}{47495}Što hoæeš od mene?
{47502}{47580}Da se ne ponašaš kao da se | ništa nije dogodilo.
{47638}{47752}Zato što ne šizim? | - Ne. Za to trebaš osjeæaje.
{47765}{47837}Ne želimo da se povrijediš.
{47853}{47955}Molim te, u tugovanju se | natjeèi s nekim drugim.
{48006}{48093}Znam kako tuguješ. | Popij još jedno pivo.
{48154}{48250}Koga vraga to znaèi? | Što ti znaš?
{48276}{48375}Nemaš pojma. Nemaš | pojma kroz što prolazim.
{48408}{48514}Ne, ne znam, ili èak | prolaziš li kroza išta!
{48531}{48617}Ali to si ti izabrao, ne ja.
{48644}{48724}Da, izabrao sam da se | ne ljutim na svijet!
{48729}{48801}Jedno mora biti razumno!
{48809}{48947}Razumno? Ne znam za tebe, | meni nedostaje sin.
{49013}{49115}Imaš vremena za razumnost. | Usadio si to i Franku.
{49169}{49242}Smatrao te vrlo razumnim.
{49281}{49349}O èemu govoriš?
{49428}{49479}Ni o èemu.
{49605}{49661}Kažeš da sam ja...
{49704}{49770}Da sam ja odgovoran?
{49835}{49883}To je to?
{49935}{50040}Reæi æu ti nešto. | Pobrkala si sve!
{50065}{50159}Misliš da sam bio | previše popustljiv!
{50166}{50254}Da sam mu dopuštao... | - Sve! Sve!
{50271}{50372}Da! Zašto nije išao tebi? | - Nije me slušao!
{50389}{50485}Nije mi vjerovao. | - Jer ti njega nisi slušala.
{50494}{50590}Ali ti jesi. Namigivao si mu. | Poticao ga.
{50617}{50696}Htio si što je on imao. Nju.
{50712}{50780}Zacijelo se šališ! | - Ma daj, znaš to!
{50785}{50868}Nisi to mogao dobiti. | Zato si to puštao.
{50873}{50946}Da uživaš preko sina.
{50952}{51009}Ne možeš priznati istinu.
{51016}{51113}Da je Frank umro zbog | tvoje fufice iz snova!
{51165}{51287}Znaš zašto je naš | sin mrtav? Zanima te?
{51311}{51384}Nije bio s njom zbog mene.
{51392}{51475}Išao je tamo zbog tebe. Da.
{51493}{51608}Jer si tako prepuna kontrole. | Napasna.
{51660}{51744}Ljuta što je on bio sve.
{51752}{51822}Naše jedino dijete. | - Nije istina!
{51837}{51956}Kao malome uvijek si mu | govorila da griješi.
{52043}{52135}Jednom si ga izvukla | s utakmice bejzbola.
{52151}{52205}I poslala doma.
{52213}{52292}Jer je bacio | rukavicu na tlo.
{52301}{52392}Koliko je bio star? 9 g.?
{52617}{52710}Sve što je radio, | bilo je pogrešno.
{52792}{52889}Što je to kod njega | bilo pogrešno?
{53093}{53192}Ne znaš opraštati.
{53247}{53327}Istina. On je tako govorio.
{53458}{53578}Ista sranja izvodiš sa mnom. | A grozno je biti takav.
{53653}{53731}Ogorèena si.
{53743}{53860}Samo okrivljuj mene, | ali pogledaj i sebe.
{54163}{54283}Htjela sam razgovarati | o onome što se dogodilo.
{54351}{54435}Želiš da budem | otvoren s tobom?
{54450}{54509}Strašiš me.
{54534}{54662}Kako bih razgovarao kad te | katkada ne mogu ni gledati?
{54896}{54936}O, Bože!
{55079}{55134}Vjerojatno policija.
{55296}{55385}Kristen Gellar iz | Gimnastièkog saveza.
{55395}{55450}Prodajemo slatkiše.
{55456}{55542}Svakoj kupnji parira Tandy | da možemo putovati na Oahu
{55548}{55641}na natjecanje Istoka i Zapada.
{55653}{55709}Dobro, kupit æu.
{55728}{55836}Imamo posebnu ponudu. | 6 komada za 10 $ .
{55857}{55930}U redu, kupit æu to.
{56000}{56076}Da nešto pridržim? | - Možete ovo? Hvala.
{56191}{56268}Evo 10 dolara. | - Hvala.
{56310}{56388}Izaberite. Što god želite. | - Bilo koje?
{56803}{56868}Ono što sam rekao...
{56960}{57025}Nisam imao pravo na to.
{57075}{57124}Nitko...
{57151}{57242}Nitko ne treba | èuti takvo što.
{57317}{57374}Žao mi je.
{57572}{57606}U redu je.
{57646}{57715}Ne. Imaš pravo, Matte.
{57729}{57803}Ja jesam grozna.
{57832}{57908}Molim te, molim te, nemoj.
{58034}{58096}Ne krivim tebe.
{58116}{58148}Samo...
{58218}{58289}Ta je cura došla u školu.
{58352}{58447}Nisam joj mogla oprostiti.
{58472}{58512}Bila sam...
{58524}{58575}Bila sam tako...
{58770}{58820}Žao mi je.
{58834}{58872}Bila sam...
{58899}{58955}Tako gnjevna.
{58973}{59024}Sve je u redu.
{59079}{59120}Samo...
{59198}{59269}Vidjela sam ga. Viðam ga.
{59276}{59330}Znam. Ja...
{59342}{59429}U njegovoj sobi, katkada | bih se zakleo da je ovdje.
{59513}{59593}Danas na semaforu zakleo | bih se da Frank... - Ne on.
{59602}{59698}Ne Franka. | Richard.
{59720}{59787}I ne znam što bih.
{60129}{60186}Gdje si ga vidjela?
{60192}{60253}Posvuda. U gradu, u duæanu.
{60269}{60327}U South Endu.
{60361}{60430}Nasmiješio mi se.
{60488}{60552}Stalno ga susreæem.
{60582}{60640}Smiješio se.
{60776}{60823}Sve je u redu.
{61948}{62031}Dolaziš u krevet? | - Ubrzo. Matt je tu.
{62047}{62105}Zdravo, Matte.
{62113}{62189}Kad dolaziš, | donesi mi tablete.
{62212}{62318}Na gornjoj su polici, | otkako su djeca bila.
{62439}{62515}Nisam razmišljao | o jamèevini.
{62544}{62628}Mislio sam da | godinama ne trebam.
{62639}{62693}Znaš što sam èuo?
{62700}{62789}Da za prijatelja | konobari u Orchardu.
{62811}{62892}I najgori gadovi | imaju prijatelje.
{62897}{63009}Nitko ga ne poznaje. | Piju što im smiješa.
{63105}{63160}Mrzim ga.
{63169}{63263}Deèki kažu da je i u | školi bio isti takav gad.
{63269}{63330}Znaš koliko æe dobiti? | Najviše 5 godina.
{63338}{63417}Znam. | - Sjeæaš se žene otprije 7 g.?
{63429}{63535}Ubila je muža i bacila ga | s mosta u vreæi s 50 kg cementa.
{63543}{63621}Rekla je da joj | nitko nije pomogao.
{63629}{63727}Znaš gdje je sad? | Tajnica je u Searsportu.
{63754}{63842}A gdje je onaj | koji joj je pomogao?
{64064}{64140}To bi mi slomilo srce.
{64183}{64291}Ali, jesi li kad pomišljao...
{64325}{64381}O tome da se odseliš?
{64446}{64554}Jesmo. | Ne bi bilo razlike.
{67269}{67344}Otpratit æu te. | - Laku noæ, Richarde.
{67352}{67437}Ideš na piæe? | - Ne, hvala.
{67452}{67522}Samo jedno. | - Drugi put.
{67562}{67599}Ma daj!
{67635}{67660}Dobro.
{67705}{67757}Jebena droljo!
{68155}{68212}Što æete vi ovdje?
{68327}{68381}Mogu li vam...
{68393}{68442}Nekako pomoæi?
{68723}{68779}Nemoj govoriti.
{68783}{68853}Otkljuèaj auto i uði.
{68865}{68922}Samo malo. Smirite se...
{68931}{68987}U redu, dobro.
{69034}{69079}U redu.
{69671}{69700}Otkljuèaj.
{69963}{70065}Ima li koga kod tebe? | - Veèeras nema.
{70073}{70133}Dobro. | Vozi tamo.
{70169}{70285}Polako! Nemoj pokušavati | srediti da te zaustave.
{71021}{71109}Ševio je moju ženu, | dr. Fowler.
{71326}{71385}Nemoj govoriti.
{72046}{72146}Idemo na stražnja vrata. | I šuti.
{72373}{72405}Upali svjetlo.
{72553}{72615}Gdje ti je kovèeg? | - Kovèeg?
{72622}{72687}Gdje je? | - U ormaru u spavaæoj sobi.
{72706}{72825}Idemo tamo. Kad doðeš do vrata, | stani i upali svjetlo.
{73481}{73534}Nema zidnog prekidaèa.
{73560}{73616}Gdje je svjetlo? | - Kod kreveta.
{73642}{73671}Hajde.
{73869}{73942}Sjedni. | Na krevet.
{74173}{74229}Koji ormar?
{74248}{74304}Gdje su kovèezi?
{74705}{74773}Želio sam se | pomiriti s Natalie.
{74786}{74869}Pokušati opet biti s njom. | Nisam mogao.
{74923}{75007}Ni razgovarati. | Uvijek je bio ondje.
{75054}{75139}Bilo je sluèajno. | Iæi æu u zatvor.
{75146}{75202}Izaæi æu star. | To nije dovoljno?
{75207}{75263}Ne ideš u zatvor.
{75313}{75385}Uzmi odjeæu za hladnoæu.
{75507}{75622}Pustit æete me? | - Bježiš unatoè jamèevini.
{75650}{75723}Molim? | - Pakiraj.
{75744}{75770}Hajde!
{75900}{76030}Suðenje. Žena i ja to | ne možemo preživjeti.
{76040}{76110}Zato odlaziš. | Kupio sam ti kartu.
{76166}{76260}Moja te žena svugdje viða. | Ne mogu to dopustiti.
{76328}{76380}Hvala, dr. Fowler.
{76560}{76643}Otišao bih po deèke | i pronašao ga ondje.
{76657}{76717}Katkad bi i prenoæio.
{76723}{76777}Duncan bi mi rekao.
{76785}{76856}Žao mi je. | - Dosta!
{76869}{76930}Trebam nešto iz kupaonice.
{77395}{77454}Hodaj dalje. | - Moram pišati.
{77501}{77530}Hajde.
{78562}{78582}Èekaj.
{78749}{78829}Željeznica
{78973}{79044}Uhvatit æe me na temelju | popisa putnika.
{79052}{79105}Karta nije na tvoje ime.
{79110}{79200}Znat æe. Da je tako Iako, | uèinio bih veæ to.
{79207}{79281}Bio si sam. | Mi smo sve smislili.
{79301}{79359}Tko to mi?
{79365}{79430}Pali motor i krenimo.
{79744}{79820}U ovo doba nema aviona.
{79828}{79900}Idi na sjever, cestom 73.
{79941}{80002}Aerodrom je na jugu.
{80013}{80118}Netko æe te èuvati. | Oni æe te odvesti na aerodrom.
{80181}{80275}Upali radio. | Naði tekmu.
{80306}{80391}Prošlo je jedan. | - Puštaju je opet.
{80420}{80477}Dosta brbljanja.
{83222}{83270}Okreni! | - Zašto?
{83276}{83334}Promašili smo! | - Dobro.
{84196}{84264}Ovdje nema nièega.
{84284}{84364}Zašto jednostavno | ne odemo na aerodrom?
{84399}{84485}Zar da ondje | ostavimo auto?
{84553}{84619}Odgulit æu 20 godina.
{84629}{84691}Imat æu 53 godina.
{84725}{84813}Godinu manje nego ja sada.
{84948}{85009}Gdje smo?
{85017}{85072}Još malo.
{85252}{85320}Ugasi motor. | Ostavi svjetla.
{85410}{85471}To je vaša brvnara?
{85477}{85544}Nije. Uzmimo torbe.
{86062}{86117}G. Grinnel! | - Ja æu ih uzeti.
{86199}{86231}Èekaj.
{86355}{86410}Uzmi ovo.
{87030}{87124}Što si uèinio?! | Nismo se tako dogovorili.
{87214}{87252}On...
{87335}{87390}Pokušao je pobjeæi.
{87468}{87565}Kanili smo èekati i | ubiti ga u šumi.
{87724}{87795}Nisam mogao èekati.
{87969}{88038}Idem po vozilo.
{89362}{89388}Èekaj.
{89903}{89935}Moramo poæi.
{91155}{91209}Ma daj!
{92081}{92133}Koliko je sati?
{92179}{92235}10 do 4.
{92255}{92329}Izgubili smo sat vremena. | Oprosti.
{92396}{92452}Da, plima je.
{92460}{92520}Ne možeš ljude sprijeèiti | da idu u ribolov.
{92543}{92625}Jebeni most! | - Oprosti, Willise.
{92782}{92854}Jednom sam bio u | njegovoj kabini.
{92867}{92916}Zaudaralo je.
{92935}{93024}Prolije više viskija | nego što smo mi ikad popili.
{93042}{93127}Molit æemo se | da je veæ pijan.
{93245}{93325}Katiena tableta | uskoro æe popustiti.
{98891}{98960}Uèinio si to?
{99997}{100066}Dobro si, Matte?
{100335}{100437}Na zidu je bila njegova | fotografija s Natalie.
{100621}{100678}Što je, Matte?
{100818}{100883}Kako se smijala...
{100973}{101006}Što?
{101173}{101229}Ne znam.
{102052}{102117}Gdje mi je pamet?
{102124}{102187}Zacijelo si gladan.
{102967}{103025}Želiš li kavu?
{103026}{103380}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan  
{105687}{105826}Obrada | DISCOVERY FILM I VIDEO
