{3195}{3241}I, kako se osjeæaš?
{3243}{3286}- Dobro.|- Da?
{3288}{3357}- U redu je. Malo boli.|- Gdje te je zviznula?
{3359}{3393}Toèno ovdje.
{3413}{3455}Nema krvi.
{3457}{3517}- Nema toèkice, niti nièega.|- I dalje osjeæam.
{3520}{3554}Naravno.
{3600}{3657}- Na to sam ranije mislio.|- Što?
{3659}{3736}Devedesete. Ne mogu si priuštiti niti namigivanje.|Previše mi nedostaju.
{3738}{3786}Nije neka stvar.
{3788}{3866}Howard, žena te lupila,|prilijepila po glavi.
{3868}{3919}- Što si joj rekao?|- Ništa.
{3921}{3999}- Nisi ništa rekao.|- Pitao sam ju za vrijeme.
{4001}{4070}"Koliko je sati?"|Ili "Imaš vremena?"
{4072}{4110}Tu je presudna razlika.
{4112}{4177}Pitao sam ju koliko je sati.|Znaš, Mountain, Central.
{4179}{4252}- Ti imaš sat.|- Ne šalim se.
{4255}{4381}Govoriš o nekom neprovociranom|napadu? To je zaista nepoželjno.
{4383}{4441}- Je li ti bar rekla vrijeme?|- Ne.
{4477}{4555}- Kog se vraga ti smiješ?|- Chad, nije važno.
{4557}{4620}Dobro, onda smo nastradali.|Ozbiljno.
{4660}{4695}Kao rasa.
{4697}{4771}Ljudi poput nas, tipovi koji brinu|o poslu, svojim ženama...
{4773}{4823}Gotovi smo ako|æe se tako ponašati prema nama.
{4824}{4901}- Kako to misliš?|- Sjedimo u grofovskoj loži...
{4903}{5009}vrijeme prolazi, potpuno na|milosti onih gadova gore.
{5012}{5083}- I sad ovo.|- Joj. Da.
{5084}{5155}Život je za uzimanje, zar ne?
{5192}{5280}Prije deset godina smo bili|na fakultetu. To je sve, samo deset.
{5282}{5346}Imam tonu takvih mladih tipova|za svojim stolom.
{5348}{5442}Zapošljavaju se kao pomoænici proizvodnje|To zanimanje prije dvije godine nije ni postojalo.
{5444}{5534}Samo da bi visjeli u kantini.|Strvinari èekaju da me pošalju u mirovinu.
{5536}{5654}Slaba zarada dva mjeseca za redom?|Hranit æe se mojim iznutricama.
{5656}{5711}- Nisam budala, znaš?|- Naravno da ne.
{5892}{5947}- Jeste li dobro?|- Tako izgleda.
{5948}{6036}- Ne. Ozbiljno.|- Zapravo je smiješno.
{6038}{6084}Da? Nema sumnje.
{6086}{6125}Veliki deèko. Èujem da igraš.
{6127}{6192}Vjerojatno je sve èastio ruèkom|u srijedu.
{6194}{6244}Da, je.
{6246}{6339}Sve je to lijepo i prekrasno, i smiješne|prièe o njegovoj djevojci u vreæi.
{6340}{6387}Kladim se da ju dobro vrti.
{6388}{6478}Za godinu dana tražit æe te|da razbacuješ zamisli
{6480}{6526}sa nekima iz mlaðeg osoblja....
{6528}{6645}i "Možeš li mi ostaviti crullere?|To su jedine krafne koje volim."
{6648}{6689}Kažem ti.|Budi oprezan.
{6793}{6840}Na èemu to radiš?
{6841}{6899}Provjeravaš kako æe "direktor projekta"|gledati na tvoje pismo?
{6900}{6971}- Budi pristojan.|- Zaboravi. Šalim se.
{7024}{7083}- Pogledaj stražnjicu ovog tipa.|- Naravno.
{7084}{7178}Nov je i zabavan i vražji|shortstop. Èetverosrpanjski piknik...
{7180}{7224}sve dok tvrtka|ima nisko uzmicanje
{7226}{7305}i razbacuje se tvojim imenom naokolo|kao netko za Phoenixov ured.
{7307}{7406}Želi još jednu drvom obloženu|plaketu: "zaposlenik mjeseca".
{7408}{7466}Dobro. Biti æu oprezan.
{7468}{7530}Kažem ti.|Èuvaj leða.
{7581}{7650}Viðam se s tom curom veæ|gotovo cijelu godinu.
{7652}{7748}Što ja prièam. Upoznao si ju.|U "Seafood jointu", prije šest mjeseci.
{7750}{7813}- Ona mala brineta? Melody?|- Melanie, da.
{7815}{7865}- Slatka je, sjeæam se.
{7867}{7951}- Da, otpeljao sam je kuæi.|Upoznao joj starce.
{7953}{8024}- Èak joj i dao prsten jednog vikenda.|- Ozbiljno?
{8026}{8102}- Da, stvarno sam ju volio.|- Zvuèi kao ona.
{8104}{8186}Ali onda je poèela|"moram se viðati i s drugima" shemu
{8188}{8243}i cijelu tu šablonu.
{8245}{8316}Odjednom sam parkiran ispred|njezine kuæe u 4 sata ujutro.
{8317}{8365}idem na posao,|podoènjaci ispod oèiju.
{8408}{8498}Zovem ju tri puta prije no što ona|odgovori. Znaš to sa telefonskim išèezavanjem.|Kada se èujemo sve rjeðe i rjeðe.
{8500}{8571}Konaèno sam rekao|"To mi ne treba u životu."
{8573}{8641}Netko me odbije,|znaš, žena?
{8643}{8702}Izluðuje me... ah!|Mrzim to.
{8704}{8757}- Da?|- Izgleda da sve...
{8759}{8818}znaš, posao, te žene...
{8820}{8875}Imam osjeæaj kao da|izlaze iz ravnoteže. Zar ne?
{8877}{8945}Da, stvarno izlaze, Howard.
{8968}{9020}Moramo nešto uèiniti.
{9080}{9160}Znaš zašto sam još uvijek chipper,|veliki smiješak na licu, Howie?
{9162}{9196}- Zašto?
{9273}{9340}Jer sam nešto shvatio.
{9342}{9412}Shvatio sam prije mjesec dana.
{9413}{9508}Došao sam kuæi i Suzanne|je baš spakirala sve što smo imali.
{9510}{9556}Da. Otišla je. Samo tako.
{9587}{9641}Stvarno? Nikad...
{9643}{9751}Ostavila mi prazninu|i moj poster "Amerièkog Žigola."
{9752}{9799}Mrcina je uzela èak i njegov okvir.
{9853}{9902}Stajao sam tamo, ni bilješke...
{9904}{10006}niti "hvala za èetiri godine krova|nad mojom izbijeljeno-plavom tikvom" ...ništa
{10008}{10078}Znaš?|I onda mi sine... èinjenica
{10080}{10167}Boli me kita|za bilo koga.
{10169}{10242}Nekoga iz obitelji, posao, nikoga...
{10244}{10282}Nije mi niti najmanje stalo.
{10319}{10353}- Geez.
{10384}{10466}- Nemoj me krivo shvatiti. Kolege smo|- Isti fakultet.
{10468}{10555}Doista, to nešto znaèi.|Ali za ostale...
{10557}{10643}Znaš, skakanje po tebi|dok ti dobro ide. Ne, to neæe iæi.
{10682}{10764}Ljudi. Vražja Susane vjerojatno|u Arizoni vozi buggye.
{10767}{10813}ne brine ni o èemu.
{10844}{10907}Bože, to me tjera da|nekog dobro zajebem.
{10908}{10947}Naravno. Isuse.
{10984}{11051}Znaš, da živimo u Indiji...
{11052}{11131}mogao bi spaliti svoju zaruènicu|na lomaèi u seoskom naselju...
{11132}{11211}da samo spomeneš što ti je|uèinila za ovaj dan.
{11212}{11252}Slušam.
{11292}{11384}Zaokruži datum na ovome momèino.|Nastavljamo igru...
{11386}{11494}sa ovim "pokupi raèun",|"ne može li se djevojka predomisliti", sranjem...
{11496}{11577}ne možemo se èak ni zezati|na radnom mjestu.
{11580}{11650}Biti æe teško iæi do kraja,|nema sumnje.
{11692}{11748}Moramo èvrsto odluèiti.
{11896}{11934}Nikad ne gubi kontrolu.
{11962}{12000}To je kljuè, Howard.
{12052}{12110}To je jedini kljuè|svemira.
{12154}{12188}Vjeruj mi.
{12251}{12309}- Hajde.|- Ne znam.
{12384}{12442}Zar ti mi izgledamo kao fratri?
{12444}{12482}Trebamo viski.
{12572}{12607}Slušaj.
{12645}{12731}U gradu smo šest tjedana, zar ne?|Samo brbljam, slobodno me prekini.
{12733}{12823}Ovo je savršeno, ima veze|sa tvojim prekidom.
{12824}{12895}Recimo da naðemo neki gala tulum.|¸
{12896}{12988}I znam da imamo puno|posla...
{12990}{13091}ali samo pretpostavljam, za volju|diskusije, spotaknemo se na nešto.
{13120}{13207}Na osobu, strašno ranjivu.
{13209}{13325}Znaš, mladu, krhku|ili slièno. Izoblièenu na neki naèin.
{13368}{13444}Neku ženu koja je prilièno sigurna|da je život...
{13446}{13556}pritom mislim na cijeli, zdrav, spolni život,|romantika i takve stvari...
{13558}{13604}za nju zauvijek izgubljen.
{13862}{13896}Bog te blagoslovio.
{13940}{13995}Dakle, naðemo takvu djevojku...
{13996}{14123}neku seosku kuèku koja bi|skoèila u blato samo da našiljiš olovku|za nju.
{14124}{14171}i oboje ju ruknemo.
{14194}{14283}Mali razgovor, veèera, cvijeæe...
{14285}{14359}Bez pritiska na prvom sudaru,|kao da
{14361}{14459}ju vodiš na, ne znam,|Ledenu paradu.
{14460}{14501}Takvo nešto.
{14503}{14591}I onda to napravimo, ti i ja,|izlazimo s njom oboje.
{14592}{14652}Odjednom, ima dva deèka.|Zove majku.
{14654}{14697}Ponovno se ureðuje.
{14700}{14746}I nastavljamo igru|dalje i dalje...
{14748}{14803}I onda jednog dana
{14805}{14895}prestane nježnost|i pritisnemo ju muški, a Jill...
{14897}{14947}kasnije doðe potpuno bijesna.
{14987}{15026}Whoa.
{15045}{15157}Sat vremena kasnije na putu smo u |civilizaciju kao da se ništa nije ni dogodilo.
{15159}{15234}Vjeruj mi. Za tjedan dana æe tražiti|tablete za spavanje
{15236}{15315}a mi æemo se smijati|sve dok ne ostarimo.
{15346}{15384}Što misliš?
{15386}{15474}- Pa, ...|- Nije li savršeno?
{15476}{15547}Vratiti malo dostojanstva|našim životima.
{15548}{15644}Ljepotica je, za slijedeæi mjesec|i pol. Možemo to odglumiti.
{15647}{15693}Možemo se predstaviti kako|god želimo.
{15695}{15752}Dobro. Mislim, zvuèi...
{15753}{15812}Ne želim te šokirati.|To je samo ideja.
{15814}{15875}Isto kao što smo izvodili u školi|samo bolje
{15876}{15981}zato što æemo dobiti na ovoj|zbrljanoj vezi, kojom se bavimo.
{15983}{16020}Razmisli o tome.
{16022}{16100}Ne, dobro. Mislim, smiješno je
{16102}{16162}Ali u stvarnosti...
{16164}{16230}- Naravno, i zato je|tako savršeno.
{16232}{16292}To je sve djevièanski teritorij.
{16295}{16345}Bez obzira što uslijedi
{16348}{16423}prešao rub zbog promocije,|žena pobjegla s nekim biokemièarom.
{16425}{16464}i tko zna što...
{16466}{16531}ali uvijek æemo imati ovo|da se vratimo.
{16533}{16646}Uvijek æemo moæi reæi:|"Da, dobro, ali mene nikad nisu sjebali|kao što smo mi nju."
{16682}{16728}Mislim da bi to bilo vrlo osvježavajuæe
{16730}{16807}i vrlo ljekovito -|silazimo sa žene koju smo upravo imali.
{16886}{17004}Onda, samo za primjer|tko bi to bio?
{17091}{17125}Nemam pojma.
{17170}{17279}Ona je tu negdje... znam to...|èeka da ju pronaðemo.
{17433}{17480}Što je rekla?
{17482}{17557}"Ne vjerujem nièemu što|tjedan dana krvari i ne umre."
{17696}{17731}Dakle, pristaješ?
{17750}{17811}Sranje, èovjeèe.
{17813}{17860}Da, pristajem.
{17861}{17909}Dobro. Uèinimo to.
{17997}{18035}Ranimo nekoga.
{18516}{18559}Bok. Kako si?
{18561}{18608}Slušaj. Oprosti?
{18642}{18715}Isuse, na što nalikujem,|na dostavljaèa? Oprosti?
{18768}{18850}Vjerojatno slušalice. Kako možeš raditi|uz glazbu? Mene bi izludilo.
{18868}{18915}Kako god, imam ovo.
{18916}{19015}Netko te je preporuèio, rekao je|da si dobra. I trebao bih to do 14 sati.
{19016}{19135}Ako to ne budem nosio do|14:00, možeš zaboraviti.
{19136}{19206}Sjedit æu do tebe sutra|i posuðivati bjelilo
{19208}{19283}a k tome ja i ne tipkam.|Onda, možeš mi to napraviti?
{19449}{19514}Slušaj. |Možeš još i baciti naslovnicu na to.
{19516}{19588}Uzmi jednu od tvrtkinih mapa|i ubaci u nju...
{19589}{19624}Oprosti?
{19716}{19776}Što je dovraga?|Jesam li što napravio?
{19840}{19920}Ne.|Nije to.
{19922}{19964}Ne, nije.
{19966}{20096}To nije ono što sam želio reæi.|Ne, nije. Nemoj mi reæi da je.
{20097}{20195}Tu sam, razgovaram s tobom|i kažem ti ne, dakle, nije.
{20263}{20334}Ovo nikamo ne vodi,|zato što nije
{20336}{20429}i  to æu nastaviti govoriti|jer nisam.
{20480}{20591}Ovo je tvrtka. Ja radim|i cijelo vrijeme se vrtimo u krug.
{20621}{20695}Predlažem da razgovaraš|direktno s njom.
{20697}{20772}Mama, rekao sam ne.
{20800}{20891}Briga me što je zvala.|Ne znaèi da joj ja želim odgovoriti.
{20893}{20931}Ne, nije.
{20984}{21092}Reci joj da te prestane gnjaviti, daj mi|25 centa po pozivu ako tako jako želi brbljati.
{21133}{21204}Ne, ne mogu ju nazvati.|Onda bih morao razgovarati s njom.
{21207}{21312}Što misliš zašto ne želim njen novi|broj? Zato da ne bih morao biti taj koji...
{21357}{21395}Ne, mama, s...
{21495}{21533}To je rekla?
{21576}{21622}Stvarno. Ta kuèka.
{21645}{21709}Ne, nisam to rekao.|Mislim, nisam...
{21737}{21779}...to mislio.
{21780}{21836}Dobro. Žao mi je. |Znam da je.
{21874}{21911}Slušaj, moram iæi.
{21914}{21987}Neæemo trebati tvoju pomoæ.|Hvala.
{22049}{22115}Trgovaèki predstavnik.|Agresivan mali drek.
{22392}{22456}- Hej, John, zar ne?|- Da. Kako je?
{22458}{22492}- U redu.|- Dobro.
{22494}{22604}- Kako stoje brojke gore?|- Usrano. Nemam èak niti radni stol.
{22606}{22653}Ti jebeni maljari gore|lutaju naokolo.
{22655}{22773}- Bar imaš prozor. Imali su|problem sa A.C.-om. Prije dva tjedna.
{22775}{22832}Recimo da ima štih hrðavosti.
{22833}{22931}Kako god, slušaj, što je sa|onom djevojkom kojoj si me poslao?
{22933}{22995}Ponaša se kao da imam drek|razmazan po kravati.
{22997}{23071}Oprosti. Trebao sam ti reæi.|Uvijek je takva.
{23072}{23143}Strašno živcira. Ne može održati|razgovor dvije minute.
{23144}{23228}Kakva je to feministièka naklapaèa?|Što si ona umišlja da je neka Božica?
{23276}{23310}Gluha.
{23424}{23482}Zajebavaš me.
{23484}{23521}Što sa slušalicama?
{23524}{23584}Ne znam. Podsvijest, valjda.
{23587}{23664}Drži jako do sebe|svaki put kada ju vidim...
{23684}{23719}Ne seri.
{23741}{23776}Hvala.
{24583}{24617}I, lažem li?
{24619}{24685}Što koristiti da te razumije,|pseæu zviždaljku?
{24687}{24764}Ne, èita s usana.
{24766}{24863}Ovdje je tri tjedna.|Došla je preko jedne od onih agencija.
{24865}{24903}Piše 95 slova u minuti.
{24905}{24955}Odlièno. Zna li prièati?
{24957}{24995}Nikad je nisam èuo.
{25052}{25098}Mislim da ima jedan od onih|glasova.
{25100}{25139}- Znaš, kao...|- Kao dupin.
{25218}{25287}Kao nedjeljno èavrljanje s Flipperom.|To mi govoriš?
{25288}{25339}Tako nešto.
{25341}{25388}Èovjeèe, koji komad.
{25390}{25444}Nekako je zgodna, na neki naèin.
{25446}{25491}Kako god.
{25492}{25535}Svejedno, hvala.
{25536}{25590}Vidimo se kasnije.
{25766}{25804}Odlièno.
{25869}{25953}Jutros, bio sam vrlo nepristojan.|Nisam se predstavio.
{25956}{26007}Ja sam Chad Piercewell.
{26008}{26099}Drago mi je.|Ti si nova, zar ne?
{26100}{26170}Neka ti ne bude neugodno.|Svi smo ponekad novi, zar ne?
{26206}{26263}Lijepa bluza.
{26324}{26410}John Merrick. To je jedina stvar|koje se mogu sjetiti cijelo vrijeme.
{26412}{26472}Sjedim nasuprot|jebenom Èovjeku Slonu.
{26520}{26576}Privlaèna je, zar ne?
{26578}{26639}Da, valjda.|Rekao bih da.
{26642}{26711}- Visoka?|- Prosjeèno.
{26712}{26760}Ali trebao bi ju vidjeti kako
{26763}{26822}radi da bi sastavila|najjednostavnije glasove.
{26825}{26947}A, E, I, O, U i ponekad Y je kao|Sveti Gral toj jadnici.
{26948}{26987}Nakon otprilike 15 minuta
{26988}{27059}nisam više mogao gledati slinu|u kutu njezinih usta
{27060}{27115}jer bi izgubio apetit za taco salatu.
{27152}{27257}- Ali bila je ljubazna? Mislim...|- Ljubazna? Da.
{27259}{27335}- Draga, brižljiva, i sve što ide uz to.|- To je dobro.
{27336}{27413}Jedna je od najbrižljivijih ljudi koji su me|ikad zalijevali kapljicama sline u razgovoru.
{27534}{27593}- No, što radiš?|- Dolazim.
{27595}{27632}Isuse.
{27635}{27698}Onda, reci. Što još?
{27700}{27809}Imam cijelu povijest njene obitelji|zabilježenu na komplet ubrusa
{27811}{27866}jer konaèno,|tražio sam ju da prestane prièati
{27868}{27918}jer bi bilo lakše zapisivati.
{27920}{28010}Dakle, sad èitam te stvari|cijelu noæ, odgovaram na 20 pitanja.
{28012}{28091}Obitelj živjela u njemaèkoj -|ratno zrakoplovstvo.
{28093}{28166}Izgubila je sluh|sa osam godina ili tako nešto.
{28168}{28239}Ima nešto sestara,|rade terenski posao.
{28271}{28352}Vidio sam njihove slike.
{28380}{28435}Traži ju da ti pokaže, kad ju sretneš.
{28467}{28518}Dakle, dalje i dalje. I tako u beskraj.
{28520}{28575}Veèera?
{28577}{28675}Da, jeli smo. Pogodi tko ne poseže |za torbicom kada konobar donese raèun.
{28707}{28753}- Kino?|- Ne. Radi noæu.
{28755}{28801}Usput. Poèinjem polagano.
{28830}{28880}- Poljubac pred vratima?|- Naravno.
{28882}{28928}- Ljubazan.|- Samo u obraz.
{28965}{29072}Nije ružna, ali|trebao bih vidjeti što radi sa ustima
{29073}{29147}da vidiš te malene balonèeke|kako se naprave i puknu.
{29149}{29221}Poljubac u lice je dosta.
{29286}{29332}Savršena je za ovo.
{29334}{29412}- Da?|- Više no što sam oèekivao.
{29414}{29513}Vou. Hej, ne mislim te provjeravati|ili tako nešto...
{29515}{29554}ali jesi li dovršio one dokumente.
{29556}{29626}Na tvom su stolu.|Kada ih potpišeš, vani smo.
{29628}{29662}Super. Hvala.
{29751}{29801}- Dolazim!|- Isuse.
{29906}{29967}Ne predomišljaš se oko ovoga, zar ne?
{29970}{30016}Ne, samo ne znam je li ona...
{30018}{30078}Dobro. Jer ne radim ovo|da bih našao družicu, dobro?
{30080}{30135}- Mislio sam da smo u ovome oboje.|- Jesmo.
{30136}{30202}Dobro. Jer nije zabavno|ako nas nije dvoje.
{30237}{30330}Dobro, otiæi æu tamo|slijedeæi tjedan, ili... ne znam.
{30332}{30379}Dobro, tjedan.
{30381}{30483}Gledaj, ovo nije neka šojka |slomljenih krila.
{30484}{30571}Uhvati je u nekoliko onih|velikih, debelih laži koje toliko voliš.
{30572}{30627}Pa mi reci što onda misliš o njoj, dobro?
{30685}{30735}Radite li vi, deèki, što ovaj vikend?
{30737}{30827}Da. Mislio sam je voditi|na snimanje "Èudaka".
{30869}{30949}- Što je to, film?|- Zaboravi.
{30951}{31021}Izlaziš li veæ jednom|ili da ti proslijedim sve pozive.
{31023}{31094}Izlazim. Oh, sranje.
{31096}{31135}Dobro. Požuri.
{31294}{31328}Evo ti.
{31456}{31512}Misliš da ima još tko u uredu?
{31514}{31548}Sigurno.
{31625}{31694}Koja je razlika izmeðu|golf lopte i G-toèke.
{31696}{31730}Ne znam.
{31732}{31806}Zato što potrošiš 20 minuta|tražeæi golf lopticu.
{31808}{31875}Taj je dobar. Da.
{31876}{31948}- Neki tip odozdo mi je to isprièao.|- Da, smiješno je.
{31949}{32015}Moram odnijeti ove|prije no što bude kasno.
{32017}{32076}Bar su nam mogli dati|nešto uredske opreme.
{32078}{32139}Ne jebi.|Mi smo ovdje kao Lewis i Clark.
{32140}{32191}Nazvat æu ih|da znaju da dolazimo.
{32193}{32228}Hvala.
{32957}{33029}Halo. Dobar dan, trebam Christine.|Ovdje Chad.
{33062}{33098}Oh, jesi?
{33139}{33173}Pa, hvala.
{33212}{33259}Ne. Ne bih se sjetio.
{33296}{33392}Ne, gospoðo. Samo joj recite da je svima|zaista žao što je bolesna.
{33423}{33499}Vjerojatno gripa vlada|ovih dana.
{33660}{33708}Nadam se da æe joj uskoro biti bolje.
{33861}{33908}Je li dobila cvijeæe?
{33938}{33972}Užasno.
{34021}{34096}Ne, samo smo malo prikupljali.|Ništa strašno.
{34119}{34153}Da, gospoðo.
{34237}{34332}Ne, radije je nemojte buditi.|Samo joj recite da sam zvao.
{34411}{34449}Dobro, još jednom hvala.
{34496}{34537}Hoæu. I vi takoðer.
{34557}{34592}Ok, bok.
{34985}{35104}Htio sam reæi da mislim da je|sve u što se upuštaš business.
{35106}{35212}Tvoje tipkanje ili moja prilika|da upravljam ovim projektom.
{35213}{35272}Nema veze.|Svaki dio života je industrija.
{35274}{35320}Od djeèje skrbi nadalje.
{35322}{35391}Trebamo izvuæi korist|iz situacije u kojoj se nalazimo.
{35393}{35443}Tako bar ja mislim.
{35446}{35541}Znaš, preokrenuti situaciju|u našu korist, napredak.
{35544}{35624}Stoga, na osobnoj razini,|to je ono što ja ovdje radim.
{35626}{35708}Prolazio sam, vidio te,|pomislio, "Zašto ne?", znaš?
{35710}{35815}Vjerojatno imaš deèka|ali moraš zgrabiti priliku, zar ne?
{35837}{35871}I tko zna...
{35873}{35944}možda ispadne|obostrana korist.
{35980}{36068}Dakle, to je stvarno samo|jako daleko da bi sada upropastio.
{36070}{36118}Volio bih izaæi ponekad.
{36120}{36169}Možda piæe?
{36197}{36255}Ja sam Howard, usput.
{36257}{36316}Slobodan sam ovaj vikend.
{36384}{36456}Bok, Howard, trebam|te na sekundu.
{36486}{36540}Vratim se za minutu.
{36562}{36623}- Što to radiš?|- To nije ona.
{36625}{36687}- Što?|- To nije Christine
{36689}{36764}- Rekao si èetvrta soba.|- Nije ovdje, hajde.
{36766}{36810}Idemo!
{36812}{36878}- Ali pozvao sam ju van.|- Tko ju jebe, idemo na sendviè.
{36880}{36914}Hajde!
{37031}{37111}I otišao sam odatle najbrže što sam mogao.
{37113}{37214}Èim sam navršio 18, otišao sam|najdalje što sam mogao.
{37270}{37353}Moja braæa....|Imam dvoje starije braæe...
{37355}{37449}oba su dobila sindikalnu karticu|dan nakon mature.
{37451}{37489}Ali ne ja.
{37511}{37557}Moj otac to nije vidio.
{37559}{37643}Mislio da je to najveæa stvar.|Krizanteme i ostalo.
{37645}{37687}Nije mu bilo dosta.
{37689}{37779}Cijela stvar sa Normanom Rockwellom.|Crkva, obitelj, oba roditelja...
{37781}{37843}mala kuæa u predgraðu,|i odmah si u raju?
{37887}{37958}Bio sam spreman za fakultet|u devetom razredu.
{38017}{38079}Još uvijek misle da sam lud|što živim u gradu.
{38080}{38155}Ozbiljno, jednostavno nisam želio|niti jedan dio toga.
{38157}{38265}Tada dolazi školarina zbog baseballa.
{38267}{38342}Da. Druge godine fakulteta sam strgao ruku.
{38369}{38452}Tada sam dobio i |poslovnu diplomu.
{38454}{38539}Upao u posao|i volio ga.
{38572}{38610}Ništa strašno.
{38630}{38688}To sam ja, u ljusci.
{38770}{38840}Prièaj mi o sebi.
{38892}{38951}Viðaš li se s kim?
{38990}{39039}Nikim?
{39106}{39181}Ne moraš pisati, samo reci.|Dobro govoriš.
{39204}{39263}Stvarno. U redu je.
{39464}{39567}Pa, živimo u ovom gradu|veæ nekoliko godina.
{39604}{39711}Moja obitelj se èesto selila|kad sam bila mala.
{39745}{39805}Otac je bio u vojsci.
{39845}{39959}Kada je umro od raka, preselili smo se|ovdje
{39960}{40009}moja majka i ja.
{40048}{40082}U njezin rodni grad.
{40138}{40221}Sestra živi u Seattleu.
{40224}{40270}Tamo ide u školu.
{40384}{40487}Ne znam što još|te zanima o meni.
{40541}{40607}Sestra, ha? To je odlièno.
{40666}{40714}Imaš li možda sliku?
{40916}{40954}Mrzim ovog tipa.
{40972}{41032}I ovog isto.
{41035}{41084}Mali gad.|Jesi ga ikad upoznao?
{41087}{41133}- Ne.|- Imaš sreæe.
{41179}{41225}Oh, i mrzim ovog tipa ovdje.
{41262}{41342}Craig ili Greg?|Jedan od njih je iz Pittsburgha.
{41344}{41382}On puši kurce.
{41517}{41552}Kako je?
{41553}{41619}- Dobro. Nisam te vidio još od...|- New Jersey, onog seminara.
{41621}{41719}Èuo sam da su te ovdje smjestili...|Èovjeèe, ovo je lijepo.
{41721}{41785}Da, tko bi rekao.|Kada su te poslali ovdje?
{41787}{41841}Prije deset dana.|Vježbam na novom DATCOM sustavu.
{41844}{41918}- Oh, super.|- Znam ju. Pogledaj facu.
{41920}{41962}- Cunt?|- Oh, da.
{41964}{42027}Da, je.|Kako god...
{42028}{42107}Vi ste tu da dovršite|Computech, zar ne?
{42109}{42164}- Aha. Unutra i van, šest tjedana.|- Mora biti lijepo.
{42166}{42256}Onaj tip s kojim si. Što njega muèi?|- Ne mogu ga još proèitati.
{42258}{42352}Dobar je. Samo što je|prvi put odgovoran, pa, znaš.
{42354}{42408}- Èini se dobar.|- Da, ništa strašno.
{42410}{42494}I, deèki, jeste li veæ poèeli|sa noænim izlascima?
{42496}{42550}Da, sinoæ smo jeli u Arby's-u.
{42580}{42634}- Oh, èovjeèe.|- Što?
{42636}{42745}Prezirem tog tipa. Trgovaèki predstavnik iz|Indiane? Veliki seronja. Sjeæaš se.
{42748}{42815}Da. Laurence.|I on je bio gore.
{42816}{42863}Toèno. Laurence.
{42864}{42948}On je nova vrsta seronje.
{42950}{43016}Posebni deformirani seronja.
{43018}{43067}Mrzim tog pederskog pušaèa kuraca.
{43069}{43149}Bez šale. Èuvajte stražnjice|ako doðe gore.
{43151}{43186}Doslovno.
{43188}{43244}Moram iæi.|- Bilo mi je drago.
{43246}{43280}I ti.
{43311}{43354}- Voliš tog tipa?|- Njega?
{43356}{43417}- Da.|- Šališ se? Mrzim tog kretena.
{43965}{44045}Dobro. Stanka je gotova.
{44047}{44101}Svi ste otpušteni.
{44103}{44186}Šalim se. Dobro je imati vas deèke odozdo|gore. Cijenim vašu pomoæ.
{44188}{44294}Oprostite zbog loših uvjeta ovdje|popravljaju štetu od vode.
{44296}{44356}Chad to zove...|Svi ste upoznali Chada, zar ne?
{44358}{44405}On to zove našim Jonestown uredom.
{44438}{44517}- Bilo je smješno kada je on rekao.|- To je zato što sam rekao "Jamestown."
{44519}{44635}Ok. Jamestown. Dakle, ovo je|najveæi kat koji su nam mogli dati...
{44637}{44711}sa raèunalima i|svime što nam je potrebno.
{44712}{44815}Znaèi izdržat æemo. Vidimo se kasnije.|Koji je najbolji naèin da ovo izvedemo.
{44817}{44883}Podijelimo se u dvije ekipe.|Iæi æemo prva, druga, prva...
{44884}{44972}Mislio sam da ti želiš obaviti|projekcijski dio.
{44974}{45045}Toèno. Tko ima te grafove?
{45082}{45131}Pogledajmo ih.
{45133}{45183}- Nije ozbiljno.|- Da?
{45185}{45268}- Ah, samo se viðamo, znaš?|Dobro.
{45270}{45335}- Izveo sam ju na ruèak nekoliko puta.|- Da.
{45337}{45408}Vidim ti kolegu dolje za stolom|svaki drugi dan.
{45409}{45503}Èuo sam da ju je vodio u kino.|Hajde. Nešto se dogaða.
{45504}{45585}Što? Veæinom je poslovno.|Tipka nešto za nas.
{45612}{45666}Oboje smo ju izveli van.|Ništa strašno.
{45668}{45711}- Naravno.|- Nije.
{45712}{45780}- Ok, ne tièe me se.|- Toèno.
{45834}{45925}Slušaj, vjerojatno znam... Ali|Kažem ti istinu. Nije ništa.
{45955}{46003}- Samo sluèajnost.|- Ok.
{46006}{46091}- Ona je dobra djevojka.|- Hej, skidam ti kapu.
{46093}{46140}Veæi èovjek od mene.
{46185}{46252}Tebi nije slatka?
{46254}{46316}- Je.|- Ozbiljno. Ima lijepo tijelo.
{46318}{46365}- Apsolutno.|- Ali?
{46404}{46479}Ti ne bi želio da te niti mrtvog|uhvate s njom, zar ne?
{46481}{46580}U ovakvoj tvrtci,|sa ovakvim ljudima...
{46582}{46618}nema jebene šanse.
{47233}{47273}Halo? Da, bok.
{47275}{47321}Je li Christine doma?
{47348}{47436}Ne. Dobro.|Ne, nemam poruku.
{47458}{47513}Imate li vi možda jedan od onih telefona...
{47515}{47650}Mislim, može li ona kako znati što|ja prièam? Kako to...
{47652}{47711}Oprostite. Oèito nije niti važno.|Prièam preko vas.
{47712}{47783}Možemo prièati preko vas, zar ne.|Samo sam znatiželjan.
{47820}{47902}Oh, imate? U redu, hvala.|Pa, samo joj recite...
{47986}{48096}Oprostite. Uredska zabava.|Netko odlazi u mirovinu.
{48098}{48139}Èak ne znam ni tko.
{48140}{48223}Možete li prièekati sekundu?|Odmah se vraæam.
{48253}{48304}Halo? Što?
{48342}{48425}Ne, provjerio sam osobno|prije no što sam poslao.
{48428}{48494}Dobro si predložila|da doðemo tu.
{48496}{48547}Nisam èak ni znao za to mjesto.
{48657}{48723}Hvala što si mi ga pokazala,|Christine.
{48724}{48759}Molim.
{48894}{48990}I izvukla si me sa oproštajne|zabave nekog tipa. Cijenim to.
{49107}{49199}Samo provjerite i nazovite me.|Siguran sam da su tamo.
{49223}{49270}Samo provjerite. OK?
{49314}{49399}Halo? Oprostite?
{49401}{49506}Svejedno, pokušao sam je uloviti prije|no što je otišla, ali ju nisam našao.
{49508}{49576}Ne, ništa strašno.|Ne...
{49657}{49704}Pa, bilo mi je drago...
{49764}{49812}Ne, ja sam Howard.
{49815}{49869}Sve je u redu.
{49872}{49946}Samo sam želio riješiti|neke uredske stvari.
{49948}{49984}Ništa strašno.
{50020}{50059}Ne, nemam poruku.
{50101}{50135}U redu.
{50170}{50204}Laku noæ.
{50311}{50368}Da li ti...
{50370}{50421}ne želim da ti bude neugodno, ali...
{50480}{50524}Ne, zaboravi.
{50526}{50586}Ne, u redu je. Stvarno.
{50652}{50749}Razmišljao sam o kinu|u koje si me vodila...
{50752.}{50798}- Sjeæaš se, kino.|- Da.
{50875}{50979}Kada sam ga ukljuèio, zvuènik,|stavio sam ga na svoju stranu...
{50980}{51035}Pretpostavio sam da ga neæeš|trebati jer...
{51075}{51121}- Ima li smisla?|- Da.
{51123}{51182}- Ne, nema. Zvuèim kao idiot.|- Ne.
{51240}{51339}- Jesam li ga trebao staviti na...|- Ne, bilo je dobro.
{51340}{51375}Sigurno?
{51417}{51509}Onda, kako ti...|Osjetiš li zvuk ili...
{51560}{51607}Zaboravi. Oprosti.
{51608}{51683}Ne. Ljudi su znatiželjni.|U redu je.
{51708}{51782}Vidjela sam veæinu filmova|na televiziji.
{51784}{51839}Èitam im s usana.
{51840}{51912}Pomaže što su im usta|50 stopa visoka.
{52064}{52099}To je užasno.
{52125}{52173}Oprosti što sam pitao.
{52199}{52233}U redu je.
{52910}{52977}- Pokušaj naruèiti govedinu ovdje.|- Toèno.
{53003}{53092}Ne mogu ostati dugo. Svi su veæ|naruèili.
{53095}{53133}- Imate puno posla?|- Bože, da.
{53136}{53215}- Radio sam na prezentaciji.|- Neæeš vjerovati.
{53217}{53273}- Znaš onog novog tipa?|- Kojeg?
{53275}{53365}Onoga, gospodina MBA, doma.|Veæ je zajebo, jako.
{53367}{53433}- Pazi na njega. Rekao sam ti.|- Dobro.
{53435}{53527}Sve ono što si mu faksirao|prošli tjedan. Odjednom ne može pronaæi.
{53548}{53599}- Šališ se.|- Ne.
{53600}{53675}- Našao je oko dvije stranice.|- Sranje.
{53676}{53747}- Stavio sam izvještaj o primitku|na oglasnu ploèu. Možeš provjeriti.
{53748}{53814}Znam da jesi.|Možeš mi dodati ubrus?
{53816}{53891}- Samo nas sramoti.|- On je taj koji je zajebao.
{53894}{53983}Nije nas izvijestio.|Sada razbacuje sve po uredu.
{53985}{54031}- Dobro mu služi.|- Da, ali ja sam onaj koji...
{54033}{54094}æe u ponedjeljak ujutro doæi sa stvari|koja æe visiti iz hlaèa.
{54096}{54166}Kopija mi je još uvijek na stolu,|svi pitaju zašto.
{54192}{54247}Trebao sam to imati na cd-u.
{54248}{54344}- Predložio sam to.|- Znam. Moja krivnja.
{54388}{54486}Naæi æemo danas. Ništa strašno|samo ne planirano.
{54580}{54615}Onda...
{54633}{54669}Kako Christine?
{54672}{54708}- Dobro.|- Da?
{54711}{54757}Oh, da. Ti?
{54759}{54817}Dobro. Poslao sam joj cvijeæe.
{54858}{54930}Da?|Smiješno. I ja.
{54972}{55050}Ja ne biram kineske uzorke|ili tražim kuæu snova
{55052}{55100}ali je dobro.
{55128}{55187}Zapravo je jako zabavno.
{55189}{55227}I ja mislim.
{55304}{55363}Dakle, tebi se više sviða?
{55395}{55432}Ne znam. Više?
{55478}{55550}Nisam siguran.|Samo jako èesto...
{55553}{55619}pogledam tamo i pomislim
{55620}{55695}"Znaš,  pomalo i vidim sebe|u toj osobi."
{55697}{55816}Mislim, ne kada prièa. Onda|samo želim pobjeæi niz ulicu
{55817}{55924}u nadi da je nitko nije èuo kako žvaèe|jezik pokušavajuæi napraviti reèenicu.
{55926}{56003}Ali nekoliko puta...|Možda je pogled ono što mi daje,
{56056}{56160}ili taj osjeæaj|kada mi dotakne ruku...
{56162}{56200}Samo ju stisne.
{56244}{56311}Mislim, zaboga, dijelimo èašu Slurpy-a.
{56313}{56403}Ne znam.|kada ju pogledam..., takvi trenutci.
{56405}{56517}i vidim, znaš,|djecu i Volvo u garaži
{56519}{56569}i sva ta popratna sranja.
{56616}{56703}- Definitivno nešto ima...|- Ozbiljno? Mislim, to je...
{56704}{56783}Ne mislim baš to...|Ah, dovraga, ne znam više.
{56784}{56856}I ti si bio vani s njom.|Osjeæaš li i ti to?
{56857}{56895}Samo povremeno.
{56921}{56979}- Ti?|- Naravno, na neki naèin.
{57083}{57126}Stvarno?
{57128}{57246}Da, valjda.|Nekako je dobra.
{57248}{57282}Znam.
{57312}{57359}Uzevši sve u obzir - èudan je ona|vrtuljak.
{57360}{57403}To je istina.
{57404}{57455}Da, samo vidi kako ide, valjda.
{57456}{57503}Da.
{57504}{57587}Vijugava je cesta|kojom putuje život.
{57588}{57647}- Vidi gdje je nas dovela.|- Ok.
{57730}{57806}- Je li dobar sendviè?|- U redu je.
{57808}{57858}Nekako te zajebu na mesu.
{57888}{57926}Da, istina.
{58157}{58230}Mislim da si rekao da je tvoj prijatelj|dobar deèko.
{58232}{58299}- Je.|- Zašto me onda šalje u Bozeman?
{58301}{58335}Montana?
{58337}{58414}Èetvrtosrpanjski vikend|a ja idem u Big Sky zemlju.
{58416}{58481}Želi da budem na nekoj konvenciji|da vodim kiosk.
{58483}{58517}Ajme.
{58519}{58585}- Stvarno pušiona. Imao sam nešto drugo u planu.|- Reci mu.
{58587}{58648}Veæ sam mu poslao e-mail.|Odgovorio mi je to.
{58651}{58710}Neki novi super sustav, sranje.
{58713}{58780}Što da ti kažem? Moæ kvari.
{58782}{58871}Prava nepravda ovdje je|da kada bih mogao baciti felšanu loptu
{58872}{58920}znaš, stvarno dobru,
{58922}{59020}samo to, ništa drugo, bez škole|ièega... ništa od ovog ne bi bilo važno.
{59022}{59118}Igrao bih u velikim klubovima deset godina|i otišao u mirovinu u Oahu.
{59120}{59167}Da?  Život je pušiona.
{59208}{59243}Slušaj.
{59308}{59343}Zabavi se.
{59463}{59529}Hej. Oprosti.
{59531}{59595}Zadržao sam se baš na odlasku.
{59597}{59715}Prošli smo rok. Morao sam urlati|na nekoliko odgovornih...
{59717}{59787}Oprosti. "urlati"?
{59789}{59843}"Urlati"... vikati.
{59884}{59930}Derati se.
{59932}{60042}- Oh, žao mi je.|- Ne, u redu je. Sve je dobro svršilo.
{60044}{60137}- Dakle...|- Ne, žao mi je za te ljude.
{60139}{60258}Žao mi je što su pogriješili.|Znam da ti je projekt vrlo važan.
{60260}{60321}Sigurno su se osjeæali grozno.
{60324}{60383}Da. Mislim ne.
{60384}{60431}Nije bilo ništa strašno.
{60433}{60546}Samo sam im objasnio gdje|su pogriješili.
{60548}{60620}Ali to me malo zadržalo.
{60645}{60696}Oh, nema veze.
{60698}{60732}Hvala.
{60843}{60881}Ovo je lijepo.
{60932}{60986}Hej. Ovo je jako lijepo.
{60988}{61075}Mislim za takvo mjesto...|grad ove velièine.
{61077}{61183}Da. Jako mi se sviða,|tako je tiho.
{61231}{61265}Da.
{61308}{61343}Onda, to mora...
{61388}{61471}- Gledaj, žao mi je.|- Zbog èega?
{61473}{61529}Što sam malo prije napravio.
{61531}{61614}Došao sa|"bio sam zauzet" sranjem.
{61636}{61691}Dakle nisi bio zauzet?
{61693}{61771}Pa ne. Mislim da, jesam,|ali nisam.
{61772}{61883}S... Izmislio sam to.
{61886}{61932}O discipliniranju one dvojice?
{61934}{62021}To sam izmislio|umjesto da sam rekao istinu.
{62023}{62079}Trèao sam natrag u hotel|presvuæi majicu.
{62080}{62147}Želio sam izgledati dobro|zato sam kasnio.
{62203}{62299}- U redu je.|- Ne, nije.
{62336}{62413}Navikao sam se govoriti ono|što mislim da ljudi žele èuti.
{62415}{62505}Zaboravio sam da možda|ponekad valja reæi istinu.
{62507}{62590}- Zato mi je žao.|- Sve je u redu. Stvarno.
{62617}{62695}- Opraštaš?|- Naravno.
{62698}{62792}Samo zapamti:|Ne èujem te kada lažeš.
{62831}{62866}Naravno.
{62869}{62942}- Pošalji obavijest.|- Da, naravno.
{63032}{63106}- Dobar savjet. Hvala.|- Molim.
{63163}{63242}- Izgledaš dobro.|- Ne.
{63244}{63283}Oh, pocrvenio si.
{63321}{63395}Drago mi je da si došao.|Bez obzira kasnio ili ne.
{63460}{63581}Oh, pogledaj.|Tako su lijepe, zar ne?
{63584}{63618}Da.
{63939}{64055}U redu, jer željeli bi stol|okrenut prema vodi.
{64057}{64160}Gledam u brošuru koju ste nam poslali.|Tako bi zapravo željeli.
{64204}{64242}Hvala.
{64245}{64293}Hej, imam ideju.
{64296}{64423}Ako prenesemo okomite komande|mislim da možemo zaobiæi...
{64424}{64499}Znaš što? Neka prièekaju|deset minuta. Doæi æu im objasniti.
{64525}{64567}Žao mi je.
{64568}{64632}Razmišljamo da odemo na|užinu.
{64634}{64697}15:30, 16:00, tako nešto.|Što god imate.
{64723}{64777}Trebam za utorak.
{64779}{64906}Ne, rezervacija je za èetvrti u mjesecu.|Možete li prièekati?
{64908}{64996}Upute za korištenje.|Dobro, moram ih uzeti.
{65060}{65095}Oprostite.
{65160}{65245}Znam da je to samo jezero,|ali pogled u ovo doba godine...
{65247}{65302}prilièno oèaravajuæ, zar ne.
{65388}{65484}Može. Imate broj moje kartice,|zar ne? Možete mi poslati potvrdu?
{65486}{65586}Moram iæi. Dobro. Bok.
{65588}{65691}Hej. Izgleda da možemo iæi|za tjedan dana, u subotu.
{65693}{65742}Mislim, ako još uvijek želiš.
{65744}{65843}Raspitao sam se. To je navodno|jedan od najljepših restorana u mjestu.
{65880}{65965}Pa, da, vjerojatno.
{65988}{66056}Moram samo provjeriti...
{66058}{66096}Mislim da mogu.
{66125}{66167}Trebala bih se vratiti.
{66168}{66287}Hej, želiš da zgrabimo nešto za ruèak?|Mislim, samo ako želiš.
{66288}{66362}Ima nekoliko stvari o|kojima bih želio razgovarati.
{66364}{66452}Možemo li pred kraj tjedna?
{66454}{66558}Danas je loš dan. Dospjelo je mnogo izvješæa.|Kraj je mjeseca, znaš.
{66560}{66634}Naravno. Ne, samo sam pitao.
{66724}{66785}Imaš lijepu haljinu.
{66828}{66887}Izgledaš dobro.
{66970}{67004}Hvala.
{67028}{67115}Mislim, pristaje ti taj stil.
{67116}{67230}Vjerojatno zvuèi glupo kada kaže tip|poput mene, ali kužim se u to.
{67232}{67270}Stvarno kužim.
{67588}{67636}Izgledaš dobro.
{67858}{67924}- Je li sve u redu?|- Da.
{67926}{68015}Ovdje je odlièan roštilj|navodno. Jedan od najboljih u gradu.
{68016}{68051}Da, je.
{68352}{68399}Hej...
{68401}{68495}Razlog zbog kojeg sam te pozvao...|Želio sam razgovarati o nama.
{68497}{68543}Samo razgovarati.
{68648}{68719}Moram to reæi,|dati sve na vidjelo.
{68840}{68897}Mrzim ovaj dio sudara.|Uvijek je težak...
{68899}{68977}kada poèneš nešto osjeæati|prema osobi...
{68979}{69046}zaželiš|otiæi korak dalje.
{69075}{69130}Znaš što pokušavam reæi?
{69132}{69178}- Moje karte su na stolu.|- Da.
{69236}{69290}Tako si lijepa.
{69454}{69564}Moram se suoèiti s tim.|Moj posao je gotov ovdje za nekoliko|tjedana, i...
{69588}{69673}želim da znaš da što god uèinila|ne smeta mi.
{69675}{69726}Ne brine me niti|kuda izlaziš niti s kim...
{69728}{69805}i ako smo razdvojeni na neko vrijeme
{69883}{69939}Samo želim da znaš da
{69984}{70065}što god se dogodilo, vjerujem ti.
{70084}{70134}Dobro?
{70166}{70219}O Bože, ovo je teško.
{70324}{70359}Volim te.
{70398}{70483}Evo, rekao sam, izašlo je.|Sada æu bolje jesti.
{70485}{70525}Istina.
{70552}{70603}Pogledam te i vidim...
{70654}{70702}dobrotu, ljubaznost...
{70740}{70800}I jako sam sretan uz tebe
{70803}{70899}i želim našu vezu...
{70901}{70947}Misliš da bi mogli imati|vezu...
{70949}{70983}zar ne?
{71050}{71137}I želim ju njegovati i odgajati|dok ne procvjeta.
{71311}{71362}To sam želio reæi...
{71406}{71508}sada možemo uživati u ovome, i baš sam|nekako raspoložen za rebrica.
{71724}{71759}Kako si?
{71794}{71857}Chris, znaš li Howarda?
{71859}{71918}Vidio sam ju. Bok.
{71920}{71987}Howard je glavni|za projekt na kojem radim.
{72056}{72132}- Christina je tajnica na treæem katu.|- Oh, stvarno?
{72134}{72180}Da. To je za krepat od smijeha.
{72182}{72310}Odjednom te posvuda vidim.|Znaš kako je to, Christine.
{72312}{72386}Howard i ja imamo isti godišnjak.
{72388}{72446}Diplomirao je semestar prije mene i|sada mi je šef.
{72448}{72524}- Samo na ovom projektu.|- Hajde.
{72526}{72605}Ne budi skroman. Izabrali su tebe|od svih. Ti si taj.
{72634}{72718}- Imaš vremena sjesti?|- Ne, ne mogu.
{72752}{72822}Moram se vratiti gore.|Stiglo je mnogo izvješæa.
{72824}{72882}Kraj mjeseca, znaš.
{72924}{72962}Šteta.
{73058}{73092}Oh, kvragu.
{73132}{73219}Moram ovo odnijeti. Oprosti.|Isprièajte me.  Odmah se vraæam.
{73347}{73380}Stvarno mi je žao.
{73421}{73467}U redu je.
{73469}{73539}Sigurno voliš ovo mjesto.
{73560}{73648}Ne. Veæ je bio napravio planove.
{73650}{73688}Ništa strašno.
{73723}{73757}Trebao bih...
{73821}{73917}Oprosti mi. Ja još...
{73939}{73973}U redu je.
{74221}{74279}Kuda je otišao Howard?
{74281}{74327}Rekao je da mora iæi.
{74360}{74461}Je li vi dvoje...|Mislim, radite zajedno.
{74463}{74564}Da. Ja radim veæinom marketing.|Howard upravlja svim odjelima.
{74566}{74667}Znala si to, zar ne? Šestero nas je|došlo ovdje zbog tog projekta.
{74670}{74796}Ne. Toliko ljudi doðe i ode.|Nisam znala.
{74796}{74848}Ništa strašno.|Sada znaš.
{74871}{74927}On je dobar tip.
{74929}{75039}Vraški tip, stvarno|pošten èovjek, mislim.
{75041}{75093}Ozbiljno, trebala bi|ponekad razgovarati s njim.
{75124}{75193}Da. Uvijek sam volio Howarda.
{75195}{75269}Svejedno, želiš predjelo?|Može?
{75271}{75321}Tako sam gladan.|Mogao bih jesti zauvijek.
{75534}{75598}Ona soba dolje je|totalno...
{75619}{75668}Izlazeæi odande...
{75670}{75716}veæ si bio u wc-u.
{75718}{75823}Vidim tri interna kako se šuljaju naokolo|kao u nekom ljetnom kampu, ili borbi hranom.
{75824}{75915}To me razljuti.|I onda još odvuku svoje sranje gore.
{75917}{75964}Da. Razgovarat æu s njima.
{75966}{76035}Bože, prekrasan je pogled.|Kako si našao ovo mjesto?
{76063}{76128}Kako-se-zove Christine.
{76130}{76206}Maloljetni kurconje|ostavljaju takvo mjesto.
{76208}{76277}Rade u društvu muškaraca,|i još uvijek žele svoje mame
{76279}{76330}da im brišu stražnjice|svaki put kada idu kakati.
{76332}{76404}- Imamo dvije kante za smeæe dolje,|- Toèno.
{76407}{76473}Èovjeèe, to me tjera da...|Ne znam.
{76475}{76540}- Kad ste vas dvoje došli?|- Trebali bi biti primjer...
{76572}{76674}Da, u pravu si.|Ah, svejedno veæ imam puno posla.
{76708}{76811}Znam. Govorim teoretski da bi|trebalo nešto napraviti.
{76812}{76883}Doma, to ne izgleda tako
{76884}{76944}i to ih treba nauèiti.
{77065}{77135}- Samo puštam paru. Ništa strašno.|- Naravno.
{77178}{77243}- I, kako ide?|- Dobro. Puno posla.
{77245}{77301}- Da?|Da, klijenti, znaš.
{77303}{77398}- Ali ipak sve u zadanim rokovima.|- Hej, cijenim to.
{77400}{77493}Želio bi to sve srediti|do praznika.
{77495}{77627}Znam da je u zadnji èas, ali možeš|li možda odletjeti nazad tijekom praznika
{77629}{77691}dostaviti nešto,|napraviti prezentaciju.
{77693}{77798}Mislim, ako se slažeš.|Žele znati što smo radili.
{77800}{77915}- Mislio sam da si ti trebao iæi nazad.|- Jesam, ali se stvari ovdje gomilaju...
{77916}{77963}Kakve? Vikend je.
{77964}{77999}Pa, stvari.
{78000}{78067}Zašto ne pošalješ Johna.|On æe odmah otiæi.
{78068}{78187}Bi, ali ne poznaje|grad niti ljude tamo.
{78188}{78307}Mislio sam da bi im ti mogao "prodati"|promjene koje smo stavili u paket.
{78308}{78370}Mislim, ako je u redu.
{78412}{78458}- Ako nije...|- Naravno. Ja sam zarada.
{78460}{78559}Nema praznika. Ostavi|na stolu. Uzet æu u petak.
{78560}{78638}Odlièno. Ja æu se pobrinuti za stvari|ovdje.
{78640}{78736}U ponedjeljak æemo zajedno|pregledati sve. Cijenim to.
{78739}{78834}Mislio sam voditi Christine|na utakmicu ili nešto. Vatromet.
{78837}{78912}- Grad poput ovoga to mora "pojesti".|- Da, izvini zbog toga.
{78914}{78975}Znaš, posao na prvom mjestu.
{78977}{79036}Smisli nešto, dobro.|Zadrži ih vruæe.
{79038}{79146}- Nastojat æu. Vjerojatno æu biti zatrpan.|- Da, sa stvarima.
{79148}{79223}Svejedno. Imamo još malo|do velikih finala.
{79285}{79378}Slušaj, u vezi ruèka, malo prije...|Nisam imao pojma da si ti planirao...
{79379}{79434}- Jesi, zar ne? Taj pogled.|- Nema problema.
{79436}{79499}- Ozbiljno. Žao mi je.|- Ne brini.
{79502}{79584}Nije ti rekla da sam ju ja planirao|izvesti, zar ne?
{79586}{79625}To sam i mislio.
{79684}{79755}Trebali bi biti oprezniji,|sada kada nas zna.
{79757}{79860}Znaš što mislim?|Možda bi se jedan od nas trebao povuæi.
{79887}{79925}Da, možda.
{79955}{80007}- Tko bi to bio.|- Oh, svejedno.
{80009}{80103}Samo ne želim biti previše oèit.
{80105}{80151}Naravno.  Ili biti uhvaæen.
{80188}{80253}Sve u redu, onda?|Ne premišljaš se ili nešto...
{80256}{80303}- Ne, ne, nikako, ja sam još uvijek...|- Dobro.
{80362}{80420}Ti ?|- Da.
{80509}{80578}Jesi li se možda ponovno|èuo sa onom svojom djevojkom?
{80579}{80622}- O da.|- Bez šale.
{80624}{80710}- Da. Zove moju mamu.|- Auh.
{80712}{80812}I dobivam te poruke|na "sekretarici", bez glasa, samo tišina.
{80814}{80902}Nema nimalo dostojanstva|da me direktno nazove. To me razljuti.
{80904}{80962}- Daj joj priliku, kupi zvono.|- Ta kuèka.
{80963}{81016}Vrate se nazad|kada bude kasno, ha?
{81048}{81094}Zove moju majku, mislim...
{81130}{81185}Vidio sam gdje si ti dobio poruku prošli tjedan.
{81187}{81233}- Što?|- Od Suzanne.
{81259}{81315}Oh, da. Ti u to vjeruješ?
{81316}{81382}Nisam šnjofkao.|Vidio sam na tvom terminalu.
{81384}{81480}Nikada mi nije odgovorila na poziv.|- Vidiš, o tome ti prièam.
{81482}{81548}- Znam.|- Poèneš žaliti nekoga....
{81550}{81588}kao Christine...
{81590}{81660}i onda se vrate|i izbiju ti zube.
{81692}{81764}Žene. One dobre su|najhladnokrvnije.
{81766}{81845}Na kraju nije ni bitno.|Iznutra su sve iste.
{81848}{81966}Meso, kosti, srce...|Samo polagano vriju...
{81968}{82065}Ja, morao sam ih imati sa|svim njihovim sranjima. Znaš što mislim?
{82067}{82148}Ponekad me tjera na...|Nešto.
{82180}{82214}Naravno.
{82664}{82710}Volim se viðati s tobom izvan tvrtke.
{82739}{82786}Nikada prije to nisam radila.
{82852}{82895}Sviða mi se tvoja soba.
{82918}{82951}Da, stvarno?
{83108}{83178}Bože, tako sam obuzet tobom.|Samo...
{83235}{83281}Obuzela si me.
{83311}{83383}Završio sam.|Vjerojatno zvuèim glupo.
{83385}{83434}Meni zvuèiš prekrasno.
{83760}{83798}Tako si krhka.
{83852}{83914}Ne mogu si niti zamisliti|da nisi tu sa mnom.
{83943}{83994}Tako te divno grliti.
{84144}{84214}Još uvijek ne mogu vjerovati|da neæu biti ovdje èetvrtoga.
{84216}{84289}- Stvarno sam želio.|- Znam.
{84292}{84374}Moraš raditi.|Nisi ti kriv.
{84377}{84423}Da. Svejedno je sranje.
{84672}{84719}Trebali bi se vratiti na posao.
{84845}{84890}- Chad.|- Što?
{84942}{84975}Voliš li me?
{85043}{85119}- Žao mi je.|- Ne.
{85155}{85189}Što?
{85239}{85308}Mislim da te volim|i samo bih željela...
{85389}{85449}Da, volim te.
{85762}{85874}Ne, ne želim procjenjivati.|Želim to prodati.
{85876}{85931}Samo to želim riješiti.
{85932}{85998}Možda bi mogli pogledati otraga...|Nekako je labav.
{86092}{86144}Znam.
{86146}{86218}Završili smo praktièki èupajuæi|prsten s njenog prsta.
{86220}{86275}Prvo ga nije željela.
{86276}{86347}Nekoliko tjedana kasnije nije|mi ga htjela vratiti.
{86348}{86418}"Samo ga želim isprobati".
{86419}{86490}Završili smo hrvajuæi se|na njenom podu jedne veèeri...
{86491}{86559}ja, vuèem je za ruku,|ona, vrišti.
{86560}{86615}Susjedi na vratima.|Totalna zbrka.
{86688}{86767}Zato je malo i savijen.
{86769}{86863}K tome nosio sam ga u|lisnici još mjesec dana.
{86865}{86954}Samo ga ispolirajte,|provjerite da je sve u redu.
{86987}{87035}Ja æu malo pogledati vaše vaze.
{87315}{87385}To je sramota.|Eto što je to.
{87387}{87430}Znam.
{87432}{87515}- Vi imate privilegije. Jeste primijetili?|- Naravno.
{87517}{87634}Nemoj "naravno" i pokazati mi srednjaka,|na odlasku van.
{87635}{87713}Želim da to znaš jer je|istina, a ne zato što neki tip...
{87715}{87770}ovaj put ja, ali i bilo tko drugi
{87772}{87839}jer neki èovjek kaže da je u redu.
{87840}{87928}Mogao sam samo preæi preko toga.|Svejedno sam sutra na putu.
{87930}{88001}Dati ti da vidiš kako je u životu|biti malo sam.
{88003}{88104}Time bi ti samo naštetio.|Stvarno bih.
{88106}{88200}Ne serem.|Poštuj ovo.
{88202}{88298}Gledaj, vi deèki sjedite|za volanom.
{88300}{88401}Možete ostvariti sve što zaželite.|U ovoj ste tvrtci.
{88403}{88468}Ali, vi se zajebavate,|naganjate jedan drugoga...
{88470}{88524}družite se sa mrcinama iz|"Brodskog prijevoza".
{88526}{88560}Gdje ti je glava?
{88612}{88727}- Dajem ti priliku. Keith, zar ne?|- Da. "Keif."
{88729}{88779}- "Keith" ili "Keif"?|- "Keif."
{88781}{88831}- Koje?|- Keith.
{88860}{88907}Pa, trebao bi shvatiti.
{88950}{89043}Da. Howard æe se vratiti|za sat vremena. Ja æu to uzeti.
{89045}{89091}- Da.|- Hvala.
{89428}{89527}Dajem ti priliku da se družiš|sa poslovnim ljudima. Nemoj ju upropastiti.
{89528}{89626}Ponekad pogledam vas deèke iz|interne kada vam daju posao.
{89627}{89733}I zapitam se...|"Ima muda za to?"
{89735}{89787}Kužiš? Ne mogu si pomoæi, ali zamisli...
{89788}{89835}Da.|- Da?
{89837}{89899}Da. "Ax" (sjekira) bilo koga.
{90028}{90074}Dat æu ti profesionalni savjet.
{90099}{90164}Rijeè je "ask" (pitaj).
{90166}{90200}Dobro?
{90287}{90394}Želiš posao poput moga, jednog dana,|sjediš i dio si ekipe?
{90436}{90495}Tamo ti visi zvono.
{90497}{90600}Došao si tako daleko.|Samo ga moraš zgrabiti.
{90603}{90673}Ali za to trebaš velika|mesingana muda.
{90735}{90785}Sada reci da ih imaš.
{90815}{90891}- Da.|- Dovoljno velika da savladaš pritisak.
{90955}{90989}Dobro.
{91134}{91174}Da ih vidimo.
{91204}{91259}Tvoje klikere.|Da vidimo što imaš.
{91295}{91342}- Ja ne...|- Nisam peder, Keith
{91343}{91404}da æu skoèiti preko stola na tebe.
{91407}{91478}Samo želim biti siguran|da imaš odgovarajuæu opremu.
{91480}{91571}Tražili su me da predložim nekoga|da bude menadžmentski pripravnik.
{91602}{91652}Ti odluèi.
{91654}{91695}Èekaj.
{91697}{91815}Pokaži mi jaja.
{91817}{91856}- Ja ne...|- Slušaj.
{91895}{91991}Imaš par kakav ima svaki muškarac|ali ako hoæeš uspjet, moraš ih nositi na rukavu.
{91993}{92042}To je cijela bit ovog posla:
{92044}{92124}Tko nosi najveæu vreæu|otrova i tko ju je spreman upotrijebiti.
{92151}{92199}Neka ti ne bude neugodno.
{92875}{92914}Dobro. Odlièno.
{92943}{92978}Si dobro?
{93007}{93053}Dobro.
{93055}{93149}Donesi mi kavu prije nego|odeš, dobro? Crna je u redu.
{93327}{93424}Hej. Mislio sam|da odemo kasnije prošetati do jezera.
{93426}{93493}Navodno bude veliki vatromet.
{93527}{93574}Je li sve u redu?
{93576}{93674}- Da.|- Mjesto? Hrana? Sve u redu?
{93676}{93710}- Naravno.|- Dobro.
{93741}{93808}- Želio sam ti reæi|- Howard...
{93811}{93870}Možda ovo nije savršeno vrijeme...
{93872}{93946}ali stalo mi je do tebe Christine.
{93948}{94061}Želim da znaš|da mi se jako sviðaš.
{94063}{94134}- Trebam...|- Samo te ne želim izgubiti.
{94159}{94230}Znam da bismo morali|žrtvovati odreðenu slobodu...
{94232}{94310}i to što ne živimo u istom gradu |bi bio problem.
{94311}{94349}- Ne, èekaj.|- Mogu tražiti premještaj.
{94351}{94389}Samo trebam tebe.
{94415}{94465}Poèeo sam to shvaæati, i..
{94503}{94538}Kažem ti.
{94561}{94615}Trebam te.
{94646}{94687}Nauèio sam ovo.
{95003}{95050}Molim te, slušaj me.
{95105}{95180}Pustila sam da ovo ode predaleko.
{95182}{95240}- Predaleko?|- Da.
{95264}{95325}Trebala sam ti reæi ranije, ali...
{95381}{95454}Volim nekoga drugog.
{95491}{95525}Žao mi je?
{95527}{95582}Pogriješila sam.
{95583}{95632}Mislim, sviðaš mi se, ali...
{95664}{95727}A ti si to sve isplanirao...
{95729}{95784}Nisam te željela povrijediti..
{95891}{95962}Ali pogriješila sam što sam došla.
{95984}{96022}Ne, ne.
{96059}{96130}Ovo je naš izlet. Zajedno smo ga isplanirali.|Ne samo ja.
{96131}{96235}Hodali smo, izlazili van...|Što prièaš?
{96238}{96327}Volim onog èovjeka|kojeg si vidio za ruèak.
{96353}{96434}Chada, tvog školskog prijatelja.
{96471}{96506}Chad i ja...
{96570}{96616}On je taj kojeg volim.
{97011}{97070}Znam da je iznenaðujuæe...
{97073}{97110}i za mene.
{97136}{97199}- Chad.|- Da.
{97240}{97306}- Jako te cijeni.|- Da?
{97307}{97370}- Da.|- Uh-huh.
{97422}{97467}Žao mi je.
{97469}{97527}- Da.|- Ne, stvarno je.
{97528}{97568}- Naravno.|- Howard.
{97570}{97638}Dobro, žao ti je.|Grozno.
{97808}{97844}Nisam mislila...
{97919}{98002}- Ja sam kriva.|- Ne.
{98004}{98073}Nisam trebala izlaziti s obojicom.
{98151}{98216}Obojica ste trebali znati za ovo.
{98355}{98389}Kada...
{98419}{98491}dugo ne izlaziš...
{98543}{98577}poèneš se pitati...
{98611}{98677}jesi li privlaèan...
{98720}{98807}ili zanimljiv nekome.
{98863}{98962}Pustiš da samo ide|prvom prilikom koju dobiješ.
{98963}{99023}To sam ja napravila.
{99055}{99090}Vidim.
{99158}{99205}Samo...
{99207}{99266}kada sam te taj dan vidjela za ruèkom...
{99267}{99363}i kada si govorio stvari|poput "prijatelji"
{99365}{99413}i kako ste išli zajedno u školu.
{99415}{99456}Nisam mogla vjerovati.
{99459}{99517}Nisam imala pojma da ste vi dvoje...
{99581}{99623}Bila je sudbina.
{99707}{99794}Nisam nikoga željela povrijediti|i žao mi je.
{99903}{100003}Bilo je jako zabavno. Stvarno.
{100070}{100111}To je...
{100207}{100295}Idemo odavde.|Samo skupi stvari.
{100297}{100331}Ja æu...
{100395}{100454}Ja æu platiti.
{100492}{100528}Žao mi je.
{100579}{100613}Da.
{101147}{101199}Što je?|- Ne mogu...
{101226}{101272}- Što?|- Mi smo.
{101316}{101363}- Što?|- Mi smo znali.
{101400}{101459}Ne znam o èemu prièaš.
{101460}{101534}Izašla si sa mnom van|zabavljala se...
{101535}{101582}ali u krevet si otišla s njim.
{101606}{101673}Ne moraš ništa prièati.|Znam.
{101675}{101733}Sjedim ovdje,|neki kreten kojem je stalo do tebe...
{101735}{101781}a ti voliš drugog.
{101813}{101867}- Molim te, nemoj...|- Jesi li tako oèajna?
{101869}{101950}- Ne vidiš polje pred sobom?
{101951}{102016}Chad? Ne voli te.
{102018}{102071}Odvratna si mu.
{102073}{102146}Prezire tebe i tvoj|bijedan defektan glas.
{102147}{102194}Tako on to zove.
{102275}{102350}Christine, ti na to nasjedaš?
{102351}{102457}Viðate se na zabavama?|On mi je prijatelj, dobro?
{102459}{102507}Doma se družimo.
{102536}{102587}Bolje se probudi.|Iskoristio te.
{102624}{102671}To je igra.
{102672}{102767}Za Chada, to je igra|i rekao je da te našao "tako savršeno".
{102768}{102844}"Gluha je", to je bio razlog.|A ne zato što te voli.
{102846}{102935}A ne cvijeæe|i osjeæaje koje ja gajim prema tebi.
{102937}{103031}Ne, to je trebao biti hobi,|zabava, gledati te kako se raspadaš.
{103085}{103131}- Kažem ti...|- Prestani!
{103133}{103182}Christine, ja...
{103183}{103271}Mi smo to napravili i jako mi je žao
{103297}{103370}ali ne mogu promijeniti istinu.
{103371}{103427}Ne! Chad to nikad ne bi napravio.
{103430}{103476}Zašto mu vjeruješ?
{103478}{103555}Pogledaj me!|Što sam ti ikada napravio?
{103557}{103624}Dobrota, ljubaznost...
{103626}{103730}Što je s tobom?|Ne vidiš da sam ja ovdje dobar tip.
{103731}{103797}Ja sam ovdje dobra osoba.
{103829}{103915}Ne mogu promijeniti što smo napravili|i ja sam seronja
{103917}{103992}i gad i sve ostalo|na tvom popisu, ali ja sam ovdje.
{104024}{104078}Ja sam ovdje i govorim ti...
{104099}{104134}Volim te.
{104227}{104273}Izvoli, molim te.
{104306}{104340}Za tebe je.
{104342}{104376}Evo.
{104409}{104494}Molim te? Samo uzmi.
{104496}{104531}Za tebe je.
{104576}{104655}Ovo više za mene nije igra.
{104689}{104723}Uzmi.
{104766}{104850}Molim te, samo uzmi.|Hajde.
{104974}{105037}Makni se od mene! Ne!
{105039}{105121}Kuèko, defektna si!
{105156}{105227}Misliš da možeš birati?|Muškarci padaju pod noge.
{105320}{105391}Hoæeš ga nazvati, Chada?
{105393}{105431}Pozvati ga?
{105461}{105530}Pitati za naše malo natjecanje,|zašto ne?
{105757}{105819}Dobro! Lažem.|Ne vjeruj mi!
{105840}{105875}Idi njemu.
{105876}{105947}Hajde. Sklupèaj se u|njegovo krilo.
{105948}{106003}Sisaj njegov suhi jezik.|Ja ne...
{106096}{106143}Nadam se da si sretna.
{106871}{106922}- Što je?|- Ništa.
{106924}{106981}Samo sam malo izvan sebe.|To je sve.
{106983}{107042}- Nisam stigao juèer,|ali èuo si što je bilo, zar ne?
{107043}{107134}Dio. Imao sam otprilike deset|glasovnih poruka na "sekretarici".
{107135}{107214}Da, i pokušao sam te zvati na dojavljivaè.|Nisam te mogao dobiti.
{107215}{107307}Da, morao sam ga ugasiti.|Što se dogodilo?
{107335}{107440}Ništa, Samo je dvanaest tipova|stajalo tamo za vikend
{107443}{107502}i èetiri stranice su bile tako svijetle|da ih nisam mogao proèitati.
{107503}{107573}- Što?|- Èak niti pristupne lozinke.
{107575}{107669}Stari je izgledao kao da sam mu|osobno podigao limfocite na 18.
{107671}{107693}Super.
{107695}{107733}Nije bio zadovoljan.
{107772}{107855}- I?|- Našao sam tipa dolje.
{107856}{107893}I uveo ga.
{107895}{107992}Kopao je i našao dovoljno da uðe|u sustav. Ostalo sam usrao.
{107994}{108041}Pokrio sam nas zasad..
{108043}{108089}Provjerio sam te kopije osobno.
{108091}{108162}Samo znam da sam uzeo|što si mi ostavio.
{108163}{108212}Otvorio sam kovertu|toèno ispred njega.
{108237}{108301}Siguran sam. Sranje.
{108341}{108412}Traže da doðem|na sastanak u èetvrtak.
{108413}{108466}-Siguran sam da je sve u redu.|- Da. Ništa strašno.
{108468}{108557}Presela im je veèera zbog tebe.|Koliko loše može da bude?
{108558}{108609}U svakom sluèaju,|odlazimo odavde u sredu.
{108611}{108679}Taèno. Za mene u petak, ali...
{108681}{108727}izgleda kao da...
{108761}{108801}Vidimo se.
{108803}{108879}A ti? Jesi li lepo proveo vikend?|Obzirom na...?
{108881}{108932}- Pa, nije loše.|- Jesi li video Kristinu?
{108934}{108985}- Jesam. - Stvarno? Šta ste radili?
{108987}{109057}Samo smo se vozikali, veèera.|Znaš veæ.
{109059}{109123}Vožnjica? Fino je to.
{109125}{109198}Stara škola.|Poslednji dinosaurus je još živ?
{109201}{109257}Da. Kako god.
{109259}{109363}Ništa nije kao vožnjica,|kad želite da budete zajedno.
{109421}{109467}Vidimo se kasnije?
{109485}{109530}Da. Izvini.
{109580}{109659}Samo mi se ne sviða|kako se stvari odvijaju. To je sve.
{109661}{109708}U kompaniji sam 6 godina.
{109733}{109808}Neæe me skloniti sa posla bez borbe.
{109837}{109889}Znaš, mogli su da me nazovu| i to kulturno saopšte?
{109942}{110028}Par sitnih grešaka tu i tamo i iznenada|me premeste u "službu sa tehnièku podršku"?
{110072}{110134}To je sranje, zar ne?
{110136}{110202}Nije me briga što Chad|ima više iskustva sa softwerom.
{110204}{110278}Trebali su o tome|da misle pre nego što...
{110280}{110335}Dobio sam premeštaj. U deliæu sekunde...
{110337}{110381}Neko æe morati da odgovara.|Jel' tako?
{110383}{110428}O èemu ti prièaš?
{110453}{110527}O nièemu. Samo brbljam....
{110529}{110598}Bože. Drago mi je što je tako.
{110600}{110656}Ne zezaj.
{110658}{110766}Stavi se u moju kožu, izaðeš za vikend|i èitav svet ti se sruši.
{110811}{110885}Mislim posao, moja bivša cura...
{110887}{110962}To je prièa za sebe.
{110964}{111057}Neæe da prièa sa mnom,|ali je zato zvala moje roditelje.
{111089}{111152}Mislim.. bože!|Sve....
{111188}{111250}Šta mi se, doðavola, desilo?
{111317}{111400}A bio sam svoj na svome.
{111863}{111926}Ne...
{111928}{111975}Ne? U redu je.
{112001}{112086}Ne. Ne mislim na to. Hoæu...
{112088}{112129}Što?
{112130}{112187}Žao mi je što se|nismo mogli vidjeti.
{112189}{112283}Samo smo|dovršavali posao, bili zauzeti.
{112285}{112346}Želio sam.|Ostavio sam poruku tvojoj majci.
{112349}{112427}- Znam...|- Što?
{112429}{112469}Doði.
{112538}{112583}Gledaj.
{112585}{112648}Vidjet æemo se ponovno.
{112673}{112720}Obeæavam.
{112845}{112891}Znam da je teško.
{112949}{113001}Voliš li me?
{113003}{113072}Da. Kao i juèer.
{113135}{113189}Voliš li me iskreno?
{113261}{113308}Naravno.
{113718}{113767}Što ti je?|Tiha si cijelu veèer.
{113812}{113872}- Znam.|- Što?
{113929}{114005}Ne, ozbiljno. Što?|Jesam li nešto napravio?
{114006}{114054}Znam što se dogaða.
{114114}{114149}Što?
{114220}{114266}Ne znam što...
{114338}{114392}Misliš na Howarda?
{114393}{114509}Ti i Howard? Izašli ste|nekoliko puta dok me nije bilo?
{114511}{114558}- Da.|- Rekao mi je što je bilo.
{114560}{114632}Rekao mi je dok sam|ga vozio na aerodrom.
{114633}{114708}Htio sam nešto reæi|ali, mislim...
{114711}{114800}Slušaj. Nema veze. Razgovarali smo|o izlascima s drugima, zar ne?
{114801}{114910}- Da, ali znam...|- Kažem ti, nema veze. Svejedno...
{114912}{114984}Mislio sam da ti bude neugodno.|Zato nisam ništa rekao.
{114986}{115036}Ne! O tome što radite.
{115105}{115173}Zbunjuješ me.|Ne znam o èemu govoriš.
{115174}{115250}O tome što vas dvoje|radite meni.
{115252}{115312}- Howard mi je rekao.|- Christine...
{115313}{115392}Gledaj. Ovo je smiješno|jer ne znam o èemu prièaš.
{115393}{115432}Igra.
{115538}{115618}Igrali ste se sa mnom|zar ne?
{115713}{115771}Igrate li igru sa mnom?
{115806}{115853}Molim te, reci mi.
{115989}{116036}Howard ti je rekao, ha?
{116097}{116144}Tako...
{116197}{116270}Dobro. Šuti|na sekundu. Daj mi da objasnim.
{116300}{116347}To... sranje.
{116349}{116420}Christine, to...|nije bila igra.
{116423}{116501}Obojici si zapela za oko i...
{116525}{116572}Molim te, pokušaj... me razumjeti.
{116573}{116654}Pretvorilo se u nekakvo natjecanje|jer smo te oboje željeli...
{116921}{116997}Pokušao sam ti to ozbiljno objasniti|ali ne mogu se ne smijati
{116999}{117078}jebi ga.
{117081}{117139}Iznenaðenje.
{117206}{117253}I, kakav je osjeæaj?
{117281}{117334}Mislim, baš ovaj trenutak?
{117336}{117420}Tako naglo. Kako se osjeæaš iznutra|znajuæi ovo što znaš?
{117467}{117505}Reci mi.
{117986}{118024}To je sve?
{118069}{118120}Samo toliko boli?
{118200}{118260}Pa, sada bih mogao iæi.
{118261}{118308}Zadatak je obavljen.
{121148}{121204}- Tko je?|- Ja sam.
{121542}{121635}Što se dogodilo? Skoro je 1:00 sat.
{121637}{121692}- Kod mene doma?|- Da, izvini.
{121721}{121768}Ne mogu zaspati.
{121835}{121864}Lijepo.
{121965}{122017}Malo je manji|nego tvoj zadnji stan.
{122019}{122089}Da, ali je super antikna zgrada.|K tome i park.
{122090}{122174}- Toèno. Da. Odlièno je.|- Još uvijek pomalo ureðujem.
{122278}{122357}Vidim da imaš novi okvir|za "Gigolo."
{122358}{122408}Da?
{122410}{122457}Izgleda dobro.
{122477}{122599}Stan ti skoro ima,|i to mislim pozitivno,
{122601}{122639}pomalo ženski štih.
{122666}{122716}Hvala, Howard.
{122719}{122753}Naravno.
{122821}{122868}Onda, što te muèi?
{122933}{122983}Ne znam. Mislim...
{123059}{123089}Sranje!
{123117}{123212}Ovih zadnjih nekoliko dana.|Spavam možda po tri sata svaku noæ.
{123214}{123265}Ne mogu jesti.
{123267}{123329}Èak nisam mogao ni pojesti rižin puding.|Juèer, za ruèak.
{123331}{123369}Povratio sam ga 30 minuta kasnije.
{123371}{123424}- Oèaravajuæe.|- Samo ti opisujem stanje.
{123456}{123512}Bolestan sam, Chad. Umirem ovdje...
{123513}{123571}Mislim, ovo sve... Jebiga!
{123573}{123640}Znam. I ja sam sjeban.|Nisam ovo tražio.
{123641}{123699}A k tome su te još premjestili dolje|sa onim novim tipom.
{123701}{123756}Mislim, dovraga.
{123757}{123821}- Rekao sam ti da se paziš.|- Ne, Chad...
{123823}{123872}Želiš onaj ured u kutu?|Mogu nešto reæi...
{123874}{123899}Gledaj!
{123921}{123965}Zbog Christine.
{124049}{124145}Ovdje sam. Moram razgovarati,|zbog nje.
{124391}{124432}- Ti si.|- Što?
{124433}{124498}- Rekao joj.|- Da. Nekako kao da mi je...
{124550}{124608}Nekako si me sjebao iza leða, znaš.
{124609}{124657}Možda si mi mogao|prvo nešto reæi.
{124685}{124810}Mislio sam da smo se dogovorili da æemo|to držati za sebe.
{124859}{124905}Rekla je da si joj|sve isprièao.
{124907}{124953}- Da.|- I?
{124954}{125021}- Daj, Chad.|- Što, Howard.
{125024}{125076}Samo sam znatiželjan.|Mislim da bar to smijem.
{125141}{125197}I kakav je osjeæaj?
{125226}{125273}Loš, ok?
{125298}{125361}- Isuse. Skoro se raspala.|- Rekao si joj da ja...
{125363}{125462}Da, rekao sam joj...|Bože, ne mogu vjerovati.
{125464}{125555}- Èovjeèe, šteta što nisam bio tamo.|- Nikad nisam uèinio ništa takvo.
{125581}{125652}Ja jesam, nakratko, na sekundu.
{125679}{125737}Ostavio ju da cmizdri u sobi.
{125738}{125785}Onda sam otišao do picerije.
{125819}{125867}Zapravo je ostala u tvojoj hotelskoj sobi.
{125893}{125935}Što?
{125937}{126041}Vidiš, znao sam da neæeš doæi|do kasno, stoga sam si uzeo slobodu.
{126043}{126119}Zamolio sam spremaèicu da otvori...
{126121}{126193}To sam isto napravio|i kada sam ju prvi puta jebao.
{126222}{126289}Mislio sam da bi ti možda mogao|naletjeti, pa...
{126290}{126354}- Chad.|- Što?
{126356}{126430}Pokušavam ti reæi|da sam se zaljubio u nju.
{126432}{126478}Isuse Bože.
{126573}{126636}Mislim, znaš.|To je igra.
{126658}{126731}Smiješno je. Prvo sam pristao...|sranje!
{126887}{126921}- Što?
{127747}{127813}- Kada je ona došla?|- Kako to misliš?
{127815}{127868}Kako misliš, kako to mislim?|To je Suzanne, zar ne?
{127905}{127980}Spava na sredini|kraljevskog kreveta? Kako to?
{127982}{128048}Mislim, kada je dopuzala nazad?
{128073}{128119}Kada? U petak?
{128145}{128191}- Da.|- Dakle petak, tri dana...
{128218}{128260}- Nikad.|- Huh?
{128262}{128321}Nije nikad ni otišla, Howie.
{128322}{128393}Postaješ mi cmizdrav ovdje|i trebao bih otiæi spavati.
{128394}{128488}Ujutro idemo na plažu|pa æu ti reæi istinu.
{128513}{128562}Nikada nije niti otišla.
{128564}{128627}Uvijek je bila ovdje.
{128629}{128684}Ali ja...
{128685}{128732}Pa, onda...
{128777}{128818}Zašto?
{128844}{128890}Zašto, Chad?
{128916}{128962}Jer sam mogao.
{129045}{129092}Oh, Bože.
{129177}{129240}I, kakav je osjeæaj Howie?
{129242}{129297}Kakav je osjeæaj|nekome zaista nauditi?
{129298}{129345}Oh, Bože...
{129641}{129688}Vidimo se u ponedjeljak.
{130459}{130505}Koliko je sati?
{130565}{130612}Sad æe 1:00.
{130697}{130744}Nisi umoran?
{130802}{130861}Ne. Samo sam dovršavao program.
{130998}{131055}Lijepo mirišeš.
{131089}{131123}Hvala.
{131296}{131362}Je li to netko bio?
{131364}{131410}- Mislila sam da je.|- Nije.
{131444}{131490}Razgovarao sam sa sobom.
{131521}{131568}Stvarno?
{131570}{131641}Da radio sam na|prezentaciji ranije, to je sve.
{131737}{131784}Poznaš me.
{131876}{131914}Naravno.
{131916}{131973}Uðem u posao.
{131975}{132029}Tada mogu biti|bilo tko.
{134636}{134681}Slušaj.
{135301}{135338}Slušaj me!
