{1}{1}25.000
{2432}{2446}Za osoblje.
{3583}{3609}Španjolski klijent 
{3614}{3666}nas èisti | za stolom 12, sjedalo 6.
{3672}{3713}Stari želi da reagiraš | kao obièno.
{3729}{3766}Nosi plavi sako
{3770}{3826}i kravatu | s ljubièastim i zlatnim prugama.
{4980}{5100}{C:$0000FF}{y:ib} B & M |{C:$FF0000}{y:b} movies 
{5162}{5235}Oprostite, | zamijenio sam vas s nekim.
{7999}{8035}- Federico? | - Otišli su.
{8192}{8230}Koliko si dužina danas | napravio?
{8254}{8266}Šest.
{8278}{8303}Zakazuješ. Nisi baš u formi.
{8328}{8352}Došao sam se oprostiti.
{8448}{8490}Veæ nekoliko dana
{8516}{8602}budim se bez zraka, | i osjeæam bol u prsima.
{8633}{8686}- Nije mi preostalo puno vremena. | - Neæeš umrijeti od starosti.
{8710}{8734}Misliš da me netko | može potuæi?
{8744}{8774}Ne prestaješ igrati.
{8798}{8829}Zanima me samo posao.
{8834}{8868}Sa svakom igrom | dovodiš ga u opasnost.
{8873}{8915}Vjeruj mi, | neæu izgubiti.
{8929}{8999}Kazino, novac, zatoèenici, | sve æe tebi pripadati.
{9006}{9034}Ne želim ništa | što nisam zaradio.
{9143}{9178}Želiš iæi zaobilaznim putem?
{9223}{9253}Želiš se sa mnom mjeriti?
{9270}{9292}Nemaš nikakve šanse.
{9316}{9368}- Tvoj talent nije dovoljno velik. | - Ne znaš to.
{9384}{9426}Ja te poznajem | Još od potresa.
{9431}{9496}Ili postoji netko drugi | tko te uzeo pod svoje okrilje,
{9505}{9582}hranio te, školovao, | uèinio da postaneš netko?
{9586}{9618}Sreæa me spasila, | rekao si.
{9623}{9654}Neæu te žrtvovati.
{9659}{9737}Nauèio sam te da se njome služiš | i smatraš se sretnijim od mene.
{9750}{9785}Odgojio sam idiota.
{9791}{9806}Sjedni!
{10014}{10075}Ti si jedini kome dopuštam da | vidi moje lice, Federico.
{10276}{10326}- Jesi li veèerao? | - Ne još.
{10363}{10399}Odi se istuširat, | pozivam te na veèeru.
{10404}{10432}Ne mogu veèeras.
{10463}{10488}Zauzet sam.
{12324}{12401}Odlaziš Federico, | bez poljubca?
{12414}{12436}Ne èini to.
{12990}{13029}Tvoj dar sam ja otkrio
{13040}{13080}i njega ti sad uzimam.
{13358}{13387}Sad možeš otiæi.
{13499}{13527}Zbogom, Federico.
{14445}{14490}Sada nakon što ga je | stari onesposobio,
{14495}{14541}možemo ga dirati | bez da nam donese nesreæu.
{15763}{15826}SEDAM GODINA KASNIJE
{16610}{16685}Zove se Tomas Sanz. | Nije putovao sam.
{16909}{16948}- A ovo? | - Reži.
{18481}{18494}Sestro!
{18571}{18608}3 mjeseca uzdržavao sam | svoju punicu.
{18622}{18686}Potom ona umire a partner | joj daje 500000 pezeta.
{18691}{18761}Ali evo moja žena | Izgubi èek.
{18766}{18834}Rekla je da je bila moja greška, | da sam ja donio nesreæu.
{18838}{18895}Poludio sam, sve što nije valjalo | bila je moja greška.
{18900}{18948}- Imaš li njezinu fotografiju? | - Pronaæi æu.
{18953}{19010}Otjerao sam je, otišla je | zalupivši vratima
{19014}{19055}i svi su papiri | poletjeli u zrak.
{19060}{19129}I najednom, | što mi padne s neba
{19134}{19195}èek od 500000 pezeta.
{19200}{19237}Što kažeš na to | Federico?
{19261}{19301}Nisam li sreækoviæ, ha?
{19310}{19344}- Zadržat æeš ga? | - Što to?
{19350}{19367}Èek.
{19399}{19439}- Što ti misliš? | - Horacio Caparros,
{19454}{19476}prokleti si sreækoviæ.
{19740}{19754}Ne.
{19767}{19788}Daj mi ga kasnije.
{22889}{22928}Claudia je, javi se.
{22934}{22970}Ima svježeg mesa | u avionskoj nesreæi.
{23013}{23043}Šteta za tebe.
{23056}{23102}Buduæi da si ti na godišnjem, | dali su mi njegov dosje.
{23106}{23134}Nemaš sreæe.
{23139}{23182}Ovog puta to æeš platiti | dvostruko.
{23194}{23216}Nisu svi mrtvi?
{23485}{23545}I sve to za samo | 50 milijuna pezeta.
{23550}{23582}Ili pola ako preživi.
{23594}{23643}Ako je uzeo naše | životno osiguranje,
{23652}{23698}dobit æe | 5 ili 6 puta više.
{23703}{23757}Što znaèi 200 | što više 300 milijuna.
{23767}{23791}To je novac!
{23882}{23905}Hvala.
{23920}{23931}Claudia!
{24079}{24110}Zdravo.
{24118}{24137}Dobar dan.
{24224}{24251}Jel' dovoljno?
{24393}{24417}To je samo rutina...
{24447}{24483}Uhiæen je zbog kraðe.
{24498}{24513}Znam.
{24526}{24554}I zaradit æe novac?
{24578}{24609}Izbjegao je | strašno iskustvo.
{24632}{24666}Taj mu novac pripada.
{24686}{24716}Prièekajte da bude isplaæen
{24721}{24739}Molim vas...
{24750}{24807}Samo se moram uvjeriti da | je potpisao, to je sve.
{24937}{24955}Koliko?
{24974}{24985}Što koliko?
{25008}{25031}Koliko ste ga platili?
{25046}{25063}25 milijuna.
{25117}{25166}Vi mislite da je to dovoljno | za takvo iskustvo?
{25186}{25211}To je dogovorena svota.
{25222}{25261}To neæe biti skupo za | zrakoplovnu kompaniju.
{25288}{25307}Sekundu...
{25623}{25650}- Dobar dan. | - Dobar dan.
{25656}{25701}- Ja sam iz osiguranja. | - Mogu li vas pretresti?
{25724}{25741}Hvala.
{25775}{25849}Imam èek kod sebe. | Potpišite ovdje i vratit æu vam ga.
{25926}{25944}Dopuštate?
{26091}{26111}Predivna je.
{26213}{26241}Što æete napraviti | s novcem?
{26286}{26302}Molim?
{26319}{26344}Kako æete ga potrošiti?
{26379}{26417}Unovèit æete èek | za dva dana.
{26457}{26469}Da...
{26474}{26526}Iako vam nièemu ne služi | tamo kamo idete.
{26641}{26681}Kad sam zabrinut, | uzimam karte.
{26705}{26729}Pomaže ubiti vrijeme,
{26734}{26752}i ne misliti.
{26758}{26784}Ponekad od samog miješanja
{26789}{26822}problemi nestaju.
{26874}{26906}Izvucite asa | i ja æu vas izvuæi odavde
{26910}{26932}noæas.
{27013}{27046}Igramo bez oklade.
{27234}{27251}Tomas Sanz,
{27256}{27282}pravi ste sretnik.
{27293}{27330}- Naravno. | - Nemojte ni sumnjati.
{27346}{27410}Vjerojatnost je 1:1000000 | da æe se avion srušiti.
{27428}{27492}A da se sruši a vi | budete jedini preživjeli
{27509}{27541}od koliko...?
{27546}{27575}237 putnika?
{27592}{27642}Šansa je 1:237 milijuna.
{27696}{27718}Revanširajte mi.
{27771}{27800}I dalje bez uloga?
{27814}{27869}Vaša sloboda | pristanete li igrati za mene.
{27906}{27923}Igrati?
{27956}{27973}Što?
{27999}{28015}Žao mi je,
{28020}{28042}vrijeme posjeta je isteklo.
{28046}{28078}Samo što nismo završili.
{28115}{28156}Dakle, potpisujete ili ne?
{30574}{30629}Uèinit æemo prvu okladu | s vašom odštetom.
{30646}{30698}Potom æemo dobitke uložiti | u slijedeæe oklade
{30705}{30757}i na kraju sve dijelimo | pola-pola.
{30769}{30788}A ako izgubim?
{30794}{30822}To se neæe dogoditi.
{30830}{30854}A ako se dogodi?
{30864}{30892}Slobodni ste otiæi.
{30945}{30970}I koliko æe to trajati?
{30975}{31009}Najviše dva tjedna.
{31026}{31069}- Ne znam ništa igrati. | - Ne brinite.
{31081}{31125}Nije vam potrebna | nikakva osobita vještina.
{31168}{31208}Samo ne zaboravite | dvije stvari.
{31234}{31271}Ne dodirujte me.
{31296}{31311}Zašto?
{31321}{31382}Moja manija. | I ne fotografirajte me.
{31419}{31464}Ne trebaju nam suveniri | s ovakvog putovanja.
{31495}{31522}Imajte to na umu.
{31905}{31923}Dobra veèer.
{31928}{31958}- Poèeli su? | - Ne.
{31966}{31992}Hoæeš li njegove dokumente?
{32029}{32050}Da, ne poznajem ga.
{32141}{32189}Avion je izgubio vezu | s kontrolnim tornjem
{32194}{32218}12 minuta nakon polijetanja.
{32223}{32273}Nedavno naðena, | crna kutija
{32278}{32340}trebala bi rasvijetliti trenutke | koji su prethodili nesreæi.
{32345}{32378}Broj žrtava iznosi
{32382}{32425}231 putnik | i 6 èlanova posade.
{32430}{32462}Jedini preživjeli, | Tomas Sanz,
{32467}{32523}uhiæen je od policije...
{32528}{32562}Ti si tu dobrovoljno?
{32572}{32637}...radi pljaèke | banke prije 2 mjeseca.
{33069}{33121}Što èovjek osjeæa | pri rušenju aviona?
{33161}{33176}Spavao sam.
{33190}{33208}Hajde.
{33230}{33247}Ti to mene zezaš.
{33252}{33276}Što je to?
{33326}{33369}- Èudno miriše. | - Smola.
{33378}{33402}Njemu najdraža.
{33450}{33464}Da.
{33779}{33810}Vaše uloge, molim lijepo.
{33904}{33922}Oprostite.
{34036}{34068}Federico, moraš izaæi.
{34073}{34127}- On je novi... | - Pomozi mu i izlazi.
{34140}{34160}Drži.
{34200}{34245}Što je to? | Bez novèanih uloga.
{34250}{34273}Nije novac.
{34280}{34302}Trofej.
{34316}{34381}Odšteta jedinog preživjelog | u avionskoj nesreæi.
{34405}{34423}Da, naravno...
{34428}{34461}Tvoje lice mi nešto govori.
{34466}{34490}Ne igram protiv njega.
{34523}{34562}Èak ni tako, | nije dovoljno.
{34567}{34615}Jedan njegov prst | bio bi lijepi trofej.
{34650}{34678}Ako se on slaže, dogovoreno.
{34682}{34704}Dobra ideja.
{34709}{34757}- Dakle, Federico? | - Igramo.
{34807}{34830}- Èekaj! | - Zaboravi mene!
{34834}{34855}Èekaj, sranje!
{34874}{34937}- Onda, mój prst? | - Neæeš izgubiti prst.
{34942}{34982}- To je sigurno. Makni se. | - Ti tipovi...
{34986}{35023}su èisti amateri,
{35041}{35100}koji su osvojili bingo | ili pali s prvog kata.
{35110}{35144}Nemaju nikakve šanse
{35149}{35178}...protiv tebe. | - Ne idem.
{35186}{35203}K vragu!
{35208}{35242}Izbjegneš | avionsku nesreæu.
{35246}{35307}Izvuèem te iz bolnice | Zar to ne znaèi imati sreæu?
{35312}{35332}I?
{35338}{35373}U tome ti je potrebna | samo sreæa.
{35382}{35406}Da, ali nisam glup.
{35410}{35443}Imaš sreæe | i osim toga
{35448}{35498}...znaš njome vladati. | - Ti si bolestan!
{35511}{35533}Pusti me da proðem.
{35545}{35570}Ako ne želiš da te dotaknem
{35575}{35598}pusti me da proðem.
{35711}{35782}Kako to da si ti jedini preživjeli | u toj nesreæi, ha?
{35786}{35829}Bilo je dobrih ljudi | u kabini.
{35834}{35882}Tko te spasio, | tebe, lopova? Bog?
{35893}{35926}- Sluèaj. | - Za tebe ne postoji
{35930}{35949}sluèaj.
{35962}{36011}Ti imaš talent da kradeš | sreæu drugih.
{36021}{36055}Inaèe bi bio mrtav.
{36071}{36110}- Tako je. | - Vjerujem u tebe.
{36126}{36154}Ali ako ti ne vjeruješ,
{36175}{36206}zaboravimo sve to.
{36250}{36293}- Zadrži novac... | - Sve si pokvario
{36298}{36342}zbog jednog prsta | koji sam uložio s tobom.
{36499}{36522}Tvoj je.
{37390}{37432}Položite ruke na stol.
{38313}{38334}Možete skinuti poveze.
{38415}{38445}Ne mièi se.
{39088}{39114}Još si u igri?
{39118}{39138}Tko je to?
{39148}{39172}Igraš li još?
{39226}{39262}Što misliš, Federico?
{39275}{39308}Neæeš umrijeti od starosti.
{40086}{40135}- Što ti je? | - Nad glavom mi je životinjica
{40158}{40209}i u jednoj noæi zaradim više | nego u èitavom jebenom životu
{40214}{40266}...riskirajuæi glavu! | - Mogao si izgubiti prst.
{40271}{40301}- Ti isto, zar ne? | - Ne.
{40312}{40377}Èekao bi da odsijeku tvoj | a ja bi pobjegao.
{40398}{40431}Njima možeš pobjeæi, | ali ne i meni.
{40436}{40474}Sva sreæa da voliš pobjeðivati.
{40826}{40882}Ti koji sve znaš, | kako æemo ovo podijeliti?
{40887}{40940}Jesen-zima, tebi. | Proljeæe-ljeto, meni.
{40945}{40973}Puno si dopuštaš!
{41308}{41340}Potražit æu sobu.
{42566}{42631}Halo, Ana je, ostavite | poruku nakon signala.
{42658}{42706}Halo, Ana, ja sam. | Jesi li tamo?
{42777}{42795}Ana...
{42832}{42855}Jesi li tamo?
{42946}{42965}Mmmm...
{42994}{43014}Ne...
{43061}{43086}Nadam se da si dobro.
{43262}{43298}Sva sreæa da nisi išla | sa mnom.
{43342}{43393}Bilo bi mi bolje | da nisam išao tim avionom.
{43452}{43478}Sretan sam | što smo živi,
{43482}{43511}oboje.
{43579}{43601}Jako sretan.
{43728}{43751}Nedostaješ mi.
{43823}{43845}Žao mi je.
{43999}{44022}Žao mi je.
{45350}{45378}Penji se!
{45432}{45458}Neæu uspjeti.
{45463}{45484}Prestar sam.
{45552}{45573}Za ime Boga!
{45631}{45653}Daj!
{45698}{45717}Ajde, daj mi!
{45734}{45777}- Ne dodiruj me! | - Daj mi torbu!
{46498}{46548}Da me nisi više nikad taknuo! | Nikad više!
{46824}{46870}Mislio sam da je poziv | iz kabine siguran.
{46874}{46918}Iduæi put, | upozori me.
{46923}{46966}Uèinit æemo to inteligentno.
{47003}{47042}- Kako se zove? | - Ana.
{47058}{47106}To je djevojka s fotografije? | - Da.
{47117}{47185}Nije išla s tobom na Martinique? | - Propustila je avion.
{47191}{47256}Koja sreæa. | Kako je propustila
{47261}{47278}avion?
{47292}{47334}Potraži telefon, | treba upozoriti toreadora.
{47954}{48000}Velika borba može nastati | samo iz straha.
{48008}{48065}Ne straha od poraza, | ne kod pravog toreadora.
{48072}{48096}Veæ straha od patnje.
{48101}{48142}Patnje tebe samog | i onih koji te okružuju.
{48149}{48219}Taj strah te tjera | u istinsku borbu.
{48426}{48476}Niste se trebali zaustaviti, | nikada niste bili doista ranjeni.
{48481}{48515}Ali izgubio sam | strah od bikova.
{48520}{48556}Nije moguæe biti toreador | bez straha.
{48588}{48608}Dobar dan.
{48669}{48686}Dobar dan.
{48843}{48882}- Alejandro Dominguez. | - Znam.
{48890}{48948}- Možemo li razgovarati? | - Isprièajte me na trenutak.
{48953}{48972}Naravno.
{49106}{49140}Nije prvi put.
{49158}{49184}Alarm nije zvonio.
{49189}{49228}Uvijek ga zaboravim ukljuèiti.
{49233}{49294}- To se èesto dogaða. | - Godine... Postajem rastresen.
{49298}{49328}Nemojte se isprièavati.
{49357}{49381}Hoæete li dugo?
{49386}{49419}Ne, na raspolaganju sam vam | za èas.
{49474}{49490}Hvala.
{49622}{49657}Molim vas, odložite je ondje.
{49770}{49785}Sara.
{49849}{49895}Na autu su jedino otisci | Tomasa Sanza.
{49900}{49936}- A njegov suuèesnik? | - Ništa.
{49942}{49994}Vrata i prozori | nisu nasilno otvoreni.
{50016}{50068}- Kako su onda ušli? | - Kroz zidove...
{50073}{50098}ili sa kljuèem.
{50189}{50230}Pokazali ste nam | èitavu kuæu?
{50472}{50498}Dominguez ima prazan dosje
{50502}{50546}i nije ni u kakvoj vezi | sa tipovima koji su registrirani.
{50552}{50565}U redu.
{51314}{51353}Bok, mali bièe, | bok.
{52132}{52158}Pusti me na miru.
{52452}{52495}Zašto si išao tamo?
{52529}{52549}Bježao sam.
{52575}{52597}A kasnije?
{52630}{52682}Htio sam pokrenuti neki posao | pored plaže.
{52736}{52802}Kad budemo gotovi, moæi æeš si | platiti Karibe.
{52832}{52854}A u što se kladimo?
{52898}{52925}Nisam još odluèio.
{53405}{53454}Vratit æemo se ovdje | slijedeæi mjesec.
{53462}{53485}Onda, do viðenja.
{53546}{53562}Èekaj.
{53622}{53663}Ostat æu ovdje, Alfredo.
{53825}{53847}Dobar dan.
{53852}{53872}Dobar dan.
{53895}{53942}- Razbili ste staklo. | - Molim?
{53966}{54026}Okrenite se, raširite noge | i položite ruke
{54031}{54063}...na auto. | - Što se dogaða?
{54068}{54090}Jeste me razumjeli?
{54274}{54310}Stavit æu vam lisice.
{54320}{54351}- Najprije desna ruka... | - Ne trebate
{54356}{54398}me doticati. | - Iza leða.
{54403}{54437}Prestanite me dodirivati!
{54451}{54471}Pustite me!
{54720}{54772}Oduzet æete mi život kao što | ste i svom suprugu i kæeri?
{54814}{54830}Molim?
{54863}{54885}Ožiljak...
{54894}{54929}Poznati ste | meðu svojim kolegama.
{54946}{54997}Trebali biste biti mrtvi. | Ali ste se spasili.
{55002}{55030}Gdje je Tomas Sanz?
{55034}{55113}Vaša sreæa je | nesreæa drugih, zar ne?
{55122}{55168}- Tomas Sanz...? | - Hodajmo.
{55189}{55232}Odvest æu vas njemu | a mene zaboravite.
{55642}{55692}Na ovo ste potrošili | èitavu odštetu?
{55698}{55717}Hoæe li iæi?
{55744}{55763}Da.
{56066}{56108}Zašto vam je toliko stalo | da uhvatite Tomasa?
{56162}{56200}Èekajte da doðe | do Židova.
{56216}{56251}- Koga to? | - Židova.
{56256}{56293}Preživio je | koncentracioni logor
{56298}{56330}i sad živi u podrumu kazina.
{56338}{56373}Oduzima ti dar | dodirom.
{56414}{56445}Postaješ obièan.
{56458}{56485}Ali ja u to ne vjerujem.
{56494}{56532}Onakvi smo kakvi smo.
{56594}{56642}Veèeras igramo | sa zatoèenicima
{56674}{56727}Budale nam dozvoljavaju da im | donesemo nesreæu.
{56732}{56782}Treba ih dobro smotati | da im se oduzme
{56787}{56814}ono malo sreæe što imaju.
{56830}{56897}Potom bacamo kocke | i najviši broj pobjeðuje.
{56980}{57015}Pljuštat æe ko iz kabla.
{57026}{57063}Trebaš ponijeti | toplu odjeæu.
{57077}{57101}Mama, zloèesta...
{57196}{57218}Nešto ne valja?
{57363}{57390}Nemaš mi ništa za reæi?
{58026}{58053}Vaše dokumente.
{58062}{58140}ZA SMRT SUPRUŽNIKA... | ZA SMRT DJETEA...
{58214}{58241}Vaš ulog, molim lijepo.
{58414}{58446}Ovo je original?
{58479}{58551}- U što se kladimo? | - Ja u svoju kuæu.
{58566}{58591}Sada æeš je založiti?
{58608}{58656}Kada budeš igrao, | misli na lijepe stvari.
{58661}{58690}Bolje je | kada se opustiš.
{58709}{58751}Misli na lijepe trenutke | u svom životu.
{58765}{58795}S Anom, na primjer.
{58845}{58894}- Zašto ti ne igraš? | - Nemam talent.
{58924}{58946}Siguran si?
{58955}{59014}Kad ga nemaš, | nitko si.
{59343}{59391}- Tip s Tomasom je najstariji. | - Dame i gospodo,
{59396}{59430}odaberite svoje zatoèenike.
{59457}{59514}Trebao bi biti tamo, | slijedeæa igra je tek za 15 dana.
{59518}{59554}- Ajmo. | - Ne.
{59559}{59587}Neæeš moæi ponoviti igru.
{59592}{59612}Primaknite se.
{59681}{59710}To je jedini naèin | da ga pronaðemo.
{60678}{60704}Sijedi gospodin.
{60721}{60770}Gospodine sijede kose, | primaknite se.
{60912}{60954}Približite se ogledalu.
{61516}{61550}Odaberi onog | koji ti je najdojmljiviji.
{61661}{61696}Tip s naranèastim džemperom.
{61704}{61758}Gospodine u naranèastom | džemperu, izvolite priæi.
{62726}{62787}Pobjednik dobiva | uloge i zatoèenike.
{62792}{62815}Povezi.
{62888}{62934}Ništa ne brini, | sada je najbolji trenutak.
{63186}{63203}U redu...
{63218}{63237}Poèet æemo.
{63935}{63966}Èekaj, ne još.
{64026}{64058}Gospoðice, približite se.
{65705}{65734}Vašu ruku, molim vas.
{65842}{65883}6 i 4... 10.
{66265}{66292}Vašu ruku, molim vas.
{66397}{66422}3 i 2...
{66435}{66452}5.
{67970}{67988}Lezite!
{68243}{68273}Igra je nevažeæa.
{68343}{68401}Bila je u bolnici | kada sam se probudio.
{68406}{68430}U džepu je.
{68435}{68487}- I tamo je uperila pištolj u mene. | - Ali te nije uhitila.
{69167}{69191}Kurva!
{69200}{69219}Zeznula si me!
{69235}{69274}Trebala si ga uhititi | kada igra završi.
{69721}{69747}Ne zaslužuješ dar.
{70402}{70449}- Što je to? | - Naša je, pospremi.
{70469}{70491}Što æemo sad?
{70503}{70549}- Kladimo se na ljude? | - To ti smeta?
{70554}{70574}Ta djevojka...
{70593}{70612}Što æe s njom biti?
{70620}{70682}- Bez sumnje æe umrijeti od | prehlade. - Bez zezancije.
{70693}{70722}Nemam pojma.
{70727}{70785}Fotografija, poljubac... | Mogla se zaljubiti u tebe.
{70956}{70974}Molim?
{70996}{71083}Slušaj, ti si uhvatio njenu sreæu | pomoæu fotografije, sad je tvoja.
{71099}{71159}U to æemo se kladiti | ubuduæe: Ljudske sudbine.
{71165}{71211}Što æeš imati više fotografija, | imat æeš više i sreæe.
{71290}{71330}Ne vjeruješ mi, ha?
{71346}{71418}Ima bolesnika koji se vole | kladiti na slike ljudi.
{71426}{71488}To je najjednostavniji naèin | da se obogatiš i utekneš.
{71586}{71610}Ne sviða mi se to.
{71648}{71675}Ne želim više biti dio igre.
{71688}{71721}Ne znam drugi naèin.
{71770}{71791}Na tebi je da izabereš.
{71820}{71907}Ili ostaješ bez postavljanja pitanja | ili ideš orobiti banku.
{71943}{72010}Brzo odluèi. | Brzo æe doæi k sebi.
{72110}{72174}- Pokvarenjaèe! | - Ne ja samo brinem o poslovima.
{74846}{74872}DOSJE: HORACIO CAPARROS
{75854}{75883}Vaš ulog, molim lijepo.
{76279}{76306}Èekaj me u šumi.
{77185}{77202}Spreman?
{77229}{77287}- Imaš li èitav ulog? | - Igram na pobjedu.
{77300}{77322}I èek?
{77373}{77416}Nakon veèeras, | gotovo je s bježanjem,
{77434}{77478}spavanjem u autu | jedenjem govna.
{77488}{77546}Završimo ovdje i direktno za | Ucancu na posljednju okladu.
{77562}{77579}Ucanca?
{77592}{77645}Ono što æemo tamo zaraditi | daleko je najvažnije.
{77650}{77680}Radi se o èasti,
{77685}{77736}postiæi ono što želiš | i zadobiti poštovanje.
{77764}{77784}To mi se sviða.
{77859}{77893}Što to, poštovanje?
{77914}{77954}To što imaš razlog je | da sve ovo èiniš.
{77988}{78017}Kad tamo pobijediš,
{78022}{78058}biti æeš | najsretniji èovjek na svijetu.
{78079}{78110}I tada æemo završiti.
{78115}{78158}Platit æeš mi piæe.
{78182}{78206}Ili bocu.
{78220}{78253}A sada se koncentriraj.
{78271}{78336}Svi tvoji protivnici spremni su | ubiti kako bi dospjeli u Ucancu.
{78752}{78763}Hajde!
{78794}{78815}Brže!
{79038}{79060}Trèite!
{79314}{79345}Trèite!
{79492}{79525}Ajde, ajde!
{79781}{79804}Više od dva!
{80102}{80122}Ajde, ajde!
{80387}{80408}Stani, Alejandro!
{80413}{80434}Pobijedio si!
{80480}{80512}Zaustavi se, Alejandro.
{80641}{80651}Stani!
{80665}{80694}Pobjedio si.
{81177}{81196}Federico?
{81301}{81322}Federico?
{81814}{81846}Želim da mi se otvore vrata.
{81910}{81942}Za tebe ona su otvorena.
{82390}{82454}Možete li me odvesti | do vlaka?
{83521}{83546}Što ona tamo radi?
{83579}{83610}Što je to?
{83703}{83730}Vrati to gdje je bilo.
{83810}{83838}Pospremi u kofer.
{84102}{84132}Žao mi je ali ona je moja.
{84226}{84246}Van.
{84273}{84293}Gubi se!
{89902}{89926}Žao mi je.
{89954}{89992}To se nije trebalo dogoditi.
{90001}{90038}Ne bi bila ovdje | da smo pronašli Tomasa.
{90081}{90098}Ana...
{90137}{90172}Potrebna mi je tvoja pomoæ.
{90205}{90230}Reci.
{90312}{90345}Poènimo od poèetka.
{90391}{90426}Zašto nisi otišla | tim avionom?
{90519}{90568}Nièemu ti nije koristilo | što si ga napustila
{90578}{90607}i izbjegla nesreæu.
{90638}{90722}I on je preživio | i gle do èega je to dovelo.
{90793}{90842}Tomas je odgovoran | za tvoju nesreæu.
{90900}{90922}Nek crkne.
{90960}{90979}Ne vjerujem ti.
{91144}{91182}On me sprijeèio | da sjednem u avion.
{91249}{91281}Na aerodromu mi je rekao
{91329}{91362}da me više ne voli.
{91462}{91487}Spasio mi je život.
{91695}{91725}Što si rekla?
{91730}{91755}Da te više ne volim.
{92122}{92148}Nešto nije u redu?
{92790}{92830}Zašto postoji dvostruki | dosje Caparros?
{92834}{92882}Sud je tražio kopiju.
{92889}{92954}- Zbog èega? | - Njegova bivša žena žalila se.
{92961}{93017}Ubio se, ali ona je htjela | dobiti odštetu.
{93022}{93063}A Van Kuipp Life | odbija platiti.
{93079}{93101}Van Kuipp Life?
{93125}{93170}To je osiguravajuæe društvo | avionskih nesreæa.
{94510}{94532}To je moje.
{94590}{94608}Dobra veèer.
{94622}{94650}- Vi ste Claudia? | - Da.
{94658}{94688}Èekaj, nemoj poklopiti.
{94693}{94774}Prièa se da ste vi zaduženi | za dosje Caparros i de Sanz.
{94783}{94799}Da.
{94816}{94860}Ali ja sam s nekim drugim | razgovarao u bolnici.
{95184}{95234}Smeæe jedno! | Kuèkin sine!
{95420}{95441}Manjak sreæe.
{95466}{95499}Manjak sreæe, gluposti!
{95723}{95748}Što æe biti s Anom?
{95772}{95792}Možemo je spasiti.
{95836}{95850}Kako?
{95863}{95891}Igraj i vrati njenu sliku.
{96106}{96145}Ali tip je otišao u Ucancu.
{96173}{96207}Drugi je sad ima.
{96230}{96247}Tko?
{96275}{96307}Samuel Berg... Židov.
{96326}{96352}Kako znaš?
{96362}{96413}To je prokleta sudbina.
{96430}{96469}U 30 godina nitko nije | preživio u Ucanci.
{96474}{96496}Kurvin sine!
{96511}{96540}Tamo si me htio odvesti!
{96560}{96625}Ne bi smio izgubiti. | Zato sam založio Anu.
{96665}{96687}Kakva je to igra?
{96712}{96775}Dat æemo ti revolver | S 5 metaka.
{96786}{96824}Prvi pucaš.
{96834}{96872}Ako ga ubiješ pobjeðuješ. | Ako ne...
{96910}{96937}Židov puca.
{96960}{96987}5 naspram jednog...
{97013}{97037}Moglo je biti i gore.
{97052}{97111}Tip koji je imao više sreæe | od tebe je mrtav.
{97125}{97152}Ja odluèujem.
{97191}{97218}Koga æeš uložiti?
{98037}{98079}Oni lete za | Ucancu.
{99854}{99894}Zašto si mi doveo gubitnika?
{99923}{99942}Nemoj igrati.
{100080}{100129}Gerard mi je rekao da si | uložio njegovu malu
{100141}{100167}bez njegovog znanja.
{100269}{100311}Ovdje nitko nikada nije došao | iz ljubavi.
{100437}{100471}Tvoj èovjek zaslužuje igru.
{101518}{101569}Nemam obièaj razgovarati | s igraèima,
{101606}{101674}ali ovog puta | napravit æu iznimku.
{101826}{101847}Gledaj.
{102000}{102050}Svakog jutra, vrata | barake su se otvarala
{102077}{102107}i odveli bi više njih.
{102128}{102158}Najprije najstarije,
{102166}{102191}zatim naše roditelje,
{102208}{102267}našu braæu i starije sestre. | Za dva tjedna,
{102278}{102327}nije nas bilo više od 50, | sve djeca.
{102332}{102366}I tada su prestali dolaziti.
{102393}{102430}I onda, jednog lijepog dana,
{102456}{102502}pojavio se èovjek. | Nije bio èuvar.
{102518}{102543}Nosio je
{102555}{102620}odijelo boje pijeska, | bez greške.
{102626}{102671}Nos je pokrio | crnim rupcem.
{102690}{102726}Nismo baš dobro mirisali.
{102735}{102782}Uzeo nas je za ruku, | jednog po jednog,
{102794}{102841}i zabilježio sve naše brojeve | u svoj notes.
{102869}{102951}Zvat æe nas da se | pridružimo našim roditeljima.
{102984}{103022}Potom je otišao | i nikada se nije vratio.
{103063}{103092}Ali vratili su se èuvari.
{103099}{103136}Poredali su nas | i izvikivali broj.
{103141}{103167}Gledao sam svoju ruku.
{103177}{103226}Nisam bio ja. | Bio je netko drugi.
{103231}{103275}Prošao bi kroz vrata,
{103286}{103336}okrenuo se | i gledao nas,
{103343}{103389}sav sretan zbog svoje pobjede.
{103418}{103439}Potom je nestao.
{103445}{103463}I tako redom.
{103474}{103525}Svaki dan novi broj, | ili dva.
{103541}{103559}Ili nijedan.
{103585}{103655}Ponekad bi nas jednostavno | motrili i odlazili.
{103674}{103735}Na kraju smo ostali | samo Daniel i ja.
{103755}{103794}Ostali smo sami | 4 dana.
{103805}{103842}Razgovarali smo, | puno smo razgovarali.
{103850}{103886}Daniel je znao neke stvari.
{103901}{103950}Rekao mi je da je pomagao | ocu uraru.
{103973}{103991}Znate li
{104016}{104074}da ako pozorno promatrate | veliku kazaljku,
{104079}{104106}možete vidjeti kako se pomièe?
{104154}{104204}Ovo je Helena, | njegova sestra.
{104239}{104260}Daniel je znao
{104265}{104326}da nas vani ne èekaju | naši roditelji.
{104365}{104408}Kada su se vrata | ponovo otvorila,
{104413}{104452}stisnuo sam ruku svog prijatelja,
{104479}{104553}molio sam žmireæi | da ne budem ja.
{104591}{104651}Kada me Daniel pustio, | nisam više mogao otvoriti oèi.
{104656}{104694}Nisam mu htio | pogledati u oèi.
{104700}{104753}"Samo mi je rekao: | "Tvoja je"."
{104770}{104791}I otišao.
{104864}{104879}Zatim,
{104900}{104943}mi je u ruku | stavio fotografiju.
{105113}{105150}Kada su se vrata | ponovo otvorila,
{105168}{105201}uniforme su se promijenile.
{105482}{105526}Dakle, ako ste spremni,
{105531}{105550}poènimo igru.
{107758}{107815}Pronašla sam dizalo | koje vodi u podrum.
{108677}{108692}Roberto?
{108760}{108793}Carlos, Javier, | èekate me?
{110799}{110839}Federico, moraš izaæi.
{110852}{110873}Imaj povjerenja.
{110889}{110930}Sjeti se | da si izašao netaknut.
{116126}{116154}Ne volim te više.
{116788}{116821}Napustimo teren.
{116959}{116980}Gotov si, odlazi.
{116997}{117054}Za ime Boga, Federico, | oboje smo gotovi.
{117086}{117114}Hajde.
{117293}{117323}Pobijedili smo.
{117349}{117386}Ti si pobijedio.
{117414}{117442}Èuvaj se.
{118773}{118804}Sara? Jesi li tamo?
{118820}{119260}{C:$0000FF}{y:ib} B & M |{C:$FF0000}{y:b} movies 
{124965}{125033}Titl: C.M.C.
