{2275}{2479}INTIMNOST
{3779}{3850}lmali smo dogovor?|- Ne.
{3913}{3950}Hajde.
{4237}{4271}Kavu?
{4321}{4409}Obièno je kuhinja dolje,|ali ovdje je gore.
{4421}{4509}Nije baš zgodno.|Stalno nešto prolijevam.
{4518}{4625}Ali ovaj tip nikada nije tu,|tako da nema tko vidjeti.
{4912}{5035}Znaèi, ti stvarno živiš ovdje?|- To si me pitala i prošli put.
{5255}{5318}Sredit æu se èim doðem|do nekog novca.
{5454}{5532}Jesu li oni CD-ovi u kutijama|dolje? - Pokazat æu ti.
{10135}{10161}Oprosti.
{12173}{12224}To je traka za autobuse,|gade jedan!
{12731}{12767}Jay, ovo je Ian.
{12778}{12844}Pomagat æe ti veèeras.|Radio je u Atlanticu.
{12854}{12922}Koji je danas dan?|- Srijeda. Vidimo se.
{13359}{13462}Stavi mi ovu kavu u frižider.|Popit æu je kasnije.
{13663}{13706}Steve je dao otkaz u subotu.
{13725}{13760}Ti si veæ bio otišao.
{13777}{13838}Ovaj Francuz se prijavio|za posao prije dva tjedna,
{13844}{13906}pa smo ga nazvali.|Izgleda da je OK.
{13915}{13950}Svi oni izgledaju OK.
{13959}{14012}Možda trebamo uzeti nekoga|tko zaista želi ovo raditi.
{14024}{14047}Okružen sam idiotima
{14056}{14100}koji su ovdje samo dok|ne naðu nešto bolje.
{14110}{14216}Sve sami glumci, plesaèi|i umišljene zvijezde.
{14228}{14281}Do ovdje su mi!
{14297}{14399}Ne propuštaju priliku da kažu|tko su, i što ih zaista zanima.
{14415}{14503}"Gdje ti ideš na satove?"|"Baš je teško graditi karijeru"
{14510}{14565}To ionako foliraju.|- Svejedno, nervira me.
{14613}{14638}Bar nije restoran!
{14706}{14750}Naveèer ovdje imaš|sasvim drugaèije mušterije.
{14760}{14821}Ja sam glavni barmen|i radim što hoæu,
{14828}{14865}a ti radiš ono što|ti ja kažem.
{14875}{14969}Zaboravi onih probnih|tjedan dana.
{14980}{15062}Ili se odmah uklopiš,|ili nikada. Gdje ti je votka?
{15113}{15160}Popodne im svatko može|poslužiti pivo.
{15169}{15219}Naveèer nije tako jednostavno.|Uvijek netko traži tvoju krv.
{15228}{15263}Moju krv?
{15336}{15377}Budalo jedna!
{15428}{15481}Vidiš onog krupnog|tipa u odijelu?
{15488}{15530}Pije od èetiri popodne,
{15538}{15587}i na kraju æeš ga morati|izbaciti.
{15600}{15634}Vidiš ovu ženu što dolazi?
{15644}{15685}Ta je od onih što|stalno naruèuju isto,
{15693}{15736}a svaki put èeka da je pitaš.
{15747}{15822}Veæ tri mjeseca radim veèeri,|a kod nje stalno ista prièa.
{15831}{15855}Bok, dušo!
{15866}{15912}Danas mi baš izgledaš|veselo.
{15919}{15983}Moram li plesati na stolu da|bih bila primijeæena i uslužena?
{16019}{16130}Što pije? - Reæi æe ti ona.|Ali ne nadaj se napojnici.
{17454}{17546}Alex mi je dao svog Action Mana,|a onda je tog istog dao Marcu.
{17558}{17630}Rekao je da je to tajna.|- Prvo ga je dao meni.
{17663}{17702}Susane!
{17714}{17755}Ovdje smo!
{17997}{18075}Tata, ja volim sve ljude.
{18198}{18269}Alex ne može doæi|na moju zabavu. Ne dam mu!
{18279}{18340}Ne daš mu? To je strašno.
{18348}{18378}Tko je taj Alex?
{18387}{18430}Alex je budala.
{18492}{18570}Je li ti hladno? - Nije.|- Malo? - Ne.
{18579}{18644}Jesi li siguran? U redu.
{18652}{18709}Sada æu vam spremiti|veèeru.
{18717}{18776}Idite se dolje igrati.|Požurite.
{18840}{18973}Djeca divno izgledaju.|- Da, izgledaju jako dobro.
{18987}{19036}Voliš ih, zar ne?
{28292}{28398}Hladno ti je?|- Je, ali nema veze.
{28798}{28905}A sljedeæe srijede,|hoæe li opet biti srijeda?
{30301}{30342}Vidimo se. - Bok.
{30407}{30516}Je li on to što nam treba?|- Nije loš. Mušterije ga vole.
{30608}{30654}Laku noæ. - Laku noæ.
{30942}{30989}Dvije votke na moj raèun.
{31023}{31086}Barmen koji "nije loš"|èasti svog šefa.
{31286}{31345}Znaš onu ženu|koja je stalno tu,
{31363}{31422}koju si motao onu noæ?
{31438}{31502}Danas me pitala|da li sam ja Joelov brat.
{31511}{31558}Što? - Da li sam|Joelov brat.
{31567}{31630}Nisam joj rekao da ili ne,|ali ona je shvatila da jesam.
{31641}{31670}To je baš cool.
{31680}{31720}Sviða mi se ime Joel.
{31776}{31845}Kao mali, slušao sam|Billyja Joela.
{31852}{31976}Billy Joel! Nemoj, molim te!|Koliko ti imaš godina?
{32004}{32064}Prvo je moja sestra|poludjela za njim.
{32075}{32130}Imala je sve njegove ploèe.|I ja sam ga slušao.
{32188}{32214}Bilo je super. Imaš li|nešto njegovo ovdje?
{32223}{32272}Pobogu, poštedi me!
{32419}{32461}Koliko dugo radiš ovdje?
{32498}{32558}Otkad mi se rodio stariji sin,|prije šest godina.
{32591}{32654}Prije toga sam bio glazbenik.|Nešto kao Billy.
{32713}{32754}Nikada ne bih pomislio|da imaš djecu.
{32836}{32892}Jednoga dana, prije godinu dana,|jednostavno sam otišao.
{32909}{32954}Otišao sam živjeti|kod prijatelja.
{32963}{33023}Takve stvari se|dogaðaju u životu.
{33047}{33079}Jedna noæ bude posljednja
{33086}{33171}koju æeš provesti kod kuæe|sa ženom i obitelji.
{33190}{33261}Sljedeæeg jutra samo otvoriš|vrata i ponovno ih zatvoriš.
{33302}{33357}Ako je kuæa veæ|prazna, tim bolje.
{33365}{33404}Svi su bili veæ otišli,|pa je bilo lakše.
{33409}{33460}Nisi rekao ništa,|samo ste se razišli?
{33466}{33503}Što da kažem?
{33566}{33594}Billy Joel!
{33633}{33661}Jebo te!
{33812}{33865}Rekao si da tražiš stan?
{33906}{33990}Grozno je kada nemaš ništa|i moraš sve ponovno kupovati.
{33999}{34093}Ne želim da mi ljudi daju svoje|stvari, muka mi je od toga!
{34100}{34192}Ako me hoæeš dokrajèiti,|odvedi me u "secondhand" duæan.
{34200}{34269}Ovdje je sve novo i èisto.|Nema prošIosti.
{34278}{34304}Da popijemo nešto.
{34329}{34395}Ne, prvo idemo u obilazak.
{34510}{34544}Moja soba je tamo.
{34552}{34601}Nema se ništa interesantno|za vidjeti.
{34609}{34652}Puno toga si promijenio.
{34660}{34719}Je li ono i prije bilo tamo?|- Tamo je odavno.
{34907}{34989}Tvoja soba.|- Moja soba.
{35094}{35143}Sviða ti se? - Da.
{35149}{35192}Što nije u redu?|- Sve je OK.
{35255}{35327}Zar nema mjesta kod Jaya?|- Victore, molim te!
{35333}{35386}Jay sada živi u kuæi,|zar ti je nije pokazao?
{35406}{35465}Rekao sam ti, to je soba u|prizemlju. Ovo je puno bolje.
{35475}{35520}Meni ionako ne treba|novac od stanarine.
{35531}{35644}Otkud ja znam? Jayu|treba novac koliko i meni.
{35653}{35710}On ne prièa o tome,|ali mogu zamisliti.
{35725}{35803}Kada ostaviš obitelj,|totalno te oderu. Kuæa, djeca.
{35811}{35911}Krv su nam popili.|Ti živiš s nekim? - Ne.
{35927}{35980}Ti si peder?|- A što ti misliš?
{35990}{36031}Znaèi, jebeš se|tamo po duæanu?
{36042}{36111}Victore, ostavi|deèka na miru!
{36130}{36218}Jay i ja smo kao braæa.|Mi smo kao blizanci.
{36239}{36335}Svaki èas je netko od nas|mogao završiti u jarku.
{36342}{36403}Ali ne, mi smo zajedno|išli naprijed!
{36409}{36456}Koliko je takvih|ljudi u životu?
{36481}{36524}I Jay i ja smo|puno lutali.
{36530}{36593}Ali uvijek smo radili|što smo htjeli.
{36600}{36645}To je jako važno.
{36666}{36719}Mi smo robovi|svojih strasti!
{36833}{36915}Victor je onaj fini gospodin|koji ti jedne veèeri
{36923}{36993}pozvoni na vrata i predloži|kablovsku televiziju.
{37001}{37077}Mogu ti dati vrlo lijepu cijenu|ako je hoæeš uvesti u sobu.
{37326}{37458}Što je bilo?|To mi smeta.
{37503}{37564}Možda ti ustvari|i neæeš stanara. - Što?
{37573}{37634}Victoru treba novac.|Ianu treba stan. - Èekaj!
{37642}{37716}Vrlo je jednostavno.|Zašto komplicirati?
{37730}{37796}Ali možda sam ja|sve pogrešno shvatio.
{37805}{37850}Možda bi trebali|odustati.
{37862}{37909}Ne, hajdemo probati!
{37973}{38034}Što se mene tièe, u redu je|ako æe ti to pomoæi.
{38050}{38155}Ja nemam ništa protiv toga.|Imam svoj život.
{38169}{38212}Ne obraæaj|pažnju na mene.
{38219}{38272}Victor izdaje sobu,|i to je sve.
{38280}{38383}Samo stavi novac na stol,|i to gotovinu. Ne primam èekove.
{38492}{38595}Sin mi je rekao da želi|upisati likovnu akademiju.
{38632}{38831}Kada sam imao 16 godina, i ja|sam malo slikao. Èudno, zar ne?
{38854}{38984}Znaš da nije dobro biti sam. |Upast æeš u neko sranje!
{38990}{39035}Što to prièaš?|- U redu!
{39042}{39089}Nemoj mi govoriš|što trebam raditi.
{39096}{39126}Hvala što si svratio,|i zbogom!
{39132}{39187}Što si ono lupetao|o blizancima?
{39195}{39275}Kakve su to gluposti?|To me izluðuje!
{44180}{44229}Bok, dušo!|- Bok, srce.
{49386}{49412}Tata!
{49426}{49464}Evo...
{49499}{49567}Tata! - Samo trenutak.
{49591}{49627}Što je?
{49643}{49748}Vidi. - Dogodila ti se|mala nezgoda?
{49841}{49917}Možda æeš jednoga dana|ti uèiniti ovo za mene.
{49956}{49992}Hajdemo se presvuæi.
{50360}{50506}Oèi su ti danas naopaèke.|- Zašto to kažeš?
{50536}{50669}Kada napravim ovako,|izgledaju kao obrve.
{50682}{50749}Tvoja glava može|se gledati s obje strane.
{50830}{50920}S mamine strane, svi imaju|vreæice ispod oèiju.
{50927}{50988}Èekaj malo, napipao sam ih.|- Ja ih nemam!
{50994}{51055}Možda æeš ih jednoga|dana imati. - Neæu!
{52335}{52361}Èekaj!
{53182}{53220}U redu je.
{53425}{53491}Victore, što æeš ti ovdje?|Gubi se!
{53504}{53569}Oprosti, trebao sam|se javiti.
{53591}{53736}Ne znam otkud mi ideja da si|ti uvijek sam. Kakva glupost!
{53788}{53864}Ali lijepo je kada ti netko doðe.|Ja sam to volio.
{53879}{53919}Ne, Victore... - Oprosti.
{53944}{54052}Onaj tvoj prijatelj Ian se nije|ni pojavio. Je li nešto rekao?
{54066}{54091}Ne znam.
{54150}{54244}Da nemaš možda neku|gu-dro u kuæi? Sav sam sjeban.
{54330}{54361}Ne koristim to.
{54369}{54412}Imaš li ovdje sve|što ti treba?
{54419}{54478}Nabavit æu ti kablovsku|kada god budeš htio.
{54544}{54594}Nikada mi nisi rekao|da se viðaš s nekim.
{54619}{54666}Rekao si: "Ne viðam|se ni sa kim".
{54673}{54761}To mi je šefica. Provjerava|da li imam sve što mi treba.
{54847}{54923}Osobno, mislim da s njima|ne treba imati ništa.
{54949}{55044}Umiješaju se emocije,|pa im ne možeš više ništa...
{55067}{55132}...reæi, na primjer,|kada se pokvari grijanje.
{55142}{55245}Jebo te, ova kuæa je ogromna.|Ti si sam ovdje?
{55335}{55427}Što još radi ta tvoja|šefica osim što te izluðuje?
{55436}{55480}Jesi li joj vidio|izraz lica?
{55494}{55535}U redu, dva dana.
{55547}{55627}Možeš ostati|dva dana, ali to je sve.
{59312}{59462}Svaki èovjek ima svoje lice, i|sva su razlièita. To je super.
{59477}{59533}Dok ih gledam,|vidim da su razlièita.
{59541}{59626}Ali da sam sutra u istom|vlaku s istim ljudima,
{59632}{59744}nikoga ne bih prepoznala.|To mi je veæi problem.
{59773}{59829}Vidjet æemo se u petak?|- Zašto?
{59835}{59882}Zar ne želiš da doðem?|- Betty!
{59915}{59994}Kakav ti je bio dan?|- Ništa naroèito.
{60029}{60060}Bok!
{61203}{61255}Gdje su karte?|- Kod tebe su, u torbi.
{61269}{61344}Onuda, niz stepenice.|Tamo.
{61573}{61637}Ne smiješ oèekivati previše|od Laure. - Kako to misliš?
{61647}{61760}Ona je naša, i volimo je. Više|i ne primijeæujemo da je bogalj.
{61766}{61849}Ne govori "bogalj"!|Ne dozvoljavam da se koristi ta rijeè.
{61869}{61919}Ali, majko, pogledaj|istini u oèi. Ona to je.
{61928}{61970}I to nije sve.|- Kako to misliš?
{61988}{62049}Laura je drugaèija|od drugih djevojaka.
{62054}{62094}Drugaèija je|u pozitivnom smislu.
{62101}{62202}Ne baš. Gledano sa strane,|ona je užasno stidljiva.
{62210}{62242}Živi u svom svijetu.
{62251}{62314}Zbog toga djeluje èudno|ljudima izvan kuæe.
{62328}{62391}Nemoj govoriti da je èudna.|- Bok.
{62403}{62430}Pogledaj istini u oèi.|Ona to je.
{62439}{62483}Neæu povlaðivati|tvojim budalaštinama, Laura.
{62498}{62565}Sjedni i saberi se|prije nego što oni doðu.
{62572}{62632}Tom je zaboravio kljuè.|Morat æeš im ti otvoriti.
{62642}{62715}Majko, ti otvori vrata...|- Ja æu imati posla u kuhinji.
{62724}{62816}Majko, molim te, otvori vrata!|Ne tjeraj me da to radim!
{62832}{62932}To su tvoj brat i g. O'Connor.|Dušo, molim te, otvori vrata.
{62940}{62978}Majko, molim te,|otvori ih ti.
{62982}{63002}Molim te!
{63007}{63038}Daj mi jedan dobar razlog.
{63055}{63115}Dolazim! Samo sekundu.
{63138}{63217}Zašto se bojiš|otvoriti vrata?
{63229}{63363}Laura Wingfield, kreni prema|vratima! - U redu, majko.
{63616}{63729}Laura, ovo je Jim.|Jime, moja sestra Laura.
{63740}{63792}Nisam znao da|Shakespeare ima sestru.
{64240}{64317}Svidjelo ti se? - Ne znam,|nisam baš ljubitelj kazališta.
{64327}{64369}Nemaju puno prostora ovdje.
{64379}{64436}Oni nisu grupa koja radi|razlièite predstave.
{64479}{64533}Koliko vremena imamo?|- Petnaest minuta.
{64541}{64585}Naruèit æu nam piæe.|- Ne, u redu je.
{64592}{64673}Guiness, molim. Što æeš ti?|- Coca colu, hvala.
{64682}{64732}Samo Coca colu?|- Da, radim kasnije.
{64740}{64791}Što æeš ti?|- Mogu li i ja Colu?
{64803}{64854}Samo to? - Hoæeš li èips?|- Ne, hvala.
{64860}{64878}Dvije Coca cole.
{64885}{64957}Mama je bila strava veèeras.|- Da. - Što si rekao?
{64965}{65091}Mama je bila strava veèeras.|- On voli dolaziti ovdje.
{65103}{65141}Da može, dolazio|bi svake veèeri.
{65150}{65194}Ja sam èesto nervozan|i razmišljam
{65202}{65254}da li æe zaboraviti tekst,|ili se spotaknuti.
{65262}{65327}Stalno gledam okolo|da li se ljudima sviða.
{65336}{65414}Ali on gleda cijelu predstavu,|i sve kuži.
{65422}{65466}Jako ti se sviða, zar ne?|- Da.
{65830}{65916}Druga polovica.|Voliš Tennesse Williamsa? - Da.
{66389}{66440}Moram ostaviti nekoga,|a ne znam kako.
{66447}{66525}Dovraga! Kakva|je sada situacija?
{66533}{66576}Jedna djevojka|s kojom se viðam.
{66582}{66672}Dolazi, jebemo se, i odlazi.|Ja je ne zovem da ponovno doðe.
{66687}{66730}Dobro, jednom sam|je pozvao.
{66749}{66788}Što bi ti rekao?
{66814}{66915}To je ludo. Jednom nešto|predložiš, i prijeðe im u naviku.
{66955}{67002}Nije da mi je to umaranje...
{67017}{67072}Ustvari, je!|To je toèno to.
{67086}{67226}To mi je umor. Ali samo sada.|Prije nije bilo.
{67235}{67292}Odjednom mi je|to postalo gušenje.
{67341}{67458}Ta prokleta srijeda je kao nešto|što dugujemo jedno drugome.
{67496}{67537}Skroz je pogrešno.
{67561}{67645}Razumjet æe. Ljudi|razumiju takve stvari.
{67724}{67765}Što bi ti uèinio|da to završiš?
{67779}{67842}Ostao bih isti, pa bi se|završilo samo od sebe.
{67850}{67907}Možeš li vjerovati|koliko je ta žena oèajna?
{67915}{67989}Srijedom od dva do nekih èetiri.|Hoæe to, i samo to.
{67997}{68064}Zašto misliš da je oèajnija|od tebe? - Kako to misliš?
{68071}{68097}Zašto bi bila?
{68105}{68172}Nisi je zvao da ponovno doðe,|niti te ona pitala da li smije.
{68181}{68247}Ipak, uvijek joj otvoriš|vrata, i to tako ide.
{68253}{68304}Gdje je tu oèajanje?
{68325}{68411}Rijetko se nalazi netko|tko želi baš isto što i ti.
{68443}{68514}Možda joj ti daješ puno.|Nisi èak ni svijestan toga.
{68520}{68563}Otkud ti znaš?|Ti je ni ne poznaješ!
{68570}{68652}Mogu je zamisliti. Siguran|sam da joj puno daješ.
{68663}{68734}Ne znam. Ne vjerujem|da želi isto što i ja.
{68741}{68802}Nemam dojam ni|da sam u vezi s nekim.
{68832}{68922}Što ona kaže o svemu tome?|- Ne znam, mi ne razgovaramo.
{69503}{69527}Victore!
{69635}{69674}Krema za cipele|ti se sva sasušila.
{69681}{69724}Ti ne trebaš biti|ovdje da to vidiš.
{69731}{69790}Zašto je s tobom uvijek isto?|Rekao sam, samo dva dana!
{69796}{69847}Odlazim sutra.|- Danas je srijeda.
{69855}{69908}Znaš da ne bi trebao biti|ovdje srijedom popodne!
{69917}{69927}U redu! Trebao si|mi tako reæi.
{70027}{70074}Ostavi to. Hajde!|- U redu.
{73699}{73775}Da postoji problem,|ti bi mi rekao, zar ne?
{73923}{73956}Zar ti nisi u pubu?
{73962}{74040}Da odem u pub, samo bih pio.|To nije rješenje.
{74117}{74172}Toèno, to nije rješenje.
{74826}{74879}Hej, hoæeš li opet|gledati predstavu?
{74895}{74987}Prošli put je bilo super.|Dokaz je to što si opet ovdje.
{75011}{75064}Ti nisi baš neki|kazališni tip.
{75122}{75208}Ti radiš ovdje?|- Ne, mada tako izgleda.
{75351}{75425}Mislio sam da on... veæ sam|zaboravio što se tu dogaða.
{75438}{75493}Što? - U predstavi.
{75585}{75692}Ljudi ne prièaju poslije|predstave, samo zbrišu.
{75723}{75753}To je rastužuje.
{75760}{75846}Zato ja slušam što govore,|pa joj poslije isprièam.
{75854}{75948}Ne treba nas biti briga, ali|ljudima se uglavnom svidi.
{76008}{76123}Ustvari, to ovisi o ulozi.|Moja žena je u predstavi.
{76136}{76216}Glumi onu djevojku, Amandu.|- Lauru.
{76222}{76263}Laura, je li tako?
{76277}{76303}Više ne znam ni sam.
{76310}{76353}Sigurno sam ti|sve ovo veæ prièao.
{76453}{76543}Ja nikada ne mogu ocijeniti|da li netko glumi dobro ili loše.
{76594}{76686}Ali publika uvijek ima neko|mišljenje. To je interesantno.
{76703}{76818}Ja ih slušam na pauzi, i|odjednom postavim neko pitanje.
{76827}{76882}Ne osjeæam se kao|budala dok to radim.
{76910}{76965}Uostalom, nikoga nije briga|da li sam ja tu ili nisam.
{76999}{77035}Ali oni ne znaju|tko si ti, zar ne?
{77043}{77127}Mislim, ljudi iz družine.|Navikli su da sam tu.
{77136}{77172}Ponekad im pomažem.
{77180}{77256}Možda sam budala, ali|osjeæam se kao svinja u govnima.
{77436}{77503}Laura, dušo, otvori vrata!|To su tvoj brat i g. O'Connor!
{77620}{77720}Ovo mjesto ti zaista odgovara.|- Iz više razloga.
{77749}{77785}Važno mi je da sam s njom,
{77796}{77857}jer bi nas ova njena strast|mogla razdvojiti.
{77895}{78002}Ako nešto zaista voliš, to je|èesto na raèun neèega drugog.
{78011}{78076}Apsolutno. - Ne želim|da ona bude žrtva toga.
{78123}{78213}Claire i ja smo odluèili da to|ne bude na raèun nièega.
{78268}{78329}Ja sam Andy. - Jay.
{78363}{78466}Znaèi, ona se zove Claire?|- Tko? - Tvoja žena.
{78519}{78556}Zar ti to nisam rekao?
{78583}{78659}Toliko sam ti stvari rekao,|a najvažniju sam zaboravio.
{78730}{78833}Sigurno je neobièno pratiti|sve to, kao što ti radiš.
{78840}{78885}Ne znam. Da se ja|bavim tim poslom,
{78890}{78939}htio bih èuti|što ljudi misle o tome.
{78945}{79021}Ali možda to|samo mene potresa.
{79044}{79124}Možda je to zbog mog posla.|Ja sam taksist.
{79261}{79314}Kada ne prièam s mušterijom,|kao da ne radim pola posla.
{79328}{79377}Da, da... - Da odigramo|jednu partiju?
{79422}{79483}Ovdje je zabavno i gore|i dolje. To je dobra stvar.
{79657}{79693}Jesi li ti oženjen?
{79838}{79895}Kada si s nekim,|samo kratko vrijeme
{79903}{79981}jedno drugom možete sati|nešto bez nadoknade,
{79997}{80048}i bez prethodnog zahtijeva.
{80059}{80129}Kasnije jedno od drugoga|stalno nešto tražite.
{80186}{80239}Možda je jedina razlika|izmeðu nje i ostalih
{80247}{80306}u tome što ona od tebe|ne traži ništa.
{80319}{80360}Ali što si ti nauèio?
{80376}{80398}Plašiš me.
{80405}{80466}Zar ništa nisi nauèio iz toga|što si napustio obitelj?
{80472}{80544}Možda bi trebao izlaziti|samo sa zdravim ljudima.
{80590}{80664}To je to. Ovo bi samo|luðak mogao poželjeti.
{80671}{80751}Nije moj stil da nekome|otkrivam svoje slabosti.
{80831}{80913}I ona se viða s|nekim drugim. - A ti?
{80924}{81041}Ne, ta žena je|sve što imam.
{81088}{81193}Kuda æeš? - Upravo je prošao|zgodan mladiæ. Oprosti, idem.
{81566}{81602}Bok, Joan!
{81613}{81639}Ovo je Claire.
{81658}{81755}Je li turneja dobro prošla?|- Valjda, kao i svaka druga.
{81765}{81791}Bok. - Bok.
{81822}{81923}Baš bi mi godila jedna|turneja, da malo živnem.
{81972}{82095}Ne izgledam kao drolja?|- Ne, drolje ne izgledaju tako.
{82127}{82186}Jutros sam imala|jedan casting.
{82198}{82263}U mom stanu je|dosta mraèno, pa sam...
{82279}{82336}Claire Nichols? - Da?
{82359}{82428}Znaèi, ti daješ satove?|- Da, amaterima.
{82441}{82513}Doði ako hoæeš, ponekad|se nešto i dogaða. - Kada?
{82520}{82631}Utorkom i petkom. Petkom u 3.|- U redu, doæi æu u petak.
{86204}{86275}Kada smo se prvi put sreli,|mislio sam da si uobražen.
{86302}{86349}Izgledalo je kao da|sereš na sve nas.
{86359}{86404}Ali, to nije tako, zar ne?|Ti samo tako izgledaš.
{86414}{86482}Mada, ponekad|ovaj naš život...
{86505}{86540}Na primjer, moja žena.
{86549}{86664}Kazalište je super, ali ja|znam da ona previše radi.
{86732}{86777}Što æeš, tako ti je to.|- Da.
{86800}{86853}Razmišljao sam|neki dan,
{86873}{86920}ljudi koji se zaista vole...
{86974}{87093}Što bi uopæe moglo stati|izmeðu njih? Što ti misliš?
{87103}{87175}Misliš, zaljubljeni,|ili samo prijatelji?
{87186}{87266}Zaljubljeni. Možda|su èak i ljubavnici.
{87320}{87420}Ti, na primjer. Što bi to moglo|sjebati tvoj brak? - Što?
{87473}{87551}Pogledaj mene. Radio sam|u tom lokalu 6-7 godina
{87571}{87699}èekajuæi da se pojavi|nešto drugo. U poèetku...
{87715}{87815}...je bilo privremeno, a sada|sam se ukopao kao kreten.
{87858}{87894}Ako hoæu biti|iskren prema sebi,
{87902}{87949}jedini put kada sam|nešto rekao i uèinio
{87959}{88020}bilo je kada sam|otišao od kuæe.
{88036}{88151}Znaèi, oženjen si! Uèinilo|mi se da sam vidio neku tugu...
{88160}{88263}Kada ti se to dogodi, obièno ga|èuvaš za sebe, zar ne? - Da.
{88271}{88341}Kada je sve propalo, i želiš|samo otiæi, to èuvaš za sebe.
{88351}{88425}Kome si rekao da odlaziš?|- Prijateljima. Jednom prijatelju.
{88436}{88536}Tada postaje ružno.|To zaboli ljude.
{88544}{88647}Jebote, to je primjer.|To bi me baš pogodilo.
{88655}{88747}Kada si u svemu tome,|ne vidiš ništa.
{88770}{88868}Tek na ulici sam shvatio|koliko sam nesretan,
{88879}{88947}i kako sam nisko pao.|Vrlo nisko.
{88959}{89070}Jer, Andy, najlakše|je ostati.
{89092}{89159}To ljudi obièno rade,|zar ne?
{89171}{89255}A ti? Kako je sve to poèelo|izmeðu vas dvoje?
{89274}{89346}Što? S kim?|Moja žena i ja?
{89356}{89432}Èekaj malo,|to su privatne stvari!
{89439}{89536}Ja imam dugaèak jezik, ali|to ne zna èak ni on! Odjebi!
{89576}{89602}Jesi li dobro?
{89612}{89640}Idi kupi sebi piæe.
{89645}{89683}Ne idi van.
{89722}{89738}Stavi na crtu.
{89744}{89791}Jesi li dobro, Luke?|- Jesam, hvala.
{89798}{89824}Dobar deèko.
{89865}{89951}Što bi ti mislio o majci|koja ima tajnu vezu,
{89962}{90062}a naveèer se vraæa obitelji|kao da se ništa nije dogodilo?
{90278}{90346}I sve to uz užasno|vješto pretvaranje.
{90362}{90475}Kako možeš, nakon što|te netko jebao cijeli dan,
{90487}{90548}naveèer se vratiti mužu,
{90562}{90625}meni, Jayu, svom mužu,|svojoj obitelji,
{90632}{90679}kao da se ništa nije dogodilo?
{90711}{90766}Stvarno hoæeš moje|mišljenje? - Da.
{90856}{90942}Ja mislim... ne znam.
{90966}{91044}Ima puno ljudi|kao što si ti.
{91106}{91151}Ali to tebi nije|od neke pomoæi.
{91158}{91254}Ona se mora vratiti kuæi,|zar ne? Da poljubi djecu,
{91260}{91418}zagrli ih, natoèi piæe sebi|i kretenu koji sjedi...
{91427}{91459}...s njom za stolom.
{91467}{91533}Možda æe morati i prièati|o tome kako je provela dan.
{91539}{91699}"Bilo je malo naporno, dragi,|ali bio je to divan dan..."
{91728}{91849}Nakon što ju je cijeli dan|jebao neki idiot,
{91856}{91911}koji, usput, ne progovara|s njom ni rijeèi.
{91918}{91965}Andy, igraj, jebote!
{91970}{92056}Ili neka Jay preuzme,|a ja idem na drugo mjesto!
{92131}{92180}Znaš što, kolega?
{92209}{92338}Tada bi me gledala s najviše|pažnje. Susane, moja žena...
{92357}{92460}Naveèer, kada doðe kuæi,|naprosto bi me gutala pogledom.
{92467}{92526}Nemoj muèiti sam sebe.
{92542}{92622}Kada doðe kuæi, mora|usporeðivati, zar ne?
{92687}{92777}Ustvari, pored tebe je|sada sretnija nego ikada.
{92783}{92820}Slušaš li me?
{92859}{92910}Što ti misliš?
{93032}{93141}Dokle god svake veèeri|dolazi kuæi, u redu je.
{93348}{93457}Nisam iznenaðen što to kažeš.|Neæu ti ni uzeti za zlo.
{93465}{93597}Dok ti se ovako nešto ne dogodi,|osjeæaš se zaista zaštiæenim.
{93646}{93738}A onda, kada se dogodi,|nisi ni iznenaðen, zar ne?
{93748}{93795}Je li tako?
{93832}{93920}Hoæeš reæi|da ako ostanemo,
{93939}{94003}to znaèi da se ne možemo|suoèiti s tim?
{94013}{94087}Jebote! Palim odavde.
{94117}{94131}Idem u krevet.
{94288}{94355}Znaèi, tvoja žena se viða|s nekim totalnim gadom?
{94426}{94477}Kažeš da taj|ne progovara ni rijeè.
{94518}{94575}Kada prièaš o tome,|toliko se iznerviraš,
{94582}{94670}kao da si ti taj|koji je dobio nogu.
{94708}{94819}Brak je divna stvar, Jay.
{94854}{94942}To je rat, bitka,|grozno putovanje,
{94969}{95012}ali i razlog za život.
{95069}{95126}Zar nisi rekao da|ne igraš baš dobro?
{95133}{95182}Ne slušaj ga,|to nije istina.
{95193}{95236}Jay nije loš igraè.
{95267}{95300}Ali vratit æeš se ti,|siguran sam u to.
{95305}{95354}Veæ sam se malo vratio.|- Ne brinem ja za to.
{95383}{95446}Mislim da sam ti prièao o|toj ženi koju viðam srijedom,
{95474}{95517}i jebemo se.
{95534}{95575}Bolje i to nego ništa.
{95582}{95650}Ona uživa u tome,|i stvarno je dobra.
{95666}{95775}Ti vjerojatno nisi taj tip,|ali meni je to jako važno.
{95873}{95930}Kojim danom se viðate?|- Srijedom.
{95992}{96047}Srijeda je dobar dan|za mene.
{96064}{96109}Posao mi dobro ide.
{96117}{96191}A subotom bih se|najradije objesio.
{96250}{96322}Odakle ti ideja da|mene seks ne zanima?
{96349}{96398}Zato što ne prièam o tome?
{96536}{96622}Kažeš da ima muža?|- Nisam ništa rekao.
{96650}{96722}Ustvari, ne znam.|To je dobro pitanje.
{96759}{96806}Hoæemo li još|jednu partiju?
{96860}{96969}Veèeras nema predstave,|tu smo samo nas dvojica.
{96984}{97018}Nema predstave?
{97098}{97161}Ustvari, ja sam|samo u prolazu.
{97181}{97230}Da li tvoja žena glumi|u još nekoj predstavi?
{97238}{97279}Ma kakvi, ne.
{97326}{97486}Veèeras daje one svoje|satove glume u nekoj nedoðiji.
{97537}{97656}Victore, zar nisi tražio da ti|danas nešto pomognem? - Što?
{97700}{97778}Da, htio sam da odemo|do osiguravajuæeg društva.
{97839}{97923}Ali možemo i ostati|kod kuæe.
{97942}{98030}Kuda ideš? - Moram, imam|posla. - Ali, tek je dva!
{98040}{98178}Neæu sjediti tu cijeli dan.|I nije dva, nego deset do dva.
{98222}{98300}Ako netko bude zvonio,|ne javljaj se.
{98327}{98382}Neæe nitko zvoniti,|ali ipak se ne javljaj.
{98412}{98500}Mogli bismo i zajedno|to raditi, zar ne?
{99134}{99203}Ideš nekuda? - Da.
{99271}{99324}Nisi dolazila prošle srijede?
{99331}{99365}Nisam bio kod kuæe.
{99378}{99423}Dobro je. Nisam mogla.
{99502}{99545}Nismo se ni dogovorili,|je li tako?
{99556}{99609}Da. Ne. Znam. Da.
{99888}{99933}Hajdemo. Hoæemo li?
{99983}{100017}Što je?
{101743}{101782}Ne ovako.
{101798}{101830}Kondom.
{103993}{104038}Gideon! - Tracy!|- Dave!
{104607}{104650}Stigla sam. Hajdemo.|- Što ti se dogodilo?
{104660}{104692}Sada sam ovdje.
{104717}{104747}Hajdemo, spremna sam.
{104999}{105025}Što to radiš?
{105077}{105110}Hoæu tu staviti ruke.
{105182}{105270}To nije pipanje! Ne da mi|da je dodirnem kako treba.
{105285}{105334}Ne da mi da je pipnem.|- Samo nastavite.
{105345}{105396}To je glupo. Kako da radimo|ljubavnu scenu, kad ona neæe?
{105404}{105453}Nismo mogli ranije doæi,|isporuèivali su nam kauè.
{105460}{105506}Pa ste ga malo isprobavali?|- Idiote!
{105512}{105560}Koncentrirajte se|na scenu. Nastavite.
{105586}{105687}Pozdrav svima. - Kako si?|Èujem da ti prehlada prolazi.
{105737}{105805}Ne smiješ iæi. Smijem li|te poljubiti? - Da.
{105854}{105888}Mala moja Betty!
{105910}{105972}Zašto me zoveš "mala"?|I ja nisam Betty.
{105991}{106079}Mala moja Betty!|Pogledaj me u oèi.
{106108}{106184}Vidim zlatne toèkice|u tvojim oèima.
{106192}{106262}Poljubi me.|- Poljubi ti mene.
{106392}{106443}Ne znam zašto|se uopæe trudim.
{106534}{106619}Betty je kruta kao daska, nije|u životu nikoga dotaknula.
{106627}{106674}Dave je arogantan|kao i uvijek.
{106683}{106712}Smiješni ste.
{106723}{106795}Ne vjerujem ni jednu rijeè.|To nije ljubavna scena.
{106802}{106871}Sada je dosta.|- Oni se znaju godinama.
{106882}{106931}Pretpostavljam da je|veæ bilo "kontakta".
{106969}{107006}Ne, ovo je prvi put|da je dodiruje.
{107011}{107050}Sav se pretvorio u prste.
{107069}{107124}Izabrala si loš dan.|- U redu je. Odlièni su.
{107132}{107177}Možda ja ne znam|kako da napravim ovo.
{107185}{107279}Ali toliko sam se uživio,|da mi se èini da sam sam.
{107302}{107367}Ponekad si toliko u neèemu|što ti se dogaða,
{107375}{107444}da i ne registriraš osobu|pored sebe. - Možda.
{107457}{107516}Da li me razumiješ?|- Nastavi.
{107894}{107962}Betty, moramo|razgovarati nasamo.
{107993}{108086}Poæi æeš sa mnom? - I ja|želim razgovarati s tobom.
{108098}{108189}Želim te ljubiti|dugim, nježnim poljupcima.
{108444}{108560}Gdje? - U usta, po tijelu...
{108621}{108735}Mislim, gdje želiš da doðem?|- Doði k meni doma.
{108849}{108896}Kada? - U redu.
{108911}{108938}Stanimo ovdje.
{108950}{108980}Dosta je za danas.
{108985}{109030}Kad ne ide, ne ide.|Sljedeæi par.
{109041}{109075}Ali, prošli tjedan,
{109081}{109167}kada smo improvizovali,|rekla si da je dobro.
{109177}{109257}Bio sam spreman jebati je|sada i ovdje, volio sam je!
{109268}{109317}Znam samo jedno...|- Ne znaš ti ništa!
{109326}{109424}Znam da je to što radiš|trebalo uèiniti da Betty
{109430}{109491}pokupi sve svoje stvari,|naðe izgovor da izaðe,
{109499}{109550}i prijeðe cijeli London|da bi došla kod tebe.
{109557}{109598}Zar nisam ja radio baš to?
{109607}{109648}Tko kaže da je bilo|daleko od toga?
{109653}{109768}Nitko ne kaže, ali je!|Mora biti.
{109777}{109801}Tako sam sretna!
{109818}{109858}Razmišljala sam|o tome da odustanem.
{109868}{109963}Izgubila sam volju za glumom|jer tu nikada neæe biti love...
{109977}{110033}Ali kada sam vidjela|ono dvoje obiènih ljudi
{110043}{110082}koji su bili naprosto sjajni...
{110093}{110194}Zaboravila sam nešto,|moram se vratiti. Ti idi.
{111496}{111534}Jesi li dobro?
{111579}{111633}Jesam. Samo sam...
{111770}{111810}Upravo sam izgubila nekoga.
{111818}{111943}Nekoga bliskog?|Je li bilo iznenada?
{111983}{112018}Žao mi je.
{112483}{112554}Oba mala prsta mi|se krive u stranu.
{112610}{112680}Izgleda kao da svaka ruka|ima svoju vlastitu volju.
{112787}{112898}Ako mene pitaš, maloprije si|bila gadura prema meni i Daveu.
{112906}{112951}Ali nemoj da ti bude žao.
{112959}{113079}Kada me netko tako maltretira,|to je kap koja prelije èašu.
{113137}{113212}Ali divim se jednoj|stvari kod tebe.
{113248}{113333}U sekundi si u stanju da se|usprotiviš cijeloj grupi.
{113347}{113431}Tada se ponosim tobom.|Nije lako biti grozan.
{113437}{113571}Betty, šuti. Nitko te ništa|ne razumije kada prièaš.
{113579}{113647}U redu. Ali ovo je|pravi posao za tebe.
{113670}{113729}Znam to jer sam išla i|na druge satove glume.
{113753}{113785}Dosta je bilo!
{113799}{113873}Ja te ne razumijem|ni jednu jedinu rijeè!
{113899}{113977}U redu. Oprosti,|gnjavim te.
{114036}{114145}Ništa niste nauèili,|a nisam ni ja.
{114200}{114258}Ipak, ne predajemo se lako.
{114346}{114437}Ja znam biti grozna,|ali vi ipak dolazite.
{114467}{114570}Stalno mi govore da sam|savršena za neku ulogu,
{114596}{114633}a ipak me odbijaju.
{114647}{114723}Kada nemaš talenta,|jedino ti ovo preostaje.
{114737}{114810}Nastavljaš raditi|da ne bi iznevjerila ljude.
{114821}{114933}Odraðuješ utorke i srijede,|petljaš nešto.
{114942}{115026}To radimo zajedno.|- Ne, ja to radim sama.
{115383}{115407}Hajde, Vic!
{115410}{115500}Kog vraga ti tražiš ovdje?|Odakle si izmilio?
{115509}{115548}Postaje vam dosadno,|je li to u pitanju?
{115555}{115620}Nismo došli zbog tebe,|nego zbog atmosfere.
{115636}{115668}Kako ste me osramotili!
{115675}{115726}Preko telefona|je zvuèalo super.
{115733}{115812}Moram ti reæi, nalaziš|sve bolja mjesta za umiranje.
{115824}{115918}Jebote, sada je tri ujutro.|Ostavi me na miru!
{115933}{116003}Vodite tog idiota odavde.|Pokušao me prebiti.
{116035}{116119}Požuri, umrijet æeš od hladnoæe.|- Ja se nikada ne razbolijevam.
{116128}{116187}Od piva se više ne mogu|napiti.
{116218}{116273}Onaj kreten mi je rekao:|"Idi kuæi, èekaju te".
{116285}{116328}Što sam mu ja uèinio?|- Vic!
{116342}{116391}Zašto tako prièa sa mnom?
{116401}{116456}Zar ne vidiš da te|svi zajebavaju?
{116480}{116533}Hlaèe ti vise|i vidi ti se dupe.
{116553}{116594}Jebote, pogledaj se!
{117070}{117148}Kad Jay digne ruke od tebe,|on ti to i ne kaže.
{117161}{117257}Smiješka se dok odlazi i|razmišlja o neèemu drugom.
{117268}{117346}Jay ti je pravi folirant.|Možeš izrabljivati ljude,
{117357}{117409}biti nezahvalan,|i da te boli kurac.
{117450}{117495}Nije mi jasno o èemu|vas dvojica prièate.
{117512}{117557}Što ti znaš o životu?
{117566}{117605}Da li si ikada živio|s nekim?
{117613}{117654}Što te briga za|moj život. Odjebi!
{117706}{117735}Moja košulja!
{117844}{118010}Jay stalno šuti kao zaliven.|Ne govori ni s kim se jebe.
{118072}{118154}Ti se stalno žališ,|a Jayu je gore nego tebi.
{118162}{118338}Ti radiš svašta, i bude ti|lakše. A Jay se razbolijeva.
{118353}{118455}Možda ne zna voljeti,|možda nikada nije nauèio.
{118461}{118520}To se ne dogaða svakome.|- Zašto to kažeš?
{118534}{118571}Pièko mala!
{118650}{118691}Jebite se obojica.
{118983}{119041}Mislim da imam|Alzheimerovu bolest.
{119069}{119099}Ne šalim se.
{119127}{119203}Pipni, što mi je ovo?
{119247}{119331}Vidi, ona lijeva te|nešto gleda.
{119358}{119419}Sigurno æe ti biti bolje nego|da se jebeš sa šeficom.
{119448}{119476}Hajde!
{119701}{119758}Poznavala sam|njihovog pjevaèa.
{119770}{119829}Družili smo se na faksu.|Bio je fin, baš pametan.
{119842}{119863}I band mu je bio dobar.
{119873}{119982}Nikada ništa nisu postigli,|ali imali su potencijala.
{119995}{120033}Trebali su otjerati|onog glupog gitarista
{120046}{120126}koji je stalno prièao|neke gluposti
{120160}{120204}i bio užasno uobražen.
{120224}{120286}Dali su mu nogu,|pa je postao bubnjar.
{120300}{120362}Èudi me da ih znaš.|- Znaèi, ovo je tvoj stan?
{120376}{120431}Da. Živjela sam tri|ulice odavde s prijateljicom,
{120441}{120471}ali smo se posvaðale.
{120480}{120556}To mi teško pada, jer smo|bile najbolje prijateljice.
{120570}{120644}Natasha mi se sviða,|ali to ipak nije isto.
{120655}{120709}Treba vremena da nekoga|zaista upoznaš.
{120754}{120811}Možda æemo ti i ja biti|stvarno dobri prijatelji.
{120841}{120927}Sviða mi se ovdje. To je|moj stan, ja sam ga sredila.
{120935}{121029}Kada ga ljudi vide,|saznaju nešto o meni.
{121038}{121136}Vide zidove, ove stvari ovdje,|i vide dio mene...
{121856}{121897}Doði. - Što je?
{121966}{122003}Ostani da plešemo.
{122018}{122053}Hajde.
{122102}{122135}Nemoj.
{122213}{122307}Žao mi je.|Jako mi je žao.
{122524}{122560}Oprosti!
{122618}{122656}Zakljuèano je.
{122725}{122778}Stvarno si stari gad.
{122982}{123074}Deèki, što ima u piletini?|Uzmite još malo.
{123118}{123175}Ne volite kožu?|- Ne, hvala.
{123187}{123228}Tko æe prsa? - Ja.
{123236}{123284}Siguran si da neæeš ništa?|- Da.
{123341}{123437}Deèki, dugo se nismo vidjeli.|- Da.
{123543}{123587}Donio sam ti ovo.
{123648}{123697}Danas je srijeda, zar ne?
{123743}{123783}Je li lijepa?
{123810}{123896}Tko je ona?|- Ne poznaješ je.
{123933}{124025}Što æeš napraviti?|- Brinuti se o sebi, eto što!
{124071}{124111}Na kraju krajeva,|netko mora.
{124249}{124323}Sve je u redu? Vidimo se.|- Bok.
{124350}{124388}Pobijedio sam ga! Bok.
{124548}{124669}Jesi li dobro?|- A ti? - Da.
{124725}{124755}Hajdemo.
{125170}{125246}Bok, Jay. Ako hoæeš,|dat æu ti jednu partiju. - Da.
{125323}{125408}Drugi dio mi se više svidio.|Zabavniji je nego prvi.
{125424}{125493}A i kraæi je, pa poslije|imaš više vremena za piæe.
{125503}{125569}Bok, Jay! - Bok, Andy.|- Drago mi je da te vidim.
{125576}{125619}Postao si redovna|mušterija.
{125633}{125674}Svidjet æe ti se drugi dio.
{125683}{125753}Završit æu cigaretu vani.|- U redu. - Oprostite.
{125805}{125875}Ne možeš izdržati|drugi dio, zar ne?
{125907}{125935}Uživaj.
{126727}{126825}Pogledaj kolika mi je sjena.|- Preko cijelog plafona!
{126833}{126880}Prestala je kiša.|Odakle dolazi ta glazba?
{126885}{126971}Iz plesne dvorane preko puta.|- Da li ste za jedan ples?
{126987}{127044}Možda je vaš program|veæ popunjen? Da pogledam.
{127053}{127117}Svi plesovi su zauzeti.|Morat æu nešto precrtati.
{127134}{127196}Valcer?|- Ali ja ne znam plesati!
{127206}{127263}Opet ta tvoja inferiornost.|- Ali, stat æu ti na nogu!
{127273}{127301}Prepusti to meni.
{127349}{127392}Ispruži malo ruke.
{127408}{127478}Opusti se.|- Ovako? O, Bože!
{127484}{127518}To je veæ puno bolje.|- Stvarno?
{127525}{127560}Puno, puno bolje!|- O, Bože!
{127573}{127630}U što smo to udarili?|- U stol. - Nešto je palo?
{127659}{127717}Nadam se da nije onaj mali|stakleni jednorog. - Je.
{127748}{127817}Je li razbijen? - Sada je|isti kao i svi drugi konji.
{127827}{127952}Izgubio je... - Rog. Nije|važno. Možda je tako i bolje.
{127958}{127985}Nikada mi neæeš oprostiti.
{127992}{128041}To ti je sigurno bio|omiljeni stakleni komad.
{128231}{128238}Oprostite.
{128422}{128508}Hajde, dvije ruke su|bolje nego jedna.
{128529}{128574}Osim toga, hoæu da|upoznaš moju ženu.
{128583}{128617}Hajde.
{128674}{128746}Ovo je Claire, moja žena.|- Bok, Jay.
{128754}{128830}Velika glumica, kao što znaš.|- Andy, opet si tu?
{128838}{128879}Jay jako voli kazalište,
{128913}{128980}iako skoro ništa nije vidio.|- Kako to misliš?
{128987}{129092}Uvijek ode na pauzi. - Uvijek?|Ne izgledaš kao agent.
{129135}{129219}Svratio si vidjeti kako smo?
{129238}{129299}Šteta. Moje najbolje scene|su u drugoj polovici.
{129372}{129444}Jay je veliki ljubitelj|Tennesse Williamsa.
{129467}{129511}Ja ne bih išao tako daleko.
{129525}{129592}Sve žene su mu nekako|histeriène, zar ne?
{129617}{129732}Jay je onaj tip koji je|ostavio ženu i sada je mrzi.
{129748}{129797}Sigurno sam ti prièao|o njemu.
{129817}{129899}Viða se s nekom ženom|jednom tjedno.
{129927}{129980}Koliko sam ja razumio,|ima tu i više od viðanja.
{130011}{130112}Idem ja gore. Laku noæ svima.|- Laku noæ, dušo.
{130124}{130233}Andy! - Da, cipele...|Nazdravlje.
{130310}{130346}Vidimo se za minutu.
{130843}{130888}Nisam završila|s oblaèenjem.
{130971}{130997}Idem. Vidimo se kasnije.
{131010}{131068}Bio mi je drago. Ostaješ|li da popijemo nešto?
{131171}{131210}Da zatvorim ovo?
{131418}{131452}U jednom trenutku...
{131457}{131502}Pošto ti nisi ništa govorila,|pitao sam se...
{131509}{131543}Žena koja toliko šuti...
{131550}{131615}Sve to što sam skrivala|je zastrašujuæe, zar ne?
{131631}{131725}Znaš što? Ovo je|baš pravo ohrabrenje.
{131741}{131800}Zakletve, vjernost,|podrška i sve to.
{131806}{131841}Zašto bi ti to propuštala?
{131847}{131904}Ne bi bila ni prva,|ni zadnja.
{131986}{132037}Ali nisam ja zato|došao ovdje.
{132118}{132148}U jednom trenutku...
{132157}{132202}Samo da budem jasan.
{132213}{132252}U jednom trenutku|sam pomislio
{132262}{132321}da, ako je ono bilo|sve što si željela,
{132328}{132424}to je zato što si znala|nešto što ja nisam.
{132432}{132555}Mislio sam da si našla nešto.|Mislio sam da si ispred mene,
{132567}{132633}i da æeš mi na kraju|reæi to što znaš.
{132641}{132752}To bi bilo super, da mi|jednom kažeš to što znaš.
{132894}{132968}A ti si, naravno,|držala jezik za zubima.
{133486}{133566}Što ti tražiš s njim?|- On mi je muž.
{133582}{133606}Oprostite.
{133647}{133692}Htio si razgovarati.
{133699}{133760}Pa evo, razgovaramo.
{133766}{133809}Ono je na raèun kuæe.
{133855}{133931}Znaèi, ti si jedan|nesretan èovjek
{133938}{134038}koji se uspio vratiti.|Je li tako?
{134062}{134103}Dobro je. Što|drugo da kažem?
{134129}{134193}Dobro je da te ovako|vidim posljednji put.
{134204}{134284}Inaèe bih brinula|kao neka glupa krava.
{134346}{134399}Na trenutak si izgledala|zaista tužno.
{134407}{134476}Ali sjeti se svega što je|tvoje i èemu se vraæaš.
{134484}{134539}Svoje obitelji, djeteta,|muža koji te voli,
{134544}{134585}posla u kazalištu|koji toliko voliš.
{134595}{134634}Tebe svi slušaju, zar ne?
{134677}{134740}Èak i ja, koji te ne poznajem,|niti ti mene poznaješ,
{134747}{134802}stojim ovdje i slušam te,|interesiram se za tebe
{134816}{134894}u nekom bijednom kazalištu|koje smrdi na pišaèu.
{134954}{134992}Gospode!
{135001}{135118}To je sve tvoja igra, zar ne?|- Nisam te ovako zamišljala.
{135127}{135168}Nisi me ovako zamišljala?
{135178}{135208}Koji si ti zamor!
{135215}{135264}Sigurno si onog prvog dana|bio jako iznenaðen
{135269}{135353}što te ja želim|i što se ne bunim,
{135362}{135458}i što se èini da me ne|boli to što ti stalno šutiš.
{135475}{135528}Nisam puno razmišljala|o tome zašto ti šutiš.
{135536}{135583}Nisi me ovako zamišljala?
{135594}{135635}Ja tebe nisam|uopæe zamišljao.
{135643}{135731}Tako mi je puno jednostavnije,|i sada je sve to riješeno. Super.
{135738}{135808}Volim kada se stvari završe|bez gubljenja vremena.
{135816}{135898}Bok, Jay. - Bok.
{135907}{135937}Odmah se vraæam.
{136021}{136138}Mama je veèeras bila|dobra, zar ne? - Da.
{136181}{136350}Zar nije ona uvijek dobra?|- Tata kaže da je neuravnotežena.
{136408}{136480}Ali on gleda samo|prvih par predstava,
{136489}{136544}pa ne može usporediti.
{136560}{136603}Ja volim gledati|predstavu puno puta,
{136621}{136697}jer ne razumijem sve iz prve.
{136805}{136912}Imaš li djevojku, nekoga|tko ti se sviða u školi?
{137020}{137102}Kako stoje stvari|meðu vama? - Pa...
{137114}{137198}Hajde, idemo.|Pozdravi se.
{137224}{137285}Hoæeš li biti ovdje|u èetvrtak?
{137424}{137520}Kada si u žalosti,|mislim da je najbolje...
{137532}{137579}...da nastaviš|živjeti normalno.
{137589}{137636}To je jedini naèin|da se nosiš s tim.
{137647}{137809}Ali zašto ipak ne kažeš|šefu da ti je netko umro?
{137857}{137931}Znaš, Betty, ustvari|nitko nije umro.
{138051}{138143}Ako nitko nije umro,|onda to ima veze s tobom.
{138242}{138330}Ako osjeæaš da umireš,|voljela bih biti s tobom.
{138359}{138424}Ustvari, polaskana sam|time što sam ovdje.
{138433}{138507}Kada sam ja umrla,|nikoga nije bilo tu.
{138516}{138588}Morala sam sama|proæi kroz sve.
{138606}{138708}U redu, uspjelo mi je, ali|društvo ipak nije naodmet.
{138743}{138784}Možda bih se trebala|vratiti.
{138937}{138996}U principu, ako si ozbiljna,
{139003}{139058}napravi program|za dan svoje smrti.
{139077}{139126}Prvo, zezanje s idiotima.
{139132}{139177}To smo radile sinoæ.
{139203}{139275}Onda moraš nekome|nešto reæi,
{139285}{139359}nešto što si stvarno jako|željela, bilo to dobro ili loše.
{139366}{139419}Nešto što nikada|ne bi rekla.
{139426}{139520}Jer na dan svoje smrti imaš|potpunu slobodu govora.
{139685}{139765}Srela sam jednog èovjeka.|Drugaèiji je od mene.
{139772}{139870}Ja ne znam usmjeriti svoju|energiju, a on je vrlo odluèan.
{139883}{139973}A onda je jednoga dana otkrio|kako da to usmjeri protiv mene.
{139980}{140091}Jednostavno je uzeo natrag|sve što mi je dao.
{140099}{140183}Mislim da je baš to|i htio, sve sjebati.
{140253}{140291}Funkcioniralo je.
{140298}{140370}Izmeðu nas je|funkcioniralo. - Da.
{140437}{140521}Što se dogodilo onoga dana|kada si ti umrla?
{140532}{140632}To je prošlost.|Sada je to iza mene.
{140678}{140780}Nema tu više ništa|da se kaže... hvala Bogu.
{141214}{141306}Claire kaže da hoæe|napustiti satove glume.
{141314}{141390}Jako sam tužna zbog toga.|- Malo je umorna, to je sve.
{141401}{141456}Previše daje sebe,|stalno joj to govorim.
{141593}{141671}Putuje tako daleko da to traje|duže nego sami satovi.
{141680}{141745}Malo je zbunjujuæe,|ali znaš što hoæu reæi.
{141767}{141828}Izvoli. Ne može se tu ništa|uèiniti, takva ti je Claire.
{141839}{141898}Oduèila je oprobati se|kao glumica,
{141938}{141999}iako nije više bila|u cvijetu mladosti,
{142014}{142121}niti je to prije radila.|Ali krenula je punom parom.
{142267}{142302}Kada smo se upoznali,
{142364}{142467}ja sam se oporavljao od veze|koja je bila vrlo bolna.
{142478}{142552}Nije mi se žurilo|uæi u novu vezu.
{142565}{142649}Nisam to planirao.|Ali ona me vidjela.
{142664}{142773}Ti si mene izabrala. Krenula|si ravno na svog Andyja.
{142890}{143040}Vrlo jaki ljudi mogu uèiniti|potpuno neshvatljive stvari.
{143059}{143102}Je li tako? - Da.
{143279}{143317}Moram iæi.
{143356}{143436}Drago mi je da si došla.|- Idem.
{143483}{143521}Odbacit æemo te.
{143625}{143657}Sve je u redu? - Da.
{144273}{144320}Tu smo. - Dobro.
{144630}{144660}Hvala vam.
{144666}{144694}Vidimo se u utorak.
{144968}{145048}Betty je simpatièna,|zar ne? - Da.
{145088}{145137}Baš sam je zavoljela.
{145275}{145332}Neæu otiæi.
{145426}{145609}Evo, Claire govori Andyju|da æe ostati s njim.
{145623}{145773}U redu. Nisam ni brinuo.
{146316}{146373}Jesi li ti pronašao Jaya,|ili je on potražio tebe?
{146382}{146418}Boli me kurac za sve to!
{146426}{146508}Znaš što je najtužnije,|što me najviše boli?
{146517}{146589}To što ti nikada neæeš|biti glumica! Nikada!
{146599}{146689}Nije mi lako to reæi,|ali to je istina.
{146700}{146766}Moraš se veæ jednom|suoèiti s njom!
{146895}{147020}Stvarno se pitam što|tvoji uèenici imaju od tebe.
{147031}{147066}Ipak, oni te vole.
{147078}{147175}I to je nešto, kada|nema nièega boljeg.
{147200}{147282}Znam da i ja snosim|dio odgovornosti za ovo.
{147290}{147393}Od poèetka nisam|vjerovao u to. Nikada.
{147442}{147516}Ali morao sam potpuno|uletjeti u to, kao neki idiot.
{147527}{147565}Morao sam podržavati|tvoje fantazije,
{147574}{147615}djevojèica koja|ne zna što da radi,
{147623}{147657}pa završi radeæi bilo što.
{147663}{147745}Kao ova budala što vozi|taksi svaki bogovetni dan.
{147797}{147908}Što se tièe onog idiota koji|misli da je jako pametan,
{147917}{147966}jednoga dana...|- Eno ti mušterije.
{148112}{148175}Znaš što? Nisam|uopæe iznenaðena.
{148181}{148234}Sjeæaš li se svog izraza lica|kada smo se upoznali?
{148242}{148293}Sada ti na licu vidim|tu istu patnju.
{148306}{148340}Dobro ti pristaje.
{148362}{148440}Ti si osoba s najmanje života|u sebi od svih koje znam.
{148447}{148527}Moj odnos sa Jayom je|za tebe odlièna prilika.
{148534}{148585}Bijedna mala prijevara.
{148591}{148669}Naravno da si protiv takvih|stvari. Tko ne bi bio?
{148685}{148744}U redu je. Andyja|ništa ne zanima,
{148750}{148805}ali zato poznaje London|kao svoj dlan.
{148852}{148987}Ti èak ne znaš ni tko sam ja.|Ne znaš kako da me povrijediš.
{149000}{149032}Da me imalo poznaješ,
{149039}{149127}znao bi da patim zato|što nemam talenta,
{149136}{149193}ali da neæu umrijeti|zbog toga!
{149590}{149676}Poèetkom tjedna obièno|ne izgledaš tako nervozno.
{149700}{149726}Joel!
{149770}{149815}Isto, molim.
{149839}{149878}Da dobro radiš svoj posao,
{149886}{149943}ne bi imao vremena da|primijetiš kako ja izgledam.
{150345}{150379}Odlièno mjesto.
{150459}{150498}Daj jedno pivo.
{150602}{150667}To ti je kao da se viðaš|s kurvom, zar ne?
{150675}{150751}Jednom tjedno,|bez razgovora.
{150769}{150872}Ipak, nekako ti je rekla da|je udana. Baš je pažljiva.
{150880}{150952}To ti je da se ne bi|previše zanio.
{151039}{151160}Sigurno je to radila i prije.|Nema šanse da si joj ti prvi.
{151175}{151244}Prestao sam.|Više je ne viðam.
{151320}{151379}Baš sam htio predložiti|da je dijelimo,
{151404}{151476}ali izgleda da nemamo|više što dijeliti.
{151495}{151594}Jedan dan tjedno|mi ne bi sjebao brak.
{151610}{151661}Šalim se.
{151894}{151966}Volim je sve više|kako vrijeme prolazi.
{152049}{152117}Samo sam ti to|htio reæi.
{153532}{153606}Imaš li crnih vreæa?|- Imam, donijet æu ih.
{153998}{154045}Ja sada idem.
{154109}{154166}U redu. Hvala ti,|Victore.
{154571}{154667}Idem. Uzet æu jaknu dolje.
{156013}{156097}Mislila sam da si možda|rekao nešto što nisam èula,
{156109}{156139}i da mi to sada zamjeraš.
{156148}{156212}Nije mi jasno kako ja tebi|mogu bilo što zamjerati.
{156219}{156274}Jesam li nešto propustila?|Što sam propustila?
{156283}{156342}Pitaj me sve što želiš,|sada sam ovdje.
{156350}{156401}Evo, pitat æu te. Zašto|si rekla Andyju?
{156410}{156471}Nije to bilo tako važno.|Nije bilo vrijedno truda.
{156489}{156596}Cijela ta frka ni zbog èega.|Možda je to kod vas tako.
{156605}{156660}Svaki put mu kažeš,|i to je to...
{156692}{156797}Ti nisi netko koga pozovem,|i on doðe, jebe se i ode...
{156809}{156889}...iz èiste zabave.|Što sam trebala osjeæati?
{156899}{156954}Kakva sam ja to|trebala biti?
{156963}{157026}Tko bih ja trebala biti|da bi svi bili zadovoljni,
{157033}{157101}da doðem kod èovjeka|i bacim mu se u zagrljaj,
{157106}{157155}zato što ja to želim.
{157223}{157289}Dugo nisam nikoga željela.
{157337}{157396}S tobom sam htjela|poèeti ispoèetka.
{157451}{157519}Ovo se obièno|ne govori, zar ne?
{157763}{157878}Znam da si mi dala nešto|što nisam ni tražio.
{157885}{157982}To nitko ne radi, i trebao|bih ti biti zahvalan.
{157999}{158098}Ipak, èini se da ti|ja to samo zamjeram.
{158389}{158522}Razdire me to što si|ti s nekim tako bliska.
{158599}{158666}Vaša bliskost me razdire.
{158792}{158856}Evo, ja sam razveden,|imam dvoje djece
{158864}{158931}koja se navikavaju|na to da ja nisam tu.
{158943}{158982}Imam nekoliko prijatelja.
{158989}{159050}Mislim da sam im|ja najbolji prijatelj.
{159056}{159094}To je veæ nešto.
{159120}{159200}Ja sam i "èovjek za srijedu"
{159224}{159345}jednoj ženi od koje|nikada ništa nisam tražio,
{159383}{159453}a ona je zadovoljna time,|to joj nije problem.
{159543}{159598}A mene to stvarno ubija...
{159658}{159688}Sve...
{160078}{160160}Ne znam što ja ovdje|tražim. Žao mi je.
{160192}{160249}Ništa nisi propustila...
{160368}{160431}...zato što ja nisam govorio.
{160441}{160496}Nisam znao da æe biti ovako.
{160522}{160621}Nisam znao da æu se ovako|èvrsto vezati za tebe.
{160628}{160704}Mislio sam da æe to|samo proletjeti.
{160833}{160886}Ostani sa mnom.
{160946}{161007}Ako si se vratila, ostani.
{161041}{161079}Vrati se...
{161122}{161175}Ostani.
{161196}{161301}Sada. Ostani sada.
{161506}{161559}Ne, Jay.
{161681}{161709}Ne.
{161897}{161940}Jesi li ga ostavila?
{161993}{162025}Ne.
{162330}{162393}Oprostite, ali ja sada|moram iæi.
{162403}{162479}Je li ovo za bacanje?|Oprostite.
{162497}{162544}Doæi æu kasnije da završim.
{166144}{166183}Idem.
{166555}{166666}Subtitles by:|M O Z E N