{1}{1}25.000
{1115}{1145}SREÆA
{1147}{1184}NESREÆA
{1192}{1223}SREÆA
{1225}{1254}NESREÆA
{2000}{2100} PEH DO DASKE 
{2434}{2510}- 'Jutro, Oscare. | - 'Jutro, gðice Albright.
{2512}{2631}Teško æete dobiti taksi u ovoj gužvi. | Nemate kišobran?
{2633}{2706}Zbilja misliš da mi treba?
{2809}{2866}Oèigledno ne.
{2873}{2905}SRETNICA
{2970}{3039}Hvala. Želim ti ugodan dan.
{3107}{3155}Zgodno. Bog.
{3262}{3368}Prvo, križanje 66. i Broadwaya. | Moram stiæi za èetiri minute.
{3370}{3460}- Dobro. Samo sanjaj. | - Bog. Dana?
{3462}{3552}WNYH, vi ste nas sedmi nazvali. | Znate koja je pjesma u pitanju?
{3554}{3653}- Ups, ponovo pogreška. Oprostite. | - Toèan odgovor. Pobijedili ste.
{3689}{3808}Pet zelenih zaredom. | Krenulo nam je, stari.
{3810}{3935}Dana, danas stižem ranije, pa æu | stati kod Balduccija. Može kolaèiæ?
{3937}{4069}Ja sam vladar svemira. | Pozitivna energija, pozitivne stvari.
{4127}{4165}NESRETNIK
{4320}{4388}Savršeno. Vodi psa u šetnju.
{4440}{4586}Dobro jutro, g. Phillips. Predstavio | bih vam najbolji bend New Yorka.
{4588}{4660}Idemo.
{4662}{4706}Super.
{4743}{4799}Novèiæ za sreæu.
{5062}{5116}G. Phillips, oprostite!
{5392}{5442}Podigni.
{5555}{5622}- Držiš ga? | - Zaobiði ih.
{5624}{5679}Tako.
{6028}{6096}Zadržite dizalo.
{6163}{6221}- Hvala. | - Nema na èemu.
{6465}{6557}Hajde, zlato. Zlato se pokakalo.
{6559}{6598}Idemo.
{6739}{6795}Tvoja me kakica skupo stoji.
{6885}{6934}Sretni?
{7090}{7144}'Jutro.
{7387}{7451}Slatko.
{7975}{8081}- Makni se. Što to radiš? | - Dobro ste? Oprostite.
{8083}{8164}Pomoæi æu vam. | Ne vrištite. Nisam namjerno.
{8166}{8235}- Upomoæ! | - Ti!
{8237}{8342}- Ovo nije... Nije dobro. | - Upomoæ!
{8344}{8404}Ni makac!
{8418}{8530}- Korak bliže i razbit æu te. | - Trebam pojaèanje. Napad u parku.
{8532}{8596}- Ni makac! | - Gumb mi je pukao.
{8598}{8668}Zaboravi. Potjera pješke.
{8670}{8777}Naš posao je glazba. | Snimi to. Moramo to riješiti.
{8779}{8860}Stanite. | Dobro jutro, g. Phillips.
{8862}{8931}- Imam novi... | - Imam te.
{8933}{9065}- G. Phillips. Poslušajte. | - Daj mi ruku. Smrdiš na govno.
{9103}{9228}Možete li me odvesti u 36. postaju? | Ondje su dobri sa mnom.
{9275}{9332}Obeæavaš? U 18 h?
{9334}{9413}Izgledat æu baš ovako.
{9415}{9483}Onda stižem u 17:30 h.
{9642}{9739}- 'Jutro, Maggie. | - Nešto si mi vesela jutros.
{9741}{9884}Brad Pitt i Jude Law imaju dijete | koje sam upoznala u dizalu.
{9886}{9963}Narudžba iz Balduccija.
{9965}{10048}Što je to s ovim tijelom? | Novi kaput?
{10050}{10114}Vidiš? Pokusni uzorak u pola cijene.
{10116}{10175}Taj kaput je nekoga upoznao.
{10177}{10270}"David Pennington". | Vlasnik Boston Celticsa?
{10272}{10351}- Ne, ludice. Njegov sin. | - Svaka èast.
{10353}{10416}I ja sam imala dobro jutro.
{10418}{10498}Saturn mi je poravnat s Neptunom.
{10500}{10570}Dana, znaš da to nema osnove.
{10572}{10669}Moja nova pjesma dobila je | pristojnu odbijenicu od 2-Tone Records.
{10671}{10765}Znaš što kažu -jedna se vrata zatvore, | da bi se druga otvorila.
{10767}{10859}Kad smo kod vrata, | kada je sastanak s Phillipsom?
{10861}{10903}Sada.
{10905}{10995}Moram voditi bilješke. | Vidimo se kasnije.
{10997}{11076}- Imaš jednog viška? | - Hoæeš dijetalni?
{11205}{11250}Gdje su svi?
{11419}{11503}Procjene od prošlog tjedna | su 470.000.
{11505}{11592}Zato zaslužujemo | izlog trgovina.
{11594}{11730}Reci da sam ja tako rekao. | Damon Phillips je to rekao. Prekidam.
{11732}{11818}- Mislio sam da imamo sastanak. | - Stižu. Ako možete...
{11820}{11926}Ovo je velika uvreda. | D nikoga ne èeka.
{11928}{12027}Tako je. Nikoga. | Bijesan je. Zar ne?
{12029}{12086}Naravno da sam bijesan.
{12088}{12166}Trebaju stiæi svaki tren.
{12168}{12280}Vi to ozbiljno? | Sara, uèini nešto.
{12460}{12536}Dobila sam poruku od gðice Braden.
{12538}{12703}Ubacuje još neke sitnice | u posebnu prezentaciju za vas i stiže.
{12705}{12827}Dobro. Znate li koliko je Downtown | Masquerade Records zaradio lani?
{12829}{12894}Znam. 507 milijuna. Zarada.
{12896}{12990}Onda znate koliko stoji | minuta mojega vremena.
{12992}{13045}964 dolara.
{13047}{13155}- Puno. Nisam oèekivao toliko. | - Ukljuèeno je i kada spavate.
{13157}{13227}Zaraðujem i dok pas kaka?
{13229}{13302}- Skupa sranja. | - Ti bokca.
{13304}{13438}Onda razumijete zašto ne smijem | gubiti vrijeme. A ovdje ga gubim.
{13440}{13572}Jasno mi je. Dajte mi trenutak | i ja æu vam je održati.
{13585}{13718}Ako neæe vrijediti minute vremena, | platit æu vam 965 dolara.
{13720}{13790}Mislim da niste dovoljno plaæeni.
{13907}{13975}Nadam se da imate èekove sa sobom.
{13977}{14032}JUŽNA POLICIJSKA POSTAJA
{14257}{14331}Ne mogu vjerovati da poèinje kiša.
{14485}{14567}Pustite prvo mene.
{14569}{14614}Idiot.
{14872}{14959}Damone. Oprosti što si morao èekati.
{14991}{15044}Sa sirom. U redu.
{15046}{15136}- Samo da uzmem dosje i poèinjemo. | - Ne, gotovi smo.
{15138}{15211}- Molim te. Dizalo se zaglavilo. | - Što?
{15213}{15293}Gðica Albright mi je iznijela | èitavu strategiju.
{15295}{15399}Sjajna je. | Pogotovo dio s partyjem.
{15401}{15503}- Party? | - Da, proslava za Masquerade. Super je.
{15505}{15556}To ti se svidjelo?
{15558}{15673}Sjajan naèin predstavljanja glazbenika, | odbija se od poreza i za dobru stvar.
{15675}{15758}Znaš da nikad ne odbijam party.
{15760}{15814}Što kažeš?
{15854}{15920}I ja volim dobar party.
{15935}{15990}Nemoj to raditi.
{15992}{16053}Sve je spremno, g. D. Auto èeka.
{16055}{16113}Proslava za Masquerade?
{16147}{16299}Oprostite, gðice Braden. Imala sam | bilješke sa sastanaka i improvizirala.
{16334}{16431}Onda te èeka organizacija partyja.
{16433}{16537}- Dobro. | - Naravno, trebat æeš svoj ured.
{16539}{16611}- Što? Ja? | - Tvoja zamisao, ti si glavna.
{16613}{16707}Sara, pronaði Ashley novi ured | i kreditnu karticu tvrtke.
{16709}{16846}- Hvala, gðice Braden. | - Molim te, Ashley. Zovi me Peggy.
{16937}{17006}- A ti si? | - Dostava pošte.
{17008}{17155}Svejedno. Bez brige, Ashley. | Pratit æu svaki tvoj potez.
{17378}{17435}Katy, stigao sam.
{17544}{17626}- Bog, Jake. | - Što ti se zbilo?
{17638}{17754}- Deèki iz èetvrtog razreda. | - Ti su najgori. Što su koristili?
{17756}{17840}- Super ljepilo. | - Znam kako je.
{17842}{17895}Bar si imao bolji dan od mene.
{17897}{17949}- Burger? | - Jasno. Za tebe s keèapom.
{17951}{18006}- Katy, gdje mi je pletenica? | - U peænici.
{18008}{18100}Drži pletenicu u peænici? | Teta Martha.
{18131}{18194}Vraæam se nakon smjene u ponoæ.
{18196}{18233}Super.
{18235}{18305}Kloni se nevolja.
{18307}{18387}- Volim te. Katy, pazi na njega. | - Pripazit æu je.
{18389}{18439}- Vidimo se. | - Spreman?
{18441}{18552}Èekaj. Hoæe li peæi? | Sviða mi se ovako.
{18554}{18627}Neæe peæi ako miruješ.
{18656}{18714}Miruj. Sve æe biti u redu.
{18716}{18803}Miruj. Je'n, dva, tri.
{18805}{18901}Evo ga. Tako. | Kako se kaže?
{18903}{19005}- Hvala, Jake. Ti si moj junak. | - Daj pet.
{19007}{19124}Ovo æu uzeti. | Mogao bi to progutati.
{19126}{19183}- Bog. | - Vidimo se.
{19303}{19366}Ne opet.
{19374}{19493}- Kamo te vodi? | - Na košarku. Igraju s Philadelphijom.
{19495}{19580}- Nije seksi. Ovdje ili u gostima? | - U gostima.
{19582}{19665}Pogaðat æu. Privatnim mlažnjakom | kojim sam upravlja?
{19667}{19719}Krivo. Ima pilota.
{19721}{19844}Kad smo kod muškaraca, moramo | pronaæi jednoga za šeficu za party.
{19846}{19915}Tako nas neæe pratiti u stopu.
{19917}{20020}Sretno. Muškarci njezina kalibra | ne daju oglase u novine.
{20022}{20084}- Daj joj se prestani diviti. | - Što je?
{20086}{20211}Profinjena je, otmjena, svagdje je | pozivaju i uvijek ima što odjenuti.
{20213}{20284}Baš. Ti nemaš ništa.
{20299}{20359}- Stižem. | - Ja æu.
{20361}{20415}- Pronaði nešto. | - Jesam.
{20466}{20560}- Tko je to? | - Smiri se. Sliniš mi po vratima.
{20562}{20629}To mi je susjed.
{20631}{20688}- Antonio. | - Bog, Ashley.
{20690}{20785}Dostavili su ti odjeæu iz èistionice, | pa sam je ja preuzeo.
{20787}{20852}Pravi si anðeo. Hvala.
{20854}{20914}Trudim se. Važan spoj veèeras?
{20916}{21045}- Recimo. Ti? | - Meni je tako svaku veèer. Vidimo se.
{21047}{21116}- Hvala. | - Bog.
{21118}{21226}- Jesi li slobodan u èetvrtak? | - Nisam. Što si imala na umu?
{21228}{21339}Ovo se ne propušta. Masquerade | Records priprema veliki party.
{21341}{21449}Hrana, zabava, ples, | spoj na slijepo s mojom šeficom?
{21451}{21503}Kakva je?
{21505}{21584}Pametna, snažna | i nezavisna žena.
{21586}{21638}- Je li zgodna? | - Naravno.
{21640}{21738}Ako misliš da æemo kliknuti, | to je dovoljna preporuka.
{21740}{21818}Super si. Baš ti hvala. Bog.
{21820}{21910}- Bog. | - To. Spoj za zmajušu.
{21935}{22010}- Ovo nije moje. | - Èije je?
{22035}{22088}- Sarah Jessica Parker. | - Što?
{22090}{22167}- Ne šalim se. | - Nisam znala da ovdje živi.
{22169}{22299}- Pogledaj. Dolce. | - Bože. Mogu je sutra vratiti.
{22313}{22409}Da vidim. | Tvoja velièina. Kakva sreæa.
{22411}{22469}Ne budi zavidna.
{22471}{22558}- Mogla bi mi dobro stajati. | - Moraš je veèeras odjenuti.
{22560}{22668}- Treba mi èokolade. | - Idem je isprobati.
{22853}{22893}Hvala.
{22919}{22963}Seronjo.
{22984}{23066}- Pazi, budalo! | - Oprostite.
{23142}{23221}Je'n, dva. Proba.
{23551}{23606}- Bog, Jake. | - Bog, Mac.
{24155}{24221}Jake, kako je prošlo?
{24248}{24311}Predao si Phillipsu CD?
{24352}{24473}Nisam. Nismo uspjeli | uskladiti rasporede.
{24475}{24593}- Jake, ovo traje veæ tjednima. | - Sve ide kako treba. Vjerujte mi.
{24595}{24694}Ovdje bi se trebala pojaviti | dva skauta za glazbene tvrtke.
{24696}{24762}U muškom zahodu je zaèepljen odvod.
{24764}{24898}Rado æu to riješiti, Mac, | ali smjena mi poèinje za dva sata.
{24900}{24966}Zamisli da je ovo Grammy.
{24968}{25026}Grammy. U redu.
{25076}{25173}Idem ovo riješiti. | Samo živahno. Pazi na G, Tome.
{25175}{25244}Veèeras æe biti super.
{25748}{25803}- Izvoli. | - Hvala.
{25830}{25889}Mislila sam da idemo zrakoplovom.
{25891}{26029}- Ovo je prijevoz do njega. | - Ovo ide u moj dnevnik.
{26031}{26154}Dobra veèer, Bayonne. Ashley, | otkud ti ta prekrasna haljina?
{26156}{26206}Ne pitaj.
{26910}{26985}Kako ste? | Deèki, nastupate.
{26987}{27066}Gospodo, uživajte. Mi èastimo.
{27281}{27443}Dame i gospodo, pozdravite najbolji | rock bend u New Yorku, McFly.
{28011}{28085}Nastavite. Sad æu ja.
{28458}{28549}- Otpuštate me? Ne plaæate mi. | - Slušaj, dobar si.
{28551}{28608}Otkrio si nas, samo...
{28610}{28701}- Da èujem ali. | - Vrijeme je da se vratimo kuæi.
{28703}{28793}- Ne možete. Nadomak smo cilja. | - Ovdje nismo imali sreæe.
{28795}{28904}A jadnom Dougu nedostaje mama. | Zbilja. Plaèe svaku noæ.
{28915}{28978}Još tjedan dana. Što kažete?
{28980}{29092}Dajte mi još tjedan dana i ako | vam ništa ne sredim, shvatit æu.
{29094}{29199}Gotovo je. Vratite se kuæi. | Samo jedan tjedan.
{29201}{29251}U redu. Tjedan dana.
{29253}{29344}Tjedan dana. | Odmorite se, deèki.
{29346}{29435}Mama æe morati prièekati | još tjedan dana, Doug.
{29462}{29500}Tjedan dana.
{29547}{29672}- Jesi li? | - David je pristojan. Poljubili smo se.
{29674}{29737}- Dosadno. | - Raèun, Zuki.
{29739}{29795}Je li bio obièan poljubac?
{29797}{29909}Ili poljubac koji izaziva trnce | u leðima i leptiriæe u trbuhu?
{29911}{30011}Dovoljan da me pozove | na drugi sastanak.
{30053}{30121}- Hvala. | - Ne.
{30123}{30218}Èekaj, što kažeš? | G. Platinasti kaže da on plaæa.
{30220}{30279}- Ne mogu vjerovati. | - Što je?
{30281}{30385}Peggy Braden ti je dala | platinastu kreditnu karticu?
{30387}{30460}Jedno je pozitivna energija, | a drugo obièna sreæa.
{30462}{30593}Maggie, poznaješ me od sedmog razreda. | Reci joj da to nije sreæa.
{30595}{30680}Bila si kraljica maturalne veèere | u srednjoj školi Franklin.
{30682}{30777}- Pa? | - Mi smo išle u Jefferson.
{30779}{30858}- To ništa ne znaèi. | - Što? Šališ se?
{30860}{30939}- Hvala, Ashley. | - Hvala, Ashley.
{30941}{31048}Kad su prodavali sreæu, | tebi su uvalili ekstra paket.
{31050}{31110}- Blesave ste. | - Hvala.
{31112}{31151}Hvala.
{31153}{31306}Ako vjeruješ da to nije sreæa, | pristat æeš na maleni test.
{31308}{31390}- Test? | - Super. Kakav test?
{31473}{31567}- Oprostite. Instant sreæku. | - Kakvu?
{31569}{31667}- Odaberi. | - Nije pošteno. Ovo mi ide.
{31669}{31743}- Onu. | - Lutrija nikomu ne ide.
{31745}{31826}- Dolar. | - Hvala.
{31828}{31892}- Cure. | - Hajde.
{31894}{31960}- Ovo je glupo. | - Hajde.
{31985}{32059}Ne gledajte. Moja sreæka.
{32094}{32137}Što si dobila?
{32139}{32207}5, 10, 15. Rekla sam da mi ovo ide.
{32209}{32303}- Ti si najveæa sretnica na svijetu. | - Kako ti to uspijeva, Ash?
{32305}{32364}Rekla sam vam. Samo zagrebete.
{32366}{32454}Što? Mogla bih te ubiti.
{32456}{32547}Ne smijem se ozlijediti. | Moram organizirati party.
{32549}{32645}Imamo prezentaciju s Peggy | za deset minuta.
{32647}{32724}Taksi. Trebamo ploèe za prezentaciju. | Neæemo stiæi.
{32726}{32798}- Sve vidiš crno. | - Istina je.
{32800}{32849}- Bog. | - Nemojte me razoèarati.
{32851}{32906}Naravno. Volimo te.
{32998}{33043}- Kako si? | - Živèano.
{33045}{33108}Svidjet æe joj se.
{33110}{33203}- Ovo je nevjerojatno. | - Brzo, spremna je.
{33214}{33256}Zdravo, gðice Braden.
{33258}{33311}Pardon. Peggy.
{33313}{33412}- Spremni za oduševljenje? | - Spremna sam za pitanja.
{33414}{33473}Svakako. Tomu se i nadam.
{33500}{33589}Zamislile smo karnevalski ugoðaj.
{33591}{33713}Pozvat æemo elitno društvo važnih osoba, | slavnih osoba i ljudi iz glazbe.
{33715}{33769}Samo što æe svi nositi maske.
{33771}{33816}Zanimljivo.
{33818}{33955}Imat æemo DJ-a, cirkusante, gatare, | dim za ugoðaj i neonsku rasvjetu.
{33957}{34019}Ondje æe biti VIP dio.
{34021}{34083}Imat æemo šampanjac. Samo najbolje.
{34085}{34176}Dom Perignon nose | konobari na štulama.
{34178}{34326}Pozornica s najnovijim spotovima | Masqueradea i profesionalnim plesaèima.
{34328}{34458}S one strane separei | u koje se ljudi mogu povuæi.
{34460}{34515}Iznad njih plesaèi u zraku.
{34540}{34645}Želim da ljudi osjete | kako je ovdje sve moguæe.
{34871}{34936}Bit æe to èarobna noæ.
{35313}{35385}- Plaæeni plesaèi? | - Rade svoj posao.
{35387}{35496}- Phillips? | - Sretan i samo što nije. Sreðeno je.
{35498}{35556}Neka bude tako, dušo.
{35666}{35703}Hvala Bogu.
{35705}{35780}Baš ti hvala. Velika sam ti dužnica.
{35782}{35921}- Koja je ona? | - Plavuša pored gatare.
{35923}{36011}- Zgodno. | - Malo je napeta.
{36026}{36109}Nema problema. To æe te više stajati.
{36111}{36169}Grozan si, ali drag.
{36171}{36256}- Kreni. Imam posla. | - I ja.
{36364}{36416}- Imam jednog žicara na ulazu. | - Što?
{36418}{36497}Mogu uæi samo oni s popisa. | Nema iznimaka.
{36525}{36656}Ja sam na popisu kao plus jedan. | Pazi na jaknu, to je samt.
{36658}{36728}- Moja noga. | - Oprostite. Bacili su me.
{36730}{36785}Koji seronja.
{36896}{36939}CATERING CRNI MAÈAK
{37076}{37174}- Je li ovo party Masqueradea? | - Ti si Ronald?
{37176}{37293}- Jesam. | - Kasniš. Plesaèi idu u sobu pet.
{37295}{37371}- U redu. | - Hajde.
{37373}{37427}Nadam se da je odjeæa dobra.
{37555}{37634}I mislila sam. Ljubavnici.
{37636}{37702}Vidiš? Rekao sam ti, dušo.
{37768}{37898}- Èini se da ste kliknuli. | - Jesmo. Hvala na spajanju.
{37900}{37975}- Ti si nas spojila? | - Kriva sam.
{37977}{38116}- Hvala. Sladak je. | - Stvoreni ste jedno za drugo.
{38118}{38197}- To je i Madame Z rekla. | - Je li?
{38199}{38262}Ljubavnici.
{38264}{38338}Idemo plesati, dušo.
{38370}{38504}- Samo tako, Z. | - Tebe ne zanima što piše u kartama?
{38506}{38595}- Neka. Èuvajte to za goste. | - Skeptik.
{38609}{38690}Koliko sam puta èula | "Upoznat æete zgodnog neznanca"?
{38692}{38821}- Tako je svaki dan. | - Misliš da je dobra sreæa normalna?
{38823}{38881}Tako sam i mislila.
{38883}{38987}Osvojit æu krstarenje? | Imam takav osjeæaj.
{38989}{39129}Baš i ne. Kaže da te | uvijek prati dobra sreæa.
{39147}{39279}Pazi se. Ova karta, | kolo sreæe, okrenuta je.
{39296}{39356}Možda se tvoja sreæa okreæe.
{39358}{39439}Nemam vremena za kolo sreæe.
{39441}{39525}Imam 500 gostiju | i pokvareni top za mjehuriæe.
{39527}{39632}- Idi. | - Samo tako nastavite. Ljudi uživaju.
{39696}{39752}Ti bokca.
{39984}{40054}Nisu li sjajni?
{40056}{40122}Poslušajte ovo.
{40124}{40213}- Poslušajte ovo. | - Poslušajte ovo.
{40215}{40288}Dobro se zabavljate?
{40290}{40349}Sviða vam se glazba?
{40351}{40438}Sviða li vam se glazba?
{40463}{40513}Nema do dobre zabave.
{40515}{40662}Hvala što ste došli i podržali | prihvatilište u 2. ulici.
{40714}{40758}Do ovog trenutka,
{40760}{40880}skupili smo 270.000 dolara.
{40882}{40942}Molim pljesak za sve vas.
{40964}{41054}Lako je puno novca, to nije dovoljno.
{41056}{41184}Obeæavam vam, | ako mi pokažete još novca,
{41186}{41253}ludo æete se zabaviti. Hajde.
{41296}{41344}Hajde. Idemo.
{41484}{41534}Baš sam dobar.
{41678}{41810}- Gdje je pjenušac? Party. | - G. Phillips. Oprostite.
{42176}{42239}Vidimo se u crkvi.
{42241}{42291}Što ima, èovjeèe?
{42516}{42592}Plesaèi moraju biti na podiju. Tamo.
{42594}{42654}Naravno. Samo...
{42851}{42980}Htio bih zamoliti | ovu mladu damu za ples.
{43013}{43109}- Ulizuješ se šefici? | - Molim?
{43111}{43210}- Pleši s njim. | - Zaslužila si. Zabava je super.
{43212}{43314}- Sladak je. | - I hoæu. Zaslužila sam malo zabave.
{43316}{43353}Bog.
{43355}{43457}Dana, smijem li plesati? | Pleše mi se. Molim te.
{43459}{43525}U redu. Zabavljaj se.
{43583}{43643}Pazi, seronjo.
{45341}{45461}- Oprosti. | - Nema problema. Ja...
{45463}{45551}Ne èujem te. | Preglasno je. Izaæi æu.
{45553}{45633}...moram iæi. | - Što?
{45650}{45810}Moram nešto obaviti, | ali odmah se vraæam. Prièekaj me.
{45918}{46003}Ashley, tko je to bio?
{46005}{46054}Zbilja ne znam.
{46056}{46166}- Poljubila si nekog neznanca? | - Da.
{46227}{46295}- Što je? | - Moja cipela.
{46374}{46435}Bože.
{46437}{46534}- Moja haljina. | - Bar imaš donje rublje.
{46614}{46713}To ti pokušavam reæi. | Ovo je najveæi party.
{46715}{46786}- Ne. | - G. Phillips, oprostite.
{46788}{46864}Ovo je najveæi party. Tako je.
{46996}{47150}Nisam mogao stati. Izgurao me. | Zovite Hitnu. Jeste li dobro?
{47173}{47226}Dobro sam.
{47228}{47285}Pozovite Hitnu.
{47287}{47367}Zbilja sam u redu. Nisam povrijeðen.
{47369}{47448}Nisam vidio veæeg sretnika.
{47486}{47539}G. Phillips, jeste li dobro?
{47541}{47603}Više nego dobro. Živ sam.
{47605}{47669}- Spasio si me, Spidermane. | - Nije to ništa.
{47671}{47735}Nije ništa. | Kako ti se mogu odužiti?
{47737}{47887}- Samo mi je drago da ste dobro. | - Nekako ti se moram odužiti.
{47889}{48045}Ne želim sada navaljivati, ali ovo je | bend kakvog tražite. Najbolji su.
{48047}{48107}- Dogovoreno. | - Kad biste... Što ste rekli?
{48109}{48188}- Dogovoreno. Dovedi McFly, je li tako? | - Da.
{48190}{48288}Dovedi ih u moj ured | i poslušat æemo ih.
{48290}{48342}- Dobro. | - Mali, kako se zoveš?
{48344}{48386}Jake Hardin.
{48413}{48475}Damon Phillips ti je veliki dužnik.
{48477}{48574}Još sam na liniji. | Mali mi je spasio život.
{48621}{48720}Je li moguæe da mi se posreæilo?
{48722}{48823}Guši se. Diši, Ashley. Povrati.
{48825}{48874}Maknite se.
{48876}{48924}Pusti meni.
{49107}{49179}- Što je to bilo? | - Maslina.
{49181}{49235}Ash. Pogledaj.
{49237}{49301}- Stavite joj lisice. | - Nisam ja.
{49303}{49400}- Uhitili su je? | - Ona je.
{49402}{49452}Pokazuje na mene?
{49454}{49519}Drž'mo je.
{49521}{49564}Oprostite.
{49566}{49623}Dolaze.
{49625}{49716}Maknite se.
{49718}{49790}- Ashley Albright. | - Nažalost, da.
{49792}{49844}Uhiæeni ste.
{49856}{49923}Je li zbog haljine Sarah Jessice?
{49925}{49996}Èekajte. Vratit æu je.
{50118}{50205}Poštujem zakon. Volim zakone.
{50207}{50277}Ovo je sjajna noæ. | Umalo me udario auto.
{50279}{50374}- Pomaknite se, gospodine. | - Što se zbiva?
{50376}{50458}Seks i grad. Sarah Jessica Parker | ima previše haljina.
{50460}{50530}To je prošlogodišnji model. | Neæe joj nedostajati.
{50545}{50647}- Ti si prostitutka? | - Eskort. Mislio sam da znaš.
{50649}{50733}- Još nisam bila ovako ponižena. | - Peggy, ja...
{50735}{50885}Zahvaljujuæi tvojim separeima i "Želim | da osjete kako je ovdje sve moguæe."
{51064}{51135}- Zašto se cerekaš? | - Znam što se zbiva.
{51137}{51207}- Što? | - Što misliš gdje je?
{51209}{51275}- Tko? | - Domaæin.
{51277}{51359}- Kakav domaæin? | - Ovog reality showa.
{51361}{51461}Dobro je, shvatila sam. | Možete izaæi i reæi što sam osvojila.
{51463}{51519}- Zar si poludjela? | - Tišina.
{51521}{51621}Slobodno mi recite - | je li vas David Pennington nagovorio?
{51623}{51684}To je moje mjesto.
{51686}{51757}Mislila sam da nisu numerirana.
{51759}{51812}Ovo je stvarno, Ashley.
{51814}{51943}Izgubila sam najveæeg klijenta | i tko zna što æe napisati u Postu.
{51945}{51994}- Braden. | - Ja sam.
{51996}{52083}- Plaæena je jamèevina. | - Hvala.
{52085}{52154}Peggy, žao mi je.
{52156}{52236}Ako nisi shvatila, otpuštena si.
{52429}{52511}- Je li i pod tvoj? | - Što si rekla?
{52986}{53057}Dosta je.
{53059}{53131}- Deèki. | - Je li auto spreman, Tiff?
{53133}{53186}Samo su...
{53242}{53312}...malo živèani. | - Idi s njim.
{53448}{53523}- Oprostite ako to nije... | - Što ti se sviða kod njih, Jake?
{53525}{53616}Svježi retro zvuk, | mješavina Beatlesa i Blink-182.
{53618}{53687}Iznenaðen sam. A prodaja i procjene?
{53689}{53804}Dobro da ste to spomenuli. | Tako dobar bend æe se prodavati.
{53806}{53873}Idealist i neiskvaren. Sviða mi se.
{53875}{53982}I ja sam nekad bio takav, | ali sam se odluèio obogatiti.
{53984}{54055}Hvala na prilici.
{54057}{54193}Slušaj, mali. Vjerujem u sreæu, pa æu | ovo poslati na radio postaje da vidimo.
{54195}{54298}Do tada radite na drugim stvarima. | Imate dva tjedna.
{54300}{54366}Potpisat æete ugovor?
{54368}{54469}Proveo sam osam minuta s tobom. | Zašto bih inaèe gubio vrijeme?
{54471}{54572}Nazovi raèunovodstvo, daj im predujam | i smjesti ih u najbolji apartman.
{54574}{54664}Ovo je veæ deveta minuta. Idemo.
{54666}{54717}Doviðenja.
{54734}{54784}Hvala.
{54873}{54923}Èestitam.
{54969}{55009}Hvala.
{55395}{55435}Bože.
{55759}{55810}Dom.
{55812}{55862}Dobro jutro.
{55980}{56042}Idem ravno u kadu.
{56115}{56154}Nije li to moj...
{56156}{56310}Pregledali smo sve. | Sve moramo izbaciti.
{56312}{56381}- Zaboga. | - To je vaš stan?
{56383}{56437}Da. Što se zbilo?
{56439}{56494}- Poplava. | - Poplava?
{56515}{56604}To je tehnièki izraz | za puno vode na krivom mjestu.
{56606}{56662}Nije strašno. Sve æemo riješiti.
{56664}{56742}Hvala. | Smijem li se sada presvuæi?
{56744}{56895}- Deèki, ona bi se presvlaèila. | - Što je smiješno?
{56897}{57018}Dušo, imaš plijesan èetvrtog stupnja. | Imaš sreæe što smo je otkrili.
{57020}{57070}Baš sam sretna.
{57214}{57300}- A moje pokuæstvo? | - Ništa se ne brini.
{57326}{57402}Spalit æemo ga prije | nego se proširi na druge stanove.
{57404}{57469}Uspjeli smo spasiti ovo.
{57530}{57593}- To je sve? | - To je sve.
{58100}{58148}Hej, ti.
{58150}{58200}Jesi li dobro?
{58289}{58404}- Ovo mi je novi stan? | - Znam. Nevjerojatan je.
{58418}{58483}Kuæno kino, satelitska TV.
{58485}{58557}Po noæi, kada se priguše svjetla,
{58559}{58657}mogli bismo reæi da ti oduzima dah.
{58676}{58750}Tako je... | I po danu.
{58752}{58847}Bend je dolje niz hodnik, | a šank i hladnjak su puni.
{58849}{58952}Tek da znaš, | lijepo je raditi za DMR.
{58954}{59090}U nekim tvrtkama zaposlenicima brane | veze unutar tvrtke. Ovdje nije tako.
{59132}{59230}- Veza? | - Može. Slobodna sam èitav vikend.
{59232}{59339}Ne smeta ti ako cura èasti? | Nekim èudacima to još smeta.
{59341}{59421}Moram iæi. | Kasnim na sat erotske masaže.
{59423}{59510}Vidimo se, Spidermane.
{59566}{59622}Erotska masaža.
{59709}{59785}Cure, hvala što ste me primile.
{59787}{59897}Ne samo da nemam love, veæ me zmajuša | ocrnila u svim tvrtkama u gradu.
{59899}{60030}- A da nazoveš roditelje? | - I priznam poraz? Neæu.
{60032}{60085}Gdje æu spavati?
{60087}{60153}- U svojoj sobi. | - Mojoj sobi?
{60155}{60240}Maggie ima sobu iznad kuhinje.
{60242}{60304}Dana je na trosjedu na razvlaèenje.
{60306}{60445}Možeš birati izmeðu La-Z-Boya, | mekan i èvrst,
{60447}{60548}i, meni omiljene, | nevjerojatne prostirke.
{60550}{60672}Savršeno. Neæu vam smetati | i zaboravit æete da sam ovdje.
{60674}{60734}- Sušilo za kosu? | - Na radijatoru.
{60736}{60786}Hvala.
{60828}{60888}Maèka ti je sasvim crna?
{60890}{60963}- Da. Zašto? | - Znatiželjna sam.
{61005}{61070}Super. Bit æe nam zabavno.
{61072}{61171}Sve æe biti... Bože.
{61173}{61239}- Što je? | - Imam prištiæ.
{61241}{61316}Cure, imam prištiæ.
{61427}{61540}- Ash, jesi li dobro? | - O, Bože.
{61791}{61866}- Tko je to napravio? | - Svaka èast.
{61868}{61921}Jesi li dobro, Ash?
{61923}{61975}Stižem.
{61977}{62046}- Dušo? | - Razbila sam zrcalo.
{62048}{62111}Znam.
{62113}{62218}Cure, što mi se to zbiva? | Ne mogu ovako još sedam godina.
{62220}{62345}Od partyja sam anti-Mida. | Sve što dotaknem pretvara se u govno.
{62347}{62405}Samo se smiri.
{62407}{62502}Iz nekog razloga, | sudbina ti je okrenula leða.
{62504}{62591}Ali kolo sreæe se okreæe, zar ne?
{62785}{62810}Otpuštena si.
{62876}{62942}O, Bože. Treba mi nekakva odjeæa.
{62950}{62995}ZAFFINA | ZATVORENO
{63293}{63361}Ima li koga? Otvorite.
{63363}{63416}Ima li koga?
{63418}{63489}- Da? | - Uništili ste mi život.
{63491}{63589}- Što? Ti si. | - U životu mi je sve savršeno išlo.
{63591}{63682}Èekaj malo. Je li bilo savršeno?
{63684}{63761}Neæete me psihoanalizirati.
{63763}{63863}Bacite svoje èini | i vratite mi moju sreæu.
{63865}{63951}Dobro. Usredotoèi se.
{64022}{64148}Sve je u redu. Vratila se. Idi kuæi. | Moram sutra rano ustati.
{64150}{64297}Ne muljajte. Vi i vaše karte ste | mi sve zeznuli. Morate to popraviti.
{64299}{64356}Pokušala sam te upozoriti, dušo.
{64358}{64460}Je li se zbilo | nešto neobièno na zabavi?
{64484}{64630}Osim poderane haljine, gušenja | i kaznene prijave, nije.
{64678}{64800}- A prije toga? | - Samo sam poljubila zgodnog tipa.
{64874}{64979}Trenutak. Rekli ste da mi je | netko može preuzeti, zar ne?
{64981}{65052}Preuzeo je moju sreæu?
{65054}{65120}Možda je njemu više trebala.
{65122}{65210}Ukrao ju je? | Mala lopovska ljubilica.
{65230}{65351}To je moja sreæa. | Recite mi kako da je povratim.
{65353}{65413}Ja?
{65415}{65477}Da vidimo.
{65479}{65564}Ako ti ju je ukrao poljupcem,
{65605}{65668}bilo bi logièno...
{65694}{65745}Što?
{65826}{65883}Dvadeset profesionalnih plesaèa?
{65885}{65961}Usne jednog od njih | kljuè su za povratak mojeg života.
{65963}{66033}- Ne mogu vjerovati. | - Maknite se s nogostupa.
{66035}{66092}- Polako. | - Zar sam postala meta?
{66094}{66175}Ovo je smiješno. | Poljubac ti neæe vratiti sreæu.
{66177}{66274}- Pogledaj kako su dobri. | - Sad je i potièeš.
{66276}{66333}Ne, ja æu promatrati i cerekati se.
{66335}{66409}Samo pokušavam vratiti svoj život.
{66411}{66490}Kako æeš ga prepoznati? | Ne znaš kako izgleda.
{66492}{66555}Imam nepogrješiv test.
{66591}{66641}To je on.
{66871}{66940}Bože. Baš je on.
{66957}{67053}Zaboga. Ashley, oženjen je.
{67333}{67397}- A to ti je sestra? | - Ne, ljubavi.
{67399}{67496}- Rajèica. Oprostite. | - To ti nije sestra.
{67498}{67557}Uništio si mi vjenèanje.
{67559}{67609}Uzmi nas.
{67768}{67820}Pazi ovo.
{67993}{68062}I gurate.
{68064}{68131}Oprostite. Neæemo dugo.
{68526}{68576}Oprosti.
{68718}{68793}- Svejedno hvala. | - Nema veze.
{68899}{68935}Što je?
{69012}{69077}Najljepše ti hvala. Ozdravi.
{69222}{69272}Zašto?
{69720}{69771}Bog, ja sam Dave.
{69942}{70035}Èuješ li me? Bog. Kako si?
{70037}{70089}Evo ga.
{70378}{70435}Ugrizao me za jezik.
{70617}{70667}Daj, molim te.
{70707}{70841}- Još nam je jedan ostao. Tom Guthrie. | - Pljuni led, Ash.
{70843}{70934}Tom Guthrie. Tražili smo ga | veæ na tri adrese.
{70936}{71044}Imaš pravo. Ja sam zec | kojem su odrezali sretnu šapu.
{71046}{71130}- Trebala bih odustati. | - Daj, Ash, nije tako strašno.
{71132}{71245}Što ako si ljubila desetak neznanaca. | Još imaš prijateljice.
{71247}{71285}Hvala.
{71287}{71370}Ali nemoj me više dodirivati.
{71372}{71441}- Ali još te volim. | - Voliš me?
{71443}{71509}Sad si stradala. Poljubit æu te.
{71645}{71708}Palaèinko. Bog, maco.
{71710}{71811}Ash, David je. Veliko otvorenje | izložbe u galeriji Station A.
{71813}{71879}Naðemo se u 19 h? | Nemoj mi slomiti srce.
{71881}{71967}- David Pennington. Novi spoj. | - Ne idem.
{71969}{72085}- Zašto? Imaš priliku sa sjajnim tipom. | - Ne, priliku da me pogodi autobus.
{72087}{72203}Maggie, tvoja mi crna maèka | ide preko puta. Nije dobro.
{72205}{72315}Doði, Palaèinko. | Ne boj se praznovjerne zlice.
{72317}{72402}Nisam praznovjerna, ali istina je. | To donosi nesreæu.
{72404}{72508}- Dana, kakav mi je horoskop? | - Lav.
{72535}{72586}Mjesec ti je u Uranu.
{72622}{72692}- Ne zvuèi dobro. | - Mogao je otkazati.
{72694}{72799}Nije li ti to dovoljan dokaz | da je loša sreæa glupost?
{72801}{72859}Ne bih rekla.
{72884}{73011}Nesretnice ne pozivaju van | najpoželjnije neženje.
{73013}{73094}Nesretnice gledaju | svoje sretne prijateljice kako idu van,
{73096}{73196}dok one gledaju Oprah | i jedu prastare slatkiše.
{73198}{73248}- Istina. | - Imaš pravo.
{73250}{73331}Naravno da imam. Odjeni se.
{73353}{73511}Možda nisam ukleta. Možda su | ove nesreæe samo nove prilike.
{73513}{73618}- Kad Bog zatvori jedna vrata... | - Otvori ti dvoja na drugoj strani.
{73641}{73724}Okreæem novu stranicu | i sreæa ponovo poèinje.
{73726}{73776}Dobro.
{73867}{73919}U redu je.
{74180}{74289}- Vratila si je u oko? | - To mi je bila posljednja.
{74291}{74353}- Odvratno. | - Moje oko.
{74401}{74472}OBRAZ ZEMLJE
{74486}{74623}Vidite, na popisu sam. Pratilja. | David Pennington i pratilja.
{74669}{74739}- Bog, Davide. | - Evo ga. Vidite?
{74797}{74901}- David Pennington. Eno ga. | - Ne. Sa mnom je.
{74903}{74944}Hvala.
{75022}{75090}Sve u redu. Dobro sam.
{75113}{75187}Doði. Imam iznenaðenje za tebe.
{75251}{75299}O, Bože.
{75301}{75428}- Pogledaj tu veliku, ružnu hrpu... | - Ashley.
{75430}{75536}Kao da je izašlo iz guzice slona.
{75588}{75666}Ovo je moja majka. Autorica.
{75682}{75765}Autorica? Zdravo, gðo Pennington.
{75767}{75851}Izgledate puno mlaðe uživo.
{75868}{76004}- Ne želim reæi da ste stari. | - Za ovo æe mi trebati votka.
{76006}{76085}Dobra zamisao. Konobar.
{76250}{76311}Ne, hvala.
{76313}{76422}Davide, tu je onaj iz Timesa.
{76424}{76506}- To je on. Taj kujin... | - Oprostite.
{76508}{76628}- Da? Taj konobar je... | - Više tvoj tip. Slažem se.
{76630}{76676}Majko. Molim te.
{76678}{76799}Morala bih do zahoda.
{76872}{76946}- Ti. Napokon. | - Molim?
{76948}{77041}Jezik za zube jer ovo je samo posao.
{77043}{77116}- Što? | - Vrati mi moju sreæu.
{77194}{77318}Iz dubine smrtnih crijeva | dolazi Èovjek od blata.
{77320}{77375}- Poljubi me. | - Nastupam.
{77377}{77461}- Ja sam Èovjek od blata. | - Ja sam Žena od blata.
{77463}{77518}Mi smo Ljudi od blata.
{77520}{77602}A ovo je naš Kralj od blata.
{77681}{77759}- Srèani udar. Oživljavam ga. | - Nemam...
{77761}{77853}- Ne diše. | - Vidiš da diše.
{77855}{78010}Ne diše. To je srèani refleks. | Moram mu dati usta na usta.
{78201}{78270}Dobro je.
{78515}{78592}- Sreæom, bila si ovdje. | - Sreæom, znaš prvu pomoæ.
{78594}{78665}Takva sam ja. Sretna.
{78667}{78730}Osjeæam se nekako...
{78855}{78900}Nezamjenjivo.
{79024}{79093}Ovo je smiješno. To je samo blato.
{79281}{79430}Upoznala si moju blizanku. Bila je | ovdje neku veèer. Ja sam dobra.
{80179}{80282}- Što želite? | - Može samo èaša vode?
{80284}{80387}Ako ne plaæaš, ne sjediš. Vidiš?
{80389}{80418}AKO NE PLAÆAŠ, NE SJEDIŠ
{80420}{80489}Mogu li barem na zahod?
{80491}{80566}Ne plaæaš, nema zahoda.
{80568}{80660}Super. Dobro. Idem.
{80662}{80775}Uživate u predstavi? | Ja inaèe nemam ovakvih dana.
{80777}{80836}Možda èak nisam ovdje.
{80838}{80983}Sve je ovo vjerojatno san | potaknut dubinskom masažom.
{80985}{81059}Koju sam osvojila na nekoj lutriji.
{81061}{81135}Ovo sjajno izgleda. | Neæete više jesti?
{81137}{81229}Šalila sam se. | Neæu jesti vaše ostatke. Bože.
{81231}{81294}Možda samo slaninu.
{81390}{81458}Što to radi?
{81526}{81608}O, Bože. Kao kojot.
{81717}{81792}- Savršeno. | - Samo ne sol.
{81825}{81972}Tek da se zna, uèinit æu nešto | besmisleno, ali ne može škoditi.
{81974}{82029}Idemo.
{82031}{82084}Moje oèi.
{82119}{82230}- Nisam namjerno. Oprostite. | - Gðice, vrijeme je za polazak.
{82232}{82307}Oprostite. Nisam namjerno.
{82362}{82455}- Mislim da smo na sigurnom. | - Hvala ti. Oprosti.
{82457}{82535}- Sluèajno sam èuo... | - Moj slom živaca?
{82537}{82618}Švorc, bez posla | i upravo sam napala jambon ïétranger.
{82620}{82661}- Što? | - Neznanèevu slaninu.
{82663}{82751}Mislila sam da bolje zvuèi | na francuskom, ali ne.
{82753}{82854}Djeluješ gladno. | Možda ovo pomogne. Puretina.
{82856}{82942}Da. Hvala.
{82954}{83023}Bilo mi je drago.
{83201}{83293}Ako tražiš posao, mogu ti pomoæi.
{83295}{83356}- Zbilja? U èemu je kvaka? | - Nema kvake.
{83358}{83421}Da pristupim tvojoj vjeri?
{83423}{83475}Nema veze s religijom.
{83477}{83555}Nije baš neki posao. | Loša plaæa, puno posla.
{83557}{83635}Nisi odgovorio na pitanje. | U èemu je kvaka?
{83637}{83708}Recimo da znam kako je kad TNS.
{83710}{83780}- TNS? | - Totalno nemaš sreæe.
{83782}{83917}Zašto misliš da TNS? | Zato što sam bacila sol preko ramena?
{84001}{84106}Èuj, znam kako ti je. | Prošao sam to. Živio sam tako.
{84108}{84177}Bio sam prvak u tim stvarima.
{84221}{84289}- Zovem se Jake. | - Ashley.
{84314}{84356}- Bože. | - Uspjela si.
{84358}{84405}- Zaboga. | - Sjajno ti stoji.
{84407}{84524}Što mi se još... Iskreno, | nisam odjevena za razgovor za posao.
{84526}{84582}Za ovaj to neæe biti problem.
{84609}{84687}- Još te zanima? | - Zašto si tako dobar?
{84689}{84772}Totalno nemati sreæe je moja stvar.
{84780}{84863}- Nemoj mi to raditi. | - Svidjet æe ti se.
{84865}{85013}- Ne trebam nespretnu konobaricu. | - Neæeš požaliti, Mac.
{85033}{85122}- Nisam ga dobila. | - Nije to.
{85124}{85245}- Jesi, ali moj stari posao. | - Pa?
{85247}{85319}Nadao sam se da æe te primiti | kao konobaricu.
{85321}{85480}Ja sam bio domar, dostavljaè hrane | i na održavanju zahoda.
{85482}{85540}Uzimam.
{86327}{86368}Upomoæ!
{88478}{88567}Idemo, deèki. Crta, perem sve.
{88816}{88855}Tako je.
{89023}{89132}Prije izdavanja albuma, Phillips | želi da svirate u tvornici pletiva.
{89134}{89229}Pokušajte zadržati gledaoce | sat vremena, kao predgrupa.
{89231}{89359}- Ljudi, naša prva gaža. | - Slušajte. Carley, pojaèaj radio.
{89370}{89443}- Nemoguæe. | - To smo mi.
{89481}{89573}- Idemo proslaviti. Èastim klopom. | - Super.
{89584}{89680}Dušo, popni se na ljestve | i zamijeni cijev.
{89682}{89755}- Nisam baš dobra s... | - Hvala.
{89757}{89853}...visinama. | - McFly, nova invazija iz Engleske...
{89855}{90015}Phillips æe nam reæi veèeras. | Do tada moramo uskladiti...
{90085}{90165}Pjesme. To nije dobro.
{90167}{90323}Trebala se popeti bez cijevi, prvo | spustiti pokvarenu. Sad æe biti svega.
{90366}{90428}Znaš gdje je metla.
{90526}{90651}Trebala je ugasiti svjetlo | jer æe je sada...
{90653}{90714}stresti struja.
{90770}{90820}O, Bože. Bog.
{90847}{90933}Osim strujnog udara, | kako ide posao?
{90935}{90978}- Ne mogu se žaliti. | - Dobro.
{90980}{91085}Ne, ne smijem se žaliti. | Potpisala sam ugovor.
{91087}{91204}- Znam. Ovo je hladno, pomoæi æe. | - Snalaziš se u ovomu.
{91206}{91244}Hvala.
{91246}{91319}Ovo je dobro.
{91352}{91479}- Pasta za zube? | - Kineski lijek za spaljene prste.
{91525}{91664}Samo sam spreman. Sve imam u ruksaku. | Prvu pomoæ, druge èarape.
{91666}{91777}- Pomalo fatalistièki? | - Samo sam realan. Znaš na što mislim.
{91779}{91855}- Daj mi svoj mobitel. | - Zašto?
{91857}{91906}Što je ovo?
{91908}{91966}Okreni ovaj dio.
{91992}{92044}Adresar.
{92046}{92124}"Bergdorf's, Bendel's i suši"? | Jesi li normalna?
{92126}{92193}Nesretnici trebaju bolnice.
{92195}{92264}Ne zovi Hitne službe. Spori su.
{92266}{92326}Vatrogasci su super.
{92328}{92439}Nacionalno središte za trovanja - | traži Loua, on je super.
{92525}{92575}Znaš što æemo?
{92604}{92674}Ovaj me ruksak proveo kroz sve.
{92676}{92794}- Vrijeme je da ga proslijedim. | - Ne mogu to primiti.
{92796}{92883}Zbilja. Trebala bi ga uzeti. | Trebaš ga više nego ja.
{92885}{92935}Hvala.
{93099}{93168}- Moram se javiti. | - Svakako.
{93170}{93240}Bog, Katy. Kako je moja cura?
{93242}{93313}Tvoj kljuè? Ispod otiraèa?
{93349}{93465}Mogu doæi po tebe i vodim te | u novi restaè. Ogroman je.
{93467}{93526}Pojest æemo pizzu, uživati.
{93528}{93580}Moram iæi.
{93607}{93655}Vidimo se, Ashley.
{93657}{93714}Jedna poznanica. Da, cura je.
{94473}{94543}- Hajde. | - Bog, deèki. Dobro zvuèite.
{94545}{94595}- Hvala. | - Što se zbiva?
{94597}{94658}- Tvornica pletiva je otpala. | - Što?
{94660}{94722}- Šališ se. | - Koma.
{94724}{94880}Na radiju ste dobro prošli, | pa sam rezervirao Hard Rock Cafe.
{94882}{94960}- Zbilja? | - Tko je faca?
{94962}{95044}To je veliko.
{95046}{95140}- Kako napreduju pjesme? | - Radimo na njima.
{95172}{95263}Tako treba. | Ne dajte se ometati. Èestitam.
{95265}{95315}Vidimo se. Uživajte.
{95317}{95400}Jake, kada æemo èuti | te sjajne pjesme?
{95402}{95457}Kada ih napišete.
{95459}{95502}Dobro.
{95504}{95558}Jake, imate dostavu.
{95617}{95696}- Ovamo. | - To je ona riba iz kuglane.
{95698}{95767}Ona što se spalila.
{95769}{95884}Uvježbajte tekst pjesme "Too Close | For Comfort". Na dobrom smo putu.
{95886}{95958}Idemo od druge strofe.
{96098}{96164}Oprosti. Hvala.
{96166}{96228}Držim ih.
{96278}{96348}- Oprosti zbog... | - Bez brige.
{96350}{96404}Uði. Poslušaj pjesmu.
{96475}{96525}Zvuèi sjajno, Time.
{96617}{96696}- Dobro zvuèe. | - Dobri su, zar ne?
{96698}{96770}- Svirat æemo u novom Hard Rocku. | - Super.
{96772}{96892}Da, samo što je prostor velik, | neæemo ga napuniti i gotovi smo.
{96894}{96969}Teško je, ali nije nemoguæe.
{97194}{97344}Jesi li možda za kavu kasnije?
{97346}{97385}Da,
{97387}{97450}mogla bih.
{97583}{97648}Evo je.
{97710}{97784}- Je li to Katy? | - Da.
{97786}{97862}Slatka je. Ona je odabrala ovu jaknu.
{97864}{97902}Zgodno.
{97955}{98027}- Izgleda kao drolja. | - Što?
{98029}{98125}Škola. Podsjeæa me na jednu iz škole.
{98127}{98176}- Neobièno. | - Èudno.
{98201}{98302}Trebala bih poæi. Mac želi | da postavim klopke za štakore.
{98304}{98393}- Da te nazovem veèeras? | - U vezi s time.
{98453}{98534}Možda drugi put. | Imam neke druge planove.
{98536}{98602}Oprosti. Bog.
{98604}{98654}Bog.
{99072}{99172}- Hvala na vožnji, Jake. | - Èekaj malo.
{99198}{99281}- Vidimo se kasnije? | - Reci da æu poslati Bernieja po tebe.
{99283}{99338}- Ne zaboravi na zadaæu. | - Dobro.
{99340}{99398}Vidimo se.
{99587}{99655}Ne otvaraj kišobran.
{99657}{99732}Ne unutra. Donosi nesreæu.
{100152}{100228}Bernie. Vrati se, može?
{100591}{100670}Imaš ponèo u ruksaku.
{100672}{100741}Nisam se ni sjetila pogledati.
{100743}{100796}Da te povezemo?
{100798}{100873}Živim samo 29 ulica odavde.
{100919}{101019}- Bar uzmi moj kišobran. | - Imam svoj.
{101021}{101098}Imam sušilicu,
{101100}{101182}kokice iz mikrovalne, satelitsku.
{101184}{101248}Ne bih smjela.
{101269}{101319}Ne nudim to svakoj,
{101321}{101464}ali ubacit æu još toplu èokoladu | sa sljezovim mrvicama.
{101516}{101595}Volim sljezove mrvice.
{101597}{101674}Baci taj gromobran i uði.
{101769}{101819}Hvala ti.
{102303}{102370}Lijep stan.
{102372}{102434}- Pronaæi æemo ti suhu odjeæu. | - Hvala ti.
{102436}{102521}Praonica je tamo, | kupaonica ondje, kuhinja ovdje.
{102523}{102630}- Sama odaberi redoslijed. | - Hvala.
{102767}{102841}- Smijem ubaciti i svoju odjeæu? | - Samo daj.
{102843}{102938}Praonica u stanu. | Zbilja si uspio.
{102940}{103010}Zgodno je.
{103012}{103107}Trebao bih i ovo oprati. Èekaj.
{103456}{103527}- Ubaci mi ovo. | - Može.
{103529}{103573}Hvala.
{103575}{103699}- Moram se javiti. Brzo æu. | - Bit æu ovdje.
{103744}{103865}Otkad perilice imaju ekrane?
{104219}{104287}Bože. Što se zbiva?
{104289}{104346}Zaboga.
{104363}{104439}Molim te, prestani.
{104461}{104506}Prestani.
{104537}{104602}Iskljuèi se.
{104647}{104734}- Što te spopalo? | - Je li sve u redu?
{104736}{104799}Sve je super.
{104893}{104946}Što se zbiva?
{104948}{105000}Zatvoriti vodu.
{105031}{105092}Bože.
{105094}{105144}Iskljuèi se.
{105146}{105205}Ne centrifuga.
{105263}{105309}- O, Bože! | - Hej?
{105419}{105485}O, Bože!
{105497}{105552}Molim te, stani.
{105570}{105643}Strašno mi je žao.
{105645}{105708}Pusti meni.
{105793}{105850}Kako si je ugasio?
{105852}{105948}Možeš je iskljuèiti na ekranu.
{105950}{106071}Što da ti kažem? | Ja sam hodajuæa nesreæa. Odustajem.
{106073}{106146}- Odustaješ? | - Odustajem. Briga me za sve.
{106148}{106210}Osjeæaj je super.
{106279}{106422}Ja sam davno odustao. | To je tajna moje sreæe.
{106424}{106498}Èekaj malo.
{106500}{106555}Pošteno igraj.
{106591}{106681}- Èovjeèe. Gotov si. | - U oko? Oprosti.
{106810}{106855}Super.
{106857}{106907}Prekidam nešto?
{106909}{106966}Bog, Katy.
{106968}{107071}- Ti si Katy? | - Tako su me nazvali.
{107096}{107147}Bog, ja sam Ashley.
{107221}{107283}To nije problem. Riješit æu.
{107285}{107345}Jake kaže da si luzerica.
{107347}{107404}Što? Nisam luzerica.
{107406}{107548}Nema veze. I ja sam luzerica. To je | izraz od milja. Nije stalno stanje.
{107550}{107640}Samo nisi imala sreæe.
{107642}{107738}- Obožavam mrvice od sljeza. | - I ja.
{107740}{107836}Dobro. Èujemo se. | U redu. Bog.
{107838}{107902}- O, Bože. | - Što je?
{107904}{107978}Phillips želi novu pjesmu | prije koncerta.
{107980}{108061}- I? | - A nemamo kurca.
{108063}{108216}Klinca. Nemamo klinca. | Ne moramo reæi teti Marthi?
{108218}{108352}- Bez brige. Napisat æu opaku pjesmu. | - Sad pišeš i pjesme? Duhovito.
{108354}{108433}- Možeš me malo podržati. | - Ovo je važna stvar.
{108435}{108514}- Bez klinca. | - Bez klinca?
{108516}{108625}- Mogu vam pomoæi. | - Što imaš na umu?
{108627}{108679}Imam jednu prijateljicu.
{109169}{109230}Kakva pjesma.
{109265}{109429}- Razumjet æu ako je neæete. | - Super je. Samo je treba prilagoditi.
{109431}{109574}Harry, ubrzaj tempo. Danny, Tome, | ubrzajte i ubacite gitaru i bubnjeve.
{110081}{110168}- Hvala. | - Nema na èemu.
{110702}{110767}Èujem da imaš još jedan hit za mene.
{110769}{110836}Treba je doraditi, ali ima nešto.
{110838}{110920}Dobro zvuèi. Pozitivno, to volim.
{110922}{110981}Èestitke na rasprodanoj gaži.
{110983}{111041}Rasprodana gaža?
{111043}{111125}- Hard Rock je rasprodan? | - Nabavio sam ti BlackBerrie.
{111127}{111198}- Nemam ga. | - Tiffany, daj mu BlackBerry.
{111200}{111298}Stvorio se red ljudi koji žele uæi.
{111300}{111450}Ne volim zagrljaje, ali dvaput | si me spasio. Na partyju i sada.
{111452}{111599}I meni je to bila super veèer. | Od tada imam ludu sreæu.
{111601}{111747}Svrati mi do ureda da dogovorimo | ovitak albuma. Imam neke zamisli.
{111749}{111843}Jakea sam poljubila na partyju.
{111845}{111883}- Da. | - Ne.
{111885}{111944}- Da. | - Da.
{111946}{112003}Super. Zgodan je.
{112005}{112153}Ne razumiješ. Ako ga poljubim, | vraæa mi se sjajan, bezbrižan život.
{112155}{112221}A to je problem?
{112855}{112906}Moram iæi.
{112941}{112993}Sada?
{113223}{113273}O, Bože.
{113461}{113511}Taksi!
{113537}{113607}Oprostite, samo sam provjeravala.
{113758}{113852}Pet dolara. Hvala ti, sreæo.
{113898}{113964}Oprostite zbog...
{113966}{114018}- Antonio? | - Bog, Ash.
{114020}{114089}- Bog. | - Koja sreæa da smo te sreli.
{114091}{114149}Žao mi je što sam onako postupila.
{114151}{114208}Imali ste puno pravo.
{114210}{114344}Onda æu te okriviti i za ovog | krasnog muškarca èvrste guze.
{114346}{114419}- Da. Ženimo se, dušo. | - Nemoguæe.
{114421}{114554}- Istina je. Kupila sam mu prsten. | - Baš mi je drago. Èestitam.
{114573}{114651}Želim da ponovo radiš za mene.
{114653}{114738}- Zbilja? | - Ne mogu te izgubiti. Nosiš mi sreæu.
{114740}{114862}- Ne znam što bih rekla. | - Imamo prezentaciju veèeras u osam.
{114864}{115017}Budi uz mene i odjeni nešto | u skladu s titulom dopredsjednice.
{115019}{115084}Zaboga. Hoæu.
{115086}{115150}Hvala. Bog.
{115175}{115269}Sreæa mi se vratila. Bože.
{115323}{115392}- Ima li koga? | - Ash?
{115394}{115477}- Jeste li za kasni ruèak? | - Bog.
{115506}{115578}Nosim iznenaðenja.
{115580}{115642}Zadnja u trgovini i moj broj. Sreæa.
{115644}{115730}Otišla sam u Miyakami | i uzela sve s jelovnika dvaput.
{115732}{115830}- Mislim da moramo proslaviti. | - Zgodno.
{115870}{115964}- Što je? | - Bend neæe Maggienu pjesmu.
{115966}{116069}- Zašto? | - Phillips je praznovjeran.
{116071}{116181}Kaže da novi bend treba svirati | samo svoje pjesme.
{116183}{116253}- To je glupo. | - Ne, samo loša sreæa.
{116255}{116311}Žao mi je. Nisam...
{116313}{116422}Prestani. Nisi ti kriva. | Život je takav, zar ne?
{116424}{116529}Idemo. Moramo stiæi prije nastupa | i poželjeti im sreæu.
{116531}{116656}- Ipak æe nastupiti? | - Imamo VIP ulaznice. Neæe propasti.
{116658}{116774}- Ja ne idem. Imam sastanak. | - Razgovor za posao?
{116776}{116869}Smiješna prièa. Peggy mi je dala posao.
{116913}{116966}Ponosim se tobom.
{116998}{117072}Vidiš da je krenulo na bolje.
{117074}{117166}- Ti si u redu? | - Naravno. Imam li izbora?
{117168}{117291}Ako æeš razmišljati o ružnim stvarima, | promaknut æe ti one dobre.
{117293}{117358}- Uživajte. | - Sretno sa sastankom.
{117360}{117406}Hvala.
{117428}{117484}Bog.
{118235}{118324}DOWNTOWN MASQUERADE RECORDS | PREDSTAVLJAJU MCFLY
{118485}{118566}Super. Ispred njih sam.
{118594}{118677}- Èovjeèe. | - Pogledaj koliko ljudi.
{118679}{118738}Pogledaj onog komada.
{118740}{118805}Na tisuæe ih je.
{118807}{118885}Idemo. Završne sitnice. | U garderobu.
{118887}{118979}- Idemo. | - Baš sam živèan.
{118981}{119040}Nešto æu zabrljati.
{119080}{119130}Nick.
{119183}{119252}- Sranje. | - Izgledaš živèano.
{119254}{119319}- Baš ti hvala. | - Hoæeš biljnog èaja?
{119321}{119483}Hvala. Može. | Monitori su spremni za Dannyja i Toma?
{119503}{119581}Sjeti se zamijeniti izlaze | na tri, pet i devet.
{119583}{119679}Netko bi mogao pasti u ovo. | Zatvorit æu vrata.
{119707}{119774}Hej. Jake. Deèki!
{119789}{119843}Taksi!
{119870}{119987}- Nikad neæemo uloviti taksi. | - Budi pozitivna.
{120021}{120084}Cure, uskoèite. Idemo.
{120145}{120218}Idemo. Nemamo puno vremena.
{120259}{120334}- Ne mogu se prestati znojiti. | - Šokantno.
{120359}{120413}- Jeste li spremni? | - Napeti.
{120415}{120473}Roðeni spremni.
{120475}{120524}- Moje oko. | - A žica.
{120526}{120584}Danny, pogledaj me. Vidiš na njega?
{120586}{120657}- Molim te. | - Dvije minute, deèki. Sretno.
{120659}{120738}Dvije minute. Trebam leda.
{120835}{120887}Ima li koga?
{120889}{120957}Deèki, ovdje sam!
{120982}{121111}- Znam da ste živèani. To je u redu. | - Trenutak.
{121172}{121222}Pametno.
{121288}{121346}Osvježivaè zraka.
{121348}{121440}Je li tko vidio Harryja?
{121464}{121516}Nije ovdje?
{121589}{121641}Ima li koga?
{121709}{121779}Razdvojite se i pronaðite ga.
{121817}{121869}- Jesi li vidio Harryja? | - Koga?
{121871}{121943}- Harryja, bubnjara. | - Koga?
{122107}{122181}- Gubi se. | - Perverznjak.
{122339}{122398}DMR mi je sve, dušo.
{122442}{122516}Skrenite lijevo. | Na Union Squareu je uvijek gužva.
{122518}{122571}Otpilila si Peggy.
{122573}{122723}Preživjet æe. Ako je Jakeova nesreæa | upola kao moja, nemamo puno vremena.
{122752}{122817}Harry, jesi li ovdje?
{122819}{122869}- Je li tko vidio Harryja? | - Ne.
{122871}{122965}Oprostite. Je li tko | vidio Harryja? Bubnjara.
{122967}{123057}- Zna li tko gdje je bubnjar? | - Kako izgleda?
{123059}{123124}Ne znam. Svi su mi isti.
{123405}{123455}Poènite veæ jednom.
{123480}{123543}- Nije ovdje. | - Hoæemo McFly!
{123545}{123632}- Nije ni ovdje. | - Dovedite McFly!
{123766}{123904}Jake. Znam kako to ide. Održavanje | napetosti, ali postaju nemirni.
{123906}{124008}- Uobièajeno je da malo èekaju. | - Nigdje ne mogu pronaæi Harryja.
{124010}{124084}Pogledao sam zahode. | I muške i ženske.
{124086}{124164}Želiš mi nešto reæi, Jake?
{124166}{124215}Imamo problem.
{124323}{124402}Koji je ovo vrag?
{124591}{124649}- Opako kasnimo. Brzo. | - Zaboga.
{124651}{124746}Hvala. Èekajte. | Ulaz na pozornicu je ovdje.
{124748}{124805}Oprostite.
{124807}{124902}- Èekajte me. | - Požuri, imate akreditacije.
{124947}{124998}Ima li koga?
{125003}{125063}Ima li koga?
{125111}{125194}Ja ne želim izaæi na pozornicu
{125196}{125336}i reæi ovoj bijednoj masi | da bend neæe svirati.
{125361}{125438}Neæu ja izaæi. Ti æeš.
{125457}{125529}Ili æeš ih smjesta potjerati gore.
{125531}{125614}- G. Phillips, bez bubnjara? | - To neæe iæi.
{125616}{125744}Deèki, ja sam bio | pomoæni bubnjar za Whitesnake.
{125746}{125840}Whitesnake? Super. | Sada imate bubnjara.
{125842}{125936}- Neæemo nastupiti bez Harryja. | - Ništa od toga.
{125938}{126076}Ako McFly ne zasvira, | neæeš upravljati ni školskim bendom.
{126078}{126165}Evo ga. Maknite se.
{126167}{126215}Hajde sada.
{126217}{126268}Ashley, nije trenutak za...
{126270}{126334}Koji je ovo vrag?
{126492}{126557}Idemo, devet,
{126559}{126612}osam, sedam...
{126647}{126710}- Ne. | - Tko je pustio dim?
{126712}{126806}...pet, èetiri, tri...
{126887}{126933}...dva...
{127064}{127118}Je li to Harry?
{127138}{127189}Idemo.
{127191}{127262}Pokreni ih, srce.
{127264}{127311}Idemo.
{127313}{127401}Ma daj. Izašao je bez nas.
{127403}{127461}Ne mogu vjerovati.
{127588}{127691}- Molim te, odsviraj Maggienu pjesmu. | - Svakako.
{127716}{127785}- Poènite s "I've Got You". | - Svakako.
{127787}{127859}- Phillips æe poludjeti. | - Briga me.
{127870}{127928}Idemo!
{127994}{128076}Harry, sviramo "I've Got You".
{128225}{128289}Hvala ti, Ashley.
{128291}{128349}Nema na èemu.
{128503}{128593}- Jesi li dobro? | - Jesam. Hvala.
{128595}{128663}Ponosim se tobom.
{129338}{129390}- Super su. | - Dobro.
{129731}{129814}Mislio sam da neæe to svirati.
{129816}{129889}Nisam praznovjeran.
{129891}{129953}Ali ja jesam.
{129955}{130015}Trebao bih te otpustiti, Jake.
{130017}{130080}Ali upalilo je.
{130082}{130146}Upalilo je. Èestitam.
{130174}{130212}Hvala.
{130401}{130457}Sviraju moju pjesmu.
{131080}{131151}Je li to pljesak | ili mi se živci raspadaju?
{131153}{131255}- Pljesak je. | - Zdravo, Times Square.
{131374}{131481}- Èestitam. | - Super ste.
{131922}{132017}Tko se želi družiti s mojim prijateljem | g. Domom Perignonom?
{132019}{132106}- To je sigurno berba '94. | - '94 je. To, dušo.
{132129}{132186}To, deèki.
{132188}{132308}Vrijeme je za šampanjac. | Idemo, "McFly" na tri.
{132310}{132409}Katy, pomozi mi. Je'n, dva, tri.
{132411}{132463}McFly!
{132607}{132679}- Danny, dolazi. | - Hajde.
{132681}{132762}Idemo. Zdravica.
{132807}{132875}Idemo proslaviti.
{132877}{132977}- Ne sada. | - Što je? Izgledaš oèajno.
{133002}{133062}Maggie, mislim da sam se zaljubila.
{133134}{133211}Super. Što je tu loše?
{133236}{133354}Ne znam. Ti osjeæaji | obièno vode prema poljupcu.
{133356}{133419}Pa poljubi ga.
{133421}{133481}Ne mogu.
{133539}{133624}Nemoj mi reæi | da još vjeruješ u to?
{133626}{133727}Više nego ikad. Ne mogu ga ne poljubiti.
{133828}{133873}- Moram iæi. | - Kamo?
{133875}{133998}Grand Central. | Idem do roditelja na neko vrijeme.
{134000}{134068}Moram si srediti misli.
{134070}{134160}Zagrli me. | Zabavi se. Èuvaj se.
{134238}{134288}Bog.
{134374}{134434}Okupite se.
{134740}{134786}KASNI
{134809}{134900}- Naravno. | - Èekaš vlak?
{134902}{134983}Ako ga èekaš, | možeš slobodno odustati.
{134985}{135012}Jake, molim te.
{135014}{135127}Uz tvoju sreæu, objavit æe | da su svi vlakovi otkazani.
{135129}{135252}Poæi æeš na autobus i poèet æe | padati kisela kiša, prolom oblaka.
{135254}{135360}Slušaj, ne možemo se viðati. | To je za tvoje dobro.
{135362}{135439}- Sreæa se mijenja, Ashley. | - Znaš?
{135459}{135544}Poljubio sam sjajnu curu | na partyju pod maskama.
{135546}{135626}Nisam luda. | Zbilja nam se sreæa zamijenila.
{135628}{135725}Još je tako. Pokaži da nema dobitka.
{135727}{135806}Misliš da je naš susret bio nesreæa?
{135808}{135915}Ne. Sretna sam što sam te srela.
{135917}{136005}Zaslužio si moju sreæu. | Puno je bolje koristiš od mene.
{136007}{136072}- Ne želim je više. | - Zar si poludio?
{136074}{136131}- Želim ti je vratiti. | - Ne. Odlazi.
{136133}{136231}Bilo je super, ali mogu bez nje.
{136289}{136350}Kako znaš?
{136352}{136413}Jer æu imati tebe u životu.
{136435}{136560}Nekoliko posjekotina i modrica | nisu velika cijena.
{136856}{136896}Ti loviš.
{136898}{136947}NEMA KAŠNJENJA
{137014}{137104}Neæeš se tako lako izvuæi.
{137106}{137161}KASNI | NEMA KAŠNJENJA
{137184}{137250}- Da? | - Nema šanse.
{137352}{137431}- Tko je sada sretan? | - Nije važno.
{137544}{137657}Bljak. Ostaviš dijete u limuzini | kako bi se ljubakao?
{137659}{137730}Odvedeš me od zgodnih rock zvijezda,
{137732}{137867}pukne mi vezica, progutam žvakaæu | i sada moram gledati pretakanje slina.
{137869}{137927}Zaboga.
{137972}{138044}Zbilja sam sretna što si ovdje.
{138080}{138192}- Zašto me tako gledate? | - Ni makac.
{138241}{138333}- Zaslinili ste me. | - Probaj ovo. Svidjet æe ti se.
{138335}{138387}- Zabavno je. | - Super.
{138482}{138561}Gdje smo mi ono stali?
{138594}{138713}25 dolara. Ludnica. Bogata sam.
{138715}{138816}Uzet æu limuzinu. | Ovo moram pokazati baki.
{138818}{138877}Upala mi sjekira u med.
{138930}{138980}Hvala.
{139000}{139056}Zaslužila je.
{139058}{139110}- Pizza? | - Dogovoreno.
{139159}{139218}Hoæeš li moæi živjeti bez sreæe?
{139220}{139277}- Nikad nisam bila sretnija. | - Ni ja.
{139279}{139347}- Vjeruješ u karmu? | - Šališ se?
{139349}{139444}Pomogla sam jednoj starici preko ceste | i drugi dan našla 100 dolara.
{139446}{139483}- To je sreæa. | - Karma.
{139485}{139524}- Sreæa. | - Karma.
{139526}{139591}- Sreæa. | - Karma. Otvori vrata.
{139606}{139664}Hvala.
{139720}{139791}- Novèiæ. | - Još nas prati sreæa.
{139793}{139865}- Baš me briga? | - Tako je.
{139917}{139979}Zatvori ventil. Cijev pušta.
{139980}{140080}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan 
