{1}{1}25.000
{265}{328}U glavnoj ulozi:
{386}{443}K R A LJ   T E K S A S A
{501}{551}U ostalim ulogama:
{1672}{1718}Zašto ih niste skinuli?
{1726}{1787}Htio sam da ih vidite.
{1815}{1879}Vidio sam. Skini ih.
{3132}{3179}Tata, propuštaš ples.
{3383}{3427}Jesi li dobro?
{3500}{3541}Tata?
{3694}{3812}Susannah kasni. -Doæi æe.|Dug je put od Austina.
{3816}{3927}Baš me briga koliko je daleko.|Želim da su mi sve tri kæeri ovdje.
{4054}{4180}Ja sam star, zar ne, Claudia?|Star kao ova zemlja.
{4197}{4265}Star kao Texas, tata.
{4279}{4345}Doði, svi èekaju.
{4636}{4696}Raðeno po predstavi|"Kralj Lear" V. Shakespearea
{4869}{4907}Režija:
{4929}{4975}Evo ga.
{5315}{5403}Tata. -Gdje je on?|-Dolazi.
{5410}{5510}Nezahvalni klipan. Bolje da|ne dopusti da ga John Lear èeka.
{5515}{5583}Ne brini za Thomasa, tata.|Idemo.
{5679}{5729}Svirajte.
{5755}{5805}Divno je vidjeti vas.
{5814}{5875}Sretan Dan nezavisnosti.|Hvala.
{5889}{5944}Sretan vam Dan nezavisnosti.
{6007}{6060}Henry.
{6095}{6178}Emmett. -G. Leare...|-Lijep ti je taj konj, Henry.
{6189}{6240}Najbolji kojeg sam odgojio.
{6248}{6323}Podsjeæa me na pastuha|kojeg si jahao u San Vicenteu.
{6326}{6433}Želim da ga uzmeš, Johne.|-Vrlo pažljivo od tebe, Henry.
{6446}{6509}G. Leare. Do vraga...
{6591}{6667}Tvoj otac mi je poklonio|ovog konja, Thomase.
{6673}{6776}Vrlo obzirno od njega,|žao mi je što nisi vidio to.
{6783}{6861}Tata ne pokazuje èesto|tu svoju stranu.
{6866}{6950}Jesi li pijan, sinko?|-Da, pio sam.
{6996}{7083}Ovo je zabava, zar ne?|Dan nezavisnosti Texasa.
{7123}{7245}Ne bi bilo nezavisnosti Texasa|da nije bilo ljudi poput tvog oca.
{7252}{7340}Neæeš stajati|pred njim i preda mnom
{7343}{7436}s tim prezrivim osmjehom.|Neæu to trpjeti!
{7516}{7603}Zahvalan sam ti, Henry.|Ovo je najbolji konj
{7608}{7695}kog sam ikad vidio.|-Hvala, Johne.
{7698}{7794}Ripe, dobro pazi na ovog konja.|-Da, gospodine.
{7960}{8033}Ma, daj, tata.|-Što je s tobom, Thomase?
{8036}{8139}Voliš svog oca praviti budalom|pred njegovim prijateljima?
{8141}{8193}Idi do vraga, deèko.
{8376}{8430}Dosta mi ga je, Emmett.
{8462}{8530}Cijeli život to trpim.|-Znam...
{8634}{8735}I dalje planiraš otiæi|u San Anton na nekoliko dana?
{8739}{8843}Što želiš reæi?|-Samo da je sad dobar trenutak.
{8861}{8954}Ja æu preuzeti tvoje obveze.|To æe tati dati vremena
{8958}{9035}da se ohladi,|a tebi da razmisliš.
{9075}{9154}Do vraga,|mogu to i odmah uèiniti.
{9733}{9774}Hvala.
{9969}{10044}Rebecca. -Susannah,|drago mi što te vidim.
{10049}{10135}Kako je on danas?|-Nepredvidiviji nego ikad.
{10139}{10232}Je li uèinio nešto ludo?|-Ne, ali još je rano.
{10314}{10355}Zdravo, tata.
{10407}{10492}Kako si? -Podnošljivo.|Kasniš, Susannah.
{10495}{10568}G. Tumlinson.|-Sretan Dan nezavisnosti, Johne.
{10572}{10703}Claudia, dobro brineš o njemu.|Zloban je, kao i uvijek.
{10706}{10829}Bogami, jesam. Uðite u kuæu,|imam vam nešto za reæi.
{10841}{10883}Doðite.
{11036}{11086}Zatvorite kapiju!
{11476}{11525}Leare!
{11554}{11635}Johne Leare! Gdje si?
{11819}{11873}Objesio si dva moja kauboja!
{11876}{11944}Kauboja?|Bili su kradljivci stoke.
{11947}{12018}Uhvaæeni su kako kolju|kravu s mojim žigom.
{12021}{12111}Bili su gladni jer si ih|otjerao s njihove zemlje.
{12114}{12196}To je moja zemlja, Menchaca,|i moja stoka.
{12199}{12300}Objesio si dva èovjeka zbog|jedne krave! Kakav si ti èovjek?
{12324}{12437}Vrlo dobro znaš kakav sam èovjek.|I tvoj otac je to znao.
{12439}{12530}Moj otac bi te veæ ubio,|stari.
{12544}{12691}Slobodno pokušaj, Toribio.|Zašto odmah ne probaš?
{13001}{13069}Nismo završili!|-Da, jasno.
{13073}{13169}Bježi s moje zemlje|prije nego što i tebe objesim.
{13306}{13423}Trebali smo ga otjerati preko|Rio Grandea kad smo imali priliku.
{13444}{13501}Nije kasno za to.
{13665}{13750}Predsjednik Houston je|zamolio da vam ovo donesem.
{13753}{13861}Kako je Sam? Je li se trijezni?|Gdje sam stavio naoèale?
{13863}{13974}To je proglas. Hoæeš da ja|proèitam? -Do vraga, zašto ne?
{14010}{14097}"Na godišnjici roðenja|naše mlade republike,
{14101}{14184}"odajemo poèast èovjeku, bez|èijeg hrabrog i nepokornog duha
{14187}{14251}"Texas nikad ne bi bio osvojen.
{14257}{14334}"Tijekom najmraènijih dana|naše borbe, kad je Alamo pao,
{14339}{14426}"kad je njegov roðeni sin|žrtvovan kod Goliada,
{14430}{14501}"John Lear je..."|-U redu je, shvatio sam bit.
{14507}{14595}Houston je oduvijek bio|preopširan kuèkin sin.
{14663}{14758}Ali, danas moram|raspraviti neke važnije stvari.
{14764}{14892}Ovo je Palo Blanco|i njegovih 200.000 jutara.
{14923}{15005}Ovdje je glavna kuæa.|Ovo je tvoje, Rebecca.
{15008}{15139}Svaki potok i klanac izmeðu.|Svako jutro zemlje plaæeno krvlju.
{15183}{15296}Nadao sam se da æu|tu zemlju predati svom sinu,
{15300}{15374}ali njega nema, mrtav je...
{15408}{15537}Shvatio sam da moj život nije|imao veæeg utjecaja na ovu zemlju
{15570}{15652}nego što vlat trave ima|utjecaja na drvo meskita.
{15654}{15762}Samo još jedno biæe koje je|na njoj proživjelo svoje dane.
{15766}{15900}Ali, tako mi Boga, još uvijek mogu|odluèiti tko æe je posjedovati.
{15921}{16001}Odluèio sam podijeliti ranè.
{16099}{16155}Kako to misliš, tata?
{16160}{16281}Od danas predajem ranè vama,|djevojkama.
{16294}{16471}Hoæu sve ovo sad srediti, da se|ne biste svaðale kad ja umrem.
{16489}{16582}Tata, je li se dobro osjeæaš?|-Dobro mi je, Claudia.
{16590}{16692}Ove godine æu, kao i uvijek,|voditi skupljanje krda.
{16700}{16818}Ali, neæu zauvijek biti ovdje,|pa hoæu ovo srediti.
{16822}{16960}Tko dobiva koji dio zemlje?|-Susannah, to zavisi...
{16987}{17043}Od èega?
{17107}{17229}Od toga koja od vas|najviše voli svog oca.
{17261}{17364}Izvoli, ti si najstarija.|Susannah, govori.
{17562}{17665}Nema èovjeka u ovoj zemlji koji se|može usporediti s mojim ocem.
{17667}{17735}Nijedan èovjek nikad nije mogao.
{17815}{17930}Došao si u Texas bez ièega|i stvorio si carstvo.
{17965}{18066}Možda si bio grub,|ali zato što si morao biti takav.
{18071}{18180}Da nisi bio takav, Komanèi bi|nas istjerali prije mnogo godina.
{18191}{18258}Volim te zbog tvoje snage.
{18265}{18348}Volim te i zbog snage|koju si meni ulio.
{18382}{18482}Dat æu ti svu zemlju|istoèno od potoka Las Animas.
{18499}{18596}To je veliki pojas zemlje,|prostire se do izvora.
{18600}{18694}Ali, tvoja kuæa je na toj|strani ranèa. -Znam to.
{18698}{18813}Prijeæi æu se u prizemlje, a ti|i tvoj muž se uselite na kat.
{18816}{18917}Provodit æu pola godine s tobom,|a drugu polovinu s Rebeccom.
{18920}{18978}Odgovara vam to, g. Tumlinson?
{18981}{19051}Da, naravno.|Vrlo je velikodušno.
{19216}{19283}A sad, Rebecca.
{19324}{19414}Tata, ne znam što reæi.|-Ne znaš?
{19528}{19603}Kad bih bila vješta s rijeèima|kao Susannah,
{19606}{19669}možda bih ti mogla reæi|koliko te volim.
{19671}{19759}Tata... -Šuti, Claudia.|Doæi æeš i ti na red.
{19816}{19914}To se ne može isprièati,|samo se može osjetiti.
{19932}{20035}Isti osjeæaj imam dok|jašem po preriji prije zore,
{20041}{20170}kad sunce izaðe i ogrije mi lice,|a divlje cvijeæe se poène otvarati.
{20213}{20284}Eto koliko te volim, tata.
{20312}{20373}Kao što volim sunce.
{20448}{20551}Dat æu tebi i tvom mužu zemlju|zapadno od potoka. -Gospodine...
{20601}{20698}Ta zemlja je slana.|Nije dobra za ispašu.
{20712}{20792}Znam to.|Prièekaj, Highsmith.
{20795}{20928}Svu zemlju zapadno od potoka|i južno od stare španjolske utvrde.
{20936}{21034}Je li ti se to više sviða?|-Da, gospodine.
{21210}{21281}Claudia,|sad æu tebe saslušati.
{21285}{21382}Ostala je najbolja zemlja.|-Nemam što reæi.
{21451}{21506}Što je rekla?
{21521}{21635}Rekla je da nema što za reæi.|-Ništa? -Ništa.
{21674}{21791}Ništa ne donosi ništa.|Bolje ponovo razmisli. -Neæu.
{21795}{21871}Ovo je nepošteno,|ne želim ništa imati s tim.
{21874}{21945}Nepošteno? Kako to misliš?
{21956}{22057}Pripazi na rijeèi ako neæeš|da odbaciš svoj miraz.
{22062}{22170}Dijete ili voli svog oca ili ne.|-Da. -Pa, reci to.
{22210}{22291}Zašto ne želiš reæi,|kao tvoje sestre?
{22294}{22376}Trebala bi to vidjeti. Zar|ti ne dokazujem ljubav svaki dan,
{22380}{22442}živeæi u tvojoj kuæi|i brinuæi se o tebi?
{22446}{22502}Susannah i Rebecca imaju muževe.
{22505}{22606}Ponosna je, prava kæer|svoga oca. -Ne upliæi se.
{22655}{22705}Reci, Claudia.
{22710}{22782}Ne možeš ljudima|zapovjediti da vole.
{22785}{22926}Ljubavi ili ima ili nema.|-Reci. -Ne. -Reci!
{22950}{23017}Johne, trebate razmisliti...
{23085}{23147}Kakvo je ovo dijete?
{23176}{23303}Dijete koje sam gajio u svojoj|kuæi, kome sam poklonio srce?
{23327}{23426}Nema više osjeæaje|od podmukle èegrtuše.
{23430}{23497}Ne, gajim previše osjeæaje...
{23500}{23589}Sve ove godine si se|pretvarala da voliš oca,
{23591}{23671}a u srcu si nosila samo otrov!|-Ne.
{23674}{23799}Neæu èuvati zveèarku u kuæi!|Neæeš dobiti dio ovog ranèa.
{23802}{23839}Leare, sad je dosta!
{23841}{23948}Dosta? Tko si ti da govoriš|Johnu Learu koliko može govoriti?
{23951}{24037}Tata... -Prekasno je, Claudia.|Ne želim te slušati.
{24041}{24160}Nikad te više neæu pogledati!|Nemaš dom! I nemaš oca!
{24182}{24239}Idi! Odlazi!
{24272}{24333}Ne možete je istjerati.
{24339}{24438}Šutjet æeš ili æu te srediti.|Jesi li me razumio?
{24690}{24790}Zašto si još uvijek ovdje?|Odlazi iz moje kuæe!
{25244}{25332}Vas dvije æete dobiti|po pola ranèa.
{25505}{25614}Tata... -Ništa ne govori, Rebecca.|Ništa ne želim èuti.
{25648}{25701}Pozdravljam vas sve.
{25763}{25831}Bit æe sve u redu.|Urazumit æe se on.
{25834}{25908}Nikad mi neæe|dopustiti da se vratim.
{25911}{26013}Susannah i ja æemo uskoro živjeti|ovdje. Razgovarat æemo s tvojim ocem.
{26216}{26319}Podjela imanja sjeverno i južno|od potoka izgleda fer.
{26322}{26430}Odgovara li vam to, g. Highsmith?|-Ovo bi mi odgovaralo.
{26433}{26511}To je Menchacova zemlja.|-To Menchaca kaže.
{26514}{26621}Svi znaju da je to sporna zemlja.|Moglo bi se smjestiti mnogo stoke.
{26624}{26729}I zapoèeti novi rat.|-Zadnji nismo ni završili.
{26749}{26836}Moj muž to nikad ne bi dopustio.|-Naravno da ne bi.
{26841}{26960}Tvoj muž je dobar èovjek,|èlan teksaške vlade.
{26970}{27103}Zar ne ide uskoro u Austin,|na sastanak sa zakonodavcima?
{27117}{27218}Ne znam što... -Šuti, Rebecca.|Prièam s tvojom sestrom.
{27268}{27380}I ti i ja znamo da je|borba s Menchacom neizbježna.
{27393}{27504}Bolje da prvi udarimo, kako|bismo imali šansu pobijediti.
{27652}{27693}Claudia?
{27775}{27857}Gðice Claudia, kuda æete?
{29452}{29504}Što se dogodilo, Claudia?
{29593}{29683}Izbacio me je.|-Tvoj otac?
{30252}{30334}Ne trebaš biti tako oštar|prema Thomasu, tata. -Zašto?
{30337}{30435}Da njegovoj majci na samrti nisam|obeæao da æe ranè ostati njemu...
{30440}{30543}Nema svrhe prièati o tome. Odavno|sam nauèio živjeti kao kopile.
{30546}{30650}Ranè nije dovoljno veliki|da se podijeli. -Gdje su konji?
{31245}{31294}Svi su nestali, tata!
{31417}{31467}Placido.
{31539}{31617}Ubit æu èovjeka koji je to uèinio.
{31649}{31694}Pažljivo.
{31700}{31799}Stavi to u zadnji dio salona.|-Si, seòora.
{31951}{32069}Glazba. To je kuæi nedostajalo|otkad je vaša majka umrla.
{32073}{32167}Ovu kuæu æeš opet uèiniti|pravim domom, Susannah. -Hvala.
{32172}{32292}Poslije tjedan-dva u preriji,|žudjet æu za glazbom. -Svirat æu ti.
{32307}{32412}Napravi mi pitu s breskvama.|Godi mi poslije sakupljanja stoke.
{32418}{32478}Hoæu, tata.
{32509}{32568}Warnell. -Gospoðo.
{32574}{32661}Pripazi na njega.|-Da, gospoðo.
{32703}{32753}Dobro jutro, momci.|-Dobro jutro.
{32756}{32857}Lijep dan za skupljanje stoke.|-Imate pravo, gazda.
{32863}{32932}Previše ste stari|da skupljate stoku.
{32935}{33041}Ne zanima me tvoje mišljenje.|-Da, znam to.
{33045}{33149}Nikad vas nije zanimalo|nièije mišljenje osim vašeg.
{33151}{33216}Padnite s konja|i slomite prokleti vrat.
{33219}{33294}Nemam namjeru pasti|s ovog konja.
{33298}{33405}Ne vjerujem ni da ste imali|namjeru da tako ostarite.
{33450}{33583}Ripe, osedlaj konja. -Zašto?|-Zato što ideš sa mnom.
{33607}{33723}Ne, ostat æu. Ovo mjesto je|ugodno kad vi niste u blizini.
{33731}{33833}Ne namjeravam ti život|uèiniti ugodnim.
{33850}{33914}Ideš s nama. -Zašto?
{33917}{34015}Zato što si jedini|koji me može nasmijati.
{34031}{34083}Uzjašite, ljudi.
{34315}{34355}Ripe, na bok.
{34639}{34676}Hajde.
{35051}{35139}Melem za dušu je biti ovdje.
{35154}{35261}Ništa mi ne godi više|od tvrde zemlje i divlje stoke.
{35294}{35366}Ripe, pjevaj mi nešto.
{35948}{36027}Možda trebate živjeti|meðu ovom stokom,
{36031}{36125}jer vaše pjevanje ne mogu|slušati ljudska biæa.
{36129}{36252}Ne znam zašto ti dopuštam|da tako razgovaraš sa mnom.
{36257}{36358}Da imaš pameti, obuzdao bi jezik|i bojao bi me se.
{36378}{36449}Sav moj strah je nestao u Alamu.
{36716}{36766}Tko je ovo, kog vraga?
{36858}{36937}Dobar dan.|-Dobar dan i vama, gospodine.
{36941}{37028}Vi ste g. Westover?|-Tako je. -Poruènik Vince.
{37053}{37110}Što mogu uèiniti za vas?
{37115}{37228}Nadao sam se da imate još konja|za prodaju, vojsci uvijek trebaju.
{37231}{37286}Nikad nisam prodao konje vojsci.
{37290}{37387}Imaju vaš žig, g. Westover.|Bila je to legalna kupovina.
{37413}{37519}Koliko ste ih kupili?|-Vjerujem da ih je bilo osamnaest.
{37574}{37664}Tko vam ih je prodao?|-Nije rekao ime.
{37668}{37823}Kako je izgledao? Meksikanac?|-Nije. Ove visine, smeðe kose.
{37857}{37982}Imao je ožiljak na èelu.|Nije lièio na konjokradicu.
{38104}{38207}Krenite dalje.|Ovdje nema konja za prodaju.
{38215}{38297}Oprostite na smetnji.|Do viðenja.
{38487}{38584}Sigurno je greška, tata.|-Naravno da je greška.
{38748}{38805}Osamnaest konja, Emmett.
{38819}{38937}Kaže da je imao ožiljak na èelu,|kao što ima Tomas.
{38942}{39046}Tomas nikad ne bi ukrao|od svog roðenog oca.
{39071}{39128}Izbaci te misli iz glave.
{39472}{39522}Tjeraj ih ovamo.
{40021}{40105}Vruæe je.|Mogu li napojiti konja?
{40109}{40253}Samo konja. Ne želim da robovi|zagade ovu vodu pijuæi je.
{40337}{40403}Rekao sam ti da to ne radiš.
{40487}{40585}Ti si onaj kuèkin sin|iz Alama, nisi li?
{41171}{41267}Jesi li ikad primijetio kako su|grane meskita pune trnja?
{41333}{41414}Vjerujem da je Bog|mislio na odbjegle robove
{41417}{41510}kad je stvarao to drvo.|-Ja nisam odbjegli rob.
{41563}{41621}Kako mogu znati razliku?
{41644}{41719}Imaš li papire|da dokažeš da nisi odbjegli rob?
{41723}{41823}Imaš li ti papire da dokažeš|da nisi glupi kuèkin sin?
{41877}{41948}Je li to dovoljno zaboljelo?
{42153}{42280}Mislio sam da je pobjegao,|da je ukrao konja i pobjegao vam.
{42553}{42623}Ne, ne...|Ne udarajte me više, gazda.
{42634}{42714}Hoæeš li se ponovo|miješati u moje vlasništvo?
{42717}{42765}Ne, neæu.
{42890}{42941}Gubi se odavde!
{43214}{43319}Jedan od momaka ima|melem od aloe.
{43336}{43452}Bio bih zahvalan za to.|Košulja mi je potpuno iskidana.
{43455}{43541}Zašto to meni govoriš?|Nisam ja švalja.
{43605}{43673}Nikad nisam ni mislio da jest.
{43717}{43823}Penji se na konja,|da više ne gubimo vrijeme.
{44073}{44133}Vidim, idete kuæi, g. Highsmith.
{44138}{44215}Vrijeme je da se vratim|na naš dio ranèa.
{44220}{44321}Moj muž æe biti odsutan|bar nekoliko tjedana.
{44357}{44463}Što ste imali na umu?|-Ne igrajmo igrice, g. Highsmith.
{44566}{44651}Trebaju nam ljudi.|-Imam ih tuce na mom ranèu.
{44655}{44745}Trebat æe nam više.|-Pitat æemo g. Westovera.
{44749}{44859}Ako nam se pridruži èovjek koji je|zarobio Santa Anu, i ostali æe.
{44908}{45014}U pravu je. Westover je|uvijek spreman za borbu.
{45017}{45103}Htjet æe znati što Lear misli.
{45146}{45213}Recite mu da je otac uz nas.
{45569}{45646}Nadam se da si donio bratu|nešto iz San Antona.
{45651}{45713}Boca viskija bi bila dobra.
{45773}{45914}Gdje su konji? -Bolje pitaj tatu.|U kuæi je, veèera. Ja æu to.
{46272}{46326}Kako si, tata?
{46366}{46557}Gdje su konji? -Ukradeni su.|-Ukradeni? Svi?
{46646}{46702}Do vraga, gdje je Placido?
{46705}{46824}Vrlo dobro znaš gdje je.|U svom grobu. -Što?
{46875}{46957}Ne znam zašto si tako nešto|uèinio, Thomase.
{46960}{47092}Ali, kad èovjek nosi dovoljno|mržnje u srcu, spreman je na sve.
{47124}{47250}Misliš da sam ja ukrao|naše konje? Da sam ubio Placida?
{47286}{47369}Pogledaj me, tata!|Pogledaj me!
{47453}{47537}Misliš da sam ukrao konje?|-Da.
{47576}{47639}Ne vidim ovdje bocu viskija.
{47695}{47750}Mora biti da me zaista mrziš.
{47755}{47834}Znam piti i povremeno|ne obuzdavam jezik,
{47838}{47900}ali nisam konjokradica i ubojica!
{48060}{48111}Tata, to nije moje!
{48127}{48216}Ti si lažljivac!|Konjokradica i ubojica!
{48219}{48301}Izgubio si razum, starèe!|-Van!
{48320}{48385}Van iz moje kuæe!
{48548}{48605}Nikad se više ne vraæaj!
{49312}{49387}Mislio sam da si|zaboravio na mene.
{49489}{49576}Kako sam odglumio?|Da probam u kazalištu?
{49582}{49636}Bogami bi trebalo.
{49653}{49741}Bili ste pošteni prema|meni i mojim ljudima.
{49769}{49876}Dobro smo zaradili od onih konja.|Pola-pola, kao što smo rekli.
{49897}{50005}Smijem li zadržati odoru?|Sviða mi se kako mi stoji.
{50243}{50301}Zadrži odoru.
{50516}{50566}Krdo raste, Susannah.
{50577}{50690}Ove godine rijetko koja krava|nema tele uz sebe.
{50707}{50795}Nadam se da si napravila|onu pitu od breskvi.
{50799}{50905}Prebio si Warnella skoro na smrt.|-Muèio je Ripa.
{50933}{51026}Trebao si doæi kod mene,|ja bih to sredila.
{51031}{51153}Kod tebe? Kad se pakao zaledi.|Sam se brinem o svom poslu.
{51204}{51283}Kava je hladna|kao voda iz bunara.
{51286}{51358}Odrekao si se svog posla,|zar si zaboravio?
{51361}{51470}Ako netko od mojih ljudi treba|biti kažnjen, ja æu to odluèiti.
{51474}{51533}Pazi kako govoriš sa mnom.
{51537}{51638}Spremi veèeru, moji ljudi su|gladni, danima gone stoku.
{51641}{51691}Nahranit æu tvoje ljude,
{51695}{51787}ali ti ne oèekuj gostoprimstvo,|zato jer ga neæeš dobiti.
{51791}{51860}Ne poslije onog|što si uèinio Warnellu.
{51865}{51940}Pokaži poštovanje|ili æu te otjerati kao Claudiju.
{51943}{52004}Patetièni, jalovi starèe.
{52015}{52123}Uživaš me ljutiti, zar ne?|Ražesti me ponovo i zažalit æeš.
{52175}{52293}Sad spremi veèeru|za mene i moje ljude.
{52478}{52528}Daj mi još piæa.
{52682}{52732}Što to radite?
{52736}{52852}Dižemo paklenu galamu, Susannah.|-Prestanite odmah!
{52866}{52965}Neæu da tvoji pijani ljudi|pucaju oko moje kuæe.
{52968}{53035}Hoæeš, ako ja tako kažem!
{53124}{53180}Prisilite ovo zvono da zvoni!
{53316}{53376}Odlazite odavde!
{53423}{53490}Idite iz moje kuæe!
{53494}{53583}Tvoje kuæe? Ovo je moja kuæa.|-Više nije.
{53783}{53905}Boga mi, uèinila bi to, zar ne?|Ubila bi roðenog oca.
{53942}{54049}Ljudi, odlazite odavde!|Idite u spavaonicu!
{54150}{54229}Hajde!|Uèinite što sam rekla!
{54232}{54308}Neæe te poslušati.|Oni rade za mene.
{54312}{54419}Ne, oni rade za mene.|Èujete li? Radite za mene!
{54450}{54558}Ako ne uèinite ono što sam rekla,|više neæete vidjeti svoje plaæe.
{54562}{54635}Sad sam ja vlasnik ranèa!
{54730}{54830}Gospodine Lear?|-Uèinite ono što kaže.
{54860}{54978}Ti i ostali idite odavde.|Odlazite! Svi vi!
{55436}{55626}Zašto, Susannah?|Zašto si se okrenula protiv mene?
{55663}{55746}Dao sam ti ranè, dao sam ti sve.
{55749}{55849}Nisi mi ga dao, tata.|Prodao si mi ga.
{55906}{56008}Rekao si cijenu|i ja sam je platila.
{56026}{56111}Nemoj misliti da sam lako|platila tu cijenu.
{56116}{56257}Morala sam reæi da te volim,|iako te oduvijek mrzim. -Mrziš?
{56314}{56432}Ti si obièan stari tiranin.|Samo to.
{56460}{56541}Radom si otjerao|našu majku u grob.
{56555}{56698}Nikad nisi primjeæivao|Rebeccu, niti mene. Nikad!
{56749}{56819}Stalo ti je samo do tvog sina.
{56823}{56933}Kad je on umro,|mario si samo za Claudiju.
{56938}{57045}Pa, njih sad nema|i tvoj život je završen.
{57055}{57195}Nije. Kad se završi,|ustat æu iz groba
{57240}{57326}i progonit æu te do Sudnjeg dana.
{57346}{57493}Uèinit æu nešto. Ne znam što.|Zažalit æeš što si to doživjela.
{57679}{57746}Sjeæam se dana kad si se rodila.
{57759}{57884}Tvoja majka mi te je dala|i rekla: "Johne, evo tvoje kæeri."
{57928}{57998}Bila si lijepo, zdravo dijete.
{58022}{58197}Nježno sam te volio. Ali, sad su|ta osjeæaje napustila moje srce.
{58225}{58329}Sad si mrtva za mene.|Mrtva kao zimska trava.
{58353}{58492}Sad imam samo jednu kæer!|-Slobodno neka te uzme!
{59483}{59591}Nadam se da æe gða Highsmith|biti bolja od gðe Tumlinson.
{59595}{59696}Rebecca je privrženo dijete,|jedina od svih.
{59704}{59785}Sigurni ste u to?|-Da, siguran sam.
{59798}{59858}Rekla mi je to.
{59918}{60024}Zašto se smiješ? -Mislio sam|da su stari ljudi mudri, ali nisu.
{60028}{60123}Vi ste pravi dokaz toga.|-Nisam rekao da sam mudar.
{60127}{60198}Nikad se nisam time hvalio.
{60254}{60316}Zašto me moja djeca mrze?
{60383}{60487}Ne pitajte me to, ako ne želite|èuti istinu. -Reci mi.
{60502}{60594}Zato što u vama nema ljubavi.|Samo ponos.
{60716}{60777}Na tegobnom sam putu, Ripe.
{60782}{60871}Ja se borim s bolom tako|što se pravim da je veæ prošao.
{60874}{60985}Kako to misliš? -Razmišljam|o sebi kao da sam veæ mrtav.
{61004}{61108}To se trebalo dogoditi,|da budem ubijen u Alamu.
{61149}{61221}Pretpostavljam da sam duh.
{61224}{61353}Bol mi više ne smeta,|kao ni ljudi. Završio sam s tim.
{61594}{61644}Kuda æete?
{62420}{62579}Mislim da je Rebeccina kuæa tamo.|Da, baš iza tog brda.
{62596}{62710}Da, tako je.|Sad mi je dobro.
{62746}{62894}Na trenutak sam se zbunio.|-Njena kuæa nije tamo.
{63111}{63171}Siguran si? -Jesam.
{63226}{63378}Ne trebam se gubiti.|Ovo je moja zemlja, poznajem je.
{63420}{63519}Stvorio sam ovu zemlju, iz nièega.
{63661}{63744}Doðite,|naæi æemo kuæu gðe Highsmith.
{63954}{64015}Poèinjem li gubiti razum, Ripe?
{64054}{64102}Ne znam.
{64165}{64285}Ne dopusti da poludim.|Ubij me prije toga.
{64608}{64709}Uskoro možemo napasti.|-Što Lear misli o tome?
{64716}{64833}Lear je uz nas. -John Lear je|oprezan èovjek, iako naprasit.
{64841}{64916}Sigurno vidi neku|korist u tome. -Vidi.
{64920}{65007}Koliko æe nam ljudi trebati?|-Stotinjak.
{65012}{65102}Menchaca ima mnogo kauboja|i dva topa.
{65136}{65191}I nama trebaju topovi.
{65194}{65279}Nabavit æemo ih,|posebno ako se vi pridružite.
{65572}{65677}Tvoj muž je smislio hrabar plan.|-On je hrabar èovjek.
{65713}{65813}Nepromišljen, koliko sam èuo.|A uz to je i zao.
{65818}{65894}Èovjek koji bi nasrnuo|i na roðenu ženu.
{65898}{65982}Zlobno ogovaranje.|-Ne znaèi da nije toèno.
{66033}{66137}Zabrinut si za mene?|-Moguæe da jesam.
{66158}{66296}Tvoj otac te sluša.|Nagovori ga da nam se pridruži.
{66300}{66451}Zašto? -Zbog dobitka.|Zemlje i stoke, i drugih stvari.
{66835}{66876}Rebecca?
{66984}{67028}Rebecca.
{67093}{67150}Johne, dobro došao.
{67281}{67421}Johne, uði. Trebamo razgovarati|o nekom poslu. -Hoæu.
{67566}{67666}Rebecca, išao sam tvojoj kuæi,|tražeæi te. Rekli su da si ovdje.
{67697}{67758}Trebala si mi, Rebecca.
{67863}{67926}Nešto se dogodilo Susannah?
{67967}{68111}Izbacila me je.|-Sigurno nije tako mislila.
{68141}{68230}Znaš da su djeca|dužna da poštuju oca.
{68235}{68302}Ti si jedina koja to radi.
{68464}{68550}Zašto ste ovdje?|-Prièamo o planu.
{68562}{68661}Kakvom planu?|-Poæi æemo na Menchacu.
{68665}{68734}Isti plan o kome su|tebi prièali.
{68739}{68827}Nitko mi ništa nije rekao|o borbi protiv Menchace.
{68831}{68908}To je tvoja ideja, Highsmith?|-Jest.
{68925}{68984}Trebate nam se pridružiti.
{68988}{69063}Da nije bilo Menchacovih,|vaš sin bi još bio živ.
{69075}{69146}Znam zašto je moj sin mrtav.
{69149}{69252}Ali, obeæao sam Shemu Hustonu|da neæu dirati Menchacinu zemlju.
{69257}{69380}Došao si u moju kuæu|i lagao me? Neæu to trpjeti.
{69390}{69510}Trpjet æete Menchacu na zemlji|koja treba pripadati Teksasu?
{69540}{69679}Da pripada nama?|Ne vidite? Ovo je naša šansa.
{69688}{69790}Èovjek, koji ne iskoristi takvu|šansu, jest kukavica.
{69795}{69912}Nazivaš me kukavicom? Vidio sam|tvoju hrabrost kod San Jacinta,
{69918}{70012}kad si ubijao Meksikance|koji su se htjeli predati.
{70016}{70117}Poškakljat æu rebra svakom èovjeku|koji tako razgovara sa mnom!
{70132}{70219}Bio bi s nama da je u tebi|ostalo imalo razuma! -Ti...
{70222}{70384}Tata. -Uzmi svog konja, Rebecca.|-Što? -Ideš sa mnom.
{70401}{70525}Nisam smio dopustiti da se|udaš za neèasnog izdajnika.
{70537}{70598}Odvest æu te od njega.
{70781}{70871}Neæu otiæi.|-Neæeš? Zašto?
{70967}{71090}On je moj muž. -Dijete,|nije dostojan da ti bude muž.
{71106}{71186}Znam da nisam uvijek bio|dobar otac,
{71195}{71293}ali uvijek sam te volio|najviše od svih kæeri. -Nisi.
{71314}{71412}Što govoriš?|Valjda poznajem vlastito srce.
{71416}{71492}Uvijek si mi bila miljenica, Rebecca.
{71498}{71592}Doði, odsad æemo biti|samo ti i ja.
{71787}{71924}Ne prkosi mi, dijete.|-Ostajem sa svojim mužem.
{72135}{72300}Dobro. Ostani.|Ostani s tim dobrim èovjekom.
{72340}{72426}Pristaje ti.|-Tata! -Makni se!
{72511}{72640}Ionako nisi dio mene,|osim kao što je bolest dio mene.
{72646}{72696}Molim te, prestani.
{72699}{72787}Ti si moj neprijatelj,|kao i tvoje sestre.
{72792}{72905}Borite se protiv Menchace.|Kad budeš dozivala oca,
{72918}{73023}kad te njegovi kauboji bace|na leða, s nožem pod grlom...
{73030}{73130}Kad budeš dozivala Johna Leara,|ja te neæu èuti.
{73134}{73194}Bit æu gluh za tvoje jauke.
{73199}{73300}Želim vam ugodan dan!|Dabogda svi gorjeli u paklu!
{73424}{73471}Tata...
{73592}{73701}Ti si budala, Highsmith.|-Vidjet æemo tko je budala.
{73842}{73917}Hajde, Rebecca. Idemo.
{73941}{74079}Ripe! Kuda æeš?|I ti mi okreæeš leða?
{74082}{74190}Je li istina da se spremaju|napasti Menchacin ranè?
{74194}{74250}Istina je, Ripe.
{74300}{74376}Onda je gðica Claudia|u opasnosti.
{74405}{74475}Claudia je kod Menchace?|-Jest, gospodine.
{74479}{74516}Otkud ti to znaš?
{74519}{74643}Navikao sam gledati svojim|oèima. Netko je mora upozoriti.
{74975}{75065}Sjeæaš li se one užasne oluje|kad smo bili djeca?
{75109}{75209}Moj i tvoj otac su otišli|zajedno na pašnjak,
{75213}{75290}spasiti stoku od davljenja.|-Sjeæam se.
{75294}{75394}Moja baka je bila bolesna,|a tvoja majka je donijela lijek.
{75397}{75462}Tada sam te prvi put vidio.
{75739}{75790}Sam sam.
{75976}{76076}Senor Westover, što je toliko|važno da riskirate dolazak?
{76080}{76153}Gdje je gðica Claudia?|-Nije ovdje.
{76157}{76272}Znam da jest. -Ne brinite.|Da je ovdje, bila bi sigurna.
{76281}{76364}Ne vjerujem da bi.|-Zašto?
{76391}{76491}Neka mi Bog oprosti|što ovo govorim.
{76532}{76631}Postoji plan.|Dolaze da ti otmu zemlju.
{76689}{76775}Ne sjeæam se vremena|bez takvog plana.
{76779}{76877}Ovog puta æe se ostvariti.|Highsmith okuplja ljude.
{76880}{76954}Ne, Lear to ne bi uèinio.
{76966}{77057}Sposoban je za svašta,|ali nikad ne bi pogazio rijeè.
{77060}{77121}Lear više nije glavni.|Izbaèen je.
{77124}{77174}Tko ga je izbacio?
{77177}{77251}Druge kæeri.|Više nema dom.
{77301}{77391}Morate ga pronaæi, g. Henry,|i dovesti ga kod mene.
{77450}{77537}Naðite mog oca, molim vas.
{77561}{77643}Vas æe poslušati.|Uvijek vas je cijenio.
{77656}{77723}Vratite mi ga, molim vas.
{77957}{78038}Ovamo!|Ide pravo na nas!
{78067}{78122}Neka doðe!
{78142}{78245}I ti si se okrenuo|protiv mene, je li?
{78268}{78332}Misliš da sam star.
{78343}{78478}Misliš da sam slab,|baš kao moje kæeri!
{78524}{78620}Promašio si me!|Još uvijek sam ovdje!
{78639}{78729}Još uvijek sam u svom sedlu!|-Želite li poginuti?
{78733}{78784}Baš me briga!
{79269}{79417}Puši! Prokleti vjetre!|Puši! Ja sam ovdje!
{79439}{79521}Doði i sredi me!
{79535}{79691}Ne boj se! Ništa ti|ne stoji na putu, osim mene!
{79716}{79842}Samo ja!|Samo John Lear! Hajde!
{80660}{80708}Leare!
{80800}{80857}Netko doziva!
{80985}{81098}O, da...|Netko doziva!
{81258}{81380}Mora biti da je bila oluja.|Zrak je svjež i mirisan.
{81452}{81582}Pogledaj to nebo. Jesi li|ikad vidio tako plavo nebo?
{81763}{81810}Johne!
{82409}{82453}Johne.
{82535}{82645}Netko je dozivao?|Jesi li to bio ti? -Jesam.
{82657}{82723}Ne vjerujem da te poznajem.
{82731}{82869}Nekad sam poznavao svakog u ovoj|zemlji, ali sad ih je tako mnogo.
{82872}{82951}Ja sam Henry Westover.
{83180}{83295}Ja sam ti prijatelj.|-Hvala, prijatelju. Sjedi.
{83512}{83680}Imaš li djece?|-Dva sina, poznaješ ih. -Zaista?
{83810}{83968}I ja sam nekad imao sina,|bar mislim. Ne sjeæam se toèno.
{84056}{84282}Ali, imam kæeri. Tri.|Èovjek se može ponositi njima.
{84307}{84416}Kako te gledaju,|oèima punim ljubavi.
{84453}{84541}Isijavaju ljubav prema svom ocu.
{84609}{84777}Nema boljeg osjeæaja na svijetu,|nego kad te djeca vole, zar ne?
{84815}{84911}Ne, Johne.|Nema boljeg osjeæaja.
{85088}{85245}Zašto plaèete, gospodine?|-Hajde, odvest æu te kuæi.
{85266}{85350}O, ne.|Ne moram nigdje otiæi.
{85355}{85452}Ovo je moj dom.|Baš ovdje gdje sjedim.
{85550}{85597}Vidiš li ga?
{85753}{85787}Pogledaj.
{85791}{85949}Boga mi, gore sam s njim.|Osjeæam sve što on osjeæa.
{85979}{86066}Gledam dolje|na sve što on vidi...
{86081}{86211}Gore sam, s njim.|Plovim na vjetru.
{86246}{86333}Hajde, idemo tamo kuda on ide!
{86367}{86492}Zar ne želite vidjeti|to mjesto kuda on ide? Hajde!
{86558}{86613}Kuda je otišao?
{86632}{86724}Bože moj, kuda si otišao?|O, ne, ne...
{86821}{86920}Ne okreæi mi leða!|Vrati se!
{87307}{87346}Emmett.
{88253}{88326}G. Westover.|-Što hoæeš, Highsmith?
{88341}{88404}Želim znati gdje ste bili.
{88453}{88520}Otkud znaš da sam negdje bio?
{88603}{88654}Emmett ti je rekao?
{88824}{88897}Sad æemo vidjeti tko je budala.
{89140}{89238}Gdje si bio? S kim si|razgovarao? -Idi do vraga!
{89309}{89416}Gdje si bio i s kim si prièao?|-Gubiš vrijeme.
{89649}{89737}Moramo brzo raditi.|Okupi koliko možeš ljudi.
{89745}{89849}Naæi æemo se u mojoj kuæi.|-Kako znaš da æe me slijediti?
{89852}{89907}Platit æu im.
{89934}{90043}Ne znam što želiš od života,|ali vjerujem da želiš mnogo.
{90065}{90183}Ne težiš malim stvarima, zar ne?|-Malo me nikad nije privlaèilo.
{90231}{90322}Ali, samo to mi je ikad|bilo ponuðeno.
{90343}{90439}Ako èovjek želi nešto,|mora to uzeti.
{90915}{90972}Smithwick! Davis!
{91127}{91177}Dovucite ga ovamo!
{91375}{91425}Èvrsto ga držite.
{91430}{91489}Držite ga! Èvrsto!
{91630}{91714}Držite ga, do vraga!|-Neæu to raditi.
{91718}{91841}Vraæaj se! Smithwick,|vraæaj se! -Ne, neæu!
{91845}{91935}Vrati se i drži ga!|Do vraga... -Držim ga!
{91975}{92018}Drži ga!
{92275}{92317}Ostalo ti je jedno oko.
{92321}{92401}Ako ne želiš i to da ti spalim,|reci mi gdje...
{92525}{92625}Pucao si u mene, kuèkin sine.|-Da, gospodine, jesam.
{92879}{92971}Planiraš li se umiješati?|-Ne, gospoðo.
{93067}{93108}Draga...
{93261}{93316}Mrtav je, Rebecca.
{93367}{93446}Mrtav je!|-Goreæe u paklu!
{93835}{93890}Držite ga!
{94678}{94737}Poznaješ me, zar ne?
{94914}{95145}Jesmo li mrtvi, ti i ja?|-Nisi mrtav, tata. -Tata?
{95283}{95344}Mislim da te poznajem.
{95502}{95606}Molim te, nemoj mi se smijati.|Mislim da si moja kæer.
{95657}{95761}Claudia?|-Da, to sam ja.
{95900}{95953}Sad te vidim.
{95996}{96123}Jasno te vidim.|Mora biti da me mrziš, dijete.
{96154}{96275}Ne. Volim te.|Volim te.
{96887}{96945}Gdje sam ja?|-Senor Lear?
{97046}{97170}U redu je, tata. -Kako je u redu?|Što æu ja u njegovoj kuæi?
{97183}{97279}Pomogao je da te spasimo|i mene je štitio.
{97283}{97383}Što to govoriš?|On je neprijatelj naše obitelji.
{97387}{97492}Što se ovdje dogaða, do vraga?|-Senor, oèekujemo napad.
{97533}{97608}Napad? Tko æe napasti?
{97771}{97877}Highsmith.|I moje dvije kæeri.
{97932}{97998}Oprostite zbog smještaja,
{98007}{98119}ali ovo je najsigurnije mjesto|na hacijendi. Ostanite ovdje.
{98189}{98319}Senor, borit æu se s vama.|-Ne, ne...
{98359}{98468}Ostanite s vašom kæeri,|sad trebate biti s njom.
{99467}{99550}Završite utovar.|Moramo iæi.
{99555}{99655}Nadam se da su vam èuture pune.|Tamo je vrelije nego u paklu.
{99920}{99991}Satnik Tumlinson se treba|vratiti ovih dana.
{99995}{100056}Ne brini za mog muža.
{100064}{100171}Kad se vratiš, zajedno|æemo se pobrinuti za njega.
{100265}{100338}Muž joj nije mrtav|ni tjedan dana.
{100344}{100441}Èudno kako su neki ljudi|hladnog srca.
{100592}{100662}Momci, na konje!|Idemo!
{101233}{101330}Što mi to radimo, Susannah?|Kakve smo to postale?
{101336}{101420}Ne budi mekušac, Rebecca.|Ne sad.
{102531}{102580}Ima li nekog?
{103515}{103557}Ne!
{103601}{103661}Nemoj, tata!|-Ostavi me na miru!
{103664}{103760}Tata, ja sam! Tomas!|Polako, tata.
{104089}{104137}Thomase...
{104430}{104480}Vratio si se.
{104545}{104599}Vratio si se...
{104803}{104898}Kako sam mogao pomisliti|da si ukrao konje?
{104944}{105009}Zašto je Emmett to uèinio?
{105014}{105145}Da bi uzeo ono što je tvoje,|ali to mu više nije dovoljno.
{105187}{105239}Kako to misliš?
{105246}{105377}Znam da je on poslao Highsmitha.|Znao je što æe on uèiniti.
{105434}{105519}Ma, daj, tata, ne govori tako.|Ne želim vjerovati u to.
{105523}{105584}Bio je to Emmett, sine!
{105676}{105755}Onda æu ga ubiti.|-Ne.
{105791}{105955}Prije sam bio slijep, nisam vidio|mržnju u Emmettovom srcu. Ali, ti...
{106067}{106128}Hoæeš li mi oprostiti?
{106475}{106575}Zdravo, Enrike.|Lijepo je vidjeti te.
{106845}{106905}Zdravo, Susannah.
{107020}{107096}Vratio si se ranije.|-Da. Gdje su svi ljudi?
{107099}{107155}Vani, na pašnjaku.
{107159}{107226}Što rade? Skupljanje je|završeno, zar ne?
{107229}{107334}Bila je oluja. Stoka se razbježala|prije nego što su je uveli.
{107345}{107425}Gdje je tvoj muž?|-Ubijen je.
{107471}{107588}Ubio ga je jedan od kauboja.|Pokopali smo ga prije dva dana.
{107612}{107687}Mogu ti pokazati njegov grob,|Henry.
{107830}{107946}Želim govoriti s Learom.|-Ne znamo gdje je. Nestao je.
{107987}{108087}Zašto, onda, sjedite ovdje?|Zašto ga ne tražite?
{108264}{108395}Radi se o Menchaci?|-Zakasnio si.
{108456}{108600}Kasno je da to zaustaviš,|ali nije kasno da podijelimo uspjeh.
{108616}{108711}Ne pokušavaj nam|stati na put.
{109477}{109552}Ne boj se.|S ocem si.
{109783}{109818}Ripe!
{109944}{109996}Donesi mi pušku!
{110073}{110194}Ripe, vrati se.|Vraæaj se, proklet bio!
{110292}{110330}Što sad hoæete?
{110334}{110429}Da vam osedlam konja|pa da odjašete u neku oluju?
{110432}{110507}Ne, želim ti nešto reæi.
{110528}{110631}Hajde, recite.|Prestanite me tako gledati.
{110639}{110747}Izgledate kao da æete štrcati|krv iz oèiju kao rogata žaba.
{110765}{110825}Što imate za reæi?
{110879}{110931}Hvala ti, Ripe.
{111175}{111234}E, pa, nema drugog puta.
{111866}{111983}Mora biti da su saznali da dolazimo,|pa su pobjegli. -Jesu.
{112030}{112114}Mislio sam|da je Menchaca hrabriji.
{112201}{112276}Što èekamo?|Tamo nema nikoga.
{112355}{112430}Uzmi deset ljudi i idi unutra.
{112442}{112496}Vas desetorica!
{115468}{115519}Zasjeda!
{115825}{115898}Bacite oružje i živjet æete!
{116189}{116244}Bacite oružje!
{116261}{116311}Idi do vraga!
{116489}{116543}Raznesite kapiju, odmah!
{116860}{116911}Izgleda kao novi Alamo!
{117010}{117062}Kroz kapiju!
{117470}{117521}Otvorite kapiju!
{117930}{117980}Naprijed! Idemo!
{118422}{118479}Povlaèenje!
{119273}{119323}Gdje vam je otac?
{120350}{120427}Ne! Dosta je bilo!
{120519}{120596}Èujete li me, do vraga?|-Tata!
{120616}{120691}Prekinite!|-Tata!
{120739}{120793}Nemojte više!
{120990}{121042}Gospoðice Claudia!
{121912}{122021}Stanite!|Obustavite vatru!
{122064}{122156}Povucite se!|Prokleti bili!
{123470}{123520}Ubojice!
{123633}{123682}Claudia.
{124205}{124275}Vidite! Pero se pomièe.
{124328}{124396}Diše! Živa je!
{124467}{124523}To je samo vjetar.
{124613}{124684}Varaš se, Ripe.|Znam razliku.
{124739}{124793}Ovo je njen dah.
{124838}{124954}Živa je.|-Nije, Johne. Nije.
{125890}{125940}Pogledajte ga!
{126074}{126177}On je živ,|a Claudia nije.
{126345}{126415}Mrtva je kao ova zemlja.
{126560}{126620}Pogledajte je.
{129220}{129275}Ti si ovo uèinila.
{129367}{129426}Moralo se uèiniti.
{129516}{129572}Gdje je Emmett?
{130296}{130410}Rebecca,|pokaži malo dostojanstva.
{130481}{130597}Objesit æu te zbog ovoga|i onog što si uèinila Westoveru.
{130654}{130707}Hoæeš li?
{131051}{131101}Ne. Ostavite je.
{131476}{131525}Susannah?
{131813}{131871}Kuda æe ona?
{131957}{132044}Neka mi netko|kaže kuda ona ide!
{132141}{132222}Ne dirajte me!|Kuda me vodite?
{132225}{132305}G. Tumlinson, kuda me vode?
{133587}{133666}Jesi li èuo?|-Što to?
{133707}{133857}Puma. -Ovdje nema puma.|-Do vraga, èuo sam je.
{133911}{134048}Tamo je i èeka da legnemo,|pa da doðe i ubije nekog konja.
{134075}{134165}Neæe ubiti naše konje.|-Otkud znaš?
{134173}{134267}Zato što sam ja ovdje.|Stražarit æu, tata.
{134310}{134372}Nadam se da hoæeš.
{134462}{134525}Znam da hoæeš, Thomase.
{135476}{135540}Prijevod: vutrovana
{135573}{135649}Sa srpskog na hrvatski,|prilagodio Tantico.
{136806}{136855}K R A J
