{2017}{2087}Je li tu g. Shraft?|-Na poslu je.
{2095}{2126}Vi ste elektrièar?
{2128}{2195}Instalacija u ovoj kuæi|je zajebana.
{2197}{2257}Mogla se odavno|zapaliti.
{2265}{2365}Ako ukljuèiš prekidaè, može|proraditi tuš u kupaoni.
{2555}{2612}Završio sam.|Hoæeš pivo?
{2625}{2675}Ne, moram ovo završiti.
{2945}{2994}Nemoj ovo pogrešno|shvatiti,
{2995}{3067}dobro si to napravio,|ali ipak nisi majstor, zar ne?
{3155}{3195}Primijeæuje se?
{3240}{3320}Sranje. Moram raditi|sve što mi se pruža.
{3332}{3377}Isto i ja.
{3380}{3460}Ako nekome treba bilo što,|javljaju se Dukeu.
{3477}{3560}Tako se zoveš?|-Da. To mi je nadimak.
{3587}{3645}Prezime mi je Wayne,|pa...
{3647}{3705}Ja sam veliki èovjek.
{3710}{3782}Vojvoda Wayne,|kauboj-elektrièar.
{3790}{3850}A ti? -Sean Crawley.
{3860}{3920}Sean? Irac si?
{3927}{3989}Mislim da se moja majka|palila na Seana Conneryja.
{3990}{4037}James zajebani|Bond, ha?
{4040}{4085}Ja sam Sean zajebani Crawley.
{4092}{4169}Ovo si želio raditi?
{4170}{4250}Farbati tuðe kuæe|u bijelo?
{4270}{4332}Ne znam...|-Ne znaš?
{4357}{4405}Mlad si.
{4410}{4475}Trebao bi pratiti|svoje snove.
{4545}{4597}Nemaš snove?
{4610}{4700}Neku glupu fantaziju?|-Kao iz filmova?
{4710}{4760}Kao, biti|privatni detektiv?
{4768}{4842}Tko je spomenuo detektiva...|-Jurnjava s autima,
{4847}{4909}pucnjava, lijepe ženske...|-Ne moraš biti
{4910}{4961}detektiv da bi dobio pièku.
{4962}{5035}Pa, razgovaramo o glupim fantazijama.|-Ne toliko.
{5147}{5210}Puno ti hvala, ne znam|što bih bez tebe.
{5230}{5325}Išao bi pješice. Kada æeš|kupiti auto? -Ne znam.
{5330}{5421}Treba ti auto. -Sean, daj mi|broj, mogao bih ti se
{5422}{5492}javiti ako nešto iskrsne.|-Da, to bi bilo super.
{5527}{5567}Nemam kemijsku.
{5580}{5612}Imaš ti?
{5630}{5697}Baš ti nestalo|vizitki, ha?
{6555}{6602}Sean Crawley?
{6607}{6685}Da, tko je to?|-Vojvoda. Kako je?
{6700}{6775}Valjda dobro. -MISLIM|IMATI NEŠTO ZA TEBE.
{6890}{6970}O èemu se radi? -Šefu|treba završiti neki posliæ.
{7090}{7122}Gospodine Crawley...
{7127}{7200}Kako ste? -Ray Mathews.|Igraš golf.
{7212}{7270}Ne. -Baš šteta.
{7272}{7335}Super igra.|A sada, gubi se.
{7380}{7442}Ne, samo æu gledati.
{7445}{7520}Što prièaš? Na igralištu|si za golf, ili igraš ili...
{7565}{7630}Dobar udarac.|Uzmi torbu.
{7680}{7742}Opisao si svoju filozofiju|života kao...
{7745}{7820}"Prvo, èuvaj se". -Glupo bi|bilo da se ne èuvaš.
{7822}{7840}Eto ti.
{7847}{7901}U ovo naše vrijeme,|moraš sve napraviti
{7902}{7955}onako kako treba?|-Tako je.
{7960}{8022}A usput... Malo da|se izmakneš pravilima?
{8075}{8145}Mislim da znam o èemu|prièate.
{8150}{8217}Prièam o tome što je|dobro, a što loše.
{8222}{8310}Ne sugeriram da treba|napraviti nešto nezakonito,
{8322}{8377}ali, znaš...
{8382}{8445}Ako se umiješaš|u nešto što je
{8467}{8530}antidruštveno...|Vojvodo, kako se kaže?
{8557}{8597}Nemoralno?
{8637}{8672}Baš tako.
{8687}{8735}Nemoralno.
{8782}{8827}Pa...
{8836}{8935}Kako bi se ti osjeæao|u vezi
{8947}{9005}nemoralnih stvari?
{9045}{9110}Mislim da to ovisi|o nama samima.
{9222}{9287}Lijepo složeno.|-Jako lijepo.
{9345}{9427}Što toèno želite napraviti?|-Trebaš motriti nekoga.
{9447}{9535}Zove se Eric Gatley,|raèunovoða je u opæini.
{9537}{9637}Hoæete da ga pratim?|-Non-stop.
{9670}{9752}OK? Hoæu da ga motriš|i unutra i vani.
{9802}{9862}Ako ode pišati,
{9887}{9937}hoæu znati koje mu je|boje mokraæa.
{10745}{10790}Sranje!
{15207}{15277}Baš ti hvala. Sljedeæi|tjedan sam ja na redu.
{15332}{15405}Bok. Vežite pojaseve.|-Bok.
{15710}{15777}Idi, spasi svijet.|-Bok.
{15807}{15842}Bok.
{15977}{16017}Oprostite...
{16250}{16302}Bok, Susan. -Bok, Tony.
{16307}{16347}Dobri ste danas?
{16355}{16432}Fino. Vidimo se|unutra.
{17007}{17062}Gðica Park?|-Da, bok.
{17065}{17137}Bok, kako ste?|Eric Gatley.
{17155}{17220}Hvala vam što ste|našli vremena.
{17225}{17272}Hvala vama što ste se|javili.
{17275}{17340}Razumijete da vam ne mogu|ostaviti ništa
{17345}{17376}od ovih materijala,|samo æu vam objasniti
{17377}{17447}o èemu se radi.|-Razumijem. Vidjeti...
{17452}{17522}Ovo je original...
{17547}{17606}Sreo se s Kineskinjom|sa vijesti.
{17607}{17697}Siguran si? -Da, pokazao|joj je dokumente.
{17805}{17825}Isuse... jebeni|Kriste...
{17840}{17886}Dobro, reæi æu Mathewsu.
{17887}{17939}Ti produži, u redu?
{17940}{17997}Sada je najvažnije.
{18062}{18140}Sean, nisi tako loš.|-Hvala.
{18147}{18225}Ne moraš biti profesionalac|da bi dobro obavio posao.
{18727}{18767}Hej, Crawley...
{18777}{18832}Baš ti je neki|ovaj iz tvog susjedstva.
{18842}{18916}Imaš li pojima koliko|te veæ èekam?
{18962}{19015}Ovoliko dugo.
{19105}{19170}Što si zinuo,|upadaj.
{19517}{19570}Znaš, ti si...
{19575}{19632}Jako si dobar.
{19665}{19717}Jesam li završio|posao?
{19792}{19840}Isprièat æu ti jednu|prièu.
{19877}{19972}Bila jednom jedna|djevojka, Samantha.
{19992}{20077}Bila mi je tajnica.
{20165}{20220}Imala je 18 godina,
{20240}{20332}ali je izgledala kao|da ima 30, kužiš?
{20452}{20552}Do ušiju sam bio zaljubljen|u nju. Kao glupan.
{20582}{20650}Kao tinejdžerska|pièkica.
{20697}{20767}Mogao sam sve|napraviti za nju.
{20775}{20842}Ali to nije bilo lako,
{20852}{20945}ona je živjela s obitelji,|a ja sam bio...
{20965}{21040}jebote, bio sam oženjen.
{21052}{21152}Jedan tip s posla|imao je stan u blizini.
{21170}{21270}Tražio sam ga kljuèeve|da bih šmugnuo sa Samantom.
{21335}{21427}Prvi put sam je odveo|tamo, i da ti kažem,
{21432}{21487}oèajnièki sam htio|tu pièku.
{21520}{21582}Ušli smo unutra, a tip je|èuvao jebeno malo pseto.
{21585}{21636}Odmah ga je zgrabila,|a ja sam joj rekao...
{21637}{21720}"Ostavi psa, hajde...|dolazi u spavaæu sobu".
{21757}{21857}Htio sam je usmjeriti|kuda hoæu iæi. 
{21897}{21957}Pas je poèeo grebati|po vrata...
{21987}{22087}Ona ga pogleda, nasmije se...|Više je obraæala pažnju
{22092}{22160}na jebeno pseto nego|na mene.
{22165}{22245}Izašao sam i bacio psa|na drugu stranu sobe.
{22287}{22387}Vratio sam se natrag, i odmah|nakon toga je otkopèala bluzu.
{22392}{22492}Bila je sva prekrasna|sa obrijanom pièkicom.
{22537}{22637}A jebeno pseto je opet|zagrebalo na vrata.
{22642}{22735}Ona pogleda u njega,|izgubi koncentraciju,
{22745}{22802}više nije bila u filmu,|kužiš?
{22835}{22930}"Oprosti, Sam", otišao sam do|jebenih vrata,
{22937}{22982}zgrabio jebeno|pseto
{22996}{23065}i slomio mu vrat|kao granèicu.
{23112}{23210}Poslije sam ga bacio|u kantu za prljavo rublje.
{23225}{23277}Vratio sam se u sobu
{23282}{23355}i ispostavilo se da se mala|Sam jebe kao zeèica.
{23375}{23457}Poanta je da...
{23492}{23590}ponekad moraš biti|malo okrutan.
{23617}{23705}Ako ti se nešto isprijeèi|na putu, ne èekaj ni trenutka.
{23745}{23787}Kužiš?
{23805}{23882}Samo je pitanje,
{23920}{23982}koliko daleko želiš|iæi.
{24082}{24155}Misliš, da se oslobodiš|od lajavog pseta?
{24260}{24310}Mislim...
{24337}{24392}Moraju biti odgovarajuæi|uvjeti.
{24430}{24512}A kakvi mogu biti?
{24620}{24672}Dobro...
{24720}{24755}Pod jedan...
{24767}{24856}Ne smije postojati naèin|da budeš uhvaæen
{24857}{24922}ili postaneš|sumnjiv. -To je talent.
{24947}{24982}Da...
{24990}{25080}I moraš biti|fizièki siguran,
{25087}{25187}ne smije me ugroziti|žrtva ili netko drugi u blizini,
{25202}{25302}moram biti u|superiornoj poziciji.
{25337}{25432}Misliš, jaèi? -Da,|ili imati bolje oružje,
{25445}{25487}iznenaðenje ili|bilo što.
{25512}{25552}Ima smisla.
{25585}{25625}Èetiri...
{25630}{25704}Èekaj. Došli smo|do tri.
{25705}{25777}Samo što sam to rekao.|-A što je bilo?
{25842}{25915}Nije važno. Dobro, onda|neka bude pod tri,
{25927}{25995}a ustvari je dio|dvojke.
{26045}{26115}Moraš biti 100% siguran|da æeš se izvuæi.
{26117}{26180}Pa, upucaj prokletog|tipa. -Ne,
{26185}{26262}da se vratim na poantu|broj...
{26297}{26347}Poanta za sigurnost.
{26350}{26410}Mora se koristiti oružje|koje ne ostavlja trag.
{26442}{26492}Dobro razmišljanje.
{26627}{26689}Do kojeg broja sam stigao?|-Tko to zna? Izgubio si se
{26690}{26745}na tri. -Nije važno.
{26770}{26837}Onda, pet.|Toèka pet.
{26887}{26980}Razlog. Treba mi razlog|zašto da to napravim.
{26982}{27030}Kao?
{27072}{27142}Kao što je...|Nagrada.
{27185}{27247}Nagrada?
{27265}{27365}Da, treba postojati dovoljno|velika nagrada
{27372}{27410}da bi se to uèinilo.
{27432}{27490}Pet tisuæa.
{27537}{27590}Zvuèi kao ništa.
{27632}{27700}15 je bolje.
{27775}{27820}Deset.
{28235}{28302}13.
{28327}{28387}13 tisuæa.
{28590}{28652}To je moj sretan|broj.
{29190}{29235}Oprosti.
{31015}{31060}Ne odgovaraj|na vrata.
{31072}{31155}Ne odgovoraj na zvono,|ne budi glupa žena.
{31275}{31352}Bok, g. Gatley.|Da li je Susan kod kuæe?
{31380}{31445}Ne...
{31447}{31512}Odvela je našu kæerku|na balet.
{31525}{31602}Mislio sam da æe biti|tu u subotu.
{31620}{31682}Da, znam. Žao mi je.
{31687}{31770}Ja sam iz misije za beskuænike...|Mogu li joj ostaviti poruku?
{31776}{31820}Svakako.
{31850}{31915}Nemam papir.
{32007}{32080}Da, èekaj, oprosti,|bio sam u vrtu...
{32115}{32152}Hvala.
{32455}{32532}Vidjeti...
{32542}{32582}Papir...
{32627}{32685}Ovdje je nered...
{33285}{33385}Znaš, to je vrijedno|na neki naèin,
{33392}{33465}bolje da ga nisi|uzimao. Hvala.
{33625}{33667}Što radiš?
{35535}{35600}Tiho, èovjeèe...
{35625}{35672}Ne brini.
{35830}{35890}Lezi dolje.
{36127}{36167}Gdje ti je šešir?
{37255}{37315}Bok, g. Gatli,
{37325}{37390}javit æu se tokom tjedna.
{37782}{37882}Glupi šupku!|-Oprosti!
{40237}{40285}Hajde, Duke,
{40287}{40360}zajebani debeljko,|javi se na telefon!
{40380}{40432}Javi se na jebeni|telefon!
{40452}{40519}SUPRUGA ERICA GATLEYA,|SUSAN, NE ZNA
{40520}{40561}ZAŠTO JE NJEN|SUPRUG UBIJEN.
{40562}{40614}POLICIJA NEMA NOVIH|TRAGOVA ZA OVAJ SLUÈAJ,
{40615}{40715}ALI MOGU EKSKLUZIVNO|OBJAVITI DA SAM
{40722}{40764}RAZGOVARALA S ERICOM|NEKOLIKO DANA
{40765}{40817}PRIJE NEGO ŠTO JE UBIJEN.|ERIC GATLEY
{40822}{40887}JE ISTRAŽIVAO KORUPCIJU|U VIJEÆNICI...
{40890}{40947}Netko takav zaslužuje|umrijeti.
{40950}{41010}ISTRAŽIVAO JE|AKTIVNOSTI OVOG ÈOVJEKA,
{41015}{41095}LOKALNOG PODUZETNIKA,|RAYA MATHEWSA.
{41107}{41180}Sean, ti si na redu.
{41185}{41232}Da...
{41305}{41400}Oprosti, moram iæi.|-Što?
{41407}{41485}Duguješ mi revanš!
{41727}{41790}Sean...|-Duke! Pobogu!
{41800}{41850}UMUKNI I SLUŠAJ.
{41852}{41919}SUTRA UJUTRO, RAVNO|U ZOOLOŠKI VRT.
{41920}{41979}TREBAM O NEÈEMU PRIÈATI|S TOBOM. -Sa mnom?
{41980}{42030}Ti prièati|sa mnom?
{42470}{42540}Što se dogaða?|Što tražimo u zoološkom?
{42547}{42625}Poznaješ li nekoga tko ide|u zoološki vrt? -Ne.
{42630}{42716}Ni ja. Znaèi, nema nas|tko prepoznati.
{42717}{42745}Osim toga...
{42747}{42825}Volim ljubimce, dobri su.
{42835}{42895}Imaš li lovu?|-Kakvu jebenu lovu?
{42920}{42976}Mathews mi duguje.
{42977}{43025}Hajde, jebo te.
{43037}{43120}Znaš što ljudi rade kada idu|u zoološki? -Što?
{43122}{43217}Pokušavaju otkriti na koje|životinje slièe njihovi prijatelji.
{43252}{43324}Da li si igrao ovu igru prije?|Obièno se igra s majmunima,
{43325}{43390}ali mi to možemo|i bolje.
{43392}{43492}Ne nešto oèigledno,|kao, reæi da slièim na slona,
{43500}{43565}veæ moraš|upotrijebiti maštu.
{43585}{43675}Ali za tebe... Moramo|otiæi kod reptila.
{43752}{43847}Da, u tebi ima neèeg|gušterskog.
{43850}{43950}Ljigavo, oprezno...
{43975}{44045}Malo kamuflaže...|-Što se zajebavaš?
{44097}{44175}Što je toliko smiješno?|-Ti si živi urnebes.
{44187}{44249}Misliš da si veliki|detektiv?
{44250}{44334}Misliš da si sve protumaèio,|ali si za žaljenje.
{44335}{44402}Znaš li uopæe zašto|se krijemo? -Ne znam,
{44410}{44485}valjda, ako se nešto dogodi,|da me ne bi povezali s tobom.
{44487}{44547}Stvarno? I...?
{44552}{44620}I valjda zato što|sam jako dobar. -Ti?!
{44622}{44722}Misliš da dobro pratiš?|Da dobro tumaèiš stvari?
{44727}{44822}Ti si detektiv toliko koliko sam|ja balerina.
{44835}{44910}Nemaš èak ni auto.
{44915}{45002}Beskoristan si, zato smo te|i unajmili.
{45025}{45090}Zašto?
{45092}{45170}Htjeli smo se|riješiti tipa,
{45175}{45267}predugo njuška okolo|i mogli smo najebati.
{45270}{45345}Zato sam mislio da|pratiš tipa,
{45350}{45450}i kada te vidi, da se|uplaši
{45470}{45530}i da se makne,|a da ga ne pipnemo.
{45540}{45627}A ti si ga ubio.|-To je bio tvoj plan.
{45637}{45687}Znaèi, sada je to|bio moj plan...
{45690}{45757}Baš genijalna ideja.
{45827}{45912}Možeš biti siguran|samo ako išèezneš.
{45917}{45981}Obavio sam posao|i hoæu da me isplatite. -Što?!
{45982}{46055}Tko bi tebi uopæe dao|13 tisuæa za bilo što?
{46070}{46121}Ali ja sam to uèinio,|i tražim svoj novac,
{46122}{46157}i ne odlazim dok|ga ne dobijem.
{46160}{46215}Ako ti je to|teško...
{46265}{46360}Ti si bezvrijedno|govno.
{46385}{46445}Neæeš ti meni reæi|što da radim.
{46467}{46562}Neæeš dobiti ni centa|i ima da te nema. Kužiš?
{46568}{46625}Ne želim te više nikada|vidjeti.
{46627}{46670}A ako te vidim...
{46680}{46780}Ubit æu te,
{46805}{46905}i to tako da nema nièega|što bi te povezalo s nama.
{46932}{46990}Zato, odlazi.
{47070}{47117}Mislim da sam te|našao.
{47137}{47202}Da, evo si!
{47205}{47280}Sean, vidi, našao sam te!
{47288}{47365}Eno te, ti si insekt,|jebeni mrav!
{47385}{47445}Vidi, pljunuti ti!
{47710}{47745}Hvala.
{48037}{48125}Zvuèao si jako nervozno|na telefonu. -Da, znam.
{48192}{48250}Što ima?
{48277}{48362}Sjeæaš li se tipa o kojem sam|ti prièao? -Što, neæe ti platiti?
{48435}{48535}Postaje strašno, prijete mi|da se izgubim iz grada. 
{48547}{48612}Da sam na tvom mjestu,|poslušao bih ih.
{48617}{48657}Duguju mi.
{48667}{48745}Djeluju mi ozbiljno.
{48752}{48809}Uèini što traže i napusti|grad. Ionako te ništa
{48810}{48845}ne drži ovdje.
{48905}{48965}Neæu iæi.
{49015}{49082}Uèini nešto za mene.|-Što to?
{49160}{49210}Èuvaj mi ovo.
{49242}{49310}Ne bih rekao...|-Ovo su samo ugovori.
{49312}{49385}Samo èuvaj mi to.
{49387}{49460}Ne znam... -Tebe ne poznaju.
{49487}{49547}Èuvaj ovo na sigurnom.
{49712}{49765}Sranje...|-Kuda æeš?! Hej!
{49797}{49877}Vrati se!
{49970}{50005}Bok, George!
{50512}{50550}Sranje!
{50660}{50727}Povrijedit æeš ga.|-Vozi, Carl.
{50735}{50800}Koji kurac hoæeš?|-Rekao sam ti,
{50800}{50857}hoæu da odmagliš.|Zašto si još tu?
{50876}{50942}Imam nešto za tebe.|-Što je to?
{50945}{51024}Karta za vlak do Chicaga.|Na stanici æe te èekati
{51025}{51070}jedan tip i dat æe ti|lovu.
{51077}{51105}Do Chicaga?
{51107}{51149}Hoæemo da se izgubiš|odavde.
{51150}{51186}Odakle da znam da æe|tip biti tamo?
{51187}{51222}Kako ti mogu|vjerovati?
{51225}{51280}Nemaš izbora.
{51540}{51615}Zbogom.|-Imam dokumente.
{51632}{51696}Imam njegove dokumente.|Sve dokaze koje je prikupio
{51697}{51757}protiv Mathewsa,|ja ih imam.
{51860}{51927}Da, sada je sve|drugaèije.
{51930}{51981}Tamo su i moje|bilješke.
{51982}{52042}U stvari, mislim da i tebe|spominje par puta.
{52045}{52125}Što piše?|-Hajde, Duke,
{52127}{52185}nisi li gledao dovoljno|filmova?
{52187}{52255}Ako mi se nešto dogodi,|pojavit æe se u javnosti.
{52317}{52365}Gdje su dokumenti?
{52425}{52499}Zaboraviti na Chicago,
{52500}{52557}obojica znamo da tamo|nema nikakvog tipa.
{52567}{52630}Vrati me natrag|u grad.
{52735}{52792}Lezi dolje!|-Što je bilo?
{52796}{52837}Daj mi jebeni|telefon.
{52882}{52925}Ima Gatleyeve|dokumente.
{52927}{53027}Kaži Mathewsu da pošalje nekoga|u njegov stan, da ga pretrese.
{53160}{53216}Gdje su dokumenti?
{53217}{53307}Što ako ti ne kažem?|Ubit æeš me?
{53330}{53370}Ne bih rekao.
{53477}{53550}Pa, sada æeš me tuæi?|-Gdje su dokumenti?
{53582}{53625}Usta su mi|zapeèaæena.
{53635}{53735}Možeš me tuèi kada|hoæeš. -To bi volio?
{53752}{53847}Uèini to, odmah sada,|meni je svejedno.
{53857}{53901}Nije te briga ako te|prebijem?
{53902}{53945}Još æu biti živ.
{53950}{53996}Ništa me ne|plaši.
{54015}{54094}Možeš me tuæi|preko cijele godine,
{54095}{54162}a na kraju, ja æu još uvijek|biti živ.
{54177}{54240}A ti još uvijek neæeš znati|gdje su dokumenti.
{54267}{54315}Zato, vidiš...
{54325}{54405}Osim ako me ne ubiješ,|meni je svejedno.
{54427}{54492}A ako ti odrežem|muda?
{54545}{54612}Pa, valjda æu se|naviknuti i na to.
{54620}{54667}Znat æeš.
{54710}{54795}Što kaže? -Da ga odvedemo|u pustinju.
{54850}{54905}Na njegov ranè? -Hej,|ako tako kaže...
{54910}{54956}Daj neku glazbu,
{54965}{55025}ovo æe biti|dug dan.
{57135}{57212}Što æete mi raditi?|-Neæeš muda, ha?
{57312}{57362}Vidimo se kasnije!
{59622}{59689}G. Crawley, jesi li|lijepo spavao?
{59690}{59752}Kako ti se sviða u hotelu?
{59757}{59830}Piša mi se.|-Malo kasnije.
{59842}{59880}Sjedni.
{59952}{60027}Vani je predivan dan.|Kada je takav dan,
{60067}{60132}ja bih trebao|igrati golf.
{60152}{60220}Golf je super igra.
{60232}{60280}Pomaže ti da|razmišljaš.
{60340}{60410}Tako je?|-Da, tako je.
{60452}{60497}Zaveži ga.
{60555}{60621}Duke je vrlo uèinkovit|sa èvorovima. Zar ne?
{60622}{60680}Nekad sam bio|izviðaè.
{60780}{60830}Gdje su dokumenti?
{60832}{60932}Neæu ti reæi.|-Želio bih da te nema,
{60957}{61012}da te nema na licu|zemlje.
{61027}{61102}Ali ti si me unajmio,|uèinio sam što si mi rekao.
{61110}{61167}Što prièaš?|Bio sam pijan!
{61187}{61245}Nisi me trebao|slušati.
{61250}{61315}Ovo je ludilo.|-Da, prièaj mi o tome.
{61340}{61440}Napravio si mi problem,|policija mi je vrlo blizu.
{61447}{61520}Ja sam zadnji koji bi te|predao policiji.
{61525}{61580}Prije ili kasnije, doæi æe|i do tebe.
{61627}{61665}Ali ako tebe nema|u blizini,
{61667}{61715}ne mogu ništa|dokazati.
{61730}{61796}Zar ne bi bilo još|kompliciranije
{61797}{61872}ako me ubiješ?|Ako umrem...
{61892}{61967}Èekaj... tko je spomenuo|ubijanje?
{62032}{62090}Nikoga nema da te ubije.
{62092}{62177}U ovoj sobi si samo ti|ubojica, moje ruke su èiste
{62185}{62237}i želim da tako i|ostane.
{62252}{62340}Daj mu malo za|popiti.
{62507}{62562}Zatvori mu nos,|kretenèino.
{62695}{62737}Još...
{62820}{62855}Prljava životinjo!
{62890}{62947}Donesi vodu|i poèisti.
{63102}{63165}Moraš biti|pažljiv s viskijem.
{63175}{63240}Može da ti sjebati|mozak.
{63245}{63320}Prvo sam stvarno želio|da nestaneš.
{63380}{63469}Onda mi je palo na|pamet, treba ubiti tipa,
{63470}{63510}pa da nestane.
{63742}{63792}Da ti isprièam|prièicu.
{63805}{63872}Jednom je radio jedan|tip za mene, Dino Scarbor.
{63875}{63940}Sjeæaš li se Dina, Duke?|-Da, siroto kopile.
{63952}{64020}Bio je faca, zgodan,|moderan,
{64030}{64092}obarao je žene s nogu. Bilo je|uživanje da ga imaš u blizini.
{64095}{64162}Izvadio je kurac pred|opaticom, zar ne?
{64205}{64275}I tako, odveo sam ga|na svoje gradilište.
{64282}{64364}Sa jedne dizalice pao je|ogromni betonski blok
{64365}{64415}i zakvaèio mu sa strane|glavu.
{64422}{64490}Nije ga ubio, ali, vjeruj,|želio bi da je.
{64507}{64575}Više ga nismo zvali Dino.|-Zvali smo ga Dumbo.
{64592}{64657}Tip je postao biljka,|nismo ga razumjeli ni rijeè.
{64665}{64710}A nije ni on.
{64712}{64812}Samo je sjedio i zurio|u zid...
{64847}{64890}Za sažaljenje.
{64985}{65060}Najstrašnije je to
{65062}{65142}što je uèinio taj|jedan betonski blok.
{65150}{65190}Stvarno strašno.
{65405}{65480}Mislim da sam ponio|pogrešan štap.
{65507}{65585}Hajde, Mathews,|valjda ne misliš ozbiljno?
{65707}{65747}Znaš...
{65750}{65827}Možda si ga sakrio negdje|daleko, a možda i ne.
{65835}{65925}Ali ovako æu te natjerati|da zaboraviš gdje je.
{65962}{66037}Mogu te natjerati|da sve zaboraviš.
{66182}{66255}Ovo je nešto najgluplje|što sam èuo.
{66257}{66357}Tko æe obraæati pažnju na|izgubljeni sluèaj poput tebe?
{66362}{66425}Ne možeš tek tako nekoga|uèiniti biljkom.
{66430}{66475}Ne?
{66507}{66552}Reci to Dumbu.
{66597}{66650}Carl, ne želim|ostaviti dojam,
{66655}{66720}raskomadaj jastuk i zamotaj mu|glavu s njim.
{66837}{66932}Mathews... -Vani je|Sean Crawley,
{66975}{67075}a iznutra Dumbo Dino.
{67102}{67145}Biti æe zabavno.
{67348}{67435}Opalit æu te toèno ovdje.
{67440}{67482}Spreman, Carl?
{67512}{67542}Dobro...
{67577}{67625}Maknite se, deèki.
{67687}{67720}Spreman?
{67777}{67817}Baš ovdje...
{68167}{68230}Dolazi k sebi.
{68237}{68275}Što misliš?
{68347}{68407}Kako si?
{68415}{68452}Ne izgleda dobro.
{68495}{68577}Izgledaš skroz|prejebano.
{68665}{68695}Napij se.
{69597}{69630}Hvatajte ga.
{69752}{69822}Veži ga!|-Ne!
{70195}{70242}Hajde, pij!
{70342}{70410}Molim vas, nemojte...
{70537}{70610}Molim vas... -Gdje su|dokumenti?
{70945}{70987}Susan...
{71382}{71440}Puši kurac, ubojico...
{71467}{71522}Umukni! -Ubojico!
{71767}{71842}I to je glazba? -Da!|-Nema nikakve melodije,
{71847}{71887}samo lupanje.
{71890}{71962}A ti glazbom zoveš|Michaela Boltona? Stinga?
{71970}{72047}Znaš što je muzika?|Johnny Cash.
{72210}{72302}Von. -Koji Von?
{72335}{72407}Nemaš pojma o glazbi.
{72440}{72500}Isuse, smrdiš.
{73652}{73702}Bolestan si?
{73922}{73995}Što radiš, jebote?|-Bolestan je.
{74022}{74080}Ima temperaturu.|-Pa što?
{74122}{74215}Umrijet æe u onoj rupi.|-Bar æemo onda svi kuæi.
{74402}{74447}Sean...
{74455}{74547}Jako sam gladna...
{74552}{74630}Nahrani me...
{74852}{74930}Još uvijek sam gladna...
{75025}{75100}Oprosti!
{75247}{75317}Ja sam na redu!|-Ne seri!
{75320}{75395}Ti si ga tukao juèer.|Hajde, daj mi štap!
{75397}{75462}Nikako! Stalno ga ti|moraš tuæi!
{76657}{76700}Zajebi to!
{76715}{76770}Glumiš?
{76785}{76834}Da li glumiš?
{76835}{76917}Hajde, meni možeš reæi.
{77000}{77037}Idemo.
{77320}{77375}Sjedni.
{77682}{77737}Hajde, pij.
{77770}{77815}Tako je...
{77970}{78048}Vidi ih... da sam|loš kao ti,
{78102}{78187}probao bih ih|srediti.
{78190}{78240}Zajeban posao...
{78300}{78382}Sean, evo grana.|Raport, deèko.
{78400}{78457}Imao sam psa kojem sam|govorio što da radi.
{78460}{78509}Kurac, imao sam i|zlatnu ribicu
{78510}{78580}koja je bila pametnija|od njega. Pseæa hrana.
{78605}{78705}Isuse, Carl!
{78768}{78812}Što je sad?
{78852}{78910}Što radi?|Èovjeèe!
{78937}{78987}Prestani, zaboga!
{78992}{79057}Donesi prvu pomoæ.|-Porezao me!
{79070}{79130}Donesi je odmah!|-Daj, donesi ti.
{79212}{79305}Da ga ostavimo na miru.|-Usrani posao...
{79362}{79405}Ne znam, g. Mathews.
{79410}{79465}Izgleda kao da je|bolestan.
{79485}{79567}Da, kao lud.
{79652}{79711}Jednostavno ne znam.
{79712}{79777}Jebi ga, nema piva.
{79812}{79865}Vidjet æemo se.
{79955}{80007}Nema piva.
{80045}{80095}Dolazi Mathews.
{80147}{80185}Sranje.
{80965}{81065}Èovjeèe, dobro je što sam|izašao. Tamo je ludinica.
{81092}{81137}Da.
{83167}{83210}Isuse!|-Pazi!
{83520}{83615}Požuri, Beckett!|-Dolazim!
{83710}{83755}Ubit æu vas!
{83787}{83835}Što je ovo, jebote?!
{83840}{83905}Izašao je van!|-Isuse...
{83910}{83962}Zgrabi ga!
{84105}{84152}Sranje!
{84467}{84555}Sean, brzo! Upadaj unutra!|Ja sam, George!
{84562}{84627}Ulazi u kombi!
{84680}{84730}Mrtav si, jebem ti|majku!
{84735}{84810}Vrati se ovamo!
{85080}{85127}Jebote!
{85662}{85747}Sean, što se dogaða?|Pregledao sam ovo.
{85907}{85957}Kako si me našao?
{85960}{86022}Pratio sam Mathewsa,
{86025}{86107}tumaèio sam dokumente,|pratio ga do ranèa...
{86200}{86255}Jako sam sretan|što te gledam.
{86305}{86342}Zbunjen sam.
{86345}{86422}Da su psi,|razumio bih, ali ljudi?
{86442}{86522}Nije važno.
{86605}{86645}Tamo...
{86707}{86760}Shvatio sam svoju|ulogu,
{86775}{86850}konaèno znam što želim|postati.
{86865}{86902}Što?
{86905}{86970}Istrebljivaè.
{87190}{87267}Koji kurac?! Jebi se!|Ovo nije šala!
{87292}{87392}Ubio si tipa!|-Dvojicu. -Zašto?
{87422}{87497}Pomozi mi da to razumijem,|zašto Gatley?
{87522}{87555}Zašto?
{87570}{87632}Ne znam, jednostavno|se dogodilo.
{87650}{87695}Nosio je šešir.
{87705}{87785}Igledao je jako glupo|s tim šeširom.
{87805}{87865}Ubio si ga zbog|šešira?
{87910}{87960}Ubio sam ga jer sam|želio.
{87975}{88040}Jebote!
{88052}{88126}Riskirao sam život zbog|tebe, a ti mi prièaš
{88128}{88210}za jebene mrave? Koji ti je|kurac? Zvuèiš nenormalno.
{88212}{88312}Još sam isti tip|kao i prije.
{88335}{88390}Izlazi iz kombija.|-George...
{88395}{88440}Odjebi van.
{88442}{88500}George...|-Odjebi!
{88507}{88552}George, nemoj...
{89600}{89665}Sjedni, mladiæu...
{91052}{91107}Bože... Što ti se|dogodilo?
{91137}{91212}Policija. -Oni su ti|ovo napravili?
{91225}{91280}Ne daj da me|odvedu.
{91285}{91340}Moramo te odvesti|u bolnicu. -Ne!
{91355}{91422}Nemojte u bolnicu,|tamo ima policije.
{91465}{91542}Treba ti pomoæ. Gary?|-Znao sam da æeš doæi.
{91737}{91790}Da ga stavimo|ovdje.
{91922}{91970}Polako...
{92005}{92050}Polako.
{92117}{92172}Donijet æu neku odjeæu.
{92282}{92340}Kako se zoveš?
{92357}{92405}James Bond.
{92430}{92520}James Bond?|-James Todd.
{92542}{92620}Jamese, daj mi to.|-Ne!
{92640}{92709}Dobro, zadrži to,|samo ga makni na stranu,
{92710}{92757}trebam te pregledati.
{92852}{92922}Reci mi gdje|te boli.
{93047}{93095}U redu je.
{93567}{93620}Prekini!
{93642}{93705}u redu je, ovdje sam.|Pogledaj me,
{93717}{93772}ovdje sam.|U redu je.
{93815}{93870}Oprosti... -Vratite se|na spavanje.
{93872}{93942}Oprosti...|-U redu je.
{93962}{94007}Košmar, ha?
{94116}{94207}Znam kako izgleda.
{94327}{94367}Prièaj mi o tome.
{94405}{94442}Što?
{94492}{94550}Što se dogodilo s tobom?
{94702}{94775}Moj muž, Eric,
{94795}{94845}nedavno je ubijen.
{94927}{94988}Što se dogodilo?
{95147}{95245}Bio je raèunovoða|u opæini...
{95317}{95397}obavljao je istragu za|graðevinske firme,
{95400}{95485}mislim da se nekoj firmi nije|svidjelo to što je otkrio
{95545}{95602}i da su ga zato|ubili.
{95717}{95794}Preživio si. Ne mogu te|prepoznati kakav si bio
{95796}{95852}kada smo te donijeli, prije|tri tjedna.
{95930}{95980}Ne bih uspio da nije|bilo tebe.
{96002}{96067}Pa, i meni je bilo|dobro.
{96070}{96127}To što sam imala|šanse da...
{96167}{96240}Dobro ti je?|-Da, samo...
{96257}{96337}Strašno me boli glava.|U redu je, proæi æe.
{96380}{96428}Bol uvijek prolazi.
{96500}{96600}Neæeš moæi ostati u|skloništu još dugo.
{96620}{96707}To je bio samo|privremeni smještaj.
{96740}{96797}Treba nam krevet,|pa...
{96817}{96912}Imaš gdje otiæi, ili|æeš se vratiti na ulicu?
{96930}{96987}Ne, imam gdje|otiæi.
{97960}{98037}Ne možemo ostati|ovdje.
{98072}{98167}Ali ne znaš ništa o njemu,|to je apsurdno.
{98407}{98480}Kuda æeš? James?
{98530}{98597}Bit æe u redu.|-Èuvaj se.
{98642}{98697}Maèe, kuda æeš?|-Vidimo se sutra.
{99137}{99172}To je to.
{99612}{99697}Ovdje jedemo i...
{99812}{99872}Pokazat æu ti|spavaæe sobe.
{100345}{100420}Ovo æe biti tvoja soba|dok si ovdje.
{100455}{100537}Ovo je Caitlin,|raskomoti se.
{100802}{100847}Najbolja si, Moe.
{101160}{101225}Caitlin, ovo je James|o kojem sam ti prièala.
{101265}{101359}Bok, James. -Hvala ti|što si mi dozvolila da boravim
{101360}{101422}u tvojoj kuæi.|-U redu je.
{101442}{101510}Ljudi ne bi trebali|biti sami.
{101512}{101612}Polude i poènu raditi|glupe stvari.
{101662}{101735}Zaboravljaju kako živi|ostali svijet.
{101752}{101797}To nije zdravo.
{101815}{101875}Ne znam što govorim,|samo...
{101887}{101985}To što sam u ovoj|sobi, gdje...
{102017}{102085}Podsjeæa me na|puno stvari.
{102135}{102227}Imaš novi frižider.|-Što?
{102360}{102397}Mislim, nije se mogao|zalediti?
{102487}{102550}Ne, od njega sam se morala|osloboditi.
{102582}{102632}Morala sam se osloboditi|od puno stvari.
{102682}{102720}Oprosti.
{102810}{102870}Bok, Gary.
{102872}{102917}Da, sve je|u redu.
{102940}{103015}Sutra? Valjda.
{103040}{103132}Da, samo mi treba adresa.|Èekaj da uzmeš papir.
{103495}{103545}Dobro, laku noæ.
{103622}{103677}Jako si uèinkovit.
{103690}{103757}Ja nisam imala pojma|da je tamo papir.
{103920}{103975}Za nas oboje.
{103992}{104052}Tamo sam mislio da æu|umrijeti. -Mama,
{104057}{104100}probudila sam se.
{104160}{104197}Zlato...
{104205}{104242}Hoæeš li prièu?
{104362}{104402}Pazi...
{104452}{104535}Koristit æe ti?|Ericova je.
{104560}{104622}Bila je Ericova.|-Ne!
{104845}{104902}U redu si?|-Da.
{104945}{105005}Pobijedila sam, mama!
{105080}{105150}Sigurno imaš sve?|-Ne brini, mama.
{105152}{105220}Javit æeš mi se, zar ne?|-Da.
{105292}{105370}Bok svima.|Toèno na vrijeme.
{105447}{105495}Bok, djevojke.
{105540}{105587}Provedite se lijepo|za vikend.
{105607}{105707}Bit æeš ovdje kada se vratim,|zar ne? -Da, da.
{105752}{105805}Hvala, Maureen.
{105807}{105862}Budi pristojna.
{106245}{106307}Ali, ne možeš se|osjeæati krivom.
{106320}{106420}Nema svrhe da se|tako osjeæaš.
{106450}{106495}Dogodilo se.
{106502}{106555}Jednostavno se dogodilo.
{106585}{106675}Negdje vani su ljudi|koji su krivi.
{106710}{106757}Ali bit æe kažnjeni.
{106872}{106972}Moraš produžiti|dalje.
{106992}{107040}Znam.
{107087}{107187}Razgovaram s tobom|o svemu...
{107400}{107470}Mi smo u redu,|zar ne?
{107702}{107770}Sjeæaš se one noæi
{107772}{107840}kada sam rekao|da sam tamo umirao?
{107852}{107917}Šalio sam se.
{107927}{107990}Tamo sam stvarno|umro.
{108007}{108070}I ponovno sam se|rodio.
{108100}{108155}Ja sam...
{108160}{108210}Liènost kakva sam|ja bio je mrtva,
{108215}{108292}i sada sam nov èovjek.|Mogu poèeti ponovno,
{108315}{108370}mogu ostaviti sve|iza sebe.
{108462}{108540}Mi se ne poznajemo,|zar ne?
{108575}{108642}Dovoljno se poznajemo.
{108760}{108832}Ovo æe zvuèati|glupo, ali...
{108875}{108965}Imamo nešto|zajednièko.
{108972}{109030}Nisam sigurna što je to.
{109042}{109115}Kada sam te prvi put|srela,
{109117}{109200}osjetila sam kao da te|veæ poznajem,
{109202}{109235}nešto...
{109372}{109435}Zašto radim ovo?
{109477}{109522}Nemam pojma.
{109642}{109692}Tvoji ožiljci...
{109747}{109812}Baš su seksi.
{110290}{110345}U redu je...
{110510}{110570}Èovjeèe, vidi ovo!
{110576}{110662}Sunce sija, a kralj se|vratio u grad!
{110667}{110752}Tako je,|pazi, svijete,
{110770}{110845}jer æu ujediniti|ljudsku rasu.
{110855}{110922}Evo, polazim!|-Kreni pažljivo.
{110985}{111022}Dobar poèetak.
{111780}{111820}I, kreæe!
{112655}{112707}Nemoj mi to raditi!
{112710}{112759}Što je, držao si|ga u gaæama?
{112760}{112845}Što radiš?|Što ako te prate?
{112850}{112917}Opusti se, smiri se,|sve je u redu,
{112920}{113002}nitko ne zna da sam ovdje.|-Sve je u redu? -Da.
{113007}{113060}Ne mogu otiæi ni kuæi|ni na posao,
{113062}{113107}ne mogu otiæi|ni na sranje.
{113110}{113167}Bojim se da me ne|šèepaju.
{113177}{113252}Ja æu sve urediti,|u redu?
{113272}{113365}Bojim se. -E pa,|nema da te uhvate.
{113382}{113442}Bojim se za tebe,|jebote.
{113462}{113547}Za mene? Ja sam|samo obièan deèko.
{114035}{114117}Sredio sam se, ali ima|nešto što hoæu znati
{114120}{114215}da ne bih ugrozio|ono što imam.
{114245}{114312}Što to?
{114315}{114391}Ti si ih pratio,|sve si shvatio,
{114392}{114487}to moram znati.|-A što je s dokumentima?
{114490}{114565}Tamo su samo adrese|i slièno...
{114592}{114639}Sranje.
{114640}{114700}Sranje, moji dokumenti...
{114705}{114782}Dokumenti,|glupane jedan!
{115010}{115055}Kod kuæe si?
{115450}{115495}Tko si ti?
{115520}{115607}Susan...|-Tko si ti?
{115622}{115702}Mislio sam da æu moæi|bolje, nisam ja kriv,
{115705}{115780}mislio sam...|-Kako si mogao?
{115782}{115845}Nisam ja!|-A tko onda?
{115850}{115920}Sve si uništio!|I vratio si se ovdje!
{115922}{115985}Daj da razgovaramo...|-Da razgovaramo?
{115990}{116090}Ti samo lažeš, nemaš ti|što reæi!
{116160}{116235}Osjeæam se bolesnom...
{116240}{116322}Moja koža gdje si me|dodirivao, moje usne...
{116515}{116560}Zakljuèano je.
{116728}{116775}I ona je zakljuèana.
{116780}{116835}Svi prozori i vrata su|zakljuèani.
{116837}{116880}Zvala sam policiju.
{116885}{116930}Gotovo je.
{117160}{117215}Susan, žao mi je...
{117245}{117296}Žao?
{117395}{117467}Molim te, pusti me,|neæu te povrijediti.
{117557}{117620}Pusti to...
{117757}{117827}Prestani, molim te.
{117830}{117880}Zašto moraš...
{117892}{117947}Ne tjeraj me da se|tuèem s tobom!
{118115}{118177}Ne želim te|povrijediti!
{118185}{118225}Povrijediti me?!
{118330}{118390}Zaboga, prestani|i slušaj me!
{118392}{118437}Èekaj malo.
{118542}{118605}Daj mi jebeni kljuè!
{119552}{119615}Beckett, dolazi ovamo!
{119645}{119690}On je, doði.
{119817}{119891}Crawley, gdje si,|govno jedno?
{119892}{119932}Umukni i slušaj.
{119942}{120019}Doæi æu tamo, hoæu|da završimo s ovim.
{120020}{120085}Imam dokumente, ako ih|želiš, doði i uzmi ih.
{120090}{120182}DA? GDJE? -Negdje u gradu,|gdje nas mogu svi vidjeti.
{120232}{120322}Može li na mom ranèu|u pustinji? -NE ZNAM...
{120332}{120382}HAJDE, IMA LI NEŠTO|ŠTO ZNAŠ? -Dobro,
{120385}{120430}biti æu tamo za par sati.
{120432}{120517}Dovoljno ti je? -Nema|problema, vidimo se.
{121275}{121320}Jebi ga.
{122635}{122682}Bok, Duke.
{123182}{123237}Sreðujem nešto.
{123260}{123322}Prvo æu trebati maknuti|sve dokaze o sebi.
{123327}{123367}Kao da nikada|nisam postojao.
{123437}{123500}Poèet æu od rane|na tvom vratu, u redu?
{123522}{123560}U redu.
{123580}{123667}Policija nikada neæe moæi|riješiti ovakvu zbrku,
{123670}{123707}i nikada me neæe|naæi.
{124590}{124657}Znaš što? Nisam|profesionalac,
{124662}{124700}ali obavljam posao.
{125145}{125192}Pogledaj je.
{125235}{125287}Mogli smo biti|sretni zajedno,
{125317}{125385}ali neæemo, zbog vas.
{125477}{125542}Voliš li roštilj?
{127052}{127137}Zaèepi. Radi kako|ti se kaže.
{127140}{127222}Ali to je sranje.|-Ne! Umukni i slušaj!
{127260}{127315}Jebote...
{127322}{127375}Ovo je previše|ludo.
{127437}{127465}U redu, slušajte...
{127470}{127528}Ako je jebaè ovdje negdje|blizu, hoæu ga odmah.
{127542}{127582}Završimo s njim.
{127585}{127642}Carl, provjeri gore.
{127647}{127730}Ti provjeri u zahodu,|ja æu vani.
{127757}{127835}I nemojte zajebati.|-Za to je kasno.
{127842}{127882}U redu, idemo.
{127935}{127977}Sranje.
{128145}{128207}Kao u zajebanom horror|filmu.
{128467}{128535}Zajebani vudu...
{128695}{128737}Sranje!
{129865}{129910}Duke, Isuse...
{129967}{130025}Što je, koji kurac,|naumio?
{130032}{130132}Zovi Carla. Odmah da|završimo s ovim.
{130517}{130582}Sranje, èovjeèe!|Što se dogodilo?!
{130600}{130690}Gdje je?|-Gore...
{130757}{130820}Ovdje je!
{131270}{131310}Što, koji kurac...!
{131322}{131360}To je benzin.
{131470}{131552}Koji kurac radiš, Crawley?|-Rašèišæavam.
{131605}{131665}Došao sam da bismo se|dogovorili.
{131717}{131752}Sereš.
{131760}{131825}Ubit æu te, jebote!
{131885}{131930}Gotovo je, Ray.
{132130}{132192}Èekaj... -Nisi se trebao|zajebavati sa mnom.
{132197}{132255}Ti si kriv za sve ovo!|-Doviðenja, Ray.
{132265}{132307}Èekaj...
{132577}{132640}Pomozi mi!|-Uozbilji se.
{132832}{132892}Sranje...
{132942}{133030}Nisi morao ovo napraviti.|-Morao sam.
{133052}{133122}Gdje je Ray?|-Mrtav je.
{133152}{133190}Sranje...
{133200}{133282}To je Carlov tekst.
{133287}{133374}Svršeno je. Ja nemam ništa|s ovim, pomozi mi,
{133375}{133417}molim te.
{133435}{133477}Moja leða...
{133487}{133562}Nešto se dogaða s mojim|leðima, pomozi mi.
{133587}{133627}Pomozi mi!
{133707}{133787}Bože, hladno mi je...
{133877}{133957}Molim te, pomozi!|Ako ostanem ovdje, umrijet æu!
{134125}{134190}Zašto? -Zar mora|postojati razlog?
{134310}{134360}Reæi æu ti|o èemu se radi...
{134415}{134515}Da li si "ikada" promatrao|mrave? -Mrave?
{134540}{134592}Jednom sam ih gledao|u zoološkom vrtu.
{134595}{134695}Tisuæe njih, jedu, seru,|jebu se, umiru...
{134725}{134787}Samo to i rade, milijunima|godina.
{134792}{134877}Što hoæeš reæi?
{134940}{135007}Hoæu reæi
{135010}{135075}da nije važno tko|što od nas radi.
{135077}{135115}Ovo je usrani svijet,
{135117}{135212}ili je najbolji, sve|ovisi kako gledaš na njega.
{135215}{135291}Ali mi tu ne možemo|ništa.
{135292}{135344}Odgovor leži u tome da|oni produže s onim što rade
{135345}{135415}a mi da produžimo|s onim što mi radimo.
{135437}{135502}Za nekoliko minuta|biti æeš mrtav,
{135505}{135564}tu nitko od nas|ništa ne može.
{135565}{135637}Ništa loše ti nisam|uèinio.
{135647}{135707}Ne ide to tako.
{135742}{135835}Molim te, ja te nisam|tukao.
{135840}{135887}Brinuo sam se|o tebi.
{135987}{136052}Više ništa nije važno,
{136057}{136120}jer si mrtav.
{136180}{136240}Ubit æeš nas?
{136287}{136347}Da.
{136425}{136460}Sranje...
{136710}{136765}Crawley, vrati se!
{136795}{136845}Pomozi mi!
{139228}{139666}Subtitles by:|M O Z E N