{1}{1}25.000
{1573}{1686}U glavnim ulogama:
{1944}{2057}PRAVILA PRIVLAÈNOSTI
{2368}{2481}U ostalim ulogama:
{3991}{4071}Potrudi se, pa æe te | muškarac pozvati van.
{4074}{4123}Neæu da me pozove.
{4126}{4191}80 posto žena koje tvrde | da su prezauzete za vezu
{4194}{4255}zapravo su usamljene, | Audrey.
{4258}{4329}Ne izlazi mi se samo | da ugodim istraživanjima.
{4332}{4381}I loše je za kožu. | - Molim?
{4384}{4431}Moja je koža | bolja kad izlazim.
{4434}{4502}Ma kad ti ne izlaziš? | - Pogledaj mi kožu!
{4505}{4531}Dok ti...
{4534}{4613}Dok ja više ne razgovaram!
{4616}{4667}Bože, to je to?
{4670}{4781}Izuzetna kuæa | od 840 èetvorna metra,
{4784}{4847}ne ukljuèujuæi vrt. | Èime se bavite?
{4850}{4898}Ovisi o prilici.
{4901}{4950}A prijateljica?
{4981}{5027}Samo pravim društvo.
{5030}{5143}Blagovaonica je slikana | za Manhattan Interiors.
{5174}{5239}Što je tamo visjelo?
{5242}{5285}John Sargent.
{5288}{5403}G. Harrison je skupljao | umjetnine. Kuæa je bez njih.
{5406}{5455}Poðite za mnom...
{5458}{5570}Strop je ruèni rad | praunuka Charlesa Thorpea.
{5573}{5603}To je stajalo.
{5606}{5664}Isplati se biti car reklama.
{5667}{5738}Zaradio je 30 milijuna | samo na Hair Houdiniju.
{5741}{5778}Zar toliko? Bože...
{5781}{5842}Poðimo u glavnu | spavaæu sobu.
{5845}{5917}Saro, nije ovo za tebe. | Nekako je...
{5920}{5971}...skuèeno.
{5986}{6029}Skuèeno?
{6032}{6102}Samo mi je to palo na pamet. | No doznala sam potrebno.
{6105}{6201}Sargenti iz blagovaonice | su nestali.
{6204}{6304}Cassatt u dnevnoj sobi | zamijenjen otiskom 39 od 150.
{6307}{6393}Nad glasovirom je plakat | easthamptonskog festivala,
{6396}{6476}nešto manje vrijednog od | Sisleya koji je ondje visio.
{6479}{6573}A ako je onaj užas u hodniku | Bacon, ja sam kobasica!
{6630}{6719}Harrisonova æe se prijevara | otkriti, dobit æu milijune!
{6722}{6822}Za nekoga drugoga! | Ne shvaæam gdje je užitak.
{6825}{6857}U pobjedi.
{6897}{6942}Hvala na svemu, mama.
{6945}{7042}Molila sam da tu rijeè | ne koristiš u javnosti.
{7102}{7164}Dvolièni lažljivi faæukov sin!
{7167}{7248}Ne volim vrijeðanje | supružnika. Ništa novo!
{7251}{7295}Možda ih je sakrio, | prodao...
{7298}{7332}Doznat æemo.
{7335}{7422}Imam iskustva s Hoffmanom, | njegovim odvjetnikom.
{7425}{7483}Dobar je, ali znam | njegovu igru.
{7649}{7731}Što to znaèi? Je li to loše? | - Ne, to ne znaèi ništa.
{7734}{7809}Samo to da je tvoj muž | našao drugog odvjetnika.
{7812}{7852}Zove se Daniel Rafferty.
{7855}{7903}Nikad èula. | - Ni ja.
{7906}{7952}Nov je u gradu. | - To me èini nervoznom.
{7955}{8045}Opusti se, nemaš | razloga za brigu.
{8048}{8163}Taj još nije radio u New | Yorku, bit æe prespor.
{8166}{8271}Nemaš razloga za brigu. | Još nisam izgubila sluèaj.
{8311}{8377}Sve u redu, dobro je. | Nije to problem.
{8380}{8453}Dobro je, sve u redu. | Dobra si ti.
{8824}{8855}Dobro...
{8890}{8923}Spremni?
{9168}{9211}To je Garyjev | novi odvjetnik?
{9879}{9936}Audrey Woods, | zastupam gðu Harrison.
{9964}{10003}Audrey Woods... | - Jasno.
{10006}{10055}Èuo sam samo pohvale.
{10095}{10125}Usput, ono je godilo...
{10128}{10205}Shvaæam da se tek | upoznajete sa sluèajem.
{10208}{10260}No želim da znate... | Što je?
{10263}{10309}Imate nešto... tu.
{10312}{10374}Hvala. Kako rekoh...
{10377}{10468}...primijetili smo da se | stanovitom imutku steèenu...
{10471}{10552}...steèenu tijekom braka | zameo trag,
{10555}{10642}no mislim da sam toèno | procijenila što nedostaje...
{10645}{10713}Snježna grudica... | Nema nagodbe.
{10716}{10769}Nisam je ni spomenula.
{10772}{10858}Osim ako mi ne želite | dati... da vidimo...
{10972}{11031}Ovoliko... toliko | dobivam za ovu parnicu.
{11034}{11087}Uz troškove. | Možemo poprièati...
{11090}{11117}Šalite se!
{11120}{11177}Pokušao sam. Sretno.
{11231}{11270}Gðica Woods, je li?
{11372}{11411}Jutro, Daniele. | - Jutro.
{11445}{11498}Dobre vijesti... suparnièki | odvjetnik je luðak.
{11939}{12008}Svi ustanite. Zapoèinje | rasprava o sluèaju 32.
{12118}{12167}Molim da sjednete | i molim za red.
{12221}{12324}Sutkinja Abramovitz, razvedena. | Bolno! Kivna na muškarce.
{12327}{12376}Dobro jutro, | dame i gospodo.
{12406}{12433}G. Rafferty...
{12436}{12505}Vraæate se na | Istoènu obalu.
{12508}{12568}Rekoh da je kalifornijsko | sunce loše za put.
{12571}{12667}Stvarno sam je vlažio | po vašem naputku.
{12704}{12746}Da èujem uvodne rijeèi.
{12840}{12913}Èasna sutkinjo, | predlažem odgodu.
{12916}{12970}Uoèili smo stanovita | razmimoilaženja glede
{12973}{13056}prijavljena imutka, odnosno | nekoliko vrijednih umjetnina.
{13059}{13098}Odnosno nekoliko | vrijednih umjetnina.
{13149}{13208}Mislite na slike, | skulpture i te stvari?
{13211}{13252}Tako je.
{13311}{13363}Slike poput ovih?
{13366}{13402}Zapravo da.
{13405}{13438}Kao ovaj Sisley?
{13441}{13494}Ili ovaj Morisot?
{13545}{13591}I što još imamo?
{13594}{13632}John Sargent.
{13635}{13672}Da.
{13675}{13746}Nije po mome ukusu. | I ja bih to poklonio.
{13749}{13875}Baš kao i moj štiæenik. | Sve. Pred neko vrijeme.
{13878}{13953}Anonimno, jasno. | Vrlo istaknutom muzeju.
{13956}{14033}Èudi me da vam to | gða Harrison nije rekla.
{14036}{14107}Vidite njezin potpis | na dokumentu donacije?
{14221}{14269}Što me podsjetilo, | èasna sutkinjo,
{14272}{14342}da predložim odgodu.
{14345}{14401}Naime tek sam unajmljen | kao zastupnik g. Harrisona
{14404}{14497}i nisam imao vremena | prouèiti sve aspekte.
{14500}{14669}Primjerice, imam raèun | na šest 28-dnevnih lijeèenja
{14672}{14803}od seksualne ovisnosti | na ime gðe Harrison.
{14872}{14915}Želim u to duboko zaviriti.
{14955}{15006}Imate tjedan dana.
{15009}{15044}Zahvaljujem.
{15122}{15179}6 mjeseci zbog | ovisnosti o seksu?
{15182}{15233}Terapeut je bio sjajan.
{15236}{15279}Moramo poprièati...
{15307}{15387}Kvocijent inteligencije joj | je velik kao èajni tanjuriæ.
{15390}{15453}Otkrila bih i sama da se | Harrison riješio umjetnina.
{15456}{15543}Zato sam tražila odgodu. | Samo me Rafferty pretekao.
{15546}{15591}I želiš da krepa? | - Majko...
{15594}{15688}Mislila sam društveno. | - Takvoga još nisam srela.
{15691}{15761}Vrlo je ne... nešto.
{15764}{15869}Ne znam je li mu se tek | posreæilo ili je jako dobar.
{15872}{15932}Možda je oboje. | - Hvala, majko!
{15935}{15973}Što to jedeš?
{16010}{16057}Povræe.
{16060}{16127}Je li zgodan? | - Nisam primijetila.
{16130}{16179}Nije tvoj tip. | Dovoljno je star za vozaèku.
{16182}{16225}Brzo, 6. kanal!
{16308}{16392}Danas smo èuli uvodne rijeèi | rastave Garyja Harrisona.
{16395}{16423}6. kanal, mama.
{16485}{16554}Navodno je rijeè | o 97 milijuna dolara.
{16557}{16673}Pred sudnicom smo zatekli | odvjetnika Raffertyja.
{16676}{16778}Držimo da su zahtjevi | gðe Harrison neèuveni.
{16781}{16900}Jamstvo ide na proizvode | g. Harrisona, ne njega osobno.
{16903}{16991}Nevjerojatno! Tek je stigao | i veæ obraðuje tisak.
{16994}{17062}I nisi primijetila | da je zgodan?
{17065}{17100}Nazovi me kasnije.
{17103}{17179}Ista je kao otac.
{17182}{17256}Predbraèni ugovor | ostaje na snazi.
{17259}{17363}Gða Harrison ima izgleda | kao snježna grudica u paklu!
{17415}{17466}U redu, g. Rafferty.
{17469}{17516}Prihvaæam!
{17754}{17821}Zašto me ne èudi?
{18028}{18079}DANIEL RAFFERTY | 2. KAT
{18649}{18713}Halo? G. Rafferty?
{19310}{19413}Hvala, Benny. Ako stigne | još, ostavi pred vratima!
{20621}{20676}Ja tu hodam!
{20679}{20726}Želite umrijeti?!
{20729}{20829}Ljubazna zamjena | za Arrona Swedlina,
{20832}{20902}jedna od najuspješnijih | njujorških odvjetnica,
{20905}{21023}prva u klasi na Yaleu, iz | Katza, Cohena i Phelpsa,
{21026}{21069}Audrey Woods!
{21260}{21310}Oprostite...
{21511}{21542}Kako je svijet malen...
{21545}{21640}Još jedan odvjetnik koji je | ljubazno uskoèio...
{21643}{21718}Neki kažu da postoji | metoda u njegovu ludilu.
{21721}{21783}Drugi pak da ludilo | jest njegova metoda.
{21786}{21865}S praksom u Chicagu, | Bostonu, Los Angelesu,
{21868}{21993}a držim da praksa | vodi do savršenstva.
{21996}{22087}Zakašnjeli Daniel Rafferty!
{22255}{22317}Uvijek izgledate | kao raspremljeni krevet?
{22366}{22457}Ili me iz neobjašnjivih | razloga otpoèetka ne volite
{22460}{22519}ili mi udvarate. | Što je toèno?
{22522}{22592}Da nagovijestim: Bili ste | blizu kod prvoga.
{22595}{22648}A što je bilo drugo?
{22651}{22726}Ma što radite ovdje? | - Barem budite malo zahvalniji.
{22729}{22765}Na èemu?
{22768}{22829}Moj prijan Lyman, onaj tamo, | trebao je zamjenu.
{22832}{22906}Pitao me znam li | zanimljivog odvjetnika.
{22934}{22986}Smatram vas vrlo | zanimljivom.
{23028}{23051}Vi?!
{23054}{23095}Tu sam zbog vas?!
{23098}{23139}Audrey Woods!
{23142}{23179}Nastupate...
{23251}{23308}SEMINAR O RAZVODU
{23382}{23473}Moj savjet: Razvod | ne mora biti agonija.
{23476}{23594}Prilika je to da ispitate | složeni osjeæajni labirint
{23597}{23662}ljudskih odnosa.
{23918}{23954}Sjajno.
{23957}{24006}Hvala, gðice Woods. | Vrlo pouèno.
{24009}{24040}Griz?
{24071}{24149}A sada poslušajmo | Daniela Raffertyja.
{24152}{24194}To sam ja. Ima li ostataka?
{24370}{24427}Puno hvala. Dobro jutro!
{24430}{24500}Sjajan govor, gðice Woods.
{24503}{24583}No... evo kako ja | sve to vidim.
{24618}{24664}Odvjetnici su šljam.
{24667}{24725}A brakorazvodni odvjetnici
{24728}{24776}su gljivice što rastu | ispod šljama.
{24810}{24891}Razvod je post-mortem | mrtvoga braka.
{24894}{24964}Mi zastupamo ljude | koji su najednom otkrili
{24967}{25039}strast prema borbi koje | do tad nisu bili ni svjesni.
{25042}{25201}Gdje je strast prema borbi | kada brak treba spasiti?
{25204}{25256}Nemojte odgovoriti.
{25259}{25313}To nije naš posao.
{25316}{25384}Svi vole spravice. | Kako se stvari razvijaju,
{25387}{25426}evo prilike da ih koristite.
{25429}{25550}Oprema za praæenje razvratna | muža ili nevjerne žene.
{25578}{25618}Na primjer...
{25621}{25788}...ovako mala kamera može | snimiti ovako veliku sliku...
{25844}{25876}Èudesno, ne?
{25879}{25929}Sjajna oštrina!
{25932}{26041}Èak i oni straga vide sve | ruže na šalu osumnjièene.
{26044}{26130}Više se ne moramo uzdati | u video-opremu iz trgovine.
{26133}{26257}Digitalna tehnika omoguæuje | da bacimo nezgrapne sustave
{26260}{26350}i postignemo optimalan | kvalitet slike.
{26376}{26474}Uvjeren sam da ta osoba | nije ni bila svjesna.
{26477}{26514}Slažete se?
{26517}{26595}U pamtite; nitko od nas
{26598}{26652}nije u ovome poslu iz ljubavi.
{26845}{26898}Mislim da ti je drag.
{26901}{26963}Drag?! Jesi li luda?
{26966}{27000}Jasno. Ali sam ti i mati.
{27003}{27061}Kad nismo u javnosti.
{27097}{27153}Mrvicu je bolno, | no veæ vidim rezultate.
{27156}{27251}Imam donje vjeðe | tinejdžerke!
{27254}{27316}Koja je doduše proletjela | kroz vjetrobran, ali ipak...
{27319}{27379}Zbog njega nisam | oka stisnula.
{27382}{27437}Ne brini, uhvatit æu ga | nespremna
{27440}{27503}i raspaliti gdje stignem!
{27506}{27579}Samo oprezno, još nisi | izgubila veliki sluèaj.
{27582}{27628}Ne, nije ni on.
{27631}{27672}A to je neodoljivo. | - Majko!
{27675}{27698}Oprosti...
{27735}{27778}Tako je...
{27781}{27845}Isprièat æu se! | - Raffertyju? Zašto?
{27848}{27908}Nisi uèinila ništa loše. | - Tako je.
{27911}{27993}Bit æe to posljednje što | oèekuje. Savršena strategija.
{27996}{28096}Isprika je manipulativna | taktika, kao i oprost
{28099}{28159}ili velikodušnost. | Past æe na to.
{28162}{28197}Nije Njujorèanin.
{28200}{28270}Tako si slatka kad se | spremaš na pobjedu!
{28340}{28382}Došla sam se isprièati.
{28385}{28446}Gnjavite se kucanjem?
{28449}{28493}Pa vi obièno samo provalite.
{28496}{28549}Urnebes! I nisam provalila.
{28552}{28597}Pogledajte vrpcu.
{28600}{28640}Ma vi ste paranoièni!
{28643}{28731}Ured vam je bio otvoren | i ja sam željela sastanak.
{28734}{28834}Isprièavam se na zbrci.
{28906}{28942}Ne znam što da kažem.
{28945}{28991}"Uðite" bi bilo lijepo...
{28994}{29027}Uðite.
{29132}{29222}Mogla sam vas tužiti zbog | povrede dižuæi one kutije.
{29225}{29306}Sluèaj Gibbons-Masters, | opasne prilike u uredu.
{29309}{29347}Povrijedili ste se?
{29350}{29388}Slomila sam nokat.
{29391}{29427}Otvorite poklon.
{29519}{29590}Ma pogledajte, jako lijepo!
{29593}{29650}Pomislih, bit æe vam drago | imati kravatu bez mrlje.
{29653}{29699}Zanimljiva pretpostavka.
{29702}{29758}Juèer ste održali | vrlo dobar govor.
{29761}{29803}Vrlo provokativan.
{29806}{29884}Vodiè kroz rastavu | "hladan k'o špricer"!
{29887}{29979}Ja se služim zakonom, | ne jeftinim teatralijama.
{29982}{30019}Dobro...
{30047}{30091}Sastanak je dobra zamisao.
{30128}{30166}Pa hajdemo onda.
{30169}{30211}Molim?!
{30241}{30299}Sastanimo se uz veèeru. | A pošto ste vi zaèetnica,
{30302}{30378}vi izvodite mene.
{30381}{30437}Da, svakako.
{30440}{30495}Ili možemo jesti ovdje. | Imam Snickerse.
{30544}{30582}Leslie, rezervirajte moj | stol u Èetiri godišnja doba.
{30585}{30642}Ja odabirem.
{30645}{30674}Bok, Leslie...
{30702}{30752}Dobro, samo ako nije vrt.
{30755}{30806}Moguænost kiše je 65 posto.
{30809}{30865}Sa sjeverozapada pristiže | polje niskog pritiska.
{30868}{30918}Pratim kanal s prognozama.
{30946}{31000}Vi ne možete biti èarobniji...
{31339}{31368}Baš s "huevosima"?
{31395}{31417}O, da.
{31494}{31570}Bože, obožavam ovaj lokal. | Tako romantièan, ne?
{31573}{31609}Ne.
{31612}{31737}Kakvo je ono moralno smeæe | o braènoj strasti?
{31740}{31820}Vi ne poželite ošamariti | štiæenike i poslati ih doma?
{31823}{31867}Zapravo ne.
{31870}{31956}Svaki me sluèaj uvjeri | da je brak krepana stvar.
{31959}{31996}Shvaæam...
{31999}{32039}"Shvaæam"?
{32042}{32109}To je sve? Shvaæate?
{32112}{32144}Shvaæam štošta.
{32147}{32179}Imate deèka?
{32182}{32262}Shvaæate štošta? Imam deèka? | Kakav je to prijelaz?
{32265}{32296}Iskreno sumnjam.
{32299}{32347}O, to shvaæate!
{32350}{32399}Shvaæate da ne mogu | imati deèka.
{32402}{32467}Mogu ga imati, vjerujte!
{32470}{32508}Cijelu gomilu!
{32511}{32578}Mogla bih lobirati za | 12-dnevni tjedan!
{32581}{32664}Što je to s rukama? | Kao, "nemam što reæi"?!
{32667}{32699}Uopæe nemate deèka.
{32702}{32737}Zašto?
{32740}{32808}Pa kad pitate... | - Lijepi ste...
{32811}{32837}...inteligentni...
{32840}{32891}To je Kušnja za brak. | - Kušnja za brak
{32894}{33002}Nije li brak krepana stvar? | - Zato nema deèka i toèka!
{33247}{33289}A vi?
{33292}{33328}Što ja?
{33331}{33383}Vi idete na spojeve? | - Rekli ste "toèka".
{33386}{33424}Opet otvaram temu. | - Shvaæam...
{33454}{33514}Mislite, osim ovog veèeras?
{33517}{33583}Ovo nije spoj! | Ovo je sastanak.
{33586}{33627}Ozbiljno? | - Da.
{33630}{33698}Ozbiljno. Moj prvi | odgovor uvijek je istina.
{33701}{33761}Živim po tom pravilu, | privatno i profesionalno.
{33764}{33819}Prvi odgovor osobe | odgovara onome što osjeæa.
{33822}{33851}Jako dubokoumno.
{33854}{33901}Slažem se. | No može li kompromis?
{33904}{33937}Redimo "intimni sastanak"?
{33940}{34027}Intimnost ne mijenja | ništa. Posao je posao.
{34030}{34094}Ne mislite valjda tako.
{34097}{34168}Da me niste rašèlanjivali
{34171}{34249}tim raskuštranim, boemskim, | "moje èarape su rasparene,
{34252}{34311}pa kužim sve munjeno" | razmišljanjima!
{34314}{34409}Ne postoji psihoanalitièki | preèac u moje gaæice.
{34412}{34451}Dvaput huevos de chivos.
{34495}{34519}Hvala.
{34583}{34639}Pogledajte, medicinski | otpad u èaši.
{34682}{34713}I nema suncobrana?
{34716}{34781}Morate to popiti. | Staro kubansko nasljeðe.
{34784}{34880}Prije dvoboja, suparnici | ispiju huevo de chivo.
{34883}{34977}To znaèi, "to što te | želim ubiti,
{34980}{35051}ne znaèi da te | ne volim i ne poštujem."
{35075}{35127}Huevo de chivo.
{35380}{35446}Koji je to vrag?!
{35449}{35505}Huevo de chivo. | Jarèevo mudo.
{35508}{35614}Jarèevo mudo?! | To sam imala u ustima?!
{35617}{35684}Ma ne, to je višnja. | Evo, maraschino višnja.
{35725}{35768}To vam je prejako?
{35817}{35873}Nipošto! | Popijmo još jednom.
{35876}{35926}Ne, ta stvar je ubojita.
{35929}{35980}Stvarno?
{35983}{36030}Konobarice!
{36062}{36112}Huevo de chivo.
{36265}{36321}Ajme...
{36324}{36389}Ponijeli ste kišobran, | gðice "TV-prognoza"?
{36439}{36551}65 posto? Da ste barem | rekli 85-90.
{36554}{36643}I baš tih 25 posto | vama treba, a meni ne!
{36646}{36728}Razlika je kako vi i ja | trebamo drukèije postotke,
{36731}{36830}jer ako mojih solidnih 65 | i vaših 85...
{36890}{36935}Malo sam pripita.
{36938}{37026}Bar æemo pred sutkinjom | biti jednako mamurni.
{37029}{37127}Što je to izmeðu vas dvoje?
{37130}{37163}Otupjela su mi usta.
{37166}{37216}Ništa ne osjeæam.
{37219}{37254}Vi?
{37397}{37440}To sam bogme osjetio.
{38577}{38649}O, moj Bože! | Što sam to uèinila?
{38652}{38697}Kavu?
{38700}{38765}Sud je za 45 minuta. | Odjeæa je u sušilici.
{38768}{38806}Sušilici?
{39123}{39182}Nosila sam gaæice. | Toliko se sjeæam.
{39248}{39311}Jesam li sinoæ uèinila nešto | što bih mogla požaliti?
{39314}{39361}Valjda ne.
{39391}{39522}Ajme meni. Bar æemo oboje | na sudu izgledati oèajno.
{39525}{39555}Spremna?
{39558}{39611}Ma daj! | - Što je?
{39614}{39700}Ti tvrdiš da usrano izgledam. | Nije dobro? Sjajna kravata.
{39738}{39811}97 milijuna dolara, | èasna sutkinjo.
{39814}{39934}No ogranièio bi mi štiæenicu | na sumnjivi predbraèni ugovor.
{39937}{40022}Pripada joj polovica imetka | i postotak od dobiti.
{40025}{40072}Vi to o zbiljno?
{40075}{40116}Molim?
{40119}{40217}Oprostite što upadam, ali | zato što je brojka velika
{40220}{40297}držite da vaša štiæenica ima | veæa prava od predbraènog?
{40300}{40352}Sinoæ niste nastupali | s tog položaja.
{40355}{40448}Ako se sjeæate... | ...svog položaja.
{40451}{40580}Sad govorim o dvoje ljudi | koji su bili muž i žena,
{40583}{40640}koji su sve dijelili | osam godina.
{40643}{40757}Žena je u trenucima | intime mužu bila nadahnuæe.
{40760}{40839}Ali kako ste ono rekli? | Blistavo! Zapisao sam...
{40873}{41019}"Intimnost ništa ne mijenja | na stvari. Posao je posao."
{41022}{41066}Kako se usuðujete?!
{41069}{41103}Evo moga stava...
{41106}{41208}Prema državi New York, | gða Harrison je potpisala
{41211}{41249}dosad neosporeni predbraèni.
{41252}{41299}Sud presuðuje | dokument važeæim
{41302}{41383}i imetak æe se podijeliti | kako je njime predviðeno.
{41386}{41447}A vas dvoje svoje | razmirice nosite van!
{41495}{41616}Sretni smo s ishodom. To je | veliki uspjeh. Trenutak...
{41619}{41693}Audrey... èekaj!
{41696}{41770}Èekaj, samo trenutak.
{41773}{41842}Molim te, | daj da objasnim.
{41845}{41944}Odsad nastupate u prostoru | lišenom svakog morala.
{41947}{41980}Ne shvaæaš, je li?
{41983}{42022}Dao sam ti | vrhunski kompliment.
{42054}{42116}Prisilila si me da igram | prljavije no ikad dosad.
{42119}{42144}Toliko si dobra.
{42147}{42254}Molim te! Te spike èuvaj | za TV. Duguješ mi ispriku.
{42257}{42332}Poput one tvoje sinoæ?
{42335}{42429}Pokušala sam te smekšati, | no dala sam da me zavedeš,
{42432}{42472}da misliš kako imaš nadzor.
{42475}{42516}Dala si mi da te zavedem?!
{42519}{42563}Povrijeðeni, g. Rafferty?
{42566}{42652}Noæas bilo je posebno. Nemoj | sve pogaziti zbog gubitka.
{42655}{42707}Oèvrsni malo. | Da me povrijedio
{42710}{42819}svaki kojeg sam zveknula, | veæ bih bila u ludnici!
{42876}{42932}Svršio si s ovim?
{43034}{43061}"Zveknula"?
{43064}{43122}Tu si rijeè upotrijebila?
{43125}{43187}Na stubama ispred suda | u 21. stoljeæu.
{43190}{43238}A koliko ih jesi zveknula?
{43241}{43284}Nijednoga. Ali nije u tome | bit, majko.
{43345}{43379}Audrey, pogledaj me.
{43382}{43435}Ne znam odakle ti | nesposobnost
{43438}{43482}priznati da te netko privlaèi.
{43485}{43549}Znaš da to nije zdravo!
{43552}{43628}Jednog dana probudit æeš se | s burmom na prstu,
{43631}{43699}najsretnija što si se udala.
{43702}{43794}On me ne privlaèi. No mrzim | što se opæenje s njim srozalo.
{43797}{43841}Odluèila si se za razvode.
{43844}{43896}Mislila si da je to otmjeno?
{43899}{43957}Nove Serene!
{43960}{43985}Molim?
{43988}{44060}Serena... najžešæi | novi dizajner.
{44063}{44100}Nikad èula.
{44103}{44153}Jesi sigurno. Udala se za | Thornea Jamisona.
{44156}{44227}Koga? | - Pjevaèa "Igala".
{44230}{44313}U pravo je potpisao | debeli ugovor za ploèe.
{44316}{44391}Nekih 80 trilijuna.
{44394}{44472}Ona zna da u žene | posljednja propadnu ramena.
{44475}{44529}Bogme je èeka | Nobelova nagrada.
{44532}{44570}Barem.
{44834}{44888}Priberi se, Audrey!
{44891}{45007}G. Harrison je rekao da sam | ga nadahnuo za novi izum,
{45010}{45071}zove se "papirolog".
{45074}{45121}Dobili ste postotak?
{45124}{45172}Ne...
{45175}{45231}Dovoljno mije bilo | dobiti njegovu parnicu.
{45234}{45343}Vaši sudski sukobi s | odvjetnicom Audrey Woods
{45346}{45408}postaju vruæa tema | upravnièkim krugovima.
{45475}{45532}Što da kažem? | Audrey Woods
{45535}{45623}je najbolja odvjetnica | koju sam sreo.
{45626}{45690}Mogu jedino stremiti tome | da postanem jednako mudar.
{45693}{45765}Divna je. | Doista divna.
{45803}{45880}U pravo ste objavili | knjigu o razvodu,
{45883}{45945}"U dobru i zlu - vodiè | do sretnoga razvoda".
{45948}{46033}Knjigu? Kakvu knjigu?! | Kada još i knjige piše?
{46036}{46127}...najveæa brakorazvodna | parnica od Harrisonove,
{46130}{46223}sluèaj košarkaša Shandela | i njegove žene Irene.
{46226}{46290}Ovo suðenje opet je sukobilo | dvoje odvjetnièkih pitbula,
{46293}{46366}Audrey Woods | i Daniela Raffertyja.
{46369}{46462}Presuda je upravo izreèena. | Kažu mi da upravo izlaze.
{46465}{46545}Kakav je osjeæaj dobiti | presudu u svoju korist?
{46548}{46634}Sretan sam što imam prvu | odvjetnicu New Yorka.
{46637}{46715}Sluèaj je otkrio pregršt | ne baš lijepih stvari o
{46718}{46792}vašem štiæeniku. Pohvaljeni | ste za èasnu taktiku.
{46795}{46878}Bitno je da se pripremite | i pomno istražite zakone,
{46881}{46913}provedete noæi za knjigom
{46916}{46947}i spremite se na sve.
{46950}{46984}Ako sam išta nauèila,
{46987}{47058}onda je to; nemoj da te | uhvate spuštenih hlaèa!
{47140}{47182}Jako dobro...
{47185}{47265}Prigovor! Zastupnik po | obièaju samo nagaða.
{47268}{47316}Odbijam, gðice Woods.
{47345}{47413}Odvjetnica se zavarava... | - Nebitno, g. Rafferty.
{47416}{47481}...cijela dokumentacija, | sve što trebate znati.
{47484}{47533}Video-trake su nebitne!
{47536}{47595}Prigovor! | Odvjetnik gnjavi štiæenika!
{47598}{47636}Odbijam, opet!
{47639}{47669}Silazite sa stola, | g. Rafferty!
{47672}{47744}Gðice Woods, sud ne zanima | što mislite
{47747}{47808}o èarapama g. Raffertyja.
{47811}{47905}Koliko gðica Woods može | popiti nije bitno za spor!
{47908}{47988}Zastupnici!
{47991}{48057}Da me zanimaju osobne svaðe,
{48060}{48122}bila bih sa svojima doma!
{48125}{48151}Je li jasno?!
{48426}{48495}Ovdje Audrey. Trenutaèno | nisam doma. Ostavite poruku.
{48498}{48555}I da jesam doma, | tebi se ne bih javila!
{48558}{48628}O boje znamo | da to nije istina.
{48631}{48708}Oprosti što smetam, | no ovdje je vrlo oblaèno,
{48711}{48786}pa pomislih da provjeriš | na kanalu za prognoze
{48789}{48856}u koje doba oèekuju kišu.
{48937}{49003}Ako želiš da te pustim, hoæu,
{49006}{49078}no to je velika šteta.
{49081}{49161}Èuvaj se.
{49164}{49204}Znaèi doma si.
{49207}{49277}Samo da ti kažem | da me pustiš na miru.
{49280}{49379}Baš sam i rekao da hoæu. | - Samo ti kažem da to i želim.
{49382}{49412}Ne misliš tako.
{49415}{49465}Vjeruj mi | - Ono prvo ili ono drugo?
{49468}{49502}Oboje. | - Zbunjen sam.
{49505}{49533}Zašto?
{49536}{49598}Ne znam baš. Možda | da mi pošalješ snimak?
{49601}{49636}Ne budi smiješan.
{49639}{49675}Veèeraj sa mnom.
{49678}{49729}Nisam gladna. | - Nisam mislio odmah.
{49732}{49764}Nisam ni ja.
{49767}{49796}Srce!
{49799}{49824}Moram poæi.
{49931}{49992}Tako providiš subotnju veèer?
{49995}{50074}Jedeš smeæe uz prognoznu.
{50077}{50154}Imam karte za Thornea | Jamisona i "Igle". Idemo!
{50157}{50200}Na rock koncert?
{50203}{50280}Seks, droga | i rock'n'roll su za tebe...
{51365}{51431}O, Bože, mislim | da sam oglušila!
{51602}{51631}Jeste li dobro?
{51681}{51727}Želite o tome prièati?
{51755}{51807}On je seronja.
{51810}{51850}Mrzim ga!
{51853}{51920}Ševi sve živo!
{51923}{51983}Ako se od njega ne | razvedem, ubit æu ga!
{52022}{52095}Može jedan savjet?
{52098}{52145}Vrlo ste mladi.
{52148}{52226}Na vezama treba raditi. Mnogi | parovi prolaze teška razdoblja.
{52229}{52312}Uvijek postoji naèin.
{52315}{52352}Razvod je posljednje rješenje.
{52355}{52402}Znam ponešto o tome.
{52405}{52478}Krivo nosite moju bluzu.
{52481}{52540}Treba je nositi golih ramena.
{52543}{52589}Vaša su lijepa.
{52592}{52644}Vi ste Serena?
{52714}{52758}Znaèi vaš muž je...
{52761}{52802}Kreten na pozornici? Da.
{52856}{52891}Evo vam moja posjetnica.
{53118}{53224}Tek da znate, odaberete li | Katza, Cohena i Phelpsa,
{53227}{53276}ja pazim na štiæenike.
{53279}{53349}Drže nas Tiffanyjem | njujorških odvjetnika.
{53352}{53428}Je I'? Da ste željezarija,
{53431}{53491}mogli biste ga traènom pilom.
{53529}{53590}Pa moguæ je i taj pristup.
{53620}{53685}Živjela Audrey i njezina | nova štiæenica Serena.
{53688}{53748}I sav novac koji æe | donijeti u tvrtku!
{53751}{53781}Još nije sigurno.
{53784}{53816}Još nije sigurno...
{53819}{53869}Gospodin vam šalje ovo... | - Hvala.
{54043}{54086}Zaboga, što je to?
{54089}{54129}Nikad nisi pio | jarèevo mudo?
{54132}{54165}Ne bih rekao.
{54455}{54515}Isprièajte me trenutak.
{54518}{54579}Mislite da je unutra | stvarno jarèevo jaje?
{54678}{54740}Previše si emocionalna...
{54743}{54779}Ma zamisli...
{54782}{54849}Vidio sam da slavite. | Sjest æe te s nama?
{54852}{54923}Samo da pozdravim Serenu. | - Ti si poklonica?
{54926}{54957}Tko nije?
{54960}{54997}Serena, Audrey Woods.
{55000}{55059}Serena mi je nova štiæenica.
{55062}{55109}Nažalost, rastaje se.
{55112}{55149}Znam.
{55152}{55182}Da?
{55185}{55229}Valjda je u novinama.
{55232}{55327}Ne, nego sam do pred 30 | sekunda mislila da je moja!
{55330}{55368}Što?
{55371}{55425}Dobar izraz lica. | Vježbao si pred ogledalom?
{55428}{55508}Odluèila sam uzeti | nekoga drugog.
{55511}{55586}Na sastanku ste stalno | prièali o moralnom pristupu
{55589}{55631}i da ne treba iæi ðonom.
{55634}{55692}Onda sam proèitala | njegovu knjigu.
{55695}{55739}Ja želim Dannyja.
{55742}{55829}Otkinut æe Thorneu jaja i | vratiti mu ih kao naušnice.
{55832}{55881}Valja primijetiti
{55884}{55953}da i gðica Woods | zna odrezati jaja...
{55956}{55999}Pa neka.
{56002}{56060}Oprosti, krivo je ispalo.
{56063}{56162}Inaèe ta se jakna | ne nosi s pojasom.
{56215}{56258}Dobro.
{56714}{56756}Odmah se vraæam.
{56863}{56901}Oteo si Serenu | da mi napakostiš.
{56972}{57025}Uði. Odjeljak 2 | je slobodan.
{57065}{57145}Ništa nisam oteo. Proèitala | je moju knjigu. Ozbiljno.
{57148}{57189}Tebi ništa nije ozbiljno.
{57192}{57263}E, to æe morati | ostati tvoj problem.
{57300}{57384}No ja ne lažem. Ne odobravam | to. Kad sam tebi lagao?
{57416}{57477}Znaš što, prijane?
{57480}{57537}Uzimaš li sluèaj | da petljaš sa mnom,
{57540}{57577}bogme æe biti ružno!
{57580}{57625}Ružnije nego sada?
{57628}{57673}Daj da ja tebi nešto kažem...
{57676}{57796}Da si umjesto paranoje | pribjegla razmišljanju,
{57799}{57870}otkrila bi da ti i ja | možemo koegzistirati.
{57873}{57934}I ne mislim samo | profesionalno.
{58030}{58073}Na zaboravi oprati ruke.
{58130}{58205}Što radite, obarate | svjetski rekord?!
{58233}{58270}Cure...
{58284}{58341}Stanite u red.
{58375}{58411}Sve æe te doæi na red.
{58414}{58468}Kako je tebi ime, malena? | - Cindy.
{58471}{58509}Tako mi se zvala kujica.
{58512}{58564}Otkad si Thornetta? | - Oduvijek.
{58567}{58630}Volim te, Thorne! | - I ja tebe, mala.
{58748}{58790}Gle, Barry,
{58793}{58856}imam i otmjene obožavateljice.
{58859}{58915}A...
{58942}{58978}...što ti želiš?
{58981}{59023}Tebe.
{59087}{59129}Lijep poèetak. | Obožavam to.
{59132}{59189}Izravno, bez kenjaže. | Tako volim.
{59276}{59347}Reci s èime | imamo posla, lutko.
{59350}{59412}Evo s èime, lutkice...
{59415}{59473}Doma imaš odanu ženu | koja naporno radi.
{59476}{59549}No ti je varaš i trošiš | na striptizete i kurve.
{59552}{59635}Napokon si je ostavio | i ona traži razvod.
{59638}{59708}U pravo si èuo uvodnu | rijeè suparnièke strane,
{59711}{59752}bez kenjaže, | baš kako voliš.
{59755}{59861}A žena ti je unajmila | drugog najboljeg odvjetnika.
{59864}{59972}Treba ti netko da isprièa | tvoju bijednu stranu prièe
{59975}{60027}i prikažete | kao kolaèiæ od jagode.
{60125}{60203}Volim kolaèiæ od jagode...
{60206}{60246}I tvoj stil.
{60249}{60292}Znaš što?
{60295}{60388}Mislim da ovaj razgovor | treba nastaviti u mojoj gajbi.
{60391}{60424}Znaš što ja mislim? | - Što?
{60427}{60493}Razmišljanje prepusti meni.
{60568}{60603}Može.
{60606}{60659}Bol?! Prouzroèit æu joj ga | toliko da æe...
{60662}{60759}Jedina "poslovna" odluka mu | je platiti kurvu karticom...
{60762}{60827}Objasnite štiæenici da je | svrha nagodbe izbjeæi bol...
{60830}{60903}Objasnite mu da mi prijetnje | nasiljem olakšavaju posao.
{60906}{60976}Možemo li odmah prijeæi | na rezanje njegovih jaja?!
{61067}{61106}Možemo li nastaviti | podjelu imetka?
{61109}{61206}Imetka?! Ona nema ništa!
{61209}{61296}Ja dajem lovu za te prnje!
{61299}{61412}Prnje? Nicole Kidman je te | "prnje" nosila na Oskarima!
{61415}{61542}Nikamo neæemo dospjeti bez | promišljanja obiju strana.
{61545}{61643}Promišljanje, od njega? | Ja sam mu vražja žena!
{61646}{61743}Nije mi imao obzira reæi da si | je dao pribiti lubanju navrh...
{61746}{61787}Meni je dovoljno. | - I meni.
{61840}{61913}Zaboravite. Ne zanima | me njegov novac.
{61916}{61980}Dobro zaraðujem. | Želim samo jedno.
{61983}{62011}A to je?
{62014}{62059}Caislean Cloiche.
{62062}{62120}Vidio sam to negdje. | Što je to?
{62123}{62172}Najèarobnije | mjesto na zemlji.
{62212}{62267}Naš dvorac u Irskoj.
{62270}{62311}Moj dvorac iz bajke.
{62458}{62486}Idemo! Idemo!
{62489}{62580}A ovdje unutra... lezi!
{62583}{62661}Ovdje volim probati
{62664}{62697}i jammati s bendom.
{62700}{62747}Ovdje se volim igrati | s voænim strojevima.
{62750}{62803}Osjeæam sreæu!
{62873}{62964}Zlati... zlato...
{62967}{62998}...srebro?
{63001}{63066}Èije je to? Nije moje. Billy!
{63069}{63181}Nisam još bio postao onaj | pravi ja, još sam bio pomalo
{63184}{63254}blesav.
{63257}{63321}Ima stotinu spavaæih soba.
{63324}{63355}Možda èak i manje.
{63358}{63406}Jednu koristi Serena | za svoj hobi.
{63409}{63456}Voli šivati.
{63459}{63487}Evo je.
{63490}{63533}Volim ga! Volim ga!
{63536}{63562}Nije li sjajna?
{63565}{63590}On je samo moj!
{63593}{63676}Možda je u tom | trenutku uzimala drogu.
{63701}{63773}To možete upotrijebiti.
{63806}{63848}Pogledajte moja kolica.
{63851}{63893}Billy!
{63922}{63953}To je bilo dobro.
{63984}{64077}Znaèi to želite. | Caislean Cloiche.
{64163}{64241}Znaèi to želite?
{64244}{64283}To znaèi | "dvorac u stijeni".
{64286}{64399}Mislim, koliko takvih | uopæe postoji?
{64402}{64466}Kad sam ga otkrio, | morao sam ga imati.
{64469}{64587}I vi ste odluèili kupiti | taj... dvorac?
{64590}{64624}Kvragu, da.
{64627}{64660}Dobro.
{64690}{64771}Rekla sam Thorneu: | "Moramo tu živjeti".
{64774}{64810}Znaèi vaša je odluka | da ga kupite.
{64813}{64863}Odmah sam nazvala | agenta nekretnina.
{64866}{64917}Halo?
{64978}{65022}O, odvjetnice...
{65065}{65138}I ja imam dobre vijesti.
{65141}{65258}Èini se da bi se sve | moglo riješiti prijateljski.
{65261}{65304}Da.
{65307}{65382}Prijeti prava opasnost | da izbije mir.
{65418}{65482}Što bi me | jako razveselilo.
{65534}{65572}I mene.
{65630}{65683}Razgovarao sam sa štiæenicom. | - I ja sa štiæenikom.
{65686}{65747}On želi... | - Ona želi...
{65750}{65793}On želi samo... | - Ona želi samo...
{65930}{66017}Poðite u Irsku po izjave | osoblja, pa da to riješimo.
{66105}{66112}IRSKA
{66611}{66659}O, shvaæam.
{66662}{66699}Vi bi uzeli kola?
{66702}{66779}Zato sam tu, | g. O'Callaghan.
{66782}{66837}Na pravom ste mjestu.
{66840}{66890}Dobro. | - Samo...
{66893}{66966}Mi utorkom ne radimo.
{66969}{67003}Molim?
{67006}{67079}Utorkom nisam ovdje.
{67150}{67196}Znam što mislite.
{67199}{67250}Ako me nema u utorak
{67253}{67303}i utorkom ne radimo,
{67306}{67423}a danas je utorak i ja tu | stojim, kako je moguæe...
{67426}{67520}To vam ovisi o tome | kako na to gledate.
{67523}{67597}Inaèe...
{67699}{67749}Vidite, utorak je,
{67752}{67833}i mene nema premda | je utorak.
{67836}{67890}Svratite kad želite | kad ne bude utorak.
{68666}{68698}Oprostite!
{68726}{68758}Oprostite!
{68854}{68911}Puno hvala. Možete li...
{68914}{68955}Odakle ti ta vražja stvar?!
{68958}{68994}Dobro jutro želim!
{68997}{69038}Caislean Cloiche?
{69041}{69070}Uskoèi.
{69098}{69143}Unutra? S tobom?
{69192}{69240}I nije baš tako daleko.
{69243}{69300}Samo ravno cestom
{69303}{69398}i nakon 13 kilometara | vidjet æeš znak
{69401}{69497}za Vražje stubište. | Dvorac je s druge strane.
{69575}{69625}Pa odakle ti?
{69628}{69680}O'Callaghan se vratio.
{69683}{69720}Utorkom ne radi.
{69723}{69787}Ne, ovaj sam posudio od | O'Callaghana mesara,
{69790}{69863}strica O'Callaghana koji radi | s autima i svakoga utorka...
{69866}{69902}Ne zanima me.
{70086}{70142}Prekrasno...
{70170}{70286}'Možeš li taknuti obzor, | tvome putu je skoro kraj. '
{70331}{70366}James Joyce?
{70369}{70413}Ne, moj stric Clive.
{70451}{70513}No jednako dubokouman, | zar ne?
{70864}{70910}Sad mi se sve pokvarilo.
{70980}{71047}Što li æu reæi | g. O'Callaghanu?
{71245}{71331}Nije li magla nevjerojatan | prirodni fenomen?
{71334}{71381}U stjenovitim podruèjima
{71384}{71474}temperatura stijena danju | je manja nego zemljina
{71477}{71541}i što biva...
{71544}{71586}"Prognoza vremena"...
{71666}{71703}Sada je ponoæ.
{71706}{71804}Malo smo se izgubili, | priznajem.
{71807}{71875}No blizu smo. | Jako smo blizu. Mirišem to.
{71921}{71957}Samo malo...
{71960}{71988}Molim?
{71991}{72046}Gle tamo... neka prikolica.
{72215}{72280}O, Bože!
{72283}{72334}Doèekali smo se na noge!
{72337}{72384}Vidi ima li svjetla.
{72387}{72453}Može. Onda æu ti napuniti | kadu i skuhati veèericu.
{72456}{72530}Èuj, zajedno smo u ovome, | sad smo ekipa.
{72533}{72583}Da, zasad.
{72586}{72624}Kako smrdi!
{72627}{72661}Evo...
{72664}{72724}Sve u svemu, mislim | da smo bili dobri. - Jesmo?
{72727}{72762}Našao sam svjetlo.
{72765}{72847}Da, oprosti. Ne znam | što bih bez tebe.
{72850}{72930}Zapravo ne shvaæam kako | ti uspijeva. Pišeš knjige,
{72933}{73042}nastupaš na TV-u, | onda komedije na sudu...
{73070}{73109}Ti se to skidaš?!
{73112}{73190}Samo ovo dolje.
{73193}{73234}Sve je prljavo.
{73237}{73282}Zašto sam to uèinila?!
{73285}{73365}U slobodno vrijeme radiš za | Irsku turistièku zajednicu.
{73368}{73401}Na što ciljaš?
{73404}{73457}Samoj mi je dobro išlo.
{73460}{73493}Budimo iskreni.
{73496}{73544}Prije mene si bila izgubljena.
{73547}{73602}Metaforièki...
{73605}{73663}Svejedno, doði.
{73666}{73723}Legni, izgledaš umorna.
{73726}{73784}Treba ti odmora.
{73787}{73864}Pa da prije mene stigneš | u taj Caislean Click.
{73867}{73937}Ne Click, nego Cloiche.
{73940}{73978}Cloiche...
{74002}{74045}Caislean Cloiche.
{74048}{74131}To uopæe nije rijeè.
{74134}{74198}To je irska rijeè. Sad smo | u Irskoj. Prilagodi se.
{74201}{74269}To mogu. Vrlo sam | prilagodljiva.
{74272}{74317}Vjerojatno više od tebe.
{74320}{74357}I jedan savjet. | - Da?
{74360}{74409}Nikad nemoj ženi reæi | da izgleda umorno.
{74412}{74468}Ajme, sažela si sebe | u jednoj reèenici.
{74471}{74556}Spoj natjecateljskog duha | i razuzdane nesigurnosti.
{74559}{74711}Zašto je netko tako pametan i | toliko je postigao, nesiguran?
{74754}{74791}Znaš što?
{74794}{74873}Provedi ti tinejdžerstvo | kao prištava, štrkljava kæi
{74876}{74949}najljepše žene na svijetu, | pa mi se javi.
{75096}{75148}I bolje da me ne ostaviš.
{75391}{75431}Nikada.
{75954}{75995}O, moj Bože...
{76111}{76155}Bilo smo tako blizu?
{76187}{76242}Kvragu i Thorne i Serena, | ja ga želim.
{76315}{76382}Pa... dužnost zove.
{76554}{76640}Misliš pridobiti poslugu | da potkrijepe tvoju tvrdnju?
{76643}{76695}To æemo otkriti.
{76698}{76741}Valjda hoæemo.
{76798}{76873}Živjeli! Dobrodošli | u Caislean Cloiche.
{76876}{76924}Ja zastupam g. Jamisona. | - Ja zastupam gðu Jamison.
{76927}{77005}Mogu li prièati s poslugom? | - Mogu li prièati s poslugom?
{77008}{77102}Ah, da niste otmjeni | odvjetnici iz Amerike?
{77135}{77174}Ma divno!
{77791}{77869}Zasad se svi slažu sa mnom. | - I sa mnom.
{78020}{78119}Moram ponovno razgovarati s | poslugom. Ovo nikamo ne vodi.
{78122}{78178}Bojim se da nemate sreæe.
{78181}{78240}Svi idu na festival.
{78268}{78310}Seoska proslava
{78313}{78394}utemeljiteljskog para koji | je selo osnovao pred 200 g.
{78397}{78437}Lijepa prièa.
{78440}{78512}Jako su se voljeli, ali | njezin otac nije odobravao.
{78515}{78584}Zato su pobjegli ovamo | i potajno se vjenèali.
{78587}{78662}Svake godine imamo | festival njima u èast.
{78665}{78704}Jako romantièno.
{78707}{78743}Pjesma i ples...
{78746}{78797}Ah, baš lijepo.
{78800}{78886}Stari nije volio da mu | seljoš bari kæer,
{78889}{78925}itd., itd., bla-bla...
{78928}{79019}U biti, lažna izlika | za trodnevno lokanje.
{79176}{79282}Nije li to divljakuša | iz moèvara?
{79285}{79375}Nikad te ne bih prepoznao. | Bo'me krasan stas veèeras,
{79378}{79423}ako smijem primijetiti.
{79426}{79526}A ti kao da nosiš...
{79554}{79582}...to.
{79585}{79670}Ne sviða ti se? | - Ne, ne, nešto kao spoj
{79673}{79762}Lennyja Kravitza | i Kissa bez šminke.
{79765}{79822}Nikad prestar | za rock'n'roll...
{80546}{80584}Èula si za prièu | o ovome mjestu?
{80587}{80659}Da, za mene je sve to | u patuljcima i vilenjacima.
{80662}{80711}Meni je baš zgodno.
{80714}{80775}Izvolite... | - Što je to?
{80778}{80815}Izgleda kao poteen.
{80818}{80853}Molim?
{80906}{80946}Tradicionalno irsko piæe.
{80949}{80993}Mrvicu nezakonito. | Zabranjene destilerije...
{80996}{81031}Gelski "jarèevo mudo"?
{81034}{81065}Živjeli!
{81121}{81201}Imala sam pravo...
{81204}{81257}Smijem li moliti | za ples, gospoðice?
{81260}{81299}Znate, ne mogu...
{81302}{81335}Ma jedva èeka!
{81338}{81381}Radim. | - Brzo æe te shvatiti.
{81384}{81412}Ja tu radim...
{81415}{81487}Samo diži noge!
{81565}{81611}Dobro ti ide.
{81780}{81839}Doði i ti!
{81842}{81891}Ne, samo daj!
{82075}{82106}Plešete?
{82109}{82202}Ne, gospoðo. | Mrvicu sam neraspoložen.
{82205}{82254}Rado, ali gležnjevi...
{82257}{82317}Ne budi mlakonja!
{82508}{82566}Isuse, bogme si | komad od žene.
{82600}{82641}Udata?
{82644}{82702}Isprièajte me trenutak.
{82909}{82968}Sekunde te ne mogu | ostaviti samog!
{82995}{83048}Idemo, srce. | Ovaj put ozbiljno.
{83104}{83141}Sad!
{83362}{83400}Daj! Daj! Daj!
{83899}{83945}Zgodno, krasno. Evo!
{84062}{84109}Hvala!
{84196}{84256}Evo, piæe za maloga...
{84259}{84355}Dame i gospodo, zauzmite | mjesta za obred vjenèanja.
{84358}{84458}Vaši su zavjeti | sveti i obvezujuæi.
{84461}{84518}Izmijenili ste prstenje
{84521}{84573}kao zalog vjeène ljubavi.
{84600}{84682}Proglašavam vas | mužem i ženom.
{84710}{84755}Možete poljubiti nevjestu.
{84825}{84875}Prekrasno...
{85149}{85228}Lijepa prièa. | Jako su se volje li;
{85231}{85297}Za to su pobjegli ovamo | i potajno se vjenèali.
{85300}{85338}Jako romantièno.
{85341}{85431}Vaši su zavjeti | sveti i obvezujuæi.
{85434}{85542}Izmijenili ste prstenje | kao zalog vjeène ljubavi.
{85545}{85642}Proglašavam vas | mužem i ženom.
{85645}{85709}Možete poljubiti nevjestu.
{86116}{86165}O... moj Bože!
{86190}{86227}O...
{86230}{86264}...moj...
{86267}{86309}...Bože...
{86333}{86367}Bože!
{86673}{86712}Budi se!
{86715}{86755}Budi se! Budi se! | - Jutro.
{86787}{86860}Lijepo molim da pogledaš | svoju lijevu ruku.
{86863}{86887}Molim te.
{86968}{87007}Ma vidi...
{87042}{87076}I ti ga imaš.
{87079}{87180}Daniele, jesmo li se | sinoæ vjenèali?
{87183}{87233}Da, nekako | osjeæam da jesmo.
{87236}{87318}Detalji su mutni, no mislim | da je mlada sjala
{87321}{87391}u Sereninoj haljini i...
{87394}{87433}Ti nisi sretna...
{87436}{87482}Izgledam li sretna?!
{87485}{87557}Teško je reæi. Nikad nisi | sretna uz mene
{87560}{87610}i kao da te stalno ljutim. | - Sve mi se vraæa...
{87613}{87698}Moramo reæi onome koji je to | uèinio da nismo to mislili.
{87701}{87743}Što ako ja jesam?
{87746}{87797}Jasno da nisi!
{87800}{87842}Kako bi se želio | mnome vjenèati?
{87876}{87948}Gðo Flanagan!
{88062}{88135}Kako znaš? | - Je li itko budan?
{88138}{88282}Još ne shvaæam. Kako cijeli | grad ne radi u èetvrtak?
{88285}{88343}Razvest æemo se u New Yorku,
{88346}{88404}kao da se nije dogodilo. | - Ali dogodilo se.
{88407}{88467}Dogodilo se nešto | puno veæe.
{88470}{88523}Mnogi se napiju | bez sudbonosnog "da".
{88526}{88593}Kada se sruše inhibicije, | èovjek postupa po osjeæajima.
{88596}{88680}Sanderson-Sanderson, | Vrhovni sud Illinoisa 1993.
{88683}{88737}Navodiš mi sluèaj | u potporu tog ludila?
{88740}{88789}Sinoæ smo se vjenèali, | zaboga!
{88792}{88817}To nešto znaèi.
{88820}{88882}Previše smo popili | i pogriješili. Opet.
{88911}{88962}U pravo vjenèani.
{88965}{88999}Èestitam!
{89002}{89052}Prestani govoriti okolo! | - Ona je prva.
{89055}{89110}Takve se vijesti šire.
{89113}{89150}Vratit æu se.
{89202}{89245}Moj Bože! | - Što?
{89248}{89299}Ne možemo se vjenèati i | biti suparnièke strane.
{89302}{89368}Zašto? Mogu nešto reæi? | - Smijat æe nam se.
{89371}{89400}Ne možeš!
{89403}{89470}Zašto? - Smijat æe nam se cijela | Njujorška odvjetnièka udruga!
{89473}{89539}Ti æeš se usprotiviti. | - Ovo je i moj brak!
{89542}{89608}Shvaæaš me? | Ubija me glavobolja!
{89749}{89800}Ma gle...
{89803}{89885}Odbila si momèiæu nogu.
{89888}{89929}Sad je beznog.
{89977}{90018}Sviða mi se.
{90021}{90072}Htio sam ga | saèuvati za uspomenu.
{90266}{90298}Oprosti, Daniele.
{90567}{90621}Poznajem te 35 godina.
{90624}{90715}Alkohol loše utjeèe na | tebe. Postaneš hiperaktivna,
{90718}{90756}agresivna, udana.
{90759}{90799}Nikome ni rijeèi!
{90802}{90881}Moram doznati zakone | one opæine.
{90884}{90936}Traži razvod ovdje.
{90939}{91016}Pametno! Za 2 sekunde svi bi | znali da sam se napila,
{91019}{91109}udala i razvela | u roku od 24 sata.
{91112}{91203}Obzirom na moje ogromno | razvodnièko iskustvo,
{91206}{91250}znam da ima puno | mjesta za manevar.
{91253}{91343}Sve možeš poništiti | sve dok se niste...
{91346}{91369}Zaboravi...
{91372}{91430}Rano ujutro odmah | poèinjem manevrirati.
{91501}{91543}Majko, što je ovo?
{91546}{91621}Cure i ja kasnije | imamo mali tulum.
{91624}{91672}Možeš se pridružiti.
{91675}{91749}Davide nam vadi salo iz | guze i ubrizgava u usne.
{91752}{91823}Eto posve novog znaèenja | izreke "govoriš iz guzice"!
{92037}{92131}Prije zahtjeva za razvod | zaviri u New York Post.
{92134}{92159}Što?!
{92396}{92437}Ideš po primjerak?
{92470}{92525}ZAKONSKI VJENÈANI | Zašto si im rekao?
{92528}{92553}Jesi li ti lud?
{92556}{92625}Misliš da sam ja? | Zašto bih?
{92628}{92706}Nakon što si rekla da ti | je brak posljednja stvar.
{92709}{92749}Naroèito sa mnom.
{92752}{92789}Smijem?
{92792}{92819}Zašto?
{92822}{92904}Javit æu Postu da su | pogriješili. Ili da smo mi.
{92907}{92948}Što da kažem?
{92951}{93031}Molim te, odloži slušalicu.
{93034}{93125}Nikoga ne želim | povrijediti.
{93128}{93211}Samo trenutak poslušaj. | Vjeruj mi.
{93249}{93312}Onako kako ti | vjeruješ meni?
{93315}{93368}Dobro, slušaj.
{93371}{93427}O braku smo, svidjelo | nam se to ili ne.
{93430}{93500}Èini se da se stvar | zbila pomalo naprasno.
{93503}{93546}Ja krivim ono piæe.
{93549}{93635}Opet smo u New Yorku i to | suprotstavljeni u sluèaju,
{93638}{93702}i bez obzira na naš buduæi | postupak, kratkoroèno...
{93705}{93731}Slažem se.
{93734}{93784}Što? | - Slažem se.
{93787}{93837}Kratkoroèno nam | jedino to preostaje.
{93840}{93889}Nisam rekao što sam htio.
{93892}{93969}Da se moramo praviti da smo | u braku zbog naših karijera.
{93972}{94074}Dakle preostaje | samo jedno pitanje, ne?
{94130}{94168}Oprosti na osjeæajima,
{94171}{94222}no o ovome sniva | svaka majka...
{94225}{94300}O danu kad joj kæi na vrata | svoje sobe stavlja bravu
{94303}{94339}kako joj ne bi ušao muž.
{94342}{94424}Ma prestani! Možda je bilo | vjenèanja, ali to nije brak.
{94590}{94639}Ja sam muž.
{94642}{94691}Ja sam majka.
{94862}{94924}Ovo je vaša soba. Naèinila | sam mjesta u ormaru,
{94927}{94995}premda mi se èini da ti | nikad ništa ne vješaš.
{95026}{95070}Spavaæa soba je tu.
{95073}{95122}Opet je ona stara. | Djeluje obeæavajuæe.
{95125}{95193}Ne trebamo odvojene sobe, | ne smeta mi kad hrèeš.
{95196}{95269}Smijem u kuhinju? | - On kuha? To mi nisi rekla.
{95360}{95447}Zadnjih par dana je èudna. | Veæ se ona doæi sebi.
{95450}{95523}Ne bih li ja | to trebala reæi vama?
{95526}{95606}Uživao sam o vama èitati | na društvenim stranicama.
{95609}{95658}Stvarno imate 56 godina?
{95661}{95707}Neki moji dijelovi da.
{95710}{95769}Koktel? | - Da, molim vas.
{95772}{95833}No samo ako je ogroman.
{96315}{96360}Naèinio sam kekse.
{96403}{96475}Ostavila sam slatko. | Bio mi je oslonac.
{96736}{96776}Što?
{96779}{96825}To æeš nositi?
{96828}{96879}Što tome fali? | - Ništa...
{96882}{96926}Samo...
{96929}{96995}...nešto nedostaje.
{97260}{97302}U braku smo, sjeæaš se?
{97305}{97402}Moramo se praviti da mislimo | ozbiljno. Makar ne bilo tako.
{97522}{97551}Pusti meni...
{97921}{97977}Pa... reci nešto.
{98149}{98200}I sebi si kupio?
{98378}{98418}Hoæeš da ja ili...
{98421}{98471}Mogu ja.
{98765}{98805}Eto...
{98808}{98853}Sad svakoga | možemo prevariti, ne?
{98895}{98942}Valjda.
{99008}{99069}U redu, tišina!
{99360}{99396}Evo... | - Hvala.
{99399}{99451}Nema na èemu.
{99497}{99546}Šuti i slušaj!
{99626}{99685}SUSHI ILI TALIJANSKA | ZA VEÈERU??
{100458}{100512}Èetiri milijuna?
{100515}{100556}Aspen?
{100559}{100601}Ajme...
{102529}{102588}Ne samo da je Serena | obnavljala i ukrašavala,
{102591}{102670}da, doista spašavala | Caislean Cloiche,
{102673}{102717}obnovila je vrtove,
{102720}{102763}posegnula u zajednicu
{102766}{102875}i vlastoruèno oživjela | drevnu tekstilnu industriju,
{102878}{102925}ulažuæi dohodak | u gospodarstvo.
{102928}{102977}Da, ulagala je i u vrtlara!
{102980}{103027}Nabijem te!
{103057}{103115}Gðice Woods, | ako ga ne ušutkate...
{103118}{103204}Moj štiæenik tek primjeæuje | kako, dok je on naporno radio
{103207}{103316}da bi platio za dvorac, ženini | postupci nisu bili èovjekoljubni.
{103319}{103354}Ako se radi o nevjeri,
{103357}{103462}rado æemo podastrti raèune | obilaska bordela.
{103556}{103588}Lijepo!
{103591}{103679}U redu! Tišina!
{103682}{103712}Zašto je to važno?
{103715}{103816}Gða Jamison nije zaslužila | 3 milijuna vrijedan dvorac
{103819}{103896}samo zato što je objesila | poneki zastor.
{103899}{103933}Zašto njoj odbiti nauèeni | standard življenja ako je
{103936}{104056}muž dao 4 milijuna za | gnjezdašce ljubavnici!
{104238}{104289}Odakle to znate?
{104317}{104362}Ja...
{104365}{104455}Rekoh da nikome | ne kažete za Aspen!
{104476}{104529}A ono odvjetnik-štiæenik | sranje?!
{104532}{104587}Neæu trpjeti takvo | ponašanje u sudnici!
{104590}{104658}Èak ne znaš skijati! | - Zaèepi, majmunice!
{104942}{105013}Želim razvod.
{105454}{105514}Bilo je sluèajno, | kunem se.
{105517}{105583}Bacao sam smeæe, | rasparala se vreæa...
{105586}{105631}Ne vjerujem ti.
{105707}{105750}Znaèi...
{105793}{105845}Želiš razvod? | - Da.
{105848}{105938}Jedna razmirica i gotovo, | baš kao i naša klijentela.
{105941}{106031}Ne nabacuj mi se svojim | pogledima na život i brak.
{106034}{106123}A profesionalni uèinak | koji tako oèajno izbjegavaš?
{106214}{106248}Dakle...
{106276}{106319}Ja u razvod ne vjerujem.
{106322}{106382}Kako to možeš reæi? | Živiš od njega!
{106385}{106436}To je posao.
{106471}{106548}No što vidimo kod tih | bijednih parova?
{106551}{106611}Sebe! Ljude koji su | grdno pogriješili!
{106614}{106666}Ne! Vidimo ljude koji se | ne žele boriti.
{106669}{106742}Za uvjerenje se treba | boriti, pošteno ili prljavo.
{106745}{106829}Neka se za brak bori onaj | tko je u braku koji želi!
{106832}{106863}Ja jesam! | - Sereš!
{106866}{106944}Ne! Znaš što? Ja u braku | nisam da spasim karijeru.
{106947}{107024}Oprosti na razoèaranju, no | fuæka mi se za karijeru.
{107105}{107141}Meni je stalo do tebe.
{107208}{107288}Ipak æu ti rado | dati razvod, jer,
{107291}{107350}reci da sam staromodan,
{107353}{107401}ali kad nekoga voliš,
{107429}{107537}valja biti nesebièan | i dati mu što želi.
{107654}{107711}Svratit æu po svoje stvari.
{109038}{109087}Halo? | - Mama?
{109475}{109535}Halo? | - Saro? Arlene...
{109538}{109596}Mogu te zvati kasnije? | Kod mene je Audrey.
{109763}{109856}Nemoj živjeti izbjegavajuæi | greške koje sam ja naèinila.
{109859}{109907}Živi svoj život.
{109910}{109954}Miliš da si ga stvaram?
{109957}{110005}Ne znam što da kažem.
{110008}{110069}Ponestaje mi usluga.
{110072}{110206}Znaš li koliko je teško | objaviti nešto u Postu?
{110370}{110411}Sve æe biti dobro.
{110592}{110683}Jutros me nazvao Thorneov | 12-godišnja pomoænica.
{110686}{110751}Ne znam odakle mu moj broj, | nije u imeniku.
{110774}{110874}Javlja da vaš štiæenik | danas neæe doæi na sud
{110877}{110933}i da se vratio | u svoj dvorac u Irskoj.
{110936}{111038}Kako još nikome nije | dodijeljen, to je zabranjeno.
{111041}{111104}Dajem vam 24 sata da ga | vratite ili prekidam sluèaj
{111107}{111178}zbog nemoguænosti nastavka.
{111210}{111254}Je li vam dobro?
{111282}{111324}Jest.
{111579}{111621}Dobrodošli natrag!
{111624}{111666}Gðo Flanegan, | je li tu g. Jamison?
{111669}{111714}O, moj Bože!
{111717}{111742}Ajme, ne!
{111745}{111790}Životinjo!
{111904}{111959}O, Bože! Jeste li...
{112006}{112053}Oprostite, mislila sam...
{112056}{112096}Vrištali ste.
{112099}{112143}A vi ne?
{112146}{112184}Fora, komad!
{112187}{112226}Da, ne... ovaj...
{112229}{112304}Došli smo svako | svojim avionom
{112307}{112442}i baš smo sve htjeli | razvaliti, kadli gða F.
{112445}{112526}Doðe i reèe: "Sretna | godišnjica". - Sedam godina.
{112529}{112586}Bio je još beba...
{112589}{112669}Tu smo se vjenèali. | U obližnjem selu.
{112672}{112720}Odluèili smo se potruditi.
{112723}{112778}Što bilo... | - Ne smijete odustati.
{112781}{112835}Posve se slažem.
{112956}{113000}Audrey...
{113068}{113123}Što vas dvoje | uopæe radite tu?
{113126}{113232}Došla sam vam reæi da | ne smijete biti ovdje.
{113235}{113270}Da, ali smo tu.
{113273}{113323}Pa mi smo vlasnici.
{113326}{113385}Ipak hvala što ste | prešli sav taj put.
{113388}{113420}Michael!
{113423}{113466}Morate nešto ponjupati.
{113498}{113528}Izvolite...
{113531}{113559}O, živjeli!
{113562}{113616}Pa to ste vi!
{113619}{113678}Kako je?
{113681}{113776}Recite gði Flanegan da | imamo još dvoje na veèerinki.
{113779}{113805}Nema problema.
{113808}{113859}I tu radite?
{113887}{113921}Kao i gdje još?
{113924}{113957}Kao sveæenik.
{113990}{114089}O, shvaæam! Stari festival... | Ma ne!
{114092}{114146}To radim iz zabave.
{114149}{114223}Ja samo imam | sveæenièku vanjštinu.
{114226}{114332}Znaèi... niste pravi sveæenik?
{114335}{114370}Zaboga, ne!
{114373}{114478}No ako to želite | obaviti za stvarno...
{114481}{114527}Uvijek prepoznam | one koji žele.
{114578}{114613}Èestitam.
{114656}{114686}Dakle...
{114689}{114736}Znaèi da...
{114739}{114773}O, ne, Bože!
{114881}{114914}Dakle...
{114917}{115077}...zadnje što ovdje nekome | treba jest odvjetnik za razvod.
{115173}{115240}Neæu ostati na veèeri, | ako ne zamjerate.
{115407}{115448}Oprostite...
{115625}{115701}Pa, hvala.
{115704}{115798}Oboje ste bili sjajni.
{115801}{115890}Pojma nisam imao da je | zakonski sustav tako dubok.
{115893}{115923}Jeste li dobro?
{115926}{115990}Ne, ne bih rekla.
{115993}{116063}Znate što ja mislim?
{116066}{116114}Mislim da ste se vas dvoje | ljubavnièki sporjeèkali.
{116142}{116220}Da, jesmo, na neki naèin.
{116223}{116265}Treba to prebroditi.
{116268}{116337}Pa vi ste nam rekli | da loše treba prebroditi.
{116340}{116387}Da je raskid posljednja stvar.
{116390}{116434}Ili tako nešto.
{116490}{116530}Jesam...
{116602}{116635}Hoæete li me povesti?
{116778}{116836}Put znaš? | - Znam li?!
{116839}{116899}Irsku znam kao svoj dlan!
{116902}{116946}Divovskim tragovima!
{116968}{117015}Paddyjevo raskrižje!
{117047}{117105}Preko mosta!
{117108}{117147}Natrag Paddyjevom | raskrižju...
{117150}{117210}Izgubili smo se. | - Nemoguæe!
{117213}{117269}Trebali smo prije | skrenuti desno. Sad znam!
{117272}{117310}Kad vam ide avion?
{117483}{117539}Je li poletio | avion za New York?
{117577}{117623}Pred dvije minute.
{117626}{117676}Je li u njemu Daniel Rafferty?
{117679}{117706}Žalim, ne smijemo...
{117709}{117772}Molim vas, budite momak | koji zna prekršiti pravila.
{117775}{117817}Bar jednom.
{117820}{117889}Jako mi je važno.
{117923}{117949}Kažete Rafferty?
{117952}{117992}Da.
{118053}{118120}Jest. Trebali ste biti s njim?
{118162}{118210}Jesam...
{118252}{118305}Kada je iduæi let za New York?
{118803}{118920}Znaš li da je 80 posto žena | koje ne žele vezu
{118923}{118971}zapravo usamljeno?
{119064}{119095}Jesi li i ti?
{119136}{119189}Bila sam.
{119192}{119364}Govoriš da se treba boriti | za spas braka, ne popuštati.
{119442}{119484}Da.
{119543}{119585}Stvarno u to vjeruješ?
{119648}{119690}Da.
{119726}{119765}Jako.
{119806}{119848}Zašto?
{119851}{119900}Pa...
{119956}{120022}...želiš se boriti?
{120045}{120111}Ne samo da moram trpjeti | vaše svaðe
{120114}{120213}ti je kom radnoga tjedna, | sad me još muzete iza vikend?!
{120249}{120321}Pa kad smo veæ tu,
{120324}{120440}odvjetnice Woods, | nešto bih vas pitala.
{120443}{120507}Uzimate li ovoga èovjeka | za zakonita muža?
{120510}{120568}Hoæete li ga voljeti, | brinuti za njega,
{120571}{120707}poštivati ga i štiti, | biti vjerna samo njemu?
{120815}{120866}"Da"... | - Znam što trebam reæi.
{120900}{120960}Ja sam joj majka.
{121039}{121080}Da.
{121083}{121125}I ja.
{121128}{121188}Do vas još nisam stigla! | - Oprostite...
{121191}{121291}Želite uvrijediti sud | na vlastitu vjenèanju?
{121294}{121340}Nipošto.
{121407}{121447}Odvjetnièe Daniele | Rafferty,
{121450}{121530}uzimate li ovu ženu | za zakonitu suprugu...
{121533}{121615}...ovlaštenju države New | York, proglašavam vas
{121618}{121696}mužem i ženom.
{121699}{121755}Možete poljubiti nevjestu.
{122269}{122326}Evo... za stara | dobra vremena.
{122329}{122393}Kako bih mogao odbiti?
{122422}{122482}Možda da zatvorite šiber?
{122485}{122570}79 posto je vjerojatno | da æe u pola sata kišiti.
{122573}{122629}Pratim prognoze...
{122630}{123040}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan  
