{1}{1}25.000
{1382}{1448}Napokon. | - Što je bilo?
{1452}{1517}Curica od nekih 6 g. | Moraš to vidjeti.
{1521}{1565}Možda ima veze | s tvojim sluèajem.
{1565}{1630}Ugurana je u nekakvu rupu. | Pokušat æe je izvaditi.
{1633}{1707}Forenzièari su unutra | od 15 h. Nije ugodno.
{1710}{1762}Unutra je danima, | možda i tjednima.
{2035}{2141}Našli smo ovo. | Zato sam te zvao.
{2231}{2321}Ostat æu. Trebam zraka. | Idem popušiti cigaretu.
{2350}{2379}Nisi prestao pušiti?
{2416}{2483}Polako uði. Treba | imati dobar želudac.
{2556}{2736}Stavi ovo. Siði i prati traku. | Rupa je puna nekakve kiseline.
{2740}{2824}Nitko ne zna toèno što je. | Ima sranja posvuda.
{5452}{5580}BEZIMENI
{5853}{5891}Molim?
{5919}{5957}Da, ja sam.
{6024}{6056}Što?
{6317}{6395}Dobro. Koja je adresa?
{6487}{6527}Dolazimo odmah.
{6652}{6816}Što je bilo? - Policija. | Našli su tijelo djevojèice.
{6869}{6945}Nisu je identificirali, ali...
{6999}{7055}Mogla bi biti Angela.
{7114}{7152}Idemo.
{7271}{7344}Pogledaj ovo. | Ima ih po cijelome tijelu.
{7373}{7432}Provukli su igle i | ostavili su ih unutra.
{7474}{7570}Ali zašto? - Ne znam. | Još je bila živa.
{7617}{7704}Ima zgrušanu krv | u skoro svim otvorima.
{7708}{7784}Imat æemo problema | i s opeklinama.
{7788}{7905}Èime ju je opekao? | - Vjerojatno kiselinom
{7916}{8004}koja se upotrebljava | u industriji. Jako je otrovna.
{8024}{8158}Obuci se, èekaju nas.
{8217}{8329}Hajde, moramo iæi.
{8368}{8461}Uništili su joj sve dijelove | za moguæu identifikaciju.
{8491}{8586}Kao da je selektivno izgorena.
{8617}{8696}Pogledaj joj zube. | Uništili su ih namjerno.
{8701}{8813}Kao neko nagrizanje. | Nije ostalo ništa.
{8817}{8862}Dobro su nam otežali stvar.
{8866}{9030}Ne, èekaj. Desna bedrena | kost je 4 cm kraæa.
{9059}{9165}Isto kao i djevojèici | iz tvoga sluèaja.
{9548}{9653}Da nije htio da je prepoznamo, | ne bi propustio ovakvo što.
{9681}{9713}Zašto su je onda | ovako zapalili?
{9757}{9831}Možda misle da identitet | smræu gubi smisao.
{9863}{9925}Nije rijetko | u obrednim zloèinima.
{9956}{10024}Da, mislim da je ona.
{10066}{10149}Našli su i narukvicu s | njezinim imenom blizu tijela.
{10181}{10249}Pun pogodak. - Još je treba | identificirati obitelj.
{10281}{10321}Stigli su roditelji.
{10370}{10480}Massera, ne idi previše | u detalje. Nije vrijedno.
{11334}{11457}Nije ona, ha? | - Morate ovo identificirati.
{11634}{11748}Gðo Gifford, je li ovo | narukvica vaše kæeri?
{11752}{11858}Njezina je. Moram | vidjeti da je to ona.
{11862}{11974}Imate pravo na to, | ali ja vam ne savjetujem.
{11979}{12060}Ne muèite se. Neæete je | moæi prepoznati.
{12072}{12148}Zašto ste onda | sigurni da je ona?
{12152}{12247}Ima kraæu nogu. | Nema sumnje, ona je.
{12305}{12407}Ne! Što su napravili | mojoj djevojèici?!
{14318}{14406}5 GODINA KASNIJE
{14499}{14567}Kasnim, ha? - Malo. | Èekaju te unutra.
{14571}{14652}Hoæe vidjeti dijapozitive. | Èini se da im se ne žuri.
{14656}{14721}Dugo su unutra? - 5 min.
{14727}{14880}Da vidimo. Ispraviti, | ispraviti, ispraviti...
{14884}{14946}Napravi mi to do sutra. | - Pokušat æu.
{14948}{15006}I javi Toniju da mi donese | preostale fotografije.
{15008}{15063}Trebam ih do popodne. | Samo one nedostaju.
{15095}{15149}Izvoli. Vruæe je. - Hvala.
{15174}{15314}Na stolu ti je hrana za ribe. | - Ribe tebi duguju život.
{15748}{15796}Nedostaju neke s tetovažama. | Imat æemo ih poslijepodne.
{15803}{15925}Ima prijedloga za naslovnicu? | - Ne. Hoæu prvo imati sve.
{15929}{16000}Dobro. Javi mi | kad sve dobiješ.
{17362}{17463}Prekidam? - Ne. | Razmišljala sam.
{17465}{17527}Izvoli. Gotovo je. - Hvala.
{17553}{17596}Nisi taknula kavu.
{17627}{17670}Claudia, jesi dobro?
{17735}{17780}Da, nije mi ništa.
{17886}{17956}U ovo mi je doba godine | uvijek isto. Blesava sam.
{17960}{18017}Znaš da nisi.
{18087}{18166}Zašto se malo ne odmoriš? | - Imaš pravo.
{18227}{18289}Nemam pojma | što bih bez tebe.
{18301}{18405}Uzet æu slobodno poslijepodne, | i ti si kriva za to.
{20205}{20265}Claudia. - Zdravo. | Nisam te èula.
{20294}{20369}Izgledaš užasno. | Jesi dobro? - Da.
{20448}{20534}Dugo te nije bilo. | - Uz knjigu nemam baš vremena.
{20538}{20636}Voljela bih to privesti kraju. | - Ono s tetovažama?
{20641}{20759}Vidjela sam Tonija. | Rekao je da izlazite.
{20768}{20833}Da izlazimo? | - Da ste opet zajedno.
{20839}{20921}Molim? - Tako mi je rekao.
{20950}{21094}Koja budala. | - Claudia, što ti je?
{21725}{21825}Claudia, Toni je. | Zovem te èitav dan.
{21848}{21906}Navratit æu sutra...
{22860}{22975}Ne znam gdje je. 10 i 30 je. | Inaèe dolazi u 9, zar ne?
{22978}{23076}Obièno da. Možda | joj je nešto iskrsnulo.
{23087}{23175}Iskrsnulo? | Vjerojatno bi javila.
{23180}{23260}Možda. I meni je malo èudno.
{23305}{23413}Toliko je žurila oko slika, | a sada se ne pojavljuje.
{23417}{23486}Mislim da æe brzo doæi, | možeš je prièekati.
{23548}{23682}Èekat æu je u uredu. | - Radije je prièekaj ovdje.
{23708}{23816}Ovdje? Ranije je bilo | drukèije. - Eto, vidiš.
{23848}{23880}Vidim.
{23964}{24057}Zašto je ne nazoveš kuæi? | Možda je zaspala.
{24360}{24386}Da?
{24565}{24591}Molim?
{24906}{24981}Mama, mama...
{24996}{25122}Pogriješili ste. | - Ne, mama. J a sam.
{25427}{25573}Da? - Mama, ja sam. | Nemoj spustiti, molim te.
{25601}{25691}Moja je kæi mrtva. | - Nije istina.
{25696}{25820}Oni žele da to vjeruješ | ali nije tako. Doista, mama.
{25825}{25920}To nisam bila ja. | - Tko je to? Zašto ovo radite?
{25924}{25997}Mama, slušaj me. | Moraš mi vjerovati.
{26001}{26074}Ne mogu više prièati. | Vratit æe se.
{26078}{26181}J ako æe mi nauditi. | Moraš doæi po mene.
{26185}{26265}U sanatoriju na plaži. | Znaš gdje je to.
{26277}{26338}Ne zovi policiju, | bit æe gore.
{26343}{26472}Ubili bi me. Obeæaj | da neæeš nikome reæi.
{26480}{26560}Što je to? - Obeæaj mi.
{26958}{27006}NIJE MRTVA
{35128}{35190}Blažene oèi.
{35232}{35329}Nedostajao si mi. | - Da. Daj mi jednu.
{35397}{35509}Prestaješ otkad te znam. | - Još malo, osjeæam to.
{35569}{35657}Uskoro æu i na vježbe. | Bit æu kao nov, vidjet æeš.
{35662}{35691}Sigurno.
{35709}{35786}Slušaj, debeli je gore.
{35801}{35862}Neæe mu biti drago | ako te vidi ovdje.
{35865}{35954}Treba izbjeæi neugodnosti. | - Samo sam došao po stvari.
{35959}{36022}Da veæ jednom | završim s ovime.
{36026}{36061}Kako si? - Dobro.
{36147}{36172}Bolje.
{36203}{36297}Znaš što æeš napraviti? | - Da. Za sada ništa.
{36316}{36390}Veæ æu smisliti nešto. | Ne brinem se previše.
{36394}{36518}Ako bilo što trebaš, reci. | - Dobro. Znam.
{36541}{36596}Moramo izaæi jednu veèer. | Kao nekada.
{36601}{36642}Malo obiæi stara mjesta.
{36645}{36699}Da te podsjetim kako | si završio prošli put?
{36704}{36765}Koja budala. - Da, budala.
{36788}{36857}Nazovi me. I ne zaboravi | predati znaèku.
{36861}{36919}Èim je naðem, dat æu ti je.
{36957}{37059}Oprosti, Bruno. Imam | poruku za tebe. - Da?
{37063}{37151}Zvala je Claudia Gifford. | Ne znam sjeæaš li se. - Da.
{37157}{37227}Rekli su joj da te nema, | ali bila je uporna.
{37233}{37324}Glede njezine kæeri. | Ostavila je broj. Dolje je.
{37329}{37364}Dobro? - Hvala.
{37867}{37936}Zdravo. Hvala što ste došli.
{37966}{38090}Kako ste? - Nisam | oèekivala da æete doæi.
{38094}{38155}Sluèajno sam dobio | vašu poruku.
{38159}{38230}Veæ 2 tjedna nisam u policiji.
{38235}{38292}Samo sam navratio | po neke stvari.
{38296}{38339}Rekla mi je tajnica.
{38367}{38409}Dobro da sam vas našla.
{38683}{38796}Niste trebali iæi sami. | Moglo je biti opasno.
{38818}{38921}Što sam trebala napraviti? | Zanemariti to?
{38929}{39012}Znala sam o kojem se | sanatoriju radi.
{39017}{39087}Na tu smo je plažu | vodili kao malu.
{39092}{39242}I glas je bio slièan njezinu. | - Je li bilo hrane, odjeæe...?
{39249}{39348}Bilo je puno toga. | Na podu su bili madraci.
{39433}{39542}Ne znam, Claudia. | Kæi vam je mrtva.
{39548}{39693}Znate to koliko i ja. - Ne. | Ranije sam znala. Sada ne.
{39882}{39933}Našla sam ovo | u jednoj kutiji.
{40221}{40283}Bilo je tamo kako | bih ja to pronašla.
{40288}{40338}Sada više nisam | sigurna ni u što.
{40342}{40383}Ne znam više što misliti.
{40397}{40466}Jasno je da vas | netko želi muèiti.
{40471}{40574}Ne znam ni tko, ni zašto. | Vaša je kæi mrtva.
{40593}{40676}Ja sam vidio tijelo. | Bila je mrtva.
{40680}{40751}Sami ste rekli da ju je | bilo teško identificirati.
{40755}{40787}Možda je to bila | druga djevojèica.
{40791}{40831}Našli su narukvicu | vaše kæeri.
{40835}{40883}I ono s nogom. Nije bilo | sumnje. I vi to znate.
{40887}{40946}Ne, ja ne znam. | To sve nije dovoljno.
{40950}{40993}Nisam je ni vidjela.
{41063}{41110}Gdje vam je suprug?
{41136}{41218}Kratko nakon toga je | otišao. Nismo uspjeli.
{41222}{41290}Mislim da se vratio | u London. Nisam sigurna.
{41295}{41362}Nemam nikoga. | Sama sam u ovome.
{41461}{41571}Molim vas, pomozite mi. | Znate da ništa nije sigurno.
{41575}{41671}Samo želim biti sigurna. | Ovako ne mogu živjeti.
{41900}{41973}Dobro. Vidjet æemo što možemo.
{41992}{42082}Javit æu vam se. | Vi ne èinite ništa.
{42084}{42153}Ako se nešto dogodi, | odmah mi javite.
{42158}{42199}Ostavit æu vam broj.
{42282}{42326}Molim vas, nemojte | ništa reæi policiji.
{42330}{42369}Ne želim da se nešto dogodi. | - Budite mirni.
{42373}{42434}Neæemo ništa reæi. | Za sada je bolje.
{42443}{42508}Uèinite kako sam rekao. | Javit æu vam se.
{42525}{42583}Popijte to, ohladit æe se.
{44442}{44526}Teresa, Bruno Massera. | Kako si?
{44530}{44576}Èuj, trebam uslugu.
{44581}{44707}Znam, ali jako je važno. | Budi neprimjetna.
{44748}{44911}Trebam curice roðene izmeðu | 87. i 89. u Španjolskoj,
{44917}{44964}kraæe desne noge.
{44968}{45080}Da. 3 do 5 cm kraæa. Dobro.
{45116}{45187}Pošalji mi to faksom. | Imaš broj?
{45223}{45294}Da, znam. Dužnik sam ti.
{46465}{46513}Mama...
{48575}{48606}Dakle...
{48730}{48772}Da vidimo.
{48840}{48997}Evo ga. Aguirre. | Curica. Sigurno je ona.
{49008}{49151}Jako dobro. Treba mi | adresa obitelji. - Nemoguæe.
{49155}{49248}Ne možemo to otkriti. | To su povjerljive informacije.
{49289}{49383}Jako je važno. | - Jeste policajac?
{49399}{49596}Što se vama èini? | - Nema telefona. Samo adresa.
{49602}{49660}Dovoljna mi je adresa. | - Zapisat æu vam je.
{49804}{49837}Hvala.
{50366}{50394}Molim?
{50433}{50514}Toni. Ne mogu | sada razgovarati.
{50524}{50579}Ozbiljno, ne mogu.
{50617}{50681}Nisam dobro. | Imam problema. Dobro?
{50703}{50749}Svejedno, molim te.
{50796}{50834}Zbilja ne mogu.
{50926}{50957}Ne mogu.
{50959}{51090}Slušaj me... Slušaj! | Žao mi je za one slike.
{51094}{51145}Mogao si ih ostaviti | prije nego si otišao.
{51165}{51264}Ne, nazvala sam ured i | uzela 2 tjedna slobodno.
{51268}{51318}Nazovi moju tajnicu, | reæi æe ti isto.
{51334}{51390}Ne trebam ništa, zbilja.
{51460}{51547}Ne uzimam ništa. | A nije te ni briga.
{51555}{51617}Ne mogu više razgovarati. | Spustit æu slušalicu.
{51621}{51679}Spustit æu! Spustit æu!
{55946}{55995}Zdravo. - Što je bilo?
{56000}{56045}Tražim obitelj Aguirre. | - Molim?
{56051}{56128}Aguirre. - Ne, ovdje nema...
{56469}{56619}Dobro ste došli. Ako vas | zanimaju, pitajte mene.
{56629}{56791}Poznajete ih? - Živjeli su | ovdje, ali su otišli.
{56804}{56860}Izgubili su malenu i otišli.
{56863}{56964}Malu su im ukrali, | ili se izgubila, tko zna.
{56970}{57038}Zvali su je šepavica. | - Kada je to bilo?
{57042}{57171}Prošlo je dosta. Ja sam još | radio u tvornici. Zamislite.
{57175}{57246}Nekih 5 g?
{57266}{57471}Otišli su prije nekih 5 g? | - 5? Da, tako nekako.
{58241}{58323}Molim? - Claudia, | Massera ovdje.
{58327}{58446}Nešto sam otkrio. Èudno je. | Možda ste u pravu.
{58484}{58584}Molim? - Nisam siguran. | Nešto se ne slaže.
{58589}{58687}Uzmite taksi i èekajte me | kod Pontifica.
{58691}{58788}Dolazim za 1 h. Znam | tko nam može pomoæi.
{59055}{59128}Dovraga! - Gdje si? | Veæ sam pola sata ovdje.
{59132}{59169}Nije lako naæi. | Bogu je iza tregera.
{59173}{59264}Pusti prièe i na posao. | Veæ smo izgubili vrijeme.
{59276}{59366}Koja je? Nadam se da ne plaèu | sve. Sve je puno djevica.
{59369}{59441}Neæeš vjerovati. U redakciju | je zvao sakristan.
{59445}{59518}Nije baš bio upuæen. | Malo se zabunio.
{59522}{59587}A ako ne plaèe? | - Ne radi se o tome.
{59591}{59657}Itekako plaèe. | Ali nije djevica.
{59659}{59735}Što je onda? - Doði. Neæeš | vjerovati. Nisi to još vidio.
{59875}{59908}Dovraga!
{59923}{60003}Pazi na detalje. | Nemoj se zbuniti.
{60009}{60132}Slikaj i s oltara. Ja idem | razgovarati sa župnikom.
{60136}{60202}Malo me strah što æe reæi.
{60208}{60316}Ovo sam pronašao. | Ne piše tko šalje.
{60321}{60360}Mislim da je videovrpca.
{60366}{60456}Kada doðeš u redakciju, | pogledaj što je to.
{60471}{60548}Ako mi ostane vremena, | navratit æu.
{60578}{60655}Još sranja. Kao da | nam nije dovoljno.
{60710}{60788}Ovo je Green House | u Liverpoolu.
{60793}{60953}Prva kuæa u kojoj kažu da | su živjeli bezimeni. 1962.
{60990}{61114}Pogledajte anðele. | Uvijek su prisutni uz put.
{61119}{61208}Zbog toga sam ovo povezao | s vašim sluèajem.
{61212}{61280}Ovo je snimljeno u istoj kuæi.
{61284}{61343}To je jedan od | zidova na 1. katu.
{61374}{61521}Ovo je Santini, Argentinac. | Kažu da je on mozak svega.
{61525}{61634}Istièe se poèetkom 60-ih | meðu ezotericima u Londonu.
{61638}{61715}Tada su te stvari bile u modi.
{61720}{61810}Èini se da je Santini | sve to odveo puno dalje.
{61814}{61868}Htio je napraviti | vlastitu grupu.
{61871}{61969}Nekakvo tajno društvo | ili parareligiozna sekta.
{61973}{62040}Nije potpuno jasno. | - Što ti misliš?
{62143}{62248}Mislim da to nije prelazilo | obiène sastanke fanatika.
{62252}{62373}Santini i njegovi bili su jako | popularni tada u Londonu.
{62378}{62469}Zato je normalno | da kruže toliki traèevi.
{62475}{62658}Kakvi traèevi? - Govorilo se | o nestancima i otmicama.
{62664}{62759}Uvijek na razlièitim mjestima, | kako ih ne bi otkrili.
{62762}{62889}Što je bilo s tim Santinijem? | - Ima nešto zanimljivo.
{62893}{63017}Mislim da ga je 82. g. | Uhitila policija u Valenciji.
{63021}{63118}Sluèajno sam to doznao | i bilo mi je zanimljivo.
{63120}{63180}Nije se uspio puno proširiti.
{63185}{63248}Ne znam što je napravio, | ali je sigurno vrlo gadno.
{63251}{63297}Mislim da ga je stigla | dobra kazna.
{63303}{63346}Ne znam je li izruèen...
{63352}{63427}Što bi s jednom curicom | da im padne u ruke?
{63431}{63478}Ne zvuèi mi to moguæe.
{63483}{63602}Zamislimo da jest. | Bilo bi opasno? - Doðite.
{63667}{63753}Ovo je jedan od najvažnijih | teoloških pismohrana u Europi.
{63757}{63867}Možda ne po kvantiteti. | Ima spisa iz 11. st.
{63871}{63979}Autentiènih rariteta o | parareligiji i ezoterici.
{63983}{64038}Skoro sve je moderan | materijal, naravno.
{64049}{64146}Držimo to odvojeno. | Recimo da je to naš hir.
{64149}{64196}Ne bi svi to smatrali | jako ortodoksnim.
{64201}{64286}Imaš li nešto o tom tipu? | - Mora biti nešto.
{64321}{64408}Evo ga. Jedan od njegovih | prvih rukopisa.
{64412}{64503}Èasopis o ezoterici. | Izlazio je u Londonu 60-ih.
{64506}{64555}Moram ovo prevoditi...
{64558}{64637}Zlo možemo | znanstveno izolirati,
{64640}{64687}osloboditi svih predrasuda,
{64690}{64763}uništiti ljusku èovjeèanstva | koja ga izopaèuje.
{64767}{64915}Sakaæenje, muèenje... | predstavljaju put proèišæenju.
{64920}{64990}Sakrament krajnje okrutnosti.
{65003}{65088}Kao nekakva sinteza | apsolutnog zla.
{65093}{65144}Toliko monstruozan | barbarski èin
{65148}{65222}koji bi ih odveo na jednu | višu razinu svijesti.
{65226}{65379}Kao kljuè u uzvišenu razinu | moæi, užitka... Bez granica.
{65384}{65451}Jedna drukèija | formula svetosti.
{65465}{65563}Na kraju je sve jednako. | Ekstremi se dodiruju.
{65576}{65656}Koja ludost, idemo... | - Ima nešto zanimljivo.
{65660}{65726}Ne znam jeste li èuli | za društvo Thule.
{65730}{65774}Jedno tajno | okultistièko društvo
{65778}{65835}koje je bilo iza okultistièkog | kabineta nacista.
{65837}{65937}I Hitler je bio njegov èlan. | Zvali su ga medij.
{65941}{66061}Njegove su strepnje | podsjeæale na to.
{66065}{66144}Može li postojati neka veza? | - Ne. Sigurno ne.
{66149}{66215}Bile su to | univerzalne strepnje.
{66219}{66271}Ima stotine sliènih primjera.
{66275}{66363}Što imaju anðeli s time? | - Ovdje ima nešto...
{66389}{66443}Lutat æe izgubljeni | i bolesni,
{66445}{66536}lišeni imena, | jer ime je rijeè,
{66540}{66602}a rijeè je instrument laži.
{66615}{66671}Odatle bezimeni.
{66676}{66735}Odbacivanje imena kao | da je nekakav nedostatak,
{66739}{66807}koji nas veže za | naše ljudsko porijeklo.
{66810}{66881}Vidite. Maštarije bolesnika.
{66885}{66965}Ja nisam vidjela kuæu | s anðelima. Bila sam tamo...
{66971}{67076}U što si se uvalio? | Rekli su mi da si ostavio to.
{67080}{67133}Napravit æe joj nešto | strašno. Ne vidiš?
{67139}{67204}Za to su je htjeli. | Zato su mi je uzeli.
{68350}{68459}Ništa. - Možda je sve | samo jedna šala.
{68473}{68578}Možda i nije. Ne znam. | Ne sviða mi se to.
{68607}{68686}Probaj još jednom. | Možda si se zabunio.
{70701}{70759}SANTINI OSUÐEN NA 80 g.
{71380}{71420}Zdravo. - Zdravo.
{71424}{71500}Tražio sam informacije | o tome Santiniju. - I?
{71528}{71632}Ništa. Uhvatili su ga zbog | maltretiranja maloljetnika.
{71636}{71694}Gdje je? - Ne znam. | Vjerojatno zatvoren.
{71697}{71751}Vidi se da je još | netko bio upleten.
{71755}{71806}Ali su ga pustili | zbog nedostatka dokaza.
{71810}{71863}Sigurno ima još nešto.
{71866}{71964}Juèer me zvao novinar iz | èasopisa o parapsihologiji.
{71968}{72022}Rekao je da ima nešto | što bi me moglo zanimati.
{72026}{72089}Što? - Ne znam. | Èinio se nervozan.
{72093}{72147}Rekao je da ima veze sa mnom | i da doðem pogledati.
{72151}{72195}Imaš adresu? - Da.
{72240}{72329}Dobro. Idemo. | Nemamo što izgubiti.
{72764}{72844}Vaš je broj bio na kaseti. | Zato sam vas zvao.
{72849}{72945}Što je to? - Ne znam. | Vi æete mi objasniti.
{72966}{72995}Idemo pogledati.
{73109}{73160}Znaš što sam ti rekao.
{73754}{73860}Što je ovo? | - Ono što se vidi.
{73874}{73940}Što ja imam s time? | - Ima još.
{73975}{74025}Vi ste na snimci. - Ja?
{74584}{74671}Bili su tamo. | - Samo malo. Što se dogaða?
{74677}{74790}Tko još zna za ovo? | - Samo ja i moj šef.
{74816}{74841}Zašto?
{74869}{74973}Bilo bi dobro da nam pomogneš. | Razmisli. - Pomognem u èemu?
{75211}{75287}Što je tebi? | - Nije baš tako strašno.
{75291}{75386}Naravno. Ti misliš da nije. | Slušaj, svi znamo što je.
{75390}{75448}Naši èitatelji to | ne žele èitati.
{75452}{75541}Piši što žele, i gotovo. | Tebi je svejedno, a i meni.
{75545}{75589}Ima problema? | - Nema. Sve je u redu.
{75593}{75701}Izvrsno. Napiši to za sutra | i ne zafrkavaj me više.
{75773}{75852}Znaèe li ti nešto bezimeni? | - Èemu to sada?
{75866}{75930}Sigurno ima veze s ono dvoje.
{75966}{76048}Èini mi se da sam nešto | èitao u prvim brojevima.
{76054}{76123}Mislim da smo nešto imali. | Prije nekoliko godina.
{76127}{76188}Mislim da je bio Romero. | Ti ga ne poznaješ.
{76193}{76353}Bio je ovdje do 82. ili 83. g. | Bio je zadubljen u sve to.
{76358}{76491}Bio je neèemu na tragu. | Slušaj, pažljivo s time.
{76507}{76636}Ono na videu je gadno. | To je za policiju. Znaš?
{76672}{76799}Zato su nama poslali vrpcu. | Misle da je Romero još ovdje.
{76819}{76898}Prokletnici. - O èemu ti to?
{76935}{77032}Kako mogu do njega? | - Do koga? - Romera.
{77119}{77193}Nadam se da znaš | u što se uvaljuješ.
{77208}{77273}Sigurno piše u rokovniku. | Pogledaj.
{77276}{77332}Ali, nemoj se sada | uvaliti u tu prièu.
{77336}{77424}Imamo do ponedjeljka. | Hoæu ovo gotovo za sutra.
{77554}{77620}Idemo, kasno je.
{77676}{77719}Zakljuèaj, dobro?
{78578}{78618}Još imam posla.
{78621}{78701}Dok se ne dogovore, | ne mogu se maknuti.
{78705}{78746}Neka idu k vragu. | - Što se dogodilo?
{78750}{78791}Jedna djevojèica je izletjela.
{78795}{78849}Èini se da se nije zatvorio | sigurnosni sustav. - Dovraga.
{78853}{78980}Treba pronaæi pogrešku. | Moram ostati ovdje.
{79015}{79093}Dobro, i što si postigao?
{79100}{79197}Ne znam u što si se uvalio, | ali mi se nimalo ne sviða.
{79203}{79264}Kojeg si kretena tražio.
{79269}{79319}Uhvatili su ga jer je | zlostavljao dvije djevojèice.
{79322}{79396}Silovao ih je | dok se igrao nožem.
{79399}{79452}Odrezao im je | nekoliko prstiju.
{79456}{79500}Ti ljudi nisu s ovoga planeta.
{79504}{79562}Stavljaju si zapaljenu | vatu u guzicu.
{79567}{79635}Upoznao sam ih nekoliko. | - I gdje je sada?
{79651}{79736}Zatvoren je u ustanovi | nedaleko Huesce.
{79740}{79830}Sveto Trojstvo, odjel B. | Na posebnom je tretmanu.
{79836}{79890}U paviljonu poremeæenih.
{79903}{79965}Idi sutra. Nazvao sam | nekoliko ljudi.
{79971}{80029}Reci da dolaziš u moje ime. | Mislim da æe te pustiti.
{80032}{80191}A ono drugo? - To me može | uvaliti u velike probleme.
{80204}{80339}Smiri se. Pitam te samo | iz predostrožnosti. U redu je.
{80343}{80403}Èuvaj se.
{80926}{81036}Rekao sam da hoæu | u komadiæima.
{81043}{81094}Ne mislim ovo jesti.
{81121}{81182}Samo mi recite gdje | da naðem informacije.
{81197}{81278}Sve ovo o bezimenima... | Sigurno znate nekoga.
{81491}{81628}Bio je neki njemaèki lijeènik. | Bolggen ili Bolgger.
{81654}{81755}On se javio meni. | Bio je neurolog.
{81768}{81867}Nikad nisam vidio nekoga | toliko prestrašenog.
{81904}{82027}Bio je savjetnik u njemaèkom | Institutu za higijenu u ratu.
{82071}{82171}Radio je na lijeènièkim | pokusima u Dachauu.
{82176}{82350}Nešto u vezi s nacistièkim | Odjelom za kemiju i farmaciju.
{82356}{82467}Rekao je da ga je taj Santini | zvao da doðe iz Njemaèke
{82471}{82565}kako bi financirao | jednu njegovu istragu.
{82578}{82666}Nešto o vladavini boli.
{82757}{82964}Santini ga je stavio | u nekakvu ezoterièku grupu.
{82970}{83076}Prisilio ga je da radi | pokuse na ljudima.
{83081}{83155}Èini se da su neèemu | bili na tragu.
{83195}{83275}Na kraju se previše | zakompliciralo
{83278}{83345}i Santini je završio | u zatvoru.
{83350}{83407}Lijeènika su pustili | zbog nedostatka dokaza.
{83410}{83537}Tako je. Tada me nazvao. | Bio sam kod njega.
{83539}{83599}Još se sjeæam adrese.
{83615}{83717}Bio je toliko prestrašen, | nije htio izaæi iz kuæe.
{83722}{83840}Uvalio se u to sranje | s bezimenima.
{83845}{83943}Ako je Santini bio zatvoren, | koga se onda bojao?
{83947}{83997}Ostalih.
{84031}{84141}Svih ostalih. | Onih koji nemaju ime.
{85665}{85701}Što je ovo?
{86435}{86562}Tko je to? | - Smirite se. Slušajte.
{86566}{86631}Želim da mi prièate o | bezimenima. Jako je važno.
{86634}{86730}Ne, molim vas. Pomozite mi. | Netko se nalazi u zidovima.
{86733}{86780}Slušajte me. Smirite se.
{86784}{86904}Znam gdje su. Pomozite mi, | pa æu vam reæi.
{87892}{87939}Ja sam, Toni.
{87977}{88022}Morao sam te vidjeti.
{88027}{88133}Što radiš ovdje? Jesi poludio? | Skoro sam umrla od straha.
{88152}{88261}Žao mi je. Evo, | donio sam ti fotografije.
{88266}{88333}Izvrsno. Imam ih, sada idi.
{88338}{88446}Èekaj, hoæu razgovarati | s tobom. - Ja s tobom ne.
{88455}{88596}Ne znam što ti je, | i zašto ne ideš na posao.
{88602}{88701}Ali, ako imaš | problem, reci mi.
{88707}{88778}Neæu da se opet vratiš | tabletama. Razumiješ?
{88783}{88896}Ne razumijem. Odlazi. | Ništa ti ne moram reæi.
{88900}{88938}Veæ više od godinu dana | nismo zajedno.
{88941}{88977}Nikako da shvatiš. | Ne mogu vjerovati.
{88980}{89028}Ne diraj me. - Slušaj me!
{89046}{89126}Nije me briga | s kime si, a s kime nisi.
{89129}{89203}Neæu dopustiti da | ti se nešto dogodi.
{89208}{89275}Pazit æu te. Razumiješ? | - Pijan si.
{89279}{89402}Jesam. I što? Pazit æu te, | htjela ti to ili ne.
{89405}{89488}Vidio sam te s onim tipom. | Izgledala si kao drolja.
{89491}{89608}Idi k vragu. Odlazi! | - I dalje æu te pratiti.
{89679}{89742}Neæeš me se osloboditi.
{89753}{89808}I dalje æu te pratiti.
{89841}{89914}Ne znaš za što sam sposoban.
{89918}{89962}Nemaš pojma.
{90954}{91029}Tko je? - Ja sam, Claudia.
{91131}{91222}Što se dogodilo? - Nisam | više mogla biti kod kuæe.
{91222}{91287}Nisam znala kamo iæi. | - U redu je. Uði.
{91418}{91512}Još se nisam smjestio. | Sve je razbacano.
{91517}{91640}Hoæeš nešto popiti? | - Ne. Slušaj, žao mi je.
{91644}{91706}Ne znam hoæu li moæi | izdržati još dugo.
{91710}{91799}Bojim se da æu poludjeti. | - Ne misli više na to.
{91803}{91842}Ovdje æeš biti sigurnija.
{91845}{91913}Možemo se izmjenjivati | na sofi.
{91920}{92018}Htio sam te nazvati. | Našao sam Santinija.
{92021}{92085}Sutra idemo do njega. - Sutra?
{92116}{92237}Ima više od 200 km. | Moramo se odmoriti.
{92242}{92295}Idem potražiti pokrivaè.
{92389}{92451}Stavi glazbu ako hoæeš. | Jedino toga ima napretek.
{92455}{92495}Na stolu je.
{92774}{92870}Tko je ovo? - Tko? | - Na fotografiji.
{92955}{92987}Moja žena.
{93058}{93132}Umrla je prošle godine. | Koje sranje, ha?
{93187}{93278}Kupio sam joj ovaj CD, | toèno na dan kada...
{93477}{93583}Oprosti. Jako mi nedostaje.
{93596}{93649}Zato mi pomažeš, je li tako?
{93664}{93733}Misliš da æeš time | spasiti nju, ali nije tako.
{94173}{94291}Kamo ideš? Još èekam èlanak. | - Žao mi je. Sada ne mogu.
{94295}{94388}Kako ne možeš? | Dobivaš plaæu, kao i svi.
{94391}{94456}Slušaj, nešto sam našao. | Nešto veliko.
{94460}{94532}Nikakva èaranja | i usrani horoskopi. Kužiš?
{94535}{94577}Napokon imam nešto | što me doista zanima.
{94581}{94614}Zar ne razumiješ?
{94618}{94731}Od tih sranja jedemo. | Zato se ostavi tih prièa.
{94735}{94838}Obièan si smrtnik kao | i svi mi. Prihvati to.
{94849}{94934}Ako odeš, ne vraæaj se. | Ozbiljno ti govorim.
{94939}{94985}Idi do vraga!
{95335}{95401}Možda misliš da sam | jedan od onih pedera
{95405}{95476}koji si stavlja rinèice | na kurac ili na guzicu.
{95516}{95603}Ako to misliš, | ništa ne razumiješ.
{95622}{95667}Daj ušuti malo.
{95779}{95836}Inzistirao je na | razgovoru s njom.
{95840}{95895}Vi radije ostanite vani, | ili neæe ništa reæi.
{95899}{95991}Kako je to mogao znati? | Nije znao da æe ona doæi.
{95996}{96060}Ne znam. - Je li opasan?
{96064}{96199}Ne. Nije agresivan. | Takve zovemo organizatorima.
{96209}{96263}Ali ovdje nema | što organizirati.
{96267}{96350}Na licu i na rukama | ima kožni poremeæaj.
{96353}{96385}Nešto degenerativno.
{96389}{96439}Ne obraæajte pozornost. | Moglo bi ga zasmetati.
{96443}{96487}Što je to? - Ne znamo.
{96491}{96582}On kaže da su ga zarazili | neèime u Dachauu.
{96586}{96686}Èesto govori o poljima | pokolja. To obožava.
{96819}{96856}Trenutaèno nisam kod kuæe.
{96860}{96922}Ostavite poruku | nakon signala.
{97451}{97499}Koje sranje.
{97547}{97577}Zaboravi.
{97648}{97779}Poznajem te. Vidio sam te | u agenciji. Tko si?
{98365}{98392}Pogledaj.
{98621}{98729}Napravio sam ovo za nju. | - Dobro je. Svidjet æe joj se.
{98737}{98784}Trebao bi joj to pokazati.
{98851}{98972}Ne znam gdje je. | Ne znam gdje se zavukla.
{99034}{99078}Prièekat æemo je.
{99083}{99170}Pomoæi æu ti | da je uvjeriš. Vidjet æeš.
{99222}{99349}Možemo iæi kod nje. | Negdje imam kljuèeve.
{99396}{99559}Ona to ne zna. | Misli da sam ih vratio.
{99582}{99662}Hajde, idemo. - Idemo kod nje.
{100473}{100572}Claudia... Jako si lijepa.
{100673}{100714}Znaš to, zar ne?
{100783}{100943}Tražim svoju kæer. Molim vas, | ako znate gdje je, recite mi.
{100955}{101101}Znaš da mi je jedna bradavica | duža od druge. Kao zmiji.
{101153}{101234}Samo su me zbog toga | stavili u kamp pokolja.
{101297}{101454}Sa Židovima i pederima. | U kapsulu od kobalta.
{101460}{101495}Znaš što je to?
{101523}{101564}Kako bi znala.
{101591}{101667}Bolno je. Jako je bolno.
{101732}{101796}Nisu svi bili zli prema meni.
{101819}{101916}Neki su mi se povjeravali, | uèili me nekim stvarima.
{101944}{101991}Nevjerojatnim stvarima.
{102040}{102087}Sve u što vjerujem...
{102106}{102231}Sve što sam otada napravio, | nauèili su me oni.
{102476}{102628}Sigurno su ti rekli da | sam kriminalac, bolesnik.
{102647}{102690}Svakakve laži.
{102737}{102780}To nije istina, Claudia.
{102785}{102933}Ja sam istražitelj. | Istražujem, tražim.
{102953}{103007}Ima li što loše u tome?
{103155}{103192}Poznajem tvoju kæer.
{103253}{103299}Vidio sam je u snovima.
{103367}{103442}Svu svoju djecu | vidim u snovima.
{103447}{103537}Preklinjem vas. Kæi mi je. | Morate mi reæi gdje je.
{103541}{103610}Misliš da ne razumijem | tvoju bol?
{103623}{103704}Varaš se. Znam kako je.
{103746}{103919}Djecu poduèavaš, pokušavaš | ih izvesti na pravi put,
{103928}{104122}pripremiti ih za spoznaju. | - Recite mi što znate o njoj.
{104222}{104270}Pogledaj stol, Claudia.
{104370}{104479}Sigurno vidiš samo stol.
{104492}{104579}Jer ne vidiš dublje unutra.
{104615}{104754}Ima stvari u stolu, | ali ih ti ne vidiš.
{104827}{104952}Termiti. Jedu ga malo po malo.
{104986}{105033}Ali to nitko ne zna.
{105044}{105139}Nikad ne miruju. | Rade to u tišini.
{105170}{105275}Dok se jednoga dana | stol ne slomi.
{105308}{105347}To je tajna.
{105431}{105540}Da me vidiš iznutra, | vidjela bi to isto.
{105580}{105636}Pun sam buba, Claudia.
{105658}{105763}Jedu me malo po malo, | i nitko to ne zna.
{105832}{105956}Ne možeš zamisliti bol. | Beskrajna je.
{106464}{106581}Reæi æu ti što znam, | jer ti želim pomoæi.
{106671}{106819}Kæi te èeka. | Moraš je pronaæi.
{106826}{106928}Ako si dobra majka. | Moja to nije bila.
{106932}{107148}Ali, gdje? - Odveli su je | tamo gdje je sve poèelo.
{107153}{107291}Što to znaèi? Gdje je | sve poèelo? Ne razumijem.
{107358}{107560}Sjeti se, Claudia. Misli. | - Preklinjem vas. Molim vas.
{107893}{107956}Jesi dobro? | - Nije nièemu služilo.
{107961}{108079}Nisam tako siguran. | Tip zna tko si.
{108083}{108222}Èini se da nam daje neke | tragove. Zagonetke. - Što?
{108271}{108376}Možda i dalje upravlja odavde. | Imaju pravo na pozive.
{108381}{108491}I cijela ta prièa o poljima | pokolja i da su ga zatrovali.
{108495}{108550}To je veza o kojoj je | govorio onaj isusovac...
{108554}{108598}Jesi vidjela brojeve | koje ima na ruci?
{108602}{108663}Kao da se sve poèinje slagati.
{108668}{108766}Neæu da više ostaješ | sama kod kuæe.
{108775}{108852}Što da napravim? | - Proæi æemo onuda.
{108856}{108921}Uzmi stvari i idemo k meni. | Ne sviða mi se ovo.
{108925}{108984}Zlo je kljuè, Claudia.
{109015}{109154}Otvara vrata. | Samo je u pitanju sinteza.
{109165}{109283}Moja su djeca spremna. | A ti si mrtav.
{109360}{109412}Ovaj Santini zna više | nego što se èini.
{109416}{109495}To da je zlo znanost. | Kljuè koji otvara vrata.
{109501}{109550}Stubama. Dizalo ne radi.
{109553}{109621}Isto je rekao sveæenik. | Sinteza zla.
{109625}{109694}Èin krajnjeg zla za dostizanje | neke više razine svijesti.
{109698}{109734}Možda je toèno | da spremaju nešto.
{109737}{109849}Ali što? - Ne znam. Samo na to | mislim. Možda neku zagonetku.
{109853}{109941}Mislim da nam daje tragove. | Mjesto gdje je sve poèelo...
{109945}{109980}Mora znaèiti nešto. | Razmisli malo.
{109982}{110082}Mi æemo razmišljati, | a kæi mi je tko zna gdje.
{110088}{110144}Možda je u ovome trenu | siluju, ili ubijaju,
{110148}{110203}a ti bi ostao ovdje | i rješavao zagonetke.
{110207}{110257}Ne! Samo te molim | da razmisliš.
{110261}{110352}Rekao je da se prisjetiš. | Prisjeti se onda. Misli.
{110369}{110483}Ne znam. Ne znam | što je time htio reæi.
{110487}{110555}Samo znam da æe joj | uèiniti nešto jako ružno.
{110557}{110644}Sam si to rekao. Spremaju | nešto. Zato je trebaju.
{110648}{110710}Dobro, smiri se. Oprosti.
{110992}{111068}Hajde, brzo. | Pokupi stvari i idemo.
{111391}{111457}Ne dolazi. Ostani tamo.
{111507}{111537}Što je?
{111925}{111953}Ne dolazi.
{112371}{112400}Bože...
{112513}{112657}Tko je to? - Toni. | - Tko je Toni?
{112662}{112761}Radi za agenciju. | Što se dogaða?
{112765}{112869}Plaše te. Boje te se. | Zato te plaše.
{112872}{112925}Zašto? Zašto me | žele preplašiti?
{112929}{112962}NIJE MRTVA
{112984}{113064}Moramo zvati policiju. | Ne možemo više èekati.
{113122}{113186}Ne znam. Doði. Idemo odavde.
{114048}{114165}Da? - Quiroga ovdje. | Tražim vas juèer cijeli dan.
{114169}{114239}Nije važno. Slušajte, | možda ih imamo.
{114245}{114354}Slijedio sam dobar trag. | Da, znam gdje su.
{114392}{114466}Nije bilo lako. | Razmišljao sam cijelu noæ.
{114495}{114603}Odakle zovete? | Ne, èekajte. Dolazimo.
{114730}{114772}Èekajte!
{114800}{114888}Quiroga! Sranje. | Tip je budala.
{114892}{114968}Što se dogaða? | - Kaže da ih ima.
{114973}{115031}U napuštenom su hotelu | izvan grada.
{115035}{115100}Pored benzinske, | prema sjeveru.
{115127}{115174}Nadam se da zna što radi.
{118229}{118298}ASTRALNO OSKVRNUÆE
{118401}{118549}Napušten hotel, prema sjeveru. | - Èekat æemo na benzinskoj.
{118554}{118621}Bila sam u jednom | motelu u blizini.
{118624}{118699}Sa svojim mužem. Prije | nego su sagradili autoput.
{118737}{118865}Tamo smo zaèeli Angelu. | - Što? Sigurna si u to?
{118869}{118963}Naravno. Odveli su je | gdje je sve poèelo.
{118968}{119046}Rekao sam ti da se | radi o zagonetki.
{121846}{121886}Nije zvao? - Ne.
{121909}{121994}Pitao sam zaposlenika. | Kaže da je iza šuma.
{121997}{122059}Poslije je cesta kojom se | doðe do motela za 1 km.
{122063}{122122}Nije bilo nikakve ceste. Ne.
{122126}{122218}Nije je bilo tada. | Izgradili su je prije 8 g.
{122223}{122283}Prolazi uz hotel. | Zbog toga su je zatvorili.
{122287}{122327}Sve se slaže.
{122335}{122409}Koriste napuštene kuæe, | da se maknu od buke.
{122411}{122507}Kao termiti. | Prokletnik Santini.
{122882}{123001}Idem. Ne možemo više èekati.
{123023}{123090}Ti ostani. Evo ti telefon | ako nazove. - Molim?
{123093}{123155}Ozbiljno. Može | biti jako opasno.
{123158}{123208}Ludim pokušavajuæi | pronaæi kæer.
{123213}{123258}A ti hoæeš da ostanem | ovdje prekriženih ruku.
{123261}{123329}Majka sam joj! - Slušaj. | Ne znamo hoæe li biti tamo.
{123333}{123431}Ne želim da riskiraš. | Ni ti ni ona. Radije idem ja.
{123435}{123523}Želim iæi i ja. Ne mislim | sada stati. Pusti me.
{123527}{123663}Smiri se. Ne vidiš kakva si? | Histerièna si.
{123899}{123996}Dovedi je, molim te. | Molim te, dovedi je.
{124052}{124141}Ako se ne vratim za pola sata, | zovi policiju.
{124175}{124274}Dobro? - Da.
{124567}{124671}Nisam ribama ostavila | hranu. Uginut æe.
{126661}{126735}Da? - Mama, ja sam.
{126745}{126861}Angela? Gdje si? | - Kod kuæe sam.
{126885}{126968}Mislim da su ubili tvoje | prijatelje. Pomozi, molim te.
{126972}{127105}Ne. - Požuri, mama. | Brzo æe se vratiti. Trèi.
{128312}{128396}Dugo te nema. Èekamo te.
{128464}{128617}Gdje mi je kæi? - Kasniš. | Tvoja kæi je naša.
{128650}{128790}Hoæu svoju kæer. Došla sam | po nju. Ona je moja.
{128824}{128856}I moja.
{129117}{129160}Zaboravila si?
{129199}{129313}Što radiš ovdje? Što je ovo?
{129355}{129544}Istina. Nisi li to tražila? | - Ne može biti, ne može biti.
{129549}{129658}Još ne razumiješ. | Bilo je to zbog nje.
{129664}{129762}Trebali smo jednu | èistu djevojèicu
{129791}{129873}kako bismo je | izopaèili od poèetka.
{129880}{129930}Ti si mi je dala.
{129960}{130020}Gdje je? | Što ste joj uèinili?
{130024}{130132}Mislim da ne želiš znati. | Sada je naša igraèka.
{130137}{130251}Naša najbolja igraèka. | - Ne. Vratite mi je.
{130256}{130298}Došla sam dovde. | Imam prava. Molim vas.
{130302}{130398}Prava? Još ne razumiješ.
{130418}{130524}Ovdje si jer smo | mi tako htjeli.
{130532}{130659}Morali smo te pripremiti. | Sada si spremna.
{130685}{130781}Pogledaj se. Davali smo ti | tragove da te dovedemo.
{130786}{130862}Kao da pletemo paukovu mrežu.
{130893}{130964}Koje tragove? O èemu govoriš?
{130974}{131082}Tako si naivna. Kuæa na plaži.
{131094}{131236}Nije ti se èinilo prelako? | Èizma u kutiji, videovrpca.
{131260}{131318}Htjeli smo ti još pomoæi.
{131327}{131428}Ljudi iz èasopisa | znali su neke stvari.
{131440}{131576}Bilo je tako lako. | Grizla si sve mamce.
{131581}{131682}Jako si dobro to radila. | - Zašto?
{131724}{131837}Zašto? Jer smo sada spremni.
{131850}{131984}Postiæi æemo što | još nitko do sada nije.
{131999}{132169}Mi preobraæujemo. | Izolirat æemo zlo.
{132179}{132277}U najèišæem stanju. | Do potpune sinteze.
{132280}{132414}Apsolutna èistoæa. | Krajnja okrutnost, ekstaza.
{132446}{132531}A ti æeš biti svjedok.
{132536}{132677}Gluposti. Neæu vam dopustiti | da je taknete. To je moja kæi.
{132703}{132797}Trèi... Trèi...
{132976}{133142}Ono što æemo napraviti | nadilazi sve do sada uèinjeno.
{133221}{133372}Najljepši èin. Ne možeš | zamisliti toliku ljepotu.
{133479}{133600}I ti æeš to vidjeti.
{133721}{133812}To si htio? Zato si sve | organizirao. Prokletnièe!
{133918}{134022}Ja ne... Nisam to ja napravio.
{134593}{134666}Ja sam to napravila, mama.
{134745}{134778}Angela...
{134911}{134987}Ne zovi me tako. | Ja nemam ime.
{135061}{135123}Ja sam. Mama je.
{135141}{135233}Ekstaza, Claudia. | Dobrodošla u novi svijet.
{135237}{135291}Što ste joj napravili? | Što se dogaða?
{135294}{135395}Sinteza, Claudia. | Ovoga puta bez pogreške.
{135400}{135532}U samoj srži. Nije dovoljno | uništenje i muèenje.
{135536}{135591}Nije bilo dovoljno.
{135596}{135667}Bilo je još nešto, | i mi smo to otkrili.
{135670}{135774}Zove se izopaèiti, | izokrenuti ono dobro.
{135778}{135823}Dosta, šuti...
{135866}{135940}Prokletnici!
{135985}{136060}Gdje je?
{136067}{136150}Ne traži ga, mama. | Ja ga imam.
{136330}{136441}Hajde, malena moja. | Kako smo se pripremali.
{136446}{136522}Ne slušaj ih, ne slušaj ih.
{136558}{136629}Što èekaš?
{136641}{136739}Ostavi ga, dušo. | Iskorištavaju te, varaju te.
{136743}{136824}Hajde, uèini to!
{136840}{136926}Ne. Pusti ga.
{137016}{137140}Ubij je, ubij je. - Dosta!
{137322}{137431}Više nisam mogla. | Prisilili su me.
{137438}{137603}Molim te, mama, oprosti mi. | Reci mi da me još voliš.
{137667}{137772}Naravno da te volim. | Toliko te volim...
{137826}{137905}Tako je, malena. | Pobijedile smo.
{137909}{137994}Više nam ne mogu nauditi. | - Trebam da me puno voliš.
{138003}{138141}Volim te puno, puno... Angela.
{138201}{138285}I bolje. Tako æeš više patiti.
{138437}{138548}Patit æeš koliko | ni oni nisu sanjali.
{138557}{138630}Ono što te èeka | bezbroj je puta gore.
{138634}{138700}Ono što su svi željeli. | Sinteza.
{138704}{138745}Ali im neæu | dopustiti da je vide.
{138750}{138863}Bit æe to samo za nas dvije. | Za tebe, prokletnice, i mene.
{138929}{138977}Što æeš napraviti?
{139112}{139164}Još æu te zvati...
{139165}{139565}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan 
