{3020}{3082}DOBITNA KOMBINACIJA
{3967}{3997}Èist je.
{4110}{4155}Zašto si ovdje?
{6843}{6890}Bilo je vrijeme...
{7215}{7310}16:35.|- Nisi me razumio, nisam pitao
{7312}{7420}za vrijeme, samo sam|rekao da je bilo vrijeme.
{7475}{7603}Bilo je vrijeme? -Aha,|pogledaj onu smeðkastu tamo.
{7640}{7760}Baš je opaljena, zar ne?|- Ima 70.
{7825}{7873}Bilo je vrijeme.
{7903}{7995}Ja sam Smith, nisam iz grada.|- G-dine Smith, slušajte...
{8005}{8097}Samo Smith. Razlog što sam u gradu,
{8100}{8133}ako se pitaš,
{8167}{8227}je zbog komešanja u Cansas citiju.
{8230}{8293}Što je komešanje Cansas citija?
{8323}{8387}To je kad svi gledaju desno,
{8389}{8453}a ti odeš lijevo.|- Nikad èuo.
{8485}{8530}To nije nešto za šta ljudi èuju.
{8620}{8675}Ovaj je proveo 20 godina
{8677}{8735}Praveæi ga.|-20 godina?
{8760}{8813}Nije to mala stvar,
{8855}{8917}treba dosta planiranja,
{8919}{8977}kao i mnogo ljudi.
{9007}{9090}Ljudi koji su povezani nekim sluèajem.
{9170}{9235}To mjesto nikada ne zaboravlja,
{9237}{9300}èak i kada ga ljudi zaborave.
{9435}{9470}Sve poèinje sa konjem.
{9585}{9653}Tako su to nekada zvali u apotekama.
{9667}{9717}Èovjek je htio ono što se naziva
{9719}{9780}"sitnom lovom" pa zato tako iskombinira.
{9790}{9857}Zove ga Doc, èovjekom poznatim
{9860}{9940}po svojim djelima, ali ne i po diskreciji.
{10073}{10133}Doc je sa strane imao kolaè Gloriju.
{10203}{10283}Koji si ono rekao da je, dušice?
{10483}{10510}Što nas dovodi do Abea,
{10513}{10577}jer je Glorija bila preveliki|kolaè za samo jednog.
{10615}{10677}Dušo, jesi li spreman?|- Šta hoæeš?
{10695}{10775}Ko je to, Abe?|- To je Simor.
{10810}{10850}Reci toj kuèki da otvori bolje oèi,
{10853}{10880}možda bi onda bolje vidjela.
{10893}{10940}Simor te pozdravlja!
{10941}{10985}Zašto me zoveš ovdje?
{11010}{11060}Božiæ je uranio ove godine,
{11063}{11095}imam poklon za tebe.
{11096}{11150}Sjeæaš se mog prijatelja Doca?
{11163}{11195}Abe nije bio njuškalo,
{11197}{11230}ali je imao dobar njuh.
{11247}{11270}A odmah ispod toga
{11273}{11295}su bila njegova usta.
{11350}{11460}Sjeæaš se Glorije, kurve?|- Da.
{11465}{11480}Ona ima tog prijatelja Doca
{11483}{11510}koji radi na dopingiranju|trkaèih konja.
{11520}{11545}Srediæe nam sve.
{11547}{11590}Konj sedam, deseto mjesto.
{11625}{11655}I tu je bio taj šaljivdžija
{11657}{11707}koji se pretvorio u uši.|- Vratimo se.
{11735}{11780}I on je izgleda bio neèiji ujak.
{11781}{11823}Max, tko ti je omiljeni ujak?
{11833}{11907}Dobro, ko ti je drugi omiljeni.
{11909}{11965}Obrati pažnju, imam nešto.
{11993}{12025}I dok kažeš keks, momci su
{12027}{12070}se bacili u promet i poèinju
{12077}{12175}prièati o tom glasu koji ti šapæe
{12177}{12227}na uho i govori ti
{12229}{12277}da imaš "sitnu lovu"
{12287}{12320}i što je gore, ti poèinješ
{12323}{12340}vjerovati u to.
{12350}{12390}Tako je bar bilo sa starim Maxom,
{12393}{12447}koji nije bio toliko|star koliko je bio umoran.
{12470}{12520}Umoran od rada kao pas, umoran
{12523}{12587}toga da shvaæa da su snovi samo snovi.
{12613}{12645}Odlazim!|- Ali uglavnom,
{12647}{12678}Maxu je bilo dosta toga
{12680}{12728}što nema travnjak ispred kuæe.
{12740}{12785}Pobrini se da ne doðe doma kasno.
{12787}{12832}Hoæu.|- To sam rekla tvom sinu.
{12878}{12930}Tebi je to smiješno?|- Bok, mama.
{12967}{13030}Bok, mama, volim te.
{13313}{13353}Ko æe biti danas?|- Shakesty.
{13365}{13395}Bolestan je.|- Maxfilies.
{13425}{13475}Daj mi kljuè.|- Bit æe šest home-ranova
{13478}{13503}u prvih pet dijelova.
{13517}{13567}Krinkoj æe preletjeti preko polja
{13570}{13600}i udariti nogom polje.
{13617}{13650}Jessy Gondor je pogodio izmeðu
{13653}{13697}prve i druge, ali ako èovjek tako kaže
{13703}{13763}sa druge baze Toni|Taylor ga je prvi izbacio.
{13805}{13863}To si skinuo sa radia?|- Da.
{13882}{13950}Dobar si. Odmah se vraæam.
{14000}{14037}Moraš ostati u autu.|- Zašto?
{14073}{14137}Zato što ne daju|djeèacima iæi na utrke.
{14163}{14205}Sola tata vodi na utrke.
{14207}{14270}Solov tata je kockar degenerik.
{14287}{14378}I da si ti sin degenerika|kockara, i ti bi.
{14380}{14470}Hoæeš li ti postati kockar degenerik?
{14500}{14553}Znaš ti bolje, tvoj tata je
{14554}{14605}pametan igra samo na sitno.
{14667}{14707}Od ovog novca æeš iæi
{14710}{14767}na Harvard i postati lijeènik.
{14800}{14878}Ali dotad moraš ostati u autu.
{14990}{15078}Slijedeæeg vikenda idemo|na utakmicu. -Važi.
{15130}{15205}Volim te, mali.|- I ja volim tebe, tata.
{15215}{15287}Èekaj, sat, sat...|- Zamalo sam zaboravio.
{15290}{15337}15 minuta, poèni sa brojanjem.
{16115}{16195}I broj sedam se probija
{16196}{16275}sa strane!|- Hajde!
{16420}{16493}Ide ispred i broj sedam se probio!
{16517}{16633}Sve je èisto pred brojem sedam.
{16783}{16840}Sedam je pao!
{16957}{17010}Tada je Max shvatio da su njegovi
{17013}{17040}snovi bili samo magla.
{17053}{17120}Hoæu se kladiti.|- Na koliko? -20 somova.
{17175}{17267}Misliš da baš imaš|sreæe. Primiæu ti okladu.
{17377}{17420}Daæu ti dva na jedan za konja.
{17423}{17477}U formularu piše devet prema jedan.
{17520}{17587}Doneseš 20 tisuæa na ruke i dobiješ
{17590}{17655}devet prema jedan ako se oklada održi.
{17670}{17727}Dolaziš ovdje sa izvrnutim džepovima,
{17729}{17760}dobijaš dva prema jedan.
{17770}{17847}Polog je deset. To znaèi da æeš,
{17849}{17925}ako izgubiš, duguješ 22 tisuæ.
{17933}{18047}Dvadeset za okladu, dva za polog.
{18049}{18130}Možeš li to platiti?|- Da.
{18300}{18367}Da bude jasno, ako izgubiš,
{18370}{18420}dugovat æeš puno novca
{18450}{18533}Ljudima kojima ne bi htio
{18534}{18615}dugovati ni šaèicu novca.
{18930}{18950}Henry?!
{18990}{19015}Henry?!
{19107}{19130}Henry?!
{19317}{19355}Prijatelju, imaš li vatre?|- Ne.
{19380}{19410}U tom sluèaju hoæu dvadeset somova
{19413}{19445}koje si slupao na konja broj sedam.
{19463}{19503}Šta si napravio mom sinu?
{19505}{19563}Na putu je kuæi. Baš kao i ti.
{19803}{19847}Gdje sam ja?
{19983}{20063}Ralf, reæi æe vam sve, kunem se.
{20147}{20185}Uvijek i jest.
{20347}{20430}Molim vas, imam obitelj.
{20573}{20713}Molim vas, platit æu. Henry?!
{21070}{21103}Henry...
{21470}{21525}Jebo te, sranje. Isuse!
{21527}{21635}Jebo te, sranje,|Isuse je pravi redosljed.
{21645}{21715}Ne razumijem, zašto su|ubili Maxovu obitelj?
{21716}{21740}Nova zanimacija.
{21767}{21820}Nisu htjeli da se itko ponovno kladi
{21823}{21860}na namještenu trku sa konjem.
{21900}{22020}Htjeli su ostaviti utisak.|- Kakva prièa.
{22050}{22095}Prièa da se Èarlin Èaplin pojavio
{22096}{22145}na takmièenju za Èarlija Èaplina i dobio
{22155}{22277}treæe mesto je neka prièa.
{22279}{22397}Ovo... ovo je nešto drugo.
{22407}{22477}To je komešanje u Cansas citiju?
{22480}{22547}Ne, to je samo zanimljiv incident.
{22627}{22747}Ovo je komešanje u cansas citiju.
{22749}{22835}Oni gledaju desno, a ti...
{23093}{23127}Oprosti zbog toga,
{23130}{23210}ponekad u životu ima više od života.
{23243}{23367}Osim toga nema komešanja|u Cansasu bez leša.
{24757}{24800}Dolje je.
{26130}{26163}Dolazim.
{26230}{26260}Dolazim.
{26388}{26488}Zašto ti treba toliko?|Ti nisi Nick?
{26510}{26577}Nisi visoka koliko sam mislio.
{26578}{26645}Pa, niska sam za svoju visinu.
{26660}{26697}To ima smisla, obièno mogu pogoditi
{26700}{26738}neèiju visinu po naèinu kucanja.
{26757}{26803}Ti drukèije kucaš, èestitam.
{26845}{26880}To je znaèi dobro?
{26883}{26930}Oèekivao sam da æeš biti
{26933}{26980}ovdje kada otvorim vrata
{26995}{27075}a ti si tamo dolje, ma nije ni bitno.
{27076}{27095}Ko si ti?
{27117}{27195}Ja sam Slevin.|- Šta ti se dogodilo s nosom?
{27225}{27280}Ti nisi morala slomiti šaku nekome.
{27283}{27307}Netko te je udario?
{27325}{27417}Da, ali oèekivao sam to.|- Oèekivao si?
{27443}{27488}Kažu da sve ide u broju tri.
{27545}{27590}Prvo sam izgubio posao, onda
{27591}{27633}sam došao kuæi i saznao da se
{27638}{27695}moja zgrada ruši zbog
{27696}{27750}hiper najezde termita.
{27777}{27827}Onda sam otišao kod djevojke Kelly,
{27828}{27877}imao sam kljuèeve pa sam ušao unutra.
{28167}{28220}Ne stajte zbog mene.
{28290}{28343}Oprosti, bilo je sluèajno.
{28344}{28433}Ti si se spotakla, a|on je pao preko tebe?
{28530}{28583}Slevin, znaš li koliko je sati?
{28584}{28620}Da, na aerodromu sam.
{28627}{28655}Sigurno da hoæeš da doðem?
{28657}{28693}Dva tjedna u New Yorku i jedina
{28700}{28745}Kelly koju æeš zapamtiti bit æe ona koja
{28747}{28810}ti je izdrkala u autobusu|na putu za letnji camp.
{28817}{28883}Kelly Perkins, rekla|mi je da su joj ruke...
{28884}{28913}To je rekla mnogima.
{28927}{29022}Zato smo je zvali drkaèica.|Nazovi me kada stigneš.
{29275}{29353}Stigao sam u grad Nik|i krenuo sam kod tebe.
{29354}{29393}Znaš li koliko je sati?
{29403}{29450}Da, èovjeèe, 7:23 je.
{29453}{29515}Verojatno još uvijek spavaš.
{29575}{29640}Ne pušim.|- Onda mi daj svoj novèanik
{29641}{29683}i sam æu kupiti cigarete.
{29717}{29753}Jel' me ti to pljaèkaš?
{29815}{29838}I evo me.
{29907}{29943}Rekao si tri.|- Što?
{29960}{30005}Rekao si da loše stvare dolaze
{30007}{30053}sa tri stvari. Izgubio si posao,
{30060}{30095}ruše ti zgradu, Kelly te je varala
{30097}{30127}i opljaèkan si. To je èetiri.
{30147}{30180}Kada te krene, onda te krene.
{30183}{30222}Zanimljivo, mada ne bi bilo tako
{30235}{30293}pametno držati èovjeka koji je toliko...
{30294}{30327}Ali, slomio mi je nos.
{30338}{30363}Ali, previdio je tvoj kofer.
{30365}{30390}Težak je, možda je mislio
{30393}{30425}da æe mu biti teže pobjeæi.
{30443}{30497}Istina, ali to se ne odnosi na tvoj sat.
{30499}{30527}Baš lijepo.|- Lažnjak je.
{30535}{30583}Ali on to nije znao.|- Možda ga nije vidio.
{30588}{30620}Jest, pitao te je koliko je sati.
{30622}{30663}Kažeš da ti je ovo treæe pljaèkanje?
{30690}{30747}Dosta putujem.|- Gdje je Nick?
{30772}{30810}Trebali smo se naæi ovdje,
{30811}{30847}nije se pojavio.|- Kako si ušao?
{30870}{30938}Vrata su bila otvorena.|- Otvorena?
{30955}{30995}Otvorena ili otkljuèana?|- Ne sjeæam se.
{31003}{31045}Rekao si otvorena.|- Možda.
{31046}{31070}Kako se ono zoveš?
{31088}{31125}Lindsey, živim niz hodnik.
{31127}{31188}Došla sam da posuditi šalicu šeæera.
{31195}{31210}Gdje ti je šoljica?
{31213}{31230}Rekla sam da sam došla
{31231}{31247}posuditi šoljicu šeæera
{31253}{31293}da imam šoljicu rekla bih da sam
{31295}{31317}došla po šeæer.|- Touche.
{31350}{31375}Možda je to Nick.
{31467}{31593}Da? Prekinuo je.
{31633}{31730}Imam ideju. Zvao si|nekoga od kad si ovdje?
{31777}{31875}Oprostite, pogrešan broj. Hotel Sheval.
{31876}{31907}Šta to radiš?
{31920}{31935}Znamo koga je on zvao
{31938}{31957}pa da saznamo ko je zvao njega.
{31965}{31997}Columbo kaže da postoje tri stvari...
{31999}{32013}Columbo?
{32033}{32105}Da, to je tv detektiv...|- Znam ko je on.
{32143}{32188}Po Columbu na mjestu zloèina se traže
{32190}{32243}tri stvari. Što je tu|što nije bilo prije?
{32305}{32345}Je li ovo mjesto zloèina?|- Mislim da je Nick u nevolji.
{32393}{32467}Oprostite, pogrešan broj.|To je ponovno bio hotel Sheval.
{32507}{32553}Zvao je hotel i oni su ga zvali,
{32555}{32600}to ima smisla.|- Možda je to trag.
{32640}{32667}Trag èemu?|- Možda je to trag
{32669}{32695}onome što se dogodilo Nicku?
{32703}{32733}Ne znamo je li se što dogodilo Nicku.
{32735}{32765}Ne znamo da mu se ništa nije dogodilo.
{32773}{32815}Rekao je da æe biti ovdje, ti si ovdje,
{32817}{32865}on nije, vrata su|otvorena i loše stvari...
{32875}{32920}Sranje, moram otiæi do|posla. Na nekoliko sati.
{32943}{32987}Vratit æu se i onda možemo
{32990}{33035}poèeti istragu.|- Istragu?
{33055}{33083}Bit æe zabavno.
{33335}{33407}Oprosti. Mogu li posuditi|šoljicu šeæera? - Što?
{33483}{33503}Nikada nisam puno razmišljala
{33504}{33517}dok nisam stavila kavu.
{33525}{33545}Krenula sam u trgovinu i onda mi je
{33546}{33565}palo na pamet da Nick ima šeæer.
{33587}{33650}Isprièaj mi tvoju prièu.
{33653}{33713}Vrati penis u egzibiciju.
{33815}{33887}Reci nešto i...|- Moj penis?
{33957}{34007}Ne, susjedi posuðuju šeæer jedni
{34009}{34055}od drugih. To je jako lijepa gesta.
{34150}{34295}Penis nije to.|Hvala na šeæeru, šeæeru.
{34500}{34560}Htjela sam srediti za kasnije.
{34561}{34595}Nemoj zakasniti.
{35000}{35023}Nije ni blizu...
{35047}{35103}Šef te hoæe vidjeti.|- Tko?
{35113}{35183}Šef. - Tko je šef?|- Èovjek za kojeg radimo.
{35233}{35265}Sjedi dolje.
{35385}{35420}Ja nisam onaj kojeg tražite.
{35421}{35440}Ja ne živim ovde.
{35447}{35487}Izgledaš kao tip koji živi ovde.
{35490}{35527}Onda ne znate kako taj izgleda.
{35540}{35575}Hoæe reæi da izgledaš
{35577}{35640}kao da živiš ovdje.|- Da, to sam mislio.
{35647}{35685}Izgleda kao da živim ovdje,
{35687}{35745}ali ne živim.|- Tek sam jutros stigao.
{35760}{35867}Èovjek kojega tražim, ime mu je...|- Ime mu je Nick.
{35995}{36060}Tko si ti?|- Ja sam Slevin.
{36120}{36157}Imaš osobnu iskaznicu?
{36225}{36280}Èudno je to da sam opljaèkan jutros.
{36335}{36385}Reci to jednonogom èovjeku
{36387}{36437}da može odskakutati niz put.
{36657}{36757}Slušaj...|- Ne, držim pod kontrolom.
{36760}{36790}Pusti mene.
{36857}{36910}Drkadžijo, samo znam da me je šef
{36913}{36965}poslao na ovu adresu i rekao je:
{36975}{37037}"Slou", to je on, "Elvise" to sam ja,
{37040}{37113}"Donesite mi onoga koji|živi na ovoj adresi"
{37123}{37203}To mi je rekao danas,|ti sa bio ovdje danas.
{37205}{37285}Ti si vjerojatno taj|koga treba pokupiti.
{37317}{37365}Danas.|- Ali ja nisam Nick.
{37385}{37443}Nažalost po tebe, nisi prvi koji mi
{37444}{37497}kaže da nije tip kojega tražim.
{37527}{37565}Možete pitati Lindsey, živi
{37566}{37603}niz hodnik, ona živi ovdje.
{37630}{37660}Neæu nikoga pitati.
{37663}{37733}Nick, ili kako god da|se zoveš, i kada bi sama
{37740}{37810}djevica Marija sa dobrim dupetom
{37811}{37880}i cicama došla i rekla mi da se
{37887}{37917}zoveš Isus Krist, ipak bih te morao
{37920}{37960}odvesti šefu.|A znaš zašto?
{37963}{38093}Ne.|- Zapovijedi, a znaš šta je to.
{38095}{38150}To su zapovijedi.
{38197}{38237}Nitko te nije nauèio da ne koristiš
{38239}{38277}rijeè koju definiraš u definiciji.
{38405}{38460}Reci još nešto i slomit æu ti nos.
{38463}{38493}Ne igram se s tobom.
{38520}{38557}Nos mi je veæ slomljen.
{38733}{38797}Mogu li reæi još nešto?|- Što?
{38805}{38850}Možete li ukljuèiti|grijanje jer je baš hladno.
{38877}{38927}Trebao si prije misliti na to
{38930}{38980}prije nego što si poèeo laprdati.
{39830}{39855}Finn?
{40070}{40097}Požuri, èovjeèe.
{40435}{40465}Hvataj ga.
{40560}{40593}Šef je tamo.
{41145}{41207}Slušaj, tvoji momci su pokupili
{41209}{41277}pogrešnog momka, ja nisam Nick Fisher.
{41285}{41370}Fisheru, upoznati ste sa Šmudom,
{41373}{41463}gdine Fišer?|Biæe iz stripova.
{41507}{41623}To je bilo jestivo|stvorenje muæena jaja,
{41624}{41737}davalo je mlijeko i umiralo je od gladi.
{41835}{41887}Šmud se mogao pojesti
{41889}{41943}i bio bi ukusa bilo koje hrane.
{42217}{42283}Šmud je svijetu davao sve što želi.
{42307}{42377}Spominjem Šmud zbog važnosti onoga
{42379}{42417}što ste dovedeni ovdje.
{42433}{42485}Oprostite, tko ste vi?|- Ja sam šef.
{42486}{42523}Mislio sam da je on šef.
{42567}{42625}Zašto? Da li slièimo?
{42670}{42745}Gdine Fisher, reæi æete mi nešto?
{42746}{42820}Ne znam, vi ste me doveli ovdje.
{42830}{42885}Jesam, ali dok ste mislili da sam ja on.
{42886}{42950}Nisam mislio da ste|vi on, nego da je on vi.
{42973}{43027}I hteo sam mu reæi... vama,
{43029}{43087}da su oni pokupili pogrešnog tipa.
{43097}{43113}Pogrešnog tipa za što?
{43114}{43133}Zbog èega god ste me|željeli vidjeti.
{43140}{43170}Znaš li zašto sam te htio vidjeti?|- Ne.
{43177}{43223}Kako onda znaš da imam pogrešnog tipa?
{43224}{43243}Jer nisam...
{43244}{43295}Možda ti želim dati 96000 dolara.
{43297}{43350}Da li i tada imam pogrešnog tipa?
{43385}{43445}Želite li mi dati 96000 dolara?
{43446}{43505}Ne, želiš li ih ti meni dati?
{43515}{43655}Ne, bi li trebalo?|- Ne znam, bi li?
{43656}{43695}Ne znam, bi li trebalo?
{43853}{43995}Da skratimo prièu. Taj|jezik te je sprijeèio.
{44087}{44145}A utisak da ste vi stekli utisak da vam
{44146}{44175}ja dugujem 96.000 dolara?
{44195}{44270}Duguješ Slimu Hokinsu 96.000 dolara.
{44271}{44347}Ti duguješ Slimu, Slim duguje meni.
{44377}{44410}Ti mi duguješ.
{44543}{44593}U tom sluèaju, da li je taj Slim tu?
{44707}{44747}Slime, znaš li ovog tipa? Slime?
{44923}{44980}Ne vrijedi. Od kako ga je netko
{44981}{45040}upucao, stari Slim je oglušio.
{45070}{45155}Zašto je Slim oglušio?|- Zašto?
{45217}{45257}Pošto vam dugujem 96000 dolara
{45259}{45307}i možda imam problem da nabavim novac.
{45345}{45427}Zašto ne bismo sredili na 90?
{45429}{45513}Da nismo malo pretjerali?
{45605}{45700}A da otpišemo cijeli dug u zamjenu
{45701}{45815}za malu uslugu?|- Zavisi od usluge.
{45937}{46033}To je bio moj sin. Èuo si da sam
{46035}{46090}rekao da je bio?|- Da.
{46115}{46155}To je zato što je mrtav, ubijen.
{46243}{46330}Prešao je u prošlo vrijeme.
{46393}{46453}Iz onog jest prebaèen je u bio je
{46454}{46503}i prije nego što je doruèkovao.
{46707}{46750}Rex talionas,
{46773}{46823}zakon odmazde.
{47203}{47257}Pakt je prekinut, moj sin je ubijen
{47259}{47327}i zato rabinov sin treba|imati istu sudbinu.
{47367}{47423}Èiji sin?|- Rabinov.
{47455}{47480}Zašto ga zovu rabin?
{47540}{47565}Zato što... je rabin.
{47640}{47670}Ko je njegov sin?
{47690}{47725}Isakta Vila.
{47855}{47980}Zašto ga zovu Vila?|- Zato što je Vila.
{48013}{48055}Ima krila, leti, širi magièni prah?
{48285}{48355}Šta o tome misli rabin?|- On to ne zna.
{48363}{48393}Vi znate, ali on ne?|- Svi znaju.
{48400}{48440}Osim rabina?|- Tako je.
{48503}{48620}Šta želite da ja napravim?|- Ti si èovek-okidaè.
{48685}{48707}Ja?|- Ti.
{48927}{49045}Zar ne postoje profesionalci za ovo?
{49046}{49177}Naravno, ali ti mi|duguješ 96000 dolara.
{49200}{49270}Zašto bih plaæao nekom drugom kada
{49271}{49347}sam veæ platio tebi. Žao mi je, klinac.
{49377}{49460}Tvoj novac više nije tvoj,
{49463}{49537}ti si u mom projektu
{49539}{49613}i radit æeš ono što treba.
{49657}{49750}Slimu bi godilo društvo, a meni Šmud.
{49751}{49817}Do jutra oèekujem tvoj odgovor.
{49885}{49913}Ima li još nešto?
{49914}{49995}Ne treba govoriti|nešto kao što su klišeji
{50005}{50085}"Ako odeš u policiju, mrtav si èovjek"
{50086}{50135}Mislim da upravo jeste.
{50145}{50175}Izgleda da jesam.
{50287}{50355}Da vidimo jesam li bio jasan.
{50356}{50423}Plaæam ti puno novca da ubiješ
{50424}{50567}nekoga, a ti æeš to dati|nekome drugom da napravi.
{50569}{50635}Ne brini ubit æu nekoga.
{50867}{50917}Zvat æu Bukovskog i|reæi mu da imamo novog.
{51835}{51873}Nick se nije pojavio?|- Ne.
{51883}{51940}Što ti je s tim ruènikom?
{51941}{51983}To je duga prièa.
{51995}{52050}Oblaèi se i možeš mi prièati usput.
{52051}{52073}Usput, gdje idemo?
{52085}{52140}Znamo da je netko zvao|Nicka iz hotela Sheval.
{52143}{52165}Razgovarala sam sa
{52173}{52217}prijateljicom koji tamo radi i ona kaže
{52219}{52267}da biljleže svaki poziv obavljen iz hotela
{52275}{52310}i da može pristupiti kompjuteru
{52311}{52347}i da možemo saznati tko je to bio.
{52377}{52510}Što je bilo? -Znam ovog tipa.|- Koga? -Ovog tipa.
{52547}{52717}Znaš njega?|- Da, sreo sam ga. Bio je mrtav.
{52725}{52867}Upoznao si mrtvaca?|- Da, u zamrzivaèu.
{53375}{53433}Mislim da je vrijeme da mi isprièaš tu
{53434}{53490}prièu zašto si još uvek u tom ruèniku.
{53505}{53555}Mogu li se prvo obuèi?
{53556}{53593}Odmah se vraæam.
{54037}{54075}Mislim da bi bila dobra ideja da...
{54137}{54240}Obuci cipele, Šelma te hoæe vidjeti.
{54241}{54345}Ne poznajem nikoga tko se zove Šelma.
{54346}{54447}Šelma poznaje tebe,|to ti je jedina briga.
{54450}{54513}Idemo.|- Kao što sam rekao...
{54633}{54702}Mislim da je bolje da ja prièam.
{54890}{54913}Što je?
{54995}{55027}Žao mu je što te je udario.
{55029}{55077}Uvijek govoriš umjesto njega?|- Da.
{55183}{55245}Nijem je?|- Ne baš.
{55267}{55302}Šta onda?|- To je osobno,
{55303}{55337}moraš njega pitati.
{55387}{55427}A kako bi mi rekao? -Ne bi.
{55530}{55558}Idemo li u...?|- Ne.
{55610}{55647}Ali...|- Ne baš.
{55740}{55820}Jednom su bili zajedno|pa su se htjeli poubijat meðusobno.
{55860}{55937}Sada svaki ima svoju kulu u izolaciji
{55939}{55983}u strahu šta bi onaj
{55985}{56027}drugi mogao napraviti.
{56277}{56300}Do gore? Apartman.
{57115}{57183}Vi mora da ste gdin Fisher?
{57185}{57297}Baš mi i ne ide|tako u zadnje vrijeme.
{57310}{57358}Bojim se da tako mora biti.
{57359}{57380}Ako baš mora.
{57400}{57510}Znate li zašto ste dovedeni ovdje?
{57513}{57580}Zato što nemam sreæe.
{57593}{57693}Vi ste sretni što znaèi da ja nisam.
{57694}{57795}Nažaost, sretni ne znaju da imaju
{57796}{57830}sreæe dok nije kasno.
{57831}{57910}Uzmite sebe za primer,|juèer vam je bilo bolje nego
{57923}{57947}danas, ali bilo vam je potrebno
{57949}{57973}danas da to shvatite.|- Ali?
{57997}{58087}Danas je stiglo. -I?|- Kasno je, vidite.
{58117}{58170}Nikad nisu sretni s onim što imaju,
{58171}{58223}uvijek žele ono što su imali, ono
{58237}{58273}što netko drugi ima.
{58275}{58315}Kao što rabin koji želi
{58316}{58352}biti gangster i gangster
{58363}{58405}koji želi biti rabin.
{58406}{58463}Što je to, tuðe je uvijek slaðe?
{58490}{58585}Kako opravdavate to da|ste rabin i gangster?
{58713}{58775}Ne opravdavam, ja sam loš èovjek
{58776}{58837}koji ne gubi vrijeme misleæi što je
{58839}{58877}moglo da bude da sam ono
{58879}{58935}što je moglo da bude ne bi moglo biti.
{58950}{58995}Ja sam i za svoje i tuðe
{58996}{59043}i tuðe je uvijek moje.
{59058}{59108}Dva èovjeka su pored vas a jednog
{59109}{59160}biste se veæ trebali bojati.
{59161}{59240}Gde je moj novac?|- Ja bih...
{59255}{59300}Kada vas netko prvi put nazove
{59301}{59345}konjem, udarite ga u nos.
{59352}{59370}Kada to netko napravi drugi put,
{59371}{59410}nazoveš ga kretenom,|ali treæi put kada vas
{59420}{59490}netko nazove konjem možda|je vrijeme da kupite sedlo.
{59747}{59787}Nemam vaš novac.
{59789}{59897}Neæete se izvlaèiti,|dugujete mi novac.
{59925}{60000}Ne znam koliko novca vam dugujem.|-33 tisuæe dolara
{60008}{60045}Ali ja nisam Nick Fisher.|- Tko ste onda?
{60046}{60080}Ja sam tip koji je na krivom mjestu
{60081}{60095}u krivo vrijeme.
{60217}{60273}Imate 48 sati da donesete novac.
{60274}{60315}Sol æe vas cijelo vrijeme paziti.
{60333}{60367}Sad možete iæi.
{60508}{60545}Imam još samo jedno pitanje.
{60755}{60850}Shvaæam, biti rabin, religiozan èovjek...
{60851}{60905}Postoje tri stvari koje ne treba èiniti
{60906}{60937}da biste spasili život i dušu.
{60955}{61005}Ne smijete vjerovati u idole,
{61008}{61115}poèiniti preljub, ili|ubiti nekoga bez razloga.
{61143}{61170}Ubiti vas prije nego što
{61171}{61208}vi ubijete mene bi bilo...|- Košer?
{61323}{61347}Prihvatljivo.
{61823}{61910}Kada mogu oèekivati polog
{61911}{62005}u banci na Kajmanskim otocima?
{62123}{62210}Uskoro.|- Dobro, reci mi,
{62211}{62300}klinac, što æeš sa njim?
{62365}{62410}S njim imam nedovršenog posla.
{62647}{62723}Ono što sigurno znam je kad netko laže.
{62724}{62773}Èovjek kao ja samo to i ima.
{62808}{62852}Razlika izmeðu života i smrti
{62853}{62897}je da zna kad ga netko laže.
{62945}{63035}Ono što je rekao, nije lagao.
{63036}{63130}To nije Nick Fisher.|- Znam.
{63435}{63495}Bila sam do hotela vidjeti prijateljicu.
{63496}{63552}Kaže da je poziv došao iz sobe 1009.
{63575}{63650}Tamo je bio prijavljen neki tip Smith.
{63651}{63690}Možeš li vjerovati?
{63705}{63813}To je najèešæe ime. Imam|dojam da ovo nije to.
{63833}{63873}Popela sam se na deseti kat
{63874}{63935}i baš tad su se|otvorila vrata sobe 1009
{63947}{63980}i tu je bio naš gdin Smith,
{63981}{64055}pa sam se pravila da idem|prema liftu umjesto da idem
{64065}{64120}iz njega pa smo sišli skupa.
{64121}{64175}Nasmijao mi se i ja sam njemu.
{64190}{64237}Nisam znala tko je on, ali sam mislila
{64239}{64285}da ti možda znaš pa sam ga slikala
{64286}{64350}koristeæi svoj mobitel,|ali je rezolucija
{64351}{64390}loša i nikad ga ne koristim.
{64400}{64490}Pravila sam se da zovem|nekoga i slikala èovjeka.
{64552}{64617}Ovo je Smith, prepoznaješ li ga?|- Ne.
{64640}{64670}Nisam ni mislila da|æeš, ali vrijedilo je.
{64687}{64737}Uglavnom, sišli smo liftom
{64739}{64837}do ulaza i taj èovjek je|izašao i pozvao taksi,
{64860}{64895}pa sam ga ja pratila.
{65023}{65090}Otišao je u zgradu sa stanovima
{65091}{65155}pa sa èekala. I prošao je sat.
{65195}{65243}Taman kada sam se spremala
{65244}{65290}otiæi, tko je izašao.|- Smit?
{65302}{65327}Ti.
{65417}{65517}Ja?|- Ti u istoj zgradi, dva velika
{65519}{65577}židova tebi sa strane.
{65680}{65810}Ne baš. - Mislim da je vrijeme|da mi isprièaš tu prièu.
{65835}{65907}Taj tip kojega zovu šefom i preko puta
{65909}{65977}je taj èovek kojega zovu rabin.
{65993}{66083}Zašto ga zovu rabin?|- Zato što je rabin.
{66253}{66333}Sada moram srediti tog Vilu
{66334}{66447}i kao da to nije dovoljno, imam 48 sati
{66450}{66535}da naðem 33 tisuæe dolara za rabina.
{66536}{66585}Ne znam tko je gdin Smith.
{66635}{66720}I najgore od svega je to|što ja nisam Nick Fisher.
{66733}{66807}Ironija.|- Znam, ja èak ni ne kockam.
{66817}{66905}Ne, ironija je imati gay sina.
{66906}{67007}Ovdje je došlo do zamjene identiteta.
{67043}{67147}Takve stvari nisu stvarne, kao amnezija.
{67150}{67260}Ti si tu, a Nicka nema|nigdje, pa si sjeban.
{67300}{67320}Sjeban.
{67425}{67490}Zar ne bi ovo trebalo|da te zabrinjava malo više?
{67513}{67567}Imam adoreksiju.|- Adoreksiju?
{67593}{67640}To je stanje u kojem si osloboðen
{67641}{67697}brige ili bilo koje preokupacije.
{67810}{67827}Do jutra trebam dati odgovor šefu.
{67829}{67850}Što æeš mu reæi?
{67913}{67955}Isto što bi rekao i èovjek sa dva penisa
{67956}{68000}kad bi ga krojaè pitao pakira li ga
{68001}{68045}s desne ili lijeve strane.|- Što je to?
{68105}{68193}Da.|- Znao sam da si razuman.
{68235}{68325}Razum je nešto kada imate izbora.
{68327}{68415}A ponekada i kad znaš da nemaš.
{68455}{68537}Nemojte taj potez, to|je klasièna namještaljka.
{68557}{68585}Ako to ne napravite,
{68586}{68655}sredit æete ga u èetiri|poteza, ali ako to napravite
{68667}{68780}on æe vas pobjediti u jednom.|- Ali on to ni ne vidi.
{68800}{68840}Ne bi bilo važno i da vidi,
{68841}{68880}Elvis me pušta da pobjeðujem.
{68925}{69057}Svi me puštaju da|pobjeðujem. Znaš li ovu igru?
{69240}{69323}Imaš tri dana.|- Mislio sam da æe
{69324}{69355}mi biti potrebno oko tjedan dana.
{69390}{69485}Loše si mislio, sa svim|tvojim iskustvom u ubijanju.
{69520}{69590}Da se dogovorimo, ako|pobjediš u ovoj igri,
{69591}{69617}imaš tjedan dana.
{70025}{70060}Koji je plan?|- Igrati po vama
{70193}{70317}Da je sve isto, zapisao bih.|- Usput, on ima sjenke.
{70417}{70447}Sjenke?
{70570}{70650}Tjelohranitelji su s njim
{70651}{70735}cijelo vrijeme.|- Vojska.
{70880}{70930}Eksis relium musad.
{70990}{71017}Idu po toènom vremenu.
{71097}{71120}To ne zvuèi dobro.
{71233}{71313}Živi u stanu pored. Nosi dugme u sluèaju
{71314}{71370}opasnosti na lancu oko vrata.
{71383}{71440}Izgleda kao obièna davidova zvijezda.
{71441}{71523}Ako ga pritisne svi|znamo kako æe se završiti.
{71543}{71580}Što je ovo?
{71635}{71653}Dolje!
{71797}{71843}Prvi put æe biti tri do pet sekundi.
{71844}{71897}Moraæeš ga pogoditi|kad najmanje oèekuje.
{71907}{71935}Gdje? -Gdje?|- U stanu.
{72047}{72097}Kako æu uæi u njegov stan,
{72099}{72147}ne mogu samo ušetati unutra?
{72165}{72210}Ne, koristi zadnja vrata.
{72400}{72497}Onda što? -On ubija|klinca, ja ubijam njega.
{72530}{72590}Postavljam svoj pištolj, èist,
{72591}{72683}bez dosijea, napravim|par opekotina na ruci.
{72727}{72777}Skinem im odjeæu i da izgleda
{72779}{72843}kao da su se meðusobno "odradili".
{72863}{72953}Obojica su gay, duplo samoubojstvo.
{72955}{72985}I to je sve?
{73040}{73093}I to je sve?|- Da.
{73455}{73553}Nisam ja loš momak, neki su me
{73554}{73687}prilièno loše procijenili.|- Neki su mrtvi.
{73850}{73920}Kad si ušao ovdje, mislio sam da
{73921}{74017}te baš briga ako te odmah ubiju.
{74063}{74103}Možete me ubiti samo jednom.
{74290}{74320}Šah-mat.
{74465}{74530}Nitko nije rekao da|te moram brzo ubiti.
{74665}{74690}Kuæa.
{74753}{74785}Imaš tri dana.
{74905}{74927}Oprostite.
{75447}{75497}Ko je, jebo te, ovaj tip?
{75499}{75577}Tko god da je u velikim je sranjima.
{75705}{75760}Pozovi Merfina i vidi jesu li što
{75761}{75815}otkrili o onoj slici?|- Da, šefe.
{75850}{75897}Hoæu cijelu njegovu prièu,
{75899}{75960}od A do Ž, hoæu znati tko je on
{75970}{76013}koga poznaje, i ti ljudi koje poznaje
{76014}{76033}koga oni poznaju.
{76043}{76093}Hoæu znati što on radi u mom gradu.
{76353}{76413}Što imaš?|- Naš mamac je u gradu.
{76450}{76520}Dobar mamac?|- Narkosi tako prièaju.
{76573}{76685}Samo se tako prièa.|- Tko je dobar mamac?
{76695}{76775}Jedan težak.|- Najteži.
{76787}{76833}On se pojavi, ljudi umiru, on nestane.
{76834}{76877}Nitko ne zna tko je on ni kako izgleda.
{76897}{76957}Nije radio u New Yorku dva desetljeæa.
{76959}{76987}Baš nam je to trebalo.
{77033}{77155}I kupite neku drugu|kavu, moram u mrtvaènicu.
{77407}{77465}Shvatila sam.|- Što to?
{77475}{77540}Slim Hokins je radio za šefa, jel'da?
{77543}{77603}Rabin je isto imao kladionièara
{77604}{77653}Beni Bejgana i sada je on u mrtvaènici.
{77654}{77667}Netko ga je ubio.
{77697}{77743}U mrtvaènici?|- Nisam ti rekla da
{77744}{77780}sam mrtvozornik?|- Nisi.
{77863}{77917}Beni Bejgan, ubijen bejzbol palicom.
{77920}{77955}Vjerojatno brzom loptom.
{78035}{78065}U svakom sluèaju, to je dokaz da
{78066}{78083}Bog ima smisla za humor.
{78095}{78153}Dobro jutro, detektive, znate ovog?
{78154}{78223}Veliki kladionièar,|radio je za rabina.
{78243}{78285}Zašto ga zovete rabinom?|- Zato što je rabin.
{78307}{78375}Izmeðu nas, prije 20 godina je bio
{78376}{78447}moj kladionièar, njemu sam slao uplate.
{78495}{78547}A ostala dvojica,|imate li nešto o njima?
{78557}{78653}Oni su otrovani, neèim egzotiènim.
{78655}{78690}Tek provjeravam.
{78710}{78755}Obavijestite me.|- Hoæu.
{78877}{78927}Ugodan dan.|- I vama.
{79070}{79113}Idem na pauzu za ruèak, Jimmy.
{79153}{79223}Zar ne shvaæaš, Nick|nije nestao, krije se,
{79224}{79273}smjestio ti je.|- Nick mi je smjestio?
{79280}{79340}Nick se negdje zaglavio i zvao tebe
{79341}{79383}da zauzmeš njegovo mjesto.
{79390}{79403}Potplatio je lopova da te opljaèka,
{79404}{79435}ali je samo htio tvoj|novèanik s dokumentima
{79437}{79475}zato je ignorirao sat i kofer,
{79476}{79550}onda je ubio Hockinsa i|Bejgana jedine ljude koji su
{79551}{79603}znali kako izgleda i|sada je tebe ostavio.
{79620}{79673}Ali ja sam prvi uspostavio|kontakt sa Nickom.
{79674}{79703}Možda samo tako izgleda.
{79713}{79800}A Smith?|- Njega još ne shvatam.
{79825}{79887}Trebao bi pobjeæi.|- Ali ne mogu.
{79889}{79927}Ubit æe te ako ostaneš.|- Ubit æe me ako odem.
{79937}{80047}Idi u policiju.|- Ne dogaða se ovo prvi put.
{80077}{80125}Ovo je prvi put da ti je šef kriminala
{80126}{80177}tražio da ubiješ gay|sina rabina gangstera
{80187}{80215}da bi otplatio dug koji|pripada tvom prijatelju
{80216}{80237}u èijem si stanu odsjeo zbog toga što
{80247}{80270}si izgubio posao, stan i zatekao
{80271}{80297}djevojku u krevetu sa drugim tipom?
{80310}{80335}Ne, ovo mi se prvi put dešava.
{80336}{80370}Nick mi je prijatelj od detinjstva.
{80440}{80495}Oduvijek sam mu bio bolji prijatelj...
{80496}{80570}Voljela bih èuti|ostatak, ali moram na posao.
{80693}{80770}Ako budeš živ kada se veèeras vratim
{80771}{80843}sa posla veèeras, mogli bismo otiæi
{80853}{80903}na veèeru?
{80904}{80925}To bi bilo odlièno?
{81005}{81047}Stvarno?
{81665}{81720}Što je?|- Pitao sam se što bi bilo
{81723}{81787}da smo se upoznali u drugim okolnostima.
{81817}{81917}Mislim da se ljudi zaljube kada imaju
{81919}{82017}neku prièu oko toga kako su se sreli.
{82027}{82057}Da može stalno da se preprièava.
{82059}{82097}Ako se mi zaljubimo,|to æe biti neka prièa.
{82115}{82155}Odemo negdje na veèeru i netko nas
{82156}{82195}pita kako smo se upoznala i ja
{82205}{82287}kažem da ti isprièaš dušo,
{82289}{82410}ti æeš to bolje. Dolaziš li ovdje èesto?
{82480}{82563}Ne, ali èuo sam da netko dolazi.
{82615}{82737}Misliš Vila? Da li je...?|- Da. - Gde?
{82925}{82965}To je apsurdno,|na šta si mislio?
{82985}{83015}Da imam nove opcije.
{83025}{83055}Tko je to? -Da poprièam sa njim.
{83085}{83105}Samo æeš da odeš|tamo i kažeš mu
{83115}{83145}"Zdravo, ja sam|Sleven i neko misli
{83160}{83215}da sam neko ko|nisam i da moram da
{83255}{83315}te ubijem da oni ne bi|mene, pa hoæeš da prièamo?"
{83330}{83360}Ne mogu to. -Misliš?
{83375}{83395}Ne mogu da mu|priðem tek tako,
{83405}{83435}ima tjelohranitelje...
{83517}{83607}Tjelohranitelji?|- Da, dvojica.
{83609}{83700}S bradama iza njega. Vidiš li ih?
{83810}{83853}Dobar si u ovome.|- Hvala.
{83865}{83905}Kako æeš prièati s njim?
{83913}{83965}Prièekat æu da ode do wc-a|pa æu ga slijeditii.
{83983}{84013}Što misliš?
{84053}{84117}Hoæe li mi netko reæi|zašto sam ja u kombiju?
{84135}{84183}Zato što sam uspeo nabaviti
{84184}{84230}rezervaciju samo za dvoje.
{84245}{84280}Vila je za stolom u sredini,
{84281}{84345}tjelohranitelji su u blizini,|naš deèko nije daleko,
{84365}{84413}ali ne shvatam tko je s njim.
{84415}{84463}Jeste li saznali što o njemu?
{84475}{84535}Tko god da je, duh je, nismo našli
{84536}{84597}nikoga tko je barem naleteo na njega.
{84727}{84765}Vila ide u wc.
{84883}{84935}Deèko kreæe, sranje!
{85455}{85490}Vrata su zakljuèana.
{85491}{85570}Opusti se, neæe to uraditi u wc-u.
{85670}{85730}Ja sam slijedeæi.
{85790}{85853}Šta ste radili wc-u?|- Prièali smo. -I?
{85863}{85895}Rekao sam da bi trebalo da se
{85896}{85927}naðemo nekada.|- Nisi valjda?
{85937}{85967}Jesam.|- I?
{85993}{86023}Zakazao sam sudar.
{86024}{86077}Ne misliš da je ovo ozbiljno?
{86090}{86127}Ne može biti gore.
{86200}{86265}Mislim da nas prate.|- Što?
{86275}{86295}Panduri.|- Slatko.
{86443}{86483}Bio je jedan ispred wc-a.
{86707}{86753}Ti i ja trebamo razgovarati.
{86853}{86930}Poznajem vas?|- Ne, ali ja znam tebe.
{87095}{87175}Oprostite, bez uvrede, ali ja nisam gay.
{87176}{87207}Ja sam policajac.
{87240}{87333}Ja nisam lopov.|- Promatram te.
{87334}{87425}Znam što namjeravaš. Tko si ti?
{87455}{87495}Znam tko nisi, nisi Nick Fisher
{87496}{87565}tip u èijem si stanu|zato što je Nick Fisher
{87573}{87615}proveo osam godina u zatvoru zbog
{87616}{87657}napadanja 14-ogodišnje navijaèice.
{87690}{87767}Poslali su mi njegovu sliku.
{87769}{87865}Ti nisi on, pa tko si, jebo te, ti?
{87963}{88025}Ja sam tip èija se veèera hladi.
{88027}{88060}Mogu li sad iæi?
{88110}{88147}Doði ovamo.
{88149}{88183}Podseæaš me na Jamesa Bonda.
{88380}{88403}To je najlepše
{88404}{88473}što mi je iko ikada rekao.|- A šef?
{88580}{88653}Ko je šef?|- Stavros Blofer.
{88683}{88770}Koji to?|- Ti si pravi Bond,
{88771}{88883}ali najbolji je Antony Dawson.|- Ko?
{88925}{88980}On je glumio u "Iz Rusije s ljubavlju"
{88981}{89035}Nikad nisi vidio njegovo lice.
{89063}{89095}Zato je najefektiniji
{89096}{89145}kad ne znaš kako izgleda.
{89705}{89745}Vidimo se kasnije.
{90413}{90437}To je bilo nevjerojatno.
{90555}{90610}Upravo sam shvatio nešto.|- Što to?
{90630}{90677}Upravo sam vodio ljubav s tobom.
{90680}{90713}Tek sad to shvaæaš?
{90723}{90763}I nemam pojma na koga si toèno
{90764}{90820}mislila kada si rekla James Bond jer
{90827}{90870}kad si rekla da te podsjeæam
{90871}{90927}na James Bonda i kada sam ti rekao
{90937}{90983}da je to nešto najljepše što mi je
{90985}{91050}iko ikada rekao i|bila si jako slatka...
{91060}{91087}Ali zapravo nisi imao
{91089}{91115}pojma o èemu prièam.
{91265}{91325}Ako si govorila o onome o kome
{91326}{91403}mislim, onda si me zamijenila s nekim
{91413}{91465}jer za mene postoji
{91466}{91610}samo jedan Bond.|- A to bi bio?
{91663}{91697}Treæi dio.|- Jedan. -Dva.
{91797}{91845}Šalila sam se.|- I ja sam.
{92075}{92117}To zvuèi puno bolje.
{92910}{92997}Gdje æeš?|- Idem po kavu.
{93873}{93947}Hej, ulazi unutra!|- Daj èovjeèe, nisam ni sa kim prièao...
{94205}{94345}Ja sam detektiv Dembraski. - Detektiv sada otima ljude?|- Ne, samo hoæemo poprièamo par rijeèi s tobom.
{94675}{94797}Pa, o èemu želite prièati? -|O tebi. - Što o meni? - Tko si ti?
{94900}{94950}Tvoje ime!
{95240}{95380}Kako se zoveš?|- Sjeæam se, Slevin Delevera.
{95443}{95483}Klinac, ne znam kako si ušao
{95484}{95547}u ovo i što se dogaða,|ali kad to shvatim
{95563}{95647}neæu biti tako ljubazan prema tebi.
{95649}{95703}Kao da je ovo lijepo.
{95780}{95813}Poslijednja šansa.
{95943}{96000}Šetaj.
{96030}{96137}Ne trebam otiæi predaleko.
{97873}{97913}Moram na posao.
{98627}{98713}Bok momci, otkud vi ovdje?|- Sad je vrijeme.
{98790}{98845}Šef kaže da želi da|izgledaš lijepo s Vilom.
{100750}{100783}Uranio si.
{100860}{100945}Uði i ulij sebi piæe. Spremao sam se.
{101245}{101365}Oprosti na neredu, nisam te oèekivao.
{101366}{101413}Izgledaš dobro.
{101467}{101555}Hoæeš vina? Nešto nije u redu?
{101675}{101770}Neko te pokušava ubiti.|- Ko?
{101867}{101885}Ja.
{103193}{103265}To je bilo blizu.|- Da.
{105125}{105155}Blizu.
{107160}{107215}Unajmio sam te za posao.
{107216}{107295}Nije trebalo izgledati kao posao.
{107353}{107437}Sredio si Vilu, srušio zgradu
{107439}{107557}i sad posao koji nije tako trebao izgledati
{107570}{107600}poèeo je tako izgledati.
{107917}{107950}Dobro, ako rabin želi rat,
{108062}{108127}dat æu mu rat.
{108335}{108360}Sol? Sol?
{108553}{108593}Sol, telefon...
{108643}{108687}Mislio sam da si Sol.
{108689}{108798}Mnogi ljudi ovih dana|misle da sam neko drugi.
{108890}{108945}Tvoj stav me podsjeæa na prièu
{108946}{109005}Hitchcocka "Sjever, sjeverozapad"
{109073}{109107}Cary Grant je èovjek po imenu
{109109}{109167}George Keplen, ali on|u stvari ne postoji,
{109185}{109287}on je izmišljen, ali èak i izmišljena
{109289}{109360}imena mogu stvoriti nevolju.
{109462}{109535}Žena na slici sa Grantom se zvala...
{109536}{109562}Iva Mori Sent.
{109590}{109675}Znaš taj film.|- Znam ga.
{109676}{109720}Odveo sam oca da ga gleda 1959,
{109723}{109773}engleski mu nije bio dobar, ali mu
{109783}{109843}se svidjela gðica Sent. Poslije mi je rekao
{109844}{109887}da je pravi bjuik, nije znao reæi
{109898}{109967}rijeè ljepota pa je govorio
{109969}{110033}bjuik. Napravio je pravu konfuziju.
{110045}{110120}Stariji ljudi znaju to.
{110193}{110273}To je moj novac?|- To je sve što vam dugujem.
{111095}{111140}Sabat je. Na Sabat
{111141}{111230}se ne javljamo na telefon.|- Znam.
{111257}{111317}Obièno bi se Sol pojavio.
{111319}{111383}Danas nema dobre posluge.
{111483}{111517}Sol je mrtav.
{111607}{111648}Svi su mrtvi.
{112233}{112298}Bio sam veæ u ovoj sobi.
{112299}{112380}Izgleda isto kao prije 20 godina.
{112417}{112490}Nekako izgleda drukèije,
{112491}{112583}tvoje auto izgledaju drukèije
{112584}{112653}ili ih neko drugi vozi.
{112710}{112733}Prošlo je 20 godina od kako nisam bio
{112734}{112800}u autu, dva desetljeæa iza neprobojnog
{112801}{112835}stakla su stvorile
{112836}{112875}prirodan strah od pušaka.
{113035}{113090}Zakljuèan u svojoj paranoji,
{113091}{113135}zatvorenik u svom domu.
{113348}{113457}Da li bi se to odnosilo i na Antonya?
{113525}{113575}Da nosim šešir, skinuo bih ga.
{113667}{113717}Da poènemo s tim?
{113855}{113895}Zadržat æemo tvoju glavu.
{114037}{114148}Kao da smo kupovali kod istog trgovca.
{114149}{114198}Lijep govor, ipak.
{114315}{114370}Volio bih da sam mogao|stajati dok je trajao.
{114633}{114667}Ti si ovo svalio na nas.|- Ja?
{114790}{114857}Ti si unajmio dobrog ubojicu da ubije
{114859}{114940}moga sina.|- Nakon što si ti ubio moga sina.
{114993}{115023}Nisam sudjelovao u tome.
{115115}{115165}Baš kao i prije.
{115180}{115220}Možda samo prst.
{115300}{115383}Gotovo je, laganje mrtvaca je isto
{115385}{115423}što i lagati sebe.
{115527}{115567}Prenagljuješ.
{115977}{116062}Tebe su nazivali šefom i bilo je jasno
{116063}{116117}šta treba biti uèinjeno.
{116287}{116362}Pokušavam zamisliti kako to izgleda.
{116417}{116487}Probuditi se u sred noæi sa šest metaka
{116489}{116557}u trbuhu, ležiš u lokvi svoje krvi.
{116690}{116770}Oèi tvoje mrtve
{116771}{116795}žene koje zure u tebe
{116985}{117040}i jedino što ti ne|da da padneš u nesvijest
{117041}{117100}je zvuk koraka èovjeka koji ide niz hodnik
{117140}{117180}tražeæi tvog sina.
{117315}{117353}Taj èovjek je spasio mog sina
{117410}{117517}i sada poslije svih ovih godina,
{117577}{117603}unatoè našem dogovoru...
{117650}{117670}Ti, smeæe jedno,
{117755}{117830}usudio si se oduzeti mi sina.
{117950}{118017}Sada sam i ja tebi oduzeo sina.
{118025}{118085}Rekao sam ti da nemam veze...
{118285}{118305}Nisi èuo?|- Lažeš.
{118407}{118498}Pogledaj me, pogledaj moj osmijeh.
{118499}{118548}Tvoj sin je mrtav,
{118660}{118680}Sin ti je mrtav.
{118790}{118810}Ubiæu te.
{118977}{119017}Rabine, èuo si za Šmuda?
{119303}{119325}Fisheru, slušaj me.
{119500}{119535}Veæ sam ti rekao,
{119577}{119612}Ja nisam Nick Fisher.
{119687}{119710}Ko je Nick Fisher?
{119950}{120085}Misliš, ko je bio Nick Fisher?|On je bio odgovor na pitanje
{120110}{120235}kako doæi do dva èovjeka|do kojih ne možeš doæi?
{120345}{120380}Natjeraš ih da doðu tebi.
{120587}{120673}Ali da bi to napravio, bilo mi je potrebno
{120674}{120743}ime, a gdje naðeš imena? U knjigama.
{120877}{120917}A ko ima knjige?
{121117}{121250}Tvoj kladionièar.|Pokvareni kladionièari.
{121343}{121383}Koji rade sa velikim prevarantima.
{121653}{121687}Tražio sam kockara.
{121730}{121780}Jednog koji je bio u obje knjige sa
{121781}{121830}dosta crvenog u koloni za minus.
{121855}{121890}Našao sam ga. Tamo sam našao
{121967}{122080}Nicka Fishera, nepoznatog koji
{122093}{122148}neæe nikome nedostajati. 1729 Nick Fisher.
{122462}{122507}Bilo je vrijeme...
{122910}{122965}Trebalo je samo da zazvoni telefon.
{123457}{123523}Samo je trebalo povuèi okidaè
{123524}{123587}i prièekati da pozoveš èoveka
{123598}{123640}koji radi poslove koje niko drugi neæe.
{123657}{123703}Želim nekoga vanjskoga,
{123748}{123785}ti si specijalista.
{123837}{123895}Zove se mamac.
{124050}{124080}Dobro, oèekuj me ujutro.
{124300}{124357}Spreman si?|- Da.
{124473}{124512}Još samo jedna stvar.
{124793}{124895}Gdine mamac, prošlo je dosta vremena.
{124898}{125015}Žao mi je što ste èekali,|prelazimo na posao.
{125083}{125157}Slim Hokins, èovjek koji je vodio moje
{125159}{125235}klaðenje je ubijen juèer i sigurno ste
{125245}{125287}veæ èuli za mog sina?|- Da, èuo sam.
{125398}{125467}Trebate to riješiti za mene.|- Tko je meta?
{125500}{125530}Njegov sin.|- Rabinov sin?
{125657}{125737}Stvar je u tome da ne smije izgledati
{125739}{125843}kao posao. Ako se to dogodi|Rabin æe objaviti rat.
{125915}{126010}Treba izgledati kao da nije ono
{126011}{126205}što jest. Može li to?|- Sve može.
{126280}{126395}Dobro je, kako?|- Komešanje u Cansas Cityu.
{126417}{126478}Nije mi poznat taj izraz.
{126555}{126580}Treba pogledati Slimove knjige.
{126612}{126645}Njegove knjige su oduzete kad je
{126663}{126712}bio u bijen, ali èuvam kopije.
{126842}{126882}Šta tražite?
{127003}{127058}Ovo je naš tip, Nick 1729.
{127109}{127162}Nick Fisher, zašto on?
{127225}{127325}Gubitnik.|- Pokupi ga i dovedi ga ovamo.
{127520}{127620}Još uvijek ne razgovarate? Ne krivim vas.
{127630}{127675}Zašto ste ovdje?|- Zbog velikog posla.
{127685}{127715}Bio sam pod dojmom,
{127716}{127762}da vi više ne radite u New Yorku.
{127770}{127830}Kao što sam rekao veliki posao,
{127831}{127912}pa si svratio|vidjeti starog prijatelja?
{128065}{128127}Ne, ali nešto tako.
{128203}{128270}Problem je samo to što|mi nismo stari prijatelji.
{128273}{128303}I ja mrzim bejzbol.
{128323}{128367}Mi nismo prijatelji i ti mrziš bejzbol,
{128369}{128407}zašto si, jebo te, došao ovdje.
{128417}{128495}Zato što nismo prijatelji. Da jesmo,
{128496}{128583}ne bih bio unajmljen|da ubijem tvog sina.
{128585}{128640}To je na vrhu liste onoga što prijatelji
{128641}{128662}ne rade prijateljima.
{128707}{128767}Dobra vijest za tebe je ta da je moje
{128769}{128805}prijateljstvo na prodaju.
{128815}{128877}Izgleda mi da ti sin više znaèi živ
{128880}{128907}nego šefu mrtav.
{128925}{128990}A meni znaèi više novca nego manje
{128991}{129057}a ti spavaš sa svim tim šuškama.
{129125}{129217}Slušam.|- Platiæeš mi duplo da ubijem
{129220}{129370}šefa za ono što mi šef|plaæa da ubijem Itsaka.
{129371}{129446}To æe nas uèiniti prijateljima. zar ne?
{129660}{129730}Pošto prijatelji èine|usluge prijateljima,
{129732}{129803}uèinit æeš mi jednu.|- Koja je to usluga?
{129828}{129883}Tièe se kolekcije dugova,
{129883}{129937}naroèito jednoga.|- Èiji?
{129949}{130047}Iz Benijeve knjige, zove se Nick Fisher.
{130048}{130102}Tko je on?|- Gubitnik.
{130127}{130185}Upravo je zaradio mnogo novca.
{130259}{130315}I onda je sve moglo krenuti.
{130717}{130817}Šta god treba, platit æu ti.
{130992}{131097}Nema plaæanja. Ja sam ti ovo napravio.
{131428}{131474}Tko si ti?
{131544}{131604}Tko je on?|- S obzirom da nema otiske
{131605}{131668}prstiju mislim da neæemo znati.
{131694}{131781}A zubni karton?|- Naravno, èim se napravi otisak vilice
{131796}{131838}pronaæi æemo karton.|- Koje ludilo.
{131974}{132086}Bukowsky, Marty je, tamo|si? Imamo još dva trupla.
{132141}{132184}Odmah dolazim. Jesi li uspio
{132185}{132278}pronaæi rabina za indentifikaciju
{132280}{132303}onoga što je ostalo od njegova klinca.
{132305}{132365}Ne, zovemo veæ|sat vremena, niko se ne javlja.
{132377}{132437}Pošaljite nekoga tamo.|- Razumijem.
{132493}{132577}Dobro si? Izgledaš potreseno.|- Dobro sam.
{133220}{133323}Da? - Bukowsky,|Merfy je. - Što ima?
{133330}{133395}Harry Kelow je svratio|danas, seæaš li ga se?
{133396}{133437}Otišao je u mirovinu prije par godina.
{133450}{133524}Žena mu je umrla pa svrati
{133526}{133564}s vremena na vrijeme.
{133619}{133676}Tip živi u prošlosti.|- Što s njim?
{133694}{133746}Èavrljali smo malo i kaže da se neæe
{133748}{133809}žaliti, ali to je sve što radi cijelo vrijeme.
{133829}{133872}Ima ženu, ona je ubijena i jadna
{133873}{133919}mu je mirovina, a onda je stao
{133920}{133966}kad je vidio sliku onog klinca.
{133968}{133994}Samo je buljio u nju.
{134009}{134059}Pitao sam ga da li ga zna.
{134060}{134136}Stvar je u tome da je buljio u ime.
{134179}{134249}On zna to ime Slevin.
{134738}{134771}Imam isti taj telefon.
{135073}{135145}Sat kasnije, poèinje prièu
{135147}{135171}o utrci konja iz '79.
{135305}{135425}Hipodrom, konj broj sedam, sjeæate se?
{135603}{135673}To je bilo dopingiranje.
{135674}{135745}Šef i Rabin su to shvatili.
{135848}{135888}Prièa o toj lokalnoj
{135891}{135931}legendi o tom klincu...
{136022}{136112}Max, kladio se sa kladionièarem
{136113}{136202}Ralfom, a Ralf je povukao okladu.
{136460}{136490}A ti...
{136670}{136727}Kada su rabin i šef saznali za namještaljku
{136728}{136787}nisu baš reagirali najsretnije.
{136788}{136882}Prièalo se da hoæe pokazati za primjer.
{136883}{136950}Ubili su sve i to baš sve,
{136987}{137042}Maxa, njegovu ženu i klinca,
{137043}{137090}Ralfa, èak je i konj umro.
{137161}{137193}To je bio masakr.
{137251}{137291}Morali su zvati specijalistu da sredi
{137292}{137321}klinca jer niko nije htio.
{137803}{137846}Šta ste napravili mome sinu?
{138211}{138239}Ti... ne, ti si mrtav.
{138351}{138385}Ti si mrtav!
{138635}{138688}Harry prièa o tome kako|su doveli specijalistu
{138689}{138732}za klinca, ali ja nisam shvatio pa sam
{138734}{138808}ga pitao kakve to veze ima sa sluèajem.
{138809}{138848}Rekao mi je ime konja.
{138858}{138912}Onda sam pitao što sa tim?
{138915}{139015}Rekao je da se konj|zvao Sretan broj Slevin.
{139028}{139088}Kako se zoveš?|- Slevin Delevre.
{139305}{139360}Sjeæaš se ovog dijela?
{139927}{139989}Ti jebeno smeæe
{140474}{140539}Vas dvojica ste ubili|sve što sam ikad volio.
{141326}{141370}Ne postoji osoba koja se zove
{141372}{141416}Slevin Delevre, što znaèi da
{141426}{141493}je klinac koristio pseudonim po
{141494}{141586}mrtvom konju i družio|se sa šefom i rabinom
{141606}{141700}koji su isto tako|umiješani u to s konjem.
{141702}{141798}Pomislio sam da to možda nešto znaèi, a
{141818}{141896}možda je i neka sluèajnost.|To više nije bitno.
{142072}{142127}Još jedna stvar, imamo jednog
{142128}{142207}novog u stanici, židova, simpatièan.
{142249}{142335}Ako te zanima kaže da ime Delevre
{142336}{142419}je hebrejskog porijekla i znaèi...
{142439}{142462}Loš pas.
{142667}{142745}Prije 20 godina je bio moj kladionièar.
{142747}{142822}Slao sam mu svoje plate.
{143155}{143204}Bukowsky, tamo si?
{145949}{146046}Tvoja devojka me je prokužila.
{146049}{146172}Slikala me je, mora iæi pod zemlju.
{146219}{146256}U redu.
{146802}{146853}Neko mora umrijeti.
{146854}{146943}Rekao je da trebaš umrijeti.
{147395}{147413}Sranje
{147488}{147518}Pucat æe ti ovdje.
{148922}{148980}Nisam mislio da æeš razumeti.
{149389}{149423}Razumeo sam.
{149541}{149569}Kako si saznao za Liz?
{149608}{149723}Ja sam ubica svetske klase, fuckhead|Kako misliš da sam našao izlaz?
{149783}{149873}Mislim da æeš možda željeti ovo.
{150790}{150900}Hoæu iæi kuæi.|- Neæeš moæi još dugo kuæi.
{151005}{151050}Zovem se mamac.
{151052}{151142}Možeš me zvati g-din mamac.
