{1}{2}25.000
{2270}{2370}{C:$0000FF}{y:ib} MIROLJUBIVI |{C:$FF0000}{y:b} RATNIK 
{2622}{2788}PREMA ISTINITIM DOGAÐAJIMA
{5964}{6015}Teško dišeš.
{6209}{6254}Loše sam sanjao.
{6585}{6658}Sigurno si dobro?
{6726}{6764}Želiš da odem?
{6868}{6939}Ostani, ja moram na zrak.
{8789}{8877}Znate li da imate | razlièite cipele?
{8948}{9006}Jedna je malo tjesnija | od druge.
{9007}{9046}Želiš li još nešto?
{9133}{9188}Hvala na posjeti.
{10001}{10044}Što ste to napravili?
{10140}{10188}Kako ste dospjeli gore?
{10997}{11070}Jedan od nas bi trebao | napraviti potez.
{11092}{11148}Netko veæ jest. | Bog, Dory.
{11151}{11194}Hej, Tommy, Dan.
{11218}{11293}Dobro izgledaš. | - Hvala ti, Trev.
{11297}{11360}Govorio sam | komadima, kretenu.
{11363}{11405}Kako to da se sve | pale na mene?
{11406}{11439}U pravu si. Kako?
{11454}{11572}Evo ih, gospodo. | Moja slatka Barbara...
{11594}{11626}Vidiš kako nam se | nasmiješila?
{11627}{11667}Kao na reklami | za pastu za zube.
{11670}{11734}Najbjelji zubi | koje sam ikad upoznao.
{11821}{11906}To je dobro, Jansene. | Ako puno trenirate,
{11907}{11982}postižete rezultate, | tako to ide.
{12133}{12168}Dobro je, Kyle.
{12221}{12249}Izvrsno.
{12301}{12373}Tko mi još ima što pokazati?
{12374}{12444}Dobro je, Millmane. | Dobro je.
{12454}{12506}Èvrsto. Spusti | ramena. Dobro.
{12507}{12537}Drži ih èvrsto.
{12620}{12658}Dobro je, dobro.
{12673}{12750}Želim vam pokazati | nešto, treneru.
{12751}{12814}Ne troši energiju. Zaèepi.
{12864}{12905}Millman.
{13216}{13267}Oprostite, treneru.
{13268}{13354}To mi ništa ne znaèi.
{13358}{13431}Mogu to napraviti, | radim na tome.
{13497}{13537}Doði.
{13566}{13620}Nitko na ovom planetu | ne može
{13621}{13671}napraviti to što ti | pokušavaš.
{13717}{13757}Bio si izvrstan, Danny,
{13758}{13825}jedan od najboljih | koje sam vidio.
{13828}{13899}Bit æeš bolji | nego prošle godine.
{13902}{13999}I možda proðeš | kroz sve kvalifikacije,
{14000}{14070}ako se prije toga ne ubiješ.
{14120}{14171}Tommy, sad si ti.
{14257}{14302}Što pokušava izvesti?
{14303}{14377}Tri uzastopna okreta | prije skoka.
{14380}{14431}To je veæ netko nekada napravio?
{14436}{14508}Ne, zato se i trudi.
{14530}{14585}Misli da æe ga to uèiniti | Gospodarom prstenova.
{14588}{14676}Samo što Millman pokušava | sjebati i Froda.
{14679}{14744}U redu, iduæi | kvalifikacijski sat je
{14745}{14815}za 6 tjedana. I znate | što vam govorim.
{14818}{14871}Nemoj misliti | da æeš uspjeti
{14872}{14938}jer si sladak i možeš | stajati na rukama.
{14941}{15012}Mislite da se šalim? | Imam snimke konkurencije
{15013}{15104}koju opet morate pogledati.
{15995}{16033}Mogu pomoæi?
{16209}{16300}Recite mi kako ste | izveli ono.
{16353}{16482}Ti voliš da ti se sve | objasni. Zar ne?
{16694}{16733}Kako smo veèeras?
{16833}{16941}Taj krov je na bar 3-4 m.
{16965}{16992}Nitko ne može napraviti
{16993}{17036}vertikalni uspon preko 1,5 m.
{17037}{17083}Znam to, ja sam gimnastièar.
{17127}{17167}Sport za najtvrðe | ljude na svijetu.
{17168}{17217}Mnogi to ne znaju.
{17225}{17292}I Spartanci i stari Grci
{17293}{17378}bili su gimnastièari, | vježbali su nad bikovima.
{17379}{17435}I tako su trenirali | najelitnije ratnike.
{17436}{17481}Jesi to znao?
{17505}{17555}Znam više nego što mislite.
{17556}{17610}A misliš više nego što znaš.
{17613}{17683}Znanje nije isto | što i mudrost.
{17684}{17730}U èemu je razlika?
{17733}{17791}Znaš kako oèistiti | vjetrobransko staklo?
{17792}{17806}Da.
{17809}{17880}Mudrost je kada to primijeniš.
{18008}{18107}Treniram 7 dana u tjednu, | 50 tjedana na godinu.
{18110}{18191}Zašto toliko? | - Vi to ozbiljno?
{18207}{18264}Ja sam na korak | od kvalifikacija.
{18267}{18292}Kvalifikacija za što?
{18362}{18440}Gledate li Olimpijadu? | - Ne.
{18467}{18522}Hvala što ste svratili.
{18540}{18611}Lako sam dobar | kao što i jesam,
{18633}{18701}moram sve napraviti | da bih se kvalificirao.
{18744}{18812}Trebaš puno toga nauèiti, | prije nego
{18813}{18886}možeš shvatiti | to što si vidio.
{18889}{19012}Hajde, pitajte me. | Pitajte me što god želite.
{19112}{19160}Jesi li sretan?
{19230}{19301}Rekao si da te mogu | pitati što god želim.
{19313}{19352}Kako "biti sretan" | ima veze
{19353}{19399}s bilo èim? | - Ima veze sa svaèim.
{19402}{19464}Stari mi je pun love.
{19465}{19575}Škola je laka, imam | najbolje ocjene,
{19581}{19614}u izvrsnoj sam formi,
{19615}{19674}i spavam sam samo | kada ja to hoæu.
{19677}{19742}Pa zašto onda ne možeš | spavati noæu?
{19784}{19865}Juèer si bio ovdje | oko 3, sada opet,
{19866}{19918}to su dvije noæi zaredom.
{19921}{19975}Što ste vi, neki filozof?
{19976}{20023}Potrebna ti je filozofija?
{20026}{20124}Ne, hvala, Sokrate, dosta | me smatraju u školi.
{20135}{20229}Posljednje pitanje: | Ako ne uðeš u tim
{20230}{20306}za Olimpijadu, | što æeš onda?
{20377}{20402}Ako ne, što?
{20403}{20459}Sigurno si razmišljao o tome.
{20462}{20547}O èemu govorite? | - U èemu je problem?
{20621}{20689}Ne znam ni što tražim ovdje.
{20721}{20796}Vi ste nakaza i ne treba mi
{20797}{20847}zastrašivanje.
{21092}{21196}Ti bar najmanje dižeš.
{21402}{21442}Bog, ljepotice...
{21443}{21525}Znaèi, ovako se zabavljate...
{21583}{21648}17, 18.
{21777}{21823}Jeste li se ti i Dory poševili
{21824}{21862}neku veèer?
{21988}{22069}To ti je ona rekla? | - Je li istina?
{22148}{22216}Mislio sam da smo prijatelji.
{22279}{22324}Što to znaèi?
{22340}{22373}Ne treniraj prijatelje
{22374}{22414}kao što tretiraš kitu.
{22427}{22490}Neka mi netko makne pivo.
{22563}{22596}Maknite moje!
{22858}{22908}Koji ti je kurac, èovjeèe?
{22909}{22944}S prijateljem kao što si ti
{22945}{22967}komu treba šupak.
{22980}{23003}Smiri se.
{23006}{23033}Hoæeš se tuæi s Tommyjem?
{23034}{23055}Što si umišlja?
{23058}{23118}Nadrkan je na tebe. | Istina?
{23127}{23157}Mislio sam da je | Dory za njega
{23158}{23195}prošlost.
{23196}{23246}A ti oprosti zato što me zavodi.
{23247}{23287}Zašto, zašto, Dan?!
{23290}{23343}Èuješ li ti sebe!? | Dory je bila Tommyjeva cura!
{23346}{23400}Mislio sam da su prekinuli!
{23401}{23441}Vrati se svojoj zabavi.
{23470}{23502}Dobro.
{24127}{24162}Hoæeš li ovo?
{24514}{24555}Stvarno si sladak.
{24775}{24813}Isuse!
{25042}{25075}Jesi li dobro?
{25155}{25210}Da. | - Oprosti.
{25887}{25950}Što je bilo? Ponovno | ne možeš spavati?
{26256}{26299}Što biste rekli | kad bih vam rekao
{26300}{26352}da te cipele viðam | u svojim snovima?
{26355}{26408}Rekao bih da još | uvijek spavaš.
{26546}{26624}Možeš provesti cijeli život | a da se ni ne probudiš.
{26653}{26741}Sokrate, ako ste | toliko pametni,
{26773}{26839}kako to da radite | na benzinskoj postaji?
{26852}{26956}Ovo je uslužna postaja. | Mi nudimo usluge.
{26957}{27025}Ne postoji više znaèenje.
{27042}{27155}Od toèenja benzina? | - Od usluga drugima.
{27233}{27284}Kako smo veèeras?
{27979}{28022}Japanski stil, ha?
{28290}{28333}Poznaješ Sokrata?
{28347}{28440}Tako ga zoveš? | Kladim se da to obožava.
{28465}{28522}S njim si ovdje svake noæi?
{28523}{28563}To ide i tebe.
{28637}{28722}Vidim da si upoznao Joy. | - Bog, Veliki Budo.
{28725}{28773}Bog, Mali Budo.
{28782}{28877}Joy, ovo je Dan. | - Upoznali smo se. Sokrate.
{29202}{29260}Izgledaš gladan.
{29441}{29482}Joy to sprema?
{29750}{29791}Živi negdje u blizini?
{29850}{29911}Je li vam rod?
{29912}{30001}Postavljaj bolja pitanja.
{30263}{30278}Što je?
{30279}{30348}Uspori. Možda nešto i okusiš.
{30445}{30510}Imate puno pravila | o svemu, zar ne?
{30524}{30572}To nisu pravila, to su stvari
{30573}{30635}iz životnog iskustva.
{30671}{30754}Zato ti i govorim | da aljkavo jedeš.
{30774}{30837}Koga briga? | - Tebe.
{30840}{30933}Po tome se razlikujemo: | Ti treniraš gimnastiku,
{30934}{30975}a ja treniram sve.
{31007}{31052}Da sam ti ja trener, | ne bi jeo meso.
{31104}{31163}Ozbiljno? | - Ni grama.
{31211}{31244}To bih vjerojatno | mogao podnijeti.
{31250}{31318}Bez TV-a, alkohola, | droge i seksa.
{31321}{31396}Drago mi je | što mi niste trener.
{31399}{31474}Ta prehrana, i taj | trening... èine li te
{31475}{31517}najjaèim što možeš?
{31520}{31551}Naravno.
{31552}{31655}Koliko dugo možeš | stajati ovako?
{31723}{31798}Vi recite. | - 5 minuta, na stolu.
{31801}{31825}Dogovoreno.
{31972}{32036}Pomakni samo jedan | mišiæ, i zvat æu te
{32037}{32074}Jack do kraja veèeri.
{32075}{32136}Jack? | - Skraæeno od Jackass.
{33280}{33318}Koliko je prošlo?
{33392}{33430}Koliko je prošlo?
{33568}{33655}Koliko je prošlo?!
{33763}{33801}Koliko je prošlo!
{33982}{34027}To mi je sin, Jack.
{34220}{34275}Hvala na posjeti.
{34320}{34356}Svi ti govore | što trebaš raditi
{34357}{34391}i što je najbolje za tebe.
{34394}{34480}Ne žele da pronaðeš | vlastite odgovore,
{34481}{34544}veæ da povjeruješ u njihove.
{34547}{34616}Da pogodim, vi želite | da povjerujem u vaše.
{34619}{34703}Ne, ja želim da prestaneš | skupljati informacije
{34704}{34807}izvana i potražiš ih u sebi.
{34863}{34912}Jeste li vi dio neke sekte?
{34913}{34983}Ljudi se boje onoga | što je u njima,
{34986}{35091}a to je jedino mjesto koje | im može ispuniti potrebe.
{35109}{35195}Zašto ne možeš spavati? | Možda zato što,
{35196}{35298}kasno noæu, kada sve zaspi, | a ti si u krevetu,
{35299}{35384}a nema nikoga drugog | osim tebe,
{35385}{35450}možda se uplašiš.
{35488}{35643}Jer sve postaje tako prazno.
{35754}{35790}Reci mi da želiš | postati više
{35791}{35858}nego netko tko se penje | na one karike
{35861}{35931}i izvodi dobro uvježbane | vratolomije.
{35995}{36130}Reci mi da želiš biti netko | tko koristi um i tijelo,
{36146}{36244}na naèin na koji mnogi ljudi | ne bi imali hrabrosti.
{36287}{36422}A onda æu te obuèiti. | Da postaneš pravi ratnik.
{37428}{37516}Što se zbiva? | - Kyle, loše je pao.
{37651}{37685}Možda je slomljena. | - Ne.
{37688}{37776}Treba nam rendgen. | - U redu je.
{37788}{37827}Siguran sam, treneru. | - Znam.
{37830}{37881}Ne izgleda kao prelom. | - Samo æe je pregledati.
{37884}{37927}Nema potrebe.
{37996}{38041}Ja kažem da ima.
{38109}{38143}Idemo.
{38384}{38444}Loše, èovjeèe, loš pad.
{38445}{38538}Ti to ne znaš, | možda je istegnuo.
{38541}{38645}Mislim, povrijedio se, | najbolji na konju,
{38646}{38714}gdje smo onda mi.
{38717}{38750}Trevore, prestani.
{38753}{38786}A ti kao ne želiš?
{38787}{38849}Jedino što nemaš | pojma jest na konju.
{38852}{38912}Nisam usredotoèen na njega.
{38916}{38993}Jer ti imaš veliki šou, | ti jedan jedini:
{38994}{39036}Gospodar prstenova.
{39037}{39073}Hoæeš vidjeti što mogu?
{39074}{39096}Ne blamiraj se.
{39097}{39120}Idi i igraj se u pijesku.
{39121}{39156}Isuse, zar niste | maloprije vidjeli
{39157}{39199}kako odvode Kylea?
{39288}{39337}Što ako je gotov?
{39349}{39379}Nemoj meni prebacivati,
{39380}{39442}idi, drži ga za | ruku ako želiš.
{39789}{39851}Ponekad baš i ne volim sebe.
{39920}{39972}Moja je prva misao | bila, kako Kyleov pad
{39973}{40024}može olakšati meni.
{40087}{40176}Ljudi nisu ono što i misle. | Misle da jesu
{40179}{40309}i to im donosi mnogo tuge. | Dobaci mi taj kljuè.
{40357}{40422}Sada, mislim li ja?
{40431}{40482}Naravno da ne.
{40618}{40666}Peticu.
{40979}{41046}Mozak je kao refleksni organ,
{41047}{41086}reagira na sve.
{41089}{41149}Puni ti glavu milijunima | nepovezanih misli
{41150}{41184}tijekom dana,
{41187}{41270}a nijedna od tih misli | ne govori toliko o tebi,
{41271}{41338}više od bore na nosu.
{41507}{41585}Udari me. | - Molim?
{41667}{41706}Što to radite?
{41707}{41759}Hajde, 10 dolara | ako me uspiješ
{41760}{41797}ošamariti.
{41874}{41911}Hajde, probaj.
{41912}{41988}Prestanite, | ne želim vas udariti.
{41991}{42022}Ne želiš?
{42153}{42211}Ne želim vas povrijediti.
{42230}{42295}Onda te moram | i dalje šamarati.
{42538}{42587}Jesi primijetio | da desna poluga
{42588}{42653}može biti vrlo uèinkovita?
{42832}{42931}Što kad bih ti rekao | da se tvoj trening,
{42932}{43005}pa i tvoj život, | svodi na to?
{43031}{43121}Razviti mudrost tako da | nauèiš primijeniti desnu polugu
{43122}{43205}na pravom mjestu | u pravo vrijeme?
{43208}{43286}Izbaci smeæe. | - Vi ga izbacite.
{43292}{43347}Smeæe je ovdje.
{43368}{43453}To je prvi dio tvoga | treninga: Nauèiti
{43454}{43541}izbaciti sve što ti nije | potrebno ovdje.
{43660}{43698}Kako?
{43709}{43801}Naðimo se sutra | na kampusu.
{43802}{43880}Na mostu Strawberry Creek.
{43899}{43949}Kamo si ti krenuo? | - Van, a ti?
{43952}{44043}Imamo probu na konju. | - Zaboravio sam.
{44046}{44110}Za manje od sat vremena. | - Èekaj!
{44113}{44216}Prièuvaj mi ovo. | - Što?
{44574}{44674}Potpuno sam zaboravio. | Imamo važan sastanak
{44675}{44757}u dvorani. | Možemo li ubrzati?
{44797}{44826}Naravno.
{45271}{45314}Tebi se obraæam!
{45360}{45421}Koji je tvoj problem?! | - Rekao si da žuriš.
{45424}{45510}Pa si me bacio s mosta! | - Praznim ti um.
{45513}{45563}Ne, nisi, bacio | si me u rijeku!
{45564}{45635}Reci mi, dok si padao, | o èemu si razmišljao?
{45638}{45678}Ne znam. | - O školi?
{45681}{45705}Ne. | - O kupovini?
{45708}{45776}Ne! | - Vidiš, i mislima se žurilo.
{45778}{45834}Sadašnjost. | Potpuno posveæena
{45835}{45880}iskustvu koje si imao.
{45883}{45956}Èak si imao naziv | za nju. Aaa!
{46007}{46072}Skrenuo si s uma, znaš?
{46081}{46139}Trebao mi je cijeli život | da to uvježbam.
{46307}{46385}I ti trebaš skrenuti | s uma, Dan.
{46466}{46566}Èime se baviš, nekim | borilaèkim vještinama?
{46588}{46629}Ovo me je uhvatilo na prepad.
{46655}{46740}Nisi obraæao pozornost, | ni sada ne obraæaš.
{46745}{46817}Um ti se ponovno raspada, | propuštaš uoèiti
{46818}{46872}sve što se dogaða oko tebe.
{46875}{46926}Ništa se ne dogaða.
{48110}{48168}Uvijek se nešto dogaða.
{48298}{48336}Izbaci smeæe.
{48368}{48438}Smeæe je sve ono | što te odvaja
{48439}{48511}od jedine stvari | koja je bitna - a to je
{48512}{48544}ovaj trenutak.
{48547}{48604}Ovdje. Sada.
{48759}{48816}Kada æeš biti | potpuno prisutan,
{48817}{48884}bit æeš zadivljen | što sve možeš uèiniti.
{48888}{48946}I koliko to dobro | možeš napraviti.
{49057}{49098}Dok ne saznamo više | o Kyleovom stanju,
{49099}{49129}netko mora pokrivati konja.
{49144}{49216}Dakle, hoæe li | netko probati?
{49221}{49266}Evo prilike.
{49322}{49360}Gdje je Millman?
{50712}{50772}Dobro, iduæi. Trev?
{50781}{50849}Znate da sam praznovjeran, | moram zadnji.
{50852}{50885}Ja æu.
{53579}{53680}Millmane, odakle je to došlo?
{54047}{54142}Sok! Da si bio tamo!
{54143}{54196}Oduševio bi se!
{54197}{54288}Primijenio sam tvoj trik! | I uspjelo je!
{54289}{54337}Bio sam izvrstan.
{54378}{54413}To nije trik.
{54414}{54510}Što god da jest, | upotrijebio sam ga.
{54511}{54591}Izbacio sam smeæe, | a Trev, on je
{54592}{54644}jedan momak koji mi je | uvijek konkurencija.
{54645}{54714}Trebao si ga vidjeti, | uništio sam ga.
{54739}{54840}Nisam razmišljao o tome | što se dogodilo,
{54841}{54887}što je moglo biti | ili je trebalo biti.
{54888}{55073}Popeo sam se, oèistio um, | i bilo je besprijekorno.
{55173}{55219}Sada sam potpuno tvoj.
{55220}{55297}Što god trebam | raditi, napravit æu.
{55300}{55370}Bez piva, bez mesa, djevojaka | - bez problema.
{55373}{55474}Koliko si ostao takav, | èist i besprijekoran?
{55489}{55607}"...Uništio sam momka, | trebao si me vidjeti!"
{55639}{55677}To je prošlost.
{55724}{55844}Hvaljenje. A ne život | u sadašnjosti.
{55845}{55910}Ništa nisi nauèio.
{56003}{56098}Idi kuæi, trening je završen | za veèeras.
{56162}{56201}Èekaj...
{56368}{56412}Je li to sve?
{56443}{56502}Idi kuæi, rekao sam ti.
{59887}{59923}Zašto moramo biti ovdje,
{59924}{59968}odakle možemo poginuti?
{59969}{60038}Nadao sam se da mi | ti to možeš reæi.
{60286}{60439}Tata je bio u pravu, | moram naæi naèin da uspijem.
{60540}{60583}Kvragu, gdje je Millman?
{60584}{60652}Predobar je da | dolazi na trening?
{60655}{60700}Ne znam kako æu | s ovom djecom,
{60701}{60733}što da im govorim?
{60736}{60826}Prièaju, ali im se | usta ne pomièu.
{60838}{60936}Nisam im majka, | ja sam im trener.
{60937}{60998}Trener misli da | sam beskoristan.
{61008}{61123}I jesam beskoristan. | Ja sam beskorisno govno,
{61124}{61187}i Millman æe uvijek | biti bolji od mene.
{61188}{61236}Èitam im misli?
{61237}{61316}Možda ih ranije nisi | dobro slušao.
{61329}{61389}Ostala su mi èetiri | kandidata.
{61390}{61437}Moram dobro razmisliti.
{61438}{61513}Moram nešto smisliti, | život mi zavisi od ovoga.
{61644}{61691}Ovo ti nekako radiš;
{61692}{61733}inaèe sam izgubio razum.
{61736}{61816}Ponekad prvo moraš | izgubiti razum
{61817}{61866}da bi došao k sebi.
{61872}{61902}Millman.
{61975}{62073}Bilo je i vrijeme da se pojaviš. | Hvala što si došao.
{63136}{63187}Rekao sam idi kuæi.
{63643}{63684}Što si mi to napravio?
{63811}{63907}Moraš biti jak ako | želiš ovo napraviti.
{63911}{63964}Što si napravio?
{63968}{64031}Tamo kamo æu te odvesti, | i za neke stvari
{64032}{64145}koje æu ti pokazati, | potrebna ti je snaga.
{64178}{64235}Morat æeš mi vjerovati.
{64470}{64529}Vruæina je, pingvin gura
{64530}{64611}pokvareni auto i prolazi | pored sladoleda.
{64612}{64668}I tako mu glava završi | u vaniliji.
{64669}{64709}I vidi mehanièara.
{64710}{64771}Mehanièar otvori | haubu i kaže,
{64772}{64855}Izgledate kao da ste | popušili foki.
{64856}{64889}A pingvin obriše | usta i kaže:
{64890}{64944}E jebi se, ovo je sladoled.
{65078}{65126}Što ima, Tommy?
{65161}{65218}Što ima novo u zeèjoj rupi?
{65373}{65465}Hoæete još jedan? | Èovjek, patka,
{65466}{65522}i sisata èasna | ulaze u kafiæ...
{65523}{65594}Viðam se s jednim tipom. | Izveo je visok skok.
{65652}{65692}Stvarno visok skok.
{65718}{65746}I?
{65813}{65862}Radim ono što mi govori.
{65863}{65934}Želim saznati kako je to uspio.
{65943}{66036}Èekaj, puštaš nekog drugog | da te trenira? - Ne.
{66065}{66146}Što ti to radi? | Jer izgledaš usrano.
{66149}{66182}Ne znam.
{66245}{66310}Ne znam što mi radi.
{66501}{66546}Bolje prekini s tim,
{66547}{66604}imamo kvalifikacije | za 4 tjedna,
{66607}{66670}a ti izgledaš kao | bezvrijedno govno.
{67067}{67105}Joy, zar ne?
{67130}{67155}Nismo razgovarali
{67156}{67194}o zajednièkom | prijatelju.
{67205}{67240}O Sokratu?
{67269}{67317}Ako ti nije rekao | kako se zove,
{67318}{67351}neæu ti ni ja reæi.
{67354}{67467}Zašto mi nije rekao? | Ne znam ništa o njemu.
{67513}{67594}Ozbiljan sam. Trebao bi | me ojaèati, uèiniti
{67595}{67678}moj život boljim, | a izgleda da je obrnuto.
{67718}{67759}Što on to radi?
{67774}{67822}Zašto se brineš?
{67840}{67938}Želim znati s kim | imam posla.
{69598}{69719}Hajde! Èvrsto, Danny! | Ne, treseš se.
{69759}{69817}Što to radiš?!
{69920}{69966}Gotov sam za danas.
{69967}{70035}Gotov? Gotov si ti veæ dugo!
{70038}{70093}Prvo mi zaspiš na konju,
{70094}{70167}a sada jedva stojiš!
{70170}{70219}Iduæi put kada si umoran, | idi spavaj
{70222}{70295}umjesto da doðeš na trening!
{70762}{70833}Ratnièe, kako smo veèeras?
{70849}{70997}Kako sam? Umoran sam, | gladan i napaljen. Ti?
{71089}{71154}Trebaju mi neki odgovori, | veèeras.
{71187}{71282}Moram znati da ovo | neèemu vodi.
{71283}{71331}I to smjesta.
{71332}{71425}Kakav to ratnik trenira tako | što sjedi i briše zahode?
{71429}{71462}Kada postaješ ratnik, | moraš nauèiti
{71463}{71497}meditirati na svakom poslu.
{71499}{71534}Brišuæi zahode?!
{71537}{71578}Oslobodi se takvih misli -
{71579}{71654}kao što je tvoj ponos, | odstupi od ovisnosti...
{71657}{71717}Navedi jednu stvar | o kojoj sam ovisan.
{71718}{71777}Od prièanja, posebno | od upadanja u rijeè.
{71780}{71840}Od misli da sve znaš, | a ustvari ne znaš ništa.
{71843}{71895}A misliš da æe ovo | proširiti moju svijest
{71896}{71924}o bilo èemu?
{71927}{71992}Slabim u igri, trener misli
{71993}{72062}da sam na drogama, | a ja mislim...
{72101}{72182}Nemam više vremena za tebe.
{72198}{72273}Sve što imaš je ovaj trenutak.
{72335}{72415}Opet si me nazvao | Jackassom.
{72416}{72470}Jer stvarno se èudim
{72471}{72548}kako me netko | tko živi kao ti
{72549}{72608}može nauèiti bilo èemu.
{72611}{72676}Jesi li ti stvarno sretan?
{72689}{72789}Možda si jedan od onih | koji nisu mnogo ostvarili,
{72790}{72831}pa misle da je svijet | izgubljen, a da sve ove
{72832}{72858}stvari ne znaèe ništa. | Biti sretan
{72859}{72888}s onim što imaš.
{72889}{72945}Što ja to imam? Da se | zadovoljim ni sa èim?
{72946}{72988}Nazivam te Jackass | kada se ponašaš
{72989}{73055}kao Jackass. Kao sad.
{73056}{73098}Kad puštaš da te | vode emocije.
{73099}{73180}Ovo nisu emocije, | ovo je zdrav razum!
{73210}{73274}Znaš što? Da ti | kažem nešto,
{73275}{73323}kako god da se zoveš:
{73383}{73480}Kada ostvarim ono što želim, | bit æu sretan.
{73483}{73579}Stvarno sretan zauvijek, | i sve što kažem,
{73580}{73674}tako æe i biti. | Jer æu to ostvariti.
{74751}{74806}Dobro je, Danny. Izvrsno.
{74816}{74867}Tako je, mirno.
{74907}{74988}Dobro je. Hajde, | završi kako treba.
{75184}{75272}Takvog te se sjeæam. | Dobar si.
{75450}{75528}Trebalo mi je ovo. | Trebao sam pobjeæi.
{75560}{75592}Blago meni.
{75593}{75693}Blago tebi. U tako ste | dobroj kondiciji...
{75724}{75811}A djevojke kao nisu | u dobroj kondiciji?
{75812}{75879}Da se ne bavim | gimnastikom...
{75888}{75926}Bi li se onda | palila na mene?
{75929}{76053}Da ja nemam ovakvo tijelo, | bi li se ti palio na mene?
{78976}{79009}Gdje si, èovjeèe?
{79064}{79127}Ne znam što da ti kažem.
{79150}{79200}Doveo sam ti cijeli tim.
{79203}{79285}Prošao si kroz crveno, | možeš li to vjerovati?
{79288}{79339}Moraš ozdraviti | èovjeèe, inaèe,
{79340}{79398}koga æu razbijati na treningu?
{79401}{79479}Ne troši energiju, šuti.
{80506}{80542}Dan?
{80832}{80906}Tvoji roditelji èekaju dolje.
{80907}{80971}Ne trebaju mi oni, | želim znati
{80972}{81017}što se dogaða.
{81018}{81085}Reæi æu ti ali, | tvoji bi roditelji...
{81086}{81149}Ne želim da me lažete.
{81155}{81229}Noga mi je u gipsu? | Kada ga mogu skinuti?
{81230}{81306}Tvoja noga | nije samo pukla,
{81307}{81366}kost ti se smrvila.
{81378}{81473}Na 17 mjesta.
{81498}{81537}Morali smo ti izvaditi | kost iz kuka,
{81538}{81608}i prièvrstiti nogu | metalnom šipkom.
{81667}{81733}Kada je vadite?
{81806}{81837}Ona se ne vadi.
{81899}{81957}Za nekoliko mjeseci | možeš zapoèeti terapiju,
{81958}{82013}možeš razgovarati | s terapeutom.
{82014}{82096}I uz naporan trening, | siguran sam
{82097}{82163}da æeš ponovno | biti u stanju hodati.
{82214}{82294}Znam da to sada | ne zvuèi baš najbolje...
{82338}{82490}Ali s obzirom na okolnosti, | imao si sreæe.
{84275}{84318}Bog, stranèe.
{84487}{84542}Èula sam da si izašao | iz bolnice.
{84553}{84588}Kako se osjeæaš?
{84659}{84689}Dobro.
{84829}{84883}Mislila sam na tebe.
{85123}{85168}Mogu li probati nešto?
{85641}{85681}Tople su ti ruke.
{85809}{85911}Stvarno tople.
{85998}{86043}Èuo si za iscjeliteljsku
{86044}{86098}moæ dodira?
{86187}{86334}Ne. Ali možeš me nagovoriti | na bilo što.
{86396}{86454}Ne upucavam ti se, Danny.
{86615}{86657}Zar mi ne bi trebala | lijeèiti noge
{86658}{86701}umjesto prsa?
{86776}{86914}Možda mislim da ti nisu | samo noge pukle.
{87162}{87243}Znam da je ovo težak | trenutak za tebe.
{87268}{87321}Slušaš me?
{87421}{87470}Kako je stari?
{87512}{87557}Pitaj njega.
{87666}{87728}Raspituje li se o meni?
{87773}{87896}Ovo je bilo loše, | zvuèim kao...
{87897}{87983}Zvuèiš kao da ti nedostaje.
{88124}{88224}Dolazio ti je u posjetu | dok si bio u bolnici.
{88409}{88448}Vidjet æemo se.
{89726}{89762}Treneru.
{89819}{89855}Millman?
{89912}{89959}Drago mi je da te vidim.
{89996}{90071}Razvio si ramena...
{90081}{90157}Samo to i mogu: | Sklekove i rotacije.
{90232}{90277}Nešto sam razmišljao, | uskoro æe mi
{90278}{90341}skinuti ove lance, | onda se vraæam...
{90342}{90433}Moraš ih slušati. | - Imam neke ideje...
{90446}{90554}Imate slobodno mjesto | u treæoj?
{90590}{90643}Treba li vam finalist?
{90657}{90791}To je tek iduæe jeseni, | što mi daje 8 mjeseci.
{90800}{90864}Što možeš postiæi | za 8 mjeseci?
{90878}{90925}Veæ sam prijavljen | Olimpijskom odboru.
{90926}{90962}Budi realan.
{90963}{91059}Što ako se vratim | tamo gdje sam bio?
{91060}{91091}Ne biste me željeli u timu?
{91092}{91148}Naravno da bih, ali pogledaj se.
{91149}{91240}Zaboga, metalna šipka | ti spaja nogu!
{91253}{91288}Ne možete odustati od mene.
{91289}{91325}Ne odustajem.
{91326}{91397}Samo me saslušajte!
{91488}{91584}Lijeènici su mi rekli da | nema nikakvih šansi.
{91597}{91679}Nikada se više | neæeš moæi natjecati.
{94174}{94235}Isuse, Millmane, | što to radiš unutra?!
{94284}{94342}Dan, otvori! Odgovori mi!
{96479}{96522}Što hoæeš?
{97046}{97134}Nitko me ne sprjeèava, | zato se ne miješaj.
{97313}{97351}Nisam te došao zaustaviti.
{97352}{97397}Misliš da neæu skoèiti?
{97472}{97521}Nièega se ne bojim.
{97551}{97591}Èak ni ovoga.
{97656}{97694}A što kažeš na ovo?
{97786}{97819}Ili na ovo?
{97953}{98000}Pogledaj se.
{98062}{98189}Držiš se dragocjenog života. | U strahu da æeš pasti.
{98308}{98391}Ja kažem: Padni.
{98538}{98618}Nije kao da odustaješ | od neèega,
{98621}{98686}neèega što veæ nisi izgubio.
{98724}{98847}Što te to zadržava?
{99085}{99139}To si ti, zar ne?
{99184}{99238}Tebe moram izbaciti.
{99545}{99590}Znaš li što radiš?
{99655}{99689}Ne.
{99720}{99870}Znaš li tko si bez mene?!
{99988}{100158}Ne. | - Što to onda radiš?!
{102270}{102306}Hajde.
{102494}{102525}Probaj ponovno.
{102804}{102860}Ne znam što da sada radim.
{102878}{102938}Prvo saznanje ratnika.
{102967}{103046}Što je? | - Neznanje.
{103381}{103433}Što mi se to dogaða?
{103495}{103598}Nikada ne plaèem. | - Naravno da plaèeš.
{103677}{103723}To je ponižavajuæe.
{103809}{103950}Emocije su prirodne, | kao kad nadolazi kiša.
{104008}{104119}Što raditi ako | ne možete raditi
{104120}{104192}ono zašto ste roðeni?
{104193}{104313}Sve ima svoju korist. | Èak i ovo.
{104412}{104478}A na tebi je da je pronaðeš.
{104790}{104829}Hajde.
{105035}{105145}Tvoj se trening sada može | prebaciti na novi teren.
{105166}{105299}Teren na kojemu æeš | odgovore pronaæi u sebi.
{105342}{105444}Vidiš li ovu krntiju? Sjedi | na njoj dok mi ne budeš
{105445}{105514}imao nešto vrijedno reæi.
{105604}{105649}To je sve?
{105650}{105732}Ne želim te vidjeti | dok ne budeš imao reæi
{105733}{105784}nešto što je vrijedno | podijeliti sa mnom.
{105883}{105921}To je sve?
{106426}{106548}Bijes, mržnja i nasilje, | to su ustvari samo strahovi.
{106563}{106683}Strah od toga da novac nije | izvor svega zla na svijetu.
{106884}{106924}Teorija kaosa je toèna,
{106925}{106998}osim što kaos uopæe | nije kaotièan,
{106999}{107054}veæ savršeno nadziran.
{107055}{107088}Ako pozajmite nekomu | 20 dolara
{107089}{107156}i više ga ne vidite, | onda je vrijedilo.
{107172}{107219}Kada radite sendviè | od maslaca i džema,
{107220}{107324}prvo stavite maslac | a ne džem.
{107513}{107582}Ljudi koje je najteže voljeti,
{107583}{107672}najèešæe su oni kojima je | ljubav najpotrebnija.
{110208}{110270}Uvijek se nešto dogaða.
{110453}{110511}Ne postoje obièni trenuci.
{110909}{110952}Dobrodošao natrag.
{111189}{111236}Šalite se.
{111329}{111387}Ovo nije još jedna | od vizija, zar ne?
{111388}{111459}Jer ne vidim kako bi se | ovo moglo dogaðati.
{111525}{111566}Što to radiš?
{112024}{112070}Nešto nije u redu?
{112087}{112156}Prestao si s ovim, | sjeæaš se?
{112157}{112206}Znaš bolje.
{112207}{112290}Bolje od svakoga tko | ne zna ono što mi znamo
{112291}{112337}ili živi kao što mi živimo?
{112338}{112389}Na to si mislio?
{112390}{112483}Možda ne bolji... | samo pametniji.
{112516}{112576}Ne postoji nitko... bolji.
{112667}{112729}Nikada neæeš biti... bolji.
{112735}{112829}Isto tako nikada | neæeš biti gori.
{112970}{113024}Navika je problem.
{113048}{113105}Sve što trebaš jest | postati svjestan
{113106}{113192}svojih izbora, i biti odgovoran | za svoje postupke.
{113242}{113283}Zato si od svih ljudi
{113284}{113340}koje si mogao poduèavati | izabrao mene?
{113351}{113425}Prestani si laskati.
{113511}{113552}Ti si mene izabrao.
{113634}{113716}Zašto bih ti vjerovao? | Nauèio si me
{113717}{113787}da uvijek slušam | vlastitu intuiciju.
{113788}{113858}Kako znaš da ja nisam
{113859}{113929}tvoja intuicija koja ti | se upravo obraæa?
{114013}{114067}Misliš da sam te umislio?
{114270}{114326}Nemoj me tako zezati.
{114531}{114568}Svatko ima što?
{114569}{114635}Svaki postupak nosi sa sobom | cijenu i zadovoljstvo.
{114636}{114703}Prepoznaj obje strane, | i postat æeš...
{114704}{114775}Realistièan i odgovoran | za svoje postupke.
{114819}{114880}Loše zvuèiš, èovjeèe.
{114928}{114990}Sigurno se šališ.
{114991}{115042}Dajte lovu, momci.
{115043}{115125}Izabrali ste pogrešne | momke za ovo.
{115180}{115255}Poluga u pravom trenutku | i na pravom mjestu.
{115340}{115381}Tvoj.
{115409}{115474}Možemo i ubrzati transakciju.
{115607}{115651}Hvala i ugodna vam noæ.
{115709}{115776}Zar niste zaboravili | naše satove?
{115981}{116046}Imate ih, zar ne?
{116078}{116136}Možda sam trebao reæi | "njegov sat",
{116137}{116188}ja ne nosim sat.
{116223}{116262}Daj mi.
{116406}{116520}Hvala, stari. | - Koji broj jakne nosiš?
{116557}{116598}Što?
{116729}{116777}Ne treba mi tvoja jakna.
{116778}{116861}To je dobra jakna, | topla postava.
{116862}{116951}Ja æu je uzeti. | Dobra je jakna.
{117051}{117121}Ti si negdje Dannove velièine.
{117446}{117481}Koju velièinu košulje nosiš?
{117482}{117603}Šališ se? Dokle æemo ovako?
{117683}{117776}Mogli su nas ubiti! Stvarno!
{117792}{117859}Mogao si ih sve prebiti,
{117860}{117902}a umjesto toga æe nas privesti
{117903}{117933}zbog nepristojnog ponašanja
{117934}{117995}a tebi je to smiješno?
{118018}{118091}Mogao si isprebijati | svakog od njih.
{118092}{118149}Na što si mislio?
{118150}{118201}Ljudi koje je najteže voljeti,
{118202}{118255}najèešæe su oni kojima je | ljubav najpotrebnija.
{118256}{118340}Znanje nije isto | što i mudrost...
{118341}{118444}Mogli su nas ubiti. | - To je transformacija.
{118485}{118526}Smrt?
{118530}{118600}Jest da je malo | radikalnija od puberteta,
{118601}{118696}ali ne toliko da se | treba posebno uzbuðivati.
{118716}{118776}Što to prièaš?
{118811}{118936}Smrt nije tužna. Tužno je to
{118952}{119027}što mnogi ljudi uopæe | ni ne žive.
{119214}{119270}Je li to dvostruki dupli?
{119342}{119419}Ne, to je puni dupli okret. | Ali trudim se
{119420}{119481}napraviti dvostruki dupli...
{119536}{119599}Prvi dan | bez pomoænih sprava,
{119600}{119671}bez lanaca i štaka.
{119799}{119863}Došao sam samo da...
{119934}{120001}Znam da nisam uvijek bio | dobar prijatelj.
{120072}{120134}Ustvari, ne mogu se sjetiti
{120135}{120210}kada sam zadnji put bio | neèiji dobar prijatelj.
{120307}{120398}Stvari su takve. | Što da radimo
{120399}{120477}kada se stalno | meðusobno natjeèemo?
{120542}{120644}Došao sam vam reæi...
{120645}{120750}Èekaj, Trev... | on se isprièava?
{120776}{120819}Èini se.
{120876}{121156}O, Bože! Gotov je! Pada! | Sestro, defibrilator! Brzo!
{121157}{121265}O, ne! Bože, bolje mene uzmi!
{121266}{121329}Uzimao sam zdravo za gotovo
{121330}{121399}sve što radim, bio sam aljkav.
{121412}{121462}Bojim se, ali...
{121477}{121561}Osjeæam se kao da | sam se otarasio starih stvari,
{121608}{121660}i to je dobro.
{121662}{121719}Kada osjetiš strah...
{121818}{121870}Posluži se maèem.
{121915}{121986}Zamahni njime | i rasijeci um na komade,
{121987}{122052}odstrani sva pokajanja | i strahove
{122053}{122097}i sve ostalo što | živi u prošlosti
{122098}{122139}i buduænosti.
{122140}{122212}Hoæu li to moæi?
{122213}{122264}Mislim da sam spreman.
{122265}{122320}Spreman na što?
{122324}{122392}Da posvetim život | višem cilju.
{122396}{122439}Stvarno?
{122442}{122506}Služiti drugima, zar ne?
{122565}{122626}Od sada æu to biti | ja, radit æu sve
{122627}{122656}što misliš da trebam.
{122657}{122690}U redu.
{122691}{122783}Mislim da trebaš da | nastaviš s treninzima.
{123123}{123210}Ratnik ne odustaje | od onoga što voli.
{123228}{123321}On pronalazi ljubav | u onome što radi.
{123322}{123414}Pogledaj me! Pogledaj me!
{123485}{123570}Imam metalnu šipku u nozi!
{123571}{123661}Biti ratnik ne znaèi | savršenstvo, ni pobjedu,
{123679}{123729}ili neranjivost.
{123752}{123898}On baš treba biti ranjiv, | jer je to najveæa hrabrost.
{123899}{123974}Kako da treniram? | Imao sam nesreæu.
{123975}{124056}Nesreæa i jest trening. | Život je izbor.
{124057}{124097}Možeš izabrati biti žrtva,
{124098}{124133}ili bilo što drugo što poželiš.
{124134}{124166}Da samo ignoriram to | što mi se dogodilo?
{124167}{124220}Ratnik postupa, | samo budala reagira.
{124221}{124290}A ako ne uspijem? | - To je buduænost, baci je.
{124291}{124321}Odakle da poènem?
{124322}{124423}Ne postoji poèinjanje ili | prestajanje, samo èinjenje.
{124524}{124568}Želim ti pokazati nešto.
{124957}{125072}Kada si ovo napravio? | - Dok si ležao u bolnici.
{125139}{125178}Dok sam što?
{125356}{125442}Sada možemo | prionuti na posao.
{129494}{129537}Uopæe ti ne vjerujem. | - Ozbiljan sam!
{129538}{129569}Misliš na onu crvenokosu?
{129570}{129627}Ne, na tvoju curu.
{129628}{129661}Od kada je ona moja cura?
{129662}{129700}Prièao si s njom cijelu noæ.
{129701}{129766}Prebacio sam je na tebe. | - O kojoj prièamo?
{129839}{129880}Hoæemo li u troje?
{129984}{130047}Stvarno nisi moj tip.
{130313}{130351}Što biste mi rekli | kada bih vam rekao
{130352}{130415}da sam opet spreman za karike?
{130536}{130627}Rekao bih da si | sjebao glavu, a ne nogu.
{130949}{130982}Zdravo, treneru.
{131269}{131312}Je li ovo tvoje?
{131394}{131428}Prièekaj.
{131813}{131885}Ostavite nas nasamo, momci.
{131911}{131955}Što se zbiva?
{131977}{132034}U redu je, ne treba.
{132065}{132093}Ovo mi je u uredu
{132094}{132136}veæ par dana.
{132171}{132209}Mislio sam da neæu | imati potrebu
{132210}{132252}da ti predam.
{132257}{132313}Olimpijski odbor je glasovao
{132314}{132384}o tvom zahtjevu | za odlaganje sudjelovanja
{132385}{132451}pri kvalifikacijama.
{132478}{132517}Žao mi je.
{132669}{132716}Podnio si zahtjev | Olimpijskom odboru?
{132717}{132783}Savjetovali su se | s tvojim lijeènicima
{132784}{132810}i saznali da,
{132811}{132852}da ne postoje dokazi
{132853}{132914}da si dovoljno sposoban | da bi se natjecao.
{133004}{133055}Tako piše...?
{133097}{133139}Ne.
{133209}{133256}Piše da možeš | promijeniti tu odluku
{133257}{133318}ako dokažeš suprotno.
{133364}{133410}Rekao sam da mi je žao.
{133411}{133460}Samo me gledajte.
{133463}{133532}I recite mi da ne vidite dokaz.
{133533}{133584}Ne želim gledati momka, | koji je bio u gipsu
{133585}{133614}prije deset mjeseci,
{133615}{133649}kako pokušava | izvesti trostruki okret.
{133650}{133710}Prvo me pogledajte | pa mi to recite.
{133711}{133745}Lijeènici su mi rekli | da možeš
{133746}{133786}ostatak života provesti | u kolicima!
{133787}{133873}Mislite da mi je to bitno!? | - Ne, Dan.
{133874}{133924}Jer ja te poznajem.
{133925}{134001}Mogao si se ubiti na tim | karikama sto puta,
{134002}{134102}a ja nisam spreman gledati | kada se to i dogodi!
{134205}{134328}Veæ sam se obratio Odboru, | i zatvorili su sluèaj.
{134487}{134532}Odustali ste od mene.
{134688}{134731}Hajde...
{134799}{134856}Odustali ste od mene.
{135406}{135460}Gotovo cijelo èovjeèanstvo | reagira
{135461}{135516}kao i ti.
{135535}{135584}Ako ne dobiješ | ono što želiš,
{135585}{135625}patiš.
{135657}{135745}A i kada dobiješ | toèno ono što želiš.
{135746}{135858}Opet patiš, jer to ne možeš | zadržati vjeèno.
{135869}{135925}Trener misli da | ne mogu nastupiti.
{135926}{135961}To nije važno.
{135962}{136025}Zna da æu biti tamo.
{136026}{136073}Ne treba ti on | ili bilo tko drugi
{136074}{136120}da bi se popeo na karike | i radio ono što voliš!
{136121}{136209}Treba mi! Prièam | o tome da sudjelujem
{136210}{136265}i pokušam osvojiti zlato.
{136266}{136336}Zlato nije bitno. | "...kada bih ga imao,
{136337}{136369}bio bih sretan".
{136370}{136433}Zar se ne èuješ? | - To su moji snovi.
{136434}{136484}Ne mislim da je | loše imati snove.
{136485}{136571}Ne trebaš se predati | svojim snovima.
{136572}{136606}Trebaš se predati | jednoj stvari
{136607}{136701}koju nikada nisi imao | niti æeš imati - kontroli.
{136716}{136752}Prihvati da ne možeš | kontrolirati
{136753}{136808}ono što ti se dogaða.
{136809}{136873}Da možda hoæeš | ili neæeš sudjelovati
{136874}{136924}na Olimpijadi.
{136925}{137002}Da možeš ili ne možeš.
{137008}{137123}I da možeš biti | nešto posebno.
{137134}{137210}Bio sam spreman | odustati od svega.
{137211}{137282}Ali ti si me uvjerio | i rekao mi
{137283}{137326}da želiš da treniram.
{137327}{137377}Rekao sam ti da ratnik | radi ono što voli.
{137378}{137491}I ja ovo volim! | - Da trèiš za zlatom?
{137493}{137600}Da živiš u strahu | da neæeš uspjeti,
{137601}{137631}to voliš?
{137632}{137727}Ne! Da | sudjelujem i pobijedim!
{137728}{137773}Da radim ono za što | sam oduvijek mislio
{137774}{137838}da sam stvoren.
{137839}{137902}Bio sam na trambulinu | prije nego na biciklu
{137903}{137969}jer sam ga zavolio.
{137983}{138054}Jer je to bila prva stvar...
{138107}{138202}Za koju sam bio siguran | da volim.
{138402}{138514}Oprosti.
{138581}{138650}Mislio sam da sam | dovoljno jak,
{138651}{138716}ali nisam.
{138733}{138781}Jer stvarno sam se trudio | da odustanem
{138782}{138836}od svega ovoga,
{138939}{138986}ali ne mogu.
{140323}{140420}Sutra ujutro ponesi | cipele za planinarenje.
{140487}{140593}Postoji mjesto na | koje te želim odvesti
{140594}{140661}još od prve noæi.
{140698}{140843}Velik je uspon, ali mislim
{140844}{140912}da si napokon spreman | da ga vidiš.
{141447}{141558}Postoje tri pravila? | - I veæ ih znaš.
{141574}{141676}Paradoks, humor i promjena.
{141688}{141722}Paradoks.
{141737}{141809}Život je misterija, ne gubi | vrijeme pokušavajuæi
{141810}{141859}otkriti suštinu.
{141860}{141896}Humor.
{141897}{141986}Zadržati smisao za humor, | pogotovo prema sebi,
{141987}{142030}snaga je sama po sebi.
{142031}{142067}Promjena.
{142247}{142291}Sve se mijenja.
{142459}{142558}Hoæeš li mi reæi kada | se približimo?
{142689}{142794}Sok, prošlo je tri sata. | - Stigli smo.
{142935}{142964}Gdje to?
{142965}{143016}Na mjesto koje ti | želim pokazati.
{143162}{143243}Vidik? | - Ne, pored tvoje noge.
{143404}{143453}Cvijet? | - Ne.
{143454}{143514}Samo da nije... | - Kamen.
{143618}{143716}Postoji li nešto | osobito u vezi s njim?
{143722}{143749}Nešto nije u redu?
{143750}{143786}Daj, molim te.
{143787}{143831}Ovo sam napokon bio | spreman vidjeti?
{143832}{143878}Tijekom cijelog puta | bio si uzbuðen,
{143879}{143898}bio si sretan.
{143899}{143932}Jer sam mislio | da æu vidjeti nešto!
{143933}{143982}Bio si kao dijete | za vrijeme Božiæa.
{143983}{144056}Sam si rekao da ti je | godio ovaj put.
{144057}{144093}Zato što sam protekla | tri sata
{144094}{144155}išèekivao da vidim | tu prelijepu stvar!
{144156}{144222}A tu je samo ovaj kamen!
{144283}{144370}Vjerojatno sam ti trebao reæi | prije nego smo krenuli.
{144389}{144431}Ali pretpostavljam
{144487}{144557}da ni ja nisam | znao što æemo pronaæi.
{144594}{144648}Nikada nisam bio siguran.
{144788}{144862}Oprosti što više nisi sretan.
{145179}{145214}Putovanje...
{145427}{145557}Putovanje nam donosi sreæu, | a ne odredište.
{146173}{146209}Millman.
{146279}{146319}Što to radiš?
{146424}{146483}Izvadi ruke iz krede.
{148254}{148300}Spreman za veliki dan?
{148301}{148376}Da, veèeras se pakiram.
{148500}{148545}Kamo si krenuo?
{148615}{148691}Samo trèim. | - S knjigom?
{148745}{148836}Zapravo, krenuo sam | poljubiti te.
{149002}{149050}Imaš li što reæi?
{149108}{149151}Sretno sutra.
{149171}{149262}Zamišljam nas zajedno. | Mene i tebe.
{149273}{149400}Sanjam neke stvari! | Ponekad se neke ispune.
{149524}{149623}Samo ti govorim da stvarno | mislim da se mogu ostvariti!
{149634}{149678}Onda možda i hoæe.
{150454}{150501}Jesi li na ovo mislio?
{150871}{150930}Tko si ti? | - Tko si ti?
{150941}{151005}Gdje je drugi èovjek | koji radi ovdje?
{151011}{151058}Danas sam poèeo.
{151125}{151197}Ako ti treba benzin, | posluži se sam.
{152290}{152368}Gdje ti je tajno oružje? | - Ne znam.
{152406}{152456}Kako to misliš, | ispalio te je?
{152457}{152513}Idemo li dalje?
{152712}{152810}Je li ti ikada rekao | kako se popeo na krov?
{152859}{152900}To nije bitno.
{153601}{153676}Vrlo visoka ocjena. 9.3 | za Davida Bloodgooda
{153677}{153724}što ga stavlja meðu | 7 najboljih
{153725}{153754}u dosadašnjem dijelu natjecanja.
{153770}{153817}Konkurencija je | ove godine žestoka.
{153818}{153891}Ne sjeæam se | da je nekada bilo ovako.
{153892}{153939}I to s dobrim razlogom. | Za one koji ste se
{153940}{154032}sada ukljuèili, ovo æe | odluèiti koja æe 6-orica
{154033}{154112}predstavljati SAD
{154113}{154168}na predstojeæoj Olimpijadi.
{154260}{154361}Dobro, samo mi pokaži rutinu.
{154412}{154501}Bez trostrukih okreta, | pokaži im.
{154519}{154590}Popni se i budi to što jesi.
{154681}{154777}Iduæi su | sa sveuèilišta Berkeley.
{154940}{155007}Kako je? Usredotoèen?
{155090}{155125}Ti si napravio nešto | što mi ne možemo
{155126}{155192}ni shvatiti, znaš to?
{155253}{155313}To je kao èudo, Danny.
{155400}{155506}Što god da si nauèio, | i što god da ti je pokazao,
{155571}{155684}misliš li da bi mogao | prebaciti
{155685}{155767}malo te èarolije na mene?
{155838}{155892}Nije to èarolija.
{155929}{156019}Samo moraš izbaciti | sva ta sranja iz glave
{156020}{156080}koja ti govore | da nisi dostatan.
{156163}{156283}Popni se i napravi | svaki potez
{156284}{156343}zbog njega samog.
{156357}{156434}Ne zbog zlata, ili | zbog toga što tvoj otac misli,
{156435}{156525}ni zbog èega drugog.
{156582}{156645}Veæ zbog tog jednog | jedinog trenutka.
{156712}{156766}Ali ovo je za zlato!
{156852}{156931}Sve što mi radimo, | bar što se mene tièe,
{156932}{157003}cijeli moj život jest da uspijem | izdržati 20 sekunda
{157004}{157101}ispred sudaca, | da bi mi dali to zlato.
{157159}{157198}Želiš li znati što bi | otac mislio o meni
{157199}{157246}ako bi se to dogodilo?
{157279}{157306}Želiš li znati kako bi mi se
{157307}{157353}život promijenio?
{157355}{157413}Kako bi mi svaki problem
{157414}{157472}koji imam sada | postao beznaèajan?
{157475}{157533}Dobio bih sve što želim.
{157617}{157662}Postao bih sretan.
{157732}{157788}Postao bih sretan, Danny.
{157893}{158073}Iduæi je | Dan Millman iz Berkeleyja.
{158074}{158114}Dan je vrlo uporan sportaš,
{158115}{158157}jer je prije samo 10 mjeseci
{158158}{158257}ozlijedio nogu u | motociklistièkoj nesreæi.
{162634}{162732}Gdje si, Dan? | - Ovdje.
{162750}{162830}U kojem vremenu? | - Sada.
{162861}{162966}Što si ti? | - Ovaj trenutak.
{164500}{164570}Dan Millman i njegov tim | napredovali su
{164571}{164657}i osvojili | prvu nacionalnu titulu.
{164738}{164796}Dan je postao autor knjiga
{164797}{164868}koje nadahnjuju | milijune ljudi diljem svijeta.
{164869}{164959}Živi u Sjevernoj Kaliforniji | sa svojom ženom Joy.
{164980}{165085}{C:$0000FF}{y:ib} d |{C:$FF0000}{y:b} d 
