{2290}{2400}SCENARIJ I REŽIJA
{3115}{3209}Još... Još...
{3273}{3359}P O R N O   F I L M
{4379}{4454}Da, izvolite.
{4484}{4555}Koji kolega?
{4563}{4664}Ah, Polde, da.|Što vas muèi?
{4671}{4756}Da, i to možemo obaviti.
{4818}{4905}Pa, sve vrste|utjerivanja i prijetnji,
{4909}{5004}vrlo diskretno|obavljamo na slovenskom.
{5008}{5063}Petak, 17. rujna.
{5068}{5136}Janez je išao sa mnom|u razred u aranžerskoj školi.
{5141}{5199}SUDBONOSNI POZIV|Godinama ga nisam vidio.
{5203}{5301}Znao sam samo da ima negdje|kod Ljubljane javnu kuæu.
{5306}{5398}UTJERIVANJE DUGA|A onda me nazvao.
{5403}{5512}Kuda da idem s tobom?
{5516}{5559}Veèeras imam teže utjerivanje|i treba mi još netko,
{5563}{5619}samo za broj, da budemo trojic|Dogovoreno? -Ali...
{5623}{5698}Gdje si baš mene našao?|Vidi kako izgledam, molim te.
{5701}{5788}Èekaj malo. Dobit æeš|milju maraka na ruke i zaèepi.
{5793}{5871}Samo mi reci|tko æe se mene bojati?
{5874}{5979}Ti æeš biti tu samo zbog|broja, tako da budemo trojica.
{5983}{6030}Je li u redu, sine?
{6241}{6302}Eno, tamo je, vidi ga.
{6726}{6823}Znate li se vas dvojica?|-Naravno. Bok, stari.
{6887}{6974}I Frank je išao|u aranžersku školu.
{6979}{7083}U drugom su ga razredu|izbacili jer je dilao travu.
{7089}{7166}Išao mi je na živce,|otkako ga poznajem.
{7181}{7259}Moram reæi da me je|i tog utjerivanja bilo strah.
{7268}{7332}UTJERIVANJE DUGA
{7609}{7707}Ako bude htio razgovarati, OK,|a ako ne, razbit æu ga.
{7712}{7808}Ja æu sve obaviti, a vas|dvojica samo imajte mrke face.
{7951}{8032}Pa gdje æu ovdje|pronaæi tog maèiæa?
{8919}{8999}I što sad, ha?
{9022}{9105}Pokušajmo ovdje.|-Misliš?
{9537}{9616}Da li možda ovdje negdje živi|godpodin Drago Rakoèeviæ?
{9620}{9701}Ja sam.|-Onda smo na pravom mjestu.
{9706}{9767}Mi smo iz|"Finance-Consulting d.o.o."
{9771}{9833}Došli smo riješiti|jedan vaš problemèiæ.
{9838}{9936}Možemo li uæi da susjedi|ne gledaju? -Možete.
{10828}{10914}Jebem ti takvo|utjerivanje dugova!
{11093}{11154}Jedan krug za sreæu.
{11159}{11232}Èovjeka jednostavno|peèe savjest.
{11255}{11355}Najradije bih naruèioca|namlatio k'o majmuna,
{11360}{11454}umjesto onog jadnika,|zar ne, Èarli?
{11459}{11532}Radije bih se prezivao Jebiæ.
{12278}{12358}Frenk je predložio da|osnujemo heavy metal bend.
{12362}{12441}VRAŽJE SJEME
{12454}{12519}Daj, ne seri.
{12543}{12678}Imam još jednu ideju.|-Reci veæ jednom koju.
{12736}{12827}Što je to?|-Hej, stari...
{12857}{12972}Ideja je da snimimo porniæ.
{13049}{13125}Što je, ti bi|besplatno guzio, ha?
{13131}{13205}Jebem ti tvoje traume|iz djetinjstva, budalo jedna.
{13211}{13295}Pa, dobro, što je? Kad|si ti budala, sve je u redu.
{13301}{13405}Da, onda je sve u redu.|-Pa nek' ti bude.
{13411}{13526}Meni se ta ideja|ne èini lošom.
{13530}{13610}Koja ideja?|-Pa ta, da snimimo porniæ.
{13615}{13669}Ma daj, ne seri.
{13673}{13773}Slušaj, prije si rekao da se|ovdje ne može praviti biznis.
{13778}{13865}Stari, to je|garant dobar biznis.
{13870}{13950}Garant. Malo æemo|se potruditi i bit æe.
{13955}{14022}Èovjeèe, ako je itko|vidio više porniæa od tebe...
{14027}{14111}Ti si ekspert za porniæe.|Doktor pornografije. -Toèno.
{14134}{14252}Glumiti neæu,|ali mogu režirati.
{14257}{14335}Dobro, prepuštamo|ti režiju, ali æeš i glumiti.
{14339}{14408}Naravno, stari,|neæeš samo svijeæu držati.
{14413}{14486}Glumite vas dvojica,|jebo te, dosta je.
{14491}{14542}Ne, ne. Svi ili ništa.
{14547}{14623}Prvi porniæ u Sloveniji...|Bit æemo prave face.
{14628}{14755}Zauvijek æemo biti slavni u|Sloveniji. Možda i u svijetu.
{14771}{14939}Možda to zvuèi èudno, ali mene|peèe savjest zbog domovine.
{14943}{15051}Stalno zaraðujem,|a ništa ne dajem zauzvrat.
{15057}{15134}S porniæem bi se|fino mogao odužiti.
{15139}{15231}Stari, to si dobro rekao.|-Jesi ti malo udaren?
{15236}{15322}Koliko æe biti love!|Hajde, budi frajer.
{15327}{15391}Režirat æu. To je OK.
{15396}{15499}O mama, mama,|želim na Jamajku...
{15591}{15714}Želim na, želim na Jamajku...
{15725}{15830}Prema suncu|vodim svoju barku...
{15836}{15954}O mama, mama,|želim na Jamajku...
{16517}{16602}U 12:00.|I dobro se naspavaj.
{16731}{16830}Istina je da su porniæi bili|moj hobi još od osnovne škole.
{16835}{16904}Pregledao sam ih|sigurno par tisuæa.
{16909}{17000}Istina je i to da važim kao|ekspert za to podruèje,
{17005}{17109}ali me je ipak iznenadilo što|sam tek tako ušao u taj posao.
{17114}{17160}REŽISER
{17163}{17264}Još jutros sam bio aranžer,|a zaspao sam kao režiser.
{18931}{18999}Subota, 18. rujna.
{19004}{19055}ANTAGONISTI
{19060}{19118}Uporedo su se dešavale stvari|o kojima nisam imao pojma,
{19123}{19199}i na koje nisam|imao nikakvog uticaja.
{20512}{20600}Poslali smo vam|pismo sreæe...
{20984}{21081}Oprosti što kasnim. Jedva sam|našao mjesto za parkiranje.
{21086}{21196}Ni Janeza još nema.|U pizdu materinu!
{21284}{21328}Brèiæi?
{21333}{21383}To je zbog filma.|Imaš li što protiv?
{21388}{21486}Znaš što, jedva èekam da|vidim jebaèice.
{21496}{21593}Daj, malo ljepše govori|o njima. Tako ih ponižavaš.
{21598}{21671}Rodio sam se s kompleksom veæe|vrijednosti. Ne mogu pomoæi.
{21676}{21743}Ionako sam to lijepo mislio.
{21748}{21833}Da, vidim, rodio si se|malo drugaèiji od ostalih.
{21838}{21920}Ah, što æu.
{21929}{22013}Razmišljao sam o porniæu|i imam nekoliko super ideja.
{22018}{22119}Jesi li ti na nekim vitaminima|pa si tako zagrijan?
{22138}{22249}Fafi ima opet menstruaciju?|Jebi ga! Svakih 14 dana.
{22260}{22359}Ne znam, reci, izgubit|æu još jednu stranku.
{22366}{22467}Da mu ga ja popušim|kad ona ne može?
{22472}{22567}Boje moraju biti dobre|i slika oštra i jasna.
{22572}{22693}Drugo: koža ne smije biti kao|jogurt. Svi moramo u solarij.
{22698}{22793}Ili u mikrovalnu.|Jeb'o te, jesi ti pametan.
{22798}{22848}Znaš što sam primjetio?
{22853}{22940}Da ti ne odgovara ništa|što u zadnje vrijeme govorim.
{22945}{23014}Sad sam veæ malo uvrijeðen.
{23018}{23117}Govori manje gluposti i sve æe|biti u redu. -Dobro, da znam.
{23154}{23249}Hoæeš malo?|-Èega? -Vruæeg psa!
{23254}{23365}Ti si jedan drkadžija. -Da|mi to nikad više nisi rekao,
{23370}{23439}pizda ti materina, inaèe æu|ti k'o labudu zavrnuti vrat.
{23444}{23527}Ti?! Ti?! Pravi...
{23903}{24007}Žene su nekada jednom|mjeseèno imale mentruaciju.
{24012}{24153}Fafi je, prema mojoj|evidenciji, ima svaka 22 dana.
{24158}{24259}Èarli, sad izraèunaj 365|dana podijeljeno sa 22.
{24264}{24307}Da pritisnem na crveno?|-Na crveno.
{24312}{24406}Znaèi 365 podijeljeno sa|koliko? -Sa 22. Koliko je to?
{24412}{24492}Stari, to je 16,5!
{24508}{24623}Znaèi, godišnje|4,5 mentruacije viška.
{24629}{24705}Za poèetak možeš uvesti "last|minute". -Kako to misliš?
{24709}{24801}Pa, kao turistièke agencije.|Ja mislim ovako...
{24805}{24896}Za one cure koje|dobiju dan kasnije...
{24898}{24959}menzes...
{24964}{25086}menstruaciju... daš 30%|popusta. Stranke æe pošiziti.
{25091}{25154}Nije ti to loše|"last minute", stari.
{25159}{25230}Pa, stari, ti nisi tako glup|k'o što sam mislio.
{25235}{25316}Znao sam koga treba uzeti za|režisera porniæa. -Slušaj...
{25320}{25390}I glumca. -Glumca ne.
{25395}{25481}Ta je ideja iz jednog od|mojih omiljenih porniæa.
{25486}{25583}Stvarno. Zove se|"Nektar". Njemaèki je.
{25588}{25683}Kravata ti je stvarno|super. Vidi ovo, Frenk.
{25687}{25821}Znaš, i te dlaèice koje imaš|umjesto brkova, su mega.
{25827}{25926}Imam ih zbog porniæa, stari.|Je su dobre? -Super, izvrsne.
{25931}{26045}Snimiti moramo dobar porniæ.|Mislim da se obojica slažete.
{26050}{26132}Tako je. -Takav koji æe biti|zanimljiv cijelom svijetu,
{26137}{26214}a ne kao neki slovenski film,|koji nitko ne razumije.
{26218}{26341}Film koji ima svoju prièu,|koji govori o nama samima.
{26351}{26415}To je to. -U redu.
{26420}{26475}l, kako stoje|cure sa slovenskim?
{26479}{26565}Èarli, slovenski možda|i nije baš najbitniji.
{26571}{26637}Ti šuti, svakako ti je|samo jebaèina na pameti.
{26642}{26706}Istina, to si u pravu,|potpuno se slažem.
{26712}{26767}Budi sretan da æeš|besplatno guziti. -I jesam.
{26773}{26848}Kako cure govore slovenski?|-Jako slabo, moram ti reæi...
{26854}{26955}Znao sam! -Uglavnom govore|ruski. -Vidiš? -Pa, dobro.
{26958}{27065}Verbalna komunikacija nije|glavna, ali je ipak bitna.
{27070}{27154}A kakve su inaèe? -Što se|tièe neverbalne komunikacije
{27159}{27258}tu su najbolje, prave|profesionalke. To garantiram.
{27263}{27371}Dobro, ali zanima me još kakve|su sa glumaèkim talentom.
{27376}{27470}Roðene glumice.|-No, dobro. -Zaista.
{27475}{27575}Volio bi da porniæ bude tako|dobar, da se ljudi u svijetu,
{27579}{27661}kada ga budu gledali, pitaju:|"Pa gdje je ta Slovenija?"
{27666}{27737}Da, to sam htio. -Mislim,|pošto prave takve porniæe.
{27743}{27783}Da. -Toèno tako.
{27788}{27872}Volio bih da bude Slovenija|što je nekada bila Danska.
{27876}{27987}Tako se govori. Nakon|audicije æu sastaviti ugovore,
{27992}{28088}da stvari budu èiste i da ne|kompliciramo oko novca. Važi?
{28097}{28167}Važi? -Što se|mene tièe - super.
{28524}{28597}A sada akcija, stari.
{28602}{28688}Što je sad? Hajde.|Hajde, idemo.
{28870}{28927}AUDICIJA
{28950}{29063}Ja govoriti slovenski|i htjeti sebe snimiti na film.
{29069}{29152}Znate li možda glumiti?|-Da.
{29157}{29237}Da. Ja uèila|u dramski sekciji...
{29242}{29328}Pa, to obeæava. -Da.
{29358}{29439}"SAMO ZA JNA"
{29444}{29520}Može li se to izbrisati?|-Misliš da to smeta?
{29524}{29602}To? -Da. -Smeta!
{29608}{29690}Veæ si glumila|u maðarskom porniæu?
{29878}{29960}Da, ja veæ glumila|u porno filmu u Budimpešti.
{29965}{30079}Super. Kako se zvao?
{30084}{30145}"Intimni kutak"
{30149}{30209}"Intimni kutak"?
{30215}{30306}Fafi je na bolovanju, ali|njena specijalnost je oralni,
{30311}{30392}tako da nema frke. -Da li|bi glumili u našem filmu?
{30397}{30531}Ja? Ja dama...
{30605}{30697}Nisam ja baš siguran u ovaj|porniæ, to vam moram priznati.
{30751}{30839}Pokaži... mastrubacija.
{30845}{30925}Ono, s dvije ruke...
{30973}{31053}Da, unutra, tako...
{31523}{31591}To! -To!
{31600}{31705}Da li bi glumila|u našem filmu? -Da.
{31719}{31841}Ja uvijek htjela snimati film.|-Ali, u porniæu, žestokom?
{31846}{31918}To svejedno. Kino je kino.
{31923}{32007}Pa ti si prava sineastka.|Fantastièno. Dobila si ulogu.
{32015}{32073}To! Hvala.
{32078}{32156}Siði. Neka doðe Kalinka.
{32161}{32232}Marina je super. Ja bih|je htio odraditi u filmu.
{32238}{32316}I kao zadnja danas,|miss Kalinka!
{33241}{33323}Kalinka, što je to bilo?
{33333}{33409}Maršak.|-Maršak?!
{33413}{33481}Zašto si nam recitirala?
{33486}{33583}Džon rekao|pripremiti dobar nastup.
{33587}{33672}Bilo je lijepo,|ali malo dosadno.
{33677}{33786}Kalinka, reci ti meni što|se tebi u seksu najviše sviða.
{33831}{33905}Sve.
{33939}{34065}Sve u veza sa seks|mi se najviše sviða.
{34070}{34185}Sve što je u vezi sa seksom|ti se najviše sviða. Bravo!
{34189}{34324}Kalinka, da li bi ti|glumila u našem filmu?
{34350}{34428}Zato ja biti ovdje.
{34432}{34556}Dobra je,zar ne?|U filmu æe biti tvoja, Èarli.
{34572}{34645}Kalinka - Èarli.
{34723}{34812}Na film!|-Na zdravlje!
{35078}{35133}Hej, Janez? -Što je?
{35138}{35232}Kad bi mogli poèeti vježbati?|-Kad cure budu slobodne.
{35271}{35396}Ti slobodna sada?|-Sada? -Da, sada.
{35406}{35534}Možemo, Džon?|-Da, idite u sobu.
{35544}{35647}Proba. Razumiješ?
{35697}{35794}Stari, kako sam|ja sretan èovjek!
{35949}{36005}Ovaj Frenk je totalni|seksualni manijak.
{36010}{36114}Što æeš. Neka uživa,|ionako nema puno od života.
{36117}{36185}A ti?
{36189}{36310}Cure treba što|prije uèiti slovenski.
{36314}{36435}Hoæemo, ali ti si Kalinkin.|Možeš iæi u sobu.
{36448}{36505}Što? -Što "što"?
{36510}{36565}Jesi li lud, stari?|-Što "lud"?
{36571}{36630}Sa ovom tisuæu puta|pojebanom fuficom?
{36635}{36710}Daj, molim te. Garant smrdi.|Radije bih se prezivao Jebiæ.
{36715}{36807}Ne znaš što propuštaš. Ja|rijetko cure dajem besplatno.
{36812}{36881}To su jadne cure.
{36888}{36988}Slušaj, nijedna nije toliko|jadna da ti nema što ponuditi.
{36992}{37072}l, nije lijepo da|o curama tako govoriš.
{37076}{37163}Znaš kakva je u Rusiji kriza.|Kužiš, one su ovdje zato,
{37168}{37238}da bi takvima, kao što|si ti, bilo dobro. Kužiš?
{37243}{37318}Da prežive. Da imaju|od èega živjeti. -Znam.
{37322}{37422}Idi u sobu inaèe|æe ti zamjeriti.
{37445}{37521}Što æe mi|zamjeriti? Što prièaš?
{37526}{37660}Idi u sobu i uèi je slovenski.|Hajde, Kalinka.
{38745}{38834}Nije ti hladno?|-Hladno.
{38886}{38947}Hvala.
{39136}{39249}Ti pustio usy?|-Brkovi. Za porniæ.
{39354}{39429}Ne sviðaju ti se?
{39435}{39522}Ne sviðaju?|-Sviðaju.
{39636}{39712}Ti mene ne voliš?
{39722}{39800}Nije to to.
{39805}{39926}Ti si jedna od najljepših|cura koje sam ikada vidio.
{39930}{40045}Uživo. Kako se zoveš?|Nisi Kalinka, zar ne?
{40050}{40165}Ne. Kalinka moje umjetnièki|ime. Moje ime Olga. -Olga...
{40178}{40260}Ja sam Èarli. -Èarli!
{40294}{40371}Ustvari sam Karli,|samo me zovu Èarli.
{40375}{40469}Kao i Frenka.|On je ustvari Franci.
{40485}{40620}John je ustvari Janez,|samo ga ponekad zovemo John.
{40637}{40754}Kakav je Janez?|- Što Janez?
{40759}{40904}Da li vas dobro pazi?|-Što je to"pazi"?
{40935}{41025}Da li se dobro|brine o vama?
{41057}{41152}Janez nas voliti kao otac.
{41158}{41291}On nas hraniti,|dati nam navci, novac.
{41295}{41416}Biznis je biznis,|takav kakav biti,
{41442}{41582}i èovjek nekada|morati pretrpjeti.
{41591}{41715}Èovjek nekada mora pretrpjeti.|Lijepo si to rekla.
{41721}{41836}I izgledaš zadovoljno.|Nije strašno?
{41841}{41941}Ja smatrati|da kako bilo nekada
{41944}{41991}i kako bilo kod drugih,
{41997}{42070}ovdje dobro.
{42109}{42189}Neki djevojke|odvezli od kuæa
{42194}{42299}i prodali u Budimpešta|za nekoliki tisuæa dolara.
{42304}{42409}Morati raditi|na autostrada u Italija.
{42414}{42522}Morati imati|20 do 30 klijenti na dan.
{42528}{42595}Inaèe ih tuæi,|ne dobiti novci...
{42807}{42895}Jesi li veæ dugo ovdje?|-Tri godine. -Tri godine?
{42899}{43023}Jesi li u meðuvremenu prodana?|-Da. Nas kupio Bato. -Bato?
{44386}{44491}Bato? -Bato i njegov|drug iz Crna Gora.
{44497}{44604}Oni nas dovezli ovamo.|Mi bile s njim jedna godina.
{44625}{44689}Strašno...
{44694}{44754}On tukao, on zatvarao...
{44760}{44822}Onda nas kupio Janez,
{44827}{44950}a Bato i njegov drug|oni završiti u arest.
{44954}{45049}Joj, u što sam se ja uvalio.
{45055}{45134}Ponekad po noæi
{45143}{45222}sanjati da se Bato vratio.
{45235}{45292}Uh, to je strašno.
{45297}{45403}Nekada èovjek|morati malo trpi.
{45635}{45709}Kako lijepo mirišeš.
{46091}{46156}Ništa, moram iæi.
{46161}{46230}Lijepo se provodi. Drago|mi je da smo se upoznali.
{46235}{46326}Što tebi je?|Što rekla loše?
{46330}{46403}Kalinka je glavna|uloga u mojoj prièi.
{46408}{46474}Zbog nje me uhvatila|pohlepnost za ljepotom.
{46479}{46525}KALINKA, PRVI PUT
{46529}{46627}Njeno lice bi najradije,|crtu po crtu, pojeo.
{46630}{46704}Cijelu noæ nisam spavao.
{46709}{46820}Drkao sam, napisao scenarij|i pripremao se za film.
{48097}{48214}Ako se nas dvoje po...|poše... poševimo.
{48219}{48323}Ako se nas|dvoje poševimo,
{48328}{48433}bit æe dobro vama,|a meni pogotovo.
{48438}{48553}Napaljena sam. Napaljena|sam i to pošteno priznajem.
{48557}{48651}Napaljena sam.|-Na-paljena. Napaljena.
{48657}{48754}Na-pa-lje-na.|-Tako je, maèkice. Vježbaš?
{48758}{48815}Da. -Fino, fino.|-Kafa hoæeš?
{48821}{48897}Može. Možeš li|mi je donijeti u ured?
{48924}{49014}Na-paljena. Napaljena.|Napaljena sam.
{49051}{49154}Po cijele sam|dane sama kod kuæe.
{49160}{49234}Po cijele sam dane|sama kod kuæe.
{49264}{49354}Napaljena sam,|svršavam...
{49358}{49415}Slušaj... -Napaljena sam.
{49419}{49497}Sretan sam što æe Slovenci|gledati porniæ na svom jeziku.
{49501}{49590}Bez sinkronizacije.|-A tko se toga sjetio, ha?
{49619}{49676}Treba li ti vilijamovke?
{49679}{49762}Jebala te tvoja vilijamovka,|prestani veæ jednom.
{49767}{49823}Ajd', u redu. -Živjeli.
{50182}{50243}Zdravo, Slaðana.|-O, bok, Èarli, kako si?
{50248}{50285}Dobro. Gladan.
{50290}{50353}Gladan si?Što æeš jesti?|Što hoæeš da ti napravim?
{50358}{50417}Danas ne bih burek, ali bih|pljeskavicu. Jesu li svježe?
{50422}{50472}Svježe su. Znaš da su|kod mene uvijek svježe.
{50476}{50541}Jednu æu. Dobro peèenu,|sa malo luka, senfa
{50546}{50624}i ajvara,|i bez majoneze danas.
{50630}{50715}Ili... ipak može|malo majoneze. -Dobro.
{50761}{50885}Jesi li ti primjetio kako je|naš Èarli izbjegao glumu?
{50890}{50961}Kako to misliš?|-Pa, tako, fino.
{50965}{51043}Pa glumi.|On je Kalinkin muž.
{51048}{51147}Nemoj zajebavat',|samo se na slici pojavljuje.
{51153}{51246}Vidiš ti, mater mu izdajnièku.
{51252}{51314}Stvarno se izvukao.
{51320}{51351}Ma ne znam...
{51357}{51412}Da nema nešto protiv Kalinke?
{51418}{51517}Ne znam, ali nešto s njim nije|u redu, kažem ti. Da nije...
{51528}{51656}Ma, pusti ga. Nek' on režira,|a mi æemo obaviti ostalo.
{51661}{51767}Vidjet æeš da æe mu biti žao.|Sigurno. -Upravo tako.
{51772}{51821}Ponedeljak, 19. rujna.
{51826}{51873}Jeste li zadovoljne, djevojke?
{51877}{51940}Znam da mi je Frenk|stalno pravio sranja.
{51944}{52010}PROBLEMI SA FRENKOM|Poslije posla je došao.
{52014}{52119}Nakon što je dugo zvonio,|na silu je razvalio vrata.
{52124}{52205}Frenk i ja smo ga|pretukli i vezali.
{52209}{52271}Vas dvojica niste normalni.|Skoro sam se usr'o u gaæe.
{52276}{52319}A ti si normalan?!
{52323}{52378}Što hoæeš? -Ništa.
{52382}{52451}Zašto si onda ovdje?|-Samo sam htio nešto ukrasti.
{52455}{52517}Samo si htio nešto ukrasti?!
{52520}{52564}Što da radim s tobom,|pizda ti materina?
{52573}{52696}Fernandel Sagadin.|-Nikada nisam èuo gluplje ime.
{52701}{52788}Da ti stari možda nije|slušao ABBA-u dok te pravio?
{52791}{52904}Znaš što, mislim da je najbolj|da ga vodimo u policiju.
{52909}{52966}Ne, samo ne na policiju.
{52970}{53039}Tamo imam dosje.|Odmah æe me zatvoriti.
{53044}{53123}Jesam li ti možda ja kriv|za to? -Nisi ti. -Nego tko?
{53126}{53212}Ona kuèka sa gatafona.|-Koja kuèka sa gatafona?
{53217}{53315}Prije svake akcije nazovem|gatanje preko telefona,
{53320}{53414}da mi gataju|hoæu li imati sreæe.
{53420}{53476}Za danas mi je rekla|da æu imati sreæe.
{53482}{53554}Pa kako možeš biti tako glup|da im vjeruješ? -Pa nisam...
{53559}{53635}Èekaj malo. Ovdje nas|dvojica postavljamo pitanja.
{53641}{53711}Sjedi tu mirno.|Ni prdnuti ne možeš.
{53717}{53810}Frenk, hajdemo malo ovamo|jer se moramo konsultirati.
{53815}{53860}Jesi li èuo? Brzo se|vraæamo. Budi miran.
{53913}{53988}Što gledaš?
{54209}{54304}Ne seri, stari. -Što je?
{54360}{54443}Baš je dobar.|Prodaj mi ga.
{54456}{54561}Tebi, k'o prijatelju,|za 3000. -3000?
{54592}{54673}Nema frke, stari.
{54689}{54774}Evo, Fernandel èasti.
{54835}{54886}PORNO ZVIJEZDA
{54891}{54978}Bio je idealan|lik za moj film.
{55013}{55091}Ne mislite valjda ozbiljno?|-Najozbiljnije.
{55094}{55154}Da glumim u porniæu?|Pa vas dvojica niste normalni.
{55159}{55225}Nemoj ti meni tko je normalan,|a tko nije. Jesi li za ili ne?
{55230}{55313}Ne mogu. Mama bi me|ubila da me vidi u porniæu.
{55317}{55387}Onda idi zovi policiju.
{55406}{55463}Imam li još kakvog izbora?
{55469}{55570}Ne. Obje su ti varijante P:|porniæ ili policija.
{55592}{55647}Hoæe li to biti plaæeno?
{55653}{55765}Još da ti platim?|Odoh na policiju .-Èekaj!
{56387}{56479}Gledaj, Fernandel, nazvala te,|jer joj se, pokvarila pipa.
{56483}{56590}Na sebi æe imati|nešto prozirno.
{56596}{56685}Hoæu da na poèetku poèneš|onako sasvim hladnokrvno:
{56690}{56806}da poèneš popravljati, ne|sluteæi ništa, a ti se Marina
{56811}{56897}odjednom poèinješ žaliti.|Èitaj tekst,molim te.
{56902}{56950}Odavde? Moj muž...
{56954}{57023}Moj muž... po cijele ga|dane nema kod kuæe.
{57034}{57137}Moga muža po cijele|dane nema kod kuæa.
{57142}{57237}Ja to još|nikada nisam napravila.
{57241}{57324}Ako se nas dvoje poševimo,
{57329}{57435}bit æe vam dobro,|a meni pogotovo.
{57439}{57509}Nitko neæe saznati.
{57514}{57608}Sve bude kao|da se ništa nije desilo.
{57612}{57693}Gledaj, Fernandel... Ti je,|dok se ona žali, samo gledaš.
{57698}{57776}Gledaš, i ništa ne kužiš,|ne znaš o èemu se radi.
{57781}{57906}Onda je fino ovdje uhvati.|Marina, stani na sve èetiri.
{57912}{58050}Ovako, a ona æe se poèeti|derati: "Pojebi me!"
{58055}{58141}Ja znati to.|-Dobro, ona æe.
{58173}{58281}Pojebi me, da moj|život dobije smisao.
{58286}{58372}Još! Jaèe guraj!
{58378}{58472}Oh, tvoja pipa zlatna.
{58477}{58543}Ja umrijeti!
{58549}{58609}U redu je.|Ne moraš pretjerivati,
{58615}{58696}samo, nauèi tekst.|I što sad?
{58702}{58804}U stan ulazi Kalinka.|Kalinka, doði.
{58810}{58887}...sa uokvirenom|slikom svog muža.
{58892}{58984}Gledaj, kad vidiš što se|dešava, moraš se brzo skinuti.
{58991}{59104}Brzo se skineš. Ne moraš|sada. I što onda kažeš?
{59109}{59240}Susjedo, ne budi škrta. Ni moj|muž nikada nije kod kuæe.
{59245}{59356}Ni ja ga još nisam prevarila.|Ali, i ja napaljena.
{59359}{59400}Odlièno! Marina,|što ti onda napraviš?
{59431}{59521}Davaj, Gabrijela, gdje nema|škrtarenja dosta za sviju.
{59536}{59611}Gabrijela, tamo gdje nema|škrtarenja ima dosta za sve.
{59631}{59741}l, sada ti Marina doživiš|bombastièan orgazam.
{59746}{59811}I što napraviš?
{59823}{59886}Toèno tako, zaškiljiš,
{59892}{59961}i od silnog užitka...
{59966}{60029}od silnog užitka|jednostavno poèneš jecati
{60034}{60112}i ponavljati: hvala, hvala...|-Hvala, hvala, hvala...
{60118}{60186}I onda se skljokaš,|onesvjestiš se. To.
{60191}{60265}Mogu li ti ga za poèetak,|da se upoznamo, pocucljati?
{60269}{60339}Pocuclati - odlièno!|"The best"...
{60345}{60421}A sada ti, Fernandel,|namigneš Kalinki,
{60427}{60496}tako je, i klimneš glavom.
{60517}{60599}Na sve èetiri, molim. Tako.|U redu. I što onda ka...?
{60657}{60746}Pizda mu materina, Frenk,|mi radimo! Ne zajebavaj se!
{60752}{60816}Dobro, neæu.|U pravu si. Slažem se.
{60822}{60869}Malo više ozbiljnosti.|-Da, radno. "Sorry".
{60872}{60925}Kalinka, što ti onda kažeš?
{60929}{60970}Hajde, stavi ga unutra|i bit æemo kvit.
{60974}{61073}To! Fernandel, ti sad polako|odozada kreneš na nju...
{61109}{61200}Idemo "von hinten". To, to.|Bez ruku. Stavi ih na bok.
{61206}{61286}Znaš to se struèno|kaže "freihandig".
{61290}{61337}Tako kako je Frenk rekao.
{61342}{61460}Sada, klekneš iza nje i kažeš:|Nisam èuo "molim te".
{61511}{61585}Dobro, ali s malo više|energije i temperamenta.
{61589}{61703}Kalinka, kad on to kaže, ti|odgovoriš "molim te". -Super.
{61736}{61905}Sada poèinješ strasno ljubiti|sliku svog muža tj. mene
{61919}{62023}i uskoro moraš poèeti|svršavati. Razumiješ?
{62029}{62146}A ti, Marina, polako poèneš|dolaziti sebi, i to zbog èega?
{62151}{62239}Zato što èuješ kako se|Kalinka dere. Kako uživa.
{62243}{62309}To je to.|Logika. Dramaturgija.
{62315}{62393}A sada, gledaj,|Fernandel...
{62399}{62504}Što ti napraviš kad vidiš da je|Marina još uvijek napaljena?
{62509}{62558}Pojma nemam.|-Pojma nemaš?!
{62564}{62658}Uzmeš tobu, iz nje izvadiš|mobitel i nazoveš prijatelja
{62664}{62746}koji odmah dolazi upomoæ.
{62751}{62838}A taj sam prijatelj konaèno|ja. Ulijeæem bez pozdrava,
{62843}{62956}navalim na Marinu i najprije|je stojeèki, pa sjedeèki,
{62959}{63088}pa kleèeæi, pa onda ležeèki.|Jesam dobro proèitao scenarij?
{63093}{63210}Toèno. Nakon što Frenk vidi|što se dogaða, kreæe u akciju.
{63214}{63321}A onda na red dolazi i Marinin|muž, koji po cijele dane radi,
{63326}{63460}a ustvari je|s Palomom i Nastasjom.
{64238}{64336}Hej, ne razumijem zašto te je|baš sada uhvatila depresija?
{64340}{64426}Nisam sasvim|siguran u sve ovo.
{64610}{64722}Hej, pa sve je u redu.|Bolje ne može biti.
{64728}{64809}Što ja znam. Ne znam ima|li ovo još ikakvog smisla.
{64814}{64911}Naravno da ima.|To su životne prièe.
{65078}{65163}Mislite li da je prièa|uopæe dovoljno životna?
{65168}{65239}Ma, ne valjaj gluposti.|Totalno je životna.
{65244}{65309}Što ja znam.|Tko æe uopæe to gledati?
{65312}{65403}Volio bih da film ima neku|poentu. -Kakvu poantu?
{65410}{65532}Na primjer, da je važno biti|zdrav i da je život dragocjen,
{65536}{65594}kao što kaže|moj frend Damjan.
{65598}{65673}Ako si samo to mislio,|to je definitivno jasno.
{65676}{65767}Misliš da je ta poenta|prepoznatljiva? -Naravno.
{65826}{65890}Ma, ne znam.
{65911}{65962}Dvoumim se.
{65967}{66071}Prijatelju, nemoj biti|sitnièav. Znaš kako kažu...
{66114}{66178}Nemoj biti takav.
{66261}{66402}Hej, stari, pomisli koliko|love æe pasti. K'o blata.
{66433}{66562}Meni nije toliko do love. Hoæu|da napravimo što bolji film,
{66566}{66642}da film postane kultni, i to|za sva vremena. To ja želim.
{66647}{66793}Slušaj, imaš malo stvaralaèke|treme. Strpi se malo.
{66835}{66940}Misliš da æemo uspjeti?|-Sto posto.
{67034}{67139}Što ja znam.|-I ja tako mislim.
{67230}{67340}Kad bi barem Bog bio|na našoj strani, lijepo molim.
{67459}{67546}Bok, stara.|-Bok, stari. Ti me zvao?
{67554}{67593}Da.
{67598}{67676}Imaš li za danas|naruèenu kakvu stranku?
{67681}{67757}Ne. -Ne? Nijednu?
{67762}{67881}Što je to bilo kad ste ti|i Èarli išli u sobu? -Ništa.
{67905}{67988}Ništa? Kako ništa?
{68008}{68050}Baš ništa?
{68054}{68167}Mi razgovarali,|onda me poljubio i išao.
{68216}{68312}Pa, kako to?|Da nije možda peder?
{68394}{68452}Slušaj, Kalinka...
{68486}{68566}Frenk sada ide u grad
{68571}{68648}Ti se sredi,|da izgledaš seksi.
{68654}{68750}Reci Èarliju da si|došla vježbati za film,
{68755}{68852}a onda ga dobro obradi.|Znaš, brinem se za kolegu.
{68857}{68939}Nadam se|da æe mu to pomoæi.
{69114}{69225}Kalinka, jesi li možda|za jednu ševicu,
{69230}{69290}onako na brzaka?
{69305}{69417}Hajde. Više od orgazma|nam se ne može dogoditi.
{69422}{69493}Što ti misliš za mene?
{69497}{69589}Ja radim za novci,|ne za zabava.
{69595}{69681}Nisam takva|kakvom me ti smatrati.
{69685}{69760}Opa, materijalistica!
{69765}{69860}Hajde, samo|jednom, na brzaka.
{69899}{70017}Ili bar jedno pušenje,|jedno malo pušenje.
{70049}{70115}Radije bih se|prezivala Jebiæ.
{70119}{70218}Prezivaj se ti kako god hoæeš!|To bi ti svakako pristajalo.
{70222}{70308}Prodaješ mi ovdje Èarlijeve|finte kao da su tvoje.
{70313}{70376}Praviš se fina preda mnom,|k'o da te ne poznajem.
{70381}{70485}Jebem ti mater i sve|po spisku, kurvo pokvarena!
{70568}{70662}Izlazi van jer te ne mogu|više gledati. Hajde, idemo!
{71318}{71390}Tko je?|-Ja, Kalinka.
{71494}{71533}Bok.
{71539}{71597}Otkud ti ovdje?
{71623}{71700}Što s tobom napravili?
{71704}{71799}"Bundes liga" frizura|za film. Ne sviða ti se?
{71807}{71891}Ne znam. Smiješno.
{71935}{72002}Hoæeš li uæi?
{72128}{72204}A što ja tebi|ovdje smetam?
{72209}{72280}Kuda me vuèeš?
{72285}{72384}Pa naravno, u podrum,|gdje drugo, u pizdu materinu.
{73011}{73100}Što ti imati protiv mene?
{73110}{73214}Kalinka, ja nemam|apsolutno ništa protiv tebe.
{73219}{73293}Samo...|-Samo što?
{73298}{73380}Nema smisla.
{73385}{73490}Zašto ti reæi nema smisla?|Što ne biti u redu?
{73580}{73668}Kalinka, ja ne|mogu, razumiješ.
{73675}{73739}Nisam peder,|ako si to mislila,
{73745}{73829}ali ne mogu ni s tobom|ni sa ijednom drugom.
{73834}{73907}Uopæe još nisam|ni sa jednom.
{73911}{73993}Jednostavno|mi se ne diže.
{74220}{74288}Jadnièak.
{74327}{74421}A možda|da nisi bio s pravom?
{74434}{74517}Ma, bio sam ja|s najmanje pet njih,
{74522}{74598}ali uvijek isto - totalna|katastrofa, poniženje.
{74603}{74712}Katastrofa.|Ne možeš ni zamisliti.
{74764}{74888}A ti nekada bio|sa djevojka koju voliš? -Ne.
{74893}{74989}Kakve to veze ima|sa mojim problemima?
{74995}{75117}Nekada to pomagati.-Pa neæeš|me ti sada uèiti o ljubavi.
{75139}{75231}TKO PRIZNA|POLA MU SE PRAŠTA
{75306}{75426}A ti nikada ne imao orgazam?
{75431}{75577}Nisam. Osim kad sam sam.|Digne mi se samo uz porniæe,
{75684}{75810}a uživo ne. Kad sam sa curom,|nešto me stisne tu unutra,
{75814}{75874}i ne ide.
{75880}{76017}Još je gore. Ne mogu ni pišati|u javnim WC-ima. Ne ide.
{76027}{76186}Svi mi smetaju. Ponekad|sam skoro popizdio.
{76228}{76293}Grozno.
{76319}{76377}Mogu li probati?
{76407}{76481}Nema smisla.
{76522}{76628}Ili, ipak probaj.
{78240}{78371}Pa nije sve u seksu.|-Tebi je to lako reæi.
{79076}{79202}A gledanje porniæa|te uzbuðuje? -Da.
{80066}{80154}Kalinka, znaš li|tekst napamet?
{80158}{80217}Sigurno?
{80361}{80450}KALINKA, DRUGI PUT
{81128}{81208}Hajde, Èarli...
{82189}{82263}Živjela Rusija!
{82387}{82477}Od berbe se nisam|toliko oznojio.
{82482}{82589}Da ponovo nešto|ne zajebem, Kalinka.
{82595}{82723}Jesam li ti rekao|da te volim? -Ne. -Volim te.
{82770}{82833}Hvala.
{82857}{83005}Na svijetu nema poezije koja|bi opisala moje osjeæaje.
{83010}{83120}Kakav Dostojevski,|kakav Tolstoj, nije to ništa.
{83187}{83309}Obeæaješ li da æeš|zauvijek biti samo moja?
{83376}{83507}Ja ne biti u tom položaju|da mogu obeæati.
{83536}{83591}Svejedno obeæaj.
{83596}{83642}Da.
{83645}{83738}Obeæaješ?|-Obeæajem.
{83787}{83867}To! To!
{83901}{83985}Kalinka, jesi li gladna?
{83990}{84065}Idemo na burek!
{84261}{84347}Dobar je, zar ne?|-Dobar.
{84355}{84486}Prva noæ Ljubljana|na ulici. -Da?
{84532}{84624}Ali noæ radim.
{84634}{84762}Uopæe nikoga ne|poznajem, samo stranke.
{84767}{84897}Ja živim ovdje u Ljubljani|nekoliko godina,
{84902}{84995}a imam osjeæaj|da sam ovdje èitav život.
{85001}{85071}Ne poznajem mnogo ljudi.
{85077}{85191}I oni koje pozajem|su svi idioti.
{85221}{85338}Ne sekiraj se, Kalinka.|Ne sekiraj se.
{85429}{85494}Kalinka...
{85511}{85580}Znaš èega sam|se sad sjetio?
{85583}{85651}Znaš što je jednom rekla|Linda Lovelace? -Ne.
{85656}{85720}Znaš li tko je|Linda Lovelace? Ne znaš?!
{85725}{85801}Nisi gledala porniæ|"Duboko grlo"?!
{85806}{85877}To moraš vidjeti.
{85881}{85968}Ona je bila jedna od najveæih|porno zvijezda na svijetu.
{85972}{86040}U jednom su je|intervjuu pitali
{86045}{86126}kakva je razlika,|tj. kakvu ona razliku pravi
{86131}{86200}izmeðu tipova koji je|guze na filmu i svog muža.
{86205}{86255}I znaš što je rekla? -Što?
{86259}{86410}Da spermu svog muža proguta,|a od ostalih ispljune.
{86454}{86538}Èarli, ti nisi normalan.
{86546}{86677}Jesi li za dogovor?|-Jesam. Ja saglasna.
{87248}{87295}Što je rekla?
{87299}{87368}Ruska kurva.
{87382}{87446}Što si rekao?
{87450}{87575}Švabo, gdje si|pokupio tu rusku kuju?
{87580}{87700}Ponovi, ako smiješ.|-Rusku kuju! Švabo!
{87704}{87807}Sad ponovi ako smiješ,|pièka ti materina!
{87830}{87924}Što je rekao?|-Ja radije ne bih.
{87954}{88039}Nisam èuo rijeè "oprosti"!
{88061}{88144}Oprosti. -Oprosti.|-Na ruskom, da razumije!
{88150}{88278}Ne znam...|-Kako se kaže? -Prastite.
{88331}{88453}A sad se gubite|dok sam još dobre volje!
{89121}{89203}Volim te.
{91114}{91190}Fernandel...
{91195}{91268}O, jebem mu Boga...
{91318}{91412}Fernandel, oprosti,|skroz sam zaboravio na tebe.
{91457}{91568}Pa, naravno,|imao si pune roke posla.
{91574}{91642}Srijeda, 21. rujna.
{91648}{91695}RASPRAVA O FILMU
{91701}{91765}Onda je Janez javio|Kalinki da ima stranku.
{91769}{91890}Frenk je došao po nju, a ja|sam poæaskao sa Fernandelom.
{91895}{91962}Imaš li tremu od snimanja?
{91967}{92054}Malo. Nadam se|da mi neæe zakazati.
{92059}{92128}I što æeš nakon filma?
{92134}{92216}Po starom. Ne znam. A ti?
{92228}{92349}Ah, mislim da je|Kalinka ljubav mog života.
{92369}{92457}Prava je ljubav iznimka,
{92463}{92567}a sve ostalo samo|domišljato ili prividno.
{92572}{92707}Znaš što mi je rekla?|Da sam strašno pametan,
{92717}{92825}širokih vidika,|da imam nevjerojatnu maštu,
{92830}{92971}da se vidi da sam talentiran,|kakvu karizmu imam...
{92976}{93155}Rekla mi je da sam strastven,|nježan, i da... -I što još?
{93306}{93458}Da imam najveæi u Sloveniji.|-Možda drugi najveæi.
{93470}{93537}Pa dobro, to je još|uvijek srebrena medalja.
{93542}{93587}PROBLEMI SA FRENKOM
{93591}{93652}Frenk je tokom vožnje|poèeo dirati Kalinku.
{93657}{93729}Ona se naravno|branila, a onda...
{93734}{93821}Kako možeš biti toliko glup|da ovako slupaš auto?!
{93827}{93884}Mogao si poginuti.
{93889}{93965}Prošli sam ti tjedan rekao|da kupiš nove gume.
{93971}{94066}Nemoj na tome štedjeti!|Pazi malo na sebe.
{94071}{94119}Hvala.
{94124}{94200}Kad snimimo porniæ, dobit æeš|novac i kupi si novi auto.
{94204}{94283}Pazi malo na sebe,|da ne pogineš.
{94295}{94355}Slušajte sad svi.
{94361}{94438}Sutra da ste mi istuširani,|sreðeni, napucani...
{94441}{94505}Higijena mora|biti sto postotna.
{94509}{94586}I nikakvih odnosa,|da jaja budu puna.
{94594}{94690}Ž'temske kiseline mora biti|puno. To posebno važi za tebe.
{94696}{94802}U redu, Frenk? Jasno?|-I Èarlija.
{94805}{94932}Priznajem vam, bio sam|potpuno drugi èovjek.
{95713}{95760}Dobar dan.
{95767}{95884}Bio je, bio je dobar dan.
{96129}{96173}Èarli!
{96250}{96307}Došao sam te posjetiti.
{96311}{96358}Jesi li umorna?
{96363}{96442}Ne, ja sam dobro.|Pomozi mi...
{96570}{96619}Hvala.
{97012}{97081}Slušao sam te pred vratima.
{97111}{97204}Ti perverznjaèiæu.
{97211}{97326}Blefirala si, zar ne?|-Ne blefirala.
{97387}{97519}Zar možeš svršiti s tipom|kojeg ne poznaješ? -Da.
{97540}{97629}Èesto? -Uvijek.
{97662}{97730}Stvarno?
{97735}{97848}Èovjek predan|poslu uvijek uspjeti.
{97884}{97968}Bravo. Ti si nevjerojatna.
{97998}{98113}Znaš li koliko ima djevojaka|koje nikada ne svrše?
{98131}{98271}Nekada èovjek|morati malo pretrpjeti.
{99738}{99867}Kalinka, jesam li ti danas|veæ rekao da te volim? -Ne.
{99870}{99972}Volim te. -Hvala.
{99976}{100070}Stalno mislim|na tebe. -Ali...
{100082}{100141}Da, i na porniæ.
{100145}{100260}Imaš li tremu od snimanja? -Ne.|Za dijalog se bojati, strah.
{100270}{100391}Znaš sve? -Stavi ga,|pa æemo biti kvit.
{100396}{100472}Ti si jedina|s kojom to mogu.
{100479}{100573}Šteta što sada nemam|ovdje kameru i televizor.
{100579}{100717}Ali, to nije jedini razlog što|želim da si zauvijek sa mnom.
{100721}{100813}Voljet æu te do groba.
{100818}{100891}Èetvrtak, 22. rujna.
{100896}{100970}Stvari su se nakon|toga brzo odvijale.
{100973}{101016}Poèeli smo snimati.
{101020}{101144}Prvi dan, prva scena -|vodoinstalater.
{101264}{101328}Samo bez nervoze.
{101454}{101575}Frenk! -Što je? Pa pogledaj|te èarape! Sa gumom!
{101591}{101648}Pa? -To se uopæe ne vidi.
{101652}{101695}Nemoj ti meni što|se vidi, a što se ne vidi!
{101700}{101748}Tko režira, ti ili ja?|-Èekaj malo...
{101753}{101828}Malo si preozbiljno|sve ovo shvatio.
{101831}{101958}Marina, nemoj mi reæi da æe ti|se vidjeti tragovi od gaæica.
{101994}{102120}Ja stegla brusthalter,|da bude lijepo izgljedalo.
{102129}{102259}Sam moram na sve misliti.
{102264}{102436}Odmah skinite gaæice i|grudnjake, da se koža izravna.
{102463}{102520}Odmah!
{102662}{102754}Maltretira nas|kao da je pravi režiser.
{102760}{102821}Ne seri više...|Snimimo to veæ jednom.
{102826}{102884}Ne tjeraj me na nešto ispod|èega se ne mogu potpisati.
{102889}{102950}Na nešto što je ispod|mog nivoa. Molim te.
{102955}{103056}Ti kao da si neki|perfekcionista. -I jesam.
{103059}{103177}Zovnite me kad budete snimali.|Pa ovo je nevjerojatno...
{103184}{103292}Daj mi dim. -Duboko udahni|da se malo smiriš.
{103340}{103414}Poèeli smo loše,|a nastavilo se još gore.
{103418}{103482}CRNOGORSKA BANDA
{104725}{104764}RASPLET
{104769}{104816}Frenk je veæ|prije negdje nestao.
{104821}{104860}Fernandel je|odmah pobjegao,
{104865}{104926}a ja sam ostao|sa Kalinkom i curama.
{104932}{105011}Kako sam kasnije saznao,|Janez se navodno dobro držao.
{105130}{105215}Oprosti, ali nisu.
{105843}{105930}Oprosti, ali nisam ja|kriv za raspad Jugoslavije.
{106712}{106785}Tako je. Što da kažem?
{106931}{107011}Kako je bilo u zatvoru?
{107128}{107208}Jesi li dobio pakete?
{107695}{107747}Imam ideju.
{107752}{107813}Da se, u tri pizde materine,|goniš tamo odakle si i došao -
{107818}{107875}u Crnu Goru.
{108462}{108539}Èekaj malo,|sad veæ vrijeðaš!
{108767}{108850}Radije bih se prezivao Jebiæ!
{109044}{109146}Sve dok dišem,|sretan sam èovjek.
{111558}{111617}Jok, brate, gorska|služba spašavanja!
{111623}{111687}Vaginalni grè.
{111692}{111742}To sam vidio samo|jednom na filmu.
{111757}{111811}PROBLEMI SA FRENKOM|I sada.
{112494}{112544}FINALE|Rekao sam mu
{112549}{112638}da Kalinka nikuda ne ide.|Da æe ostati sa mnom.
{113125}{113196}Ne razumijem srpsko-hrvatski.
{113896}{113968}KALINKA, POSLJEDNJI PUT
{113991}{114084}Stotinu sam se puta upitao|da li mi se to desilo
{114089}{114201}samo zbog onog pisma sreæe,|koje sam bacio u kantu.