{1}{1}25.000
{869}{929}NOÆNI LET
{1425}{1475}Plodovi mora South Florida Sun
{1636}{1683}ODOBRENO | LUXE ATLANTIC
{1779}{1819}Idemo!
{2018}{2084}MANSARDA | TLOCRT KATA
{3163}{3190}LUXE ATLANTIC
{3192}{3276}- Bob i Marianne Taylor. | - Slušajte...
{3278}{3338}- Miami ima i drugih hotela. | - Žalim...
{3340}{3432}Gdje je problem? | Rezervirali smo pred 6 mjeseci.
{3434}{3493}- Ne vidim... | - Gdje je Lisa?
{3495}{3557}- Ona nam uvijek pomogne. | - Nije u gradu.
{3559}{3612}- Preminula joj baka. | - Cynthia, je li?
{3614}{3660}- Da. | - Što je za vas gore:
{3662}{3745}Da vi nazovete nju ili ja upravu?
{3747}{3797}Dobro.
{3853}{3900}K vragu! Dallaski vozaèi!
{3902}{3964}Tko ih je uèio voziti | Stevie Wonder?!
{3966}{4036}- Ne brinite se, stiæi æete na avion. | - 10 minuta.
{4052}{4124}- Lisa Reisert... | - Liso?
{4126}{4211}Oprosti, ali imam paniku.
{4213}{4287}- Polako, tu sam. Što je bilo? | - Bob i Marianne Taylor.
{4289}{4326}Redoviti gosti.
{4328}{4398}Izbrisala sam rezervacije,
{4400}{4449}nepoznat mi je novi sustav.
{4451}{4539}Rezervacija je potvrðena. | Imam priznanicu.
{4541}{4597}Sama sam je skinula s interneta.
{4599}{4667}- Znam, smirite se. | - Ne govori to!
{4669}{4716}- Smirite se? | - Rekla mi je da se smirim!
{4718}{4820}Ne govorite nam to. | Dosad smo bili jako mirni.
{4822}{4892}- Oprostite... | - Reci. Samo minutu,
{4894}{4979}- bit æete zadovoljni, obeæavam. | - Još minutu, bit æete zadovoljni.
{4981}{5015}- Obeæavam. | - I bolje!
{5017}{5091}Unesi mój pin, 788... | Prièekaj.
{5112}{5142}- Tata. | - Liso?
{5144}{5195}- Možeš prièekati? | - Jasno.
{5197}{5276}Dobro. Dakle 7884 L. Reisert.
{5278}{5361}- Oprosti što zovem. | - Neka.
{5363}{5410}- Jesi li se upisala? | - Da, što sad?
{5412}{5488}Klikni na direktorij Kriza | i vidjet æeš prazne sobe.
{5490}{5564}Daj im 4. kat sobu na uglu, | noæas i sutra besplatno.
{5566}{5672}Trenutak... Dobro, sve sreðeno.
{5674}{5728}Prve dvije noæi mi èastimo.
{5730}{5794}Ako vam zatreba još što, | javite mi.
{5796}{5837}Neæemo.
{5839}{5880}Nisam ja kriva.
{5891}{5961}Kako su me uzrujali! | Kakvi seronje...
{5963}{6038}Ne postoji gost-seronja, | nego gost s posebnim potrebama.
{6040}{6111}- Stigli smo. | - Zadržite! Još nešto?
{6113}{6190}Simpsoni kažu da nisu dobili | "kalifornijski" madrac.
{6192}{6225}Dalje?
{6257}{6303}- Bože... | - Reci.
{6305}{6375}Poruka Osiguranja. | Charles Keefe i društvo
{6377}{6431}stižu u 5:30 a ne 17:30.
{6433}{6494}Ništa èudno, | sigurnosni razlozi.
{6496}{6590}Postavi naše deèke na ulaz, | a njegovi æe preuzeti.
{6592}{6650}G. Keefe je Platinasti klub?
{6652}{6693}Politièar. Domovinska sigurnost.
{6695}{6768}Stavi u sobu | kutiju kubanskih Montecrista
{6770}{6837}i bocu Cristala. | Soba 3825.
{6839}{6900}- Sreðeno. Ugodan let. | - Hvala.
{6949}{7018}Pozor putnicima na letu 1387.
{7020}{7075}- Lisa Reisert. | - Još sam tu...
{7077}{7115}Tata, oprosti.
{7134}{7189}- Sve u redu. | - Kako ide?
{7191}{7271}Spremam se za novu | besanu noæ s maratonom komedija.
{7273}{7339}Da ne zaboravim...
{7341}{7394}Proèitala si knjigu koju sam ti dao?
{7396}{7433}Skoro.
{7444}{7528}On je iz Teksasa. Nisam znao | da tamo imaju peraèa mozga.
{7530}{7619}Imaju, no odsele se u Kaliforniju | i pokrenu TV-emisije.
{7621}{7664}- Kako obnova? | - Dobro.
{7666}{7712}Blagi napredak | u zadnjih par dana.
{7714}{7797}Izgubio sam novèanik, što i nije èudo. | Dobro izgleda.
{7799}{7843}Jedva èekam da vidim.
{7845}{7959}I trebaš. | Hodnik na katu nije za prepoznati.
{7961}{8022}- Jasno, tvoju sobu nisam ni taknuo. | - Ne, tata.
{8024}{8098}Ma samo naprijed. | Pretvori je u dvoranu ili teren za golf.
{8100}{8148}Znaš da ne mogu.
{8150}{8238}Nikad ne znaš | kad æeš htjeti opet prenoæiti ovdje.
{8240}{8337}Pobjeæi od svakodnevice.
{8339}{8396}U svakodnevici opstojim, | ti to znaš, tata.
{8437}{8480}Dobro.
{8504}{8551}Da...
{8553}{8648}- Kako ti se drži mama? | - Dobro, s obzirom...
{8666}{8712}A ti? Dobro?
{8714}{8767}- Dobro. | - Sigurno?
{8795}{8898}Sve je u redu. | Morat æeš mi poèeti vjerovati na rijeè.
{8900}{8945}Moram sad ovjeriti kartu.
{8947}{9005}Sigurno neæeš prijevoz?
{9007}{9096}- A tvoj novèanik? | - Ma to je 5 minuta.
{9098}{9156}Idem noænim letom, | i to zadnjim.
{9158}{9216}Bit æe jako kasno. | Zvat æu te sutra. Volim te.
{9218}{9294}- I ja tebe volim, srce. | - Dobro, zdravo.
{9390}{9537}Nova obavijest o kašnjenju. Zbog | vremena, otkazuje se za Pittsburgh.
{9581}{9658}Svi koji su trebali | na otkazani let za Atlantu,
{9660}{9727}doðite da vas preusmjerimo.
{9729}{9771}Let 1019 za Miami kasni.
{9805}{9861}- Oprostite! | - Nema frke.
{9863}{9904}Nosim svoje borbene èizme.
{9928}{9999}- Molim? | - Putovanje je danas ratovanje.
{10001}{10036}Da.
{10062}{10114}O, njega obožavam.
{10116}{10181}Kakva je? Puno ste doznali?
{10183}{10221}Ne znam baš.
{10239}{10276}Zgodan je.
{10278}{10351}Danju radim, | pa mi uvijek promakne emisija.
{10353}{10413}Let 247 za Cleveland kasni.
{10415}{10492}- Evo... tako æete nadoknaditi. | - Ne mogu...
{10494}{10585}Gotova sam. Daje mi ih tata, | mogu otvoriti knjižnicu.
{10587}{10645}- Vrlo ste ljubazni. | - Uživajte.
{10647}{10753}Svi za let za Atlantu, | želite li veèeras u Dallas,
{10755}{10814}doðite u prvi red.
{10816}{10860}Oprostite...
{10862}{10945}Oni mogu, a mi smo tu preko sata! | Kako je to moguæe?
{10947}{11000}Ako ih ne preusmjerimo, | izgubit æe vezu.
{11002}{11082}Meni ste otkazali let | i dvaput me preusmjerili!
{11084}{11155}- Shvaæam... | - Zovite mi šefa! Besmislica!
{11157}{11223}Ne tjerajte je na to, | daje sve od sebe.
{11225}{11267}Ne govorim s vama.
{11269}{11312}- To shvaæam. | - Èujte, ja samo...
{11314}{11360}Molim vas, gospodine.
{11362}{11438}Jedino ona stoji izmeðu odlaska | i potpune anarhije.
{11440}{11522}- Ali ona ne... | - Radi veæ punih 18 sati
{11524}{11591}i misli da je svi mrzimo | koliko i vi.
{11593}{11664}Neka radi svoj posao.
{11666}{11759}Sigurno nezahvalniji od vašega.
{11839}{11884}Pušiona od kompanije!
{11967}{12025}Iduæi u redu, molim!
{12027}{12068}To sam ja!
{12094}{12132}Evo...
{12144}{12220}Puno hvala. | I vama.
{12222}{12253}Nema na èemu.
{12255}{12319}Da, hvala.
{12321}{12367}Ma ništa. | Obièna potpora.
{12369}{12433}- Vi ste pokrenuli stvar. | - Da.
{12435}{12488}- Valjda refleksno. | - Kako to?
{12490}{12576}Radim u hotelu. | Stalno imam posla s takvim ljudima.
{12611}{12656}"Marriott"? "Hilton"?
{12658}{12713}- "Luxe Atlantic". U... | - Miamiju, da.
{12715}{12764}Dobro ga znam.
{12766}{12854}- Dakle letite... | - Avionom za Miami, koji strašno kasni.
{12856}{12917}- Vi? | - Nažalost takoðer.
{12919}{13000}No znate što? | Zato je Bog stvorio "Tex-Mex".
{13002}{13103}Najbolji nachosi na aerodromu | baš preko puta izlaza.
{13105}{13161}Hvala na obavijesti.
{13200}{13255}Èuvam vam mjesto.
{13336}{13419}Znam, nije baš... | ali kad veæ zajedno letimo...
{13421}{13486}Nisam mislio uzurpirati | vašu privatnost.
{13488}{13544}- Ne. | - Gospoðice, ja mogu doæi tamo...
{13546}{13646}- Moram obaviti par poziva... | - Jasno, shvaæam. Samo dajte.
{13648}{13721}- Ugodan let. | - Takoðer.
{13723}{13784}Naknadno æemo vam javiti
{13786}{13850}o odlasku leta 1019 za Miami.
{13852}{13908}- Bog. | - Ti si zacijelo Rebecca.
{13910}{13947}- Da. | - Ja sam Mary.
{13949}{14023}Èujem da | danas prvi put letiš sama.
{14025}{14087}Sigurno si jako hrabra.
{14089}{14130}- Bit æeš dobro? | - Hoæu, mama.
{14132}{14189}- Sigurno? | - Da, sigurno!
{14191}{14265}- Samo pitam... | - Imam 11, a ne 9 godina!
{14267}{14318}Doðite za mnom.
{14337}{14410}Izvolite nachose. | Pripazite, tanjur je vruæ.
{14412}{14449}Hvala.
{14477}{14539}O, Bože! Tako mi je žao.
{14541}{14602}- Ne brinite, ledena... | - Dobro.
{14604}{14666}- Dat æu vam ubruse. | - Ne, sve u redu.
{14668}{14703}- Sigurno? | - Da.
{14705}{14750}Dobro. Larry!
{14752}{14820}Vrati mi se | po novu ledenu kavu.
{14822}{14886}- Veæ popila? | - Netko je nosi...
{14888}{14941}Dame i gospodo, | molim pozornost.
{14943}{15042}Let 17 u odlasku | iz Dallasa s izlaza 2
{15044}{15104}kasni 20 minuta.
{15647}{15722}Nosaè prtljage | neka se javi na izlaz 4.
{15724}{15807}Nosaè prtljage | neka se javi na izlaz 4.
{15842}{15871}- Bog. | - Bog.
{15905}{15973}- Zauzeto? | - Ne, samo dajte.
{15975}{16010}Hvala.
{16012}{16079}Znaèi, obavili ste pozive?
{16107}{16147}Da, gotovo!
{16149}{16201}Sjajno. Što æete?
{16253}{16318}- Ništa. Dobro sam. | - Da pogodim...
{16351}{16377}Dajte!
{16420}{16455}Osjeæam votku...
{16489}{16562}Svakako zaslaðenu.
{16564}{16658}Cosmopolitan... | Ne, odveæ obièno.
{16679}{16716}Screwdriver...
{16718}{16792}Ne, ne, odveæ dosadno.
{16794}{16866}Znaèi, preostaje | jednostavnost grejpa
{16868}{16948}ili složenost ananasa.
{16996}{17040}Morski povjetarac s grejpom.
{17112}{17171}- Može zaljevski povjetarac? | - Vrijedi.
{17173}{17203}Hvala.
{17205}{17269}Ipak, vrlo ste daroviti. | Jako blizu.
{17271}{17339}- Probija led... | - Da.
{17341}{17404}- Idete doma? | - Trudim se.
{17406}{17455}Letovi su postali zabavni?
{17457}{17542}Meni je zabavno | iziæi iz aviona u komadu.
{17544}{17629}- Bojite se letjeti? | - Da. Mrvicu...
{17631}{17678}U Teksasu ste bili poslovno?
{17680}{17740}Ne. Umrla mi je baka.
{17767}{17836}Sve je u redu, | Imala je 91 godinu.
{17838}{17897}- 91... | - Da.
{17899}{17957}Svaka èast. | U èemu je bila tajna?
{17959}{18028}Pahuljice i momak | po imenu Duke.
{18030}{18078}Kako?
{18080}{18192}Da. Govorila je da joj | pahuljice èiste arterije,
{18194}{18278}a Duke pomaže oko ostalog.
{18327}{18382}Ajme, dinamièna žena.
{18384}{18478}Ništa je ne bi pokolebalo, znate? | Veliki optimist.
{18499}{18545}"Uvijek gledaj naprijed",
{18547}{18582}tako bi govorila.
{18584}{18650}- Izvolite... | - Hvala.
{18685}{18749}...pojaèane sigurnosne mjere.
{18760}{18807}- Prija? | - Da.
{18809}{18878}Sigurno? | Uvijek možemo uzeti morski.
{18880}{18939}Isti mój tata... | Kažem da sam dobro,
{18941}{19012}a on: "Sigurno"? Sigurno.
{19014}{19084}- U redu, vjerujem vam. | - Dobro.
{19086}{19147}- Usput, zovem se Jackson. | - Lisa.
{19149}{19202}- Drago mi je. | - Kratko "Jack"?
{19204}{19292}A, ne "Jack", | nisam od 10. godine.
{19315}{19360}Prezime je Rippner.
{19368}{19404}Jack Rippner (Jack Trbosjek),
{19406}{19483}to je kao...
{19485}{19523}Sad znate.
{19525}{19582}- Nije baš lijepo od vaših roditelja. | - Nije.
{19584}{19653}Što sam im i rekao | prije nego sam ih ubio.
{19655}{19681}Što?!
{19726}{19808}Ako vam je utjeha, | moje je kršteno ime Henrietta.
{19810}{19839}Henrietta.
{19841}{19913}No to je ime moje bake.
{19930}{19962}Bilo.
{19990}{20074}Živjela Henrietta, | èiji je duh vrlo živ.
{20430}{20457}Što?!
{20475}{20546}Kažem ti da je bila slasna.
{20611}{20663}Novosti iz Washingtona...
{20665}{20714}Dok jaèa rat protiv terorizma,
{20716}{20790}pomoænik tajnika za | domovinsku sigurnost Charles Keefe
{20792}{20842}kreæe u 7-dnevni obilazak
{20844}{20915}luèkih gradova Juga. | Prije 4 mjeseca,
{20917}{21003}uznemirio je Ministarstvo | ovim primjedbama na prvoj
{21005}{21052}tiskovnoj konferenciji...
{21054}{21152}Ne diskriminiram, samo komuniciram. | Premda ne ljubazno.
{21154}{21233}Nemojte me krivo shvatiti, | vjerujem u diplomaciju.
{21235}{21344}No prvo morate imati | njihovu pozornost.
{21377}{21484}Imam li je? | Zahvaljujem.
{21486}{21598}Dame i gospodo, pljesak za ukrcaj | u let 1019 za Miami, Florida.
{21808}{21882}- To smo mi. | - Èudima nikad kraja.
{21884}{21914}Da.
{21940}{21995}- Pustite to meni. | - Ne, molim vas.
{21997}{22035}Da.
{22037}{22081}- Zadržite ostatak. | - Puno hvala.
{22083}{22115}Hvala.
{22131}{22157}Onda...
{22159}{22199}Ostavljenu prtljagu
{22201}{22299}- prijavite osiguranju. Hvala. | - Trenutak. Oprostite.
{22301}{22387}Da.
{22409}{22437}Samo malo...
{22472}{22522}Moram to obaviti.
{22524}{22550}- Žao mi je. | - Dobro.
{22552}{22598}- Bilo mi je drago. | - Drago mi je.
{22600}{22650}- Ugodan let. | - I vama.
{22652}{22684}Bog.
{22686}{22750}Da, èini se da kreæemo.
{22752}{22828}Oluja je otišla. | Ne, ima vremena.
{22830}{22912}- Hvala na strpljenju. | - Mo'š mislit'.
{22943}{23002}Požurimo se. | Prolazim!
{23081}{23142}- Uspjeli ste, momci. | - Jedva.
{23144}{23186}Hvala. Pa-pa.
{23188}{23224}Izvolite... Izvolite...
{23289}{23352}- Hvala. Ugodan let. | - Hvala.
{23354}{23405}Hvala na strpljenju.
{23407}{23467}Desnu. Ugodan let.
{23470}{23529}- Bog. | - 18-G. Prolazom, pa lijevo.
{23531}{23582}- Hvala. | - Hvala na strpljenju.
{23584}{23618}- Kako ste? | - Bolje.
{23620}{23657}- Isprièavamo se zbog kašnjenja. | - 21-F.
{23659}{23711}- 21 -F je ravno... | - Hvala.
{23713}{23760}Bog, kako si?
{23800}{23905}Prigušit æemo svjetla | tijekom noæašnjeg leta.
{23907}{23972}Svjetlo za èitanje | ukljuèuje se na naslonu za ruku.
{23974}{24047}Kad kapetan iskljuèi
{24049}{24125}znak za vezanje pojaseva, | poslužit æemo piæe,
{24127}{24192}sokovi i kava su besplatni.
{24194}{24255}- Pomoæi æu vam. | - Vino i kokteli naruèite uz naplatu.
{24376}{24416}Bog.
{24418}{24463}Opet.
{24465}{24526}- Niste u 1. razredu? | - Ne.
{24528}{24582}- Uvijek putujem ekonomskim. | - I ja.
{24584}{24696}Mislim da je to moje mjesto.
{24698}{24767}- Ma nemoguæe. | - Ne znam.
{24769}{24824}- Piše 18-G? | - Zafrkavate se.
{24826}{24903}Ne zafrkavate se... | Nosaè?
{24905}{24984}- Ne, ne, sve je u redu. | - Zahtijevam.
{25033}{25065}- Dobro ste? | - Da.
{25067}{25104}- Sigurno? | - Da.
{25106}{25165}Inaèe sam baždarena.
{25194}{25248}Povjetarci su bili jaki.
{25250}{25318}U svakom sluèaju, | više vam ne dam.
{25427}{25487}Pa kakva sluèajnost!
{25489}{25551}Da, znam...
{25586}{25631}Samo malo.
{25633}{25683}Da me ne uhodite?
{25717}{25745}Ne.
{25878}{25929}- E, jeste me... | - Oprostite.
{25992}{26037}- Bože... | - Jeste li dobro?
{26039}{26114}Kažem li da, | pitat æete "Sigurno"?
{26116}{26186}Ne, to je oblast vašeg tate.
{26209}{26246}Da, jesam.
{26248}{26327}Danas sam na sprovodu | popila jeftina vina.
{26329}{26388}U sprezi s jeftinom votkom...
{26390}{26465}- Shvaæam. | - Zašto krivim vas.
{26467}{26534}- Sad mi je grozno... | - I treba.
{26536}{26569}Stvarno.
{26571}{26666}Noæ je bila duga, pa èim | prije pospremite stvari i sjednete,
{26668}{26736}tim æemo prije krenuti.
{26738}{26807}- Neto treba nosaèa... | - Oprostite.
{26809}{26862}Dobro.
{26937}{26974}Dajte meni...
{26992}{27053}- Puno hvala. | - Nema na èemu.
{27055}{27144}A ja baš pomislila kako | više nema kavalira.
{27177}{27213}Ugodan let.
{27228}{27269}Ajme...
{27295}{27347}Veæ sam na 2. poglavlju.
{27349}{27377}O, sjajno.
{27437}{27487}Prije sam joj dala knjigu.
{27489}{27554}Obožava doktora Phila.
{27556}{27612}Vidio sam. | Ljubazno od vas.
{27614}{27655}Takva sam.
{27657}{27698}Udovoljavam | ljudima od jutra do sutra.
{27733}{27787}- Al' ste popularni. | - Oprostite...
{27789}{27870}- Ne, u redu je. Ne. | - Obièno nije tako.
{27872}{27904}Samo dajte.
{27906}{27939}Što je?
{27971}{28024}Ne, sve je u redu.
{28026}{28089}Znaèi stvar krenula?
{28091}{28146}5:30, dogovoreno.
{28193}{28266}Posao... zadnji put.
{28293}{28340}- Zbogom, Joe. | - Ugodan let.
{28559}{28621}- Hvala. | - Nema na èemu.
{28668}{28739}Molimo prestanite koristiti | elektronske ureðaje.
{28741}{28824}Dojavljivaèi, mobiteli, | prijenosna raèunala
{28826}{28897}i sve s prekidaèem treba iskljuèiti.
{28899}{28969}Korištenje mobitelom | tijekom leta nije dopušteno.
{28971}{29044}Popis ureðaja | koji se smiju rabiti naæi æete
{29046}{29136}- u èasopisu Fresh Air. | - Osoblje, sjednite.
{29448}{29515}Dakle èeka nas noæni let za Miami. | Dobro došli.
{29517}{29576}Polijetanje možda bude | nemirno zbog vremena.
{29578}{29654}No ne brinite se, | uskoro æemo biti iznad toga.
{29656}{29705}Nadoknadit æemo | izgubljeno vrijeme.
{29734}{29826}Odobreno nam je polijetanje. | Osoblje, pripremite kabinu.
{29838}{29943}Dame i gospodo, | odobreno nam je polijetanje.
{30370}{30429}- Neæemo uspjeti! | - Šuti.
{30431}{30462}Kažem ti, neæemo!
{30464}{30521}Šuti, udarit æu te.
{30523}{30561}Samo se zafrkavam...
{31114}{31166}Jesmo li stigli?
{31168}{31279}Je li Henrietta bila | mamina ili tatina mama?
{31361}{31410}Mamina. Tatina...
{31493}{31557}Tatina je davno umrla.
{31559}{31603}Vaši još žive zajedno?
{31636}{31717}Rastali su se pred 3 godine. | U braku su bili 32 godine.
{31812}{31851}Šteta.
{31853}{31887}Znaèi, mama...
{31889}{31954}Vratila se u Teksas | a tata ostao u Miamiju.
{31956}{32009}Tako... Tata još radi?
{32011}{32079}Da. Ne! | Nedavno pošao u mirovinu.
{32081}{32155}Ima puno vremena, | pa èesto naziva.
{32157}{32210}Znaèi radno vrijeme | nadomješta...
{32212}{32251}Brigom.
{32253}{32318}Ima li za to razloga?
{32365}{32421}Pa i da ima,
{32423}{32498}mora shvatiti da se | život mijenja
{32500}{32568}i da dolazi | do promjena.
{32570}{32599}Shvaæam...
{32601}{32681}Obièno kad sve ide savršeno | i vratite se u koloteèinu,
{32683}{32789}sve ide po planu, | a onda jednog dana iznenada
{32791}{32852}netko zaboravi prièvrstiti | motor za krilo.
{32854}{32898}Da.
{32900}{32990}Govori vam kapetan. | Najgore smo prošli, opustite se.
{32992}{33048}Zavežite pojaseve
{33050}{33118}dok sjedite zbog turbulencije. | Hvala.
{33120}{33215}- Hvala na odvraæanju pozornosti. | - Nisam to radio.
{33217}{33259}Nego?
{33261}{33323}Samo sam usredotoèen | na vas i vašeg oca.
{33354}{33380}Zašto?
{33382}{33417}Dio posla.
{33452}{33483}Peraè mozga?
{33514}{33562}Ne, menadžer.
{33597}{33651}- Ne valjda hotela. | - Ne.
{33653}{33724}- Jer tada biste... | - Kupio novu knjigu o samopomoæi.
{33816}{33846}Što radite?
{33848}{33951}Rušenje vlade, | medijski upadljivi atentati, klasika.
{34023}{34107}- Špijun... Mogla sam misliti. | - Ne, nisam špijun.
{34130}{34193}- Ubojica. | - Grozno gaðam.
{34195}{34247}A, radite za CIA-u!
{34249}{34303}Da je tako, | ne bih smio reæi.
{34305}{34356}- Ali ne... | - Mafija?
{34358}{34397}Slaba lova.
{34464}{34519}Bogme èudno.
{34521}{34580}- Zašto mi ne kažete što radite? | - Veæ jesam.
{34654}{34733}Dobro, oprostite,
{34735}{34816}što god bilo, ne tièe me se.
{34818}{34869}Sve dok ne kanite...
{34871}{34920}Što?
{34922}{34979}Oteti avion.
{34981}{35035}Ne, nisam samoubojica.
{35037}{35099}To je dobro.
{35108}{35166}No imate prvo, | veæinom je to samo moja stvar.
{35168}{35272}No sudbina je htjela da je | moj posao sav oko vas.
{35311}{35376}- Molim? Mene? | - Toèno.
{35400}{35464}Ne shvaæamo kamo | smjerate s tim.
{35466}{35551}Charles Keefe, vaša redoviti | važan gost. Zvuèi poznato?
{35618}{35666}- Ne. A treba? | - Da.
{35668}{35745}Ide prema vašem hotelu. | Zato i trebate slušati.
{35747}{35787}Ne, ne mislim...
{35789}{35837}- Ne, bogme ne moram. | - Morate
{35839}{35879}ako želite da vam tata poživi.
{35935}{35982}- Molim?! | - Èuli ste.
{36084}{36118}Da.
{36161}{36227}Kako želite. | No možda da najprije pogledate ovo...
{36229}{36262}J. R.
{36277}{36357}Joe Reisert. | Vaš otac? Da?
{36374}{36427}- Gdje ste to uzeli? | - Ne ja.
{36429}{36490}Suradnik. S njegova stola.
{36492}{36562}Navodno uz vašu | sliku s promocije.
{36578}{36629}J.R. Definitivno tatino.
{36631}{36672}Njegovi inicijali... No i moji.
{36674}{36741}Jack Rippner. Kreditna, vozaèka.
{36743}{36816}"Ne znam zašto, stjuardeso, | ova emocionalno nestabilna
{36818}{36881}i pripita djevojka, | koju prvi put vidim,
{36883}{36968}najednom je poludjela kad | sam to izvadio iz džepa."
{36987}{37064}Recite stjuardesi | i tata vam umire.
{37175}{37216}Sjednite.
{37458}{37496}Stavite pojas.
{37619}{37665}POZIV OSOBLJU
{37716}{37741}Uspjela?
{37743}{37796}Prvo ode mirovina, | onda i aparat za kavu.
{37798}{37868}Svjetluca 18-G. | Da ja...?
{37870}{37946}Ne, ja æu. | Vjerojatno hoæe još jedno piæe.
{37948}{37998}Možda joj se pridružim.
{38188}{38226}- Bog. | - Bog.
{38228}{38280}- Izvolite? | - Liso,
{38282}{38345}želiš možda | još jedan jastuk?
{38378}{38428}Ne, ništa.
{38443}{38493}Imala je gadan dan.
{38495}{38527}Smrt u obitelji.
{38529}{38617}- O, kako mi je žao. | - Da.
{38619}{38685}- Donijet æu vam vode i maramice. | - Hvala.
{38687}{38735}- Sad æu ja. | - Hvala.
{38775}{38856}Sjajno, Liso. | Samo budi kako treba.
{38858}{38936}Ali obuzdaj osjeæaje.
{38981}{39030}U èinili ste nešto ocu?
{39032}{39132}Ne. A tako æe i ostati | dok igrate kako treba.
{39213}{39247}Što hoæete?
{39249}{39307}Prièekajte maramice i vodu.
{39309}{39388}Kad ostanemo sami, | vraæamo se poslu.
{39390}{39439}- Izvolite... | - Puno hvala.
{39441}{39512}- Brz oporavak... | - Hvala.
{39830}{39877}Trebate nazvati hotel.
{39879}{39947}Vrlo jednostavno. | Svojim utjecajem preselite
{39949}{40051}Keefea iz 3825 u 4080.
{40053}{40122}Detalje prepuštam vama. | Vi samo prodajte.
{40149}{40238}Ja sam kriva osoba. | Nemam za to ovlaštenja.
{40240}{40281}Znam da imate.
{40283}{40338}Znam da ste jedini koji to
{40340}{40388}može obaviti u roku.
{40458}{40517}- Da vam zapišem? | - Ne.
{40552}{40601}Što onda otežete?
{40693}{40779}Znaèi promjena Keefeove | sobe olakšava stvar?
{40851}{40952}Liso, s kakvom god tipièno | ženskom emocionalnom dilemom
{40954}{41040}sad imali problema, | imate moje suosjeæanje.
{41042}{41097}Ali zbog vremena | zdravog razuma,
{41099}{41188}rašèlanimo to na mušku | èinjeniènu logiku.
{41190}{41278}Obièan poziv spašava vam | oèev život.
{41280}{41328}Samo brzo.
{41411}{41459}Ubit æete Keefea, je li?
{41462}{41545}Stvarno trebate poèeti | više brinuti o tati.
{41547}{41630}Kako znam da mu | veæ niste naudili?
{41632}{41685}- Dobro je on. | - Zašto da vjerujem?
{41687}{41782}U zadnjem razgovoru reèeno je | da gleda TV, jede ostatke lazanja
{41784}{41830}i gleda komedijski maraton.
{41832}{41941}Smirite se, mój se momak | vratio srebreni BMW
{41943}{42033}parkiran pred Blossom | Palms Laneu 9321.
{42035}{42111}Sjedi u mraku, | sluša lagani jazz,
{42113}{42191}oštreæi svoj 30-cm | dugi ka-bar.
{42213}{42264}To je nož.
{42424}{42500}- Želim ga èuti. | - Jasno, nakon poziva.
{42502}{42591}Ne, odmah moram znati je li | dobro, inaèe nema ništa.
{42707}{42745}Na vaš raèun.
{42790}{42833}Kreditna?
{42895}{42997}Dame i gospodo, iskljuèen | je znak za obvezno vezanje.
{42999}{43045}Slobodno se kreæite.
{43700}{43828}Nastavak maratona slijedi | nakon promidžbenih poruka.
{43969}{44027}Stižem, stižem!
{44038}{44072}Bože...
{44107}{44151}- Halo. | - Tata?
{44167}{44226}Liso? Veæ si doma?
{44257}{44311}Ne, zovem iz aviona.
{44313}{44353}Kasno smo poletjeli...
{44355}{44448}Znam da ne voliš kad pitam, | no jesi li dobro?
{44450}{44494}Zvuèiš uzrujano.
{44559}{44607}Liso?
{44609}{44675}Još si tamo?
{44754}{44809}Je li vam zvuèao zdravo?
{44811}{44881}Nadam se, jer ja | bolje ne mogu.
{44883}{44923}Završimo sad s tim.
{44962}{45046}Oprostite... možete | li mi opet pomoæi?
{45048}{45114}Zadnji put, obeæavam.
{45116}{45151}Svakako.
{45334}{45365}Bez mudrolija.
{45659}{45713}- Baš ste dragi. | - Živjeli.
{45715}{45791}Nisam oèekivala da | æu morati toliko raditi.
{45793}{45893}Gomila upitnika o vama | prije samog nastavka.
{45895}{45945}Samo malo...
{45957}{45985}- Jasno. | - Nokti...
{45987}{46076}Pustite upitnik.
{46078}{46159}- Podvuæi æu mój najdraži dio. | - Divno.
{46169}{46199}- Našla! | - Sjajno
{46201}{46248}- Spasili ste mi život. | - Da.
{46250}{46333}Napišite adresu, rado bih | vam uzvratila uslugu.
{46335}{46393}Uvijek tako | polomim nokte.
{46395}{46459}Sam mi pomognite | da vratim gore.
{46461}{46552}- Napustite prolaz. | - Izgleda da æe biti sudar...
{46597}{46658}- Vratit æu se po to. | - Ne, evo...
{46660}{46696}- Zadnji put... | - Hvala.
{46698}{46729}Dobro.
{46743}{46836}- Izvolite. Zaklanjam vam sjedalo. | - Nimalo.
{46838}{46882}- Oprostite, gospoðo. | - Idem!
{46884}{46921}Hvala.
{47058}{47124}Ove su danas agresivnije.
{47186}{47265}Nisam želio da se | stvar zakomplicira.
{47310}{47360}Pretpostavljam | da æe to proèitati.
{47362}{47391}Koje?
{47916}{47989}- Kako je? | - O, puno bolje, hvala.
{47991}{48037}- Dobro. | - Hvala.
{48631}{48657}Jastuk?
{48669}{48712}Možda pokrivaè?
{48771}{48851}Jastuk? Jastuk?
{48853}{48934}Želite pokrivaè?
{49547}{49609}Molim vas da se | vratite na mjesta.
{49650}{49721}"Želi se zagrijati | za svoj život.
{49723}{49771}No budite realni.
{49773}{49821}Zovem vas
{49823}{49899}da smjesta | prestanete s pretpostavkama
{49901}{49945}i pozabavite se èinjenicama.
{49947}{50030}Èinjenica: | Strah od èina je ljudski.
{50032}{50094}Ništa ne uèiniti je glupo.
{50096}{50171}Èinjenica: | Razmišljanje umjesto djela
{50173}{50225}samo uzrokuje glavobolju."
{50227}{50297}Ne izmišljam to. | Tu piše.
{50299}{50337}Èinjenica:
{50339}{50383}Sat vremena ste u nesvijesti
{50385}{50448}a soba još nije promijenjena.
{50450}{50509}Zato æu vam nabaviti aspirin.
{50538}{50591}Trebate mi probrani, Liso.
{50647}{50706}Nadali smo se smirivanju,
{50708}{50803}ali ništa od toga. Kontrola | odobrava uspon na 10.500 metara,
{50805}{50885}pa da vidimo možemo | li gore izgladiti stvar.
{50898}{50962}Dakle obavimo to.
{51074}{51150}Ako to obavim, | ako nazovem,
{51152}{51235}obeæavate da æete maknuti | onoga pred tatinom kuæom?
{51237}{51306}Nazovete vi, pa ja, tata se | budi, kava,
{51308}{51389}ništa ne sumnja. Vratite se na posao, | život ide dalje.
{51494}{51570}Upravo nazivam | vaš hotel.
{51605}{51664}Ne moram govoriti | da zvuèite uvjerljivo.
{51666}{51713}- Rekli ste dovoljno. | - Dobro.
{51814}{51886}Dobro jutro, Luxe Atlantic. | Ja sam Cynthia.
{51888}{51954}Halo?
{51956}{51996}Lisa ovdje.
{51998}{52064}Liso? Grozno zvuèiš. | Jesi li dobro?
{52066}{52156}Avion je upao | u veliku turbulenciju.
{52158}{52203}- Još letiš? | - Da.
{52205}{52251}Èujem da | se posvuda kasni.
{52253}{52312}Ponosit æeš se mnome, | sve spremno za Keefea.
{52314}{52393}Kristal na ledu, cigare baš | nije lako naæi u ovo doba.
{52395}{52473}Što ne kažeš... èuj, | treba mi usluga.
{52475}{52511}Sigurno si dobro?
{52513}{52572}Više | me to nemoj pitati.
{52574}{52602}Samo se...
{52604}{52634}POKUŠAJTE POSLIJE
{52755}{52833}Nešto je iskrsnulo.
{52835}{52893}Treba promijeniti Keefeovu sobu.
{52895}{52940}Pronaði spis.
{52997}{53084}Prebacit æemo ga | u sobu 4080. Da.
{53086}{53133}Pin je 4882.
{53151}{53207}- Potom mi... | - Dajte mi to.
{53209}{53260}Cynthia?
{53267}{53297}TRENUTAÈNI PREKID
{53370}{53436}Dobro razmišljate s obzirom...
{53438}{53499}Teèajevi kontrole stresa?
{53501}{53595}Isplate se. Na kraju vas | možda budem morao ukrasti.
{53597}{53640}- Oprostite. | - Da?
{53642}{53719}- Telefoni ne rade? | - Katkad tijekom oluje.
{53721}{53773}Proradit æe kad se smiri.
{53775}{53850}- Hvala. | - Što, nemate rezervni plan?
{53898}{53970}- Zašto ovdje? | - Kriva je vaša baka.
{53972}{54031}Ona je kihnula, vi odjurili,
{54033}{54119}- Keefe promijenio planove i eto. | - Kikiriki, pereci?
{54121}{54159}- Kikiriki, hvala. | - Gospoðice?
{54161}{54201}Ne.
{54218}{54274}Što ako ne prorade?
{54307}{54371}Pokopamo tatu | u zavarenom lijesu.
{54706}{54823}Narode, držite se, | jer imam vijest. Zaruèena sam!
{56202}{56233}Poznajem ga.
{56235}{56305}- Koga to? | - Keefea.
{56307}{56367}Stvarno pošten èovjek.
{56369}{56441}E, katkad zlo | zadesi dobre ljude.
{56453}{56485}Poput vas.
{56538}{56596}Poznajem vas veæ neko vrijeme.
{56598}{56636}Prije ovog veèeras.
{56638}{56707}Koliko vidim, | život vam se vrti oko posla.
{56709}{56790}Povremeni koktel | u kafiæu na uglu,
{56792}{56897}klasièni filmovi kasno naveèer... | I kajgana u 3 ujutro.
{56899}{56945}Kako ste postali usamljenik?
{56947}{57000}Rastava roditelja?
{57042}{57104}Netko vam slomio srce?
{57248}{57318}Kapetan je opet ukljuèio | znak za pojaseve.
{57320}{57403}- Moram na zahod. | - Dopušteno je kretanje po zrakoplovu.
{57429}{57471}Bolje ne mogu.
{57508}{57569}Znate što? Imate me.
{57571}{57654}Nazvat æu èim | to budem mogla.
{57656}{57711}No sad me morate pustiti.
{57748}{57795}Trebam mi.
{57797}{57874}Vjerujem vam.
{57909}{57954}I torbicu...
{57956}{58004}Ali ne toliko.
{58181}{58239}Na trenutak sam | zaista bila nervozna.
{58241}{58285}Ulazili smo i izlazili.
{58742}{58776}Oprostite.
{58954}{58981}Èekate?
{59030}{59083}Da. Hoæeš...?
{59085}{59116}Vi ste prije.
{59181}{59220}Oprostite.
{60062}{60115}O, Bože...
{60306}{60370}Dobro. Ustani.
{61120}{61151}INTERNI TELEFON
{61288}{61307}ZAUZETO
{61329}{61355}Zanimalo me...
{61370}{61390}U 18F NALAZI SE BOMBA
{61482}{61507}ZAUZETO
{61564}{61589}Ne opirite se.
{61594}{61667}Nabrijani ste od silne | kreativnosti. Dišite.
{61669}{61694}Rebecca...
{61726}{61777}Ne smiješ tako odjuriti.
{61779}{61818}Unutra je muškarac.
{61820}{61897}Zahodi su zajednièki. | Vodim te najbližeg tvom mjestu.
{61899}{61969}Ali unutra je i žena.
{61971}{62040}Dobro, znaèi jedan | od onih letova...
{62073}{62132}Zaustavite èovjeka | pred tatinom kuæom.
{62134}{62243}Veæ jesam predusrevši | dvaput vaše objave.
{62245}{62315}Da ih se doèepala | stroga stjuardesa,
{62317}{62394}pošla bi pilotu i veæ | bismo negdje sletjeli.
{62396}{62457}Dogodi li se to, èovjek
{62459}{62559}u BMW-u je doznati. | Zato uèinite tati uslugu
{62561}{62638}i prestanite se kockati | njegovim životom.
{62800}{62894}Ne morate ovo èinit. | Ništa od ovoga...
{63137}{63180}To vam je netko uèinio?
{63212}{63249}Ne.
{63281}{63327}U tome je stvar?
{63377}{63414}Ne.
{63436}{63465}Znate što mislim?
{63506}{63534}Znate li?
{63536}{63613}Niste baš poštena osoba.
{63615}{63673}Pratim vas 8 tjedana
{63675}{63736}i nikad ne naruèite ništa
{63738}{63792}osim jebenog povjetarca.
{63794}{63861}Ne mogu disati, | ne mogu disati...
{63986}{64037}Nikad vam nisam lagao.
{64039}{64110}Znate zašto? | Jer nemam koristi.
{64112}{64182}Oboje smo profesionalci.
{64184}{64234}Imamo volju i sredstvo.
{64236}{64300}Kad toga nema, | naši naruèitelji su nezadovoljni.
{64302}{64360}A tada patimo i život | na postane usran.
{64389}{64451}A to se neæe dogoditi.
{64453}{64491}Je li?
{64534}{64608}- Neæe. | - Dobro.
{64610}{64688}Jer æu vam reæi da | telefoni opet rade.
{64690}{64755}Sigurno smo se | ovaj put dogovorili?
{64803}{64846}Jesmo.
{64867}{64915}Divota.
{64981}{65040}Hvala na brzinskom.
{65072}{65108}Dobro.
{65153}{65188}Hajde...
{65263}{65294}Oprostite.
{65381}{65429}Nije ovo motel.
{65443}{65479}Jasno.
{65558}{65634}- Izgubili ste nešto? | - Da, knjigu.
{65636}{65751}Bila je tu i... | Možda je pala ispod...
{65771}{65831}Biste li pogledali? | Trebate se pribrati.
{65833}{65901}Èini se da smo | privukli pozornost.
{65903}{65983}Èim završe obilazak, | obavit æemo poziv.
{66005}{66070}Kapetan je ukljuèio | znak za pojaseve.
{66072}{66160}Molim da se èim prije | vratite na mjesta. Hvala.
{66499}{66574}Ajme... Ti si mi ukrao | olovku, seronjo?
{66576}{66638}Ne. Prestani. | Spavam.
{66764}{66843}G. Keefe u 7 ima doruèak | a sastanak je toèno u 8.
{66845}{66908}U 9:15 smo gotovi. | Kako je?
{66910}{66956}Automobili su na putu | i stižu na vrijeme.
{66958}{67018}Blindirane escalade, | puni komunikacijski paket.
{67020}{67051}- Sve spremno. | - Dobro.
{67053}{67105}Razdijelite to s promjenama.
{67107}{67131}Misli brzo!
{67133}{67185}- Tata radi. | - Tako!
{67187}{67217}Doði, ti...
{67240}{67291}Trebao bi spavati.
{67309}{67360}10 minuta do slijetanja.
{67865}{67906}Smeæe?
{68127}{68164}Ja æu.
{68408}{68443}Vrijeme...
{68622}{68668}Hvala.
{68972}{69024}Luxe Atlantic. | Ovdje Cynthia.
{69039}{69085}Halo?
{69087}{69149}- Lisa ovdje. | - Bog.
{69151}{69202}Znaèi još uvijek | trebaš uslugu.
{69204}{69309}Da. Provjerila sam s Danom | Youngom iz Održavanja.
{69311}{69387}- Keefe ne može u tu sobu. | - Ali uvijek tamo odsjeda.
{69389}{69503}Znam, no sreðivali su | ventil za vodu u kupaonici,
{69505}{69598}ali ne pravi, | pa ako netko otvori vodu...
{69600}{69646}- Bit æe sranja. | - Tako je.
{69648}{69718}Pa kamo s njim?
{69775}{69841}Liso? Još si tamo?
{69843}{69884}4080.
{69917}{69987}4080. Dobro.
{69989}{70053}- Njegovo æe osiguranje sigurno... | - Toèno.
{70055}{70123}Neæe biti sretni,
{70125}{70208}- pa reci da sam ja odobrila. | - Dobro. O, Bože.
{70210}{70307}Cigare, Cristal... | Nema puno vremena, bolje da poðem.
{70549}{70589}Izuzetno.
{70637}{70677}Blizu smo.
{70902}{70927}Što?
{70929}{71022}Znate što. Mój tata.
{71024}{71089}Nazovite. | Vaš dio dogovora.
{71215}{71279}- Još vas trebam. | - Obeæali ste.
{71281}{71336}Održat æu to. Kad sletimo,
{71338}{71396}potvrdit æu stvar s Keefeom.
{71398}{71480}Dok to èekate, | što ako vaš èovjek odluèi ubiti tatu,
{71482}{71549}- jer niste zvali? | - Ne bez moje zapovijedi.
{71551}{71652}Pas radi samo što gazda naredi.
{71697}{71774}Još malo. | Keefeovi æe u prošlost,
{71776}{71833}tata æe biti siguran...
{71835}{71913}- Molim? | - Što?
{71915}{71947}S njim je obitelj?
{71977}{72024}I njih æete pobiti?
{72062}{72176}Netko želi odaslati glasnu | poruku, njihova stvar.
{72178}{72227}Ja obavim svoje | i idem dalje.
{72401}{72436}O, Bože...
{72464}{72506}Lisa?
{72952}{73034}Dobro došli u Luxe Atlantic.
{73036}{73074}Evo kljuèeva i ostalog.
{73076}{73152}Stavljamo vas u 4080. | Odobrila upraviteljica.
{73154}{73206}4080? Mi smo u 3825.
{73208}{73285}- 4080 je krasan apartman. | - Uvijek smo u 3825.
{73287}{73349}Da, ali u 3825 imamo | veli problem s vodom.
{73375}{73423}4080 ima sjajne zahode.
{73425}{73466}Žele da mijenjamo sobe.
{73468}{73541}Imamo višestruke rezervacije, | možemo u Hilton.
{73543}{73616}Charles, djeca su iscrpljena.
{73618}{73680}- Tko je to odobrio? | - Lisa Reisert.
{73682}{73728}Može, znam je.
{73730}{73787}- Moramo provjeriti sobu. | - Dajte.
{73789}{73823}Razumijem!
{74130}{74196}Zapoèinjemo slijetanje | u Miami.
{74198}{74293}Ubrzo æemo vas prizemljiti. | Znamo da je izbor velik,
{74295}{74365}pa hvala na izboru Fresh Aira.
{74367}{74435}- Sjednite uspravno. | - Koliko još?
{74437}{74498}Par minuta.
{74525}{74611}Gospoðo, molim vas | da ispravite sjedalo.
{74613}{74698}Svakako provjerite | je li pojas prièvršæen,
{74700}{74782}je li sjedalo uspravno | a polica sklopljena.
{74784}{74816}Hvala.
{74898}{74928}Što sad?
{74930}{75018}Odalamili ste me po glavi | i nabili na zid.
{75035}{75065}Otrpite.
{75067}{75143}Predaleko smo otišli, | nemojte sad upropastiti.
{75158}{75232}Dajte se uspravite, Liso.
{75257}{75304}Skoro smo stigli.
{75389}{75443}LUXE ATLANTIC
{75865}{75917}- Onda? | - Ne bogzna što. Jahta.
{75919}{75974}Daleko. Valjda pecaju.
{75976}{76035}- Provjeri. | - Odmah.
{76268}{76345}Posada, pripremite kabinu | za slijetanje u Miami.
{76399}{76483}One koji nastavljaju | dalje izvješæujemo
{76485}{76572}da ih èeka | pomoæ na tlu.
{76574}{76648}Hvala na strpljenju | i ugodan dan.
{76650}{76711}Kad iziðemo, pratit | æu vas do terminala.
{76713}{76771}Popit æemo par cappuccina,
{76773}{76858}ubiti 10-15 minuta | dok ne jave da je Keefe sreðen.
{76860}{76916}Potom napuštam vaš život.
{76947}{77046}Kad nestanem, nazvat æu | g. Ubojicu pred kuæom
{77048}{77139}i slobodni ste. | Možete vikati i urlati,
{77141}{77263}zvati tatu, reci mu da | bježi susjedima. Dobro?
{77265}{77304}Kako god kažete.
{77316}{77357}Nema pitanja?
{77404}{77470}Kakvu sam korist | dosad od njih imala?
{77520}{77570}Najbolje pitanje dosad.
{77593}{77643}Osoblje, molim sjednite.
{78244}{78317}Dame i gospodo, | u ime posade Fresh Aira,
{78319}{78432}prvi vam želimo dobrodošlicu | u sunèani Miami na 26 C.
{78581}{78644}- Dolje sve èisto. | - Jesi li puno ulovio danas?
{78646}{78692}Ne još, gospodine.
{78694}{78759}- Oprostite na smetnji. | - Nema problema.
{78820}{78867}- Dobar lov. | - Hvala.
{78869}{78914}- Sretno. | - Hvala.
{78940}{78988}Trinaest, 1. èasnik na središnjoj.
{79068}{79132}- Možemo. | - Idemo!
{79424}{79487}Obalna straža kaže | da je sigurno.
{79489}{79522}Dovedi ih.
{79843}{79886}Zbilo se na parkiralištu.
{79919}{79960}Ožiljak...
{79981}{80028}Pred 2 godine.
{80067}{80108}Usred dana.
{80212}{80281}Držao mi je | nož na grlu,
{80283}{80331}sve vrijeme...
{80382}{80443}Sve otad stalno se nastojim
{80445}{80513}uvjeriti u jednu stvar.
{80649}{80715}Da niste mogli ništa uèiniti.
{80744}{80788}Ne.
{80867}{80917}Da se neæe ponoviti.
{81381}{81421}Oprostite...
{81454}{81493}Gospoðo!
{81551}{81596}Hvatam avion!
{81623}{81655}Sve u redu?
{81675}{81747}O, Bože! Trebamo pomoæ!
{81749}{81784}Bože!
{81797}{81858}- Je li tko lijeènik?! | - Što je?
{81860}{81918}- Èovjeku treba pomoæ. | - Èekajte.
{81920}{81968}Pomoæ! Tu straga!
{81984}{82069}- Samo minutu... | - Trebamo lijeènika!
{82071}{82173}Molim da ostanete mirni | i vratite se na mjesta.
{82204}{82269}- Ode ti olovka... | - Trebamo hitnu.
{82296}{82357}Zaustavite tu ženu, | probola je èovjeka!
{82504}{82572}Imamo hitan sluèaj. | Osiguranje na izlaz M-2!
{82619}{82649}Osiguranje...
{82651}{82757}Molim pomoæ, šifra 3, izlaz M-2. | Osiguranje, šifra 3.
{82900}{82975}- Kamo je otišla? | - Iza ugla.
{83018}{83059}Jako sam žedna.
{83061}{83140}Ja sam Wendy, aerodromske | usluge.
{83142}{83223}- Jeli ste kod nas? | - Da.
{83274}{83301}Prije sam...
{83338}{83372}Gdje je?
{83397}{83422}Gospodine!
{83427}{83478}Našli smo vam lijeènika.
{83523}{83587}Nemojte govoriti da | ne oštetite glasnice.
{83589}{83643}Nije gadno. Dušnik.
{83645}{83698}Zapravo nije opasno.
{83715}{83775}Nemojte!
{83784}{83850}Trebate u bolnicu!
{83934}{84008}Morate napisati | izvješæe za policiju!
{84071}{84117}- Mój šal! | - Daj, daj...
{84166}{84248}Putnici za let 1221, 1221,
{84250}{84294}Doðite
{84296}{84321}NEMA SIGNALA
{84323}{84385}Ne! Drek!
{84475}{84519}Izlaz M-2!
{84559}{84627}M-2 je gore do kraja!
{84739}{84764}FLORIDSKE KUÆE
{84855}{84924}- Stigli smo! | - M-2!
{85022}{85107}Oprezno. Pozor, putnici koji su | doputovali Fresh Airovim letom 217,
{85109}{85200}prtljagu mogu podiæi na izlazu broj tri.
{85456}{85485}Pazite!
{85785}{85827}Glave gore!
{86328}{86368}Daj, daj, zatvori se.
{87083}{87152}- Hajde! | - Danny, uspori, dušo.
{87154}{87231}- Klinci, oprezno. | - Dvojica gore, dvojica dolje.
{87233}{87274}Lijepo...
{87326}{87356}Lijepo, zar ne?
{87717}{87782}Dobro došli.
{87784}{87854}Na terminalu | je pušenje zabranjeno.
{87856}{87935}Držite prtljagu na oku | i prijavite osiguranju
{87937}{87994}prtljagu bez vlasnika.
{88058}{88094}Mój auto!
{88211}{88253}Daj...
{88360}{88385}AKUMULATOR | JE GOTOVO PRAZAN
{88387}{88425}Sranje!
{88514}{88557}Drek! | Bože!
{88640}{88699}Dobro, još jedan...
{88771}{88810}Ja æu.
{88837}{88893}Lux Atlantic. | Ja sam Cynthia.
{88895}{88969}- Daj mi Keefeovu sobu! | - Što je?
{88971}{89029}Moraš Keefea | maknuti iz te sobe!
{89031}{89100}- Pa veæi za zamijenila... | - To nema veze.
{89102}{89167}Mislim da se | nešto sprema.
{89169}{89212}Ukljuèi požarnu uzbunu.
{89214}{89293}- Kog vraga pri... | - Isprazni hotel! Svi van!
{89295}{89368}Moraš poæi gore | i sama im reæi!
{89370}{89414}Reci da je Keefe meta!
{89416}{89474}Cynthijo, Keefe je meta!
{89476}{89546}- Netko æe ga ubiti! | - O, drek!
{89583}{89630}Drek, drek!
{89739}{89784}Svi van!
{89786}{89850}Svi se uputite | prema izlazu.
{89852}{89934}Budite mirni. | Trebamo napustiti èekaonicu.
{90034}{90092}Još jedan...
{90279}{90316}K vragu!
{90354}{90390}Halo.
{90768}{90847}G. Keefe!
{90910}{90944}- Hello! | - Što se dogaða?
{90946}{91033}Zvala je Lisa. | Maknite Keefea odavde.
{91035}{91107}Uzbuna! Van s njim! | Brzo!
{91252}{91299}- Sarah, brzo! | - Danny.
{91301}{91331}- Charles! | - Lydia!
{91333}{91367}- Moramo poæi! | - Jesi?
{91369}{91428}- Da! | - Svi na krov!
{91430}{91465}Smjesta!
{91560}{91590}ZAKLJUÈAN
{91706}{91782}- Izlazite! | - Trèite!
{91821}{91878}Sve van!
{91896}{91932}Projektil!
{91934}{91961}Brzo!
{91963}{91990}Legnite!
{93130}{93156}O, Bože...
{93574}{93621}Van s njim!
{93623}{93680}Idemo! Idemo!
{93682}{93741}- Dobro ste? | - Jesmo.
{93743}{93800}Idemo!
{94495}{94546}Lisa?
{94558}{94609}- Tata... | - Ma koji vrag...?
{94611}{94674}- Zvao si hitnu? | - Da. Tko je ovo?
{94676}{94748}- Objasnit æu. Si dobro? | - Ja?! Daj...
{94750}{94817}- Moram zvati hotel. | - Sjedni...
{94819}{94902}- Dobro si... | - Da.
{94904}{94959}- Dobro. | - Idem po prvu pomoæ.
{95003}{95047}Stiže murja.
{95141}{95214}- Luxe Atlantic. | - Cynthijo, dobro si?
{95216}{95263}- Da. | - Svi su dobro?
{95265}{95319}Da, mislim.
{95321}{95408}Bože... požuri ovamo. Pojma | nemam kako da ovo objasnim.
{95410}{95489}Stižem.
{95525}{95585}Tata, daj mi svoje | kljuèeve. Moramo...
{95636}{95668}Bog.
{95799}{95840}Tata!
{95842}{95886}Nije mrtav.
{95888}{95985}Hoæu da gleda kako | prvo tebe sreðujem.
{96124}{96164}Tata...
{96199}{96226}Daj...
{96232}{96263}Moraš ustati.
{96352}{96431}Vidiš, Liso, | ja nikad ne lažem.
{96453}{96500}Dakle sad je osobno?
{96502}{96559}Samo dovršavam posao.
{96561}{96639}Zakasnio si. | Svi su živi.
{96641}{96727}U hotelu su svi | preživjeli.
{96737}{96830}Što? Nisi znao? | Zakazao si, Jack.
{96864}{96931}- Dovršit æu posao. | - Ne u mojoj kuæi!
{99852}{99952}Gdje ti je sad tvoja | muška logika, Jack?
{99954}{100026}Mislim da to nije to.
{100028}{100059}Èuješ?
{104471}{104527}Hitna služba. | Ima li koga?
{104529}{104555}Halo!
{104557}{104633}Oprostite na èekanju, | imali smo sluèaj u gradu.
{104635}{104707}Èujem da ste pogazili | èovjeka pred kuæom.
{104709}{104776}U kuæi mi je èovjek | koji me želi ubiti.
{104778}{104843}Ako možete, | zakljuèajte se u sobu.
{104845}{104874}Stiže ophodnja.
{104876}{104915}Požurite.
{105634}{105672}Ne!
{105779}{105810}Bijedan si.
{106656}{106715}- Prièat æemo opet. | - Ni makac!
{107045}{107071}Hej!
{107374}{107454}Hajde, srce, hajde.
{108104}{108162}- Ovamo... ovamo. | - Izvinite?
{108164}{108221}- Šifra? | - Prièekaj.
{108242}{108304}- Cynthia. | - Dobro si?
{108306}{108337}- Da, ja sam... | - Da?
{108339}{108364}Mislim...
{108366}{108444}Pa nije bilo | loše s obzirom na sve.
{108446}{108490}Tek jedan incident...
{108504}{108554}Bila si sjajna.
{108556}{108606}- Hvala. | - Dobro.
{108644}{108695}Oprostite, dame...
{108702}{108727}G. Keefe.
{108729}{108785}Objema želim zahvaliti
{108787}{108861}- u ime svoje obitelji. | - Moramo...
{108863}{108910}Èujemo se.
{108936}{108997}- Prijam. | - Liso?
{108999}{109058}Najgore što sam | doživjela.
{109060}{109119}Znate li vi | što smo prošli?
{109121}{109184}- Pa. | - Prvo nema rezervacije.
{109186}{109286}Onda nam se raspao strop, | posvuda po meni žbuka.
{109288}{109343}Mogu dobiti astmu!
{109345}{109423}Žalim. | Možemo li ikako ispraviti?
{109425}{109479}Da, poènite | s otpuštanjima.
{109481}{109573}Riješite se ove. | Posve je nesposobna.
{109575}{109650}Definitivno. I drska.
{109652}{109718}Shvaæam...
{109776}{109857}Ispunite upitnik | na recepciji.
{109859}{109950}Upitnik?! | Traži da ispunimo upitnik?
{109952}{109999}Želite da ispunimo | karticu za komentare?
{110001}{110062}Da. A kad završite,
{110064}{110110}gurnite si ga u prkno.
{110177}{110227}Da.
{110258}{110314}- Ma ti si moja junakinja. | - Idemo odavde.
{110316}{110362}- Otvorimo bar... | - Šampanjca?
{110364}{110432}Sve, samo ne | zaljevski povjetarac.
{110433}{110633}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan  
