{1}{1}25.000
{331}{394}Prtljažnik? - Ne.
{399}{444}Plot?
{448}{494}Propeler?
{499}{531}Jesi li siguran?
{535}{587}Da. Zamislio sam nešto | što poèinje na slovo P.
{592}{647}Sve sam navela.
{657}{741}A tatin prdac? | - To je bilo prije 15 min.
{787}{851}I to mora biti nešto | što možeš vidjeti.
{859}{970}Recimo, zamislila sam | nešto na slovo S.
{1001}{1073}Sunce? - Jako dobro.
{1082}{1192}Ja sam na redu. | Nešto na slovo J.
{1204}{1247}Jama? - Ne.
{1523}{1556}Brisaèi!
{1560}{1598}Uèini nešto!
{1888}{1936}Što je, dovraga?!
{2098}{2191}Je li tko za divljaè? | - Dobro da je rent-a-car.
{2212}{2250}Bix?
{2370}{2405}Bix!
{2512}{2555}Bix! Idemo!
{2720}{2761}Ulazi u auto. - Zašto?
{2767}{2817}Jer tako kažem.
{3104}{3153}Dušo?
{3427}{3480}O, moj Bože.
{3634}{3750}Mama! - Vidim. | Idemo Bixu po pomoæ.
{3845}{3881}Doði.
{3968}{4014}Mama! Mama!
{4498}{4559} ZADAH SMRTI | (NOÆ ZA UMIRANJE) 
{6435}{6478}Ubojica
{6483}{6554}Domaæe. Èisto.
{6563}{6609}Ecstasy.
{6615}{6725}Moram reæi da može | uzrokovati zbunjenost,
{6743}{6828}dezorijentaciju i priviðanja.
{6880}{6946}Upozoreni ste.
{7011}{7085}Kako znam da su pravi?
{7391}{7432}Shvaæam.
{7541}{7590}Ne mièi se.
{8146}{8248}Idete do Area 52-a? | - Da. Malo kasnimo.
{8335}{8393}Hej...
{8461}{8514}Vozite oprezno.
{8690}{8743}Fali još jedan.
{8749}{8798}Je li ovo za izlet?
{8804}{8848}Ti si Frka? - Jedan i jedini.
{8852}{8909}Nelsone, kako je? | - Ovo je Cookie.
{8915}{8965}Jack. - Gretchen.
{8971}{9046}Cookie, Jack, Gretchen. | Dobro.
{9079}{9157}Držite noge i ruke | unutra cijelo vrijeme.
{9165}{9237}O stankama za nuždu | odluèujem ja.
{9243}{9354}A tko onim glupim glasom pita | jesmo li stigli, leti odavde.
{9447}{9503}Jesmo li stigli?
{9711}{9803}Je li tko bio u Area 52-u? | - Ja, prošle godine.
{9816}{9904}I? - Daleko najbolja | zabava u pustinji.
{9915}{9987}Ja sam u Paviljonu. | Doði do mene.
{10007}{10085}A ti, Gretchen? | - Ondje mi je deèko.
{10104}{10195}Èula sam da izlazi s mojim | zgodnim profesorom ekologije.
{10215}{10287}Odakle je poznaješ? | - Znam je s fakulteta.
{10308}{10353}A ti, Frka?
{10363}{10440}Cure si oslikavaju tijela | i hodaju uokolo u toplesu.
{10469}{10546}Umrijet æeš kada to vidiš. | Raj sisa.
{10571}{10656}Trebam dobar opis. - Zašto?
{10666}{10698}Ne vidim.
{10704}{10773}Zbilja? - Slijep sam.
{10880}{10960}Dobar si. | Vježbaš to doma?
{10997}{11051}Što se dogodilo?
{11093}{11162}Pikado strelice. Sa 6 g.
{11188}{11268}Poslije toga prestali su ih | raditi s metalnim vrhom.
{11274}{11353}To si ti? Plastiène | nikada nisu zaživjele.
{11360}{11429}To zahvali mome bratu.
{11455}{11518}Žao mi je. - Ne.
{11544}{11595}Zbilja?
{11761}{11856}Gdje je zahod? - Ovuda.
{12096}{12170}Znaš, Frka i ja | smo u istom bratstvu.
{12177}{12232}Jack se zna snaæi.
{12255}{12312}Tip je dobar.
{12380}{12420}Budale!
{12426}{12471}Nisam bio ja!
{12488}{12556}Je li on zbilja...? - Da.
{12638}{12704}Nadoknadit æu mu to. | Pazite ovo.
{12797}{12864}Nisi valjda. - Jesam.
{12871}{12957}Ne ostavljaj me nigdje | samog ni sa kime i ni sa èime.
{12963}{13060}Lud je. Izgubio je lijeènièku | dozvolu jer je spavao s lešom.
{13083}{13165}Èuo sam da je bila komad. | - A on ju je ubio.
{13174}{13251}Previše toga mu žele | prišiti. - Komu to?
{13280}{13354}Ono što ne zna | neæe mi nauditi.
{13460}{13520}Možda sam lud, | ali nisam glup.
{13526}{13607}Jedna rijeè. Web-kamera. | - Ne znam o èemu ti to.
{13629}{13707}Zaèepi jebenu gubicu, | smeæe jedno.
{13744}{13821}Ukrao si moje bebice. | Sakrio ih u naprtnjaèu.
{13838}{13912}I otišao sa svojim | prijateljima u karavanu.
{13922}{13989}Želim ih natrag. Fale mi.
{13994}{14093}Area 52, u šatoru za 2 h. | Ako te nema, mrtav si.
{14138}{14226}I raspitaj se malo, | uvijek održim obeæanje.
{14330}{14440}Tko je to? - Pogrešan broj.
{14621}{14739}Odakle ti ime? - Zovu me Frka | jer kažu da stvaram probleme.
{14774}{14823}A Cookie?
{14827}{14901}Roditelji su mi dali | da ga izaberem s 3 g.
{14922}{15007}Da sam ja tada birao, | bio bih Vatrogasna kola.
{15040}{15114}Ja bih bio Piško. - Vidi se.
{15119}{15170}Budi dobra. - Zašto?
{15199}{15267}Tatica ti može uljepšati dan.
{15274}{15321}Je li to E?
{15340}{15417}Ima još puno toga. - Gdje?
{15426}{15493}U mojoj naprtnjaèi. - Koliko?
{15499}{15567}Dovoljno za sve u autu.
{15607}{15670}I za naših 100 | najboljih prijatelja.
{15829}{15860}Što?
{15933}{15982}Ne budi paranoièna.
{15988}{16051}Ja jesam za | dobar provod, ali...
{16065}{16143}Ne i za provod u æuzi? | - Toèno.
{16269}{16362}Ne mislim se toga riješiti. | Ovdje je barem 20 somova.
{16415}{16498}Pronaði drugi prijevoz. | - Ne možeš me ostaviti.
{16529}{16587}Nazovi nekoga.
{16704}{16787}Nema signala. | - Ja idem do toaleta.
{16805}{16876}Upravo si bila. | - Reci to mome mjehuru.
{17010}{17075}Ne znam zašto dižeš frku.
{17080}{17146}Nelsone, možeš mi pomoæi?
{17160}{17225}Hvala na podršci.
{17332}{17385}U mrtvoj toèki smo.
{17529}{17593}50 $ da je to bilo 5.2.
{17605}{17732}Umrijet æu ovdje od | vruæine ili od potresa.
{17743}{17787}Ne možeš ga ostaviti | ovdje bez signala.
{17793}{17834}Gretchen, daj.
{17840}{17914}Odvest æu te natrag | do gostionice. Samo to.
{18068}{18129}Jeste li osjetili ovo?
{18251}{18292}Dovraga.
{18369}{18423}Daj mi nešto dobro.
{18429}{18498}Idemo na opaki tulum pa | ti stari hitovi nisu dobri?
{18502}{18550}Glazba prati život.
{18555}{18612}Postoje pjesme | za svaku prigodu.
{18616}{18660}Srednjoškolska matura?
{18666}{18707}Green Day, | Time of your life?
{18713}{18778}Prelagano. Bolovanje | od bubrežnog kamenca?
{18797}{18843}Survivor, Eye of the Tiger.
{18849}{18920}Zarobljen u pustinji | umiruæi od žeði.
{18940}{19010}Chopinov Posmrtni marš? | - Kakav klišej.
{19018}{19090}Nije li i umiranje takvo? | - O, Bože.
{19296}{19335}Što?
{19424}{19470}Èini se da se dogodila | automobilska nesreæa.
{19476}{19529}Zovi policiju. - Nema signala.
{19580}{19650}Moramo stati. | - Imam sastanak za 1 h.
{19697}{19746}Slušajte.
{19777}{19846}Nesreæa, policija, nije baš | idealno mjesto za nas.
{19869}{19926}Veæ je netko prijavio?
{19935}{20000}Podsjetnik da treba | živjeti u trenutku.
{20004}{20078}Nikada ne znaš | što ti donosi sutra.
{20136}{20210}Treba se zabaviti | još dok se može.
{20527}{20582}To je to? Bez pozdrava?
{20586}{20632}Budi sretan da sam | te povela i dovde.
{20638}{20690}Ne èini to. | Glasujem da glasujemo.
{21286}{21350}Prerezan ti je dovod benzina.
{21366}{21434}Prerezan? | - Imaš li ljepljivu traku?
{21452}{21525}Trebala bih? Imam | kljuè za matice u prtljažniku.
{21543}{21623}Imam ja nekakve gume. | Trebam ovo pokrpati.
{21652}{21735}Budi ozbiljan. | - Imaš ti bolju zamisao?
{21891}{21959}Cijela kutija? - Nikad ne znaš.
{22002}{22056}Nisi li malo uobražen?
{22060}{22142}Može biti. Kad bih | znao što to znaèi.
{22158}{22235}Pogledaj što sam našla. | - Ukrala si to Frki?
{22244}{22326}Ne znaèi ukrasti | ako ne možeš to vratiti.
{22344}{22400}Da, tako mu i treba.
{22580}{22625}Dobro si? - Da.
{22852}{22904}Nešto je u zraku.
{23065}{23114}Sve je popravljeno.
{23119}{23192}Oprosti. Ja uvijek | igram na sigurno.
{23224}{23293}Zdravo, ja sam Frka. | Tvoja suprotnost.
{23346}{23417}Koja je presuda? | - Trebamo gorivo.
{23424}{23476}Ne stignemo do | iduæe benzinske.
{23482}{23531}Posudit æemo benzina.
{23657}{23703}Gdje je Jack?
{23746}{23782}Jack?
{23841}{23882}Jack!
{23965}{24029}Nismo valjda | izgubili slijepca.
{24155}{24212}Ne èujem ništa. | - Sada æe i omutaviti?
{24268}{24326}Jesmo li na istome mjestu?
{24357}{24448}Ima li koga? Gdje su svi?
{24572}{24640}Mesna štruca. | - Evo telefona.
{24647}{24728}Imam Pomoæ na putu. | - Nema signala.
{24807}{24860}Kakvo je ovo mjesto?
{24890}{24987}Prikolice uz put imale su | satelitski tanjur. 700 kanala.
{25016}{25071}Mi nemamo ništa.
{25276}{25350}Ima li koga? - Trebamo | pomoæ s automobilom.
{25538}{25601}Vraæam se brzo. | Vraæam se brzo.
{25997}{26037}Još ništa.
{26165}{26221}Jeste èuli ovo? - Što?
{26229}{26290}Stani. Vrati se. - Ne mièi se!
{26396}{26442}Što je? - Psst.
{26502}{26573}Vozaè je izgubio | nadzor nad prikolicom.
{26610}{26664}Nekakva katastrofa.
{26682}{26732}Zatvorili su ceste.
{26757}{26812}Èuo sam bio. - Antraks?
{26816}{26870}Objašnjava zauzeti signal.
{26894}{26945}Nadam se da nema povrijeðenih.
{26951}{27021}Polako. Ne znamo što su rekli.
{27110}{27179}Zapeli smo ovdje? | - Nemamo izbora.
{27215}{27271}Treba ipak | provjeriti telefone.
{27277}{27331}Ja idem prva.
{27494}{27560}Nema vode. - Zato ima kreveta.
{27599}{27671}Gdje još ima ovakve | zabave za 25 centi?
{27721}{27801}Duhovit si za slijepca. | - Hvala.
{27991}{28029}Opa!
{28232}{28314}Aparat za kavu u sobi? | Ogrtaèi i papuèe?
{28351}{28401}Ne mièi se.
{28529}{28607}Ne mislim propustiti najveæu | zabavu na Zapadnoj obali.
{28636}{28715}Ako ne odem, | do grla sam u govnima.
{28761}{28817}Mora negdje biti benzina.
{28872}{28909}Moglo je biti i gore.
{28915}{29015}Moglo se samo raditi o vožnji | s tipovima iz hrvaèkog tima.
{29035}{29107}Treba malo razmisliti, | dvije zgodne cure, pivo.
{29152}{29195}Isuse.
{29255}{29320}Pogledaj ovo sranje. | - Što je to?
{29372}{29448}Nikad ne znaš na koga | æeš naletjeti usred nièega.
{29519}{29571}Pogledaj ovo.
{29640}{29700}Pištolj za rakete. Lijepo.
{29772}{29825}Bolesno.
{30063}{30101}Idemo.
{31161}{31215}Ima li koga?
{31463}{31523}RECI MOM SINU | DA GA VOL...
{31708}{31746}Èovjeèe.
{31768}{31825}Idemo odavde. | Neæemo naæi benzin.
{31832}{31920}Bojiš se mraka? - Ne, bojim se | pustinjskih uvrnutih budala
{31927}{32006}koje love male životinje | vrtlarskim priborom.
{32030}{32081}Pogledajmo u ovaj ugao.
{32115}{32195}Samo daj. Ja se vraæam | curama i pivu.
{32232}{32332}Maminom deèku se tresu gaæe? | - Daj, ovo je skroz sjebano.
{32349}{32421}Još malo pa æemo | naæi i ljudske ostatke.
{32749}{32792}Kako hoæeš.
{33091}{33154}Vidiš, ovo je klasik.
{33168}{33231}Prikradaš se ljudima?
{33249}{33340}Kad si slijep, baš i ne znaš | da se nekomu prikradaš.
{33399}{33501}Nelsone, pazi na cure. | Ja nas idem spasiti.
{33591}{33646}Misliš li da ovo nešto znaèi?
{33676}{33757}Neki luðak je ostao i imao je | dovoljno vremena da ubija.
{33769}{33831}Tko je ovo napisao | poremeæen je.
{33836}{33921}Ovo nije baš luksuzni hotel, | zato ostajem u šatoru.
{33965}{34059}Idem uz cestu malo istražiti. | - Ne bi trebao nikamo.
{34082}{34164}Hvala, gospoðice, ali | nisam pitao nièije mišljenje.
{34185}{34228}Nadam se vratiti se | s benzinom.
{34233}{34290}Ako ne, samo pratite raketu.
{34411}{34493}Je li ondje bilo trulog mesa? | - Dobar nos.
{34513}{34585}Našli smo neèiju kolekciju | žrtava nesreæa na putu.
{34672}{34725}Želiš me primiti za ruku?
{34735}{34796}Èiniš se dragim, | ali ne idem tim putem.
{34813}{34868}Jako smiješno, stari.
{34882}{34937}Ne, držanje za ruke je teže.
{34945}{35003}Daj da te primim | pod ruku pa ti vodi.
{35057}{35098}Jesi?
{35118}{35176}Još uz sebe nosim | klupko užeta.
{35182}{35244}Odvežem ga kada sam | na nekom nepoznatom mjestu.
{35249}{35356}Tako ne moram brojati korake. | Ranije sam to uvijek radio.
{35407}{35473}Poput mrvica kruha | za slijepe. - Upravo tako.
{35479}{35539}Pustit æemo Frku | da se on brine.
{35546}{35602}Mi æemo se malo opustiti.
{35774}{35833}IDUÆE ODMORIŠTE | ZA 1,5 KM
{36267}{36338}Nemoj da ti zagori. - Osjetiš?
{36351}{36422}Moram se snaæi | svojim ostalim osjetilima.
{36429}{36502}Osjetilo mirisa je prvo, | ono s kojime se rodimo.
{36521}{36588}I posljednje na samrti.
{36604}{36681}Neæeš valjda sada poèeti | prièati prièe o duhovima?
{36698}{36772}Jer mi se sada baš pleše.
{36812}{36877}Jeste vidjeli vijesti | prošli tjedan?
{36882}{37002}FBI lovi kuhara èiji je tajni | sastojak meso njegove žrtve.
{37064}{37138}Zadnji put je | viðen u gostionici.
{37146}{37194}U pustinji.
{37221}{37270}Uz osamljenu...
{37309}{37359}...cestu.
{37420}{37466}Netko je ondje.
{37493}{37530}Tko?
{37539}{37609}Upravo sam ga vidjela | u gostionici. - Sigurno?
{37649}{37713}Nadam se da ne gledaš mene.
{37720}{37788}Ostat æu s Jackom, | vas dvoje idite vidjeti.
{37912}{37972}Stajao je ondje.
{38081}{38131}Ima li koga?
{38240}{38297}Izgleda da mi se priviða.
{38371}{38427}Trebala sam znati.
{38495}{38569}Ne uzimaj | pilule od stranaca.
{38606}{38688}A piæe od tipa kojega | poznaješ pola dana?
{39099}{39173}Cookie? - Isto što i ti.
{39823}{39863}Hej.
{39894}{39957}Hej. Rekao sam hej.
{40005}{40057}Sve veze su prekinute.
{40548}{40635}Ostali smo bez benzina | i izgubili smo se.
{40647}{40705}Sve sam kanio vratiti.
{40722}{40777}Evo, uzmi.
{40884}{40950}Nemoj me tjerati | da upotrijebim ovo!
{41095}{41186}Što si zadnje vidio? | - Plavo nebo.
{41219}{41275}Sjeæam se te plave boje.
{41309}{41360}Ah, tko ih treba?
{41365}{41422}Oèi se poigravaju tobom.
{41430}{41494}Idem provjeriti | Nelsona i Cookie.
{42875}{42924}Da?
{43756}{43833}Sviða mi se | Gretchenin naglasak.
{43847}{43919}I kako se ne da zafrkavati.
{43984}{44043}Australci su guba.
{44053}{44124}Mislim da je ona | Južnoafrikanka.
{44130}{44188}I Jack je jako drag.
{44223}{44304}Da može vidjeti, | pokazala bih mu palèeve.
{44370}{44479}Ako si raspoložena, znam jedno | zgodno prenoæište u blizini.
{45031}{45075}Jesu li ga pronašli?
{45081}{45147}To su izmislili | kako bi bili sami.
{45173}{45238}Oboje su ondje? - Da. Zašto?
{45284}{45361}Ništa. - Što ništa?
{45422}{45496}Ništa. Uèinilo mi se | da sam nešto namirisao.
{45508}{45566}Namirisao? Neku životinju?
{45617}{45677}Samo ako je na dvije noge.
{46101}{46163}Sranje! Sranje! Sranje!
{46169}{46229}Znam da si tamo.
{46512}{46575}Tražim suprugu, Rose Stucky.
{46584}{46652}Plavuša u indijanskoj jakni.
{46670}{46750}Jesi li vidio nekoga? - Ne.
{46786}{46882}Neki me prijatelji èekaju | malo dalje odavde.
{46933}{47007}Ako se ubrzo ne vratim, | doæi æe me tražiti.
{47025}{47079}Dobro.
{47111}{47169}Izaði malo da te vidim.
{47595}{47664}Ti si prva osoba | koju vidim veæ satima.
{47700}{47800}Jesi dobro? - Da. A vi?
{47848}{47929}Da, sjajno. Hajde, popni se. | Povest æu te.
{48009}{48091}Ne treba. - Sigurno?
{48123}{48186}Nikad ne znaš na što | možeš naletjeti.
{48475}{48544}Mogu li probati? | - Samo mrtvi eter.
{48636}{48711}Neobièno je ovdje veèeras. | Ovo s cestama.
{48795}{48855}Što s njima? - Zatvorene su.
{48942}{48999}To gotovo ima smisla.
{49044}{49097}Ima li koga?
{49119}{49163}Hej.
{49176}{49254}Možeš tako do besvijesti. | Nema nikoga.
{49567}{49632}Rekao si da te | prijatelji èekaju?
{49648}{49707}Na raskrižju. | Ne možete promašiti.
{49747}{49819}Bez brige. | Vratit æu te u komadu.
{50008}{50055}Netko dolazi.
{50147}{50199}Napokon.
{50448}{50502}Gdje su Nelson i Cookie?
{50508}{50564}Uzeli su sobu. | - Plaæaju po satu.
{50570}{50627}Jesu li svi dobro? | - Da, zašto?
{50633}{50711}Dobro. Ostanite mi | na vidiku, može?
{50720}{50814}Jesi dobro? - Da, izvrsno. | Sve je sjajno.
{50847}{50918}Ovo je... | - Henry. Henry Stucky.
{50923}{50972}Zdravo. Drago mi je.
{50978}{51021}Gretchen, Jack.
{51026}{51083}Jack je slijep.
{51094}{51177}Odakle ste vozili? | - Uglavnom u krug.
{51273}{51343}Jeste dobro? - Da, jesam.
{51365}{51433}Traži suprugu.
{51440}{51508}Kada ste je | zadnji puta vidjeli?
{51514}{51580}Jutros. Sigurno jutros.
{51586}{51685}Što se dogodilo? | - Dogaðaju mi se èudne stvari.
{51726}{51785}S pamæenjem.
{51792}{51880}Znam zaboraviti stvari, | što nisam htio reæi Rose.
{51890}{51947}Nisam htio da se brine.
{51959}{52043}Vjerojatno je na benzinskoj, | èeka da otvore ceste.
{52083}{52136}Dobro. Dosta èavrljanja.
{52164}{52233}To je bilo èudno.
{52248}{52300}Zašto ne parkirate ovdje?
{52334}{52377}Frka je vidio nešto.
{52383}{52454}Smjestite se i zakljuèajte. | Vièite zatrebate li što.
{52681}{52722}Stižem.
{52789}{52835}Evo, javljam se.
{52840}{52908}Jesi što našao? | - Da. Tipa u autu.
{52917}{52986}Ceste su otvorene? | - Ne, on ostaje ovdje noæas.
{53005}{53086}Vas dvoje ste dobro? | - Bolje ne može.
{53092}{53130}Dobro. Zakljuèat æu vrata.
{53136}{53171}Što se dogaða?
{53176}{53244}Ne puštajte nikoga unutra. | Vièite vidite li što èudno.
{53422}{53518}Zašto me odjednom hvata jeza? | - Zajebava nas.
{53531}{53607}Zašto? - Jer je on takav.
{53630}{53704}Svakako mu dobro ide. - Da.
{53969}{54029}Upomoæ! Molim vas!
{54262}{54313}Što je bilo?
{54342}{54416}Budan sam. Vodi me odavde!
{54422}{54479}Hajde. Hajde.
{54515}{54577}Isuse! - Trèi!
{54633}{54677}Trèi!
{55706}{55771}Što se dogaða? - Ništa.
{55856}{55986}Jesi li vidio nešto? - Ne. Vi?
{56022}{56080}Ne. Ne.
{56203}{56252}Što onda tražite?
{56447}{56505}Tko ste vi?
{56539}{56596}Što ste mu uèinili?
{56623}{56691}Vidio si ga. - Da.
{56747}{56805}Vidiš ljude koji umiru.
{56828}{56900}Ljude? Više ih je?
{57062}{57143}Dvoje ih je kod skladišta, | ono što je ostalo od njih.
{57187}{57261}Pokušao sam pomoæi, | no nisam mogao.
{57280}{57324}I klinac.
{57330}{57388}O, Bože, klinac. | Bio je skalpiran.
{57394}{57446}Bilo je toliko krvi.
{57556}{57654}Bio je i jedan kamiondžija. | Vidio sam pola kamiondžije.
{57806}{57904}Bojim se da onaj tko | ovo radi ima moju Rose.
{57967}{58044}Možete nam dati malo benzina | da možemo otiæi odavde?
{58051}{58147}I meni treba da tražim ženu. | Možete sa mnom ujutro.
{58503}{58557}Telefon je još zauzet.
{58576}{58680}Volio bih vas oboje èuvati. | - Što se vani dogodilo?
{58701}{58774}Možda sam zeznuo stvar | i nekoga jako razljutio.
{58806}{58869}Ili možda samo gubim razum.
{58873}{58935}Pretjeruješ. Postajem umorna.
{58940}{59010}Dobro. Silazim za trenutak.
{59061}{59121}Dobro vièeš? - Najbolje.
{59147}{59202}Upotrijebi to ako ti zatreba.
{61247}{61313}Pitam se zna li itko | uopæe da smo nestali.
{61380}{61443}Neæe li te Joshua tražiti?
{61448}{61519}Govoriš to s takvim prijezirom. | On ti je cimer.
{61530}{61579}A tvoj je deèko.
{61586}{61664}Odgovor na tvoje pitanje je | ne, neæe me tražiti.
{61683}{61766}Ne zna da dolazim. | Htjela sam ga iznenaditi.
{61815}{61889}Stvari meðu vama | baš nisu najbolje, ha?
{61906}{61958}Nisu nikakve.
{61989}{62075}Rekao ti je? | - Ne. Zidovi su tanki.
{62131}{62227}Mislim da ima drugu, | ali ne želi priznati.
{62234}{62307}Htjela sam ga | veèeras to pitati.
{62380}{62468}Zaslužuješ bolje. | - Svi zaslužuju bolje.
{63417}{63489}POZOR | SEPTIÈKI OTVOR
{63795}{63886}Imam glupo pitanje. | Bi li volio vidjeti?
{63944}{64005}Neke stvari. - Na primjer?
{64011}{64068}Tebe. - Zašto?
{64109}{64177}Sjeæam se kako izgledaju | neke obiène stvari.
{64183}{64263}Ljudi, zgrade, | priroda, kuæni aparati.
{64305}{64375}Ali nisam imao prilike | vidjeti lijepu ženu.
{64387}{64483}Pogledati je u oèi i uživati | u njoj. Bilo mi je 7 g.
{64519}{64572}Tada mi to nije mnogo znaèilo.
{64717}{64847}Drag si. Šator ti je | na tri koraka ulijevo.
{64883}{64941}Ja æu na spavanje.
{65076}{65208}Sutra. Sutra æemo na put. - Da.
{65612}{65685}Hej. - Pomoæ. | Dogodila se nesreæa.
{66715}{66764}Tupan.
{66835}{66891}MOTEL | NA POLA PUTA
{68929}{68978}Hajde, uvrnuta kuèko.
{69494}{69533}Osobni broj
{69569}{69635}Što želiš od mene? | - Gdje si?
{69662}{69725}Možemo riješiti ovo, Redforde.
{70212}{70268}Moram piškiti.
{70292}{70347}Ti i tvoj mjehur.
{70398}{70463}Idi tamo. - Potrgan je.
{70522}{70580}Odmah se vraæam.
{70695}{70791}Nemoj se pomaknuti | dok se ne vratim.
{74662}{74716}Ne! Upomoæ! Upomoæ!
{74747}{74789}Upomoæ!
{74937}{74975}Upomoæ!
{75004}{75058}Pomozite mi!
{77637}{77679}Cookie?
{78080}{78119}Cookie?
{78470}{78572}Cookie? Jesi ovdje?
{79352}{79393}Cookie?
{79695}{79769}Isuse! Prestani se šuljati! | - Oprosti.
{79789}{79890}Jesi li vidio Cookie? | - Ne. Nisam je ni èuo.
{79911}{79965}Zar nije s vama?
{79975}{80049}Gretchen spava, a ja | je nisam èuo da dolazi.
{80125}{80171}Gdje je Frka?
{80228}{80283}Misliš da je s Frkom?
{80356}{80438}Ne bi... - Tvoj je prijatelj. | Provjerit æu telefon.
{81203}{81238}Cookie?
{81587}{81630}Psst. Budi tiho.
{81719}{81761}Èujem vas.
{81866}{81905}Budala.
{81972}{82016}Policija. - Pomozite nam.
{82020}{82072}Halo? - Gospoðo?
{82078}{82132}Upomoæ! - Gospoðo, smirite se.
{82137}{82210}Ne znam gdje smo. | Dogodila se nesreæa.
{82225}{82274}Halo? - Ima li povrijeðenih?
{82278}{82374}Nalazimo se u blizini | motela Na pola puta.
{83869}{83938}Dobro, budala sam.
{83967}{84011}Samo se stišajte!
{85598}{85643}Jebiga!
{86650}{86704}Jesu li svi dobro?
{87208}{87244}Nelsone?
{87555}{87608}Nelsone?
{87672}{87726}Nelsone. Probudi se.
{87859}{87907}Jesi dobro?
{87912}{87979}Jack, mislim da je... - Što?
{88036}{88115}Nije... - Što, živ?
{88330}{88424}Tražio je Cookie. | Mislio je da je s Frkom.
{88580}{88622}Cookie?
{88716}{88758}Frka?
{88939}{89024}Jack? Tvoja ruka. Jesi dobro?
{89175}{89260}Pronašao sam... Jelena.
{89612}{89668}Kako može prespavati sve ovo?
{89787}{89840}Ne mislim da spava.
{90189}{90252}Mrtav je. - Što se dogodilo?
{90270}{90340}Nema vidljivih rana, | ako to misliš.
{90359}{90432}Misliš da to ima veze | sa zatvorenim cestama. - Da.
{90484}{90536}Sjedni ovdje.
{90547}{90640}Provjeri sve kanale. | Potražit æu Frku i Cookie.
{90714}{90761}Ne zvuèiš prestrašeno.
{90769}{90833}Iz Johannesburga sam. | Ne strašim se lako.
{91345}{91391}Cookie?
{91405}{91441}Frka?
{91787}{91838}Ima li koga?
{91928}{91990}Upomoæ! Trebamo pomoæ!
{92112}{92215}Imamo hitni sluèaj! | Motel Na pola puta. Upomoæ!
{92698}{92740}Ovo nije stvarno.
{93052}{93124}Ima li koga? Trebamo pomoæ.
{93386}{93529}Što želiš? - Tebe. Tebe.
{93612}{93732}Tko je to? - Mrtav si.
{93895}{93938}Gretchen!
{94025}{94079}Ima puno toga što me ne plaši.
{94106}{94177}Ali mi je dosta | onog mrtvaca unutra.
{95253}{95301}Ne opiri mi se!
{96722}{96771}Ovo je misterij.
{96786}{96846}Izmeðu svjetla i mraka,
{96862}{96933}noæi i dana, živih i mrtvih.
{96997}{97088}Borit æete se ovdje | ili æete umrijeti ovdje.
{97905}{97951}Predajem se!
{97980}{98060}Dobro? Nasjeo sam. | Sada možete prestati.
{98130}{98185}Shvatio sam. Svi su mrtvi.
{98358}{98408}Ha, ha! Da.
{98433}{98501}Svi ste vi jebene budale. | Dobro?
{98516}{98583}Gretchen, mislio sam | da te bolje poznajem.
{98648}{98702}Svi me ostavite na miru!
{99566}{99608}Gretchen!
{99919}{99957}Jack?
{100219}{100260}Sranje.
{100581}{100626}Gretchen!
{101155}{101218}Jack! Trèi!
{101614}{101683}Hajde! Idemo natrag!
{101905}{101974}Isuse, Frka! Jesi dobro?
{102016}{102065}Srce mi još kuca.
{102072}{102136}Što se dogodilo? | - Ostao sam bez ruke.
{102147}{102193}Šališ se. - Da bar.
{102198}{102243}Je li? - Da.
{102394}{102461}Tip u stanu ispod mene | bio se predozirao.
{102508}{102568}Tijelo mu nisu našli | tjedan dana.
{102639}{102746}Leš mu se rastapao. | Pretvarao se u tekuæinu.
{102752}{102821}Taj se smrad probio kroz pod.
{102855}{102916}Nikada ga neæu zaboraviti.
{102927}{102990}To je taj smrad. Smrt.
{103108}{103179}Kakav nam je plan? | - Smrt se ne planira.
{103214}{103277}Ona doðe kada joj se prohtije.
{103306}{103390}Moraš prileæi! | - Ne. Ne idem bez borbe.
{103412}{103461}Ne ideš nikamo!
{103469}{103544}Neæu izdržati ni do jutra. | U èemu je svrha uopæe?
{103631}{103704}Ti ipak možeš vidjeti. | - A ti možeš drkati.
{103773}{103824}Upotrijebi drugu ruku.
{103834}{103882}Jesi li ti koristio | drugu ruku?
{103887}{103957}Kao da te neki stranac | navlaèi. Nemoguæe.
{104259}{104301}Trèi!
{104886}{104936}Ne trošite metke na mene!
{106045}{106086}Drži ovo.
{106134}{106191}Ako ga namirišeš, pucaj.
{106209}{106268}Dati slijepcu pištolj | znak je oèaja.
{106273}{106322}Bolje i to nego da voziš.
{106991}{107024}Hajde.
{107055}{107115}Dovraga. - Jesmo stigli?
{107228}{107291}Imamo nekoliko | sati do svitanja.
{107297}{107347}Cesta ne može | ostati zatvorena zauvijek.
{107353}{107399}Moramo izdržati.
{107530}{107590}Spremnik s benzinom | udaljen je desetak metara.
{107770}{107802}Lijevo!
{107923}{107965}Otišao je.
{108042}{108113}Recimo da je to smrt. | - Premladi smo da umremo.
{108312}{108355}Desno!
{108431}{108513}Ta stvar æe se stalno vraæati. | Kako æemo ga zaustaviti?
{108614}{108686}Želiš li živjeti, ne smiješ | se bojati umrijeti.
{108695}{108752}To je rekao Aristotel.
{108780}{108838}Možda ipak Jerry Garcia.
{109081}{109149}Jesi se ikada seksala | na vrhu vozila
{109156}{109226}dok te neko èudovište | pokušavalo ubiti?
{109244}{109346}Ne. A ti? - Da. Jednom | Ali bio sam mlad.
{109384}{109440}Nije baš bilo dobro.
{109458}{109518}No ne bih imao ništa | protiv pokušati to opet.
{109523}{109574}Uglaðen si.
{109623}{109663}Jack?
{109861}{109896}Jesi dobro?
{109900}{109955}Zaboravio sam da smo visoko.
{110053}{110108}To nije bilo dobro.
{110137}{110213}Trebalo je to snimiti | i zaraditi nešto sitno.
{110253}{110297}Sranje.
{110420}{110482}Evo. Primi me za ruku.
{110512}{110554}Na najvišoj si stubi.
{110559}{110597}Polako.
{111716}{111757}Pusti ga!
{112212}{112255}Jack.
{112287}{112333}Reci nešto.
{112450}{112501}Smeðe oèi.
{112544}{112642}Bit æe dobro. Spasit æu nas. | Sve æe biti u redu.
{113225}{113260}Ne!
{113327}{113398}Troje ih nije preživjelo. | Ima li još koga?
{116228}{116259}Drž' se.
{117425}{117487}Kako si znao | da imam smeðe oèi?
{119782}{119862}Želiš li živjeti, ne smiješ | se bojati umrijeti.
{121235}{121285}Pusti me. - Nemoj...
{121338}{121418}Upomoæ! - Ne opiri mi se. | Bit æeš dobro. Duboko udahni.
{121439}{121521}Zašto nam nisi pomogao? | - Pomažem. Bit æete dobro.
{121727}{121781}Danas ste spasili živote.
{121802}{121874}Muškarac, izbaèen kroz | vjetrobransko staklo.
{121894}{121940}Prsnuæe vratne žile.
{121946}{122013}Žena, plava kosa, 20, | unutarnje ozljede.
{122041}{122093}Takoðer preminula.
{122150}{122195}Ovdje je muškarac.
{122199}{122252}Bijelac, mislim.
{122258}{122313}To mi je danas | treæa kobna nesreæa.
{122319}{122402}Nešto dalje kod nadvožnjaka | vozaè zaspao za volanom.
{122422}{122477}Cijela obitelj u prikolici.
{122482}{122527}Ne mogu više toga podnijeti.
{122533}{122592}Imamo i mrtvog | starijeg muškarca.
{122610}{122643}Gospoðo?
{122703}{122779}Vozio je i primio se za prsa.
{122818}{122874}Mislila sam da je srèani udar.
{122894}{122945}Auto je samo izgubio kontrolu.
{123007}{123054}Govoriš o 20 somova.
{123077}{123129}Dobro. Naði drugi prijevoz.
{123149}{123195}Ne možeš me ostaviti ovdje.
{123200}{123263}Nazovi nekoga. | - Nema signala.
{123269}{123315}Ja idem u toalet.
{123841}{123888}Nisu to naslutili.
{124232}{124281}Mislila sam da je | to srèani udar.
{124286}{124343}Nema signala. | U mrtvoj toèki smo.
{124374}{124437}Idem u toalet. Moram piškiti.
{124443}{124490}Žena, unutarnje ozljede.
{124510}{124557}Daj mi nešto dobro.
{124563}{124620}Izbaèen kroz | vjetrobransko staklo.
{124636}{124670}Pikado strelice.
{124689}{124748}To je taj smrad, smrt.
{125166}{125224}Upomoæ. Dogodila se nesreæa.
{125480}{125680}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan 
{125697}{125750}Sjeæaš li se nesreæe?
{125776}{125854}Ne. Samo neèega. | Bilo je èudno.
{125907}{125981}Uèinilo mi se da vidim. | I vidio sam tebe.
{126021}{126089}A ti? - Nièega.
{126568}{126645}
