{1}{1}25.000
{1813}{1904}UTRKA ŽIVOTA
{2087}{2158}Nazvali su ga autom obiènog èovjeka.
{2182}{2274}Henry Ford ga je osobno zvao | automobilom za "široke mase".
{2317}{2440}Bio je funkcionalan i jednostavan, | poput šivaæeg stroja ili štednjaka.
{2492}{2579}Mogli ste ga nauèiti voziti | za manje od jednog dana.
{2581}{2690}I dobiti ga u kojoj god boji želite, | tako dugo dok je to bila crna boja.
{2747}{2857}Kad je Ford osmislio model "T", | trebalo je 13 sati za sastaviti ga.
{2909}{3013}Nakon pet godina sklapalo se | po jedno vozilo svakih 90 sekunda.
{3082}{3204}Pravi izum nije bio taj automobil, | veæ pokretna vrpca na kojoj se radio.
{3251}{3347}Ubrzo su i druge grane industrije | preuzele isti naèin montaže.
{3349}{3511}Švelje su postale prišivaèice gumba, | a majstori stolari su radili kvake.
{3545}{3668}Bio je to i poèetak i kraj | maštanja istovremeno.
{3979}{4029}Howarde!
{4083}{4133}Charlese, tebi govorim.
{4135}{4245}- Treba zamijeniti žbice, kao svima. | - Trebali bi raditi bolje žbice.
{4247}{4308}Je li? A što bi onda ti radio?
{6380}{6468}Bila je to zemlja moguænosti.
{6471}{6590}Zemlja se sve više smanjivala, pa je | za uspjeh preostao samo Zapad
{6592}{6643}ljudima s voljom i željom.
{6680}{6776}Ako vam je san bio dovoljno velik | i ako ste imali petlje slijediti ga,
{6778}{6839}mogli ste se uistinu obogatiti.
{6865}{6948}HOWARDOVI BICIKLI
{8263}{8338}- Ovo je govno eksplodiralo. | - Što?
{8340}{8423}To je "Stanleyjev" parostroj. | Kotao je eksplodirao.
{8425}{8475}Možete li ga popraviti?
{8626}{8708}Naravno. Naravno da mogu.
{9532}{9593}Ovo je èudesan stroj.
{9605}{9721}Dvotaktni sustav s kotlom | koji grije ova velika rešetka.
{9723}{9835}U osnovi, | to je mala lokomotiva.
{9837}{9909}- Hvala vam. | - Neke sam stvari poboljšao.
{9911}{9968}Sigurnosni ventil je eksplodirao.
{9970}{10060}Uz pojaèani tlak, | jurit æete oko 60 na sat.
{10062}{10097}Uistinu?
{10099}{10176}A uz pregrijavanje pare, | vidim vas i kako jurite
{10178}{10260}- 80, možda i 90 na sat. | - Je li to moguæe?
{10262}{10377}A èar vam je u tome, g. Coughline, | što mu ne treba hrane i timarenja.
{10379}{10464}Osim ako se ne zabijete u banderu, | neæe se razboljeti i krepati.
{10466}{10501}Uistinu smiješno.
{10503}{10651}Iskreno govoreæi, ne bih dao | više od 5 dolara za najboljeg konja.
{11687}{11746}Ovo nije cilj, prijatelji moji.
{11749}{11837}Ovo je start utrke. | Cilj je buduænost.
{11839}{11922}A novi je Buick "White Streak" | taj koji æe nas u buduænost odvesti.
{11924}{12036}Èetiri cilindra u redu, | 42 i l/2 konjske snage.
{12039}{12151}Ovaj automobil možete kupiti | u svim našim salonima.
{12153}{12229}"'Doba automobila je stiglo', | hvastao se Howard".
{12239}{12296}"'Buduænost je stigla"'.
{12404}{12479}Proèitaj ovo s buduænošæu opet.
{12481}{12533}Veæ se bavim buduænošæu.
{12535}{12631}Pardon. Ja æu ga preuzeti. | Doði amo, djeèaèe moj.
{12633}{12691}Jesi li ti buduænost?
{12805}{12855}Spremaš li se na Mjesec?
{12915}{12951}Mjesec.
{12990}{13075}- Kupujem. | - Treba li nam uistinu to?
{13095}{13145}Ne, ne treba nam...
{13147}{13216}Tu su i kuæica za timaritelja, | pašnjak, sjenik
{13218}{13268}i vrlo lijepe štale.
{13276}{13326}Kako su velike štale?
{13876}{13999}IRWINOV "DESETOTONAC" | SPEKTAKL DIVLJEG ZAPADA
{14151}{14223}- Imam ga. | - Smiri se.
{14275}{14326}Prekini.
{15136}{15186}Hajde, tatice.
{15549}{15599}Tako valja.
{15665}{15733}ALBERTA, KANADA
{15848}{15947}- Ne kupuj mu konja. | - Zašto ne? Odlièan je jahaè.
{15949}{16046}- Zato jer mu je 16 godina. | - Pa što?
{16048}{16113}Morao bi zaraditi za konja.
{16164}{16199}Dobro.
{16201}{16251}Emerson!
{16278}{16338}- On je svima poznat. | - Dobro. Tišina.
{16340}{16401}- A za Longfellowa se i ne zna. | - Zna se.
{16403}{16453}Dickinsonova.
{16504}{16582}"Visinu svoju ne znamo".
{16622}{16702}Znam to. Znam.
{16727}{16777}Onda?
{16801}{16905}"Visinu svoju ne znamo | Sve dok se ne dignemo".
{16907}{16966}- Dobro. | - Izuzetno dobro, Johne.
{16969}{17062}"Ako smo dostojni sebe, | Svojim stasom nebo dosegnemo".
{17064}{17145}- Odlièno. | - Jako dobro.
{17332}{17376}"I junaštvo..."
{17465}{17610}"Junaštvo o kom pjevamo | Obièna bit æe stvar".
{17615}{17653}To je to.
{17655}{17833}"Ne možemo svemu mjera biti, | A bojat se biti vladar".
{17976}{18050}Ti bi ga trebao jahati. | Ti si znao pjesmu.
{18070}{18117}Istina.
{18119}{18187}Ali on izgleda savršeno, zar ne?
{18189}{18268}Da, izgleda.
{18286}{18355}To je prava poezija, Agnes.
{18448}{18505}Hvala vam što ste došli.
{18507}{18597}Došao sam ovamo prije 15 godina | s dvadeset i jednim centom u džepu.
{18599}{18672}Znam da mnogi od nas imaju istu prièu.
{18674}{18839}I ne mogu se prestati pitati, | ako smo iz te bijede došli do ovoga,
{18841}{18907}postoji li za nas u Americi nemoguæe?
{18909}{19021}Iako to zvuèi sladunjavo, | želim nazdraviti buduænosti.
{19052}{19149}Jer je ovdje, prijatelji moji, | doslovno nebo granica.
{19151}{19201}Za buduænost!
{19690}{19800}SLOM!
{19815}{19909}Nije bilo samoubojstava | na Wall Streetu toga dana.
{19911}{19981}To je samo mit | koji se s vremenom stvorio.
{20058}{20173}Prave posljedice toga 29. listopada | vidjele su se tek nešto kasnije.
{20212}{20258}PRODAJE SE ZA 100 DOLARA...
{20260}{20393}Do podneva je sve što je steèeno | u prošloj godini uništeno.
{20395}{20520}U 4 poslijepodne, 10 milijarda dolara | tržišne vrijednosti je propalo.
{20582}{20674}U sljedeæa se dva tjedna | rasap nastavio.
{20721}{20835}U vrlo je kratkom vremenu | 25% radne snage ostalo bez posla.
{20995}{21069}Velika je nacionalna selidba poèela.
{21096}{21167}Obezdomljene su obitelji | izašle na amerièke prometnice
{21169}{21297}u posljednjoj imovini koja im je | preostala. U svojim automobilima.
{21359}{21544}Iznenada su milijuni Amerikanaca | imali novu definiciju "doma".
{21988}{22049}"ÈUDO"
{22156}{22216}Zaradio sam danas 2 dolara.
{22249}{22301}Što?
{22303}{22376}Zaradio sam 2 dolara. Izvoli.
{22506}{22556}Otkuda ti to?
{22655}{22714}Vaš ih je deèko istimario | i promijenio im sedla.
{22717}{22774}Ništa mu nisam morao govoriti.
{22854}{22972}Hej, Riði, gdje je mladi momak | poput tebe toliko nauèio o konjima?
{22974}{23030}Ime mu je Johnny.
{23071}{23130}Možete me zvati "Riði".
{24084}{24134}Jeste li vidjeli...
{24287}{24337}Što se dogodilo?
{24543}{24608}- Što je to? | - Sve.
{24654}{24713}Dickens, Wordsworth...
{24715}{24774}Tvoja "1001 noæ" | i "Moby Dick".
{24788}{24880}- Èak i tvoj Milne iz vremena... | - Zašto? Što se dogaða?
{24906}{25037}G. Blodget ima kuæu, | pravu kuæu, a žena mu kuha.
{25039}{25089}Odlièna je kuharica.
{25091}{25152}Telefon je blizu. Nazvat æemo te.
{25154}{25215}Nazvati i reæi ti gdje smo.
{25218}{25268}Idemo mi svi lijepo doma.
{25270}{25339}- Hajdemo. | - Slušaj me, nadaren si.
{25435}{25485}Nemojte me ostaviti.
{25555}{25605}Vratit æemo se.
{25858}{25968}Idi s g. Blodgetom. | On æe se brinuti o tebi.
{25970}{26020}U redu je, idi s njime.
{26186}{26348}6 GODINA KASNIJE
{26602}{26682}Ne znam, još mi uvijek | djeluješ previsok za jockeya.
{26706}{26756}Nikad nisam imao više od 55 kila.
{26770}{26849}- Gdje si nauèio tako jahati? | - Doma.
{26916}{27008}Slušaj, ovako æe biti. Ja tebi | plaæam 10 dolara tjedno za jahanje.
{27010}{27114}Ti meni duguješ 9 dolara za hranu, | 6 za spavanje u štali i 3 za opremu.
{27116}{27215}- Takav je dogovor. | - Kako æu vam vratiti dug?
{27217}{27252}Pobijedi.
{27394}{27452}Huljo!
{27454}{27492}Pusti me!
{28545}{28591}Pusti me!
{29040}{29138}Za dlaku! Kad izgubiš za dlaku, | bolje je da si pao s konja!
{29140}{29226}Na! Poèisti govna iz štale.
{29228}{29292}Do posljednjega! Za dlaku!
{29294}{29344}Za Boga miloga.
{29496}{29582}Ne, Bille, neæu. | Nema više otkaza.
{29599}{29655}Pa, ne može biti gore nego jest.
{29669}{29755}Èuj, ako se ovako nastavi, | mi æemo...
{29770}{29841}Bit æe sve u redu. Uistinu. Hoæe.
{29870}{29940}Dobro. | Vidimo se u gradu.
{30132}{30236}Frankie. | Hajde, prelijep je dan.
{30238}{30313}- Zašto ne otiðeš u ribolov? | - Èitam.
{30315}{30436}Možeš èitati kad bude kišilo. | Uèit æu te voziti kamion.
{30438}{30512}Veæ si me nauèio voziti kamion.
{30541}{30606}- Što to èitaš? | - "Flasha Gordona".
{30658}{30729}Daj, tata, pa radi se o buduænosti.
{30902}{30961}Bit æemo u San Franciscu | do srijede.
{32835}{32885}Da?
{32911}{32946}Što?
{34893}{34965}ST JUDE'S | JAVNA KUHINJA
{36140}{36193}Uði.
{36195}{36245}Nisam gotova.
{36262}{36317}Sam može dovršiti.
{36333}{36413}Ne želim da Sam dovrši. | Ja želim dovršiti.
{36460}{36515}- Annie. | - Ne.
{39299}{39435}U doba kad je svijetu uistinu trebalo | piæe, u Americi ga niste mogli dobiti.
{39477}{39523}Alkohol je bio nezakonit.
{39525}{39663}Utjehe je bilo malo, a stvari bez kojih | se moralo je bilo puno.
{39688}{39747}Uskoro je stvoren pogranièni grad
{39749}{39868}koji je omoguæavao da na jugu bude | svega èega na sjeveru nema.
{39896}{39950}Sve ste mogli tamo dobiti.
{39952}{40070}Hranu, društvo, dobar gin,
{40072}{40230}a uz kockanje, takoðer zabranjeno, | mogli ste vratiti izgubljenu sreæu.
{40364}{40414}Ubrzaj!
{40537}{40603}Jockey jaši | kao da ima nakovanj u džepu.
{40605}{40676}Neæu se više s tobom kladiti. | Ne sviða mi se.
{40825}{40871}Tko je to?
{40873}{40944}George Woolf, | najbolji jockey na svijetu.
{41263}{41321}- To je Charles Howard? | - Jest.
{41329}{41439}- Mislila sam da je ovamo došao... | - Na brzinu se rastati? Zašto?
{41457}{41507}Pogledaj ga.
{41546}{41600}Nije prebolio rastavu.
{42112}{42189}Bilo je to u palaèi moænoga sultana.
{42191}{42289}- Kojega sultana? | - Sultana Arabije.
{42303}{42412}Živio sam tamo godinu dana, jahao sam | njegove arapske pastuhe danju,
{42414}{42501}a noæu pisao povijest tih krajeva.
{42512}{42614}A onda me, jednoga dana, | sultan pozvao u svoju sobu.
{42638}{42711}Pogledao me i rekao...
{42713}{42812}"Johne Pollarde, | ti si moj najbolji jockey".
{42814}{42949}"Tebe sam izabrao za svoju utrku | od 100 milja od Kusmata do Tripolija".
{42992}{43057}200 milja.
{43059}{43122}Dobro, 200 milja. | Isprièavam se, Sahibe.
{43199}{43307}- Nisi mi trebao kvariti prièu. | - Ta je prièa poèela s 50 milja.
{43309}{43430}Sve se pri preprièavanju produžuje. | Pitaj svoju prijateljicu Wandu.
{43454}{43560}Da više jašeš, a manje prièaš, | mogao bi neke utrke i dobiti.
{43562}{43614}Kladim se u 2 $ da æu te pobijediti.
{43616}{43684}Nisam baš uvjeren. | Kladim se u 5 $ da æu ja pobijediti.
{43686}{43736}Dogovoreno!
{43817}{43869}Razmotrimo izglede. Ti si favorit.
{43871}{43916}- Podijelimo novac. | - Zaboravi.
{43918}{43989}- Dva naprama jedan. | - Dogovoreno.
{43991}{44066}Ti imaš brzoga konja. | Što radiš na zaèelju?
{44068}{44148}Volim èavrljati. | A konj mi nije brz.
{44150}{44202}- Ideš li veèeras? | - Ne, a ti?
{44204}{44246}Ne.
{44275}{44324}- U koliko sati? | - Ne znam. U osam?
{44326}{44406}Dobro. Imam prolaz. Moram iæi.
{44548}{44598}Prokleto bilo!
{44946}{45012}- Imamo ga. | - Ja æu ga uzeti.
{45014}{45067}Gubite se odavde!
{45086}{45180}- Rekao sam da æu ga ja uzeti. | - Slomljena mu je noga.
{45183}{45271}Ionako æete ga morati ubiti. | Ja æu vam uštedjeti naboj.
{45386}{45466}Dobro. Neka mu bude. | Neka ga on sredi.
{45813}{45863}Bok, pajdo.
{45975}{46025}Hej, momèe.
{47118}{47193}Imam prolaz! Moram letjeti!
{47501}{47595}Bijaše jednom kraljevna od Sijama,
{47597}{47700}Bijaše ovdje, | kraj mene ta dama,
{47702}{47827}Nahranio sam je, vinom zalio | i zatim povalio...
{47907}{47957}Jebemu.
{47994}{48108}- Što se rimuje sa "Sijam"? | - Super je. Ti si to ispjevao?
{48124}{48185}Tako je oèito?
{48212}{48302}- Lijepo je. | - Ne, ti si lijepa.
{48330}{48404}Ne govori to. Plaæaš me.
{48489}{48649}Onda, jesi li za, kužiš, akciju?
{48703}{48755}Naravno. Zašto ne bih bio?
{49167}{49279}- Kako si mogao propustiti prolaz? | - Imam prolaz! Moram letjeti!
{49299}{49349}Jesi li slijep?
{49503}{49545}Je li ti dobro?
{50409}{50459}Ne želite gledati?
{50535}{50607}Ne, ne bih baš.
{50609}{50659}Niti ja.
{50863}{50966}Prijatelji su vas doveli | kako bi se oraspoložili? Je li tako?
{51019}{51080}Jest. Tako nekako.
{51082}{51170}Muškarci. Misle kako sve mogu | riješiti tulumarenjem.
{51231}{51305}Isprièavam se, ali, tko ste vi?
{51371}{51421}Marcela Zabala.
{51469}{51573}- Moja je sestra Isabella udata za... | - Aha. Znam.
{51601}{51651}Drago mi je. Charles.
{51999}{52058}Osjeæate li se sada bolje?
{52188}{52228}Ne.
{52255}{52299}Ne, ne baš.
{52389}{52459}A kako bi se i mogli uza sve to?
{53294}{53345}Hajde, pajdo, probudi se.
{53684}{53794}- Jesam li poražen? | - Ne. Uništio si ga.
{53854}{53904}Polako.
{53915}{53980}- Polako. Nježno i lagano. | - Dobro sam.
{53982}{54065}- Èastit æu te juhom. | - Idi i pobjeðuj u utrkama.
{54067}{54124}Idemo k "Sloanu" i samo æemo...
{54127}{54252}Dobro sam. Ne treba mi tvoja pomoæ, | a sasvim sigurno ni tvoje milosrðe.
{54287}{54339}Pusti me na miru.
{54531}{54588}Dvadeset godina | veæ nisam bio na konju.
{54591}{54679}Bez brige. Te se stvari | ne zaboravljaju.
{55160}{55218}Hajdemo.
{55415}{55472}Hajde!
{56453}{56528}Nagovorila te da uzjašeš konja | i sad bi ih i kupovao?
{56530}{56636}- Da, možda par. | - Hoæeš pobjede, ili samo vlasništvo?
{56665}{56721}- Hoæu pobjede. | - Kakvo pitanje.
{56723}{56780}Prvo æeš trebati trenera.
{56782}{56856}Štoviše, dva. Tako da možeš | jednome dati otkaz.
{56972}{57057}Štale Randyja Thatchera. | Dresira 50 ili 60 ponija.
{57060}{57185}- Dobar deèko. Zna konje u dušu. | - Ma, zna govno.
{57187}{57281}Možda imaš u vidu manje uzgajivaèe, | nekoga tko ima vremena za...
{57283}{57326}Tko je to?
{57394}{57482}Prolupao je. | Živi sam u pustari.
{57509}{57597}- Èime se bavi? | - Bio je trener i potkivaè.
{57616}{57687}Sad se samo brine za tog konja.
{57710}{57765}Doði, pogledajmo drugog uzgajivaèa.
{58196}{58234}Bok.
{58254}{58304}Živjeli.
{58417}{58527}- Jeste li gladni? | - Ne, hvala, dobro sam.
{58529}{58576}Charles Howard.
{58588}{58663}- Tom Smith. | - Drago mi je.
{58751}{58817}Što je u zavoju?
{58853}{58907}Ružin korijen.
{58914}{58975}Pospješuje optok krvi.
{58977}{59032}Hoæete li sjesti?
{59090}{59141}Može. Hvala vam.
{59269}{59319}Hoæe li se oporaviti?
{59321}{59380}Veæ se oporavio, malo.
{59406}{59457}Hoæe li se utrkivati?
{59498}{59577}Ne. On više ne.
{59624}{59675}Zašto ga onda lijeèite?
{59720}{59770}Jer ga mogu lijeèiti.
{59834}{59884}Svaki je konj za nešto dobar.
{59930}{60028}Može vuæi kola ili predvoditi konje.
{60030}{60090}I još ga je lijepo vidjeti.
{60115}{60275}Ne možete ga otpisati | zbog lakše povrede.
{60603}{60653}Je li to kava?
{60670}{60720}Jest.
{60820}{60870}Loša je.
{60924}{61034}- Uvijek govorite istinu? | - Da, nastojim.
{61265}{61331}TRI MJESECA KASNIJE
{61440}{61530}Nije to samo brzina. To je duh.
{61540}{61625}Želite konja koji se | ne boji natjecanja.
{61627}{61715}Pola ovih konja su cirkuski poniji.
{61717}{61802}Vi želite konja | koji neæe uteæi od borbe.
{61829}{61879}Kako æete naæi takvoga?
{61922}{62020}Pobjednik sam "Robles Handicapa". | Drugo mjesto na "Tijuana" derbiju.
{62022}{62083}Prvo na "Manzanita Oaksu", | utrci s visokim nagradama.
{62086}{62123}Znam.
{62125}{62250}- U Tijuani je konj sišao sa staze. | - Zvuèi dobro. Javit æemo ti.
{62252}{62317}Mogu vježbati konje ujutro.
{62350}{62434}Ili ih hladiti nakon utrke, ako želite.
{62436}{62494}Uistinu? Hladio bi ih?
{62525}{62575}Ovo je puna šaka brade.
{62611}{62662}Ostvario mi se san.
{62664}{62773}Upregnuo bih te u plug, | to bi bilo za tebe.
{62792}{62847}Jesi li se natjecao za novac?
{62949}{62994}Ne bih rekao.
{62996}{63079}Niti od èovjeka nisi brži, | a kamoli od drugog konja.
{63081}{63160}Prokleta vreæa govana za klaonicu.
{63162}{63300}Ovo ti je valjda najbrže u životu, | ti si buduæe ljepilo.
{63779}{63829}Kad je prvi put vidio Seabiscuita,
{63831}{63942}bio je ždrijebe koje je koraèalo | kroz maglu u pet ujutro.
{63944}{64042}Smith je kasnije obièavao reæi | kako je konj gledao ravno kroz njega,
{64044}{64165}kao da mu govori, "Kog Boga buljiš? | Što ti misliš, tko si?"
{64239}{64329}Bio je to mali konj, jedva metar i pol.
{64331}{64382}Bio je i bolestan.
{64384}{64513}Šepao je pri hodu, | zviždalo mu je u pluæima.
{64520}{64659}Smith nije na to obraæao pozornost. | Gledao je konja u oèi.
{64710}{64781}Tako mu svega.
{64928}{65034}Bio je sin Hard Tacka, | potomka slavnog Man O' Wara.
{65036}{65128}Njegovo podrijetlo nije ostavilo dojam | ni na koga na farmi Claiborne.
{65131}{65186}Riješi ga se.
{65298}{65417}Sa šest mjeseci poèinje ga trenirati | legendarni Sunny Fitzsimmons,
{65419}{65512}koji je s vremenom stekao | isto mišljenje o konju.
{65525}{65586}Je li to trkaæi ili cirkuski konj?
{65638}{65711}Mišljenje nije mogla poboljšati | nježna mu narav.
{65713}{65801}Dok mu je predak bio žestok, | gotovo nasilan natjecatelj,
{65803}{65893}Seabiscuit je spavao veæi dio dana
{65895}{66025}i uživao se valjati satima | meðu stablima borovice.
{66043}{66095}Drugi veliki dar bijaše mu jedenje.
{66108}{66243}Iako napola manji od drugih konja, | èesto bi pojeo dvaput više od njih.
{66262}{66333}Fitzsimmons ga je držao lijenim
{66335}{66424}i bio je siguran da mu mora | treningom ukloniti tvrdoglavost.
{66426}{66534}Udari ga toliko puta koliko možeš | tijekom èetiristo metara hoda.
{66536}{66649}Kako to nije pomoglo, | držali su ždrijebe nepopravljivim.
{66687}{66757}Uèinili su ga partnerom za vježbu | boljim konjima,
{66759}{66814}prisiljavali da gubi izravne dvoboje
{66816}{66903}kako bi jaèali samopouzdanje | druge životinje.
{66905}{67071}S tri godine starosti, borio se | u dvije jeftine trke za novac tjedno.
{67073}{67176}Uskoro je postao bijesan i gnjevan | poput svoga pretka Tacka.
{67231}{67327}Prodan je za bagatelu od 2000 dolara.
{67409}{67478}Naravno, sve je to imalo smisla.
{67489}{67614}Šampioni su bili veliki. Sjajni. | Nisu imali mana.
{67651}{67763}Kad su ga konaèno ukljuèili u utrke, | uèinio je ono što su ga nauèili.
{67765}{67798}Izgubio je.
{67851}{67905}Što ti se ipak sviða na njemu?
{67947}{68002}Ima pravi duh.
{68004}{68065}I ja bih rekla.
{68068}{68129}Može li ga se jahati?
{68131}{68181}Naravno.
{68253}{68303}Kad doðe vrijeme.
{68335}{68412}- Zna biti razdražljiv. | - Shvatio sam.
{68427}{68479}Ozbiljno mislim.
{68481}{68531}Sve je u redu.
{68725}{68795}Isuse Kriste! Konj vam je lud!
{69234}{69284}Doði.
{69307}{69357}Hajde, svinje jedne!
{69786}{69837}Sa svima æu se boriti!
{70441}{70491}U redu je.
{70543}{70602}Ne bojim te se.
{70628}{70696}Jasno. Znam ja.
{70737}{70811}Znam ja kakav si.
{70985}{71035}Jesi li gladan?
{71241}{71291}Zacijelo jesi.
{71375}{71425}Hajde, momèe.
{71805}{71908}Bi li ga mogao jahati jedan krug, | da ga ljudi vide na djelu?
{71910}{71948}Odlièno.
{71977}{72058}Red Pollard, a ovo su | gospodin i gospoða Howard.
{72060}{72101}- Bok. | - Živjeli.
{72153}{72216}Sad æemo krenuti.
{72331}{72392}Zna li trèati kasom?
{72394}{72434}E, to æemo vidjeti.
{72901}{73011}- Doima se prilièno brzim. | - Da, u svim smjerovima.
{73050}{73122}Toliko je iscrpljen | da je teško reæi kakav je uistinu.
{73154}{73278}Imam osjeæaj da su ga toliko | muèili trèanjem u krug
{73281}{73343}da je zaboravio zašto je roðen.
{73395}{73470}Mora nauèiti | kako opet postati konjem.
{73509}{73571}Kako to postiæi?
{73757}{73819}Kako daleko neka ga odvedem?
{73822}{73892}Dok sam ne stane.
{73895}{73944}U redu.
{73962}{74026}Mislim da æe to biti prilièno duga tura.
{74051}{74112}Nadam se.
{74549}{74615}Tako, mali moj. Dobar si.
{74618}{74667}Pogledajmo kako si brz.
{74780}{74829}To je to.
{75602}{75693}- Ako ništa drugo, nije bio skup. | - Nije, to je istina.
{75948}{76023}Prokleto bilo. | Èudesna si ti životinja.
{76676}{76767}- Možeš uæi. | - Dobro mi je vani, hvala.
{76770}{76834}Da, tako i izgleda.
{76837}{76886}Ne, uistinu mi je dobro vani.
{76913}{76985}Dobro. Kako želiš.
{77282}{77331}Dobro došli.
{77656}{77716}- Hvala. | - Nema na èemu.
{77985}{78034}U redu je.
{78070}{78131}Nisam baš toliko gladan.
{78134}{78210}Naravno da nisi.
{78213}{78265}To je samo hrana.
{78370}{78434}U redu je.
{78436}{78498}Htio bih te snažnog, a ne mršavog.
{79059}{79162}To su zvali programom pomoæi, | ali je to bilo znatno više od toga.
{79179}{79309}Imalo je desetke imena: | NRA, WPA, CCC.
{79335}{79401}Ali se sve svodilo samo na jedno.
{79456}{79557}Po prvi je put nakon dugog vremena | nekome bilo stalo.
{79598}{79723}Po prvi put nakon dugog vremena | više niste bili sami.
{82277}{82399}- Utrka kozliæa? | - Ne. Samo ga pokušavam smiriti.
{82402}{82481}Ovi pametniji | ne vole biti stalno sami.
{82484}{82599}Katkad ih bilo koja | druga životinja utješi.
{83542}{83591}Prilièno je tiho ovdje.
{83630}{83705}- Što ste uèinili? | - Izvolite pogledati.
{84403}{84531}OK. Nemoj ga uništiti, | ali moramo vidjeti što može.
{84563}{84661}Odvedi ga na tisuæu metara i pusti ga.
{84664}{84776}- Neka ga pustim? | - Da, sinko, to je trkaæi konj.
{84930}{84979}Hajde!
{85193}{85278}Znam da ti možeš i bolje! | Pokažimo im, momèe!
{85371}{85426}Kako izgleda?
{85429}{85495}Pospano.
{85498}{85562}Hajde. Pokažimo im, Djedice.
{85831}{85879}Evo ga!
{85929}{85964}Moj Bože.
{86236}{86300}Ti i ja! Idemo!
{86610}{86663}- Što? Brz je? | - Brz.
{86666}{86717}Koliko brz?
{86745}{86847}Vaš konj je upravo oborio | rekord staze na Tanforanu.
{86947}{87059}Ponekad èeznu | za malo natjecanja.
{87136}{87213}TRKALIŠTE "SANTA ANITA", | ARCADIA, KALIFORNIJA
{87250}{87331}Kad veæ govorimo o gubitnicima, | imam jednog posebnog za vas.
{87334}{87422}Imamo konja èiji su izgledi | 70 naprama 1, a to je još dobro.
{87425}{87522}Taj ne može dobiti niti milostinju, | a kamo li 2000 dolara nagrade.
{87525}{87607}Kamo je zalutao? | On je tvor na vrtnoj zabavi.
{87610}{87660}Muha u zdjeli s punèem.
{87663}{87757}Kladim se da ta raga, Seabiscuit, | neæe izdržati ni kilometar i pol.
{87760}{87849}Ja sam Tik-Tak McGlaughlin, | uživo iz "Clocker's Cornera".
{87956}{88024}- Htjela sam smeðu, imali su crvenu. | - Odlièna je.
{88027}{88086}Ne misliš li da je "H" preveliko?
{88089}{88146}Jesi li vidjela koliki je naš jockey?
{88440}{88530}Favorit je ovaj sivac tamo.
{88533}{88587}Ubrzava kasnije tijekom utrke,
{88590}{88686}pa mu se zalijepi veæ ispoèetka | i budi tik uz njega.
{88716}{88828}Kad naš deèko skuži tko mu je suparnik, | dat æe sve od sebe.
{88831}{88892}Ali, ništa dok se sivi ne trgne.
{88895}{88944}A što ako to bude prekasno?
{89055}{89166}Mislim da to neæe biti važno. | Iskreno reèeno.
{89998}{90055}Hej, Sahibe.
{90058}{90115}Nekako je mali, je li tako?
{90118}{90222}- Izgledat æe ti uskoro još manji. | - Dajem pet dolara da neæe.
{90225}{90274}Dogovoreno.
{90368}{90430}Krenuli su!
{90439}{90524}Pirate's Cove vodi, | slijedi ga Gerondo.
{90527}{90603}Silver Treasure je treæi, | a za njim je Seabiscuit.
{91225}{91274}Huljo.
{91359}{91413}Govno nijedno!
{91464}{91514}Kog Boga radi?
{91586}{91637}- Hajde! | - Što to radiš?
{91640}{91734}Nabit æu te u ogradu, govnaru!
{91749}{91800}- Mièi se s mene! | - Kako ti se ovo sviða?
{91803}{91852}Mièi se.
{91934}{91986}Sviða li ti se ograda?
{92059}{92165}Maiden's Prayer i Seabiscuit | nametnuli su strašnu brzinu.
{92168}{92251}- Stiže konjica. | - Prijeèiš mi put?
{92295}{92412}Vodi Silver s unutrašnje strane, | slijede ga Kendango i Pirate's Cove.
{92442}{92493}Silver Treasure i Pirate's Cove.
{92496}{92615}Pobjednik je Silver Treasure, | za dvije i pol dužine.
{92726}{92792}- O èemu si mislio? | - Prljavo se borio.
{92806}{92882}- Jesam li mu trebao to dopustiti? | - Da, kad su mu izgledi 40 naprama 1.
{92885}{92947}- Gotovo me pritisnuo u ogradu! | - A, je li?
{92950}{93004}Èuj. Imali smo plan.
{93007}{93123}Gurao me. Što sam trebao uèiniti? | Presjekao mi je put!
{93221}{93328}- Prljavo se borio. | - Sinko.
{93368}{93422}Na što si tako ljut?
{93691}{93759}Telefon je blizu. | Nazvat æemo te.
{93762}{93823}Svakih par tjedana | æemo ti dojaviti gdje smo.
{93826}{93890}Idemo svi mi lijepo doma, može?
{94114}{94163}Nadaren si.
{94398}{94447}Moram posuditi novce.
{94546}{94597}U redu.
{94600}{94771}Nisam veæ dugo bio kod zubara | i moram posuditi novce.
{94785}{94886}- To je u redu. | - Ne znam kad æu vam moæi vratiti.
{94888}{94990}Hoæu reæi, kad pobijedimo, | vratit æu vam novce.
{94993}{95045}Naravno, ako me još želite za jahaèa.
{95096}{95149}Naravno da te želim.
{95240}{95296}Koliko ti treba?
{95387}{95431}Deset dolara.
{95459}{95519}Izvoli.
{95658}{95707}Sve u redu.
{95832}{95903}Hvala vam. Puno mi to znaèi.
{96084}{96160}To je to, Djedice. Sad smo OK.
{96163}{96245}U redu je, momèe.
{96249}{96329}Tako je, OK smo. | Ništa ne brini.
{96332}{96417}Imamo sve vrijeme svijeta. | To je to.
{96420}{96486}Nježno i polako. Baš ovako.
{96596}{96685}Što kažeš? | Jesi li spreman?
{96688}{96763}Ti i ja. Idemo!
{97822}{97941}Na koncu, nisu to bile brane, | ili ceste,
{97944}{98040}ili mostovi, ili parkovi, | ili tuneli,
{98043}{98166}ili tisuæe drugih javnih projekata | izgraðenih tijekom tih godina.
{98169}{98257}U pitanju je bilo nešto nevidljivo.
{98260}{98363}Ljudi koji su samo godinu prije bili | uništeni, osjeæali su se obnovljeni.
{98389}{98472}Ljudi napuklih sudbina, | iznenada su zaèuli poziv.
{98475}{98535}Mislim da je ovaj konj izuzetno srèan.
{98538}{98640}Možda je bio na dnu, ali nije | bio otpisan. Nije se prepustio tome.
{98668}{98747}Svi mi možemo ponešto nauèiti | od tog malog frajera.
{98750}{98842}On ne zna da je mali. | Misli da je najveæi od svih konja.
{98845}{98903}Imate velike planove za maloga konja?
{98906}{99008}Ponekad mali frajer, | kad ne zna da je mali,
{99011}{99070}može uèiniti velike stvari.
{99096}{99217}Ovo nije cilj, prijatelji. | Buduænost je cilj.
{99220}{99279}Biscuit je konj | koji æe nas tamo odvesti.
{99282}{99341}Baš konj koji æe nas odvesti tamo.
{99344}{99456}Uvjerili ste me. Stari radijski maèak | mora progutati gorku pilulu poraza.
{99459}{99567}Po jednu za svaku reèenicu, | uvijene u pitu od isprike.
{99570}{99626}Ja æu pitu sa sladoledom.
{99680}{99732}I još nešto. Samo želim reæi...
{99735}{99802}- Hvala na pjenušcu. | - Nema na èemu.
{99805}{99860}- Jeste li vidjeli unutrašnji dio? | - Nisam.
{99863}{99968}Pogledajte. Vaš je mali konj | rasprodao sva jeftina mjesta.
{100187}{100229}Bože!
{100232}{100308}Što kažete na tolike ljude | na najjeftinijim mjestima?
{100311}{100411}To su ljudi za koje se utrkujemo, | ljudi s èetvrtinom dolara u džepu.
{100414}{100487}Ovo je poprilièna promocija | za ovako malog konja.
{100501}{100566}"Malen jest, ali je žestok".
{100569}{100628}- Što je to? | - Shakespeare, deèki.
{101090}{101137}Svete mi krave!
{101226}{101346}Pogledaj to, Biscuite. | Evo ga. Ti i ja.
{101393}{101442}Požurite! Evo ga!
{101627}{101676}To je za tebe.
{101738}{101802}TRKA SAN ONOFRE
{101947}{102036}TRKA SAN MIGUEL
{102201}{102281}TRKA SAN RAFAEL
{102534}{102640}Šest uzastopnih pobjeda | malog ždrijepca, lijepa hrpica.
{102643}{102738}On bi mogao biti jedno od najveæih | èetveronogih iznenaðenja.
{102741}{102810}Ostala su samo stajaæa mjesta | za vidjeti maloga ponija.
{102813}{102899}Ako ne možete izdvojiti èetvrtaka, | možete viriti sa stabla.
{102902}{102952}Što je tajna ove prièe?
{102955}{103083}Iz pouzdanih izvora sam èuo | da mu prije svake trke daju litru piva.
{103085}{103163}Sa samog trkališta, | ekskluzivno o konjima,
{103166}{103226}Tik-Tak McGlaughlin, | za kino-novosti.
{103229}{103264}Tko je to?
{103440}{103489}Dobro jutro.
{103536}{103580}Što je ovo?
{103583}{103643}Pivo. Od zadivljenih gledatelja.
{103646}{103704}I to dobro pivo. Ima ga još unutra.
{103792}{103877}- Gdje je konj? | - Daje autograme.
{103884}{103918}Što radi?
{103977}{104078}Izvoli, Maxe. Pusti neka se minutu | suši prije nego to prodaš.
{104081}{104149}- Mislite li da æe oboriti rekord? | - Pitajmo njega.
{104151}{104255}Hej, Biscuite, hoæeš li pobijediti? | Hoæeš li oboriti rekord?
{104266}{104344}Što mislite, što je tog konja | preobratilo u pobjednika?
{104347}{104396}Mislim da smo mu samo dali priliku.
{104399}{104468}Ponekad je sve što nekome treba | još jedna prilika.
{104471}{104573}Ima tu puno ljudi | koji dobro razumiju što govorim.
{104638}{104722}Evo, deèki. | Uzmite par potkova sa sobom.
{104739}{104851}Ove su posebne. | Zauvijek donose sreæu. Izvolite.
{105011}{105081}Gdje su mi, dovraga, potkove?
{105144}{105216}- Odustaješ? | - Ne mogu ovako raditi.
{105219}{105313}On nije životinja za paradu. | Trkaæi je konj.
{105316}{105365}Samo malo rada s javnošæu...
{105368}{105465}Ne mogu od njega uèiniti pravog konja | ako nemam vremena za rad s njim.
{105468}{105515}Što? On jest pravi konj.
{105518}{105587}- To još ne znamo. | - Ima šest pobjeda za redom.
{105590}{105650}Protiv koga?
{105709}{105793}Ovo je pravi konj.
{105873}{105918}NITKO RAVAN WAR ADMIRALU
{105988}{106058}Prvo ih je potukao | na derbiju u Kentuckyju.
{106061}{106143}Zatim slomio u Preaknessu.
{106146}{106259}I, napokon, uništio sve | u Belmontu, i osvojio "Triple Crown".
{106262}{106326}S gotovo metar i osamdeset, | velik je koliko i brz.
{106329}{106406}Osamdeset? To moraju jahati dvojica.
{106409}{106473}Velik je.
{106476}{106568}Obzirom na savršeno rodoslovlje | i savršene rezultate,
{106571}{106670}milijunaš Riddle je možebit | konaèno stvorio savršena konja.
{106672}{106764}Pozdravlja vas Horace Halsteder | za "Metrotone News".
{106806}{106901}Što to, dovraga, znaèi? | "Savršen je".
{106904}{106991}- A što znaèi "savršen"? | - Što?
{106994}{107098}Pokaži mi što je savršeno, | pa æu ti ja pokazati što nije.
{107192}{107295}On je najbolji konj Istoka. | Mi imamo najboljeg konja Zapada.
{107298}{107374}Država zaslužuje saznati | koji je konj bolji.
{107377}{107451}Ne možete to vidjeti, ali je | na moj stol upravo baèena rukavica.
{107454}{107536}- Govorimo li mi o utrci dva konja? | - Kako god g. Riddle želi.
{107539}{107611}Samo dva konja, sto dva konja, | vreæe i dva konja.
{107614}{107685}To što smo manji | ne znaèi da se bojimo.
{107688}{107780}U pravu ste. Svaki mali èovjek | u Americi shvaæa što govorite.
{107783}{107882}Jeste li èuli? Imate sastanak | sa sudbinom. Spojak sa...
{107939}{107989}- Sudbinom? | - Sudbinom, tako je.
{107992}{108068}Sudbina, a ime joj je Seabiscuit.
{108173}{108247}Drago mi je da su utrke napokon | došle i do Kalifornije.
{108250}{108319}Koriste li oni kaubojska sedla?
{108335}{108413}Pazite, usporeðivati ta dva konja | je smiješno.
{108416}{108533}War Admiral je pravi trkaè koji je | dobio sve prestižne utrke u Americi.
{108536}{108662}To njihovo ždrijebe trèkara | po nekakvim kolskim putovima.
{108683}{108803}Kad bismo odgovorili svim izazivaèima | koji žele sebe uèiniti poznatima,
{108806}{108850}to ne bi bilo pošteno prema nama.
{108853}{108912}Ali, niti prema njima.
{108915}{109018}Ne biste Jacku Dempseyju u ring | pustili nekog srednje kategorije.
{109021}{109078}Biste li?
{109081}{109157}Srednja kategorija? Ubit æu ga.
{109160}{109250}Šakom u glavu tako da crkne. | Kukavica. Srednja kategorija?
{109253}{109330}- Moramo ga namamiti na utrku. | - Kako?
{109356}{109448}- Ovo je još uvijek Amerika, ne? | - Jest.
{109451}{109501}Lova.
{109504}{109535}Sto tisuæa dolara?
{109538}{109612}- Najveæi iznos u povijesti Amerike. | - Bez daljnjeg.
{109615}{109691}Namamit æete najbolje punokrvnjake | s istoène obale. Sve.
{109694}{109762}Ovo æete trkalište uèiniti èuvenim.
{109765}{109824}Neka samo oni imaju | sva ta plavokrvna govna.
{109827}{109891}Naš je novac dobar kao i njihov.
{109894}{109973}Ovo je naš trenutak. | Oni su zatoèenici prošlosti.
{109976}{110054}- A ovo je buduænost. | - Odlièno.
{110096}{110151}- Doðite ovamo. | - Što je?
{110173}{110263}Zar ih ne želite vidjeti kako | u gomilama izlaze iz vagona,
{110266}{110359}kako dolaze na vaše trkalište?
{110362}{110466}To je sama pobjeda.
{110469}{110592}Ovdje je ciljna crta.
{110595}{110686}- Prodajete li i aute ovako? | - Na stotine.
{110689}{110756}Samo malo! | Tek što ste pomislili da je gotovo,
{110759}{110874}Doc Strub je opljaèkao kasicu | prasicu i prodao srebrninu.
{110877}{110927}Sto tisuæa dolara za jednu trku?
{110930}{110994}Poželim i sam staviti sedlo na leða.
{110996}{111058}Hoæe li Biscuit biti favorit? | Teško.
{111061}{111120}Uslijedit æe invazija na nas.
{111123}{111222}Bit æe to pobjednici Derbyja, | Preaknessa, Belmonta.
{111224}{111308}Polako. Sve je te trke dobio | jedan konj. Ali, za sto somova,
{111311}{111403}kako može Admiral odbiti pristati | u prijateljskoj luci?
{111406}{111503}Ovo je Tik Tak McGlaughlin | uživo iz "Clocker's Cornera".
{111539}{111593}Sudjelovat æete u utrci za sto tisuæa?
{111596}{111662}Što kažete na sto tisuæa?
{111665}{111709}Ne, hvala.
{111712}{111764}- Dajte. | - Isprièajte me.
{111767}{111813}- Sranje! | - Charlese.
{111850}{111938}- Da, shvaæam o èemu se radi. | - Mi æemo se ipak utrkivati.
{111941}{112001}Bit æe i drugih vrhunskih konja.
{112004}{112068}Pobijedimo li, | morat æe se s nama suoèiti.
{112071}{112127}On æe se morati suoèiti s nama.
{112172}{112246}DVA TJEDNA KASNIJE
{112367}{112444}Special Agent je strahotno brz. | Bit æe vodeæi,
{112447}{112526}ali ne može tako cijelo vrijeme, | pa se nemoj lijepiti za njega.
{112529}{112606}- Neæu. | - Indian Broom bi isto mogao biti tu.
{112609}{112725}Znamo da mu ne daju trèati | punom snagom, koriste prstenaste žvale.
{112728}{112816}Treba biti zabrinut zbog Rosemonta.
{112819}{112939}U završnici je poput teretnog vlaka | i borit æe se s tobom za pobjedu.
{112942}{113057}Morat æeš veæ sve obaviti | do trenutka kad on uðe u završnicu.
{113060}{113136}Još je malo blatnjavo od one kiše,
{113139}{113245}pa se drži dalje od ograde, | tamo je blato duboko.
{113248}{113355}- Namjeravam se držati podalje. | - Da, tako valja.
{113391}{113520}Osim toga, | pokušaj osjetiti kad želi ubrzati.
{113573}{113627}Reæi æe ti kad bude spreman.
{115958}{115994}Hajde, Rede!
{116431}{116484}Hajde!
{116715}{116752}Gledaj ga.
{116877}{116912}Hajde!
{117149}{117235}- Ovaj put nisam ja kriv. | - Rekao sam ti, pazi se Rosemonta.
{117238}{117274}Mislio sam da sam pobijedio.
{117277}{117342}- Nisam ga mogao vidjeti! | - O èemu to govoriš?
{117345}{117409}- Bio ti je za vratom. | - Ne mogu...
{117411}{117495}- Što? | ...vidjeti na tu stranu!
{117609}{117657}ULAZ ZABRANJEN
{117660}{117712}- Lagao nam je. | - Što?
{117715}{117805}Lagao nam je. | Želiš li jockeya koji laže?
{117808}{117857}Što hoæeš reæi?
{117860}{117965}Ne vidi. Slijep je na jedno oko.
{118520}{118569}U redu je, Tome.
{118625}{118699}- U redu? | - Da, u redu je.
{118776}{118906}Ne možeš ga otpisati zbog lakše povrede.
{118978}{119017}Laku noæ.
{119160}{119284}Èini se da se taj njihov konj pokazao | slavnim trkaæem za novce od oklada.
{119330}{119439}Ako ništa drugo, ne moramo se više | gnjaviti prièom o Davidu i Golijatu.
{119483}{119537}Dobro, a sad me pustite proæi.
{119608}{119678}OBEZGLAVLJENI JAHAÈ | NA ŠTO JE MISLIO?
{119681}{119767}JOCKEYEVA POGREŠKA STAJALA | BISCUITA POBJEDE
{119835}{119884}Dovraga s time.
{119904}{119936}POSTAJA "UNION"
{119939}{119987}Samo par obavijesti.
{119990}{120130}Prvo, Red Pollard ostaje | Seabiscuitov jockey, sad i zauvijek.
{120133}{120235}Drugo, ako se boje doæi | i utrkivati se, mi æemo ih naæi.
{120238}{120314}Prijavit æemo se za svaku utrku | gdje je War Admiral prijavljen,
{120317}{120434}a ako ga povuku iz utrke, | idemo na sljedeæu gdje je prijavljen.
{120437}{120558}Ne vraæamo se dok se ne ogledamo | i pobijedimo, ili izgubimo.
{120561}{120605}Znate...
{120627}{120726}Radije bih imao jednog konja poput | ovoga nego sto War Admirala. Hvala.
{121340}{121414}Jednostavno ne znam što reæi.
{121417}{121506}Cijenimo to. | I Biscuit takoðer, siguran sam.
{121509}{121651}Sramežljiv je kad su govori u pitanju | jer bi vam se inaèe osobno zahvalio.
{121676}{121845}Danas ste ovdje jer je to konj | koji neæe odustati...
{121848}{121883}Tako je.
{121886}{121950}...èak i kad ga život udari po nosu.
{122021}{122118}Ali, bogamu, svatko nešto i izgubi.
{122121}{122152}E, da.
{122173}{122285}Ili se spakirate i vraæate doma, | ili se borite do kraja. Je li tako?
{122288}{122329}Tako je.
{122427}{122484}- Želite li vidjeti utrku ta dva konja? | - Da!
{122509}{122563}- Uistinu? | - Da!
{122566}{122640}Hoæete li vidjeti kako ovaj momak | jaše konja?
{122672}{122711}Seabiscuit!
{122781}{122882}Nova vijest! Biscuit na ratnoj stazi! | Hoæe li doæi do utrke?
{122885}{122934}Sve u jednome èlanku!
{122980}{123064}Ne shvaæam što ih toliko muèi. | Hoæu reæi, pa pogledaj nas!
{123067}{123216}Konj nam je premali, jockey prevelik, | trener prestar.
{123219}{123268}Isprièavam se, Tome.
{123271}{123326}A ja sam preglup za shvatiti razliku.
{123329}{123405}Èovjek bi pomislio da žele utrku, | a ne da žele pobjeæi.
{123472}{123521}HOWARD U LOVU!
{123639}{123723}Dame i gospodo, | gledam u silno mnoštvo ljudi.
{123726}{123808}More željnih lica | koja zahtijevaju utrku života.
{123811}{123882}Došli su ove veèeri po zimi i vjetru.
{123885}{123949}Izloženi studeni, koncem listopada.
{123952}{124051}Pokušat æu se probiti barem do jednog | od njih, pa æete i sami èuti sve.
{124054}{124098}Isprièavam se. Pardon.
{124101}{124203}Gospoðo, zašto ste veèeras došli | s troje male djece
{124206}{124263}vidjeti ovoga malog konja?
{124266}{124316}Želimo vidjeti utrku ta dva konja.
{124405}{124506}Rekoh, "Ne mislite li | da g. Riddle ovoj zemlji duguje..."
{124509}{124553}Utrku!
{124573}{124635}RIDDLE ŠUTI | NIKAKVA ODGOVORA OD NJEGA NEMA
{124638}{124676}ADMIRAL SE PREDAJE?
{124726}{124775}10000 LJUDI U BALTIMOREU
{124799}{124893}- Dobro, ali pod mojim uvjetima. | - Pod uvjetima kakve god hoæete.
{124896}{124965}Utrka na dva kilometra. | Ništa drugo ne prihvaæam.
{124968}{125056}- U redu. | - Želim start na zvuk zvona.
{125059}{125110}Neæemo koristiti nikakve naprave.
{125131}{125180}Mislite, bez startne rampe?
{125220}{125252}Dobro.
{125255}{125361}I utrkujemo se ovdje, | na domaæoj stazi. Bezuvjetno.
{125405}{125478}Mjesto izgleda dostatno dobro.
{125481}{125560}Siguran sam da æe vam | tu biti udobno, g. Howarde.
{125630}{125664}UTRKA UGOVORENA!
{125667}{125734}UTRKA PRVI STUDENOGA U PIMLICOU
{125766}{125815}Isuse Kriste.
{125839}{125887}Želim biti konj.
{125890}{125960}Velièinom gotovo odgovaraš.
{125963}{126018}Baš duhovito.
{126021}{126099}Ovo niti ne miriše po štali.
{126102}{126170}Vjerojatno koriste deodorant | svakog jutra.
{126173}{126216}A konji ipak kenjaju.
{126305}{126349}Pa, istina je.
{126368}{126412}Ovamo!
{126415}{126455}Biscuit!
{126597}{126668}ADMIRALOVA PRIVATNA ŠTALA
{126671}{126722}Smjestili su nas u sobu za služinèad.
{126725}{126802}- Je li to on? | - Nije.
{126839}{126888}Premali je.
{126964}{127008}To je on.
{127057}{127106}Isuse.
{127289}{127380}Možda je to konj koji | u ograðenom prostoru dobro izgleda.
{127614}{127718}- Moramo odmah izbiti na èelo. | - Biscuit nikad ne ide na èelo.
{127721}{127823}Znam, ali ga moramo nauèiti | da odmah prijeðe u vodstvo.
{127826}{127950}Ako se taj monstrum izdvoji, | nikad ga neæemo dostiæi.
{127980}{128029}Što, trening ispoèetka?
{128111}{128160}Imamo dva tjedna.
{128227}{128271}VATROGASNA POSTAJA BALTIMORE
{128326}{128390}Doðite sa mnom. Pardon.
{128477}{128531}Kupili bismo vaše zvono.
{128534}{128576}KUÆNI RED TRKALIŠTA
{128579}{128668}- Niste se najavili. | - Radi se vjerojatno o propustu.
{128671}{128754}Želite li da upalim svjetla | ili nešto drugo?
{128808}{128868}Ovo je reakcija grabežljivca.
{128871}{128970}Ako ga samo poèešem po sapima, | poletjet æe.
{128973}{129032}Želimo ga nauèiti | da to uèini na zvuk zvona.
{129035}{129077}Kako daleko neka ga odvedem?
{129080}{129175}Trideset metara. | Tek toliko da nauèi povesti.
{129178}{129222}Bit æe tako.
{129258}{129305}- Spremni? | - Spremni.
{129877}{129926}Dobro, kreæemo.
{130129}{130207}TIHO! OVAJ KONJ SPAVA
{130355}{130450}Dajte, Tome. Kad æete raditi s konjem?
{130486}{130545}Vjerojatno kad se probudi.
{130548}{130644}Bože. Za izludjeti.
{130688}{130728}Cijelo trkalište?
{130731}{130843}Hoæu da to uèini bar jedanput | bez ièega ispred sebe.
{130846}{130955}- Ali, ja ništa ne vidim. | - Nema veze. On vidi.
{130958}{131049}Tome, molim vas, | zašto morate uvijek to raditi?
{131052}{131080}Dovraga.
{131142}{131186}Super.
{131257}{131306}Isuse Kriste.
{131507}{131546}Bože.
{131839}{131878}Time.
{131925}{131960}Tikvice.
{132002}{132051}Kako si, Tikvice?
{132105}{132157}Ne srami se.
{132160}{132215}Hej, Rede?
{132274}{132323}Moj Bože.
{132381}{132492}Trebao sam te zaposliti kao jockeya, | a ne kao èistaèa štale.
{132495}{132538}Bilo mi je dobro.
{132559}{132619}Èuj, u nevolji sam.
{132622}{132700}Doveo sam ovog konja | i pokušavam ga prodati.
{132703}{132747}Teška vremena i ostalo.
{132750}{132828}Pitao sam se | bi li ga htio zagrijati za mene.
{132850}{132906}Ako ljudi vide Reda Pollarda...
{132909}{132973}Da, zagrijat æu ga za vas.
{133092}{133161}Prijeði kilometar za deset sekunda.
{133164}{133220}- Može li on to? | - Mora.
{133339}{133374}Pokušaj sad.
{133610}{133654}OK, pokušaj ponovno.
{133801}{133845}Polako!
{135204}{135272}Veæina ozljeda je na nozi.
{135274}{135379}- Koliko je teška ozljeda? | - Ne znam. Smrskana je.
{135382}{135510}11, 12 lomova. Tako nešto. | Morat æemo ga operirati.
{135512}{135565}Strpljivo me prièekajte.
{136555}{136614}Završili smo.
{136617}{136716}Doživotno æe šepati, | ali se èini da æe ponovno hodati.
{136749}{136802}Hoæe li moæi jahati?
{136805}{136842}Ne, neæe moæi jahati.
{136845}{136932}- Sigurni ste? | - Jahati neæe. Hodati hoæe.
{136948}{137027}- Èuvajte se. | - Hvala vam.
{137167}{137266}- Treba vidjeti onog drugog. | - Bit æeš dobro.
{137268}{137346}Za par mjeseci æeš ustati | i bit æeš kao nov.
{137373}{137457}Ja sam onaj koji | izmišlja prièe, sjeæate se?
{137495}{137534}Da, tako je.
{137559}{137617}Potrajat æe možda nešto duže.
{137766}{137832}Morat æemo otkazati utrku.
{137848}{137918}Ne, ne otkazujte.
{137921}{137994}On je krasan konj, | ali sam se ne može utrkivati.
{137997}{138046}Ne otkazujte.
{138215}{138254}Pozovite Woolfa.
{138278}{138357}- Sinko, nitko ne jaše... | - U redu je.
{138378}{138427}Pozovite ga.
{138430}{138511}- Hoæete li otkazati? | - Ne, neæemo otkazati.
{138514}{138601}Red Pollard želi Seabiscuitovu | pobjedu u toj utrci više od svega.
{138604}{138650}On nam ne bi dao otkazati.
{138672}{138741}- Hvala vam, ljubazni ste. | - Nema na èemu.
{138775}{138832}"Ledeni" je došao. | Kakve li prièuve!
{138835}{138890}Poput uvoðenja Babea Rutha | kao prièuve.
{138893}{138954}Èelièni živci i led u žilama!
{138957}{139013}- Zašto, pa George Woolf je... | - Nevažan.
{139016}{139126}Mogu dovesti i èetiri jahaèa | Apokalipse, ne bi promijenilo stvar.
{139129}{139199}War Admiral je konj nenadmašna uzgoja.
{139202}{139264}Nema veze tko mu je putnik.
{139320}{139426}Lijeva mu je strana jaèa, Georgie. | U zavoju zanosi poput zrakoplova.
{139429}{139521}Možda æe trebati pomoæ pri promjeni | smjera, udalji ga od ograde u zavoju.
{139524}{139593}- Kao što si ti radio na "Gold Cupu". | - Toèno.
{139596}{139660}Treba mu dobro zagrijavanje, | poèni vrlo polako.
{139663}{139727}Kad želiš nešto od njega, bez bièa.
{139729}{139783}Samo pucni dva puta, | neka zna da imaš biè.
{139786}{139864}- Znat æe kad mora raspaliti. | - Tako je.
{139867}{139981}I nikad s lijeve strane.
{139984}{140057}Udarili su ga s lijeve strane | kad je bio mali.
{140060}{140138}- Volio bih da ga ti jašeš. | - Pusti to.
{140161}{140213}Bit æu i ja tamo s tobom.
{140419}{140468}Odlièno.
{140471}{140610}Pokaži mu biè kod oznake za zadnjih | 400 metara i pojurit æe kao vjetar.
{140764}{140898}Pritisni ga na lijevu stranu malo | ranije i dobit æeš još više od njega.
{140975}{141026}Odlièno.
{141029}{141074}Zatvori vrata.
{141461}{141585}OK, znaš da Smith želi da se izborite | za vodstvo do kraja prvog kruga?
{141588}{141666}Znam. Radimo sa zvonom.
{141669}{141745}- To mi nekako izaziva nelagodu. | - To je sve u redu.
{141748}{141814}Ali morate prepustiti | vodstvo na najdužem dijelu.
{141816}{141921}- Prepustiti? | - Prepustiti Admiralu.
{141924}{141974}Neka se Biscuit bori.
{141977}{142115}Ako ga dovedeš u ravninu | s drugim konjem i on ga pogleda u oko,
{142118}{142186}nema teorije po kojoj bi bio poražen.
{142188}{142264}Samo ga suspreži | tijekom zadnjeg zaokreta
{142267}{142395}i pusti ga neka si dobro pogleda | Admirala, a onda ga pusti.
{142398}{142488}To nije pitanje nogu, Georgie,
{142512}{142550}to je pitanje ovoga.
{142650}{142674}1. STUDENOGA 1938.
{142677}{142788}U 10 ujutro je najbliži parking | bio 15 blokova odavde.
{142791}{142873}Kolièina osvježavajuæih napitaka | i ponude je za pasti u nesvijest.
{142876}{143075}17000 galona limunade; | 60000 hot-dogova, 2000 baèava piva.
{143078}{143122}NBC prenosi utrku,
{143125}{143192}a danas se radi samo | pola radnog vremena,
{143195}{143253}tako da se može pratiti prijenos,
{143256}{143358}a zahvaljujuæi juèerašnjoj zamolbi | g. Howarda poslodavcima.
{143361}{143469}Znam da je ovo otmjeno trkalište, | ali bi morali otvoriti unutrašnji dio,
{143472}{143543}tako da i obièni ljudi mogu doæi.
{143546}{143612}Ne morate biti bogati | za uživati u ovome.
{143637}{143714}Seabiscuit u trku ulazi s izgledima | 2 naprama 1 protiv njega,
{143717}{143828}ali to nikad ne bi znali, sudeæi | po jaèanju buke u središnjem dijelu.
{143831}{143955}Do završetka æe više od 40 milijuna | Amerikanaca slušati prijenos.
{143967}{144146}OK, malo je blatnjavo kod ograde, | drži ga dalje odande.
{144149}{144235}Ima i osušena brazda od traktorskog | kotaèa metar i pol od štitnika.
{144238}{144310}Prošao sam jutros stazom.
{144313}{144365}Dobro.
{144368}{144514}E, mora zapoèeti oštro, | kako smo i uvježbavali,
{144517}{144591}ali ima i još nešto.
{144613}{144712}Što? Neka pustim | da me stignu na najduljem dijelu?
{144714}{144785}Nisi ti jedini koji poznaje ovog konja.
{144870}{144914}Sretno, George.
{144917}{144986}I neka bude kratko. Idemo, Same.
{145114}{145163}- Sretno, George. | - Hvala, Nick.
{145241}{145295}Dva se jockeya pozdravljaju.
{145298}{145373}Vrlo kratak pozdrav, | poput bokserskog dodira rukavica.
{145376}{145432}Hajde, nije vrijeme za æaskanje.
{145435}{145480}Oba su konja na stazi,
{145483}{145543}a možete èuti | i buku iz gledateljstva.
{146123}{146167}Evo ga!
{146495}{146549}VLASNIŠTVO VATROGASNE | POSTROJBE BALTIMOREA
{147768}{147845}Seabiscuit vodi za dužinu njuške. | Sad veæ glave!
{147848}{147962}Bio je ispred War Admirala, | nametnuo pritisak i zatim poletio.
{147965}{148078}Jure prema okretištu. | Koji æe biti prvi?
{148081}{148178}Seabiscuit dolazi prvi do okretišta | i ide prema najdužemu dijelu!
{148406}{148499}Seabiscuit vodi za dvije dužine tijela.
{148502}{148571}Seabiscuit s dvije dužine. | War Admiral zaostaje.
{148574}{148648}Seabiscuit s dvije dužine. | Dvije i pol.
{148908}{148974}Sad ga uspori, sinko.
{149044}{149112}Uspori ga. Hajde.
{149114}{149203}Dolaze najdužim dijelom! | Seabiscuit vodi.
{149206}{149265}Hajde, ne zafrkavaj se.
{149314}{149446}Nadamo se da si u pravu, Rede. | Sad æemo. Polako.
{149590}{149639}Prokleto bilo.
{149880}{149960}Evo War Admirala! | To je War Admiral!
{149963}{150072}Potpuno su poravnati | pri ulasku na ravni dio.
{150225}{150305}Drži se uz njega. Polako.
{150334}{150402}To je to. Hajde sad.
{150487}{150553}Približavaju se okretištu, | Seabiscuit je u vodstvu.
{150556}{150616}Ne, War Admiral. | Ne, Seabiscuit.
{150619}{150663}Još samo malo.
{150699}{150745}Vodi Seabiscuit. Ne, War Admiral.
{150748}{150851}Konji su potpuno poravnati | pri ulasku u zavoj!
{151044}{151078}Sad.
{151092}{151130}Sad. Hajde, George.
{151133}{151176}Oslobodi ga.
{151179}{151228}Sad to uèini.
{151264}{151313}Zbogom.
{151378}{151485}- Oslobodi ga! | - Dolazi Seabiscuit!
{151591}{151666}Seabiscuit vodi za dužinu tijela. | Za dužinu i pol.
{151669}{151735}War Admiral posustaje. | Seabiscuit vodi za dvije dužine.
{151738}{151806}- Hajde. | - Seabiscuit, dvije i pol dužine.
{151809}{151892}Sad uistinu odmièe! | War Admiral posustaje!
{152142}{152186}To!
{153734}{153784}- Hvala. | - Èestitam.
{153787}{153853}- Zadivljujuæe. | - Èestitam. Hvala.
{153856}{153922}Ledeni, uspio si. Kakav je to osjeæaj?
{153925}{154003}Htio bih da je moj prijatelj | Red Pollard danas na mome mjestu.
{154006}{154050}Bit æe.
{154142}{154249}Ovime završavamo prijenos | utrke stoljeæa.
{154252}{154331}A sad poruka moga sponzora, | "American Oil Company".
{154334}{154415}Nema boljeg goriva od "Amoco" goriva.
{154848}{154897}Polako.
{154943}{154992}Pazite na kotaè.
{156259}{156353}Pozdravite slavnoga junaka. | Vratio nam se "Mali div".
{156355}{156449}Nema više dvoboja za tog ponija, | nitko mu nije dorastao.
{156451}{156542}S kim bi se utrkivao? S Pegazom? | Žao mi je tih drugih konja.
{159310}{159351}Kad æe znati što mu je?
{159353}{159506}Ne znam. Možda za jedan sat. Nisam | sigurna. Charles je s veterinarom.
{159508}{159576}Boli li ga pri savijanju? | Ako ne...
{159578}{159673}Još ništa ne znamo. | Èim budemo znali, nazvat æu te.
{159675}{159726}Dobro.
{159913}{159963}Mora biti sve u redu.
{160048}{160088}G. Howarde.
{160282}{160351}Puknuo mu je ligament.
{160353}{160415}Stavio sam mu udlagu | kako bih nogu imobilizirao,
{160417}{160483}ali je sad posvema šepav.
{160531}{160591}Nikad se više neæe utrkivati.
{160766}{160880}Znam da je to teško, | ali æu ga uspavati ako želite.
{161757}{161824}U redu je, Djedice. Dolazim k tebi.
{162816}{162851}OŽUJAK
{162853}{162944}Prvo moraš vratiti malo elastiènosti.
{162958}{163009}Onda možeš opteretiti koljeno.
{163011}{163114}Kad poèneš koljeno optereæivati, | cijela noga postaje jaèa.
{163116}{163198}Znam. I meni se žuri s oporavkom.
{163200}{163273}Ali, znaš što je Hadrijan | rekao za gradnju Rima.
{163275}{163389}"Opeku po opeku, graðani moji. | Opeku po opeku".
{163418}{163581}Vidiš, oni su Arapi, | ne trebaju piti.
{163583}{163739}Ti konji mogu pet do šest dana | živjeti bez kapi vode.
{163741}{163802}Poput deve.
{163804}{163887}Ne kažem da bi i ti trebao tako.
{163889}{163950}Samo kažem da su oni takvi.
{164033}{164094}Dobra zamisao.
{164096}{164146}Odmori se malo.
{165055}{165171}- Ne znam baš, Rede. | - Samo æemo hodati u krugu.
{165173}{165227}Hoæe li noga izdržati?
{165229}{165308}Konj teži 600 kilograma. | Neæe me ni osjetiti.
{165310}{165359}Mislio sam na tvoju nogu.
{165521}{165604}Evo Seabiscuita u jurišu stazom,
{165606}{165677}pretjeèe suparnike jednog po jednog.
{165679}{165743}Treæi je. Sad veæ drugi.
{165745}{165783}Prvi.
{165785}{165901}Seabiscuit prolazi kroz cilj | i osvaja kup Santa Anite
{165903}{165964}s Redom Pollardom na leðima. To!
{166448}{166488}Što?
{166606}{166701}LISTOPAD
{166923}{166965}Polako.
{167182}{167242}Bolje ti je, je li tako, momèe?
{167376}{167448}Sve je u redu, samo moram | malo jaèe pokositi travu.
{167450}{167500}Nemam ništa protiv.
{167772}{167837}Tako valja. Dobro.
{168031}{168093}Odlièno izgleda. | I ti odlièno izgledaš.
{169128}{169175}- Je li to moguæe? | - Naravno.
{169177}{169226}Veæina ljudi misli da je to nemoguæe.
{169228}{169280}Veæina bi ga ljudi dala...
{169310}{169435}Najbolje ga je pustiti na stazu | i neka malo galopira.
{169437}{169483}Tako æemo jedino doznati.
{169485}{169549}- Može li on to? | - Naravno.
{169551}{169596}Mislim, vjerujem da može.
{170129}{170186}Bio je odlièan. | Ništa nisam primijetio.
{170188}{170284}A zašto ga ne bismo pustili | normalno trenirati u petak ujutro?
{170286}{170342}Tisuæu metara, | da vidimo kako stvari stoje.
{170344}{170399}Jasno. Bit æu tamo.
{170401}{170452}Hvala.
{170501}{170551}Dobro se oporavlja.
{170585}{170677}- Može li biti spreman? | - Za što?
{170679}{170734}Ma, daj. Znaš za što.
{170920}{170972}Dobro vam jutro želim.
{170974}{171043}Lijepi ždrijebac. Tko je to?
{171045}{171120}Dvogodišnjak. Još nije za trke.
{171122}{171205}Mislio sam da ga pripremate | za trku od sto tisuæa.
{171207}{171257}Samo su mu dvije godine.
{171309}{171350}Klin se klinom izbija.
{171401}{171469}- Dugo ste veæ ovdje? | - Tek sam došao.
{171471}{171533}Pripremam se za vijesti.
{171535}{171610}- Siguran sam da se vidimo uskoro. | - Dogovoreno.
{171738}{171783}Zaustavite strojeve!
{171785}{171895}Ovo nije vijest u zadnji trenutak, | ovo su tri vijesti u jednoj.
{171897}{171997}I pripremite koji apaurin, | taj me mali konj izluðuje.
{172022}{172125}Pogodite tko uskoro pokušava trèati | 1000 metara i ide na Kup "Santa Anite".
{172127}{172172}Svih mi svetaca, pogodili ste.
{172174}{172264}Ljudi, ljudi, pa jeste li pogodili.
{172623}{172722}Za minutu i 12 ili 13, tako nešto.
{172724}{172787}Poène li biti prebrz, | uspori ga.
{172789}{172841}Pokušaj vidjeti kako mu je i...
{173166}{173235}U redu je. Sve je u redu.
{173237}{173287}Doði. U redu je.
{173552}{173653}"I ovaj, najgori udarac od sviju".
{173774}{173831}- Možemo li razgovarati? | - Razgovarajmo.
{173833}{173902}Ne možeš to uèiniti. | Možeš ostati doživotno invalidan.
{173904}{173958}Veæ sam bio doživotno invalidan.
{173960}{174038}Oporavio sam se. On mi je pomogao.
{174040}{174090}Vraga, vi ste mi pomogli.
{174162}{174207}Isuse Kriste.
{174291}{174366}Taj je konj isto toliko | moj, koliko i vaš.
{174623}{174673}Prokleto bilo.
{174689}{174759}- Ovisi o njemu. | - Ali on kaže da ne mogu jahati...
{174761}{174827}On je lijeènik. O njemu ovisi.
{174901}{174951}Vi ste ovo napravili?
{174981}{175053}Omota se oko jahaæe èizme.
{175055}{175116}Ojaèa ju sve do lista.
{175118}{175193}Ništa ne osjeæam kad zajašem.
{175344}{175453}Èujte, može se rasprsnuti svakog | trenutka, èak i sad. Zaboravite trke.
{175455}{175522}Vidite li ovo? Jedva da je zacijelilo.
{175524}{175636}Ne možemo znati koliko optereæenje | uopæe može podnijeti.
{175638}{175759}Ako se ponovno ozlijedi, | vjerojatno više nikad neæe hodati.
{175775}{175845}"Vjerojatno". | Upravo je rekao "vjerojatno".
{175847}{175927}Sve je moguæe. | To smo veæ dokazali, jesmo li?
{175929}{176015}- Ovo je druga stvar. | - O, da. Uistinu druga.
{176102}{176218}Ne radi se o bilo kakvoj utrci, | u pitanju je Santa Anita.
{176220}{176327}- Skoro sam pobijedio, bio sam tamo. | - Znam.
{176859}{176961}Èak i s pojaèanjem, | teško da æe noga izdržati
{176963}{177024}ako ga udare ili gurnu.
{177026}{177089}- Želite li znati što ja mislim? | - Naravno.
{177091}{177171}Bolje je èovjeku | slomiti nogu nego srce.
{177240}{177315}Nije to samo noga. Nije!
{177317}{177369}Može pasti, može biti pregažen.
{177371}{177451}- Ako padne s konja... | - Mogao bi poginuti?
{177750}{177815}I ja se igram s time cijelo vrijeme.
{177892}{178031}Kako god se trudila, prokletu | kuglicu ne mogu zadržati u rupi.
{178033}{178093}Uvijek ispadne iz nje.
{178276}{178326}Pusti ga jahati, Charlese.
{178370}{178420}Pusti ga.
{178597}{178676}Mogu shvatiti jedan povratak, | ali ovo je smiješno.
{178678}{178774}Tko je sljedeæi, Lazare? | Aha, junaštvo, ludilo, uzbuðenje!
{178776}{178841}Najveæi broj ljudi na trkama | u povijesti Santa Anite.
{178843}{178976}55000 na sjedeæim mjestima. 20000 | u središnjem dijelu. A tek je podne.
{179423}{179473}Nije loše.
{179519}{179585}Sveti Kristofor za sreæu.
{179609}{179668}Malo je kasno za to, nije li?
{179845}{179915}Hajde, dobijmo utrku.
{180011}{180071}Program utrka | možete dobiti ovdje.
{180298}{180348}- Spreman? | - Jesam.
{180728}{180786}Whichee je najbrži.
{180788}{180889}Izbit æe na èelo, | ali sumnjam da æe izdržati.
{180891}{181017}- Budi mu za petama, kao uvijek. | - Jasno.
{181019}{181085}Wedding Call može potegnuti na kraju.
{181087}{181160}On isto ima petlju, pazi i na njega.
{181162}{181210}Neæu ponoviti istu pogrešku.
{181323}{181397}Opustite se, deèki. Bit æe sve dobro.
{182091}{182155}Nadam se. Bog vas blagoslovio.
{182420}{182510}- Sretno. Dobro izgledaš. | - Nemoj me ureæi.
{182573}{182662}Smiri se. Jesi li za piæe?
{182689}{182746}Dobra zamisao.
{182748}{182798}Na koga se kladiš?
{183894}{183950}Hej, stara kuæo.
{183952}{184017}- Što ti radiš ovdje? | - Jašem drugog konja.
{184019}{184101}Ako ne jašem njega, | ne znaèi da æu sjediti i gledati.
{184103}{184184}Ne brini se. Nemam nikakvih izgleda.
{184186}{184246}Vidimo se na cilju.
{186132}{186170}Brže, momèe!
{186200}{186235}Brže!
{186915}{186980}- Kako si, Rede? | - Georgie.
{186982}{187032}Jeste li dobro vas dvojica?
{187114}{187164}Sad, momèe.
{187215}{187282}- To je to. | - Svako dobro.
{187349}{187394}Hajde, Djedice.
{187498}{187543}Sad ga ubrzaj.
{187798}{187845}Hajde, Rede!
{188075}{188120}Evo prolaza.
{188124}{188173}Naprijed, Biscuite!
{188995}{189124}Svi misle da smo našli | ovog pokvarenog konja i popravili ga,
{189126}{189176}ali nismo.
{189227}{189277}On je popravio nas.
{189310}{189363}Svakoga od nas.
{189403}{189453}I, rekao bih, na neki naèin,
{189492}{189557}popravili smo i jedni druge.
{189560}{189930}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan  
