{1}{1}25.000
{346}{411}U glavnim ulogama:
{1636}{1808} SHERLOCK HOLMES | UBOJSTVO U VISOKOM DRUŠTVU 
{3775}{3902}Obdukciju vrši dr. D. Dunwoody, kirurg | Gradske policije, Odsjek centra.
{3941}{4058}Žena. Oko 20 godina. - Nije li mlaða?
{4108}{4172}Dr. Watson. - Lestrade.
{4183}{4307}Dr. Watson je kirurg ovdje u bolnici. | - Jako dobro znam tko je dr. Watson.
{4327}{4444}Visoka èarapa, svezana oko vrata. | - Radije prerežite sa strane.
{4466}{4524}Da ne oštetite èvor.
{4529}{4624}Stara Holmesova dosjetka. | Èvor može reæi mnogo toga.
{4666}{4864}Kratki crni sako. Jeftino krzno | oko vrata. Crna svilena suknja.
{4888}{4985}Otrcano rublje. | Izgled tipièan za prostitutke.
{5000}{5072}Tijelo u dobrom stanju.
{5100}{5222}Modrice oko vrata. Tragovi, èini se, | poveza oko ruku i koljena.
{5227}{5269}Èini se da je bila stegnuta.
{5274}{5380}Vjerojatno je seksualna igra | izmaknula kontroli. - Jadno dijete.
{6846}{6957}Dobro jutro, Watsone. | - Kako znate da sam ja, Holmese?
{6964}{7057}Ne pušim duhan s aromom. | Ne nosim miris.
{7061}{7174}Zaudarate na klaonicu. | Nosite miris mrtvaènice.
{7389}{7449}Molim zeleni èaj, Chang. | Samo jednu šalicu.
{7454}{7491}Gospodin æe ubrzo otiæi.
{7622}{7705}Èini se da vam godi život | daleko od Ulice Baker.
{7710}{7782}Vidim da ste 3.5 kg teži | nego kad smo se zadnji put sreli.
{7785}{7907}Toèno 3 kg. | - Doista? Rekao bih da je malko više.
{7979}{8060}Molim vas šalicu èaja. - Ne slušaj ga.
{8124}{8246}Zašto me slijedite, Watsone? | - Zbog jednoga sluèaja.
{8250}{8369}Djevojka od nekih 16, 17 godina. | Pronaðena na obali Temze
{8374}{8454}kod Shadwella. Oko vrata joj je bila | svezana svilena èarapa.
{8458}{8530}Ako tražite senzacionalistièki sadržaj | za svoje kriminalistièke kronike,
{8535}{8618}vratite se svojoj uhodanoj metodi | izmišljanja.
{8657}{8724}Ne tražim sadržaj. | Nastojim spasiti dragoga prijatelja
{8729}{8794}od smrti zbog narkotika i dosade.
{8804}{8888}Dirljivo. - Obeæali ste.
{8893}{8983}Obeæanja su poput zakona. | Tu su da bi ih se kršilo.
{9036}{9089}Doðite do Londonske bolnice. | Pogledajte tu djevojku.
{9094}{9163}Pozdravite zaruènicu.
{10424}{10486}Gðo Hudson!
{10549}{10649}Gðo Hudson! - Ovo vam je stiglo | u zadnja 3 dana.
{10736}{10805}Ne, ne, ne, ne, ne.
{10902}{11011}Gðo Hudson, jeste li pospremali? | - Vrlo malo.
{11029}{11089}Ali gdje...
{11274}{11350}Kada æete objedovati? - Molim?
{11355}{11435}Kada æete objedovati? - U 19.30h.
{11510}{11555}Prekosutra.
{12225}{12457}Otete u cvijetu ljepote, | ne vidjevši grobne tegote
{12649}{12724}Po drugi ste put pogodili | gdje sam, Watsone.
{12807}{12849}Tako sam predvidljiv?
{12854}{12916}Možda sam napokon nauèio | primjenjivati vaše metode.
{12919}{12989}Imate li izvješæe s obdukcije? - Imam.
{13025}{13089}Što su joj pronašli u želucu?
{13102}{13271}Gutljaj vinjaka i napola probavljenu | belgijsku èokoladu.
{13293}{13397}Znakovi snošaja? | - Naprotiv, bila je djevica.
{13411}{13488}Toliko o pretpostavci policijskoga | kirurga da se radilo o prostitutki.
{13493}{13572}Bar je netko imao dovoljno | zdravoga razuma da saèuva èvor.
{13577}{13707}Watsone, ovo nije njezina odjeæa, | osim možda èarape. - Doista?
{13710}{13838}Ona nije iz radnièke klase. Nokti su | oèuvani, ruke nježne. Zubi su snažni.
{14099}{14143}Holmese?
{14335}{14379}Bože.
{14477}{14518}Nazovite Scotland Yard. | Recite Lestradeu
{14522}{14632}da je žrtva lady Alice Pentney. | - Molim?
{14685}{14757}Kæi vojvode i vojvotkinje | od Narborougha.
{14766}{14804}...ljubavnik!
{14913}{14960}Poènimo.
{15261}{15369}Roberta, privremeno æeš zamijeniti | moju kæer. - Da, Vaša Milosti.
{15475}{15530}Na mjesta.
{16227}{16272}Dosta toga.
{16283}{16380}Ne zaboravite da æete ovo odigrati | u prisustvu kralja.
{16402}{16489}Pokušajmo ponovno. | - Ovo se ne drži kako treba.
{16691}{16743}Odmah se vraæam.
{16858}{16985}Vaša Milosti, gdje je Lady Alice? | - Nisam sigurna. Da budem iskrena,
{16988}{17039}nedavno smo se porjeèkale | oko neke sitnice
{17044}{17127}i sad me kažnjava | tako što nije došla na probu.
{17144}{17213}Što se dogaða, inspektore?
{17224}{17341}Moram vas zamoliti da poðete sa mnom | vidjeti leš jedne djevojke. - Molim?
{17371}{17482}Djevojke koja odgovara | opisu vaše kæeri. - Nije moguæe.
{17718}{17829}Roberta, ne brini se. | Sigurno nije ništa.
{17972}{18046}Došla je vojvotkinja od Narborougha.
{18539}{18602}To nije ona.
{18664}{18746}Jeste li sigurni? | - U pravo sam vam rekla. To nije ona.
{18780}{18849}Oprostite... - Tko ste vi?
{18869}{18963}Sherlock Holmes. - Èula sam za vas.
{19033}{19121}Pogledajte ponovno, Vaša Milosti.
{19385}{19472}Je li to Lady Alice Pentney?
{19666}{19744}Bila je ovako odjevena? - Da.
{19749}{19847}To nije njezina odjeæa. | Zašto je tako odjevena? Bože.
{19914}{19985}Grozno...
{20300}{20422}Ušljiva kurvica je jedno. | Ovo je, Bože pomozi, sasvim drugo.
{20430}{20549}Drago mi je èuti da suosjeæate | s obitelji žrtve, Lestrade.
{21013}{21068}Gðo Hudson!
{21086}{21158}Mislim da se sjeæate našega gosta.
{21175}{21243}Dr. Watson! - Gðo Hudson.
{21247}{21325}Tako mi je drago da vas vidim. | U zadnje je vrijeme...
{21330}{21413}Ogovaranje je poèelo, | a da nisam stigao ni skinuti šešir!
{21427}{21538}Ta smiješna pantomima | nije nimalo bolja.
{21627}{21747}Uvijek ste bili jako neuredni, | ali ovo, Holmese...
{21754}{21799}Watsone, ovo je slobodna zemlja.
{21804}{21891}Ljudi mi imaju pravo slati pisma, | a ja ih imam pravo ne otvarati.
{21896}{22010}Dakle, vojvoda od Narborougha. | Evo ga, Watsone.
{22014}{22199}George de Vere Pentney, K. G., P. C., | A. R. A, pa to je cijela abeceda.
{22219}{22269}Natoèite nam vinjak, | molim vas, Watsone.
{22274}{22333}Dosta je vinjaka usred | bijela dana, Holmese.
{22338}{22443}6. vojvoda. Završio Eton | i Trinity College Cambridge.
{22449}{22516}Sjedište mu je Dvorac Narborough | u Hampshireu.
{22519}{22614}Posjeduje pola Argyllshirea. | Itd., itd., itd.
{22622}{22722}Tijelo je poput plamena. | Ugasit æe se ako nestane goriva.
{22738}{22819}Dojmljivo, Watsone. | - Morate jesti Holmese.
{22824}{22877}Tijelo svakoga dana mora | sagorjeti dovoljno hrane.
{22882}{22969}Sreæom, svako pravilo poznaje | iznimke. - Onda dobro.
{23085}{23282}Doruèak. Porcija slanine. Jedno jaje. | 100 grama... - Dakle, Watsone!
{23404}{23493}Ne trošite dah, | kako æete si ohladiti kašu?
{23780}{23819}Halo.
{23858}{23914}Bojim se da...
{23993}{24066}U tom sluèaju, bit æe mi zadovoljstvo.
{24096}{24186}Osam, pola devet. Izvrsno. Doviðenja.
{24204}{24297}Èini se da niste jedini | koji se brine o mojoj prehrani. - Kako?
{24316}{24354}Da?
{24399}{24477}Došao je vojvoda od Narborougha. | - Aha!
{24480}{24560}Èini se da sam ga sam prizvao! | Pošaljite nam ga, gðo Hudson.
{24564}{24630}Možda bolje da odem. - Ni sluèajno. | Ostanite gdje jeste.
{24636}{24704}Hajde, stari moj, | bit æe to kao u dobra stara vremena.
{24819}{24913}Dobar dan, Vaša Milosti. | Sjednite, molim vas.
{24991}{25072}Ovo je moj prijatelj i kolega, | dr. Watson.
{25079}{25127}Lord Blakemore mi je rekao | da se smijem pouzdati
{25132}{25261}u vaš sud i vašu povjerljivost. | Zbog toga sam vam se odluèio obratiti
{25266}{25357}u vezi s jednim vrlo bolnim, | nedavnim dogaðajem.
{25361}{25416}Znam za vaš gubitak, Milosti.
{25421}{25546}Želim da naðete ubojicu moje kæeri, | g. Holmes. Bogato æu vas nagraditi.
{25558}{25647}Cijena moje usluge je uvijek ista, | Vaša Milosti.
{25652}{25754}Ne mijenjam je, | osim kada je smanjim na ništicu.
{25825}{25905}Imam li odriješene ruke | za rad na ovome sluèaju?
{25910}{25985}U okviru pristojnosti i dobroga ukusa.
{25997}{26104}Kako æemo biti u vezi? | - Možete me naæi u mojemu klubu.
{26188}{26254}Doviðenja, gospodo.
{26321}{26399}Pravi... gospodin.
{26441}{26538}I Jack bi bio gospodin, Watsone, | kad bi znao francuski.
{26552}{26685}Vidimo se na veèeri. | - Bojim se da ne mogu, Holmese.
{26689}{26814}Veèeram sa zaruènicom. | - I ja Watsone. Osam, pola devet.
{27577}{27616}Ne vidim zašto je ovo nužno.
{27621}{27697}Insp. Lestrade samo radi | svoj posao, Vaša Milosti.
{27702}{27789}Ali Lestrade, bilo bi bolje | pozivati èlanove posluge pojedinaèno.
{27799}{27871}Najprije niže sluge, | kako bi se izbjegao metež.
{27875}{27946}Hvala, g. Holmes. | - Smijem li vidjeti sobu lady Alice?
{27950}{28008}Naravno. - Hvala.
{28399}{28464}Zaboga, Lestrade! | Zašto policajci u èizmama
{28469}{28591}gaze svuda poput krda bizona?! | - Idemo. Svi van.
{28594}{28679}Ostavi to gdje je bilo. Hajde.
{29796}{29879}Tu, Lestrade... I tu.
{29932}{30002}Neka potraže otiske prstiju | na ovoj boci.
{30007}{30082}Neka saèuvaju malo vinjaka za analizu.
{30096}{30235}Egipatska božanstva. | S najaromatiènijim turskim duhanom.
{30304}{30493}Dva su pušena u cigaršpicu. | Dva su ugašena pod muškom cipelom.
{30558}{30672}Nije se odupirala. Pod noktima joj | nije bilo kože ili kose.
{30685}{30749}Nije bilo znakova borbe.
{30786}{30899}Pažljivo, Holmese, molim vas! | - Možda joj je dao belgijske èokolade.
{30943}{31029}Kada je zadnji put noæ bila vedra? | - U nedjelju.
{31072}{31139}Sigurno joj je bilo hladno.
{31327}{31410}Ali imala je to na sebi.
{31430}{31544}Postoji li ovdje stubište | u sluèaju opasnosti? - Ondje je.
{31552}{31674}Sigurno se dobro snalazio. | Pažljivo pretražite naselje Mews.
{31679}{31729}I svima uzmite otiske prstiju. - Svima?
{31733}{31796}Bez iznimke.
{31924}{32072}Posljednja zvjezdana noæ prije nego | što se spustila paklena magla.
{32122}{32239}Boca l'Espirit de Courvoisiera. | - Iz podruma Njegove Milosti.
{32244}{32346}Odnesena je Njegovoj Milosti | u nedjelju nakon 23 h.
{32352}{32424}Tako. - Zvali ste me, g. Bates?
{32429}{32491}Da, Florence. | - Florence, èiji je ovo kaput?
{32550}{32638}Vojvotkinjin. - Sigurno?
{32652}{32693}Da.
{32710}{32757}Hvala.
{32991}{33072}Nadam se da æe se ovo dati oprati.
{33110}{33166}Sve je to užasno.
{33216}{33319}Je li vaša kæi bila jako nesretna? | - To nije bitno, g. Holmes.
{33338}{33411}Naprotiv, Vaša Milosti, | to je iznimno bitno.
{33449}{33529}Što ste mislili, gdje je Lady Alice | bila u nedjelju naveèer?
{33558}{33682}Nismo znali. Veæ je jednom ili dvaput | samo otišla. - Bez pratnje?
{33739}{33827}Kada ste te veèeri otišli | iz svoje biblioteke, Vaša Milosti?
{33832}{33900}Mislim da sam oko ponoæi | otišao spavati.
{33905}{33960}Nedugo nakon toga, | rano ujutro u ponedjeljak,
{33964}{34058}Lady Alice je oteta s krova. - S krova?
{34063}{34174}Pred njezinom sobom. Ondje je sjedila | umotana u majèin krzneni kaput,
{34179}{34266}pušila oèeve cigarete | i pila oèev vinjak.
{34271}{34355}Netko ju je spustio požarnim stubama | i odnio kroz Mews.
{34363}{34466}Zaboga! | - Mislim da je poznavala ubojicu.
{35379}{35430}Holmese, dragi prijatelju.
{35435}{35519}Je li vaša netipièna neformalnost | amerièkoga podrijetla, Watsone?
{35524}{35649}Sherlock. - Gðo Vandeleur.
{35660}{35714}Jenny. Molim vas, zovite me Jenny.
{35719}{35783}Johne, molim te, | uzmi Sherlockov kaput.
{35860}{35935}Da vam spravim piæe. | Izgledate mi kao èovjek za viski.
{35939}{35982}Viski sa sodom? Jesam pogodila?
{35986}{36047}To bi bilo... - I pridružit æu vam se.
{36083}{36130}John i ja smo se upoznali | na konferenciji u Zurichu.
{36135}{36172}Išao sam se skijati.
{36177}{36252}Ja sam diplomirana psihoanalitièarka. | Ali to sigurno veæ znate.
{36257}{36336}Ne znam. - Kako vas dvojica možete biti | tako bliski prijatelji,
{36341}{36411}a da ne razgovarate o tako bitnim | osobama kao što su zaruènice?
{36438}{36505}Mene te stvari ne zanimaju.
{36516}{36616}Koliko znam, Sherlock, vama se žene | ne sviðaju, niti im vjerujete.
{36621}{36718}Brzo, daj još vina. | - Žene su jedno od nužnih zala.
{36758}{36824}Pretpostavljam da nikad | niste bili zaljubljeni.
{36829}{36904}Moj je um uvijek bio nadreðen | mojemu srcu.
{36936}{37018}Biste li se podvrgli psihoanalizi?
{37047}{37118}Bili biste zadivljujuæ sluèaj.
{37288}{37349}Zapadna Afrika? - Da.
{37383}{37485}Iznimno ružno. | - Putujete li èesto, Sherlock?
{37507}{37582}Oduvijek smatram da putovanja | sužavaju svjetonazore.
{37586}{37638}Osim toga, za državu je najbolje | da je ne napuštam.
{37643}{37744}Inaèe se kriminalni stalež | uzbudi više nego što bi bilo zdravo.
{37805}{37910}Znate, palo mi je na pamet | da bi odjeæa lady Alice
{37914}{38054}za njezina ubojicu mogla imati | neko posebno znaèenje. - Nastavite.
{38069}{38168}Èini se da ju je zadržao. | - Kako bi je nosio?
{38172}{38261}Možda. - Možda se radi o fetišistu.
{38297}{38400}Jeste li èitali Psychopathiu sexualis | Richarda von Krafft-Ebinga?
{38407}{38525}Ne pomnjivo. - Neki su autorovi | etièki pogledi zastarjeli,
{38530}{38622}ali obraðeni su sluèajevi dojmljivi. | Moram vam reæi da ga ne smije zaobiæi
{38627}{38713}nitko tko se zanima za seksualne | poremeæaje. - Hvala.
{38716}{38777}Možete je zadržati. | - Jako ste ljubazni.
{38782}{38899}Obraðuje divan niz perverzija: | Sadomazohizam, bestijalnost,
{38904}{39021}egzibicionizam, transvestizam, | koprofiliju... - Odem na 10 minuta...
{39025}{39119}Homoseksualnost, nekrofiliju, | silovanje, muèenje.
{39124}{39204}I evo što se dogodi. | - Ubojstvo iz požude, i ima toga još.
{39208}{39275}Vjerujem da ima. Holmese?
{39280}{39338}Jaku i crnu, molim vas, Watsone.
{39375}{39419}Odmah.
{39664}{39761}Kad je djevojka nestala? - Nakon 21 h. | Trebala su nam 2 sata da vas naðemo.
{39891}{39955}G. Holmes, ovo je lord Massingham.
{39972}{40019}Moj kolega, dr. Watson.
{40025}{40141}Nestala je lordova kæi lady Georgina. | Otišla je u sobu malo prije 21 h.
{40146}{40294}Ovo joj je prva godina, g. Holmes. | Uvježbava predstavu za kralja.
{40302}{40416}Bila je umorna i jako uznemirana, | jadnica, zbog male Pentneyjeve.
{40421}{40524}Otišla je u sobu. Moja žena je otišla | gore nekih 10 minuta kasnije.
{40529}{40604}Vrata su bila zakljuèana iznutra | i Georgina se nije javljala.
{40608}{40655}Što ste uèinili? - Silom smo ušli.
{40661}{40702}Nikoga nije bilo u sobi?
{40707}{40772}Gdje je sada lady Massingham? | - Legla je...
{40777}{40893}Je li bio lijeènik? - Jest. | Naš lijeènik. Pod sedativima je.
{40914}{40989}Ovo je lady Roberta, starija sestra | lady Georgine.
{40996}{41075}G. Holmes i dr. Watson | pomažu policiji pri istrazi.
{41308}{41399}Morate je pronaæi, g. Holmes.
{41404}{41494}Morate je pronaæi zbog svih nas.
{41518}{41607}Mogu li sada vidjeti sobu? - Naravno.
{41814}{41877}Ostavite me nakratko samog.
{42697}{42769}Svi kažu da je lord Massingham | iznimno blizak kralju.
{42774}{42866}Polako, Lestrade. | Usredotoèimo se na ovdje i sada.
{42941}{42986}Holmese?
{43010}{43071}Holmese? Holmese?
{43235}{43313}Uvijek podignite pogled | kad ste na mjestu zloèina, gospodo.
{43780}{43933}Dakle? - Holmes... | Holmes je krenuo za jednim tragom.
{46041}{46124}Georgina? Georgina! Georgina.
{46235}{46324}Je li se vratila? Je li tu?
{46368}{46413}Hugo?
{46547}{46629}Bojim se da sam ustanovio | kako je lady Georgina oteta.
{46647}{46727}O, ne. O, ne, ne...
{46750}{46841}Moram je pronaæi. Molim vas, | preklinjem vas! Pronaðite je!
{47127}{47199}Savršeno vrijeme | za onoga èijem se srcu ubojstvo mili.
{47204}{47274}Nadajmo se da æemo je naæi | prije nego što se nešto dogodi.
{47279}{47363}Veæ je mrtva. - Molim?
{47371}{47433}Siguran sam u to.
{48160}{48313}Bože! Policija! U pomoæ! Ubojstvo!
{48508}{48630}Poznati opojni aromatièni miris. | - Kloroform.
{48636}{48724}Obje su djevojke uspavane. Lady Alice | sredstvom za spavanje u vinjaku.
{48729}{48858}Lady Georgina kloroformom. | Nijedna se, èini se, nije odupirala.
{48874}{48949}Mislite da se radi o istomu èovjeku? | - Nema sumnje.
{48954}{49019}Kako? Jednu su izvadili iz Temze, a | druga je visjela na rasvjetnom stupu.
{49025}{49144}Možda se promijenio naèin ubojstva, | ali zaštitni je znak ubojice isti.
{49149}{49254}U oba je sluèaja jedna èarapa u grlu, | druga zavezana oko vrata
{49258}{49394}karakteristiènim èvorom, a tu su i | tragovi vezanja: Ubojièina posjetnica.
{49399}{49522}Ovaj èovjek obilježava svoja djela | poput slikara koji potpisuje platno.
{50824}{50910}To je ona. To je Georgina.
{50918}{50989}Polako, polako.
{51082}{51144}Je li to odjeæa tvoje sestre?
{51294}{51329}Nije.
{51454}{51530}Ovo je jedini nepoznati otisak | s boce vinjaka.
{51582}{51663}Ubojièin? - Nema sumnje.
{51668}{51727}Rekao sam vam da æe | ostaviti trag, Lestrade.
{51732}{51768}Da?
{51791}{51904}Odjeæa koju je lady Georgina... | - Lady Georgina Massingham, da...?
{51921}{52058}Odjeæa koju je nosila... | - Pripada lady Alice Pentney.
{52113}{52191}To je odjeæa koju je lady Alice | nosila kad je oteta.
{52211}{52243}Tako je, gospodine.
{52247}{52355}Lestrade, savjetujem vam da pošaljete | sve raspoložive ljude u Belgraviju.
{52379}{52416}Zaboga!
{53124}{53233}Jeste li primijetili kako odjeæa lady | Alice pristaje lady Georgini? - Ne baš.
{53241}{53316}Gotovo savršeno. | - Ne vidim kako velièina odjeæe...
{53319}{53399}Možda je odabrana zato što je bila | iste visine i težine.
{53404}{53482}Ubojica ima oko, možda èak izvježbano, | za te pojedinosti.
{53486}{53625}Možda je radio za krojaèa. | Krojaèa lady Alice ili lady Georgine.
{53635}{53691}Saznajte tko im je šivao odjeæu. | Nabavite popis zaposlenika.
{53696}{53824}Sve æe buduæe žrtve biti istoga | fizièkoga tipa i iz istoga staleža.
{53829}{53919}Napravite popis mladih plemkinja koje | su istoga fizièkoga tipa. - U redu.
{53922}{54016}Htio bih pregledati odjeæu koju je | lady Alice nosila kad su je našli.
{54021}{54068}Biste li mi je poslali u Ulicu Baker?
{54072}{54141}Morat æete mi to potpisati. | - Samo tako nastavite, Lestrade.
{54177}{54383}Èini se da tražimo serijskoga ubojicu | koji je ubio lady Alice i Georginu.
{54471}{54624}Takvi se ubojice obièno okome | na lake mete. Prostitutke, djecu...
{54652}{54807}Ove su žrtve iz najviših slojeva. | O njima se vodi briga.
{54811}{54968}Imaju pratioce gdje god krenu. | Pa ipak, pod okriljem ove magle,
{54972}{55071}ubojica ih je oteo pred nosom | njihovih roditelja.
{55075}{55169}Ovo nije Trbosjek. | To nije sluðeni ubojica iz požude.
{55175}{55330}Šarmantan je, ugodna izgleda | i iznimno pažljivo bira žrtve.
{55335}{55477}Vrlo je snažan. Iznimno brz. | I odnosi žrtve kad ih se doèepa.
{55497}{55629}U svoj brlog. | Ondje provodi vrijeme s njima.
{55721}{55843}Skida ih, povezuje im ruke | i noge kod koljena.
{55852}{56035}Zatim skine jednu èarapu | i nagura je žrtvi u usta.
{56066}{56238}Vjerujem da zbog toga žrtva potmulo | vrišti, što uzbuðuje ubojicu.
{56285}{56377}Zatim skida drugu èarapu | i stavlja joj je oko vrata.
{56382}{56539}Možda je priteže drvenim štapom | poput podveza.
{56610}{56788}Nema tragova snošaja, ali pazite, | radi se o seksualnomu sadistu.
{56810}{56964}Za njega je strah, bol i poniženje | žrtve puteni užitak.
{57039}{57146}Napokon, odijeva žrtvu u odjeæu | prethodne žrtve,
{57150}{57219}koju je saèuvao samo radi toga.
{57222}{57396}Odjeæa i obredno presvlaèenje | simbolièki su nezamjenjivi za njega.
{57632}{57771}Eto. Još nemamo sumnjivaca.
{57800}{57883}Policija je, po obièaju, | potpuno zbunjena.
{57904}{58010}Bojim se da nisam sve rekao | našim prijateljima.
{58014}{58083}Tajenje informacija nije šala, | Holmese.
{58086}{58202}Svašta. Govorim koliko hoæu. | To je prednost slobodnoga strijelca.
{58208}{58318}Dakle, o èemu se radi? | - Georgina je imala Aliceinu odjeæu.
{58322}{58433}Alice je bila u otrcanoj odjeæi. | Logika kaže da postoji nepoznata,
{58438}{58538}skromnija, prva žrtva, kojoj je | pripadala ta skromnija odjeæa. - Da.
{58541}{58607}Ako otkrijemo tko je to, | još bolje, ako je naðemo,
{58613}{58764}bit æe nezamjenjiv izvor dokaza. | Prva žrtva uvijek najviše govori.
{58846}{58955}Ovo je satinet. | Tanja, jeftinija inaèica satena.
{58960}{59113}Ova je pomiješana s vunom. | Vjerujem da je proizvedena u Americi.
{59135}{59189}Ako ne griješim, iz njujorških...
{59213}{59313}Što je? - Ovdje je nešto, Holmese. | Pod prstima je poput kovanice.
{59330}{59422}To je uobièajeno skrovište | meðu sirotinjom.
{59429}{59527}6 penija? - Ne. 10 šilinga.
{59672}{59747}Nevjerojatno, Holmese. | - Osnove, dragi Watsone.
{59752}{59832}Razlika u težini je oèita.
{59889}{59946}Tu je još nešto.
{59979}{60044}Èini se da je priznanica.
{60116}{60232}Piše naziv tvrtke. W. G. Bilney. | - Bilneyjeva radnja?
{60236}{60308}Znate o èemu se radi? | - O obuæarskoj radnji na West Endu.
{60313}{60422}Morat æete ih posjetiti, Watsone. | Tražimo Amerikanku, do 20 godina,
{60427}{60518}pristala izgleda unatoè staležu, | finih manira.
{60522}{60679}Visoka je oko 170 cm, vitka, skladnih | proporcija, svijetle puti, tamne kose.
{60683}{60818}Ja imam i drugih obveza, Holmese. | Htio bih se i oženiti. - Znam, Watsone.
{60888}{60996}Možda æu naæi sat, dva. | - Nadam se da æe biti dovoljno.
{61493}{61543}G. Holmes. - Lady Roberta.
{61549}{61649}Oca mi trenutaèno nema. | Organizira sprovod.
{61655}{61743}Bih li mogao još jednom pogledati | Georgininu sobu? - Naravno.
{61827}{61930}Nemate fotografija svoje kæeri, | g. Vandeleur? - Nažalost, ne.
{61935}{62022}Sve sam izgubio u požaru | kod kuæe, u New Yorku.
{62027}{62177}Postoji jedna djevojka koja odgovara | vašemu opisu. Bila je Amerikanka.
{62182}{62274}Nemojte me zezati. | - Ali zvala se Sarah O'Brien.
{62279}{62358}O'Brien je bilo djevojaèko prezime | njezine majke.
{62371}{62432}Ovo je doista nezgodno.
{62463}{62539}Ta je djevojka došla u Englesku | kao osobna sluškinja
{62544}{62641}amerièke nasljednice koja se zaruèila | za engleskoga plemiæa.
{62646}{62722}Djevojka je zadržala posao | i nakon vjenèanja,
{62727}{62866}ali oko Božiæa su je otpustili. | Došla je k meni i pitala za posao.
{62872}{62932}Sjeæate li se kako se zvala | ta amerièka nasljednica?
{62938}{63058}Ovaj... Mislim da se obogatila | pakiranjem svinjetine.
{63079}{63133}Ne mogu se sjetiti prezimena, | žao mi je.
{63138}{63227}Što se dogodilo mojoj kæeri, | g. Bilney?
{63333}{63452}Jeste li religiozni, g. Holmes? | - Skeptik sam po prirodi.
{63457}{63621}Bože, ako postojiš, | spasi mi dušu, ako je imam.
{63693}{63825}Znam da je vjera nekima velika utjeha | u ovakvim trenucima.
{63841}{63941}Bojim se da je moj otac | poèeo gubiti vjeru.
{64013}{64260}Želi da proèitam nešto na pogrebu. | Ali ne znam hoæu li imati snage.
{64324}{64405}Siguran sam da æete moæi udovoljiti | zahtjevu svojega oca.
{64410}{64475}Možda æe vam nešto znaèiti | da vjerujem da æete
{64480}{64575}iz svega ovoga izrasti | u izvanrednu mladu ženu.
{64652}{64699}Hvala.
{64763}{64866}Možda bi bilo lijepo da za vijenac | privežete nešto Georginino.
{64871}{64972}Kako to mislite? - Neki spomen.
{64979}{65150}Što to? - Nešto što odražava njezin | duh... Èini se da je voljela plesati.
{65166}{65285}Jest. - Možda plesne cipelice?
{65449}{65577}Gdje je lady Georgina dala izraditi | svoje cipele? - Kod Bilneyja.
{65614}{65730}Pogrebnik je zakljuèio da je | Sarah O'Brien poèinila samoubojstvo.
{65735}{65804}Da se bacila u Temzu. | - Što pogrebnik misli
{65808}{65860}da ju je nagnalo | na tako drastièan potez?
{65864}{65996}Nije znao. Jedno je intrigantno. | Iz vode je izvaðena gola.
{66022}{66135}Intrigantno? - Neobièno za ženu | koja se namjerava ubiti.
{66180}{66283}Možda æe se Bilney sjetiti imena | tajnovite pakiraèice svinjetine.
{66291}{66405}Trebali bismo je moæi naæi, | premda je London zapljusnut
{66410}{66482}amerièkim nasljednicama | koje traže muževe s naslovima.
{66488}{66571}Zadužit æu Lestradea za to. | Iako je potpuno praznoglav,
{66575}{66657}kad shvati što mu je èiniti, | uporan je poput buldoga.
{66682}{66749}Što je bilo s lešem? | - To mi je rekao Bilney.
{66754}{66839}Pokopali su je u Whitechapelu | o njegov trošak. - Izvrsno, Watsone.
{66846}{66971}Hvala. Mislim da bi vam se svidio | moj nastup. Pretvarao sam se...
{66975}{67093}Oprostite, niste li rekli | da imate sastanak u 14 h?
{67097}{67155}Nije valjda toliko? - Prošlo je 14 h, | dragi prijatelju.
{67160}{67336}Uh! Kasnim, Holmese. Jako kasnim. | Trebao sam se naæi s gðom Vandeleur
{67341}{67429}u Ulici Bond. | Prokletstvo, vražje èizme.
{67433}{67527}Žurite se polako, Watsone. | - Želi da je savjetujem oko haljine.
{67532}{67622}Stvarno? - Ne bilo koje haljine. | Oko one haljine.
{67627}{67697}Nisam znao da ste struènjak | za visoku modu. - Dobro znate da nisam!
{67702}{67854}Ja, meðutim, znam što je ove godine | u modi. Svi lude za svijetlo sivom.
{67900}{68008}S mrežastim velom i ružièastim ružama.
{68044}{68160}Mjesta zloèina se mogu prekriti | istom kovanicom.
{68164}{68307}Peca u malomu ribnjaku, Lestrade. | Jeste li otkrili èiji su otisci? - Ne.
{68341}{68418}Povjerenik je dobio pismo od kralja. | Njegova Visost predlaže
{68422}{68518}poboljšanje u detektivskim redovima. | Kaže da stanje ne zadovoljava.
{68522}{68577}Oèekuje da æe se sluèaj riješiti | bez daljnjih žrtava.
{68583}{68638}Mogu odmah dati otkaz. | Da mi ga drugi ne moraju davati.
{68643}{68716}Samosažaljevanje je | vrlo neprivlaèno, Lestrade.
{68721}{68824}Treba mi dopuštenje | za ekshumaciju. - Molim?
{68829}{68908}Radi se o Sari O'Brien. Izvukli su je | iz Temze u srpnju ove godine.
{68913}{69014}Sumnjam da smijem... - Pobrini se | da nas ne sprijeèi birokracija.
{69019}{69082}Kralj, Lestrade, sjeti se kralja.
{69113}{69227}Bože, odvratno je! | Ondje se ne može disati.
{69233}{69302}Bolnica je puna oboljelih | od upala dišnih puteva.
{69308}{69438}Lijepo je ružno, a ružno lijepo: | Lebdi kroz maglu i zagaðeni zrak.
{69443}{69564}Kakva je haljina? - Molim? Zakasnio sam | i propustio cijelu strku i paniku.
{69627}{69738}Holmese, zaboga, što radite? | Hoæete li zaplesati fandango?
{69741}{69855}Humor vam se neoèekivano | razvio u lukave dosjetke, Watsone.
{69860}{69935}Morat æu se nauèiti braniti od toga.
{69941}{70072}Evo ga. Mamac je postavljen. | - Kakav mamac?
{70075}{70200}Tu je, Watsone. Promatra i èeka. | Mislim da æe biti na pogrebu.
{70205}{70339}Ako doðe, nadam se da neæe odoljeti | spomenu koji mi je dala Roberta.
{70346}{70464}Ne smijete izložiti lady Robertu | opasnosti. - Ni neæu.
{70469}{70557}Budno æu je paziti. | - Vi neæete biti ondje, Watsone.
{70561}{70638}Za vas imam zadatak | od neprocjenjive važnosti.
{71943}{72146}Ljubav je strast koja traje, | ni od vremena, ni od prostora ne staje
{72216}{72383}Zemaljske je stvari neæe strti | Ona je svjetlo što sja i poslije smrti
{72566}{72768}Zlatni lanac što trgati se ne da | Besmrtna sila koja neæe da se preda
{72838}{73058}Strasti æe zemlja izreæi pravorijek | Ali duše koje vole, vole zauvijek
{73571}{73650}Hvala što ste došli. | Mislim da je prošlo u redu.
{73874}{73946}Povedi konje, Charlese. | Inaèe nikada neæemo doæi kuæi.
{73950}{73991}Da, Vaša Milosti.
{74894}{74955}Imogen, idemo.
{75597}{75638}Imogen.
{75674}{75714}Imogen!
{75725}{75763}Imogen, draga?
{75857}{75894}Imogen!
{76083}{76119}Imogen, draga?
{76124}{76171}Imogen! Imogen!
{76183}{76247}Imogen, Imogen, Imogen!
{76250}{76289}Imogen. Imogen.
{76294}{76324}Imogen!
{76329}{76366}Imogen, doði.
{76371}{76397}Imogen!
{76554}{76614}Što se dogodilo? | - Još je jedna djevojka nestala.
{76619}{76713}Imogen Helhoughton. | Tek joj je 13 godina, g. Holmes.
{76813}{76850}Imogen, Imogen!
{76855}{76897}Imogen!
{77472}{77557}Što je novo, Watsone? | - Zaboga, Holmese!
{77561}{77674}Bar me pustite da uðem prije nego | što poènete s paklenskim pitanjima.
{77708}{77783}Zašto zaudarate | na denaturirani alkohol?
{77797}{77925}Kako bih uništio smrad te jadne | djevojke. Bilo je odvratno, Holmese.
{78058}{78180}Svirali ste Bacha? - M-hm. Njemaèka | glazba pogoduje introspekciji.
{78232}{78336}Zašto ste introspektivni? | - Mlada je djevojka oteta na pogrebu.
{78341}{78410}Ne! - Svima pred nosom.
{78414}{78485}Da nije lady Roberta? | - Ne. Imogen Helhoughton.
{78489}{78619}Najmlaða kæi Sir Johna i lady | Helhoughton. Tek joj je 13 g. - Bože!
{78680}{78739}Zašto je posegnuo | za nekim tako mladim?
{78744}{78847}Oportunizam. | Uoèio je priliku i iskoristio je.
{78861}{78955}Ne bih se èudio da je fizièki slièna | drugima dvjema djevojkama.
{78968}{79060}Toliko o mojoj zamci. Što to imate?
{79064}{79158}Ovu sam èarapu izvadio | iz grla Sarah O'Brien.
{79188}{79261}Bila joj je duboko u jednjaku.
{79272}{79427}Dakle, rukopis je isti. | Instinkt mi govori da je blizu.
{79463}{79638}A kako ne možemo saznati gdje, | moramo u duši naæi strpljenja.
{81274}{81333}Molim vas. Molim vas, pomozite.
{81379}{81452}Pomozite. Neka mi netko pomogne.
{81643}{81710}Ovamo. Ovamo!
{81855}{81943}I? Je li zapamtila kako izgleda? | - Nisam je smio ispitati.
{81947}{82024}Unutra je s lijeènikom. U šoku je, | možete zamisliti, jadnica.
{82027}{82144}Bit æe još žrtava, Lestrade, | ako ubrzo ne pronaðemo ubojicu.
{82149}{82227}Doista smo imali sreæe što je ova | djevojka preživjela i može govoriti.
{82232}{82338}S tim æemo morati prièekati. - Kvragu, | ne mogu raditi cigle bez gline!
{82341}{82439}Holmese, moram priznati da bih | postupio isto kao taj lijeènik.
{82443}{82500}Takav šok može dovesti do pada | krvnoga tlaka...
{82505}{82630}Da, da, Watsone, znam sve o šoku. | No ne biste li se složili
{82635}{82763}da je dobro prièati o traumi | dok je dojam još uvijek svjež,
{82768}{82888}prije nego što okošta, | i to sa senzitivnim profesionalcem?
{82893}{82957}Vi biste slušali pola minute prije | nego što je poènete ispitivati.
{82960}{83033}Nisam ni predlagao sebe, | nego iznimno dragu i pažljivu
{83036}{83150}psihijatricu koju sluèajno poznajem. | - Tko je ona, zaboga?
{83343}{83418}Otkrili smo tko je amerièka | pakiraèica svinjetine. - Slušam.
{83422}{83507}Sada je lady Marham. | - Zašto je otpustila Sarah O'Brien?
{83511}{83618}Mislila je da joj krade odjeæu. | I li da je nosi, ako je baš ne krade.
{83633}{83733}Kakvu odjeæu? - Donje rublje, | èarape, cipele.
{83738}{83796}Gða Vandeleur dolazi.
{83808}{83919}Sarah O'Brien je vjerojatno mjesec-dva | radila s poslugom lorda Marhama.
{83924}{83968}Evo popisa.
{84014}{84154}Charles Allen? Bio je lakaj lorda | Marhama kad je Sarah otpuštena.
{84225}{84346}Ha! Charles Allen. Sada je lakaj | vojvotkinje od Narborougha.
{84355}{84400}Sigurni ste da se radi | o istomu èovjeku?
{84405}{84480}Nema veze i ako je to tako. | - Kako to mislite, inspektore?
{84485}{84583}Alibi mu savršeno drži vodu. | - Kako ste danas iskrièavi, Watsone.
{84588}{84697}Kad je lady Alice nestala, bio je | na službenoj veèeri s vojvotkinjom
{84702}{84761}i vidjelo ga je stotinjak ljudi.
{84766}{84847}Bio je s vojvotkinjom | i kad je oteta lady Georgina.
{84852}{84975}Ne bi trebao postojati dogaðaj | koji mudar èovjek ne zna objasniti.
{84979}{85046}Dovedite ga na ispitivanje, Lestrade. | Dovedite ga odmah.
{85208}{85263}Došla je.
{85366}{85435}Bio sam slobodan napisati | nekoliko pitanja.
{85439}{85494}Ništa ne obeæavam, Sherlock, | osim da æe mi na prvomu mjestu biti
{85497}{85619}psihološko zdravlje djevojèice. | - Toèno. Obratite pažnju na 3. pitanje.
{85632}{85836}Zgrabio me s leða. Preko nosa i usta | mi je stavio krpu odvratna mirisa.
{85894}{86038}Htjela sam zavikati, ali nisam mogla. | Povlaèio me izmeðu grobova.
{86060}{86122}Mislim da sam se onesvijestila.
{86147}{86218}Èega se sljedeæe sjeæaš?
{86222}{86318}Skinuo mi je povez s oèiju.
{86325}{86394}Jesi li mu vidjela lice?
{86460}{86586}Htio bih razgovarati o neèemu iz doba | kad ste bili lakaj lorda Marhama.
{86591}{86713}Sjeæate li se sluškinje lady Marham, | djevojke po imenu Sarah O'Brien.
{86718}{86797}Sjeæam se. | - Lady Marham ju je otpustila?
{86804}{86885}Mislim da jest. - Znate li zašto?
{86902}{86997}Ne. - Znate li što je bilo s njom?
{87002}{87111}Znam. Ubila se. Bilo je u novinama | i svi su prièali o tomu.
{87136}{87229}Znate li zašto se ubila? - Ne.
{87255}{87388}Držao je dvije èarape. | Jednu mi je svezao oko vrata.
{87391}{87504}Mislim da to nije... | - Drugu mi je ugurao u usta.
{87508}{87561}Nije li joj ovo preteško?
{87566}{87614}Zašto ste napustili službu | kod lorda Marhama?
{87619}{87729}Vojvoda od Narborougha mi je ponudio | posao. Prihvatio sam ponudu.
{87733}{87833}Kako vas je vojvoda zapazio? | - Pratio sam lorda Marhama
{87838}{87908}u mnogim prigodama kojima je | nazoèio i vojvoda od Narborougha.
{87913}{87993}I zapazio vas je? - Ne znam, doista.
{87996}{88097}I li vas je zapazila vojvotkinja? | Vi ste vojvotkinjin lakaj, zar ne?
{88102}{88169}Jesam, Holmese.
{88174}{88291}Radi se o sitnici, ali ipak bih vas | zamolio da me oslovljavate titulom.
{88296}{88413}Inaèe bih radeæi ovaj posao bio na | 'ti' s pola londonskih kriminalaca.
{88460}{88560}Da, gospodine Holmes, | u vojvotkinjinoj sam službi.
{88564}{88636}Pokazao mi je odjeæu | koju je imao za mene.
{88649}{88813}Stalno je govorio kako æu prekrasno | izgledati u njoj. Poèeo me svlaèiti.
{88846}{89068}Stajala sam. Kleknuo je preda me. | Skinuo mi je cipele i...
{89127}{89232}Mislim da bi bilo dosta. | - Je li držao cipele?
{89263}{89372}Je li ih gladio? Je li ih ljubio?
{89441}{89516}Znate li za Bilneyjevu | obuæarsku radnju?
{89635}{89739}Ne. - Ondje je Sarah O'Brien radila | kad je napustila lady Marham.
{89743}{89835}Da? - Gdje Grace nabavlja obuæu?
{89839}{89889}Kod Calstocka u Piccadillyju.
{89894}{89975}Kako veže èizme? | Sa strane, naprijed ili otraga?
{90052}{90111}Naprijed.
{90118}{90297}Spustio mi je èarape. Do gležnjeva. | Stavio mi je usta na nožne prste.
{90366}{90554}Zubima je uhvatio èarapu i povukao je. | Skinuo mi je lijevu èarapu. I desnu.
{90621}{90805}Odjednom se razbjesnio. | Vikao je na me. Izvukao me iz sobe,
{90836}{91058}uza stube, na ulicu. Èarapa mi je bila | u ustima. Gušila sam se.
{91113}{91168}Ustanite, molim vas.
{91280}{91377}Stavite, molim vas, nogu ovdje.
{91725}{91836}Hvala. Puno ste nam pomogli. | Zamolit æu da vam uzmu otiske.
{91839}{91933}Veæ jesu. - Da, ali nešto nije bilo | u redu. Ponovit æemo to.
{91938}{92018}Nemate razloga protiviti se. - Nemam.
{92022}{92079}Dobro. Prièekajte.
{92275}{92393}Vidjela ga je. Opisuje ga | Lestradevomu policajcu. - Izvrsno.
{92397}{92488}Zamalo se spasila. Nije bilo tako | grozno kako je moglo biti.
{92493}{92560}Što misliš, zašto ju je pustio | iako ga može prepoznati?
{92579}{92674}Ne znam. Možda ipak nije htio | nauditi trinaestogodišnjakinji.
{92679}{92746}Ne, ne radi se o tomu. | Odjeæa bi joj savršeno pristajala.
{92750}{92855}Radi se o neèemu drugom. | Morat æemo moliti još jednu uslugu.
{92893}{92963}Doktore, mogu vam opisati | stopala lady Imogen.
{92968}{93063}Lady Helhoughton, doista ih moramo | vidjeti vlastitim oèima.
{93080}{93132}Smijem?
{93585}{93664}Hvala, Imogen. | Hvala, lady Helhoughton.
{93732}{93822}Kirurg je to odlièno napravio. Hvala.
{93835}{93924}Ta je nakaznost jedino | zbog èega ju je pustio.
{94016}{94122}Talipes calcaeno-valgus? | - Mislim da je talipes varus.
{94127}{94189}A to je? - Èotava noga.
{94194}{94258}Isprièavam se.
{94336}{94402}Još jednom hvala na suradnji.
{94421}{94508}Mogu li sada poæi? - Naravno.
{94754}{94869}Slobodno? - Netko vas mora ispratiti. | Takva su pravila. Izvolite.
{94886}{94964}Mislim da sam došao onuda. | - Ne, ovuda.
{95383}{95460}To je on! To je on! On je, on je.
{95525}{95619}Mislim da je to pouzdano | prepoznavanje. - Mislite što hoæete.
{95947}{96085}To je bilo jako okrutno, Sherlock. | - Možda, ali mislim da je opravdano.
{96333}{96418}Evo novih otisaka prstiju | Charlesa Allena.
{96422}{96493}Ove ste uzeli jutros? | - Prije 15 minuta.
{96605}{96661}Ne slažu se, Holmese.
{96666}{96785}Znamo da je bio s vojvotkinjom | kad je lady Imogen oteta s groblja.
{96791}{96918}Znamo da je bio s vojvotkinjom I još | 100 gostiju kad je oteta lady Alice.
{96950}{97036}Lady Imogen je prošla pakao. | Sigurno je jako zbunjena.
{97041}{97161}Zabunila se u vezi s Allenom. | Nemate dokaza, Holmese. Uopæe.
{97193}{97314}Gospodine, vojvoda i vojvotkinja od | Narborougha vas žele vidjeti. - Molim?
{97349}{97488}Smije li moj lakaj sada iæi? - Smije. | Isprièavam se, Vaša Milosti,
{97493}{97600}za sve probleme... - Nema problema, | inspektore. Bila je to manja nelagoda.
{97621}{97682}Gdje ste bili sinoæ, Vaša Milosti?
{97730}{97814}Odgovarati na pitanja | insp. Lestradea je jedno.
{97819}{97914}Reakcija na vaše | bezrazložno njuškanje nije ista.
{97921}{98032}Podsjetio bih Vašu Milost da je vaš | muž potražio mene u ulici Baker.
{98036}{98186}Da, i zamolio bih vas da potražite | mene na Trgu Eaton da se razdužimo.
{98197}{98299}Više ne želim da me zastupate. | - Kako Vaša Milost želi.
{98361}{98468}Mislite li da nitko drugi ne može | riješiti ovaj sluèaj?
{98472}{98529}Èudovišne li umišljenosti.
{98575}{98627}Ovuda.
{99385}{99472}Najveæi je poticaj | kad se sve okrene protiv tebe.
{99477}{99536}Ne bi li najrazumnije bilo | zakljuèati sve te plesaèice
{99541}{99643}dok se ne pronaðe ubojica? | I li bar dok se ne digne magla?
{99708}{99785}Bilo bi to vrhurazumno, Watsone. | Ali nešto ste zaboravili.
{99788}{99864}Što to? - Ništa se ne smije isprijeèiti | slobodnomu tržištu.
{99868}{99955}Djevojke treba udati! | Hvala na pomoæi, gðo Vandeleur.
{99960}{100000}Ne znam jesam li se | uopæe trebala miješati.
{100005}{100071}Doista? Eto, èovjek uèi dok je živ.
{101374}{101466}Što hoæete? Plašite me. | Zašto ste ovako ušli?
{101471}{101546}Morao sam vas vidjeti, | a da vaš otac za to ne sazna.
{101550}{101672}Roberta, imate li hrabrosti biti mamac | za ubojicu vaše sestre?
{102236}{102340}Nedavno ste izradili cipele za lady | Robertu Massingham? - Jesam.
{102344}{102446}Želim da joj izradite par cipela. | Za veèeras. - Veèeras?!
{103908}{103949}Dobra veèer.
{104304}{104357}Dobra veèer, Vaša Milosti.
{104775}{104872}Dobra veèer, lorde. | - Dr. Watson. Kako ste?
{104875}{104954}Vrlo dobro. - Gdje je g. Holmes?
{104958}{105018}Kad bih barem znao. | Trebali smo se naæi ovdje.
{105022}{105097}Monsieur Sherlock Holmes? - Da.
{105132}{105197}Drugi najviši kriminalistièki | struènjak u Europi?
{105202}{105305}Smijem li vas pitati, Ekselencijo, | tko je po vašem mišljenju prvi?
{105310}{105496}Èovjeku preciznoga znanstvenoga uma | mora se svidjeti rad g. Bertillona.
{105627}{105682}Pompozna budala.
{105765}{105897}Njihova kraljevska velièanstva kralj | Edward VI I. I kraljica Alexandra.
{106683}{106802}Eno je. - Doista je prekrasna.
{109011}{109132}Draga, ponosim se tobom. - Hvala.
{109243}{109329}Tvoja bi sestra uživala u ovome.
{109535}{109582}Roberta...
{111104}{111215}Jeste li dobro, lady? - Jesam, hvala.
{111252}{111366}Biste li da upalim svjetla | da bolje vidite? - Nemojte se gnjaviti.
{111641}{111747}Biste li štogod popili? - Ne, hvala.
{111810}{111933}Sigurno ste dobro? | Izgledate malo onemoæalo.
{111957}{112047}Sasvim sam dobro, kažem vam. | Vratite se svojoj gospodarici.
{112219}{112310}Možda bi vam godila èaša pjenušca.
{112650}{112727}Molim vas da me sada ostavite.
{112960}{113035}Jamais de la vie!
{113099}{113179}Što se dogaða? Straža!
{113396}{113460}Pomagao sam joj. | Onesvijestila se.
{113488}{113555}Doktore Watson...
{113775}{113949}Nije loše za drugog najvišeg | kriminalistièkog struènjaka u Europi.
{114330}{114411}Holmese, opet ste me namjerno | držali u neznanju.
{114416}{114471}Doista mislim da biste mogli biti | malo iskreniji prema meni.
{114475}{114522}Moje bi zanimanje | bilo pusto i dosadno
{114527}{114594}da katkad ne pripremim prizor | koji æe uvelièati ishod dogaðaja.
{114599}{114654}Imate zanimljiv | dašak tajnovitosti, Holmese.
{114658}{114725}Najbolji kovaè planova | je onaj koji ih kuje sam.
{114730}{114797}Hvala na povjerenju.
{115141}{115199}Zaboga...
{115204}{115261}Inspektore. Uzmite otiske prstiju | ovomu èovjeku.
{115266}{115333}Opet? - Opet.
{115494}{115605}Veæ smo mu dvaput uzeli otiske | i ne slažu se s onima s boce vinjaka.
{115610}{115682}Ovaj put hoæe. - Kako, zaboga?
{115686}{115790}Tako što postoje dva Charlesa Allena. | - Molim?
{115794}{115904}Kad izuzmete sve što je nemoguæe, | ono što ostane je rješenje,
{115908}{115969}koliko god bilo nevjerojatno. | - Ali kako mislite da su dva?
{115974}{116091}To je jedino objašnjenje. Èovjek koji | nam je u pritvoru je jedan od dvojice.
{116124}{116205}Kako? - Braæa Dromio. Braæa Antipholus. | Kastor i Poluks.
{116210}{116291}Na engleskom, Holmese. | - Jednojajèani blizanci.
{116405}{116486}Znaèi, jedan od njih je na slobodi. | - Da, ali ubojica je kod nas.
{116491}{116568}Kako znate? | - Pokušao je oteti lady Robertu.
{116571}{116652}Holmese... - Otisci æe sve rašèistiti.
{116657}{116743}Dok je sadistièki blizanac obnašao | svoj prljavi posao,
{116747}{116854}brat mu se uvijek pobrinuo za alibi. | Do sada smo veæ dva puta
{116858}{116977}uzeli otiske Charlesu-sudioniku. | A ne ubojici.
{117029}{117104}Ali identièni su. - Otisci prstiju su | i kod jednojajèanih blizanaca
{117108}{117274}razlièiti i individualni. | Napokon nam je dolijao.
{117711}{117760}Spava.
{118057}{118144}Hvala na pomoæi. - Nema na èemu.
{118219}{118275}Kako vam je žena?
{118341}{118474}U mentalnoj je bolnici. - Možda je tako | najbolje dok se ne oporavi.
{118560}{118685}Bojim se da nikada neæe preboljeti | gubitak Georgine.
{118733}{118863}Muškarac se, naravno, može nositi | s tragedijom kad ga zadesi.
{118891}{119010}Ali žene... One su ipak slabije...
{119127}{119180}Sutra se ženim.
{119215}{119293}Stvarno? Nisam znao.
{119360}{119405}Èestitam.
{119552}{119633}Evo novih otisaka prstiju. - Dajte.
{119907}{120000}Imamo krivoga èovjeka. - Molim?
{120016}{120069}Ubojica je još uvijek na slobodi.
{120074}{120136}Odmah nazovite lorda Massinghama. | Moramo ga upozoriti.
{120141}{120208}Lady Roberta je u velikoj opasnosti.
{121783}{121849}Halo?
{121925}{121980}Doktore Watson!
{122229}{122310}O, Bože! Roberta!
{122329}{122363}Kloroform.
{123497}{123566}Holmese, što se dogaða?
{123599}{123700}Dva su, Watsone. Gotovo identièni, | gotovo ih je nemoguæe raspoznati.
{123705}{123757}Otkada znate?
{123761}{123863}Sumnjam veæ neko vrijeme. | Neobièni èvor oko vrata,
{123868}{123935}Charlesove cipele svezane | na potpuno isti naèin.
{123940}{124010}Kad ga je Imogen Helhoughton | prepoznala, bio sam siguran.
{124015}{124066}To je èovjek kojega smo tražili. | Ali kako je mogao biti
{124069}{124136}na dva mjesta odjednom? | Morala su biti dvojica.
{124141}{124250}Ali imamo krivoga? - Imamo krivoga.
{124360}{124443}Watsone! Watsone!
{125702}{125769}Gdje ih odvodi?
{125918}{125985}Gdje ih odvodi?
{125988}{126074}Uèini to. Dovrši to.
{126813}{126860}Moram vidjeti vojvotkinju | od Narborougha.
{126865}{126936}Znate li koliko je sati? | Uz dužno poštovanje... - Oprostite.
{127133}{127213}To je nemoguæe. - Nije, vjerujte. | Prevarili su vas,
{127218}{127325}preveslali na najgori moguæi naèin. | - Ne znam o èemu govorite.
{127329}{127435}Vaša Milosti, jedan je brat | upravo u pritvoru,
{127440}{127552}a drugi muèi lady Robertu Massingham | i vjerojatno æe je ubiti.
{127557}{127710}Morate mi pomoæi. Ne smijete štititi | èovjeka koji vam je ubio kæer.
{127802}{127866}Ne možete štititi sebe na raèun | života jedne mlade djevojke.
{127871}{128004}Ne mogu... Zbunjena sam. | Teško je to shvatiti.
{128008}{128146}Ne, Vaša Milosti, nije. Njih su se | dvojica stalno izmjenjivala.
{128150}{128240}Glumili su jedan drugoga. | Sve su dijelili.
{128308}{128375}Sve.
{128440}{128566}Nije li vam to govorio | vaš ženski instinkt?
{128582}{128750}Još jednom æu vas pitati, | imate li pojma gdje bi mogao biti?
{128958}{129036}Gdje ste se sastajali?
{129268}{129311}Gdje je?
{129396}{129518}Kad plesu doðe kraj
{129522}{129636}Kad svane zora
{129644}{129766}Kad odu plesaèi
{129772}{129894}Kad odu zvijezde
{129900}{130025}Mnoga su srca tužna
{130030}{130227}Vidjet æe tko ih zna, | Mnoge su nade ugasle
{130316}{130441}Kad plesu doðe kraj
{130532}{130619}Watsone? - Holmese. Sastajali su se | u Albert Mansions u Kensingtonu.
{130997}{131096}Stanite, stanite. | Odvest æu vas onamo. - Molim?
{131102}{131166}Znam kamo odvodi djevojke. | Odvest æu vas onamo.
{131172}{131241}Teško je oèuvati nježne ruke.
{131288}{131377}Kožu koja je dovoljno glatka za ovo.
{131382}{131493}Veæina ljudi bi poderala | svilene èarape. Ali ja neæu.
{131735}{131843}Ne, molim vas. Ne, ne.
{131993}{132055}Ovdje je.
{132268}{132340}Kvragu. Zaustavite ga!
{132404}{132479}Zaustavite ga! Stani!
{132868}{132916}Holmese. - Watsone.
{132927}{132993}Jeste li naoružani? - Imam štap.
{133060}{133122}Koji broj? - Broj 12.
{133157}{133227}Watsone. - Što je?
{135086}{135111}Watsone.
{135213}{135300}Pusti je, ili pucam. | - Siguran si da æeš pogoditi?
{135304}{135447}Ne posve. Ali siguran sam u sljedeæe: | Ako je ubiješ,
{135454}{135624}nikada više neæeš vidjeti brata, | obeæavam ti. Otpusti podvez.
{135685}{135785}Sudit æe vam pojedinaèno. | Objesit æe vas pojedinaèno.
{135790}{135894}Više se nikada neæete vidjeti | na ovome svijetu.
{135919}{135982}Pusti je.
{136250}{136355}To je poput vrata, zar ne? | Otvorena su.
{136382}{136486}Kad jednom proðeš kroz njih, | više nema povratka.
{136515}{136700}Znam. To je ovisnost. Svaki put | nam treba malo više, zar ne?
{136735}{136836}Da nas podigne. Do iste visine.
{137022}{137086}Koja je uloga tvojega brata?
{137113}{137285}On ti je alibi, to znam. Je li ti | svodnik? Je li perverzan poput tebe?
{137349}{137452}Tako ih dobro odijevaju, zar ne? | - Dobro odijevaju?
{137500}{137593}Šepure se preda mnom | u svojim kostimima,
{137604}{137721}otkrivaju više nego što pokrivaju, | razmeæu se.
{137724}{137805}Ne razmeæu se. | Ni ne primjeæuju te.
{137835}{138005}Lady te zove u krevet, ali djevojke | koje želiš, koje ti se sviðaju,
{138058}{138219}one te nikada ni ne pogledaju, zar ne? | - Ovdje da. Ovdje me pogledaju.
{138465}{138543}Nisu li prekrasne? - Ne diraj ih.
{138563}{138707}Volim ih dirati. Koža im je tako meka. | - Ostavi ih.
{138724}{138843}Divno mirišu. - Ostavi ih, kad kažem.
{138847}{139007}Posebne cipele za posebnu djevojku. | Više ti neæe trebati.
{139291}{139355}Kako je, Watsone? - Ne diše.
{140313}{140391}Hvala Bogu. Hvala Bogu.
{141383}{141429}Charlese.
{141722}{141819}Pustite mi je, doktore Watson. | - Pažljivo.
{141869}{141924}Iæi æu s njom.
{142530}{142594}Kojega li dana za vjenèanje.
{142979}{143032}Nazdravimo.
{143063}{143130}Ako možemo suditi èovjeka | prema njegovu društvu,
{143135}{143204}onda je doista pristojno da je Watson | napokon pronašao
{143207}{143286}šarmantnu i pristalu družicu.
{143304}{143408}Doktore i gospoðo Watson, | želim vam zdravlje i sreæu.
{143433}{143504}Zdravlje i sreæu.
{143629}{143707}Sada moramo iæi. | - Primi moj savjet, Jenny.
{143721}{143791}Ne daj da ti Watson kaže | da nije raspoložen za slike
{143794}{143936}i da te odvede u Muzej anatomije | gledati voštana srca, pluæa i jetra.
{143961}{144035}Ne brini se, Sherlock, | raspored je veæ dogovoren.
{144040}{144165}Sutra naveèer smo u Operi Garnier. | - U pravo vam to govorim.
{144200}{144316}Što æete sad kad nema | vašega Boswella?
{144321}{144424}Moja je igla uvijek sa mnom. | - Holmese...
{144477}{144586}Dobri stari Watsone. Vi ste jedina | èvrsta toèka u vremenima promjene.
{144590}{144663}Ne, sjedit æu i gledati u zid | poput Whislerove majke.
{144668}{144793}Radna soba u sivom. | A sada je vrijeme da poðete.
{144847}{144946}Da ne propustite kasni doruèak | sutra u hotelu Splendid.
{144969}{145080}Nadam se da æete me pozvati kad æete | trebati kolegu u vašim istragama.
{145085}{145136}Dragi prijatelju. Naravno.
{145183}{145230}Naravno.
{145344}{145391}Sretan put!
{145392}{145593}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan 
{146482}{146607}Prijevod: | VIRTUAL-D, Zagreb
{146632}{146757}Obrada: | CONTINENTAL FILM, Zagreb
