{1}{1}25.000
{820}{920}{C:$0000FF}{y:ib} CRNO |{C:$FF0000}{y:b} I BIJELO  
{1491}{1522}Dobro jutro svima!
{1524}{1597}Ovdje Fuzzy, s radio postaje Power 106.
{1600}{1675}Danas je moj omiljen dan. | Želite znati zašto?
{1677}{1734}Sretno Valentinovo.
{1736}{1789}Toèno, danas je Valentinovo.
{1791}{1840}Netko mi je veæ poslao slatkiše.
{1842}{1889}Neki slušatelji cvijeæe.
{1891}{1963}Najsretniji sam tip u L.A. -u.
{1965}{2027}Dobro jutro svima. Dan je prekrasan.
{2029}{2095}Sunèano je, veæ je 18 stupnjeva.
{2097}{2164}Gužva je u prometu. Koga briga? | Danas su svi zaljubljeni.
{2166}{2208}Stiæi æe na posao kad zažele.
{2210}{2276}Svi æe dobiti cvijeæe i slatkiše.
{2278}{2361}Svaka djevojka ima dogovoren spoj. | Svi su restorani rezervirani.
{2363}{2419}Kad odem s posla | vjerojatno æe i mene èekati èetiri spoja.
{2421}{2456}Valentinovo - sastanak s Jackom Pinom | Revizija izraèuna
{2458}{2535}Moram nekamo izvesti mamu. | Djevojka mi je veæ poslala buket cvijeæa.
{2537}{2611}A samo nebo zna | što mi je veèeras pripremila supruga.
{3380}{3416}Sretno Valentinovo.
{3432}{3476}Vratit æu se ranije.
{5041}{5068}Kenya.
{5092}{5118}Kenya!
{5165}{5193}Leah.
{5253}{5333}Ovo mi je poslao Berte i ne znam što æu.
{5335}{5404}U ovoj bih izgledala kao krava.
{5406}{5440}A ova mi se sviða...
{5442}{5493}ali cijelo æu vrijeme morati uvlaèiti trbuh.
{5495}{5564}Odjeni onu koja ti se sviða. | Vjenèanje je tvoje.
{5574}{5613}Moramo te udati.
{5615}{5665}Kao što bi rekla moja majka: | "Negdje te èeka...
{5667}{5724}- "muškarac koji ti je suðen." | - Sigurna sam u to.
{5726}{5779}Koga poznajemo za tebe?
{5781}{5826}Ne poèinji. Danas me èeka naporan dan.
{5828}{5899}Uvijek je tako. Èak i vikendom.
{5901}{5944}Ne smije ti posao biti sve u životu.
{5946}{6003}I nije. Imam sastanak.
{6005}{6090}Brian! Visok je, privlaèan, opet sâm...
{6092}{6158}arhitekt, inteligentan. Savršen je.
{6160}{6188}Hvala, ali ne.
{6190}{6229}- Ma daj. | - Ne volim spojeve naslijepo.
{6231}{6306}U redu. Dodat æu to na popis stvari | koje Kenya ne voli.
{6308}{6394}Uz sushi, pse, kajak...
{6396}{6484}jezive gmizavce i crvenu boju.
{6503}{6557}Crvena nikako nije moja boja.
{6642}{6690}Jack Pino? Kenya McQueen.
{6713}{6749}- Zdravo. | - Zdravo.
{6867}{6957}Pregledala sam pismo iz banke | i imam nekoliko pitanja.
{6959}{7033}- Ne bismo li trebali prièekati? | - Koga?
{7035}{7088}Zar ne dolazi još netko?
{7125}{7170}Ne.
{7179}{7225}Ja sam viša upraviteljica.
{7267}{7379}Kad razradimo ugovor | poslat æu nekoga po spise.
{7426}{7509}Ali sad smo samo mi. U èetiri oka.
{7511}{7553}U redu.
{7735}{7799}Èetiri martinija za èetiri prekrasne dame.
{7801}{7827}Hvala.
{7829}{7857}- Želim nazdraviti. | - Da.
{7859}{7925}Možda u ovome trenutku | nemamo sve što želimo...
{7927}{7964}ali imamo jedna drugu.
{7966}{8066}- Sretno Valentinovo. | - Sretno Valentinovo.
{8081}{8120}Ovo je prekrasno, Kenya.
{8122}{8177}Bacimo se na posao. Gdje su komadi?
{8179}{8232}Da. Gdje su?
{8303}{8344}- Imaš slatko... | - Srce...
{8355}{8390}Shante.
{8408}{8436}Bože mili!
{8438}{8514}Zato mi èinimo 42,4%.
{8516}{8546}Èega?
{8557}{8637}42,4% crnkinja nikad se nije udavalo.
{8639}{8696}Proèitala sam èlanak. | Ne piše da se nikad neæemo udati.
{8698}{8731}Samo da nas to èeka.
{8733}{8801}A kad æe se to dogoditi? | U nekom drugom životu?
{8803}{8871}Pa èak i ako se nas 42,4% | nikad nije udavalo...
{8873}{8925}to znaèi da æe se nas 57,6% ipak udati.
{8927}{8979}A to je veæi postotak.
{8981}{9046}Hvala, matematièarko. Dojmljivo.
{9048}{9106}No ipak je sve protiv nas.
{9108}{9196}Kažu da je pojava najraširenija | meðu Afroamerikankama...
{9198}{9241}koje imaju ostvarene karijere.
{9243}{9306}Sutkinja, raèunovotkinja, | bankarica, pedijatrica.
{9308}{9338}To smo mi.
{9340}{9405}Umorila sam se da me smatraju žrtvom.
{9407}{9481}Uspješne crnkinje | koje su osuðene na nesreæu i samoæu.
{9483}{9543}Moram vjerovati da æu pronaæi g. Savršenog.
{9545}{9590}I ne treba mi. Samo želim dobrog tipa.
{9592}{9619}Tako je.
{9621}{9676}Ne treba mnogo zaraðivati, | samo da ima posao.
{9678}{9706}- Da. | - Slažem se.
{9708}{9773}Mora biti viši od mene, | visokoobrazovan i da nije luðak.
{9775}{9853}Bez djece, zdravih zubi | i bez nastranog seksa.
{9855}{9925}Katkad volim probati nešto novo, ali...
{9927}{9953}Što?
{9967}{10021}- Opet to èiniš. | - Opet imaš cijeli popis.
{10023}{10080}Trebala si ostati s Rashidom Mohammedom.
{10082}{10129}S tim muslimanskim šovinistom?
{10131}{10201}Ma daj. Rashid je bio dobar.
{10203}{10317}Jela bih grah, išla u džamiju...
{10319}{10405}hodala pet koraka iza njega i nosila burku.
{10430}{10521}Poslušala sam novi CD | dr. LaWande Phillips.
{10523}{10592}Kaže da ako slijepo slijedimo...
{10594}{10629}ono što mislimo da želimo...
{10631}{10713}time si zakidamo obilje toga.
{10715}{10789}Toliko smo si zacrtale...
{10791}{10849}izgled SC-a...
{10865}{10911}"Savršenog crnca."
{10916}{10977}Ona kaže da se trebamo opustiti...
{10979}{11041}kako bi ljubav došla sama od sebe.
{11043}{11125}Tako se to i zove. "Opusti se i uživaj."
{11127}{11192}A to znaèi | da ne smiješ praviti popise, Kenya.
{11213}{11280}- "Opusti se i uživaj." | - Toèno.
{11282}{11367}I zvuèi mnogo bolje od "podgrijavaj nadu".
{11381}{11409}U redu.
{11411}{11478}- Opusti se i uživaj. | - Svemir nas sluša.
{11480}{11514}- Savršeno. | - Da.
{11516}{11553}Samo nek' je crn i dobar.
{11555}{11617}Visokoobrazovan, uglaðen i zaposlen.
{11619}{11661}S dobro plaæenim poslom.
{11739}{11781}Imate novu poruku...
{11783}{11868}primljenu danas u 21.49.
{11883}{11971}Kenya, Rashid je. Sretno Valentinovo.
{11973}{12025}Èesto mislim na tebe.
{12027}{12099}Htio sam ti reæi da se ženim.
{12115}{12191}Prekrasna je. | Upoznao sam je na skupu muslimana.
{12193}{12248}Želim da doðeš na vjenèanje...
{12250}{12277}Halo.
{12285}{12343}Sretno Valentinovo, srce.
{12363}{12411}Nikada ne zaboravljaš.
{12421}{12482}Da zaboravim svoju djevojèicu? Nemoguæe.
{12503}{12533}Hvala, tata.
{12537}{12587}Zvuèiš potišteno. Reci mi što ti je.
{12589}{12666}Dobro sam. Sve je u redu.
{12676}{12739}Ne odustaj, srce.
{12749}{12817}Znaš kako ostvariti svoje snove.
{13529}{13561}Gðice McQueen?
{13616}{13700}Dr. Brockton, nisam vas vidjela.
{13719}{13769}- Odlièno izgledate. | - Hvala.
{13771}{13833}Ovo je Kenya McQueen.
{14135}{14189}- Kako je Laurie? | - Dobro.
{14211}{14290}- Zašto nam se ne pridružiš? | - Ne mogu.
{14294}{14347}- Imaš spoj s nekim? | - Ne.
{14349}{14458}Jedan moj prijatelj nedavno je | preko interneta ugovorio spoj naslijepo.
{14463}{14539}Pripazi se. Ima mnoštvo vrebaèa.
{14565}{14593}Da.
{14617}{14657}- Bilo mi je drago. | - Vidimo se.
{14659}{14711}- Bilo mi je drago, Kenya. | - Takoðer.
{15339}{15384}Èekate nekoga?
{15386}{15428}Po imenu Brian?
{15471}{15497}Zašto?
{15510}{15565}Ja sam Brian.
{15567}{15602}Ti si Kenya?
{15617}{15679}- Brian Kelly? | - Da.
{15681}{15731}Brian Kelly, moj spoj naslijepo?
{15934}{15979}- Žao mi je. | - Toliko je loše?
{15981}{16021}Oèito si oèekivala nekoga drugog.
{16023}{16049}Nisam.
{16062}{16116}Leah te savršeno opisala.
{16124}{16153}Baš je šašava.
{16155}{16210}O tebi je rekla sve najbolje...
{16212}{16248}Hoæemo li sjesti?
{16265}{16291}Može.
{16306}{16373}- Pronaðimo stol. | - Može.
{16416}{16490}Kako si, brate? Magic je dobar prema tebi?
{16492}{16533}Nikad ga nisam upoznao.
{16800}{16878}- Svi su zauzeti... | - Evo jednoga.
{16970}{17030}Dreadlocksi su ti sjajni, curo.
{17079}{17105}Èovjeèe...
{17287}{17358}- Neugodno ti je? | - Ne. Zašto bi mi bilo?
{17360}{17453}Razgovaraš s neznancima, | želiš dokazati da si dio ekipe.
{17574}{17645}Veæ si imala spoj naslijepo?
{17670}{17701}Ovo mi je prvi.
{17724}{17762}Zašto si to uèinila?
{17768}{17810}Ne znam...
{17827}{17914}obeæala sam curama da æu biti otvorenija.
{17961}{18001}Ali ne ovoliko.
{18261}{18314}- Što je? | - Ništa.
{18497}{18568}Slušaj. Drago mi je što smo se upoznali...
{18570}{18615}ali moram iæi.
{18617}{18678}Ovaj me tjedan èeka toliko posla.
{18680}{18730}- Drago mi je... | - Što si me upoznala.
{18732}{18786}Da, doista.
{18788}{18817}I meni takoðer.
{18819}{18878}- Doista? | - Da.
{18880}{18913}- Bog. | - Bog.
{19035}{19071}Što bi Lei?
{19073}{19129}Vjerojatno je imala dobre namjere, | ali èovjeèe.
{19131}{19190}- Idemo. | - Tek smo stigle.
{19192}{19270}- Imaš drugog posla? | - Da. Mogu se doma zadovoljavati.
{19272}{19303}- Bog. | - Bog.
{19305}{19334}Sjajna zabava.
{19336}{19425}Pogledaj ovo mjesto i sve to cvijeæe.
{19435}{19465}Pogledaj fontanu.
{19467}{19522}Te su ploèice uvezene.
{19524}{19573}Tko god da je sredio vrt...
{19575}{19619}- Pjenušac. | - Napokon.
{19635}{19667}Hvala.
{19679}{19744}Leah bogme zna prirediti proslavu zaruka.
{19746}{19806}Nešto se kuha.
{19818}{19892}Ne znam zašto me uvijek gledaju | oni u pregaèama i odorama...
{19894}{19932}s ploèicama s imenima?
{19934}{20000}Piše li mi na èelu da sam spremna na sve?
{20011}{20071}Tko želi probati nešto vruæe i slatko?
{20110}{20186}"Opusti se i uživaj", je li?
{20207}{20278}- Isprièavam se. | - Ne ostavljaj me, Cheryl.
{20290}{20365}- Kako si? | - A ti?
{20380}{20417}Walter. Drago mi je.
{20419}{20487}- Cheryl. Takoðer. | - Zdravo, Cheryl.
{20489}{20557}- Što kuhaš? | - Moj specijalitet.
{20567}{20611}Rado bih probala nešto vruæe i slatko.
{20613}{20642}Želiš kušati?
{20644}{20674}- Da. | - Odmah.
{21277}{21329}Ovo je moja sretna fontana. Sviða ti se?
{21331}{21412}Gðo Cahan. Èestitam.
{21414}{21499}Hvala. Zovi me Winnie. | Skoro pa si dio obitelji.
{21501}{21577}Kuæa je prekrasna. | Sviða mi se ureðenje vrta.
{21579}{21608}Hvala ti.
{21610}{21670}Kupila sam prvu kuæu | i jedva èekam urediti vrt.
{21672}{21725}Onda moraš upoznati | našeg krajobraznog arhitekta.
{21727}{21774}Mislim da se ne bi bavio | tako malenim poslom.
{21776}{21841}Pitat æemo ga. Briane, doði na trenutak.
{21843}{21883}Ma nisam još spremna.
{21885}{21973}- Briane, ovo je naša dobra prijateljica... | - Kenya, znam. Upoznali smo se.
{21975}{22020}Mislila sam da si arhitekt.
{22022}{22050}Krajobrazni arhitekt.
{22052}{22133}Kenya je kupila svoju prvu kuæu | i želi srediti vrt.
{22135}{22181}Možda bi joj ti mogao pomoæi.
{22183}{22226}Ili nekoga preporuèiti ako si prezaposlen.
{22228}{22276}Mislim da je Kenya prezaposlena.
{22278}{22340}Sigurno æe pronaæi vremena. | Upravo se divila tvojemu radu.
{22342}{22370}Zbilja?
{22372}{22416}- Lijepo je. | - Hvala.
{22418}{22459}Treba te, Briane.
{22461}{22548}Isprièavam se, | idem podsjetiti kæer da je još uvijek Cahan.
{22550}{22605}- Izgledaš prekrasno. | - Hvala.
{22647}{22733}Imam tek mali vrt | i nemam baš mnogo sredstava, stoga...
{22735}{22798}U redu je. Posao je posao.
{22800}{22906}Nazovi me ako budeš spremna.
{22918}{22950}Stoj mi dobro.
{24411}{24452}Što to èiniš?
{24666}{24722}Morat æeš ga ostaviti u autu. Ne ljubim pse.
{24724}{24775}Ni ja. Samo smo dobri prijatelji.
{24811}{24862}Jesi me.
{24864}{24898}- Bog, kako si? | - Dobro.
{24900}{24926}Ne ljubiš pse, je li?
{24928}{24984}Ne volim pseæe dlake po kuæi.
{24986}{25047}- Nadam se da nije problem. | - U redu je.
{25049}{25123}Èuo si, Max? Ne voli pse. | Morat æeš prièekati u autu.
{25125}{25158}Žao mi je.
{25160}{25222}Idemo, Max! Upadaj!
{25224}{25263}Bravo.
{25265}{25296}Sjajan je.
{25298}{25353}- Otraga. | - Da.
{25484}{25529}Hvala ti što si došao...
{25531}{25602}iako sam se ponijela ružno prema tebi.
{25638}{25691}U redu je.
{25721}{25766}Što ti se èini?
{26071}{26101}Pa...
{26594}{26636}Jedno je sigurno.
{26638}{26671}Trebaš me.
{26691}{26735}Predložit æu ti nekoliko rješenja.
{26737}{26815}Vidio sam da ti se kod gðe Cahan | svidjela fontana...
{26817}{26895}pa pretpostavljam | da æe ona biti središte vrta.
{26904}{26953}- Fontana? Sviða mi se to. | - U redu.
{26955}{26987}Ali ne mogu si je priuštiti.
{26989}{27031}Struja, troškovi...
{27033}{27091}Ma izvest æemo to veæ nekako. | Moraš imati fontanu.
{27093}{27173}Kad se vratiš kuæi s posla | ispružit æeš se na ležaljci...
{27175}{27241}slušat æeš vodu kako žubori | i popiti èašu vina.
{27279}{27379}- Ovo ti je važno? | - Ne. Uopæe.
{27381}{27440}Izbacit æemo to. Puteljak.
{27461}{27534}Ovdje bismo mogli nešto izgraditi.
{27536}{27603}Skriti sve bugenvilijom...
{27634}{27667}ili glicinijom.
{27686}{27731}Sviða mi se. Lijepo je.
{27755}{27819}Trebaš vidjeti jedan vrt | koji sam nedavno sredio. Sjajan je.
{27821}{27919}Dvorište i puteljak poploèani | su šarenim kamenom.
{27936}{28025}Sjajno sam riješio rasvjetu i glazbu.
{28035}{28066}Rado bih to vidjela.
{28068}{28122}Imaš li sad vremena? Rado bih ti pokazao.
{28124}{28152}- Sada? | - Da.
{28154}{28247}Ne mogu. Imam previše posla. | Imaš li koju fotku?
{28249}{28296}One nisu dovoljan prikaz.
{28298}{28339}Danas doista ne mogu.
{28341}{28371}Blizu je.
{28373}{28439}Odvest æu te onamo | i odmah vratiti kuæi. Obeæavam.
{28859}{28902}Prekrasan dan.
{28985}{29050}Smijem li se naèas zaustaviti | u gradskom vrtu?
{29052}{29079}Molim?
{29081}{29143}Ovdje smo. Samo æu nešto ostaviti.
{29335}{29380}Brzo æu.
{29405}{29454}Možeš uæi ako želiš.
{29456}{29497}Vidi što sam ti donio, Maria.
{29499}{29550}- Mijo! | - Hej!
{29552}{29612}- Drago mi je što te vidim. | - I meni.
{29614}{29667}- Kako si? | - Más o menos.
{29669}{29723}No posao mi ide dobro.
{29725}{29774}- Èula sam za Penelope. | - Da.
{29776}{29811}Glupaèa jedna.
{29821}{29888}- Znao si da æe tako završiti? | - Da.
{29891}{29917}Kako?
{29922}{29971}Iskreno?
{29973}{30039}Penelope je dobra, ali ne i prema meni.
{30041}{30103}- Dobro si? | - Da.
{30115}{30149}Zgodna je.
{30249}{30288}- U kosi mi je pauk. | - Što?
{30290}{30320}- U kosi mi je pauk. | - Samo malo.
{30322}{30372}- Izvadi ga! | - Èekaj.
{30374}{30417}Nema nièega.
{30419}{30479}Samo diši.
{30481}{30516}Diši.
{30567}{30603}Diši.
{30678}{30715}Sigurno me smatraš luðakinjom.
{30717}{30798}Ma ne. Samo ne ljubiš pauke.
{30819}{30851}Ni pse.
{30853}{30918}Imam cijeli popis. Beskrajan je.
{30940}{30973}Znaš...
{31003}{31095}izradit æu neke nacrte | pa vidi hoæe li ti se svidjeti.
{31097}{31141}Odluka je tvoja.
{31143}{31244}Budeš li imala svojih zamisli | samo me nazovi. Može?
{31246}{31299}Razmislit æu.
{31301}{31376}Još uvijek se navikavam na hipoteku.
{31378}{31407}Bez žurbe.
{31436}{31463}U redu.
{31478}{31507}Hvala.
{31612}{31666}Laku noæ. Èvrsto spavaj.
{31669}{31697}Hvala.
{31699}{31749}Èuvaj se pauka.
{31948}{31976}Kenya?
{31978}{32035}Donio sam ti poklon za posao s Pinom.
{32062}{32124}Izvrsno. Moje osobno raèunalo.
{32126}{32155}Bill Lebree.
{32157}{32217}- Dobro došao. Odmah æu te uposliti. | - Na raspolaganju sam.
{32219}{32267}Imat æu pismene obveze, postupak...
{32269}{32299}i traženi popis oko 15 sati.
{32301}{32363}Trebat æe mi natrag do èetvrtka, | najkasnije do 10.30.
{32365}{32420}U meðuvremenu pregledaj ovo...
{32422}{32491}prouèi pad vrijednosti i amortizaciju.
{32493}{32528}Nema problema.
{32530}{32579}Ovdje sam ako vam išta zatreba.
{32581}{32612}Hvala.
{32617}{32646}Kenya...
{32648}{32705}Znam koliko je važan ovaj posao, Edwine.
{32707}{32745}- Ne brini se. | - Nisam zabrinut.
{32747}{32788}Imamo potpuno povjerenje u tebe.
{32790}{32860}Zato bismo te htjeli kao partnericu.
{32862}{32892}Sjajno.
{32894}{32936}Ukoliko dobro obaviš posao s Pinom.
{32938}{32968}Naravno.
{32970}{33029}Ovo su dobre vijesti.
{33031}{33063}Èim glavešine odluèe...
{33065}{33113}imat æeš posla preko glave.
{33115}{33146}Jedva èekam.
{33148}{33212}Za gðicu Kenyu McQueen.
{33214}{33244}Za mene?
{33246}{33292}- Roðendan ti je? | - Nije.
{33390}{33422}Od koga je?
{33517}{33551}Mojeg krajobraznog arhitekta.
{33582}{33624}Ne! Van!
{33626}{33692}Mièi se, Max. Natrag u auto.
{33694}{33750}Upadaj! Idemo, Max!
{33817}{33895}Oprosti. Pobjegao je iz auta.
{33897}{33966}Ubuduæe se pobrini da ne bježi.
{33968}{34000}U redu.
{34075}{34118}Prolila sam tvoju kavu.
{34580}{34654}Hvala. Lijepo od tebe.
{34656}{34743}Vruæa, bez pjene. | I sebi sam spravljala jednu.
{34745}{34785}Lijepo od tebe.
{34787}{34840}Što misliš, kad æeš završiti s poslovima?
{34842}{34917}Ovdje smo tek dva dana. | Veæ ti je muèno od nas?
{34919}{34957}Ne, samo sam...
{34962}{35031}Kad završiš...
{35033}{35070}mogla bih prirediti zabavu.
{35072}{35121}- Za dobrodošlicu? | - Da.
{35123}{35181}Sjajna zamisao.
{35183}{35222}Trebaš se opustiti.
{35265}{35300}Toliko je oèito?
{35357}{35440}Subota je, a ti si u odijelu...
{35540}{35612}Imam mnogo posla.
{35614}{35673}Upravo sam saznala | da æu postati partnerica.
{35675}{35752}Zavidan uspjeh. Èestitam.
{35754}{35819}- Još se nije dogodilo. | - Ali hoæe.
{35885}{35924}Bolje da se vratim.
{35998}{36076}A što æeš ti ovdje u subotu?
{36086}{36133}Naporno radim...
{36148}{36220}za jednu vrlo zaposlenu damu | koja zaslužuje zabavu.
{36230}{36262}Hvala na kavi.
{37237}{37267}Što je?
{37269}{37296}Što je?
{37335}{37364}- Bog. | - Bog.
{37408}{37464}Tko ti je onaj pustolov?
{37466}{37504}- Bog. | - Bog.
{37520}{37600}Oprosti. Stacy, ovo je moja sestra Kenya.
{37602}{37652}Èast mi je. Doista.
{37694}{37750}- Evo novca za mamin roðendan. | - U redu.
{37752}{37789}Imam alat za ovo.
{37791}{37841}Nisi mi rekla da sreðuješ vrt.
{37843}{37905}Zar ti moram baš sve reæi?
{37936}{38001}Briane, ovo je moj mlaði brat Nelson.
{38024}{38069}Drago mi je.
{38101}{38140}Što ima?
{38142}{38200}Oprosti mu. Rodio se drzak.
{38214}{38255}Pa to ti je samo radnik.
{38265}{38303}- Nelsone! | - Što je sad?
{38368}{38442}Što ja to èujem?
{38444}{38486}Sviða ti se bijela boja?
{38544}{38602}Navijaš za drugu ekipu?
{38608}{38664}Spavaš li s neprijateljem?
{38677}{38727}Bio je to spoj naslijepo.
{38731}{38767}Nisam znala.
{38780}{38810}Zašto ti to uopæe govorim?
{38812}{38872}Spoj naslijepo? Pa to je glupo!
{38874}{38952}Izlaziš na spoj naslijepo s bijelcem...
{38954}{39042}Nisi valjda toliko oèajna? Što je s tobom?
{39051}{39124}Ne želim da mi se zadire u privatnost.
{39137}{39191}Ovo je ludnica!
{39193}{39257}- Tvoja prva kuæa. | - Hvala.
{39264}{39309}Smijem li na WC?
{39311}{39366}Da. Onamo.
{39455}{39497}Nadam se da ima èarobnu ribicu.
{39499}{39557}Meni prigovaraš?
{39559}{39640}Treba ti muškarac.
{39642}{39712}- Ja æu ti nekoga pronaæi. | - Meðu svojim prijateljima? Ma daj.
{39714}{39788}Trebaš biti malo dostupnija.
{39794}{39856}- Što to znaèi? | - Zainteresiranija.
{39873}{39915}Otvorenija, opuštenija.
{39917}{39969}Trebaš ublažiti svoje kruto držanje.
{39971}{40020}Pokušala sam. Loše je završilo.
{40025}{40072}Uèini mi uslugu, srce.
{40074}{40160}Možeš li mojoj sestri udijeliti koji savjet | kako uloviti muškarca?
{40162}{40222}Naravno. Imam nekoliko dobrih caka.
{40229}{40275}Treba ti dobar nutricionist.
{40277}{40333}Ne bi vjerovala | kako dobra dijeta može pomoæi.
{40335}{40375}Meni je promijenila život.
{40377}{40430}Hvala.
{40432}{40473}Kako ste se uopæe upoznali?
{40475}{40505}Vozila sam se...
{40507}{40560}a on se zaustavio kraj mene | u svojem novom Jaguaru.
{40562}{40642}Nisam mogla vjerovati. Jaguar XJS!
{40644}{40687}- Ideš! | - Ideš!
{40689}{40723}- Ideš! | - Ideš!
{40725}{40757}- Ideš! | - Ideš!
{40759}{40821}Kad æu ga ja malo provozati?
{40823}{40865}Nikad.
{40867}{40920}Nikad ti ga ne bih posudio.
{40955}{41040}Želim posaditi mješavinu kalifornijskih | i višegodišnjih biljaka...
{41042}{41106}da stvorim mediteranski ugoðaj.
{41115}{41156}Slažeš se sa mnom?
{41160}{41204}Ionako ne razlikujem biljke.
{41206}{41288}Kalifornijske domaæe biljke | najbolje uspijevaju u ovakvome okolišu.
{41290}{41387}A višegodišnje cvjetaju | u odreðeno doba godine.
{41389}{41448}Mijenjaju energiju i izgled vrta.
{41450}{41493}Pogledaj ovo.
{41532}{41594}Mediteranska lavanda, moraš je imati.
{41596}{41640}Ima iscjeljujuæe moæi.
{41642}{41715}U prošlosti su se njome štovali bogovi.
{41786}{41860}- Kako si upao u ovaj posao? | - Preko mojeg oca.
{41865}{41932}Imao je vrt u svim kuæama | u kojima smo živjeli.
{41934}{42000}Svakog sam mu proljeæa | pomagao saditi biljke.
{42002}{42074}Isprva sam to mrzio. | Potom sam poèeo uživati.
{42076}{42158}Bio sam jedini 12-godišnjak u kvartu | koji se znao brinuti o orhidejama.
{42160}{42243}- S 12 si veæ otkrio svoj poziv? | - Ma ne, nisam odmah.
{42245}{42330}Nakon faksa sam u jednoj tvrtki | osmišljavao reklame.
{42332}{42383}Radio sam to šest godina.
{42385}{42419}Oglašivaè, ha?
{42421}{42490}Da. Odijelo, kravata i sve što ide s time...
{42499}{42533}Mrzio sam to.
{42541}{42633}Jednog sam dana u ured ponio orhideju.
{42635}{42701}Potom su biljke jednostavno prevladale.
{42703}{42789}Provodio sam više vremena | brinuæi se za njih, nego za posao.
{42805}{42848}Èinilo se kao pravi izbor.
{42859}{42946}Što kažeš na ovo za podlogu?
{42957}{43009}- Izgleda dobro. | - Odlièno.
{43219}{43276}Evo moje slatkice!
{43278}{43337}Uvijek morate raditi scenu?
{43339}{43399}- Sretan roðendan, mama. | - Hvala, srce.
{43401}{43464}Evo i Nelsona! Bog, srce.
{43478}{43534}- Drago mi je što te vidim, sine. | - Oèe.
{43650}{43688}Isprièavam se.
{43690}{43764}Kiki, ovo su moji roditelji. | Dr. I gða McQueen.
{43766}{43795}Drago mi je.
{43797}{43845}Ovo je moja sestra Kenya. | Kenya, ovo je Kiki.
{43847}{43874}Drago mi je.
{43876}{43936}Haljina vam je prekrasna.
{43938}{43988}Sviða vam se? Sama sam je dizajnirala.
{43990}{44027}Nisam je ni šivala, samo se zakaèi.
{44029}{44079}Kamo je nestala ona s umecima? Stacy?
{44081}{44126}Kiki ju je zamijenila.
{44147}{44234}Kako ste se proveli u La Quinti?
{44236}{44309}Odlièno. Za trodnevni put | mama je ponijela pet torbi.
{44311}{44385}Bio je to spa vikend.
{44387}{44428}Morala sam imati izbora.
{44430}{44511}Jedna od torbi bila je njegova za golf.
{44513}{44562}Èime se baviš, Kiki?
{44564}{44671}Sad radim u fotokopirnici, | ali ove æu jeseni upisati dizajn.
{44686}{44781}Mi smo visokoobrazovana obitelj, | kao što vam je Nelson sigurno rekao.
{44783}{44853}Dr. McQueen upravitelj je neurokirurgije | u bolnici Cedars Sinai.
{44855}{44885}Dosta je, Joyce.
{44887}{44975}Moja kæi uskoro æe postati partnerica | u Baily, Banks i Biddle.
{44977}{45028}Benson, Baily i Becks, majko.
{45030}{45065}Toèno, Becks.
{45067}{45119}A ponosimo se i našim dragim Nelsonom...
{45121}{45212}koji se upravo zaposlio na upravnom odjelu | u 20th Century Fox.
{45223}{45287}Upravnom odjelu? | Mislila sam da si producent.
{45289}{45325}Bože saèuvaj!
{45337}{45403}Bio je najbolji student prava.
{45405}{45483}Jaguar je poklon za diplomski | od njegova oca.
{45517}{45573}Tata ti je kupio Jaguara?
{45745}{45821}Mama, Kenya izlazi s bijelcima.
{45900}{45952}Imala sam jedan spoj naslijepo...
{45960}{46043}koji je prošao loše, | a sad sam ga zaposlila da mi sredi vrt.
{46061}{46102}Sreðuje vrt.
{46104}{46157}Znaèi to je bio onaj pustolov?
{46159}{46207}Znao sam da mi nešto ne štima.
{46209}{46278}Vrlo je ljubazan i odlièno se zabavljamo.
{46280}{46351}- Mama! | - Sviða ti se ureðivanje vrta?
{49011}{49054}Radiš dokasna?
{49056}{49117}Pokušavam iæi ukorak s tobom.
{49142}{49201}Lijepo je.
{49206}{49254}Bit æe prekrasno.
{49309}{49355}Dolazi ovamo, Max.
{49357}{49389}U redu je.
{49697}{49733}Gladna sam.
{49787}{49827}Želiš da naruèimo nešto?
{49969}{50018}Sve je u drap boji.
{50025}{50112}Unijet æeš malo življe boje?
{50156}{50193}Što imaš protiv drap boje?
{50195}{50228}Pa...
{50247}{50276}sigurna je...
{50297}{50335}i bezlièna.
{50337}{50394}Podsjeæa na hotel.
{50405}{50450}Ne odražava tvoju osobnost.
{50509}{50597}Moja majka misli | da su žive boje za djecu i kurve.
{50621}{50661}A što ti misliš?
{50721}{50757}Ne znam.
{50773}{50842}Boje unose energiju.
{50848}{50881}Bude èula.
{50883}{50946}Mogu te rastužiti i razveseliti.
{50948}{50981}Uèiniti hrabrom.
{50983}{51032}Nisam hrabra.
{51034}{51069}Sigurna si?
{51078}{51141}Mislim da nemaš vremena | dovoljno se upoznati.
{51143}{51188}Uvijek radiš.
{51198}{51304}Neki od nas trebaju naporno raditi | kako bi ostali u igri.
{51337}{51377}Ne bi shvatio.
{51379}{51407}Iskušaj me.
{51425}{51486}Veèeras si pun savjeta, g. Sveznajuæi.
{51488}{51561}- Možda bih ti ja trebala udijeliti koji. | - Pucaj.
{51563}{51620}Užasno posluješ.
{51622}{51666}Nisi tražio predujam.
{51668}{51740}Uložio si toliko vremena da ti se posao | veæ novèano ne isplati.
{51742}{51832}Nije ti možda sinulo | da imaš poseban popust?
{51834}{51904}Nisam financijski struènjak poput tebe...
{51906}{52014}no uspješno vodim ovaj posao | veæ šest godina.
{52021}{52121}Želiš li pregledati moje poslovanje...
{52123}{52183}slobodno izvoli.
{52206}{52235}Imaš moje odobrenje.
{52237}{52294}Vjeruj mi, preskupa sam za tebe.
{52509}{52586}Pretpostavljam da ne ljubiš bijelce.
{52702}{52760}Više volim crnce.
{52780}{52847}To nije predrasuda, veæ izbor.
{52870}{52941}Dakle, tvoj izbor je imati predrasude.
{52957}{53020}- A ti? | - Žene su žene.
{53050}{53092}Neke su otrovnice, neke nisu.
{53094}{53148}- Izlazio si s crnkinjama? | - Sa svakakvima.
{53150}{53202}- Zavodnik, znaèi. | - Ne.
{53218}{53252}Samo sam...
{53279}{53319}Krajobrazni arhitekt.
{53348}{53415}Surovu zemlju pretvaram u plodnu.
{53494}{53562}Prilièno je kasno.
{53601}{53669}- Trebaš pomoæ s ovim? | - Ne, hvala.
{53672}{53749}- Hvala na veèeri. | - Nema na èemu.
{53751}{53801}Vidimo se sutra.
{54015}{54041}Bog.
{55078}{55143}Pustio sam ih da odu ranije. Praznik je.
{55152}{55218}- Idem i ja. | - U redu.
{55222}{55295}Ali ti ideš sa mnom.
{55320}{55386}Zašto? Moramo kupiti još nešto za vrt?
{55388}{55427}Ne, idemo planinariti.
{55429}{55470}Samo jednodnevni izlet.
{55502}{55576}- Pozivaš me na spoj? | - Pozivam te na izlet.
{55578}{55668}U oba sluèaja odgovor je ne. | Ne volim planinarenje.
{55767}{55798}Pismo ili glava?
{55814}{55931}Tko bi pametan izlazio po ovakvoj vruæini?
{55936}{55973}U èemu je svrha?
{55975}{56027}Ne gledaj dolje, veæ gore.
{56029}{56064}Tražim zveèarke.
{56066}{56134}Ne brini se za njih, | veæinu ih pojedu planinski lavovi.
{56136}{56169}Baš si zabavan.
{57665}{57728}- Èovjeèe. | - Sranje! Moja kosa!
{57772}{57854}- Ubit æu te! | - Nisam znao da æe kišiti, kunem se.
{59356}{59451}Nemoj misliti da ovo nekamo vodi.
{59496}{59529}Laku noæ.
{60839}{60888}Zašto su te nazvali Kenya?
{60908}{60947}Ondje sam roðena.
{60965}{61045}Moj otac radio je ondje kao lijeènik.
{61079}{61125}Majka me htjela nazvati Tiffany.
{61127}{61234}Mrzila je istoènu Afriku. | Jedva se èekala vratiti u SAD.
{61241}{61272}Zašto?
{61281}{61337}Ne znam. To je moja majka.
{61371}{61431}Nije imala gdje trošiti novac.
{61510}{61583}Osim toga, imala sam astmu kao djevojèica.
{61586}{61648}Nije imala povjerenja u njihove bolnice.
{61667}{61705}Astmu?
{61734}{61787}Zato mrziš kukce...
{61800}{61832}pauke...
{61865}{61904}visoku travu...
{61919}{61950}i planinarenje.
{61952}{62004}Da, držali su me pod zvonom.
{62148}{62227}Mala Kenya zatvorena u kuæi | dok se ostala djeca igraju.
{62253}{62299}Slika...
{62365}{62416}i ponavlja jednadžbe.
{62421}{62498}- Patetièna sam, zar ne? | - Nisi.
{62568}{62615}Prekrasna si.
{62726}{62762}Prekrasna.
{62956}{63012}Smijem li te još nešto pitati?
{63171}{63216}Možeš li skinuti ovo?
{63291}{63329}Kako to misliš?
{63331}{63399}Nije perika, zar ne?
{63419}{63489}Ali nije ni tvoja prava kosa.
{63546}{63618}- Ne mogu vjerovati da si me to pitao. | - Samo sam radoznao.
{63620}{63674}To su umeci ako te baš zanima.
{63676}{63709}Nisi li izlazio s crnkinjama?
{63711}{63752}- Imale su pravu kosu. | - I ja je imam.
{63754}{63791}- Ispod? | - Da!
{63793}{63865}- To ti je samo prièvršæeno? | - Da.
{63878}{63933}Slušaj, mislim da bi trebao otiæi.
{63935}{63997}Ovo neæe iæi. Ne znam što mi bi.
{63999}{64057}Pogriješili smo, molim te otiði.
{64059}{64131}- Zato što sam te pitao za kosu? | - Zbog svega.
{64159}{64205}Od danas...
{64207}{64282}više neæu trebati tvoje vrtlarske usluge.
{64319}{64369}Baš si mustra, Kenya McQueen.
{64371}{64397}Izlazi!
{64447}{64479}Oprosti ako sam te uvrijedio.
{64481}{64567}Samo me zanimalo | kako izgledaš potpuno naga.
{64708}{64751}- Što si uèinila? | - S kim?
{64753}{64819}Znam. Ali...
{64822}{64881}Kišilo je i planinarili smo.
{64883}{64945}- Planinarila si? | - Zanijeli smo se.
{64947}{64998}Vrijedi li èemu u krevetu?
{65000}{65036}- Nedra! | - Što?
{65038}{65078}- Ne budi sirova! | - Molim te!
{65080}{65113}- Onda, kakav je? | - Vidiš?
{65115}{65165}Da.
{65178}{65229}- E tako reci. Ima velik... | - Da.
{65239}{65274}Ali gotovo je.
{65285}{65313}Gotovo je.
{65320}{65376}Bilo je to za jednu noæ. | Usto sam ga i otpustila.
{65378}{65424}- Molim? | - Nikad ne bismo uspjeli.
{65426}{65460}Naravno da ne!
{65462}{65512}- Ne moraš se udati za njega! | - Udaj se za njega.
{65514}{65574}- Samo se dobro... | - Poševi kako spada.
{65576}{65662}- Barem jednom kako treba. | - Opusti se.
{65823}{65856}Izvadite ih.
{66501}{66559}Došao sam po ostatak stvari.
{66600}{66632}Znao sam.
{66665}{66691}Što?
{66716}{66755}Prekrasna si.
{66832}{66872}Ne brini se za plaæanje.
{66874}{66900}Èekaj.
{66975}{67006}Ne odlazi.
{67171}{67219}Znam da si osjetljiva na boju kože.
{67221}{67297}Iæi æemo polako.
{67365}{67435}Nitko ne treba znati za nas.
{67447}{67503}Bit æe to naša mala tajna.
{68816}{68843}Ne mièi se.
{70265}{70340}Ne možeš mi reæi da bijelci | nisu pomalo opsjednuti psima.
{70342}{70376}Imaju pseæe hotele, psihijatre.
{70378}{70436}Ljubite ih u usta. Spavaju s vama.
{70438}{70477}Pogledaj tebe i Maxa.
{70479}{70537}Imate svoj jezik. "Trèi, Max."
{70539}{70604}- Idemo, Max. | - Oprosti.
{70606}{70657}Oprosti, Max. U redu je.
{70659}{70745}Tvoja susjeda Lillian ima kuju Selinu.
{70752}{70802}Ta kuja svaki dan ima novu opravu.
{70804}{70868}Èak je i šminka.
{70870}{70929}- Ona se ne raèuna. | - Ma nemoj.
{70931}{70987}Ne slažem se. Kušaj ovo.
{71074}{71130}Uèini to još jednom, molim te.
{71141}{71193}To želim èuti.
{71195}{71260}Trebate cijeniti neke stvari.
{71262}{71317}Pogledajte koliko je ovdje lijepih crnaca.
{71319}{71393}Zaplješæite im.
{71417}{71488}Dobri komadi.
{71492}{71554}Znate li zašto su mi oni posebno dragi?
{71556}{71620}Jer društvo ih uvijek osuðuje.
{71622}{71667}"Neradnici su."
{71669}{71726}A kad rade "ne brinu se za djecu".
{71728}{71787}A kad imaju djecu | "ne provode kvalitetno vrijeme s njima".
{71789}{71852}No znate što im ja onda kažem?
{71854}{71915}Sjeæate li se snajperiste Beltwaya?
{71956}{72022}On je kvalitetno provodio vrijeme | sa svojim sinom.
{72024}{72074}Vodio ga je sa sobom na posao.
{72076}{72121}Pouèavao ga je poslu.
{72144}{72244}Ne možete donositi zakljuèke o cijeloj rasi | na temelju jednog sluèaja.
{72256}{72294}Volim svoju crnu braæu.
{72296}{72344}Zato sam izlazila samo s njima.
{72346}{72391}Nikad s momcima druge rase.
{72393}{72452}Ma jesam.
{72454}{72500}S Afrikancem.
{72519}{72619}Bio je toliko dobar | da poslije nisam znala kako se zovem.
{72621}{72652}Bilo je nevjerojatno.
{72654}{72708}Meðutim, nikad nisam izašla s bijelcem.
{72710}{72763}Ne da me ne privlaèe.
{72765}{72812}Jer vidim da ovdje ima zgodnih komada.
{72814}{72861}No moj jedini problem s njima je...
{72863}{72923}što nikad ne znaju prekinuti s djevojkom.
{72936}{72989}Gledam ja dokumentarce o ubojicama.
{73004}{73076}Kad izaðete s njima, sutradan nestanete.
{73089}{73120}Svi vas traže.
{73122}{73190}A vi u zamrzivaèu, izrezani na komadiæe...
{73192}{73250}spremni za roštiljanje.
{73258}{73345}Ja sam Sommore. Bili ste sjajni, hvala vam.
{73570}{73662}Bili smo u New Orleansu, Charlestonu, | zemlji vina.
{73664}{73719}Ondje se dobro jede, | Walter radi toga voli putovati.
{73721}{73764}- Da. | - Istinski gurman.
{73766}{73844}Udebljala sam se oko 2 kg, | ali odlièno se zabavljam.
{73856}{73900}Èujte i poèujte!
{73904}{73968}Bi li ikada rekla da æe pasti...
{73970}{74011}na nekoga s pregaèom? Reci, Kenya.
{74013}{74080}Pokazao si mi put, zar ne?
{74240}{74318}Èini se da se i vas dvoje zabavljate.
{74320}{74368}Nikako ne mogu dobiti Kenyu.
{74370}{74420}Prije se javljala veæ nakon prvog zvona.
{74422}{74504}- Pa... | - Radim na važnom poslu, tako da...
{74559}{74585}Da.
{74595}{74623}Kenya.
{74635}{74708}Priznaj da se dobro zabavljaš.
{74710}{74799}Imam dar za tebe.
{74807}{74884}Buduæi da sad voliš življe boje, | nadam se da æe ti se svidjeti.
{74886}{74959}- Hvala ti. | - Nema na èemu.
{74967}{75013}- Prekrasan je. | - Prekrasan je.
{75028}{75085}- To je moja pjesma. Idemo plesati. | - U redu.
{75087}{75154}Hajde da vas vidimo.
{75646}{75695}Èujem da se baviš vrtlarstvom.
{75697}{75738}Toèno.
{75740}{75785}I da si napaljen na nju.
{75787}{75849}- Molim? | - Napaljen si na nju.
{75877}{75936}Èiniš to sa svakim klijentom?
{75938}{76000}- Izvodiš ih van? | - Ne. Zašto?
{76002}{76052}Vidiš li onu ženu?
{76054}{76127}Volim je. A i Kenya je voli.
{76129}{76209}Ona joj je poput sestre, | a meni poput šurjakinje.
{76211}{76260}- Kužiš me? | - Da.
{76262}{76331}Ona nam je poput obitelji. Èuvamo je.
{76368}{76413}- Kužiš? | - Da.
{76415}{76444}Odlièno.
{76446}{76477}Kuži li što?
{76504}{76565}- Je li? | - Ma ništa.
{76567}{76628}- O èemu ste razgovarali? | - O tebi.
{76640}{76687}Bit æu gore u baru, Sommore.
{76689}{76723}Hej!
{76725}{76782}- Kako si, srce? | - Odlièan nastup.
{76784}{76816}Hvala vam što ste došli.
{76818}{76847}Moja djevojka Cheryl.
{76849}{76886}- Bog, kako si? | - Drago mi je.
{76888}{76920}- Kenya. | - Bog.
{76922}{76955}- Brian. | - Bog.
{76957}{77031}Ponijeli ste svjetlo sa sobom.
{77051}{77152}Ili ti se drago ševiti s bijelcima | ili je to tvoj socijalni radnik.
{77154}{77184}Ne krivim te.
{77219}{77282}Jasne su mi sve neprikazane obveze.
{77284}{77314}I niste zabrinuti?
{77316}{77388}- Vidjeli ste isplative akcije? | - Ovdje su.
{77390}{77422}Pregledala sam ih. Jack...
{77424}{77492}Doista mi treba ova javna ponuda.
{77498}{77567}Znam, ali ugovor mora imati smisla.
{77581}{77630}Vidio si ovo, Bille?
{77640}{77675}Naravno da jest.
{77677}{77729}Pripremio je sve spise prije moje procjene.
{77731}{77826}Znam da to žarko želiš, ali ovako te štitim.
{77828}{77868}- Jack. | - Edwine.
{77870}{77920}- Još mi duguješ partiju golfa. | - Istina.
{77922}{77969}Sjedni s nama na trenutak.
{77971}{78004}Rado, ali èeka me sastanak.
{78006}{78055}U dobrim si rukama. Kenya zna svoj posao.
{78057}{78134}Ipak bih volio da i ti pogledaš. | Možeš li svratiti poslije sastanka?
{78136}{78189}Naravno. Ne smeta ti, Kenya?
{78191}{78274}Ni u kom sluèaju. Jack cijeni tvoje mišljenje.
{78276}{78322}Svi smo ovdje da ugodimo klijentu.
{78324}{78358}Siguran sam.
{78515}{78576}Gðica Kenya McQueen i gost
{78602}{78652}Organizacija Pacific Cotillion
{78920}{78953}Gledaj ovo.
{79048}{79088}Bože!
{79133}{79162}Èovjeèe!
{79188}{79218}Briane...
{79246}{79317}ovo je nevjerojatno.
{79415}{79444}Sve...
{79501}{79551}što sam oduvijek željela...
{79625}{79656}i više.
{79696}{79728}Hvala ti.
{79966}{79997}Težak dan?
{80021}{80051}Naporan.
{80097}{80141}Klijent je naporan.
{80172}{80267}Sumnja u svaki moj korak.
{80269}{80338}Trebam sve dvaput provjeriti.
{80345}{80393}Zbog "crnog poreza".
{80450}{80482}Crnog poreza?
{80505}{80601}Moraš raditi dvostruko više | da budeš jednak drugima.
{80605}{80665}Sigurno nisi paranoièna?
{80695}{80729}Nisam.
{80731}{80790}Onda æu i ja raditi subotom.
{80942}{80968}Hej.
{80995}{81048}Nemoj mi tako upadati, ne poznaješ me.
{81050}{81092}Mislio sam da ti treba pomoæ.
{81094}{81143}Želiš ukrasti moje tajne.
{81145}{81174}Eto što pokušavaš.
{81176}{81225}Prokužio si me. Istina.
{81227}{81289}Trebaš biti presretan...
{81291}{81342}što si uopæe pozvan na ovu crnaèku zabavu.
{81344}{81385}- I jesam. | - Kužiš me?
{81387}{81442}- Hej. | - Vidimo se poslije.
{81525}{81575}- Hej. | - Izgledaš prekrasno.
{81577}{81603}Bog.
{81644}{81678}Eno Lee.
{81680}{81714}Leah! Paule!
{81716}{81751}- Bog. | - Bog.
{81753}{81837}Tako mi je drago što vas vidim.
{81839}{81874}I meni.
{81876}{81917}- Vjenèanje je za nekoliko tjedana. | - Da.
{81919}{81953}- Ovdje je prelijepo. | - Hvala.
{81955}{81983}Pokazat æu ti fontanu.
{81985}{82040}- Prièala sam ti o njoj. | - Da.
{82042}{82109}- Obavio si sjajan posao. | - Hvala.
{82111}{82168}Uživao sam. Piæe?
{82170}{82214}Može. Sok.
{82216}{82264}Odmah.
{82293}{82337}Taj bijelac uopæe nije loš.
{82435}{82495}Opustila si se.
{82497}{82591}Imaš prirodnu kosu, pokazuješ svog deèka.
{82593}{82651}- Sladak je. | - Vrtlar je.
{82653}{82725}I to dobar vrtlar. Pogledaj samo oko sebe.
{82727}{82777}- Tony je sladak. | - Rastavljen je.
{82792}{82868}Ne tehnièki, ali ne žive zajedno.
{82870}{82910}- Suzzette. | - Molim vas.
{82912}{83008}Došao mi je u ordinaciju | s tim bolesnim djetetom.
{83019}{83061}I mišiæavim rukama.
{83069}{83149}Rekao je: "Treba nam pomoæ."
{83158}{83201}Što mi je bilo èiniti?
{83203}{83268}Opusti se i uživaj. Živjele!
{83270}{83334}Crncima se nikad ne pružaju dobre prilike.
{83336}{83419}- Da je to uèinio bijelac... | - Odmah bi ga unaprijedili.
{83421}{83509}- Tako je. Kužiš me. | - Razgovarate o "crnom porezu"?
{83552}{83581}Piæe?
{83588}{83637}Èekaj malo.
{83639}{83699}Pa on je doušnik.
{83714}{83794}Ranije mi je pokušao ukrasti | tehniku roštiljanja.
{83796}{83876}Èini mi se da želi otvoriti svoj restoran.
{83916}{83981}Isprièavam se...
{83983}{84069}Zašto me stalno tapšeš po ramenu | kao da si policajac?
{84140}{84168}Kenya!
{84547}{84610}Ovo lièi na javnu kuæu u Bangkoku.
{84613}{84655}- Bog. | - Bog, srce.
{84657}{84714}- Mislila sam da neæete doæi. | - Dr. McQueen.
{84716}{84743}Tata!
{84753}{84789}- Zdravo. | - Ja sam Brian.
{84791}{84830}Krajobrazni arhitekt.
{84832}{84894}Brian je i moj deèko.
{84935}{85016}- Drago mi je. | - Takoðer.
{85026}{85124}Zašto si se ošišala? Izgledala si prekrasno.
{85126}{85171}Bili su to umeci, majko.
{85179}{85229}Ali sjajno su ti pristajali.
{85231}{85299}Povedi me u kuæu da se malo osvježim.
{85340}{85410}- Vi ste ovo sredili? | - Da, pokazat æu vam.
{85412}{85460}Pogledaj ovo mjesto, Kenya.
{85462}{85571}Kakav je ovo umjetnièki stil? | Što ti se dogaða?
{85602}{85633}Ne odgovaraj.
{85721}{85767}Reæi æu ti sve mami.
{85769}{85804}- Bog, Nelsone. | - Bog.
{85832}{85931}Luna, moja sestra Kenya.
{85933}{85961}- Bog. | - Bog.
{85963}{86027}Mislim da sam pronašao onu pravu.
{86057}{86121}Èestitam.
{86123}{86202}Ma ne za mene, za tebe. | Tvojeg buduæeg muža.
{86204}{86266}U grad se upravo doselio | moj mentor s faksa.
{86268}{86320}Ne miješaj mi se u život, u redu?
{86322}{86395}Možeš li ga samo upoznati?
{86397}{86470}Kunem ti se da æeš mi biti zahvalna.
{86472}{86545}Pozvao sam ga ovamo veèeras.
{86547}{86597}- Što? | - Juèer.
{86599}{86647}Zadavit æu te.
{86649}{86706}Sad je veæ kasno, stigao je.
{86780}{86853}Ovo je zato što sam upao nepozvan.
{86855}{86895}Mark Harper.
{86907}{86957}- Što ima, mali? | - Kako ste, gospodine?
{86959}{87023}Mark me je prvi put zaposlio kao stažistu.
{87061}{87143}- Hvala. Bilo mi je drago. | - I meni. Napokon.
{87145}{87193}Nelson mi prièa o vama veæ godinama.
{87195}{87233}- Istina. | - Da.
{87235}{87306}- Upravo ste kupili kuæu? | - Da.
{87308}{87336}Lijepa je.
{87338}{87399}Upravo sam se doselio iz Phoenixa. | I ja tražim kuæu.
{87401}{87487}Možda mi možete pomoæi. | Provesti me po gradu.
{87529}{87621}Vjerojatno ste dosad sve istražili.
{87623}{87688}Ponešto znam...
{87690}{87744}ali nisam baš toliko mjerodavna.
{87746}{87784}- Ma nemojte. | - Što?
{87786}{87848}Samo se srami. Nema bolje od nje...
{87850}{87908}i može vam napraviti izraèun bilo èega.
{87910}{87965}Savršeno, jer to je upravo ono što mi treba.
{87967}{88011}Što kažete na iduæi tjedan?
{88081}{88122}Mogu vam se još javiti?
{88133}{88207}Naravno.
{88245}{88301}Poðimo do roštilja.
{88303}{88373}- Dobro mi je ovdje. | - Pokazat æu ti roštilj.
{88375}{88423}- Bilo mi je drago. | - Takoðer.
{88425}{88453}- Bog, srce. | - Bog.
{88455}{88497}- Kako si? | - Dobro.
{88517}{88609}- Tko je ono? | - Nelsonov prijatelj.
{88636}{88669}Lijepa biljka.
{88772}{88800}Kenya!
{88822}{88850}- Bog. | - Bog.
{88852}{88905}- Vidimo se poslije. | - U redu.
{88912}{88973}Upoznali smo Nelsonova mentora.
{88981}{89054}Nije li zgodan? I uglaðen.
{89056}{89097}Kaže da æeš mu pokazati grad.
{89099}{89165}- Pozdravi se, Joyce. | - Moramo iæi.
{89167}{89237}Zanimljivo ste sredili vrt, mladiæu.
{89239}{89272}- Hvala. | - Odlièan posao.
{89274}{89319}- Bilo mi je drago. | - Takoðer.
{89321}{89369}- Dobila si pozivnice za bal? | - Da.
{89371}{89421}Moraš doæi. Senator Abamaus Leeds je...
{89423}{89463}Poslije æemo o tome.
{89465}{89496}Idemo. Laku noæ.
{89498}{89537}- Laku noæ. | - Laku noæ.
{89604}{89630}Bog.
{89649}{89697}O kakvom je balu rijeè?
{89789}{89825}Imam sedamnaest godina.
{89827}{89890}Zvanièno se predstavljam društvu.
{89892}{89933}Ne mogu vjerovati da ljudi još to èine.
{89935}{89966}Shvaæaju to ozbiljno.
{89968}{90009}Mama i tata.
{90073}{90122}Moj pratilac, David Fontaine.
{90129}{90190}Njegov i moj otac | zajedno su studirali medicinu.
{90192}{90237}Moji su ga pozvali èak iz Atlante.
{90239}{90319}- Nisi mogla pronaæi mjesnog deèka? | - Majci je to bilo veoma važno.
{90321}{90391}"Kenya Denise McQueen | u pratnji Davida Fontainea...
{90393}{90481}"sina dr. Fontainea."
{90487}{90524}Bezvezarija.
{90589}{90652}Djed je umro prije dvije godine.
{90654}{90701}Baka i dalje živi u Baltimoreu.
{90703}{90769}- Zabavljaju se. | - Živjeli su za taj dan.
{90771}{90845}Bio je to dogaðaj godine | crnaèkog visokog društva.
{90990}{91029}Želiš iæi?
{91033}{91090}Iste je veèeri kao i zabava u gradskom vrtu...
{91092}{91142}ali mogu otkazati.
{91173}{91241}Ne znam. | Mislim da æu ove godine preskoèiti.
{91243}{91289}Zašto? Zbog mene?
{91297}{91349}Sjajan sam plesaè.
{91392}{91493}Ne znam. Ne bi nam bilo ugodno.
{91516}{91549}Nama ili tebi?
{91705}{91757}Idemo u krevet.
{91766}{91820}Sutra moramo na posao.
{91822}{91851}Znam.
{92021}{92069}- Kenya! | - Hej, Edwine.
{92071}{92131}Isprièavam se zbog onoga s Jackom Pinom.
{92133}{92219}Znam da je seronja. No, klijent je klijent...
{92221}{92267}i moramo se podrediti njegovim željama.
{92269}{92297}Toèno.
{92299}{92345}Znali smo da æeš uspjeti. Profesionalka si.
{92347}{92386}- Hvala. | - Hvala tebi.
{92483}{92560}Walter mi je otkrio tajnu | spravljanja lososa na roštilju.
{92562}{92598}Da pokušamo?
{92645}{92685}Može, svejedno mi je.
{92750}{92786}Dobro si?
{92797}{92834}Da.
{92857}{92954}Idu mi na živce bijelci s posla.
{92964}{93013}Možemo li jednu veèer | ne razgovarati o njima?
{93015}{93094}Bijelcima, braæi, sestrama. Svima njima.
{93132}{93174}Kako to misliš?
{93199}{93286}Samo veèeras ne. I ja sam imao ružan dan.
{93297}{93362}Želim se malo opustiti.
{93416}{93482}- Želiš da ne govorim o rasnim problemima? | - Ne.
{93484}{93549}Da budemo zajedno, | a da nikad ne razgovaramo o tome?
{93551}{93612}Molim? Pa samo o tome i razgovaramo.
{93614}{93668}Sad mi se ne da.
{93855}{93924}A kad ti odgovara?
{93941}{94017}Kad smo kod kuæe iza zatvorenih vrata | i kad zbijamo šale o tomu?
{94019}{94093}Ne, samo ne cijelo vrijeme. Neugodno mi je.
{94095}{94140}Oprosti, nisam tako odgojen.
{94142}{94197}Pa ti i ne trebaš naglašavati da si bijel...
{94199}{94267}jer te nitko na to ne podsjeæa svaki dan.
{94269}{94308}Primijetiš da si bijel...
{94310}{94400}jedino kad si u prostoriji s crncima. | A ja sam u prostoriji...
{94451}{94560}U svijetu sam bijelaca | i svaki me dan podsjeæaju da sam crna.
{94562}{94612}Ako ti ne mogu povjeravati | svoje frustracije...
{94614}{94684}- i moram li sve držati u sebi... | - Stani, Kenya.
{94686}{94765}Viša si upraviteljica | u jednoj od najbjelijih tvrtki u zemlji.
{94767}{94851}Diplomirala si na Stanfordu i Whartonu.
{94853}{94902}Imaš svoju kuæu. Mnogo zaraðuješ.
{94904}{94980}Više nego 98% ljudi, bijelih ili crnih. | Sigurno više od mene.
{94982}{95038}Prièaj mi onda malo o svojim frustracijama.
{95040}{95092}Ne želiš me slušati. Ne želiš èuti...
{95094}{95134}da kad se pojavim na sastanku...
{95136}{95194}uvijek osjeæaju nelagodu | kad otkriju da sam ja...
{95196}{95250}odgovorna za njihova | milijarderska ulaganja.
{95252}{95296}Radije bi to povjerili obiènom èinovniku.
{95298}{95377}Onome koji mi donosi kavu, | samo zato što je bijel.
{95379}{95416}Znaš li koliko je to ponižavajuæe?
{95418}{95474}Seronje su. Zaboravi ih.
{95476}{95532}Nemaju veze s nama.
{95534}{95611}Ako s tobom ne mogu razgovarati...
{95613}{95655}o rasnim problemima...
{95657}{95739}i ako sve trebam zadržati za sebe... | Poricati tko sam...
{95741}{95839}Nikad nisam tražio da išta porièeš. | Samo sam se htio odmoriti jednu veèer.
{95841}{95932}O tome i jest rijeè kad si crnac. | Nema odmora.
{95946}{95981}Slušaj.
{96012}{96091}Nikad neæu biti na pravoj strani rata | kojeg vodiš u glavi...
{96093}{96156}jer nisam crn i nikada to neæu biti.
{96158}{96253}Možda ovo nije ono što želiš. | Možda jednostavno neæe iæi.
{96255}{96292}Možda i neæe.
{96810}{96900}- Bog. | - Bog, Kenya. Nezgodno vrijeme?
{96932}{96984}Mogu se zamisliti ovdje.
{96992}{97024}Lijepo je.
{97057}{97144}No mislim da je cijena previsoka | s obzirom na kvart.
{97146}{97192}Ponudila bih 80 tisuæa manje.
{97194}{97275}I kad te pita što misliš, | nemoj djelovati prezagrijano.
{97277}{97327}Prièekaj do sutra.
{97329}{97361}- U redu. | - U redu.
{97363}{97422}Kako ste?
{97436}{97495}- Sviða mi se. | - A gði Harper?
{97497}{97580}- Ne, nisam... | - I gða Harper ima svoja pitanja.
{97584}{97636}No vratit æemo se sutra | s konaènim odgovorom.
{97638}{97707}- U redu. Imate moju posjetnicu. | - Hvala.
{97709}{97744}Gðo Harper.
{97800}{97828}Vidimo se.
{97957}{98003}Dosta o meni.
{98025}{98095}Kako se bijelci na poslu odnose prema tebi?
{98097}{98163}Znaš kakvi su. Uvijek me preispituju.
{98165}{98224}Da. "Crni porez".
{98229}{98261}No i dalje smo u igri.
{98263}{98319}Èinimo sve za napredak, zar ne?
{98355}{98388}Da.
{98460}{98544}Koliko èesto odlaziš u St Louis?
{98563}{98600}Svako malo.
{98602}{98688}U posljednje sam vrijeme vezan za stol. | Radim i vikendom.
{98690}{98764}Nikamo ne idem. Sad me žele i za partnera.
{98766}{98808}Poznato mi je.
{98810}{98856}I tebe?
{98858}{98905}Bravo!
{98907}{98954}Dva partnera.
{98959}{98985}Èovjeèe.
{99073}{99152}Nadam se da nije prerano...
{99154}{99240}ali želio bih se viðati s tobom.
{99248}{99311}Ali nisam neki šminker iz L.A.-a...
{99313}{99361}mnogo žena i užurbani život.
{99363}{99435}Volim iæi polagano. | Jedna po jedna djevojka.
{99437}{99483}Sad razmišljam o buduænosti.
{99533}{99628}Viðaš li se ti s nekim?
{99667}{99693}Sad?
{99746}{99780}Ne.
{99803}{99837}To sam želio èuti.
{99894}{99962}Da, majko. Sutra idem po haljinu.
{99996}{100045}U redu.
{100081}{100136}Nazvat æu te.
{100225}{100254}Max!
{100479}{100529}Pozvat æeš me unutra?
{100680}{100748}Nismo se èuli veæ dva tjedna.
{100750}{100792}Nisi li prvo trebao nazvati?
{100794}{100852}Radije sam došao.
{100876}{100950}Imaš pravo. Trebao sam prvo nazvati.
{100960}{101038}Nisam se javljao...
{101051}{101111}jer sam se osjeæao glupo.
{101113}{101168}Trebao sam te poslušati onaj dan.
{101170}{101246}Trebalo ti je rame za plakanje, | a ne još jedna kritika.
{101252}{101303}Ne znam što mi je bilo.
{101305}{101400}Jedan mi je radnik dao otkaz | pa sam bio pomalo frustriran.
{101402}{101474}Želim biti s tobom, Kenya.
{101478}{101548}Možemo razgovarati o bilo èemu.
{101550}{101651}Možda se neæu uvijek prepoznati | u svakoj prièi, ali bit æu suosjeæajan.
{101664}{101705}Vjeruješ li mi?
{101733}{101823}Bila bi prava šteta da se meðu nama | isprijeèi nešto tako beznaèajno.
{101825}{101898}Odustati jer je ponekad izazovno.
{101900}{101958}Zar nismo spremni na izazove?
{102040}{102080}Kenya, volim te.
{102164}{102212}Ne znam što bih rekla.
{102318}{102363}Da ti pomognem?
{102365}{102432}Upoznala sam nekoga.
{102502}{102577}Nisam nikoga tražila. | Jednostavno se dogodilo.
{102618}{102677}Da pogodim? Crnac je?
{102679}{102722}Nije samo to. Imamo štošta zajednièkog.
{102724}{102772}- Poslovan tip? | - Da.
{102791}{102848}Idemo, Max.
{102912}{102964}Nisam to planirala.
{102966}{103036}Ne brini se. | Samo smo se malo zabavljali, zar ne?
{103062}{103091}Da.
{103101}{103160}Poslat æu ti èek poštom.
{103162}{103201}Ne treba.
{103235}{103267}Stoj mi dobro.
{103428}{103495}Moraš se potpuno opustiti. Koljena.
{103497}{103577}Bokove. Ama baš sve.
{103579}{103623}Kakve to ima veze s udaranjem lopte?
{103625}{103680}Moraš imati dobar osjeæaj za udarac.
{103682}{103732}Kužiš? Poskakuj sa mnom.
{103734}{103802}Tako. Bravo.
{103804}{103851}Koljena opuštena. Tri stvari.
{103853}{103897}Stražnji zamah.
{103899}{103940}Dodir.
{103942}{103980}I nastavak.
{103982}{104028}Da vidim kako æeš nastaviti.
{104030}{104056}Ovako.
{104083}{104136}Bravo.
{104194}{104220}U redu.
{104424}{104468}Ovo je sjajno, zar ne?
{104921}{104978}Hvala. Sjajan posao, mladiæu.
{104984}{105039}Trebamo ovamo. Bog, mladiæu.
{105052}{105087}- Hvala. | - To je za vas.
{105089}{105124}- Za mene? | - Da.
{105126}{105193}- Ovo je Leina obiteljska sinagoga? | - Da.
{105195}{105245}Treba ti jarmulka.
{105335}{105363}Kenya.
{105382}{105410}Bog.
{105415}{105462}Ovo je Penelope.
{105478}{105535}- Vi ste Penelope. | - Drago mi je.
{105537}{105587}- Lijepa haljina. | - Hvala.
{105672}{105756}Isprièavam se, ovo je Mark.
{105781}{105831}- Brian. | - Drago mi je.
{105847}{105874}Bog.
{105894}{105984}Opet ste zajedno? Lijepo.
{106048}{106075}Da.
{106180}{106232}Drago mi je što te vidim.
{106385}{106428}Možda trebam pozvati lijeènika.
{106430}{106466}Ne, u redu je.
{106468}{106551}Astma mi se pojavi u najnezgodnije vrijeme. | Proæi æe.
{106553}{106600}Je li ovdje rijeè o Brianu?
{106602}{106648}Ma ne.
{106650}{106726}Ali odakle mu pravo | da se pojavi s tom bijelom curom?
{106728}{106785}Koliko se sjeæam i on je bijel.
{106787}{106856}I kažeš da je gotovo? Ti si prekinula s njim?
{106858}{106923}Možda ne bismo ovdje | trebale razgovarati o tomu...
{106925}{106963}jer ovo je rabinov ured.
{106965}{107023}Mislim da ovo nije pravo mjesto.
{107039}{107112}Saberi se. Nemoj da te Mark vidi ovakvu.
{107176}{107205}Kako je mogao?
{107207}{107284}Vratio se njoj kao da se ništa nije zbilo.
{107286}{107356}Zaboravljaš da se i ti viðaš s nekim?
{107358}{107430}S uspješnim crncem.
{107432}{107491}Imaš pravo. Što mi je? Mark je sjajan.
{107493}{107520}- Istina. | - Da.
{107522}{107564}- On je tvoj SC, zar ne? | - Toèno.
{107633}{107682}Budimo jasne.
{107684}{107764}Brian je sladak, ali bijelac je.
{107766}{107830}Ma daj, Kenya, molim te!
{107832}{107892}Dokad si mislila živjeti u laži?
{107894}{107932}Budi iskrena sama sa sobom.
{107934}{108004}Uvijek si sama prijeèiš put.
{108006}{108089}Ti mi se javljaš, ševiš se s oženjenima!
{108091}{108118}Dosta je.
{108120}{108159}Zaboravila si "opusti se i uživaj"?
{108161}{108192}- Èekaj malo. | - Oprosti.
{108194}{108225}- U redu je. | - Istina je.
{108227}{108260}Idi s vragom.
{108283}{108340}Nema to veze s time.
{108342}{108394}Rekle ste da Walter i ja neæemo uspjeti.
{108396}{108424}A povezaniji smo nego ikad.
{108426}{108501}Ne znam koji ti je vrag, | ali Mark je prava lovina.
{108503}{108572}Ako ne znaš što æeš s njim, | samo mi ga prepusti...
{108574}{108618}pa æu ti ja pokazati što æeš s njim.
{108620}{108705}Udat æu se za njega | i izroditi mu mnogo djeèice.
{108707}{108749}Crne.
{108836}{108923}Naše nedjeljne veèere | obièaj su od prve godine braka.
{108925}{108974}- Toèno, Edmonde? | - Da.
{108976}{109050}Jedini dan kad jedem domaæu hranu.
{109052}{109137}Èujem da tvoj otac ima osiguravajuæu kuæu.
{109139}{109175}To je siguran posao.
{109177}{109230}Koliko su ti roditelji u braku?
{109232}{109285}Zašto ga ne pitaš i broj osiguranja?
{109287}{109331}To je samo pitanje.
{109338}{109400}45 godina. Oni su moj uzor.
{109402}{109440}Slatko!
{109446}{109515}Iduæe godine slavimo 35 godina braka.
{109521}{109568}Dr. McQueen je pustolov...
{109570}{109636}a ja sam...
{109638}{109680}glas razuma.
{109700}{109743}Dobra je to ravnoteža.
{109745}{109804}Uvijek me potièe na nova iskustva...
{109806}{109880}a ja uvijek odbijam.
{110034}{110084}Trebao sam im pokazati tko je gazda.
{110086}{110120}Da.
{110135}{110212}Lauren je zamijenila Lanu. | A tko æe zamijeniti Lauren?
{110214}{110320}Posljednja mi se djevojka zvala Luna. | Da, zamijenila ju je Lauren.
{110330}{110433}A Lauren je možda ona prava. | Slušaj njezino stanje.
{110435}{110488}Optièarka je i ima svoju gajbu.
{110490}{110535}Sve je na njezinoj strani.
{110537}{110570}- Stanje? | - Stanje.
{110572}{110626}Tako se odluèuješ na veze?
{110628}{110692}Samo držim korak s tobom, srce.
{110694}{110792}Mark je sjajan. Dobra lovina.
{110804}{110853}Svidjet æe vam se ova prièa, gðice McQueen.
{110855}{110908}Uvjerio sam vašu kæer da izaðe sa mnom...
{110910}{110974}tako što sam joj predložio | da mi pomogne pronaæi kuæu.
{110976}{111039}Rekao sam joj da mi treba | njezino struèno mišljenje.
{111041}{111120}No nisam joj rekao, | da sam i sâm porezni odvjetnik...
{111127}{111169}i da sam veæ znao sve iznose.
{111171}{111240}Zovu me "èovjek broj".
{111265}{111330}Možeš li mi zamjeriti? | Koristiš se onime što znaš.
{111332}{111415}- To je tako slatko, Mark. | - Hvala.
{111417}{111463}Ako sve bude išlo kako treba...
{111465}{111543}tko zna što æemo slaviti za šest mjeseci.
{111545}{111580}Toèno, Kenya?
{111595}{111628}Bože mili.
{111642}{111680}Mark.
{111693}{111768}O, moj Bože!
{111770}{111855}Zaboravimo na kavu | i proslavimo pjenušcem.
{111860}{111905}Bože!
{112537}{112571}Znaš...
{112665}{112752}svidjela mi se fotka s dugom kosom.
{112788}{112830}Znaš li koja?
{112891}{112936}Pusti dugu kosu.
{112995}{113065}Ne mogu.
{113081}{113160}Kenya. Idem prebrzo?
{113232}{113285}Èekaj.
{113301}{113387}Spavat æeš u gostinskoj sobi.
{113389}{113482}Shvaæam ako nisi spremna, | bez pritiska, sve je u redu.
{113512}{113595}Èekat æu te sve dok ne budeš spremna.
{113967}{114046}- Odvest æu te kuæi. | - Sama æu se odvesti.
{114057}{114112}- Zašto? | - Ne mogu ovo.
{114165}{114208}Sjajan si momak.
{114257}{114287}Savršen.
{114336}{114407}Ali nisi za mene.
{114449}{114494}Nadam se da shvaæaš.
{114550}{114615}Nešto sam pogrešno rekao? Uèinio?
{114617}{114690}Bio si sjajan. Ja sam problem.
{114709}{114787}Tražim nešto.
{114813}{114876}Ne znam što je, ali nije ovdje.
{114878}{114928}- Samo tako? | - Žao mi je.
{115129}{115165}Sranje.
{115197}{115224}Sranje.
{115239}{115282}Baš sam glupaèa.
{115350}{115430}Možda sam upravo uèinila | najveæu pogrešku u svojem životu.
{115448}{115506}Zgodan je i pametan.
{115518}{115610}Ali nije bilo kemije.
{115620}{115694}- Ne znam. | - Nemoj se koriti.
{115711}{115748}Slušaj svoje nagone.
{115750}{115797}Što ako su pogrešni?
{115799}{115872}Dobri su. Bila si hrabra.
{115876}{115941}Poslušala si svoje srce, | a ne svoje roditelje...
{115943}{116032}crnaèko društvo ni prijateljice.
{116040}{116090}Odluèila si sama za sebe.
{116108}{116172}Nazvat æeš Briana?
{116176}{116227}Nije rijeè o Brianu.
{116229}{116323}Bila bi da je barem crn, ali nije. | To je stvarnost.
{116325}{116394}Priznajem ti...
{116412}{116517}da ni meni nije bio baš najdraži | kad sam ga upoznao.
{116536}{116615}No na kraju dana rasno pitanje je nevažno.
{116617}{116672}Važna je ljubav.
{116681}{116748}Osjeæaji izmeðu muškarca i žene.
{116765}{116832}Osjeæaš li se uz njega voljeno, | nasmijava li te...
{116834}{116922}možeš li uz njega zaboraviti | na svakodnevne probleme?
{116924}{116996}Jer ako to imaš s Brianom...
{117012}{117088}Ne znam kad æeš to shvatiti.
{117206}{117266}Savjetujem da Pino grupacija...
{117268}{117318}ne kupi Net Worth Consolidated.
{117387}{117424}Ne želiš ovu tvrtku, Jack.
{117426}{117499}Ne želim ti mazati oèi brojkama...
{117501}{117576}i ne podržavam tvrtku | koja ti savjetuje kupnju.
{117600}{117652}Žao mi je, ali to je moja odluka.
{117684}{117742}To nije ono što sam želio èuti.
{117784}{117873}Možemo li ostati nasamo s Jackom?
{117896}{117922}Naravno.
{118388}{118464}Imam spise za Kate Blanchard.
{118545}{118603}Imam i bocu tekile u svojem stolu.
{118605}{118644}Dobro sam, Darrene.
{118795}{118856}- Smijemo li razgovarati? | - Naravno.
{118912}{118992}Sjajna predstava, Kenya.
{119026}{119102}To je upravo ono što tražimo.
{119118}{119170}Hrabrost, pamet i besprijekornost.
{119179}{119276}Bez tvoje izvrsne procjene, | ova bi tvrtka uèinila veliku pogrešku.
{119284}{119330}Sjajno obavljeno, Kenya.
{119395}{119424}Hvala.
{119456}{119547}Veèeras se glasuje, | no htio bih ti prvi èestitati...
{119556}{119584}partnerice.
{119586}{119637}Postala sam partnerica?
{119639}{119678}Da.
{119712}{119804}To je sjajno!
{119811}{119881}- Rekao sam ti da te držimo na oku! | - Bože mili!
{119883}{119977}Tvoja je uloga ovdje nezamjenjiva. | Sretni smo što si dio ekipe.
{119979}{120019}Cijenim to.
{120021}{120059}Èestitam.
{120064}{120092}Edwine.
{120117}{120168}Imam jednu molbu.
{120170}{120203}Reci.
{120224}{120293}Jedan vikend mjeseèno je nedodirljiv.
{120309}{120421}Bez mobitela, e-pošte. Samo moje vrijeme.
{120468}{120519}Mislim da to možemo srediti.
{120989}{121038}Spremne ste držati korak sa mnom veèeras?
{121040}{121100}Jer plesat æu s vama...
{121102}{121143}sve dok vas potpuno ne iscrpim.
{121145}{121224}- Ma daj, Edmonde! | - Je li ono Cheryl?
{121279}{121305}Opa.
{121347}{121409}- Izgledaš prekrasno. | - Nisam te ni prepoznao!
{121411}{121445}Izgledaš prekrasno!
{121447}{121527}- Sjajiš. | - Hvala, gðo McQueen.
{121529}{121584}Možda je to zbog ovoga.
{121684}{121768}Bože! Da èujemo potankosti.
{121770}{121808}Iznenadila sam se.
{121810}{121903}Vozila sam ga do zraène luke, | a on padne na koljena i eto ti ga!
{121912}{121988}Oèekivala sam nešto lijepo, ali ovo?
{121994}{122052}- Sâm ga je izabrao. | - Bože mili!
{122054}{122141}- Nadam se da dobro pamtiš. | - Ne brini se.
{122145}{122198}Prekrasan je, zar ne, Kenya?
{122200}{122236}Da.
{122238}{122316}Razgovarat æemo poslije. | Ne zaboravi naš razgovor.
{122364}{122390}Dobro si?
{122400}{122440}- Da. | - U redu.
{122456}{122516}Predstavljamo gðicu Deavon Frost.
{122518}{122585}Roditelji gða i dr. Malcolm Frost.
{122587}{122697}U pratnji Sidneya Baldwina, | sina Stanleya Baldwina.
{122780}{122843}Gðica Rene Atkins.
{122845}{122913}Roditelji gða i g. Ronald Atkins.
{123199}{123276}...gða i g. David Hunter III.
{123819}{123851}Uspori malo.
{124152}{124199}Ovo je tako glupo.
{124215}{124276}Ne mogu vjerovati da sam vjerovala u ovo.
{124479}{124532}Što želimo dokazati ovime?
{124534}{124609}Da se naše male princeze | mogu udati za prinèeve?
{124611}{124652}Imaju li valjan pedigre...
{124654}{124698}zajamèen im je sretan život.
{124700}{124744}Koliko je to plitko?
{124791}{124860}Nikome ne vjerujte! Više nije što je bilo.
{124862}{124889}Kenya!
{124899}{124931}Prestani!
{125440}{125507}Pretvarajte se dok možete.
{125509}{125548}Sad mi je dosta!
{125563}{125619}Cijelu nas veèer sramotiš.
{125621}{125682}- Ja vas? | - Da.
{125684}{125738}Samo prigovaraš.
{125746}{125835}Kriviš sve osim sebe za svoju nesreæu.
{125837}{125908}Suoèi se s time.
{125927}{125964}Hvala, majko.
{125986}{126015}Kenya.
{126070}{126112}Nisam joj to trebala reæi.
{126853}{126886}Slatkice.
{127024}{127110}Postoji trenutak u životu | kad se moramo odluèiti.
{127112}{127157}- I moramo... | - Opa.
{127159}{127224}Ne brini se. Ja sam lijeènik.
{127256}{127287}I otac.
{127289}{127330}Ovo mi nije novo.
{127332}{127375}Idi za svojim poslom.
{127464}{127526}Ne moraš mi reæi da si zaljubljena u Briana.
{127528}{127571}Toliko je oèito.
{127573}{127628}Gotovo je, molim te ne spominji ga.
{127630}{127676}Prepoznam ljubav kad je vidim.
{127678}{127755}Osim toga, upoznao sam ga. Dobar je.
{127771}{127837}Ukoliko ga voliš, trebaš nešto poduzeti.
{127839}{127869}Ali, tata...
{127871}{127949}Tvoja majka uvijek kaže da sam pustolov.
{127970}{128065}Znaš li da nisam imao ništa | kad sam je upoznao?
{128079}{128116}Nikad ti nisam rekao...
{128118}{128192}no baka i djed prijetili su | da æe je se odreæi uda li se za mene.
{128194}{128258}No suprotstavila im se i pobjegla sa mnom.
{128274}{128354}Nismo znali kako æemo dalje, | ali uspjeli smo.
{128379}{128428}Njezini su nam roditelji poslije oprostili.
{128430}{128519}Ljubav je pustolovina, Kenya.
{128538}{128605}Nije to odluka koju èiniš za druge.
{128615}{128705}Veæ odluka koja dolazi iz srca. | On je bijelac, nije izvanzemaljac.
{128714}{128799}On je bijelac, nije izvanzemaljac.
{128847}{128959}Kao da smo neka èista rasa | koja se ne smije miješati s drugom.
{128961}{129018}Pogledaj nas sve u ovoj zemlji.
{129020}{129099}Crni, bijeli, smeði, žuti. Svi smo izmiješani.
{129111}{129178}Nitko nije potpuno èist.
{129315}{129371}Da je barem moj otac takav.
{129379}{129468}Oprosti, ne iznajmljujem ga, | èak ni u posebnim prilikama.
{129668}{129724}- Možete mi pozvati taksi? | - Da.
{129726}{129787}- Kamo æeš? | - Po Briana.
{129789}{129850}- Što? | - Toèno.
{129867}{129927}Znaš li zašto? Volim ga.
{129992}{130040}Neka ljubav ne èeka. Uzmi moj auto.
{130042}{130101}Hajde.
{130131}{130219}Samo pazi kako voziš.
{130279}{130315}To!
{130475}{130511}Ne!
{130874}{130935}- Bog. | - Bog.
{130937}{131037}- Vidjeli ste Briana? | - Mislim da je otišao.
{131064}{131096}Hvala.
{132008}{132047}Nedostajao si mi, Max.
{132049}{132082}Bog, Maxie.
{132094}{132123}Bog.
{132399}{132425}Bog.
{132453}{132479}Hej.
{132517}{132629}Znam da misliš kako sam ratoborna...
{132647}{132746}živèana i izbirljiva... Možda i jesam.
{132772}{132821}Èudno je to...
{132824}{132886}što s tobom mogu biti ono što jesam...
{132888}{132929}još od samog poèetka.
{132931}{133013}Uz tebe osjeæam da mogu uèiniti bilo što...
{133025}{133104}reæi bilo što, pokušati bilo što.
{133187}{133233}A to je život kakav želim.
{133259}{133349}Želim pustolovinu s tobom.
{133428}{133485}Ne razumiješ. Trebamo biti zajedno.
{133487}{133553}Nikad neæu biti tvoj savršen èovjek, Kenya.
{133555}{133603}Ne želim biti tvoj drugi izbor.
{133605}{133639}U tome i jest problem.
{133641}{133721}Više nemam sumnji. | Znam da je ovo ono pravo.
{133743}{133779}Snovi se mijenjaju.
{133803}{133885}Kao mlada htjela sam se udati | za Ricka Jamesa.
{133922}{133975}Želim tebe, Briane.
{134034}{134067}Volim te.
{134121}{134161}I ja tebe, Kenya.
{134169}{134223}Nikad te nisam prestao voljeti.
{134321}{134399}Moramo odmah otiæi. | Nemamo mnogo vremena.
{134401}{134446}Kamo idemo?
{134505}{134559}Poznaješ li tipa s gitarom?
{136691}{136760}Èovjeèe!
{136775}{136819}- Pogledaj ga! | - Majko mila.
{137164}{137208}Fotkanje!
{137210}{137262}Gledajte svi onamo!
{137777}{137819}Pronašao sam je, tata!
{137840}{138040}{C:$0000FF}{y:ib} d |{C:$FF0000}{y:b} d  
