{1735}{1740}PUT U TAMU
{3125}{3222}ZAPADNA EUROPA|Zima, 1945.
{4200}{4298}...jednog su našli u snijegu,|drugog kako plaèe u kolibi.
{4300}{4348}Što misliš da æe biti|s tom dvojicom glupana?
{4350}{4468}U najboljem sluèaju, vrate ih na front,|u najgorem, streljaèki odred.
{4470}{4585}Vas dvojica ste najveæi glupani|koje sam ikad vidio.
{4585}{4683}Iæi æe pred zid, pitanje je|samo kojeg æe prvog.
{4685}{4763}Hej, što oèekuješ? 82.zraèno-|desantna. Luðaci.
{4765}{4883}82.-a, ha? Izgleda da ste|onda dvostruko glupi :
{4885}{5010}1. što idete pred zid, a 2. što ste|iskoèili iz ispravnog zrakoplova.
{5025}{5075}Zašto ste se pridružili|u zraèno-desantnu?
{5080}{5159}Vjerovatno su mislili da æe|ženama izgledati opasniji.
{5180}{5315}Èovjek koji skaèe iz zraka. Skaèe iz|povijesti toèno u ženin krevet.
{6135}{6215}Što se dogodilo?|Što se dovraga dogodilo?
{6220}{6290}Mislim da je vozaè gotov.
{6350}{9428}Neka se nitko ne mièe,|u minskom smo polju.
{6430}{6533}Što æemo, ne možemo doæi do|svojih stvari... - Smiri se!
{6535}{6685}Mislim da sam slomio gležanj.|- Padobranac, dobro si?
{6755}{6818}Da. - Ne mièi se!
{6820}{6920}Slušaj ga, ne mièi se. - Mislim da je|i tvoj partner popušio.
{6985}{7053}Ne pokušavaj pobjeæi,|jer æu te ubiti.
{7055}{7185}Što æemo uèiniti?|- Smiri se! Dobro?
{7195}{7360}Možeš li izvuæi lopaticu? - Što?|Možeš li izvuæi lopaticu?!
{7370}{7590}Izvadi je i proèešljaj si s njom put|uz brežuljak do onih stabala.
{7635}{7688}Zašto ne možemo prema cesti,|ona je bliža?
{7690}{7753}Jer je cesta sigurno|minirana jaèe.
{7755}{7960}Samo uzmi lopaticu i polako|proèešljaj put prema stablima.
{7975}{8050}Hajde, ti to možeš.
{8215}{8365}Dobro ti ide.|Samo polako.
{8390}{8485}Hej, ne mièi se.
{8625}{8725}Ne mièi se. U minskom polju smo.|Razumiješ li?
{8835}{8895}Da li me razumiješ?
{8965}{9009}Kako ide, Pike?
{9095}{9155}Samo kamen!
{9170}{9235}Za sada je èisto.
{9460}{9599}Mina, toèno ovdje! - Dobro, oznaèi|je i nastavi dalje.
{9630}{9675}Smiri se, Pike.
{10125}{10208}Padobranac! - Dvojica na|jednoga, narednièe.
{10210}{10260}Padobranac!|- Da?
{10315}{10390}Želim da nastaviš, gdje|je on stao.
{10420}{10465}Hajde, mièi se!
{10470}{10550}Nastavi gdje je stao,|slijedi njegov put.
{10560}{10638}Nemam lopatu. - Mièi se, hajde!
{10640}{10680}Jebiga!
{11210}{11260}Nastavi se kretati.
{11340}{11380}Samo tako...
{11405}{11440}Stani!
{12220}{12265}Hej, ti!
{12265}{12330}Što to radiš? Hej!
{12750}{12799}Što to radiš?
{12910}{12980}Mrtav sam.
{13490}{13583}Što si uèinio? - Postao sam|najslobodniji èovjek na svijetu.
{13585}{13673}Mrtav sam, ali evo me.|Veæi od života.
{13675}{13740}Veæi od života!
{13785}{13848}Što æemo sada? Kamo æemo?|Slobodni smo!
{13850}{13903}Ja sam slobodan, ti si još|uvijek zatvorenik.
{13905}{13965}Kako mogu biti zatvorenik, kad|nema nikoga da me èuva?
{13985}{14030}Ne želim èekati|da se još netko pojavi.
{14515}{14575}Moramo stati.|- Nastavi dalje!
{14575}{14625}Ne znamo ni kamo idemo!
{14670}{14735}Stanimo. - Nastavi dalje!
{14915}{14983}Èekaj, ovo je sranje.
{14985}{15043}Moramo napraviti plan.|Vidjeti što æemo.
{15045}{15210}Zaèepi! - Samo kažem da u ruksaku|možda ima mapa, kompas ili nešto?
{15265}{15345}Namirnice, papiri... ništa!
{15400}{15593}Nastaviti æemo hodati. Ti i ja æemo|biti kao kauboji.
{15595}{15643}Idemo prema zapadu.
{15645}{15713}Pokušati æemo pronaæi britansku|jedinicu da se u njoj izgubimo...
{15715}{15865}a ti æeš biti sa mnom|cijelim putem.
{16605}{16660}Donna?
{16830}{16910}Ovdje je tako prelijepo, zar ne?
{17035}{17130}Dobro sam, ne brini...
{18185}{18243}Reci mi što je|tako smiješno?
{18245}{18343}Ovi švabe traže amerièku patrolu da|joj se predaju. Ne žele se više boriti.
{18345}{18465}Govoriš njemaèki? - Jedva èekaju da|doðu u logor da se konaèno najedu.
{18480}{18620}Jesu li rekli gdje je logor? - Ne...|i oni su izgubljeni.
{21320}{21390}Ustaj, vojnièe!
{23910}{23960}Pronašao si nešto?
{24110}{24530}Da li se ikad pitaš kako je ovo|mjesto izgledalo prije rata? - Ne.
{24255}{24338}Ne pitaš se kakav si i sam|bio prije rata?
{24340}{24410}Isti kao i sada.
{24405}{24500}To me ni malo ne iznenaðuje.
{24635}{24710}Nikad me ne potcjenjuj!
{24750}{24825}Prestani cviliti...
{24828}{24900}i poèni hodati.
{25360}{25470}Nemoj da èujem da ti nikad|nisam ništa dao.
{25775}{25880}Što se ovdje dogodilo?|- Švabe dobili svoje.
{25890}{25950}Zgodno.
{26210}{26330}Pa... umrli su blizu Boga.
{26840}{27013}"I anðeli, koje Gospodin nije htio,|uskrsnuli i zaboravljeni,
{27015}{27178}potvrdili su da su mjesto|tragedije, èovjeka i njegovog heroja,
{27180}{27250}pokorili crvi."
{27285}{27410}Killney, "Pjesma mojih|ministrantskih dana."
{27435}{27535}Zamolio sam uèitelja|da mi je objasni.
{30055}{30150}Ako nastaviš zuriti u vatru,|spaliti æeš si oèi.  Ali, u redu je...
{30180}{30260}Svi djeèaci su|pomalo piromani.
{30690}{30740}Stani!
{30800}{30950}Prestani!
{30880}{30950}Ubij ga!|- Dovraga, ne!
{30955}{31140}Nemoj! Možda nam ovaj momak može|reæi gdje smo? Razmisli malo!
{31175}{31210}Dobro...
{31245}{31283}Ustaj!
{31285}{31355}Otkrijmo što zna.
{31370}{31500}Govoriš li njemaèki?|Engleski?
{31510}{31743}...hodam dolinom sjenki... - Da, da,|seronjo, govoriš li engleski?
{31745}{31940}...iako hodam dolinom sjenki i smrti...|- Beskoristan je.
{31945}{31095}Smiri se... - Bolje ti je da|mu ne okreæeš leða.
{32100}{32165}A ni meni.
{32175}{32325}Smrii se. Jesi li gladan?|Gladan?
{32345}{32475}Nemoj mu davati našu hranu!|- Hej, smiri se...
{32477}{32618}Glupane, on je samo neki crkveni|seronja, ne zna ništa! - Dobro!
{32620}{32690}Vezati æemo ga|i pogledati uokolo.
{32915}{32970}Ok, ideš ispred mene.
{32985}{33055}Smiri se.
{34425}{34502}Rekoh ti da ne okreæeš|leða tom tipu.
{34505}{34600}Jebaè bi ih mogao|malo zagristi.
{35890}{36055}Dovraga, koliko misliš da smo prešli?|- Prestani cviliti i nastavi hodati.
{36315}{36450}Još ide za nama.|- Da, neka nas sustigne.
{36465}{36710}Hodati æeš s nama, ali bez prièe.|- Reci mu da nema klope za njega.
{37855}{37985}Mora da je nekakvo selo u blizini.|Otvorite oèi i  bez prièe.
{40170}{40260}Sada je stvari opet onakve,|kakve bi i trebale biti.
{40335}{40430}Hajdemo pronaæi|našeg ljudoždera.
{41790}{41845}Daj mi malo onog šeæera.
{42040}{42150}Vidi, vidi...|što to imam za tebe.
{42200}{42249}Hajde, mala...
{42270}{42350}Hajde ovamo... Imam te!
{42435}{42490}Odakle si došla, ha?
{42540}{42620}Pomozi mi da se popnem.
{42940}{43050}Da li si ikad prije jahao?|- Da, jahao sam prije.
{43055}{43111}Puno puta!
{43200}{43375}Što misliš odakle je? - Ne znam, samo|znam da više nisam u pješadiji.
{44480}{44540}Skoèi gore.
{45900}{45950}Dole, sagni se.
{46005}{46125}Jesi li vidio što?|- Gadovi su je izrešetali.
{46200}{46330}Ako unutra ima švaba, do sada|su nas siguno primjetili. - Idemo tamo.
{48175}{48250}Hotel od èetiri zvijezde.
{51050}{51099}Probudi se!
{51177}{51220}Doði ovamo.
{51435}{51590}Jebiga, u što bi trebali gledati?|- Nešto predivno...
{51675}{51745}Samo sam zurio u nju.
{51825}{51888}Slijedeæi put kad me probudiš...
{51890}{52065}bolje ti je da Rita Hayworth stoji gola,|vièe moje ime i moli me da je pojebem!
{52800}{52889}Idem dolje|donesti vode.
{52905}{52988}I potražiti nešto za jesti.
{53025}{53089}Možda ima nešto što|štakori nisu pronašli.
{53155}{53285}Konj je još tamo. Jesi za|konjski odrezak?
{54050}{54125}Ted, imamo društvo!
{54365}{54415}Civili.
{54455}{54515}Ima pušku.
{54595}{54660}Sranje!|- Nemoj još panièariti.
{54745}{54800}Maknimo se.|- Da.
{55600}{55670}Ne mièite se!
{55748}{55815}Ne mièite se!|Ne, ne... Njemaèki?
{55945}{56045}Govorite engleski? |- Engleski? Da.
{56075}{56150}Napokon prilika|za razgovor.
{56185}{56295}Ako pokušate|pobjeæi, ubiti æu vas.
{56325}{56520}Deming... - Deming ne postoji,|mrtav je, sjeæaš se?
{56530}{56635}Nemoj!
{56660}{56745}Deming, smiri se.
{56770}{56850}Ne! Nemoj, dovraga...
{57015}{57065}Sada...
{57130}{57190}Ruke na dugmad.
{57230}{57370}Hajde! Slijedi predstava.
{57580}{57619}Još...
{57680}{57825}Do kraja. Skini sve|do kraja.
{57985}{58050}Moram priznati...
{58085}{58150}Betty Gray Lincoln|ima konkurenciju.
{58158}{58220}Budi miran.
{58235}{58325}To je izmeðu Betty|i mene.
{58375}{58410}Ovamo.
{58550}{58599}Tako, vidiš...
{58660}{58719}Nije tako loše, zar ne?
{58730}{58850}Hajde da ih malo kušamo.|Tko im može odoljeti?
{59030}{59080}Dolje je, dolje!
{59150}{59280}Kopile! Prljava svinjo!
{59470}{59630}Neæeš doživjeti da opet|dodirneš ženu, obeæavam ti!
{60020}{60065}Prekrasan dan.
{60070}{60135}Ovdje je tako prelijepo.
{61470}{61550}Sad se razumijemo.
{61585}{61650}Predstave æe biti.
{62335}{62428}Sada... gdje je vaša postrojba?|Koliko je udaljena?
{62430}{62495}Pitaš dva pogrešna momka.
{62497}{62638}Nije vrijeme za laž. Oèito ste njemaèki|špijuni, vidjeli smo tu taktiku i prije.
{62640}{62733}Želimo znati gdje je ostatak vaše|postrojbe. Svejedno æemo saznati.
{62735}{62790}Sve ste krivo shvatili.
{62800}{62873}Gospodine, mi smo|amerièki vojnici.
{62875}{62978}Dva èovjeka putuju sami, bez|potpore, bez zapovjednika...
{62980}{63053}Nema Amerikanaca u |ovoj podruèju.
{63055}{63105}Èak ne znamo ni gdje smo.
{63200}{63368}Gledajte... istina je da smo|dezerteri. Pobjegli smo, ok?
{63370}{63545}Kažete da ste kukavice? Prva stvar|koju vam vjerujem. - Kukavice!
{63700}{63798}Postoji moguænost da je|to što govorite istina.
{63800}{63895}Ako ste pravi Amerikanci, znati æete|u koga je bio zaljubljen Tom Sawyer?
{63897}{63940}Tom Sawyer?
{63985}{64108}Onaj iz knjige? - Rekli su mi da je tu|knjigu proèitao svaki amerièki djeèak.
{64110}{64210}U Becky Tacher.|- Da, Becky Tacher.
{64220}{64353}Ostati æete vezani dok ne nastavimo.|Jesti æete što dobijete...
{64355}{64490}i dobivati æete ... - Oprostite...|- Poštovanje koje zaslužujete!
{64570}{64630}Ljudi, tko ste vi?
{64645}{64760}Tko su ova djeca?|- Vaša suprotnost.
{65485}{65610}Amerièki? - Da, tako je klinac.|Amerièki.
{65670}{65745}Tko su ova djeca?|Sva izgledaju malo sjebana.
{65895}{65999}Seronjo!
{74275}{74435}Dakle, niste nacisti, Amerikanci|ste? Kopilad!
{74635}{74718}Ne znamo o èemu govoriš,|što se dogaða?
{74720}{74868}Oko 60 njemaèkih vojnika|i jedan tenk dolaze ovamo.
{74870}{75039}Oslobodi nas, da pobjegnemo. Ovdje|su zbog vas, ne sigurno zbog nas.
{75200}{75255}Ne želim više bježati.
{75275}{75370}Oslobodi me i boriti æu se.
{75430}{75480}Oslobodi me!
{75880}{75999}Što sa mnom? Dovraga, oslobodi|me ili... - Ili što?
{76000}{76110}Ili što, seronjo?|Umrijeti æeš.
{76120}{76160}To æeš.
{76165}{76290}Jedina šansa koju imaš, koju mi|imamo, je da se boriš.
{76340}{76410}Ne možemo više bježati.
{76575}{76625}Idemo gore.
{77145}{77220}Jebaè...|- Da vidim.
{77285}{77335}Sranje...
{77495}{77625}Koliko nas ima? - 10 djece i nas|èetvero. - Što ste radili ovdje?
{77640}{77728}Tko su ta djeca? - Zašto su poslali|tenk da ih sredi?
{77730}{77833}Oni su siroèad. Držali smo sirotište|za djecu sa posebnim potrebama.
{77835}{77918}Jednoga dana èuli smo|zrakoplove, eksplozije...
{77920}{78013}Pobjegli smo u šumu. Ali neka|djeca ništa ne razumiju...
{78015}{78063}misle da je rat samo jedna igra.
{78065}{78143}Ja sam ih uvježbao i tako smo|postali borbena grupa.
{78145}{78203}Udarimo i sakrijemo se|gdje stignemo.
{78205}{78288}Uèio sam ih lekcijama iz povijesti,|koje su jako dobro shvatili.
{78290}{78385}Dao sam im nešto što nikada|nisu imali... identitet!
{78425}{78480}Obitelj!
{78500}{78560}I sada su vas|švabe otkrili ovdje.
{78925}{78988}Poèinje!|- Jebeni Alamo.
{78990}{79060}Uzmite opremu! - Gore,|požurite!
{79405}{79465}Uði tamo, brzo!
{84572}{84720}Što se to dogodilo? - Ne znam, izgleda|da se netko unutra naselio.
{84722}{84510}Pregrupirati æemo se|i onda otkriti tko.
{84875}{84953}Idu na vrh brda, pokušavaju|nas opkoliti.
{84955}{85025}Zašto jednostavno ne sravne|sve za zemljom?
{85125}{85213}Ne razumijem. Zašto nas|ne raznesu sa tenkom?
{85215}{85288}Možda nemaju granata.|- Ne bih na to raèunao.
{85290}{85378}Onesposobiti æemo tenk kad|padne noæ, imam plan.
{85380}{85480}I mi smo u njemu?|- Ne ukljuèuje vas, mi æemo to obaviti.
{85905}{85988}Rekli ste da æemo samo ušetati|unutra i izaæi van.
{85990}{86063}Niste spominjali da æe|netko uzvraæati vatru.
{86065}{86138}Tamo je nešto što|nismo oèekivali.
{86140}{86218}Tipièno za cijeli ovaj|usrani rat.
{86220}{86278}Završiti æemo s tim.
{86280}{86365}Samo pucanj upozorenja.
{86425}{86570}Vjerovatno neki glupi partizani, koji|ni ne znaju da su veæ pobijedili.
{87725}{87780}Idite do prozora!
{87975}{88015}Dovraga!
{88075}{88130}Idemo u prizemlje.
{88185}{88263}Pucajte iz strojnice prema|srednjem dijelu.
{88265}{88415}Pucajte oko prozora. Tamo æe|preživjeli biti. - Razumijem.
{89900}{90010}Koliko dugo možeš ostati dolje?|- Jako dugo.
{90012}{90080}Koliko dugo možeš|zadržati dah?
{90615}{90660}Sranje!
{91065}{91110}Jesu li svi tu?
{91150}{91190}Dolje!
{91215}{91315}Dariusa nema!|- Idem ga pronaæi.
{91405}{91503}Koliko izlaza ima odavde? - Glavni|i jedan stražnji, niz padinu.
{91505}{91560}Idem pokriti taj stražnji,|s vremenom æe ga otkriti.
{92470}{92528}Tu granatu bacio je|jedan amerièki vojnik.
{92530}{92630}Kako su Amerikanci|stigli ovdje?
{93210}{93268}Predajte se, spasite svoje živote!
{93270}{93400}Dajem vam pet minuta da odluèite,|želite li živjeti ili umrijeti!
{93540}{93610}Došlo je vrijeme.
{93925}{94035}Spasite svoje živote,|izaðite odmah!
{94060}{94099}Nelu...
{94370}{94499}Ne brinite. Sve æe biti|brzo gotovo. Dobro je.
{94505}{94555}Èetiri minute.
{94570}{94630}Dolje.
{94660}{94740}Poginuti æemo sigurno.|Na prvom smo katu.
{94760}{94865}Ako ona stvar opali, sve|æe se raspasti.
{95020}{95118}Još 3 minute. Nadam se da|se pripremate izaæi.
{95120}{95192}Drago mi je što taj|seronja zna gledati na sat.
{95370}{95500}Imao je pravo. Imao je pravo,|sve je samo igra.
{95502}{95560}Samo æemo se|malo igrati.
{95580}{95653}Ništa... ne misle izaæi.
{95655}{95728}Ali ne smijemo|uništiti zgradu.
{95730}{95899}Moramo biti krajnje precizni,|nemamo drugog izbora.
{96115}{96175}Moramo nešto uèiniti.|- Pokrivajte ga!
{97040}{97110}Dao sam im nešto|što nikada nisu imali...
{97505}{97559}Glupi stari seronja!
{97905}{98075}Vaš glupi napad garantira vam smrt.|Nije moralo završiti ovako.
{99400}{99463}Malo ga je oštetilo.|- Malo smo dobili na vremenu.
{99465}{99550}Ali kupola je èitava, a mi smo sjebani.
{100345}{100435}Što? To je napravilo|jedno dijete?
{100615}{100683}Èini se da se|djeca bore za vas?
{100685}{100760}Siguran sam, da ne želite|da itko od njih više umre.
{100770}{100878}Dati æu vam novu ponudu.|Pustite svu djecu.
{100880}{101998}Pustiti æu ih. Moj interes|nije ubijanje djece.
{101000}{101080}Ovo je rat odraslih.
{101100}{101180}Nije znao da su ovdje|djeca? - Da.
{101182}{101225}Nisu ovdje zbog njih.|- Da.
{101227}{101268}Zašto su onda ovdje?
{101270}{101355}Mjesto je bilo oèišæeno prije nego|smo došli ovamo. Nema nièega.
{101400}{101440}Nema nièega.
{101540}{101623}Dolje, dolje!|Što hoæe?
{101655}{101700}Idi!
{101760}{101830}Mehanièaru... brže to!
{101835}{101960}Popravi kupolu pa da završimo|s time!
{103650}{103760}Slike... Ovdje|su zbog slika!
{104380}{104530}Ti... To si ti.
{104590}{104655}Prelijepa si.
{104760}{104868}Ne vidim da išta poduzimate.|Nijedno dijete neæe biti spašeno.
{104870}{104985}Ne ostavljate mi drugog izbora.|Dolazimo!
{105030}{105128}Znaš zašto su švabe ovdje? Dolje je|jebeni muzej slika! - Što?
{105130}{105195}Hrpa slika! Odasvud!
{105315}{105370}Sranje!  Premraèno je da|išta vidimo!
{105465}{105545}Idemo, to je to! Djeco,|budite spremni!
{105705}{105760}Dolaze... Dolaze!
{106025}{106070}To!
{106255}{106320}To je to!
{106505}{106560}Svi dolje i ne pucajte!
{106660}{106699}Èekajte...
{106725}{106760}Èekajte...
{106775}{106805}Èekajte!
{106860}{106915}Sada!
{107500}{107545}Nemam municije!
{109085}{109135}Previše ih je!
{109155}{109215}Moramo pokriti|sve ulaze!
{109235}{109285}Hajde, klinac, idemo!
{109450}{109515}Brzo, pokrijte onaj ulaz!
{109655}{109720}Dolje niz stepenice, odmah!
{110130}{110180}Svi u prizemlje, idemo!
{115460}{115540}Nešto što nikada|nisu imali... identitet!
{115560}{115599}Obitelj!
{116715}{116850}Znaš da æe se vratiti|sa pojaèanjem? - Znam.
{117830}{117923}Izvedi djecu odavde i ti|poði s njima? - Što?
{117925}{118020}Idi uz kanal, odvesti æe te|do šume. Uspjeti æeš.
{118140}{118199}Što æe biti s tobom?
{118325}{118385}Konaèno sam shvatio...
{118435}{118505}nakon 33 godine...
{118585}{118630}tko sam ja zapravo.
{118880}{118950}Bio sam kao otac tim ljudima.
{118970}{119108}Bili su moja obitelj... i ja æu se|pobrinuti za njihovu buduænost.
{119110}{119189}To je naša posljednja borba.
{119330}{119480}Dobro si? Kako glava?|- Uspjeti æu.
{119610}{119735}Na prvu eksploziju koju|èuješ... kreæete!
{119740}{119820}Ne moraš to raditi.|- Prestani cviliti...
{119840}{119888}i poèni hodati.
{120025}{120065}Kreni!
{120290}{120350}Za mnom... hajde!
{120630}{120755}Hej, vi jebaèi! Gdje ste?
{120890}{121015}Znam tko sam, jebaèi!|Doðite po mene!
{121015}{121010}Gospodine, kupola je popravljena!|- Okrenite kupolu udesno!
{121190}{121250}Držite se zajedno, što više dolje!
{121600}{121650}Hej, jebaèi!
{121680}{121750}Znate li tko sam ja?
{121910}{122025}Ja sam pokoritelj crva!
{122055}{122135}Ja sam pokoritelj crva!
{122160}{122290}Ja sam pokoritelj crva!
{123800}{123880}Nadam se da je vaša buduænost|bila vrijedna toga.
{126334}{126399}Ona je prelijepa.
{126475}{126535}Ti si prelijepa.
{127635}{127705}Europa bi mogla biti|prelijepo mjesto.
{127715}{127780}Ako je samo|vidiš na pravi naèin.
{128520}{128560}Ne ostavljaj me.
{128580}{128635}Molim te, ne ostavljaj me.
{128665}{128720}Nikada te neæu napustiti.
{128885}{128985}Posveæeno Williamu D. Burr, JR.|(1927-2000)
{128986}{128987}
{129020}{131050}Prijevod i obrada :|ToNY_VT
{131051}{131052}
