{1}{1}25.000
{1385}{1410}Opa!
{1790}{1831}Bjeûi!
{1834}{1890}To je Zugor!
{1893}{1932}»udoviöte?
{2196}{2285}Hej, hej, hej! | Nije fer ûicati voûnju.
{2358}{2452}Halo. äto to radiö?
{2455}{2519}äto god to bilo, | ne ide ti najbolje.
{2522}{2583}Dolazi li joö uvijek?
{2741}{2793}»ekaj malo.
{2796}{2861}Zugor ne postoji.
{2864}{2935}On je samo plod maöte.
{2938}{3020}Terk se pretvarala, tako da mogu | vjeûbati spaöavanje ûivota.
{3022}{3073}Prespor sam. | Ako ne postanem brûi,
{3076}{3129}neöto Êe me straöno uhvatiti.
{3132}{3175}Najgori si majmun.
{3178}{3245}Kad bi se Zugor spustio | s Tamne planine,
{3247}{3290}dosad bi te veÊ probavio.
{3293}{3326}A i tebe...
{3329}{3372}Ne bi.
{3375}{3408}Promaöio si.
{3411}{3437}Opet.
{3470}{3504}Baö tuûno.
{3540}{3611}Recept za katastrofu.
{3614}{3697}Snaga da budeö snaûan
{3700}{3783}I mudrost za mudraca
{3786}{3896}Sve Êe to s vremenom doÊi
{3933}{4016}Na putu kojim hodiö
{4019}{4104}Vrhunac ti neÊe izmaÊi
{4107}{4187}Sine ËovjeËji, gledaj nebo
{4190}{4277}Ne gubi nadu, opusti se
{4280}{4351}Jednoga Êeö dana biti netko
{4354}{4469}Ljudsko biÊe odraslo
{4614}{4671}Hajde, moûeö ti to.
{4804}{4876}Moûeö ti to. | Moûeö ti to.
{4908}{4944}Jej-o | Jej-o
{4947}{4984}Jej-o | Jej-o
{4987}{5049}Jej-o, jej-o | Jej-o
{5254}{5347}Sine ËovjeËji, gledaj nebo
{5350}{5411}Pazi!
{5414}{5487}Jednoga Êeö dana biti netko
{5490}{5554}Drvo! Drvo Drvo!
{5658}{5776}Sine ËovjeËji, | muökarac Êeö postati
{5903}{5962}- Jesi li dobro? | - Duöo, jesi li Ëitav?
{5965}{6040}äto ti je? Joö je beba.
{6043}{6092}Nemoj se viöe igrati s njim.
{6094}{6139}Netko Êe stradati zbog njega.
{6168}{6260}- Jadna Kala. Mali je napast. | - Za sve nas.
{6263}{6334}Lijepo. Skoro si | izbrisao pola obitelji.
{6337}{6395}Opet Slonovski vodopadi.
{6398}{6459}VeÊ Ëujem Kerchaka.
{6462}{6542}"Mogao si nekog ubiti."
{6545}{6614}"Joö je dijete. NauËit Êe."
{6617}{6678}"NeÊe opstati u dûungli.
{6681}{6723}Ne moûe trËati, ni penjati se.
{6726}{6776}Opasnost je za sve nas.
{6779}{6844}Mislim da Êu sada | dojmljivo zareûati."
{7023}{7111}Hej, kompa. Znaö da se öalim?
{7114}{7176}Dakako.
{7179}{7292}Nisam ismijavala tebe. | VeÊ Kerchaka.
{8379}{8466}Hajde, vrijeme za spavanje.
{8469}{8531}Da vidimo...
{8550}{8628}Evo. Kako je? Udobno?
{8631}{8662}Super je, mama.
{8727}{8791}Imam tvoj nos.
{8794}{8900}- Imam tvoje prste. | - Mama, prestani.
{8903}{8951}Prevelik sam za "nos i prste".
{8954}{9025}Mislim da jedan nedostaje.
{9028}{9092}Moûda se skriva...
{9095}{9168}...tu. | - Mama, prestani.
{9171}{9232}Prestani. Ne, ozbiljno...
{9235}{9295}Mama, prestani.
{9370}{9414}Tarzane, öto je?
{9463}{9542}- Tarzane? | - Nisam dobar majmun.
{9545}{9607}Ne mogu pobjeÊi Zugoru.
{9610}{9686}Zugoru? Znaö da on ne postoji.
{9689}{9735}To je samo priËa o duhovima.
{9738}{9799}Ali da je stvaran, | ulovio bi me.
{9802}{9855}Prespor sam.
{9858}{9934}Znaö öto? Ako Zugor | doe po tebe,
{9937}{10005}spasit Êu te. | Budi siguran.
{10008}{10108}Ali tada Êeö biti | u opasnosti zbog mene.
{10111}{10208}Svima bi bilo bolje da me nema.
{10211}{10341}Doi. éelim ti neöto pokazati.
{10609}{10702}Ovo je drvo prije stajalo ovdje samo.
{10724}{10781}äto mu se dogodilo?
{10784}{10826}Bila je velika oluja
{10828}{10923}i vjetar je puhao | dok drvo nije palo.
{10926}{10998}A sada pogledaj ovamo.
{11300}{11364}Ovo je najjaËe drvo u dûungli
{11367}{11432}jer ima mnogo debala | koja rade zajedno
{11435}{11495}i podiûu liöÊe prema nebu.
{11498}{11558}I pogledaj, debla su razliËita.
{11561}{11611}Neka su tanka, neka debela,
{11614}{11712}- neka iskrivljena, neka ravna. | - Ovo izgleda debelo.
{11715}{11775}Izgleda, zar ne?
{11778}{11867}Ali sva pomaûu u ojaËavanju drveta
{11870}{11939}da moûe preûivjeti | bilo kakvu oluju.
{11942}{11982}Poput obitelji.
{12015}{12078}- Poput naöe obitelji? | - Tako je.
{12081}{12163}Trebaö obitelj, Tarzane. | I obitelj treba tebe.
{12166}{12249}- Nitko me ne treba. | - Ja te trebam.
{12297}{12374}I uvijek Êu te trebati.
{12377}{12440}Gdje nam je sada onaj prst?
{12443}{12490}Mama, imam sve prste.
{12493}{12574}Ne bih rekla. | Moûda je tu. Ili tu...
{12577}{12625}Mama, prestani.
{13143}{13178}Zubi.
{13181}{13232}»uvaj se velikih straönih zuba.
{13235}{13323}Bjeûi! To je Zugor!
{14596}{14673}Prestani se igrati, Tarzane.
{14676}{14747}Onda, öto se Ëeka?
{15011}{15071}Bjeûite!
{15755}{15801}- Tarzane! | - Mama!
{16751}{16801}Ne.
{17015}{17063}Kala.
{17513}{17557}Mama?
{17590}{17630}Mama?
{17670}{17728}Gdje su svi?
{17731}{17801}Mama, gdje si?
{17804}{17839}éao mi je, Kala.
{17842}{17939}Bio je tu. | Skoro sam ga uhvatila.
{17942}{18031}A onda je... Ne.
{18034}{18084}Niöta nisi mogla uËiniti.
{18087}{18174}UËinila bih sve. | I dala svoj ûivot za njegov.
{18261}{18335}Jadna Kala. Bilo je uûasno.
{18338}{18380}Zamalo je i ona poginula...
{18405}{18522}Mrzim to reÊi, ali vjerojatno | joj je bolje bez njega.
{18525}{18567}Mislim da nam je svima bolje.
{19287}{19403}Moûe li mi netko reÊi | kamo pripadam
{19406}{19508}Kamo bih trebao poÊi?
{19511}{19611}Moûe li mi netko pokazati | u Ëemu grijeöim?
{19635}{19737}éelim znati
{19806}{19908}Zaöto povrijedim one koje volim
{19911}{20024}Svime öto Ëinim?
{20027}{20144}Ako ne mogu biti | ono öto ûele od mene
{20147}{20218}äto da uËinim?
{20266}{20362}- Ne mogu otiÊi kuÊi | - Ne mogu otiÊi kuÊi
{20365}{20474}- Toliko znam | - Toliko znam
{20477}{20603}Moûda bi bilo bolje | da nestanem
{20606}{20678}Sam
{20681}{20799}- Moram pronaÊi svoj put | - PronaÊi svoj put
{20802}{20875}I nekako Êu opstati
{20878}{20925}Nekako Êu opstati
{20928}{21056}Kad bi samo postojalo mjesto | gdje mogu biti
{21059}{21148}Samo ja
{21151}{21278}Kad bi samo postojalo mjesto | gdje mogu biti
{21281}{21414}Samo ja
{22461}{22585}Zugor!
{24013}{24088}Gle öto imam. PtiËicu.
{24091}{24164}- Ali nisam ptica. | - Kago, vidi öto sam naöao.
{24167}{24207}PtiËicu.
{24210}{24250}Ha?
{24354}{24447}Zar ne vidiö da sam | se zabavljao? Trebao bih...
{24450}{24494}»ekaj malo.
{24497}{24587}- Uto, to nije ptica. | - Baö nisam.
{24590}{24668}Nema perje, | mozgu od banane.
{24671}{24734}Jest, i mogu dokazati.
{24737}{24815}Bacit Êemo je s litice | i kad poleti,
{24818}{24890}ti Êeö biti mozak od banane.
{24923}{24983}Ne bodi me.
{25038}{25109}Ne bodi me! | Ne bodi me! Ne bodi me!
{25156}{25198}Prestani! Prestani!
{25201}{25248}Prestani se smijati!
{25251}{25301}Svia mi se kad moj brat ötuca.
{25304}{25345}Urnebesno je.
{25348}{25396}Sad je dosta.
{25399}{25454}Sruöit Êu te.
{25603}{25664}DeËki!
{25667}{25705}Zdravo, mama.
{25739}{25827}Moji dragi deËki, | zlata moja,
{25830}{25895}öto vam je mama Gunda | rekla o svaanju?
{25898}{25999}- Podbadao me. | - Nazvao me je mozgom od banane.
{26002}{26043}Usnice!
{26093}{26150}Svaa Ëini mamu...
{26153}{26226}...vrlo nesretnom!
{26229}{26288}Razumijemo li mamu?
{26291}{26356}Da, mama.
{26359}{26465}Kakve su to gluposti o ptiËici?
{26468}{26508}Nisam ptica. Ja sam majmun.
{26602}{26665}- Majmun! | - Poput vas.
{26748}{26799}Moûemo li ga ipak | baciti s litice?
{26802}{26871}Ako si majmun, | gdje ti je obitelj?
{26874}{26933}Kako si doöao ovamo?
{26936}{26985}Morao si doÊi kroz onu pukotinu.
{26988}{27035}To je jedini ulaz.
{27038}{27074}Osim pada.
{27077}{27152}Spotaknuo sam se. | Bjeûao sam od Ëudoviöta.
{27155}{27215}- Svi smo mi bjeûali, duöo. | - »udoviöte?
{27218}{27288}»uva pukotinu, Ëeka nas.
{27291}{27400}I ako te uhvati, | kaûu da Êe te pojesti.
{27403}{27438}Nazivaju ga...
{27441}{27499}- Nemoj reÊi, mama. | - Ne sluöam.
{27502}{27545}Ne ûelim ovo Ëuti.
{27548}{27597}...Zugor.
{27600}{27646}Ali ne postoji...
{27649}{27789}Zugor!
{27792}{27840}Dolazi.
{27875}{27923}Zugor!
{28064}{28133}Zugor!
{28676}{28747}To je Zugor! | Bjeûite, Zugor!
{28951}{29017}Moje drvo. Ne prilazi.
{29020}{29100}- Ali moraö me pustiti... | - Ne. Bjeûi.
{29154}{29203}- Molim te! | - Ne.
{29206}{29266}Ako ostanem vani, | moûda me Zugor uhvati.
{29269}{29344}Baö mi je ûao.
{29347}{29425}Moraö mi pomoÊi.
{29428}{29498}Moraö.
{30076}{30141}Mama?
{30541}{30645}U redu, duöice. | Idemo, penjite se.
{30801}{30904}Ovo je bio joö jedan | veliki dan za moje deËke!
{30907}{30961}Zugor nas je uplaöio, mama.
{30964}{31012}Znam, mili.
{31015}{31062}- Mene nije uplaöio. | - Baö je.
{31065}{31150}- Nije. | - Jest.
{31153}{31201}Nije.
{31407}{31456}- Mama? | - Da, mili?
{31459}{31546}- PriËaj nam priËu. | - U redu.
{31549}{31618}Ako vam ispriËam priËu, | hoÊete li spavati?
{31621}{31648}Da.
{31651}{31708}Da vidimo.
{31711}{31822}NekoÊ davno | bila je obitelj tri...
{31825}{31887}...ne znam, tri...
{31890}{31954}Smijeöne ûabice? | U redu, mili.
{31957}{32076}NekoÊ davno bila je | obitelj tri ûabice.
{32079}{32156}Jedna je od njih bila malo tupa...
{32159}{32251}- Koja? | - A druga malËice nasilna.
{32254}{32286}Ta mi se svia.
{32289}{32402}Neki bi rekli da ih je mama | previöe drûala pod kontrolom...
{32405}{32455}...no ne slaûem se s time.
{32458}{32541}Pojedu li ûabe krokodili?
{32544}{32609}Ne, ne daj da ûabe | budu pojedene.
{32612}{32644}Neka odlete.
{32647}{32721}U redu je, Uto. | Nisu pojedene.
{32724}{32814}Ali tri ûabice | bile su posve same
{32817}{32885}u bijelom svijetu,
{32888}{32943}skakutale od bare do bare.
{32946}{32983}Skok na skok.
{32986}{33093}Pokuöavale su naÊi mjesto | na kojemu bi bile ûeljene.
{33096}{33203}No gdje god su bile, | otjerane su.
{33206}{33282}Moûda bi trebale | razbiti nekoliko glava.
{33285}{33371}Zavröile su | u uûasnoj dolini
{33374}{33416}gdje ih je straöilo Ëudoviöte.
{33419}{33490}Imale su vrlo malo | jela i piÊa
{33493}{33607}i morale spavati samo | na öiljatu kamenju!
{33610}{33671}- I tako... | - Ha?
{33674}{33810}...sutra Êe ona naÊi | svojim ûabicama novi dom.
{33813}{33932}I ovaj Êe put svi koji joj | stanu na put osjetiti
{33935}{34051}straöan bijes mame éabe!
{34108}{34185}Mama, slomio sam jastuk...
{34188}{34221}...opet.
{34542}{34580}Tarzane?
{34583}{34640}Mama!
{35730}{35774}Jao!
{37513}{37606}Zugor!
{37807}{37919}Zugor!
{37966}{38025}Zugor!
{38087}{38142}Zugor?
{38145}{38192}Ne mogu vjerovati.
{38428}{38486}- Bok, Zugore. | - Zdravo.
{38533}{38587}Ti si Zugor, zar ne?
{38590}{38662}- Nisam. | - Jesi. Vidio sam te.
{38665}{38723}- Nisi. | - Uplaöio si nosoroga
{38726}{38761}kako bi mu uzeo voÊe.
{38764}{38834}To je moje!
{38994}{39045}Bjeûi!
{39903}{39982}Baö ti hvala... Ni na Ëemu!
{39985}{40068}Ti si kriv öto nas uopÊe lovi.
{40071}{40130}Hej, Ëekaj.
{40178}{40218}Odlazi.
{40259}{40320}Ostavi me samoga.
{40323}{40406}- Samoga? | - Da. Samoga.
{40409}{40516}Zugorovo pravilo broj 1: | Ne trebaö nikoga.
{40519}{40554}Idi kuÊi.
{40557}{40634}- Ne mogu. Pobjegao sam. | - Da, da, da.
{40637}{40669}I ne vraÊam se
{40672}{40719}dok ne nauËim biti dobar majmun.
{40722}{40783}éao mi je. | Igraj se s aligatorom.
{40786}{40884}Ti me nauËi. | Ti si Zugor.
{40887}{40935}NauËim? Ja? Ne.
{40938}{41005}»ekaj... Ne.
{41008}{41067}Moûe i ovako: Ne!
{41070}{41109}Vidimo se, zbogom, pa-pa.
{41364}{41434}Dobro, idem ja.
{41437}{41534}Jedva Ëekam da svima kaûem | tko je Zugor.
{41537}{41562}Ha?
{41564}{41639}NaroËito onim | velikim majmunima.
{41642}{41689}Dobro Êemo se nasmijati
{41692}{41745}kad im kaûem da si ti Zugor.
{41748}{41785}»ek', Ëek', Ëek'.
{41788}{41864}Znaö, mogao bi se predomisliti.
{41867}{41931}Tako nikada neÊu | ispriËati tu tajnu.
{41981}{42055}Ne sviaö mi se.
{42141}{42222}Dobro. Dogovoreno. | PomoÊi Êu ti.
{42225}{42287}A ti nikomu neÊeö reÊi.
{42290}{42433}Tako je! | Nikomu neÊu reÊi!
{42545}{42590}Tarzan?
{43042}{43096}Ne moûeö me uhvatiti, Zugore.
{43099}{43150}Ne sad, deËki. U redu?
{43153}{43217}Nisam raspoloûena.
{43248}{43356}Hej! Rekoh, nisam raspoloûena! | Gubite se!
{43560}{43625}Oprostite.
{43628}{43770}Igra ne bi bila ista | bez Tarzana. Znate?
{43791}{43846}Ne mogu vjerovati da ga viöe nema.
{43892}{43971}Terk! Tarzan je ûiv!
{43974}{44024}- NemoguÊe. | - Ali Ëuo sam ga.
{44027}{44089}Govorio je: | "NeÊu nikomu reÊi."
{44091}{44180}Predugo si na suncu. Uzmi | dva manga i nazovi me ujutro.
{44182}{44274}»uo sam Tarzanov glas | s Tamne planine.
{44277}{44318}Zaöto ga nitko drugi nije Ëuo?
{44320}{44427}Ja sam slon. | OdliËno Ëujem.
{44467}{44563}Dobro. Da vidimo | moûemo li ga pronaÊi.
{44625}{44757}Terk... Tarzan je rekao | da nikomu ne kaûemo.
{44760}{44820}Ha? Oh.
{44823}{44855}»ek', Ëek'.
{44858}{44905}Ostanite.
{44908}{44957}- A, ne. | - Ne moramo.
{44960}{45015}Morate. Vi...
{45018}{45125}Morate ostati iza i... | Pokrivati nas. Da.
{45128}{45172}Ako itko pita,
{45175}{45271}recite da beremo | majmunske bobice.
{45274}{45305}- Jasno? | - U redu.
{45308}{45343}Majmunske bobice. Jasno.
{45346}{45429}Da, baö ste slatki. | Dobro? Tutanj.
{45600}{45690}Terk me uËila kako biti dobar | majmun glumeÊi Ëudoviöte.
{45693}{45762}Glumi da je ti, | ali ti nisi Ëudoviöte.
{45765}{45829}Ti si Zugor koji se pretvara...
{45859}{45916}Hej! »ekaj me!
{45945}{46001}Tvoj dom? Gdje spavaö?
{46004}{46096}Super je. | Imaö i svoj potok.
{46099}{46165}A sada, u öto je manje | rijeËi moguÊe,
{46168}{46218}öto uËiniti | da te se rijeöim?
{46221}{46261}NauËi me biti dobrim majmunom.
{46264}{46359}Majmun? Mali, ti nisi majmun.
{46394}{46441}E jesam.
{46477}{46525}Ne. Dokazat Êu ti.
{46528}{46585}Moja ruka: Dlake.
{46588}{46673}Tvoja ruka: Nema dlaka.
{46676}{46736}Nisi majmun.
{46765}{46816}Ali... Moram biti.
{46819}{46889}Moja mama je majmunica, | prijatelji su mi majmuni,
{46892}{46929}cijela obitelj.
{46932}{46991}Ako nisam majmun, onda...
{46994}{47029}Onda...
{47032}{47092}...öto sam?
{47117}{47159}Ne znam.
{47162}{47242}Moûda nekakav mutantski | bezdlaki pavijan.
{47245}{47310}Ili vrsta dosadne | ptice bez perja.
{47313}{47338}Ptice?
{47341}{47429}Ili rijetka vrsta | ruûne ribe.
{47432}{47483}- Ruûne? | - O, da.
{47486}{47566}Vrlo, vrlo, vrlo ruûne.
{47604}{47668}Eto. I mislio sam da nisi majmun. | Zavröili smo.
{47670}{47731}Ne mogu te nauËiti biti | neöto öto nisi. Bok.
{47734}{47809}»ekaj. Pomozi mi | doznati öto sam.
{47812}{47891}Dogovorili smo se... Zugore.
{48003}{48033}Dobro.
{48036}{48107}- Zugore, hvala ti... | - Stani.
{48110}{48161}Nikakvo mlako zahvaljivanje
{48164}{48240}neÊe se poticati | ni tolerirati.
{48243}{48302}Doi. äto prije otkrijemo öto si,
{48305}{48346}to Êu te se prije rijeöiti.
{48348}{48373}U redu.
{48376}{48431}- Hej, Zugore. | - Ha?
{48434}{48482}Ipak hvala.
{48783}{48877}Katkad mi je sve | izvan dosega
{48880}{48961}Ma koliko se trudio
{48964}{49084}Katkad mislim | da u meni nema niËega
{49140}{49241}Kada sve öto ûelim zadrûati
{49244}{49322}Od mene odlazi
{49325}{49449}I iako padam, | opet me doziva
{49502}{49591}No nastavljam traûiti | Potonuù Êu il'plivati
{49594}{49684}Nastavit Êu traûiti | pravoga sebe
{49687}{49790}Tko sam ja? | Reci mi
{49793}{49864}Odakle dolazim?
{49867}{49962}Tko sam ja? | Reci mi
{49965}{50096}Kao da se uopÊe | ne uklapam
{50221}{50323}Katkad poûelim pobjeÊi
{50326}{50398}I sve ostaviti
{50401}{50529}NaÊi mjesto | kamo pripadam
{50591}{50669}Nastavit Êu traûiti | I pronaÊi ga sam
{50672}{50762}Nastavit Êu traûiti | pravoga sebe
{50765}{50864}Tko sam ja? | Reci mi
{50867}{50943}Mogu li ikad biti svoj?
{50946}{51033}Tko sam ja? | Reci mi
{51036}{51092}Kao da se ne uklapam...
{51095}{51152}Znaö öto, mali? éilav si.
{51179}{51231}Mrzim ûilavost.
{51234}{51289}Kao da se ne uklapam
{51292}{51436}Ne, ne, ne | UopÊe se ne uklapam
{51531}{51635}Ja sam Zugor. Grrr!
{52159}{52220}- Teta Kala je tuûna. | - Zaöto?
{52223}{52274}Nedostaje joj Tarzan.
{52277}{52320}Tako je, maleni.
{52323}{52364}Ne plaËi, Tarzan je joö...
{52367}{52414}- Majmunske bobice. | - SjeÊaö se?
{52417}{52495}Znam. Nisam joj mislio reÊi.
{52498}{52549}- äto? | - Da je Tarzan ûiv.
{52552}{52604}I Terk i Tantor ga traûe.
{52607}{52652}Na Tamnoj planini.
{52718}{52794}Tarzan je ûiv?
{52797}{52881}Idem ih traûiti. | Ostanite tu, djeco.
{53229}{53313}Danas nije bilo baö najbolje.
{53316}{53378}Ali sutra Êemo opet pokuöati.
{53381}{53434}Nestrpljiv sam, uzbuen,
{53437}{53488}bez daha od iöËekivanja.
{53491}{53537}Dosta blebetanja.
{53540}{53623}Manje blebetanja, | viöe spavanja.
{53726}{53762}Ja, tu.
{53765}{53831}Ti, tamo.
{53834}{53890}Skroz tamo.
{53970}{54025}Ja Tarzan, ti gunalo.
{54421}{54456}Stare kosti.
{54459}{54499}Trebaö bolje gnijezdo.
{54502}{54577}Moja mama zna napraviti | baö dobro gnijezdo.
{54580}{54664}Da. I moja je mama | radila sjajna gnijezda.
{54667}{54695}Lijepo.
{54698}{54739}- Mekano. | - Toplo.
{54741}{54841}Jedanput je napravila gnijezdo | koje se njihalo izmeu dvije grane.
{54844}{54920}Kao da spavaö na zraku.
{55007}{55072}Kad si shvatio da si Zugor?
{55075}{55127}To je proölost.
{55129}{55192}- Sve je to proölost. | - äto se dogodilo?
{55195}{55236}Ostario sam. Ostavili su me.
{55239}{55304}Ista stara priËa. | Bu-hu. Baö tuûno.
{55328}{55377}Opasnost za obitelj.
{55433}{55471}Razgledat Êu...
{55474}{55522}Moram pripaziti. | Drûati ih podalje.
{55525}{55572}- Pravilo broj 1. | - Mogu pomoÊi?
{55608}{55656}Ne.
{55916}{56035}Terk, ne ûivi li Zugor | na Tamnoj planini?
{56038}{56108}Ne brini se za to.
{56111}{56198}Zugor je samo plod maöte.
{56201}{56258}Nije stvaran.
{56261}{56335}Dakako, ti to znaö | i ja to znam,
{56338}{56387}ali zna li on?
{56390}{56477}Zugor!
{56525}{56610}Hajde. Iö!
{56613}{56702}Vjerujem u Zugore! Vjerujem | u Zugore! Vjerujem! Vjerujem!
{56946}{56975}Jesam te.
{56978}{57072}- Jesi ga, Kago. | - Hej, pusti me.
{57075}{57184}Kago? Ovo nije ptiËica.
{57187}{57258}- Nije? | - Ne. Nije.
{57321}{57389}Hej, ne moûeö to raditi | mom bratu.
{57560}{57620}O, ne! Zugor je uhvatio Terk!
{57667}{57725}Pusti moju prijateljicu!
{57728}{57802}Uzmi mene umjesto nje!
{57805}{57875}HoÊeö malo?
{57878}{57963}Pojest Êe je. Uûas!
{57966}{58079}äto Êemo sad s tobom?
{58082}{58182}Znam. Bacimo je s litice | da vidimo moûe li letjeti.
{58185}{58238}Gorile ne lete.
{58241}{58296}Da? Kako znaö?
{58299}{58359}Jer smo mi gorile.
{58362}{58451}- Pa? | - I ne moûemo letjeti.
{58454}{58515}Da, ali da su nam kosti öuplje
{58518}{58571}i da imamo krila i perje,
{58574}{58631}bili bismo najveÊe ptice u gradu.
{58634}{58702}äto za ime...?
{58705}{58755}Mama, naöli smo gorilu!
{58758}{58795}A odakle je
{58798}{58883}ova slatkica doöla?
{58886}{58936}Hej, hej. Dosta, gospoo.
{58939}{58982}Trebam taj obraz za jedenje.
{58985}{59100}O, baö si slatka.
{59103}{59157}Odakle si, mila?
{59160}{59270}PriËaj nam o svojoj obitelji. | Ima li netko srebrna lea?
{59273}{59378}Zaboravite. NeÊu pjevati | i ne moûete me natjerati.
{59381}{59448}Kago.
{59702}{59807}Pokuöajmo ponovo. | Moûe, mila?
{59810}{59899}Kako si umakla Zugoru?
{59902}{60002}I odakle si rekla | da ti je obitelj?
{60005}{60114}Je li ondje lijepo? | Ima li puno hrane i vode?
{60117}{60206}Moûda bi nam jednom | mogla pokazati put.
{60209}{60276}Terk? Jesi li vani
{60279}{60366}ili si pojedena?
{60369}{60422}Ne ûelim nikog na planini
{60425}{60500}da mi tu prlja | i igra se s mojim stvarima.
{60503}{60543}To su moje stvari.
{60546}{60642}Hej! Zaöto se igraö | s mojim stvarima?
{60645}{60690}Napravio sam ti gnijezdo.
{60693}{60748}Ti si ovo napravio?
{60751}{60825}- Za mene? | - Dakako. Za tvoje stare kosti.
{60828}{60897}Kao öto ti ga je mama radila. | Iskuöaj ga.
{61114}{61179}To nije bilo dio dogovora.
{61182}{61220}Znam.
{61402}{61449}Dobro je.
{61452}{61524}Spavanje na zraku.
{61552}{61607}Ne znam öto si, Tarzane,
{61610}{61652}ali pametan jesi.
{61655}{61751}Kao ono öto si uËinio | s lijanom i nosorogom.
{61789}{61883}- Nikad nisam vidio niöta sliËno. | - Da.
{61886}{61951}Ali nisam pametan | da shvatim öto sam.
{61954}{62041}Nisam jak kao slon. | Visok kao ûirafa.
{62044}{62100}Ne mogu letjeti kao ptica.
{62195}{62246}Moûda nisam niöta.
{63231}{63321}ZnaËi, tu Êeö sjediti | i drûati me
{63324}{63366}dok ti se mama ne vrati?
{63369}{63401}Da.
{63404}{63470}- Cijeli dan? | - Da.
{63498}{63549}Razbit Êu te.
{63730}{63783}Sluöaj, Uto,
{63786}{63870}zaöto moraö raditi | sve teöke poslove?
{63873}{63926}Ha? äto? Teöke poslove?
{63929}{64012}Moraö sjediti sa mnom | dok se onaj lijeni Kago
{64015}{64063}zabavlja udarajuÊi svoje kamenje.
{64066}{64164}Ne znam, | ali ne Ëini mi se poöteno.
{64167}{64222}Ne, uopÊe nije poöteno.
{64225}{64301}Ni najmanje poöteno.
{64553}{64613}Hej, ovo nije poöteno.
{64616}{64681}- äto? | - Rekoh, nije poöteno.
{64684}{64735}Ja radim sve teöke poslove.
{64738}{64831}I ti moraö malo raditi, | pa ti evo, g. LijenËino.
{64834}{64882}Trpjet Êeö to?
{64885}{64954}- Trpjeti öto? | - Uto te uvrijedio.
{64956}{64985}- Uvrijedio me? | - Da.
{64988}{65065}- Uvrijedio si me? | - Da?
{65090}{65124}Ja Êu...
{65204}{65287}Nemate pojma | s kim imate posla.
{65349}{65389}Stani.
{65392}{65422}Uto, stani!
{65425}{65480}Gdje je?
{65483}{65541}»ekaj samo dok je opet uhvatim.
{65544}{65605}Ja Êu... Ja Êu...
{66664}{66728}Hej, uhvatio si bananu. Bravo.
{66731}{66798}Baö i ne. | Da sam Ëimpanza ili pavijan,
{66801}{66862}popeo bih se na drvo i uzeo sve.
{66865}{66934}Mogu uzimati | samo jednu po jednu.
{66961}{67034}Joö uvijek misliö da nisi niöta?
{67077}{67141}Moûda moûemo uËiniti | neöto po tom pitanju.
{67144}{67212}- Moûemo? | - Da, ja mislim,
{67215}{67265}buduÊi da nisi niöta,
{67268}{67331}a ûeliö biti neöto...
{67334}{67448}...mogao bi pokuöati | biti Zugor.
{67479}{67525}Zugor?
{67528}{67612}U redu je ako ne ûeliö. | Slobodno moûeö odbiti.
{67653}{67745}Ipak to moûe biti | priliËno samotno.
{67748}{67834}Misliö, bio bih poput tebe?
{67969}{68028}Opa! Zugor!
{68031}{68091}Da! Ja sam Zugor.
{68094}{68171}Grrr!
{68217}{68262}Pravilo broj jedan:
{68265}{68319}Ne trebamo nikoga | osim nas samih.
{68322}{68423}Ovo je naöa planina. Grrr!
{68426}{68476}Naöa planina.
{68512}{68558}VjeûbeniËe Zugore,
{68561}{68632}upotrijebi tu svoju lijanu | za prikupljanje doruËka.
{68635}{68679}Na zapovijed.
{68702}{68745}Zugore?
{68880}{68967}Znaö, ovo nije bilo | dio dogovora.
{68970}{69010}Znam.
{69166}{69264}Halo? Ima li koga?
{69267}{69310}Halo?
{69432}{69499}Neöto me uhvatilo. | »udoviöte!
{69502}{69562}Zbogom, okrutna dûunglo.
{69565}{69631}Propao sam! Propao!
{69634}{69693}Postat Êeö kokosova glava.
{69696}{69757}- Terk? | - Jedna jedina.
{69760}{69816}Hajdemo odavde.
{70021}{70064}Terk? Tantore?
{70067}{70166}Tarzane! | éiv si! éiv si!
{70169}{70226}Mislili smo da si mrtav, | a onda je Tantor...
{70229}{70324}»uo te, ali kad smo doöli | do Tamne planine, Zugor...
{70327}{70388}A onda su oni veliki majmuni...
{70391}{70464}A onda sam zapeo u rupi, | a Terk su pojeli.
{70467}{70509}Otprilike.
{70512}{70607}- »ekajte. Veliki majmuni vas gone? | - Vjerojatno su nam za petama.
{70610}{70688}Doite. Znam sjajno skloniöte.
{70738}{70783}Lijep ponovni susret.
{70786}{70889}éao nam je öto je pobjegla. | Ali ona je zla genijalka.
{70892}{70976}U redu je, deËki. | Sada ih moûemo slijediti.
{70979}{71065}- Kamo, mama? | - Da izbjegnemo Zugora, dakako.
{71402}{71486}äto radite ovdje? | Rekoh da ostanete doma.
{71489}{71527}Doma nam je dosadno.
{71530}{71573}I volimo majmunske bobice.
{71576}{71629}Ne traûimo majmunske bobice.
{71632}{71745}- Ali moûda Êemo ih naÊi. | - Dobro, ali ostanite blizu.
{71868}{71915}Daj se pokreni!
{71918}{71974}Majmuni su nas veÊ | mogli izlemati.
{72049}{72083}Opa!
{72086}{72127}Ha?
{72213}{72259}Jesmo li se izvukli?
{72262}{72321}Da, ovdje Êemo biti sigurni.
{72345}{72398}Baö ste mi nedostajali.
{72401}{72490}I ti nama, kompa. | Zato smo te doöli vratiti doma.
{72493}{72558}- Ne vraÊam se doma. | - Ne vraÊaö?
{72561}{72639}Ne. Sad sam Zugor.
{72642}{72691}Zugor? äto to znaËi?
{72694}{72763}Da ne trebam nikoga | osim samoga sebe.
{72766}{72835}- Nikoga? | - Nikoga.
{72838}{72881}A mamu?
{73057}{73122}Bolje joj je bez mene.
{73125}{73219}A i ne mogu se vratiti. | Sad sam Zugor.
{73222}{73298}Tko je uopÊe | to Ëudoviöte Zugor?
{73301}{73363}Rekao sam vam, nije Ëudoviöte.
{73366}{73431}- Nema Ëudoviöta. | - Nema?
{73434}{73488}Kako nema Ëudoviöta?
{73525}{73611}Mislim, nema Ëudoviöta...
{73614}{73686}- VeÊeg ili straönijeg... | - Hej!
{73689}{73748}Vidi öto sam naöao.
{73751}{73826}Pusti me! Pusti me!
{73829}{73864}Dobro.
{73994}{74070}äto...? Zaöto? Tko?
{74073}{74102}Zdravo.
{74235}{74295}- Zugore... | - Rekao si da nikomu neÊeö reÊi.
{74298}{74342}- ObeÊao si. | - Oprosti.
{74345}{74436}- Nisam mislio... | - Ti si Zugor?
{74439}{74486}Sve ovo vrijeme | moji jadni deËki i ja
{74489}{74591}bili smo u toj uöljivoj | dolini zbog tebe?
{74594}{74638}Trebao bih...
{74698}{74772}- Pusti ga na miru! | - MiËi se s puta, uöljivËe.
{74775}{74830}Znate öto, deËki?
{74833}{74967}Mislim da bi ovo mjesto | trebalo malo... preurediti.
{74970}{75007}Da!
{75010}{75070}Baö dobro. Baö dobro.
{75185}{75269}Hej, Kago, gle ovo.
{75272}{75356}SkoËica, skoËica, skok...
{75611}{75749}Vidiö? Nije lijepo | varati mamu Gundu.
{75752}{75808}- Zugore? | - Ti si kriv za ovo.
{75811}{75843}éao mi je.
{75846}{75899}Morao sam pomoÊi prijateljima i...
{76078}{76160}ZnaËi odatle ste svi vi.
{76163}{76215}Kako lijepo.
{76218}{76258}Brbljavica nam je odala
{76261}{76331}znamo gdje moûemo naÊi | novi dom.
{76334}{76380}Iscijedili su iz mene.
{76383}{76480}Hajdemo, deËki. | Preuzet Êemo susjedstvo.
{76483}{76609}I ovaj nam put | nitko neÊe smetati.
{76741}{76818}Evo je. Tamna planina.
{76943}{77026}Zugore! Zugore, gdje si?
{77055}{77102}Zugore.
{77105}{77157}Prvo pravilo...
{77202}{77283}Zugore, doi. | Trebamo tvoju pomoÊ.
{77286}{77374}- Upozorit Êemo Kerchaka. | - »ekajte. Idemo s vama.
{77377}{77451}Bez uvrede, | ali usporavat Êeö nas.
{77454}{77560}- Hajdemo, Tant. | - NeÊe stiÊi na vrijeme.
{77563}{77614}Samo ti poznajeö ovu planinu.
{77617}{77690}Ne. Nikad te nisam | trebao prihvatiti.
{77693}{77767}Mislio sam da si mi prijatelj, | a izdao si me.
{77810}{77918}To je bilo prvo pravilo, | a ja sam ga prekröio.
{77921}{77962}Molim te.
{77965}{78050}Znam da sam sve upropastio, | ali moraö pomoÊi.
{78053}{78079}Bu-hu.
{78082}{78120}To je moja obitelj.
{78123}{78164}Onda idi. Idi!
{78167}{78239}Ne trebaö me! | A ni ja tebe!
{78269}{78310}Dobro.
{79434}{79493}Bu-hu za mene.
{79714}{79790}- Znam kuda treba... | - Da, i ja.
{79793}{79856}- Onuda. | - Doite. Znam preËac.
{79859}{79923}- Tarzane! | - Ne!
{80098}{80144}Opa!
{80422}{80470}Nemojmo ovo | viöe spominjati.
{80510}{80554}Hajde!
{80659}{80717}Usporite. Nemojte predaleko.
{80720}{80774}- NeÊu. | - Ha?
{80777}{80830}Hej, vidi, mama. Beba.
{80833}{80875}Zaboga.
{80878}{80919}Mogu se igrati s njom?
{80922}{80974}- Mogu li? | - Pusti ga.
{80977}{81026}Tko kaûe?
{81091}{81143}Hej.
{81146}{81185}- Odbij! | - Da!
{81188}{81245}Ne moûeö to raditi mom bratu.
{81307}{81357}Mama!
{81438}{81509}- Mama, jesi dobro? | - Tarzane!
{81512}{81550}O, baö fino.
{81553}{81642}- Pusti ga na miru! | - Da vidimo moûe li letjeti.
{81645}{81689}Mama!
{81718}{81804}Zugor!
{82043}{82094}- Zugore? | - Tarzane!
{82097}{82135}Ali öto ti...?
{82138}{82170}Uspio sam!
{82173}{82258}Napokon sam otkrio öto si!
{82261}{82357}- Tarzan! | - Tarzan?
{82360}{82424}Da. Spasio si nas | od nosoroga!
{82427}{82513}I napravio sjajnu leûaljku! | I dohvatio one banane!
{82516}{82562}»iniö stvari koje | nitko ne moûe.
{82565}{82635}Mali, ti si Tarzan.
{82638}{82680}A sad ih sredi.
{83039}{83085}- Hej! | - Ha?
{83088}{83123}Hej!
{83126}{83164}To je on.
{83402}{83471}MiËi se, smrdljivi starËe.
{83474}{83507}Smrdljiv?
{83510}{83586}Pogodila si svaku granu | kad si padala s drveta ruûnoÊe.
{83589}{83683}Tako si koöËat da te sigurno | ni leöinari ne bi htjeli.
{83686}{83788}Hej, vodeni konj je zvao. | éeli svoje tijelo natrag.
{83837}{83885}Drûite se, maleni.
{83917}{83980}Teta Kala. Teta Kala!
{84204}{84270}Hajde. Penjite se.
{84364}{84403}Ha?
{84674}{84749}ZaËepi, krpetino stara.
{84752}{84826}Ti velika mjeöino | moËvarnoga plina.
{84829}{84879}Guöterove usne!
{84882}{84938}- Puûeva sluzi! | - äiömiöja bljuvotino!
{84941}{85000}Imaö lijepe oËi!
{85003}{85029}Ha?
{85059}{85148}Ovo je jezivo. äto je on?
{85151}{85198}Gdje je?
{85201}{85250}äto je to bilo?
{85315}{85363}Mama!
{85581}{85614}Hej!
{85666}{85704}O-o.
{86282}{86310}Ha?
{86385}{86450}Uto, Ëekaj me!
{86568}{86647}Teta Kala, drûi se!
{87176}{87228}- Mama! | - Kala!
{87352}{87434}To! Bravo, Tarzane!
{87657}{87708}Mislila sam da sam te izgubila.
{87711}{87761}Oprosti öto sam otiöao, mama.
{87764}{87808}Ali nisam te ûelio povrijediti.
{87811}{87852}Povrijediti?
{87855}{87929}Tarzane, spasio si me.
{87979}{88015}Mama!
{88018}{88135}- Mama! UpomoÊ! | - Goni nas.
{88138}{88204}Posvuda je!
{88207}{88250}Zdravo, deËki.
{88253}{88305}Mama?
{88308}{88394}Misli da imam lijepe oËi.
{88643}{88705}»ek' malo. NeÊemo | nikoga prebiti?
{88708}{88764}- Da. | - Ne, mili moji.
{88767}{88835}- S tim je gotovo. | - Ali, mama...!
{88838}{88900}Usnice!
{88903}{88982}Koliko puta moram reÊi, | bez svae.
{88985}{89070}Nema viöe svae | ni sa kime.
{89073}{89117}Da, mama.
{89251}{89344}Bezvremenska tajna ljubavi.
{89777}{89828}U redu, | mislim da sam shvatila.
{89831}{89912}Mislio si da nisi niöta, | no zapravo si neöto,
{89915}{89975}öto te Ëini bilo Ëime?
{89978}{90035}- Ne, mama. | - Kako je ono bilo?
{90038}{90112}Nema veze. Imala si pravo.
{90115}{90219}Ja sam dio obitelji.
{90222}{90312}Tarzane, ponosim se tobom.
{90397}{90431}- Zugore! | - Tarzane.
{90434}{90513}- Doöao sam se oprostiti. | - VeÊ?
{90516}{90572}Pa, znaö.
{90637}{90682}Trebaju me.
{90736}{90804}- Uskoro Êu te posjetiti. | - I bolje ti je.
{90807}{90862}I, Zugore...
{90865}{90932}Hvala. Hvala na svemu.
{90935}{91010}Ne. Hvala tebi.
{91158}{91227}DeËki, vas dvojica Êete popraviti
{91230}{91272}ono lijepo Zugorovo drvo
{91275}{91331}koje ste razbili u komade.
{91334}{91376}- Ali, mama... | - DeËki.
{91379}{91460}Pravilo broj jedan: | Nikad ne odgovarajte svojoj majci.
{91463}{91498}- Nismo... | - Bu-hu.
{91501}{91536}- Samo smo... | - Bu-hu.
{91539}{91584}Bu-hu za vas.
{91612}{91674}Niöta ne bjeûi Ëudoviötu!
{91719}{91764}Stvarno?
{91936}{91991}äto je to bilo?
{91994}{92074}To je, prijatelju moj, | Tarzan.
{92077}{92164}Poneöto od svega
{92167}{92255}UËinit Êe me svime | öto ûelim biti
{92258}{92309}Tko sam ja?
{92312}{92420}Znam da mogu sve
{92423}{92512}Tko sam ja? | Znam
{92515}{92658}Da, mogu biti sve | Baö sve öto poûelim
{92659}{92859}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan 
