{840}{998}Kad sam rekao da se sjeæam to dana, nisam lagao.|Volio bih jesam, ali jednostavno ne mogu.
{1030}{1173}Èudne su te stvari koje vam ostaju u glavi. Mislite|da nisu važne, èak i ako se dešavaju ispred vas.
{1214}{1358}Ponekad je to ono što ostane.|Ponekad i najvažnije stvari jednostavno proðu.
{1398}{1505}Tako brzo odu, kao|da ih nije ni bilo.
{1529}{1720}Ne sjeæam se tog dana. Ali mogu vam reæi o tome kad|sam imao 5 god. i kada mi je tata kupio sladoled.
{1773}{1903}Okus sladoleda koji mi je tata kupio|je bio isti kao roza žvaka.
{1935}{2085}I o jednoj djevojci.... imala je |nacrveniju kosu koju sam vidio.
{2151}{2319}Sve je tu, kad da se sad dogodilo. Ali tog dana|se ne sjeæam. Barem ne detalja koje su oni htjeli.
{2382}{2530}Sjeæam se da je to bio prvi topao dan|proljeæa i kako me sunce peklo po vratu.
{2644}{2876}Ovo mi je jedan prijatelj rekao ''vjeruj|da je život više od nekih njegovh dijelova...
{2914}{3080}Sjeæam se svake rijeèi. Ali kad se|toga sjetim, jedno mi padne na pamet...
{3139}{3242}Što ako ti dijelovi ne mogu|da se spoje?
{4314}{4363}Samo sekundu.
{4503}{4553}Naprijed.
{4650}{4846}Kako si, Beck? - Dobro, OK.|-Kako si ti, tata? - Gdje je Ryan?
{5688}{5878}I ja sam joj to govorio, ali nas ne sluša.|-Mislim da ne zvuèim dobro kao ostale.
{5935}{6070}Kate posebno. Ona je dobra pjevaèica.|-Koristit æe ti. Nisi se bavila glazbom.
{6109}{6278}Tako je èudno. Sjediš tamo,|i odjednom je vrijeme za pjevanje.
{6431}{6537}To treba zvuèati lijepo.|-Meni se sviða tvoj glas.
{6564}{6750}To bi mi rekao i da sam oèajna.|-Misliš da je to loše?- Ne.
{8343}{8551}Javi mu da si se preselila u ASU.|-Imam još par dana.
{8720}{8820}Halo?|Polako, ne razumijem te.
{9059}{9115}Ne, odmah dolazim.
{9292}{9331}Le?
{9718}{9801}Bok, mama.|-Jesi li dobro?
{10087}{10170}Mislim da sam pogriješio.
{10506}{10690}Gledaš vijesti? - Da. - Kažu|da osumnjièeni ima 16 godina.
{11006}{11073}20 puta?|Da li je ikad bilo 19?
{11106}{11195}JBK, šefe.|-Jebeno Bolesni Klinac.
{11434}{11581}Imate li glazbu na tome? - Što?|Imate li normalni radio za glazbu?
{11645}{11793}Kad èekate pored ulice da netko|prekoraèi brzinu, glazba ubija vrijeme.
{14900}{15109}On to nije uèinio. Moram ga vidjeti,|molim vas. -Svake druge nedjelje, u 4.
{15155}{15300}Molim vas, molim vas.|Samo na minutu, samo jednu minutu.
{15368}{15493}Ne mogu ništa|uèiniti, zato idite.
{15590}{15693}Leland Fitzgeralde? Jesi li ti|to uèinio? Imaš li što reæi?
{15825}{15956}Zašto si to uèinio? - Zbog tuge.|-Èije tuge?
{16021}{16112}Vaše tuge.
{16518}{16630}Da vidim ruke.|Naprijed.
{16912}{16987}Gospodo, hodajte.
{17628}{17703}Torba?|-Torba.
{18018}{18134}Dobro jutro, imate li možda marku?|-Samo da vidim.
{18190}{18375}Nova sam, pa ne znam gdje je što.|-Moram poslati raèun.
{18506}{18649}Evo. - Hvala.|Ja sam Pearl.
{19015}{19150}Ovo sutra je formalnost. Sudac|æe te vratiti ovdje.
{19181}{19337}Poslije toga ide saslušanje i presuda.|Pomozi mi malo.
{19368}{19543}Optužen si za prvostupanjsko ubojstvo.|Ako odeš na sud za punoljetne
{19553}{19625}dobit æeš smrtnu kaznu.|Ako imaš sreæe, doživotnu.
{19718}{19859}Znaš li što to znaèi?|-Nisam idiot. Cijeli život u zatvoru.
{19996}{20221}Što sam ti rekao? Naslovna strana,|Leland Fitzgerald, ubojica retarda.
{20321}{20508}Ne bi nikad pogodio tko mu je tata.|-Kladim se na Sotonu. -Albert Fitzgerald.
{20550}{20678}Bila sam blizu. - Što je s njim?|-Odakle da krenem... pijanica...
{20700}{20837}Odvratan je. -Pa što? Ne možeš|ga osuditi zbog njegovog života.
{21481}{21703}Oprostite, mogu li pogledati vaše novine?|-Naravno. ''posao'' ili ''život''?
{21737}{21836}Prièekat æu naslovnu stranu, hvala.
{21908}{22131}Oprostite, jeste li vi glumac? |- Svi smo, draga.- Ne, mislim, poznat.
{22181}{22368}Poznati ste mi. - Bio sam u mjziklu Stanleya|Kubricka "Pirati". Stotnik Morgan.
{22481}{22590}Kada završite sa novinama....
{22956}{23055}Što si ti ovdje?
{23093}{23212}Ne pitam te jer si puno usrao,|jer to veæ znam.
{23265}{23458}Jedan me zajebao za trebu.|Nabio sam mu olovku u oko.
{23503}{23634}Bijelci nisu neki gangsteri. Posebno ako|izgledaju kao Eminem.
{23681}{23815}Vi baš znate zasrati, ha?
{24100}{24156}Sjednite svi.
{24196}{24387}Malo sam spor danas. -Opet si pio|onu brlju? - Bez komentara.
{24412}{24527}Oslijepit æete od toga.|-3 dolara 2 litre? Kako da propustim to?
{24565}{24768}Vi ste novi. Kako se zovete? - Leland|P. Fitzgerald. - Ja sam Pearl Madison.
{24808}{24987}Ja sam vam nastavnik za sve koliko |god dana, tjedana ili mjeseci bili ovdje.
{25115}{25315}Pearl, kad æeš dovesti onu plesaèicu?|-Èim doðe iz L.A., bit æe joj drago da vas vidi.
{25343}{25387}Lažovu.
{25578}{25654}Zdravo, gðo Pollard.
{25743}{25854}Budni ste cijelu noæ?|-Da.
{25956}{26056}Da vam zapalim?
{26323}{26500}Kako je mogao znaèiti tom djeèaku|toliko da ga povrijedi?
{26662}{26793}Stvarno ne znam što reæi.
{26825}{26973}Znajte da, ako išta mogu uèiniti...|- U redu je, dušo.
{27598}{27787}U Veneciji nema zemlje uopæe, ha?|Samo voda? -Kanali, da. Nema ni automobila.
{27806}{27962}Èuju se koraci. -Molim? -Pošto|nema automobila, samo se koraci èuju.
{28048}{28281}Pazi, u Veneciji ima malo samoubojstava,|jer ako skoèiš sa zgrade, padaš u kanal.
{28354}{28475}Sutra æemo o tome.|Sat je gotov, donesite knjige ovdje.
{28861}{29075}Mogu li uzeti da pišem nešto?|-Nažalost, ne može. Ali ja æu ti èuvati.
{29231}{29399}Ljubomoran sam, kada si bio u Italiji?|-Tata mi živi u Parizu, ponekad idemo tamo.
{29481}{29543}Vidimo se.
{30056}{30156}Ti si ubio onog retardiranog?
{30217}{30293}Jesi ti neki sotonist?
{30448}{30543}Što ti je s rukom?|-Probo sam se.
{30575}{30762}Ako se želiš ubiti, pokušaj|u trbuh. -Samo sam htio vidjeti kakav je osjeæaj.
{30904}{31037}Da li je boljelo? Trebao si mene|zamoliti, uèinio bih ti.
{31643}{31706}ZNAM ŠTO HOÆE OD MENE
{32060}{32137}Hvala. -Drago mi je da| vidim da netko želi pisati.
{32262}{32325}Pearl, mogu te nešto pitati?
{32418}{32612}U vezi tvog imena... -Pitaš se zašto|Pearl (Biser)? Voliš košarku? - da.
{32663}{32807}70-ih je Earl Monroe ''Pearl'' igrao za Nickse.|-Earl Pearl? -Da.
{32875}{33031}Moja mama nije voljela sport, ali ju je|tata nekako nagovorio da ide.
{33061}{33237}Earl je tada postigao 33 koša. Tada|je moja majka samo prièala o tome
{33249}{33385}kako je on igrao kao plesaè,|jer mu je kretanje kao poezija.
{33531}{33699}Tada je bila samo ta prièa, ali par Božiæa|kasnije, prièao sam s tatom
{33723}{33893}i on mi je rekao da su poslije utakmice|otišli kuæi  i... poštedio me detalja.
{33941}{34072}i 9 mjeseci kasnije ... -Evo Pearla.|-Da.
{34112}{34200}Vjeruj mi, bolje ti je da staviš|olovku u èarapu.
{34354}{34543}Znaš što žele. Žele razlog. Nešto što|bi povezali sa zakopanim kostima.
{34606}{34743}Tako duboko su zakopane, da izgleda|kao da se nije ništa dogodilo. Žele da se kajem.
{34775}{34930}Možda su krivi moji roditelji, ili TV|ili filmovi...
{35031}{35292}Možda je djevojka kriva. -Jesi li se ikad|pitao da li postoje anðeli? -Možda, kao mali.
{35357}{35581}Kad sam bio mali, baba mi je umrla,|i svaki put kad bih ukrao slatkiš...
{35617}{35818}ili kad bih se igrao sa sobom, dobivao|bih osjeæaj da me ona gleda.
{35893}{36085}Mislim da oni ne špijuniraju nas, nego|da nas èuvaju. Anðeli èuvari.
{36148}{36300}Brinu se o nama. Brinu se da nam |se ne desi ništa loše.
{36410}{36598}Kako je onda skoro sve loše?|-Možda su lijeni.
{36675}{36925}Smiješno je... lijeni anðeli. Zamišljam ih|kao debele ljude sa krilima.
{37187}{37437}Budi ti moj anðeo èuvar.|Neka sve bude u redu.
{37518}{37693}Kosa ti miriši na jagode. - To mi je|šampon, ludo, ne kosa.
{37757}{37925}Sviða mi se i tako. -Ozbiljna sam,|reci da æeš uvijek biti tu.
{37968}{38181}Ponekad sam negdje drugdje.|-Reci mi da æe sve biti u redu.
{38247}{38525}Ja ne mogu to obeæati...|-Znam, ali ponekad kažeš nešto
{38537}{38668}što nije istina, ali to stvarno želiš.|Možda je to dovoljno.
{38822}{38906}Reci mi da æe sve biti u redu.
{39206}{39275}Sve æe biti u redu.
{40392}{40517}Naravno da moraš ostati.|Nije da sam sretan, ali razumijem.
{40610}{40706}Voda, Miranda.|Ne, sipam vodu.
{40800}{40912}Slatka H2O.
{41068}{41143}Istinu? Dobro.
{41174}{41387}Dobit æu nešto novo.
{41416}{41568}Pišem istu prièu 3 godine, |i ništa od toga.
{41662}{41812}Cijenim to, draga, ali mislim da |ljudi ovo ne èitaju.
{41875}{41988}Miranda, sretan sam zbog tebe.
{42055}{42176}Sviða mi se to. I to je možda|onda šansa koju si tražila,
{42206}{42329}a kada to doðe u to moraš|zagristi. Razumijem to.
{42425}{42525}Bilo bi mnogo lakše da si ovdje.
{43237}{43410}Sjeæam se kada su nam životi bili|neobièni. Kada smo gorjeli skoro kao vatra.
{43473}{43637}Sada je drugaèije. Životi su bez|smisla, ili èak bez nade.
{43699}{43848}Vrijeme se mjeri samo gubitkom.|Posla, kombija...
{44298}{44343}Bok, Bet.
{45867}{45993}Jesi li dobro?-|Molim? Što si rekao?
{46031}{46204}Pitao sam jesi li dobro?|-Da, samo onaj...
{46437}{46625}Izgleda kao da ti je on smetao... -U redu je.|Stalno se dogaða. Mislim da je zbog odjeæe.
{46676}{46861}Moram je nositi u školi u koju|idem, da ne bi stršala od ostalih...
{46899}{47067}a u stvari samo pali napaljene tipove.|Je li to katolièka škola?
{47154}{47292}Ne, suprotno. Za zeznute ljude.|-Na koji naèin?
{47381}{47568}Na svakakve. - A kako si ti zeznuta?|-Došao si me ispitivati o mom životu?
{47657}{47842}Ne, došao sam jer sam mislio da ti onaj|smeta. I jer mislim da si jako lijepa.
{48012}{48180}Nitko više ne govori lijepa. Govore,|treba...
{48216}{48387}Treba znaèi slatka ili tako nešto.|Ali meni se sviða ''lijepa''-
{48435}{48555}Super je rijeè. Hvala ti što|si mi rekao da sam lijepa.
{48650}{48826}Ja sam Leland P. Fitzgerald.|-Becky Pollard.
{48931}{49087}Ne krivim Becky. Treba mi biti|krivo zbog onoga što joj se dogodilo.
{49168}{49292}Ali ja sam svoje suze isplakao.
{49331}{49512}Posljednji put sam plakao na bakinoj|sahrani. Sjeæam se neke male...
{49687}{49812}ja nisam želio da me ona |vidi kako plaèem.
{49906}{50023}Ali suze su same išle.
{50068}{50204}Tada sam shvatio da suze|ne mogu oživjeti mrtve.
{50437}{50573}Ima još nešto o suzama...
{50698}{50822}One ne mogu vratiti ljubav|koje više nema.
{50975}{51068}Ja sam, Beck. |Ista stvar je s molitvama.
{51106}{51238}Pitam se koliko života ljudi protraæe|na suze i molitve tražeæi da se nešto desi.
{51611}{51711}Lijepo je imati nekoga za kriviti|za sve loše stvari.
{51807}{51925}Što je bilo?|-Ništa, samo ovo ide malo brzo.
{51972}{52179}Ne kažem da je to loše...|ali ja nisam obièno takva.
{52225}{52365}Posebno ne sa kolegom.|-Koliko ti treba da zavedeš kolegu?
{52410}{52526}Nisam te ja zavela.-|Ma, jesi, prelijepa si.
{52586}{52709}Ti si i više.|Ne znaš koliko si lijepa.
{52761}{52904}Smrtonosna si. |Nemoæan sam.
{52982}{53075}Ostat æeš?|-Da.
{53163}{53323}Usreæila si me.|Jer te želim poljubiti.
{53562}{53654}Mogu li te poljubiti?
{53925}{54045}Nedostajala si mi.|Uvijek mi nedostaješ.
{54488}{54647}Znaèi, ti si pisac?-|NIsam od nonih koje ljudi èitaju.
{54780}{54911}O èemu pišeš?
{54945}{55145}Jesi li èula za onog malog što je|izbo onog retardiranog? - Da.
{55198}{55378}Želim o njemu pisati.|Želim napisati knjigu o Lelandu.
{55544}{55696}Možda je Bog tu jer se ljudi plaše|loših stvari.
{55905}{56060}Oni misle da se Bog i Vrag|igraju igre.
{56419}{56505}I nikad ne znaju na kojoj|æe strani završiti.
{56994}{57171}Ovo je moj brat, Ryan.|-Bok, Ryane.
{57232}{57352}Drago mi je. - Pjevaj pjesmu.|-Samo to radi.
{57551}{57667}Èim poènem pjevati, on poludi.|I ne znaš što želiš, glupko?
{57727}{57910}Ona igra vjerojatno znaèi kad |ljudi pokušaju nešto dobro, a ispadne zlo.
{58024}{58167}Nemoj ti meni. Zašto on zaslužuje |posebnu pažnju?
{58196}{58353}Razumijem da svi trebaju biti isti.|Ali ovaj je drugaèiji.
{58377}{58542}Ova sluèaj nitko do sada nije imao.|-Odgovor je i ostat æe ''ne''.
{58612}{58794}Neæeš se sastajati ni sa kim|vam uèionice. Jasno?- Vrlo.
{58828}{58975}Charlie ti je objasnio. Ne moraš|popunjavati molbu niti išta.
{59008}{59203}I neæu, samo æu reæi da sam| uèinio to. -Ako to napraviš, otiæi æeš odavde.
{59236}{59377}Ne želim te izgubiti. Želim|saznati više o Lelandu.
{59432}{59608}Jesi li rekao da ti je djevojka u L.A.?|-A taj miris? - Koji?
{59637}{59742}Miris djevojke?
{59929}{60058}Bar razmisli o tome.|-Razmišljam o mnogo stvari.
{60266}{60446}Dobar dan, ja sam Beckyn prijatelj. |-Što se dogodilo? - Uletio je u žbunje.
{60535}{60650}Da pogledam to. - Idemo za 10 minuta...|Bok, gdje je Becky?
{60688}{60796}Što je napravio? |-Ništa, potrgao je rukav.
{60838}{60974}Ne mislim da je pokušao zeznuti|nešto. Kao da je to morao napraviti.
{61001}{61136}Hvala ti što si ga dopratio.|-Veæ neko vrijeme se družimo...
{61158}{61342}Je li Becky spominjala nešto?|-Nije se pojavila.
{61419}{61602}Vjerojatno nije htjela da se danas |vidimo. Ali volim otpratiti Ryana.
{61649}{61823}Hoæeš prijevoz kuæi?| Allen te može povesti.- Hvala vam.
{62032}{62259}Ideš li na posao? - Ne.|Mislim... samo par stvari...
{63396}{63432}Stani.
{63846}{63887}Idemo.
{64217}{64290}Je li to sve?|-Da.
{64341}{64502}Nevažno je to što nema dosje|uslijed težine optužbe.
{64532}{64705}Odbija se zahtjev da budeš u starateljstvu|majke! Da li bi dodao nešto, mladiæu?
{64799}{64869}Ne.
{65037}{65159}Ti živiš sa Pollardovima?|-Da, izgleda èudno.
{65204}{65323}Ne. -Ne misliš da je |èudno? -Ne.
{65525}{65728}Moja mama je poginula prošlog ljeta |u saobraæajnoj nesreæi. Tata je bliskiji
{65738}{65859}sa Tanjom, mojom sestrom.|Nije ga zabrinulo što se selim.
{65891}{66050}Odbaci me do škole.|-Nije problem da te odvezem kuæi.
{66110}{66298}G. Pollard je rekao da ide na trening.|-Prestao sam prošli tjedan.
{66323}{66475}Što? - Bio sam loš.|Nisam se mogao pribrati.
{66575}{66699}Julie i ja idemo na ASU sljedeæe godine|Bit æe bolje tad.
{66846}{66900}Torba?|-Torba.
{66940}{67089}Hvala. - Ja gubim.|-2:0 za Spurse, nije mnogo.
{67113}{67245}Znaš da Sunsi uvijek gube prvo.|-Ne znam za ovaj put.
{67299}{67487}I ti si se zainteresirao za onog.|Teško mi je zamisliti mamine maze
{67500}{67667}da naprave tako nešto. Ali ovaj se razlikuje.|-Fascinantan je.
{67726}{67849}Ti si pisac. Prièaj.|To i hoæu.
{68201}{68421}Jesi li èitao Frosta? - Znam što želite.|-Samo želim s nekim prièati.
{68561}{68755}To su htjeli i na suðenju.|-Želite ''zašto''.
{68870}{68955}Možda se ovo jednostavno dogodilo.
{69135}{69388}Zar nije utakmica sad? - Koja?|-Možete li promijeniti program? -Da.
{69733}{69907}Sviða mi se naslov. -To ne znaèi da sam|predsjednik. To je šala.
{69983}{70202}O èemu pišeš? -O mom viðenju svijeta?|Kako ga ti vidiš? - Pun je prilika.
{70335}{70616}A ti? - Vjerojatno kao vi.|Ali mnoge loše stvari se ne vide.
{70662}{70838}A što je loše?|-Kada vidiš što je tu ustvari.
{70862}{70965}Tuga?|-Nije ti rekao što to znaèi?
{71062}{71194}Nije mnogo prièao. Kada je došao|samo je govorio da je pogriješio.
{71257}{71427}Vidjela sam mu ruku i odvela ga|u bolnicu. 
{71495}{71698}Uvijek je tu. Èak i kada sve izgleda|dobro. Djeca se igraju, parovi ljube...
{71760}{71950}Veæina ljudi je ne vidi. |-Zašto?
{71985}{72154}Isto kako i ljudi izmièu stvari.|Kako svi umiru iznutra.
{72250}{72408}I ti se na isti naèin osjeæaš tužan?|-Ne osjeæam skoro ništa.
{72494}{72661}Jesi li išta primijetio u vezi njega?|-Danas? -Kad si ga posjetio.
{72961}{73120}Èim je došao od tebe, vidjela sam da nešto|nije u redu. Mislila sam da ste se posvaðali.
{73196}{73348}Možda ga je rastužila ona djevojka.|Ljudima ponakad ne uspije.
{73402}{73546}I nitko nije kriv. -Imaš zreo pristup.|-Ne znam.
{73575}{73703}Reci mi kakva ti je djevojka?|-Miranda? Sjajna je.
{73730}{73951}Ona druga. - To se jednostavno dogodilo.|-Da li bi to povrijedilo Mirandu?
{73989}{74172}Da.|-Zašto si to onda uèinio?
{74232}{74366}Ona neæe saznati.|-Da li je to onda u redu? - U redu?
{74465}{74626}Mirande nema dugo, tako da ne znam|na èemu smo. I samo sam èovjek.
{74650}{74830}Ljudi to govore samo kad nešto|loše naprave. Nitko ne govori 
{74846}{74961}''ja sam samo èovjek''|kada spase dijete iz požara.
{75172}{75234}Hvala ti.
{75537}{75628}Htio sam ti nešto reæi|o Becky.
{75745}{75900}Ti znaš zašto je ona u onoj školi?|-Rekla mi je da je zeznula.
{75936}{76077}Nisi pitao kako? -Rekla bi mi da je|važno.
{76195}{76288}Droga je u pitanju.
{76335}{76536}Ne želim ti prièati ako ne želiš|èuti. - Ne, možeš.
{76560}{76779}Bila je sa jednim Kevinom, on ima|20 godina. I dila drogu.
{76878}{77091}Pobjegla je s njim i uništila se.|Gða Pollard je morala iæi po nju.
{77223}{77420}Kevin danas izlazi iz zatvora.|-Dovest æu je za par minuta.
{77552}{77687}Što je to bilo? - Ne znam, samo sam|potpisala. Koji je danas nadnevak? - 24.
{77725}{78010}Približila se roku. Da li si joj rekao?|-Da... ali možda još nije sigurna.
{78095}{78311}Možda se želi uvjeriti da je to najbolje|za nju. -Vidjela sam vas, kad si je grlio.
{78350}{78545}I kako je gledaš dok spava. Brini se|o njoj. Ne mogu i nju izgubiti.
{78645}{78823}Pogledaj to sunce.|Ni ne sjeæam se kako je to.
{78874}{79029}Što si ti uèinio?|-Pogrešno mjesto, pogrešno vrijeme.
{79099}{79294}I to je protuzakonito?|-Je, ako si crnac od 17 godina.
{79426}{79500}Živio Sotona.
{79862}{80026}Znam da si tu.|Javi se, ocu da te vidim.
{80111}{80358}Nedostaješ mi, želim te vidjeti.|Pošto si ovdje, možda možeš doæi.
{80612}{80736}Provjeri Martina Engla.
{80803}{80878}A David Steat?
{80998}{81065}Samo još jedan, Edgar Pinkerton.
{81166}{81289}Stvarno? Mogu li dobiti|broj sobe... Dobro.
{81350}{81441}Da li postoji bar u hotelu?
{81555}{81724}Oprostite, ne daju mi da pijem sam.|Pa, mogu li reæi da pijem s vama?
{81766}{81924}Izmišljate li?|-Da.
{81953}{82100}Može, ali u baru nema ništa na kredit.|Piæe? - Hvala.
{82172}{82323}Oprostite, ali ja sam vaš obožavatelj. Èitao| sam sve vaše... -Oèigledno i ''Pad Edgara''.
{82363}{82486}Iz toga vidite da nisam peder, pa vas|neæu jebati, a vjerojatno ste èuli da sam 
{82495}{82662}i kreten pa neæu èitati vašu|autobiorafiju i slati je mom agentu.
{82725}{82860}Ja radim u popravnom domu|gdje je Leland.
{82892}{83061}Kako je on? - Dobro, ali je izoliran.| - Možete li srediti da ga vidim?
{83084}{83252}Ne, ja sam samo nastavnik. U nedjelju|su posjete... -Mislite da ne znam to?
{83347}{83489}Je li to uèinio? -Nije mi dozvoljeno da o tome|prièam van...- Rekao vam je nešto.
{83650}{83776}Rekao je da je, ali ne znam zašto.|A mislim da ni on ne zna.
{83816}{83983}On uglavnom izleda nezainteresiran za |svoju sudbinu? - Nezaineteresiran?
{84037}{84214}Ako mislite da imate neke informacije,|griješite. Nismo bili bliski.
{84259}{84454}'Amerika je preglasna' ste napisali 94-te, 95-te,|znaèi Leland je imao... -Nije mi to jaèa strana.
{84489}{84650}Je li bio ljut što ste otišli? - Ne zanima me |prouèavanje ljudskih reakcija.
{84677}{84878}Ne slažem se, èitao sam vaše knjige...|-To ne pomaže. - Posjeæivao vas je.
{84907}{85077}Rekao je da je dolazio par puta godišnje.|Kakve su vam bile posjete?
{85116}{85335}2. poglavlje? - Molim? - Mašta.|Niste ovdje zbog mog sina...
{85412}{85557}Ovdje ste jer ste namirisali dobru knjigu,|a ja sam 2. poglavlje.
{85614}{85819}Želim da pišem o vašem sinu, ali ne i da|ga iskoristim. - Sretno sa romanom.
{86099}{86252}Nisam vidio tatu od moje 6. godine.|-Mislio sam da ste putovali.
{86417}{86559}Slao mi je avio-karte otkad sam|imao 12. -Nisi bio u Parizu?
{86636}{86787}Nisam ni prièao s njim otkad je otišao.|Ponekad bi mi slao novac za roðendan.
{86875}{87059}Jedne godine je htio da doðem za Božiæ.|Prvo sam morao do New Yorka, pa u Pariz.
{87117}{87329}Ali sam ostao u New Yorku. Rekao sam |tati da ima elektriciteta u zraku.
{87397}{87511}On se nije bunio.
{87573}{87726}Ali nisam mogao naæi sobu.|Nitko djetetu nije htio dati sobu.
{87889}{88129}Bio sam u kinu, i jedna obitelj je|sjela do mene.
{88186}{88359}Primijetili su da imam gomilu torbi.|Pitali su me što æu ovdje.
{88416}{88534}Rekao sam da želim biti tu.|I to je privuklo pažnju majke.
{88620}{88800}Zove se Angela, ja je zovem gða Calderon.|Bila je zabrinuta.
{88889}{89025}Htjela je da provedem praznike s njima.|-Vidjelo se da su bogati.
{89053}{89239}Kæerka je bila mali snob, ali dobra.|Pokušavala je da me poljubi, ali ...
{89295}{89489}Svi su bili fini, ali posebno gða|Calderon. Volio sam je gledati u oèi.
{89537}{89712}Kao da sam vidio elektricitet cijelog grada|u njenim oèima. Pored nje nisam bio 
{89721}{89849}usamljen. Pored nje je |sve bilu u redu.
{89896}{90125}Ili pogrešno, a ti to nisi vidio. - Tata mi je|poslao jednu kartu na proljeæe.
{90278}{90500}Bila je za Italiju. Htio je vidjeti svijeta.|-Gdje si bio posljednji put?
{90587}{90769}Tata je rekao da ide na proljeæe |u New York. - Vidio si Calderonove?
{90807}{91048}Da li se nešto dogodilo? -Velik je to grad.|Uvijek se nešto dogaða.
{91746}{91878}Gdje je ona?|-Tko? Tko si ti?
{91910}{92061}Allene... - Hajde, idemo.|Gdje? - Idemo kuæi.
{92132}{92348}Ne želim te tuæi, ali ovo je moj stan.|I želim znati tko si ti.
{92527}{92572}Prestani!
{92610}{92737}Imaš li pojma što si uèinio mojoj|obitelji?- Prestani!
{92787}{92900}Uništio si joj obitelj.|-Prestani!
{92954}{93050}Jebeni narkomane!
{93120}{93221}Glupane!
{93647}{93762}Ne znam definiciju ljubavi.|-Znaš to u srcu.
{93798}{93972}Ljubav je samo rijeè.
{93988}{94124}Jesi li rekao Becky da je voliš?|A ona tebi?
{94197}{94414}Ali raskinula je. - Nisam nikad bio ljut| zbog toga.- U redu je. Imaš pravo.
{94492}{94648}Zašto? - Samo si èovjek.|Mislim, èovjek si, je li tako?
{94773}{94899}Ako ti to kažeš.|-Hvala ti za ovo što si uèinio.
{95015}{95178}Trebamo prièati. Znam da nije|najbolje vrijeme... - Je.
{95271}{95438}Selim se u Iowu.|Ako se predomisliš, razumjet æu.
{95521}{95744}Zašto mi ništa nisi rekla?|Ali u redu je.
{95809}{96034}Mogu biti s tobom, a da krenem u |školu sljedeæeg semestra. - Ovo je u vezi nas.
{96291}{96633}Znaš što mislim, i ako imaš nešto reæi,| reci. -Ne trebamo planirati selidbu.
{96762}{97060}To znaèi da ne idemo, ili ...? -Ja te volim,|ali mi smo zajedno veæ dugo.
{97088}{97346}Otkad si se uselio, kao da smo vjenèani.|-Oprostite, ali da prièamo u vezi sutra.
{97387}{97492}Evo, dolazim.
{97650}{97884}Ovo mi ne izgleda kako treba,| možda je bilo previše prerano...
{97911}{98100}Promijenili smo se oboje... -Ja nisam.|-Onda sam ja i ne želim da ideš sa mnom u Iowu.
{98171}{98295}Žao mi je.
{98319}{98380}Èekaj, Julie!
{98997}{99109}Evo definicije: ljubav je kad ne|možeš nekoga izbaciti iz glave.
{99147}{99303}Prva misao ujutro i posljednja naveèer.|Možda nije u srcu, ali jest u glavi.
{99484}{99621}Da li ti misliš na Becky?|-Stalno.
{99690}{99917}Ne brini ti ništa. -Ako si me probudila |da mi to kažeš
{99964}{100134}izgleda da imam o èemu brinuti.|-Htjela sam vidjeti nekoga poznatog.
{100171}{100363}I prièati s nekim... |-U dva sata ujutro?
{100395}{100611}Oprosti, ali došlo mi je... Ti si moj|anðeo èuvar.
{100719}{100939}Da li ga ti voliš? - Ne. - Ne boj|se. Reci mi istinu.
{101064}{101149}Ne znam.|-Ne znaš?
{101299}{101572}Oprosti, zbunjena sam. Nisam htjela...|Možda trebamo sutra prièati.
{101632}{101787}Željela sam te vidjeti jer si dobar|prema meni. - To je nedovoljno.
{101851}{102071}Nije tako. Trebaš mi. Jako.
{102145}{102312}Ne brini ni o èemu.|Vjeruj mi.
{102702}{102855}Oprosti.|Je li sve u redu?
{103283}{103335}Sranje.
{103515}{103683}Halo?|Nisam èula signal zvona.
{103729}{103802}Ne, on se tušira...|Halo?
{103970}{104147}Smiri se, ako se ne smiriš ne mogu|ti objasniti.  Neæu ti lagati.
{104186}{104299}Želim da prièamo kao |normalni ...
{104389}{104545}Tebe nema tri jebena mjeseca...|Miranda? Ma, što ti imam objašnjavati.
{104578}{104765}Da li si je jebao? -Ma, daj...- Samo|želim to znati. -To je nevažno za ovo.
{104777}{104877}A što je ovo? - Razgovor.|Ja najviše prièam. - Ja ti pomažem.
{104968}{105082}Možda ja tebi pomažem.|-Nisam ja ovdje zbog greške, Lelande.
{105168}{105283}Ako sam ja pogriješio, ne znaèi da vi|radite kako treba. -To ja nisam reko.
{105345}{105538}Rekli ste da ste samo èovjek, to |objašnjava. - Dobro, ja sam gad, jesi sretan?
{105624}{105748}Želio si jebati tu drugu djevojku?|-Da, htio sam.
{105939}{106078}Ne vidim ništa pogrešno u tom pitanju.|Samo prièamo, je li?
{106371}{106540}Otišli smo kod mene, i na sekretarici|je bila Mirandina poruka.
{106608}{106844}U L.A. je bio zamljotres i ona se uplašila,|i umjesto da zovem svoju djevojku
{106899}{107072}jebao sam drugu curu.|Znao sam da je to pogrešno.
{107243}{107415}Znaš što je èudno oko zemljotresa?|Ljudi izvlaèe ljude iz ruševina.
{107470}{107688}Brinu se jer vide cipelicu neke|djevojèice. Za 2 dana to sve zaborave.
{107759}{107911}To pokazuje da u ljudima i dalje ima|dobra. -U zemljotresu. -Ljudi griješe.
{107984}{108184}Griješimo. Èak i s najboljim namjerama|nitko nema volju da èini stalno dobro.
{108295}{108475}Što se dogodilo sa Becky? - Ne krivim je.|Zapitaš se zašto... - Nije to u pitanju.
{108516}{108684}Povrijedio sam nekoga. Ali lakše mi je| kad sjedim s nekim tko je isto zeznuo.
{108760}{108908}Raskinula je sa mnom zbog drugog.|-Ne želim te povrijediti.
{108953}{109087}Onda nemoj. -Nekad ljudima ne ide.|I nitko nije kriv.- Sranje.
{109171}{109277}Ona je kriva, lagala te je.|-Ja ne gledam tako na to.
{109294}{109532}Zbunjena sam. Nisam kao ti. Kažeš|da te povrijeðuje, ali izleda da nije tako.
{109544}{109659}Onda si se naljutio. -Ali tako je. |-Pokaži mi onda. -Kako?!
{109685}{109825}Uèinio si neke stvari koje nisu ništa|promijenile, ali si ih uèinio.
{109891}{110026}Da li da se derem na tebe?| Da te udaram? Da li tako treba?
{110190}{110293}Ja te volim.
{110425}{110600}Što još reæi? Što reæi|što æe promijeniti tvoje mišljenje?
{110825}{110940}Volio bih da sam|kao ostali.
{111028}{111198}Sviðalo ti se kad si bio zaljubljen|u nju, je li tako?
{111222}{111404}To je sve dio paketa. Ljubav je|super stvar, jer znaš kako je biti tužan.
{111471}{111584}Kako je biti sam...
{111656}{111851}Nešto sam rekao prije... laž.|-Koju?
{111881}{112059}Da ne osjeæam ništa.
{112112}{112244}Ulavnom to zadržavam u sebi,|ali... -Kad ne možeš?
{112300}{112524}Samo to onda vidim.|Recimo da neki klinac igra bejzbol.
{112589}{112764}Ja vidim samo onog što ne |može igrati, jer prièa loše viceve.
{112812}{112957}Kad vidim par kako se ljube, |samo vidim jedan stari tužan par.
{112991}{113110}koji varaju jedno drugo,|i ne smiju se pogledati u oèi.
{113187}{113265}I osjeæam tu tugu.
{113317}{113454}Vjerojatno i više od |svih njih.
{113489}{113622}Da li se sad tako osjeæaš?|-Uglavnom to zadržim za sebe.
{113695}{113898}Da li si se tako osjeæao poslije raskida|sa Becky? -Možda? -Poslije New Yorka?
{114011}{114163}Nije važno. Prièa o tome |je sama tužna i...
{114254}{114356}ali to ništa ne može|promijeniti.
{114620}{114809}Oprostite, g. Pollard. - Ovo nije trenutak.|-Molim vas... - Uèinite mi uslugu.
{114944}{115065}Poštujem vašu situaciju. -Hvala.|Ali nadali smo se da... -Što?
{115131}{115255}Što? Mi smo u žalosti! Gdje je tu|prièa?
{115297}{115458}Mi smo izgubili dijete i želimo da nas|ostave na miru. Je li to teško razumjeti?
{115512}{115687}Isprièavam se. - Hoæete prièu? Idite|kod roditelja onog klinca. Njih pitajte!
{115711}{115822}Oni su pogriješili, ne mi!|-Oprostite.
{116395}{116463}Ovo se nikada neæe |završiti.
{116612}{116821}Jesi li razmišljao da li ovo ima smisla?|Oduzmu ti djevojke, slobodu, sunce...
{116932}{117146}Da to ne bi više radio. Ali samo shvatiš|kako si beznaèajan.
{117199}{117386}Kad izaðeš, više se ni ne osjeæaš|kao èovjek.
{117742}{117903}Važno mi je da on zna da nisam znala.|Obeæaj da æeš joj to reæi.
{117957}{118033}Obeæajem.
{118102}{118239}Elden te želi vidjeti.
{118330}{118463}Znam da sam ja ispao gad.|-Ispriku neæu ni dobiti, zar ne?
{119222}{119268}Oprostite.
{119485}{119606}Konaèno te je pustilo |ono za 2002.?
{119631}{119760}Isprazni kasu.
{119809}{119983}Hajde! - Dobro, trebat æe mi malo|vremena. Ovo je kompjuter.
{120064}{120186}Ne mrdaj se. -Dobro, ne mrdam se.
{120361}{120497}Nemam vreæu.|-Daj mi! Hvala.
{120701}{120815}Ovo je sranje, i to to znaš.|-Ne, nego ti vodiš svoj program.
{120839}{120984}Pitao si me, rekao sam ''ne''. Onda si |pomislio '' tko njega jebe, uèinit æu to''.
{121141}{121320}Ovo je u vezi tvoje knjige.|Mogu te brzo otpustiti.
{121376}{121504}Povlaèim te s položaja.|Poslije ruèka ideš umjesto Belseya.
{121679}{121802}Pearl, možeš li nam uèiniti uslugu?|-Nisam trenutno u tom položaju.
{121850}{122008}Možemo li igrati košarku?|-Neæu više biti ovdje.
{122050}{122165}Šalju me u drugu uèionicu.|-Vratit æeš se sutra. -Neæu.
{122344}{122493}Nedostajat æe mi naši razgovori.|-Pokušat æu se vratiti, ali ne znam.
{122542}{122620}Ne pitam se ja.
{122755}{122877}Nisam ti rekao sve što sam htio.
{123029}{123147}I da prièamo o New Yorku. - Završio si|s pisanjem? - Ne znam.
{123234}{123364}Proèitaj ti.|Možda naðeš nešto tu.
{123607}{123776}Nije važno da li ja nešto naðem tu.|Nije važno ni što si ti mislio.
{123795}{123914}Najvažnije je ono što æe biti s|tobom, jer ti imaš neku kontrolu.
{123976}{124219}Poslušaj svog advokata. Želi ti najbolje.|Znam da znaš da si pogriješio.
{124249}{124408}Znam da ne pokazuješ to, ali shvaæaš.|Ne možeš to pobrisati.
{124456}{124626}Ne može nitko. Ali to ne znaèi da zbog|tvoje greške treba odustati od tvog života.
{124776}{124841}Na zemlju!|Polako!
{125045}{125150}Što se dogaða?|-Hapsimo vam sina. -Nije mi sin.
{125217}{125257}Allene?
{125426}{125593}Što je ovo? - Žao mi je. Samo sam |htio otiæi iz grada. Pogriješio sam.
{125627}{125763}Ne govori ništa.|Dobit æeš advokata.
{125874}{126056}Rekao si mom šefu da pišem knjigu|o Lelandu. -Rekao sam da pokušavaš.
{126086}{126235}Mislio si da æu dozvoliti da iskorištavaš| mog sina? -Ne, to je tvoj posao. -Što?
{126265}{126438}Ti si ovdje, jer si ti namirisao knjigu. |-Ja ne lovim svoje ideje, lešinaru.
{126469}{126601}Mogu napisati 12 prièa ovdje, u baru.|-Znaèi to radiš?
{126679}{126819}Ja sam jedini koji mu je htio pomoæi.|- Nemaš me pravo 
{126824}{126932}optuživati da ne brinem o sinu.|-Da je tako, pokušao bi se vidjeti s njim.
{126968}{127083}Umjesto da mu šalješ karte. |-Naš odnos te se ne tièe.
{127122}{127260}Oèigledno se i tebe ne tièe.|-Svjestan sam da sam griješio!
{127376}{127513}Ali bar pišem knjige.
{127567}{127667}Jadan si. -Zato nikad neæeš biti|pisac. -Ne, zato nisam gad.
{128435}{128511}Mogu li uæi?
{128792}{128875}Samo da vidim da li si dobro.
{128951}{129074}Vjerojatno si ljuta na mene.|Ali nisam ja ništa zgriješila.
{129310}{129406}Pogriješila sam, i znam to.
{129470}{129578}I žao mi je.
{129857}{130018}Vraæam se na rehabilitaciju.|I ''skinut æu'' se ovoga puta.
{130196}{130389}Kunem se da nisam znala da |æe Leland napraviti nešto.
{130651}{130775}Da sam samo znala...
{130849}{130994}Znaš koliko volim Ryana.|Znaš koliko ga volim.
{132249}{132382}Kako si? - Kako si ti?|-Dobro. Jesi se ti spasio?
{132416}{132529}Gilmor mi duguje par usluga.
{132629}{132796}Imaš li želju da ovo baciš?|-Dovraga!
{133135}{133244}Kada pogodim 3 zaredom,|poèni plesati.
{133509}{133622}Miranda, nemoj spuštati.|Zajebao sam.
{133717}{133853}Žao mi je. Znam da sam pogriješio.|Neæu pokušavati objasniti...
{133912}{134062}Znaj da mi je jako žao i želim|ti nadoknaditi to.
{134117}{134278}Jako želim da ti nadoknadim to.|Doæi æu zrakoplovom tamo.
{134339}{134473}Želim ovo ispraviti.
{134490}{134600}Volim te.|Volim te jako.
{134872}{134921}Ti si je bacio.
{135678}{135728}Bok, Allene.
{135809}{136019}postoje dva naèina gledanja na svijet.|Ili vidite tugu iza svega, ili to krijete.
{136070}{136235}Srce se ne može slomiti ako ne date|svijetu da ga dodirne. Ne krivim je.
{136327}{136599}Par dana kasnije sam se vratio u New York.|Bio sam uzbuðen što sam se vratio.
{136666}{136793}Mislio sam da æe biti kao prije.|Da mogu biti onaj stari.
{136835}{136976}Èim sam je vidio, shvatio sam da je |nešto drugaèije. Razvela se.
{137042}{137165}G. Calderon ju je varao skoro cijelog braka.|Rekla je da je zovem Angela.
{137325}{137545}Te noæi sam joj rekao za Becky.|Sjeæam se do rijeèi što je rekla.
{137581}{137718}To se dogaða svima.
{137774}{137893}To je najgori dio odrastanja.|Slamanje srca.
{138062}{138163}To je dio života.
{138196}{138436}Izgleda da je to poveliki dio. -Zato, vjeruj |da je život više od njegovih dijelova.
{138526}{138650}Razmišljao sam o tome, ali nisam |razumio, a i njoj nije to služilo.
{138717}{138870}Slamalo mi se srce zbog nje, htio sam|napraviti nešto, ali nisam mogao ništa.
{138961}{139038}Samo sam jedno mogao.
{139616}{139799}Elektricitet joj nije više bio u oèima.|Pomislio sam da uopæe nije bio tamo.
{139868}{140037}Oèi su nam samo oslikavale tugu.|To sam vidio na svima.
{140096}{140237}Lica su razlièita, a ista. Svima su|slomljena srca. Iznova, i iznova.
{140321}{140461}Vidio sam lice moje mame. Koliko|ju je tata povrijedio, i kako je usamljena.
{140507}{140653}Kako je željela biti sretna.|To svi roditelji žele, ali ispadne drukèije.
{140844}{140970}Kad sam se vratio, on je èekao Becky,|ali ona nije došla, pa sam ga ja otpratio.
{141024}{141166}Sutra sam na njegovom satu vidio |kako ga uèe rijeèi, ili što je loše.
{141196}{141326}Nije bilo rijeèi kao što su ''jagoda''|ili ''poljubac''.
{141418}{141564}Vidjelo se da mu se sviða onda djevojka.|Ali ona mu se smiješila kao 
{141577}{141629}beba kad napravi nešto|slatko.
{141677}{141824}Pomišljao sam da zna da on nikada|neæe moæi imati takvu djevojku.
{141914}{142000}Znao je sve.
{142031}{142192}Znao je da nikad neæe biti normalan.|Ljudi mu se smiju ili ga sažaljevaju.
{142205}{142416}Sve je to znao, ali nije ništa mogao.|Nisam mogao spavati.
{142443}{142591}Mislio sam o gði Calderon i Ryanu,|i nešto me gušilo!
{142642}{142816}Sva ta tuga, a mi ne možemo ništa.|Samo želimo da nestane.
{142895}{143021}Kada kažem da se na sjeæam tog dana,|ne lažem. Volio bih da mogu.
{143069}{143165}I ne želim.
{143259}{143347}Isuse.
{143364}{143435}Gotovo je.
{143462}{143520}Sada je gotovo.
{143704}{143828}Možda sada ima smisla, možda sada|za sve postoji razlog.
{143890}{144108}Možda negdje ima ''zašto'', možda|sve to možemo negdje zakopati.
{144219}{144350}Zakopati tako duboko|da izgleda kao da se nije dogodilo.
{144401}{144557}Ali ništa, ni ''zašto'', ni ljutnja,|ni isprika, ni molitve,
{144607}{144719}ni suze, ne mogu obrisati|nešto što se veæ dogodilo.
{144805}{144894}Ne možeš to obrisati,| i nitko ne može.
{144926}{145070}Ali kao si ti pogriješio, ne znaèi da| treba odustati od tvog života.
{145224}{145316}Ti znaš da mi je žao, zar ne, Pearl?|-Da, znam.
{145406}{145530}Ali to ne mijenja ništa.
{145831}{145965}Najgori dio je znati da dobrota u |ljudima postoji, ali je zakopana duboko.
{146058}{146180}Možda ne vjerujemo u Boga zato što|se bojimo loših stvari, veæ se bojimo
{146199}{146259}dobrih stvari.
{146409}{146517}Ako Bog ne postoji, to znaèi da je |dobrota u nama, i možemo 
{146534}{146641}biti dobri koliko želimo. Pa, kad |radimo loše stvari, to želimo.
{146677}{146837}Ili zato što moramo. Ili nam trebaju loše |stvari da nas podsjete što su dobre stvari.
{146981}{147084}Što radiš to, ludo?|Samo obiði.
{147561}{147597}Hajde.
{147815}{147870}U redu je.
{147937}{148002}Sve æe biti u redu.
{148067}{148120}Obeæajem.
{148266}{148666}Subtitles by:|M O Z E N
