{1}{1}23.976
{925}{1075}U IME PRAVDE
{2447}{2494}{Y:i}Dobrodošao kuæi, Leo!
{2863}{2916}Pazi, vruæe je.|-Hvala, dušo.
{3009}{3072}Ne, èekaj ... -Ma, daj.|-Èekat æemo Lea.
{3089}{3144}Strpi se, Bernarde.|Prièekat æemo ti bratiæa.
{3187}{3295}Zgodan je, svidjet æe ti se.|-Misliš?
{3279}{3345}Znam. Imam nos za te stvari.
{3444}{3492}Polako. Vruæe je.|-Pazim. Pazim.
{3500}{3565}Val, hrana izgleda savršeno.|Napravimo malo mjesta
{3570}{3644}na stolu. -Što je s tvojim|suprugom? Hoæe li doæi?
{3655}{3735}Frank ne može doæi. Mislila|sam vam reæi. Ima puno posla,
{3745}{3803}ali sastat æe se s Leom sutra.
{3848}{3904}Barem Bernard nešto jede.
{4025}{4095}Hej, srce. Kako si?|-Dobro.
{4126}{4179}Erica, poznaješ li Belvee?|Belva.
{4193}{4230}Belva. Lijepo ime.
{4248}{4302}Govorio sam joj o tvom|bratiæu Leu.
{4307}{4364}Želio bih je|upoznati s njim.
{5201}{5260}Evo ga.
{5269}{5315}Hej!
{5453}{5593}Bok, mama. Kako si mi? Jesi|li dobro? -Jesam, dobro sam.
{5655}{5715}Izgledaš odlièno.|-Hvala, i ti isto.
{5944}{6004}Tako mi je drago što si|stigao kuæi! -I meni.
{6070}{6127}Hej, Leo!
{6144}{6180}Leo, lave!
{6184}{6241}Svi smo te došli vidjeti, kompa!
{6252}{6292}Kako si? -Dobro.
{6297}{6366}Volim te, èovjeèe.|Dobrodošao kuæi.
{6430}{6484}Hvala. Drago mi je što te|vidim. -I meni.
{6491}{6518}Kako si?|-Dobro.
{6520}{6559}Dobrodošao kuæi.|-Što ima, Dante?
{6561}{6605}Izgledaš odlièno.|-Kako si, Todd?
{6609}{6663}Kako si, Leo?
{6677}{6727}Izgleda da vam je krenulo, deèki.
{6733}{6790}Ne brini. I ti æeš|uskoro stati na svoje noge.
{6873}{6934}Želio bih te upoznati s|Belvom. Belva, ovo je Leo.
{6968}{7025}Belva je plesaèica.|-Bok!
{7029}{7114}Hajdemo. Stol je pun.|-Idemo jesti. -Navalite.
{7125}{7174}Ponudite se.
{7210}{7292}G. Handler.|Moramo razgovarati.
{7308}{7362}Gdje možemo|biti nasamo?
{7382}{7451}U spavaæoj sobi, mislim.|-Idemo.
{7554}{7639}U mom izvješæu piše da si|pušten danas u 16:00h.
{7653}{7690}Tako je.
{7697}{7773}Trebao si se odmah javiti.|-Nitko mi to nije rekao.
{7778}{7879}Mislio sam da imam 24 sata|vremena. -Ubuduæe se moraš
{7885}{7988}redovito javljati, na vrijeme.|U izvješæu piše da si stvarao
{7993}{8085}neke probleme. Služio si 16|mjeseci za kraðu automobila.
{8091}{8148}Buduæi da si na uvjetnoj|slobodi, bit æeš pod našom
{8150}{8228}stalnom paskom.Imat æu uvid u|tvoj porezni karton, bankovne
{8232}{8324}podatke, platne odreske. Sve|u svrhu praæenja tvog dohodka.
{8331}{8383}Što je s tvojim zaposlenjem?|Imaš li što u vidu?
{8387}{8488}Mislim da ima nešto. -Što?|-Novi suprug moje tete
{8493}{8564}vodi privatan posao.|Na visokom je položaju.
{8569}{8616}Sutra imam intervju s njim.
{8623}{8684}Nekolicina mojih prijatelja|takoðer radi za njega.
{8721}{8785}Što je s posjetama psihologu?
{8803}{8873}Ne želim uzrokovati probleme.|Želio bih opet biti èovjek
{8878}{8937}koji daje svoj|doprinos društvu.
{9094}{9244}Što kažeš? Zgodan je, zar ne?|-Da, ali ne znam ga od prije.
{9276}{9360}U tome i jest stvar.|-Ne znam kakav je ranije bio.
{9545}{9598}Sve u redu?|-Da.
{9606}{9662}Kako to da nisi s ostalima?
{9666}{9742}Willie zabavlja društvo.|Željela sam se malo maknuti.
{9780}{9847}Sve u redu meðu vama?|-Da.
{9855}{9919}Razmišljamo o tome da se|sredimo, ...
{9930}{10000}ali sad je sav u poslu, znaš.
{10026}{10164}Žao mi je za tvog oca.|Bio je dobar èovjek.
{10315}{10370}Možda bi se trebali vratiti|u društvo. -Erica...
{10410}{10471}Kakav ti je oèuh?|Slažeš li se s njim?
{10494}{10554}U redu je.
{10636}{10695}Jesi li dobila moja pisma?
{10821}{10883}Mora da su zaboravili|ukljuèiti razvodnu kutiju.
{10991}{11059}Ovdje si...|-Bok, mama.
{11066}{11121}Zamraèenje, ha?
{11174}{11234}Zašto gnjaviš bratiæa, Erica?
{11246}{11307}Idi, pogledaj je li sve|na mjestu unutra.
{11442}{11491}Oprostite, teta Kitty?|-Da?
{11516}{11573}Želio bih vama i vašem|suprugu zahvaliti što
{11578}{11637}ste mi sredili intervju za|sutra. Zaista to cijenim.
{11644}{11699}Znaš da bih sve uèinila za|tvoju majku.
{11817}{11900}Nije baš najboljeg zdravlja.|Bolje da ti to odmah kažem.
{11933}{11993}Srce joj slabi.
{12205}{12234}Eno Lea.
{12239}{12295}Hej, Leo!
{12302}{12359}Kako si, prijatelju?
{12372}{12407}Jesi li dobro?
{12411}{12473}Jesi li uzeo pivu ili što|drugo? -Ne treba. U redu je.
{12478}{12564}Deèki i ja zaista poštujemo|to što si se zauzeo za nas.
{12577}{12661}Nisi nas cinkao murjacima.|-Dajte,ne bih vas nikada odao.
{12700}{12774}Želio bih da radiš s nama.|Natukni to Franku kad se
{12778}{12828}vidiš s njim.|-U redu. -Dobro.
{12845}{12921}Popij s nama pivu. -Ti si ih|dovoljno popila za sve nas.
{12947}{13042}Leo, otiæi æemo za vikend|do kluba. Kao nekad.
{13048}{13120}Zvuèi odlièno. Èuvaj se.
{13133}{13198}Leo, što ima novo? -Što?!|Više me ni ne pozdravljaš?
{13202}{13239}Dobro izgledaš.
{13247}{13290}Društvo, oprostite.
{13298}{13341}Svima...
{13380}{13447}Željela sam samo reæi kako mi|je drago što smo se svi
{13473}{13531}okupili ovdje, i...
{13572}{13710}Proteklih godina nam nije|bilo baš lako...
{13722}{13802}Ali sada je sve drugaèije.
{13817}{13892}Od sada nadalje nas sve|èekaju samo dobra vremena.
{13935}{13975}Samo toliko.
{14150}{14216}Popijmo kavu, uspijem li|pronaæi Ionèiæ.
{14352}{14465}Samo sam ti htio reæi da mi|je žao...zbog svega.
{14539}{14597}Ne brini.
{14608}{14677}Idi prijateljima. Provedi se.
{14809}{14845}Kako ide, Todd?
{14860}{14916}Leo, sjedni. Razgovaraj malo|s nama. Kako si?
{15208}{15381}ELEKTRIÈNE ŽELJEZNICE|-KORPORACIJA-
{16343}{16379}Bok, Denise. Pozdravi majku.
{16502}{16550}{Y:i}Pozovi ga, Denise.
{16694}{16761}Drago mi je što sam te|napokon upoznao. -I meni.
{16770}{16807}Oprosti na èekanju.
{16814}{16864}Sjedni.|-Hvala.
{16953}{17001}Kako ti je majka?
{17009}{17118}Dobro je. Bori se. -Puno|lijepog mi je prièala o tebi.
{17148}{17227}Ona je divna žena. Sve ove|godine te uzdržavala sama,
{17232}{17293}bez ièije pomoæi. Za to je|potrebna velika hrabrost.
{17298}{17386}Znam. Sve æu uèiniti|kako bih joj se odužio.
{17433}{17551}Supruga i ja smo joj nudili|pomoæ, ali nije htjela ni èut.
{17583}{17649}Divim joj se. Znam da joj|nije bilo lako posljednjih
{17656}{17736}nekoliko godina. Uvalio si se|u neku nevolju, ukrao par
{17741}{17814}automobila, ili tako nešto.|Ali, odslužio si svoje.
{17869}{17974}Znam da ti je bilo gadno, ali|u svijetu biznisa nije ništa
{17980}{18042}drugaèije. Ponekad moraš|imati oèi i na leðima.
{18103}{18206}Znaš li što radimo ovdje?|Što god je vezano uz vlakove
{18208}{18248}ili Newyoršku podzemnu|željeznicu;
{18250}{18301}mi postavljamo|ili popravljamo.
{18309}{18372}Spojnice, koènice,|transformatori. Imaš li
{18378}{18465}iskustva s tim stvarima?|-Mogu nauèiti. -To je dobro.
{18491}{18577}Imamo ovdje teèaj za|strojare. Mogu samo okrenuti
{18584}{18695}broj. -U ovom trenutku mi je|najvažnije skrbiti se za
{18701}{18789}majku i sebe. Koliko dugo bi|takav teèaj trajao?
{18796}{18874}Za strojara? Par godina.|Ali te èeka dobar posao kad
{18895}{18986}završiš. 400-500 dolara|na tjedan.
{19035}{19101}Mogao bih te financirati dok|ne položiš ispite.
{19128}{19193}Što je s Willieom? On nije|išao ni na kakav teèaj.
{19198}{19256}Predložio mi je da radim|s njim.
{19269}{19328}Mislim da to za tebe|ne bi bilo pametno.
{19330}{19396}U èemu se sastoji njegov|posao? -On veæinom kontaktira
{19398}{19469}s dobavljaèima. Nisam siguran,|ali smatram da bi trebao
{19475}{19532}razmisliti o teèaju.
{19558}{19655}Razmislit æu.|-U redu.
{19783}{19870}Mogli biste ti i majka doæi|kod nas na veèeru u subotu?
{19878}{19936}Cijela obitelj æe biti na|okupu. Bilo bi mi drago.
{19970}{20016}U redu.
{20036}{20077}Leo...
{20099}{20189}Hvala ti što si došao. I|slušaj...
{20194}{20255}sada si moj neæak i zaista|bih ti želio biti od pomoæi.
{21878}{21935}Ricky!|-Hej, Willie. Što ima?
{21940}{21988}Ovo je moj prijatelj, Leo.|Leo, Ricky.
{21994}{22054}lšli smo zajedno u osnovnu.|-Hvala ti što si me povezao
{22056}{22111}s Russelom. Sviða mi se|stereo koji mi je ugradio.
{22113}{22161}Savršen zvuk. Napravio je|odlièan posao.
{22163}{22215}Rekao sam ti da je najbolji.|-Što æete popiti?
{22223}{22321}Dva Millersa, Jim Beam i|rum-colu. Stavi na moj raèun.
{22450}{22584}Willie, ne znam što æu.|-U vezi èega? Franka?
{22610}{22643}Da.
{22648}{22693}Ne moraš ni na kakvo|usavršavanje.
{22699}{22771}Isto sranje je i meni govorio.|Uvjerio sam ga da me pusti
{22776}{22839}aaraditi s biznismenima.|-Kako si to uspio?
{22870}{22931}Družio sam se s njima|i zaslužio njihovo povjerenje.
{22949}{23014}Puno novaca bacaš. Kakve to|poslove ti za njega obavljaš?
{23094}{23151}Poði sutra sa mnom i vidjet|æeš na svoje oèi.
{23157}{23217}Bude li ti se svidjelo,|razgovarat æemo s Frankom.
{23219}{23277}Samo pitam. Znaš da se ne|smijem uvaliti ni u kakvu
{23279}{23354}nevolju. -Pobrinut æu se da|ne uletiš u nevolje.
{23365}{23437}Frank je divan èovjek. Mogli|bi uz njega napredovati.
{23443}{23511}Znaš da mi je majka cijeli|život ovisila o pomoæi drugih.
{23519}{23598}Sad je novac u mom džepu.|Moguænosti su neogranièene.
{23637}{23689}Ali ti si uvijek bio dobar s|ljudima.
{23695}{23750}Ja nisam tako dobar|s rijeèima.
{23773}{23829}Ti si mi najbolji prijatelj.|Pobrinut æu se za tebe
{23835}{23934}da upadneš. -Nadam se da æe|upaliti jer bi mi to trebalo.
{23982}{24033}Želio bih raditi s tobom.|-Odlièno.
{24039}{24099}Poèinjemo sljedeæi tjedan.|Kako ti se sviða Belva?
{24102}{24172}Dobra je, ali ne dovoljno|dobra, razumiješ što mislim?
{25001}{25073}Sestrièna ti je predivna.|-Da, jest.
{25367}{25415}Hajde, zgodnišu, pleši!|Idemo!
{25492}{25549}Hajde! Pleši!
{26530}{26585}Ruke iznad glave.
{26650}{26706}Isprazni džepove.
{26783}{26845}Ok. Sve u redu. Slobodan si.
{26858}{26907}Hvala, Glenn.|-Sve u redu, Willie.
{26909}{26974}Ovdje imate veliko osiguranje.|Siguran si da je u redu što
{26976}{27052}idem s tobom? -Nemaš problema.|Svi me ovdje znaju.
{27076}{27155}Što se ovdje nalazi?|-Gradska vijeænica.
{27171}{27210}Sve što se dogaða sa|željeznicom,
{27212}{27254}ovdje živi i umire.
{27256}{27323}{Y:i}Pokušavamo sklopiti ugovore|vrijedne 14 milijuna dolara.
{27325}{27386}{Y:i}Bit æe gadno, jer sva nam je|konkurencija ovdje.
{27424}{27501}{Y:i}Korporacija Weltech je|najveæa od njih,
{27511}{27570}{Y:i}na èijem su èelu Manny|Sequiera i Hector Gallardo.
{27678}{27742}{Y:i}Sequiera je potplatio dva|vijeænika kako bi dobio taj
{27744}{27782}{Y:i}ugovor.
{27787}{27851}{Y:i}Paul Lazarides je Frankova|veza. On nas predstavlja kod
{27853}{27954}{Y:i}Uprave za transport,|na èelu koje je Al Granada.
{27974}{28036}{Y:i}Moj posao je podmazivati ga,|kako bi posao tekao u našem
{28041}{28093}{Y:i}smjeru.
{28117}{28179}Kakav sam? Ne bih želio|privlaèiti poglede drugih.
{28186}{28234}Izgledaš odlièno.|Hajde. Idemo.
{28329}{28426}Na redu je nalog 4-2-3-9-9,|vezan za zamjenu ispravljaèa
{28431}{28584}na linijama Queens i Bronx.|Nakon pažljivog razmatranja
{28591}{28669}ponuda, uzimajuæi u obzir|cijenu i izvedbu rada, Vijeæe
{28675}{28783}je odluèilo dati koncesiju|EI. Željeznicama iz Masphet.
{28809}{28855}Stavite to u zapisnik.
{28870}{28958}Sljedeæe.Nalog broj 4-6-9-6-4.|U vezi postavljanja 230
{28965}{29038}spojnica, sve za podzemnu...|-G. Upravitelju, molim za
{29040}{29106}rijeè. -Hectore, dopusti da|dovršim. -Taj ugovor nam je
{29108}{29153}zajamèen. -U krivu ste.
{29157}{29208}Dogovorili smo se da|ispravljaèi idu nama.
{29215}{29271}Hectore, dopusti da dovršim.|-I oni to znaju.
{29285}{29358}10%je zajamèena kvota za|manjinske tvrtke.
{29363}{29448}Kojih 10%ulazi u to, naša|je odluka. Da ovisi o meni,
{29453}{29515}Weltech ne bi dobio ništa jer|vam je broj loše izvedenih
{29518}{29582}a radova previsok. -To je zbog|Elektriènih Željeznica.
{29585}{29650}Pokušavaju nas izbaciti s|tržišta. Želimo uložiti žalbu.
{29655}{29762}Neke istrage su veæ bile|sprovedene na osnovu
{29768}{29853}pritužaba Weltecha, i sve|su optužbe na naš raèun
{29857}{29948}odbaèene. Weltech je upoznat|s rezultatima tih istraga.
{29956}{30028}No svejedno nastavljaju s|iznošenjem daljnjih optužbi.
{30039}{30118}Smatram da nam duguju ispriku.|-Ja Vama dugujem ispriku?-Da.
{30159}{30219}Nastavimo sa sastankom.|-Ti to meni prst pokazuješ?!
{30226}{30323}Dobit æeš po|nosu! -Idemo, stari.
{30345}{30436}Jeste li vi u cirkusu,|vas dvojica? Prestanite s tim.
{30453}{30528}{Y:i}Gutierrez. Želim razgovarati|s tobom.
{30567}{30663}{Y:i}Nemam ti što za reæi,|Hectore.-Daj, prijatelji smo.
{30715}{30840}{Y:i}Obojica znamo što radiš.|-Ne znam na što ciljaš.
{30867}{30942}Zašto ne bi radio za nas,|umjesto za one budale?
{30964}{31025}Ne troši moje dragocjeno|vrijeme. -Hej!
{31063}{31194}{Y:i}Put ti nikada neæe biti tako|bijela kao njihova.Zapamti to.
{31225}{31271}Idemo!
{32087}{32180}Tko je ovaj?|-Leo. Viðat æeš ga èešæe.
{32197}{32259}Nisam raspoložen za sklapanje|novih prijateljstava.
{32401}{32450}Pobrinut æemo se mi za|Weltech.
{32459}{32514}Tko je to? -Frankov neæak.|-Je li ON bio u zatvoru?
{32519}{32589}Bez brige, dobar je on|deèko. -Imaš li novac?
{33874}{33931}Pozdravi ujaka u moje ime.
{33941}{34003}Vidimo se.|-Èuvaj se.
{34047}{34105}Što je to bilo, dovraga?
{34142}{34285}Ništa. Samo je zabrinut|da nisam ozvuèen.
{34321}{34392}Ili mu se jako sviðam.
{34411}{34476}Meni je to jebeno èudno.
{34499}{34555}On dobije postotak od|svih sklopljenih ugovora?
{34560}{34624}Slušaj, ne brini ti za|to. On je gradski službenik.
{34626}{34682}Sustav na taj naèin|funkcionira.
{34688}{34737}Ali evo i pozitivne strane|cijelog posla.
{34786}{34834}Ovo je tvoj dio.
{34852}{34896}Isplativo?
{34922}{34964}Ovo je tek džeparac.
{34975}{35016}Sigurno si puno uštedio.
{35023}{35070}Sve sam potrošio na tvoju|sestriènu.
{35129}{35188}Moramo obaviti još par|posliæa ovaj tjedan.
{35213}{35301}Sljedeæi tjedan te vodim u|tunele. -Dobra ideja.
{35459}{35516}Leo, jesi li spreman?|Moramo uskoro krenuti.
{35562}{35617}Mama.
{35620}{35677}Kupio sam ti nešto.
{35694}{35750}Što to radiš? Ne moraš mi|kupovati stvari.
{35754}{35849}Želio sam. Mislio sam da ti|to treba. -Ali, Leo. Ne možeš
{35853}{35912}tako trošiti. Svaki novèiæ|je dragocjen, znaš to.
{36204}{36273}Predivna je.|-Hvala ti.
{36322}{36406}Požuri. Frank je poslao auto|po nas. -Evo me.
{36417}{36469}Brzo æu se preodjenuti.
{36869}{36926}Stigli smo. Ovdje žive.
{37147}{37187}{Y:i}Bernarde, otvori vrata.
{37198}{37257}{Y:i}Mama, veæ sam sjeo za stol.|-Oprostite što kasnimo.
{37259}{37314}{Y:i}Ne kasnite. Hrana je upravo|stigla.
{37329}{37392}Sjednite. Uèini mi uslugu,|Will. Pomakni se ondje.
{37409}{37470}{Y:i}Sjedni ovdje, Leo.|-Sve u redu? -Jest.
{37488}{37532}Bok, Bernard.|-Kako ste?
{37547}{37600}Lijepa kuæa. -Hvala. Drago|mi je što ti se sviða.
{37606}{37633}Radimo neke izmjene.
{37639}{37680}Preureðujem sobu|za rekreaciju.
{37686}{37749}Oni šupci nas svako jutro|bude. -Je li potrebno psovati?
{37759}{37827}Mogu li dobiti malo|lo meina?
{37838}{37913}Frank, ovo izgleda doista|ukusno. -Hrana je odlièna.
{37920}{38010}Ali ponekad je malo previše|zaèine.-To je Bernijev tanjur.
{38021}{38080}Možeš li mi dodati|rižu kad si gotov?
{38099}{38146}Hvala, mama.
{38174}{38292}Leo, jesi li majci spomenuo|naš razgovor? -U vezi èega?
{38300}{38384}Rekao sam mu da bi trebao|razmisliti o teèaju za
{38390}{38475}strojara. -Zvuèi kao|odlièna ideja.
{38527}{38596}Ustvari, bio sam s Williem|i mislio sam raditi s njim.
{38647}{38706}Porazgovarao bih s tobom o|tome. -Zvuèi dobro.
{38720}{38786}Njih dvojica, poslovni|suradnici. Zvuèi dobro,zar ne?
{38871}{38951}Ne razumijem. Mislio sam|da smo se dogovorili.
{38973}{39034}Nije mi ugodno|uzimati tvoj novac. -Novac?
{39052}{39131}Imali smo veæ razgovor o tome.|Ne želimo nièiji novac.
{39150}{39212}Zašto ne bi njih dvojica|radili zajedno?
{39405}{39516}U redu. Nadam se da æeš se|snaæi u poslu i postati dio
{39521}{39638}nas. Moguæe, i napredovati.|-Iskreno se nadam tome.
{39728}{39793}Dobro.
{39844}{39927}Ok, sve sreðeno. Sad oèistimo|sve iz tanjura, vrijedi?
{39936}{39988}Ima li one ljute gorušice?|Nadam se da ima.
{40432}{40487}{Y:i}Erica.
{40549}{40624}Što je?|-Želim ti nešto pokazati.
{40632}{40671}Što?
{40763}{40821}Što je to?
{40847}{40905}Otvori.
{41193}{41257}O, Willie.
{41301}{41359}Obavijestit æemo ih sve|ovaj vikend.
{41367}{41434}Želim to uèiniti na pravi|naèin.
{42027}{42086}Volim te.
{42437}{42486}Kuda æemo?
{42493}{42540}Na Sunnyside ranžirni|kolodvor.
{42545}{42599}Deèki su tamo,|èekaju nas.
{42605}{42658}Želim te upoznati s nekim.|On radi sa mnom.
{42676}{42732}Što æemo raditi tamo dolje?
{42769}{42829}Onesposobiti konkurentske|vlakove.
{42848}{42908}Izazvat æemo kratki spoj na|njihovim strojevima i
{42910}{42974}onesposobiti ih. Uskratit æe|im povjerenje i mi dobivamo
{42976}{43043}posao. Veèeras æe to biti|Weltechovi vlakovi.
{43057}{43122}To su oni tipovi s kojima smo|se prepucavali u Vijeænici,
{43124}{43172}sjeæaš se?
{43220}{43278}Ti se ne miješaj, veèeras|samo drži stražu.
{43286}{43416}Sve æe biti u redu.|-Kako ste, deèki?
{43431}{43467}Kako ide, Dante?
{43475}{43534}Kako si, Todd?|-Hej, Leo!
{43556}{43610}Raymonde, ovo je Leo.
{43634}{43731}On æe sa mnom|dostavljati lovu.
{43807}{43886}Jesi li ikada bio u|Povjerenstvu 1 ili 3? -Ne.
{43909}{43966}Jer, mi ne suraðujemo s|Izgradnjom.
{43978}{44037}Nisam upoznat s time.
{44070}{44141}Ovdje si jer prijatelji|garantiraju za tebe.
{44201}{44260}Idemo dolje.
{44730}{44800}Leo, ostani ovdje. Èuvaj|stražu. U redu?
{44809}{44854}Dobro. Èekam vas ovdje.
{45511}{45569}Donio sam ti ulaznice za|Knickse.
{45575}{45620}Ovo je za tebe.
{45627}{45690}Ne želim to, Willie.|Mièi deèke s traènica.
{45712}{45771}O èemu ti to?|-Nisi više dobrodošao ovdje.
{45799}{45875}Weltechovci su prošli tjedan|bili ovdje i dali mi $2000.
{45882}{45944}I dovoljno su jaki da preuzmu|kontrolu nad poslovima.
{45946}{46024}Ponudi li ti tko veæi iznos,|obratiš se nama i mi dajemo
{46030}{46091}jednako toliko. -Ne, više ne.|Zna se da EI. Željeznice
{46093}{46159}ispadaju iz igre, a Weltech|jamèi jednaku naknadu.
{46166}{46238}Mièi ih s traènica,|ili zovem murju.
{46440}{46518}Daj, Elliote...Ne bi nam|valjda to uèinio.
{46676}{46720}Što to, dovraga, radiš?
{46726}{46763}Iskaèite!
{46837}{46925}Willie!|Will!
{46984}{47034}Što to radiš?
{47039}{47104}Ništa.|-Kako to misliš, ništa?
{47109}{47180}Ti si neki huligan? Trebao|bih ti glavu razbiti, znaš?!
{47217}{47261}Iskljuèi to.
{47328}{47370}Što æeš s tim?|-Iskljuèi alarm.
{47384}{47423}Tebi govorim.
{47490}{47556}Imaš li kakve isprave?
{47684}{47739}Ni ne pomišljaj na to.
{47962}{48021}Ruke iznad glave.|Okreni se.
{48061}{48110}Kuronjo!|-Nisam ništa uèinio!
{48138}{48200}Želiš bježati? Trebao bih|ti nos razbiti, ti, kuronjo!
{49051}{49140}{Y:i}Halo? -Gðo. Handler,|je li Leo kod kuæe?
{49159}{49219}Mama, možeš poklopiti.
{49263}{49320}{Y:i}Nisam mislio da æe se tako|nešto dogoditi, znaš to.
{49326}{49382}Rekao si da æe sve biti|u redu. -Znam.
{49392}{49492}{Y:i}Ali krenulo je nizbrdo.|Što si to uèinio?
{49506}{49601}Što sam uèinio? Murjak mi je|zamalo glavu razbio!
{49609}{49702}Jesi li dobro? -Jesam, ali|ne znam za njega.
{49719}{49786}{Y:i}U redu. Ne smijemo|panièariti.
{49795}{49863}{Y:i}Razgovarat æu s Frankom. On|æe znati što treba uèiniti.
{49869}{49947}{Y:i}Ne brini. Vijeæe si ne može|priuštiti uhiæenja i istrage.
{49954}{50016}{Y:i}Jebeni politièari su|umiješani u to, razumiješ?
{50033}{50086}Razumijem.
{50163}{50333}Willie? -Nisam znao da|si ovdje.
{50355}{50422}{Y:i}Morala sam se maknuti|iz one kuæe!
{50473}{50527}{Y:i}Tko je to?
{50789}{50847}Tko je?|-Raymond.
{50958}{51033}Što se, dovraga, dogodilo?|-Ne mogu sada razgovarati.
{51052}{51125}Sakupi deèke i naðemo se|veèeras u uredu. Može?
{51184}{51247}Je li to krv na tvojim|rukama? -Nije to ništa.
{51252}{51310}Porezao sam se. Idi sad.
{51581}{51640}Tko je to bio?|-Kolega s posla.
{51653}{51724}U ovo doba? -Ne brini.|Vrati se na spavanje.
{52167}{52225}Halo?
{52274}{52303}Samo malo.
{52310}{52364}Tko je to?|-Ne znam.
{52504}{52639}Da?|-Imao si problema jutros?
{52648}{52755}Tko je to?|-Nadglednik je mrtav.
{52760}{52808}{Y:i}Za murjaka se još ne zna|hoæe li se izvuæi.
{52814}{52863}Hectore, jesi li to ti?
{52867}{52930}{Y:i}Svjedoèi u našu korist.|Weltech ima dobre odvjetnike.
{52932}{53003}Ne zovi više na ovaj broj!
{53090}{53167}Što svi to žele?
{53207}{53259}Žao mi je zbog ove ludnice.
{53266}{53323}Nisam znao da æeš veèeras|biti ovdje.
{53424}{53488}Ne mogu doèekati dan našeg|vjenèanja.
{53660}{53725}Reæi æu majci...
{53733}{53794}I vjenèat æemo se.
{53974}{54038}Imat æemo pravu obitelj.
{54829}{54900}Što te muèi?|-Ništa. Umoran sam.
{55478}{55522}Imamo i previše problema s|manjinama.
{55524}{55585}Konglomerati su izgubili|ugovore s Obranom, vratili
{55587}{55626}su se poslu vezanom|uz željeznice.
{55628}{55680}Nismo u moguænosti poduzeti|nikakve korake.
{55682}{55713}Sa svih strana me pritišæu.
{55715}{55764}Konglomerati preuzimaju|velike ugovore.
{55766}{55824}Manjinskim tvrtkama su|zajamèeni manji poslovi,
{55826}{55883}a ja se nalazim u samoj|sredini. -Ne uzrujavaj se.
{55885}{55939}Prièekaj do nakon izbora.|-Zašto nakon izbora?
{55945}{56020}Nakon ovih, pa onih izbora...|Izbori nemaju veze s mojim
{56026}{56098}poslom. -Više strpljenja,|Frank. -Poslušaj me.
{56107}{56170}Moraš skinuti te manjinske|kvote, inaèe ispadam iz igre.
{56181}{56248}To je jedini naèin na koji se|mogu izvuæi. -Kako stvari
{56250}{56318}stoje, ruke su nam vezane.Ovo|umorstvo nam visi za vratom
{56320}{56375}tko zna što æe iz toga sve|proizaæi? Znaš li ti išta
{56377}{56445}o tome? -Da su moji deèki|umiješani, veæ bih ih ubio.
{56473}{56534}Policajac je još živ, Frank.|U komi je.
{56556}{56611}{Y:i}Izvuèe li se i ispadne li|da je povezano s našim
{56613}{56672}{Y:i}poslovanjem, pakao æe se|otvoriti pod našim nogama.
{56674}{56736}{Y:i}Murjaka æe biti posvuda, a|mi to neæemo moæi sprjeèiti.
{56738}{56794}{Y:i}Ne možeš ništa uèiniti u|vezi kvota?
{56816}{56884}{Y:i}Vremena se mijenjaju, Frank.|-Tko je? Što hoæeš?
{56921}{56980}Ja sam. -Hej, Willie.|Što trebaš?
{57028}{57114}Želio bih porazgovarati o|neèemu s tobom. -Imam posla.
{57288}{57401}Ništa važno. Sam æu se|pobrinuti za to.-U redu, onda.
{57434}{57471}Dobro.
{57599}{57658}{Y:i}Želim vam reæi da mi je|tvrtka u ozbiljnoj krizi.
{57676}{57727}{Y:i}Razumijete?
{57822}{57899}{Y:i}Jedan djelatnik Gradskog|prijevoza je ubijen,
{57901}{57962}{Y:i}dok se djelatnik policije|nalazi u dubokoj komi nakon
{57964}{58023}{Y:i}jutrošnjeg napada na|ranžirnoj stanici Sunnyside,
{58025}{58084}{Y:i}u Queensu. Policijska uprava|izvješæuje kako se službenik
{58086}{58149}{Y:i}Rifkin odazvao na poziv na|uzbunu primljenog s ranžirne
{58153}{58212}{Y:i}stanice nešto nakon 1:00|jutros. 10 minuta kasnije,
{58214}{58287}{Y:i}Rifkin je pronaðen na|traènicama, u nesvjesnom
{58292}{58353}{Y:i}stanju. Tijelo nadglednika|ranž. stanice je takoðer
{58358}{58447}{Y:i}pronaðeno u blizini, u svom|uredu. Iskrvario je na smrt
{58453}{58508}{Y:i}iz ubodne rane nožem.|Gorwitz je punih 14 godina
{58514}{58567}{Y:i}bio djelatnik Gradskog|prijevoza.
{58571}{58632}{Y:i}Predsjedatelj Gradskog|vijeæa Queensa, g. A. Mydanik
{58635}{58689}{Y:i}je izjavio kako je poitresen|i rastužen ovim incidentom.
{58691}{58744}{Y:i}Vijest me duboko potresla.|Neæu dopustiti ovakvim
{58746}{58803}{Y:i}napadima da proðu nekažnjeno.|Potraga za poèiniteljima
{58805}{58864}{Y:i}ovog zloèina je na samom|vrhu naših prioriteta.
{58866}{58932}{Y:i}Službenik Rifkin se i dalje|nalazi u kritiènom stanju,
{58938}{58982}{Y:i}dok policija još nema|osumnjièenih.
{59006}{59071}Ima li malo mlijeka za kavu?|-Donijet æu ti. -Hvala, srce.
{59152}{59214}Još kupuješ u Waldbaumu?|-Da, ponekad.
{59250}{59309}Leo, je li to za tebe?|-Da, mama, ja æu.
{59463}{59561}Što je na stvari? -Moramo|razgovarati. Deèki su dolje.
{59574}{59624}Èekaju nas. -Samo da uzmem|jaknu.
{59638}{59713}Imamo torte. Pridruži nam se.|-Ne mogu, hvala.
{59734}{59819}Erica je ovdje. Neæeš uæi?|-Uði.
{59900}{59972}Nisam znao da si ovdje.
{60105}{60175}Dobar dan, gðo. Olchin.|-Izgledaš dobro veèeras.
{60183}{60236}Hvala.
{60242}{60309}Oprostite. U žurbi sam.|-Ne, Willie. Doði malo.
{60403}{60456}Mama...
{60469}{60515}Willie i ja...
{60522}{60577}Razgovarali smo o vjenèanju.
{60740}{60816}Kad je to bilo?|-Sinoæ.
{60844}{60914}A što je sa školom?|-Završit æu je.
{60951}{61051}To je velika odluka. O kojoj|bismo trebali porazgovarati.
{61197}{61294}Will, jesu li to oni?|-Da.
{61317}{61357}Ne, hvala.
{61363}{61436}Zaista moram krenuti. Nisam|mislio da æemo danas
{61442}{61528}potegnuti tu temu. -Mislim|da bi to trebali raspraviti.
{61610}{61673}Will, èekaju nas.
{61699}{61754}Oprosti.
{61773}{61806}Idemo.
{61879}{61933}Hej, Leo.
{61968}{62040}Zvali su me iz Weltecha.|Onaj tip, Hector.
{62049}{62106}Èuli su što se dogodilo.
{62143}{62217}Nude mi zaštitu, obratim li|se njihovim odvjetnicima.
{62239}{62309}Sve bi dali da mogu Franku|nešto natovariti na glavu.
{62332}{62432}Nemoj me odati, Willie.|-Naravno da neæu.
{62441}{62560}Poklopio sam mu slušalicu.|Moramo se u ovome držati
{62566}{62692}zajedno. Slušaj deèke, što æe|ti reæi. Saslušaj ih.
{62770}{62842}Situacija je vrlo nepovoljna|za nas.
{63045}{63089}Kako si, Todd?|-Kako ide?
{63129}{63194}Onaj murjak kog si prebio...|predstavlja nam veliki
{63201}{63272}problem. Probudi li se,|nadrapali smo.
{63310}{63366}Ne znamo što bi ti u tom|sluèaju uèinio da izbjegneš
{63368}{63421}zatvor. -Ne bih vas sjebao.
{63427}{63489}Ali, uhvate li te,|gledaš na doživotnu.
{63539}{63600}Znaš da vas ne bih|cinkao.
{63610}{63675}Što se dogodilo? Mislio sam|da æeš razgovarati s Frankom.
{63692}{63752}Frank je bez utjecaja u|policiji.
{64035}{64094}Na 4.-om je katu u bolnici|Booth Memorial.
{64102}{64152}Sobe su èetverokrevetne.
{64154}{64210}Toddov prijatelj radi tamo|kao medicinski brat,
{64212}{64270}danas je u noænoj smjeni.|On æe te pustiti unutra.
{64275}{64363}Pred sobom stoji èuvar. Radi|smjenu od 8 sati.
{64394}{64584}Èekaj da ode na WC, pa uði.|-Ali, tip je jebeni murjak!
{64625}{64656}Nitko ovo ne želi.
{64724}{64762}Ali nemamo izbora.
{64828}{64888}Ne znam jesam li sposoban za|tako nešto.
{64893}{64973}Razmisli dobro. Taj policajac|je samo tebe vidio.
{64982}{65042}Ne možeš li to sam srediti,|morat æemo to uèiniti na naš
{65044}{65169}naèin. A mi neæemo dirati|u policajca. Jasno?
{65766}{65830}Èekajte ovdje, deèki. Todd|æe razgovarati s tipom.
{66041}{66130}Leo?
{66136}{66190}Dogodi li se što...
{66199}{66266}...poðe li što po krivu...
{66277}{66334}...bježi.
{66341}{66400}Napusti grad.
{66493}{66558}Ja æu se pobrinuti za tvoju|majku.
{66697}{66755}Osjeæam se kao da æu umrijeti.
{66860}{66944}Požuri. Još malo i gotova|mi je pauza.
{68009}{68068}Nemoj odustati.
{72146}{72206}Kako se osjeæate?
{72232}{72300}Pozvao sam vaše najbliže.|Na putu su ovamo.
{72333}{72397}Neko vrijeme niste bili|pri svijesti.
{72411}{72511}Odmorite se.|Zaslužujete odmor.
{73259}{73317}Što se dogodilo?|-Kuronja je pobjegao!
{73338}{73480}Prijatelj ti je mrtav, Willie!|Èuješ li? Mrtav!
{73755}{73822}Nešto nije u redu? -Nije se|noæas vratio s posla.
{73835}{73908}Što se dogodilo?|-Ne znam.
{73936}{73991}Jutros se nije javio svom|službeniku za uvjetnu.
{73996}{74024}Zvali su.
{74040}{74098}Tako je prekršio uvjetnu,|rekli su.
{74106}{74153}Prekršio je uvjetnu.
{74164}{74200}U redu je. Sjedni.|Smiri se.
{74205}{74248}Ali, što ako...?
{74258}{74311}Što ako mu se nešto dogodilo?
{74318}{74363}Val, slušaj me.
{74369}{74429}Sestra si mi. Volim te, ali|ne možeš dozvoliti da te ovo
{74431}{74491}i dalje ubija. Èuješ me?
{74956}{75014}U redu, gospodo. Doðite.
{75024}{75071}Do samih traènica.
{75089}{75149}Slikajte sve elektriène sheme|u signalnim kutijama.
{75158}{75238}Napravi prema specifikacijama.
{75301}{75356}Za veliki broj ugovora,|manjinske tvrtke æe
{75361}{75409}imati prednost.
{75697}{75777}Jesi li razmislio o mojoj|ponudi? -Skini mi se s vrata.
{75936}{75996}Možeš li nas malo pogurati|kod ovog ugovora? -Ne bih se
{75998}{76082}previše trudio, da sam na|tvom mjestu. -O èemu ti to?
{76102}{76179}Glavni istražitelj je došao|do novih podataka. Pogoðeni
{76181}{76252}policajac je pregledao krim-|albume i imaju osumnjièenog.
{76254}{76292}Tvoj neæak.
{76299}{76357}Žao mi je što sam ti to ja|morao reæi.
{76383}{76439}Ulovit æe te.|-Zaèepi.
{76477}{76534}Ti æeš biti prvi na|optuženièkoj klupi.
{76740}{76795}Zašto mi nisi spomenuo|umiješanost u ubojstvo?
{76797}{76860}Mislili smo to sami riješiti.|-Ti si kreten.
{76885}{76956}Ovo bi nas moglo uništiti.|Poveže li nas Vijeæe s
{76962}{77034}ubojstvom, s poslom je gotovo.|Svi bismo mogli završiti u
{77040}{77101}zatvoru. -Nisam ga trebao|pustiti s vama. Leo je poput
{77105}{77171}tempirane bombe. -Sve æe se|srediti. Leo je otišao.
{77196}{77271}Nitko ne zna da je radio kod|nas. -Neæe prestati kopati.
{77292}{77357}Ti misliš da je istraga za|umorstvo vremenski ogranièena?
{77384}{77451}Tko je ubio nadglednika?|Leo?
{77648}{77707}Jasno mi je. Pokušavaš|zaštititi prijatelja.
{77733}{77794}Moramo izbjegavati|tvog neæaka.
{77802}{77860}Opovrgnuti da je ikada radio|ovdje. Razgovarat æu s
{77862}{77933}raèunovodstvom, provjeriti da|nisu ispunili nikakve porezne
{77935}{78017}kartone. Dat æu i izjavu,|kako nas je razvoj dogaðaja
{78022}{78124}sve pogodio. -Ništa ti od|toga neæe upaliti.
{78134}{78212}Prije ili kasnije æe ih|nešto navesti na nas.
{78220}{78275}Morat æemo porazgovarati|s tim murjakom.
{78281}{78339}Koliko traži za mijenjanje|iskaza.
{78358}{78411}Veèeras je zabava kod|predsjednika vijeæa.
{78417}{78470}Porazgovarat æu sa|Seymourom...
{78476}{78532}... vidjeti možemo li se|za što uhvatiti.
{78616}{78674}Mislio sam da mogu pomoæi.
{78703}{78777}Mislio sam da æu mu pomoæi.
{79347}{79414}Žao mi je.
{79687}{79767}Èekamo njih? -Znaš da|ih uvijek moramo èekati.
{79781}{79833}Hej...!
{79840}{79906}Hej, Bernie.|Kako si?
{80106}{80159}Jesmo li spremni za pokret?
{80165}{80229}Odmah æemo siæi.|-Odmah?
{80240}{80325}O èemu se radi? -Je li|Willie dolje? -Da.
{80496}{80536}U èemu je stvar?
{80543}{80628}Razmišljaju o ženidbi. -Ne|želim o tome s njim
{80641}{80772}raspravljati. On mi nije otac.|-Majka ti je vrlo uzrujana.
{80816}{80866}Ne bismo li trebali|porazgovarati o tome?
{80876}{80951}Ne bi li ti odjebao iz moje|sobe? -Hej! -U redu je...
{80959}{81027}Slušaj, radi onako kako ti je|po volji. Želiš li uzrujati
{81032}{81130}majku, samo naprijed, udaj se.|Želiš li srljati u brak bez
{81137}{81237}promišljanja, samo naprijed.|Ali spremi se veæ jednom.
{81298}{81342}Spremi se.
{81500}{81600}Znaš šta on radi?|- Šta?
{81663}{81730}Šta misli gde on zaraðuje|za ono što ti kupi?
{81730}{81754}Ona njegova kola...
{81820}{81954}Frenk mi ništa ne kaže, |ali dobijam ideju šta se dogaða.
{81986}{82012}Neznam o èemu prièaš.
{82045}{82211}Šta god bilo nastradat èe.|Govorila sam sa mojom sestrom.
{82800}{82829}Kako si, Harriet?|-Drago mi je što te vidim.
{82849}{82902}Zaželimo Arthuru sretan|roðendan.
{82925}{82965}Veæ sam mu ga toliko puta|zaželjela...-Sada jesi.
{83320}{83404}Eno ga. Hej, Manny!|Drago mi je što te vidim.
{83474}{83525}Arthure.
{83616}{83674}Mislim da te nije èuo.
{83831}{83895}Kako izgleda odavde, imaju|neko ukusno peèenje ondje.
{83897}{83965}Idite vi, naðite mjesta.|Pridružit æu vam se za minutu.
{83967}{83987}U redu.
{84088}{84143}Javio sam se Artu kako bih|ga pozdravio, a on me potpuno
{84145}{84202}ignorira. -Ne smije se u ovom|trenutku pojavljivati s tobom
{84204}{84251}u javnosti previše.|-Bilo mi je neugodno.
{84253}{84311}Znaš li koliko sam novaca|uložio u njegovu kampanju?
{84316}{84376}Prièekaj dok se prašina malo|ne slegne, u redu?
{84422}{84511}Što znaš o tom murjaku,|koji nam je sve ovo zakuhao?
{84521}{84583}Kaže da je siguran za|osumnjièenog.
{84591}{84650}Koliko siguran?|-Ne znam.
{84662}{84715}Što misliš time reæi?
{84720}{84779}Mislio sam, možda bi mogli|osnovati kakvu zakladu u
{84785}{84818}njegovo ime.
{84824}{84891}Dobio je udarac u glavu,|možda ga sjeæanje baš i
{84896}{84953}ne služi najbolje.
{84958}{85003}Izvidit æu situaciju.
{85012}{85076}Daj, molim te. Jer željeli|bismo mu pomoæi na neki naèin.
{85085}{85147}aPrije nego ova istraga|izmakne kontroli.
{85720}{85769}Ne mièite se!
{85782}{85838}Nalog za pretres. Tražimo|vašeg sina. Je li ovdje?
{85844}{85905}Ne. Što to radite? -Imamo|uhidbeni nalog za vašeg sina.
{85933}{85992}Gospoðo? Jeste li dobro?
{86048}{86104}Nema ga ovdje. Idite,|molim vas.
{86109}{86197}Ovamo, Joe.|-Kao da ju boli u prsima.
{86211}{86282}Izbaci sve van. Idemo!|Provjeri da nema oružja!
{86314}{86369}Ima problema s disanjem.|Pozovi hitnu.
{86480}{86545}{Y:i}Službenik Gerald Rifkin æe|uskoro biti pušten iz bolnice.
{86553}{86646}{Y:i}Rifkin, koji je ozlijeðen u|napadu na Sunnyside ranžirnoj
{86651}{86720}{Y:i}stanici, u Queensu, se|oporavio od ozljeda.
{86728}{86796}{Y:i}Policiji je dao prvi trag u|otkrivanju poèinitelja napada,
{86801}{86864}{Y:i}kao i umorstva Nadglednika|Gradskog prijevoza.
{86870}{86975}{Y:i}Nakon pregleda krim-albuma|identificiran je 24-godišnji
{86982}{87058}{Y:i}bivši osuðenik, Leo Handler,|kao njegov napadaè.
{87066}{87125}{Y:i}lako policija vjeruje da je|Handler napustio državu,
{87132}{87204}{Y:i}svi koji imaju bilo kakva|saznanja o mjestu njegova
{87211}{87269}{Y:i}prebivališta umoljavaju|se neka se jave najbližoj
{87271}{87307}{Y:i}policijskoj postaji. Slijedi:
{87314}{87371}{Y:i}gdje ste se nalazili kad|je u gradu nestalo struje?
{87445}{87484}Halo?
{87491}{87542}{Y:i}Ja sam, Will.
{87613}{87735}Gdje si?|Jesi li dobro?
{87761}{87819}{Y:i}Optužen sam za stvari koje|nisam poèinio. Za sve me
{87823}{87879}optužuju. Nemam kuda otiæi,|ne mogu ni sa kim
{87886}{87960}porazgovarati. -Žao mi je.|U ovom trenutku ti ne mogu
{87969}{88039}pomoæi ni na koji naèin.|-Kada se mogu vratiti?
{88056}{88161}{Y:i}Moraš se još malo pritajiti.|-Kako mi je majka?
{88176}{88237}Nazvao bih je, ali vjerojatno|prisluškuju telefon.
{88241}{88298}{Y:i}Jesi li ju vidio?
{88326}{88366}Willie?
{88404}{88462}Jesam.
{88470}{88524}Je li dobro?
{88530}{88593}Bit æe u redu.|-Što nije u redu?
{88602}{88678}Sve je u redu. Obitelj je uz|nju i dobro je.
{88715}{88771}Èujem ti po jebenom glasu da|nešto nije u redu!
{88773}{88885}Ne, slušaj, Leo. Smiri se.|Ne mogu razgovarati sada.
{88922}{89041}{Y:i}Nazovi me za par tjedana.|I znaj, Frank æe sve srediti,
{89074}{89132}{Y:i}radi na tome, dobro?
{89180}{89246}Jesi li na liniji?
{89255}{89298}Da, dobro.
{89919}{89979}Je li ti majka gore?
{89988}{90047}Što radiš ovdje?
{90062}{90127}Hoæeš da te uhvate?
{90164}{90250}Policija je bila ovdje. -Znam,|gledao sam ih kako dolaze
{90255}{90293}i odlaze.
{90320}{90373}Idem na stražnji ulaz.
{90380}{90442}Pusti me unutra.
{90450}{90490}Poslušaj me.
{90504}{90551}Moram je vidjeti.
{91165}{91256}Mama...|Jesi li budna?
{91468}{91527}Kako se osjeæaš?
{91662}{91722}Došao sam te vidjeti kako si.
{92028}{92092}Znam da nisam sin kakvog|bi voljela imati.
{92207}{92278}I sam sebi sam obeæao da|æu uèiniti što god treba
{92283}{92360}kako bih se uklopio.
{92433}{92495}Ono što sam prije uèinio,|znam da je bilo loše.
{92503}{92571}Ali nisam uèinio ništa od|ovoga za što me optužuju.
{92716}{92759}I znam...
{92766}{92824}Znam da se nikad neæu moæi|iskupiti na pravi naèin.
{92875}{92949}Želio sam ti to reæi.
{92982}{93041}Nisam ga ja ubio, mama.
{93312}{93385}Želio sam je samo vidjeti.
{93466}{93594}Je li Willie bio s tobom?
{93660}{93717}Na ranžirnom kolodvoru?
{93929}{94014}Nije to on uèinio, zar ne?
{94841}{94913}Moraš biti jaka.
{94954}{95011}Znam da ste imali planova.
{95025}{95084}Moramo pronaæi naèin kako|da se izvuèemo iz ovoga.
{95101}{95267}I pronaæi æemo ga.|-Doði...
{95482}{95581}Hvala ti na brizi za nju.Doæi|æu sutra opet. Pozovi doktora.
{95849}{95909}Oprostite što prekidam vaš|sastanak. Ja sam detektiv
{95911}{95961}Tommasino. -Kako ste?|-Detektiv Bulette.
{95966}{96021}Kako vam mogu pomoæi?|-Pogledajte ovu sliku.
{96025}{96094}Postavio bih vam par pitanja.|Imate li ikakva saznanja gdje
{96097}{96169}bi se mogao nalaziti? -Sreo|sam ga svega par puta.
{96192}{96244}Supruga mi kaže da uvijek|upada u neke nevolje.
{96248}{96340}Nije bio vaš zaposlenik?|Vaša tajnica nam je rekla da
{96347}{96419}je bio na razgovoru kod vas.|-Tako je. Tražio je posao,
{96424}{96485}ali nisam imao nikakvo|otvoreno mjesto za njega.
{96543}{96615}Kontaktirajte nas, saznate|li išta o tome gdje se nalazi.
{96628}{96664}Naravno.|Nema problema.
{96666}{96725}Hvala vam što ste nam|posvetili dragocjeno vrijeme.
{96727}{96767}Hvala.
{96913}{96990}Seymour, što si otkrio?|-Bit æe saslušanja u vezi
{96996}{97084}ubijenog nadglednika ranžirne|stanice. Ima još nešto, Frank.
{97121}{97184}Sinoæ sam razgovarao s|Naèelnikom policije.
{97191}{97250}Policajac je nepotkupljiv.|Rekao je, nema nikakvog
{97254}{97329}izgleda da æe Rifkin|pristati na mito.
{97346}{97406}Može li nam Myotonic tu|kako pomoæi? -Kako to misliš
{97408}{97465}"pomoæi"? Mali je ubojica.
{97479}{97602}Što ti je murja rekla?|-Što misliš? Traže ga.
{97646}{97710}Možda bi ga ti trebao srediti|prije nego ga se oni doèepaju.
{97762}{97828}Što?! -Da nikada ne|ispliva na površinu.
{97912}{97967}Što želiš time reæi?
{98016}{98077}Što ti misliš, tko sam ja?!
{98099}{98158}Samo da je njegovo uhiæenje|prioritet broj jedan
{98163}{98236}predsjedniku vijeæa. Ne želi|završiti kao onaj samoubojica,
{98240}{98293}Donnie Manes.
{98324}{98420}Morat æete nešto drugo|smisliti u vezi rješenja
{98426}{98503}tog problema.
{98510}{98569}Nikad nešto takvo ne bih|mogao uèiniti.
{98628}{98719}Mali kuronja je u mojoj|obitelji!
{98771}{98825}Neka ostane tamo gdje jest.|Pobrini se za to.
{98954}{99033}Možemo li što uèiniti,|doktore?-Dao sam joj Digoxin,
{99039}{99096}pa æemo pratiti kako se|situacija razvija.
{99101}{99162}Imate li kakav kontakt-broj|na koji vas možemo dobiti?
{99177}{99222}Držite se.|-Hvala.
{99229}{99276}Dobar dan, gðice. Olchin.|Hej, srce!
{99278}{99340}Tvoj brat mi je rekao da æu|te naæi ovdje. Cijeli te dan
{99342}{99379}pokušavam dobiti telefonom.
{99386}{99438}Idem unutra.
{99530}{99666}Gdje si cijeli dan?|-Ovdje sam. -Znam to.
{99692}{99767}Zašto mi ne uzvraæaš pozive?|-Puno se toga dogaða u
{99771}{99837}posljednje vrijeme.
{99939}{100010}Ima li tvoja majka kakvih|problema sa mnom?
{100045}{100112}Ne, koliko ja znam, nema.
{100133}{100196}Vidio sam kako me pogledala|kad si joj rekla za ženidbu.
{100270}{100353}Mislim da bi trebao iæi. -Ne.|Želim razgovarati s tobom.
{100412}{100471}Nemam ti što reæi.
{100558}{100633}Je li to zbog onog što se|dogodilo s Leom?
{100670}{100736}Idem natrag unutra.|-Erica, èekaj!
{100742}{100802}Želim razgovarati s tobom.|Saslušaj me. Erica...
{101461}{101544}Uskoro je saslušanje. Znaèilo|bi mi kad bi pošla sa mnom,
{101549}{101605}za podršku. -U redu.
{101745}{101816}Kako ti je sestra?
{101861}{101927}Što je, dušo?
{101934}{101994}Vidjela sam Lea veèeras,|ispred stana.
{102138}{102212}Vidjela si Lea veèeras...
{102232}{102296}Sve æe nas u nevolju uvaliti.
{102392}{102496}aRekao si mi da se neæe|vraæati -Bio sam tamo veèeras.
{102507}{102582}On je bio tamo?|-Da, bio je tamo.
{102624}{102685}Moramo to nekako|riješiti.
{102708}{102766}Što želiš da uèinim?
{102817}{102912}Moju ženu to...|jako uznemirava.
{102983}{103070}Erica puno vremena provodi|s Leom, u posljednje vrijeme.
{103081}{103137}A ona ne voli da su zajedno...
{103144}{103202}Zbog onog što se meðu njima|dogodilo.
{103233}{103291}Na što ciljaš?
{103331}{103403}Ti ne znaš...
{103511}{103569}Uhvatila ih je zajedno kad|im je bilo 15 godina.
{103668}{103726}Nisam to znao.
{103857}{103912}Znaš, pronašao sam neka|njegova pisma koja joj je
{103920}{103983}slao, ali nikada nisam|mislio da...
{104301}{104363}Volio bih da postoji naèin|na koji možemo riješiti taj
{104365}{104412}problem.
{105119}{105177}Što radiš ovdje?
{105452}{105511}Došao sam obiæi svoju majku.
{105589}{105650}Svoju majku?
{105734}{105797}Ne bi smio biti ovdje.
{105802}{105865}Otišao je na krov provjeriti|je li sigurno. -Zaèepi!
{106002}{106058}Zašto si se vratio?
{106128}{106194}Sve si sjebao.
{106220}{106251}Pusti ga da...
{106263}{106297}Willie, koji ti je vrag?
{106307}{106338}Koji je tebi vrag?!
{106355}{106393}Pusti me.
{106416}{106454}Ti, jebeni...
{106581}{106684}Hajde!
{107505}{107576}Hajde!|-Šupèino!
{107587}{107638}Šupèino!
{108056}{108116}Gotovo je, Will.|Bilo je dosta.
{108279}{108335}Zajebao si me, Will!
{108342}{108395}Zajebao si me.
{109391}{109468}Frank?
{109742}{109808}Isuse, što se tebi dogodilo?
{109815}{109879}Je li te majka vidjela takvu?
{110116}{110200}Znam da nisam bila|pravedna prema Vama.
{110248}{110300}I nisam Vam ni pružila|priliku da budete otac
{110306}{110366}mom bratu i meni.
{110396}{110462}Žao mi je zbog toga.
{110583}{110647}Znam koliko Vam to znaèi,|koliko ste se trudili.
{110725}{110794}Nadam se da mi možete|oprostiti...
{110799}{110858}...jer i meni je|to sve teško padalo.
{110983}{111065}Jako sam voljela svog oca.
{111177}{111249}I bili smo vrlo bliski|kao obitelj.
{111381}{111455}Stoga vas sada molim.
{111559}{111630}Leo treba vašu pomoæ.
{111692}{111749}Želi razgovarati s Vama.
{111758}{111832}Rekla sam mu da æete ga|primiti.
{111843}{111913}Molim Vas.
{112388}{112445}Gdje je on?
{112464}{112522}Mogu Vas odvesti.
{112614}{112672}Idi do automobila.
{113356}{113418}Leo?|-Ovdje sam.
{113747}{113808}Puno si mi nevolja zadao.
{113817}{113880}Morao sam na razgovor s|policijom.
{113886}{113948}Trebam Vašu pomoæ.
{113956}{114011}Kako ti ja mogu pomoæi?
{114050}{114117}Doista ne znam.
{114120}{114189}Možda biste mogli razgovarati|s nekim. Ja nisam nikoga ubio.
{114212}{114274}Znaš li tko jest?
{114579}{114651}Volio bih da ti mogu pomoæi.|Zaista bih.
{114708}{114768}Ali moram se boriti svim|sredstvima kako bih zaštitio
{114770}{114813}ono što sam izgradio.
{114818}{114877}Razumiješ, zbog svoje|obitelji.
{114892}{114970}Jer to je sve što mi je|ostalo.
{115107}{115164}Leo...
{116388}{116468}Leo...
{116475}{116541}Pazi na sebe.
{116600}{116659}Ne mogu ostati. Previše|ljudi zna da sam ovdje.
{116684}{116804}Svi su protiv mene.|-Znam.
{116923}{117029}Žao mi je što smo uvijek|bili samo nas dvoje.
{117121}{117188}Koji smo se sa svime sami|morali hvatati ukoštac.
{117246}{117307}Nitko mi drugi nikad niti|nije bio potreban.
{117389}{117558}Ali nikada nisi nikoga|imao...
{117608}{117722}...na koga bi se ugledao.
{117816}{117923}Znala sam gledati biznismene|koji bi putovali na posao.
{117970}{118073}Uvijek sam se nadala da æeš|ti postati jedan od njih.
{118082}{118161}Dobro bi ti stajalo odijelo.
{118218}{118322}Ali tko zna èime se oni|bave.
{118410}{118486}Volim te, mama.
{118499}{118573}Ne gubi vjeru.
{118730}{118807}Veèeras æu ostati malo duže.|-U redu...
{118868}{118931}Bit æe mi dobro.
{119060}{119127}Idem po ostale stvari.
{121455}{121571}Mama. Moram te sada|odvesti do susjeda.
{124501}{124575}Reci Williju da znam|da te on poslao.
{124583}{124645}Reci mu da drži|oèi i na leðima.
{124689}{124800}Pogledaj me.
{124891}{124949}Mogao bih vas sve srediti.
{124998}{125059}Mogao bih. I uèinit æu to.
{125204}{125260}Nemoj.
{125265}{125312}Molim te.
{125317}{125375}Ustaj!
{125621}{125722}Bježimo odavde!|-Jesi li? -Vozi!
{125957}{126042}{Y:i}Na stotine ljudi se oèekuje|na javnom saslušanju
{126048}{126094}{Y:i}gdje æe biti rasprave o|optužbama za
{126101}{126154}{Y:i}korupciju u željeznièkom|javnom prijevozu.
{126156}{126223}{Y:i}Mydanic je zakazao sastanak|pritisnut optužbama da njegov
{126225}{126284}{Y:i}Ured ne poduzima dovoljne|mjere da se skandal riješi.
{126288}{126351}{Y:i}Neki od mjesnih politièara|kao i direktora željeznica
{126353}{126416}{Y:i}bi vrlo lako mogli završiti|na optuženièkim klupama.
{126420}{126480}{Y:i}Ubojstvo Elliota Gorwitza,|prošli mjesec, kada je i
{126482}{126548}{Y:i}policijski službenik Rifkin|ozlijeðen u napadu na ranžir.
{126550}{126622}{Y:i}kolodvoru je tako pokrenulo|cijelu lavinu dogaðaja.
{126627}{126693}{Y:i}Od tada se u gradu održavaju|demonstracije, poput onih na
{126695}{126788}{Y:i}Manhattanu koje su završile|nasiljem. 29-ero ljudi je
{126793}{126851}{Y:i}uhiæeno za napad i|nedolièno ponašanje.
{126856}{126917}{Y:i}Policija je još u potrazi za|Leom Handlerom, jedinim
{126919}{126972}{Y:i}osumnjièenikom u sluèaju|Gorwitz.
{127062}{127118}Frank je vrlo zabrinut,|Willie.
{127123}{127203}Upravo sam se èuo s njim.|Želi znati kako je prošlo.
{127278}{127357}Imali smo malih problema...
{127391}{127438}...ali æemo pokušati ponovno.
{127485}{127535}Sredit æete to?
{127629}{127701}U koliko je sati saslušanje?
{127708}{127793}Ne znam hoæeš li ti biti|tamo. -Zašto ne?
{127801}{127859}Frank i ja mislimo da to ne|bi bila dobra ideja.
{127866}{127939}Zbog istrage.
{128068}{128129}Frank misli da ne bih trebao|biti prisutan?!
{128144}{128204}Znaš kako je.
{128252}{128349}Takoðer ti je poruèio da ga|više ne zoveš kod kuæe.
{128395}{128486}l, ti imaš kljuèeve, zar ne?
{128511}{128544}Da.
{128563}{128621}Želi ih natrag.
{128658}{128717}U redu?
{128747}{128888}Nemam ih sada sa sobom.|-U redu je. Ostavi ih kod
{128893}{128966}njega kad god možeš. Malo je|zabrinut za svoju sigurnost.
{129029}{129084}Vidimo se, Willie.
{129450}{129521}Halo, Weltech? -Molio bih|vas Hectora Gallardoa.
{129528}{129595}Samo trenutak.
{129608}{129665}Halo? -Ovdje Willie|Gutierrez.
{129674}{129721}Zakasnio si.
{130149}{130223}Svrha sastanka je rašèistiti|stvari pred javnosti,
{130237}{130297}dati ljudima glas te|najaviti našu istragu.
{130305}{130345}O ostalim navodima|æemo kasnije.
{130354}{130407}Pridrži mi ovo, molim te.
{130576}{130645}Bok, Frank. Kako si?
{130688}{130741}Pomakni se jedno mjesto.
{130821}{130872}Jesi li razgovarao s|Willijem?
{130880}{130945}Da. Još pokušava|riješiti onu stvar.
{130948}{131013}Nemaš razloga za brigu. Rekao|sam mu neka se drži podalje.
{131015}{131090}Gdje je Sequiera?|-Nisam ga vidio.
{131122}{131209}Sigurno on i ovi iz Weltecha|žele uæi na velika vrata.
{131726}{131784}Frank, okreni se.
{132081}{132144}Isuse. Što on radi ovdje?
{132416}{132523}Voljan je predati se nakon|ovog postupka. Jamèim za njega.
{132674}{132734}Reci Vijeænicima da moramo|razgovarati, odmah.
{132749}{132836}Mydanic mora biti prisutan,|naglasi mu to.
{133156}{133214}Neka bude kratko.
{133251}{133305}Imamo novi problem.
{133311}{133383}Mi? Kako to misliš, "mi"?|On je tvoj neæak.
{133392}{133453}Od sada moraš sam, Frank.
{133471}{133564}Bacaš me vukovima? Imam sve|dokumentirano. Kopiju svakog
{133570}{133633}èeka koji si primio, kojima|si kupio jebenu kuæu u
{133639}{133734}Sands Pointu. Nemojmo se|blesavima praviti, u redu?
{134813}{134934}O èemu mi to prièamo?|Dogodilo se umorstvo.
{134945}{135012}Ne možemo trgovati|ljudskim životom.
{135023}{135146}A ovog èovjeka ovdje su|krivo optužili za zloèin.
{135169}{135227}U redu, slušaj. Zašto mi|sve to govoriš?
{135249}{135323}Govoriš o mom neæaku. Uèinit|æu sve što mogu kako bih mu
{135329}{135421}pomogao. Možemo li se|dogovoriti tako da svi
{135426}{135485}budemo sretni?|-Ne znam, Frank.
{135532}{135621}Tvoj neæak ima svašta za reæi|o poslovanju tvoje tvrtke.
{135650}{135734}Svi imaju pravo to èuti.|Hajdemo.
{135745}{135824}Èega dobrog nam to može|donijeti? Ne možemo li to
{135831}{135892}aariješiti na lijep naèin?|-Ne razumiješ.
{135925}{136015}Dugo su nas ovaj èovjek i|ovi ljudi potiskivali van
{136020}{136103}iz posla. Mislim da je|stiglo vrijeme za naplatu.
{136116}{136223}Slažete li se?
{136747}{136805}Što ti radiš ovdje?
{136815}{136866}Donio sam kljuèeve.
{136888}{136944}Mislio sam da si na|saslušanju.
{136948}{137003}Bila sam u školi.
{137009}{137068}Tražiš li Lea, ne znam gdje|se nalazi.
{137082}{137160}Ne tražim Lea.|Znam gdje je.
{137239}{137314}Artie. Seymour mi kaže da|si me trebao. -Uði, Sal.
{137347}{137416}Ovo je Donaèelnik Disipio, iz|Policijske Uprave Plaza.
{137422}{137460}Kako ste?
{137467}{137526}Imamo jedan problemèiæ.|Nadamo se vašoj pomoæi.
{137535}{137589}Sve za tebe, Artie.
{137596}{137680}Mišljenja smo da je vaš|službenik Rifkin malo smušen.
{137688}{137754}Tako?|-Da, tako.
{137774}{137836}Ovaj ovdje mladiæ, on nije|èovjek koga tražite.
{137852}{137940}Razumijemo patnje koje je|službenik Rifkin prošao,
{137948}{138007}i spremni smo mu to|kompenzirati.
{138027}{138091}Naravno, mi vama dostavimo|odreðeni iznos,
{138107}{138196}a vi ga rasporedite|po vašoj volji.
{138304}{138373}Nevinog su te optužili?|-Da.
{138391}{138436}Mogu vam pomoæi u tom|sluèaju jer znam
{138443}{138531}tko je poèinitelj.|-Spreman si svjedoèiti?
{138555}{138616}Da, definitivno.
{138763}{138835}Mislim da bi mogli riješiti|veæi dio vaših problema.
{138846}{138898}Prièa se da je Rifkin|velika poštenjaèina.
{138904}{138972}Zna biti tvrde glave, ali|ponekad pretjera u noænom
{138979}{139065}batinjanju. A obojica znamo|da ne bi volio da se proèuje.
{139128}{139198}Sve sad ovisi o tebi.
{139275}{139336}Želim samo 20%.
{139362}{139440}Od svih ugovora.
{139551}{139617}To je pošteno.
{139630}{139685}Smatram da jest.
{139778}{139838}Leo je bio pametan.
{139844}{139916}Napravio je ono što sam ja|trebao od samog poèetka.
{139932}{140000}Malo je kasno za to sada.
{140038}{140118}Da. Sigurna sam da æe biti|sve u redu s tobom.
{140166}{140250}Svi me pokušavaju iskljuèiti.|-Ne mogu ti pomoæi.
{140259}{140298}Erica, èekaj!
{140314}{140349}Èekaj!
{140510}{140565}Prestani!
{140704}{140775}Volim te, Erica.|Tako mi je žao.
{140898}{140988}Nemoj bježati od mene,|molim te. Ti si sve što imam.
{141180}{141240}Tako te puno volim.
{141509}{141567}Kuda æeš?
{141636}{141679}Doði.
{141717}{141780}Ideš vidjeti jebenog Lea?
{141789}{141852}Kako je to bolesno,|vas dvoje! Kako bolesno!
{141915}{141943}Ne!
{142086}{142124}Ne!
{142186}{142238}Ne!
{142271}{142330}Pusti me na miru!
{142685}{142765}Dobra veèer, dame i gospodo,|cijenjeni Donaèelnièe Disipio
{142771}{142846}i poštovani èlanovi|policijskih snaga.
{142858}{142918}Želim vam svima reæi kako|sam zatražio unutarnju
{142923}{143011}istragu koja se ne može|mjeriti opsegom ili razmjerom.
{143046}{143129}Svjestan sam èinjenice da|nas neki problemi ovdje
{143131}{143191}u opæini i našoj zajednici|mogu lako podijeliti, ali
{143193}{143258}vaše pojavljivanje veèeras|oznaèava jedno povjerenje u
{143260}{143285}naš sustav.
{143287}{143343}Rezultati naše unutarnje|istrage, koji æe biti
{143345}{143412}objavljeni sljedeæeg tjedna,|æe pokazati da su iskazi
{143414}{143488}nekih predstavnika medija te|umiješanih graðana potpuno
{143490}{143515}neosnovani.
{143520}{143622}Naša istraga je pokazala da|bi se osumnjièenog,
{143627}{143685}komu smo veæ neko vrijeme|za petama,
{143691}{143754}trebalo osloboditi svih|optužbi.
{144917}{144986}Oprostite, gospodine...?|Imamo dojavu alarma.
{144989}{145066}Možete li mi pokazati vašu|dozvolu, prometnu te zelenu
{145068}{145110}kartu?
{145130}{145178}Gospodine?
{145278}{145324}Izaðite iz automobila.
{145401}{145455}Zovi pojaèanje.|-Primljeno.
{145491}{145573}Što si radio unutra?|Jesi li ukrao štogod?
{145769}{145826}{Y:i}Naš izvještaj, koji æe|sljedeæi tjedan biti
{145831}{145908}objavljen, æe pokazati da se|na našoj podzemnoj željeznici
{145915}{145982}dogaðaju brojni sluèajevi|nasilja. Imamo veliku
{145988}{146053}obvezu prema našem|javnom sustavu prijevoza.
{146065}{146119}Ne možemo dozvoliti da|nasilje huligana uništi
{146121}{146241}{Y:i}naš grad. Naša srca odlaze|obitelji g. Gorwitza.
{146258}{146322}{Y:i}Umorstvo g. Gorwitza velika|je tragedija.
{146324}{146383}{Y:i}Veæ smo mnogo puta pokazali|kako možemo djelovati
{146385}{146468}{Y:i}ujedinjeno. Gledajuæi mnoštvo|ovdje sakupljeno, vidim...
{146502}{146589}G. i gðo. Olchin? Možete li|poæi s nama. Radi se o vašoj
{146599}{146783}kæeri. Žao mi je. Naðena je,|mrtva, u vašoj kuæi.
{146801}{146912}Moje sauèešæe.
{147498}{147572}Dame i gospodo, zauzmite|svoja mjesta...
{148885}{148945}Leo...
{149118}{149172}Slušaj...
{149180}{149241}Želio sam ti reæi...
{149247}{149354}Ne moraš ništa brinuti,|imam prijatelje na visokom položaju.
{149359}{149479}Postarat æu se,|da ona životinja dobije svoje.
{149583}{149634}A ubuduæe...
{149646}{149666}Što god ti zatreba...
{150321}{150387}Ideš li unutra?
{150463}{150560}Potreban si majci.
{150815}{150866}Doði.
