{1}{1}25.000
{1646}{1733}ULOGE:
{1917}{2003}U B O J I C A    M E K 0 G | S R C A 
{3130}{3206}Treba mi novac. - Da, jutro | je zbilja krasno.
{3209}{3287}Sunce sja, ptice cvrkuæu.
{3289}{3382}Jedini zubar kojeg znam koji | ne zna zaraditi. - Zbilja?
{3385}{3502}A njen otac? - Kao zubar, | moj muž je bio veoma uspješan.
{3512}{3639}Druga stvar... - Ima rijeè za | tu drugu stvar. Pronevjera!
{3647}{3739}Kad smo kod toga, | koliko ti treba, draga?
{3746}{3840}5 bi vjerojatno bilo | dovoljno. - Tisuæa? Za što?
{3877}{3973}Tvoj otac bi bio | ponosan.
{3980}{4048}Vidjet æu što mogu uèiniti. | U meðuvremenu, dame,
{4051}{4108}želim vam ugodan dan.
{4111}{4200}Bio bi, kad bi mi uèinio | uslugu i umro!
{7344}{7441}Redatelj:
{7560}{7650}Oprosti, prijetiš li | ti to meni?
{7664}{7760}I mislila sam da ne. | Predomislila sam se, u redu?
{7770}{7865}Da, vratit æu ti novac. | Da, da, madam Dupre.
{8025}{8095}Dobro jutro, doktore.
{8105}{8184}Dobre vijesti, g. Boulez. | Neæemo morati vaditi zub.
{8189}{8247}Treba ga samo bušiti. | - Slušajte, doktore.
{8254}{8321}Neæu bušilicu. - Neæete | bušilicu? - Neæu bušilicu.
{8328}{8405}Mrzim je. Dajte mi plin, | izvadite zub i ostat æemo
{8412}{8488}prijatelji. U redu? | Odlièno!
{8663}{8745}Samo hamburger i pomfrit. | - Ja æu hamburger, ali ovaj
{8752}{8861}put bez majoneze. - Bez | majoneze? - Ni mrvicu. Dobro?
{8908}{9040}Stavit æe majonezu. - Smijem | nešto reæi? 0stavi gaduru!
{9083}{9200}Molim? - Svoju ženu. 0stavi je. | Naði drugu i poèni ispoèetka.
{9207}{9333}Oze, znam da me se ne tièe | i da radim za tebe 3 tjedna.
{9349}{9465}Ali kažem ti što vidim. | Tvoja žena nije dobra osoba.
{9471}{9546}Oèekuješ da ti proturjeèim? | - Zašto se onda muèiš?
{9552}{9615}Razvedi se od nje! - Ne | mogu si to priuštiti.
{9620}{9695}Opelješit æe me. Veæ | otplaæujem dug njena oca.
{9702}{9771}Znaèi iskorištavat æe te dok | ne isplatiš dug njena oca?
{9776}{9866}Jako je šarmantna. - Ne može | si pomoæi. Njena majka...
{9871}{9974}Da se lijepo izrazim... | Ona je antikrist.
{10001}{10102}Uèinio bi svijetu uslugu kad | bi našao nekog da je kokne.
{10146}{10227}A ti znaš nekog tko bi to | uèinio? - Nazoèni se
{10234}{10308}iskljuèuju? - Izvolite. | - Hvala.
{10315}{10381}Govorimo teoretski ili | želiš da navedem cijenu?
{10389}{10460}Trebaš razgovarati s mojom | ženom. Obogatila bi se.
{10467}{10540}Zašto to kažeš? - Zbog police | osiguranja. Više vrijedim
{10544}{10615}mrtav nego živ.
{11179}{11281}U blagovaonicu. Sklonite | to plastièno smeæe.
{11286}{11350}Možete li se kretati sporije?
{11362}{11431}Vi ste sigurno naš novi | susjed. Nicholas Oseransky.
{11437}{11497}Zovite me 0z.
{11511}{11599}Jimmy. | Jimmy Jones.
{11623}{11730}Jesmo li se veæ sreli? | - Ne. - Sigurni ste? - Da.
{11737}{11797}Sjetio bih se. Odlièno | pamtim lica. - Neobièno.
{11804}{11861}Tako ste mi poznati. | Odakle ste? - G. Jones?
{11867}{11937}Gdje želite da | ovo stavimo?
{12070}{12128}Ništa nisam vidio, | kaže Tudeski
{12135}{12196}Njegova usta su nijema
{12241}{12299}Tulipan vene, | Istražni sud prijeti Tudeskom
{12305}{12376}Tulipan cinkari
{12435}{12516}Razgovor s plaæenim | ubojicom
{12606}{12655}Osloboðen
{12662}{12749}Na kat, u stražnju | spavaæu sobu. Što ste rekli?
{12818}{12902}Jeste li dobro? - Jesam. | - Sigurno? Lzgledate
{12909}{12988}kao da vas muèe | plinovi.
{13005}{13109}Pojeo sam hamburger za ruèak. | - Stavili su majonezu?
{13114}{13196}Da. - Zašto to rade?
{13201}{13279}Svaki punokrvni Amerikanac zna | da je jedini dodatak koji
{13286}{13383}se treba staviti na | hamburger... keèap!
{13392}{13481}Ili možda malo specijalnog | umaka koji ovdje u Kanadi
{13487}{13543}jako vole! Mislim da i | u njemu ima malo majoneze.
{13550}{13645}Boga mi, kad pljusnu majonezu | preko, mogao bih nekoga ubiti.
{13650}{13715}Zbilja, zbilja vas nisam | htio uzrujati.
{13721}{13811}Tko je uzrujan? | Samo razgovaramo.
{13872}{13952}Idem ja kuæi. - Dobro.
{13957}{14036}Nadam se da æe vam biti | bolje. - Hvala.
{14077}{14156}Oze... - Da?!
{14171}{14259}Hvala što si navratio i | poželio mi dobrodošlicu
{14265}{14348}u susjedstvo. - U redu.
{14555}{14616}Pakiraj se! | Odlazimo!
{14622}{14676}Isuse!
{14715}{14790}Isuse! Upravo sam naletio na | našeg novog susjeda.
{14797}{14881}Znaš li tko je to? | - Vjerojatno æeš mi ti reæi.
{14887}{14968}Jimmy "Tulipan" Tudeski. | - I to nešto znaèi?
{14975}{15059}Jimmy Tulipan je bio plaæeni | ubojica u bandi Gogolak!
{15075}{15146}Banda Gogolak. Maðarska | banda u Chicagu koja je
{15152}{15222}vodila sjeverni dio grada. | Taj Jimmy je bio glavni
{15229}{15311}nasilnik Laszla Gogolaka!
{15525}{15632}Seksi. - Sophie, taj èovjek | je ubio 17 ljudi.
{15637}{15708}Odakle mu glupi nadimak? | - Tulipan? To je njegovo
{15714}{15794}cvijeæe koje šalje na | pokope svojih žrtava.
{15801}{15873}Pitam se što radi ovdje? | - Vjerojatno se skriva.
{15879}{15949}Otkucao je Laszla Gogolaka. | Sad je Laszlo na doživotnoj
{15957}{16028}robiji. Jimmy je dobio samo | 5 godina. Dave mi je rekao
{16035}{16091}da je odbio program | zaštite svjedoka.
{16097}{16166}Zaštitu od koga? - Sigurno | Laszlov sin Janni želi
{16173}{16290}staviti cijenu za njegovu | glavu. - Misliš ugovor?
{16314}{16398}Mafijaški ugovor?
{17021}{17121}Bolje ti je? | - Da, hvala. - Dobro.
{17126}{17205}Idemo se provozati. | - Provozati? - Da, provozati.
{17222}{17312}Ti si jedini koga znam | u gradu. Ako se provozamo
{17319}{17410}možeš mi malo pokazati | grad.
{17415}{17475}To te neæe | ubiti, znaš?
{17481}{17535}Obeæavaš?
{17541}{17636}Koliko sam shvatio, ti nisi | Kanaðanin? - Samo brakom.
{17646}{17716}Odakle si? - Iz Chicaga.
{17721}{17788}Ne iz Chicaga...
{17794}{17905}Tamo sam se rodio ali | više ne znam ništa o Chicagu.
{17933}{18057}Dobro. - Potpuno sam zaboravio | sve što ima veze s Chicagom.
{18089}{18176}Ja sam iz Jerseya. | - New Jerseya?
{18183}{18279}Da. Iz New Jerseya. - Ako si | iz Jerseya, iz Jerseya si.
{18285}{18387}Jersy je još jedan grad o | kojem ne znam baš ništa.
{18497}{18581}Uvijek si ovako nervozan? | - Da.
{18588}{18663}Kao i sve ostalo što u mom | životu ne valja, sve je poèelo
{18669}{18765}od moje ženice. U mom rodnom | gradu, njen otac i ja smo
{18772}{18833}imali zajednièku zubarsku | ordinaciju.
{18840}{18896}Ti si zubar? | - Bojim se da jesam.
{18900}{18991}Sklon si samoubojstvu? | - Zašto to kažeš?
{18997}{19068}Jednom sam proèitao da su | zubari skloni samoubojstvu.
{19073}{19161}Jimmy, možda mrzim svoj život, | ali ne želim umrijeti!
{19167}{19274}Bolje se navikni na to jer | æeš umrijeti. - Ubit æu te!
{19373}{19447}Svi umiru.
{19459}{19517}Prije ili kasnije.
{19522}{19596}Tulipan? - Ne!
{19605}{19704}Prièao si o svom tastu... | - Eto ironije, on jest bio
{19709}{19771}sklon samoubojstvu. | - Statistika ne laže.
{19779}{19833}Uhvaæen je kako | zlostavlja pacijenta.
{19838}{19958}Maloljetnog muškog pacijenta. | - Molim te, nemoj više. - znam.
{19978}{20051}Klinac ga je poèeo | ucjenjivati. Baš u tom
{20057}{20128}trenutku Porezni odjel odluèi | ispitati njegovo varanje na
{20133}{20208}porezu. Trebao mu je novac | i to brzo. Otišao je
{20216}{20297}zelenašu, uzeo veliki zajam | na raèun naše ordinacije,
{20303}{20374}o èemu ja nisam imao pojma | i nastavio u... - Vegas,
{20379}{20471}Atlantic City, Reno. Izgubio | novac, a tebi ostavio raèun.
{20476}{20575}Jesam li u pravu? | - Jesi. Baš je tako!
{20600}{20706}Nakon skandala koji je | uslijedio, bankrota, blamaže,
{20714}{20795}moja žena i njena majka su | odluèile da je najbolje da
{20801}{20893}se preselimo ovamo. | - Voliš živjeti u Kanadi?
{20898}{20996}Ne. Živim ovdje | sa svojom ženom.
{21068}{21171}Sigurno si zubar? - Da, zašto? | - Još nikad nisam sreo zubara
{21179}{21285}koji mi se sviða. - Trudim | se da bude što bezbolnije.
{21316}{21380}I ja.
{21690}{21743}Bilo je dobro.
{21748}{21837}Drago mi je što smo se | bolje upoznali. - Znaš što?
{21840}{21907}I meni.
{21910}{21965}Sad možeš iæi. | - Super.
{21998}{22069}Oze! - Da, draga?
{22076}{22160}Hvala Bogu što si došao kuæi! | - Hvala Bogu što sam došao?
{22166}{22252}Imam ideju. Smislila sam kako | da otplatimo tatin dug!
{22258}{22330}Zaposlit æeš se. | - Ne! - Ne?
{22336}{22416}Zar nisi rekao da je glava | našeg susjeda ucijenjena?
{22422}{22500}To ti je plan? Da nam | ubiješ susjeda?
{22507}{22609}Evo što æeš uèiniti. 0tiæi æeš | u Chicago, saznati tko nudi
{22618}{22703}novac za njegovu glavu... | - Glavu Jimmyja Tudeskog?
{22711}{22790}Onda æeš im reæi da znaš | gdje je on ali tek poslije
{22796}{22857}dogovora o honoraru za | nalazaèa. - Honorar za
{22862}{22944}nalazaèa? Za ugovor za | ubojstvo? - Je li to problem?
{22950}{23039}Osim èinjenice da bih | sudjelovao u ubojstvu?
{23045}{23118}Ali on je ubojica. Sam si | to rekao. - To je još jedan
{23123}{23176}dobar razlog da | se to ne uradi!
{23178}{23251}Što god da je skrivio, bio je | na robiji. Platio je dug
{23254}{23331}društvu. - Sad može platiti | i naš dug.
{23339}{23434}Znam da æe ovo zvuèati ludo, | ali bio sam s njim danas
{23440}{23547}i prilièno je drag. 0sim | toga, meni nije ništa uèinio.
{23602}{23701}Upucavao mi se. - Molim? | - Upucavao mi se!
{23706}{23789}Ta životinja mi se udvarala! | - Kada?
{23805}{23878}Ranije jutros, prije | nego što si došao.
{23884}{23967}Rekao je da se uopæe niste | upoznali. - Kome æeš vjerovati?
{23973}{24034}Plaæenom ubojici ili svojoj | ženi? - Moram odgovoriti?
{24040}{24149}Nicholase! - Dobro, dobro. | Recimo da ti se udvarao.
{24160}{24237}5 godina je bio u zatvoru. | Oèajan je. Spavao bi i sa
{24244}{24338}strojem za mljevenje mesa. | - Svinjo! Gadiš mi se!
{24344}{24433}Pokraj nas živi poznati | ubojica koji nas može pobiti
{24440}{24516}na spavanju, a ti neæeš ni | prstom mrdnuti?! - Toèno!
{24521}{24617}Neæu ni prstom mrdnuti. | Zato što je ovo ludo!
{24901}{24970}Uèini mi to...
{24990}{25077}i dat æu ti razvod.
{25084}{25172}Ako mi to ne uèiniš, | kunem se da æu ti tako
{25177}{25255}zagorèati život da æe ti | zadnjih nekoliko godina
{25261}{25336}izgledati kao ugodno | krstarenje.
{25342}{25442}Veæ sam ti uzela avionsku | kartu. Polaziš sutra u 9.
{25448}{25515}Bolje se poèni | pakirati.
{25735}{25837}Kad se vraæaš? Moram | pomaknuti sve tvoje preglede.
{25843}{25914}Ne vjerujem da æu ostati | duže od par dana. - Ideš sam?
{25920}{26012}Da. - Super. Možeš mi uèiniti | ogromnu uslugu dok si tamo?
{26017}{26086}Izaði i poševi nekog!
{26092}{26130}Jill!
{26137}{26203}Zovi me èim se vratiš. Još | bolje, zovi me odmah poslije.
{26208}{26287}Zovi me u tijekom ševe. | Želim sve detalje.
{26492}{26566}Ne oèekuj previše. Nisam | siguran hoæu li moæi stupiti
{26571}{26645}u kontakt s tim ljudima. | Gogolakovi nemaju reklamni
{26652}{26739}broj u novinama. - Znam da | æeš uèiniti sve što možeš.
{26848}{26978}Što je ovo? - Sretno, dragi. | I brzo se vrati.
{27074}{27149}Ima li u avionu | vreæica za povraæanje?
{27787}{27896}Ti si Jimmy Tudeski, zar ne? | Jimmy Tulipan?
{27933}{28020}Ne brini. Tvoja tajna je | sigurna uz mene, macane.
{28023}{28121}Ali nikad neæeš povjerovati | što moj dragi muž smjera.
{28491}{28561}Vratio si se u Chicago? | Sjajno.
{28567}{28677}Naðimo se u Ekins Oyster | baru za 45 minuta.
{28791}{28868}Dave, kažem ti, nemaš razloga | za brigu. - Kako da ne brinem?
{28875}{28957}Kažeš da si došao u Chicago | otkucati Tudeskija Gogolaku.
{28962}{29036}Neæu ga otkucati. Misliš da | sam sklon samoubojstvu?
{29041}{29117}Pa, zubar jesi.
{29128}{29235}Nikoga neæu otkucati. Došao | sam samo da se riješim Sophie.
{29240}{29365}Imam rok. Doæi æu u tvoju | hotelsku sobu èim završim.
{29371}{29436}U meðuvremenu, obeæaj mi da | neæeš napraviti neku glupost.
{29443}{29521}Zašto to govoriš? - Pa oženio | si Sophie, zar ne?
{29541}{29604}Znaèi, ja plaæam raèun?
{29958}{30060}Oprostite, sigurno sam u | krivoj... - Koju sobu tražiš?
{30082}{30205}519. - Na pravom si mjestu. | Ti si Nicholas Oseransky?
{30261}{30347}Tko ste vi? - Èujemo da imaš | informacije o prebivalištu
{30356}{30423}Jimmyja Tulipana.
{30429}{30498}Tko vam je to rekao? Dave? | - Tko je Dave? - Zašto vam
{30505}{30607}je rekao? - Pusti Davea. | Što se nas tièe, nema Davea.
{30620}{30692}Dave ne postoji.
{30710}{30819}Odgovori mi na pitanje. | Imaš li ili nemaš...
{30847}{30952}informacije o prebivalištu | Jimmyja Tulipana?
{30959}{31047}Ne znam o èemu govoriš, | èovjeèe. - Zbilja?
{31125}{31207}Sigurno sam pogrešno | obaviješten.
{31214}{31296}Isprièavam se. | - U redu je.
{31404}{31464}Pokušajmo još jednom.
{31471}{31556}Èujemo da imaš informaciju | o prebivalištu...
{31561}{31656}Tko vam je to rekao? - Ne | zamaraj se nebitnim stvarima.
{31661}{31788}Važno je da mi znamo da ti | znaš gdje je Jimmy Tudeski.
{31798}{31863}Slušaj, zbilja nemam...
{31892}{31986}Neæeš zvati pomoæ? | - Bi li mi to pomoglo? - Ne.
{31997}{32121}Tko si ti? - Franklin | Figueroa. Ili Frankie Figs.
{32135}{32226}Radim za Jannija Gogolaka. | - Bože moj...
{32280}{32359}Gdje je Jimmy? - Slušaj, | kunem se...
{32376}{32473}Vjeruj mi, ne želiš cijelu | noæ plesati sa mnom zbog
{32483}{32582}hulje kakva je Jimmy T. | Poštedi se bola.
{32622}{32714}Zbilja nemam... | Ne, ne...
{32743}{32848}Možda znam gdje je on. | - Dobro. Ali nemoj reæi meni.
{32854}{32920}Idemo da to kažeš Janniju. | - Dobro. Smijem li prvo
{32926}{33016}propišati malo krvi? | - Samo izvoli. - Hvala.
{33804}{33859}Moj otac...
{33877}{33940}je veliki èovjek.
{33990}{34064}Èovjek od vizije...
{34108}{34188}i karaktera.
{34195}{34287}Èovjek koji je branio | svoja uvjerenja.
{34326}{34401}Za razliku od onog štakora, | gada...
{34415}{34481}i govna!
{34488}{34560}Tudeskija.
{34602}{34675}Možeš li ti...
{34721}{34831}zamoliti Cynthiju da nam se | pridruži, molim te?
{34919}{35031}Hoæeš piæe? - Ne, hvala. | - Popij nešto. - Viski sa sodom.
{35103}{35204}Želim da razumiješ. Frankie | mi je rekao da imaš problema
{35211}{35317}sa svojom savješæu. - Da, | jer ovo nije bila moja ideja.
{35322}{35399}Misliš da je bila moja? | Nije.
{35406}{35512}Da je po mome, moj otac | bi još upravljao svime,
{35518}{35582}a ja bih bio negdje, | recimo...
{35590}{35643}Ne znam...
{35799}{35903}Na Arubi. - U stvari, Aruba | nije ništa naroèito.
{35945}{36024}Molim? - Vama bi se | možda svidjela.
{36030}{36084}Tamo sam bio na medenom | mjesecu. Valjda mi se zato
{36090}{36141}nije dopalo.
{36148}{36248}Upamti, kad prièamo o | Tudeskiju, ne prièamo
{36256}{36368}o ljudskom biæu. | Nego o glodavcu...
{36411}{36509}Govorimo o... štetoèini!
{36753}{36828}Gdje sam stao? | - Mislim, kod štetoèine.
{36834}{36919}Govorimo o nekome... | jebeš to!
{36924}{37084}O neèemu što ne zaslužuje | da udiše... zrak.
{37128}{37209}Janni, opet prièaš o sebi?
{37227}{37349}G. Oseransky... | ovo je Cynthija.
{37467}{37547}Jimmyjeva žena.
{37734}{37822}Cynthija, izgleda da | gospodin... - Doktor.
{37845}{37979}Molim? - Dr. Oseransky. | On je zubar. - Nije bitno.
{37988}{38109}Izgleda da naš prijatelj zubar | zna gdje je Jimmy.
{38154}{38218}Došao si uzeti novac | za ugovor? - Ne!
{38224}{38285}Janni, samo da znaš, pošto | sam ja našao ovog tipa,
{38292}{38363}ja ga hoæu. Ugovor je moj. | - Samo dok ja sudjelujem
{38367}{38430}u ubijanju. - Sve dok | dobijem punu cijenu.
{38436}{38546}Želim vidjeti tog štakora | beskièmenjaka kako moli.
{38556}{38628}Novac nije važan.
{38635}{38758}Sad sam sve èula. Ne vjeruj | mu. Ovaj bi te ubio za 25 c.
{38811}{38880}G. Oseransky...
{38886}{38962}Frankie æe vas otpratiti | natrag u Kanadu.
{38968}{39040}Odvest æete ga do èovjeka za | kojeg vjerujete da je
{39048}{39126}Jimmy Tudeski. - Ali... | - Frankie, javit æeš mi?
{39132}{39193}Onda u redu.
{39200}{39273}G. Gogolak...
{39292}{39386}Moja supruga bi mi još više | zagorèala život da barem
{39392}{39463}ne tražim...
{39534}{39644}Postoji li ikakav honorar za | nalazaèa?
{39742}{39827}Honorar za nalazaèa?
{40198}{40253}Znaš što?
{40260}{40354}Reci svojoj ženi da æemo | nešto smisliti.
{40541}{40652}Cynthija, ne žuri se. | Trebamo malo poprièati.
{40791}{40878}Zvat æu te ujutro. | Kreæemo rano.
{40951}{41065}Doktore, nemoj pomišljati na | neku glupost poput bježanja.
{41070}{41126}Neæu.
{41158}{41238}Što si uèinio? S kim si | razgovarao? - 0 èemu prièaš?
{41242}{41304}Znaš tipa po imenu Frankie | Figs? - Èuo sam za njega.
{41309}{41383}Kad sam se vratio s ruèka, | bio je u mojoj sobi!
{41390}{41457}Frankie Figs je bio u tvojoj | sobi?! - Da. Odnekud je saznao
{41463}{41529}da znam gdje je Jimmy. | - Što je uèinio?
{41534}{41587}Nakon što mi je prvo malo | protresao bubrege,
{41592}{41662}odveo me kod Janija | Gogolaka! - Reci da se šališ.
{41666}{41730}Kome si rekao? Želim toèno | znati kome si rekao!
{41736}{41831}Nikome, kunem se! | - Kako onda...
{41853}{41927}Što da radim?
{41934}{42015}Èujemo se. Moram prekinuti.
{42466}{42540}Posluga u sobu. - Ovdje | dr. 0seransky iz sobe 519.
{42545}{42631}Trebat æe mi veæa | boca viskija.
{42926}{42998}Da? - Ja sam. | - Oze!
{43005}{43088}Kako si? - Ne znam što æu. | Uèinio sam nešto strašno.
{43093}{43164}Što može biti tako strašno? | - Moraš otiæi iz Kanade.
{43172}{43264}Samo bježi odatle! | U Chicagu sam. - Èuo sam.
{43295}{43381}Jesi li se veæ vidio | sa Jannijem?
{43395}{43559}Otkud znaš? - Opusti se. | Sve znam. Ne brini.
{43566}{43649}Sve æu ti objasniti | kad se vratiš, u redu?
{43656}{43711}U meðuvremenu...
{43716}{43775}lijepo se provedi kad si | veæ tamo? Proživi malo.
{43783}{43873}Ali... što... - Prièat | æemo kad se vratiš.
{43879}{43923}Ako ti tako kažeš...
{44748}{44812}Hoæeš me pozvati da uðem | ili æu morati siæi dolje
{44819}{44873}i reci Jannijevim momcima | da si nepristojan?
{44879}{44971}Jannijevi momci su dolje? | Da, uði.
{45140}{45223}Volim muškarce koji se | znaju ponašati.
{45320}{45384}Janni me poslao da vidim | jesi li iskren. On igra
{45389}{45450}na povjerenje.
{45455}{45547}Da ili ne? - Da ili ne...
{45567}{45655}znaš gdje je moj | zalutali muž?
{45662}{45716}Gðo Tudeski... - Zovi me | Cynthija. Zašto biti formalan
{45722}{45765}prema ženi koja æe zbog | tebe postati udovica?
{45772}{45818}Ne razumiješ... - Što se tu | ne može razumjeti?
{45825}{45889}Želiš svoj dio love, zar ne? | Samo se pitam zašto sam
{45896}{45971}ne obaviš posao? - Zašto ja... | - zašto ne ubiješ Jimmyja
{45977}{46072}i pokupiš nagradu? | - Što je? Nemaš želudac za to?
{46119}{46208}Ili ti je problem | malo niže?
{46263}{46324}Jesi li nedavno povraæao? | - Minutu prije. Baš sam
{46330}{46414}htio oprati zube. | - Prièekat æu. - Dobro.
{46420}{46511}Gðo Tudeski, Cynthia, | to nije bila moja ideja.
{46517}{46591}Sluèajno si prešao 1600 km | da otkucaš Jimmyja Janniju.
{46598}{46686}Ne! To nije bila moja ideja. | To je isplanirala moja žena.
{46691}{46781}Ona je htjela da doðem u | Chicago i otkucam Jimmyja.
{46794}{46878}Možda bi za sve bilo najbolje | da Janniju kažeš da sam lud,
{46885}{46986}da sam munjara, kemijski | neuravnotežen, udaren!
{47015}{47102}Možda bi to bilo najbolje. | Jer...
{47287}{47372}Samo mu kaži da sam se | ponašao ovako.
{47377}{47458}Ali ti znaš gdje je Jimmy, | zar ne?
{47502}{47589}Gðo Tudeski, ne želim da | itko umre.
{47596}{47677}Govorim iskreno.
{47745}{47834}Što vi želite? | - Što ja želim?
{47901}{47993}Samo želim da svemu | ovome doðe kraj.
{48153}{48235}Toliko se bojim.
{48298}{48393}Posluga. Naruèio sam viski | prije povraæanja.
{48454}{48538}Izvolite. | - Hvala.
{48615}{48708}Što biste rekli da vas | ponudim piæem?
{48715}{48807}Rekla bih: Bez leda, bez vode | i u visokoj èaši.
{48814}{48866}Što da kažem? Bila sam | mlada.
{48873}{48932}Jimmy se razlikovao od svih | muškaraca koje sam upoznala.
{48937}{49004}Da, on je prvi ubojica | kojeg poznajem.
{49009}{49103}Takvih nije bilo u privatnom | klubu moga oca. Loš muž.
{49110}{49219}Stalno me je varao. | - Zašto se nisi... - Razvela?
{49228}{49311}Jimmy ne vjeruje u razvod. | Smatra da je to grijeh.
{49372}{49442}Znam, plaæeni ubojica koji | ima moralne vrijednosti.
{49446}{49535}Sad kad je izašao iz zatvora, | hoæete li opet biti zajedno?
{49540}{49626}Pod uvjetom da ga Frankie | i Janni prvo ne ubiju?
{49636}{49732}Ne. Izmeðu mene i Jimmyja | je gotovo.
{49738}{49810}I kad bih htjela pokušati još | jednom, a ne želim,
{49817}{49923}uvijek bi postojalo ono | drugo izmeðu nas. - Što to?
{49970}{50053}Èinjenica da me | želi ubiti. - Zašto?
{50085}{50167}Ti si dragi momak. | Zbog novca.
{50172}{50261}Bogata si? - Zbog novca koji | nam je Laszlo Gogolak dao
{50265}{50337}kao svadbeni dar. Samo što | to nije bio svadbeni dar.
{50343}{50399}Laszlo je samo privremeno | parkirao novac kod nas
{50404}{50512}da ga sakrije od federalaca. | - Koliko? - 10 milijuna dolara.
{50537}{50620}To je vraško parkiralište. | - Do novca se moglo samo ako
{50625}{50715}Jimmy, Janni i ja potpišemo | zajedno.
{50720}{50804}Ako nemaš tri potpisa, | trebaju ti dva potpisa...
{50815}{50879}i potvrda o smrti.
{50886}{50959}Ili jedan potpis i... | - Dvije potvrde o smrti.
{50965}{51037}Zato te Jimmy želi ubiti. | Ako ubije tebe... - I Jannija.
{51048}{51146}Onda æe on dobiti novac. | Sve. - Zgoditak do kraja.
{51231}{51319}Zašto mu nisi rekla da | ne želiš taj novac?
{51351}{51443}Rekla sam mu. Ne želim ni | novèiæ. Ali on zna da se
{51448}{51513}želim razvesti, a on ne | vjeruje u razvode.
{51519}{51602}Ali ubojstva su mu u redu. | - To mu je posao.
{51609}{51676}Da sam ja u pitanju 10 mil. | Ne bi bilo dovoljno.
{51682}{51763}Koliko bi tebi trebalo da | bi ubio svoju ženu?
{51770}{51835}Govorim o tebi. - 0nda mene. | Koja bi bila cijena?
{51842}{51913}O tome i govorim. Mislim da | si nešto najljepše što sam
{51918}{52007}ikad vidio. Ne mogu vjerovati | da sam do rekao na glas.
{52011}{52099}To progovara viski. | - Ne, nego ja.
{52169}{52250}Proteklih 7 godina života sam | sjedio i èekao da se nešto
{52257}{52336}dogodi. Nisam znao što.
{52374}{52480}Dok ti nisi ušla u sobu u | kuæi Jannija Gogolaka.
{52530}{52613}Oprosti. Neugodno ti je. | - Moram krenuti. - Nemoj.
{52621}{52677}Molim te.
{52699}{52770}Ti si dobar èovjek. | Bolje da krenem.
{52826}{52891}Idemo.
{53122}{53223}Noæ je tek poèela. Žuri | li vam se natrag, deèki?
{53337}{53425}Doista si mislio to | što si rekao?
{53486}{53591}Imam vremena do ponoæi. | U meðuvremenu...
{53856}{53939}Obeæaj mi nešto. - Sve. | - Nemoj žuriti.
{53945}{54029}5 godina nisam vodila ljubav. | - Nisam ni ja.
{54042}{54117}U braku sam.
{54424}{54495}Skoro je vrijeme.
{54506}{54649}Opet? Jeo si ostrige | za ruèak? - U stvari, jesam.
{54777}{54882}Jimmy zna da sam tu. | - Tu sa mnom?! - Tu u Chicagu.
{54887}{54949}Da sam razgovarao s | Jannijem.
{54954}{55027}Kako? Kako je | saznao?
{55038}{55120}Jer sam mu ja rekao. | - Što?! - Ionako je veæ znao.
{55127}{55183}Kako? - Pretpostavljam | preko moje drage žene.
{55190}{55250}Ona želi da te netko ubije? | - Izgleda. To je jedino što
{55256}{55351}mi pada na pamet. Ali kad sam | razgovarao sa Jimmyjem...
{55372}{55445}nije zvuèao uznemireno! | - I ne bi. Bio bi ti najbolji
{55452}{55531}prijatelj sve do trenutka | kad...
{55552}{55620}On æe me ubiti, zar ne?
{55627}{55702}A onda, kad to uèini, | ti æeš biti sljedeæa.
{55708}{55781}To neæu dozvoliti. Neæu | dopustiti da te Jimmy ubije.
{55786}{55847}Odvest æu Frankija u Kanadu | i dovesti ga kod Jimmyja.
{55852}{55917}Da Frankie ubije njega? | - Da postoji neki drugi naèin.
{55923}{56019}Bolje Jimmy nego ti. - Nisi | shvatio? Svakako sam mrtva.
{56029}{56155}Zašto? - Èim Jimmy bude mrtav, | zašto bi me Janni poštedio?
{56160}{56259}Ubio bi i mene... - Da može | pokupiti svih 10 milijuna!
{56344}{56410}Neæu to dopustiti.
{56415}{56513}Kunem se da neæu dopustiti | da te netko ubije!
{56523}{56592}U ovim okolnostima, mislim | da je to nešto najromantiènije
{56597}{56675}što sam ikad èula. | - Hvala.
{57222}{57348}Što?! Rekao si Jimmyju? | Zašto si to uèinio, do vraga?
{57354}{57431}Loše sam se osjeæao. | Drag mi je. Bio mi je drag.
{57437}{57502}Više ti nije drag? - Pomalo | je teško biti prijatelj
{57507}{57562}s nekim tko te želi ubiti. | - Da si mene prodao Janniju
{57568}{57657}i zatim mi to rekao, | i ja bih te koknuo. - Znam.
{57716}{57800}Mogu ti zatvoriti taj razmak. | - Zbilja? - Da. Za sekundu.
{57804}{57864}Šališ se? | - Nema problema.
{57871}{57967}Jesi li uèinio ono što sam | ti rekla? - Neæu ti odgovoriti.
{57974}{58087}Jesi! Jasno mi je da si se | seksao! - Veliki auto, molim.
{58096}{58174}Tko je ona? Želim znati sve! | - Moram iæi. Ako je nešto hitno
{58178}{58248}ponio sam dojavljivaè. | - Dobro, budi takav.
{58252}{58302}Ne treba mi osiguranje. | - Uzgred, zvala je kuja iz
{58308}{58364}pakla i rekla da ona i njena | mama idu na slapove Nijagare.
{58369}{58444}Vjerojatno da osigura alibi. | Moram iæi.
{58451}{58549}Poði sa mnom do hotela. | Osim ako ne bi radije otišao
{58558}{58654}kuæi usred bijela dana, | a Jimmy ti je prvi susjed.
{58661}{58734}Idem s tobom.
{59516}{59578}Frankie Figs.
{59601}{59675}Jimmy T.
{59946}{60017}Što se dogaða?
{60024}{60087}Kako je, Frankie? | Dobro došao u Montreal.
{60109}{60182}Drago mi | je što te vidim.
{60187}{60261}Oze, izgledaš zabrinuto. | Zar ne izgleda zabrinuto?
{60268}{60321}Izgleda. | - Opusti se.
{60327}{60410}Frankie mi je rekao | kako si se dobro držao.
{60446}{60531}Promijeni gaæe. Izlazimo.
{61121}{61233}Zadržat æu Colu i pomfrit, | ali vraæam ovaj hamburger.
{61273}{61364}Ako staviš majonezu u njega, | doæi æu ti u kuæu, išèupati
{61368}{61441}ti noge, zapalit æu ti kuæu | i gledati te kako pužeš
{61446}{61544}krvavim batrljcima iz kuæe. | U redu? Èuješ?
{61552}{61644}Meni je dobro. | - Dobro ti je?
{61657}{61734}Nešto æu ti reæi, Oze. | Nije ti dobro. Znaš da tvoja
{61741}{61796}želi da umreš?
{61803}{61890}Toliko sam i sam shvatio. | - Želim da znaš, jer ja nisam
{61897}{61992}prvi kome se obratila. | - Prvi? - Ubojica. - Ima ih još?
{61996}{62091}Bar još jedan. To je propalo, | pa se obratila meni.
{62131}{62211}Što si joj rekao?
{62302}{62392}Misliš, jesam li prihvatio | ugovor?
{62564}{62652}Nisam prihvatio ugovor. | - Koliko ti je ponudila?
{62657}{62714}10.000.
{62765}{62882}Nije ni èudo da si je odbio. | - Ali si je odbio? Lako sam
{62889}{62973}otišao k Janniju? - Nisi išao | k Janniju. Jimmy me je
{62978}{63040}poslao da te odvedem.
{63045}{63114}Znam da Frankie zna biti | vrlo uvjerljiv. - Uzgred,
{63121}{63183}kako ti ide mokrenje? | - Dobro, hvala.
{63191}{63274}Zašto me Frankie vodio k | Janniju? - Da mu kažeš
{63279}{63373}gdje sam. - Da on doðe ovamo | i ti ubiješ njega? - Toèno.
{63379}{63460}Uzgred, rado æu ti srediti | ženu. - Srediti mi ženu?!
{63466}{63546}Koknuti je. - Koknuti? | - Ukokati. - Ukokati?
{63552}{63619}Mislio sam da misliš na...
{63624}{63741}Rekla mi je da si joj | se upucavao.
{63747}{63800}Smiješno.
{63807}{63890}Zašto je to smiješno?
{63919}{64046}Nisam ti to namjeravao reæi, | ali ona se upucavala meni.
{64074}{64141}I? - Oze.
{64146}{64278}Mi smo prijatelji. Ne seksa | se sa ženom od prijatelja.
{64327}{64378}Osim toga...
{64384}{64449}tvoja žena mi i nije baš | jako privlaèna.
{64456}{64520}Tek si izašao iz zatvora? | - Da. - 5 godina si bio
{64527}{64598}u zatvoru i moja žena ti | nije privlaèna?
{64604}{64685}Ona nije dobra osoba.
{64702}{64802}Ubio si 17 ljudi i misliš | da moja žena nije dobra osoba?
{64850}{64956}Nije važno koliko sam | ljudi ubio.
{64961}{65077}Važno je kako se slažem s | ljudima koji su još živi.
{65232}{65321}Pojest æeš ovo? | - Samo izvoli!
{65933}{66000}Mislim da smo dovoljno | èekali. Nazovi Jannija.
{66007}{66078}Što prije doðe, to bolje. | - Kad ubiješ Jannija,
{66089}{66175}vratit æeš se u Chicago? | - Ne, završio sam s Chicagom.
{66181}{66270}A tvoja žena? Bit æete | opet zajedno?
{66326}{66436}Ubit æeš i nju? - Za mnogo | više od 10.000 dolara.
{66442}{66544}Ne smiješ to uèiniti! | - Zašto? - Žena ti je!
{66549}{66627}Bio si u pravu u glede njega. | Nevjerojatno je sladak.
{66632}{66699}Ima onakvu ženu i još | vjeruje u braèni zavjet.
{66704}{66782}I ja. 0sobito ono, | dok nas smrt ne rastavi.
{66788}{66861}Moj biper. | Moram u ordinaciju.
{66885}{66995}Braèni zavjet ili ne, | bolje èuvaj leða.
{67000}{67115}Tvoja žena još traži | ubojicu. Sretno.
{67761}{67867}G. Tourette, mislim da | æemo morati izvaditi zub.
{68191}{68280}Oze, što je?
{68330}{68417}Ne, 0ze! Nemoj!
{68485}{68545}Prijateljica sam ti. | Prièaj sa mnom.
{68551}{68656}Moram razgovarati s nekim, | jer æu... - Samo polako!
{68786}{68833}Dobro.
{68839}{68894}Kao prvo, upravo sam saznao | da moja žena traži nekoga
{68901}{68981}tko æe me ubiti. | - Tko ti rekao? - Prijatelj.
{68988}{69055}Netko koga znam? - U stvari, | moj prvi susjed.
{69060}{69122}Evo što je smiješno. | I on je plaæeni ubojica!
{69129}{69222}Kako se zove? - Jimmy. | Jimmy Tudeski.
{69236}{69296}Jimmy Tulipan?!
{69304}{69380}Jimmy Tulipan živi kraj | tebe i ti ga poznaješ?
{69387}{69465}Oze, možeš nas upoznati? | - Jill...
{69483}{69557}On je profesionalni ubojica. | - Ne razumiješ. Godinama ga
{69563}{69629}želim upoznati! Molim te. | Hajde!
{69742}{69812}Brzo, hajde!
{69902}{69992}Što je ovo, 0ze? - Ne znam. | - To ste zbilja vi.
{69999}{70070}G. Tudeski, ne razumijete. | Ja sam vam jedna od najveæih
{70075}{70141}obožavateljki. Pratim vašu | karijeru od malih nogu.
{70147}{70238}Vi ste razlog što se pokušavam | ubaciti u taj posao.
{70244}{70323}A koji bi to posao bio? | - Ubijanje po ugovoru.
{70330}{70400}To želim raditi. Ako mi možete | posvetiti minutu, znam da bih
{70407}{70502}od vas mogla tako mnogo | nauèiti.
{70521}{70584}Uði.
{70647}{70728}I ti.
{70902}{70985}Što je ovo? - Poznaješ ovu | djevojku? - Moja asistentica.
{70990}{71060}Znao si da je plaæeni ubojica. | - U stvari, još sam nevina.
{71065}{71131}Još nisam nikoga ubila. | Mislim, profesionalno.
{71137}{71201}Oz mi je trebao biti prva | žrtva. - Molim?! - Unajmila me
{71206}{71251}je njegova žena. - Što sam | ti rekao? - To si bila ti?
{71259}{71314}Trebalo je izgledati kao | nesreæa. Zato sam poèela
{71319}{71363}raditi za njega, da mu | upoznam navike. - Dobro.
{71368}{71427}Da ga upoznam. -Mudro. | - Hvala. Ali kad sam ga
{71434}{71491}upoznala, postao mi je drag.
{71495}{71589}Prva pogreška. - Znam! | - Zbližiš se, ali ne previše.
{71628}{71714}Natoèi si martini. | - 16 je sati!
{71865}{71961}Ne predbacuj si. Pred tobom | je cijela karijera.
{71967}{72054}Sjeæam se kad sam ja poèinjao. | Nisam uèinio mnogo.
{72059}{72123}Obavio sam par stvari, | skupio nešto novaca.
{72128}{72217}Radio sam nešto što mi | se sviðalo. 0nda me vrbovao
{72220}{72334}Laszlo Gogolak. Prvo je htio | da mu koknem malog roðaka.
{72340}{72429}Je li to incident sa | Stanleyem Posilanskym?
{72434}{72520}Laszlo nije htio da izgleda | kao naruèeno ubojstvo.
{72524}{72605}Morao sam se približiti | Stanleyu koji je bio zbilja
{72611}{72699}šarmantan, sladak, smiješan | mali tip s uvrnutim smislom
{72705}{72781}za humor. | Nasmijavao me je.
{72786}{72853}Zbilja mi je bio drag kao | osoba, razumiješ?
{72860}{72928}Previše si se zbližio.
{73062}{73139}Da, previše sam se zbližio.
{73146}{73214}Kad je došao trenutak | istine...
{73220}{73304}Gušenje. - Njega? | - Mene. Poèeo sam se gušiti.
{73308}{73376}Nisam mogao.
{73382}{73459}Rekao sam mu da sam ga | došao ubiti. Zamisli to.
{73464}{73527}Rekao sam "Bježi, Stanley, | bježi. Idi, sakrij se".
{73560}{73642}Rukovali smo se, rastali | se kao prijatelji.
{73647}{73752}Kad sam se okrenuo, gad | mi je pucao u leða.
{73767}{73854}Metak je izašao ovdje.
{73861}{73913}Što si uèinio?
{73918}{73999}Poslije toga mi Stanley | više nije bio tako drag.
{74004}{74090}Zbilja je dugo umirao.
{74124}{74253}Ovaj ožiljak mi je podsjetnik. | Nikad se ne zbližavaj previše.
{74522}{74598}Oprostite.
{74627}{74688}Oprostite!
{74695}{74773}Ne želim vas prekidati, | ali htjela si me ubiti?!
{74778}{74847}Takav je bio plan?!
{74882}{74964}Što radiš veèeras? | - Nemam planova.
{74976}{75070}Hoæeš nam pomoæi? | Meni i Frankie Figsu?
{75104}{75205}Nudiš mi posao? | - Samo ako te zanima.
{75220}{75320}Bila bi mi èast. | Poput ostvarenja snova!
{75327}{75387}Tko je meta?
{75393}{75485}Janni Gogo. | - Janni Gogo?
{75587}{75654}Pogledaj mi ruku. | Sva sam se naježila.
{75701}{75797}Telefon me uplašio. | Opet zvoni.
{75827}{75902}Što je tebi? | - Ne znam.
{75911}{75978}Da? Frankie.
{76057}{76120}Dobro, odlièno. | Vidimo se uskoro.
{76125}{76177}Dobra vijest? - 0dlièna.
{76183}{76291}Izgleda da dolazi Janni Gogo | i dovest æe i moju ženu.
{76297}{76370}Tvoju ženu?! | - Zašto?
{76379}{76448}Janni je misli srediti | nakon što sredi mene.
{76455}{76547}Što æeš raditi? Pokušat æeš | je spasiti? - Ne. I ja želim
{76553}{76633}njenu smrt. - Zbilja? | - Da. - Smeta ti to?
{76639}{76716}Zašto bi? Ni ne poznajem je. | - Nevjerojatni ste!
{76723}{76823}Mirno govorite o ubojstvu | prekrasne, nevine žene
{76828}{76903}èiji je jedini zloèin, | po meni, što je udata za tebe!
{76908}{76975}Neæu to više slušati!
{76981}{77045}Znate što æu uèiniti?
{77059}{77114}Ja æu...
{77119}{77186}Ja æu otiæi!
{77204}{77282}Ja æu... | Klizi li ovo?
{78141}{78221}Javi se.
{78283}{78363}To je moj telefon, | hvala.
{78410}{78474}Halo?
{78508}{78597}Tko je bio? - Prekinuo je. | - Oèekuješ poziv?
{78603}{78703}Objasni mi zašto se to | tebe tièe? - Ponesi joj torbu.
{78710}{78790}Avion èeka, a ja ne.
{79676}{79733}Oh, Bože!
{79897}{79992}Ne sviða ti se Walther? | - Nosi ono što ti odgovara.
{79997}{80097}Njega koristi James Bond. | - Zbilja? - Da. - Volim amerièke.
{80457}{80533}Postoji li naèin da te | sprijeèim da to uèiniš?
{80539}{80612}Oze, smiri se. Obeæavam ti | da nitko neæe znati da si
{80619}{80695}imao ikakve veze s ovim. | - Nije u tome stvar. - Nego?
{80700}{80764}Ipak æeš ubiti | svoju ženu!
{80833}{80888}Da!
{80895}{80994}Imam jako dobar razlog da | ubijem svoju ženu.
{81000}{81077}10 milijuna dobrih razloga | da je ubijem.
{81084}{81156}Dobro, a kad bih ti rekao ne.
{81161}{81248}Kad bih rekao da ti | to neæu dopustiti?
{81357}{81442}Ti si najplemenitiji tip | kojeg sam ikad upoznao.
{81448}{81520}Sad ti je jasno zašto ga nisam | mogla ubiti? - Volim ga.
{81564}{81664}Doði. Opusti se. Sjedi | na svoju omiljenu stolicu.
{81669}{81744}Popij malo martinija.
{81754}{81855}Èuj, ovo veèeras æe se | dogoditi htio ti to ili ne.
{81865}{81957}I ti æeš pomoæi. - Ja?! | Pomoæi? - Da, ti æeš pomoæi.
{81967}{82039}Otiæi æeš s Frankijem da | doèekate Jannijev avion.
{82045}{82115}Ako ne budeš tamo, Janni æe | æe postati sumnjièav,
{82122}{82189}vratit æe se u avion i otiæi | natrag za Chicago. To neæemo.
{82256}{82335}Tako æe biti, u redu?
{82361}{82421}Kažem ti ovo kao prijatelj.
{82426}{82531}Ako ovo zezneš, | mrzio bih...
{82604}{82694}Doista bih mrzio da te | moram ubiti.
{82700}{82771}Mrzio bih to. Mrzio bih to | više nego što mrzim majonezu.
{82777}{82842}A znaš koliko mrzim majonezu. | - Znam. - Vjeruj mi, i ti želiš
{82849}{82912}da Janni Gogolak umre. | - Ne! Tu griješiš.
{82919}{83007}Ne želim da itko umre. | - Ako se mi ne potrudimo da
{83012}{83061}umre Janni, on æe se | potruditi da umreš ti.
{83068}{83124}Gogolakovi ne vole za sobom | ostavljati svjedoke.
{83129}{83238}K vragu, Jimmy, | zašto si se baš tu doselio?!
{83248}{83367}Oze, znaš kakvo je zemljište | u vrtu? Tu sam tek dva dana,
{83372}{83432}a veæ mi nièe | rajèica... - 0h, Bože moj!
{83696}{83766}Zašto si stala? - Uèinit æeš | to veèeras? - Veèeras,
{83772}{83871}bilo kad! Idemo! | Ubaci u brzinu! - Za 10.000?
{83876}{83960}Èekaj, rekla si 15.000. | - Predomislila sam se.
{83967}{84059}Ali ako misliš da trebam | potražiti drugoga... - Ne!
{84087}{84211}Neka bude 12.500. | - To bih mogla preživjeti.
{84232}{84341}Samo da moj muž ne preživi! | - Neæe. 0beæavam.
{84379}{84436}Ti si sigurno... | - Jill St. Clair.
{84441}{84529}G. Figueroa, smijem li reæi | da je posao koji ste obavili
{84534}{84618}na K. Vincentu i na | R. Abrahamsu, oba su...
{84651}{84730}Prava remek djela. - Vidim | da si dobro napisala zadaæu.
{84737}{84821}Imam zbirku isjeèaka. | - Frankie! - Što ima?
{84826}{84906}Dušo, idi po 0za. Još jednom | æemo sve ponoviti.
{84913}{84997}Da budemo sigurni da | znamo što nam je raditi.
{85030}{85121}Slatka mala. - Definitivno | ima potencijala.
{85313}{85393}Vrijeme za rock & roll.
{86830}{86922}Imam isti ovakav auto. | - Zbilja? - Ne.
{87516}{87602}Dobro, da se nitko | nije pomakao.
{87643}{87731}Tišina svi!
{88250}{88332}Bože, ovo æe mi | se svidjeti.
{88357}{88463}I što sad? | - Èekat æemo dok...
{88516}{88601}Ne zaspi. - Dobro.
{89291}{89404}Lijepo sanjaj, Jimmy. | Poènimo.
{89951}{90016}Imamo društvo.
{90144}{90242}Netko poznat? | - Ozova žena i neki tip.
{90248}{90336}Vjerojatno tvoja zamjena. | Novi ubojica.
{90357}{90471}Sad ne možemo ništa. | Drži ih na oku. - Dobro.
{90478}{90538}Te hlaèe ti sjajno stoje.
{90545}{90633}Muž ti je loš èovjek? | - Nije.
{90640}{90727}U stvari, izgleda da ga | svi vole.
{90734}{90852}Možda to najviše mrzim | kod njega. - Dobro, ponovimo.
{90858}{90955}Zašto, do vraga? - Da budem | siguran da je sve u redu.
{90961}{91046}Želiš da umre na neki | odreðen naèin? - Briga me.
{91052}{91152}U inozemstvu sam, | kupujem haljinu za pokop.
{91200}{91289}Zubar, spusti rolete.
{91359}{91436}Još danas!
{91872}{91969}Bože. Zašto baš sad...
{91984}{92072}Ti si oženjen, zar ne? | - Da. - Ima li tvoja žena...
{92094}{92178}Ženske proizvode? Da, ima. | Tamo su. Pokazat æu ti.
{92299}{92422}Nemugo. - Nem... što? | - Nemoj dugo! - Razumijem.
{92458}{92534}Napravi buku, on æe ustati | iz kreveta da vidi u èemu
{92541}{92635}je problem i neka umre! | U redu? Razumiješ me?
{92638}{92715}Ono s umiranjem? - Onda malo | ispreturaj kuæu da izgleda
{92719}{92817}kao provala, pa se vrati u | auto i odjurit æemo natrag
{92823}{92940}na slapove Nijagare. - Gdje | æeš mi dati drugih 5.000?
{92946}{93005}Moja nas majka tamo | èeka s novcem.
{93011}{93085}Tvoja majka zna za ovo? | - Ona želi da se ovo dogodi
{93092}{93153}isto toliko koliko i ja.
{93160}{93251}A ja doista, doista želim | da se to dogodi.
{93278}{93339}Ubit æe te! - Ubit æe te! | - Što? - Što?
{93347}{93408}Èim Janni sredi Jimmyja, | ubit æe tebe. Zato sam došla
{93413}{93483}da te mogu upozoriti. | - To je tako...
{93550}{93625}Janni neæe nikoga ubiti. | Jimmy tamo èeka... - Jimmy?!
{93631}{93694}Jimmy i Frankie su... kako | se to kaže? - U dosluhu!
{93706}{93811}I ti si u dosluhu? - Morao | sam se praviti da jesam!
{93823}{93882}Imam plan.
{93929}{94033}Vrijeme je. Vas dvoje | ostanite tu.
{94267}{94347}Znaš ove ljude?
{94354}{94405}Ne.
{94412}{94471}Tko je to?
{94536}{94606}Je li to Janni Gogolak? | - Iz bande Gogolakovih.
{94612}{94704}Možda. Tip po imenu Jimmy | Tulipan živi odmah do nas.
{94710}{94796}Jimmy Tulipan?! Idu ga ubiti. | Ostani ovdje!
{95103}{95187}Tko je to? | - Ne znam.
{95192}{95265}Prekrasno mirišeš.
{96399}{96498}Bog. Momci, | tražite nekoga?
{96735}{96818}Bog, Janni. | Pazi glavu!
{97167}{97269}Ovo ušuljavanje u kuæu i | pokušaj da me ubijete...
{97300}{97383}zbilja ste dobri, momci. | Zbilja...
{97393}{97454}zbogom, Janni.
{98052}{98121}Što se dogaða? - 0z je upravo | pobjegao s tvojom ženom,
{98127}{98223}a Sophijin ubojica je ispred | kuæe. - Pobrinut æu se za to.
{98229}{98328}Trebala bi se obuæi. | Znaš što? 0stani tako.
{98339}{98432}Za 60 sekundi promoli glavu | kroz prozor.
{98526}{98611}Lijepo obavljeno. | - Hvala, Jimmy.
{98648}{98710}Brzo se vraæam.
{98717}{98826}Ne znam ništa ljepše od lijepe | gole žene koja drži pištolj.
{98831}{98909}A ti si lijepa na sve naèine, | zar ne?
{98915}{98994}Nemoj da ti nešto padne | na pamet.
{98999}{99087}Doista slatka guza.
{99227}{99305}Mogu ti pomoæi?
{99642}{99718}Sad se možeš obuæi.
{100074}{100156}Gdje da stavim ovo? | - Stavi tamo. - Dobro.
{100326}{100412}Zašto se Oz odvezao s mojom | ženom? - Mogu ga pozvati na
{100420}{100494}biper pa ga pitaj. | - Pozovi ga.
{100502}{100572}Pazi ovo sranje.
{100622}{100721}Možda nas neæe proganjati. | Možda æe nas pustiti da odemo.
{100727}{100798}Dobro, možda mogu razgovarati | s njim, urazumiti ga.
{100804}{100876}Prijatelji smo, zar ne? | - Tako je mislio i Lefkowitz.
{100881}{100950}Što se dogodilo Lefkowitzu?
{100960}{101044}Ne želim znati što se | dogodilo Lefkowitzu.
{101081}{101172}Tvoj biper. | - Znam.
{101221}{101288}Jimmy.
{101303}{101363}Jimmy, ja sam.
{101381}{101478}Oze, što si mislio kad si | tako odjurio sa Cynthijom?
{101483}{101531}Oprosti.
{101538}{101601}Ali ne mogu ti dopustiti | da je ubiješ. - Molim?
{101606}{101662}Kakve to ima veze s tobom?
{101667}{101740}Jimmy, ja sam zaljubljen | u nju.
{101748}{101820}Èuj, ja...
{101854}{101942}Što si rekao? | - Volim je.
{102001}{102097}Slušaj se! 0 kakvoj ljubavi | prièaš? Tek si je upoznao.
{102103}{102182}Kaže da voli Cynthiju. | - Nije valjda? - Ona je ta!
{102187}{102275}Ona koju je štepao u | Chicagu! - Ona koju je...
{102333}{102393}Moju ženu?
{102415}{102558}Štepao si moju ženu, Oze?! | - Ne bih koristio taj izraz.
{102580}{102651}Èekaj, da vidim jesam li | shvatio! 0tišao si u Chicago
{102658}{102757}i stupio u seksualnu vezu | s mojom ženom?! To mi prièaš?
{102773}{102861}To? - Jimmy, daj mi. | Smiri se. - Kunem se...
{102866}{102954}Malo se uzrujao. Uspio sam | uzrujati masovnog ubojicu.
{102961}{103000}Reci mi gdje si!
{103006}{103063}Saznaj gdje je! | Ne mièite se odatle!
{103070}{103162}To je suludo! - Oze, pastuše. | - Bit æe mrtav pastuh.
{103175}{103253}Reci Jimmyju da sam možda | smislio izjednaèeno rješenje.
{103256}{103369}Znam da imate višak mrtvaca. | - Jedan od njih je murjak.
{103394}{103468}Što kaže? | Što kaže!
{103486}{103559}Reci mu da se ne mièe | odatle! Odmah dolazim!
{103569}{103655}Zvuèi sjajno. Prièat æu s | deèkima pa æu te nazvati.
{103747}{103858}Jimmy, kad si posljednji put | bio kod zubara?
{103927}{104025}Zbilja si tako mislio? | To što si rekao.
{104031}{104143}O èemu? Da te volim? Naravno. | Èemu inaèe sve ovo?
{104161}{104276}Zbog seksa. Mislim, sjajnog | seksa. - Bilo je jako dobro.
{104372}{104454}Je li ovo za tebe | bilo samo to?
{104464}{104535}Nemoj me pogrešno shvatiti. | Jako mi se sviðaš.
{104541}{104616}To je sjajno èuti, ali imam | novost za tebe. Obièno ne
{104623}{104719}riskiram život zbog ljudi | kojima se samo sviðam.
{104795}{104869}Zbilja mi se sviðaš.
{104883}{104936}Ali...
{105001}{105061}Ali tko zna, možda...
{105068}{105159}Možda je osjeæaj koji imam | u dnu trbuha...
{105170}{105244}Možda je to ljubav.
{105254}{105340}Tvoj biper. | - Znam.
{105451}{105508}Da? - Ja sam.
{105526}{105626}Reæi æu ti nešto. Imaš | muda. - Tko bi to rekao.
{105631}{105712}Jill mi je rekla tvoju | ideju. I...
{105836}{105926}Mislim da vrijedi pokušati.
{105942}{106030}Jimmy, hvala ti. | - Samo da znaš...
{106045}{106129}da sam razoèaran, Oze.
{106134}{106233}Strašno si me razoèarao. | - Vjeruj mi, ti si posljednja
{106239}{106308}osoba na svijetu koju bih | želio razoèarati.
{106314}{106408}Ali sve što sam uèinio | bilo je zbog ljubavi.
{106421}{106487}Nije bitno.
{106518}{106591}Vidimo se u tvojoj ordinaciji. | - Dobro, daj mi sat vremena.
{106596}{106661}Ne zaboravi truplo.
{106875}{106965}G. Boulez, upamtite da morate | èistiti zubnim koncem.
{107049}{107142}Ostani na brodu. Uzmi ovo. | Ako se ne javim za 2 h, idi.
{107149}{107233}Nestani. Napusti | zemlju.
{107248}{107301}Oze...
{107314}{107381}Pazi se.
{107453}{107537}Ja sam g. Pažljivi.
{108412}{108497}Oz. Samo sam htio | provjeriti da si to ti.
{108504}{108554}Svi su unutra.
{108560}{108650}Uzgred, imaš grande jajca, | amigo.
{108812}{108898}Veliki i moæni Oz.
{108949}{109016}Poèni.
{111136}{111215}Za sada je dobro.
{111316}{111389}Jesi li gore? | - Da, imam ga.
{111460}{111529}Frankie, selotejp.
{111838}{111898}Uspjeli smo.
{111915}{111996}Mislim da je dobro.
{112025}{112099}Roštilj? - Roštilj.
{112463}{112555}Danas je ispala doista | lijepa veèer.
{112671}{112758}Odmah se vraæam.
{112827}{112907}Na što te ovo podsjeæa? | - Na starog Charliea.
{113127}{113175}Dobro.
{113183}{113239}U redu.
{113995}{114088}Doktore, ovi ljudi vas | žele vidjeti.
{114126}{114177}Isprièajte me.
{114184}{114238}Ovuda, gospodo.
{114279}{114350}Dr 0seransky, ja sam | narednik Buchanan.
{114357}{114470}Ovo je pozornik Morrissey. | - Što mogu uèiniti za vas?
{114565}{114658}Vi ste vlasnik smeðe Toyote | Corolle, registarskih tablica
{114667}{114770}zSJ959? - Jesam. | Ima li nekih problema?
{114775}{114867}Znate li gdje vam je vozilo? | - Posudio sam ga susjedu.
{114873}{114968}Otišao je na pecanje. | - Ima li vaš susjed ime?
{114989}{115062}Jimmy Jones.
{115092}{115177}Hoæete li nas odvesti do | njegovog mjesta boravka?
{115184}{115264}Vaš auto je pronaðen pored | silosa u staroj luci.
{115270}{115349}U njemu su bila dva trupla. | Izbio je požar.
{115356}{115430}O Bože! - Jaèina opeklina je | onemoguæila svaku normalnu
{115438}{115516}identifikaciju. Zato | su uzeti zubni otisci.
{115523}{115599}Po stomatološkim kartonima | smo uspjeli utvrditi da
{115606}{115671}su trupla pripadala Janniju | Peteru Gogolaku i
{115686}{115765}Jamesu Stefanu Tudeskiju. | - Obojica su bila velike
{115770}{115858}face u èikaškom | zloèinaèkom sindikatu.
{115864}{115950}I vi mislite da je taj James... | - Tudeski. - Je li to Jimmy
{115956}{116065}kojeg ja znam? - To | namjeravamo otkriti.
{116315}{116401}Zar to nije Hansonov auto?
{116408}{116488}Idi i pogledaj.
{116521}{116605}Tko je Hanson? - Jedan | od naših ljudi.
{116610}{116686}Bio je na tajnom zadatku. | Zabrinuti smo jer se jutros
{116690}{116771}nije javio.
{117153}{117232}Tvoja majka zna za ovo? | - Moja majka želi da se ovo
{117237}{117328}dogodi isto toliko koliko | i ja. A ja to jako želim.
{117470}{117553}Auto jest Hansonov, ali | njemu ni traga.
{117558}{117642}Ali sam našao kasetu.
{117891}{117992}Dr. 0seransky, možete li nam | reæi gdje vam je žena?
{117998}{118055}Moja žena? Na slapovima | Nijagare sa svojom majkom.
{118060}{118111}Zašto?
{118118}{118189}Dr. 0seransky, ne znam kako | da vam to kažem. Izgleda da
{118194}{118257}je vaša supruga nedavno | pokušala unajmiti plaæenog
{118263}{118344}ubojicu da vas ubije. | - Plaæenog ubojicu?
{118348}{118406}Oh, Bože!
{118566}{118649}Ovdje je zabranjeno pušenje.
{118794}{118875}Gdje je on, gðo Oseransky? | - Bolje da imate odgovor
{118881}{118956}na moja pitanja. | - Bog, mama.
{118991}{119064}Možete mi postavljati pitanja | dok ne poplavite, ali želim
{119071}{119125}razgovarati s mojim | odvjetnikom! - Veæ jeste.
{119131}{119187}Ne želi imati | ništa s vama.
{119194}{119267}Specijalni agent Hanson, | što ste mu uèinili?
{119273}{119375}Nisam ja. - Imamo vaš glas | na kaseti! Pisao je izvještaj!
{119379}{119435}Pokušali ste ga unajmiti | da vam ubije muža.
{119441}{119488}Što se dogodilo?
{119494}{119561}Pokušao je odustati? | Pokušao je odustati,
{119567}{119624}pa ste ga ubili. - Ništa od | ovoga se ne bi dogodilo
{119630}{119685}da je ona djevojka obavila | svoj posao!
{119691}{119785}Koja djevojka? - Jill! | Tajnica mog muža!
{119809}{119870}I ona je bila plaæeni | ubojica? - Da, ja sam je
{119876}{119962}unajmila! Ona je ubojica!
{120095}{120191}Bilo bi tužno da nije tako | jadno. - Želite prièati s njom?
{120210}{120296}Ne. | Ne bih.
{120300}{120364}Ne krivim vas.
{120369}{120428}Znate nekog dobrog | odvjetnika za razvode?
{120435}{120529}Ona je to uèinila! Ona je | ubojica! Morate mi vjerovati!
{120684}{120776}Ne brini, razjasnio sam | sve u detalje. - Jimmy ima
{120783}{120849}svoje naèine. - Pobrinut | æu se za Jimmyja.
{120855}{120900}Više ga nikad neæeš | morati vidjeti.
{120907}{120962}Dok ti i Jill budete dizale | novac iz banke, Jimmy i ja
{120967}{121026}æemo biti u muzeju likovnih | umjetnosti. - Jimmy u muzeju
{121033}{121087}likovnih umjetnosti?! - U tom | muzeju ima ljudi. Neæe ništa
{121092}{121179}pokušati. - Dobro, | ako ti tako kažeš.
{121461}{121533}Gdje je Cynthija?
{121545}{121617}Ti i ja odlazimo.
{121704}{121777}Onda æu javiti Cynthiji na | biper, ona æe te pozvati na
{121782}{121837}onaj telefon i reæi kamo | trebaš iæi. - Èuj ti njega.
{121844}{121923}Pravi g. Viteški podvig. | - Oprezan sam. Ja sam zubar.
{121928}{121983}Da.
{122068}{122130}Deèki, lijepo se igrajte.
{122234}{122299}Vozi u muzej likovnih | umjetnosti.
{122324}{122400}Zbilja misliš da æeš, | ako Cynhtija nešto zezne,
{122407}{122463}biti sigurniji u tom muzeju?
{122846}{122907}Da, da...
{122913}{122971}Nadam se da u tom muzeju nema | ništa specijalno što si
{122975}{123063}danas htio vidjeti. - Zašto? | - Jer ne idemo u muzej.
{123068}{123157}Idemo u marinu. | - U marinu? - Da.
{123161}{123251}Iznajmio sam brod na jedan | dan. Zar ne, Frankie?
{123396}{123478}Vidiš? I ja sam oprezan.
{124494}{124551}Ti si Jill?
{124568}{124628}Drago mi je.
{124640}{124732}Gdje ti je pištolj? - Zašto | misliš da imam pištolj?
{125027}{125092}Baci ga u vodu.
{125235}{125302}Imaš potvrde o smrti?
{125318}{125380}Idemo u banku.
{125397}{125465}P0TVRDE 0 SMRTI
{125496}{125581}Èini se da je sve u redu. Gdje | želite da pošaljemo novac?
{125585}{125664}U banku na Kajmanskim otocima. | Broj raèuna je...
{125670}{125737}Isprièajte nas jedan | trenutak, molim. - Naravno.
{125742}{125804}Hvala. - Bit æu tamo.
{125977}{126058}Možemo jednostavno otiæi, | znaš. Ti i ja.
{126083}{126143}Sa svih 10 milijuna.
{126256}{126315}Što misliš?
{126452}{126505}Mislim...
{126513}{126607}znam da æe Jimmy ubiti Oza | ako to uèinimo. - Pa što?
{126770}{126873}Ti si sretan èovjek, 0ze. | - Zašto to kažeš?
{126883}{126971}Uskoro æeš saznati voli li | tebe žena koju ti voliš.
{126983}{127042}Pivo?
{127052}{127177}Da sam ja na njenom mjestu, | uzeo bih novac i pobjegao.
{127258}{127349}Na što se kladiš? | - Na ljubav.
{127389}{127474}Ljubav prema tebi znaèi | novac za mene. Kao što rekoh,
{127490}{127572}zbilja bih mrzio da te | moram ubiti.
{127880}{127954}Kad æeš to uèiniti? - Prvo | moramo biti sigurni da
{127959}{128014}æemo dobiti novac.
{128049}{128115}Ali ga namjeravaš ubiti?
{128161}{128259}Jimmy, slušaj. Bio je tamo! | Bio je tamo kad si ubio
{128264}{128354}Jannija i drota. Znam | da ti se taj momak sviða.
{128386}{128474}Da, sviða mi se. | - Ali moraš ga ubiti.
{128482}{128552}Ako ti nisi spreman na to, | ja æu... - Frankie!
{128588}{128663}Ne zaboravi s kim | razgovaraš, u redu?
{128697}{128788}Jimmy Tudeski možda jest | mrtav, ali ne za ozbiljno.
{128798}{128855}Razumiješ?
{128861}{128947}To mi je drago èuti. | - Samo ti upravljaj brodom.
{129067}{129167}Razmisli, Cynthija. Rijeè je | o 5 milijuna dolara svakoj.
{129181}{129252}Zar ti Oz doista | toliko vrijedi?
{129297}{129359}Stvar je u tome...
{129389}{129470}da mislim da ga volim. | - Misliš? Misliš?!
{129474}{129564}Dušo, za 5 milijuna dolara | bolje budi vraški sigurna!
{129619}{129674}Jesam.
{129679}{129738}Žao mi je, ali...
{129743}{129805}volim ga.
{129810}{129858}Zbilja?
{129863}{129949}To je pravi odgovor. | Ti, vrati se natrag.
{130084}{130137}Da?
{130228}{130279}U redu.
{130308}{130363}U redu.
{130408}{130471}Dobili smo novac.
{130571}{130623}Zbogom, Oze.
{130670}{130720}Ali...
{130902}{130961}Žao mi je, Frankie.
{130970}{131032}Uvijek si mi se sviðao.
{131055}{131156}Zašto si ga ubio?! - Morao | sam ubiti jednog od vas.
{131223}{131294}Onda si definitivno donio | pravu odluku!
{131381}{131450}Ali zašto si ga morao | ubiti?
{131574}{131635}Da te ja nisam ubio, | Frankie bi.
{131710}{131808}Mislio bi da sam se smekšao, | pa bi se na kraju okrenuo
{131812}{131873}za mnom i za novcem.
{132017}{132061}A ja?
{132067}{132160}Želim da taj novac | pošaljete na ovaj raèun.
{132166}{132242}Želim da se 1 milijun uplati | na ovaj raèun na imena
{132247}{132327}dr. Nicholas i gðe | Cynthije Oseransky.
{132334}{132392}1 milijun... | - Što?!
{132398}{132484}Uranjeni dar za svadbu | od Jimmyja.
{132497}{132560}Ne tog Jimmyja.
{132581}{132675}Možete nas još malo | isprièati? - Dakako. - Hvala.
{132808}{132878}Je li ovo ozbiljno? - Jest, | ali da biste dobili novac
{132882}{132941}morate doæi zajedno i | pokazati kopiju vjenèanog
{132945}{133068}lista. - Jimmy mi daje | razvod? - Ne èitaš novine?
{133080}{133136}Jimmy Tudeski je mrtav.
{133298}{133400}Ne znam što da kažem. - Kad | bude vrijeme, samo reci. - Da.
{133468}{133574}Možda sam se doista smekšao. | Ranije bih te sigurno ubio.
{133580}{133644}Ne budi tako strog | prema sebi.
{133673}{133744}Ili... | Ne znam.
{133767}{133831}Možda sam se doista | promijenio nakon smrti.
{133868}{133941}Mislim da se ne radi o tome. | - Kako to misliš?
{134007}{134082}Ti je voliš, zar ne? | - Cynthiju?
{134473}{134561}Bog, Oze. Cynthija te èeka. | Rekla je da znaš gdje.
{134675}{134735}Pozdravi moju udovicu.
{134787}{134841}Èuvaj se.
{135319}{135383}Udaj se za mene.
{135496}{135557}Jimmy ti je rekao.
{135565}{135620}Što?
{135666}{135727}Nije, zar ne?
{135792}{135850}Ti me jednostavno...
{135856}{135928}želiš oženiti? | - Ne.
{135948}{136021}Ne želim te jednostavno | oženiti.
{136034}{136103}Želim te oženiti više nego | što je ikad itko želio
{136107}{136176}nekoga oženiti | u povijesti svijeta.
{136265}{136342}Hoæu li pretjerati | ako ti kažem
{136364}{136426}da te volim?
{136692}{136754}I kažem. - Da.
{136795}{136857}Voljela bih se udati | za tebe.
{136882}{136961}Ne bi ti smetalo da provedeš | život sa siromašnim zubarom?
{136990}{137055}Nešto mi govori da æemo | se snaæi.
{137060}{137400}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan  
