{1}{1}25.000
{1080}{1180}{C:$0000FF}{y:ib} MALA |{C:$FF0000}{y:b} AKEELAH 
{1252}{1351}Znaš li onaj osjeæaj kada, bez | obzira što radiš ili kamo ideš,
{1354}{1390}jednostavno se ne uklapaš?
{1401}{1442}Ne znam rijeè za to.
{1446}{1515}Otuðenje, zastranjivanje?
{1519}{1609}Nesuradnja? | Ne... to nisu te rijeèi.
{1612}{1667}Ali mora postojati rijeè za to.
{1671}{1726}Jer tako se osjeæam | cijelo vrijeme.
{1730}{1818}Ja sam Akeelah Anderson | i 11 mi je godina.
{1822}{1894}I sve poèinje u osnovnoj školi | Crenshaw Middle School
{1897}{1936}u južnom Los Angelesu.
{2271}{2371}Sada svi pohaðate 7. razred | i znam da možete bolje od ovog.
{2374}{2459}Kada dobijete listu s rijeèima, | prouèavajte ih!
{2466}{2495}Akeelah!
{2514}{2575}Koliko si dugo uèila | za ispit u slovkanju?
{2640}{2662}Nisam uèila.
{2744}{2784}Doði do mene poslije nastave.
{2852}{2896}Ocjena 5, 100% toènosti.
{2935}{3020}Dobro znaš da bi mogla biti | jedna od mojih najboljih ðaka.
{3024}{3120}Ali ne pišeš domaæe zadaæe, | i èesto izbjegavaš nastavu.
{3123}{3149}O èemu se radi?
{3153}{3189}Ne znam.
{3379}{3431}Znaš li za natjecanje | u slovkanju iduæi tjedan?
{3435}{3465}Ne.
{3475}{3535}Trebala bi se prijaviti.
{3649}{3730}Misli li on doista da æu hodati | u kratkim hlaèicama?
{3733}{3812}On je lud! Vraæa li se | Devon danas kuæi?
{3815}{3910}Da. Ima dvotjedni dopust. | - Tvoj je brat sjajan momak.
{3914}{4041}Zasigurno æe biti pilot, | a ja njegova stjuardesa.
{4075}{4136}Imate li sitnog | za mene, djevojke?
{4140}{4192}Nemamo ni za sebe.
{4264}{4326}Derrick-T ima dobar novi auto!
{4372}{4442}Ma samo radi nevolje Terranceu!
{4445}{4541}Tvoj brat radi nevolje sam sebi. | Što je gða Cross htjela?
{4545}{4630}Ništa. Prièala mi je o nekom | glupom natjecanju u slovkanju.
{4634}{4703}Hoæeš se prijaviti? | Bila bi dobra u tome.
{4707}{4804}Natjecati se pred mnoštvom? | Sledila bih se od straha.
{4820}{4881}Prièaj mi o djeèaku koji te | tražio da nosiš kratke hlaèice.
{4885}{4903}Sladak je.
{5232}{5263}Pogodak! | 69 bodova.
{5267}{5298}To!
{5325}{5354}Keelie, mama kaže | da moraš jesti!
{5358}{5395}Moram oboriti rekord! | Za minutu æu...
{5399}{5456}Ne zanima me! | Mama kaže da moraš jesti!
{5462}{5553}Napokon! O tvojoj kuhinji | sanjam veæ 5 mjeseci!
{5559}{5620}Barem jedno od moje djece | cijeni to što radim.
{5624}{5699}Svi te cijenimo. Daj pusu!
{5711}{5770}Gdje je Terrance? | - Ne znam, možda još na poslu.
{5773}{5827}Posao mu je završio prije sat | vremena. Nadam se da mu
{5830}{5871}Terrick-D ne radi društvo.
{5875}{5920}Terrick-D? Taj je nevaljalac | još uvijek živ?
{5923}{5959}Ne nakon što se ti | obraèunaš s njim!
{5963}{6006}Tako je. Hej, ti!
{6015}{6056}Koliko si zrakoplova | do danas sredio?
{6061}{6152}Nijedan. Nema puno akcije dok | sjediš za simulatorom vožnje.
{6156}{6273}To je dobro, dok si na tlu. | Neka malo bijeli deèki lete.
{6277}{6359}Mama, dobit æu i krila i diplomu | prije nego misliš!
{6362}{6400}Osim ako me ova mala | ne prestigne, naravno!
{6403}{6455}Neæe ako nastavi izostajati | s nastave sa Georgijom!
{6459}{6505}Izostajati s nastave? | - Samo s tjelesnog!
{6509}{6597}Ne izostaj! | - Akeelah, ugasi TV.
{6601}{6693}Prebaci na sportski | program da vidim rezultate.
{6901}{6986}Odslovkaš li sljedeæu rijeè | ispravno, bit æeš pobjednica!
{6991}{7066}Što je ovo? | - Akeelah, ugasi TV!
{7070}{7178}Bordocrvena! | - B-O-R...
{7184}{7255}D-O-C-R...
{7260}{7307}V-E-N-A. | Bordocrvena.
{7312}{7400}Èestitam! Pobijedila si!
{7466}{7565}Akellah, poslušaj me! | Ugasi TV!
{7624}{7688}Bordocrvena...
{7810}{7947}Bordocrvena - [def.] nijansa | crvene boje, kao trula višnja.
{7951}{8010}Zašto jednostavno ne | piše samo trula višnja?
{8059}{8135}Tata, jesi li ikada | èuo za ovu rijeè?
{8236}{8304}Aha... vjerojatno jesi.
{9270}{9302}Bog, èudakinjo!
{9346}{9429}Riješi nam zadaæu iz engleskog. | Èujemo da si mozgalica.
{9433}{9544}Nisam ja nikakva mozgalica! | - Znamo da jesi! Imaš sve petice!
{9579}{9645}Znala sam. Uplašena je. | Kuda bi ti?
{9650}{9733}Ne znam kako da ti zahvalim | što si danas došao, Josh.
{9737}{9833}Imam prigovore zbog loših | ocjena mojih uèenika.
{9837}{9919}Kako ti rekoh, | cijenim to što si me pozvao,
{9923}{10037}ali ne vidim kako mogu pomoæi. | - Samo želim da obratiš
{10040}{10101}malo pozornosti na tu djecu | i razuvjeriš me u mojoj ideji!
{10104}{10156}Neki od njih imaju potencijala!
{10160}{10241}Cure, zašto niste na nastavi? | - Ona nas zadržava!
{10245}{10276}Akeelah!
{10317}{10368}Jesi li se prijavila | za ono natjecanje?
{10377}{10402}Nisam.
{10423}{10474}Posjeti me u uredu, | molim te.
{10537}{10668}Znaèi, nijednom nisi | pogriješila u slovkanju do sad.
{10672}{10763}Ali tvoje pohaðanje nastave nije | nešto èime se možeš pohvaliti.
{10771}{10824}11 ti je godina. | Preskoèila si jedan razred?
{10828}{10860}Da, drugi.
{10923}{11022}Jesi li èula za državno | natjecanje u slovkanju?
{11026}{11068}Mislim da je bilo | na TV-u prošli tjedan.
{11072}{11155}Da. Prikazuju ga na | ESPN-u svake godine.
{11159}{11323}Ðaci svih škola natjeèu se na | lokalnim natjecanjima kako bi
{11326}{11410}pristupili glavnom državnom | natjecanju u Washingtonu.
{11414}{11483}Iduæe godine želim vidjeti | jednog svog ðaka tamo.
{11486}{11542}Onaj tko danas pobijedi | na školskom natjecanju
{11546}{11651}predstavljat æe školu | na okružnom natjecanju.
{11655}{11710}Zašto bi netko predstavljao | školu koja nije u stanju
{11714}{11764}staviti obièna vrata na zahode?
{11854}{11916}Ako ne možemo pokazati | što naši uèenici znaju,
{11920}{11985}neæemo imati niti za knjige, | a kamoli za zahodska vrata.
{11990}{12041}Dogovoreno? Iæi æeš | se natjecati danas?
{12044}{12110}Pa da me svi zovu | èudakinjom i mozgalicom?
{12114}{12176}Ne... nisam za to.
{12193}{12348}Više bi kaznu zbog izostanaka?
{12363}{12495}Dobro došli na Prvo | školsko natjecanje u slovkanju.
{12499}{12640}Imamo jake igraèe i molim | jedan veliki pljesak za njih!
{12768}{12855}Izvukli smo brojeve | da vidimo tko æe iæi prvi.
{12860}{12935}Chuckie Johnson, | osmi razred!
{13002}{13085}Imam pitanje u vezi s mrežom | na obruèu... - Chuckie!
{13105}{13141}Usredotoèi se!
{13147}{13236}Poèet æemo s rijeèju molitva.
{13244}{13306}Motika? | Mislite ono za kopanje?
{13311}{13425}Ma ne... Molitva! Kada klekneš | pa razgovaraš s Bogom.
{13428}{13491}Kada kleknem? Što?!
{13495}{13526}Samo lijepo odslovkaj.
{13544}{13644}M-O-T-I-K-A.
{13653}{13757}Ne, Chuckie. Odslovkao si | motika. Rekla sam molitva!
{13761}{13862}M-O-L-I-T-V-A. | Nisi me pozorno slušao.
{13906}{13984}U redu. Iduæa je | Akeelah Anderson.
{14107}{14205}Tvoja rijeè je sumnja.
{14219}{14268}S-U-M-NJ-A.
{14273}{14338}Oprosti, nismo te èuli. | Možeš li još jednom?
{14342}{14385}S-U-M-NJ-A.
{14401}{14428}Izvrsno!
{14501}{14546}Calvin Baker.
{14552}{14664}L-A-K-A-N-O. | Lagano.
{14678}{14780}Žao mi je. Ide ovako: | L-A-G-A-N-O.
{14877}{14956}Odslovkaš li iduæu rijeè | kako treba, pobijedit æeš.
{14960}{15004}Izmišljotina.
{15009}{15071}I-Z-M-I-Š-LJ-O-T-I-N-A.
{15075}{15190}Toèno! Osvojila si prvo | mjesto na školskom natjecanju!
{15352}{15488}Isprièavam se! Odslovkaj mi | brzoprstnost ako znaš!
{15517}{15635}Gospodine, njoj je svega | 11 godina, i veæ je pobijedila.
{15639}{15676}G. Welch, što je ovo?
{15724}{15803}Brzoprstnost. Znaš li?
{16002}{16196}B-R-Z-O-P-R-S-T-N-O-S-T. | Brzoprstnost.
{16212}{16244}Toèno!
{16368}{16399}Svespretnost!
{16403}{16478}S-V-E-S-P-R-E-T-N-O-S-T.
{16483}{16510}Pterodaktil!
{16514}{16584}P-T-E-R-O-D-A-K-T-I-L.
{16589}{16626}Sinhronizativan!
{16635}{16668}S-I-N...
{16772}{16812}S-I-N...
{16905}{17016}...K-R-O-N-I-Z-A-T-I-V-A-N.
{17072}{17112}Sinkronizativan?
{17116}{17275}To je bilo netoèno. | Zamijenila si h za k.
{17363}{17423}Vidite? Ipak nije tako pametna!
{17670}{17719}Akeelah! Èekaj!
{17723}{17824}Kamo æeš? Bila si sjajna! | Slovkala si rijeèi koje ja ne znam!
{17828}{17934}Rekla sam vam da | ne želim to! Smiju mi se!
{17940}{17992}Smijali su se iz straha.
{18003}{18073}Ali da se nisi povukla, | možda bi zaradila poštovanje.
{18077}{18174}Bob, cura ima potencijala. | Treba joj struèno vodstvo.
{18239}{18347}Znaš li tko je to? Dr. Joshua | Larabee. Bio je ravnatelj
{18351}{18399}odsjeka za engleski jezik pri | Sveuèilištu u Los Angelesu.
{18403}{18482}Pohaðali smo fakultet skupa. | Kao dijete je došao
{18486}{18597}do finala u natjecanju. | On misli da i ti to možeš.
{18605}{18696}Žao mi je... ali ja se više | ne natjeèem u ovom!
{18779}{18857}Curo, isprašila si sve | koji su se juèer pojavili!
{18861}{18911}Ali nisam | odslovkala zadnju rijeè.
{18915}{18971}Znala si sve ostale | pred onim likom!
{18975}{19081}Trik-rijeèi... svi znaju da | pterodaktil poèinje s p.
{19085}{19170}Da ja slovkam kao ti, posao | stjuardese dobila bih odmah!
{19245}{19289}Keelie, probudi se!
{19410}{19503}Dev, veæ odlaziš? | - Da. Moram natrag u bazu.
{19530}{19624}Ravnatelj je nazvao mamu. Kaže | da si briljirala na natjecanju.
{19628}{19659}Zeznula sam jednu rijeè...
{19663}{19709}Znam, ali rekao je i da | si mnogo rijeèi znala.
{19713}{19801}Spomenuo je i moguænost da | odeš na još veæe natjecanje.
{19806}{19862}Ne želim to. | - Zašto?
{19869}{19973}Svi æe buljiti u mene i bit æe | tisuæu rijeèi koje neæu znati.
{19977}{20019}Pa si malo uplašena, ha?
{20043}{20107}Kako misliš da mi je bilo 1. put | kada sam skakao iz zrakoplova?
{20111}{20178}Svaki dio tijela je | govorio da to ne napravim.
{20182}{20256}Ali katkad moraš | slušati svoje srce.
{20261}{20380}Ni ne volim svoju školu. | Zašto bih išta radila za nju?
{20433}{20464}Uèini to za tatu.
{20494}{20602}Znaš kako je volio rijeèi... | Bio bi presretan da pristaneš.
{20612}{20734}Što mama kaže? - Znaš mamu, | stotinu joj je stvari na pameti.
{20756}{20885}Èuj. Reci da, i ako | doguraš do finala,
{20888}{20968}spustit æu se padobranom | da te gledam. Hoæeš tako?
{21402}{21487}Sjajna odluka, Akeelah!
{21492}{21560}Mislite li da mi škola može | pribaviti novo odijelo?
{21564}{21625}Znate... za okružno natjecanje.
{21629}{21700}Pa... možda, vidjet æemo.
{21704}{21787}Ako uspiješ doæi do | sljedeæeg stupnja, sigurno!
{21791}{21851}U tom bi sluèaju morala osvojiti | jedno od prvih 10 mjesta
{21854}{22021}na okružnom. Morat æeš se | iskazati pred mnoštvom djece
{22024}{22071}koja veæ imaju neko iskustvo u | tome, a èak ni ona nisu dogurala
{22074}{22102}do velikog finala u Washingtonu.
{22106}{22148}Možda bih trebala | odustati veæ sada!
{22152}{22266}Nikako. Samo trebaš | vježbati marljivo...
{22278}{22370}...s dr. Larabeejem. | - Što? Ne trebam njegovu pomoæ!
{22374}{22462}Najbolje da se pripremam sama. | - Najbolji uvijek imaju trenere!
{22466}{22588}Slušaj, dobio sam ga na ideju | da te vodi sad, dok ima pauzu.
{22592}{22690}Samo razgovaraj s njim. | Izvoli. Ne živi daleko.
{22694}{22793}Živi ovdje? Mislila sam | da je on neka faca!
{22797}{22864}I uzmi ovo. Video snimka | prošlogodišnjeg natjecanja.
{22868}{22940}Sukcesivno! | - Može definicija?
{22944}{23018}Ono koje slijedi. | - Mogu li znati jezik porijekla?
{23022}{23091}Latinski. | - Latinski? Zar ne prièamo
{23094}{23140}ovdje na engleskom?
{23520}{23594}Hej, što je to? | - Gdje si bio?
{23598}{23688}Mama je bila zabrinuta... | - Trebala bi se manje brinuti.
{23697}{23778}Što to gledaš? | - Natjecanje u slovkanju.
{23789}{23887}Èuo sam za to. Borit æeš se | protiv gomile bijele djece!
{23915}{23969}Mi crnci tu nemamo šanse.
{25009}{25040}Zakasnila si.
{25044}{25109}Niste mi se javili, zvonila sam. | - Jer kasniš.
{25112}{25177}Uði. Hajde, uði!
{25314}{25405}Znaèi... htjela bi nauèiti | dobro slovkati.
{25408}{25479}Znam slovkati! | - Slovkaj mi Staphylococci.
{25519}{25607}S-T-A-F... | - Nema tu nikakvog F.
{25611}{25682}To je izvorno grèka rijeè, | znaèi ne može se pojaviti F.
{25686}{25898}Staphylococci. | S-T-A-P-H-Y-L-O-C-O-C-C-I.
{25903}{25994}Pobjednièka rijeè, Državno | natjecanje u slovkanju, 1987.
{25998}{26080}Prva stvar koju svi ozbiljni | natjecatelji nauèe je popis
{26084}{26140}svih dosadašnjih pobjednièkih | rijeèi i njihovo porijeklo.
{26144}{26239}Možda ja nisam tako ozbiljna! | - Možda nisam ni ja.
{26284}{26362}Kako to da si doma preko dana? | Kaj ti je s poslom?
{26366}{26431}Uèini mi uslugu. Uliènu spiku | ostavi pred vratima.
{26436}{26522}Ulièna spika? Ne prièam ja tako. | - Kaj ti je s poslom?
{26526}{26590}Tako s prijateljima prièaj.
{26594}{26654}Dok si ovdje, prièat æeš | normalno ili neæeš uopæe.
{26658}{26703}Jasno? | - Da.
{26739}{26776}Kao da me briga.
{26782}{26834}Možeš slobodno otiæi. | - Molim?
{26838}{26891}Èula si me. | - Zašto?
{26895}{26988}Nemam vremena za | drske male djevojèice.
{26992}{27120}Drske? Komu ti... | Mislim, nisam drska!
{27126}{27208}To je prva stvar koju napraviš? | Pleteš prste u to kako...
{27214}{27285}Kritiziraš me kako govorim?
{27310}{27371}Mislila sam da se tu radi | o slovkanju rijeèi.
{27441}{27477}U redu.
{27668}{27807}Znate što? | Kad se potrudim, pamtim sve!
{27811}{28034}I ne trebam pomoæ jednog obiènog | vrtlara! Isprike na drskosti!
{28559}{28678}Hej! Što još radiš budna? | - Moram uèiti.
{28688}{28750}Doæi æeš me gledati | na okružnom natjecanju?
{28754}{28848}Gdje, u tvojoj školi? | - Ne. Na Beverly Hillsu.
{28852}{28986}Beverly Hills? Slušaj, imaš | svoju domaæu zadaæu.
{28990}{29061}Ne želim da svoje vrijeme | protratiš na tu igru.
{29064}{29143}Nije to igra! Hoæeš li | me doæi gledati?
{29166}{29237}Znaš i sama da radim | u bolnici u subotu.
{29242}{29277}Kiana æe poæi.
{29281}{29344}Samo da ne ide | i ono cmizdravo dijete!
{29417}{29494}Požurimo! Zakasnit æemo.
{29761}{29853}Dovraga! Nadam se da nisu | svi došli kako bi se natjecali.
{29860}{29938}Idi po svoj broj. | Mi æemo biti ovdje.
{29951}{29987}Sretno, Keelie!
{30437}{30531}Bog! Tvoje ime? | - Akeelah Anderson.
{30538}{30635}Pronašla sam te. Prva si
{30639}{30695}iz Crenshaw osnovne škole.
{30712}{30853}Koliko tu djece uopæe ima? | - 139. Sljedeæi!
{31002}{31094}Trebaš pomoæ? Ne boj se, | neæu te ubosti.
{31103}{31184}Prvi put si ovdje? | - Da. A ti?
{31188}{31298}Drugi put. Dogurao sam do | državnog natjecanja i bio 13.
{31305}{31335}Sretan broj 13!
{31359}{31463}Dogurao si sve do tamo? | - Trima iz moje škole je uspjelo.
{31477}{31566}Vidiš onog klinca tamo? | To je Dylan Chiu.
{31570}{31638}Veæ mu je 2 g. Pošlo | za rukom plasirati se kao drugi.
{31642}{31720}Ovo mu je zadnja prilika, i svi | su uvjereni da æe pobijediti.
{31724}{31797}Iskreno, volio bih ga pomesti!
{31824}{31897}Ja sam Javier. | - Akeelah.
{31900}{31961}Nadam se da idemo do kraja. | - Nadam se da neæu prva ispasti.
{31965}{32029}Neka svi natjecatelji | zauzmu svoja mjesta!
{32033}{32140}Zapamti, ako zapneš... samo | odslovkaj kako misliš da ide.
{32144}{32211}Iako misliš da se radi o teškoj | rijeèi, èesto se lako odslovka.
{32214}{32256}Sretno! | - I tebi.
{32266}{32369}M-I-Š...
{32390}{32502}I-Æ-N...
{32507}{32604}O-U-P...
{32609}{32644}A-L-N-I.
{32648}{32695}Mišiænoupalni.
{32912}{32952}Rhesus!
{32958}{33035}Resurs? | Mogu li znati definiciju?
{33045}{33117}Žuækasti majmun iz Indije.
{33121}{33168}Aha! Rhesus!
{33177}{33264}R-H-E-S-U-S. | Rhesus.
{33298}{33328}Toèno!
{33659}{33696}Broj 54?
{33921}{33958}Eminentan!
{34056}{34094}Jeste li èuli rijeè?
{34106}{34224}Nisam sigurna da li sam èula | iminentan ili eminentan.
{34229}{34311}Želiš definiciju? | - To bi bilo supaè.
{34390}{34544}Eminentan - naoèit, poseban, | drukèiji od drugih.
{34550}{34590}Eminentan!
{34629}{34780}E-M-I-N-E-N-T-A-N. | Eminentan?
{34805}{34831}Toèno!
{35289}{35336}Hipertropik!
{35342}{35434}H-I-P-E-R-T-R-O-P-I-K. | Hipertropik.
{35440}{35471}Toèno!
{35854}{35896}Concierge!
{35900}{35963}Mislite na onog èovca koji | vrijeme provodi u hotelu?
{35967}{36106}Molim u mikrofon. | - Da, radi se o domaru/vrataru.
{36113}{36253}C-O-N-C-I-E-R-G-E.
{36257}{36283}Toèno!
{36404}{36488}Ide ti dobro! | - Samo imam sreæe!
{36493}{36539}Zamisli da dobijem...
{36670}{36735}Ostalo je još samo | 11 natjecatelja.
{36739}{36838}Prvih deset æe iæi dalje.
{36843}{36879}U iduæoj rundi...
{36975}{37061}...ako promašite rijeè, | ne napuštajte pozornicu...
{37135}{37230}...jer æete imati šansu | za preostala mjesta.
{37242}{37304}Kiana, izaði | s tim djetetom!
{37379}{37407}Dakle...
{37503}{37529}Poènimo!
{37535}{37648}S-I-L-O-G-I-Z-I-R-A-M. | Silogiziram?
{37653}{37680}Toèno!
{37959}{37999}Sinegdota!
{38264}{38310}Mogu li znati što je to?
{38316}{38463}Dio jedne prièe, | individualni segment,
{38467}{38571}materijal neke stvari, ili | kombinacija svega toga.
{38768}{38811}Molim, odslovkaj rijeè!
{38860}{38890}S...
{38963}{38998}I...
{39065}{39088}N...
{39127}{39150}E...
{39188}{39228}K...
{39253}{39292}T...
{39432}{39532}O-T-A. | Sinektota?
{39628}{39801}Toèno slovkanje je: | S-I-N-E-G-D-O-T-A.
{39988}{40117}Odslovkaš li sljedeæu rijeè, | bit æeš posljednji finalist.
{40131}{40176}Carmagnole!
{40277}{40325}Mogu li znati definiciju?
{40329}{40403}Živahan francuski ples.
{40457}{40646}C-A-R-M-A...
{40939}{41040}G-N-O-L-E. | Carmagnole.
{41047}{41080}Toèno!
{41086}{41189}Posljednji finalist danas!
{41305}{41433}Varao je! Vidjela sam ga! | Mama mu je pomagala!
{41442}{41526}Isprièavam se... a tko ste vi?
{41531}{41621}Keelina sestra. Bila sam tamo | i vidjela kako mu je mama
{41627}{41701}došapnula slovo G!
{41710}{41797}Znao je tu rijeè! | Ponavljali smo je skupa!
{41801}{41899}Biste li pomogli | sinu u slovkanju te rijeèi?
{41928}{41980}Ovo je ozbiljna stvar.
{42079}{42236}Vi to meni govorite? Znate li vi | koliko se dugo spremao za ovo?
{42241}{42270}Znao je tu rijeè!
{42275}{42352}Ne... nisam je znao.
{42437}{42568}Žao mi je, ali morat æu | diskvalificirati broj 62.
{42573}{42707}Ako broj 54 | odslovka toèno još jednu rijeè,
{42711}{42780}postat æe naš | zadnji finalist!
{43017}{43048}Plagijat!
{43164}{43311}P-L-A-G-I-J-A-T. | Plagijat.
{43338}{43372}Toèno!
{43377}{43456}Kvalificirala si se | za regionalno finale!
{43564}{43600}Moj broj.
{43604}{43675}Imamo uèenièki klub u školi, | doði jednom vježbati s nama!
{43679}{43746}Zvuèi zabavno! | - I jest.
{43751}{43811}Došli su mi roditelji. | Vidimo se!
{43815}{43853}Bog! | - Bog!
{43950}{44058}Prvih troje | s regionalnog natjecanja
{44062}{44140}odlaze na državno | natjecanje u Washingtonu.
{44144}{44206}Ne ako ne znam slovkati | sinegdotu!
{44212}{44258}O, ne... gledajte ovo!
{44292}{44370}Koliko ti puta moram reæi | za oblaèenje? Slušat æeš me
{44374}{44451}dok si u mojoj kuæi! Bez droge, | uliène bande i skupih satova!
{44455}{44526}Skini ga! | - Derrick-T mi ga je dao.
{44530}{44602}Mama? | - Što hoæeš? Vas dvoje u kuæu!
{44606}{44665}Skini ga! | - Mama, uspjela sam!
{44669}{44702}Uspjela u èemu?
{44706}{44781}Plasirala sam se | na regionalno natjecanje!
{44785}{44884}Samo ti daj, mama æe uskoro | u mrtvaènicu na identifikaciju!
{44888}{44958}Ma neæeš! | - Èini se da æu morati!
{45008}{45076}Akeelah! | - Smjesta u kuæu!
{45110}{45158}U redu je, g. Welch.
{45183}{45214}Vidimo se.
{45379}{45411}Pogodi što?
{45475}{45529}Bit æu na | regionalnom natjecanju.
{47626}{47657}Dylan?
{47753}{47792}Ja sam Akeelah.
{47893}{47960}Javier je rekao da | vam se mogu pridružiti.
{47965}{48016}To je za luzere!
{48020}{48067}Meni je moj otac mentor.
{48091}{48122}Gdje je tvoj?
{48146}{48187}Nemam ga.
{48192}{48249}Na koliko si natjecanja | pobijedila?
{48253}{48296}Samo na školskom.
{48342}{48392}Slovkaj mi Xanthosis!
{48432}{48459}Z-A...
{48464}{48501}Poèinje sa X.
{48505}{48616}Da ona budala nije varala, | ne bi dospjela dovde.
{48712}{48747}Euforièan!
{48758}{48849}Euforièan je pridjev, | grèko porijeklo.
{48854}{48912}Opisuje stanje sreæe | i blagostanja.
{48919}{48971}Ili slovkaj, ili idi!
{48976}{49062}Promašiš li, dobiješ minus. | Tri minusa i vani si!
{49103}{49131}Euforièan.
{49136}{49219}E-U-F-O-R...
{49224}{49292}...I-È-A-N.
{49305}{49333}Euforièan.
{49341}{49374}Psorijaza!
{49379}{49415}Slušaš li latinski u školi?
{49419}{49493}Psorijaza je imenica, | grèko porijeklo.
{49497}{49615}Zezaš me? Moja škola | nema novaca ni za lopte.
{49619}{49726}Pomaže ti da razumiješ rijeèi. | Psorijaza je svrbež kože.
{49730}{49785}Mogla bi zamoliti mamu | da te vozi na naše satove.
{49789}{49865}Ne znam. Ovo poèinje | zvuèati sve teže...
{49869}{49954}I jest. Natjecanja u | slovkanju ozbiljna su stvar.
{49959}{50010}Mislim da æu ovaj put | baciti loptu.
{50181}{50246}Kad malo bolje razmislim, | mogu li ipak slovkati?
{50255}{50300}U Crenshowu me | smatraju èudakinjom.
{50305}{50377}Ne brini se. | Isto to misle i za nas ovdje.
{50382}{50429}Stigla mi je mama. | Trebaš prijevoz?
{50441}{50524}Pa... ne. Moja æe | mama doæi po mene.
{50528}{50568}Trebala bi stiæi uskoro.
{50604}{50694}Slavit æu roðendan uskoro. | Hoæeš li doæi?
{50700}{50777}Možda. Ako æu moæi.
{50786}{50837}Bilo mi je drago što | sam te opet vidio! Bog!
{50842}{50868}Bog!
{51653}{51691}Gdje si bila?!
{51734}{51764}Uèila sam.
{51769}{51812}Gdje si uèila?
{51855}{51947}Na Woodland Hillu. | - Woodland Hill? Kako to?
{51974}{52015}Tamo je slovkarski klub.
{52020}{52101}G. Welch te vozio? | Nitko mi ništa nije javio.
{52191}{52278}Išla sam sama. Nisam znala da æe | vožnja autobusom potrajati!
{52283}{52318}Žao mi je.
{52325}{52387}Zar si izgubila pamet?
{52393}{52496}Premlada si za to!
{52500}{52549}Nije bilo nikoga | da me povede!
{52553}{52589}Razlog je što radim!
{52594}{52700}To si rekla i za vikend. | Svi su ostali roditelji bili.
{52704}{52780}Možda ti roditelji | imaju malo više vremena.
{52784}{52880}Ne treba mi još jedno dijete | za koje æu se stalno brinuti!
{52885}{52942}Ako to tvoje slovkanje | znaèi iskradanje iz kuæe,
{52946}{52971}ništa od toga!
{52974}{53030}Ne možemo to otkazati! | Došla sam do regionalnog!
{53034}{53118}A izostajanje s nastave? | Dobila sam pismo iz škole.
{53122}{53201}Morat æeš u ljetnu školu | zbog izostanaka!
{53205}{53312}Mama, mrzim Crenshaw! | Dosadno je i nitko ne mari.
{53316}{53383}A u Crenshaw Hillu bi marili?
{53387}{53477}Bar imaju latinski! | I djeca ne uèe po hodnicima!
{53481}{53570}Dobro za njih! | No bez ljetne škole
{53574}{53610}zaboravi slovkanje!
{53614}{53711}Ali moram se pripremiti za | državno natjecanje na ljeto!
{53716}{53768}To æeš nagodinu.
{53772}{53794}To nije pošteno!
{53799}{53859}Rekla sam svoje!
{54149}{54199}Ti bi mi dopustio...
{54486}{54544}REGIONALNO SLOVKARSKO NATJECANJE | ODOBRENJE RODITELJA
{54681}{54736}Potpis roditelja
{54867}{54988}1979., Macalature, | M-A-C-A-L-A-T-U-R-E. Latinski.
{54992}{55080}1990., Fibranne, | F-I-B-R-A-N-N-E. Francuski.
{55085}{55212}1996., Vivisepulture, | V-I-V-I-S-E-P-U-L-T-U-R-E.
{55228}{55253}Latinski.
{55282}{55350}Nauèila sam sve | pobjednièke rijeèi.
{55354}{55405}Baš kao što se rekli.
{55417}{55478}Žao mi je što sam | prošli put bila drska.
{55482}{55522}To se više ne dogaða.
{55527}{55580}Mislim, to se više | neæe dogoditi.
{55584}{55620}Obeæavam.
{55647}{55744}Htjela sam vas zamoliti | da se predomislite.
{55798}{55902}Trebam mentora... | Opako!
{55947}{56031}Zbilja! | Zbilja trebaš mentora.
{56192}{56233}Uði.
{56399}{56488}Prekrasna dama! | To vam je žena?
{56497}{56561}Imala si sreæe | na okružnom natjecanju.
{56565}{56738}Državno natjecanje je teže. Ako | želiš da se pripremamo skupa,
{56743}{56867}držat æemo se moga rasporeda. | Tri sata na dan, poèevši od 9.
{56871}{56949}Možeš li tako? | - Moram pohaðati ljetnu školu.
{56952}{57034}No g. Welch mi je rekao da bi | rad s vama to nadomjestio.
{57038}{57139}Nije li to za uèenike koji ne | zadovoljavaju tijekom godine?
{57143}{57281}Pa... to je katkada za one | koji žele znati više...
{57285}{57367}Aha... | Spusti to, molim te.
{57480}{57552}Imaš li ciljeva?
{57586}{57645}Ciljeva u životu. | Što bi htjela biti kad narasteš?
{57649}{57732}Lijeènica? Odvjetnica? | Stand-up komièarka?
{57749}{57835}Ne znam. Jedino što mi | ide dobro je slovkanje.
{57932}{58036}Prošeæi i proèitaj | što piše na zidu.
{58127}{58174}Proèitaj naglas, | molim te.
{58213}{58324}Naš najveæi strah | nije strah od nemoæi.
{58328}{58434}Naš najveæi strah je da | smo beskrajno moæni.
{58439}{58628}Pitaš se, tko sam ja da budem | briljantan, prekrasan i nadaren?
{58635}{58737}Doista, | tko si ti da to ne budeš?
{58765}{58880}Roðeni smo da budemo | manifestacija Boga u nama.
{58884}{58937}I dok gledamo | sjaj vlastitoga svjetla...
{58942}{59039}...nesvjesno dajemo drugima | dopuštenje da uèine isto.
{59108}{59154}Znaèi li ti to išta?
{59176}{59208}Ne znam.
{59223}{59332}Napisano je normalnim rijeèima. | Što ti to znaèi?
{59383}{59448}Da se ne bih trebala bojati. | - Bojati èega?
{59520}{59555}Bojati...
{59627}{59646}same sebe?
{59865}{59977}Državno natjecanje | nije djeèja igra.
{59981}{60055}Ako želiš dogurati do tamo, | ne smiješ biti mimozica.
{60060}{60129}Moraš iæi bistrom | glavom naprijed.
{60135}{60173}U redu?
{60217}{60388}I neæu trpjeti tvoje besmislice. | Nemoj kasniti i biti drska.
{60393}{60486}U redu? | - Dogovoreno.
{60726}{60786}Tu smo! Stani!
{60801}{60876}Mama bi poludjela da sazna kako | smo posudili auto zbog ovog!
{60886}{60947}Zato mama neæe | ništa saznati.
{60973}{61015}Idemo, Georgia.
{61141}{61202}Idem do trgovaèkog | centra s Kianom.
{61207}{61260}Mislila sam da želiš | iæi na tu proslavu.
{61309}{61341}Bog, Akeelah!
{61446}{61476}Sigurna si?
{61489}{61517}Jesam.
{61536}{61570}Doði, idemo!
{61866}{61896}Zašto si njega pozvao?
{61900}{61983}Naši oèevi su prijatelji. | Èudi me što se uopæe pojavio.
{61988}{62021}Da ti pokažem kuæu?
{62027}{62057}Da. | - Idemo.
{62083}{62216}Ovo je ured moga oca. | Novinar je, okreæe velike novce.
{62268}{62307}Èime se tvoj otac bavi?
{62326}{62438}Moja tata... | radio je na održavanju parkova.
{62493}{62607}Imaš mnogo prijatelja. Nikad | nisam imala ovakvu proslavu.
{62611}{62676}Pomislio bih kako i ti | imaš mnogo prijatelja.
{62800}{62836}Otkud ovo?
{62843}{62961}Bilo je impulzivno. | Tužit æeš me za zlostavljanje?
{63162}{63206}Što ovi dolje rade?
{63211}{63276}Èini se da je | Dylan donio Scrabble.
{63284}{63311}Scrabble?
{63327}{63388}Dobivam 30 sekunda | za svaku od ovih ploèa.
{63392}{63455}Trebamo još jednog. | Tko želi igrati?
{63460}{63493}Ja!
{63632}{63745}Igra još nije ni poèela, a | Roman dobiva 32 boda!
{63750}{63871}Dylan se upliæe i zaraðuje | 39 bodova preko slova Z.
{63879}{63946}Polly razbija led sa | rijeèju acorn.
{63964}{64073}Dylan odgovara pravom mjerom, | rijeèju beacon, 20 bodova!
{64086}{64136}Sto mu gromova!
{64191}{64280}Dok ste rekli keks, Akeelah | izvlaèi sva svoja slova i dobiva
{64284}{64403}50 dodatnih bodova, što | znaèi ukupno sjajnih 82!
{64425}{64477}Što li æe Dylan sada izvesti?
{64481}{64586}Vrijeme nije na njegovoj strani. | Napetost se reže oštricom noža!
{64590}{64636}Zašuti!
{64832}{64958}Nevjerojatno! Dylan se vraæa | iz mrtvih, to je 76 bodova!
{65132}{65212}Dolazimo do kraja. Nakon što | je porazio svih pet protivnika,
{65217}{65264}ostala mu je još jedino Akeelah.
{65268}{65360}Vodi za 21 bod i ostalo | joj je još svega par slova.
{65364}{65416}Je li ovo veliki preokret?
{65425}{65470}Kakva je ovo zabava?
{65676}{65784}Hopla! | Dylan sada vodi za 6 bodova.
{65961}{65996}Hoæeš li?
{66231}{66330}Akeelah je preuzela vodstvo | za 12 bodova, ima još 1 slovo!
{66334}{66392}Ovo bi mogla biti | Dylanova zadnja prilika!
{66551}{66589}Zbogom, malena!
{66687}{66798}Ovim potezom je izjednaèio, no | dobiva Akeelahina dva boda.
{66802}{66864}Dylan pobjeðuje. | Srcolomac.
{66923}{67009}Dobar nastup Akeelah! Nitko mu | se nije još ovoliko približio.
{67013}{67050}No nisam ga pobijedila!
{67080}{67171}Curo, propustila si kupnju | zbog ove glupe igre?
{67229}{67274}Posreæilo joj se.
{67291}{67389}Ako ti jedva polazi za rukom | pobijediti malu crnu curicu,
{67393}{67462}kako se uopæe možeš nadati | prvom mjestu u Washingtonu?
{67489}{67522}Slušaj me!
{67540}{67636}Neæeš mi opet biti drugi! | Pobijedit æeš!
{67694}{67721}Idemo.
{67824}{67856}Smatrao je, želi li pronaæi | svoje mjesto pod suncem,
{67925}{67997}mora biti svoj i nièiji drugi.
{68002}{68064}Dr. Larabee, | ova knjiga je preteška.
{68068}{68125}Tako treba. | Razvit æe tvoje mišiæe.
{68130}{68177}Zar ne razvijamo | moj vokabular ovdje?
{68181}{68225}Tako je. | Nastavi.
{68229}{68277}Ali veæ znam veæinu | rijeèi ovoga govora!
{68281}{68340}Nije to govor. | To je esej.
{68344}{68456}Autor je g. Dubois, prvi crnac | koji je doktorirao na Harvardu.
{68460}{68521}A da se pozabavimo | dugaèkim rijeèima?
{68525}{68561}Slovkaj mi cabalistic!
{68565}{68668}C-A-B-A-L-I-S-T-I-C.
{68673}{68765}Kada si to nauèila? | - Maloprije u ovoj knjizi.
{68769}{68876}Ali u isto to vrijeme Dylan | ih nauèi vjerojatno 20!
{68881}{69035}Tih istih 20 njemu neæe ništa | znaèiti. On ih pamti kao robot.
{69039}{69119}Veliki ljudi o kojima èitamo, | Dubois, JFK, dr. King...
{69122}{69203}Oni su rijeèima | mijenjali svijet!
{69208}{69334}Nisu došli do tih rijeèi | neprestanim išèitavanjen!
{69339}{69448}U redu. Ali kada se naðem | na toj pozornici i kažu mi
{69452}{69572}da odslovkam neku australsku | ribicu ili Mjeseèevu bakteriju,
{69576}{69658}bit æe nam žao što se nismo | pozabavili tim išèitavanjem,
{69662}{69718}a malo manje èitanjem eseja.
{69737}{69782}Ako smijem primijetiti...
{69844}{69911}Na Mjesecu nema bakterija.
{69928}{70033}Reci mi nešto. Što misliš, | otkud dolaze velike rijeèi?
{70041}{70089}Od ljudi s velikim mozgovima?
{70204}{70233}Što vidiš?
{70237}{70294}Hrpu dugaèkih rijeèi | koje ne znam?
{70298}{70355}Ma ne. | Pogledaj ponovno.
{70374}{70432}Kakvu vrstu energije | dobivamo od Sunca?
{70437}{70460}Solarnu.
{70464}{70525}Što znaèi sol? | - Solarna.
{70530}{70606}Kako ti terraneous zvuèi? | - Kao teren.
{70611}{70757}Da, zemlja. Soliterraneous | povezuje sunce i zemlju.
{70761}{70814}Dakle, otkud dolaze | dugaèke rijeèi?
{70819}{70880}Iz kratkih rijeèi. | - A koliko takvih znaš?
{70885}{70933}Na tisuæe! | - Tako je!
{70937}{70993}Još mnogo njih moraš nauèiti.
{70997}{71130}Grèke, latinske, | francuske rijeèi.
{71154}{71240}I ako ih nauèiš sve, znat | æeš slovkati bilo koju!
{71244}{71291}Bez obzira koliko dugaèku.
{71362}{71431}A da se vratimo | na èitanje eseja?
{71435}{71546}Mislio sam da želiš | osvojiti to natjecanje.
{71580}{71637}Možda je za prvi put | bitno sâmo sudjelovanje.
{71641}{71682}Ma neæemo tako!
{71717}{71810}Toliko želiš tu nagradu | da ne možeš mirno spavati.
{71815}{71896}Otkad si saznala | za to natjecanje,
{71900}{71949}živiš za osvajanje | prvoga mjesta!
{71953}{71986}Ali ako to ne možeš reæi | naglas, neæeš ga ni osvojiti.
{71990}{72046}Da èujem... Reci to! | - Želim pobijediti.
{72050}{72110}Glasnije! | - Želim pobijediti!
{72114}{72203}Pobijediti u èemu? - U državnom | slovkarskom natjecanju!
{72207}{72347}U redu. Pobijedit æeš | spremajuæi se na moj naèin.
{72351}{72467}Razumijevajuæi snagu jezika. | Zatim na rašèlanjivanje rijeèi.
{72472}{72620}Pamteæi male rijeèi, korijene. | Upit æeš ih sve. Memorizirati.
{72626}{72723}Znaš li što æeš tada postati? | - Znam. Umorna.
{72743}{72842}Postat æeš pobjednica. | Spremna?
{72854}{72905}Spremna. | - U redu. Poènimo.
{74401}{74496}Kako to da si veæ tu? | - Nisam se osjeæala dobro...
{74540}{74614}Što to imaš? | - Domaæu zadaæu.
{74709}{74802}Regionalno natjecanje | je uskoro, mogla bi...
{74807}{74866}Mjesto radnje je Beverly Hills?
{74886}{74917}Ne znam.
{74921}{75005}Prvo ljetna škola, | onda sve ostalo.
{75008}{75057}Ali kada bi samo... | - Akeelah!
{75079}{75135}Jednostavno nisam | raspoložena.
{75434}{75487}Kako to da više ne pouèavate?
{75504}{75658}Pouèavam, preko Interneta. | Nastavimo!
{75687}{75728}Effervescent!
{75733}{75771}E-F-F...
{75785}{75815}E-R...
{75823}{75860}V-E...
{75923}{75977}S-E-N-T. | Effervescent.
{75981}{76014}Ma hajde! | Znaš tu rijeè!
{76018}{76056}Taj pas me ometa!
{76060}{76161}Ometat æe te mnogo više | stvari na pravom natjecanju!
{76165}{76244}Kakvi su to pokreti rukom? | - Koji?
{76260}{76388}To što radiš rukom. | Što je to?
{76393}{76431}Ne znam.
{76665}{76793}Što æe ti te sve igraèke? | - Pripadale su mojoj neæakinji.
{76827}{76922}Imaš li svoje djece? | - Voliš ispitivati, ha?
{76927}{77090}Prirodno sam znatiželjna. | - Istodobno i preznatiželjna.
{77107}{77155}Pokaži mi kako | preskaèeš uže.
{77162}{77226}Samo to? | - Da.
{77429}{77471}Vodi li ovo kamo?
{77566}{77612}Da. Nastavi.
{77770}{77842}Rekao sam da nastaviš. | Usredotoèi se.
{77847}{77893}Ponovi onu zadnju rijeè. | Effervescent.
{77897}{77957}Ne misli ni na što drugo! | Kreni!
{77979}{78055}E-F-F-E-R...
{78060}{78212}V-E-S-C-E-N-T. | Effevescent!
{78221}{78322}Vidiš? To je tvoj trik. | Tvoja mnemonièka tehnika.
{78327}{78380}Skakanje preko užeta? | - Ritam.
{78384}{78465}Djeca se na natjecanju | koriste mnogim pomagalima.
{78469}{78626}Njišu se, kreæu u krugovima. | Sve da ostanu usredotoèenima.
{78630}{78837}Ti voliš ritam. Ako æeš pamtiti | rijeèi uz ritam, bit æeš bolja.
{79699}{79750}Baš šteta što ti je majka danas | morala ostati na poslu.
{79754}{79789}Jesi joj pokazala | svoj novi dres?
{79793}{79878}Jesam, svidio joj se. | Evo Javiera!
{79883}{79978}Danas je baš uzbudljiv dan | za nas jer æe troje najboljih
{79982}{80144}predstavljati južnu Kaliforniju | na državnom natjecanju!
{80221}{80280}Što kažete, da krenemo?
{80286}{80378}Misliš da mala ima šanse? | - Vidjet æemo.
{80417}{80450}Alfresco!
{80454}{80547}A-L-F-R-E-S-C-O. | Alfresco.
{80551}{80585}Toèno!
{80829}{80870}Mogu li èuti ponovno?
{80874}{80921}Malloseismic!
{80946}{81019}M-A...
{81024}{81071}...L-O...
{81095}{81140}...S- E...
{81167}{81214}...I-S-M-I-C...
{81255}{81404}Malloseismic se piše | s dva L.
{81592}{81721}D-O-U-B-L-U-R-E. | - Toèno!
{81872}{81909}Psalmody!
{81916}{81955}Molim definiciju!
{82027}{82158}Gðo Anderson! | - Neka smjesta siðe s pozornice!
{82189}{82242}P-S-A...
{82247}{82354}Ne zanima me, | neka smjesta siðe!
{82360}{82402}...L-M-O...
{82406}{82570}Bila sam jasna kad sam | rekla da joj nije mjesto...
{82595}{82664}D-Y! | Psalmody.
{82684}{82719}Toèno!
{82776}{82814}Molim sljedeæi!
{82830}{82906}Isprièavam se. | Majka jedne natjecateljice
{82910}{82983}želi prièati s kæeri. Hitno je.
{83006}{83088}U redu, ali mora se vratiti | prije sljedeæeg nastupa,
{83092}{83172}ili æe biti diskvalificirana. | - Vratit æe se.
{83553}{83628}Mislili smo | da znate za sve ovo!
{83632}{83677}Hoæeš li mi reæi što se | dogaða ovdje?
{83681}{83740}Nisam potpisala | nikakvo odobrenje!
{83763}{83833}Potpisala sam tatu. | - Što?!
{83913}{84006}Kako misliš da je meni? | Javierova mama me pitala
{84009}{84108}hoæu li iæi s njima. Ne znam | ni tko je ni o èemu prièa.
{84112}{84183}Žao mi je. Samo | sam se htjela natjecati.
{84187}{84280}Potajno? Iza mojih leða | zadnjih šest mjeseci?
{84285}{84377}Pozdravi se sa svojim | prijateljima, ovdje završavaš!
{84381}{84444}Razmislite još | jednom, gðo Anderson.
{84448}{84544}Zaslužuje ovu priliku! | - Bob! Gða Anderson je u pravu.
{84566}{84625}Akeelah ne zaslužuje | nastupiti ove godine.
{84633}{84657}Što?
{84688}{84730}Iduæi natjecatelj, molim!
{84783}{84834}Približi se mikrofonu.
{84944}{85016}Malo brže! Hajde!
{85113}{85222}Isprièavam se, gðo Anderson, | ako sam ikako bio upleten...
{85235}{85277}A tko ste vi?
{85282}{85328}Joshua Larabee.
{85333}{85444}Pomogao sam Akeelahi da se | pripremi za ovo natjecanje.
{85463}{85555}Dobit æe dodatne bodove | za suradnju s dr. Larabeejem.
{85559}{85643}Osmislili smo poseban | program samo za nju.
{85665}{85760}Zašto mi nisi rekla? | - Nisam uživala u tome.
{85765}{85847}Ali svaki put kada bih spomenula | natjecanje, nisi htjela ni èuti!
{85882}{85921}Nisam znala što uèiniti.
{85971}{86126}Mogu li èuti rijeè još jednom? | - Veæ smo ti proèitali 5 puta.
{86148}{86254}Mogu lije èuti u reèenici? | - Èuo si je veæ.
{86259}{86387}Mislim, u nekoj drugoj reèenici. | - Imaš pravo na samo jednu.
{86392}{86431}Što je s ovim malim?
{86516}{86628}Ovo ti je zbilja važno. | Nikad mi do sada nisi lagala.
{86642}{86732}Smisli si dobru kaznu za | ovo što si mi pripremila!
{86849}{86897}Morat æu | propustiti natjecanje.
{86901}{87007}G. Welch i dr. Larabee | su mnogo uložili u ovo.
{87012}{87058}Morat æeš izabrati | nešto drugo.
{87180}{87226}Pranje suða jedan | cijeli mjesec?
{87231}{87277}Tri mjeseca!
{87332}{87391}Ima li vremena vratiti | se na pozornicu?
{87439}{87487}Ako se požurimo, da.
{87496}{87547}Bolje kreni.
{88019}{88055}Vi ste dr. Larabee?
{88059}{88084}Da.
{88110}{88206}Doista mislite da Akeelah ima | šanse na tom natjecanju?
{88232}{88303}Da, mislim da ima.
{88419}{88465}Mogu li èuti tu rijeè | u nekoj pjesmi?
{88469}{88496}Što?
{88558}{88664}Nema veze. Ratatouille. | R-A-T-A-T-O-U-I-L-L-E-
{88668}{88732}Ratatouille? | - Toèno!
{88739}{88825}Broj 73, molim! | - Ovdje je.
{88957}{89025}Hvala ti. | - Skoro sam poèeo plesati!
{89063}{89131}Poènimo. | Pluviosity!
{89139}{89178}Molim definiciju!
{89183}{89305}Stanje velike kišovitosti.
{89484}{89655}Pluviosity. | P-L-U-V-I-O-S-I-T-Y.
{89662}{89722}Pluviosity. | - Toèno!
{90181}{90288}Želio bih vam svima zahvaliti | što se danas došli podržati našu
{90294}{90351}Akeelah Anderson!
{90574}{90606}Hvala vam!
{90657}{90693}Hvala vam mnogo!
{90819}{90910}Sad si poput filmske zvijezde! | - Znam. Ludo je.
{90915}{90984}Moja je mama predložila da odemo | danas nekamo proslaviti.
{91020}{91105}Javierovi roditelji me vode van. | Ali možda bismo mogli...
{91110}{91183}Isprièavam se. Ovdje je novinar | koji bi htio prièati s tobom.
{91187}{91247}Ne želim. | - Šališ se?
{91251}{91334}Škola Crenshaw vapi | za ovakvim publicitetom.
{91338}{91389}Isprièavamo se. | Samo malo.
{91422}{91487}Dobar dan, ja sam Lauren i | javljam se iz Los Angelesa.
{91490}{91535}Sa mnom je | Akeelah Anderson.
{91540}{91628}Pohaða 7. razred Crenshaw | škole, izborila se za državno
{91632}{91726}u slovkanju. Kako se osjeæaš | prije odlaska u Washington?
{91730}{91788}Prilièno je zabavno. | - Jesi li uzbuðena?
{92255}{92327}Slovkaj mi affenpinscher! | - Affen-što?
{92331}{92437}Grallatorial! | - G-R-A-L-A-T...
{92441}{92496}Krivo! | Jacquard!
{92501}{92569}Dr. Larabee? | - Slovkaj! Jacquard!
{92596}{92687}J-A-Q... | - A što je sa C?
{92693}{92785}To su sve promašene rijeèi | s prošlogodišnjeg natjecanja.
{92789}{92825}Nisi u stanju odslovkati | nijednu od njih!
{92828}{92867}Jer nismo nauèili | nijednu od njih!
{92870}{92963}Zašto si odustala juèer? | Zbog još jednog intervjua?
{92967}{93049}Blesirala si se na TV-u? | - Ne. Išla sam kupovati.
{93071}{93170}Nisam vas brukala! | Išla sam u božiænu kupovinu.
{93175}{93306}Zar tu ne koristimo samo | književne rijeèi?
{93507}{93634}Brukati - tretirati nekoga loše.
{93640}{93722}Nove rijeèi dolaze | u rjeènik svake godine.
{93873}{93993}Slušaj... meni nije uspjelo doæi | do državnog natjecanja prije 14.
{93997}{94091}Bio sam bez mentora, treninga... | Nisam imao ništa!
{94095}{94182}Dogurao sam do treæeg | kruga i ispao.
{94186}{94301}Ti imaš veliku priliku | da osvojiš tu stvar.
{94353}{94436}Ali sve što smo radili | u ovih 8 mjeseci
{94440}{94610}bilo je uèenje rijeèi! | Zašto se ne bi malo zabavili?
{94617}{94707}Rekao sam ti veæ, Denise. Možeš | se zabavljati nakon natjecanja.
{94751}{94821}Tko jeDenise? | - Što?
{94843}{94910}Denise, tako ste me nazvali. | Tko je to?
{94991}{95026}Dr. Larabee, sve u redu?
{95103}{95194}Da. Sve je u redu.
{95298}{95407}Cijeli prošli tjedan | proveo sam na ovom ovdje.
{95422}{95490}Što je to? | - Kartice, 5000 komada.
{95494}{95559}Vrste rijeèi koje bi se | mogle pojaviti u finalu.
{95563}{95642}Pet tisuæa? | Imamo svega nekoliko mjeseci.
{95646}{95782}Zar æemo raditi po cijele dane? | - Ne. Spremat æeš se sama.
{95797}{95935}Više te nemam èemu nauèiti. | - Što?
{96009}{96158}Sve si shvatila, Akeelah. | Konstrukciju, etimologiju...
{96164}{96294}Sada se trebaš | usredotoèiti na rijeèi.
{96313}{96394}Nema šanse da svladam | toliko puno rijeèi sama!
{96398}{96498}Možeš ti to. Tvoj je mozak | poput spužve. Samo budi uporna.
{96502}{96640}Dr. Larabee, prisežem, | neæu više izostati ni jednom!
{96646}{96700}Ne možete mi u ovom | trenutku prestati biti mentorom!
{96705}{96757}Pristao sam te voditi do | regionalnog natjecanja.
{96761}{96844}Jesam. | Nemam te više èemu uèiti.
{96847}{96951}Svladaj te rijeèi | i sve æe biti u redu.
{97229}{97290}Radi ovoga sam | bila u kupovanju.
{97368}{97400}Sretan Božiæ...
{97883}{97931}Halo? | - Hej, mala!
{97935}{98013}Što radiš? | - Gledam TV.
{98045}{98127}Idemo skupa rolati ovaj vikend? | - Zašto ne odeš sa svojim
{98131}{98268}novim prijateljicama? | - Molim? Što je s tobom?
{98273}{98387}Ništa. Imam domaæu | zadaæu. Vidimo se.
{98581}{98673}Keelie! Požuri! | Na TV-u si!
{98679}{98773}Akeelah Anderson je | postala nova zvijezda.
{98778}{98829}Cijeli grad prièa o njoj.
{98834}{98919}Pobijedi li na državnom, | cijelo æe naselje slaviti!
{98923}{99052}Njezin æe nastup | pozitivno utjecati na sve nas.
{99058}{99117}Veæ se pripremam za | natjecanje iduæe godine!
{99247}{99345}Akeelah? Što je bilo? | - Ne želim više biti u tome.
{99349}{99475}Zašto? - Dr. Larabee mi više | ne želi biti mentor.
{99488}{99540}Georgia se više | ne želi družiti sa mnom,
{99544}{99630}a svi ovi ljudi | oèekuju da pobijedim.
{99634}{99731}Jednostavno je preteško. | Želim da sve prestane.
{99735}{99779}Dušo, radila si tako... | - Molim te.
{99783}{99838}Molim te. | - U redu.
{100080}{100143}Nisam je mislio uzrujati.
{100199}{100315}Iskreno sam mislio da | radim najbolju stvar za nju.
{100562}{100699}Znate, dr. Larabee, | mojem je djetetu svega 11 g.
{100711}{100792}I prošla je kroz | mnogo toga do sada.
{100798}{100848}Otac joj je ubijen | kad joj je bilo 6 g.
{100853}{100921}Netko ga je upucao | kad se vraæao s posla.
{100927}{101022}Znate li kako se mogla osjeæati?
{101120}{101155}Mogu zamisliti.
{101174}{101259}Zašto onda želite | rastužiti dijete još više?
{101263}{101325}To je nepoštena optužba, | gðo Anderson.
{101330}{101507}Ne mogu joj više | nikako pomoæi.
{101511}{101592}Ali ona vas treba. | Doista vas treba.
{101597}{101679}Ne slažem se, gðo Anderson. | Akeelah ne treba mene.
{101789}{101845}Sjeæam se kad nas je | vodio na utakmice,
{101849}{101940}u kino i kad smo se | gaðali kokicama.
{102054}{102090}Želim ti nešto reæi.
{102198}{102288}Znaš zašto nisam željela da ideš | na natjecanje od poèetka?
{102294}{102423}Zato što sam vidjela tvoju vrpcu | s pobjednikom i 200 gubitnika.
{102429}{102511}I nisam željela da budeš | jedna od tih gubitnika.
{102541}{102614}Jesi li znala da ti je mama | po svršetku srednje škole
{102618}{102689}upisala fakultet? | - Ne.
{102721}{102815}Imala sam školarinu. | Išla sam za lijeènicu.
{102865}{102898}Što se dogodilo?
{102980}{103064}Osjeæala sam | da ne pripadam toj školi.
{103086}{103186}Uvjerila sam samu sebe | da æu pasti.
{103232}{103323}Ispisala sam se jer nisam | htjela da se to ostvari.
{103342}{103427}Ne želim da uèiniš isto | s ovim natjecanjem.
{103727}{103858}Gabbro, skupina | tamnih teških kamena.
{103910}{103955}Možeš li je slovkati za mene?
{103999}{104048}G-A...
{104064}{104137}...B- R-O. | Gabbro?
{104160}{104211}Zapravo ima dva B.
{104297}{104402}Znaš, ne manjka ti | ljudi koji ti žele pomoæi.
{104406}{104527}Kladim se da postoje tisuæe | mentora koji bi ti pomogli.
{104531}{104572}Poèevši od mene.
{104655}{104794}Mama, misliš li da bi se | mogla vratiti na fakultet?
{104896}{104941}Mogla bih.
{105024}{105096}Volim te. | - I ja tebe.
{105110}{105207}Krakulur. | K-R-A-K-U-L-U-R.
{105211}{105282}Hej! | Zašto se bojiš natjecanja?
{105286}{105344}Što, sada se bojiš klinaca | iz predgraða?
{105347}{105378}Ne.
{105457}{105501}Kako uopæe slovkaš | sve te rijeèi?
{105505}{105612}Uèim ih. | - Što god. Evo mi prijevoza.
{105656}{105750}Hej, što ima, Derrick-T? | - Što ima, Terrence? Tko je to?
{105769}{105821}Nitko, samo moja | mlaða sestra.
{105825}{105906}Što ima, malena? | Vidio sam te na TV-u.
{105910}{105979}Pokušavaš pobijediti na nekom | velikom natjecanju, ha?
{105984}{106023}Odgovori èovjeku.
{106032}{106082}Znaš, ja sam jednom | nešto osvojio...
{106085}{106165}U petom razredu. | Napisao sam pjesmu.
{106169}{106230}Èak sam dobio | i plavu vrpcu.
{106245}{106325}Da, dobro. Napisao si si pjesmu. | - Šuti, stari.
{106330}{106385}Što ti misliš da je rap?
{106402}{106497}Što to imaš u ruci? | - Ništa, samo neku glupu rijeè.
{106502}{106597}Pomažeš joj? | - Ne, tu sam s tobom...
{106715}{106847}Ne, èovjeèe. | Ostani ovdje i pomogni sestri.
{106851}{106910}Zašto? | - Zato što sam ti ja tako rekao.
{106925}{106959}Idemo, èovjeèe.
{107032}{107106}Derrick-T! | - Što je?
{107138}{107182}Želim proèitati | tvoju pjesmu.
{107204}{107307}Nakon što osvojiš natjecanje. | Idemo, èovjeèe.
{107419}{107476}Ne moraš mi pomoæi | ako ne želiš.
{107565}{107626}Os-Iob-oðe-nje?
{107632}{107727}Misliš osloboðenje? | - Hej, štogod. Možeš li slovkati?
{107850}{107895}50000 trenera.
{107984}{108028}O-S-L...
{108395}{108424}Ap-ter-igo-t.
{108428}{108483}Što? | - Ova ovdje.
{108487}{108557}Apterigot. Možda mi ne bi | trebao pokazivati kartice.
{108560}{108601}O, da. Oprosti.
{109292}{109326}Naprijed, Akeelah, dušo! | Uèini nas ponosnima!
{109971}{110039}5000, nauèila sam ih sve.
{110050}{110088}Ali imala sam neku pomoæ.
{110115}{110164}Onda bi trebala biti | baš dobro pripremljena.
{110238}{110291}Znate, dr. Larabee,
{110295}{110407}kad sam bila curica, | moj tata je poginuo.
{110536}{110584}Plakala sam cijelo vrijeme.
{110649}{110762}Ali onda... pronašla sam | nešto što mi je pomoglo.
{110805}{110868}Što to? | - Slovkala sam...
{110888}{110959}Slovkala sam cijelo vrijeme. | I osjeæala bih se bolje.
{111066}{111131}Možda kad vi | razmišljate o njoj...
{111152}{111194}Možete pokušati slovkati.
{111221}{111259}Moglo bi pomoæi.
{111635}{111662}Akeelah?
{111758}{111832}Tko ti je rekao? | - Upravo vi.
{111851}{111914}Nazvali ste me | njezinim imenom: Denise.
{112085}{112173}To je njezino uže, zar ne? | - Da.
{112264}{112303}Je li ona bila vaša curica?
{112434}{112462}Da.
{112536}{112577}Što joj se dogodilo?
{112808}{112852}Jako se razboljela.
{112898}{113009}Bila je samo par godina | mlaða od tebe kad je umrla.
{113149}{113187}Gdje joj je mama?
{113242}{113293}Preselila se u drugi grad i...
{113338}{113387}Nakon što se to dogodilo...
{113414}{113510}Moja žena Patricia i ja...
{113557}{113668}Shvatili smo... polagano...
{113707}{113806}Da je veoma teško ostati...
{114032}{114147}Bilo kako bilo, | ovo je Patricijin vrt.
{114220}{114326}Znaš... trebam puno | reda u svom životu.
{114339}{114402}Zato više ne predajem | po školama.
{114439}{114485}To je previše nepredvidljivo.
{114516}{114554}Kao i s tobom...
{114566}{114627}Sve ovo s natjecanjem | je postalo...
{114659}{114708}Malo nepredvidljivo.
{114852}{114881}Dr. Larabee...
{114935}{115014}Ne mogu iæi u | Washington bez vas.
{115018}{115084}Možeš, Akeelah. | Možeš uèiniti sve što želiš.
{115088}{115145}Ne mogu pobijediti Dylana. | - Nemoj to govoriti.
{115149}{115180}Istina je.
{115184}{115288}Bez obzira koliko rijeèi nauèila | on æe uvijek znati više.
{115293}{115340}Reæi æu ti nešto o Dylanu.
{115382}{115453}Postoji samo jedna osoba | koja ga može natjerati
{115457}{115538}da slovka najbolje | što može.
{115543}{115633}To nije njegov otac. | Nisu ljudi s natjecanja.
{115637}{115680}Nije ni on sam.
{115687}{115742}Ta osoba si ti.
{115767}{115877}Pa... kad ti i ja
{115886}{115938}doðemo u Washington,
{115957}{116035}potrudimo se da ga | natjeramo do kraja.
{116050}{116084}U redu?
{116566}{116650}Hej. | - Bog.
{116691}{116789}Sutra idem u Washington. | - Da, dobro, zabavi se.
{116801}{116839}Žao mi je što sam bila | toliko zauzeta.
{116843}{116917}Sve ovo s natjecanjem | zbilja je bilo napeto.
{116932}{116967}Ali znaš što?
{117018}{117094}Svega bih se toga odrekla | zbog našega prijateljstva.
{117099}{117155}To je glupo. | - Zašto je glupo?
{117159}{117229}Zato što ljudi žele | da budeš dobra.
{117268}{117319}Ja želim da budeš dobra.
{117376}{117461}Znaš što? Georgia, ti si | moja najbolja prijateljica.
{117465}{117569}Uvijek si uz mene, èak i | kad se osjeæam nesigurno.
{117574}{117633}Ali moram ti reæi nešto.
{117636}{117729}Ako želiš biti stjuardesa, | prvo se moraš voziti u avionu.
{117733}{117829}Hoæu jednog dana. | - Što kažeš na sutra?
{117973}{118045}Moram prièati s kapetanom.
{118056}{118126}Zaboravi na stjuardesu. | Bit æu pilot.
{118163}{118240}Što je s njim? | - Boji se visine.
{118245}{118333}Bojim se povraæanja. | Mogao bih povraæati.
{118338}{118452}Moj brat je u zraènim snagama | i on kaže da je strah u glavi.
{118474}{118581}Dao mi je ovo za sreæu. | Ne brini se... neæu te ubosti.
{118597}{118686}Znaš, nikad ti nisam zahvalila | za pomoæ na državnom natjecanju.
{118690}{118803}Nema beda. - Zapravo, | bilo je baš kavalirski.
{118898}{119026}Sad ne razmišljam o avionu. | - Pa, u tom sluèaju...
{120080}{120143}Rekla samti da ga ne treseš. | - Žao mi je.
{120147}{120195}Mislila sam | da ste trebali uèiti.
{120199}{120223}Uèimo.
{120227}{120299}Zvuèi kao da je zabava ovdje. | Hajde, sutra imaš veliki dan.
{120302}{120344}Bolje da završite. | - Još pola sata.
{120348}{120377}15 minuta.
{120420}{120457}Što misliš da | Dylan sada radi?
{120462}{120514}Pokušava nauèiti drevni grèki.
{120518}{120597}Trebali bismo ga pozvati. | - Tog nevaljalca? Zaboravi.
{120623}{120650}Vratit æu se.
{120728}{120762}Je li Dylan ovdje?
{120836}{120868}Zauzet je.
{120893}{121012}Pa... nekoliko nas se | druži u mojoj sobi.
{121015}{121111}Pijemo sok i gledamo filmove. | Možda bi volio doæi?
{121117}{121177}Žao mi je, ali sutra | je natjecanje.
{121181}{121309}Treba uzeti malo | odmora prije velikog dogaðaja.
{121321}{121386}To je možda tvoja strategija, | ali nije naša.
{121415}{121509}Èekajte! | Ovo je za Dylana.
{121675}{121700}U redu.
{121768}{121872}Naš najdublji strah nije | to što smo nedorasli.
{121881}{121952}Naš najdublji strah | je da smo snažni
{121956}{121997}preko granica.
{122021}{122060}Pitamo sami sebe
{122064}{122159}Tko sam ja da budem | briljantan, prekrasan,
{122163}{122226}nadaren i nevjerojatan?
{122247}{122352}Zapravo, tko si ti | da ne budeš?
{122749}{122856}NACIONALNO NATJECANJE | U SLOVKANJU
{123643}{123706}Ja sam Ted Saunders, ovdje sam | s Katie Kerwin-McCrimmen,
{123710}{123817}javljamo se iz glavne dvorane | u Grand Hyattu u Washingtonu.
{123821}{123896}Katie, kao bivša prvakinja u | slovkanju, što misliš od koga bi
{123900}{123958}trebali oèekivati iznenaðenje | na ovogodišnjem natjecanju?
{123962}{124031}Par klinaca je bilo visoko | plasirano na prošlom natjecanju,
{124035}{124068}posebno Dylan Chiu.
{124072}{124131}On je bio drugi | dvije godine za redom.
{124135}{124220}Izlemaj mu guzicu, Akeelah! | G-U-Z-I-C-U, guzicu.
{124224}{124297}...ali slovkar kojega æu pratiti | mala je Akeelah Anderson
{124300}{124385}iz Los Angelesa. Ona je postala | mala medijska senzacija
{124389}{124452}zato što joj je samo 11 g... | - To je moja sestra!
{124455}{124522}...a ovo je njezin prvi pokušaj | na natjecanjima u slovkanju.
{126104}{126157}Možete li ponoviti rijeè, molim?
{126162}{126232}Argumentirati.
{126248}{126292}Kakva je to rijeè?
{126300}{126360}A-R-G-U...
{126364}{126438}...M- E-N-T...
{126442}{126530}...I-R-A-T-I. | Argumentirati.
{126535}{126568}Toèno!
{126586}{126613}Da.
{126694}{126764}Za 11-godišnje dijete, | to je jednostavno nevjerojatno.
{126768}{126846}Ali pazi... | jedno krivo slovo i to je to.
{126890}{126927}Oersted.
{126932}{126997}Koji je izvorni jezik? | - To je iz danskog imena.
{127001}{127083}Ne podnosim ovog Korejanca. | - On je Kinez. - On je arogantan.
{127088}{127139}O-E-R-S-T-E-D.
{127143}{127176}Toèno!
{127358}{127433}Koje je objašnjenje? | - Xylem je kompleksno tkivo
{127437}{127500}u vaskularnom sustavu | viših biljaka.
{127505}{127561}Xylem. | X-Y-L-E-M
{127565}{127622}Xylem. | - Toèno.
{127727}{127804}Mislili su da me imaju, | ali sam malo previše za njih.
{127821}{127897}...E-P-I-J-A.
{127901}{127946}Ortoepija. | - Toèno!
{127969}{128039}Flokulacija je iz latinskog. | - Možete je uporabiti u reèenici?
{128043}{128096}Flokulacija. | - Može objašnjenje?
{128100}{128145}Toèno. | - Lobscouse.
{128149}{128224}Izvorni jezik, molim. | - Ima li kakav drukèiji izgovor?
{128228}{128282}Gastromit. | - Može objašnjenje?
{128330}{128381}Latinski. | - Eskarotièno.
{128399}{128444}Madrigal. | - Toèno!
{128448}{128506}Može objašnjenje? | - Iz najranijega doba.
{128510}{128548}Aboriðinski. | - Toèno!
{128552}{128628}Izvorni jezik? | - Empleomanija.
{128649}{128718}Bilo kakav odnos bez | odvajanja dvije fraze.
{128722}{128783}...J- E-Š-A-N, | Izmiješan.
{128787}{128851}Ako ste se tek sad prikljuèili, | u 8. smo krugu
{128854}{128949}državnog natjecanja u slovkanju, | a ostalo je samo 30 slovkara.
{128953}{129009}...U... R...
{129020}{129088}...S- U-S. | Ekscursus.
{129173}{129211}Glinasto.
{129218}{129291}Oprostite? | - Glinasto.
{129298}{129348}Može objašnjenje?
{129353}{129479}Glinasto znaèi, odnosi se | nalili sadrži glinu.
{129484}{129540}Izvorni jezik? | - Latinski.
{129544}{129616}Èovjeèe, to je bjelaèka rijeè. | To je zamka... prestani igrati.
{129621}{129683}Sufiks koji bi | preplašio veæinu ljudi.
{129686}{129733}Oni ga nastoje | slovkati T-I-O-U-S
{129737}{129772}ili C-I-O-U-S.
{129776}{129859}Potjeèe li od latinske rijeèi | argilla što znaèi glina?
{129863}{129893}Tako je.
{129995}{130094}A-R-G...
{130115}{130159}...I-L...
{130172}{130235}...L-A...
{130331}{130359}Hajde.
{130686}{130742}Mogu ispoèetka? | - Možeš.
{130746}{130821}Ali ne možeš promijeniti slova | koja su veæ reèena.
{131236}{131356}A-R-G-I-L-L...
{131361}{131491}A-C-E-O-U-S.
{131498}{131560}Argillaceous. | - Toèno!
{131734}{131787}Pogodila je! | To je moja mala sestra!
{132176}{132273}Ovo je 12. krug ljudi, | a pet preostalih slovkara -
{132277}{132321}Mary Calveretti, 12 godina,
{132325}{132369}13-godišnji Rajeeve Subramonian,
{132373}{132470}12-godišnji Javier Mendez, | Dylan Chiu, takoðer iz Hillsa.
{132474}{132512}Stvarno ih tamo uèe | kako treba!
{132516}{132555}I naravno, | Akeelah Anderson.
{132626}{132685}Možete li upotrijebiti | rijeè u reèenici?
{132689}{132789}Merovinški kraljevi su bili | poznati po crvenoj kosi.
{132794}{132821}U redu.
{132870}{132980}M-A-R...
{132990}{133076}...O-V-I-N...
{133080}{133155}...G-Š-K-I.
{133158}{133194}Merovingški.
{133276}{133407}Merovinški se piše | Merovinški.
{133644}{133689}Zaboravio sam | slovkati kako zvuèi.
{133693}{133784}13. prošle godine, 5. ove, | iduæe godine idem do kraja.
{133789}{133820}Sad je tvoj red.
{134010}{134078}...Z-A-M, Mitridatizam.
{134113}{134194}...P-I-S-C-N-C-E, | Resipiscence.
{134198}{134218}Toèno!
{134223}{134309}...F-I-R-E? | Vitrophyre?
{134349}{134430}...G-I-N-O-U-S. | Serpiginous.
{134435}{134485}Toèno. | - To!
{134563}{134596}To je moja mala.
{134786}{134853}Uzet æemo mali predah | prije nego li Akeelah i Dylan
{134857}{134918}zapoènu sa svojim | rijeèima za naslov.
{135328}{135373}Prilièno dobro, ha?
{135549}{135625}Pobrini se da ostaneš | usredotoèen, dobro?
{135640}{135714}Ovo je tvoje posljednje | natjecanje u slovkanju.
{135718}{135818}Ako izgubiš od te curice, | bit æeš drugi cijeli život.
{135822}{135907}Nema šanse! Èuješ me? | Nema šanse!
{135911}{136019}Promatraš nekoga? | - Samo želim Dylanu sreæu.
{136024}{136096}Napravila si sjajan posao. | Tako sam ponosan na tebe.
{136100}{136207}Slušaj, probat æe te pogoditi | svim trik rijeèima koje imaju.
{136211}{136262}Samo se sjeti stvari | koje smo uèili.
{136266}{136340}Možeš rastaviti te rijeèi èak | i ako ih nikad nisi vidjela?
{136347}{136432}Ali ako ne pobijedim Dylana, | imam iduæu godinu?
{136436}{136493}Naravno. | Iako ne znam koliko æemo
{136497}{136550}vremena imati | da uèimo zajedno.
{136554}{136658}Zamoljen sam da se vratim i | predajem na UCLA i pristao sam.
{136665}{136736}Zbilja? | - Ne želim uskratiti sljedeæeg
{136740}{136878}Duboisa povlastica mojih | dosjetki i gorkih primjedaba.
{137113}{137196}Što je? | - Ništa, dr. Larabee.
{137209}{137312}Morala bih se vratiti. | Bez obzira što se dogodi...
{137349}{137454}Znajte da nisam mogla | ovako daleko bez vas.
{137499}{137555}Akeelah, dušo, tu si. | Hajde.
{137560}{137662}Moram iæi. | - Opet æe poèeti.
{137952}{138049}Nemoj izgledati tako nervozno. | Imala je dobrog trenera.
{138101}{138206}Upravo sam saznala da su samo | dvije avionske karte po djetetu.
{138211}{138286}Pitam se kako smo | mi završili sa šest.
{138333}{138445}Možda zbog nekakve neoèekivane | darežljivosti natjecanja.
{138496}{138611}Ili je možda Akeelin trener | prilièno darežljiv.
{138704}{138838}Hvala ti na svemu. | - Nema na èemu.
{138865}{138961}Dame i gospodo, pozdravimo | Akeelah i Dylana!
{139003}{139060}Zapamtite, ako bilo koji | slovkar promaši rijeè,
{139064}{139161}drugi mora slovkati tu promašenu | rijeè i jednu svoju da pobijedi.
{139165}{139188}Toèno? | - Tako je.
{139192}{139273}Mogli bi iscrpiti svih | 25 rijeèi za naslov.
{139277}{139313}Ali to se nikad | nije dogodilo.
{139316}{139374}Rijeèi za naslov | jednostavno su preteške.
{139378}{139451}Filiopietistic. | - Objašnjenje?
{139455}{139579}Odnosi se na pretjerano | obožavanje predaka i kulture.
{139584}{139665}Filiopietistic. | F-I...
{139696}{139749}...L-I...
{140228}{140271}Akeelah, ti si na redu.
{140444}{140480}Xanthosis.
{140495}{140567}Xanthosis? | - Poèinje s X.
{141041}{141076}Gðice Anderson?
{141279}{141406}Xanthosis | Z-A-N...
{141413}{141455}...T-H-O...
{141479}{141576}...S- I-S. | Xanthosis
{141965}{142009}Dylan, ti si na redu.
{142556}{142630}Xanthosis | X-A-N...
{142660}{142728}...T-H-O-S...
{142820}{142884}...E-S. | Xanthosis.
{142985}{143023}Xanthosis se piše
{143027}{143061}X-A-N...
{143065}{143141}T-H-O-S-I-S.
{143212}{143259}Mogu li dobiti vode, molim?
{143263}{143313}Možemo li dati | slovkarima malo vode?
{143467}{143525}Što radiš? | - Što ti radiš?
{143529}{143585}Bacila si tu rijeè. | - I ti si.
{143590}{143691}Samo æeš sve ovo odbaciti? | - Tvoj tata æe biti sretan.
{143723}{143803}Koga briga? On nikad ništa nije | osvojio u svom životu.
{143807}{143860}Ja sam osvojio regionalno | tri puta za redom.
{143864}{143931}I završio dvaput | drugi na državnom.
{143935}{144021}A sad možeš završiti prvi. | Ja mogu druge godine.
{144025}{144119}Daj najbolje od sebe ove godine. | - Dylane... - Daj najbolje...
{144152}{144195}ili ja to ne želim.
{144213}{144252}Evo vaše vode.
{144425}{144542}Prilièno nevjerojatno, | da su oboje pali na toj rijeèi.
{144546}{144592}Imamo nekakvu | jako nervoznu djecu tamo.
{144618}{144701}Effleurage ili effleurage!
{144819}{144884}E-F-F-L-E-U...
{144888}{144966}...R-A-G-E | Effleurage.
{144978}{145009}Toèno!
{145080}{145142}Ovo je kao da gledate | dvije zvijezde tenisa
{145145}{145239}kako na mreži izmjenjuju voleje. | Ova djeca su nevjerojatna!
{145243}{145334}Lagniappe: L-A-G-N-I-A-P-P-E | Lagniappe.
{145338}{145381}Sumpsimus. - Možete li je | upotrijebiti u reèenici?
{145385}{145417}Je li to glagol? | - Ofelimiti.
{145421}{145458}Tralaticijski! | - Toèno.
{145462}{145495}Sophrosyne. | - Parrhesia.
{145499}{145536}Je li to grèki? | - Je li to bio latinski?
{145540}{145571}Koji je izvorni... | ...jezik, molim?
{145574}{145604}Lyophilize. | - Zarzuela.
{145607}{145631}Vibrissae. | - Craquelure.
{145635}{145667}Toèno!
{145680}{145748}Ova djeca žvaèu ove | super-teške rijeèi
{145752}{145792}kao da su pahuljice | za doruèak.
{145796}{145923}Znate, mogli bi iæi do kraja, no | veæina to smatra nezamislivim.
{145928}{146004}Sad smo na 13. rijeèi | u krugu za prvaka.
{146008}{146106}Ako proðete kroz posljednjih 12, | bit æete zajednièki prvaci.
{146111}{146161}To se nije nikad | prije dogodilo.
{146169}{146202}Vinegarroo. | - Ecdysis.
{146206}{146236}Concitato. | - Puerpera.
{146240}{146269}Toèno!
{146293}{146349}Dylan i Akeelah pokušavaju | izvesti èudo.
{146352}{146428}I da stignu do cilja, trebaju | jedan drugog za uspjeh.
{146432}{146497}...E-R-A-Z...
{146657}{146746}...A-D-I-A-N. | Šeherazadijan.
{146751}{146779}Toèno!
{146864}{146938}...L-O-G-I...
{146972}{147076}...È- K-I | Palinologièki.
{147080}{147114}Toèno!
{147259}{147371}Dame i gospodo, došli smo do | zadnje dvije rijeèi za naslov.
{147375}{147486}Jedan ili oboje naših slovkara | osvojit æe prvo mjesto!
{147493}{147535}Dylan, ti si na redu.
{147707}{147785}Logorija. | - Objašnjenje, molim!
{147800}{147916}Logorija je pretjeran | i èesto nerazgovijetan govor.
{148073}{148114}Logorija.
{148175}{148198}L...
{148241}{148264}...O...
{148283}{148333}...G-O...
{148388}{148410}...R...
{148434}{148482}...I-J...
{148500}{148583}...A. | Logorija?
{148608}{148648}Èestitam, Dylan!
{148652}{148722}Osvojio si Scrippsovo državno | natjecanje u slovkanju.
{148726}{148803}To! To!
{148914}{148945}Sredi ih.
{149081}{149171}Dame i gospodo, molim vas, | sjednite zbog Akeelinog reda.
{149316}{149366}Pulchritude.
{149382}{149422}Pulchritude.
{149560}{149692}Potjeèe od latinske rijeèi | pulcher što znaèi prelijepo,
{149714}{149760}zar ne? | - Tako je.
{149789}{149828}...P... | ...U...
{149833}{149864}...L... | ...C...
{149868}{149894}...H... | ...R...
{149899}{149929}...I... | ...T...
{149934}{149969}...U... | ...D...
{149975}{150025}...E. | - Pulchritude.
{150112}{150153}Èestitam, Akeelah!
{150279}{150316}O tome ti ja prièam!
{150393}{150468}Znate li onaj osjeæaj | se sve osjeæa na mjestu?
{150472}{150571}Kad se ne morate | brinuti o danas ili juèer
{150577}{150680}ali osjeæate se sigurno i | radite najbolje što možete?
{150692}{150740}Postoji rijeè | za taj osjeæaj.
{150752}{150783}Zove se ljubav.
{150803}{150868}L-J-U-B-A-V.
{150881}{150947}To je ono što osjeæam | prema cijeloj obitelji,
{150952}{151037}i svim svojim trenerima | u svojem susjedstvu,
{151041}{151156}otkuda dolazim, gdje sam | nauèila slovkati.
{151631}{151664}Uspjeli smo.
{151980}{152080}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan  
{152720}{152793} 
