{1}{1}25.000
{1269}{1355}Stifleru, kako to da je Steve | pokupio sve najbolje u vašoj obitelji?
{1357}{1441}- Popuši mi, drkadžijo. | - Daj, stari, to ti nedostaje.
{1446}{1525}Vidio sam to milijun puta, glupavi šupèino.
{1527}{1619}- Matte, Steve je poput filmskog genija. | - Pravi amerièki heroj.
{1621}{1658}Tarantino za sisice.
{1660}{1717}Nema šanse da æeš ti ikada biti tako dobar.
{1719}{1756}Dokazat æu Steveu...
{1758}{1834}da sam dorastao standardima | Stiffmeisterove produkcije.
{1847}{1900}Kad Steve vidi moj redateljski talent...
{1902}{1985}- mlaði brat upada u obiteljski biznis. | - To je on rekao?
{1987}{2087}- Konaèno te nazvao? | - Nije, ali ostavio sam mu drugu poruku.
{2126}{2205}Javit æe mi se. Prošla su samo tri tjedna.
{2234}{2359}Gospodo jebaèi, zdravica. | Od sutra smo maturanti.
{2516}{2585}SREDNJA ŠKOLA EAST GREAT FALLS | NAPRIJED MATURANTI
{2594}{2628}SRETNO!
{2632}{2665}Upišite se na LJETNE TEÈAJEVE
{2667}{2716}NAPRIJED! - GENERACIJA 2005
{3844}{3901}Odmorimo se, ljudi.
{3910}{4014}Zapamtite, ovo sviramo na kraju, | nakon Pomp and Circumstance.
{4016}{4070}Neæu da netko poène svirati | pogrešnu pjesmu.
{4072}{4143}- Elyse, opusti se, djevojko. | - Dobro sam.
{4151}{4221}Samo sam... Prvi sam put ovdje i...
{4223}{4288}Ovo je matura, nije Boston Pops orkestar.
{4290}{4367}Ova æe izvedba odrediti | cijelu našu maturantsku godinu. Mislim...
{4369}{4482}Vidi, svi se ovdje zaista trude radi tebe.
{4579}{4642}Glupan. Tupan. Kreten. Guska.
{4665}{4752}- Sviðaju mi se kad su živahni. | - Što ti radiš ovdje?
{4754}{4817}Želimo samo reæi sayonara, | i dati vam do znanja...
{4819}{4937}da planiramo osvojiti državni naslov | sada kad je Stiffmeister glavni.
{4939}{5035}- Adiós, seronjo. | - Veæi je šupak od svog brata.
{5121}{5165}Sveca mu, Arrianna.
{5186}{5240}Matte, što ti radiš ovdje?
{5243}{5345}Samo bismo htjeli da | maturanti imaju nezaboravan zadnji dan.
{5347}{5418}Super. Dakle, veèeras imamo kampiranje...
{5420}{5494}samo za maturante, ali vi možete doæi.
{5496}{5560}Samo da si provjerim raspored. OK.
{5591}{5683}Ponesite vreæe za spavanje, | u sluèaju da odluèimo razapeti šator.
{5801}{5895}- Vidi ovo. Baš u pravo vrijeme. | - Bit æe super.
{5909}{5990}Vrijeme je za poèetak akcije Matu-fuk-iranje.
{6055}{6101}Bit æe ludilo.
{6103}{6147}- Sranje. | - Glavni zgoditak!
{6155}{6248}Naplata, maturanti. | Nemojte si time posprejati ruke, peèe.
{6321}{6391}Maturalni dar od Stiffmeistera.
{6411}{6474}BIVŠI UÈENICI ŠKOLE ÈESTITAJU | Generaciji 2005
{6476}{6537}Stari, trebali smo nasprejati diplome.
{6593}{6630}Oprostite, bendiæi.
{6754}{6844}Ugrizi me za jaja i nazovi me Skippy. | Pa to je Steely Dan.
{6850}{6928}- Što? | - Dvoglavi vibrator.
{6945}{6987}Vibrator. To je vibrator.
{6996}{7050}- Èovjeèe. | - Èak ima i ime.
{7091}{7116}Picardo?
{7125}{7200}- Nasprejaj to. | - Neæu. Tko ga naðe, njegov je.
{7206}{7288}Ok, narode, Pomp and Circumstance. | Pet minuta do poèetka. Idemo.
{7290}{7346}Bendiæi. Brišimo odavde.
{7445}{7494}- Matte? | - Leesy.
{7531}{7602}Kako su one? Još uvijek male i drske, vidim.
{7604}{7662}- To je smiješno. | - Da.
{7687}{7783}- Što radiš ovdje, Matte? | - Došao sam ti zaželjeti sreæu.
{7785}{7846}- Za glazbenu izvedbu. | - Sreæu?
{7848}{7915}Nisi mi se obratio od osmog razreda.
{7917}{7990}Upravo zbog ovakvog tona.
{7992}{8049}Idem ja sad.
{8143}{8247}Dame i gospodo, | ustanimo u èast naših maturanata.
{8249}{8295}Douchebag æe ovo propustiti.
{8595}{8627}Da.
{8707}{8747}Plaèu li?
{8812}{8846}Ti bokca!
{9008}{9037}Da!
{9552}{9594}Jedite govna, maturanti.
{10110}{10165}Stifleru!
{10179}{10227}PSIHOLOG SAVJETNIK
{10229}{10317}Dugo sam èekao na ovo.
{10347}{10414}Danas je stigao dan obraèuna.
{10492}{10529}Bog, Matthew.
{10542}{10599}Brat ti je sigurno vrlo ponosan.
{10663}{10717}Nastavio si njegovu ostavštinu.
{10741}{10793}Muèenje nedužnih...
{10808}{10882}blaæenje sveg dobrog i èistog.
{10964}{11029}Ali sad æeš biti uništen.
{11055}{11132}A što æeš, protjerati me, Shermanatoru?
{11165}{11236}Ja sam sofisticirani stroj za savjetovanje...
{11238}{11328}vratio sam se u vremenu | kako bih vodio mlade i nevine umove.
{11337}{11457}Moja je prva zapovijed | zaštiti uèenike ove institucije...
{11478}{11547}te sve, èovjeèanstvo...
{11565}{11635}od napasti koja je drugi Stifler.
{11640}{11702}Potrebna je promjena ponašanja.
{11710}{11778}Još nije kasno promijeniti tvoju buduænost.
{11844}{11939}Ne, izgnanje bi bilo prejednostavno.
{12016}{12094}Znam savršenu kaznu za tvoj zloèin.
{12154}{12229}Buduæi da imaš toliko problema s bendom...
{12233}{12298}možda biste se trebali sprijateljiti.
{12300}{12340}Nema šanse.
{12384}{12495}Ili æeš nauèiti biti obzirniji | ili æeš biti izopæen.
{12515}{12551}Nema nogometa.
{12574}{12603}Nema zabava.
{12605}{12649}Nema proljetnih praznika.
{12667}{12729}Nema mature.
{12737}{12776}Nema faksa.
{12778}{12819}Nema studentica.
{12840}{12874}Comprende?
{12987}{13036}Pakuj se, Stifleru.
{13049}{13116}- Ideš u Glazbeni kamp. | - Glazbeni kamp!
{13277}{13333}Sranje, smeæe.
{13389}{13416}POZDRAVI IZ PORNO PRIJESTOLNICE, USA!
{13445}{13481}To, Steve! Napaljene Valley Girls.
{13483}{13520}Da si bar ovdje Drkadžijo! Da nisi! | Popuši mi, Steve.
{13522}{13548}Bem ti.
{13966}{13995}Dog Years - ÈESTITKE MATURANTI!
{13997}{14028}Rekao sam ti da æe mi se Steve javiti.
{14030}{14063}To je samo razglednica...
{14065}{14118}ali dao mi je sjajnu ideju.
{14120}{14147}Vidi...
{14149}{14200}Steveov glupavi prijatelj, Jim...
{14202}{14261}je oženio | glupavu nimfomanku iz benda, Michelle.
{14263}{14333}I rekao je da se samo neprestano ševe | u Glazbenom kampu.
{14335}{14434}Prijatelju, ne možeš ševiti cure iz benda. | One su klasika.
{14467}{14549}Ne govorim o tome, smradu iz guzice.
{14552}{14613}Govorim o snimanju videa dok se ševe.
{14615}{14700}Ljudi vole skrivenu kameru | s glupanima koji to rade.
{14702}{14794}Napaljeni Bendiæi. | Steve æe imati dostojnog protivnika...
{14798}{14860}jer mali braco upada u obiteljski biznis.
{14955}{14984}ŠPIJUNSKI KOŠ
{14986}{15025}To, Spy Chest.
{15042}{15078}Tajni video.
{15093}{15120}Skrivene kamere
{15122}{15147}Kvragu, to.
{15149}{15174}Mikro kamera za tijelo
{15176}{15203}Mikro kamera 299.99$ i više - kupite odmah
{15205}{15233}Infracrvena kamera u boji | Kamera u boji 159.99$
{15235}{15267}Infracrvena kamera u boji? Kupujem. Sranje.
{15269}{15330}Mikro špijunska kamera | Spy Chest 3201 za 99.99$
{15332}{15365}Kamera olovka 399.99$ | Kamera u boji 99.99$
{15367}{15432}Špijunska kamera 199.99$ | Vanjska kamera 99.99$
{15436}{15463}Emitiranje sutradan
{15465}{15508}Može sutra? Bit æe sjajno.
{15820}{15854}TRAŽE SE DJEVOJKE - UPITATI UNUTRA
{16018}{16056}MUŠKE SPAVAONICE
{16343}{16388}GLAZBENI KAMP - OKUPLJANJE
{16515}{16586}Dobrodošli u Tall Oaks 2005.
{16615}{16682}Èujmo to od srednje škole Lloyd Memorial.
{16684}{16742}L-L-O-Y-D!
{16760}{16797}L-L-O-Y-D!
{16827}{16871}- Mount St. Marie. | - Mount St. Marie!
{16873}{16906}Mount St. Marie!
{16908}{16947}East Great Falls High.
{16962}{16997}East Great Falls!
{17010}{17046}East Great Falls!
{17067}{17146}I peterostruki prvaci | i šampioni Tall Oaks Kupa...
{17153}{17196}Beechwood Academy.
{17198}{17264}Mi smo Broj jedan! Mi smo Broj jedan! | Mi smo Broj jedan!
{17266}{17301}Dobro, smirite se.
{17316}{17371}Kao što vam je poznato, svake godine...
{17373}{17446}jednom se kompozitoru | maturantu Tall Oaksa dodjeljuje...
{17448}{17556}školarina za prestižni Robards konzervatorij.
{17558}{17610}Elyse, ti ju moraš dobiti ove godine.
{17612}{17689}Ove æe godine, Dr. Susan Choi, | predsjednica Robardsa...
{17691}{17761}osobno ocjenjivati kompozicije.
{17763}{17871}I ne zaboravimo pozdraviti | savjetnike kampa Tall Oaks.
{17975}{18019}Dobrodošli u Glazbeni kamp!
{18046}{18148}Kod posjete našoj ambulanti, | sestra Sanders æe se pobrinuti za vas.
{18212}{18322}Dobro, idemo raditi | i nek najbolji bend pobijedi.
{18513}{18540}Spremni?
{18989}{19027}Što sad?
{19034}{19096}Ti si novi? Izgledaš kao da si se izgubio?
{19102}{19192}Ti si šupak? Obrastao si i odvratno smrdiš.
{19232}{19307}Ovaj put æu ignorirati takav govor.
{19334}{19386}Tako se ovdje ne govori.
{19388}{19495}Novi moraju stalno nositi kapicu. | To su pravila.
{19497}{19571}A tko je tebe izabrao za gradonaèelnika | Kreten Grada?
{19584}{19683}Ja sam Brandon Vandecamp, | glavni bubnjar, Beechwood Academy...
{19685}{19727}i predsjednik Savjeta Tall Oaksa.
{19729}{19825}A tko su oni, predsjednièe? | Prva dama i Vice pica?
{19972}{20005}Baš ti pristaje.
{20008}{20122}Uh, moj, hvala. Znate, | buduæi da sam službeni kreten u bendu...
{20124}{20178}možete li pogoditi koja mi je omiljena stvar?
{20180}{20239}- Nemam pojma. | - Razbit æu ti jaja.
{20297}{20323}Natrag, gade.
{20325}{20382}Sveta majko Mozartova.
{20428}{20455}Ovo je gadno.
{20457}{20521}Niste znali da je Jackie Chan bio u kuæi?
{20523}{20571}Stanite. Odmah prestanite.
{20573}{20629}Ti su kvržièasti slinavci prvi poèeli.
{20631}{20694}Nije istina. | Samo smo ga podsjetili da nosi kapicu.
{20696}{20753}A on je bezobrazno uvrijedio | Brendonove genitalije.
{20755}{20862}- To je laž, šmrkavèe. | - Oskare, Jimmy, otpratite ga do...
{20868}{20924}- Makroa. | - Èega?
{20935}{20989}- Mrtav si. | - Odmah, gospodo.
{21009}{21061}Brandone, jesi dobro?
{21086}{21147}Da li bi mi rekao što dovraga radiš, Stifleru?
{21149}{21210}Nije važno, Veliki O. Neæe dugo ostati.
{21212}{21239}- Gade! | - Dolazi ovamo.
{21241}{21294}Makro æe te srediti, budalo.
{21296}{21358}- Tko je makro? | - Makro.
{21360}{21413}Osoba za Rješavanje Morala i Konflikta.
{21415}{21472}Èuo sam da je jednom klinac otišao tamo...
{21474}{21516}kao bariton a vratio se kao sopran.
{21518}{21589}- Klarinet u guzicu i natrag. | - Što?
{21591}{21648}Osoba za Rješavanje Morala i Konflikta
{21770}{21802}Pièkice.
{22135}{22168}Oh, oprostite.
{22220}{22272}Frankenstein. Jezovito.
{22302}{22360}Samo sam obožavatelj Borisa Karloffa.
{22367}{22465}- Ja sam Makro, G. Levenstein. | - Ti bokca, vi ste Jimov tata.
{22479}{22550}Ševio je onu crvenokosu nimfomanku | u mojoj kuæi na jezeru.
{22552}{22641}- Oh, Bože, nisi valjda Stiffler? | - Da, ja sam Steveov brat, Matt.
{22675}{22762}- Postoje dva Stifflera? | - Da. A što vi radite ovdje?
{22764}{22860}Pa, Jim je otišao od kuæe, oženio Michelle...
{22862}{22938}crvenokosu nimfomanku koju si spomenuo.
{22968}{23039}Buduæi da je bila bivši Savjetnik godine | u Tall Oaksu...
{23041}{23164}ponuðeno joj je da bude Makro ovog ljeta, | ali trudna je.
{23172}{23255}Oèito iz razloga | na koje se maloprije aludirao.
{23257}{23330}A ja imam jako dobar odnos s mladima...
{23332}{23390}pa sam se dobrovoljno javio za posao.
{23392}{23477}Taj kreten nije u našem bendu | i nismo odgovorni za njegove postupke.
{23479}{23545}- Tko ti je pišao u piccolo? | - Osjeæam netrpeljivost ovdje.
{23547}{23579}- Zatrovao mi je bend. | - Što?
{23581}{23653}- Ja sam Makro i posao mi je baviti se... | - Što on radi ovdje?
{23655}{23737}- Matt Stiffler je èisto zlo, baš kao i brat mu. | ...konfliktima.
{23739}{23775}Hvala, Leesy.
{23890}{23928}Èini se dragom.
{23951}{23986}Postoje pravila, naravno.
{23988}{24029}- Morat æeš nositi kapicu. | - Da.
{24031}{24113}Znam da je malo blesavo, ali to je tradicija...
{24115}{24202}nešto što ti je poznato, | buduæi da si u nogometnom timu...
{24204}{24289}poput hoda slonova i ispijanja piva iz baèvi.
{24291}{24347}No ovdje moraš nositi smiješnu kapicu i...
{24349}{24410}- i pomalo trendovsku Tall Oaks majicu. | - Da.
{24425}{24474}Plivaj niz struju, Matt...
{24476}{24534}i dobro æeš se zabavljati...
{24543}{24616}i vrlo uskoro steæi nove prijatelje.
{24784}{24853}Bog, Ernie Kaplowitz, tenor saksofon.
{24884}{24947}Super, i ja sam novi.
{24953}{25049}Želio sam doæi prošle godine, | ali Kompjuterski kamp je bio u isto vrijeme...
{25051}{25150}Da, to je bilo ovdje kad sam ja stigao. | Tvoje je ime na tome.
{25173}{25199}ŠPIJUNSKI KOŠ
{25201}{25235}Što je to?
{25277}{25365}Bog, dobrodošao u Casa de Stiffler. | Ja æu ti biti domaæin, Matt.
{25369}{25454}Svakog æu si dana postaviti za cilj | da te ne prebijem.
{25456}{25524}Dozvoli mi da te odvedem do tvojih odaja.
{25549}{25612}Kad sam ovdje, ti si tamo.
{25641}{25690}Ugodan ti dan, seronjo.
{25697}{25726}Nisam...
{25808}{25836}U redu...
{25838}{25878}Izaæi æu i odložiti ti stvari.
{25880}{25910}Ok. Bendiæi-vizija.
{25912}{25938}KAMERA ZA KAPU - HARD DRIVE
{25977}{26079}Ovo je show države Ohio iz 1978...
{26081}{26114}The Wizard Of Oz.
{26116}{26206}Onaj u kom je sviraè gadostifona | zaboravio staviti toèku na I?
{26254}{26319}Baš. Èudaci.
{26367}{26426}Ne boj se, Stiffmeister je ovdje.
{26428}{26504}Glazbeni kamp je postao puno bolji, dame.
{26507}{26569}Ti si mlaði brat Stevea Stifflera, zar ne?
{26571}{26616}- Mlaði i obdareniji. | - Sjajno.
{26618}{26703}- Možeš li mu nešto poruèiti od mene? | - Nema problema, senorita.
{26870}{26976}Èini se da je Steve nekog | poseksao i ostavio kao i inaèe.
{27002}{27081}- Ima li problema ovdje? | - Ne, sve je u redu.
{27130}{27208}- Zabavljaj se u Glazbenom kampu. | - Hvala, hoæu.
{27304}{27360}- Vidimo se. | - Naravno.
{27372}{27439}Morao bi poèeti pokazivati malo poštovanja.
{27441}{27523}Morao bi se poèeti | vraæati za svoj stol, Veliki Psu.
{27525}{27569}Mièi mi se.
{27602}{27699}Hola, chicas. Lijepo te je vidjeti opet, Elyse.
{27707}{27782}Što se dogaða veèeras? | Malo zabavice, malo ludovanja?
{27784}{27846}Tko želi nakupiti malo milja èeste ševe?
{27848}{27922}- Ti si naj... | - Seksi frajer koji je došao u Glazbeni kamp.
{27924}{28021}- Što? Chloe, on je tako neugodan. | - Seksi neugodan.
{28023}{28097}- Hvala. | - Umorna sam od muvanja s tim...
{28099}{28145}glupavima finim deèkima...
{28148}{28202}i osjetljivim umjetnièkim tipovima.
{28211}{28320}- Zabavimo se s pravim frajerom veèeras. | - Tako je. Taj sam:
{28333}{28429}- 100%-tni frajer. | - Super, u mojoj sobi u 8 sati.
{28457}{28545}Sjajan prvi dan, kamperi. Govori vam Makro.
{28547}{28632}I kažem vam, moral je bio samo takav.
{28634}{28700}Uskaèite u krpe i dobro se naspavajte jer...
{28702}{28732}NATJECANJE U TALL OAKSU
{28734}{28804}od sutra poèinju | mnoge planirane uzbudljive aktivnosti...
{28806}{28896}meðu kojima je i utrka za Kup Tall Oaksa.
{28900}{28949}Neka igre zapoènu.
{28956}{29051}Napaljeni bendiæi. | Prvi prizor. Zabava s frajerom.
{29168}{29272}Zove se Strip Trivia. Izmislile smo ju | i to je tradicija Glazbenog kampa.
{29280}{29383}"Èetvrti i dugi", "Sekspariæi" | "Udaraèice" i "Tko puše u mene?"
{29386}{29462}Ovo mi izgleda kao prava igra za mene. | Hoæemo li?
{29486}{29559}Sjednite u sredinu. | Vaša igra, moj raspored sjedenja.
{29561}{29599}Sjednite malo bliže, moje dame.
{29601}{29656}Ne bojte se. Sve je u redu.
{29658}{29686}Dobro...
{29693}{29765}Pravila su jednostavna. | Biraš kategoriju i pitanje...
{29767}{29826}a za svaki netoèan odgovor, | skidaš komad odjeæe.
{29828}{29854}U redu.
{29856}{29944}- Ja æu prvi. "Tko puše u mene?" | - Dobro.
{29946}{29973}NE PALI ME
{30023}{30130}Ja sam srebrna Stradivardijeva truba | koju svira dobitnik Pulitzerove nagrade.
{30155}{30187}Tko puše u mene?
{30191}{30251}- I ja bih želio znati. | - Žao mi je.
{30256}{30291}Skini cipele i biraj ponovo.
{30293}{30340}Niste mi rekle da su pitanja iz glazbe.
{30342}{30429}- Pa ovo je Glazbeni kamp, moronu. | - Bit æemo fer...
{30436}{30509}i dat æemo mu bod prednosti.
{30594}{30635}To.
{30664}{30706}Dobro. Može.
{30744}{30814}Što ti je? Bojiš se pokazati te male sisice?
{30816}{30882}Razvila sam se od èetvrtog razreda, Matte. | Ti nisi?
{30884}{30957}O, da, imam 4 kile zrelosti baš ovdje, Leesy.
{30959}{31030}- Prestani me tako zvati. | - Dobro, idemo dalje.
{31047}{31149}- Matt, izaberi pitanje, molim te. | - Dobro, jebi ga. Štogod.
{31164}{31217}Evo ti ovo. Nauživaj se.
{31255}{31320}- Èetvrti i dugi. | - Naravno, nema problema.
{31399}{31507}Koja od Beethovenovih simfonija | ima najduži èetvrti stavak?
{31529}{31574}Dobro, vidim u kom smjeru ovo ide.
{31576}{31641}Super, pobijedile ste.
{31748}{31785}Ne nosim gaæe, dame.
{31794}{31895}Moram dati svom prijatelju malo zraka. | A sad igramo po mojim pravilima.
{31906}{31983}Samo pitanja iz nogometa. | Spremite se za skidanje, cure.
{31994}{32081}- Èekaj. Hoæe netko pivo? | - Ja hoæu.
{32092}{32211}Savjetnik ima tajnu zalihu | u frižideru u sobi preko puta.
{32215}{32308}- Možeš li ti otiæi? | - E, sad govorimo o pravoj zabavi.
{32310}{32357}Stiffy se vraæa za sekundicu.
{32408}{32470}Nema nikoga...
{32472}{32534}a nismo još vidjele tvoju najbolju stranu.
{32689}{32742}To, imamo ga!
{32792}{32836}Kako je nadrljao.
{33022}{33083}Èovjeèe, deèki, buðenje.
{33085}{33145}Moram samo iskljuèiti klimu, može?
{33147}{33183}Laku noæ, djevojke.
{33352}{33415}Oprosti, šupak, ali igra je završena.
{33420}{33526}Deèkima se baš hoda do doma dužim putem.
{33547}{33590}Provjera soba, djevojke.
{33625}{33652}Sranje.
{33660}{33714}- Skloni mu odjeæu. | - Kroz prozor.
{33732}{33791}Tko želi pivo?
{33956}{33998}Sestro Sanders.
{34065}{34125}- Namjestile su mi. | - Napao nas je sprejem...
{34127}{34192}- i uništio nam proslavu mature. | - Išao sam tamo igrati...
{34194}{34220}Stanite. Djeco.
{34222}{34271}Dobro...
{34277}{34319}gdje ti je odjeæa?
{34383}{34418}Kod mene je.
{34433}{34481}- Mogu li pitati zašto? | - Skinule su me...
{34483}{34561}- Nema veze. Sam je skinuo je hlaèe... | - A one su mi ukrale odjeæu.
{34563}{34629}Zadržao sam se s gðom. | Doubtfire u provjeri...
{34777}{34826}Da vidim da li sam dobro razumio.
{34828}{34940}Elyse, ti misliš da je Matt ohola budala | koga penis tuèe po èelu...
{34942}{35024}samo kako bi dobio priznanje | svog brata sociopata.
{35026}{35120}Ti, Matte, misliš da je Elyse | konzervativna, glupava èistunka...
{35122}{35188}koja se treba opustiti i poševiti.
{35190}{35267}Oprosti mi na izrazu. | Jesam li sve dobro rekao?
{35309}{35344}Gledajte, djeco...
{35372}{35437}jedini naèin rješavanja vaših razlièitosti...
{35450}{35490}jest zajednièki rad.
{35518}{35569}Zašto od sutra ne biste poèeli...
{35571}{35645}polako rješavati vaše razlièitosti?
{35733}{35776}Lijevo krilo pokret.
{35835}{35871}Okret i pokret.
{36055}{36085}Do vraga!
{36122}{36166}Bend 10 pokreta!
{36172}{36197}Sranje.
{36210}{36295}Kad viknem Bend 10 pokreta | èvrsto pucneš i staneš.
{36297}{36391}- Želiš da èvrsto stojim? | - Vidjela sam te i nisam bila impresionirana.
{36456}{36485}Vidi...
{36506}{36562}nikad nismo pobijedili Beechwood, ok?
{36575}{36628}Nekima od nas, ovo je zadnja šansa.
{36688}{36726}Nemoj više zeznuti, dobro?
{36728}{36762}Da, šupèe.
{36824}{36878}- Idemo, narode, natrag na posao. | - Što god.
{36880}{36913}Ne treba mi ovo.
{36915}{36974}Svrstajte se ponovno. Prvi red, ovamo.
{37309}{37341}Èistaèica.
{37343}{37380}Svlaèionice i tuševi
{37999}{38057}Oskare, jesi li mi donio piæe?
{38064}{38136}- Hajde. | - Pripazi malo, mala.
{38198}{38240}Pa to je Ernie Crapowitz.
{38242}{38317}Konaèno si izašao na svjetlo dana. | Tako i treba.
{38350}{38411}Èuj, želim znati što se ovdje dogaða noæu.
{38413}{38476}Lude stvari. | Borba jastucima bez odjeæe, bilo što.
{38478}{38562}Zar ti izgledam kao tip koji je zadužen za | borbu jastucima bez odjeæe?
{38564}{38601}Prvi sam put ovdje.
{38603}{38632}Vidiš ovu kapicu?
{38634}{38661}Da.
{38684}{38719}Da, vidim.
{38721}{38802}Kad se veæ spominju kapice, | a gdje je tvoja, Stiffleru?
{38810}{38857}I dalje ne poštuješ pravila, ha?
{38859}{38905}- Da vidim. | - Opet se uvaljuje u nevolje.
{38907}{38989}Ne nosi standardnu Tall Oaks majicu | niti kapicu.
{38991}{39071}Trebate oduzeti 2 boda Great Fallsu.
{39077}{39122}Slušaj ti, Vande-blesane...
{39130}{39197}što ako uzmem njegovu kapicu...
{39199}{39265}i stavim ju na moj pimpek?
{39267}{39365}Da li bi ti se to svidjelo? | Imam ju na pravom mjestu, ok?
{39369}{39423}Oduzmite 5 bodova Great Fallsu.
{39427}{39458}Pet bodova.
{39460}{39536}Èovjeèe, ovo je mjesto prava pušiona.
{39658}{39700}Stavi kapicu, sine.
{39840}{39887}Pet bodova.
{40447}{40502}Stani mirno. Ne mièi se.
{40504}{40546}Ne ide on nikuda sad.
{40548}{40628}Ovo nije tvoj svijet. Ovo je naš svijet | i ne želimo te u njemu.
{40630}{40684}Veæ su nam oduzeli pet bodova zbog tebe.
{40686}{40729}Ne možemo to dopustiti.
{40735}{40776}Namjesti èovjeku kapicu.
{40962}{41008}Sad pokazuješ poštovanje, budalo.
{41010}{41041}A pasta za zube...
{41043}{41108}æe biti naplata za onaj sprej, šupèino.
{41441}{41478}Sranje.
{41495}{41556}Donijet æu razrjeðivaè boje iz skladišta.
{41591}{41624}Životinje.
{41875}{41974}Matte, poslali su te ovamo...
{41984}{42019}da se promijeniš.
{42023}{42113}Do sad su ti se samo sinusi proèistili. | Zato...
{42122}{42184}mislim da je vrijeme pokušati nešto drugo.
{42191}{42234}Sprijateljiti se.
{42276}{42320}Steæi njihovo povjerenje.
{42374}{42429}Zašto bih ja to želio?
{42507}{42544}Dobro.
{42643}{42693}Dobrodošli u Stiffler-viziju.
{42695}{42757}Mislim da ima sat cimbala što poèinje u 1.
{42759}{42788}Mrzim to.
{42790}{42843}Ali je bolji od nosanja bas bubnja.
{42845}{42875}Istina.
{42984}{43037}Tvoje izgledaju sjajno.
{43039}{43117}- Dvije za cijenu jedne. | - Lijeva mi je veæa, vidiš?
{43119}{43189}- I meni, mala. | - Mogu to super srediti.
{43191}{43233}- Ne! | - Hoæeš vidjeti?
{43235}{43297}- Bila sam... | - Zamagljena leæa. Ne!
{43568}{43661}- Što je to, lasice? | - Da, to je KR3, mali.
{43663}{43751}Kaplowitzev robotski rover s daljinskim. | I ti si nadrljao.
{43753}{43839}- Hej, Oskare, nek netko pozove Makroa. | - Stari, molim te, prestani.
{43841}{43931}Nemoj biti takva konzerva. | Mogu ti pomoæi oko one ženske.
{44022}{44048}Koje ženske?
{44050}{44110}Stari, one s tetovažama. Bastube.
{44112}{44147}Ime joj je Chloe.
{44162}{44243}Daj, èovjeèe. Mogu pomoæi. | Ja sam Stiffmeister.
{44245}{44312}- Gospodar ljubavi i romanci. | - Sereš.
{44316}{44432}Poševio sam tri navijaèice u jednom tjednu, | za vrijeme proljetnih praznika. Studentice.
{44675}{44740}A ja znam zašto ti je kamera prestala raditi.
{44800}{44847}Stari, ovo je prava stvar.
{44861}{44935}- Jesi ikad gledo curama ispod suknji s tim? | - Nisam.
{44937}{44994}Ali mi je pomoglo biti prvi | na Državnoj smotri.
{44996}{45051}Nadam se upisati | Tehnološki u Massachusettsu.
{45053}{45105}Stvarno bih želio raditi za NASA-u.
{45107}{45167}Nacionalnu Asocijaciju Analnog Seksa?
{45172}{45214}Ne, to je Svemirska...
{45233}{45345}- Postoji Asocijacija analnog seksa? | - Da, ali moraš biti profesionalac.
{45383}{45435}Samo malo, postoji Svemirska Asocijacija?
{45472}{45519}Trebao si koristiti ovo.
{45550}{45651}- Vidiš, ima leæe koje se ne zamagljuju. | - No, dobro.
{45677}{45794}- Može li robot snimati? | - Dobro, što namjeravaš?
{45829}{45889}Mislim, s videom. Što æeš uraditi?
{45891}{45932}O, to je samo za zabavu.
{45935}{46018}Tko ne voli gledati seksi gole ženske, ne?
{46053}{46118}Nek to ostane meðu nama | i dat æu ti da gledaš.
{46122}{46209}Osim toga, namjestit æu ti Chloe | do sredine tjedna.
{46222}{46282}Hej, Stiffleru, telefon.
{46291}{46335}U Detroitu smo!
{46350}{46415}Umoèeni u slatki brazilski rum.
{46417}{46483}Naroljan sam do daske, èovjeèe!
{46485}{46589}Danas æu ti poslati rum. | Mogao bi ti poslužiti u Kretenogradu.
{46591}{46631}Mjesto je užasno.
{46660}{46701}Moj cimer, Dr. Robot...
{46703}{46755}uhvatio me | da snimam studentice pod tušem.
{46757}{46808}I sad moram biti fin i dobar s njim.
{46810}{46891}I ne snimam dobre scene | jer me bendiæi mrze.
{46932}{46985}To ti je kao pokušaj seksa s djevicom.
{46987}{47073}Ponašaj se kao da ti nije stalo | sve dok ti oni sami ne dadu dobre scene.
{47075}{47124}Zavrijediti njihovo povjerenje?
{47135}{47182}Stari, to bi moglo hodati.
{47185}{47246}Bit æu tajni fuker benidiæa.
{47268}{47352}Bog, svima. | Krasan dan u Glazbenom kampu, zar ne?
{47357}{47450}Frendovi iz benda. Što ima? Yo.
{47468}{47563}Samo se zahvaljujem na buðenju. | Baš ste šaljivdžije.
{47590}{47664}Hej, konaèno sam èuo zov glazbe, ok?
{47682}{47761}Tamo. Èujete li? I ja èujem.
{47768}{47880}Drugi sam èovjek i... | Usput, izgledate sjajno u kratkim hlaèama.
{48129}{48208}- Što to radiš? | - Èekam vježbu marširanja, gðo.
{48210}{48269}Èuj, Matte, stvarno nemam vremena za ovo.
{48271}{48356}Èuj, mislim kad sam veæ ovdje | mogao bih to stvarno iskoristiti.
{48358}{48440}Matte, marširanje nije jednostavno, znaš? | Nije to kao nogomet.
{48442}{48530}- Jesi li bila u napadu protiv dvojice? | - Jesi li zakoraèio u dvokoraku?
{48532}{48616}Da, kad su nas pajkani lovili | po Koreno Creeku.
{48631}{48700}I tako si se uplašio, da si plakao.
{48718}{48816}- Bio sam alergièan. | - Bila je zima, Matte.
{48840}{48923}Ako me ne nauèiš marširati, | morat æu ponovno plakati.
{49009}{49037}U redu.
{49044}{49141}Lijeva noga na jedan i tri, | desna na dva i èetiri.
{49143}{49180}Mora se i raèunati?
{49386}{49480}Jedan, dva, tri, sredina. Jedan, dva, tri, crta.
{49482}{49535}Desna noga na èetiri.
{49589}{49650}- Nek ti korak bude ujednaèen. | - Što?
{49687}{49772}U redu, idemo, prijatelju, sredit æu ja tebe.
{49807}{49923}Svaka cura koja svira tubu, | dobra je u svemu. To Stiffler kaže.
{49925}{49988}Ne znam što to znaèi, ali mora biti dobro.
{49990}{50020}Spreman si.
{50022}{50059}Idemo naæi Chloe.
{50366}{50395}Sranje.
{50425}{50504}Što je sad? Tko to radi?
{50560}{50587}Uzmi ga.
{50589}{50615}U redu je.
{50847}{50934}- Hvala, mali ružni stroju. | - Nema na èemu...
{50943}{50984}ljepotice.
{51351}{51454}Mojom desnom, mojom desnom, | ali mogu i mojom lijevom, lijevom.
{51538}{51564}Guze.
{51598}{51625}Dobra igra.
{51774}{51818}Upravo si mi dodirnuo guzu.
{51987}{52045}- Što je to? | - Tvoj instrument.
{52056}{52099}Ovo je pederasto.
{52124}{52175}- Mislim, slabo je. | - Dobro.
{52194}{52263}Postoje dva položaja.
{52278}{52378}Kad ga držiš, ovako, i kad sviraš, ovako.
{52382}{52423}Kad viknem "rogovi uvis"...
{52425}{52475}ispružit æe svoj instrument i...
{52477}{52517}Bog, gubitnici.
{52521}{52612}Matte. O, Bože, oprosti mi, Matte.
{52614}{52668}- Mislim da sam si probušio jezik. | - Da vidim.
{52670}{52735}- Nema nièega, nema rupe. | - U današnjoj epizodi...
{52737}{52809}gledajte gubljenje vremena | na izgubljene sluèajeve.
{52830}{52929}Ako sam dobro razumio, | ti si napisala glazbu za show, Elyse...
{52931}{52970}ako to nazivaš glazbom.
{52972}{53031}U pravu si. Jesam.
{53033}{53086}Koga bi tata angažirao da ju napiše za tebe?
{53088}{53207}Samo te upozoravam, kolaèiæu. | Robardsova školarina je moja.
{53219}{53258}Kao da ti je potrebna.
{53260}{53337}Nije bit u tome da li mi treba. | Bit je u tome da ju želim.
{53339}{53421}- Da, i dobijem ono što želim. | - Zašto ne ušutiš veæ jednom?
{53423}{53453}Matte, nemoj.
{53478}{53545}- Što æeš uèiniti? | - Razbiti te.
{53549}{53592}- Izazivaš me? | - Ne.
{53594}{53675}- A što ako te izazivam? | - Ne, Brandone, ne izaziva te.
{53677}{53745}Prihvaæam. Amfiteatar u 5 sati.
{53754}{53823}Prošlo je tri godine otkad me nisu izazvali.
{53829}{53874}Imamo izazivaèa.
{53939}{54005}Drago mi je | što æu moæi podsjetiti ljude zašto.
{54016}{54052}East Great Falls.
{54059}{54110}Vidimo se, šupèino.
{54155}{54247}- Znaš li što si uèinio? | - Nema veze. Seronja æe ionako izgubiti.
{54249}{54313}Izazvao si ga na dvoboj, Matte.
{54320}{54349}S maèevima?
{54364}{54456}Ne, idiote. Izaæi æete na pozornicu i svirati.
{54458}{54512}A raja æe odluèiti tko je pobjednik.
{54519}{54572}Možemo li napraviti stoj na rukama?
{54579}{54685}Ovo je ozbiljno. | Beechwood dobija 5 bodova za pobjedu.
{54687}{54766}A on æe pobijediti, | buduæi da svira instrument.
{54771}{54814}Pa i ja sviram.
{54827}{54894}Nek poène Kraljevska bitka Tall Oaksa.
{54908}{54977}Nagrada je 5 bodova za kup.
{54999}{55047}Brandone, ti nastupaš prvi.
{56101}{56132}Hajde!
{56188}{56249}Popuši mi, gade.
{56274}{56305}Slabo.
{56323}{56361}Ovo je tako ponižavajuæe.
{56363}{56393}U redu, Bandone.
{56395}{56434}Pokaži mu, Brandone.
{56864}{56893}Uzmi ovo!
{57172}{57239}Èini se da je natjecanje završilo.
{57255}{57312}Zamisli. Upravo smo izgubili 5 bodova.
{57375}{57447}A pobjednik je zbog odustajanja...
{57507}{57559}Znam da to nije njegova greška...
{58104}{58146}Ne znaš rijeèi.
{58668}{58706}Trebao je to obrijati.
{58774}{58814}East Great Falls!
{58828}{58872}East Great Falls!
{58879}{58925}East Great Falls!
{58941}{58980}East Great Falls!
{59056}{59118}U redu, 5 bodova za East Great Falls.
{59163}{59211}To, Great Falls!
{59268}{59320}East Great Falls!
{59380}{59401}East Great Falls!
{59426}{59477}East Great Falls!
{59479}{59527}East Great Falls!
{59608}{59658}- Hej. | - Što je?
{59660}{59722}- Ti si stvarno Škot? | - Naravno da nisam.
{59746}{59779}Mama me tjerala svirati.
{59781}{59826}Najdosadniji kojeg sam se sjetio.
{59828}{59919}Mislim da si roðen | za stiskanje i puhanje, Stiffleru.
{59924}{59956}Hej, Oskare.
{60069}{60133}Koliko još Oskara znaš? Hajde.
{60190}{60248}- Što ima? | - Bubnjevi ti zvuèe prilièno dobro.
{60250}{60276}Hvala.
{60278}{60330}Samo reci želiš li nauèiti nove pokrete.
{60332}{60359}Stvarno?
{60361}{60426}- Zabrljat æe. | - Sigurno æe zabrljati.
{60463}{60571}- Hvala što si nam vratio tih 5 bodova. | - Ja sam ih izgubio. Morao sam ih vratiti.
{60585}{60659}Ljudi, Sheree æe mi pokazati neke pokrete.
{60672}{60698}Narode...
{60700}{60805}podsjeæam da se bitka za kup zagrijava | i zato zapamtite...
{60807}{60832}GROŽÐE
{60834}{60922}održavati duh fair playa i | prijateljskog natjecanja u Tall Oaksu.
{60938}{60995}Imamo pljuvaèke za šest konzervi.
{61073}{61144}- To, mala, ponosan sam na tebe. | - Hvala J. Lo.
{61146}{61181}Zakon. Veliki O?
{61190}{61262}Juèer si imao pravu malu ekshibiciju.
{61266}{61334}Znaš, plebejci misle da si heroj.
{61336}{61390}Ne znam što je plebejac, Vande-glupane.
{61392}{61469}Nisu li ti rekli da ne uznemiravaš | važnu facu dok jede?
{61471}{61537}To je moje, seronjo. Možeš mi vratiti?
{61572}{61650}- Pimpeci. | - Ovo je još uvijek moj kamp, šupak.
{61656}{61717}- Padaš sve niže. | - Nije istina.
{61719}{61746}Mama ti je pala.
{61748}{61828}Jel svirala trubu? Usnice su joj baš tvrde.
{61834}{61865}Opako.
{62241}{62269}Njami.
{62359}{62407}To se traži.
{62435}{62506}- Što se dogodilo ovaj put, Claire? | - Vježbala sam solo...
{62508}{62543}i ozlijedila se.
{62564}{62608}Otrovali su me.
{62639}{62704}Ovo je prirodni biljni ekstrakt...
{62706}{62779}koji potièe refleks povraæanja.
{62883}{62948}Što god je unutra, vrlo brzo æe izaæi van.
{62955}{63003}Kao i on, ako budemo te sreæe.
{63045}{63132}Siguran sam da je to nešto...
{63140}{63245}što si pojeo za ruèak. Imam isti problem. | I moj je stomak vrlo osjetljiv.
{63260}{63342}Bio sam na jednom primanju. | Na istom su pladnju, zamisli...
{63344}{63469}poslužili srnetinu u sosu, | pržene lignje i hladetinu.
{63604}{63631}Što?
{63848}{63876}ŽURNO
{63900}{63965}- Što ima, ljuskaru? | - Doði, stari. Vidi ovo.
{63967}{64055}Poslijepodne, dok su savjetnici vježbali | za show talenata...
{64057}{64119}odglumio sam napad astme | i zamijenio obje kamere.
{64121}{64185}Ovo je rutina njihove vježbe, goli.
{64194}{64263}Stari, ti si prljavi mali virtualni faker. Mrak.
{64279}{64387}- Mislio sam da æemo samo gledati. | - Toèno, možda æemo htjeti gledati ponovo.
{64514}{64631}Poslušao sam tvoj savjet za Chloe. | Upotrijebio sam Rovera da joj dam sok.
{64645}{64737}- I to je tvoja sjajna, luda ideja? | - Da, mislim da joj se svidjelo.
{64739}{64812}- Zvuèi pederski. | - Nije pederski.
{64849}{64918}Veèeras je fešta | s logorskom vatrom i hladnim piæem...
{64920}{64998}i moram znati | drugi korak Stiffmeisterovog plana.
{65000}{65086}Fešta s hladnim piæem. Stvarno.
{65094}{65132}Posebna dostava.
{65135}{65177}Spremi se za ludi provod.
{65207}{65245}Spremi se pomaziti macu.
{65247}{65327}Vrijeme je da se Dr. Robot poševi.
{65332}{65358}Poševi?
{65362}{65426}Rekao sam ti, vjeruj Stiffmeisteru.
{65432}{65498}Meister je majstor na njemaèkom.
{65517}{65621}Napiti ju? To je tajna odrastanja? | To je drugi korak?
{65626}{65745}Zapravo, to je èetvrti korak. | Nemaš muda za drugi niti jezik za treæi.
{65749}{65785}Imam muda.
{65798}{65859}Ali nisi još èuo što je peti korak.
{65950}{66038}Roðen da bih brijao
{66126}{66214}Vruæe sam krvi | provjeri i uvjeri se
{66223}{66314}Imam visoku temperaturu
{66316}{66383}Doði, mala | Da li samo plešeš?
{66426}{66493}- Ovo je baš dobro. | - Nemoj previše uživati u tome.
{66495}{66578}- Sutra imamo veliku probu, ljudi. | - Opusti se, Leesy.
{66588}{66666}Uživaj u slatkom voæu | Glazbenog kampa s tvojim prijateljima.
{66668}{66759}Daj, Elyse. Opusti se malo. Zabavljaj se.
{66761}{66793}Zabavljam se.
{66795}{66867}Hej, napaljeni, idemo uzeti još malo ovoga | dok još ima.
{66869}{66927}- Dobro. | - Napaljeni?
{66929}{67038}To mu je nadimak. Poševio bi pticu u letu. | Nije normalan.
{67062}{67155}Slušaj ovo, prijatelju. | Jednom sam poševio obou u kampu.
{67180}{67237}- Stvarno? | - Malo puhao u nju...
{67239}{67350}fino zagrijao drvo, nalio motornog ulja | i udri.
{67355}{67407}Možda bi trebao pokušati s flautom.
{67518}{67578}Sad je vrijeme da ti pokažem te pokrete.
{67580}{67605}Stvarno?
{67740}{67768}Što?
{68115}{68148}Znam što radiš.
{68150}{68249}- Znaš? | - Ono što uvijek radiš. Lažnjak si.
{68255}{68330}Napravit æeš sve samo da bi bio glavni.
{68332}{68425}Baš kao i kad smo bili klinci, | sa mnom si bio normalni stari Matt...
{68433}{68516}ali kad bi bio sa Steveom i frendovima, | bio si Stiffmeister.
{68541}{68581}Tko æeš biti veèeras?
{68583}{68622}Hej, mali kuronjo...
{68624}{68731}prestani biti takav dupelizac | i daj mi još jedno piæe.
{68733}{68780}Glupavi majmune.
{68968}{69030}Znaš šta? Zabavit æu se veèeras.
{69222}{69297}Proklete ženske, èovjeèe. Ne razumijem to.
{69299}{69393}Mislim, Oskar u šumi ševi savjetnicu Sheree.
{69395}{69462}- Kako je to moguæe? | - Taj se prskavac ševi?
{69464}{69536}Baš tako. A vidi nas, | dvojica najnabrijanijih u kampu...
{69538}{69641}nemamo nikakve šanse ubosti nešto. | To je stvarno sranje, prijatelju.
{69650}{69699}Stari, moram to vidjeti.
{69786}{69832}- Mièi više kukovima. | - Kukovima, ovako?
{69834}{69928}Da, sad brže. Da. Tako. Krug. Baš tako.
{69930}{70030}Alfa ženka je izabrala nedostojnog mužjaka.
{70032}{70095}Hoæe li on preživjeti ovaj opasan susret...
{70101}{70207}ili æe ona zadovoljiti svoje primarne potrebe | i prožderati ga za veèeru?
{70214}{70253}Ostanite s nama.
{70263}{70356}Oprosti. Stvarno nisam dobar u ovom.
{70358}{70408}Opusti se. Dobro ti ide.
{70489}{70525}Ovo je bezveze.
{70533}{70594}A ovako? Oskare.
{70608}{70660}Da li me to tvoja palica bode?
{70688}{70735}Nemam palice sa sobom.
{70737}{70804}Ustao si se za mene, Oskare?
{70817}{70858}Postaje vruæe.
{70865}{70935}Ugrizi me za dupe i nazovi me kaubojem.
{70954}{71007}Pozdrav, D košarice Sheree.
{71018}{71060}Kukovi. Kukovi.
{71066}{71106}- Koristi kukove. | - Kukove, o, da.
{71108}{71152}I korak, i...
{71229}{71259}Tko bi rekao?
{71281}{71314}Opa.
{71385}{71443}Yo, mi u Tall Oaksu | pijuckamo sokiæe
{71445}{71500}Imamo rogove, trube | ritam i flaute
{71502}{71558}Great Falls svira
{71560}{71621}I otjerat æemo prokleti Beechwood iz grada
{71623}{71680}J. C., što, ljulja gomilu
{71682}{71756}Svi su u transu od voænog punèa
{71838}{71919}- Samo želim da me poštuju. | - To je baš slatko.
{71925}{71986}Jedina osoba ovdje koja æe ševiti.
{72206}{72255}Pozdrav oboa.
{72660}{72702}To je baš zakon.
{72739}{72843}Nadam se da te nisam uplašio | s Roverom i sokom.
{72846}{72898}Ne, èovjeèe, to je bilo slatko.
{72915}{73001}Nitko nikad nije bio tako dobar prema meni.
{73015}{73053}Još i više, iskreno...
{73063}{73138}metal me baš pali.
{73596}{73649}Poster OBOE - Gornji dio
{73651}{73705}Motorno ulje
{73780}{73832}Èovjeèe, zaglavila se.
{74420}{74479}- Ugasi svjetla. | - K vragu, gangsteru.
{74482}{74546}- Samo sam se zezao, prijatelju. | - Èuj... zapelo je.
{74548}{74606}- Sranje, da ti pomognem? | - Ne diraj me.
{74643}{74669}Hajde.
{74687}{74725}Možda bi trebao puhati u nju.
{74727}{74768}Probaj puhati u nju, a ja æu vuæi.
{74770}{74822}Nema teorije. Jimmy ne stavlja usne na to.
{74824}{74859}Trebaš biti timski igraè.
{74861}{74915}- Pokušaj i opusti se, stari. | - Ne tako jako.
{74917}{74955}O, Bože!
{75122}{75206}- Samo sam mu pokušavao pomoæi. | - Stari, zaèepi.
{75208}{75235}Kako god.
{75237}{75286}Alergièan je na motorno ulje.
{75288}{75352}Otok bi trebao splasnuti za koju minutu.
{75358}{75457}Ovakve se stvari ne bi dogaðale | našem starom Makrou.
{75961}{76029}Kad sam ja odrastao nije bilo MTV-a.
{76061}{76123}Možda su ovo vremena | s previše podražaja...
{76125}{76224}koji tjeraju mladog èovjeka da gura...
{76241}{76310}svoj instrument u tako èudna mjesta.
{76356}{76394}Poznavao sam mladiæa...
{76396}{76475}koji je imao seksualni odnos | s pitom od jabuka.
{76479}{76532}I izrastao je u normalnog muškarca.
{76537}{76607}Dakle, potpuno si normalan...
{76634}{76672}u vezi tih stvari.
{77112}{77187}- Jesi li dobro? | - O, da.
{77189}{77297}Toliko sam pijana | da æu najvjerojatnije zaboraviti da si...
{77332}{77382}ševio obou.
{77600}{77642}Imam šest piercinga.
{77677}{77738}Što ne ukljuèuje ove na licu.
{78062}{78096}Dva ovdje...
{78153}{78226}i èetri malo niže.
{78507}{78557}Nisam to vidio veæ neko vrijeme.
{78563}{78684}Da, nemamo vremena za ples. | Samo bend, bend, bend.
{78686}{78734}Govorio sam da se trebaš zabaviti.
{78736}{78821}- Zabavljam se. Doista, cijelo vrijeme. | - Baš.
{78823}{78888}Samo sam pod velikim stresom. Mislim...
{78904}{78957}iduæe æemo godine maturirati, i, ne znam.
{78959}{79008}Ne govorim baš puno o tom...
{79010}{79081}jer je kup timska stvar i...
{79083}{79158}Ali, dobiti Robardsovu školarinu, to je kao...
{79160}{79206}dobiti buduænost, znaš? I...
{79224}{79292}Dr. Choi dolazi. Mislim...
{79296}{79379}ne razumiješ ti to. Ona je slavna...
{79390}{79462}jako, doista, slavna. I ponekad sam...
{79487}{79528}stvarno pod jakim stresom...
{79530}{79622}i smirujem se svirajuæi Picardo.
{79639}{79704}Èekaj, ti imaš... Picardo?
{79708}{79770}Jeftini, ali izgubila sam ga.
{79778}{79859}- Èekaj, ako sam ja sluèajno našao Picarda... | - Pronašao si ga?
{79861}{79907}- Možda. | - Vrati mi ga.
{79914}{79951}Ako te mogu gledati.
{79974}{80047}Dobro, ali treba mi malo zagrijavanja.
{80049}{80108}Imam svo vrijeme ovog svijeta.
{80170}{80196}Zamisli.
{80241}{80303}Ali moram biti jako pijana.
{80324}{80404}Jako pijana. Majka zemlja.
{80426}{80451}Da.
{80465}{80501}Odlazi, odbij.
{80959}{81015}Dobro ljudi, odmorimo se.
{81097}{81148}Danas smo svi malo usporeni.
{81191}{81230}Èovjeèe, grozni smo.
{81232}{81317}Jedna noæ zabave nije bila vrijedna | gubitka jednog dana vježbe.
{81406}{81442}Daj mi to.
{81461}{81523}Slušajte me, grupo lijenih govnoljubaca.
{81525}{81572}Oni plebejci iz Beechwooda se ne odmaraju.
{81574}{81644}Želimo li pobijediti, moramo se potruditi.
{81652}{81703}Idemo, gadovi. Natrag na posao.
{81705}{81772}- Matte, to je moj posao. | - Uhvatite pimpeke i mièite dupe.
{81774}{81825}Mi smo u ratu, narode, u ratu.
{81827}{81908}Pokažite sisice. Neka vam narastu muda. | Održavajte ju toplom za mene.
{81910}{82009}Dozvolit æete seronjama iz Beechwooda | da nas pobijede? Tako sam i mislio.
{82011}{82043}U redu, Tall Oakersi...
{82045}{82118}u završnom smo tjednu. | Vrijeme je za borbene boje.
{82120}{82196}I vežite pojaseve | jer slijedi nam gadna vožnja.
{82198}{82245}Želim obou, klarinet, crne stvarèice...
{82247}{82314}i u trenu nam je spremna ritam sekcija.
{82316}{82368}- Pratite me, bendiæi? | - Da.
{82370}{82437}Natjecanje za kup Tall Oaksa se zagrijava.
{82525}{82561}Beechwood pobjeðuje.
{82614}{82639}Štogod.
{82641}{82673}Trebala si mi dati upravljaè.
{82675}{82719}Vodi tu kuèku doma, èovjeèe.
{82724}{82829}Uðite. Hej, drkadžijo, | ne znam otkud da poènem s tobom.
{82993}{83080}Beechwood vodi, | Great Falls i Lloyd izjednaèeni za 2. mjesto.
{83082}{83132}Beechwood liže jaja. Pokret!
{83337}{83391}Pobjeda, East Great Falls.
{83472}{83523}Desnom nogom na crtu.
{83565}{83614}Jimmy, ljubitelju losiona.
{83786}{83849}East Great Falls za èetiri boda.
{84080}{84124}Guzièasti pirati, pozdrav.
{84146}{84230}Tvoja mala grupica sviraèa | je možda dobila bitku...
{84264}{84327}ali svakako nam javi kad ožednite.
{84329}{84383}Da, jer ima ovoga više no dovoljno.
{84511}{84606}To vam je smiješno majmuni. | Smiješno, zar ne?
{84611}{84674}Zajebi taj izazov. Razbit æu ga.
{84676}{84728}Èekaj. Imam bolju ideju...
{84750}{84799}ako misliš da imaš muda za to.
{85088}{85113}Da.
{85115}{85191}- Siguran si da to možeš? | - Roðen sam da budem porno zvijezda.
{85193}{85231}Isporuka po narudžbi.
{85255}{85328}Kad se vratim, | bit æu lakši za milijun Stifflera.
{85810}{85859}Brandone, stvarno si dobar bubnjar...
{85861}{85888}Oprosti.
{86181}{86213}Hej, društvo...
{86215}{86305}ne zaboravite zaslon od sunca. | Tijela su vaši instrumenti.
{86307}{86357}Ne želite imati ispucane gubice za solo.
{86359}{86415}Naravno da ne želimo. Bog.
{86541}{86597}Zaštitni faktor 30? Stvarno je gusta.
{86843}{86891}Kakav joj je okus, Vande-pišo?
{86903}{86957}Dobra, ha? Topla i slana? Da.
{86959}{87050}Nova spermo-formula. 100%-tni Stiffy sok...
{87052}{87103}ZF 69.
{87265}{87295}Najedi se.
{87322}{87361}- To. | - Stani, èovjeèe.
{87363}{87404}- Da. | - Ernie.
{87406}{87438}- To. | - Ernie.
{87663}{87726}Ono što si napravila prije bilo je bolje.
{87728}{87825}Ovo zvuèi kao da si preaktivni mozak | poèasnog društva.
{87836}{87927}Umjesto zloèestih, vlažnih...
{87947}{87988}prljavih ženskih gaæica.
{88005}{88053}Mora biti spontanije.
{88124}{88156}Stani.
{88158}{88226}Možda bi se trebala više družiti | s tvojim prijateljem Mattom.
{88228}{88253}Da, baš bih.
{88255}{88341}Znam da je glupan i sve to, | ali ima on i muškost.
{88344}{88446}Napravi malo ljubavne glazbe, kužiš? | A onda æe note svršiti same.
{88461}{88538}- O, Matt! | - Prestani.
{88543}{88579}Matt. Matt.
{88656}{88715}Proði, šupèe. Sad.
{88734}{88779}Hej, Elyse.
{88809}{88856}Baci ju natrag. Hajde.
{88875}{88910}Što si dobila?
{89094}{89130}Promašaj. Oprostite.
{89166}{89207}Hej, ako moram udarati u triangl...
{89209}{89255}- ti moraš bacati loptu, dobro? | - Ok.
{89257}{89302}Izvuci ruku prema natrag. Tako.
{89304}{89394}Rame prema cilju. Odlièno. | Sad, iskorak naprijed.
{89396}{89454}Ne marširamo. Jedno stopalo.
{89456}{89525}- Dobro. | - Super si. Spremna? Evo.
{89531}{89564}Drži loptu iznad uha...
{89566}{89642}i kad ju bacaš, | pusti da ti sklizne s prstiju, ok?
{89671}{89698}Ok.
{89706}{89741}Hajde, baci ju.
{89883}{89926}Vidiš? Nauèio sam te neèemu. Što je?
{89928}{89988}Svaki put kad ju bacim, | otrèat æeš i dohvatiti ju?
{89990}{90032}To se tako uglavnom radi.
{90034}{90078}Kao da se igram štapom s mojim psom.
{90080}{90171}- Da, osim što ja ne ližem vlastita jaja. | - Bi da možeš.
{90179}{90204}O, da.
{90243}{90278}Dobro, još jednom.
{90294}{90323}Upravo ovdje.
{90352}{90415}Gle, onaj izgleda kao zeèiæ.
{90423}{90469}Ne izgleda.
{90501}{90551}Zeèiæ s jednim jajetom.
{90556}{90622}- Ne, to je rep. | - Štogod kažeš.
{90703}{90778}- Misliš li da æemo pobijediti? | - Naravno, pobijedit æemo.
{90780}{90883}- Ako napišeš dio za gajde. | - Nikad više neæu ponoviti tu grešku.
{90885}{90958}- Koju? | - Recital u osom razredu.
{90983}{91042}Natjerao si me da napišem dio za tebe.
{91097}{91144}Nosio si kilt.
{91177}{91237}Da, Steve je došao s frendovima.
{91252}{91305}Gadno su me zezali radi tog.
{91313}{91370}Danima nisam izlazio iz sobe.
{91377}{91454}Osvetio si mu se ukravši moje donje rublje...
{91456}{91513}kako bi ga stavio na stup za zastavu.
{91536}{91584}Èak i moje sportske grudnjake.
{91654}{91717}Buduæi da smo tako sentimentalni...
{91719}{91768}Žao mi je zbog donjeg rublja.
{91771}{91810}I dnevnika.
{91876}{91923}I svih drugih stvari.
{92889}{92916}I to je to.
{92929}{92998}- Ti si poèela. | - To æe mi donijeti školarinu.
{93000}{93025}Što?
{93027}{93091}Moram to zapisati prije no što zaboravim.
{93213}{93262}Možemo li to ponoviti sutvra uveèer?
{93264}{93333}Da, naravno. Vidimo se u sumrak.
{93400}{93459}Da ponesem Picardo?
{93461}{93515}Ok, odradit æu solo za tebe.
{93759}{93800}- Što ima, Ernie? | - Hej.
{94256}{94304}Opet je bila ona ružna sestra.
{94666}{94710}O, moj Bože.
{94712}{94744}Matt Stiffler?
{94762}{94874}- Èovjeèe, pogledaj se. | - Arrianna, što ti radiš ovdje?
{94876}{94956}Rutinske vježbe s bendom. | Što ti radiš ovdje?
{94958}{95016}Morao sam doæi. Škola me natjerala.
{95039}{95121}- Netko zna za to? | - Oni znaju sad.
{95146}{95222}Hajde, bez slikanja? | Što ste vi, papa-sise-raci?
{95224}{95266}- Ti bokca, super smiješno. | - Smiješak.
{95268}{95360}Dame. Nema vremena za bratimljenje.
{95384}{95482}Uzmite torbe. Još æemo se vidjeti, bendiæu.
{95486}{95588}Koji glupan. Poslat æu to svima mailom.
{96124}{96191}Cure, ovo je bilo sjajno. | Odmorite se, udaraljke.
{96193}{96235}Rogovi, moramo raditi na intonaciji.
{96237}{96300}Sutra je završna izvedba, ljudi.
{96320}{96364}Tako su nesposobne.
{96388}{96445}Sviraš triangl. Baš slatko.
{96465}{96541}Ne sviram. Rekao sam ti...
{96557}{96589}- Morao sam... | - Moram iæi.
{96591}{96671}- Ne družim se s bendiæima. | - Nisam glupavi bendiæ.
{96680}{96768}Nisam. Vidi. Samo se ponašam kao glupan.
{96775}{96846}Samo glumim da bih snimio skriveni video.
{96848}{96933}Potajice sam ih snimao dok rade svašta.
{96956}{97028}- Stvarno? | - Da, mogu ti pokazati.
{97091}{97147}Dobro, svrati nakon veèere.
{97159}{97222}Stavit æu pompone u prozor.
{98025}{98090}- Kasniš. | - Nemoj mi reæi. Otvori prozor.
{98170}{98216}Èekaj. Budi oprezna s tim.
{98434}{98512}Samo jedan uvjet | prije no što ti pokažem plodove svog truda.
{98514}{98543}Koji?
{98551}{98619}Želim da obrišeš onu fotku s mobitela.
{98898}{98973}Nitko u školi ne smije èuti ni rijeèi | o trianglu ili kapici.
{98975}{99038}Ne želim da se misli da sam glupavi bendiæ.
{99040}{99084}Dobro. Možemo li sad poèeti?
{99086}{99169}Èim obrišeš fotku s mobitela.
{99514}{99582}- Ideš li u grad? | - Ne veèeras. Preumorna sam.
{99584}{99647}Osim toga, deèki ovdje su više seksi.
{99649}{99719}Znam. Ove godine je dobra berba.
{100074}{100168}- Evo. Gotovo. | - Možemo li sad vidjeti video?
{100189}{100228}Stiffmeister produkcija...
{100230}{100316}u suradnji s novim talentiranim redateljem, | Matthew Stifflerom...
{100318}{100366}ima èast premijerno prikazati neobraðene...
{100368}{100475}nefiltrirane, nevjerojatne Napaljene bendiæe.
{100507}{100535}To.
{100555}{100589}Napaljeni Bendiæi
{100637}{100729}- O, Bože. | - Ovo je nevjerojatno.
{101272}{101328}- Zezaš me, ne? | - Ovo je sjajno.
{101363}{101439}Danielle se sviða Jimmy, | ali viša je za glavu od njega.
{101441}{101476}Èekajte da èujete ovo.
{101478}{101540}Sheree je spavala | s debelim Oskarom, bubnjarom.
{101542}{101581}Rekla je da je sjajan.
{101592}{101669}Ja sam bila jednom s Brandonom. | On je kao bubnjar. Nema...
{101671}{101717}ritma, a ne može ni bubnjati jako dugo.
{101719}{101762}O, Bože. Ti to ozbiljno?
{101764}{101864}Prerano svršava. | A ne govorim o njegovim godinama.
{101889}{101955}Možeš li mi namazati leða? | Mislim da sam malo izgorila danas.
{101957}{101982}Naravno.
{101987}{102057}Èuj ovo. Ima samo jedno jaje.
{102071}{102127}- Zezaš. | - Samo jedno.
{102154}{102225}Zato stalno i nosi okolo onaj veliki štap.
{102227}{102276}Na vrhu mu je drugo jaje.
{102353}{102396}Sranje, sranje.
{102469}{102505}Što je ovo?
{102842}{102874}Ubijmo to.
{102908}{102937}- Kamo je otišao? | - Tamo je.
{102939}{102966}Pazi se.
{103923}{103969}Ovo æe završiti u jezeru.
{103994}{104054}Nitko neæe znati za tvoj video.
{104056}{104119}Jer sadržaj koji se vidi na njemu...
{104240}{104328}Sutra moramo pobijediti na natjecanju. | I ne želim te vidjeti.
{104337}{104365}Jasno?
{104512}{104548}Jesi li mu pomogao?
{105145}{105181}S East Great Fallsom u vodstvu...
{105183}{105254}Beechwood mora pobijediti | u završnim utakmicama Glazbenog kampa.
{105256}{105309}Uputite se prema polju za marširanje | u toku jednog sata.
{105311}{105342}KUP TALL OAKSA | ŠAMPIONAT U MARŠIRANJU
{105344}{105425}Vidite, Dr. Choi, | Brandon Vandecamp iz Beechwooda...
{105427}{105482}je naš daleko najbolji glazbenik...
{105484}{105604}a otac mu je, Landon, | isto tako naš najveæi donator.
{105626}{105728}Robards treba nadarene glazbenike | ali i darežljive donatore.
{105730}{105776}VIŠNJA-LIMETA-NARANÈA-GROŽÐE
{105907}{105939}lpecac.
{105996}{106073}- Pa, što ima? Zabavljate se? | - Dobro je.
{106203}{106256}Hoæeš malo Ipecaca, Vande-govno?
{106326}{106419}Ovaj æe ti biljni ekstrakt pomoæi da ti, | Beechwoodova maskota, dobro sviraš, ha?
{106456}{106481}Sranje.
{106708}{106766}Rekao sam ti da te ne želim više vidjeti.
{106768}{106829}Jednog æeš mi dana zahvaljivati, seronjo.
{106935}{107000}- Naranèa? | - Opet?
{107013}{107062}- Do vraga. | - Ova naranèa je odvratna.
{107064}{107110}Probat æu grožðe, prijatelju.
{107179}{107274}Baš me briga koliko puta pobijede. | Danas neæe piti sok od grožða.
{107276}{107333}Tako se govori.
{107373}{107442}Peterostruki šampioni...
{107457}{107501}Beechwood Academy.
{107749}{107796}SUCI
{108270}{108348}- Dobri su. | - Ove su godine bolji no ikad.
{108350}{108385}U redu, društvo.
{108397}{108455}Nije iznenaðenje da je Beechwood dobar.
{108459}{108544}Ali ova je godina drugaèija. | Ove ih godine možemo pobijediti.
{108566}{108643}Stvarno smo se trudili, | i dovoljno smo dobri...
{108645}{108707}a ovo je naš trenutak, pa osvojimo kup.
{108709}{108757}To!
{109594}{109635}Beechwood Academy.
{109637}{109722}Njihovu današnju glazbu | napisao je glavni bubnjar...
{109724}{109771}Brandon Vandecamp.
{109775}{109805}Nadmašite ovo.
{109873}{109958}East Grat Falls, | možete uæi na natjecateljsko polje.
{110373}{110449}- Bend 10 pokret. Jedan, dva, spremni. | - Sranje.
{110451}{110489}Leesy, èekaj, nemoj.
{110491}{110540}Ne. Èekaj.
{110787}{110843}Žao mi je. Ne znam što se dogodilo.
{110845}{110897}Ne na moje cipele. Evo ti.
{111013}{111039}Stiffler.
{111467}{111521}Ti si poput svog brata, Stevea.
{111523}{111610}I nisam baš siguran da ga trebaš | tako revnosno slijediti.
{111612}{111686}Znaš, ljudi | koje je Steve smatrao prijateljima...
{111689}{111752}- Baš ga i nisu jako voljeli. | - Što?
{111754}{111789}Ali vjerujem da si ti drugaèiji.
{111791}{111893}Mislim da te ljudi žele voljeti. | Ali se moraš jako potruditi.
{112237}{112330}Rastanak je slatka tuga. Kad si gubitnik.
{112487}{112590}G. Levenstein piše | da je bilo nekoliko incidenata...
{112592}{112623}u kampu.
{112635}{112695}Ali isto tako kaže...
{112698}{112788}da si nakratko prijateljevao s bendom.
{112885}{112987}Kad poène škola, pozorno æemo te pratiti.
{112992}{113082}Zapamti, Shermanator vidi sve.
{113115}{113146}Odlazi.
{113264}{113317}Jesu li svi mrzili mog brata?
{113589}{113676}Poèetni datum: 21. kolovoza 2005.
{113690}{113747}Uèinjen mali pomak sa Sttifyjem mlaðim.
{113757}{113816}Promjena ponašanja vidljiva.
{113851}{113893}Nastavit æemo promatrati.
{113908}{113962}Shermanator završio.
{114229}{114288}Malo akcije sa "Sheree Košarice D."
{114398}{114443}Malo Dr. Robota.
{114487}{114523}Ludi fuker.
{115258}{115290}Obriši
{115374}{115406}Bastuba
{115443}{115473}Veliki O & DD
{115540}{115576}Vlažna 4 - Vlažna 6
{116158}{116190}Stiffleru, gdje ti je instrument?
{116192}{116221}Stari, nosiš pogrešnu uniformu.
{116223}{116290}Tko ih šljivi, stari. Pošizit æe kad vide video.
{116292}{116345}Ako bismo | imali pretpremijerno prikazivanje...
{116347}{116397}svi bi vidjeli da nisi totalni kreten.
{116399}{116456}Ne mogu. Sve je obrisano.
{116481}{116557}- Što? | - Video, èovjeèe, obrisao sam ga.
{116581}{116606}Zašto?
{116628}{116692}Mislim da mali braco | napušta obiteljski biznis.
{116694}{116730}Ti me zezaš?
{116815}{116868}Draži su mu glupavi bendiæi od nas.
{117192}{117250}Koncert POVRATAK U ŠKOLU | KARTE U PRODAJI
{117254}{117291}Hej, što ima, ljudi?
{117310}{117357}Mrtav si, smeæe jedno.
{117376}{117430}- A i ti, klinjo. | - Èekaj, èekaj, èekaj.
{117432}{117525}Stari, povraæanje je bio nesretan sluèaj. | Netko je zamijenio posude.
{117638}{117691}Ta naranèa je odvratna, stari.
{117708}{117824}Chloe, nikad nismo vidjeli Elyse golu.
{117842}{117889}Matt je iskljuèio kompjutor.
{117910}{117972}I zato mu moramo oprostiti?
{117998}{118063}- Još je uvijek šupak. | - U pravu si.
{118087}{118119}Šupak sam.
{118129}{118183}Ne mogu ispraviti sranje sa sprejem...
{118185}{118242}i ne mogu osvojiti taj Kup bendiæa.
{118245}{118314}Ali mogu pomoæi nekome | da dobije što i zaslužuje.
{118334}{118386}I ne tražim da mi oprostite.
{118391}{118453}Samo mi pomozite pomoæi Elyse.
{118653}{118700}Konzervatorij ROBARDS - 2005. - 2006.
{118715}{118774}- Imam broj. | - Kreni.
{118776}{118861}555-0171.
{118909}{118975}Nije trebao naliti Ipecac u nièiju posudu.
{118977}{119021}Mogli smo sami pobijediti.
{119076}{119179}Nije me briga što me snima kamerom. | Zapravo, briga me, ali...
{119205}{119259}Dušo, ovo je stiglo za tebe.
{119349}{119384}Iz Robardsa je.
{119419}{119450}Što kaže?
{119492}{119554}Dr. Choi me želi vidjeti?
{119565}{119612}Konzervatorij Robards
{119614}{119660}PARKING ZA OSOBLJE
{119982}{120030}- U redu. | - U redu.
{120035}{120081}- Ok. | - Ok.
{120121}{120147}Bog.
{120536}{120594}Dobar dan. Elyse Houston.
{120623}{120689}Imam sastanak s Dr. Choi.
{120715}{120801}- Niste zapisani. | - To mora da je pogreška. Vidite...
{120848}{120881}Imam pismo.
{121013}{121058}To je pismo, znate...
{121077}{121106}Lažno.
{121118}{121188}- To nije potpis Dr. Choi. | - Molim?
{121505}{121532}Stiffler.
{121623}{121677}Kurvin sine.
{121717}{121822}Što? Nije ti bilo dosta | što si me ponizio u Glazbenom kampu?
{121824}{121888}Morao si mi i ovo smjestiti?
{122378}{122419}Što se ovdje dogaða?
{122454}{122489}Ovo je moj bend.
{122500}{122545}A to je njena glazba.
{123943}{123968}Pa...
{123982}{124071}Vidjela sam razne | zanimljive pokušaje upisa...
{124087}{124128}ali ovo je prvi ovakav.
{124163}{124264}Izvrsna audicija, gðice. Houston. | Hajdemo porazgovarati o školarini.
{124299}{124335}Mislila sam da je Brandon pobijedio.
{124337}{124417}Ne, diskvalificiran je zbog plagijata.
{124419}{124446}To.
{124499}{124548}To je ono pravo.
{124648}{124705}O, Bože, ljudi, ovo je bilo sjajno.
{124719}{124816}- Baš vam hvala. | - Zahvali njemu. To je bila njegova ideja.
{124818}{124843}Naravno.
{124910}{124997}- Ti si sve ovo isplanirao? | - Uz pomoæ nekih prijatelja.
{125067}{125098}Doði.
{125209}{125266}Mislim da je ovo tvoje.
{125300}{125328}Znaš...
{125345}{125442}Picardo je vrsta piccola.
{125465}{125521}Ponekad si pravi šupak...
{125531}{125556}Stiffy.
{125557}{125890}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan  
