{1}{1}25.000
{1299}{1391} KRLETKA 
{3312}{3395}Agadore, gdje je Starina? | Nastupa za 5 minuta.
{5124}{5154}Armande.
{5156}{5207}Kennedyji su opet | došli na veèeru.
{5208}{5263}Treæi put ovaj tjedan. | Da im ne naplatimo?
{5264}{5334}Ted? - Samo mlaði.
{5346}{5425}Da bar doðe Ted. | Daj im besplatnu kavu.
{5513}{5589}Ostavite mjesta za kavu.
{5673}{5704}Gdje je Starina?
{5706}{5768}Agador kaže da stiže za 5 min.
{6702}{6793}Starina ne želi nastupiti. | Još je u ogrtaèu.
{6797}{6828}Kvragu!
{6830}{6875}Ne znam što se dogodilo.
{6877}{6955}Idi ga pripremi. | Doæi æu za tobom.
{7003}{7103}Neka se Carmen pripremi | umjesto njega. Za svaki sluèaj.
{7241}{7296}Dušo, molim te, odjeni se.
{7311}{7349}Neæu, Agadore!
{7351}{7442}Victoria Page veèeras | ne pleše ples crvenih cipela.
{7460}{7494}Niti ikada više.
{7495}{7542}Onda samo èarape, dobro?
{7544}{7590}Victoria Page je mrtva.
{7591}{7649}Ja æu ti ih navuæi.
{7650}{7691}Znaš kako je umrla?
{7692}{7753}Sama, plaèuæi za ljubavnikom.
{7756}{7831}Jesi li jeo? Loše izgledaš.
{7841}{7894}Molim te! Pomozi mi.
{7896}{7966}Što je to? | - Vitamini.
{7971}{8035}Kupila sam ih za Armanda.
{8041}{8105}Ali to je sada gotovo.
{8145}{8175}Dobro.
{8376}{8412}Alberte!
{8432}{8493}Gdje si? Doði!
{8516}{8566}Otvori. - Van!
{8567}{8621}Otvori! - Idi!
{8625}{8701}Ne želim da me | vidi. Grozna sam!
{8747}{8793}Sranje!
{8831}{8899}Zovem policiju!
{8913}{8948}Abre la puerta!
{8997}{9069}Otvori! | - Pokušavam, ali lud je.
{9070}{9105}Alberte!
{9153}{9191}Želiš me upropastiti?
{9192}{9247}Ne gledaj me! | Grozna sam!
{9249}{9303}Debela i grozna!
{9320}{9373}Agadore, boli me.
{9375}{9428}Znam. Proæi æe.
{9430}{9509}Neæe! Mrzim svoj život!
{9518}{9565}Jesi li ti lud?
{9566}{9601}Vani je gomila ljudi.
{9603}{9655}Samo sam ti za to dobra.
{9656}{9784}Ne mogu to podnijeti. | - Važna je samo predstava.
{9786}{9873}Èak ne naša | predstava. Tvoja predstava.
{9873}{9933}Želim ugovor o uzdržavanju!
{9935}{10014}Nemam sad | dokumente. Može sutra?
{10015}{10071}Nemoj tako sa | mnom. - Kako?
{10072}{10127}Sarkastièno i prezirno!
{10128}{10187}Kao da sve znaš | jer si muškarac,
{10188}{10235}a ja ništa jer sam žena.
{10237}{10294}Nisi žena. - Gade!
{10345}{10397}Smirite se.
{10398}{10457}Što god da jesam, | on je kriv za to.
{10459}{10535}Nekad sam bila lijepa. | Mlada i puna nade.
{10537}{10597}A pogledaj me sada!
{10599}{10710}Niska, debela, | nesigurna, sredovjeèna!
{10713}{10770}Zbog mene si nizak?
{10826}{10879}Što æu? Na redu je.
{10881}{10931}Da pošaljem Carmen?
{10940}{10983}Nemamo izbora.
{10989}{11052}Samo ne Carmen!
{11054}{11091}Kako se usuðuješ?
{11093}{11129}Hajde! - Ne!
{11130}{11182}Cyrile, idi. | - Molim te
{11183}{11275}Nastupit æu. | Ljudi žele vidjeti Starinu.
{11277}{11353}Starina ih ni ovakva | neæe razoèarati.
{11355}{11388}Mambo glazba.
{11390}{11455}Neka Beatrice i | Dante pripreme stube.
{11473}{11522}Tresu mi se ruke. | - U redu je.
{11524}{11576}Agadore, trebam Pirin.
{11577}{11628}Što piješ? - Ništa.
{11630}{11730}Samo jednu prije | nastupa i jednu poslije.
{11731}{11813}Ne traži više. | - Dragi mój Agadore.
{11841}{11892}Stavit æu ti ovo ovdje.
{11894}{11947}Diši. Ne misli na loše stvari.
{11949}{12041}Gužva je. Pustite | me da se pripremim.
{12043}{12099}Ostavimo je.
{12264}{12299}Što radiš? - Što?
{12300}{12353}Zašto mu daješ | tablete? Što je Pirin?
{12354}{12427}Aspirin s izbrisanim a i s.
{12435}{12493}Sjajna ideja. - Znam.
{12562}{12621}Sada briješ prsa?
{12644}{12696}Nisam ih stigla depilirati.
{12748}{12810}Najgore je kad se zapustiš.
{12829}{12930}Uèinila sam sve | kako bih ti bila privlaèna.
{12948}{13036}U godinu dana dobila | sam i izgubila 50 kila.
{13045}{13166}Sa 100 sam došla na | 60 i onda opet na 100.
{13171}{13234}A nisi ništa rekao.
{13237}{13351}Ni rijeè ohrabrenja | ni potvrde mog truda.
{13355}{13457}Ne bih izdržala | da nema Pirina.
{13461}{13521}Ako se ne pripremiš, ubit æu se.
{13581}{13626}Više me ne voliš.
{13628}{13664}Sranje!
{13666}{13717}Imaš drugoga. - Što?
{13718}{13754}Osjeæam to.
{13755}{13857}Vidjela sam kako se u | hladnjaku hladi boca bijelog vina.
{13882}{13934}Pijem samo crveno.
{13939}{13990}Kao i ti.
{14089}{14129}Nemam drugoga.
{14130}{14210}Prešao sam na bijelo | jer u crvenom ima tanina.
{14220}{14296}Vani je 150 ljudi, od | toga su pola Kennedyji.
{14297}{14416}Svi èekaju da | plješæu velikoj Starini.
{14422}{14469}Tanina?
{14474}{14546}Što radiš dok nastupam? | - Samo ležim ovdje.
{14547}{14659}Kamo ideš dok se lomim | na pozornici? Znam taj pogled.
{14668}{14707}Hajde, udari me!
{14709}{14780}To želiš. Udari me.
{14787}{14846}Udari me.
{15566}{15600}Dame i gospodo.
{15601}{15659}Jedina, jedinstvena...
{15660}{15735}Neusporediva Starina.
{16650}{16729}Hvala. Dobro došli u Krletku.
{16750}{16864}Vratila sam se sa | safarija. Imam novi muf.
{16894}{16970}Ima i modne dodatke.
{17011}{17095}Ne gledajte me | tako. Nisam ga ja ubila.
{17096}{17157}Uginuo je i sve mi ostavio.
{17208}{17300}Gdje je divan par | koji slavi obljetnicu?
{17319}{17384}Èestitam, dragi moji.
{17447}{17523}I ja æu možda | ubrzo imati što slaviti.
{17525}{17601}Mislim da sam našla pravoga.
{17643}{17676}Da.
{17679}{17746}Znate da se ne volim hvaliti.
{17748}{17833}Ali upoznala sam prodavaèa.
{17858}{17917}Jednostavan je.
{17943}{18006}Neki misle da je budala.
{18495}{18551}Isprièavam se.
{18592}{18630}Što kažeš?
{18632}{18681}Slièiš Lucynoj dvojnici.
{18695}{18758}Spoj sam Lucy i Rickyja.
{18760}{18873}I to je strašno. Donesi | bijelo vino u posudi s ledom.
{18875}{18932}Ohladi èaše i | uzmi slobodnu noæ.
{18934}{19011}Zašto mi se obraæaš | kao da sam sluga?
{19013}{19056}Jer si odani poslužitelj.
{19057}{19136}Otac mi je bio | šaman svog plemena.
{19141}{19200}Majka je bila sveæenica.
{19203}{19256}Kojeg su vraga | došli u New Jersey?
{19259}{19361}Bili su glupi. | Htjeli su da imam karijeru.
{19362}{19463}Halo? Karijeru? Kada | æu opet doæi na audiciju?
{19464}{19570}Kada stekneš talent. Svuci | periku. Reæi æu Albertu da je nosiš.
{19572}{19674}Onda æu mu ja reæi da se | s nekim viðaš dok on nastupa.
{19690}{19761}Dvije rijeèi. Zelena karta.
{19763}{19836}Idi! Ostavi vrata otkljuèana!
{19837}{19901}Sa svima si prava zvijer.
{19917}{19970}Doði, Gloria.
{21030}{21081}Sve ljepši si.
{21085}{21135}Hvala. I ti si.
{21136}{21188}Ma ne. Zbilja?
{21198}{21254}Osjeæam se napuhano.
{21316}{21411}Misliš da dobro izgledam? | - Sjajno izgledaš. - Baš lijepo.
{21480}{21539}Drago mi je što si se ošišao.
{21589}{21639}Jeo si? | - Jesam.
{21640}{21671}Neko piæe?
{21673}{21762}Pivo, ako imaš. - Nemam. | Kad smo kod napuhavanja.
{21780}{21817}Bijelo vino.
{21818}{21859}Krasno.
{21871}{21948}Kako dugo Albert nastupa? | - Tek je poèeo.
{21978}{22039}Agadoru sam dao slobodno.
{22099}{22145}Sami smo.
{22146}{22192}Kao što si htio.
{22203}{22262}Otkad voliš pivo?
{22318}{22370}Nešto ti moram reæi.
{22375}{22453}Ali ne želim da budeš | onakav kakav znaš biti.
{22467}{22512}Bože!
{22544}{22596}Ženim se.
{22681}{22739}Nisam ti htio | reæi preko telefona.
{22741}{22837}S curom. Upoznao | sam je na faksu.
{22838}{22918}To je divno... | Jesi li uzrujan?
{22926}{22978}Reæi æu ti zašto.
{22984}{23053}Prvo, imaš samo 20 godina.
{23055}{23112}Tata, znam da sam mlad.
{23119}{23210}Ali uvijek si govorio da | znam što radim. I znam.
{23211}{23337}Nude mi poslove. Znam | što želim. I imam sjajan uzor.
{23340}{23388}Ma daj! | - Istina je.
{23389}{23454}Svi drugi dolaze | iz propalih brakova.
{23455}{23526}Ne laskaj mi. | To je jeftini trik.
{23631}{23683}Je li to u redu, tata?
{23685}{23710}Zar je važno?
{23712}{23755}Naravno da jest.
{23756}{23859}Reci da je u redu prije nego | što Albert doðe i zavrišti.
{23863}{23916}Ne mogu. Neæu.
{23925}{23965}To je previše suludo.
{23967}{24047}Ako to uèiniš, | sam si. Jasno?
{24049}{24120}Ne vraæaj se i | ništa ne traži od mene.
{24122}{24177}Ne želim ništa | imati s tim. - Dobro.
{24178}{24229}Ako tako misliš... - Mislim.
{24233}{24295}Dobro. Zbogom, tata. | - Zbogom, sine.
{24370}{24405}Znao si da blefiram.
{24407}{24473}Bio si dobar. | - Zbilja? - Nije bio loš.
{24474}{24521}Malo sam popustio.
{24521}{24574}Reci mi da je u redu.
{24594}{24708}Jest. Oduvijek sam to | htio. Samo ne ovako rano.
{24739}{24837}Pusti kovèege | i ostani neko vrijeme.
{24894}{24959}Popijmo zdravicu | ovoj katastrofi.
{24960}{25007}Šalim se.
{25023}{25065}U redu je.
{25066}{25117}Kako se mlada dama zove?
{25117}{25144}Barbara.
{25155}{25214}Jesi li ti luda? | Ne dolazi u obzir!
{25216}{25255}Udaja! Nemaš ni 18!
{25257}{25323}Tko je on, Barbie? | Kad si ga zadnji put vidjela?
{25324}{25362}Ne zovi me Barbie.
{25364}{25447}Danas u 2. Spavam s njim | veæ duže od godinu dana.
{25452}{25513}Bože! Je li se testirao?
{25514}{25544}Kevine!
{25546}{25593}Jest. I ja sam.
{25631}{25712}Èekaj dok ne završe izbori. | Ne mogu sada o tome.
{25714}{25820}Odakle je, Barbie... ra? | Tko mu je otac?
{25823}{25947}Bavi se umjetnošæu. | U Umjetnièkom vijeæu je.
{25948}{26024}Da? - Financirali su | Mapplethorpeovu izložbu?
{26024}{26126}Ne! On je kulturni | ataše u Grèkoj.
{26130}{26170}Zbilja?
{26171}{26211}Koji je to vrag?
{26213}{26347}Poput diplomatske dužnosti. | Neka je vrst veleposlanika.
{26349}{26398}Èime se bavi majka?
{26404}{26454}Kuæanica je.
{26456}{26523}Lijepo, za promjenu. | Nije li, Kevine?
{26525}{26578}Ne mogu sada o tome.
{26619}{26661}Halo? | - Dobro si?
{26663}{26737}Jesam. Sad sam im rekla.
{26738}{26827}I ja. Mój je otac uzbuðen.
{26828}{26901}Upravo nam nazdravlja.
{26907}{26982}Evo ti ga. Hajde, uzmi.
{26988}{27071}Rekla si da su u Grèkoj! | - Skini se s telefona!
{27114}{27156}Zdravo, Barbara.
{27157}{27200}Za vašu buduænost.
{27201}{27278}Sranje! Ne, dušo, to | nije bila moja zdravica.
{27279}{27345}Slomila mi se èaša. Oprosti.
{27346}{27434}Bilo mi je drago. | Èujemo se poslije.
{27446}{27497}Kako se usuðuješ prisluškivati!
{27498}{27553}Rekla si da su mu | roditelji u Grèkoj. - Jesu.
{27554}{27649}Vidjela si ga danas, | a sad je s njima u Grèkoj?
{27694}{27733}Nije.
{27780}{27832}Grèka?
{27842}{27896}Vratili su se preko zime.
{27897}{27949}Kod kuæe su u South Beachu.
{27950}{27999}To je poput Palm Beacha?
{28001}{28100}Blizu je. Dvije minute | vožnje od kuæe Jeba Busha.
{28107}{28160}Zbilja?
{28608}{28652}Èekaj. - Tko je on?
{28654}{28722}Gdje je tvoja fufa?
{28728}{28795}Ne vièi. To je Val.
{28810}{28851}Val?
{28859}{28961}Spava u svojoj sobi, | pogledaj ako mi ne vjeruješ.
{28990}{29039}Zašto mi nisi rekao?
{29041}{29095}Iznenaðenje.
{30094}{30147}Dobro jutro!
{30243}{30296}Lijepo cvijeæe.
{30296}{30343}Dobro jutro, Alberte.
{30414}{30494}Jutros imamo svježeg | jastoga, Alberte.
{30520}{30627}Hvala, ne danas, g. Lopez. | Danas se vratio Prašèiæ.
{30639}{30677}Da vam dostavimo tortu?
{30679}{30791}Da. Neka piše, Mom | Prašèiæu od njegove tete.
{30792}{30822}Dobro.
{30824}{30916}Hvala. Želim se vratiti | prije nego što se probudi.
{30920}{30976}Kušat æu ovo.
{30985}{31036}Èokoladni schnecken.
{31105}{31157}Trijumf! Zdravo.
{31187}{31256}Možda još jedan na | put, ako vam ne smeta.
{31259}{31310}Kada schnecken šmeka...
{31356}{31408}Dobro jutro. | - Još nije.
{31410}{31466}Hvala. | - Nema na èemu.
{31478}{31529}Ovo je mulj?
{31531}{31608}Da. Za malu | promjenu od kave.
{31634}{31712}Zašto nisi rekao | da Val dolazi, zloæo?
{31714}{31784}Ne bih bila takav s tobom.
{31787}{31832}Odjeni se.
{31833}{31886}Zašto me ne | pustiš da nastupim?
{31887}{31963}Bojiš se moje | gvatemalnosti?
{31967}{31996}Èega?
{31997}{32061}Gvatemalnosti. | Moje prirodne vruæine.
{32062}{32106}Bojiš se da sam primitivan.
{32108}{32193}Da ne mogu biti na pozornici | s estrogenskim plesaèicama.
{32194}{32253}Da. Bojim se tvoje vruæine.
{32257}{32341}Evo me. Nosaèica. | Dobro jutro, Agadore.
{32344}{32446}Operi ovo. Ostalo | æe donijeti popodne.
{32449}{32500}Dobro jutro.
{32504}{32556}Ta brada!
{32568}{32626}Izvoli. | - Hvala, dušo.
{32712}{32766}Turska kava. Izvrsna.
{32768}{32807}Vidiš?
{32809}{32851}Val još spava?
{32853}{32950}Sigurno je iscrpljen. | Trebao si mi reæi da dolazi.
{32960}{33063}Sramim se svog ponašanja, | ali kako sam mogla znati?
{33068}{33149}Ne želim svog sina | dijeliti sa mnom.
{33150}{33193}Tjeraš me od sebe.
{33204}{33312}Vidi tu košulju! Krpa!
{33313}{33414}Koliko god mu ih | pošaljem, on uvijek nosi ovu!
{33423}{33490}Grozno izgledaš. | Što ti je?
{33492}{33525}Val se ženi.
{33526}{33602}Ne budu blesav. | Peèem svinjetinu za veèeru.
{33603}{33689}Htjela sam file minjon, | ali jako su skupi.
{33718}{33761}Kako to misliš, ženi se?
{33762}{33808}Znaš kako to mislim.
{33810}{33883}Ne shvaæam. | - Shvaæaš.
{33943}{34006}S curom koju je | upoznao na faksu.
{34008}{34073}Ne! Ali...
{34097}{34181}Još je dijete! | Upropastit æe se!
{34183}{34233}Sve smo to prošli.
{34245}{34317}Oženit æe se bez | obzira na to što kažemo.
{34319}{34367}Što manje kažemo, to bolje.
{34368}{34410}Bože!
{34469}{34523}A ujutro sam bila dobro.
{34558}{34653}Sada se iznenada | osjeæam veoma èudno.
{34656}{34700}Diši.
{34744}{34784}Èuo si.
{34788}{34881}Vallie! Mój Bože! | To mi je takav šok!
{34883}{34964}Ništa neæu reæi. | Obeæala sam tvom ocu.
{35001}{35078}Ali ako se tako mlad | oženiš nekom droljicom
{35080}{35154}cijeli æeš život | žaliti zbog toga. Eto!
{35155}{35198}To je sve. Dosta o tome.
{35236}{35307}Što stojiš? Daj mi pusu!
{35313}{35366}Ili si prevelik za to?
{35407}{35457}Zdravo, Albie.
{35481}{35591}Mali æe nas ostaviti. | Neæemo imati drugog.
{35595}{35649}Osim ako se ne dogodi èudo.
{35664}{35776}Kada smo senator i ja osnovali | Koaliciju za moralni red,
{35776}{35866}htjeli smo izraziti moralne, | a ne politièke stavove.
{35868}{35991}Senator Jackson kaže | da je moral stvar politike.
{35993}{36068}Pobaèaj, istospolni brak...
{36076}{36115}Divna emisija.
{36117}{36189}Najinteligentnija na televiziji.
{36191}{36233}Pornografije ne bi bilo
{36235}{36319}kada je politièari ne | bi štitili svojim zakonima.
{36320}{36384}Zato su oba Doma | sada republikanska.
{36424}{36473}To je sjajna platforma.
{36475}{36563}Drago mi je što uz | Jacksona, a ne Dolea.
{36564}{36604}Dole je previše...
{36606}{36636}Mraèan.
{36636}{36707}Htio sam reæi liberalan, | ali i mraèan je.
{36708}{36753}Moram joj dati otkaz.
{36754}{36818}Taj mladiæ za kojeg | se Barbie želi udati...
{36820}{36925}Gðo Porter, 2. stranica, 2. | Paragraf. Porno, a ne Pronto.
{36932}{37034}Možda su stara, ugledna | obitelj. Kulturni ataše...
{37036}{37154}Vaš menadžer kampanje | želi razgovarati s vama.
{37162}{37214}Hvala, Bridget.
{37434}{37476}Zdravo, Bene.
{37504}{37554}Spreman za što?
{37595}{37622}Što?
{37624}{37659}Što je, Kevine?
{37660}{37722}Jackson je mrtav. - Bože!
{37724}{37788}Umro je u krevetu? Èijem?
{37804}{37856}Prostitutkinom?
{37866}{37940}Maloljetnica? Crnkinja?
{37953}{38039}Ne mogu vjerovati! | Upropašten sam!
{38040}{38170}Nisi ti odgovoran | za njegov privatan život.
{38171}{38274}Potpredsjednik sam | Koalicije za moralni red.
{38275}{38363}Suosnivaè je umro u krevetu | maljoljetne crne kurve!
{38365}{38431}Èekaj da novinari to doznaju!
{38438}{38473}Bridget!
{38487}{38538}Dobro bi mi došlo nešto slatko.
{38539}{38592}Želiš li ovo?
{38594}{38636}Ovo.
{38643}{38698}Mali mój.
{38979}{39024}Alberte, izluðuješ me.
{39025}{39073}Znam, ali...
{39153}{39215}Nagrada za atletiku.
{39260}{39318}Bar micva.
{39378}{39448}Vrijeme brzo prolazi.
{39459}{39577}Izgledao je èudno, ali smiješio | se pa se nisam zabrinula.
{39579}{39633}Kako ih tako brzo snime?
{39634}{39684}Plate im.
{39690}{39741}Ne spominju te mnogo.
{39742}{39793}Još je rano.
{39796}{39884}Veèeras æete èuti | posljednje rijeèi sen. Jacksona.
{39887}{39936}Možete li snimiti kuæu?
{39937}{40040}Kada poènete snimati, | stajat æu ovdje.
{40042}{40144}Izgledao je èudno, ali | smiješio se pa se nisam zabrinula.
{40174}{40253}Ovo je dobro mjesto. | Ne znam hoæe li...
{40271}{40326}Možete li ondje?
{40340}{40439}Vidjet æe se dio kuæe. | Ne znam hoæe li izaæi.
{40561}{40594}Gdje je tata?
{40595}{40689}Otišao je razgovarati sa | savjetnicima. Nisu htjeli doæi.
{40691}{40769}Nisam ga smjela | pustiti. Kako æe uæi?
{40816}{40856}Mama.
{40899}{41005}Moram ti nešto reæi | o Valovim roditeljima.
{41007}{41062}Ne mogu nas okriviti za ovo.
{41064}{41166}Jackson je bio seljaèina | i nismo se družili s njim.
{41168}{41275}To mogu shvatiti. | Dobro je što nisu snobovi.
{41535}{41579}Što radiš ovdje?
{41581}{41658}Došao sam kroz | voænjak, preko štale.
{41659}{41711}Opasno je. Mogao si pasti.
{41712}{41805}I jesam! Svi | govore samo o ovome.
{41839}{41916}Kevine, možda | postoji rješenje.
{41917}{41985}Smrt? Njemu nije pomogla.
{42017}{42109}A vjenèanje? | Veliko, bijelo vjenèanje.
{42111}{42167}Kakvo, tko se udaje?
{42187}{42227}Ne!
{42231}{42303}Zašto? Vratilo bi ti ugled.
{42311}{42361}Vjenèanje je nada.
{42362}{42451}Bijelo vjenèanje je | obitelj, moral, tradicija.
{42452}{42509}Bilo bi osobito.
{42514}{42625}Sin kulturnog atašea, | svojevrstan diplomat
{42626}{42727}koji na nas ne gleda | svisoka zbog Jacksona.
{42728}{42784}Koji želi biti dio naše obitelji.
{42785}{42861}Zamisli naslovnice | Peoplea, Timea i Newsweeka.
{42862}{42937}Ljubav i optimizam | protiv cinizma i seksa!
{42939}{42989}Bilo bi to pozitivno!
{42990}{43067}Tražit æemo Papin | blagoslov. To nije teško.
{43080}{43165}Previše je kontroverzan. | A Billy Graham?
{43166}{43212}Preveliki liberal.
{43213}{43289}Gdje su slatkiši? | - Bilo ti je dovoljno.
{43290}{43343}Kako mu se zove otac?
{43356}{43398}Armand.
{43400}{43433}Coleman.
{43434}{43514}Pitam se jesu li u rodu | s Tish i Bobom Colemanom.
{43516}{43574}Jesu li iz Bostona? | - Ne bih rekla.
{43575}{43652}Moramo odmah otiæi u | South Beach. Veèerat...
{43721}{43799}Veèerat æemo s njima | i prespavati kod Bushovih.
{43800}{43913}G. I gða Armand Coleman | iz Grèke i South Beacha.
{44351}{44411}Kakav je to san?
{44495}{44571}Zašto izgleda stvarno?
{44623}{44716}Što ako se pokaže
{44716}{44815}da to nije samo san?
{44841}{44894}Vilenjaèki prah.
{44966}{45046}Doði, maleni snu i igraj se.
{45087}{45162}Ne boj se.
{45164}{45216}Nemoj izblijedjeti.
{45217}{45270}Brzo, maleni snu,
{45272}{45345}prije nego što nestaneš.
{45347}{45421}Ostvarimo te.
{45453}{45509}Vidio sam to.
{45511}{45593}To je nemoguæe. | Ili sam umjetnica,
{45594}{45694}ili transvestit koji | samo želi nasmijavati.
{45696}{45799}Proðimo do kraja. | - Moram shvatiti tu pjesmu.
{45800}{45892}Moram dati sve od sebe. | Svi drugi mogu proæi do kraja.
{45894}{45928}Žvaèe žvakaæu.
{45930}{45973}Pomaže mi da razmišljam.
{45974}{46021}Šteta žvakaæe.
{46023}{46076}Nastavimo. | I dosta razgovora.
{46077}{46128}Moramo razgovarati. - Sjedni.
{46130}{46197}Važno je. | - Tiho. Pokus je.
{46212}{46281}Ti si san, a ja sanjar.
{46288}{46353}Svaku te noæ sanjam.
{46372}{46457}Reci mi, snu,
{46459}{46561}Jesi li i ti sanjar?
{46571}{46662}Možeš li doæi gore? | - Ne mogu sada.
{46735}{46820}Vidio si što je uèinio? | Zdravo, Vallie, dušo.
{46827}{46958}Napuhao je balon! Ne | može tako dok pjevam!
{46960}{47011}To je transvestitski nastup.
{47013}{47114}Ali trebao bi biti dobar. | Fantastièan, ako je moguæe.
{47115}{47190}To što imaš 22 g. I | veliki... - Ja æu, Alberte.
{47191}{47243}Redatelj si. - Hvala.
{47244}{47322}Ovo je kompleksna | pjesma puna mitskih tema.
{47323}{47395}Žena koja pjeva stvorila te.
{47396}{47497}Njezina si fantazija. | Iznenada ti, fantazija,
{47499}{47600}vidiš nju koja te izmislila i | ona postaje tvoja fantazija.
{47630}{47700}Ne shvaæam. | - Uzmi još žvakaæe.
{47701}{47745}Alberte. | - Èujem te.
{47746}{47791}Hvala. Znam.
{47806}{47876}Poènimo s idejom da,
{47877}{47955}kada vidiš to | divno, seksi biæe,
{47957}{48049}prolazi tvoja potreba za | žvakanjem. Naelektriziran si!
{48050}{48138}Nešto ti se uzburka u | pelvisu i popne ti se do srca,
{48139}{48205}gdje postaje pelvissrce.
{48207}{48259}Da? Evo me!
{48260}{48317}Da samo stojim ovdje?
{48318}{48393}Otpleši eklektiènu | plesnu toèku!
{48395}{48495}Budi Fosse ili | Martha Graham!
{48496}{48609}Ili Twyla, Twyla! | Ili Michael Kidd!
{48611}{48717}Ili Madonna! Ali | drži sve to u sebi.
{48733}{48837}Radi na tome. Vratit | æu se. Sjajno izgleda.
{48839}{48888}Barbara dolazi s roditeljima.
{48889}{48934}Kada? - Sutra.
{48935}{48975}Dovoljno vremena.
{48976}{49051}To nije sve. | Ima još mnogo.
{49156}{49184}Vino?
{49185}{49287}Reci mi što je. | Moram se vratiti na pokus.
{49366}{49461}Barbarin otac | konzervativni je senator.
{49476}{49577}Kandidirao se za novi | mandat. Barbara mu je rekla...
{49630}{49732}Da si kulturni ataše u | Grèkoj i da je Albert kuæanica.
{49743}{49867}Što? - Morala je. Utemeljitelj | je Koalicije za moralni red.
{49868}{49987}Briga me. Ne želim biti | netko drugi. Želiš da budem?
{49989}{50069}Ne, naravno. Ne | želi ni ona. Ali...
{50070}{50154}Tata, on je Kevin Keeley.
{50168}{50219}Tko je Kevin Keeley?
{50229}{50271}Èitaš li novine?
{50273}{50378}Naravno. Variety, rubriku | Umjetnost i zabava u Timesu...
{50379}{50457}Što mi nisi rekao? | Ženiš se za neku nacisticu?
{50459}{50550}Ne. Konzervativan je, | kao i pola Amerike.
{50566}{50632}Ženim se za | nju, a ne njega.
{50633}{50684}Trebam pomoæ. | - Za ovo ne.
{50686}{50722}I prije si to radio.
{50724}{50772}Tajio tko sam? Nikada.
{50774}{50851}Što si rekao kad | sam krenuo u školu?
{50855}{50959}Da uèiteljici kažem | da si poslovni èovjek.
{50993}{51066}Bio si malen, a | ona je bila glupaèa.
{51068}{51118}Nisam htio | da te povrijede.
{51120}{51176}Sad je drukèije. | Muškarac si.
{51181}{51233}Još me mogu povrijediti.
{51253}{51363}Puno bi mi znaèilo | kada bi nam pomogao.
{51364}{51406}Samo jednu noæ.
{51418}{51511}To je ludost! | Trebao bih zatvoriti klub
{51512}{51612}kako bih se pravio da sam | kulturni ataše, što god to bilo.
{51614}{51707}A kako æemo Alberta | pretvoriti u kuæanicu?
{51708}{51809}Pošalji ga nekamo. | - Ti ga pošalji.
{51811}{51929}Neæe proæi kod njih. | Nekih se stvari moramo riješiti.
{51936}{51979}Kojih?
{51998}{52053}Ovoga, na primjer.
{52060}{52111}Neptun? To je klasik.
{52123}{52174}I ovoga.
{52182}{52234}Kirby? To je umjetnost!
{52236}{52283}A ovo?
{52450}{52491}Bolje?
{52739}{52856}To nije samo | nekoliko stvari. Sve.
{52858}{52934}Moramo to malo ublažiti.
{52948}{53026}Mora slièiti | domovima drugih.
{53029}{53133}Moramo sve promijeniti | kako bismo bili poput drugih.
{53150}{53224}A možda bi trebao malo...
{53254}{53332}Promijeniti gestikulaciju.
{53336}{53414}Što želiš reæi? | - Budi manje oèit.
{53428}{53480}Oèit sam?
{53774}{53834}Nedavno sam okreèio zidove.
{53894}{53982}Siði. Pokušava | mu oduzeti žvakaæu.
{54053}{54105}Odmah dolazim.
{54174}{54258}Da, šminkam se. | Da, živim s muškarcem.
{54287}{54353}Da, sredovjeèni sam peder.
{54354}{54447}Ali znam tko sam. Trebalo | mi je 20 g. Da to postignem.
{54448}{54523}To mi neæe uništiti | neki idiotski senator.
{54525}{54590}Jebe mi se za | to što on misli!
{54802}{54867}Još smo pred kuæom | senatora K. Keeleya,
{54868}{54944}suosnivaèa | Koalicija za moralni red.
{54951}{55034}Èekamo kolegu sen. | Jacksona, sen. Keeleya.
{55035}{55134}Sada ne znamo | je li kod kuæe...
{55135}{55215}Neki izvori govore | da je u kuæi sen. Dolea.
{55217}{55316}U takozvanom | Camp Keeleyu smo.
{55317}{55374}Èekamo da se pojavi senator.
{55376}{55465}Osnovao je | Koaliciju za moralni red
{55467}{55528}zajedno sa sen. Jacksonom.
{55532}{55633}Senator je pod opsadom | u svojoj raskošnoj kuæi.
{55635}{55689}Opkoljen je | medijskom vojskom.
{55690}{55779}Svi oèekuju njegov | komentar na ove dogaðaje.
{55906}{55957}Kamo ga vozite?
{55974}{56029}South Beach, Florida.
{56141}{56217}Narode, kruži | mnogo neslanih šala
{56219}{56291}na raèun smrti sen. Jacksona.
{56306}{56352}Evo još jedne.
{56360}{56467}Veèeras su Jayu gosti | Yasser Arafat i Kate Moss.
{56476}{56529}Ovo je nepodnošljivo.
{56741}{56788}Kevine, nemoj!
{56790}{56879}Siæi æu ljestvama. Ne mogu | se suoèiti s novinarima.
{56881}{56953}Neka me vozaè | pokupi kod voænjaka.
{56954}{57006}Ne želim izaæi sama!
{57008}{57108}Barbara æe biti s tobom. | Ne zanimaš ih ti.
{57131}{57172}Tata!
{57178}{57237}Idem na stražnji izlaz.
{57240}{57334}A što je s objavom | Barbarina vjenèanja?
{57335}{57415}Tek kada ih upoznamo. | Što ako se predomisle?
{57416}{57493}Pusti me. | Vidimo se u autu.
{57652}{57707}Izlazi! | - Sen. Keeley!
{57727}{57855}Hoæete li izgubiti glasove? | - Kakva je buduænost Koalicije?
{57900}{58001}Je li istina da je sen. | Jackson uzimao litij?
{58009}{58063}Gospodo! I dame.
{58065}{58141}Ja sam, poput | svojih kolega,
{58142}{58244}republikanaca i demokrata, | liberala i konzervativaca,
{58246}{58347}šokiran i rastužen uvjetima | pod kojima je naðen
{58348}{58454}senator Jackson, kao i | samom njegovom smræu.
{58463}{58520}Moja obitelj i ja
{58522}{58629}odlazimo iz grada na nekoliko | dana zbog razloga o kojima...
{58646}{58718}Moramo isplanirati dogaðaj...
{58738}{58781}Koji æe...
{58782}{58820}Ne mogu vam...
{58822}{58874}Koji æe možda zacijeliti
{58876}{58948}neke loše emocije
{58950}{59071}koje poslije smrti | sen. Jacksona svi osjeæamo.
{59078}{59134}Kamo æete, senatore?
{59142}{59251}Na našu farmu. To je | sve što vam mogu reæi.
{59252}{59338}Jeste li poznavali | curu? - Gdje je farma?
{60617}{60682}Agadore? Kvragu!
{60699}{60729}Što sam uèinio?
{60730}{60817}Preuredit æemo stan | za sutra. Kvragu!
{60834}{60894}To je za roditelje?
{60903}{60992}Moramo se riješiti | svega pretjeranog.
{61007}{61061}To je mnogo.
{61065}{61152}Morat æeš naæi odoru i | odjenuti se poput batlera.
{61163}{61215}Neæu. Slièit æu pederu.
{61220}{61278}Ali pederu u odori.
{61287}{61334}Ne pitaj, no govori.
{61335}{61414}Poèni sutra ujutro. | Ja æu rano izvuæi Alberta.
{61414}{61455}Odakle mi odora?
{61456}{61523}Reæi æu mu da mora | otiæi nekoliko dana.
{61524}{61575}Bit æe teško.
{61588}{61636}Imam mnogo posla.
{61660}{61700}Tata.
{61738}{61785}Hvala.
{61788}{61889}Uèini mi uslugu i neko | mi se vrijeme ne obraæaj.
{62233}{62288}Kevine, unajmimo avion.
{62289}{62342}Ne možemo izaæi iz auta.
{62345}{62400}Odmah æe nas vidjeti.
{62894}{62950}Volim sunce.
{62970}{63016}Da, divno je, zar ne?
{63025}{63137}Dobro bi ti došlo. Uzmi nekoliko | dana slobodno. Izgledaš umorno.
{63182}{63225}Što želiš reæi?
{63226}{63294}Ništa.
{63571}{63614}Nemoj se ubiti ovime.
{63620}{63675}Tko je u zahod | stavio Playboy?
{63676}{63728}Pusti, to èitaju.
{63730}{63804}Nemoj dodavati. Oduzimaj.
{63811}{63913}Požurite se. Mora | izgledati pristojno do 18 h.
{63915}{63963}To je prekratko.
{63965}{64035}Želim da bude armanijevski.
{64051}{64157}Ali ne vuci. Produži. | Ovako kao da je poplava.
{64218}{64256}Tako.
{64258}{64342}Nešto si htio reæi. | - Da izgledaš umorno.
{64344}{64426}Staro znaèi umorno. | Kažeš da izgleda staro.
{64428}{64485}Izgledaš odmorno | znaèi da je bilo kolagena.
{64486}{64553}Divno izgledaš. | Hajdemo u kupnju.
{64555}{64599}Želim iæi kuæi.
{64602}{64681}Po ovakvom danu? | Kupit æu ti što poželiš.
{64691}{64763}Sve? Moram | obuti druge cipele.
{64765}{64801}Kupit æu ti ih. | - Trebam èarape.
{64803}{64891}Kupit æu ti sandale. | - Što se dogaða?
{64892}{64960}Ništa.
{64996}{65047}Onda se vidimo gore.
{65049}{65089}Što je?
{65095}{65156}Ozlijedio sam | svoju stvar. - Što?
{65165}{65197}Gležanj.
{65199}{65256}Ne mogu gore.
{65257}{65301}Èekaj. Donijet æu ti led.
{65303}{65385}Ne! - Zašto? | Moja ruka!
{65430}{65475}Mrzim kad si histerièan.
{65476}{65515}Ne ostavljaj me!
{65600}{65640}Što je to?
{65642}{65722}Iz antikvarnice preko | puta. Previše maèo?
{65724}{65780}Nemoj dodavati.
{65852}{65911}Stavite soba na patio.
{65930}{65987}Ne budi dijete. Pazi!
{65989}{66032}Ne mogu brže.
{66033}{66071}Nasloni se na mene.
{66073}{66108}Trebam lijeènika.
{66109}{66174}Ne budi smiješan. | Èak nije ni natekao.
{66176}{66213}Moramo u bolnicu.
{66214}{66339}Pretjeruješ. Ne budi | takvo dijete. Samo sjedni.
{66435}{66477}Opljaèkani smo.
{66498}{66579}Nismo. Samo sam | iznio neke stvari.
{66584}{66640}Bit æe ovdje kad se vratiš.
{66677}{66719}Kad se vratim?
{66745}{66791}Kamo idem?
{66826}{66870}Nisi mu rekao?
{66895}{66934}Što?
{66995}{67083}Valova zaruènica veèeras | dolazi s roditeljima.
{67085}{67198}Mislili smo da bi bilo | bolje da ne budeš ovdje.
{67437}{67485}Shvaæam.
{67544}{67583}Shvaæam.
{67585}{67623}To je samo veèeras.
{67624}{67682}Samo dok su ovdje ljudi.
{67698}{67739}U redu je, dušo.
{67747}{67812}Nije strašno. Bolno je.
{67816}{67881}Ali nije važno.
{67946}{67978}Idem.
{67980}{68028}Samo jednu noæ.
{68029}{68079}Èudovište,
{68096}{68166}nakaza odlazi.
{68206}{68258}Bit æete sigurni.
{68488}{68538}To je dobro prošlo.
{68612}{68650}Alberte!
{68735}{68775}Alberte! Slušaj.
{68776}{68864}Idi! Mrzim te! Više | te ne želim vidjeti!
{68907}{68959}Srce mi puca.
{68967}{69036}Molim te, ne plaèi. | Dobro, možeš ostati.
{69038}{69094}Neæu jer me ne želite.
{69095}{69176}Možete me izbaciti kad | želite, bez kakvih prava.
{69178}{69223}Imam ugovor o uzdržavanju.
{69224}{69289}Opet lažeš. | Ovo je previše.
{69290}{69352}Previše gadarija i boli.
{69378}{69436}Opipaj mi bilo. | Jesam li dobro?
{69448}{69528}Vrlo je brzo. | Maknimo se sa sunca.
{69798}{69855}Konobaru! | - Dolazim.
{69861}{69905}Ovo je kraj, znam to.
{69907}{69951}Nije. Diši.
{69974}{70028}Hvala, Rodrigo. | Uobièajeno.
{70029}{70076}Odmah, g. Goldman.
{70099}{70170}Hvala. Sad je bolje.
{70233}{70323}Nisi ti kriv. Njezini | su roditelji budale.
{70335}{70372}Val je lud za tobom.
{70373}{70425}Je li? To mi pomaže.
{70453}{70500}Baš si drag.
{70526}{70569}Voda je hladna.
{70585}{70698}Možda je previše da me | predstaviš kao njegovu majku.
{70722}{70798}Reci da sam roðakinja | koja je došla u posjet.
{70799}{70841}Valov tetak. Tetak Al.
{70842}{70902}Èemu? Da bi bio | Valov gay tetak.
{70904}{70954}Mogu glumiti heteroseksualca.
{70956}{71015}Ma daj! Vidi | kako držiš èašu.
{71016}{71071}Mali prstiæ, držanje.
{71082}{71193}A ti? Oèito nisi | kulturni... Što god.
{71201}{71264}Ne ideš u muzeje | i jedeš kao svinja.
{71265}{71368}Konzervativcima ne smeta | ako si svinja. Samo ako si peder.
{71557}{71659}Jebeš njih! Naravno | da æeš proæi kao tetak.
{71667}{71732}Sjajno glumiš, | a ja sjajno režiram.
{71734}{71776}Zajedno možemo sve.
{71777}{71815}Armande! Zbilja?
{71817}{71884}Naravno. Imamo | pet sati vremena.
{71886}{71965}Prvo spusti mali | prst. Opet se digao.
{71980}{72032}I promijeni držanje.
{72033}{72113}Jesi li ti lud? | Što to radiš?
{72115}{72156}Prestani vrištati!
{72158}{72223}Uèim te da se | ponašaš poput muškarca.
{72249}{72329}Veèerat æemo. | Vježbajmo hranom.
{72370}{72417}Namaži senf na tost.
{72481}{72544}Nemoj žlicom. | Nemoj da tako kapa.
{72568}{72649}Uzmi nož i maži.
{72677}{72713}Muškarci mažu.
{72714}{72763}Mažu.
{72854}{72971}Spusti mali prst! Prsti ti | moraju biti èvrsti! Ne tresi se.
{72977}{73035}Nož drži hrabro, jako.
{73054}{73106}Probušio sam tost!
{73109}{73211}Pa što? Samo se nemoj | rasplakati kada to uèiniš.
{73222}{73281}Reagiraj poput | muškarca, smireno.
{73282}{73406}Reci si, Alberte, | probušio si tost. Pa što?
{73415}{73454}To nije kraj svijeta.
{73455}{73555}Alberte, probušio | si tost. Pa što?
{73586}{73658}Da. Nema | potrebe za histerijom.
{73660}{73729}Moram se sjetiti da | uvijek ima još tosta.
{73730}{73802}Tako treba. | Pokušajmo hodati.
{73803}{73873}Dok držim sendviè? | - Nema veze. Hodaj.
{73928}{73971}Dolje!
{74525}{74570}Previše ženskasto?
{74600}{74647}Zamisli ovo.
{74649}{74751}Istina, klišej, ali | zamisli. John Wayne.
{74752}{74811}A da poènemo | s nekim lakšim?
{74812}{74855}Ma daj! Voliš ga.
{74861}{74908}Ima poseban hod.
{74910}{75011}Lako ga je oponašati. Ako | je netko muškarac... Pokušaj.
{75017}{75105}Siði s konja | i uði u salun.
{75200}{75240}Lijep detalj.
{75607}{75653}Zdravo, gospoðo.
{75830}{75869}Nije dobro?
{75882}{75984}Savršeno je. Nisam ni | shvaæao da Wayne tako hoda.
{76396}{76433}Drži se.
{76531}{76571}Tip je manijak!
{76625}{76668}Što li je u South Beachu?
{76671}{76773}Armand Goldman, | ti stari... Znaš veæ što.
{76777}{76829}Jesi li gledao Dolphinse?
{76869}{76910}Totalno pederski?
{76931}{77025}Ne okreæi dlan dolje. | Želim se rukovati, ne ljubiti ga.
{77027}{77069}Ispravi zapešæe.
{77071}{77134}Ispravi, a onda stegni.
{77158}{77220}Ale, ti... Znaš veæ što.
{77222}{77283}To sam sad rekao. | - Sada to ja kažem.
{77284}{77330}Ispravi, stegni.
{77488}{77596}Ale, kujin sine! Vidio | si što je sudac svirao?
{77597}{77713}Dolphinsi su imali još | samo 30 m, 34 s prije kraja.
{77715}{77805}Što misliš kako mi je? | Šokiran sam, izdan.
{77842}{77887}Pogrešan odgovor?
{77896}{77963}Nisam siguran. Idemo opet.
{77970}{78004}Ovo je uzbudljivo.
{78005}{78058}Jest, stari. | - Tako je, amigo!
{78059}{78110}Jest, kvragu! | - Jest, kvragu!
{78148}{78203}Da, jebote! | - Da, jebote!
{78231}{78281}Još jedanput, kompa.
{78303}{78335}Žao mi je.
{78337}{78366}Samo polako.
{78367}{78415}Ti polako, stari.
{78419}{78489}On je naletio | na mene. - Pa što?
{78502}{78540}Zašto si takav kreten?
{78542}{78586}Zašto si ti budala?
{78711}{78763}Meni kažeš da sam budala?
{78783}{78858}Ne, govorim | budali iza tebe.
{78940}{79016}Oteklina je veæ | splasnula. Nije ništa.
{79018}{79106}Bio si moæan, divan, | veoma muževan.
{79110}{79159}Ponosim se tobom.
{79160}{79213}Taj majmun | izgledao je smiješno
{79214}{79315}dok ti je nabijao glavu u | zemlju. Ne zna se boksati.
{79318}{79369}Hvala. Divan si.
{79409}{79500}Donijet æu još leda. | Brzo se vraæam, ljubavi.
{79641}{79755}Možemo li za veèeras | unajmiti hetero sluškinju?
{79771}{79830}U South Beachu takvih nema.
{79869}{79921}I imam još loših vijesti.
{79921}{79984}Rekao sam Albertu | da može ostati.
{80003}{80045}Zašto?
{80064}{80133}Rekao je da mu puca srce.
{80134}{80189}Prijatelj mi je i partner.
{80194}{80254}Kako æe se predstaviti?
{80261}{80295}Kao tvoj tetak.
{80296}{80337}Mój tetak?
{80339}{80390}Zaboravimo sve ovo.
{80393}{80491}Ne budi tako negativan. | Imaš 20 g. Imaj malo nade.
{80493}{80595}Kako? Kada tebe i | tetka Alberta vide zajedno...
{80616}{80714}Bože! Osjeæao sam se | tako dobro, a sada...
{80731}{80774}Kakva zavrzlama!
{80775}{80824}Treba nam žena.
{80825}{80904}Albert bi prošao kao tetak | kad bi bila prisutna i majka.
{80905}{80975}Ironièno. Kada | trebaš ženu...
{81011}{81063}Mogu pitati tvoju majku.
{81067}{81135}Ne bi ona to uèinila. Bi li?
{81141}{81173}Kako možemo znati?
{81174}{81257}20 g. Me nije vidjela. | To ti dovoljno govori.
{81259}{81356}Prije 20 g. Bila je mlada, | uplašena, bez love, no sada...
{81357}{81409}Ne misliš valjda ozbiljno?
{81431}{81506}Nije pošteno što | Vala nagovaraš na ovo.
{81507}{81581}Pristala je?
{81622}{81673}Moja majka?
{81696}{81756}Bože! Armande?
{81768}{81855}Nevjerojatno! Prošlo | je 100 g. Gdje si?
{81866}{81914}Dolazim za 5 minuta.
{81916}{81954}Jedva èekam.
{81956}{82011}I ja. Zdravo.
{82071}{82111}Primit æe me.
{82131}{82210}Odbacit æu te do kafiæa. | Doæi æu za 15 minuta.
{82211}{82313}Idem s tobom. Sigurno | imaju nekakvu èekaonicu.
{82620}{82699}Trebam Katharine | Archer. Armand Goldman.
{82702}{82745}Uðite.
{82892}{82934}Sjedni.
{82967}{83001}Isprièavam se.
{83116}{83154}Army Goldman.
{83155}{83228}Kathie Archer. Ili se | prezime promijenilo?
{83229}{83314}Sad sam izmeðu | muževa. Sjedni.
{83369}{83426}Èesto mislim na tebe.
{83448}{83548}Svaki put kad vidim reklamu | za Krletku. Još si s Albertom?
{83550}{83598}Da, još smo zajedno.
{83609}{83643}A ti...
{83646}{83698}Vidim, dobro ti ide.
{83700}{83786}Zahvaljujuæi tebi. Ovo | sam otvorila tvojim novcem.
{83787}{83830}Trebao si uzeti dionice.
{83830}{83895}Dobio sam Vala. | Poštena razmjena.
{83920}{83955}Je li...
{83990}{84018}Kako je on?
{84020}{84081}Dobro. Želi se oženiti.
{84093}{84131}Da? Koliko ima godina?
{84132}{84176}20. - 20?
{84240}{84277}Bože! 20!
{84289}{84365}Danas te prvi put | u životu zbilja treba.
{84771}{84807}Svjetlucavo.
{84896}{84975}Imelda, otkaži moje | dogovore za veèeras.
{85109}{85211}Inaèe za radna vremena | pijem sok od povræa, ali ovo...
{85226}{85327}U zdravlje kæeri sen. | Keeleya i našeg Vala.
{85341}{85417}Nisam mnogo uèinila | za njega ovih 20 godina.
{85418}{85467}Ne brini se zbog toga.
{85474}{85525}Nisam majèinski tip.
{85569}{85622}Ja sam majèinski tip.
{85635}{85692}A Albert samo što nema sise.
{85879}{85954}Sjeæaš se predstave | na kojoj smo se upoznali?
{85955}{85995}Vrlo dobro.
{85997}{86046}Ljubav je u zraku.
{86050}{86089}Razni oblici.
{86090}{86164}Ljudi su svugdje
{86164}{86207}Poludjeli,
{86208}{86255}I ponašaju se èudno.
{86256}{86301}Èekaj.
{86317}{86390}Žene su na službi muževa,
{86392}{86460}djevice su oèito nervozne.
{86471}{86544}Djevice su oèito nervozne.
{86547}{86644}Ljubav je posvuda.
{86713}{86746}Ah, ciganka.
{86749}{86793}Bio si zgodan.
{86795}{86889}Nedostupan. | I imao sjajno tijelo.
{86894}{86941}Neugodno mi je.
{86942}{87018}Bojao si se. | Bilo je to slatko.
{87020}{87122}Zamalo da nisam umro. | Zatekao sam ženu u krevetu!
{87126}{87182}Platila sam vrataru 20 $ .
{87192}{87244}20 $ u ono vrijeme!
{87249}{87277}Bože!
{87279}{87304}Pomislio sam, Pa što?
{87304}{87330}Pomislio sam, Pa što?
{87333}{87434}Baš da vidim o èemu | heteroseksualci toliko govore.
{87478}{87512}Koliko smo trajali?
{87514}{87596}Znam toèno. Od | 2.30 do 3.45. Dvaput.
{87786}{87823}Ljubav je u zraku.
{87824}{87857}Ima je posvuda.
{87859}{87916}Neženje, èuvajte se,
{87918}{87981}Djevice, èuvajte se. | - Upozorene ste.
{87982}{88076}Ako osjetiš uzbuðenje, | a želiš ostati neženja...
{88087}{88161}Ostani kod kuæe i ne diši.
{88170}{88244}Moglo bi te zgrabiti
{88247}{88340}jer ljubav je posvuda!
{88524}{88558}Oprosti.
{88618}{88706}Sjajno izgledaš. | I još dobro plešeš.
{88709}{88762}I ti, Armande.
{88769}{88818}Hvala. Lijepo hladi.
{88824}{88928}Odakle sve ove dlake? | Nisi li imao glatka prsa?
{88942}{89015}Brijao sam se jer sam | htio izgledati mlaði.
{89016}{89093}Ovako je ljepše. | Mnogo muževnije.
{89094}{89144}Mnogo dlaka.
{89154}{89200}Daj da ih pipnem.
{89208}{89251}Lijep lanac.
{89255}{89331}Vidi kako sjaji u | tom gnijezdu dlaka.
{89336}{89384}Otkopèaj košulju.
{89386}{89444}Pazi, svilena je. | - Daj da taknem ta prsa.
{89445}{89516}Nemoj poderati. | - Ta lijepa, dlakava prsa.
{89518}{89594}Oprosti. - Nisam | ga mogla zaustaviti.
{89595}{89634}Alberte?
{90529}{90563}Je li Albert ovdje?
{90564}{90598}Nije.
{90600}{90711}Sjajno! Onda vozi iz | Miamija 30 km/s pod ruènom.
{90713}{90774}Morao sam doæi busom.
{90890}{90939}Veèeras æemo | nekoga razapeti?
{90940}{91019}Sviða ti se? To sam dobio | za onoga glupog soba.
{91020}{91099}Dodali su i knjige. | Sve to sutra ide natrag.
{91104}{91156}Dolazi li moja majka?
{91164}{91202}Doæi æe.
{91208}{91258}Hvala.
{91284}{91321}Eto. Vidiš?
{91323}{91360}Sve je u redu.
{91362}{91456}Došao sam po èetkicu | za zube. Agadore?
{91459}{91518}Na uobièajenom je mjestu.
{91607}{91683}Bilo bi mi drago | vidjeti vašu djecu.
{91685}{91767}Primi raspelo. | To je rekvizit muèenika.
{91825}{91928}Da, još jedna | šala na mój raèun.
{91972}{92050}Vjerojatno ste mi se | i ti i Katharine smijali.
{92052}{92146}Zašto ne? Više | nisam mlada ni nova.
{92151}{92204}I svi mi se smiju.
{92218}{92282}Znam koliko sam smiješna.
{92288}{92404}Jedino je rješenje otiæi | nekamo gdje nitko nije smiješan.
{92406}{92458}Gdje su svi jednaki.
{92481}{92520}Zbogom, Armande.
{92522}{92601}Gðice Albert! | Ne zaboravite ovo.
{92606}{92653}Ne želim da odete.
{92664}{92736}Dragi, odani Agadore.
{92757}{92812}Ostavljam ti stereo ureðaj.
{92814}{92883}Crvene èizme. | - Ne želim ih.
{92884}{92936}Perike. - Koje?
{92952}{93040}Najbolje. Neæe mi | trebati ondje kamo idem.
{93084}{93133}Dobro, nasjest æu.
{93146}{93187}Kamo ideš?
{93196}{93242}U Los Copa.
{93244}{93331}Ondje nema | nièega osim groblja.
{93370}{93448}Znam. Zato | nosim malo prtljage.
{93450}{93496}Aha.
{93502}{93611}Ideš na groblje s èetkicom | za zube. Vrlo egipatski.
{93668}{93706}Zbogom, Armande.
{93708}{93783}Gðice Albert, | èekajte! Nemojte!
{93818}{93859}Sranje!
{93861}{93918}Bit æe bolje bez tetka.
{93920}{93981}Što si mu uèinio? | Ide na groblje!
{93982}{94024}Smiri se! - Zašto?
{94026}{94078}Jer moraš pripremiti veèeru.
{94079}{94151}Idem za usranim Albertom.
{94298}{94339}Možeš li...
{94345}{94393}Znaš kuhati?
{94407}{94464}Tvoj otac tako misli.
{95073}{95149}Moje je groblje | u Key Biscayneu.
{95169}{95225}Meðu najljepšima | je na svijetu.
{95226}{95324}Lijepa stabla, | plavo nebo, ptice.
{95400}{95460}To u Los Copi je usrano.
{95536}{95587}Pravi si gnjavež.
{95632}{95710}Istina je. Više | nisi mlad ni nov.
{95718}{95768}I nasmijavaš ljude.
{95778}{95853}Još sam s tobom | jer nasmijavaš i mene.
{95854}{95936}Sada moram prodati svoje | mjesto u Key Biscayneu
{95938}{96020}kako bi me pokopali | kraj tebe u usranoj Los Copi
{96021}{96088}jer se želim i dalje smijati.
{96217}{96261}Što je to?
{96264}{96304}Proèitaj.
{96395}{96432}Ne shvaæam.
{96434}{96521}Ugovor o uzdržavanju. | Rekao sam ti da ga imam.
{96551}{96676}Piše da ti imam pravo | dati pola od svega što imam.
{96679}{96775}Tako je sigurnije ako se | nekom od nas nešto dogodi.
{96777}{96841}Ali tko je sada vlasnik?
{96848}{96890}Ti.
{97014}{97072}Ne želim to.
{97081}{97127}Onda mi daj pola.
{97129}{97192}Daj mi olovku. | Ne želim sve ovo.
{97247}{97286}Potpiši se.
{97681}{97737}Eto. Partneri smo.
{97752}{97840}Vlasnik si pola mog | života. I ja pola tvoga.
{97842}{97882}Pola kluba?
{97884}{97955}Kakve veze | ima? Uzmi sve.
{97970}{98009}Imam 50 godina.
{98010}{98098}Samo jedno mjesto zovem | domom. Zato što si ti ondje.
{98102}{98215}Kakve veze ima ako netko | nekomu kaže da može ostati?
{98277}{98329}To je naše.
{98697}{98725}Halo?
{98726}{98809}Otišla je, g. Goldman. | Ali uvijek pita za poruke.
{98810}{98846}Dobro, zapisat æu.
{98873}{98903}Recite.
{98934}{98979}Nemoj doæi...
{98992}{99097}Veleèasni Al Sharpton rekao je | da su zadnje Jacksonove rijeèi,
{99098}{99175}Novac je na ormariæu, | Èokolado, rasistièka.
{99176}{99237}Prostitutka se | zove Natumbundra.
{99239}{99321}Idiot Jackson! | Sad æe i crnci poèeti.
{99328}{99403}Barbarino vjenèanje | udaljit æe nas od svega.
{99405}{99530}Colemani su idealna obitelj. | Nisu se rastavljali. Jesu li?
{99549}{99624}Nisu. - Vidiš? | Spašeni smo.
{99668}{99768}Morao sam birati izmeðu | Alberta i tvoje majke.
{99771}{99823}Morao sam birati.
{99825}{99886}Odabrao sam Alberta.
{99923}{99966}Shvaæaš, zar ne?
{99968}{100017}Znao sam da hoæeš.
{100075}{100127}Ne mogu izravnati kravatu.
{100164}{100204}Sako æe je prekriti.
{100245}{100302}U ovom odijelu | slièim svom djedu.
{100318}{100400}Uvijek se ovako odijevao | i ubio se s 30 godina.
{100437}{100475}Posljednje upute?
{100477}{100545}Ne hodaj ako baš ne moraš.
{100573}{100620}I ne gestikuliraj.
{100662}{100690}To je sve?
{100691}{100732}Ne govori.
{100734}{100774}Puno.
{100811}{100866}Kakve veze ima? | Ovo neæe upaliti.
{100868}{100970}Ne budi tako negativan. | Možemo mi to izvesti.
{102367}{102402}Što je?
{102452}{102489}Nije dobro?
{102548}{102623}Zašto? Odjeven | sam poput vas.
{102669}{102717}Skinuo sam prstenje.
{102735}{102775}Nemam šminku.
{102830}{102873}Obièan sam...
{102913}{102952}Muškarac.
{103002}{103041}A to?
{103115}{103219}To? Pa da imam | bar malo boje na sebi.
{103403}{103488}Misliš da sam | u ovoj odjeæi
{103489}{103552}èak još i oèitiji, zar ne?
{103741}{103782}Imaš pravo.
{104032}{104111}Ali htio sam ti pomoæi.
{104216}{104258}A ti me mrziš.
{104290}{104340}Obojica me mrzite.
{104485}{104528}Ne mrzimo te.
{104597}{104656}Budi dobar prema meni.
{104673}{104748}Mnogo radi da zaradi.
{104787}{104846}Mnogo, dušo.
{104896}{104999}Mnogo radim da zaradim, | zato budi dobar prema meni.
{105028}{105065}Tako je.
{105067}{105120}Obuj cipele. Kasno je.
{105122}{105198}Nema smisla | da obujem cipele.
{105200}{105290}Nikada ih ne nosim | jer u njima padam.
{105296}{105345}Obuj cipele!
{105347}{105449}I govori normalnim | glasom. Ne radi to.
{105504}{105540}Dobro.
{105774}{105813}Armande. Katharine je.
{105815}{105848}U autu sam.
{105849}{105912}Dobila sam | poruku da ne doðem.
{105941}{106050}Ne. Rekao je da ne | doðeš kasno. Èuo sam ga.
{106072}{106151}I mislila sam da | je tajnica pogriješila.
{106153}{106205}Dolazim za pola sata.
{106244}{106281}Ti si, Val?
{106295}{106324}Da.
{106350}{106423}Vale, želim da znaš
{106425}{106514}koliko sam sretna što | ti tako mogu pomoæi.
{106532}{106580}Znam da je malo kasno.
{106583}{106626}Ne, u redu je.
{106660}{106702}Hvala na ovome.
{106765}{106835}Vidimo se za pola sata.
{106868}{106907}Mama.
{106923}{106962}Što?
{107002}{107078}Jesi li rekao, Vidimo | se za pola sata, mama?
{107079}{107128}To je bila... - Da.
{107131}{107192}Ne možeš je | nazvati. U autu je.
{107194}{107222}Jesi li ti lud?
{107225}{107300}Albert je veæ histerièan. | Kakav æe biti kad vidi nju?
{107302}{107350}Neæe me osramotiti.
{107351}{107434}Majka mi je. Nisam joj | mogao reæi da ne doðe.
{107435}{107513}Znaš da sam | bez nje u gabuli.
{107673}{107766}Znaèi, ovo je pakao. | I u njemu je raspelo.
{108262}{108338}Nisam baš ovako | zamišljala Palm Beach.
{108356}{108409}Kad su došli, | ovdje je bio samo pijesak.
{108411}{108487}Ovo su izgradili | dok su bili u Grèkoj.
{108655}{108733}Zakljuèao se. Uz | malo sreæe neæe ni izaæi.
{108816}{108918}Nisam vjernik i Židov sam, | ali hvala ako sve bude u redu.
{108947}{109066}Kad smo kod Židova, rekla | im je da se prezivamo Coleman.
{109112}{109142}Hvala.
{109183}{109220}Evo me.
{109250}{109283}Savršeno.
{109351}{109394}To je zbog cipela.
{109533}{109634}Dobra veèer. Ja sam | Spartak, batler Goldmana.
{109637}{109682}Molim vas, uðite.
{109766}{109808}Goldman?
{109811}{109884}Coldman. Spartak je...
{109887}{109933}Iz Gvatemale. - Nov.
{109941}{110002}Vale, moji roditelji.
{110028}{110072}Ovo je Val Coleman.
{110095}{110137}Coleman ili Coldman?
{110138}{110180}Coleman.
{110181}{110225}D se ne izgovara.
{110229}{110267}Mój otac.
{110319}{110364}Moja kæi Barbara.
{110365}{110403}Drago mi je.
{110442}{110492}Mój muž.
{110495}{110528}Èast mi je.
{110530}{110583}Imate jak stisak.
{110586}{110647}U Grèkoj ga morate imati.
{110729}{110803}Moja majka | stiže za 15 minuta.
{110804}{110872}S roditeljima je | u Palm Beachu.
{110874}{110931}Nije li to krasno?
{110933}{110997}Povezivanje naraštaja.
{111004}{111050}Da. Uðite.
{111131}{111209}Kako noga? Otac ima | staru nogometašku ozljedu.
{111211}{111263}I vi patite. | Gdje ste igrali?
{111265}{111319}U Grèkoj. | - U Miamiju.
{111331}{111369}Zanimljiva soba.
{111370}{111425}Ne misliš da je lijepa?
{111427}{111480}Jest. Vrlo...
{111490}{111611}Ugodna kuæa za odmor. | Volim strogoæu dekora.
{111622}{111728}Otac ovdje najviše | radi i razmišlja.
{111729}{111814}Znaèi i nije kuæa | za odmor, nego...
{111815}{111864}Samostan.
{111866}{111920}Krasna je.
{111938}{112004}Lijepe stare knjige.
{112040}{112080}Pogledaj.
{112082}{112162}Nancy Drew i sluèaj | izgorjele svijeæe.
{112175}{112222}Imate cijelu seriju.
{112224}{112267}Majèine su.
{112269}{112310}Sjednite!
{112331}{112371}Molim vas.
{112753}{112810}Proslavimo šampanjcem.
{112814}{112855}Baš lijepo.
{112862}{112903}Agadore! | - Spartak!
{112904}{113010}Agador Spartak. Želi da mu | se obraæamo punim imenom.
{113195}{113249}Možemo li dobiti šampanjac?
{113576}{113618}Ondje? Hvala.
{113662}{113699}Bog te blagoslovio.
{113722}{113755}Otišli su iza ugla.
{113756}{113816}Stražnji ulaz u | ovu zgradu. Klub?
{113818}{113857}Pogledajmo.
{113878}{113954}Imate veliku | odgovornost. Dvije kuæe.
{113955}{114009}Kada ste kupili ovu?
{114016}{114096}Prije 15 godina. | Ovo je bila židovska èetvrt.
{114098}{114190}Barbara nam je rekla | da je uokolo bio pijesak.
{114224}{114318}Znate kako kažu. | Gdje ima pijeska...
{114363}{114435}Evo ga. Šampanjac za sve.
{114462}{114509}I viski, ako imate.
{114584}{114628}Je li još netko kod kuæe?
{114644}{114728}Naša kuja Pirana. | Zatvorimo je kada imamo goste.
{114825}{114886}Ja æu natoèiti. | Idi dovrši veèeru.
{115119}{115204}Sjajan je kuhar, ali | još ne zna posluživati.
{115258}{115310}Gdje li je žena?
{115862}{115919}Bio je èudan.
{115934}{115975}Zbilja.
{115978}{116043}Pitao sam, Želiš | li se udati za mene?
{116044}{116130}Pitala je, Nisi li rekao | da æeš èekati 30. godinu?
{116131}{116166}Bilo je smiješno.
{116176}{116233}Da, zvuèi smiješno.
{116353}{116397}Kako je bilo na putu?
{116438}{116494}Lijepo. Vrlo | lijepo putovanje.
{116513}{116605}Vozili smo kako bismo vidjeli | promjenu godišnjih doba.
{116644}{116729}Dugo smo putovali. | Virginia, Kentucky,
{116737}{116777}Tennessee,
{116800}{116838}Georgia.
{116847}{116949}Bilo je èarobno doæi | s hladnog sjevera
{116952}{117026}na jug, gdje je uvijek toplo
{117028}{117136}i vidjeti velike | razlike meðu regijama
{117138}{117204}ove naše divne zemlje.
{117273}{117356}Žena i ja nekada smo | išli u Virginiu svake jeseni
{117357}{117410}i gledali kako lišæe žuti.
{117428}{117480}Virginia ima sjajno lišæe,
{117482}{117583}premda mislim da je | lišæe u Ohiu podcijenjeno.
{117652}{117718}Divno je voziti | autocestom l-75.
{117847}{117888}Divno.
{117889}{118014}Odlazili bismo u Virginiu da | pobjegnemo na neko vrijeme.
{118017}{118118}Kako bismo vidjeli | lijepe farme i prirodu.
{118135}{118218}Zapela sam u gužvi. | Poènite jesti bez mene.
{118220}{118279}Brda, planine...
{118323}{118400}Prava ljepota | grimiznim planina.
{118417}{118469}Fantastièno!
{118506}{118581}Crveno lišæe, | grimizne planine,
{118598}{118649}zelena polja.
{118723}{118782}A ceste! Crne.
{118813}{118868}Presijecaju zelenilo.
{118890}{118938}Sve te boje.
{118951}{118989}Stabla.
{119078}{119130}I Pennsylvania je lijepa.
{119169}{119219}Je li to bila moja žena?
{119221}{119265}Sada na telefonu?
{119267}{119342}Mislim da jest. | Unio sam se.
{119344}{119389}Vale, to je bila mama?
{119391}{119445}Da, zapela je.
{119452}{119504}Rekla je da poènemo jesti.
{119506}{119544}Ja bih se javio,
{119545}{119633}no zaintrigirala me | senatorova prièa.
{119642}{119687}Nije bila baš tako dobra.
{119689}{119739}Bila je divna.
{119748}{119850}Isprièavam se. Moram | to javiti Agadoru Spartaku.
{120231}{120272}Isprièavamo se.
{120349}{120421}Nikad ništa nije | ovako brzo pošlo po zlu.
{120422}{120457}Ovo je poput kletve!
{120459}{120535}Što æemo? | Da je èekamo ili...
{120547}{120623}Mokar si! - Znojim | se poput životinje.
{120624}{120705}Ne mogu ja ovo. | - Možeš! Možemo zajedno.
{120731}{120782}Dogaða se nešto èudno.
{120794}{120844}To je zbog Jacksona.
{120845}{120929}Žena nas ne želi | vidjeti, a otac je uništen.
{120931}{120979}Ma sigurno nije to.
{120986}{121088}Nešto drugo je. Nešto | izmeðu oca i batlera.
{121089}{121159}Nije ništa! | - Nešto jest.
{121161}{121216}Nije! Uvijek misliš najgore.
{121217}{121260}Ne! - Misliš!
{121261}{121325}Majka samo kasni. | - Èuj, mlada damo...
{121328}{121366}Kasni!
{121368}{121425}Pazi, mlada | damo. - Evo ih.
{121446}{121487}Isprièavam se.
{121525}{121603}Dat æemo joj | još pola sata.
{121603}{121650}Ako ne...
{121669}{121720}Evo me!
{121732}{121771}Molim vas,
{121771}{121859}oprostite što kasnim, | no nevjerojatna je gužva!
{121866}{121933}Senator i gða Keeley.
{121933}{122011}Drago mi je što vas | napokon upoznajem.
{122037}{122088}Ti si sigurno Barbara.
{122098}{122148}Kakvo lijepo dijete.
{122149}{122201}Zagrli me.
{122203}{122253}Ne boj se.
{122255}{122319}Divno. Srami se.
{122329}{122383}Drago mi je, gðo Coleman.
{122387}{122423}Goldman.
{122425}{122464}Zar se d izgovara?
{122465}{122556}Izgovara se Coleman? | Imali smo zabunu oko toga.
{122569}{122609}Ah, da. Coleman.
{122611}{122681}U Americi se d ne izgovara.
{122690}{122804}Cole d' isle au Man. Tako | to izgovaraju u Francuskoj,
{122806}{122866}gdje je Armandov dvorac.
{122868}{122945}U Grèkoj, gdje radi, | zovu ga Cole d'man.
{122947}{123052}Ovdje gdje živi to se | izgovara vulgarno Coleman.
{123054}{123162}Ne znamo gdje smo dok | ne èujemo kako nas zovu.
{123246}{123287}Sad je sve jasno.
{123291}{123328}Napokon.
{123350}{123413}Želim vas zagrliti, | gðo Coleman.
{123415}{123460}Moje drago dijete!
{123470}{123506}Dobra došla.
{123520}{123558}Pogledaj ovo.
{123560}{123648}Naše snimke za emisiju | o Jacksonu. Pojaèaj.
{123657}{123730}U takozvanom | Camp Keeleyu smo...
{123766}{123803}Kamo ga voziš?
{123836}{123885}South Beach, Florida.
{123921}{123999}Odakle ovo? - Od sinoæ | pred Keeleyevom kuæom.
{124013}{124138}Debeli radi za National | Inquirer. Harry Radman.
{124142}{124247}Strašno se udebljao | poslije Simpsonova sluèaja.
{124287}{124336}Ovo mora iæi u program.
{124347}{124404}Divno ste ovo sredili.
{124406}{124482}Sve je jednostavno | i nije natrpano.
{124489}{124575}Kod nas su posvuda | papiri. Vi muškarci!
{124578}{124622}Poput djece su.
{124624}{124716}Mogu upravljati svijetom, | ali ne znaju odabrati kravatu.
{124719}{124821}Znam. Svoga ne mogu | natjerati da kupi novo odijelo.
{124826}{124868}Armande, napadaju nas.
{124927}{125010}Neka ih. Takve ih | je priroda naèinila.
{125013}{125065}Možda sam staromodna,
{125066}{125178}no žalim ženu koja nema | vremena brinuti se za muža.
{125179}{125258}Tako je! Lijepo je | upoznati ljude poput vas.
{125260}{125312}Našu vrstu ljudi.
{125372}{125471}C-o-l-e-m-a-n. | Nema imena na zvoncu.
{125473}{125534}Ne mogu ga naæi.
{125537}{125639}A ime na ulazu u klub? | Goldman. To je blizu.
{125641}{125713}Imaš pravo. To bi | zbilja bilo posebno.
{125714}{125759}Pokušaj Goldmana. Kako?
{125761}{125800}Armand Goldman.
{125809}{125910}Èudna mi je ta zbrka | oko školske molitve.
{125912}{125987}Kao da bi Židovima, | muslimanima, ikomu
{125989}{126055}smetalo što se | djeca mole u školi.
{126057}{126096}To je ludost!
{126142}{126203}Hvala, Agadore | Spartak! Možeš iæi!
{126275}{126346}Dobar je, ali problematièan.
{126347}{126417}Nikad ne znamo | što ga nasmijava.
{126430}{126472}Bar govori engleski.
{126474}{126560}Zadnjih šest mjeseci | promijenili smo mnogo šofera.
{126561}{126653}A koliko smo mi sluškinja | mijenjali zadnjih 6 godina!
{126665}{126722}Rodney, Bruno, Chuck...
{126725}{126773}Treba vam još leda!
{126774}{126819}Sviðate mi se.
{126820}{126914}Nemate pametne knjige na | policama ni slike po zidovima.
{126921}{127017}Samo raspelo i topli, | obiteljski osjeæaji.
{127022}{127078}To Clintonu | nikako nije bilo jasno
{127080}{127143}kad je uveo molitve u školi | i homoseksualce u vojsci.
{127145}{127180}Još leda.
{127181}{127259}Idiotska tema. | Homoseksualci u vojsci.
{127261}{127343}Te frizure i odore. | Tko bi to htio?
{127361}{127437}Mama, ne govori o stvarima | u koje se ne razumiješ.
{127439}{127495}Nemoj tako s majkom. | Vrlo je inteligentna.
{127497}{127585}Mislim da homoseksualnost... | - Još mnogo leda za vas!
{127585}{127646}...slabi ovu zemlju.
{127649}{127774}To sam mislila dok nisam doznala | da je Aleksandar Veliki peder.
{127777}{127829}Kad smo kod homiæa u vojsci!
{127831}{127902}Što kažete na te Dolphinse?
{127973}{128018}Ja æu.
{128128}{128179}Mislim da smo naèeli temu
{128181}{128236}od koje je g. Coleman nervozan.
{128238}{128279}Ne krivim ga.
{128319}{128404}Znam da ste èuli kako | je umro sen. Jackson
{128430}{128477}Ah, to.
{128493}{128558}Da, grozna prièa.
{128585}{128648}Naravno, mi to ne vjerujemo.
{128651}{128683}Kako to mislite?
{128684}{128732}Oèito su mu to namjestili.
{128733}{128796}Voljela bih vidjeti obdukciju.
{128805}{128886}To je rekao i | Rush Limbaugh.
{128907}{128936}Isprièavam se.
{129102}{129203}Napetost. Kao da na ludom | konju jašeš prema zapaljenoj štali.
{129206}{129257}Veèera malo kasni.
{129260}{129341}Jer nisam imao | vremena za kupnju.
{129371}{129410}Cura je draga.
{129412}{129496}To dugujem Valu. Nije mu | bilo lako tako odrastati.
{129498}{129577}Oprosti što sam se smijao | gði Albert, ali kakva je to frizura?
{129579}{129667}Jebeš ga! To je | jedna noæ. Preživjet æu.
{129706}{129786}Pogrešno je ubiti | lijeènika koji vrši pobaèaje.
{129787}{129844}Mnogi protivnici | pobaèaja... - Tata?
{129847}{129906}Ne slažem se s njima, | no mnogi èvrsto vjeruju...
{129909}{129937}Ovdje sam.
{129939}{130011}Zaustavi lijeènike, | zaustavio si pobaèaje.
{130012}{130089}Smiješno. Lijeènici | samo rade svoj posao.
{130091}{130171}Bolje je ubiti majke. | To æe ih zaustaviti.
{130181}{130224}Doði na trenutak, dušo.
{130225}{130319}Znam. Ako ubiješ | majku, ubit æeš i fetus.
{130321}{130420}Ali ionako æe biti ubijen. | Neka potone s brodom.
{130431}{130478}Zbilja te trebam.
{130520}{130557}Isprièavam se.
{130723}{130769}Uvjeravam vas...
{130776}{130876}Majka se tom prièom | približava logiènom,
{130877}{130918}no apsurdnom zakljuèku.
{130919}{130978}Baš kao što je | Jonathan Swift uèinio
{130981}{131064}kad je predložio da irski seljaci | svojom djecom hrane bogataše.
{131065}{131134}Jedno mi je jasno | o tvojoj majci.
{131136}{131221}Strastvena je i slijedi | svoje srce. I volim je.
{131290}{131341}Goldman je vlasnik kluba,
{131343}{131444}živi iznad njega, vlasnik | je zgrade i homoseksualac je.
{131462}{131518}Ne može biti bolje.
{131604}{131661}Mogla sam plesati cijelu noæ.
{131665}{131735}Mogla sam plesati cijelu noæ
{131743}{131849}i još moliti za još.
{131882}{131915}Imate krasan glas.
{131917}{131973}Mogla sam raširiti krila
{131975}{132051}i uèiniti tisuæu stvari
{132065}{132163}koje prije nisam èinila.
{132195}{132259}Tvoja majka mora znati | da želim karijeru i brak.
{132260}{132338}Albert nije moja | majka. Transvestit je.
{132339}{132418}Znam, ali | stalno to zaboravljam.
{132427}{132496}Zvuèi baš poput majke.
{132509}{132588}To znam samo
{132598}{132692}kada on zapleše sa mnom.
{132709}{132803}Mogla sam plesati, | plesati, plesati
{132818}{132890}cijelu noæ.
{133016}{133063}Bravo!
{133147}{133223}Imate dobar glas, | Agadore Spartak.
{133227}{133323}Hvala svima. | Veèera je poslužena.
{133364}{133466}Divno. Ovuda. Glumila | sam Elizu u srednjoj školi.
{133478}{133529}Sigurno ste bili dražesni.
{133591}{133670}Uði. Zalijepit æu na | vrata poruku Katharine.
{133679}{133765}Gðo Keeley, ovamo. | Senator meni zdesna.
{133767}{133854}Vale, ovamo. | Barbara, dušo, sjedni.
{133860}{133909}Sjajna ste domaæica.
{133911}{133950}Hvala vam.
{133954}{134015}Sjajno se zabavljam.
{134034}{134087}O ovome sam sanjala.
{134091}{134194}Velika obitelj puna | ljubavi okupljena za trpezom.
{134195}{134247}Kao kada sam bila dijete.
{134248}{134300}Tako smo i mi odrasli.
{134305}{134393}Nije li bilo divno? | Sretne obitelji,
{134394}{134503}svi su govorili engleski | i nije bilo droge ni side.
{134505}{134541}Lakše s vinom, mama.
{134543}{134596}Zanimljiv porculan!
{134604}{134686}Slièi mladiæima koji | preskaèu jedan drugog.
{134688}{134729}Grèko je?
{134791}{134829}Ja...
{134846}{134883}Ne znam.
{134893}{134946}Nisam to prije vidjela.
{134948}{135024}Zbilja? Barbara, | donesi mi naoèale.
{135026}{135078}U torbi su mi kraj stolice.
{135079}{135136}Gdje su moje? | Ovo jest grèko.
{135138}{135263}Grèki mladiæi. | Goli grèki mladiæi.
{135267}{135343}I cure. Nemate | cure na tanjuru?
{135344}{135420}Ja imam jednu. | - I ja. Pogledajte.
{135422}{135483}Mislim da je to cura.
{135504}{135582}Onda dugo niste | vidjeli curu. Mladiæ je.
{135583}{135658}Možda mi trebaju | naoèale, ali to vidim.
{135671}{135748}Nisam ti našla naoèale | Možda su u autu.
{135755}{135804}Moje su tu.
{135857}{135916}Brže, idiote! | Gledaju tanjure.
{135918}{135981}Koji idiot izvadi | tanjure, a da ih ne pogleda?
{135982}{136025}Prestani vaditi! Daj.
{136027}{136106}Ne možeš | posluživati iz toga.
{136108}{136156}Èekaj! Još raèiæi.
{136165}{136213}Da vidim što rade.
{136219}{136259}Evo.
{136281}{136397}Agadorova sjajna juha. | Ne kuha je za svakoga.
{136405}{136494}Njegov specijalitet. | Juha od plodova mora.
{136496}{136541}Nije li to jaje?
{136544}{136614}Jest. To je huevo.
{136635}{136689}Tipièno gvatemalski.
{136697}{136767}Ondje u sve | stavljaju jaja
{136769}{136841}jer im kokoši | mnogo znaèe.
{136844}{136912}Jedina su im prava valuta.
{136927}{137005}Kažu da žena vrijedi | kokoši koliko je teška.
{137006}{137107}Bogatstvo muškarca | mjeri se njegovim kokotom.
{137109}{137152}Isprièavam se.
{137229}{137263}Koji je to vrag?
{137265}{137356}Slatko-kisela juha. Zašto si | rekao da su plodovi mora?
{137357}{137442}Koji je to vrag? | - Ne znam. Izmislio sam to!
{137444}{137495}Bože, ovo je noæna mora!
{137782}{137843}Gdje ste odsjeli na Floridi?
{137856}{137937}Kod Jeba Busha | na Fisher Islandu.
{137940}{138020}Fisher Island. | To je lijepo mjesto.
{138027}{138125}Ondje su mi roditelji | živjeli sve do smrti.
{138159}{138235}Niste li ih | posjetili u Palm Beachu?
{138240}{138278}Što?
{138318}{138382}Jesam. Sada...
{138401}{138451}Kada su mrtvi...
{138453}{138490}Preselili su se...
{138492}{138556}Premjestili su ih jer...
{138622}{138652}Pa...
{138667}{138752}Majka je govorila istinu, | živi na Fisher Islandu,
{138753}{138812}i neka te pokopaju | u Palm Beachu
{138815}{138892}i tako æeš dobiti | najbolje dijelove Floride.
{138932}{139009}Tata, uði. | Sve odlazi kvragu.
{139016}{139069}Nije skuhao glavno jelo.
{139073}{139144}Jest æemo samo juhu?
{139146}{139197}Seljaèka je | juha glavno jelo.
{139199}{139264}Zato sam toliko | toga stavio u nju.
{139266}{139303}Šuti!
{139309}{139379}Stavi poruku za | Katharine dolje na vrata.
{139381}{139459}Moram se vratiti dok | nisu došli do dna tanjura.
{139460}{139536}Imao sam mnogo posla | i nisam stigao kupovati!
{139538}{139568}Šuti!
{139580}{139632}Sve je u redu.
{139634}{139708}Šuti, vrag te odnio! | Prestani plakati!
{139710}{139789}Što stojiš? Samo | što nije došla! Idi!
{139808}{139861}Kvragu! | Jebeš raèiæe!
{139969}{140003}Bože!
{140024}{140093}To je on. | Njegov auto.
{140095}{140152}Tu se parkiraj. Gužva je.
{140156}{140193}To je raskrižje.
{140195}{140247}Pa? Novinari smo.
{140519}{140620}Katharine, nemoj doæi | gore. Sutra se èujemo. Armand.
{140622}{140673}Ovo æe biti sjajno.
{140710}{140816}Od toga dana poèeli su | tražiti groblje koje im se sviða,
{140817}{140864}umjesto da jedu tofu.
{140865}{140917}Tata je volio Key Biscayne...
{140919}{140994}Vrijeme je za desert. | Jesi li završio? - Da.
{140996}{141081}Popijmo kavu | u dnevnom boravku.
{141182}{141255}Njegov auto. Gledam ga.
{141302}{141379}Okruženi smo | transvestitskim klubovima.
{141385}{141431}Imamo odobrenje.
{141432}{141472}Tri?
{141549}{141591}Gdje su?
{141617}{141657}Iza ugla su.
{141839}{141905}Što mislite o | njihovu vjenèanju?
{141906}{141988}Ona ima samo 18, | a on 20 g., zato...
{142055}{142124}Zaboga! To kao | da dolazi odozdo.
{142135}{142208}Sigurno je iz | kluba iza ugla.
{142220}{142273}Ovo je u istoj zgradi.
{142275}{142377}Ma ne! Uvijek sam | mislila da je to neèiji televizor.
{142398}{142476}Majko, znaš da | živimo iznad noænog kluba.
{142487}{142538}Proputovala je cijeli svijet,
{142540}{142618}no u srcu je još cura | iz Grover's Cornersa.
{142619}{142687}Malo jesam naivna.
{142712}{142768}Ne sramite se porijekla.
{142770}{142864}Nije dvorac, ali | to je dobar dom.
{142884}{142964}Hvala vam. | Upamtit æu to.
{142972}{143083}Naravno, Armand je | profinjeniji od mene.
{143091}{143192}Ali on je iz | dobre obitelji.
{143211}{143296}Poput ovih dvoje | krasnih mladih ljudi.
{143298}{143338}Slažete se?
{143348}{143404}Gdje je zahod? | - Pokazat æu ti.
{143406}{143500}Želim da mi mama | Coleman pokaže. - Dušo!
{143502}{143552}Poljubac, dušo.
{143554}{143619}Samo idem na | zahod. - Idemo svi.
{143621}{143667}Ludi ste.
{143679}{143717}Moji muškarci!
{143718}{143777}Nije li to divno? | Svi smo zajedno.
{143778}{143862}Tako je dirljivo | da æu zaplakati!
{143886}{143957}Dogaða se | nešto vrlo èudno.
{143959}{143996}Znam.
{144013}{144053}Ta veèera!
{144072}{144148}Na tim je | tanjurima bilo nešto.
{144150}{144227}I sin je nestao | dok smo jeli.
{144238}{144290}Znaš što se dogaða. - Da?
{144297}{144346}Najstarija prièa na svijetu.
{144348}{144378}Što?
{144446}{144495}Ona je iz provincije.
{144536}{144618}A on je pretenciozni | Europljanin najgore vrste.
{144638}{144693}On i njegov | Cole d'... Kako veæ.
{144695}{144777}I taj dekadentni | porculan. Sve sam to veæ vidio.
{144778}{144835}Aristotel Onassis bio je takav.
{144837}{144914}I svi Francuzi. | Osobito Mitterand.
{144920}{144996}I Englezi. Osim | Margaret Thatcher, naravno.
{144999}{145100}Ali John Major sigurno ima | neku, a ona to ne može podnijeti.
{145101}{145144}Tko? - Gða Coleman.
{145147}{145204}Što je nju briga | za Johna Majora?
{145205}{145277}Ne može podnijeti njega.
{145280}{145358}Colemana i njegove | gadne europske tradicije.
{145392}{145484}Snob je. To spominjanje | Grover's Cornersa.
{145486}{145534}Kevine, baljezgaš.
{145536}{145621}Ljuti me koliko | je on prezire.
{145630}{145730}Vidio si ga kada ona | govori? Gotovo da je uplašen.
{145732}{145841}Ne da joj da vodi kuæu. | On je u kuhinji i poslužuje.
{145843}{145924}Govori onomu garavom | divljaku što da radi.
{146039}{146074}Što je?
{146081}{146175}Oprosti. Sve | sam upropastila!
{146177}{146271}Nitko nije primijetio | periku. Gdje je ljepljiva vrpca?
{146273}{146316}Sve su odnijele.
{146317}{146416}Imam kopèu. Upalit | æe ako ne mièete glavom.
{146417}{146466}Hvala. Draga si.
{146498}{146543}Oprosti, Vale.
{146556}{146659}Nisi toliko simpatizirao | s jadnom Bessie Jackson!
{146661}{146724}Bessie Jackson | bezosjeæajna je krava.
{146726}{146814}Ova je žena dama. | Postat æe ti dio obitelji.
{146818}{146936}Ako je grozan, možda se tvoja kæi | ne smije udati za njegova sina!
{146937}{147042}Nije grozan na taj naèin. | Neæe se uplesti u skandal.
{147047}{147108}Tek te sada vidim | u pravom svjetlu.
{147110}{147184}Uopæe te ne poznajem!
{147190}{147278}Ne brineš se za Barbaru. | Važna ti je samo karijera.
{147280}{147340}I jadna gða Coleman!
{147342}{147450}I ti se brineš za moju | karijeru. Htjela si taj brak!
{147452}{147555}Barbara æe izaæi na kraj s time | malim. Moderna je i žilava.
{147559}{147662}Gða Coleman plaèe kad joj | kažeš majka. Tako je ranjiva.
{147665}{147745}Srce mi puca. Takve | se žene više ne raðaju.
{147826}{147868}Evo me!
{147889}{147929}Zaboravila sam kljuè.
{147929}{147959}Tko je to?
{147961}{148014}Valova majka, gða Goldman.
{148018}{148062}Je li Armand ovdje?
{148098}{148133}Valova majka?
{148135}{148178}Gða Goldman?
{148196}{148288}Znaèi, tako! | Gad živi s ljubavnicom.
{148291}{148333}Ja æu otvoriti vrata.
{148335}{148386}U pogrešnoj ste kuæi!
{148419}{148534}Dobra veèer. Mogu li vam | uzeti torbicu kao inaèe? Ili...
{148559}{148597}Prvi put?
{148599}{148677}Vi ste sigurno | senator i gða Keeley.
{148680}{148793}K. Goldman. Drago mi je. | Oprostite što kasnim...
{148796}{148900}Oprostite, ali Barbara... | Što ona radi ovdje?
{148902}{148938}Objasnit æu.
{148940}{148994}Objasnite svima nama.
{148998}{149056}Ne želim sramotiti | ovu mladu damu,
{149057}{149123}ali koliko vaš sin ima majki?
{149164}{149239}Ova se žena predstavila | kao Valova majka.
{149242}{149295}Koliko ih ima?
{149410}{149456}Samo jednu.
{149553}{149600}Ovo je moja majka.
{149614}{149704}Mój je otac vlasnik | kluba. Moja majka nastupa.
{149738}{149768}Što?
{149779}{149871}Barbara i ja smo lagali. | Svi su lagali za nas.
{149893}{149943}Ovo su moji roditelji.
{149970}{150022}Ovo je moja žena.
{150036}{150087}Ona je rodila Vala.
{150108}{150162}Drago mi je, Katharine.
{150170}{150221}Vrlo lijepo, Vale.
{150223}{150273}Sjajno ste ga odgojili.
{150275}{150342}Hvala. Ponosimo se njime.
{150345}{150385}Ne shvaæam.
{150386}{150488}Barbara, on je vlasnik | toga kluba ispod?
{150539}{150587}Nije kulturni ataše?
{150635}{150729}Nije. I nije | oženjen kuæanicom.
{150738}{150799}I prezivaju se Goldman.
{150822}{150863}Židovi su.
{150865}{150909}Ne shvaæam.
{150934}{151010}Muškarac je. | Obojica su muškarci.
{151012}{151063}Ne možete biti Židovi.
{151065}{151105}Ne, Kevine.
{151107}{151177}Kevine, to je muškarac.
{151210}{151240}Što?
{151241}{151310}Ne shvaæaš? | Homoseksualci su.
{151312}{151402}Vlasnici su transvestitskog | kluba. Muškarci su.
{151489}{151533}Senatore Keeley,
{151537}{151641}to vam možda neæe pomoæi, | no mislila sam sve što sam rekla
{151643}{151773}o povratku obiteljskih | vrijednosti i èvršæem moralu.
{151780}{151818}Kao da sam poludio.
{151819}{151856}Vrlo je jednostavno.
{151857}{151909}Zvala vas je mama Coleman.
{151911}{152007}Kevine, ništa se nije | promijenilo. Još sam ista.
{152009}{152076}S jednom malenim razlikom.
{152110}{152162}Dobro, ne baš malenom.
{152285}{152325}Ne shvaæam.
{152326}{152405}Objasnit æu u autu. | Hajdemo, Barbara.
{152415}{152458}Ne idem.
{152483}{152544}Barbara, ne radi mi to.
{152571}{152669}Možda nisam ranjiva | poput gðe Coleman,
{152672}{152732}ali i ja imam osjeæaje.
{152752}{152813}Netko me mora voljeti!
{152889}{152983}Smiri se, Louise. | Barbara, idemo.
{153031}{153088}Ideš s nama. | - Molim te.
{153090}{153194}Rasplakao sam ti | majku, èekaju me izbori.
{153209}{153243}Usred skandala smo.
{153245}{153341}U domu sam homoseksualaca | koji imaju transvestitski klub.
{153342}{153422}Koliko života moraš | uništiti da bi se udala?
{153647}{153748}Voljela bih da | ste vi dio moje obitelji.
{153915}{154004}Samo želim reæi, | g. I gðo... Gospodine...
{154016}{154138}Kako veæ. Nadam se da to | neæe utjecati na vaše glasovanje.
{154188}{154230}Senatore Keeley!
{154273}{154306}Ne!
{154326}{154369}Jesi li ga snimio?
{154370}{154414}Nisam. Bih da ga nisi pozvao.
{154416}{154461}Htio sam da se okrene.
{154689}{154725}Strvinari!
{154788}{154897}Stigla je još jedna TV ekipa. | I auto. Piše Florida Eagle.
{154898}{154947}Samo su iz novina.
{154948}{154990}Veæ vidim naslov.
{154991}{155084}Jackson i njegove žene, | Keeley i njegovi muškarci.
{155085}{155125}Ovo je posve normalno.
{155127}{155231}Došao si upoznati roditelje | mladiæa za kojeg ti se udaje kæi.
{155232}{155326}Amerikance ne | zanimaju detalji.
{155328}{155392}Vjeruju samo naslovima.
{155393}{155507}To je njihova rijeè protiv | vaše da ste uopæe bili ovdje.
{155512}{155594}Prije ili poslije | morat æu otiæi.
{155596}{155664}Ljudi æe primijetiti | ako nestanem.
{155665}{155748}Još jedna TV | ekipa. Ulaze u klub!
{155777}{155855}Zamisli ti to! I baš | veèeras ne nastupam!
{155856}{155903}Je li tko za juhu?
{155904}{155943}Ne!
{155978}{156017}Tata, žao mi je.
{156019}{156051}Znam.
{156052}{156092}Senatore?
{156109}{156156}Još jedno za vas?
{156158}{156191}Zapravo ne pijem.
{156192}{156286}Ali sada je vrijeme | da se pretvarate.
{156325}{156378}Daj mi nešto slatko.
{156386}{156465}Možda se Keeleyi mogu | izvuæi na kraju nastupa.
{156466}{156532}Èekaju ih. Prepoznat æe ih.
{156590}{156645}Ne mora biti.
{157331}{157374}Pljesak za naše cure.
{157377}{157491}Bližimo se kraju. I vi | ste obitelj. Pjevajte i vi.
{157507}{157558}Obitelj smo.
{157596}{157648}Uz mene su moje sestre.
{157693}{157745}Obitelj smo.
{157789}{157844}Ustanite i pjevajte.
{159165}{159204}Kako æe dugo èekati?
{159205}{159306}Koliko moraju. Nemaju prièu | ako ga ne snime kako izlazi.
{159320}{159374}Ustanite i pjevajte.
{159806}{159849}Obitelj smo.
{159878}{159934}Uz mene su moje sestre.
{159976}{160025}Obitelj smo.
{160073}{160127}Ustanite i pjevajte.
{160168}{160221}Obitelj smo.
{160570}{160662}Oèaraj ih. Pokaži im. | Oduševi ih. Hajde.
{160745}{160786}Doðite.
{160959}{161010}Obitelj smo.
{161131}{161180}Obitelj smo.
{161417}{161493}Nikada nisam | plesao s muškarcem.
{161499}{161550}Za sve postoji prvi put.
{161591}{161630}Pardonirajte.
{161671}{161722}Sa mnom | nitko ne želi plesati.
{161722}{161797}To je zbog haljine. Znao | sam da æu izgledati debelo.
{161798}{161864}A ja? Lijepa sam | kao i drugi muškarci.
{161865}{161898}Ples?
{161909}{161949}Ne ti. Barbara.
{161950}{162032}Ne idi. Ne želim biti | jedina cura koja ne pleše.
{162033}{162111}Idi prema izlazu. | Brzo æemo doæi.
{162146}{162211}Jesi li za ples, dušo?
{163541}{163630}Doði za 20 min na križanje | ulica El Dorado i Palm.
{163634}{163708}Gospoðo, ni | za milijun dolara.
{165074}{165274}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan 
{165275}{165341}Bob Dole je krasan!
{165539}{165589}Koja je majka?
{165649}{165690}Ne znam.
{165724}{165768}Mazel tov!
{165773}{165861}U znak sjedinjenja | možete poljubiti mladu.
{166064}{166105}Oprosti.
