{1293}{1391}G R A D   K R I M I N A L A
{4805}{4930}Da ti nešto napravim?|Sendviè, sir? -Ne.
{4939}{4997}Pojest æu nešto na putu.
{5200}{5250}Na putu kamo?
{5255}{5311}Palm Springs, Rachel.
{5414}{5477}Ne želim se svaðati.
{5600}{5667}Kada se vraæaš?|-Za par dana.
{5702}{5756}Super.
{5771}{5816}To je Lee?
{5872}{5921}To je on?
{5933}{5999}Da, on je.|-Reci mu da dolazim.
{6301}{6368}Bok, Rachel.|-Bok, Lee.
{6520}{6600}Djeca su sve veæa.|-Da, da...
{6853}{6933}Dobar auto. Odakle ti?|-Pokupio sam ga.
{6945}{7025}Od nekoga koga znam?|-Nadam se da ne.
{7066}{7121}Jorge.
{7148}{7225}Samo trenutak. Dobro?|-Naravno. I ja sam to prošao.
{7387}{7436}Što je sad?
{7446}{7505}Prièala sam s mamom.
{7512}{7563}Opet traži novac?
{7571}{7649}Ne. Doæi æe da mi pomogne|s djecom.
{7668}{7747}Morat æu raditi dvije|smjene. -Sranje!
{7764}{7832}Jorge. -Moramo o tome|prièati baš sada?
{7837}{7912}Htjela sam prièati s tobom ujutro.|Nisi mi rekao da ideš.
{7929}{7979}Moram krenuti.
{8046}{8122}Ne brini. Dobro? On je dobar|odvjetnik. Izvuæi æe dobru
{8127}{8195}pogodbu. Sve æe biti|u redu. Dobro?
{8200}{8268}To ti je rekao prije nego|što si mu platio?
{8314}{8405}Zašto me moraš sada|gnjaviti s tim?
{8411}{8477}Nemoj da ti se mama useli|k nama. Èim se vratim,
{8483}{8552}odlazimo odavde.|Dobro?
{8675}{8733}Lud sam za tobom.
{8862}{8926}Pazi se. -Kao uvijek.
{8940}{8999}Budite dobri, pa æemo|vidjeti za kuænog ljubimca.
{9008}{9054}Dobro? -Dobro.
{9137}{9189}Brišimo odavde.
{9395}{9463}Gdje je Skip? -Doæi æe|veèeras. Naæi æemo se kod
{9470}{9538}parkinga za prikolice.|Tamo sam skrio kamion.
{9546}{9604}Tko æe još doæi?|-Moj brat Roy.
{9619}{9718}Nekad je živio ovdje?|-Ovdje, ondje, svugdje.
{10925}{11002}Federalna policija!|Masturbiraš tamo?
{11026}{11091}Polako digni ruke s|pimpeka.
{11127}{11181}Otvaraj!
{11228}{11275}Kako si, mali?
{11298}{11379}Ti si odmor za oèi.|Kako ti je žena? -Dobro.
{11388}{11443}Život je dobar prema tebi?
{11451}{11511}U poznaj Jorgea Montanu.|On je jedan od mojih ljudi.
{11517}{11569}Ovo je Roy. Zar ne|izgleda dobro?
{11575}{11643}Rekao si da æe biti dva mom ka?|-Da, drugi stiže veèeras.
{11743}{11860}Popijmo koktel! CCTV, vrata|se otvaraju daljinskim.
{11865}{11977}Na krovu, lijevo je kutija|od alarma ADT. -Model 300 D.
{11983}{12032}Kao u banci.
{12039}{12119}Tihi alarm? -Da. Spojeni su|s tvrtkom Royal Sentry.
{12125}{12187}Svi poslovni prostori u gradu|ih koriste.
{12195}{12245}Policajac na unajmiljivanje|ima Berettu 9, kako bi se
{12250}{12302}bogate starice osjeæale|sigurne kad doðu.
{12308}{12353}Što je tu?
{12359}{12405}Tu se obavlja distribucija|za zapadnu obalu ruskih
{12409}{12538}dijamanata. Neki Droutzkoy|vodi sibirski ekvivalent
{12543}{12616}De Beersa. Tamo je toliko|hladno da dijamante mogu
{12621}{12762}vaditi samo dvaput godišnje.|Taj Droutzkoy dolazi ovdje...
{12780}{12868}Svakog prvog utorka u travnju,|na putu za Phoenix.
{12875}{12946}On, tri tjelohranitelja i|3 milijuna u kamenju
{12951}{13008}pred samo zatvaranje.
{13068}{13171}Odakle ti te informacije?|-Kupio sam ih.
{13556}{13606}Prekrasno. -Da.
{13634}{13739}Nije roza. Pravi krvavi rubini|iz Burme. Vidite èistoæu.
{13876}{13964}Koliko stoje?|-38.600 dolara.
{14131}{14272}Da budem iskren, tražim nešto|malo ''znaèajnije''.
{14305}{14364}Malo znaèajnije?
{14387}{14443}Odmah se vraæam.
{14620}{14695}Dakle, idemo na snagu.|-Kao kauboji.
{14772}{14846}Bit æemo dugo eksponirani.|Najmanje dvije do tri minute.
{14854}{14924}Policija æe imati posla|na drugim mjestima.
{14978}{15070}Roy, reci mi da nije izvedivo.|Najmanje 3 mil. dolara.
{15142}{15234}Kad ga sredimo, taj æe Rus|pošiziti. -Tko ga jebe.
{15249}{15296}Bivša komunjara.
{15313}{15395}Dat æemo mu kratki kurs iz|slobodne inicijative.
{15417}{15499}K tome, to je crno tržište.|Da se neæe žaliti konzulatu?
{15700}{15790}MONTANA, TI SI? -Da.|-ÈEKAJ, PITAT ÆU OVE DEÈKE.
{15812}{15915}VIDJELI STE SKIPA? NI ONI|GA NISU VIDJELI. IMAŠ PORUKU?
{15921}{15980}Ne, pokušat æu kasnije.|Hvala.
{16247}{16334}Kako je bilo. -Išlo je glatko.|Skip se javio? -Nije.
{16340}{16413}Zvao si ga? -Deset puta.|-A kartaški klub? -Nije viðen.
{16419}{16464}Jebi ga!
{17281}{17352}Nemam pojma gdje je.|I ja ga želim isprašiti.
{17619}{17674}Evo ga.
{17705}{17752}On je.
{17880}{17992}Gdje si bio, èovjeèe?|-Ševio tvoju ženu. U padaj!
{18140}{18175}Vozi!
{18893}{18937}Što je ovo?
{18946}{18985}Idemo.
{18994}{19044}U nutra.
{19049}{19107}Odell te tamo èeka.
{19161}{19255}Rista, ne šizi. -Ja èekam tu.|-Nitko te neæe napasti.
{19262}{19315}Neam šanse da uðem unutra|kupovati pištolje od nekog
{19321}{19397}Kunta Kinte kojeg sam upoznao|na kratkoj kavi.
{19411}{19465}Lud si.
{19693}{19836}HALO? -Ja sam. Ja sam oko 1200|zapadno od 120-te.
{19844}{19923}Ostani na liniji. Ako èuješ|pucnjeve, zovi policiju.
{19929}{19980}ŠTO?! -Što?
{19985}{20040}Dobro naèuli uši.
{20274}{20329}Gdje je novac?
{20420}{20474}Prebroj to.
{20585}{20636}U redu je.
{20689}{20763}Smith & Wesson. Sig.
{20808}{20870}Walter.
{20899}{20952}Glock 9.
{20978}{21044}Ovaj mi se sviða.|Odakle ti?
{21074}{21125}Što?
{21130}{21204}Èuo si me. -Što to radiš?|Trebalo je trajati 5 minuta?
{21219}{21276}Ovaj traži nevolju.
{21288}{21354}Zašto? -Pita me odakle su|pištolji.
{21403}{21503}Što ti zamišljaš tko si?|Ovdje nema prepada, upada.
{21514}{21606}Radimo posao. -Jasno mi je.|Odgovori na pitanje.
{21677}{21793}Reaganomija, to je to.|Sva ta srezavanja javnog
{21799}{21880}obrazovanja. Sad jadni bijeli|gadovi ne znaju ni èitati.
{21885}{21985}Odjebi. Odakle su? -Proèitaj|to, kretenu.
{22022}{22107}To su dokumenti koje|prodavaèi nose u Sacramento.
{22116}{22207}Da li su poslani tamo, ili su|neispunjeni? Zapitaj se:
{22213}{22286}''Zašto su neispunjeni?''
{22525}{22580}Bijeli momèe...
{22612}{22696}Voliš automobile?|-Što misliš pod tim?
{22734}{22795}Nabavit æu ti auto, rista.
{22842}{22951}Lincoln, Porshe, Cheeba.|Sve se to vrti ovuda.
{22976}{23050}Ako nešto trebaš,|nazovi.
{23268}{23313}Jebi ga.
{23376}{23450}Ne mogu joj plaæati|njegovateljicu. -Dobro.
{23485}{23545}Onda je smjesti u dom.
{23575}{23629}Ti joj to reci.
{23706}{23782}Dakle? -Što, dakle?
{23809}{23972}Kako to misliš, što? Sjanjno|je. Jednostavno. -Jednostavno.
{23984}{24040}Prekrasno. Kao što|sam ti rekao.
{24088}{24174}Da sam dobio dolar svaki put|kad sam èuo da je posao lak...
{24213}{24282}Gotovo je. Idem u zatvor.
{24307}{24372}Jebi ga. Žalit æeš se na|viši sud? -Ne, to sam veæ
{24378}{24435}izgubio. I moguænost obnove|postupka. Moram se predati
{24440}{24499}za 10 dana.
{24536}{24631}Moja djeca. -Ima drugi|naèin da se to sredi.
{24653}{24722}Da ubacim lovu pod neèija|vrata? -Tko je sudac?
{24729}{24810}Tannenbaum. -Zaboravi, to je|loša ideja.
{24817}{24893}Koja optužba? Posjedovanje|oružja?
{24899}{24969}Zbog toga neæeš na doživotnu|u Sing Sing. -2. do 5 godina.
{24978}{25047}To ti je 20 mjeseci, maksimum.
{25153}{25254}Jednom se vozim naoružan i|baš me tada zaustavi policija.
{25259}{25319}Kamo ideš? -U Folsom.
{25365}{25431}Tu školu smo prošli Roy i ja.|Pobrinut æu se da ti
{25436}{25526}bude dobro. Ne birni ni|glede obitelji.
{25534}{25602}Nakon ovog posla,|bit æe im dobro.
{25801}{25874}Rekla si deèkima?|-Da li sam rekla?
{25947}{26041}Što? -Kako to misliš?|Da idem u zatvor.
{26075}{26134}Ne, ti æeš im reæi.
{26161}{26250}DAJ, ZNAŠ DA SI TI BLlŽA|S NJIMA.
{26294}{26372}Ovaj put neæu. Ti si zabrljao,|ti to i sredi.
{26419}{26472}Rachel...
{26521}{26582}GDJE SU SADA?
{26626}{26700}Gledaju utakmicu kod|Roberta.
{26770}{26827}Kako su?
{26846}{26905}Nedostaje im otac.
{26984}{27041}Kao i meni.
{27620}{27675}Jorge.
{27692}{27752}Što je s corvettom?|-Gljive.
{27831}{27913}Gdje si maznuo prikolicu?|-Iznajmio sam je, gluperdo.
{27922}{27971}I ja tebe volim.
{27976}{28039}Što to radiš?|-Nabavio si oružje?
{28046}{28115}Što sam ti rekao? Imaš propuh|u glavi? -Ponašaš se usrano.
{28123}{28173}Na vrijeme. Samo si trebao|doæi na vrijeme.
{28179}{28237}Morao sam se prijaviti|u motel.
{28294}{28386}Roy, ovo je Skip.|Skip nam je vozaè.
{29006}{29053}Kamo æeš?
{29082}{29140}Na spavanje.
{29164}{29233}Dobro si? -Da. -Sigurno?
{29296}{29350}Roy.
{29358}{29410}Hvala.
{30933}{30994}Ako stvari krenu loše,|idemo u Calexico.
{31003}{31073}Idemo na sjever na par dana.|Ako je sve dobro, ostajemo tu.
{31085}{31140}Da ponovimo?
{31156}{31224}Meni je u redu. -I meni.
{31255}{31332}Dobro. Kreæemo.|Alarmi su sjebani.
{31430}{31513}Ako sve bude kako treba,|uèinit æemo to ponovo.
{31563}{31623}Mi smo opaka momèad.
{32174}{32231}Možda bih trebao|naruèiti veèeru?
{32348}{32426}Možda ne bi trebao brinuti.|Deèki æe se pojaviti.
{32900}{32954}Ugasi to sranje.
{33033}{33111}Dovodim se u pravo|psihièko stanje.
{33155}{33205}Skreni ovdje.
{33387}{33436}Kreæemo.
{34536}{34591}Oprostite, imate li...
{34762}{34809}Žao mi je, zatvoreno je.
{34866}{34994}Svi dolje, s licem na pod!|Ruke na glave! Odmah!
{35380}{35484}Otvori sef!|Otvori!
{35519}{35575}Hajde.
{35917}{35978}Èinite veliku pogrešku.
{36769}{36823}Lee? Imaš mjesta? -Da.
{37783}{37830}Idemo!
{38546}{38598}Kako smo prošli?
{38747}{38808}Kako smo prošli?
{38872}{38968}Ne znam. Kompjutori su|poludjeli! Svaki alarm u
{38973}{39025}ulici je ukljuèen!
{40636}{40689}Bok, dragi. Kako|je prošlo? -Super.
{41426}{41492}Što je to?|-Slavlje.
{41544}{41643}Hajde. -Što?|-Moramo krenuti. -Ali...
{41666}{41730}Jebeš ali! Pakiraj se.
{41840}{41938}Koliko si zaradio? -Lee kaže|da smo uzeli 2 ili 3 milijuna.
{42041}{42139}Zaradit æeš milijun|dolara? -Ne.
{42167}{42296}Podijelit æemo. -Koliko æeš|ti dobiti? -Ne znam.
{42310}{42362}Saznat æemo kasnije.
{42514}{42569}Što?
{42606}{42675}Zaèepi.
{42749}{42806}Dodaj mi olovku.
{43178}{43273}Na tri milijuna dobivamo|15 do 20 centa po dolaru.
{43332}{43402}Sranje. Još imamo gorivo i|hranu.
{43411}{43473}Imamo i troškove.
{43611}{43668}Dobro.
{44039}{44201}Dobra roba. Jako dobra roba.|1,5 do 3 karata.
{44262}{44337}Lijepo, zar ne? Pogledaj.|Nije li prekrasno?
{44351}{44432}Kad ti polazi autobus?|-8:52 h.
{44550}{44608}Moj broj za transfer|u banci.
{44646}{44711}Volio bih da doðeš u L.A.|sa m nom.
{44822}{44881}Bio si sjajan, mali.
{45036}{45160}Koliko æemo zaraditi, šefe?|-300.000, možda 350.000 dol.
{45174}{45247}Moram podijeliti s mom kom koji|mi je prodao informaciju.
{45276}{45349}Ali mislim da smo obavili|dobar posao.
{45377}{45450}Svaka sitnica se raèuna.|To je moj moto.
{45473}{45573}Tko želi pivo? Roy, imaš|vremena za još jedno pivo?
{45607}{45683}Imaš vremena za još jedno|pivo? -Nemam.
{45810}{45879}Skip, natoèi mi još|jedno pivo, molim te.
{47003}{47084}Roy!
{52197}{52260}ROY!
{59512}{59565}Sunny.
{59577}{59637}Sunny.
{59647}{59704}Halo.
{59712}{59772}Halo, Sunny.
{59780}{59841}Roy?
{59942}{60012}Mislila sam da ste|vi deèki otišli...
{60052}{60109}U Palm Springs.
{60123}{60184}Lee je rekao...|-Lee je m rtav.
{60242}{60302}Što? -Nije uspio.
{60390}{60462}Poznaš njegovog|prijatelja Skipa?
{60567}{60635}Sunny? -Ne.
{60652}{60730}Znaš li kamo je Lee|volio izlaziti?
{60764}{60829}U ''Widlife Lounge''.
{60835}{60927}Gdje je to?|-Na lvar Str.
{60952}{61020}Svi se tamo okupljaju.
{61191}{61278}Lee je m rtav? -Da.
{61388}{61462}Ne mogu to prihvatiti.
{61715}{61789}Ne mogu to prihvatiti.
{62341}{62400}Mogu ti pomoæi? -Pivo.
{62467}{62545}Da li je Skip dolazio?|-Tko? -Skip.
{62571}{62632}Ja sam prijatelj|Lee Egana.
{62658}{62736}O èemu prièaš?|-Poznaš ga ili ne?
{62761}{62836}Možda. -Poznaš ga?|Onda poznaš i Skipa.
{62907}{63013}Jebi se ti i jebem ti majku|i oca što su te napravili.
{63019}{63079}Sad odjebi odavde.
{63124}{63177}Opaki gad?
{63546}{63605}Nazovi. -Ne mogu!|-Nazovi Skipa!
{63639}{63706}Ne! Backusov ured.|-Backus?
{63712}{63786}On je... odvjetnik.|-Odvjetnik?
{63792}{63829}Da. -Gdje?
{63835}{63887}Gdje?!
{63899}{63957}Gdje?! -U centru.
{63962}{64011}Ustani.
{64981}{65121}Philipe, zvao je Roy Egan.|-Zaštiti se. -Gdje si?
{65146}{65232}U bolnici Saint Vincent?|-Ne. County General.
{65306}{65383}Što ti je uèinio?|-Tri slom ljena rebra
{65392}{65458}i manji potres mozga.
{65467}{65521}Sjeæam ga se.
{65528}{65581}Mogu izaæi na kraj s njim.
{65839}{65890}G. Egan. Uðite.
{66099}{66158}Skip Kovich.
{66170}{66260}Gdje je? -Ja ga ne|zastupam.
{66295}{66358}Gdje je?
{66398}{66445}Prije dvije godine.|Posjedovanje provalnièkog
{66451}{66523}alata. Oslobodio sam ga.|Tada sam ga zadnji put vidio.
{66602}{66708}Jebem te u leða, gade.|-U odvjetnièkom si uredu.
{66714}{66808}Mi smo odvjetnici.|Budi pametan.
{66827}{66883}Gdje je?
{66890}{66944}Ne znam. Ne znam kako bih ti|pomogao. -Daj mi adresu,
{66949}{67032}broj telefona.|Želim bilo što!
{67061}{67132}Proèulo se da to radim?|Što misliš kakvu ja to
{67136}{67206}kriviènu praksu obavljam?
{67263}{67329}Koga briga?
{67493}{67549}Kovich...
{68093}{68168}ZDRAVO. DOBILI STE BARE|ELEGANCE CLUB.
{68177}{68263}TULUMARIMO OD 20 DO 2 SATA|SEDAM VEÈERI TJEDNO.
{68283}{68339}NALAZIMO SE NA...
{69091}{69154}Da li je Skip veæ stigao?
{69166}{69229}Pitaj njegovog komada.
{71733}{71799}Ni rijeèi. Želim Skipa,|a ne tebe.
{73196}{73267}Gdje je Skip?|-Ne znam.
{73283}{73384}Ne znaš? Gdje stanuje?|-Ovdje sigurno ne.
{73392}{73497}Gdje stanuje? -Ne znam!|-Imaš njegov broj telefona?
{73503}{73571}Ne. -Znaš nekog njegovog|prijatelja?
{73651}{73733}Skip kojega ja poznam nema|prijatelje. Samo ljude
{73737}{73787}koje sjebe.
{73808}{73915}Što je tebi uèinio?|Zašto ne pozoveš policiju?
{73978}{74055}Ja sam svoj policajac.
{74328}{74412}Tko je to? -Skip. Sjeæaš me|se? Potrebna mi je pomoæ
{74416}{74499}veèeras. -Veèeras?|Nemoguæe.
{74564}{74659}Kako hoæeš. Zaradi novac ili|spavaj. Izaberi.
{74670}{74755}Zaglavio sam s jednim|zelenašem. Radi s Kinezima.
{74761}{74845}Ako odem tamo sam, m rtav sam.|Platit æu ti da mi èuvaš leða.
{75969}{76065}Harvey. -Imaš novac?|-Razgovarajmo.
{76472}{76519}Pazi ovo.
{76632}{76682}Što je to?
{76710}{76813}Šališ se? Tu je 1000 dol.|-Ne boj se za ostatak.
{76820}{76922}Ti se boj. Dužan si mi 40.000.|Što je ovo? -Da li bih došao
{76928}{77023}ovamo da sam te htio zeznuti?|Zapitaj se to. Bih li?
{77047}{77146}Prièaj. -Keshaun, kamo æeš?
{77168}{77269}Pronjuškat æu malo, dovraga.|-Vuci guzicu natrag i pazi.
{77361}{77447}Èemu uopæe ovo sranje usred|noæi? -Nešto zanim ljivo.
{77455}{77543}Zato umukni i pazi.|-Dogovor je ovakav.
{77562}{77650}Utopio sam robu ujaku Lukeu.|Nazovi i pitaj ga.
{77656}{77717}Za dva dana, ne samo da æeš|dobiti svojih 40. 000 somova,
{77722}{77787}nego æu dodati još 20.000.
{77802}{77863}10 ekstra je zbog kašnjenja.
{77870}{77943}A ostalih deset je za posao|koji želim da obaviš za mene.
{77949}{78037}Kakav posao? -Traži me jedan|èovjek. -Ima li to veze sa
{78040}{78110}neredom u Palm Springsu?
{78129}{78200}Tko je on? Kako se zove?
{78209}{78270}Roy Egan.
{78277}{78352}Imaš veze po cijelom gradu.|Pronaði mi ga.
{78591}{78662}Izvukao sam ti zapis.|-Super. Daj mi ga.
{79458}{79509}Mogu vam pomoæi?
{79519}{79571}Lijepi auto.
{79625}{79674}Želite ga kupiti?
{79739}{79789}Ne, hvala.
{79804}{79860}Sigurni ste?
{79890}{79953}Ima mašinu 302.
{79969}{80030}Što god to znaèilo.
{80116}{80181}Izgubili ste se?
{80338}{80417}Nisam. -Djelujete tako.
{80479}{80545}Jorge Montana živi ovdje?
{80620}{80679}Što želite?
{80715}{80779}Vi ste Jorgeova žena?
{81008}{81090}Sranje. -Poznajete Skipa?
{81166}{81238}Zaboga. -Gdje bih ga|mogao naæi?
{81819}{81894}Kako je um ro? -Skip.
{81900}{81991}U bio je Jorgea i moga brata.|Pobjegao je s plijenom.
{82018}{82076}Znate Skipa?
{82210}{82272}Što namjeravate uèiniti?
{82333}{82394}Znate dobro što.
{82659}{82729}Što da kažem djeci?
{83020}{83096}Ako saznate gdje bih mogao|naæi Skipa.
{83181}{83257}Vi deèki ste svi isti.
{83299}{83360}Gubi se van!
{83972}{84037}Reci svome gazdi da je poziv|došao iz odvjetnièkog ureda
{84041}{84185}iz motela na 1635 Spring Str.|-To je Chinatown. -I 500 dol.
{84199}{84311}Bit æe 1000. -Još nešto?|-Možete li pratiti tu liniju
{84315}{84397}i dati mi popis poziva u|sljedeæih 48 sati?
{84404}{84464}Nema problema.|-Nazvat æu te kasnije.
{84631}{84691}Adresu mi je dala moja veza.
{84722}{84789}Poziv odvjetniku je|došao odavde...
{84796}{84846}I odavde. Dvaput je zvao.
{84950}{85004}Kako želiš da se to sredi?
{85013}{85040}Zauvijek.
{85048}{85078}Idemo.
{85084}{85126}Popij èaj.
{85540}{85601}Ostajete još jedan dan?
{86785}{86840}Još diše?
{86898}{86952}Probudio se.
{86958}{87015}Bacimo ga u luci.
{88997}{89050}Mama!
{89177}{89279}Tko je to? -Prijatelj vašega|oca. Hajde, uvedi ga unutra.
{89287}{89348}Uvedi brata unutra.
{89925}{89988}Mislim da ti treba doktor.
{90100}{90165}Bez bolnice...
{90196}{90264}Ne možeš umrijeti ovdje.
{90372}{90440}Pet somova...
{90511}{90590}Pobrini se za mene.
{90727}{90778}Egan!
{90868}{90924}Dovraga!
{90955}{91012}M rtav je?
{91026}{91070}Nije.
{91078}{91142}Djeluje kao da je m rtav.
{91301}{91359}Henry, što to radiš?|Van!
{91403}{91456}Hajde!
{93796}{93887}Gdje su ti djeca? -Poslala|sam ih kod sestre.
{93974}{94046}Nisam htjela da budu|blizu tebe.
{94285}{94375}Nabavit æu ti novac. Prebacit|æu ga iz banke.
{94387}{94459}Ne želim tvojih 5.000.
{94845}{94935}Što ako ti mogu pomoæi|da naðeš Skipa?
{95122}{95212}Èuješ me ili si zaspao|otvorenih oèiju?
{95218}{95337}Kako bi mi mogla pomoæi?|-Doæi æemo do toga. -Odmah.
{95567}{95619}Želim 1.000 dolara.
{95663}{95724}1.000? -Tako je.
{95770}{95848}Dugujem ti 5. Dodat æu 5.|-Rekla sam 1.000.
{95916}{95977}20. 000 dolara.
{96106}{96226}Uzmi ili ostavi.|-Pronaæi æu ga bez tebe.
{96517}{96574}Sretno.
{97204}{97268}Èak ni ne znam što nudiš.
{97364}{97411}Ovo.
{97791}{97851}Jorgesov je.
{97871}{97936}Znam sva imena u njemu.
{97943}{98005}Tko su i što su.
{98183}{98264}Ako ti ja ne kažem, isto ti je|kao da tražiš po imeniku.
{98380}{98461}Dobro. Dogovoreno.
{98519}{98577}Ovdje. -Što?
{98590}{98666}Ujak Luke. Nakon neèeg|velikog Jorge je otišao u
{98672}{98742}Dallas. Pokupila sam ga u|zreènoj luci. Imao je dva
{98747}{98845}kufera. Ostavila sam ga u|stražnjoj ulièici i èekala
{98851}{98935}ga skoro sat vremena.
{98972}{99036}Kad se Jorge vratio,|bio je praznih ruku.
{99042}{99085}Kad sam ga pitala gdje je bio,|rekao je da je posjetio
{99091}{99141}ujaka Luka.
{99146}{99218}Tri dana kasnije našla sam ga|kako nagurava novac u kutije.
{99234}{99287}Isplata. -Da.
{99338}{99408}Nije to bio zadnji put da|je radio s tim èovjekom.
{99443}{99510}Luke prodaje ukradene stvari.
{99559}{99699}Što namjeravaš? -Poslati|tvoje klince na koledž.
{99983}{100040}Smislio si kako?
{100210}{100261}Kada?
{100307}{100358}Sutra.
{100383}{100477}Skip je prodao svoju robu.|Èeka novac.
{100564}{100625}To mi daje prostora.
{100731}{100810}Što da ja uèinim?|-Ne miješaj se.
{100901}{100960}Kad ubijem Skipa ostat æe|tijelo. Ništa što bi navelo
{100965}{101011}na tebe.
{101025}{101101}I pak ti i djeca napustite|grad. Javi mi kamo æete.
{101133}{101198}Poslat æu ti novac.
{101312}{101379}Port Arthur, Teksas.
{101428}{101487}Na Gulf Coast.
{101649}{101709}Ne izgledaš kao ubojica.
{102206}{102259}Vjeruješ u to?
{102678}{102742}I auto bi mi dobro doašo.
{102866}{102932}Hvala. Poèni s pakiranjem.
{103150}{103239}Jorge nije bio svjestan što|ima. Ja bih bio pametniji.
{103247}{103304}Ja bih se držao tebe.
{105170}{105215}Tko si ti?
{105256}{105363}Roy Egan. -Što hoæeš?|-Neæu ništa od tebe.
{105367}{105431}Hoæu novac koji èuvaš|za Skipa.
{105438}{105530}Ja sam bio èetvrti èovjek.|-Ne znam o èemu prièaš.
{105535}{105592}Nemam nikakav novac.
{105597}{105658}Pogriješio si.|Ne mogu ti pomoæi.
{106409}{106552}Da? -Gdje si? -Ovdje. Tu sam|nekad radio. Zašto?
{106562}{106612}Sve je u redu?
{106621}{106690}Ne dolazi po svoj novac.|-Zašto?
{106738}{106844}Jer više nije ovdje. Nema ga|više. -O èemu prièaš?
{106882}{106950}Nema ga! Egan ga je uzeo.
{106975}{107078}Sereš! Tebi sam predao robu!|Dužan si mi novac!
{107084}{107166}Ako te opljaèkao, to je|tvoj problem! -Jebi se!
{107173}{107288}Ti i tvoj novac! Pozna te.|Znao je da je novac za tebe.
{107313}{107362}Prije nego što poludiš...
{107395}{107459}Znam gdje se nalazi.
{107500}{107631}Gdje? -Neæu ti ništa platiti.|Uzmi sam svoj novac.
{107640}{107695}Uzmi ga od njega.
{107710}{107789}Kako je došao do tebe?|-Zašto pitaš mene?
{107796}{107852}On je bio tvoj èovjek.
{108212}{108292}Kreæemo. Egan se smjestio|u neku rupu u Rascoeu.
{108297}{108344}Novac je kod njega.
{112745}{112810}Gdje je Skip? Gazda želi|njegov novac!
{112849}{112901}Gdje je novac?!
{112912}{112960}Ne znam!
{112965}{113025}Kunem se da ne znam!
{113456}{113526}Steady, podigni tu kurvetinu.
{113767}{113812}Doði.
{113846}{113895}Jebi ga!
{113950}{114007}Reci mu da hoæu svoj novac!
{114055}{114105}Skip, ti si?
{114138}{114193}Sranje!
{114267}{114353}Imam tvoju gaduru.|Hoæu novac!
{114382}{114445}Izlazim. Sad!
{114529}{114591}Èuješ me, Skip?|-Da!
{114935}{115004}Mene nitko neæe opelješiti!
{116957}{117045}Gdje si bio, Roy?|Zovem te pola sata.
{117066}{117138}Imam je.|Hoæu novac.
{117164}{117221}Previše sam toga prošao da|bih je ostavio na životu
{117227}{117288}ako me razoèaraš.
{117323}{117386}Evo što æeš.
{117451}{117539}Kreni 60-tom istoèno prema|Azusi. Dva lijeva skretanja
{117546}{117612}i skreni na neasfaltiranu|cestu.
{117623}{117674}Shvatio si?
{117728}{117794}Èuješ me ili ne?
{117820}{117897}Da. -Dobro.
{117945}{118028}Bez trikova. I donesi|jebeni novac!
{119496}{119557}Dolazi. Dovedite ga ovdje.
{126747}{126805}Drži se, Roy.
{128869}{128931}Mièi mi se s puta!|Ovdje je!
{128955}{129002}Gdje?
{129037}{129103}Tu ste ga ostavili?|Gospoðo?
{129128}{129180}Gospoðo?
{129358}{129408}Ostavite me na miru!
{129572}{129633}Kako je izgledao?
{130683}{130751}POKOPALI SMO JORGEA U|CAMARILLU...
{130761}{130857}U BLIZINI PLANTAŽE NARANÈI|GDJE SMO SE IGRALI KAO DJECA.
{131071}{131139}UZELI SMO NOVAC I POBJEGLI.
{131331}{131397}ODREDIŠTE: PORT ARTHUR.
{131753}{131822}GDJE NITKO NE ZNA NAŠU PRIÈU.
{132066}{132137}Zdravo, kako ste? -Odlièno.|A vi? -Dobro. A deèki?
{132145}{132240}Dobro su. Igraju se na plaži.|-Dobro. Vidimo se sutra.
{133259}{133666}Subtitles by:|M O Z E N
