{517}{623}PLJAÈKA STOLJEÆA
{640}{1400}
{1499}{1578}Ruku na srce, nikad|nisam bio lud za blagdanima.
{1609}{1663}Veæ odavno nisam|bio na blagdanima.
{1672}{1719}ŠEST DANA RANIJE
{1729}{1796}Veæ dugo nisam vidio|svoju obitelj, a ni djevojku.
{1808}{1889}Veæ dugo nisam vozio|automobil. Zbog automobila
{1897}{1983}sam i dospio ovdje. U "Iron|Mountain", najstroži zatvor.
{2011}{2080}Gulio sam pet godina|zbog kraðe automobila.
{2090}{2153}A veæina mojih kolega,|poznati ubojice i silovatelji,
{2165}{2242}bit æe pušteni uvjetno za|tri godine. Takav je život.
{2263}{2327}Ponekad. Što se|mene tiæe, takav je stalno.
{2335}{2401}To sam ja, Rudy Duncan,|prijetnja za društvo,
{2411}{2449}onaj lijevi.
{2456}{2513}Na desnoj je strani Nick|Cassidy, moj najbolji
{2518}{2584}prijatelji. Tada smo mislili|da æemo izaæi za tri dana.
{2598}{2672}O to mu govoriš u zatvoru.|Kako æeš sve ispraviti.
{2685}{2741}Da više nikad neæeš|napraviti istu pogrešku.
{2937}{3000}Kad odemo odavde...
{3007}{3066}Što æeš prvo uèiniti?
{3073}{3123}Vruæa èokoIada.
{3132}{3208}Molim?|-To æu prvo uèiniti.
{3216}{3275}Izaæi æu van i popiti|šalicu vruæe èokolade.
{3285}{3329}I komad pite od oraha.
{3337}{3395}Tako je.|I komad pite od oraha. -Da.
{3444}{3503}I ona æe biti vani.
{3521}{3598}Ona æe biti tamo|vani i èekat æe me.
{3631}{3691}Uzela nam je sobe u|motelu na Auto-cesti 5.
{3730}{3789}Zakljuèat æemo se|na tjedan dana...
{3796}{3853}...piti vino i|brèkati se u kadi.
{4051}{4122}Znaš ...Nick... sve one|slike koje je poslala...
{4136}{4195}Siguran si da|je to zaista ona?
{4206}{4280}Èuo sam da cure nekad|šalju slike drugih cura.
{4286}{4341}Znaš, sliku svoje|zgodnije sestriène.
{4348}{4400}Zašto govoriš takvo što?
{4407}{4467}Samo kažem...|-Zašto to govoriš?
{4475}{4524}Samo kažem...
{4532}{4583}Možda bih je|ja trebao izvesti...
{4591}{4651}Provesti s njom par dana|da vidim je li cura u redu.
{4660}{4735}Samo dan-dva.|Možda dvije noæi?
{4753}{4801}KoIiko treba.
{4808}{4864}Da provjerim|uzimaš li dobru robu.
{4874}{4958}Znaš što? Samo ti uživaj|u svojoj vruæoj èokoladi.
{4980}{5039}Ja æu|riskirati s AsheIy.
{5096}{5142}To sam i mislio.
{5238}{5297}Brže malo!
{5302}{5353}Otvaraj vrata 3.
{5394}{5490}Sranje! -Što je?|-Alamo se vratio.
{5555}{5630}Nije mu nedostajalo|sunca. Nadrljao sam.
{5658}{5720}Pitcher kaže kako misli da|sam ga ja cinkao i optužio ga
{5726}{5783}da je istukao Creeda.|Zato što sam bio tamo.
{5788}{5849}Misli da je zbog mene završio|u samici. -Sranje, Rudy!
{5865}{5908}Idemo van!
{6138}{6196}Stanite!
{6215}{6273}Ulazite unutra!
{6280}{6320}Slušaj ovo.
{6328}{6384}Popis sam sastavila,|dvaput ga provjerila.
{6391}{6462}Vražiæak budi moj|i bit æe ludi spoj!
{6473}{6541}Da izdržim još jedan dan,|dovoljno je samo da sklopim
{6548}{6603}oèi i maštam kako te grlim...
{6610}{6651}...ljubim...
{6661}{6703}i dodirujem.
{6714}{6776}Zato što znam|da æu u tom trenutku
{6781}{6849}imati osjeæaj da sam|pronašla smisao života.
{6864}{6938}Djeluje prilièno zreIo za|jednu 25-godišnjakinju.-Da.
{6983}{7042}Odrastanje u Detroitu|tjera te da brzo sazriš.
{7066}{7129}Ili je to u pitanju|ili su slike stare 10 god.
{7257}{7331}Barem mi zbog nje ne|nedostaje Millie Bobek.
{7338}{7394}Ipak sam Millien dužnik.
{7403}{7501}Da je nisam ševio, ne bih|nikad ni završio ovdje.
{7527}{7583}Da nisi onog tipa|tresnuo po gIavi,
{7589}{7675}ne bi našao|pravu ljubav. -Ljubomoran si.
{7684}{7806}Što ako te vidi, a ti|joj se fizièki ne svidiš?
{8012}{8074}Mi smo povezani.
{8237}{8295}Ovo je pismo sranje.
{8300}{8356}Trebao si pisati tom|èasopisu. -Da, jesam.
{8365}{8429}Izaæi æu odavde i|odmah zapoèeti ljubavnu vezu.
{8436}{8502}A ti æeš otiæi odavde,
{8507}{8597}autobusom, u potrazi za|najpijanijom ženskom u bircu.
{8609}{8686}Tako je. "Dobro jutro,|ljepotice", reæi æu joj.
{8745}{8835}Trebao si pisati, Rudy.|Sad bi imao djevojku.
{8863}{8924}Trebao sam puno toga uèiniti.
{8969}{9109}AIi ja samo žeIim stiæi|kuæi na božiænu veèeru.
{9167}{9220}Spavati u svom krevetu...
{9238}{9303}GIedati utakmicu|sa svojim starim...
{9327}{9382}I jesti ostatke|hrane barem pola godine.
{9406}{9447}Samo želim kuæi.
{9992}{10044}Voli te Ashley.
{10108}{10181}Što je ovo?|-Sveèani žeIe.
{10250}{10306}Progutaj, pa æeš vidjeti.
{10311}{10405}Samo da znaš, nas æemo|dvojica izaæi za dva dana.
{10421}{10497}I dok æemo mi uživati|u jastogu i roštilju,
{10504}{10594}ti æeš stajati ovdje|i smrdjeti po toj strahoti.
{10634}{10689}Tko je sad u zatvoru?
{10742}{10821}Hej, Alamo, kako si?|Izašao si iz samice?
{10832}{10902}Dobro izgledaš.|Smršavio si.
{10939}{10998}Nisam te ja cinkao.
{11016}{11050}Nisam ja.
{11058}{11121}Još samo dva dana. Idemo.
{11271}{11349}Rekla mi je da joj brat|vozi kamione, sjeæaš se?
{11356}{11408}Možda mi može naæi posao.
{11415}{11499}Da radiš kao zaštitar?|-Neæu više to raditi.
{11513}{11572}AshIey ima pravo.|Moram zapoèeti svoj posao.
{11584}{11657}Otvoriti tvrtku.
{11667}{11743}Mene to ne zanima.|Bavio sam se time.
{11756}{11827}Kraða automobila|ne može se smatrati obrtom.
{11853}{11918}Savjetnik za rastavljanje|auto-dijelova ne zvuèi baš
{11925}{12043}najbolje. Želim biti šef.|Da ljudi rade za mene.
{12164}{12316}Što ti je? -Èudovišta|u želeu. -To je samo žohar.
{12339}{12403}To su bjelanèevine.|Dobre su za tebe.
{12430}{12496}Èudovišta u|želatini! -Smiri se!
{12517}{12628}U želatini su èudovišta!|Èudovišta su u želatini!
{12642}{12705}Neka ide do vraga!
{12793}{12833}Isuse!
{12841}{12900}Sjedni, sjedni!|-Kujin sine!
{12937}{13002}Neæu ovo jesti!|-Jedi ti ovo govno!
{13055}{13117}Svi dolje! Rudy,|ne miješaj se u ovo.
{13127}{13205}Hoæeš ti malo èudovišta?
{13297}{13345}Još samo dva dana!
{13425}{13466}Jebi ga!
{13497}{13559}Ne mièi se!
{13622}{13676}Mi nemamo|nikakve veze s ovime!
{13754}{13808}Rudy, pazi!
{14103}{14180}Cassidy je ranjen!|Proboli su ga nožem!
{14195}{14275}Bože moj!|-Rudy! AshIey!
{14288}{14358}Drži se. Samo se drži!|-Èuvari, doðite!
{14367}{14459}Èuvari!|-AshIey æe doæi...
{14482}{14543}Nick, moraš biti...|Èuvari! Èuvari!
{14551}{14602}Do vraga!
{14647}{14712}Nick! Bože moj, Nick!|Odvedite ga odavde! Odmah!
{14729}{14765}Nick! Nick!
{14772}{14831}Nick! Nick!
{15118}{15185}Bar se više neæe vratiti.
{15267}{15348}Zatreba li ti društvo|veèeras, pozovi me.
{16897}{16955}Otvaraj vanjska vrata
{17176}{17239}Dobro došli u|svoj svijet, seronje.
{17246}{17290}Nemojite se sad|pretvarati neznancima.
{17298}{17342}Ostaviit æemo vam|upaljena svjetla.
{17453}{17525}Dobro došao kuæi, tata.
{17589}{17670}Ovdje... Hej!
{18588}{18657}Sve mi to pomogne|da izdržim kad maštam
{18663}{18731}kako te grlim|kad sklopim oèi, i ljubim,
{18751}{18810}i dodirujem te.
{18842}{18900}Nemoj to|uèiniti, Rudy! Nemoj!
{19204}{19261}Isuse Kriste...
{20057}{20115}Ti si AshIey?
{20164}{20247}Ja sam Nick.
{20875}{20993}Ashley, oprosti. Bojao sam|se da æeš se okrenuti i otiæi
{20998}{21123}kad me vidiš prvi put. Bojao|sam se da æeš mi slomiti srce.
{21152}{21237}Da si me drukèije|zamišljaIa u pismima.
{21277}{21385}Bojao sam se|da ti se neæu svidjeti.
{21413}{21473}Da neæu odgovarati onoj|slici koju si ti zamislila.
{21480}{21538}Ja sam mislila da æeš,|kad me vidiš ovako odjevenu,
{21546}{21672}otiæi u drugom smjeru. Možda|ti se neæe svidjeti jakna...
{21698}{21767}Sviða mi se tvoja jakna.|-Možda ti se neæe...
{21832}{21902}Možda bi me|vidio i ne bih ti se...
{21922}{22022}Ashley...nemoj.|Toga sam se ja bojao...
{22123}{22184}Mislila sam da si rekao|da imaš kovrèavu kosu.
{22206}{22282}Imam. Jako je|kovrèava. Kad naraste.
{22297}{22388}AIi, skratio sam je.|Mogu je pustiti ako žeIiš.
{22401}{22501}Mogu biti|jako èupav. -Ne, nemoj.
{22521}{22580}Želim da budeš ono|što ti želiš biti.
{22631}{22752}Ponovi to. -Što?|-Opet se nasmiješi onako.
{22848}{22906}Hajde, još jednom.
{23053}{23224}Maštao sam o tom smiješku|dugo vremena, AshIey Mercer.
{23375}{23455}Bolji si nego|u mojoj mašti, Nick.
{23555}{23610}Stvaran si.
{25280}{25378}Mogu te pitati nešto? Prvi|put si ovako nešto uèinila?
{25452}{25509}Pogledaj se.
{25518}{25589}Tako si lijepa i draga.
{25614}{25687}Zašto si pisala nekom|nepoznatom zatvoreniku?
{25700}{25790}Rekla sam ti,|sjeæaš se? -Ponovi mi.
{25921}{25983}Svi deèki|s kojima sam izlazila
{26020}{26081}nikad me|nisu htjeli upoznati.
{26169}{26239}Kakva sam u stvari.
{26262}{26342}Samo su me htjeli povaliti.
{26409}{26479}A tip poput tebe, Nick...
{26501}{26574}Šest mjeseci je moralo proæi,|da mi samo dodirneš lice.
{26625}{26714}Mislila sam da æe takav|deèko morati smisliti naèin
{26721}{26780}kako da me upozna.
{27081}{27155}AIi, kad sam proèitala|ono što si mi napisao,
{27163}{27276}rekla sam: ovaj|deèko nije kriminalac.
{27329}{27390}On je samo štitio|svoju djevojku.
{27405}{27462}Netko je bio ubijen,
{27469}{27527}ali on nije ubojica.
{27554}{27625}Uèinio je ono što je|morao da bi spasio nekoga.
{27685}{27747}A svijet nije|na to tako gledao...
{27755}{27807}Država Michigan, u stvari.
{27846}{27905}Napisao si mi|neke prekrasne stvari.
{27916}{28013}Nisam sve ja pisao.|-Jesi. Ti si to napisao.
{28046}{28106}Tip s kojim sam dijelio|æeIiju malo mi je pomogao
{28116}{28203}oko romantiènih stvari.|Dobar je. Svidio bi ti se.
{28236}{28352}Govorim o srcu,|ne o rijeèima.
{28426}{28530}Mora da je i on svoje srce|unio u te rijeèi. -Doista?
{28756}{28839}Trebao se onda potpisati.|Onda bi on bio sad tu.
{28935}{28999}VOZAÈKA DOZVOLA|RUDY DUNCAN
{29409}{29499}Sretan Božiæ, Ho-ho-hol|-Sretan Božiæ, djede!
{29641}{29683}Doði, trebaš kaput.
{29689}{29759}Moj deèko neæe po|ovoj hIadnoæi hodati bez
{29766}{29867}lijepog kaputa! -Veæ|si mi previše toga kupila.
{29873}{29926}Ja tebi nisam ništa.
{29933}{29994}Nick...|Izašao si, i ovdje si.
{30013}{30070}Ti si moj Božiæ.
{30077}{30215}Košta 200 dolara! -Znam.|Zaboravio si gdje radim.
{30261}{30333}U kozmetièkom odjelu.
{30639}{30745}Samo za praznike. Pustit æemo|je da uživa u praznicima.
{30760}{30804}Onda æemo joj sve reæi.
{31250}{31318}Reæi æu im da nam ne|smetaju do kraja godine.
{31341}{31407}Kad se vratim, želim da|imaš samo lizalicu u ruci.
{32021}{32059}Bok, Nick!
{32646}{32694}Sranje!
{32760}{32817}Dugujem ti piæe.
{32934}{32993}Dobro došao kuæi, Nick.
{33054}{33114}Slušaj, èovjeèe,|ne poznaješ me!
{33137}{33247}Poznajem te. I to dosta dobro.|-Ne možeš me znati...
{33262}{33361}Vraga ne mogu.|-Pazi, srce! Unosim drvce!
{33735}{33804}Èini se da se|netko zabavljao.
{33911}{33999}Zdravo, sestrice.|Sretan Božiæ!
{34011}{34058}Ne! Kujin sine!
{34077}{34147}Polako. Nemoj joj nauditi.|-U redu. Oprostite èudovište.
{34387}{34477}Gabriele, što to radiš?|-Proèitao sam mnogo toga
{34483}{34547}o tebi.|-GabrieIe, što radiš ovdje?
{34554}{34639}Proèitao sam da štošta|toga znaš. -GabrieIe...
{34658}{34743}I da si proputovao svijeta.|-Slušaj, ja nisam on.
{34768}{34833}Ne znam što hoæeš od|Nicka, ali ja nisam on.
{34845}{34959}Nick? -Žao mi je.|Zaista mi je žao, AshIey.
{35017}{35074}Ne! Ne!
{35117}{35265}Tko si ti? -Ja nisam on. Ona|misli da sam Nick, ali nisam.
{35279}{35338}Strpaj ga u kamionet.|-Bio sam s njim u zatvoru!
{35346}{35408}Tako sam saznao za nju i|njega. Zamijenio sam ga.
{35426}{35466}Što?
{35485}{35547}Ja sam izašao, a Nick nije.
{35554}{35625}Znao sam za njena|pisma i... Isuse Kriste...
{35632}{35689}Ne znam što hoæeš od|Nicka, ali ja nisam on.
{35696}{35754}Samo sam želio biti on.
{35861}{35956}Ti nisi Nick Cassidy?-Nisam.|Samo smo bili u istoj æeliji.
{35990}{36079}AIi pretvarao si|se da jesi? -Jesam.
{36110}{36196}Tako da se možeš spojiti|s mojom sestrom. -Da.
{36235}{36333}Tako da je možeš|poševiti. -Da.
{36397}{36461}Misliš da æe ti|pomoæi ako mi to kažeš?
{36514}{36555}Ne!
{36569}{36633}Ne, Ne!
{36640}{36678}Je li to on?
{36685}{36743}Molim te, Gabriele,|nemoj ga povrijediti!
{36749}{36806}To je kreten s kojim si se|dopisivala godinu dana?
{36808}{36861}Nemoj, molim te...|-Ovo je Nick Cassidy?
{36868}{36935}Da! Da!
{36982}{37046}Bolje mu je da nauèi|da te više poštuje!
{37103}{37167}Vodite je odavde. -Ne!
{37585}{37619}Da.
{37890}{37949}Proèitao sam|tvoja pisma, robijašu.
{38035}{38098}Nemoj meni prodavati|te božiæne fore.
{38384}{38435}Proèitao je tvoja pisma.
{38440}{38512}Jedan dan me nije|bilo i on je ušao...
{38520}{38570}Jane ga je|pokušala sprijeèiti
{38575}{38626}ali on ih je proèitao.
{38633}{38707}Koja pisma?|-Zna da si radio u kockarnici.
{38837}{38953}Molim? Ti si mu to smjestila!
{38968}{39054}Nisam, nisam. -Kad si|odluèila to uèiniti?
{39090}{39142}Nakon kojeg njegovog pisma?
{39146}{39214}Èetrdesetog?|Pedesetog? Prvog? Kojeg?
{39219}{39277}Nemoj, Nick...|-Nisam ja Nick!
{39288}{39392}Mislila si da æeš ga|zeznuti? E, on je tebe!
{39411}{39487}Ja nikad nisam radio u|kockarnici! Nisam ja on!
{39495}{39558}Ne razumiješ!|Ja te voIim!
{39567}{39657}Isuse Kriste... -Nemoj|psovati, Božiæ je.
{39675}{39819}Saslušaj me. Moj je brat|ubio neke ljude. Znam to.
{39830}{39899}Ne znaš ga. Ne znaš što je|sve kadar uèiniti. Ubit æe te.
{39906}{39973}Budeš li mu i dalje trubio|da nisi ti, ubit æe te.
{39994}{40071}Ovdje piše da maloprodaja|zaradi 50 % sveukupnog
{40076}{40141}godišnjeg dobitka|izmeðu 1. i 25. prosinca.
{40176}{40237}To je polugodišnji promet|za samo mjesec dana.
{40254}{40368}Pametna bi zemlja proglasila|još jedan darežljiv praznik.
{40381}{40438}Izmislila bi, recimo,|drugi Božiæ.
{40444}{40497}Krajem svibnja ili|poèetkom lipnja.
{40502}{40556}Da stimulira prodaju.
{40562}{40620}Otkad ideš u veèernju škoIu,|boli me gIava.
{40628}{40683}Drugi Božiæ...
{41105}{41195}Draga moja, seksi,|Ashy-Lashy,
{41244}{41308}stalno te sanjam.
{41314}{41371}Znajuæi da postojiš|negdje tamo vani,
{41377}{41441}zidovi mi više nisu tako|uski, tako èvrsti i hladni.
{41489}{41587}Jednom æu te odvesti|na jezero "Superior".
{41592}{41660}Prije nego što sam se našao|ovdje, prije vražje Millie,
{41676}{41785}radio sam u|kockarnici kao zaštitar.
{41830}{41889}Gledao sam kako|ljudi kradu žetone,
{41896}{41995}broje karte, kako se|napijaju kao svinjie.
{42032}{42091}To je bio najlakši|posao koji sam ikad radio.
{42129}{42273}Dobro pišeš, Nick. Dao|bih ti za ovo pismo peticu.
{42353}{42416}Sad nam reci ono|što moramo znati.
{42426}{42496}Poslije vas dvoje možete|živjeti sretno zajedno.
{42521}{42587}Podarite mi|neæake i neæakinje.
{42595}{42679}Slušaj me, nikad|nisam radio u kockarnici.
{42702}{42800}Nick Cassidy je tip koji|je napisao to pismo.
{42811}{42892}Bio sam s njim u buksi.|Bio je tamo zbog umorstva
{42898}{42975}nekog tipa koji je gnjavio|njegovu curu u bircu.
{42985}{43029}On je mrtav.
{43039}{43102}On je napisao ta pisma i|radio u kockarnici.
{43125}{43213}Moj je zadnji posao|bio kod automehanièara.
{43220}{43286}Dobio sam 5 god.|zbog kraðe automobila.
{43291}{43347}On je sa mnom dijelio|æeIiju. Otud ga poznajem.
{43352}{43411}Žao mi je zbog tvoje sestre.|Tek sam izašao.
{43455}{43505}Samo žeIim...
{43512}{43591}Ne znam ništa. Nikoga se ne|sjeæam. Samo hoæu iæi kuæi.
{43798}{43861}Ubij ga.-Nemoj,|Gabriele. Ne!
{43869}{43916}Što je?|-Obeæao si mi.
{43924}{43982}Obeæao sam da æemo|nestati kad nam pomogne.
{43987}{44070}Ali ovaj tip, ne želi|suraðivati.-Obeæao si mi...
{44075}{44137}A ti si meni obeæala da æeš|ga nagovoriti da nam pomogne!
{44187}{44255}Radije bi umro|nego bio s tobom.
{44333}{44397}Ionako bi bio grozan deèko.
{44453}{44510}Ubijte ga i razbacajte|ostatke posvuda uokoIo.
{44519}{44584}Nemoj, GabrieIe. Nemoj!
{44591}{44646}Umukni!
{45067}{45129}Nemoj mi zaprljati|cipeIe krvlju.
{45153}{45224}U redu, u redu!|Što žeIite znati?
{45231}{45287}Kockarnica ''Tomahawk''.
{45294}{45352}Isuse Kriste!|Što vas zanima?!
{45582}{45669}Pola godine piše|ljubavna pisma, i zezne me.
{45689}{45747}HvaIa na poštanskim|markicama, Ash.
{45788}{45853}U redu, što|vas zanima? -Sve.
{45909}{45985}Nick, voIim te.|-Hej! -VoIim te.
{46031}{46103}Rekla je da te voli.|Reci nešto.
{46152}{46296}Imao sam bolji seks u|zatvoru. -Baci ga u kamionet.
{46360}{46496}Èudovište, on nije taj tip.|Cijelo vrijeme dok si vozio,
{46503}{46622}govorio joj je da nije|on taj tip. Jasno mi je
{46630}{46711}da nama kaže da nije on.|Ali zašto bi njoj govorio?
{46729}{46815}Možda ipak nije on taj tip.
{47333}{47380}Da sam ušao u zatvor
{47385}{47444}s iskaznicom za knjižnicu,|s njom bih i izašao.
{47516}{47576}Tip koji je napisao|ona pisma, volio je AshIey.
{47647}{47707}Živio je za nju.
{47853}{47922}Gdje ona radi? -Što?
{47941}{48002}Napisala ti je stotinjak|pisama. Gdje radi?
{48010}{48063}U kozmetièkom odjeIu robne|kuæe Lindstrom's.
{48068}{48143}Koje joj je|drugo ime? -Samantha.
{48338}{48401}Kako su je zvali u|gimnaziji? -Bam-Bam.
{48410}{48469}Kako su je zvali|na faksu? -Kakvom faksu?
{48485}{48643}Koga se najviše boji? -Svog|brata. -Krivo. Utapljanja.
{48660}{48738}Krivo. Najviše se|boji svog brata.
{48863}{49042}To je ljubav. Vrijeme|je da poèneš prièati.
{49072}{49189}Vrijeme je za prièu.
{49309}{49394}Dovedite ga.|-Nemoj! Nemoj! Jebeš to!
{49401}{49471}Nick neæe ništa uèiniti dok|ne dobije nešto za Nicka.
{49482}{49562}Kužite? Želim vruæu èokoIadu.
{49583}{49658}Želite li prièati o poslu,|hoæu prvo vruæu èokoladu!
{49709}{49768}I pitu od oraha!
{49817}{49872}Dobra pita...
{50018}{50073}Kad si radio ondje...
{50268}{50358}Znao si kako izgleda unutra.
{50658}{50752}Znate što? Baš bi mi prijali|prženi kolutiæi od luka.
{50779}{50826}Rekli ste da æete|samo razgovarati.
{51034}{51131}Koliko ima novaca u|kockarnici? -Teško je reæi.
{51137}{51196}Bubni nešto.
{51232}{51293}Pet miIiona?
{51357}{51433}Isuse, doði ovamo! U pismu|si napisao kako za Božiæ,
{51438}{51514}pola zaštitara pošalju kuæi,|nitko ne ulazi niti izlazi,
{51531}{51599}a vi se ostali napijete.|Je li to istina ili nije?
{51651}{51728}Radilo se o Badnjaku.
{51732}{51793}Na Badnjak æemo opljaèkati|tu kockarnicu, robijašu.
{51802}{51864}A ti æeš nam reæi kako.
{51960}{52018}Ovo vidimo.
{52035}{52093}Sad nam reci ono što|ne možemo vidjeti.
{52105}{52171}Gdje su prostorije za|osoblje, alarmi,
{52180}{52236}kakav je raspored|na katu, i sve ostaIo.
{52310}{52386}Što je ovo? Kavez?|Kavez je na drugoj strani.
{52413}{52450}Sve ste pobrkali.
{52456}{52501}Tako izgIeda.|-Otkada?
{52516}{52555}Što je ovo?
{52562}{52636}Tu se poslužuju rebrica|za 5,99 doIara. -A buffet?
{52641}{52703}Buffet je kraj bara.
{52740}{52809}Zacijelo su preurediIi|kockarnicu. -MoIim?
{52818}{52875}Šef koji je vodio|kockarnicu...
{52904}{52956}Jack Bangs.
{52983}{53051}Uvijek je prièao da æe|preurediti kockarnicu.
{53059}{53118}Zacijelo je to uèinio|dok sam bio u zatvoru.
{53129}{53186}Sve se promijenilo.
{53195}{53252}Ne mogu vam pomoæi. Ne znam|gdje su sad smješteni
{53258}{53355}zaštitari. -Ne zanima me|gdje se doruèkuju palaèinke!
{53381}{53454}Zanima te lova?|Tamo gdje je sad buffet,
{53461}{53550}Bangs je imao ured.|Tamo je držao sef.
{53603}{53710}Tamo je držao svu lovu|koja je dolazila.
{53723}{53785}Zvao se Èarobnijaèki sef.
{53902}{53993}Krao je novac od plemena.|Tamo su ležale tisuæe.
{54014}{54069}Možda i milijuni.
{54076}{54137}Milijuni u Èarobnijaèkom sefu?
{54150}{54208}Milijuni.
{54219}{54266}Da, aIi, znate...
{54329}{54396}A vi mi kažete da|je ured premješten!
{54404}{54465}Bog zna što je još drukèije.
{54472}{54520}Osiguranje...
{54528}{54593}Želite da vam pokažem|raspored, a nemam pojma.
{54707}{54773}Onda nam znaèi ni ne trebaš.
{54940}{54999}Ne baš nužno.
{55017}{55093}Jer, pustite Ii me unutra,
{55105}{55177}znat æu kako se novac|kreæe i rad osiguranja.
{55188}{55262}Znam njihove signale.|Znam kako rade.
{55269}{55361}Pustite li me unutra,|usporedit æu crteže
{55367}{55433}i moæi æu vam reæi|je li se što promijenilo.
{55439}{55494}Greška, robijašu.|Uðeš li, prepoznat æe te.
{55501}{55557}Pa što onda?
{55564}{55627}Prepoznaju li ga, sjetit æe|ga se nakon pljaèke.
{55634}{55696}Neæe me prepoznati,|vjeruj mi. -A zašto?
{55744}{55819}Zato što æeš me prerušiti.
{55862}{55921}A timski rad?
{55926}{55985}Radije bi se vratio|u zatvor? -Možda i bih.
{56017}{56083}Ali tamo nemaš|50 programa na TV-u.
{56091}{56136}Lijepo spavaj.
{56143}{56191}Sutra æeš pjevati za veèeru.
{56300}{56362}Ponudi se.
{56385}{56460}Samo uzmi.|Ne treba mi.
{56778}{56865}Nick, daj da ti pomognem.
{56881}{56940}Idi u drugu sobu.|-Daj da ti pomognem!
{56946}{56994}Idi u svoju sobu!
{56999}{57055}Rekao je da samo|žeIi s tobom razgovarati.
{57061}{57120}Mislila sam nakon Nove|Godine... -Znala si što hoæe.
{57129}{57209}Da smo bar imali još maIo|vremena...-Nagovorila bi me?
{57329}{57389}Da æe biti gotovo|i da æe me pustiti?
{57396}{57455}Pucat æe mi ovako u potiljak.
{57463}{57543}Ili æu ostati|do kraja života u zatvoru.
{57551}{57636}I moj je život u pitanju.|Neæe me samo tako pustiti.
{57644}{57705}Misliš da se neæe|iskaliti na meni, Nick?
{57724}{57797}I ja sam upetljana|u ovo i zbilja se bojim.
{57804}{57855}Molim te...
{57883}{58080}Sjeæaš li se svih onih|pisama koje si mi napisao?
{58126}{58207}O tome kako æemo biti ti i|ja zajedno, protiv svih?
{58383}{58479}Znaš, to je moja sreæa.
{58490}{58551}Konaèno upoznam tipa|za kojim sam Iuda,
{58559}{58617}a moj ga brat|želi još više od mene.
{58622}{58680}Zašto mi nisi rekla da|ti je brat kriminaIac?
{58688}{58754}Gabriel poznaje neke tipove|u Miamiju i New Yorku.
{58760}{58828}Tipove kojima pomaže da|oružje doðe u Detroit.
{58835}{58898}To je sve što znam?|-Za njih sada radi?
{58905}{58973}Ne. On ne želi|ni s kim raditi.
{58979}{59052}Što su zadnje|pokrali? -Molim?
{59155}{59214}Koga su opljaèkaIi?
{59251}{59310}Ne bih rekla da su do|sada nekoga opljaèkaIi.
{59316}{59376}Samo prevoze oružje.
{59404}{59474}Nikad nisu izveli pljaèku?
{59547}{59652}Zaista?|Oni me stvarno trebaju.
{59676}{59737}Doista me trebaju.
{59953}{60011}Kauboj.
{60024}{60127}Poslat æeš me u indijansku|kockarnicu obuèenog u kauboja.
{60160}{60229}Nisi razmišIjao o tome?|-Ili to, ili kao baIerinu.
{60259}{60342}Trebat æe mi lova.|To je kockarnica.
{60480}{60551}Što da radim s 10 doIara?|-Nemoj davati napojnice.
{60581}{60648}Ako æemo raditi zajedno,|nemoj me sIati unutra
{60655}{60714}kao usamljenog kauboja|sa samo 10 doIara.
{60722}{60819}Hoæeš da budem neprimjetan?|To košta barem par stotina.
{60842}{60900}Dajte svoj doprinos, deèki.
{61718}{61796}Nemoj gubiti.
{61804}{61890}Hoæu li dobiti kaubojsko|ime iIi æemo samo...
{61898}{61976}Prepoznaju li te, imat|æeš i kaubojski sprovod.
{61988}{62035}Idemo.
{62043}{62108}Mièi ruke s mene!
{62167}{62226}Jesi li spremna za|kockanje, draga?
{62259}{62317}Sada jest.
{62354}{62415}Pripazite mi svi na gitaru.
{62870}{62928}Zaista mi otežavaš|pokušaj da se isprièam.
{62933}{62996}Zar to pokušavaš uèiniti?|Reci to s kljuèevima za auto.
{62998}{63060}Mnoge veze poèinju ovako.|S obiteljskim probIemima.
{63172}{63236}Ostavi to za kasnije, Bam-Bam.
{63247}{63310}Znate li koji je problem|kockarnice Tomahawk ?
{63315}{63372}Znate li što nas dijeli od|toga da budemo savršeni?
{63377}{63455}Snijeg. S-N-I-J-E-G.|Jebeni snijeg.
{63461}{63558}U Las Vegasu nema snijega.|Ne žele ga, ni ne treba im.
{63571}{63642}Mislim da èak imaju i|zakone protiv tog sranja.
{63658}{63733}Angažirali ste me jer|želite kvalitetu Vegasa.
{63748}{63805}Donio sam vam je.
{63812}{63878}Htjeli ste Lasvegaške|novine. Dao sam vam ih.
{63885}{63941}Ali, ne mogu vam|dati njihove profite
{63948}{64006}dok se ne okupite|oko logorske vatre,
{64011}{64088}popušite lulu mira i uèinite|nešto oko tog snijega.
{64125}{64187}Dosta su toga napravili.|Proširili su restoran.
{64204}{64278}Ovdje su premjestili igre.
{64449}{64501}Poznaješ ovog tipa?
{64507}{64562}Da, to je Mike.
{64595}{64657}Mike radi ovdje.
{64674}{64755}Potroši nešto bratove love.|Malo æu razgledati uokolo.
{64804}{64914}Možda biste htjeli ostati i|probati naša vrhunska rebrica.
{65308}{65368}Dvije rum-coIe, molim vas.
{65377}{65440}Brže.
{65499}{65561}Hrpa sitnih kladiteIja.
{65618}{65636}Hvala lijepa.
{65644}{65708}Kako ide, kauboju? -Dobro.
{65719}{65780}Zovem se Jack Bangs.|Vodim kockarnicu.
{65794}{65852}Da te pitam nešto.
{65859}{65934}Otkud si saznao za|nas? S radija? TV-a?
{65945}{65988}Iz zatvora.
{65993}{66037}Iz zatvora.
{66185}{66244}Ne smijem se vratiti u Vegas.
{66435}{66492}Dobili smo!
{66596}{66683}Što je htio? -Htio je znati|otkud znam za kockarnicu.
{66710}{66768}Lakše malo. Olakšaj mi maIo.
{66823}{66879}Bože, oprostite!
{66885}{66925}Isuse Kriste!
{67012}{67058}Nije se samo|osiguranje promijenilo.
{67066}{67122}Idem ovo oprati.
{67141}{67207}Što se dogodilo? -Odlijepili|su mu se brkovi. Uzmi ovo.
{67691}{67747}Dam ti sto dolara|za ovu jaknu.
{67753}{67809}Nemojte me ubiti! -Smiri se.|Nitko te neæe ubiti.
{67812}{67867}Djed Mraz æe ti dati|$100 i kaubojsku jaknu.
{67934}{68018}Daj mi još jedno, dušo.
{68115}{68170}Kako si? -Smrzavam se.
{68235}{68320}Koliko dugo radiš ovdje?|-Pet godina. Od otvorenja.
{68343}{68423}Kad ste|preuredili? -MoIim?
{68430}{68499}Mislim na kockarnicu.|Sve ste preuredili.
{68522}{68582}Tomahawk|je isti od otvorenja.
{68589}{68644}Samo se gubitnici|koji dolaze ne mijenjaju.
{68687}{68744}Lažljivi gade!
{68838}{68891}Bježi, maIi!
{69138}{69186}Sranje!
{69726}{69773}Evo ti tvoja jakna!
{69780}{69826}Dao mi je sto dolara!
{69975}{70036}Što se dogodilo?|-Zeznuo nas je.
{70049}{70128}Kockarnica se nije|mijenjala od otvaranja!
{70142}{70207}Èudovište, razgovarao je s|upraviteljem tamo. -Eno ga!
{70366}{70417}Brže, brže!
{70422}{70459}Hajde!
{70983}{71046}Samo ti trèi, Romeo!
{71054}{71117}Što brže ideš,|mi æemo stiæi tamo.
{71133}{71189}Mi smo kamionaši, kretenu!
{71194}{71241}Vožnja je naš kruh!
{71891}{71911}U pomoæ!
{71918}{71978}U pomoæ! -Misli|da æe nam pobjeæi.
{72020}{72064}Sranje.
{73379}{73438}Moramo doæi do onog drveæa!
{73714}{73771}Sranje!
{74701}{74763}Izvucite ih odande!|Hajde, izvucite ih!
{74780}{74841}Je li dobro?|-Dobro, dobro...
{74868}{74933}Obzirom na tvoju brzinu,|teško æu te prihvatiti kao
{74938}{75019}nekog svog.|-Trebate Ii pomoæ?
{75144}{75187}Trebate pomoæ?
{75195}{75256}Gubi se odavde!|-Zaèepi!
{75261}{75310}Gubi se odavde!
{75356}{75415}Treba li vam pomoæ...
{75485}{75563}Gabriele, nemoj!|-Neæe nam nauditi.
{75582}{75658}Neæe nas zapamtiti.|Nemoj! -Zaèepi!
{75716}{75753}Ne!
{75836}{75893}O, Bože!
{76174}{76236}''Što je ovo?|Ovo nije Tomahawk. ''
{76247}{76314}''Ovo prvi put vidim.|Sigurno su ga preuredili.''
{76344}{76416}''Buffet je bio tamo,|a bar na drugoj strani''
{76445}{76512}''Ne znam. Ne mogu vam|pomoæi. Nemam pojma.''
{76549}{76610}Nešto mi govori da|nisi bio iskren sa mnom.
{76641}{76709}Što si rekao upraviteIju|kockarnice? -Ništa.
{76823}{76883}Ništa. Mislio je|da sam kockar.
{76894}{76982}Da nisi spominjao|pljaèku? -Kunem se da nisam.
{77090}{77160}Isuse Kriste! Mislio|je da sam kockar!
{77182}{77240}Nije me prepoznao!
{77254}{77313}Nije me prepoznao!|Za Boga miIoga!
{77327}{77387}Vozim kamione veæ jako dugo.
{77423}{77500}7 milijuna kilometara ceste|sam prošao. Užasnog terena.
{77517}{77579}Da im kažem da sam umoran,|uzeli bi nekog drugog.
{77607}{77685}1600 km do zalaska sunca,|ili ništa od klope za moje.
{77715}{77771}Sranje.
{77803}{77925}A na svakoj cesti samo su|mame i tate i ništa drugo.
{77932}{77995}I njihova djeèica koja me|pogledom šalju k vragu
{78002}{78061}i govore da se maknem s|njihove sretne auto-ceste.
{78120}{78190}I ja sam radio...
{78197}{78256}I crnèio sam.
{78264}{78358}Èekao da se auto-ceste|rascijepe na pola,
{78366}{78461}da se rijeke izliju i da se|Bog spusti na ZemIju
{78468}{78523}i da me na neki naèin nagradi.
{78546}{78604}Da mi da moj dar
{78613}{78677}i kaže: ''Gabriele, sine moj,
{78700}{78774}gotovo je s vozikanjem|kamiona.
{78832}{78889}Pa, robijašu...
{78917}{78975}Dao mi je taj dar.
{78999}{79061}Kunem se Bogom, samo je htio|znati otkud znam za njih.
{79082}{79153}Nije znao da sam to|bio ja. Nije to znao!
{79215}{79288}Nemoj me samo poèeti gaðati.
{79358}{79439}Nick, pokušavao|sam te pogoditi.
{79569}{79661}Zato što ne zaslužujem da|budem u ušljivom motelu
{79683}{79745}usred pederskog Michigana,
{79759}{79851}i da gaðam pikadom,|tebe, bezvrijednu gnjidu!
{80102}{80172}Znaš što?
{80177}{80289}Moja mIaða sestra zaslužuje|nekog, mnogo boljeg od tebe.
{80361}{80422}Veèeras æemo još|jednom pogledati kartu.
{80444}{80527}I ovaj put bilo bi ti bolje|da kažeš nešto pametno.
{80601}{80642}Što su ti uèinili?
{80672}{80722}Morali su mi|nešto rastumaèiti.
{80728}{80785}Što si mu to uèinio?
{80823}{80881}Gubi se!
{80889}{80940}Samo otiði.
{81136}{81250}Samo sam se htio vratiti u|Sidnaw. Probati mamin umak
{81260}{81350}i kolaèe od|brusnice tete Lisbeth.
{81383}{81448}Pravi ih s pravim brusnicama.
{81456}{81497}Stvarno je dobar.
{81506}{81565}Stiæi æemo tamo, dušo.
{81609}{81666}Samo se odmori.
{81802}{81861}Spasio si mi život.
{81940}{82019}Mogao si pobjeæi,|ali nisi. Spasio si me.
{82025}{82107}Ti si mene spasila. -Spasila|sam te zato što te volim.
{82184}{82250}Zašto si me spasio?
{82279}{82335}Onaj tip iz zatvora,
{82343}{82404}Rudy, kradljivac automobila,
{82412}{82470}ponekad sam mu|èitao tvoja pisma.
{82489}{82577}Znao sam da su|bila intimna, ali...
{82664}{82783}Kad bih mu ih èitao,|imao bi izraz lica
{82790}{82908}kao da zamišlja da|njemu tad pišeš, kunem se.
{82956}{83015}A ponekad...
{83021}{83081}Mislim da se i|zaljubio u tebe.
{83110}{83172}Ulila si nadu|dvojici muškaraca, AshIey.
{83207}{83266}Nada je dobra stvar.
{83287}{83378}Zajedno æemo se izvuæi iz|ovoga, obeæajem ti to.
{83402}{83442}Obeæajem ti.
{84038}{84094}Pjevaj, Nick.
{84615}{84685}ŠaIa...
{84784}{84829}Dobro.
{84836}{84901}Što želite uèiniti jest...
{84936}{85033}Želite se popeti|na najvišu razinu.
{85039}{85142}A to æete uèiniti kroz ova|vrata na zapadnom zidu.
{85185}{85237}Morate doæi do zaštitara.
{85243}{85302}Odande se morate spustiti do|blagajnikova mjesta.
{85305}{85384}Onda u brojaènicu novca.|Tamo je nenaoružani èuvar.
{85403}{85519}Vrata se otvaraju šifrom|koju æe blagajnik znati.
{85528}{85611}A Èarobnijaèki sef?|-To je gore.
{85616}{85689}Doæi æemo do|Èarobnijaèkog sefa.
{85718}{85824}Morate imati jednog za kavez,|još jednog za kockarnicu
{85829}{85878}i jednog na vrhu.
{85885}{85942}Onda æe vam trebati|netko da pokupi lovu
{85947}{86032}i još dvojica koja æe|paziti na ulaz i izlaz.
{86100}{86157}Ima nas petero.|Ashley æe biti vani.
{86187}{86244}Ali, trebaš šestoro ljudi.
{86282}{86336}Ne.
{86355}{86411}Ne izmišljam to.
{86417}{86475}Uðeš li s petoricom, neæeš|imati nadzor nad izlazom
{86477}{86526}ili alarmom.
{86534}{86583}Znam što govorim.
{86600}{86657}Neka dignu ruke oni koji|su sudjelovali u pljaèki.
{86686}{86743}Tko je sudjelovao u|pljaèki, neka digne ruku.
{86826}{86889}Ja sam sudjelovao.
{86954}{87027}Trebaš šestoricu|ljudi. Zaista trebaš.
{87047}{87101}Što æeš uèiniti?
{87264}{87341}Želim nacrt|sIužbe osiguranja.
{87352}{87424}Gdje su sva vrata,|èuvari i svaka pepeljara.
{87450}{87498}Dobro.
{87510}{87564}Šestero ljudi,|to je šest pištolja...
{87616}{87665}Nema šanse.
{87672}{87766}Što da uèinim? Neæe me se|bojati bez pištolja. -Toèno.
{87775}{87830}Što je, GabrieIe?
{87873}{87973}Zar ti nije za to trebao?|Zato što se u to razumije?
{88010}{88081}Bez pištolja.|-Kako hoæeš.
{88098}{88157}Onda moraš smisliti|kako æeš doæi do zaštitara,
{88162}{88216}a da nikomu|ništa ne bude sumnjivo.
{88221}{88297}Odmah ti kažem da ti to|neæe uspjeti sa ski maskama.
{88386}{88492}Taj sam dio isplanirao davno|kad sam proèitao tvoje pismo.
{88533}{88599}Svi æemo se|odjenuti kao kauboji?
{88608}{88665}Ma ne, ne kao kauboji.
{88671}{88728}Ne na Badnjak.
{88971}{89031}Sigurno se šališ.
{89043}{89102}Vrijeme je blagdana.
{89304}{89368}Evo ti tvoj crtež.
{89430}{89488}Bolje da bude.
{90505}{90575}NAORUŽAN PONOSOM .
{91749}{91809}Jedini tip koji ne nosi|pištolj u svom kamionu.
{92058}{92139}Mogao bi govoriti sa|silikonskim jezikom.
{92146}{92209}Vidio si tipa s jezikom od|silikonskih umetaka za cice?
{92220}{92290}Ovog mog tipa najmanje|su brinuIa crna pluæa.
{92320}{92376}Iz kože mu je|izbijalo toIiko dima
{92383}{92437}da bi ljudi pitali:|''Hej, gdje se roštilja?''
{92661}{92730}Ne, ne!
{92739}{92802}Mièi se od mene, k vragu!
{92848}{92934}Bolje ti je da me se kloniš|da ne bih sve uprskala!
{92948}{93022}Samo sam te htio sprijeèiti.|-Htio si me ubiti!
{93051}{93144}Kad sam vidio kako si|pala, mogao sam se ubiti.
{93153}{93213}Ti si nešto najbolje|što mi se dogodilo.
{93220}{93280}Znam da moraš biti s njim.
{93295}{93365}Ali, zlo mi je od toga.
{93385}{93452}Moramo nastaviti ovako...
{93462}{93547}Uèinio je ono što trebamo|i pomogao nam je s kartom.
{93585}{93644}Više nam ne treba.
{93816}{93883}Piješ mi krv, znaš Ii to?
{93919}{94004}Slušaj me, jer moramo biti|jako pametni oko toga.
{94024}{94119}Što me više želi, više æe mi|htjeti pomoæi.
{94137}{94207}On je samo radna snaga.
{94221}{94303}Želi novac?|-Ne, srce.
{94398}{94450}On želi mene.
{94512}{94574}Tvoju mlaðu sestru.
{94680}{94751}Da nas barem sada mogu|vidjeti mama i tata.
{94904}{94972}Da barem samo sve radi|mehanièki.
{94981}{95041}Meni se èini da samo ševi|moju djevojku
{95051}{95147}i da to jedino radi kako|treba.
{95167}{95196}Srce...
{95209}{95276}On mi ništa ne znaèi.|-Vidimo se kasnije, gnjide!
{95299}{95371}Uza sve svoje bivše, morat æe|opljaèkati tri kockarnice!
{95387}{95441}Našao si GabrijeIa?
{95447}{95511}Sa curom je. Nadoknaðuje|vrijeme izgubljeno s Nickom.
{95516}{95582}Idemo na cugu. -Trebao bih|provjeriti našeg Romea.
{95627}{95685}Nasmiješiti mu se|s ljubavlju.
{95843}{95899}Èekat æu te u bircu.
{97332}{97387}Hajde, otvori se.
{97484}{97539}Ako mogu provaliti u|automobil,
{97545}{97606}mogu i motelska vrata.
{97818}{97876}Tko lupa vratima?
{98368}{98434}Kako si?
{98865}{98919}Vaši raèuni.
{98926}{98981}Sve najbolje!
{99213}{99278}Hvala na $100 za plaæeni|program.
{99323}{99393}To je za onih 200 koje si|popio iz mini-bara.
{99408}{99466}Dosta je! -To je bila moja|kreditna kartica!
{99473}{99529}Mislio sam, kad veæ plaæate|sobu...
{99592}{99662}Htio si oružje, robijašu...
{99709}{99763}Nemoj!
{99940}{100021}Vidi što su ti patuljci Djeda|Mraza donijeli.
{100029}{100087}Što kažeš na njegove|patuljke?
{100092}{100148}To su vilenjaci.|Vilenjaci Djeda Mraza.
{100157}{100217}Zahvali se, kretenèino.
{100356}{100419}Druženje s kriminalcima|primora te da mnogo planiraš.
{100424}{100515}Ali niti jedan posao koji sam|obavio, niti jedan plan,
{100522}{100598}nije se odvijao|onako kako je zamišljeno.
{100631}{100694}Moji planovi za|bijeg su se izjalovili.
{100705}{100789}Buduæi da sam na uvjetnoj,|ne mogu otiæi na policiju.
{100809}{100897}Nervozan si?
{100925}{101008}Trenutno si ti|samo vozaè kamiona.
{101014}{101080}Niši uèinio ništa loše.
{101085}{101143}Uèiniš li ovo, kajat æeš se|do kraja života.
{101150}{101203}Hvala što si me na to|podsjetio.
{101212}{101250}Opusti se.
{101258}{101312}Popij nešto.
{101319}{101370}Malo ruma.
{101396}{101448}Nije li to tvoje omiljeno|piæe?
{101898}{101971}Hej, baš si žedan!
{102019}{102101}Bolje ti je da ovo radiš|kako je Gabrijel isplanirao.
{102137}{102202}Inaèe se možeš pozdraviti sa|životom.
{102560}{102629}U cijeloj zgradi|nije bilo ni žive duše.
{102754}{102827}Pošalji deèke kuæi, Ede.
{102835}{102898}Tom, idi proslaviti|Božiæ sa svojima kuæi.
{102905}{102981}Don, možeš iæi.|-Sretan Božiæ, Jack!
{103052}{103110}Nitko više ne dolazi ni|varati ovdje.
{103121}{103188}Zdravo!
{103221}{103312}Djedice su stigIe! Drago|mi je što vas vidim.
{103389}{103450}I htjeli bismo|vam uzeti novac.
{103457}{103508}Došli smo pokupiti|lovu. Imate li novaca?
{103515}{103560}Kako ste?
{103567}{103614}Jako dobro,|samo što ne radimo.
{103622}{103667}Sve najbolje!
{103674}{103730}On je iz Lindstrom'a,|a ja sam iz Saveawaya.
{103737}{103798}Nemamo igraèaka za|djecu, ali imamo novac.
{103953}{104006}Svi ulozi.
{104053}{104123}Srce, kako si?|-Smrzavam se. Izvolite?
{104134}{104192}21. -Uzeli ste mi kartu!
{104204}{104254}Oprostite.
{104260}{104313}DjeliteIj ima|18. -Vidi sad.
{104320}{104385}Dobit æu tvoje|sanjke. -Saveawayl
{104395}{104442}Sjedni kraj mene.
{104449}{104511}Kako si? -Hoæete|skinuti te brade?
{104522}{104586}Neæu. Ta mi|brada donosi sreæu.
{104603}{104663}Èuvaj ga se. On donosi|nesreæu.
{104693}{104751}Djede br. 3, izvoIite?
{104761}{104820}Može li debeljko dobiti|kovanice od 25 centa?
{104838}{104883}Pazi na moj ulog.
{104905}{104967}5...9.
{105008}{105067}Opet ste mi maznuli kartu!
{105093}{105149}Idi, potraži dimnjak|u koji možeš upasti.
{105171}{105252}Isuse, uništit æete me ovdje!
{105261}{105355}Tako to ide.|-Dolaze još dvojica.
{105363}{105451}Evo, takve vas|volim. Tako treba.
{105462}{105523}Postoji li sindikat za|Djedove iz robnih kuæa?
{105565}{105609}Tko bi znao?
{105618}{105681}Idi za stol za starce!
{105688}{105741}Uzimaš novac Djedu Mrazu!|-Nema drugog stola!
{105760}{105845}Kakvi to Ijudi|varaju Djeda Mraza, zaboga?
{105866}{105932}Zaštitari! -Uzeo si je!
{105944}{105992}Varaš me!
{105999}{106058}Ostani dolje.|Sve je u redu.
{106073}{106145}Djed Mraz ubija|Boga u tvojim èuvarima.
{106299}{106352}Zaštitari...
{106359}{106411}Gore, skreni|desno, tamo su.
{106711}{106769}Iskljuèite vražji alarm!
{106813}{106850}Bacite ih!
{106856}{106910}Bacite pištolje!
{106947}{107035}Maknite se od aIarma!|-OdIožite oružje!
{107049}{107090}Brže, brže!
{107108}{107165}DoIje!
{107303}{107364}Ovo više ne trebaš.
{107521}{107584}Idemo! Upadajte ovdje!
{107675}{107731}Samo poslušajte|moje prijatelje.
{107739}{107797}Samo su maIo uznemireni.
{108139}{108198}Koja je šifra za sobu|gdje se broji novac?
{108216}{108274}Bacite pištolje!
{108280}{108328}Ni makac!
{108885}{108959}Gade jedan! Ovdje nema|oružja! Vraga!
{108966}{109037}Gade jedan!|-Svi dolje!
{109161}{109224}Ovdje nema oružja. -Pusti sad|njega i uzmi lovu.
{109238}{109297}Zaboravi na njega i uzmi lovu!
{109404}{109507}Zaboravi na njega. Za ljude|poput nas nema buduænosti.
{109532}{109607}Potjeèemo iz|tvornièkih gradova,
{109613}{109688}iz gradiæa bez perspektive.
{109703}{109760}Bez buduænosti|su. Svi su isti.
{109765}{109820}Želiš li buduænost,|moraš je ukrasti.
{110417}{110475}Ne mogu se vratiti|u Las Vegas.
{110576}{110661}Boli me briga za Las Vegas!
{110698}{110758}Novac je u automobilu.|Idemo sad odavde.
{110861}{110918}Sjeæaš se Nicka|Cassidyja, zaštitara?
{110926}{111007}Da, Nick Cassidy?|Gdje je on?
{111015}{111074}Imamo dosta love.|Brišimo odavde!
{111081}{111132}Gdje je on?
{111221}{111310}To nije Nick Cassidy.
{111324}{111398}Nick Cassidy je radio|ovdje prije dvije godine.
{111497}{111557}Kauboju!
{111700}{111780}Takav je tvoj život.|Zeznula si krivog tipa.
{111872}{111935}Ja sam Rudy Duncan.|Još možemo provesti Božiæ
{111942}{111982}zajedno.
{111990}{112038}Gade prokleti!|-AshIey!
{112048}{112109}Ne, k vragu!|-Imaš sreæe, robijašu.
{112181}{112261}Provest æeš Božiæ|s Isusom Kristom.
{112287}{112381}Samo malo. Taj sef postoji.|Bio sam s Nickom u zatvoru.
{112390}{112443}Nešto mi je rekao,|a neèega se sjeæam.
{112450}{112510}Rekao mi je da upravitelj|èuva skrivenu lovu u uredu.
{112515}{112582}Da... da...|-Nema sefa!
{112589}{112665}Sef ne postoji! -Rekao|mi je to! Sef postoji!
{112692}{112746}On krade od|otvaranja. Sef ne postoji.
{112751}{112799}Postoji. -A gdje je onda?
{112817}{112891}Iza police s piæem.
{113648}{113733}Diži se. Otvori ga.|-Ne mogu se vratiti u Vegas.
{113744}{113813}Boli me briga|za to! Otvori ga!
{113833}{113887}Brže!
{113924}{114010}Ne mogu se vratiti...
{114148}{114204}Èarobnijaèki sef.
{114212}{114251}Èarobnijaèki sef.
{114704}{114778}Djede Mraze!|Dobro došao u Tomahawkl
{115531}{115586}Diži se.
{115874}{115971}Da, Bog je dobar.
{116015}{116135}Što æeš sada reæi|vilenjacima Djeda Mraza?
{116243}{116320}Zahvalit æeš se.
{118066}{118125}Nikad ne|ponavljam istu grešku.
{118166}{118228}Upravo jesi.
{118728}{118782}Krivi tip.
{118793}{118868}Opljaèkali smo kockarnicu|s krivim. Nije li to Božiæ?
{118913}{118971}Nije li ovo Božiæ?
{119032}{119088}Neka nas sve Bog blagoslovi.
{120099}{120155}Baš si pametan.
{120162}{120221}Strašno si pametan.|Pametniji od ostalih.
{120228}{120304}Èarobnijaèki sef.|Mali dar za nas u sefu.
{120322}{120435}Imam poklon za tebe od|Puga, Merlina i Jumpyja.
{120447}{120498}Otiæi æeš tamo gdje su oni.
{120505}{120570}Tamo æe te pronaæi i|prebiti k'o vola u kupusu!
{120586}{120661}Misliš da si pametan|i da imaš sreæe?
{120667}{120719}Hajde da vidimo|koliko si pametan!
{120726}{120781}Evo koliko si ti pametan.
{120788}{120858}Izašao si iz Tomahawka i|na pola si puta za Kanadu,
{120864}{120919}sve dok te led ne zaustavi.
{121070}{121120}Klekni!
{121127}{121182}PogIedaj!
{121189}{121263}Dok tresneš o tlo, auto|æe se zapaliti kao komet.
{121276}{121340}A s njim sigurno i sav novac.
{121374}{121443}To je bila tvoja|ideja ili njezina?
{121465}{121545}Prièala mi je o|èasopisima za robijaše.
{121568}{121626}Pomislila je da sigurno|postoji neki usamljeni tip
{121628}{121679}s korisnim znanjem|koga nema tko slušati.
{121697}{121889}I tako smo nabavili zalihe|pisama i listovnog papira.
{121896}{121977}Teško je biti|djevojka vozaèa kamiona.
{122007}{122101}Doði, dušo!
{122255}{122319}Spasio sam ti|život. -Nisi smio.
{122329}{122382}Zaista te je volio, znaš?
{122393}{122447}Nick te je zaista volio.
{122574}{122630}A tko ne bi?
{122697}{122752}Možda si htjela|da ovdje završi.
{122764}{122865}Na dnu litice sa|spaljenim srcem. Možda.
{122878}{122933}Ali, to se nije dogodilo.
{122958}{123016}Bio je najsretniji kad je|èitao tvoja pisma.
{123024}{123082}Hajde, upadaj u koIa.
{123131}{123198}Hej, Gabriele!
{123316}{123382}Ne moraš biti|plemenit prema meni.
{123411}{123479}Tip te je obranio i ubijen|je, a ti loviš njegovu curu?
{123583}{123643}Rekla sam, nemoj|mi govoriti o pohlepi!
{123650}{123727}Ne to.|Kako si znaIa za nož?
{123742}{123796}Nikad nisam spominjao|nož. Otkud to znaš?
{123816}{123881}Rekao si da je pravi|Nick umro spašavajuæi tebe.
{123890}{123974}Nisam. Rekao sam|da je umro. To nisam.
{123981}{124074}Jesi. -Nikad nisam|rekao kako, samo da je umro.
{124083}{124135}Rekao si da su|ga izboli nožem.
{124143}{124201}Da je umro.|Nikad nisam rekao kako.
{124210}{124301}Rekao si da|su ga izboli nožem,
{124311}{124367}ili neèim sliènim.
{124410}{124457}Ash?
{124462}{124525}Otkud je znala da|je bio nož u pitanju?
{124550}{124602}Ash?
{124610}{124667}Kako si znala?
{124831}{124893}Isuse Kriste...
{124914}{124955}Muškarci.
{126411}{126469}Sretan Božiæ, Rudy!
{126845}{126915}Uspjeli smo, srce!
{126922}{126962}Da, jesmo.
{126970}{127027}Uspjeli smo.
{127033}{127095}Malo se sve pobrkalo, ali...
{127103}{127173}Sve æu ti|isprièati kad krenemo.
{127328}{127387}Samo da znaš,
{127405}{127489}nikad se nisam ševila|s pogrešnim muškarcem.
{127503}{127566}Onda, Rudy...
{127588}{127654}Želim te upoznati|s Millie Bobek.
{127670}{127744}Sjeæaš se Millie? Moje|djevojke prije nego sam
{127751}{127806}završio u zatvoru?|Radila je u onom bircu
{127814}{127952}gdje sam ubio onog tipa.|Millie je ovdje...
{127991}{128086}Posluživala je te|razdražljive vozaèe kamiona.
{128100}{128151}Stvarno puno brbljaju.
{128156}{128229}Pripremaju pljaèku stoljeæa.
{128236}{128296}Nema veze ako 2 god.|gulim u zatvoru.
{128303}{128351}Neka se ona|sprijatelji s njima.
{128358}{128416}Neka im kaže da joj|je pravo ime AshIey.
{128423}{128486}I da ima ideju o tome da|piše deèkima u zatvoru.
{128496}{128553}Pronaæi naivca|kojem æe povjerovati.
{128604}{128718}Znaš... nikad to ne bi|uspjeli bez tebe, Nick.
{128770}{128833}Hoæu reæi, Rudy.
{128842}{128901}Oduvijek sam želio opljaèkati|tu kockarnicu, Rudy.
{128909}{129000}Još otkad sam tamo radio.|A najboIje je da to drugi
{129008}{129105}uèine umjesto mene. Platio|sam AIamu $100 da me ubode.
{129123}{129182}On guli doživotnu.|Svejedno mu je.
{129190}{129244}Trebao me je ubosti kasnije,
{129255}{129353}ali kad je izbila tuènjava,|nisam mogao vjerovati.
{129390}{129495}Prerezao me po rebrima i|kapsula puna krvlju iz
{129509}{129583}domaæe radinosti ti osigura|topli, bolnièki krevet.
{129613}{129693}Platio sam èuvarima da|rastrube da sam mrtav.
{129704}{129771}Kad je rana zacijelila,
{129778}{129836}jutros sam izašao iz zatvora,
{129844}{129957}a veèeras sam bogat èovjek.
{129975}{130025}Ulazi u auto.
{130204}{130284}Drži ga na nišanu.
{130292}{130352}Kako si znao da æu to uèiniti?
{130359}{130456}Zato što si slušao svaki|put kad sam èitao pisma.
{130513}{130624}Èak i da nisi zagrizao|mamac, mogli smo pokušati.
{130656}{130722}Samo ih je trebala uvjeriti|da to mogu i sami uèiniti.
{130755}{130832}Ali, pojavio se|dobri, stari Rudy.
{130837}{130895}Dobri, stari,|predvidljivi Rudy.
{130902}{130970}Svaki put na brzinu|želi doæi do love.
{130984}{131046}U Tomahawk je ušlo|pet Djeda Mrazova.
{131065}{131139}To æe izjaviti svjedoci.
{131148}{131218}Znaèi da ih pet|ne smije izaæi van.
{131246}{131314}Moramo imati pet.
{131400}{131473}Misliš da ne znamo|što su slabi izgledi?
{131487}{131575}Moja te djevojka vukla za|nos kao mladog majmuna.
{131583}{131642}Ako zezneš stvar,|ona æe zbrisati.
{131649}{131716}Oni bi tražili AshIey Mercer.
{131726}{131779}Ma tko ona bila.
{131874}{131959}Pola godine prièao|sam ti o toj kockarnici.
{131976}{132036}Sad valjda znaš zašto.
{132123}{132195}Ulio si im samopouzdanja|da uðu unutra, Nick.
{132239}{132305}Samo smo to trebali od tebe.
{132312}{132366}Rekao si neke|lijepe stvari o meni.
{132372}{132431}Cijenim to.
{132438}{132495}Znaš što? Imaš pravo.
{132503}{132557}Zaista je volim.
{132588}{132645}I ona...
{132657}{132733}Ona voli mene.
{132741}{132800}Cijelo si vrijeme|bio u pravu u vezi toga.
{132923}{132981}Božiæ je, lutkice.
{133039}{133105}Zapalimo drvce.
{133427}{133496}Sranje!
{133562}{133613}Piši mi.
{133666}{133743}To je kao vožnja|bicikla, ne zaboravlja se.
{133779}{133834}Zbogom, Rudy.
{133839}{133897}Bilo je lijepo|družiti se s tobom.
{134037}{134111}1.pravilo: Nikad ne daj volan|u ruke kradljivcu automobila!
{134207}{134292}Ne!!!
{135043}{135133}U Tomahawk su|ušlapetorica Djeda Mraza.
{135146}{135213}To æe izjaviti svjedoci.
{135220}{135306}To znaèi da|petorica neæe izaæi.
{135313}{135371}Mora ih biti pet.
{135816}{135869}Rudy...
{135876}{135935}Ostajemo samo nas dvojica.
{135985}{136042}Možemo podijeliti Iovu.
{136077}{136144}Misliš da sam mislio|ozbiljno za Millie Bobek?
{136178}{136240}Htio sam je ubiti.
{136251}{136335}Moraš mi vjerovati!|Kunem se, vjeruj mi!
{136353}{136405}Vjeruj ti ovo.
{136442}{136498}Rudy! U pomoæ!
{139848}{139908}Samo želim stiæi u Sidnaw.
{139928}{139987}Na božiænu veèeru.
{139996}{140054}Gledati tekmu|sa svojim starim.
{140062}{140116}Spavati u svom krevetu.
{140123}{140183}i jesti ostatke|hrane bar pola godine.
{140198}{140252}Pojesti malo|božiæne purice.
{140616}{140750}Kao što sam rekao, nikad|baš nisam volio blagdane.
{140756}{140819}Sve do sada.
{140820}{141066}SVRŠETAK
