{1170}{1310}{C:$FF0000} DON JUAN DEMARCO
{2970}{3020}Moje ime je Don Juan DeMarco.
{3020}{3130}Ja sam sin velikog maèevalaca|Antonija Garibaldija DeMarca,
{3130}{3200}koji je tragièno poginuo braneæi èast|moje majke,
{3200}{3280}prelijepe Done Inez Santiago.
{3330}{3400}Ja sam najveæi svjetski ljubavnik.
{3840}{3900}Vodio sam ljubav sa preko tisuæu žena.
{3960}{4050}Prošlog utorka sam napunio 21 godinu.
{4130}{4250}-Dobra veèer, gospodine.|-Dobra veèer, Nicholas.
{4300}{4380}Nijedna žena iz mog zagrljaja|nije otišla nezadovoljena.
{4380}{4500}Samo jedna me odbila,|i to na moju veliku nesreæu,
{4500}{4600}jer mi je ona od svih najviše znaèila,|pa sam iz tog razloga
{4600}{4700}odluèio da u 21-oj okonèam svoj život.
{4750}{4820}Ali, prije toga, moje posljednje osvajanje.
{5500}{5600}-Smijem li?|-Zapravo, ja oèekujem prijatelja koji oèigledno kasni,
{5600}{5680}ali æe biti ovdje uskoro.|-Neæu vas ometati.
{5700}{5750}Ja sam Don Juan.
{5850}{5930}To je vrlo duhovito. Da li se u hotelu|održava neki maskenbal?
{5930}{5990}Ne, ja sam Don Juan.
{6000}{6100}Izravan potomak plemenite|španjolske obitelji.
{6100}{6180}-I ti zavodiš žene.|-Ne. Ja nikada ne iskorištavam ženu.
{6200}{6300}Ja ženama pružam zadovoljstva. Ako se one odluèe za to.
{6360}{6440}To je, naravno, najveæe zadovoljstvo|koje æe one ikada iskusiti.
{6600}{6750}Postoje žene finog kova, 
{6750}{6850}izrazite graðe kose,|s lijepim linijama ušiju,
{6850}{6900}koje imaju vjeèni sjaj.
{6930}{6970}Te žene...
{7062}{7200}imaju prste iste osjetljivosti|kao i njihove noge,
{7200}{7320}vrhovi prstiju imaju istu|vrstu osjetljivosti kao i stopala,
{7320}{7520}a kada im dodirneš zglobove|to je kao da im prelaziš rukom preko koljena,
{7520}{7620}a ovaj nježni, mesnati dio,
{7650}{7750}to je kao da im diraš butine,
{7870}{8020}i... konaèno...
{8180}{8250}Svaka žena je misterija koju treba otkriti,
{1080}{1310} DON JUAN DEMARCO
{8280}{8350}ali žena nema ništa od pravog ljubavnika.
{8380}{8450}Njena boja kože nam govori kako da se postavimo,
{8450}{8550}boja rumenila ruže se mora iznuditi,
{8550}{8650}da bi se žena otvorila kao|ružine latice na toplini sunca.
{8700}{8770}Blijeda i uzavrela koža,
{8800}{8900}zove na val požude da se razbije o obalu,
{8900}{9000}da bi se na dnu sakrile sve laži,|a na površinu izvukla samo najèišæa ljubav.
{9000}{9100}Teško je opisati|kako treba voditi ljubav sa ženom.
{9120}{9200}Najbliže bi bilo kao sviranje|rijetkog glazbenog instrumenta.
{9230}{9280}Pitam se...
{9300}{9400}Da li Stradivarijeva violina osjeæa isto ushiæenje|kao i violinist,
{9400}{9500}kada odsvira jedan savršen zvuk iz njenog srca?
{10070}{10200}Svaki pravi ljubavnik zna da je trenutak najveæeg|zadovoljstva tek poslije davno završene ekstaze.
{10200}{10300}I da tada u svojoj ruci drži lijep,|potpuno procvao cvijet
{10430}{10500}Oprosti što kasnim, srce.|Bilo je neizbježno.
{10580}{10640}Nadam se da ti nije bilo dosadno.
{10880}{10960}E... sada je vrijeme da umrem.
{11840}{11900}-Zdravo, Jack.|-Kako si?
{11940}{12000}-Ja sam...|-Ti si nabacio koji kilogram.
{12000}{12100}A, što æeš. Vidiš da ti i ja kupujemo u istoj pekari.
{12150}{12250}Oprosti što sam te zvao ovamo|ali ovo može riješiti samo Superpsihiæ.
{12350}{12420}-Što æe mu kostim?|-On je Don Juan.
{12420}{12600}Želi slavno okonèati svoj život.|Hoæe da mu pošaljemo najboljeg maèevalaca,
{12600}{12800}i to po moguænosti Don Francisca de Silvu da se bori s njim.
{12800}{12850}-On je to stvarno rekao?|-Upravo tako.
{13050}{13130}-Kako se ulazi u ovo?|-Na ovu stranu.
{13800}{13880}Gdje je Don Francisco de Silva?|Neæu se boriti ni sa kim drugim.
{13900}{13960}-Hm...|-Gdje je?
{13960}{14140}Don Francisco de Silva je otputovao|na Mallorcu za vikend,
{14140}{14230}ali ja sam njegov ujak,|Don Octavio del Flores.
{14230}{14350}To mi uopæe ne odgovara.|Ja moram umrijeti od ruke Don Francisca.
{14350}{14400}Ja sam Don Juan DeMarco.
{14400}{14460}Ti? Ti si ONAJ Don Juan?
{14460}{14500}Toèno.
{14500}{14700}Zašto, pored svih tih tih uspjeha,|veliki Don Juan želi okonèati svoj život?
{14700}{14880}-Zato što nemam više za što živjeti.|-Baš nijednu stvar?
{14920}{15100}Da. Jer mi je Dona Ana sve u životu.|-Njeno ime je Donna Ana.
{15120}{15180}Sada razumjete zašto moram umrijeti.
{15230}{15330}Ja samo zahtijevam da to bude od ruke Don Francisca,
{15330}{15430}jer želim umrijeti slavno od ruke|dobrog protivnika.
{15430}{15600}Don Juane, ta žena je posebna.|Želio bih èuti nešto više o njoj.
{15700}{15950}Da li si ikada sreo ženu koja te inspirira|da voliš, dok ti nije svako èulo ispunjeno njom,
{15950}{16150}udišeš je, osjeæaš njen okus,|vidiš svoju neroðenu djecu u njenim oèima,
{16150}{16250}i znaš da je tvoje srce napokon našlo dom.
{16250}{16330}Tvoj život poèinje s njom,|a bez nje æe sigurno završiti.
{16470}{16600}Nikada nisam sumnjao da gubitak takve ljubavi|može biti jako bolan ali....
{16600}{16780}Zašto gubiti nadu u život, zašto gubiti sve?|Ne smiješ zaboraviti moj prijatelju,
{16780}{16990}da je moæ tvoje ljubavi, moæ ljubavi Don Juana|vjeèna i nikada ti neæe biti uskraæena.
{17120}{17260}Isprièavam se...|zbog svog neèovjeènog ispada, Don Octavio.
{17450}{17500}Molim te...
{17550}{17600}Prihvaæam.
{18350}{18700}Bijelac, star 21 godinu, doveden na 10-dnevno promatranje,
{18550}{18700}poslije samoubilaèkog poteza|koji je bio posljedica prekida veze,
{18700}{18900}pacijent nema prethodnih pokušaja samoubojstva,|nikada nije bio na lijeèenju,
{18900}{19100}potpuno je èist, škola, zatvor, majka, otac, ništa...
{19100}{19220}A deèko je luði od dva luðaka u baèvi.
{19220}{19290}Sklon je teškim iluzijama i vjeruje da je netko drugi.
{19320}{19380}Da li je to netko koga poznajemo?
{19380}{19420}On je Don Juan.
{19505}{19555}Dobro... dobro... smirite se.
{19555}{19600}Ne šalim se.
{19730}{19800}Tko ga želi?
{19880}{19900}Ja æu.
{19900}{19950}Èekaj... èekaj malo...
{19980}{20040}Zar ti ne ideš u mirovinu?
{20050}{20120}Naravno da idem,|ali to je za tek nekoliko mjeseci.
{20150}{20240}Kako si mi opisao, ovo izgleda kao jedan|od onih dugaèkih sluèajeva,
{20240}{20320}i zato æu ga dati Billu. Imaš li vremena?
{20490}{20670}Hm... prièekaj samo sekundu... bez uvrede, ali|ja bih volio da detaljnije poprièamo kasnije.
{20670}{20720}Veselim se tome.
{20770}{20820}Hoæu ovog klinca.
{20820}{20880}Budi razuman, Jack, ti odlaziš za 10 dana.
{20880}{20930}Pa, kao i on.
{20930}{21080}Ne, ne, ne, ovakav pacijent s ovakvim|problemima se ne lijeèi za tjedan i pol.
{21080}{21200}Rok æe proæi,|on æe biti primljen i svejedno æe otiæi Billu.
{21200}{21270}A da se sve ovo dogaða prije godinu dana|i ja ti kažem da æu ovog klinca za 10 dana izlijeèiti
{21270}{21340}i izvuæi odavde u to ne bi bilo uopæe sumnje?
{21340}{21380}Vjerojarno bi bilo tako.
{21380}{21460}Što znaèi da si ga iz nekog drugog razloga dao Billu?
{21460}{21500}O... Jack...
{21500}{21580}Ti ovako po brojevima radiš veæ mjesecima i ti to znaš,
{21580}{21700}Istrošio si se. Zato si i tražio da odeš u prijevremenu mirovinu.
{21700}{21850}Zato, molim te Jack, ne èini mi život težim nego što je.
{21850}{21950}Koliko se dugo znamo, 25 godina, i vjeèito je ovako,
{21950}{22100}za svo to vrijeme ti si prokleto najbolji lijeènik|koje je ovo mjesto ikada vidjelo. Najbolji.|Svi to znaju.
{22100}{22250}Ali sada je vrijeme da se ide dalje... prièaj, kuda ideš?|Piramide? Prekrasno. Pijesak, plavo nebo...
{22300}{22380}Trebao bi vidjeti svoje lice.
{22380}{22500}Jack. Dat æu ga Billu.
{22550}{22700}Ovaj klinac æe igrati flamenco na njegovoj glavi|dok mu ona ne poène izgledati kao tortilla.|I to u tvojoj smjeni.
{22900}{23100}Da li bi...|Da li bi mi htio isprièati zašto si se htio ubiti?
{23120}{23220}Ti želiš da ti Don Juan DeMarco,|najveæi svjetski ljubavnik, prièa...
{23220}{23300}Što ti znaš o velikoj ljubavi?
{23400}{23530}Da li si ikada volio ženu dok mlijeko ne procuri iz nje,
{23580}{23720}jer je upravo rodila pravu ljubav.
{23770}{23920}Da li si ikada okusio ženu,|dok ne povjeruje da može biti zadovoljena...
{23920}{24080}time što æeš joj pojesti jezik|i proždirati cijelu...
{24080}{24200}Da li si ikada volio ženu tako kompletno|da tvoj glas tjera njeno tijelo
{24200}{24350}da zadrhti i izazove neviðenu reakciju,|takvu da je samo njen jecaj može osloboditi.
{24500}{24560}-Gdje je Don Octavio de Flores?|-Tko?
{24560}{24620}-Tko?|-Domaæin ove vile?
{24690}{24820}Via? Via? -Via. -Via.
{24820}{24980}Vila? -Da, Via. -Vila. -Via.|(igra rijeèi: via=preko, villa=vila)
{25050}{25220}-Gdje je Don Octavio?|-Misliš dr. Mickler?
{25220}{25300}Tko?
{25360}{25600}-Zašto misliš da je dr. Mickler Don Octavio de Flores?|-Zašto ti misliš da je Don Octavio de Flores dr. Mickler?
{25800}{25900}-Hej, bok, Billie... Kako je?|-Don Octavio de Flores....
{25900}{26000}-Na usluzi...|-Rekao si mu da si Don Octavio de Flores?
{26000}{26100}-Isuse.|-Rekao si pacijentu u zabludi da si plemiæ iz 17. stoljeæa?
{26100}{26200}Cijela ideja se sastojala u tome|da ga uvedem u `kabao`. Je li tako?
{26200}{26270}-Sada je tvoj, Done.|-Èekaj, èekaj malo...
{26270}{26370}-Da li si to rekao Paulu?|-Možeš se kladiti u to.
{26370}{26520}-I što je rekao on na to?|-Citiram: Jack ga je pokvario, neka ga on i popravi.
{26750}{26850}Vrlo ljubazno od vas da mi pokažete put.
{27090}{27250}Dr.Mickler... Dr. Mickler, dovela sam g. Juana na dogovoreno...
{27300}{27420}-Hvala, Gloria.|-Mogu se vratiti na kraju radnog vremena i vratiti ga nazad.
{27420}{27500}-Ne... Ne... To uopæe neæe biti potrebno.|-Nije mi problem.
{27500}{27580}Za nekih sat vremena æu prolaziti pored ovih vrata i...
{27580}{27650}Ne, hvala ti puno.|-Imam i pauzu koja samo što nije.
{27650}{27700}Hvala ti.
{27700}{27770}Što radiš ti ovim djevojkama?
{27850}{27950}Tvoji ljudi su mi uzeli masku, Don Octavio.|Oni nemaju prava na to.
{27950}{28150}Ja nikada ne skidam svoju masku u javnosti.|Da li razumjete posljedice tog postupka?
{28150}{28210}Ne u potpunosti, ali..
{28210}{28260}Ja æu biti proklet.
{28260}{28330}Razumijem da to može biti uznemirujuæe.
{28430}{28540}Zamisli da tebi skinu ovu masku koju nosiš.
{28580}{28700}Maske mogu biti vrlo nezgodne.|Koliko ti nosiš svoju?
{28700}{28770}Od svoje šesnaeste.
{28770}{28900}Stavio sam masku na lice i|zarekao se da je neæu nikada skinuti,
{28900}{29000}na dan kada sam se oprostio od majke,|prelijepe Done...
{29000}{29190}Imam neke pilule. Volio bih da ih uzmeš.|Mislim da bi ti pomogle.
{29190}{29400}Pilule æe zaustaviti iluzije?|Onda se bojim da ove pilule moramo uzeti zajedno.
{29400}{29580}-Jer si i ti u teškoj zabludi.|-A u kojoj to?
{29580}{29700}Imaš neku fantaziju da si taj dr. Mickler.|Ja sam vrlo razoèaran tobom, Don Octavio.
{29700}{29780}Vrlo razoèaran.
{29830}{29950}Evo u èemu je stvar. Oni te mogu natjerati da uzmeš|ljekove. Takav je zakon.
{29950}{30140}Ti si ovdje na 10-dnevnom promatranju,|i za tih 10 dana oni mogu raditi što god hoæe.
{30140}{30220}Nisam u zabludi. Ja jesam Don Juan.
{30220}{30380}Nemoj me lijeèiti 10 dana|i dokazat æu ti da sam u pravu.
{30380}{30460}A što ako ti ne povjerujem da si Don Juan?
{30620}{30750}Onda æu uzeti tvoje lijekove|i možete me zadržati koliko hoæete.
{30850}{30980}Da li smo se dogovorili?|Da li imam 10 dana da ti isprièam svoju prièu?
{31150}{31280}Vrlo dobro. Roðen sam u Meksiku.
{31800}{31920}Postalo je oèigledno još u najranijem dobu|da sam drugaèiji od ostalih.
{32350}{32480}Poèinjao sam shvaæati da nisam|kao ostali djeèaci.
{32500}{32600}Kada sam napunio 10, toliko sam privlaèio djevojèice|da je to dosta zabrinjavalo majku.
{32600}{32800}Tako me upoznala s Bogom,|moleæi se da æe me on spasiti prije nego što bude kasno.
{32800}{32950}Ali je, oèigledno, bilo prekasno.
{33050}{33130}Lekcije koje sam nauèio u crkvi|nisu bile bezvrijedne.
{33130}{33320}Dok sam napunio 12-tu, nauèio|sam dijeliti svoj blagoslov s manje sretnima.
{33890}{34000}Jedne noæi, gledao sam Donu Querida prije spavanja.|Primijetio sam po prvi puta kako žensko donje rublje
{34000}{34200}jedva dodiruje njenu kožu.|Kako se kreæe u ritmu njenih pokreta.
{34200}{34360}Kako svila lebdi nad njenim tijelom,|oblikujuæi joj tijelo, kao anðeoska krila.
{34360}{34500}Shvatio sam kako žena treba biti dodirivana.
{34550}{34620}Da li si ti Talijan, Meksikanac ili Španjolac?
{34620}{34700}To je sve što mi imaš za reæi?|Želiš znati moju nacionalnost.
{34700}{35000}Tvoje ime, DeMarco, to je talijansko, odrastao si| u Meksiku, a govoriš engleski sa kastiljanskim naglaskom.
{35060}{35210}Moj naglasak je obojen uslijed brojnih putovanja.|Vrlo dobro, odgovorit æu na tvoje pitanje.
{35210}{35350}Odrastao sam u Meksiku, otac mi je roðen u Queensu i njegovo ime je|Tony DeMarco. On je bio Talijan, kralj plesa u Astoriji.
{35350}{35500}Tvoj otac je bio kralj plesa ovdje, u New Yorku u Astoriji?
{35650}{35770}Moj otac je došao u Meksiko|raditi za jednu farmaceutsku kompaniju.
{35770}{35900}Samo što je izašao iz autobusa i krenuo|prema obližnjoj haciendi da iznajmi sobu,
{35900}{36050}ugledao je moju majku. Oba njena roditelja je pokosila|bolest. Ona je bila mlada i jaka pa je preživjela.
{36050}{36120}Preuzela je njihovu plantažu.
{36120}{36350}Sjedeæi pod suncem na verandi obasjana|svjetlošæu, djelovala je nestvarno. Bila je prelijepa.
{36350}{36500}Moj otac nije mogao vjerovati svojim oèima.|Bila je to ljubav na prvi pogled.
{37400}{37520}Držali su se na mjeseèini.|Ljubili i dodirivali. Plesali do jutra.
{37520}{37640}Mislio sam da si rekao da|je tvoja majka stajala pod suncem?
{37640}{37780}To je tatina verzija.|Mamina se odigravala noæu.
{37780}{38000}Uzeli su se sljedeæi tjedan. Moj otac je uzeo ime Don Antonio,|postao je šef i preuzeo plantažu.
{38000}{38080}Njihova ljubav bila je kao savršena molitva.
{38080}{38220}Èak i sam Bog morao ju je priznati.|Ja sam roðen toèno 9 mjeseci kasnije.
{38320}{38400}I tada mu ja kažem:
{38400}{38600}Ti si prtljao po našem autu šest dana|i uopæe nemaš predodžbu zašto hladnjak ostaje pokvaren.
{38600}{38730}Auto æemo uzeti isto tako pokvarena kao kada|smo ga i dovezli, osim što sada tražiš da ti platimo,
{38730}{38850}430$ za vrijeme koje ti je bilo potrebno da|shvatiš kako ne znaš što je s automobilom.
{38850}{38920}I znaš što mi je rekao?
{38920}{39100}Možemo i dalje tražiti, ali|æe nas koštati 65$ sat.
{39100}{39220}Jack. Jack!
{39280}{39400}O! Ne znam... Plati mu.|-Da mu platim?
{39500}{39600}-Kuda si odlutao?|-U Meksiko.
{40270}{40350}-Jack, tražio sam te.|-Ovo je za tebe. Isprièavam se, sestro.
{40350}{40420}-Zašto mi daješ tulipane?|-Grace. Izvoli.
{40420}{40600}-Hoæu prièati s tobom.|-Klinac je fantastièan.
{40600}{40750}Drago mi je što ti ispunjava oèekivanja. Hoæu da poprièamo...|-Znam da hoæeš...
{40750}{40850}Kada misliš poèeti sa lijeèenjem?|On je ovdje veæ 2 dana.
{40850}{40950}Imaš mu namjeru davati lijekove?|-Hm... ne znam.
{40950}{41080}Èekaj. On je pacijent u zabludi. Lijekovi?
{41080}{41200}Ako mu dam lijekove, nikada neæu uæi u|taj njegov svijet, a on je èaroban.
{41220}{41320}OK. Bez lijekova.|Privremeno, ali ako mi uèiniš jednu stvar...
{41380}{41430}A to je?
{41430}{41600}Trenutno Don Juan ima ometajuæi utjecaj|na žensko osoblje. Mislim, službeno u njegovoj haciendi
{41600}{41760}ima više sestara na valiumu nego pacijenata.|Uèini nešto oko toga.
{41760}{41800}Nema problema, veæ sam se pobrinuo za to.
{41820}{41900}-Hajdemo, èovjeèe, vrijeme je za tvog psihiæa.|-Tko si ti?
{41900}{42050}Ja sam tvoja nova sestra, g. Compton.|Ali ti me možeš zvati Rocco, Casanova.
{42050}{42120}Ja nisam Casanova. Ja sam Don Juan.
{42120}{42200}Da. Sigurno. Hajde, kreæi.
{42750}{42850}Imam danas za tebe pravu poslasticu.
{42920}{42980}Ovdje su joj bradavice...
{42980}{43100}Njen ljubavnik joj ljubi obrise stražnjice|i upravo prelazi na butine....
{43350}{43400}A da mi prijeðemo na nešto drugo?
{43400}{43450}Što imaš na umu?
{43450}{43500}Prièati o tome tko sam ja.
{43500}{43550}-Znam tko si.|-Tko?
{43550}{43650}Ti si Don Octavio de Flores,|ujak Don Francisca de Silve.
{43650}{43720}I gdje smo mi?
{43800}{43900}Pa, nisam nigdje vidio isprave,|ali pretpostavljam da smo u tvojoj vili.
{43950}{44150}Što bi rekao nekome ako ti on kaže da je ovo psihijatrijska|bolnica, da si ti pacijent, a ja psihijatar?
{44150}{44300}Rekao bih mu da ima ogranièen i nemaštovit pogled|na trenutnu situaciju.
{44300}{44420}Gle. Ti želiš znati da li sam ja|svjestan da je ovo mentalna ustanova.
{44420}{44460}Da, razumijem to.
{44460}{44580}Ali, kako onda mogu reæi da si ti don Octavio,|a ja gost u tvojoj vili. Toèno?
{44580}{44620}Toèno.
{44620}{44760}Jer vidim preko granice vidljivosti oka.|Naravno, postoje oni koji se ne slažu sa mnom, to je istina.
{44760}{44900}Kao kada kažem da su sve moje žene oèaravajuæe|ljepotice, oni to osporavaju.
{44900}{45140}"Ovoj je nos velik, kukovi na ovoj su preširoki,|grudi na treæoj su vrlo male."
{45160}{45300}Ja te žene vidim onakvima kakve stvarno jesu.
{45300}{45500}Velièanstvene... spektakularne... nesavršene,|zato što nisam ogranièen svojim oèima.
{45500}{45700}Žene na mene reagiraju prirodno zato što ja tražim|ljepotu koja se nalazi u njima dok sve drugo ne postane sporedno.
{45700}{45860}i onda ne mogu odoljeti želji da puste|tu ljepotu i obaviju me njome.
{45930}{46080}Da odgovorim na tvoje pitanje, ja vidim da ovo|velièanstveno zdanje predstavlja tvoj dom, tvoju vilu,
{46080}{46450}a što se tièe tebe, ti si veliki ljubavnik kao i ja,|iako si možda izgubio svoj put, kao i naglasak.
{46460}{46550}-Da nastavim?|-Da.
{46550}{46620}Vrlo dobro. Nazad u Meksiko.
{46700}{46820}Moja majka, blagoslovljena bila, nije odustajala lako.
{46820}{46940}U mojoj 16-oj po posljednji put mi je pokušala|utisnuti kršæanske vrijednosti. Tako što mi je našla mentora.
{46950}{47050}Majèin sud je napravio propust.
{47050}{47300}Dona Julia je imala 23 godine i muža.|Odana i vjerna žena Don Alfonza,
{47300}{47520}èovjeka od 50 godina. Nije bila tajna da bi njoj|bilo bolje s dvojicom mladiæa od 25.
{47760}{47860}Osjeæaji su me obuzimali dan i noæ.
{47860}{48090}Vjera u sebe me muèila. Goruæa rana zajedno s blagoslovom....
{48090}{48160}Ali što je to bilo?
{48160}{48300}-Nisi imao pojma što je to?|-Pretpostavljao sam, ali...
{48350}{48500}Moj otac, razumijevajuæi da je moja muškost na|pomolu, uèio me kako koristiti svoj maè.
{48500}{48620}Tada je bilo puno maèevanja, kada si odrastao?
{48620}{48800}To je bio mali i izolirani gradiæ|koji se opirao modernoj tehnologiji.
{49190}{49370}Primjetio sam da je osmijeh na njenom licu nestao,|ali ga je zamijenila tuga koja je bila slaða od osmijeha.
{49370}{49550}Osjetio sam da se u njoj vodi borba.|A ni moja situacija nije bila ništa lakša.
{49660}{49720}Samo mi je ona bila u mislima.
{49720}{49860}Da ne bih poludio, okrenuo sam se meditaciji.
{49860}{50110}Razmišljao sam o znaèaju istine, životu, bogu.
{50110}{50260}Razmišljao sam o svom dnevnom rasporedu,|a onda sam se sjetio njenih oèiju.
{51660}{51800}Odjednom sam shvatio kako je žensko tijelo naèinjeno
{51800}{51880}kako muškarèevo tijelo reagira na njega,
{51880}{52050}vatra koja gori u mojim preponama, velika želja da se spojimo u jedno,
{52100}{52300}sve je to došlo zajedno u jednom briljantnom bljesku.
{52650}{52800}Postoje samo 4 životna pitanja: Što je sveto?
{52800}{52950}Od èega je duh sazdan?|Za što vrijedi živjeti?
{52950}{53060}Za što vrijedi umreti?
{53060}{53200}Odgovor na sva 4 je isti:samo ljubav.
{53333}{53420}Dona Julia je bila moja prva ljubav.
{53450}{53600}Pa... naše vrijeme je isteklo..
{53720}{53800}Hej, a maska....
{53843}{53980}Opsesivno kompulsivni poremeæaj sa erotskim osobinama.
{54000}{54120}Potvrðen poremeæaj o stvarnosti.
{55573}{55670}-Pretpostavljam da hoæeš gore.|-Odakle ta ideja?
{55760}{55840}Zašto slušaš operu? Mrzim operu.
{55840}{55900}Imaš jako lijepe oèi.
{56020}{56100}Moram gore.
{56150}{56250}Moram popiti kalcij da mi se kosti ne polome u komadiæe,
{56250}{56500}aspirin da mi srce ne zakašlje, Metamucil da ne dobijem prehladu i rak,
{56380}{56500}i naravno, estrogen da uvjerim tijelo da mi je 23.
{56550}{56590}Doði ovamo.
{57300}{57360}Što radiš, dovraga, tamo?
{57900}{57960}-Provjeravaš mozak?|-Ne.
{58000}{58200}Razmišljao sam o našoj adolescenciji.|Nije ostalo više bojišta za nas.
{58250}{58300}Osjeæam da smo predali živote navici.
{58380}{58530}Što se dogodilo sa svom onom vatrom|koja nam je obasjavala put?
{58600}{58800}Znaš da te vatre donose puno nevolja,|nismo ih više u stanju kontrolirati.
{58800}{59000}Izlete nam iz ruku, sagorjevaju dosta energije i|onda iznenada umre.
{59000}{59150}Da ti kažem nešto: to je sranje zato...
{59040}{59100}-Ne, nije.|-Je.
{59100}{59220}Dobar, stabilan, topao sjaj je dovoljan|da odradi posao.
{59220}{59270}Za duge staze...
{59270}{59400}Bez vatre nema vruæine,|bez vruæine nema života.
{59400}{59480}-To je jednadžba...|-Ne.
{59580}{59700}Da li iz ovoga mogu zakljuèiti da se ti|neæeš tako lako povuæi u mirovinu?
{59700}{59920}Prokleto si u pravu. Zbog èega da odem u mirovinu? Zbog života?
{59800}{59880}Slušaj me, tek smo poèeli.
{59880}{60000}Ovo je 12 runda, a ti hoæeš pobjeæi.
{60000}{60150}Što se dogaða? Èudan si u zadnje vrijeme.
{60150}{60300}Moraš mi reæi, Jack.
{60300}{60480}Uopæe nije tajna...|Ne znam... Osjeæam se...
{60480}{60600}Lijeèim jednog klinca koji misli da je Don Juan.
{60600}{60690}Ima kostim, masku, maè...
{60700}{60820}Tko je on u stvarnosti?|-Ne znam.
{60850}{61000}On dopire do mene.
{61330}{61420}Prokletstvo. Stvarno si dobar komad.
{61520}{61680}-Znam.|-Ovo æe biti dobro.
{62100}{62220}U svakom trenutku smo letjeli jedno|drugom u zagrljaj.
{62220}{62400}Vrijeme je stalo za ta 4 mjeseca.|Nije postojala noæ ni dan. Samo moja i njena ljubav.
{62400}{62500}A što se tièe Don Alfonza, on je toliko|vremena trošio sreðujuæi
{62500}{62600}poslovne detalje, da sam praktièki živio u njihovoj kuæi.
{62600}{62720}Zaista sam vjerovao da sam našao vjeèni raj.
{62720}{62790}Dok jedne noæi...
{62790}{62860}Dona Julia, moja slatka...
{62930}{63080}Gdje je? Gdje si ga sakrila?
{63080}{63160}Za ime Božje, Don Alfonzo, što si pio?
{63160}{63240}Kako možeš sumnjati u mene?
{63240}{63000}Mene, zbog èije nevjere bi me ubili?
{63300}{63400}Da, traži, traži, uvreda za uvredu.
{63400}{63500}Nezahvalnièe. Da li si sad zadovoljan?
{63500}{63580}Ja æu ubiti tog èovjeka.
{63620}{63700}Moj maè... gdje je moj maè?
{63830}{63880}On æe me ubiti.
{64030}{64100}Brzo, izaði kroz vrt.
{64330}{64400}Ubit æu te!
{64640}{64800}To je bilo zadnji put da sam vidio svog mentora,|prelijepu Donu Juliu.
{64870}{65000}U velikoj tuzi je otišla te noæi|i više je nikada nisam vidio.
{65000}{65160}Don Alfonzo je bio ponižen jer ga je|namagarèio 16-godišnji djeèak.
{65160}{65320}Da bi uzvratio istom mjerom, objavio je|kako su on i moja majka u dugogodišnjoj vezi.
{65320}{65390}to je, naravno, bila soèna laž.
{65450}{65540}Moj otac je brzo reagirao|i stao u obranu èasti moje majke.
{65640}{65720}Nisam sumnjao da æe moj otac|lako pobjediti
{65760}{65860}sve do jedne fatalne pogreške.
{65860}{65980}Pogledao je u oèi moje majke... i bilo je prekasno.
{65980}{66080}Ubio si mi oca, sada æeš morati mene.
{66560}{66620}O, Bože, izgubit æu ih obojicu!
{67990}{68080}Oprosti mi, oèe.
{68140}{68220}Naravno da ti opraštam.
{68260}{68380}Ti si moj sin.
{68980}{69180}I tako je moj otac, veliki maèevalac|Don Antonio, umro na rukama moje majke
{69180}{69300}dok su njene suze padale na njega.
{69330}{69400}Sada svoju sramotu nosim zauvijek.
{69400}{69480}Stavljam masku na lice,
{69500}{69580}i nikada je ne skidam pred drugima.
{69850}{69930}Otac me napustio dosta rano,
{69930}{70000}tako da nikada nisam imao priliku.