{1}{1}25.000
{918}{1022}{C:$0000FF}{y:ib} OŠTRICA |{C:$FF0000}{y:b} LUDILA 
{2958}{3035}Prema istinitoj prièi | "Postaja u divljini" od A.M.
{4086}{4237}Koji je to vrag? | - Je li ovo zatvor? - Da.
{4319}{4426}George! | - Tko je George?
{4432}{4556}George! | - Što hoæeš?
{4591}{4707}George! | - Što hoæeš?
{4713}{4759}Dolazi ovamo! | - George.
{4765}{4817}Uèinila sam to. | - Što si uèinila?
{4822}{4916}Ubila sam ga, svoga muža. | To sam bila ja.
{4922}{5070}Idem po g. Mullen-a. | Ostani ovdje.
{5073}{5136}George!
{5183}{5359}Ja sam Marie. Ja nisam George.
{5425}{5494}Ona je uznemirena, gospodine. | Napeta.
{5499}{5584}Ponaša se kao luðakinja.
{5590}{5631}Zašto je ne pošaljete u crkvu?
{5639}{5755}Veleèasnog nema u utvrdi, | gospodine.
{5760}{5826}Ovdje je pretoplo, Donnely. | Ovo je zatvor, a ne jebeni motel.
{5832}{5895}Da, gospodine.
{5901}{5991}Veliš da si ubila èovjeka, | svoga muža.
{5997}{6063}Kako se zoveš?
{6066}{6192}Pitanje je jednostavno. | Tvoje ime.
{6197}{6230}Može govoriti.
{6236}{6387}Ova djevojka govori francuski.
{6418}{6505}Pazite gospodine. | - Baš je neobièna.
{6511}{6563}Evo, sjedni.
{6569}{6641}Hajde.
{6676}{6789}Puna je ogrebotina. | - Podivljala je, gospodine.
{6794}{6852}Ispuni obrasce, Donnely. | Zatvori je.
{6857}{6916}Izjavu æu uzeti sutra.
{6921}{7091}Da joj dam nešto za jesti, | gospodine? - Kako hoæeš.
{7253}{7322}Ovo vrijeme je došlo | iz samog pakla, gospodièna.
{7330}{7487}Radije bih da se | smrznem nego da visim.
{7572}{7672}Dolina Crvene rijeke | 1851
{7688}{7729}Zapisnik g. Henry Mullen-a,
{7735}{7790}upravitelja Suda za prekršaje, | Hudson Bay Company...
{7798}{7831}15 studeni
{7839}{7872}Zbog odsutnosti | guvernera Simpsona...
{7878}{7944}meni je dodijeljeno da ispitam | èudnu mladu ženu koja se sinoæ
{7949}{8037}pojavila u utvrdi. Buduæi da | nemam iskustva u ovim stvarima
{8043}{8117}zamolio sam | dr. Jenkinsa da mi asistira.
{8122}{8222}Prije svega, | reci mi svoje ime.
{8241}{8312}Onda dobro, | tko je George, tvoj muž?
{8320}{8411}Možda se sklonio | sa nekim mještanima. - I nestao.
{8422}{8483}Uèinila sam nešto strašno.
{8486}{8546}Da, rekla si da si ubila muža.
{8551}{8628}Ne, i George je! Bože moj!
{8634}{8722}Kako si ga ubila?
{8728}{8782}Kamenom.
{8788}{8851}Èula sam | kada mu je lubanja pukla.
{8857}{8945}Gdje se to desilo? | - Kod kuæe.
{8951}{9027}Gradili smo kamin. | Imali smo puno kamenja.
{9033}{9143}Zašto si ga ubila? | - Zato jer sam željela.
{9149}{9217}Željela sam ubiti muža, | pa sam to i uèinila!
{9222}{9278}Još nam nisi rekla svoje ime. | - Annie.
{9286}{9349}A muževo? - Simon.
{9355}{9434}A tko je George?
{9440}{9476}Njegov brat.
{9481}{9542}Sada je možete pregledati, | dr. Jenkins. - Ne!
{9547}{9607}Iskreno, | radije bih da se prvo opere.
{9613}{9709}Bi li to voljela? | Ugodnu toplu kupku?
{9715}{9781}Super. Odvedi je u kuæu, Ruth.
{9786}{9891}To nije u prirodi žene. | - Tamo vani usred nièega...
{9896}{9946}...odvojeni od civilizacije...
{9952}{10001}...ljudi uèine | ne vjerojatne stvari.
{10006}{10100}Istina, istina. Ali nitko | nije prijavljen kao nestao.
{10105}{10199}Nitko ne zna | što se tamo vani dogaða.
{10204}{10278}Vjerojatno se izgubila.
{10287}{10342}Što misliš koliko ima godina?
{10347}{10430}18... 19. Teško je reæi.
{10438}{10548}Morat æemo je bolje pogledati.
{10554}{10611}Što je sad to?
{10617}{10677}Ljubièasto.
{10683}{10801}Da, ja volim ljubièasto.
{10878}{10961}Tvoja knjiga?
{11024}{11117}Stavit æu je ovamo, može?
{11123}{11208}Nagorjela, ha?
{11282}{11345}Dobro.
{11381}{11472}Uði sada.
{11483}{11620}Ja idem po još vode.
{12616}{12674}Nemoj iæi sa njime, Annie.
{12679}{12762}Annie, izlazi van! | Hajde, izlazi van!
{12767}{12897}Annie, hajde! Hajde! Požuri!
{13012}{13108}Ne razumijem. Rekla sam joj da | završi sa kupanjem, da se obuèe.
{13114}{13185}Gðice Craswell, ne znam! | Znala je da on èeka!
{13193}{13279}U redu, neka | izabere neku drugu djevojku.
{13284}{13348}Želim da izabere mene. | - Nemoj iæi sa njime, Annie!
{13353}{13411}Ja znam, sanjala sam!
{13416}{13468}Ja imam svoj san, Sadie.
{13474}{13526}Ja želim djecu, dom i muža!
{13546}{13589}Jednom sam imala dijete.
{13595}{13661}Pobacila sam zbog infekcije, | bilo je veliko poput štakora!
{13666}{13716}Odnijeli su ga i dali psima!
{13722}{13853}To je laž! | - Istina je! Skoro sam umrla!
{13961}{14107}Ne zanima me zna li pjevati. | Treba mi žena koja može raditi.
{14214}{14324}Evo je. - Strašno je sitna. | - Jaka je i spremna.
{14332}{14470}Francuskinja je, | ali èita i piše engleski.
{14475}{14494}Nepotrebno.
{14503}{14566}Može sašiti bilo što. | Odijela, košulje.
{14574}{14668}Dobro je poduèena.
{14695}{14778}Zadovoljit æe.
{14816}{14929}Neæete požaliti, gospodine.
{15102}{15223}Želiš se utopiti?
{15358}{15407}Škoti rade dobar whiskey.
{15413}{15490}Barem su u neèemu dobri.
{15495}{15542}Evo je, gospodine.
{15551}{15657}Obukla sam joj | svoju radnu haljinu.
{15663}{15693}Hvala Ruth.
{15699}{15789}Ovo sam našla. Nagorjela je.
{15795}{15853}Je li tamo bio požar? | - Ne želi govoriti, gospodine.
{15858}{15905}Pogrešno je | uèiti djevojke da èitaju.
{15913}{16029}Slažem se. - Hvala Ruth.
{16034}{16136}Hajde. Sjedni na stol, | molim te, gospoðo...
{16141}{16194}Simon. - Simon. Dobro.
{16199}{16241}Sjedni na stol, | poèet æemo sa pregledom.
{16246}{16284}Prepustit æu to tebi. Hvala.
{16291}{16331}Hajde. Doði i sjedni. | Hoæeš li doæi i sjesti?
{16337}{16397}Doði ovamo i sjedni!
{16406}{16511}K vragu i vezat æu te, | ako bude potrebno!
{16518}{16628}Samo je drži, g. Mullen. | Molim te.
{16631}{16703}Hvala. Neæe dugo trajati.
{16708}{16791}Ja pregledam svakoga | tko doðe u zatvor, gðo Simon.
{16796}{16884}To je za tvoje dobro.
{16887}{16934}Kako spavaš?
{16939}{16999}Dobro.
{17005}{17066}Je li ti se žena javila?
{17071}{17132}Tu se nema što reæi. | Njena odluka je jasna.
{17137}{17181}Neæe se vraæati.
{17189}{17247}A ti? Jesi li donio odluku?
{17255}{17360}Donesem puno odluka, | a onda se predomislim.
{17365}{17445}Oh, ozeblina. Mora da boli.
{17451}{17533}Da. Bilo joj je teško sa ovim.
{17536}{17602}Puno masnica i ogrebotina.
{17610}{17731}Da, vidi ovo. Otisak | ugriza ovdje na njenoj ruci.
{17736}{17822}Ljudski? - Da.
{17827}{17896}Dobro, sada lezi. Samo lezi.
{17905}{17957}Hajde.
{17962}{18042}Raširi noge, molim te.
{18050}{18105}Raširi noge. - Budi mirna!
{18108}{18226}Nitko te neæe povrijediti.
{18234}{18295}Dobro.
{18358}{18427}Jako dobro.
{18432}{18515}Ako zanemarimo oèito, | vrlo je jaka i zdrava.
{18520}{18600}Brak je konzumiran, | iako ne na ugodan naèin.
{18609}{18644}Shvaæam.
{18649}{18740}Želim da uzima po žlièicu | ovoga èetiri puta dnevno.
{18746}{18856}Smirit æe joj živ ce. | Pomoæi æe joj da spava.
{18861}{18941}I vjerojatno æe joj | osvježiti sjeæanje. - Nadam se.
{18947}{18974}Ruth, neka se obuèe.
{18982}{19045}Nema što obuæi, gospodine. | Samo rite.
{19051}{19111}Daj joj onda nešto | iz ormara od moje žene.
{19117}{19172}I ostavi knjigu!
{19178}{19307}Doði, obuæi æemo te kao damu.
{19312}{19436}Tvoj prvi sluèaj ubojstva, | g. Mullen.
{19640}{19708}Našla sam ga.
{19714}{19799}Malo je iznošen, | stari radni kaput g. Mullena.
{19805}{19882}Treba ti nešto. | To mjesto je tako hladno.
{19887}{19928}Je li ovo tvoja soba?
{19936}{20082}Ne. Gða Mullen je sav ovaj | namještaj donijela iz Engleske.
{20088}{20154}Ogroman je.
{20159}{20305}Imaš li neke škare? | Konac i iglu?
{20313}{20404}Pitat æu.
{20407}{20476}Umovi vjetra, | kao zimski vjetrokazi...
{20481}{20553}mogu premještati i okretati.
{20558}{20684}Gos. Mullen, puno je drugaèija | otkako sam joj dala taj lijek.
{20690}{20731}Govori. - Super.
{20739}{20833}Želi škare da nešto sašije. | Mislite li da je to sigurno?
{20839}{20979}Da, u redu je Ruth. Hvala.
{20987}{21028}Draga Sadie,
{21034}{21171}Osim neugode jahanja na konju, | nikada nisam bila sretnija.
{21177}{21245}Priroda je velièanstvena.
{21251}{21306}Osjeæam se kao | da mi je život tek poèeo.
{21311}{21380}Sve je novo. Sve je moguæe.
{21386}{21446}Èim se smjestim, | poslati æu po tebe.
{21452}{21501}Možda æeš promijeniti | svoje mišljenje o braku...
{21509}{21655}jer æeš moæi birati slobodne | zgodne muškarce u okrugu.
{21661}{21710}Za sada, Simon ne govori puno.
{21716}{21834}Èini se da mu se jako žuri doma.
{21839}{21930}Što to radiš? | - Pišem o našem putovanju.
{21936}{22070}Uzmi svoga konja. | Slijedi me.
{22401}{22475}Simon!
{22585}{22736}Pokreni se, za ime Boga! | - Ne mogu!
{22805}{22918}Namirnice padaju! | Diži se! Drži ih!
{23063}{23146}Makni deku. - Molim?
{23151}{23212}Želim te vidjeti.
{23218}{23275}Ne ovdje.
{23280}{23366}Zašto ne? Žena si mi.
{23371}{23473}Da, ali... - Ali, što?
{23492}{23575}Smjesti se.
{23591}{23682}Prokleto kamenje!
{24081}{24221}Uèini kako sam ti rekao, | moja djevojko, i shvatit æeš.
{24268}{24433}Raširi noge. - Zašto? Ne!
{25074}{25184}To je malo za jedan dan.
{25189}{25318}Baš nam je bilo dobro.
{25324}{25453}Slijedeæi put æeš sama htjeti.
{25684}{25755}Dobro jutro, Annie.
{25761}{25912}Hoæeš li malo tople zobene kaše? | - George? - Ne.
{25918}{26030}Što si to napravila?
{26036}{26182}Pogledaj ovaj prekrasan rad.
{26187}{26248}Da, jako je lijepo.
{26253}{26336}Gdje si nauèila ovako šivati?
{26341}{26413}U školi. Sve smo uèile.
{26418}{26490}Išla si u školu? - Da.
{26493}{26559}I tvoj muž je išao u školu?
{26564}{26655}Ne, on je došao po mene. | Želio je ženu i odabrao je mene.
{26660}{26718}Shvaæam.
{26724}{26814}Sjedni i ne miješaj se.
{26820}{26930}Gdje je tvoja kuæa, gðo Herron?
{26996}{27081}Ne znam.
{27339}{27416}To je to?
{27491}{27565}George!
{27664}{27744}Simon!
{27752}{27815}Jedi.
{27909}{27983}Slušaj me, gðo Herron.
{27989}{28043}Nema razloga | da mi ne isprièaš sve.
{28049}{28112}Ti si u najgoroj | situaciji koja postoji.
{28118}{28195}Priznala si zloèin zbog kojega | možeš visiti, razumiješ li to?
{28198}{28258}Obješena tamo vani | dok svi gledaju!
{28264}{28365}Prekrivenih oèiju. | Grozna smrt. Ali takav je zakon.
{28371}{28428}Zar te nije briga?
{28434}{28558}Zar ne želiš spasiti život | od takve sudbine?
{28563}{28613}Gdje je bio George | kada je Simon umro?
{28618}{28668}U šumi, radio.
{28676}{28753}Vratio se sa naramkom | dašèica i vidio što se desilo.
{28759}{28828}Gdje je tijelo? - Zakopano.
{28833}{28910}George i ja smo ga zakopali.
{28915}{28962}Ništa nisi napravio!
{28968}{29034}Nisam mogao puno bez konja.
{29039}{29124}Mogao si rabiti ruke.
{29130}{29286}Malo sam nabacivao. | Ali trebala mi je miješalica.
{29325}{29416}Gdje su namirnice? | Ovdje nema nièega.
{29421}{29495}Pitaj nju, | pustila ih je niz rijeku.
{29504}{29584}Zar nisi?
{29683}{29765}Mislila sam da je ovdje kuæa. | Farma, tako je pisalo u pismu.
{29770}{29891}Biti æe. Dvorac.
{29908}{30037}Simon! Što to radiš? | - Ne mogu spavati vani!
{30043}{30117}Neæeš spavati ovdje sa nama.
{30120}{30172}Možemo pregraditi dekom, | napraviti dvije sobe.
{30178}{30239}On neæe spavati ovdje!
{30243}{30310}Spavati æeš u kolibi. | - Ostati æu sa Treeces.
{30318}{30414}Vraga hoæeš.
{30430}{30576}Spremi nešto za jelo dok George | i ja vratimo konja susjedima.
{30582}{30661}Veèeras? Simon, umorna je.
{30667}{30772}Još ništa nije napravila. | - U redu je, volim kuhati.
{30777}{30824}Ima li mesa?
{30829}{30912}Nisam namjestio zamke. | Okolo su tvorovi.
{30917}{30989}Ali ubrao sam nešto malina.
{30994}{31044}Malina? - Da.
{31052}{31129}Kriste.
{31132}{31291}Ima hrane koliko hoæeš | ako ti ne smeta ubijanje.
{31580}{31654}Bilo je kao da sam se | izgubila usred oceana.
{31660}{31872}Osjeæala sam se | tako siæušno ispod toga neba.
{31973}{32053}Henry, veèeras je vjenèanje.
{32061}{32166}Vjerojatno æe biti puno lijepih, | mladih squaws.
{32171}{32212}Nitko te neæe kriviti.
{32218}{32276}Pisao sam svakoj župi, | Katolièkoj i Protestantskoj,
{32284}{32383}u krugu od 40 km. | Netko bi je morao poznavati.
{32389}{32441}Rekla je da je hodala tri dana.
{32446}{32499}Mogla je hodati i u krug.
{32504}{32570}Istina. Rekla je da se | spustila niz rijeku sa zapada.
{32576}{32636}Tamo su uglavnom Škoti.
{32641}{32716}Evo dobre ideje. | Zašto ne dovedemo Annie?
{32721}{32801}Ona bi podigla svaku zabavu. | - Vjerujem da bi.
{32807}{32892}Mullen...
{32897}{32980}Mi ovdje manje više | možemo uèiniti što želimo.
{32985}{33084}Ja idem na zabavu | sa tobom ili bez tebe.
{33090}{33191}Biti æe zabavno.
{33995}{34080}Pa, ja odustajem.
{34085}{34168}Ja mogu odigrati još jednu. | - Vrijeme je za spavanje.
{34173}{34245}Ja se idem oprati.
{34250}{34308}I ti bi se trebao oprati.
{34314}{34380}Zaveži, mladiæu.
{34385}{34542}Pa, pobijedio | sam pet puta za redom.
{34693}{34753}Simon. Ona je jako mlada.
{34759}{34825}Živio sam sa mladima. Ne vole | muškarce koji su prljavi i smrde
{34831}{35034}kao ti. | - Zvuèiš kao curica. Briši odavde
{35161}{35249}Laku noæ, Annie.
{35254}{35342}Laku noæ.
{35977}{36043}Doði ovamo. - Ne!
{36049}{36164}Doði ovamo. - Ne želim!
{36214}{36335}Budi mirna! - Boli me!
{36711}{36846}Ne guraj George, vuci! | - Vuèem!
{36893}{37020}Hajde, curice. | - Ne zovi me tako!
{37355}{37482}Idi i donesi još jedno, curice.
{37559}{37614}Što ti radiš?
{37622}{37734}Diži se i na posao.
{37740}{37801}Hvala.
{37850}{37963}Hej, ovo je dobro! Što je ovo?
{37968}{38034}Isto što i sinoæ i preksinoæ.
{38043}{38180}Ne, ne može biti.
{38499}{38656}Prestani!
{39164}{39297}Za ime Boga, Simon! | Što joj to radiš? - Odbij!
{39305}{39395}Zašto je ozljeðuješ?
{39401}{39464}Simon!
{39503}{39643}Prokletstvo, George.
{39780}{39849}Ti se ne miješaj!
{40622}{40707}Sanjala sam da ležim tamo gdje | cvijeæe raste, sretna u sunèevu
{40713}{40779}sjaju, slušajuæi | kako divlje ptice pjevaju
{40784}{40914}uz kristalnu rijeku što teèe.
{41268}{41332}Oh, to je sve!
{41340}{41447}Vratit æu ti.
{41846}{41970}Annie!
{42000}{42154}Ne. Ne. Uhvatit æu te!
{42250}{42415}Jedna oluja u tom šatoru | i svi æemo biti gotovi!
{42751}{42836}Gos. Mullen je rekao da | se premjesti u veæu æeliju.
{42841}{42926}Ne smeta mi što ne govori puno. | Samo šiva i šiva.
{42932}{43064}Èula sam da pjevaš. To je dobro! | - Imam nešto.
{43070}{43166}Pismo! Ti si ga napisala?
{43174}{43265}To je nešto što bih voljela, | nauèiti pisati.
{43270}{43364}Poslati æeš to za mene?
{43380}{43438}Ovo je William Seller. | Rekla sam ti za njega.
{43443}{43515}Želi da mu sašiješ neke haljine. | - Kostime,
{43520}{43622}za predstavu baziranu na operi.
{43628}{43705}Sigurna si da ona to zna? Ne | mogu priuštiti da mi to pokvari.
{43710}{43771}Naruèio sam materijale izdaleka, | dugo je trebalo da stignu ovamo.
{43776}{43881}Ona je umjetnica. | Pogledaj njen rad.
{43889}{43999}Da, izvrsno je.
{44005}{44090}Ali... - Ali što?
{44118}{44183}Imam par crteža...
{44189}{44247}da te nadahnem.
{44252}{44304}Ovo su mjere za Luciu.
{44310}{44362}Obje haljine su za nju.
{44370}{44425}Je li ti poznata prièa o Luciji?
{44431}{44497}Ne. - To je prekrasna prièa...
{44502}{44566}...o mladoj djevojci | koja se zvala Lucia.
{44574}{44714}Strašno se zaljubila | u mladog muškarca.
{44733}{44786}George!
{44791}{44893}To su Treeces!
{44898}{44972}Dobrodošli!
{44981}{45016}Kriste!
{45025}{45066}Bok, George!
{45074}{45165}Došli smo da vidimo ako želite | doæi k nama u subotu naveèer.
{45170}{45239}Nismo imali prilike | da te pozdravimo, gðo Herron.
{45245}{45300}Mi nemamo vremena za zabavu!
{45305}{45347}Ne obraæajte pažnju na njega, | gðo Treeces.
{45352}{45421}Nadamo se da æeš nam pjevati, | George.
{45426}{45545}Sa zadovoljstvom. | - Dobro. Nedostaješ nam u crkvi.
{45550}{45616}Žurili smo se da završimo kuæu.
{45624}{45710}Nadam se da ne radite nedjeljom.
{45715}{45770}Mogu li vas ponuditi èajem? | - Ne, hvala.
{45776}{45833}Zapravo smo | na putu prema utvrdi.
{45839}{45943}Simone, idemo po namirnice prije | nego što se promijeni vrijeme.
{45949}{46111}Vraæamo se za par dana. | Treba li ti što? - Ne.
{46116}{46193}Mora da ti nije lako ovdje...
{46199}{46254}...samoj sa dva mlada muškarca.
{46259}{46317}Ne, dobro nam je.
{46320}{46449}Imaš jako puno posla | prije nego što padne snijeg.
{46455}{46532}Gle, ovo je nešto | što do sada nisam vidio.
{46537}{46631}Kamin, otvoren | sa obje strane u sredini sobe.
{46636}{46702}Simon kaže | da može grijati èetiri sobe.
{46708}{46746}Ovo je prava vatrena opasnost.
{46755}{46815}Zar spavaš ovdje, George? | Mora da se smrzavaš.
{46820}{46928}Biæe nam drago da spavaš | kod nas, George. To možeš.
{46933}{47021}Pa, nije tako strašno. | Napravio sam malo sklonište.
{47024}{47084}Imam onaj tepih od | medvjeðeg krzna koji si mi dao.
{47090}{47192}Gradiš preblizu potoku.
{47197}{47359}Cijelo ovo podruèje | bude poplavljeno u proljeæe.
{47480}{47739}Ne trebamo njegovu pomoæ.
{47745}{47816}Niti èiju drugu.
{47819}{47876}On se nada da æemo propasti | tako da on može sve uzeti.
{47882}{47926}Ili æe svoju | kæer oženiti za Georga.
{47932}{47982}Bio bi lud da to uèiniš, | jel da mladiæu?
{47987}{48064}Ti si iznajmio njihovu kuæu, | Simon. - Otplatio sam mu krznima.
{48069}{48176}Nije baš pametan. Puno kuæa ima | kamine u sredini, otvorene ovako
{48182}{48309}Svaka kuæa u Orkneyu.
{48314}{48380}Onoj Jenny si zapeo za oko, | George.
{48385}{48437}Prosto i jednostavno.
{48446}{48556}Da, pa možda samo prosto. | Ja nisam jednostavan.
{48564}{48638}Dobro.
{48696}{48801}Laku noæ. - Laku noæ.
{49059}{49111}Gospodine?
{49117}{49251}Annie mi je dala | da ovo pošaljem.
{49257}{49339}Ja nikada ništa nisam slala, pa | sam pomislila da to dam vama.
{49345}{49472}Hvala, Ruth. | Ja æu se za to pobrinuti.
{49607}{49700}Draga Sadie, u velikoj sam | nevolji i moram ti se povjeriti.
{49705}{49747}Ne znam kome mogu vjerovati,
{49752}{49810}pa ti neæu pisati o svojoj | situaciji dok mi se ne javiš.
{49815}{49848}Ako doðeš ovamo...
{49857}{49914}sigurna sam da æe ti onaj | g. Mullen u utvrdi pomoæi
{49922}{49980}da se smjestiš.
{49986}{50085}Iskreno tvoja, Annie. | Ništa ne objašnjava.
{50090}{50200}Kaže da puno toga drži u sebi.
{50206}{50294}Poslati æu pismo. | Onda, ako Sadie postoji...
{50297}{50357}dopisivanje æe se nastaviti, a | mi æemo saznati što se stvarno
{50362}{50514}dogodilo tamo vani. | - Dobra ideja.
{51314}{51378}Napisao je to | svojoj tajnoj ljubavi.
{51383}{51476}Agnes Craig. Udata žena.
{51482}{51551}Ljubavnica.
{51556}{51605}Imaš upeèatljiv glas.
{51614}{51710}Nije ni èudo | da im fališ u crkvi.
{51717}{51890}Nije se imalo Bog zna o èemu | pjevati dok ti nisi došla, Annie
{51899}{51978}Svake noæi | zahvaljujem Bogu što si ovdje.
{51986}{52080}Pravi si blagoslov.
{52199}{52347}Bolje da idem i spremim veèeru.
{52449}{52517}Annie...
{52522}{52580}Da si moja žena...
{52589}{52724}ja bih te obožavao.
{52938}{53059}Prošao je cijeli mjesec...
{53064}{53130}a još uvijek se ništa nije | znalo o identitetu mlade žene,
{53136}{53210}niti o lokaciji njene kuæe.
{53216}{53279}Njena mladost i neposrednost | izazivale su simpatije...
{53284}{53315}ali iz mog iskustva...
{53320}{53436}suditi o karakteru žene prema | njenom izgledu, je pogrešno.
{53441}{53587}Mislim da je bolje | da tebi ovo dam. - Hvala.
{53622}{53705}Vidi ovo.
{53711}{53810}"Sadie Johnson, preminula." | Oh, Bože.
{53818}{53884}Reæi æeš joj. | - Bilo bi pametno ne reæi.
{53892}{53978}Zbog jednoga, piše drugo pismo. | Ovog puta, dugaèko.
{53983}{54041}Da. Da, jasno mi je što misliš.
{54046}{54101}Èovjek na tvom položaju | uvijek mora reæi istinu...
{54107}{54239}ali istina ne mora biti | reèena u cijelosti. - Toèno.
{54244}{54311}Ima siguran rukopis, | slažeš li se?
{54316}{54467}Da. Da, fascinantna | mlada djevojka je ona.
{55174}{55278}Da. Jako dobro. Bravo.
{55284}{55344}Ovo je fantastièno!
{55349}{55446}Stvarno si talentiran, mladiæu. | Gdje si nauèio ovako pjevati?
{55451}{55539}Pa, odgojila | me je sestra moga oca...
{55545}{55661}uèiteljica. | Simon nije imao takvu sreæu.
{55666}{55737}Odgojio ga je roðak moje majke, | lugar.
{55743}{55886}Mogao bih vam nešto zapjevati, | ali ne bi vam se puno dopalo.
{55891}{55949}Želio sam | nastaviti školovanje...
{55955}{56029}ali Simon nije mogao èekati da | doðe do oèevog nasljedstva.
{56034}{56089}Prekrasno je | što imate jedan drugog.
{56095}{56161}Bi li otpjevao još jednu, | George?
{56166}{56260}Ne, ne može. Upravo odlazimo.
{56266}{56318}Uzmi kaput.
{56323}{56386}Polako, sinko, mislili smo da | æete veèeras prespavati ovdje.
{56392}{56497}Da, vani je mrkli mrak. | - Ja i tako nisam želio doæi.
{56502}{56582}Mogli bismo krenuti | rano ujutro, Simon. - Ne!
{56587}{56645}Prokletstvo!
{56648}{56711}Pa, meni ne bi palo na | pamet da putujem ovako kasno.
{56716}{56802}Ne, ja ostajem. | - Bojite li se vukova Veleèasni?
{56807}{56865}Bog æe vas štititi.
{56870}{56936}Nadam se da æete | opet uskoro doæi, gðo Herron.
{56942}{57003}Ja možda | ne znam èitati i pisati...
{57008}{57091}ali mogu raditi svakodnevne | poslove bez žaljenja.
{57096}{57134}Dobro, idemo, Simon.
{57143}{57206}Htjela bih vam zahvaliti gðo | Treece, za najbolje jelo
{57211}{57283}koje sam ikada jela u životu... | i za gostoprimstvo.
{57289}{57324}Bog vas blagoslovio sve.
{57330}{57395}Bio bi mrtav da nema mene! | Veæ stotinu puta!
{57401}{57580}Idemo, Simon. | - Inaèe æe ga pojesti vukovi.
{57627}{57687}Bio je pravi užitak.
{57693}{57800}Zaboravi njega, George. | Napravila sam pitu od grožðica.
{57808}{57896}Sjedni. - Hvala.
{57901}{58036}Naša Jenny je napravila puding, | George.
{58061}{58160}Drži se, ženo!
{58350}{58499}Simon! Simon, ja padam!
{58636}{58699}Misliš da sam glup?
{58705}{58807}Misliš da ne | vidim što se dogaða?
{58812}{58972}Trebao bih vas oboje ostaviti | ovdje da se smrznete. - George!
{59293}{59365}Silazi dolje!
{59524}{59645}Zapali vatru.
{60030}{60107}Zašto nisi u krevetu?
{60116}{60198}Simon, ne želim to.
{60203}{60283}Daj da prvo | ovdje lijepo zagrijemo.
{60289}{60338}Sada skini sve sa sebe.
{60347}{60421}Ti samo sjedni, | a ja æu se skinuti za tebe.
{60429}{60511}Dopast æe ti se. Sve æu skinuti.
{60517}{60561}Dopast æe ti se.
{60569}{60715}Ti samo tu sjedni.
{60756}{60825}George æe uskoro doæi.
{60830}{60987}Ako budemo jako tihi, | otiæi æe u krevet.
{61257}{61317}Annie!
{61322}{61386}Annie!
{61391}{61422}Annie!
{61430}{61477}Jesi li dobro?
{61521}{61609}Proklet bio!
{61614}{61661}Mièi se k vragu odavde!
{61669}{61755}Annie!
{61760}{61818}Annie, reci nešto!
{61823}{61895}Bilo što! - Simone, ti si pijan.
{61900}{62021}Reci mu, | Annie da sam neodoljiv muž.
{62027}{62090}Dobro sam, George! Dobro sam!
{62098}{62216}Ne! Ja ulazim unutra! | - Ne, nemoj! Nemoj! - Annie!
{62220}{62282}Odlazi, George! | - Annie, molim te!
{62288}{62335}Idi sada.
{62340}{62409}Molim te idi.
{63130}{63193}Hvala, Donnely.
{63209}{63284}Dobio sam odgovor na svoj upit.
{63289}{63361}Veleèasni McBain. | - Jesu li pronašli Georga?
{63366}{63457}Rekao je da je dogovorio | brak sa vama i gðom Herron.
{63465}{63509}Èini se da puno zna.
{63517}{63561}Jako je zabrinut za tebe...
{63570}{63627}i kaže da je sve ovo bila...
{63633}{63735}strašna pogreška.
{63740}{63817}Zašto si došla ovamo, Annie?
{63822}{63919}Jeste li ikada pogledali | u oèi mrtvog èovjeka, g. Mullen?
{63924}{63984}Ne, ne u mrtvog èovjeka.
{63990}{64048}Mrtvog djeteta.
{64053}{64111}Moje kæeri, stare par dana.
{64116}{64182}Žao mi je. - Krivim sebe.
{64188}{64251}Ali to ništa ne mijenja, jel da?
{64257}{64307}Ne, gospodine.
{64314}{64408}Smrt je zauvijek.
{65495}{65563}Annie, sjeæaš li se mene?
{65568}{65643}Veleèasni McBain, naravno.
{65651}{65706}Siroto malo dijete.
{65712}{65797}Tražili smo te svaki dan, | onda smo èuli da si ovdje.
{65803}{65932}Jeste li vidjeli George? | - Da, on je kod Treeces.
{65937}{66003}Uznemiren je i zbunjen...
{66009}{66122}a siguran sam da si i ti.
{66127}{66176}Ali Annie...
{66182}{66261}George nam je | rekao što se desilo.
{66267}{66347}Mislim da nije, Veleèasni.
{66353}{66460}Mislim da nije.
{66465}{66556}Što to imaš na sebi?
{66561}{66726}Vjenèat æu se sa Vragom, | gospodine.
{66732}{66814}Recite Georgu da ne laže, | osim ako je apsolutno siguran...
{66820}{66936}da istina | nikada neæe biti otkrivena.
{66941}{67037}Ja æu sve srediti. Majka joj je | bila katolik, a otac je bio Skot
{67043}{67095}Natjerajte ga da ode, g. Mullen!
{67101}{67158}Nitko je za ništa ne optužuje!
{67164}{67219}Niste bili tamo, Veleèasni! | Vi ne znate!
{67227}{67282}Annie, bi li me malo saslušala!
{67287}{67348}Idemo, Veleèasni. | Ovo nikamo ne vodi.
{67353}{67428}Donnely.
{67609}{67706}A ti vjeruješ u njegovu prièu? | - George je èlan moje pastve.
{67711}{67761}Zakleo se da je to istina.
{67768}{67914}Ili je ona luda, | ili je ovaj mladi èovjek lažljivac.
{67920}{68036}Jesam li ja zla ili luda?
{68101}{68222}George! Konaèno je zaspao.
{68228}{68324}Annie. Sve je u redu.
{68327}{68434}Uðimo unutra.
{68520}{68649}Odvedi me.
{68734}{68800}Mogli bi poèeti od poèetka.
{68805}{68945}Naša kuæa. Naša obitelj.
{69234}{69320}Proklet bio!
{69451}{69589}Nemoj! Nemoj!
{69622}{69751}Prestani!
{69944}{69968}George!
{69974}{70145}Trebao bih isto uèiniti i tebi!
{72403}{72471}Pijan je.
{72476}{72554}Zaspao je. Žao mu je George. | Sigurna sam da æe se isprièati.
{72559}{72628}Može se isprièati i | samome Vragu, što se mene tièe.
{72634}{72686}Što ako se vatra ugasi? | Smrznut æe se.
{72694}{72820}Jeste li svi dobro? | - Samo trabunjanje.
{72826}{72922}Isuse! Simon! Što to radiš?
{72999}{73043}Odlazite sa moje zemlje!
{73051}{73112}Što je tebi k vragu? | Ovdje sam da pomognem!
{73118}{73167}Nezahvalni nitkovi!
{73175}{73239}Za ime Boga, Simon! | Ne možemo ostati ovdje!
{73247}{73349}Neæe preživjeti zimu!
{73354}{73428}Natrag!
{73434}{73491}Treba nam pomoæ! | Zar ti to nije jasno?
{73499}{73566}K vragu i ona! Želiš li izgubiti | ovo mjesto? To æe se i desiti!
{73571}{73640}George! | Gðo Herron! Jeste li dobro?
{73645}{73717}Bježite k vragu od nas! | Ostavite nas na miru!
{73722}{73791}U afektu si, sinko!
{73797}{73868}Kriste!
{74050}{74116}Sada imaš priliku | da sve ispraviš, jadni brate!
{74121}{74182}Vi se popnite na te konje, | a mi æemo natrag na posao...
{74187}{74251}a ti joj se ne približavaj...
{74256}{74454}ili æeš odavde otiæi sam | i nikada se više ne vraæaj.
{74501}{74564}George!
{75666}{75749}"Oh, Sadie, znam da je | nemoguæe poslati ovo pismo...
{75755}{75853}ali ipak, | moram razgovarati sa tobom.
{75859}{75925}Bogu hvala | da Simon ne zna èitati.
{75930}{76027}Bojim se | da se dogodilo ono najgore.
{76035}{76093}Otišli su | i nema ih veæ dvije noæi...
{76099}{76247}a ja se bojim | da je George možda mrtav."
{76486}{76555}Božiæ je.
{76561}{76618}Sretan Božiæ, Annie.
{76624}{76715}Donio sam kljuè.
{76780}{76843}Donio sam ti | još jednu boèicu laudanuma.
{76847}{76995}Mislio sam da ti je pri kraju. | Želiš li gutljaj?
{77111}{77262}Mislim da je vrijeme | da pogledam ozeblinu.
{77267}{77339}Za svaki sluèaj, naravno.
{77344}{77451}Bi li molim te sjela?
{77487}{77663}Ako možeš, molim te skini ovoj.
{77672}{77754}Dobro.
{77822}{77924}Skinimo i tvoju èizmu. | - Što ti radiš ovdje?
{77930}{78053}Mièi se odavde, glupa budalo! | Idi!
{78059}{78125}Škot...
{78147}{78224}Tiho sada, Annie.
{78230}{78395}Pusti lijeènika | da obavi svoj posao.
{78428}{78491}Prestani! | - Vruæe je ovdje, Annie!
{78497}{78543}Prestani! | - Što se k vragu ovdje dogaða!
{78551}{78614}Božiæ je, g. Mullen! | - Božiæ, moje dupe!
{78620}{78675}Otvori prokleta vrata! | - Vrati se natrag na slavlje!
{78684}{78882}Navuci proklete hlaèe, èovjeèe! | Odmah prekini sa time!
{78945}{79091}Pijana budalo! | Gubi se k vragu odavde!
{79234}{79415}Nemoj mi reæi da i ti nisi | nikada pomislio na to, g. Mullen
{79613}{79742}On misli da si jako lijepa.
{79747}{79792}Znaš što...
{79797}{79918}doði k meni doma na fini topli | objed, na malu Božiænu puricu.
{79987}{80105}Vidite? | Prazna zdjela. Prazna zdjela.
{80111}{80226}Protrljaj i nešto zaželi.
{80240}{80339}Zaželjela si slatkiše.
{80347}{80399}Zapjevaj nam nešto, Annie.
{80408}{80551}Ti si na redu. Obeæala si Annie. | - Hajde!
{81659}{81786}"Mislila sam da je vukao | deblo i da je to bio Simon.
{81791}{81967}Ali, zapravo je bio George, | u Simonovom kaputu.
{82245}{82355}Oh, moj Bože.
{82440}{82550}Što se desilo?
{82555}{82690}George, što se desilo?
{83301}{83408}Što da radimo?
{83414}{83586}Što da radimo? Što da radimo?
{83620}{83762}Kada se to desilo? Juèer?
{83768}{83859}Potukli ste se?
{83867}{83958}Bila je to nesreæa.
{83964}{84013}Ne brini se.
{84021}{84062}Sve æe biti u redu.
{84068}{84118}Drvo je palo na njega. | - Siroti Simon.
{84126}{84180}Bio mi je muž, ali ga | zapravo uopæe nisam poznavala.
{84186}{84249}Nitko nije. Nitko.
{84255}{84310}Teško je radio.
{84318}{84357}Da.
{84365}{84395}"Ne mogu poricati, Sadie...
{84403}{84484}Osjetila sam ogromno olakšanje | kada sam vidjela da je mrtav.
{84489}{84549}Htjela sam zaboraviti sve | što je bilo vezano za njega...
{84552}{84607}kao da se on | nikada nije ni dogodio.
{84612}{84706}Kao da je to bio George koji je | došao po mene i doveo me ovamo.
{84711}{84827}Moje molitve su bile uslišene."
{85030}{85105}Bog æe mi oprostiti.
{85110}{85212}Naravno da æe ti Bog oprostiti. | Bila je to nesreæa.
{85218}{85314}Zatvori oèi. | Bog æe nam reæi što da uèinimo.
{85319}{85380}Oèe naš koji jesi na nebesima...
{85385}{85443}Sveti se ime tvoje.
{85449}{85575}Doði kraljevstvo tvoje. | Budi volja tvoja...
{86780}{86878}Moramo otiæi i reæi | Treeces-ima i Veleèasnom.
{86884}{86989}Ne veèeras. | Pokrila sam tijelo. Sigurno je.
{86994}{87080}Sutra.
{87085}{87266}Uði brzo, | prije nego što se ohladi.
{87272}{87365}Ovdje je tako mirno. - Da.
{87374}{88114}Sve æe biti u redu.
{90099}{90280}Želio sam te od prvog | trenutka kada sam te vidio.
{93033}{93091}Annie!
{93096}{93187}Isprièavam se. | Nisam te htio prestrašiti.
{93189}{93250}Brinuo sam se za tebe.
{93255}{93349}Razgovarao sam sa g. Treece.
{93355}{93459}Da, dobro od vas da ste došli.
{93464}{93550}Veleèasni. Dobrodošli.
{93555}{93624}George.
{93632}{93690}Gdje je Simon?
{93696}{93828}Otišao je. U utvrdu.
{93833}{93880}Trebala nam je nova sjekira.
{93886}{93943}Gos. Treece | je bio jako uvrijeðen.
{93949}{94007}Rekao mi je | da je Simon pucao na njega.
{94012}{94089}Ne na njega. U zrak.
{94095}{94161}U poèetku | nije ni vidio da je to on.
{94168}{94265}Da, Simon, | pucnjava i ostalo, bio je ljut.
{94270}{94328}Da. - Shvaæam.
{94334}{94408}Htio bih s njim porazgovarati. | - Shvatio je da nije bio u pravu.
{94416}{94447}Žao mu je. - Vjerujem.
{94455}{94540}Ja ne želim stvari pogoršavati, | ali kada æe se vratiti?
{94545}{94680}Reæi æemo mu da ste dolazili.
{94738}{94815}Svi se brinemo za vas.
{94820}{94914}Zar ne mislite da bi bilo bolje | da negdje odete do proljeæa?
{94920}{94983}Dobro smo, Veleèasni. Stvarno.
{94988}{95076}Ovog puta æemo sagraditi bolju. | U meðuvremenu...
{95082}{95151}snaæi æemo se. | Hoæete li popiti èaj?
{95156}{95228}Ne, hvala.
{95233}{95393}Vidim da imate posla.
{95568}{95651}George, zašto si mu slagao?
{95657}{95774}Zašto si lagao Veleèasnom?
{95780}{95871}Da dobijemo malo vremena skupa. | Sada.
{95876}{95932}Zašto mu nisi | jednostavno rekao što se desilo?
{95939}{96016}Annie, ja želim biti s tobom.
{96022}{96110}Sam sa tobom. Sada.
{96116}{96170}Volim te.
{96176}{96267}Ali moramo Simonu | prirediti pravi pogreb u crkvi.
{96272}{96357}Ne, pokopat æu ga ovdje. | - Zašto?
{96366}{96429}On nije vjerovao u Boga!
{96437}{96580}To je ono što bi on želio.
{96586}{96745}Kamo ideš? - Da provjerim zamke.
{96861}{96908}"6-ti sijeèanj.
{96913}{97015}Odluèio sam otputovati u kuæu | Herron-ovih da sam sve ispitam."
{97020}{97059}Gos. Mullen.
{97065}{97125}Mene neæe biti | kada se ti vratiš.
{97130}{97219}Ova zemlja me testira.
{97224}{97295}Moram priznati | da je izvukla ono bolje iz mene.
{97301}{97367}Valjda si u pravu | što me šalješ natrag.
{97372}{97439}Ako možeš | napiši mi nešto o djevojci...
{97441}{97601}Zanimalo bi me što si otkrio.
{97755}{97958}"Odluka da osudim gðu Herron | bila mi je kao teret iznad glave
{97964}{98036}Razlika u izjavi izmeðu gðe | Herron i Veleèasnog McBaina...
{98041}{98112}je toliko zapanjujuæa | da zahtijeva daljnju istragu.
{98118}{98170}Izvijestio sam o svojoj | želji da pregledam tijelo...
{98178}{98302}i da ispitam | sve koji su ukljuèeni."
{98420}{98503}Prokletstvo! To govno!
{98508}{98558}Što je bilo? - Vukovi.
{98563}{98607}Namirisali su tijelo.
{98616}{98676}Ujutro æu otiæi po novu | lopatu da ga možemo pokopati.
{98682}{98734}Dugo te nije bilo. - Da.
{98742}{98805}Trebalo mi je | vremena da razmislim.
{98811}{98876}O èemu. - O tome što æu dalje.
{98882}{98945}Ne znam puno o poljoprivredi.
{98951}{99011}Simon je bio | onaj koji je sve to znao.
{99017}{99099}Ja sam odrastao u gradu, | u velikoj kuæi, sa poslugom.
{99108}{99185}Mislim da ja ovo sada | ne mogu nastaviti.
{99190}{99272}Neæeš biti sam, ja æu biti ovdje
{99278}{99328}Naša farma æe biti prava farma.
{99333}{99427}Imati æemo piliæe, | guske, krave i mlade.
{99432}{99474}Annie!
{99479}{99668}Ne vidim kako | to možemo imati sada.
{99674}{99740}O èemu razmišljaš?
{99745}{99814}Ja nemam kamo iæi!
{99823}{99905}To nije u redu.
{99911}{100032}Ovo što mi radimo nije u redu.
{100040}{100117}Znam.
{100122}{100235}Trebali smo èekati.
{100359}{100516}Ali ja te želim sada. | Ne mogu si pomoæi.
{100521}{100603}Sada ne želim nikoga vidjeti.
{100607}{100722}Samo želim tebe.
{100926}{101101}Što æe biti sa nama?
{101674}{101742}Henry Mullen. | Tražim Georga Herrona.
{101747}{101822}Nije ovdje. Otišao je u | posjet teti koja ga je odgojila.
{101824}{101885}Ali poslao sam obavijest po | Veleèasnom McBainu da æu doæi
{101888}{101951}za tjedan dana. - Nije nam rekao. | - Moram sa njime razgovarati.
{101957}{102034}Bez brige. | Možete ostati sa nama.
{102039}{102097}Vratit æe se za par dana, | sigurna sam.
{102103}{102168}Nije bilo u redu da je | ona bila sama sa ta dva mladiæa.
{102172}{102248}Simon je bio zao i glup. | Puno drugaèiji od Georga.
{102254}{102320}George je drag mladiæ.
{102323}{102374}Žao nam ga je.
{102380}{102430}Jedva da je | od nesreæe i progovorio.
{102435}{102512}Kada su se tek doselili, George | je bio u crkvi svake nedjelje.
{102518}{102584}Onda je došla ona. Veleèasni | kaže da je odgojena u našoj
{102589}{102658}crkvi, ali... | - Pozvali smo ih na veèeru.
{102664}{102730}Otišli su usred jela. | - George nije želio iæi.
{102737}{102823}Slijedeæe jutro osjetili smo dim | Henry je otišao tamo...
{102828}{102903}...a Simon ga je otjerao | pištoljem. - Pištoljem?
{102908}{103037}Rekao sam Veleèasnom McBaine.
{103274}{103334}Odmah æu ih odnijeti | i dati joj da proba.
{103340}{103414}Biti æe joj drago. Imat æu još | posla za tebe ako imaš vremena.
{103422}{103486}Jedino što imam je vrijeme, | gospodine.
{103489}{103582}Da. Da, apsurdno je, ti ovdje.
{103587}{103661}Meni se sviða. - Da, dobro...
{103670}{103807}Sloboda nema ništa sa | neèijim fizièkim okruženjem.
{103813}{103931}Dopusti mi.
{103936}{104036}Vratit æu se.
{104324}{104391}"Oskudnost i izoliranost | mjesta deprimiraju me.
{104399}{104481}Život bi ovdje bio jedva | moguæ i u najboljim uvjetima.
{104487}{104748}Tamo je bio i grob, | kako je gða Herron i rekla.
{104764}{104889}Ali bio je prazan, a | okolna zemlja natopljena krvlju.
{104893}{104937}Netko je nedavno bio ovdje...
{104943}{105128}sudeæi prema vatri koja | je tinjala u ošteæenom kaminu.
{105133}{105293}Èula sam kako | je pukla njegova lubanja."
{105903}{105969}Što ti radiš ovdje?
{105974}{106027}Istražujem smrt Simona Herrona.
{106032}{106101}Zovem se Henry Mullen.
{106107}{106195}George Herron.
{106200}{106288}Ovdje sam da pregledam | tijelo umrlog, vašega brata.
{106293}{106343}To je bila nesreæa!
{106351}{106428}Èini se da je to upitno.
{106434}{106547}Spusti taj pištolj!
{106593}{106657}Rekao si Treeces | da ideš u posjet svojoj teti.
{106662}{106780}Rekao sam. Jesam. Ali sam | odluèio da prvo doðem ovamo.
{106786}{106857}Da provjerim zamke. | - Vidio sam tijelo, George.
{106862}{106923}U kaminu.
{106929}{106989}Vukovi su ga izvukli.
{106995}{107044}Bilo je...
{107049}{107110}strašno.
{107116}{107207}Dijelovi su mu | bili odvuèeni u grmlje...
{107212}{107278}pojedeni do kosti.
{107284}{107372}Zato sam sakupio | sve što sam mogao naæi...
{107377}{107416}i zapalio sam to.
{107424}{107478}U kaminu?
{107484}{107566}Nisam znao što bih drugo mogao.
{107572}{107647}Koliko imaš godina? | - 17, gospodine.
{107652}{107729}17. Èuo sam što ti se desilo...
{107734}{107798}od Veleèasnog i gðe Treece.
{107803}{107866}Sada bi mi ti trebao | isprièati sve svojim rijeèima.
{107870}{107946}Nema se što isprièati. | Brat mi je imao nesreæu.
{107952}{108043}Vidio sam svojim oèima. | Drvo je palo na njega.
{108048}{108120}A Annie, njegova žena...
{108126}{108251}pa, pogodilo ju je, valjda.
{108257}{108320}Otišla je. - Draga ti je.
{108326}{108403}Da, dobro se slažemo.
{108408}{108469}Oboje volimo knjige i muziku.
{108474}{108590}A tvoj brat, jesi | li se dobro slagao sa njime?
{108595}{108672}Simon i ja | nismo imali puno zajednièkog.
{108676}{108752}Ali naporno je radio. | Želio si je stvoriti bolji život.
{108757}{108812}Nama. Ja sam to cijenio.
{108818}{108868}Shvaæam.
{108873}{108917}Što to radiš?
{108922}{108983}Uzimam ostatke | tvoga brata sa sobom.
{108989}{109041}Odnijet æeš ih? - Da, kao dokaz.
{109047}{109105}Biti æe ti vraæeni ako želiš, | zbog pokopa,
{109109}{109145}ili ih mi možemo | pokopati umjesto tebe.
{109153}{109255}Ne, ja æu to. Ja æu ih pokopati. | - Dobro.
{109261}{109332}Hoæeš li | nastaviti živjeti ovdje?
{109338}{109428}To je sve što imam. Gos. Treece | je rekao da æe mi u proljeæe
{109432}{109497}pomoæi sa zadnjim. | Bili su jako dobri prema meni.
{109503}{109616}Potrudit æu se da uspijem.
{109896}{109943}Što æe biti sa Annie, gospodine?
{109951}{110025}Ako dokazi potvrde njenu izjavu, | optužit æemo je...
{110034}{110091}pa æe iæi na sud.
{110097}{110174}Znaèi mogla bi biti obješena? | - Ako bude kriva, da.
{110179}{110286}A ako bude kriva, ti æeš takoðer | biti kriv, zbog utaje dokaza.
{110292}{110361}Razumiješ li ovo? | Ti si takoðer pod istragom.
{110366}{110454}Da. Ali ona nije kriva, | g. Mullen.
{110459}{110520}Mogu to potvrditi pred Bogom, | mojim Stvoriteljem.
{110526}{110584}Treba mi pismena izjava o tome, | George.
{110592}{110674}Da, gospodine. - Voliš li lov?
{110680}{110732}Moram živjeti, gospodine.
{110740}{110886}Brat me toliko nauèio.
{110960}{111057}"Moje putovanje iziskivalo je | onoliko pitanja kao i odgovora.
{111062}{111117}Razbijena lubanja | je dokaz koji osuðuje.
{111122}{111222}Ali George Herron je | siguran da je to bila nesreæa.
{111227}{111279}Sada imam | sliku njenog života tamo.
{111287}{111343}Težak život sa teškim èovjekom.
{111348}{111422}Dovoljno težak | da ženu dovede do ludila.
{111428}{111538}Ili ubojstva?
{111543}{111603}Moje spoznaje su bile u sukobu.
{111609}{111766}Riješio sam je optužiti | i prepustiti poroti da odluèi."
{112096}{112186}Gos. Mullen se vratio. | - Da. Jako je umoran.
{112192}{112272}Sinoæ je spavao pod zvijezdama. | - Je li razgovarao sa George-om?
{112278}{112341}Meni ne podnosi izvještaj.
{112349}{112407}Moram sa njime razgovarati.
{112412}{112478}Ni tebi ne podnosi izvještaj.
{112484}{112594}Daj mi tvoj materijal.
{112602}{112698}I tvoje krpe (uloške).
{113124}{113201}Gos. Seller. - Oprostite. | Èuo sam da ste se vratili.
{113204}{113259}Da. Ima li problema? | - Ne baš.
{113265}{113322}Gða Herron | me tražila da ovo pošaljem...
{113328}{113391}ali poštar je rekao da se njeno | zadnje pismo ovoj S. Johnson...
{113399}{113490}vratilo sa oznakom "preminula", | pa je èudno da joj nije reèeno.
{113499}{113592}Da, mislio sam da je tako bolje. | Bila je pod velikim stresom i...
{113597}{113658}Znate što, dajte ga meni.
{113664}{113771}Nikada si ne bih | oprostio da joj naudim.
{113776}{113851}Usuðujem se reæi da je | dovoljno naudila sama sebi.
{113856}{113905}Kako napreduje vaša predstava?
{113914}{113985}Probna predstava je veèeras. | - Veselim se da æu je vidjeti.
{114007}{114111}Gos. Seller, | ne govorite ništa gði Herron.
{114120}{114180}Molim vas.
{114351}{114409}Hoæete li sada veèerati, | gospodine?
{114414}{114478}Da, veèeras æu jesti ovdje, | Ruth.
{114483}{114532}Djevojka bi htjela | s vama razgovarati.
{114538}{114590}Razgovarat æu sa njom sutra.
{114599}{114686}Gospodine... - Hvala, Ruth.
{114851}{114918}"Draga Sadie, zašto | mi nisi odgovorila na pisma?
{114923}{115063}Mislim da ih nisi ni dobila.
{115270}{115385}K vragu, | je li prekasno za istinu?
{115391}{115451}Više nije bio djeèak.
{115457}{115594}Dijete je nestalo iz njega."
{116284}{116345}Mièi se odatle!
{116353}{116419}Idi! Idi!
{116611}{116779}Idi! Ne bojim te se!
{117822}{117879}"Rana je bila od sjekire...
{117887}{118003}duboka i strašna, | skroz kroz kosti i njegovo srce.
{118011}{118195}Što god da se desilo tamo, | Sadie, završilo je izdajom...
{118201}{118256}brat protiv brata...
{118264}{118325}a sve to zbog mene.
{118330}{118495}Ja sam ih okrenula | jednog protiv drugog."
{119697}{119801}Rekao sam ti da æu ga pokopati!
{119809}{119873}Reci da je to bila nesreæa...
{119881}{119914}kao što si rekao...
{119922}{120002}Zašto ga nisi ostavila na miru?
{120008}{120164}Pomozi mi! - Bože!
{120709}{120778}Ja sam ga ubio.
{120784}{120882}Gledao sam ga kako | ispušta zadnji prokleti dah...
{120887}{121041}i nije mi bilo žao.
{121050}{121144}I ti si željela da je mrtav.
{121151}{121218}Znam da smo oboje krivi.
{121223}{121374}Ali nitko ne mora znati.
{121382}{121509}Uèinio sam to za tebe!
{121534}{121605}Htio se vratiti da te opet uzme, | rekao je...
{121614}{121683}i smijao mi se.
{121688}{121815}Suludo je govorio | o onome što æe ti raditi.
{121823}{121889}Zato sam uzeo sjekiru...
{121894}{121987}i divlje je bacio.
{121993}{122043}On je pao dolje...
{122051}{122125}i samo je jednom kriknuo.
{122134}{122219}Onda me samo pogledao.
{122224}{122323}I to je bilo sve.
{122332}{122428}Bilo je prelagano.
{122551}{122661}Prelagano.
{122975}{123038}Zar neæeš doæi u krevet?
{123047}{123118}Možda smo to oboje željeli...
{123124}{123211}ali ja sam to uèinio.
{123217}{123343}Nikada nikome neæu reæi.
{123352}{123426}Bilo je bolje | dok nisi znala istinu...
{123432}{123495}...jer svaki put | kada te pogledam...
{123503}{123755}sjetim se kako izvlaèim krvavu | oštricu iz leða svoga brata!
{124497}{124555}Kamo æeš sada?
{124561}{124604}Istina me progoni, Annie.
{124615}{124695}Ne mogu spavati i ne mogu | ostati ovdje. Idem u utvrdu.
{124701}{124761}Oboje smo George, ne samo ti!
{124766}{124901}Ako netko doðe, reci mu | istinu o onome što sam uèinio.
{124907}{124995}Predat æu se. | Ne moraju znati za nas.
{125000}{125044}Nemoj iæi!
{125050}{125220}Nadam se da te | nikada više neæu vidjeti!
{125655}{125726}"Danima sam èekala, | polako gubeæi razum.
{125732}{125781}Mislila sam da je | George otišao u utvrdu...
{125787}{125869}i da æe visiti za zloèin | koji je bio moj koliko i njegov.
{125875}{126004}Konaèno, | više nisam mogla izdržati.
{126221}{126293}Znala sam svoj udio u ovome...
{126298}{126361}ali sam doista mislila | da me George volio...
{126370}{126491}onoliko koliko i ja njega."
{126535}{126659}Kako je gða Herron?
{126664}{126722}Ne baš dobro. Zabrinuto.
{126727}{126788}Ima jutarnje muènine.
{126796}{126950}Trudna je. Oèito je.
{126955}{127016}Dobit æe dijete?
{127022}{127093}Sada je ne možeš objesiti, | jel da?
{127099}{127153}To ne ovisi o meni, Ruth.
{127159}{127211}Mislim da da.
{127220}{127324}Znam da je tako.
{127330}{127420}"Potrebna si mi ovdje, Sadie. | Moram te moliti za veliku uslugu
{127426}{127552}Molim te odmah se javi, | jer æu doista poludjeti."
{127745}{127838}Gos. Mullen.
{127847}{127921}Moram ti nešto reæi. | - Da, ali prvo...
{127926}{128069}Molim te sjedni, gðo Herron.
{128282}{128388}Ovo se vratilo.
{128696}{128828}Jako mi je žao.
{128870}{128941}Jesi li donio kakvu odluku?
{128947}{129034}Još ne. Kompliciranije | je nego što sam mislio.
{129040}{129146}To je sve što mogu reæi.
{129295}{129440}Reæi æu Ruth da ti donese èaj.
{130549}{130705}"U sluèaju gðe Annie Herron...
{130714}{130757}U sluèaju gðe Annie Herron...
{130763}{130881}odluka je ovog ureda...
{130947}{130986}...odluka je ovog ureda...
{130994}{131055}da nema dovoljno dokaza za | opravdanu sumnju zbog bilo
{131060}{131126}kakve kriminalne radnje. Gða | Herron je patila od iluzija...
{131134}{131197}izazvanih zlostavljanjem | od strane njenog supruga.
{131203}{131278}Rezultat toga je bio da je | vjerovala da je upletena...
{131283}{131332}u njegovu smrt nesreæom...
{131341}{131403}buduæi da se željela | osloboditi svoga zlostavljaèa.
{131409}{131459}Buduæi da je oporavkom | pokazala svoju pravu prirodu...
{131464}{131566}oslobaða se pritvora."
{131868}{131962}Godinu dana kasnije
{131998}{132234}Lijep dan za vjenèanje, | zar ne, Annie?
{132326}{132380}Dužnosti odanog muža su...
{132389}{132451}da zaboravi sve druge | za vrijeme njenog života...
{132457}{132512}štujuæi vjeru i istinu | u svakom trenutku...
{132518}{132608}kako rijeè Božja i njegovo | sveto Evanðelje zapovijeda.
{132614}{132740}Uzimam je pred Bogom | i u prisutnosti ove župe.
{132745}{132778}Gospodin vas | posveæuje i blagoslivlja.
{132787}{132839}Gospodin izlijeva | blagodati svoje milosti na vas...
{132847}{132903}da ga možete štovati i skupa | živjeti u ljubavi do kraja
{132908}{133086}vaših života. | Hoæete li molim vas svi ustati?
{133315}{133397}"Èini se da je g. Treece ipak | preuzeo kontrolu nad zemljom...
{133403}{133541}kao što je Simon i rekao."
{134739}{134824}Dame biraju. Vi ste na redu, | gospoðe. Idemo, sada.
{134830}{134932}Dame biraju.
{134940}{135103}George, kao tvoja šogorica, | mislim da zaslužujem jedan ples.
{135276}{135361}Tako mi je žao, Annie.
{135366}{135520}Iznevjerio sam te. | - Svi èinimo ono što moramo.
{135526}{135597}Nisi mi rekla | da nosiš njegovo dijete.
{135606}{135718}Ne njegovo. Tvoje.
{135724}{135787}Curica je. Sadie. Sadie Herron.
{135793}{135826}Ali vodit æe se | kao Simonova kæer...
{135834}{135963}tako da ima | pristojno ime u ovom svijetu.
{135972}{136060}Naravno.
{136120}{136243}Znam da æeš se | dobro brinuti za nas, George.
{136252}{136390}Hoæu.
{136400}{136700}{C:$0000FF}{y:ib} d |{C:$FF0000}{y:b} d 
{137778}{137916}
