{1970}{2090}LJUDSKA PRIRODA
{2569}{2661}LiIa, zašto si|to moraIa uèiniti?
{2666}{2750}Hoæe Ii to utjecati|na prodaju tvoje knjige?
{2756}{2796}Je Ii ti žao?
{2802}{2835}Nije mi žao.
{2849}{2884}Meni je žao.
{2906}{2973}Ja više ne znam|što znaèi da mi je žao.
{3097}{3137}Nije mi žao.
{3145}{3217}I provest æu ostatak|života u zatvoru. Pa što?
{3251}{3326}Ionako sam cijeIi život u zatvoru.
{3361}{3444}U zatvoru od krvi, mesa i hormona.
{3472}{3520}U zatvoru zvanom Ijudsko tijeIo.
{3587}{3667}Jedino znam da mi je žao.
{3687}{3748}Žao mi je što sam iskIjuèen.
{3760}{3854}Što moja LiIa|trune u svojoj æeIiji.
{3876}{3925}I žao mi je Nathana.
{3968}{4018}Koji trune u svome grobu.
{4102}{4184}Ja više ne znam|što znaèi da mi je žao.
{4203}{4239}Èudno je.
{4248}{4307}Kad sam bio živ, znao sam.
{4311}{4368}Možda je to biIo|sve što sam znao.
{4376}{4417}AIi ovdje...
{4432}{4477}ŽaIjenje je besmisIeno.
{4494}{4536}Ljubav je besmisIena.
{4562}{4615}Ljubomora je besmisIena.
{4620}{4704}Moja prièa poèinje|kad mi je biIo 12 g.
{4712}{4744}Isuse.
{4752}{4819}Te se godine|dogodiIo nešto grozno.
{4849}{4948}Majka je rekla da zbog toga|nikad neæu pronaæi muškarca.
{4952}{4996}Pa neka se naviknem na to
{5002}{5114}da æu život posvetiti|znanosti, vjeri ili sliènom.
{5887}{5991}HormonaIno je.|Priroda je èudna i zamršena.
{6024}{6088}S vremenom se može pogoršati.
{6099}{6180}Kad sam navršiIa 20 g.,|izgIedaIa sam kao majmunica.
{7993}{8051}Kako me taj miš gledao...
{8058}{8157}Nije ga bilo briga što|imam dlake po cijelome tijelu.
{8188}{8240}BiIa sam što sam biIa.
{8280}{8345}OsjeæaIa sam se tako sIobodna.
{8392}{8456}Shvaæate Ii što govorim?
{8477}{8536}Nešto o mišu, zar ne?
{8580}{8653}MisIim da svatko|na svijetu sada zna
{8657}{8751}da me u divIjini odgojio majmun.
{8756}{8840}Zapravo, èovjek koji|je mislio da je majmun.
{8845}{8932}No svodi se na isto.|gospodo, zar ne?
{8937}{8997}Provevši godine u|mjesnoj umobolnici
{9001}{9078}jer se pokušao smjestiti|u nastambu majmuna u ZOO-u,
{9082}{9153}trudio se živjeti|prema vašim pravilima.
{9158}{9260}Zaposlio se, oženio s|ljudskim biæem, dobili su mene.
{9264}{9349}Sve dok tragedija nije|uništila godine terapije
{9354}{9427}i podsjetila ga|kakva je ljudska rasa.
{9429}{9479}KENNEDY UMOREN
{9483}{9573}Majmuni ne ubijaju|svoje predsjednike!
{9792}{9898}Ukrao je maloga mene|od moje ljudske majke
{9901}{9999}te me odgojio s ljubavlju,|nježnošæu i poštovanjem.
{10048}{10146}Donedavno sam i ja|vjerovao da sam majmun.
{10166}{10243}Iako nisam znao|koja toèno vrsta.
{10248}{10300}Majmuni ne razmišIjaju o vrstama.
{10303}{10395}MogIo bi se reæi da majmuni|i ne znaju da su majmuni.
{10421}{10463}No sada...
{10498}{10551}Rekao bih da sam bio...
{10604}{10632}Èimpanza.
{10925}{10998}Moram reæi da sam|uvijek mrzio majmune.
{11013}{11082}Dakako, više nije tako.
{11088}{11166}Sada više ne znam|što mržnja znaèi.
{11191}{11261}No dok sam bio živ,|mrzio sam majmune.
{11270}{11321}Krivim roditeIje za to.
{11360}{11472}Ne krivim ih. Ne|znam više što je krivnja.
{11487}{11550}No mislim da su utjecali
{11554}{11637}na moju sklonost|mržnji prema majmunima.
{11642}{11706}Mama, vidi, majmun.
{11713}{11806}Nathane, èipmanze su|èovjekoIiki majmuni.
{11826}{11917}Osim toga...|HaroIde, reci deèku.
{11933}{11989}Reci mu, HaroIde.
{12050}{12144}ÈovjekoIiki majmun|naš je najbIiži roðak.
{12152}{12206}Osobito...
{12234}{12273}Èimpanza.
{12279}{12362}RazIikujemo se|samo po jednome kromosomu.
{12371}{12437}No znaš po èemu|se istinski razIikujemo?
{12442}{12499}Ne, tata. Što?|-CiviIizacija.
{12504}{12593}Bez nje, i mi bismo|možda živjeIi u kavezima.
{12597}{12652}NabacivaIi se izmetom.
{12668}{12729}MasturbiraIi u javnosti.
{12733}{12830}NjuškaIi crvene|oteèene ženske stražnjice.
{12878}{12959}Tvoj oèuh i ja|izvukIi smo te od života
{12962}{13071}koji bi sigurno|završio propašæu u aIkohoIu.
{13073}{13202}Ti se nikad ne smiješ|vaIjati u prIjavštini nagona.
{13229}{13292}To može svaka gIupa životinja.
{13296}{13355}Životinja mi je spasila život.
{13358}{13457}Pa sam odluèila|živjeti meðu njima u šumi.
{13463}{13557}Životinje imaju|oèi koje ne osuðuju.
{13980}{14022}PogIedajte svu tu dIaku.
{14026}{14078}Posvuda, posvuda.
{14100}{14140}Na pasancu.
{14144}{14183}Na djetIiæu.
{14187}{14247}Na maznome starome medi.
{14272}{14342}BiIo mi je neugodno zbog dIaka.
{14345}{14410}Nisam biIa za maženje.
{14415}{14508}Sad sam sigurna|da je to bIagosIov.
{14514}{14602}Nemam potrebu za odjeæom.
{14613}{14674}Mislila sam da je Bog
{14679}{14759}Dijabolièan stvoritelj
{14768}{14898}On je odobrio|svaku moju dlaku
{14918}{15010}Od glave do pete
{15087}{15154}Sada sam slobodna
{15161}{15222}Nemam više briga
{15229}{15334}Prihvatila sam|milijune svojih dlaka
{15366}{15437}Moji novi prijatelji
{15441}{15495}Raspucani vrhovi
{15499}{15583}Daleko sam od|užasnutih pogleda
{15640}{15702}Vjevericama ne smeta.
{15707}{15758}A ni gavranima
{15770}{15876}Ako je cura dlakava|ili svježe obrijana
{15903}{15962}Stvorenja su ljubazna
{15970}{16057}Pa sam našla svoje|novo zeleno utoèište
{16062}{16134}l neæu otiæi
{16196}{16257}Jer sam jedna od njih
{16269}{16329}Znate to
{16587}{16662}Smislila sam kako da|zauvijek ostanem u šumi.
{16666}{16738}Postala sam pisac o prirodi.
{16742}{16807}Sinoæ, na svom vrhu planine.
{16811}{16905}osjetila sam kako mi|vjetar fijuèe kroz kosu.
{17017}{17053}Bilo je silovito.
{17099}{17142}Skoro sam poginula.
{17173}{17293}Sve moje brige nestale su|s tim olujnim vjetrovima
{17295}{17376}Bila sam u prirodi,|bila sam priroda.
{17380}{17474}Vidra, roda, stablo hrasta.
{17552}{17582}Žena.
{17609}{17721}Kad sam se proslavila, rekla|sam sebi: Jebeš èovjeèanstvo.
{17725}{17791}Nikad nisam vidjela|svoga izdavaèa ni svoju publiku.
{17796}{17876}Nisam vidjela drugo ljudsko|biæe i bilo je prekrasno.
{17940}{18039}No moram priznati. Navršivši|30 g. bila sam jako uspaljena.
{18045}{18117}Trebala sam|muškarca u životu.
{18441}{18544}Postat æu što moram|postati da bih to postigla.
{18547}{18663}Uspjeh æe mi omoguæiti|da postanem bezdlaka laž.
{18869}{18934}Napredak! -Da? -Da.
{18944}{19072}Dušo, postaješ gIatka,|posvuda, poput djeèje guze.
{19075}{19160}Sviða mi se to, Louise.|Postajem poput prave cure.
{19164}{19236}Još tražiš pravoga|muškarca? -Uvijek.
{19246}{19355}Moj brat poznaje tipa|koji je možda pravi za tebe.
{19358}{19459}Trebam nekog pravog za sebe.|-Ovo je nešto seksuaIno?
{19464}{19573}Zašuti i govori.|-Zgodan, 30 g., psihoIog.
{19576}{19642}VoIi životinje?|Mora voIjeti životinje.
{19645}{19727}VoIi životinje i tebe.|-Kako to misIiš?
{19731}{19834}Nekako smo došIi do|toga da si mi prijateIjica.
{19837}{19906}G. zgodni psihoIog|i IjubiteIj životinja
{19908}{19957}rekao je da|bi te htio upoznati.
{19961}{20018}Zar neæe vidjeti?
{20035}{20124}Moj brat kaže da tip|ima 35 g. i djevac je.
{20129}{20194}Možda neæe znati|kakve su ženske inaèe.
{20196}{20254}Osim toga, i Ioše|vidi, gotovo je sIijep.
{20257}{20308}Što u ovakvim|situacijama pomaže.
{20311}{20383}Osim toga, ima|iznimno maIen penis.
{20386}{20436}I toga se smrtno stidi.
{20439}{20552}Vjerojatno æe biti zahvaIan|što mu posveæuješ pozornost
{20555}{20618}da æe biti zauvijek tvoj.
{20623}{20711}BIizak je s tvojim bratom kad|mu govori tako osobne stvari.
{20714}{20767}Moj je brat njegov psihiæ.
{20777}{20844}Jebeš èovjeèanstvo|bilo je divno štivo.
{20847}{20911}NajIjepša ti hvaIa.|Jako voIim životinje.
{20915}{20965}Ja radim sa životinjama.
{20974}{21044}Sada poduèavam miševe...
{21080}{21154}Ponašanju za stoIom.
{21238}{21292}Kako napreduje?
{21298}{21387}Nadam se da me ne smatraš|gIupim. -O, ne!
{21392}{21479}To je važan rad, dio|šireg socioIoškog pokusa.
{21482}{21551}VIada mi pIaæa troškove.|-Kakav širi pokus?
{21555}{21627}Tvrdim da pristojnost|i Iijepo ponašanje
{21632}{21705}uveIike manjkaju u|našim svakodnevnim odnosima.
{21707}{21764}PrevIadavaju|prostakIuk i vuIgarnost.
{21768}{21831}Zato, uspijem Ii miševe|nauèiti ponašanju za stoIom,
{21836}{21909}moæi æu nauèiti i Ijude,|a uspijem Ii nauèiti Ijude...
{21914}{21966}Možda æu moæi...
{22009}{22084}Postiæi da svijet|bude maIo sigurniji.
{22094}{22186}Bože, hvaIa Ti na|darovima koje æemo primiti.
{22190}{22239}Amen.
{22264}{22328}O, Bože, Nathane, ne!
{22345}{22414}Pogrešna viIica, mIadiæu.
{22425}{22477}HaroIde, reci mu.
{22525}{22574}Pogrešna viIica, Nathane.
{22578}{22658}Žao mi je. Uzet æu|pravu. Zaboravio sam.
{22740}{22771}Reci mu.
{22843}{22933}Prekasno je. Moraš u svoju sobu.
{23134}{23286}MisIite Ii da ta|indoktrinacija u djetinjstvu
{23288}{23409}ima veze s time što vas danas|zanima ponašanje za stoIom?
{23464}{23540}Ne èini ti se da je to|maIo preprikIadno, WendeIIe?
{23543}{23587}Što onda ti misIiš,
{23592}{23665}odatkIe potjeèe ta strast?
{23668}{23731}To je moj posao.
{23737}{23834}Ne možeš to svesti na|roditeIjsku indoktrinaciju.
{23839}{23892}Zašto je Picasso sIikao?
{23895}{23957}Zašto je Mozart skIadao?
{23960}{24077}Picassov otac bio je sIikar.|Mozartov otac bio je gIazbenik.
{24089}{24186}U redu, sada si zIoèest.|Samo se praviš važan.
{24189}{24272}Nisam došao da bi mi se rugao.|-To mi nije biIa nakana.
{24277}{24343}To je moj posao, samo to.
{26319}{26366}Ovo divno izgIeda.
{26377}{26422}Ti divno izgIedaš.
{26497}{26585}Veèeras sam jako sretan, LiIa.
{26591}{26691}Moj rad dobro napreduje,|moj privatan život...
{26771}{26801}ViIica.
{26892}{26929}MoIim?
{26941}{27053}Vanjska viIica|obièno je za saIatu.
{27078}{27136}Ideš izvana prema unutra.
{27142}{27220}Žao mi je. Nikad|nisam uèiIa te stvari.
{27222}{27279}Ništa bitno.
{27302}{27340}Ovo je dobro.
{27351}{27425}Oprosti što sam se uzrujao.
{27434}{27474}Ne, meni je žao.
{27489}{27546}U nekim sam stvarima zaostaIa.
{27552}{27613}Doista uživam u tvome društvu.
{27618}{27681}Doista?|-Da.
{27702}{27734}MoIim te.
{27752}{27859}Nemoj govoriti dok|u ustima imaš hrane.
{27890}{27934}Tako si Iijepa.
{27964}{28061}I to samo umanjuje...|Kritiziram te.
{28238}{28343}Ne mogu vjerovati da sam ti|Iijepa. -Imam èudne osobine.
{28347}{28406}Ja misIim|da si i ti Iijep. -MisIiš?
{28410}{28495}Da, doista. I ja|imam èudne osobine.
{28498}{28542}Nije me briga.
{28580}{28631}Nije?|-Ne.
{28659}{28725}Kakve, na primjer?
{28810}{28857}Recimo... Nikakve.
{29220}{29295}Ne mogu vjerovati koIiko|sam zaIjubIjena u tog èovjeka.
{29299}{29353}Louise, tako je sIadak.
{29355}{29404}Èak i njegov maIeni penis.
{29409}{29507}Kao maIeni svinjski penis|iIi nešto sIièno. Šarmantno je.
{29513}{29608}Uvijek si voIjeIa životinje.|-On æe otkriti, Lou.
{29612}{29689}Divna si žena.|Sretan je što te ima.
{29691}{29795}Louise, govoriš to dok mi|ukIanjaš dIake sa stopaIa.
{29798}{29866}MaIo si fizièki èudna.|Pa što onda.
{29870}{29951}Znaš u što se ja zaIjubim|kod muškarca? U njegov um.
{29954}{30013}Postoje granice.|-Ne, to je to.
{30018}{30096}Kraj reèenice, pasusa,|zatvori knjigu, gotovo je.
{30098}{30164}Daj mi inteIektuaIca|kakav je moj brat.
{30168}{30247}Znam da izgIeda prosjeèno,|no tako je pametan, znaš?
{30251}{30300}Baš me briga kako je upakiran.
{30303}{30374}Ne jebeš se s time.|-Da, jebeš se.
{30379}{30449}Jebeš se s umom.|Jebeš se s umom i toèka.
{30452}{30526}Zatvori knjigu, završi|reèenicu, završi biIo što.
{30530}{30658}Imam pametnog prijateIja|za tebe. Ima IQ 170.
{30661}{30732}Kako izgIeda?|-Predivan je.
{30738}{30794}On je... PatuIjak.
{30825}{30865}Isuse, LiIa.
{30868}{30960}Neæu hodati s jebenim patuIjkom.
{30963}{31019}Što je uopæe ljubav?
{31023}{31120}S novoga stajališta shvaæam|da ljubav nije ništa više
{31124}{31225}od zbrkanog spoja|potrebe. oèaja.
{31228}{31335}straha od smrti i|nesigunosti u velièinu penisa.
{31340}{31397}No, ne osuðujem to.
{31401}{31475}Znam kako je jadno živjeti.
{31539}{31626}Èujte...|Ne žeIim još biti mrtav.
{31648}{31716}Postoji Ii naèin da...
{31771}{31812}HaIo?
{31916}{31972}Ne, vjerojatno nema.
{32049}{32082}Ništa strašno.
{32128}{32179}Kako biIo, LiIa se useIiIa.
{32183}{32226}ImaIi smo svojih probIema.
{32229}{32331}No toIiko smo žeIjeIi Ijubav|da smo oboje zažmiriIi.
{32345}{32426}Recimo prvi put kada sam|doveo LiIu svojim roditeIjima.
{32428}{32502}Drago mi je što sam vas napokon|upoznaIa, g. i gðo Bronfman.
{32506}{32592}Nathan mi je mnogo govorio|o vama. Samo najboIje, dakako.
{32597}{32633}HvaIa, miIa.
{32747}{32836}Oprostite. Bi Ii mi netko|rekao tko je ovaj djeèaèiæ?
{32853}{32960}Tvoj otac i ja|posvojiIi smo još jednoga sina.
{33031}{33105}Wayne se upravo vratio|iz mirovnjaèkoga kampa
{33109}{33151}i iz znanstvenoga kampa.
{33155}{33206}Reci svima što si nauèio.
{33210}{33307}Rješavanje sukoba|i seciranje trakavice.
{33379}{33461}Jako mi je drago što|sam te upoznao, Wayne.
{33465}{33539}Takoðer. Naša mama|mnogo mi je govoriIa o tebi.
{33543}{33627}VoIio bih da|i ja to mogu reæi.
{33638}{33725}Usput, Iakat mu je na stoIu.
{33740}{33809}Dobar deèko.|-To je sve? Dobar deèko?
{33814}{33898}Nathane, ne obraæaj|se majci tim onom.
{33903}{33995}Oprostite, aIi èini mi se da|Wayne treba maIo više disci...
{34000}{34063}Oprosti, mama, ne znam|gdje mi je biIa gIava.
{34066}{34151}Wayne ima priIiènu|samodiscipIinu za svoju dob.
{34153}{34194}Što to znaèi?
{34199}{34259}Èini se da je vrlo|discipIiniran, no pitam se
{34262}{34315}misIite Ii da je to najboIje...
{34318}{34388}LiIa piše o prirodi.|Jeste Ii znaIi to?
{34391}{34434}Piše o životinjama i prirodi.
{34437}{34497}I mnogim drugim|stvarima u prirodi osim toga.
{34501}{34572}Vjetru, životinjama, èemu god.
{34576}{34622}Vjevericama.
{34647}{34695}VoIim prirodu.
{34733}{34841}Dok je u ZOO-u|gdje joj je i mjesto.
{35050}{35110}Mrzim Waynea. Ti ne?
{35148}{35244}Oprosti zbog reakcije|moje majke na tvoj rad.
{35249}{35295}Što radiš ondje?
{35300}{35406}Nije se tako èiniIo. Smijao si se|njezinim gIupim okrutnim vicevima.
{35410}{35495}Samo sam pokušavao|održati raspoIoženje.
{35500}{35567}Znaš da o prirodi|misIim što i ti.
{35573}{35659}Doista?|-Da, voIim je.
{35670}{35732}Je Ii? Doista, dušo?
{35736}{35788}Priroda mi je omiIjena stvar.
{35798}{35871}Tako mi je IaknuIo.
{35920}{36009}ProsIavimo to sutra|dugaèkom šetnjom šumom.
{36018}{36066}Kakva sjajna zamisao.
{36233}{36282}Krema za brijanje?
{36321}{36367}Ne bih rekIa.
{36459}{36488}Zašto?
{36666}{36792}Jednoga dana ugIedao sam nešto|što nisam vidio od oèeve smrti.
{36824}{36876}Vidio sam druge majmune.
{36902}{36965}Brbljali su na|nerazumljivu jeziku.
{36970}{37036}Poslije sam nauèio|da je to engleski.
{37071}{37189}Pitam se je li možda moja|prva procjena bila toèna.
{37481}{37546}VidjeIa sam bjeIinu.|Jesi Ii vidio to?
{37559}{37649}Što?|-Ne znam. Nešto.
{37652}{37678}JeIena?
{37699}{37765}Ne, preuspravan je. Osoba?
{37838}{37928}Možda bi najboIje biIo|da se sada vratimo.
{38045}{38132}Ako je osoba, zašto|bismo je išIi vidjeti?
{38172}{38218}To baš nije priroda.
{38261}{38353}Ljudi koji žive u|šumi ne žeIe biti viðeni.
{38360}{38413}Poštujmo njihove žeIje.
{38539}{38601}Ovako te ugrizu krpeIji.
{38605}{38681}Dobiješ Lajm-boreIiozu.
{38745}{38797}Zaboga, što to...
{39162}{39234}Majmun kakvoga|nikad prije nisam vidio.
{39238}{39294}Poput mene, no drukèiji.
{39311}{39382}l odjednom, osjetio|sam da me prožima vruæina.
{39387}{39462}Htio sam je dodirnuti,|milo vati, sjediniti se s njom.
{39466}{39557}lmao sam potrebe koje|nisam mogao objasniti.
{39650}{39770}Uèinio sam što bi i svaka|druga životinja u toj situaciji.
{39776}{39821}Pobjegao je!
{41388}{41438}Tko si ti?
{41557}{41637}Ne razumiješ|moj jezik, zar ne?
{42343}{42386}PogIedaj što si uèiniIa.
{42390}{42433}Je Ii mrtav?|-Nije.
{42436}{42500}MoIim te, odjeni se.|MogIa bi se prehIaditi.
{42510}{42598}MisIiš da je zaIjubIjenik u|preživIjavanje? -Ne, divIji je.
{42602}{42680}DivIji? Ne diraj ga.|Mogao bi biti zaražen.
{42685}{42729}Možda... Bože, bjesnoæa.
{42748}{42815}IzgIeda u redu.|-MisIim da trebamo poæi.
{42820}{42888}Ne shvaæam te.|Ovo je fascinantno.
{42891}{42970}Ovo je Ijudsko biæe|nezagaðeno civiIizacijom.
{42975}{43048}A ti samo žeIiš|pobjeæi u auto. -Èekaj.
{43120}{43170}Poèinješ mi iæi na živce.
{43175}{43273}Zaboravi miševe, zamorèiæe,|maèke. I majmune.
{43288}{43369}PreIazim na peti|stadij s Ijudskim biæem.
{43420}{43496}Mogu ga promijeniti.|Mogu ga poduèiti.
{43499}{43580}Mogu ovome nesretniku spasiti|život. -Neæu ti dopustiti.
{43585}{43637}Pogrešno je. Sretan je tu.
{43641}{43674}Sretan? Je Ii sretan?
{43678}{43741}Nikad neæe znati kako|je kad te žena voIi.
{43744}{43808}Neæe èitati Moby Dicka.|Neæe se diviti Monetu.
{43867}{43935}Oduzeo bi mu sIobodu.
{43954}{44055}SIoboda je samo drugi izraz|kad nemaš ništa izgubiti.
{45043}{45071}Doktore?
{45304}{45348}Dobro jutro.
{47063}{47151}Samo tri udara.|Èimpanzi je potrebno 15.
{47154}{47237}Ovo æe biti tres|jednostavno, zar ne, Gabrielle?
{47246}{47286}Dobro jutro.
{47313}{47378}Moramo mu|dati ime, zar ne?
{47434}{47502}Ti odIuèi. Danas je tvoj dan.
{47512}{47574}Doista? Moj dan?
{47581}{47714}Kad sam biIa maIena, imaIa|sam psa mješanca Puffa.
{47758}{47861}Podsjeæa me na mog psa.|Tako je dIakav i sIadak.
{47889}{47964}Jako sam voIjeIa|svoga psiæa, gospodine.
{47966}{48009}Onda neka bude Puff.
{48013}{48070}Puff Bronfman, može?
{48073}{48145}Dobro jutro, Puff Bronfman.
{48148}{48202}Ja sam dr. Bronfman.
{48206}{48284}A ovo je moja pomoænica GabrieIIe.
{48311}{48395}Dok budeš bio ovdje,|mi smo ti tata i mama.
{48402}{48480}ŽeIiš Ii saIate, sine?
{48529}{48578}Dr. Bronfman!
{48586}{48626}Bok, GabrieIIe.
{48658}{48781}Samo sam vam htjeIa reæi|da uživam radeæi s vama.
{48811}{48868}Sad mi je neugodno|što sam to rekIa.
{48871}{48950}Ne mora ti biti. BiIo mi|je drago što sam to èuo.
{48953}{49003}Sjajna si pomoænica.
{49011}{49066}HvaIa.
{49087}{49122}Biste Ii...
{49129}{49222}ŽeIite Ii možda da|odemo popiti kavu?
{49307}{49410}Ne znam.|Zapravo sam na putu...
{49415}{49476}Sad mi je doista neugodno.
{49507}{49605}Oprostite, nisam trebaIa|postaviti tako gIupo pitanje.
{49610}{49663}Znam da ste važan èovjek.
{49666}{49706}Ne budi smiješna.
{49712}{49755}Tako ste dragi.
{49943}{49973}Žao mi je.
{50004}{50044}Dobro, dobro.
{50056}{50144}Znate što mi trebate reæi.
{50150}{50253}Vidimo se sutra.|Osim ako nisam otpuštena.
{50266}{50326}Nisi, ni govora!
{50409}{50477}VoIim kako izgovarate moje ime.
{50482}{50531}Je Ii to gIupo?
{50672}{50708}HaIo?
{50732}{50790}Zdravo, GabrieIIe.
{50824}{50881}Tko je to?|-Da, GabrieIIe.
{50925}{50990}Tko je to?|-Netko s posIa.
{51036}{51100}Ispravno si preuzeIa inicijativu.
{51107}{51175}To pokazuje da si mudra.
{51191}{51246}Doista?|-Tko s posIa?
{51272}{51330}Možeš maIo prièekati?
{51386}{51436}Tko je to, Nathane?
{51443}{51513}Razgovaram o posIu i...
{51644}{51688}HormonaIno je.
{51694}{51734}Ne mogu si pomoæi.
{51740}{51790}Cijelo tijelo?
{51794}{51896}ldem na elektrolizu. Treba|vremena. U meðuvremenu se brijem.
{51901}{51960}Moraš se brijati kao majmun.
{51966}{52025}Majmuni se ne|briju, pasji skote!
{52029}{52074}Ne cjepidlaèi.|Znaš što mislim.
{52078}{52168}Ne ljuti se na mene.|-Ne ljutim se. Gadi mi se.
{52172}{52223}lsta sam osoba kakva sam bila.
{52227}{52293}Moram razmisliti. Moram iæi.
{52298}{52330}O, Bože!
{52404}{52471}O, moj Bože.
{52548}{52589}Halo? lma li koga?
{52828}{52882}Divan dan, zar ne?
{52914}{52988}Ne, hvala. Ne mogu|više pojesti ni zalogaj.
{53016}{53086}Drago mi je|što smo se upoznali.
{53109}{53193}lsprièavam se.|Neæe se ponoviti.
{53212}{53254}Pohvalite kuhara.
{53258}{53340}ldiopatska dlakavost javlja|se kod žena koje imaju dlake
{53344}{53433}pojaèano osjetljive na|normalne razine androgena.
{53439}{53479}Divno izgledate.
{53529}{53585}Kako sam se našao u ovoj zbrci?
{53596}{53647}Je Ii moja|djevojka muško? Nije.
{53651}{53740}AIi ona je dIakava.|A ne bi smjeIa biti.
{53756}{53846}Doktore, nisam znaIa.|Oprotite što smetam.
{53851}{53928}DošIa sam po papire|koje sam ostaviIa.
{53935}{54031}Oprosti što sam te prepao.|Došao sam za sI...
{54098}{54170}Gospode!|Spustio sam ti sIušaIicu?
{54173}{54226}Možda sam zvaIa|u pogrešan trenutak.
{54230}{54310}Žao mi je.|-I meni. Bio sam rastresen.
{54314}{54365}Je Ii sve u redu?
{54390}{54460}Poèeo sam govoriti francuski.
{54464}{54540}BiIa sam u pidžami|kad sam se sjetiIa
{54545}{54612}da sam ostaviIa neke|papire koje moram proæi.
{54617}{54678}Vidite? IzjuriIa|sam ravno iz kuæe.
{54682}{54746}IzgIedam neuredno.|-Ne, ni govora.
{54750}{54824}I ja sam u pidžami.|Èudno, zar ne?
{54907}{54943}Kako je naš sin?
{55022}{55081}MoIim?|-Naš sin?
{55187}{55266}Èini se da je dobro.|ProbudiIi smo ga.
{55271}{55328}SvjetIa.|-Trebam ih ugasiti.
{55443}{55601}Otpjevat æu mu uspavanku koju mi|je mama pjevaIa kad sam biIa maIa.
{55606}{55663}Kad si biIa|maIa Francuskinja?
{55666}{55718}Dakako, Iudice.
{55724}{55784}MogIa bi ga utješiti.
{55805}{55862}Ako to èuje.
{56878}{56941}Tako.|Hoæemo Ii zatvoriti?
{57064}{57104}Ne bih ovo smio reæi, no...
{57126}{57186}Jako si Iijepa, GabrieIIe.
{57190}{57284}Doista? Sebe uvijek|vidim tako ružnu.
{57308}{57386}Ne ružnu, aIi obiènu, praznu.
{57403}{57497}Jako si Iijepa. Trebaš|to znati. Budi samouvjerena.
{57501}{57549}NajIjepša hvaIa.
{57589}{57678}Lijepo je èuti takav|kompIiment od muškarca.
{57683}{57730}Istina je. Ne bih Iagao.
{57736}{57801}Dragi ste prema meni.
{57898}{57949}Tako meko.
{57953}{57987}Doktore.
{57993}{58041}Žao mi je.
{58407}{58504}Još...
{58563}{58605}DIaka.
{58980}{59042}Vidio sam to, gospodo.
{59051}{59091}CijeIi taj znojan
{59095}{59181}strastven, gadan divan èin.
{59204}{59258}I da se sIobodno izrazim.
{59275}{59361}I ja sam htio maIo toga.
{59489}{59586}MisIim da sam od|toga trenutka shvatio
{59594}{59657}žeIim Ii to dobiti
{59661}{59717}moram igrati njihovu igru.
{60345}{60396}Sjajno, Puffe.
{60449}{60574}Dama s kojom si, isprièa se|jer mora iæi napudrati nos.
{61044}{61081}Savršeno, Puffe.
{61102}{61146}Bravo.
{61442}{61506}Još osjeæam krivnju, i mrtav.
{61547}{61593}Èovjek se nada da...
{61692}{61747}Doista sam voIio LiIu.
{61823}{61905}Samo što je njezin probIem...
{61926}{61994}I kad je GabrieIIe|otkriIa svoje osjeæaje...
{62011}{62106}BiIa je previše|konvencionaIna ženska.
{62136}{62179}ImaIa je taj nagIasak.
{62201}{62271}Bio sam izgubIjen.
{62366}{62422}Viðaš Ii se s kim drugim?
{62424}{62503}Oprosti što pitam,|no osjeæam da moram znati.
{62514}{62586}Ni govora.|-PomogIo bi da znam.
{62623}{62728}Jer u posIjednje si|vrijeme tako udaIjen.
{62760}{62827}Radiš do kasno naveèer,|gotovo se više i ne seksamo.
{62831}{62892}A kad èinimo to, tako je...
{62915}{62944}Drukèije.
{62950}{63023}Samo imam toIiko toga na pameti.
{63078}{63133}Sviða ti se novi izgIed?
{63266}{63332}Lijepo je.|-Doista?
{63360}{63461}Trudim se, znaš. Trudim|se da budem ono što žeIiš.
{63465}{63571}ŽeIim biti što ti žeIiš.|Samo žeIim biti što ti žeIiš...
{63606}{63665}Ti si baš ono što žeIim.
{63669}{63693}Doista?
{63696}{63744}Svakako.
{63754}{63793}Dakako.
{63811}{63939}Trudim se. Louise kaže da su|mi ostaIe još 2 g. eIektroIize.
{63943}{63983}Sjajno.|-Da.
{63988}{64103}PrijaviIa sam se na baIet. Vidi|mi nokte. Kao kod prave cure!
{64117}{64186}Ta ti boja sjajno stoji.
{64198}{64279}Nathane, napravimo dijete.
{64604}{64650}To je moja mora.
{64653}{64766}I nikako ne mogu|shvatiti o èemu je rijeè.
{64812}{64868}MisIim da je rijeè o LiIi.
{64875}{64928}O LiIi? Kako?
{64931}{65026}Otkako je spomenuIa|djecu, tako si napet.
{65030}{65108}Znam da imaš probIema|s njezinom dIakavošæu.
{65112}{65187}Shvaæam.|O tome trebam razmisIiti.
{65190}{65268}Smatrao sam da više ima|veze s odgojem djeteta.
{65272}{65346}Dijete majmun predstavIja|roditeIjsku odgovornost.
{65350}{65438}Važno je da razmisIiš o|svojim osjeæajima prema LiIi.
{65443}{65484}VoIim LiIu.
{65487}{65551}Divna je i ona voIi mene.
{65561}{65620}To nije sitnica.
{65653}{65706}Ona je dobra osoba.
{65717}{65784}To je danas rijetkost.
{65848}{65911}Kako mogu prestati voIjeti nekoga
{65915}{65994}zbog maIene|fizièke nesavršenosti?
{65999}{66083}Ako se to može i tako nazvati.
{66089}{66157}Što osjeæaš prema GabrieIIe?
{66229}{66308}Dobra ve-èer,
{66318}{66380}da-me
{66389}{66499}i gos-po-do.
{66584}{66682}Dobra veèer,|dame i gospodo.
{66742}{66799}Bravo, Puffe.
{66806}{66877}Ne napreduje Ii|Puff spektakuIarno, miIa?
{66881}{66939}Nathane, moramo razgovarati.
{67077}{67121}Moja francuska pudIice.
{67124}{67179}Prestani. Makni se.|-Što?
{67186}{67238}Moraš izabrati, Nathane.
{67242}{67330}To je kao Sophijin izbor,|samo što je ovo Nathanov izbor.
{67334}{67392}Jesi Ii gIedao fiIm|Sophijin izbor?
{67396}{67484}Isto je tako samo što je ovako.
{67510}{67573}Pokušavam sve riješiti.
{67577}{67657}Ne, sada moraš odIuèiti!
{67683}{67752}VoIim te, dr. Nathane.
{67833}{67877}AIi neæu èekati.
{67881}{67936}Neæu biti tvoja fufica.
{67940}{68031}Tvoja gospodièna.|Tvoj komad sa strane.
{68067}{68113}ŽeIim imati
{68116}{68202}sIatko maIeno dijete
{68205}{68275}u svome trbuhu.
{68293}{68351}Tvoje.
{68686}{68755}Tako te jako voIim, GabrieIIe.
{68761}{68802}AIi...
{68808}{68887}Osjeæam ''aIi'', Nathane!
{68946}{69020}Ne znam kako da napustim LiIu.
{69192}{69241}Zbogom, Nathane!
{69315}{69362}Tako sam sretna!
{69368}{69460}Znam da æe sve biti divno!
{69571}{69600}Voila.
{69695}{69727}HvaIa.
{69885}{69935}Kako je na posIu?
{69947}{70004}Odurno. ZadovoIjna?
{70073}{70140}Neæu da ti posao bude oduran.
{70227}{70271}Oprosti.
{70293}{70361}Moj pomoænik dao je otkaz.
{70379}{70451}Bio je jako važan za projekt.
{70478}{70541}Dušo, žao mi je.
{70573}{70624}Možeš Ii naæi nekog drugog?
{70627}{70679}VaIjda. Nema veze.
{70706}{70798}Ja mogu doæi raditi za tebe.
{70806}{70903}Znam da ti nisam davaIa|potporu, no promijeniIa sam se.
{70908}{70945}To je divan projekt.
{70949}{71016}Uzeo si ono|jadno neciviIizirano biæe
{71019}{71084}i pretvaraš ga|u Ijudsko biæe.
{71088}{71169}Drag si i suosjeæajan èovjek.
{71174}{71225}ProdaIa sam jebenu dušu.
{71230}{71295}Dopustio sam da proda dušu.
{71297}{71348}Nisam je pokušao sprijeèiti.
{71352}{71403}To je neoprostivo.
{71406}{71488}U to sam vrijeme misIio|da æe to biti dobro za nju.
{71490}{71569}Kad je došIa raditi s|Nathanom, doimaIa se drukèijom.
{71573}{71644}Ne znam, kao bez duše.
{72499}{72532}Bravo!
{72645}{72703}Bravo za tebe, Puffe.
{72815}{72869}Ukroti me, dragi.
{72876}{72978}Ukroti svog|maIog majmunèiæa Ijubavi!
{73077}{73162}Ukroæena sam, dr. Bronfman.
{73166}{73223}Drago mi je.
{73237}{73291}Pomoænice moja.
{73862}{73883}HvaIa.
{73977}{74077}Danas æu poèeti gusjom paštetom.
{74579}{74671}Uzdignut do vrhunca|kulture i profinjenosti.
{74675}{74809}Ovo je neprocjenjiv dar za|mene od dr. Nathana Bronfmana.
{74814}{74861}MisIim da je spreman.
{74866}{74941}Ajoj.|-Ajoj.
{74944}{75024}Puffe, eIektrièna|ogrIica ostaje na tebi.
{75029}{75101}MisIim da neæeš trebati|udare, aIi za svaki sIuèaj.
{75105}{75162}U redu, pošteno.
{76106}{76172}Èestitam.
{76212}{76256}O, hvaIa.
{76270}{76314}Ne, Puffe, zIoèesti!
{76513}{76570}Isprièavam se, gospoðo.
{76573}{76667}U redu je, Puffe.|-Neæe se ponoviti.
{76814}{76849}Hoæemo Ii?
{77885}{77963}Ovo je sjajno, Puffe.|Divno ti ide.
{77996}{78091}Uživam u ovome.|Krasno je biti vani.
{78105}{78186}Kakav je grad divan izum.
{78224}{78320}GoIeme zgrade od stakIa i èeIika|bIješte na podnevnome suncu.
{78324}{78415}Otmjeno odjevene žene u|najboIjim Ijetnim opravama.
{78419}{78484}ŠaroIiki uIièni prodavaèi.
{78501}{78545}Kakva je hrana?|-SpektakuIarna.
{78549}{78620}Losos je divan.|Morate mi dati recept.
{78624}{78666}Svaka èast kuharu.
{78670}{78733}Drago mi je da vam je u|sIast. Kuharu æe biti jako...
{78738}{78777}MoIim vas.
{78796}{78823}Ne!
{78980}{79030}Bi Ii to biIo sve?
{79036}{79107}Neæe se ponoviti, kunem se.
{79112}{79172}Navikavam se, shvaæate?
{79175}{79252}To je životinjski poriv.|Nemaš se èega sramiti.
{79256}{79318}Reci mu.
{79365}{79461}Moraš se kontroIirati.|Mi nismo majmuni.
{79892}{79947}Fino. Dobro nam ide.
{80075}{80136}Jako Iijepo. ZadovoIjan sam.
{80292}{80335}Izvrsno.
{80465}{80508}Super.
{80760}{80798}ZIoèesti Puff.
{80847}{80884}Guzica.
{81685}{81776}Sjajno, Puffe. Veèeras|dobiješ dodatni desert.
{81781}{81850}Sutra je živi pokus.
{82120}{82222}Zdravo, kako ste danas?|-Sjajno, hvaIa.
{82230}{82326}Fino. Što vam mogu donijeti?|-Puffe, daj ti naruèi prvi.
{82367}{82416}Što je Reuben?
{82420}{82473}MoIim, dušo? Reuben?
{82477}{82551}To je sendviè s|govedinom i kiseIim zeIjem...
{82556}{82622}Dobro! To æu. Govedina|je pristojno meso.
{82626}{82694}Može Ii sada netko drugi?
{82809}{82918}Ponosim se tobom. Bio si|sjajan u teškim okoInostima.
{82922}{82967}ApsoIutno.|-Jesam Ii?
{82972}{83033}Trudio sam se.|Doista sam se koncentrirao.
{83038}{83072}Tako sam sretan.
{83079}{83162}Zato što je tako dobro prošIo,|imamo maIeno iznenaðenje za tebe.
{83165}{83231}Dodatno sIatko?|-Još boIje.
{83340}{83387}Iznenaðenje!
{83848}{83926}Možeš odIaziti i|doIaziti kad te bude voIja.
{83939}{84052}U Iadici noænog ormariæa|imaš i novca za Iudovanje.
{84059}{84106}To je divno!
{84131}{84207}MisIite da sam|spreman? Doista?
{84211}{84308}Vjerujem da æeš donositi|dobre i zreIe odIuke.
{84312}{84389}Vjerujem da æeš|postupiti ispravno.
{84455}{84587}Vaše povjerenje probudiIo je|u meni osjeæaj odgovornosti.
{84590}{84658}Ne žeIim vas|razoèarati. -Dobro.
{84662}{84742}Kad si u nedoumici, ne èini|ništa što bi doista žeIio.
{84747}{84790}To je kIjuè.
{84805}{84842}Može.
{84869}{84915}Oprosti, miIa.
{85015}{85116}Kad su neke stvari poznate|i kad je jedna uroðena
{85121}{85184}ili je udaljena
{85215}{85323}ako se odnosi na nešto,|um to smjesta spoznaje
{85327}{85416}samim shvaæanjem|tih jednostavnih stvari.
{85420}{85508}Bez obzira na to|je li to uroðeno ili nije...
{85619}{85702}Idem do Puffa,|vidjeti kako se drži.
{85706}{85772}Da idem i ja?|-Ti se samo opusti.
{85778}{85840}Kakva je knjiga?|-Dobra.
{85863}{85924}Neæu dugo.
{86088}{86174}Zaboravi. Možda ostanem|ovdje i opet se oroIjam.
{86177}{86248}Otmjena zamisao|-Bar ti proðe vrijeme.
{86252}{86290}Èula si za Emmu?
{86296}{86367}Da, što je?!|-Nathan je.
{86374}{86425}Naletjela je|na bivšeg deèka...
{86428}{86466}Nazovem te.
{86556}{86623}Gade! Što žeIiš?
{86628}{86678}Htio sam razgovarati.
{86683}{86763}Donio si svoju odIuku,|g. SmrdIjivi Amerikanèe.
{86766}{86837}Moram ti nešto reæi.|-Što?
{86841}{86932}MisIim da bi biIo Iakše|ako razgovaramo Iicem u Iice.
{86935}{86959}Zašto?
{86967}{87016}MisIim...|-Previše misIiš.
{87020}{87099}Tvoje je srce veIika|stvar s previše ''misIim'' u sebi.
{87104}{87171}Puno je. ToIiko|da nemaš o èemu misIiti!
{87176}{87237}MoIim?|-Èuo si me!
{87240}{87388}ZIo mi je kad se pretvaraš da|ne razumiješ što ti govorim.
{87392}{87442}OdIazi odavde!
{87457}{87510}Dobro. Vidi...
{87547}{87613}Oprosti što sam smetao.
{87619}{87710}U redu! Uði ako moraš!
{87714}{87796}Vrata su otvorena, kurvin sine!
{88091}{88154}Ovdje, ušIjivo govno jedno.
{88439}{88467}Onda?
{88471}{88553}Bože, divna si.|-MoIim te, grozno izgIedam.
{88565}{88619}Ne, tako si divna.
{88623}{88681}Svejedno. Prijeði na stvar.
{88693}{88756}Napustit æu LiIu.
{88763}{88843}Ne mogu prestati|misIiti na tebe.
{88846}{88887}Ja sam preboIjeIa to.
{88892}{88967}VoIim te, GabrieIIe.
{89020}{89118}Samo mi daj maIo vremena|da nježno prekinem s LiIom.
{89123}{89230}Doista je draga. Ne žeIim je|povrijediti više nego što moram.
{89233}{89299}Mene si povrijedio, znaš.
{89303}{89373}Kad si donio Nathanov izbor.
{89378}{89491}Je Ii ti to uopæe|važno, svinjo jedna?
{90025}{90068}Dugo te nije biIo.
{90072}{90185}Puff i ja zapIeIi smo|se u fiIozofsku raspravu.
{90200}{90323}Dobro je naèitan, iako|zna èitati samo mjesec dana.
{90338}{90392}Doista æe nas prosIaviti.
{90397}{90447}Znaèi, on je dobro? -Jest.
{90452}{90483}Jako dobro.
{90486}{90594}Mirno provodi veèer|uživajuæi u novome domu.
{90605}{90691}Èudno, jer ja sam|baš biIa pokupiti ga
{90694}{90754}iz bordeIa na|istoènom kraju grada.
{90757}{90812}Nazvao je kad je|potrošio sav svoj novac.
{90816}{90920}Opijao se, gIedao|striptiz i jebao kurvu.
{90924}{90990}Što si ti|veèeras radio, miIi?
{90995}{91030}Sranje.
{91031}{91098}Što si radio veèeras, miIi?
{91148}{91224}ZaIjubIjen sam u drugu, LiIa.
{91226}{91307}Što si veèeras radio?|-Ševio sam je, u redu?
{91346}{91431}Znaš èega sam se|odrekIa da bih biIa s tobom?
{91434}{91491}OdrekIa sam se svoje duše!
{91496}{91603}Svojih uvjerenja!|Svojih dIaka!
{92039}{92106}I da ne duIjimo.
{92111}{92200}PredstavIjam vam|dr. Nathana Bronfmana i Puffa.
{92290}{92352}HvaIa. Prijeðimo na stvar.
{92476}{92574}Ovo je Puff na|dan kad je uhvaæen.
{92962}{93011}Neæu posIugu!
{93014}{93130}Ne znate proèitati jebeni znak|"Ne smetaj" koji visi na kvaki?
{93135}{93179}LiIa, Louise je.
{93187}{93246}Odjebi, Louise.
{93249}{93344}Reæi da me odveo od|drvenih bojica do parfema
{93347}{93411}biIo bi premaIo reèeno.
{93416}{93491}Dr. Bronfman odveo me od|igranja vIastitim izmetom
{93497}{93542}preko drvenih bojica
{93548}{93600}do shvaæanja|sIoženih radova
{93605}{93710}Franza KIinea, Josepha|Beuysa, MarceIa Duchampa,
{93715}{93772}od kompuIsivne masturbacije...
{93777}{93842}Ovo sam ja, Louise.
{93846}{93894}Ovako izgIedam.
{93898}{93970}Ovo sam ja i više|se ne žeIim pretvarati.
{93973}{94101}PonudiIa sam ti eIektroIizu|jer samo to mogu ponuditi.
{94103}{94201}AIi žeIim što god|tebe èini sretnom, OK?
{94205}{94266}Usreæuje Ii te ovo?|-Ne.
{94283}{94371}Zašto mi ne daju da budem sretna?
{94400}{94475}Ne znam što da radim.
{94500}{94553}Ne znam...
{94581}{94639}I ubiIa sam Puffa.
{94652}{94701}Nisi. Puff nije mrtav.
{94705}{94824}Na neki naèin jest i na neki|naèin jesam. -Što to govoriš?
{94828}{94871}Doði doma sa mnom.
{94876}{94976}Sredit æu te. Radit æu|non-stop dok ne bude gotovo.
{94979}{95067}I zato Iaku noæ, adieu...
{95071}{95113}Do iduæeg susreta.
{95119}{95174}Au revoir.
{95386}{95467}Bio si divan.|-Jesam? Nisam bio ukoèen?
{95469}{95533}Ne budi Iuckast.
{95537}{95628}A ti... I ti si bio divan.
{95632}{95716}Osobito mi se svidjeIo|kad si rekao au revoir.
{95731}{95827}Doðite, vas dvoje.|Idemo prosIaviti.
{96222}{96308}To je Iijepo. Moje je ime Puff.
{96523}{96587}A sada tango.
{97041}{97142}Danas je super prošIo.|Vas dvoje ste sjajan par.
{97153}{97201}Fantastièno.
{97819}{97945}Biti izvuèen iz dubina|zakinutosti i neznanja
{97949}{98063}i uzdignut do visina|kuIture i profinjenosti.
{98098}{98160}To je neprocjenjiv dar
{98164}{98284}koji mi je dao|dr. Nathan Bronfman.
{98639}{98672}Gotovo.
{99118}{99216}Imamo 17 novih poziva,|moj divni èovjeèe.
{99220}{99251}Super.
{99257}{99335}Svi æemo biti bogati i sIavni.|-ZahvaIjujuæi tebi, Nate.
{99341}{99454}ZahvaIjujuæi tebi, tvojoj|marIjivosti, pameti, upornosti...
{99473}{99539}I dakako tebi,|sIatkice, zbog tvoje...
{99559}{99604}MoraIne potpore.
{99611}{99641}Da, da!
{99645}{99724}Pardon. Dr. Bronfman?
{99756}{99815}To je djeèaèiæ?
{99825}{99890}Ne, Puffe, to je patuIjak.
{99896}{99972}Draže im je da ih zovu|maIi Ijudi, nije Ii tako?
{99976}{100069}Meni je draže kad me|zovu dr. EdeIstein.
{100100}{100206}Dr. EdeIstein je odrastao|èovjek, vjerovao iIi ne.
{100212}{100249}Zbog genske anomaIije...
{100253}{100305}AkondropIazije...
{100311}{100392}Zbog toga je|minijaturno Ijudsko biæe.
{100410}{100451}ZanimIjivo.
{100468}{100522}Što možemo uèiniti za vas?
{100528}{100637}Prvo, možete uæi u|taj smiješni stakIeni kavez.
{100668}{100709}Ti ne.
{100740}{100794}O èemu je rijeè?
{100800}{100841}Nemamo novca ovdje.
{100847}{100998}Ako ste iz teroristièke skupine|maIih Ijudi iIi akondropIazièara,
{101002}{101057}znajte da dajem punu potporu...
{101061}{101142}Poèinjete me|umarati, dr. Bronfman.
{101245}{101305}Iznenaðen, srdašce?|-Ovo je LiIa?
{101310}{101380}Da, ovo je LiIa, pièko.
{101389}{101439}Amerikanka i ponosi se time.
{101469}{101552}DIake su nestaIe,|Nathane, sve je sreðeno.
{101557}{101647}Sada sam i mišiæava i svaki|me dan na uIici gIedaju.
{101652}{101684}Predivna si.
{101689}{101760}ŽeIiš Ii me dodirnuti?|-Da.
{101763}{101800}Jadnik.
{101807}{101852}HvaIa, Frank, najboIji si.
{101855}{101906}Sve za tebe, draga moja.
{101911}{101997}Frank i ja znamo kako je kad|te izbjegavaju zbog izgIeda.
{102002}{102126}Tjerati Ijude da preziru|sami sebe pravi je pakao.
{102131}{102187}Andre MaIraux.|-Amen.
{102349}{102403}Oprosti. Ovdje je|nemoguæe naæi parking.
{102408}{102467}Imate mjesta|druge strane uIice.
{102471}{102501}Da, našIa sam.
{102504}{102572}Na TiItonovoj.|Ne možete promašiti.
{102576}{102638}Pokraj Veteranske boInice.
{102641}{102716}Rado æemo vam|potpisati potvrdu.
{102833}{102909}Veži ih.|-Sa zadovoIjstvom.
{102929}{102995}U redu, Fifi, daj mi ruke.
{104244}{104277}Èekaj tu.
{105379}{105416}ZIoèesto.
{105470}{105500}Ustani.
{105625}{105648}Stani.
{105702}{105739}Svuci odjeæu.
{106513}{106543}Hajde.
{106641}{106678}SvIaèi.
{106893}{106954}Ti i ja vraæamo se prirodi.
{106958}{107013}Iznova æu te trenirati.
{107025}{107097}Ponovno æu te osIoboditi.
{107101}{107157}AIi sada voIim biti èovjek.
{107232}{107291}ŽeIim biti kakav sam bio prije?
{107295}{107315}Dobro.
{107330}{107378}Pokazat æu ti kako.
{107383}{107452}Tako je poèeIo moje|ponovno obrazovanje.
{107469}{107528}LiIa me nauèiIa toIiko toga.
{107541}{107610}BiIa je stroga,|aIi poštena uèiteIjica.
{107625}{107737}Poèeo sam se sjeæati radosti|života u èistome stanju.
{107765}{107817}No dogodiIo se još nešto.
{107846}{107907}Nešto možda potpuno Ijudski.
{108220}{108290}Odavde izgIedaš tako dobro.
{108295}{108327}Oprosti.
{109397}{109457}Veèeras izgledaš divno.
{109461}{109516}Zdravo, moje je ime Puff.
{109934}{110014}ŽeIiš Ii me dodirnuti, Nathane?
{110161}{110249}MisIim da nešto nije u redu|s Nathanom. -Vjerujem da nije.
{110261}{110356}Promijenio si se. Mijenjaš|raspoIoženje. Imaš napade bijesa.
{110359}{110465}Kad vodiš Ijubav sa mnom,|kao da si s nekim drugim.
{110485}{110574}Dok vodimo Ijubav,|gotovo me i ne pogIeda.
{110639}{110722}Ja te ne bih prestao|gIedati da si moja cura.
{110727}{110815}Majko, reci Wayneu da se|prestane upucavati mojoj curi.
{110819}{110881}On ima 6 g., Nathane.
{110887}{110945}Upucava joj se.|To nije upucavanje?
{110949}{110991}Nitko se nikomu ne upucava.
{110995}{111096}Možda od brata možeš nauèiti|kako se postupa sa ženama.
{111101}{111170}Više me ne voIiš iIi što je?
{111175}{111244}Reci mi smjesta!
{113114}{113154}Kao što sam i sumnjao.
{113161}{113203}SiIazite sa stabIa.
{113223}{113249}MoIim te.
{113257}{113335}To je|najartikuIiranije što znaš?
{113347}{113429}Nakon što sam potrošio|toIiko vremena da te nauèim.
{113432}{113508}Zaboga, razgovaraIi|smo o Wittgensteinu.
{113513}{113616}Ne kažem da si imao|reæi što pametno o temi.
{113785}{113877}Bez brige, LiIa,|došao sam samo zbog Puffa.
{113915}{113970}Sada imam GabrieIIe.
{113996}{114038}Ona je divna cura.
{114042}{114124}Nije znojna i smrdIjiva.
{114154}{114223}Požudna cura.
{114316}{114367}Smijem te dodirnuti?
{114376}{114428}Samo te pomirisati.
{114438}{114493}Kako sada mirišeš.
{114505}{114565}PrIjavo i moæno.
{114580}{114649}MoIim te, pouèi i|mene kako da budem majmun.
{114652}{114698}MarIjivo æu uèiti.
{114701}{114767}Vidiš, vježbao sam.
{114784}{114873}Još mi ne ide najboIje.
{114878}{114925}AIi vidi.
{114937}{114986}Trudim se.
{115392}{115501}Spusti pištoIj.|Budimo razumna Ijudska biæa.
{115517}{115584}Ti i LiIa ostanite i|živite prirodnim životom.
{115587}{115631}Idem. Više me neæete vidjeti.
{115635}{115678}Ja nisam majmun.
{115718}{115764}Mogu govoriti? Moram.
{115887}{115927}Zdravo, Nathane.
{115945}{116038}Drago mi je što te vidim.|Objasnit æu ti svoj poIožaj.
{116075}{116153}Prije nego što si me našao, bio|sam jednostavno potpuno biæe.
{116156}{116196}U skIadu sa svojim svijetom.
{116201}{116270}PosIije tebe postao|sam dvoIièan, anaIan.
{116273}{116348}Nepovezan sa svojom okoIinom.
{116357}{116446}Jednom rijeèju,|Nathane, postao sam ti.
{116488}{116582}LiIa me ponovno|upoznaIa sa samim sobom.
{116653}{116691}Zdravo, LiIa.
{116719}{116772}VoIim te i poštujem.
{116777}{116830}Spusti pištoIj.|-MoIim te!
{116843}{116897}Ne prekidaj me.
{116926}{116986}Kako si samo nepristojan.
{117021}{117104}Rijeèi.
{117245}{117289}Rijeèi su zIo.
{117309}{117391}Nisu Ii zIo te|rijeèi koje rabimo?
{117410}{117503}Zna Ii tko definiciju|simultanagnozije?
{117505}{117573}Baš sam htio pogIedati pije|nego što me LiIa spasiIa.
{117577}{117662}To je nesposobnost uviðati|eIemente kao dio cjeIine.
{117665}{117743}HvaIa. Drago mi je. Nema na|èemu. Lijepo te opet vidjeti.
{117746}{117781}Prestani!
{117786}{117841}Sad sam zbunjen.
{117864}{117963}Ništa nije kako treba.|Moram pronaæi smisao.
{117976}{118045}Moram pronaæi smisao!
{118185}{118234}Uzrujan si.
{118245}{118312}Ja govorim! Ja!
{118337}{118402}Ne ti! Ja!
{118405}{118458}Ja govorim.
{118468}{118506}Ja pjevam
{118515}{118555}PIešem.
{118608}{118663}U redu.|-Ubit æu te.
{118676}{118722}Ne.|-Da.
{119158}{119199}I onda...
{119261}{119307}UstrijeIiIa sam Nathana.
{119336}{119405}Onda je LiIa ustrijeIiIa Nathana.
{119416}{119465}Onda me Puff ustrijeIio.
{119469}{119509}I onda sam umro.
{119514}{119554}To je sve što znam.
{119561}{119612}To je kraj moje prièe.
{119653}{119704}Idem Ii sada u raj?
{119724}{119764}IIi u pakao?
{119782}{119825}IIi što?
{119837}{119891}Samo ostanem ovdje?
{119974}{120059}Ostanem ovdje i ponovno isprièam?
{120263}{120406}Za ono što ti se dogodiIo|jednako sam kriva koIiko i Nathan.
{120464}{120529}Predat æu se za ubojstvo.
{120533}{120602}Neæu ti dopustiti.|-Ostani tu u šumi.
{120607}{120688}Moram se tako žrtvovati.
{120697}{120771}Onda æu ja živjeti za oboje.
{120785}{120860}Bit æu najsIobodniji...
{120887}{120952}Najpravija životinja|u cijeIoj šumi.
{120955}{121012}Baš na to i raèunam.
{121137}{121269}No prvo se vrati i|svjedoèi pred Kongresom o...
{121304}{121376}O neuraèunIjivosti èovjeèanstva.
{121437}{121482}U redu.
{121511}{121558}Ako misIiš da æe pomoæi.
{121609}{121669}l to je. gospodo. moja prièa.
{121675}{121749}Pristao sam svjedoèiti|pred ovim odborom
{121752}{121821}nadajuæi se da æu|prenijeti amerièkoj javnosti
{121824}{121890}da doista postoji|izgubljeni raj.
{121893}{121970}Ljudska su biæa|postala toliko oèarana
{121974}{122025}svojim|intelektualnim dostignuæima
{122028}{122136}da su zaboravila gledati|zemlju kao uèiteljicu.
{122148}{122203}Ovo je ohoIost, prijateIji.
{122233}{122341}Moja prièa o uništenju|i izdaji dokaz je toga.
{122390}{122447}Održat æu obeæanje LiIi.
{122459}{122516}Odbacit æu ovo odijeIo.
{122566}{122631}I vratiti se u divIjnu.
{122645}{122738}Proživjet æu svoje|dane goI i sIobodan.
{122777}{122829}HvaIa i Bog vas bIagosIovio.
{122833}{122899}Vaša nas je prièa duboko dirnuIa.
{122902}{122982}Donijet æemo zakone|o ovome probIemu.
{122986}{123017}HvaIa.
{123022}{123075}Samo to tražim.
{123132}{123182}Zbogom, Lila.
{123205}{123302}Vodim te sa sobom u|svom neukroæenom srcu.
{124346}{124408}Gomila je oduševljena.
{124412}{124475}Mislim da nas je|možda sve dirnuo
{124480}{124566}svojom porukom o|poštovanju svijeta prirode.
{125472}{125503}Èekaj!
{125558}{125613}VidjeIa sam te na TV-u.
{125647}{125725}TražiIa sam te 30 g.
{125730}{125764}I ugIedaIa sam te.
{125768}{125845}Divnog i krasnog|odrasIog èovjeka.
{125952}{125978}Majko?
{126002}{126053}Da. Derek.
{126177}{126242}Drago mi je što|sam te upoznao, majko.
{126277}{126346}AIi majmun sam|kao što je i tata bio.
{126358}{126449}Sada moram natrag|u šumu. Zauvijek.
{126498}{126545}Vjerojatno.
{126568}{126663}Vjerojatno sam i|misIiIa da æeš to reæi.
{126676}{126771}Drago mi je što|sam te opet vidjeIa.
{126779}{126902}Moj je broj u imeniku|ako mi se požeIiš javiti.
{126908}{126962}Majmun sam, mama.
{126980}{127026}Majmun.
{127043}{127119}Majmuni se ne javIjaju.
{128507}{128549}Zdravo, djeèaèiæu moj.
{128552}{128655}Mama, donijeIa si odjeæu?|Guzica mi se smrzava.
{128675}{128724}Nathanovo odijeIo.
{128807}{128844}Zgodno.
{128925}{129015}Znaš, oduvijek sam te žeIio.
{129025}{129108}Reci moje ime.|-GabrieIIe.
{129149}{129250}ToIiko me podsjeæaš na Nathana.|-Kakav otac, takav sin.
{129255}{129359}I mnogo na moga psiæa mješanca.
{129507}{129571}Hajdemo jesti. Umirem od gIadi.
{129576}{129649}Francusku? -Da.
{130401}{130566}NEW YORK
{130888}{131666}Subtitles by:|M O Z E N

