{1}{1}25.000
{1653}{1733}Gray? 
{2115}{2187}Gledam film.
{2623}{2705}Kasniš na posao.
{2712}{2764}Oprosti.
{2770}{2871}Što si gledao? Peep show?
{2930}{2969}Zloèesta si.
{2976}{3007}Ti si zloèest.
{3014}{3076}Hej, vrati se! | Idemo na doruèak.
{3086}{3157}Ne, rano æu na ruèak. | - S kime?
{3199}{3265}U vezi nekog filma, | s redateljem.
{3311}{3372}S malo whiskeya | i na kauè?
{3424}{3477}Rez! | Izvrsno.
{3495}{3558}To je bilo super. | Gray, što ti misliš?
{3572}{3678}Možemo ponoviti, ako želiš. | Meni se sviða. A tebi?
{3685}{3753}Ako želiš, možemo ponoviti. | U redu. Idemo na ruèak.
{4732}{4921}POTAMNJELI SJAJ
{5272}{5329}Hej, Jimmy Stewart, | vadi ruku iz hlaèa.
{5489}{5535}Lijepo...
{5716}{5790}Bok, Mia. Kako si? Ovdje | Elvis Costello.
{5805}{5941}Kako si? U gradu sam. | Nazovi me. U gradu sam.
{5948}{6014}Jesam li to veæ rekao? Mislim | da jesam. Nazovi me.
{6020}{6062}Odsjeo sam u Four Seasons.
{6086}{6166}Bizarno. Zvuèao je nervozno. | - Da. Pet puta je ponovio
{6172}{6223}da je u gradu.
{6262}{6308}Ne ljuti se na mene. | - Ne ljutim se.
{6320}{6398}Uopæe se ne ljutim. Samo, | on je... Nije bitno.
{6406}{6489}On je Elvis Costello. Misli da | može nazvati kad poželi.
{6494}{6532}Ljigavo. | - Ok.
{6652}{6714}Kako je prošao sastanak?
{6727}{6791}Ne želim razgovarati | o tome. - U redu.
{8510}{8590}To je cameo uloga. Glumim | dilera samo zato što sam
{8597}{8657}mogao nositi trenirku i | glumiti supermodela...
{8672}{8732}Nisi nosio trenirku. | - Znaš što sam htio reæi.
{8809}{8847}Mia, izgledate predivno.
{8853}{8909}Sretan si èovjek, Gray. | - Da, jesam.
{9473}{9553}Mia, okreni se!
{9903}{9959}Kakvo sranje! Možeš li | vjerovati kako je to prošlo
{9966}{10013}na Sundance filmskom | festivalu?! - Naravno.
{10022}{10061}Kad se radi o homoseksualnim | anðelima ovisnicima.
{10069}{10187}G. Cinièni, oborio si ih. I | bio si izvrstan. Zar ne, Mia?
{10203}{10279}Što? - Rekao je da sam bio | izvrstan. Zar nisam? - Što?
{10286}{10354}Rekao je da je bio izvrstan! | - Bio je predivan!
{10365}{10541}Bio si fantastièan! | - Što? - Fantastièan!
{11038}{11096}Kad sam ju prvi puta | ugledao, bila je predivna.
{11105}{11196}Bože! I tada sam rekao: "Želim | te oviti pokrivaèen noæi."
{11203}{11252}"Želim te raskomadati, uvuæi u | nosnice i tada predstavljati
{11259}{11315}pakao u tebi."
{11360}{11421}O, Bože! - Hej, mafijaši. | Ne pucajte! - Gore s njima!
{11428}{11468}Doði...
{11481}{11548}Kako si, ljepotice? | Kako si ti? - Dobro, a ti?
{11555}{11611}Dobro sam. - Bok, Stiev. | - Mia, kako si?
{11741}{11798}Drago mi te je vidjeti. | - Stiev, odakle ti to odijelo?
{11805}{11862}Od nekog talijana. Teško | mi je pronaæi odjeæu.
{11875}{11927}Visok sam kao cirkusant.
{11938}{12014}Znate što mislim? Graya | možeš odvesti u prodavaonicu
{12022}{12086}djeèje odjeæe. Obuæi æe | se za cijelu godinu.
{12114}{12179}Ljubomoran sam. | Imaš super žensku,
{12186}{12227}možeš se obuæi | gdje želiš...
{12256}{12296}Mièi se.
{12306}{12412}Ovo je èudan trenutak... | - Šalim se.
{12438}{12552}Prestani, daj... | Izvrstan si.
{12564}{12661}Volim te, Gray. | - I ja tebe volim.
{12788}{12905}Charlotte! - Jesu li svi | naroljani kao ja?
{12915}{12996}Svi smo naroljani. | On pogotovo.
{13032}{13086}Možemo li dobiti | piæe, molim?
{13158}{13206}Tko?
{13260}{13301}Što?
{15007}{15072}Hajde, Gray...
{16239}{16296}O, Bože...
{16730}{16834}Nedostaju mi nedjelje. | - Danas je nedjelja.
{18603}{18668}Dobro jutro.
{18711}{18809}Ovdje su vaše pozivnice, | pisma obožavatelja, cigarete...
{18833}{18916}U redu, ako ste... | - S obranim mlijekom? - Da.
{18982}{19089}Urolog je otkazao za sutra | jer mora kod kiropraktièara.
{19097}{19133}U redu? Treba li | vam još štogod?
{19140}{19305}Ne? U redu... Idem ja. | - Gabriel... Camden.
{19315}{19407}Mislim da je Britanac. Ne | znam mnogo o njemu.
{19466}{19559}"Draga Mia, siguran sam da | ti ovo mnogi govore...
{19566}{19664}Ali, predivna si žena... I, | unatoè tome, znam da imaš
{19672}{19741}dubinu koju nemaju | mnoge filmske zvijezde."
{19760}{19837}Sad se puno bolje osjeæam. | Treba mi to svako jutro. Hvala.
{19847}{19962}Osjeæam istinsku povezanost s | tobom i ako se naðeš sa mnom,
{19970}{20005}znam da æeš osjetiti da ovo | nije samo još jedno
{20014}{20096}pismo obožavatelja." -Doista? | - Kao da to nikada nisi èula.
{20123}{20232}Visok sam 1,80m, imam | smeðe oèi, dobro sam graðen...
{20679}{20831}PETO PISMO | UHODE?
{21209}{21321}"Poželite li popiti sa mnom | kavu ili èaj, saznat æete
{21325}{21384}da nisam samo još jedan | obožavatelj, veæ netko
{21391}{21443}s kime biste imali | mnogo toga zajednièkog."
{21528}{21581}Trebala bi ga nazvati.
{22334}{22458}Halo? - Jett, ja sam. | - Cynthia? - Ne, Gray je.
{22488}{22587}Što radiš ovdje? | - Kako to misliš? Nedjelja je.
{22626}{22690}Pokušao sam ti ostaviti poruku, | ali ti je tajnica puna.
{22704}{22777}Da... Oprosti | zbog toga. Ja...
{22841}{22962}Slušaj, Gray... Moram danas | na spoj. Dolazi mi ženska.
{22970}{23056}Tko? - Ne znaš ju. Upoznao sam | ju u vlaku. Konobarica je.
{23158}{23235}Siguran si? Svjetlo je | predivno sada.
{23248}{23316}Ima guzu kao 12-godišnjak. | Moram se pripremiti.
{23398}{23448}Vidimo se.
{25994}{26058}37,24 dolara.
{26130}{26239}Sigurno to mrzite, ali želio | sam vam reæi da vaši filmovi...
{26247}{26326}Doista mi mnogo znaèe. Imaju | veliki utjecaj na moj život.
{26332}{26371}Hvala.
{26378}{26439}Zasigurno zvuèi suludo, | ali ja sam...
{26447}{26513}Prije par tjedana sam vam | poslao jedno pismo.
{26527}{26616}Doista? - Da. - Zovem se | John Eckhart. - Gray.
{26623}{26652}Drago mi je.
{26670}{26762}Potpišite se... ovdje.
{26783}{26840}Nikada ranije nisam nikome | napisao pismo.
{26847}{26941}Ali, studiram režiju. Trenutno | sam na zadnjoj godini.
{26948}{27031}Vi ste jedan od rijetkih u | kojima pronalazim nadahnuæe.
{27048}{27106}Hvala. To mi doista mnogo | znaèi. Hvala vam.
{27149}{27219}Vi ste pohaðali studij | režije, zar ne? - Što?
{27227}{27319}Studirali ste režiju? - Da, | a onda sam postao glumac.
{27461}{27531}Moja je djevojka vidjela | jednu vašu izložbu fotografija.
{27536}{27598}Rekla je da su doista predivne. | Sviðale su joj se.
{27607}{27646}Doista?
{27884}{27942}Muffin od brusnica, | gospodine...
{27974}{28054}Gray Evans, ovo je moja | djevojka Jane Styros. - Bok.
{28064}{28114}Bok. Drago mi je...
{28151}{28219}John i Jane...
{28337}{28396}Trebao bih... | - Ovo je vaše...
{28403}{28449}Trebate li vreæicu, ili nešto? | - Ne, ne... u redu je.
{28456}{28524}Doðite kadgod želite. Dat æu | vam popust na vaše filmove.
{28531}{28575}Vi biste meni trebali platiti | da njih kupim.
{28580}{28621}Bilo mi je drago.
{28770}{28884}"Dat æu vam popust na vaše | filmove." -Bilo je simpatièno.
{30083}{30148}Smiješak, Gray!
{31166}{31273}U redu je. Sigurno nije | ništa strašno, samo to misliš
{31278}{31369}jer si trenutno u krizi. Svi | prolaze kroz krize u vezama.
{31380}{31441}Samo je... | - Znaš što mislim?
{31453}{31596}Da. Svi smo pod stresom. | Postaje smiješno. Mi...
{31643}{31751}Rijetko kad se seksamo. Više | uopæe ne vodimo ljubav.
{31758}{31869}Osim kad smo pijani... | ili nakon svaðe.
{31911}{31998}Poznavao sam predivnu, | prelijepu ženu.
{32007}{32073}Doista prelijepu, pametnu, | izvanrednu... - Koju?
{32080}{32131}Svima je bila draga. | - Poznajem li je?
{32136}{32176}Sumnjam. Zvala se Shelby.
{32181}{32284}Izlazila je s tipom koji | nije bio ništa posebno.
{32294}{32352}Ona ga je izdržavala. | Nije imao ni posao.
{32357}{32400}Nikada joj nije davao | komplimente. Nije joj
{32405}{32446}govorio ni da mu je stalo do | nje. Uvijek joj je prigovarao
{32452}{32503}kako ništa ne radi kako | treba... - Toèno to!
{32509}{32546}Kako bi se trebala | ponašati... A ona je bila...
{32551}{32589}Svi su joj govorili kako je | predivna i prelijepa.
{32597}{32659}A on joj je uvijek govorio | kako joj "to ne stoji"...itd.
{32665}{32744}Jednom se pojavila kod mene. | Imala je masnicu pod okom.
{32757}{32855}Rekao sam joj kako svi kažu | da je predivna djevojka,
{32862}{32948}najbolja prijateljicu | koju bi svatko poželio.
{32958}{33047}Pitao sam je kojega vraga | radi s tom životinjom.
{33095}{33236}Rekla je da je on jedini | koji joj kaže istinu.
{33297}{33346}I tada postaje...
{33358}{33467}...teško. Jer si uvijek tako | nasmijana i predivna. - Da...
{33474}{33532}I to moraš nositi u sebi. - Da.
{33572}{33675}Ali sada mi se to ne da. -Nemoj | biti takva. Znaš i sama.
{33684}{33723}Ne lovi u mutnome. | - Divan si. Oprosti.
{33730}{33788}Ozbiljno mislim... - Ne... | - Ozbiljan sam. - Nisi.
{33795}{33872}Ne pokušavam te zadiviti. | Prolaziš kroz teško razdoblje.
{33879}{33909}Ne znam...
{33940}{34026}Ali, sve si ono što sam | nabrojao. Znaš to.
{34341}{34399}I... rez!
{34454}{34511}To! - Mogu li dobiti | vruæi ruènik?
{34552}{34701}Znam da si se brinuo zbog tog | prizora, ali mislim da æe se
{34706}{34809}dobro uklopiti. - Ne, to je | samo CPR. Kreten!
{34841}{34929}Isuse! Prepao si me. | Kako si ušao?
{34977}{35015}Pitam li ja tebe kako | radiš svoj posao?
{35025}{35083}Ne. Ali te ne plaæam da mi | se šuljaš iza leða. - Hej!
{35109}{35188}Neko vrijeme ne bih išao tamo, | da sam na tvom mjestu. Reci!
{35212}{35302}Bila je to dobra maèka u | dizalu. - Ako se ostatak života
{35307}{35368}želiš osjeæati kao | patuljak, da.
{35423}{35557}Pa, kako si, Yehud? - Nije | loše, ti? - Malo sam zabrinut.
{35564}{35626}Naravno da jesi.
{35660}{35725}Kako to misliš? Trebao bih se | brinuti? - Opusti se, Gray.
{35732}{35813}Ljudi me obièno ne zovu, | ako nisu zabrinuti.
{35875}{35976}Da? - Ja sam, Samantha. - Bok. | - Bok. Samo sam htjela vidjeti
{35983}{36054}znaš li da je Yoohuda... | - Yehud. - Yehud, oprostite.
{36061}{36181}Da. Uplašio me je. - Oprostite. | - Mislim da je ovdje.
{36189}{36258}Jesi li ovdje, Yehud? | - Jesam. - Ovdje je. - Ok.
{36267}{36316}U redu, idem ja onda. | Trebate li...
{36324}{36454}Vaš gastrointernolog... | Imate logopeda u 15h...
{36470}{36553}Idem sad. Bit æu dostupna na | mobitelu. - Ok. - Ugodan vam dan.
{36559}{36602}I tebi. - Bok. - Bok.
{36640}{36732}Ševiš li ju? - Ne. Slušaj, | Yehud. Ne znam ima li smisla
{36739}{36827}brinuti se, ali... - Gray! | Nitko te ne pokušava ubiti.
{36834}{36957}Vidio sam ga dvaput. | Nije normalan.
{36974}{37079}Da? - Još pet minuta, | Gray! - Ok!
{37125}{37227}Znaš... - Ako želiš, ostat | æu malo na snimanju.
{37239}{37289}Pojavljuje se na premijerama? | - Da. Provjeri ga.
{37295}{37371}U redu. Provjerit æu ga. | - Ok. - Ok. - Hvala ti.
{37382}{37462}Moram stiæi na utakmicu. | Radim na osiguranju tamo.
{37470}{37582}Sutra poèinjem. - Ok. Što | znaš o Elvisu Costellu?
{37623}{37729}Misliš da te on uhodi? | - Ne, nema veze.
{37866}{37953}Usput, taj prozor... | Sigurnosni rizik.
{38008}{38066}Yehud se šali.
{38160}{38193}Slušajte!
{38211}{38372}Reci mi kad si spreman | zapoèeti. Veæina je tvog teksta.
{38427}{38546}Kad on zapoèinje? Rekao sam: | "Kao prvo, on je osoba..."
{38553}{38617}Drugo, zauzet sam. A treæe, | pogrešno je gledati ga
{38624}{38684}samo kao glumca. On nije | samo stvar.
{38691}{38803}Ozbiljan sam. Odmah mi reci. | Od 500 reèenica, 499 su tvoje.
{38816}{38889}Ne šalim se. Samo malo, | ali... - U redu.
{38897}{38939}Treba li tko štogod | iz kupaonice?
{39911}{40001}Hej, sjeæaš me se?
{40014}{40078}Ja sam John. Bio si u | mojoj trgovini.
{40085}{40230}Kakva sluèajnost! - Da. | Imamo ulaznice za ovo.
{40279}{40346}Želiš li...? | - Da, hvala.
{40518}{40631}Sam si ovdje? - Došao sam s | curom. Upoznao si je. Jane.
{40639}{40673}Da, da... | - Da.
{40748}{40796}Želiš li...?
{40835}{40959}Hej, srce. - Baš smiješno. | - Da. Kakva sluèajnost.
{40967}{41051}Da. - Kako si? | - Izvrsno.
{41070}{41128}Trebali bismo... | - Znaš... Oprosti.
{41135}{41183}Danas smo bili u | zoološkom vrtu i slikali.
{41190}{41252}Jesi li to kad radio? | - Nisam. - Ne?
{41343}{41403}Ne mrziš li kad ti ljudi | prilaze i gnjave te?
{41409}{41511}To si me došao pitati? - Idemo. | Oèito ne želi da ga gnjavimo.
{41518}{41599}To je sigurno cool, zar ne? | Znaèi da je ljudima stalo.
{41683}{41781}Kad si umirao u onom filmu | s anðelima, što si rekao?
{41799}{41935}Vodite me odavde. -To si rekao? | - Moram do supruge. - A, da!
{41969}{42034}I ja bih otišao do nje, da sam | na tvom mjestu. - Brett?
{42064}{42147}Puno je niži | nego što sam mislio.
{42179}{42272}Tamo je condo. - Gdje? | - Kod Rosarita.
{42300}{42368}Obožavam Rosarito. Jesi li | bio ondje? - Predivno je.
{42375}{42428}Na samoj plaži. | - Što radiš tamo?
{42448}{42498}Doista? Ma daj...
{42690}{42772}Gray Evans. | Obožavam tvoje filmove.
{42992}{43077}Bože, pjesma!
{44108}{44178}Hej! | - Jesi li vidjela ovo?
{44188}{44223}Što? - Slušaj.
{44230}{44300}"Sumnjamo da æe brak G. Evansa | i Mie Lang još dugo potrajati.
{44307}{44371}Izvori bliski paru tvrde | kako je veza klimava.
{44377}{44483}Oboje su podložni bijesnim | ispadima i olujnim vezama."
{44558}{44681}To nije baš lijepo. - Nije | lijepo? To je kleveta.
{44690}{44740}Ti se šališ?
{44807}{44877}Što? Ok... | Možda ovo...
{44891}{44960}Slušaj. "Oèito je da G. Evans | nije obožavatelj E. Costella.
{44966}{45037}Nakon èestih telefonskih | poziva Kralja Mii Lang,
{45044}{45132}Gray je poludio od ljubomore, | tvrde izvori. Ima li Elvis
{45139}{45202}iskrene namjere? Znamo da | netko ne misli tako."
{45229}{45298}Mia, to su bili | razgovori meðu nama.
{45322}{45399}S kime si razgovarala? | - Nisam nikome ništa rekla.
{45406}{45453}Jesi li ti, dragi?
{45522}{45575}Nisam.
{45597}{45671}Ne znam zašto uopæe to èitaš.
{45774}{45836}Kako možeš biti | tako flegmatièna?
{45843}{45896}To je samo žuta štampa.
{46148}{46221}Zašto nikada više ne kuhamo?
{46274}{46358}Nikada nismo kuhali.
{46543}{46601}Nemoj biti tužna.
{46623}{46692}Jesi li tužna? | Nemoj biti tužna...
{46734}{46859}Daj... | - Prestani. Hej!
{47009}{47072}Mrzim te.
{47360}{47421}Što je to tamo?
{47440}{47511}Scenarij o zecu koji govori.
{47688}{47760}Nemoj se smijati mom poslu. | - Ne smijem se.
{47817}{47894}Smijem se. | - Znam.
{48778}{48848}Bok, Mia. | Ovdje Elvis Costello.
{48855}{48944}Bilo mi je drago vidjeti te. | Sastanimo se na veèeri.
{48951}{48986}U gradu sam.
{49091}{49165}Neæeš joj biti | ljubavnik, gade!
{49180}{49288}Gade! - Ona mi je žena! - Zašto | se onda ne ponašaš tako?
{49301}{49360}Boli me... | - Bježiš od sebe!
{49369}{49417}Bježiš od sebe! | - Isuse!
{49424}{49539}Bježiš od sebe, | glupi gade! - Rez!
{49566}{49623}Bilo je izvrsno. Fantastièno! | Jesi li dobro?
{49630}{49690}Bilo je izvrsno. | - Metoda "razbij sve".
{49703}{49801}Connor, ne zaustavljaj prizor. | To je moj posao, kužiš?
{49809}{49896}Kužiš? Zamalo mi je slomio | ruku! - Što si ti, idiot?
{49904}{49975}Da, ja sam idiot. - Dobit æeš | otkaz. Briga me tko ti je otac.
{49982}{50041}Baš me briga. - Goni se! | - Ionako si gotov.
{50053}{50122}Je li bilo dobro? - Nisam | zadovoljan. Želim ponoviti.
{50129}{50159}Šališ se?
{50198}{50241}Budala.
{50258}{50296}Zabilježi to.
{51137}{51242}Halo? - Bok, Gray. Felicia je. | - Bok. - Dobro sam, hvala.
{51252}{51312}Zvuèiš kao da si se | prehladio. Jesi li dobro?
{51323}{51433}Jesam. Jeo sam chilli, | neko tajlandsko jelo.
{51452}{51513}Znam da si ovdje. | Swoosh, noæni klub,
{51520}{51621}pokreæe èasopis s prilogom | o slavnim parovima.
{51627}{51687}Žele ih slikati u ležernom | okružju. Kod kuæe,
{51694}{51744}ili dok igraju tenis. I žele | tebe i Miu za naslovnicu.
{51751}{51788}Pristajemo. - To je bilo lako.
{51870}{51929}Nema šanse, Gray. | Preljigavo je. Ne mogu to.
{51937}{52022}Nije ljigavo. Možemo uèiniti | bilo što. Samo æe iæi za nama.
{52031}{52100}A mi možemo raditi štogod | želimo. - Ne, žao mi je.
{52107}{52158}Ne mogu biti dio toga. | I, nisi mi jasan.
{52164}{52228}Mrziš taj biznis. | Mrziš krpice.
{52235}{52327}Mrziš to što smo slavan par. | - To smo što jesmo.
{52333}{52405}Možemo im pokazati to što | jesmo. Umjesto ovog olujnog,
{52411}{52510}uzburkanog sranja koje èuju. | - Ali jesmo olujni i uzburkani.
{52518}{52549}Nismo!
{52857}{52940}Ja sam, Jedd. Žao mi je | zbog onoga neki dan.
{52947}{53011}Moram na kolonoskopiju | za par tjedana.
{53019}{53147}Upoznao sam malu crvenokosu | koja kaže da te poznaje.
{53153}{53224}Glumi u istom showu. | Zove se Jenny ili Jane.
{53259}{53347}Ne moraš zvati natrag. Bit æu | u kadi. Osjeæam se boležljivo.
{53423}{53514}Od svih ljudi iz ovog izdanja, | nitko nije radio nešto vani.
{53540}{53626}To je doista slatko. Je li | zoološki vrt vaše mjesto?
{53634}{53814}Ne baš. - Oboje volimo život | divljine. I volimo šetati.
{53841}{53897}To je kao da ubijamo dvije | ptice jednim udarcem.
{53916}{53976}Da, ne volimo ptice. | - Hej, kako ste?
{54033}{54118}To je tako organski, Gray. | - Znao sam da æe ti se svidjeti.
{54129}{54167}Hej, kako ste?
{54177}{54267}Sada æemo... | Uslikat æemo vas. - Ok.
{54568}{54629}Srce, što želiš prvo vidjeti?
{54638}{54696}Braènog savjetnika.
{54705}{54750}To nije životinja.
{54778}{54831}Željela bih vam | zahvaliti zbog ovoga.
{54838}{54931}Doista to cijenim. | Izgledate fantastièno.
{54995}{55105}Isuse. Želite li vode? | - Ne, dobro sam.
{55118}{55160}Sigurno? | - Da.
{55182}{55258}Kako izgleda vaš prosjeèan | dan? Kad ne radite?
{55265}{55300}Nedjeljom...
{55309}{55356}Hajde, ti reci.
{55369}{55551}Ustanemo oko 4h popodne. | Naruèimo pizzu. Ušlagiramo se.
{55585}{55699}Što kažeš, dušo? Oko 5- | 5:30h? - Ušlagirate se?
{55707}{55757}Da. Nafiksamo se heroinom.
{55879}{55937}Šalimo se. | - Aha.
{55947}{56048}Ne, prilièno smo obièni. | Kao svi drugi. Ustanemo,
{56069}{56164}doruèkujemo, i... znate.
{56240}{56365}Èitamo novine. | Samo èitamo novine.
{56392}{56446}Samo to, znate?
{56522}{56589}Da... - Nacrtao si | mi lažne cice.
{56615}{56671}Što? - Dogovorili smo se | da æeš se lijepo ponašati.
{56677}{56757}Ne razumiju tvoj humor. - Nisam | ja kriva što su obiène fufice.
{56764}{56903}Tiše! - Ne ušutkuj me! Samo | sam onakva kakva jesam.
{56913}{56993}Nije li to bit? - Budi tiše... | dovraga! - Ali, zašto, Gray?
{56998}{57048}Mi smo ovakvi!
{57112}{57158}Sranje...
{58295}{58364}Dobar dan, g. Evans.
{58780}{58812}Jeste li dobro, gospodine?
{58819}{58878}Što to radite? | - Imate pravo na šutnju...
{58884}{58950}Ima pištolj! - Imate | pravo na odvjetnika...
{58998}{59060}Što to radite, dovraga? - Što | misliš? Stvaramo vijesti.
{59074}{59100}Što?
{59357}{59446}Je li Gray Evans poludio? Lli | je to još jedan sluèaj kad
{59453}{59497}obožavatelj pretjera u | svom divljenju prema
{59504}{59604}omiljenoj zvijezdi? Sumnja se | da bi Hortens mogao odgovarati
{59611}{59709}za nekoliko sluèajeva | uhoðenja slavnih osoba...
{60192}{60436}Gray, o èemu si razmišljao? -Da | bi bilo lijepo da me ne ubije.
{60449}{60539}Ubiju? - Da. - Tko bi te ubio? | Tip je samo htio da mu
{60545}{60646}potpišeš knjigu. - To je bio | "Lovac u Žitu," Louis.
{60655}{60723}Jezovito. | - Ti to ozbiljno?
{60870}{60951}Bok. - Bok, srce. | Kako si? - Dobro.
{61066}{61125}Vidi ovo. Divlja horda.
{61147}{61196}Felicia, jesi li dala iskaz? | - Ne, htjela sam prvo
{61203}{61260}s vama razgovarati. - U redu. | Bit æemo jezgroviti.
{61268}{61313}Ja sam samo odvjetnik | za odnose s javnošæu.
{61319}{61372}Dok ne naðemo | odvjetnika za zloèine,
{61379}{61468}recimo da je bila samoobrana. | - I bila je samoobrana. -Doista?
{61476}{61538}Da. - Samoobrana. - Da. | - Je li ti prijetio, Gray?
{61547}{61588}Vidio sam tipa 95 puta.
{61665}{61721}Yehud, reci im da ti uhoda | nikada neæe objašnjavati,
{61726}{61792}prije nego te upuca.
{61801}{61899}Istina je. Doista se èini da | vlada epidemija uhoðenja.
{61918}{61994}U redu. Ali, ovaj tip nije | uhoda, veæ obožavatelj.
{62000}{62058}Da, a Mark Chapman je | obožavao "White Album."
{62067}{62162}Bio je to dobar album. Tip | te tuži, to je ozbiljna stvar.
{62169}{62198}To je apsurdno.
{62205}{62262}Donesite mi još jedno piæe, | molim vas. - Što æeš, Scotch?
{62480}{62551}Sutra æemo se reorganizirati? | Gray, odmori se malo.
{62568}{62626}Yehud, mogu li razgovarati | s tobom? - Naravno.
{62639}{62698}Hoæeš Vicodin? | - Da, može.
{62984}{63036}Što je bilo? -Želim razgovarati | s tobom o neèemu.
{63043}{63102}Mislit æeš da sam paranoièan.
{63139}{63288}Ali, u ovom trenutku ni | sam ne znam što radim.
{63309}{63372}U èemu je problem? | - U redu...
{63531}{63632}Prošli tjedan sam primio | jedno pismo obožavatelja.
{63639}{63706}Od Hortensea? - Ne, | drugoga. - Drugoga...
{63733}{63809}Tog istog dana sam | ga sluèajno i upoznao.
{63898}{64023}Dva dana kasnije, opet sam | sluèajno naletio na njega
{64032}{64181}i njegovu djevojku koja | voli moje fotografije.
{64237}{64335}Prije tri dana sam dobio | poruku mog prijatelja Jedda.
{64447}{64547}Ona radi umjetnièku izložbu | kod mog prijatelja.
{64617}{64711}U redu...
{64856}{65038}Preporuèit æu par tipova da | te prate. - Ne, Yehud...
{65056}{65199}Nisam èudak. Ne želim... - Nisi | èudak, veæ filmska zvijezda.
{65213}{65296}Samo bih želio da ih | provjeriš, to je sve. - U redu.
{65311}{65421}Dat æu ti pištolj. - Što? | - Osjeæat æeš se bolje. - Ne!
{65432}{65492}Zar ti izgledam kao Charlton | Heston? Neæu pištolj!
{65524}{65587}U redu... Ako se predomisliš... | - Neæu se predomisliti.
{65594}{65672}Samo mi to provjeri. | - Ne moraš se živcirati, ok?
{65678}{65730}Ne živciram se... Yehud.
{67363}{67428}Žao mi je, Shana. Htio | sam oprati rublje s tobom.
{67435}{67483}U redu je, mali. | Kako je prošlo?
{67489}{67538}Bio sam dobar, ali znam da ne | bih smio previše poluditi.
{67545}{67601}Sladak si kad poludiš. | Hoæeš pojesti nešto?
{67608}{67690}Zato sam toliko uzbuðen. | Kupio sam dva ogromna iceberga.
{67698}{67772}Hoæe li tko njegovu omiljenu | salatu? - Netko bi mogao.
{67779}{67823}Jer moje srce mora | malo smršavjeti.
{67894}{67953}Nedostajala si mi. | - Ti meni još više.
{67962}{68040}Nemojmo se nikada razdvajati | dulje od 4 sata, može? - Može.
{68185}{68272}Jesi li štogod dobro uslikala | danas? Nebo je bilo ludo plavo.
{68280}{68334}Hej, ljepotane, daj da | tebe uslikam.
{68451}{68492}Savršeno.
{69505}{69554}Felicia mi je dala ove | portrete da potpišeš za
{69562}{69608}step-cipele za bebe.
{69620}{69675}U redu, znam... Oprosti. | Zadržat æu ih.
{69683}{69763}Htjela je i da ti pokažem ovo. | To je The National...
{69919}{69978}Jesi li vidio ovo sranje?
{70010}{70066}Vjerojatno æe upotrijebiti taj | èasopis kao dokaz.
{70079}{70134}Gray... - Možeš li | ti to vjerovati?
{70166}{70254}Ne brini o Hortenseu. Nema | materijala za sudski spor.
{70262}{70292}U redu...
{70397}{70455}Doista se bojiš te djece?
{70488}{70566}Ne znam, ti meni reci. | To je sve o njima?
{70576}{70697}Najisplativiji sam u gradu. | - Èini se da jesi.
{70711}{70744}Pa...
{70797}{70853}Što imamo ovdje?
{70911}{71008}John Eckhart i Jane Styros.
{71044}{71099}Žive blizu trgovine | gdje si ih upoznao.
{71107}{71224}Ali, nemaš razloga za brigu.
{71323}{71405}Zaljubljeni su? | - Pozlilo mi je od njih.
{71431}{71496}Hoæeš vidjeti njezinu | sliku kad je naga?
{71503}{71562}Prirodna je crvenokosa. | - Ne, hvala.
{71580}{71618}Nema više vatre, ha?
{71698}{71760}Kakav je njihov uobièajeni | dan? Što rade?
{71769}{71818}Veæinom što i ostali parovi.
{71824}{71932}Da, što? - Što i obièni parovi | rade. - Što oni rade?
{71966}{72033}Primjerice, što su radili | sinoæ? Daj mi primjer.
{72041}{72100}Sinoæ? | Sinoæ...
{72118}{72238}Sinoæ je John završio s | poslom kasnije nego obièno.
{72275}{72351}Uzeo je neke DVD-ove, neka | francuska sranja, mislim.
{72388}{72468}Otišao u robnu kuæu po | novu zavjesu za tuš.
{72509}{72603}Onda je otišao u trgovinu po | namirnice, vratio se kuæi u 7.
{72644}{72678}To je mali stanèiæ,
{72697}{72784}pun sitnica. | Umjetnièka djela
{72826}{72914}na zidovima. Neka vrsta | bitnièkog ureðenja...
{72953}{73078}Otišao je u kuhinju i | prišuljao joj se.
{73103}{73235}Kao da se danima nisu | vidjeli. Ili tjednima.
{73246}{73316}A zapravo je prošlo | 9 sati i 20 minuta.
{73349}{73436}Onda joj je skuhao veèeru.
{73490}{73595}Što je skuhao? - Kirnju | u umaku Teriyaki.
{73612}{73670}Sa smeðom rižom i šparogama.
{73775}{73833}Je li joj se svidjela veèera?
{73847}{73904}Kakvo je ovo sranje? | Kakvi su to papiri?
{73912}{74027}Transkript. Daljinski mikrofon | postavljen na njihovu prozoru.
{74072}{74168}Ti se ne šališ, Yehud. - To | dobiješ za 5000 dolara.
{74185}{74283}Za 10 ti mogu odglumiti | Janeinog ginekologa.
{74290}{74333}Ne, zadovoljan | sam. Hvala ti.
{74369}{74452}Èine se doista bezazleni, | a mnogo se toga dogaðalo
{74459}{74517}u zadnje vrijeme. | - Istina.
{74565}{74640}Mogu li to zadržati? | - To je tvoj primjerak.
{74654}{74734}Izvrsno. Hvala ti. | - U redu, vidimo se. - Da.
{74888}{74942}Gray...
{74992}{75083}Sve æe biti u redu. | - Znam. Da...
{75124}{75185}Bit æu u Swooshu, | ako me trebaš. - Ok.
{75698}{75823}U pravu si. Svi oni snimaju | male filmove kako bi ih
{75830}{75927}kasnije iskoristili kao | ulaznicu u veæa studija.
{75934}{76053}Sumnjam da to rade iz ljubavi. | - Znam, Mia. U pravu si.
{76060}{76143}1970.-ih su klinci to radili | jer su morali. Kao s glazbom.
{76152}{76211}Više se ni ne trude | da ju nauèe svirati.
{76218}{76304}Sada su filmovi nove gitare, | a redatelji nove rock zvijezde.
{76312}{76411}Tako je, da. - Izvolite raèun. | Želim vam ugodnu veèer.
{76433}{76540}Vi takoðer. - Hvala. -Oprostite, | htio sam reæi da obožavam
{76547}{76613}vaše filmove.
{76945}{77043}MIINO NEVJERSTVO
{77517}{77573}Bok, draga.
{77681}{77735}Što je ovo?
{77743}{77835}Uvijek jedemo vani, ili | naruèujemo izvana
{77843}{77928}pa sam mislio da bi bilo dobro | da pojedemo skuhanu veèeru.
{77955}{78030}Ti si to sve skuhao? | - Možeš li vjerovati?
{78091}{78137}Super...
{78145}{78188}Sjedni...
{78226}{78284}Kako si proveo dan?
{78360}{78515}Dobro. Obavljao sam neke | posliæe, skuhao veèeru...
{78560}{78622}I, znaš...
{78781}{78847}Kako si ti provela dan? | - Dobro.
{78856}{78993}Da? Bilo je dobro na poslu? | - Znaš veæ. Kao i obièno.
{79022}{79119}Da, znam. Ti mladi | redatelji znaju biti èudaci.
{79136}{79194}Nikada ne znaš zašto to rade.
{79240}{79366}Uvijek sam mislio da ti tipovi | snimaju takve filmove
{79375}{79501}kako bi im oni bili ulaznica | za veæa studija.
{79508}{79616}Ne rade to iz ljubavi. - Da. | Što je za veèeru?
{79797}{79897}Ukusnu kirnju u | teriyaki umaku.
{79918}{79959}I smeðu rižu.
{80035}{80115}I nešto od èega æe ti | smrditi mokraæa.
{80126}{80193}Alergièna sam na kirnju. | Sjeæaš se?
{80218}{80280}Ono jednom sam skoro | umrla. Sjeæaš se?
{80514}{80608}Sjeæaš se ti ovoga? | - Ne.
{80715}{80797}Ne sjeæaš se da si | nazvala taj broj.
{80804}{80866}Mogu ti pustiti poruku.
{80874}{80953}Radilo se o poslu, Gray. | Želi snimiti mjuzikl sa mnom.
{81013}{81104}Mislim da je to najveæe | sranje koje sam ikada èuo.
{81113}{81171}Doista? A što toèno?
{81187}{81264}Želi s tobom snimiti mjuzikl? | - Htjela sam ti reæi,
{81273}{81321}ali ako si primijetio, u | zadnje vrijeme si
{81327}{81383}prilièno napet.
{81448}{81563}Pijan si. Zašto se ne | otrijezniš, pa kad se vratiš,
{81570}{81635}možemo jesti i razgovarati | o tome.
{81666}{81739}Da, pojedimo kirnju. | Možda æeš se ugušiti.
{81813}{81916}Neæeš tako razgovarati sa | mnom. Što sam ti uèinila?
{82593}{82652}Bok. | - Bok.
{82698}{82781}Gledaš statièki elektricitet? | - Htio sam pogledati film.
{82788}{82837}Hoæeš li i ti sa mnom?
{82926}{82975}Sanjao sam nešto.
{83054}{83118}Je li san bio stvaran?
{83140}{83200}Da, mislim da sam | znao da sanjam.
{83212}{83337}I to si odluèio uèiniti? Ja | bih letjela da znam da sanjam.
{83385}{83442}Ja se bojim visina.
{83495}{83558}To si odluèio?
{83567}{83649}Sanjati o tome da sanjaš | kako nas gledaš na TV-u?
{83714}{83774}Da, zato što nas volim.
{83820}{83881}I ja nas volim.
{84059}{84124}Da, samo želi potpisani | portret, i sve æe zaboraviti.
{84136}{84242}Sad æe odbaciti optužbe? | - Da. - Poslat æeš mu portret?
{84248}{84293}Ne znam. Mislim da bih ga | htio vidjeti na sudu.
{84318}{84377}Moram kuæi, pa...
{84399}{84468}U redu, vidimo se.
{85298}{85343}Bok, John.
{85349}{85408}Hej, Gray, kako si? | Drago mi je vidjeti te.
{85416}{85446}I meni.
{85453}{85541}Jesi li dobro? Èuo sam | za ono... štogod to bilo.
{85547}{85583}Za što?
{85588}{85635}Za onaj incident...
{85643}{85754}A, da, sve je u redu... | - Zanimalo me je.
{85817}{85876}Ne mogu vjerovati...
{85928}{86002}Ipak si to uèinila. - Oprosti, | nisam si mogla pomoæi.
{86027}{86094}Jane! Bok. | Izgledaš izvrsno.
{86100}{86163}Jesi li èuo? | Ipak ti se sviða...
{86204}{86267}Gdje ste nestali onu veèer?
{86287}{86354}Èinilo se kao da te je | samljela rulja,
{86360}{86400}a njoj nije bilo baš dobro... | - Uhvati me panika
{86407}{86468}na takvim dogaðanjima. - Da, | ja trebam konjsku tabletu
{86475}{86534}za smirenje, svaki put kad | idem na takve dogaðaje.
{86544}{86629}Želiš li štogod? Zatvaram kasu. | Mogu ti dati svoj popust.
{86643}{86687}Mogu li pogledati malo?
{86713}{86756}U redu, hvala.
{86773}{86801}Pa...
{86808}{86858}I? | - Malo je...
{86865}{86941}Ne sviða ti se. - Nije to. | Samo sam iznenaðen.
{86948}{86986}Laži mi. Pretvaraj se | da ti se sviða.
{86993}{87047}U redu. Onda æu ti lagati. | Sviða mi se. Izvrsno je.
{87544}{87667}MIA LANG u filmu | ÈAROBAN SAT
{87688}{87750}Jednoga æeš me dana | ostaviti zbog nje, zar ne?
{87807}{87913}Neæu. Nikada neæu uspjeti | saznati njezin broj telefona.
{87920}{87956}Kreten!
{88121}{88242}Ti si moje srce, srce. | - Volim te. - I ja tebe.
{88444}{88529}Moramo li danas posuditi | film? Možemo li van?
{88535}{88604}Idemo van pogledati film. | - Znaš što sam mislila.
{88611}{88688}Prikazuju Ples na Kiši. | Hajde, molim te...
{88695}{88730}Danas je dan za film. | Molim te, molim te...
{88737}{88802}Juèer je bio dan za film. | Danas je dan za život.
{88817}{88924}Tko bi odolio takvom | oèitom èinu manipulacije?
{89114}{89176}Jesi li pronašao nešto | što ti se sviða?
{89318}{89379}Jeste li možda za piæe? | Ili pet?
{89443}{89493}Može.
{89510}{89544}Ok.
{90137}{90233}Gdje si bio? | - Zezao se kod Jetta.
{90280}{90370}Zezao se KOD | Jetta, ili S Jettom?
{90385}{90459}Nismo li mi predivan par?
{90577}{90693}Zašto si tako sretan? | - Ne mogu biti sretan?
{90765}{90856}Ne znam. Možeš li? | - Netko je imao loš dan.
{90865}{91006}Netko je izgubio ulogu zbog | 19-godišnjeg modela.
{91062}{91150}Trebala bih poèeti gurati | prst u grlo kao veæina njih.
{91163}{91273}Film je ionako bio sranje. | - Što...
{91314}{91411}Doista si pun razumijevanja, | Gray. Je li danas Božiæ?
{91418}{91458}Naravno.
{91510}{91583}Doista si super raspoložen.
{91663}{91800}Možda zato što sam | ja loše raspoložena.
{91917}{92036}Tako si lijepa, tako... | - Ne. - Da. - Ne.
{92043}{92093}Da... - Ne.
{92171}{92271}Ja sam tvoja | debela stara žena.
{92853}{92940}ÈAROBAN SAT
{92946}{93008}Gray...
{94210}{94284}Tako si lijepa. | Izgledaš predivno.
{94291}{94341}Jesi li skoro gotov? | Doði u krevet.
{94349}{94414}Nisam još ni zapoèeo.
{94453}{94530}Ne znam koliko još dugo | mogu ovo izdržati. Iskreno.
{94558}{94633}Ovo moram predati u èetvrtak, | a uopæe nemam nadahnuæa.
{94640}{94683}Sutra æu morati | cijeli dan raditi.
{94777}{94865}Možda više nemam što za reæi. | - Naravno da imaš.
{94974}{95021}Što?
{95076}{95160}Srce, samo si umoran.
{95300}{95347}Bilo je ludo vidjeti Graya | neku veèer sa svim onim
{95355}{95452}obožavateljima, zar ne? | - Uznemirujuæe je.
{95534}{95653}Da, znam, ali daj... | Mislio sam... - Što?
{95662}{95745}Bilo bi lijepo... - Što? Imati | gomilu razmaženih silovatelja
{95753}{95820}cura na prvom sastanku da te | gnjave? - Hej, neki od mojih
{95824}{95890}najboljih prijatelja siluju | cure na prvom sastanku!
{95922}{95984}Ne govorim o slavi, | i tome, ali...
{96060}{96106}...ovo je sranje.
{96113}{96161}Raditi za minimalac? | Užas.
{96182}{96219}Cijeli dan biti okružen | filmovima koje su snimili
{96227}{96297}drugi? Užas.
{96305}{96397}Jedva da mogu plaæati ovaj | stanèiæ. Cijevi su zahrðale.
{96427}{96519}Ali tvoja nije. | Meni je samo do nje stalo.
{96700}{96773}Strpi se malo, srce. | Nismo još tako stari.
{96783}{96849}Stariji smo | nego smo ikada bili.
{96980}{97054}Prije tebe sam mislio | samo na posao i uspjeh.
{97133}{97201}Ali, kunem se, ništa mi to | sada ne bi znaèilo bez tebe.
{97313}{97378}Toliko te volim...
{97633}{97712}Toliko te volim...
{100947}{101022}Jesi li vidio ovo? Piše da | bi se G. Evans i M. Lang
{101030}{101116}mogli rastati. - Tip je idiot | ako se rastane od nje.
{101817}{101876}Jednoga dana æeš me | ostaviti zbog nje.
{101895}{101954}Nikada neæu uspjeti | saznati njezin broj telefona.
{102379}{102433}Zanemario si me.
{102440}{102526}Bio si pijan. Nisi plakao, | nisi se isprièao.
{102544}{102594}Opet bi isto uèinio.
{102604}{102674}Kako možeš oèekivati | da to izdržim?
{102708}{102842}Jer se volimo. - Voljeli smo | se. Kada si govorio stvari kao:
{102861}{102965}"Prije tebe sam mislio | samo na posao i uspjeh.
{102985}{103040}Ali, kunem se, ništa mi to | sada ne bi znaèilo bez tebe."
{103148}{103223}Gledam film...
{104216}{104346}Jesi li gledala taj film? | - Dijelove jesam. Hvala.
{104653}{104694}Idem po sendviæ. | Hoæeš li ti štogod?
{104701}{104729}Ja æu ti ga donijeti. | Od èega želiš?
{104735}{104767}Nemoj, ja æu. | Hoæeš li ti štogod?
{104775}{104836}Ne, hvala. | - U redu...
{105220}{105269}Èini se da æe se G. Evans | uspjeti nagoditi sa svojim
{105276}{105335}"moguæim" uhodom, | Larryjem Hortenseom.
{105342}{105415}Evans je nedavno srušio | obožavatelja u zoo-u kada je
{105420}{105482}zamijenio knjigu "Lovac | u Žitu" za pištolj.
{105502}{105592}Isprve je odbijao nagoditi se, | ali je sada potpisani portret
{105599}{105620}poslan poštom, a Hortense | je odbacio sve optužbe.
{107266}{107359}Èovjeèe... | - Samo sam...
{107405}{107473}Samo sam želio biti prijatelj.
{107606}{107743}Možemo biti prijatelji. | - To je sranje. Pretvaraš se.
{107750}{107803}To radiš za život, zar ne?
{107866}{107922}Veæ si kriv.
{107941}{107982}Upucaš li me, ti si kriv.
{108018}{108143}Neæu te upucati. Zašto bih | to uèinio? Volim te.
{108243}{108302}Što želiš?
{108402}{108482}Sad æemo otiæi na ruèak, | u redu? Ti i ja æemo se
{108489}{108574}zakopati ratne sjekire, kako | ono kažu. Ok? Frendovi.
{108639}{108688}Jebi se.
{109606}{109661}Previše nas je.
{109692}{109741}Hortensea danas nismo | uspjeli dobiti radi komentara,
{109748}{109828}jer je na proputovanju oko | svijeta sa svojom majkom.
{109835}{109911}S nama u studiju je struènjak | za uhoðenje slavnih osoba...
{110334}{110426}Doista mislim da možemo | pomoæi jedan drugome.
{110435}{110506}Ova glupa situacija koja me | je snašla æe sigurno donijeti
{110511}{110659}nevine žrtve, a ja ne želim | biti sljedeæa žrtva.
{110708}{110853}I osjeæam da si iskren, | a ja želim biti dio
{110860}{110922}neèega što ima znaèenje.
{110932}{111019}Mislim da bismo trebali | napisati nešto zajedno,
{111027}{111091}ili pokrenuti | zajednièki projekt...
{111154}{111218}Ozbiljno to misliš? | - Sranje...
{111313}{111376}Halo? Da?
{111412}{111473}Na vražjem sam piæu!
{111612}{111715}Slušaj, Gray, znaš da volim | tvoje filmove.
{111728}{111801}Doista si ozbiljan?
{111813}{111912}Smrtno sam ozbiljan. | Ovo je sami poèetak.
{111919}{111994}O rušenju sustava pomoæu | sustava. Razumiješ me?
{112016}{112084}O prièanju naše prièe.
{112118}{112178}Da, da...
{112194}{112232}Živjeli!
{115133}{115205}Možeš li mi dodati olovku? | - Meni govoriš?
{115227}{115334}Jedina si ovdje. - Znam. | Kako to možeš podnijeti?
{115374}{115469}Koji ti je vrag? - Ne znam, | John, valjda mi se ne sviða
{115475}{115533}provoditi svoje slobodno | vrijeme s drugim parom.
{115539}{115597}Što? - Niste li to ti i Gray?
{115609}{115722}Smiješno. To sam ja | tebe htio pitati.
{117244}{117342}Spremna? - Da. Moram biti u | galeriji u 9 da sve pripremim.
{117447}{117505}Znaš da te volim, zar ne?
{117512}{117573}Da, i ja tebe volim.
{118672}{118752}1990-2001 | autorice Jane Styros
{119108}{119168}Ovdje Jane, molim | ostavite poruku.
{119226}{119303}Jane, snimaš li?
{119311}{119364}Ovdje Nick. Nemam | hlaèe na sebi.
{119382}{119522}Jesi li tamo? Sranje! Nakon | 24h šibanja samoga sebe,
{119529}{119622}ne znam kako... I ti moraš | preuzeti odgovornost.
{119685}{119765}Zanimljivo je da te toliko | vrijeða rijeè "patološki."
{119773}{119838}Obièno se ljudi ne vrijeðaju | nebitnim stvarima.
{119885}{119925}U redu, da.
{120038}{120122}Bok, Gray. Shana ovdje. | Razmišljala sam o onome
{120130}{120194}što si govorio o tome da | ljudi jednostavno "prerastu"
{120202}{120251}jedni druge.
{120261}{120312}Nisam se baš lijepo | osjeæala zbog tih rijeèi.
{120327}{120482}Ali se doista nadam da æeš ti | odrasti. Èak i ako zbog mene.
{120516}{120560}I, možda si u pravu.
{120567}{120640}Možda æemo, razdvojeni, | oboje odrasti.
{120669}{120747}Ako ti ikada dojadi | druženje s tvojim idolima...
{120792}{120936}Bok, Briannon. Ovdje Ellen. | Obièno ne odgovaram strancima,
{120943}{121014}ali... - Što misliš?
{121176}{121248}Podsjeti me da te nikada | ne nazovem "patološkom."
{121309}{121393}Ne, sviða mi se. Uznemirujuæe | je, ali to mi se sviða.
{121420}{121472}Zašto uznemirujuæe?
{121481}{121542}Ne znam, osjeæam kao da | postoji toliko... jada.
{121644}{121773}U životima mojih otuðenih | ljubavnika. - Da, valjda.
{121822}{121965}Što John misli o svemu tome? | - Ima mnogo razumijevanja.
{122042}{122099}Kažeš to kao da je | to nešto loše. - Ne...
{122135}{122188}To je dobro.
{122304}{122346}Jesi li gledala onu epizodu | Zone sumraka kada tip
{122355}{122415}ima štopericu i može | zaustaviti vrijeme.
{122444}{122534}Onu kada sve zamrzne i | pljaèka banke? - Da.
{122545}{122626}Kako si se toga sjetio? | - Malo sam pripit.
{122691}{122778}Tvoj me rad malo podsjeæa | na to. Kao da sve zaustavi.
{122848}{122976}I slièno je filmovima. Uvijek | se možeš vratiti filmu,
{122984}{123039}jer se on nikada ne mijenja.
{123082}{123153}Da, ali sjeti se što se | dogodilo tipu iz Zone sumraka.
{123190}{123251}Sve je zaustavio, | i slomio mu se sat.
{123627}{123673}Jesi li gledala onu epizodu | Zone sumraka kada tip
{123680}{123737}ima štopericu i može | zaustaviti vrijeme.
{123749}{123838}Onu kada sve zamrzne i | pljaèka banke? - Da.
{123905}{123976}Kako si se toga sjetio? | - Malo sam pripit.
{124013}{124107}Tvoj me rad malo podsjeæa | na to. Kao da sve zaustavi.
{124384}{124451}Da, ali sjeti se što se | dogodilo tipu iz Zone sumraka.
{124486}{124565}Sve je zaustavio, | i slomio mu se sat.
{124795}{124927}Halo? - Bok, Mia je. | Još pišeš? - Da... Ne.
{124952}{125142}Oprosti. Danas æu kasno doæi. | Ideš u krevet? - 4 je ujutro.
{125164}{125236}Moram rano ustati. | - Dobro... - Bok.
{125502}{125582}Gray...
{125606}{125672}Èinim li to kako treba? | Je li pregrubo?
{126352}{126399}Gray...
{126682}{126759}Ne želim razgovarati o tome. | Uzmi stvari i idemo.
{126770}{126866}Koji ti je vrag? - Koji mi je | vrag? Koji je tebi vrag?
{126873}{126951}Kad si se poèela upucavati? | - Kad si ti postao Jake LaMotta?
{126959}{127010}U jednom trenu se buniš | koliko vremena provodimo
{127017}{127064}s Grayom, a u drugom je: | "Gray ovo, Gray ono..."
{127079}{127119}"Gray i ja imamo mnogo | toga zajednièkog."
{127133}{127230}Nisam ovo tražila! Vi | muškarci ste ljubomorne svinje!
{127240}{127305}Hvala Bogu što ne | generaliziraš. - U pravu si.
{127319}{127408}Ti si ljubomorna svinja. | Je li to bolje? - Bože...
{127425}{127529}Toliko sranja trpim od tebe | i nikada se ne bunim.
{127536}{127605}Možda se to ne bi dogodilo | da nisi beskièmenjak.
{127614}{127693}Tako je! - Ja sam kreten jer | imam razumijevanja?
{127724}{127778}Jer ti pomažem da prikupiš te | proklete vrpce kako bi
{127785}{127828}paradirala svojim životom. | - Onda nemoj!
{127874}{127936}Ti si nas dovela do ove | situacije. To si željela.
{127967}{128018}Ondje sam | gdje si me željela.
{128026}{128083}Ja sam bar imala nešto za | pokazati za svoj jad. A ti?
{128104}{128199}Kad si postala takva gadura? | - Kad si ti izgubio svoje
{128206}{128253}samopoštovanje i postao | psiæ koji trèi za zvijezdama?
{128263}{128318}Toliko te je ponijela pomisao | da izlaziš sa svojim
{128326}{128395}super-junakom, da ti nije palo | na pamet da mi se upucava.
{128403}{128453}I kad si konaèno primijetio, | nisi ni pomislio da te ne bih
{128465}{128537}nikada prevarila jer te | doista volim.
{128546}{128591}Lako si ti zaljubljen | u Graya Evansa.
{128601}{128634}Nisam zaljubljen | u Graya Evansa.
{128643}{128708}Zašto ga onda viðamo | gotovo svaki dan?
{128718}{128806}Ne èini li ti se èudnim da ne | znamo gotovo ništa o njemu?
{128945}{129020}Vi ste obojica krvopije. On | mrzi život, a ti ga nemaš.
{129044}{129103}Jebi se, Jane!
{129121}{129168}Što si mi to rekao?
{129280}{129349}Nikada mi nisi to rekao.
{129498}{129544}To je izvrsna stvar kod | ovakvih razgovora.
{129553}{129662}Vidiš pravo lice osobe. Ja sam | drolja, a ti ljubomorni gad.
{129719}{129803}Idemo. Kasnimo.
{129834}{129919}Možeš li navuæi sretno lice | na par sati ili æemo cmizdriti?
{129963}{130018}Mislim da æu moæi.
{130091}{130152}Zadnji put.
{130795}{130831}Bilo je zabavno.
{130837}{130886}Ja sam se zabavila.
{130895}{130973}I Sylvia Plath bi se zabavila | s toliko votke u sebi.
{131039}{131135}Dobra usporedba. Književna | poredba i sve ostalo...
{131168}{131237}Htio sam te usporediti sa | slavnim konceptualnim
{131244}{131307}umjetnikom, | ali takvi ne postoje.
{131332}{131383}Isuse...
{131413}{131467}Hoæemo li razgovarati | o tome veèeras?
{131486}{131539}Nemamo o èemu. | - Što to govoriš?
{131577}{131658}Što to govoriš? | - Gray? - Gray...
{131668}{131711}Nasmrt si me uplašio.
{131825}{131875}Gray, što to radiš?
{131893}{131934}Gray! Prestani!
{132012}{132089}Prestani!
{132413}{132465}Možeš li zaèepiti?
{132481}{132548}Zaèepi!
{132857}{132914}Tako si veliki pjevaè?
{132920}{132976}Bit æeš veliki pjevaè?
{132984}{133048}Sad više ne možeš | pjevati, kretenu!
{133581}{133643}Sada sam doista tužan.
{133884}{133944}Hladno mi je.
{134628}{134712}Bojim se da sam uèinio | nešto strašno.
{134723}{134852}Zovem se John Eckhart. | Živim u 611 Rialto Street.
{134859}{134981}Oteo sam Graya Evansa. | Da, onog glumca.
{135019}{135102}Imam pištolj i ne znam | što æu uèiniti.
{136108}{136209}Samo sam ti želio reæi da | mi je žao i da te volim.
{136396}{136438}Gray?
{136534}{136627}Što zapravo želiš?
{136676}{136825}Želiš biti sa mnom? | Je li to?
{136865}{137005}Ne... Ne radi se o seksu.
{137392}{137458}Nego o èemu, Gray?
{137829}{138038}Više ne vodimo ljubav.
{138097}{138166}Zašto misliš da je tako?
{138259}{138324}Ne znam...
{138335}{138555}Možda jer ti... Ne mogu | to ni izgovoriti.
{138587}{138692}Možda me više ne voliš. | - Više te ne poznajem.
{138724}{138780}Kako to možeš reæi?
{138786}{138837}Kako to možeš reæi?
{138868}{138930}Ja sam. Ovdje sam.
{139055}{139128}Voliš li me?
{139204}{139261}Bože, ovo je sranje.
{139266}{139314}Ovo je sranje.
{139364}{139405}Oprosti mi.
{139419}{139492}Prestani se isprièavati.
{139501}{139551}I prestani se ponašati | kao nevinašce.
{139567}{139615}Zanemario si me.
{139623}{139703}Bio si pijan. Plakao si, | i isprièavao se.
{139711}{139761}Opet bi isto uèinio.
{139805}{139879}Kako možeš oèekivati | da to izdržim?
{139931}{139972}Kako?
{140153}{140209}Jer se volimo.
{140310}{140367}Voljeli smo se.
{140381}{140437}Kada si govorio stvari kao:
{140443}{140538}"Prije tebe sam mislio | samo na posao i uspjeh.
{140558}{140646}Ali, kunem se, ništa mi to | sada ne bi znaèilo bez tebe."
{140653}{140735}Sjeæaš se toga? | Jedan film, Gray.
{140754}{140837}Glumi u jednome filmu, | i u njihovim si redovima.
{140881}{140939}Samome si sebi najgora | noæna mora.
{140951}{141008}Isti si kao drugi.
{141047}{141088}Proziran si.
{141123}{141180}Okusiš malo uspjeha, i...
{141331}{141423}John Eckhart, ovdje policija. | Primili smo vaš poziv.
{141430}{141487}Došli smo vam pomoæi.
{141497}{141548}Obeæajemo, ništa vam se | neæe dogoditi.
{141555}{141636}Ovo je malo previše za | malu svaðu, zar ne?
{141709}{141774}Uvijek sam govorio da si vatra | koja ukljuèuje sve alarme.
{141810}{141872}Gotovo je, Gray.
{142127}{142194}John, javi se!
{142313}{142377}Jedan od tvojih deèkiju? | Šalim se.
{142391}{142437}Nisam to trebao reæi.
{142454}{142506}Moraš me pustiti.
{142623}{142716}Što? - Moraš me pustiti.
{143265}{143296}Rez!
{143307}{143367}Gray, jesi li zadovoljan?
{143802}{143859}On mi je suprug!
{143866}{143916}Tko ste vi? | Tko je ovdje odgovoran?
{143925}{143963}John Eckhart!
{143973}{144002}Spusti oružje!
{144015}{144057}John, spusti oružje!
{144590}{144639}Gray!
{144688}{144756}John, spusti oružje!
{145060}{145099}Spusti oružje!
{145106}{145154}Može smiješak, Gray?
{145598}{145656}...pogoðen je sinoæ kad ga je | policija zamijenila za njegova
{145661}{145707}otmièara, obeæavajuæeg | redatelja èije prijateljstvo
{145714}{145789}s Evansom je preraslo u | kobnu opsesiju.
{145797}{145863}Gray Evans koji se proslavio | tek prije par godina
{145872}{145926}je slovio za jednu od | najveæih zvijezda
{145933}{145985}velikih ekrana.
{147414}{147560}Žao mi je, Shana. Htio | sam oprati rublje s tobom.
{147599}{147765}U redu je, mali. | Kako je prošlo?
{147778}{147943}Bio sam dobar, ali znam da ne | bih smio previše poluditi.
{147965}{148137}Sladak si kad poludiš. | Hoæeš pojesti nešto?
{148152}{148330}Zato sam toliko uzbuðen. | Kupio sam dva ogromna iceberga.
{148338}{148503}Hoæe li tko njegovu omiljenu | salatu? - Netko bi mogao.
{148517}{148666}Jer moje srce mora | malo smršavjeti.
{148696}{148786}Nedostajala si mi. | - Ti meni još više.
{148793}{148959}Nemojmo se nikada razdvajati | dulje od 4 sata, može? - Može.
{148967}{149147}Jesi li štogod dobro uslikala | danas? Nebo je bilo ludo plavo.
{149169}{149272}Hej, ljepotane, | daj da tebe uslikam.
{149411}{149465}Idemo.
{150732}{150788}Jednoga æeš me dana | ostaviti zbog nje, zar ne?
{150789}{151189}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan 
