{9}{57}Block 2 Pictures
{118}{148}Predstavljaju
{155}{200}U produkciji Jet Tone Films
{239}{284}RASPOLOŽENI ZA LJUBAV
{291}{315}U glavnim ulogama:
{323}{353}Maggie Cheung Man-Yuk
{360}{390}Tony Leung Chiu-Wai
{397}{421}Režija:
{430}{456}Wong Kar-Wai
{545}{569}Trenutak bez sna.
{575}{617}Držala je glavu spuštenu
{622}{661}i dala mu priliku da priðe.
{666}{715}Ali on nije mogao,|nije imao hrabrosti.
{721}{759}Ona se okreæe i odlazi.
{770}{813}HONG KONG, 1962.
{923}{984}Jedite, riba je|vrlo svježa danas...
{1133}{1174}Oprostite što vam prekidam veèeru.
{1179}{1238}U redu je, hajdemo sjesti ovdje.
{1289}{1331}Dosta je kasno!
{1340}{1379}Sada sam se vratila s posla.
{1400}{1432}Kako da vas oslovljavam?
{1437}{1473}Zovite me gða Suen.
{1478}{1521}- A vi?|- Moj muž se zove Chan.
{1527}{1594}- Nazovite me kada odluèite.|- Hoæu.
{1602}{1647}Zapisali ste moj broj?
{1654}{1678}Jesam.
{1685}{1722}Dobro, ispratit æu vas.
{1727}{1784}- Ne morate.|- Nije problem!
{2044}{2072}Dakle, dogovorili smo se!
{2078}{2110}Puno vam hvala!|Moram iæi.
{2115}{2137}- U redu.|- Doviðenja.
{2142}{2172}- Svako dobro, doviðenja!
{2210}{2249}Da li imate slobodnu sobu?
{2254}{2342}Žao mi je, upravo je iznajmljena|onoj gospoði.
{2357}{2381}Hvala, u svakom sluèaju.
{2403}{2433}Koliko vas ima?
{2452}{2482}Samo ja i moja žena.
{2488}{2572}- Zašto ne probate kod susjeda?|- Imaju slobodnu sobu?
{2580}{2719}Da, sin g. Kooa upravo se oženio...|Njegova soba je prazna.
{2732}{2752}Hvala vam.
{2758}{2834}- Jako ste ljubazni. Pitajte njih.|- Hvala.
{2984}{3010}Ovuda, hajde!
{3015}{3047}Ne ta soba!
{3053}{3094}Ups, opet greška!
{3180}{3231}Pazite! Uza zid, tamo.
{3371}{3408}Ormariæ tamo!
{3414}{3442}Pazite!
{3465}{3504}Nemojte ništa razbiti!
{3511}{3557}Ne na radio!
{3574}{3596}G. Chow...
{3602}{3661}Puno stvari za jedan par!
{3668}{3721}- Ormar nije moj.|- Opet greška?
{3726}{3750}Ide kod susjeda.
{3754}{3800}Vrijedi, kod susjeda!
{3814}{3908}Ovo nisu moje cipele!|Nosite ih kod susjeda.
{3959}{4029}Kakva sluèajnost!|Seliti se istog dana!
{4044}{4079}Da li je g. Chan tu?
{4090}{4161}Radi u inozemstvu.|Vraæa se iduæi tjedan.
{4172}{4219}Trebali ste prièekati.
{4235}{4296}Previše je za vas samu.
{4307}{4364}- Snalazim se.|- Pozvat æu Amah da pomogne.
{4369}{4411}Ne treba, mogu sama.
{4416}{4453}Što se ovdje dogaða?
{4483}{4507}Pazite na ogledalo!
{4513}{4562}Gðo Chan, ostavit æu vas.
{4719}{4772}- Ovi èasopisi nisu moji.|- Opet greška?
{4777}{4814}Nema veze, samo ih ostavite tamo.
{4830}{4881}Pazite kako vješate ogledalo,|vrlo je osjetljivo!
{4887}{4928}Da li su ovi èasopisi vaši?
{4953}{4996}Da, od mog muža.
{5007}{5043}On razumije japanski?
{5048}{5099}Pomalo, šef mu je Japanac.
{5104}{5139}Kako da vas oslovljavam?
{5144}{5170}Moj muž se zove Chan.
{5176}{5214}Ja sam Chow...|Ostavit æu vas.
{5224}{5250}Hvala vam, g. Chow.
{5255}{5285}Nema na èemu.
{5350}{5386}Pitat æu gðu Chan...
{5455}{5512}Gðo Chan, jedite s nama|prije nego što krenete!
{5522}{5571}Ne, hvala,|žurim na aerodrom.
{5577}{5634}- Muž vam se vraæa?|- Da.
{5640}{5680}Onda vas neæu zadržavati.
{5727}{5767}- Izlazite?|- Da.
{5829}{5857}Oprostite što kasnim!
{5863}{5891}Amah, toèi pivo.
{5940}{5962}Živjeli!
{6000}{6074}Gðo Chow, morate probati|šangajska jela.
{6080}{6150}Gdje je otišla gða Chan ovako kasno?
{6185}{6244}Èeka muža na aerodromu.
{6250}{6295}Zato izgleda drugaèije.
{7695}{7761}Sve je spakirano,|èuvaj se.
{7767}{7797}Hoæu.
{7870}{7934}Na koliko ideš ovaj put?
{7941}{7988}Dva do èetiri tjedna.
{8006}{8106}Ne zaboravi donijeti|još dvije onakve torbice.
{8113}{8135}Za koga?
{8141}{8163}Za mog šefa.
{8169}{8201}Dvije?
{8206}{8240}Znaš zašto.
{8245}{8290}Razlièitih boja?
{8321}{8376}Može i istih! Koga briga?
{8398}{8428}Dobro...
{8690}{8815}Gðo Ho,|g. Ho je još na sastanku.
{8821}{8896}Kasno æe stiæi kuæi...|Nemojte ga èekati za veèeru.
{8965}{9020}Da, imamo puno posla|u posljednje vrijeme.
{9049}{9143}Da, reæi æu mu da vas nazove|èim stigne.
{9338}{9377}Da li ste zvali moju ženu?
{9382}{9445}Da, rekla sam da æete|se vratiti kasno.
{9462}{9528}- Sredili ste rezervacije u restoranu?|- Stol za dvoje u osam.
{9539}{9609}Gðica Yu je javila|da je krenula.
{9631}{9736}Vratit æu se poslije veèere,|da vam donesem nešto?
{9745}{9794}Ne, hvala, snaæi æu se.
{9823}{9924}Možete otiæi kada završite,|ja æu zakljuèati.
{10027}{10078}- Dobra veèer, g. Ho!|- 'Veèer!
{10525}{10580}- Izlazite , gðo Chan?|- Da.
{10690}{10722}Izlazite tako kasno?
{10727}{10769}Samo idem po rezance.
{10779}{10836}Amah kuha svinjsku juhu,|pridružite nam se.
{10842}{10912}Hvala, ustvari i nisam gladna,|samo bih malo na zrak.
{10922}{10964}Previše ste ljubazni.
{10970}{11003}Drugi put!
{11076}{11160}Svi su ogladnjeli,|hajdemo jesti.
{11216}{11255}Da li si prièao s Mingom?
{11286}{11341}Dobro, iæi æu s nekim drugim!
{11372}{11416}Šalim se!
{11426}{11499}Doæi æu ranije veèeras,|vidimo se!
{11691}{11719}Chow!
{11725}{11749}Dolazim!
{11905}{12018}Vrijeme da se krene!|Završi to sutra!
{12028}{12085}Ne, skoro sam gotov...
{12092}{12122}Ovaj, Ming...
{12139}{12209}- Treba mi nekoliko dana slobodno|iduæeg mjeseca. - Zašto?
{12224}{12296}Obeæao sam ženi putovanje.|Založi se za mene, hoæeš li?
{12315}{12372}Poprièat æu sa šefovima.
{12377}{12424}Ali, sljedeæi ruèak ti plaæaš.
{12429}{12455}Hoæu.
{12466}{12492}Hvala, Ming!
{12570}{12600}Gotov je!
{12606}{12657}Ne, sam æe se iskljuèiti!
{12688}{12737}Nije gotov, rekao sam ti!
{12771}{12830}Lonac za rižu!|Vaš je, gðo Koo?
{12844}{12951}Ne, to je previše za nas!|Od gðe Chan je.
{13014}{13051}Muž mi ga je donio iz Japana.
{13056}{13100}Htjela sam pokazati gði Koo|koliko je dobar.
{13117}{13147}Sada je gotov!
{13156}{13174}Gðo Chan...
{13398}{13505}Da li bi g. Chan mogao|meni donijeti jedan?
{13512}{13536}Nema problema!
{13548}{13612}G. Chow, i vi biste trebali|uzeti jedan.
{13619}{13716}Vaša žena èesto dolazi|kasno kuæi.
{13752}{13795}Ne bih htio muèiti gðu Chan.
{13801}{13854}Dobrosusjedski je, zar ne?
{13884}{13968}Nije problem! Reæi æu mu da|kupi jedan sljedeæi put.
{13984}{14010}Hvala vam!
{14231}{14292}Probajmo rižu.
{14338}{14410}G. Chan, oprostite što sam vas|namuèio oko lonca.
{14414}{14460}Stvarno, nije bio problem.
{14489}{14548}Koliko sam vam dužan?
{14554}{14601}Vaša žena mi je platila.
{14608}{14632}Stvarno?
{14637}{14673}Nije vam rekla?
{14687}{14723}Radi u noænoj smjeni.
{14729}{14780}Èesto zaspim prije nego što doðe.
{14785}{14825}Sigurno joj je teško.
{14830}{14895}Da. Gða Chan se nije još vratila?
{14900}{14978}Vraæa se uskoro...|Treba vam za nešto?
{14992}{15041}Prijatelj mi putuje u Singapur.
{15047}{15102}Zanima me da li mu može|nabaviti jeftinu kartu.
{15107}{15152}Pitat æu je kad se vrati.
{15181}{15226}Previše vas gnjavim.
{15232}{15306}Ma ne, susjedi smo!
{15323}{15362}Ostavit æu vas.
{15514}{15543}Tražio si me?
{15551}{15620}Jesam, gdje si do sada?
{15637}{15665}Što ima?
{15683}{15775}Gða Chan je zvala, ostavio si|šešir u njenoj kancelariji.
{15781}{15848}Namjerno! Trebao mi je|izgovor da se vratim.
{15858}{15898}Znam ja tvoje fore!
{15926}{15961}Udana je.
{15967}{16011}Znam, zato sam i otišao.
{16016}{16089}Inaèe bih se ja doselio|u susjedstvo.
{16095}{16183}Da ti žena nije tako privlaèna,|puno bi se živcirala.
{16251}{16292}Nisam ja kao ti.
{16342}{16386}Molim te, nazovi gðu Chan za mene.
{16393}{16468}Pokupit æu šešir sutra.|I voditi je na ruèak!
{16488}{16516}Sanjaj!
{16522}{16589}Odnijet æe šešir kuæi.|Ja æu ga donijeti sutra.
{16608}{16675}Šališ se! I ti si|mi neki prijatelj!
{16680}{16741}Znaš što, hajdemo po nju sada!
{16773}{16834}Trebala bi završiti s poslom.|Možemo iæi zajedno!
{16849}{16888}Nemam vremena za ovo.
{16893}{16913}Chow!
{16920}{16981}Da! Bježi odavde, imam posla.
{16987}{17052}Bit æu kod tebe.
{17093}{17123}Hej, Ping!
{17323}{17365}G. Chow, da li je g. Koo|kod kuæe?
{17373}{17440}Izašao je...|Opet niste kupili novine?
{17445}{17508}- Da, svratit æu kasnije.|- Možda ih ja mogu pronaæi.
{17513}{17550}Hvala.
{17805}{17845}- Ove?|- Da.
{17875}{17959}Uvijek sam volio te serijale,|nerado bih propustio epizodu.
{17969}{18012}Stvarno? I vi ih volite?
{18059}{18103}Èak sam pomišljao da napišem jedan!
{18108}{18138}Zašto niste?
{18145}{18206}Nisam mogao poèeti,|pa sam odustao.
{18211}{18262}Nisam roðen da pišem|borilaèke prièe!
{18268}{18321}Ali možete ih uzimati iz moje|kolekcije kada god poželite.
{18327}{18397}Ne bih sada, možda drugi put.|Hvala.
{18402}{18440}Nema na èemu!
{18615}{18654}Tko je? Gða Chan!
{18671}{18724}Samo bih htio vratiti ovo|g. Chowu. Je li tu?
{18731}{18778}Nije ga bilo nekoliko dana.
{18783}{18811}Zašto?
{18821}{18860}Posvaðali su se.
{18877}{18981}Ostavite ih meni,|ja æu mu ih dati.
{19006}{19028}Hvala vam.
{19237}{19265}Ništa!
{19288}{19354}Veèeras mijenjam nekoga.
{19402}{19444}Èujemo se poslije.
{19539}{19583}Ne moraš dolaziti po mene!
{19651}{19693}Veæ je otišla.
{19709}{19789}Stvarno? Htio sam je|izvesti na veèeru.
{19803}{19871}Nije vam rekla da danas|ranije odlazi?
{19876}{19941}Nikada se ne sjeti reæi mi.
{19988}{20033}Možda je veæ stigla kuæi.
{20059}{20118}- Idem ja.|- Dobro, doviðenja.
{23583}{23607}Bok!
{23910}{23940}Nisi u bolnici!
{23946}{24007}Ne spominji mi je!|Posudi mi 30 dolara!
{24015}{24041}Što æe ti?
{24050}{24095}Moram saèuvati obraz!
{24100}{24128}U èemu je stvar?
{24134}{24168}Ah Hoi je uprskao.
{24173}{24251}Dao mi je savjet za utrku,|rekao je da je to sigurna stvar.
{24269}{24373}Nisu mi stigli ni|konce izvaditi...
{24378}{24433}a ja sam se kladio|u sve što imam.
{24438}{24473}I gaæe sam izgubio!
{24483}{24527}Što si oèekivao?
{24545}{24596}Mislio sam da mi je sretan dan.
{24602}{24647}Bilo kako bilo,|ostala su mi 2 dolara.
{24660}{24742}Pa sam otišao u javnu kuæu.
{24753}{24795}Seks u takvom stanju?
{24800}{24859}Mislio sam da æe mi donijeti sreæu.
{24900}{24959}Što si mogao dobiti za 2 dolara?
{24984}{25067}Stara sam mušterija,|Kwai-fei mi daje na kredit.
{25083}{25115}Dobivaš na kredit?
{25120}{25208}Ostavio sam osobnu iskaznicu i|rekao da æu donijeti novac.
{25220}{25275}Mislio sam da æu lako skupiti|nekoliko dolara.
{25285}{25334}Ali do sada ništa,|i veæ puno kasnim.
{25340}{25354}Pa?
{25363}{25407}Èetverooka je bila tamo juèer.
{25412}{25469}Vidio sam je kako pred svima|maše mojom osobnom iskaznicom.
{25474}{25496}Kakva sramota!
{25502}{25551}Hajde, posudi mi 30 dolara!
{25704}{25746}Ovoliko ti mogu dati.
{25765}{25818}10 dolara treba meni.
{25885}{25929}Vraæam ti iduæeg mjeseca.
{25949}{26004}- Hajdemo nešto prigristi.|- Molim?
{26012}{26082}Danas sam jeo samo|malo won-ton rezanaca.
{26087}{26135}Èekaj da završim ovo.
{26208}{26269}Nisam siguran da bih ti ovo|trebao reæi...
{26279}{26301}Što?
{26306}{26365}Vidio sam tvoju ženu|juèer na ulici.
{26372}{26410}Pa što?
{26445}{26522}Bila je s nekim tipom.
{26634}{26675}Vjerojatno s prijateljem.
{26732}{26789}Samo sam mislio da bi|trebao znati.
{26829}{26904}Gðica Yu? Ja sam.
{26933}{27027}G. Ho je još uvijek na sastanku.|Neæe imati vremena za veèeru.
{27071}{27120}Da, imamo puno posla.
{27218}{27244}Hoæu.
{27262}{27307}Reæi æu g. Hou da nazove.
{27441}{27504}- Jeste li zvali gðicu Yu?|- Jesam.
{27514}{27540}Što je rekla?
{27546}{27595}Da je nazovete kasnije.
{27600}{27657}A gða Ho kaže da je spremna|razrezati svoju roðendansku tortu.
{27662}{27691}Poruèuje da požurite kuæi.
{27697}{27756}- Jeste li mi nabavili poklon za nju?|- Da, ovo.
{27762}{27806}- Što je unutra?|- Šal.
{27819}{27891}- Mislim da æe joj se svidjeti.|- Hvala vam.
{27897}{27928}A ovo vam je ostatak.
{27933}{28015}Uvijek vas muèim,|neka vam bude za autobus.
{28034}{28091}Zašto ne biste veèerali s nama?
{28097}{28172}Hvala, planirala sam|pogledati film veèeras.
{28177}{28219}Onda vas neæu zadržavati.
{28224}{28299}Sutra neæe biti posla,|uzmite jutro slobodno.
{28539}{28590}Izlaziš veèeras?
{28638}{28679}Ne zaboravi kljuèeve.
{28684}{28745}Cijelo susjedstvo veèera u gradu.
{28754}{28841}Imam puno posla,|vratit æu se kasno.
{29210}{29250}Što želite, gðo Chan?
{29260}{29288}Èula sam glasove,
{29293}{29350}mislila sam da su se|gospodin i gospoða Koo vratili.
{29357}{29425}Nisu još, da li vam ja|mogu pomoæi?
{29470}{29523}Ne, samo sam htjela|s nekim poprièati.
{29554}{29600}- Sami ste?|- Jesam.
{29685}{29726}Rano ste se vratili!
{29743}{29816}Došla sam se odmoriti.|Ne osjeæam se dobro...
{29863}{29924}Što je u pitanju?|Imam neke lijekove...
{29947}{30020}Ne brinite,|prespavat æu to.
{30063}{30114}U tom sluèaju,|ostavit æu vas.
{30272}{30310}Tvoja žena.
{30368}{30413}Da li si prièao sa svojom ženom?
{30441}{30485}Onda se neæemo više viðati.
{31629}{31674}Ima li vijesti sa Filipina?
{31679}{31707}Da, telegram.
{31712}{31756}Bijesni tajfun, pa je brod|još uvijek u luci.
{31778}{31893}Molim vas, recite Chanu da æe|isporuka možda kasniti.
{31904}{31943}Pitajte ga da li je to problem.
{32029}{32101}Vaša žena je zvala.|Ne morate iæi po nju.
{32106}{32149}Igra mahjong sa gðom Lau.
{32154}{32215}Èekat æe vas u restoranu|u 5:30.
{32290}{32331}A ovo je poklon od gðice Yu.
{32340}{32366}Bila je ovdje?
{32372}{32417}Ne, poslala je.
{32422}{32503}Kaže da æe veèerati sama|pošto vam je roðendan.
{32510}{32572}Moli da je nazovete|kada imate vremena.
{32618}{32685}- Donijet æu vam još jednu kavu.|- Hvala.
{33239}{33265}Hvala.
{33398}{33443}Dobro vam stoji ta kravata.
{33448}{33557}Primijetili ste?|Dosta je slièna staroj.
{33591}{33652}Stvari se primijeæuju|kada se obrati pažnja.
{33944}{33972}Idem sada.
{33977}{34055}Ako Chan bude imao problema,|zovite me u restoran.
{34061}{34110}Hoæu.|Zašto ste promijenili kravatu?
{34115}{34157}Nova je bila prenapadna.
{34162}{34202}Držat æu se starih.
{34207}{34251}Ne zaboravite zakljuèati.
{36808}{36883}Usput, nisam skoro|vidio vašeg muža.
{36900}{36961}U inozemstvu je,|na službenom putu.
{36974}{37044}Zato vas viðam kod|trgovca rezancima.
{37067}{37118}Ne volim kuhati za sebe.
{37136}{37191}Ni ja nisam skoro vidjela|vašu ženu.
{37218}{37290}Majka joj je bolesna,|pa je kod nje.
{37330}{37371}Tako, znaèi.
{37391}{37419}Laku noæ!
{37436}{37454}Laku noæ!
{37471}{37516}Gðo Chan, vratili ste se!
{37521}{37560}Kiša tako jako pada!
{37565}{37607}Htjela sam uzeti kišobran|i krenuti vas tražiti.
{37620}{37642}Jako ste dobri.
{37648}{37676}Amah, tko je?
{37682}{37722}- Gða Chan.|- Gðo Suen!
{37737}{37840}Uhvatila vas je kiša?|Rekla sam da možete jesti s nama!
{37861}{37912}Drugi put... uživajte u igri.
{37971}{38084}Muž joj nikada nije tu.|Tužno je vidjeti je tako samu.
{38089}{38179}Tako se oblaèi kada|ide po rezance?
{38450}{38501}G. Chow!|Otkud vi ovdje?
{38518}{38567}Gða Koo ima telefonski poziv.
{38602}{38638}Kasno se vraæate.
{38643}{38688}Bila sam u kinu.
{38703}{38742}Idem ja.
{38919}{38943}Halo?
{38958}{39002}Da, trenutak.
{39009}{39062}- Tko je?|- Zovu gðu Chan.
{39321}{39417}Sigurno je èudno što vas zovem|u izlazak, ali moram vas pitati...
{39426}{39475}Torbica s kojom|sam vas vidio veèeras...
{39480}{39521}Gdje ste je kupili?
{39539}{39581}Zašto pitate?
{39640}{39724}Vrlo je elegantna.|Htio bih kupiti ženi jednu.
{39782}{39827}G. Chow, tako ste|dobri prema njoj!
{39856}{39934}Ne baš! Moja žena je|vrlo izbirljiva.
{39947}{40025}Roðendan joj je za nekoliko dana.|Ne znam što da joj poklonim.
{40134}{40191}Možete li mi vi|nabaviti jednu?
{40210}{40288}Možda joj se ne bi svidjela|ista takva.
{40340}{40397}U pravu ste, nisam|o tome razmišljao.
{40446}{40481}Ženama bi smetalo.
{40487}{40554}Da, naroèito zato jer smo|susjedi.
{40622}{40675}Da li ih ima u drugim bojama?
{40728}{40775}Morat æu pitati muža.
{40792}{40816}Zašto?
{40841}{40923}On mi ju je donio sa službenog puta|u inozemstvu.
{40929}{40971}Ne prodaju se kod nas.
{41068}{41104}Onda ništa.
{41265}{41291}Ustvari...
{41297}{41346}I ja bih vas nešto pitao.
{41398}{41418}Što?
{41457}{41491}Gdje ste kupili kravatu?
{41564}{41611}Ne znam odakle mi.
{41629}{41674}Žena mi kupuje kravate.
{41684}{41706}Stvarno?
{41764}{41899}Ovu mi je donijela sa službenog puta|u inozemstvu.
{41911}{41950}Ne prodaje se kod nas.
{41983}{42024}Kakva sluèajnost!
{42090}{42120}Da.
{42258}{42293}Ustvari...
{42350}{42416}Moj muž ima istu takvu.
{42445}{42502}Kaže da je poklon od šefa.
{42508}{42549}Pa je nosi svaki dan.
{42674}{42735}A moja žena ima torbicu|istu kao vašu.
{42758}{42791}Znam,
{42797}{42823}vidjela sam je.
{42890}{42947}Na što ciljate?
{43232}{43295}Mislila sam da sam|ja jedina koja zna.
{43741}{43786}Pitam se kako je poèelo...
{44173}{44257}Kasno je...|žena vam se neæe ljutiti?
{44281}{44354}Navikla je, nije ju briga.
{44415}{44455}A vaš muž?
{44466}{44513}Sigurno veæ spava.
{44614}{44656}Da ostanemo zajedno veèeras?
{44825}{44884}Moj muž nikada ne bi rekao|tako nešto.
{44944}{44984}Što bi on rekao?
{44999}{45052}Ne znam, ne to.
{45073}{45126}Netko je morao uèiniti|prvi korak.
{45132}{45172}Tko bi drugi mogao?
{45303}{45375}Kasno je...|žena vam se neæe ljutiti?
{45394}{45455}Navikla je, nije je briga.
{45490}{45528}A vaš muž?
{45549}{45596}Sigurno veæ spava.
{46115}{46155}Ne mogu to izgovoriti.
{46261}{46300}Razumijem.
{46360}{46413}U svakom sluèaju,|veæ se dogodilo.
{46419}{46484}Nije bitno tko je uèinio|prvi korak.
{46576}{46623}Da li stvarno poznaješ|svoju ženu?
{47347}{47408}- Naruèi za mene.|- Zašto?
{47514}{47569}Nemam predodžbu što|tvoja žena voli.
{47822}{47866}A tvoj muž?
{48855}{48885}Voliš ljuto?
{48981}{49030}Tvoja žena voli ljuta jela.
{49712}{49776}Zašto si me zvao|danas na poslu?
{49887}{49969}Nisam imao što raditi.|Htio sam ti èuti glas.
{50080}{50172}Vješt si kao moj muž.|Pravi je laskavac.
{50808}{50859}Zašto me nisi zvao danas?
{50884}{50935}Bojao sam se da ti se|neæe svidjeti.
{50973}{51015}Onda me nemoj više zvati.
{51401}{51464}Gðo Chan!|Pismo od vašeg muža.
{51528}{51583}Nije za mene, veæ za|g. Chowa u susjedstvu.
{51588}{51691}Zbog japanske marke sam mislila|da je od vašeg muža.
{51712}{51751}Pa, pogriješila sam.
{52139}{52178}Žena ti je u Japanu?
{52227}{52258}Kako si znala?
{52319}{52370}Što piše u pismu?
{52378}{52406}Ništa posebno.
{52458}{52511}Piše li kada æe se vratiti?
{52543}{52570}Ne.
{52595}{52655}Što misliš,|što rade sada?
{53525}{53574}- Jesi li dobro?|- Jesam.
{53606}{53650}Molim vas, stanite ovdje!
{53665}{53689}Zašto?
{53705}{53744}Izaæi æu prva.
{53769}{53801}Neka, ja æu.
{55316}{55370}- Gðo Chan!|- Ping! Vratili ste se?
{55393}{55417}Bili ste kod g. Chowa?
{55421}{55486}Da, htio sam da odemo na ruèak.|Ali nije mu dobro.
{55491}{55571}- Što mu je?|- Ima groznicu. Sam je.
{55577}{55638}Idem mu kupiti|nešto za jelo.
{55656}{55691}Dolje rade dobru rižu.
{55695}{55733}Neæe rižu.
{55742}{55771}Što hoæe?
{55777}{55843}Ne može ništa èvrsto,|pa traži sirup od sezama.
{55848}{55881}Baš je težak!
{56018}{56061}Amah!
{56069}{56133}Gðo Suen, na krovu je,|vješa rublje.
{56138}{56199}- O, vratili ste se.|- Da. Izašli ste?
{56204}{56286}Bliži se roðendan moje majke.
{56292}{56341}Pa sam je vodila da kupimo|tkanine.
{56345}{56403}Trajalo je cijeli dan,|mrtva sam!
{56412}{56461}I bila sam kod frizera...|Je li lijepa?
{56466}{56490}Vrlo!
{56495}{56534}Što kuhate?
{56556}{56619}Odjednom sam se zaželjela|sirupa od sezama.
{56630}{56693}Cijeli lonac je za vas?
{56704}{56763}Pomislila sam, kad sam veæ tu,|skuhat æu pun lonac.
{56782}{56825}Tako ste pažljivi!
{56843}{56883}- Probajte, molim vas.|- Hoæu.
{56911}{56939}Kakva sluèajnost!
{56945}{56982}Izlaziš?
{56987}{57062}Idem na rezance,|umirem od gladi.
{57073}{57101}Gladna si? Hoæeš li sa mnom?
{57133}{57157}Ne, hvala.
{57181}{57216}Ti si s posla?
{57224}{57263}Sigurno si jako optereæena.
{57268}{57345}Ustvari, bila sam|u kinu.
{57369}{57408}Stvarno? Kakav je bio film?
{57419}{57437}Onako.
{57456}{57507}Nekad sam volio|otiæi u kino.
{57512}{57554}Nekad si imao puno hobija.
{57558}{57636}Kada si sam, imaš vremena|za mnoge stvari.
{57653}{57702}Sve se mijenja kada se oženiš.
{57708}{57754}Sve odluke su zajednièke...
{57759}{57782}Je li tako?
{57855}{57937}Ponekad se pitam kakav bih bio|da se nisam oženio.
{57942}{57989}Jesi li ikada razmišljala o tome?
{58044}{58068}Možda sretniji!
{58161}{58239}Nisam znala da je braèni život|tako kompliciran!
{58263}{58298}Kad si sam,
{58303}{58366}odgovoran si samo za sebe.
{58376}{58420}Kad si u braku,
{58444}{58505}nije dovoljno da tebi dobro ide.
{58555}{58649}Nemoj se predavati crnim mislima,|možda æe se brzo vratiti.
{58736}{58758}A ti?
{58780}{58837}Ustvari, u istom smo sosu.
{58906}{58948}Ali, ja se ne predajem crnim mislima.
{58973}{59014}Nisam ja kriv.
{59033}{59100}Neæu gubiti vrijeme|razmišljajuæi gdje sam pogriješio.
{59105}{59149}Život je prekratak.
{59181}{59220}Nešto se mora promijeniti.
{59258}{59298}Pa, kakav ti je plan?
{59336}{59418}Hoæu napisati|borilaèki serijal.
{59444}{59520}Ustvari, veæ sam poèeo.|Pokazat æu ti.
{59525}{59553}Odlièno!
{59574}{59645}I ti ih voliš, zašto mi ne bi|pomogla da ga napišem?
{59651}{59734}Ne znam kako,|ja ih samo èitam!
{59740}{59795}Mogli bismo diskutirati.
{59827}{59869}U redu, dat æu sve od sebe.
{59908}{59956}Nisam ti zahvalio|za sirup od sezama.
{59965}{60043}Nema potrebe,|ionako sam ga radila.
{60074}{60164}Nevjerojatno, meni se|baš jeo tog dana.
{60178}{60227}Stvarno? Kakva sluèajnost!
{60236}{60271}Stvarno je bila!
{60317}{60364}Idem po one rezance.
{63893}{63959}Opet! Na pola veèere -|on pijan! Grozno!
{63965}{64039}Rekla sam ti da staneš!|Što sam još mogla?
{64226}{64250}Ja sam!
{64255}{64288}Uplašio si me.
{64294}{64333}Kako je g. Koo?
{64344}{64381}Pijan, kao i obièno.
{64599}{64654}Nisam oèekivao da æe se|vratiti tako rano!
{64707}{64779}Kad si veæ zarobljena ovdje,|dovrši rezance.
{64864}{64907}Vjerojatno æe brzo otiæi.
{65175}{65210}Hoæeš malo juhe?
{65284}{65326}Hoæeš malo juhe?
{65599}{65659}Gðo Suen! Igramo ovdje veèeras!
{65684}{65748}Da, gða Koo dijeli|sa svojim mužem.
{65764}{65817}Mogao bih i ja to.
{65822}{65875}Ne, ne bismo vas muèili.
{65903}{65958}Igrat æete cijelu noæ?
{65967}{66028}Ne, samo osam partija.
{66139}{66182}Igrat æe do jutra?
{66208}{66261}Gða Suen kaže samo osam partija.
{66267}{66306}Vjeruješ li u to?
{66457}{66539}Odmori se malo,|probudit æu te kada završe.
{66554}{66582}A ti?
{66594}{66641}Dovršit æu poglavlje.
{66966}{67001}Dokle si stigao?
{67007}{67054}Pijani majstor se upravo pojavio.
{67059}{67106}Kada je on ubaèen?
{67131}{67160}Upravo sada!
{67720}{67771}G. Chow, doma tako rano?
{67776}{67842}- Izašao sam po nešto hrane.|- Nema posla danas?
{67847}{67890}Nije mi baš dobro,|ostat æu kod kuæe.
{67895}{67948}Bolesnik ne bi trebao jesti|svu tu ljepljivu rižu.
{67953}{67992}Uzeo sam i za poslije.
{67998}{68041}Nemojte pretjerivati!
{68054}{68074}Dobro jutro!
{68080}{68115}Dobro jutro,|je li gotova partija?
{68121}{68249}Ne još, ali g. Yang mora na posao.|G. Tsai æe ga zamijeniti.
{68287}{68338}Da li si zvao moje na poslu?
{68344}{68372}Da.
{68379}{68418}Što si im rekao?
{68424}{68479}Da se ne osjeæaš dobro.
{68497}{68540}Da li su te pitali tko si?
{68545}{68571}Ne.
{68644}{68703}Vjerojatno su mislili|da sam tvoj muž.
{68718}{68782}G. Ho zna da je na putu.
{68793}{68834}Pretvaraj se da se vratio.
{69047}{69098}Možda smo previše oprezni?
{69103}{69144}Ionako sam èesto ovdje.
{69150}{69199}Nismo se trebali uspanièariti.
{69237}{69311}Pa, banuli su|bez najave.
{69316}{69359}Što bi drugo pomislili?
{69438}{69483}Èovjek ne može biti|bezgriješan.
{70436}{70462}Možeš iæi!
{71047}{71113}- Amah!|- Gðo Chan! Kasno se vraæate!
{71128}{71177}Danas sam imala puno posla.
{71188}{71245}Nisam vas vidjela jutros.
{71250}{71295}Doruèkovala sam s majkom.
{71301}{71354}Niste bili tu kada sam otišla.
{71383}{71405}Gdje je gða Suen?
{71411}{71499}Spava, igrala je|mahjong cijeli dan.
{71505}{71558}- Budite tihi, da je ne probudite.|- U redu!
{71567}{71614}Gðo Chan, što vam je s nogom?
{71620}{71669}Nove cipele.
{72780}{72833}Èemu specijalna veèera?
{72847}{72940}Pošto neæeš uzeti|svoj dio honorara...
{72973}{73041}Sve što sam radila,|bilo je samo da ti dam nekoliko ideja.
{73065}{73125}Pojavile su se nove|narudžbe za serijal.
{73132}{73173}Bit æe još posla.
{73178}{73271}Stvarno? Tako brzo?|Nije li to previše posla?
{73279}{73341}Zato tražim novi stan.
{73349}{73377}Zašto?
{73420}{73446}Za pisanje!
{73472}{73521}Tako je zgodnije.
{73536}{73629}Nema nièega izmeðu nas,|ali ne želim glasine.
{73673}{73716}Što misliš?
{73738}{73789}Èemu rasipanje novca?
{73801}{73906}Ne trebam ti ja,|možeš pisati sam.
{74858}{74903}Koga tražite?
{74909}{74948}Chow Mo-Wan?
{74956}{75014}Nije dolazio nekoliko dana.
{75079}{75126}I mi ga tražimo.
{75174}{75227}A tko ga zove?
{75291}{75330}Što da mu poruèim?
{75378}{75427}Nije problem, doviðenja.
{75727}{75772}Molim te, odnesi ovo|u raèunovodstvo.
{75778}{75840}I sutra pozovi majstore|za klimu.
{75846}{75870}G. Ho!
{75909}{75960}Ne morate ostajati|ako je sve obavljeno.
{75965}{76006}- Ja æu zakljuèati.|- Dobro.
{76297}{76321}Halo?
{76453}{76492}Gdje si?
{78019}{78062}Doæi æu opet sutra.
{78082}{78144}Ne treba,|kada odspavam, bit æu dobro.
{78160}{78205}Nije problem.
{78226}{78286}Donijet æu ti nešto za jelo...|Što bi volio?
{78292}{78325}Svejedno.
{78342}{78408}Idem sada. Odmori se.
{78414}{78459}Nazovi me kada stigneš kuæi.
{78471}{78539}Pusti da zvoni tri puta,|pa prekini vezu.
{78562}{78580}U redu.
{78755}{78798}Nisam mislio da æeš doæi.
{78893}{78938}Neæemo biti kao oni.
{78982}{79008}Vidimo se sutra.
{82279}{82320}Reci mi iskreno...
{82390}{82433}Da li imaš ljubavnicu?
{82497}{82538}Ti si luda!
{82607}{82644}Tko ti je to rekao?
{82650}{82691}Nema veze tko.
{82710}{82753}Imaš li ili nemaš?
{82816}{82844}Ne.
{82973}{83016}Nemoj mi lagati!
{83050}{83091}Pogledaj me...
{83208}{83274}Reci mi|da li imaš ljubavnicu?
{83379}{83401}Da!
{83551}{83592}Kakva je to reakcija?
{83617}{83718}Ako otvoreno prizna,|pokaži mu!
{83807}{83877}Nisam oèekivala da æe|tako lako priznati.
{83909}{83956}Nisam znala kako da reagiram!
{84007}{84038}Još jednom, u redu?
{84466}{84511}Reci mi iskreno...
{84541}{84584}Da li imaš ljubavnicu?
{84673}{84708}Ti si luda!
{84839}{84880}Tko ti je to rekao?
{84916}{84996}Nema veze,|imaš li ili nemaš?
{85126}{85154}Ne.
{85218}{85257}Nemoj mi lagati!
{85269}{85310}Reci mi!
{85338}{85367}Pogledaj me:
{85383}{85420}da li imaš ljubavnicu?
{85647}{85671}Da!
{86314}{86353}Jesi li dobro?
{86436}{86493}Nisam oèekivala da æe|ovoliko boljeti.
{86717}{86781}Ovo je samo proba.
{86857}{86914}Neæe stvarno tako lako priznati.
{86921}{87007}Sve je u redu,|nemoj plakati.
{87118}{87169}Èesto izlazite u posljednje vrijeme.
{87176}{87200}Da.
{87254}{87344}U redu je da uživate|dok ste mladi.
{87368}{87413}Ali nemojte pretjerivati.
{87487}{87535}Kada vam se vraæa muž?
{87546}{87585}Uskoro!
{87613}{87714}Ubuduæe, ne dajte mu|da toliko putuje.
{87736}{87814}Par bi trebao provoditi|više vremena zajedno.
{87837}{87878}Zar ne?
{87931}{87955}Laku noæ.
{88481}{88528}Hoæeš li doæi veèeras?
{88533}{88559}Zašto?
{88565}{88629}Urednik me proganja,|kaže da sam prespor.
{88634}{88693}Treba mi tvoja pomoæ,|kada možeš doæi?
{88718}{88767}Ne mogu neko vrijeme.
{88786}{88814}Zašto?
{88834}{88904}Gða Suen mi je održala predavanje.
{88913}{88944}Što je rekla?
{88952}{88991}Bolje da ne znaš.
{88999}{89067}Ne bismo se trebali|toliko viðati.
{89325}{89393}Gðo Chan, opet izlazite|po rezance?
{89398}{89490}Ne veèeras,|spremit æu sebi nešto.
{89514}{89650}Pridružite nam se,|jest æemo won-ton od povræa!
{89666}{89695}U redu.
{93333}{93386}- Bez ruèka danas, g. Ho?|- Bez.
{93420}{93475}Izvjesni g. Chow vas je tražio.
{93482}{93533}Kaže da ga nazovete.
{93602}{93624}Hvala.
{94417}{94468}- Stigla s posla?|- Da.
{94514}{94576}- Èudno vrijeme!|- Zar nije?
{94593}{94630}Dugo si ovdje?
{94636}{94675}Kratko.
{94725}{94774}Ne vjerujem da æe skoro stati.
{94821}{94845}Èekaj me.
{95536}{95575}Otpratit æu te kuæi.
{95586}{95666}Bolje da nas ne vide zajedno.
{95710}{95751}Onda ti idi prva.
{95802}{95845}Ako vide tvoj kišobran,
{95850}{95905}znat æe da sam bila s tobom.
{95963}{96002}Nisam razmišljao.
{96090}{96162}Idi ti prvi, ja æu malo prièekati.
{96214}{96255}Pravit æu ti društvo.
{96782}{96823}Da li si me pokušavao|nazvati?
{96874}{96931}Nisam bio siguran da li si|dobila poruku.
{96951}{97004}Da li bi mi mogla nabaviti|kartu za brod?
{97052}{97095}U kojem smjeru?
{97128}{97181}Ping mi je pisao iz Singapura.
{97189}{97273}Nedostaje im ljudi, hoæe|da doðem i pomognem.
{97373}{97416}Koliko æeš ostati?
{97422}{97488}Ne znam, vidjet æu.
{97605}{97652}Èemu žurba u Singapur?
{97700}{97739}Novo okruženje...
{97785}{97838}Dosta mi je govorkanja.
{97875}{97935}Zašto brinuti,|kada znamo da nije istina?
{98021}{98126}I ja sam tako mislio,|i nije me brinulo.
{98214}{98269}Mislio sam da neæemo biti kao oni.
{98367}{98406}Pogriješio sam.
{98476}{98525}Neæeš ostaviti muža.
{98591}{98632}Pa æu radije ja otiæi.
{98797}{98869}Nisam mislila da æeš se|zaljubiti u mene.
{98885}{98930}Ni ja.
{99048}{99116}Samo me zanimalo|kako je poèelo.
{99136}{99175}Sada znam.
{99215}{99276}Osjeæaji se ušuljaju|samo tako.
{99368}{99413}Mislio sam da imam kontrolu.
{99435}{99503}Ali mrzim samu pomisao|da ti se muž vrati.
{99518}{99555}Volio bih da se ne vrati!
{99599}{99634}Vrlo sam zao.
{99728}{99771}Hoæeš li mi uèiniti uslugu?
{99802}{99826}Što?
{99864}{99905}Hoæu biti spreman...
{101268}{101323}Bolje da se više ne viðamo.
{101430}{101473}Muž ti se vratio?
{101498}{101531}Da...
{101576}{101615}Jesam li jadna?
{101672}{101705}Nisi.
{101955}{101996}Neæemo se više vidjeti.
{102057}{102108}Pazi na muža bolje.
{103076}{103117}Molim te...
{103146}{103207}Ne shvaæaj ozbiljno,|ovo je samo proba.
{103234}{103266}Nemoj plakati!
{103375}{103414}Ovo nije stvarno...
{104618}{104678}Ne idem kuæi veèeras.
{105306}{105413}Mei-Yi posveæuje ovu pjesmu|prijateljima na medenom mjesecu.
{105417}{105533}Gða Cheung šalje|najljepše želje susjedima.
{105550}{105607}I g. Chan, na poslu|u Japanu,
{105613}{105749}želi svojoj ženi|sretan roðendan.
{105760}{105877}Zato uživajmo u pjesmi "Pun cvat",|u izvedbi Zhou Xuana.
{108297}{108326}Ja sam.
{108361}{108406}Ako ima karata viška...
{108433}{108467}Bi li pošla sa mnom?
{112029}{112064}Ja sam.
{112086}{112137}Ako ima karata viška...
{112142}{112191}Bi li pošao sa mnom?
{112468}{112527}SINGAPUR, 1963.
{112594}{112645}G. Chow je na poslu.
{112663}{112710}Imate li poruku?
{112738}{112783}Nema na èemu.
{113500}{113537}Da li je netko bio u mojoj sobi?
{113542}{113565}Ne.
{113576}{113635}- Nešto nedostaje.|- Što?
{114364}{114390}U stara vremena,
{114427}{114553}ako je netko imao tajnu|koju nije htio odati...
{114568}{114610}Znaš što bi uèinio?
{114632}{114675}Nemam pojma.
{114758}{114819}Popeo bi se na planinu,|našao drvo...
{114854}{114895}...izdubio rupu u njemu...
{114915}{114972}I šapnuo tajnu unutra.
{114989}{115042}Onda bi zaèepio rupu blatom.
{115081}{115182}I tajna bi ostala tamo zauvijek.
{115237}{115334}Kakva gnjavaža!|Ja bih samo pojebao nešto.
{115414}{115455}Nisu svi kao ti!
{115486}{115585}Ja sam obièan èovjek,|nemam tajne kao ti.
{115590}{115658}Ti sve držiš u sebi!
{115664}{115707}Reci mi bar nešto!
{115720}{115760}Nemam ja tajni.
{115801}{115850}Okani se, prijatelju!
{115884}{115917}Neæu nikome reæi.
{119468}{119506}Halo, Singapurski dnevnik.
{119525}{119554}Trenutak.
{119584}{119623}G. Chow, poziv za vas.
{119638}{119666}Hvala!
{119733}{119761}Halo?
{119900}{119924}Halo?
{121018}{121072}HONG KONG, 1966.
{121099}{121159}- Tko je?|- Ja sam.
{121187}{121247}- Gðo Chan, koliko je prošlo!|- Da.
{121266}{121311}- Amah, tko je to?|- Gðo Suen!
{121316}{121363}Otkud vi kod nas?
{121368}{121410}Da, sto godina je prošlo.
{121420}{121505}Bila sam u prolazu, pa sam vam|donijela kartu za brod.
{121516}{121540}I jedan mali poklon.
{121544}{121617}Niste trebali, lijepo je|samo vas vidjeti.
{121622}{121668}Ovdje je takav nered!
{121674}{121702}Veæ se pakirate?
{121707}{121857}Beznadno je, žao mi je|bilo što baciti!
{121903}{121942}Hajdemo vam naæi stolicu.
{122044}{122090}- Uzmite èaja!|- Hvala.
{122103}{122202}Ruèajte s nama, gðo Chan!|Idem na plac.
{122245}{122317}Ne mogu, èeka me posao.
{122339}{122380}Nemojte pobjeæi!
{122392}{122499}Gða Suen æe se naljutiti|ako ne budete jeli s nama.
{122518}{122566}Amah, nalij i meni èaj.
{122607}{122640}Kako vam je muž?
{122644}{122686}Dobro je, hvala.
{122698}{122733}Koliko æete biti odsutni?
{122739}{122778}Ne znam.
{122785}{122844}Ako mi se svidi,|možda i ostanem!
{122864}{122892}Zašto?
{122899}{123035}Moja kæer brine zbog|situacije u Hong Kongu.
{123042}{123104}Ne želim otiæi.
{123110}{123254}Otkad su Koovi otišli,|nemam s kim igrati mahjong.
{123273}{123401}A mojim kæerima u Americi|treba pomoæ oko djece.
{123486}{123525}Što æete s ovim stanom?
{123545}{123597}Nisam sigurna...
{123636}{123685}Ne želim ga prodati.
{123729}{123776}Mogla bih ga iznajmljivati.
{123802}{123844}Koliko biste tražili?
{123878}{123917}Zainteresirani ste?
{123924}{124029}Vama bih ga dala s popustom.
{124038}{124073}Razmislit æu.
{124079}{124114}Gðo Suen, vaš èaj!
{124151}{124206}Tko su vam susjedi sada?
{124217}{124367}Ne poznajem ih dobro.
{124379}{124523}Koovi su mi bili kao obitelj!
{124561}{124629}Bilo je baš lijepo tada, zar ne?
{124654}{124682}Je.
{124717}{124748}Hajdemo sjesti ovdje.
{125381}{125409}Da?
{125414}{125440}Da li je g. Koo kod kuæe?
{125451}{125508}Odselio se odavno.
{125537}{125569}Da li znate gdje?
{125594}{125634}Poznajete li ga dobro?
{125649}{125688}Nekad sam živio ovdje.
{125719}{125763}Da li je gða Suen i dalje|prvi susjed?
{125769}{125889}Otišla je! Velika je zbrka,|svi bježe.
{125914}{125955}Tko sada živi tamo?
{125968}{126063}Jedna žena sa sinom.
{126076}{126123}Deèko je sladak.
{126190}{126301}Nema adrese na Filipinima...|Samo telefon njegovog sina.
{126385}{126470}- Ne mogu ovo primiti!|- Molim vas, morate.
{126487}{126526}Hvala vam, onda.
{126798}{126837}To doba je prošlo.
{126843}{126907}Ništa što mu je pripadalo|više ne postoji.
{126932}{126962}Jesi li spreman?
{126968}{127017}- OK!|- Idemo!
{127315}{127393}CAMBODIA, 1966.
{127400}{127515}Diplomatski odbor èeka|na aerodromu...
{127524}{127627}Princa Norodom Sihanouka|i kraljicu Sisowath Kossamak
{127642}{127685}doèekuju generala|De Gaullea.
{127851}{127974}Ima deset kilometara|od Pochentonga do Phnom Penha.
{128000}{128061}200.000 ljudi okupilo se|oko puta.
{128067}{128121}Doèek nezapamæen|u povijesti kraljevstva.
{133291}{133365}Sjeæa se tih nestalih godina.
{133370}{133460}Kao da gleda kroz|prašnjavi prozor,
{133466}{133565}prošlost može vidjeti,|ali ne i dotaknuti.
{133570}{133677}I sve što vidi|mutno je i nerazgovjetno.
{133794}{133901}Kraj
{133972}{134019}Posebna zahvalnost:
{134029}{134091}G. Liu Yi-Chang
{134101}{134160}Producent, scenarij i režija:
{134168}{134230}Wong Kar-Wai
{134240}{134283}Izvršni producent:
{134292}{134349}Chan Ye-Cheng
{134359}{134402}Pomoænik producenta:
{134411}{134464}Jacky Pang Yee-Wah
{134473}{134516}Dizajn produkcije i montaža:
{134525}{134578}William Chang Suk-Ping
{134587}{134630}Direktor fotografije:
{134639}{134711}Christopher Doyle|Mark Lee Ping-Bing
{134721}{134764}Glazba:
{134835}{134868}Predradio:
{134877}{134928}Wong Chi-Ming
{134939}{134980}Specijalan nastup:
{134991}{135114}Siu Ping-Lam, Cheung Tung Joe|Rebecca Pan, Lai Chin,
{135123}{135224}Siu Ping-Lam, Cheung Tung Joe|Rebecca Pan, Lai Chin,
{135235}{135278}Glasovi:
{135287}{135349}Sun Jia-Jun, Roy Cheung
{135376}{135666}Subtitles by:|M O Z E N