{1}{1}25.000
{1086}{1170} JILL RIPS 
{3839}{3925}Prema romanu | Fredricka Lindsayja
{4005}{4103}Redatelj
{4624}{4655}Pokaži mi.
{4782}{4866}Sranje. - Je li to onaj | koji mislim da jest?
{4898}{4978}Ovo æe biti nezgodno. Drago | mi je što je sluèaj tvoj.
{7452}{7489}Matt?
{7626}{7668}Ne gledaj me tako.
{7699}{7771}Ionako se ovdje | osjeæam poput duha.
{7844}{7878}Izgledaš...
{7913}{7960}Pa, drukèije.
{8093}{8141}Žao mi je zbog tvog brata.
{8240}{8293}Ideš k majci?
{8412}{8481}Onda se vidimo poslije.
{9277}{9357}11. VELJAÈE 1977. g.
{9513}{9569}Daj se pomakni.
{9683}{9763}Ako se pitaš kako sam | te prepoznao, nisam.
{9767}{9914}Prepoznao sam taj smrdljivi | kaput. - A tek sam ga kupio.
{9969}{10064}Moraš se uklopiti. | Nabavi si poliester.
{10069}{10141}To je neuništivo. | Kužiš me? - Znam.
{10231}{10307}Tko je tip u odijelu?
{10328}{10437}Conway. - Graðevinac? | - Sada jedini u gradu.
{10441}{10505}Što god se veliko | gradilo, njegovo je.
{10576}{10638}Znam da ovo nekamo vodi.
{10654}{10822}Èini mi se da je moj brat | smetao planovima Velikog Jima.
{10852}{10962}Naš geolog Michael je rekao | da tunel ne bi smio biti tu.
{10966}{11077}Dok je Veliki Jim rekao...
{11178}{11263}"Uložio sam tri godine | života u taj projekt."
{11277}{11357}Koliko vrijedi tri | godine života tog tipa?
{11367}{11475}Koliko? 30 milijuna | dolara? - Više. Više.
{11483}{11617}Lako su mi svezali brata i | inscenirali seksualno umorstvo
{11622}{11835}samo treba saznati èije je | raèune pomrsio. - Ja? Zašto?
{11897}{11971}Ne, ne.
{12056}{12228}Tko je maèka s mojom mamom? | - Isuse, pa žena tvoga brata.
{12270}{12325}Njegova žena.
{12447}{12508}Zna li kako su ga našli?
{12535}{12610}Zna. Morao sam je ispitati.
{13535}{13572}Ja sam Irene.
{13779}{13891}Ti i Michael ste | živjeli ovdje s mamom?
{13991}{14101}Tražili smo joj smještaj, ali | ništa joj se nije svidjelo.
{14186}{14310}Ti živiš u Los Angelesu? | - Što ti je još rekao o meni?
{14323}{14389}Ne puno. Da si bio policajac.
{14484}{14588}Navodno si jednom okupio sve | prostitutke ovoga grada
{14592}{14693}i natjerao ih da bose | hodaju po kiši i pjevaju,
{14696}{14809}a zatim si napustio posao. | Nije razumio zašto.
{14827}{14879}Trebao je nazvati i pitati.
{14917}{14977}Telefon radi s obje strane.
{15033}{15125}Koliko ste bili u braku? | - Šest mjeseci.
{15255}{15300}Šest mjeseci.
{16546}{16747}Rez na vratu je èist. Nije ga | oèekivao, možda ni osjetio.
{16752}{16919}Zatim je 53 puta dobio u | genitalije. Prilièan nered.
{16924}{17046}Borio se. Kut uboda otkriva | da se radi o dešnjaku.
{17050}{17155}Neobièno je što su rane pliæe | nego što bismo oèekivali.
{17186}{17260}Muèen je. - Ne.
{17285}{17365}Bio je mrtav prije nego | što je dobio veæinu uboda.
{17369}{17480}To nas navodi da se | radi o fizièkom ogranièenju.
{17500}{17579}Ubojica nije pretjerano jak.
{17583}{17719}Nije imao snage ni da | nožem presijeèe hrskavicu.
{17726}{17869}Ispod užeta smo našli | vrlo malo rezova i modrica.
{17874}{18010}Kao da je dopustio | da ga se veže.
{18059}{18163}Po èvorovima je oèito | da u ovome nema micanja.
{18177}{18250}Je li u krvi bilo | sedativa? - Ne.
{18342}{18458}Jesi dobro? - Hvala vam, hvala.
{18512}{18635}Ljudi iz vlade su pomalo | poput bogova. Pomažu onima
{18640}{18763}koji pomognu sebi. | Nisam morao posebno moliti
{18769}{18868}niti se ulizivati da bih | pokrenuo ovaj projekt.
{18882}{18985}Samo sam objasnio zašto | nam je podzemna potrebna.
{18990}{19186}Zašto zaslužujemo najbolju | prometnu vezu u unutrašnjosti.
{19192}{19298}A možda sam se malo ulizivao.
{19340}{19451}No postojao je jedan èovjek. | Njega ništa nije pokolebalo.
{19454}{19577}Samo istina. Priznajem, | imali smo razlièite vizije.
{19581}{19729}Moja je bila ovaj tunel. | No poštovao sam ga.
{19739}{19845}Naš grad je izgubio velikog | èovjeka u Michaelu Sorensonu.
{19848}{19957}No sjetit æemo ga se kad | god proðemo ovim tunelom
{19961}{20003}koji nosi njegovo ime. Hvala.
{20170}{20250}Slijedite me i pokazat | æu vam iduæu fazu.
{20442}{20533}Juèer se nismo upoznali. | Ja sam Jim Conway.
{20538}{20660}Veliki Jim, zar ne? - Ovisi | koliko se dobro poznajemo.
{20668}{20721}Žao mi je zbog tvog brata.
{20733}{20835}Je li? - Nekad si bio | policajac ovdje, zar ne?
{20838}{20949}Michael je rekao da si ostavio | posao bez ijedne rijeèi.
{20952}{20998}Ostavku sam poslao poštom.
{21002}{21094}Mnogi su rekli da piješ. | Jesi li i sad pijan?
{21180}{21284}Sigurno ste primijetili | da je ovdje izuzetno hladno.
{21289}{21377}Radnici moraju izlaziti | svakih 45 minuta.
{21520}{21635}Sjeæa li se itko kojeg mog | govora koji je toliko trajao?
{21651}{21735}Hvala vam. Moji ljudi | æe vas izvesti.
{21995}{22047}Hladnokrvna si, ha?
{22078}{22135}Hladnoæa mi | nikad nije smetala.
{24034}{24183}Doðeš li opet ovamo, bivši | policajèe, ostat æeš ovdje.
{25850}{25947}Što æeš kad sve popakiraš? | - Kako to misliš?
{25960}{26156}Bili ste vjenèani tek šest | mjeseci. Vraæaš se svojima?
{26189}{26272}Koje ti je djevojaèko | prezime? - Reed.
{26277}{26362}Vraæaš se gðici | Irene Reed u New York?
{26365}{26418}Moja obitelj je odavde.
{26442}{26515}Šališ se. Svijet je mali.
{26591}{26675}Oèito mi je suðeno | da živim ovdje.
{26705}{26833}Roditelji su mi mrtvi. | U New Yorku nemam ništa.
{26902}{27026}Žao mi je. Nastradali su? - Ne.
{27044}{27206}Bili su stariji. Usvojena sam. | - Znaèi da ostaješ.
{27241}{27409}Smeta li ti? | - Dok je mama zbrinuta, ne.
{27579}{27703}Matt, baš sam govorio tvojoj | majci da mi je žao što smetam.
{27707}{27769}Jesi li joj rekao | da si policajac?
{27774}{27869}Zar se tako razgovara | sa starim prijateljem?
{27874}{28011}Sad je naèelnik. - Vi ste | sigurno Irene. Max Peerse.
{28020}{28090}Žao mi je zbog | Michaela. - Hvala.
{28135}{28306}Sjedni, hajde. - U redu je. | - Stavit æu još jedan tanjur.
{28498}{28585}Ne zna kako je Michael | pronaðen. - Shvaæam.
{28599}{28714}Ne znam kako æeš joj zatajiti | nešto takvo... - Slušaj me.
{28718}{28795}Ne, slušaj ti mene. Deèki | su vidjeli nekog nalik tebi
{28799}{28876}kako njuška po Conwayevom | tunelu na dan otvaranja.
{28880}{28965}Pitam se zašto su digli | toliku prašinu oko toga.
{28969}{29036}Više nisi murjak, Sorensone.
{29140}{29263}A samo mi pogoršavaš probleme | koje imam s tim tipom.
{29362}{29450}Baš sam govorio | Mattu o ubojstvu...
{29469}{29617}Bože, zar još jedno? | - Da, seksualni zloèin.
{29627}{29737}Takvo što još niste vidjeli. | - Nisam to vidjela u novinama.
{29741}{29889}Doista? - Samo prièaj. | - Što to mumljaš, Matte?
{29957}{30014}Pitao me kako seksualni...
{30117}{30160}Isuse, guši se!
{30338}{30426}Pojaviš li se ovdje bez naloga | kunem ti se da æu te ubiti.
{30430}{30563}Kujin sine. - Svim jedinicama. | 187 na brdima soli u luci.
{30567}{30665}Vozila Hitne koriste | sjeveroistoèni ulaz.
{30780}{30863}Kamo æeš? - Kamo i Peerse.
{30971}{31007}Dobar udarac.
{31398}{31501}Što imamo? - Još jedna | plutaèa. Što da ti kažem?
{31505}{31556}Prièaj, doði ovamo.
{31627}{31721}Eddie. - Pustite ga!
{31839}{31931}Isuse. Tog Conwaya | ima svugdje.
{31935}{32016}Jesi mu vidio glavu? | - Koju glavu? - Zgodno.
{32031}{32132}Možda nikada ne saznamo | tko je. Nije li to zgodno?
{32138}{32277}Glava nije ubojièino djelo. | To se dogodilo poslije.
{32281}{32402}Pregazio ga je tip s kombijem. | Vozio je mrtav umoran.
{32406}{32483}Nije stao dok nije osjetio | udarac, vratio se natrag
{32487}{32625}i opet ga pregazio. | - Ne vjerujem. - Što to?
{32661}{32712}Identificiraj ga.
{32778}{32902}Ideš na piæe? | - Ne, ali volio bih.
{32907}{32980}Idemo na piæe. - Dobro.
{33087}{33179}Vidio sam nekog tipa | s Conwayom u tunelu.
{33183}{33231}Crna kosa u stilu Elvisa. | Èini mi se poljski akcent.
{33289}{33360}Izgleda kao poljski Elvis.
{33418}{33582}Prije umorstva, Peerse me | natjerao da motrim Conwaya.
{33598}{33738}Taj seronja je kapetan? | - Život je kuèka.
{33778}{33934}Dok smo ga motrili, što se | pokazalo gubljenjem vremena,
{33938}{34033}èesto smo viðali tvog brata. | Prije dva tjedna Conway je
{34037}{34206}priredio zabavu. Bratova žena | odlazi rano, sama i uzrujana.
{34220}{34366}Sat vremena kasnije izlazi | Michael s nekom kurvom.
{34433}{34585}Jebiga! - Idiote, što radiš?! | - E sad si mi zakuhao.
{34600}{34735}Zaboravio si kako sam te | pokrivao? Hoæu ime tog Elvisa!
{34759}{34804}Isuse...
{34916}{35032}Eddie, ako nešto | slomiš... - Slušaj to.
{35044}{35187}Da nije moje kæeri, veæ bih... | - Eddie, radi se o mom bratu.
{35200}{35368}Jebiga! Prièaš | o Joeu Kujaviju.
{35630}{35681}Znaš gdje ga mogu naæi?
{35725}{35939}Svodnik je žena u koži. | - Žena u koži? - Sadomazo.
{35962}{36089}To je sve što znam. | - Ta nakaza èuva Conwaya?
{36106}{36196}A ti ne vidiš kakve Conway ima | veze s ubojstvom moga brata?
{36200}{36258}Što još znaš o njemu?
{36266}{36407}Ima tome veæ 20 godina. Èuo | sam da je zatukao neku curu.
{36413}{36524}Annette Verr | ili Vernon. Ne znam.
{36580}{36759}Priveli su ga, ali imao | je alibi. Mustru Mary O.
{36765}{36867}Jedna od njegovih cura. | - Gdje mogu naæi Mary O?
{36873}{36966}Dolazi u onu rupu | na Treæoj, "Emma Peels".
{37813}{37943}Kad Mary dolazi? | - Èovjek s oružjem, ha?
{37948}{38020}Udariš li Mary O, | ona æe ti vratiti.
{38029}{38124}Ja to ne radim, | dušo. Bez uvrede.
{38229}{38352}U redu je. Znaš li | gdje je mogu naæi?
{38371}{38495}Nisi Maryna redovna mušterija.
{38537}{38824}Dobro, obradila si me. | Dvadesetka. Povest æu te.
{38858}{38937}Raèun. - Otkud znaš Mary O?
{38964}{39081}Preko Kujavija. | - Otkud znaš Joea?
{39094}{39147}Conway me povezao.
{39280}{39382}Proèulo se da se | raspituješ o krivom èovjeku.
{39395}{39519}Nauèit æemo te | nekoliko pravila. Jasno?
{40153}{40258}Reci Velikom Jimu da se | i dalje raspitujem o njemu.
{40261}{40310}Nema frke. Uèinjeno.
{40553}{40678}Možeš me obraditi, ali | neæu ti reæi ništa o Joeu.
{40684}{40738}Gdje živi Mary O?
{40750}{40795}Kunem ti se...
{40824}{40914}Na uglu Pete | i Sprucea. Na katu.
{41006}{41049}Vratit æu se ako lažeš.
{41095}{41176}Na uglu Pete i Elma.
{41408}{41513}Nemoj prestati, nemoj!
{41569}{41668}Molim te, nemoj!
{41817}{41954}Stani, molim te. Nemoj!
{42585}{42683}Odloži to. - Tko si | sad ti?! - Odloži ga.
{42688}{42782}Rekla si da je ovdje sigurno. | - Jest. Gadno si pogriješio!
{42785}{42834}Nisi nièiji junak!
{42990}{43073}Odveži ga i izbaci | odavde. - Što hoæeš?
{43076}{43162}Nijedan murjak ne bi ovamo | došao sam. - Imaš mozga.
{43167}{43251}Znaèi li ti što | ime Annette Vernon?
{43354}{43437}Glup si što si došao ovamo bez | obzira koliko ti je platila.
{43442}{43542}Mrtva je. - Znam da je | èvrstoguza Annie mrtva.
{43546}{43680}Govorim o platinastoj kuji | koja postavlja ista pitanja.
{43715}{43829}Platinasta kosa. Mršavica, | kao moje jedno bedro.
{43924}{43978}Oèito si joj previše rekla.
{44039}{44167}Otvorila si limenku crva. | - Ništa joj nisam rekla.
{44172}{44237}Znam mi ime zato što ga | je proèitala u novinama
{44241}{44315}jer sam èuvala djecu one | kuje dok ih nisu usvojili.
{44319}{44405}Nisi voljela Annette, | ali si joj èuvala djecu?
{44469}{44545}Nisu ona kriva | zbog svoje majke.
{44716}{44841}Rekla je da sam ološ. | Ali ja sam još ovdje.
{44845}{44976}Dok je èvrstoguza | Annie završila na smeæu.
{44986}{45148}To je sve što platinasta zna. | - Otkud joj Kujavijino ime?
{45151}{45259}Izvukla ga je iz guzice. | Platinasta ne zna ništa.
{45334}{45450}Ali ja znam. I imam sve što | trebam da ga udesim zauvijek.
{45519}{45617}Moram piškiti ako æemo | nastaviti. Mogu li?
{45632}{45738}Samo upamti da držim pištolj.
{45783}{45837}O, dušo, dušo.
{46475}{46533}Pozovi psa! Ubit æu ga!
{46537}{46640}Zbilja æu ga ubiti. | - Daj, ionako ga mrzim.
{46791}{46832}Sranje.
{47115}{47263}Reci Joeu da ga tražim. Naðe | li me prvi i to je u redu.
{47698}{47787}ŽENSKI UBOJICA ODGOVORAN | ZA ZADNJE UBOJSTVO U BOSTONU
{48141}{48186}Èula sam da plaèe.
{48190}{48277}Otišla sam je pogledati i | vidjela da je èitala novine.
{48369}{48447}Je li dobro? - Upravo | se vratila u krevet.
{49298}{49473}Što radiš u njegovoj sobi? | Što tu radiš? Izlazi.
{49477}{49647}Gubi se van iz sobe. | Van! Van iz sobe.
{50592}{50648}G. Conway!
{50921}{50979}Priznaj da si naruèio | ubojstvo moga brata.
{50983}{51097}Potezi oèajnika, | g. Sorensone. Otmica. Napad.
{51210}{51318}Priznaj da si ga naruèio. | - Jesi li sišao s uma?
{51398}{51535}Zaustavi auto! Èuješ me? | Smjesta! Èuješ, Sorensone?
{51623}{51747}Sranje. Kažem ti, dovraga! | - Priznaj da si ga ubio.
{52036}{52130}Zaustavi vražji auto! | - Priznaj ubojstvo.
{52488}{52630}Sorensone, dovraga! | Zaustavi. Zaboga, stani.
{52633}{52707}Stani, znam istinu. | Znam istinu.
{52761}{52796}Isuse Kriste.
{52929}{52988}Vozi me u moj ured.
{53151}{53222}Bavim se usreæivanjem ljudi.
{53225}{53272}Dajem im što žele.
{53306}{53426}No moram se osigurati | da æe održati obeæanje.
{53463}{53507}Michael Sorenson.
{53629}{53735}Razradio sam sustav | koji ih održava poštenima.
{53754}{53817}Drže svoju rijeè.
{53861}{53982}Matte, upoznaj svog | starijeg brata Michaela.
{54176}{54299}To je brat kojeg si poznavao. | Imam još pet nastavaka.
{54303}{54398}Naruèio sam kopiju da bi | glasovao u moju korist,
{54402}{54453}a zatim su ga | našli u zaljevu.
{54458}{54556}Nisam ga morao ubiti | da ga pridobijem. Imam ovo.
{55225}{55276}A imao je ženu.
{55306}{55435}Eto vam, g. Sorensone. | Nitko tu ništa ne krije.
{55440}{55542}Michael je samo dopustio | krivoj kuji da ga sveže.
{55561}{55627}Umro je u potrazi | za boljim orgazmom.
{55881}{55928}Želim ime te djevojke.
{56756}{56963}Kažu mi da me tražiš, bivši | murjaèe. Kako ti mogu pomoæi?
{56981}{57090}Zanimalo me gdje mogu | nabaviti takvu vlasulju.
{60202}{60311}Gdje sam? - Netko je nazvao | i rekao da si ovdje.
{60316}{60402}Rekao je i da napustiš grad | ili te drugi put neæu naæi.
{62203}{62246}Da ti operem leða?
{62375}{62437}Zašto mi nisi rekla da se | Michael bavio perverzijama?
{62440}{62487}Nisam htjela | riskirati da se proèuje.
{62493}{62538}Pa si dopustila | da naganjam Conwaya!
{62542}{62606}Nadala sam se da ima | nekakve veze s tim!
{62611}{62704}Da koristi Michaelovu | slabost da bi prikrio istinu.
{62719}{62747}Nije.
{62929}{62965}Mogla si mi reæi.
{63299}{63346}Ne poznajem te.
{64065}{64231}Saznala si za to prije ili | poslije vjenèanja? - Poslije.
{64275}{64421}Polako me navodio. | - Kako bi drukèije?
{64447}{64532}Ne možeš odmah prijeæi | s poljupca na šamare.
{64620}{64708}Prièaš o tome kao da | je to nešto perverzno.
{64776}{64840}Seks nije ništa prljavo.
{64850}{64951}Predugo si špijunirao | ljude po jeftinim hotelima.
{64978}{65085}Neæeš me uvjeriti da | seks i bol idu zajedno.
{65121}{65311}Za veæinu se ne radi o boli. | U biti ni nema toliko boli.
{65316}{65456}Sve je to gluma. Igranje | uloga na dubljoj razini.
{65515}{65716}Ljudi poput Michaela koji | danju nadziru sve oko sebe
{65719}{65812}trebaju potpuno opuštanje.
{65831}{65901}Da netko drugi | odluèuje za njih.
{65943}{66059}Što je to znaèilo tebi? - Meni?
{66162}{66255}Bilo je više fizièki.
{66328}{66452}Nije me privlaèilo. | Èinila sam to za njega.
{66466}{66677}Našli smo nešto fizièko | u tome. Ne volim ni bol,
{66747}{66980}ali ako mi je zadaje u | pravilnim dozama dok me ševi
{67058}{67281}i to osoba koja zna da | to ne èini dok svršavam...
{67433}{67655}S nekim tko zna kako treba, | svatko bi se mogao navuæi.
{67739}{67913}Ali takvu osobu je teško | naæi. Tvoj brat je znao.
{68128}{68183}Trebao se držati tebe.
{68580}{68690}Upoznaj Annette Vernon. | Ubijena je. Prije 20 godina.
{68727}{68826}Spominje se još samo Mary | O"Bannion koja je udomila
{68830}{69002}Annettine dvije kæeri Ursulu i | Frances dok im nisu našli dom.
{69041}{69158}Nedavno je netko s platinastom | kosom posjetio Mary.
{69174}{69331}Što misliš tko bi se | raspitivao o Annette?
{69376}{69525}Jedna od kæeri? - Tko bi drugi, | s obzirom da je bila kurva.
{69583}{69670}Èini mi se da nikog nije bilo | briga ni kad je bila ubijena.
{69711}{69978}Ili Ursula ili Frances dolaze | se raspitati o Joeu Kujaviju.
{70002}{70133}Tko je on? - Majèin svodnik. | Kæerin je motiv oèito osveta.
{70219}{70423}Ošteæena roba. Zatim sam vidio | djevojku na filmu s Michaelom.
{70435}{70530}Domina, platinaste kose.
{70627}{70671}Pada li ti išta na um?
{70973}{71033}Znaèi da æeš | nastaviti tražiti.
{71131}{71174}Èini se da da.
{71191}{71252}O èemu se zapravo radilo?
{71296}{71455}Ona parada prostitutki | na kiši? Je li to istina?
{71547}{71641}Tad sam bio malo zbunjen.
{71656}{71836}Nisam shvaæao zašto bi | itko odabrao naèina života
{71901}{71983}kakav su odabrali neki od | ljudi na koje sam nailazio.
{72004}{72171}Umjesto da ih uhitim, | htio sam ih usmjeriti.
{72280}{72543}Kad su krenule, na trenutak se | èinilo da ih je kiša oprala.
{72628}{72807}Kao da vidim tko su | doista, a ne ono što su.
{73008}{73046}Ne znam.
{74119}{74209}Nisi mi oznaèio | što više želiš, Jack.
{74335}{74468}Otvoren sam, Serena. | - Ne voliš se igrati na rubu?
{74514}{74548}Ne.
{74568}{74699}Proðimo neke stavke. | Discipliniranje? - Svakako.
{74740}{74880}Preodijevanje? - Ne. | - Djeèje igre? - Ne.
{74909}{75070}Vezanje? - Ne, da. Da. | - Klistir? - Ne.
{75084}{75181}Analni seks? - Ne. | - Škakljanje? - Možda.
{75187}{75315}WC obuka? - Moram | razmisliti. - Ponižavanje?
{75349}{75466}Za ovaj tjedan mi je bilo | dosta. - Ponižavanje? - Ne.
{75503}{75565}Dodijelit æu te Randi.
{75647}{75781}Kompa mi kaže da je Frances | najbolja. - Nemamo takvu.
{75791}{75880}A da imamo, morala | bi promijeniti ime.
{75885}{75995}Sigurno? Kratka, platinasta | kosa. - Platinasta?
{76013}{76164}Trebao si reæi. Imamo samo | jednu kojoj to dobro stoji.
{76374}{76412}Katie?
{76739}{76768}Sjedni.
{76839}{76901}Ne, tamo.
{77670}{77711}Što bi htio?
{77821}{77905}Skini odjeæu.
{78746}{78784}Što sad?
{78885}{78994}Nisam kurva! | Profesionalka sam.
{79040}{79168}Mogu te dovesti u stanje | gdje æeš se na najmanji ubod
{79217}{79450}razletjeti. A ti | tražiš ples na stolu?
{79607}{79702}Tražim nekoga. - Kao i svi.
{79727}{79827}Kao i svi. - Jesi li | se ikad zvala Frances?
{79940}{80002}Jesi li poznavala | Michaela Sorensona?
{80093}{80160}Razgovaram s tobom. Vrati se!
{80295}{80296}Vrijeme je isteklo. | - Sranje! Platio sam jedan sat.
{80505}{80576}Hoæeš na teži naèin?
{80813}{80870}Udaraš kao profiæ, ha?
{81045}{81113}Vražji Matt Sorenson.
{81133}{81223}Dave Daniels. - Daniels?
{81228}{81326}Bivši boksaèki prvak? | Nisam te prepoznao.
{81372}{81512}Veæ dugo ne boksam. | Èuo sam ti za brata.
{81618}{81736}Što radiš ovdje? | - Ne gledaj me tako.
{81740}{81817}Ne bavim se perverzijama, | samo osiguravam.
{81843}{81957}Tražim jednu curu. Ursula | ili Frances. - Èuo sam.
{81979}{82110}Znam jednu platinastu Frances, | ali ona radi samostalno.
{82113}{82222}A ovi ovdje te nikad neæe | uputiti nekoj samostalnoj.
{84505}{84591}Kako si, Mary? - Opet ti! | Razbio si mi vrata!
{84595}{84639}Što sam mogao | kad ih zakljuèavaš.
{84680}{84732}Uništit æeš mi posao.
{84757}{84893}A ti meni veèeru. Idemo. - Što? | - Plavuša koja je bila tu?
{84898}{84990}Reæi æeš mi je li to ona | koja mislim da jest. Kreni!
{86582}{86640}Je li ona? - Ne znam.
{86656}{86760}Sranje. - Mogla bi | biti. Nisam sigurna.
{86912}{86999}Èekaj ovdje. - Ne, što sad?
{88312}{88448}Što? Vozi me doma. - Izlazi.
{88498}{88559}Kvragu, nadam se | da je pas bio bijesan.
{88563}{88610}Tebe æu prvu ugristi.
{88659}{88701}A možda i neæu.
{88812}{88889}Policajèe Bob. | Još smo na prometnom?
{89000}{89081}Ako nisam uhiæen, možete | me zadržati samo 12 sati.
{89089}{89162}Ovdje sam veæ 10 h. | - Umoran sam.
{89192}{89294}Dosta mi je tvog glumatanja | vozaèa za Jima Conwaya.
{89348}{89428}Netko je ostavio | film ubojice.
{89494}{89551}Molio sam Conwaya da te tuži.
{89554}{89678}Sljedeæi put æeš, s tužbom ili | bez, ostati duže od 12 sati.
{89811}{89964}Moram vidjeti taj film. | - Naravno, samo doði k meni
{89969}{90039}da ti dam napitak koji | æe te uèiniti nevidljivim.
{90043}{90125}Ne vidi joj se lice. | - Vidi li se žrtvino lice?
{90128}{90215}Neki tip je došao u stan | prostitutke koju pratim.
{90220}{90280}Ako je taj tip ubijen...
{92669}{92749}Mislim da znam kako | se Frances prezivala.
{92873}{92967}Reed je bilo prezime | njezinih usvojitelja.
{93059}{93206}Njihova majka, jeftina kurva, | nasmrt je pretuèena
{93210}{93323}i izbaèena s ostalim smeæem. | - S ostalim smeæem?
{93335}{93382}Smeta li ti to?
{93574}{93655}Je li Frances bila prisutna | kad vam je majka ubijena?
{93672}{93787}Kad nam je majka ubijena? | - Frances ti je sestra.
{93866}{93923}Tebe su nekad zvali Ursula.
{94446}{94539}Poèela sam od nule. | Manje od nule.
{94603}{94716}Reedovi su nam nisu ponudili | ništa doli rada na farmi.
{94749}{94917}Walter, naš takozvani otac, | poèeo je ševiti Frances,
{94954}{95046}a kad se zagledao | u mene, otišla sam.
{95076}{95191}Pokušala sam nagovoriti | Frances, ali bojala se.
{95231}{95373}Kad sam stigla u New York, | našla sam posao tajnice
{95429}{95494}i zaboravila sam na Reedove.
{95582}{95675}Pet godina kasnije u mom se | uredu pojavila Frances.
{95695}{95794}Pokušala sam joj pomoæi, ali u | gradu je veæ bila godinu dana
{95798}{95915}i zaraðivala je u krevetu | za 1 h više nego ja na tjedan.
{96029}{96114}Tek se poèela baviti | perverznijim stvarima.
{96119}{96208}Nakon toga sam se | udala za Michaela
{96211}{96319}i on me doveo | natrag ovamo. Kuæi.
{96347}{96438}Tu se pojavila i ona. | - Da, pratila me.
{96498}{96582}Njezin je deèko saznao | za njezinu prošlost
{96586}{96680}i tražio je da usluži | njegove prijatelje.
{96713}{96782}Tako je ona to opisala.
{96799}{96924}Rekao je ako im seks | u vezi izgubi važnost,
{96928}{96994}njezina prošlost | neæe mu ništa znaèiti.
{97013}{97115}Kako su se ona | i Michael našli?
{97144}{97237}Dosadilo mi je raditi | sve ono za Michaela.
{97314}{97360}Pa si ih upoznala.
{97411}{97575}Bio je tako dobar prema meni. | Nisam ga htjela izgubiti.
{97826}{97971}Tip iz filma. Njega si | vidio da ide kod one kurve?
{98034}{98123}Sranje, nisam siguran. Sjeæam | se da je imao sivo odijelo
{98127}{98241}i crvenu kravatu. - Ma da? Daj | potraži mu kravatu u džepu.
{98252}{98322}Isuse, pa gledaj. - Ne znam.
{98360}{98447}Ne mogu dobiti nalog | ako nisi siguran.
{98543}{98590}Onda ga neæemo tražiti.
{98635}{98736}Ti æeš biti vani. | Mene æe pozvati unutra.
{99216}{99301}Znaš rijeè kojom | zoveš pomoæ? - Èizme.
{99363}{99495}Imamo posla. Gubi se. | - U redu je. Èizme.
{99499}{99656}Da, u reèenici. Sviðaju mi se | tvoje èizme. Maca u èizmama.
{99661}{99715}I slièno, znaš.
{99746}{99802}Znam da to nisi dugo radio.
{99957}{100036}Majko sveta!
{100129}{100169}To je ona?
{100224}{100295}Mijenjajmo se. | Ti ostani u autu uz radio.
{100299}{100356}Neka mene veže i ubije.
{102092}{102140}Jesi spreman za vezanje?
{102174}{102260}Hajde, radi, sranje jedno.
{103430}{103473}Odaj poèast.
{103548}{103585}Odaj poèast.
{103797}{103879}Podaj se. Pratiš me, Jack?
{104333}{104361}Sranje.
{104954}{104993}Reci mi da me voliš.
{105069}{105128}Volim te. - Volim te i?!
{105174}{105213}Volim te, gospodarice.
{105447}{105483}Što radiš?
{105518}{105590}Želim vidjeti. - Šuti, svinjo.
{105623}{105655}Prestani.
{106077}{106119}Hajde, Matte.
{106131}{106262}Gospodarice, plaæam najljepšoj | djevojci, želim je vidjeti.
{106268}{106343}U protivnom bih platio nekoj | debeloj kurvi da me mlati.
{106346}{106381}Šuti!
{106390}{106510}Hajde, reci rijeè. | - Zaèepi!
{106606}{106685}Èizme, èizme. "Bemti, hajde.
{107007}{107154}Kamo si krenuo? - Znaš Jima | Conwaya? To je njegova zgrada.
{107159}{107282}Provjeravam je li sve | u redu. - Guido, gledaj.
{107290}{107432}Možda si policajac, ali | tip koji je ušao, nije.
{107438}{107576}Nemam vremena za ovo. | Daj mi kljuèeve i gubi se.
{107582}{107710}Pljaèkaš me? | - Tako je. A sad se gubi.
{107714}{107838}Prokleta kujo, ne šalim se! | Ne šalim se, odveži me!
{107842}{107948}Zaèepi! Dosta mi je | tvoje gubice. - Jebemti!
{108215}{108268}Mrtav si!
{108316}{108350}"Bemti.
{108439}{108477}Èizme!
{108637}{108677}Èizme!
{109538}{109589}U redu je, kompa.
{109598}{109695}Tako, u redu je. | Ja sam, Eddie. Smiri se.
{109698}{109763}Okreni se. Daj | da ti to skinem.
{109775}{109833}U redu je. Tu sam.
{109880}{109980}Što se dogodilo? - Što? | Koji se tebi vrag dogodio?
{110002}{110101}Mahala je nožem, prijatelju. | - Ti bi bio broj èetiri.
{110110}{110150}Gdje je nož?
{110243}{110292}Isuse, Eddie.
{110371}{110534}Ne, htjela te je ubiti. | - Prevarila me je. Gdje je nož?
{110566}{110641}Ona je ubojica, znaš to.
{110697}{110744}"Bemti sve!
{110933}{111066}Vidi ovo, jebeni | èudaci. Kvragu.
{111096}{111160}Ma jebiga! - Što radiš?
{111556}{111594}Evo ga.
{111652}{111691}Sereš.
{111714}{111908}Serem? Stojim tu kraj mrtve | kurve zbog tebe, g. Sereš.
{112094}{112131}Koji vrag?
{112431}{112510}Vidiš? Rekao sam ti | da je ona ubojica.
{112567}{112677}Tako mi svega. - Što radiš?
{112721}{112813}Nije snimao kad | je podigla nož.
{113945}{113986}Je li mrtva?
{114290}{114425}Žao mi je. - Nije to | bila Frances koju pamtim.
{114492}{114544}Brinula sam se za tebe.
{115599}{115653}Vezanje.
{115754}{115827}Ne igraš na rubu, zar ne?
{116306}{116397}Ponižavanje. Discipliniranje?
{116438}{116552}Ponižavanje. Škakljanje. | - Nisam kurva.
{116664}{116711}Djeèje igre.
{116935}{116978}Pokori se.
{117001}{117045}Svršavanje.
{117756}{117865}Da. - Ja sam Margaret Reed. | - Poznajemo li se?
{117869}{117958}Ne. Ja sam majka | Frances i Irene.
{117976}{118016}Opusti se.
{118138}{118219}Šteta što nije sredila | one koji su doista važni.
{118274}{118332}Onog koji vam je ubio majku?
{118410}{118547}Možda jest. Nitko ne zna | toèno tko je on bio.
{118725}{118765}Što radiš?
{118810}{118919}Nauèit æeš se opustiti.
{118948}{119006}Ne želim da me tuèeš, Irene.
{119012}{119090}Ako me ovaj tjedan udari još | netko, ne znam što æe biti.
{119093}{119165}Miješaš vezivanje | s discipliniranjem.
{119209}{119282}Misliš da je doista znala | tko vam je ubio majku?
{119445}{119489}Ne znam.
{119518}{119727}Ubijala je spontano. Sve koji | su je svojom perverznošæu
{119730}{119848}podsjeæali na maminog ubojicu. | To je bila njezina moæ.
{119854}{119945}Mogla ih je ubijati | zbog njihovih perverzija.
{120059}{120158}Vjerojatno je mislila | da je ubojica Kujavijan.
{120162}{120248}A on nije osoba koja | bi dopustila da ga svežu.
{120341}{120402}Želiš razgovarati o tome?
{120480}{120573}Kamo si otišla? - Želim.
{120686}{120794}Voljela bih da je našla | neku drugu slabost.
{120799}{120883}Ili snagu koju posjeduje.
{120917}{121022}No kao žena vjerojatno nije | razmišljala o svojoj snazi.
{121093}{121151}Možeš li me odvezati?
{121248}{121295}Trebali bismo se vratiti.
{121543}{121575}Što radiš?
{121668}{121716}Utrkivat æemo se.
{122341}{122414}Je li se Irene vratila? - Nije.
{122470}{122588}Èudno. - Možda i nije. | Gða Reed je bila ovdje.
{122593}{122690}Irenina majka. - Majka?
{123011}{123128}Uzela je kofer i rekla | da mora obaviti neke stvari.
{123154}{123206}Zatim se oprostila.
{123660}{123695}Jebiga!
{124523}{124621}Što radiš ovdje? - Je li to | djevojka koja te ispitivala?
{124626}{124748}Rekla sam... - Gledaj. Zamisli | je s vlasuljom ili prerušenu.
{124790}{124862}To je ona! To je ona!
{124915}{125033}Zvuèat æe ti èudno, ali idem | spasiti tvog kompu Joea.
{125062}{125166}Ozbiljno. Gdje je? | - Ne znam. Nisam toliko glupa.
{125169}{125284}Ne, sklona si samoubojstvu. | - Daj, napalit æu se.
{125289}{125377}Glupa kujo, | gdje je? - Ne znam.
{125392}{125513}Dobio je nekakvu omotnicu. | Došao je, proèitao je
{125517}{125608}i smjesta otišao. | - Gdje je omotnica?
{125612}{125674}Otkud bih ja to znala?
{126063}{126102}Koga vraga radiš?
{126872}{126926}Hladnoæa mi | nikad nije smetala.
{127101}{127146}Irene!
{129815}{129903}Idemo, Irene. | - Hoæeš li pucati, Matte?
{129930}{130024}Ubojica si. - Ja sam ubojica.
{130069}{130131}Što je s ljudima | koji su ubili mene?
{130155}{130252}Vodi me nakon... | - Ne znaš je li Kujavija.
{130256}{130338}Nije važno! | On prodaje žene.
{130342}{130462}Loš je kao i oni koji ih | kupuju. Svi oni koji su mrtvi.
{130466}{130595}Oni koji bi ukrali dušu | èovjeku koji je na dnu.
{130599}{130731}Mogao bi biti bilo koji od | ubijenih. - To nije dovoljno.
{130769}{130892}Nemaš pravo... - Ne. | Nemam nikakva prava.
{130920}{131025}Kao i kad mi je majka ubijena, | a nitko nije tražio ubojicu
{131029}{131122}jer je bila kurva. Kao | i kada je moj novi otac
{131126}{131228}odluèio da mu mogu | biti kæi i ljubavnica.
{131240}{131353}Kao i kad je tvoj brat odluèio | da nisam dobra za njega
{131355}{131437}ako se ne podam | njegovim prijateljima.
{131441}{131564}Nema kraja | pravima koja nemam.
{131664}{131713}Privodim te.
{131784}{131883}Zašto dolaziš ovamo? - Ne.
{131953}{132004}Umri, kurvo!
{132201}{132280}Držim te, držim te.
{132358}{132416}Ošteæena roba, ha?
{133032}{133097}Imaš kakvu ideju što | se ovdje dogodilo?
{133209}{133286}Ovako su nekako | našli Romea i Juliju.
{133304}{133385}Eto ti ga, crno na bijelo.
{134680}{134726}Jesi li dobro?
{134862}{134907}Dobro sam.
{134969}{135010}Jesi li je našao?
{135097}{135187}Ne, mislio sam da je ovdje.
{135188}{135388}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan  
