{1}{1}25.000
{486}{631}K U N D U N
{907}{992}Sinovi Džingis-Kana|nadjenuli su Dalaj-Lami ime.
{1005}{1071}Ono znaèi; "Ocean Mudrosti."
{1081}{1138}Tibetanci se u ratom|rastrganoj Aziji
{1149}{1205}veæ cijelo tisuæljeæe|zalažu za mir.
{1211}{1269}Vladar im je Dalaj-Lama,
{1280}{1336}utjelovljenje|samilosnog Buddhe.
{1343}{1413}Godine 1933. preminuo je|Trinaesti Dalaj-Lama.
{1424}{1486}Èetiri god. Kasnije, sveæenik|je tražio 14. Dalaj-Lamu
{1499}{1565}u zabaèenome|dijelu Tibeta.
{1579}{1647}Potraga se bližila kraju.
{1659}{1725}Buddha se iznova rodio.
{2990}{3390}{C:$0000FF}{y:ib} B & M |{C:$FF0000}{y:b} movies 
{3466}{3538}Prièaj mi.|- Opet? - Prièaj mi.
{3545}{3642}Otac ti je bio teško bolestan.|Mislili smo da æe umrijeti.
{3658}{3768}Uginule su nam neke|životinje. - Krava? - Da, krava.
{3793}{3884}I konj, jak i piliæi.
{3910}{3975}Zaredale su se|èetiri neplodne godine.
{4059}{4189}Jedne sam noæi osjetila da|æeš doæi. Rodio si se u zoru.
{4224}{4342}Prièaj mi. - Nisi plakao.|- Nisam. - Ne, nisi plakao.
{4390}{4458}Toga je dana|tvoj otac ozdravio.
{4484}{4564}Nazvao te Lhamo,|Zaštitnik. - Znam.
{4590}{4657}Spavaj sad, Lhamo.
{7189}{7267}Ja. - Ne. - Ja.|- Ne, ovo mora prestati.
{7304}{7403}Ja, ovdje. - Ne, ja sam otac,|a ti dijete. Sjedni ondje.
{7444}{7538}Ne. - Ja sjediti ovdje. - Ne.
{7608}{7674}Što je u tome loše?|Neka sjedi gdje hoæe.
{7702}{7784}Razmazit æeš ga.|Samo ga ti poslužuješ
{7797}{7857}i diraš njegovu hranu.|Sve je preèisto.
{7917}{7980}Što je loše u tome?|- Misli da je kralj.
{8091}{8188}Isprièajte moju prièu.|- Ne opet. - Opet. Ja.
{8250}{8307}U redu, Lhamo,|ja æu ti je isprièati.
{8314}{8389}Rodio si se u zoru.|Vani je bilo veoma tiho.
{8399}{8469}Pomogla sam mami.|Pozvala me.
{8479}{8540}Nisi plakao kad si se rodio.|Nikada nisi plakao.
{8551}{8655}Dali smo ti slatki napitak.|- Kakao si posvuda!
{8760}{8817}Prestanite!
{8850}{8928}Odjahat æu s tobom do|samostana. - Hvala, oèe.
{8940}{9032}Sjetila sam se.|I vrane su tada letjele.
{9039}{9110}Kada? - Onoga dana kada se|rodio Lhamo. Sjeæaš se?
{9143}{9181}Bio si bolestan.
{9190}{9248}Donijela sam ti ga i rekao si|da æe se zvati Lhamo.
{9255}{9325}Pomolio si se. Zaspala sam,|a kasnije sam izašla
{9332}{9388}i vidjela ih.
{9398}{9475}Par vrana se došao|gnijezditi na naš krov.
{9480}{9579}Došle su zbog Lhame.|- Baš kao i zbog Dalaj-Lame.
{9933}{9989}Moraš prestati, Lhamo!
{12001}{12057}Da!
{12185}{12273}Putujemo u Lhasu.|- Uðite. Veoma je hladno.
{12683}{12741}Vaše sluge se mogu|poslužiti kuhinjom.
{13828}{13892}Ovo je moje.
{13958}{14075}Dat æu ti je ako znaš|tko sam. - Lama.
{14190}{14247}Moje!
{14489}{14552}Ne, Lhamo. Vrati je.
{14665}{14731}Oprostite,|obièno to ne radi.
{15103}{15170}Uvijek govori kako|želi iæi u Lhasu.
{15184}{15231}Lhamo!
{16382}{16447}Hvala što si nam se pridružio.
{16519}{16578}Kažeš da je ovo tvoje.
{16657}{16715}Što je još tvoje?
{18090}{18150}Da, to je tvoje.
{18727}{18785}Da, to je tvoje.
{19703}{19776}Ovo je moje. Moje!
{19813}{19908}Da, Kundune!
{20278}{20401}Ovo je moje.|Moje! Treba mi.
{20437}{20562}Ovo je moje, mama.|- Lhamo, kupit æu ti bolji.
{20694}{20762}Dvije godine kasnije,|1939.
{20844}{20906}Tko ste vi? - Doði,|Lhamo, moramo poæi.
{21007}{21086}Postat æeš visoki Lama.|Veliki tibetanski sveæenik.
{21097}{21156}To je dobro. Ne boj se.
{21164}{21221}Nisi prvi djeèak|kojeg su ovako otkrili.
{21228}{21293}A sigurno nisi ni posljednji.
{21347}{21409}Neæu dopustiti|da te snaðe zlo.
{21419}{21497}Postat æeš|veliki èovjek. - Znam.
{21715}{21781}Tko ti je rekao|da smiješ tu sjediti?
{23421}{23511}(Ugledali smo logor.)
{23555}{23587}Regente Reting?
{23596}{23670}Ekselencijo, približava se|djeèakova karavana.
{24848}{24938}Nije više djetešce koje ste mi|rekli da naðem, Ekscelencijo.
{24955}{25056}Snažan je, veoma radoznao,|pomalo plašljiv.
{25065}{25129}Spreman je upoznati|èovjeka koji ga je otkrio.
{25602}{25668}Obrijat æemo ti glavu.|Ne boj se!
{25678}{25767}Ošišat æemo te!|- Doði!
{25998}{26056}Znaš li recitirati?
{26060}{26125}Neka budem iscjelitelj i|lijek, neka budem njegovatelj
{26130}{26221}svim bolesnima na svijetu,|dok svi ne ozdrave.
{26355}{26422}Možeš li upamtiti?
{26685}{26778}Neka budem zaštitnik|svim usamljenima.
{26785}{26867}Neka budem most,|èamac, brod,
{26875}{26939}svima koji žele|prijeæi preko rijeke.
{27065}{27158}Prije mnogo stoljeæa u|Tibetu se rodio djeèak.
{27181}{27244}Zvao se Gendundrub.
{27252}{27342}U noæi kad se rodio, pljaèkaši|su došli u njegov dom.
{27361}{27433}Obitelj je morala|bježati da bi se spasila.
{27466}{27524}Skrili su djetešce.
{27531}{27605}Kad su se vratili sljedeæi|dan, djetešce je bilo živo.
{27642}{27707}Èuvale su ga|dvije crne vrane.
{27730}{27871}Bio je prvi. Bio je|Samilosni Buddha.
{27878}{27935}Nazvali smo ga Kundun.
{28095}{28205}Samilosni Buddha.
{29351}{29415}Vidio sam te u priviðenju.
{29430}{29503}Ja sam Reting,|tvoj regent.
{29510}{29599}Našao sam te. Bilo je teško, ali|ostavio si mi dobre znakove.
{29631}{29725}Nadam se da nisi|predugo èekao, Kundune.
{30010}{30118}Odluèio si se vratiti u|ovaj život još jedanput.
{30141}{30296}Ostat æeš koliko god|možeš, a onda æeš se vratiti.
{30333}{30465}Raðaš se neprestano|iznova sve dok je života.
{30490}{30598}Tu si da bi|volio sva živa biæa.
{30610}{30743}Samo ih voli. Brini se za njih.|Budi samilostan prema njima.
{30779}{30871}Dokle god|sve živo bude disalo,
{30878}{30927}gdje god da bude,
{30934}{31026}u samilosti|pojavit æe se Buddha.
{33579}{33748}Samilosni Buddha. Dragulj koji|ispunjava želje. 14. Dalaj-Lama.
{37303}{37365}Sad æete primiti komornika.
{37863}{37951}Vaša Svetosti, ja sam|Phala, vaš komornik.
{37959}{38018}Služit æu vam|kako god budem mogao.
{38087}{38147}Peti Dalaj-Lama.
{38272}{38333}Sedmi Dalaj-Lama.
{38458}{38518}Trinaesti Dalaj-Lama.
{38597}{38701}Kad postanete punoljetni,|držat æete Veliki peèat.
{38908}{38991}Sretno, 14. Dalaj-Lamo!
{40365}{40442}Poderat æu je. Gledaj mene.
{40815}{40899}Ti si na redu.|- Pali!
{41003}{41094}Ja sam vojskovoða!|- Ja sam hrabriji!
{41107}{41237}Imam više vojnika. -Imam|pametnije vojnike. Svi su moji!
{41367}{41443}Danas si izgubio.|Sutra æeš možda pobijediti.
{41478}{41542}Stvari se mijenjaju, Kundune.
{42141}{42199}Reting traži previše od nas!
{42206}{42249}Koliko mu još moramo|dati zemlje i novca
{42255}{42316}zato što je našao djeèaka?|Sve ide iz našeg džepa.
{42325}{42404}A tu su i darovi i imanja|za Dalaj-Laminu obitelj.
{42441}{42490}Gle, otac!
{42501}{42562}Novèanici su nam prazni,|vojska oslabljena.
{42569}{42642}Regent traži preveliku nagradu|za pronalaženje Dalaj-Lame.
{42651}{42704}Iscijedit æe nas|do zadnjega novèiæa.
{42712}{42789}Ne mislite valjda da Reting|sam financira
{42797}{42872}pronalaženje djeèaka?|Nije tražio ovaj položaj.
{42886}{42992}Radije bi se povukao u osamu.|- Sa svim svojim ženama.
{43027}{43070}Veliki Trinaesti!
{43079}{43140}Možemo li ga vidjeti na licu|ovog divnog djeteta?
{43150}{43224}Ponovno se rodio tik|uz kinesku granicu.
{43231}{43330}Kao da je bacio rubac što je|dalje mogao pa je pao u Amdo.
{43340}{43400}Pljuska Kini!
{43406}{43479}Rekao je: Ovo je Tibet!|Rodit æu se ovdje.
{43491}{43601}Na rubu naše zemlje!|Kaže: Ovo je moj Tibet!
{43899}{44002}Vaš novi dom i nove sluge? Sve|je kako ste željeli? -Da, hvala.
{44636}{44702}Mama?
{45208}{45279}Mama?
{45363}{45428}Ne sviða mi se ovdje.
{45537}{45631}Ovo je stara, mraèna kuæa,|ali više æe ti se svidjeti
{45638}{45724}ljetni dvorac. Ondje|ima vrtova i životinja.
{45750}{45855}Jakova i pasa.|Pèela i ptica.
{45889}{45974}Paunova.|- Slonova? - Ne.
{45989}{46082}Rijeka i jezero.|- Riba? - Mnogo riba.
{46117}{46177}Tko je ova žena?
{46284}{46343}To je Penden Lhamo.
{46369}{46500}Njezina je dužnost da|štiti tebe i vladu Tibeta.
{46571}{46652}Je li stvarna ili|izmišljena? - Stvarna je.
{48549}{48639}Velike jedu tek|kad malene završe.
{49049}{49113}Svetosti, hoæete li dignuti ovo|sa stola? - To je tvoje mjesto.
{49222}{49322}Dalaj-Lama ne bi smio jesti|svinjetinu. Loše je za mozak.
{49329}{49408}Hajde uèiti. Nadrapat æu|ne budeš li uèio.
{49485}{49549}Dalaj-Lama ne smije jesti jaja.
{49957}{50013}Oprosti.
{50083}{50212}Imamo ga napokon.|- Jede jaja! - Nema jaja!
{50220}{50318}Otiðite! - Ne razgovara se tako|s ljudima. -Ali, ja zapovijedam.
{50331}{50390}Komu?
{50403}{50492}Mogu li spasiti ovce od|klanja? -Bogat si, kupi ih.
{50516}{50583}Hoæeš li ih kupiti za mene?|- Gdje æeš ih držati?
{50625}{50730}Ovdje. Ja i ti. - Onda|æu ih kupiti za tebe.
{50789}{50910}Sada imaš predivne konje.|- Da, imam ih. Idi sad.
{51004}{51063}Ne želim iæi!
{51226}{51317}Moji su zubi unutra!|- Koji zubi?
{51325}{51382}Moji zubi, sjeæam se.
{51435}{51477}Otvori ga!
{51923}{51984}Moji stari zubi.
{52049}{52128}Pripadali su 13. Dalaj-Lami.
{52347}{52405}Svetosti!
{52637}{52702}Vidovnjak kaže,|ako ne odem iz Lhase,
{52712}{52789}i ne posvetim se molitvi,|moj æe život biti ugrožen.
{52814}{52881}Molim vas, smjesta otiðite.
{52889}{52966}Mislite da bih trebao dati|ostavku? - Da, Ekscelencijo.
{52989}{53078}Ljudi se pitaju kako Reting|može davati obeæanja
{53085}{53157}u ime Dalaj-Lame|ako ih sam nije ispunjavao?
{53206}{53288}Žao mi je, rinpoche|Reting, ali istina je.
{53310}{53393}Dat æu ostavku,|ali kad opasnost proðe,
{53401}{53467}opet æu biti regent.
{53483}{53554}Želimo samo uèiniti što je|najbolje za Njegovu Svetost.
{54127}{54183}Utoèište su mi tri dragulja,
{54190}{54303}Buddha, Dharma i Sangha, dok|ne postignem prosvjetljenje.
{54345}{54403}Gdje je Reting?
{54419}{54524}Gdje je Reting danas?|- Otišao je iz Lhase, Svetosti.
{54534}{54590}Kamo je otišao?
{54621}{54679}Povukao se, Svetosti.
{54686}{54778}Na koliko dugo?|- Nekoliko godina.
{54845}{54928}Otišao je iz vaše službe.|Izabrat æemo novoga regenta.
{54985}{55106}Ne shvaæam. - Nije to za vaše|godine, Svetosti. - Zašto ne?
{55117}{55191}Utoèište su mi|Buddha, Dharma i Sangha
{55252}{55368}Hoæu da budete moj novi|regent. To je zapovijed.
{55488}{55550}Utoèište su mi tri dragulja,
{55556}{55669}Buddha, Dharma i Sangha, dok|ne postignem prosvjetljenje.
{56589}{56663}Èetiri godine kasnije,|1944.
{56670}{56727}Lobsane, sada? - Vozi!
{57747}{57841}Darovi sa Zapada. Dobio|ih je trinaesti Dalaj-Lama.
{59992}{60113}Važnost èetiriju plemenitih|istina. Koje su to istine?
{60125}{60204}Èetiri plemenite istine|prema Buddhinu uèenju su:
{60213}{60289}Istina patnje, istina|o tome zašto patimo
{60309}{60380}istina o kraju patnje...|- Pokazuješ previše ponosa.
{60416}{60553}Pogni glavu. Riponche Ling|ti je uèitelj. Pokloni mu se.
{60615}{60738}Što su uzroci patnje?|- Ponos uzrokuje patnju.
{60763}{60819}Recitiraj, sjeti se što znaš.
{60908}{60976}Moram napregnuti mozak.
{61069}{61131}Odgovori!
{61320}{61432}Prvo, èovjek shvaæa da sam|sebi bespotrebno zadaje
{61439}{61568}mnogo patnje. Drugo, traži|razloge za to u svome životu.
{61587}{61650}Gledati znaèi vjerovati|u svoju sposobnost
{61667}{61717}da ukloniš patnju.
{61727}{61812}Naposljetku, budi se želja|za pronalaskom puta k miru.
{61824}{61924}Sva biæa žele sreæu. Svi|žele pronaæi najèistijega sebe.
{62055}{62129}Vrijeme je da ga ostavite.
{62300}{62386}Ne želim da odete.|- Ostarjeli smo.
{62415}{62474}Bit æe ti dobro.
{62538}{62644}Nedostajat æete mi.|- Dobar si ti Dalaj-Lama.
{62770}{62890}Vidim sigurno putovanje.|Vidim siguran povratak.
{63376}{63433}Ovo je Britanija.
{63464}{63554}Gdje je Poljska, Norbu?|- Ne znam, Svetosti.
{63585}{63644}Gdje je Pearl Harbor?
{63666}{63736}Znaš li ti, Pompo?|- Ne znam.
{63905}{63963}Ovo je Tibet.
{63992}{64051}Ovo je Kina.
{64124}{64206}Koliko vojnika imamo?|- Oko pet tisuæa, Svetosti.
{64228}{64348}Pet tisuæa? Toliko?|To je mnogo.
{64378}{64462}Sigurni smo u Tibetu.|- Nadamo se, Kundune.
{65721}{65772}Lažljivci!
{65793}{65828}Budale!
{65835}{65911}Ništa niste nauèili!
{65962}{66045}Pet oblika degeneracije!
{66055}{66120}Crvena ideologija!
{66137}{66227}Opasnost iznutra i izvana!
{66264}{66312}Posveta!
{66319}{66354}Vještina!
{66361}{66408}Žaljenje!
{66414}{66462}Neuspjeh!
{67226}{67320}Poslušaj upozorenje|svoga prethodnika
{67352}{67452}ili æe rat doæi ovamo.
{67809}{67877}Oprezno!
{68510}{68578}Svetosti, imamo pismo.
{68770}{68862}13. Dalaj-Lama napisao je ovo|pismo godinu dana prije smrti.
{68878}{68937}Prije nego što ste se rodili.
{69018}{69078}Kad sam navršio 18 godina,
{69087}{69201}pozvan sam da zemlji|služim kao duhovni
{69216}{69278}i svjetovni poglavar.
{69298}{69415}Odgovornost je bila velika i|pritisnula me kao teško breme.
{69455}{69511}A onda su nas|okupirali Kinezi.
{69526}{69610}Mogli smo se samo moliti.
{69645}{69708}Molitve su nam brzo uslišane.
{69731}{69814}Jer velika je snaga istine,|a karma je nepogrešiva.
{69852}{69915}Istjerali smo Kineze.
{69962}{70131}Moguæe je da æe u Tibetu|vjera i vlada biti napadnute.
{70177}{70268}Samostani æe biti|opljaèkani i uništeni,
{70288}{70390}a redovnici i redovnice|ubijeni ili istjerani.
{70431}{70501}Postat æemo robovi osvajaèa.
{70525}{70626}Lutat æemo|bespomoæno kao prosjaci.
{70735}{70836}Dani i noæi prolazit æe sporo|u velikoj patnji i nasilju.
{71104}{71177}Gdje si ti roðen,|Taktra? - U Kyarpu.
{71227}{71339}A ti, Phala? -U Lhasi, Svetosti.|- Ovdje? - Da, Svetosti.
{71508}{71567}Što da radim?|Ja sam samo djeèak.
{71602}{71659}Vi ste napisali ovo pismo.
{71673}{71743}Vratili ste se|da biste nas vodili.
{71772}{71833}Uskoro æeš snositi|veliku odgovornost.
{71906}{71976}Moraš znati|što treba uèiniti.
{72050}{72119}Jedan je B-29 iznad|japanskoga grada Hirošime
{72127}{72199}oznaèio poèetak|nove ere za civilizaciju...
{72299}{72432}U 8;15 h ujutro bomba teška|800 kg i velike razorne moæi...
{72442}{72532}...gljiva je sravnila|osupnuti neprijateljski grad.
{72539}{72596}Uplašenim se stanovnicima|èinilo da je kraj svijeta.
{72602}{72676}Gotovo užasno lijep gljivasti|oblak vinuo se u nebo.
{72683}{72757}Nastanak atomske gljive|postat æe simbol smrti
{72762}{72797}i razaranja.
{72805}{72853}Jedan je znanstvenik|proroèanski upozorio
{72862}{72958}da je eksplozija atomske|bombe najsliènija sudnjem danu.
{72968}{73025}Kad nastupi kraj svijeta,|siguran sam da æe
{73031}{73131}posljednji ljudi vidjeti|što smo mi danas vidjeli.
{73203}{73259}Kako je dragocjen|ljudski život?
{73306}{73406}Zbog prošle si karme|dobio ovaj ljudski život.
{73431}{73496}Neuki, nemoj sada zaspati!
{73707}{73763}Ne vidim!
{73773}{73828}Što se dogaða?
{74006}{74065}To je moj prijatelj,|ostavite ga na miru.
{74075}{74147}Norbu, što se dogaða?|- Uhiæen je riponche Reting.
{74167}{74229}Reting? - Kundune, žao mi je.
{74241}{74318}Nije ovo za tvoje oèi.|- Zašto nije?
{74583}{74644}Sazovite Kashag.
{74802}{74950}Što se dogodilo Retingu?|- Veoma je zamršeno, Svetosti.
{74995}{75040}Recite mi!
{75115}{75187}Reting je opet htio|postati regent.
{75193}{75251}To više nije bilo moguæe.
{75256}{75322}Pokušali su ubiti|rinpochea Taktru.
{75345}{75408}Doista?|- Reting je uhiæen.
{75427}{75498}Redovnici iz samostana Sera su|se borili na Retingovoj strani.
{75561}{75667}Redovnici imaju puške? - U|ovome sluèaju imaju, Svetosti.
{75713}{75830}Nisam znao da redovnici imaju|puške. -Inaèe nemaju, Svetosti.
{75902}{75981}Gdje je sada riponche Reting?|- Zatvoren je ovdje u Potali.
{76027}{76100}U Potali postoji zatvor?
{76115}{76182}Oduvijek je ovdje|bio zatvor, Svetosti.
{76309}{76399}Nešto treba|promijeniti u Tibetu.
{76462}{76518}Mi bismo èaja.
{76600}{76733}Jesi li ozlijeðen? - Dobro sam.|Star sam i teško me ubiti.
{76927}{76984}Prièajte mi o Kini.
{77027}{77089}I to je veoma|složena situacija.
{77132}{77248}Vaša Svetosti, Kinezi opet|pokušavaju uvjeriti svijet
{77257}{77314}da Tibet pripada njima.
{77324}{77452}Tibet je Tibet. - Dugo smo|vremena bili nenaoružani.
{77461}{77544}Znali smo da i oni to znaju.
{77559}{77622}Sada pokušavaju|izmijeniti povijest.
{77682}{77734}Kakva nesreæa!
{77838}{77901}Zašto ne zamolimo sve Kineze|koji žive ovdje da odu?
{77907}{77985}Ako ovdje nema Kineza, Tibet|ne može biti kineska pokrajina.
{78040}{78100}Veoma dobro! Vrijeme je|da podsjetimo svijet
{78105}{78164}da smo neovisni.
{78173}{78258}Može li nam Indija pomoæi?|Znaju da nismo dio Kine.
{78291}{78348}Indija je nedavno|stekla neovisnost.
{78354}{78414}Još se bore i|ne mogu nam pomoæi.
{78452}{78530}Britanija? - Britanija je|odluèila da neæe pomoæi.
{78609}{78748}A Amerika?|- Vidjet æemo, Svetosti.
{78759}{78823}Napisat æu pismo|predsjedniku Amerike.
{78875}{78925}Izvrsno, Kundune.
{78937}{78984}Idem posjetiti|riponchea Retinga.
{78991}{79050}Ne bih vam|savjetovao, Svetosti.
{79199}{79265}Hoæu da dobro postupate|s riponcheom Retingom.
{79276}{79350}On mi je uèitelj.|On me našao.
{79365}{79426}Bit æe kako vi|kažete, Vaša Svetosti.
{79725}{79833}Moram znati što vi znate|sada. Nisam više dijete.
{80076}{80141}Mao Ce-tung pozvao je na rat.
{80149}{80208}Uspostavit æe|komunistièku Kinu.
{80218}{80275}Hoæe li Željezna zavjesa|pasti na Aziju
{80281}{80338}kao što je pala na|Rusiju i Istoènu Europu?
{80345}{80456}Objava rata|i 20 godina borbe...
{80609}{80665}Kundune!
{80675}{80815}Poslušajte ovo: Gospodinu|Trumanu, predsjedniku SAD-a.
{80837}{80904}Drago mi je|što ste dobra zdravlja
{80911}{81014}i što se zalažete za sreæu i|blagostanje cijeloga svijeta.
{81031}{81124}Dajem sve od sebe|za Buddhinu vjeru
{81132}{81188}i dobrobit svih živih bièa.
{81253}{81314}To je zasad sve.
{81329}{81419}Kundune, riponche|Reting je umro u zatvoru.
{81833}{81955}Budi sabran dok|ulaziš u osviještenost.
{81998}{82164}Budi sabran. Poði|ocu svomu. Mrtav je.
{82240}{82321}Vaša bi majka htjela da|obavite posljednji ritual.
{82388}{82451}Budite sabrani.
{84935}{85008}Komunisti su|preuzeli vlast u Kini.
{85063}{85161}Samilosni Buddha|trebao bi ovo znati.
{85321}{85407}Mao Ce-tung postavio|je Tibetu tri zahtjeva.
{85443}{85540}Prvo, Tibet mora prihvatiti|èinjenicu da je dio Kine.
{85652}{85757}Drugo, Kina mora|preuzeti obranu Tibeta.
{85918}{86031}Treæe, sve politièke i|trgovinske veze s inozemstvom
{86038}{86109}održavat æe se preko Kine.
{86820}{86893}Pet godina kasnije,|1949.
{86938}{86995}Što biste vi|uèinili, Svetosti?
{87275}{87345}Prihvatimo li prvi zahtjev,|da Tibet postane dio Kine,
{87361}{87419}ništa drugo više|neæe biti važno.
{87544}{87604}Kupit æemo ih!|Kupit æemo ih!
{87696}{87835}Što biste vi uèinili, Taktra?|- Moje je mišljenje nebitno.
{87890}{87949}Odbacio bih sva tri zahtjeva
{87956}{88027}i rekao da nam Kinezi|neæe nareðivati.
{88076}{88133}Poslušat æemo glas naroda.
{88140}{88239}Pitat æu zaštitnièka|božanstva za savjet.
{88254}{88317}Buddha se pojavljuje gdje je|najpotrebniji. - Kako vi kažete.
{91349}{91406}Uðite.
{91568}{91625}Sazovite Kashag.
{91725}{91807}Svetosti. - Da?|- Kinezi su nas okupirali.
{93128}{93207}Kinezi su prešli rijeku na|šest mjesta oko Chamda.
{93264}{93378}Ima li poginulih? -Radioamater|je javio da je jedan ubijen.
{93390}{93524}Rekao je da kineski vojnici|dolaze i onda je radio utihnuo.
{94015}{94080}Ovoga je tjedna poèelo|mirno oslobaðanje Tibeta.
{94088}{94148}Pripadnici komunistièke|vojske ušli su u
{94153}{94242}zapadnu kinesku pokrajinu|na zahtjev tibetanske manjine.
{94255}{94313}Dugo pod vlašæu imperijalista
{94318}{94391}Tibetanci su živjeli u|feudalnome kraljevstvu
{94400}{94458}pod vlašæu Dalaj-Lame.
{94468}{94538}Dok vojska napreduje|prema Lhasi,
{94545}{94619}seljaci pozdravljaju|osloboditelje
{94628}{94685}i pridružuju se pohodu.
{94698}{94769}Što narod kaže, Norbu?|- Misle da je sad vrijeme
{94775}{94884}da stupite na tron.|- Premlad sam, nemam iskustva.
{94934}{95011}Naravno da imate iskustva,|Kundun. Tko bi drugi bio ovdje?
{95092}{95149}Norbu?|- Da, Svetosti?
{95155}{95231}Pitaš li se ikad je li Reting|pronašao pravoga djeèaka? - Ne.
{95340}{95403}Htio bih imati 18 godina|kada doðem na prijestolje.
{95410}{95466}Svi su Dalaj-Lame|èekali do osamnaeste.
{95882}{95943}Kucnuo je èas.
{96100}{96269}Svetosti, 17. studenoga 1950.|Stupit æete na prijestolje.
{96321}{96410}Tražimo da zbog opreza odmah|nakon toga napustite Lhasu.
{96502}{96558}Kako vi kažete.
