{498}{552}Hoæemo li proèitati pravila posjeta?
{563}{593}Proèitajte ih.
{602}{668}Gospodine, fizièki dodir...
{670}{755}ogranièen je na jedan zagrljaj|na poèetku i jedan na kraju.
{757}{817}Ruke se moraju èitavo vrijeme vidjeti.
{833}{880}Znaèi nema igranja rukama.
{986}{1024}Hvala, gospodo.
{1093}{1134}Mogu li sjesti, gospodine?
{1141}{1173}Dopušteno.
{1551}{1589}Što radiš ovdje, Jime?
{1591}{1642}Došao sam vidjeti jesi li skrenuo.
{1693}{1765}Trebao bi biti dostupan kasnije.|Prièekajte trenutak.
{1774}{1867}Miss Kelly, tu je sve osim atletske opreme.
{1872}{1952}To sam našao na podu, u hodniku.
{1956}{1985}Što je, Danny?
{1989}{2068}- To sam našao u hodniku.|- Hvala, Danny.
{2072}{2151}Trebate nam ih poslati što prije moguæe.
{2158}{2181}PUKOVNIK WINTER
{2183}{2227}OSOBNO I POVJERLJIVO|PROÈITATI DO 12.00
{2230}{2335}Kaže da patiš od iluzija, da se ponašaš|kao da još uvijek zapovijedaš vojskom.
{2346}{2408}To kaže jer želi da me premjeste.
{2753}{2812}U STANJU SMO OTETI|GENERALA WHEELERA.
{2815}{2864}NE DOÐETE LI U CENTAR ZA POSJETE
{2866}{2905}I NE DATE LI MU OSTAVKU DO 12.10.
{2907}{2963}ON ÆE POSTATI NAŠ ZATVORENIK.|G. IRWIN
{2965}{3049}Da imaš nepobitne dokaze da je Winter|hladnokrvno ubio èovjeka...
{3051}{3127}bez dobrog razloga,|tada bih možda mogao nešto uèiniti.
{3138}{3265}Veæ tri puta je bio pod istragom|i osloboðen je od svih optužbi.
{3269}{3374}Što se Washingtona tièe,|on radi izvrstan posao.
{3378}{3431}A ti si osuðeni kriminalac.
{3532}{3591}- Mogao bi zatražiti još jednu istragu.|- Mogao bih.
{3593}{3665}Ali bez ikakvih novih dokaza,|kakav je smisao toga?
{3667}{3761}I osim toga, Gene, iskreno ti kažem,|nije me uopæe briga.
{3783}{3883}Briga me jedino za tebe,|i da te odavde izvuèem.
{3885}{3938}Zar se nisi veæ dovoljno kaznio?
{3960}{4017}Ono što sam uèinio bilo je loše, Jime.
{4039}{4092}Sve jedinice, ovo je opæa uzbuna.
{4094}{4177}Sve jedinice, ovo je opæa uzbuna.
{4446}{4499}Ne mogu dopustiti da se ovo nastavi.
{4514}{4623}Izaæi æeš odavde i provesti malo vremena|sa svojom kæeri i unukom.
{4635}{4729}Moje osoblje može pripremiti nalog|za pomilovanje iz zdravstvenih razloga...
{4731}{4782}Nisam bolestan.
{4786}{4837}Hoæeš li suraðivati?
{4839}{4879}Nisam bolestan.
{4881}{4941}Ne vidim nikakve znakove, gospodine.
{4960}{5036}Naravno da ne.|Skrivat æe to do posljednjeg trenutka.
{5141}{5186}Crvena jedinica, kreni.
{5190}{5220}Idi, idi, idi!
{5244}{5281}O èemu se ovdje radi?
{5298}{5397}Radi li se o kontroli?|Ni jedan dvorac ne može imati dva kralja!
{5472}{5497}Na pod!
{5546}{5574}Što radiš?
{5617}{5683}Svi zatvorenici neka ostanu potrbuške|na tlu.
{5796}{5850}Zaboga, što se dogaða?
{6934}{6961}Gospodine?
{6974}{7009}Suzavac?
{7028}{7138}Vratite se u hangar, ništa se ne dogaða.|Bio je blef.
{7143}{7219}Možete ga vratiti doma. U hangar.
{7270}{7350}- Mislili ste da æe me uzeti kao taoca?|- Mjere predostrožnosti.
{7352}{7436}Kakvom jedinicom vi ovdje zapovijedate,|pukovnièe?
{7479}{7546}Jutros u 11:58 primio sam pismo...
{7550}{7655}u kojem je pisalo da vas grupa zatvorenika|namjerava uzeti kao taoca u 12.10.
{7659}{7717}Mislio sam da je bolje odmah reagirati.
{7721}{7806}Èuo sam neke prilièno uznemirujuæe stvari|o zbivanjima u ovom zatvoru.
{7808}{7901}Sada to opet èujem od èovjeka|komu vjerujem i èije mišljenje poštujem.
{7903}{7953}- Mogu li slobodno govoriti?|- Možete.
{7955}{8055}S dužnim poštovanjem, generale,|ne znam što ste mogli èuti.
{8064}{8144}No dok ne provedete neko vrijeme|u dvorištu sa tim životinjama...
{8146}{8203}neæete imati pojma što se ovdje dogaða.
{8220}{8259}Shvaæam.
{8270}{8381}No èujem li još samo jednu prièu o nekomu|tko je umro pod vašom upravom...
{8385}{8451}ovdje ste gotovi. Shvaæate li?
{8471}{8507}Da, gospodine.
{8560}{8590}U redu.
{8627}{8714}Što se tièe Irwina, moje je mišljenje|da je zdrav koliko i vi ili ja.
{8716}{8771}Volio bih da nije, ali jest.
{8785}{8855}Ništa ne bih volio više nego razlog|da ga izvuèem odavde.
{8857}{8945}Ali jedini je naèin da se to dogodi|ako vi to zatražite.
{8994}{9036}To je toèno, gospodine.
{9042}{9135}Recite mi da ga ne možete savladati,|i odvest æu ga.
{9172}{9233}Mislim da ga mogu savladati.
{9274}{9321}Èuvajte se, pukovnièe.
{9447}{9488}"Eugene R. Irwin.
{9563}{9681}"general amerièke vojske,|suprotno nareðenju...
{9683}{9758}"njegovog vrhovnog zapovjednika|da evakuira Burundi..."
{9787}{9867}"Zapovjednik" je predsjednik,|za one od vas koji ne znaju.
{9884}{10002}...izabrao je vod vojnika da bi našli i uhitili|Jacksona Ngwea, lokalnog diktatora.
{10006}{10078}"Zanemarujuæi pouzdane informacije...
{10092}{10173}"vojnici gen. Irwina ušli su u grad u 03.00.
{10175}{10259}"Osmorica su uhiæeni i smaknuti."
{10290}{10329}Zanemarujuæi...
{10358}{10416}pouzdane informacije...
{10438}{10478}osmorica su...
{10493}{10531}smaknuti.
{10641}{10753}Ono što želim da shvatite jest|kakve mogu biti posljedice...
{10780}{10908}kada odluèite slijediti èovjeka|koji je voðen samo svojim ponosom.
{10923}{11048}Èovjek koji bi uèinio bilo što kako bi|upisao još jednu pobjedu na pojas...
{11064}{11112}bez obzira na cijenu...
{11129}{11179}prije nego nestane.
{11352}{11391}Poènite s izvlaèenjem.
{11748}{11828}- Skidaj jebene ruke s mene!|- Idemo! Izlazi!
{11836}{11906}U redu, doktore, idemo u šetnjicu.
{11933}{11976}Vraæaj se ovamo!
{11982}{12011}Otvori 355.
{12015}{12046}Otvori je!
{12120}{12176}Vidi ih. Opustite se, dame.
{12238}{12275}Ja nemam veze s tim.
{12608}{12652}Nema razloga za to!
{12832}{12873}Ne stavljaj me u samicu!
{14482}{14513}Što æemo sada?
{14644}{14756}Svi zahtjevi za posjete moraju biti|podneseni upravi do 11.00 danas.
{14790}{14862}Znaèi zaista si blefirao Wintera.
{14893}{14958}Problem je u tome|što je on imao bolju ruku.
{14976}{15031}Ja ne igram poker, igram šah.
{15043}{15115}U šahu, kada igraš s nekim dovoljno dugo...
{15117}{15197}shvatiš da su njihova prva tri poteza|uvijek ista.
{15200}{15245}Koji je bio njegov prvi potez?
{15248}{15341}- Koji je bio prvi potez?|- Dvije jedinice sa po 20 èuvara.
{15346}{15406}Unutarnje jedinice su imale samo palice.
{15408}{15434}Drugi potez?
{15436}{15467}Vodeni top.
{15471}{15509}- Treæi?|- Helikopter.
{15523}{15595}Trebamo li o ovome raspravljati|pred ovim èovjekom?
{15597}{15646}Znaš da mu se ne može vjerovati.
{15704}{15728}Ne znam.
{15778}{15837}Tako koristiš breme zapovijedanja?
{15840}{15912}Pretvaraš ljude u šahovske figure?
{15962}{15993}Da.
{16024}{16065}Zašto ne odeš?
{16129}{16168}Svima vama manipulira.
{16193}{16264}Zatvorenik koji odlazi, tko je to?
{16273}{16298}Yates.
{16307}{16416}Bio je pilot Apache helikoptera|a sada je propalica, varalica, kladionièar.
{16421}{16478}- Na što se kladi?|- Na bilo što.
{16480}{16518}Tuènjave, vrijeme.
{16540}{16623}Uzimao je opklade èak i na to|hoæe li se Irwin ubiti ili ne.
{17235}{17357}"Ovaj izrazito uèinkovit èasnik|bez ikakvog je morala."
{17402}{17439}Je li to istina?
{17454}{17518}To misle ljudi koji su bolji od mene, da.
{17564}{17656}Zašto si ovdje, Yatese?|Volio bih èuti tvoju verziju.
{17708}{17804}Bio sam umiješan u krijumèarenje droge|iz Juareza u El Paso...
{17808}{17871}uz nekoliko mojih podèinjenih.
{17880}{17921}Bio si umiješan?
{17929}{17984}Ti si vodio tu operaciju, zar ne?
{17988}{18019}Toèno.
{18078}{18178}Ovdje kaže da si tajno snimao svoje ljude.
{18190}{18230}Je li to toèno?
{18240}{18265}Da.
{18268}{18373}Koliko ti je smanjena kazna zbog toga?
{18375}{18421}Skinuli su mi èetiri godine.
{18467}{18515}Sada si zatvorski kladionièar.
{18581}{18653}Reci mi, Yatese,|kako je èovjek poput tebe...
{18679}{18726}dospio na West Point?
{18730}{18803}Moj otac je dobio|najviše odlikovanje kongresa.
{18848}{18878}Tako znaèi.
{18978}{19050}Nekada jabuka padne daleko od stabla.
{19134}{19171}Tvoj otac.
{19198}{19287}Tvoj otac je bio ratni zarobljenik|sa g. Irwinom, zar ne?
{19447}{19472}Toèno.
{19475}{19561}A ti se ipak nisi pridružio Irwinovom...
{19565}{19600}križarskom pohodu?
{19612}{19647}Križarskom pohodu.
{19663}{19719}- Zašto?|- To nije moja borba.
{19723}{19765}G. Irwin se s nekim bori?
{19810}{19870}Ovdje piše da ti preostaju tri godine...
{19889}{19949}s nama. Toèno?
{19957}{19997}Ako tako piše.
{20001}{20048}Tako piše.
{20093}{20137}Zvuèi li tri mjeseca bolje?
{20189}{20284}Moram ovu stvar riješiti...
{20301}{20369}prije nego još netko pogine|ili bude povrijeðen.
{20407}{20441}Slažeš se?
{20462}{20488}Valjda.
{20490}{20560}A to mogu postiæi uz pomoæ informacija.
{20610}{20709}Pa, trebao bi dobro razmisliti|želiš li se pridružiti Irwinovom...
{20731}{20766}križarskom pohodu.
{20941}{20998}Želite da budem vaš doušnik, gospodine?
{21002}{21076}Nije li kasno da bi se u tebi|rodio smisao za pravdu?
{21108}{21154}Zašto baš mene moraš udariti?
{21159}{21240}Prestani cmizdriti.|Samo æu te jednom udariti.
{21255}{21308}- Kada?|- Sada!
{21343}{21367}Bori se!
{21875}{21909}Unatrag!
{22077}{22154}Na guzice. Sjednite, smjesta. Idemo!
{22280}{22350}Momci, nemamo puno vremena.
{22462}{22569}Ne možemo više nositi vojnièke odore.|Izgubili smo to pravo.
{22585}{22625}To se odnosi i na mene.
{22647}{22704}Nisam izvršio naredbu.
{22710}{22783}Prekršio sam svoju dužnost zapovjednika.
{22803}{22872}Osam muškaraca je platilo straviènu cijenu.
{22918}{22976}To je greška s kojom nije lako živjeti.
{22992}{23067}Tu sam, kao i vi, osuðeni kriminalac.
{23088}{23180}Jedina razlika izmeðu vas i mene|jest da ja znam da sam kriv.
{23231}{23292}Odstranjeni smo ovamo kao zatvorenici...
{23345}{23388}i jedna stvar je sigurna:
{23406}{23458}naši èuvari imaju vlast nad nama.
{23479}{23522}Mogu nas pokušati poniziti.
{23532}{23570}Mogu nas istuæi.
{23577}{23682}Mogu nas danima držati u samici,|ali jednu stvar ne mogu uèiniti.
{23698}{23773}Ne mogu nam oduzeti ono što jesmo.
{23797}{23842}Mi smo vojnici.
{23887}{23966}To je jedina stvar|koja nas ovdje može održati.
{24015}{24068}A to nam nitko ne može uzeti.
{24072}{24105}Tako je.
{24214}{24271}Kodeks vojne pravde.
{24328}{24422}"Osnove za skidanje s dužnosti|zapovjednika kaznene kasarne.
{24441}{24467}"Jedan:
{24474}{24516}"Zanemarivanje dužnosti.
{24523}{24583}"Dva: kriminalno ponašanje.
{24590}{24678}"Tri: nepoštivanje proceduralnih pravila.
{24682}{24752}"Èetiri: davanje lažnih izjava.
{24773}{24861}"Pet: ponašanje koje ne pristaje|èasniku i gospodinu.
{24908}{25009}"Šest: Okrutnost i maltretiranje|osoba pod njegovom komandom.
{25112}{25227}"Sedam: gubitak nadzora nad ustanovom."
{25279}{25308}Gospodo...
{25339}{25421}predlažem da se domognemo nadzora|nad ovom ustanovom.
{25834}{25885}Uzmi dvorac, bilo koji dvorac.
{25889}{25965}Sada razmisli o osnovnim stvarima|koje ga èine dvorcem.
{25972}{26073}Položaj. Zaštita. Vojnici. Zastava.
{26093}{26165}Jedina razlika izmeðu ovog dvorca|i ostalih je...
{26167}{26231}da su sagraðeni|kako bi sprijeèili ljude da uðu.
{26234}{26295}Ovaj je sagraðen|kako bi ih sprijeèio da izaðu.
{26297}{26335}Ali i dalje je dvorac.
{26351}{26459}Svaki dvorac može biti osvojen,|radilo se o 14. Ili 21. Stoljeæu.
{26529}{26640}Kako bi se osvojio dvorac,|morate nadvladati vojnike...
{26660}{26702}zauzeti položaj...
{26725}{26779}i, konaèno, zaplijeniti zastavu.
{26796}{26826}Enriquez.
{26907}{27015}Ti pripremi komandno mjesto, u redu?|Ovdje imaš èuvare.
{27019}{27109}Kao prvo, ovo je upravna zgrada.|Winterov ured.
{27114}{27143}Èuvari.
{27170}{27277}Prva faza: neutralizirati Winterove èuvare.|Druga faza: tornjevi.
{27279}{27340}Ako nadzireš tornjeve, nadzireš dvorište.
{27342}{27438}Toranj 1, toranj 2, toranj 3, toranj 4.|Toranj 4 je Zamorro.
{27450}{27488}Njega se treba èuvati.
{27519}{27559}Treæa faza: vodeni top.
{27626}{27663}Faza 4: helikopter.
{27693}{27744}Helikopter znaèi zauzeti uzvisinu.
{27751}{27814}Bit æe teško doæi do helikoptera.
{27830}{27863}Ali je moguæe.
{27886}{27932}Konaèno, zastava.
{27964}{28052}Kada zaplijenimo zastavu,|podiæi æemo je naglavce.
{28062}{28098}To znaèi opasnost.
{28140}{28265}Toèno. Zastava naglavce znaèi:|"Šaljite pomoæ. Tvrðava je pala."
{28269}{28374}Podignemo je naglavce i tako je držimo|dok je Wheeler ne stigne i ne vidi je.
{28378}{28415}Tada smo pobijedili.
{28418}{28478}Yatese, zatvori... Shvaæaš što hoæu reæi?
{28494}{28551}Yatese, što ovdje radiš?
{28556}{28605}Pitaj njega, on me pozvao.
{28609}{28678}Znam da je njegov otac|služio s vama u Vijetnamu.
{28690}{28736}Ali zar nam zaista treba?
{28743}{28785}Da, on ostaje.
{28789}{28863}- Duffy, ti radiš u održavanju?|- Da, gospodine.
{29048}{29076}Yatese.
{29110}{29142}Imaš trenutak?
{29193}{29225}Kako stojim?
{29238}{29292}5:2 za pukovnika.
{29338}{29385}Misliš da ne mogu pobijediti?
{29453}{29513}On previše zna. Pripremljen je. Spreman.
{29528}{29594}Možda je pripremljen, ali ne i spreman.
{29612}{29649}Ti bi nam mogao koristiti.
{29652}{29728}Samo želim ovo preživjeti i vratiti se doma.
{29767}{29805}Nagodio si se s njim?
{29811}{29878}Ja bih to uèinio na njegovom mjestu.|Obratio se tebi.
{29880}{29961}On zna za što si sposoban. Ali i ja.
{29989}{30101}O, da? Znam za što si sposoban.|Poznajem takve kao ti.
{30105}{30195}Je li to iz tvojeg dugogodišnjeg iskustva|na bojnom polju?
{30227}{30301}Zašto bih ti pomogao?|Možeš li me ti izvuæi odavde?
{30305}{30354}- Ne.|- Što æeš onda uèiniti za mene?
{30356}{30412}Ponovno od mene stvoriti vojnika?
{30414}{30495}Postat æu sve ono što mogu biti?|Nauèit æeš me da salutiram?
{30497}{30597}Ovo je otprilike vrijeme kada bih ti održao|svoj govor o vojniku u tebi.
{30614}{30714}Ali istina je da ti vjerojatno|nikada nisi trebao postati vojnik.
{30728}{30794}Tvoj otac je bio vojnik|i ja sam ga tako doživljavao.
{30796}{30867}Ti si ga doživio kao razoèarenje.
{30881}{30916}To je bilo tada.
{30919}{31004}Jedina stvar koja je ovdje važna|je što smo sada i što æemo uèiniti.
{31006}{31122}Ovaj èovjek vidi ono najgore u tebi i to æe|iskoristiti. Ja želim vidjeti ono najbolje.
{31132}{31204}To znaèi da nema sredine.|Potreban si ovim ljudima.
{31206}{31282}I meni si potreban. Ti izaberi.
{31309}{31393}Ne govori mi da preživljavaš u zatvoru.|Ti se sakrivaš.
{31576}{31642}- Kako ide veèeras, gospodine?|- Dobro, a vi?
{31646}{31672}Gospodine?
{31710}{31772}Zatvorenik Yates želi s vama porazgovarati.
{31841}{31882}Dajte mi pet minuta.
{31972}{31997}Bok.
{32000}{32025}Bok.
{32088}{32175}Ured pukovnika Wintera. Pošalji to gore.
{32286}{32318}Gospodine?
{32371}{32424}- Da?|- Zatvorenik Yates.
{32554}{32607}Želite da uèinim to za vas.
{32619}{32724}Tih 30 dana, ta tri mjeseca, nije dovoljno.
{32729}{32806}Želim odmah odavde. Sutra.
{32823}{32869}Bojim se da to nije moguæe.
{32873}{32988}Kada ta stvar eksplodira,|svi æe znati da sam ja izbrbljao.
{32992}{33040}Tada moj život neæe ništa vrijediti.
{33042}{33116}Stoga, ili æete me odmah izvuæi odavde...
{33121}{33216}ili æete naæi nekog drugog momka|koji zna koliko i ja i voljan je to izbrbljati.
{33218}{33253}Sa sreæom.
{33307}{33364}Najranije što te mogu izvuæi je tjedan dana.
{33366}{33464}Neæu preživjeti ni sedam sekundi.
{33468}{33558}Možeš odsjediti taj tjedan u samici.|Tamo te nitko neæe dirati.
{33656}{33744}l, što g. Irwin smjera?
{33750}{33810}Smjera osvojiti zatvor.
{33829}{33859}Zbilja?
{33883}{33936}Ta te informacija neæe izvuæi odavde.
{33938}{34018}Neæe ti osigurati ni veæu porciju krumpira.
{34020}{34061}Poznajem potankosti.
{34069}{34168}Znam da smjera neutralizirati vaše ljude|i zauzeti tornjeve...
{34172}{34229}i kakvo oružje i oruðe pravi.
{34306}{34345}Znaš li kada?
{34388}{34445}Yatese, znam da si tu!
{34458}{34505}Svinjo doušnièka!
{34510}{34553}Cutbush, umukni!
{34592}{34627}Što on ovdje radi?
{34632}{34675}Donio je èisto rublje i skrenuo s uma.
{34677}{34765}Dosta je bilo! Smjestite ga u samicu.|Neka nitko s njim ne razgovara.
{34767}{34816}Stavite mu èuvara pred samicu.
{34820}{34855}Prokleti štakor!
{34859}{34945}U èemu je problem? Majka mi je bolesna!|Pokušavam dobiti dopust.
{34947}{34983}Nosite ga odavde!
{34987}{35020}Kapetane, doðite.
{35117}{35157}Isuse.
{35173}{35224}Sada nemaš izbora...
{35231}{35314}ili æeš provesti sljedeæe tri godine u samici.
{35361}{35452}Treba mi vremena.|Moram se vratiti meðu zatvorenike.
{35487}{35577}Sutra æu nešto znati.|Doðite po mene u 5.00.
{35587}{35626}Treba mi još vremena.
{35665}{35758}Zatvorenici, jedan korak unatrag, marš!
{37198}{37248}Gdje je Yatesova æelija?
{37258}{37301}Broj 340, gospodine.
{37499}{37543}Jesi li spreman propjevati?
{37550}{37600}- Dobro jutro, gospodine.|- Voljno.
{37662}{37693}Pukovnièe?
{37741}{37775}Pukovnièe?
{37905}{37939}Dobro jutro.
{37967}{37996}Dobro jutro.
{38066}{38118}Što imaš za mene?
{38173}{38208}Ne baš puno.
{38239}{38267}Ne baš puno?
{38332}{38369}Zašto si onda tu?
{38433}{38486}Ima nešto što æe vas možda zanimati.
{38547}{38626}Kada zauzmu zatvor|podiæi æe zastavu naglavce.
{38639}{38667}Naglavce?
{38670}{38759}- To je meðunarodni znak opasnosti.|- Da, znam što znaèi.
{38809}{38852}Gdje æe naæi zastavu?
{38878}{38919}Veæ je imaju.
{38933}{38958}Vašu.
{38973}{39006}Moju?
{39256}{39297}Peretz, tko je juèer ulazio ovdje?
{39299}{39348}Ja sam je uzeo, jebeni ubojico!
{39501}{39549}Mislio sam da si pametniji.
{39571}{39603}Znam.
{39764}{39826}Reæi æeš nam gdje je zastava?
{39844}{39912}Ustani, Yatese. Gdje je zastava?
{39994}{40045}Ti si zaista jebena kukavica, Zamorro.
{40047}{40111}A ti si veliki junak. Idemo!
{40113}{40201}Diži ruke s mene, gade!
{40237}{40285}Umukni, Yatese.
{40651}{40725}Svi zatvorenici neka napuste æelije.|Ovo je pretraga.
{40899}{40980}Svi zatvorenici neka krenu prema dvorištu|kroz južna vrata.
{41128}{41177}Dva po dva, kreæite!
{41612}{41649}Onamo, gospodine.
{41666}{41707}Ludo, zar ne?
{41746}{41787}Zaista ludo.
{42110}{42188}Kapetane Peretz, naðite moju zastavu.
{42422}{42457}6.10.
{42503}{42528}6.10.
{42794}{42899}Ne želim èuti da je niste našli.|Dobili ste naredbu, naðite tu prokletu stvar!
{42915}{42974}Gospodine, našli su puno oružja.
{42987}{43022}Ali ne i zastavu.
{43026}{43109}Ne, gospodine.|Ali barem imamo svo njihovo oružje.
{43133}{43187}Sada ne mogu puno toga uèiniti.
{43320}{43389}Koliko ljudi pretražuje æelije?
{43393}{43466}Oko 100. Gotovo svi koje smo mogli naæi.
{43522}{43563}Zastava nije važna.
{43575}{43675}On želi biti u dvorištu.|Dovedi naše iz æelija u dvorište, smjesta!
{43724}{43821}Svi u dvorište! U stroj!|Idemo! Dvostrukom brzinom!
{44019}{44049}Smjesta!
{44133}{44251}Peretz, odmah dovedi te ljude u dvorište!|Obavijesti specijalce! Idi, idi!
{44353}{44385}Lanci!
{44688}{44752}Kakav je to osjeæaj? Želiš slobodu?
{44908}{44962}Postavi komandno mjesto, brzo!
{45175}{45240}Spusti me! Znaš li što æe ti se dogoditi?
{45400}{45455}Beaupre, jesi li to ti?
{45459}{45515}Je li poèeo napad? Jebi ga, jeste.
{45612}{45690}Prokletstvo! Lancima su zatvorili vrata.
{45731}{45765}Vidim to.
{45795}{45854}Trebat æe im vremena da izaðu.
{45890}{45973}Kada stignu reci im da budu spremni|za napad, ali zadrži ih.
{45975}{46040}Oèekivat æe da odmah reagiramo,|zato neæemo.
{46123}{46206}Gnjido. Kladio sam se protiv tebe|i izgubio èitav svežanj cigareta.
{46208}{46247}Danas je puno gubitnika.
{46531}{46558}Èuvaj se.
{46588}{46669}Hajde, Zamorro, jebaèu! Hajde!
{46682}{46720}Vjeruješ li ti u to?
{46725}{46784}U redu, idemo. Idemo!
{46812}{46859}- Izvadi to!|- Kasnije!
{47005}{47109}Poslušaj me. Pukovnik je rekao|da ih zadržimo, u redu. Zadrži ih.
{47206}{47294}Možda bismo trebali zvati|generala Wheelera.
{47349}{47456}I reæi mu? Da je pukovnik Winter|izgubio nadzor nad svojim zatvorom?
{47578}{47618}Spreman si krenuti?
{47621}{47651}Da, gospodine!
{47721}{47775}Putanja æe biti bolja.
{47889}{47921}Gdje me želiš?
{47963}{48032}Ovo je poruènik McLaren|iz zatvora Fort Truman.
{48034}{48093}Mogu li govoriti s generalom Wheelerom?
{48118}{48229}Morat æeš ga probuditi.|Treba ga pukovnik Winter!
{48242}{48284}Ovdje imamo pobunu!
{48365}{48417}Idi. Lansiraj kada budeš spreman.
{48559}{48587}Upali je.
{48610}{48635}Vatra!
{48915}{48945}Gospodine?
{48971}{49034}Pukovnièe, on želi s vama razgovarati.
{49055}{49089}Tko?
{49103}{49131}On.
{49346}{49370}Da?
{49411}{49498}Pukovnièe,|preuzimam komandu nad vašim zatvorom.
{49560}{49606}Bogme ne.
{49702}{49800}Idemo, momci, idemo! Prestanite dangubiti,|nemamo puno vremena.
{49838}{49865}G. Dellwo.
{49870}{49896}Gospodine.
{49898}{49932}Kada smo spremni?
{49938}{49979}Samo trenutak.
{49986}{50036}Gospodine, možete li doæi ovamo?
{50219}{50252}Što je to?
{50266}{50323}Ta stvar sakrivena u prolazu?
{50361}{50390}Ne znam.
{50559}{50597}Pusti ih.
{51350}{51412}Kreni sa plavom i crvenom jedinicom.
{52061}{52121}Napuni jebenu stvar!
{52171}{52210}Diži je!
{52226}{52253}Pali!
{52351}{52393}Donesi mi pušku!
{52573}{52622}Napuni je. Spreman?
{52645}{52689}Pali!
{52769}{52808}Jebo te, upalilo je!
{52861}{52885}Pali!
{53173}{53206}G. Dellwo.
{53233}{53270}Idi tri metra naprijed.
{53272}{53302}Da, gospodine.
{53309}{53346}Tri metra naprijed!
{53484}{53612}Sredi onoga koji puni katapult.|Ne dozvoli mu da ga opet napuni.
{53616}{53663}Hoæete li uspjeti ovaj put?
{53667}{53703}Naravno, gospodine.
{53736}{53774}Onda je došlo vrijeme.
{53780}{53829}Pogodit æemo cilj, gospodine!
{53850}{53884}Ovo je ona prava!
{53923}{53962}Ovaj u sredini.
{54022}{54055}Hajde!
{54063}{54088}Pali!
{54630}{54661}Pali!
{54667}{54693}Gospodine!
{55103}{55136}Ubaci je!
{55441}{55482}Izbaci je!
{55521}{55561}Izbaèena je.
{55565}{55614}Nikada se ne zna s vatrom.
{55674}{55743}Rekao sam ti da æu ti vratiti, seronjo.
{55868}{55897}Gospodine?
{55955}{55993}Pazite na prozor.
{56265}{56312}Daj vodeni top, smjesta!
{56432}{56457}Duffy?
{56520}{56569}Samo još par minuta, gospodine.
{56578}{56621}Povucite se! Povucite se!
{57044}{57105}Duffy, što to radiš? Ugasi vodu!
{57183}{57232}Idite na komandno mjesto!
{57237}{57276}Idite! Idite!
{58059}{58092}Što radiš?
{58338}{58372}Naprijed!
{58405}{58436}Sranje!
{58881}{58929}Winter, jebena kukavice!
{58947}{58993}To je vaša privatna veza.
{58999}{59033}Odgovorite.
{59037}{59098}Vojni zatvor, ured pukovnika Wintera.
{59125}{59155}Da, gospodine.
{59191}{59231}To je general Wheeler.
{59285}{59355}Stižemo, pukovnièe.|Bit æemo tamo za 20 minuta.
{59381}{59422}Ne shvaæam.
{59424}{59475}Imate pobunu. Tražili ste pomoæ.
{59477}{59512}Ne, nisam...
{59589}{59665}Situacija je pod nadzorom, gospodine.
{59681}{59724}Upravo èistimo nered.
{59745}{59808}Drago mi je to èuti. Vidimo se za 20 minuta.
{59879}{59916}U redu, gospodine.
{60132}{60199}Svršimo s tim. Dajte helikoptere.
{60523}{60549}U redu.
{60906}{60941}Napuni vodeni top.
{61293}{61338}Požuri! Zakaèi taj lanac!
{61405}{61443}Gdje je jebena voda?
{61715}{61740}Sada.
{62245}{62277}Zakaèeni smo!
{62311}{62360}- Idi, Yatese!|- Pomozi mi!
{62446}{62498}Gospodine, mislim da je to Yates.
{62503}{62538}Da, znam!
{62693}{62728}Drži se!
{63231}{63261}Gdje je on?
{63496}{63528}Što radiš?
{64027}{64108}Izbaci tog momka. Mièi se, ja se penjem!
{64134}{64204}Ukloni ga. Zaustavi ga!
{64619}{64669}Jebeš gumene metke!
{65190}{65216}Hajde!
{66038}{66063}Hajde!
{66080}{66112}O, Bože!
{66190}{66255}- Nikada nisam uništio helikopter.|- Ne govori, mièi se!
{66257}{66301}Idi. Izlazi, idi!
{67299}{67339}Dobro si, Yatese?
{67366}{67400}Idemo.
{68165}{68218}- Spreman?|- Da.
{68252}{68281}U stroj!
{68292}{68378}Idemo, ljudi, u stroj! Brzo!
{68385}{68431}Idemo, vojnici, smjesta!
{68474}{68510}Idemo!
{68648}{68676}Nadesno!
{68708}{68736}Okrenite se!
{68903}{68934}Spremni...
{68963}{68996}naprijed!
{69036}{69069}Rukom naprijed!
{69343}{69390}Ljudi su okupljeni, gospodine.
{70632}{70705}Prvi i drugi vod, van.|Treæi i èetvrti vod, van.
{71669}{71747}Odobrio sam korištenje pravog streljiva.
{71764}{71861}Svaki zatvorenik koji se ne pokori mojim|zapovijedima bit æe ustrijeljen.
{72147}{72222}Svi zatvorenici na tlo, smjesta!
{72677}{72784}Još æu jednom dati tu zapovijed,|onda æu pucati na njih.
{72832}{72942}Ne želite to imati na savjesti, zar ne,|zatvorenièe Irwin?
{73099}{73171}Svi zatvorenici na tlo, odmah!
{73665}{73693}Èekaj.
{73876}{73928}Ne moramo se predati, borit æemo se.
{73930}{73999}Ne. Ovdje je kraj.
{74177}{74210}Lezite!
{74765}{74795}I ti, Yatese.
{74925}{74955}To je naredba.
{75505}{75531}Sada...
{75543}{75586}dajte mi moju zastavu.
{75708}{75758}To nije tvoja zastava.
{75976}{76030}Što radite, g. Irwin?
{76060}{76103}Izgubili ste!
{76115}{76203}Neæu vam to dopustiti!|Neæete podiæi zastavu naglavce!
{76240}{76297}Lezite ili æemo pucati u vas!
{76303}{76408}To je nareðenje!|Neæete podiæi zastavu naglavce!
{76440}{76500}Strijelci, otvorite vatru.
{76786}{76844}Strijelci, otvorite vatru.
{77048}{77105}Pucajte u tog èovjeka! To je nareðenje!
{77249}{77292}Što rade?
{77295}{77354}Što radite? Uèinite to. Otvorite vatru!
{77368}{77427}Ne dopustite mu da obešèasti tu zastavu!
{77435}{77494}Otvorite vatru!
{77635}{77670}Što rade?
{77688}{77738}McLaren, Niebolt, sa mnom!
{77740}{77789}Niebolt, ostani gdje si.
{77837}{77878}Ne suprotstavljaj mi se!
{77887}{77957}Zar ne vidiš kako on podriva|moju komandu?
{77997}{78073}Zar ne vidiš? Zar ne shvaæaš što on èini?
{78243}{78286}Odmakni se od zastave!
{78299}{78343}Odmakni se od zastave!
{78547}{78575}Pukovnièe!
{78599}{78656}Pukovnièe, spustite pištolj!
{78781}{78838}Molim vas, pukovnièe, spustite pištolj.
{79064}{79105}Gospodine, svršeno je.
{79139}{79186}Dajte mi ga.
{79457}{79507}Zatvorenici, ostanite na tlu.
{79551}{79575}Doktore!
{79633}{79679}McLarene, vrati ih u æelije!
{79681}{79738}Tim A, tim B, krenite!
{80001}{80041}Ruke iza glave!
{80217}{80269}Zatvorenici æe se vratiti u æelije.
{80353}{80387}Hvala.
{80485}{80543}Moram zaustaviti to krvarenje!
{80547}{80621}- Hitna pomoæ stiže.|- Moramo ga odvesti u bolnicu!
{80622}{82635}{C:$0000FF}{y:ib} B & M |{C:$FF0000}{y:b} movies 
{82642}{82697}Jedan je veliki general jednom rekao:
{82729}{82813}"Kažeš svojim ljudima:|'Vi ste vojnici. Ovo je naša zastava. '
{82857}{82921}"Kažeš im:|'Nitko ne smije uzeti našu zastavu. '
{82935}{83016}"Onda je podigneš visoko|kako bi je svi mogli vidjeti.
{83099}{83166}"Sada imaš svoj dvorac."
{83379}{83443}VOJNIK AJ BECK
{83485}{83549}AGUILAR - USMC
{83789}{83869}EUGENE R. IRWIN - VOJSKA SAD-a
