{4147}{4185}Ne, Ben!
{4185}{4229}Vrati kavez u auto, u kuæi je prehladno.
{4229}{4253}Gladan je.
{4253}{4320}Može prièekati pet minuta.
{4388}{4440}Možeš li pomoæi, Eva?
{4489}{4536}Sve je mokro, pazite gdje stavljate.
{4944}{4968}Gdje da spustim?
{4968}{5040}Nije bitno, svuda je mokro.
{5040}{5063}Ali... budite mirni.
{5160}{5207}Zatvori vrata.
{5400}{5447}Što vi radite ovdje?
{5472}{5519}I kako ste ušli?
{5663}{5686}Što hoæete?
{5711}{5735}Spustite pištolj, prvo.
{5735}{5782}Ostani tu, ili pucam!
{5926}{5974}Da li mislite da imate pravo biti ovdje?
{5974}{6021}I da uperite takvo oružje u nas?
{6094}{6141}Koliko dugo æeš stajati tako?|Prestani!
{6190}{6237}Drži ga.
{6357}{6405}Slušajte, možemo li sjesti i razgovarati?
{6525}{6573}Uvijek postoji naèin.
{6597}{6621}Idite odavde!
{6645}{6717}A gdje bi mi trebali ostati?
{6789}{6836}Kada æete otiæi?
{6836}{6908}Ovo je vaše, možete nam dati.
{6908}{6956}Zašto da vam dam?
{7028}{7076}Možete, ako hoæete.
{7100}{7172}Odakle ste? Koje je vaše rodno mjesto?
{7172}{7220}Posao?
{7268}{7292}Zašto ste otišli?
{7292}{7316}Nema vode.
{7388}{7412}Što æete uèiniti?
{7508}{7556}Pustite djecu.
{7604}{7628}OK?
{7670}{7718}Idite èekati u auto!
{7718}{7765}Eva, izvedi Bena!
{8179}{8227}Što vi želite uèiniti?
{8251}{8323}Pogledaj što je u torbama.
{8802}{8897}Predlažem vam da se vratite...
{8993}{9041}Ubio si ga, Fred...
{9137}{9161}Ubio si ga!
{9233}{9257}Tišina!
{9305}{9353}Prestani! Mièi se!
{9353}{9425}Bježi! Prestani!
{9545}{9569}Odlažite!
{9617}{9665}Ostavite me na miru, idite svojoj kuæi!
{10600}{10648}Otišli smo na odmor, ubili su mog muža!
{10720}{10792}Razumijete li što vam govorim??
{10839}{10887}Što sada...?
{10935}{11031}Našu kuæu na selu zauzeli su nepoznati ljudi!|Ubili su mog muža!
{11055}{11151}Oteli su nam auto, opljaèkali nas...
{11223}{11295}Stvarno mi je žao, žao mi je.
{11391}{11438}Trebate nam pomoæi.
{11486}{11534}Poznata vam je trenutna situacija.
{11558}{11606}Svašta se dogaða!
{11630}{11702}Zašto ste me došli uznemiravati, kad ste znali??
{11702}{11774}Jedino ovdje...|-Odvedite djecu odavde.
{11798}{11869}Idite, morate otiæi!
{12685}{12733}Gðo Ordnaire!
{12924}{12972}Znam da me èujete!
{17406}{17454}Vratit æu se!
{17502}{17574}Ostanite ovdje!
{17574}{17694}Idem naæi hranu i neke stvari.|Spavajte.
{17694}{17766}Budite oprezni, razumijete?
{18029}{18053}Brzo se vraæam.
{18125}{18221}Sada ste veliki, razumijete?
{18221}{18269}Vratit æu se brzo.
{18581}{18629}Ovdje spavajte.
{18749}{18821}Ne dolazite kod mene doma.|Gospoðo, moj muž æe znati.
{18845}{18917}Uglavnom, on èuva te stvari.
{18917}{19012}Primijetit æe da nedostaju.
{19036}{19060}Sretno!
{19540}{19636}Stani, ja æu probati!
{19756}{19804}Zaustavi ga, brzo!
{19804}{19900}Ti mi reci kako! Probaj!
{19900}{19947}Ne želim da odleti!
{20019}{20043}Sad!
{20186}{20234}Pazi, pobjeæi æe!
{20234}{20282}Znam, pažljivo!
{20402}{20450}Stani!
{20450}{20522}Uhvati ga, brzo!
{20570}{20618}Prestani!
{20618}{20666}Uplašit æeš ga!
{20690}{20786}Evo, polako... sranje!
{20810}{20834}Što se dogodilo?
{20906}{20954}Lezi ovdje i ne mièi se!
{21049}{21097}To je nova maramica!
{21169}{21241}Pokrij usta!
{21361}{21433}Samo nježno, pokrij.
{21553}{21601}Ostani ovdje, ja æu ga uhvatiti.
{21649}{21673}Vjeruj mi.
{21769}{21817}Polako.
{21913}{21961}Sigurno nas ne voli! Evo!
{21984}{22032}Pogledaj, drži nježno.
{22176}{22200}Uzmi.
{22344}{22392}Spavaj, sada.
{28552}{28624}Mama! Mama, probudi se!
{28624}{28672}Mama! -Što je bilo?|-Ben, nestao je!
{28672}{28744}Što! -Pobjegao je! Što to govoriš?
{28744}{28840}Žao mi je, nisam ga èuvala!|Mislila sam da spava!
{29726}{29750}Ben!
{30157}{30277}Idemo natrag, da ga naðemo, pažljivo!
{30301}{30349}Pazi da se ne opeèeš. -Pazim.
{30397}{30445}Ben! Gdje si?
{30517}{30565}Sigurno je otišao van!
{30565}{30637}Ovdje je mraèno.
{30637}{30685}Spusti vatru na zemlju.
{30877}{30949}Dodaj travu, potražit æemo ga.
{31188}{31260}Ovako nema smisla da tražimo.
{31260}{31332}Ti vodi raèuna o vatri.  -Dobro.
{31332}{31452}Ostani ovdje!|Kada se vratim, da te naðem ovdje, u redu?
{31452}{31572}Ili mi neæemo moæi njega naæi,|a ni on nas, razumiješ?
{31644}{31716}Razumiješ?|Ben!
{31835}{31883}Ne brini, naæi æemo ga!
{31955}{32027}Majko, bojim se!
{32027}{32099}I ja sam uplašena, naæi æemo ga!
{32099}{32146}Naæi æu ga i dovesti.
{32218}{32290}Ti moraš ostati ovdje!
{32506}{32602}Idem sada, i vratit æu se!
{32746}{32890}Volim te, nemoj iæi!
{33633}{33681}Ben! Èuješ li me?
{33705}{33801}Doði ovdje, ako vidiš vatru!
{34616}{34664}Ben! Èuješ li me? |Odgovori mi, ako me èuješ!
{35214}{35382}Ima li koga? Ima li koga?
{36150}{36197}Past æe kuæa!
{36221}{36341}Rekla sam ti da budeš pažljiva!|Zašto nisi vodila raèuna?
{36341}{36389}Zašto si otišla?
{36389}{36461}Ne znam kako je nastao požar! Ne znam!
{36485}{36581}Eva! Eva! Nemoj trèati! Stani!
{36701}{36797}To je moja greška! Nisam te trebala ostaviti s vatrom!
{36797}{36869}Trebala sam ostati ovdje!
{37492}{37540}Ben!
{37612}{37731}Ostanite tu!|-Dobro.
{37731}{37851}Ne prilazite! -Dobro, dobro!
{37875}{37947}Molim te, pusti ga, nije ti ništa uèinio!
{38019}{38139}Znaš što je jako èudno? |Što radi ovdje u sred noæi?
{38187}{38258}Odakle si? Molim te, pusti ga.
{38258}{38378}Zašto si ga uhvatio?
{38450}{38546}Hvala! Doði ovdje, brzo! |Kuda ideš?
{38642}{38810}Što si radio? Gdje si bio?
{38858}{38906}Ne smiješ negdje iæi bez našeg znanja.
{38954}{39002}Obeæaj mi.
{39170}{39217}Hoæeš li ostati ovdje?
{39289}{39313}Doði ovdje.
{39409}{39457}Gdje si ga vidio, Ben?
{39649}{39697}Zar ne želiš razgovarati sa mnom?
{39745}{39841}Što nije u redu? Jesi li bolestan?
{39913}{40033}Mogu li pogledati? Mogu ti pomoæi.
{40057}{40105}Što radiš ovdje? Reci mi!
{40129}{40248}Što radiš ovdje, u mraku? Ostajemo ovdje.
{40272}{40344}Da li ti je hladno? Da li si bolestan? |Mama, vjerojatno je bolestan.
{40392}{40512}Gdje te boli? Što se dogodilo?
{40536}{40583}Što se dogodilo?
{40631}{40703}Mama, umoran je, ne pitaj ga.
{40751}{40799}Imaš li što za piti?
{40871}{41015}Možemo ti dati malo.|-Dati mi što?
{41135}{41183}Kako se zoveš?
{41278}{41350}Ja nisam dobar, nema smisla da budete fini|prema meni.
{41422}{41446}Zašto?
{41518}{41542}Ne postoji ništa dobro.
{41590}{41638}Da li uvijek misliš tako?
{41662}{41710}To što govoriš...
{41710}{41782}Teško mi je razumjeti.
{42166}{42214}Odakle si?
{42405}{42429}Zašto želiš znati?
{42453}{42525}Ako ti želiš pomoæi, moraš mi reæi nešto.
{42717}{42885}Jeste li dužni?|Jeste li došli ovdje zbog dugova?
{42981}{43005}Zašto to misliš?
{43053}{43149}Bicikl nije dovoljan.|-Što?
{43292}{43364}Došli ste ovdje biciklom?  -Da.
{43412}{43507}Daleko? -Tri sata.
{43627}{43747}Kao da nemate mjesto za ostati.
{43771}{43867}Nitko vas neæe pustiti.
{45018}{45090}Nije èisto. -Nije važno.
{45186}{45258}Sigurno ima muha kada je mrtva, veæ truli.
{45258}{45329}Kao da je pastir sam...
{45473}{45545}To je pas. -Kakav pas?
{45545}{45593}Kakav pas! Kakav pas! Pas!
{45617}{45689}Nije bilo hrane, mrtav je, to je normalno!
{45713}{45833}To se stalno dogaða.|-Prvi put vidim.
{45905}{45929}Sranje!
{45929}{46049}Prošla su tri dana, jadnik!
{46169}{46217}Idemo odavde, brzo!
{46455}{46527}Što radiš? - Dolazi ovamo, Eva.
{46551}{46623}To odijelo je dobro!
{46647}{46767}Nije ga lako uzeti.|Misliš li da mogu biti kriv?
{46767}{46839}Ima i kratkih dijelova.
{47438}{47462}Dolazi!
{47510}{47534}Zar ti ne treba?
{48302}{48349}Stanite! Stanite!
{48613}{48709}Stanite! Molim vas!
{48709}{48829}Molim vas, stanite!
{48901}{48973}Hej! Prièekajte nas!!
{48997}{49117}Povedite me!
{50531}{50577}Dobar dan.
{50627}{50723}Hajde, idemo, nije važno ima li koga.
{51418}{51440}Bok.
{52904}{53000}Ja sam Anna Loren.|Ovo su moja djeca, Eva i Ben.
{53000}{53046}Dolazimo iz grada.
{53192}{53262}Drugi ljudi? Ne razumijem vas.
{53407}{53503}Tu smo samo mi, nema drugih ljudi, nikoga.
{53647}{53719}Nema nikoga drugog.|Oni ne shvaæaju.
{53719}{53765}Znam, ne govori!
{53935}{53957}Ovdje je jako hladno.
{54319}{54365}Mogu li upaliti vatru?
{55109}{55179}Da li ste ikada vidjeli vlak ovdje?
{55229}{55349}Vlak! Van.
{55373}{55443}Jeste li vidjeli da lake staje ovdje?
{56499}{56547}Bok.
{56547}{56619}Odakle ste?
{56619}{56667}Iz grada.
{56667}{56763}Ja sam Anna Loren.|Ovo su moja deca, Eva i Ben.
{56835}{56931}Oprostite, moja žena i dete.
{56931}{56977}Što radite ovdje?
{57315}{57385}Što ovaj, s uvjetnom rukom, radi ovdje?
{57410}{57457}Da li si ukrao nešto moje?
{57506}{57602}Ne izmišljm, imam dokaze.
{57602}{57674}Ako si ukrao našu hranu,|bolje je da odmah vratiš.
{57674}{57722}U stvari, što on može uzeti od tebe?
{57722}{57794}Ne postoji ništa tvoje.
{57794}{57866}Samo zato jer imaš pištolj?
{57866}{57914}Time impresioniraš ostale, zar ne?
{57914}{57960}Ne govori tako.
{58009}{58081}Brzo tvoju torbu.
{58081}{58127}Ovdje ima puno ljudi.
{58201}{58271}Ostavi deèaka na miru!|Bolje bi bilo ba se ne miješaš.
{58321}{58369}Prije tebe i tvoje obitelji,|ovdje je bilo poštovanja.
{58369}{58488}U ovako lošim uvjetima, ti i tvoja obitelj|bi bili sretni.
{58488}{58536}Nije civilizirano tako govoriti.
{58536}{58632}Zbog tebe smo izgubili osjeæaj civilizacije|kada si došao, razumiješ?
{58632}{58728}Ako ti se ne sviða, povedi djecu i ženu| i idite odavde!
{58800}{58848}Možeš li umiriti djecu?
{58848}{58870}Možeš li ih kriviti?
{58896}{58992}Kome ti govoriš? Misliš da si vlasnik ovog?
{58992}{59038}Barabo.
{59064}{59184}Eva... Eva
{59184}{59232}Molim te, mama, pusti me.
{59232}{59328}Vrati se! |Ne mora se ni vraæati!
{59376}{59519}Gospodine, molim vas, ja æu razgovarati s njim.
{59831}{59951}Mama, molim te... vratit æu se.
{60454}{60550}Sigurno nisi ništa uzeo?  Ne!
{60550}{60620}Ja æu govoriti s njima. -Neka umru!
{60646}{60742}Vratit æeš se, zar ne? Idem sada.
{60742}{60788}-Ne ulazi ovdje!  -Ali, boli te ruka.
{60910}{60955}Boli?
{60981}{61029}Neæeš mi reæi kako si to dobio?
{61029}{61075}-Što misliš, tko si ti?
{61149}{61245}Jesi li se borio? S ikim?
{61269}{61365}Ne želiš reæi?  -Ne.
{61484}{61604}Molim te, ne idi.
{61652}{61748}Naviknuo sam biti sam.|Nije isto.
{61748}{61818}Zaboravi... vidimo se kasnije.
{61964}{62036}Da li znaš što je to?
{62036}{62108}Te stvari unutra.  -Kako da kažem...
{62108}{62156}S tim se pali vatra.
{62156}{62226}Možeš li drugaèije zapaliti?
{62276}{62372}Daj im! Daj!
{62396}{62442}Trebaš se vratiti.
{62467}{62514}Nemam što za reæi.
{62923}{62969}Možda moraš odluèiti da ostaneš.
{63019}{63067}Živim u blizini.
{63067}{63113}Smiješno je da to kažeš.
{63379}{63427}Ostavi ga, što mi možemo?
{63427}{63451}Kako? Veæ je otišao.
{63451}{63521}Trebaš ga pozvati natrag.|On treba slušati.
{63546}{63592}Zar me neæete tuæi ponovno?
{64073}{64119}Ne bih to tako rekao tebi.
{64385}{64431}Imaš li cigaretu?
{64720}{64766}Naravno.
{64984}{65032}Ali ne previše.
{65032}{65152}Osim mene, ovdje nitko ne puši.|Nitko neæe tražiti cigaretu.
{65655}{65725}Da li dolazite iz grada? Zar ne?
{65751}{65797}Koje podruèje? 12.
{65871}{65967}Da li ste dugo ovdje? - Ne, samo 6 dana.
{65967}{66087}Ostali? Nitko ne govori, niti zna.
{66087}{66183}Ne sviðaju mi se ovi ljudi.|Kažu da je vlak prošao prije deset dana.
{66231}{66255}Da li je stao?
{66255}{66325}Ako stane, ja ne ostajem ovdje.
{66447}{66590}Možete me zvati Bea.|-Ja sam Anna. -Znam.
{66710}{66805}Imate? -Hvala.
{67333}{67429}Imate li neke stvari za zamijeniti? -Što?
{67453}{67525}-Ovisi, ne znam što žele.
{67525}{67571}Imam ogrlicu.
{67596}{67642}To je dobro.
{67692}{67788}Bilo što dobro, da nije slomljeno? Sat?
{67788}{67834}Uzmi za sebe.
{67908}{67978}Ti? -Ja?
{68028}{68100}Ovaj? U redu.
{68100}{68146}Može se prodati drugima.
{68196}{68242}Da li mislite da je pravda lokalna?
{68268}{68292}-Što lokalno?
{68292}{68364}Znam da je teško potpuno razumjeti nekoga|iako ste s osobom partner...
{68364}{68436}Ali se uglavnom zna, više ili manje.
{68436}{68484}Možda je to pravda, lokalno vlasništvo.
{68484}{68554}Na kraju, to se podrazumijeva, zar ne?
{68579}{68649}-Ali, što mislite pod pravdom?
{68675}{68747}-Poznajem jednog..
{68747}{68819}Fred, moj prijatelj, on je lokalni..
{68819}{68915}Drugi ne poznaju njegove najèudnije dijelove,|barem pored mene.
{68963}{69011}Ima 36 godina...
{69011}{69083}roðen na Zemlji, imao je 36 do sada.
{69083}{69155}On je podrška mojoj egzistenciji.
{69155}{69201}Božja ruka æe nas dodirnuti, ako je on meðu nama.
{69227}{69323}Ako on želi slomiti nekoga od nas...|onda je gotovo.
{69347}{69417}Zaista? -Da.
{69467}{69562}Nismo osigurali jedni druge na puno naèina.
{69610}{69681}Imamo samo lokalnu vezu.
{69681}{69729}Nije trenutak da se ljutiš.
{69729}{69777}Koliko je? -Nije sigurno.
{69777}{69799}Žao mi je.
{69921}{69969}Eva, što se dogodilo?
{69969}{70017}Vidjela sam kako se svaðaju zbog vode.
{70017}{70041}Nismo detaljno razmotrili problem vode.
{70041}{70113}Slušajte me, svi, zapravo je jednostavno.
{70113}{70209}Ako želite iæi, morate prièekati|vlak u kojem ima mjesta.
{70233}{70329}Ako idete svojom voljom, dobit æete dio.
{70353}{70473}Slušajte, svi!  Slušajte, pažljivo!
{70568}{70640}Stvari æe imati mjesto, ali prvo moramo odrediti rutu.
{70640}{70712}Što želite da radimo?|Ima nas 14, ukljuèujuæi mene.
{70712}{70760}Vlak vani ne može iæi bez stroja.
{70760}{70808}Pokušavam da svi budu zadovoljni.
{70808}{70880}Ali samo vi znate vrijednost trenutnog materijala.
{70880}{70904}To su javne stvari.
{70904}{71000}Vi odluèite, ne prebacujte problem na mene.
{71000}{71072}Treba nam osoba koja se odvaja.
{71072}{71144}Zašto uvijek radite problem?
{71144}{71240}Nitko nije pozvao vas i vašeg muža ovdje,|niste dobrodošli.
{71240}{71336}Mislite da smo htjeli doæi?|Samo zbog vlaka vani!
{71336}{71408}Stavite nas u sobu punu barbara.
{71408}{71432}Ne diraj me!
{71432}{71504}Misliš da ne znam da voliš kontrolirati druge?
{71504}{71599}Nareðivati drugima cijeli dan!|Drugi æe te rado doèekati?
{71599}{71671}Ovo je selo, ne grad.|Ako ti se ne sviða, vrati se!
{71671}{71719}Ne želim kontrolirati... Mir!
{71719}{71815}Žao mi je...|Molim vas, slušajte o situaciji.
{71959}{72029}Trenutna situacija je van kontrole.
{72103}{72199}Malo... Zbog toga što je izvor obnove jug...
{72271}{72317}Ima ih sve manje i manje...
{72391}{72487}Sve je više gladnih...|Sve više štete...
{72773}{72869}Brojni su razlozi doveli do nestašice hrane.
{72893}{72939}Vode u još goru glad...
{73181}{73227}Izgleda da moja navika da štedim nije od koristi.
{73253}{73275}-Samo to?
{73301}{73349}Sigurno se šalite?
{73349}{73445}Stalno tako. Kako je moguæe da nema nikakvih vijesti|o trenutnoj situaciji?
{73445}{73469}To što govoriš samo me svaki put razoèara!
{73469}{73517}Probao sam vam pomoæi i ponoviti veæinu.
{73517}{73565}Ako to nije ono što želite, ne krivite mene.
{73565}{73611}Prestanite! Svaða sve govori!
{73636}{73684}Ne mislite na druge u istoj situaciji?
{73684}{73804}Moj muž se trudi da vam prenese najvažnije.
{73804}{73852}A dobiva samo podsmijeh!
{73852}{73900}Odluèite, ostajete ili idete?
{73900}{73996}Pogledaj kako je iznervirana, moj muž|æe zauzeti mjesto.
{73996}{74020}Slušajte njene primjedbe, ili odluèite odmah!
{74020}{74116}Zanima me samo kuda idemo.|Ne mogu gubiti vrijeme.
{74140}{74212}Nemate nimalo osjeæaja? -Osjeæaja?
{74212}{74260}Kako to da vi govorite o osjeæaju! Sjajno!
{74260}{74332}Vaši osjeæaji su pod suncem i èine da dobro mirišete?
{74332}{74402}Kako to govoriš o osjeæaju?|Bolje ga pokaži.
{74548}{74643}Prestani! Uzalud govoriš!|Kako se možeš moliti?
{74763}{74809}Dosta je bilo!
{74907}{74929}-Hvala.
{75051}{75099}Oprostite, uznemirena sam.
{75099}{75195}-U redu je, razumijem.
{75578}{75697}Njen muž radi kao idiot, a ona se smije cijelo vrijeme!
{75697}{75745}Gospoða Azoulay ima takvog muža...
{75745}{75793}A vi hoæete da taj smijeh prestane?
{75793}{75889}I još više, kada se svaða i vozi bicikl, on |izgleda kao žena.
{75889}{75985}Vi ste me probudili, hvala vam, hvala puno.
{76009}{76081}Zausta? Primijetili ste?
{76081}{76153}Vaš šamar je bio dovoljan.
{76153}{76225}Ali, zašto ne udarite nju, g. Koslowski?
{76225}{76295}Takav idiotizam ne smije biti javan.
{76321}{76391}Ako je ne probudite, samo je pustite da ponovno radi onakve stvari.
{76441}{76487}Kako to da ste sigurni?
{76585}{76607}To je iskustvo.
{76633}{76703}Dosta! Molim vas, ne govorite više!
{76728}{76824}Ne govorite više, molim vas!
{76848}{76918}Zbog djece, neka nitko ne govori!
{76992}{77040}Trebao si otiæi.
{77040}{77112}Rezultat je savršen.|Svi komentari su umjesni.
{77112}{77158}Ali ja se sramim vas.
{77208}{77278}Doði... idemo.
{82337}{82383}Jesi li primijetio da nije lajao?
{82505}{82551}Ne.
{82577}{82673}Bili su u gradu zbog kraðe.|Umorni su.
{82697}{82744}I nitko nije primijetio.
{82744}{82791}Sve je ukradeno.
{82816}{82888}Ali ne mogu živjeti na farmi.
{82888}{82934}Sve je napušteno.
{82960}{83030}Teško je vratiti samopouzdanje.
{83128}{83150}Osim mene.
{83200}{83246}Zašto ti...? -Jer sam budala.
{83320}{83368}Moje ponašanje me izdalo.
{83368}{83414}Ostao sam samo ja.
{83464}{83510}Ta djeca me uvijek prate.
{83536}{83606}Smiju mi se, promatraju me kao igraèku.
{83704}{83799}Zašto? -Zašto? Ludi su.
{83799}{83845}Samo ja nisam ništa u njihovim oèima.
{83943}{84063}Nisam pravi prijatelj.|Samo igra.
{84135}{84230}Zajedno s tobom, bojim se.
{84230}{84326}Oni æe reæi da je tvoj prijatelj ništa s psom...
{84446}{84516}Gdje je sada? Otjeran od mene.
{84542}{84588}Samo neka ne bude šala na moj raèun.
{85093}{85139}Što radiš?
{85285}{85381}Tražiš nešto? Da, neke male stvari.
{85549}{85619}Može li svijetliti? -Da.
{85669}{85788}Idemo? Ne?
{85860}{85956}Bok! Ja idem natrag.
{86004}{86074}Kako ti nije hladno? -Navikao sam.
{86100}{86196}Ne znam da li mogu doæi sutra.
{86196}{86268}Ako dolazim, probat æu donijeti hranu.
{86268}{86388}Moja majka ima ogrlicu i sat.|Treba nabaviti hranu.
{86412}{86532}To je vrijedno u gradu.|Kako hoæeš.
{86939}{86985}Eva.
{87130}{87152}Uzmi.
{87538}{87584}25 litara najviše.
{87610}{87682}Mogu li dobiti malo vode, molim vas?
{87682}{87754}Ako mi vi ne pomognete, nitko ne može.
{87754}{87800}Muž mi nije odavde, ne poznaje nikoga.
{87825}{87897}Nemamo gdje živjeti, sin je bolestan ponovno.
{87897}{87945}Preklinjem vas.
{87945}{88017}Molim vas, nemamo što dati.
{88017}{88113}Imamo samo odjeæu, molim vas.
{88113}{88161}Ne gubi vrijeme.
{88161}{88231}Nemam ništa, san je bolestan, molim vas.
{88281}{88377}Ja mogu uèiniti sve što vi želite,|vi možete što god želite.
{88377}{88423}Zaboravi, ne radi probleme.
{88449}{88521}Mi æemo vam pomoæi, u redu?
{88521}{88569}Kasnije prièajte. Nema koristi.
{88569}{88641}Nema smisla!
{88641}{88711}Ako mi date malo vode, ja æu uèiniti bilo što|za vas!
{88737}{88783}Ostavite malo vode, molim vas!
{88856}{88928}Preklinjem vas!|Možete se odmah ševiti sa mnom!
{88928}{88974}Koliko, za litru vode?
{89000}{89072}Izgleda kao bogat èovjek, koliko imaš?
{89072}{89168}Mi nemamo ništa, samo èekamo vlak!
{89168}{89216}Onda umukni!
{89216}{89262}Molim vas!
{89288}{89334}-Ja vam mogu dati bicikl.
{89384}{89430}Ne treba mi sada.
{89456}{89502}-Sat?
{89576}{89672}Lijepo, zašto ga odmah ne daš svom prijatelju?
{89672}{89718}Hvala, možda si lord.
{89744}{89839}To je sve, ima još mušterija!
{90366}{90388}Dragi oèe...
{90414}{90460}Upravo sam našla olovku i papir,
{90486}{90532}i moram ti pisati.
{90582}{90678}Ovdje se puno stvari dogodilo.|Netko može biti ogranièen.
{90726}{90822}Ne znam da li æeš moæi èuti ili proèitati ovo...
{90822}{90892}Da li možeš osjetiti koliko te volimo.
{90917}{91037}Duboko vjerujem u to, i pokušavam,|jednostavno je...
{91061}{91133}Najdraži oèe...
{91133}{91229}Tako je teško naæi ljude koji vole jedni druge..
{91229}{91275}Nemoguæe je naæi dobro...
{91301}{91347}Gušim se...
{91373}{91469}Možda æeš pitati zašto ne kažem mami ili Benu?
{91469}{91613}To je nemoguæe.|Da si ovdje, znao bi.
{91637}{91733}S mamom, preplašena je...
{91733}{91779}Ja ne znam što da radim.
{91805}{91875}Ne mogu podnijeti, nadam se da je situacija promijenjena.
{91924}{92044}Mali Ben nije Ben kojeg si razumio...
{92068}{92114}Poznavala sam djeèaka...
{92140}{92186}Samo s njim sam imala o èemu razgovarati.
{92212}{92308}Ali te prièe nisu bile zabavne.
{92308}{92354}Mislim da nije važno.
{92380}{92476}Kada bi mama znala, bilo bi joj teško.
{92524}{92570}Nekad mislim da je sve pomiješano.
{92596}{92692}Ali je stvarno, zato ti pišem.
{92716}{92812}Jer kada se zbrka prebaci na papir, bude jasnije.
{92859}{92907}Mogu reæi samo da je ovo sažetak.
{92907}{92976}I u trenutnoj situaciji, moraš se zamisliti.
{93098}{93170}Ustajemo rano svakog jutra.
{93170}{93242}Samo zbog toga što netko ovdje rano ustane,
{93242}{93288}probudi ostale.
{93314}{93384}Onda ponavljamo isti posao...
{93865}{94033}Arina! Dijete æe umrijeti!
{98611}{98683}Odakle si? -To nije tvoja stvar!
{98683}{98778}Pažljivo s mojim stvarima!
{99329}{99400}Èije je ovo? Pažljivo.
{99545}{99641}Vrijeme je isteklo, svi spavaju na cementnom podu privremeno.
{99641}{99761}Zato što je grad previše star.|Cementni pod...
{99761}{99833}Bok, oprostite, da li je vaše?
{99833}{99929}Ako je, molim vas, odnesite ga na kratko.|To je naše mjesto.
{99929}{100000}Kako? Ne budi previše glasni, odnesite, u redu?
{100000}{100048}Nitko neæe prouèavati èije je to mjesto.
{100048}{100168}Broj konja je ogranièen, za sada|imamo samo 33.
{100168}{100215}Možete jesti meso sutra poslijepodne.
{100288}{100360}Oprosti, u èemu je problem?
{100360}{100456}Želim znati što oni rade?|Zašto ne znaš?
{100456}{100504}Zar oni ne èekaju vlak? Koji vlak?
{100504}{100600}Što, za ime svijeta, oni rade?|Promatraj malo, tada æeš znati.
{100624}{100647}Oprostite.
{100720}{100792}Voda za 37 dolara po baèvi, nosite ovako?
{100792}{100839}Znam da je vaše, kako? Što je bilo?
{100864}{100912}Ništa, oni su samo uzeli baèvu s vodom od njega.
{100912}{100983}Ti si glavni ovdje? Svi su glavni ovdje.
{101031}{101078}Da li misliš da je nevjerojatno?
{101103}{101175}Zatvori vrata, ozbiljno je...
{101175}{101247}Ovi ljudi nisu fini, zar ne? Da.
{101247}{101294}U pravu si.
{101367}{101439}Da li imaš vijesti o onom djeèaku?
{101439}{101535}Da li si ga vidio? Oprostite...
{101702}{101822}Oprosti, mislim da je bolje da približimo vatru.|Vlak možda naiðe.
{101870}{101917}Mislim da je prtljaga u putanji vlaka.
{101966}{102013}Opasno je.
{102037}{102109}Zapalili smo veæu vatru na putanji vlaka.
{102109}{102156}Pa, vlak æe stati ranije jednom, vidiš.
{102181}{102204}Hm, vatra...
{102301}{102421}Kakva je? Kakva je?
{102565}{102588}Velika buka.
{102637}{102708}Vrlo je oštra.
{102877}{102924}Doði, ti, probaj.
{103044}{103092}Upravo ti!
{103092}{103163}Gluh? To je tvoje ime?
{103236}{103308}O! Pusti me da jedem!
{103308}{103404}Više bih volio gledati!
{103404}{103500}Nemoj mi reæi da još nisi spreman.
{103500}{103548}Mlad èovjek treba biti spreman na svakakve stvari.
{103548}{103595}Hajde, u redu?
{103644}{103692}Rekao sam, tvoj bicikl,
{103692}{103739}ili æe otjerati ljude u smrt.
{103764}{103811}Da li si dobro?
{104195}{104242}Ništa.
{105105}{105201}Molim vas, napravite mlijeko.
{105321}{105368}Da li možete pomoæi?
{105489}{105536}Što! Maštanje!
{105585}{105633}O, tko?
{105633}{105729}Kome da pomognem? Da li je plemenito pomagati drugima?
{105729}{105825}Kuèka prièa cijeli dan: ona je bolesna, neæe biti fina.
{105825}{105873}Da li bi više dao starijem èovjeku...
{105873}{105944}Dovraga! Poslije piæa, idemo van na nuždu!
{105969}{106040}Da li misliš da ne trebamo jesti, ustajemo rano i idemo kuæi kasno.
{106328}{106424}Da li znaš koliko je mlijeko? Kako bi ispao...
{106520}{106543}Nemoj iæi.
{106664}{106711}Kuèkin sine!
{106736}{106807}Kuèko!
{108917}{109013}Stani, hvala.
{109085}{109131}Zašto ljudi ne mogu raditi dobre stvari?
{109276}{109347}Èovjeèe, ne razmišljaj o tome.
{113470}{113541}Gdje si išao? Ostavi me na miru.
{113614}{113685}Zajedno s ovim ljudima, da li možeš podnijeti?
{113710}{113733}Ako da, to je naprosto živa smrt.
{113854}{113901}Gledaj one ovce, oni umiru.
{113950}{113997}Neæe, ako ima vode.
{114070}{114142}Ne budi tako hladnokrvan.
{114142}{114189}Djeca koja su ovdje su još uvijek mlada.
{114189}{114237}Njima jako treba voda, da li znaš gdje se nalazi voda?
{114237}{114260}Ako ti...
{114429}{114476}Pomakni se malo.
{115196}{115219}Mama!
{115292}{115340}Opeèen sam, nikada nisam vidio ženu.
{115340}{115412}Ne, istina je! Ubojstvo!
{115412}{115484}Pitaj djecu! Oni neæe lagati!
{115484}{115532}Nije realno! Nikada ih ne viðam.
{115532}{115604}Ako mi ne vjeruješ, pitaj moju ženu.|Ako mi ne vjeruješ...
{115604}{115676}Daj mi mog muža! Stani!
{115676}{115748}Ubojstvo! Kuèkin sine!
{115748}{115819}Odlazi! Stani!
{115868}{115915}Gospoðo! Smirite se!
{116203}{116250}Slušaj, nikada nisam vidio ženu u životu.
{116250}{116322}Oèigledno je zašto su ubili njenog muža!
{116322}{116370}Svi ljudi znaju da sam ja dobra osoba.
{116370}{116466}Što se dogodilo? Gospoða je rekla,|ova osoba je ubila njenog muža.
{116466}{116537}Vašeg? Besmislica!
{116610}{116658}Što se dogodilo?
{116658}{116705}Rekla je da se to dogodilo kada su se vratili na odmor na vikend.
{116730}{116850}Koji vikend? Nekoliko dana ranije
{116898}{116945}Pitaj kuèkinog sina.
{116970}{117018}Pitaj ga zašto je to uèinio.
{117018}{117089}Nemoguæe! Bili su u gradu.
{117114}{117161}Moja žena i ja smo daleko odatle.
{117186}{117281}Da li imate neki dokaz? Moj muž je mrtav, mrtav.
{117281}{117352}Vi znate da to nije dokaz, ali ovo...
{117377}{117449}Možete pitati djecu, mrtav, stvarno.
{117449}{117520}Oprostite, ako nemate dokaze, ne možemo vam pomoæi.
{117689}{117760}Probajte se smiriti, uvijek postoji naèin.
{118408}{118456}Donesite konopac, uplašite konja.
{118456}{118527}Uðite brzo unutra, ili æe vam postati hladno.
{118648}{118671}Brzo, hajde.
{118744}{118791}Ben! Gdje je Benny?
{118936}{119032}Ben! Benny!
{119128}{119198}Ben! Benny!
{120397}{120445}Zamisli moju situaciju.
{120445}{120492}Vi govorite jedni protiv drugih.
{120517}{120565}Nemate dokaza, pa tako ni oni.
{120565}{120637}Èiju ideju da poslušam?
{120637}{120709}Izvjesno, nisam sudac.
{120709}{120805}Ovdje, svatko je moj partner, to je fer.
{120925}{120948}Oprosti.
{121141}{121237}Hm, sam život nije fer.
{121237}{121308}Samo za život.
{121308}{121380}Sam sam vidio takve stvari veæ nekoliko puta.
{121380}{121452}U takom malom mjestu, to se skoro dogaða stalno.
{121452}{121548}Niste mi puno rekli.
{121572}{121692}Zašto mi vjerujete?
{121692}{121764}Imam kompletno iskustvo.
{121764}{121884}Svuda je tako.|Vidjet æeš istinu na prvi pogled.
{121884}{121932}Ljudi su ludi.
{121932}{122028}Bez obzira bio dan ili noæ,
{122052}{122147}nikada ne vidim takve stvari sa simpatijom.
{122171}{122267}Kraða svuda, sve je pomiješano.
{122290}{122362}Isto kao "Deset zapovijedi".
{122362}{122434}Ljudi èak žrtvuju luðake.
{122434}{122530}Ovo bi trebalo biti manje fer nego vaše...
{122554}{122650}Samo rijeè, ako nemate dokaza.
{122698}{122746}Bolje se smirite i prekinite.
{122746}{122794}To je dobro za vas.
{122794}{122866}Ako me razumijete, to  je bolje.
{122866}{122962}Oni koji su uvijek koristoljubivi, dobit æe zasluženu kaznu.
{122986}{123082}To je fer.
{123082}{123153}Od trideset šeste godine, ja uvijek tako razmišljam.
{123537}{123608}Oprostite, u èemu je problem?
{123681}{123752}Da li želiš? Ne, hvala.
{123777}{123969}Onda? Želim znati da li se na tvom videu može pustiti glazba?
{124017}{124088}Naravno, doði.
{124113}{124160}Pomozi mi da podignem.
{124280}{124327}Vrlo mi je drago da voliš glazbu.
{124376}{124423}Daj mi.
{124448}{124544}Vrlo mi je drago što uvijek nosim svoju vrpcu,
{124544}{124615}bez obzira kuda idem.
{124664}{124784}Da li stvarno voliš glazbu? Da, naravno.
{124784}{124855}Ali motaj vrpcu na ovu stranu,
{124880}{124927}ako želiš slušati, moraš se pripremiti, u redu?
{128570}{128617}Georges, ovdje.
{128954}{129026}Što? Što to radiš?
{129026}{129098}Što želiš? Prekini!
{129098}{129146}Izaði, sada! Želiš li pobiti sve ljude?
{129146}{129242}Što? Što se dogodilo?
{129242}{129361}Prekini! Ne trebaš biti tako nametljiv.|Zar ne vidiš svojim oèima?
{129361}{129433}Idemo! Idemo! Ne vuci me!
{129433}{129504}Da li si ti skroz lud? Zar ne vidiš?
{129553}{129601}Moraš ušutjeti!
{129601}{129649}Pogledajte sebe i svog muža, kao nositelj robe.
{129649}{129721}Vas dvoje stranaca ne donosite ništa,
{129721}{129793}samo bolest, brbljanje, lopovluk.
{129793}{129865}Ne poèinje se od danas.
{129865}{129913}Ne ogovaraj nas!
{129913}{129961}Upoznat sam sa zemljom.
{129961}{130057}Vas dvojica pacijenata ste zarazili nekoliko farmera.
{130057}{130153}Nije istina! Kunem se, ustvari oni su ih ubili.
{130153}{130249}U redu! Donosimo suðenje prvo! Kuèko! Doði!
{130249}{130321}Ne prebacuj sve na nas.
{130321}{130345}Priznaj ako si to nekad uèinio...
{130345}{130415}Zašto se svaðaš! Što zeliš raditi ujutro?
{130464}{130560}Veèeras, oni su ukrali vodu.
{130560}{130632}Netko je vidio.
{130632}{130728}Ne mogu podnijeti da netko krade naše stvari.|Nikada!
{130752}{130847}Pretukli su mog muža iz osvete.
{130847}{130918}Možda su jako gladni!
{130943}{130991}Prièat æemo o tome ujutro.
{130991}{131087}Želiš li pucati u njega, sada?|-Što misliš, gdje je?
{131087}{131183}Ne zanima me.|-Ostavi negdje, ili pojedi.
{131183}{131279}Možda je nesporazum.|-Nema sumnje.
{131279}{131327}Znam da je djeèak.|-Koji djeèak?
{131327}{131422}Djeèak koji je s njom, on je ukrao meso.
{131590}{131613}Tko tebe uèi?
{131662}{131710}Kako to da imaš toliko ukradenih stvari?
{131710}{131781}Nitko me ne uèi. -Istina?
{131806}{131878}Hoæeš li me sada saslušati?
{131878}{131950}Zato što su tvoja dva stranca umalo ubijena.
{131950}{132021}Nadam se da možeš pomoæi tom djeci.
{132046}{132094}Nema nikakvog dokaza.
{132094}{132141}Onda sam sigurno lud?
{132214}{132261}Onda su i ostali?
{132286}{132309}Normalni su.
{132957}{133004}Što se dogaða?
{133173}{133220}Žao mi je!
{133412}{133508}Djevojka se ubila!
{133604}{133651}Zašto?
{137199}{137319}Mislim da mi možeš pomoæi. Kako?
{137367}{137414}Ja nisam bila u pravu.
{137462}{137533}Uništena je moja želja za životom.
{137606}{137629}Razoèarana sam.
{138038}{138109}Evo, još se može popraviti.
{138350}{138446}Odjeæa male djevojèice, zadrži.
{138517}{138540}Hvala.
{138685}{138732}Pokopana je.
{138757}{138853}Žao mi je, još jedan udarac.
{141298}{141345}Dobro.
{145516}{145683}Što se dogodilo? Što ste uèinili?
{145947}{146043}Što nije u redu s tvojom glavom? Da li je poremeæena?
{146067}{146114}Što to radiš?
{146139}{146187}Doði ovamo, o èemu mišliš?
{146187}{146259}Neæu te povrijediti, doði.
{146259}{146330}Vjeruj mi, neæu te povrijediti.
{146427}{146498}Gledaj u gospoðu.
{146571}{146642}Prestani! Ostavi me na miru! Prestani!
{146642}{146738}Pusti me! -U redu! U redu!
{146738}{146834}U redu! U redu! U redu!
{146834}{146954}Smiri se! U redu!
{147050}{147097}Imaš li mi nešto tužno za reæi?
{147146}{147193}Nije važno kako, reci.
{147338}{147410}Bogu nije portebno da to radiš, nekome æe trebati!
{147410}{147481}Svi poznaju tvoje srce!
{147625}{147697}Da, garantiram ti da je istina, ne brini!
{147697}{147768}Ti si hrabar.
{147937}{148009}Reci mi, gdje su tvoji roditelji?
{148009}{148056}Gdje su oni?
{148081}{148152}Zašto su te ostavili ovdje samog?
{148296}{148343}Nisu to trebali uèiniti.
{148392}{148464}Vjeruj mi, ne budi takav.
{148464}{148535}Hrabar si, to je dovoljno.
{148703}{148750}Mi možemo izdržati.
{148847}{148943}Možda da poènemo od sutra...
{148943}{149015}Doæi æe veliki vagon,|svi æe moæi uæi.
{149015}{149111}Ako ne zatvorimo vrata, vidjet æemo prizore...
{149159}{149255}To je lijepo, otvoriti vrata vlaka i gledati|prirodu.
{149279}{149375}Nikada neæemo govoriti o stvarima koje su se dogodile ovdje.
{149375}{149446}Zaboravit æemo svaðe, kraðe, umiranja...
{149591}{149638}Ono što radiš sada je dovoljno da pokaže želju.
{149710}{149781}Ja æu zauzvrat prièati drugima o tvojoj hrabrosti...
{152860}{153666}Subtitles by:|M O Z E N