{1}{1}25.000
{1147}{1293}{C:$0000FF}{y:ib} PISMA |{C:$FF0000}{y:b} JEDNOG UBOJICE 
{1331}{1396}Race, vjeruj mi.
{1401}{1484}Poslije svega, | znam, teško je,
{1489}{1573}ali moraš mi vjerovati | da si mi sve na svijetu.
{1586}{1686}U planinama sam našla | savršeno mjesto
{1713}{1856}za kuæicu; pravo mjesto | za nas. Mirno. Krasno.
{1895}{1953}Bili bismo presretni.
{1996}{2084}Poslala sam ti još jednu | sliku, da me ne zaboraviš.
{2097}{2181}Snimila sam ih mnogo, | ali ova je najbolja.
{2277}{2335}Kao da smo skupa.
{2350}{2432}I... Jednoga dana...
{2506}{2595}Zaboga, zašto nam to rade?
{2631}{2692}Zašto ne možemo biti skupa?
{2722}{2779}Odvest æe mi te.
{2791}{2889}Odvest æe te i ubit æe te.
{2975}{3075}Ali ja sam tu. | Ja znam da si nevin.
{3086}{3167}Znam da æemo | uvijek biti skupa.
{3172}{3252}Uvijek æu te voljeti. | Tvoja Steph.
{3291}{3430}UTAH, DRŽAVNI ZATVOR | OSUÐENICI NA SMRT
{3450}{3502}DNEVNIK OSUÐENIKA | NA SMRT, autor H. Darnell
{3502}{3551}Osuðenik na smrt | na listi uspješnica
{3554}{3616}Ne znaš koliko mi | znaèe tvoja pisma.
{3621}{3681}23 sata u æeliji.
{3696}{3754}Klopa, pederu.
{3891}{3960}Nekad te stvarno pogodi...
{3963}{4075}No tvoj me glas smiri | kao šum valova uz obalu.
{4291}{4396}Zaboravim da æe me ubiti | za zloèin koji nisam poèinio,
{4401}{4483}i nadam se... | Ma koga zavaravam?
{4497}{4566}Horton, doði.
{4624}{4678}ZAPADNO OD PECOSA, | Zane Grey
{4682}{4737}Hvala, uživao sam.
{4743}{4871}Znaš, to je Eisenhower èitao | prije smrti. - Zajebavaš?
{4919}{5032}Znaš Morgana u æeliji | do mene? Danas æe ga smaknuti.
{5037}{5105}Bože, kako to | uništava èovjeka...
{5110}{5223}Vidio sam to 7 puta. | No ja nisam potišten.
{5228}{5298}Knjiga mi se još | izvrsno prodaje.
{5357}{5416}Ma jebe mi se!
{5557}{5687}Nova odvjetnica odluèna je | dokazati da sam nevin.
{5691}{5769}Poslije 7 g. Teško je | vjerovati, ali...
{5774}{5831}Nadamo se.
{5865}{5992}Katkad bih pružio ruku | u mrak i zamislio da si tu.
{6000}{6096}Jer tvoja me vjera | drži, Steph.
{6147}{6277}Prva stvar ujutro i zadnja | prije spavanja si mi ti.
{6311}{6368}Voli te Race.
{6420}{6476}Ma èuj ta sranja!?
{6482}{6549}A ta njegova kokoš | puši svaku rijeè!
{6554}{6651}A tip je ubio suprugu! | Što radimo krivo...?
{6894}{6968}Imaš posjetu, | frajeru. Diži se.
{7030}{7088}Da te vidim.
{7123}{7233}Prelijepa si. Da bar...
{7274}{7351}Volio bih... - Nemoj.
{7377}{7454}Znam. I ja.
{7514}{7644}Jednoga æemo se dana odvesti | na Slanu poljanu.
{7650}{7781}Samo nas dvoje. Otvorit | æemo krov. Sunce na licu.
{7786}{7890}I juriti poput vjetra. | - I juriti poput vjetra.
{7929}{8020}Samo ti i ja. Obeæavam.
{8050}{8105}Zbilja si posebna.
{8224}{8329}Sinoæ sam nas sanjala. | Imali smo obitelj.
{8359}{8439}Jednom æemo se odvesti | na Slanu poljanu.
{8445}{8506}I juriti ko vjetar.
{8633}{8698}Bog, Gloria.
{8703}{8794}Kako si? - Race, | imam datum za posjetu.
{8804}{8917}Javili su mi što smijem | nositi, a što ne.
{8922}{9080}Ništa izazovno. Minice ne. | Ni dekoltirane majice.
{9096}{9212}No ništa ne piše o tome | što se nosi... ispod.
{9221}{9312}Što misliš? - Bože!
{9636}{9771}Odbijena je odgoda | smaknuæa. Žao mi je.
{9810}{9886}Kada? - 23. travnja.
{9917}{9966}Skoro 3 mjeseca.
{9971}{10055}Moraš mi pomoæi, Judith. | - Molim se za nas, Race.
{10144}{10206}Ti si mi dar od Boga.
{10263}{10368}Ovo nije sluèajno. On nas je | i spojio. Gleda nas.
{10438}{10562}Nikad te neæu iznevjeriti. | - Svako se jutro probudim,
{10596}{10660}a okolo... ništa.
{10688}{10799}Ne mogu to podnijeti. | - Znam. Teško je.
{10810}{10924}Ali jak si. Izdržat æeš.
{10957}{11118}A i ja sam tu, uza te. | - Samo da to završi...
{11223}{11333}9:30. Saznao si da te žena | vara s najboljim prijateljem.
{11337}{11407}Ljut si. Posvaðate se. | Susjedi èuju. - Pa?
{11413}{11513}Èekaj. U 9:45 odlaziš. | Ali nitko te ne vidi.
{11518}{11594}U 10: 12 pucnji. | Ženu naðu mrtvu.
{11599}{11694}Upucana u glavu i prsa. | Prstenjak odrezan.
{11699}{11759}To te pokopalo kod porote.
{11764}{11880}No sada, jedan èovjek kaže | da te vidio kako odlaziš.
{11885}{11997}Za 20 min vidio je Tolly | kako ulazi, èuo pucnje,
{12000}{12080}a Tolly je istrèao. | - Sranje!
{12162}{12222}Gotovi smo.
{12235}{12300}Otvori! - Idi u æeliju.
{12305}{12467}43 dana! Neæu gubiti | vrijeme na takva sranja! Idem!
{12496}{12581}Ako te ne zanima kljuèni | svjedok koji nije svjedoèio,
{12585}{12723}u redu. - Uvijek | ista prièa. Otvori!
{12727}{12809}Tužilac nije rekao | tvom odvjetniku za njega!
{12815}{12985}Doði! - Bila je izborna godina. | Morao je dobiti sluèaj.
{13097}{13286}Slušaš me. Dobro. Jer sada | držimo sustav za jaja!
{13291}{13355}Tražit æu ponovno suðenje.
{13702}{13753}Što se zbiva?
{13759}{13864}Pokreni se. - Neæu! | Ne želim iæi! Molim vas!
{13880}{13983}Dajte mi još malo vremena!
{13989}{14078}Neka mi netko | pomogne! Molim vas!
{14142}{14220}Šuti! Ne cmizdri.
{14449}{14589}Norme, èuj ovo. - Ne veèeras. | Idem na tekmu. Moram iæi.
{14594}{14691}Èekaj. - Raširit æu ti | noge što jaèe.
{14696}{14832}Uzet æu lizaljku od višnje, | iæi ti njome do bedara,
{14837}{14973}i onda ti je ugurati. | - Hustler æe uživati ko beba.
{14979}{15042}Baš si jadan. Odoh ja.
{15049}{15177}Kamo, Parkeru? Zaboravi tekmu. | Cijelu æeš noæ biti ovdje.
{15241}{15359}Taj kreten Darnell! Ne sve | èetiri! Ne noæas! Kreten!
{15375}{15464}Jednoga dana...! | - Pomiješaj. - Što?
{15493}{15550}Zamijeni ih.
{15998}{16094}Kralj na lovca 4. | - 2 dana. A ti?
{16135}{16204}Igraj i plaèi.
{16286}{16437}Hortone. Kako Sylvia? | - Ne pitaj.
{16451}{16538}Još je nisi pozvao van?!
{16598}{16719}Razmišljao sam. | Daj mi par savjeta.
{16724}{16826}Tebi to dobro ide. | - Ne znam baš.
{16832}{16896}Oèito je!
{16979}{17156}Tu nije isto... | To je moguæe samo odavde.
{17163}{17245}Ja s jedne strane | rešetaka, one s druge.
{17251}{17330}Tu su svi na sigurnome.
{17361}{17419}Što ako te puste?
{17616}{17710}Moguæe je. Novo suðenje | te može spasiti.
{17821}{17878}Šah-mat.
{18046}{18099}Èuj ovo.
{18162}{18241}Bog, Race. Hvala na pismu.
{18270}{18329}Vrlo je lijepo.
{18359}{18421}Samo, nije bilo | namijenjeno meni!
{18428}{18487}No to nema veze, ne?
{18494}{18568}Jer tebi su sve | pièke iste, ne?
{18574}{18663}Vjerovala sam ti. | Povjerila ti se.
{18678}{18754}A tebi to ništa | nije znaèilo!
{18773}{18857}Od sada, znaèit æu ti sve!
{18863}{19030}Kako si mogao? | Ubit æu te, gnjido!
{19035}{19118}Jebemu. Kako se to dogodilo?
{19131}{19237}Veoma sam pažljiv. | - Znaš koje je?
{19268}{19423}I što kaniš? - Èekati. | Da stignu pisma od drugih.
{19429}{19525}U noæima poput ove, | kad je strašno vruæe,
{19557}{19609}mislim o tebi.
{19684}{19742}Kako te mazim.
{19908}{19976}Opet si u svim novinama.
{20013}{20134}Možda su se isplatila | sva ona moja pisma guverneru.
{20279}{20462}Imam dobar osjeæaj. Idemo. | - Ako te puste, što æeš s njom?
{20468}{20544}Saznat æu tko je | zamijenio vrpce.
{20548}{20628}I onda? - I onda æu | sve ispraviti.
{20633}{20693}Zvuèi opasno. - Moram.
{20696}{20816}Još ne znaš tko je? - Ne. | Pišu ko da je sve u redu.
{20834}{20898}Poslala mi je | još jedno. - Što?
{20916}{20984}Isto? - Još gore.
{21038}{21114}Misliš da se ne šali? | - A što ti misliš?
{21119}{21179}Da si moraš èuvati leða.
{21251}{21367}Sigurno te izluðuje | što ne znaš tko sam.
{21371}{21430}Ali ja tebe znam.
{21435}{21510}Praviš se da to | nije problem. Nadaš se
{21570}{21659}da æe nestati. Ali neæe.
{21699}{21757}Izdao si me.
{21773}{21850}Neæu dopustiti da se izvuèeš.
{21855}{21939}Umrijet æeš, Race. | Pobrinut æu se za to.
{21943}{22003}Neka optuženi ustane.
{22068}{22145}Èlanovi porote, | jeste li donijeli odluku?
{22150}{22287}Jesmo, èasni suèe. U | sluèaju... - Ne zavaravaj se.
{22292}{22366}Ma što odluèili, | presuda æe ti biti ista!
{22372}{22435}Nije kriv. - Smrt!
{22641}{22699}Smrt.
{23400}{23473}Opraštate li ženi? | - Kako vam je kad je mrtva?
{23480}{23545}Osloboðen je svih optužaba!
{23548}{23612}Što ste uèinili s prstom?
{23639}{23696}Race!
{23701}{23789}Race! Ovamo! | Race! - Steph! - Doði!
{24110}{24173}Mislite da samo | tako možete otiæi?
{24464}{24544}Rado bih te pozvala | da ostaneš,
{24551}{24617}ali moji još ne znaju za tebe.
{24658}{24719}Mormoni su.
{24784}{24857}To je naša tajna, može?
{25029}{25089}Uzdravlje.
{25325}{25474}Bože. - Bog. - Razgovarao sam | s prijateljima,
{25486}{25566}i odjednom pomislih, | Nadam se...
{25583}{25710}Pokušavamo razgovarati... - Ne | govorim tebi, ženo-ubojice.
{25781}{25858}Kao što rekoh... | - Ako nisi èuo,
{25891}{25987}presuda je nije | kriv. - Briga me.
{26010}{26167}Dakle, sjedio sam i pomislio, | Valjda ona voli ševu u guzu;
{26174}{26262}jer on se u gajbi | na to naviknuo.
{26267}{26368}Race... - Da se mene pita, | sada bi srao u gaæe
{26373}{26480}pred vodom za strijeljanje. | Hajde, ubojico. Idemo.
{26518}{26592}Hajde. - Nemam namjeru
{26597}{26678}prvu noæ slobode | provesti u gajbi.
{26735}{26803}Ugodna vam veèer.
{26838}{26900}Isprièavam se. Laku noæ.
{27038}{27117}Oprosti, Steph... - Nije važno.
{27123}{27201}Ne znam što mi je došlo | da te dovedem ovamo.
{27205}{27260}Ma nema veze.
{27449}{27549}Ne! Nemoj! - Hajde! Diži se!
{28059}{28114}Ne!
{28584}{28642}Nisam kriv, gnjido!
{28681}{28746}Nisam kriv, èuješ?!
{28769}{28842}Nisam kriv! - Prestani, Race.
{28860}{28985}Ubit æeš ga! - Izvrsno! - Nemoj.
{29155}{29210}Molim te.
{29884}{29933}Hvala.
{29946}{30093}Zbilja mi je žao. - Šališ se? | Svatko bi to uèinio. - Ne.
{30098}{30199}Nitko ne bi. | Htio sam ga ubiti.
{30209}{30328}Isto k'o unutra... | Zajebavali me...
{30370}{30490}Ne želim biti takav. | Nisam takav. Nisam.
{30535}{30701}Znam kakav si. - Znaš? | - Poslije toliko godina...
{30731}{30788}nema više tajna.
{31020}{31079}Steph.
{31132}{31288}Imaš sva moja pisma? | - Jasno. Èuvam ih ko oko.
{31326}{31409}Jesi li ikada... - Što?
{31572}{31712}Mislio sam... | Ono o Morganu, o noæi...
{31717}{31797}kad je umro. | - Nemojmo veèeras o tome.
{31828}{31892}Steph... - Ne veèeras.
{32899}{33047}Bog, Lita je. - Bog. Race. | - Nisam doma. Ostavite poruku.
{33402}{33468}Dobili ste Judith. | Ostavite poruku.
{33495}{33607}Bog. Race. | Šteta što nisi doma.
{33633}{33722}Bog, Race. | Baš sam mislila na tebe.
{33793}{33919}Rado. Ali sada je | gužva oko žetve...
{33992}{34100}Vidimo se uskoro. | Naæi æu te.
{34143}{34200}Znam gdje si.
{34246}{34305}Bog. Èuvaj se.
{34969}{35072}Hvala što si došao. | - Drago mi je što te vidim.
{35271}{35370}Htjela sam porazgovarati | oèi u oèi, ne žicom.
{35375}{35476}Dobro, jer i ja želim | s tobom razgovarati.
{35572}{35631}Sjeæaš se noæi | kad je Morgan umro?
{35636}{35697}To je... Teško.
{35742}{35800}Jest.
{35813}{35918}Ondje je... Uz jezero je | bio kafiæ; možemo...
{35926}{36029}Imam dogovor u 15 h. - U 15?
{36042}{36139}Imamo malo vremena. | - U zatvoru.
{36214}{36323}Vrijeme posjeta. | - Posjeæuješ još nekoga?
{36343}{36437}Dugo se dopisujemo. Jadnik.
{36442}{36523}23 su mi godine. Sam je.
{36530}{36643}Dakle... Mislim da je | bolje da prekinemo.
{36831}{36942}Zbog vrpce, zar ne? | Èuj, Gloria...
{36946}{37010}Rekao sam ti da mi je | žao. Nisam to htio.
{37015}{37071}O èemu govoriš?
{37081}{37154}Nisam samo tebi pisao.
{37182}{37295}Nisam to ni mislila. | - Nisi? - Normalno.
{37304}{37364}Onda ne kužim. | U èemu je problem?
{37372}{37434}Sad si slobodan.
{37534}{37671}Èuj... Naš mi je | odnos bio važan.
{37681}{37802}Ali sve se... promijenilo. | - Zašto? - Tu je drukèije.
{37815}{37939}Ondje, sve meðu nama, | sve je bilo važno.
{37946}{38034}Jer nismo znali | kada æe te odvesti.
{38062}{38140}Što æeš sada?
{38266}{38326}Još nešto.
{38342}{38480}Što? - Kada si poèela pisati | tom drugom? - Žao mi je.
{38490}{38550}Moram iæi.
{38683}{38701}Možda na kraju ipak požalim
{38775}{38872}Ali opet bih uèinila isto
{38911}{38981}Tata je pokušao | Tata je pokušavao
{39041}{39106}Tata je pokušao | Uèiniti anðela
{39114}{39171}Od svoga maloga srca
{39324}{39385}Kako si me našao?
{39415}{39513}Pitao sam u tvom uredu. | Potrajalo je.
{39618}{39684}Drago mi je što te vidim.
{39712}{39772}Izvoli.
{39777}{39845}Kušaj. Fino je.
{40041}{40099}Lita.
{40104}{40191}Lita! Kako si? - Drago mi je | što te vidim. - Bog.
{40196}{40248}Dobro izgledaš.
{40264}{40348}Prijatelji? - Da. Policajci.
{40384}{40488}Èesto ovamo dolaze. | - Šališ se? Kako znaš?
{40553}{40611}Bila sam policajka.
{40656}{40716}Doði. Daj.
{40733}{40828}Jedan pogled | Jedna iskra
{40850}{40945}Vreli poljupci u noæi
{40993}{41078}Uzmi me u naruèje...
{41329}{41458}To nikad nisi spomenula. | - Davno je to bilo.
{41464}{41518}Kad sam bila udana.
{41523}{41594}Bio je murjak? | - Ne. Bio je šupak.
{41914}{41971}Hajde.
{42046}{42095}I dva...
{42099}{42148}Okret.
{43155}{43222}Zašto si otišla iz murje?
{43251}{43354}Gonili smo jednu | gnjidu u Gardnervilleu.
{43359}{43436}Jebeni perverznjak. | Napadao je djecu.
{43485}{43546}Lijevo na semaforu.
{43589}{43749}Uhvatili smo ga u Woodfordu, | gradiæu na državnoj granici.
{43754}{43866}Izvan moje nadležnosti. | Pustili su ga.
{43898}{44019}Poèela sam ga pratiti. | Kamo on, tamo i ja.
{44024}{44153}Èekala sam da pogriješi, | da mu pokažem lekciju
{44156}{44220}koju nikad neæe zaboraviti.
{44257}{44316}I, uspjela si?
{44350}{44438}Ne. Tužio je murju | zbog maltretiranja.
{44443}{44540}Zato si izgubila posao? | - Ne. Zato što sam šefa
{44545}{44637}nazvala jebaèkom | svinjom. - Jebaèkom?
{44685}{44775}To je još blag izraz. | - Jebaèka?
{44813}{44871}Zeleno je.
{45107}{45188}Oprosti zbog nereda.
{45326}{45409}Još ga moraš nositi? | - Svaki dan.
{45428}{45519}Trebala sam ga imati | i u braènoj postelji.
{45667}{45734}Piæe? Viski?
{45881}{45945}Što si to rekla...?
{45972}{46081}Tako bih mogla reæi | da su modrice od vježbanja.
{46087}{46227}Kujo! - Kriste! - Kad te | izmlati zloèinac, junak si.
{46257}{46321}Kad te namlati muž,
{46381}{46497}budala si. - Nisi budala. | - Hoæeš leda?
{46570}{46661}Može. - Stavi neku | glazbu. Odmah æu.
{46721}{46796}Nešto posebno? - Bilo što.
{47146}{47279}Jesi li što našao? - Zaboga. | Sve moje vrpce...
{47354}{47414}Nedostaje li ti to?
{47858}{47916}Lita...
{47981}{48090}Èuj... Moram te nešto pitati.
{48203}{48323}Sjeæaš se vrpce koju sam | poslao kad je Morgan umro?
{48331}{48437}Da. Zašto?
{48452}{48581}Moguæe je da si | dobila krivu vrpcu. - Krivu?
{48603}{48761}Mislim, vrpcu | namijenjenu nekom drugom.
{48796}{48860}Nekom drugom?
{48907}{48992}Nisam se samo | s tobom dopisivao.
{49034}{49089}Bilo vas je èetiri.
{49126}{49185}Èetiri?
{49240}{49332}Èetiri?! - Pokušaj me shvatiti.
{49336}{49401}Sve ste mi davale | naklonost i potporu...
{49405}{49480}Naklonost i potporu?! | - Ne, samo...
{49484}{49555}Svima si pisao ista sranja?!
{49560}{49621}Sve sam vas trebao. | - Sve si nas varao!
{49626}{49686}Ni jednu nisam | molio da mi piše...
{49691}{49784}Došao si vidjeti imam li | tuðu vrpcu! - Morao sam.
{49788}{49865}A što da je nemam?!
{49870}{49957}Poševio bi me i otišao | iduæoj?! - Slušaj...
{49972}{50053}Slušaj ti mene, gade! | Što si ti umišljaš!?
{50058}{50179}Sedam godina laži! Svima nama! | - Održavale ste me živim...
{50184}{50310}Ma odjebi! Gubi se! Van!
{50337}{50474}Gubi se! - Molim te, slušaj me. | - Ma odjebi istog trena!
{51315}{51426}Krasan auto. Vidiš kako je | lako doæi do tebe?
{51541}{51628}Iduæi put, možda ga | dignem u zrak.
{51765}{51857}Htio si se izvuæi | objašnjenjem?
{51862}{51929}Mislio si, posjet | i isprika je dovoljno?
{51934}{52001}Nije. I nikad neæe biti.
{52008}{52109}Presuda je smrt. | Umrijet æeš, Race.
{52149}{52236}I kao maloj, govorila je, | Ne vjeruj muškarcima.
{52241}{52306}DJETINJSTVO. Tko je ona? | Majka? Kæi? Sestra?
{52311}{52393}Svake me veèeri upozoravala. | Ne vjeruj im, rekla bi.
{52412}{52501}Kao mala, | bojala sam se mraka.
{52505}{52566}Mamica bi mi ostavljala | upaljenu svijeæu.
{52570}{52636}JUDITH - MAMICA
{52682}{52772}Kad sam bila mala, | sanjala sam da sam kraljevna.
{52776}{52834}STEPH - KAD SAM BILA MALA
{52841}{52950}S tobom sam u tvojoj | æeliji. U tvojoj glavi.
{52975}{53042}Zauvijek. Dok ne umreš!
{53100}{53203}U tvojoj glavi. | Zauvijek. Dok ne umreš!
{53241}{53350}Vjeruj mi, Race. | Poslije svega...
{53359}{53421}Teško je, ali | moraš mi vjerovati
{53426}{53489}da si mi sve na svijetu.
{53540}{53608}Mamice!
{54975}{55038}Tata!
{55051}{55116}Gle, tata!
{55356}{55445}Voljela bih ti roditi sina.
{55467}{55543}Bio bi divan otac.
{55584}{55660}No radije bih djevojèicu.
{55716}{55801}Djevojèice su posebne.
{56865}{56922}Bože!
{57095}{57178}Što je bilo? - Otkud ti tu?
{57328}{57387}Èekao sam da ti muž ode.
{57560}{57701}Dobro si? - Jesam. | - Steph... - Zovem se Stephanie!
{57956}{58015}Otkad ti to radi?
{58065}{58176}Ne razumiješ. | Pod strašnim je pritiskom.
{58220}{58328}Što si mislila | da æe biti kad izaðem?
{58444}{58545}Da æeš me odvesti | daleko. Usreæiti me.
{58581}{58660}U našem savršenom svijetu.
{58672}{58731}Steph...
{58802}{58862}Za sve si ti kriv, zar ne?
{58896}{58954}Zar ne?
{58968}{59092}Nisi mogao èekati? | Morao si me uhoditi.
{59114}{59171}I sve pokvariti.
{59369}{59498}Nisam te htio povrijediti. | - Navikla sam.
{59527}{59573}Sa mnom je Horace | Darnell. - Race.
{59662}{59758}Race je bivši robijaš | i autor uspješnice
{59764}{59819}"Èekajuæi smrtnu presudu".
{59824}{59897}Jesi li iznenaðen | uspjehom knjige?
{59901}{60016}Pa, èudno je što takvo | štivo ljude zanima.
{60023}{60136}Navodno su bivši robijaši | vrlo privlaèni ženama?
{60142}{60264}Ne znam to, ali knjigu | mnogi vole. - Daj, Race!
{60269}{60338}Tu nemamo tajna! | Imamo par poziva.
{60343}{60404}Dennis Fraser iz Hebera.
{60427}{60514}Koja ti je bila | omiljena hrana?
{60549}{60623}Kuhar je bio majstor | za maèke ubijene na cesti.
{60627}{60693}Hvala, g. Fraser. | Annette Pakula.
{60699}{60798}Èujemo se? | - Uživaš li u slobodi?
{60803}{60904}Divno je, jer... | - I meni je bilo,
{60907}{60971}dok mi nisi išèupao srce.
{60976}{61042}Hvala, gðice Pakula. | - Rekao si da me voliš,
{61047}{61177}a lagao si! Neæeš se | izvuæi! Išèupat æu ti srce!
{61182}{61310}Hvala gðici Pakula. | Kako rekoh, žene vas vole...
{61315}{61383}Sad ste se svi uvjerili.
{63323}{63400}Buduænost Racea Darnella
{63516}{63582}Buduænost Racea Darnella.
{64677}{64746}Isuse!
{64749}{64851}Izgleda poznato? | - Dajte mi telefon.
{64858}{64942}Labos kaže, | nije bilo silovanja.
{64946}{65052}STOŽER FBI-a -Nije silovanje. | Ni pljaèka. Što je to?!
{65057}{65133}Darnellov dosje... | - Rekao sam ti...
{65137}{65219}Ubijena je na isti naèin. | Isti prst odrezan.
{65224}{65303}To nema smisla. | Zašto bi uèinio isto
{65308}{65384}što ga je veæ skoro | odvelo u smrt?!
{65389}{65466}Netko ga imitira? | - Ili ubojstva nemaju veze.
{65472}{65572}A prst? - Možda | ljubomora. Sluèajno.
{65579}{65670}Možda Racea svrbe | prsti poslije 7 g.
{65675}{65778}Ne zakljuèujmo prerano. | - Usporedili su otiske.
{65782}{65898}Darnellovi su. | - Privedite ga.
{65903}{65968}Iz ovih stopa.
{65980}{66069}Netko mi prijeti. | Moram saznati tko.
{66074}{66191}Rekao si policiji? | - Policiji?! Ne. Zašto?
{66202}{66319}Krivo razmišljaš. | - Kako to misliš?!
{66324}{66422}Njima bih se zadnjima | obratio! Ismijali bi me!
{66430}{66566}Što ti ja mogu uèiniti? | - Nabavi zapise tel. Poziva.
{66572}{66682}Zanima me tko je | Annette Pakula. - I onda?
{66725}{66829}Èuj... Dat æu ti pravni | savjet, otiæi murji s tobom,
{66832}{66912}ali neæu sudjelovati | u nekakvim osvetama.
{66916}{67002}Ako to želiš riješiti, | reci murji.
{67285}{67416}Forrest, èuj ovo. Susjed kaže | da je Darnell bio tu u 16 h.
{67652}{67720}Hoæu sve o Darnellu. | Zapise poziva.
{67725}{67784}Cure. Ili deèke... | Sve detalje!
{67790}{67872}Patrick ima dosje. | - Hoæe li nam ga dati?
{67876}{67960}Gdje je on uopæe? Reci | mu da siðe s komada!
{67964}{68008}Darnell ima... - Patrick.
{68049}{68139}Elizabeth Bancroft mu je | odvjetnica. A Prenticeova?
{68142}{68226}Tu nema ništa. - Bit æe. | - Blokirajte okolne ceste.
{68232}{68375}I javite svim postajama. | - Što æe biti dokaz? - Prst.
{68878}{68929}NOVI PODACI
{68997}{69046}NOVI PODACI
{69268}{69336}SNIMLJENO RANIJE
{69385}{69440}Bože!
{69574}{69655}Želite se pomaknuti? - Da.
{69704}{69756}Niste li vi...
{71225}{71287}Ubila ih je, Hortone.
{71313}{71375}Stephanie i | Elizabeth su mrtve.
{71379}{71444}A ja sam je doveo do njih.
{71500}{71592}Nisam ih ja ubio. | Znaš da nisam!
{71611}{71727}Znaš da nisam! Èuo | si je! Luda je!
{71776}{71834}Kvragu, Hortone! Slušaj me!
{71837}{71916}Moram u Kansas. Judith | ima Stephinu vrpcu.
{71920}{72000}Judith je ubojica! Slušaj me!
{72031}{72104}Nemoj. Slušaj me!
{72109}{72172}Ako misliš da sam | kriv, zovi murju.
{72175}{72232}Ali razmisli! Razmisli!
{72236}{72297}Šah. Knjige. Stalno. | To je bilo sranje?!
{72302}{72373}Ako tako misliš, pozovi ih!
{72400}{72491}Ali ako me uhite... mrtav sam!
{72532}{72600}Gledat æu te kako ih zoveš.
{72605}{72695}Znam tko je ubojica! | Zašto bih bio tu da lažem?!
{72700}{72832}Gledat æeš me u oèi. | Jer nikad ti nisam lagao!
{72849}{72931}Hajde. Zovi ih.
{73032}{73101}O, ne!
{73470}{73542}Horton Weaver? | - Oèekivao sam vas.
{73547}{73632}Ag. Louise Singleton | i ag. Patrick O'Dell.
{73638}{73737}Je li vam se Darnell | pokušao javiti? - Uðite.
{73742}{73819}Nemam èesto društvo...
{73824}{73936}Biste li željeli jesti | sa mnom? - Ne, hvala.
{73942}{74028}Možda vam se Darnell | pokuša javiti.
{74033}{74108}Jedna žena prijeti Darnellu.
{74117}{74202}Šalje mu pisma. | Stavite to u zapisnik.
{74220}{74360}Zapisnik. - Hoæemo. | - Èuvajte se. - Hoæemo.
{74782}{74873}Nisam te htio dovesti | u takav položaj.
{75218}{75304}Što sam to uèinio?!
{75454}{75536}Koji sam ja kreten!
{75788}{75875}Da. Idi. Nestani.
{76898}{76954}Kansas?
{76990}{77014}Dobro. Tko æe mi reæi | o prijetnjama Darnellu?
{77217}{77384}Nitko? - Bilo je nešto... Ali | ne bih to zvao prijetnjom.
{77404}{77527}Nego kako? - Pa, više kao...
{77533}{77597}Ljubavni nesporazum.
{77669}{77822}Nesporazum? Dobro... Pomislio | sam da mi trošite vrijeme.
{77909}{78066}Istražujem dvostruko ubojstvo; | ne želim zbrku. Jasno?
{78207}{78323}Nemoj... me jebati.
{78431}{78524}Darnell se dopisivao s 4 žene.
{78534}{78614}Imena? - Jedna je...
{78619}{78710}Anita... Rita... - Lita. | Radila je u banci.
{78716}{78868}U osiguranju, ne? - Takvo što. | - Odakle je? - Iz Renoa.
{78873}{78963}Pitajte Hortona. | Njih su dvojica bili...
{78968}{79044}bliski... Isprièavam se.
{79060}{79173}Privedite ga. - Horton je vani.
{79180}{79245}Stric mu je bolestan.
{79335}{79416}A Lita? - Sumnjam.
{79439}{79510}Ali, tko zna...
{79534}{79641}Može biti bilo koja. | Ona Annette Pakula ima vrpce.
{79647}{79729}Kad naðemo nju, | našli smo ubojicu.
{79921}{80022}Stric kaže da nije bolestan. | Nije se ni èuo s Waeverom.
{80028}{80129}Izdaj potjernicu za njim. | Motrite strièevu kuæu.
{80137}{80244}Isuse. Što misli, | tko je?! Wyatt Earp?!
{80300}{80384}Možda. Možda.
{80441}{80597}Osim par stvari, | ovo je èisti Zane Grey. - Jest.
{80608}{80721}Što si uèinio piliæu? | - Bacio ga na vatru. - Da?
{80777}{80859}Još jedno pivo? - Može.
{80926}{81004}Kad si izašao | iz kuæe s pištoljem,
{81009}{81091}mislio sam, ubit æeš me.
{81156}{81218}I ja sam to mislio.
{81767}{81878}Da ja vozim? - Ne treba. | - Nije daleko.
{82006}{82068}Što je? - Stavi kapu.
{82121}{82179}Kapu!
{82196}{82285}Ne gledaj ga. Ali | ni ne skreæi pogled.
{82299}{82370}Ponašaj se kao da smo domaæi.
{82483}{82539}Koèi?
{82567}{82629}Ne još.
{82788}{82872}Što radi? - Izvukli smo se.
{86404}{86550}Gade! Srao si da si nevin! | A ja sam ti vjerovala!
{86589}{86668}Lita. Što tu radiš?! | - Privest æu te.
{86673}{86743}Ovaj put nemam frku | s nadležnošæu.
{86747}{86832}Lita... - Diži se! - Dobro.
{86895}{86960}Slušaj me! - Zaveži!
{87034}{87091}U auto!
{87138}{87203}Sve si krivo shvatila.
{88333}{88398}Bože.
{88695}{88751}Isuse!
{88776}{88833}Kriste!
{88862}{88918}Žao mi je.
{88996}{89053}U auto.
{89113}{89207}Ubila si je. | - Ne. Ti si je ubio.
{89212}{89267}Kao svoju ženu.
{89272}{89344}Ubila si i Stephanie. | - A ne! Ti si je ubio!
{89349}{89450}I Elizabeth. - Natrag!
{89453}{89571}Stalno si tu bila. - Ne. | Pratila sam te od Hortona.
{89825}{89923}Race Darnell. Izaðite | s podignutim rukama.
{89997}{90064}Vi u polju! Stanite!
{90152}{90232}Na polje! - Brzo!
{90578}{90686}Tko je ona?! - Lita! | - Tako mi svega!
{90724}{90782}Hortone.
{90817}{90875}Makni se!
{91048}{91108}Brže! Skini mi lisice!
{91192}{91250}Što...!?
{91376}{91432}Sranje!
{91513}{91570}Horton!
{94468}{94561}Dobro si? - Uhvati ubojicu. | To nam je jedina nada.
{94566}{94632}Hajde, Race!
{94644}{94749}Race! - Moram iæi. - Idi, | sinko. To je jedina šansa.
{94956}{95063}Zašto si mi skinula lisice? | - Možda ipak nisi ubojica.
{95222}{95338}Tri? Isuse! - Još dva, | i dobivaš komplet noževa.
{95352}{95449}Kansas. Nije kraj svijeta, | ali ga se odande vidi.
{95465}{95567}Policija iz Renoa; Lita | Coe je izbaèena prije 6 g.
{95572}{95670}Neregularno uhiæenje. | I nastavila je pratiti tipa.
{95674}{95781}A tip je tužio policiju | zbog maltretiranja.
{95803}{95868}Idemo.
{96362}{96447}Weaver je rekao sve što | zna; no to nije mnogo.
{96452}{96546}Darnell ide u New Orleans | po neku crvenokosu Gloriju.
{96550}{96659}I? Èekamo da Darnell | ubije tu Gloriju?
{96664}{96740}Javit æu tamošnjoj | policiji. - Ne kužiš.
{96745}{96830}Nije Darnell ubojica. | - Vraga nije!
{96837}{96900}Èekao je smrtnu presudu | još prošli tjedan!
{96906}{96995}Kamo god krene, netko pogine.
{97103}{97190}Znaš što radiš? | - Aha. - Dolje!
{97207}{97279}A što misliš tko jest?
{97308}{97396}Žena. Valjda Coe.
{97416}{97542}Zašto? - Razmisli. Zašto je | izbaèena iz policije.
{97549}{97603}Pretjerala je.
{97608}{97679}Tebi nikad ne doðe | da to uèiniš?!
{97683}{97753}Imala je pravo; | tip je bio smeæe.
{97757}{97862}Da, ali manipulativan je | tip. Solo igraèica.
{97865}{97926}Veza s Darnellom bila je jaka.
{97930}{98017}I zato je ubojica? | - Dobila je tuðu vrpcu!
{98020}{98123}Idemo. - Shvatila je | da veza nije posebna.
{98128}{98220}Isto sranje kao i s drugima.
{98224}{98311}Pa što? Šok... - Ne samo to.
{98314}{98386}Dala je srcu oduška. | Gle što radi.
{98390}{98455}Prijeti Darnellu | još u zatvoru.
{98460}{98641}To je racionalno ponašanje?! | Darnell izaðe, ona ga prati.
{98645}{98769}Sjeæaš se? | Sazna da ih je bilo èetiri.
{98773}{98849}Izdaja je teža | nego je mislila.
{98853}{98911}Strašna konkurencija.
{98914}{98985}Pa ubije Prentisicu. | Onda odvjetnicu.
{98989}{99101}Zašto nju? - Pa... Jer je | Darnell želi vidjeti.
{99105}{99173}Jer je lijepa. - Nastavi.
{99178}{99279}Krene u Kansas | do Judith Dutton. Ubije je.
{99282}{99395}No Darnell se pojavi. | Pa se pravi da je našla leš.
{99399}{99493}Zašto ga ne ubije, ode | u New Orleans i dovrši to?
{99498}{99563}Ne znam.
{99668}{99756}Što je? | - Pokušavam te shvatiti.
{99783}{99864}Svi misle da si ti ubojica.
{99869}{99957}Da nisi, znamo samo | ti, ja i Gloria.
{99961}{100046}Èim tebe uhvate, | ona kreæe na mene.
{100050}{100126}Nazovimo ovo ulaganjem.
{100130}{100219}Zar samo ja shvaæam? | Što je vama, ljudi?!
{100224}{100331}Sve upuæuje na Darnella. | O L. Coe nemate ništa.
{100334}{100432}Brinker. - Ne znaèi | da griješimo. - Daj!
{100493}{100550}Kreæemo.
{100623}{100624}Idu prema jugu. - Drži ih | tako. - Ne mogu vjerovati! FBI!
{101223}{101319}Kad mi otac èuje, | bit æe zelen od zavisti!
{101424}{101488}Upravljaj na 2-0-0.
{101959}{102018}Kurs 2-0-0.
{102115}{102221}Kada stižete? - Za 40 sek. | - Za 30, okrenite se.
{102226}{102289}Dalje æe jedinice na tlu.
{102498}{102555}Sranje!
{103049}{103144}Ne sviða mi se ovo. | - Moramo. - Idemo.
{104031}{104086}Hajde.
{104680}{104740}Prekini paljbu!
{104745}{104819}Ne pucaj! - Doði, Lita!
{104861}{104941}Skoèi! Daj! - Stani ondje.
{104975}{105032}Ne mogu! - Nema druge!
{105060}{105136}Jedan. Dva. Tri.
{105368}{105429}Ne pucajte!
{105641}{105701}Sranje.
{105784}{105846}Pobjegli su vam.
{105942}{106023}Hoæu ljude sa psima | na obje obale rijeke.
{106027}{106143}Hoæu helikopter. Ronioce | na 10 km u oba smjera.
{106162}{106239}A ovaj kreten može doma.
{106298}{106365}Možeš iæi.
{106695}{106768}Ubojica usamljenih | žena pobjegao FBI-u
{106890}{106953}Možemo. I hoæemo. U redu.
{106992}{107086}Djeco, idemo u New Orleans. | Gloria je zvala.
{107181}{107259}Kako je hladno! Barem je suho.
{107264}{107358}Našao si drva | za vatru? - Nešto.
{107406}{107517}Znaš gdje smo? | - Negdje u Arkansasu.
{107566}{107668}Ali znaš kamo idemo? - Znam.
{107992}{108072}Uvijek sam mrzila | tu sliku. - Ja ne.
{108077}{108168}Gloria, zar ne? | - Da. - Mogu vidjeti?
{108349}{108413}Lijepa je.
{108451}{108556}Oèito je nisam poznavao. | O svemu je lagala.
{108561}{108701}Èak i za ime. Na radiju je | bila Annette Pakula.
{108780}{108926}Race... Slušaj me. | Moraš mi vjerovati.
{110177}{110232}UBOJICA OSAMLJENIH ŽENA
{110259}{110316}OSUMNJIÈENI UBOJICA | OSAMLJENIH ŽENA POBJEGAO FBI-u
{110623}{110677}Hej, vi!
{110769}{110825}Imate 20 sitnoga?
{110879}{110935}Vidjet æu.
{111248}{111305}Hvala.
{112006}{112064}Race...
{112105}{112161}Odmah se vraæam.
{112727}{112807}DNEVNIK: ÈEKAJUÆI SMRT
{113645}{113746}Što radiš?! - Idemo, Race. | - Van! - Idemo!
{113766}{113834}Van iz mog taksija! | - Gubi se!
{113857}{113918}To je moj taksi!
{113923}{114003}Kvragu!
{114092}{114165}Znam tko si. - Što?
{114401}{114486}Da, ja sam zvala. | Bila sam pijana. I bijesna.
{114491}{114575}Nemoj... - Pakula mi je | bilo muževo prezime.
{114701}{114803}Što radiš?! Stani. | - Idemo na murju.
{114811}{114908}Riskirat æu. | - Stani kad kažem!
{115097}{115160}Hajde. Ubij me.
{115712}{115768}Nazvala sam èim | sam sinoæ stigla.
{115774}{115840}Bila sam na promociji | knjige u New Yorku.
{115845}{115961}Krenuli su ovamo. Zato | æemo odavde voditi akciju.
{115965}{116068}Zašto ih ne uhitite | kada stignu ovamo?
{116073}{116214}Moramo ih uhvatiti na djelu. | - A ja sam mamac?!
{116242}{116323}Recimo. Ali budite bez brige.
{116328}{116432}Bit æemo stalno uz vas. | - Vidjela sam Racea
{116447}{116548}kad je pušten. | Ne vjerujem da je ubojica.
{116566}{116628}Ni mi.
{117809}{117898}Coe je ušla. Iz ul. Lafayette.
{117903}{118010}Mogu je skinuti. - Tek kad | kažem! Da vidimo što æe.
{118013}{118073}Sama je.
{118168}{118255}U bici, za pobjedu | važan je faktor iznenaðenja.
{118329}{118391}Oprostite.
{118395}{118496}Možete li mi dati broj | stana Glorije Stephen?
{118501}{118586}Ne, ali reæi æu vam je li tu.
{118630}{118721}Ne. Upravo je izašla. | Valjda je u dizalu.
{118788}{118848}Hvala.
{118889}{118946}Singleton?
{118950}{119005}Dobro, šefe.
{119038}{119094}Idemo.
{120905}{120992}Osumnjièena u dizalu. | - Nemoj je prestrašiti.
{121115}{121171}Pardon.
{121398}{121452}Predvorje
{121494}{121556}FBI. Spustite oruž je! - Baci!
{121562}{121622}Nemoj, Lita. - Baci!
{121938}{122008}Sranje! Darnell! - Ne!
{122089}{122189}Sranje! - Stube! - Vi, sa mnom!
{122193}{122303}Daj mi pištolj, Lita. | - Miruj, ili joj ode glava!
{122399}{122509}Krov ili stan? Jedna grupa | na stube, druga na krov!
{122762}{122836}Trebam nacrt stana i krova.
{122843}{122927}Hoæu helikopter | i Hitnu. Hajde!
{122944}{122945}Ulazi!
{123128}{123214}Dolje. Dolje! Licem na pod!
{123222}{123297}Lita, nemoj... - Dolje!
{123549}{123631}Ja najbolje razumijem | kako se osjeæaš.
{123635}{123690}Gdje su? - Što?
{123694}{123777}Vrpce koje si ukrala. | - Odustani. Gotovo je.
{124313}{124370}Natrag!
{124419}{124481}Gdje su vrpce?
{125741}{125801}Èuvaj je.
{126340}{126428}Dobro je. Daj to sada meni.
{127112}{127168}Ne!
{127256}{127313}Ne!
{127568}{127632}Bez brige, tebe neæu ubiti.
{127676}{127768}Nemoj! - Ne!
{127897}{127972}Nema puno vremena. FBI stiže.
{127993}{128060}Singletone, nije li ovo super?
{128271}{128381}Slušala sam tu vrpcu | kao i sve druge tvoje vrpce.
{128420}{128525}Sa slušalicama. | Pritisnula sam dugme,
{128566}{128673}i vidjela sam te... | u mojoj glavi.
{128754}{128813}Èula sam
{128839}{128937}svu nježnost | u tvom glasu. Ljubav.
{128968}{129063}A onda sam èula, Judith.
{129175}{129269}Preslušala sam sve | naše vrpce tebi.
{129274}{129368}Svi ti usamljenièki, | jadni... snovi.
{129387}{129464}O'Delle, gdje si? | - Na 12. katu.
{129480}{129539}Imala je pravo.
{129582}{129640}Moja baka.
{129673}{129766}Odgojila me. Znala je.
{129777}{129884}Rekla mi je da su | svi muškarci smeæe! Znojni.
{129890}{129963}Prljavi. Kukavice.
{129968}{130047}Mislila sam, ti si drukèiji.
{130052}{130148}Èuo si sve naše | tajne. Skrivene misli.
{130171}{130285}Otvorile smo ti srca; | a što si ti uèinio?
{130291}{130412}Èak i iz zatvora, | uspio si! Sjebao si nas!
{130444}{130523}A to boli.
{130558}{130651}Užasno boli.
{130700}{130822}Morala sam te zaustaviti. | Tvoji su otisci na pištolju.
{130907}{130982}Sad si nas sve ubio.
{131027}{131118}I ideš natrag u zatvor.
{132247}{132312}Stvarno sam te voljela.
{132548}{132662}I ja tebe. | Više nego što misliš.
{132710}{132804}To me ne opravdava. Nemoj.
{132884}{132944}Nemoj, Gloria.
{132972}{133033}U redu je.
{133129}{133190}Oprosti mi.
{134046}{134114}Stanite! - Daj!
{134124}{134226}Komu æe vjerovati, | tebi ili meni?
{134262}{134388}Ni makac! FBI! Baci oruž je!
{134393}{134483}Spusti, Darnell. | Gurni ga ovamo.
{134487}{134544}Polako.
{134657}{134770}Imam pištolj. | - Dolje! Licem dolje!
{134775}{134824}Ruke otraga!
{134827}{134884}Polako.
{134891}{134958}Makni je.
{134966}{135023}Imamo Darnella.
{135033}{135091}Dobro je!
{135099}{135190}Otvorile smo ti srca, | a što si ti uèinio?
{135227}{135328}Èak i iz zatvora, uspio si! | Sjebao si nas!
{135359}{135462}A to boli. Užasno boli.
{135495}{135560}Morala sam te zaustaviti.
{135563}{135632}Tvoji su otisci | na pištolju. - Ne!
{135750}{135870}Gnjido! Ubit æu te!
{135875}{135962}Ovamo! - Kretenu!
{135967}{136075}Jedna žrtva tu, | druga kod kasetofona.
{136265}{136322}Pomoæi æu vam.
{136371}{136437}Lita.
{137325}{137382}Imate posjet.
{137486}{137552}Tako mi svega.
{137585}{137644}K vragu sve. Doði!
{137649}{137744}Joj, oprosti! | Dobro si? Oprosti.
{137773}{137893}Nisu te uhitili? | - Agent Brinker ima veza.
{137911}{137991}Bilo mi je drago, | g. Darnelle. Èuvajte se.
{137997}{138096}Ag. Brinkeru. - Harvey. | G. Waveru. - Hvala.
{138304}{138368}Za sjeæanja, partneru.
{138525}{138619}Vidimo se. - Vidimo se.
{138663}{138718}Hortone!
{138723}{138785}Samo nešto...
{138860}{138918}Èuvaj se, profesore.
{139379}{139512}Jednom æemo se odvesti | na Slanu poljanu.
{139517}{139569}Samo nas dvoje.
{139574}{139634}S otvorenim krovom.
{139639}{139717}Sunce æe nam grijati lica.
{139723}{139797}Jurit æemo poput vjetra.
{139800}{139900}{C:$0000FF}{y:ib} d |{C:$FF0000}{y:b} d 
