{1}{1}25.000
{1883}{1953}Pasadena, | dom sitnih starica,
{1956}{2042}dobitnika Nobelovih nagrada, | znanosti i tehnologije
{2046}{2088}divnih muzeja,
{2091}{2166}i jednog ili dvojice | dobitnika Pulitzerove nagrade.
{2202}{2292}Dobro došli u grad u | kojemu ljudi još èitaju.
{2386}{2494}HITLEROVO DIJETE
{2956}{3016}Tražite nešto posebno?
{3037}{3064}Ne.
{3079}{3137}Volite trilere? | - Ne osobito.
{3156}{3211}Ovaj je prilièno dobar.
{3240}{3340}Nisam znala da je Hitler imao | djece. - Mi ne znamo za to.
{3343}{3461}No što ako je imao | dijete s Evom Braun?
{3489}{3566}I odgojili su ga | nacisti u Argentini.
{3569}{3628}Da poðe oèevim stopama.
{3693}{3739}To je baš smiješno.
{3748}{3821}To je pretpostavka, a | one smiju biti smiješne.
{3825}{3883}Hvala, ali tražit æu dalje.
{3886}{3951}Knjiga od 25 $ za 3,99 $.
{3954}{4018}Ne ako je ne kupim. | - Toèno.
{4086}{4127}Jeste li ovo vi?
{4178}{4286}Napisali ste ovu knjigu? | - Uzela mi je 7 g. Života.
{4287}{4349}No ne dajte da | to utjeèe na vas.
{4351}{4404}Biste li mi je potpisali?
{4456}{4499}Sigurni ste? | - Jesam.
{4543}{4605}Što da napišem? | - Vi ste pisac.
{4777}{4811}Hvala.
{4877}{4906}Uživajte.
{4911}{4967}Svakako hoæu. | - Molim vas.
{4970}{5020}Hvala. | - Hvala vama.
{5023}{5061}'Ðenja. | - 'Ðenja.
{5322}{5393}Ovo je prièa o Byronu Tilleru.
{5398}{5496}Skromnu èovjeku iz | skromne èetvrti u Pasadeni.
{5500}{5570}Èetvrti izgraðenoj za | obitelji srednje klase.
{5574}{5651}Dok je ona još bila | bliže vrhu nego dnu.
{5656}{5705}Pozdravi mamu. | - Bok, deèki.
{5709}{5741}Bok. Kako ste?
{5745}{5784}Trebaš pomoæ? | - Ne.
{5789}{5832}Danas sam prodao knjigu.
{5835}{5866}To je dobro.
{5871}{5958}Nisam izraèunao, no mislim | da æemo dobiti 3 centa.
{5961}{6004}Porez æe nas uništiti.
{6007}{6095}Dušo, važno je da | ljudi još èitaju tvoje radove.
{6101}{6153}Bio sam kod Rizzolija.
{6166}{6226}U poèetku je nisam | pronašao. No bila je ondje.
{6231}{6315}Sedam godina moga života | u kutiji s ostacima.
{6318}{6420}S kuharicama, knjigama o | samopomoæi i postizanju orgazma.
{6423}{6530}Ne srami se ako ljudi | žele platiti za orgazme.
{6534}{6605}Što je ovo? | - Koje?
{6607}{6641}Heinz je umro?
{6645}{6708}Rade 57 okusa keèapa, a mi | si ne možemo priuštiti jedan?
{6711}{6762}Zašto platiti više za marku?
{6766}{6854}Koliko pelena Nathaniel | još potroši na tjedan?
{6857}{6977}Ovisi o tome proguta | li hranu ili je ispljune.
{6987}{7053}Kad æe ozbiljno | shvatiti kontrolu mišiæa?
{7081}{7127}Mislim s 3 g.
{7130}{7253}Onda je bolje da mi novu | knjigu objave... Brzo.
{7347}{7430}Ne želim da se bilo | kada brineš za bilo što.
{7454}{7544}Sada spavaj, | Nathaniele Hawthorne Tilleru.
{7554}{7589}Volim te.
{7673}{7767}Što radiš ondje? | - Okreæem mu glavu.
{7771}{7837}Da se ne spljošti | na jednoj strani.
{7840}{7912}Okoštala je prije | 2 g. Doði u krevet.
{7915}{7954}Da doðem u krevet?
{7979}{8074}O èemu su muškarci razgovarali? | - Uglavnom o pravnim fakultetima.
{8077}{8141}Mislim da naginje na Duke. | - To je dobra škola.
{8144}{8243}I on to misli. - Ako ne želi biti | odvjetnik? - Nitko to ne želi.
{8246}{8315}Zato rano posadiš to sjeme.
{8330}{8381}Što ako želi biti pisac?
{8386}{8478}Ako ne dopustimo da mu se | glava spljošti, neæe se dogoditi.
{8481}{8576}Ti nemaš plosnatu glavu. | - Možda ne izvana.
{8581}{8620}Dušo? | - Molim?
{8643}{8708}Bog ti je dao dar.
{8725}{8792}Sjeæaš se što je | pisalo u Newsweeku?
{8795}{8879}"Reèenice Byrona Tillera | živahne su i pune boje.
{8883}{9015}Hitlerovo dijete originalno | je kao rijetko koji triler."
{9020}{9090}Mislim da je pisalo | "Rijetko se vidi u trilerima."
{9093}{9139}A što je pisao Times?
{9144}{9195}Podsjeti me.
{9256}{9324}Spominjao je nešto | o meni i Hemingwayu.
{9328}{9362}Da? | - Jest.
{9365}{9432}Zaboravila sam. | - Doista? Zaboravila?
{9435}{9531}Možda ti trebam | osvježiti pamæenje.
{9582}{9652}Osvježavam. Evo.
{9735}{9777}O, moj Bože!
{9931}{9995}Kao Hemingway...
{10011}{10070}Oblikuje reèenice...
{10125}{10208}okom rezaèa dijamanata.
{10268}{10346}Ostavlja najbolje | i najblistavije.
{10368}{10423}Gospode, dobar si.
{10426}{10476}Ne èujem te!
{10512}{10574}Rekoh da si dobar.
{10630}{10718}Nije sigurno je li žena | govorila Bogu ili Bryanu,
{10721}{10809}no èinilo se da ima više | nego dovoljno osnova za to.
{10812}{10878}To mi je privuklo pozornost.
{10881}{10945}Smještena izmeðu | holivudskih porno duæana,
{10948}{11028}duæana s novotarijama | i scijentoloških duæana,
{11033}{11137}izmeðu tonskih studija èiji | su zlatni dani odavno prošli,
{11139}{11234}scenarista po kojima ne | snimaju i ugovori su im istekli,
{11237}{11325}te loših glumaca koji | poduèavaju druge loše glumce
{11328}{11414}koji sanjaju da æe | jednoga dana proæi audiciju
{11419}{11494}sjedio je Byron Tiller | koji je donedavno vjerovao
{11497}{11612}da je pisanje romana koje nitko | ne želi èitati pravi posao.
{11622}{11675}Prodaj se, dušo, prodaj se.
{11691}{11785}Ciljevi postaju manje | uzvišeni kad trebaš novac.
{11798}{11838}Hitno.
{11847}{11895}U redu? | - Hvala.
{11907}{12002}Savršen èovjek za | Elizejske poljane.
{12620}{12725}Poslao sam ti ovaj jer | ste mi izdali i prošli.
{12761}{12867}Nisam htio razbiti | dobitnièku kombinaciju.
{12915}{12968}Piškotu? | - Ne, hvala.
{12976}{13077}Treba ga malo popraviti, | no zato si ti urednik.
{13090}{13216}Ekskalibur je èudesan maè | kad se svi ti ubijaju radi njega.
{13230}{13320}To je maè koji je kralj | Artur izvadio iz kamena.
{13338}{13392}Znam pozadinu. | - Dakako.
{13395}{13489}Neumjestan je u prièi | o radnicima migrantima.
{13506}{13562}Ekskalibur je simbol.
{13617}{13640}Simbol.
{13644}{13761}Predstavlja nade | i snove o buduænosti.
{13766}{13836}Radnici migranti | su mikrosvemir.
{13841}{13895}Nisu li uvijek?
{13906}{13975}U tome je problem.
{13990}{14072}Koji? - Odat æu ti | tajnu o mikrosvemirima.
{14079}{14153}Ljudi ih mrze. | - Nisam to znao.
{14161}{14232}Tko želi sjediti u | autobusu i èitati knjigu
{14236}{14300}koja ti govori da | si dio mikrosvemira?
{14305}{14374}Zna to. Ogleda se i zna.
{14388}{14443}Simbolizam je još gori.
{14447}{14512}Jadnik želi da | mu sve to narišeš.
{14515}{14618}Nitko ne želi gubiti | vrijeme tražeæi smisao.
{14623}{14721}Moja žena misli da je to | najbolje što sam ikad napisao.
{14743}{14799}Zacijelo te jako voli.
{14910}{15032}Uvijek sam bio otvoren | za sve kreativne promjene.
{15046}{15122}To ne bi bilo pošteno | prema tebi. - Bilo što.
{15165}{15217}Možda iduæi put.
{15311}{15382}Mogu li dobiti predujam? | - Za što?
{15389}{15481}Za slijedeæu. | - Znaš da bih rado, no...
{15512}{15590}Znam da moji | problemi nisu tvoji.
{15642}{15713}Ali nemam više od èega živjeti.
{15742}{15800}Doista si tako oèajan? | - Jesam.
{15837}{15906}Onda iskoristi taj osjeæaj.
{15931}{16015}Svi najbolji romani | napisani su u oèaju.
{16128}{16197}I najbolje samoubilaèke poruke.
{16240}{16346}Misliš da tipa u odijelu | zanimaju radnici migranti?
{16351}{16440}Pa što ako se uredniku nije | svidjela? Evo ti moj savjet.
{16453}{16493}Jebeš njega.
{16522}{16616}Hvala, Harry. | To je divan poticajan govor.
{16693}{16728}Zdravo.
{16769}{16831}Kako ste? | - Nismo se upoznali.
{16843}{16874}Nismo.
{16879}{16957}Ja sam Luther Fox. | - Byron Tiller.
{16969}{17017}Znaèi, pisac ste?
{17059}{17094}Tako je.
{17100}{17140}Èuo sam za što?
{17144}{17193}Iskreno sumnjam.
{17200}{17296}Objavio sam sitno sranje | po imenu Hitlerovo dijete.
{17309}{17349}Svidjelo mi se.
{17387}{17452}Proèitali ste je? | - Doimate se iznenaðeni.
{17455}{17525}Nikad nisam upoznao | svoju publiku.
{17534}{17576}Evo me.
{17654}{17756}Na èemu sada radite? | - Imam neke zamisli.
{17804}{17899}Mislim da bih bio dobar tipkaè.
{17904}{17959}Malo je teško, je li?
{17962}{18044}Hemingway se ubio i ljudi | su kupovali njegove knjige.
{18046}{18118}Ja sam u jebenoj | kutiji s ostacima.
{18121}{18236}Teško je tu kutiju ne | smatrati vrstom propasti.
{18240}{18305}Mislim da radite od muhe slona.
{18307}{18404}Problem je što se | moj slon pretvorio u muhu.
{18409}{18465}I ako nisi obitelj...
{18507}{18552}Muha...
{18571}{18619}Kako onda živiš?
{18621}{18722}Možeš uzdržavati obitelj ako | si spreman uèiniti što treba.
{18753}{18799}Moram iæi.
{18834}{18931}Hvala na piæu i | što ste me slušali.
{18963}{19050}Ako ne dobijete | posao tipkaèa, dajte...
{19064}{19158}Navratite do ureda | i možda nešto smislimo.
{19168}{19247}Ništa nije bolje od | malo životnog iskustva.
{19394}{19474}ELIZEJSKE POLJANE | Uvijek na usluzi
{19685}{19764}Što je urednik rekao? | - Zašto ne spavaš?
{19769}{19836}Nisam mogla doèekati | da vidim što je rekao.
{19839}{19894}Vidi mjesta za promjene.
{19897}{19944}Ali svidjelo mu se?
{19970}{20036}Ne znam. To je relativna stvar.
{20039}{20094}U odnosu na što?
{20097}{20163}Jesi li John Grisham ili nisi.
{20166}{20251}Sa mnom nisu | pretjerano srdaèni.
{20300}{20354}Objavit æe ga, zar ne?
{20441}{20462}Hoæe.
{20487}{20543}Je li rekao kada?
{20546}{20593}Ne, to radi planski.
{20598}{20678}Na drugoj strani | zgrade. Saznat æu.
{20797}{20882}Rekla sam ti da æe sve | biti u redu, nisam li?
{21041}{21098}Paul Pearson!
{21118}{21197}Mislio sam da si ti. | - Drago mi je što te vidim.
{21200}{21263}Takoðer. | - Dobro ti ide otkako si otišao?
{21267}{21329}Sjajno. Objavio | sam prvi roman.
{21334}{21364}Èuo sam.
{21367}{21470}Htio sam ga proèitati, no nisam | našao knjižaru koja ga drži.
{21476}{21515}Kako je u uredu?
{21519}{21602}Znaš kako je s reklamom. | Svaki se dan pomalo ubijamo.
{21607}{21683}Nedostaje mi. Akcija, rokovi.
{21686}{21737}Jak adrenalinski naboj.
{21739}{21826}Razmišljam o tome da se | vratim ako su okolnosti prave.
{21834}{21943}Rekao si mi da se jebem. | - To je adrenalin govorio.
{21956}{22024}Doista bi se vratio? | - Bih.
{22025}{22075}Plaæa bi bila manja. | - Dakako.
{22081}{22147}Usrani klijenti. | - Sto god odluèiš.
{22152}{22195}To je dobar stav.
{22200}{22287}Zašto ga nisi i prije imao? | - Malo sam odrastao.
{22290}{22344}Drago mi je što to èujem.
{22348}{22419}Dobro. Hvala. | Vidimo se ujutro?
{22423}{22516}Zapravo, mislim da bi | bilo bolje da se jebeš.
{22551}{22595}Èestitam. | - Hvala.
{22598}{22652}Došli ste proslaviti. | - Gdje bismo drugdje?
{22657}{22747}Dvoje mojih omiljenih ljudi. | Poslat æu svoje najbolje...
{22750}{22822}Nije potrebno. | - Moj dar vama.
{22825}{22872}Jako velikodušno.
{22970}{23069}Nemoj se ljutiti, no trebamo | pozajmiti novac od mojih.
{23081}{23188}Tvoj me otac mrzi. | - Razlog više da nam dâ zajam.
{23200}{23254}Osjeæat æe se nadmoæniji.
{23260}{23373}Ne želim mu pružiti zadovoljstvo. | - Znaš da nikad nije zadovoljan.
{23391}{23491}A kad ti objave roman, | vratit æemo mu s kamatom.
{23632}{23721}Misliš li da ti je otac | imao pravo? - Glede èega?
{23724}{23770}Možda jesam propalitet.
{23902}{23980}Ti me voliš i misliš | da æe sve biti u redu.
{23983}{24028}Dakako.
{24121}{24201}Bezuvjetna ljubav | može biti prava gnjavaža.
{24220}{24256}Bok.
{24327}{24399}Volim te. | - Vidimo se poslije posla.
{24426}{24487}Što bi sada, frajeru?
{24499}{24559}Idemo malo do parka?
{24619}{24671}Težak jebeni posao.
{24674}{24765}Napišeš Ilijadu i tko zna | hoæe li je tko kupiti.
{24770}{24813}Recimo tvoja posljednja knjiga.
{24817}{24882}Dobra kritika u Timesu.
{24886}{24946}Ništa nisi zaradio, zar ne?
{24950}{25022}Tako nekako. | - Kakav je to posao?
{25026}{25109}Moraš se upitati što | je Guttenberg mislio.
{25112}{25209}Zabole me jedna stvar što | je mislio. Dosta sranja.
{25212}{25266}Trebaš novac, zar ne?
{25295}{25335}Da, pozajmicu.
{25342}{25413}Mnogo sam razmišljao o tome.
{25421}{25490}I neæu ti pozajmiti novac.
{25493}{25555}Zašto? | - Što je ono Shakespeare rekao?
{25557}{25638}Pozajmice ne uzimaj niti ne daj.
{25641}{25732}Ovdje sam jer sam obeæao | vašoj kæeri da æemo se naæi.
{25735}{25813}I zabiti vam jezik u guzicu.
{25816}{25879}Obavio sam što sam trebao.
{25887}{25978}Znamo da nikad neæeš | moæi uzdržavati obitelj!
{25983}{26029}Razmisli o tome!
{26533}{26618}ELIZEJSKE POLJANE
{26772}{26821}Bok, kako ste?
{27164}{27193}Da?
{27201}{27229}Bok.
{27247}{27310}Je li g. Luther Fox tu?
{27313}{27372}Ovo je tu. Vidite li ga?
{27396}{27491}Ne. Recite mu da ga | je tražio Byron Tiller.
{27505}{27569}Byron Tiller, pisac?
{27597}{27649}Èuli ste za mene? | - Svakako.
{27663}{27730}Neki dan od Luthera.
{27775}{27809}Pa da.
{27835}{27900}Moja se slava širi.
{28235}{28290}Pretpostavio sam da ste tu.
{28305}{28367}Nohra mi je rekla da ste bili.
{28371}{28428}Ne voli baš ljude, je li?
{28431}{28525}Poznajem je 6 g. I | jedino što znam da voli
{28528}{28622}jesu ljubavni romani | i bomboni s grožðicama.
{28625}{28671}Nije baš neki ured.
{28674}{28782}Nije to toliko ured koliko | mjesto za preuzimanje poruka.
{28821}{28898}Tako je. Neki dan | spomenuli ste
{28901}{28988}da možda imate nešto | za mene pa sam svratio.
{29000}{29058}Doðite i razgovarat æemo.
{29074}{29102}Može.
{29151}{29240}Jedini drugi posao bio mi | je u reklamnoj agenciji.
{29243}{29302}Neæe me primiti natrag.
{29324}{29400}Bio sam u agencijama za | zapošljavanje i rekli su mi
{29403}{29478}da nisam opremljen | da bilo što drugo radim.
{29507}{29576}Kakvim se poslom vi bavite?
{29602}{29673}Elizejske poljane | su eskort služba.
{29834}{29871}Eskort služba.
{29922}{29958}Eskort služba.
{29975}{30101}Stojite na uglu | u kaubojskim šeširima...
{30118}{30176}Ne, nismo kurve.
{30198}{30321}Pomažemo usamljenim ženama | koje trebaju utjehu.
{30348}{30415}Žene. | - Èesto samo kao prijatelji.
{30420}{30499}Samo žene? | - Staromodan sam.
{30539}{30631}Mislili ste da bih | ja bio za taj posao?
{30649}{30722}Zgodni ste, | obrazovani, suosjeæajni.
{30728}{30808}Suosjeæajan? | - Proèitao sam vaš roman.
{30812}{30886}Suosjeæanje mu je | najjaèa strana. - Hvala.
{30889}{30948}Iako je premisa bila drek.
{31036}{31144}Da ste proèitali omot, znali | biste da imam ženu i dijete.
{31174}{31239}Tim bolje. | - Kako to?
{31242}{31305}Profesionalci smo. | Obitelj kod kuæe
{31310}{31424}zapreka je emotivnim | vezama s klijentelom.
{31425}{31462}I vi imate obitelj?
{31466}{31544}Nisam te sreæe. No | mnogi je zaposlenici imaju.
{31545}{31606}Ne glumim moralistu,
{31610}{31710}no ne sramite li se | zbog toga što radite?
{31720}{31775}Ne, siromaštvo to èini.
{31818}{31909}Ono što predlažem može | biti kratko koliko god želite.
{31912}{31987}Samo da prebrodite | ovu sušu u životu.
{31993}{32032}Privremeno.
{32799}{32827}Zdravo.
{32865}{32898}Kako ste?
{32924}{32978}Bio sam u prolazu. | Htio sam zahvaliti...
{32981}{33027}Zahvalili ste sinoæ.
{33033}{33096}Ne sjeæam se. | - Ja da.
{33099}{33175}Nije lako biti pristojan | kad si sklon samoubojstvu.
{33177}{33257}Jako me se dojmilo. | Moram se javiti na ovo.
{33291}{33343}Još jedanput... | - Ne, ne, uðite.
{33375}{33436}Sigurno? | - Apsolutno.
{33559}{33639}Nisam znao da ste se | vratili, gðo Hardwick.
{33642}{33676}Uði.
{33693}{33791}Piše da ste trebali biti | u Indiji još mjesec dana.
{33825}{33885}Znam. Curry to èini.
{33923}{34012}Ali vi uvijek | izgledate divno. Naravno.
{34086}{34181}Ne znam mogu li što | u tako kratkome roku.
{34232}{34299}Koliko ste dlakavi po tijelu?
{34303}{34372}Molim? | - Koliko ste dlakavi?
{34374}{34422}Dlakav po tijelu? Zašto?
{34426}{34498}Koliko plaæaju, imaju | pravo biti izbirljive.
{34502}{34574}Nazvat æu vas oko 17 h, može?
{34579}{34631}Do tada æu nekoga naæi.
{34635}{34717}'Ðenja, gðo Hardwick. | Ionako nije za tebe.
{34722}{34844}Moram priznati da sam | razmišljao o tvome prijedlogu.
{34847}{34895}Igraš li tenis?
{34898}{34958}Loše. | - Fino. Ona mrzi gubiti.
{34962}{35038}Tko to? | - Žena Franklina Bucknera.
{35042}{35133}Probdio sam cijelu | prošlu noæ i mislio...
{35137}{35244}Gða Loretta Forbes iz Encina. | 46 g. Voli operu i balet.
{35248}{35302}O tome sam mislio.
{35306}{35434}Možda nešto privremeno. | Poput opere, tenisa, baleta.
{35439}{35508}Ali ne... Znaš.
{35574}{35621}Samo ne želim da...
{35673}{35717}Pa, znaš...
{35729}{35793}Znaš, ono ondje.
{35939}{36056}Možda je ovo loša zamisao. | - Loša je samo ako ne uspije.
{36091}{36231}Možda mi uspiješ naæi staricu | koja treba partnera za bridž.
{36281}{36329}Byrone. | - Molim?
{36332}{36389}I ja sam prvi | put imao tremu.
{36394}{36499}Zato ti moramo naæi nekoga | s kime æeš se dobro složiti.
{36502}{36612}Ako ne možemo ponuditi | pravu ljubav, možemo simetriju.
{36628}{36697}Morat æeš skinuti | vjenèani prsten i naoèale.
{36701}{36748}Luthere...
{36782}{36848}Cijenim sve što si uèinio.
{36853}{36948}Još nisam uèinio ništa. | - Možda je tako najbolje.
{36951}{37078}Andrea Allcott, 35 godina. | Karizmatièna. Lice anðela.
{37086}{37189}Imate mnogo toga zajednièkog. | I muž joj je romanopisac.
{37192}{37246}Kao i ti. | - Sjajno.
{37250}{37347}Možda si èuo za njega. | Tobias Allcott.
{37364}{37443}Dobitnik Pulitzerove nagrade?
{37460}{37501}Mislim da je osvojio tri.
{37505}{37617}No "dobitnik Pulitzerovih | nagrada" zvuèi gotovo pohlepno.
{37625}{37762}Na studiju sam odslušao | semestar o njegovu pisanju.
{37765}{37809}Da? Koliko si dobio?
{37832}{37874}+4.
{37911}{37984}Možda trebaš obnoviti znanje.
{38501}{38571}Dušo, jesi li | vidio moju naušnicu?
{38624}{38668}Zar si je progutao?
{38714}{38783}Osjeæam dobre | stvari o ovome tipu.
{38787}{38845}Uvijek si imao instinkt za to.
{38860}{38907}Jesam, zar ne?
{38934}{38995}Zacijelo mnogo obeæava.
{39018}{39112}Kad je Picassov uèitelj crtanja | vidio njegove prve škrabotine
{39115}{39183}zacijelo je osjetio | nešto osobito.
{39197}{39281}Tako sam se ja osjeæao | kad sam upoznao tebe.
{39286}{39372}Dušo, beznadno si romantièan.
{39375}{39468}Pun nade. To je mnogo gore.
{39511}{39547}Kasno je.
{39594}{39649}Hajdemo onda nešto raditi.
{39660}{39717}Ne, George me oèekuje.
{39731}{39793}Hajdemo slaviti.
{39812}{39875}Nije li malo prerano?
{39904}{40001}To je najbolje vrijeme za | slavlje, dok se ne pokvari.
{40005}{40046}Bez brige.
{40050}{40089}Neæe.
{40241}{40273}Izvoli.
{40282}{40321}Što je to?
{40327}{40401}Èek za prošli | mjesec. Zaboravila sam.
{40444}{40478}I ja.
{40536}{40581}Bok.
{40748}{40791}Izlaziš?
{40811}{40852}Nisam ti rekao? | - Nisi.
{40856}{40914}Imam sastanak s izdavaèima.
{40918}{40969}Ovako kasno? | - Piæe i veèera.
{40974}{41003}Zašto?
{41007}{41077}Prerano je govoriti o tome. | - Meni nije.
{41081}{41131}Znaš da sam praznovjeran.
{41151}{41189}Nisi.
{41232}{41295}U dobrim stvarima jesam.
{41333}{41447}Nisi primijetila jer u posljednje | vrijeme nije bilo dobrih stvari.
{41634}{41709}I zbor | Knjiga mjeseca
{41720}{41804}Žele da se naðem s | ljudima iz Knjige mjeseca.
{41807}{41864}Bože! Doista? | - Nema jamstava.
{41867}{41924}Nema, dušo! Ali to je divno!
{41927}{42039}Mislim da me pokušavaju | ugurati. U veljaèi.
{42047}{42151}Da bar imaš | nešto ljepše odjenuti.
{42185}{42275}To je samo veèera. | Stol æe skrivati veæi dio.
{42279}{42385}Naruèi jastoga ako imaju. | Bit æeš prekriven ubrusom.
{42675}{42720}Moram iæi.
{42732}{42806}Želim èuti sve kada doðeš doma.
{44054}{44102}Ti si zacijelo novi.
{44106}{44136}Jesam.
{44154}{44196}Nigel Halsey.
{44216}{44249}Byron.
{44252}{44298}Da. Pisac.
{44318}{44374}Ostavio si dojam na gazdu.
{44388}{44448}Vidim da te vodio u Dunhill.
{44469}{44507}Da vidimo.
{44512}{44552}Bože, ne opet ona.
{44556}{44648}Ne reci klijentici da ima lijepu | guzu. Morat æeš ponavljati.
{44664}{44707}Hoæeš li...
{44716}{44770}Bulgari za veèeras?
{44779}{44851}Ne, uzmi ga ti. | - Hvala.
{44900}{44961}Jesi li ovo radio i prije?
{45005}{45076}Nisam. | - Kao da silaziš s trupca.
{45080}{45155}Samo nemoj siæi | dok ona ne završi.
{45163}{45280}Luther je rekao da | one ne žele uvijek...
{45333}{45418}Da, tako je. | No, naviknut æeš se.
{45423}{45544}Kad zatraže da ih zagrliš, | shvatiš da je sve sranje.
{45548}{45625}Ali koji posao to nije? | Možeš prodavati rabljene aute.
{45630}{45744}Bar dobiju što su platile. | Bez brige, snaæi æeš se.
{45756}{45869}Bogate kuje žele samo | malo društva i seksa.
{45912}{46004}Mi smo poput | kokera kojemu se digao.
{46040}{46118}Imat æu tu sliku u mislima. | - Dobro.
{46587}{46615}Halo?
{46621}{46667}Zdravo, ja sam.
{46682}{46722}Nešto nije u redu?
{46733}{46820}Ma ne. Samo sam... Imam...
{46837}{46905}Došlo mi je da | ti kažem da te volim.
{46909}{46952}I ja volim tebe.
{46986}{47048}Zašto? | - Znaš zašto.
{47133}{47177}Želim to èuti.
{47200}{47251}Zato što si...
{47256}{47352}Pametan, zabavan, | obziran.
{47357}{47429}Dena...
{47433}{47530}Ne sjeæam ništa od toga.
{47550}{47621}Byrone, samo imaš tremu.
{47627}{47682}To je dobro. Znaš zašto?
{47696}{47725}Zašto?
{47733}{47831}Jer æu ja ovdje | vjerovati u tebe, dobro?
{47929}{47966}U redu.
{48187}{48254}Svatko prvi put ima tremu.
{48256}{48342}Za Byrona je bilo bitno | da upozna nekog divnog.
{48345}{48401}Nekoga poput Andree Allcott.
{48404}{48481}Koja je doista | imala lice anðela.
{48485}{48537}I ne samo lice.
{48540}{48614}Plastièni kirurzi zaraðuju | dovoljno da kupe jahtu
{48617}{48680}preraðujuæi prirodu | da izgleda ljepše.
{48684}{48772}To nije bio bilo | kakav obièan anðeo.
{48775}{48869}Ovim je, siguran sam, | Bog osobno upravljao.
{49002}{49073}Vi ste zacijelo èovjek | iz Elizejskih poljana.
{49182}{49212}Jesam.
{49698}{49810}Mrzim iæi sama na ovo. Izvukla | bih se, ali dobrotvorno je.
{49824}{49919}Nadajmo se da æe, što | god bilo, brzo naæi lijek.
{50474}{50532}Što biste sada željeli?
{50537}{50577}Jeste li gladni?
{50581}{50618}Ne baš.
{50632}{50694}Zapravo, rado | bih pojela piškotu.
{50699}{50774}Jednu piškotu. | - Svakako.
{50832}{50887}Koliko? | - Dva dolara.
{50907}{50946}Èujte... | - Hvala.
{50949}{51010}Mogu dobiti raèun? | - Ne.
{51030}{51083}Izvolite. | - Hvala.
{51114}{51222}Ne morate zahvaljivati, | to je poslovni trošak.
{51254}{51357}Došli smo do pitanja, koje | ne znam trebam li postaviti.
{51377}{51483}Pitanje je vaše pravo. | Moje je da ne odgovorim.
{51532}{51624}Zašto veèeras niste | došli s prijateljem?
{51718}{51744}U redu.
{51771}{51862}I zašto netko poput vas | treba nekoga poput mene?
{51868}{51945}Za neke prilike | žena treba pratitelja.
{51950}{52008}Da, ali mislio sam...
{52031}{52102}Da bi vam bilo | lako pronaæi pravog.
{52104}{52157}Niste li vi pravi?
{52160}{52250}Mislio sam na nekoga | koga ne treba naruèiti.
{52328}{52370}Udana sam.
{52401}{52461}To nije uvijek zapreka.
{52487}{52549}Veoma volim muža.
{52580}{52625}To je veoma lijepo.
{52658}{52715}I mi tako mislimo.
{52743}{52804}Možete dalje taksijem?
{52852}{52887}Mogu.
{52902}{52952}Laku noæ, g. Tiller.
{53098}{53139}Laku noæ.
{53641}{53752}Ako možete odmah poslati | èek, bio bih vam zahvalan.
{53779}{53833}Da. Hvala. Zbogom.
{53870}{53942}Zašto im je teško | namiriti èekove?
{53944}{54002}Kao da je dobro kad ne plate.
{54005}{54051}Vidio sam te sinoæ. | - Da? Gdje?
{54054}{54110}Na koncertu. | - A, da.
{54130}{54181}Veoma je privlaèna.
{54183}{54252}Jennifer Adler. | Godinama je klijentica.
{54255}{54341}Ostala je jedina kojoj | se osobno posveæujem.
{54344}{54419}Da nema nje, | odavno bih se povukao.
{54422}{54502}Mislim da æu se ja povuæi sada.
{54532}{54572}Veæ?
{54576}{54671}Da, nisam siguran | da sam stvoren za ovo.
{54682}{54746}Sumnjaš u moje instinkte?
{54751}{54786}Ne.
{54789}{54877}Onda se nadam da voliš | eksperimentalno kazalište.
{55332}{55389}Mrzim gledati ovo sama.
{55459}{55540}Izvukla bih se... | - Da pogodim. Dobrotvorno?
{55740}{55833}Imao sam takvo što | na komandnoj ploèi auta.
{55941}{55981}Pa...
{56098}{56158}Jeste li za piškotu?
{56454}{56520}Želite da ovaj put uðem?
{56523}{56581}Ako želiš.
{56593}{56661}Ako ne, èek neæe imati pokriæe?
{56682}{56721}Možda.
{56723}{56791}Kamo, milostiva? | - U Pasadenu.
{57209}{57241}Hoæete?
{57250}{57283}Ne, hvala.
{57398}{57481}Èesto izlazite? | - Ne preèesto.
{57513}{57616}Prijatelje imam po mužu, | a veæina je mrtva.
{58041}{58101}Da vas otpratim do vrata?
{58115}{58161}Bilo bi pristojno.
{58339}{58394}Hvala, Phillipe. | - Laku noæ.
{58399}{58423}Hvala.
{58459}{58502}Volite li vruæi kakao?
{58562}{58649}S mlijekom ili vodom? | - S mlijekom, dakako.
{58691}{58769}Što biste da sam | rekla da je s vodom?
{58772}{58838}Molio bih se da ima | sljezovih kolaèiæa.
{58978}{59013}Slasno.
{59017}{59122}Nisam bila sigurna za mlijeko. | Inaèe spremam samo jedan.
{59126}{59197}Muž vam ne voli vruæ kakao?
{59235}{59298}Ima dijabetes.
{59322}{59433}Doimate se mlado da budete | u braku nekim poput njega.
{59481}{59534}U poèetku nije bilo bitno.
{59603}{59667}No posljednjih | nekoliko godina...
{59681}{59758}Siguran sam da | mu je teško kao piscu.
{59776}{59869}Što vi znate o tome? | - I ja pomalo pišem.
{59934}{60002}Doista? | - Da, doista.
{60019}{60062}Iznenaðeni?
{60075}{60129}Zapravo i nisam.
{60140}{60248}Niste tip kojeg zadovoljava | vucaranje s usamljenim ženama.
{60271}{60320}Znaèi, usamljeni ste?
{60323}{60435}Ništa nije više usamljenièki | od gledanja voljenog kako umire.
{60536}{60654}"Smrt, jedini besmrtnik | koji nas sve tretira jednako.
{60656}{60764}Èiji su sažaljenje, mir | i utoèište za svakoga."
{60843}{60903}Veoma lijepo. | - Mark Twain.
{60948}{61009}Stvarnost je manje poetièna.
{61192}{61237}Žao mi je.
{62286}{62379}Zdravo, dragi. Zašto | si tako kasno budan?
{62383}{62433}Zaboravio sam uzeti insulin.
{62438}{62494}Ali inaèe si dobro?
{62516}{62571}Da, dobro sam.
{62635}{62703}Želim da upoznaš Byrona Tillera.
{62766}{62795}Byrone?
{62846}{62880}Byrone?
{63024}{63059}Zdravo.
{63109}{63149}Gospodine.
{63152}{63226}I Byron je pisac. | - Ma stvarno?
{63273}{63361}Da, pomalo pišem. | Nisam u vašoj klasi.
{63366}{63436}Bar je to utješno.
{63456}{63528}Želiš li jesti? | - Ne, hvala.
{63531}{63607}Nastavite s time što radite.
{63665}{63724}Èast mi je upoznati vas.
{63733}{63810}Htio sam odgovoriti, | "I meni je zadovoljstvo."
{63814}{63904}No to bi bilo luckasto, zar ne?
{63954}{63991}Laku noæ.
{64129}{64171}Sranje.
{65420}{65465}Byron Tiller.
{65506}{65573}Ti nadahnjuješ.
{65948}{65999}'Jutro. | - 'Jutro.
{66059}{66102}Dobro si spavao?
{66107}{66148}Nisam oka sklopio.
{66151}{66233}Ni ja. Èini se | da nas muèi nesanica.
{66236}{66323}Lottie me pokrenula jakom kavom.
{66327}{66406}Nemoj mu davati lonèiæ, | nije putujuæi trgovac.
{66432}{66524}Ne, nisam gladan, hvala. | - To nije za vas!
{66643}{66713}G. Allcott želi da | mu doneseš doruèak.
{66719}{66773}Ja? Zašto?
{66782}{66845}Iskrsnut æe u razgovoru.
{67446}{67481}Uði. Uði!
{67506}{67553}Èuo sam kako tipkate.
{67556}{67648}Nisam htio smetati. | Doruèak vam se hladi.
{67676}{67768}Ionako nema veze. | Ne smijem ga pojesti.
{67805}{67876}Samo meko kuhano jaje.
{67887}{67973}Ostalo je za ukras | da se ne osjeæam loše.
{67980}{68078}Završit æu u pseæoj zdjeli. | - U redu. U slast.
{68090}{68152}Sinoæ ste se dobro proveli?
{68189}{68296}Sve je u redu. | Ima moj blagoslov.
{68307}{68407}Muškarac se treba pobrinuti | da mu je žena zbrinuta.
{68425}{68482}Kako god može. | Ne slažete se?
{68488}{68532}Da, veoma. Gospodine.
{68535}{68621}Možda sam pogriješio | oženivši se mlaðom.
{68624}{68711}No do prije nekoliko | godina bio sam snažan.
{68717}{68829}Èuo sam sve prièe. | - Vjerujte samo u nevjerojatne.
{68832}{68947}Imao sam sreæu što | sam živio bez granica.
{68984}{69087}No na kraju samo Bog to može.
{69124}{69232}Genij treba imati povlastice | koje obièni ljudi nemaju.
{69258}{69321}Mislite da sam genij? | - Da, gospodine
{69371}{69429}Vjerojatno imate pravo.
{69462}{69501}No i to...
{69531}{69600}S vremenom postane teret.
{69602}{69729}U vašim godinama, iz | mene su curile zamisli.
{69742}{69874}Sad ih istiskujem kao | prdce kako bih ih spojio.
{69918}{69985}Vjerojatno sušno razdoblje. | - Suša!
{69987}{70098}To se dogaða samo u | sredini života, ne na kraju.
{70125}{70248}Ali i sada radite. | - Trebalo mi je 12 g. Za to.
{70251}{70376}Ureðivao sam malo, | ubijao nepotrebne pridjeve.
{70386}{70457}Jedva èekam da to objave.
{70460}{70579}Da, mislim da ni | ja to neæu moæi èekati.
{70584}{70707}Svi su mi se organi okrenuli | protiv mene, gadovi mali.
{70799}{70853}Biste li željeli to proèitati?
{70961}{71031}Doista? | - Da. Pisac ste.
{71048}{71130}Želio bih mišljenje | još jednog profesionalca.
{71351}{71406}Moja žena misli da je divno. | - Da.
{71410}{71562}Ali žena mi je, a u ljubavi | ne vjerujte sustavu vrijednosti.
{71758}{71820}Što radiš? | - Èitam.
{71837}{71926}Dobio sam najnoviji | rukopis Tobiasa Allcotta.
{71944}{72013}Vrijedi li što? | - Ništa ne vrijedi.
{72018}{72091}Onda ostavi to i | obrati pozornost na mene.
{72094}{72176}Vrijeme je da provedeš veèer | sa ženom umjesto s urednikom.
{72181}{72219}Spreman?
{72244}{72271}Jesam.
{72514}{72584}Što misliš? | - Jako lijepo.
{72591}{72702}Potrošila sam previše, no trebaš | odijelo sada kad si veliki pisac.
{72705}{72768}Odakle ti novac? | - Tata je poslao 1000 $.
{72771}{72840}Neæe dati više dok se | ne isprièaš. - Neæu.
{72843}{72948}Rekla sam mu da æe se prije | pakao smrznuti. Daj mu vremena.
{72960}{73008}Piše baš...
{73058}{73155}Ovdje, da je izraðeno | od 80% dobrih stvari.
{73181}{73273}I 20% jeftinijih | tako da se i ne vidi.
{73295}{73382}I rekla sam da | malo napuste meðunožje.
{73389}{73434}U redu.
{73477}{73529}Sviða ti se?
{73552}{73617}Da, oduševljen sam.
{73620}{73725}Rekla sam prodavaèu | da je za slavnoga romanopisca.
{73728}{73793}Kojega traži | klub Knjiga mjeseca.
{73797}{73842}Dena, rekao sam ti...
{73864}{73939}Još razgovaramo o tome.
{73985}{74071}Šaljem pozitivne vibracije. | - Vidim to.
{74253}{74307}Vodi ljubav sa mnom.
{74781}{74853}Tobias me doveo | ovamo na naš prvi spoj.
{74855}{74899}Kako ste se upoznali?
{74900}{74987}Otišla sam ga u intervjuirati | i više nisam otišla iz kuæe.
{74991}{75055}Bio je to vraški intervju.
{75073}{75179}Voli mladost oko sebe. | Kaže da ga to održava mladim.
{75199}{75251}Što si htio reæi?
{75281}{75348}Èini se da više ne djeluje.
{75454}{75535}Oèi su mu još | mlade kad mene pogleda.
{75655}{75727}Èini se da je samo to bitno.
{75957}{76047}Moj ti je muž dao kopiju | romana da ga proèitaš.
{76055}{76147}Inaèe to ne èini. | Veoma te cijeni.
{76157}{76209}I ne poznaje me.
{76214}{76263}I što misliš?
{76299}{76352}Divan je, zar ne?
{76357}{76430}To je najbolje | što je ikada napisao.
{76443}{76507}Drek je, zar ne? | - Tako je.
{76536}{76589}Bi li nešto uèinio za mene?
{76603}{76638}Reci mu.
{76673}{76736}Što? | - Da ništa ne valja.
{76740}{76782}Ne mogu.
{76785}{76867}Onda æe mu reæi | kritièari i to æe ga ubiti.
{76872}{76948}Ostala mu je samo reputacija.
{76952}{77036}I kad umre, | želim da mu to ostane.
{77041}{77104}Ne znam. | - Molim te, Byrone.
{77355}{77420}Ljutit æete se ako sjednem?
{77456}{77519}A ti ako ne ustanem?
{77554}{77608}Lijepe patke.
{77657}{77692}Da, pa...
{77730}{77780}Mislim da samo...
{77786}{77896}Pridonosimo | njihovu apatiènu stavu.
{77959}{78031}Veæina ljudi željela | bi se vratiti kao ptica.
{78034}{78111}Ne znaju o èemu | govore. To je jadno.
{78116}{78206}Živiš od milostinje i ostataka.
{78279}{78359}Vjerojatno zbog slobode | koju utjelovljuje letenje.
{78363}{78470}Ptice to ne znaju. | Za njih je letenje posao.
{78511}{78615}Dakako, osim ako | si orao ili jastreb.
{78640}{78710}Lebdiš u visinama. | To bi moglo biti lijepo.
{78766}{78798}Da.
{78847}{78916}Kao što biste se vi vratili? | - Ne bih.
{78928}{79027}Nikad mi ne bi bilo | bolje nego u ovome životu.
{79036}{79061}Nikada.
{79079}{79128}Veæina ljudi ne može to reæi.
{79131}{79230}Zbog toga nije | nimalo lakše otiæi.
{79299}{79335}Nahrani patke.
{79381}{79486}Dok sam radio, još | sam osjeæao taj zov.
{79497}{79542}Znaš?
{79555}{79618}Sad kad je knjiga završena...
{79652}{79739}Više ne mogu | naæi smisao za sebe.
{79896}{79925}Proèitao si je?
{79962}{79996}Jesam.
{80048}{80072}I?
{80134}{80177}Divna je.
{80330}{80392}Za prvu verziju.
{80473}{80544}Bože! K vragu! Isuse Kriste!
{80595}{80692}Ne možete podnijeti kritiku? | - Kakvu to "prvu verziju"?
{80710}{80768}Što ti se nije svidjelo?
{80771}{80824}Možemo o tome poslije? | - Ne!
{80828}{80887}Bezvezna je. | - Bezvezna?
{80969}{81007}Cijela?
{81010}{81071}Radije ovoga trena ne | bih zalazio u potankosti.
{81075}{81123}Imam druge stvari na pameti.
{81126}{81210}Isuse Kriste. Možda | ste mi slomili nos.
{81229}{81263}Pokaži.
{81303}{81338}Pokaži mi!
{81396}{81433}Ne nos!
{81470}{81510}Doði.
{81519}{81614}U redu, pokaži što nije u | redu s onim što sam napisao.
{81616}{81700}Ne želim krvariti po tome. | - Moja je krv na svakoj stranici.
{81711}{81748}Reci što ne valja!
{81751}{81806}Znate zbog èega ste | tako sjajan pisac?
{81808}{81866}Složili smo se da sam genij. | - I to pomaže.
{81869}{81931}No problem su | likovi o kojima pišete.
{81933}{82004}Tako su stvarni da | èitatelj osjeæa njihovo meso!
{82009}{82039}Hvala.
{82044}{82117}Ali ovo je 800 stranica | o propasti Rimskog carstva!
{82120}{82186}Dobro je istraženo. | - Koga briga za to?
{82190}{82262}Koji si ti kurac da | kritiziraš moj rad?
{82266}{82305}Nisam nitko. | - Da, toèno!
{82308}{82382}Ali i nitko ipak | može imati pravo.
{82566}{82629}Èekajte malo. | Smijete li piti?
{82634}{82671}Ne, ne smijem.
{82675}{82764}Lijeènik kaže da æe me ubiti. | Nadam se da ima pravo.
{82768}{82847}Ne kažem da ovo | što imate nije sjajno.
{82850}{82892}Loše to govoriš.
{82896}{82959}Kažem da ste možda | odabrali pogrešan pristup.
{82962}{83031}Što je glavna tema | o kojoj ste željeli pisati?
{83035}{83139}Da svako društveno ureðenje | naèini od neke skupine robove.
{83143}{83205}Sjajno! | - Hvala na odobravanju.
{83209}{83280}Pa što æe vam | onda rimski robovi?
{83283}{83374}Što im nedostaje? - Nitko se | ne može poistovjetiti s njima!
{83379}{83461}Želiš reæi da sam | potratio 12 g. Života?!
{83473}{83506}Ne! | - Nego?
{83510}{83594}Možete reæi svoje | kroz svaku potlaèenu skupinu.
{83598}{83638}Ima ih dovoljno.
{83643}{83707}Mogao bi to biti najbolji | roman što ste ga napisali!
{83712}{83752}Veæ sam mislio da jest.
{83757}{83841}Samo se morate | otarasiti rimskih robova.
{83845}{83912}I naæi drugi mikrosvemir.
{83984}{84027}Crnci? | - Ne.
{84059}{84099}Židovi? | - Ne.
{84145}{84202}Homoseksualci? | - Ne.
{84217}{84265}Pa tko onda?!
{84328}{84377}Radnici migranti.
{84435}{84481}Radnici migranti.
{84893}{84945}Daj, daj!
{85032}{85087}Radnici migranti!
{85108}{85153}Pas mater!
{85392}{85433}Bok. | - Bok.
{85438}{85480}Kad si nabavio leæe?
{85516}{85590}Urednik kaže da naoèale...
{85620}{85709}Naudile su prodaji | Hitlerovog djeteta.
{85720}{85807}Mislila sam da si | to rekao za bradu.
{85821}{85915}Platili su leæe jer su | rekli da æu izgledati...
{85920}{86019}Preintelektualno i nitko | neæe htjeti èitati knjigu.
{86027}{86116}Zašto se jednostavno | ne slikaš bez naoèala?
{86192}{86277}Zbog javnih nastupa. Znam | da ti se sviðaju naoèale.
{86280}{86381}Ne baš. Volim te | sa svim tvojim manama.
{87394}{87442}Htio si me vidjeti.
{87507}{87569}Znaš kad sam posljednji | put bio ovdje?
{87588}{87614}Ne.
{87624}{87690}Ni ja. Divno je, zar ne?
{87788}{87858}Osjeæaš kao da je sve moguæe.
{87897}{87965}Bio sam neka | vrst èuda od djeteta.
{87978}{88063}Svirao sam Mozarta sa 7 g. | - Doista?
{88080}{88144}Nije isto kao da si Mozart.
{88148}{88202}Nije loše za poèetak. Ne misliš?
{88233}{88268}Što se dogodilo?
{88299}{88343}Odrastao sam.
{88369}{88420}Wolfgang nije imao izgleda.
{88449}{88538}Smatram da žaljenje | nikomu ne koristi.
{88541}{88613}Ovo je nezgodan posao.
{88618}{88710}Sretan si što | imaš ženu i obitelj.
{88728}{88832}Ne dopusti da ti njihova | ljubav izmakne iz ruku.
{88956}{89018}Znaš zašto sam te doveo ovamo?
{89022}{89082}Ne, dragi, zašto?
{89102}{89184}Ovamo sam te doveo | kad smo prvi put izašli.
{89224}{89304}Ne ovamo. | - Lokacija je ista.
{89309}{89369}Srušili su onaj restoran.
{89372}{89456}L. A. Je teško | mjesto za romantiku.
{89458}{89504}Tebi dobro ide.
{89568}{89673}Sjeæaš se novoga tipa | o kojem sam ti govorio?
{89706}{89823}Sredio sam mu posao. Zaradit æe | više nego što sam ja ikad vidio.
{89826}{89872}Divno, dragi.
{89918}{89995}I razmišljao sam. | - Volim kad razmišljaš.
{89998}{90041}Tako je seksi.
{90083}{90170}Ako ne iskoristiš | uspjeh da obogatiš život,
{90173}{90268}onda samo stavljaš | neuspjeh u Gucci cipele.
{90281}{90364}Ne znam što želiš reæi. Hvala. | - Dopusti da ja ovo platim.
{90484}{90517}Hvala.
{90592}{90623}Izvoli.
{90673}{90723}Što je to?
{91000}{91077}Èek koji sam ti | napisala prošli mjesec.
{91094}{91135}Ne želim ga.
{91162}{91261}Jedina si u 30 g. | S kojom mogu biti ja.
{91283}{91351}Ne želim više tvoj novac.
{91362}{91411}Želim samo tebe.
{91420}{91471}Ne shvaæam.
{91493}{91562}Želim da napustiš muža.
{91605}{91686}Želim se oženiti s tobom.
{91868}{91931}Zacijelo si poludio!
{91936}{92005}Zašto bih to uèinila?
{92057}{92118}Evo. Uzmi to natrag.
{92221}{92284}Što si umislio?
{92290}{92335}Doði. Idemo.
{92339}{92390}Budalice.
{92425}{92474}Ta ti je dobra.
{92508}{92545}Veoma lijepo.
{92549}{92617}Sjajno. Jedete li | ovako svaku veèer?
{92619}{92648}Ne, ne.
{92655}{92690}Hvala.
{92718}{92803}Ne svaku veèer. Veèeras slavimo.
{92824}{92876}Dobro došao u obitelj.
{93041}{93089}Ja moram reæi...
{93093}{93181}To je veoma velikodušna | ponuda i hvala vam.
{93197}{93276}Ne znam koliko mi | je vremena preostalo.
{93286}{93387}No provest æu ga gledajuæi | svoju divnu ženu sretnu.
{93494}{93615}Uèinit æu sve što mogu. | - Uèinit æeš sve što ona želi.
{93627}{93666}U redu.
{93841}{93897}Dragi, ti mu trebaš reæi. | - Da, draga.
{93932}{93976}Pa, Byrone...
{93992}{94044}I ja æu trebati tvoju pomoæ.
{94050}{94095}U redu. | - Sa svojom knjigom.
{94100}{94175}Dat æu prijedloge... | - Ne, ne želim ih.
{94179}{94281}Samo æe me uzrujati. | Pomozi da je ponovno napišem.
{94326}{94393}Da. Dobro.
{94564}{94616}Mislite zajedno?
{94623}{94728}Kao da æeš mi sjediti u | krilu. Volim tvoje zamisli.
{94732}{94864}Andrea ti vjeruje, a Luther | kaže da si završio Yale.
{94881}{94944}Onda nisi potpuno loš.
{94967}{95048}30% tantijema, | zajednièko autorstvo.
{95053}{95104}Zajednièko autorstvo.
{95135}{95214}Moje ime pored...
{95248}{95341}Pored vašeg imena. | - Možda istom velièinom slova.
{95505}{95565}Byrone, što radimo ovdje?
{95568}{95620}Aklimatiziramo se.
{95651}{95732}Moæi æemo pozvati | i tvog oca. Doði sa mnom.
{95735}{95782}Byrone, ovo je ludost.
{95813}{95870}Kako si to možemo priuštiti?
{95873}{95962}Tobias Allcott | želi pisati sa mnom.
{95979}{96023}Sa mnom.
{96039}{96102}Pleši sa mnom.
{97114}{97206}Trebamo mu odjenuti | zoot odijelo.
{98691}{98728}Zdravo, Byrone.
{98731}{98827}Bio sam sa ženom koja me tjerala | da joj sišem nožne prste.
{98830}{98867}Je li ti ovo normalno?
{98872}{98926}Groznica.
{98928}{99004}Èovjek misli da | na osobi postoje mjesta...
{99007}{99051}Gdje im ne treba društvo.
{99383}{99452}Pogodi koje je rijeèi | Nathaniel danas nauèio?
{99455}{99477}Koje?
{99480}{99552}Koji se vrag | dogodio s mojim tatom?
{99575}{99611}To nije smiješno.
{99615}{99670}Nije ni trebalo biti.
{99684}{99771}Moram završiti ovo poglavlje. | - Možeš sutra.
{99774}{99834}Moraš povesti | malo vremena s nama.
{99839}{99903}Dena, trebam nekoliko minuta. | - Molim te.
{99906}{99955}Ne shvaæaš što radim?
{99959}{100041}Pokušavam. - Trebam | vremena. Ovo je velika prilika.
{100045}{100127}Bilo nam je dobro | i s malim prilikama.
{100230}{100324}Misliš da uživam što | moram ovako raditi?
{100344}{100417}Koliko prilika | èovjek dobije u životu?
{100422}{100463}Moraš zgrabiti priliku.
{100468}{100553}Èak i ako mrziš | sve što ide uz nju!
{100558}{100629}A ja mrzim ovo! Mrzim!
{100641}{100742}No èinim to za tebe! | Èinim to za Nathaniela.
{101284}{101321}Tko je?
{101325}{101368}Samo ja.
{101391}{101452}Hvala, draga, Divno je.
{101456}{101504}Dobro se osjeæaš?
{101517}{101551}Umorno.
{101562}{101622}Trebaš se naspavati.
{101632}{101698}Umoran sam samo | kad su mi oèi otvorene.
{101701}{101789}Kad su zatvorene, | samo se bojim.
{101823}{101922}Kamo æeš? | - U ured da vidim mogu li...
{101926}{101985}Ne, radit æeš poslije.
{101991}{102050}To je problem. Ne mogu raditi.
{102119}{102241}Kad razmišljam, kao | da ulazim u praznu sobu.
{102305}{102414}Ako na stranice dolazi bilo | što dobro, on je zaslužan.
{102451}{102502}Ne govori tako.
{102507}{102635}Kažu da je najtužnije | kad nadživiš svoju djecu.
{102675}{102743}Moj dar bio je moje dijete.
{102801}{102846}Umoran si.
{102895}{102962}Ne poštuješ istinu. Uopæe.
{103091}{103168}To kod tebe najviše volim.
{103995}{104097}NEÈUJNI PJEVAÈ BALADA
{104180}{104224}Dobro obavljeno.
{104318}{104375}Nisam èuo nikakav smijeh.
{104388}{104479}Što joj je? | Unutra ima smiješnih stvari.
{104494}{104534}Da. Pa...
{104555}{104648}Rijetko se naglas smije kad èita.
{104703}{104770}To je jedino nesavršenstvo.
{104876}{104934}Andrea je jedina...
{104983}{105066}Za koju vjerujem | da me potpuno voljela.
{105097}{105166}Zanemarivala je moje mane.
{105172}{105222}I žao mi je što jest.
{105276}{105362}Da nije, vjerojatno bih | nešto poduzeo zbog njih.
{105385}{105480}Èuvaj se žena koje | te vole onakvog kakav jesi.
{105483}{105582}To je siguran znak | da se prelako zadovolje.
{105789}{105820}Ovo je...
{105855}{105891}Divno.
{105999}{106051}Hvala, draga.
{106523}{106602}ELIZEJSKE POLJANE | Uvijek na usluzi
{106862}{106912}Doista ti se svidjela?
{106942}{106988}Oduševila me.
{107019}{107076}No je li komercijalna?
{107080}{107172}Ljudi kupuju Tobiasove | romane, èitali ih ili ne.
{107193}{107261}To je lijepo kad si ikona.
{107419}{107475}Isprièavam se. | - Dobro si?
{107478}{107520}Nisam mogao spavati.
{107526}{107575}Osjeæaš se loše?
{107579}{107658}Osjeæam se divno. | Zato nisam mogao spavati.
{107663}{107718}Nisam to htio prespavati.
{107727}{107784}Što to piješ?
{107791}{107840}Vodu.
{107845}{107945}S dovoljno viskija | da nema metalni okus.
{108194}{108244}Samo sam htio...
{108277}{108372}Htio sam reæi | koliko sam oboma zahvalan.
{108409}{108449}I...
{108496}{108539}Laku noæ.
{108575}{108630}Lijepo spavaj, dragi moj.
{108767}{108824}Nešto trebaš.
{109029}{109096}Ne želim veèeras biti sam.
{109134}{109185}Ne veèeras.
{109805}{109854}Doði. Lezi.
{109859}{109904}Hvala ti, draga.
{111061}{111091}Bok.
{111133}{111193}Izlaziš?
{111230}{111325}Htio sam da uzmemo Nathaniela | i odemo nešto pojesti.
{111328}{111392}Razgovarati. | - O èemu?
{111505}{111552}Kamo ideš?
{111572}{111676}Zašto mi nisi rekao | kamo si svake veèeri išao?
{111702}{111775}Pogledaj me i reci mi!
{111829}{111893}Takva si jebena šupèina!
{111896}{112006}I ja sam šupèina! | Bila sam jebeno slijepa!
{112028}{112107}Ne tièe te se kamo idem!
{112476}{112527}Kako si?
{112531}{112573}Prilièno dobro.
{112601}{112671}Smijem sjesti? | - Izvoli.
{112764}{112833}Nisi baš dolazio.
{112847}{112899}Ostavljao sam ti poruke.
{112904}{112966}Uzeo sam si malo slobodno.
{112984}{113036}Što te muèi?
{113087}{113164}Jednom si mi rekao | da si bio oženjen.
{113167}{113201}Jesam.
{113219}{113296}Dok si radio? | - Preklopilo se.
{113325}{113402}I? | - I što?
{113445}{113514}To ti je uništilo brak?
{113539}{113660}Veze su zamršene. Nikad ih | ne prekine samo jedna stvar.
{113664}{113744}Rekao si da je veæina | tvojih zaposlenika oženjena.
{113748}{113801}Nisam rekao sretno.
{113806}{113884}Moraš nauèiti slušati pridjeve.
{114452}{114559}Znaš, sada kad sam | završio knjigu...
{114563}{114606}Imam malo više vremena.
{114609}{114676}Želio bih navratiti, | možda da ruèamo zajedno.
{114693}{114742}Neæe me biti.
{114747}{114826}Mislim da je vrijeme | da ostavim ovaj posao.
{114830}{114883}Razmisli i ti o tome.
{114888}{114930}Sad sam pisac.
{114933}{114999}Još te plaæaju kao kurvu. | Nemoj to zaboraviti.
{115003}{115052}One to ne zaborave.
{115057}{115104}Pa-pa.
{115173}{115222}Što æeš raditi?
{115307}{115391}Najbolje što mogu, mislim.
{115611}{115732}Treba li u iduæih 10.000 g. | Postiæi još koji važan cilj?
{115737}{115782}Uði.
{115834}{115927}Mislio sam da želite èaj. | - To je veoma ljubazno.
{115931}{116012}Hvala, Byrone. | Veoma lijepo od tebe.
{116145}{116194}Pitao sam se...
{116198}{116231}Da?
{116282}{116346}Kad æete dati knjigu izdavaèu?
{116349}{116403}Baš smo razgovarali o tome.
{116410}{116466}Da. Pa, mi...
{116475}{116591}Mislili smo da bi bilo | dobro prièekati da umrem.
{116726}{116789}Oprostite, ali zbog èega?
{116792}{116868}Objave li me posmrtno, | bit æu vruæa roba.
{116872}{116985}Kritièari æe se bojati pokopati | me i prodavat æe se kao luda.
{117070}{117125}Ne budi uzrujan.
{117129}{117246}Lijeènik kaže da imam još | koji tjedan, najviše mjesec.
{117308}{117388}Znaš što æe to znaèiti? | Da si dobro zbrinut.
{117405}{117478}I to æe me usreæiti.
{117556}{117609}Hvala na èaju.
{117758}{117817}Byrone, èekaj malo.
{117982}{118019}Da.
{118064}{118120}Ako ti bude imalo lakše...
{118148}{118224}Veæ osjeæam bolove u prsima.
{118566}{118648}Mark Twain. Volim ga.
{118667}{118765}Zna se izražavati. | Dobro se osjeæam.
{118769}{118881}Slušaj ovo: Je li ova kap | strpljivo padala 5000 g.?
{118887}{118934}Sad pada.
{118940}{119041}Još æe padati kad sve ovo | bude trebalo biti potonulo.
{119044}{119110}Poslijepodne povijesti | i sumrak tradicije
{119115}{119208}progutala je tamna noæ zaborava.
{119809}{119862}Osjeæam se tako glupo.
{119904}{119964}Nisam mogla ništa reæi.
{120126}{120185}Bio je to divan sprovod.
{120197}{120243}Imala sam sreæe.
{120265}{120357}Rekla sam mu sve što sam | htjela prije nego što je umro.
{120495}{120553}Htio bih napisati predgovor.
{120558}{120629}Da mu tako zahvalim. | Bi li to voljela?
{120644}{120678}Veoma.
{120753}{120814}Ali neæe biti potrebno. | - Uopæe nije problem.
{120819}{120917}Doista to želim. | Ponosim se našim radom.
{120931}{121039}Tvoj rad. | - Roman mi znaèi nešto osobito.
{121049}{121123}Znam da æe te ovo razoèarati.
{121133}{121230}Ali ne znam ni za kakav | tvoj dogovor s mojim mužem.
{121235}{121315}Koliko ja znam, | niste imali ugovor.
{121387}{121466}Molim? | - Ili dokaz o usmenom dogovoru.
{121469}{121563}Pardon. Ja sam napisao tu knjigu.
{121566}{121632}Shvaæaš. | - Što to?
{121637}{121688}Ja sam napisao tu knjigu.
{121693}{121766}Ne može imati | drugo ime pored njegovog.
{121771}{121853}Svi æe znati da je | trebao pomoæ. Ne želim to.
{121855}{121952}Ti si htjela da èeka s | objavljivanjem dok ne umre.
{121957}{122018}Moram štititi njegovu reputaciju.
{122046}{122096}A ti si to omoguæio.
{122101}{122165}Da, jesam!
{122208}{122316}Odrekao sam se | života zbog ove knjige!
{122357}{122420}I samo mi to možeš reæi?!
{122472}{122530}Hvala ti na divnom provodu.
{122717}{122830}Nema jebene teorije | da se izvuèeš s ovime!
{122834}{122886}Nemaš izbora. | - Nemam?
{122891}{122958}Osim ako se ne želiš poniziti.
{122963}{123067}Ne zaboravi, dobro si | plaæen za svoje usluge.
{123196}{123257}Molim te da me ne mrziš.
{123277}{123377}Ako si ikada bio | zaljubljen, shvatit æeš.
{123466}{123515}Jebi se.
{124047}{124163}Broj koji ste nazvali nije | u upotrebi. Novog broja nema.
{124166}{124252}Provjerite jeste li | nazvali ispravan broj.
{125602}{125680}Ti si zacijelo èovjek | iz Elizejskih poljana.
{125717}{125772}Tako je oèito?
{125841}{125905}Rezervirao sam u Huntingtonu.
{125908}{125957}Moj muž ondje jede.
{125961}{126006}Možemo nekamo drugamo.
{126009}{126091}Nema veze. | On gleda kroz mene.
{126113}{126150}Nemoguæe.
{126160}{126195}Hvala.
{126201}{126255}Zacijelo ima previše posla.
{126261}{126330}Tako mi kaže.
{126334}{126411}Kad je rijeè o muškarcu...
{126414}{126513}Koji skrbi za obitelj, | prioriteti se pomiješaju.
{126542}{126611}No to nema veze s ljubavi.
{126662}{126793}Koliko te plaæam, oèekujem da | u svemu budeš na mojoj strani.
{126809}{126847}Isprièavam se.
{126855}{126917}Idem napudrati nos.
{127238}{127302}Mislio sam da æu | ovdje naletjeti na tebe.
{127305}{127335}Ideš na piæe?
{127340}{127369}Ne, odlazim.
{127371}{127415}S kime si?
{127438}{127504}Norma Van Ruden iz San Marina.
{127519}{127562}Kriste! | - Što je?
{127573}{127664}To je ona koja voli | da joj sišeš nožne prste.
{127667}{127738}Dat æu ti savjet. | Olakšaj si.
{127743}{127824}Ne vodi je prije na ples.
{127877}{127903}Hvala.
{127907}{127972}Moramo si èuvati leða.
{127984}{128044}Koga ti veèeras vuèeš sa sobom?
{128049}{128095}Nju.
{128841}{128899}Što? Neæemo uzeti sobu?
{128962}{129046}Zašto muškarac | èini to što vi èinite?
{129050}{129147}Smatram da nam je zadatak | donijeti radost drugima, draga.
{129150}{129229}Zapravo me doista zanima istina.
{129325}{129360}Jednostavno je.
{129406}{129543}Jebanje je posljednje utoèište | èovjeka koji se osjeæa nemoænim.
{129599}{129627}Hvala.
{129670}{129704}Laku noæ.
{129765}{129815}Laku noæ.
{129948}{130044}Ovaj posao zna uèiniti | da izgledate malo starije
{130046}{130125}i možda budete malo mudriji.
{131269}{131303}Onda?
{131314}{131378}Ja æu tjesteninu sa školjkama.
{131381}{131433}Dobar izbor. Vi, gospodine?
{131436}{131478}Što biste vi predložili?
{131481}{131534}Pasta primavera.
{131550}{131598}Nije baš uvjerljivo.
{131636}{131685}Što je primavera?
{131688}{131790}Proljetno povræe s tjesteninom. | - Nešto kao ðuveè?
{131813}{131872}Kao ðuveè. | - Je li svježe?
{131877}{131925}Kao proljeæe.
{131928}{131971}Dobro.
{132299}{132376}Uzmi 10 minuta stanke. | Ja æu te zamijeniti.
{132681}{132728}Bok. | - Bok.
{132850}{132940}Oprosti. To su | moji kljuèevi od kuæe.
{133060}{133120}Èula sam da te Dom zaposlio.
{133123}{133152}Da.
{133157}{133255}Smatrao sam kako je | jedino što mogu vratiti...
{133258}{133323}Moje samopoštovanje.
{133362}{133404}Je li uspjelo?
{133408}{133500}Bilo bi lakše bez | leptirke na kopèanje.
{133767}{133828}Kako je moj sin? | - Dobro je. Sjajno.
{133886}{133931}Mnogo govori?
{133947}{133994}Pita za tebe.
{134111}{134149}Pišeš li?
{134166}{134205}Imam...
{134270}{134359}Imam malo problema... | S dobivanjem nadahnuæa.
{134694}{134803}Jela si? Za 20 minuta | imam stanku za veèeru.
{134817}{134886}Ne bih. Moram se vratiti.
{134951}{134989}Shvaæam.
{134992}{135106}Došla sam ti reæi da smo | se doselili u staru èetvrt.
{135109}{135173}Èuo sam. Pokušavao | sam doæi do tebe.
{135184}{135247}Ali broj ti nije u imeniku.
{135272}{135310}Da, pa...
{135350}{135421}Bila sam tako raspoložena.
{135502}{135559}Jako mi je žao.
{135666}{135723}Laku noæ, Byrone.
{135982}{136040}Nathanielov privatni telefon.
{136283}{136372}Kakva ljepota! Znaš kako | vas dvoje izgledate zajedno?
{136375}{136399}Kako?
{136402}{136444}Prirodno.
{136467}{136518}Moram smiriti ženu.
{136521}{136594}Znaš kakva je kad ne | naruèuju njezine specijalitete.
{136597}{136670}Nije ona kriva. | - Kažem joj: Nisi ti kriva.
{136673}{136748}Tako je osjetljiva. | - Zbog jelovnika je.
{136751}{136832}Što mu nedostaje? | - Da budem iskren?
{136837}{136912}Samo malo. | - Sve zvuèi isto.
{136922}{136973}"Manicoti" kao "osso buco".
{136976}{137063}Rijeèju "soèno" | opisuješ tri jela.
{137066}{137172}Da ga napišem iznova? | - Uèinio bi to za mene?
{137272}{137330}Osjeæam nadahnuæe.
{137367}{137464}Vidio sam ga još jedanput, | oko godinu dana poslije.
{137466}{137582}Napisao je roman Pomrèina | o braku koji se raspada.
{137584}{137665}Ponosio sam se što sam | mu dovoljno uništio život
{137668}{137775}da mu je to dalo | temu o kojoj æe pisati.
{137791}{137934}Za tren æe se okrenuti i | više je nikad neæe vidjeti.
{137937}{138033}Znao je da je neke stvari | trebao reæi, želio je reæi.
{138095}{138175}No kad je pogledao | ženino lice,
{138179}{138287}mogao se sjetiti samo | onoga što je starac rekao:
{138331}{138443}Èuvaj se žena koje te | vole onakvog kakav jesi.
{138445}{138537}To je siguran znak | da se prelako zadovolje.
{138540}{138616}Žena ga je voljela previše | da bi se željela zadovoljiti,
{138619}{138715}ali on više nije imao | savjesti da se mijenja.
{138718}{138833}Uvjerio se da sve što | èini, èini za nju.
{138903}{139025}Ovladao je kobnom tehnikom | vjerovanja u vlastite laži.
{139028}{139145}A onda su jednoga dana | njegova žena i dijete nestali.
{139200}{139346}Imao je sve može poželjeti | osim razloga da ujutro ustane.
{139349}{139451}Taj djeliæ sekunde | nakon što otvorite oèi
{139454}{139539}i imate se komu okrenuti,
{139544}{139603}tko vas voli...
{139606}{139743}Tko vas voli više i grli jaèe | u porazima nego u pobjedama.
{140093}{140184}Natoèio si je još jedan viski
{140188}{140291}znajuæi u tome trenu | da æe provesti ostatak života...
{140428}{140532}Pokušavajuæi vratiti | taj djeliæ sekunde.
{140555}{140612}Hvala što ste došli.
{140844}{140878}Hvala.
{140893}{140976}Kako se zovete? | - Yasmin, s Y.
{141044}{141116}Doista mi se svidjela knjiga. | - Hvala.
{141175}{141229}Izvolite. | - Hvala.
{141247}{141283}Bok. | - Bok.
{141288}{141343}Kako se zovete? | - Georgette.
{141346}{141384}Bilo je veoma dirljivo.
{141387}{141413}Hvala.
{141418}{141490}Samo bih voljela da ga | je na kraju primila natrag.
{141522}{141573}Ja takoðer.
{141601}{141693}Bila sam triput u braku. | Kad je gotovo, gotovo je.
{141696}{141793}Trebaš znati kad je | vrijeme da kreneš dalje.
{141878}{141936}Vrijeme je.
{142122}{142161}Ime?
{142223}{142301}Posveti je Nathanielu.
{142630}{142679}Jesi li je proèitala?
{142731}{142812}Zašto mi prije nisi | mogao reæi te stvari?
{142969}{143035}Ja sam pisac.
{143961}{144032}Poveo sam godine | pokušavaju zadovoljiti žene.
{144035}{144082}On je došao do zakljuèka
{144084}{144188}da je važno znati | zadovoljiti samo jednu.
{144201}{144282}O tome treba pisati.
{144283}{144683}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan  
{144714}{144800}Redatelj
{144887}{144971}Scenarist
