{766}{792}Naprijed. 
{840}{892}Pazi na vrata, zapovjednièe.|Pokušaj ništa ne dirati. 
{1760}{1808}Jesi li si znao da je|obièna kuæna prašina. . . 
{1810}{1900}sastavljena najviše|od ljudske kože?
{1960}{1990}Ne, gospodine,|to nisam znao. 
{2040}{2106}Natjera te da razmisliš o|tome koga pozivaš u goste. 
{2396}{2450}Dvije žlice strojnog ulja. . . 
{2452}{2492}mogu zagaditi. . . 
{2534}{2633}zalihe vode za cijeli brod. 
{2690}{2775}Neke stvari jednostavno|ne idu zajedno. 
{2825}{2884}Zar ne,| zapovjednièe?
{2956}{2991}Položit æe. 
{3015}{3075}Juèer je postigao 94 boda|na posljednjem ispitu. 
{3111}{3160}Gospodine, ne mora biti|sutra tako brzo. 
{3163}{3211}Sve što treba uraditi,|je da završi vježbe. 
{3348}{3362}Billy. . . 
{3543}{3633}možda æe doæi dan kada æe obojeni|završiti ovu školu za ronioce, 
{3639}{3707}ali to neæe biti sutra ili|bar dok sam ja ovdje. 
{3774}{3805}Slažeš se sa mnom,| naravno. 
{3875}{3977}Zar ne, zapovjednièe?| Da, gospodine. 
{4825}{4864}Baseball sezona je|završena, kuharu. 
{4931}{5000}Shvatio sam, Rourke.|Èak nisam ni pomislio. 
{5002}{5064}Zašto ne?|Jer sam  vidio vaše posljednje zaranjanje. 
{5140}{5223}Želiš znati što sam ja?  Ja sam jadni skot|koji je postavljen ovdje
{5227}{5326}da ti utuve u tu glavu da se|neke stvari ne mijenjaju. 
{5333}{5403} Zaslužujem položiti.|Od kada zasluga nešto znaèi?
{5415}{5445}Ne žele imati|obojenog ronioca. 
{5461}{5524}Jer ma što uradio, u njihovim oèima,|nikad neæeš biti dobar kao oni. 
{5536}{5583} Pa, zaslužio ili ne,|past æeš. - Ne, vi æe te. 
{5584}{5628}Misliš da ti dugujem nešto?
{5640}{5705}Ne dugujem ti ja ništa. 
{5720}{5805}Ti ili bilo tko drugi. Sjeban si,|kuhare. Dogaða se i najboljima. 
{5808}{5848}Bili ste u pravu, zapovjednièe.|Vi i ja nemamo ništa zajednièkog. 
{5864}{5960}Ja možda i jesam neki prljavi crnjo | iz selendre, ali ja bar nešto èinim od sebe. 
{5968}{6035}Vi, vi ste onaj isti mali èovjek|pun mržnje od èega ste i poèeli. 
{6060}{6080}Da nema ronjenja,| bili bi ništa. . . 
{6109}{6173}do izgubljen, pokvareni skot|koji je nekada bio nešto. 
{6593}{6666}Hej!
{6668}{6715}Što ti je to rekao da te|natjerao da se toliko trudiš?
{6750}{6765}" Budi najbolji. "
{6792}{6798}Pa, i jesi. 
{6875}{6948}Samo ne dolazi sutra.|Pappy te neæe pustiti. 
{7090}{7111}A što je s vama,| zapovjednièe?
{7245}{7323}Ovaj dan æe odluèiti tko æe od|vas postati ronilac Mornarice. 
{7336}{7429}Cilj ovog testa je da se pravilno|sastavi ova bandaža pod vodom. 
{7447}{7511}Dijelovi za sastavljanje se|nalaze dolje na dnu. 
{7525}{7622}Kada jednom doðete do njih,|zatražit æe te alat. 
{7635}{7668}On æe vam biti spušten. 
{7689}{7778}Mjerit æe vam vrijeme, prema trudu i dobit æe| te više bodova za brzi završetak. 
{7784}{7865}Mada, nastavit æemo vam pumpati zrak|dokle možete izdržati hladnoæu. 
{7884}{7941}Zato polako i|obavite to kako treba. 
{8622}{8665}Ako ne završite bandažu, 
{8686}{8735}onda ste protratili 6|mjeseci svoga života. 
{9030}{9132}Ronioci,| postrojite se i priðite šini. 
{10124}{10161}Gornja strana, locirao|sam svoje radno svijetlo. 
{10700}{10730}Gornja strana,| Plavi Ronilac. 
{10735}{10797}Locirao sam svoj zadatak|i tražim svoju torbu s alatom. 
{10827}{10899}Gornja strana, ovdje Crveni Ronilac.|locirao sam svoj zadatak . 
{10919}{10996} Tražim svoju torbu s alatom.|Pomagaèi spustite torbe. 
{11596}{11655}Gornja strana, Plavi Ronilac.|Još uvijek èekam svoj alat. 
{12452}{12536}Plavi Ronioèe,|tvoja torba je na dnu. 
{12948}{13020}Zapovjednièe, poènite mjeriti|vrijeme na svim zadacima. 
{13640}{13715}Pomoænik strojara Rourke,|1 sat, 37 minuta. 
{13722}{13741}Savršeno sastavljanje. 
{14337}{14409}Druga Klasa Yarmouth,|2 sata, 19 minuta. 
{14414}{14433}Savršeno sastavljanje. 
{14888}{14916}Nisam vjerovao da |æu to doživjeti. 
{14940}{15025}4 sata  i 9 minuta. Bolje ikad,|nego nikad, strojaru Crofoot. 
{15027}{15098}Savršeno sastavljanje.|Kakva je voda tamo dolje?
{15113}{15161}Hladna kao led,| zapovjednièe. 
{15172}{15184}Izvucite ga. 
{16182}{16210}Kako to misliš,|još nije izašao?
{17483}{17488}Izvinite. 
{17918}{17950}Stanica za ronjenje,|govori vam Glavni Ronilac. 
{17952}{18035}Zapovjednièe Sunday, sada svaki|kuhar i èistaè cipela u kampu. . . 
{18037}{18100}želi to probati. 
{18111}{18127}Zato slušaj, 
{18154}{18200}Ne diži ga dok se ne|prestane pomicati. 
{18223}{18246}Skoro da je mrtav,| gospodine. 
{18266}{18310}Ne dok se ne prestane | pomicati, zapovjednièe. 
{18508}{18524}Predaj se,| kuharu. 
{18546}{18594}Ako tamo dolje padneš u šok,|možda se nikada neæeš probuditi. 
{18615}{18637}Hajde, sada.|Nije ovo vrijedno umiranja. 
{18679}{18690}J-ja se zovem. . . 
{18723}{18786}Oficir druge klase. . . 
{18815}{18866}C-C-Carl Brashear. 
{18929}{18958}Ja sam ronilac Vojne Mornarice. 
{19612}{19678}Dižite ga.|Dižite ga!
{19680}{19728} Imam ga.| Vraæamo ga. 
{19731}{19798}Mornaru,|zanemari to nareðenje!
{19855}{19860}Mornaru!
{19938}{20017}Zapovjednièe Sunday,|stupa na snagu odmah, 
{20039}{20112}smjenjujem vas|sa vaših dužnosti!
{20138}{20175}Jeste li me èuli,| zapovjednièe?
{20250}{20275}Drži konop.|Drži konop. 
{20885}{20941}Hajde, Brashear.|Skoro si uspio. 
{20963}{20987}Samo još par koraka.|Hajde, pomoæi æemo ti. 
{21014}{21025}Još malo. 
{21055}{21075}Tako je. 
{21422}{21429}Otvorite ga. 
{21918}{21968}Oficir druge klase|Carl Brashear, 
{21995}{22022}9 sati,|31 minuta. 
{22045}{22063}Savršeno spajanje. 
{22278}{22287}Vodite ga unutra. 
{22358}{22385}Pomozite mu!
{22740}{22790}Carl,| j-j-jesi l-li è-è-èuo...
{22806}{22861}Uspori malo, Snowhill.|Vratili su me u program za ronjenje. 
{22873}{22925} Poèinjem trening iduæi tjedan.| Èestitam. 
{22955}{22978}Hvala, Carl. 
{23028}{23084}Hej, zamalo zaboravih.|È-è-uo si za Sundaya?
{23116}{23200} Ne. G-gospodin Pappy je pobjesnio|kada te je kuèkin sin pustio. 
{23213}{23255}Rasturio ga je i izbacio. 
{23290}{23325}Izgleda da je kreten|dobio što je zaslužio, a?
{23384}{23396}Izgleda da jeste. 
{23570}{23585}Izgleda da jeste. 
{24440}{24465}Hoæeš li ostati ?
{24780}{24795}Volim te, dušo. 
{25190}{25205}Od gospodina. 
{25587}{25616}Ti mrziš šampanjac. 
{25660}{25684}Ti imaš ronilaèki posao. 
{25703}{25757}Mornarièka luka u Brooklynu.|Pomoæni ronilac. 
{25764}{25780}Brooklyn?| Brooklyn!
{25850}{25914}Oh, dušo, moæi æemo|veèerati kao stari braèni par. 
{25922}{25965}Oh, pa, dušo,|nisam prihvatio posao. 
{26001}{26054}Èekali smo tri godine|da se otvori to mjesto. 
{26062}{26098}Jo, neæu napredovati|ako ne ronim. 
{26120}{26206}i nikad neæu postati glavni ako ostanem |pomoænik. Naæi æu nešto drugo. 
{26375}{26440}Kasni mi tri mjeseca.|Kasni što?
{26605}{26667}Imat æeš|Pravu. . . bebu?
{26705}{26758}Imat æemo dijete!|Imat æemo pravu bebu!
{26764}{26800}Dobit æemo bebu. 
{26830}{26942}Dame, gospodo i ostale propalice,|vrijeme je da se doèeka Nova Godina. 
{26978}{27066}Sretna Nova Godina.| 5, 4, 3, 2, 1. 
{27068}{27145}Sretna Nova Godina.| Sretna Nova Godina!
{27258}{27285}" Nikada neæeš znati "
{27316}{27337} " Koliko te volim "
{27409}{27486}Apsolutno. Moraš ih podiæi, s obzirom da imamo| 16 do 20 godina iskustva. 
{27490}{27542}Morat æeš im se unijeti u|lice i reæi im tko je glavni. 
{27552}{27584}Ako to ne napraviš, neæe te|pozdravljati do kraja života. 
{27614}{27672}I tako ja sjedim|Izvinite. 
{27734}{27782}Što to, a?|Ne sjeæa me se. 
{27880}{27932}Stariji Zapovjednik Sunday,|U. S. S. Hoist. 
{28016}{28069}Ti si mi okonèao ronilaèku|karijeru, poruènièe. 
{28087}{28163}Zapovjednik poruènik Hanks.|Drago mi je . 
{28180}{28203}To je bilo davno,| zapovjednièe. 
{28220}{28247}Davna prošlost. 
{28308}{28375}Pa,|došli smo  se javiti. 
{28377}{28420}Hej. 
{28446}{28560}Nisam znao da imaš kæer. 
{28598}{28610}Tako je. 
{28644}{28657}Baš je slatka. 
{28700}{28795}OK, moramo iæi. . .|jer æe Billy plesati sa mnom. 
{28805}{28820}Sretna Nova Godina. 
{28859}{28865} Hajde, Billy.|Zabavite se. 
{28911}{28950} Plesat æeš sa svojom slatkom ženicom,| je li tako?   Da. 
{29185}{29231}Vidiš?| Zar nije bilo lako?
{29270}{29280}Bilo je. 
{29300}{29401} Da.| Ne. Billy. 
{29432}{29461} On je najveæi pijanac u Mornarici.| Billy!
{29755}{29770}Jeste li dobro,| gospodine?
{29880}{29945}Stariji zapovjednièe Sunday,|Proglašavam vas krivim. . . 
{29947}{30040}za kršenje èlana 90|Vojnog Zakona:
{30050}{30086}napad na nadreðenog oficira. 
{30105}{30153}Vaše ponašanje je|potpuno neprihvatljivo. 
{30182}{30240}Bit æe te kažnjeni s pola|plaæe tijekom 6 mjeseci, 
{30251}{30305}ogranièenje kretanja u|bazi na dva mjeseca. . . 
{30330}{30401}i ovim se degradirate|na èin nižeg oficira. 
{30431}{30490}Za one koji su nam se tek pridružili,| naša glavna prièa  se nastavlja. . . 
{30507}{30569}tisuæu milja |daleko na Mediteranu. 
{30586}{30645}Prije samo par sati,|amerièki bombarder B-52. . . 
{30646}{30697}koji je letio na rutinskoj misiji|iznad obale Španjolske. . . 
{30707}{30763}udario je u snježni nasip. 
{30776}{30873}Trenutak prije nestanka s radara,|posada je izbacila nuklearni tovar. 
{30890}{30954}3 bojeve glave od 50-megatona|baèene su padobranom. 
{30964}{30999}Dvije su odmah pronaðene. 
{31007}{31100}Ali treæa hidrogenska bomba ostaje |izgubljena u moru. Uspio si. 
{31103}{31187}Brodovi mornarice SAD imaju sonare koji | mogu pomoæi. . . Becky, doði po svoje igraèke. 
{31191}{31264}U monotonoj i frustrirajuæoj|pretrazi po morskom dnu. 
{31280}{31348}Pretraga morskog dna|bit æe posao za Alvina, 
{31353}{31445}dvoèlana podmornica koju je posudio|od Oceanographic Instituta iz Woods Holea. 
{31455}{31551}Pa ipak, èak i dok vojni brodovi èešljaju|morsko dno za bojevom glavom, 
{31556}{31588}isto rade i ruske podmornice. 
{31606}{31689}Prema pomorskom zakonu bomba koja je | nestala u meðunarodnim vodama
{31695}{31734}pripada onome koji  je prvi pronaðe. 
{31751}{31819}Zadatak da pronaðu i|izvuku bombu prije Rusa. . . 
{31830}{31890}imaju elitni ronioci mornarice|prikazani na snimci. 
{31903}{32007}Na službu u Norfolku, Virginija, ronioci su| stigli mlažnjakom prije nekoliko  sati, 
{32015}{32096}mnogi od njih u uniformama|koje su još jutros nosili. 
{32368}{32404}Plavi Ronioèe,|ovdje kapetan. 
{32510}{32541}Plavi Ronioèe,| javi se. 
{32578}{32611}Ovdje sam, Hart.|Što ti je potrebno?
{32651}{32722}Carl, cijenio bih ako bi mi našao|tu izgubljenu nuklearku. 
{32741}{32795}Htio bih postati|admiral prije nego umrem. 
{32805}{32835}Dat æu sve od sebe,| Hart. 
{33507}{33523}Kapetane. 
{33525}{33618}Gornja strana, vidim nepoznati metalni|predmet koji strši s morskog dna. 
{33620}{33674}Našao je nešto.|Nastavite uz najveæu opreznost. 
{33677}{33700}Razumio. 
{33939}{33991}Gornja strana, našli smo|konzervu Coca-Cole. 
{34010}{34040} Prokleta konzerva. 
{34067}{34127}Svejedno je izvadite.|Volim kad mi je ocean èist. 
{34260}{34324} Iskljuèi tu opremu.|Imamo ronioca dolje. 
{34326}{34367} To nije naš sonar.| Što to prièaš?
{34415}{34434} Sranje. 
{34483}{34523}Alpha Whiskey,|ovdje Charlie Victor. 
{34533}{34611}Imam nepoznati objekt u mojem okrugu| vjerojatno podmornica. 
{34653}{34740}Plavi Ronioèe, Plavi Ronioèe imamo kontakt s | nepoznatim. Vjerojatno ruska podmornica. 
{34745}{34840}Smjer 2-0-9 brzinom od 16 èvorova|i kreæe se toèno prema vama. 
{34842}{34925}Poduzmite hitne mjere izbjegavanja.|Ponavljam, hitne mjere izbjegavanja. 
{34927}{35053}Pripremite se za hitno izranjanje.|Plavi Ronioèe, da li me èuješ?
{35055}{35075}Plavi Ronioèe?
{35165}{35191}Javi mi se,| Carl. 
{35918}{35946} Javi se,| Carl. 
{36268}{36300}Hajde,| Plavi Ronioèe. 
{36540}{36600}Narednièe, recite stanici za ronjenje|da nam pripremi zamjenu. 
{36640}{36663}Javi se, Carl. 
{36917}{36958}Hajde, Carl. 
{37425}{37512} Carl, èuješ li me?| Ovdje sam, kapetane. 
{37533}{37554} Tu je. 
{37584}{37632}Spremi se za izranjanje, Carl.|Vraæamo te kuæi. Razumio. 
{37870}{37970}Hoæeš mi uèiniti uslugu?   Kada me budeš htio| uplašiti slijedeæi puta, bar me prvo upozori. 
{38260}{38325}Kapetane, podmornica je podigla|pola morskog dna. 
{38328}{38402} Našla je za nas!|Šališ se. 
{38438}{38454}Oh, da!
{38475}{38536}Misli da ju je našao.|Da, imaš je. 
{38545}{38568}To je to.| Imaš je. 
{38640}{38721}Mirno! Mirno!|Uvlaèim je!
{38743}{38802} Podignite je!| Izvucite je, momci. 
{38821}{38878}Mirno!| Izlazi s lijeve strane. 
{38880}{38919}Idemo, momci!| Imamo nuklearku!
{38938}{39028}Izlazi, momci!|Hajdemo sad! Hajdemo, momci!
{39060}{39087}Baš je teška. 
{39433}{39453}Pokret!
{40970}{40984}Jo?
{41165}{41220}Dušo. Dušo. 
{41256}{41287}Tako sam se uplašila. 
{41293}{41330}Oprosti mi. 
{41505}{41548}Oh, sranje. 
{41653}{41745}Tvoja noga. . .|zamalo je odsjeèena. 
{41813}{41862}Trebat æe vremena da zacijeli. 
{41917}{42017}Vremenom, moæi æeš|hodati s-s-sa štapom. 
{42090}{42132}Mogu li još roniti?
{42205}{42245}Tako mi je žao. 
{43113}{43156}Hajde, Carl. 
{43353}{43442}G-ðo Sunday, vaš muž je|pronaðen pijan na javnoj plaži. 
{43447}{43557}On je alkoholièar i mora|ostati na lijeèenju 30 dana. 
{43562}{43633}Ako se zaljulja,| neæe pasti!
{43638}{43716}Ako padne,| past æe na takav naèin. . . 
{43721}{43841}da æe se moæi sakriti, a prolaznici æe  | pomisliti da je policajac. 
{43907}{43964}Niži oficir neæe piti!
{43969}{44052}A ako æe piti,| neæe se napiti!
{44057}{44148}A ako se napije,| neæe se poljuljati!
{44153}{44227}A ako se poljulja,| neæe pasti!
{44232}{44317}A ako padne, past æe|na takav naèin. . . 
{44322}{44410}da æe prolaznici|pomisliti da je policajac!
{44452}{44523}Svi smo krajnje ponosni na|vas, zapovjednièe Brashear. 
{44528}{44640}Sada se oporavite, da biste se mogli|vratiti kuæi i uživati u mirovini. 
{44678}{44763}Kako planirate provesti svoju|mirovinu, zapovjednièe Brashear? Kako je biti heroj?
{45267}{45297}Kako si?
{46273}{46302}Dušo. . . 
{46432}{46473}Više nikada neæeš roniti. 
{46589}{46634}I ono što sada moraš uraditi. . . 
{46657}{46702}ja ti tu ne mogu pomoæi. 
{46837}{46884}Ali kada budeš|spreman krenuti. . . 
{46894}{46947}i ako mi možeš obeæati
{46947}{47003}da više nikada neæeš piti, 
{47021}{47097}èekat æu te u onom autu tamo. 
{47198}{47236}Ali ako ne možeš. . . 
{47390}{47435}onda samo proði pored mene. 
{48516}{48549}Paket za vas,| gospodine. 
{49107}{49148}Želim se vratiti. 
{49165}{49230}Gdje to, zapovjednièe?|Punu ronilaèku dužnost. 
{49250}{49289}Želim ponovo roniti. 
{49296}{49397}Carl, shvaæam,| ali, uh
{49416}{49458}Ali to jednostavno nije moguæe. 
{49490}{49533} Dobar dan, admirale. 
{49544}{49597} Carl, ovo je kapetan Hanks. 
{49606}{49628}Zapovjednik Brashear. 
{49636}{49697}Kapetan Hanks je|prebaèen kao viši èasnik. . . 
{49698}{49780}u Kontrolnom Odboru u Pentagonu. 
{49800}{49836}Pridružit æe nam |se za par tjedana, 
{49842}{49925}da upozna ljude u prvim redovima,|da upozna njihove brige. 
{49932}{49992}Da, i da se okrene|zapovjednikovoj brizi. 
{49998}{50096}Da radi kao mornarièki ronilac sa|jednom zdravom nogom i drugom. 
{50113}{50169}Izvini.|Jednostavno nije moguæe. 
{50175}{50199}Odsijecite je. 
{50291}{50381}"Piloti povrijeðeni u nesreæama|su tražili da im se amputiraju udovi. 
{50387}{50463}Uz prave proteze, neki od njih|su se vratili na redovne dužnosti. "
{50494}{50520}Zato tražim od vas ovo:
{50526}{50644}Odsijecite mi nogu i sakupite|konzilij doktora za 12 tjedana. 
{50650}{50748}Tada æu pokazati da sam sposoban|da se vratim na punu ronilaèku dužnost. 
{50764}{50809}Želim postati|glavno-zapovijedajuæi. 
{50878}{50972}Cijenimo vašu hrabrost, zapovjednièe,|ma koliko bila pogrešno upuæena. 
{50978}{51014}Molim da nas izvinite. 
{51284}{51326}Ja sam doktor, Carl. 
{51335}{51393}Moje mišljenje ovdje nešto znaèi. 
{51486}{51521}Izgleda ne. 
{51574}{51626}Kako æeš se vratiti|s jednom nogom?
{51639}{51686}Nekada sam jedva znao èitati.|Pronašao sam naèin. 
{51690}{51715}Da. 
{51770}{51837}Mogu izdržati|mjesece na moru, 
{51862}{51918}opasne zadatke koje nikada|nisi odbijao, ali ovo. . . 
{51923}{51970}Što hoæeš od mene?
{52004}{52104}Hoæeš da se vratim kuæi, kosim travnjak,|da se vozim u kolicima ?
{52120}{52201} Kako æu pogledati svoga sina?|Njega ne miješaj u ovo. 
{52225}{52324}Ovo ne radiš ni zbog mene|ni zbog njega. Ovo je zbog tebe. 
{52336}{52387}Uvijek je bilo zbog tebe. 
{52419}{52457}Priznaj to,| Carl. 
{52483}{52544}Bar mi toliko pruži. 
{52785}{52842}Zašto mi radiš to?
{52963}{53000}Odgovori mi,| do vraga!
{53011}{53103}Ili odlazim odavde,|i više se ne vraæam. 
{53928}{53964}Volim te, Jo. 
{57383}{57433}Bježi od mene!
{57438}{57470}Govno jedno!
{57520}{57546} Kuharu. 
{57547}{57650}Prokletstvo! Izgleda da sam|propustio ludu zabavu. 
{57836}{57877} Svuda sam bio. 
{57891}{57928}Uglavnom nevolje. 
{57934}{58020} Mornarica mi je dala ronilaèku|školu druge klase u Little Creek-u. 
{58025}{58066}Svodi se na ništa. 
{58167}{58211}Obavio sam par razgovora. 
{58260}{58297}Od petka,| onaj kapetan Hanks
{58302}{58389}æe sakupiti medicinski odbor|i umiroviti te. 
{58449}{58515}Rekao je da imam 4 tjedna.| Lagao je, kuharu. 
{58522}{58600}Boli njega koliko sklekova|možeš napraviti s jednom nogom. 
{58606}{58679}Zamijenit æe i mene i tebe i sve iskusne|morske vukove u Mornarici. . . 
{58686}{58743}za jednog elektronièara s|naoèalama od pepeljare. 
{58748}{58794}Taj æe te otjerati u penziju. 
{58799}{58842}Vratila mi se noga.|Još nisam gotov. 
{58847}{58931}Ti imaš sad tu drvenu nogu i nikakve |šanse da pobijediš Hanksa, sinko. 
{59072}{59123}Sve što sam htio biti|u životu je Glavni Ronilac. 
{59124}{59158}Sve što sam ja|htio je da to ostanem. 
{59235}{59320}Ako hoæeš pobijediti Hanksa, moraš|ga zaobiæi. Idi pravo na vrh. 
{59355}{59379} Washington. 
{59419}{59495}- Zapovjednik Mornarièkog Osoblja.|Tako je. 
{59512}{59592}A ne trebaju im napuhana piskarala|poput Hanksa ništa više nego nama. 
{59675}{59723}Možda mogu|povuæi neke veze. 
{59885}{59932}Zašto radiš ovo,|Sunday?
{60018}{60057}Nerviraš ljude. 
{60075}{60189}Zapovjednièe Decker, vi ste glavni|za osoblje u ovoj bolnici, zar ne?
{60190}{60209}Da, gospodine. 
{60265}{60355}Kako to onda da ne znate|gdje je zapovjednik Brashear?
{60380}{60410}Lako ga je uoèiti. 
{60422}{60503}On je jedini crni |ronilac u Mornarici, 
{60515}{60545}i ima samo jednu nogu. 
{60572}{60663}Izgleda da je zapovjednik|prebaèen, gospodine. 
{60700}{60717}Gdje?
{60727}{60772}Po èijem nareðenju?| Sam je potpisao svoja nareðenja. 
{60809}{60877}Zovite Obalnu Patrolu.| Opustite se. Samo želimo razgovarati. 
{60930}{61012}Èekaj, èekaj. Ti znaš gdje|je Brashear. Gdje je?
{61092}{61180}Shvaæam. Dobro. Zapovjednik Brashear|je otišao bez prava na dopust. 
{61188}{61230}Hoæu da ga pronaðete i uhitite. 
{61232}{61328} Neæete ga naæi.|Što hoæete od mene, zapovjednièe?
{61332}{61390}4 tjedna za uvježbavanje,|onda proba pune spremnosti. . . 
{61405}{61464}i ponovno saslušanje kod|Zapovjednika osoblja mornarice. 
{61490}{61516}Zapovjednika ?!
{61520}{61565} Da, gospodine.|U bazi mornarice u Washingtonu?
{61566}{61614}Tako je.|Ništa od toga. 
{61748}{61795} Hoæe li ronioc|biti vraæen na položaj?
{61863}{61929}Izgleda da je zapovjednik Brashear, izgubivši| nogu za domovinu, postao nekakav heroj. 
{61978}{62000}Dobro. 
{62126}{62202}Dat æu ti saslušanje|pod jednim uvjetom, hm?
{62246}{62302}Ako ne uspije,| ti ideš u mirovinu. 
{62333}{62354} Uspjet æe. 
{63463}{63497}Minuta i pet, brže. 
{63551}{63623}Vidimo se na sudu. 
{65964}{66015}Kapetan Hanks je naredio|da ostanete ovdje, zapovjednièe. 
{66658}{66701}Molim vas sjednite,|zapovjednièe Brashear. 
{66845}{66913}Samo se u Vojsci pozdravlja|u  prostoriji, zapovjednièe. 
{66923}{66978}U Mornarici u kojoj sam ja odrastao,| pozdravljanje je opravdano
{67050}{67038}s obzirom na težinu situacije,| gospodine. 
{67098}{67143}Pa. . . sada smo u drugaèijoj|Mornarici, zapovjednièe. 
{67292}{67312}Pa  zapoènimo !
{67365}{67398}Zapovjednièe Brashear, 
{67400}{67469}jednog dana život drugog|ronioca može ovisiti o vama. 
{67481}{67521}Da li iskreno mislite|da kao èovjek. . 
{67620}{67710}Imate skoro 40.|Imate samo jednu nogu. 
{67711}{67753}mislite da se možete natjecati|sa zdravim i upola mlaðim roniocima?
{67818}{67905}Pitanje je, gospodine,|mogu li se oni natjecati sa mnom?
{67978}{68005} Donesite odijelo.|Da, gospodine. 
{68065}{68098}Ovdje nema pušenja,|zapovjednièe. 
{68480}{68528}Prouèavanja mornarièke|opreme za ronjenje. . . 
{68535}{68621}pokazuju da ako bi osoba|izgubila svijest. . . 
{68625}{68731}ili preminula, razlika u|karakteristikama plovnosti. . . 
{68743}{68855}proteze i prave noge|bi je omela da slobodno pliva. 
{68858}{68938}Mislite, ako bi se udavio,|ne bi isplivao, da?
{68944}{68994} Da, gospodine.|Obeæavam, 
{69013}{69130}ako poginem na moru, dat æu sve|od sebe da umrem kao marinac. 
{69750}{69812}Samo sam mislio da pogledate buduænost|dubokog ronjenja Vojne Mornarice
{69828}{69881}Ovo je najnovija HEO-2|oprema s miješanim plinom. 
{69890}{69960}Teži oko 100 kg,|i ljudi koji žele da je koriste, 
{69961}{70019}prije nego što i mogu poèeti|kvalifikacije za ronioce, 
{70020}{70107}morat æe u njoj preæi|12 koraka, bez pomoæi. 
{70169}{70214}Možete li vi to,|zapovjednièe Brashear?
{70400}{70429}Da, gospodine,| mogu. 
{70492}{70511}Pa. . . shvaæam. 
{70547}{70587}Ma koliko mi bilo mrsko da ovo|produžavam još jedan dan, 
{70590}{70636}ipak hoæu,| u interesu temeljitosti, 
{70650}{70705}pripremite se da pokažete|svoju sposobnost. 
{70706}{70760}Ovdje, gospodine.| Odmah. 
{70803}{70854}Sinko, skloni se, ili æu|ti morati slomiti vilicu. 
{70960}{71019}Zapovjednièe Brashear,|mislim da nije odgovarajuæe. . . 
{71021}{71148} Hoæu da svi to vide. Kapetane Hanks,|slažem se s vašom ocjenom
{71255}{71322}Èak i ovi klizavi podovi onemoguæavaju da se|to ovdje pokaže, gospodine. 
{71324}{71438}Zapovjednièe Sunday, nije li vam bilo dosta|nevolja u vašoj karijeri?  Vaš savjet nije dobrodošao. 
{71450}{71519}Tko je ovaj èovjek?|Zapovjednik Leslie W. Sunday. 
{71550}{71641}Isplivali ste iz Saint Lo-a|u zaljevu Leyte. 
{71676}{71756}Zadržali ste dah 4 minuta. 
{71760}{71782}Pet, gospodine. 
{71869}{71898}Neka ostane. 
{71963}{72006}Dobro.| Nebitno je. 
{72042}{72122}Gospodo,|vratimo se na naš problem. 
{72125}{72208}Ovo nije ni vrijeme ni mjesto|da zapovjednik Brashear. . . 
{72270}{72315}Izvinite, zapovjednièe,|postoji li problem?
{72433}{72557}Kapetane Hanks, proveo sam veæi dio svog |života u Mornarici pokušavajuæi uspjeti. 
{72575}{72655}S druge strane, taj moj poduhvat je nanio|velike gubitke onima koje volim. 
{72673}{72708}I oni su podnijeli mnoge žrtve. 
{72720}{72785}I oni su pretrpjeli veliku|bol podržavajuæi me. 
{72793}{72920}Ako preðem ovih 12 koraka danas,|vratite me u aktivnu službu. 
{72938}{72973}Vratite mi moju karijeru. 
{72989}{73051}Pustite me da je završim|i odem kuæi u miru. 
{73140}{73224}Zapovjednièe Brashear,|posao moderne mornarice. . . 
{73226}{73307}Oprostite, gospodine. Ali za mene,|Mornarica nije posao. 
{73327}{73412}Imamo mnoge tradicije. U mojoj|karijeri, proživio sam mnoge od njih. 
{73420}{73467}Neke su bile dobre,| neke loše. 
{73485}{73567}Pa ipak, danas uopæe ne bih bio|ovdje da nije naše najsvjetlije tradicije. 
{73604}{73629}A to je?
{73677}{73703}Èast,| gospodine. 
{73929}{73985}Nastavite,| zapovjednièe. 
{74070}{74090}Leslie?
{74148}{74170}Koju nogu imaš?
{74197}{74254}Onu s kojom hodam,| Leslie. 
{74275}{74317}Tako mi se zvao otac.|To ti smeta?
{74320}{74362}Oh, ne.| Uopæe ne. 
{74542}{74601}Stvar je lagana.|Slomit æe se kao èaèkalica. 
{74621}{74653}Ne ako se oslonim |na zdravu nogu. 
{74654}{74754}Preko 100 kg na jednoj nozi?|Onesvijestit æeš se do šestog koraka. 
{74822}{74868}Pomagaèi,| obucite ronioca. 
{76069}{76111}Ronioèe,| ustani. 
{76158}{76176}Pustite ga. 
{76227}{76273}Kapetane, ako se dobro|sjeæam pravila mornarice, 
{76278}{76334}roniocu se može|pomoæi da ustane. 
{76360}{76418}Ovo je mnogo mesinga da se|podigne iz sjedeæeg položaja. 
{76441}{76517}To je lijevani bakar, zapovjednièe.|Mesing ne koristimo veæ desetljeæe. 
{76529}{76607}A nova pravila nalažu da|ronioc mora ustati sam. 
{76618}{76660}Tako piše u novom pravilniku,| gospodine?
{76700}{76779}Ako smijem pitati, kapetane,|kako to da vi to znate?
{76789}{76816}Ja sam ga napisao. 
{76918}{76948}Da, gospodine. 
{77090}{77138}Ronioèe,| ustani. 
{77386}{77433}Ispravi opremu i priði poluzi. 
{77947}{77969}1. 
{78039}{78060}2. 
{78142}{78160}3. 
{78248}{78275}4. 
{78352}{78376}5. 
{78457}{78476}6. 
{78537}{78556}7. 
{78630}{78650}8. 
{78793}{78820}Gospodo,| njegova noga. 
{78850}{78924}Molim vas,| gospodo. 
{78980}{79056}Ronioèe, odstupi.| Ronioèe, ne obraæaj pažnju. 
{79060}{79100} Ovo je moj detalj.|Admirale. 
{79168}{79246}Proklet da si, kuharu,|pokreni tu guzicu! Daj mi tih 12!
{79534}{79590}9. Ronilac nije borac. 
{79591}{79682}On je struènjak za spašavanje.|10. 
{79685}{79776}Ako je nešto izgubljeno pod vodom, on ga naðe.|Ako je potonuo, on ga izvadi. 
{79779}{79817}Ako smeta,| on ga skloni!
{79848}{79963}11. Ako ima sreæe, umrijet æe|mlad 100 m ispod valova, 
{79966}{80034}jer je to najbliže èemu on|može priæi da bude heroj!
{80042}{80101}Èak i ne znam zašto itko želi|biti ronioc u Mornarici. 
{80120}{80174}Sada, doði ovdje,| kuhare!
{80296}{80333}Voljno. 
{80645}{80687}Pomagaèi,| skinite ronioca. 
{81240}{81320}Mornarica SAD s|ponosom vraæa. . . 
{81330}{81410}zapovjednika i ronioca|Carla Brasheara. . . 
{81412}{81479}u punu,| aktivnu službu. 
{81645}{81665}Hvala vam. 
{81930}{81950}Èestitam,| kapetane. 
{81965}{81985}Hvala vam. 
{82368}{82399}Mogu odustati. 
{82414}{82477}Èovjek za koga sam se udala nije|nikada odustao u cijelom životu. 
{82603}{82624}Volim te. 
{82640}{82712}I ja tebe, dušo.|I ja tebe. 
{83138}{83170}Dobro je bilo,| zapovjednièe. 
{83713}{83814}1968-e Carl Brashear je postao prvi|èovjek s amputacijom
{83815}{83915}koji se vratio na punu|aktivnu dužnost. Dvije godine kasnije
{83916}{84016}postao je prvi crnac |Glavni Ronilac. 
{84017}{84117}Nije se umirovio u|sljedeæih devet godina. 
{84120}{85170}{C:$0000FF}{y:ib} B & M |{C:$FF0000}{y:b} movies 
