{1}{1}23.976
{1371}{1431}DŽON HERNDON MERSER|25. JUNA, 1976.
{1438}{1486}''I ANÐELI PEVAJU''
{2270}{2373}PONOÆ U VRTU DOBRA I ZLA
{2897}{2954}Prestani da buljiš u mene, Flevijuse.
{2960}{3037}Znamo se otkad si se kurvao u ulici Bul.
{4167}{4221}Znate li gde mogu naæi taksi?
{4227}{4252}Upravo je otišao.
{4258}{4321}Prièekajte da se vrati.
{4327}{4368}Osim ako ne želite sa mnom.
{4374}{4421}- Idete li do ulice Džons?|- Iæi æu.
{4439}{4471}Odložite stvari onde.
{4596}{4655}Na desno, Gusarska Kuæa...
{4661}{4718}...sagraðena 1794.
{4724}{4819}Gusari i ostali ološ su tu|delili svoj plen.
{4862}{4917}Šerman je obitavao u Kuæi Grin-Meldrim...
{4923}{4993}...pošto je osvojio i spalio Atlantu.
{4999}{5040}Hteo je zapaliti Savanu...
{5046}{5121}...no meštani su ga opili|punèem "Èetam Artiljerija"...
{5127}{5185}...i zabavama,|te je odluèio...
{5191}{5237}...poštedeti naš lepi grad.
{5243}{5299}Forsajt Park, dame i gospodo.
{5918}{5954}Tražite li nešto?
{6001}{6025}Ne.
{6595}{6622}Gospodine Kelso?
{6627}{6675}Da li ste vi g. Kelso?
{6683}{6765}Ja sam Lorin Bekster.|Dobro došli u Savanu.
{6782}{6863}"Grad i selo" je moj omiljeni èasopis.
{6876}{6969}Zaboravljam na gostoljubivost.|Šta æete popiti?
{6993}{7035}Bilo šta hladno.
{7188}{7242}G. Vilijams je restaurirao ovu kuæu.
{7246}{7318}Saèuvao ih je puno od rušenja.
{7378}{7448}Letnjikovac je namenjen|Džimovim strankama...
{7453}{7515}...i gostima, kao vi.
{7771}{7800}Stigao je.
{7872}{7929}Dobro došli, g. Kelsi.
{7938}{8007}- Oprostite, g. Kelso?|- Džon Kelso.
{8011}{8059}Da. Ja sam Beti Harti.
{8064}{8103}Soni vas oèekuje.
{8109}{8156}Želim videti Džima Vilijamsa.
{8163}{8210}Soni je Džimov advokat.
{8317}{8349}Dobro...
{8355}{8388}...uðite, frajeru.
{8403}{8427}Džon Kelso.
{8455}{8531}Dobrodošli u antikvarnicu.|Izvolite sesti.
{8740}{8788}Obavestite me.
{8861}{8916}- Kako ste putovali?|- Dobro. G. Vilijams je rekao...
{8922}{9021}On æe doæi. Ali moramo najpre nešto rešiti.
{9027}{9114}Ugovor o poverljivosti.|Uobièajena stvar.
{9120}{9153}Kao i èlanak koji...
{9160}{9232}...odreðuje Džimovo pravo na autorstvo.
{9268}{9372}"Grad i selo" hoæe 2 kartice|teksta o Božiænoj zabavi.
{9378}{9443}Obièna razglednica.|Šalite se?
{9457}{9499}To nije obièna zabava.
{9549}{9587}Razgovarali ste s èasopisom?
{9593}{9664}Bolje vi, no neki advokat iz Njujorka.
{9707}{9750}Bilo kako bilo...
{9770}{9813}...ja to neæu potpisati.
{9843}{9884}Ali zašto?
{9903}{9951}To je samo èlanak o zabavi.
{9962}{10015}Razlog više da ne popustim.
{10021}{10091}Profesionalac ste, sigurno se razumemo.
{10217}{10252}Obeæavate nepristranost?
{10265}{10308}Da, svakako.
{10513}{10536}Džim...
{10573}{10616}...ovo je Džon Kelso.
{10623}{10649}Kako ste?
{10691}{10743}Da prošetamo, deèko?
{10843}{10897}Krenimo ka Forsajt Parku.
{11179}{11211}Možete li...?
{11217}{11258}Naravno, Beti.
{11284}{11308}Hajdemo.
{11489}{11528}Potpisali ste Sonijev ugovor?
{11536}{11564}Zapravo, ne.
{11593}{11692}Bolje. Soni preljubomorno èuva moja prava.
{11707}{11761}- Šetate psa, g. Glover?|- Da, gospodine.
{11767}{11826}Patrik voli jutarnju šetnju.
{11964}{12041}Molim vas?|Možete li me slikati s Agom?
{12051}{12075}Divno.
{12082}{12108}Hvala.
{12153}{12195}U redu. Smešak.
{12250}{12292}Hvala. Dobar pas.
{12332}{12355}Hvala vam puno.
{12360}{12393}Hvala vama.
{12429}{12502}Šta god mi uèinili, g. Kelso...
{12510}{12563}...Aga æe biti slavniji od nas.
{12582}{12609}On je univerzitetska maskota.
{12616}{12661}- "Buldog iz Džordžije."|- Stvarno?
{12670}{12767}Glupa primedba, no onaj èovek|je rekao da šeta psa.
{12815}{12841}Kakvog psa?
{12848}{12902}G. Glover je radio kod advokata.
{12912}{13016}G. Buhan je testamentom odredio|da g. Glover bude plaæen...
{13021}{13099}... 15$ nedeljno za šetanje Patrika,|njegovog labradora.
{13108}{13134}No...
{13156}{13179}...gde je Patrik?
{13187}{13304}Patrik nas je napustio 2 godine|posle g. Buhana, oko 1974.
{13309}{13358}- Pas je umro.|- Tako je.
{13385}{13439}A zašto g. Glover ne šeta Agu?
{13513}{13559}A ko bi tada šetao Patrika?
{13651}{13687}Jasno.
{13750}{13799}- Evo nas.|- Ovo je vaša kuæa?
{13819}{13916}Sagradio je general Hju Merser 1860.,|no nije tu nikad živeo.
{13925}{13974}Praded Džonija Mersera.
{13980}{14007}Tekstopisca?
{14015}{14046}Sin Savane.
{14066}{14111}Koja vam je njegova|najomiljenija kompozicija?
{14127}{14201}Moja majka je obožavala "Fools Rush In."|(Samo budale žure)
{14210}{14240}Vaša majka.
{14258}{14282}Stvarno.
{14292}{14412}Rado bih vam sve pokazao,|no u toku su pripreme za zabavu.
{14435}{14480}Zar nije zabava sutra uveèe?
{14488}{14523}Biæe dve zabave.
{14531}{14603}Veèeras je za neženje.|Samo za muškarce.
{14634}{14662}Želite li doæi?
{14690}{14716}Rado bih pisao o tome.
{14723}{14802}Žao mi je. Privatno je.|Zabranjeno za novinare.
{14808}{14883}Želite li videti moju radionicu?|U letnjikovcu je.
{14944}{15061}To je jedna od najveæih kuæa u Savani.|Zauzima èitav blok.
{15069}{15102}Moja radionica.
{15110}{15155}Ovde se obavljaju sve...
{15162}{15199}...restauracije.
{15488}{15534}Ovaj pejzaž, to je Stabs?
{15551}{15578}Bravo.
{15595}{15630}Moj je otac bio trgovac.
{15637}{15711}Naziv je|Ledina Njumarket s konjušnicom.
{15719}{15786}Nedavna kupovina.|Izložiæu je sutra uveèe.
{15796}{15834}Izvanredno delo.
{15849}{15892}Zanimljiv namaz boja.
{15918}{15945}Crno svetlo?
{16189}{16212}Donji sloj je preslikan.
{16234}{16275}Bravo, deèko.
{16384}{16434}- Pregledali ste rendgenom?|- Ne.
{16457}{16501}Kako æete znati šta je ispod?
{16546}{16592}Više volim ne znati.
{17995}{18025}Samo trenutak.
{18221}{18262}- Ko je to?|- Mendi.
{18269}{18291}Ko?
{18338}{18367}Ne poznajem Mendi.
{18373}{18435}I neæete, ako ne otvorite vrata.
{18477}{18524}Drago mi je.
{18736}{18784}Imate li leda?
{18841}{18874}Naravno, poslužite se.
{18886}{18963}Hladnjak Džoa Odoma je nikakav.|A osim toga...
{18969}{19021}...sada nema ni struje.
{19069}{19101}Žedni?
{19127}{19181}Ja? Ne, zapravo ne.
{19225}{19325}Kad ste žedni, jedna èaša leèi.|Ako niste, onda spreèava.
{19332}{19390}Bolje spreèiti nego leèiti.
{19461}{19510}Obucite pantalone, Džon Kelso.
{19573}{19611}Odmah, samo da ih naðem.
{19681}{19753}Novi dodatak kuæi Odom.
{19761}{19844}Pogledajte, Džo rešava|naš problem sa strujom.
{19906}{19997}Veæ sam to radio i nije me ubilo.
{20003}{20063}Uvek postoji prvi put.
{20248}{20270}Evo!
{20276}{20306}Gotovo!
{20336}{20359}Nema problema.
{20370}{20397}Džo Odom?
{20403}{20434}Jedan, jedini.
{20443}{20477}Gde mi je èaša?
{20484}{20505}Pridržite.
{20548}{20603}Za struju Savane!
{20619}{20677}I ne zaboravimo na prijatelje...
{20691}{20714}...koji...
{20725}{20743}...bilo koje!
{20781}{20839}Za vas! Uðimo.
{20864}{20973}Imaæeš posla.|Veruj mi, znam šta govorim.
{20999}{21070}Upoznao si g. Kelsoa,|poslednju prinovu?
{21077}{21110}Džeri Spens.
{21116}{21159}- Kako ste?|- Oèaran sam.
{21166}{21219}- Kako ste vi?|- Nije loše.
{21225}{21278}- Pohaða moju crkvu?|- Pitam se.
{21286}{21311}Episkopalna crkva.
{21317}{21347}Videæemo.
{21353}{21384}Ozdravljujem
{21399}{21463}Duge se noæi vuku|u velikim limenkama
{21520}{21601}Nadam se da æe mi ona|dozvoliti biti snažan
{21637}{21697}Na smetlištu|vodiæemo ljubav
{21703}{21757}Na smetlištu|pod okriljem zvezda
{21763}{21820}Na smetlištu|oseæam miris raja
{21826}{21864}Neæeš me morati dvaput pitati
{21870}{21933}Mogu samo o tome maštati
{21939}{22003}Ja i ta propala devojka|vodimo ljubav na smetlištu
{22309}{22331}Sviða vam se?
{22337}{22366}Žestoko.
{22375}{22442}Žestoko i dobro.|Punè "Èetam Artiljerija".
{22449}{22473}Šta ima u njemu?
{22479}{22522}3 dela voæa, 7 dela likera.
{22529}{22578}Sve što nam se naðe pri ruci.
{22586}{22627}Divna zabava. Divna kuæa.
{22653}{22762}Vlasnik je na godinu dana u Evropi.|Zamolio me da pripazim.
{22769}{22802}Zalivam cveæe.
{22883}{22904}Zaposeli ste kuæu?
{22938}{22982}Prejaka reè.
{22990}{23031}Vi niste advokat?
{23073}{23150}Dobro. Advokati su smeæe.|Znam to...
{23157}{23221}...jer sam i ja bio jedan.
{23231}{23255}Bio?
{23271}{23350}Sveèano su me se rešili pre dve godine.
{23357}{23404}Neka sitnica u raèunovodstvu.
{23419}{23450}A šta sada radite?
{23456}{23526}Mendi i ja æemo otvoriti bar s klavirom.
{23534}{23560}Veæ imate jedan.
{23566}{23603}Tako izgleda, zar ne?
{23616}{23670}Trenutak. Prekinite muziku.
{23677}{23699}Pogledaj.
{23747}{23778}Pogledaj ovo.
{23786}{23813}Džeri Spens.
{23842}{23910}Opet si se nadmašio.
{23916}{24006}Frizura dostojna buduæe bivše...
{24014}{24049}...gðe Džoa Odoma.
{24067}{24110}Sanjaj i dalje, dragi.
{24120}{24150}Zaljubljena si.
{24240}{24290}Lepa žena.
{24299}{24334}Vereni ste?
{24364}{24391}Ne još.
{24434}{24510}Kasno je. Dižem se rano.|Bilo mi je drago.
{24516}{24551}Ne, prièekajte.
{24572}{24614}Džoovo pravilo broj 2:
{24620}{24720}Ako moraš krenuti,|nemoj bez zaliha.
{24745}{24805}Ovo je dovoljno za put.|Bilo mi je drago.
{24988}{25013}Hej, vi.
{25036}{25098}Na zabavama je bolje se osamiti, zar ne?
{25154}{25187}Hvala na pozivu.
{25193}{25219}Kad god želite.
{25225}{25256}Uvek.
{25416}{25445}Malopre...
{25451}{25484}...kako ste znali moje ime?
{25491}{25531}Dobro došli u Savanu.
{25724}{25753}G. Džon Kelso?
{25805}{25828}Ovo je za vas.
{26029}{26112}"Ostavite poruku i javiæu vam se."
{26198}{26256}"Vidimo se veèeras, deèko!"
{26615}{26653}- G. Kelso?|- Da.
{26659}{26725}Lusil Rajt.|Pripremam zabave za g. Vilijamsa.
{26730}{26774}- Drago mi je.|- Biæe ovde za èas.
{26780}{26824}Želite li videti šta služimo?
{26830}{26859}Naravno.
{26865}{26892}Doðite.
{26950}{27006}Puno svežeg povræa...
{27013}{27052}...tople lepinje...
{27058}{27093}...divovski raèiæi.
{27133}{27198}Da vidim.|Dimljena šunka i æuretina.
{27212}{27231}Oboje.
{27237}{27335}Veliki poslužavnik s voæem.|I predivno jelo od rakova.
{27341}{27364}Raèja supa?
{27379}{27397}Džef Brazvel.
{27438}{27520}- Slikam Džimove zabave.|- Slikajte celi sto.
{27526}{27586}"Grad i selo" želi lepe slike.
{27597}{27647}I kolaèiæi od bundeve.
{27680}{27769}G. Vilijams zahteva domaæu hranu za zabave.
{27782}{27852}Veèeras æete se dobro zabaviti.
{27858}{27902}U pravu ste, Lusil.
{27929}{27988}Odgovara vam. Broj 44.
{28077}{28135}Imam oko za to.
{28193}{28243}Dobro došli u Kuæu Merser.
{28266}{28326}Ove godine nadmašili ste samu sebe.
{28332}{28368}Hvala vam.
{29233}{29268}Sreæan Božiæ.
{29276}{29311}Sreæan Božiæ.
{29316}{29403}Èovek s cigarom.|Drago mi je da ste se vratili.
{29422}{29445}Ema.
{29484}{29549}Saèuvali ste mi èašu?|Sreæan Božiæ.
{29555}{29615}Mislio sam da æete mi je ukrasti.
{29628}{29667}- Senatore, kako ste?|- Izvrsno.
{29684}{29763}Sreæan Božiæ.|Drago mi je da ste tu.
{29785}{29815}Pogledaj ko je tu.
{29873}{29921}Dobro došli u Kuæu Merser.
{30417}{30492}Mislim da je zabava uspela.
{30503}{30555}Moja neæakinja.|Doði da te zagrlim.
{30665}{30711}- Kako ste?|- Džon Kelso.
{30991}{31085}Draga! Izgledaš predivno.
{31091}{31135}Imam istu takvu kuæi.
{31160}{31222}Naša smaragdna ptica je došla.
{31239}{31299}Lepo je videti te.|Naoèit kao uvek.
{31305}{31363}- Kako si draga?|- Izvrsno.
{31484}{31536}Ko je to predivno stvorenje?
{31542}{31574}To je Serena Dous.
{31580}{31634}Serena, blistaš kao uvek.
{31640}{31671}Trudim se.
{31677}{31723}Nekad poznata lepotica.
{31729}{31817}Kad joj je umro bogati muž,|vratila se u Savanu...
{31823}{31893}...i pretvorila spavaæu sobu u lièni muzej.
{31898}{31933}Upoznaæu vas.
{31939}{31997}- Izgledaš divno.|- Ko su svi ti ljudi?
{32041}{32104}Divno je videti te van kreveta.
{32137}{32224}Za tebe æu, Džime,|uvek izaæi iz kreveta.
{32322}{32425}Heri nam upravo pokazuje|svoju nedavnu kupovinu.
{32484}{32548}Znate li šta je to?|pištolj velikog kalibra.
{32555}{32633}Moj pokojni muž je prosvirao|sebi mozak s takvim.
{32638}{32687}- I moj.|- Molim?
{32696}{32791}Baš sam si spremala piæe,|kad sam èula pucanj.
{32799}{32912}Pomislih da zvuk dolazi s televizije,|no to je Lajman krvario...
{32918}{32980}...u svom omiljenom naslonjaèu.
{32986}{33049}Svi su znali da je naš brak promašaj.
{33055}{33170}Da sam dodirnula oružje,|optužili bi me za ubistvo.
{33239}{33288}Jednog æu dana...
{33385}{33472}...ubiti nekoga.|Mogu zapoèeti s vama. Ili vama.
{33629}{33672}- Da li je napunjen?|- Oh, da.
{33724}{33761}Kome da se pridružimo?
{33767}{33831}Tamo gde nam ne preti pucnjava.
{33844}{33885}Oprostite na tren.
{34389}{34448}To je s Napoleonovog krunisanja.
{34474}{34515}Posedujete impresivnu zbirku.
{34539}{34629}Ne, g. Kelso. To nije zbirka,|to je moj dom.
{34635}{34689}- Faberže?|- Zanima me malo.
{34695}{34747}Malo? Tri jaja...
{34757}{34825}...kutija s draguljima i pozlaæeni album.
{34836}{34910}Èak bi i car Nikola bio zadovoljan s tim.
{34984}{35005}Zar ne?
{35011}{35043}Priznajem.
{35074}{35135}Želite li videti nešto malo...
{35142}{35174}...neuobièajenoga?
{35180}{35217}Vrlo rado.
{35366}{35408}Draga majko.
{35414}{35483}- Zabavljaš se?|- Predivno je.
{35489}{35519}Džon Kelso.
{35535}{35574}On je pisac, majko.
{35782}{35838}To nazivamo salonom za ples.
{35959}{36002}To je ta skupocena relikvija?
{36011}{36069}Vrlo retka relikvija.
{36150}{36230}To je bodež kojim je princ Jusupov...
{36242}{36278}...usmrtio Raspuæina.
{36346}{36408}Otkinuo mu je i kurac i jaja.
{36414}{36444}Istinito...
{36450}{36515}...i pomalo izopaèeno, zar ne?
{36534}{36563}Pomalo.
{36645}{36672}Nemaèki Luger?
{36678}{36746}Pažljivo, napunjen je.|Bili smo opljaèkani.
{36774}{36829}Svi imaju napunjeno oružje.
{36877}{36941}Vaša porodica oduvek sakuplja zbirke?
{36947}{37045}Uètiv naèin da me pitate|da li sam nasledio bogatstvo.
{37063}{37101}- Jeste li?|- Ne.
{37127}{37204}Roðen sam u Gordonu, u Džordžiji,|malom mestu kraj Mejkona.
{37210}{37266}Otac mi je bio brijaè,|a ponekad i zidar.
{37272}{37312}Majka mi je bila sekretarica.
{37318}{37381}Novac sam stekao u poslednjih 11 godina.
{37392}{37443}Da, ja sam...
{37449}{37488}...sveži bogataš.
{37494}{37553}Ali reè bogataš je glavna.
{37570}{37612}Samo me dve stvari zanimaju...
{37618}{37643}...rad...
{37649}{37734}...i znamenja aristokrate,|vredni uloga.
{37741}{37833}Stvari koje moraju prodati|kad nema više novaca.
{37839}{37880}A novaca uvek nestaje.
{37889}{37940}I ostaje im jedino...
{37954}{37996}...njihovo lepo ophoðenje.
{38002}{38075}Odjebi, glupa kuèko!
{38090}{38138}Ne puštaju me da uðem.
{38144}{38184}Moram kroz ulaz za poslugu.
{38211}{38245}Oprostite trenutak?
{38308}{38356}Nisi smeo doæi veèeras.
{38362}{38406}Ne seri.
{38412}{38492}Zajebali su me i besan sam.|Daj mi 20$.
{38527}{38592}U petak je isplata za sve.
{38598}{38624}Daj mi 20$.
{38630}{38720}- Moram se otkaèiti.|- Mislim da veæ jesi.
{38737}{38760}Daj mi novac.
{38767}{38833}Nisam još dovoljno otkaèen.
{38839}{38909}Neæu ti dati novaca|za alkohol ili travu...
{38915}{38953}...ili šta veæ nameravaš...
{38975}{39003}Jebi se, Džim!
{39009}{39102}Ne preti mi! Upozoravam te.|Ozbiljno govorim.
{39241}{39284}A ti seronjo!
{39345}{39386}Bolje se pripazi.
{39446}{39474}Jebi se.
{39822}{39917}Bili Henson.|Zaposlen je pola radnog vremena...
{39930}{39998}...i povremeno je prilièno slikovit.
{40597}{40687}Ne znam ko me više mrzi,|Etveli ili njihovi psi.
{40693}{40793}Etvel je ljut na mene otkad|sam ga maknuo iz veæa.
{40911}{40966}Postoji samo jedan lek tome.
{42520}{42558}Hvala, senatore.
{42564}{42612}Ðavolska zabava, Džim.
{42619}{42678}- Nadmašili ste se.|- Predivno.
{42685}{42751}Stvarno smo uživali.|Hvala na pozivu.
{43004}{43043}Ovo je...|Imate moju knjigu.
{43051}{43093}Izgledate iznenaðeno.
{43115}{43184}Nisu se baš grabili za njom.
{43359}{43429}Kakva sluèajnost da su mi dodelili...
{43437}{43514}...prilog, a vi ste proèitali|moju jedinu knjigu.
{43561}{43611}To nije sluèajnost.
{43625}{43687}Da li ste ikad pisali za "Grad i selo"?
{43694}{43717}Ne.
{43815}{43851}Vi ste tražili mene?
{43910}{43982}Veæ godinama žele pisati o Božiænoj zabavi.
{43989}{44099}Ove sam godine pristao pod jednim uvetom:
{44105}{44144}Vašim uèestvovanjem.
{44223}{44253}Hvala vam.
{44279}{44316}Ne, hvala vama.
{44349}{44466}Opustite se, uživajte u konjaku|i isprièajte mi vaš život.
{44575}{44632}Kasno je, a sutra rano putujem...
{44638}{44725}...pa bolje da odložimo.|Za sledeæi Božiæ.
{44745}{44786}Ako budete na popisu.
{44810}{44853}Nadajmo se najboljem.
{44860}{44941}Jedva èekam èlanak i nadam se|da je bilo dovoljno...
{44953}{44990}...za esej od 2 kartice.
{44997}{45043}Imam materijala za 30 kartica.
{45049}{45097}Hvala. Ne morate me pratiti.
{45203}{45241}I, deèko...
{45301}{45344}...uistinu mi se svidela knjiga.
{45379}{45405}Hvala.
{45890}{45937}IDENTIFIKACIONO ODELENJE
{45943}{46013}Divna jakna.|Od ugrožene vrste.
{46019}{46101}14-karatno zlato i|Groznica subotnje veèeri.
{46107}{46139}Ko je gladan?
{46160}{46205}Malo punèa, lutko?
{46211}{46274}Divan poni.
{46288}{46349}Šta to radiš, opijaš konja?
{46377}{46400}Šta se dogaða?
{46408}{46465}Džim Vilijams je upucao nekoga.
{46471}{46497}Sendviè?
{46515}{46537}Molim?
{46544}{46627}Upravo tako.|To osvetljenje nije zbog Božiæa.
{46634}{46655}Stvarno?
{46661}{46714}Da. Upucao je nekoga.
{46747}{46787}Pogledaj kako juri.
{46793}{46839}Poèinje mi se sviðati taj Jenki.
{46845}{46936}Šta ono kažu?|Radoznalost je dotukla Jenkije.
{47083}{47169}Bio je pijaniji kad se vratio,|a verujte mi...
{47185}{47293}...kad je pijan,|potpuno se promeni.
{47316}{47377}Veæ je ranije porazbijao stvari.
{47385}{47461}Verovatno je pogledao neki loš film...
{47468}{47516}...neku prièu o|prorezanim grkljanima.
{47522}{47634}Verovatno ga je to razjarilo,|jer nije nikad bio takav.
{47648}{47705}Posvaðali smo se.
{47713}{47813}Uništio je taj skupoceni|antièki sat u predvorju.
{47820}{47850}Ako želite...
{47864}{47891}...nešto žešæe...
{47897}{47932}...bar je u dnevnoj sobi.
{47938}{47986}Ne, hvala.|Još sam na dužnosti.
{48039}{48066}Znam.
{48109}{48137}Žao mi je.
{48146}{48194}Sve je to uznemirujuæe.
{48216}{48272}Hoæe li još dugo trajati?
{48492}{48530}Šta vi tu radite?
{48538}{48595}Radim i za grad.|Imam slike sa zabave.
{48601}{48631}Poslaæu vam ih.
{48638}{48668}Dobro, dobro.
{48905}{48987}Upao je u moju kancelariju|i poèeo se drati...
{48994}{49084}... "Možda sutra odlazim,|no ti æeš otiæi veèeras."
{49090}{49190}Tada je dvaput zapucao.|Zgrabio sam Luger i odvratio.
{49196}{49273}I vi biste isto tako reagovali.
{49279}{49358}Nisam se nikad tako uplašio.|Da nisam pucao...
{49365}{49443}...sutra ujutro biste èitali moju posmrtnicu.
{49450}{49504}- Šta vi tu radite?|- Bilo je otvoreno.
{49510}{49542}Isuse, Frenk!
{49570}{49618}Moj klijent neæe ništa izjaviti.
{49674}{49747}Ne mogu verovati da me nisi pozvao!
{49753}{49797}Koliko se dugo znamo?!
{49803}{49874}Šta se doðavola zbiva?
{50851}{50914}Nisam ga imao vremena razviti.
{50919}{50968}Film sa zabave.
{51248}{51323}Džim je rekao da ste èuli Hensonove pretnje.
{51339}{51379}Taj mali žigolo.
{51387}{51442}Rekao sam Džimu da je opasan.
{51585}{51622}Zaboravi "Grad i selo".
{51628}{51724}Znam, tek je treæi dan i to je|obièno ubistvo, no saèekaj.
{51730}{51809}To je poludela verzija|"Prohujalo sa vihorom".
{51828}{51888}Znam da si moj agent. Poslušaj.
{51894}{51973}Šetaju na uzici pse koji ne postoje.
{51978}{52036}Naoružani su do zuba i pijani.|Njujork je dosadan.
{52042}{52073}Nazvaæu te kasnije.
{52109}{52210}Lardžent želi biti ponovno izabran,|iæi æe do suðenja.
{52214}{52268}Ne odgovara na moje pozive...
{52273}{52325}...moraæemo na stražnja vrata.
{52331}{52364}Vraæam se.
{52370}{52418}Hvala što ste došli, frajeru.
{52429}{52470}Džim je u kancelariji.
{52610}{52668}Želimo vam nešto predložiti.
{52676}{52722}Da ne napišem èlanak.
{52740}{52763}U redu.
{52813}{52849}Divno.
{52919}{52942}Zašto?
{52973}{53009}Zapravo...
{53019}{53052}...razmišljao sam...
{53061}{53092}...da napišem knjigu.
{53106}{53164}Isuse. Knjigu o èemu?
{53169}{53214}To je obièna samoodbrana.
{53219}{53296}Zašto onda strepite od tužioca?|Èuo sam u hodniku.
{53302}{53342}Ovo je mali grad.
{53347}{53410}Moramo obraniti naš ugled...
{53418}{53462}...od vanjskog sveta.
{53472}{53547}Ako se proèuje da nas neko|iz Njujorka ocrnjuje...
{53559}{53618}...meštani Savane æe zanemeti.
{53643}{53692}Pozvaæete me za svedoka?
{53701}{53734}Pretite mi?
{53740}{53765}Nikako.
{53774}{53840}Lažna zakletva vodi u zatvor.
{53848}{53925}Ne nameravam to.|Nemam iskustva s ubistvima.
{53934}{53973}Ako nije ništa važno...
{53983}{54017}...ne morate brinuti.
{54029}{54114}Plaæen sam da brinem.|Neæu vam dozvoliti.
{54218}{54275}Ne treba mi nièija dozvola.
{54299}{54329}Zapravo ne treba.
{54389}{54437}Zašto je onda tražite?
{54528}{54564}Treba vam moja dozvola...
{54570}{54595}...moja pomoæ...
{54601}{54641}...moj pristanak...
{54657}{54699}...inaèe nemate o èemu pisati.
{54724}{54753}Zapravo nemate.
{54773}{54817}Oboje smo svesni toga.
{54882}{54944}Dakle, uzajamna pomoæ?
{54963}{54992}Kako to mislite?
{55042}{55138}Razmenjivaæete informacije|do kojih doðete, s nama?
{55185}{55252}Da, ali neæu menjati svoj tekst.
{55260}{55333}A vi ga neæete videti pre izdavanja.
{55613}{55638}Dakle...
{55651}{55711}...ko æe biti glavni lik u knjizi?
{55878}{55936}Veæ ste tako nešto izveštavali?
{55942}{55992}Ponekad za Eskvajer.
{55998}{56029}Šta vi mislite?
{56035}{56066}Šta ja mislim?
{56077}{56152}Brine vas tužioc?|Porota prati štampu.
{56158}{56216}Možemo iskoristiti medije.
{56222}{56268}O èemu vi prièate?
{56274}{56343}Henson se prostituisao.|Je li registrovan?
{56349}{56395}Narkoman? Diler? Makro?
{56401}{56457}To može uticati na porotu.
{56463}{56503}Neka detektivi istraže.
{56510}{56576}Ovde su detektivi zapravo policajci.
{56590}{56655}Uostalom,|zašto nam treba detektiv...
{56661}{56740}...kad imamo pisca iz Njujorka...
{56746}{56790}...koji ima odgovor na sve?
{56848}{56881}Èuvajte se, frajeru.
{57381}{57431}- Vi ste iz cveæare?|- Ne, ja sam Džon Kelso.
{57436}{57493}Pisac sam i hteo bih znati...
{57499}{57559}Ako nisi iz cveæare, ostavi me.
{57565}{57659}Dama je u žalosti,|a nisam dobila ni ružu...
{57665}{57738}...ni kakav znak pažnje.|Molim te, ostavi me.
{57825}{57921}Bili Henson je tu živeo.|Hteo bih vas nešto pitati.
{57927}{57994}Mogu i kasnije navratiti.
{58000}{58117}Ne mogu verovati da si tako uporan.|Odakle si?
{58125}{58166}A pristojno ponašanje?
{58172}{58216}Ostavi me na miru.
{58284}{58338}Moje sauèešæe. Nazvaæu...
{58357}{58413}Vratiæu se, ili...
{59731}{59810}PORODIÈNO SAVETOVALIŠTE|DR. MAJRA BIŠOP
{60509}{60569}Izvinjavam se što pre nisam doneo.
{60613}{60731}Hvala, prekrasne su.|Stvarno su prekrasne.
{60737}{60804}Hteo bih vas nešto pitati.
{60816}{60860}Ovo je tvoj auto?
{60908}{60947}A da me odvedeš kuæi?
{61047}{61076}Hvala.
{61290}{61369}Pitam se, šta beli deèko kao ti...
{61374}{61482}...radi s ovim crnaèkim ofucanim autom?
{61488}{61567}Upravo sam ga kupio.|Nije tako loš.
{61574}{61638}Ne, nije loš.|Povredila sam ti oseæaje?
{61644}{61710}Žao mi je.|Nisam te htela povrediti.
{61714}{61798}To je jaèe od mene.|Govorim ono što oseæam.
{61804}{61852}Ne mogu sebi pomoæi. To je tako.
{61864}{61925}- Barem si siguran.|- U vezi èega?
{61931}{62020}Niko ti neæe pokušati ukrasti to sranje.
{62035}{62118}To mi je samo dok ne uštedim za Rols Rojs.
{62124}{62195}Šablis je lepo ime.|Neuobièajeno.
{62201}{62303}Hvala. Sa vinske boce.|To mi je ime za nastup.
{62309}{62400}- Vi ste glumica?|- Nisam. Ja sam umetnica.
{62407}{62469}Radim u Pik-Apu u ulici Kongres.
{62475}{62567}Plejbek, najavljujem, plešem|i slièno sranje.
{62573}{62667}Osoba koju sada gledaš je|obièna mala Šablis.
{62673}{62706}Ali uveèe...
{62712}{62793}...kad obuèem haljinu,|našminkam se...
{62798}{62864}...stavim svoj nakit i parfem...
{62870}{62924}...postajem "Dama Šablis".
{62983}{63043}Jako si dražestan.
{63049}{63105}Pravo belo vino za pravu crnu curu.
{63112}{63188}Ujedno i laskavac.
{63207}{63317}Vruæe je ovde.|To moje inekcije deluju.
{63355}{63378}Molim?
{63384}{63447}Da, dragi, moje inekcije.|Nije važno.
{63452}{63505}O èemu si hteo razgovarati?
{63542}{63571}Bili Henson.
{63619}{63708}Ne. Bili je mrtav.|Zatvoren sluèaj.
{63723}{63758}Bio je vaš deèko?
{63764}{63802}Bili, moj deèko?
{63808}{63844}Bili ste ljubavnici?
{63864}{63895}Ne. Doðavola, ne.
{63901}{63970}Bio je previše vulgaran za mene.|Ja sam dama.
{63976}{64043}Izlazio je s mojom cimerkom Korin.
{64080}{64172}To dvoje su se ludo zabavljali.
{64273}{64355}- Divne su.|- Recite mi više o Korin.
{64373}{64431}Ona je kao veæina devojaka.
{64446}{64527}Privlaèi je pogrešan tip muškaraca.
{64546}{64639}Bili nije bio dobar izbor.|Mislila je da ga može promeniti.
{64646}{64725}Ali nije bilo moguæe promeniti tog gada.
{64731}{64793}- Hteo bih razgovarati s njom.|- I ja bih.
{64800}{64901}Ali pobegla je, dugujuæi mi|dva meseca stanarine.
{64908}{64978}Bili je hteo platiti,|no sada je...
{65041}{65082}Ali on je...
{65089}{65140}- Izvolite.|- Hvala.
{65147}{65215}Kao što je moja mama govorila...
{65267}{65315}... "Dve suze u žlebu...
{65321}{65375}...sve odjebu. "
{65408}{65442}Moraæu to zapamtiti.
{65448}{65505}Nemoj. To nije za objavljivanje.
{65696}{65733}Otvoriæu vam vrata.
{66061}{66097}Hvala, dragi.
{66241}{66336}U telefonskom imeniku,|zapisani ste pod F. DiVo.
{66384}{66423}Šta znaèi taj "F"?
{66469}{66529}"F" je za Frenk, dragi.
{66535}{66566}To sam ja.
{66916}{66962}- Ona je on.|- Tako je.
{66966}{66998}Zezate me.
{67004}{67072}Ako se zakomplikuje,|poprièajte s njom.
{67078}{67124}Pristojni ljudi ne razgovaraju o tome.
{67135}{67181}Ne prikazuje povoljno Bilija.
{67187}{67266}Isprièaæu vam nešto.|Imali smo jednom sudiju...
{67272}{67359}...èiji se sin spetljao|s gangsterovom devojkom.
{67383}{67430}Jednog su ga jutra našli...
{67446}{67531}...na verandi, s genitalijama|obešenim o rever.
{67590}{67640}Mrtvi ne prièaju.
{67662}{67712}Sutradan je u novinama pisalo...
{67718}{67764}... "Kobni pad s verande".
{67794}{67840}I šta ste time hteli reæi?
{67855}{67958}U Savani, treba saèuvati obraz|pred neugodnostima.
{67994}{68060}Pokušaæu potražiti tu Korin.
{68075}{68118}Moram da idem.
{68124}{68198}Slavim Božiæ u Tajbi Ajslendu.|Biæe puno gostiju.
{68204}{68237}Sreæan Božiæ.
{68243}{68302}- I vama, Džon.|- Doviðenja, Aga.
{68523}{68574}Sreæan Božiæ!
{69629}{69668}Ima ih na žici!
{70216}{70255}Luter neæe da jede!
{70457}{70487}Raèun, molim.
{70520}{70553}Nije vam prijalo?
{70564}{70621}Ne, bilo je dobro. Izvrsno.
{70682}{70717}Šta ima u boèici?
{70757}{70837}Kaže da ima dovoljno otrova za sve nas.
{70882}{70931}Ako jede i ako je dan dobar...
{70937}{70960}...u redu.
{70977}{71005}Ako ne jede...
{71011}{71118}...recimo: na vašem mestu|danas ne bih pila vodu.
{71128}{71166}Gde stavlja otrov?
{71172}{71230}U gradski vodovod.
{71289}{71325}Vi u to verujete?
{71376}{71486}Dugo živim ovde, zlato.|Skoro svemu verujem.
{71573}{71605}Gde idemo?
{71611}{71658}Strpljenja, deèko.
{71767}{71864}Vreme je da upoznate|mog glavnog branioca.
{71876}{71911}Idemo na groblje?
{71917}{72004}Ne u Bonaventuru.|Groblje za obojene je malo niže.
{72803}{72893}Dr. Luis Bazard|1900-1981
{73526}{73602}Noæas imamo vrt samo za nas.
{73668}{73703}Upoznaj Minervu.
{73778}{73802}Kako ste?
{73844}{73887}Pokušavaš me zaèarati?
{73919}{73971}Vrati ruku natrag u džep.
{74158}{74207}Žalim te.
{74227}{74267}Reci zašto, Minerva.
{74279}{74327}Misli da ga niko ne voli.
{74415}{74458}Glupost. Mi se ne znamo.
{74530}{74565}U sebi nosiš prazninu.
{74571}{74610}I previše pitanja.
{74616}{74719}Nisi sposoban nigde iæi,|ako nemaš odgovore.
{74774}{74838}Nema odgovora.
{74968}{75050}Došao si izdaleka da bi to otkrio, zar ne?
{75124}{75194}A sada, na posao.|Doneo si novac?
{75251}{75278}Stavi na grob.
{75336}{75399}Poljubi ga prvo, da ti se vrati.
{75458}{75512}Doneo si sjajne novèiæe?
{75688}{75716}Zakopaj ih.
{75744}{75819}On radi protiv tebe, Džejms.
{75826}{75867}Ko? Dr. Bazard?
{75923}{75974}Deèko. Mrtvi mladiæ.
{75987}{76037}Bili. To me ne iznenaðuje.
{76043}{76078}Dr. Bazard?
{76130}{76166}Vreme za mrtve je kratko.
{76192}{76222}Vreme za mrtve?
{76244}{76283}Traje sat vremena.
{76291}{76372}Pola sata pre ponoæi do pola sata posle.
{76383}{76455}Pola sata pre ponoæi za dobre èari.
{76463}{76515}Pola sata posle, za zle.
{76521}{76576}Noæas nam trebaju oboje.
{76583}{76623}Imaš bocu s vodom?
{76681}{76724}Nije iz vodovoda?
{76756}{76788}Daj mi je.
{76907}{76945}Mora olabaviti svoj...
{76951}{77024}...pritisak na Džejmsa.
{77117}{77150}Treba mi duh Šango...
{77167}{77219}...i jedan mali hungan.
{77541}{77567}Doðite.
{77602}{77630}Doði!
{77754}{77802}Reci mi nešto o njemu.
{77822}{77857}Da me pokušao ubiti?
{77863}{77923}Ne, pre toga.|Nešto dobro.
{77968}{77996}Ljubazne reèi...
{78002}{78064}...æe se ukoreniti, procvetati|i blagosloviti te.
{78098}{78144}Nešto što ga je èinilo sretnim?
{78231}{78259}Njegov auto.
{78277}{78343}Obožavao ga je.|Niko mu nije smeo priæi.
{78349}{78403}Bio je njegov ponos i sreæa.
{78419}{78474}Nastavi govoriti. Deluje!
{78512}{78586}Obojio ga je u mat crno.
{78592}{78674}Potrošio bi sate na autu,|popravljajuæi ga...
{78680}{78704}...èisteæi ga.
{78710}{78765}Obojio ga je kao trkaèki auto...
{78771}{78814}...i podesio ga je u tom stilu.
{78831}{78867}Bio je jako kreativan.
{78934}{78988}Malo je ljudi znalo za to.
{78994}{79029}Bio je umetnik.
{79048}{79110}U trenutku dok si to izgovarao...
{79116}{79166}...osetila sam kako se opušta.
{79186}{79237}Èuo te kako govoriš da ga voliš.
{79315}{79378}To je besmisleno.|Pokušao me ubiti.
{79435}{79495}Borio se protiv tebe,|a sada znam zašto.
{79505}{79587}Želi da kažeš svima da si ga mrzeo.
{79612}{79670}Toliko da si ga ubio.
{79688}{79737}Uèiniš li to, iæi æeš u zatvor...
{79743}{79775}...i on to zna.
{79815}{79861}Najvažnija stvar:
{79888}{79987}Moraš svakog dana tražiti|oproštaj od njega.
{80131}{80177}A sada, zlo.
{80295}{80356}Brzo, brzo.|Reci mi njegovo ime.
{80368}{80403}Finli Lardžent.
{80419}{80533}Kad se vratiš kuæi, napiši na|papiru 7 puta njegovo ime.
{80539}{80589}Spoji sva imena.
{80595}{80646}"I" bez taèke, "T" bez crtice.
{80653}{80710}Preklopi dvaput i skloni u džep.
{80819}{80847}Naði njegovu sliku.
{80853}{80921}Zašij mu usta s krvljom golubice.
{80927}{80956}Zacrni mu oèi.
{80962}{81013}Krenite sada!|Imam posla.
{81112}{81138}Deèko!
{81160}{81203}Upamti ove reèi.
{81253}{81307}Da bi shvatio žive...
{81315}{81377}...moraš razgovarati s mrtvima.
{81460}{81483}Idite!
{81489}{81534}I nemojte se osvrtati!
{82285}{82319}Na grobu...
{82328}{82369}Ko je Dr. Bazard?
{82376}{82425}Minerva je bila udata za njega...
{82431}{82516}...najpoznatijeg vudu vraèa|u okrugu Bofort.
{82522}{82592}Možda ne znate, no ovo je zemlja vudua.
{82611}{82669}Ne verujem u trikove...
{82675}{82735}...veæ u duhovnu moæ.
{82750}{82820}Za sjajne novèiæe je bilo lako...
{82826}{82893}...no za vodu je bilo malo teže.
{82909}{82981}Zar bi prepoznala vodu iz vodovoda?
{83009}{83055}Ne po izgledu ni po okusu...
{83061}{83131}...no shvatila bi,|èim bi me pogledala.
{83259}{83289}Mislim da æe...
{83295}{83365}...vraèanje sa slikom biti dobra terapija.
{83418}{83480}A svakodnevno moljenje oproštaja?
{83511}{83608}Ne, mislim da se to neæe dogoditi.|Nikako!
{83803}{83841}- Hvala.|- Dobro se provedite.
{83874}{83909}- Hej, vi.|- Kako ste?
{83915}{83944}- Kako ste?|- Dobro.
{83950}{83974}Radite ovde?
{83986}{84028}Kao što vidite.
{84034}{84065}Ništa lošeg u tome.
{84071}{84109}Baš vam hvala.
{84578}{84609}Lepo je.
{84620}{84670}Želite poslati cveæe?
{84698}{84752}Mislim da dâ. Nisam siguran.
{84758}{84795}Malo je komplikovano.
{84810}{84842}Za koga?
{84865}{84895}Kako izgleda?
{84901}{84945}Ne poznajem je dobro.
{84951}{84981}Ruže su najomiljenije.
{84987}{85035}Malo presmelo.
{85041}{85074}A šta kažete na...
{85080}{85102}...poinsetiju?
{85108}{85166}Moglo bi stvoriti pogrešan utisak.
{85181}{85255}- Previše je trajna?|- Teško je reæi.
{85261}{85309}To je komplikovano.
{85329}{85365}A šta kažete na petunije?
{85371}{85466}Lepe su, a nisu presmele,|ugodno mirišu...
{85472}{85518}...a posle 3 dana ih bacite.
{85535}{85579}To otprilike tražite, zar ne?
{85683}{85739}Žao mi je, nema više petunija.
{85990}{86043}Hajde, kreni, Luis. Kreni.
{86119}{86151}Krenimo.
{86191}{86232}Dobar dan, Jenki Džon.
{86270}{86339}Zvuèi poput crknutog akomulatora.
{86461}{86526}Neko mi je sjebao auto.
{86532}{86566}...da se tako izrazim.
{86572}{86604}Gde idemo?
{86660}{86706}Može li živa zabava?
{86737}{86768}Kreni, Luis.
{86774}{86818}Dobar konj.
{86824}{86855}Hej, kuèko!
{86861}{86894}Hej, kuèko!
{86903}{86998}Malo više srca.|Hajde svi: "Hej, kuèko!"
{87004}{87044}Hej, kuèko!
{87061}{87125}Da, kuèka sam i na to sam ponosna.
{87131}{87232}Mama se oznojila.|Sva se preznojim pred belcima.
{87238}{87297}Ali budite uvereni, trudim se.
{87322}{87351}Oprosti, draga.
{87437}{87462}Oprosti.
{87468}{87490}Oh, Bože!
{87496}{87587}Ne "Oh, Bože", draga,|veæ "Oh, moja carice".
{87593}{87662}Grlite se otkad sam na sceni.
{87672}{87779}Pogledajte našu Mis èednosti.|Volim takve mustre, srce.
{87785}{87875}Ili on ima dobar alat,|ili si ti pakleno uspaljena.
{87951}{88000}To ti je deèko? Ili suprug?
{88008}{88039}Suprug.
{88049}{88094}A šta g. Muškarac radi?
{88106}{88140}On je lekar.
{88146}{88171}Lekar?
{88177}{88287}Bolje naoštri nokte, jer ako je|ginekolog, onda je moj.
{88305}{88342}Ozbiljno to mislim.
{88371}{88487}Moj je. Lekar.|Naoštri nokte, uzeæu ti ga.
{88547}{88629}Pogledaj kako crveni.|Preslatki je.
{88635}{88681}Želiš me pregledati?
{88733}{88789}Ništa ne skrivam.
{88881}{88940}Nadam se da imaš Amerikan karticu.
{88946}{89001}Znate li nešto?|On može otiæi.
{89007}{89075}Jer ova Lutka ima veæ belog deèka...
{89081}{89129}...koji juri za njenim dobrima.
{89135}{89216}Posvetlite tamo dole.|Pravo tamo.
{89222}{89301}Vidite li onog zgodnog belca?|Da, upravo onog.
{89307}{89415}Jurio je za Lutkom kroz èitavu|Savanu da je dobije.
{89421}{89505}Prvog dana mi je doneo ruže.
{89511}{89547}No, kao što znate...
{89553}{89610}...ništa nije previše dobro za Lutku.
{89616}{89705}Ništa nije previše dobro za Damu.|Ozbiljno to mislim.
{89711}{89799}Ako zateknem ijednu|od vas kuèki kraj njega...
{89805}{89897}...znajte da æete imati posla|sa Damom Šablis...
{89903}{89987}...s Lutkom, Velikom Caricom,|i mojim jebenim pijukom za led.
{90002}{90049}Dakle, dalje ruke od njega.
{90115}{90144}Hej, srce.
{90150}{90178}Kako si, Lutko?
{90190}{90249}Dobro.|Ko je taj zgodni muškarac?
{90269}{90291}Džo Odom.
{90296}{90321}Drago mi je.
{90327}{90407}Veæ se znamo.|Proveli smo jednu noæ zajedno.
{90413}{90526}Budi precizniji.|Ima veèeri kojih se ne mogu setiti.
{90532}{90576}Drugom prilikom.
{90601}{90713}Moje kocke leda su suve.|Ostavljam vas same.
{90719}{90809}Hvala. Vidimo se kasnije, džentlmenu.
{90815}{90841}Vrati se brzo.
{90857}{90922}Ne požuruj ga.|Hoæu biti sama s tobom.
{90928}{90950}Kako si?
{90956}{91055}I dalje krijem svoj slatkiš.|Da ti ga otkrijem?
{91061}{91103}- Ne moraš.|- Siguran si?
{91109}{91140}Ne još.|Hoæu reæi, nikad.
{91146}{91188}- Sasvim je mali.|- Molim te.
{91194}{91223}Kao lizalica.
{91229}{91266}Ne trebaju svi slatkiše.
{91300}{91376}U redu. No, moram ti nešto reæi.
{91382}{91498}Imam deèka broj èetiri.
{91504}{91533}Stvarno?
{91539}{91623}Visok, plavokosi, dobro graðeni tip.
{91629}{91697}Mehanièar je u ulici Aberkorn.|Znaš gde je?
{91703}{91780}- Znam.|- Tetoši me kao kraljicu.
{91790}{91834}Stvarno. Ne preterujem.
{91876}{91963}Obeæaj mi, ako ga ikada sretneš,|u šta sumnjam...
{91969}{92039}...da mu neæeš reæi moju "T".
{92045}{92083}- On nema pojma.|- Tvoju "T"?
{92089}{92135}Ma znaš, moju "T". Moju tajnu.
{92141}{92180}Moj sakriveni slatkiš.
{92193}{92285}On to ne zna i ti mu ne smeš ništa reæi.
{92304}{92367}- Obeæaj mi.|- Zar neæe primetiti?
{92373}{92437}Primetiæe, kad ja to budem htela.
{92444}{92487}Kao što sam za tebe htela.
{92493}{92537}Ali ja nisam hteo tvoj slatkiš.
{92543}{92576}Ali si ga njušio.
{92582}{92647}- Nisam.|- Zašto si ovde?
{92653}{92683}Želim te intervjuisati.
{92700}{92733}Predstava je izvanredna.
{92739}{92784}Hvala. Želiš me intervjuisati?
{92790}{92828}Da, stalo mi je.
{93221}{93244}Šta se dogaða?
{93250}{93300}Ubistvo s predumišljajem.
{93306}{93365}Žele ga doživotno maknuti.
{93395}{93473}SUDNICA OKRUGA ÈETAM
{93510}{93538}Èasni Sude...
{93546}{93619}...zajednica koja nas je izabrala...
{93625}{93722}...ne bi bila zadovoljna da|oslobodimo bogataša...
{93728}{93789}...optuženog za ubistvo s predumišljajem.
{93804}{93841}I imali bi pravo.
{93880}{93924}SUDIJA|SEMJUEL L. VAJT
{93941}{93973}U redu, gospodo.
{93981}{94056}Pažljivo sam saslušao vaša obrazloženja.
{94062}{94172}G. Vilijams je optužen za težak zloèin...
{94178}{94252}...i ne mogu dozvoliti|da se brani sa slobode.
{94294}{94357}Ali mogu ubrzati istragu...
{94368}{94399}...i približiti suðenje.
{94406}{94435}To je sve.
{94746}{94842}Izgleda da æe biti dovoljno|materijala za knjigu.
{95007}{95089}Da li je svestan ozbiljnosti situacije?
{95095}{95154}Vama je jasno, meni takoðe...
{95183}{95249}...a posle noæi u zatvoru|i on æe shvatiti.
{95412}{95480}BIRAJTE|FINLIJA LARDŽENTA
{95520}{95542}Šta vas muèi?
{95548}{95639}Rekli ste Soniju da sam èuo|Bilija kako vam preti.
{95659}{95718}I vi ste mu pretili.|Ako svedoèim...
{95724}{95749}Nisam mu pretio.
{95755}{95781}Upozorio sam ga.
{95801}{95873}Bio je nasilna osoba.|Pijanica i narkoman.
{95881}{95951}Nasilno je upao i zahtevao novac...
{95957}{96014}...preteæi mi razbijenom bocom.
{96020}{96067}To odgovara vašem seæanju?
{96073}{96158}- Otprilike.|- Vaše svedoèenje može pomoæi.
{96243}{96296}Šta je bilo meðu vama?
{96387}{96411}Iskljuèiæu to.
{96438}{96477}Ne smeta mi.
{96621}{96658}Da li se radilo samo o seksu?
{96672}{96730}Prièajte mi o vašem odnosu.
{96867}{96916}Bili i ja smo bili povezani.
{96940}{97005}To porota neæe moæi razumeti.
{97032}{97076}Videæe u tome samo seks...
{97082}{97126}...i razliku u godinama.
{97165}{97230}Ali Bili je mogao postati neko.
{97273}{97325}Velike stvari, veliki ljudi...
{97364}{97431}...zapoèinju skromno.
{97437}{97487}Trebao sam mu...
{97537}{97587}...i on je meni trebao.
{97651}{97713}Hoæete li mi suditi za to?
{97733}{97760}Ne.
{97823}{97860}Nevin sam, Džone.
{97891}{97940}Važno je da u to verujete.
{97968}{98008}Verujete li?
{98061}{98097}Da, verujem.
{98194}{98264}Ljudi ne žele sa mnom razgovarati.
{98309}{98346}Srediæu to.
{98353}{98443}Možete mi sutra doneti|kataloge Sotbija i Kristija?
{98448}{98534}Veèeru služe u 19 sati,|tada æemo telefonirati.
{98575}{98608}Mi?
{98837}{98888}Da, plaæam troškove.
{98941}{98988}Džim. Kako ste?
{99007}{99075}Dobro sam.|Da pokušamo, može?
{99103}{99147}Da vidimo da li radi.
{99531}{99564}U redu je, zvoni.
{99620}{99720}Halo, poziv Džim Vilijamsa|za Gezu von Habsburga.
{99746}{99769}Hvala.
{99793}{99818}Hvala.
{99920}{99944}Geza.
{99955}{100026}Džejms! Drago mi je što te èujem.
{100033}{100101}Da li te zanima Maksimilijanov sto?
{100182}{100222}Neka ga neko smiri.
{100303}{100403}Izgleda da tvoj pas ne želi da prodaš.|Koje je pasmine?
{100452}{100509}Ruski ovèar.
{100547}{100585}Zvuèi kao Šar-Pej.
{100602}{100668}Ne, to je moj terijer.
{100857}{100919}Može li neko izvesti psa u vrt?
{100928}{100984}Pobrinuæu se za to.
{101041}{101119}Geza, znaš da želim najveæu cenu.
{101134}{101173}Po obièaju.
{101227}{101254}Uæuti!
{102315}{102378}Da li je to|Kartaški klub udatih žena?
{102391}{102424}Da.
{102491}{102537}Da li æe neko pozvoniti?
{102543}{102585}Oh, ne!
{102591}{102669}Pravila su stroga.|Vrata se otvaraju taèno u 4.
{102778}{102812}Sve izgledate predivno.
{102821}{102853}Zapravo, Džim je...
{102861}{102932}...predložio da vas upoznam s ostalima.
{102939}{103005}Ali, ako to može ostati meðu nama...
{103031}{103086}- Zašto?|- Samo trenutak.
{103107}{103148}Sve je u redu, moje dame?
{103167}{103193}Dobro.
{103223}{103283}Džim je veæ odavno moj prijatelj.
{103288}{103345}Ali ove dame još ne znaju...
{103350}{103427}...koji stav zauzeti u vezi tog dogaðaja.
{103439}{103466}Znate i sami...
{103474}{103506}...nemio sluèaj.
{103512}{103593}Imam posla u kuhinji.|Hoæete li sesti?
{103600}{103664}- Ne igram bridž.|- Nisam to mislila.
{103672}{103699}Muškarci i ne smeju.
{103720}{103763}Pogotovo ne neženje.
{103770}{103844}No, možete sesti i prièekati.|Odmah se vraæam.
{104076}{104144}To je zloèin iz strasti.|Ljubavnièka svaða.
{104150}{104231}Moguæe, no prilièno je nezgodno za Džima.
{104252}{104277}Stvarno?
{104287}{104373}Nema baruta na mladiæevim rukama.|On nije pucao...
{104379}{104419}...kao što Džim tvrdi.
{104476}{104541}A položaj rana od metaka...
{104547}{104633}...poništava teoriju o|samoodbrani g. Vilijamsa.
{104639}{104660}Kako to?
{104666}{104757}Jedan je metak pogodio grudi,|a drugi leða.
{104763}{104822}A treæi metak...
{104828}{104865}Šta æe biti s Džimom?
{104914}{104963}Teško je reæi.
{104970}{105080}Oni koji su sretni što je Bili|prestao jurcati ulicama...
{105087}{105144}...misle da je...
{105149}{105269}...Džim izabrao èudan naèin da|obelodani svoju homoseksualnost...
{105278}{105306}...nemojte zameriti.
{105319}{105348}Sa praskom.
{105381}{105416}Doslovno.
{105450}{105473}A zatim...
{105478}{105508}...tu su i drugi.
{105522}{105558}Prièajte mi o njima.
{105578}{105681}Sigurno je da æe zameriti|Džimu ubistvo tog mladiæa.
{105686}{105751}Pogotovo tog mladiæa.
{105770}{105794}Zašto?
{105813}{105889}Bili je bio vrhunska muška prostitutka.
{105894}{105965}Po prièanju, izvrstan u poslu...
{105970}{106071}...omiljen od muškaraca i od žena.
{106113}{106145}Nezgodno je...
{106151}{106218}...što nije sve uspeo obiæi.
{106243}{106298}Bili Henson je bio èuven...
{106304}{106342}...po dobro obavljenom poslu...
{106348}{106372}...no...
{106380}{106464}...nisu ga svi stigli isprobati.
{106475}{106572}Kažu da je Džim ubio najboljeg|jebaèa u Savani.
{106578}{106607}- Istina?|- Ne znam.
{106613}{106668}Ti poznaješ tržište. Šta misliš?
{106674}{106699}Mili Bože!
{106739}{106837}Traèevi su na ceni u ovom gradu.|Ljudi plaæaju.
{106842}{106950}Ali ako prigusti, podržaæe Džima.|Možete mi verovati.
{106958}{107028}- A vaša strategija?|- Naš se plan odvija.
{107034}{107104}Imamo dogovor.|Delim ono što saznam...
{107111}{107144}Doðite.
{107150}{107196}Ne obazirite se.
{107309}{107337}Datum suðenja.
{107347}{107398}Za tri nedelje je finale.
{107404}{107431}Licem u lice.
{107441}{107496}Svaka ekipa ima svog aduta.
{107508}{107579}Njihov: test o analizi baruta.
{107590}{107663}Nema ga na rukama,|znaèi, on nije pucao.
{107669}{107742}Dakle, Džim ga je hladnokrvno ubio...
{107766}{107798}...i namestio scenu.
{107806}{107847}Kakav je vaš odgovor?
{107855}{107971}Taj test nije siguran.|Neki sudovi ga ne priznaju.
{107977}{108063}Finli ima Doktora Poa.|A mi vrhunsku nauku...
{108069}{108130}...i struènjaka sa severa.
{108176}{108252}Kažu da je namestio scenu.|Šta odgovarate?
{108260}{108298}To je naš adut.
{108320}{108363}Traljavi policijski posao.
{108368}{108406}Pogledajte ovo.
{108572}{108606}To sam ja!
{108611}{108646}Upravo tako.
{108652}{108711}Mesto zloèina.|Nisu vas smeli pustiti.
{108741}{108809}Ušao sam na stražnja vrata.
{108841}{108892}Nisu vas smeli pustiti.
{108933}{108989}Zajedno smo kad smo sretni
{109008}{109071}I kad nas brige more
{109089}{109143}Zar nije bolje tako
{109270}{109348}Bio oblaèan ili sunèan dan
