{1551}{1617}Spavam.
{1842}{1895}Jesi li dobro?
{1896}{1942}Nemoj.
{1967}{2013}- Ustaj, ustaj.|- Ne!
{2014}{2066}Pokušaj.
{2148}{2226}Hajde, ovo æe biti tvoj veliki dan.
{2229}{2300}Ne želimo propustiti ovu priliku.
{2416}{2483}- Dobro.|- Tko danas dolazi?
{2542}{2598}Znaš tko dolazi.
{2624}{2675}Bobby.
{2690}{2775}Bobby, ne!|Bobby...
{3237}{3300}April, moraš požuriti.
{3382}{3442}OK, stižem odmah.
{3512}{3564}April?
{3591}{3647}Dolazim.
{3811}{3862}Evo me.
{4301}{4354}Joy?
{4505}{4554}Draga?
{5058}{5170}Dušo, jesi li vidjela svoju majku?|Ne mogu je pronaæi.
{5173}{5217}Ne.
{5385}{5431}Gdje si?
{5621}{5664}- Ne znaš kucati?|- Gdje je ona?
{5666}{5729}Ne znam. Tko?
{5730}{5781}Tvoja majka.
{5783}{5823}Draga?
{5824}{5889}Mama?
{6200}{6275}U redu je, spremite se.
{6719}{6805}- Trebaš to?|- Da, trebam.
{8557}{8591}Vruæe je.
{9020}{9103}- Ionako nema veze.|- Naravno da ima.
{9107}{9178}Vjerojatno neæe ni doæi.
{9283}{9338}- Mama, kako se osjeæaš?|- Super.
{9341}{9390}To je dobro.
{9428}{9476}- Je li ovo dovoljno?|- Odlièno.
{9480}{9524}Mislio sam da æeš to reæi.
{9527}{9577}- Ponio si fotoaparat?|- Naravno.
{9580}{9615}- Siguran si?|- Apsolutno.
{9617}{9668}Radije provjeri.
{9670}{9739}- Mora biti ovdje.|- Zašto im treba tako dugo?
{9741}{9823}Pitam se nije li bilo|vrlo sebièno od nje
{9825}{9874}tražiti da doðemo u New York.
{9876}{9938}Smije li mama uopæe putovati?
{9939}{9992}Dušo, ako ne sada, kada æe?
{9995}{10116}Ponudila sam da spremim jelo,|no to bi bilo previše jednostavno.
{10118}{10185}Zašto misli da zna kuhati?
{10188}{10249}Ne sjeæam se da sam je vidjela u kuhinji.
{10253}{10349}- I tko je imao odlièan iz domaæinstva?|- Znaš koliko se time ponosimo.
{10352}{10417}- Molim te, povuci mi zatvaraè.|- Naravno.
{10419}{10485}Mora biti tu negdje.
{10518}{10606}- Zatrubi.|- Odmah æe stiæi.
{10607}{10711}- Probudit æemo susjede.|- Tko šljivi susjede. Zatrubi.
{10712}{10760}Mama, molim te.
{10763}{10850}- Patentni zatvaraè nije problem.|- Zapravo jest.
{10851}{10965}Ne, tata, nije problem|patentni zatvaraè, veæ April.
{10968}{11019}Evo ih.
{11108}{11161}- Kako se osjeæaš?|- Super.
{11163}{11213}- Povraæa ti se? Vrti?|- Odlièno sam.
{11215}{11265}- Kako si spavala?|- Super.
{11267}{11357}- Fotoaparat nije ovdje.|- Požuri.
{11441}{11560}Samo trebaš reæi:|"Nisam za to sposobna" i razumjet æemo.
{11562}{11613}- Što je sad?|- Zaboravio sam aparat.
{11614}{11672}- Gdje ti je kravata?|- Moram je nositi?
{11675}{11751}- To nije bilo pitanje.|- Ne, gospodine.
{11753}{11802}Razumiješ li...
{11828}{11925}- Ovo je možda posljednji put...|- Tata, tvoj dah.
{11928}{11972}Nema utrnulosti ni nelagode?
{11975}{12064}- Glavobolja? Povraæanje? Vrtoglavica?|- To si me veæ pitala.
{12067}{12116}Samo kaži: "Nisam za to sposobna."
{12118}{12173}To je sve što trebam reæi?
{12175}{12266}Znojiš li se? Oblijeva te hladan znoj?|Ruke su ti hladne? Tople?
{12267}{12338}- Trnci ti prolaze prstima...|- Beth, zaveži.
{12360}{12438}'Jutro, draga.|Kako se osjeæaš?
{12446}{12525}Nikad dovoljno jedaæeg pribora.
{12526}{12584}Pogledaj ove tanjure.
{12585}{12664}Otkud ti ovo?
{12666}{12744}- To je za sol i biber.|- Znam, no odakle ti?
{12747}{12813}Lz trgovine.
{12850}{12918}Imali smo ih dok sam bila dijete.
{12953}{13070}Kad mi je Joy dopuštala da ih držim,|rekla bi: "Pazi, vrijede više od tebe."
{13071}{13121}To je strašno.
{13123}{13191}Iduæe godine su nestali.
{13193}{13262}Što se dogodilo?
{13264}{13312}Na njih mi je pao èekiæ.
{13416}{13478}Dobro.
{13509}{13578}Koliko si ih platio?
{13580}{13632}Nisu bili jeftini.
{13659}{13754}Koliko si ih platio, Bobby?
{13833}{13891}50 centa.
{14001}{14063}To se isplatilo.
{14321}{14375}Žao mi je.
{14376}{14434}Nisam znao.
{14681}{14727}Èeka nas puno kuhanja.
{14729}{14796}Na 190 stupnjeva, nadjevenoj purici
{14797}{14915}teškoj 7 kilograma treba oko 5 sati|ako raèunamo 40 minuta po kilogramu.
{14918}{14967}Raèunaj i sat vremena za hlaðenje.
{14969}{15043}- Što to govoriš?|- Imamo vremena.
{15258}{15322}- Pire od krumpira, umak.|- Doista?
{15324}{15429}Nareži krumpire. Rastopi maslac,|pospi smeðim šeæerom.
{15431}{15494}Složenac od mahuna,|spravljen s mahunama.
{15497}{15599}Jelo od drobljenih krekera|i oštriga. Zvuèi teško.
{15601}{15716}Upotrijebi maslac i neposredno|prije peèenja prelij vruæim mlijekom.
{15718}{15822}Umak od brusnica. Otvori limenku i|istresi u zdjelicu. Vrlo jednostavno.
{15825}{15849}Što još?
{15851}{15904}Salata Waldorf...|jabuke, celer, orasi
{15905}{16002}i preljev od majoneze pomiješane|s mlijekom ili vrhnjem i sladilom.
{16003}{16122}Buænica kupljena u vrlo skupoj trgovini.
{16290}{16340}Pazi kuda ideš.
{16376}{16424}Samo polako.
{16564}{16623}Da se nisi usudio...
{16625}{16750}Beth, to je za mene, kad budem stara,|da se uvijek mogu prisjetiti ovoga dana.
{16752}{16810}Samo polako.
{16811}{16871}Samo što nismo stigli.
{16874}{16940}- Evo nas.|- Bok, bako.
{16979}{17067}Ja sam Beth. Tvoja unuka Beth.
{17068}{17142}Baš si draga.
{17195}{17285}- Bok, ja sam Timmy.|- Timmy je tvoj unuk.
{17330}{17394}Nije moguæe.
{17666}{17745}- Poznajem te.|- Bok, mama.
{17747}{17798}Jesi li jela?
{17800}{17890}Vruæe, Jime.|Bilo što, samo da je vruæe.
{17893}{17981}Dobro jutro.|Želite li naruèiti?
{17982}{18150}- Meni s kremom, prekriveno vanilijom.|- Mogu li dobiti dva èokoladna...
{18151}{18247}- Imaju uštipke?|- Znate da April kuha.
{18250}{18319}Još dvanaest s premazom.
{18415}{18502}- Što misliš o pravim ubrusima?|- Papirnati su u redu.
{18504}{18579}Bojim se da æe papir|izgledati pomalo papirnato.
{18580}{18662}Moramo li sada o tome?
{18665}{18735}Mogao bih ih pokupiti|dok idem to obaviti.
{18737}{18830}- Izlaziš?|- Da, moram to obaviti.
{18832}{18885}Mislim da æe ti se svidjeti razlog.
{18924}{19008}Želim da izaðeš.|Želim da sada izaðeš.
{19011}{19081}- Ali, želim pomoæi.|- Tako æeš mi pomoæi.
{19082}{19187}Idi to obaviti, ja mogu sama.
{19189}{19262}- Doista?|- Bobby.
{19263}{19339}Bit æe mi lakše bez tebe.
{19632}{19684}- Idem.|- Zbogom.
{19839}{19927}ŠTO TREBA UÈINITI -|ZAGRIJ PEÆNICU
{20310}{20448}Kažite mi, kako je moguæe|da netko ne vjeruje u Boga?
{20534}{20585}O, Bože.
{20819}{20900}Ne zavreðuju ukrase.
{20902}{20955}Da, ali ti ih zaslužuješ.
{21207}{21231}DOBRO DOŠLI
{21324}{21375}MAMA
{22482}{22530}O, ne!
{22912}{22957}Upali se.
{23267}{23326}Govori Anthony. Nisam kod kuæe.
{23329}{23438}Imate li problema, prièekajte.|Vraæam se sutra.
{23441}{23507}Sretan vam Dan zahvalnosti.
{23547}{23618}Vaš poziv nam je važan.
{23620}{23783}Nastojimo vam pružiti što bolju uslugu.|Predviðeno vrijeme èekanja je 48 minuta.
{23882}{23932}Mama?
{24005}{24055}Kako ti je?
{24146}{24197}Bravo!
{24320}{24369}Ima li koga?
{24456}{24507}Ima li koga?
{24601}{24695}Nastavite li kucati,|probudit æete me.
{24697}{24787}A ne želite me probuditi.
{24858}{24924}- Moje je mišljenje...|- Nikoga ono ne zanima.
{24927}{25018}- Nikoga ne zanima tvoje.|- Beth, je li te tata nešto pitao?
{25021}{25086}- Ne govorim tebi.|- Uvijek to èiniš.
{25088}{25181}Trebaš preuzeti kontrolu i okrenuti auto.
{25185}{25252}Mama. Daj da...
{25255}{25372}- Zabrinuli smo se za tebe, draga.|- Dobro sam. Dobro se osjeæam.
{25374}{25449}- Sad sam ja uzbuðena.|- Doista? Zbog èega?
{25451}{25496}Pa, da vidimo.
{25497}{25620}- Imam èips, štapiæe, kokice...|- Prestani.
{25624}{25688}- Mama, dosta je.|- Prestani, to nije u redu.
{25690}{25778}Ne sada kad se April toliko trudi|i sprema sva tvoja omiljena jela.
{25782}{25876}Nazvala je da provjeri|sastojke odreðenih recepata.
{25878}{25954}Presjeæi æu to u korijenu.
{26000}{26067}Sigurno je zvala na naš raèun.|Ja to ne bih nikada.
{26070}{26139}Nisi li ti savršena?
{26140}{26223}Je li netko spomenuo April?
{26224}{26297}Da, bako. Ona ti je druga unuka.
{26299}{26374}Znam, mislila sam da je mrtva.
{26375}{26475}- Nemoj, dragi, šteta je.|- Samo jednom æu to reæi.
{26477}{26563}- Što?|- Odlièno æemo se provesti.
{26566}{26655}- Zapravo i ne vjeruješ u to.|- Mislim da je moguæe.
{26656}{26743}- Bolji si èovjek od mene.|- Baš smiješno. Bolji èovjek.
{26745}{26803}- Drago mi je što idemo kod nje.|- Dobro.
{26807}{26935}Ovako, umjesto da April doðe|ukrašena novim iglama i tetovažama
{26937}{27007}i, ne daj Bože, prespava kod nas,
{27008}{27105}mi se pojavimo,|iskusimo katastrofu od njena života,
{27107}{27184}cijelo vrijeme se smiješimo|i onda se vratimo kuæi.
{27188}{27267}- Ne znamo je li katastrofa.|- Vjeruj mi, ja znam.
{27286}{27335}- Nedostajala sam vam?|- Naravno.
{27337}{27393}April je sada puno bolje.
{27394}{27493}Imala je dva prava posla,|našla je novi stan,
{27495}{27558}Eddie, raspaèivaè droga, je prošlost
{27559}{27627}i ima novog deèka.
{27628}{27722}- Super.|- Taj tip obeæava.
{27726}{27786}- Je li doista tako?|- Tako je.
{27787}{27868}Zbog èega, Jime?|Kaži nam, molim te. Zašto?
{27870}{27993}Navodno ju taj Bobby podsjeæa na mene.
{28384}{28452}Eugene, netko je pred vratima.
{28495}{28575}- Tko je?|- Stanujem u 3C.
{28576}{28647}- Trebam malu pomoæ.|- Pomoæ?
{28757}{28828}Imam jedan problem.
{28829}{28893}- Tko je?|- Nova cura iz 3C.
{28896}{28963}- Kaže da ima neki problem.|- Što?
{28966}{29034}Problemi, Eugene.|Cura ima problema.
{29037}{29183}Bijela je, mlada,|cijeli povlašteni život je pred njom.
{29185}{29315}Jedva èekam da èujem|kakvi problemi je muèe.
{29677}{29728}Dakle, to je kratka verzija.
{29730}{29790}- O, Bože.|- Prokletstvo.
{29793}{29870}Da sam vam isprièala dužu,|ne biste plakali.
{29871}{29917}Koliko je stara?
{29918}{29991}Rodila me kad je bila|mojih godina, znaèi ima 42.
{29993}{30063}- Ja ima 42.|- Ne, ti imaš 45.
{30122}{30170}Ne mogu zamisliti.
{30173}{30240}Zapravo, nitko od nas ne zna.
{30243}{30375}Eugene bi veæ danas mogao|progutati pureæu kost i ugušiti se.
{30378}{30427}Baš ništa ne znamo.
{30430}{30496}Ali shvatiti da su ti dani odbrojeni
{30497}{30580}i da imaš posljednju priliku|uèiniti ono što voliš
{30583}{30652}- i biti s onima koje voliš...|- Prokletstvo.
{30654}{30741}Jadnica. Tvoja jadna majka.
{30742}{30795}Da. Ne.
{30796}{30848}Vaša veza je sigurno posebna.
{30898}{31000}Tako je. Vrlo smo bliske.
{31001}{31107}- Kao sestre. Ona mi je kao najbolja...|- Ne slažete se, zar ne?
{31133}{31205}Ne. Nikako. Nikada ni nismo.
{31208}{31275}- O, Bože.|- Evette.
{31277}{31328}Znam, dragi.
{31374}{31433}Dušo, moramo skuhati za sebe.
{31450}{31509}- Razumijem.|- Ali èekaj, ne mièi se.
{31511}{31597}- Tina dolazi s deèkima u dva?|- Tako je.
{31600}{31656}Glen æe, kao i uvijek, kasniti.
{31659}{31742}- Dolazi li Rashid?|- Znam što misliš.
{31743}{31802}Naravno da znaš, dragi.|Uvijek je tako.
{31829}{31890}Evo što æemo.
{31893}{31973}Odgodit æemo naše kuhanje do 10.30.
{31976}{32130}To æe ti omoguæiti poèetak,|a onda æeš morati naæi drugu peænicu.
{32133}{32193}Kako ti to zvuèi?
{32223}{32309}BOBBY, PEÆNICA NE RADI.|AKO ME NEMA, JA SAM U 2B.
{32649}{32701}- To je tvoje.|- Imam poruku za tebe.
{32703}{32752}- Što je?|- Tyrone te traži.
{32755}{32845}- Ne poznajem nikakvog Tyronea.|- On poznaje tebe.
{33183}{33236}Lijepo je to što èiniš za nju.
{33239}{33300}- Baš i nije.|- To je lijepa gesta.
{33301}{33363}- Nije li to lijepo, Eugene?|- Imam pitanje.
{33365}{33425}Lijepo je pisati pisma, posjeæivati dom.
{33428}{33500}- Nisi ih još posjetila?|- Nisam.
{33503}{33628}- Nisi otkad se razboljela?|- Tako... Tako joj više odgovara.
{33632}{33728}- Ne vjerujem ti.|- Vjerujte mi. Ja sam prva palaèinka.
{33732}{33809}- Kako to misliš?|- Prva se palaèinka baca.
{33810}{33866}- Imam pitanje.|- Koje?
{33879}{33949}Jesi li je nadjenula?
{33981}{34080}- Je li ptica nadjevena?|- Da.
{34083}{34184}- Èime?|- Stabljikama celera, i što ja znam.
{34186}{34220}Celer je dobar.
{34223}{34281}- Lukom.|- Luk je dobar.
{34283}{34360}Uglavnom, smjesom iz vreæice.
{34404}{34494}Upotrebljavaš kupovni nadjev?
{34496}{34605}- Je li to loše?|- Ne. Bit æe dobro.
{34606}{34656}Što sam trebala upotrijebiti?
{34658}{34739}- Sigurna sam da je dobar.|- Ne stavlja se kupovni nadjev.
{34741}{34818}Molim te, Eugene.|Tvoja prva purica?
{34821}{34891}Moram li te podsjeæati|na onu napola peèenu?
{34892}{35021}Ružièasto meso, bez okusa,|a iduæe godine si jadnu pticu spalio.
{35116}{35180}Sjeæaš se toga?
{35183}{35248}- Ne, ne sjeæam se.|- Zato sam ovdje, dragi.
{35249}{35332}- Tako da ništa ne zaboraviš.|- Baš ti hvala.
{35335}{35408}- Dodaj mi mahune.|- Ne brini za to.
{36092}{36145}Što to radiš? Ne trebam kartu.
{36147}{36202}Želim krenuti drugom cestom.
{36204}{36310}Sporednim cestama, vidjeti nove stvari,|da nam ne propadne dan.
{36313}{36369}- Ne smijemo kasniti.|- Niti stiæi prerano.
{36372}{36508}Dajem ti izbor.|Dopusti mi da prouèim kartu
{36509}{36583}ili se uzdaj u moju|savršenu orijentaciju.
{36585}{36646}Ja sam za savršenu orijentaciju.
{36688}{36713}Gdje smo?
{37952}{38034}Pazi. Nemoj puštati toplinu.
{38060}{38118}Kako izgleda?
{38121}{38194}Ne znam kako bi trebala izgledati.
{38285}{38374}- Što on radi?|- Kaži joj što pripremaš.
{38375}{38445}Ništa posebno ove godine.
{38446}{38561}Juhu od batate s pekan orasima,
{38563}{38643}zaèinjeni nadjev od kamenica,|umak od iznutrica,
{38644}{38730}mahune s limunom i ružmarinom,
{38732}{38789}crvenu blitvu na lešo s èešnjakom,
{38791}{38843}sladoled od cikorije
{38844}{38921}i buènicu s javorovim sirupom.
{38924}{38997}- Opa.|- Ništa posebno ove godine.
{39018}{39078}- Da, tako je.|- A ti?
{39185}{39263}Puricu, umak...
{39265}{39356}- Waldorfsku salatu.|- Zvuèi neobièno.
{39374}{39463}U nju ide razno voæe i orašèiæi.
{39464}{39517}Preljev je uglavnom majoneza.
{39518}{39628}Zatim pire od krumpira, naravno,|i umak od brusnica, što je lako.
{39629}{39681}Samo otvoriš limenku.
{39684}{39734}- Evette.|- O, dušo.
{39770}{39885}- Volim hranu iz konzerve.|- Nitko ne voli hranu iz konzerve.
{40083}{40150}Bila je to vjeverica, èini mi se.
{40153}{40215}Ili vrlo mali rakun.
{40433}{40482}Idemo.
{40645}{40711}Mama traži mjesto.
{41139}{41197}Žao nam je što se nismo upoznali.
{41198}{41261}Nadamo se da je bilo brzo.
{41262}{41337}- I...|- To je dovoljno. Beth, pjevaj.
{41339}{41390}Neæu.
{41454}{41518}Mislim da je Tim dovoljno rekao.
{41520}{41595}Što onda èekamo?
{41729}{41778}Ulij to, dušo.
{41781}{41894}- Tako je. Nadarena si.|- Dobro.
{41897}{41993}Dok èekamo da se razmuti, miješaj.
{42045}{42129}- Hajde, curo.|- Nemojte, nije to ništa.
{42132}{42193}Jesi li to ikad spremila?
{42196}{42269}- Onda nije ništa.|- Oprostite.
{42272}{42395}- Što je sljedeæe?|- Ostavimo to da tiho vrije.
{42397}{42477}- Molim vas, možete li...|- Zatim se treba ohladiti.
{42479}{42609}- Dame, molim vas.|- Dragi, samo reci i mi odlazimo.
{42636}{42712}Ne brini, Eugene je uvijek tako pedantan.
{42713}{42796}- Jesi li našla drugu peænicu?|- Nisam je ni poèela tražiti.
{42799}{42906}Što je prije naðeš, to bolje.
{42909}{42995}- Stižem.|- Ne brinite. Dogovoreno.
{43196}{43325}Eugene i Evette iz 2B...|Poznajete ih?
{43327}{43411}Trenutaèno mi pomažu i mislila sam...
{43414}{43550}Moji dolaze, a mama... Komplicirano je.
{43551}{43689}I onda je peænica, ili štednjak,|ne znam kako se to zove, ali poèelo je...
{43690}{43741}Oprostite.
{43771}{43869}Ona je loša majka|i ne znam zašto bi mi pomogli.
{43872}{43996}Èudno, i moja majka bila je zla žena.
{43999}{44101}Nije imala ni jednu|dobru kost u èitavom tijelu.
{44104}{44192}Neprestano je pušila, varala na kartama
{44194}{44299}i uvijek se na nešto žalila.
{44339}{44398}- Žao mi je.|- Znate što?
{44426}{44569}Sve bih dao da s njom|mogu provesti više vremena.
{44739}{44808}Znaèi, pomoæi æete mi?
{45158}{45211}Pomozite.
{45225}{45329}Latrelle, Bobby je.|Stigao sam. Nazovi me.
{45330}{45464}Broj je 212-737-3858.
{45501}{45551}U redu.
{45675}{45762}- To je divno. Puno ste mi pomogli.|- Dobro.
{45764}{45834}- Ja sam April iz 3C.|- Tish iz 4A.
{45837}{45919}Hvala, Tish iz 4A.
{45944}{45998}Moja obitelj vam zahvaljuje.
{46161}{46230}Ovo je posljednja.
{46859}{46945}To je za božiænu èestitku.|Idemo, mama.
{46979}{47072}- Bez April?|- Otkad bi ona trebala biti na slici?
{47073}{47125}Èekajte.
{47313}{47364}Bobby.
{47670}{47721}Stižem.
{48022}{48074}Zadrži rukavice.
{48076}{48140}Evette, gdje je cjedilo?
{48144}{48204}- Sretno.|- Hvala.
{48307}{48351}JA SAM U 4A
{48414}{48464}JA SAM ZA PRAVO NA POBAÈAJ
{48466}{48544}NADER ZA PREDSJEDNIKA|STRANKA ZELENIH
{48583}{48636}Bok, to sam ja.
{48638}{48689}- Možemo li razgovarati?|- Naravno.
{48690}{48741}Nasamo.
{48893}{48970}Nešto vam moram reæi.
{48974}{49028}Nikad ne jedem nešto što ima lice.
{49054}{49127}Neæete to jesti.|Samo æu upotrijebiti peænicu.
{49128}{49210}Bilo je to za mene živo biæe,|duša koja diše...
{49212}{49282}- Ja sam vegetarijanka. Razumijem.|- A ja veganka.
{49286}{49379}I sam miris peèenog mesa...
{49380}{49466}Mislim da vam ne mogu pomoæi.
{49718}{49809}Latrelle, èovjeèe, Bobby je.|Stigao sam na mjesto...
{49867}{49971}Èuje li me itko? Lma li itko|peænicu koju mogu upotrijebiti?
{49972}{50054}- Molim vas.|- Pitajte Waynea u 5D.
{50057}{50160}- On ima novu peænicu.|- Govorite glasnije, gospoðo.
{50163}{50236}Probajte kod Waynea u 5D.
{50239}{50316}On ima novu peænicu.
{50318}{50385}Hvala.
{50443}{50556}Dušo, samo provjeravam je li sve u redu.
{50558}{50621}Ako me ne trebaš, ne podiži slušalicu.
{50624}{50719}Samo provjeravam jesi li dobro.
{50720}{50771}Volim te.
{50837}{50908}Trebam ovo.
{50933}{51007}Mogu li upotrijebiti...
{51009}{51077}- Ne govore engleski.|- Znam.
{51099}{51204}- Mogu li upotrijebiti...|- Gubite vrijeme.
{51263}{51315}Oprostite.
{51442}{51493}Oprostite.
{51551}{51605}Vi ste Wayne?
{51658}{51714}Wayne koji ima novu peænicu.
{51715}{51789}To je konvektorska|samoèisteæa peènica.
{51791}{51859}Ima automatski termometar za meso,
{51861}{51955}zvuèni signal zagrijavanja,|dvije vrste peèenja,
{51956}{52039}svjetla za vruæe površine|i rešetku za peèenje.
{52042}{52111}I meni najdraža...
{52113}{52177}vrata peænice bez okvira
{52178}{52261}s luksuznim prozorom.
{52283}{52345}Opa!
{52347}{52419}Predivna je.
{52466}{52518}Da, stvarno jest.
{52577}{52638}- Ne znam kako bih pitala...|- Budite moj gost.
{52640}{52689}- Doista?|- Bit æe nam drago.
{52715}{52831}Tiho, Bernadette.|U redu je, ona ne grize.
{53043}{53104}- Latrelle, gdje si?|- Gdje sam?
{53107}{53166}Da, gdje si?
{53168}{53224}Èovjek želi znati gdje je Latrell?
{53226}{53280}Da, želim znati.
{53326}{53397}- Ovdje.|- Gdje si bio? Zakasnit æu.
{53400}{53470}- Gdje si bio?|- Stajao sam ovdje.
{53471}{53530}Poznaješ li Tyronea?
{53531}{53590}- Tyrella?|- Tyronea.
{53625}{53715}Koliko daleko moramo iæi?
{53717}{53769}Evo je.
{53834}{53888}Šališ se.
{53914}{54033}- Rekao si da si radio u maloprodaji.|- Nisam lagao. Pomozi mi.
{54084}{54119}ŠTEDIONICA
{54121}{54233}Obeæao si mi kvalitetnu odjeæu.
{54236}{54341}Imat æeš kvalitetnu odjeæu, vjeruj mi.
{54343}{54433}- Da ti vjerujem? Nemoj, èovjeèe.
{54490}{54608}Krivo sam te procijenio, èovjeèe.|Mislio sam da si tip
{54612}{54751}koji ne pada na poznate firme|i Armani Prada sranje.
{54753}{54798}Prestani s tim.
{54800}{54884}90% ljudi bi željelo imati tu odjeæu.
{54887}{54974}Samo ti hoæu reæi da,|ako je nešto korisno,
{54976}{55089}ako to možemo nositi,|ako to ljudi koje volimo mogu nositi,
{55092}{55184}to æe biti na ovim vješalicama,|zato poèni tražiti.
{55186}{55256}Na tvom mjestu poèeo bih tamo.
{55257}{55319}Ako ništa ne naðem,|bolje da te nema.
{55337}{55419}Zaustavi auto, Jime.|Odmah ga zaustavi.
{55451}{55545}Jesi li dobro? Slabo ti je?|Trebaš svježi zrak?
{55548}{55678}- Mama, trebala bi izaæi iz auta.|- Dobro mi je.
{55679}{55812}Èekam pravi trenutak|da vam to kažem, ali njega nema.
{55813}{55891}Svi me slušajte.
{55959}{56018}Ne znam kako bih vam to rekla.
{56075}{56146}Moramo se dogovoriti|kako æe svatko od vas...
{56147}{56205}U redu je, dušo.
{56282}{56358}Kako æe svatko od vas, na svoj naèin,
{56361}{56411}riješiti pitanje...
{56521}{56634}bacanja hrane bez znanja naše domaæice.
{56656}{56709}Molim te, Joy, kako možeš.
{56757}{56823}To nije jako smiješno.
{56884}{56952}Evo što predlažem.
{56991}{57078}Uzmite zalogaj, na primjer,|složenca od mahuna.
{57081}{57165}Pretvarajte se da žvaèete.|Kašljajte. Prinesite ubrus ustima.
{57166}{57240}Ispljunite hranu u ubrus.|Isprièajte se.
{57241}{57346}Bacite hranu u zahod. Povucite vodu.
{57901}{57985}Dušo, drugi put je èvršæe smotaj.
{58047}{58096}Oprosti, mama.
{58749}{58798}Smack Daddy je...
{58799}{58841}- Tko?|- Smack Daddy.
{58844}{58943}- Jesam li ja èuo za Smacka Daddyja?|- Crni pjevaè. Ne možeš ga znati.
{58945}{59097}Ne, nikad nisam èuo za Jamesa Browna,|Barryja Whitea i Puffy The Doga...
{59100}{59157}- Mogu li završiti?|- Izvoli.
{59160}{59224}Smack Daddy nije za
{59225}{59319}jednokratnu uporabu, veæ zauvijek.
{59321}{59467}Milijuni ga žele,|ali kao da pjeva samo meni.
{59506}{59600}Godine nisu važne. Ne brine ga|jesam li stara, bolesna, u raspadanju.
{59604}{59677}Vidi moju dušu.|Nije prevrtljiv. On je tamo za mene.
{59680}{59762}- Kao tata?|- Vaš otac ne zna pjevati.
{59788}{59874}Ali Smack Daddy... Baš je seksi.
{59875}{59997}Što navodi na seks.
{59998}{60167}Doziva neke lijepe uspomene.
{60168}{60221}Misliš s tatom?
{60224}{60273}I s njim.
{60712}{60761}Halo?
{60845}{60927}- Što je?|- To ste vi.
{60991}{61086}Kucao sam na mnoga vrata tražeæi vas.
{61087}{61158}- Vaša su bila pritvorena.|- Uðite.
{61161}{61210}Kako napreduje?
{61328}{61380}Bez problema na vidiku.
{61383}{61436}Baš sam htio provjeriti vašu puricu,
{61438}{61561}a onda sam pomislio, jer ipak je vaša,|da biste je sami htjeli pogledati.
{61689}{61790}Naravno, mogu to uèiniti za vas,|i hoæu, ako to želite.
{61793}{61865}Nisam se usudio...
{61866}{61920}U redu je.
{61982}{62097}Ljudi èesto pogrešno misle kako je|dovoljno samo staviti puricu u peænicu.
{62099}{62193}Purica treba pažnju.|Za nju treba brinuti s ljubavlju.
{62194}{62280}Na perad treba dobro paziti.
{62305}{62394}- Naravno.|- Toliko toga može krenuti po zlu.
{62397}{62510}Purica može mjestimièno izgorjeti,|biti prekuhana, ili nedovoljno kuhana,
{62513}{62575}što šteti zdravlju,|a tu je i podlijevanje?
{62578}{62651}Wayne, doæi æu za sekundu, u redu?
{62753}{62802}Sekunda je istekla.
{62915}{62965}Dajte mi samo minutu.
{63073}{63129}Tik-tak.
{63543}{63608}- Èekajte. Stižem.|- Mislim da ne možete.
{63610}{63674}Bernadette ima mali mjehur|i ako ja ne...
{63676}{63760}- Ne mogu li samo proviriti?|- Bojim se da ne možete.
{63762}{63818}- Brzo æu.|- Ne.
{63820}{63915}Znate onaj dobar osjeæaj koji vam|daje pružanje pomoæi drugima?
{63919}{63983}Sada nemam taj osjeæaj.
{63984}{64043}Oprostite. Nisam shvatila...
{64044}{64179}Pitam se: "Wayne,|jasno je što radiš za nju,
{64182}{64240}ali što ti time dobivaš?"
{64242}{64317}Morate o tome razmisliti
{64318}{64393}i možda mi kasnije|možete pomoæi razumjeti
{64394}{64447}što dobivam ovom razmjenom.
{64448}{64564}Ako to uopæe možemo zvati razmjenom.|Doði, Bernadette.
{64640}{64698}To je sve smeæe, Latrelle.
{64787}{64850}Nastavi tražiti.
{64885}{64944}To je odjeæa za svodnike.
{64946}{65014}- Zelena poput novca.|- Ne.
{65016}{65075}- Iznenaðujuæi suvratak.|- Ne.
{65094}{65154}- Baršun.|- Kvragu s njim.
{65184}{65249}Kako bih to mogao nositi?
{65350}{65457}Èovjeèe, ovo sam saèuvao za sebe,
{65459}{65539}ali mislim da je tvoj broj. Probaj.
{65678}{65729}Što je to?
{65730}{65832}Mamine fotografije|koje sam prije snimio i nove.
{65834}{65904}- Baš lijepo.|- Dobio sam fotoaparat za roðendan.
{65905}{65959}Timmy je vrlo darovit.
{65962}{66050}- Sva naša djeca su darovita.|- Beth je takoðer nadarena.
{66051}{66132}Baš lijepo.
{66133}{66190}Možda sada nije pravo vrijeme.
{66279}{66414}- Ovo je bilo prije.|- Tako da se uvijek mogu prisjetiti.
{66417}{66502}- To je zasad dovoljno.|- Slažem se.
{66505}{66578}Želim ti još jednu pokazati.
{66606}{66741}Gdje je ona? Ova mi je najdraža.
{66795}{66853}Gledaj kako svjetlo...
{66928}{66982}Pogledaj ruku.
{67034}{67122}Više volim kad Beth pjeva.
{68361}{68467}Èuo si izreku: "Èuvaj se prilika|koje opravdavaju novo odijelo"?
{68468}{68544}- Ne.|- Sad ti ja kažem. Èuvaj se.
{68545}{68607}Nikad nisi bio zaljubljen?
{68609}{68667}Nisam bio niti ne želim biti zaljubljen.
{68668}{68780}- To te promijeni.|- Kako?
{68783}{68878}Èiniš stvari koje si mislio da ne možeš.
{68881}{68932}Moja mama, pokoj njenoj duši...
{68936}{69006}- Nemoj opet o mami.|- Vozila je...
{69007}{69088}- Nije znala voziti.|- Nisi je poznavao. Žalim te zbog toga.
{69090}{69141}Ne žali mene. Ti si zaljubljen.
{69143}{69256}Moja majka me je vozila kao bebu|i auto se prevrnuo.
{69258}{69322}Našao sam se ispod auta.|Znaš li što je uèinila?
{69323}{69373}- Podigla je auto.|- Sereš.
{69375}{69459}Podigla je auto i izvukla me na sigurno.
{69462}{69590}Ljubav joj je dala|tu nevjerojatnu snagu.
{69661}{69722}Ljubav èini takve stvari.
{70911}{71025}- Bravo.|- Još!
{71026}{71101}- Ima li želja?|- Da prestaneš.
{71562}{71656}Oprosti, užasna sam.
{71728}{71818}- Tko si ti?|- Nemoj opet poèinjati. Znaš tko sam.
{71821}{71890}Znam tko kažeš da jesi,
{71891}{72015}ali moja kæi je dobra i draga,|i lijepo govori...
{72016}{72115}- Ne više.|- Onda te ne poznajem.
{72596}{72651}Sranje.
{73249}{73324}Joy, draga, jesi li dobro?
{73491}{73602}Tako sam kritièna.|To mi jedna od najgorih pogrešaka.
{73606}{73689}Neki razlozi za to su oèiti.
{73691}{73742}Ali, ne prestajem se pitati,
{73743}{73811}zašto sam okrutna,|na primjer, prema tebi, Beth,
{73812}{73877}kad si godinama bila kæer mojih snova?
{73880}{73934}Bila si, znaš da je tako.
{73935}{74017}Ako izuzmemo gojaznost,|ista si osoba.
{74021}{74064}Zašto sam okrutna prema tebi?
{74068}{74177}Zaboravimo èinjenicu|da ponavljaš moje pogreške.
{74180}{74279}Mislim da sam okrutna jer smo|skupa proveli toliko lijepih trenutaka.
{74281}{74341}A mislim da æu s pogoršanjem, Timmy,
{74344}{74432}i prema tebi postati okrutna|jer nas veže puno lijepih trenutaka.
{74434}{74521}Zašto sam onda okrutna prema April|kad nas ne vežu lijepi trenuci?
{74524}{74603}- To nije istina.|- Danima se, Jime,
{74607}{74696}pokušavam sjetiti neke lijepe|uspomene s April i ima samo jedna.
{74700}{74771}Jedna živopisna, prekrasna uspomena.
{74772}{74838}- Mora ih biti više.|- Jedna može biti puno.
{74841}{74890}- Èega se to sjeæaš?|- Nije važno.
{74893}{74949}Naravno da je važno. Kaži nam.
{74952}{75012}Što je to bilo?
{75016}{75094}Tek je napunila tri godine.
{75096}{75198}Gledala je kroz veliki prozor|na ulicu Locust.
{75200}{75294}Bilo je rano ujutro,|ali veæ je bilo sunèano.
{75297}{75470}Dugo je gledala kroz prozor,|a zatim se okrenula prema meni i rekla:
{75473}{75578}"Majko, zar ne voliš|jednostavno svaki dan?"
{75643}{75698}To sam bila ja.
{75748}{75849}Jesam. April je imala šest godina|dok smo stanovali u ulici Locust.
{75884}{75938}Je li to toèno?
{75941}{76075}A crtež broda "Mayflower",|onaj koji si uramila?
{76077}{76134}- I to sam bila ja.|- Prekini.
{76136}{76252}Oprosti, ali toènost je važna.|To su i moje uspomene.
{76253}{76318}- Sigurna si?|- Ima pravo, dovraga.
{76319}{76399}Samo se jedne mogu|ovako na brzinu sjetiti.
{76400}{76529}Bila je... Ne znam koliko je bila stara,|ali nosila je ružièastu spavaæicu.
{76532}{76581}To sam bio ja.
{76618}{76687}- Šalim se.|- Strašno smiješno.
{76690}{76781}Vratio sam se s puta, možda i nisam,
{76784}{76844}ali ušao sam u njenu sobu,
{76848}{76990}a ona je spavala u kolijevci,|bilo je to divno.
{76991}{77074}- To je sve?|- Da, to je sve.
{77077}{77130}- To je divno.|- Ne, nije.
{77131}{77212}Tvoj najsretniji trenutak|bio je dok je spavala.
{77248}{77360}Nisam rekao da je to bio najsretniji|trenutak. To mi je palo na pamet.
{77652}{77718}- Što to radiš?|- To je sranje.
{77721}{77823}Sve èega se sjeæam je mušièavost,|kraðe u trgovini, požar u kuhinji.
{77826}{77863}To je bila nesreæa.
{77864}{77947}Naèin na koji je palila šibice|i bacala ih prema Beth?
{77951}{78022}Ili kako je upaljaèem|Timmyju kratila šiške?
{78025}{78126}- Ma daj.|- Droge, nezahvalnost.
{78207}{78300}Grizla mi je bradavice|kad bih je pokušavala dojiti.
{78302}{78394}Nije ni èudo|da sam dobila rak. Ona je rak.
{78443}{78505}Joy, vrati se u auto.
{78678}{78728}Što se dogaða?
{78753}{78828}Mama je željela protegnuti noge.
{78829}{78876}Joy, stani.
{78903}{78952}Pokušala sam, ali ne mogu k njoj.
{78955}{79082}- Ne mogu podnijeti novo ružno iskustvo.|- Neæe se to dogoditi.
{79085}{79139}Ti to ne znaš.
{79140}{79209}U tome je i smisao posjeta.
{79210}{79291}- Kreiramo uspomene.|- Ne slušaš me.
{79293}{79378}- Imam previše uspomena.|- Dobre uspomene.
{79379}{79438}Radimo nešto dobro.
{79469}{79520}Što ako ne bude tako?
{79521}{79596}Bit æe. Obeæajem.
{79597}{79666}Obeæajem ti, bit æe krasno.
{79690}{79741}Otkud znaš?
{79765}{79841}Rekao sam ti da mora biti tako.
{79910}{79969}A ako ne bude?
{79970}{80021}Onda æu je ubiti.
{80703}{80788}Dobar dan. Htjela bih prijaviti otmicu.
{80837}{80912}Rekla sam: "Htjela bih prijaviti otmicu."
{80913}{80989}Taj èovjek, koji živi u mojoj zgradi,
{80992}{81143}oteo mi je puricu i drži je veæ|više od sat vremena, pa je ne mogu...
{81145}{81194}Moju puricu.
{81344}{81429}Ne, znam. Zato sam nazvala.
{81432}{81491}Morate razumjeti...
{81573}{81622}GDJE SI?
{82761}{82811}Loša djevojka.
{82869}{82920}Hoæu svoju puricu.
{82924}{82979}- To mi je hvala.|- Dajte mi moju puricu.
{82983}{83094}- Tražim pravu rijeè.|- Dajte mi moju glupu puricu.
{83096}{83178}To je veæ bolje. Vaša je.
{83207}{83293}- Ne morate mi zahvaliti.|- I neæu.
{83295}{83370}- Zahvalite Bernadette.|- Što?
{83372}{83437}Bez nje ne bismo našli rješenje.
{83439}{83498}Voli kad je meso slabije peèeno.
{83500}{83564}Hoæe li dušica probati...
{83815}{83938}Vi ste loša cura. Jako loša.
{84034}{84090}Ne, nisam.
{85512}{85561}Dobro došli u naš dom.
{85766}{85828}Tyrone te traži.
{86168}{86217}- Kako si, Bobby?|- Eddie.
{86220}{86269}- Eddie je mrtav.|- Molim?
{86272}{86346}Promijenio sam ime. Sada sam Tyrone.
{86392}{86462}- Dakle, ti si Tyrone?|- Promijenio sam ime.
{86465}{86526}Svi to rade.
{86528}{86585}Moj cijeli svijet, što je bila April.
{86645}{86696}Moram poæi.
{86749}{86813}Da ti i želim nauditi,|a na neki naèin to želim,
{86817}{86895}- neæu, možeš se opustiti.|- Hvala.
{86897}{86984}To je njen izbor.|Ako želi biti s tobom, to je u redu.
{86988}{87071}To je samo... Ima nešto što...
{87092}{87165}- Mogao bi joj nešto reæi?|- Što želiš da joj kažem?
{87211}{87263}Sretan Dan zahvalnosti.
{87871}{87892}Poènite.
{87930}{87979}Jer...
{88089}{88169}Ovdje su nekad živjeli Indijanci.
{88171}{88220}Roðeni Amerikanci.
{88223}{88298}Onda je stigao brod "Mayflower".
{88300}{88393}Iskrcao je ljude poput mene|na veliku stijenu.
{88394}{88467}Prvu godinu bilo im je teško.
{88511}{88592}Vrlo teško.
{88687}{88727}Zapoèet æu ponovno.
{88838}{88920}Bilo je to jako davno.
{88924}{89010}Prije nego što smo im|ukrali veæinu zemlje,
{89014}{89126}ubili veæinu njih,|a ostale strpali u rezervate.
{89129}{89195}Prije nego što im se|izgubio jezik i obièaji.
{89383}{89448}Zaboravite što sam upravo rekla.
{89452}{89512}Jednom je bio dan
{89515}{89632}kad su svi mislili|da trebaju jedni druge.
{89844}{89984}Znali su da toga dana|ne mogu biti sami.
{90026}{90096}TUNEL "LINCOLN"|VOZITE LIJEVOM STRANOM
{91572}{91626}Zašto smo stali?
{91653}{91718}Tata je mislio...
{92774}{92838}168?
{92841}{92901}160...
{92904}{93048}- 162. Moralo bi biti ovdje.|- Tata?
{93052}{93117}Èekaj. Tata, pazi.
{93118}{93172}- Pazi.|- Tko su ovi?
{93175}{93252}154. Tu bi trebalo biti.
{93754}{93810}- O, Bože.|- O, Bože.
{93813}{93906}- To je pogrešna ulica.|- Ne, mislim da smo na pravom mjestu.
{93907}{93962}Ne, nije moguæe.
{93965}{94070}Oèito imamo pogrešnu adresu.
{94071}{94120}Tata, mislim da smo na pravoj.
{94259}{94318}Kvragu, April.
{94459}{94510}Ne razumijem. Kako ste...
{94585}{94641}Što?
{94660}{94745}To je izraðeno od tijesta.
{94949}{94998}Hvala vam.
{95038}{95118}Zakljuèajte vrata.
{95168}{95260}- Dobro došli. Kako ste?|- Mama, nemoj.
{95264}{95361}Ja sam Bobby. Vi ste Aprilina obitelj?
{95425}{95476}To boli.
{95541}{95607}Vi ste joj sigurno majka.
{95752}{95803}Idem po nju.
{95978}{96046}April, stigli su.
{96049}{96113}Dušo, tvoji su ovdje.
{96143}{96218}- Bobby?|- Stigli su.
{96272}{96337}- Bože, što ti se dogodilo?|- Dobro sam.
{96338}{96400}Trebaš prvu pomoæ.
{96401}{96499}- Tvoja obitelj je dolje.|- Gledaj kakve su ti usne i oko.
{96500}{96560}Smiri se. Dobro sam.
{96563}{96656}Èekaju te dolje. Moraš krenuti.
{96658}{96730}- Sigurno si dobro?|- Kreni.
{96818}{96908}- Umak od brusnica je gotov.|- Stigli su.
{98290}{98348}Ne razumijem. Bili su tamo.
{98362}{98438}Možda su otišli nešto obaviti.
{98525}{98591}Zašto bi prevalili toliki put?
{99299}{99380}Što æemo sa svom tom hranom?
{99419}{99468}Ovo je tako lijepo.
{99591}{99648}Nešto odlièno miriši.
{99650}{99720}Sigurna sam da æemo|ovdje naæi za svakoga ponešto.
{99790}{99868}- Joy, jesi li dobro?|- Moram u kupaonicu.
{99872}{99934}Timmy æe me odvesti.
{100211}{100315}Nemoj sebe kriviti.|Uèinili smo pravu stvar.
{100394}{100445}Ovako je puno bolje.
{100446}{100522}Dobar dan. Sretan Dan zahvalnosti.
{100621}{100716}Odlazim. Ostat æeš sama.|Da vidimo kako ti se to sviða.
{100719}{100768}Mama.
{101814}{101864}Mama?
{101892}{101951}Mama, jesi li dobro?
{102154}{102192}Oprostite.
{102195}{102323}Francuski, ruski, plavi sir,|zaèin za salatu, talijanski, seljaèki.
{102711}{102834}Sve pripremljeno u restoranu.|Imamo i èokoladnu tortu...
{102836}{102894}- Ne zvuèi li to dobro?|...buènicu.
{102897}{102952}Servirate li i šlag s tortom?
{103659}{103707}Ovaj komad?
{103807}{103858}Evo.
{103889}{103974}- Hoæeš da ja otvorim?|- Ne, ja æu.
{107696}{108666}Subtitles by:|M O Z E N

