{1}{14}
{25}{137}Poèeli su kao i nesretni | ljubavnici iz stare Verone.
{148}{204}Ovo je Verona u New Jerseyu.
{224}{315}Cijela Verona znala je obiteljsku svaðu | koja ih je razdvajala.
{325}{417}Ti? | -Ti?
{461}{551}Prestolani? | -Barem nisam Montebello.
{552}{611}Radije æu se vratiti natrag.
{660}{721}Sve je poèelo s pizzom.
{754}{847}Montebello, | najbolje pizze u Veroni.
{855}{928}Pizzu Stari svijet, posebnu, | odmah.
{929}{965}PROSLAVA SV. GENNARA 
{966}{1061}Prestolani, bolja od najbolje | pizze u Veroni.
{1062}{1135}Može, Novi svijet | sa svime gore.
{1136}{1378}{C:$0000FF}{y:ib} RAT |{C:$FF0000}{y:b} PIZZA 
{3008}{3051}Spremna je, tata.
{3099}{3149}Adios, maestro.
{3175}{3217}Antonio!
{3231}{3273}Antonio!
{3288}{3407}Ok, Antonio, | ravno na tu adresu.
{3513}{3587}Predaj ju dok je | sir još topao.
{3875}{3977}Oh, moje fotografije.
{3985}{4097}Oh, žao mi je. -U redu je. | Imam ih.
{4135}{4197}Hvala. | -Nije potrebno.
{4337}{4427}Hvala. -Posljednji poziv, vlak za | New York City.
{4443}{4587}Propustit æu vlak. | - Ok.
{5034}{5180}Ljudi, gibajte. Nije teško, | brašno je, idemo.
{5190}{5297}Kako ste? Pizze prijaju? | -Hej, što æemo s tolikim brašnom?
{5301}{5439}Lani su me Montebellovi iznenadili. | Pojavili su se na fešti s 300 pizza.
{5444}{5575}Ove godine, bit æu spreman. | Napravit æu 368.
{5613}{5688}Haj, Gina. Dobrodošla kuæi.
{5689}{5814}Vidjela sam slike sa diplome. | I znaš, izgledaš pametnija. -O, hvala.
{5815}{5882}Mali Billi je uzbuðen je biti | u tvom razredu na jesen.
{5883}{5930}Što, u kakvom mojem razredu?
{5931}{6025}U maloj školi, zafrkantice. | Vidimo se na fešti.
{6150}{6234}Što æeš sa zajmom? | Sredit æu drugi tjedan, obeæavam?
{6253}{6300}Gina! | -Gina?
{6301}{6449}Gina, napokon doma. -Zdravo. | -Jako si mi nedostajala.
{6450}{6522}Zdravo, tata. | Primi ovo.
{6551}{6637}Haj, Annette. | Dobrodošla.
{6640}{6770}Što je bilo, napustila Chicagu u žurbi? | - Ne, nezgodica na stanici.
{6771}{6913}Gina, koje slike. | Uvijek vidiš drugaèije, posebno.
{6914}{7022}Fotografija, zaboravi. | Ništa neæeš zaraditi kao fotograf.
{7025}{7109}Slikat æeš vjenèanja, | a svoje neæeš imati.
{7110}{7182}Više æeš zaraditi | kao nastavnik.
{7227}{7367}Vidjet æeš, malo sam ispremještala | svoju sobu. -Misliš našu sobu.
{7370}{7447}Èetiri godine te nema. | -Dobro, samo kažem.
{7559}{7614}Kako lijepo!
{7635}{7720}Ne sviða ti se. | Vratit æemo natrag, dobro.
{7721}{7847}O, gdje mi je bila glava, da ureðujem. | Nemam diplomu umjetnosti i dizajna.
{7857}{7953}Dobro je. | -Dobro, ne valjda... èudno.
{8003}{8092}Kamo su mi nestale fotografije?| -U garaži.
{8150}{8219}Možeš ih ponijeti sa sobom, | kad se udaš za Carla.
{8220}{8294}Što je to tu, udajem se za Carla,
{8295}{8394}predajem, i još æu živjeti u | ružièastom leopardovom brlogu?
{8395}{8482}Gina, jer si otišla u grad, | misliš da je život stao?
{8483}{8616}Presvlaèi se, idemo u restoran! | I zamijeni majicu, uzmi nešto ljepše.
{8629}{8733}Što ne valja s majicom? | Otac je pozvao ljude, proslaviti tvoj povratak.
{8755}{8850}Nije zabava zbog diplome, je li? | -Iznenaðenje!
{8851}{8957}Iznenaðenje!
{9007}{9110}Hura, Gina. | -Hvala, pravo iznenaðenje!
{9118}{9177}Zdravo, ljudi.
{9290}{9372} TOMMY'jeva KUHINJA 
{9474}{9535}Hej, ljudi! | -Hej, Joe!
{9545}{9628}Oprosti, kasnim. | -Ne brini. Ove poznaješ, je li?
{9629}{9709}Kuhari. | -Ovo je.. Jean Paul. On je nitko.
{9710}{9754}Drugim rijeèima, nisam kuhar.
{9755}{9832}Posjeduje restorane. | Ne kuha kao mi.
{9833}{9943}Jean Paul, otvaraš restoran u gradu? | Htio sam otvoriti 100, u franšizama,
{9944}{10009}ali, propalo je.
{10010}{10101}Oprostite, Tommy, za stolom 14 | žele upoznati glavnog kuhara.
{10126}{10235}Tako se radi. -Odmah sam natrag. | Nemoj da mi tko gleda karte!
{10270}{10399}Joe, valjda si donio nešto za igru. | -Imam recepata za ložiti.
{10400}{10478}Davaj na stol. | -Igrat æemo ih za poker.
{10479}{10624}Govedina Puttanesca! | -Tko ima više? -Plaæam i poveæavam...
{10625}{10772}Osobuco, s paradajzom, | maslinama i umakom.
{10796}{10886}Dodajem... slasticu koja grije u zimskoj noæi.
{10888}{10932}Požutiš šalote luk,
{10933}{10967}da se kroz njega ne vidi,
{10980}{11019}dodaš pileæu bujon,
{11020}{11062}tuèeno vrhnje,
{11071}{11106}limunov sok.
{11107}{11182}Sorrento, prave limune!
{11198}{11253}Zgusneš, na ravnomjernoj vatri,
{11254}{11296}dodaš tjesteninu,
{11315}{11357}pokriješ rezanim pršutom,
{11446}{11514}Tjestenina: | a'la Montebello!
{11557}{11648}Zato svojom rižom | s jastogom, plaæam!
{11653}{11728}-Odustajem, èovjeèe. | -Joe, hoæeš li pratiti,
{11744}{11807}razotkrij pizza umak!
{11850}{11892}Umak za pizzu?
{11896}{11958}Sve to daješ za umak za pizzu?
{11974}{12037}Tommy je uložio recepte | restorana s 5 zvjezdica.
{12038}{12120}To je božanski umak za pizzu, | božanski umak.
{12129}{12215}Skrivaju ga u obitelji generacijama. | Nitko ga nije zapisao.
{12260}{12302}Reci, Joe.
{12326}{12368}Igraš ili ispadaš?
{12622}{12668}Odustajem.
{12703}{12745}Ma daj!
{12804}{12852}Dobro odigrano!
{12935}{12982}Èetiri devetke?
{12986}{13016}Zafrkavaš me?
{13017}{13047}Nije se isplatilo.
{13048}{13077}Oprostite.
{13094}{13194}Žao mi je što prekidam, Tommy, | uskoro stiže publika iz kazališta.
{13195}{13264}Dobro ljudi, moram zaraditi najam. | Idemo.
{13296}{13351}Mary, pomoæi æeš mi?
{13407}{13482}Umak, zbilja je tako dobar? | -Da.
{13488}{13556}Ali, nema šanse | da te odvedem u svoju kuhinju.
{13560}{13616}Naravno, niti kad bi ti se pružila prilika?
{13617}{13697}Možda prilika uložiti u 100 kuhinja? 
{13698}{13740}U franšizama? 
{13899}{13979}Želim nazdraviti... Gini,
{13980}{14042}zbog povratka u Veronu.
{14045}{14115}Divno je da si se vratila | kamo pripadaš.
{14132}{14178}Za Ginu!
{14198}{14233}Hvala!
{14234}{14324}Hajde, poðimo. | -Glazba, zabava do daske.
{14430}{14489}Daj mi balon.
{14491}{14570}Pazi, otiæi æe.
{14572}{14614}Daj ga meni!
{14638}{14766}Što sad rade? | Hoæe svu struju uzeti, sve usisati.
{14769}{14811}Eto, pogledaj.
{14820}{14900}Ciguliganje je gotovo. | Evo ti sada!
{14901}{14943}Vinnie!
{15005}{15048}Znam što pokušava!
{15058}{15093}Pokušava mi dati novi | srèani udar.
{15094}{15166}Vinnie, smiri se. | -Smiren sam, ok?
{15185}{15267}Nicky, izlazi odande. | -Što je, idem na sastanak.
{15276}{15356}Dodaj mi crijevo, Casanova. | -Što æeš uèiniti, Vinnie? -Što æu?!
{15357}{15432}Pustit æu kišu na sveèanost, | to æu.
{15433}{15504}Joe, prièaj s tatom, smiri ga. | -Rado. 
{15505}{15574}Tata, slušaj. | Upoznao sam poslovnog èovjeka,
{15575}{15685}traži kamo investirati... franšize. | Zainteresirao sam ga za pizze.
{15686}{15791}Èemu bi mi to trebalo? | Sve je sasvim dobro, sretan sam.
{15792}{15882}Nicky, požuri! | -Navoj zeza. Smiri se, odmah æu.
{15883}{15985}Tata, to je prilika. | Ovo nam zbilja ide u prilog.
{16020}{16054}Znaš što nam ide u prilog?
{16055}{16123}Što? | -Znam što nam ide u prilog.
{16161}{16203}Mikrovalovi.
{16257}{16299}Joe!
{16318}{16360}Tata!
{16439}{16492}Carlo!
{16560}{16615}Drago mi te je vidjeti. | -Sad je poslovoða.
{16616}{16687}Da, tata, rekao si mi | to tisuæu puta.
{16692}{16737}I jako je zgodan deèko. 
{16738}{16798}Reci mu zdravo, | zagrli ga.
{16799}{16841}Hajdemo.
{16970}{17029}Haj, Carlo! | Haj, Annette!
{17046}{17116}Lijepo cvijeæe. | -Karanfili.
{17117}{17192}Znaš, cvijeæe koje | deèko nosi djevojci.
{17193}{17258}Volim... karanfile.
{17259}{17319}Da? Htio sam uzeti krizanteme,
{17320}{17410}ali ne pristaju za ljeto. | -Više su jesenje cvijeæe.
{17411}{17468}Pa si... donio karanfile.
{17532}{17622}Da, Carlo, uvijek | znaš ponešto o neèem.
{17633}{17688}Volim biti u tijeku dogaðanja, Annete.
{17689}{17731}U svemu sam takav.
{17760}{17802}A gdje je Gina?
{17866}{17896}Sestrièna Gina!
{17897}{17962}Balon je na drvetu Montebellovih.
{17963}{18003}Hoæeš nam ga dohvatiti?
{18004}{18072}Da, idem po ljestve. | -Hvala.
{18125}{18235}Pusti to, odi s bratom van, | traži djevojku, zaèini si život.
{18236}{18266}Moram pobrati limune.
{18267}{18337}Možeš ujutro. | -Ne mogu, to su sorenti.
{18338}{18383}Beru se kad su zreli,
{18384}{18459}Ostanu li predugo na drvetu, | ne valjaju nikome.
{18460}{18502}Izgube aromu.
{18541}{18603}Neke stvari ne mogu | èekati sutra.
{18607}{18657}Joe, jesi li sretan?
{18708}{18789}Sretan sam, mama. Vidiš!
{18879}{18921}Reæi æu ti kad ne budem.
{19120}{19194}Dohvatit æu ih ja.
{19440}{19508}Ti? | -Ti?
{19532}{19576}Prestolani?
{19583}{19640}Barem nisam Montebello.
{19684}{19774}Neka glasna i buèna zabava | je kod vas?
{19775}{19817}Kojim povodom?
{19851}{19910}Ja sam povod tomu,
{19917}{20032}nekakva proslavica diplome.
{20183}{20233}Pa... sretno diplomiranje.
{20274}{20332}Limun? | -Najbolji limun.
{20425}{20470}Oprosti, zaboravio sam zamotati.
{20871}{20918}Poði tražit svijeæe, Lou.
{21252}{21360}Oh, hvala. | -Èini se još padaš na mene.
{21373}{21415}U redu.
{21544}{21590}Hvala.
{21620}{21690}Jako mi je žao što sam | zaboravio doèekati na stanici.
{21691}{21741}Otac me... poslao u Bronx,
{21742}{21817}stiglo pet kutija šunke iz Parme, | htio je da osobno podignem.
{21818}{21888}zaglavio sam s pakiranjem, | a na povratku...
{21889}{21939}grade novu obilaznicu.
{21940}{21975}Istraživao sam...
{21976}{22039}time skreæu još više kamiona...
{22040}{22107}Carlo, u redu je | što me nisi doèekao.
{22108}{22153}Trebao sam doæi.
{22154}{22199}Oprostit æeš mi,
{22200}{22240}ti si moja djevojka. | -Ne Carlo, ja...
{22241}{22316}Dobro što si se vratila, | više nisi srednjoškolka. 
{22317}{22382}Više se neæemo razdvajati.
{22515}{22572}Joe, jesam ih, ha?
{22604}{22656}Znao sam da æe izbiti transformator.
{22660}{22710}Vidio si kako je iskrio?
{22721}{22777}Da, tata, bilo je | toliko iskri.
{22822}{22912}Uvijek smo te sreæe, Montebello | sve uništi.
{22913}{22984}Jesi pomislio potrošiti novac i | dodati vlastiti pretvaraè?
{22985}{23064}Bandera je na mojem vlasništvu. | -Dobro, nagodite se po pola.
{23065}{23125}Ne možeš s Montebellom | po pola.
{23126}{23211}Daš mu pola, uzme | tri èetvrtine, znam.
{23212}{23262}Svi kažu nek mrzim Montebellove.
{23263}{23317}Ali ne znam zašto bi | ih mrzila.
{23318}{23378}Tata ti nije isprièao prièu?
{23379}{23414}-Ne, ne tu prièu, molim.
{23415}{23465}To je povijest obitelji.
{23466}{23508}Važno je.
{23522}{23592}Doðite djeco, sjednite.
{23598}{23682}Sjednite. | Svi tiho, tiho!
{23684}{23724}Nekoæ davno,
{23725}{23770}u staroj domovini...
{23771}{23813}Tu misliš na Brooklin.
{23822}{23917}Ne... u staroj, | staroj domovini,
{23918}{23973}u Veroni, u Italiji.
{23979}{24104}Prestolanovi su stvorili najbolje | što je izišlo iz Italije.
{24105}{24190}Impresivnije od | Michelangelovog Davida,
{24191}{24266}vjeènije od renesanse,
{24267}{24326}bila je to pizza!
{24398}{24508}Kraljica Margarita i svita | sastali su se u crkvi.
{24519}{24649}Vaš pra-pra-pra-pra-pradjed
{24650}{24740}Giuseppe Prestolani, | hitao je
{24741}{24858}obaviti najprviju | isporuku pizze.
{24932}{25027}Zašto pra-pra-pra- | pra-Prestolani izgleda ljutit?
{25028}{25128}Jer su Montebellovi | ukrali ideju za pizzu,
{25129}{25234}i predstavili ju kraljici | kao vlastitu.
{25300}{25360}Svaða je potrajala | zanavijek.
{25361}{25391}Hej, tata!
{25392}{25453}Si kad pomislio da je | prièa, samo prièa?
{25454}{25488}Znaš, fikcija.
{25489}{25569}Zapati nešto o fikcijama, Gina?
{25570}{25664}Ponekada su istina.
{25696}{25778}I nema moguænosti da | spor završi?
{25792}{25845}Zašto bi pa to htjeli?
{26088}{26196}Blagoslovi, obitelj, | vjera, prijateljstvo,
{26199}{26299}posve nas okružuju, | i uzimamo ih zdravo za gotovo.
{26300}{26409}Kad uðete u novi tjedan, | pomislite što znaèi biti velikodušan.
{26426}{26496}Dok se veselimo | dolazeæem...
{26647}{26724}dolazeæem blagdanu Sv. Gennara,
{26728}{26783}razmotrite i | vrijeme praštanja.
{26784}{26809}vrijeme dobroèinstva,
{26810}{26880}vrijeme da možda | dobijemo novi krov.
{27341}{27421}Lui, daj mi stotaka kojeg sam ti jutros dao.| -Zašto?
{27422}{27474}Stavio je smotak petaka.
{27475}{27535}Želi da izgledam loš pred Bogom.
{27880}{27951}Je li ga drmnulo?
{28180}{28229}Joe, ovamo.
{28406}{28461}Joe... stari!
{28562}{28604}Joe, ovamo!
{28728}{28768}Budem ja. | -Budite tiho!
{28769}{28857}Svi! Ovo je kuæa | Gospodinova.
{28955}{28977}Žao mi je, Oèe.
{28978}{29051}Vidi ovo, Joe Montebello | krade novac crkve.
{29052}{29132}Ne krade novac. -Znaš da se šuška | da je radio za CIA-u.
{29133}{29213}Moraš paziti, | jer bi mogao i tebe ukrasti.
{29214}{29256}Poludila si.
{29290}{29332}Dosta!
{29481}{29589}Ok! Koji je bistroglavi omotao | petaka...
{29590}{29665}oko role letaka? 
{29843}{29914}Dobro jutro, oèe? | -Kako ste?
{29924}{29968}Do srijede, oèe.
{29980}{30020}Gina! -Oèe, oh...
{30021}{30071}Lijepo je što si nam se vratila kuæi.
{30072}{30128}Puno hvala, misa je bila odlièna.
{30148}{30184}Ne mislim da su me ozbiljno slušali.
{30185}{30279}Ne primajte osobno, | nikoga ne slušaju.
{30280}{30345}Naiði drugi tjedan, | pokazat æu ti tvoju uèionicu.
{30346}{30381}Moju što, moju uèionicu?
{30382}{30417}Tvoj te otac prijavio.
{30418}{30504}Naravno, prihvatili smo. | Bit æeš prava uèiteljica male škola.
{30505}{30623}Oèe Spacio, netko treba razgovarati | s mojim ocem, molim vas.
{30625}{30699}Hej, Gina, dolazi! | Idemo na doruèak.
{30711}{30782}Molim vas. | -Gina, hajde.
{30867}{30909}Joe! -Zdravo, oèe. 
{30910}{31002}Probaj doæi na vrijeme drugi tjedan. -Da.
{31165}{31291}Hvala. -Svaki tjedan dolazim, a | odlazim sve zbunjeniji.
{31305}{31352}Nemoj meni prièati.
{31430}{31466}Nick, za što si molio?
{31467}{31519}Ne mogu reæi, | ne bi se ostvarilo.
{31523}{31599}Molitva je bila za roðendansku želju Nicky, | možeš reæi.
{31600}{31689}Southbeach manekenke. | Mislite na djevojke u crkvi?
{31690}{31740}Ne djevojke, mama, manekenke.
{31741}{31781}Modeli, dat æu ti.
{31782}{31834}Znaš za što sam ja molio?
{31838}{31908}Da tata razmotri franšize | s onim J.T.-om.
{31909}{31939}Joe,
{31940}{32015}umak je u obitelji | preko 100 godina.
{32016}{32046}Zašto bi ga podijelio?
{32047}{32127}Zadržat æemo tajnu umaka, | i jedino tako æemo napredovati.
{32128}{32173}Pre-rizièno!
{32209}{32251}Porastu li franšize, 
{32305}{32381}mogli bi Prestolanija | izgurati iz posla.
{32396}{32471}Prvo što si smisleno | rekao do sada.
{32472}{32537}Misliš da zbilja to možemo? | -Apsolutno!
{32538}{32592}Puno bi porasli,
{32599}{32641}možda se obogatili.
{32660}{32720}Da se obogatimo, | usadio bi usadke na prsa,
{32721}{32783}ne bi oblaèio košulju. | -Tiho!
{32792}{32832}Ti, prièaj!
{32833}{32878}Možeš ga dovesti na festival?
{32879}{32909}Hoæu ga upoznati.
{32910}{32950}Naravno, sad æu nazvati.
{32951}{32981}Lakše.
{32982}{33067}Kako znaš da Lou Prestolani | nije iza svega,
{33068}{33098}da nije...
{33099}{33216}skovao urotu| izbaciti nas iz posla?
{33218}{33288}Misliš da je Lou Prestolani unajmio | istražitelja
{33289}{33373}da doðe njuškati u našu pizzeriju,| u Veronu, New Jersey.
{33375}{33450}Da se pozabavi kraðom našeg umaka? | Ma daj!
{33451}{33536}Nemoguæe, ali ne kažem | da nije moguæe.
{33537}{33612}Reæi æu ti za Loua | Prestolanija, ok?
{33613}{33758}Oduševljava se Blofeldom, Strombergom i | Scaramangom. 
{33834}{33909}Kime? -Protivnicima Jamesa Bonda.
{33910}{33984}Ništa te nisu nauèili u toj CIA-i?
{34031}{34071}Poðimo na tortu sa sirom.
{34072}{34114}Tako se govori.
{34138}{34178}Hajde na posao!
{34179}{34239}Noæas, igrajmo pravu igru, 
{34240}{34362}pokažimo noæas Montebellovima | kako se pizza pravi!
{34621}{34651}Još!
{34652}{34682}Joooš!
{34683}{34753}Drži ih odignute i pokrij, | neka drže toplinu.
{34759}{34824}Carlo, moram s tobom razgovarati.
{34825}{34870}Gina, ne mogu odmah.
{34871}{34921}Trebam puniti 50 èaša le parmesane deserta.
{34922}{35022}Carlo, noæas nema smisla. Fešta je | svake godine sve luða.
{35023}{35088}Gina, moraš iæi.
{35089}{35147}Reci bar jedan razlog | zašto bi trebala?
{35165}{35276}Ove godine, smješteni smo | toèno nasuprot Montebellovih.
{35291}{35331}Jesmo li?
{35332}{35407}Sjedit æemo oèi u oèi | s Montebellovima?
{35408}{35457}Bit æe to pravo!
{35549}{35600}Hej, kamo ideš?
{35605}{35655}Trebam se presvuæi, | govorit æemo kasnije.
{35656}{35698}Doviðenja.
{35992}{36022}Znaèi dolaziš na feštu?
{36023}{36068}Lovim auto, upravo. | Taksi!
{36069}{36149}Odlièno. Kad stigneš pitaj za | najbolju pizzu u gradu.
{36150}{36218}Budem tamo. -Kamo? | -Verona, New Jersey.
{36391}{36473}Jean Paul stiže. | -Jean Paul?
{36482}{36577}Francuz? Trebam Francuza da mi pokaže | voditi talijanski restoran, je li?
{36578}{36673}Tata, to je Papino ime, Jean Paul, | moralo bi nešto znažiti.
{36674}{36704}Da, ima smisla.
{36705}{36747}Hoæeš se prestati igrati!
{36816}{36883}Smješteni smo toèno nasuprot njima.
{36887}{36917}Smjestili su nas nasuprot Prestolanovima?
{36918}{36978}Da, svi æe biti tamo. | Nije li to super?
{37019}{37061}Da!
{37065}{37165}Tata, ti peci pizze... | moram se presvuæi.
{37166}{37208}Presvuæi što?
{37232}{37262}Kecelju.
{37263}{37332}Prljava je, sva je od umaka.
{37344}{37390}Na njoj uvijek bude umaka.
{37485}{37557}Stari, hej! | -Joe, što ti je?
{37636}{37686}To si obukla za prodavat pizzu?
{37687}{37753}O da, kad je takav poseban dan.
{37783}{37872}Valjda æeš raditi nešto | posebno s Carlom?
{37874}{37937}Možda. Ne znam...
{37945}{38010}imam predosjeæaj da æe biti dobra fešta.
{38011}{38053}Vidimo se.
{38292}{38334}Blago tebi.
{38593}{38662} DOBRODOŠLI NA SLAVLJE | SV. GENNARA 
{38719}{38759}Joe, doði, poèinjemo.
{38760}{38842}Ne mogu, tata, èekam J.P.-a. | Gdje je?
{38871}{38941}Priðite! Hajde!
{38942}{38982}Ove æemo ih godine srediti, da? 
{38983}{39033}Hajdemo svi, priðite! Ovamo!
{39034}{39100}Moji prijatelji Verone! | -Moji prijatelji Verone!
{39101}{39170}Ovo je veliki trenutak! | -Predstavljam vam...
{39171}{39277}Kosi toranj od pizza!
{39427}{39482}Ukrao si mi ideju!
{39483}{39533}Pizza-gužvaè!
{39534}{39569}Moraš imati mozak.
{39570}{39605}Da bi imao ideju.
{39606}{39690}Oèito, nisam ništa ukrao.
{39692}{39785}Kad su svrstavali bez-mozgavce, | vi ste zaboravili stati u red! 
{39798}{39889}Nemam pojma o èemu govoriš? | -Upravo to mislim! 
{40099}{40143}Zaboravi!
{40150}{40215}Tvoj toranj pizza veæi | je no njegov.
{40216}{40315}Zbilja? -Da, on ima mali toranj.
{40317}{40379}Tvoj je puno veæi.
{40633}{40673}Hej, Lou!
{40674}{40716}Možemo razgovarati?
{40720}{40775}Carlo, što je, što si nervozan?
{40776}{40824}Bit æe posebna veèer.
{40827}{40897}Cannoliji? Volim cannolije.
{40898}{40974}Lou, ne možeš to jesti, znaš... | To je posebna fila.
{40975}{41026}To mi je najbolji dio. | -Lou, nemoj.
{41085}{41127}Lou!
{41216}{41267}Prsten od dva karata.
{41302}{41398}Tražim dopuštenje da Gini | dam ovaj cannoli. 
{41413}{41481}Carlo, Gina ne voli cannolije.
{41504}{41604}Ne voli? | -Ali vjerujem da æe ovog voljeti.
{41715}{41793}Znaš da sam te | uvijek smatrao sinom.
{41801}{41896}Sjeæam se da si me | otpoèetka zvao ljenèinom.
{41907}{41937}To zvuèi obiteljski.
{41938}{41988}A sad æeš i postati.
{42004}{42044}Kad æeš ju zaprositi?
{42045}{42087}Dat æu joj na Ferrisovom kotaèu.
{42096}{42126}Odlièna ideja.
{42127}{42217}Ti tamo èekaj, ja æu ju | naæi i poslati ju.
{42233}{42275}Hvala, Lou.
{42444}{42484}Oprostite, madmoiselle!
{42485}{42545}O, to pa nisam skoro èula. 
{42546}{42599}Poèeo sam od vas, došao sam na feštu i
{42600}{42651}i tražim... najbolju picu u gradu.
{42652}{42708}Mislim da tražite | bolju od najbolje.
{42709}{42751}Poðite sa mnom.
{42873}{42953}Koja predivna kombinacija sireva. | Božanstveno.
{42954}{43010}Kako sam rekla, bolja od najbolje.
{43034}{43070}Uzet æu cijelu.
{43071}{43157}Hej, Gina, Gina! | -Pozdravi mi Joea.
{43222}{43267}Zbog èega si nasmijan?
{43268}{43368}Uèini mi molim uslugu. | Želim da Carlu kažeš... da!
{43369}{43439}Da? -To je poruka. Da.
{43440}{43485}Zašto ti ne kažeš Carlu da?
{43486}{43538}Vjeruj, bolje æe zvuèati od tebe.
{43562}{43642}Tata? -Što? | -Je li se pojavio? -Ne.
{43643}{43729}Dobro... da. | -Odmah poði, on je kod Ferrisovog kotaèa.
{43730}{43786}Idi! | -Donijet æu, dobar tek!
{43787}{43878}Idi! | -Dobro!
{43966}{44036}Kamo si ti pošla? | -Annette, trebam te uslugu!
{44037}{44087}-Ne, zaboravi. Neæu preuzeti | tvoju smjenu.
{44088}{44158}Trebaš reæi Carlu | da je tata rekao da.
{44169}{44219}Zaboravi, sama æu. | -Oh, ne, hoæu.
{44220}{44265}Budem. -Ok, kod Ferrisovog kotaèa je.
{44266}{44322}Hvala. | -Odlièno.
{44422}{44493}Puno sam razmišljao...
{44503}{44588}Mislim da... Evo što mislim!
{44599}{44641}Mislim da trebam...
{44670}{44700}Znaš...
{44701}{44741}Razmisli...
{44742}{44787}Mi veæ stvarno dugo...
{44788}{44864}Dobro, ne ide mi... 
{44865}{44899}Što to?
{44900}{44975}Haj, Annette. | -Imam ti nešto reæi.
{44976}{45064}Vozite se ili ne? -Ne, èekam... | -Da!
{45065}{45145}Volim Ferrisov kotaè. Ti ne?
{45180}{45228}Proèitao sam u Enciklopediji Britanici.
{45229}{45319}Prvi kotaè postavio je | George Washington Ferris.
{45320}{45403}1893., | na izložbi u Chicagu.
{45421}{45486}Da, kako znaš?
{45487}{45572}Kviz! Nisi jedini koji | želi biti informiran.
{45683}{45782}Oh, to je cannoli? Volim cannolije.
{45784}{45826}Ovaj, probaj ovog.
{45830}{45865}Bolji je. -U redu.
{45866}{45927}Dobro. Evo ga!
{46192}{46240}Nadam se da æeš | naæi što tražiš.
{46293}{46335}Možda upravo jesam.
{46359}{46469}Ne bi tu trebala biti s tobom. | Vidi li nas tko zajedno, bit æe nevolja.
{46470}{46542}O, tako sam se prepao.
{46551}{46624}Usput, mislim da se znaš braniti.
{46632}{46674}Ja sam taj s ožiljkom.
{46688}{46730}Doði ovamo.
{46804}{46882}Ne mogu vjerovati da se | još ljutiš, Montebello? 
{46885}{46925}Imao sam deset godina.
{46926}{46971}Ne vidim nikakvog ožiljka.
{46972}{47016}Pogledaj bliže.
{47073}{47115}Bliže.
{47164}{47214}Svi misle da sam | te namjerno gaðala.
{47215}{47255}Jesi. | -Molim te!
{47256}{47296}Lopta je bila majušna. 
{47297}{47367}Udarala sam loptu, kako... | Kojoj je na putu bilo moje lice.
{47368}{47410}Upravo.
{47499}{47562}Ipak, dobro si prošao.
{47580}{47622}Misliš li?
{47631}{47692}Hej, Gina! Gina!
{47707}{47782}Ne znam jesi li primijetio, | ali naše se obitelji ne vole.
{47783}{47823}Zbog neèeg u vezi pizze?
{47824}{47889}Ma da, naša je | pizza najbolja.
{47890}{47930}To je jer nisi kušala našu.
{47931}{47992}Hej, Gina! Gina!
{48022}{48064}Moram se vratiti štandu.
{48103}{48145}I ja.
{48364}{48468}Znaš, grozno je što | tu nema mirnog kutka.
{48485}{48543}Sjenica, stražnji ulaz.
{48561}{48611}Oh... da, može.
{48612}{48722}Tamo bi mogli dogovorili... to s pizom, | jednom zauvijek.
{48723}{48771}Upravo što sam imao na umu.
{48780}{48824}Naðemo se u sedam.
{48825}{48868}Nemoj donijeti loptu.
{48931}{49002}Tata... dolazim.
{49027}{49109}Prestolani! Bolja od najbolje.
{49183}{49238}Izvolite. Samo doðite.
{49584}{49619}Sigurno to želiš?
{49620}{49664}U igri sam ako i ti.
{50116}{50158}Nije loša.
{50167}{50225}Zanimljivo, ali...
{50318}{50360}Odlièna je.
{50404}{50446}Da.
{50790}{50850}Kako da je ostalo toliko pizza?
{50851}{50900}Zbilja želiš saznati?
{51040}{51112}O, Carlo, kako je prošlo s Ginom?
{51113}{51148}Ne znam, nisam ju našao.
{51149}{51199}Nisi našao? Na kotaèu?
{51200}{51278}Nije tamo ni došla. | -Kako misliš, nije ni došla?
{51280}{51336}A što je sa cannolijem?
{51337}{51377}Morao sam ga sam pojesti.
{51378}{51450}A što je s Ginom, | gdje je?
{51464}{51506}Ne znam.
{51640}{51710}A što se dogodilo nakon | što su te izbacili iz škole?
{51711}{51771}Nitko me nije izbacio, | maturirao sam s odliènim.
{51772}{51852}Tko kaže da sam izbaèen? | Svi o tom prièaju.
{51853}{51893}Da, a kako tvoj otac?
{51894}{51962}Riješio je neplaæene | kockarske dugove?
{51975}{52015}Kakvo to kockanje? 
{52016}{52061}U crkvi, izvukli su ga.
{52062}{52092}Molim te!
{52093}{52188}Što je s bratiæem | Tonyjem, koji je išao u zatvor? 
{52189}{52296}Tvoj bratiæ Tony je u zatvoru.| -Nemam bratiæa Tonyja.
{52328}{52370}Zbilja?
{52479}{52528}A ti i Carlo?
{52555}{52597}Skupa ste?
{52626}{52678}Komplicirano je.
{52742}{52792}Znaš što je komplicirano?
{52793}{52878}Cijeli život živimo odvojeni | zidom jedno od drugog.
{52879}{52962}Uopæe nemamo pojma | tko je druga osoba.
{53045}{53096}Ja sam Gina.
{53101}{53143}Joe!
{53797}{53875}Koliko je sati? | -Ti ne nosiš sat?
{53888}{53963}Ustanem kad i sunce izaðe, | peèem pizze,
{53964}{54035}idem kuæi kad se peæ ohladi, | što æe mi sat?
{54080}{54179}Morala bi se vratiti. | Otac me vjerojatno veæ traži.
{54186}{54253}Si kad napravila nešto | što otac ne bi želio?
{54257}{54315}Otišla studirati. 
{54343}{54385}Nije lako.
{54400}{54451}Volim obitelj,
{54455}{54532}ali ponekad ne volim biti s njima.
{54546}{54600}Ima li to smisla?
{54622}{54664}Prilièno.
{54698}{54765}Shvaæaš da ovo više | ne smijemo napraviti?
{54774}{54844}Da su kakve druge okolnosti...
{54845}{54894}ali je trenutno...
{54936}{54985}komplicirano.
{55012}{55055}Opet ta rijeè.
{55090}{55145}Naðimo se sutra u šest...
{55149}{55191}na željeznièkoj stanici.
{55200}{55252}Ne, neæe igrati.
{55331}{55380}Bi moglo u šest i èetvrt?
{55512}{55554}Baj.
{55778}{55878}Èiuvava, vrsta malog meksièkog psa,
{55879}{55958}Doberman, veliki...
{56020}{56107}Svi su se od brige | razboljeli, kamo si otišla?
{56191}{56249}Oh... otišla sam kuæi.
{56257}{56316}Zašto bi se ovamo vraæala?
{56318}{56341}Odmoriti se.
{56342}{56399}Naveèer. Tada spavamo.
{56400}{56458}Znaš, slabo lažeš.
{56461}{56542}Nešto je na tebi drugaèije, | promijenila si se.
{56560}{56672}Imaš umaka na majici. | -Pa što, koješta.
{56948}{57010}Predobar je da bi bio naš.
{57030}{57094}Oh, Bože, Gina Prestolani,
{57095}{57157}èiji umak si kušala?
{57316}{57357}Hej, Carlo! | -Gina.
{57358}{57422}Kako ti je. Èujem da ti je sinoæ bilo loše.
{57423}{57539}Ovaj, puno bolje... | zapravo trebam slobodnu veèer.
{57594}{57674}Dva dana si doma, | a još te nisam zapravo vidio.
{57675}{57705}Trebamo govoriti.
{57706}{57756}Da, slažem se, trebali bi...
{57757}{57804}ali ne veèeras jer...
{57823}{57865}imam sastanak s prijateljicom.
{57874}{57904}Prijateljicom.
{57905}{57952}Ko... kojom prijateljicom.
{57976}{58011}Iz škole.
{58012}{58087}Kad smo kod škole, | ljuta si jer te nisam posjeæivao?
{58088}{58178}Gina, htio sam, ali je ovdje | uvijek nešto naišlo.
{58179}{58239}Puno sam uposleniji otkako me | tvoj tata postavio za poslovoðu.
{58240}{58332}Da, Carlo, govori da | napravio strašan posao.
{58431}{58473}Hoæeš slobodnu veèer?
{58537}{58579}Uzmi ju.
{58598}{58640}Hvala!
{58880}{58959}Koliko loše? Imamo tri mjeseca, | a onda smo u nevolji.
{58960}{58990}Što?
{58991}{59056}Sve smo potrošili na fešti, | na kosi toranj pizze.
{59057}{59117}To je reklama, oglašavanje.
{59118}{59194}Oglašavanje èega, da izlazimo | iz posla.
{59199}{59229}Hoæemo li?
{59230}{59295}Lue, znam da ne voliš o knjigama,
{59296}{59366}ali moramo govoriti o knjigama.
{59380}{59437}Znaš moje mišljenje o knjigama.
{59443}{59512}Volim prièekati dok | ne iziðe film.
{59590}{59641}Što?
{59915}{59952}Hvala.
{60022}{60075}(šupèino)
{60076}{60171}Haj! | Ajme, izgledaš super.
{60172}{60232}Baš sam... to htjela reæi za tebe.
{60233}{60298}Samo naprijed. | -Izgledaš odlièno.
{60299}{60356}Zafrkava me?
{60370}{60429}Joe Montebello?
{60865}{60942}ZATVORENO
{60956}{61006}Donio si limune?
{61057}{61107}Što ima posebno | u tim limunima?
{61108}{61158}Stablo je zasaðeno | od bakinih limuna iz Italije.
{61159}{61229}Pokaži ljubaznost drvetu, | i ono æe tebi.
{61230}{61270}Što to znaèi?
{61271}{61301}Nemam pojma.
{61302}{61332}Bila je malo odsutna. 
{61333}{61378}Upadajte. Sve sam ti pripremio.
{61379}{61444}Joe i ja znamo se | veæ dugo.
{61445}{61530}Zajedno smo služili, | spašavao mi je guzicu u CIA-i.
{61531}{61561}Što, istina je?
{61562}{61642}Kulinarski institut Amerike.
{61648}{61740}Draga moja, našla si najbolju pjesmu, | nikad ispjevanu.
{61744}{61809}Ovaj je èovjek meðu najboljim kuharima | što su došli iz CIA-e.
{61810}{61845}To je prošlost.
{61846}{61906}Dao sam ti limune, i hoæu kuhati.
{61907}{61962}Hoæeš napustiti svoju kuhinju?
{61998}{62080}Sigurno ne trebaš pomoæ. | -Moæi æe i sam. Hvala.
{62194}{62254}Divno miriše. Što je to?
{62255}{62320}Nešto što pripremam | samo tebi.
{62331}{62361}Oh... trenutak.
{62362}{62421}Scampi a'la Verona | di Montebello.
{62423}{62477}To nudite | kod Montebellovih?
{62484}{62545}Ne smijem to ponuditi | kod Montebellovih.
{62563}{62605}Probaj ovo!
{62774}{62816}Nije loše.
{63020}{63072}Jela sam i bolje.
{63271}{63332}Ali ne u ovom životu.
{63422}{63467}Èudesan si, što se dogodilo?
{63468}{63523}Da radim u | obiteljskom poslu s pizzama,
{63524}{63589}i ostajem u selu? | -Aha.
{63635}{63677}Ne prièam o tome.
{63746}{63792}Hoæeš govoriti sa mnom?
{63857}{63912}Tata je imao srèani udar.
{63938}{63986}Èula sam.
{63994}{64034}Trebamo kuhara.
{64035}{64084}Netko je bio potreban.
{64085}{64133}Ja sam bio najpodobniji.
{64162}{64232}Tražio je da prihvatim | u 8:22 dopodne.
{64243}{64303}8:22 do podne, | zašto si to zapamtio?
{64304}{64359}Posljednji put sam | pogledao sat.
{64360}{64395}Zašto?
{64396}{64478}Jer mi je u tom | trenu vrijeme stalo.
{64702}{64739}Bit æeš fotograf?
{64740}{64793}Ako otac pristane. 
{64794}{64844}Što on ima s time?
{64845}{64905}Ti si taj koji kaže. | -Ozbiljno.
{64951}{64993}Probaj.
{65177}{65219}Božanstveno.
{65228}{65308}A za svoje snove, | zašto ocu ne objasniš,
{65309}{65355}da želiš raditi ono što želiš.
{65385}{65427}Moja su obitelj.
{65461}{65503}Toèno,
{65507}{65549}obitelj.
{65618}{65676}Doði, osmjeh molim.
{65879}{65954}Mislio sam, bit æu...
{65955}{66008}veliki kuhar, u gradu.
{66016}{66058}Kuhat æeš i dalje.
{66102}{66144}Ovako više nikada.
{66293}{66335}Odi sjesti.
{66539}{66632}Predivno. A tvoj brat, | kuha li on?
{66635}{66684}Ah, pokušao je jednog dana.
{66686}{66813}Sve je zagorilo, | crno u sosu, crno u calzoneu,
{66827}{66877}a kako je uspio | zagoriti salatu,
{66878}{66908}još uvijek nemam pojma.
{66909}{66951}Nije valjda tako loš.
{66980}{67022}Može biti?
{67036}{67071}Vatra u... uuuh!
{67072}{67149}Požar, jesam ju. Mirno.
{67273}{67310}Tata, gdje je Joe?
{67311}{67381}Bilo je slasno.
{67405}{67447}Isprièaj me.
{67481}{67521}Tommy, još jednom | hvala za kuhinju.
{67522}{67561}Sjeti me se kad budem trebao posao,
{67562}{67620}spomenuo sam te J.P.-u, | da doðe k tebi. 
{67621}{67691}Pa da. Nije se ni pokazao.
{67692}{67785}Joe, mislim ozbiljno. | Otišao je na feštu i pojeo cijelu pizzu.
{67786}{67851}Sutra æe te nazvati. | -Stvarno?
{67852}{67900}Mislim da se zainteresirao.
{67903}{67956}Bravo!
{67974}{68019}Valjda æe mi konaèno krenuti.
{68020}{68105}Imam oèi! Mislim da je | tebi veæ krenulo.
{68106}{68148}Vidimo se.
{68162}{68212}Hvala, cijenim... | -Hej, pripazi!
{68213}{68263}To su kopije, bude | te opelješio.
{68264}{68331}Onda, dobro sam odabrala?
{68340}{68387}Za mene? | -Aha.
{68521}{68611}Deset je i sedamnaest. | -Što je posebno sa 10:17?
{68637}{68702}Toèno vrijeme u koje | mi je život opet zapoèeo.
{68983}{69023}Donijela sam torte od sira.
{69024}{69080}Nisam baš gladan. Hvala.
{69093}{69150}Da podijelimo? | -Može.
{69189}{69278}Zašto si se... obukao?
{69285}{69370}Èekao sam... | Ginu da se vrati.
{69371}{69436}Èini se da puno provodiš | èekajuæi ju.
{69437}{69513}Da... nešto bi te pitao? | -Što?
{69533}{69612}Reæi æeš mi kako ti ovo zvuèi, ok?
{69764}{69806}Dobro...
{69850}{69880}Gina...
{69881}{69932}ovaj, Annette...
{69942}{70020}èudno je, znaš, | jer se dugo poznajemo.
{70053}{70112}Trebao bi možda biti na koljenima...
{70114}{70180}Ono što hoæu reæi je da...
{70230}{70294}Pripadamo jedno drugom, | ti i ja.
{70366}{70456}To jest, ti i ja... | drugim rijeèima...
{70622}{70664}Hoæeš se udati za mene?
{70698}{70740}Da!
{70754}{70832}Hoæu reæi, da, | zvuèi savršeno.
{70855}{70897}Mada...
{71051}{71146}Gina ne osjeæa za tebe ono, | što ti osjeæaš za nju.
{71147}{71237}Kako to reæi, | a ne povrijediti te? 
{71273}{71385}Cura s kojom se sinoæ sastala, | nije djevojka i nije samo prijatelj.
{71399}{71468}Voljela bi da | zaslužiš puno bolju.
{71470}{71550}Gina te nema prava | tako tretirati.
{71551}{71581}Kako me tretirati, | Annete?
{71582}{71647}Ne smijem, ne smijem.
{71648}{71698}Nije na meni | dati kažem.
{71699}{71744}Da je Gina izašla s | Joe Montebellom.
{71745}{71815}Hoæeš još kolaèa sa sirom? | Joeom Montebellom?
{71816}{71866}Gina je vani s | Joeom Montebellom?
{71867}{71907}Zbog èega urlaš?
{71908}{71953}Gina je vani s | Joeom Montebellom!
{71954}{72014}Što? Poludio si? | Sišao si s uma?
{72015}{72067}Možete biti tiše tamo?
{72101}{72186}Hej, reci sinu nek | drži ruke dalje od moje kæeri!
{72187}{72247}Moj sin se ne bi | ni približio tvojoj kæeri.
{72248}{72298}Zašto je onda sada s njom vani? | -Što?
{72299}{72379}Kažem ti, Montebello, | ovo mi se ne sviða! -Tebi?
{72380}{72435}Ni meni. A ne znam ni što se dogaða.
{72436}{72494}Ali vjeruj da æu otkriti.
{72532}{72574}Kasno je.
{72608}{72655}Ponoæ.
{72680}{72784}Zapamtiti æu svaki tren | ove veèeri.
{72835}{72920}Znaš, veèeras je možda zadnji put
{72921}{72972}da nekog ljubiš prvi put.
{73167}{73209}Joe!
{73218}{73280}Gina! | -Oh, Joe, kompa!
{73299}{73329}Ljubiš se s Montebellom?
{73330}{73360}Kako možeš?
{73361}{73437}Èini se da si u nevolji!
{73452}{73504}Što sam rekao, Montebello?
{73508}{73550}Koliko je sati?
{73589}{73631}12:01, zašto?
{73640}{73680}Jer je vrijeme meni stalo.
{73681}{73756}Zašto si s njom izašao, je li sine?
{73757}{73822}Što si radila vani s njim, | moja vlastita kæi?
{73823}{73863}Hoæeš mi dati još jedan | srèani udar, a?
{73864}{73939}Trebaš se udati za Carla. | -Tko je rekao da moram?
{73940}{74000}Zašto, zašto, zašto? | -Mama je rekla da si zaèinim život.
{74001}{74031}Ne sa arsenom?!
{74032}{74087}Arsen nije zaèin.
{74098}{74143}Pitao me. Rekao sam da.
{74144}{74204}Onda se udaj za njega. | -Pazi na usta!
{74205}{74249}Ona je Prestolani!
{74250}{74323}Zabranjujem ti! | Razumiješ?!
{74337}{74417}Zabranjujem ti s njom izaæi! | -Gotovo je, Gina!
{74418}{74458}Isfolirala si se u Chicagu.
{74459}{74549}Sad si doma. Sredit æeš se, | udati za Carla, pouèavati.
{74550}{74625}Dvadest pet mi je, | radit æu što æu raditi.
{74626}{74676}Prestar sam za ovo. | -Prestar za obitelj?
{74677}{74734}Neæiu pouèavati.
{74738}{74798}Nadam se da neæu dovoljno ostariti.
{74799}{74834}Reæi æu što ne budeš.
{74835}{74906}Više nikad neæeš vidjeti | Joea Montebella.
{75041}{75086}Što? -Zašto si im to isprièala?
{75087}{75137}Zna... znala si da æe se naljutiti, | i kazniti me.
{75138}{75178}Nemoj upirati u mene prstom.
{75179}{75214}Uperi ga u sebe.
{75215}{75275}Ti si izašla sa | Joe Montebellom.
{75276}{75321}Mi smo sestre.
{75322}{75396}Zato jer imamo | istu majku i oca,
{75403}{75443}nismo zato sestre.
{75444}{75504}Ne razumijem te, | Annette,...
{75505}{75555}Ne shvaæam zašto se | stalno na mene ljutiš...
{75556}{75622}zašto se stalno povlaèiš...
{75632}{75729}I ne shvaæam zašto | stalno èitaš enciklopediju?
{75733}{75817}Samo ti trebaš | ovdje biti pametna?
{75819}{75899}Za nekog tko je išao na fakultet, | glupa si.
{75902}{75982}Gine, nekada | moraš odabrati.
{76016}{76092}Ljubav, ili obitelj.
{76378}{76462}Hej, braco! | -Samo miješam umak.
{76528}{76570}Dobar je.
{76929}{76969}Tata, sjeæaš se Joea?
{76970}{77010}Joe, poznaješ tatu?
{77011}{77072}Bili ste otac i sin.
{77102}{77152}Hej, što kažete na | Yenkeeje?
{77163}{77209}Alex Rodrigues je zbilja...
{77264}{77315}žestok.
{77415}{77490}Sinoæ sam gledao obrazovni program,
{77491}{77541}o bengalskim tigrovima.
{77542}{77607}Imaju... genetski zapis,
{77608}{77663}ti tigrovi... po roðenju,
{77664}{77707}znaju koga æe napadati.
{77708}{77758}Mali tigriæ,
{77759}{77804}uvijek napada hijenu.
{77805}{77890}Prestolanovi su... | kao tigrovi.
{77891}{77986}A mi smo hijene? | -U ovom sluèaju, ti... si hijena!
{77987}{78042}Djevojka je neèemu predodreðena.
{78043}{78073}Ne može si pomoæi.
{78074}{78116}Jako griješiš, tata.
{78145}{78212}Montebellovi, najbolje pizze | u Veroni.
{78221}{78251}Da, prièekajte.
{78252}{78298}Joe, tvoj Francuz.
{78363}{78398}Hej, J.P., kako si?
{78399}{78429}Kako ti se | dopala pizza?
{78430}{78540}Što reæi Joe, pizza je odlièna, | ali nije mi se dopao umak.
{78541}{78576}Pa svi vole umak.
{78577}{78622}Bio je dobar, ne odlièan.
{78623}{78678}Ali volim sireve.
{78679}{78764}Slasna je, Mocarela, smekšala me. 
{78765}{78830}O, ne. J.P., nisi...
{78836}{78899}Kušao si krivu pizzu. | -Kako misliš?
{78902}{78972}Pitao sam djevojku za | najbolju pizzu u Veroni,
{78973}{79068}Ona je pitala: | Hoæete bolju od najbolje? I jesam.
{79069}{79149}To je bila Prestolanijeva. J.P., vrati se, | probaj našu.
{79150}{79210}Sutra, s investitorima. | Morate probati umak.
{79211}{79291}Dobro, ali sad moram dati | jednaku priliku i Prestolanovima.
{79292}{79364}Ne bi njima razbijao glavu. | Nego J.P., još jedno,
{79373}{79458}djevojka koja ti je pokazala pizzu, | je li...
{79459}{79499}imaš njeno ime?
{79500}{79565}Osmjehuje se kao | da joj ne treba ime.
{79566}{79634}Ali netko ju je zvao Gina. | Poznaš ju?
{79697}{79739}Mislio sam da da.
{79883}{79925}Bio si u pravu, tata.
{79949}{80006}Ja sam hijena.
{80140}{80182}Gina!
{80186}{80261}Hvala... hvala! | -Zašto?
{80262}{80317}Za što, mislila sam | da sa mnom ne govoriš?
{80318}{80373}Toèno, i ja sam mislila da ne prièaš s njom?
{80374}{80424}Imaš kakve stolove za èistiti?
{80425}{80477}To neæe proæi,
{80478}{80583}ona se vani smuca s Montebellom, | a ja neka èistim nered. 
{80584}{80642}Dovela nam je Francuza u kiosk.
{80643}{80703}Došao je radi dogovora | s Joe Montebellom,
{80704}{80844}Gina mu je dala našu pizzu, | i zainteresirala je Francuza za nas.
{80855}{80930}Gina, možda si riješila | sve naše probleme.
{80931}{80973}Hvala, dušo.
{81092}{81134}Što sam rekao?
{81238}{81280}Gina!
{81349}{81404}Gdje je Gina? | -Nije ovdje!
{81435}{81478}Imam nešto za nju.
{81721}{81772}Zdravo Gina. Hej!
{81932}{81977}Gðo. Montebello, trebam | govoriti s Joeom.
{81978}{82067}Oh, žao mi je, otišao je. | U bolnicu.
{82074}{82141}U bolnicu? | -Da, mislim da mu...
{82142}{82220}moraju veliku nožinu... | izvuæi iz leða.
{82221}{82281}Sad izlazi! | -Ne, èekajte, moram s njim govoriti...
{82282}{82343}Moram s njim govoriti, molim!
{82345}{82378}Gðo. Montebello!
{82379}{82437}Molim vas, gðo. Montebello!
{82910}{83010}Trebali bi me docrtati| k Montebellovima.
{83011}{83057}Nemoj se gristi.
{83072}{83120}Usputno, ne ljutim se.
{83153}{83268}Èuj, vidim to ovako: | Bili smo dobar par u srednjoj.
{83269}{83314}Prekinuli smo do završetka fakulteta.
{83315}{83357}...tvog.
{83366}{83411}Nije nam bilo loše u srednjoj.
{83412}{83482}Srednja mi je u lijepim | uspomenama, Carlo.
{83698}{83747}Donio je to maloprije.
{83774}{83816}Èuj, Gina...
{83835}{83875}pogriješila si sinoæ.
{83876}{83918}Zaslužio sam.
{83932}{84011}Više nego drugi, otac ti može potvrditi.
{84030}{84093}Ali Gina, ti si Prestolani!
{84099}{84194}Oduvijek si, i ne pripadaš | Montebellovima.
{84225}{84270}Nešto sam istraživao.
{84271}{84401}Neki ljudi su po cijelu zimu u svjetioniku.
{84407}{84449}Znaš zašto?
{84478}{84565}Pomažu izgubljenim brodovima | pronaæi put kuæi.
{84639}{84689}Ti si poput, | izgubljenog broda,
{84690}{84745}ja sam svjetionièar.
{84771}{84820}Pomažem ti naæi | put kuæi.
{85122}{85188}Nemoj predugo ostati izgubljena.
{86113}{86183}Drago mi je g. Prestolani, | upoznajte moje partnere.
{86184}{86234}Nadam se da imate dobar apetit.
{86235}{86277}Ulazite, ovuda.
{86401}{86436}Kod Prestolanovih su.
{86437}{86497}Donesi paket. | -Odmah, tata.
{86678}{86788}Prestolanovi su uvijek razumjeli u sir.
{86789}{86864}Moj pra-pra-djed u stvari
{86865}{86955}bio je poznat kao | veliki sirar Verone.
{86956}{87036}Naravno, težio je skoro 180 kg, | ali to nema veze.
{87037}{87122}Došao je kao poznavatelj parmezana,
{87123}{87216}pekorina i mocarellija.
{87219}{87289}Isto znanje imamo i danas,
{87290}{87340}ovdje u ovom restoranu.
{87341}{87402}Lou, dopustimo neka probaju pizzu.
{87652}{87682}Imao sam pravo, je li?
{87683}{87753}Miševi! | Miševi u restoranu!
{87754}{87804}Što se dogaða, ne panièari!
{87805}{87847}Samo ih je nekoliko miševa.
{87911}{87962}Podmeæe nam ih dvaput godišnje.
{87972}{88014}Nemojte iæi.
{88028}{88098}Montebello ih podmeæe. | Samo dva puta godišnje.
{88099}{88132}Vratite se!
{88133}{88175}Vratite se!
{88234}{88282}Francuzi se svega uplaše.
{88365}{88440}Paradajzi, koje koristimo u umaku,
{88446}{88506}potjeèu od iste stabljike
{88507}{88582}kakvu je moj pra-pra-pra-djed donio iz
{88583}{88668}stare domovine, prije | više od sto godina.
{88689}{88749}Zovemo ju Stari svijet, | jer to je.
{88750}{88844}Blaga i bajna, | kao Stari svijet.
{88871}{88944}Bon apetito! | -Hvala.
{89677}{89762}Što je ovo? | -Prestolani napada elektrikom.
{90078}{90138}Ubijaju me, ubijaju!
{90139}{90199}Dosta. | -Sredio sam alarm.
{90215}{90292}Trebam obje obitelji | na neutralnom terenu, odmah!
{90293}{90329}Gdje, u Švicarskoj? | -Da!
{90330}{90402}Naðite mi Švicarsku | u Veroni, New Jersey, smjesta.
{90403}{90489}Mjesto gdje se | obitelji ne bore.
{90509}{90551}Postoji li?
{90675}{90750}Oèe Specia, uvjereni ste | da nemate što protiv?
{90751}{90786}Uèinite što | možete, molim vas.
{90787}{90855}Dao bi vam svoj okovratnik, | kad bi pomoglo.
{90858}{90922}Ti ljudi me izluðuju.
{90949}{90993}Ovo nije jako profesionalno.
{91300}{91379}Joe, mislim ti objasniti.
{91696}{91756}Jako mi je žao | što se ovo dogaða.
{91787}{91832}Uživao sam u vašoj pizzi.
{91833}{91873}I dopada mi se vaša pizza.
{91874}{91962}Ali u krevet odvesti mogu | samo jednog od vas.
{91980}{92040}Isprièavam se. | Mogu otiæi
{92041}{92106}u posao, s jednom obitelji.
{92107}{92167}Opet æemo se sastati, | za tjedan dana,
{92168}{92213}naèinit æu ugovor | s onima,
{92214}{92286}koji uspiju s najboljom | sveukupnom pizzom.
{92290}{92325}A do tada,
{92326}{92386}nema više borbe,
{92387}{92464}podmuklosti | ni sabotaža.
{92503}{92572}Ima li ovdje itko prigovora,
{92584}{92687}treba govoriti sada, | ili zanavijek šutjeti.
{92800}{92845}Zdrobit æemo ih, tata.
{92846}{92951}Otiæi æe k vragu. | -Nema ih za tjedan dana.
{92967}{93049}Što æemo sada? | -Lou, da ja radim umak!
{93053}{93128}Naravno, tata, | sposoban je.
{93129}{93164}Lou, to je izazov.
{93165}{93240}Volim izazove, daj mi | tjedan dana.
{93241}{93357}Tjedan, Lou, i dat æu ti najbolji | vražji pizza umak u Veroni.
{93432}{93474}Dobar si momak, Carlo.
{93553}{93595}Primimo se posla.
{93804}{93898}Hej, netko je to ostavio | pred vratima.
{93905}{93965}Osobno ne mislim da si zgodan,
{93966}{94042}njoj oèito jesi, jamèim.
{94057}{94099}Nedostaje mi, Nicky.
{94133}{94255}Znaš Joe, uvijek te | vidim u vrtu,
{94259}{94308}provjeravaš paradajze na stabljici,
{94315}{94384}mirišeš ih, zuriš u boju.
{94396}{94426}Nisi zadovoljan.
{94427}{94530}Sve godine si tražio | savršeni paradajz,
{94533}{94630}a savršeni paradajz stalno je | rastao kod susjeda.
{94799}{94862}Valjda moram i ja reæi | nešto što voliš èuti.
{94905}{94947}Imaš pravo.
{95056}{95099}Joe, što je bilo? | -Imam nešto u peænici.
{95100}{95175}Ne, ne, ne. -Ja æu to obaviti. | Idi!
{95178}{95220}Idi!
{95374}{95439}Nosi se odavde. | -Trebam s tobom razgovarati.
{95440}{95509}Nisi htio u crkvi. | -Gina! -Što?
{95621}{95686}Znaš zašto ga zovu balzamski ocat? | -Ne, ne znam.
{95687}{95772}Jer misle da je | balzam koji sve lijeèi.
{95773}{95858}Štoviše, èak i slomljeno srce.
{95919}{95961}Probaj.
{95975}{96035}Ne. | -Nije otrov.
{96036}{96078}Vidiš?
{96577}{96657}Gina, žao mi je.
{97218}{97260}Mrzim te.
{97319}{97361}Zašto?
{97375}{97426}Jer djeluje.
{97516}{97585}Hej, Gina, jesi li tamo?
{97652}{97694}Gina?
{97768}{97833}Gina! Gina!
{97834}{97876}Trebam pomoæ!
{97920}{97962}Zdravo, tata.
{98016}{98097}S kim si prièala ovdje? | -Nikime...
{98142}{98192}To je velika dostava, a?
{98193}{98235}Aha.
{98929}{98971}Pitao sam se,
{98990}{99063}koji nam je vrag, | nismo se nikad svaðali.
{99066}{99138}Pokušaj, neæu urlati.
{99142}{99182}Nisam Annette.
{99183}{99219}Ona to želi.
{99220}{99322}Ja ne, ne želim pouèavati u maloj školi, | ne želim se udati za Carla,
{99330}{99414}Hoæu biti fotograf, | biti s Joeom.
{99416}{99471}Propast æe, kad | Jean Paul nas odabere.
{99472}{99580}U vezi toga, trebamo nazvati | Jeana Paula i odustati.
{99588}{99678}Što? -Rekao si da neæeš urlati. | -Nisam mislio da æeš ludjeti.
{99679}{99759}Trebamo ugovor. | -Toèno, ali nije nama namijenjen.
{99760}{99840}Joe je taj koji je doveo Jeana Paula. | -Briga me kako je došao do nas.
{99841}{99896}Ne odustajemo.
{99897}{99977}To je mi, ili oni. | Kako je oduvijek bilo.
{99998}{100068}Jesi li u obitelji, | ili ne, Gina?
{100104}{100172}Vrijeme je da odabereš.
{100220}{100290}Nemoj me siliti | da moram birati.
{100291}{100360}Je li te on uvukao u smicalicu? | -Ne bi to nikada uèinio.
{100367}{100444}Jedini razlog zašto Montebello | nije sklopio posao
{100445}{100495}sam ja.
{100513}{100556}A što sam ja uèinila?
{100563}{100647}Povrijedila sam...
{100669}{100752}nekog u kog sam | zapravo zaljubljena.
{101150}{101202}Pomislio sam da æu te naæi.
{101256}{101298}Poznam tog tipa.
{101407}{101449}Pamtim da sam bila sretna.
{101463}{101493}Vidiš.
{101494}{101536}Fotografija dokazuje.
{101560}{101617}Nisam ti htio donijeti teškoæe. 
{101646}{101721}Joe, kad sam došla kuæi, nisam | bila sigurna što želim. 
{101722}{101786}Te veèeri... | rekao si... 
{101787}{101834}Nisam tako kuhao godinama.
{101950}{102014}Otac je rekao | da trebam odabrati.
{102036}{102085}Ljubav ili obitelj.
{102197}{102239}Razumijem te.
{102248}{102302}Nadala sam se da hoæeš.
{102319}{102372}Jer od tog trenutka si
{102395}{102440}sva moja obitelj.
{102756}{102812}Kao da plaèeš, je li?
{102852}{102894}Možda malko.
{102998}{103077}Znaš da moramo napustiti Veronu. | Noæas.
{103084}{103126}Za mnom.
{103210}{103315}Trebam vam pomoæi da pobjegnete? | -To je odskoèna daska za buduænost.
{103316}{103362}To nije dobro.
{103377}{103474}Moramo sjesti s obiteljima | i to riješiti.
{103498}{103588}Ako pomaže, dovest | æu kardinala. -Ne pomaže.
{103589}{103679}Neæe se predomisliti, otac je paranoidan. | -Mojeg drma srce.
{103680}{103768}Jedino što se dosad ovdje | promijenilo, smo mi.
{103786}{103862}Molim vas, morate | nam pomoæi.
{104102}{104144}Gdje je majica?
{104565}{104620}Kako sam propustila?
{104889}{104969}Tako, odlazimo u zalazak | dostavnim vozilom?
{104970}{105050}Znam... ali | èemu æe se djeca smijati?
{105051}{105081}I ja mislim.
{105082}{105158}Valjda æe ih Otac Specio | zadržati u crkvi. 
{105213}{105255}Hej, Tommy.
{105260}{105317}Možeš nas smjestiti u gradu? | Odlièno.
{105350}{105397}Tommy, ne možeš mi to uèiniti.
{105421}{105490}Vrijedi. Vrijedi.
{105492}{105587}Tommy stvara teškoæe, | primit æe nas, ali æe koštati.
{105588}{105618}Što želi?
{105619}{105674}Limune. Hrpu limuna.
{105675}{105727}Moram natrag u restoran.
{106066}{106162} RECI MU ŠTO OSJEÆAŠ! | VOLI TE SESTRA 
{106372}{106494}Ne, ne, ne, ne, | dosta više s tim.
{106498}{106577}Sjednite zajedno, | kao ljudi.
{106579}{106701}Ali, Oèe... -Jedini ali želim vidjeti | dok ste zajedno u klupi.
{107135}{107195}Želim da sakupite glave,
{107196}{107256}i razmislite zašto ste ovdje.
{107377}{107422}Ne znam ... zašto sam ovdje.
{107423}{107458}Imam posla za obaviti.
{107459}{107507}Dobiti ugovor.
{107515}{107564}Mi æemo dobiti ugovor. | -To misliš?
{107565}{107645}Ne mislim, znam. | -Dosta je.
{107687}{107748}Mislite da ne znam | što radite,
{107758}{107798}ali on zna.
{107799}{107866}On sve vidi!
{107870}{107912}I rekao mi je!
{107926}{107968}Zato, nema više miševa,
{107992}{108057}nema više mikrovalki.
{108058}{108128}Dobar je, jako dobar.
{108129}{108189}Ne mislite da znam, ali znam.
{108190}{108277}Želim da sjedite i razmišljate, | što ja to znam.
{108351}{108455}Dobro. Kleknut æu i moliti | da dobijem ugovor.
{108467}{108509}Evo, Lou.
{108518}{108587}Samo æu ja moliti bolje.
{108999}{109041}Haj, Carlo!
{109090}{109145}Haj, Annette! Radim na umaku.
{109146}{109226}Kuhanje ti je kao znanost, | puno pokušaja i proba.
{109227}{109277}Približavam se, | jako sam blizu.
{109278}{109357}Zbog toga je sve kao da | je kuhinja eksplodirala?
{109404}{109462}Da, kao.
{109470}{109500}U redu je.
{109501}{109531}Ne mogu nabasati.
{109532}{109608}Probao sam sve recepte | odavde do Hobockena.
{109620}{109695}Dobar je, | ali ne odlièan.
{109719}{109783}Možda imaš krive sastojke.
{109795}{109825}Sve sam iskušao,
{109826}{109901}prstohvat ovoga, | žlièicu onoga. 
{109902}{109947}Cijeli dan rezuckam èešnjak.
{109948}{110026}Možda trebaš probati nešto novo.
{110044}{110099}Nešto neoèekivano.
{110130}{110172}Kao što?
{110236}{110278}Kao ovo.
{110727}{110832}Želim to uèiniti | tako dugo,
{110833}{110918}ti i Gina, | krivi sastojci, Carlo.
{110919}{111011}Ona je spoznala, | ja sam spoznala.
{111015}{111057}Pitam te,
{111076}{111120}znaš li i ti?
{111220}{111280}Sjeæaš se dana kad sam prosio Ginu?
{111293}{111333}Mislim, tebe u ime Gine?
{111334}{111376}Znaš o èemu prièam? | -Da.
{111380}{111445}Kad god sam pokušao,
{111446}{111519}prošnja Gine mi nije pravo sjedala.
{111547}{111589}Ali s tobom...
{111593}{111645}osjeæao sam kako treba.
{111654}{111740}Nisu bile važne krive rijeèi, | jer si me razumjela.
{111745}{111832}Uvijek znaš što hoæu reæi, | prije dovršim, Annete.
{111906}{111968}Ne znam zašto | to prije nisam skopèao.
{111982}{112028}Uvijek si tu.
{112043}{112100}I stalno me iznenaðuješ.
{112189}{112298}Oprosti, suviše prièam, ponekad moram... | -Zavezati.
{112558}{112627}Želiš otiæi nekamo...
{112634}{112664}razgovarati?
{112665}{112707}Zakljuèat æu nas!
{113596}{113667}Mirišeš nešto? | -Pokupi limune i idemo!
{114042}{114087}Donesi protupožarni iz kuhinje!
{114088}{114133}Èemu æe ti? | -Brzo, restoran vam je u plamenu.
{114134}{114184}Što? Oh!
{114310}{114340}Hajde, Gina, požuri!
{114341}{114383}Evo!
{114722}{114764}Hajde!
{114803}{114843}Joe, brže!
{114844}{114894}Hajde!
{114900}{114942}Ne radi!
{115061}{115103}Joe!
{115157}{115204}Požuri, Joe!
{115233}{115288}Joe, žuri!
{115329}{115371}Žuri!
{116015}{116109}Ovo je smiješno. | -Vjeruj, s tobom se ne slažem.
{116146}{116199}Nosimo se odavde.
{116202}{116262}Htjeli bi ovo uzeti, | prije no poðete.
{116263}{116293}Imam za vas pisma.
{116294}{116354}Od tvog sina, | i tvoje kæeri.
{116355}{116433}Objašnjenja, zašto su morali | napustiti Veronu.
{116456}{116498}Oh, Bože moj!
{116542}{116582}Sve je to tvojom greškom!
{116583}{116625}A ti si planirao, je li?
{116644}{116694}Haj, gðice Russo...
{116695}{116737}Što ne valja?
{116740}{116769}Što se dogodilo?
{116770}{116824}Restorani su u plamenu. | -Što?
{117118}{117173}Sve je otišlo. | Oba restorana.
{117174}{117216}Što...
{117240}{117270}Što je s Joem?
{117271}{117313}I Ginom?
{117317}{117359}Ni znaka još.
{117518}{117560}Lou,
{117609}{117660}ovo je otišlo predaleko.
{117775}{117810}Doðite, povest æu vas unutra.
{117811}{117877}Ovuda. Pazite kamo stajete.
{118602}{118644}Ovamo!
{118753}{118803}-Joe! | -Gina!
{118819}{118884}Živi su, živi su!
{118885}{118937}Joe, dobro si? | -Gina!
{118961}{119016}Oh, hvala Bogu!
{119017}{119057}Zbilja si dobro?
{119058}{119140}Vratili ste se! -Gina!
{119189}{119262}Dušo, oprosti što sam bila | takva.
{119275}{119310}Voljela sam Carla,
{119311}{119391}nisam ti rekla. | -Razumijem, zbilja.
{119392}{119427}Nadam se da i on tebe.
{119428}{119500}Voli, voli.
{119504}{119546}Hvala.
{119595}{119653}Joe, dobro si? | -Da, jesam.
{119671}{119728}Mislila sam da sam | te izgubila.
{119827}{119887}Žao mi je, što si to prolazila.
{119888}{119942}Znam, znam tata.
{119959}{120001}I ja tebe volim.
{120025}{120078}Hej, ti, usijana glavo!
{120086}{120142}Ja? | -Da, ti!
{120152}{120219}Gina, ima biti s Joeom!
{120228}{120280}Joeom Montebellom.
{120294}{120336}Voli ga.
{120345}{120387}Samo to je važno.
{120396}{120446}Ako ti je to problem,
{120447}{120527}imat æeš štrajk konobarice | na duši.
{120528}{120568}Štrajk konobarice?
{120569}{120611}Gotovo je!
{120625}{120702}Nisam imao novac za platiti | osiguranje za prošli mjesec.
{120726}{120756}Nije gotovo, Lou.
{120757}{120799}Tek poèinje.
{120808}{120868}Imali smo vremena razgovarati | na drvetu.
{120869}{120914}Gini sam dao recept za naš umak.
{120915}{120980}A ja njemu tajnu sastava sireva,
{120981}{121021}i kako ih kombiniramo.
{121022}{121067}O èemu oni to?
{121068}{121098}Hej, ja ne znam.
{121099}{121129}Što to rade?
{121130}{121165}Svi, tiho!
{121166}{121206}Da dovršimo!
{121207}{121266}Ne želimo da se | sve vrati na staro.
{121267}{121338}Stvari æe se od sada | zbilja promijeniti.
{121339}{121407}Monebellovi, prestajete s poslom.
{121410}{121465}Isto i Prestolani. | -Što?
{121466}{121546}S današnjim danom, | proglašavamo ujedinjenje.
{121547}{121607}Montebello i Prestolani.
{121608}{121648}Zvat æemo se...
{121649}{121714}Prestolani, i Montebello.
{121715}{121809}Montebello i Prestolani.
{121850}{121935}Dosta! | Joe i ja, sada smo glavni.
{121942}{121984}Što to znaèi?
{122098}{122190}ŠEST MJESECI KASNIJE 
{122224}{122294}Možemo uæi? | -Ne, privatna zabava.
{122310}{122357}Pogledaj fotografije!
{122371}{122466}Nema li gina Prestolani | odlièno oko?
{122467}{122507}Kupila sam jednu prošli tjedan.
{122508}{122598}Ima galeriju u centru, | trebali bi promisliti o investiranju.
{122599}{122639}Dušo, uložit æu u picu.
{122640}{122675}Trbuh me ne vara.
{122676}{122766}Vrtio bi pizze i spotove.
{122767}{122822}Stavljao bi pizze i vrtio ploèe.
{122823}{122849}Parti na suncu.
{122850}{122936}Malo si bio na suncu, | i veæ te spalilo.
{123049}{123078}Umak sa stabljike.
{123079}{123114}Sir iz Italije.
{123115}{123157}Pizza iz Jerseya.
{123181}{123226}Sam ti rekao da je | dobra zamisao?
{123227}{123306}Hej, moja ideja je| da se udružimo.
{123318}{123418}Tvoja? Domislio sam se | kad još nisi imao ni pojma.
{123439}{123469}O èemu smo prièali?
{123470}{123500}Prestanimo.
{123501}{123546}Prvo Chicago, pa Miami,
{123547}{123621}San Francisco i | onda... Pariz.
{123653}{123703}Vidite tko se vratio.
{123704}{123767}Dobrodošli.
{123770}{123852}Baš na vrijeme | za otvorenje.
{123856}{123911}Znaš koji problem | imaju na Karibima?
{123912}{123942}Nema dobrih piza.
{123943}{123988}Uobièajeni poljoprivredni zasadi,
{123989}{124039}uzgajaju kukuruz, a povræe je suviše...
{124040}{124118}Hej, Carlo, | budi tiho, molim.
{124136}{124201}Joe, lijepo si ovo uredio.
{124202}{124237}Misliš? | -Èudesno je.
{124238}{124335}Ona u San Franciscu bit æe ista | uz jednu veliku razliku.
{124354}{124396}Kakvu to?
{124450}{124506}Ljudi, mogu tražiti | pozornost, molim?
{124531}{124581}Zadovoljstvo mi je pretstaviti
{124582}{124655}novog upravitelja Prestobella | u San Franciscu.
{124656}{124699}Ako prihvaæaš.
{124700}{124754}Da, jasno.
{124755}{124785}Idem u San Francisco?
{124786}{124865}Mi idemo u San Francisco! | -Idemo u San Francisco!
{124882}{124924}Odlièno! Bravo!
{124953}{124983}Tiho!
{124984}{125024}Svi tišina!
{125025}{125070}Želim nazdraviti...
{125071}{125176}krasnom, predivnom novom restoranu, | Prestobellovih!
{125177}{125247}Za Prestobello! | -Prestobello!
{125293}{125358}Za Ginu i Joea!
{125359}{125418}Za Ginu i Joea!
{125445}{125490}Oh, za Annette i Carla!
{125491}{125549}Za Annette i Carla!
{125577}{125619}Recite nešto, djeco!
{125678}{125712}Dobro, trebali smo birati 
{125713}{125794}izmeðu ljubavi i obitelji, i...
{125795}{125852}Odabrali smo.
{125896}{125944}Uzimamo oboje.
{126195}{126244}Joe, kompa!
{126280}{126340}Krasno, pravi deèko.
{126440}{126526}Za ljubav! | -Za ljubav!
{126900}{127212}{C:$0000FF}{y:ib} preveo: |{C:$FF0000}{y:b} drdamjan 
{127232}{127298}uloge:
{128020}{128077}osobe i dogaðaji izmišljeni... | sliènost sa mrtvima i živima sluèajna...
{128078}{128108}nisu povrjeðivane životinje, bla bla...
{128109}{128151}prava zaštiæena...
