{1}{1}25.000
{609}{720}Ave Caesar!
{727}{864}Q U O    V A D I S
{879}{985}Film|Jerzyja Kawalerovicza
{1646}{1787}Prema romanu|Henryka Sienkiewicza
{1796}{1874}Marko Vincije
{1883}{1971}Ligija
{1981}{2078}Petronije
{2088}{2162}Neron
{2175}{2267}Hilon Hilonides
{2279}{2358}Uostalim ulogama
{3554}{3628}Glazba
{3844}{3922}Redatelj
{4936}{5014}Marko Vincije, sin vaše sestre,
{5023}{5173}stigao je iz Male Azije.|-Uvedi ga .
{5296}{5417}Pozdrav, Petronije.|Neka te bogovi blagoslove.
{5427}{5515}Osobito Asklepije|i Kiprida . -Dobro došao.
{5525}{5603}Kiprida mi jeveæ|dala grèeve u nozi.
{5613}{5710}Što ima u Armeniji? Kako rat?|-Nije dobro.
{5721}{5793}Da nije Korbulona ,|izgubili bismo.
{5800}{5910}On je pravi bog|rata . Pošten i glup.
{5921}{6032}Drag mi je jer ga se|i Neron pribojava .
{6040}{6072}Nije on glup.
{6084}{6164}Možda . Mudrost se|ne razlikuje od gluposti.
{6173}{6272}Ovo je najbolje u životu.
{6279}{6361}Ali ti voliš i rat.|Ja ga prezirem.
{6369}{6445}Riðobradi voli|pjevati i svoju poeziju.
{6452}{6577}Ti ne pišeš pjesme?
{6588}{6657}Ne. -I ne sviraš|lutnju? Ne pjevaš?
{6667}{6739}Ne. -Onda sam miran.
{6746}{6807}Dobro je pisati pjesme,
{6813}{6924}ali bolje ih je|ne pisati ili pjevati.
{6933}{7045}Jedino je potrebno|diviti se Riðobradom.
{7054}{7109}Dobro došao !
{7117}{7164}Pozdrav !
{7173}{7331}Riskiraš da se|Popeja zaljubi u tebe.
{7431}{7530}Trebam savjet.|-Pogodila te Amorova strelica?
{7538}{7591}Na putu u Rim išèašio sam zglob.
{7600}{7762}Proveo sam nekoliko|dana kod Aula Placija .
{7769}{7878}Zar uz njegovu ženu?|-Ne, ne, uz Pomponiju.
{7884}{8003}Zovu je Ligija . Kalina|je njezino barbarsko ime.
{8011}{8091}Jednog se jutra|gola kupala u fontani.
{8100}{8197}Vidio sam zrake zore|kako joj prolaze kroz tijelo.
{8206}{8325}Znaèi, prozirna je|poput mlade srdelice?
{8333}{8430}Ne ismijavaj me.|Ludo sam zaljubljen.
{8436}{8551}Nemam mira . Ne želim|ništa drugo. Samo Ligiju.
{8558}{8622}Kupi je, ako je robinja .
{8631}{8728}Taokinja je.|Kæi ligijskog kralja .
{9223}{9326}Hvala ti što si mi|pazio na neæaka .
{9333}{9410}Zahvalnost me dovela amo
{9417}{9542}i to što te nikad nema|u Cirkusu ili amfiteatru.
{9552}{9671}Starci zavole svoj dom.
{9736}{9814}Poslušajmo izbliza|taj bezazleni smijeh.
{9823}{9915}AuI i Ligija igraju se|loptom. -Smijeh, Petronije,
{9925}{9999}rekao bih da tebi sav|život u njemu prolazi.
{10008}{10131}Život jevrijedan|smijeha i zato se smijem.
{10506}{10590}Ne znam jesi li|besmrtna ili si božica?.
{10602}{10666}Ako si od smrtnih Ijudi,|na Zemlji koji žive,
{10677}{10774}triput ti bili roditelji|i braèa blagoslovljeni.
{10783}{10941}Vidim da nisi zao|ni luda baš glava .
{10990}{11124}Èuti Homera od|tako mlade djevojke. . .
{11148}{11222}Našeg sina pouèava Grk.
{11231}{11321}Sluša njegove lekcije.
{11333}{11462}Kažu da je kljuè|sreæe dijeliti želje bogova .
{11473}{11570}Ali ja mislim da|drukèiji i veæi užitak
{11581}{11722}samo Ijubav može donijeti.
{11900}{11988}Bogovi tragaju za takvim užitkom
{11996}{12128}i slijedim ih, no buduæi|da nisam upoznao Ijubav,
{12136}{12272}tragam za onom|koja æe me usreæiti.
{12281}{12385}Znaš li zašto ti|sve ovo govorim?
{12394}{12455}Ne.
{12642}{12745}Tvoj je svijet isti kao i|svijet kojim vlada Neron.
{12752}{12875}Svijetom vlada Bog, a ne Neron.
{12883}{12997}Vjeruješ li u bogove,|Pomponijo? -U jednoga .
{13006}{13120}Taj je pravedan i svemoguæ.
{13231}{13323}Vjeruje u jednog|svemoguæeg Boga .
{13333}{13450}Ja ne. Slažem se da|žene imaju tri ili èetiri duše.
{13458}{13519}Od kojih nijedna nije razumna .
{13529}{13617}Ali hvalim tvoj odabir.|Podsjeæe me na proljeæe.
{13627}{13686}Želim jeviše nego ikada .
{13696}{13757}Mogao bih ubiti Aula|i Pomponiju i oteti je.
{13769}{13855}Još jedna besana noæ. . .
{13865}{13943}Išibat æu jednog|od svojih robova
{13954}{14013}i slušati ga kako jauèe.
{14023}{14060}Glupo razmišIjaš.
{14069}{14145}Moram je imati.|Ako ti ne pronaðeš naèin,
{14154}{14299}ja æu ga pronaæi.|-Razmislit æu.
{14308}{14402}Prièekaj me ovdje.
{14708}{14825}U oèima ti vidim da|ti vatra izjeda dušu.
{14836}{15007}Znaš li proricati?|-Plati i saznat æeš više.
{15090}{15201}Ljubav. . .I smrt. . .Šeæu uz tebe.
{15271}{15351}Uvrijedit æeš bogove.
{15361}{15418}Vatra æe odnijeti|više od tvoje duše.
{15429}{15466}Odlazi.
{15475}{15524}Ovo je za tebe. -Hvala .
{15534}{15632}Satirycon. Èiji?|-Moj. Ali to je tajna .
{15640}{15693}Rekao si da ne pišeš stihove,
{15702}{15763}ali ovdje ima više od proze.
{15775}{15847}Neron je razlog zbog|èega me poezija guši.
{15856}{15917}Neki se škakljaju po|grlu perom flaminga ,
{15927}{15982}a ja èitam Neronove stihove.
{15992}{16051}Instant olakšanje.
{16061}{16162}Teško ti bude u|srcu, a u trbuhu lako.
{16992}{17074}Donosim pozdrave i nalog cezara .
{17083}{17197}Hvala na pozdravima ,|a nalog æu poštivati.
{17208}{17354}U tvojoj kuæi živi|k æi ligijskog kralja .
{17365}{17437}Ponuðena je kao zalog|za sigurnost naših granica .
{17446}{17534}Po nalogu božanskoga|Nerona moram je odvesti.
{17613}{17730}Prièekaj ovdje, Hasta .
{17742}{17807}Ligijo. . . .
{17823}{17884}Volimo te kao da si naša k æi,
{17898}{17982}ali držanje taoca|privilegij je cezara .
{18048}{18105}Radije bih da je mrtva .
{18113}{18291}Molit æu cezara da|promijeni zapovijed.
{18352}{18444}Nije moguæe da je se sjeæa .
{18454}{18489}Petronije. . .
{18498}{18679}Neka je proklet dan|kad su bili u našem domu !
{18690}{18768}Zbogom, radosti naša .
{18777}{18900}Razgovarat æu sa Senekom.|Možda se on založi za te.
{18909}{19024}Domine, dopusti da|poðem s njom i da je zaštitim.
{19033}{19121}Ti njoj služiš, a ne|nama . Ali kako. . .?
{19138}{19235}Moje ruke lome željezo.
{19354}{19539}Gdje je Ligija?.|Govori ! Sto si uèinio?
{19571}{19685}Bogalj sam samo u|zoru. Veèer me razbudi.
{19692}{19772}Èini se da te u|gimnastici pouèava tkalac,
{19779}{19847}a pristojnosti kovaè.
{19892}{19976}Imaš željezni stisak,|ali ako si me izdao,
{19983}{20073}osjetit æeš èelik|mojega maèa . Gdje je?
{20083}{20160}Zamolio sam cezara dvije usluge.
{20171}{20265}Da je uzme Aulu|i da je preda tebi.
{20277}{20338}Gdje je tvoj maè?
{20350}{20480}Jer ti æeš u zatvor,|a Ligija u tvoju kuæu.
{20546}{20620}Oprosti mi. Znaèi,|nisi je htio za sebe
{20629}{20678}ili za cezara?.
{20686}{20797}Tigelin je carski svodnik,|a da sam je htio za sebe,
{20806}{20949}rekao bih ti to. -Zašto|nije poslana u moju kuæu?
{20958}{21087}Zbog zakonitosti.|Odvedena je kao taokinja .
{21096}{21162}Kad se o tome prestane govoriti,
{21173}{21288}u tajnosti æe biti|poslana u tvoju kuæu.
{21350}{21424}Pomponija me zamolila|da pazim na tebe.
{21433}{21515}I hoæu, ali nemoj|naljutiti Nerona .
{21523}{21638}Želi da te pripremim za gozbu.
{21663}{21747}Tako si dobra , Akte.
{21756}{21811}Zla nisam,
{21821}{21878}iako su mi sreæa
{21888}{21943}i radost nestale.
{21952}{22064}Ljudi su uèinili cezara|zlim. Prije je bio dobar.
{22071}{22249}Popeja . -Još ga voliš, Akte?
{22263}{22360}Nitko ga drugi nevoli.
{22367}{22416}Upoznat æeš ga na gozbi.
{22427}{22495}Zamoli Petronija i|Vinicija da ga nagovore
{22504}{22650}da tevrati kuæi.
{22738}{22874}Sto puta si Ijepša od Popeje.
{22992}{23175}Koja je božanska|zemlja dom ovakve Ijepote?
{23186}{23237}Ne sjeæam je se,
{23246}{23347}ali Urso mi je rekao|da su šume posvuda .
{23840}{23901}Ovdje su naša mjesta .
{23994}{24062}Pozdrav, o, najljepša .
{24071}{24307}Pozdrav, božanska .|-Pozdrav, Marko.
{24317}{24465}Blagoslov si mojim oèima .
{25117}{25191}Volim te, Ligijo.
{25200}{25312}Pusti me. -Voli i ti|mene, božice moja .
{25323}{25380}Cezar vas gleda .
{25392}{25462}Ti više nisi pokraj njega ,
{25473}{25551}a vele da ti prijeti sljepoæa ,
{25561}{25626}pa kako ga možeš vidjeti?
{25636}{25732}I on vas gleda kroz smaragd.
{25761}{25810}Petronije. . . .
{25819}{25880}U onu se taokinju|Vinicije zaljubio?
{25892}{25999}Tako je.|-I smatra je lijepom?
{26009}{26126}Vidi ti se u oèima .|Misliš da je premršava .
{26133}{26237}I primijetio si|njezinu veliku manu.
{26248}{26357}Preuska je u bedrima . -Tako je.
{26411}{26472}Slažem se s cezarom ! -Dobro !
{26481}{26557}Baš sam govorio da u|tebi ima malo pameti, a
{26567}{26686}cezar tvrdi da si prava budala !
{26761}{26843}Noæas sam|sanjala da sam vestalka .
{26852}{26966}Nakon èetiri razvoda?.|Samo u snu.
{26984}{27112}A da cezar tako zapovjedi?
{27159}{27220}Habet.
{27411}{27476}Popeja !
{27498}{27668}Zdravo, božanska Augusto !|-Dobro došla , božice !
{28463}{28528}Krotone !
{30194}{30313}Prije nego što se gosti|napiju, zapjevajte nešto.
{30325}{30439}Bogovi znaju koliko me|te izvedbe stoje muke.
{30446}{30520}Apolon mi je podario glas
{30529}{30619}i takav se dar ne smije|ostaviti da propadne,
{30629}{30674}ali zaista sam promukao.
{30683}{30777}Ne budi okrutan !|-Zapjevaj, cezare !
{31094}{31201}Za tebe. . .
{31215}{31367}. . .pjevam, o, jedina .
{31379}{31493}U boli. . .
{31502}{31666}. . .nudim ti svoju pjesmu.
{31679}{31800}Daleko si, tugo|moja ! I Ijiljani žale.
{31808}{31894}Voda s otrovom postaje gorka .
{31904}{32018}Vino postaje ocat. Nek'|Ijiljani opet budu bijeli.
{32025}{32173}Nek' voda opet dobije|okus, a vino bude nektar.
{32511}{32557}Da je o glazbi rijeè,
{32567}{32695}Orfej bi sada bio žut|kao naš Lukan ovdje.
{32702}{32814}Za stihove pak|žalim što nisu lošiji,
{32823}{32868}jer onda bih našao
{32881}{32963}prikladne rijeèi hvale.
{32973}{33039}Vidio sam te golu.
{33046}{33132}U fontani. Mislila|si da nema nikoga .
{33142}{33218}No, ja sam tevidio|i još te takvom vidim,
{33231}{33341}iako si sada odjevena .|Odbaci halju.
{33354}{33549}Razodjeni se. Kao što je|i Krispinila to uèinila .
{33984}{34140}Predivne ruke. . .|O, kako su lijepe.
{34150}{34242}Vidio sam takve ruke.
{34252}{34301}Ali èije?
{34311}{34364}Moje majke !
{34371}{34439}Moje majke. . . Agripine. . .
{34452}{34544}Kažu da obnoæ šeæe|po mjeseèini morem.
{34554}{34651}Kod Baja i Baula .|Kao da traga za neèim.
{34661}{34758}I tko god je|pogleda , umire.
{34767}{34843}Lijepa tema .
{34852}{34944}Morao sam. . .|Morao sam je ubiti. . .
{34954}{35044}Ona je bila unajmila|ubojice da ubiju mene.
{35054}{35103}Da je nisam pretekao,
{35113}{35234}Danas ne biste|slušali moje pjesme.
{35508}{35610}Ligijo, daj mi|svoje usne. -Pusti me !
{35619}{35769}Cezar te za mene|uzeo ! -Akte ! Akte !
{35777}{35865}Sutra æu poslati po tebe.|Ne mogu više èekati.
{35898}{35997}Moraš biti moja .|Ovdje, sada , smjesta !
{36013}{36105}Daj mi svoja usta !
{36113}{36201}Ostavi je,|Marko ! Pusti je !
{36277}{36307}Ligijo. . .
{36319}{36355}Ligijo. . .
{36367}{36399}Ligijo !
{37175}{37234}Ako tevoli, neka|traži od Aula tvoju ruku.
{37235}{37293}Ako tevoli, neka|traži od Aula tvoju ruku.
{37302}{37421}Radije bih se|vratila Ligijcima .
{37488}{37616}Tko je ta robinja?. -Nije|robinja , božanska Augusto.
{37623}{37707}Ona je taokinja koju|je odgojila Pomponija .
{37750}{37862}U posjetu ti je? -Ne,|smještena je u palaèi.
{37871}{37953}Po èijem nalogu?|-Cezarevu.
{37961}{38047}Radije bi živjela|ovdje? -Ne, gospo.
{38056}{38128}Nemam izbora .|Ponuðena sam Viniciju.
{38136}{38247}Kao robinja . -Cezar|te obeæao Viniciju?
{38254}{38375}Tako je, gospo.|Vratite me Pomponiji.
{38442}{38497}Imaš moju rijeè. . .
{38506}{38629}Još veèeras æeš|biti robinja Vinicija .
{38890}{39011}A ako plan ne uspije?|-Moli Boga da uspije.
{39142}{39218}Divna Ligijo, nosim ti|pozdrave Marka Vinicija .
{39227}{39350}Poziva te na|gozbu u svojoj kuæi.
{39448}{39538}Idem.
{39888}{39989}Juèer si bio pijan.|Ponašao si se kao zidar.
{39998}{40086}Zakuni joj se,|ako hoæeš i Hadom,
{40096}{40228}da sevraèa Pomponiji,|pa je nagovori da ostane.
{40236}{40355}Veæ pet godina tako|postupam s Krizotemidom
{40363}{40501}i ne mogu reæi|da je bila okrutna .
{40509}{40576}Veæ bi trebali biti tu !
{40586}{40670}Još æe im poæi ususret|i mimoiæi se s njima .
{40683}{40757}Veæ bi trebali biti tu !
{40767}{40872}O, gospodaru !|-Smilujte se !
{40881}{40928}Gdje je?
{40936}{40972}Borili smo se !
{40983}{41038}Gdje je?!|-Pogledajte krv !
{41048}{41142}Gdje? -Branili smo je. . .
{41165}{41249}Imajte milosti !|-Svi æete biti išibani !
{41263}{41341}Sto šiba !
{41352}{41422}Ako želiš vidjeti|svježe meso,
{41433}{41525}kupit æu ti mesnicu.
{41583}{41687}Akte, izbjegni|nevolju i reci istinu.
{41694}{41764}Cezar ju je odveo? -U|palaèi nije, kunem se.
{41773}{41901}Neron je uz kolijevku|svoga bolesnog djeteta .
{41909}{41989}AuI ju je odveo?|-Tako je Ligija htjela .
{41996}{42076}Sve si znala?. -Nije|htjela biti priložnica .
{42086}{42172}I ti si to bila . -Da ,|a prije toga robinja .
{42179}{42391}Ligija je cezarov dar.|Briga me njezina prošlost!
{42400}{42490}Bit æe mi konkubina ,|i bit æe išibana !
{42506}{42587}A kad mi dosadi,|dat æu je nekom robu.
{42596}{42754}Vidjeli smo Popeju i malu|Augustu. S crnkinjom.
{42763}{42807}Dijete se razboljelo,
{42813}{42943}a dadilja je rekla da|je Ligija urekla dijete.
{42950}{43060}Ako dijete ozdravi,|zaboravit æe. Inaèe. . .
{43067}{43172}Popeja æe optužiti Ligiju|i to æe biti njezin kraj.
{43179}{43276}Možda je i mene urekla?
{43283}{43404}Ne govori cezaru o njoj|dok dijete ne ozdravi
{43413}{43507}ili æeš navuæi|Popejinu osvetu na nju.
{43515}{43626}A veæ je dosta suza|pustila zbog tebe.
{43633}{43741}Ti jevoliš, Akte.
{43750}{43807}Da .
{43815}{43876}Zato što tebi|nije platila mržnjom.
{43884}{43955}Budalo slijepa ,|ona tevoli !
{43963}{44150}Nevoli me.|Mrzi me. Mrzi me.
{44163}{44332}Neka ti Bog oprosti|sve tvoje grijehe.
{44596}{44643}Kako je dijete?
{44652}{44705}Kako je božanskoj?!|-Neka ide k vragu !
{44715}{44797}Tišina ! Poði samnom|ako želiš pronaèi Ligiju.
{44808}{44914}Moji su robovi|motrili sve ulaze u grad.
{44983}{45104}Malarièan si.|-Bolestan sam.
{45113}{45187}Ne znam što bi|ti lijeènik dao,
{45194}{45282}ali znam što bih ja .|Ljubav je moèna .
{45290}{45387}Nijedna ju žena ne može|zamijeniti. Meðutim. . .
{45394}{45453}Lijepa robinja . . .|-Ne, hvala .
{45461}{45572}Možda tvoje za tebe|nemaju èara novosti.
{45581}{45720}Pogledaj ovu. Neka|ti ona bude moj dar.
{45729}{45803}Ne treba mi.|Cijenim ovo,
{45813}{45920}ali neæu.
{46044}{46132}Euniko,|okupaj se i namaži
{46140}{46216}i otiði kuæi Vinicijevoj.
{46223}{46297}Ne, gospodaru. Ne mogu.
{46306}{46365}Smilujte se, najdraži,|radije bih da me išibate
{46375}{46523}nego da me otjerate.
{46742}{46834}Tko je Eunikin|Ijubavnik? -Nitko.
{46842}{46955}Što znaš o njoj? -Provodi|noæi u svojim odajama .
{46963}{47024}Ne kupa se s|ostalim robovima .
{47033}{47086}Ponudio sam je
{47094}{47188}Viniciju, no odbio ju je.
{47198}{47249}Ustani.
{47258}{47335}Ostat æe ovdje
{47344}{47445}Odvedi je i daj joj|dvadeset i pet šiba .
{47456}{47620}Pazi da joj ne|pokvariš kožu. -Doði.
{47706}{47794}Eunika zna tko|može doæi do Ligije.
{47802}{47896}Je li taj èovjek stigao?
{47904}{47983}Èeka vas. Zove|se Hilon Hilonides.
{47990}{48072}Tko je on? -Mudar|èovjek. Astrolog.
{48079}{48149}Pogaða Ijudsku sudbinu|i prorièe buduænost.
{48156}{48235}I tebi je prorekao|tvoju? -Jest, gospodaru.
{48242}{48351}Što ti je prorekao?|-BoI i sreæu.
{48377}{48447}Juèer si patila . Danas|te možda snaðe sreæa .
{48456}{48579}Veæ jest, gospodaru.
{48588}{48746}Kako to? -Ostajem ovdje.
{48863}{48914}Zdravo, božanski Teriste !
{48923}{49003}Kako masnice koje ti je|pod Trojom nabio Odisej?
{49011}{49070}Najmudriji meðu|mrtvima , Odisej,
{49079}{49169}pozdravlja najmudrijeg|od živih, Petronija ,
{49179}{49271}i moli ga da mi novim|plaštem pokrije masnice.
{49283}{49338}Odgovor vrijedi plašta .
{49346}{49412}Znaš li što želimo? -U|domovima dviju obitelji
{49421}{49499}i pola Rima ne govori|se ni o èemu drugomu.
{49508}{49610}Djeva po imenu Ligija|ili Kalina nestala je.
{49623}{49720}Ja æu je pronaæi.|-Kako?
{49729}{49805}Vi imate pomagala ,|a ja imam mozak.
{49858}{49948}Umrijet æeš ako me|zarad dobitka prevariš.
{49956}{50022}Filozof sam i ne mogu|biti lakom na blago.
{50031}{50135}Osobito ne takvo|kakvo obeæaješ.
{50142}{50203}Koju školu predstavljaš?
{50213}{50295}Cinik sam jer|mi je isparan plašt.
{50304}{50363}Stoik jer prihvaæam|svoje siromaštvo.
{50373}{50443}I peripatetik jer,|nemajuæ nosiljke,
{50452}{50518}pješaèim od|krème do krème
{50527}{50586}i pouèavam one|koji æe mi platiti vrè piæa .
{50600}{50639}Tada postaješ retor?
{50650}{50724}Heraklit je|rekao: Sve teèe.
{50733}{50805}Ne možeš zanijekati da|jevino tekuæina , zar ne?
{50813}{50851}Kad poèinješ?
{50861}{50951}Veæ jesam. Tražim je i|dok razgovaram s vama .
{50961}{51037}Imaš li kakvog iskustva?.
{51048}{51128}Krepost i mudrost|danas nisu na cijeni
{51136}{51230}i filozofi tragaju za|drugim sredstvima .
{51238}{51301}Dobro. Što ti treba?.
{51311}{51370}Oružje. -Kakvo?
{51379}{51491}Takva su vremena . . .
{51502}{51645}Vi ste ispitivali, a|sad je na meni red.
{51654}{51736}Tribune, jesi li vidio|kakva èudna obilježja
{51746}{51845}ili znakove kod Ligije?
{51854}{51935}Je li crtala kave|tajne znakove?
{51942}{52053}Jednom je nacrtala|ribu. -Riba ! Riba !
{52061}{52133}Jednom ili više puta?|-Jednom. -Ribu?
{52215}{52291}Što ona znaèi? -Neka|vas Fortuna blagoslovi.
{52300}{52443}Obojicu jednako,|gospodo. -Plašt je tvoj.
{52454}{52716}Odisej ti zahvaljuje|za Tersita !
{53173}{53226}Pozdrav, Spore.
{53236}{53318}Vrè crnoga .
{53379}{53461}Spore, danas sam|radio sa Senekom
{53471}{53580}i ovo mi je|poklonio za put.
{53886}{53964}Znaš li što je ovo?
{53971}{54010}Riba .
{54019}{54093}Koja bi lako preživjela u|tvom razvodnjenom vinu.
{54102}{54137}To je simboI
{54144}{54210}ili u filozofiji -|Fortunin osmijeh.
{54219}{54287}Poštuj filozofiju|ili æu piti drugdje.
{54296}{54407}Moj prijatelj Petronije|kaže da bih i trebao.
{54490}{54607}Što je bilo? -Božanska|Augusta je umrla !
{54617}{54711}I careva djeca umiru.
{54723}{54862}Ti si kriv ! Èarobnjaštvo|je ubilo malu Augustu !
{54871}{55029}Ti si doveo zlog|duha koji ju je urekao !
{55038}{55221}Jao meni !|Jao ! Jao meni !
{55231}{55393}Spali Rim, gospodaru,|no saèuvaj nam svoj glas.
{55404}{55457}Cezare, gubitak je golem,
{55467}{55650}ali neka nam barem,|ovo blago utjehe ostane.
{55661}{55789}Ti si jedini od|svih na to pomislio.
{55796}{55905}Ti jedini,|Petronije ! Jedini !
{55913}{55980}Poði u Ancij,|mjesto njezinoga roðenja .
{55988}{56144}Tamo æeš naèi|radost i umirenje.
{56158}{56207}Da !
{56223}{56313}Napisat æu|himnu u njezinu èast.
{56321}{56420}I glazbu æu skladati.
{56465}{56501}Reci na grèkom,
{56511}{56572}Isus Krist, Božji|sin, Spasitelj.
{56581}{56599}I?
{56609}{56782}Od prvog slova svake|rijeèi napravi novu rijeè.
{56792}{57030}Ihthis?. Riba ! -Riba .
{57038}{57128}Nacrtala je ribu? -Da|je bila ptica , rekao bih.
{57140}{57224}Eto, ona je kršæanka .
{57231}{57325}Znaèi, Ligija truje|studence, kolje djecu
{57336}{57424}i predaje se|raspuštenosti? Ne. . .
{57433}{57497}Osim ako se nevaramo|što se tièe kršæana .
{57504}{57574}Govoriša kao sam Sokrat.
{57581}{57642}Prije tri godine upoznao|sam jednog lijeènika .
{57656}{57722}Z vao se Glauk,|kršæanin je
{57731}{57813}i dobar i|krepostan èovjek.
{57823}{57944}Taj ti jevrli èovjek|rekao za znak ribe?
{57952}{57980}Nažalost, ne.
{57988}{58035}Ubo je nekog|poštenjaka nožem,
{58044}{58128}a ženu mu i djecu|zarobiše trgov ci robljem.
{58138}{58220}Dva prsta sam|izgubio braneæi ih.
{58231}{58295}No meðu kršæanima|ima dosta èudesa ,
{58304}{58363}pa se nadam da|æe ponovno izrasti.
{58373}{58437}I ti si postao|kršæanin? -Od juèer.
{58446}{58493}Ali zavjetovao|sam se i Merkuru
{58502}{58601}da æu, ako mi naðe djevojku,|žrtvovati dvije krave
{58609}{58689}pozlaèenih rogova .|-Znaèi, iako si kršæanin
{58700}{58792}i filozof, ipak|vjeruješ u Merkura?.
{58800}{58853}Vjerujem u sve|što je potrebno.
{58859}{58920}Ali junice su skupe. . .
{58929}{58999}Kad bi Vinicije. . .|-Ni obola , Hilone.
{59006}{59076}Njegova æe te|darežIjivost iznenaditi,
{59086}{59195}ali tek kad|se Ligija naðe.
{59204}{59329}Dobro, gospodo.
{59690}{59776}Nije meðu kršæanima?|-Jest, gospodine.
{59783}{59869}Meðu njima je i lijeènik|Glauk. -Tko je on?
{59877}{59951}Zbog njega sam|izgubio ova dva prsta .
{59959}{60045}Ostavio sam ga na umoru|i dugo sam ga oplakivao.
{60054}{60197}Nažalost, još je živ.
{60206}{60276}Što želiš?.
{60283}{60395}Želio bih da|Glauk nestane.
{60402}{60476}Unajmi nekoga da ga|ubije. Na moj raèun.
{60483}{60600}Previše æevam naplatiti|i ucjenjivat èevas.
{60609}{60668}Koliko trebaš?|-Tisuæu sestercija .
{60675}{60825}Moram naèi poštene koji|neæe pobjeæi s kaparom.
{61069}{61135}Kršæanin je. Godine|su mi zasjenile pamæenje.
{61142}{61205}Jedan od Isusovih uèenika|izdao ga je.
{61388}{61518}Juda , gospodine, objesio|se. -Da , tako je, Juda .
{61529}{61601}Velika ti hvala .
{61602}{61686}Evo brata kojega|si želiovidjeti.
{61698}{61812}Mir Kristov bio s tobom !
{61873}{61978}Kako te zovu,|sine? Ursus.
{61988}{62068}Voliš li Krista?|-Iz srca i iz duše.
{62077}{62155}I poznato ti je imeJuda?.
{62163}{62230}Jest. Objesio se.
{62240}{62355}Mir s tobom,|vjerni slugo Jaganjèev.
{62365}{62441}Juda ima dostojnog|nasljednika meðu nama .
{62527}{62586}Oèe, tko je taj izdajica?
{62596}{62668}Sin Judin. Pravi se|kršæaninom i optužuje nas
{62679}{62753}da trujemo studence,|koljemo djecu,
{62761}{62824}ne priznajem|cezara bogom. . .
{62833}{62914}Tko æe braniti Krista|i kazniti izdajnika?
{62921}{63057}Ja bih to mogao, Oèe.
{63065}{63190}Idi meðu kršæane.|Naði Glauka i ubij ga .
{63198}{63266}Glauka? -Poznaješ ga?.
{63273}{63353}Ne, ali sutra èe apostoI|govoriti na Ostrijanu.
{63361}{63430}Ondje æu naèi Glauka .
{63438}{63514}Na Ostrijanu? -Da , oèe.
{63523}{63624}Ubiti izdajnika isto je kao|ubiti medvjeda ili vuka .
{63633}{63712}Ali što ako je Glauk|nedužan? -Slušaj. . .
{63721}{63832}Pouèavao sam o Kristovu|nauku jednu djevojku. . .
{63840}{63922}Eunika . Služi u|Petronijevoj kuæi.
{63933}{64050}Ondje sam èuo kako Glauk|želi izdati sve kršæane.
{64058}{64126}I obeæao je Viniciju. . .|-Viniciju?
{64133}{64214}. . .da æe mu naæi|djevojku. Što je?
{64223}{64393}Ništa , oèe.|Ubit æu Glauka .
{64646}{64720}Heureka !
{64727}{64793}Vidio si je? - Razgovarao|sam s Ursom.
{64800}{64853}I znaš gdje su? -Ne znam.
{64861}{64918}Ali ako je ona u Rimu,|onda je i Ligija .
{64927}{65062}I vjerojatno æe|veèeras biti u Ostrijanu.
{65069}{65182}Gdje je to? -Izmeðu|Via Salaria i Nomentana .
{65188}{65311}I evo znaka bez|kojega ne možemo uæi.
{65325}{65391}I evo skrupula .
{65398}{65476}Kad Ligija bude ovdje,|dobit æeš punu vreæu.
{65484}{65564}Jupiteru ! -Sjedni !
{65573}{65653}læi æeš sa mnom u Ostrijan.
{65677}{65787}S nama æe poæi|i gladijator Kroton.
{65796}{65849}Dobro da si me danas pozvao.
{65856}{65915}Sutra idem u Benvenet.
{65925}{66003}Borit æu se protiv|najjaèeg a frièkog crnca .
{66011}{66076}Djevojku èuva|èovjek goleme snage.
{66083}{66147}Jednom æu rukom|uhvatiti koga kažeš,
{66154}{66244}a drugom æu se boriti|protiv sedam Ligijaca
{66254}{66360}i odvesti djevu u tvoju|kuæu. -Ne dopusti mu to !
{66369}{66435}Kamenovat æe nas.
{66442}{66549}Uèini to diskretno|i izbjegni svaki rizik.
{66556}{66671}Tako æe biti, Krotone !|-Tvoji nov ci - tvoja volja .
{67375}{67512}Kristov prvi uèenik. Ribar!
{67640}{67785}Dok su tugovali,|pojavi se Marija iz Magdale
{67794}{67899}vièuæi da jevidjela Gospodina .
{67908}{67982}Ne mogavši ga|od sjaja prepoznati,
{67994}{68093}mislila je da jevrtlar,|ali on joj reèe:
{68102}{68139}Marijo !
{68148}{68298}A ona usklikne: Rabboni !|( Uèitelju ),i padne mu pred noge.
{68306}{68418}On joj naredi da to|obznani uèenicima ,
{68425}{68515}ali oni joj nevjerovaše.
{68523}{68574}A kad od sreæe zaplaka ,
{68581}{68651}jedni su je korili,
{68658}{68732}a drugi su mislili da joj je|žalost pomutila pamet
{68740}{68814}jer je govorila da je|u grobu vidjela anðele.
{68823}{69001}Uèenici otrèaše onamo|i vidješe prazan grob.
{69009}{69076}Kad je sunce zašlo,
{69086}{69157}Klepfa , koji je s drugim|uèenicima išao u Emaus,
{69167}{69241}vrati se žurno i reèe:
{69248}{69340}Zaista uskrsnu Gospodin !
{69350}{69401}Prepirali su se.
{69409}{69480}Zatvorili su vrata od|straha pred Židovima .
{69490}{69584}Uto stade on sam meðu njima .
{69594}{69758}Strah ih je obuzimao,|a on reèe: Mir vama !
{69765}{69851}I vidjeh ga , kao|što ga svi vidješe.
{69861}{70028}I bješe kao svjetlost i|kao sreæa srcima našim
{70038}{70153}jer smovjerovali da je uskrsnuo
{70161}{70293}i da æe mora presahnuti|i gore u prahu nestati,
{70302}{70480}a slava njegova neæe proæi.
{70513}{70638}Gospodine. . .Ondje. Do Ursa .
{70779}{70861}Idemo. Nismo skidali kukuljice.
{70869}{71003}Èekaj. -Vidjet æe nas. -Èekaj !
{71590}{71682}Pratit æemo ih i|vidjeti u koju kuæu ulaze.
{71690}{71795}Sutra æeš dovesti|svoje robove i odvesti je.
{71802}{71872}Ne.|-Što onda smjeraš, gospodine?
{71879}{71982}Slijedit æemo je|i ugrabiti je odmah !
{71988}{72089}Ligijac je snažan. -Reci|tom starom jarcu da šuti.
{72098}{72241}Ako je sada ugrabimo,|kamenovat æe nas.
{72831}{72910}Tako ti Jupitera , Apolona ,|Veste, Kibele, Izide,
{72919}{73051}Ozirisa i svih bogova s|istoka i zapada , nemoj !
{73059}{73187}Poslušaj me ! -Ja idem|prvi. Ti me slijedi.
{73744}{73843}Eno Ursa .
{73850}{73899}Što želite?
{73908}{73987}Ti, ubij ga !
{74213}{74272}Marko !
{74283}{74418}Puštaj me ! Urso !
{74588}{74664}Ne ubij !
{75367}{75505}Ubijte me. . .
{75575}{75628}Ubijte me. . . .
{75640}{75697}A rana na glavi?
{75704}{75776}Nije ništa . Ruku mu|je slomio preko glave.
{75784}{75864}Ali oèuvao je|glavu i spasio život.
{75873}{75945}Znam da si vješt|i zati te Ursus doveo.
{75956}{76040}A još juèer me htio ubiti.
{76050}{76101}Znam, rekao mi je,
{76111}{76178}ali objasnio sam mu|tko je pravi izdajnik.
{76565}{76622}Nisi mu dopustila da me ubije.
{76631}{76754}Bog ti vratio zdravlje.
{76927}{76997}Daj mi još piti.
{77006}{77129}Gospodin nas uèi da|volimo svoje neprijatelje.
{77138}{77237}Zalijeèili smo ti rane.|Ostavi Ligiju na miru.
{77250}{77295}Zar æete me otjerati?
{77308}{77374}Ne, mi odlazimo|u strahu od potjere.
{77386}{77474}Ne bojte se.|Ja æu vas zaštititi.
{77483}{77571}Pozovi svoju nosiljku.
{77581}{77729}Dom æe ti biti udobniji|od našeg siromaštva .
{77738}{77874}Kršæani, vaša djela|govore da ste pravedni.
{77881}{77967}Neka vaš lijeènik kaže|smijem li se micati,
{77977}{78162}jer ne odlazim osim|ako me na silu iznesete.
{78171}{78235}Mi se ne služimo silom.
{78246}{78365}Onda mi dajte da odahnem.
{78375}{78461}Kroton je danas|trebao poæi u Benevent.
{78471}{78590}Nema drugih svjedoka|osim jednog Grka . Naðite ga .
{78600}{78659}Ja æu ga ušutkati.
{78669}{78751}Javit æu kuæi da sam|otišao u Benevent.
{78761}{78837}Ako je Grk javio prefektu,
{78844}{78920}reæi æu da sam sam ubio Krotona .
{78931}{78984}Mirno ostanite ovdje.
{78994}{79101}U tom sluèaju, Glauk i|udovica æe te njegovati.
{79113}{79234}Starèe, bojiš li se da|bih pozvao svoje robove
{79242}{79336}i oteo Ligiju? -Da .
{79348}{79451}Razgovarat æu sa Hilonom i|napisati pismo pred tobom.
{79463}{79580}Nemam drugog|poslanika . Promisli sam.
{79588}{79685}A ako Ligija ode,|sam æu skinuti zavoje
{79694}{79788}i neæu ni jesti ni piti,
{79798}{79987}a moja smrt neka padne|na tebe i na tvoju braèu.
{79994}{80137}Krispe, neka ostane meðu nama :
{80146}{80236}Dok ga Krist ne ozdravi.
{80246}{80355}Neka tako bude.
{80477}{80625}Nsetko te traži.|Kaže da je hitno.
{80829}{80921}Nisam tu. . . Ne|poznajem ovog momka .
{80931}{81043}Rekla sam da spavaš.|Rekao je da te probudim.
{81052}{81171}Glupaèo ! Išibat æu te !
{81179}{81257}Hilon Hilonides!|-Pax tecum ! (Mir s tobom ). Pax!
{81265}{81405}Najboljem od kršæana .|Da , ja sam Hilon.
{81415}{81485}Posrijedi je pogreška .
{81494}{81580}Tvoj te gospodar,|Vinicije, želi vidjeti.
{81590}{81738}A zar mi dragi|prijatelj nosiljku nije poslao?
{81748}{81807}Hodat æemo. -A ako odbijem?
{81815}{81862}Ja to ne bih uèinio.
{81871}{81926}Poæi æu s tobom jer to želim.
{81936}{82014}Slobodan sam i mudar èovjek.
{82025}{82097}One koji me uvrijede|mogu pretvoriti u stabla
{82111}{82220}ili životinje. Idemo !
{82792}{82893}Zašto si se|oglušio na moje savjete?
{82902}{82994}Šuti i slušaj !
{83004}{83112}Kroton me htio|ubiti i opljaèkati.
{83121}{83226}Ubio sam ga , a oni|su zalijeèili moje rane.
{83236}{83337}Bio je zao. -Sreæom|sam imao svoj nož.
{83346}{83432}Rekao sam ti da uzmeš oružje.
{83440}{83507}Što si ti uèinio? -Molio|sam se za tvoje zdravlje.
{83517}{83634}I? -Mislio sam doæi,|ali on me našao.
{83642}{83705}Odnesi ovo u moj dom.
{83715}{83826}Napisao sam da sam|otišao u Benevent. Jasno?
{83865}{83959}Otišao sam u Benevent.|-Jesi. . .
{83971}{84061}Da . Oprostili smo se|kod Porte Kapsene.
{84071}{84120}Od tada žalim
{84129}{84228}i riskiram da|od tuge i umrem.
{84238}{84405}Napisat æu da ti|moje sluge osuše suze.
{84423}{84476}Daj mi žižak.
{84579}{84710}Ne prepoznaješ|li me, Cefase?
{84719}{84847}Nisam ja . . .|To nisam. . . Glauk?
{84856}{84930}On je osudio i|pogubio moju ženu
{84940}{84993}i moju obitelj.
{85002}{85125}On je htio da ubijem|Glauka . -Gospodine !
{85138}{85299}Pomozi mi ! Moli za mene.
{85400}{85474}Pismo ! Odnijet æu|pismo, gospodine !
{85483}{85606}Zakopaj ga u vrtu. Pismo|æe odnijeti netko drugi.
{85615}{85716}Za ime Božje,|ja sam kršæanin !
{85725}{85868}Možeš me još|jednom krstiti ! Glauko !
{85877}{86064}Uèini me robom, ali|spasi me, preklinjem te !
{86073}{86151}A spasitelj nam reèe:
{86161}{86255}Ako ti brat|tvoj sagriješi,
{86263}{86428}prekori ga , a ako se|pokaje, oprosti mu.
{86438}{86489}Hilone. . .
{86500}{86576}neka ti Bog oprosti
{86586}{86720}kako ti u Kristovo|ime i ja praštam.
{86727}{86828}Neka spasitelj bude|milosrdan kao i ja .
{86858}{86915}Idi u miru.
{87088}{87195}Pismo, gospodine, pismo !
{87208}{87292}Predat æu ga .
{87690}{87860}Ovo je tvoja najveæa|pobjeda do sada .
{87954}{88038}Mir s tobom !
{88506}{88590}I ti si meni oprostila?.
{88600}{88732}Ne smijemo gajiti|mržnju u srcu.
{88963}{89128}U snu sam ti vidio dušu.
{89334}{89420}Robe !
{89446}{89555}Dobar dan i dobro|zdravlje, ali nisam rob.
{89563}{89684}Dragovoljno služim|Kalini. -Gdje je ona?.
{89694}{89797}Upravo je otišla .|Cuvala te svu noæ.
{89806}{89910}Zašto je nisi zamijenio?|-Jer nije htjela .
{89921}{89982}I upravo te ona spasila .
{89990}{90062}Zar ti je žao|što me nisi ubio?
{90071}{90147}Nije, Krist nam|zabranjuje ubijati.
{90156}{90215}A Kroton?
{90225}{90350}Zapovjedio si da digne|ruku na kraljevsku k æer.
{90358}{90483}Èekaj, pomoæi æu ti.
{90523}{90669}Pij. -Božice moja .
{90890}{91011}Htio sam doæi do tebe|na pokvaren naèin.
{91021}{91089}Vrati se|Pomoniji Grecini.
{91098}{91213}Nitko teviše|neæe napadati.
{91223}{91313}Da je barem mogu vidjeti !|Makar izdaleka .
{91321}{91372}No, ne mogu sevratiti.
{91381}{91491}Neron mrzi njezinu|obitelj. -Da . Znam.
{91498}{91619}Ali da te meni prvo dao. . .
{91627}{91730}Želiš me ponovno|vidjeti na Palatinu?
{91738}{91835}Ne, imaš pravo,|gluposti govorim.
{91844}{91978}Mnogo si|sretnija od mene.
{91984}{92070}Imaš svoju|vjeru i Krista .
{92079}{92143}Ja imam samo tebe.
{92152}{92220}Bez tebe bih bio|poput prosjaka .
{92229}{92343}Razgovaraš samnom, no|misliš na Njega , zar ne?
{92354}{92614}Misli i na mene,|jer æu ga inaèe mrziti.
{92623}{92682}Ti si moje božanstvo.
{92694}{92782}Želim se tebi moliti|i štovati te.
{92792}{92874}Ti ne znaš|i ne možeš znati
{92883}{93049}kako te ja Ijubim. . .
{93194}{93337}Ti si izvor mog života .
{93348}{93434}Moja jedina . . .
{93446}{93557}Ligijo. . . Ligijo. . .
{93688}{93803}Odlazi prije nego što te|zao duh pokosi !
{93813}{93899}Gospodin je i radi tvoje|duše umro na križu,
{93906}{94039}a ti želiš èovjeka koji|te hoæe za konkubinu.
{94048}{94183}Tko je on? Sluga|i saveznik Sotonin !
{94192}{94357}Njegovo sredstvo|u pohoti i zloèinu.
{94438}{94543}Pomozi mi, oèe,|preklinjem te !
{94552}{94710}Nevjerujem samoj sebi|i ne mogu protiv Ijubavi !
{94719}{94840}Krispo, zar misliš|da bi se Krist,
{94850}{94955}koji je dopustio Mariji|da mu leži pod nogama
{94963}{95162}i oprostio joj, odvratio|od ove djevojke?
{95171}{95235}Griješio sam protiv|Božjeg milosrða ,
{95242}{95351}ali prihvaèanjem|zemaljske Ijubavi
{95359}{95509}odrekla se Krista . -Ja|sam to tri puta uèinio.
{95519}{95595}A ipak mi je oprostio.
{95602}{95649}Ja sam Pavao iz Tarsa .
{95659}{95739}Ja sam gonio i zatvarao|sljedbenike Isusove.
{95748}{95812}Kad su Stjepana ubijali,
{95821}{95893}ja sam èuvao halje onih|koji su ga kamenovali.
{95902}{95978}Htio sam istrijebiti|istinu po svoj zemlji,
{95988}{96074}ali Gospodin je htio da je|po svoj zemlji nauèavam.
{96083}{96202}Dok tvoj Ijubljeni|ne ugleda Svjetlosti,
{96211}{96307}pokušaj ga izbjegavati|da te ne odvede u grijeh.
{96317}{96603}Ali znaj, nema nièega|lošega u tome da ga voliš.
{96675}{96755}Ne znam èak ni|gdje je ona sada .
{96763}{96833}Otišla je|dok te nije bilo.
{96846}{96961}Krispo ju je sakrio.|Nevjeruje mi.
{96969}{97074}Ne, to je bila|Ligijina odluka .
{97081}{97155}A što se tièe Krispa ,|Petar ga je izgrdio
{97163}{97288}zato što ju je osudio|što se zaljubila u tebe.
{97296}{97360}Ona je rekla|apostolu da mevoli?
{97371}{97499}Ruka ti je ozdravila .
{97508}{97641}Nemoj je naprezati.
{97950}{98018}Pozdrav, božanska !|Pozdrav, Krizotemido !
{98029}{98099}Sam si.|Istinski znak dosade.
{98106}{98221}Doði, odvest|æu te na gozbu.
{98596}{98710}Zaveo si mi Krizotemidu.
{98719}{98816}Dvostruko ti hvala .|Odbio si Euniku
{98825}{98950}i oslobodio si|me Krizotemide.
{99165}{99264}U daljini sam tražio|nešto što mi je blizu.
{99273}{99385}Što su mrzovoljni kršæani|u usporedbi s ovim?
{99394}{99447}Nekoæ sam volio|miris vervena ,
{99458}{99568}ali sad volim|Ijubice, kao i Eunika .
{99575}{99714}Ljepotice moja , neka|pripremevijence i vino.
{99911}{99997}Ne, Ligija nije Eunika .
{100006}{100108}Ljubav ti je promijenila|njuh, a meni dušu.
{100117}{100189}Neka Had|proguta tvoje kršæane !
{100198}{100323}Uništili su ti smisao|života . U Had s njima !
{100333}{100392}Oni te neæe|nauèiti nièemu.
{100404}{100472}Ljubav, Ijepota|i moæ daju sreæu,
{100483}{100582}a za njih je to|taština . Nisu pravedni !
{100592}{100691}Ako æemo zlo|plaèati dobrim,
{100702}{100755}èime æemo plaèati dobro?
{100765}{100824}Nagradit æe se u|životu poslije smrti.
{100833}{100947}Vidjet æemo. Ako mrtvo|tijelo išta moževidjeti.
{100958}{101032}Planiraš oteti|Ligiju? -Ne.
{101040}{101159}Ne mogu je povrijediti.|-Prihvatit æeš Kristov nauk?
{101169}{101301}Želim to, ali narav|mi ga ne podnosi.
{101344}{101451}A hoæeš li moæi|zaboraviti Ligiju?
{101461}{101530}Neæu.
{101579}{101718}Doði i popij malovina .|Eunika je nestrpljiva .
{101758}{101817}Odgodit æemo|put u Egipat.
{101827}{101941}Prema proroèanstvu,|ionako æu vladati njime.
{101950}{101991}Dignut æemo spomenike
{102000}{102082}uz koje æe piramide|biti malene.
{102092}{102178}Moja æe Sfinga|biti sedam puta veæa .
{102188}{102266}I imat æe moj lik.
{102275}{102339}Svojim pjevanjem veæ si|sagradio sebi spomenik.
{102348}{102412}Žalim što æeš|odgoditi putovanje.
{102421}{102536}Bogovi to žele od mene.
{102548}{102694}Sama mi je Vesta|šapnula : Nemoj iæi.
{102704}{102839}Zašto se bojimo Veste|više od drugih bogova?.
{102848}{102930}Od straha sam pao i|bio bih tresnuo o pod
{102940}{103076}da me nitko nije|pridržao. Tko? -Ja .
{103090}{103172}Ti? Hvala .
{103181}{103291}Kako je ona djevojka|preuskih bedara?
{103300}{103376}Kladim se da ju|jeveæ zaboravio.
{103386}{103449}Muèi me dosada .
{103458}{103535}Ostao sam u Rimu,|a ne podnosim ga .
{103544}{103614}Otiæi æu u Ancij. Ove|me prljave ulice guše.
{103625}{103719}Kad bi neki gnjevni bog|sravnio Rim sa zemljom,
{103729}{103843}izgradio bih vam mnogo|velièanstveniji grad.
{103850}{103938}Kad bi ga neki gnjevni|bog sravnio sa zemljom?
{103952}{104112}Da . Zašto?|-Zar ti nisi bog?
{104175}{104249}Odlazim u Ancij.
{104256}{104357}Vi, maleni Ijudi, ne|razumijete moje potrebe.
{104365}{104466}A ti æeš poæi sa mnom.
{104477}{104532}Tigelin, Vatinije,|Sekst, Akvilin. . .
{104544}{104689}Kakavološ! Oni æevladati|svijetom? Ja ne idem.
{104696}{104770}Nisam odgovoran|za ono što se dogaða .
{104777}{104822}Ali otiði.
{104831}{104913}Dovest æeš i sebe|i Ligiju u opasnost.
{104923}{104991}Moram jevidjeti. -Gdje je?
{104998}{105115}Ne znam. -Znaèi da|je razboritija od tebe?
{105125}{105201}Ne želi tvoju propast.
{105213}{105326}Neka ti bogovi daju|moæ i besmrtnost.
{105333}{105433}Što hoæeš?. -Znam|gdje se Ligija nalazi.
{105440}{105530}Gdje je? -Kod Lina . Sveæenik je.
{105540}{105645}Ursus radi noæu.|Žene su po noæi same.
{105652}{105691}Kako znaš?
{105700}{105810}Kršæani su me poštedjeli,|pa sam pun zahvalnosti.
{105817}{105911}Zabrinjava me njihova|sudbina , no prije svega
{105919}{105976}mislio sam o tebi.
{105986}{106064}Princeza još|veèeras može biti tu.
{106073}{106225}Nadam se da æeš me|nagraditi, gospodaru.
{106304}{106370}Neæu te poslušati.
{106377}{106483}No bez nagrade neæeš otiæi.
{106490}{106601}Trista šiba ! -Zašto?|O, kralju perzijski !
{106609}{106712}Zašto, kolose milosrða?|Tako si nepravedan.
{106721}{106867}Kao ti s kršæanima . Tristo šiba !
{106877}{106947}Pedeset! Ne tristo ! Ne !
{106956}{107037}Pedeset! Sto možda ,|ali ne tristo !
{107046}{107147}Imaj samilosti, za ime Kristovo !
{107369}{107432}Onesvijestio se.
{107438}{107503}Dovedi ga .
{107744}{107805}Gospodine. . .
{107813}{107941}Velikodušan si i moæan.
{107952}{108100}Praštam ti u ime Krista ,|kojemu život dugujem.
{108109}{108285}Tada æu služiti i njemu i tebi.
{108496}{108580}To je kuæa . Iza zidina .
{108640}{108730}Dobro. Sad zaboravi|da si mi ikada služio.
{108736}{108799}Zaboravi Mirjam, Petra i Glauka .
{108806}{108880}Zaboravi da kršæani postoje.
{108890}{108928}Jednom na mjesec
{108936}{109024}moj æe ti osloboðenik|isplaèivati dva zlatnika .
{109033}{109094}Ako se i dalje|usudiš uhoditi kršæane,
{109106}{109136}išibat æu te do smrti.
{109146}{109197}Zaboravit æu !
{109208}{109314}Tako mi Ante i furija , neæu !
{109402}{109580}Pozdravljam vas u ime|Krista , kojega štujete.
{109581}{109758}Pozdravljam vas u ime|Krista , kojega štujete.
{109765}{109849}Neka mu je|ime zauvijek slavljeno !
{109879}{109978}Poslušajte me, Petre i Pavle,
{109988}{110037}znam da je Ligija ovdje.
{110048}{110182}Lako bih je mogao oteti,|ali neæu.
{110192}{110309}Bog te blagoslovio zbog toga .
{110319}{110467}Došao sam k vama kao|Ligijinim roditeljima .
{110475}{110607}Dajte mi je za ženu.
{110613}{110747}Moæi æe štovati Krista .
{110756}{110830}Volim je kao oèi svoje.
{110840}{110934}Nisam ni vaš ni|Kristov neprijatelj.
{110944}{111057}Kad mislim da je|èista kao snijeg na gori,
{111067}{111197}onda jevolim još i više.
{111206}{111329}Vaš ju je nauk takvom|uèinio. Volim taj nauk.
{111340}{111453}lako ga ne razumijem.
{111461}{111541}Vidite da sam iskren.
{111552}{111616}Grèka je stvorila|mudrost i Ijepotu.
{111625}{111728}Rim moæ, a štovi donosite?
{111736}{111812}Ljubav.
{111821}{111887}Tko kuca , otvorit æe mu se.
{111896}{112066}Blagoslivljam tebe,|tvoju dušu i tvoju Ijubav.
{112486}{112630}Ligijo, voliš li ga?
{112740}{112837}Volim.
{113084}{113207}Volite jedno drugo.
{113219}{113313}U vašoj Ijubavi nema grijeha .
{113323}{113464}Nisam pobjegla od|tebe. -Zašto onda?
{113473}{113557}Dobro ti znaš.
{113567}{113624}Pošalji Ursa k Aulu.
{113636}{113766}Neka donese|tvoje stvari u moj dom.
{113775}{113830}To u nas nije obièaj.
{113840}{113974}Nije ni u Rimu.
{113981}{114108}Ali uèini to za mene.|Odnijet æu ih kuæi.
{114117}{114220}Podsjeæat æe me na tebe.
{114229}{114321}Dok mi ne postaneš ženom.
{114331}{114388}I reæi æu,
{114400}{114512}Gdje si ti Gaj,|ondje sam i ja Gaja .
{114733}{114784}Grašak s uljem|i rubac nisu pomogli.
{114794}{114882}Riðobradi je promukao.
{114892}{115011}Proklinje Rim i njegov|zrak. Selimo se u Ancij.
{115019}{115080}A kako je majmun promukao?
{115088}{115216}Glumio je Ledu,|oznojio se i ozebao.
{115250}{115357}Nitko neæe plakati !|O, Ijudi, vatra !
{115365}{115455}lako kuæe tinjaju,|pucaju i urlaju,
{115465}{115541}a iskre ukrašavaju crne|zidove, tko æe povikati?
{115550}{115636}Krvava tijela onih|koji su tu živjeli?
{115644}{115703}Grad je uništen,|a pohlepni plamen
{115713}{115814}još liže te zidine.
{115821}{115882}Tvoja Ijepota ,|Trojo, izgubljena je.
{115894}{115976}Kraj je blizu !
{115988}{116047}Koraci, jauci. . .Tišina !
{116056}{116117}Troja je sada golema buktinja .
{116129}{116248}Žrtvena vatra , planula pustinja .
{116313}{116382}Loši stihovi.
{116392}{116445}Što je loše u njima?.
{116456}{116573}Bit æu iskren. Dobri su|za Vergilija ili Ovidija ,
{116583}{116647}èak i za Homera ,
{116656}{116758}ali za tebe ne ! Tvoj|požar ne žari dovoljno.
{116767}{116866}Tvoja vatra ne žeže.|Ne slušaj njihova laskanja .
{116875}{116994}Možeš stvoriti djelo za|koje svijet još nije èuo.
{117004}{117139}Ponovit æu. Napiši bolje !
{117148}{117253}Bogovi su mi dali malo talenta ,
{117259}{117399}ali i prijatelja koji|znade reæi istinu u oèi.
{117408}{117489}Bacit æu ih. . . ! -Ne ! Ne.
{117498}{117549}lloši pripadaju èovjeèanstvu.
{117558}{117718}Onda æeš ih tidobiti.|U kutiji po mom ukusu.
{117729}{117891}Moj požar u Troji|ne plamti dovoljno.
{117921}{118036}Otvorio si mi oèi.|Znaš li razlog tomu?
{118044}{118165}Kad kipar stvara|lik boga , traži uzor.
{118173}{118245}Ja nikada nisam|vidio grad u plamenu.
{118254}{118389}Spalit æu Ancij, ako želiš.
{118396}{118460}lli, ako ga želiš poštedjeti,
{118469}{118539}sagradit æu ti drveni|grad, a ti ga spali.
{118550}{118687}Drvenjare?
{118696}{118762}Zar ti je pamet|ishlapila , Tigeline?
{118771}{118916}Ne cijeniš moj|talent i moje Troike.
{118967}{119132}Zamislite kako|sada smrdi u Rimu.
{119167}{119233}Neron ti neæe zamjeriti|što si otišao iz Ancija
{119244}{119385}bez dopuštenja?.|-Neæe. Pisat æe poeziju.
{119392}{119449}A ja nisam|mogao biti bez tebe.
{119461}{119582}Znala sam da æeš doæi.
{119592}{119703}Gledam te.|Buljim u tvoju sjenu,
{119713}{119869}koja je posudila|Ijepotu tvoga tijela .
{119879}{119994}Težine nema . Kao da|je stvorena od pjene.
{120004}{120220}Kamo god hodaš|leptiri i cvijeæe. . .
{120338}{120499}Ne mogu biti na miru.|Petronije, Vincije. . . .
{120508}{120582}lako mi je duša tužna ,
{120590}{120682}osjeæam da bih mogao|pjevati tu pjesmu javno.
{120692}{120857}Možeš je pjevati ovdje,|u Rimu, i u Ahaji.
{120884}{120937}Kad sviram i pjevam,
{120948}{121018}otkrivam èari koje ne|znam i ne razumijem.
{121027}{121160}Osjeæam ih, i iako|sam moæan i božanski,
{121169}{121278}osjeæam se|nevažan poput prašine.
{121286}{121368}Jedinoveliki umjetnici|mogu biti tako skromni.
{121379}{121465}Znam što pišu|po zidovima u Rimu.
{121475}{121557}Ubojica majke. Okrutnik.
{121567}{121622}Za njih sam èudovište.
{121631}{121690}Zar sam doista takav tiranin?
{121700}{121823}Okrutna djela ne èine|èovjeka okrutnikom.
{121834}{121928}Trebali bi te poznavati|kao ja . -Kruže glasine
{121938}{122086}da Diodor i Terpnos bolje|od mene udaraju u citaru.
{122094}{122155}Budi iskren, je li to istina?.
{122163}{122274}U tebi sevidi umjetnik.|Oni su tek vješti.
{122284}{122389}Neka žive onda !|Uèinio si im veliku uslugu.
{122396}{122480}Ja sam umjetnik u|svemu èega se primim.
{122488}{122562}Znam, kažu da sam lud.|Ja samo tražim.
{122571}{122676}Kad je to uzaludno,|poludim, ali samo tražim.
{122698}{122801}Zato sam i dao|ubiti majku i ženu.
{122809}{122876}Nadao sam se da æe mi|takva žrtva otvoriti vrata
{122884}{122983}k neèemu nezamislivom,|neobiènom i velikom.
{122992}{123089}No nije bilo dovoljno za|otvaranjevrata spoznaje.
{123098}{123223}Što kaniš uèiniti?|-Postoje dva Nerona .
{123233}{123315}Jedan kakvog svi poznaju,|a drugi je umjetnik.
{123323}{123391}Njega poznaješ samo ti.
{123400}{123535}Teško je nositi breme|najveæevlasti i talenta .
{123542}{123645}Žalim te, cezare, svim|srcem, kao i Vincije,
{123652}{123711}koji te u duši obožava .
{123721}{123822}No on služi Marsu, a ne muzama .
{123831}{123912}Zaljubljen je. Dopusti|da ode, jer æe svisnuti.
{123923}{124022}Ona ligijska taokinja|pronaðena je.
{124033}{124160}Zaljubio se u njezinu krepost.|Zeli se njome oženiti.
{124169}{124218}Uzdiše, vene. . .
{124227}{124324}Lijepa je,ali preuska u bedrima .
{124333}{124399}Voliš li je kao što on to tvrdi?
{124408}{124436}Da .
{124446}{124560}Idi onda , oženi se i|vrati se s prstenom.
{124569}{124697}Hvala .|-Lijepo je usreæivati Ijude.
{124708}{124841}Ne bih htio ništa drugo|èiniti do kraja života .
{124892}{124964}Božanski imperatore,|oprosti, u Rimu je požar!
{124975}{125120}Bogovi. . Dovršit æu svoju Troiku.
{125127}{125184}Hoæu li uspjeti vidjeti|grad u plamenu?
{125196}{125280}Grad guta more plamena ,|smrti i ludila .
{125292}{125374}Rim nestaje !
{125386}{125460}Jao meni bijednomu !
{125496}{125632}Jao tebi, sveti Prijamov grade.
{126313}{126412}Dajte mi svježeg konja !
{126500}{126590}Koji dio gori? -Poèelo|je kod Velikog cirkusa .
{126606}{126708}Vatra je dosad došla do|središta . -A Zatiberje?
{126723}{126801}Nije još, ali vatra se širi.
{126811}{126880}Ljudi umiru !
