{355}{446}MORAL
{459}{500}Znaš li što je moral?
{545}{586}Reæi æu ti.
{604}{711}Moral je za ljude|koji imaju, za bogate.
{733}{801}A tko je uvijek u pravu?
{832}{916}Bogati. A siromašni su sjebani.
{943}{1010}PRAVDA
{1028}{1092}Da ti pokažem svoj moral?
{1159}{1229}Neæeš li požaliti?|- Ne baš.
{1235}{1330}Mislim da se bojiš.|Ovo je moj moral.
{1341}{1386}To je moral.
{1399}{1464}Znaš li zašto imam ovo?
{1527}{1655}Jer g. Moral u svojoj uniformi...
{1673}{1771}uvijek pobjeðuje...
{1777}{1838}njega i njegov vražji moral.
{1844}{1943}A ja...|Ovo je moja pravda.
{2014}{2067}Ili si u pravu...
{2109}{2156}...ili u krivu...
{2162}{2227}nije važno, èovjeèe.
{2396}{2455}Les Cinemas de la Zone predstavlja:
{2461}{2559}dramu o mesaru samom|u raljama svoje zemlje.
{2626}{2746}Njegov život, njegov moral.|Kada bih sažeo svoj život...
{2752}{2868}Moj život je život gubitnika.|Trebali bi to zapisati.
{2874}{2932}Prièa o èovjeku|kao toliko njih prije.
{2938}{3023}Sve je poèelo u Francuskoj,|zemlji sira i izdajica.
{3029}{3086}Èovjek je roðen u blizini |Pariza, 1939.
{3092}{3179}1941. majka ga je napustila.|Nikada je više nije vidio.
{3185}{3251}Na dan osloboðenja, djeèak|saznaje tko mu je otac.
{3256}{3320}Komunist koje je umro|u jednom od koncentracijskih logora.
{3327}{3401}Šest mu je godina sada.|Poèinje njegova mentalna borba.
{3406}{3502}Nevinost mu je ukradena|u ime Isusa kako je odgajan.
{3509}{3604}Da bi bio sposoban preživjeti, djeèak|postaje mesar u svojoj 14 godini.
{3610}{3668}Sljedeæih 10 godina radi|za razne ljude...
{3674}{3756}...štedeæi svaki cent|za vlastiti posao.
{3761}{3859}Koji poèinje u 30-oj.|Teško je u poèetku...
{3865}{3925}...ali nakon dvije godine|duæan dobro posluje.
{3931}{4006}Živi od toga.|Upoznaje mladu tvornièku radnicu...
{4013}{4111}...i uzima joj nevinost u|l'Avenir hotelu preko puta tvornice.
{4117}{4163}Od tada sve ide brzo.
{4169}{4281}Devet mjeseci kasnije postaje otac|Cynthie, bebe neželjene od njezine majke.
{4287}{4373}Ponovno je napušten i ostavljen|da sam podigne svoju kæer.
{4379}{4441}Godine prolaze.|S duæanom ide dobro.
{4447}{4568}Mesar kupuje stan|gdje mu kæer odrasta nijema.
{4574}{4625}Poèinje njena adolescencija.|Postaje žena.
{4631}{4723}Otac, još uvijek samac,|mora obuzdavati svoju strast.
{4729}{4814}Tada sudbina pokuca na vrata.|Djevojèica dobije svoju prvu menstruaciju.
{4820}{4892}U neviðenoj boli|trèi u trgovinu.
{4898}{4966}Na putu tamo, radnik je pokuša|zavesti.
{4972}{5023}Susjed to vidi|i odvede je njenom ocu.
{5029}{5123}Otac ugleda krv na njezinoj suknji|i pomisli da je silovana.
{5129}{5191}Uzima nož|i odlazi u potragu za silovateljem.
{5197}{5236}Ugleda radnika na doku.
{5242}{5316}Mesar zareže èovjeka po|licu nožem.
{5322}{5434}Mesar završava u zatvoru zbog toga.|Djevojèica je predana instituciji.
{5440}{5490}Otac povremeno piše|svojoj kæeri. Mjeseci prolaze.
{5496}{5579}Mesar moja prodati stan|i mesnicu.
{5585}{5649}Kada konaèno bude slobodan,|nema više ništa od svoje imovine.
{5654}{5720}Da bi preživio,|postaje konobar.
{5726}{5833}Uskoro postaje ljubavnik svoje šefice. |Ona zatrudni i želi prodati kafiæ...
{5839}{5884}...da bi poèela novi život|u nekom drugom gradu.
{5890}{5975}Èak ima dovoljno novca|da iznajmi mesarnicu.
{5981}{6019}Èovjek nema izbora.
{6025}{6091}Po prvi put odlazi u posjet|svojoj kæeri.
{6097}{6164}Pozdravlja je.|Ona ga vidi kako odlazi, ali ništa ne govori.
{6170}{6247}Sljedeæi dan èovjek odlazi iz|Pariza sa svojom ženom...
{6253}{6345}...nadajuæi se bijegu iz mraènog |tunela svog života.
{6351}{6411}U Lilleu žive neko vrijeme|sa ženinom majkom...
{6417}{6459}...dok ne naðu vlastitu kuæu i duæan.
{6466}{6595}U usporedbi s Parizom, ulice|na sjeveru èine se napušteno i sivo.
{6602}{6663}Po prvi puta, èovjek se osjeæa|kao stranac.
{6669}{6766}Priviða mu se mrtvi otac.
{6772}{6867}Ali mesar je, poput svih drugih,|biæe koje želi preživjeti.
{6872}{6961}Odluèuje zaboravititi na svoju |prošlost i izdaju svoje kæeri.
{6968}{7061}Kao i na svoju ljubav prema njoj.|Ali ljubav je previše snažna.
{7067}{7161}Ne može puno ljudi reæi|da su istinski upoznali ljubav.
{7200}{7279}Taj èovjek sam ja.|To je bio moj život, do sada.
{7284}{7391}Ali danas poèinje moj novi život.|Poèinjem ponovno.
{7397}{7511}Da, dame i gospodo.|Danas brišem svoju prošlost.
{7533}{7634}Predgraðe Lillea, sjeverna Francuska,|3. sijeèanj, 1980.
{8285}{8372}Laku noæ, djeco.|- Laku noæ, mamice.
{8436}{8483}Oprostite.
{8824}{8888}Na toj je strani moj otac|obièavao spavati.
{9191}{9238}Nije li ti veæ dovoljno toplo?
{9244}{9293}Bolje joj je da miruje.|Ona i njezino dijete.
{9299}{9438}Ako nastavi navaljivati ovako,|raznijet æu joj glavu. I to ne samo njezinu glavu.
{9569}{9634}Hoæemo li pogledati|duæan sutra?
{9757}{9788}Da.
{10318}{10370}Da, sviða mi se.
{10400}{10453}Ali malo je preskup.
{10512}{10590}Transakcija bi trebala biti|10 posto jeftinija.
{10608}{10650}Kao i najamnina.
{10663}{10694}Na vaš raèun?
{10700}{10762}Ne. Na moj.
{10982}{11025}Bilo je to loše mjesto.
{11031}{11093}Radije bih zadržala novac|dok ne rodim.
{11099}{11176}Nismo se tako dogovorili.|Što æemo do tada?
{11182}{11253}Naæi æeš privremeni posao.|Hajde.
{11276}{11311}Hvala.
{11403}{11437}''Traži se: mesar za svinjetinu''
{11443}{11503}Gledaj. Traže mesara.
{11536}{11587}Ja nisam mesar za svinjetinu.
{11665}{11727}Bilo bi jednostavnije nego voditi |duæan.
{11777}{11817}Da, u pravu si.
{11859}{11899}Što to radiš?
{11905}{12034}Nije mi do toga. Radi se o mom novcu.|Ja sam trudna i možeš odmah zaèepiti.
{12086}{12126}Toèno.
{12238}{12369}Vražja kobasica. Vražje vino.|Vražja obitelj u dosadnom gradu.
{12384}{12450}Sve bi to trebalo biti jako dobro.|Novi duæan.
{12456}{12505}Dobar novi život.
{12516}{12564}Ali koliko su prljavi...
{12570}{12679}...ne bih se iznenadio|da im svrati inspekcija.
{12695}{12744}To se dogaða kad ostariš.
{12750}{12838}Izgubiš smisao za miris i izgled,|i postaneš prljav.
{12860}{12929}Ali debela krava|nema ispriku.
{12971}{13043}A tvoji roditelji, jesu li još živi?
{13054}{13119}Rekla sam ti da je siroèe.
{13126}{13172}O, žao mi je.
{13513}{13571}Trebao bi se smješkati.
{13590}{13635}Kužiš?
{13674}{13747}Da privuèeš kupce.
{13787}{13885}U duæanu smo,|sa glazbom i svim ostalim.
{13894}{13985}Svi bi se trebali osjeæati ugodno.|Kužiš?
{14010}{14060}Samo se smješkaj za mene.
{14135}{14194}Potrudi se malo. Nasmiješi se.
{14310}{14404}Zaboravi. Briši.
{14413}{14457}Hajde.
{14463}{14500}Budala.
{14551}{14632}Dolaziti ovdje moleæi za posao.
{14684}{14787}Što? Mogao si biti mesar za svinjetinu!
{14819}{14879}Što si mislio? Da možeš|sjediti ispred TV-a zauvijek?
{14885}{15002}Da ti nisi tako škrta, veæ|bi imali vlastiti duæan.
{15007}{15060}Zato zaèepi.
{15232}{15304}Da bi pobijedili u Roubaixu, |morate biti u formi.
{15310}{15443}I morate znati gdje|voziti.
{15449}{15528}Ne smijete iæi za|nepoznatom skupinom.
{15579}{15688}Tu je. Moj zet.|Doktor Choukroune.
{15713}{15759}Baš smo prièali|o tvojim problemima.
{15765}{15882}Traže noænog èuvara |u staraèkom domu, gdje radi.
{15910}{15978}Vaša punica mi je sve|objasnila.
{15984}{16044}Ako vam ovo ne može pomoæi...
{16160}{16244}Dat æu vam broj i adresu|doma...
{16251}{16325}...pa im se možete javiti.
{16335}{16396}Doviðenja, gospodine.
{16593}{16704}Toèno, ljigavica misli da sam|èuvar u staraèkom domu.
{16710}{16786}Da joj i guzicu obrišem|kad sam veæ na njoj?
{16806}{16923}U drugu ruku... Ako radim noæu,|neæu morati gledati njihove ružne njuške.
{16944}{17041}Jeste li prije radili u noænoj smjeni?|- Ne baš.
{17047}{17155}Možda se èiniti lagano, ali nakon|nekog vremena vas može izludjeti.
{17379}{17454}Jeste li radili u domu ikad prije?
{17460}{17499}Iznosio sam smeæe.
{17505}{17557}Baš i nije zabavno.
{17656}{17739}Èudno je, znate, mislite da æe|sve za njih uskoro biti gotovo...
{17745}{17835}...ali stvari koje se|dogaðaju iza tih vrata...
{17848}{17931}Pa, vidjet æete.
{18128}{18182}Ovo je vaš ured.
{18375}{18418}Radim ovdje veæ 2 tjedna.
{18424}{18521}Nisam se osjeæao ovako dobro|otkad sam izašao iz zatvora.
{18527}{18657}Ovo mjesto nije gore od zatvora.|Baš suprotno. Osim smrada.
{18681}{18756}Starci užasno smrde.
{18762}{18804}- Staraèki dom Debussy,|18. travanj, 1980., 4.00 -
{18810}{18924}Ne podnosim te dvije stare |vreæe u njihovom stanu.
{18941}{19010}Ne bi smjele misliti|da sam slabiæ.
{19016}{19082}Ali, stara krava je bogata...
{19088}{19185}...i misli da zbog toga |može raditi što god hoæe.
{19191}{19260}Tako je to.|Svi se bore za svoj novac...
{19266}{19342}...i svoj duæan.|I nitko to neæe napraviti umjesto vas.
{19434}{19510}Jeste li bili kod doktora?|- Ne.
{19516}{19624}Žena se guši.|Možete li mi pomoæi? Brzo.
{19636}{19685}Da, ne znam...
{20036}{20075}Brzo.
{20096}{20146}Držite joj ruku.
{21573}{21610}Tatice...
{21684}{21826}Ne ostavljaj me samu.
{22072}{22175}Sve je tako crno.
{22737}{22851}Smrt ne otvara vrata.
{22896}{22956}Na kraju krajeva, smrt|nije ništa naroèito.
{22973}{23028}Svi dižu puno strke oko toga
{23034}{23114}Ali, kada malo bolje razmisliš,|to nije ništa posebno.
{23120}{23189}Beživotno tijelo, to je sve.
{23246}{23292}Ljudi su kao i životinje.
{23298}{23377}Voliš ih,|pokopaš ih, to je to.
{23394}{23482}Ipak, ovo je|prvi put da to vidim.
{23488}{23545}Oèigledno je i njoj prvi put.
{23551}{23638}Izgleda vrlo oèajno.
{23692}{23774}A to je tako jebeno dosadno.
{23832}{23898}OK, otpratit æu je doma.
{23934}{24040}Izgleda vrlo krhko.|I prilièno je slatka, takoðer.
{24120}{24182}Otpratit æu te kuæi.
{24338}{24400}Podsjeæa me na moju kæer.
{24427}{24464}Moju Cynthiju.
{24470}{24539}Sigurno je vrlo usamljena,|gdje god bila sada.
{24584}{24624}Doði.
{24718}{24782}Ali usamljenost ništa ne znaèi.
{24813}{24912}Možeš živjeti sa tipom, ili curom,|ili èak sa djecom...
{24924}{24979}...a biti sam.
{24987}{25067}I ja sam.|A i ona je.
{25101}{25202}Roðeni smo sami,|živimo svoje živote sami, umiremo sami.
{25209}{25278}Sami, zauvijek sami.
{25284}{25338}I kada jebemo sami smo.
{25344}{25395}Sami sa svojim tijelom.|Sami sa svojim životom...
{25401}{25473}...koji je poput tunela,|nemoguæe ga je dijeliti.
{25481}{25564}Sa godinama se sve samo pogoršava...
{25571}{25668}...ostavljajuæi nam jedino |uspomene života koji polagano propada.
{25742}{25822}Gledajte, gða Fabienne.
{25838}{25889}Što ona radi ovdje?
{25933}{25986}Kvragu, veæ smo tu.
{26136}{26218}Èudno... kada mi se god svidi |neka djevojka, zabrljam.
{26224}{26311}Èak i onda kada one žele mene.|Ona me definitivno želi.
{26317}{26424}Ali kladim se da ima deèka.|Sve djevojke negdje imaju deèke.
{26433}{26527}Život je tunel. Svatko ima svoj|vlastiti, mali tunel.
{26533}{26599}Samo što nema svjetla na kraju.
{26605}{26704}Samo praznina.|Èak i uspomene nestaju.
{26711}{26795}Stari ljudi to znaju.|Žive jednostavan život...
{26802}{26868}...imaju malu penziju|i mali grob.
{26874}{26947}I sve je potpuno beskorisno.
{26952}{26997}Èak i imati djecu.
{27002}{27099}Kada ostariš i budeš siromašan,|stavit æe te u dom...
{27105}{27161}...i pustiti te da patiš u tišini.
{27167}{27245}Njima nije stalo.|Oni ne vole svoje roditelje.
{27252}{27361}To je mit. Voliš svoju majku|jedino kada te hrani.
{27368}{27433}A svog oca jedino kada ti daje novac.
{27448}{27524}Èim se njoj sise malo|osuše...
{27532}{27641}...ili kad oèev džep ostane|prazan, bolje ih je maknuti...
{27647}{27743}...i nadati se da æe umrijeti|brzom i jeftinom smræu.
{27767}{27827}To je zakon života.
{27833}{27942}Samo kada postoji nasljedstvo,|djeca se prave dobra.
{27948}{28058}Ali, zbog hladnjaka ili TV-a|nema potrebe glumiti dobrog tipa.
{28064}{28149}Možda minimalno,|zbog unutarnjeg mira.
{28155}{28199}Nazvati ih svaki drugi mjesec...
{28205}{28295}...ispustiti par suza na pogrebu|i obavio si svoju dužnost.
{28302}{28386}Ljubav i prijateljstvo.|Sve je to ogromno sranje.
{28392}{28463}Iluzije iz mladosti...|da prikriju èinjenicu...
{28468}{28577}da su svi ljudski odnosi|nepotrebni.
{28583}{28683}Naravno da su prijateljstvo i ljubav potrebni,|ali jedino ako od njih ima koristi.
{28689}{28751}Stvarnost je puno više korumpirana.
{28757}{28847}Voliš svoju majku, jer te ona|hrani da bi preživio.
{28852}{28961}Svog prijatelja, jer ti on pomogne|naæi posao, da bi preživio.
{28968}{29043}Svoju ženu, jer ti kuha|i oslobaða te sperme...
{29051}{29133}...i daje ti djecu|koja æe se brinuti za tebe kada ostariš...
{29139}{29185}...i bojati se umrijeti.
{29220}{29324}Ali, kazni svoje dijete jednom,|i sve æe ti se to vratiti kada ostariš.
{29338}{29383}Kazna...
{29389}{29463}...æe biti njihovo oruðe.|Kada te stave u dom...
{29468}{29548}...to æe im biti isprika|da prikriju svoje nezanimanje...
{29554}{29641}...koje svi osjeæamo|spram svojim odgajatelja.
{29670}{29788}Ne, ne sviða mi se beba|koje mi žele uvaliti.
{29838}{29918}I siguran sam da bi|beba mislila jednako.
{29955}{30057}Ne, jebaèina je definitivno|pogrešno shvaæena.
{30063}{30114}Èak je i jebeno skupa.
{30120}{30168}Ali ipak, to je razbibriga.
{30174}{30285}Kada ti se više ne jebe,|tada znaš da je tvoje vrijeme isteklo.
{30291}{30386}I da je sve isto|u tvom životu.
{30426}{30499}Jedino je reprodukcijski kod|urezan u nama...
{30505}{30574}...i mislimo da mu moramo služiti.
{30677}{30711}Hvala.
{30720}{30764}Biti roðen protiv svoje volje. Jesti.
{30770}{30855}Mahati kurcem uokolo.|Zapoèinjati novi život. Umrijeti.
{30867}{30967}Život je jedna velika praznina. Uvijek je bila,|i uvijek æe biti.
{30973}{31076}Ogromna praznina koja funkcionira|èisto dobro i bez mene.
{31127}{31236}Ne želim više igrati tu igru.|Ne u ovom životu.
{31270}{31355}Želim iskusiti nešto osobno,|nešto intenzivno.
{31361}{31474}Ne želim biti konaèni, zamjenjivi|dio divovske mašinerije.
{31482}{31577}Na dan kada umrem hoæu|znati da sam napravio više...
{31583}{31676}...nego usrani milijuni jebaèa|zajedno.
{31682}{31739}Pogledajte to ovako...
{31745}{31836}...svaki pušaè je radio iste|stvari kao i ja.
{31848}{31942}Ne znam.|Moram naæi razlog...
{31949}{32036}...ispriku, ili bilo što|da naðem motivaciju...
{32042}{32107}...za sljedeæih 20 godina.|Dok ne umrem.
{32133}{32267}Da poèinjem život ponovno,|želio bih raditi porniæe.
{32273}{32368}Sve je jasno.|Ljudi koji to rade...
{32374}{32430}...razumiju ljudsku rasu.
{32436}{32505}Ili si roðen s karom|koja treba biti...
{32511}{32591}...veliki, tvrdi kurac|koji æe puniti proreze.
{32597}{32749}Ili si roðen sa pièkom|koja treba biti popunjena kurcem.
{32764}{32828}U oba scenarija, opet æeš biti sam.
{32835}{32938}Da, ja sam kurac.|To je to.
{32958}{33011}Ja sam tužan, tužan kurac...
{33019}{33150}...i da bih zaradio malo poštovanja|moram biti tvrd cijelo vrijeme.
{33187}{33274}Ali s debelom kravom|to više ne mogu.
{33281}{33356}Radije bih uzeo|staru ljigavicu.
{33362}{33467}Ili svo troje.|Ja, majka, kæer.
{33473}{33571}Kladim se da bi im se svidjelo to,|te perverzne kurve.
{33577}{33660}Da obje budu dobro pojebane|na tatinom krevetu.
{33666}{33755}Krava bi popizdila.
{33769}{33891}Kompleks tornjeva Pablo Picasso.|Te noæi, oko 10:30.
{34550}{34589}Gdje si kvragu bio?
{34595}{34648}Jesi li je jebao?
{34655}{34727}Jesi li je jebao?|- Što?
{34733}{34787}Moram li ti slovkati?
{34828}{34902}Što mi je Fabienne rekla?
{34908}{34975}Vidjela te jutros|s nekom kurvom.
{34981}{35042}Nisam ništa napravio.|- O, ma nemoj?
{35049}{35101}Nije mi se dalo vraæati|u ovu prokletu rupu.
{35107}{35186}Pa, odlazi onda. Odjebi.|- Sigurno hoæu.
{35192}{35260}Dobro. Konaèno æu imati|svoje dijete samo za sebe.
{35267}{35344}Da ga pretvoriš u pedera.|- Kao i njegov tata.
{35350}{35380}Pederu.
{35386}{35450}Kako si me nazvala?|- Polupederu.
{35456}{35555}Glupa kuèko. Evo ti.|- Ti si glupa kuèka.
{35561}{35625}Što?|- Ti si glupa kuèka.
{35630}{35732}Udarit æu te u jebeno|lice, glupa stara kuèko.
{35741}{35801}Govno jedno!
{36213}{36280}Idem po pištolj.|- Što?
{36286}{36345}Pištolj.|- Koji pištolj?
{36390}{36443}Otkud ti pištolj?|- Od muža.
{36449}{36491}Gdje je taj pištolj?
{36504}{36556}Gdje je?|- Tamo.
{36562}{36655}Gdje tamo?|- Tamo u ormaru.
{36661}{36701}Kojem ormaru?
{36738}{36786}Onaj mali?|- Da.
{36795}{36843}Kuèko.
{36971}{37009}Mama...
{37015}{37058}Moja beba...
{37087}{37136}Moja beba, mama.
{37156}{37194}Nemam je.
{37335}{37410}Ubio je moju bebu.
{37517}{37565}Zovem policiju.
{37619}{37676}Ta kuèka. Podmukla je.
{37682}{37746}Stvarno podmukla.
{37756}{37829}Ostani miran. Miran, miran.
{37835}{37906}Moram se izvuæi iz ovog|prokletog mjesta.
{37971}{38019}Moja beba, mama.
{38025}{38142}Koja beba, tvoja beba je sada|mesna okruglica. Meso.
{38170}{38266}Barem bi trebala biti sretna|što neæe vidjeti tvoje prokleto lice.
{38272}{38382}Moja beba... moja beba...
{38604}{38687}Mama, moja beba...
{38776}{38857}Šupèino! Jebaèu! Kuèkin sine!
{39310}{39389}Te kuèke su dovoljno lude|da nazovu muriju.
{39395}{39445}Možda veæ i jesu.
{39451}{39533}Kako sam je pretukao, vjerojatno|sada bljuje fetus po tepihu.
{39539}{39597}To bi moglo znaèiti nevolju.
{39603}{39681}Nemam pojma koliko godina|bi mi mogli dati za to.
{39687}{39796}Mogla bi to nazvati ubojstvom,|mada je sama zapoèela.
{39806}{39873}Kvragu. Što da radim sada?
{39879}{39950}Nije da mi je žao.|Tom djetetu je bolje mrtvom...
{39956}{40013}...nego zaglavljenom|s njih dvije.
{40019}{40095}Kladim se da æe se krava razboljeti.
{40115}{40195}Da. Bolje da se ne vraæam onamo.
{40201}{40235}Ne veèeras. Nikada više.
{40241}{40336}Gotovo je.|Bolje mi je samom...
{40342}{40399}...nego gledati njih dvije.
{40405}{40501}Nisam odgovoran za|sav jad na svijetu.
{40507}{40611}Ne. Poèinjem ponovno,|sam, u Parizu.
{40635}{40735}Ako to znaèi da æu trebati biti |seronja, tako æe i biti.
{40741}{40790}Totalni seronja.
{40827}{40869}Mogu ja to.
{40915}{40963}To je jedini naèin da pobijedim.
{41105}{41188}Potrošio sam previše prokletog vremena.
{41207}{41266}Osim toga, sada imam pištolj.
{42066}{42130}Nadam se da voliš dobru glazbu.
{43247}{43334}Odvest æu te do Sjevernog Pariza.|OK?
{43538}{43595}Vražji Pariz može biti dosadan...
{43602}{43672}...ali ostatak je još gori.
{43680}{43764}Kako ljudi mogu živjeti na takvom|mjestu cijeli život?
{43772}{43859}Ti seljaci su vjerojatno|potpuno drugaèiji od mene.
{44009}{44105}OK. Još jedno poglavlje u|životu našeg sirotog èovjeka.
{44111}{44208}Kako se izvukao iz |dvostruke paukove mreže.
{44229}{44321}Veæ mi je bolje.|Sa svim tim sranjem iza sebe.
{44334}{44414}Ne znam kako æu preživjeti|od samo 300 franaka.
{44420}{44514}Prvo trebam prenoæište.|Osim toga, imam prijatelje.
{44520}{44566}Pa, to æemo još vidjeti.
{44572}{44671}Barem sam u blizini|pravih ljudi ponovno.
{44694}{44785}Nekako mi navire sretan osjeæaj|da trebam slijediti svoje instinkte.
{44791}{44859}Moram biti oprezan da|ne naletim na policiju.
{44865}{44951}Kladim se je krava veæ odglumila|sirotu, staru žrtvu do sada.
{44957}{45067}Možda je èak i rekla nekome od|mojih pariških prijatelja.
{45073}{45142}Da, moram biti na oprezu.
{45148}{45229}Barem me policija nikada|neæe naæi ovdje.
{45266}{45362}Bio sam u klubu.|Ona je bila tamo. Pogledali smo se.
{45368}{45449}Možete li mi dati sobu na drugom katu,|onu s pogledom na ulicu?
{45455}{45543}Jeste li veæ bili ovdje prije?|- Prije petnaest godina.
{45592}{45632}Soba broj 26.
{45648}{45748}60 franaka za noæ. Plaæeno unaprijed.
{45754}{45850}Poslije toga, plaæaš mi 60 franaka |za svaku dodatnu noæ.
{45856}{45984}...mogao sam je proždrijeti.|Nisam mogao prestati.
{45989}{46080}Poèela je lupati i cviliti.
{46086}{46151}Navalio sam kao pobješnjeli bik.
{46157}{46270}A ona je vrištala. Razjebao sam je u komadiæe.
{46276}{46338}Nevjerojatna veèer.
{46694}{46733}Vaša soba, gospodine.
{46828}{46882}Onda æu platiti za veèeras...
{46888}{46945}A za sutra æemo vidjeti.
{47113}{47167}U redu.
{47462}{47533}Èudno je vratiti se|ponovno u ovu sobu.
{47546}{47620}Stajati ispred kreveta|u kojem je napravljena moja kæer.
{47653}{47714}Mama joj je bila pravi komad.
{47720}{47797}Da sam znao da æe napustiti|mene i djevojèicu...
{47803}{47871}...ne bih to napravio.
{47877}{47986}Ali nema povratka natrag. |Svršio sam i sada imam kæer.
{47992}{48034}Mada je njezina majka mrtva...
{48040}{48141}...još imam svoje uspomene|svih popodneva u ovom krevetu.
{48147}{48183}Prava žena je prekrasna.
{48189}{48271}Ali veæina ih je èangrizava|jer ne dobiju kurca.
{48277}{48322}Kvragu...
{48328}{48415}...ženska je ostavila mene |i dijete zbog Portugalca.
{48421}{48492}Žene znaju biti tako jadne.
{48505}{48601}Zato što nemaju kurac,|osjeæaju se superiorno muškarcima...
{48607}{48733}...kada ih izdaju sa drugim|kurcem. Osobito ako je bogatiji.
{48739}{48808}Nakon što ju je izjebao...
{48814}{48900}...princ ju je izbacio|kao komad pokvarenog sira.
{48923}{49031}Bila je zla, ali dovoljno bistra|da shvati što je imala.
{49037}{49085}Prošlost se uvijek osveæuje.
{49091}{49147}Uvijek plaæaš za ono što si uèinio.
{49157}{49226}I ako se bacila na autocestu
{49248}{49294}...ja nisam tu mogao ništa poduzeti.
{49303}{49354}Dobila je što je zaslužila.
{49363}{49427}Isuse Kriste, nije lako biti švorc.
{49433}{49497}Ali ono najgore je nemati |se na koga osloniti.
{49502}{49560}Što manje imaš,|to si beznaèajniji.
{49566}{49680}Uvijek im mogu reæi da sam otac,|da sam imao vlastiti duæan. Da sam dobra osoba.
{49686}{49757}Vlasnik hotela,|moj takozvani prijatelj...
{49763}{49829}...konobar,|njih nije briga.
{49835}{49910}Kada vide da si švorc,|jednostavno te izbace van.
{49916}{49984}Pokušavajuæi te pritom što više|poniziti.
{49990}{50057}Umjesto da pomognu èovjeku|u nevolji...
{50063}{50183}...uvlaèe se nekom bogatašu u šupak|i nadaju se novcu.
{50189}{50255}Zato uvijek prièaju sranja.
{50261}{50313}Radije bih bio siromašan i iskren.
{50319}{50402}Neka mi netko da posao|da otkupim svoj duæan.
{50408}{50545}Sve me ostalo ostavlja samog.|Nije neka euforija, ali preživjet æu.
{50553}{50642}Kako glupo od mene, posjeæivati|na dan zatvaranja.
{50676}{50742}Pitam se koga bih mogao okrasti...
{50834}{50920}Ne, neæu to napraviti.|Neæu spustiti svoje standarde na žicanje.
{50930}{50997}Moram imati nekog samopoštovanja.
{51012}{51089}Uvijek mogu prodati pištolj.
{51096}{51166}Bit æe za dobrih 200 do 300 franaka.
{51317}{51389}'Jutro. Šalicu kave, molim.
{51478}{51532}Mogu li dobiti šalicu kave, molim?
{51551}{51604}Za èaj od mente pokušaj preko puta.
{51610}{51665}Nisam tražio èaj od mente.
{51711}{51823}Nisam dobio dostavu danas.|- Veæ si poslužio neke ljude.
{51860}{51936}Upravo sam ti rekao da nisam|dobio dostavu danas.
{51945}{51998}Kako glupo.
{52019}{52142}Kažeš mi da nisi dobio dostavu,|ali si poslužio veæ neke.
{52157}{52295}Budi pristojan. U mom si lokalu.|-Pristojan sam.
{52302}{52407}I nisam u 'tvom' lokalu, ja sam u lokalu.|Molim, posluži me.
{52414}{52479}Slušaj, ne cijenim te.|- Moraš me poslužiti.
{52486}{52540}Ne stvraja mi probleme.
{52545}{52610}Mrdaj svoje smeðe dupe odavde.
{52680}{52757}Trebao bi otiæi i vidjeti...
{52765}{52820}svoju staru mesnicu.
{52826}{52862}Zašto?
{52867}{52952}Pa, Arap je fantastièan.
{52970}{53054}Duæan je uvijek pun.|Ponekad ni ne stigne poslužiti sve.
{53125}{53295}Misliti o tome kako ti se život promijenio.|Išlo ti je prilièno dobro.
{53302}{53382}Kako to da si završio ovako?
{53410}{53460}Užasno izgledaš.
{53466}{53555}Da.|- Pa, jednostavno je: nemam posao.
{53574}{53682}Šteta. I samo æe se pogoršati.
{53704}{53762}Baš ti hvala.
{53811}{53919}Da ti kažem što ti je èiniti.
{53932}{54025}Idi u zavod za zapošljavanje.
{54137}{54227}Izgledaš mi malo blijedo.
{54232}{54374}Ako ne želiš završiti |u nekom jarku...
{54387}{54512}...moraš nešto poduzeti.|Zgrabi život ponovno.
{54570}{54654}Kakvu vrstu posla tražite?|- Ja sam mesar.
{54662}{54758}Nemamo posla za mesara trenutaèno.|- A mesara za puretinu?
{54765}{54810}Ista stvar.
{54853}{54912}Pokušajte ponovno za neko vrijeme.
{54986}{55019}Hvala.
{55545}{55637}Ti... Sigurno|se želiš zabaviti.
{55670}{55703}Naravno.
{55817}{55857}Pa...
{55907}{55958}Èekaj...
{56028}{56083}Odvest æu te nekuda.
{56478}{56528}Što taj tip hoæe?
{56542}{56645}Je li peder, ili samo ljubomoran|što ona želi moj kurac?
{56669}{56796}Zašto ne. Nije moj tip,|ali ne mogu to odbiti.
{56904}{56963}Izgleda mlado. I seksi.
{56979}{57055}Nadam se da æe mi se dignuti.|Ako ne...
{57064}{57153}...uvijek se mogu izvuæi da|sam osjeæajan tip.
{57317}{57379}Što se dogaða?
{57386}{57476}Tukao sam male kuèke|prije.
{57532}{57626}To je razmjena, znaš?
{57655}{57762}Mislim... dat æu ti energiju.
{57823}{57874}I toplinu.
{57880}{57957}To je razmjena|tekuæina...
{57963}{58116}Mada su naše energije|razlièite boje...
{58125}{58249}Neæeš mi dati novac.|Hoæeš li?
{58366}{58489}Jesam li u pravu? Da?|Dat æeš mi energiju.
{58495}{58565}Zato što æu i ja tebi dati energiju.
{58726}{58792}Da li se slažeš?
{58820}{58874}Slažeš se, zar ne?
{58880}{58937}Pokaži mi ruku.
{59137}{59195}Ugodan si.
{59438}{59498}Gledaj, postajem tvrda.
{59632}{59675}Tatice...
{59725}{59790}Neæeš me ozlijediti, zar ne?
{59817}{59862}Doði.
{59919}{59969}Da, doði.
{60564}{60641}Da me bar pustila da napravim to|na svoj naèin.
{60657}{60751}Ali ne. Totalna katastrofa.
{60795}{60835}Kuèka.
{60842}{60890}Sve su iste.
{60916}{60996}Ista poza,|ista scena, isti smrad.
{61004}{61077}A èak sam i platio za to.
{61098}{61171}Ovo nije dobro, mesaru.|Ovo uopæe nije dobro.
{61178}{61229}Probudi se. Brzo
{61240}{61332}Potražit æu starog Rolanda.|On mi je uvijek bio najbolja mušterija.
{61340}{61429}Nadam se da nije otišao u mirovinu.|Uvijek je to priželjkivao.
{61435}{61524}Kladim se da je dobri, stari Roland|uštedio neki novac.
{61529}{61628}Nadam se da mi ona kurva|nije prenijela neku boleštinu.
{61632}{61695}Samo mi to još nedostaje,|kurac prekriven gnojem.
{61701}{61775}Zadnji put je bio u vojsci,|hvala Bogu.
{61790}{61900}Ne, ne mogu.|Uvijek je ovo ili ono.
{61905}{61966}Ne možemo tako živjeti.
{61978}{62049}Ali, on je prijatelj, zar ne?
{62054}{62157}Je. Ali postoji više|prijatelja na svijetu.
{62164}{62229}Pogotovo kada traže usluge.
{62257}{62339}To je život.|- Recite mu da sam svratio.
{62345}{62438}Hoæu. Ali ne znam |hoæe li biti sretan zbog toga.
{62467}{62592}Došli ste u krivo vrijeme.|Ne mogu vam pomoæi s novcem.
{62599}{62687}Ni sa 200 franaka?|- Želite li da ispraznim džepove?
{62692}{62724}Ne, nemojte.
{62729}{62857}Mogu vam dati nešto hrane.|- Ne, hvala.
{62863}{62964}Mogu vam ponuditi krevet tu i tamo.
{62990}{63063}Ako želite. Na dan ili dva.
{63107}{63142}Bit æu u redu.
{63149}{63227}Stvarno sam švorc, znate.
{63232}{63320}Posudio sam novac tipu koji|mi je bio poput sina.
{63329}{63385}Još mi nije vratio.
{63391}{63474}Najgore je to što ja živim od |socijalne skrbi.
{63492}{63579}Ne mogu si priuštiti odlazak|u staraèki dom.
{63628}{63733}Znate mene.|Napravio bih to da mogu.
{63769}{63867}Ali osjeæajte se slobodnim svratiti |bilo kada. Ako želite.
{63887}{63951}Uvijek æete dobiti kruha.
{63998}{64054}Kako vaša kæer?
{64129}{64166}Dobro.
{64220}{64263}Da, OK.
{64329}{64394}Morate se boriti za nju.
{64410}{64550}Uvijek sam živio ovako.|Uvijek sam se borio.
{64653}{64766}Nemam puno.|Kao što rekoh, socijalna skrb.
{64866}{64928}Osjeæajte se slobodnim svratiti |bilo kada.
{64975}{65049}Uvijek æe se naæi komad|kruha za vas.
{65263}{65349}Život je bitka, svaki dan.
{65376}{65457}Morate se boriti. |I pokazati izdržljivost.
{65482}{65536}Imajte to na umu.
{65596}{65661}Tako je i kod mene. Ja se borim.
{65669}{65721}To sam uvijek radio.
{65872}{65917}Probajte izvuæi nešto iz toga.
{65932}{66032}Vi ste poput mene.|Roðeni pod nesretnom zvijezdom.
{66038}{66134}Postoje bogati ljudi i siromašni ljudi.|Siromašni moraju trpjeti.
{66142}{66206}Mi smo oni siromašni.
{66225}{66315}Molim vas, posjetite me ponovno,|volio bih to.
{66347}{66432}Nadam se da æe biti pod|boljim uvjetima.
{66966}{67071}Da. Otprilike dovoljno za sendviè.|Ali ipak...
{67103}{67186}Šunka ili sir. Ne oboje.|I bez maslaca.
{67222}{67267}Vruæe je ovdje.
{67287}{67339}Što æu sutra?
{67347}{67434}Ne mogu prositi.|Ne u mojim godinama.
{67465}{67524}I sigurno ne u svom susjedstvu.
{67537}{67597}O, što volim svoju zemlju.
{67603}{67634}Francuska.
{67640}{67739}Siromašna Francuska. Pogoðena|svim jadom na svijetu.
{67745}{67873}Nema više tvornica, nema više posla.|Samo ruševine i nezaposleni.
{67905}{68003}Kvragu, što sam gladan.|A nikakvog duæana nema na vidiku.
{68012}{68118}Ni milju odavde.|Mogu komotno ostati ovdje.
{68125}{68189}Saèuvao bih si novac|za hranu sutra.
{68211}{68304}Bolje da odem spavati.|Kada spavaš, zaboraviš na glad.
{68310}{68379}Možda sutra ni neæu|biti gladan.
{68414}{68486}Oprostite, imam nekih problema|u voðenju duæana.
{68494}{68578}Blizu sam bankrota.|Probajte kod Antoinea.
{68584}{68652}Možda vam on može pomoæi.
{68671}{68759}Ne mogu napraviti ništa za vas.
{68786}{68845}Ne mogu vas zaposliti.
{68951}{69045}A što ako...|- Ne, ne mogu vam pomoæi.
{69078}{69139}Ali, poznajete li direktora klaonice?
{69145}{69231}France Chevalinea?|- Da, idite pitati u klaonicu.
{69314}{69421}Užasno je.|Nema se što raditi.
{69428}{69467}Jedva nešto prodajemo.
{69473}{69537}Baš sam morao otpustiti nekoga.
{69542}{69630}Nisam si ga mogao priuštiti.|U krizi smo.
{69674}{69717}Slušajte...
{69751}{69817}Mrzim pitati...
{69829}{69951}ali, možete li mi posuditi nešto novca?|Na par dana. Dok ne naðem posao.
{69971}{70059}Kasnim mjesec dana s plaæanjem raèuna.|Mjesec dana!
{70110}{70179}Možete li zamisliti?
{70270}{70351}Klaonica je tražila ljude.|Pokušajte tamo.
{70357}{70422}Pokušajte. Idite, prièajte s njima.
{71218}{71390}Život je tako prokleto sebièan.
{71411}{71594}Preživljavanje je genetski zakon.
{71721}{71830}Nije dobro tražiti posao|kod svojih bivših dobavljaèa.
{71893}{71995}Pogotovo ako želim otvoriti |vlastiti duæan kasnije.
{72001}{72072}Pa, to baš i nije vjerojatno.
{72142}{72281}Ah, to je najmanje što mogu uèiniti |za mene poslije svega što sam kupio od njih.
{72300}{72375}Mislim da sam se sviðao direktoru.
{72478}{72584}Mada, biti ugodan prema mušteriji|ne znaèi puno.
{72636}{72750}Da ima posla, tražili bi|mesara kao što sam ja.
{72760}{72871}Nadam se da neæe pitati za|Arapa koji je preuzeo moj duæan.
{73103}{73189}Kada æete platiti za sobu?|- Idem po novac.
{73195}{73234}Kvragu.
{73240}{73323}Raznijet æu mu mozak|ako ne prestane.
{73369}{73430}Što? Nema se tu èega sramiti.
{73436}{73509}Nemam što izgubiti.|Idem do kraja.
{73515}{73593}Napravit æu to za novac.|Ubijanje konja možda nije...
{73599}{73700}...vrlo zabavno,|ali me olakšava.
{73722}{73753}Da.
{73759}{73821}Trebam dobar posao.
{73927}{74031}Sreli smo se prije.|Bio sam vaša mušterija, sjeæate se?
{74045}{74095}I bankrotirali ste.
{74123}{74163}Da.
{74196}{74245}Kako bilo...
{74251}{74350}klanje konja je lakše|od voðenja mesnice.
{74356}{74440}To je dijelom istina.|Slušajte.
{74446}{74557}Možda nam zatrebaju mesari kasnije.|Jeste li ispunili formulare?
{74563}{74599}Da, jesam.
{74618}{74702}Ne vidim vašu dob.|- Pedeset.
{74772}{74845}Dobro. Imate li dosje?
{74859}{74905}Da... Nemam.
{74958}{75011}Bio sam u zatvoru|na nekoliko dana.
{75017}{75072}Bila je to pogreška.
{75078}{75173}Mislio sam da mi je netko|napao kæer.
{75268}{75391}Vjerojatno bih vam trebao reæi|da sam razgovarao sa više kandidata.
{75419}{75491}I to nije samo moja odluka.
{75498}{75544}Slušajte, evo što biste trebali uèiniti.
{75550}{75657}Nazovite moju tajnicu...|poènite sljedeæi mjesec.
{75752}{75816}Ne možete me zaposliti prije?
{75822}{75898}Da se mene pita...
{75913}{75979}...to bi veæ bilo riješeno.
{76212}{76250}Hvala.
{76284}{76369}Oprostite na zadržavanju.|- Nema problema.
{76522}{76619}Što? Takav peder, da me tako tretira?|Sigurno sanjam.
{76625}{76678}Kao da ne znam da mu je žena|pobjegla...
{76684}{76760}...jer ga je jedan od zaposlenika|jebao u guzicu.
{76766}{76874}Svi klaonièari znaju|da Blanchat voli kurèeve.
{76880}{76960}Ima dobru dozu samopoštovanja|za prokletu pederèinu, to je sigurno.
{76966}{77022}Kladim se da mu je otac|bio isti.
{77028}{77162}Zašto je tako puno bogataša gay?|Vjerojatno zbog nedostatka fizièkog rada.
{77175}{77273}Totalni su mlitavci.|To im svima zajebe gene.
{77279}{77379}Da, to je to.|Francuzi i njihov France Chevaline.
{77385}{77465}Uvreda je svima nama što je taj|seronja Francuz.
{77471}{77578}Kontrolirani od takvih ljudi,|sigurno smo nacija bogatih gadova.
{77584}{77645}Što im je finija odjeæa, to su gori.
{77651}{77755}Formular moje dupe. Trebao sam ga|odmah odalamiti po licu.
{77761}{77833}Trebao sam ga izmlatiti.|Pitati me za dosje.
{77839}{77914}Misli li taj jebaè|da sam ja neki gubavac?
{77920}{78002}Trebao bi malo otiæi u zatvor|i vidjeti kakav je stvarni svijet.
{78008}{78106}Ali bogati nikada ne idu u zatvor.|Možda jedan ili dvoje svakih deset godina.
{78112}{78221}Zatvor je za siromašne.|A zakoni su za bogate.
{78227}{78344}Siromašni ne mogu krasti.|Jedino okradeni i izjebani.
{78350}{78406}Nema problema.|A bogataši...
{78412}{78499}...nam mogu uzimati novac, sreæu|i dignitet.
{78505}{78590}Svaki dan ti vam prevaranti|i njihovi sinovi...
{78596}{78702}...guraju ruke u džepove|i guzicu.
{78709}{78804}Vaše, vaše žene, vaše djece.|I èak æe vas natjerati da se smješkate.
{78810}{78885}OK, smješkat æu se.|Ali poslije toga: osveta.
{78891}{78939}U tome najviše uživam.
{78945}{79025}Francuskoj su potrebni ljudi |poput Robespierrea.
{79031}{79111}A ne ovi šmokljani|u našoj vladi.
{79117}{79191}Ovako je u zemlji veæ stoljeæima|Ovako ili još gore.
{79197}{79264}Svi su previše gay|za revoluciju.
{79270}{79332}Sada je osveta sve što je preostalo.
{79343}{79423}Da, kao ja. Ja æu svima|olakšati.
{79429}{79503}Ako je Robespierre mogao biti |nacionalni junak, i ja æu...
{79509}{79584}...na manjem nivou,|ubijajuæi svu tu gamad...
{79590}{79649}...koja me ne želi zaposliti|zato što sam bio u zatvoru.
{79655}{79795}Želi li me pretvoriti u crva|koji æe mu pušiti kurac za novèiæ?
{79801}{79868}Pokazat æu ja njemu pravo nasilje.
{79874}{79938}50 godina poniženja|koje sam imao...
{79943}{80051}...on æe dobiti u šest minuta.|Šest minuta èiste agonije.
{80057}{80124}Nažalost, neæe dobiti priliku|uèiti iz iskustva.
{80130}{80212}Njegova obitelj æe platiti.|I njegovi prijatelji.
{80218}{80263}Bogataši uvijek imaju prijatelje.
{80291}{80361}Ja nemam prijatelja.|Samo svoj pištolj.
{80398}{80474}Gledaj, gostionica.|Nazdravit æu tom jebaèu...
{80480}{80541}...koji nema pojma da je upravo|potpisao vlastitu smrtovnicu.
{80547}{80630}Da, ostalo mi je nešto novca.|Oko jedanaest franaka.
{80645}{80705}Znam kako æe izgledati moje sutra.
{80711}{80796}Èekat æu ga sutra naveèer,|pred vratima. I pratiti ga.
{80802}{80875}Èim me ugleda, uplašit æe se.
{80881}{80962}Ubrzat æe prema svom stanu|kako mu se budem približavao.
{81001}{81061}Kako si? Završio si s poslom za danas?
{81067}{81128}Sigurno je naporno odbijati|ljudima molbe za posao svakodnevno.
{81134}{81221}Èovjeèe, stvarno znaš kako poniziti|ljude s one strane tvoga stola.
{81227}{81276}Sjeæaš me se, zar ne?
{81300}{81420}Imaš kuæu, auto, odjeæu|i novac u banci.
{81426}{81513}Od 35 godina rada|nije mi ništa ostalo.
{81519}{81595}Sve što je ostalo od mog života|nije na tvom formularu...
{81601}{81685}...to je moj pištolj.|O, nisi navikao na pištolje.
{81691}{81749}Pa, ja nisam navikao na gotovinu.
{81755}{81811}I ja bih želio normalan život.
{81817}{81871}Nakon 35 godina rada i poštenja...
{81877}{81979}...moj dostavljaè me tretira|kao kriminalca.
{82066}{82137}OK, g. Šefe, izgubio sam.
{82143}{82207}Ja sam obièno govno.|Ali imam pištolj.
{82212}{82330}Ne bojim se.|Moja æe biti zadnja.
{82336}{82454}Stisnut æu mu pištolj uz vrat|i promatrati kako mu se pedersko lice trza.
{82460}{82524}Veæ si se usrao?|Zašto si takav slabiæ?
{82530}{82606}Zato što sam nezaposlen?|Ili je to zbog mog dosjea?
{82634}{82682}Znaš li što nezaposleni govore?
{82688}{82759}Jebi se.|Od svih rasa na svijetu...
{82765}{82817}...jedna mora nestati.|Znaš li koja?
{82823}{82882}Tvoja. Seronje i izdajice.
{82888}{82984}Podiæi æu pištolj i raznijeti mu|mozak. Slušaš li me sada?
{82990}{83103}I pucat æu ponovno.|Mogu ga èuti kako vrišti: Ne! Ne!
{83110}{83156}Što kažeš na to, g. Šefe?
{83162}{83285}Život zna biti nasilan.|Nisi ovo oèekivao, zar ne?
{83319}{83393}Koliko vam dugujem?|- 12 franaka.
{83877}{83930}Može 11.20?
{84077}{84118}Koji je tvoj problem?
{84213}{84255}Želiš li mi pušiti kurac?
{84331}{84372}Želiš li mi pušiti kurac?
{84456}{84498}Siromašni kreten.
{84681}{84734}Crnaèka pederèino.
{84890}{84954}Rekoh: crnaèka pederèino.
{84980}{85064}Odjebi odavde.|- Nisam ništa loše napravio.
{85070}{85143}Jesi li me èuo? Goni se.|- Nisam ništa napravio.
{85149}{85210}Odjebi.|- Nisam ništa napravio!
{85216}{85273}Odjebi van, seronjo.|- Ne izazivaj.
{85362}{85426}Vidiš li ovu pušku?|Pusti mog sina na miru.
{85432}{85532}Neæu te upucati u guzicu,|veæ u glavu, propalice.
{85539}{85571}Odjebi.
{85595}{85656}Odjebi ili æu ti raznijeti mozak.
{85918}{85963}OK je.
{85982}{86025}OK je.
{86031}{86059}Pièkica.
{86125}{86211}Ništa ne kužiš.|Èija si ti kuèka?
{86217}{86289}Odjebi, seronjo.|Lud je.
{86296}{86360}Jebaè si misli da je neka faca.
{86395}{86471}Otkuda se on stvorio?|- Pijan je.
{86477}{86551}Gostionièar je bio dovoljno|pristojan što je samo mahao tom puškom.
{86568}{86630}Ja bih veæ povukao okidaè.
{86636}{86714}Ti si težak sluèaj.|- Alkoholièar.
{86720}{86764}Još jednu rundu, gostionièaru.
{86811}{86880}Samo jednu?|- Da, za mene i moje prijatelje.
{86886}{86967}Seronje. Idem po svoj pištolj.
{86973}{87035}Još me ne znaju.|Ne znaju tko sam ja.
{87041}{87129}Ne boj se upotrijebiti nasilje.|To je ljudska stvar.
{87135}{87201}Moram ovo riješiti|brzo i temeljito.
{87207}{87323}Pokazat æu ja njima pravdu svoje zemlje.|Klanjat æe se oni pištolju.
{87329}{87428}Nema pravde bez osvete.|Neæu uplitati muriju.
{87472}{87564}Moram provesti pravdu.|Smrt tim propalicama.
{87570}{87608}Bez milosti.
{87614}{87671}Metak u njihove prazne glave...
{87677}{87751}...i to su dva parazita|manje na svijetu.
{87797}{87866}Kvragu. Moram provjeriti pištolj.
{87956}{87993}Tri metka.
{88009}{88074}Jedan za gostionièara. |Jedan za njegovog sina.
{88080}{88189}I još jedan za seronju koji me|nazvao alkoholièarem. Poštivat æe me oni.
{88195}{88242}Moram se usredotoèiti na prva|dva pucnja.
{88248}{88349}Ne znam iz koje pripizdine su ispali,|ali ne izgledaju mi francuski.
{88355}{88456}Otac je nosio raspelo. Možda je neki|španjolski ili portugalski farmer.
{88462}{88542}Neki promijene ime i religiju|samo da bi se uvukli u zemlju.
{88548}{88654}Ali ja sam Francuz i ja æu ih|nauèiti dostojanstvu.
{88875}{88917}Izaði van.
{88932}{88994}Dolaziš li van, pederèino stara?
{89092}{89134}Dolaziš li, ili što?
{89212}{89271}Hej, dolaziš li van, pièkice?
{89369}{89411}Tebi se obraæam!
{89494}{89549}Nemaš muda, ha?
{89561}{89635}Izlaziš li, pièkice?
{89903}{89951}Pokazat æu ti tko sam ja.
{90003}{90040}Kvragu.
{90125}{90169}Kurcolizac!
{91184}{91264}Pomislio bi da je svijet civiliziran,|ali to je džungla.
{91270}{91371}A u džungli ti je bolje držati se|jaèih životinja.
{91377}{91435}Ili æeš biti ulizica...
{91441}{91505}...koji stalno mora bježati|i skrivati se.
{91510}{91592}To sve ovisi o sreæi|kada si roðen.
{91598}{91704}Ili si roðen siromašan, i moraš|se pokoravati drugima.
{91710}{91802}Stajati u redu, biti ponižavan.|Ali ponekad postaneš nasilan.
{91808}{91869}Ili si roðen bogat|i brineš se o svom novcu.
{91875}{91953}Pretvaraš se da voliš svoju ženu,|djecu i prijatelje...
{91959}{92011}...kao što se i oni pretvaraju|da vole tebe.
{92017}{92113}Ali èim ti život ili kuæa|propadnu...
{92119}{92234}...i ne ostane ti ništa za ponuditi,|tvoji takozvani prijatelji...
{92240}{92328}...svi æe te pregaziti, u tišini.
{92334}{92386}Da bi ti "pomogli".
{92392}{92452}To je upravo ono što žele.
{92458}{92519}Što si u goroj situaciji,|moleæi za pomoæ...
{92525}{92611}...oni æe se bolje osjeæati.|I pregazit æe te.
{92666}{92737}Sumnjam da æu ikada|shvatiti neke stvari.
{92743}{92811}Došlo je moje vrijeme. Propao sam.
{92819}{92923}U dubokom sam sranju,|potpunom i krajnjem sranju.
{92929}{93033}Ali ne bojim se. Naprotiv.|Ne molim nikoga za pomoæ.
{93067}{93128}Bit æu ispravan do kraja.
{93134}{93211}Prokopat æu tunel|kroz sva ta sranja.
{93218}{93285}To je moj cilj. Boriti se do kraja.
{93301}{93358}Cijeli moj život je bio|jedna ogromna hrpa govana...
{93364}{93435}...željen od moje majke|koja se voljela ševiti...
{93441}{93511}...a èije lice nikada nisam vidio.
{93570}{93667}Ponovi to, jebeni majmune.
{93674}{93721}Ponovi to, ako si muško.
{93727}{93768}Jebeno æu te upucati.
{93793}{93860}Krv šiklja iz glave|ovog jebaèa.
{93866}{93932}Želi zapomagati,|ali nikoga nema.
{93938}{93999}Samo njegov prokleti sin.
{94007}{94029}Jebaè.
{94066}{94145}Treæi metak je za mog prijatelja|u klaonici.
{94151}{94247}Uæi æu u njegov ured|i dati mu svoj formular.
{94253}{94287}Bankrotirao si.
{94847}{94940}Kada završim s njima,|moram ubiti sebe.
{94947}{95014}Zgodno samoubojstvo za mesara.
{95059}{95123}Ionako æu umrijeti, pa mogu |komotno napraviti što god hoæu.
{95128}{95202}Nema više kažanjavanja, |nema više zloèina.
{95209}{95268}Neke su zabave zabranjene...
{95274}{95378}...samo zato što seronje u|sveæenièkoj odori ili kravati tako kažu.
{95384}{95448}Ali meni se oni ne sviðaju.
{95454}{95522}Oni su uništili moj život.
{95528}{95622}U ime morala, oni su me|izdali.
{95862}{95942}Pa zašto se ne bih|ubio?
{95948}{96016}Još tri metka.|Ako zadržim jedan za sebe...
{96022}{96113}...još uvijek imam dva|za ostale. Da.
{96119}{96171}Nikome neæu nedostajati.
{96177}{96238}Vjerojatno æe osjetiti olakšanje.
{96269}{96348}Da, mogao bih umrijeti|i to je to.
{96355}{96433}Praznina, baš kao i prije |nego što sam se rodio.
{96800}{96900}Što je sa Cynthijom? Mogu li je|samo tako napustiti?
{96906}{96941}Bez pozdrava?
{96947}{97038}Hoæu li dopustiti da je izbace|i da postane propalica...
{97044}{97179}...izjebana i premlaæena od|ostalih pariških propalica?
{97195}{97221}Ne.
{97239}{97281}Ja sam njen otac.
{97287}{97397}Èak i ako je pogreška,|ona je moja odgovornost.
{98694}{98789}O, da. Ona svinja iz klaonice.
{98807}{98901}Ubit æu ga kao što niti jedan èovjek|prije nije bio ubijen.
{98907}{99017}Natjerat æu ga da pati koliko je god to moguæe.|Pa æu uživati u tome najviše što mogu.
{99026}{99095}Platit æe za|sve one koji zaslužuju umrijeti...
{99101}{99153}...a koje ja ne mogu ubiti.
{99159}{99228}Èak i ako nije najgori.
{99234}{99335}Da moram ubiti nekog seronju,|on je najveæi kreten kojeg poznajem.
{99341}{99490}A danas æu raznijeti njegovu|pedersku glavu u komadiæe.
{99504}{99577}To je jedini naèin da vratim|dostojanstvo...
{99583}{99655}...i radost svom životu.
{99667}{99755}Nema drugog rješenja.|Sve je jasno.
{99768}{99854}Svaki je èovjek svoj moral. |Svaki je èovjek svoja pravda.
{99870}{99948}A moja slijedi.
{100117}{100179}Pa, vidiš, vratio sam se.
{100422}{100486}Vodim je do Eiffelovog tornja.
{100492}{100549}Ugodan dan.
{100573}{100611}Hvala vam.
{101250}{101343}Promijenila se u ovih|par mjeseci. Jedva je prepoznajem.
{101349}{101422}Možda æe za par godina izgledati|kao i njezna majka.
{101430}{101528}Kako æu ja izgledati za 10 godina?|Kladim se da æu biti veæ odavno mrtav.
{101548}{101643}Bilo bi lijepo znati|što nam donosi buduænost. Tko zna?
{101653}{101717}Ako nam se posreæi, imat æemo|3. svjetski rat.
{101723}{101807}I svi seronje oko mene|æe biti razneseni u djeliæe.
{101860}{101956}Zašto Francuska, a ne ostali?|Nismo gori od Nijemaca.
{101976}{102055}Pa, Njemaèku bi trebalo uništiti.
{102061}{102145}Svi su oni nacisti|i sinovi nacista.
{102151}{102217}Nacisti su ubili mog oca.
{102325}{102408}1988., godina totalnog uništenja|Njemaèke od Rusa.
{102425}{102484}Pomozimo im.
{102533}{102585}Zašto sve ovo izmišljam?
{102595}{102657}Noæas više neæu biti|na ovom planetu.
{102675}{102726}Siguran sam.
{102734}{102788}Ali ona ne zna.
{102810}{102856}Èudno je.
{102925}{103057}Kako brzo život prolazi,|a za ništa. Èudno.
{103080}{103158}Tako je mirna,|kao da se boji.
{103164}{103245}Kladim se da osjeæa|kako ne idemo na Eiffelov toranj.
{103249}{103297}Moram je utješiti.
{103367}{103481}Idemo na dugo putovanje.|Jako dugo putovanje.
{103515}{103557}Samo nas dvoje.
{103584}{103633}Sviða ti se to, zar ne?
{103668}{103732}Pažnja. Imate 30 sekundi da|da napustite podruèje projekcije.
{103747}{103793}Jedino kada sve izgubite, |naæi æete svoj put natrag.
{103799}{103848}Možda glad proèišæuje moje misli.
{103854}{103914}Što manje jedeš,|više vidiš.
{103920}{104001}U logorima, neki su ljudi|vidjeli magnetske valove.
{104009}{104086}Sve æe biti OK. Nadam se.
{104095}{104177}Nemam što izgubiti.|Osjeæam se jaèim nego ikada.
{104183}{104248}Život jer neprestana bitka.
{104254}{104364}Za uspjeh; ne oklijevajte.|To oduzima puno energije.
{104370}{104434}Opasnost
{104443}{104574}Hotel de l'Avenir|23. travanj, 1980., oko podneva.
{104908}{105006}Sretna je što ima oca.|Ja svoga nikada nisam upoznao.
{105011}{105077}Ubili su ga Švabe.
{105095}{105164}Zašto se toliko promijenila?
{105170}{105257}Možda su radili neke èudne stvari|s njom u domu.
{105308}{105355}Ne, ne vjerujem.
{105374}{105438}Tamo su jedino žene.
{105485}{105536}Moja kæer je prilièno zgodna.
{105561}{105609}Ponosan sam na nju.
{105635}{105746}Ima dražesno tijelo. Puno|ljepše od majèinog.
{105788}{105839}Trebao bih je okupati.
{105849}{105886}Ne.
{105893}{106007}Tu je jedino sudoper. Osim toga,|mogao bih uèiniti nešto glupo.
{106023}{106064}Pištolj?
{106070}{106108}Da.
{106115}{106160}Ne bih se trebao bojati.
{106198}{106274}Ako æu predugo èekati, |mogao bih se predomisliti.
{106298}{106342}Rašèistimo ovo.
{106348}{106432}Nasilje koje moram upotrijebiti|služi...
{106438}{106541}...tome da nas izvuèe iz ove|mizerije prilièno jednostavno.
{106605}{106693}Biti mrtav je vjerojatno poput spavanja.
{106699}{106757}Ali bolje.
{107018}{107075}Što se mora, mora se.
{108056}{108135}Evo. Uèinio sam što sam morao.
{108143}{108220}Ali nije bilo baš tako prekrasno|kao što sam planirao.
{108224}{108299}Sada privedimo kraju|sav taj jad.
{108305}{108346}Nemam što izgubiti.
{108350}{108443}Da, to je to.|Èinim to za sebe.
{108449}{108515}Moja je dužnost zaštititi te|od godina oèaja koje dolaze.
{108521}{108602}Èekaj me na drugoj strani.|Odmah sam tamo.
{108636}{108685}Neæe dugo trajati.
{108810}{108854}Evo, gotovi smo.
{109605}{109642}Gotovo je.
{110043}{110107}Nisam je promašio, jesam li?
{110148}{110192}Hajde, umri.
{110198}{110268}Što èekaš?
{110279}{110333}Bilo bi bolje s nožem.
{110342}{110386}Ubijao sam svinje.
{110393}{110471}Moj sveæenik me tome nauèio.|Zabij nož u glavnu arteriju.
{110475}{110546}Trese se kao svinja.|Boli je. Mrzim ovo.
{110550}{110617}Èini se jednostavnije u klaonici.|Što sada?
{110623}{110708}Zašto ovo radim?|Ona umire. Protiv moje volje.
{110715}{110789}Vodi me viša sila.|Ona umire tamo gdje je napravljena.
{110795}{110892}To je bila sila, a ne ja.|Vraæa se onamo...
{110898}{110982}...otkuda je i došla. To æu reæi|na sudu. Kakvom sudu?
{110988}{111038}Moram se vratiti tamo gdje sam poèeo. |Ubit æu se. Pozlit æe mi.
{111044}{111152}Nemoj povraæati, ne sada, ne pored nje.|Ona je u strašnim bolovima.
{111158}{111229}Ovo bi moglo trajati predugo.|Dokrajèit æu je.
{111234}{111296}Nema svrhe plakati nad prolivenim mlijekom.|Ako pucam još jednom...
{111300}{111388}...neæe mi preostati dovoljno metaka|za sebe i klaonièarskog pedera.
{111394}{111483}Život uvijek ide u |jednom pravcu, i to prebrzo.
{111490}{111593}To je dobro protiv zla.|Moram odluèiti.
{111683}{111757}Gomilati pogrešku na pogrešku|dok ih vrijeme ne izbriše.
{111763}{111838}Ali smrt nije pogreška,|to je samo izlaz.
{111844}{111884}Moja kæer je mrtva,|sada je red na mene.
{111891}{111963}Raznesi si jebeni mozak.|Pokaži im svoj mozak.
{111969}{112049}Svi neprestano zaboravljaju da smo |samo od krvi, mesa i kostiju.
{112055}{112126}Ja sam komad mesa koji previše razmišlja.
{112133}{112200}Ubili su mi kæer.|Ubij ih.
{112207}{112288}Mesaru, oslobodi se.
{112294}{112339}Netko je napao moje dijete.
{112345}{112430}Ubit æu gada.|To mi je dužnost.
{112435}{112500}Težak...|Moj otac je bio komunist.
{112507}{112608}Želio je ono što je ispravno.|Švabe su ga ubili.
{112614}{112683}Zato što je bio humanist.|Smrtna kazna, nema 'ali'.
{112689}{112782}Sreæom, Amerikanci i|Rusi su ubili te naciste...
{112788}{112861}...i njihove jebene žene.
{112868}{112983}Ali ostavili su nacistièke štetoèine|da još uvijek mrdaju ovom zemljom.
{112989}{113046}Svi njihovi simpatizeri|su trebali biti javno...
{113050}{113117}...silovani i kastrirani.|Natjerani da pate.
{113123}{113177}Amerikanci su toliko|razvijeniji od nas.
{113183}{113259}Skoro je gotovo. Želim vidjeti lice|svoga oca. I svoje majke...
{113266}{113383}Ona je bila zla.|Povuci okidaè, èovjeèe.
{113390}{113458}Bila je kurva koja je izdala|Židove i komunjare.
{113464}{113508}Jesi li se ustrtario?|Èesto zlo pobjeðuje.
{113515}{113606}Saèuvat æu zadnji metak za direktora.|Isuse, ja sam dobar.
{113611}{113736}Razapeli su ga i jebeni sveæenici|su ukrali njegov lik.
{113743}{113822}Sve dobro je odavno mrtvo.|Da bi zlo moglo vladati.
{113826}{113892}Ne. Moraš se boriti protiv zla.|Ja sam dobar...
{113898}{113996}...on mora umrijeti, ne ja.|Otac, kæer, pištolj.
{114000}{114058}Svijet je zao,|dobro mora pobijediti.
{114064}{114185}Nema mjesto za èistoæu.|Možda nije mrtva. Dolazim.
{114209}{114264}Bože, volim te.|Ne umireš tako brzo.
{114270}{114343}Pomozi mi pobjeæi iz ovog|smrdljivog sira.
{114349}{114427}Ona se samo pretvara.|Crvi posvuda.
{114433}{114504}Sir nije dovoljan.|Žele moje meso.
{114509}{114584}Crvi u sveæenièkoj odori.|Predobro da bi bilo istinito.
{114591}{114666}Došli su u tvoje ime,|ali lažu.
{114672}{114772}Oni su nacisti.|Zašto sam je ovako unakazio?
{114776}{114859}Zlo je bilo u njima.|Nitko je nikada neæe dodirnuti.
{114866}{114973}Možda joj u mrtvaènici gurnu|prst u pièku.
{114979}{115055}Saèuvat æu metak|da joj raznesem tijelo.
{115060}{115163}Ona je èista. Nastavljam po planu.|Èekat æe me.
{115169}{115243}Cynthia, nisi više zatoèena|u svom tijelu.
{115249}{115297}Prvo ubojstvo je ono|najvažnije.
{115301}{115398}Drži se, i ja dolazim. Možda|me moja prokleta majka takoðer èeka.
{115404}{115472}Bilo bi odlièno da umremo skupa.|Sa Cynthijinom majkom.
{115476}{115542}Mi smo nevini.|Dobro mora vladati.
{115547}{115658}Dolazim, dušo.|Broji do deset. Deset... devet...
{115665}{115754}Ponijet æu našu prošlost i našu ljubav.|Iz svog mozga?
{115759}{115825}Što æe napraviti s mojim mozgom|i mojim kurcem?
{115832}{115884}U mrtvaènici æe ih narezati|i staviti u staklenku.
{115891}{115941}Uèinili su nešto sa ovom sobom.
{115947}{116036}Moraš platiti, èak i za zrak,|ili æe te gušiti do smrti.
{116043}{116135}Smrt mora biti dobra. Nemam|dovoljno metaka za sve.
{116142}{116247}Ili sam ja, ili oni,|pa ipak idem ja.
{116251}{116306}Cynthia me èeka, ionako.
{116311}{116423}Da, dušo, èekaj. Sedam, šest...|Ali vratit æemo se.
{116429}{116545}I ja æu biti predsjednik.|I vladati Francuskom.
{116549}{116633}I sve æu ih izjebati.|Neæe mi pobjeæi.
{116639}{116695}Crveni gumb. I praznina.
{116699}{116815}Sve što æe dobiti bit æe komadiæi mozga.|Došlo je vrijeme.
{116822}{116863}Sve je gotovo.
{117348}{117436}Ne, to sam ja.|To je moja glava.
{117467}{117514}Ne, ne bih trebao ovo napraviti.
{117536}{117599}Ja sam dobra osoba i|tako bi trebalo i ostati.
{117663}{117717}Èudno, kako uvijek izvisim.
{117723}{117814}Moje roðenje, moja mladost,|ljubav, moj duæan.
{117831}{117898}Nikada nisam trebao biti roðen.|Nikada.
{117909}{117951}Nikada.
{117967}{118100}Moj cijeli život je pogreška.|Sve, osim moje kæeri.
{118149}{118210}Znam što æe se dogoditi.
{118266}{118324}Ovo je samo deja vu.
{118330}{118399}Bio sam ovdje veæ tisuæu puta.
{118451}{118523}Èini se da se sve ponavlja,|ponovno i ponovno.
{118674}{118755}Volim te više od ièega.
{119383}{119442}Ne ostavljaj me.
{122185}{122280}Moral
{123147}{123257}Èovjeèanstvo ima moral.
{124444}{124508}Ne znam kako æe|ovaj dan završiti.
{124521}{124597}Ali tu sam, s tobom.
{124617}{124718}I sretan sam.|Sretniji nego ikada.
{124754}{124806}Ostalo nije važno.
{124816}{124899}Možda je ovo naš zadnji dan,|a možda i nije.
{124905}{124984}Možda se nikada neæu|upucati u glavu.
{124991}{125049}Možda æu spavati s tobom...
{125057}{125116}...i završiti u zatvoru sutra.
{125122}{125180}Èetiri mjeseca, godina, dvije godine.
{125185}{125281}Ma zatvor i nije bio tako loš.
{125286}{125377}I da jest,|uvijek sam se mogao objesiti.
{125410}{125542}Èak i da odem u zatvor, uvijek æu imati|ovaj trenutak da me ohrabri.
{125549}{125668}I zadovoljstvo da sam napravio|ono što sam htio ja, a ne netko drugi.
{125674}{125772}Možda mogu svom životu dati znaèenje,|poslije svega. Štiteæi tebe...
{125776}{125886}...i èineæi te sretnijom|nego što je to itko drugi mogao.
{125893}{126005}Ti si mi kæer.|I ja æu te uèiniti... ženom.
{126065}{126144}Napravit æemo to.|I budi sretna.
{126149}{126199}Bit æe to naša mala tajna.
{126249}{126361}Napravimo to ili ne,|èovjeèanstvo se neæe promijeniti.
{126371}{126452}Ali za tebe i mene|to znaèi potpunu promjenu.
{126458}{126546}Ljudi misle da su slobodni.|Ali sloboda ne postoji.
{126551}{126652}Samo zakoni koje su nepoznati ljudi|donijeli da bi se zaštitili...
{126658}{126723}...što iskljuèuje mene i moju tugu.
{126726}{126823}Jedan od tih zakona kaže|da te ne smijem voljeti...
{126829}{126895}...jer si mi kæer.|Zašto?
{126899}{126994}Kladim se da to ne zabranjuju zato što|je to nešto neispravno...
{126999}{127059}...nego zato što je previše jako.
{127304}{127379}U našem sluèaju, nema drugog izbora.
{127441}{127477}Volim tebe.
{127495}{127552}I ništa drugo.
{128200}{128666}PREVOD I OBRADA|ÈEDO FILM - by Lucifer
