{601}{655} NEOBIÈNI  ODNOSI  
{710}{770}igraju:
{1410}{1520}Osjeæam se... kao da nestajem.
{1540}{1705}U zrcalu moj odraz | postaje sve bljeði.
{1705}{1783}Bojim se da moje stvarno | ja, ono od nekoæ, nestaje.
{1784}{1897}Moj me muž više ne primjeæuje. | Èak i kad smo u istoj sobi. 
{1935}{2026}Želi da poènem nositi | zavodljivo rublje. Mislim...
{2106}{2196}Bože. Prošlo je vrijeme.
{2207}{2375}Da završim misao? -Ne bi bilo | pošteno prema iduæem pacijentu.
{2378}{2461}Nastavit æemo iduæi tjedan.
{2469}{2557}Ako dotad potpuno ne | nestanem. -Koncentrirajte se.
{2590}{2670}Je li g. Simon veæ došao? Dobro. | -Niste valjda opet zaspali?
{2671}{2806}Kava bez kofeina. Skuhaj mi | obiènu. Poèinjemo za 10 minuta.
{2882}{2940}Bože. Probudi se!
{3313}{3430}Ovo nije u redu. U ovoj èaši | nema nièega. Jesi primijetio?
{3444}{3480}Nemojmo da se to ponovi.
{3625}{3767}Nisam znao da si tu. | Rekli su mi da si otputovala. -Bog!
{3767}{3920}Napokon. -Propisno kasnim. | -I to ti je onda najstariji prijatelj.
{3920}{4010}A ne najbolji? -Najstariji | ukljuèuje najbolji. -Nikako.
{4018}{4116}Je li bolje biti najstariji | ili najbolji? -Imaš pravo.
{4119}{4250}Najstariji ili najbolji penis? | -Idemo na piæe. Shvatili smo.
{4260}{4290}Èudak.
{4411}{4470}Odliène su. Kušaj.
{4492}{4606}Zaboravio sam da smo svi kužni. | -Oprosti što držim do higijene.
{4613}{4760}Što to imamo? -Tvoja je zabava. | Ne znaš? -Ostat æe na doruèku.
{4824}{4909}Što misliš? -Rane tridesete.
{4925}{5060}Previše troši na kosu i nokte. | Uložila je mnogo novca u grudi.
{5066}{5180}Dobra investicija. -Slažem se. | -Udana? -Mislim da nije.
{5187}{5240}Želi seks, ali ne i vezu.
{5248}{5390}Želi samo imati muškarca. | -I tu uskaèeš ti. -Tako nekako.
{5399}{5503}Da sam barem plitak kao ti! -To | zahtijeva mnogo truda. Oprosti.
{5600}{5720}Razmišljao sam kako dajete mojim | snovima homoseksualni znaèaj.
{5731}{5770}Koji oni nemaju.
{5800}{5874}Dobro, mi je život dosadan. | Onkologija je dosadna.
{5893}{5935}Vaše su me rijeèi uznemirile,
{5984}{6040}ali me još više | uznemiruje kad mi zaspite!
{6075}{6140}O, Bože. Žao mi je.
{6196}{6310}Ne znam... -Naspavajte se! | -Sasvim sam odmoran.
{6317}{6423}Ali ne mogu ostati budan. -Ja ne | zaspim s pacijentima. -Suludo.
{6428}{6514}Svako malo dremnem. | Uopæe nemam energije.
{6549}{6579}Smršavili ste?
{6630}{6660}Da, malo.
{6711}{6799}Imate li temperaturu? Ustanite!
{6822}{6866}Što? -Dajte, ustanite.
{6913}{7040}Ovime sigurno kršimo pravila | odnosa lijeènika i pacijenta.
{7114}{7144}Slezena je proširena.
{7175}{7280}Želim vas pregledati. | Doðite do mene poslije posla.
{7286}{7376}Danas? Ne mogu. Imam | važnu stvar u 3 sata. -Otkažite ju!
{7527}{7621}Bolje je da ne bude sam. | -Hvala što ste me nazvali.
{7638}{7685}Napravit æete još pretraga?
{7729}{7850}Vaš je rak aktivan i | na žalost prilièno agresivan.
{7920}{7985}Injekcije interferona | æe ga usporiti.
{7991}{8081}No zaustaviti ga može samo... | -Presaðivanje koštane srži.
{8142}{8236}Bez presaðivanja | æu umrijeti. -Da.
{8273}{8348}Jednojajèani blizanci | najbolji su davaoci.
{8354}{8466}Braæa i sestre odmah su | poslije njih. -Nemam ih.
{8475}{8625}Jedinac je. Mama mu je još živa. | -Roditelji su loši davatelji.
{8626}{8699}Pogledajte ovo. | Pokazat æu vam nešto.
{8772}{8913}Oèeva i majèina krvna linija. | Dvije razlièite krvne linije.
{8948}{9040}Djeca su mješavina obje linije.
{9044}{9170}Zato su braæa i sestre najbolji | davatelji. -Rekao sam, nemam ih.
{9175}{9280}Što æemo dalje? | -Nasumice æemo tražiti? -Da.
{9281}{9400}Uæi æete u program. -Kakvi su | mi izgledi? -Optimistièni smo.
{9402}{9508}Uèinite mi uslugu. Nemojte mi | mazati oèi. Budite kolegijalni.
{9548}{9680}Dobro. Nasumiènim traženjem | imate 35% izgleda.
{9764}{9875}To je prilièno dobro. -Gdje? | Gdje je to dobro? U Vegasu?
{9885}{9985}Rekao mi je da æu umrijeti. | Sviðaju ti se izgledi? Izvoli.
{10346}{10387}Tajming ti je loš.
{10402}{10533}Imam karte za filharmoniju i | kasnim. -Zdravo. I meni je drago.
{10538}{10611}Bez puse. Našminkala | sam se. Donesi mi rukavice.
{10649}{10786}Možeš sjesti na minutu? | -Jerry, auto me èeka dolje.
{10790}{10874}Sekundu. -Da nisam u Ženskom | odboru... -Imam leukemiju.
{10951}{10981}O, Bože.
{11182}{11285}Martini? -Radila | sam ih tvom ocu.
{11288}{11383}Govorio je da umrtvljuju bol. | -Zbog mene sad i piješ.
{11404}{11473}Molim te, sjedni.
{11705}{11795}Nikad me nisu optužili | da sam puna ljubavi.
{11801}{11910}Znam da sam | hladna osoba, ali...
{11967}{12006}Znaš da te volim.
{12048}{12150}I da bih preuzela | taj odurni rak
{12154}{12226}u svoje tijelo kad bih | ga mogla izvuæi iz tvoga.
{12280}{12388}Jer ja sam ti majka. | Bog to zna.
{12391}{12462}Bog zna da sam ti majka.
{12537}{12567}Ali ono što nisam...
{12623}{12660}Moj predivni sine...
{12710}{12752}Nisam tvoja biološka majka.
{12890}{12970}Imala sam brojne pobaèaje.
{12981}{13077}Tvoj otac je prihvatio | posao u Engleskoj.
{13102}{13190}Napokon smo te | našli u Liverpoolu.
{13208}{13301}Posvojili smo te dva | dana nakon što si se rodio.
{13304}{13397}A rodila te mlada | katolkinja Sheila.
{13415}{13536}Sheila Burton. Ne sjeæam se | imena mladiæa koji ti je otac.
{13561}{13650}Žao mi je. | Doista mi je žao.
{13717}{13840}Èovjek ne bi smio zaboraviti | takvo što. Nešto tako važno.
{13863}{13993}Ne, nisam ljut, ali mi ide na živce | da su lagali. Ne mogu vjerovati.
{13999}{14120}Imali su razlog. -Koji? | Da od mene naprave budalu?
{14145}{14223}Sve što sam mislio | da jesam, zapravo nisam.
{14226}{14333}Nisam pljunuti otac, | nisam Amerikanac.
{14372}{14481}Nisam ni Židov. -Obojica | znamo da to nije bogzna što.
{14523}{14637}Nisam ni lijeènik. Èovjek bi | oèekivao da se znam ubosti.
{14804}{14920}Zašto ne tražiš davatelja? | -Daj mi košulju. Èistu košulju.
{14925}{15050}Zašto ne tražiš majku? -Javili | smo se engleskim službama.
{15051}{15176}Šalju nam... -Veæ tjedan dana! | Bojiš se? -Èega? -Da je naðeš.
{15182}{15295}Zašto ne sjedneš u avion i odeš | je tražiti? -Zašto ne zavežeš?
{15298}{15400}Ti zaveži, | tvrdoglava mazgo! Umireš!
{15449}{15479}Samo mi daj košulju.
{15615}{15725}Koje boje? -Dr. Lipman ima | zakonsko pravo na podatke o svom roðenju
{15726}{15860}pohranjene kod vas. Poslali smo | vam dokumente koje ste tražili.
{15862}{15898}Ti vam nisu dovoljni?
{15938}{16066}Molim? Zatvarate? | Kakav vi to posao vodite?
{16074}{16147}Gðo Brailsford, dr. Lipman.
{16200}{16336}Dobro. Možete li na | trenutak zašutjeti? Hvala.
{16341}{16475}Neæete vjerovati, no nisam glup. | Svjestan sam vremenske razlike.
{16475}{16595}Ako je ovdje u New Yorku 12 sati, | u Liverpoolu je srednji vijek.
{16598}{16706}Dosta mi je tih | gluposti o ovjerama,
{16709}{16820}naknadama i službeni | potvrdama u tri primjerka.
{16820}{16905}Sit sam vaših | birokratskih gluposti.
{16906}{17036}Imate komad papira koji trebam. | Jeste li kad èuli za faks?
{17052}{17082}Gðo Brailsford?
{18398}{18460}Broj 173, na šalter 6, molim.
{18559}{18650}173? -Zdravo. -Gospodin...
{18650}{18790}Oprostite, dr. Lipman. Dr. Jerry | Lipman. -Da. -Idi na èaj, Gwen.
{18851}{18940}Dr. Lipman, ja sam | gða Ruth Brailsford.
{19047}{19170}Drago mi je, gðo Brailsford. | Loše smo poèeli preko telefona.
{19178}{19358}Isprièavam se. -Pustite. Samo | budite pristojni, inaèe letite.
{19364}{19452}Jasno? -Jasno. Zaslužio sam.
{19520}{19650}Dobro. Obišao sam sve ljude | s popisa koji sam jutros dobio.
{19685}{19771}Imam sve papire. Svi su | potpisani. Mislim da je sve tu.
{19822}{19865}Zgrada je veæa nego se èini.
{19903}{19933}Ima mnogo katova.
{19994}{20070}Èudim se da nema lift. Dizalo.
{20125}{20270}Dobro. Dajte mi još vozaèku, | putovnicu i zdravstvenu.
{20321}{20431}Sve ono što sam pokazao | vašem kolegi prije 3 i pol sata?
{20492}{20553}Jer ovo su isti dokumenti.
{20723}{20764}Èini se da je sve u redu.
{20849}{20916}Imamo mnogo posla.
{20920}{21053}Javite se za tjedan dana. Reæi | æemo vam koliko æe potrajati.
{21056}{21198}Ne, ne ne. To nije | pošteno. -Vièete na mene?
{21202}{21341}Zašto mislite da bih došao | iz Amerike po tu informaciju?
{21368}{21398}Zašto?
{21429}{21546}Što mislite? Za patetièni susret | obitelji u nekom talk-showu?
{21610}{21646}Imam leukemiju.
{21661}{21794}Ako ne naðem davatelja | koštane srži, umrijet æu.
{21837}{21925}Ako mi ne date dokumente | o roðenju i posvajanju,
{21928}{22065}leæi æu ovdje ispred svih tih | ljudi i umrijeti vama na pragu.
{22069}{22145}I zato mi dajte te | vražje papire, molim vas.
{23665}{23740}Toxteth, majko. Toxteth.
{23761}{23899}Spoj rijeèi "toxic" i "death". | -Kažeš slam? -Gore od toga.
{23902}{24021}Vidio si je? -Mislim. Nisam | siguran. Mislim da je ona.
{24028}{24107}Kako izgleda? -Ovako.
{24109}{24240}Kao ja, no ružnija, deblja i | blajhana, u najlonskoj haljini.
{24240}{24330}I s cigaretom na usni. Stvorila | si sliku? -Sigurno se bojiš.
{24331}{24460}Uvijek si okrutan kad se | bojiš. -Ne znam koji mi je plan.
{24462}{24560}Što da joj kažem? -Zašto joj | ne kažeš istinu? -Zašto nisi ti?
{24613}{24716}O, dušo. Jako se bojiš. | -Žao mi je. Znaš...
{24750}{24848}Ja veæ imam mamu. Ne želim | da ovo ikako... -Slušaj me.
{24850}{24980}Uvijek æu te jednako voljeti. | Majka sam ti i želim da živiš.
{24981}{25105}Otiði k njoj i budi | ljubazan. I poèešljaj se.
{25942}{26025}Isus ili Jehova? -Što?
{26028}{26084}Jeste li mormon ili svjedok?
{26134}{26266}Ništa. Tražim | Sheilu Burton. -Žao mi je.
{26270}{26380}Ne živi tu. -Tako se prezivala | kao cura. Sad je Fitzpatrick.
{26411}{26500}Fitz kako? -Fitzpatrick.
{26502}{26606}O, Fitzpatrick! Da, | to je Sheila. -Dobro.
{26633}{26707}Sheile trenutaèno nema. | Ostavite ime i telefonski broj.
{26739}{26845}Ne, u redu je. Doæi | æu opet, ako smijem.
{26845}{26931}Èekajte, što da joj kažem? | Tko ju je tražio?
{26961}{26991}Njezin sin.
{27052}{27082}Što?
{27143}{27260}Imam razloga | vjerovati da sam sin
{27264}{27340}kojeg je ona, kojeg ste | vi, dali na posvajanje.
{27420}{27520}Molim? Ne znam | o èemu govorite.
{27546}{27678}Imam... -Pustite to. Odlazite. | Ne znam o èemu govorite.
{27730}{27825}Oprostite. Mau...
{27833}{27955}Polako! -Što to radite? -Srušila se! | Trebam hladan mokar ruènik.
{27959}{28107}Hladan mokar ruènik! Odmah! | Polako. Duboko udahnite.
{28395}{28425}Osjeæam se tako glupo.
{28476}{28550}Neugodno mi je. | Napraviti takvu scenu.
{28582}{28660}Ali pojavio si | se iz... -Kvragu.
{28753}{28840}Znaèi, istina je. -Da, dušo.
{28889}{28919}Bojim se da jest.
{29040}{29070}Imala sam 16 godina.
{29126}{29156}Živjela sam s roditeljima.
{29197}{29250}Danny je bio uz mene.
{29308}{29420}Nismo imali novca. I nismo bili | vjenèani, što je tada bio grijeh.
{29424}{29601}Nismo znali što æemo. Mislili | smo, najbolje je da te damo...
{29625}{29735}Damo ti priliku. Da te damo | nekome tko æe se brinuti za tebe.
{29801}{29831}To smo i uèinili.
{29932}{30005}Vrijeme je za kolo sreæe.
{30133}{30163}Dobro.
{30209}{30360}Danny i ja vjenèali smo | se poslije nekoliko godina.
{30385}{30514}I imamo dva djeèaka. | Tvoju braæu. -Još dva?
{30536}{30640}Sjajno! -Frank je dobar.
{30642}{30753}Derek je grozan, ako se mene | pita. -Ona se udala za njega.
{30753}{30890}Jer sam morala. No brzo | sam se rastala. -Ma daj.
{30894}{31007}Pa nije baš tako loš. -Nije | se pojavio na pokopu vlastita oca.
{31015}{31122}Mrtav je? Moj je otac mrtav? | -Žao mi je. Htjela sam polako.
{31141}{31225}Dok nekomu nije | izletjelo. -Žao mi je.
{31227}{31377}Derek nije došao jer je bio | shrvan boli. -Misliš, drogom?
{31408}{31565}Postoje li slike mog oca? | -Da. Maureen, slike, molim.
{31754}{31880}Uvijek govorimo da æemo ih | staviti u album. -Bog, mama!
{31885}{31957}Djeco! -Maureenina djeca.
{32021}{32062}Anthony i Emma.
{32142}{32249}Ovo je vaš novi | stric. Stric Jerry. -Bog.
{32268}{32360}Novi stric? | Odakle se stvorio?
{32399}{32510}Izašao je iz bakinog trbuha | kao tvoj tata i stric Frank.
{32525}{32650}Braæa su. No nitko | nije znao za njega
{32651}{32775}jer je Jerry bio moje | tajno dijete. -Gdje je bio?
{32782}{32900}Zaboravila si ga? -Koliko | imaš godina, strièe Jerry?
{32908}{32975}29. srpnja imat æe 40 godina.
{33184}{33285}Znaèi, ovo je Frank? | -To je Frank, da. -Dobro.
{33310}{33404}Tetka Vi? -Jako dobro.
{33450}{33593}To je sigurno Derek. -To je | Derek s neæakinjom. -Derek.
{33632}{33773}Ujak? Ujak Albert. Alfred? | Ujak Alfred? -Baš taj.
{33808}{33900}A ovo je Dennis. Ovo je | moj tata. -Tako je, tvoj tata.
{33904}{34009}Da nije bio Židov? | -S prezimenom Fitzpatrick?
{34080}{34226}Nisam ni mislio. -Zar si Židov? | -Da. Mislio sam da jesam.
{34231}{34379}Ma da? Vidi vraga! Kako je | to? -To je drugaèije, zar ne?
{34387}{34442}Reci nam nešto o sebi.
{34513}{34640}Moj otac, moj drugi otac, David, | umro je prije 10 godina.
{34654}{34800}No moja majka, moja pomajka, | Ester, zdrava je ko drijen.
{34830}{34934}Jedinac sam. Odnosno. | bio sam sve do danas.
{35006}{35040}I živim u New Yorku.
{35052}{35152}Ondje sam odrastao i završio | medicinu. -Nisi valjda lijeènik?
{35158}{35260}Jesam. Psihijatar. -O, Bože.
{35264}{35417}Sigurno misliš da smo ludi. | -Ne, s vam je sve u redu.
{35420}{35470}Bacimo se na jelo. | Sigurno si gladan.
{35521}{35563}Joj, vidi, vidi.
{35592}{35680}Izvoli, dušo. Navali.
{35793}{35823}Svidjet æe ti se.
{35879}{35966}To je saveloy. -Saveloy.
{35985}{36015}Saveloy.
{36146}{36176}Joj!
{36202}{36254}Imate li salvetu?
{36258}{36331}Daj krpu! Nismo neuglaðene.
{36675}{36740}Vratit æu se. Odmah ujutro.
{37545}{37647}Što misliš, zašto je došao? -Pa | nije li oèito? Zbog mog novca.
{37686}{37773}Mislim da nešto | želi. -Želi obitelj.
{37777}{37892}Oborio te s nogu, | Ginger Rogers. Pogledaj se.
{37908}{38050}Nije oženjen. Da nije homiæ? | -Vidjela si kako drži kobasicu.
{38134}{38200}Lijeènik! Možeš vjerovati? -Da.
{38235}{38333}Budeš li pametna, izvuæi æeš | još i perilicu. -Užasna si!
{38360}{38427}Više bi mi odgovarao hladnjak.
{38497}{38610}Zgodan je, | zar ne? -Da. Nije loš.
{38638}{38668}Popijmo èaj.
{38729}{38870}Braæa. Da, množina. Dva. | -Jedan ti sigurno odgovara.
{38870}{39000}Valjda. -A pretrage? -Nisam im | još rekao. Moram se ulagivati.
{39001}{39135}Zar si na odmoru ondje? -Nije | lako. Moram biti jako oprezan.
{39137}{39273}Reci im da radiš pretrage za | kravlje ludilo. -Baš. -Kakvi su?
{39278}{39411}Neæeš vjerovati. Živi u | kartonskoj kutiji na smetlištu
{39414}{39500}s dvoje unuèadi i snahom
{39500}{39612}koja me ponudila masnom | kobasicom što sja u mraku.
{39626}{39691}Kao da si zagrizao u infarkt.
{39697}{39740}Dolazi ovamo, huligane!
{39743}{39903}Gurneš li još nešto sestri u | nos, odalamit æu te štapom!
{39914}{39978}Jesi li me èuo? | Jesi li me èuo!
{40000}{40059}Zdravo... Uði.
{40206}{40320}Došao je stric Jerry. -Bog, | strièe Jerry. -Proði, Jerry.
{40347}{40462}Hajde, doði. Raskomoti se. | Svi se inaèe raskomote.
{40540}{40690}Što je ovo? Ostaci kaše. Hoæeš | tanjur? -Ne, jeo sam u hotelu.
{40834}{40952}Baka kaže da radiš s luðacima. | -Imaš kojeg masovnog ubojicu?
{40970}{41043}Mama kaže da lijeèiš ljude | kojima nije dobro u glavi.
{41046}{41167}Da poradim na | njemu? -Imaš gnjide!
{41187}{41285}Ne budi bezobrazan! Van iz moje | kuhinje dok se ne upristojite!
{41293}{41393}Kad ste zadnji put oprali | trule zube? Sad ih operite!
{41474}{41557}Kao dvoje štenaca koji | njuškaju oko pseæe stražnjice.
{41600}{41707}Polaskan sam. -Jerry, zaboravila | sam reæi. Nazvala sam Franka.
{41711}{41848}Ima slobodan dan. Hoæeš ga | vidjeti? -Da! Da! Može. Da.
{41907}{41950}Bog, strièe Jerry!
{41993}{42091}Posebni su, zar ne? | Sve su mi na svijetu.
{42135}{42251}Dobro. Idemo onda do Franka. | Gdje je on? -U Broad Greenu.
{42260}{42375}Pokazat æemo mu znamenitosti. | -Može. -Nisam baš taj tip.
{42516}{42643}Vidiš ovu zgradu slijeva? -Da. | -To je protestantska katedrala.
{42647}{42787}Još je grade. Ima sto godina. Ljudi | su na njoj doèekali mirovinu.
{42788}{42895}Neka naðu mlaðe ljude. -Našu | su gradili nekoliko tjedana.
{42899}{43002}Evo je. Katolièka katedrala. | Zovu je Paddyjev wigwam.
{43015}{43126}Protestanti se svojom osveæuju | katolicima. -Pogledaj desno.
{43131}{43265}Vidiš što je to, Jerry? Žuta | podmornica. Znaš zašto je tu?
{43267}{43317}Naravno. -Zbog Ringove pjesme.
{43323}{43470}Evo veoma važne zgrade. | Zove se Liver Building.
{43489}{43635}Liver kao Liverpool. -Zašto | se drukèije izgovara?|-Nisam o tom razmišljala.
{43705}{43810}Stani! Ovdje stani, Jerry. -Jesi | dobro? -Da, samo želim stati.
{43926}{43974}Ovdje si roðen, dušo.
{44032}{44120}Ovdje? -O, Bože. Da. | Ovdje je bila Ženska bolnica.
{44153}{44200}Tu sam te izgubila.
{44349}{44487}Nisi imao pojma, zar ne? | -Nisam. -Ne. Ali sve je istina.
{44505}{44642}I ne samo to. Nakon 39 | godina ovdje je veèeras.
{44651}{44681}Iznenaðenje.
{44782}{44896}Brat za kojeg nisi ni znao | da ga imaš. Uði, Jerry.
{45098}{45128}Drago mi je.
{45210}{45240}Jerry.
{45340}{45432}Ovo je moja žena | Mavis. -Zdravo. -Zdravo.
{45476}{45572}Jeste li za šaum role? | Otvorila sam kutiju.
{45577}{45684}Ondje je soba za goste. | Vidiš ove željezne ukrase?
{45688}{45815}Sam sam ih radio. Ponosan sam | na njih. Ondje je ventilacija.
{45829}{45928}Gore je bojler. | Dvaput sam obložio cijevi.
{45930}{46061}Ne zanima ga glupi bojler! | -Ne! Zanima me Frank, zaista.
{46116}{46161}Osjeæaj se kao kod kuæe, Jerry.
{46167}{46299}Što je moje, tvoje je. -Frank, | nemam smrznutog graška! -Evo me.
{46478}{46508}Evo ga.
{46614}{46644}Bog, tata.
{46725}{46825}Svidio bi ti se. Ljudi | su ga uglavnom voljeli.
{46866}{46902}Sigurno bih i ja.
{46967}{47055}Dolazim jednom na | tjedan da oèistim.
{47073}{47191}A Derek? Dolazi li | on ikad? -Taj huligan?
{47194}{47323}Totalni škart. Skuplja èikove | i živi s droljom u Bootleu.
{47330}{47360}Oboje su navuèeni na hors.
{47426}{47504}Nemam pojma što si rekao, | ali nije zvuèalo laskavo.
{47562}{47636}Možeš li me | odvesti do Dereka? -Ne.
{47668}{47785}Ne bi dobro prošlo kod | kuæe. -Kod kuæe? -Mavis.
{47834}{47962}No mogu mu javiti. | -Da? Rado bih ga posjetio.
{47975}{48100}Volio bih i tebe bolje upoznati. | Možda bismo mogli na veèeru.
{48106}{48223}I zabaviti se. -Kao momaèka | veèer sa striptizetama?
{48227}{48311}Može. I te kako. Godinama | si to nisam priuštio.
{48378}{48441}Mavis te zauzdala, zar ne?
{48539}{48590}Idemo po smrznuti grašak.
{48900}{49030}Dobro si? -Da. | Samo ti idi. Zov prirode.
{49206}{49305}Bog. Pazi kako voziš. | -Ta Mavis je oštrokondža.
{49307}{49440}Stalno kvoca Franku. | Dobro. Idemo prvo po djecu.
{49443}{49550}Pa do hotela po tvoje stvari. | Ostaješ kod nas. -Ne, ovako...
{49559}{49690}Moje dijete neæe spavati u | hladnom hotelu! Ne dopuštam.
{49690}{49723}Možeš spavati u mom krevetu.
{49866}{49966}Howie, možeš li mi naæi | dobrog onkologa u Liverpoolu?
{49967}{50080}Da, najboljeg. Zašto? Što se | dogaða? -Poèeo sam povraæati.
{50083}{50183}Ne znam je li kriv rak ili | boravak u ovoj kuæi. Sve...
{50184}{50278}Sve je tako malo, | jeftino i raspada se.
{50305}{50411}Možeš malo glasnije? -Ne, tu su | na dva metra, -U istoj ste sobi?
{50411}{50535}Ne, na drugom su kraju kuæe. | -Èekaj malo. Bolestan si.
{50537}{50714}Povraæaš, a živiš u kutiji za | kruh? Neobièan naèin života.
{50825}{50910}Halo? -Dobro. Oprosti.
{50934}{50995}Naæi æu ti onkologa za 24 sata.
{51515}{51655}Što radite u mom krevetu? | -Baka se rita. -Ritaj i ti nju.
{51655}{51790}Ne dolazi k meni. -Ti si topao, | strièe. -Nisam vam ja termofor.
{51790}{51895}Idite spavati u svoj krevet. | -Ovo je naš krevet. -Da.
{52113}{52184}Jerry? -Da? -Oprosti dušo.
{52224}{52259}Što je sve to?
{52300}{52402}Moji vitamini. Hipohondar sam.
{52451}{52507}Sva sreæa da si lijeènik.
{52517}{52650}Želim da se ti, ja i Maureen | veèeras naðemo u ovom lokalu.
{52658}{52742}U 6:30. Nemoj da ne doðeš.
{53440}{53590}Dobro došao, sine. Ovo su | sve naši prijatelji i obitelj.
{53605}{53635}Ovdje su kako bi te upoznali.
{53701}{53833}Neugodno mi je. -Znam. Samo | se brzo napij. -Jedva govorim.
{53867}{53930}Srce mi je zapelo u grlu.
{53938}{54091}Želim da svi prijatelji, cijela | obitelj i cijeli svijet znaju
{54094}{54230}da je djeèak kojeg sam | lakoumno dala prije 39 godina
{54255}{54359}našao svoj put natrag. | Poput bumeranga.
{54386}{54499}Voðen božjom rukom. | Ne bih više odugovlaèila.
{54527}{54645}Molim da zaželite toplu | dobrodošlicu mom sinu.
{54658}{54720}Dr. Jerryju Lipmanu!
{55074}{55140}Do kraja veèeri | pijete na moj raèun.
{55220}{55325}Drago mi je što sam te upoznala, | momèe. -I meni, tetko Vi.
{55355}{55400}Bog. -Vidimo se. -Bog.
{55422}{55540}Zašto nosi selotejp? -Mama kaže | da je to jeftino zatezanje lica.
{55543}{55660}Tužno je to. | Selotejpom zateže bore.
{55674}{55790}A kad ga skine? -Obrazi | joj vise ispod sisa. -Tiho.
{55905}{55965}Hvala, strièe Jerry. -Hvala.
{55971}{56102}Evo ujaka Alfreda. Sad æeš se | naslušati. Idemo, djeco. -Ide?
{56142}{56240}Sheila kaže da si uspio | u New Yorku? -Jesam.
{56258}{56396}Sheilin ujak Peter, moj | brat, uspio je u Australiji. 
{56404}{56513}Koja, èini se, nije daleko od | tvog grada. -Nije jako daleko.
{56515}{56620}Dobro mu ide. Ima 2 ili | 3 puba. Lijepo zaraðuje.
{56621}{56740}Australci su skloni pivu. | -Više nego psihijatriji.
{56742}{56840}Okušao se i u tom. No shvatio | je da pivo nosi bolju zaradu.
{56960}{57021}Jeste li vidjeli Dereka? -Nismo.
{57044}{57160}Uèinite mi uslugu. Vidite li ga, | neka me nazove. Važno je.
{57160}{57287}Hvala. Cijenio bih to, -Hej, ti. | Nisi plesao na vlastitoj zabavi.
{57916}{58000}Što se dogodilo? -Ništa.
{58087}{58230}Samo sam pozdravio Maureninu | prijateljicu. Mavis je pošizila.
{58253}{58305}Sad æe se danima ljutiti.
{58344}{58450}Ne znam, Jerry. Sigurno sam | ja kriv. -Prestani se kriviti.
{58450}{58505}Neprestano se | razoèarava u meni.
{58546}{58610}Rekla je da razmišlja o rastavi.
{58680}{58730}Što ako...
{58738}{58868}iza svega stoji zdravstveni | problem? -Zdravstveni?
{58894}{58964}Mislim da patiš od | klinièke depresije.
{58985}{59100}Možda je kemijska neravnoteža | ili pomanjkanje vitamina.
{59101}{59216}Da imam nalaz krvi, znao bih | više. -Da idem na pretrage?
{59227}{59340}Trebao bi. Nitko neæe znati,| to bi bila naša tajna. -Deèki.
{59345}{59383}Ujaèe Alfred.
{59524}{59637}Kip slobode još je ondje? | -Nije, prodan je Disney Worldu.
{59650}{59754}Prevezli su ga na Floridu i | pretvorili u vodeni tobogan.
{59786}{59877}K vragu sve. Tipièno za | Amere. Ništa im nije sveto.
{59902}{60032}Samo je važan dolar i... | -Centi. -Nemaju trunke pameti.
{60053}{60200}Svi se smiješite, za ime Boga! | Smiješite se. Ne tražim mnogo.
{60204}{60315}Samo obiteljsku sliku. Ovo je | zadnja prilika. -Gdje je Derek?
{60315}{60388}Ima posla. | -S prostitutkama?
{60506}{60642}Idemo. Baka vas vodi u školu. | -Želimo da nas vodi stric Jerry.
{60647}{60760}Bojim se da ništa od toga danas. | -Stric Jerry se ne osjeæa dobro.
{60763}{60897}Još je pijan od sinoæ. | -Dosta. -Ajoj! -Van. Idemo.
{60904}{61035}Dohvatit æu te. -Operi zube. | -Majmunèiæu. Brže trèi.
{61660}{61733}Vidimo se, Jerry. | -Èekaj! Èekaj!
{61761}{61878}Odvest æu te na posao. -Sjest æu | na autobus. -Zrak æe mi goditi.
{61887}{61938}Zrak? U Liverpoolu si.
{62018}{62048}Mrzim kad to radiš!
{62139}{62273}Dr. Livingston, pretpostavljam. | -Derek? Ja sam Jerry. -Znam.
{62290}{62394}Bog. -Bog. Izvoli. | Donio sam ti darak.
{62426}{62467}Baš lijepo. Majica.
{62517}{62654}Liverpool! -Ti prljava, užasna | protuho! Tvoja je! -Naravno!
{62663}{62802}Htio sam mu dati nešto svoje. | I zašto sam saznao od stranaca?
{62804}{62865}Jesi li donio kakav dar | djeci? U obliku novca?
{62870}{63030}Ne ide mi. Èinim što mogu. | -Ništa. -Zato sam je ostavio.
{63031}{63116}Ti mene? Ja sam tebe | izbacila, skote! -On je skot.
{63272}{63340}Jerry, kompa. | Vodim te na pivo.
{63343}{63475}Neæe tako rano lokati s tobom. | Rekao si da me voziš na posao.
{63479}{63595}Imamo auto? Sjajno. -Obojica te | možemo odvesti na posao. -Da.
{63600}{63698}Nema problema. A poslije te | vodim u Great Eastern. -Super!
{63701}{63778}Obojica se nosite! Radije | bih na posao na koljenima!
{63835}{63915}Maureen je prava kuja. | Odvratila je djecu od mene.
{63953}{64040}Moraš priznati da je dobra | majka. -Vraga je dobra majka.
{64044}{64150}Ostavi djecu Sheili, pa | okolo lovi mlade deèke. -Da?
{64185}{64337}I taj Frank. Dosadnjakoviæ. -I s | njim imaš problema? -Sebièan je.
{64356}{64443}Taj ti ne bi dao ni blato | ispod noktiju. Ma kakvi.
{64467}{64521}Nitko se nikada nije | založio za Dereka.
{64555}{64635}Nikad mi nisu pomogli. Nitko.
{64699}{64834}Èak ni mama. -Sheila? Teško | mi je u to povjerovati. -Vjeruj.
{64845}{64965}Ne zalaži se za nju. Ne poznaješ | ju. Krivim mamu više od ostalih.
{64966}{65096}Za? -Prije 10 godina mamin bogati | ujak... -Ujak Peter? -Peter.
{65102}{65260}Nudio je put u... -Australiju. | -Hoæeš nastaviti? -Samo ti daj.
{65263}{65410}Ujak Peter se obogatio nizom | pivnica. No mama je odbila.
{65414}{65540}Nije htjela milostinju od ujaka. | Ponosna je. -Sebièna krava!
{65545}{65650}Zbog nje sam ovakav. Od mene | je moglo biti nešto u Australiji.
{65666}{65727}Mogao sam se razviti.
{65762}{65863}Zašto nisi iskoristio | svoje oèite potencijale?
{65938}{66054}Vjerujem pogrešnim ljudima? | -Možda. No... Znaš što mislim?
{66084}{66226}Imaš kemijsku neravnotežu. | Pomanjkanje magnezija i kalija.
{66230}{66350}Preporodit æeš se uz pravi | lijek. -Tražim ga godinama.
{66361}{66490}Obièna pretraga krvi. Nitko | neæe znati. Naša mala tajna.
{66492}{66620}Pretrage mi ne idu. -Napravi | je. Zaista. Vrlo je jednostavna.
{66623}{66740}Svrati sutra do Sheile. Objasnit | æu ti. Poslije možemo na piæe.
{66814}{66871}Sjajno. -Dogovoreno.
{66885}{67022}Prokleta Nora! Nevolje. -Tko | je Nora? -Vidiš tipa? Ne gledaj!
{67031}{67125}Dugujem mu 40 funta. Ako | me vidi, razbit æe mi glavu.
{67147}{67239}Èekaj, ja æu ti dati | 40 funta. Ovo je suludo.
{67303}{67426}Trideset. Sredi stvari. Evo 50. | Neka se naðe. Igraj na sigurno.
{67489}{67519}Uzmi.
{67575}{67645}Stekao si | doživotnog prijatelja.
{67786}{67829}Bog, deèki. Što pijete?
{67892}{67960}Bok, Jerry. -Frank!
{67988}{68095}Baš mi je drago. -Maureen | mi je rekla da si tu. Kako si?
{68099}{68195}Dobro sam. Dobro. | Gdje ti je ženica?
{68215}{68338}Kod kuæe. Suðe i psovke frcaju | na sve strane. Mojom krivnjom.
{68345}{68454}Nema veze. Ionako je plastièno. | Nema štete. -Nije to dobro.
{68462}{68595}Ni za tebe, ni za nju. | -Možda imaš pravo.
{68633}{68743}Kakvim ti glupostima Derek | puni glavu? -Èavrljamo.
{68754}{68860}Misli da bi bilo drukèije da ga | je Sheila pustila u Australiju.
{68865}{68991}Sad krivi mamu? Lažljivac. Ujak | je svima poslao novac za kartu.
{68996}{69171}Mamin je vraæen. Moj je uložen | u kuæu, a Derekov u nos, vene.
{69171}{69260}U sve. Da je mozak dinamit, | njegov ne bi ni šešir pomaknuo.
{69263}{69370}No spasio me braka s buldogom. | -Pazi, nije to tvoja drolja.
{69370}{69525}Ja uživam kad se moja razmaše | jezikom. -Deèki. -Lupit æu ga!
{69525}{69660}Deèki! -Ne bi mogao oderati ni | kožicu s pudinga. -Ne ljuti se!
{69660}{69770}Šalio sam se. -Jako smiješno. | Ne smijem se. -Dobro je, deèki.
{69772}{69860}Pa braæa smo. Tko je za | još jedno piæe? Ja èastim.
{70173}{70307}Hej. Frank? -Što je? | -Jerry je potkresan. -Da?
{70344}{70460}Vidi ti to. Mi smo | obojica zapušteni. -Dobro. 
{70460}{70564}Što je ovo? Poseban trenutak u | životu? Braæa mi bulje u penis?
{70606}{70725}A da nabavite kabelsku? Teži je | negoli izgleda. -Još jedan kat.
{70727}{70760}Zar živi na krovu?
{70878}{70980}Dobrodošao u zemlju snova. Pazi | gdje staješ i ne diši kroz nos.
{70984}{71055}On ovdje živi? O, Bože.
{71130}{71200}Možeš? -Da. | -Bacimo ga ovamo.
{71211}{71255}Jen, dva, tri.
{71332}{71410}K vragu. Samo spavaj.
{71488}{71580}Nemoj ga žaliti. Svojski se | trudio da bi do ovoga došao.
{71679}{71765}Da pogodim. Ujak | Peter? -Daj da pogledam.
{71820}{71880}Da. U svoj svojoj velièini.
{72151}{72278}Odrastao si. Ne tièe je se... | -Ni tebe se ne tièe što radi.
{72287}{72410}Takva je i gotovo. -Imaš pravo. | Oprosti. Nisam se htio miješati.
{72433}{72587}Oprosti što sam graknuo. Lako | prasnem. Ne mogu se srediti.
{72594}{72714}Frank, to su klasièni | simptomi bipolarnog poremeæaja.
{72740}{72850}Misliš? -Da. Pretrage krvi | dale bi mi potrebne informacije.
{72871}{72966}Mogao bi to obaviti u | pauzi za ruèak. -Dobro.
{72997}{73088}Sutra imam posla u | Manchesteru. Možemo pekosutra.
{73093}{73164}Da, može i prekosutra.
{73269}{73299}Dobro.
{73340}{73443}Vidimo se Jerry. -Dobro. | -Prekosutra. -Nego što.
{73695}{73815}Howarde, ovdje | Houston. Uzlijeæemo.
{73912}{74045}Sheila, gdje su mi košulje? | -Ovdje dolje. Oprala sam ih.
{74058}{74100}Ne, ne. Ne èini to.
{74109}{74180}Rukom su šivane | i ne pere ih se u...
{74310}{74340}Odlièno izgledaju.
{74406}{74545}Miris šumskog voæa. Malo ih | podigne. -Hvala. Nisi trebala.
{74552}{74582}Sjedni i doruèkuj.
{74673}{74703}Dobro jutro.
{74774}{74844}Jesi li se dobro proveo | Derekom? -Jesam.
{74885}{75015}Koliko ti je novca | izmuzao? -Ni penija. Ništa.
{75026}{75180}Ima problema. Htio bih mu | pomoæi. -Kako si samo pažljiv!
{75267}{75390}Kako to da onda imaš | vremena za sve osim za Sheilu?
{75403}{75515}Što to znaèi? -Ne znam. Možda | joj ipak podsvjesno zamjeraš.
{75515}{75643}Što te ostavila. -Nemoj. Ne | izigravaj psihologa amatera.
{75645}{75780}Zaista mi se to ne sviða. | -Pogodila sam u živac? -Nisi.
{75780}{75890}Griješiš. Ne zanemarujem | Sheilu. I, daj, ne gnjavi me.
{75892}{76047}Tek sam saznao da sam posvojen. | -Glup si ili nisi htio znati?
{76053}{76185}Što? -Šutjelo se? Nijedna slika | mame u trudnoæi. Nisi posumnjao?
{76189}{76312}Velik si. Trebao si skopèati. | Svatko odavde veæ bi skopèao.
{76315}{76415}Možda ipak nismo glupi. -Nisam | ni rekao. Kamo æeš? -Na posao!
{76416}{76515}Imam više posranih | poslova? -Dobro, dušo...
{76572}{76680}Vidimo se. -Imam ideju.
{76690}{76835}Idemo nešto raditi zajedno. | Što bi voljela? -Poèistiti kuæu.
{76839}{76965}Moram posušiti rublje, glaèati. | Gore je smetlište. -Pomoæi æu.
{76965}{77097}Želim. Kako mogu pomoæi? | -Ako baš želiš, odvedi djecu van.
{77146}{77212}Ne tako brzo. -Želim | onamo. -Nemoj što slomiti.
{77227}{77268}Ja ti neæu namještati kost.
{77298}{77425}Ujaèe Jerry, gurni nas! -Dobro, | gurnut æu vas. Ali ne prebrzo.
{77449}{77547}Dobro, brzo æemo. Ali ne | prebrzo. Sad æemo iæi malo brže.
{77550}{77630}Pa sporije. Sad sporije, | sad brže. Istodobno.
{77726}{77840}Ujaèe Jery, jesi li | dobro? -Jesam. Samo...
{77862}{77980}Spleo sam se o vlastite noge. | Nevjerojatno. -Siguran si? -Da.
{77983}{78109}Htio sam vas odvesti na slatkiše | i kokice. Šteta što nema kina.
{78114}{78241}Ima. -Ima jedno. -Nema! -Niz | ulicu. -Ma daj! -Odeon. -Da.
{78245}{78313}Što onda još èekamo? Idemo.
{78391}{78526}Neæete. Ja æu imati problema. | -Znaš li koliko je sati? -Da.
{78527}{78672}Sutra imaju školu. Brzo gore. | -Laku noæ, djeco. -Laku noæ.
{78688}{78767}Laku noæ. -Laku noæ, | dušo. -Morate spavati.
{78799}{78925}Ja sam kriv. Izgubio sam | pojam o vremenu. Krivi mene.
{78950}{79016}Djeca su draga. Doista.
{79201}{79309}Mislim da moramo | razgovarati. -I te kako.
{79488}{79635}Slušaj, ne ljutim se na | tebe što si me dala posvojiti.
{79638}{79764}U redu? Maureen misli da | se ljutim, ali ne ljutim se.
{79799}{79841}Dovoljno se i sama ljutim.
{79890}{80092}Stvari se tako zapetljaju | krivnjom, sramom i aluzijama.
{80126}{80240}Istina je poput maèa. | Presijeèe sve te gluposti.
{80247}{80370}Oslobodi te. Ne osjeæaš li se | bolje sad kad se sve zna? -Da.
{80378}{80465}Da. -Da.
{80534}{80640}Ovo ti je ispalo iz torbe. | Nemoj mi reæi da je vitamin.
{80650}{80798}Nije ispalo. Kopala si mi po | stvarima. -Da. -Kopala si! -Da.
{80806}{80900}Sad mi ponovi da je istina | maè koji te oslobaða.
{81307}{81347}Želiš li mi što reæi, sine?
{81628}{81670}Imam leukemiju.
{81719}{81774}Rak krvi.
{81860}{81890}I...
{81941}{82027}Umirem. Umirem.
{82132}{82170}Žao mi je.
{82378}{82425}I meni, dušo.
{82494}{82524}I meni.
{83045}{83190}Treba što prije naæi davatelja. | -Ja nudim svoju koštanu srž.
{83191}{83298}Lijepo od vas, ali roditelji | ne odgovaraju. Braæa su bolja.
{83327}{83450}Navedem li braæu na pretrage | krvi, moram li im reæi razlog?
{83458}{83571}Ne, ali bih vam savjetovao. | -Zašto im ne bi rekao?
{83599}{83730}Možete objasniti Sheili | kako se radi presaðivanje? -Naravno.
{83760}{83900}Koštana srž se uzima | injekcijom. -Imate koju?
{84006}{84095}Majko Božja. -Evo.
{84097}{84170}Ovo je od titana.
{84183}{84288}Èvršæi je od èelika. -Dobro.
{84294}{84456}To je važno jer se ovim dijelom | ulazi u zdjeliènu kost davaoca.
{84460}{84580}Iz nje se vadi srž. Koliko | bi se to puta moralo ponoviti?
{84581}{84654}Pedesetak. Pedeset.
{84852}{84945}Vidiš? -Prestrašno.
{84948}{85074}Zato sam ih htio upoznati prije | nego ih zamolim za ovakvu žrtvu.
{85094}{85208}Moji su sinovi dobri deèki. | Uèinit æe to za tebe. Znam.
{85250}{85296}I znam da bi ti | to uèinio za njih.
{85621}{85735}Mogu uæi i vidjeti gdje | radiš? -Samo sam èistaèica.
{85737}{85867}Ali možeš. Trebala bih ih zvati | prebivaoci, no zovem ih stanari.
{85868}{85974}Ima ih 58. Svi su beskuænici. | -Možeš me povesti kuæi, Sheila?
{85999}{86129}Ja sam joj draži. -Imam prišt | na turu stariji od tebe. -Pokaži.
{86135}{86285}I meni. -Evo pola funte. -Huligani. | Do Božiæa ste opet na ulici.
{86286}{86396}Brišite. -Jako zgodno. | Baviš se i savjetovanjem.
{86397}{86520}Regie, dušo. Ovo je | za tebe. -Hvala, Sheila.
{86523}{86658}Dva para. Jedan za nošenje, | drugi za pranje. Mijenjaj ih.
{86689}{86842}Tko je ovo? -Moj sin, | dr. Lipman, -Lijeènik! Ma nemoj?
{86845}{86971}Izlijeèite smrad njegovih nogu. | -Neæe na vas trošiti vrijeme.
{86976}{87088}Usto, nisam takav lijeènik. | -Mama vam je sjajna. -Da, baš.
{87132}{87310}Èije je ovo djelo? Odurno! | Nemate ni trunke srama!
{87318}{87440}Odmah to perite. Odmah. | Jer æu vas baciti na cestu.
{87444}{87557}Kamo i pripadate. I ti. | Odmah. Slobodno pritisnite.
{87625}{87692}Zar ne znate ni èistiti?
{87736}{87808}Ni pisati ne znate.
{87844}{87870}Dušo? -Bog.
{87870}{88017}Gdje ste? Zabrinula sam | se. -Zar ideš van? -Da.
{88079}{88150}Vidi ti nju. Baš si lijepa.
{88190}{88350}Derek je bio. Rekao je da si ga | trebao odvesti na piæe. -Joj!
{88356}{88490}Krenuo je s dva prijatelja u | Sheffield. -A mene nije bilo.
{88497}{88650}Išli su po drogu. Trebaš im zbog | benzina. -Kombi je ukraden.
{88668}{88734}Idem s prijateljicama na piæe.
{88759}{88835}Možeš nam se pridružiti.
{88885}{88940}Neka nam Bog pomogne.
{90516}{90658}Što je bilo? -Fay i Carol | se svaðaju. -Zašto? -Zašto?
{90662}{90728}Zbog tebe. Zar si gluh, | slijep i nijem, Jerry?
{90743}{90860}Nisi primijetio da se ponašaju | kao uspaljene školarke?
{90900}{91030}Što je? -Žao mi je. Ovo je | san svakog Židova.
{91030}{91106}Zbilja? Vruæe | mi je. Idemo van.
{91500}{91526}Kamo to idemo?
{91577}{91607}Imaš li uopæe pojma?
{91983}{92030}Zbilja si vruæa.
{92255}{92404}Isuse... Sad nema povratka. | -Ovo ne bi smjeli raditi.
{92495}{92602}To! Ovdje! Sada!
{92676}{92790}Proklet bio! -Jesi dobro? | -Jesam. Nemoj prestati.
{93177}{93295}Ja plaæam ruèak. Što god želiš. | U najboljem restoranu u gradu.
{93313}{93375}Za èime žudiš?
{93454}{93600}Pomfrit s curryjem. -Pogledaj | ovo. Koliko mjesta samo ima.
{93600}{93735}Lijep je. -Gore je ledenica. | -Pogledaj sve te ladice.
{93735}{93873}Kako ste ga ugurali kroz | vrata? -Što je ovo? -Jerry.
{93882}{94020}Ne znam što da kažem. | -Na što? -Hvala ti.
{94023}{94153}Ne, nije od mene. Sigurno | je od Dereka. -Glupane. Briši.
{94379}{94445}Evo što dobiješ kad | si dobar prema Sheili.
{94500}{94608}Što bih dobio za perilicu? | -Èistu odjeæu, bezobraznièe.
{94611}{94725}Frank je išao na pretrage. | -Sjajno. Ideš uskoro kuæi?
{94727}{94842}Moram još obraditi Dereka. Usto, | nikad nisam imao bolji seks u životu.
{94843}{94969}Prasnuli smo se u tunelu. | -Ne? -Da. -Baš frojdovski.
{94974}{95004}Sjajna je.
{95005}{95120}Bezobrazna je, prosta, | apsolutno preslatka.
{95191}{95316}Žao mi je što donosim loše | vijesti. -Pomalo se navikavam.
{95382}{95489}Željezo ti je nisko. Inaèe | si u odliènom stanju. -Dobro.
{95513}{95599}Što savjetuješ? | -Poèni uzimati željezo.
{95649}{95700}I prestani gutati | Mavisine gluposti.
{95760}{95912}Frank? -Da? -O èemu se radi? | -Ni o èemu. Jerry je navratio.
{95976}{96086}Ovo je sad jako | kompilicirano. Dobro. Spremni?
{96097}{96220}Odmaknite se. Ovo æe | biti jako uzbudljivo. Evo!
{96223}{96330}To je bio vulkan. -Kako si to | uèinio? -Moja èarobna moæ.
{96334}{96465}Možemo još jednom? | -Zaista zna s djecom. -Da.
{96490}{96593}Taj apsolutno svakog | može smotati. Nije li tako?
{96681}{96823}Ono je vijeænica. -Vijeænica. U njoj | se održavaju sastanci. -Pa? 
{96827}{96908}Na kojima raspravljaju | o gradu. Na sastancima.
{96943}{97036}A da jedemo u | Innuendu? Što kažeš?
{97039}{97186}Zvuèi kao talijanski bar za | pedere. -Vidiš, ipak si pametna.
{97190}{97260}Šuti, nisam pametna. -Opet.
{97261}{97420}Svaki put kad mi se nešto sviða | na tebi, ti to odbiješ. Zašto?
{97422}{97570}Potajno se nadam da æeš naæi još | nešto što ti se sviða na meni.
{97588}{97668}Lažeš. Izmislila si to. | -Jesam, ali dobro je. -Jest.
{97669}{97745}No prozreo sam te | jer si prozirna.
{97795}{97835}Gospodine. -Hvala.
{97980}{98090}Malo mi je neugodno. | Kao da smo na sudaru.
{98092}{98210}Dobro, jesmo na sudaru. | -Nismo. Samo jedemo.
{98223}{98307}U Americi, kad dvoje | ljudi vodi ljubav dan i noæ,
{98309}{98428}hranjenje se zove sudarom. -Kakva glupost!
{98430}{98575}Mi ne vodimo ljubav. Ovo | je seks. Jako dobar seks.
{98596}{98626}Ne vodimo ljubav?
{98682}{98840}Ja vodim ljubav. -Pa nismo kao | dva golupèiæa. Više je nekako...
{98840}{98953}Životinjski. -Jest. Ali | ispod tog životinjskog ima...
{98979}{99037}Znaš... Slušaj, rado sam...
{99090}{99163}Rado sam s tobom. | Sviðaš mi se. Jako si draga.
{99171}{99345}U pogledu... -Bože. -Što se | smiješ? -Ne moraš to govoriti.
{99347}{99410}Velika sam cura. | Znam što radim.
{99435}{99528}Spavam s tobom i ljepše | mi je no ikad u životu.
{99534}{99622}Dobro, to sam htio èuti jer | ni meni nikad nije bilo ljepše.
{100390}{100476}Hvala. Na èudesnoj noæi. 
{100791}{100895}Derekov prijatelj. -Opusti se. | Što su mogli vidjeti? -Dovoljno.
{100960}{100997}Vidio je poljubac za laku noæ.
{101144}{101248}Gladna si. -Što je | ovo? -Moja nova maèka.
{101264}{101395}Jadnica. Bez doma. -Sigurno | nije cijepljena protiv bjesnoæe.
{101400}{101462}U Engleskoj nema bjesnoæe.
{101486}{101607}Uostalom, cijeli život | skupljam lutalice. -Ironièna si.
{101707}{101809}Molim? Uèinila sam što | je najbolje za moje dijete.
{101818}{101970}Tko si ti da me kritiziraš? | Živio si u bajci. -Oprosti.
{102019}{102100}Nisam trebao. -Nisi. | Dosta toga nisi trebao.
{102140}{102197}Znam što se dogaða | izmeðu tebe i Maureen.
{102201}{102336}Nemam pravo soliti pamet, | ali ne želim da ju povrijediš.
{102342}{102425}Ima osjeæaje. Svi ih imamo.
{102493}{102523}Imaš pravo.
{102564}{102657}No bez brige. Neæu ostati | toliko da bih je povrijedio.
{102720}{102813}Frank je išao na | pretrage. Ne odgovara.
{103151}{103230}Pretpostavljam da mu | nisi rekao za rak.
{103392}{103422}O, Bože.
{103483}{103596}Bog zna da mi je žao što | umireš, no dosta mi je laganja.
{103649}{103736}Nemoj više dušo. Dosta je.
{104140}{104281}Tvoj divni novi sin drpa | moju ženu! Moju ženu!
{104311}{104360}Derek! Èekaj!
{104457}{104503}Što to imamo?
{104548}{104628}Derek! -Onaj tko | naðe, njegovo je.
{104649}{104704}Jesi li znala da | ti je deèko narkiæ?
{104810}{104840}Što je ovo?
{104941}{105050}Lijek protiv raka. | Imam oblik raka krvi.
{105052}{105156}Ako mi ne presade | koštanu srž, umrijet æu.
{105178}{105281}Obièno su najbolji | davatelji braæa i sestre.
{105284}{105405}Èekaj malo! Zato si htio | da idem na pretrage krvi.
{105460}{105503}Ti i Frank, obojica.
{105516}{105596}Htio sam vidjeti odgovarate li.
{105657}{105747}Zgodno. Spavaš | s oboljelim od raka.
{105773}{105873}Nadam se da æeš se zaraziti. | -Tvom neznanju nema kraja.
{105879}{106000}Zašto... Zašto mi nisi rekao? | Zašto si svima lagao?
{106005}{106120}Nije. Rekao je meni. | A sad oboje van iz sobe.
{106121}{106213}Pustite èovjeka da uzme lijek | prije nego što ga napadnete.
{106252}{106282}Evo, dušo.
{106630}{106758}Sramota je! -Jedina je sramota | što umire, a nikog nije briga.
{106759}{106861}Maureen je briga. -Ne | zavidi ljudima na sreæi.
{106895}{107014}Oživjela je. Vratila joj se boja | u obraze. -Koje? Dosta je?
{107016}{107131}Neæeš me udarati! Idem | kuæi! -Idi! Hvala Bogu!
{107185}{107287}Uèinio sam to. Usprotivio | sam se Mavis i rekao joj.
{107288}{107423}Sve što me godinama muèilo. | I da neæu više to trpjeti. -Sjajno.
{107429}{107510}Što je rekla? -Izbacila | me iz kuæe i želi rastavu.
{107525}{107662}Za sve je Jerry kriv. Brak mi je | uništen. -Obraðuje i Maureen.
{107666}{107751}Žao mi je što zadnji saznaješ.
{107757}{107860}Jerry je jako, jako bolestan. | -Što? -Ima leukemiju.
{107893}{108008}Zato je i htio da idemo na | pretrage. Da nam isiše srž.
{108014}{108120}Ja sam ih napravio. -Ali ne | odgovaraš, jer sad mene lovi.
{108350}{108410}Ne znam otkud da | poènem s isprikama.
{108466}{108577}Frank... -Nitko neæe znati. | To æe biti naša mala tajna.
{108577}{108620}Gdje li sam to veæ èuo?
{108763}{108860}Uspio sam unijeti mnogo | tuge u vaše živote.
{108884}{108995}Nisam vam vjerovao jer vas nisam | poznavao. Sad vas poznajem i...
{109030}{109143}Zaista mi je jako žao | što vam nisam vjerovao.
{109411}{109528}Kamo si krenuo? -Vraæam | se u hotel. -Èekaj, sine.
{109592}{109700}Svratit æeš do mene prije | nego što odeš. -Da. -Ne.
{109703}{109834}To nije bilo pitanje. Svratit æeš | do mene prije nego što odeš.
{109864}{109894}Hoæu.
{110070}{110122}Jeste li dobro? -Da, jesam.
{110181}{110221}Pretjerao sam s konjakom.
{110302}{110400}Izvolite. -Hvala. | -Hvala vama. -Laku noæ.
{110488}{110560}Znaèi, dogovorili smo se? | -Da. -Da? -Da, super.
{110590}{110626}Bog!
{110725}{110835}Znala sam da æu te tu | naæi. Muèno mi je u želucu.
{110836}{110982}Bolesna sam od onog što si mi | rekao. Rekao si mi strašne stvari.
{110987}{111026}Užasne stvari.
{111133}{111251}I stojim iza toga. -Sigurna | sam da si ih rekao u bijesu.
{111254}{111395}I zato sam spremna oprostiti. | -Ne tražim oproštenje, Mavis.
{111400}{111470}Ne trebam tvoju milostinju, hvala.
{111491}{111577}Èuj, vrati se kuæi | pa æemo razgovarati.
{111680}{111722}Koja je èarobna rijeè?
{112123}{112152}Molim!
{113079}{113135}Jerry! Jerry!
{113220}{113258}Samo malo.
{113401}{113431}Nisi se žurio.
{113502}{113600}Zbog tebe i tvog petljanja | imao sam najbolji seks u životu.
{113608}{113700}S kim? -S Mavis. | Pozdravlja te.
{113779}{113924}Lijepo. Ja æu na kauè. -Spavat | æeš tu? -Moramo u bolnicu u 9.
{113935}{114039}Èekat æe nas mama, Maureen | i Derek. Iæi æe na pretrage krvi.
{114286}{114415}Mama. Gdje su ostali? -Djeca su | u školi. Maureen dovodi Dereka.
{114417}{114457}Evo je.
{114503}{114620}O, Bože, sama je. gdje je? -Nije | se držao dogovora. -Dogovora?
{114677}{114800}Mama i Maureen skupile su 100 | funta da Derek napravi pretrage.
{114805}{114906}Sad ima fobiju od igala koju bi | mogao prevladati za 100 funta.
{114911}{114960}Da ne bi! Èekajte me tu.
{114987}{115109}Odvedite me natrag. -Dat æu mu | novac. -Više se ne radi o novcu.
{115233}{115281}Fobija od igala, kažeš?
{115359}{115444}Sramim te se, | Derek. Sramim.
{115655}{115690}Prijamni ured? -Da.
{115856}{115992}Prometna? -Ne, došao | je dati krv. -Uspravi se.
{116592}{116704}Èuj, ne mogu dugo | ovako izdržati. Stoga...
{116713}{116770}Ako imaš što reæi, reci.
{116824}{116897}Nemam gaæice na sebi | i trtica mi se smrzla.
{117715}{117767}Ovo sad nije seks.
{117816}{117850}Nije? -Ne.
{117922}{117957}Vodim ljubav.
{118703}{118770}Moram iæi. Djeca se nikad | nisu probudila bez mene.
{119174}{119204}Volim te.
{119445}{119499}Žao mi je.
{119761}{119791}Bog, dušo!
{119847}{119903}I, što je rekao?
{119998}{120065}Ne, ni Derek ne odgovara.
{120124}{120244}Moram iæi. Sad se moram žuriti. | Moram se vratiti u New York. 
{120275}{120399}Poèeti kemoterapiju. Možda mi se | posreæi s programom davatelja.
{120441}{120497}A Maureen? Jesi li...
{120522}{120660}Ne mogu se sad opraštati. | Posebno ne s njom. Ne ovako.
{120668}{120733}Ne u ovom stanju.
{120784}{120920}Èuj, ne želim da | se itko brine. U redu?
{120920}{121035}Nisam navikao na poraze. | Pobijedit æu ovo. Doista.
{121095}{121136}Kupio sam vam...
{121207}{121310}Nisam znao što kupiti. Pogaðao | sam. Kupio sam Emmi boombox.
{121313}{121363}Znam da veæ ima. -Sine.
{121450}{121490}Kad se odrekneš djeteta,
{121520}{121612}zapravo si se odrekao prilike da voliš.
{121666}{121716}Nikad više nisi potpun.
{121772}{121890}Želim ti zahvaliti što | si se vratio i našao me.
{121943}{121973}Što si me uèinio potpunom.
{122084}{122114}Volim te, sine.
{122330}{122360}I ja tebe volim.
{123536}{123677}Bog, majko. -Još sam ti majka? | -Zabrinula si se? -Nimalo.
{123692}{123780}Lažeš! Bojala se zamjene | nalik na Julie Andrews.
{123783}{123930}Možemo s vrata? -Izgledaš loše. | Ostaješ kod mene. -Ne ostajem.
{123934}{124069}Onda bar jedi. -Hoæu. -Maknite | se s vrata ili æu vas pojesti.
{124335}{124430}Vidim, imate nekakve | novosti. Išta dobro?
{124451}{124557}Nismo uspjeli naæi nikog | s odgovarajuæom srži.
{124557}{124660}To je neobièno. No proširili | smo pretragu na Evropu.
{124693}{124840}Prema mojim procjenama ovaj | rak nekontrolirano mahnita.
{124869}{124941}Udvostruèio sam kolièinu | interferona. -Primijetio sam.
{125015}{125051}Primijetio sam i da ne pomaže.
{125136}{125186}Pišamo u vjetar, zar ne?
{125252}{125371}Možda bi bilo | vrijeme da... Znate veæ...
{125398}{125439}Sredite svoje poslove.
{125790}{125937}Što biste rekli, koliko imam | vremena da sredim svoje poslove?
{126065}{126095}Nekoliko mjeseci.
{127180}{127276}Molim? -Jerry, dušo! -Hej!
{127282}{127437}Nisi normalan! Paketi stižu | svaki dan! Trošiš gonile novca!
{127438}{127502}A na što drugo da trošim novac?
{127579}{127686}Jesu li djeca ondje? -Nisu. | U školi su, ali nedostaješ im.
{127745}{127800}Kako je Maureen? Je li ondje?
{127811}{127926}Prièekaj malo. Želi | razgovarati s tobom.
{127990}{128099}Ne, dušo. Otišla je. | Danas je kod manikirke.
{128128}{128243}Jerry, jesu li našli davatelja? | -Evo, samo što nisu.
{128249}{128350}Osjeæam se odlièno.
{128360}{128470}Na makrobiotièkoj dijeti sam. | Èini se da pomaže.
{128471}{128620}Odlièno, dušo. Sjajno. -Ne | mogu se sad još vratiti k vama,
{128622}{128690}ali se stanje definitivno poboljšava.
{128883}{129014}Laže koliko je dug | i širok. -To mu dobro ide.
{129044}{129085}Umire!
{129105}{129223}Što misliš, zašto nam šalje | stvari? -Ne znam. Nije me briga.
{129226}{129320}Dobro, jer æu sve to prodati. | Koga poznajemo da ima kovèeg?
{129547}{129630}Eno ga! -Ujaèe Jerry! -Bog!
{129638}{129677}Nevjerojatno!
{129729}{129825}Bog, dušo! Jeli ti drago | što nas vidiš? -Šališ se?
{129830}{129940}Poput sna koji je postao java. | Odakle vam novac za karte?
{129941}{130050}Prodale smo tvoje darove. | Ne ljutiš se? -Nikako.
{130142}{130257}Tu sam zbog njih. Pravi se kao | da me nema. Neæe ti biti teško.
{130303}{130375}Takva je otkako si | otišao. Ti si kriv, dušo.
{130414}{130527}Evo nas, uðite. | -Isuse! Golemo je!
{130530}{130670}Tko još ovdje živi, bako? | -Nitko, dušo. Samo Jery. Bože.
{130730}{130840}Ti bokca! Jesi li | oèekivala takvo što?
{130877}{130992}Nije li malo previše? | -Nije. Drži jezik za zubima.
{131020}{131135}Ujaèe Jerry, možemo li Anthony | i ja razgledati? -Samo navalite.
{131149}{131283}I ništa ne dirajte. -Dirajte | sve što želite. Osigurano je.
{131380}{131503}Ne slini. Kao turist si. To je | hladnjak. -Veæi je od moje kuæe.
{131511}{131654}Bako, doði vidjeti | televizor! Veæi je od kina!
{131682}{131789}Ujak Jery je rekao da možemo | peæi kokice. -Mogu? -Ja æu.
{131793}{131873}Ti riješi stvari s Kraljicom | noæi prije nego što je zadavim.
{131924}{131954}Hajde.
{132395}{132431}Možemo li razgovarati?
{132476}{132513}Nije li malo prekasno?
{132897}{132944}Bar mi objasni... -Skini mi se!
{133008}{133056}Nisam ti ja | neurotièna pacijentica!
{133119}{133230}Mogu li bar objasniti zašto sam | otišao? -Gluh si? Ne zanima me!
{133230}{133350}Što je bilo, bilo je. Imao | si dobar tajming. -Tajming?
{133391}{133540}Misliš da su èesti neoženjeni | muškarci koji se uredno peru?
{133542}{133650}Otišao sam jer mi je bilo | loše. -Ne skrivaj se iza toga.
{133653}{133780}Nije to jedino na svijetu. | Svatko ima probleme.
{133834}{133864}Zašto sam onda | otišao? Reci mi.
{133885}{134005}Dok se radilo samo | o seksu, bio si sretan.
{134006}{134088}Meni je postalo važnije. | Pokušala sam to sakriti.
{134099}{134207}No zadnju noæ u tvom hotelu | otkrila sam osjeæaje.
{134207}{134370}I drugo jutro si nestao. -Ne, | nije to! Otkrio sam da umirem!
{134379}{134491}I ja sam umirala. | Nisi primijetio?
{134560}{134684}Uletiš mi u život i | za sobom ostaviš kaos.
{134921}{135060}Nisam htio... Nisam | htio doæi i stvarati zbrku.
{135062}{135130}I nisam se htio zaljubiti u bratovu ženu.
{135283}{135327}Ali lagao si joj.
{135394}{135424}Jesam.
{135465}{135600}Jesam. Pretvarao sam se | da sam sretan i zdrav momak.
{135606}{135696}I upalilo je jer si nasjela | i svidio ti se taj momak.
{135707}{135860}No to je najveæa laž. Jer | ja zaista nisam taj momak.
{135928}{136023}Ustvari sam ružan, | raspadam se.
{136069}{136105}Osoba koja umire.
{136200}{136250}Zato si pobjegao?
{136341}{136371}O, Bože.
{136415}{136540}Kako si mogao proèitati | toliko knjiga i ostati glup?
{136593}{136724}Zar si zaista mislio da | moraš biti èist
{136724}{136791}i dezinficiran | da bi mi se svidio?
{136825}{136870}Što ti ja mogu ponuditi?
{136916}{136946}Sebe.
{137120}{137166}Oprosti.
{137258}{137324}Jako mi je žao.
{137379}{137465}Tako mi je žao! | -Zaveži i poljubi me.
{137770}{137890}Kako si sa zdravljem? Ne | izgledaš mi dobro. -Nisam dobro.
{137900}{138000}Ne ide mi najbolje. | -Oboje su èvrsto zaspali.
{138052}{138089}Nema davatelja, zar ne?
{138173}{138308}Nema. Stanje se, | zapravo, dosta pogoršalo.
{138354}{138460}Rekli su mi da imam tri | mjeseca. U najboljem sluèaju.
{138620}{138655}Neæe biti lijepo.
{138666}{138760}I zato bih htio, ako dopuštaš,
{138767}{138909}sam ovo proživjeti. | Da imam malo privatnosti.
{138928}{139000}I dostojanstva. -Nema šanse.
{139029}{139137}Tko æe te paziti? I sam | kažeš da æe Esther otputovati.
{139160}{139276}Tko æe te maziti noæu? | -I držati za ruku kad te strah?
{139321}{139450}Ne mogu podnijeti da sam | bespomoæna. Da ne mogu pomoæi.
{139452}{139550}Izašao si iz mog tijela. | Moja si krv.
{139633}{139663}Na TV uvijek govore
{139664}{139800}kako roditelji djetetu | daju bubreg, slezenu...
{139805}{139905}nije mi jasno zašto ja ne mogu pomoæi? -Doði.
{139936}{139992}Ovako su mi objasnili.
{140077}{140145}Ovo je majèina strana.
{140158}{140228}Ovo je oèeva strana. | Razlièite su.
{140259}{140340}Djeca su mješavina.
{140350}{140469}Potrebni su brat ili sestra | jer roditelji ne mogu pomoæi.
{140541}{140605}Tko bi pomislio da ima toliko | razlièitih kombinacija? -Da.
{140612}{140703}No dovoljna je jedna | mrvica da sve bude drukèije.
{140763}{140850}Koliko ima dobrovoljaca | u programu? -Na tisuæe.
{140854}{140945}Sad traže po Europi. | -A da nema papra?
{141045}{141164}Što? -Što bi bilo | da nema papra?
{141206}{141236}Samo sol...
{141307}{141337}ako su obje...
{141390}{141467}ako obje krvne linije dolaze | od slane strane obitelji?
{141790}{141829}Mama?
{142000}{142040}O, Bože, jadnice...
{142131}{142161}Tko?
{142322}{142360}Peter.
{142413}{142443}Peter?
{142494}{142570}Ujak Peter? -Ujak Peter.
{142775}{142805}Kako?
{142866}{142940}Pomagao je obitelji. | Nismo imali novca.
{142987}{143097}Mama i tata su pili. | Ona èak više nego on.
{143148}{143258}Nama djeci govorili su | da moramo biti posebno dobri 
{143319}{143362}prema ujaku Peteru.
{143410}{143480}Jer je on bio naš anðeo èuvar.
{143571}{143666}Kad sam napokon | skupila hrabrost i rekla im...
{143892}{143977}Da me napio džinom.
{143993}{144033}I što je uèinio.
{144125}{144240}Rekli su da sam ga izazivala | i pretukli me na mrtvo ime.
{144360}{144480}Tek sam poslije shvatila | što je moj otac uèinio.
{144490}{144540}Tukao me da pobacim.
{144620}{144747}Nisam te htjela dati. | Uèinili su mi to iza leða.
{144768}{144860}Bilo mi je svejedno od koga si. | Bio si moje dijete.
{144979}{145027}Uzeli su mi te.
{145090}{145216}I nikad te više | nisu spomenuli. Kao da si ništa.
{145271}{145380}Ni... Ni dan nije prošao | da nisam mislila na tebe.
{145600}{145680}U redu je. Prošlo je.
{145703}{145783}Više nema osjeæaja | krivnje i srama.
{145874}{145977}Znaèi, ne mrziš me? | -Da te mrzim? Šališ se?
{146025}{146135}Volim te. -Jasno | da te voli. Majka si mu.
{146136}{146229}Ne, Ester mu je majka. -Èekaj. Ester...
{146237}{146315}Ester mi je majka, | ali ti si moja mama.
{146738}{146880}Neka je sa sreæom i | tebi i mami. Reci joj da je volimo.
{146899}{147015}Neka nas Maureen nazove | i kaže kako je prošlo. -Jerry.
{147015}{147107}Èujem da operacija možda ne | uspije. Jesam li u oporuci?
{147135}{147256}Ne slušaj ga. Slušaj, | mislimo na tebe i molimo se.
{147262}{147394}Znaš to, tar ne? -Hvala. | -Morate iæi. -Moram prekinuti.
{147403}{147484}Dobro. Bog. | -Bog. -Sretno.
{147564}{147668}Howarde... -Ne. -Samo | sam htio reæi... -Ne poèinji.
{147685}{147736}Vidimo se ujutro. | Donijet æu ti novine.
{147826}{147866}Volim te. Pusa.
{148130}{148261}U ovom trenutku rijeèi se | èine strašno neprimjerenima.
{148268}{148330}Vaša me ljubav èini poniznom.
{148369}{148438}Dali ste ovom djeèaku život
{148440}{148530}i sad ste dovoljno hrabri | da to pokušate još jednom.
{148561}{148591}Hvala.
{148662}{148790}Hvala. -Nikad mi nitko | nije rekao nešto tako lijepo.
{148813}{148861}Sad vidim odakle mu dobrota.
{148984}{149066}Ovo æe uspjeti. Èujete li me?
{149335}{149365}Volim te.
{149736}{149766}Nervozan si?
{149887}{149991}Postoje izgledi da ovo ne uspije.
{149998}{150095}Znam, ali moramo | pokušavati dok ne uspijemo.
{150219}{150249}Ako uspije...
{150290}{150320}Ako uspije,
{150371}{150452}hoæu li se morati obojiti | u plavo i poèeti pušiti?
{150522}{150619}Ovo je dijete pravi gad. | -Vrijeme je da krenemo.
{150683}{150827}Kamo... ju vodite? -Na anesteziju. | -Ne bez mene. -U redu je, deèki.
{151284}{151340}NEOBIÈNI ODNOSI
{151415}{151445}SAD - Velika Britanija | 2001.
{151546}{151576}Režiser: Paul Reed
{151577}{151607}{y:ib} s tv-a zapisao |{C:$FF0000}{y:b} drdamjan  
