{1}{2}23,976 fps
{340}{440}STRANGELAND
{522}{594}* [ rock glazba ]
{1902}{1974}* I've died a thousand times.|umro sam tisuæu puta
{1974}{2046}* Drowned in a sea of lies.|utopljen u moru laži.
{2046}{2139}* Walked every path through every door.|hodio stazama na svaka vrata
{2190}{2250}* Oh, how I've suffered through!|o, koliko sam propatio
{2250}{2310}* The wicked men can do...|poroèni koji su
{2310}{2370}* the pain they can endure.|patnju æe trpjeti
{2382}{2442}* The things I have in store.|to što upamtih
{2526}{2586}* These are the lies,|to su laži
{2586}{2658}* here in paradise|tu u raju
{2658}{2730}* Legions suffer for the few,|legije zbog nekolicine pate
{2730}{2790}* never knowing they were used.|ne znajuæ' da su iskorišteni
{2790}{2862}* Don't turn away...|ne osvræi se
{2862}{2934}* get down to your knees and pray!|na koljena padni i moli
{2934}{2998}* On the things you dedicate.|za ono èemu si posveæen
{3006}{3078}* For the pain you would forsake!|za patnju koju bi napustio
{3090}{3138}[ zujanje ]
{3200}{3246}producenti:
{3246}{3294}* The little lies!|male laži
{3294}{3375}* These are the lies!|to su laži
{3426}{3522}* These are the lies!|to su laži
{3522}{3594}* The dirty little lies!|prljave male laži
{3630}{3678}[ zvoni telefon ]
{3678}{3762}[ spajanje modemske linije ]
{3837}{3885}[ glas raèunala ]|Dobrodošli.
{4220}{4270}Hej, svima
{4320}{4380}CaptHowdy: Mogla bi me pozvati na|zabavu. Koji si razred?
{4579}{4620}Minifin777:|Student sam druge godine.
{4692}{4780}[ smješkanje ] Evo ga.|Donna, pogledaj ovog lika.
{4940}{4990}Howdy Captain|Što ima?
{5050}{5111}CaptHowdy: Ništa posebno. slušam muziku...|Volite hip-hop?
{5112}{5160}Kakvo je to ime|Captain Howdy?
{5238}{5340}Volite li hip-hop?|[ smješka se ] Volim.
{5436}{5480}Volim!!!!!
{5552}{5621}U koju srednju ideš?|Šalji mi IM na Calhoun!!
{5661}{5721}Što je IMme?|Ne IMme!
{5721}{5793}I toèka M toèka, pa me.
{5799}{5850}[ zvonjava raèunala ]|Trenutna poruka.
{5850}{5922}Sad možemo s njim|razgovarati na samo.
{6000}{6069}CaptHowdy: Ne, Kennedy. Što ima kod tebe?|- Dangubim s prijateljicom.
{6072}{6108}[ zvonjava raèunala ]
{6110}{6147}CaptHowdy: Doðete na zabavu?
{6147}{6189}Ajoj! Pojasni mi.
{6191}{6280}Ideš na slijepo sa zaslonskim imenom?|Tko je taj?
{6282}{6311}Odakle si ti?
{6315}{6415}Jednom æemo upoznati, udati se i virtualno|seksati sa èovjekom iz snova, on-line.
{6415}{6498}Sve što trebam o liku je ovdje.
{6545}{6618}Muškarac... Samac... uèenik...
{6618}{6683}Sad ti je bolje?|- Rekla bih.
{6687}{6759}Hej, tebe nije pozvao.
{6768}{6819}[ hihoæu se ]|Kada? Gdje?
{6868}{6840}Može i prijateljica?
{7068}{7152}[ hihoæu se obje ] Veèeras! 21.00!|Moja kuæa! Roditelji otišli!!! MOŽE I PRIJATELJICA!
{7158}{7206}Uzmi adresu.
{7512}{7560}[ žena ]|Mike?
{7704}{7752}Mike!
{7752}{7824}Da, Toni?|Što je?
{7836}{7908}Jesi li... što primijetio?
{7980}{8025}Ne znam.|Što tražim?
{8025}{8088}Bože, Mike, Genevieve|sinoæ nije došla kuæi.
{8088}{8180}Nije ostala kod Tianainih?|- Da, vjerojatno prespavala.
{8180}{8255}Ubit æu je što nije zvala.|[ zvoni telefon ]
{8283}{8331}Bolje joj je da je ona.
{8331}{8391}[ nastavlja zvoniti ]
{8499}{8540}[ Toni ]|Halo?
{8571}{8640}Oh, Mary Ann.|Drago mi je što si nazvala.
{8679}{8715}Što?|[ beep ]
{8716}{8799}[ Toni nastavlja, klonulo ]
{9063}{9135}[ Toni ] Baj.|[ odlaže slušalicu ]
{9135}{9207}Bila je Tianaina mama.
{9207}{9255}Ni ona nije došla kuæi.
{10350}{10398}[ vrištanje ]
{10398}{10446}Mama!|Aah!
{10446}{10518}[ udiše ]
{10554}{10614}* [ glazbena linija: metal ]
{10830}{10902}* [ nastavlja glasnije ]
{11559}{11619}[ cmizdrenje ]
{11775}{11835}Eto.|[ cmizdrenje, jecanje ]
{11835}{11895}Tako je bolje.|[ cmizdrenje nastavlja ]
{11900}{11943}Probaj ne govoriti.
{12240}{12306}[ grmljavina ]
{12340}{12400}Dobrodošli u HELVERTON|Stanovnika 350.000 Nadmorska...
{12400}{12460}"Lijep za posjetiti|još bolji za napustiti"
{12504}{12576}[ nerazgovjetni žamor ]
{12576}{12648}[ zavija sirena, žamor ]
{12732}{12792}Isuse Kriste.|[ uzdah ]
{12900}{12940}Cijelu noæ si tu?
{12950}{13010}Sve usporeno osim sata.
{13022}{13070}[ zuji aparat ]
{13070}{13118}Vražji aparat.
{13298}{13346}[ pada sitniš ]
{13346}{13416}Što radiš s NCIC ispisima?|[ centar za prikupljanje informacija ]
{13418}{13478}[ šalica pada na mjesto ]|NCIC?
{13478}{13550}[ toèenje tekuæine ]|Pretragu FBI raèunalima.
{13550}{13634}Telefonom sam zahtijevao|popis poznatih seksualnih prijestupnika.
{13634}{13680}Rekao si da æeš se pobrinuti.
{13706}{13760}Što, ja tu moram|sve sam napraviti?
{13790}{13838}[ uzdiše ]
{13910}{13970}Èuj, uz tebe sam.|Važi?
{13970}{14010}Tek sam došao.
{14010}{14066}Trebalo je biti gotovo juèer.
{14066}{14150}Uspjeh nam zavisi o|pogrešci drugoga, Christiane.
{14150}{14210}Mi ne griješimo.|Nikad.
{14282}{14342}Sigurno neæeš bezkofeinsku?
{14402}{14522}Èuj, zašto se ne odeš kuæi otuširati, |odmoriti ili što veæ?
{14522}{14594}Zvat æu FBI|i nabaviti popis.
{14594}{14654}Ako što iskrsne,|javim na dojavnik.
{14690}{14762}Èuj, obeæavam.|Ako što iskrsne, javim ti.
{14762}{14810}Odi kuæi.|Dobro?
{14846}{14894}Da.
{14894}{14954}[ sirene nastavljaju ]
{14963}{15047}[ Toni ] Iste minute èim nešto èujem,|èut æeš i ti. Aha.
{15059}{15102}Da, zvat æu te kasnije.
{15107}{15155}Dobro?|Dobro.
{15239}{15287}To je Tianaina mama.
{15311}{15359}U komi je.
{15359}{15443}Hoæe znati što se zbiva.|Kao da ja znam.
{15443}{15491}Zna više od mene.
{15491}{15539}[ uzdiše ]
{15550}{15650}Toni, govorim ti sve što se|odnosi na sluèaj. - Hej, znam postupak.
{15659}{15707}[ zvono na vratima ]
{15707}{15755}Bože.
{15755}{15810}Ne mogu pomoæi, Genevieve...
{15810}{15899}ako moja oèinska briga|nadjaèa objektivnost detektiva.
{15899}{15983}Znaš to.|Da, da, to æe mi pomoæi.
{15986}{16034}[ zvono na vratima ]
{16094}{16198}Pustit æete nas unutra|ili moramo kuhati na trijemu?
{16238}{16310}Èetrdeset pet sati?|Da te pitam nešto?
{16310}{16358}Imaš djece?
{16358}{16406}Da?
{16406}{16490}Onda zamisli|da ga nema dva dana...
{16490}{16574}i šupak od èinovnika ti kaže|da treba biti dulje od dva dana...
{16574}{16640}za dobiti informacije|potrebne za traganje.
{16658}{16742}Toèno. Imate 12 sati,|ni minute više.
{16742}{16815}[ zvoni telefon ]|Ovdje Christian. Što imate?
{16826}{16860}Kako se držiš?
{16883}{16920}Užasno.
{16931}{16979}Htjela bi vrištati.
{16979}{17030}Smiješ slobodno, dijete.
{17051}{17085}Kako je Michael?
{17135}{17171}Èelièni muškarac.
{17183}{17267}Dobar je èovjek.|Nemoj misliti da on ne pati.
{17288}{17315}[ Toni ]|Tko bi znao?
{17315}{17387}Ideš nekad na Internet|ujaèe Mike?
{17435}{17483}Ne.
{17543}{17580}Baš je zgodno.
{17615}{17665}A što to, Angela?
{17675}{17723}Pa, možeš nekom|poslati e-mail, bilo kud.
{17759}{17828}Možeš napisati pismo,|nazvati.
{17828}{17879}Ne.|To je nešto više.
{17879}{17900}Ne moram biti ja.
{17900}{17999}Nekad se pretvaram da sam |kraljica maturalne,
{17999}{18110}a mogu promijeniti ime i postati|loša paklena cura.
{18119}{18191}Upoz... chatala sam|s nekim ubojicama.
{18227}{18275}U redu.
{18335}{18396}Cure nekad izaðu s takvim likovima?
{18443}{18522}[ smješka se ] U redu, Angela.|Neæu nikome reæi.
{18539}{18587}Pa, da.
{18623}{18719}A Genevieve? Nekad je izišla|s momkom kojeg je on-line upoznala?
{18755}{18803}Svakako, ponekad.
{18833}{18881}[ nemoæno jecanje ]
{18881}{18975}[ muškarac]|Gdje su obredi prijelaza?
{18989}{19085}Inicijacija koju moraju|mladi pretrpjeti.
{19121}{19169}Kako se uopæe mogu nadati
{19181}{19270}[ jecanje nastavlja ]|postati pravi odrasli bez rituala?
{19277}{19361}Živimo u svijetu napuèenom ljudima
{19361}{19409}u svojim srednjedobnim tijelima
{19435}{19505}još se spotièu i pužu...
{19517}{19589}sa svojim djetinjim umovima.
{19613}{19694}Svi moramo proæi|obred prijelaza,
{19730}{19790}i mora biti fizièki.
{19844}{19901}Mora biti bolan.
{20006}{20078}Mora...
{20078}{20135}ostaviti obilježje.
{20240}{20312}[ muškarac ]|Mislim da smo našli. Da.
{20312}{20363}* [ radio: rap metal ]|Frank!
{20363}{20411}Mislim da smo našli!
{20420}{20495}* [ nastavlja ]
{20588}{20690}Sigurno želiš nadgledati ovo?|- Nemam izbora. Dakle, što imamo?
{20707}{20759}'Veèer Tom!|- Detektiv!
{20759}{20879}Dobro, dva lovca uoèila su|tragove guma koji skreæu u vodu.
{20915}{20946}Spremni?|- Da.
{20960}{21023}Tamo spremni?|- Možemo iæi.
{21023}{21071}Možemo ušutkati tu muziku?
{21071}{21131}
{21131}{21215}[ muškarac ] Makni se od kablova, molim.|Makni se od kablova.
{21407}{21455}Polako.|Polako.
{21491}{21551}Evo ga.
{21551}{21599}[ žena vièe nerazgovjetno ]
{21599}{21675}[ muškarac ]|Polakše. Neka se ocijedi.
{21920}{21956}[ muškarac ]|Polako.
{21968}{22016}[ Christian ]|Oho. Dobro je.
{22028}{22100}Dobro je.|[ muškarac ] Oho, oho, oho!
{22352}{22436}Pozornièe, dopustite...|hoæu uslikati lijevu stranu.
{22736}{22786}[ Mike ]|Ovo je Tianin auto.
{22889}{22925}Sranje!
{23009}{23057}[ uzdiše ]
{23357}{23393}Ohh!
{23510}{23558}[ uzdiše ]
{23594}{23654}[ uzdiše ]|To je Tiana.
{23735}{23837}Hej, Gage?|Doði ovamo. Pogledaj ovo.
{23897}{23957}Kakva je to dovraga stvar?
{24119}{24191}Izgleda mi kao septum spike.|[ šiljak pregrade nosa ]
{24191}{24270}Industrial strength.|- Što?
{24270}{24323}Septum spike.
{24323}{24383}Za probušeni septum,
{24383}{24450}i vjerojatno je najveæi|kojeg sam vidio.
{24467}{24530}Industrijski kvalitet.|Što, veæi je no inaèe?
{24530}{24587}Da. Ovaj je jebeno èudovište.
{24599}{24683}Klasièno bušenje septuma|radi se iglom kalibra 14.
{24695}{24731}Kalibar 8, najviše.
{24743}{24803}Ovo je kalibar osam, kopèate?
{24815}{24902}Ovaj ovdje?|Izgleda kao kalibar 00.
{24904}{24947}Vlasnik ovog spikea
{24947}{25043}u septumu ima rupu|kroz koju možeš provuæi prst.
{25055}{25115}Mora biti pravi zanesenjak, a?
{25115}{25175}Po èemu si|ti toliko mjerodavan?
{25175}{25223}Dobrodošao u moj svijet, isljednièe.
{25223}{25277}Misliš da se u životu|zanimam samo za
{25277}{25335}naganjanje hitne|u ovom govnu?
{25338}{25397}Kako misliš, tvoj svijet?
{25421}{25522}Body art. Tetovaža,|piercing, branding. [ žigosanje ]
{25522}{25558}Scarification.|[ stvaranje ožiljaka ]
{25558}{25620}Sve su to naèini|osobnog izražavanja
{25620}{25673}koji sežu unatrag|do peæinskog èovjeka.
{25673}{25769}Da, baš.|- Hej, imamo moæ nad svojim tijelom.
{25781}{25841}Kako tehnologija|izmièe sama sebi,
{25841}{25889}mi, moderni primitivci,
{25889}{26009}èvrsto se držimo|tradicije preinaèenja tijela
{26009}{26057}i plemenskih rituala.
{26057}{26117}Moderni primitivci.|- Tako je.
{26117}{26165}Misliš da je to|nešto novo?
{26165}{26273}Majka Winstona Churchilla imala|je tetovažu na zglavku, stari.
{26273}{26365}A gdje se ti moderni primitivci nalaze?|- Xibalba.
{26369}{26435}Xibalba?|- Da.
{26435}{26485}Klub u gradu.|Svidjet æe vam se.
{26489}{26549}Sigurno hoæe.|- Što znaèi Xibalaba?
{26573}{26621}Znaèi:|"Ulaz u pakao".
{26621}{26667}* [ metal ]
{26667}{26730}* Pretty girl with a knife.|cura zgodna nosi nož
{26741}{26801}* Watch your back, it's your wife.|pazi leða, tvoja je to žena
{26825}{26873}* Heroin load my blood.|heroin lije se u krv
{26910}{26966}* Shoot, shoot! Fun, fun!|droga, droga, živo, živo
{26993}{27038}* Pretty girl on ecstasy.|curica na ecstasyju
{27038}{27086}* [ nastavlja se ]
{27098}{27155}[ muškarac ]|Hej! Veæ je vrijeme!
{27158}{27205}[ žamor ]
{27422}{27482}* On ecstasy.|na ecstasyju
{27482}{27554}* Now, she wants to fuck me on the chin.|hoæe seks na mojoj bradi
{27554}{27602}* We are in league.|mi smo u savezu
{27602}{27674}* We are the doctors of low self-esteem.|doktori smo niskog samopoštovanja
{27674}{27758}* We do it wrong and we don't believe.|radimo krivo i ne vjerujemo
{27770}{27878}* We are the congress of the new disease.|mi smo sabor bolesti nove
{28169}{28229}* Pretty boy with a gun.|zgodan momak sa pištoljem
{28253}{28310}* Bang, bang! Fun, fun!|bang, bang, živo, živo
{28350}{28418}* Pretty girl with a knife.|cura zgodna nosi nož
{28418}{28502}* Watch your back, it's your wife.|pazi leða, tvoja je to žena
{28502}{28574}* Heroin load my blood.|heroin mi lije se u krv
{28574}{28637}* Shoot, shoot! Fun, fun!|droga, droga, živo, živo
{28673}{28745}* Pretty girl on ecstasy.|curica na ecstasyju
{28745}{28829}* Now she wants to fuck me on the chin.|hoæe seks na mojoj bradi
{28841}{28889}* We are in league.|mi smo u savezu
{28889}{28961}* We are the doctors of low self-esteem.|doktori smo niskog samopoštovanja
{28961}{29033}* We do it wrong and we don't believe.|radimo krivo i ne vjerujemo
{29045}{29132}* We are the congress of the new disease.|mi smo sabor bolesti nove
{29132}{29195}* [ nastavlja se ]
{29429}{29535}* That's right! Yeah, yeah!|tako je, da, da
{29535}{29573}Idemo odatle.
{29573}{29645}Kao da tražimo vlasnika|staklene cipelice.
{29645}{29693}Da, u sobi punoj Pepeljuga.
{29729}{29771}* Yeah!|da
{29810}{29894}* Pretty thing with no head.|zgodna stvar bez glave
{29906}{29978}* Perhaps you're better better off dead.|možda si bolji, bolji mrtav
{29978}{30038}* War! Blood everywhere!|rat, krv posvuda
{30038}{30086}* [ išèezava ]
{30600}{30647}Spusti ga!
{30665}{30712}Rekao je da|ostavimo neka visi.
{30760}{30820}Nije rekao da ga ubijemo.
{31192}{31252}Zašto...
{31288}{31336}Nisam mrtav?
{31356}{31392}Mislili smo da jesi mrtav.
{31404}{31474}Skoro sam stigao tamo!
{31565}{31656}Šamani to zovu|mala smrt.
{31664}{31735}Prelazio sam bezdan!
{31820}{31880}Bio sam skoro tamo.|[ uzdah ]
{31916}{31952}[ riga ]
{32936}{32984}[ muškarac ]|Da, dobro.
{32984}{33068}[ Christian ]|Pa, ne morate znati podrobnosti o sluèaju.
{33068}{33116}Da, odlièno.
{33119}{33167}[ muškarac ]|Christian. Hej, zapovjednièe.
{33170}{33225}[ zapovjednik ]|Javite mi se kad završite.
{33238}{33270}Gage.
{33322}{33368}Michael?
{33388}{33440}[ Christian ]|Neæemo objaviti nikakvih informacija.
{33460}{33530}Izvješæe mrtvozornika|za Tianau Moore.
{33532}{33628}Potvrdio je da je bila mrtva|72 sata prije no ste izvukli tijelo.
{33628}{33711}[ Christian ]|Jer je maloljetna - Ima još.
{33718}{33782}[ Christian ]|Dobro! Zašto ne otpuzaš natrag pod kamen?
{33785}{33844}Neæe èekati, Church.|Mogu podnijeti.
{33860}{33976}Našli su nizove simetrièno smještenih|rana bušenja...
{33976}{34096}kroz ovojnice i|slojeve epitela kože lica,
{34096}{34144}dojkama i genitalijama.
{34144}{34192}[ Christian ]|Ugodan dan želim. [ spušta slušalicu ]
{34192}{34312}Sudeæi po mjeseèastom|obliku ulaznih i izlaznih rana,
{34312}{34372}uèinjene su kirurškom iglom broj osam.
{34396}{34426}Dovraga.
{34426}{34516}Ni jedna od rana sama po sebi|nije bila opasna po život.
{34516}{34564}Vrlo malo krvi, zapravo.
{34564}{34602}Nisu je one ubile.
{34612}{34674}Uzrok smrti je|zastoj srca.
{34674}{34778}Imala je srèani udar?|- Tiana je mala uroðenu srèanu manu.
{34780}{34845}Trauma je izazvala udar.
{34845}{34900}Kakva trauma?
{34900}{34945}Muèena je.
{34945}{34996}* [ linija: rap metal ]
{35149}{35209}* [ glasno nastavlja ]
{35629}{35689}[ tipkanje po tipkovnici ]
{35833}{35881}[ raèunalo odzvanja ]
{35881}{35929}[ glas raèunala ]|Dobrodošli.
{36781}{36877}[ zvoni telefon ]
{36961}{37033}[ Angela ] Halo?|- Haj Angela, ovdje ujak Mike.
{37033}{37111}Hej. - Slušaj, možeš|veèeras doæi do policijske stanice?
{37117}{37153}Trebam malu pomoæ.
{37165}{37225}Dobro, upiši: "Tinsel
{37225}{37345}zarez, buttmunch, toèka.
{37345}{37429}Tinsel bomb, uskliènik."
{37504}{37567}[ Gage ] Šališ se?|Ovo je sastav?
{37567}{37624}[ zvoni telefon ]|Ovdje Christian.
{37635}{37690}Èe... Prièekajte malo.
{37696}{37756}Onaj raèunalni èudak|Bendix iz on-line servisa.
{37756}{37847}Haj, g. Bendix.|Isljednik Cage ovdje. Što za mene imate?
{37852}{37936}[ zvuènik telefona ] Imam listu koju ste tražili.|Dopustite da objasnim...
{37936}{37999}Onda faksiraj!|- Pssst! Što to?
{38008}{38098}Pa, jedno æe vas ime osobito zanimati.
{38098}{38186}Zadnja osoba s kojom je MissXXX|chatala prije nego je nestala,
{38187}{38234}znate, iz chat sobe.
{38234}{38295}Jako me zanima, g. Bendix.|Koje je?
{38296}{38406}Pa, on ili ona koristio je broj|ukradene kartice i lažne osobne podatke.
{38406}{38468}Nemamo nièeg osim|zaslonskog imena.
{38468}{38522}Ovdje detektiv Christian.|Kakva su to sranja?
{38522}{38594}Dali smo sudski nalog,|ne nekakav zahtjev,
{38594}{38655}zato obraðuj neke korisne informacije
{38655}{38730}prije nego siðem tamo i|uhitim ti megabajtsku guzicu.
{38730}{38801}Hej, hej! Steve!|Što je, g. Bendix?
{38801}{38858}Imate olovku?|Piše se...
{38858}{38954}Veliko C,|malim slovima "apt"
{38954}{39062}veliko H,|malo "owdy."
{39122}{39182}CaptHowdy?|- Da, tako je.
{39182}{39255}Korisnièko ime ostavit æu aktivnim|dok drugaèije ne kažete.
{39275}{39350}Hvala, g. Bendix.|- Sretno, isljednièe.
{39407}{39510}Što si mi ti, tata?|Nemoj mi to više raditi.
{39510}{39600}Je l' kad razmišljaš?|Hoæemo da nam pomogne, a ne mrzi.
{39600}{39660}Imamo ga.|- Imamo koga?
{39662}{39703}Kapetana Howdyja.
{39710}{39782}Koristim "Pronaði èlana"|u tražilici.
{39782}{39836}Što je "Pronaði èlana"|u tražilici?
{39839}{39875}Padajuæi izbornik.
{39875}{39959}O, Angela...|Evo tu si.
{40099}{40135}
{40160}{40200}Pridružili ste se |teen chatu.
{40460}{40500}Evo ga.
{40622}{40694}[ laje pas ]
{41020}{41060}Idi na profil èlana
{41140}{41180}
{41218}{41270}roðena 1978... uèenica... sama...
{41273}{41333}[ lavež se nastavlja ]
{41333}{41385}I, kako æemo ga upecati?
{41393}{41441}Znam kako.
{41441}{41498}Otvori njegov profil.
{41609}{41690}ulièni hokej... snowboarding...
{41690}{41750}Evo zašto ga vole.
{41750}{41798}On je cool lik.
{41798}{41860}Kako uopæe znamo da je lik?
{41862}{41960}Ne znamo.|Dobro, brzo otvori svoj profil.
{41990}{42044}Sad posvjetlaj "Hobiji"...
{42053}{42095}Obriši "Water skiing"
{42122}{42161}Umetni "Zimski sportovi".
{42407}{42479}“Tisuæe napadaju grane zla,
{42479}{42563}no jedan ga u korijenu sasijeca.”
{42580}{42653}Pitaj ima li|snowboardera u kuæi.
{43080}{43140}CaptHowdy: Raves,|kakav boarding te zanima?
{43175}{43241}Rekla sam ti. Odgovori:|"half-pipe, slobodno."
{43289}{43360}I pitaj kakvu dasku koristi.
{43643}{43717}Jesmo te!|CaptHowdy: Doðete na zabavu?
{44270}{44390}[ Captain Howdy ]|Izraz sadizam, tako je zlosretan.
{44390}{44486}Izvrši li lijeènik presaðivanje kose|li operaciju nosa,
{44486}{44534}onda je u redu.
{44534}{44606}Trudiš se i pomažeš|drugom ljudskom biæu
{44606}{44738}postiæi viši nivo|duhovne i osjetilne svijesti
{44738}{44786}tako da..
{44786}{44846}Oh, ne znam...
{44870}{44930}Bušeæi mu genitalije...
{44930}{44990}i kažu da si bolestan.
{45026}{45074}Kakav želiš?
{45110}{45158}[ muškarac jeca ]
{45158}{45206}[ Captain Howdy ]|Mmm... ampallang.
{45210}{45266}Dobro odabrano.
{45266}{45314}E to je piercing!
{45314}{45398}[ jecanje nastavlja ]|Svakako, to je opipljiv posao.
{45422}{45482}Moramo proæi kroz spužvasto tkivo,
{45482}{45535}pa æe malo krvariti.
{45536}{45608}A ne daj Bože,|pogoditi kavenozno...
{45608}{45674}[ šapuæe ]|krv šiklja posvuda.
{45773}{45868}Kako kažu, plemenske žene u Borneu
{45869}{45989}ni ne pomišljaju na seks|s muškarcem koji nema ampallang.
{45989}{46089}One koje su moj iskusile,|zbilja su uživale.
{46090}{46133}Nije li tako?
{46133}{46181}Èisto!|Idemo!
{46181}{46266}Gibaj, gibaj, gibaj!|- Ovdje èisto! Stepenicama!
{46268}{46316}Èisto!|Idemo, idemo!
{46340}{46388}Idemo!
{46412}{46460}Onda dobro.
{46496}{46556}Prihvatimo se.
{46556}{46592}Gibaj!
{46592}{46640}[ jauk, prigušeno vrištanje ]
{46676}{46760}Gibaj desno!|[ pojaèan jauk ]
{46760}{46800}Pogledaj ovamo!
{46868}{46916}[ glasno, prigušeno vrištanje ]
{46964}{47012}[ cviljenje ]
{47036}{47132}[ oboje dahæu ]|[ tiho vrištanje ]
{47132}{47180}[ stenje ]
{47216}{47264}Moje tablete.
{47276}{47342}[ stenjanje nastavlja ]
{47450}{47510}[ zveket metalnog oruða ]|[ cviljenje nastavlja ]
{48038}{48086}Prošlo je dobro.
{48086}{48134}Da.
{48134}{48182}Gdje je Gage?
{48242}{48305}Ne mogu zamisliti|kroz što prolazi.
{48314}{48362}U pravu si.
{48362}{48410}[ uzdah ]
{48410}{48458}Idem s njim razgovarati.
{48518}{48602}[ muškarac ]|Pozornièe, što se zbiva?
{48602}{48674}[ razgovor nastavlja, utišano ]
{48674}{48722}Želiš društvo?
{48758}{48800}Ne.
{48818}{48870}Hoæeš znati što Gen misli?
{48877}{48962}[ Gage ] Nitko je neæe naæi.|- Ma daj, Mike.
{48986}{49058}Možda ima pravo.
{49106}{49166}Èuj, Mike,|uhvatit æemo mi njega.
{49202}{49250}[ èisti grlo ]
{49553}{49625}[ laje pas ]
{49709}{49757}[ lavež nastavlja ]|[ uzdah ]
{50381}{50441}[ zvonjava ]|[ glas raèunala ] Dobrodošli
{50602}{50670}CaptHowdy: Gdje si bila Raves?|Èekao sam svu noæ. Ili da te zovem "murjak"?
{50900}{51050}Zovi me detektiv. Tko si ti?|Ovo je neka bolesna šala?
{51344}{51452}[ Captain Howdy na raèunalu ] Korištenje izraza "bolesno"|da bi se umanjilo i omalovažilo...
{51452}{51510}Navlaèenje vela preko stvarnosti
{51510}{51584}[ pas laje ]|koju se nije moæi protumaèiti.
{51596}{51668}Lijepa vježba noæas.|Nadam se, niste suviše razoèarani.
{51678}{51750}Klikni snimanje i odgovori na trenutnu|zvuènu poruku CaptHowdyja.
{51840}{51890}[ lavež nastavlja ]|Klikni snimanje i odgovori CaptHowdyju...
{51902}{51998}To je dio posla.|Dio potrage za tobom.
{51998}{52084}Inteligentan si.|Zašto se sam ne predaš?
{52103}{52157}[ lavež nastavlja ]
{52205}{52265}[ raèunalo zvoni ]
{52265}{52367}[ Captain Howdy ] Neæe li pobjeda predajom|biti isprazna?
{52367}{52448}Hajde. Naði me.
{52448}{52520}[ lavež nastavlja ]
{52742}{52793}[ lavež nastavlja ]
{52901}{52960}[ Captain Howdy ]|...biti isprazna?
{52965}{53009}Hajde. Naði me.
{53021}{53093}[ lavež psa na poruci ]
{53231}{53288}Naði me.|[ pas laje ]
{53300}{53378}[ lavež nastavlja na raèunalu ]
{55336}{55378}[ zveket lokota ]
{57038}{57110}* [ metal, prigušeno ]
{57220}{57284}* [ nastavlja glasnije ]
{57464}{57512}* Well, i'm a man *|ja sam èovjek
{57536}{57584}* I can't wait|ne mogu èekati
{57620}{57656}* I'm a man|ja sam èovjek
{57692}{57740}* Ain't i great|nisam li velik
{57776}{57812}* I'm a man|ja sam èovjek
{57848}{57884}* Real motherfucker|pravi mamojebaè
{57920}{57968}* You ain't shit|nisi ni govno
{58004}{58052}* Just another sucker|nego još jedan pušaè
{58100}{58160}* [ nastavlja ]
{58496}{58556}[ jeca ]
{58760}{58796}[ jecanje ]
{59060}{59156}[ jecanje ]
{59240}{59312}Oh, Gen!| - [ jecanje ]
{59348}{59408}Oh, Genny. Tu je tata.|Genny.
{59408}{59462}U redu je, dijete.|Tu sam.
{59468}{59540}Ne mièi se dušo.|Pssst. Dobro je.
{59552}{59636}[ cvileæi ]|- U redu, dušo. Još malo i gotovo.
{59664}{59732}U redu, dušo.|Drži se, dobro?
{59804}{59852}[ glasni metalni škljocaj ]
{59852}{59924}[ cvljenje pojaèava ]
{59924}{59972}Psst! Ma dobro!|Tu je tata.
{59972}{60044}Bit æemo vani za tren, dobro?|Pojaèanje stiže.
{60056}{60104}[ prigušeno urla ]|- Evo ga.
{60104}{60152}[ Captain Howdy urla ]
{60896}{60944}Aaaah!
{60956}{61016}[ stenje ]
{61040}{61088}Aaaah!
{61176}{61238}[ pucanj ]|Aaaah! Ohhh!
{61286}{61334}Daj mi neki razlog!
{61334}{61406}[ kliktaj oroza ] Daj mi razlog|bolesna guzico!
{61478}{61550}Gadurino kopile!|Daj ruku!
{61562}{61652}[ Gage zadihan ]|[ lisice škrebeæu ]
{61738}{61786}Gadurino kopile!|[ stenje ]
{61786}{61846}Dobro je, zlato.
{61846}{61918}[ Genevieve nastavlja cviljeti ]
{61954}{62026}[ tiho cerekanje ]|U redu, Geny.
{62026}{62086}[ uzdiše stenje ]
{62146}{62194}[ Gage ] U redu.|[ uzdiše ]
{62194}{62235}Skoro gotovo.
{62242}{62290}[ cerekanje ]
{62290}{62380}Nisam se cijelog|života nièega bojao.
{62380}{62422}Znaš zašto?
{62422}{62470}Jer sam želio biti mrtav.
{62494}{62542}Zašto to željeti?
{62542}{62590}Nemam se više èega bojati.
{62626}{62686}Samo mržnju imam za žvot.
{62722}{62782}To mi je jedini užitak.|[ cereka se ]
{62782}{62866}[ prigušeno cerekanje ] I ja želim|da si mrtav, takoðer.
{62902}{62962}[ smijanje ]
{63094}{63166}[ šapuæe ]|Gotovo je. Dobro.
{63166}{63214}Evo ga.
{63310}{63382}[ nastavlja se smijati ]
{63382}{63466}Hajde. Pssst.|Dobro. Ne plaèi, dijete.
{63471}{63555}Hajde. Idemo odatle van, |da mogu pomoæi ostalima.
{63555}{63603}[ radio, najavljivaè ]|Vrijeme, prognoza i...
{63603}{63660}[ radio, izvjestitelj]|U spokojnom Helvertonu, u Koloradu,
{63660}{63721}detektiv je danas tražeæi svoju kæer
{63721}{63780}otkrio istinsku|kuæu užasa.
{63780}{63850}Na nesreæu, našao je|puno više no što je tražio.
{63850}{63922}[ radio, domaæin emisije ] Captain Howdy prošao|s priznanjem ludila.
{63922}{64020}Pogledajte ga. On je lud.|[ žena ] - Izgled s tim nema veze.
{64020}{64099}Jedino pitanje je,|shvaæa li...
{64099}{64147}[ tipkanje teleprintera, žena izvjestitelj ]|Glavna je vijest...
{64147}{64250}da Carleton Hendricks nije|proglašen krivim zbog ludila.
{64255}{64300}[ radio, domaæin emisije ] Captain Howdy,|prekrasno.
{64300}{64352}Murjaci su ga trebali ubiti,|dok su mogli.
{64363}{64411}[ muški izvjestitelj ] Unatoè silnim|lokalnim protestima,
{64411}{64515}Carleton Hendricks, zloglasni|Captain Howdy, je osloboðen.
{64519}{64603}U lijeènièkom izvješæu stoji|da se potpuno i sveukupno promijenio.
{64603}{64665}Carleton Hendricks|je promijenjen èovjek.
{64665}{64720}èetiri godine kasnije
{64860}{64925}* Yes, i must peel away the skin|da, moram oguliti kožu
{64929}{64976}* And cut away the flesh|i odrezati meso
{64977}{65049}* To discard, expose and absolve|da odbacim, izložim i oslobodim
{65049}{65145}* The pain such a cold heart longs|bol za kojom srce hladno èezne
{65145}{65229}* To express with groans|izrazim ju jecajima
{65260}{65300}[ žena na razglasu ]|Liniju tri, molim.
{65416}{65480}* [ muški pjevaè šapuæe ]|Iznad!
{65524}{65600}[ izražajno ]|Iznad!
{65620}{65710}[ vrištanje ]|Iznad!
{65728}{65816}Iznad!
{65824}{65896}Iznad!
{65908}{65966}[ žena ] Morali su|krivo razumjeti.
{65968}{66034}Nisu to mogli reæi.|To je bolesno.
{66040}{66083}Zbilja su ga pustili?
{66088}{66170}[ muškarac ] Hendricksa? Morali su.|Carleton je promijenjen èovjek.
{66170}{66222}Prošao je sve|faze lijeèenja
{66222}{66285}i odlièno je ocijenjen|od nadzornog odbora.
{66290}{66358}Sud ne nalazi razlog zašto bi ga držali.|Èovjek može iæi.
{66358}{66459}[ žena ] Ne po mom.|To što je djeci napravio je nesavjesno.
{66459}{66512}[ muškarac ] Što je|Captain Howdy napravio, je li?
{66512}{66592}Carleton Hendricks,|kao da ga ni nema.
{66676}{66716}[ kucanje na vrata ]
{66760}{66825}Spreman ste za rock 'n' roll?|- Hej, Sam.
{66856}{66930}Došao veliki dan,|a vi lice zakopao u knjigu.
{66964}{67012}"Povukao sam se
{67012}{67086}iz gužve gradova i gomile
{67096}{67182}i dane provodim|okružen knjigama mudrim,
{67192}{67260}prozorima svjetla|našeg života
{67264}{67325}obasjanim sjajem duša ljudskih."
{67336}{67414}Aha. To je Hendricks izvorno?
{67414}{67456}[ smiješi se ]|Želio bi.
{67456}{67500}To je H. G. Wells.
{67504}{67590}A što H. G. Wells ima reæi|o današnjem odlasku kuæi?
{67590}{67648}Na nesreæu, ništa.
{67660}{67705}Malko sam nervozan.
{67720}{67800}Ne bi te pustili|da ne misle da si spreman.
{67804}{67866}Drži se svojih lijekova.
{67869}{67920}I bit æeš dobro, a?
{67948}{67984}Poðimo.
{68020}{68070}Carleton, bolje da vas upozorim.
{68070}{68164}Odbor dobrodošlice|vani vas èeka.
{68180}{68224}Nisu presretni.
{68236}{68270}Mogu zamisliti.
{68320}{68350}Ne.
{68368}{68410}Mislim da ne možete.
{68500}{68620}[ preklapanje ljutitih glasova udaljeno ]
{69448}{69507}Mama? Tata?
{69510}{69544}Doma sam!
{69592}{69652}[ Captain Howdy ]|Èin sporog probadanja
{69652}{69736}transcendentalni je duhovni dogaðaj.|- Ne! Ne!
{69736}{69832}[ vrištanje ] Nije bol.|Nego osjet.
{69904}{69998}Pazi kako tijelo|doživljava osjet!
{69998}{70050}Predaj se doživljaju!
{70055}{70096}Osjeti navalu endorfina
{70096}{70180}dok kirurški èelik prorezuje!
{70192}{70240}Tata!
{70240}{70312}[ cviljenje ]
{70312}{70372}Hej, Genny, Genny, Genny.
{70372}{70436}Dušo. Psst!|Dobro, dijete.
{70436}{70485}[ jecanje ]
{70499}{70555}To je san.|Tu je tata.
{70555}{70595}Nitko ti neæe ništa, dušo.
{70607}{70679}Psst.|Ohh, dijete.
{70703}{70775}Ne plaèi.|Ne plaèi. Ne plaèi.
{70775}{70847}Ne plaèi, dušo. Dobro je.
{70847}{70919}Dobro. U redu.|[ jecanje nastavlja ]
{70943}{70985}[ šapuæe ]|Dobro.
{70985}{71030}[ muškarac ] Ponio si dopunsku bateriju?
{71030}{71090}[ reporter ] Ovo je prizor|pred domom Carleton Hendricksa,
{71092}{71185}èovjeka koji je, unatrag tri godine,|odgovoran za otmicu i muèenje
{71185}{71282}petero mladih i za preranu|smrt šesnaestogodišnjakinje.
{71283}{71342}Carol Anne Chalmers-Perez|je u kadru.
{71379}{71411}Možete nam iskazati što osjeæate
{71411}{71460}u vezi oslobaðanja|Carletona Hendricksa?
{71460}{71518}Nemam komentara.|- Nešto morate misliti..
{71518}{71566}Taj vam je èovjek|povrijedio kæer.
{71566}{71615}[ uzdah ]
{71638}{71696}Ja sam Carol Anne Chalmers-Perez,
{71696}{71780}pred domom Carletona Hendricksa,|izvješæujem za Channel 4 News.
{71780}{71840}[ škljocanje aparata ]
{71885}{71950}[ žena ] Idi natrag na odjel psihijatrije!
{71972}{72024}[ žena nastavlja ] |Ti si sin Satanov.
{72144}{72206}[ muškarac ] Spali ga, kopile!|Psihotièni luðak!
{72206}{72282}Dati æu ktratku izjavu!|[ brbljanje istovremeno ]
{72290}{72426}Molim vas, g. Hendricks|prolazi tešku tranziciju.
{72426}{72470}Vi ga ometate.
{72470}{72576}Sud je odredio da|g. Hendricks nije kriv.
{72576}{72692}Tjeraj ga iz grada, bolesnika! - Za vrijeme|suðenja proveo je godinu u zatvoru
{72692}{72764}i tri godine|u državnoj ustanovi.
{72780}{72885}G. Hendricks je|izlijeèen i otpušten.
{72888}{72956}[ ruganje, vikanje ]|G. Hendricks nema što reæi.
{72958}{73016}Da.
{73066}{73103}Imam.
{73234}{73310}[ muškarac ]|Èudovište koje ubija!
{73394}{73450}Žalim.|[ žena ] - Mièite!
{73472}{73530}Gospodine Isuse Kriste,|gorjet æeš u paklu,
{73530}{73590}žališ, kopile jedno!?
{73665}{73732}[ žena ]|Žališ, kopile jedno!?
{73816}{73888}Netko se mora pobrinuti|za tog momka.
{73936}{73984}Je li?
{74248}{74340}Draga, gdje je|u guzici tvoja kæer?
{74344}{74392}Vjerojatno je s prijateljima.
{74392}{74442}Ne, ne, ne, ne, ne.
{74452}{74500}Reæi æu ti gdje je.
{74524}{74600}Vani se gužva s nekim|nogometašem iz škole.
{74608}{74656}[ grmljavina ]
{74656}{74752}Dušo, sigurno je dobro.|Vjerojatno je izgubila pojam o vremenu.
{74812}{74889}...zbog potencijalno opasnog|uvjetnog puštanja
{74889}{74966}iz državne mentalne ustanove,|ovog tjedna.
{74972}{75056}Carleton Hendricks,|znan i kao Captain Howdy,
{75056}{75128}roditelje i zabrinute graðane razbjesnio je
{75128}{75164}svojim otpuštanjem
{75166}{75230}i povratkom u|zajednicu Helverton, Kolorado,
{75232}{75302}gdje su sjeæanja na|gnusne zloèine koje je poèinio
{75302}{75350}pred samo èetiri godine...
{75350}{75415}još svježa u sjeæanjima|lokalnog stanovništva.
{75418}{75518}Dužnosnici Kolorada rekli su citiramo:|"Ruke su nam vezane".
{75520}{75580}Moraju "Slijediti|slovo zakona."
{75596}{75668}[ odvjetnik ] Za vrijeme suðenja|proveo je godinu u zatvoru
{75668}{75736}i tri godine|u državnoj ustanovi.
{75736}{75808}[ prasak groma ] G. Hendricks|nema što reæi.
{75808}{75868}[ Hendricks na TV-u ]|Da. Imam.
{75868}{75928}Žalim.
{75938}{76004}Gospodine Isuse Kriste,|gorjet æeš u paklu!
{76004}{76076}Žališ, kopile jedno!?
{76076}{76160}[ voditelj ] Prognoza, pljuskovi, teški povremeno,|uz mjestimiène oluje...
{76160}{76256}A to govance, a?|Natrag na ulice?
{76256}{76330}Doðe li blizu mojoj djevojèici,|ubit æu ga.
{76376}{76424}Jack!
{76460}{76520}Dušo, sigurno hoæeš|još jedno?
{76520}{76560}Kelly je dobro.
{76580}{76698}Psiho životinja šeta vani,|možda s kæeri našom,
{76698}{76736}a ti kažeš da je sve u redu?
{76736}{76820}I tko si da mi govoriš kad sam|dovoljno popio? - U redu!
{76820}{76858}Gdje je telefon?|Hmm?
{76860}{76910}Gdje je telefon?!|Daj telefon!
{76912}{76976}Zvat æemo policiju...|Jack!
{76976}{77048}Prekasno.|Imali su svoju priliku.
{77048}{77120}Što ideš napraviti?|- Što je veæ trebalo napraviti.
{77120}{77168}[ zvonjava ]
{77216}{77252}[ muškarac ]|Halo?
{77252}{77312}Pajdo G.|Ovdje Jackson.
{77312}{77384}Hej Jacks. Što ima?|- Sluša, ja...
{77384}{77428}Mislim da je Howdy uhvatio Kelly.
{77428}{77492}Sranje.|- Da.
{77492}{77576}Izvrti pozive i naðemo se u klubu.|I Gino?
{77576}{77624}Da?|- Ponesi opremu.
{77624}{77696}* [ metal ]|[ stenju, dahæu ]
{77768}{77852}* Welcome to my tidal wave|dobrodošao na moj plimni val
{77936}{78044}[ izdiše ] * How i arrived i can't explain|kako sam stigao ne mogu objasniti
{78128}{78200}[ nastavlja se ]|Eric?
{78212}{78320}Nemoj mi sad zaspati.|Moram do ponoæi doma ili æe tata pošiziti.
{78320}{78428}* When everyone just runs away|[ gunða ] dok su svi pobjegli
{78428}{78476}U redu.
{78476}{78570}* postoji tajno mjesto|Probudit æu te za, oko pola sata.
{78570}{78644}* I like to go|kamo volim iæi
{78644}{78692}* Everyone has left|svi su otišli
{78728}{78788}* But their face don't show|ne vidi im se na licima
{78838}{78898}Hajde!|[ muškarci reže ]
{78922}{78994}Jebeno èudovište!|Gdje je?
{78994}{79078}Šti si uèinio mojoj kæeri?|[ muškarac ] - Psihotièaru!
{79114}{79210}[ stanje ]|[ muškarci reže ]
{79318}{79390}Voliš bol, psiho?
{79462}{79522}[ muškarac ] Hajde!|Vrati se tamo!
{79726}{79774}[ grmljavina ]
{79774}{79846}Gino.|[ dahæe ]
{79846}{79906}Idemo na vožnjicu.|[ smijeh muškaraca ]
{79930}{79978}Dobit æeš svoje, momèe!
{79990}{80038}Momèiæu!
{80078}{80138}[ Jackson ] Idemo!|Ulazi u auto!
{80138}{80198}[ muškarac ]|Imat æemo zabavicu!
{80198}{80270}[ paljenje motora ]|[ zatvaranje vrata ]
{80342}{80390}Idamo po ostale.
{80402}{80450}[ vikanje ]
{80534}{80582}[ muškarac ]|Uuhuu!
{80642}{80714}[ žena na policijskom radiju, nejasno ]
{80798}{80858}[ grmljavina ]
{81266}{81314}Poðimo!
{81314}{81362}Mièi noge proklete!
{81362}{81410}Držat æe.|Dobro zategni.
{81542}{81602}[ galami ]|Dolazi!
{81638}{81690}Idemo!
{81698}{81758}Daj uže.|Tu je.
{81770}{81818}Daj njegove ruke!
{81878}{81976}Umri, kopile.|[ muškarac ] - Daj ga ovamo.
{81986}{82070}Smrt je...|poput starog prijatelja.
{82214}{82286}Objesi kurvino kopile!|- Da!
{82334}{82394}Gade!|- Vješaj ga!
{82778}{82862}[ krklja ]
{83090}{83150}[ muškarac ]|To!
{83150}{83198}[ udar groma ]
{83290}{83350}Hajde!|Odlazimo!
{83390}{83486}[ mrmljanje, žamor ]
{83546}{83594}[ grmljavina ]
{83702}{83774}[ grana pucketa ]
{83810}{83858}[ glasan prasak ]
{84122}{84206}[ zadihan, kašlje ]
{84506}{84542}Kako napeto!
{85100}{85190}Dobrodošli u HELVERTON|Stanovnika 350.000 Nadmorska...
{85190}{85290}"Lijep za posjetiti|još bolji za napustiti"
{85800}{85860}[ muškarac ] U redu.|Uði.
{85860}{85944}[ žamor nastavlja ]
{86004}{86070}[ muškarac ]|Sjedni si.
{86094}{86142}To ti je zadaæa?
{86150}{86210}[ djevojka ] Da, za prirodu.|Jako teška.
{86210}{86280}Madeline?|Izlazi!
{86300}{86370}Poèinje mi se spuštati,|zaboga.
{86375}{86462}Odmah dolazim.|Nije to lako navuæi, znaš.
{86462}{86510}[ grgljanje, klepet ]
{86510}{86560}Koji Bog je tamo?
{86582}{86630}Glupa drolja.
{86666}{86763}Hej, dobro.|Tako.
{86810}{86870}Daj joj što hoæe, odmah.
{86870}{86978}* [ disko ]
{86978}{87030}Oh, da.
{87175}{87242}Doði tati.
{87326}{87386}[ udiše ]|Oh!
{87386}{87470}Dovraga, izaði.|Pališ me!
{87470}{87554}[ smijeh ]
{87638}{87698}[ dahæe ]
{87746}{87800}Dosta tog sranja!
{87820}{87880}Dolazi ovamo.|[ i dalje dahæe ]
{87902}{87962}Jesi li gluha?
{87970}{88080}Rekao sam dosta plesnog sranj...|Bože, Maddy.
{88120}{88154}Što?
{88202}{88250}Što ti se dogodilo|s vratom?
{88274}{88334}Maddy!|Ti?
{88334}{88406}Hoæeš se loptati, strašilo?|- Ohh!
{88406}{88454}[ tresak tijela ]
{88634}{88700}[ Christian ] Nemoj biti tako krut.
{88700}{88764}Daj, radimo što nam je u moæi.
{88784}{88818}Hej, Mike.
{88832}{88916}Sirota Kelly Roth misli|da je ona kriva za osvetu.
{88916}{88964}Dogodilo bi se,|s njom i bez nje.
{88976}{89024}[ zvonjava ]
{89099}{89160}CaptHowdy: Mrtvi su mrtvo mrtvi,|kad su mrtvi.
{89286}{89322}[ zvonjava ]
{89330}{89366}CaptHowdy: Voliš svoju znaèku, Michael?
{89366}{89448}Reci da, prikaèenu na|njegovo debelo crijevo.
{89520}{89580}[ zvoni telefon ]
{89580}{89640}[ nastavlja zvoniti ]
{89652}{89724}Javi se.|[ zvoni ]
{89748}{89822}Dvanaesta postaja.|Detektiv Christian.
{89832}{89916}[ Howdy na telefonu ] Ja sam od onih|kojima je suvišno bitno.
{89916}{89988}A ti, bez tebe mogu.
{90012}{90077}On je.
{90228}{90288}Spreman si pristupiti, Carletone?
{90288}{90336}Misliš da je tvoja znaèka moæ.
{90336}{90420}Nije.|Znanje je moæ.
{90420}{90480}Tvoja znaèka nije ni trajna.
{90480}{90545}Moje znaèke,|ne mogu se skinuti.
{90555}{90660}Razdvajaju me od ostalih|do dana moje smrti.
{90660}{90768}Moje znaèke su vjeène,|a tvoje su podobnost.
{90768}{90828}Tvoje znaèke ne znaèe ništa.
{90828}{90876}Moje znaèke|predstavljaju zakon.
{90876}{90924}Trebam uslijediti Gageovu|vanjsku liniju.
{90924}{91020}Koji zakon, Michael?|Zakon koji me nije osudio krivim?
{91020}{91116}Ili zakon koji dopušta drugima|uzeti stvar u svoje ruke?
{91116}{91176}Bilo je pogrešno.|- Ne, ti si pogrešan!
{91176}{91236}Svi ste pogrešni!
{91279}{91351}Pronašao sam sad cijelo|novo stado koje potrebuje
{91351}{91447}duhovno buðenje|u rukama mojim mirnim.
{91447}{91531}Gdje si, Carleton?|Reci mi gdje si.
{91605}{91651}Jebem ti!
{91657}{91777}Neki žele da im se sve da|s velikom crvenom mašnom,
{91777}{91825}ali ne i ti.
{91825}{91909}Ti ne želiš, je li?|[ prigušeno vikanje ]
{91957}{92017}Kad je dovoljno, a?
{92045}{92113}Kažu da preobiljem
{92113}{92173}stižeš u palaèu mudrosti,
{92173}{92233}pa ne znamo kad je dovoljno...
{92233}{92281}[ vrištanje ]
{92281}{92377}dok ne saznamo|kad je više nego dovoljno.
{92377}{92449}[ vrištanje ] Oh, prestani biti beba.
{92460}{92538}Ne voliš me previše,|je li, Jacks?
{92538}{92569}[ prigušeno vikanje ]
{92593}{92641}Shvaæam.
{92641}{92749}U našem društvu, fizièke|razlike plaše ljude.
{92749}{92809}Oh, možeš biti...
{92809}{92893}pakleno nastran iznutra
{92899}{93005}ali napravi fizièku sitnicu kao...|O, što ja znam,
{93007}{93055}tetoviraj lice,
{93055}{93127}i èovjeèe,|svi se užasnu.
{93127}{93199}Prokletstvo našeg društva|je što se moramo
{93199}{93272}uklopiti u kruti uzorak|da bi pripadali.
{93277}{93343}Nema mjesta mašti
{93343}{93391}i stvaralaštvu.
{93427}{93485}[ jecanje ]|Ti to plaèeš?
{93540}{93580}Jacksy.
{93588}{93633}[ ceri se ]|Jacksone!
{93643}{93736}Nema plakanja.|Nisi dijete.
{93758}{93865}Djetinjstvo ti je završilo trenom|kad si saznao da moraš umrijeti.
{93865}{93919}[ mumljanje ]
{93919}{93991}[ zveket metala ]
{93991}{94039}[ mumljanje ]|Sunèana.
{94087}{94148}Vrijeme da proširimo tvoje...
{94149}{94207}duhovne vidike.
{94207}{94258}[ prigušeno vrištanje ]|Vjeruj mi.
{94265}{94339}Potrebno ti je izvantjelesno iskustvo.|[ prigušeno vrištanje ]
{94377}{94410}Što je ovo?
{94435}{94519}[ mrmlja ]|Veæ jesi duhovno osviještena?
{94519}{94639}Sunèice, moj dragi|stari otac mi je govorio...
{94641}{94699}nemoj brkati oèaj...
{94699}{94765}sa duhovnim buðenjem.
{94795}{94854}Pripremi se za|Kavandi ritual.
{94855}{94928}Prigrli koplja Šivina.
{94951}{95047}Pati, kæeri moja,|noseæi Itiburi.
{95071}{95131}Hoæe li kæer prihvatiti Itiburi?|[ jecanje ]
{95167}{95263}Protumaèit æu kao da.|Ne mièi.
{95263}{95371}Bol je važan dio našeg povezivanja.|[ prestrašeno jauèe ]
{95371}{95443}Fizièki užas povezuje nas
{95443}{95490}još snažnije.|[ vrišti ]
{95515}{95575}Silina doživljaja...
{95575}{95635}proširuje bezdan izmeðu nas
{95635}{95719}i onih koji ga|s nama ne dijele.
{95743}{95850}Moraš se izdiæi iznad onoga|što tijelo osjeæa kao bol.
{95859}{95908}Pretvoriti to u zadovoljstvo|[ glasno jecanje ]
{95910}{95990}a onda u duhovni dogaðaj.
{96005}{96058}Ti ne osjeæaš bol.
{96058}{96135}Tijelo osjeæa bol.|[ vrištanje ]
{96259}{96315}Dakle, možda osjeæaš bol.
{96380}{96445}...PAKAO-GRAD...
{96445}{96499}[ otvaranje vrata auta ]
{96500}{96540}[ zatvaranje vrata ]
{96561}{96609}Hvala.|[ uzdah ]
{96609}{96693}[ zvoni telefon ]
{96741}{96837}Da. Gage.|- Hej. Nije pravi trenutak?
{96837}{96925}Krenuli smo preko u bolnicu|vidjeti kako je Madeline Rooth.
{96929}{96993}Kako ide kod tvoje mame?
{96993}{97070}Ona dobro. Ja dobro.|Voljela bih da si ovdje.
{97075}{97125}Da, i ja.
{97125}{97177}A... Gen se vratila kuæi?
{97178}{97237}Što prièaš?|U školi je.
{97238}{97310}Zvala sam školu.|Kažu da je otišla juèer.
{97315}{97346}Što?
{97370}{97425}U školi kažu da si zvao.
{97454}{97562}Uh, uh...|- Mike?
{97562}{97646}Uh... Na putu sam kuæi.
{97706}{97758}[ gume cvile ]
{97868}{97941}[ signal zauzete linije ]|Oh, Bože, nemoj dopustiti.
{97941}{98006}[ signal zauzete linije ]
{98006}{98066}[ trubi sirena ]
{98114}{98162}[ gume cvile ]
{98238}{98310}[ Mike ]|Genevieve! Toni!
{98364}{98436}Oh, ne.|Èovjeèe!
{98436}{98508}Što? Nema pozdrava?
{98520}{98576}Gdje je moja kæer, Hendricks?
{98588}{98640}Genevieve je sa mnom.|[ Toni jeca ]
{98640}{98700}Poduzimam osobitu brigu o njoj.
{98724}{98796}Morate voljeti ovu tehnologiju.
{98796}{98856}Detektiv "kako se ono zove"
{98856}{98928}raspada se, kako je vidjeti.
{98928}{99010}A ovo je ljupka gða Gage?
{99020}{99116}Kakvo neoèekivano,|pa ipak ugodno iznenaðenje!
{99116}{99204}Što si napravio mojoj kæeri,|jebeno kopile?
{99216}{99276}Oh! Vatreno.
{99276}{99384}To trebam.|Možda sam krivu uzeo.
{99384}{99435}Zašto Genevieve?|Što ti je napravila?
{99435}{99498}Ona... nije ništa.
{99498}{99548}Niste joj rekli?
{99560}{99606}Niste, je li?
{99615}{99715}Kako humano. - O èemu|on to? Što mi nisi rekao?
{99715}{99768}Mike, blizu smo mu.|Drži ga on-line.
{99768}{99888}Znaš, bol je osobit|osobni doživljaj.
{99900}{99996}Što dulji nakit,|bol je kraæa. [ jecanje ]
{99996}{100050}Oh, Bože. Oh, ne, ne.|- Šteta što nisi ovdje.
{100050}{100140}Dok piercingi su svježi,|seksualno uzbuðenje
{100140}{100200}je za umrijeti.
{100200}{100272}Sadistièka vreæo govana!|Ubit æu te!
{100272}{100336}Kunem se Bogom,|ubit æu te! - Stani, stani.
{100336}{100392}Sadistièki? Zaista?
{100392}{100484}Životinja je ugrabila Genny.|Stvarno ga hoæeš razbjesniti?
{100484}{100622}Sadistièko nalazim dosadnim.|Zanima me podizanje ljudske svijesti,
{100622}{100696}mijenjanje stanja|primitivnim ritualima.
{100696}{100747}Hej, kamo svi odoše?
{100747}{100827}U redu, zlato. Tata æe te naæi.|Drži se.
{100829}{100937}Oh! "Tata æe te naæi.|Drži se." Jezivo! Kad?
{100937}{101021}Molim te, Carletone,|preklinjem te.
{101021}{101095}Uzmi mene.|Moju kæer pusti.
{101095}{101172}Primamljivo, ali znaš...
{101172}{101222}Gen i ja tek smo...
{101222}{101318}zagrebali površinu|naše veze.
{101328}{101378}Toliko mesa,
{101378}{101426}a malo vremena.
{101498}{101570}Što... se dogaða?
{101654}{101735}Ne.|- Oh, ne!
{101774}{101833}[ grcanje ]|Ne!
{101833}{101882}[ ljutito gunða ]
{101900}{101982}[ klopot ]|Toni?
{102044}{102087}Što je time mislio?
{102122}{102194}Što mi nisi rekao?
{102194}{102254}[ jecajuæi ]|Što si uèinio?
{102254}{102310}Što si uèinio?
{102314}{102374}Što nisam uèinio.
{102462}{102538}[ žena na policijskom radiju ] Patrola 9,|ispitajte neovlašteno djelovanje
{102538}{102612}na East Halifax 410.
{102660}{102756}Patrola 9 na raspolaganju.|Brava je obijena. Unutra smo.
{102756}{102809}Potvrdite odobrenje.
{102811}{102908}10-4, patrola 9.|Imate odobrenje. Možete postupiti.
{102982}{103036}[ lift stao ]
{103666}{103760}Patrola 9. Neidentificirani|uljezi u prostorijama.
{103760}{103810}Zahtijevamo hitno pojaèanje.|Prijem.
{103810}{103894}[ dispeèer ] Postupite oprezno.|Pojaèanje stiže.
{104386}{104458}* [ glasni rap metal ]
{104470}{104515}* Take a look around|pogledaj okolo
{104515}{104566}* You forgot what you came here for.|zaboravili ste po što ste došli
{104566}{104614}Sranje!
{104650}{104710}* You can't forget my name|ne možete mi zaboraviti ime
{104710}{104730}* Take a look |pogledaj
{104730}{104806}* Take deep breath recollect yourself |duboko udahni, skockaj se
{104806}{104878}[ cmizdri ]
{104900}{104963}* You can't forget my name uhh|ne možete mi zaboraviti ime
{105022}{105070}O, Bože.
{105166}{105226}* All right it's time to do|sve u redu, vrijeme je
{105226}{105286}* Take a look around|pogledaj okolo
{105286}{105318}* You forgot what you came here for|zaboravili ste po što ste došli
{105318}{105346}* What's your theory|koja ti je teorija
{105346}{105418}* Why you try to play that game|zašto igrate ovu igru
{105418}{105450}* You can't forget my name|ne možete mi zaboraviti ime
{105450}{105478}* Take a look around|pogledajte okolo
{105478}{105511}* Take a deep breath|duboko udahni
{105511}{105574}* Recollect yourself you know how|skockaj se znaš kako
{105574}{105634}* [ nastavlja ]|[ policajac ] Isuse!
{105680}{105742}Patrola 9! Trebam hitnu i
{105742}{105795}i pošaljite zapovjednika,|bez odlaganja!
{105802}{105870}[ ljudi vièu ] [ muškarac ]|Idemo! Gibaj!!
{105958}{106006}Može, spreman?|Spreman.
{106006}{106033}Sad!
{106162}{106217}Ovoga vozimo u opæu okružnu.|- Dobro.
{106217}{106285}Idemo.|- Vozi je!
{106433}{106493}Što je Bog mislio
{106493}{106565}kad je napravio|Carletona Hendricksa?
{106601}{106661}Zbog èega misliš|da je bio Bog?
{106661}{106721}"Xibalba."
{106781}{106886}Briga me tko ga je napravio,|jer æu ga ubiti.
{106889}{106973}Ništa ne bih volio više|no vidjeti ga mrtvog.
{106973}{107033}Michael, tko smrti nalikuje,|najviše se opire smrti. CH.
{107033}{107080}A to on želi.
{107153}{107213}Ne smijemo, a i ne želim.
{107213}{107261}[ zavijanje udaljenih sirena ]
{107273}{107309}Idem pogledati Genevieve.
{107501}{107573}* [ glasni heavy metal ]
{107741}{107813}* [ muškarac pjeva ]
{108017}{108065}Hendricks?|* [ prestaje ]
{108065}{108113}Što?
{108173}{108257}Za onoga koji se toliko|trudi promijeniti izgled
{108257}{108325}sigurno ne želiš|biti viðen.
{108401}{108450}Gdje si, Carleton?
{108461}{108569}Ime nije nešto za zanemariti.
{108569}{108629}Ukljuèuje niz odnosa
{108629}{108749}izmeðu onog koji ga nosi|i izvora iz kog je izvedeno.
{108749}{108811}Zovi me Captain Howdy.
{108811}{108865}"Izvedeno" ?
{108869}{108953}Otac ti je bio|mornarièki ratni heroj.
{108953}{109012}Kapetan Bradford Hendricks.
{109049}{109115}Tako slaviš njegovo ime?
{109121}{109193}Zovi me Captain Howdy.
{109229}{109289}Moram s tobom razgovarati.
{109289}{109349}Tako? Prièaj.
{109397}{109457}Zašto se ne možeš|suoèiti sa mnom?
{109469}{109541}Možda nisi navikao imati posla|s nekime tko nije vezan
{109541}{109610}i nema zašivena usta?
{109613}{109673}Zato ti je neugodno, Carl?
{109673}{109769}Netko dokazom junaštva smatra
{109769}{109854}ako u boj bez oružja poðe
{109854}{109930}jer ne može naškoditi iz daleka.
{109937}{110040}Lako je junaèiti se|iza mamine haljine.
{110070}{110120}[ cviljenje guma ]
{110264}{110312}Gage!
{110312}{110365}Što je bilo?|Moj pištolj?
{110384}{110440}To te smeta?
{110462}{110522}Evo.|[ stavlja pištolj na pod ]
{110600}{110658}Znaš što je tu interesantno?
{110662}{110730}Uz svu retoriku|i beskrajno napuhavanje
{110730}{110819}nisi više od školskog nasilnika|s kompleksom proganjanja.
{110825}{110880}Muèiš one koji su slabi.
{110888}{110950}Bježiš i skrivaš se.|[ urla ] Ha?
{110972}{111064}A da ti doðem i|izbijem govna iz tebe?
{111066}{111128}Tko te zaustavlja?
{111188}{111248}[ vièe ]
{111284}{111356}Prvo sanjaš,|a onda umreš.
{111560}{111608}[ urla ]
{111692}{111770}* Ring around the rosie|ringe-ringe-raja
{111772}{111835}* Pocket full of posies|doš'o èika Paja
{111940}{111980}Ah-choo!|[ jaje muæ ]
{111990}{112040}Ah-choo!|[ jaje muæ ]
{112086}{112170}A mi djeca èuè!
{112182}{112230}Zbogom, Michael!
{112242}{112338}[ stenje ]|Mmm.
{112338}{112410}[ zadihan ]
{112485}{112557}* [ heavy metal nastavlja ]
{113010}{113103}Znaš, tatice,|Genevieve je vrištala.
{113103}{113163}Ne!
{113211}{113259}[ vrištanje, stenjanje ]
{113319}{113355}Aaah!
{113544}{113576}Michael.
{113579}{113643}Ne boj se umrijeti.
{113703}{113823}Smrt je mjerilo po kom|zbilja i razum se suditi mogu.
{113823}{113863}[ stenje ]
{113907}{113979}Genevieve ti se ima|pridružiti brzo.
{114210}{114306}Veæa li je bol,|kraæi je nakit!
{114306}{114351}[ stenje ]
{114399}{114436}Ne!
{114447}{114500}[ urla ]
{114550}{114615}[ rokæe ]|Što je, Carletone?
{114627}{114711}Ljutiš se na mene?|- Znaš...
{114747}{114843}Michael,|Genevieve se... [ stenje ]
{114843}{114903}Genevieve se|sigurno slièno osjeæala...
{114920}{114999}[ dahæe ]|dok sam bio u njoj.
{114999}{115059}[ smije se, dahæe ]
{115059}{115107}Ne.
{115155}{115240}O, što æeš sada,
{115251}{115323}[ smije se ]
{115611}{115659}Što je bilo, Carletone?
{115659}{115707}Bojiš se?
{115707}{115820}Rekao si da se|u životu nikad nisi bojao,
{115827}{115887}jer si želio biti mrtav.
{115887}{115959}Je li bilo tako?
{115971}{116015}To ti je za Genevieve,|pizdo!
{116019}{116067}Ne. Ne!
{116148}{116186}Jeee!
{116196}{116256}[ stenje ]|Jeee!
{116352}{116448}Bol je osobit|osobni doživljaj, Carletone.
{116510}{116556}[ vrišti ]|Ti...
{116556}{116637}[ vrištanje ]
{116739}{116808}Ne! Ne! Ne!
{116808}{116860}Ne!|[ cvili ]
{116949}{116997}Ne!
{117399}{117444}Aaah!
{117444}{117522}Mike, ja sam.|Doði, mrtav je.
{117550}{117599}Gotovo je.
{117645}{117681}Aaaah!
{118041}{118113}[ kašlju ]
{118140}{118189}Mike, stari.
{118189}{118240}Nisi imao izbora.
{118261}{118333}Svi imamo izbora.
{118333}{118393}Ja sam svoj odabrao.
{118393}{118441}[ uzdah ]
{118453}{118537}Reci onima iz unutarnje da sam|u bolnici. - Povrjeðen si?
{118537}{118597}Dobro sam.
{118597}{118669}Idem vidjeti obitelj.
{118729}{118777}[ uzdah ]
{119041}{119131}preveo|drdamjan
{119400}{119436}* All right|dobro
{119712}{119760}* Listen|slušaj
{119760}{119800}* Everybody says they|svi kažu
{119800}{119849}* Wanna change the world|da æe promijeniti svijet
{119849}{119952}* Everybody's got a banner to unfurl|svi barjak hoæe razviti
{119952}{120024}* Man, woman, boy and girl|muškarac, žena, djeèak i djevojèica
{120096}{120150}* On the corner, down the road|na uglu, ulici
{120150}{120193}* And up the block|u kvartu
{120193}{120225}* There's somebody who needs|netko treba
{120225}{120288}* Some of what you've got|nešto od tebe
{120288}{120372}* And they ain't askin' for a lot|i ne traže puno
{120420}{120456}* Well, God knows|i Bog zna
{120468}{120564}* You can hear the people cryin'|èuješ, ljudi plaèu
{120600}{120672}* You know you can't turn away|ne možeš im okrenuti leða
{120684}{120768}* You gotta give it a shot|i pokušaj
{120768}{120840}* Heroes are hard to find|teško je naæi junake
{120840}{120936}* Won't someone take the time|neæe se nitko zauzeti
{120936}{121008}* Heroes are hard to find|teško je naæi junake
{121008}{121104}* We need you come and shine|trebamo te, doði, blistaj
{121104}{121188}* Heroes are hard to find |teško je naæi junake
{121188}{121272}* You've got to cross that line|prekoraèi crtu
{121284}{121332}* Heroes|junake
{121332}{121404}* Are hard to find|teško je naæi
{121440}{121488}* Ooh|ooh
{121488}{121776}* [ solo dgitara ]
{121872}{121944}* [ utišava se ]
{121944}{122040}* [ vrištanje, smijeh ]
{122100}{122196}* [ vrištanje, smijeh nastavlja ]
{122520}{122580}* Oh, it's so nice to see you|o lijepo mi te vidjeti
{122580}{122700}* Up inside my dreamy little world|u mom svijetu snenom
{122784}{122855}* And it's so nice to be with|lijepo je s vama
{122855}{122952}* All you lovely little boys and girls|ljupkim deèkiæima i curicama
{123048}{123112}* Make yourself comfortable|raskomotite se
{123112}{123180}* My place is so divine|kod mene je božanstveno
{123180}{123228}* Don't you think i'm wonderfull|ne mislite da sam divan
{123228}{123300}* To say yes to you one more time|da vam ponovim da
{123300}{123396}* Stay away from Captain Howdy|kloni se kapetana Howdyja
{123420}{123480}* Stay away|kloni se
{123492}{123564}* From Captain Howdy|kapetana Howdyja
{123576}{123612}* Stay away|kloni se
{123624}{123684}* From Captain Howdy|kapetana Howdyja
{123696}{123744}* Stay away|kloni se
{123744}{123840}* From Captain Howdy|kapetana Howdyja
{123840}{123888}* Stay away|kloni se
{123888}{123960}* From Captain Howdy|kapetana Howdyja
{123960}{124020}* Stay away|kloni se
{124020}{124104}* From Captain Howdy|kapetana Howdyja
{124104}{124152}* Stay away|kloni se
{124152}{124224}* From Captain Howdy|kapetana Howdyja
{124224}{124284}* Stay away|kloni se
{124284}{124368}* From Captain Howdy|kapetana Howdyja
{124368}{124416}* Stay away|kloni se
{124416}{124488}* From Captain Howdy|kapetana Howdyja
{124488}{124548}* Stay away|kloni se
{124548}{124644}* From Captain Howdy [ smijeh ]|kapetana Howdyja
{124644}{124728}* Stay away from Captai Howdy|kloni se kapetana Howdyja
{124728}{124812}[ smijeh nastavlja ] Stay away|kloni se
{124812}{124908}* From Captain Howdy [ smijeh pojaèava ]|kapetana Howdyja
{124908}{124956}* Stay away|kloni se
{124956}{125016}* From Captain Howdy|kapetana Howdyja
{125028}{125088}* Stay away|kloni se
{125088}{125148}* From Captain Howdy|kapetana Howdyja
{125184}{125268}* Stay away from Captain Howdy|kloni se kapetana Howdyja
