{3164}{3224}Vežite pojaseve, molim.
{4956}{4977}O, ne!
{4982}{5026}Ni ovdje nije mnogo suše, tata.
{5031}{5068}Bože moj!
{5074}{5130}Krov je procurio. -Da.
{5135}{5188}Ali je kuæa bar velika. Velika je!
{5218}{5259}Sviðaju mi se ovi veliki prozori.
{5282}{5328}I pogled je baš lijep.
{5337}{5423}Da. Trebam samo|popraviti krov, dušo.
{5427}{5447}Da.
{6660}{6684}Pronašao sam ovo iza. Hoæeš?
{6688}{6718}Ne!
{6740}{6810}Smiri se. Što ti je? Smiri se!
{6816}{6849}Tata!
{6870}{6938}Što je? Što je bilo?
{6954}{6997}Gubi se odavde!
{7072}{7104}Što je bilo, dovraga?
{7109}{7131}Sarah, da li si dobro?
{7136}{7193}Da, dobro sam.|Samo me preplašio.
{7200}{7250}Pa pretpostavljam.
{7256}{7295}Sigurna si?
{7300}{7351}Da, dobro sam.
{7407}{7484}Tata?
{7640}{7729}Mogla bi prièekati. Samo|dok dobiješ školsku uniformu.
{7729}{7765}Ne moraš odmah iæi.
{7771}{7847}Pa ne mogu sjediti u kuæi|i gledati TV do kraja života.
{7840}{7889}Zašto ne? Ja to radim.
{7899}{7957}Želim krenuti i da završimo s tim.
{7963}{8027}Baš lijepo izgledaš. Sretno.
{8031}{8079}Doæi æu po tebe. -Iæi æu pješke.
{8084}{8122}Sigurna si?  -Da.
{9058}{9099}Pogledaj ove ribe!
{9112}{9180}Ja obožavam Sotonu!|On je moj Bog!
{9195}{9303}U redu je. Sve su na jednom|mjestu. Sve su na jednom mjestu.
{9474}{9565}U almanahu piše da æemo|danas dobiti rivala u neèemu.
{9570}{9627}Da, divno. Udavit æu se živa.
{9633}{9696}Nova sveukupnost|traži novu ravnotežu.
{9701}{9780}Zemlja, zrak, voda, vatra.|Možda je to onaj èetvrti.
{9787}{9814}Kome treba èetvrti?
{9819}{9882}Nancy, potreban nam je netko|kako bi obrazovali uglove
{9886}{9963}sjevera, juga, istoka i zapada.|-Ili da napravimo krug.
{9966}{10047}Možda bi ona mogla|biti ta èetvrta.
{10060}{10126}Ma daj! -Obožavam|žene u uniformi.
{10255}{10299}Dobar dan, razredu!
{11008}{11077}Mislite, da li sam nešto povalio?
{11207}{11268}Boku sam povalio!
{11563}{11629}Što je ona tamo rekla za mene?
{11725}{11831}Ovo nije u redu. Trebali|bi uèiti meksièki.
{11823}{11899}Kaže se španjolski. -Da, španjolski.
{13028}{13057}Ovdje je.
{13083}{13111}Tko?
{13118}{13196}Netko tko æe biti èetvrti. Ona je ta.
{13223}{13262}Da nisi bolesna?
{13372}{13408}To je ona.
{13458}{13524}Bok. Mogu li|sjesti s vama?
{13529}{13617}Moram napraviti jedan|eksperiment u laboratoriju.
{13700}{13735}Pa dobro.
{13754}{13808}Možeš sjesti ovdje.
{13875}{13924}Jesi li sad zadovoljna?
{13933}{13960}Što je?
{14155}{14183}Bok.
{14192}{14210}Bok.
{14216}{14319}Ti si Sarah, zar ne? -Da.|-Bok, ja sam Chris.
{14336}{14388}Želim se isprièati zbog|onih tipova na francuskom.
{14419}{14460}Pravi su kreteni. -Znaš kako|kažu, "Našla krpa zakrpu".
{14467}{14487}Tako je.
{14498}{14597}Èekaj! Upravo si me nazvala|kretenom? Jesi, zar ne?
{14601}{14693}Oprosti. Isplivali su moji|obrambeni mehanizmi.
{14674}{14747}Ovdje su ljudi zaista grubi prema|meni. -Stvarno? A tko to još?
{14752}{14834}One tri djevojke iza tebe.|Nemoj buljiti!
{14920}{15057}Tako je veæ bolje.
{15050}{15077}Sranje!
{15087}{15137}Pa to su vještice iz Eastwicka.
{15143}{15202}Što? -Što god radila,|drži se dalje od njih.
{15207}{15292}Zašto? -Vidiš onu s desne|strane? Ona je prava drolja.
{15298}{15367}Nije da to znam iz iskustva, ali...
{15373}{15480}Ona u sredini ima ožiljke|od opekotina svuda po tijelu.
{15487}{15570}Nisam vidio, ali znam tko jest.|U svakom sluèaju, one su...
{15589}{15644}Ma bolje da ti ne kažem. -Što?
{15650}{15689}Što su?
{15695}{15735}One su vještice.
{15751}{15779}Vještice?
{15787}{15861}Tako ljudi prièaju.
{15895}{15943}Što radiš poslije škole?
{15958}{16000}Ne znam. Valjda ništa.
{16018}{16038}Stvarno?  -Stvarno.
{16044}{16105}Ja sam zauzet. Treniram nogomet.
{16131}{16183}Mogla bi me doæi gledati.
{16190}{16267}Nogometni trening.|Zvuèi tako privlaèno.
{16974}{17006}Sarah!
{17013}{17048}Tražiš nekog?
{17064}{17088}Ne.
{17096}{17164}Neki od ovih kretena nogometaša|tjeraju djevojke da dolaze na
{17168}{17230}njihove treninge i gledaju ih.|Kao da je to zanimljivo.
{17234}{17307}Da. Kao ona djevojka tamo|što gleda Chrisa Hookera.
{17337}{17350}Ja ga èak i ne poznajem.
{17355}{17425}Nancy je žao zbog onoga|što se desilo na biologiji.
{17430}{17515}Ona je nepristojna prema svima,|pa nemoj to uzimati osobno.
{17521}{17548}Ti si Nancy?
{17554}{17632}Ona je Nancy, ja sam|Bonnie, a ovo je Rochelle.
{17637}{17685}Bok. Ja sam Sarah.|-Da, znamo tko si.
{17729}{17780}Hoæeš da odemo negdje na kavu?
{17786}{17866}Ne, ne mogu. Moram|iæi kuæi. Tata me èeka.
{17871}{17920}Mogla bi naæi izgovor.
{17941}{18009}Rochelle je kidnula sa svog treninga.
{18040}{18084}On spopada sve što ima sise.
{18089}{18117}Osim mene.
{18122}{18163}Ne gledam njega.
{18181}{18206}On širi bolest.
{18232}{18283}Znam to iz iskustva.
{18364}{18452}Tako je, Chris! Samo dodaj, dušo!
{18561}{18584}On je kreten.
{18677}{18710}Hajde.
{18765}{18852}Ideš s nama, je li tako?|-Kuda æemo?
{18858}{18886}Idemo u kupovinu.
{18914}{19011}Nemam novca.  -Dobit æemo|popust za pet prstiju na ruci.
{19016}{19088}Popust za pet prstiju?
{19105}{19185}Sarah, gdje si ranije živjela?|-U San Franciscu.
{19192}{19253}Zašto si se preselila?|-Ovde je grozno.
{19258}{19305}Tata je tako želio.
{19340}{19451}Motorizirana si?|-Ne treba mi ovdje auto.
{19456}{19502}Auto ti treba svuda.
{19521}{19569}Što ti je to?
{19551}{19605}Rezala sam vene.
{19641}{19697}Èime si to napravila?
{19704}{19746}Kuhinjskim nožem.
{19752}{19821}Nisi to uèinila kako treba.
{19829}{19855}Da...
{19882}{19943}Hajde, djevojko, idemo.
{20047}{20138}Kako treba? Otkud ti znaš|kako treba? -Umukni, Rochelle!
{20146}{20185}Pa otkud znaš?
{20914}{20943}Sarah!
{20955}{20989}Što?
{21026}{21078}Stavi ovo u torbu.
{21060}{21083}Neæu.
{21147}{21186}Sve u prirodi krade, znaš.|Velike životinje kradu
{21193}{21286}od onih manjih. -Ali one|kradu kako bi opstale.
{21319}{21350}Mi to ne moramo raditi.|-Ali ovo je drugaèije.
{21355}{21428}Unutra se nalaze èini i moæne|misli pa tako spreèavamo
{21434}{21550}druge da ovo proèitaju.|Nikada. Osim možda mi.
{21572}{21617}Vi se stvarno tim bavite?
{21652}{21687}Tako nekako.
{21986}{22026}To nije za tebe.
{22031}{22066}Oprostite.
{22112}{22160}Kakav divan prsten.
{22165}{22207}Pripadao je tvojoj majci?
{22222}{22250}Jest.
{22276}{22327}Platit æeš za to?
{22385}{22441}Nisi kao tvoje prijateljice.
{22572}{22627}Znaš li kako se koriste svijeæe?
{22645}{22676}Da. Zapali se fitilj.
{22693}{22798}I više od toga. Crvena|je za ljubav, a crna...
{22810}{22841}U stvari...
{22884}{22962}Proèitaj ovo. Tu je sve objašnjeno.
{22970}{23000}Koliko?
{23006}{23040}30 dolara.
{23071}{23155}Znate, nikada ranije ništa|o ovome nisam proèitala.
{23162}{23209}Ne upražnjavam takve stvari.
{23227}{23313}Možda si ti ipak prava|vještica. Moæ dolazi iznutra..
{23331}{23343}Hajde, Sarah.
{23542}{23590}Mislim da bi trebali|iæi kuæi.
{23595}{23676}Samo gledaj ravno|i nastavi hodati.
{23863}{23935}Molim vas, mojoj bebi treba|hrana. -Nemam ništa kod sebe.
{23941}{24010}Nemoj joj davati novac.|Kreni odmah. -Ništa nemam.
{24016}{24087}Poznajem te. Imam zmiju.
{24079}{24135}Èekaj malo, moram|razgovarati s tobom!
{24140}{24175}Sanjao sam te.
{24224}{24310}U mom snu si bila mrtva!
{24354}{24396}Tebi prièam!
{24400}{24465}Vrati se Isusu!
{24473}{24538}Nemoj bježati od mene!
{24566}{24641}Znam o èemu ti prièam!
{24648}{24721}Ja sam povezan s tobom!
{24802}{24890}Saslušaj me!
{25038}{25118}Hajde, Sarah, idemo odavde! Polazi!
{25168}{25205}Brzo!
{25238}{25270}Bože moj!
{25319}{25384}Što je bilo? -Jesi li|vidjela što se desilo?
{25388}{25471}Nisam. -Udarila su ga! Auto|ga je udario, a mi smo to uèinile.
{25471}{25545}Možda jesmo, a možda i nismo.|-Ma definitivno jesmo.
{25545}{25613}Osjetila sam da æe ga|auto udariti.  -I ja.
{25613}{25691}I ja sam. -Sarah, jesi li|i ti osjetila?  -Jesam.
{25691}{25769}Onda je, ljudi, Sarah èetvrta|za sjever, jug, istok i zapad.
{25769}{25872}Možemo uèiniti da se svašta|dešava. Ovo je stvarnost!
{25885}{25909}Sranje. -Narode, ovo je jezivo.
{25933}{26025}Pa jurio te.|Želio te povrijediti.
{26043}{26077}Nisam ja kriva, mislim...
{26077}{26130}Cure, možda æe|nas sad saslušati.
{26130}{26157}Tko?
{26161}{26195}Mano.
{26201}{26279}Tko je to? Nešto kao Bog?
{26279}{26355}Ne. Èovjek je izmislio Boga.|Ovo je starije od toga.
{26358}{26422}Da li se vi klanjate vragu?
{26426}{26484}To je i kao Bog i kao vrag.
{26489}{26576}On je sve. Drveæe, zemlja,
{26606}{26634}kamenje, mjesec! Sve!
{26657}{26709}Priroda?
{26689}{26762}Kad bi Bog i vrag igrali nogomet,
{26778}{26886}Mano bi bio stadion na kome|igraju, sunce koje ih obasjava.
{26933}{27012}Da li ti se èesto dešavaju|ovakve stvari kao veèeras?
{27012}{27094}Ne. Ne na taj naèin. Druge|stvari mi se dešavaju.
{27094}{27154}Gdje si to nauèila? -Ne znam.
{27156}{27208}Ti si prirodna vještica.
{27259}{27303}Mrzim to. Uvijek se sve upropasti.
{27347}{27468}Katkad poželim da padne kiša,|da pukne cijev u sobi i sve poplavi.
{27475}{27503}Ma nemoj!
{27510}{27636}Zaista! Želim da sve bude|tiho i silno, silno to želim
{27641}{27719}i onda tri dana budem|potpuno gluha.
{27726}{27828}Ako možeš to, da li si ikada|èula za prizivanje duhova.
{27834}{27854}Nisam.
{27887}{27944}To je kad ih dozoveš.
{27972}{27999}Mano!
{28095}{28157}To je kao kad ga uneseš u sebe.
{28165}{28213}Kao kad te on ispuni.
{28274}{28439}On odnosi sve što je loše u|životu i ponovo sve ispravi.
{28461}{28547}Ništa ne može sve da ispravi.
{28586}{28629}Možda za tebe.
{28703}{28783}Kuda si krenula? -Poèele|ste me plašiti.
{28803}{28838}Uplašila se!
{28857}{28903}Nancy, potrebna nam je.
{28909}{28939}Znam to.
{28957}{28992}Vratit æe se ona.
{29069}{29140}Stvarno sam se èudno osjeæao|kad sam te sinoæ pozvao.
{29140}{29215}Nisam mislio da æeš doæi.|-Htjela sam te iznenaditi.
{29215}{29291}Iznenaditi? -Da.  -Mislio sam|da æeš se motati s onim
{29291}{29373}djevojkama. -Kojim djevojkama?|-Onima sa uvrnutim glavama.
{29373}{29457}Uvrnutim glavama? Što je to|uvrnuto na njihovim glavama?
{29457}{29526}Ona jedna djevojka ima|veliku glavu. -Stvarno?
{29526}{29611}Da. Izgleda kao Sveti Bernard.|-Ne znam za to.
{29611}{29730}Mrzim te sa velikim glavama.|Naravno, i to je bolje nego
{29730}{29790}imati malu glavu, za koju|ti jednostavno doðe da je objesiš
{29790}{29833}na retrovizor u autu.
{29833}{29880}Zašto si tako opsjednut glavama?
{29880}{29971}Samo sam primijetio|kako je tvoja super.
{29971}{30028}Sviða ti se moja glava? -Da.|Dobra je to glava. -Dobra?
{30032}{30130}Dobra je. Dobra je za|ljubljenje. Mogu li?
{30136}{30183}Vidimo se kasnije, brate.
{30197}{30260}Bilo mi je drago što smo|se upoznale, Sarah. -Bok.
{30266}{30296}Vidimo se.
{30353}{30423}Ajmo kod mene|doma. Nema nikoga.
{30423}{30462}Neæu iæi.
{30483}{30541}Ne mogu. Moram kuæi.
{30556}{30586}Pa dobro.
{30650}{30682}Ljutiš se?
{30717}{30761}Ne.
{30789}{30823}Oprosti.
{30841}{30877}U redu je.
{31006}{31058}Pa, uspaljenice, kako je bilo?
{31089}{31149}Što to? -Na tvom|sastanku sa Chrisom.
{31153}{31253}O èemu to prièate? -Chris|je veæ svima isprièao.
{31258}{31365}Što to? -Da ste radili one stvari.
{31366}{31396}Ali nismo.
{31444}{31494}Onda se možda samo hvali.
{31548}{31618}Jer veæ je cijeloj školi isprièao
{31636}{31694}da se najgore jebeš od svih
{31706}{31846}djevojaka koje je imao.|Veæ se svuda širi prièa.
{31956}{32009}Ne, nije to napravio. -Jest.
{32024}{32090}Isto je prièao i za Nancy.
{32104}{32146}Rekla sam ti da je kreten.
{32341}{32420}Bok. Možemo li na|trenutak poprièati?
{32434}{32528}Chris! -Žao mi je, zauzet je.|Možda bismo ti mogli...
{32528}{32583}ugovoriti kasnije ovog tjedna.
{32636}{32699}Zašto si lagao za mene?
{32711}{32813}Slušaj, ne želim ponovo|izaæi s tobom. U redu?
{32837}{32927}Molim te, prestani me|moliti. To je baš bijedno.
{32973}{33008}Hej, Chris!
{33056}{33129}Jebi se!
{33126}{33163}Ma, ne.
{33179}{33226}Ali ja hoæu.
{33233}{33307}Zaplakat æe! I ja æu se rasplakati.
{33313}{33355}Rasplakat æu se!
{33623}{33680}Pogledaj, baš je slatka!
{33685}{33746}Pravi morski pas!
{34344}{34396}Sjajno! Izuzetno!
{34554}{34633}Bože, imam stidnu|dlaèicu u èetki.
{34659}{34795}Ne, èekaj! Èekaj. Ovo je jedna|od Rochellinih kovrèavih dlaka.
{35001}{35058}Zašto mi to radiš, Laura?
{35063}{35114}Misliš da si duhovita?
{35134}{35185}Stvarno hoæeš znati zašto?
{35193}{35258}Da. Stvarno hoæu znati.
{35286}{35358}Zato što ne volim crnèuge.
{35377}{35406}Oprosti.
{35654}{35737}Veæ sam vam ovo rekla, ali|želim bolje pojasniti.
{35750}{35787}Ovo je samo eksperiment.
{35793}{35860}Ništa vam ne možemo|garantirati u pogledu
{35865}{35926}rezultata ili nuspojava.|Neslužbeno vam mogu
{35932}{35993}reæi da koliko znamo,|postoji vrlo mali rizik.
{36000}{36066}Ova genska terapija nije opasna.
{36073}{36154}Može biti ponešto|bolna, ali nije opasna.
{36457}{36533}Dobro. Probaj se opustiti.
{36651}{36788}Sada ubrizgavam intravenozni.|Osjetit æeš mali ubod kada igla
{36794}{36933}probije kožu, a onda još uboda|kada se igla bude pokretala.
{36944}{37024}Pokušat æu da traje|što je moguæe kraæe.
{37058}{37118}Miruj i nastavi disati.
{37297}{37351}U redu?
{37446}{37501}Dobro je... Opusti tijelo.
{37509}{37538}Ne...
{37546}{37605}Samo još malo, Bonnie.
{37721}{37762}Ne mrdaj.
{39183}{39229}Nestalo je struje! Èovjeèe!
{39247}{39321}Nisi ni raèun platio! Dala|sam ti novac da platiš
{39329}{39404}raèun, a što ti radiš kod kuæe|tako kasno? Kasniš!
{39414}{39515}To je zbog oluje, Grace!|Kratak spoj, Grace! -Oluje?
{39521}{39589}Zato je nestalo struje, Grace.
{39706}{39780}Ma nije zato nestala|struja.  -Doæi æe.
{39785}{39897}Opet hoæeš da ti dam novac!|Dala sam ti da platiš raèun!
{39905}{40001}Ne možeš ni raèun platiti!|Ma èemu onda služiš?
{40009}{40067}Znaš ti èemu ja služim.
{40296}{40353}Hej, Sarah! Idemo|danas na izlet.
{40357}{40439}Gðice Downs, mrzim što|prekidam vaš društveni skup...
{40463}{40511}Baš si pametna, sestro!
{41370}{41435}Èuvajte se perverznjaka.
{41440}{41509}Mi smo perverznjaci, gospodine.
{42081}{42155}Zemlja, zrak, vatra, voda...
{42258}{42324}Bolje je nabosti se na ovu|oštricu nego uæi u krug
{42331}{42412}sa strahom u srcu.|Kako æeš uæi?
{42428}{42522}Sa savršenom ljubavlju|i povjerenjem.
{42652}{42775}Bolje se nabodi na oštricu nego|da uðeš sa strahom u srcu.
{42781}{42902}Kako æeš uæi? -Sa savršenom|ljubavlju i povjerenjem.
{43077}{43152}Bolje je nabosti se na ovu|oštricu nego uæi u krug sa
{43157}{43262}strahom u srcu. Kako æeš uæi?
{43303}{43393}Sa savršenom ljubavlju i|povjerenjem.
{43399}{43458}Tako treba, djevojko.
{43524}{43554}Kako gore...
{43597}{43635}tako i dolje.
{44170}{44259}Pijem sa svojim sestrama|i tražim za moguænost da
{44265}{44377}uzvratim onima koji me tlaèe.|Naroèito onom rasistièkom
{44382}{44492}poblajhanom govnu, Lauri Lizzie!
{44481}{44514}Samo tako.
{44625}{44719}Pijem sa svojim sestrama|i tražim da više volim sebe
{44723}{44850}i dopustim sebi da me|drugi malo više vole.
{44863}{44908}Naroèito Chrisu.
{44973}{44995}To je baš bijedno.
{45003}{45041}Definitivno bijedno.
{45135}{45227}Pijem sa svojim sestrama|i uvlaèim u sebe moæ
{45234}{45329}da budem lijepa.|Izvana kao i iznutra.
{45590}{45667}Pijem sa svojim sestrama|i uvlaèim u sebe,
{45799}{45845}svu moæ novca.
{45878}{45915}To je sve?
{46089}{46127}U zdravlje.
{46151}{46199}U zdravlje! -U zdravlje!
{46223}{46314}Kako æete to izvesti?
{46332}{46338}Bože moj!
{46343}{46365}Što?
{46404}{46442}Pogledajte!
{46529}{46586}To je Mano!
{46570}{46612}Divno je.
{46651}{46703}On nas sluša!
{47430}{47462}Misliš da funkcionira?
{47467}{47531}Ne znam. Stalno gleda.|Stalno se okreæe.
{47536}{47629}Nikom to nije jasno. -Baš èudno.
{47655}{47726}Znam. Evo ga, gleda te opet.
{47757}{47787}Još uvijek je iza?
{47813}{47837}Da.
{47877}{47920}Sarah!  -Da?
{47952}{47987}Nije bitno.
{48028}{48029}Djeluje.
{48049}{48094}Ili djeluje ili je poludio.
{48117}{48163}Mrziš me, je li tako? -Ne.
{48168}{48214}Ne mrziš?  -Ne.
{48219}{48326}Kad si momak, a ja to jesam,|ljudi oèekuju razne stvari...
{48332}{48412}Znam da sam isprièao|neke ružne stvari za tebe...
{48418}{48477}Jesi li rekao svojim|prijateljima? -Što?
{48495}{48583}Da si jedno lažljivo govno.|-Nisam. Ali hoæu.
{48612}{48672}Reæi æu im to sutra.|Reæi æu istinu. -Dobro.
{48678}{48752}Mogu li sjediti pored|tebe na misi?  -Naravno.
{49089}{49120}Gledaj ovo...
{49125}{49200}Chris, ponesi mi ovo.|Stvarno su teške. -Da.
{49207}{49285}I Bonnine. Ima slabu kièmu.
{49298}{49325}Hvala.
{49460}{49603}Chris, da li bi mi pridržao|kurèinu? Stvarno je težak.
{49698}{49746}Jesi li bolestan, deèko?
{49802}{49831}Sjedni.
{50065}{50156}Obrati pažnju...
{50218}{50265}Djeluje.
{50270}{50348}Njena èarolija djeluje.
{50355}{50443}Hoæeš li pogledati, zaboga!
{50478}{50604}Ono je bilo super! -Jedva|èekam da i moja upali.
{50630}{50725}Teško je to, znate. -Pa bili ste|na pola metra jedno od drugog.
{50735}{50789}Bježi! -Pa nisam toliko teška!
{50795}{50881}Kako da ne. Laka si k'o perce.|I možeš putovati svemirom.
{50911}{50926}U stvari, voljela bih to.
{50931}{50998}Da li ste ikada igrale onu|igru "laka k'o perce,
{51004}{51048}èvrsta k'o daska"? -Nismo.
{51052}{51217}Jedna djevojka legne, ostale se|okupe oko nje i zavuku prste ispod.
{51256}{51284}Koje prste?
{51290}{51308}U redu.
{51313}{51429}Uzmete kažiprst i srednji prst|i stavite ispod nje. Ovako.
{51474}{51543}Morate zamisliti da|je nevjerojatno laka,
{51551}{51591}kao da je od zraka.
{51597}{51660}Cijelo njeno tijelo ili samo ruka?
{51665}{51760}Cure, dajte se koncentrirajte.
{51888}{51943}Mislim da sam uganula prst.
{51976}{52013}Umukni! -Koncentrirajte se!
{52032}{52080}Hajde, cure. Da li ste spremne?
{52090}{52165}Laka k'o perce, èvrsta k'o daska.
{52910}{52958}Uspjele smo.
{53396}{53472}Ljudi, ovo ne uspijeva.
{53535}{53591}Ušuti, ili æeš pasti!
{53653}{53709}A kako da se spustim?
{53807}{53847}Tko zna uputstva?
{53852}{53920}Samo se nastavite|koncentrirati.
{53949}{53986}Nevjerojatno!
{54107}{54190}Bok, cure! Donijela|sam vam svima ruènike!
{54199}{54234}Jao, moje dupe!
{54242}{54290}Što se ovdje dogaða? -Ma ništa.
{54296}{54350}Da se vi djevojke ne|drogirate? -Ne, mama.
{54448}{54488}Da li si dobro?
{54516}{54558}Morate ovo probati.
{56027}{56039}Išèupala si mi dlaku!
{56045}{56101}Oprosti. Uèinilo mi se da|sam vidjela neku bubu.
{56130}{56147}Možda bi trebala|oprati kosu, znaš.
{56151}{56178}Glupa kuèko!
{56400}{56476}Ima dosta ispucane|vrhove. -Stvarno?
{56480}{56538}Pretpostavljam da je to dokaz|da nije prirodna plavuša.
{56543}{56578}Zblajhana!
{56597}{56662}Što mislite da æe se|desiti Lauri? -Ne znam.
{56668}{56740}Ako te ostavi na miru,|neæe joj se ništa desiti.
{56755}{56830}Ali i ništa dobro.|-Slabe su šanse za to.
{56902}{56969}Tko je to? -Moja prava majka.
{56992}{57023}Gdje je ona?
{57036}{57126}Umrla je dok me raðala.
{57122}{57195}Žao mi je.  -U redu je.
{57213}{57297}Uzmi moje ožiljke.
{57351}{57436}Uèini da budem lijepa|izvana, kao iznutra.
{57481}{57544}Uzmi moje ožiljke.
{57568}{57618}Uzmi mi ožiljke...
{58378}{58409}Evo.
{58415}{58458}Evo i nje na dasci!
{58465}{58500}Prekini s tim, Laura!
{58843}{58872}Bože moj!
{58882}{58931}Što je?
{58938}{58969}Što se desilo?
{58977}{59048}Kako izgleda?
{59173}{59249}Jesi li stavljala nešto na kosu?
{59446}{59506}Zapamtite da moramo proæi|nekoliko tretmana prije nego
{59513}{59578}što se rezultati budu vidjeli.
{59652}{59685}Da li je bolje?
{59691}{59757}Ne bih ti mogla reæi, dušo.
{59982}{60026}Samo trenutak...
{60060}{60116}Kako izgleda?
{60196}{60234}Ne znam.
{60379}{60394}Èekajte...
{60550}{60592}Ne mogu vjerovati!
{60991}{61030}Uspjelo je.
{61038}{61066}Što?
{61089}{61137}Uspjelo je.
{61137}{61160}Bože!
{61403}{61463}Stvarno, ako to napraviš|možeš oslijepiti.
{61467}{61520}Siguran si?
{61589}{61659}Trebala se danas vratiti.|Jesi li razgovarala s njom?
{61677}{61692}Nisam.
{61793}{61889}Ovaj sat poèinje toèno|u petnaest do devet.
{61894}{61932}Žao mi je, pediker je zakasnio.
{61939}{61987}Vidi ti nju!
{62004}{62066}Sranja mu! Bonnie!
{62084}{62124}Kako ide?
{62151}{62224}Da, kako ide, Bonnie? -Bože moj!
{62231}{62330}Tako divno izgledaš.|Ne mogu vjerovati.
{62323}{62434}Uspjela si. -Ma nisam ja. -Sve|smo uspjele. Potpuno smo uspjele.
{62442}{62548}Natjerale smo Chrisa da te voli.|A i Laura je ostala bez kose.
{62554}{62673}Samo da je vidite.|Sad svaki dan nosi šešir.
{62687}{62724}Jadna Laura!
{62750}{62877}Što je s Nancy? -Njena èarolija|ne djeluje. -Kakva èarolija?
{62884}{62981}Ne znam. Mislim da više|ne želi biti bijelo smeæe.
{62987}{63099}Rekla sam joj da prièeka|malo i sredit æe se to.
{63574}{63603}Dobro!
{63695}{63739}U redu, hajde, hajde...
{63783}{63853}Kroz ovo se skoro|sve može vidjeti.
{63860}{63908}Ostavi me na miru! Isuse!
{63941}{64007}Otac tako nešto ne|radi svojoj kæerci.
{64011}{64062}Ja joj nisam otac. -Hvala Bogu!
{64067}{64160}Njen otac je onaj što ti je|platio 50 dolara da te kara
{64166}{64224}na zadnjem sjedištu auta! -Svinjo!
{64236}{64328}Ne! -Da me više|nikada nisi udarila!
{64454}{64497}Ne!
{64535}{64558}Mama...
{64565}{64571}Što je to bilo, dovraga? Bože moj!
{64800}{64826}U redu si?
{64909}{65020}Krv mu istjeèe. Moramo|ga stabilizirati.
{65085}{65143}Što se dogaða?
{65151}{65216}Što mu se to dogaða?
{65251}{65343}Znam da vam je teško, ali|standardna je procedura
{65349}{65420}da vam postavim nekoliko|pitanja prije nego što vam
{65413}{65532}isplatimo naknadu po polici.|-Ne razumijem. Kakva polica?
{65538}{65641}G. Sanders je uplaæivao|doživotnu mirovinu preko
{65646}{65713}kompanije i kod ovolike|isplate uobièajeno je da...
{65743}{65763}Kolike isplate?
{65796}{65826}Samo trenutak...
{65892}{65920}Izvinite...
{66018}{66134}175.000 dolara.
{66146}{66177}Sto...
{66210}{66288}Èekajte, kažete da|æemo to mi dobiti?
{66294}{66315}Vi.
{66377}{66490}175... -Divnog li èovjeka!
{66766}{66824}175.000 dolara!
{66900}{66965}175.000!
{67034}{67084}Ne mogu vjerovati da je mrtav.
{67102}{67152}Mislite da smo ga|mi ubile? -Ne znam.
{67195}{67222}Bok.
{67236}{67316}Nemoj se stidjeti, dušo!|Imaš lijepu guzu!  -Bonnie!
{67327}{67396}Pa što. Baš ima slatku|stražnjicu. -Prava si drolja.
{67425}{67464}Mislite li da joj je ovdje|otmjeno. -Pa i same znate.
{67494}{67520}Mislite li da æe nas|pozvati na veèeru?
{67617}{67691}Bok! -Bok, curke!
{67720}{67764}Tako divno izgledate.
{67771}{67864}Drago mi je što ste došle|da nam vidite stan.
{67870}{67958}Dobro došle u naš stan! Super je.
{67986}{68045}I pogledajte ovaj pogled.
{68072}{68108}A još i kauè.
{68114}{68195}Obožavam ovaj kauè i pogled.
{68206}{68290}Èim sam ga vidjela, odluèila|sam i rekla prodavaèu:
{68296}{68343}"Samo ga ti zapakiraj, dušo!"
{68356}{68421}A još ovo!
{68427}{68457}Moj džuboks!
{68673}{68743}Ovdje svaku pjesmu|pjeva Connie Francis.
{68749}{68825}Zar to nije super? Još|kao mala sam maštala
{68830}{68928}da imam džuboks samo|sa ploèama Connie Francis.
{68972}{69007}To je baš super.
{69011}{69059}A tko je Connie Francis?
{69064}{69159}O, umukni, djevojko! Znaš,|Connie Francis ti je... -Hajdemo!
{69164}{69240}Baš mi je drago što sam vas|ponovo vidjela. -Connie Francis...
{69256}{69292}Èekajte malo!
{69370}{69393}Hajde.
{69398}{69465}Hajdemo napraviti mali|tulum povodom useljenja.
{69471}{69496}Žao mi je, mama!
{69678}{69777}Èitala sam ovo i pomislila|da bi i vas moglo zanimati.
{69782}{69884}Zahtjev. Probajte sa zahtjevom.|Ta iluzija je tako stvarna
{69886}{69977}da æe svakoga zavarati. To|je najstariji oblik magije.
{69991}{70058}Da se kladimo da mogu|to izvesti? -Misliš?
{70087}{70127}Ovo je da se osjeti...
{70167}{70211}A ovo je da budem...
{70238}{70336}Oblikuj i formiraj|kako bi se vidjelo.
{70381}{70440}Neka moæ bude trodupla.
{70474}{70566}Kad budem ovakva,|neka tako i bude!
{70640}{70662}Što?
{70680}{70747}Oèi su mi smeðe.  -Pa?
{70775}{70811}Obièno su zelene.
{70852}{70920}To si mogla izvesti i|pomoæu kontaktnih leæa.
{70925}{70974}Da. Ali lijepo ti stoji.
{70980}{71029}Suptilno je. Ali dobro.
{71064}{71100}Hoæete nešto veæe?|-Veæe!  -Veæe!
{71147}{71198}Koncentrirajte se. Hajde.
{71356}{71377}Spremne?
{71671}{71701}Impresionirane?
{71714}{71805}Svakako sam impresionirana!|-Izgledaš kao Claudia!
{71797}{71835}Hoæeš pipnuti?
{71855}{71888}Prava je!
{71888}{71962}I mnogo jednostavnije od|odlaska u frizerski salon.
{71962}{71995}Zaista, u salon?
{71995}{72072}Nevjerojatno je.|-Èekaj! Gledaj sad!
{72196}{72251}Napravi od mene|plavušu. -Ne, mene!
{72257}{72334}Napravi me plavušom. -Neæe moæi.
{72315}{72345}Ma daj!
{72351}{72415}Napravi meni nešto!|Meni! -A što hoæeš?
{72417}{72467}Manju guzicu.
{72575}{72578}Sarah!
{72707}{72740}Sarah!
{72931}{72972}O, ne! Ne!
{72998}{73053}Zašto se nisi javila na telefon?
{73062}{73106}Tri je ujutro, Chris.
{73129}{73173}Da. To je dobar razlog.
{73179}{73268}Znaš što sam razmišljao? Možda|bismo mogli živjeti zajedno.
{73273}{73361}Mislim da trenutno nisam|spremna za takvo vezivanje.
{73381}{73401}Sranje.
{73413}{73491}Samo, ne mogu prestati|da razmišljam o tebi.
{73497}{73564}Ne znam zašto, ali|mislim da te volim.
{73569}{73666}Nikada ranije nisam|nikoga volio osim, možda,
{73672}{73748}moje mame i šteneta|koje sam dobio kao mali.
{73754}{73808}Mislim da bi trebao|otiæi kuæi, Chris.
{73812}{73912}Ne, Sarah! Prièekaj! Molim te!|Sarah, molim te!
{73894}{73967}Slušaj, ne znam što se|to dogaða sa mnom!
{73972}{74014}Ne mogu ni|jesti ni spavati!
{74019}{74071}Mogu li vam pomoæi?
{74078}{74140}Meni nitko ne može pomoæi.
{74305}{74374}Ponovno ste ovdje. Što danas|mogu uèiniti za vas?
{74382}{74432}Trebaju nam neke nabavke.
{74440}{74508}Moram razbiti neke èini.
{74512}{74627}Kad otvoriš branu i bujica|krene, kako to zaustaviti?
{74633}{74728}Kad na nešto baciš èini, to|poslije ne možeš povrtiti.
{74744}{74795}One moraju iæi svojim tokom.
{74800}{74864}Ma trebaš ga pustiti da pati!
{74871}{74947}Nije na tebi da|procjenjuješ patnju.
{74964}{75046}Kada æu saznati što se|krije iza one zavjese?
{75027}{75106}Da. Što radite tamo? Nalazite|svu izgubljenu djecu iz kraja?
{75112}{75145}Bavite se crnom magijom?
{75150}{75211}Magija nije ni crna ni bijela,|veæ i jedno i drugo.
{75216}{75289}Zar se priroda ne sastoji|od jednog i drugog?
{75293}{75355}Ona je istovremeno|nježna i okrutna.
{75362}{75439}Dobro je u srcu Boga,|zlo u srcu vještice,
{75444}{75495}a život to drži u|ravnoteži. Razumijete?
{75513}{75532}Ne baš.
{75561}{75580}Onda razumijete ovo.
{75586}{75661}Što god uèinite,|trostruko æe se vratiti.
{75666}{75765}Èekajte. To nismo proèitale|ni u jednoj knjizi. -Niste?
{75773}{75873}To je dio osnovne spiritualne|istine. To se oèitava na mnogo
{75904}{75960}naèina u mnogo stvari.|"Radite drugima samo ono
{75966}{76018}što biste željeli da i vama rade."
{76216}{76263}PRIZIVANJE DUHA
{76275}{76327}Hoæu kupiti ovu knjigu.
{76338}{76439}Hoæete prizvati duha?|Za to morate biti vrlo iskusne.
{76444}{76470}To je jako opasno.
{76474}{76528}Odrasla sam ja djevojèica. U redu?
{76533}{76591}Sada mi molim vas|prodajte knjigu. Koliko?
{76610}{76643}35 dolara.
{76650}{76693}Pa, izvolite.
{78205}{78294}Kad mi je sve krenulo naopako,|baš prije nego što sam se pokušala
{78296}{78377}ubiti, imala sam|obièaj da zamišljam stvari.
{78396}{78513}Zatvorila bih oèi i vidjela bih|samo zmije i bube posvuda.
{78578}{78685}A onda bih ih otvorila i|one bi još uvijek bile tamo.
{78666}{78722}Nikuda ne bi otišle.|Bile su posvuda.
{78775}{78911}Znaš, zmija je vrlo moæno biæe.|Trebala bi je poštivati.
{78946}{79028}Zar nisi ti moæna? Da, jesi...
{79088}{79160}U redu. Poènimo.
{79230}{79296}Oformimo uglove. Hoæemo li?
{79491}{79612}Pozdravljam èuvare kule|stražare na istoku!
{79605}{79710}Moæi zraka i pronalazaka.|Saslušajte me!
{79716}{79768}Nas! Saslušajte nas!
{79788}{79864}Pozdravljam èuvare kule|stražare na jugu!
{79869}{79938}Moæi vatre i osjeæaja!|Saslušajte nas!
{79946}{80022}Pozdravljam èuvara kule|stražare na zapadu!
{80027}{80096}Moæi vode i intuicije,|saslušajte nas!
{80113}{80196}Pozdravljam èuvare kule|stražare na sjeveru!
{80175}{80253}Moæi majke Zemlje,|saslušajte nas!
{80351}{80441}Neka naša magija uspije|u ovu svibanjsku veèer!
{80501}{80612}Zmije ove zemlje,|koje živite duboko!
{80628}{80681}Èuvaru dubokog mora,
{80722}{80775}pokaži nam svoju slavu!
{80804}{80868}Pokaži nam svoju moæ!
{80885}{80964}Molimo ti se! Molimo ti se!
{81000}{81056}Prizivamo te!
{81168}{81245}O, Sveti, saslušaj naš poziv!
{81251}{81299}Saslušaj naš poziv!
{81305}{81393}Ti mudri, pokaži svoj put!
{81404}{81470}Mi smo te uznemirile!
{81500}{81588}Pokaži svoju moæ i slavu!
{81605}{81695}Mi te prizivamo! Prizivamo te!
{81710}{81756}Prizivamo te!
{81764}{81834}Ispuni me!
{82274}{82315}Je li ovdje?
{83395}{83443}Osjeæate li ovo?
{83475}{83521}Blagoslovio me je.
{83571}{83659}Osjeæam ga kako mi|protjeèe kroz žile.
{83676}{83723}Još uvijek je u meni.
{83766}{83796}Pliva...
{84617}{84653}Pogledajte ovo!
{84729}{84767}Tako je divno.
{84832}{84880}Ovo je poklon!
{84953}{85013}Ovo su moji pokloni!
{85029}{85091}Osjeæam te u sebi!
{85269}{85325}Ti si tamo, znam.
{85340}{85409}On je svuda! On je u svemu!
{85449}{85531}Slušajte, samo kažem da|mislim da je veæ dosta.
{85538}{85622}Ne znam što se ovo dogaða?|Užasno ponižavam Chrisa,
{85654}{85709}a htjela sam samo|da mu se dopadnem.
{85724}{85846}Bonnie, što se to dogaða s tobom?|Nekada si bila tako fina,
{85854}{85929}a sada si potpuno|ispala iz sistema.
{85911}{86002}Oprosti, ali veæi dio svog života|sam provela kao monstrum,
{86024}{86098}a sada kada u tome uživam|žao mi je što ti to smeta.
{86105}{86167}Ljudi, recite mi koje|je boje ono svjetlo?
{86175}{86197}Crveno.
{86203}{86257}Zar crveno ne znaèi|da trebam stati?
{86263}{86332}Da, znaèi da trebaš stati.
{86390}{86448}To je kao ono o èemu|je Lirio govorila.
{86478}{86501}Izbacile smo stvari iz ravnoteže.
{86506}{86574}Znam da trenutno mislite da|smo dobile ono što smo željele,
{86581}{86650}ali to æe nam se obiti|trostruko o glavu.
{86670}{86740}Da li mi ovdje vodimo|teološki razgovor?
{86757}{86835}Pa zabavno je i jezivo.|Koga još boli dupe!
{86842}{86893}Nancy, nas!
{86924}{86942}Što vi mislite?
{86947}{86993}One ne razmišljaju.
{87000}{87024}Kuèko!
{87043}{87130}I prestani ih pokušavati|pridobiti, neæe ti upaliti.
{87137}{87206}Ne pokušavam ih|pridobiti. Paranoièna si.
{87211}{87238}Paranoièna? -Da.
{87245}{87288}Nisam paranoièna!
{87283}{87306}Paranoièna si.
{87313}{87350}Umuknite!
{87398}{87484}Hoæeš biti s nama ili|želiš napustiti naš krug?
{87490}{87511}Odmah mi to reci!
{87519}{87582}Zašto sa tobom uvijek mora|biti ovako, Nancy?
{87611}{87613}Jer tako stoje stvari!
{87618}{87681}Mislim da trebaš razmisliti.|I neæu vas napustiti.
{87763}{87823}Jednog dana i neæe|biti tako super, Nancy.
{87830}{87955}Da se nisi uplašila,|Sarah? Bojiš se?
{88215}{88246}Tako je!
{88252}{88295}Ovo je bilo zamalo.
{88930}{88978}Vidiš, opada!
{88987}{89032}Ne razumijem!
{89064}{89125}Èime sam ovo zaslužila?
{89179}{89207}Laura!
{89257}{89311}Što je bilo? Što se desilo?
{89317}{89354}Ne znam.
{89430}{89482}U redu je. Smiri se.
{89482}{89551}Donijet æu ti odjeæu,|u redu? Ostani ovdje.
{89727}{89814}SARAH, DAJ MOLIM TE! INAÈE|IZGLEDAŠ KAO NETKO KOME
{89842}{89846}JE POTREBNO DA POPRIÈA S NEKIM.
{89863}{89915}Otkud znaš kako izgledam|kad prièamo preko telefona?
{89932}{90005}SLUŠAJ, VAŽNO JE. MORAM|BITI NASAMO S TOBOM.
{90009}{90113}MORAM TE VIDJETI. NE ZNAM|ZAŠTO, ALI... ZAŠTO SI TAKVA?
{90118}{90218}PA, SAMO JEDNA VEÈERA, DAJ!|-Ne znam... -MOLIM TE!
{90261}{90339}U redu. Sutra naveèer. -DA! DA!
{90386}{90443}Vidimo se tada. -BOK.
{90547}{90638}KADA SAM SE POÈELA|DRUŽITI S NJIMA LAKNULO MI JE.
{90643}{90728}NEMAM BLISKIH PRIJATELJA|JOŠ OD SAN FRANCISCA.
{90733}{90809}BILO JE JAKO LIJEPO|PRIPADATI NEGDJE.
{90815}{90897}Jednom se nisam složila s|njima i okrenule su mi leða.
{90901}{90933}To nije prijateljstvo.
{90938}{90976}Potpuno te razumijem.
{91014}{91037}Stvarno?
{91042}{91114}Znaš, ponekad se osjeæam|kao da smo ista osoba.
{91119}{91221}Razumiješ me?|-Nisam baš sigurna.
{91244}{91312}Ni ja nisam siguran.|Baš èudno, nešto sam
{91318}{91379}razmišljao kako nemam|pojma o èemu to prièam.
{91449}{91558}Zar ne bi trebali otiæi|u restoran ili tako nešto?
{91539}{91617}Ne.
{91625}{91730}U redu. Slušaj, Chris, znam|da misliš da gajiš snažne
{91748}{91864}osjeæaje prema meni. Ali da li|si se ikada zapitao otkud to?
{91893}{91995}Nisam. Ne mogu|razmišljati, samo osjeæam.
{92001}{92080}Èudno je kako se to desilo.|Jednog dana sam se probudio
{92086}{92162}i jedva sam èekao da te|vidim. Tako je svaki dan.
{92167}{92229}Ali sada kad te imam,|neæu te pustiti.
{92235}{92309}Stani i razmisli što govoriš,|Chris. Ti me èak i ne poznaješ.
{92363}{92414}Hajde, izmasirat æu ti leða.
{92422}{92457}Neæu da mi masiraš leða. -Ne, ne!
{92463}{92554}Chris, neæu da to radiš. -Smiri|se na trenutak i okreni se.
{92536}{92593}Mislim da bi me trebao|odvesti kuæi.
{92623}{92662}Ne. Sarah, okreni se. Hajde!|-Molim te, odvezi me kuæi.
{92662}{92743}Samo me zagrli, u redu? Prvo|me zagrli. -Onda æu pješke!
{92835}{92878}Sarah! -Ne!
{92882}{92925}Sarah, vraæaj se! Vraæaj se ovamo!
{92957}{92986}Dovraga!
{92999}{93067}Ne! Pusti me! Hajde, puštaj me!
{93071}{93095}Miruj!
{93109}{93193}Chris, nemoj, molim te! Pusti me!
{93510}{93571}Sarah!
{94086}{94117}Bože moj!
{94126}{94155}Sarah, uði.
{94183}{94251}Što se desilo? Da li si dobro?
{94320}{94462}Trebala si mu vidjeti pogled.|Bio je tako èudan. Tako prazan.
{94469}{94532}Kao da to nije bio on.
{94585}{94651}Gdje bi sad mogao biti?
{94664}{94701}Radi se tulum...
{94715}{94772}Kod Treya.
{94774}{94842}Ne, Nancy. Pusti to.
{94859}{94943}Nemoj iæi. Ništa|time neæeš pomoæi.
{94995}{95055}Želim se iæi poigrati.
{95573}{95640}Ljudi! Nancy Downs je ovdje!
{95678}{95684}Nancy?
{95704}{95768}Ovdje je? Znaèi tu je?
{95994}{96059}Je li Sarah s tobom?
{96468}{96523}Što se dešava?
{96540}{96573}Gdje je ona?
{96841}{96929}Ti i ja smo se nekada|lijepo zabavljali.
{96951}{97084}Ako se dobro sjeæam, bila su|to prilièno žestoka vremena.
{97112}{97142}Sjeæaš se?
{97148}{97206}Trudim se zaboraviti to.
{97211}{97285}Zaboraviti? Zaboravit æeš ovo?
{97291}{97320}Prestani!
{97400}{97452}Da li si raspoložen?
{97457}{97523}Misliš za to da mi odgrizeš kurac?
{97528}{97573}Otkud ti ideja da sam|to željela napraviti?
{97578}{97606}Odlazi!
{97710}{97743}Odlazi!
{97882}{97917}Ne!
{98431}{98477}Što to, jebote...
{98575}{98617}Iznenaðenje!
{98623}{98652}Sarah?
{98865}{98933}Vodi ljubav sa mnom, Chris.
{99248}{99317}Neæe biti ovdje.
{99299}{99372}A neæe ni Chris.
{99605}{99639}Rochelle!
{99680}{99746}Kako ide?
{99762}{99791}Dobro.
{99805}{99839}Slušaj...
{100222}{100265}Ti si vještica!
{100304}{100351}Bili su u pravu!
{100382}{100385}Obièno je tako.
{100403}{100455}Nancy, hajde. Ustani iz|kreveta, pa idemo.
{100485}{100490}I ona je vještica, znaš.
{100495}{100564}Zaljubljen si u nju samo|zato što te zaèarala.
{100570}{100586}Ne...
{100593}{100693}Da. Tužno, ali istinito.|Zato ja i jesam ovdje.
{100711}{100780}Da bih ti pomogla da je zaboraviš.
{100773}{100810}A što je to tebe briga?
{100814}{100903}Nancy, ustaj iz kreveta!|Na smrt si ga prepala!
{100909}{100970}Baš ti hvala! Idemo!
{101000}{101015}Ne! On mora platiti!
{101023}{101054}Samo si ljubomorna.
{101068}{101092}Ljubomorna?
{101097}{101126}Ljubomorna!
{101171}{101251}Ti za mene èak i ne postojiš!
{101271}{101442}Ti ne postojiš. Ti si ništa.|Ti si obièno govno.
{101498}{101634}Ti ne postojiš. Ti sa ženama|znaš samo kao s kurvama.
{101641}{101725}A ti si kurva. I to mora prestati!
{101748}{101855}Da li razumiješ? Razumiješ|li što ti govorim?
{101880}{101909}Žao mi je.
{101933}{101979}Njemu je žao!
{101985}{102064}Žao mu je! Žao mu je!
{102206}{102256}Ne!
{102668}{102742}Nisam željela da bude povrijeðen.
{102748}{102787}Sviðao mi se.
{102822}{102916}U dubini duše on je bio|dobar deèko. Nisam znala
{102924}{103024}da æe to dotle doæi.|Nisam mislila da može.
{103029}{103111}Daj, dušo, znam da ti je teško,|ali bio je to nesretan sluèaj.
{103119}{103170}Tata, potrebno mi je sad|da budem sama. U redu?
{103176}{103211}Dušo, saslušaj me.
{103216}{103320}Ne diraj me! Sve što dodirnem,|pretvara se u govno.
{104009}{104122}Vežem te da ne|možeš èiniti zlo, Nancy.
{104129}{104232}Zlo protiv drugih ljudi|i zlo protiv sebe.
{104288}{104419}Vežem te da ne|možeš èiniti zlo, Nancy...
{105304}{105360}Prestanite!
{105395}{105425}Stanite!
{106366}{106394}Tu si!
{106424}{106444}Svuda smo te tražile.
{106450}{106499}Da li si dobro? -Da, dobro sam.
{106513}{106578}Èule smo da ti je|policija dolazila u kuæu.
{106585}{106623}Bili su i kod mene.
{106630}{106694}Budite mirne. Ništa|im nisam rekla.
{106700}{106754}Zašto onda želiš napustiti krug?
{106746}{106785}Nisam to rekla.
{106790}{106851}I ne moraš reæi.|Razmišljaš o tome.
{106887}{106955}Slušaj, Nancy, ljudi|su poginuli, Chris i...
{106962}{106993}To su bile nesreæe.
{107007}{107045}Zaslužili su to.
{107062}{107075}Tko to kaže?
{107079}{107122}Ja. I znaš da je to istina.
{107126}{107169}Dobro. Kako hoæete. Izlazim.
{107175}{107215}Dobro. U redu je.
{107235}{107310}Ionako nam ne treba više|èetvrta, zar ne, cure?
{107317}{107340}Ne.
{107420}{107473}Ali ako veæ razmišljaš|da napustiš krug,
{107477}{107525}bolje razmisli o tome|da napustiš i ovu školu.
{107529}{107592}Ili možda i ovaj grad.|Još nismo sigurne.
{107605}{107660}Ili ovu planetu.
{107694}{107783}I molim te, nemoj više|bacati èini na mene.
{107789}{107815}Nisam...
{107855}{107890}Znaš,
{107898}{107936}u stara vremena
{108003}{108073}kada bi vještica izdala|svoje sljedbenike,
{108111}{108161}ubili bi je.
{108382}{108411}Bok.
{108465}{108514}Lijepo spavaj, Sarah.
{108552}{108599}Kako spavaš u posljednje vrijeme?
{109029}{109058}Dobar dan!
{109081}{109136}Halo?
{109150}{109205}Da?
{109210}{109275}Zdravo... -Što je bilo?
{109295}{109323}Što je bilo?
{109341}{109444}Znam da vas ne poznajem|dobro, ali nisam se imala kome
{109449}{109498}drugom obratiti.
{109504}{109576}One djevojke sa kojima|sam ovdje dolazila...
{109584}{109648}Pokušavaju upotrijebiti|magiju protiv mene.
{109654}{109734}Njome su ubijale ljude.|Pokušala sam ih vezati,
{109739}{109843}ali mi nije uspjelo. Sada su|svuda, gdje god se okrenem.
{109835}{109921}Svuda su oko mene i|ne znam što da radim!
{109927}{109995}Razumijete? Ona je|u mojim snovima.
{110001}{110098}Zna što se odvija u mojoj|glavi i može mi èitati misli!
{110103}{110196}Tako mi je žao! Nisam se imala|kome drugom obratiti.
{110202}{110229}Molim vas...
{110349}{110377}Doði.
{110839}{110865}Što je ovo?
{110870}{110921}Ovaj hram je sagraðen na moæi.
{111060}{111140}Sarah, nosiš ogromnu|svjetlost u sebi.
{111148}{111221}Veæu od bilo kog stvorenja|koje sam ikada upoznala.
{111226}{111260}Ne smiješ se bojati.
{111265}{111359}Ne mogu to kontrolirati.|Na kraju æu povrijediti nekog.
{111391}{111456}Èuješ glas svoje majke.
{111473}{111509}Što s njom?
{111522}{111585}Govori ti da budeš jaka.
{111595}{111663}I ona je bila vještica, naravno.
{111701}{111740}Zar nisi znala?
{111750}{111784}Nisam.
{111859}{111917}Možeš pobijediti one|koje te izazivaju,
{111923}{111987}ali se moraš pokoriti višoj sili.
{112204}{112261}Moraš prizvati duha.
{112280}{112326}On je uèinio da Nancy poludi.
{112330}{112390}Odveo je na mraèno mjesto.
{112413}{112455}Ne boj se. Kreni.
{112459}{112488}Ne mogu.
{112495}{112539}Nema drugog naèina.
{112607}{112719}Pozdravljam èuvare kule|stražare na sjeveru...
{112907}{112980}Ne mogu ostati ovdje!
{112992}{113054}Sarah, stani! Sarah!
{113709}{113742}Halo?
{113777}{113824}Tata!
{113843}{113887}Jenny!
{114202}{114224}Halo?
{114233}{114277}OTIŠLI SU.
{114288}{114375}ODLETJELI SU ZA SAN FRANCISCO.
{114371}{114438}MISLILI SU DA SI|POBJEGLA OD KUÆE.
{114526}{114615}SARAH, DOGODILA SE NESREÆA.
{114633}{114677}O èemu to prièaš?
{114714}{114784}ZAR NE ZNAŠ? -Što?
{114791}{114848}SVUDA JE PO VIJESTIMA.
{114940}{114969}UKLJUÈIT ÆU TI TV.
{114974}{115069}OLUPINA AVIONA SE NALAZI NA|PODRUÈJU JEDNE KVADRATNE MILJE.
{115077}{115181}SUMNJA SE DA JE DO TRAGEDIJE|DOŠLO ZBOG KVARA MOTORA.
{115199}{115267}KADA BUDE PRONAÐENA CRNA|KUTIJA, OTVORIT ÆE SE ISTRAGA.
{115260}{115350}JOŠ JEDNOM, LET 321 IZ LOS|ANGELESA ZA SAN FRANCISCO
{115355}{115405}SE SRUŠIO I NEMA PREŽIVJELIH.
{115435}{115459}Ne!
{115860}{115886}Ne!
{116806}{116849}Bože moj...Bože moj...
{117039}{117066}Ne!
{118133}{118159}Prestanite...
{118166}{118195}Prestanite!
{118240}{118303}Prestanite!
{118304}{118357}Ne, Nancy!
{118384}{118421}Prestani!
{118434}{118467}Imam te!
{118521}{118577}Bože...
{118557}{118666}Da sam tako patetièna kao ti,|ubila bih se još odavno.
{118659}{118708}Trebala bi poèeti s tim.
{119908}{119975}Gdje su moj tata i Jenny?
{119989}{120039}Uskoro æeš ih vidjeti.
{120075}{120134}Veèeras æeš se ubiti, dušo.
{120172}{120224}Ne, neæu.
{120279}{120318}Iznenaðena si?
{120333}{120365}Ne...
{120376}{120518}Stvarno? Nešto u tvojim oèima|mi govori da nisi tako sigurna.
{120537}{120619}Konaèno, imaš|razloga to napraviti.
{120624}{120712}Ubila si Chrisa, ubila svoju mamu.
{120757}{120848}Ubila si svoju mamu|dok si izlazila iz nje.
{120853}{120891}To je nešto stvarno posebno.
{120908}{120966}Ni ja to ne bih mogla|izvesti. Tako je!
{120970}{121002}Prestani, molim te!
{121042}{121137}U èemu je stvar? Zašto ne|primijeni magiju na nama?
{121142}{121178}Jer je slaba!
{121193}{121251}Slaba! Slaba! -Ne...
{121316}{121390}Bože, ovo je tako odvratno!
{121455}{121525}Sada je kraj, pustite|je da ode u miru...
{121531}{121619}Sada je kraj, pustite|je da ode u miru...
{121839}{121975}UBILA SAM CHRISA.|ŽAO MI JE. SARAH
{121970}{122045}Ja ovo nisam napisala.
{122050}{122167}Nije bitno. Rukopis je isti.|Što je to s tvojim ožiljkom?
{122250}{122263}Ovo nije stvarno.
{122268}{122365}Zašto onda još uvijek krvariš?
{122438}{122468}Trèi!
{122476}{122572}Trèi nazad u svoju sobu|kao kukavica kakva si ti!
{122642}{122702}Tako si bijedna!
{122826}{122902}Prestanite! Stanite!
{122989}{123061}Molim vas, stanite!
{123054}{123089}Molim vas!
{123282}{123342}Ne znam što da radim!
{123507}{123576}Rochelle, idi gore da|vidiš što se dešava.
{123581}{123648}Ne! Sve ovo je jednostavno...
{123654}{123794}Ne! Idi gore ili æu|ti prerezati grkljan!
{123808}{123894}Idi vidjeti gdje je. -Hajde,|idem s tobom.
{124001}{124093}Pozdravljam èuvare kule|stražare na sjeveru.
{124098}{124235}Prizivam moæi majke zemlje.|Prizivam vas. Prizivam vas...
{124260}{124311}Sarah! Sarah!
{124374}{124466}Neka moæ bude trostruka,|neka uvide... Neka moæ bude
{124472}{124536}trostruka, neka uvide...
{124639}{124665}Bonnie?
{124825}{124846}Moja kosa!
{124981}{125042}Vraæa se trostruko!
{125151}{125205}Ne ponovo!
{125271}{125307}Što se desilo?
{125316}{125374}Kuda æete?
{125355}{125406}Kuda ste krenule?
{125469}{125610}Pozdravljam èuvare kule|stražare na jugu...
{125649}{125711}Posegni u sebi...
{125753}{125827}Posegni u sebi...
{125974}{126067}Pozdravljam èuvare kule|stražare na sjeveru.
{126072}{126143}Prizivam moæi majke Zemlje.
{126149}{126197}Prizivam vas!
{126249}{126298}Prizivam te, Mano.
{126324}{126385}Prizivam te, Mano.
{126436}{126485}Prizivam te, Mano.
{126511}{126562}Prizivam te!
{126589}{126635}Prizivam te, Mano...
{128086}{128121}Sarah!
{128238}{128272}Sarah...
{128374}{128408}Sarah?
{128946}{129010}Da li sam te prepala,|Nancy? Oprosti.
{129045}{129076}Što se dogaða?
{129115}{129161}Zašto nisi mrtva?
{129167}{129225}Došao je kod mene i spasio me.
{129300}{129414}Želio je da ti prenesem poruku.|U velikim si govnima.
{129432}{129515}Rekao je da si zloupotrijebila|ono što ti je dao,
{129509}{129552}i sad æeš morati platiti.
{129569}{129613}Je li?
{129623}{129680}Jeste.
{129735}{129819}Usput, što se desilo|s Rochelle i Bonnie?
{129906}{129953}Istrèale su odavde, a|da se nisu ni oprostile.
{129958}{129991}To je jako nepristojno.
{130186}{130282}Što se dogaða?|Što se ovo dogaða?
{130421}{130425}Prestani!
{130432}{130475}Prestani!
{130477}{130512}Upomoæ!!!
{130888}{130942}Smiri se, to je samo magija.
{131054}{131102}Tko je sad bedan?
{131400}{131505}Malo sam luda. Ali nisam htjela.
{131589}{131661}Sve je izmaklo|kontroli i žao mi je.
{131705}{131773}Više neæe biti igara, u redu?
{131805}{131861}Sarah, tako mi je žao.
{131890}{131922}Dobro.
{131987}{132022}Sad æu otiæi.
{132028}{132064}Ali prvo jedna stvar...
{132091}{132169}Vežem te, Nancy, da ne|možeš nanositi zlo.
{132173}{132226}Zlo drugim ljudima i sebi.
{132219}{132243}Èekaj!
{132260}{132341}Vežem te, Nancy, da ne nanosiš|zlo drugima i sebi.   -Èekaj!
{132346}{132369}Vežem te...
{132675}{132789}Ne možeš me vezati! Ne možeš!
{132856}{132912}Ubit æu te! Ubiti!
{133620}{133649}Gdje si?
{133750}{133819}Gdje je Sarah?
{134051}{134079}Gdje si?
{134209}{134271}Trik, trik, trik...
{134699}{134734}Sarah...
{135112}{135223}Vežem te, Nancy,|da ne nanosiš zlo...
{135269}{135369}Vežem te, Nancy,|da ne nanosiš zlo...
{135529}{135556}Sarah?
{135568}{135595}Bok.
{135601}{135642}Sarah, kako si?
{135660}{135728}Dobro. Ponovno mogu|spavati noæu, pa...
{135741}{135776}Kako ste vi?
{135794}{135899}Željele smo se isprièati.
{135918}{135977}Stvarno se osjeæamo loše što...
{135982}{136032}Što ste me htjele ubiti?
{136092}{136180}Da. Iskreno, nismo mislile|da æe to tako daleko otiæi.
{136185}{136222}Bok, cure! Kako ste?
{136228}{136274}Dobar dan, g. Bailey!
{136284}{136384}Znaš da je ono na TV-u bio|samo trik. Samo neslana šala.
{136453}{136476}Baš smiješno.
{136495}{136525}Sarah, èekaj!
{136595}{136686}Samo smo se pitale da li|još uvijek imaš svoje moæi?
{136692}{136765}Jer ih mi nemamo.
{136807}{136842}Pa...
{136861}{136938}Ako hoæeš da se družimo, da se molimo ili obrazujemo uglove...
{136942}{137045}Možda. Zadržavajte dah|dok vas ne pozovem.
{137054}{137115}Vjerojatno i onako nema više moæi.
{137866}{137900}Èuvajte se.
{137907}{137977}Nemojte otiæi|tamo gdje i Nancy.
{138231}{138263}Ti!
{138311}{138441}Dao si mi moæ! Mogu|raditi s njom što hoæu!
{138446}{138484}Mogu letjeti!
{138564}{138630}Dala sam ti nešto da|smanjim tu moæ.
{138630}{138640}Ali ja mogu letjeti.|Ja letim. Ja letim.
{138755}{138830}Ja letim. Ja letim.
{139000}{139100}Ja letim... Ja... letim...
{139190}{139666}Subtitles by:|M O Z E N