{186}{260}SUMERIA, PRIJE 5000 GODINA|Od poèetka èovjeèanstva,
{261}{334}èovjek je poznavao bol|i patnju.
{335}{422}Rat ga je pratio
{423}{480}i smrt.
{534}{610}Divovi su takoðer|hodali zemljom.
{610}{674}Èovjek ih se bojao.
{674}{747}A Bog ih je prezirao.
{748}{818}Izbrisao ih je|sa lica
{819}{898}zemlje...
{899}{970}sve do sada.
{1463}{1580}Uðite, gospodaru Ammon,|jer ovo je vaša kuæa.
{1630}{1677}Gdje je moj sin?
{1678}{1737}Vratio se prošle noæi.
{1738}{1791}Na sigurnom je, gospodaru.
{1792}{1840}Za sada.
{1841}{1887}Reci.
{1888}{1936}Hebrejski Bog je...
{1936}{1996}Možda više nisam|u njegovoj milosti,
{1997}{2054}ali neæu dopustiti|tvoje vrijeðanje.
{2055}{2169}Kako se usuðuješ spominjati|postojanje drugog boga?
{2170}{2241}Nisam želio uvrijediti,|moj gospodaru.
{2459}{2561}Težina grijeha, sveèeniæe.
{2668}{2738}Reci mi koja|je vijest od mog oca.
{2738}{2847}Yahweh je sudio jednako|i ljudima i Nephilima.
{2848}{2916}Svi æemo biti uništeni
{2917}{2985}uslijed velikog|potopa.
{2986}{3014}Moja braæa?
{3014}{3100}Pali anðeli æe takoðer|biti udavljeni u vodi,
{3101}{3168}takva je poruka Yahweha.
{3191}{3275}Ne bih trebao oèekivati milost.
{3295}{3345}Odluèili smo|hodati zemljom
{3346}{3462}iskoristili kæeri njegovog|omiljenog stvorenja... èovjeka.
{3486}{3583}Ne mogu zanijekati|to potomstvo.
{3714}{3742}Pozdrav, oèe.
{3742}{3791}Aramise, slijedeæih dana,
{3792}{3842}veliki potop
{3843}{3892}uništiti æe|sav život.
{3893}{4019}Moram biti spreman|na veliko žrtvovanje.
{4020}{4071}Boriti æu se.|Preživjeti æu.
{4072}{4083}Ne.
{4084}{4199}Njegova volja biti æe|provedena. Umrijeti æeš.
{4200}{4268}Oèe!
{4269}{4359}Kada èovjeèja ruka|otkrije tvoj grob,
{4360}{4449}poèeti æe novo|doba Nephilima,
{4450}{4532}i još jednom|oni æe znati
{4533}{4615}koja je osveta|posrnulih.
{6294}{6340}Uskoro æe vrijeme,|moj gospodaru.
{6341}{6405}Robovi su spremni|da putuju s njim
{6406}{6456}na drugi svijet.|A Aramis?
{6457}{6523}Mrtav je.|Do zore æemo...
{6600}{6674}Rekao si da je|mrtav.
{6734}{6847}Nije zbog vašeg prisutstva. Vaša|moæ ga je oživjela.
{6848}{6894}Aramis.
{6918}{6995}Zašto je takav?
{6996}{7039}On je samo prazna|ljuska, moj gospodaru.
{7040}{7114}Otrove koje smo koristili da|ga ubijemo, uništili su mu mozak.
{7115}{7173}Želio sam saèuvati sina
{7174}{7244}ne ga uèiniti budalom!
{7658}{7785}Nije još vrijeme da|hodaš ponovno, Aramise.
{7786}{7837}Žao mi je.
{7872}{7937}Spavaj, sine moj.
{10125}{10182}Matt?
{10217}{10259}Matt?
{10260}{10325}Što radiš tamo dolje?
{10576}{10606}Dobro si?
{10607}{10665}Ljestve su se slomile.
{10666}{10724}Daj mi ruku.
{10879}{10946}Mala mumija.
{10946}{11017}Prokletstvo.
{11018}{11127}Oh, Isuse. Oprosti.|Hajde van.
{11329}{11374}Isuse.
{11374}{11449}Pitam se kako|je ovaj mališan
{11450}{11487}ostao tako saèuvan.
{11488}{11591}Vlažne kosti,|savršen mrtvaèki pokrov.
{11592}{11693}Smiješno, ali ne izgleda|ritualno obraðen.
{11847}{11896}Vidiš, izvaðen mozak,
{11897}{11951}vjerovatno i drugi organi.
{11952}{12004}To je ritualna mumifikacija.
{12005}{12101}Èak niti Anasazi ne bi|tome posvetio toliku pažnju.
{12111}{12169}Možda nešto što su Maje|znali uèiniti.
{12170}{12226}Ne postoje dokazi da su|Maje ikada putovali
{12227}{12283}ovako daleko na sjever,|profesore Fletcher.
{12284}{12338}Tko zna?
{12339}{12462}Pronaðemo nekoliko posuda i kost|ili dvije i mislimo da znamo sve.
{12463}{12498}Ako ovo je pripadnik Maja,
{12499}{12567}možda prekrojimo sadržaj|nekoliko povijesnih knjiga.
{12568}{12635}Ovaj mališan možda|je ona velika stvar
{12636}{12666}koju toliko tražimo.
{12666}{12703}Želim odvesti ekipu|dolje.
{12704}{12794}Ne bez kaciga|i ostale opreme.
{12795}{12860}Bio sam dolje sam, Joseph.
{12861}{12876}Sigurno je.
{12877}{12944}Ta rupe nije tamo|bila prije tri dana.
{12944}{13010}We're two miles|from the fault line.
{13011}{13067}Kako možeš reæi|da je sigurno?
{13068}{13134}Našom eksplozijom|otvoren je taj otvor,
{13135}{13152}ne potres.
{13153}{13275}Upravo sam shvatio da možda nisi|ništa nauèio u Meksiku.
{13482}{13589}Joseph, ti si kreten.
{13798}{13872}Želiš se pobrinuti za|to, Jenny? Hvala.
{13872}{13945}Što se to|dogodilo u Meksiku?
{13946}{13977}Oh, Bože.
{13978}{14008}Joseph.
{14009}{14071}On je tip momka|koji bi
{14072}{14125}dodao malo soli|na ranu.
{14126}{14197}Meksiko se dogodilo|prije nekoliko godina,
{14198}{14245}Matt je bio|dolje sa ekipom.
{14246}{14292}Pregledavali|su peæinu,
{14293}{14340}u nekoj|prašumi.
{14341}{14409}Pronašao je prolaz|ispod vode,
{14410}{14479}i krenuo, bez da se vratio|po ronilaèku opremu,
{14479}{14547}ili da je nekome rekao|kamo su krenuli.
{14548}{14610}Doslovno su uronili.
{14635}{14766}Voda je bila dublja,|a prolaz duži
{14767}{14821}nego što je|mogao pretpostaviti.
{14822}{14890}Tamo je bilo|nekoliko manjih prolaza.
{14891}{14940}Nekoliko momaka|je ušlo u neke od njih.
{14941}{15034}Matt je jedini|koji je izašao.
{15082}{15149}Što misliš o tome?
{17072}{17131}Profesore Fletcher!
{17132}{17177}Matt!
{17375}{17434}Uzmi radio i pozovi Mortona.
{17453}{17510}Ovo je veliko otkriæe.
{17598}{17656}Stvarno veliko.
{17794}{17872}Izrièito sam zapovijedio da|ovo ne dirate.
{17873}{17925}Razumio sam vas, gospodine.|Ali, gosp. Morton...
{17926}{18003}Ali što? Tko je|to pomaknuo? - Ja sam.
{18004}{18067}Ti si Matt?
{18068}{18118}Da.
{18119}{18156}Oh, da, Charles|mi je rekao za vas.
{18157}{18217}Nisam vas oèekivao ovako|brzo. Barstow, zar ne?
{18218}{18299}Angela Barstow. Ja sam strukturalni|inžinjer, zadužena za sve.
{18300}{18377}Žalim što vam to moram|reæi, ali...
{18378}{18454}ja sam ovdje|zadužen za sve.
{18454}{18510}Zaista?
{18510}{18558}Da. Ovo je|moje nalazište.
{18558}{18652}Morton neæe cijeniti to|što oduzimate moje vrijeme.
{18653}{18728}Ja sam ovdje arheolog.
{18729}{18761}Ono što mi je on rekao,
{18762}{18829}upali ste u rupu|i posreæilo vam se.
{18830}{18879}Zgodan naèin|kopanja, šefe.
{18880}{18969}Neka ostane na tome.|- Dobro.
{19241}{19316}Našli smo nešto na toèki 17,
{19317}{19354}pa prebacujemo opremu.
{19355}{19411}Morati æemo kopati okolo,
{19412}{19518}što znaèi da treba preusmjeriti|cijevi u dužini oko 2000 stopa.
{19518}{19574}Gus ima nove planove i mape
{19574}{19590}za glavešine.
{19591}{19694}Želio bih da završimo to
{19694}{19747}do kraja mjeseca.
{19748}{19764}Jasno?
{19765}{19843}Sada krenite. Imamo|mnogo posla.
{20085}{20161}Charles, da li bi htio objasniti|nekoliko stvari ovoj gospodièni?
{20162}{20245}Slušam, ali trebalo bi objasniti|ovom Indiana Jonesu
{20246}{20328}da su ljudi prestali koristiti rijeè|"gospodièna" negdje oko 1955.g.
{20329}{20376}Vidim da ste|se upoznali.
{20377}{20436}Ponaša se kao|da upravlja ovim mjestom.
{20437}{20483}Ti i ja smo dogovorili|da je to moje nalazište.
{20484}{20586}Fletcher upravlja|nalazište.
{20586}{20609}Prokleto toèno.
{20610}{20669}Samo malo. Kad ste me pozvali|da doðem ovamo...
{20670}{20707}Dajte da završim.|Nakon onog fijaska u Utahu,
{20708}{20795}u svezi indijanskih artefaka,|zaposlio sam ga da procijeni stanje
{20796}{20853}da bi bili sigurni da|neæemo iskopati nešto
{20854}{20910}što æe nam se|poslije vratiti u glavu.
{20911}{20949}Pomalo je usijana glava,
{20950}{21032}ali je jedan od najboljih|kopaèa u poslu.
{21033}{21082}To mi je i on rekao.
{21082}{21124}A što se tièe Angele,
{21125}{21198}ona odluèuje o|tome kako æeš kopati.
{21198}{21219}Jasno?
{21220}{21255}Oh, dovraga, Charles.
{21256}{21347}Trebamo izvuæi puno zemlje, a|sprijeèiti da ne doðe do urušavanja.
{21348}{21368}To je Angelin posao.
{21369}{21426}Ne želimo se probuditi i|gledati velikog momka zatrpanog
{21427}{21486}sa nekoliko stotina tona zemlje.
{21486}{21573}Postupaj s njom dobro.
{22047}{22109}Tri koze.
{22110}{22170}Ne, ovce.
{22170}{22210}Tri ovce.
{22210}{22260}I mlijeko jedne koze,
{22261}{22338}u zamjenu za|kolaèiæe.
{22339}{22394}Jesam li ja kolaèiæ?
{22395}{22476}Još uvijek volite malo kave|i puno mlijeka, profesore?
{22477}{22574}Matthew, sjedni.|Lijepo što si došao.
{22618}{22662}Oh, moraš biti vidovnjak.
{22662}{22730}Kafeterija,|imaju kavu,
{22731}{22797}ali ne prave|mocha latte,
{22798}{22898}a njihova ideja o|velikoj èaši i nije tako velika.
{22899}{22937}Dakle...
{22938}{23013}što je, gospodin|velika faca?
{23014}{23071}Uvlaèiš se, ha?
{23072}{23120}Znaš, veæina|nas mora moliti
{23121}{23227}na koljenima da bi |dobila
{23228}{23286}Koliko dugo si|sa Mortonom?
{23287}{23336}Dvije godine.
{23337}{23425}Zašto se ne vratiš predavati?
{23457}{23528}Ne poèinju sa|gradnjom na podruèju,
{23529}{23619}dok ne potvrdim da na zemljištu|ne postoji ništa arheološki važno.
{23620}{23685}Zaista jako pazimo.
{23730}{23786}Zašto ne bi bili?
{23786}{23823}Samo sam želio da
{23824}{23896}znate da ne dovodimo|ništa u opasnost.
{23897}{23920}Matthew, jesi li siguran
{23921}{23986}da nisi pomalo Židov|tu gore, ha?
{23986}{24060}Nosiš se sa krivnjom|kao profesionalac.
{24061}{24107}Bio sam na istražnoj komisiji.
{24108}{24238}Jedina osoba koja te krivila za|nesreæu, bio si ti sam.
{24255}{24322}Želio bih da mi|nešto prevedete, Eli.
{24323}{24401}Samo to ovdje i radim.
{24402}{24438}Gledajte...
{24439}{24554}90% od starih tekstova|je poput ovih.
{24554}{24600}Potvrde. Pogledaj...
{24601}{24663}"Koliko koza je èovjek|mijenjao za ženu.
{24664}{24746}"Tko je vlasnik bunara".
{24747}{24798}Advokati, raèunovoðe,
{24798}{24908}èak i u ona vremena, Matthew.|Oni su upravljali sa svim.
{24909}{24920}Feh.
{24921}{24991}Pogledajte ovo.
{25148}{25231}Ljudski zglob...
{25286}{25328}Ne...
{25328}{25369}ruka.
{25370}{25440}To je èovjeèja ruka.
{25441}{25511}Ovo je vrlo staro.
{25512}{25582}Starije od starog.
{25606}{25641}Struktura pisanja
{25642}{25745}je kao kod|starih plemena.
{25759}{25810}Gdje si to pronašao?
{25810}{25904}Pokazati æu vam.
{26170}{26248}Seik...? Ne.
{26249}{26282}Tempest.
{26282}{26337}Rabine, dobili|ste paket.
{26338}{26406}Hvala ti, draga.
{26444}{26510}Tvrke za proizvodnju|baterija me vole,
{26511}{26549}je neprestano zaboravljam|iskljuèiti ovu stvar.
{26550}{26626}Izraðuju ih tako da se ugasi|sam, kad prestaneš govoriti.
{26626}{26697}Da, ali tko|vjeruje tehnologiji, ha?
{26698}{26782}Ah, u pravo vrijeme.
{26800}{26892}Znaš, imam|nešto za priznati.
{26893}{26935}Poznajem sumerske simbole
{26936}{26996}kao što znam|što sam doruèkovao.
{26997}{27084}Ali kad se radi|o starom hebrejskom,
{27085}{27171}kad bih rekao da sam zahrðao,|bila bi to blaga kritika.
{27558}{27670}"I velika poplava æe|ih uništiti."
{27809}{27867}Imaš li što, doktore?
{27868}{27940}Nešto, Mickey.
{27941}{28065}Kao onaj film o tri klinca,|koji su se izgubili u šumi.
{28066}{28145}Nije li mu i meðunožje|isušeno?
{28146}{28224}Njegovo meðunožje,|barem njegov veæi dio,
{28225}{28306}je u nekoj ogromnoj|posudi tamo negdje.
{28307}{28392}Vjerovatno su zamijenili|sve njegove organe,
{28393}{28472}sa biljkama, možda lišæem
{28473}{28521}ili talismanima.
{28522}{28590}To je ono što je fascinantno|na toj mumiji.
{28591}{28641}Više nalikuje na|egipatsku mumiju,
{28642}{28704}nego išta što je pronaðeno|na ovom kontinentu.
{28705}{28760}To je ono fascinantno.
{28761}{28825}Ne da je|velièine kamiona?
{28826}{28876}Da, to isto.
{28876}{28925}Prièekaj malo!
{28926}{29016}Mickey, vrati se, polako!
{29075}{29150}Samo malo, zapelo je.
{29170}{29247}Ok, da fokusiram.
{29261}{29323}Oh, moj Bože.
{29324}{29384}To su ljudi?
{29385}{29449}Kamera je prenisko da bi|mu bila na stomaku.
{29450}{29533}Pretpostavljam da ne gledamo|njegovo posljednje jelo?
{29534}{29617}S faraonima su èesto|pokapali i njihove sluge.
{29710}{29746}Izgleda kao da su|tamo postavljeni.
{29747}{29870}Mickey, gdje smo u|odnosu na njegove organe?
{29895}{29965}Negdje oko desnog bubrega.
{29966}{29997}Tako sam i mislio.
{29998}{30094}Mislim da su postavljeni tamo|da bi zamijenili bubreg.
{30094}{30223}Mislim da æemo pronaæi još tijela|u pluæima i srcu.
{31722}{31822}Nisam raspoložen|za igru.
{32237}{32321}Rekoh, ne želim se|zajebavati uokolo!
{32927}{32978}Ružan momak, ne?
{32978}{32995}Ne znam.
{32996}{33069}Rekao bih da dok je bio|živ bio je dosta zgodan.
{33070}{33130}Veæina akromegalika|ima izoblièene dijelove tijela.
{33130}{33206}Kosti nastavljaju rasti kad|sve druge prestane.
{33207}{33269}Ovaj momak je|dosta proporcionalan.
{33270}{33308}Dosta što?
{33309}{33362}Akromegalici...
{33363}{33441}ljudi koji boluju|od gigantizma.
{33482}{33558}Eli, zašto misliš da|još nitko nikada
{33558}{33633}nije naišao na|jednu od ovih stvari?
{33634}{33703}Da li je tvoja baka|još uvijek živa?
{33704}{33726}Što?
{33726}{33811}Tvoja baka, pretpostavljam|da je preminula, ne?
{33812}{33860}Da, još kad sam|bio klinac.
{33861}{33926}Da, ali što ako,|i ne želim te uvrijediti,
{33927}{33996}bi želio sada ekshumirati|njezino tijelo,
{33996}{34063}iz njezinog lijepog kovèega|iz 20. stoljeæa,
{34064}{34154}da li misliš da bi mnogo|ostalo od nje.
{34155}{34174}Ne.
{34175}{34252}Naš prijatelj ovdje bio|je zakopan u zemlju
{34253}{34305}preko 50 stoljeæa.
{34306}{34367}Da ne spominjem,
{34368}{34436}da se èini da je na|pogrešnom kontinentu.
{34436}{34490}Èudim se da smo|pronašli i ovog jednog.
{34491}{34542}Oprostite, gosp. Morton.
{34543}{34602}Gus je prikupio ekipu sa raznih|mjesta i spremni su.
{34603}{34665}Vani su ako im se|želite obratiti.
{34666}{34725}Evo me odmah.
{34726}{34794}Eli, imaš pravo|u svezi moje bake,
{34795}{34861}ali vidio sam kosti dinosaura
{34862}{34927}približne starosti|oko 70 milijuna godina.
{34928}{34972}Što kažeš na to?
{34973}{35070}Nadao sam se da se|toga neæete dosjetiti.
{35202}{35259}Što je?
{35260}{35316}Joseph je nestao.
{35317}{35337}Ne znam.
{35338}{35403}Ostavio je otkljuèanu kuæu.|Svjetla su bila upaljena.
{35404}{35455}Pronašli su njegov|nož oko 30 stopa
{35456}{35562}from the front door|by that new mustang.
{35598}{35673}Slušajte, uskoro æe|se smraèiti,
{35674}{35714}Joseph nije tip momka
{35715}{35781}koji bi se otišao napiti|i nestati.
{35782}{35850}Možda se razbolio ili nešto,
{35851}{35882}ili se dezorijentirao.
{35882}{35964}Ove planine su opasne,
{35965}{36029}sa svakakvim vrstama|peæina i tunela.
{36030}{36044}Pripazite malo,
{36045}{36150}ako što primjetite|radijem javite Gusu.
{36150}{36254}Ja æu sa Jerryjem|gore u helikopter.
{36302}{36350}Nikad ih nisam vidio|da su se pokrenuli tako brzo.
{36351}{36406}Mora da su stvarno|zabrinuti za Josepha.
{36407}{36549}Ne, tko ga prvi pronaðe|dobiva sanduk piva.
{36550}{36581}Oh.
{36582}{36626}On im je prijatelj.
{36626}{36662}Hajde, Matt.
{36662}{36696}Govorimo o Josephu.
{36697}{36771}Iako, on je najbolji prijatelj|kojeg je itko od njih ikad imao.
{36772}{36871}Zbog toga nisam|im ponudio baèvu piva.
{36890}{36968}Mickey, pomoæi æu vam|u potrazi.
{36969}{37046}Oh, nisam znao|da piješ.
{37315}{37409}Gdje je policija?|Zašto nisu došli ovamo?
{37410}{37461}Moraš odavde otiæi|preko 40 milja,
{37462}{37533}da bi pronašao nekoga tko|nije šerif samo na papiru.
{37534}{37627}Morton ionako voli da|sve ostane unutar tvrtke.
{37628}{37721}Vjerovatno je samo zabrinut|da je Joseph odustao od svega,
{37722}{37835}iako mu je upravo|isplatio dodatak na plaæu.
{37836}{37852}Kakav dodatak?
{37853}{37920}Platio sam nekolicini momaka|da drže usta zatvorena,
{37921}{38000}da se ne bi proèulo o|našem velikom momku.
{38001}{38079}Nama vjeruje pa|nismo dobili ni lipe.
{38080}{38118}Ravno naprijed je postrojenje.
{38118}{38243}Kompleks starog|kamenoloma.
{38244}{38318}Ne vjerujem da je|Joseph otišao tako daleko.
{38318}{38390}Ali nastaviti æemo tražiti.
{38390}{38454}Matt. Matt.
{38455}{38518}Matt.
{38986}{39071}Pokušavam ti reæi|da usporiš.
{39072}{39138}Gus, javi se.
{39139}{39175}Andy, ovdje Gus.|Reci.
{39176}{39271}Nevolje. Ja i Pete smo provjeravali|peæine oko nalazišta 3.
{39272}{39300}Nestao je.
{39301}{39334}Nestao? Kako misliš|nestao?
{39334}{39382}Otišao sam pišati i|èuo sam Petea kako puca.
{39382}{39428}Ali kad sam se vratio|do kamioneta, nestao je.
{39429}{39522}Tamo smo za nekoliko minuta.|Reci mu da nas èeka tamo.
{39523}{39582}Nisi trebao iæi pišati.
{39583}{39642}Drži se. Pete se može|pojaviti svakog trena.
{39642}{39707}Stižemo ubrzo.
{40157}{40213}Andy!
{40293}{40339}Krv.
{40340}{40411}Još je netko bio|ovdje osim Petea i Andyja.
{40412}{40473}Izgleda kao Andyjev radio.
{40494}{40556}Izgleda da Joseph|nije jedini
{40557}{40620}koji je nestao.
{40620}{40682}Andy!
{40682}{40776}Nekakva protestna grupa|ili nešto slièno?
{40776}{40869}Tko zna? Morton si je|stvorio mnogo neprijatelja.
{40911}{41040}Mogla bi biti i neka suparnièka|graðevinska tvrtka.
{41110}{41152}Hej, momci!
{41211}{41269}Hej, momci!
{41548}{41597}Prestani se micati!
{41652}{41727}Znao sam da æe se|odrastanje sa starijom sestrom
{41728}{41806}jednog dana isplatiti.
{41807}{41909}Mislim da sam ti svinuo|kljuè za mijenjanje toèkova.
{41910}{42001}Nadam se na neæemo|probušiti gumu na putu odavde.
{42009}{42061}Charles,|ovdje Gus.
{42062}{42103}Da li ste pronašli Josepha?
{42104}{42124}Nismo.
{42125}{42203}Ustvari, još|su dvojica nestala.
{42204}{42235}Što, nestala?
{42236}{42320}Imamo ovdje malo|nezgodnu situaciju, Charles.
{42321}{42419}Dovraga. Šaljem|ljude odmah.
{42420}{42478}Dobro.
{42498}{42570}Nije zvuèao sretno.
{42570}{42666}Mislim da nam to|nije najveæi problem.
{44081}{44129}Oh, da!
{44391}{44453}Matt, odveli su Mickeya.
{44534}{44566}Izgledaš usrano.
{44567}{44597}Bili smo napadnuti.
{44598}{44667}I onda su jednostavno|nestali, kad smo tražili Mickeya.
{44668}{44743}Preveliki problem da se|sami s njim nosimo.
{44744}{44826}Slažem se. Što je to?
{44842}{44885}Moja ostavka,
{44886}{44939}i kopija onoga što|æu reæi policiji
{44940}{44987}o tome što se dogodilo|Mickeyu i ostalima.
{44988}{45054}Veæ sam nazvao nekoga|da se pobrine za stvari.
{45054}{45108}On je najbolji u|poslovima zaštite.
{45109}{45166}Biti æe ovdje sutra ujutro.
{45166}{45252}Ne treba nam policija.
{45252}{45336}Ne treba nam policija?
{45337}{45394}Charles, èetiri èovjeka|su nestala.
{45395}{45451}Veæ sam to prošao.
{45452}{45526}Ne želim više riskirati|nièiji život, zbog nièega.
{45527}{45588}Policija neæe uèiniti|ništa drugo
{45589}{45697}od onoga što sami radimo, osim|što bi nam zatvorili posao.
{45698}{45805}Da li se samo o tome|radi, o projektu?
{45845}{45887}Što misliš, što æe se|dogoditi
{45888}{45966}kada doðu ljudi|iz ministarstva
{45967}{46045}da poprièaju o našoj 42 stope|velikoj mumiji zakopanoj pod zemljom?
{46099}{46184}Još im nisi ništa o|tome rekao?
{46186}{46295}Rekao si da æeš ih nazvati, pa æemo|ovaj put sve odraditi prema zakonu.
{46296}{46390}Imam desetogodišnje iskustvo|u pregovaranju o pravu na zemljište
{46391}{46425}i njeno iskorištavanje
{46426}{46510}i dvogodišnje u|arhitektonskom planiranju.
{46534}{46565}Matt...
{46566}{46632}to nalazište|vrijedi milijune.
{46633}{46734}Zamisli koliko æe radnih mjesta|omoguæiti. Pogledaj samo Las Vegas.
{46735}{46778}Nije vrijedno toga.
{46778}{46856}Ne znamo niti da li su Mickey|i Joseph uopæe živi.
{46856}{46933}Prièekaj barem iza vikenda.|Za to vrijeme možeš ih nastaviti tražiti.
{46934}{46991}Ako do tada ne|pronaðemo ljude,
{46991}{47048}otiæi æu s tobom|na policiju.
{47080}{47189}Charles, da se radi|o nekome drugome,
{47190}{47266}rekao bih da zaborave|na cijelu stvar.
{47267}{47341}Ali ti si uvijek prema|meni bio pošten.
{47342}{47444}Imaš vremena do ponedjeljka,|ali moramo ih pronaæi.
{47716}{47849}U osnovi, ovo potvrðuje|moje sumnje.
{47850}{47934}Ova mumija je jedan|od Nephilima,
{47935}{47985}Posrnuli.
{47986}{48030}Bili su izrodi,
{48031}{48129}djeca palih anðela|i ljudskih žena.
{48165}{48267}To mora da je bila|problematièna trudnoæa.
{48292}{48382}Otac ovoga, bio je|voða svoje vrste,
{48383}{48410}uništavatelj.
{48411}{48491}Još nisam uspio otkriti|njegovo ime,
{48492}{48610}ali on je jedan od anðela koji|su poslani da unište Sodomu,
{48610}{48711}ludi grad grijeha, koji je|izrastao u pustinji.
{48712}{48811}Mislio sam si da æete|promijeniti mišljenje, gosp. Morton.
{48812}{48903}Èini mi se da imate dva sigurnosna|problema na koja morate misliti.
{48904}{49014}Vaši nestali radnici i ona stvar|koju ste pronašli.
{49015}{49078}To æe se odraziti|i na moju cijenu.
{49113}{49210}Dobro. Sve dok se|to podrazumijeva.
{49211}{49292}Doæi æu sutra.
{49540}{49644}Dokument takoðer|opisuje i proroèanstvo.
{49644}{49747}Ono kazuje o|povratku uništitelja.
{49924}{50006}Udaramo u granit.|Da pokušamo drugdje?
{50006}{50092}Ne, hvala, gotovi smo.
{50126}{50179}Mickey je mršav, ali ne vjerujem|da bi stao tamo.
{50180}{50269}Samo pokušavam otkriti kakva|je stabilnost tla na kojem stojimo.
{50270}{50344}Peæina koju si mi pokazao nije|udaljena više od nekih deset stopa.
{50345}{50419}Ako se ti ljudi pojavljuju i|nestaju kao što si rekao...
{50420}{50456}Kako to misliš "Ako"?
{50457}{50505}Moraju nekamo otiæi.
{50506}{50567}Možda postoji peæina|ili tunel,
{50568}{50629}a mi ga još|nismo pronašli.
{50695}{50779}Ili je u pitanju|jednostavno magija.
{50812}{50853}Hvala.
{51894}{51966}Ako nastavimo udarati u|sami kamen, bez šupljina,
{51967}{52007}neæemo pronaæi|nikakav tunel.
{52008}{52067}Sutra æu donesti|sonarnu opremu.
{52068}{52158}Možeš li mi ujutro|pomoæi s tim?
{52159}{52200}Naravno.
{52200}{52239}Što je?
{52240}{52337}Kao što si rekla, magija.
{52372}{52473}Trebamo otiæi odavde.|Nije sigurno.
{52761}{52823}Nisam kod kuæe.
{52859}{52914}Lijep konj.
{52915}{52986}Hvala.|Dao mi ga je tata.
{53054}{53148}Još uvijek želiš da ti|pomognem sa onim sonarom?
{53149}{53160}Da.
{53161}{53266}Buduæi da nisi bio ovdje jutros|u 7 sati, otišla sam malo jahati.
{53267}{53293}Mislio sam da si rekla...
{53294}{53374}Toèno... Rekla si|u 7 sati... Oprosti.
{53375}{53424}Nema veze.
{53555}{53626}Hvala.|Prièekaj me sekundu.
{53819}{53900}Gledaj, ja...
{53901}{53946}Htjedoh reæi|da mi je žao
{53947}{54030}zbog naèina na koji sam|se ponio neki dan.
{54056}{54098}Ja...
{54099}{54177}Osjeæao sam kao da|gubim kontrolu.
{54242}{54277}Inaèe, sam i|uvijek toèan.
{54278}{54381}U redu je. I vrijeme je da|budeš smušen.
{54382}{54441}Ti si rak.
{54442}{54488}Znaš...|tvoj horoskopski znak.
{54489}{54562}Kako si znala|da sam rak?
{54562}{54617}Pogledala sam tvoj dosije.
{54618}{54662}To mi je hobi.
{54663}{54706}Astrologija.
{54707}{54768}24.lipanj, rak...|pod utjecajem mjeseca,
{54769}{54881}a buduæi æe prekostutra|biti mala pomrèina,
{54882}{54952}tvoj je red da|budeš pomalo smušen.
{55001}{55070}Biti æe pomrèina mjeseca?
{55129}{55249}Da, vrijeme da ludi|postanu još luði,
{55250}{55337}poveæati æe se|broj samoubojstava
{55338}{55388}a rakovi æe se ponašati|malo ludo.
{55389}{55456}Da je moja tetka ovdje,|molila bi za tvoju dušu.
{55456}{55521}Pentekostalci ne vjeruju|u ta proroèanstva.
{55522}{55611}Dobro da sam svoje naprave|za vradžbinu ostavila unutra.
{55612}{55700}Moglo je biti i gore. Da me|odgoje kao baptista.
{55754}{55773}Nema kartanja,
{55774}{55858}a vjerovali su da|predbraèni seks vodi do
{55858}{55914}ispijanja piva|i plesanja.
{55915}{56009}Pa, ponekad pijem pivo,|tu i tamo...
{56126}{56214}A uvijek sam htjela|nauèiti plesati.
{56426}{56518}Mislio sam da æeš|doæi malo ranije.
{56518}{56557}Izvini, Gus. Zaboravio sam|na vrijeme.
{56558}{56682}Nema problema. Znam kakvi ste vi|rakovi u ovo vrijeme.
{56682}{56769}Kome si sve rekla o|tim horoskopskim ludostima?
{56770}{56800}Nikome.
{56801}{56858}Na radiju ti je bila pritisnuta|tipka za odašiljanje.
{56859}{56953}Svi koji su bili na drugom kanalu,|mogli su æuti jutarnje èavrljanje,
{56954}{57093}a usput, kad æeš odvesti|tu djevojku na ples?
{57173}{57226}Želiš mi pomoæi ovdje?
{57227}{57313}Matt! Matt!
{57382}{57418}Da li mi se i to|treba dogoditi?
{57419}{57484}Kako se to moglo dogoditi?
{57485}{57547}Nitko nije prošao pored|mene.
{57548}{57585}Za Boga miloga,|Dennise,
{57586}{57641}nije ustao i sam|izašao kroz vrata.
{57642}{57694}Nitko te ne optužuje za|ništa, Dennise.
{57695}{57827}Nijedan od ovih znakova nije|bio na kamenju koje je bilo gore.
{57850}{57883}Oh, moj Bože.
{57884}{57922}Upravo smo saznali.
{57923}{57998}Nije dobro,|Matthew.
{57999}{58073}Morton æe|popizditi.
{58293}{58351}Nije nimalo dobro.
{59629}{59672}Ja sam Raphael Ammon.
{59673}{59765}Angela Barstow,|strukturni inženjer.
{59785}{59854}Dobro ste,|gospoðice Barstow?
{59854}{59889}Dobro sam.
{59890}{59953}Dobro je. Malo|je dehidrirala.
{59954}{60044}Bila je na jahanju jutros.|Matt Fletcher.
{60045}{60124}Arheolog.
{60134}{60193}Vi mora da ste super|policajac za iznajmljivanje.
{60194}{60246}Moj tim se rasporeðuje|po planini,
{60246}{60265}okružujuæi dolinu.
{60266}{60386}Gosp. Ammon inzistirao je doæi ovamo|i prije nego smo mu pokazali smještaj.
{60386}{60439}On se bavi time, Matt.
{60440}{60464}Dobro.
{60465}{60561}Jer još je|netko nestao.
{60624}{60686}Pokušaj sada.
{60686}{60710}Ista stvar.
{60711}{60752}Ton ide dolje samo nekih|osam stopa
{60753}{60885}i sonar pokazuje samo stijenje|slijedeæih 5 stopa.
{60958}{61009}Nadaš se da je|kamen samo iluzija?
{61010}{61078}Tvoja pljuvaèka æe|proæi kroz kamen?
{61078}{61175}Pokušavam pogoditi pauka.
{61235}{61296}Kako je 42 stope visoka,
{61297}{61388}i 20 tona teška mumija otišla|odavde, a da to nitko nije primjetio?
{61389}{61449}Zaboravio si,|mrtva mumija.
{61450}{61509}Mrtva gigantska mumija.
{61510}{61583}Netko ju je morao uzeti.
{61630}{61689}Iskoristili ste vrijeme|koje ste zahtjevali.
{61690}{61786}Gosp. Ammon vas želi napolju, kako|bi mi napravili svoju inspekciju.
{61786}{61864}Reci Ammonu da prièeka.|Nismo gotovi.
{61865}{61941}Možete mi reæi i sami,|gosp. Fletcher.
{61942}{62024}Moj odgovor æe|biti isti.
{62068}{62108}Matthew.
{62109}{62196}Molim vas idite... odmah.
{62197}{62271}Koji je vaš problem, gospodine?
{62272}{62321}Gurate nas u stranu.
{62322}{62377}Ovdje ste veæ cijeli dan|i ne èini mi se
{62378}{62461}da vaši ljudi traže|naše nestale.
{62490}{62551}Matthew, nemoj.
{62552}{62629}Slušaj starca.
{62783}{62890}Slušaj me.|Ne izazivaj.
{62890}{62945}Znam ih te vrste.
{62946}{63000}Vraæaju jako.
{63059}{63154}Nešto mi smrdi.
{63226}{63278}Žalim, gðice Barstow,
{63279}{63333}ali moramo obaviti našu|opservaciju.
{63334}{63397}Vaša ekipa može|se vratiti sutra.
{63398}{63459}Naravno. Žao mi je|zbog Matta.
{63460}{63511}Samo je zabrinut|za nestale radnike.
{63512}{63599}Nikakva šteta nije|uèinjena. Uvjeravam vas.
{64279}{64378}Hvala vam, hvala vam|moj gospodaru.
{64379}{64431}Imaš èast.
{64432}{64482}Moj sin nije jeo veæ
{64483}{64593}dugo, dugo vremena.
{64594}{64642}Ne!
{64686}{64748}Ali izlijeèio si me.
{64810}{64844}Moj sin je lovac.
{64845}{64923}Ne bi pojeo|ranjeni plijen.
{64924}{65001}Mora ga|ubiti sam.
{65139}{65196}Shalom.
{65226}{65271}Žalim gospodine,|ne smijete unutra.
{65272}{65382}Oh, razumijem to,|pravila su tu s razlogom,
{65383}{65472}ali unutra sam|ostavio svojTallith.
{65480}{65518}Tallith...|je molitveni šal,
{65518}{65554}a rabin bez|molitvenog šala,
{65555}{65656}samo je èudak|s èudnom kapom, ne?
{65657}{65728}Oh, ali ne mislim da|mladog momka
{65729}{65789}sa kapom poput tvoje.
{65790}{65817}Lijepa kapa.
{65818}{65883}Hajde, obavite|to brzo.
{65884}{65925}Hvala ti.
{66366}{66482}Morao sam potvrditi ono|što sam vidio jutros.
{66482}{66515}Matthew je imao pravo.
{66516}{66571}Ove oznake su drugaèije.
{66572}{66621}Odreðuju toèno vrijeme
{66622}{66713}za ispunjenje proroèanstva.
{66772}{66870}"Kad èovjeèja ruka|otkrije Nephilime
{66870}{66923}"kada zemlja
{66924}{67022}"izazove|mjeseèevu pomrèinu,
{67023}{67077}"posrnuli anðeo
{67078}{67130}"koji je stvorio to stvorenje,
{67131}{67189}"æe se vratiti,
{67190}{67305}"a njegovo ime biti æe Ammon. "|Ammon.
{67337}{67405}Stvarno dobro|èitate, rabine.
{67462}{67521}Ne vjerujem da postoji više od|tuceta živih ljudi,
{67522}{67635}koji bi mogli proèitati|ovaj tekst.
{67698}{67761}To je ono što radim.
{67806}{67868}Raphael Ammon?
{67868}{67923}Dakle vi ste...
{67924}{67977}Upravo taj.
{67978}{68060}Ammon Uništitelj,
{68061}{68118}Abodan.
{68158}{68203}Anðeo smrti.
{68204}{68313}Da, znam tko|ste vi,
{68314}{68345}i da budem iskren,
{68346}{68416}to me strašno plaši.
{68417}{68476}Neæete osjetiti|niti malu bol.
{68502}{68574}Ubiti æete me?
{68606}{68631}Da.
{68632}{68758}Da li bi ispunili|zadnju želju?
{68766}{68857}Rabine, ako me želite moliti|da vas ne ubijem...
{68858}{68935}Oh, ne, nije to...
{68936}{69038}Mislio sam na to,|ali ipak ne.
{69083}{69169}Recite mi kako ste|upali u Njegovu nemilost.
{69227}{69296}Vi to ozbiljno?
{69321}{69433}Jer je Bog izabrao|vas umjesto nas.
{69454}{69508}Bio sam ponosan.
{69509}{69624}Zabranio je naše parenje|sa ljudskim kæerima.
{69642}{69705}Jedno, volio sam ženu,
{69706}{69831}Bog je uništio svijet poplavom,
{69832}{69905}ubijajuæi moju braæu|i naše potomstvo.
{69906}{70028}Ali vi ste sakrili|jednog od njih.
{70029}{70083}Èetvoricu smo pokopali,
{70084}{70185}na èetiri|strane svijeta,
{70186}{70287}izvan dosega Božjih|sljedbenika na Zemlji.
{70288}{70345}Kako ste preživjeli?
{70346}{70368}Otišao sam.
{70369}{70462}U paklu je postojalo|mjesto za mene,
{70463}{70555}tamnica u|srcu tame.
{71051}{71085}Kad sam se vratio,
{71086}{71153}želio sam osvetu.
{71154}{71239}Pronašao sam najgrešniji|grad u cijeloj zemlji
{71240}{71306}i spalio ga do temelja.
{71307}{71373}Sodoma.
{71374}{71433}A njegovi ljudi
{71434}{71511}nazvali su me|"Anðelom kazne"
{71566}{71602}U svojoj ljutnji,
{71603}{71649}pridobio sam kæer
{71650}{71728}jednog od njegovih|pravednika.
{71729}{71819}Zbog vas se prisjeæam|mnogo toga, rabine.
{71819}{71908}On je takoðer znao,|kako doprijeti do mene.
{71909}{72001}Ali njegova glupava|žena nije.
{72156}{72299}Skrivali su se u peæini|u vrijeme kad je Sodoma gorjela.
{72315}{72349}Nagovorio sam|njegovu kæer
{72350}{72465}da ga napije|i zatim spava s njim,
{72466}{72544}kako bi osigurala|nastavak obitelji.
{72563}{72641}Bog je mrzio incest.
{72658}{72770}Te noæi upoznao sam i njegovu|najmlaðu kæer, Rachel...
{72771}{72858}u biblijskom smislu.
{72859}{72941}Ali njen sin|bio je èovjek.
{72942}{73002}Proroèanstvo me trgnulo.
{73003}{73061}Nema više divova,
{73062}{73143}sve dok niste iskopali|mog sina.
{73144}{73201}Noæas...
{73202}{73278}spavati æu|sa Angelom
{73279}{73354}na nalazištu i|zaèeti æemo novoga.
{73354}{73387}Angela?
{73388}{73455}Zašto ne s nekom|kurvom u ulièici
{73456}{73514}ili s èasnom sestrom|u samostanu?
{73515}{73571}To je bila ona|prije 5000 godina
{73572}{73635}u peæini izvan Sodome
{73635}{73697}i biti æe ponovno ona, noæas.
{73743}{73791}Angela?
{73792}{73827}Rachel?
{73828}{73881}Njena duša?
{73882}{73933}Njezina bit.
{73934}{74004}Èovjeèanstvo æe|služiti mojoj djeci.
{74004}{74072}Kad nema reda,|dolazi kaos.
{74073}{74221}Iz kaosa smrt i|kraj èovjeèanstva.
{74298}{74329}Oh, oprostite mi.
{74330}{74392}Možda nisam|preveliki ekspert
{74393}{74444}da bih|razumio Knjigu Otkrivenja,
{74445}{74495}ali postoji uvriježeno mišljenje
{74496}{74576}da kršæani imaju|ponešto pravo
{74577}{74656}kad su predvidjeli naèin|na koji æe svijet završiti.
{74657}{74726}Tamo ne postoji ništa
{74727}{74806}što bi spominjalo vas.
{74849}{74928}Neæete uspjeti.
{74941}{75025}Ali moram pokušati, rabine.
{75026}{75085}Zbog toga postojim.
{75522}{75585}Fletcher. Ustaj.
{75605}{75680}Nisam znao|da si ti.
{75681}{75732}Svjetla su pogašena|posvuda u kampu.
{75733}{75782}Èak i prièuvni|generatori ne rade.
{75783}{75826}Znam. Nešto nije u|redu. Napunjena je.
{75827}{75903}Štogod da se dogaða,|nije normalno.
{75904}{75914}Da.
{75915}{75994}Zalijepi ovo trakom|za cijev puške.
{75995}{76090}Ako imamo sreæe,|baterije nisu pri kraju.
{76091}{76163}Moramo|pozvati policiju.
{76164}{76208}Veæ sam pokušao.
{76209}{76321}Telefoni ne rade. Pomrèina mora|da utjeèe na naš odašiljaè.
{76322}{76380}Radio veza|još uvijek radi.
{76426}{76445}Petak je naveèer.
{76446}{76538}Veæina ljudi je u gradu,|troše svoju tjednu plaæu.
{76539}{76669}Ostali su u|svojim prikolicama.
{76698}{76725}Spreman?
{76726}{76824}Da. Okej, idemo.
{76964}{76986}Što je s Angelom?
{76987}{77096}Biti æe dobro.|I njoj sam rekao istu stvar.
{77134}{77243}Njena prikolica vjerovatno|je najsigurnije mjesto gdje može biti.
{78092}{78135}Oprostite. Upravo sam|sam htio pokucati.
{78136}{78177}Uplašili ste me.
{78178}{78275}Želio sam provjeriti kako ste...|zbog nestanka struje.
{78276}{78340}Dobro sam.|Hvala vam.
{78341}{78407}Da li ste otkrili što|se dogodilo sa strujom?
{78408}{78474}Moji ljudi rade s vašima kako|bi otkrili što se dogodilo.
{78474}{78547}Ne bi trebalo još|dugo potrajati.
{78548}{78634}Mogu li uæi i provjeriti|vaš generator?
{78634}{78695}Ne radi.|Pokušala sam.
{78696}{78756}Ako nema ništa protiv...
{79082}{79144}Bojim se da|i dalje ne radi.
{79145}{79205}Kako išta možete vidjeti?
{79206}{79283}Imam nevjerovatan|noæni vid.
{79284}{79359}Proveo sam dugo|vremena u mraku.
{79360}{79383}Da.
{79384}{79428}Pa, hvala|što ste me posjetili.
{79429}{79516}Javim vam radijem|ako bude kakvih problema.
{79549}{79629}Veoma ste lijepi,|Angela.
{79833}{79878}Mislim da bi|trebali otiæi.
{79879}{79975}Uskoro æe mjeseèeva eklipsa.
{79976}{80028}Dopustite da vam|pokažem što je noæ.
{80671}{80802}To nije naèin na koji žena treba|postupati sa svojim novim suprugom.
{81202}{81265}Gdje su dovraga|Ammonovi ljudi?
{81266}{81359}Maloprije su bili ovdje.|Nisu me pustili unutra.
{81733}{81777}Eli...
{81778}{81843}zar nikada ne|prestaješ raditi?
{81878}{81929}Eli?
{81929}{81980}Eli.
{82102}{82179}Žao mi je, Matt.
{82180}{82262}Da ga nisam|doveo ovamo,
{82263}{82325}još uvijek bi bio živ.
{82325}{82386}Nisi ti kriv.
{82425}{82464}Sutra dovodimo|policiju,
{82465}{82560}FBI, cijelu prokletu|vojsku ako treba.
{82639}{82716}To je Elijev diktafon.
{82717}{82793}Još uvijek snima.
{82866}{82958}Ali moram pokušati, rabine.|Zbog toga sam...
{83008}{83056}Nije moguæe.
{83057}{83080}Ali je.
{83081}{83184}Divovske mumije,|posrnuli anðeli, sve to.
{83218}{83291}Oh, moj Bože, Angela.
{83442}{83479}Nije ovdje.
{83480}{83533}Ostavila je radio-vezu.
{83534}{83574}Njen konj je osedlan
{83575}{83634}kao da se spremala|otiæi na jahanje.
{83634}{83666}Pronaæi æemo je.
{83667}{83745}Pokušati æu pronaæi Gusa|i neke od momaka.
{83746}{83806}Naðemo se ovdje.
{83814}{83898}Ammon je rekao da mora izvesti|ritual za vrijeme pomrèine.
{83898}{83925}To nam daje|nešto vremena.
{83925}{83997}Pokušaj ne|uletjeti u nevolje.
{84041}{84097}Angela!
{84126}{84188}Angela!
{84327}{84451}Reci mi da ne vidim|ono što vidim.
{84555}{84580}Živa je.
{84581}{84678}To je samo kostur. Upravljaju|sa stvari koju obožavaju.
{85105}{85153}Mickey!
{85255}{85298}Doktore... Fletcher.
{85299}{85342}Još malo i slobodan si.
{85343}{85431}Gdje su ostali...|Joseph, Andy i Pete?
{85432}{85477}Žrtvovani su.
{85478}{85545}Kako to misliš?
{85546}{85612}Pojedeni su.
{85613}{85653}Hajde.
{85710}{85767}Da li je još koji od naših|ljudi na toj stvari?
{85768}{85836}Ne, ostali su svi|Ammonovi sljedbenici.
{85837}{85904}To je sve što sam|htio èuti. Ostani dolje.
{85905}{85952}Nema problema.
{86094}{86209}Hej, ovamo!
{86499}{86577}Hajde.
{86745}{86819}Hajde!
{87327}{87418}Fletcher, Mickey mi je|rekao što se dogodilo.
{87418}{87467}Vidim da si uspio|ne uletjeti u nevolje.
{87468}{87526}Nisam uspio pronaæi|Gusa ili ikoga drugog.
{87527}{87561}Moramo pronaæi Angelu.
{87562}{87625}Znam gdje je|Ammon drži.
{87626}{87681}Mogu vam pokazati.
{89225}{89267}Okej, vidiš ono?
{89268}{89325}Èini se kao kraj|peæine.
{89326}{89353}Ali to stijenje|je samo paravan.
{89353}{89441}Vadili su to stijenje|i vraæali ga na mjesto.
{89442}{89472}Vodi prema|nekoliko tunela.
{89473}{89553}Tako su uspjevali tako brzo|nestajati.
{89554}{89632}Rezervar vode je pola milje|iza tog brda.
{89633}{89740}Pravo je èudo da nismo otkrili ulaz|kad smo tamo dizali stvari u zrak.
{89785}{89870}Oh, ne...
{89870}{89924}Što je?
{89998}{90033}Trèite!
{90129}{90183}Na oružje!
{90184}{90226}Pogodio sam.
{90227}{90293}Da li si èuo|da je vrisnuo?
{90294}{90359}Mislim da si|ga još više raspizdio.
{90614}{90701}Da vidimo kako æe trèati|kad mu raznesem prokletu nogu.
{90794}{90838}To još nije ništa.|Èuo sam kako govore.
{90839}{90933}Neæe biti u punoj snazi sve dok|Ammon ne završi ritual.
{90934}{90955}Mickey ima pravo.
{90956}{91012}Mumija æe biti|sve snažnija.
{91013}{91097}Ammon je onaj,|koga trebamo zaustaviti.
{91137}{91169}Još uvijek nas|pokušava uhvatiti,
{91170}{91245}pa æu ja nastaviti pucati,|ako se slažeš s time.
{91246}{91271}Okej.
{91272}{91296}Kamo je nestao?|did he go?
{91297}{91442}Kako misliš, gdje je nestao? On|je mumija od 42 stope!
{92137}{92195}Takvi momci ne odustaju.
{92196}{92309}Hej, tamo je Josephova|prikolica. Imam ideju.
{93302}{93371}Mislio bi da æe|kurvin sin
{93372}{93468}ostaviti rezervne kljuèeve|prije nego ode.
{93469}{93528}Hej, pazi gdje voziš!
{93529}{93587}Svjetla su ti ugašena, idiote!
{94166}{94225}Jerry.
{94226}{94288}To je moj momak.
{95350}{95406}Jerry.
{96314}{96397}Hej, ovamo.
{96398}{96442}Da, ovamo.
{96965}{97017}Ne mogu vjerovati.
{97018}{97095}Znam da to postoji|u crtiæima, ali èovjeèe...!
{97285}{97352}Rekao bih da je|bilo jako blizu.
{97353}{97419}Ne znam. Yosemite|Sam uvijek ima prièuvni plan.
{97420}{97441}Bio si dobar.
{97441}{97539}Sjetio sam se da je Joseph imao|dinamit u prikolici, pa sam ga uzeo.
{97540}{97606}Kad si izletio iz|te prikolice
{97607}{97648}mašuæi sa tim|dinamitom...
{97649}{97682}Mislio sam da æeš|nas sve raznijeti.
{97683}{97764}Nisam o tome niti razmišljao.|Ne bi li to bilo super?
{97765}{97792}Momci!
{97793}{97849}Što je, Mickey?
{97849}{97904}Što to rade?
{98199}{98293}Ja jedini još|nisam upucao nikoga.
{98377}{98445}Nemaš više metaka!
{98509}{98587}Daj mi je.
{99405}{99485}Moraš nauèiti novi|naèin borbe.
{99486}{99540}Sad mi kažeš.
{99810}{99902}Prestani se zezati|s tom stvari.
{99903}{100033}Ne zezam se.
{100069}{100120}Lijepa vožnja.
{100121}{100168}Upadaj.
{100711}{100744}Uskoro, imati æeš
{100745}{100816}posebno mjesto u|svijetu, Rachel.
{100817}{100853}Ja nisam Rachel.
{100854}{100913}Bila si...
{100914}{100973}prije mnogo godina.
{100974}{101012}Natjerana da mi|rodiš ljudskog sina.
{101013}{101159}Zbog toga postoje ciklusi...|da bi dobila drugu šansu.
{101160}{101213}Ne možeš.
{101213}{101276}Kada sve bude gotovo,
{101277}{101359}svega æeš|se sjetiti.
{101360}{101442}I ponovno æemo|biti zajedno.
{101493}{101577}Ne smijemo dopustiti|da uništiš ovaj trenutak.
{101620}{101690}Zar ne?
{101841}{101929}Dobro,|izvuæi æemo Angelu
{101930}{101974}i zatim dignuti|tunel u zrak.
{101975}{102015}Ovdje imam dovoljno|eksploziva
{102016}{102113}da urušim sve|Ammonu preko ušiju.
{102114}{102167}Èekaj, neæe uspjeti.
{102168}{102210}Ono što je|rekao Eliju.
{102211}{102313}Samo æe ga velika|poplava uništiti.
{102314}{102365}Jezero.
{102365}{102437}Ako dignemo u zrak|vrh brane,
{102438}{102509}cijela konstrukcija|æe se srušiti.
{102510}{102553}Ja æu je srušiti.
{102554}{102603}Poplaviti æe tunele.
{102604}{102640}Nakon što izvuæemo Angelu.
{102641}{102681}Dobro si odigrao ono|sa onim divom.
{102682}{102805}Ali ovdje nam treba netko tko|zna postaviti eksploziv i tajmer.
{102806}{102869}Ja æu.
{102905}{102969}Vrijeme istièe, momci.
{103032}{103084}Charles.
{103093}{103211}Što ako je ne izvuèem|prije nego potopiš tunele?
{103257}{103313}Ako je u nesvijesti...
{103346}{103427}Nitko nije mogao spasiti|te ljude u Meksiku, Matt.
{103428}{103477}Sve æe biti u redu.
{103477}{103582}Javi mi radijem kad|izvuèeš Angelu odande.
{103981}{104039}Zgodno, ne?
{104040}{104073}Koliko još?
{104074}{104173}Ne znam. Veæinu puta|bio sam drogiran.
{104174}{104234}Mislim da smo blizu.
{104873}{104950}Noæas ne možeš|ništa više promijeniti.
{105020}{105077}Moram pokušati.
{105141}{105185}Znam.
{105193}{105227}Okej, ne daj da te dodirne.
{105228}{105261}Èuo sam njegove|sveæenike kako govore...
{105261}{105363}Sve dok pomrèina nije gotova,|ne može ti ništa ako te ne dotakne.
{105364}{105446}Trebao sam s tobom|nahraniti sina.
{106401}{106517}Fletcher,|kod rezervara sam.
{106801}{106925}Biti æe|prelijepa majka.
{106926}{106978}Ne misliš li tako?
{106979}{107029}Nikad se ne zna.
{107029}{107101}Uporan si.
{107102}{107148}Priznajem.
{107149}{107238}Mislio sam da|si jednostavno glup.
{107239}{107295}Oh, i to sam.
{107296}{107350}Možeš u pakao.
{107351}{107445}Ne, hvala,|bio sam tamo.
{107974}{108032}Mickey, pazi.
{109249}{109320}Hej, ukrao si|našu opremu.
{110781}{110863}Trebao si poslušati|svog prijatelja rabina,
{110864}{110945}kad ti je rekao da me|ne izazivaš, mali èovjeèe.
{111014}{111143}Spaliti æu ti|dušu... polako.
{111259}{111343}Želio sam te ostaviti|za poslije,
{111344}{111426}ali dosta mi je|igranja s tobom.
{111471}{111567}Znao si da te|ne smijem dotaknuti.
{111760}{111841}Mickey, moraš ustati.
{112277}{112305}Matt.
{112305}{112363}Dobro si? Možeš|li hodati?
{112364}{112424}Da. Trèi.
{113581}{113649}Sada, Charles,|raznesi branu.
{113728}{113787}Charles, èuješ li me?
{113787}{113845}Raznesi branu.|Hajde, kreæi.
{114286}{114394}Charles, raznesi branu,|Angela je spašena.
{114737}{114793}Oh, ne...
{114794}{114844}Nastavi hodati.
{115333}{115441}Hajde.
{115442}{115478}Hajde!
{115584}{115665}Ne, što to radiš?|Umrijeti æeš.
{117145}{117221}Nema puno toga što|još moramo uraditi ovdje.
{117221}{117312}Ako vam što zatreba,|nazovite nas.
{117313}{117344}Èuvajte se.
{117345}{117417}Slijedimo tog Ammona|i njegove ljude.
{117418}{117475}Ali èini mi se|dosta oèito.
{117476}{117505}Doista?
{117506}{117553}Pa, postojalo je nekoliko|tvrtki
{117553}{117613}koje bi izvukle korist iz toga|da ovaj projekt propadne.
{117614}{117673}Pretpostavljam da je jedna od njih|unajmila Ammona
{117674}{117721}da uzdrma posao,|poplavi zemljište.
{117722}{117769}Možda su bili neki|aktivisti za zaštitu prirode.
{117770}{117817}U Washingtonu...
{117818}{117866}je prošle godine jedan|uništio tri konstrukcije.
{117867}{117923}Rekao je da je|štitio sove.
{117924}{117951}Nisam se|toga dosjetila.
{117952}{118035}Iznenadili bi se kakve se lude|stvari dogaðaju u svijetu.
{118036}{118118}Raditi æemo ovdje nekoliko dana|s vašim ljudima
{118119}{118194}da ih sve ispitamo.|Pokušajte se odmoriti.
{118195}{118254}Okej, hvala.
{118576}{118684}Razraðujem teoriju|o aktivistima za zaštitu prirode.
{118710}{118813}Razmišljala sam samo o tome|da im se ne poènem smijati u lice.
{118814}{118843}Razgovarao si s Gusom?
{118844}{118885}Da, kaže da je sinoæ
{118886}{118943}bila ekipa koja je|poèistila sve.
{118944}{118991}Pretpostavljam,|Ammonovi sljedbenici.
{118992}{119021}Kako to misliš?
{119021}{119134}Kao prvo, nema više dokaza da je|poludjela divovska mumija
{119135}{119191}rasturila cijeli logor.
{119192}{119226}Nestala je.
{119227}{119259}A s njom i|mali ljudi.
{119260}{119350}Ostala šteta se èini kao da je|od pada helikoptera,
{119351}{119444}a tu nesreæu su veæ objasnili|kao posljedicu pomraèenja.
{119474}{119521}Što je sa peæinama?
{119521}{119617}U njima je trenutno nekoliko|milijuna galona vode,
{119618}{119695}ukljuèujuæi onu u kojoj smo|pronašli i mumiju.
{119696}{119751}Cijelo nalazište je|pod vodom.
{119805}{119868}To je previše.
{119958}{120002}Hej.
{120003}{120046}Hej.
{120144}{120217}Nisam znao da se|poznajete tako dugo.
{120218}{120336}Gotovo od dana|kad sam se rodila.
{120385}{120426}On mi je bio otac.
{120427}{120506}Zašto nikad nije|ništa rekao?
{120557}{120623}Jer sam mu rekla|da ne kaže.
{120646}{120702}Jer sam željela da sve|odradim sama.
{120703}{120779}Ne kao šefova kæer.
{120804}{120895}Barstow je djevojaèko|prezime moje majke.
{120920}{120965}Gus je znao...
{120966}{121021}i još nekolicina momaka.
{121022}{121064}Žao mi je.
{121065}{121105}Neka ti ne bude.
{121105}{121206}Tata je znao|što radi.
{121252}{121289}Oduvijek je znao.
{121290}{121370}Kad bih znala|da æe to vratiti njega
{121371}{121404}ili nekoga od ostalih,
{121405}{121509}rekla bih policiji sve|što znam.
{121510}{121552}Znam.
{121601}{121661}Kad bi im rekli|pravu istinu,
{121662}{121722}završili bi noseæi iste|bijele luðaèke košulje.
{121751}{121812}Hajdemo na zrak.
{122008}{122149}Trebati æe mi bar godinu dana|da napravim branu kakva je bila.
{122149}{122205}Ponovno æeš je izgraditi?
{122296}{122349}Što æeš ti?
{122350}{122401}Razmišljao sam.
{122402}{122503}Ammon je rekao da|su zakopali 4 diva u zemlju,
{122504}{122585}svakog na drugom|kraju svijeta.
{122589}{122707}Uèenjaci se prepiru oko toga|gdje bi ta mjesta bila.
{122730}{122791}Pokušao bih ih pronaæi.
{122817}{122853}Èini se kao puno posla.
{122853}{122983}Trebamo ih pronaæi i uništiti|prije nego to uèini netko drugi.
{123019}{123060}Kad mi momak želio
{123061}{123160}da ih pronaðe|i uništi,
{123161}{123246}trebao bi i|dosta dobrog...
{123247}{123314}inžinjera koji bi|radio s njim.
{123315}{123382}Gus bi ovdje|mogao odraditi posao.
{123383}{123450}Èini se kao opasan posao.
{123469}{123569}Ne želim da radiš išta|što ne želiš raditi.
{123570}{123637}Ne kažem da|ne želim.
{123667}{123713}Samo kažem
{123714}{123813}da bi trebali|popiti par piva
{123814}{123872}i zaplesati malo,
{123873}{123945}èisto da malo|pokrenemo stvari.
{124400}{124520}GODINU DANA POSLIJE
{125000}{125999}Prijevod i obrada :|ToNY_VT
{126000}{126001}
