{129}{232}"Idemo naæi Hu Yang stabla,|a buduæi da ti je sudbina"
{236}{368}"vezana za srce, pomoæi æeš|mi. - Neæu! - Ja mislim da hoæeš."
{880}{964}Smrt. Baš prikladno.
{1444}{1528}Oprostite! Isprièavam se!
{1585}{1717}Ovo me ubija. Gdje se može|pojesti hamburger ovdje?
{1868}{1952}"Zdravo, Bobe."
{2017}{2147}"Daj, Bobe, znaš da znam da|znaš da æeš progovoriti. - Ha?"
{2256}{2342}Zaboravimo... - Kako to misliš?
{2357}{2460}Zna gdje su djeca.|- Šališ se. Pogledaj da.
{2464}{2545}Bi li mu ti išta rekla?
{2572}{2653}Ne bih.
{2668}{2784}Vidi se koliko vi znate! Sve|znam! Dobio sam važan posao!
{2790}{2892}Trebao sam paziti na vas dok|Karl ne otkrije što zna starac
{2897}{2982}kojega je našao Tong.
{3822}{3907}Ima li koga?
{4241}{4331}Karl je bio tu.
{5152}{5211}Yin!
{5215}{5321}Èekaj! Ne možeš iæi|po ovakvom vremenu!
{5327}{5451}Ne možeš iæi sama protiv|Karla! - Ne! Moram naæi Tonga!
{5522}{5620}Znam da si zabrinuta!|I naæi æemo ga!
{5624}{5743}"Ma gdje god bili, ostat æe|ondje dok oluja ne proðe! - Ne!"
{5855}{5931}Slušaj me! Slušaj...
{5936}{6069}"Lily i Tong vrijede puno Karlu!|Vjeruj mi, neæe im nauditi!"
{6084}{6173}Neæe im nauditi! Vjeruj mi...
{6569}{6687}Vrijeme se urotilo protiv nas.|Moramo èekati još jednu noæ.
{6693}{6819}"Nažalost, vremenske prilike|ne mogu kontrolirati. Još."
{6928}{7006}Nisam gladna.
{7014}{7121}Mislim da oboje znamo|da to i nije baš istina.
{7127}{7256}"Niste jeli od doruèka. Dajte,|mušice, morate pojesti nešto."
{7352}{7416}Tako...
{7428}{7550}To je bolje. Glupo|je da se svaðamo.
{7599}{7698}Trebam tvoju pomoæ. - S èime?
{7719}{7838}Mislim da srce Dun|Huanga nije samo legenda.
{7845}{7942}Kao ni uloga tvoje|obitelji u svemu tome.
{7946}{8060}"Ja nisam taj. - Ne? Ja mislim|da želiš to uèiniti, Tong."
{8065}{8168}Mislim da si proveo|život u sjeni Yin.
{8172}{8296}Ljubomorni mlaði brat. Nikoga|nije zanimalo što misliš. Istina?
{8313}{8369}Razmisli...
{8373}{8456}Mogao bi postati legenda.
{8466}{8598}Idi kvragu! - U redu.|Prelazimo onda na plan B.
{8619}{8746}Nasilje. - Ne bojim se tvojih|prijetnji. - Ja ne prijetim.
{8772}{8892}Ja kažem i onda to i uèinim. I|kažem da bi mi trebao pomoæi.
{8903}{8980}Pogledaj te momke.
{8985}{9063}Brutalni degenerici.
{9067}{9195}Bilo bi grozno pustiti ih na|jednu noæ s tvojom prijateljicom.
{11701}{11785}Dopusti meni...
{12386}{12482}Oprosti. - U redu je.
{13800}{13849}Evo...
{13875}{13980}Laku noæ. - Laku noæ.
{14801}{14876}Ne mogu.
{14880}{15007}U redu je. - Oprosti što|sam te uvukao u ovo.
{15029}{15149}"Bila bih radije|tu s tobom, ovako,"
{15173}{15260}nego igdje drugdje na svijetu.
{15967}{16068}Sada si ti glava obitelji.
{16110}{16270}"Tata... - Za dodir ne samo|da moraš biti spretan,"
{16312}{16396}veæ moraš i vjerovati.
{16407}{16511}"Yin, vjeruješ li?"
{16553}{16681}"Naravno da vjerujem,|tata. Naravno da vjerujem."
{16731}{16837}Bez smrti nema života.
{16858}{16991}Smrt je samo|korak do novog života.
{17489}{17584}Bez smrti nema života.
{19273}{19385}Nisam mislio|da æe ih toliko biti.
{19402}{19482}Pokušat æu.
{19782}{19866}Našli smo nešto.
{20009}{20066}Oprezno.
{20309}{20428}Mislim da bih uspio.|- Nikad neæeš proæi tuda.
{20851}{20906}Yin!
{20910}{20997}"Yin, jesi li dobro?! - Jesam!"
{21009}{21093}S druge strane zida si!
{21155}{21241}Iskopat æu prolaz do tebe!
{21447}{21530}"Što æete uèiniti, šefe?"
{21723}{21845}Ono što i uvijek. Pustit|æu Erica da mi to naðe.
{23026}{23152}"Yin, tu si? - Našla sam nešto."
{23180}{23272}Što? - Posudu.
{23395}{23513}Srce ne kuca bez krvi|makar bilo i od kamena.
{23531}{23692}Odnesi srce Svetom èovjeku i|ispuni mu vene krvlju Dun Huanga.
{23735}{23826}"Eric, evo ti prvo ova posauda."
{23858}{23944}Evo ti je. Oprezno.
{23978}{24095}Sveti èovjek je nekakva|formacija stijena na planini.
{24102}{24289}Ovo je pustinja|Yadan. Tamo idemo.
{24383}{24432}Eric? Eric?
{24437}{24501}"Hvala, Yin, baš si ljubazna."
{24505}{24607}"Kako da se oprostimo nakon|svega što smo prošli, Yin?"
{24612}{24698}Ovako. Zbogom.
{25310}{25402}"Žao mi je, stari."
{25410}{25502}"Moglo je biti zabavno, Eric."
{25567}{25651}Završimo s ovim.
{25953}{26042}Što se dogaða? - Ulazi! - Unutra!
{27449}{27535}Uvijek mi se sviðala.
{27599}{27659}Yin?
{27664}{27725}Yin?
{27767}{27840}"O, Bože!"
{27844}{27930}Yin?! Yin?
{28003}{28090}"Reci nešto, Yin!"
{28163}{28248}"Zaboga, reci nešto!"
{28253}{28338}Daj mi nekakav znak!
{28392}{28501}Nikada te više neæu|ostaviti! Obeæavam!
{28506}{28651}Prestat æu krasti! Sve|æu uèiniti! Sve što želiš!
{28666}{28748}"Molim te, nemoj umrijeti!"
{28849}{28907}Yin!
{28912}{28991}"Diši, Yin!"
{28995}{29072}Imam te!
{29361}{29452}Uèinit æeš sve što želim?
{30668}{30752}Pogledaj ono.
{30893}{30976}Zamke. - Da.
{31004}{31083}Karl æe upasti u veliku zamku.
{31100}{31183}I vodi Tonga sa sobom.
{31762}{31822}Sranje.
{31942}{32028}Morat æemo iæi okolo.
{32324}{32431}"Èekaj malo,|Yin, razmotrimo ovo..."
{32447}{32509}Ne...
{32537}{32617}"Èekaj malo, Yin!"
{32621}{32678}Ne...
{32708}{32765}Ne!
{32950}{33059}Nije bilo tako loše|kako je izgledalo.
{33421}{33480}Stani!
{33795}{33879}Sveti èovjek.
{35626}{35687}Napokon.
{37224}{37309}Upamti da Lily raèuna na tebe.
{38830}{38952}Èarolija... - Ne. Znanost.
{38991}{39095}Fosfor mi osvjetljava put.
{39946}{40024}Uæi znaèi birati.
{40028}{40117}Birati znaèi biti izabran.
{40146}{40225}Sudbina èeka.
{40248}{40361}"Èuješ li, Tong. Sudbina èeka."
{40428}{40487}Tong!
{40563}{40694}Neki ljudi jednostavno ne žele|umrijeti! - Opet sam ti na putu?
{40701}{40790}Tako je. Posljednji put.
{40794}{40893}"Karl, slušaj me,|ovdje je sve puno zamki."
{40897}{40983}"Zašto da ti vjerujem, Eric?"
{41039}{41129}Eto zašto.
{44335}{44419}Vidi tko je došao.
{45528}{45590}Tong!
{46100}{46224}Imao sam pravo. Ne znaš|ni udariti kako treba. Priznaj!
{46296}{46370}Mislio si da æu pasti na to?
{46533}{46613}Mogao si.
{48073}{48191}Što je to što nemaš? Reci.|Što misliš da æeš dobiti?
{48236}{48319}Kad je èovjeku poput tebe dosta?
{48375}{48431}Nikada.
{48449}{48565}Ne shvaæaš što je Sharira|zapravo. I nikada neæeš.
{48575}{48726}Želiš je za sebe. - Zar ne|razumiješ? Ne može se uzeti.
{48742}{48803}Neæe ti dopustiti da je uzmeš.
{49015}{49138}Pogledaj oko sebe.|Èak je i Zemlja protiv tebe.
{49890}{49977}"Ne poduzimaj ništa, Tong."
{50101}{50160}Eric!
{51361}{51425}Lily!
{51653}{51739}Drži se!
{52729}{52815}Sudbina èeka.
{53967}{54049}Bolje da krenemo.
{55077}{55165}Kako æemo prijeæi?
{55395}{55517}Ne. Predaleko je.|Umrijet æeš pokušaš li.
{55522}{55647}Umrijet æemo|ostanemo li tu. Uspjet æu.
{55683}{55801}Ali trebam tvoju pomoæ.|- Zašto misliš da æeš uspjeti?
{55821}{55906}Zato što vjerujem.
{57954}{58053}"Èuj, Tong, ima li koji drugi|naèin da prijeðemo... - Tong!"
{58057}{58167}...a da to ne zahtijeva|tisuæljetnu obuku. - Skaèi!
{59197}{59256}Sharira.
{62420}{62526}"Ispunila si svoju|sudbinu, dijete."
{62532}{62638}"Hvala, uèitelju. - Ono što|je bilo izgubljeno, naðeno je."
{62642}{62740}"Ono što je naðeno, nikada nije|bilo izgubljeno. Sve što postoji,"
{62746}{62840}u ravnoteži je. - Došao|je kraj. Ponovo poèinje.
{63340}{63470}"Majmuni veæ imaju|svoje mjesto, sine."
{64273}{64350}Odluèio sam.
{64867}{64984}Siguran si? - Jesam.|- Dobar si. Jako si dobar.
{65019}{65106}Hvala. - Nema na èemu.
{65349}{65454}Zabrinuta si za njega.|- Tong je dovoljno odrastao
{65458}{65605}"da sam odluèuje. - Znam, ali...|Ne mogu vjerovati, odrastao je."
{65686}{65790}Ovo je dobro|mjesto za njega. - Jest.
{65795}{65906}"Onda, spreman|si iæi kuæi? - Kuæi?"
{65916}{66025}"Ja? Misliš, nakon|svega što sam uèinio,"
{66038}{66160}smijem se vratiti kuæi?|- Samo ako ti to želiš.
{66694}{66785}Što je ovo? - Koje? - Ovo.
{66812}{66926}"Ah, to... Našao sam|to neki dan na tržnici."
{66933}{67040}Taj mali èovjek... Bio je|jako malen... Prodao mi je to
{67044}{67167}"i rekao... Vjerojatno nije ništa,|ali rekao je da... - Neæe moæi."
{67204}{67280}Imaš pravo.
{67298}{67382}No možda bismo mogli pogledati.
{67409}{67517}Ne. Loša ideja. - Daj!|Provjerit æemo na putu kuæi.
{67521}{67665}Daj mi to. Ne...|Daj mi... Daj mi to!
{67670}{68670}{C:$0000FF}{y:ib} B & M |{C:$FF0000}{y:b} movies 
{68827}{68987}Obrada:|VTI
