{1}{1}25.000
{227}{260}Ako ovo ponovite, 
{274}{307}poreæi æu.
{327}{450}Kao što sam uvijek poricao. I|uvijek æu poricati. Do smrti.
{529}{558}Razumijete li?
{691}{797}ŠOKANTNO PRIZNANJE
{1886}{1937}ZABRANJEN LOV
{2330}{2480}{C:$0000FF}{y:ib} d |{C:$FF0000}{y:b} d  
{2571}{2633}Zdravo, prvaèe! Kako ide?
{2682}{2730}Idemo. Požuri se. Kasnimo.
{2743}{2767}Ne idem.
{2967}{3026}Kako to misliš?|- Jednostavno ne želim iæi.
{3074}{3134}Kyle? Kyle, pogledaj me.
{3175}{3225}Danas je premijera.|Tvoja sestra raèuna na tebe.
{3233}{3270}Preboljet æe me.
{3280}{3352}Vrlo si bezobziran. - Zašto?|Jer želim ostati doma?
{3355}{3447}Da, zato što želiš ostati|doma. - To želim! Ostati doma!
{3860}{3952}Na sušilici je èista majica,|Kyle. Uz kaki hlaèe. Kyle?
{3987}{4014}Kyle?
{4113}{4160}Nemoj mi reæi. - On ne ide.
{4174}{4223}Što je sada? - Što je uvijek?
{4342}{4413}Harry kaže da ga ne|prisiljavamo, pa i neæemo.
{4423}{4498}A zna li Harry što bismo|trebali reæi Shelly?
{4502}{4542}Reæi mi o èemu?
{4688}{4737}Pravo si govno, znaš?
{4746}{4812}Jednostavno mi se veèeras|ne da biti s ljudima.
{4819}{4866}To èesto govoriš.
{4908}{4969}Nije kao da to|neæeš još raditi.
{5135}{5168}Sutra?
{5201}{5241}Doæi æeš?
{5334}{5396}Jednostavno veèeras|slomi nogu.
{5398}{5435}Hoæu.
{5552}{5599}Jesi li dobro?
{5621}{5661}Jesam.
{5812}{5869}Predstava ide dalje,|gðice Streisand.
{5909}{5954}Hajde. Limuzina èeka.
{5975}{6023}Vidimo se. - Sretno.
{6265}{6324}Saèuvat æu ti sjedalo|ako se predomisliš.
{6375}{6395}Da.
{6402}{6445}Ima li izgleda za to?
{6487}{6520}Ne.
{6714}{6755}Volim te, partneru...
{6824}{6861}Vidimo se.
{7297}{7347}Ne postoji ništa
{7358}{7486}Što mogu reæi ili uèiniti
{7563}{7718}Što ljudi neæe kritizirati
{7817}{7867}No ipak æu
{7881}{8002}raditi ono što želim
{8080}{8179}I baš me briga ako me i svi
{8190}{8276}preziru
{8337}{8401}Ako mi doðe
{8406}{8562}da skoèim u more
{8588}{8723}To je samo moja stvar
{8807}{8911}Ako poðem u crkvu u nedjelju
{8930}{9039}A zatim sam u kabaretu|cijeli ponedjeljak
{9047}{9177}To je samo moja stvar
{10443}{10570}To je samo moja stvar
{11123}{11144}Divno.
{11148}{11170}Hvala.
{11623}{11648}Pazi.
{11657}{11685}Dobro.
{11698}{11793}Polako. Pazite kamo stajete.|Oprezno, dušo.
{12404}{12432}Sranje!
{12654}{12701}Mama? Gdje je Kyle?
{12756}{12783}Kyle?
{12804}{12841}Gdje si?
{12911}{12966}Kyle! Kyle! Ne!
{13103}{13126}Ne!
{13284}{13321}Kyle!
{13945}{14022}Hajde! Idemo!|Probudi se! Probudi se!
{14027}{14071}Mama! - Michaele!
{14075}{14140}Tata, što je? - Zovi Hitnu!
{14270}{14344}Bože! - Uzmi telefon|i zovi 911. Brzo!
{14381}{14451}Probudi se, Kyle! Hajde, sine.
{14456}{14537}Molim te! Kyle, molim te. Daj.
{14568}{14608}Ne!
{14609}{14675}Molim te, molim te!
{14706}{14822}Molim te! Nemoj,|Bože! Bože, nemoj!
{15393}{15422}Tri godine poslije
{15425}{15520}Današnji gost je bivša|zvijezda ovog sveuèilišta,
{15523}{15591}odjela psihologije. Uèitelj.
{15608}{15729}Lijeènik. Autor. Te rijeèi|samo poèinju opisivati
{15734}{15793}njegov doprinos polju.
{15797}{15866}Trebalo ga je|nagovarati da doðe,
{15871}{15934}no znam da æete mu|poželjeti dobrodošlicu.
{15937}{16040}K.S. -ov razmetni sin.|Dr. Michael Hunter.
{16441}{16566}Zamislite da ste djeca. I da|ste ovamo dovedeni da nauèite
{16569}{16705}što je kreda. Zamislimo|da vam kažem sve o kredi,
{16729}{16846}ali vas istodobno|tuèem. Tuèem vas
{16883}{17001}ovim pokazivaèem. Neki od|vas bi mogli uživati u tome.
{17021}{17146}Sada više niste dijete, ali|nosite sa sobom podsvjesne
{17155}{17217}podražaje na strah.
{17222}{17335}Duboko ste zakopali|te batine u podsvijest.
{17339}{17408}Promijenili ste istinu u...
{17453}{17507}U prihvatljivu laž
{17519}{17601}koja vam dopušta da|funkcionirate u društvu.
{17614}{17656}Trebam dobrovoljca.
{17670}{17720}Ova mlada dama æe biti dobra.
{17728}{17785}Kao terapeut želite|da vam pacijent
{17788}{17861}jednostavno kaže|izvor svojega bola,
{17865}{17954}ali onda ta osoba ne bi|trebala psihijatra. Stoga...
{17986}{18060}jednostavno pitamo,|a pacijentica odgovara,
{18064}{18200}no èesto je ono što nije|reèeno važnije od reèenoga.
{18218}{18302}Pokušat æemo s jednostavnom|asocijacijom rijeèi.
{18401}{18429}Dobro si? - Aha.
{18454}{18498}Drvo. - Jako.
{18513}{18550}Ljubav. - Dobro.
{18563}{18601}Mama. - Pjevanje.
{18640}{18666}Tata.
{18684}{18716}Odijelo.
{18785}{18833}Deèko. - Visok.
{18873}{18920}Znaèi da ja otpadam.
{18965}{19014}Vrlo dobro. Kako|ti je ime? - Gina.
{19025}{19076}Gina. To je bilo lijepo.|Studentica si?
{19079}{19135}Bit æu psihijatrica poput vas.
{19146}{19189}Moja suæut.
{19214}{19274}Što tvoji roditelji|misle o tome?
{19278}{19319}Mama misli da sam luda.
{19323}{19370}A tata?
{19439}{19531}On nije baš|najsretniji, je li?
{19569}{19671}Malo toga bi ga moglo|usreæiti kad nije na poslu?
{19716}{19759}Kad je kod kuæe?
{19807}{19851}S tobom?
{20127}{20198}Dobro si? U izmjenjivanju|rijeèi s Ginom,
{20202}{20296}promatrao sam mišiæe na|njezinom licu. Položaj oèiju,
{20315}{20452}ritam njezinog disanja. To su|sve pokazatelji podsvijesti.
{20466}{20524}Do nereèenoga.
{20528}{20673}I napetost izmeðu oca|i kæeri je èesta pojava.
{20735}{20797}Gospodine? Moj rad? Kratak je.
{20801}{20854}Jedva imam vremena|pisati, a kamoli èitati.
{20860}{20957}Dr. Huntere, zakasnit æete.|Oprostite svi. Hvala vam.
{21067}{21143}Barbara Lonigan. - Vrlo dobro.
{21157}{21203}To je bilo sjajno. - Hvala.
{21214}{21247}Odrasla si.
{21253}{21360}Sada radim za Djeèju skrb.|Radim na svom doktoratu.
{21386}{21422}Kao što sam i oèekivao.
{21449}{21485}To je naporan posao.
{21489}{21566}27 sluèajeva.|Ništa prezahtjevno.
{21579}{21713}No imam jedno dijete o kojemu|želim razgovarati s vama.
{21715}{21757}Barbara...
{21774}{21839}Više ne radim s|pacijentima. - Znam to.
{21849}{21923}Ne mogu vam reæi koliko|mi je žao zbog vašeg sina.
{21964}{22000}U redu je.
{22011}{22092}Ne želim se nametati,|no ovo je neobièan sluèaj.
{22099}{22171}Prije 4 g. Našao je|svoju majku mrtvu kod kuæe.
{22175}{22232}Otac ju je pretukao nasmrt.|Dobio je doživotni zatvor,
{22236}{22320}a Tommy je završio u stambenom|programu u Holly Hillsu.
{22321}{22414}Za šest mjeseci æe napuniti|18 g. I bit æe otpušten.
{22420}{22483}Misliš da nije spreman?|- Da. Mislim.
{22491}{22560}Post-traumatski stres? - Svaki|socijalni radnik kaže isto.
{22564}{22608}Ništa ne utjeèe na njega.
{22612}{22686}On je dobar deèko. Nema|abnormalnih znakova ponašanja,
{22689}{22755}nema reaktivnih simptoma.|- Duboka depresija.
{22758}{22795}Da, znam da tu ima neèega.
{22800}{22873}Ako bi mu mogli posvetiti|jedan sat... - Molim te...
{22892}{22936}Nije problem u vremenu|nego u predanosti.
{22939}{22992}Ti je oèito imaš.|A ja ne. Ne više.
{22995}{23068}No ako skriva reaktivne|emocije, vi biste ih vidjeli.
{23072}{23145}Molim te, shvati. Ja pišem|knjige. Održavam predavanja.
{23165}{23229}To sada radim. Žao mi je.
{23299}{23369}Hoæete li bar pogledati|sažetak Tommyjeva spisa?
{23396}{23485}Kad budete imali vremena.|Svi moji brojevi su tu.
{23495}{23531}Cijenila bih to.
{23796}{23856}Lijepo je vidjeti te.|- I vas. Èuvajte se.
{26298}{26335}Nema me. Ostavite poruku.
{26339}{26387}Zdravo, tata! Shelly je.|Jesi li tamo?
{26427}{26444}Shelly?
{26455}{26509}Nedostajala si mi|prošli tjedan.
{26512}{26575}Da, znam. Ali slušaj,|upravo mi se pokvario auto.
{26579}{26659}Tvoj auto? Dobro si?|- Jesam. Ništa strašno.
{26663}{26711}Troy ima prijatelja|koji æe mi ga odvuæi.
{26714}{26760}Tko je Troy?|- Laurin prijatelj.
{26764}{26813}Tko je Laura?|- Shelly, ubila si ga.
{26817}{26874}Smiri se. Zovem tatu.
{26877}{26918}Shelly? Gdje si?|Dolazim po tebe.
{26924}{26968}Ne! Tata, dobro sam.
{26972}{27034}Samo trebam posuditi auto|za školu sutra. Mogu li?
{27036}{27073}Da. Gdje si? Dolazim po tebe.
{27077}{27116}Vidimo se sutra.|- Shelly, slušaj me!
{27120}{27152}Dobro, bog.
{28151}{28209}Uglavnom si rasturio|na polugodištu.
{28213}{28274}Sigurno se dobro osjeæaš.|- Da. Prilièno dobro.
{28278}{28386}Razmišljaš o prijamnima?|- Ne znam je li koledž za mene.
{28433}{28517}Zašto ovo snimamo?|- Radim to jednom na mjesec.
{28526}{28614}Da snimim tvoj napredak.|- Osjeæam se kao zamorac.
{28624}{28673}To mi nije namjera, Tommy.
{28676}{28817}Ali tako je. Neugodno mi je.|Možete li je iskljuèiti?
{29321}{29343}Hvala, tata.
{29715}{29763}Izuzetno sam zahvalna|za ovo, dr. Huntere.
{29767}{29832}Bila sam uvjerena|da sam vas izgubila.
{29839}{29877}I jesi.
{29887}{29967}Ali slušaj, dvije stvari.|Prva, zovi me Michael. - Dobro.
{29969}{30041}I druga, ništa ne obeæavam.|Samo pola sata.
{30045}{30085}To je sve što tražim.
{30104}{30177}Ohrabrujemo ih da sudjeluju|u kuhanju jednom na tjedan,
{30179}{30249}što Tommyju prilièno|dobro ide. Dobro miriše.
{30254}{30317}Ako upotrijebite dosta|èešnjaka, sve dobro miriše.
{30319}{30376}Prièala sam ti o dr. Hunteru,|mome starom profesoru...
{30379}{30422}Ovaj, bivšem profesoru.
{30427}{30473}Zdravo, ja sam Tommy.|- Michael.
{30490}{30546}Drago mi je. - Takoðer.
{30550}{30623}Mogu li ga ostaviti s tobom|nasamo da razgovarate?
{30627}{30672}Svakako. Nikamo ne idem.|- Dobro.
{30712}{30734}Zdravo.
{30753}{30834}Bar ne još pet i pol tjedana.|- Tako su mi rekli.
{30880}{30957}Je li ti drago što odlaziš?|- Vama ne bi bilo?
{30981}{31021}Da, bilo bi.
{31115}{31190}Onda, što ste vi?|Moj završni ispit?
{31205}{31241}Što to znaèi?
{31289}{31389}Poslali su mi sve struènjake.|Vi biste mogli biti zadnji.
{31513}{31550}Ne baš.
{31606}{31640}Što je na jelovniku?
{31650}{31742}Nekakav cušpajz. Ostatak|mesne štruce, piletine,
{31745}{31790}povræa, tjestenine.
{31848}{31915}Želite kušati?|- Svakako. Dobro miriše.
{31954}{32013}Malo je vruæe. Izvolite.
{32032}{32087}Razmišljaš li o ovome|kao o karijeri?
{32091}{32151}Ne znam. Stresnije je|nego što to ljudi misle.
{32154}{32227}Kladim se da nisam prvi kuhar|kojeg lijeèite. - Imaš pravo.
{32231}{32328}No opet, ne lijeèim te.|Samo razgovaramo.
{32359}{32413}Nitko nikad samo ne razgovara.
{32484}{32581}Onda, što mislite?|Nešto nije u redu sa mnom?
{32637}{32679}Tek sam te upoznao.
{32702}{32777}Misliš li ti da nešto|nije u redu s tobom?
{32780}{32835}To još nisam èuo.|- Zato sam ovdje.
{32839}{32872}Mogao bih tako nastaviti.
{32875}{32963}Misliš da ja mislim da|nešto nije u redu s tobom?
{32967}{33022}Mislim da nešto|nije u redu sa svima.
{33025}{33103}To je dobro, inaèe bih morao|potražiti pravi posao.
{33107}{33155}A ne znam kuhati.
{33248}{33313}Ukusno je. - Dobro.
{33913}{33951}Bilo mi je drago. - Da.
{34439}{34514}Smijem li malo pojaèati|glasnoæu? - Prestani, tata.
{34924}{34957}Razgovarajmo.
{34990}{35051}Mislila sam da više|ne primaš pacijente.
{35080}{35153}On nije pacijent.|Samo je djeèak.
{35182}{35296}Samo djeèak u domu za|zastranjele. Koga je ubio?
{35304}{35373}Koga je ubio?|Nije nikoga ubio.
{35411}{35492}Zapravo je sabraniji|od nekih tvojih poznanika.
{35507}{35596}Od Troya, recimo.|- Ti i ne poznaješ Troya, tata.
{35601}{35643}U tome i jest problem.
{35667}{35750}Je li ga tvoja majka upoznala?|- Ne. Mama je zauzeta.
{35927}{35966}Kada æeš se obrijati?
{36028}{36074}Zašto se razilazimo?
{36092}{36161}Daj, tata. Ne razilazimo se.
{36165}{36208}Nismo kao prije.
{36214}{36338}Gdje si bio? Pogledaj se u|zrcalo. Ništa nije kao prije.
{36589}{36625}Kako slatko.
{36696}{36735}Što si rekla, tko je on?
{36739}{36806}Brad. Novi partner u tvrtki.
{36851}{36882}Glupan.
{36902}{36935}Totalni.
{37020}{37088}Moram iæi. Hvala za auto.
{37344}{37387}Neæemo se poljubiti?
{37441}{37502}Zdravo, dušo.|Kako je bilo u školi?
{37988}{38080}Kyle! Ne! Bože! Ne!
{38752}{38782}Zdravo, tata.
{39326}{39362}Tako mi je žao.
{39550}{39617}Pogledaj se. Živ si.
{39653}{39705}Baš je lijepo što si živ.
{39782}{39848}Ne, tata. Nisam.
{41171}{41208}Trebat æeš potpuniji dosje.
{41213}{41259}Ovo su zabilješke|s razgovora s Tommyjem.
{41262}{41331}Policijska izvješæa,|sudski transkripti.
{41335}{41387}Pretpostavljaš da æu ga|htjeti opet vidjeti.
{41391}{41421}Pa, došao si danas.
{41425}{41482}Danas da, no to ne znaèi|da sam došao na duže vrijeme.
{41486}{41520}To ovisi o tebi.
{41524}{41582}Samo uzmi kutiju.|Neka bude kod tebe.
{41618}{41664}I lijepo je opet|vidjeti tvoje lice.
{41668}{41741}Taj profesorski izgled...|To nisi bio ti.
{41917}{41943}Hvala.
{42507}{42608}Diana Caffey kod kuæe|s Tommyjem starim 4 dana.
{42700}{42774}Tommy i tata, ljeto 1993.
{42886}{42981}Joseph, Diana i Tommy,|Božiæ (1996.)
{43283}{43388}Tommyjeva majka (Diana)|Naðena u kuhinji.
{43411}{43436}Zaboga.
{43605}{43723}Služi doživotnu kaznu|u kaznionici Cayerville
{43894}{43984}Tommy na mjestu zloèina
{44681}{44728}Uredili ste se. - Da.
{44757}{44825}Zbog mene?|- Ne posve. Ali blizu si.
{44861}{44902}Možemo li razgovarati? - Da.
{44986}{45055}Htio bih razgovarati|o tvojim roditeljima.
{45103}{45145}Ja radije ne bih.
{45186}{45230}Dobro. A o školi?
{45241}{45302}Proèitao sam tvoj dosje.|Ocjene su ti bile loše,
{45304}{45399}a sada imaš èiste petice.|Sto se dogodilo? - To je sve?
{45450}{45517}Slažete se da ne razgovaramo|o mojim roditeljima?
{45521}{45592}Ako ne želiš, neæemo.
{45607}{45692}Reci mi, kako si odjednom|postao tako pametan?
{45710}{45793}Ne znam. Prije sam|èesto markirao.
{45799}{45866}I kamo si išao?|- Vucarao sam se.
{45880}{45964}Obièno sam išao do pruge.|Vezivao bih maèke lutalice.
{45966}{46050}Gledao kako vlak|prolazi preko njih.
{46141}{46171}Šalim se.
{46203}{46244}Znao sam.
{46248}{46278}Ne, vjerojatno sam se
{46282}{46358}uozbiljio|kad sam ovdje završio.
{46362}{46421}Poèeo sam planirati buduænost.
{46461}{46564}Što god æu na kraju raditi,|trebam nešto normalno.
{46572}{46628}Što je normalno? - Ne znam.
{46664}{46738}Samo želim biti slobodan.|- Što ti to znaèi?
{46748}{46781}Pa...
{46823}{46869}Èujete?
{46921}{46962}Tako zvuèi.
{47013}{47102}I to æe znaèiti da više neæu|morati odgovarati na pitanja.
{47112}{47171}Moram na predavanje.|Vidimo se.
{47753}{47798}Zdravo. - Što radiš ovdje?
{47923}{47973}To je lijep pozdrav.
{48021}{48070}Hoæeš u kino, na hamburger?
{48107}{48199}Ne mogu, tata. Petak|uveèer je. - Da, tako je.
{48225}{48271}Moram iæi. - Volim te.
{48345}{48389}Onda, što misliš?
{48472}{48516}Dobro izgleda.
{48538}{48585}Nazvat æu te. - Dobro.
{49153}{49208}Veèeras je veliki|rave na pruzi.
{49221}{49255}Jesi li za?
{49274}{49304}Dobro.
{49526}{49563}U redu. Idemo.
{51442}{51482}Paule!
{51525}{51606}Sranje, ti nisi Paul!|- Ne. Žao mi je, nisam.
{51611}{51743}Jebiga. A on ima robu. Imaš|li ti robu? Gljive, nitro?
{51767}{51817}Ne, žalim. Ponestalo mi.
{51863}{51927}Da veæ nisam na eksu,|popizdila bih.
{51956}{52045}Osim toga, veæ sam izgubila|svoj trbušni prsten.
{52049}{52111}Hoæeš li mi|pomoæi u potrazi?
{52261}{52306}Kako ti je ime? - Tommy.
{52310}{52420}Ja sam Chloe. Doista nikad|nisi probao ecstasy?
{52437}{52487}Ne. Ne zanimaju me droge.
{52492}{52621}Kao da valovi prolaze kroz|tebe. Toplo je i zamagljeno.
{52673}{52732}A kod seksa je još bolje.
{52758}{52798}Crveniš se?
{52851}{52886}Guba.
{52902}{53049}Poželiš i dirati.|Sve i sva. Osjeæaš se dobro.
{53061}{53123}Tvoj prsten je ovdje negdje?
{53131}{53210}Tu je negdje pao.
{53254}{53315}Trebali bismo se vratiti|na rave, zar ne?
{53322}{53365}Kako to misliš?
{53410}{53477}Mislim da æu...|Samo se želim vratiti.
{53493}{53590}Èekaj! Jesam li|nedovoljno jasna?
{53594}{53638}Ne želim. Dobro?
{53666}{53703}Ne želiš me!
{53723}{53769}Mislim... Nisi ti kriva.
{53774}{53856}Znaš li koliko bi njih|ovo objeruèke prihvatilo?
{53936}{53965}Doði...
{54289}{54323}Pogledaj komade! - Što?!
{54327}{54407}Mnogo komada! - Navali.|Ja æu potražiti Troya.
{54849}{54879}Troy!
{54971}{55004}Jebi se.
{55493}{55554}Ti si kæi dr. Huntera, zar ne?
{55567}{55636}A ti si njegov novi pacijent.|- Jesam li?
{55640}{55698}Iz nekog razloga me|ne želi tako nazvati.
{55702}{55747}Da, èudan je. Vidimo se.
{55773}{55823}Jesi li dobro? - Da.
{55887}{55920}Možeš li me odvesti kuæi?
{55923}{55983}Tek smo došle.|Jesi li našla Troya?
{55989}{56062}Molim te, ne mogu|ostati ovdje.
{56067}{56141}Ohladi, Shel. Tek smo došle.
{56248}{56288}Možeš li me odvesti kuæi?
{56291}{56354}Nemam auto.|Ali te mogu otpratiti.
{56379}{56457}Zbilja je daleko.|- Ne smeta mi.
{56475}{56524}Shelly! Shel!
{56538}{56566}Oprosti.
{56568}{56619}Sjeban sam, Shel.|Malo sam pijan.
{56623}{56667}Mislio sam da si ti ona cura.
{56670}{56717}Molim te. - Kunem se|svojom jebenom majkom.
{56719}{56773}Ne bi to trebao raditi.
{56776}{56847}Tko si ti?|- On prati Shelly kuæi.
{56884}{56936}Misliš? - Svakako.
{56983}{57049}Sereš, stari.|- Prestani, Troy. Pijan si.
{57053}{57109}Jebeš njega! Ubit æu nakazu!|- Prestani!
{57214}{57254}Èuvaj leða, kompa.
{57270}{57319}Hoæu. Doði.
{57709}{57789}Petak uveèer je.|Nema sretne dame?
{57876}{57944}Ne? Ajme. Zašto ne?
{57952}{58001}Dobro. Dosta sam rekla.
{58101}{58189}Jesi li ti sam uopæe bio na|terapiji otkad ti se sin ubio?
{58338}{58370}Ne.
{58400}{58484}Ne mogu zamisliti što|si proživio. - Da, pa...
{58526}{58569}U redu je.
{58624}{58702}Zašto to radiš? - Što?
{58713}{58753}Spomenula sam|tvoga sina dvaput,
{58757}{58824}a ti si rekao u redu|kao da me tješiš.
{58829}{58896}Ili ušutkavaš.
{58970}{59008}Ništa ti ne promakne.
{59074}{59128}Što se bojiš da æu reæi?
{59133}{59264}Bojim se da æeš reæi da je|moj sin na boljemu mjestu.
{59319}{59392}Ili da mi je bar ostala kæi.
{59418}{59475}Ljudi ti to zapravo govore?
{59478}{59559}Ne otkako sam se nauèio|govoriti u redu je.
{59764}{59834}Moj tata bi poludio|da zna da sam s tobom.
{59863}{59935}Uvijek govori o|profesionalnim granicama.
{59964}{60005}Znaèi, vjeruješ mi?
{60029}{60114}Ne znam. Mojem tati se sviðaš.
{60125}{60159}Sviðam?
{60214}{60306}Onda... Ta tvoja škola...|- To je dom. Možeš to reæi.
{60388}{60480}Zar nemaš zabranu izlaska?|- Da. Ali vjeruju mi.
{60502}{60603}Ionako æu biti slobodan za|mjesec i pol. Sam u svijetu.
{60607}{60660}Znaèi da moraš biti|dobar prema meni.
{60664}{60733}Zašto? - Ako ne budeš,|moj te tata neæe pustiti.
{60739}{60793}Nemoj to govoriti. U redu?
{60818}{60909}Šalila sam se. Moj te tata ne|bi mogao zadržati ni da hoæe.
{60912}{60973}Da, mogao bi! Mogao|bi me zadržati tamo!
{60976}{61063}Zato je i došao.|A ja neæu ostati, Shelly.
{61067}{61120}Dobro. - Neæu.
{61178}{61313}To je bila glupa šala. Ne|brini se. Mome se tati sviðaš.
{61494}{61586}U redu je. I meni je žao.
{61630}{61663}Doði.
{61686}{61777}Živi li tvoja kæi s tobom?|- Ne. Živi sa svojom majkom.
{61804}{61880}Ali ona je razlog zašto se|nisam vratio u Philly.
{61885}{61932}Tate i kæeri, ha?
{61951}{62027}Mrzi nas oboje.|- Uvjerena sam da te ne mrzi.
{62031}{62080}Ljuta je. To znam.
{62105}{62156}Još od Kylea.
{62168}{62228}Njezina mama i ja smo bili|tako zaokupljeni jedno drugim
{62231}{62290}da se ona izgubila u sredini.
{62320}{62375}A ti i tvoja majka ste|krivili jedno drugo.
{62379}{62470}Ne. Ona je krivila mene.|A i ja sam.
{62544}{62602}Ali više se ne kriviš.|Nadam se.
{62654}{62708}Michaele?
{62723}{62772}Pametniji si od toga.
{62797}{62857}Samoubojstvo je|samomotivirajuæi èin.
{62860}{62937}Ti si nas to uèio.|Nitko drugi ne može te
{62948}{63000}natjerati na to.
{63008}{63102}Volio bih zadržati se|na Tommyju. - U redu.
{63523}{63548}Što je?
{63575}{63608}To je moja stara kuæa.
{63640}{63698}Šest agencija u dvije godine.
{63728}{63769}Zašto se nije prodala?
{63812}{63858}Mogu li je vidjeti?
{63864}{63895}Zašto?
{63916}{63954}Ne želiš to?
{64033}{64088}Može. Zašto ne? - Guba.
{64631}{64655}Kako si to uèinila?
{64659}{64752}Moj brat je to namjestio.|Uvijek bi se zakljuèao vani.
{64905}{65015}Ovo je bila blagovaonica.|Tamo je bio veliki stol.
{65091}{65199}A ovo je bio dnevni boravak.|Tamo je bio kauè
{65229}{65323}i stoliæ za kavu.|Ovdje je bilo veliko zrcalo.
{65351}{65399}A tamo je kupaonica.
{65518}{65551}Što je gore?
{65730}{65774}Soba moga brata.
{65778}{65826}Da? Starijeg ili mlaðeg?
{65842}{65911}Nijedno. Mrtav je.
{65974}{66018}Ubio se u garaži.
{66073}{66105}Kako?
{66129}{66221}Ugljièni monoksid. U|obiteljskom monovolumenu.
{66224}{66286}Kažu da je to kao kad zaspiš.
{66290}{66401}Da. Šaka maminog valija|se pobrinula za to.
{66742}{66779}Kakav je bio?
{67007}{67045}Bože...
{67102}{67144}Svi ti tragovi.
{67190}{67253}Moj brat je imao tu lopticu.
{67264}{67330}Uvijek ju je nabacivao.|Izluðivao je moju majku.
{67398}{67439}A tatu?
{67459}{67518}On je to volio. Uvijek|su se igrali zajedno.
{67626}{67685}Èak i moji roditelji|krive sebe.
{67744}{67781}A ti?
{67802}{67876}Ne. Ne želim im pružiti|to zadovoljstvo.
{68123}{68206}Uvijek sam mislila|da sam ja kriva.
{68266}{68313}Mogla sam ga sprijeèiti.
{68375}{68410}Znala sam...
{68498}{68561}To ga je muèilo. Svi smo|znali. I moj tata je znao.
{68565}{68641}Pokušao ga je poslati na|terapiju, ali bezuspješno.
{68645}{68706}Stanje mu se|još više pogoršalo.
{68741}{68813}Da si mogao èuti kako sam|razgovarala s njim.
{68817}{68876}Sjedila sam pored njega
{68942}{69008}i bilo mi je stalo|samo do sebe
{69045}{69112}i do moje glupe predstave.
{69146}{69190}Nedostaje mi.
{69300}{69411}Oprosti. Nikad ne|razgovaram o tome.
{69426}{69466}Trebali bismo poæi.
{70044}{70081}Što je tvoj otac radio?
{70087}{70178}Bio je prodavaè.|Restoranske potrepštine.
{70252}{70304}Slažeš se da|razgovaramo o njemu?
{70307}{70405}Ne baš. No ne bi mi škodilo|da malo suraðujem.
{70427}{70513}Cijenim to. Što tražiš?
{70547}{70628}Ovdje je negdje.|Siguran sam. Ah, evo je.
{70778}{70823}Prije sam stalno igrao.
{70861}{70896}Što kažete?
{70898}{70942}Pokažite mi svoju|najbolju igru.
{71247}{71275}Dobro je.
{71286}{71358}A tamo? Lijepo.|Nastavi se kretati.
{71384}{71420}Po ovu vi idete.
{71569}{71625}O èemu govorite?|3:1? Vi niste postigli bod.
{71629}{71691}Naravno da jesam.|- Niste. Ja serviram.
{71724}{71754}Što je to bilo?
{71803}{71858}Što je to bilo?|Nisam to vidio.
{72082}{72137}Trebao sam je stiæi.|Mislim da je to zbog cipela.
{72141}{72210}Da, tako je.|Okrivi cipele, tata.
{72259}{72359}Idemo. Zar ste|umorni? Idemo!
{72428}{72479}Hajde. Bacite lopticu.
{72607}{72652}Hajde.
{72817}{72846}Još jedna.
{73135}{73181}Dobra igra. Vrlo lijepo.
{73186}{73225}Sretnik.
{73279}{73337}Sanjaš li ikad|svoje roditelje?
{73443}{73529}Sanjam li ikad svoje|roditelje? To je novo.
{73534}{73577}Snovi imaju znaèenje.
{73582}{73674}To tvoja podsvijest pokušava|riješiti neriješena pitanja.
{73704}{73778}Ne. Ne sanjam. Ne njih.
{73804}{73864}Dobro. Što sanjaš?
{73899}{73950}A vi? - Što ja?
{73963}{74026}Sanjate li svoga sina?
{74197}{74259}Kako znaš za njega? - Ne znam.
{74263}{74364}Znam samo da je mrtav.|Oprostite.
{74429}{74463}U redu je.
{74626}{74675}Prièaj mi o svojim|roditeljima.
{74709}{74795}O njihovom braku.|- Mislim da to znate.
{74802}{74843}Znam kako je završio.
{74885}{74934}No moralo je biti|i dobrih trenutaka.
{74960}{75012}Trenutaka ljubavi meðu njima.
{75266}{75314}Znam da je teško|govoriti o tome.
{75317}{75356}Ništa vi ne znate. U redu?
{75358}{75412}Onda me prosvijetli.
{75470}{75534}Kako si se osjeæao onaj|dan kad si došao doma?
{75574}{75625}Što mislite,|kako sam se osjeæao?
{75641}{75682}Pretoèi to u rijeèi.
{75733}{75827}Doista ne želim. Dobro sam.
{75901}{75982}Ne želim više igrati.|- Ne igramo se.
{75986}{76052}A ako doista želiš biti|slobodan za mjesec dana,
{76056}{76144}trebali bismo se|pozabaviti ovime.
{76148}{76210}Zadržali biste me ovdje kao|da sam lud? - Nisam to rekao.
{76213}{76328}Samo se brinem da ne zabrljaš|svoju buduænost u svijetu.
{76331}{76416}Kada doðem u pravi svijet,|prošlost više neæe biti bitna.
{76418}{76461}Nadam se da je to istina.
{76465}{76571}Dokaži mi to. Dokaži da si se|pomirio sa svojom prošlošæu.
{76718}{76758}Razgovaraj sa mnom.
{76769}{76828}Ne gledaj dolje. Pogledaj me.
{76913}{76984}Pusti to iz sebe.|Pretvori to u zvuk.
{77312}{77375}Razgovaraj sa mnom. Zašto|ne možeš razgovarati sa mnom?
{77429}{77484}Molim te. - Dobro.
{77532}{77575}Ali ne sada.
{77749}{77781}Dobro.
{77860}{77906}Ali ne sada.
{77970}{78020}Zašto? - Jednostavno...
{78076}{78201}Drugi put. - Dobro. Drugi put.
{78274}{78308}Dobro.
{78655}{78707}Skoro je zaplakao? Ozbiljno?
{78713}{78771}O èemu ste razgovarali?|O njegovom ocu? O majci?
{78775}{78832}Reci mi što si uèinio.
{78867}{78919}Jedva sam zagrebao površinu.
{78923}{78972}Nikad prije nije|bila zagrebana.
{78977}{79058}Ne bi ti škodilo da|proslaviš male pobjede.
{79099}{79180}Možeš li ga zadržati ovdje?|- Ovo je škola za djeèake.
{79184}{79246}Morali bismo ga prebaciti u|ustanovu za odrasle. Zašto?
{79248}{79290}Misliš da bismo ga|trebali zadržati?
{79294}{79335}Imaš li ovlasti|zadržati ga ovdje?
{79339}{79367}Tehnièki.
{79371}{79456}Mogli bismo ga vezati. No ako|zatraži svoj dosje, papire,
{79459}{79516}država me smatra|njegovim skrbnikom
{79520}{79603}i morala bih potpisati|njegovo službeno otpuštanje.
{79605}{79665}Je li ti ikad|spomenuo moga sina?
{79667}{79736}Nikad ne bih izdala to|povjerenje, Michaele.
{79883}{79919}A ovo?
{79947}{80031}Rekao je da je stalno igrao.|- Na što ciljaš?
{80282}{80347}I moj sin je stalno igrao.
{80446}{80508}Hoæeš reæi da te|podsjeæa na tvoga sina?
{80671}{80707}Michaele?
{80840}{80883}Michaele?
{81364}{81396}Shelly?
{81408}{81447}Uði. - Ne razgovaram s tobom.
{81531}{81565}Ne igraj te igre.
{81569}{81616}Nije to igra. Preboljela|sam te. Idemo dalje.
{81618}{81646}Preboljela si me? - Da.
{81650}{81698}Ne odlazi od mene dok|razgovaram s tobom.
{81701}{81739}Nismo završili.|Idemo na vožnju.
{81743}{81800}Moram razgovarati s tobom,|Shelly! - Ne želim...
{81833}{81895}Rekla je ne.|- Jebemti! Pusti me!
{81912}{81963}Dobro! Samo me pusti!
{82186}{82214}Jebemti!
{82309}{82339}Mama!
{82379}{82412}Mama!
{82470}{82523}Lijepa kuæa. - Valjda.
{82585}{82646}Hoæeš nešto popiti? - Da. Može.
{83233}{83285}Ne misliš da æe me prijaviti?
{83310}{83353}Tko? Troy? - Da.
{83357}{83415}Ne bi razgovarao s policijom.
{83419}{83489}Oduzeta mu je vozaèka.|Vozio je pijan.
{83504}{83563}Murjaci su zadnji ljudi|s kojima želi razgovarati.
{83567}{83659}Policija je pronašla tijelo|20-godišnje Chloe Frymen...
{83663}{83733}Bože! Poznajem tu djevojku!|Išla je u moju školu!
{83781}{83881}Glasnogovornik policije kaže|da se sumnja na ubojstvo
{83886}{83954}iako još nema nikakvih|znaèajnih tragova.
{83962}{84042}Melissa Gleason iz|željeznièke postaje Lawrence.
{84048}{84108}Larry. - Hvala, Melissa.
{84112}{84159}Bože, to je strašno.
{84229}{84271}Jesi li dobro?
{84292}{84351}Samo sam... - Da, znam.
{84376}{84483}Užasno. Željeznica?|Sigurno je bila na raveu.
{84487}{84565}I mi smo bili tamo.|- Da, bili smo.
{84719}{84789}Hoæeš li još? Dobro je, ha?
{85499}{85572}Bože! Uplašio si me!|- Oprosti. Nisam htio.
{85576}{85649}Ne, u redu je.|To je bilo nenamjerno.
{85653}{85710}Trebao bih poæi.|- Ne! Èekaj!
{85724}{85819}Tommy? Što je?|- Ništa. Samo...
{85855}{85926}Ne smijem upropastiti šanse|za odlazak iz Holly Hillsa.
{85930}{86026}Zbog Troya? Ja æu se|zauzeti za tebe.
{86066}{86110}Štitio si me.
{86267}{86304}I hvala ti.
{86621}{86663}Nema na èemu.
{86876}{86946}Ne brinite se ako ste|prekršili zabranu izlaska.
{86956}{87041}Ako ste bili vani tu noæ,|neæete biti kažnjeni.
{87058}{87136}Samo nekoliko pitanja.|Prije tri petka,
{87169}{87214}željeznièko skladište|Lawrence,
{87218}{87329}stara tvornica kemikalija...|Jedan od onih rave tuluma.
{87351}{87406}Oèito zanimljivo mjesto...
{87410}{87472}Ostavit æu broj na koji se|možete javiti.
{87476}{87596}Strogo povjerljivo. Možda|pomognete u hvatanju ubojice.
{87633}{87666}Hvala.
{87713}{87809}Shvatite, g. Caffey, da nisam|došao otvoriti stare rane
{87814}{87888}ili vas osuðivati|na bilo koji naèin.
{87906}{88012}Kako je on?|- Dobro. Donio sam vam sliku.
{88146}{88184}Kad su mi rekli da æete doæi,
{88188}{88248}napola sam se pitao|hoæe li i on biti s vama.
{88252}{88341}Ne, on nije ovdje. Ali|može izaæi za tri tjedna.
{88492}{88551}Kuhinja. - Dobar je kuhar.
{88595}{88648}Da, Dianin utjecaj.
{88664}{88725}Nadam se da biste mi|mogli pružiti uvid
{88730}{88812}u nešto što možda ne znam.|- Kao na primjer?
{88856}{88933}Vrlo je pametan. - Prepametan|za vlastito dobro.
{88965}{89044}Jeste li ga disciplinirali?|- Kad je to bilo potrebno.
{89051}{89106}A vaša žena?|Je li ga ona...?
{89117}{89190}Molim vas. Ta žena ga je|samo grlila i ljubila.
{89198}{89250}Mene nije, naravno.
{89254}{89304}Da, proèitao sam vaše|sudske transkripte,
{89308}{89363}vašu obranu. Drugi èovjek.|Zloèin iz strasti.
{89367}{89474}Da. Da vas pitam.|Kako biste se vi osjeæali?
{89480}{89554}Ranije sam se vratio doma.|Imao sam loš dan na poslu.
{89654}{89783}Ništa, Di. Ništa|cijeli tjedan.
{90359}{90402}Ranije si se vratio.
{90486}{90512}Jo!
{90736}{90790}Drijemala sam. Uplašio si me.
{90809}{90856}Otišao sam do prozora,|a tamo je bio on.
{90860}{90954}Polugoli kujin sin koji je|trèao kroz dvorište iza kuæe.
{91013}{91053}I tada sam poludio.
{91384}{91435}Što si uèinila?!
{91576}{91612}Isuse.
{91675}{91751}Ako to nije privremeno|ludilo, ne znam što jest.
{91811}{91868}Lako to sada više nije bitno.
{91880}{91950}Što je bilo s Tommyjem|kad se vratio kuæi?
{91998}{92063}Bio je u školi.|Ništa nije vidio.
{92078}{92116}Samo rezultat.
{92203}{92236}Da...
{92245}{92297}To je vjerojatno|najgori dio.
{92341}{92422}Dok su me odvodili,|on je tamo stajao.
{92711}{92763}Tada sam ga zadnji put vidio.
{92841}{92884}Do sada.
{93069}{93101}Slušajte...
{93125}{93167}Jesmo li završili?
{93187}{93248}Želite li još što|podijeliti sa mnom?
{93290}{93363}Recite mu da ne dolazi.|Kad izaðe.
{93375}{93432}Recite mu da ga više|ne želim vidjeti.
{93484}{93540}Recite mu da ne dolazi.
{93562}{93609}Recite mu to, u redu?
{93882}{93922}Niste imali prava iæi tamo.
{93926}{93979}Taj tip nema|nikakve veze sa mnom.
{93984}{94034}Otac ti je i stalo|mu je do tebe.
{94050}{94139}Nije mu stalo.|Sto sad govori? Da je nevin?
{94151}{94209}Ne, prihvaæa posljedice|onoga što je uèinio.
{94214}{94257}Moram te nešto pitati.
{94295}{94346}Jesi li vidio oca|kako ubija majku?
{94356}{94427}Kakvo je to pitanje?|- Jednostavno. Odgovori.
{94459}{94521}Rekao je da jesam? - Ne,|rekao je da si bio u školi.
{94525}{94563}I bio sam u školi.
{94567}{94636}Ti si mi rekao da si|uvijek markirao.
{94645}{94691}Jesi li markirao i taj dan?
{94694}{94775}Ne. Ali i da jesam, bio bih|na željeznièkoj pruzi.
{94777}{94843}Tako da ni na koji naèin|nisam bio tamo.
{94891}{94921}Dobro.
{95015}{95072}Neæe ti se svidjeti|iduæe pitanje. - Stanite.
{95079}{95150}Znam što æete reæi.|Nije bilo drugog èovjeka.
{95158}{95296}Usmjerio si nož u mene, Tommy.|Nemoj držati nož prema meni.
{95359}{95419}Moja mama to nikada|ne bi uèinila.
{95439}{95478}Nema šanse.
{95483}{95548}Doimaš se uvjereno.|- Uvjeren sam.
{95630}{95758}Znaš da je obdukcija dokazala|nedavnu seksualnu aktivnost?
{95769}{95814}Zašto to radite?
{95837}{95925}Što radite? Govorite|o mojoj mami, zaboga!
{95938}{95990}I što hoæete? Što hoæete?
{95994}{96056}Što hoæu od tebe? Moramo|razgovarati o ovome.
{96058}{96112}Pristao si na razgovor|i razgovarat æemo.
{96116}{96168}Znam da je ovo bolno|i žao mi je.
{96172}{96215}Ali moramo razgovarati o tome.
{96219}{96266}Reci mi, kako si se|osjeæao taj dan?
{96270}{96308}Kako sam se osjeæao taj dan?
{96312}{96366}Moj tata je došao kuæi|i posvaðali su se.
{96370}{96396}Ubio ju je.
{96400}{96485}A sada kaže da je bila|drolja samo da se izvuèe.
{96490}{96538}Kako se ti osjeæaš zbog toga?|- Kako se ja osjeæam?
{96542}{96577}Kako se osjeæaš?
{96602}{96631}Ovako?! - Da.
{96635}{96705}Sretni ste zbog ovoga?|Muka mi je od toga!
{96717}{96752}Sranje!
{96756}{96801}Idem odavde!
{96818}{96893}Pustite me!|- Izbaci to iz sebe! Izbaci!
{96896}{96963}U redu je, Kyle.|Imam te, Kyle.
{96967}{97029}Kyle? Kyle! Pustite me!
{97047}{97095}Nisam vaš sin.
{97102}{97151}Oprosti. Tommy.|Tommy, nisam tako mislio.
{97156}{97237}Ne, nemojte. Nisam vaš sin.|U redu? - Znam to.
{97290}{97330}Nisam ja bio kriv.
{97341}{97370}Hajde.
{97378}{97482}Hajde, recite. Recite:|Nisi ti kriv.
{97493}{97588}Hajde. Svi to kažu.|Hajde. Nisam ja kriv!
{97591}{97681}To što se dogodilo mojoj majci|nije imalo veze sa mnom!
{97694}{97732}Recite to!
{97801}{97842}U redu, Tome.
{97859}{97901}I nije bilo drugog èovjeka.
{97990}{98040}Nije bilo drugog èovjeka.
{98051}{98099}Tako je.
{98137}{98224}Mislim da smo završili.|- Da, završili smo.
{98253}{98291}Oprosti.
{99152}{99189}Sranje...
{99480}{99534}Još dva tjedna i nema me.
{99563}{99664}Ali moram otiæi po njihovim|pravilima. Kao obièna osoba.
{99719}{99781}Ali ti nisi obièna osoba.
{99787}{99873}Ti nisi kao nitko|koga sam ikad upoznala.
{99885}{100021}Razgovaraš sa mnom. I|slušaš me. Ne vršiš pritisak.
{100231}{100270}Ti me ne ispituješ.
{100321}{100369}Što? - O meni.
{100404}{100483}Ti si jedina osoba koja|ne kopa po mojoj prošlosti.
{100495}{100580}Da postoji nešto što mi želiš|reæi, rekao bi mi, zar ne?
{100915}{100966}Nemoj. - Što je?
{100977}{101051}Oprosti. Moram iæi.
{101982}{102014}Zdravo. - Zdravo.
{102154}{102207}Nisam mogao naæi tvoj broj.
{102249}{102305}Jesam li došao u krivo|vrijeme? - Ne. Uði.
{102308}{102361}Sigurna si da je u redu?|- Svakako.
{102426}{102468}Ovo je lijepo. - Hvala.
{102494}{102552}Sjedni. Da ti donesem|nešto? Piæe ili nešto drugo?
{102556}{102674}Ne, ne. Mislim da sam ionako|na zakonskoj granici.
{102702}{102813}Ne znam za koga da se više|brinem. Za tebe ili Tommyja.
{103001}{103085}Molim te, reci da si|me vidjela da dolazim.
{103108}{103179}Ne. Samo sam možda|tražila tragove.
{103185}{103310}Za majstora ljudskog stanja,|prema sebi nisi iskren.
{103366}{103431}Ne provodim svoje rijeèi|u djela, je li?
{103638}{103770}Napisao sam ovo nedugo|poslije Kylea.
{103781}{103887}A opet on uopæe nije unutra.|Nijednom ga ne spominješ.
{103921}{103984}Za mene je on na|svakoj stranici.
{104365}{104543}Pitala si me neki dan|podsjeæa li me Tommy na Kylea.
{104587}{104638}Podsjeæa, zar ne?
{104667}{104739}Katkad on postaje Kyle.
{104860}{104919}To nije neuobièajeno,|Michaele. Znaš li to?
{104923}{105020}Znam. To je prenošenje.|No ovo je nešto drugo.
{105033}{105140}Postoji nešto u njegovom|glasu, u kretnjama.
{105144}{105271}Držao sam ga i|osjeæao sam Kylea.
{105388}{105436}A njegove oèi...
{105558}{105631}To su njegove oèi.
{105978}{106022}Gubim razum.
{106084}{106129}Ne gubiš razum.
{106163}{106207}Samo ti nedostaje sin.
{106324}{106437}U redu. Kasno je. Umoran si.|- Molim te. Daj, Barbara.
{106459}{106515}Ostani ovdje i opusti se.|- Ne, dobro sam. Ozbiljno.
{106518}{106585}Znam da si dobro, ali ostani|ovdje. - Osjeæam se glupo.
{106588}{106645}Ne. Ne osjeæaš se glupo.|- Daj. Molim te.
{106648}{106767}Opusti se. Prespavaj ovdje.|Umoran si. Naspavaj se.
{107093}{107127}Hvala.
{108683}{108752}Tommy, nisam htjela. Oprosti.
{108771}{108807}U redu je.
{108820}{108877}Toliko mi se sviðaš.|- Shelly, nemoj.
{108899}{109014}Volim te, Tommy.|- Shelly, ne.
{109048}{109096}Samo želim biti s tobom. - Ne!
{109144}{109179}Rekao sam ne!
{110328}{110378}Želim vam reæi nešto,|g. Caffey.
{110382}{110412}Je li Tommy dobro?
{110417}{110478}Ne radi se o njemu.|Zapravo radi, ali neizravno.
{110498}{110557}Zapravo se više radi|o meni. O nama.
{110578}{110618}Što s nama?
{110621}{110696}Nitko ne zna za ovo.|Ni moja bivša žena.
{110700}{110734}Ni moja kæi.
{110766}{110802}O èemu govorite?
{110842}{110902}Imamo nešto|zajednièko, g. Caffey.
{110973}{111043}Zapravo se ne razlikujemo|previše. Vidite...
{111299}{111346}I ja sam imao sina.
{111380}{111458}Bio je sretno dijete.|Odano i puno poštovanja.
{111468}{111567}U pubertetu je razvio|jedan oblik depresije.
{111582}{111679}Moja žena je htjela da poène|uzimati lijekove, ali ja...
{111741}{111812}Htio sam da krene na terapiju
{111815}{111984}kod moga kolege Harryja|Quinlana. Moga prijatelja.
{112003}{112079}Nekoga kome sam vjerovao.
{112197}{112282}Prošlo je nekoliko mjeseci|i èinilo se da je Kyleu bolje.
{112296}{112401}A dobri stari Harry rekao|nam je da budemo strpljivi.
{112522}{112570}Da nastavimo vjerovati.
{112598}{112742}I ja sam nastavio vjerovati|dok se moj sin nije ubio.
{112815}{112853}Nekoliko dana|poslije sprovoda
{112857}{112930}našao sam Kyleovo oproštajno|pismo u kojem je objasnio
{112934}{113028}stid koji je osjeæao zbog svog|posebnog prijateljstva
{113032}{113133}s Harryjem Quinlanom. I kako|je to bilo previše za njega.
{113144}{113311}I da to više nije mogao|tajiti. Da se osjeæa prljavo.
{113464}{113534}Harry Quinlan je|zlostavljao moga sina.
{113570}{113650}Jebena životinja je|zlostavljala moga sina.
{113667}{113762}I moj 16-godišnji sin|nije našao drugi naèin
{113787}{113854}da se riješi tog bola.
{113978}{114020}Otišao sam u|trgovinu oružjem,
{114027}{114073}no tamo su imali|period èekanja.
{114075}{114134}Stoga sam otišao ravno|do kuæe Harryja Quinlana
{114138}{114185}jer sam ga htio mrtva.
{114188}{114224}Harry!
{114226}{114258}Harry, otvori vrata!
{114334}{114415}Otvori vrata, Harry! Smjesta|ih otvori, govno jedno!
{114423}{114463}Harry, otvori vrata!
{114472}{114526}Harry, pizdo! Otvori vrata!
{114548}{114589}Bravo, Harry!
{114633}{114685}Harry, pogledaj me!|Pogledaj me!
{114713}{114806}To je bio moj mali! Harry!|Moj mali! Jebena životinjo!
{114820}{114887}Što æeš uèiniti s time?|Otvori vrata, govno jedno!
{114894}{114982}Hajde! Ustrijeli me!|Bio je moj mali, Harry!
{114986}{115056}Bio je moj mali, jebena|životinjo! Uèini to!
{115061}{115120}Uèini to! Uèini to! Uèini to!
{115381}{115453}Znate li što nas|razdvaja, g. Caffey?
{115480}{115563}Ne razum ili racionalno|razmišljanje. Samo sreæa.
{115567}{115628}Samo glupa jebena sreæa.
{115751}{115803}Htio sam da to znate.
{115906}{115957}To je bio Tommy.
{116043}{116072}Što?
{116099}{116178}To je bio Tommy.
{116237}{116292}Ako ovo ponovite,
{116298}{116348}poreæi æu.
{116352}{116495}Kao što sam uvijek poricao. I|uvijek æu poricati. Do smrti.
{116525}{116573}Razumijete li?
{116921}{116978}Vratio sam se kuæi toga dana,
{116986}{117085}a tamo su se dogaðala|neke èudne stvari.
{117154}{117195}To je sve?|Razgovarat æete s njim?
{117199}{117279}Ako ga ne želite prijaviti|policiji, g. Pasternak...
{117283}{117316}Razgovaram s vama.
{117317}{117375}Pozovimo onda Tommyja|i èujmo njegovu stranu.
{117379}{117459}Da mi slomi i drugu ruku? Ne.|Lud je. Ne želim ga vidjeti.
{117463}{117510}Dobro. Razgovarat æu s njim.|Sad idite kuæi.
{117514}{117552}Nazvat æu vas.|Imam vaš broj. Hvala.
{117556}{117593}Raymonde, molim te.
{117602}{117662}Pazi kuda ideš, Raymonde.
{117676}{117740}Naði Tommyja i zamoli ga|da smjesta doðe.
{117945}{117975}Caffey?
{118022}{118060}Poznaješ onog tipa?
{118081}{118117}Kako si, sinko?
{118158}{118203}Ja sam det. Hannah,|a ovo je moj partner.
{118204}{118291}Razgovarao je s Barbarom|o tebi. Zvuèao je ljuto.
{118317}{118358}Što ti se dogodilo s rukom?
{118369}{118419}Zašto su murjaci opet ovdje?
{118423}{118479}Vjerojatno sada|žele naše otiske.
{118482}{118552}Ako dovoljno žele sumnjivca,|doðu po njega na Holly Hills.
{118556}{118644}Uglavnom, Barbara te želi|vidjeti i nije zvuèala sretno.
{119064}{119117}Nije u kuhinji. - Kažem ti,|Michaele, nije u kampusu.
{119122}{119174}Èak i da je mislio da je|u nevolji, ne bi pobjegao.
{119178}{119244}Ne možemo ga pustiti.|Mora ostati ovdje zauvijek.
{119247}{119274}Na stalnoj terapiji.
{119278}{119329}Kako je to uspio skrivati sve|ove godine i biti tako miran?
{119333}{119384}Ne skriva to.|Potisnuo je to u sebe.
{119388}{119435}Što se njega tièe, to se|nikada nije dogodilo.
{119439}{119483}Tko je taj mali|slomljene ruke?
{119498}{119523}Troy Pasternak.
{119527}{119569}Rekao je da se potukao s|Tommyjem oko neke djevojke.
{119572}{119601}Troy? - Da, zašto?
{119604}{119705}Tko je djevojka? - Nije rekao.|Samo da mu ju je Tommy ukrao.
{119777}{119811}Nazvat æu te kasnije.
{119973}{120027}Ne zakljuèavaš vrata?|- Michaele? Sto radiš?
{120053}{120079}Gdje je ona?
{120081}{120132}Shelly? - Da. Shelly.|Tvoja kæi. Gdje je?
{120136}{120186}Michaele?|- Je li u svojoj sobi?
{120189}{120213}Michaele!
{120348}{120388}Znaš li gdje je on?
{120392}{120482}Tko? - Znaš tko. Tommy|Caffey. Moj pacijent!
{120487}{120557}Rekao si da ti nije pacijent.|- Ne pravi se pametna.
{120561}{120620}Mislila sam da ti nije stalo!|- Pa mi nisi htjela reæi!
{120650}{120691}Jer sam znala da æeš|ovako reagirati.
{120695}{120749}Onda to nisi ni|smjela uèiniti!
{120752}{120822}Ne znaš ništa o njemu!|Ne poznaješ ga, Shelly!
{120826}{120878}Poznajem ga bolje od tebe.
{120882}{120963}Što bi to trebalo znaèiti?|- Ne. Ne tako! Bože!
{120964}{121022}Vidiš li sada|kako svi razmišljaju?
{121025}{121078}On mi je prijatelj,|tata. Razgovaramo.
{121082}{121139}Razgovarate! - Da.
{121143}{121201}Jesi li mu govorila o nama?|O našoj obitelji?
{121236}{121299}Jesi li razgovarala|s njim o Kyleu?
{121305}{121346}I o tome kako je Kyle umro?
{121350}{121413}Jesi li mu rekla da je|Kyle igrao handball?
{121417}{121479}Možda. Ne znam...|- Nema možda. Da ili ne?
{121483}{121564}Jednom smo bili u staroj kuæi|i možda sam nešto rekla.
{121569}{121656}U našoj kuæi? Odvela si ga|našoj kuæi? U našu kuæu?
{121680}{121735}Michaele, izaði.|- Znaš li za ovog deèka?
{121739}{121788}Kojeg deèka? - Kojeg deèka?|- Prestani vikati.
{121791}{121871}Gdje je sada? Jer nije u domu.|- Michaele... - Ne znam.
{121872}{121913}Shelly... - Ne znam!
{121946}{122002}Neæeš ga više vidjeti.|Razumiješ li?
{122005}{122056}Tata, ne možeš mi reæi...|- Neæeš ga vidjeti!
{122057}{122096}Ja sam ti otac!|Reæi æu ti što želim!
{122099}{122159}Pozvat æu Brada. - Ostani|kod kuæe! Zadrži je ovdje!
{122270}{122335}Ne možeš mi nareðivati|što da radim! Nije pošteno.
{122339}{122421}Tommyju je stalo do mene.|Više nego ikome od vas!
{122478}{122520}Samo idi, Michaele. Idi!
{122627}{122670}Zadrži je ovdje.
{123106}{123157}Tommyjeva majka (Diana)
{123406}{123495}Ima li štogod? - Ne, bila sam|na svim moguæim mjestima.
{123525}{123597}Odjeæa mu je još uvijek tu.|- Vratit æe se. Znam to.
{123601}{123676}A Holly Hills æe nazvati èim|se pojavi. Ako ti to pomaže,
{123682}{123742}naæi æu se s tobom. U redu?
{123745}{123809}Dopustio sam da|manipulira mnome, Barbara.
{123814}{123889}Iskoristio je moju|vlastitu kæer. I sina.
{123893}{123948}Ti si mu bio zadnja prepreka.
{123951}{124026}Sigurno je mislio da æe mu|bilo kakva usporedba s Kyleom
{124031}{124077}iæi u prilog.
{124083}{124142}Evo auta. Nazvat æu te.|- Michaele...
{125135}{125196}Držite noænu stražu, doktore?|- Samo èekam nekoga.
{125235}{125327}Znate li u kojoj sobi bih mogao |pronaæi Thomasa Caffeyja?
{125384}{125467}Njega èekam. Mislimo|da je možda pobjegao.
{125471}{125538}Jedino s njim danas|nisam razgovarao.
{125559}{125611}Hoæete li me nazvati|kad se vrati? - Svakako.
{125615}{125669}Hvala. Èuvajte se. - Takoðer.
{126348}{126379}Tommy?!|- Nemojte se ljutiti.
{126381}{126420}Ne ljutim se. Uði.
{126471}{126517}Michael je.|Jesi li tamo?
{126530}{126589}Ne, ne. Nemojte se javiti.|Molim vas. - Barbara?
{126593}{126649}Samo želim|razgovarati. - Dobro.
{126766}{126813}Dobro, nazovi me èim prije.
{126829}{126887}Ljuti li se na mene?|- Zašto bi se ljutio?
{126916}{126966}Zbog tebe i Shelly.
{126991}{127053}Zna za to?|- Da. Gdje si bio, Tommy?
{127061}{127093}Sranje!
{127179}{127252}Prije svega, Shelly je|dobra djevojka. I...
{127255}{127328}I nisam pritisnuo ruku onom|deèku. Morate mi vjerovati.
{127332}{127424}To nije razlog da nestaneš.|- Znam. Samo sam...
{127476}{127520}Uplašio sam se. - Èega?
{127554}{127616}Napuštam Holly Hills, Barbara.|Ne mogu više èekati.
{127621}{127706}Možemo razgovarati ujutro|u Holly Hillsu. U redu?
{127711}{127830}Ne. Nema više rasprava. Nema|razgovora. Odlazim noæas.
{127858}{127941}U redu, Tommy. Onda æu|nazvati dr. Huntera... - Ne.
{127945}{128014}Ne morate to uèiniti.|Koliko dugo vas poznajem?
{128018}{128079}Radio sam sve što ste|tražili od mene. Sve.
{128081}{128135}Sada samo želim|ono što mi pripada.
{128140}{128221}Što je tjedan i pol? Potpišite|moje papire i pustite me.
{128225}{128271}Tommy, napredovao si|velikim koracima.
{128274}{128323}Da, i to je dobro.|- Vrlo dobro.
{128327}{128430}I dr. Hunter... Vjerujemo da|bi ti koristilo... - Ne! Ne!
{128434}{128497}Neæu ostati ovdje!|Neæete me zadržati ovdje!
{128500}{128570}Koristilo bi ti još|savjetovanja, to je sve.
{128574}{128620}Je li to zbog Shelly?|- Nije zbog Shelly.
{128624}{128686}To je kazna. - Nije kazna.
{128712}{128802}Dr. Hunter je danas|opet posjetio tvoga oca.
{128865}{128918}Znamo istinu, Tommy.
{128933}{128975}O tvojoj majci.
{129052}{129085}Tommy?
{129135}{129173}Tommy, nemoj...
{129206}{129239}Tommy?
{129305}{129345}Tommy, molim te...
{129441}{129537}Moraš mi vjerovati.|- To je laž! Laž!
{129792}{129846}Ne, molim te!
{129994}{130023}Ne!
{130337}{130366}Barbara?
{130547}{130574}Barbara?
{130640}{130734}Pokušavam dobiti broj|324-8962, a ne mogu.
{130758}{130792}Barbara?
{131417}{131477}Kako to mislite, slušalica je|podignuta? - Mora biti.
{131834}{131867}Što ti radiš ovdje?
{131884}{131919}Ne bi smio biti ovdje, sinko.
{132116}{132153}Ne bi smio biti ovdje!
{132209}{132249}Tko je pustio dijete unutra?
{133103}{133130}Barbara?
{133379}{133410}Barbara?
{133423}{133457}Je li dobro?
{133489}{133533}Zovite policiju! Smjesta!
{133570}{133617}Zovite Hitnu!
{133649}{133688}Dobro je. Imam te.
{134028}{134081}Tommy. Doði straga.
{134195}{134237}Gdje si bio?|- Gdje ti je mama?
{134241}{134324}Gore s Bradom. Moj tata zna za|nas. - Znam. Odlazim veèeras.
{134355}{134424}Zašto? - Nisam tako|htio... - Idem s tobom.
{134504}{134564}Èekajte. Želi nešto reæi.|Sto, dušo? Sto?
{134568}{134638}Nisam smjela reæi...|- Sto nisi smjela reæi?
{134645}{134716}Majka... - O majci? U redu je.
{134722}{134774}Shelly... Shelly...
{134819}{134854}Shelly?
{135189}{135253}Michaele, smiri se. - Nemoj|mi govoriti da se smirim!
{135260}{135330}Mali je opasan.|- Kako to misliš, opasan?
{135358}{135419}Izvedi Shelly iz kuæe.|Ja dolazim.
{135461}{135489}Shelly!
{135513}{135544}Shelly, gdje si?
{135572}{135658}Èekaj. Nije li to Troyev auto?|- Dogovorili smo se. Upadaj.
{135737}{135768}Shelly!
{135779}{135846}Shelly! Ne!|Slušaj me! Shelly!
{136028}{136052}Michaele!
{136063}{136139}To su bili oni. S njim je.|Uzeo ju je, Michaele.
{136140}{136180}Zovi policiju! Smjesta!
{136378}{136438}Ne razumijem. Zašto bi ti|Troy posudio svoj auto?
{136441}{136503}Dosta pitanja, u redu?|Nemoj govoriti.
{136508}{136554}Razmišljam! - Oprosti.
{136589}{136662}Bojim se, Tommy. - I ja.
{136977}{137021}Sranje! To je moj tata.
{137133}{137176}Neæe me zadržati ovdje.
{137774}{137817}Shelly! - Hajde!
{137861}{137886}Ni makac!
{137901}{137936}Hajde. - Rekao sam, ni makac!
{137939}{137983}Bacite pištolj!|- Vi se ne miješajte!
{137984}{138050}To je moja kæi! Shelly!|- Baci pištolj! Baci ga!
{138053}{138116}Tommy, baci pištolj!|- Recite njemu da ga baci!
{138120}{138185}Spustite pištolj!|Spustite pištolj. Tommy...
{138352}{138384}Dopusti da ti pomognem.
{138387}{138432}Ne želite mi pomoæi|nego me zadržati ovdje!
{138436}{138488}Tommy, nemoj joj nauditi,|molim te. - Nauditi joj?
{138491}{138542}Neæe mi nauditi. - Nikad|joj ne bih naudio. Nikad!
{138546}{138593}Znaš da ne možeš održati|to obeæanje. - Zavežite!
{138596}{138642}Znaš to. - Zavežite!|Shelly vas mrzi!
{138645}{138712}Znam to. Znam da me mrzi.
{138742}{138862}I ne krivim je. Nije|ona kriva. Ja sam kriv.
{138942}{139029}Znam da sam te iznevjerio,|dušo. Kad ti je brat umro,
{139044}{139084}znam da nisam bio uz tebe.
{139088}{139159}Kao da si poèinjala novi|život, a ja nisam bio uz tebe.
{139161}{139259}Moram ti to nadoknaditi.|To mi je potrebno.
{139282}{139348}Hoæeš li mi pružiti priliku?
{139503}{139568}Tommy... Molim te.
{139572}{139645}Pruži mi tu priliku. Priliku|koju ja želim pružiti tebi.
{139649}{139752}Molim te. Pusti je.|Ti i ja možemo ovo riješiti.
{139774}{139823}To je moje dijete.
{139889}{140008}Znaš da mi bez tebe više|ništa nije ostalo. Molim te.
{140231}{140290}Žao mi je, Tommy. Moram iæi.
{140392}{140419}Tata...
{140762}{140825}Ovamo. Ne prilazite. U redu|je. Ja æu sve srediti.
{140830}{140878}Ne pucajte! Nemojte pucati.
{140912}{140954}Nema kamo pobjeæi, doktore.
{140970}{141011}Ne pucajte!
{141019}{141058}Tommy...
{141144}{141187}Nemaš kamo, Tome. Doði.
{141191}{141228}Što hoæete od mene?|- Želim ti pomoæi.
{141230}{141270}Zašto me jednostavno|ne možete pustiti?
{141274}{141357}Jer ti želim pomoæi. Ne mogu|te pustiti i ti znaš zašto.
{141388}{141454}Dopusti da ti pomognem.|Razgovaraj sa mnom.
{141544}{141592}Što vam je moj otac rekao?
{141686}{141715}Rekao mi je za tvoju majku.
{141718}{141791}Ne govorite o njoj!|Ona me voljela.
{141806}{141848}Jako te voljela. - Da.
{141964}{142005}On nije trebao biti tamo.
{142172}{142288}Ništa, Di. Ništa|cijeli tjedan.
{142292}{142339}Ormar. U ormar. U ormar.
{142427}{142492}Bio je tako ljut.|- Na koga je bio ljut?
{142547}{142605}Na mene! Bio je ljut na mene!
{142755}{142775}Ti!
{142817}{142889}Moja mama je voljela mene!|Nije voljela njega!
{142893}{142970}A on ju je udarao i udarao!|Htio sam da prestane.
{143011}{143060}Što si uèinila?!
{143062}{143109}Prestani! Prestani!
{143113}{143160}Prestani udarati moju majku!
{143201}{143226}Prestani!
{143249}{143308}Bio si djeèak. Nisi mogao|sprijeèiti ni jedno ni drugo.
{143312}{143370}Mogao sam ga sprijeèiti.|- Nisi ti bio kriv.
{143374}{143422}Griješite.|- Nisi ti bio kriv.
{143425}{143470}Griješite.|- Nisi ti bio kriv.
{143473}{143542}Ubio ju je zbog mene.|- Nisi ti bio kriv.
{143544}{143610}Jesam, ja sam bio kriv! - Nisi!
{143864}{143914}Sada ti mogu pomoæi, Tome.
{143927}{143991}Mogu ti pomoæi.|Dopusti da ti pomognem.
{144019}{144109}Ne. - Tommy, opusti se.
{144187}{144228}Molim te. Tako.
{144284}{144327}U redu je. Žao mi je.
{144501}{144554}Tommy! Ne! - Idemo!
{144974}{145022}Nemoj to uèiniti!
{145576}{145614}Tata!
{146271}{146308}Kako smo danas?
{146343}{146373}Savršeno.
{146453}{146487}Kako je Shelly?
{146550}{146580}Dobro.
{146632}{146670}Kako je Barbara?
{146784}{146819}Dobro je.
{146829}{146888}Usredotoèimo se danas|na tebe, u redu?
{146897}{146984}Zašto? Rehabilitirat æete me?
{147071}{147123}Oslobodit æete me, doktore?
{147145}{147189}Ima raznih sloboda.
{147191}{147246}Ali to nije sloboda|koju ja želim.
{147250}{147316}Ali postoji ona|koju svi trebaju.
{147346}{147386}Ona koja je unutra.
{147491}{147528}Ovdje.
{147664}{147705}Ja nisam vaš sin.
{147878}{147920}Znam to.
{148001}{148041}Da vidimo tvoju najbolju igru.
{148665}{148694}Dobar bod.
{148747}{148791}Imate sreæe. - Lijepo.
{148818}{148862}Tvoj servis? Dobro.
{148880}{148912}Pazi!
{148976}{149013}Vježbali ste, ha?
{149018}{149057}Lijepo. 
{149080}{149780}{C:$0000FF}{y:ib} d |{C:$FF0000}{y:b} d 
{150012}{150112}Prijevod:|VIRTUAL-D, Zagreb
{150137}{150262}Obrada:|Blitz Film&Video Distribution
