{1}{1}25.000
{633}{727}Kao djeèak sam se | uputio sam u šumu
{730}{787}da bih se popeo | na najviše drvo.
{793}{877}Pri samom vrhu okliznuo | sam se i pao, no uspio sam se
{880}{984}uloviti za jednu granu. | Bio je to dugaèak pad.
{1015}{1102}Visio sam tako dok mi | glava nije poèela pucati.
{1105}{1204}Ruke su me boljele kao | da mi ih trgaju s tijela.
{1235}{1367}Osjeæam to i sada. Krv | mi je bubnjala u ušima.
{1383}{1512}Užasna bol i strah od pada.
{2223}{2309}A mislio sam da sam sve vidio. | Vozila je više od 150 km/h.
{2393}{2474}Stavi ispod. Podupri | ga ispod vilice.
{2480}{2549}Ne vidim nikoga unutra. | Možda nije mrtva.
{2560}{2637} MUDROST KROKODILA 
{2803}{2879}Luda je što je tako vozila. | - Što želite reæi?
{2915}{2974}Možeš mi otpetljati žicu?
{4578}{4687}Iako nema svjedoka nesreæe, | policija je izvijestila sud
{4690}{4837}da je Sarah Duncan vozila | brzinom veæom od 130 km/h.
{4858}{4914}Prema mišljenju | policijskog lijeènika,
{4920}{4969}smrt je morala | biti trenutaèna.
{4983}{5042}Zakljuèujem da se | u sluèaju Sarah Duncan
{5045}{5099}radilo o nesretnom sluèaju.
{5245}{5332}Sud izražava suæut | obitelji gðice Duncan.
{5348}{5417}Kao i njezinom zaruèniku | Stevenu Grlsczu.
{5758}{5867}OÈAJ
{8488}{8592}Kako si? - Nisam | tražila tvoju pomoæ.
{9160}{9219}Ti si, zar ne?
{9678}{9759}Ne moraš stalno držati | palac gore. Piši olovkom.
{9770}{9817}Ne vrijedi. - Dobro.
{9823}{9924}Usredotoèi se na mene. | - Ovo sigurno ne možeš.
{10130}{10279}VOLIM TE, MRZIM TE
{10888}{10949}Što slavimo?
{10978}{11029}To je tajna.
{11158}{11234}Vjeruješ li mi? | - Jasno da ne.
{11270}{11329}Zatvori oèi.
{11438}{11504}Vjeruješ li mi, Maria?
{11538}{11607}Ne znam. Što æeš uèiniti?
{11700}{11767}Kako si to napravio?
{12108}{12169}Zašto me ne poslušaš | i zatvoriš oèi?
{12460}{12537}Otvori oèi.
{18063}{18209}RAZOÈARANJE
{18450}{18502}Imate li toèan iznos? | - Ne, žao mi je.
{18505}{18564}Trebam toèan iznos. | - Žao mi je.
{18625}{18709}To je sve što imam. | - Nemate ništa sitnije?
{18713}{18767}Da imam, dao bih vam.
{18863}{18929}Zadržite.
{25570}{25662}Pardon, to je moje. | Posvuda ga ostavljam.
{25670}{25787}Èujte, kažu mi da ste | me crtali u galeriji.
{25828}{25954}Jesam. - Mogu li vidjeti? | - Mislite, ponovno?
{26148}{26237}Vrlo su... - Lijepe? | - Nisam to mislila.
{26245}{26347}Niste zadivljeni? | - Ni to nisam mislila.
{26365}{26452}Samo što ja ne | izgledam tako dobro.
{26470}{26529}Djeca kažu da vas | vjerno prikazuju.
{26555}{26612}Ne mislim da sam lijepa.
{26618}{26712}Nisu rekli da ste lijepi, | veæ da su slike vrlo vjerne.
{26773}{26847}Zadržite ih.
{26940}{27002}Ne bih mogla.
{27043}{27094}Hvala.
{27098}{27147}Biste li...
{27163}{27262}Biste li veèerali | sa mnom? - Zašto?
{27303}{27419}Dobro. Može u srijedu | u 20:30 h? The Bell.
{27425}{27487}Preko puta. Bit æu tamo.
{27500}{27552}Mój broj.
{27598}{27709}Èita se 'Grilsh'. | - Anne Levels.
{27770}{27852}Zašto si gore | slikala, Anne Levels?
{27855}{27939}Za posao. Inženjerka sam.
{27963}{28017}Vidimo se u srijedu.
{28200}{28272}Jutros je u Engleskom | kanalu pronaðen mraèan teret.
{28278}{28359}Koèa koja je ribarila | 15 km od obale Suffolka
{28363}{28427}u svojoj je mreži | dovukla tijelo mlade žene.
{28433}{28542}Radi se o Mariji Vaughan | èiji je nestanak prijavljen
{28548}{28649}prije gotovo pet tjedana. | Policija je zapoèela istragu
{28655}{28752}te izjavila da koèa nije | rabila zabranjene mreže,
{28758}{28819}tijelo ne bi | nikada bilo naðeno.
{28880}{28939}Policiju.
{29660}{29717}Dobar dan, g. Grlscz.
{29760}{29822}Istražujemo umorstvo | Marie Vaughan.
{29843}{29887}Hvala što ste nam se javili.
{29985}{30124}Koliko razumijem bili ste | u vezi s gðicom Vaughan. - Da.
{30130}{30197}Smijem li pitati zašto niste | prijavili njezin nestanak?
{30220}{30289}Pri zadnjem susretu | smo se posvaðali.
{30295}{30382}Moralo je biti gadno kad | je otada niste potražili.
{30428}{30499}O èemu se radilo? | - Htjela se udati.
{30518}{30642}Za nekog drugog? - Za mene. | - Je li svaða bila nasilna?
{30673}{30732}Ne.
{30738}{30829}Je li bila žuèna? - Nije | se radilo samo o ženidbi.
{30863}{30944}Vidite, nisam više uopæe | htio nastaviti vezu s njom.
{30960}{31017}Zašto, gospodine?
{31023}{31144}Maria je bila vrlo | nesreðena, strastvena osoba.
{31173}{31319}Ljutita, nesretna. Ljubomorna.
{31330}{31397}Je li imala razloga | za ljubomoru? - Ne.
{31503}{31642}Vaša bivša djevojka poginula | je u automobilskoj nesreæi.
{31655}{31707}Prošloga listopada.
{31713}{31784}Dvije tajnovite smrti. | Strašna sluèajnost, zar ne?
{31860}{31937}Znate li kamo je gðica | Vaughan odlazila od vas?
{31953}{32052}Ne. - I svejedno se | htjela udati za vas? - Da.
{32273}{32364}Imate li kakve | tragove? Bilo što?
{32368}{32462}Još je rano. Još pokušavamo | složiti kakvu takvu sliku.
{32505}{32569}Željeli bismo proæi | neke datume s vama.
{32578}{32684}Recite ako trebamo razgovarati | s još nekim. - Dakako.
{32688}{32779}Još nešto. Ako biste | nam mogli pomoæi...
{32823}{32922}Nismo mogli pronaæi broj | vašeg socijalnog osiguranja.
{32925}{32997}Vaše ime ne daje nikakav broj.
{33020}{33092}Možete li nam ga dati?
{33613}{33672}Našao si me.
{33708}{33822}Zato si otkazala veèeru? | - Beton. Nov tip, vodootporan.
{33825}{33877}Temperatura | sušenja je kritièna.
{33880}{33959}Ako želiš posao obavljen... | - Puno posla, èini se.
{34153}{34197}Jesi li primijetila | u kineskim restoranima
{34200}{34274}što je hrana bolja to | su konobari mrzovoljniji?
{34348}{34402}Toliko o mom pokušaju | da te zadivim.
{34405}{34459}Trebao sam tražiti žlicu.
{34465}{34519}A gledaj tebe!
{34550}{34617}Djed mi je prièao | prièu o štapiæima.
{34663}{34754}Jednu je noæ Konfucije | sanjao da je u posjetu paklu.
{34763}{34869}Iznenadio se što je pakao | krasna sala za veèere,
{34875}{35027}a prokleti sjede okolo i jauèu | pod teretom najukusnije hrane.
{35030}{35084}Smjeli su jesti što god žele,
{35088}{35187}ali su morali rabiti | štapiæe dugaèke 1,5 m.
{35200}{35337}Prokleti su gladovali. Oèajno | su zurili u nepojedenu hranu
{35340}{35424}znajuæi da iako je pred | njima èitava vjeènost
{35428}{35542}neæe moæi riješiti problem. | Zatim Konfucije dolazi u raj.
{35545}{35697}Raj je isto tako blagovaonica | puna ukusne hrane.
{35703}{35787}Ljudi oko stolova | bili su sretni i siti.
{35793}{35857}No i oni su se morali | držati istoga pravila.
{35860}{35959}Smjeli su jesti samo | sa štapiæima dugim 1,5 m.
{35995}{36117}Samo u raju, | hranili su jedni druge.
{36248}{36309}Drži ih više. | Imat æeš veæu kontrolu.
{36438}{36519}Prièa moga života. Trèim | prije nego što sam prohodao.
{36868}{36947}Anne Levels je bila ovdje.
{38335}{38412}Anne Levels je bila ovdje.
{38580}{38679}Shvatite to ovako, g. Grlscz, | naši su mozgovi vrlo stari.
{38683}{38757}Neurolozi smatraju da | nitko nije posve èovjek.
{38763}{38834}Na nekoj razini | svi imamo èetiri noge.
{38840}{38924}Ispod te | svi imamo oštre zube.
{39003}{39012}Sigurno je bio Nissan Torrino? | - Kažem vam, mój zet ga ima.
{39115}{39242}Vraški skupa kanta. Pretjerano | ga hvale, ako mene pitate.
{39285}{39394}Pametan je. - Pardon? - Pravo | mjesto za odlaganje tijela.
{39405}{39542}Živi pijesak je u stanju | prekriti èovjeka za 20 min.
{39558}{39614}Ukoliko ga ne odnese struja.
{39620}{39702}Izbaci tijelo | i do 15 km na puèinu.
{39705}{39787}To je sve što mogu. Stari | sportski automobili su u redu,
{39793}{39869}ali motor je uglavnom uništen.
{39885}{39979}Ako ga želiš prodati prije | odlaska na novo putovanje,
{39985}{40067}morat æeš istresti barem 2000.
{40145}{40204}Upozorio sam te | kad si ga kupila.
{40210}{40259}Neki ljudi ne vole kad im | prijatelji kažu 'rekao sam ti'
{40263}{40332}ali ja sam se tome | kod tebe uvijek divila.
{40380}{40477}Onda, kad si poèela | kupiti muškarce na ulici?
{40480}{40537}Nisam ga pokupila.
{40560}{40627}Priznaj, muškarce baš | i ne znaš procijeniti.
{40653}{40724}Oèito, izašla sam s tobom.
{40800}{40867}Ne znaš ništa o njemu?
{40873}{40947}Znam onoliko koliko možeš | znati nakon tri tjedna.
{40953}{41029}No volim muškarca | koji je obavijen tajnom.
{41450}{41587}Nešto o meni? - Ideja. | Ako je odmah ne zapišem...
{41640}{41697}Divni su.
{41723}{41817}Zašto su tako mali? | - Ukrasni su. Iz 18 st.
{41825}{41894}Tradicija nalaže da se | daju djeci kada se rode.
{41968}{42049}Srebrne su. U Kini ih | obièno daruju prvom unuku,
{42053}{42109}što sam bila ja.
{42133}{42219}Znaèe da æe dijete | uvijek biti sito i sigurno.
{42333}{42414}Djed ih je kupio u Shangaju | od nekog prevaranta.
{42418}{42514}Rekao je da mijenjaju boju | u dodiru s otrovnom hranom.
{42548}{42617}Smatram ih svojim sreæonošama.
{42660}{42812}Puna si èudnih prièica | i izreka, zar ne? - Od majke.
{42945}{43009}Kada bih uèinila najmanju | pogrešku, èula bih kakvu prièu
{43015}{43089}o sudbini djevojka koje | ne namještaju svoj krevet
{43095}{43187}i kasne na èaj. Zato | ne sudim knjigu po koricama.
{43190}{43232}Nikada ne gledam | prije nego što skoèim.
{43238}{43299}Znam da je neke | stvari bolje prešutjeti,
{43303}{43409}a da je briga | vragu najdraža zabava.
{43458}{43527}To još nisam èuo. - O vragu?
{43545}{43619}Sjedila bih u kutu i | ljutila se i eto prièice.
{43650}{43699}Izgledaš lijepo.
{43758}{43824}Zar se ne kaže 'uvijek | gledaj prije nego što skoèiš'.
{43828}{43879}Što sam ja rekla? - Nikad.
{43915}{43989}Èini se da je kap. | Birdsey bio u pravu.
{43993}{44092}Samo dvije tvrtke | iznajmljuju Nissane diesele.
{44103}{44199}Veæ u prvoj koju sam | nazvao znali su koga tražim.
{44205}{44267}Znali su da je unajmitelj | imao lažnu osobnu
{44270}{44329}jer su ga pokušali | naæi zbog kazne.
{44353}{44459}Slušajte ovo, | našem ubojici se žurilo.
{44505}{44554}Dobro.
{44563}{44679}Poveæajte ovaj dio. Èim prije.
{44705}{44759}Dobro.
{44788}{44839}Èestitam, nar. Roche.
{44845}{44927}Veæ dugo nisam vidio | tako dobro obavljen posao.
{44933}{44994}Nema na èemu. Samo | radim svoj posao.
{44998}{45097}Jeste li provjerili ono | s osiguranjem S. Grlscza?
{45100}{45184}Jesam. Krivo su napisali. To | je sve. Ništa èudno, zar ne?
{45190}{45279}Trebalo bi zabraniti | prezimena bez samoglasnika.
{45295}{45389}Žena ima trudove veæ 27 sati. | Dosta joj je, preko glave.
{45393}{45529}Želi kuæi. - Nisam | naruèio školjke. - Vrati ih.
{45570}{45684}Tko ne riskira, ne profitira. | - Babica joj priðe i kaže,
{45690}{45842}Gðice Fitzpatrick, radi se | o vašoj krvi. B pozitivna.
{45920}{45977}Probaj ovako.
{45998}{46114}Prièaj mi kako si | upoznao Anne. Crtao si je.
{46118}{46167}Kako romantièno.
{46173}{46309}Ili je to samo dobar nastup. | - Tako je, dobar nastup.
{46420}{46514}Anne nam je pokušala reæi što | radiš, ali nije bila jasna.
{46523}{46652}Medicinski istraživaè. | Rješavam probleme.
{46655}{46732}Ne govorimo o medicini. Dosta | mi je toga dok sam s Martinom.
{46738}{46829}Prièaj mi o svom prezimenu. | Nisam još èula takvo.
{46835}{46884}Bugarsko je.
{47005}{47087}Grilsh.
{47098}{47182}Bože, ne bih ga | znala proèitati.
{47205}{47289}Znaèi, tako vam loše ide | da nemate ni za samoglasnike.
{47295}{47382}Definitivno. Ako hoæeš 'a', | moraš spavati s naèelnikom.
{47490}{47577}Ako neæeš to | pojesti, Anne, ja æu.
{48003}{48092}Ne moraš iæi sa mnom. | Svakoga dana idem sama.
{48110}{48182}Ne mogu te pustiti | kuæi samu. - Možeš.
{49135}{49224}Fotogenièan si. Šteta | što ne možeš dobiti jednu.
{49230}{49294}Trebat æe mi. Volim | voditi evidenciju.
{49310}{49389}Odjebite, policajac sam.
{49715}{49782}Otišao bi?
{49830}{49902}Mój prijatelj | ne voli policajce.
{49915}{50039}A kažem mu da vi štitite | graðane od ljudi poput nas.
{50258}{50324}Ja krivim nasilje na TV-u.
{50330}{50449}Vidite, policajèe, kada je | netko prijetnja društvu,
{50453}{50569}nema s njim razgovora. Zar ne?
{50638}{50749}Pardon, mogu ti | pomoæi? - Ne bih rekao.
{50768}{50852}Je li ti on deèko? | - Prati me veæ dva dana.
{50858}{50962}Doista? Zašto bi te pratio? | - Misle da sam nekog ubio.
{51083}{51152}Jesi li? - On tako misli.
{51183}{51259}Ako ga sredimo, dugo | vremena neæe nikoga pratiti.
{51268}{51352}Želiš nešto znati? | U velikoj si nevolji.
{51383}{51449}Poslat æe nekog drugog. | Policajci su uporni.
{51453}{51509}Osobito s onima | koji ih ubijaju.
{51515}{51589}A morat æete | ga ubiti, zar ne?
{51660}{51749}Teško da je toga vrijedan. | A morat æete ubiti i mene.
{51788}{51884}Zašto misliš da neæu? | - Nisi glup.
{51968}{52032}Jednom smo ga udarili. | Ionako æe nas tražiti. - Neæe.
{52038}{52174}Ako kaže da je napadnut, ja | æu reæi da je on prvi napao.
{52593}{52659}Znate mi ime | i znate gdje živim.
{52678}{52772}Jebeš ih. Imamo novac. | Sredimo ih! - Ne.
{53023}{53107}Ma jebeš to. Obièno sranje.
{53128}{53204}Njegov socijalni radnik | kaže da si ne može pomoæi.
{53265}{53332}Narednik picoliki je tvoj.
{53373}{53414}Imaš sreæe.
{53433}{53494}Ali ti to veæ znaš.
{53793}{53849}Mój križ. - Idemo.
{54020}{54139}Žao mi je. - Ma ništa. | Hvala. Zahvalan sam.
{54188}{54254}Veèeras sam se prisjetio | zašto ne idem podzemnom.
{54265}{54332}Donosi lošu sreæu. | - Znam na što mislite.
{54395}{54449}Problem je što nikada | ne mogu dobiti taksi.
{54553}{54634}Nepošteno lice, ha? | - Javit æu vam.
{54658}{54714}Govorio sam o svom licu.
{54753}{54819}I ja.
{54853}{54954}Zašto vam je križ | bio toliko važan?
{54995}{55044}Dar od žene.
{55063}{55187}Katolik sam... | u stvari postat æu.
{55213}{55274}Obraæam se, znate.
{55308}{55369}Hvala na pomoæi.
{55483}{55587}Kada me opet budete pratili, | možete mi platiti piæe.
{57318}{57429}Prijeði put i sva mjesta | gdje je mogao stati.
{57435}{57594}Možda se netko neèeg sjeæa. | Tko god bio, sreæa mu istjeèe.
{57710}{57782}Evo. Stavi ovo.
{57890}{57952}Vaša pregaèa, g. Grlscz.
{58008}{58067}Gledaj me u oèi.
{58158}{58222}Jesi li dobro?
{58998}{59092}Gotovo je. Bravo.
{59738}{59792}Njuškalo!
{59800}{59907}Što je to? - Kristali iz | ljudskih bubrega i mjehura.
{59943}{60049}Istražujem ekstremna emotivna | stanja za zakladu Wellcome.
{60053}{60127}Ona katkad uzrokuju da tijelo | proizvede ovakve kristale.
{60215}{60299}Moglo bi se reæi da je | ovo bijes, ovo ogorèenje,
{60303}{60422}zloba, ljutnja, zavist, | a ovaj veliki je mrzovolja.
{60463}{60592}Èula sam da je vrlo bolno | dok izlaze. - Vrlo, kažu.
{60633}{60682}Idemo li?
{60695}{60696}Što ti je bilo s prstom?
{60763}{60859}Porezao sam se spašavajuæi | psiæa od utapanja.
{61340}{61404}Tri moja deèka su | u istražnom zatvoru
{61408}{61532}zbog tvog inspektora. | Neæemo više biti fini.
{61618}{61687}Gðo O'Grady. | - Ja im svoj novac ne dam.
{61770}{61824}Moderna žena.
{61880}{61962}Nema veze s ovim. Pustite je.
{62005}{62169}Pustit æu te. Samo mi | trebaš dati svoju ženu.
{62193}{62422}Što? - Jednostavno je. | Daj mi je i možeš iæi.
{62525}{62597}Ionako æu je uzeti.
{62780}{62869}Idi... tamo.
{64308}{64384}Bježi.
{68800}{68922}Poznavao sam jednog | neurologa koji je govorio
{68928}{69029}da nemamo | jedan mozak, veæ tri.
{69045}{69144}Prvi je ljudski, ispod | njega je mozak sisavca,
{69150}{69214}a ispod njega mozak reptila.
{69293}{69437}Znaèi kada ti psihijatar | kaže da legneš na kauè,
{69443}{69594}u stvari liježeš | s konjem i krokodilom.
{69783}{69897}Spavaj. - Nisam umorna.
{69975}{70062}Dobro, ostani budna. | Ja idem spavati.
{70233}{70292}Nemoj gledati.
{70433}{70549}Jesi li ikad nešto ukrao? | Ja sam ukrala ovaj sat.
{70588}{70667}Kradljivica si? | - Kad mi je bilo 14 godina.
{70713}{70817}Ako se misliš predati | policiji, èekat æu te.
{70843}{70937}Strašno sam ga željela. | Tjednima sam ga vrebala.
{70940}{71034}Jednom sam ušla u trgovinu | i zatražila neke sitnice.
{71055}{71147}Kad se vlasnik okrenuo, uzela | sam sat i stavila ga u džep.
{71180}{71294}Iako sam imala novca. Dan | danas ne znam zašto sam ga
{71300}{71394}toliko htjela da me | od toga bolio želudac
{71398}{71487}i zašto ga nisam | htjela platiti.
{71535}{71634}Reci mi je li to uèinio | konj ili krokodil?
{71818}{71872}Zašto si ga zadržala?
{71893}{71979}Da me podsjeæa | na moju sramotu.
{72133}{72307}Bio si vrlo drag | prema onoj djevojèici.
{72665}{72762}Hvala ti što si me spasio.
{73615}{73682}Što još možemo?
{73720}{73782}Dalje je sve nizbrdo.
{73795}{73879}Možda nešto... - A što to?
{73885}{73979}Ostavit æemo to u rezervi za | onda kada ti postanem dosadan.
{74043}{74117}Želim znati.
{74150}{74239}U školi sam naplaæivao | 6 penija da bih ovo radio.
{74245}{74312}Nemam 6 penija.
{74553}{74609}Ostani tamo.
{74765}{74832}Ostani.
{75278}{75372}Tko to izranja iz divljine | poput stupa od dima?
{75378}{75457}Obavijena mirisima | mirte i tamjana?
{75460}{75534}Spoj tvojih bokova | je poput dragulja.
{75540}{75609}Djelo spretna umjetnika.
{75618}{75674}Èitaj ti.
{75725}{75834}Usnice su ti poput grimizne | vrpce, a usta dražesti puna.
{75838}{75902}Dah tvoj jabukama odiše.
{75905}{75979}Grudi su tvoje | poput dva grozda.
{75995}{76059}Lijepa si sva, ljubavi moja.
{76073}{76132}Mane nijedne nemaš.
{76278}{76337}Taksi. - U redu je, g. Grlscz.
{76340}{76402}Idem u vašem smjeru. | Odbacit æu vas.
{76740}{76844}Uredi da g. Grlscz vidi | svjedoka prije ulaska.
{76883}{76937}Zgodno.
{77050}{77107}Za mnom, g. Grlscz.
{77285}{77362}Nije lako raditi | u naplatnoj kuæici.
{77373}{77442}U prosjeku na tjedan | vidiš 10.000 ljudi.
{77448}{77517}Na praznike i | dvostruko više. 20.000.
{77520}{77582}I zamislite, | nijedan nema toèan iznos.
{77738}{77779}Bez brige, | ne vide kroz staklo.
{77783}{77839}Ako nekog želite pogledati | izbliza, recite broj
{77843}{77892}i zatražit æemo ih | da istupe naprijed.
{77925}{77997}Moram istaknuti da osoba koju | ste vidjeli možda nije ovdje.
{78038}{78104}Možete li skinuti naoèale?
{78708}{78794}Broj šest. - Hoæete reæi | da se radi o broju šest?
{78798}{78854}Ne, želim ga bolje pogledati.
{78915}{78977}Istupi naprijed broj šest.
{79243}{79357}Neka se vrati na mjesto. | - Vratite se natrag, broj 6.
{79538}{79627}Broj devet. - Istupi, broj 9.
{79910}{80014}Opet broj šest. | - Naprijed, broj šest.
{80358}{80477}Broj devet je. - Sigurni ste? | - Narednièe Roche.
{80485}{80579}Nisam siguran. Na tjedan vidim | 10.000 ljudi, što oèekujete?
{80600}{80652}Izgledate mi poznato, | možda ste vi.
{81043}{81109}Hvala, gospodo. Možete iæi.
{81453}{81564}Niste mek policajac. | - Ne, prije ljubazan.
{81650}{81712}Hoæete vi? - Ne, hvala.
{81765}{81827}Volio bih rašèistiti | neke stvari.
{81908}{82049}Posjetnica koju ste dali | nasilnicima kad ste...
{82055}{82104}Kad sam vam spasio glavu?
{82270}{82392}Zašto imate posjetnicu | na drugo ime? - Nemam.
{82398}{82477}Netko mi ju je dao. Medicinski | dobavljaè, Jeremy O'Grady.
{82510}{82589}G. O'Grady se mogao | gadno iznenaditi.
{82595}{82659}Oèito nisam razmišljao | o svim posljedicama.
{82673}{82732}Oèito.
{82818}{82884}Kada bolje razmislim...
{82928}{82987}Mogao sam im dati | da vas dokrajèe.
{83245}{83352}Teško je, zar ne? | Postupiti ispravno.
{83468}{83532}Mogu li...
{83705}{83839}Ova posjetnica | i broj su izvan uporabe.
{83855}{83949}A imate kuæni broj.
{83990}{84112}Èudno, zar ne? | Sitnica, ali èudna.
{84333}{84399}Tako osvajam žene.
{84423}{84512}Èesto to radite? | - Ne èesto. Jednom na mjesec.
{84525}{84584}Rekao bih da je to èesto.
{84613}{84669}Date im karticu | i èekate da vas nazovu?
{84673}{84784}Više-manje. - Više ili manje?
{84818}{84877}Ovisi o okolnostima.
{84890}{84987}Dam im posjetnicu i kažem | da to inaèe ne radim.
{85008}{85109}A broj? - Služi | samo za to. - Zašto?
{85113}{85199}Tako znam tko zove | kada nazove. - Objasnite.
{85230}{85322}Katkad telefon zazvoni | a s druge strane je tišina.
{85328}{85439}Samo moram reæi: 'Ti si, | zar ne? ' I uvijek jest.
{85598}{85729}Èudno zvuèi kad se kaže | na glas. Djeluje... - Zlokobno.
{85738}{85837}Mislio sam reæi jeftino.
{85858}{85914}Biste li mi vjerovali kada bih | rekao da sam prestao s tim?
{85920}{85977}Hoæete li mi to reæi? | - Hoæu. - Zašto?
{85990}{86092}Moram li odgovoriti? - Ne.
{86305}{86419}Zanimljivo. - Je li? - Nisam | priznao ništa nezakonito,
{86425}{86504}ali sam priznao da sam | dva puta bio zloèest.
{86520}{86594}Možda ste promašili | svoj životni poziv.
{86625}{86682}Ne bih rekao.
{86688}{86774}Sveæenik vas sasluša | da biste bili spašeni.
{86778}{86842}Policajac vas sluša da | bi vas uvalio u nevolju.
{86863}{86957}Znaèi, u nevolji sam? | - Imali ste putovnicu kod sebe.
{86960}{87062}Nekamo ste krenuli? | - Otvarao sam bankovni raèun.
{87118}{87212}Rado bih je zadržao ako | vam ne smeta. - Smeta mi.
{87230}{87304}Svejedno bih je zadržao.
{87735}{87792}Ovdje sam.
{88130}{88212}Ne, prestani! | - Što je? - Ništa.
{88218}{88282}Ništa? - Ne volim | što me stalno mrcvariš.
{88298}{88387}Pipkaš me kao da sam... | Ne želim da to radiš.
{88393}{88449}Nisam mislio da to | radim. Žao mi je.
{88518}{88582}Neæu više.
{88753}{88924}Dan je bio naporan. | Oprosti. Problemi na poslu.
{89060}{89134}Nema isprike što sam | se iskalila na tebi.
{89228}{89319}Vrijedi li dogovor za subotu | s Martinom i Karen? - Da.
{89323}{89404}Dobro. - U stvari, | možemo li prestati? - Što?
{89408}{89507}Ne mogu ovako brzo prihvatiti | ispriku dok sam još ljut.
{89533}{89637}Ne možeš se izvikati | i odmah isprièati. Shvaæaš?
{90013}{90084}Dar za mene? - Ne.
{90393}{90479}Sumnjam da bi me nacrtao | ovako spokojnu da sada crtaš.
{90640}{90787}Sada znaš kakva sam doista. | Što æeš sa mnom? - Idem.
{90820}{90874}Ne moraš iæi.
{90895}{90982}Ne, moram iæi. Nazvat æu te.
{91093}{91182}Glupo, glupo.
{91395}{91477}Tko to izranja iz divljine | poput stupa od dima?
{91485}{91559}Obavijena mirisima | mirte i tamjana?
{91580}{91637}Sva si lijepa, ljubavi moja.
{91645}{91717}Nema na tebi mane.
{91790}{91847}Voliš li ga?
{91893}{91977}Ne znam razumijem li ga. | Što se dogaða u njemu.
{91998}{92124}Ne znam zašto... Vjerojatno | sam ja kriva. Nešto krije.
{92138}{92222}Što to? - Nikada nisam | bila u njegovom stanu.
{92268}{92419}Promatra ljude. Zapisuje | u male, crne bilježnice.
{92425}{92479}I savršen je.
{92560}{92659}Znam, majka je govorila | da nikada nisam zadovoljna.
{93775}{93887}Stevene, Anne je. | Nazovi kada se vratiš.
{94028}{94187}Srijeda, 11:11 h. - Anne je.
{94223}{94279}Jesi li dobro?
{94290}{94339}Radi se o...
{94345}{94469}Žao mi je zbog onih rijeèi. | Volim kako me dodiruješ.
{94500}{94547}Nazovi me.
{94968}{95029}Anne Levels.
{95205}{95309}Ja sam jedan od | vrste, Anne. Biæe.
{95335}{95402}Krokodil koji treba posao.
{95413}{95509}Koji treba bankovni | raèun. Mjesto za život.
{95550}{95609}Ja sam pogreška.
{95675}{95799}Moraš se ponovno roditi | u duhu. Želiš li biti kršten?
{95860}{95937}Želim.
{96100}{96174}Krstim te u ime Oca...
{96233}{96362}Sina i Duha Svetoga.
{96570}{96667}Iskreno, doista ne mogu reæi | da mi je drago što vas vidim.
{96715}{96792}Možemo li negdje razgovarati?
{96865}{96949}Radeæi ovaj posao nauèite da | istina nije uvijek vjerojatna.
{96963}{97059}Dosad ste vi bili | posve vjerojatni.
{97083}{97177}Bili ste uvjerljivi, | ali ja nisam bio uvjeren.
{97233}{97314}A sada jeste. - Maria | Vaughan se pokušala ubiti.
{97320}{97367}Zašto mi niste rekli | da ste joj spasili život?
{97370}{97429}Nisam to tako gledao.
{97545}{97619}Moram vam reæi, g. Grlscz,
{97660}{97749}da više niste osumnjièeni | u našoj istrazi.
{97825}{97952}Zašto? - Veæina bi se složila | da nije baš vjerojatno
{97955}{98029}da prvo nekom spasite | život, a zatim ga ubijete.
{98068}{98147}To što sam Mariji spasio | život ništa ne dokazuje.
{98165}{98299}Možda dokazuje da ste | u srcu dobar èovjek. - U srcu?
{98415}{98534}Znate li što je vaš problem? | - Ne, recite. - Dobro i zlo.
{98590}{98749}Zlo nije samo zloba... | umorstvo silovanje i slièno.
{98758}{98854}Vrag je prije svega | bio otac lažaca.
{98865}{98944}Laži koje govorite | i istina koje prešuæujete.
{98950}{99039}Sve skriveno jest kraða. Sve | što krijemo od voljenih osoba
{99045}{99124}èini prijevaru. A uvijek | nešto krijemo, zar ne?
{99130}{99209}Poznavao sam javne ljude koji | nisu bili pretjerano iskreni.
{99225}{99382}Svi žele da zli budu negdje | drugdje i tamo èine zlodjela.
{99405}{99499}Tako ih se može odvojiti | od obiènih ljudi i uništiti.
{99545}{99652}Ali linija koja razdvaja dobro | i zlo prolazi ljudskim srcem.
{99703}{99789}A tko je spreman | uništiti dio svoga srca?
{99858}{99959}Znate to, zar ne? | Trik tajnog policajca.
{99978}{100042}Kako to mislite? | - Izazivate me sigurnošæu.
{100058}{100152}Nije loša zamisao. No bojim | se presuptilna za mene.
{100263}{100332}Jeste li oženjeni? - Jesam.
{100355}{100442}Isprièajte mi kada ste | zadnji put lagali ženi.
{100463}{100522}Bit æemo jedan-jedan.
{100640}{100762}Neku veèer smo bili na veèeri. | Imali smo godišnjicu braka...
{100798}{100912}U jednom trenutku misli | su mi odlutale, kao i obièno.
{100933}{101052}Ona me trgnula pitanjem | 'Što mislim? '. Rekao sam joj.
{101063}{101204}Mislio sam kako dobro izgleda | i kako je još uvijek lijepa.
{101218}{101299}Da mi je ugodno i da bismo | to trebali èešæe raditi.
{101305}{101402}Lagali ste? - Ne, | rekao sam istinu.
{101410}{101519}Ali misleæi kako je | lijepa i kako mi je ugodno,
{101523}{101672}razmišljao sam i o mladoj ženi | na drugoj strani restorana.
{101698}{101747}Bila je lijepa.
{101755}{101817}Zgodnièka, rekao bi mój otac.
{101848}{102022}No više od svega me se dojmio | njezin predivan smiješak.
{102100}{102257}Jesam li to trebao reæi ženi? | - Bi li je to uzrujalo? - Da.
{102295}{102407}Znaèi, istina, samo istina i | ništa do istine, nije istina.
{102848}{102924}Neke je stvari | bolje prešutjeti.
{102930}{103042}Hvala nije jedna | od njih. - Hvala.
{103622}{103739}Uèinite nešto!
{104097}{104194}Dajte mi nož. Dajte mi nož. | - Što? - Samo mi daj nož.
{104255}{104326}Što radiš? - Moram otvoriti | dovod zraka. - Ubit æeš ga.
{104332}{104376}Ionako æe umrijeti.
{106325}{106396}Usnice su ti poput | grimizne vrpce.
{106465}{106549}Nema na tebi mane.
{106790}{106979}Znaèi živ si. Pomislila sam | da me izbjegavaš. Je li?
{107017}{107096}Skrivao sam se. - Od mene?
{107125}{107219}Da. - Zašto? - Ne znam.
{107250}{107326}Mislio sam na tebe. | - Nešto dobro ili loše?
{107345}{107454}Previše. - Želim doæi k tebi.
{107487}{107569}Zašto? - Nedostaješ mi.
{107642}{107754}Naðimo se u 'Pelicanu'. - Ne! | Želim vidjeti gdje živiš.
{107870}{107966}Kako želiš. - Vidimo se uskoro.
{109337}{109396}Za tebe.
{109770}{109849}Znaèi ovdje se skrivaš?
{112337}{112459}Ne boj se. - Ne, ne.
{112547}{112681}Vratit æu se ovamo. | Otvorit æu vrata.
{112907}{112959}Umrijet æu.
{113005}{113061}Za dva tjedna, možda tri.
{113095}{113246}Tijelo mi posustaje. | Krvarim. Više ne zarastam.
{113315}{113439}Trebam krv. Trebam ljubav | koja teèe tvojom krvi.
{113650}{113719}Ono što sad | osjeæaš prema meni.
{113725}{113894}U grlu, prsima, u krvi. | Nešto gotovo opipljivo.
{113920}{114059}Sjeæaš se kristala? Bijes, | zloba, razoèaranje. Oèaj.
{114110}{114306}Osjeæaji su stvari. Tvoja | krv nosi sve što osjeæaš.
{114492}{114554}Samo želim osjeæati.
{114705}{114821}Hranim se ljubavlju. To jedem.
{114855}{114931}Svaki put kada nekog uzmem, | uzimam sve što osjeæaju.
{114937}{115051}Sve zamjerke. | Zlo mi je od toga.
{115115}{115301}Kada bih našao pravu ženu, | kada bi me savršeno voljela,
{115415}{115476}tada bi to prestalo.
{115570}{115654}Mislim.
{115690}{115786}Hoæeš reæi da si | zbog toga ubijao?
{116625}{116714}Jedna posjekotina i | iskrvarit æu za 20 minuta.
{117275}{117359}Kljuèevi su na stolu.
{117672}{117769}Ovakvo stanje nije ugodno.
{117802}{117864}Ne djeluje.
{117957}{118019}Nemaš spokoja.
{118037}{118094}Ni mira.
{118097}{118204}Sve što radiš, što ne radiš. | Sve što drugi rade. Zašto?
{118207}{118296}Što ona radi? Što voli? | Što ne voli? Sve je važno.
{118300}{118344}Stalno je sve važno.
{118347}{118384}Ne mogu ni zaspati | da ne bih prestao disati.
{118390}{118454}Moram se podsjeæati da dišem!
{118720}{118829}Ne vjerujem ti. - Vjerovala | ili ne, nije važno.
{118940}{119004}Umrijet æu.
{119132}{119196}A ti æeš živjeti.
{119337}{119406}Jer sam shvatio | da bi mi nedostajala.
{119480}{119559}Da te volim.
{119680}{119749}Tako sam umoran.
{121400}{121516}Astmatièarima nije bilo | pomoæi kada sam bila dijete.
{121572}{121651}Majka je znala cijele | noæi ležati uza me,
{121660}{121731}kada mi je bilo doista | loše i nisam mogla disati,
{121775}{121871}i satima mi je gladila kosu.
{121920}{121976}Bdjela je nada mnom.
{123755}{123804}Ne vidim.
{124460}{124656}Što je? Osjeæaš nekakav | miris? Aroma kruške.
{124775}{124879}Aceton miriše poput kruške.
{124955}{125044}Tijelo proizvodi aceton | kada samo sebe izjeda.
{125132}{125191}Zašto si još ovdje?
{125330}{125401}Voliš li me?
{127532}{127606}Ostao sam bez flastera.
{127630}{127694}Idem do ljekarne.
{127700}{127794}Ne budi smiješan. Idem ja. | Ne izgledaš dobro. - Sigurno?
{127812}{127866}Stanje se pogoršava, zar ne?
{127912}{127989}Stižem za 15 minuta.
{131452}{131509}Znam što si.
{131530}{131584}Ne volim te.
{131600}{131676}Možda ne srcem, ali | ljubav ti je još u krvi.
{131947}{132021}Je li ti žao?
{132042}{132201}Kakve god mane imao, | svakako nisam zloban.
{135475}{135531}Kada sam bio djeèak...
{135537}{135679}Pao sam s drveta. Ali uspio | sam se uhvatiti za granu.
{135717}{135794}Dugo sam užasnut visio ondje.
{135860}{136059}Tišina od boli u rukama. | I tutnjanje krvi u ušima.
{136110}{136216}A zatim sam pao.
{136267}{136389}Ne sjeæam se što se dogodilo | kada sam udario o zemlju.
{136435}{136551}Samo se sjeæam | agonije držanja...
{136585}{136646}I divnog osjeæaja...
{136735}{136789}Predivnog osjeæaja...
{136820}{136889}Prepuštanja.
{136890}{137090}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan  
