{1}{1}25.000
{715}{824}SJEVERNA AFRIKA 1946. g.
{1972}{2106} MLADI CRNI PASTUH 
{7479}{7529}Problemi, Kadire?
{7531}{7628}Gdje je Mansoor, uvijek ima nevolja.
{7630}{7725}Ako mu platimo, | nadam se da æe se sve biti u redu.
{7939}{7985}Neera!
{8005}{8065}Samo sam gledala.
{8875}{8962}- Zbilja nisam umorna. | - Zaustavit æemo se kod planine.
{8964}{9036}Sigurnije je.
{9038}{9142}Sanjala sam dom. | Ondje je prelijepo, poput palaèe.
{9144}{9232}Krasni pašnjaci | za konje moga djeda.
{9234}{9368}Najbolji su u èitavoj dolini. | Pobjeðuju na svakoj utrci. Skoro na svakoj.
{9370}{9442}Tvoj je djed važna osoba,
{9444}{9566}ako uzgaja nepobjedive konje | i živi u palaèi poput kralja.
{9568}{9687}Nije me htio poslati od kuæe, ali je | mislio da je tako sigurnije dok rat traje.
{9689}{9786}Život je nepredvidljiv | poput pijeska na vjetru.
{9879}{9930}Što je?
{9956}{10020}Što nije u redu, Kadire?
{10072}{10129}Mansoor.
{10255}{10308}Pokušaj se spasiti.
{10310}{10380}Kreni prema zapadu, | slijedi planine i stiæi æeš kuæi.
{10382}{10473}Nemoj se zaustaviti | i nemoj se osvrnuti. Idi! Idi!
{10475}{10538}- A ti?! | - Idi!
{16666}{16709}Dobar deèko.
{16788}{16823}Èekaj!
{16990}{17034}Vrati se!
{18738}{18867}Hej, kamo si krenuo? | Èekaj me!
{19930}{19985}Dat æu ti vode.
{22039}{22097}Vranèe!
{22818}{22882}Dobar deèko.
{22884}{22974}Zajedno æemo pronaæi put kuæi.
{25799}{25880}Moramo dalje.
{25882}{25957}Mislim da smo blizu. | Nadam se.
{26496}{26586}Stigli smo! Evo doma! Idemo!
{27717}{27770}Mirno! Smiri se!
{27772}{27847}Stani! Vrati se! | Nemoj me ostaviti!
{27909}{27951}Vrati se!
{28032}{28084}Vranèe?
{28661}{28716}Ima li koga?
{28937}{29024}- Adene? | - Neera? Jesi li to ti?
{29026}{29088}Mislili smo da si mrtva.
{29090}{29177}Ne, to sam ja, | glavom i bradom. Vidiš?
{29179}{29293}- Hoæeš li me potjerati? | - Nisam mislio da si ti.
{29295}{29418}Èuli smo da su napali povorku. | Nisam oèekivao da æu te opet vidjeti.
{29420}{29492}- Gdje su ostali? | - Pobjegli su.
{29494}{29561}- Zar svi? | - Ostali smo Ben Ishak i ja.
{29833}{29930}- Je li on dobro? | - Katkad ga èujem kako plaèe.
{29987}{30026}Odlazi!
{30127}{30204}Ostavi me na miru. | Èuješ li me? Odlazi!
{30225}{30294}Ali to sam ja, djede.
{30723}{30826}Da mi nije pomogao, odustala bih. | Ne bih stigla dovde.
{30828}{30952}U pustinji se vrag poigrava s nama.
{30954}{31063}Te nam se prièinja.
{31065}{31199}Ali on je zbilja stvaran. | Jak je i brz. Moramo ga pronaæi.
{31258}{31344}Crni konj je varka.
{31346}{31439}On postoji samo u tvojoj glavi, i u srcu.
{31457}{31510}Zaboravi ga.
{32097}{32206}Nije li konj ispred ostalih Kazir?
{32208}{32345}Kazir više nije naš, | poput svih ostalih.
{32347}{32413}Raspršili su se.
{32415}{32549}Rhamon je uzeo Kazira i veæinu kobila.
{32551}{32652}- Bili su poput obitelji. | - Nismo imali izbora.
{32654}{32774}Stigli su vojnici s tenkovima, | s bombama i sve uništili.
{32776}{32900}Sve je izgorjelo. | Sve je uništeno.
{32902}{32980}Nismo ih više mogli hraniti. | Morali smo ih prodati.
{32982}{33034}I Ginu?!
{33036}{33111}Pomisao da je netko drugi posjeduje,
{33113}{33191}nisam mogao podnijeti.
{33193}{33272}Zato sam je pustio u pustinju | kojoj je pripadala.
{33274}{33392}Neki su ljudi pomislili da je bilo glupo, | no znam da sam pravilno postupio.
{33394}{33480}Više nismo uzgajivaèi. | Neka tako bude.
{33482}{33556}No imamo krov nad glavom.
{33558}{33623}Sretniji smo od veæine ljudi.
{33625}{33685}Zadržali smo Abu.
{35723}{35790}- Sjeæaš se pjesme? | - Možda.
{36782}{36867}Salaam alaika, Ishak. | Trebate pomoæ?
{36869}{36952}Snaæi æemo se.
{36954}{37040}Kazir izgleda dobro, zar ne?
{37042}{37124}Trebao si doæi na utrke. | Pobijedio je.
{37126}{37225}Mansoor je bio prezaposlen kraðama | pa nije doveo Radana,
{37227}{37310}tako da nije bio veliki izazov. | Nitko ga nije mogao ugroziti.
{37312}{37430}No, svidjele su mi se nagrade. | Možda koju i prepoznaš.
{37432}{37512}- Sve ih je dobio? | - Nova pravila.
{37529}{37637}Svi ponude najbolju kobilu, | a pobjednik ih dobiva sve.
{37639}{37725}Sretan si što si dobio | ove dobre konje.
{37727}{37795}Tvoj æe ugled | zbog toga porasti.
{37797}{37871}Èuo sam da je Mansoor ulovio | tvoju kobilu Ginu.
{37873}{37960}No nije uspio uloviti | crnoga konja koji je bio s njom.
{37962}{38042}Možda je nestao u Tajnoj dolini.
{38044}{38122}Da si je zadržao, | mogao bi obnoviti krdo.
{38124}{38216}Naprotiv, što ti je ostalo? | Ovaj konj...
{38218}{38359}Nade velikog Ben Ishaka | ostaju na ovom jadnièku.
{38405}{38501}Nemoj biti pustinjak, starèe. | Doði na utrke iduæe godine
{38503}{38580}svjedoèiti Kazirovoj | stotoj pobjedi za Rhamonovo pleme.
{38582}{38666}Vidimo se ondje.
{38947}{39001}Djede...
{39037}{39091}Jesi li ga èuo?
{39093}{39176}To je sigurno on. | Moje ždrijebe. Ginin sin.
{39178}{39232}To su samo glasine, Neera.
{39234}{39322}Ako ga pronaðemo, | možemo poèeti ispoèetka.
{39324}{39412}Obnovit æemo krdo. | Opet imati konje, kao nekada.
{39414}{39497}Puna si planova.
{39499}{39649}Podsjeæaš me na majku. | Hrabra i neustrašiva. Voljela je svoje konje.
{39651}{39720}Razumjela je njihove osjeæaje.
{39722}{39794}Jahala je kao | da je roðena na konju.
{39796}{39859}Bila je bolja | od veæine muškaraca.
{40251}{40348}GODINU DANA KASNIJE
{44969}{45055}Doði... Dobar deèko.
{46297}{46345}Ben Ishak!
{46361}{46492}Stigla je Neera! | Nije sama!
{46550}{46607}Brzo, doðite!
{46641}{46732}Što to radiš, Neera? | Jesi li poludjela?
{46734}{46839}To je on, djede! | Nije san, on je stvaran. Ktomu i brz.
{46841}{46929}- Mogla si se ozlijediti. | - On mi ne bi nikada naudio.
{46944}{47044}Ima vatreno srce, Neera!
{47123}{47154}Smiri se.
{47156}{47300}Može potuæi Kazira. | Znam da može pobijediti. Zbilja može!
{47302}{47401}Ako i jest tako dobar kao što kažeš, | vrijeme utrka je blizu.
{47403}{47479}Nemamo vremena za vježbanje, | a nemamo ni džokeja.
{47481}{47572}Ja æu ga jahati. Mene sluša. | Uèinit æe što mu naredim.
{47574}{47646}Divlji je.
{47648}{47735}A ti si samo curica.
{47737}{47824}- Nije pravedno. | - Znaš li koliko je opasan?
{47826}{47923}Ne želim više nikoga izgubiti, jasno?
{47925}{47993}Neæu to dopustiti. | Zabranjujem ti to.
{48186}{48306}- Moraš mi pomoæi. | - Šališ se? Reci mi da se šališ.
{48308}{48403}Odsad je to naša tajna. U redu?
{49225}{49295}Nemoj ubrzati | dok ne proðeš kraj mene.
{49297}{49381}Polako. Prièekaj moj znak.
{49403}{49448}Priprema...
{49450}{49490}Pozor...
{49507}{49570}To nije polako!
{49626}{49696}Rekoh, polako!
{50691}{50741}Gina.
{51884}{51952}- Gdje je? | - Ne znam.
{52107}{52175}Daj opet!
{52504}{52554}Moramo požuriti.
{52816}{52866}Gina...
{52930}{52984}Sjeæaš me se?
{53606}{53693}Ovo je utrka, ne bitka!
{53983}{54084}Prièekajte nas! Mjesta!
{54086}{54139}Stižemo!
{54340}{54415}Polako, stani!
{54417}{54555}Pleme Ben Ishaka ponosno najavljuje | službeno sudjelovanje pastuha Shatana.
{54557}{54713}A upisnina? Što nudite? | Zar ovu staru i nemoænu kobilu?
{54742}{54859}Sigurna si u to što èiniš? | Što ako izgubi?
{54861}{54940}Neæe izgubiti. Reci im to.
{54942}{55055}Kao upisninu nudimo | našega najboljega konja -
{55057}{55124}pastuha Shatana.
{55126}{55233}Trebate ponuditi kobilu, | ne nekakvog paklenog konja.
{55235}{55350}I to najbolju kobilu. | Takva su pravila.
{55352}{55465}Prestani, Rhamone, | dopusti mu da se natjeèe.
{55661}{55753}Reci Ishaku da se oprosti s konjem.
{55789}{55839}Sretno.
{56425}{56484}Polako.
{56486}{56532}Smiri se.
{56865}{56929}Smiri se. Kreni!
{56931}{56977}Ne.
{57806}{57887}Možeš ti to, Shatane! Trèi!
{58287}{58345}Skoèi, Shatane!
{58414}{58464}Bravo!
{59098}{59161}Hajde, Thore!
{59432}{59503}Hajde! Brže!
{59666}{59711}Makni se!
{60189}{60245}Sustignimo ih!
{60911}{60964}Brže!
{61096}{61173}Makni se!
{61903}{61952}To, Shatane!
{62183}{62243}Hajde.
{62309}{62357}Idemo!
{62524}{62594}Pustite me da proðem, Mansoore!
{63095}{63179}Imamo prednost. Hajde.
{64090}{64147}Ti to možeš, Shatane!
{64412}{64504}Ovo je naša prilika. | Sada. Hajde!
{64537}{64584}Pazi!
{64626}{64723}- Pustite me da proðem! | - Makni se.
{65475}{65527}Brže, Shatane, brže!
{65694}{65754}Hajde, Shatane!
{66274}{66349}Bravo. Uspio si.
{66600}{66800}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan  
{66826}{66937}Oprosti što te nisam poslušala, | djede, no pobijedio je!
{66939}{67001}Ljutiš se?
{67094}{67185}Neera, uspjelo ti je! Lukavice jedna!
{67187}{67264}- Uspjeli smo! | - Doði, Adene.
{67266}{67316}Uspjeli smo!
